### ISSUE TITLE
Remove obsolete line from Homebrew

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-cli#10006]
Just creating this issue here, as i need to figure out what is the right way to do that:

Following line is now obsolete/unnecessary:

https://github.com/Homebrew/homebrew-core/blob/afd1f699d17314a985ac50121b26df519cf1e4a5/Formula/azure-cli.rb#L673

It caused following issue (but also helped detect wrong location of test files):

https://github.com/Azure/azure-cli/issues/10003

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look.

**Comment by fengzhou-msft** [comment]
Code structure changed in [v2.0.68](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#july-2-2019), code under `src/command_modules/` was moved to `src/azure-cli/azure/cli/command_modules`. This line should be removed.
