### ISSUE TITLE
--service-objective  `Basic` no longer works

### ISSUE THREAD

**Issue by SeaDude** [Azure/azure-cli#10001]
What is the correct syntax for the Basic --service-objective? 
This recently stopped working in my script and instead, autoprovisions a $403/mo. SQL Server Instance with the error: `./createAzureSQLServerAndDB.sh: line 56: --service-objective: command not found`
I have to go into portal.azure.com and manually set the pricing tier.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bdd674-b454-e863-c943-9c979b466a92
* Version Independent ID: b15341f9-3f1b-00e0-a1c2-970f25a6ab03
* Content: [az sql db](https://docs.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#az-sql-db-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SeaDude** [comment]
Here is the failed `--service-objective Basic` in action: https://youtu.be/otzx-d3NhSw?t=540. Results in a ~$400 sql server instance instead of $4.99. 
Please advise on the proper syntax as the docs are not correct.
Thank you

**Comment by SeaDude** [comment]
Any status on this?

**Comment by jaredmoo** [comment]
Thank you for reporting! Can you please share a minimal repro? My assumption is that there is a syntax issue in `createAzureSQLServerAndDB.sh`.

**Comment by jeroenterheerdt** [comment]
hi @SeaDude - please respond by 1/10 otherwise we will go ahead and close this issue.

**Comment by SeaDude** [comment]
Hello,
Here is the script. Last line is the one in question.
```
#!/bin/bash

# Source:https://docs.microsoft.com/en-us/azure/sql-database/scripts/sql-database-create-and-configure-database-cli?toc=%2fcli%2fazure%2ftoc.json
# Install Azure CLI: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
# Login to Azure CLI using `az login`
# Enter variables below. Examples shown in comments "< >".
# Change script file to executable. 
# Run (on Linux) with ./createAzureServer-DB.sh > serverSetup.txt
# See video tutorial here: 

# Set Azure location <westus>
export azureLocation=

# Set Azure resource group name <rgwhatever-$RANDOM>
export resourceGroup=

# Set SQL server name <srvwhatever-$RANDOM>
export serverName=

# Set SQL server admin login and password
export adminUserName=
export adminPassword=

# IP address range to whitelist for SQL Server access <curl ifconfig.me>
export startIp=
export endIp=

# Set SQL database name <dbwhatever-$RANDOM>
export databaseName=

# Create a resource group
az group create \
	--name $resourceGroup \
	--location $azureLocation

# Create a logical server in the resource group
az sql server create \
	--name $serverName \
	--resource-group $resourceGroup \
	--location $azureLocation  \
	--admin-user $adminUserName \
	--admin-password $adminPassword

# Configure a SQL Server firewall rule to allow this IP access
az sql server firewall-rule create \
	--resource-group $resourceGroup \
	--server $serverName \
	-n initialSetupIP \
	--start-ip-address $startIp \
	--end-ip-address $endIp

# Create a SQL database
az sql db create \
	--resource-group $resourceGroup \
	--server $serverName \
	--name $databaseName \
# See https://docs.microsoft.com/en-us/azure/sql-database/sql-database-dtu-resource-limits-single-databases#standard-service-tier for pricing
	--service-objective Basic
```

**Comment by jeroenterheerdt** [comment]
@SeaDude you have a comment just above `--service-objective Basic`. This is will break your sh script and will treat `--service-object Basic` as a new command - as per the error message: `./createAzureSQLServerAndDB.sh: line 56: --service-objective: command not found`. Simply removing the comment makes the command work as expected.
