### ISSUE TITLE
list all addons and their state

### ISSUE THREAD

**Issue by smartpcr** [Azure/azure-cli#10000]
would be nice to list all add-ons on aks and if they are enabled.

**Comment by jluk** [comment]
@smartpcr thanks for the feedback, we've backlogged this request in agreement.

**Comment by jluk** [comment]
Revisiting, given this is available in the enable-addons command help text I am going to close for now. But I have opened this related issue on AKS to provide a way to retrieve all available addons programatically. https://github.com/Azure/AKS/issues/1341
```
➜  ~ az aks enable-addons -h
The behavior of this command has been altered by the following extension: aks-preview
The extension is in preview

Command
    az aks enable-addons : Enable Kubernetes addons.
        These addons are available:
            http_application_routing - configure ingress with automatic public DNS name creation.
            monitoring - turn on Log Analytics monitoring. Requires "--workspace-resource-id".
            virtual-node - enable AKS Virtual Node (PREVIEW). Requires "--subnet-name".
            azure-policy - enable Azure policy (PREVIEW).
```

**Comment by shuqiyang** [comment]
Hi 
 think the result of this cmd 'az aks enable-addons -h' is just what values of addons it can accept, not what kinds of addons is available in Azure environment.
Problem will occur, when I use it in AzureChinaCloud.
It will give the same result as Azure Global, however, features like http_application_routing is not available for AKS in AzureChinaCloud

**Comment by ozbillwang** [comment]
got answered : https://github.com/Azure/azure-cli/issues/26937#issuecomment-1642874929
