### ISSUE TITLE
az webapp up fails

### ISSUE THREAD

**Issue by davorbadrov** [Azure/azure-cli#10013]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


glob() got an unexpected keyword argument 'recursive'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 566, in execute
    raise ex
TypeError: glob() got an unexpected keyword argument 'recursive'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up -n {}`

## Environment Summary
```
Linux-5.1.15-300.fc30.x86_64-x86_64-with-fedora-30-Thirty
Python 2.7.16
Shell: bash

azure-cli 2.0.67 *

Extensions:
webapp 0.2.20

```

**Comment by panchagnula** [comment]
@davorbadrov thanks for reporting this - I believe this is because of the python version, can you check the version of python you are using by running python --version if the version is 2.* , can you install python 3.5 , that should fix the issue, in the meantime I will update the command to handle older versions of python  as well.

**Comment by davorbadrov** [comment]
@panchagnula

Thanks for the swift reply. You are right, my python version is 2.x and python 3.x is under `python3` on my machine, I've added my terminal outputs below.

```sh
$ python --version
Python 2.7.16

$ python3 --version
Python 3.7.3
```

**Comment by panchagnula** [comment]
@davorbadrov thanks for confirming, the current workaround would be to make the Python 3 your default Python version if that doesn't impact any other work for you.
