### ISSUE TITLE
Az CLI network vnet subnet delete command returns an incomplete response

### ISSUE THREAD

**Issue by TheHunter896** [Azure/azure-cli#10014]
## Describe the bug
The response from az cli is not complete, does not tell me what is using the subnet, "is in use by (nothing) and cannot be deleted" 

**Command Name**
`az network vnet subnet delete`

**Errors:**
```
Subnet rg-container-instance-subnet is in use by  and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.
```

## To Reproduce:
Execute the command 
```shell
az network vnet subnet delete --id /subscriptions/**ID**/resourceGroups/**RG-NAME**/providers/Microsoft.Network/virtualNetworks/**VNET-NAME**/subnets/**SUBNET-NAME**
```
No prerequisites 

## Expected Behavior
az cli tells me what is using the subnet

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.63 *

```

**Comment by yugangw-msft** [comment]
This is a question, rather an issue to me
@MyronFanQiu, any commands can help @TheHunter896 to find out?

**Comment by MyronFanQiu** [comment]
@TheHunter896 Hello. Which resource do you use in the subnet? I just simply checked the NIC. It will show the correct error.
```
Subnet default is in use by /subscriptions/xxxxxxxx-1bf0-4dda-aec3-cb9272f09590/resourceGroups/fanqiu-test/providers/Microsoft.Network/networkInterfaces/wessadfsadf/ipConfigurations/ipconfig1 and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.
```
It will not show all resources under the subnet, but at least, it will show one. Could you share the resource type you are using and the version of the CLI(`az --version`)?

**Comment by MyronFanQiu** [comment]
And which terminal?

**Comment by TheHunter896** [comment]
Hey thanks for the quick answer and sorry for my late answer! 
Currently I am using 2.0.69 AZ CLI and I do not know which resource I am using in the subnet since it was not built by me, I am just in charge of deleting it :')

**Comment by tjprescott** [comment]
This command returns the error from the service. The service might consider returning a more thorough error, but adding a bunch of logic to try and figure out what is using the subnet is beyond the scope of the basic delete command.

**Comment by MyronFanQiu** [comment]
@TheHunter896 This issue is a little bit strange because CLI just return the error from the service. Meanwhile, I will try to figure out is there any command can help you list all the resource used under the subnet.

**Comment by TheHunter896** [comment]
Alright thanks! I will wait no hurries!

**Comment by MyronFanQiu** [comment]
@TheHunter896 Hello. There is a workaround. You can use the command `az network vnet show -g {rg} --vnet-name {vnet} --subnet {subnetname}` to get the detail information. If your subnet is used by other service, there should be the service information under the field `ipConfigurations`

**Comment by MyronFanQiu** [comment]
@TheHunter896 You can see the id ip configuration id belonging to each service respectively. Then you can check the existence of that specific service and delete it.

**Comment by MyronFanQiu** [comment]
@TheHunter896 Hello, Did you solve your problem?

**Comment by TheHunter896** [comment]
Yes! Thanks so much, sorry for the late answer I had a little holiday :).
