### ISSUE TITLE
Need examples to clarify how all this commands are used.

### ISSUE THREAD

**Issue by pelon34** [Azure/azure-cli#10016]
This documentation is very ineffective to our customers if they are unable to reference examples with values that show how all this parameters are used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a635a197-a39e-7368-9d30-78c6e686272a
* Version Independent ID: 1a6dcecc-d86f-ea73-7452-ba8a9ba2137e
* Content: [az storage file copy](https://docs.microsoft.com/en-us/cli/azure/storage/file/copy?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Juliehzl** [comment]
@pelon34 Sorry for late response for some internal errands, we will provide examples for `az file copy` command soon. In addition, a new command for copy operation is released named `az storage copy` in azure cli 2.0.71. You can try to use the new command which will have better performance.

**Comment by yonzhan** [comment]
add to S164.
