### ISSUE TITLE
Add PrivateIPAddressVersion in LoadBalancerFrontendIpConfiguration

### ISSUE THREAD

**Issue by jaepark08** [Azure/azure-cli#10018]
**Resource Provider**
What is the Azure resource provider your feature is part of?
NRP

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
Adding a field 'PrivateIPAddreeVersion' in LoadBalancerFrontendIpConfiguration.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
V20190401

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. This should be on the master branch
of the REST API specs repo.
Azure/azure-rest-api-specs#6162

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
8/15/2019. Please let me know if you cannot meet the target date.

**Comment by MyronFanQiu** [comment]
@jaepark08 Hello. I need sometime to figure out the complexity of the feature request. I will update the result within this week. Please ping me if I miss this issue due to limited bandwidth.

**Comment by MyronFanQiu** [comment]
@jaepark08 Hi. I want to check the feature request again.

https://github.com/Azure/azure-sdk-for-python/blob/24c8eed10b543deadd9de96025a18f5813894190/sdk/network/azure-mgmt-network/azure/mgmt/network/v2019_04_01/models/_models_py3.py#L6538

what you want is that the commands `az network lb frontend-ip create/update` support a new argument called `--private-ip-address-version`. So, I assume that the `--private-ip-address` now support both IPv4 and IPv6 format as the input. Other arguments are not influenced and keep same behavior. Am I right?

**Comment by jaepark08** [comment]
> @jaepark08 Hi. I want to check the feature request again.
> 
> https://github.com/Azure/azure-sdk-for-python/blob/24c8eed10b543deadd9de96025a18f5813894190/sdk/network/azure-mgmt-network/azure/mgmt/network/v2019_04_01/models/_models_py3.py#L6538
> 
> what you want is that the commands `az network lb frontend-ip create/update` support a new argument called `--private-ip-address-version`. So, I assume that the `--private-ip-address` now support both IPv4 and IPv6 format as the input. Other arguments are not influenced and keep same behavior. Am I right?

That is correct.

**Comment by jaepark08** [comment]
@MyronFanQiu Any progress in this? Sprint 67 code complete date seems to have passed. Is this going to be in 8/13/2019 release?

**Comment by MyronFanQiu** [comment]
@jaepark08 Sorry for that. Due to low bandwidth, talked with @MikhailTryakhov, I'm working on other three issues which have high priority.

**Comment by MyronFanQiu** [comment]
@jaepark08 Hello. When I tried to test the command, I cannot create LB frontend ip configuration with IPv6 private-ip-address. Which kind of settings I should do in order to support IPv6?

**Comment by jaepark08** [comment]
You need to implement private ip address version and set it as IPv6.
If private ip address allocation method is static, the private ip address should be within the subnet that you specified.
