### ISSUE TITLE
Adding optional parameter port in "az network application-gateway probe" in create and update cli commands

### ISSUE THREAD

**Issue by abjai** [Azure/azure-cli#10027]
What is the Azure resource provider your feature is part of?
NRP

Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
Adding a optinal parameter name 'port' in 'az network application-gateway probe' create and update cli commands. This parameter is valid only for Standard_V2 and WAF_V2 sku for which proper checks at NRP are added. Current Cmdlet link: https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/probe?view=azure-cli-latest

What is the minimum API version of your service required to implement your feature?
2019-04-01

Provide a link to the location of your feature(s) in the REST API specs repo. This should be on the master branch
of the REST API specs repo.
https://github.com/Azure/azure-rest-api-specs/pull/5758 This is already merged to master.
Master link: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/applicationGateway.json

If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
Aug first week. We are targeting Sprint 67.

**Comment by haroldrandom** [comment]
Sorry to have you waiting. We will look into it.
