### ISSUE TITLE
Name parameter should contain information about valid characters and length

### ISSUE THREAD

**Issue by SvenLauterbach** [Azure/azure-cli#10020]
When executing the example command for creating a new storage account the CLI says, that the name is invalid:

az storage account create -n MyStorageAccount -g MyResourceGroup -l westus --sku Standard_LRS

MyStorageAccount is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.

The example should be updated and the name parameter should have informations about the min. and max. length and the valid characters. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92115d19-d7a0-93a8-bf2b-5126d1cddcd0
* Version Independent ID: a657f09b-e1ac-12a2-4b9c-7aaa1f0e3f5c
* Content: [az storage account](https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by zikalino** [comment]
Just reference from REST API SPECS:

https://github.com/Azure/azure-rest-api-specs/blob/2fcd0139889b923094b39a6aae015e1ea3604b68/specification/storage/resource-manager/Microsoft.Storage/stable/2019-04-01/storage.json#L2362

In addition storage account name should be globally unique.

I suggest in such cases we should follow pattern like:

mystorageaccount123

So basically here we use exactly the same name but lowercase, which indicateds only lowercase letters are allowed. Prefix "123" indicates that name has to be globally unique (e.g. has random part).

As a part of fixing it all storage samples should be updated to have the same storage account name.

**Comment by yonzhan** [comment]
add to S172
