### ISSUE TITLE
az vm create with --public-ip-address "" results in error

### ISSUE THREAD

**Issue by JustinGalbraith** [Azure/azure-cli#10037]
When executing a VM create command using --public-ip adress "" as stated in the doc results in an error. What is the correct syntax for deploying a new VM without allocating/attaching a public IP address? 

az : ERROR: az vm create: error: argument --public-ip-address: expected one argument

--public-ip-address
Name of the public IP address when creating one (default) or referencing an existing one. Can also reference an existing public IP by ID or specify "" for None.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by JustinGalbraith** [comment]
I believe I found the problem. If you are using the PowerShell ISE environment you must wrap the "" in '. The final command looks like --public-ip-address '""'

**Comment by tjprescott** [comment]
@JustinGalbraith you are correct.

**Comment by carct** [comment]
not only from PowerShell ISE environment, had this in a script and called-up the script from a PowerShell.Core Session, it worked only when i used ` --public-ip-address '""' `
