### ISSUE TITLE
Table output for `storage message get` needs ID value

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#1003]
The `id` and `popReceipt` are required values for processing a message (as they must be passed to delete to complete the message). 

```
az storage message get -q myqueue 
  DequeueCount  PopReceipt                    TimeNextVisible            Content         InsertionTime              ExpirationTime
--------------  ----------------------------  -------------------------  --------------  -------------------------  -------------------------
             2  AgAAAAMAAAAAAAAAYMV+mQMZ0gE=  2016-09-27T21:10:39+00:00  test content 1  2016-09-27T21:04:41+00:00  2016-10-04T21:04:41+00:00

```

**Comment by tjprescott** [comment]
The default table formatter suppresses id because in the vast majority of cases, id is something ridiculously long. We can use a callable table format or there may be a way to let the table formatter "know" not to suppress id in this case.
