### ISSUE TITLE
flag on example that is not explained and cant find any information about it

### ISSUE THREAD

**Issue by pelon34** [Azure/azure-cli#10033]
In your example on how to generate a sas token for a fileshare and use it to upload a file you have a flag with value: -otsv this parameter is nowhere to be found in the document and there is no explanation of what it does or if it is required or a typo.

end=`date -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`
                        sas=`az storage share generate-sas -n MyShare --account-name MyStorageAccount --https-only --permissions dlrw --expiry $end -otsv`
                        az storage file upload -s MyShare --account-name MyStorageAccount --source file.txt  --sas-token $sas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae881ef-ad75-32e6-6e64-6b526a2d9a5d
* Version Independent ID: 99971e2e-9ff6-f865-07f7-61efbcb16021
* Content: [az storage share](https://docs.microsoft.com/en-us/cli/azure/storage/share?view=azure-cli-latest#az-storage-share-generate-sas)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by zikalino** [comment]
**-otsv** is equivalent of **--output tsv** which is actually documented:

```
    --output -o           : Output format.  Allowed values: json, jsonc, none, table, tsv, yaml.
                            Default: json.
```

Perhaps it would be better to use long format **--output tsv** to make it more readable.

**Comment by Juliehzl** [comment]
Update help message in PR #10161
