### ISSUE TITLE
az eventhubs eventhub create --destination-name

### ISSUE THREAD

**Issue by bartjanson** [Azure/azure-cli#10031]
--destination-name should be one of the following: EventHubArchive.AzureBlockBlob or EventHubArchive.AzureDataLake

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa949ea-86b1-125e-e7d3-f0f88a2661ab
* Version Independent ID: c8351dbc-7358-ba5b-6757-3929a4a2b42b
* Content: [az eventhubs eventhub](https://docs.microsoft.com/en-us/cli/azure/eventhubs/eventhub?view=azure-cli-latest#az-eventhubs-eventhub-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/eventhubs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/eventhubs/_help.py)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by zikalino** [comment]
This option doesn't seem to be well documented.
I have tried some random value and is seems to have no effect.

**Comment by bartjanson** [comment]
i think it is connected to using the --enable-capture flag with the value
true

**Comment by brunomartinspro** [comment]
@zikalino how did you solve it?

**Comment by brunomartinspro** [comment]
> @zikalino how did you solve it?

never mind my bad, i thought this was used to link a storage account container..

**Comment by samuelkoppes** [comment]
We are investigating this issue, and will report back with a status updated by 11/4/2020.

**Comment by v-Ajnava** [comment]
documentation updated for --destination--name, can you please upgrade to latest CLI and try again ? 
--destination-name             : Name for capture destination, should be EventHubArchive.AzureBlockBlob.

**Comment by Saglodha** [comment]
Hi @bartjanson, thank you for bringing this up. We would investigate this internally and update the documentation accordingly.

**Comment by bartjanson** [comment]
documentation looks good now, both in az cli and on the help page for create..

**Comment by SaurabhSharma-MSFT** [comment]
@bartjanson  I believe this issue has been fixed and can be closed. Please let us know.
