### ISSUE TITLE
massive list of "list key" operations when using `--account-name`

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#10042]
I thought `--account-name` was meant to use the new style of access to storage accounts that didn't use the storage keys. Why is my activity log full of "List key" calls while my scripts are running?

**Comment by tjprescott** [comment]
If you provide --account-name and no key or connection string, the CLI will retrieve the account key behind the scenes. This has been the behavior since the CLI's beginning. @limingu how does one default to the OAuth pattern?

**Comment by colemickens** [comment]
It looks like I needed to have specified `--auth-mode login` on my requests.

The docs for this specifically refer to `--auth-mode key` as "legacy", and manage to side-step saying what the default behavior is... https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-script#call-cli-commands-using-azure-ad-credentials
