### ISSUE TITLE
storage account naming guidance

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#10041]
This is a general question. Somehow, storage accounts are still required to be globally unique, and still only allowed to be 24 characters long. Meanwhile, there are locations with names that are 20 characters long. Say you are building images, which must be homed to a location, what is suggested as a naming scheme?

I can't think of anything better than finding some hashing function that outputs to 24 chars (...), and feed it a subscription id, location, and "unique name", but those output names are all going to be unreadable and generally nonsensical. Other platforms at least give canonical, short names that can be reliably used for naming in such scenarios.

This must be a wide-spread "issue". What are others doing?

**Comment by colemickens** [comment]
DigitalOcean, Packet, and IBM Cloud use consistently-four-character names. They and the rest that I've checked have neither such incredibly short storage account names, nor do they require global uniqueness.

**Comment by zikalino** [comment]
I think this discussion should not only include storage account names, there are other Azure resources that require names to be globally unique.

I am for instance concerned about examples, if you run examples that require unique name out of the box, most likely it will fail.

**Comment by colemickens** [comment]
Here's the thing, I (feel like I) shouldn't have to do any of this anyway:

Managed disks takes care of storage accounts under the scenes... and yet... it can't replicate a blob from another location, and I still can't make images public across subscriptions. So instead, I have to do this all myself, maintain the scripts, and distribute them to users so they can then replicate blobs and construct their own images in their subscriptions... 

```
[azureuser@xxnixos-22711:~/code/nixpkgs/nixos/maintainers/scripts/azure/v2]$ cat * | wc -l
139
```

**Comment by zikalino** [comment]
@colemickens regarding sharing images across subscriptions, you could use Shared Image Gallery **az sig**. will that help you?

**Comment by colemickens** [comment]
Not unless they can be made public, no.

**Comment by colemickens** [comment]
Just allowing MD creation from arbitrary blobs would cut out a lot of
frustration. Storage accounts are a nightmare and there's no reason I
should need to ask end users go through the hassle of managing storage
accounts just to be able to create a MD that ends up replicating the blob
transparently anyway. Typing it out makes me a feel a bit crazy. I have to
go through all of the trouble of scripting naming and creating a storage
account and container, just to replicate a blob, just to create an MD and
have the platform replicate the blob again, at which point, the storage
account is entirely unneeded again. Such a headache for what should be so
simple.

**Comment by colemickens** [comment]
It actually appears that Managed Disks + SIG might support exactly what I need to avoid managing storage accounts myself, but there's further clarification needed. See: https://github.com/Azure/azure-cli/issues/10192

**Comment by colemickens** [comment]
Note: SIG names also have to be unique... At least it's only subscription-wide, I guess, instead of globally like storage accounts.

**Comment by colemickens** [comment]
lol. can't use dashes in the gallery names either. It really just never ends, does it, jumping through random annoying hoops just to do something like create a custom image in Azure. Just. Never. Ends.

**Comment by yonzhan** [comment]
@colemickens was your issue resolved?

**Comment by jiasli** [comment]
I think the limitation on Storage Account name is out of the scope of Azure CLI. 

The reason why it has to be [globally unique](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-create?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=azure-portal#create-a-storage-account) is because the name is used as part of the [domain name](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction#storage-accounts) `http://mystorageaccount.blob.core.windows.net` to identity the Storage Account.

I checked the feedback forum and did see this post: [Increase Storage Account Name Length from Max of 24 Characters](https://feedback.azure.com/forums/217298-storage/suggestions/36884797-increase-storage-account-name-length-from-max-of-2). You may vote on this post to get Storage team noticed. Thank you for your understanding.
