### ISSUE TITLE
Cosmos DB cannot update throughput DTU at database level

### ISSUE THREAD

**Issue by Dave76** [Azure/azure-cli#10048]
Although you can set the throughput when you create a database using:

`az cosmosdb database create --throughout 500`

If you run the create command again you will get an error stating the resource already exists, which makes sense. So we need something like:

`az cosmosdb database update --throughput 500`

**Comment by tjprescott** [comment]
There are two issues here:
1. Missing an update command (feature request)
2. A create command is not idempotent, which is violation of the CLI standards. https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#standard-command-types

**Comment by Dave76** [comment]
Good point. 

Ideally, i should just be able to run the create command again with a new throughput, and it will know the database already exists and just update the throughput.  

Otherwise, I need to check for existence first, then run either create or update, which is more difficult. (obviously not impossible):

```
databaseExists=$(az cosmosdb database exists --resource-group $resourceGroup --name $cosmos --db-name $cosmos_database )
if [ "$databaseExists" = false ]; then
   echo "Creating cosmos database [$cosmos_database]"
   out=$(az cosmosdb database create --resource-group $resourceGroup --name $cosmos --db-name $cosmos_database --throughput $cosmos_throughput)
   echov "$out"
else
    echo "Cosmos database [$cosmos_database] exists"
    ## run update command (which currently does not exist) 
fi
```

**Comment by shurd** [comment]
Hi @Dave76, thank you for raising this issue. We are currently working on changing the way databases and collections are accessed by the CLI. Currently, the CLI uses "azure-cosmos", which is a data-plane python package. Soon, the CLI will instead access collections and databases through our resource provider.

When this change is made, you will be able to update database level throughput. The target date for completion of this work item (416566) is September. We will keep you updated as work progresses.

**Comment by Dave76** [comment]
Thanks @shurd. Please let me know when this work item is complete.

**Comment by shurd** [comment]
Hi @Dave76, in version 2.0.71 of the CLI, we released a preview version of the new database and collection management. As a part of this change, you can update database level throughput.

Creating a MongoDB database with shared throughput:
```
az cosmosdb mongodb database create --account-name {account_name} -n {database_name} --throughput 500 -g {resource_group}
```

Updating throughput:
```
az cosmosdb mongodb database throughput update -a {account_name} -n {database_name} -g {resource_group} --throughput 600
```

If you run the same "create" command and attempt to update throughput via that command, you will get a bad request exception as we do not allow throughput update through that codepath. Running the same exact "create" command twice (with no throughput update) no longer throws an exception.
