### ISSUE TITLE
app gateway: use app service

### ISSUE THREAD

**Issue by gjdonkers** [Azure/azure-cli#10055]
How can I turn on the checkbox for Use App Service when creating a http-settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2bf0577-695e-a054-b82d-894ff3cdf05d
* Version Independent ID: 66c0304d-8588-b64c-cb6b-fce366190db0
* Content: [az network application-gateway http-settings](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/http-settings?view=azure-cli-latest#az-network-application-gateway-http-settings-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@gjdonkers Hello. Thanks for opening this issue. I want to know more about this issue. What is `checkbox`? Could you give me an example or link?

**Comment by gjdonkers** [comment]
When adding an HTTP Settings to an Application Gateway though the interface you can use the checkbox __Use for App Service__, see the attached image. How can I do this with the Azure CLI?
<img width="633" alt="Schermafbeelding 2019-07-29 om 09 42 09" src="https://user-images.githubusercontent.com/5495117/62030413-4ed94600-b1e5-11e9-8d50-fa3a771b0097.png">

**Comment by MyronFanQiu** [comment]
@gjdonkers Hello. Sorry for the delay due to limited bandwidth. I checked the behavior of this checkbox. It seems that it will create a probe and enable it, right? Based on the SDK perspective, I found one field called `probe_enable`, but I'm not sure whether it's corresponding behavior or not.

**Comment by surajmb** [comment]
@gjdonkers The "Use for App Service" option is a UI only option which does two things
1. Enables "Pick hostname from backend address"
2. Enables Custom Probe

In PowerShell or CLI, we don't have that as a single switch, hence you can use the following CLI switches to achieve them

[--host-name-from-backend-pool {false, true}]
[--probe]

For example, az network application-gateway http-settings update -g MyResourceGroup --gateway-name MyAppGateway -n MyHttpSettings --probe MyNewProbe --host-name-from-backend-pool true

**Comment by MyronFanQiu** [comment]
@gjdonkers Hello. Did you solve your problem?

**Comment by gjdonkers** [comment]
Sorry for my late response. This will solve my problem! Thank so much!
