### ISSUE TITLE
Expiration date needs to be converted to GMT

### ISSUE THREAD

**Issue by romanows** [Azure/azure-cli#10050]
The expiration date in the example for "az storage container generate-sas" is not generated correctly on recent Ubuntu releases (and I expect most Linux distros).  The problem is that the date command on this system may output time in the user's timezone and not in UTC.  The fix is to use the "-u" flag to convert local time into UTC.  So the correct command-line for the default Ubuntu install would be:

    end=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`

and not:

    end=`date -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcba5ed-e693-6345-2c1b-c17422d7b8f9
* Version Independent ID: 58297400-b777-6868-1687-0af3a512a16f
* Content: [az storage container](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Juliehzl** [comment]
You can run```echo $end``` to get the $end value in Ubuntu after running ```export end=`date -d "30 minutes" '+%Y-%m-%dT%H:%MZ'```. It should be the UTC time after 30 minutes from now. Can you check again?

**Comment by romanows** [comment]
Checked again, same outcome, the original command is buggy on platforms that are not already set to UTC.

If you are trying this command yourself and succeeding, my guess is that your platform is already set to UTC.  You can check this by typing `date "+%Z"`.  If the output is `UTC` then you will not notice the bug.  But not everyone's platform runs on UTC time and they will all encounter the bug in hard-to-debug ways.

A Linux platform running your command is going to give you the time 30 minutes from now in the configured timezone.  For me, this is "EDT" as shown by `date "+%Z"`.  Because you put the "Z" on the timezone string, Azure will definitely interpret this EDT time in the GMT/UTC timezone, which is a source of subtly buggy behavior.
