### ISSUE TITLE
az aks get-verions missing preview tags

### ISSUE THREAD

**Issue by HannoSolo** [Azure/azure-cli#10059]
**Describe the bug**
In the latest version of Azure Cli (2.0.69) when I execute the command - az aks get-versions --location westeurope --output table - the output does not tag versions as being "preview"

C:\Users\v-hater>az aks get-versions --location westeurope --output table
Unable to load extension 'aks-preview'. Use --debug for more information.
KubernetesVersion    Upgrades
-------------------  ------------------------
1.14.3               None available
1.14.1               1.14.3
1.13.7               1.14.1, 1.14.3
1.13.5               1.13.7, 1.14.1, 1.14.3
1.12.8               1.13.5, 1.13.7
1.12.7               1.12.8, 1.13.5, 1.13.7
1.11.10              1.12.7, 1.12.8
1.11.9               1.11.10, 1.12.7, 1.12.8
1.10.13              1.11.9, 1.11.10
1.10.12              1.10.13, 1.11.9, 1.11.10

C:\Users\v-hater>az --version
azure-cli                         2.0.69

**To Reproduce**
Install version 2.0.69 of Azure Cli and execute the command - az aks get-versions --location westeurope --output table

**Expected behavior**
In version 2.0.64 the output correctly shows the "preview" tags:

C:\Users\v-hater>az --version
azure-cli                         2.0.64

C:\Users\v-hater>az aks get-versions --location westeurope --output table
The behavior of this command has been altered by the following extension: aks-preview
KubernetesVersion    Upgrades
-------------------  ----------------------------------------
1.14.3(preview)      None available
1.14.1(preview)      1.14.3(preview)
1.13.7               1.14.1(preview), 1.14.3(preview)
1.13.5               1.13.7, 1.14.1(preview), 1.14.3(preview)
1.12.8               1.13.5, 1.13.7
1.12.7               1.12.8, 1.13.5, 1.13.7
1.11.10              1.12.7, 1.12.8
1.11.9               1.11.10, 1.12.7, 1.12.8
1.10.13              1.11.9, 1.11.10
1.10.12              1.10.13, 1.11.9, 1.11.10

**Environment summary**
Azure CLI 2.0.69 installed on Windows OS

**Additional context**
This will cause problems if you don't see the preview tag and update your production AKS cluster to the latest version

**Comment by seanmck** [comment]
Fixed by #10022
