### ISSUE TITLE
app-gateway: SSL Certificate from KeyVault

### ISSUE THREAD

**Issue by gjdonkers** [Azure/azure-cli#10054]
How can I add a SSL from the KeyVault. Using the ID from the KeyVault with `--ssl-cert` is not working. Can you add this to the examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dce00db-c8d7-9b93-7ac8-114a500a6a34
* Version Independent ID: 14a03192-a30b-d273-fa11-32413868a5fa
* Content: [az network application-gateway http-listener](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/http-listener?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
This is currently not supported in CLI. Please follow issue #8244.
