### ISSUE TITLE
The --condition and the --action-group options need more information. 

### ISSUE THREAD

**Issue by carlbrochu** [Azure/azure-cli#10078]
The --condition and the --action-group options need more information.  I am gettting a "Badrequest" error when setting something which should be valid for action-group and condition doesn't seem to work with an "and".  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d97968df-72c9-e50c-d5b1-54562c1bdef7
* Version Independent ID: 0cde4f15-6464-3106-b787-3ee37c7de0ee
* Content: [az monitor metrics alert](https://docs.microsoft.com/en-us/cli/azure/monitor/metrics/alert?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@MyronFanQiu  planned after Ignite.

**Comment by MyronFanQiu** [comment]
@carlbrochu Hello. Could you share the detail of `--condition`? It should work with `and`.

**Comment by MyronFanQiu** [comment]
@carlbrochu Hello. Are you still there? Is it possible to share an example to us so that we can investigate this issue deeply?

**Comment by carlbrochu** [comment]
I was trying to create an Azure monitor and passing these arguments just doesn't seem to work on the cli portion.  The support for an "And" statement seems to be missing.

**Comment by MyronFanQiu** [comment]
@carlbrochu Hi. I just tried the command 
```
az monitor metrics alert create -n alertmytest -g test --scopes /subscriptions/xxxxx/resourceGroups/feng-cli-rg/providers/Microsoft.Storage/storageAccounts/xxxx --condition "avg SuccessE2ELatency > 250 where ApiName includes GetBlob and ApiName includes PutBlob" --description "mytest"
```
and it works.
`and` is used in multiple dimensions instead of multiple condition. You can specify extra `--condition` to add more than one condition in one command.
If you still meet error, can you share the example of your command and I can have a try.

**Comment by MyronFanQiu** [comment]
@carlbrochu I cannot produce this issue and it's a little bit out of date. I closed this one first. If you still have any issue, don't hesitate and feel free to open a new one.
