### ISSUE TITLE
Accomodate WAF V2 payload for SSL termination.

### ISSUE THREAD

**Issue by Sudharma** [Azure/azure-cli#10072]
The API for powershell is updated with new WAF V2 payloads , identity and sslcerts with keyvault secret id. Please update the same for Azure Cli

 Powershell.
https://docs.microsoft.com/en-us/azure/application-gateway/configure-keyvault-ps

Azure Cli
https://docs.microsoft.com/en-us/cli/azure/network/application-gateway?view=azure-cli-latest#az-network-application-gateway-create

possible duplicate of . https://github.com/MicrosoftDocs/azure-docs/issues/35845
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yugangw-msft** [comment]
CC @MyronFanQiu

**Comment by MyronFanQiu** [comment]
@Sudharma Hello. Working on it. https://github.com/Azure/azure-cli/issues/8244
