### ISSUE TITLE
create action group with azure function receiver with Azure CLI

### ISSUE THREAD

**Issue by ferantivero** [Azure/azure-cli#10076]
**Is your feature request related to a problem? Please describe.**
when `az monitor action-group update    -n $ACTIONGROUP_NAME    -g $RESOURCE_GROUP    --add-action azureFunction <<args>> ` it ends the execution with an error

> ValueError: usage error: the type "azureFunction" is not recognizable.

**Describe the solution you'd like**
Az CLI adds support for Azure Function receiver

**Describe alternatives you've considered**
using azure REST APIs for the moment: https://docs.microsoft.com/en-us/rest/api/monitor/actiongroups/createorupdate

**Additional context**
N/A

**Comment by MyronFanQiu** [comment]
@ferantivero Hello. I roughly checked the REST link. Could you set Azure Function receiver using REST API for now? I just saw `azureAppPushReceivers` in the sample.

**Comment by ferantivero** [comment]
@MyronFanQiu yes, you could:

```json
{
    "location": "Global",
    "tags": {},
    "properties": {
        "groupShortName": "429s-ag",
        "enabled": true,
        "emailReceivers": [],
        "smsReceivers": [],
        "webhookReceivers": [],
        "itsmReceivers": [],
        "azureAppPushReceivers": [],
        "automationRunbookReceivers": [],
        "voiceReceivers": [],
        "logicAppReceivers": [],
        "azureFunctionReceivers": [
            {
                "name": "ACTION_NAME",
                "functionAppResourceId": "/subscriptions/SUBSCRIPTION_ID/resourceGroups/RESOURCE_GROUP/providers/Microsoft.Web/sites/FUNCAPP_NAME",
                "functionName": "FUNCTION_NAME",
                "httpTriggerUrl": "https://FUNCAPP_NAME.azurewebsites.net/api/FUNCTION_NAME",
                "useCommonAlertSchema": true
            }
        ],
        "armRoleReceivers": []
    },
    "identity": null
}
```

**Comment by MyronFanQiu** [comment]
@ferantivero  Thanks.

**Comment by yonzhan** [comment]
add to S164.

**Comment by soumya6541** [comment]
Is it feasible to create action group with action as Azure function using az command? I have tried but it is throwing below error,
usage error: the type "azureFunctionReceivers" is not recognizable.

**Comment by MyronFanQiu** [comment]
@soumya6541 @ferantivero  sorry for the delay. you should be able to add azure function by `--add-action azurefunction NAME FUNCTION_APP_RESOURCE_ID FUNCTION_NAME`. Please have a try now.

**Comment by ShijunLu** [comment]
> @MyronFanQiu yes, you could:
> 
> ```json
> {
>     "location": "Global",
>     "tags": {},
>     "properties": {
>         "groupShortName": "SHORT_NAME",
>         "enabled": true,
>         "emailReceivers": [],
>         "smsReceivers": [],
>         "webhookReceivers": [],
>         "itsmReceivers": [],
>         "azureAppPushReceivers": [],
>         "automationRunbookReceivers": [],
>         "voiceReceivers": [],
>         "logicAppReceivers": [],
>         "azureFunctionReceivers": [
>             {
>                 "name": "ACTION_NAME",
>                 "functionAppResourceId": "/subscriptions/SUBSCRIPTION_ID/resourceGroups/RESOURCE_GROUP/providers/Microsoft.Web/sites/FUNCAPP_NAME",
>                 "functionName": "FUNCTION_NAME",
>                 "httpTriggerUrl": "https://FUNCAPP_NAME.azurewebsites.net/api/FUNCTION_NAME",
>                 "useCommonAlertSchema": true
>             }
>         ],
>         "armRoleReceivers": []
>     },
>     "identity": null
> }
> ```



> @MyronFanQiu yes, you could:
> 
> ```json
> {
>     "location": "Global",
>     "tags": {},
>     "properties": {
>         "groupShortName": "SHORT_NAME",
>         "enabled": true,
>         "emailReceivers": [],
>         "smsReceivers": [],
>         "webhookReceivers": [],
>         "itsmReceivers": [],
>         "azureAppPushReceivers": [],
>         "automationRunbookReceivers": [],
>         "voiceReceivers": [],
>         "logicAppReceivers": [],
>         "azureFunctionReceivers": [
>             {
>                 "name": "ACTION_NAME",
>                 "functionAppResourceId": "/subscriptions/SUBSCRIPTION_ID/resourceGroups/RESOURCE_GROUP/providers/Microsoft.Web/sites/FUNCAPP_NAME",
>                 "functionName": "FUNCTION_NAME",
>                 "httpTriggerUrl": "https://FUNCAPP_NAME.azurewebsites.net/api/FUNCTION_NAME",
>                 "useCommonAlertSchema": true
>             }
>         ],
>         "armRoleReceivers": []
>     },
>     "identity": null
> }
> ```

Hi Ferantivero, may I know what is the FUNCAPP_NAME ? I cannot find document about this. If I what to add a azure function in my project to this action group, how should I find the functionAppResourceId? 
Thanks
