### ISSUE TITLE
Issue in pyhthon with "az network application gateway"

### ISSUE THREAD

**Issue by EmaOnLine** [Azure/azure-cli#10073]
## Describe the bug

**Command Name**
`az network application-gateway update`

**Errors:**
```
pop from empty list
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 578, in execute
    raise ex
cli/core/commands/__init__.py, ln 636, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 629, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.6/site-packages/six.py, ln 693, in reraise
    raise value
...
cli/core/commands/arm.py, ln 525, in handler
    set_properties(instance, expression, force_string)
cli/core/commands/arm.py, ln 806, in set_properties
    name, path = _get_name_path(key)
cli/core/commands/arm.py, ln 968, in _get_name_path
    return pathlist.pop(), pathlist
IndexError: pop from empty list
```

## To Reproduce:
az network application-gateway update -n $appgw -g $rg --set identity.type='UserAssigned' identity.userAssignedIdentities=$identityId

- _Put any pre-requisite steps here..._
- `az network application-gateway update -n {} -g {} --set {} {} {}`

## Expected Behavior
Excute the command without errors
## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.69

Extensions:
interactive 0.4.3

```

**Comment by yugangw-msft** [comment]
CC @MyronFanQiu

**Comment by MyronFanQiu** [comment]
@EmaOnLine Hello, I did the test, however, I met another error. 
```
Unable to build a model: Unable to deserialize response data. Data: ddxx, {ManagedServiceIdentityUserAssignedIdentitiesValue}, AttributeError: 'str' object has no attribute 'items', DeserializationError: Unable to deserialize response data. Data: ddxx, {ManagedServiceIdentityUserAssignedIdentitiesValue}, AttributeError: 'str' object has no attribute 'items'
Traceback (most recent call last):
  File "C:\Codes\azure-cli-dev-folder\azure-cli\python3\lib\site-packages\msrest\serialization.py", line 1450, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "C:\Codes\azure-cli-dev-folder\azure-cli\python3\lib\site-packages\msrest\serialization.py", line 1497, in deserialize_dict
    return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
AttributeError: 'str' object has no attribute 'items'
```
Similar with this issue https://github.com/Azure/azure-cli/issues/10011. I will check with our team to confirm its usage and limitation. 
Meanwhile, could you please give me more detail information so that I can reproduce your issue? I use this command, I'm not sure whether the format or type of the ` identity.userAssignedIdentities ` is correct or not.
```
az network application-gateway update -n ffsdfsdf -g fanqiu-test --set identity.type='UserAssigned' identity.userAssignedIdentities='ddxx'
```

**Comment by EmaOnLine** [comment]
Hello @MyronFanQiu, 
I need to assign an identity to an existing application gateway in order to access a vault key.
All the elements of the environment are configured, I just need this step. The identity is already configured in the key vault.
I made the following attempts but always having the error above as a result:
- do not use variables passing values directly
- execute the command from the command line instead of the script
- execute the command directly from the Azure command line

I suspect that the problem is precisely when filling in the `identity.userAssignedIdentities` field. I used it in every way, even those I knew were wrong, but the result never changed. This is why I think it could be a bug in the field ... but I hope it's my mistake instead :-)

Thanks for the support

**Comment by MyronFanQiu** [comment]
@EmaOnLine Hi. I discussed with my team member. We have a document talking about this.
https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#using-the-generic-update-arguments
You can check the doc and try something like this below as a workaround. 
--set identity="{\"type\": \"UserAssigned\", \"userAssignedIdentities\": { \"/subscriptions/xxxxxxxx-xxxx-4dda-aec3-xxxxxxxxxxxx/resourcegroups/china/providers/Microsoft.ManagedIdentity/userAssignedIdentities/china-id\": { \"clientId\": \"xxxxxxxxx-2df7-4841-9c9a-xxxx\", \"principalId\": \"xxxxxxx-f7d8-40c6-98bf-xxxxxxxxxxx\"}}}

**Comment by EmaOnLine** [comment]
Hi @MyronFanQiu ,
I read the documentation you gave me and I changed the command.
It returns the following error:
**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
python3.6/site-packages/msrest/serialization.py, ln 1288, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
...
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

**Comment by MyronFanQiu** [comment]
@EmaOnLine I will check the swagger file. @zikalino  Could you please also take a look?

**Comment by yugangw-msft** [comment]
@EmaOnLine, it would be helpful if you could run the command with `--debug` and share with us the trace.

**Comment by EmaOnLine** [comment]
@yugangw-msft hi, here the result of command with debug
[az-network-appliaction-update-debug.log](https://github.com/Azure/azure-cli/files/3450579/az-network-appliaction-update-debug.log)

**Comment by yugangw-msft** [comment]
Looks like the double quotes used for valid json payload were not escaped, could you please escape it? If this turns out messy, you can check out [tips](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues), particularly the 7th point of using a file
```
--set identity="{\"type\":\"UserAssigned\"..."
```

**Comment by MyronFanQiu** [comment]
@EmaOnline Hello. I created a PR to support this in a more intuitive way.

**Comment by EmaOnLine** [comment]
hi @yugangw-msft , same issue also with double quotes...

As workaround, i have configured script in powershell, and work it. In this case, is more flexible than AZ Cli...
If you want to find a solution like "exercise", we can leave the thread open and I can do the tests. As you prefer.

Thanks for the support

**Comment by yugangw-msft** [comment]
@EmaOnLine, I tried out the command just now. As long as the quote gets escaped, it will work, though I would agree it is a bit hard to get it right through the generic updater .
```
az network application-gateway update -g china -n china-ag --set identity="{\"type\": \"UserAssigned\", \"userAssignedIdentities\": { \"/subscriptions/xxxxxxxx-1bf0-4dda-aec3-cb9272f09590/resourcegroups/china/providers/Microsoft.ManagedIdentity/userAssignedIdentities/china-id\": { \"clientId\": \"xxxxxxxx-2df7-4841-9c9a-47f7c08eaa58\", \"principalId\": \"xxxxxxxx-f7d8-40c6-98bf-9df39740444d\"}}}
```
