### ISSUE TITLE
webapp:Need only Backup Command

### ISSUE THREAD

**Issue by developerprashantsinghal** [Azure/azure-cli#10070]
az is missing in triggering already configured backup for webapp without SAS url. Currently we can trigger backup using SAS url "az webapp config backup create" or  "az webapp config backup update" but this command will also create schedule for backup which is not required to me.

I need an az command to trigger already configured webapp backup only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae944b4-aa1b-4bc7-5f3c-1e645c792e86
* Version Independent ID: 06e361cb-035c-0b20-1b85-6532e551a35a
* Content: [az webapp config backup](https://docs.microsoft.com/en-us/cli/azure/webapp/config/backup?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp/config/backup.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/backup.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
@Nking92 & @btardif this is a request for a new command, can you guys review & answer if this is something can & should support. Thank you.

**Comment by Nking92** [comment]
Hi @developerprashantsinghal 

I believe "az webapp config backup create" does what you would like. That command will create a backup on-demand, independent of your backup schedule. On the other hand "az webapp config backup update" is designed to configure the backup schedule, so please don't use that command for an on-demand backup.

**Comment by panchagnula** [comment]
thanks @Nking92 , @developerprashantsinghal can you try the command Nick suggested & let us know that it answers your question?

**Comment by panchagnula** [comment]
Closing this due to lack of response for 12 days

**Comment by developerprashantsinghal** [comment]
i can not use sas token due to some internal policy. For now as my webapp backup is already configured manually so i just reschedule the backup and this action also trigger backup of my webapp. 
 ############################################################

$SchedulerDetails=az webapp config backup show --resource-group "myResourcegroup" --webapp-name "myWebapp" --subscription "mySub"
#parsing json data
$FrequencyOfBackup= $SchedulerDetails | findstr "frequencyInterval"

$Days=$FrequencyOfBackup |  ForEach-Object { $_ -replace '    ' } | ForEach-Object { $_ -replace '"' } | ForEach-Object { $_ -replace ':' } | ForEach-Object { $_ -replace ',' } | ForEach-Object { $_ -replace 'frequencyInterval ' }

# Triggering backup of webapp by rescheduling 
if($Days -eq "31"){
az webapp config backup update --resource-group "myResourcegroup" --webapp-name "myWebapp" --subscription "mySub" --frequency "30d" --retention "0"

echo "Backup frequency set for 30 days and indefinite retention"
}

if($Days -eq "30"){

az webapp config backup update --resource-group "myResourcegroup" --webapp-name "myWebapp" --subscription "mySub" --frequency "31d" --retention "0"

echo "Backup frequency set for 31 days and indefinite retention"
}

else
{
az webapp config backup update --resource-group "myResourcegroup" --webapp-name "myWebapp" --subscription "mySub" --frequency "30d" --retention "0"

echo "Backup frequency set for 30 days and indefinite retention under else condition"
}

**Comment by prajyot-joshi-kr** [comment]
Has anyone encountered **"sizeInBytes": 0** issue while executing the az webapp config backup create ? which causes the backup to fail[](https://github.com/Azure/azure-cli/issues/15240)
