### ISSUE TITLE
Set name for restore point/snaphot

### ISSUE THREAD

**Issue by Lelelo1** [Azure/azure-cli#10080]
Before doing potential dangerous things or having successfully set up something important on an Azure VM - I would like to name the specific snapshot/restore point I manually trigger - so that I can easier understand what the state of the vm where in that snapshot/restore point in the future. 
I could not found any azure cli command for how to manually create a restore point - but in the portal in VM it is created like so:

![RestoreNow](https://user-images.githubusercontent.com/42244983/61995365-d90b9800-b087-11e9-8a89-04d30ccc7c25.png)

**Describe the solution you'd like**
After clicking `Backup now` - entering the following page: 
![RetainBackupEnterName](https://user-images.githubusercontent.com/42244983/61995633-3a813600-b08b-11e9-94fa-86f88758253d.png)
... There could be and entry as well  where one could optionally give a name/description to the restore point.

And/or: Create cli command like `az backup recoverypoint create`. Add a `-name` flag with the command.

And a column for name/description in the list:
![NameColumn](https://user-images.githubusercontent.com/42244983/61995775-1b83a380-b08d-11e9-9c42-d9df1002ba84.png)

**Describe alternatives you've considered**
Manually keeping a note where I describe the state of the vm - with the time stamp of the restore point. Or create a azure table doing the same thing.

**Comment by pvrk** [comment]
Could not make this in the next semester planning but acknowledging the feedback. Added this to our backlog request. Closing this issue as a feature-request in backlog.
