### ISSUE TITLE
/usr/bin/python: No module named azure (Python 3.5 from Homebrew)

### ISSUE THREAD

**Issue by kostrse** [Azure/azure-cli#1008]
When Python 3.5 installed from Homebrew, and **azure-cli** installed by the Homebrew's **pip3**, the **az** launcher script tries to run on system python 2.7.

```
$ az
/usr/bin/python: No module named azure
```

Direct command `python3 -m azure.cli` works fine.

**Comment by aribornstein** [comment]
What was the solution i'm seeing the same behaivor
