### ISSUE TITLE
Installing on OSX tries to modify root's bash completion, not the user's

### ISSUE THREAD

**Issue by migueldeicaza** [Azure/azure-cli#1009]
This happens after I try to install it:

```
Installation successful.
Enable shell/tab completion? [y/N]: y
Unable to enable tab completion. No '/var/root/.bashrc' or '/var/root/.bash_profile' file found.
Run the CLI with /usr/local/bin/az --help
```

**Comment by derekbekoe** [comment]
Thanks for the feedback.

Looks like you ran the curl install command with sudo, i.e. `curl -L https://aka.ms/InstallAzureCli | sudo bash`.

You're correct, currently we attempt to modify the rc file for the current user. If the file doesn't exist, you get that error message.

It'd be hard to guess which user tab completion should be enabled for if the initial attempt fails.

I have commented on a related issue with a solution that can be implemented - https://github.com/Azure/azure-cli/issues/939#issuecomment-250298058.
