### ISSUE TITLE
Azure Devops Release Pipeline task named 'Azure App Service Deploy' is skipping some .dll files

### ISSUE THREAD

**Issue by bhanush3** [Azure/azure-cli#10093]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Azure Devops Release Pipeline task named 'Azure App Service Deploy' is skipping some .dll files

**To Reproduce**
create new release in release pipeline

**Expected behavior**
should deploy all .dll in bin folder or subfolder

**Environment summary**
I am deploying a .net API App using task version 4.*. Package or Folder option: "$(System.DefaultWorkingDirectory)/**/*.zip"
All other option in this task is left blank. There are no other tasks in release pipeline. In content of .zip package I can see there are some folders under path 'Content\D_C\a\1\s\project\Api\app.Api\obj\Debug\Package\PackageTmp\bin' named de, es, fr, it, ja, ko, ru and these folders have some .dll files which needs to be isntalled or updated. When I run Release pipeline it shows that it has successfully deployed the API App but I see logs I find out that it is not installing .dlls in de, es, fr, it, ja, ko, ru folders and also skipping some .dlls in bin folder which is breaking the API app in result.

**Additional context**

**Comment by yugangw-msft** [comment]
Assuming you are using ADO CLI, please open the issue at https://github.com/Azure/azure-cli-extensions/issues
