### ISSUE TITLE
You do not have the required permissions needed to perform this operation

### ISSUE THREAD

**Issue by pvnguyen123** [Azure/azure-cli#10095]
## Describe the bug

**Command Name**
`az storage blob upload-batch`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

<Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the 
Time:2019-07-30T15:20:05.3197074Z</Message><AuthenticationErrorDetail>Request date header too old: 'Tue, 30 Jul 2019 06:25:26 GMT'</AuthenticationErrorDetail></Error>.

'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 132, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload-batch -s {} -d {} --account-name {}`

## Environment Summary
```
Linux-4.19.55-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.69 *

```

**Comment by pvnguyen123** [comment]
Using Ubuntu WSL2, this happens after computer comes out of sleep mode.  Restarting the PC seems to fix the issue.  Is the time stamp caching on the CLI?

**Comment by Juliehzl** [comment]
@pvnguyen123 It looks just your environment (WSL2), is providing an old time to the CLI. I think nothing goes wrong and I will close this issue now. If you have any question, pls feel free to reopen it.
