### ISSUE TITLE
500 Error for AZ AKS create preview 

### ISSUE THREAD

**Issue by ChrisRG711** [Azure/azure-cli#10096]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When trying to use AZ AKS Create to create a new AKS cluster with VMSS using the CLI in preview we only get the following message
WARNING: The behavior of this command has been altered by the following extension: aks-preview
ERROR: request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with 
url: /subscriptions/xxx/resourceGroups/NSNonProdCluster/providers/Microsoft.ContainerService/managedClusters/NSNonProd
Cluster?api-version=2019-04-01 (Caused by ResponseError('too many 500 error responses',))

**To Reproduce**
Here is the command we run. 

$SubnetId= "/subscriptions/xxx/resourceGroups/NSTestNework/providers/Microsoft.Network/virtualNetworks/xxx/subnets/xxx"
$NodeSize="Standard_D3_v2"
$DockerBridgeCidr="172.17.9.1/16"
$ResourceGroup = 'xxx'
$Location = 'Centralus'
$Cluster="xx"
$ServiceCidr="10.3.12.0/23"
$DNSServiceIP="10.3.12.10"
# Deploy a cluster with RBAC
az aks create --name $Cluster --resource-group $ResourceGroup --location $Location --enable-rbac --aad-server-app-id xxx --aad-server-app-secret xxxx --aad-client-app-id xxx --aad-tenant-id xxx --node-vm-size $NodeSize --node-count 3 --enable-vmss --enable-cluster-autoscaler --min-count 3 --max-count 6 --max-pods 40 --docker-bridge-address $DockerBridgeCidr --service-cidr $ServiceCidr --dns-service-ip $DNSServiceIP --vnet-subnet-id $SubnetId --network-plugin azure --service-principal xxx --client-secret xxxxxxx

**Expected behavior**
The AZ AKS CREATE command should create the cluster with the specified options

**Environment summary**
straight Az aks create command in Powershell window

**Additional context**

**Comment by palma21** [comment]
Hi @ChrisRG711 what is the version of your AKS-preview extension?

Could you update your CLI version and update the extension version as well?
For the extension: az extension update --name aks-preview


Current versions should be: 
azure-cli                         2.0.70
Extensions:
aks-preview                        0.4.6


After that try again, if this does not fix it, please do open a support ticket, we're happy to assist.

**Comment by ChrisRG711** [comment]
updated, same error. I opened a support ticket as well. so far no luck. I tried doing the same through the cloud shell and get the same errors.

**Comment by palma21** [comment]
I'll follow up on the ticket, can you double check your subnetID is correct and already exists?

**Comment by yangl900** [comment]
@ChrisRG711 there is bug at our end that the subnet Id comparison was done case sensitively. Before we fix at our side, please try: 1) make sure the subnet exists 2) the subnet name you passed in CLI matches exactly with the actual subnet resource name.

Let me know if that solves the problem. We are fixing the bug too.

**Comment by jluk** [comment]
I believe this should be fixed so closing, but @ChrisRG711 if you continue to hit this please comment and we can re-open on the AKS github repo.
