### ISSUE TITLE
failing to pipe a file to azure blob throug the azure cli

### ISSUE THREAD

**Issue by diepes** [Azure/azure-cli#10090]
## Describe the bug
Get a error when i pipe a file to azure cli , az storage blob upload
**Command Name**
try 1
`echo "Test $(date -I)" | az storage blob upload -c "test" -n example.txt -f - `
 also tried
try 2
`echo "Test $(date -I)" | az storage blob upload -c "test" -n example.txt -f /dev/fd/0`

**Errors:**
```
try1:
...
  File "/opt/az/lib/python3.6/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '-'


try2:
The command failed with an unexpected error. Here is the traceback:
...

'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 132, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
```

## To Reproduce:
export AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol........"
then pipe a file to az storage blob upload and try to upload it to Azure.
echo "Test $(date -I)" | az storage blob upload -c "9spokes-db-ops" -n example.txt -f /dev/fd/0

## Expected Behavior
a file with the content should appear in azure blob, similar to streaming to a s3 bucket

## Environment Summary
```
Linux-4.15.0-52-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.69

Extensions:
aks-preview 0.4.5

```

**Comment by Juliehzl** [comment]
For try1, you should specify a valid file path for ```-f```; For try2, can you show me your more message using ```az storage blob upload -c "test" -n example.txt -f /dev/fd/0 --debug```?

**Comment by Juliehzl** [comment]
Also note that the firewall setting for your storage account.

**Comment by onpaws** [comment]
Having the same issue.
So far, it seems `az storage blob upload` doesn't support streaming-style uploads.

I know it's [possible](https://gist.github.com/hackedunit/01934c02f1bae74f995d9dd76208fd3b#file-db_backup-sh-L41) to persist out a file first, but in my case I'd prefer to upload directly.

@Juliehzl Is there a feature request for streaming-style uploads already? If not, where can I open one?

**Comment by Juliehzl** [comment]
Hi @onpaws, you could create an issue here https://github.com/Azure/azure-cli/issues/new?assignees=&labels=&template=Feature_request.md&title=

**Comment by Juliehzl** [comment]
close the issue for no response

**Comment by onpaws** [comment]
Submitted a new issue as requested
