### ISSUE TITLE
az aks get-versions --location southafricanorth No registered resource provider

### ISSUE THREAD

**Issue by mohamedsaif** [Azure/azure-cli#10100]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.70

**Describe the bug**
No registered resource provider found for location 'southafricanorth' and API version '2019-04-01' for type 'locations/orchestrators' although southafricanorth is in the supported locations listed in the error response

**To Reproduce**
az aks get-versions --location southafricanorth

**Expected behavior**
List of the supported kubernetes versions in southafricanorth

**Environment summary**
Azure CLI latest version installed on Ubuntu VM (cli 2.0.70)

AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list

sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv --keyserver packages.microsoft.com --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF

sudo apt-get update
sudo apt-get install azure-cli  
![azure-cli-error](https://user-images.githubusercontent.com/1328093/62181074-1fe8de80-b363-11e9-8024-68a3c66e7851.jpg)

**Comment by brendandburns** [comment]
Hrm, I tried this and it worked for me. Was this a new subscription? There is eventual consistency in the provider registration.

If it continues to fail for you, please try re-registering for the provider:

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-register-provider-errors#solution-2---azure-cli

And let us know if it continues to fail and we'll investigate on our side.

Thanks!

**Comment by brendandburns** [comment]
@tjprescott I think this can be closed.
