### ISSUE TITLE
Comman az monitor metrics alert list returns the same property twice on actions.

### ISSUE THREAD

**Issue by phillipsj** [Azure/azure-cli#10106]
## Describe the bug

**Command Name**
`az monitor metrics alert list`

**Errors:**

I am seeing the below in the JSON making it difficult to parse due to having the same property repeated.

![image](https://user-images.githubusercontent.com/1568133/62220510-26d11a80-b37e-11e9-9f06-34a18df15939.png)

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor metrics alert list`

## Expected Behavior

That the properties will not be duplicated.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.67 *

Extensions:
tipsextension Unknown

```

**Comment by yonzhan** [comment]
@MyronFanQiu  please take a look.

**Comment by MyronFanQiu** [comment]
@meday89 Hello. I just saw your commits in the metric alert swagger. I just found this line is not consistent with the server's behavior.
https://github.com/Azure/azure-rest-api-specs/blob/de100e16eabbd5d41551cba8b1d8cd97f3701bf9/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-03-01/metricAlert_API.json#L459
Could you check it or help us find the proper person? Thanks!

**Comment by yonzhan** [comment]
@meday89 any update?

**Comment by meday89** [comment]
Hey @phillipsj phillipsj, 
Thanks for reporting this, we're looking into the issue.

**Comment by yonzhan** [comment]
@meday89 any update for this issue?
