### ISSUE TITLE
command `az ad app permission add` doesn't reveal`permission name` and `description` on azure portal

### ISSUE THREAD

**Issue by smartpcr** [Azure/azure-cli#10104]
When using az-cli to set oauthpermissions, portal doesn't reveal name and description field (shows guid in name field, and empty description)

However, if I manually set `API permissions` on portal, these fields do show correct values.

**Comment by yugangw-msft** [comment]
@smartpcr can you please provide a repro?

**Comment by smartpcr** [comment]
resolved offline. thanks!
