### ISSUE TITLE
error in azure blob upload-batch

### ISSUE THREAD

**Issue by dileepdevops** [Azure/azure-cli#10102]
## Describe the bug

**Command Name**
`az storage blob upload-batch`

**Errors:**
```
az storage blob upload-batch: error: argument --destination/-d: expected one argument
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload-batch -d --account-name {} -s {} --account-key {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.66 *

```

**Comment by yugangw-msft** [comment]
The error is valid that you need to supply the destination
//CC @Juliehzl
