### ISSUE TITLE
`--debug` should show the command as entered

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#1010]
It's not uncommon, especially while writing a script, to not have good visibility into what the CLI received from the terminal.  After trying `--debug`, it does not seem that this is printed out anywhere except the request body.

The Azure CLI should
1. Present the command as received early in the `--debug` output
2. Do not dump the command table into `--debug` as it is mostly just a HUGE block of noise now.  

```
msrest.http_logger : Request body:
msrest.http_logger : {"availableToOtherTenants": false, "passwordCredentials": [{"startDate": "2016-09-28T12:06:16.011115Z", "keyId": "c9cc1517-ea52-4344-9b7e-fe8acc26f5a3", "endDate": "2017-09-28T12:06:16.011115Z", "value": "6376f5b3a931483c83087481822be86e"}], "displayName": "$MY_APP_NAME", "identifierUris": ["http://$my_app_id_URI/"], "homepage": "http://$MY_APP_NAME"}
```

**Comment by johanste** [comment]
--debug is intended for (not surprisingly) debugging output. Part of this includes which commands that are available (i.e. the command table). I believe that what you are looking for is the --verbose spew, which does indeed need to be cleaned up.

**Comment by mayurid** [comment]
@JasonRShaver : I agree with Johan. Let us know if you have any concerns else close this.
