### ISSUE TITLE
webapp: az webapp up failed

### ISSUE THREAD

**Issue by Feeloh** [Azure/azure-cli#10117]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
list index out of range
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 652, in _run_job
    cmd_copy.exception_handler(ex)
cli/command_modules/appservice/commands.py, ln 55, in _polish_bad_errors
    raise ex
...
azure/cli/core/__init__.py, ln 485, in default_command_handler
    return op(**command_args)
cli/command_modules/appservice/custom.py, ln 2447, in webapp_up
    location = set_location(cmd, sku, location)
cli/command_modules/appservice/_create_util.py, ln 276, in set_location
    return available_locs[0]
IndexError: list index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up -n {}`

## Environment Summary
```
Linux-4.15.0-1051-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.70

```

**Comment by panchagnula** [comment]
@Feeloh we had an api regression yesterday that was returning an empty array of values that are needed for webapp creation, this issue got mitigated ~3am PST on 8/1 can you please re-try & let us know. Thanks.

**Comment by panchagnula** [comment]
@Feeloh please respond if this is still an issue - the API regression has been fixed for a while.

**Comment by Feeloh** [comment]
Thanks, I used an alternative way for deploying my web application on azure :)
