### ISSUE TITLE
'utf-8' codec can't decode byte 0xff

### ISSUE THREAD

**Issue by taoyama** [Azure/azure-cli#10125]
## Describe the bug

**Command Name**
`az vm boot-diagnostics get-boot-log`

**Errors:**
```
'utf-8' codec can't decode byte 0xff in position 20475: invalid start byte
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
storage/v2018_11_09/blob/baseblobservice.py, ln 2166, in get_blob_to_stream
    stream.write(blob.content)
cli/command_modules/vm/custom.py, ln 1087, in write
    content = str_or_bytes.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 20475: invalid start byte
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm boot-diagnostics get-boot-log -n {} -g {}`

## Environment Summary
```
Linux-3.10.0-957.10.1.el7.x86_64-x86_64-with
Python 3.6.4
Shell: bash

azure-cli 2.0.70

Extensions:
image-copy-extension 0.2.1

```

**Comment by yonzhan** [comment]
@qwordy please take a look.

**Comment by qwordy** [comment]
> 
> 
> @qwordy please take a look.

OK

**Comment by qwordy** [comment]
Could you share what commands you run before this command? I need more information to reproduce and locate the bug. Thanks.

**Comment by taoyama** [comment]
On CentOS 7
$ docker run -it microsoft/azure-cli
$ az login
$ az vm boot-diagnostics get-boot-log -n myvm -g myresourcegroup

I am not able to reproduce that anymore. I guess it is already fixed.

**Comment by qwordy** [comment]
OK. If this problem happens again, you can reopen this issue or open a new issue. Thanks.
