### ISSUE TITLE
Add terminate scheduled event configurability

### ISSUE THREAD

**Issue by szimmerMicrosoft** [Azure/azure-cli#10124]
**Resource Provider**
What is the Azure resource provider your feature is part of?

CRP, Microsoft.Compute

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.

Additional of a couple Virtual Machine Scale Set properties in ScheduledEventsProfile.TerminateNotificationProfile.

This is a configurable property (on create and update)
Which will enable a notification to be sent to the VM on the instance metadata server that a VM is being deleted (terminated).

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

2019-03-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. This should be on the master branch
of the REST API specs repo.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-03-01/compute.json

All references from scheduledEventsProfile (line 8519)

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

8/8/2019

**Comment by qwordy** [comment]
What is default value of enable? "false"?

**Comment by szimmerMicrosoft** [comment]
This is by default disabled.

By default scheduledEventsProfile is null, which disables this feature.

This is equivalent to setting TerminateNotificationProfile.enable = false

**Comment by qwordy** [comment]
> 
> 
> This is by default disabled.
> 
> By default scheduledEventsProfile is null, which disables this feature.
> 
> This is equivalent to setting TerminateNotificationProfile.enable = false

OK. Thank you!

**Comment by qwordy** [comment]
Next time, provide a pull request link so that we can see the swagger changes.
Thank you!

**Comment by qwordy** [comment]
Merged.
