### ISSUE TITLE
--scope parameter

### ISSUE THREAD

**Issue by rgherta** [Azure/azure-cli#10127]
Would be helpful to have a link pointing to the Azure scopes format. For example I would like to assign a role to manage a CosmosDB database and yet I am not sure what is the correct namespace and where to find it.

I had to do az role assignment list -all and search for my needed scope format

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dacfad8-cb2f-2534-3b29-89b0930a2252
* Version Independent ID: 17325cd4-44c5-4069-d9f6-940a55f0f7c9
* Content: [az role assignment](https://docs.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
A scope is simply an Azure resource ID. For CosmosDB, it's like
`/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DocumentDB/databaseAccounts/{accountName}` defined in https://docs.microsoft.com/en-us/rest/api/cosmos-db-resource-provider/databaseaccounts/createorupdate

It also appears in the address bar of the web browser when checking the CosmosDB database in Azure Portal. 

This can also be set to different levels, like subscription, resource group, or resource...

**Comment by SeaDude** [comment]
I've also been looking everywhere for `scope` documentation. It doesn't seem to exist. I was also pointed to `resource id` as a scope definitions. I believe this is only partially accurate as a scope can be defined to the subscription, resource group or resource-level.
