### ISSUE TITLE
az account error

### ISSUE THREAD

**Issue by linuxunderground** [Azure/azure-cli#10130]
**Describe the bug**
In my linux console, I get this error message :
"command authoring error for 'account show': 'subscription' conflicting option string: --subscription"

**To Reproduce**
`$ az account show`
or
`$ az account set -s …`

However, 
`$ az account list`
works well.

**Environment summary**
The problem occurs with azure-cli-2.0.69 and azure-cli-2.0.70 on Gentoo linux.

**Additional context**
Note that version 2.0.68 works quite well.
I'm waiting for a fix before releasing new Gentoo ebuild on
[https://github.com/linuxunderground/gentoo.overlay/tree/master/net-misc/azure-cli](https://github.com/linuxunderground/gentoo.overlay/tree/master/net-misc/azure-cli)

**Comment by yugangw-msft** [comment]
@linuxunderground, i assume you installed through `pip`, if yes, can you please create a virtualenv and do a clean install? This would at least isolate the problem a bit.

**Comment by linuxunderground** [comment]
@yugangw-msft, NO. 
It's the Gentoo package manager (portage) that install source tarball release with python setuptools, package after package, each downloaded on https://pypi.org/. I maintain Azure-CLI 2.0 for Gentoo through my own overlay.
The trouble is certainly in azure-cli-2.0.70.tar.gz or in azure-cli-core-2.0.70.tar.gz. Only these 2 packages change to reproduce or not the trouble.

**Comment by linuxunderground** [comment]
PS:
I suspect that it's related to this comment on [https://pypi.org/project/azure-cli/](https://pypi.org/project/azure-cli/)

> 2.0.69
> Core
> Fixed issue where –subscription would appear despite being not applicable.

**Comment by linuxunderground** [comment]
Hi,

[azure-cli-profile.txt](https://github.com/Azure/azure-cli/files/3522066/azure-cli-profile.txt) : this is a patch to apply to azure-cli-profile-2.1.5.tar.gz package. This patch fixes this issue.

Some explanations :
At https://pypi.org/, you have 2 different packages (azure-cli-2.0.71.tar.gz and azure-cli-profile-2.1.5.tar.gz)  with the same files to install in the same place :

```
$ ls azure-cli-2.0.71/azure/cli/command_modules/profile
-rw-r--r-- 1 vincent users 8542  8 aoû 05:45 custom.py
-rw-r--r-- 1 vincent users  792  8 aoû 05:45 _format.py
-rw-r--r-- 1 vincent users 3154  8 aoû 05:45 _help.py
-rw-r--r-- 1 vincent users 5074  8 aoû 05:45 __init__.py

$ ls azure-cli-profile-2.1.5/azure/cli/command_modules/profile
-rw-r--r-- 1 vincent users 7864  5 avr 00:46 custom.py
-rw-r--r-- 1 vincent users  792  5 avr 00:46 _format.py
-rw-r--r-- 1 vincent users 3154  5 avr 00:46 _help.py
-rw-r--r-- 1 vincent users 4562  5 avr 00:46 __init__.py
```
IMHO, it's not a good idea. Not to mention that Gentoo package manager does not like it!

You make changes on one side but not on the other side. Do not be surprised to have strange behaviors :-)

Regards

--
Vincent

**Comment by linuxunderground** [comment]
My last findings :
If azure-cli-profile and other azure-cli-* (except azure-cli-core and telemetry) packages have become obsolete with current azure-cli package then this issue may be closed.
