### ISSUE TITLE
unable to login after work user password reset

### ISSUE THREAD

**Issue by smartpcr** [Azure/azure-cli#10134]
I recently reset my password, when I did `az login` and calling the following method `az ad sp list --display-name **`, I keep getting the following error (note, this is happening on windows/linux, but not on mac):

``` txt
Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked. The user might have changed or reset their password. The grant was issued on '2019-06-06T17:51:29.8920000Z' and the TokensValidFrom date for this user is '2019-07-29T17:21:03.0000000Z'.\r\nTrace ID: aa7a20fd-7617-4ace-89a1-33440ca31700\r\nCorrelation ID: 1a0bb613-9fdf-4a55-9a99-155918f3c96d\r\nTimestamp: 2019-08-02 18:04:27Z","error_codes":[50173],"timestamp":"2019-08-02 18:04:27Z","trace_id":"aa7a20fd-7617-4ace-89a1-33440ca31700","correlation_id":"1a0bb613-9fdf-4a55-9a99-155918f3c96d"}
```

I've tried close all the browser and cleared out folder .azure, but no success

**Comment by yugangw-msft** [comment]
@jiasli, let us add a new condition on “AADSTS50173” at [here](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/adal_authentication.py#L42) to polish the error so users would know to run “az login”.

**Comment by jiasli** [comment]
As discussed, this is due to outdated browser cookies. The solution is to purge browser cache and re-login to CLI.
