### ISSUE TITLE
can't see the output url of vpn-client  

### ISSUE THREAD

**Issue by limordavid** [Azure/azure-cli#10144]
## Describe the bug

**Command Name**
`az network vnet-gateway vpn-client generate`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network vnet-gateway vpn-client generate -g {} -n {} --processor-architecture {} --resource-group {}`

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.69 *

```

**Comment by MyronFanQiu** [comment]
@limordavid Thanks. I will do some investigation. Ref a possible related issue.  https://github.com/Azure/azure-cli/issues/10085

**Comment by MyronFanQiu** [comment]
@limordavid Hello. I cannot reproduce this. Could you please run the command with `--debug` and `-o json` twice?

**Comment by MyronFanQiu** [comment]
close this one since no response. Feel free to open a new one if you still encounter such issue.
