### ISSUE TITLE
Unsupported Media Type

### ISSUE THREAD

**Issue by rsaitosntk** [Azure/azure-cli#10143]
## Describe the bug

**Command Name**
`az rest`

**Errors:**
```
Unsupported Media Type({"error":{"code":"UnsupportedMediaType","message":"The content media type '<null>' is not supported. Only 'application/json' is supported."}})
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az rest -m {} -u {} -b {}`

## Environment Summary
```
Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.70

Extensions:
interactive 0.4.3

```
## Additional Context

<!--

**Comment by yonzhan** [comment]
@Juliehzl please take a look.

**Comment by Juliehzl** [comment]
@rsaitosntk Sorry for late response during transition process. I know it is a long time after you open the PR. But can you provide more information  with `--debug` in you command to help CLI find the root cause for you issue?

**Comment by rsaitosntk** [comment]
@Juliehzl
In CLI commands, the --debug option is considered valid.
However, the implementation status of APIs in Azure is changing day by day, and we do not know exactly.
Also, our project is complete and there is no environment to provide further information.

**Comment by Juliehzl** [comment]
> @Juliehzl
> In CLI commands, the --debug option is considered valid.
> However, the implementation status of APIs in Azure is changing day by day, and we do not know exactly.
> Also, our project is complete and there is no environment to provide further information.

Anyway, sorry for inconvenience and thanks a lot for you information. If you have other problems, feel free to let us know.

**Comment by Splaxi** [comment]
For anyone find this when searching for: 
```
Unsupported Media Type({"error":{"code":"UnsupportedMediaType","message":"The content media type '<null>' is not supported. Only 'application/json' is supported."}})
```

It is most likely that you have 2 issues: Your json needs to be a single line json string, escaped. I had a multi line json in a variable in PowerShell, and when converting it to a single line and escaping the **"** to **\"** the error went away.

**Comment by TheITRx** [comment]
convert this json to a powershell object:

{
  "properties": {
    "eventHubName": "$eh_name",
    "eventHubAuthorizationRuleId": "$eh_auth_rule_id",
    "logs": [
      {
        "category": "Administrative",
        "enabled": true
      }
    ]
  }
}

**Comment by TimurSadykov** [comment]
> For anyone find this when searching for:
> 
> ```
> Unsupported Media Type({"error":{"code":"UnsupportedMediaType","message":"The content media type '<null>' is not supported. Only 'application/json' is supported."}})
> ```
> 
> It is most likely that you have 2 issues: Your json needs to be a single line json string, escaped. I had a multi line json in a variable in PowerShell, and when converting it to a single line and escaping the **"** (double qoute) to **\"** (slash double quote) the error went away.

Still same error
