### ISSUE TITLE
az acr login --name fails 

### ISSUE THREAD

**Issue by sdatta1** [Azure/azure-cli#10142]
## Describe the bug

**Command Name**
`az acr login`

**Errors:**
```
HTTPSConnectionPool(host='susantaacr.azurecr.io', port=443): Max retries exceeded with url: /v2/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0595E9D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
Traceback (most recent call last):
pip-install-19n3wov0\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr login --name {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.70

```

**Comment by yugangw-msft** [comment]
@sdatta1, sorry for the delay. The error was more generic, not related with the command of `az acr login`
```
Failed to run command 'docker pull mcr.microsoft.com/mcr/hello-world:latest'. Error response from daemon: Get https://mcr.microsoft.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
The question here is did you run the command behind a firewall/proxy or have a whitelists of IPs you can reach out?
There are a few diagnostics suggested at `https://github.com/docker/for-win/issues/611`, which you can try out, and let us know whether they help.

**Comment by yugangw-msft** [comment]
Please reactivate with more information for us to diagnose for the root cause
