### ISSUE TITLE
`az ad app update --homepage` doesn't update homepage

### ISSUE THREAD

**Issue by miicahjardine** [Azure/azure-cli#10151]
az ad app update --homepage does nothing.  I run the command and get no errors no feedback. 

When I check in the portal the value has homepageUrl has not updated.  using CLI Version 2.0.70

I am using powershell script to call AZ commands.  I have a piece of code which looks like this...

$manifest = get-content $manifestLocation

    # Set the homepage url
    if ($manifest.signInUrl) {
        write-host "Set homepage url... " -NoNewline
        az ad app update --id $applicationInfo.appId --homepage $manifest.signInUrl 
        write-host " Done"
    }
    else { write-host "No homepage url specified in the manifest file...skipping" }

# manfest signinurl has the value of https://bobTheApp.prod

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
Thank you for raising this issue. I have fixed it in pull request https://github.com/Azure/azure-cli/pull/10226.
