### ISSUE TITLE
VM/VMSS: Referencing VMSS during VM creation

### ISSUE THREAD

**Issue by shpa-microsoft** [Azure/azure-cli#10156]
**Resource Provider**
What is the Azure resource provider your feature is part of?
- Compute

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
- Converged API VMSS now allows usage of VMSS in a way similar to availability Sets. Therefore we now need to reference VMSS instead of av-set during VM creation for clients who want to use this. Find internal API docs here: https://microsoft-my.sharepoint.com/%3Aw%3A/g/personal/shpa_microsoft_com1/Ef68QZMoy9BIpvnmq8RDeB8BoSvADf3afeUadvvs49MlBQ?e=gmWhky 
- https://microsoft-my.sharepoint.com/%3Aw%3A/g/personal/shpa_microsoft_com1/Ea1j9UXmUA5OnMul_N4fFrABjyLHBNjayNArtj3vRgSvCA?e=Xwrx0d

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
- 2019-03-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. This should be on the master branch of the REST API specs repo.
- https://github.com/Azure/azure-rest-api-specs/pull/6836 (needs to be merged yet)

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

**Comment by qwordy** [comment]
We have received you feature request.

**Comment by shpa-microsoft** [comment]
Need traction on this. Tried reaching out to whoever I could find. Perhaps posting here will do the job. @qwordy , @Juliehzl , @yonzhan Please help. We need this for Ignite too and it's been open for a very long time. Thank you! :)

**Comment by qwordy** [comment]
> 
> 
> Need traction on this. Tried reaching out to whoever I could find. Perhaps posting here will do the job. @qwordy , @Juliehzl , @yonzhan Please help. We need this for Ignite too and it's been open for a very long time. Thank you! :)

OK. We will prioritize this issue. I have opened a PR, but it has problems. Do you know how to create a valid vmss in Azure CLI to be referenced in `vm create`? vmss of new type?

**Comment by shpa-microsoft** [comment]
Yes, when you create a VMSS, please do not provide any VM profile in the template and that should be acceptable for this one. More details in the email thread I started.

**Comment by yonzhan** [comment]
@qwordy are you blocked by some problem ?

**Comment by qwordy** [comment]
I think I need add a new parameter for `vmss create` to create a such kind of vmss. Now, all control flows in `vmss create` will define virtualMachineProfile.

**Comment by shpa-microsoft** [comment]
Made review comments on that PR. Please reach out to me directly for any confusion.

**Comment by yonzhan** [comment]
This request is already planned for Ignite. The PR is https://github.com/Azure/azure-cli/pull/10646, currently reviewed by Jun Wang (AZURE) from Compute team.

**Comment by qwordy** [comment]
> 
> 
> Made review comments on that PR. Please reach out to me directly for any confusion.

OK. Thanks!

**Comment by qwordy** [comment]
This feature will be available in Azure CLI 2.0.76. Official Release: 11/04/2019
