### ISSUE TITLE
centos install CLI error

### ISSUE THREAD

**Issue by titanwan** [Azure/azure-cli#10159]
curl -L https://aka.ms/InstallAzureCli | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
105  1369  105  1369    0     0    527      0  0:00:02  0:00:02 --:--:--     0
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /tmp/azure_cli_install_tmp_6BBFIH.
######################################################################## 100.0%
/tmp/azure_cli_install_tmp_6BBFIH: OK
Running install script.
-- Verifying Python version.
-- Python version 3.7.0 okay.
/tmp/azure_cli_install_tmp_6BBFIH:309: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  distname, version, _ = platform.linux_distribution()
-- Verifying native dependencies.
-- Executing: 'rpm -q gcc libffi-devel python37u-devel openssl-devel'
-- One or more of the following native dependencies are not currently installed and may be required.
"yum check-update ; yum install -y gcc libffi-devel python37u-devel openssl-devel"

**Comment by Juliehzl** [comment]
According to error message, you need to install [prerequisites](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest#prerequisites) packages through ```yum check-update```  and ``` yum install -y gcc libffi-devel python37u-devel openssl-devel```.

For CentOS, you also can install Azure CLI according to  https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest.

**Comment by fengzhou-msft** [comment]
Please follow the latest installation guide: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest
