### ISSUE TITLE
File paths (inclusion/exclusion) for acr task triggers

### ISSUE THREAD

**Issue by BenjaminHerbert** [Azure/azure-cli#10153]
Is there a way to specify inclusion/exclusion of file paths in ACR tasks triggers? 

I have a monorepo with many different Dockerfiles and - as there are different jobs that have both source code and base image update triggers - some jobs are build too often when a commit is made in the repository. Once for the commit and once triggered by the base-image update.

Someting as this: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#paths) perhaps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0e3f3c-5aed-28b6-1e28-22ff32a8521d
* Version Independent ID: 128e5bc6-e518-bd5a-f511-48e0ed185739
* Content: [az acr task](https://docs.microsoft.com/en-us/cli/azure/acr/task?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by northtyphoon** [comment]
@BenjaminHerbert thanks for the question. Unfortunately tasks doesn't support path filter. Can you raise your feature request in https://aka.ms/acr/uservoice.  

One workaround is disable Tasks built-in commit trigger and instead using Azure Pipeline to subscribe to the filtered commit events and call `az acr build -t image .` from Azure Pipeline CLI task.

**Comment by BenjaminHerbert** [comment]
@northtyphoon I am currently using _base image update triggers_. (See https://docs.microsoft.com/bs-latn-ba/azure/container-registry/container-registry-tasks-overview#automate-os-and-framework-patching). 

Do you have a pointer how/if this (read: a base-image update triggers all dependent builds) is is possible with Azure (DevOps) Pipeline?

**Comment by northtyphoon** [comment]
DevOps hasn't supported  base-image update trigger yet. It's under development. Stay tuned.

**Comment by BenjaminHerbert** [comment]
@northtyphoon That's good to hear. Is there a way where I can track the progress for this feature? :yum:

**Comment by rayoef** [comment]
This was more of a feature request than documentation question. Closing now.
#please-close

**Comment by rayoef** [comment]
#please-close
