### ISSUE TITLE
[az monitor metrics alert][Unable to update|disable availability alert]

### ISSUE THREAD

**Issue by Sviatik** [Azure/azure-cli#10162]
## Describe the bug
I've created availability checks in app insights and it automatically creates alert. When I try to disable it, I get the next error message 

**Command Name**
`az monitor metrics alert update`

**Errors:**
```
validation error: Parameter 'MetricAlertCriteria.odatatype' can not be None.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create some availability check. 
- Try to update alerts using command below.
- `az monitor metrics alert update --enabled false --name {} --resource-group {} --debug`

## Expected Behavior
Disable that alert

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.68 *

```

**Comment by Sviatik** [comment]
UPD
Also tried with
```azure-cli 2.0.70```
The same issue.

**Comment by Chirag1233** [comment]
I have the same issue.

**Comment by khabbabs** [comment]
I have similar issue when updating log profile locations

**Comment by sMiik** [comment]
Same issue here.
Tried with azure-cli 2.0.63 on windows and 2.0.72 on cloud shell.

The error is thrown with either value for enabled parameter and for both name + resource-group parameter combination or ids parameter

**Comment by sMiik** [comment]
Seems that you can also do this by modifying the resource, i.e.
`az resource update --set properties.enabled=false --name {} --resource-group {} --resource-type Microsoft.Insights/webtests`
does the same thing, except with resource update the command actually works. I added the resource-type parameter just in case

**Comment by Sviatik** [comment]
@sMiik 
Yes, it works great for me.
Thanks a lot!

**Comment by MyronFanQiu** [comment]
@Sviatik Hello. I'm looking into this issue recently. I used the `az monitor metric alert create` to create an alert rule for storage account. Then I tried to disable it and it worked. I couldn't reproduce this error. Could you please give me more details about your process? What's your process to create a resource and then create a metric alert?

**Comment by Sviatik** [comment]
@MyronFanQiu 
Hello, 
Here are steps to reproduce:
- Create manually availability check (web test) in application insight. It can be ping to google.com (It automatically create alert)
![image](https://user-images.githubusercontent.com/15470583/64704978-d0e0ae00-d4b7-11e9-9cc1-cb6a8ab02edc.png)
.
![image](https://user-images.githubusercontent.com/15470583/64705544-cbd02e80-d4b8-11e9-8e97-5d4c236bfbff.png)


- Try to disable this alert using ```az monitor metrics alert update --enabled false --name {} --resource-group {} --debug```

**Comment by MyronFanQiu** [comment]
@Sviatik Thanks! I have reproduced the error. I will take a look.

**Comment by MyronFanQiu** [comment]
@Sviatik Hello. Looks like the server will return some odata.types which are not supported by python SDK. There is not [subtype](https://github.com/Azure/azure-sdk-for-python/blob/483a33447ba26e62c1b6d4a389055a191b5d4b6e/sdk/monitor/azure-mgmt-monitor/azure/mgmt/monitor/v2018_03_01/models/_models_py3.py#L695)  for Microsoft.Azure.Monitor.WebtestLocationAvailabilityCriteria. I will invite service team to take a look at this issue.

**Comment by MyronFanQiu** [comment]
@Dalubash Hello. Could you please take a look at this issue?

**Comment by harelbr** [comment]
Disabling the alert rule of an Application Insights web test using the `az monitor metrics alert update` command isn't supported currently.

As a workaround, you can achieve this by directly modifying the 'enabled' property of the alert rule's underlying resource, using the following command:
`az resource update --set properties.enabled=false --name {} --resource-group {} --resource-type Microsoft.Insights/metricAlerts`

Please note that the command above will only disable the web test's alert rule, and the web test itself will continue running. If you’d like to also disable the web test, use the following command:
`az resource update --set properties.enabled=false --name {} --resource-group {} --resource-type Microsoft.Insights/webtests`

**Comment by MyronFanQiu** [comment]
@Sviatik Hello. Since service team doesn't provide SDK for CLI currently. I will left this issue open and move it to backlog.

**Comment by harelbr** [comment]
This item is on our backlog to address (backlog item #5365351).
