### ISSUE TITLE
Fails when installed with pip3

### ISSUE THREAD

**Issue by tstringer** [Azure/azure-cli#1016]
Doing the following:

```
$ pip3 install azure-cli
```

And then running `az`, I get the following error:

> /usr/local/opt/python/bin/python2.7: No module named azure

Is this supposed to run with python3?

**Comment by derekbekoe** [comment]
We  do support Python 3.
However, currently we expect the python interpreter to be called `python` and not `python3`.
Related to https://github.com/Azure/azure-cli/issues/1008 which links to a PR.

**Comment by leobastin** [comment]
I do have python 2.7 but  get the same error:
/usr/bin/python: No module named azure

$ python
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
