### ISSUE TITLE
az devops service-endpoint create asking for unkown parameter (--service-endpoint-configuration)

### ISSUE THREAD

**Issue by mlcroix** [Azure/azure-cli#10164]
**Describe the bug**
We are trying to use an azure DevOps pipeline in order to roll out projects. however, we are running into a problem when we try to create a service connection. When we run the script outside of the pipeline everything works fine, however, in the pipeline we get the following error:
**ERROR: az DevOps service-endpoint create: error: the following arguments are required: --service-endpoint-configuration**

We checked the documentation but they don't mention this parameter also we couldn't find anything about it on google.

We also tried to use this parameter with a random string, however, then we receive the following error:
**az: error: unrecognized arguments:**

We tested this on our own Linux agent and the hosted ubuntu agent but both gave the same errors.

**To Reproduce**
```
SubscriptionId=$(az account list --query "[?name=='Integratie zone'].[id]" --output tsv)
SubscriptionName="IntegratieZone"
CombinedTeamName=$(echo -e "Team Saas" | tr -d '[:space:]')
ServicePrinciplePassword=$(az ad sp create-for-rbac --name "SP$CombinedTeamName" --role Contributor --query password --output tsv --scopes /subscriptions/_SubscriptionID_)
        ServicePrincipleAppId=$(az ad sp list --query "[?displayName=='SP$CombinedTeamName'].[appId]" --all --output tsv)

        export AZURE_DEVOPS_EXT_AZURE_RM_SERVICE_PRINCIPAL_KEY=$ServicePrinciplePassword
        set | grep AZURE_DEV

az devops service-endpoint create \
--authorization-scheme ServicePrincipal \
--name "SP$CombinedTeamName-endpoint" \
--service-endpoint-type azurerm \
--project "Team Saas" \
--org "https://dev.azure.com/_organisationname_" \
--encoding "utf-8" \
--azure-rm-service-principal-id $ServicePrincipleAppId \
--azure-rm-tenant-id $(ServicePrincipleAppTenantId) \
--azure-rm-subscription-id $SubscriptionId   \
--azure-rm-subscription-name $SubscriptionName \
```

**Expected behavior**
The command will create a service connection with the configured service principle in the desired project.

**Environment summary**
Azure devops pipeline inline script
Ubuntu agent
azure-cli: 2.0.70
azure-devops: 0.11.0

**Comment by yugangw-msft** [comment]
please open the issue at https://github.com/azure/azure-cli-extensions
