### ISSUE TITLE
The command az webapp up failed with an unexpected error - Python 2.7

### ISSUE THREAD

**Issue by gustavo-accellog** [Azure/azure-cli#10179]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


glob() got an unexpected keyword argument 'recursive'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
TypeError: glob() got an unexpected keyword argument 'recursive'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up -g {} -n {} -l {} --sku {} -p {}`

## Environment Summary
```
Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.70

```

**Comment by panchagnula** [comment]
@gustavo-accellog please update the python version 3.5 or higher & this should be resolved. Looks like I missed a part of the code which is still using glob that is not available on older versions of Python.

**Comment by gustavo-accellog** [comment]
I had the same problema in az aks creat and it was ok now.
https://github.com/Azure/azure-cli/issues/9651#issuecomment-518289351
I'm using CentOS 7 and the python 2.7 is default. But I use python 3.6 too.
