### ISSUE TITLE
'az policy assignment show' doesn't work on portal assigned policies

### ISSUE THREAD

**Issue by itaylaufer** [Azure/azure-cli#10175]
## Describe the bug

**Command Name**
`az policy assignment show`

**Errors:**
```
Operation returned an invalid status code 'Not Found'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

1. I've assigned an existing Azure policy in the portal to a management-group.
2. I chose the 'Audit virtual machines without disaster recovery configured' policy and called the assignment name 'testing'
3. ran 'az policy assignment show --name testing' and got the error 'Operation returned an invalid status code 'Not Found''
 
- _Put any pre-requisite steps here..._
- `az policy assignment show --name {}`

## Environment Summary
```
Darwin-18.0.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.70

```

**Comment by yonzhan** [comment]
@Juliehzl please take a look.

**Comment by Juliehzl** [comment]
Could you show me debug information with `--debug` in your command?

**Comment by Juliehzl** [comment]
@jsntcy Can you have a look at this issue?

**Comment by yonzhan** [comment]
@itaylaufer  any update for this issue?

**Comment by zhoxing-ms** [comment]
@itaylaufer Because we haven't received any reply for a long time, so I will close this issue first. If you still have any questions, please feel free to let us know~
