### ISSUE TITLE
Can't open AKS Kubernetes dashboard with az aks browse

### ISSUE THREAD

**Issue by ravisjoshi** [Azure/azure-cli#10177]
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b0e2810>: Failed to establish a new connection: [Errno 61] Connection refused'))
Traceback (most recent call last):
python3.7/site-packages/urllib3/connection.py, ln 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
site-packages/urllib3/util/connection.py, ln 80, in create_connection
    raise err
...

python3.7/site-packages/requests/adapters.py, ln 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /closeport/8001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b0e2810>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Darwin-16.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.69 *

```

**Comment by kasunsjc** [comment]
@ravisjoshi I have tried this on my cluster and works fine can you update the azure cli to latest and try.

Does this work previously, or is it the first time are you executing this command

**Comment by ravisjoshi** [comment]
@kasunsjc this is the first time I have executed this command.

**Comment by kasunsjc** [comment]
@ravisjoshi I tried it with newly created cluster and my existing cluster. It works fine with me. Yes its the first time I executed the command

**Comment by haroldrandom** [comment]
Have this solved?

**Comment by ravisjoshi** [comment]
yes, it's resolved. Somehow it doesn't open in first time and when I reload the same tab again, it shows the dashboard.
