### ISSUE TITLE
az login --debug is not showing HTTP request

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#10189]
**Describe the bug**
With CLI 2.0.70, `az login --debug` is not showing HTTP request.

**To Reproduce**
Run `az login --debug`.

**Expected behavior**
HTTP request should be shown as
```
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/...'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'User-Agent': ...
```

**Comment by yonzhan** [comment]
We will triage this issue.

**Comment by StianOvrevage** [comment]
This might be the same root cause as my problem, running `az vmss list --verbose --debug` does not show HTTP Headers when the request fails because of 429 TooManyRequests.

Yet the very information I need about the current rate limit buckets etc are in the HTTP Headers.

**Comment by jiasli** [comment]
The original issue was fixed in https://github.com/Azure/azure-cli/pull/11587. Moving the 429 TooManyRequests issue to a new issue.
