### ISSUE TITLE
Azure CLI won't install for Ubuntu disco

### ISSUE THREAD

**Issue by Octorocka** [Azure/azure-cli#10198]
I am having issues installing the azure cli for 19.04 (Disco Dingo) when I follow the instructions from 
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

At step 4 I am getting an error message,

> sudo apt-get update
W: The repository 'https://packages.microsoft.com/repos/azure-cli disco Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/disco/main/binary-amd64/Packages  Could not handshake: The TLS connection was non-properly terminated. [IP: 10.19.8.225 911]
E: Some index files failed to download. They have been ignored, or old ones used instead.

At first I thought it was a proxy issue. However I verified my apt proxy settings [as well as my ~/.bashrc] and they are correct. The file '/etc/apt/sources.list.d/azure-cli.list' looks like this,
cat /etc/apt/sources.list.d/azure-cli.list
deb [arch=amd64 allow-insecure=yes] https://packages.microsoft.com/repos/azure-cli/ disco main

Can someone shed some light on why I am getting an error message?

**Comment by yonzhan** [comment]
We will triage this.

**Comment by fengzhou-msft** [comment]
@Octorocka I cannot reproduce your issue. On my disco machine, azure-cli.list shows 
`deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ disco main`, no `allow-insecure` setting.
Not sure if you already read this, but here's some troubleshooting instruction for [proxy issue](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#proxy-blocks-connection).

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please feel free to reopen the issue if you still have the issue with the latest release.
