### ISSUE TITLE
I am the owner of all resources and I receive this error when try to create a File share

### ISSUE THREAD

**Issue by yoprogramo** [Azure/azure-cli#10190]
## Describe the bug

**Command Name**
`az storage share create`

**Errors:**
```
This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:b85cbaed-501a-005a-60ce-4d0326000000
Time:2019-08-08T09:52:30.3231727Z</Message></Error>
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
...
azure.common.AzureHttpError: This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:b85cbaed-501a-005a-60ce-4d0326000000
Time:2019-08-08T09:52:30.3231727Z</Message></Error>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage share create --account-name {} --account-key {} --name {}`

## Environment Summary
```
Linux-4.15.0-1052-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.70

```

**Comment by Juliehzl** [comment]
Do you set firewalls for this storage account?

**Comment by boillodmanuel** [comment]
This happens when the account storage has a firewall.
In my case, the I allow Azure Services to bypass the firewall, so I expect the CLI could bypass it, but it doesn't.
For me, it's an issue

**Comment by yonzhan** [comment]
add to S167.

**Comment by Juliehzl** [comment]
> This happens when the account storage has a firewall.
> In my case, the I allow Azure Services to bypass the firewall, so I expect the CLI could bypass it, but it doesn't.
> For me, it's an issue

To bypassing the firewall, you can use `az storage share-rm create`.

**Comment by yonzhan** [comment]
@yoprogramo was your issue resolved?

**Comment by yonzhan** [comment]
@boillodmanuel  any feedback?

**Comment by boillodmanuel** [comment]
I confirm that `share-rm` bypass the firewall 👍but what about blob and other storages?

**Comment by Juliehzl** [comment]
> I confirm that `share-rm` bypass the firewall 👍but what about blob and other storages?

Currently we only have such support for file share, but we are welcome for the request of other storage services.

**Comment by boillodmanuel** [comment]
> we are welcome for the request of other storage services.

Hi @Juliehzl. How can I do this request? How is this synchronized with request for REST API ? Or Go SDK? 
I don't even know if she `share-rm` is available on these clients?

**Comment by Juliehzl** [comment]
Hi @boillodmanuel, you may need to go to other repos, e.g. https://github.com/Azure/azure-sdk-for-go? I only own CLI related part and cannot provide more for other parts.
