### ISSUE TITLE
[webapp] - az appservice plan update - 'NoneType' object has no attribute 'sku'

### ISSUE THREAD

**Issue by ackbaradmiral** [Azure/azure-cli#10197]
## Describe the bug

**Command Name**
`az appservice plan update`

**Errors:**
```
'NoneType' object has no attribute 'sku'
Traceback (most recent call last):
Temp\pip-install-rtk110ve\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 654, in _run_job
Local\Temp\pip-install-rtk110ve\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 305, in __call__
azure\cli\core\commands\arm.py, ln 515, in handler
azure\cli\command_modules\appservice\custom.py, ln 1281, in update_app_service_plan
AttributeError: 'NoneType' object has no attribute 'sku'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az appservice plan update --sku B3 -n AppName -g ResourceName`

## Expected Behavior
AppService Upgraded 

```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.70

```

**Comment by ericlobner** [comment]
If you have multiple subscriptions, you will need to set the subscription first, use: 

`az account set --subscription "YOUR SUB NAME"`

**Comment by ackbaradmiral** [comment]
Figured it out - needed to pass in the "App Service Plan" name. I was originally passing in "App Service" name.
