### ISSUE TITLE
core: updating the msrest dependency to 0.6.9

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#10195]
This is to incorporate the fix of https://github.com/Azure/msrest-for-python/pull/167

@zikalino, please take this on and fix it for the current release across all the installers. You can sync up with @iluican for the verification.

Note, all requirement files should be updated. For cloud shell, the one is [here](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/requirements.py3.Linux.txt#L99).

**Comment by iluican** [comment]
@yonzhan This is breaking some functionality in our extension (IoT), could you please try and prioritize the fix? Reading the release notes between msrest 0.6.7 and 0.6.9, there shouldn't be any breaking changes, so updating the dependency should be straightforward.

**Comment by yonzhan** [comment]
@iluican we already triaged this issue and will finish it in this sprint.

**Comment by yonzhan** [comment]
resolved
