### ISSUE TITLE
webapp:ISO 8601 timestamp web app setting is being converted

### ISSUE THREAD

**Issue by sawyerh** [Azure/azure-cli#10215]
**Describe the bug**
I am attempting to set an app setting to an ISO 8601 timestamp, and the value is being converted to a different format and timezone.

Example of the command and setting:

```bash
az webapp config appsettings set -n my-app \
  -g my-app-rq \
  --settings MAINTENANCE_END="2019-08-12T08:00:00.000-04:00"
```

Azure is saving this setting with the following value instead: `"08/12/2019 12:00:00"`

When I set the same value in the Azure Portal, the value _does not_ get converted, which is the expected behavior.

**To Reproduce**
- Run the command above
- Edit the value in the Azure Portal and observe it _not_ doing the same type of conversion

**Expected behavior**
- When I run `az webapp config appsettings set`, I expect the value (`"2019-08-12T08:00:00.000-04:00"`) to be set in Azure without being converted to a different format (`"08/12/2019 12:00:00"`).

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.69 *

**Comment by poveden** [comment]
I've discovered that, at least from Windows, if the timestamp is surrounded by spaces, AZ CLI will publish the value correctly _and without spaces_:

```
az webapp config appsettings set -n my-app \
  -g my-app-rq \
  --settings SOME_SETTING=" 2019-08-12T08:00:00.000-04:00 "
```

**Comment by sawyerh** [comment]
@MyronFanQiu Any updates on this? This feels like a major bug.

**Comment by panchagnula** [comment]
@sawyerh CLI doesn't do any DateTime conversion on our end & simply sends the value to the API. have you tried the suggestion @poveden provided above.

Also you mentioned you did the from portal & it works correctly can you tell which menu item on the portal you used here?

**Comment by panchagnula** [comment]
@sawyerh please re-activate after providing the info above so we can investigate this further, given there is an assumption that portal is doing the right behavior here. Thanks!
