### ISSUE TITLE
[webapp] - Apply should_disable_connection_verify consistently

### ISSUE THREAD

**Issue by jonasbutt** [Azure/azure-cli#10216]
`verify=not should_disable_connection_verify()` is missing on this line:

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L2330

See this line for the correct implementation:

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L325

A fix was made previously, but this was only a partial solution, since the next call to check the status of the deployment fails:

https://github.com/panchagnula/azure-cli/commit/a48061ea65d71d007b6cf45cd8586047b69fb730

Hope this can be fixed soon. Thanks!

**Comment by btardif** [comment]
we will tackle this in sprint 69

**Comment by jonasbutt** [comment]
Thanks for fixing this :)
