### ISSUE TITLE
Document CI is broken

### ISSUE THREAD

**Issue by formulahendry** [Azure/azure-cli#1022]
It is broken at https://ci.appveyor.com/project/VisualStudioChinaAppVeyorUsers/azure-cli/build/1.0.200 with commit https://github.com/Azure/azure-cli/commit/90c7b7de3159e41160c96dbaffd13f94e20c3874.

Errors:
Exception occurred:
  File "C:\projects\azure-cli\doc\sphinx\azhelpgen\azhelpgen.py", line 51, in <lambda>
    + str(not p.required) + p.name):
AttributeError: module 'azure.cli.core._help' has no attribute 'get_group_priority'

**Comment by mayurid** [comment]
Looks like a PR is out to be reviewed.
