### ISSUE TITLE
"az acr helm repo add" fails on "'NoneType' object has no attribute 'basic'"

### ISSUE THREAD

**Issue by orensam-msft** [Azure/azure-cli#10222]
## Describe the bug

**Command Name**
`az acr helm repo add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'NoneType' object has no attribute 'basic'
Traceback (most recent call last):
  File "/Users/orsamuel/code/venvs/k8s-lab/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/orsamuel/code/venvs/k8s-lab/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
AttributeError: 'NoneType' object has no attribute 'basic'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az acr helm repo add --name {} --subscription {}`

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 2.7.16
Shell: bash

azure-cli 2.0.51 *

```

**Comment by shizhMSFT** [comment]
@orensam-msft Could you upgrade your `az` cli to the latest version? I cannot reproduce the bug in the version `2.0.70` and the latest version `2.0.71` while I do find that the version `2.0.51` has issues in AAD login.

**Comment by orensam-msft** [comment]
Hi, upgrading to `2.0.71` did the trick. Thanks!
