### ISSUE TITLE
AZURE_CLI_DISABLE_CONNECTION_VERIFICATION doesn't work with Storage data-plane operations

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#10236]
**Describe the bug**
`AZURE_CLI_DISABLE_CONNECTION_VERIFICATION` doesn't work with Storage data-plane operations. https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy

**To Reproduce**
When using CLI behind a proxy like Fiddler,
```
set AZURE_STORAGE_ACCOUNT="xxx"
set AZURE_STORAGE_KEY="xxx"
set AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1
az storage blob list --container-name xxx
```
Got exception 
> HTTPSConnectionPool(host='xxx.blob.core.windows.net', port=443): Max retries exceeded with url: /xxx?restype=container&comp=list&maxresults=5000 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Expected behavior**
CLI should ignore certificate error.

**Environment summary**
2.0.71 on Windows

**Additional context**
Luckily, `REQUESTS_CA_BUNDLE` works.

**Comment by jiasli** [comment]
Related to https://github.com/Azure/azure-storage-python/issues/175

**Comment by ivanignatiev** [comment]
I have the same issue, all commands works well except "az storage"

**Comment by Juliehzl** [comment]
I will look into it. @ivanignatiev have you tried REQUESTS_CA_BUNDLE  as above?

**Comment by jiasli** [comment]
It doesn't look like storage data-plane SDK is willing to support disabling SSL verification. We have to change `site-packages\certifi\cacert.pem` or `REQUESTS_CA_BUNDLE` to make it work.

**Comment by jiasli** [comment]
See https://github.com/Azure/azure-cli/issues/11436
