### ISSUE TITLE
`azure_namespace_package` Issue When `pip wheel azure-*.tar.gz`

### ISSUE THREAD

**Issue by mhbkb** [Azure/azure-cli#10232]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Got "error: error in setup.cfg: command 'bdist_wheel' has no such option 'azure_namespace_package'" when generating wheel from source.

**To Reproduce**
pip wheel azure-cli-telemetry-1.0.3.tar.gz
They should have the same issue in **`azure-cli-core`, `azure-cli-testsdk` and `azure-cli`**

**Expected behavior**
It should generate wheel successfully. A similar issue happened on other Azure Python packages, and it was fixed at: https://github.com/Azure/azure-storage-python/commit/c773644c7efa71fcc74d86e5824a6f5811b30d26#diff-9385f70944b305a1d3e417154acc5e40

**Environment summary**
I believe it can reproduced in any platform.

**Additional context**
Just a side note that we need to generate wheel from sdist because:
1. It is more secure;
2. It is platform independent.

**Comment by colemickens** [comment]
This is the same issue that seems to block `pypi2nix` from being able to package the Azure CLI for nixos/nixpkgs.

**Comment by colemickens** [comment]
probably related: https://github.com/Azure/azure-cli/issues/3160

**Comment by mhbkb** [comment]
Created https://github.com/Azure/azure-cli/pull/10497

**Comment by yonzhan** [comment]
Resolved by https://github.com/Azure/azure-cli/pull/10497
