### ISSUE TITLE
Invalid Object Az Storage Blob upload-batch .tif files

### ISSUE THREAD

**Issue by irfanmaroof** [Azure/azure-cli#10239]
## Describe the bug

**Command Name**
`az storage blob upload-batch`

**Errors:**
```
az: error: unrecognized arguments: readme.txt
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload-batch -d {} --account-name {} --account-key {} -s {} {}`

## Environment Summary
```
Darwin-18.0.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.70 *

```

**Comment by Juliehzl** [comment]
Hi @irfanmaroof It looks you expect to use specify two source files with space separated. At a result, the last argument `readme.txt` cannot be recognized, right? Actually, for `upload-batch` command, `-s` should be the ***directory*** where the files to be uploaded are located. Spaced-separated sources are not supported now.

**Comment by irfanmaroof** [comment]
az storage blob upload-batch -d "" --account-name "" --account-key "" -s .

I am providing the full current directory you can see above command with ".".
I have .tif files so I see issue for these files only.

**Comment by Juliehzl** [comment]
Can you send your debug message to my e-mail (zuh@microsoft.com )or post in comment  using `az storage blob upload-batch -d "" --account-name "" --account-key "" -s . --debug`?  Please remember to delete your ***account key*** information.

**Comment by irfanmaroof** [comment]
Today When I tried this command it worked.

Thanks for your help.
