### ISSUE TITLE
'az storage blob service-properties' doesn't support DefaultServiceVersion property

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#10235]
**Describe the bug**
[`az storage blob service-properties`](https://docs.microsoft.com/en-us/cli/azure/storage/blob/service-properties?view=azure-cli-latest) doesn't support [`DefaultServiceVersion`](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-service-properties) property.

**To Reproduce**
`az storage blob service-properties show --account-name xxx` is missing `DefaultServiceVersion`.

`az storage blob service-properties update --account-name xxx --set DefaultServiceVersion=2019-02-02` fails with 
> Couldn't find 'DefaultServiceVersion' in ''. Available options: ['cors', 'deleteRetentionPolicy', 'hourMetrics', 'logging', 'minuteMetrics', 'staticWebsite']

**Expected behavior**
`DefaultServiceVersion` is supported correctly. 

**Environment summary**
2.0.71 on Windows.

**Comment by jiasli** [comment]
PowerShell supports this operation: 
```
Update-AzStorageBlobServiceProperty ... -DefaultServiceVersion 2019-02-02
```
https://docs.microsoft.com/en-us/powershell/module/az.storage/update-azstorageblobserviceproperty?view=azps-2.5.0

**Comment by iotalambda** [comment]
The command is incorrect. This should work:
`az storage account blob-service-properties update --set defaultServiceVersion="2019-02-02" --account-name xxx`

**Comment by yonzhan** [comment]
add to S169

**Comment by Juliehzl** [comment]
Hi @jiasli it is already supported in `az storage account blob-service-properties`. Please have a try. 😊
