### ISSUE TITLE
az webapp config set --generic-configurations failed

### ISSUE THREAD

**Issue by PuffTMD** [Azure/azure-cli#10248]
## Describe the bug
When adding in --generic-configuraitons "{"clientAffinityEnabled": false}" to the webapp config set commands I receive an unexpected error.

**Command Name**
--generic-configurations "{"clientAffinityEnabled": false}"

**Errors:**
```
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
azure/cli/core/util.py, ln 244, in shell_safe_json_parse
    return json.loads(json_or_dict_string)
lib/python3.6/json/__init__.py, ln 354, in loads
    return _default_decoder.decode(s)
lib/python3.6/json/decoder.py, ln 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.6/json/decoder.py, ln 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

...

cli/command_modules/appservice/custom.py, ln 788, in update_site_configs
    config_name, value = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

## To Reproduce:
add --generic-configurations into the webapp config set command

- _Put any pre-requisite steps here..._
- `az webapp config set -g {} -n {} --generic-configurations {"clientAffinityEnabled": false} --slot {stagging} --ftps-state {Disabled} --php-version {5.6} --http20-enabled {true}`

## Expected Behavior
Update the ARR Affinity setting to false

## Environment Summary
```
Linux-4.9.184-linuxkit-x86_64-with
Python 3.6.4
Shell: bash

azure-cli 2.0.71

Extensions:
interactive 0.4.3

```

**Comment by panchagnula** [comment]
@MyronFanQiu the documentation example is misleading on the usage here to use --generic-configurations, add the JSON object to a son file & run the command as az webapp config set -g {}-n {} --generic-configurations @test.json & see if that works.

@yugangw-msft looking at the code the usage of the command as given in the documentation incorrect az webapp config set -g MyResourceGroup -n MyUniqueApp --generic-configurations "{"alwaysOn": true}" I wanted to check with you if this was originally supported & got regressed, since you originally implemented it. Please comment. Thanks!

**Comment by yugangw-msft** [comment]
The command missing the wrapping quotes: ```"{\"clientAffinityEnabled\": false}"```
We have a doc [here](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues) with suggestions of how to handle quotes.
Right now, we need to fix the sample from `-h` which misses the quotes
```
 turn on "alwaysOn" through a json with content '{"alwaysOn", true}'
        az webapp config set -g MyResourceGroup -n MyUniqueApp --generic-configurations
        "{"alwaysOn": true}"
```

**Comment by PuffTMD** [comment]
I've updated the command as indicated above 👆 but there is no change on the portal for webapp config for clientAffinityEnabled

**Comment by yugangw-msft** [comment]
then we will use this issue to track the doc issue on `az webapp config set`

**Comment by panchagnula** [comment]
clientAffinityEnabled is a site Object property so we use this command https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-update

--set is the equivalent of --generic-configurations so you can try using that as well.

**Comment by eholman** [comment]
@yugangw-msft The help changes got undone in the commit after yours: https://github.com/Azure/azure-cli/commit/573d0640d1b738bd1fb57d674f583da0ad5a608d#diff-40e30572983a53c248e7106702aabcc2L867 - so it's again not ok. 

The suggested doc regarding handling quotes was helpful though!

**Comment by poplaar** [comment]
As of June 2021, --generic-configurations doesn't seem to be working, what is the current status?

`az webapp config set -g myGroup -n myAppName --generic-configurations '{ "managedPipelineMode": "Classic" }'`

Errors : 

`The command failed with an unexpected error. Here is the traceback:
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 506, in shell_safe_json_parse
    return json.loads(json_or_dict_string, strict=strict)
  File "/opt/az/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/opt/az/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1169, in update_site_configs
    json_object = get_json_object(s)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 466, in get_json_object
    return _convert_to_snake_case(shell_safe_json_parse(json_string))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 531, in shell_safe_json_parse
    raise InvalidArgumentValueError(msg, recommendation=recommendation) from json_ex
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse JSON: { managedPipelineMode: Classic }
Error detail: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1175, in update_site_configs
    config_name, value = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)`

I also tried passing in as a json object --generic-configurations `@pipeClassic with the .json consisting of 
{ "managedPipelineMode": "Classic" } 

Error : 
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse JSON: @pipeClassic
Error detail: Expecting value: line 1 column 1 (char 0)
..ValueError: not enough values to unpack (expected 2, got 1)

Thanks,
AT

**Comment by mvitor** [comment]
@poplaar Your problem seems to be with your json input syntax. A Syntax like below worked to me in a Cmd/Win terminal. Hope it helps.
````
az webapp config set -g myGroup -n myAppName --generic-configurations "{\ "managedPipelineMode\": \"Classic\" }"
````

**Comment by poplaar** [comment]
![az_generic](https://user-images.githubusercontent.com/76943390/147331693-f99f52f1-dc51-4aec-bc7b-512bbe605b71.JPG)
@mvitor Thanks for the tip, but even with the syntax you suggest I receive an error 'Error detail: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)' and 'ValueError: not enough values to unpack (expected 2, got 1)' 
Also mentioning 'ValueError: not enough values to unpack (expected 2, got 1')

I have uploaded an image of how the Azure Cloud Shell app displays the command after typing it on the command line. Note where some of the text is in blue, indicating it is not quite able to parse it.

**Comment by LexLuengas** [comment]
Escape the double-quotes with a backtick, as documented in https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.3. This worked for us:
```
az webapp config set -g ... -n ... --generic-configurations "{\`"managedPipelineMode\`": \`"Classic\`"}"
```
