### ISSUE TITLE
storage account update returns a confusing error message when the specified key is of the incorrect type

### ISSUE THREAD

**Issue by adamday2** [Azure/azure-cli#10242]
**Describe the bug**
Updating a storage account to use a key-vault encryption source returns confusing error when the specified key is of the incorrect type (EC rather than RSA)

**To Reproduce**

1. Create a key-vault, create an EC-based key.
2. Create a storage account that is Microsoft.Storage backed
3. Attempt to update the storage account to use a KeyVault backed key
```
az storage account update --name mystorageaccount -g mygroup --encryption-key-vault https://mykeyvault.vault.usgovcloudapi.net/ --encryption-key-source Microsoft.Keyvault --encryption-key-name myexistingkey --encryption-key-version abcd1234 --verbose --debug
```

Returns error:
```
“cli.azure.cli.core.util : Values for request parameters are invalid: encryption.keyvaultproperties.keyname”
```

**Expected behavior**
As the portal does, the CLI should also indicate that the issue is with the type of key specified (must be RSA, not EC), rather than the keyname. 

**Environment summary**
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

**Additional context**
-

**Comment by Juliehzl** [comment]
Hi @adamday2 When we create new key with EC key type for storage account Encryption in portal, the action is still allowed and log message is the same as what azure cli shows.
<img src="https://user-images.githubusercontent.com/49508232/63327964-d720b600-c361-11e9-99fe-11ae77a5aad6.png" width=200 height=60 />
But for existing keys, EC type keys are not allowed to be selected in keys list and with information RSA is required.
<img src="https://user-images.githubusercontent.com/49508232/63328073-0800eb00-c362-11e9-9340-0bb825716585.png" width=150 height=100 />

I think both service team and cli should make some changes for this to give more accurate message.

**Comment by adamday2** [comment]
Thanks for investigating @Juliehzl . I see the difference now and agree!

**Comment by zhusijia26** [comment]
@Juliehzl could you please provide info about what action items are needed before we close the issue?

**Comment by zhusijia26** [comment]
Pending work is not in Storage team, thus removing Storage label

**Comment by Juliehzl** [comment]
@zhusijia26 Actually it is a storage related issue. We hope storage team can improve error message when users try to assign EC based key to storage account. Currently both for portal and CLI, we will return "Values for request parameters are invalid: encryption.keyvaultproperties.keyname", which is not accurate, and it should be key type error.

**Comment by zhusijia26** [comment]
@kartikshah9 Could you please find someone to help on the issue and get this issue reassigned? Thank you!

**Comment by amishra-dev** [comment]
@xiafu-msft can you please look at if we can provide better error messages from the python SDK.

**Comment by xiafu-msft** [comment]
This pr https://github.com/Azure/azure-sdk-for-python/pull/15782 should be able to address the problem, and it will be available in the release in next week. 
We only plan to improve track2, feel free to reopen this issue if you have any concern!
