### ISSUE TITLE
Set-Policy: An Example would be great especcialy how to set multiple permissions at once

### ISSUE THREAD

**Issue by ManuelMinkAtBOSCH** [Azure/azure-cli#10249]
az keyvault set-policy --name kv-name --certificate-permissions {backup, create} --upn myname@xxxx.com does not work e.g

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226e5769-f6c8-a480-db78-727fb96348ec
* Version Independent ID: 8ee06a2a-6eda-11be-3c8e-6ad948be207e
* Content: [az keyvault](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
`--certificate-permissions` should be "space-separated list of certificate permissions to assign". Please test if this works:
```
az keyvault set-policy --name kv-name --certificate-permissions backup create --upn myname@xxxx.com
```
