### ISSUE TITLE
Add more details to reduce customer confusion for "az network list-service-tags"

### ISSUE THREAD

**Issue by jispar** [Azure/azure-cli#10244]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the Problem**
https://docs.microsoft.com/en-us/cli/azure/network?view=azure-cli-latest#az-network-list-service-tags
The location parameter is causing lots of customer confusion. 
Wee need to add more details:

"The location that will be used as a reference for version (not as a filter based on location, you will get the list of service tags with prefix details across all regions but limited to the cloud that your subscription belongs to)."

**Comment by MyronFanQiu** [comment]
@jispar NP. I will update the help information of this commands
