### ISSUE TITLE
Can't Set Subscrition by ID?

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1025]
Surely I'm missing something...

**Comment by colemickens** [comment]
Can we have `az account set --id ID` rather than awkwardly overloading the `--name` flag?

**Comment by mayurid** [comment]
@colemickens : This does loook confusing.
@yugangw-msft: Can you look into this?

**Comment by JasonRShaver** [comment]
The weirdness is that by having one param that supports both, we don't have to consider the weirdness around which is required.  In that thinking, what is the least confusing name?

If we broke it out into two params, things get a bit more explicit, but now customers need to consider an extra option (which param) that only exists to clean up help text.

My gut is leaning towards two params (with error text and help parameter text to explain that one of the two is required)

Thoughts? @colemickens

**Comment by tjprescott** [comment]
I think as part of PR #1197 the plan is for this to be --subscription, which will take a name or id. @yugangw-msft

**Comment by colemickens** [comment]
I like the more explicit option but I won't complain about an overloaded single flag, as long as its called something like `--subscription`.

**Comment by yugangw-msft** [comment]
it is working now
