### ISSUE TITLE
az policy set-definition update

### ISSUE THREAD

**Issue by YRollHid** [Azure/azure-cli#10253]
## Describe the bug

**Command Name**
`az policy set-definition update`

**Errors:**
```
Unable to build a model: Cannot deserialize as [PolicyDefinitionReference] an object of type <class 'dict'>, DeserializationError: Cannot deserialize as [PolicyDefinitionReference] an object of type <class 'dict'>
Traceback (most recent call last):
python3.6/site-packages/msrest/serialization.py, ln 571, in body
    data = deserializer._deserialize(data_type, data)
python3.6/site-packages/msrest/serialization.py, ln 1258, in _deserialize
    self._deserialize(local_type, value)
...

python3.6/site-packages/msrest/serialization.py, ln 1476, in deserialize_iter
    type(attr)
msrest.exceptions.SerializationError: Unable to build a model: Cannot deserialize as [PolicyDefinitionReference] an object of type <class 'dict'>, DeserializationError: Cannot deserialize as [PolicyDefinitionReference] an object of type <class 'dict'>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az policy set-definition update --name {} --definitions {} --management-group {} --output {}`

## Environment Summary
```
Linux-4.15.0-1052-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.71

```

**Comment by yonzhan** [comment]
@Juliehzl  please take a look.

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
@YRollHid Could you please show me the specific parameters you used?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Comment by Folling** [comment]
Hello, we're experiencing the same problem. Should we create a separate issue or is it appropriate to revive this one? I can provide further details as required.
