### ISSUE TITLE
EventHub: CLI parameter for eventhub, skip-empty-archives is broken

### ISSUE THREAD

**Issue by v-Ajnava** [Azure/azure-cli#10259]
When attempting to set the skip-empty-archives property using Azure CLI, nothing changes. 

cli command:
az eventhubs eventhub update --resource-group borgetPAAS --namespace-name borgetEventHub --name borgethub --skip-empty-archives false 

cli was updated to the latest version before running the commands. 

Steps to Reproduce
----------------------
1.  In the portal create an eventhub namespace with an eventhub.
2. Enable "Capture" for the eventhub
3.  From the command line interface run
 C:\Users\borget>az eventhubs eventhub show --resource-group borgetPAAS --namespace-name borgetEventHub --name borgethub
{
  "captureDescription": {
    "destination": {
      "archiveNameFormat": "{Namespace}/{EventHub}/{PartitionId}/{Year}/{Month}/{Day}/{Hour}/{Minute}/{Second}",
      "blobContainer": "borgetehstorage",
      "name": "EventHubArchive.AzureBlockBlob",
      "storageAccountResourceId": "/subscriptions/6ab99e42-15a0-4dae-9838-ef343c8fc811/resourceGroups/borgetPAAS/providers/Microsoft.Storage/storageAccounts/borgetstoragetest"
    },
    "enabled": true,
    "encoding": "Avro",
    "intervalInSeconds": 300,
    "sizeLimitInBytes": 314572800,
    "skipEmptyArchives": null
  },
  "createdAt": "2019-06-18T14:42:16.840000",
  "id": "/subscriptions/6ab99e42-15a0-4dae-9838-ef343c8fc811/resourceGroups/borgetPAAS/providers/Microsoft.EventHub/namespaces/borgetEventHub/eventhubs/borgethub",
  "location": "West Europe",
  "messageRetentionInDays": 1,
  "name": "borgethub",
  "partitionCount": 2,
  "partitionIds": [
    "0",
    "1"
  ],
  "resourceGroup": "borgetPAAS",
  "status": "Active",
  "type": "Microsoft.EventHub/Namespaces/EventHubs",
  "updatedAt": "2019-08-13T10:01:07.683000"
}
4. Run the command to set the skip-empty-archives parameter to false 
C:\Users\borget>az eventhubs eventhub update --resource-group borgetPAAS --namespace-name borgetEventHub --name borgethub --skip-empty-archives false
{
  "captureDescription": {
    "destination": {
      "archiveNameFormat": "{Namespace}/{EventHub}/{PartitionId}/{Year}/{Month}/{Day}/{Hour}/{Minute}/{Second}",
      "blobContainer": "borgetehstorage",
      "name": "EventHubArchive.AzureBlockBlob",
      "storageAccountResourceId": "/subscriptions/6ab99e42-15a0-4dae-9838-ef343c8fc811/resourceGroups/borgetPAAS/providers/Microsoft.Storage/storageAccounts/borgetstoragetest"
    },
    "enabled": true,
    "encoding": "Avro",
    "intervalInSeconds": 300,
    "sizeLimitInBytes": 314572800,
    "skipEmptyArchives": null
  },
  "createdAt": "0001-01-01T00:00:00",
  "id": "/subscriptions/6ab99e42-15a0-4dae-9838-ef343c8fc811/resourceGroups/borgetPAAS/providers/Microsoft.EventHub/namespaces/borgetEventHub/eventhubs/borgethub",
  "location": "West Europe",
  "messageRetentionInDays": 1,
  "name": "borgethub",
  "partitionCount": 2,
  "partitionIds": [],
  "resourceGroup": "borgetPAAS",
  "status": "Active",
  "type": "Microsoft.EventHub/Namespaces/EventHubs",
  "updatedAt": "0001-01-01T00:00:00"
}

- -
In the example above the parameter is null but even if the parameter has been set to true using the portal, the cli command will not be able to change the value. 

- -

------------------------------------------------------------------------
ADDITIONAL INFORMATION FROM AZURE SUPPORT CENTER

Support Request Number: 119081224001806

Subscription Id: 9367bab8-a423-4820-bc39-00e1aaac685e

Resource Group:rxr-idi-qe-rg

Resource Uri: rxr-idi-qe-eh

Tenant Id: 92cb778e-8ba7-4f34-a011-4ba6e7366996

**Comment by v-Ajnava** [comment]
Issue was reported over ICM : https://icm.ad.msft.net/imp/v3/incidents/details/139260789/home

**Comment by yonzhan** [comment]
@v-Ajnava  what is the status of this issue ?

**Comment by yonzhan** [comment]
@v-Ajnava how is the status of this issue ?
