### ISSUE TITLE
"az rest": allow the HTTP request body to be taken from a file (similar to curl's "--data @filename")

### ISSUE THREAD

**Issue by ogerardin** [Azure/azure-cli#10268]
**Is your feature request related to a problem? Please describe.**
When using `az rest` under Windows, if you need to pass a large body you quickly hit the length limit for a single command.

**Describe the solution you'd like**
I'd like to be able to put the body in a file and pass a reference to that file instead of the the actual body to the `az rest` command, e.g. 
`az rest -m PUT -u https://management.azure.com/bla --body @filename`

**Describe alternatives you've considered**
The alternative is to use curl instead but it requires obtaining the subscription ID and the authentication token beforehand:
```
az account show --query id
az account get-access-token --query accessToken
curl -X PUT "https://management.azure.com/subscriptions/%SUBSCRIPTION_ID%/..." -H "Authorization: Bearer %TOKEN%" -H "Content-Type: application/json" --data @filename

```
**Additional context**
According to the doc, headers and query params can already be loaded from a file using the @ notation, so it would seem natural to extend this to the body.

**Comment by jiasli** [comment]
`--body` actually does support @ notation. @ notation applies to all CLI args. https://github.com/Azure/azure-cli/blob/516d297a9f1276bd9a9208e4a43281238b0c496e/src/azure-cli-core/azure/cli/core/commands/__init__.py#L83 

I have created PR #10632 to fix the help message.
