### ISSUE TITLE
Investigate reducing our Docker image size

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#1027]
Our docker image size is currently ~750mb, can we reduce this?  

```
REPOSITORY                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
azuresdk/azure-cli-python   latest              ab693813f2b5        About an hour ago   751.1 MB
```

**Comment by JasonRShaver** [comment]
Standard Python image:
https://hub.docker.com/r/library/python/tags/ 267mb

And an article from Steve if it helps:
https://blogs.msdn.microsoft.com/stevelasker/2016/09/29/building-optimized-docker-images-with-asp-net-core/

**Comment by derekbekoe** [comment]
Currently, our Dockerfile uses `FROM python:3.5` which on its own is 265 MB.
We could look at using an [Alpine Linux image](https://hub.docker.com/_/alpine/) instead.

I see 3.5-alpine - 28 MB available at https://hub.docker.com/r/library/python/tags/.

The main question would be whether this smaller image has the dependencies we need and behaves in a similar way to the `python:3.5` image.

**Comment by pcgeek86** [comment]
The best way to find out would be to give it a shot. I could probably take a look at this at some point. I'll be out the next week at a conference though. Gonna be talking about this tool there.

http://www.itdevconnections.com/dc16/Public/PopUpDetails.aspx?Display=Session&Id=1015448
