### ISSUE TITLE
api-version=2017-10-01-preview was not found

### ISSUE THREAD

**Issue by Alonreznik** [Azure/azure-cli#10277]
## Describe the bug

**Command Name**
`az sql dw list`

**Errors:**
```
The specified resource 'https://management.eastus2.control.database.windows.net/modules/AzureResourceManager/subscriptions/<subscriptionId>/resourceGroups/<RG>/providers/Microsoft.Sql/servers/<servers>/<servername>/databases?api-version=2017-10-01-preview' was not found.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sql dw list -g {} -s {}`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.71

```

**Comment by jaredmoo** [comment]
Following up with @Alonreznik by a private channel.

**Comment by jaredmoo** [comment]
The issue looked like incorrect parameter substitution on the command line.
