### ISSUE TITLE
workernode-count on hdinsight resize is not working

### ISSUE THREAD

**Issue by stijn192** [Azure/azure-cli#10271]
az hdinsight resize does not work with a given "workernode-count" - rather it expects a "--target-instance-count".

I don't know what is the preferred behaviour, but the command in documentation does not work with --workernode-count, but does with --target-instance-count. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b788579d-d73c-df07-abfe-1ab149da330a
* Version Independent ID: 057f1657-8841-39ce-38d0-29f154c0163e
* Content: [az hdinsight](https://docs.microsoft.com/en-us/cli/azure/hdinsight?view=azure-cli-latest#az-hdinsight-resize)
* Content Source: [src/azure-cli/azure/cli/command_modules/hdinsight/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/hdinsight/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by aim-for-better** [comment]
I am looking at this issue

**Comment by aim-for-better** [comment]
@stijn192  Could you please retry it?
I resized a cluster successfully by running 
```
az hdinsight resize -n mycluster -g mygroup --workernode-count 5
```

**Comment by aim-for-better** [comment]
I have tested, `--workernode-count` works well in the latest azure cli.  I want customer to retry but customer didn't reply. Just closed this issue. If customer still have such issue, they can reopen, but please provide azure cli version so that we can save confirmation time.
