### ISSUE TITLE
Key Vault Certificate command doesn't support certificate transparency flag for OneCert issuer

### ISSUE THREAD

**Issue by jasonxdhu** [Azure/azure-cli#10276]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

    When use command "az keyvault certificate create --vault-name {vault_name} -p @{json_body} -n {cert_name}" to create a certificate issued by OneCert, it failed with error message "The Self issuer does not support Certificate Transparency. Disable Certificate Transparency and try again."
    The "Self issuer" is not correct since the issuer should be "OneCert issuer".

**To Reproduce**
Steps to reproduce the behavior.

    1. Create a key-vault
    2. Set PermissionsToCertificates of the key-vault to full permission, such as get,create,update,delete,import...
    3. Whitelist your test domain with OneCert.
    4. Run command "az keyvault certificate create --vault-name {vault_name} -p @{json_body} -n {cert_name}"

Below is a sample json body with transparency flag is set to "true":
{
  "key_props": {
    "exportable": true,
    "kty": "RSA",
    "key_size": 2048,
    "reuse_key": true
  },
  "secret_props": {
    "contentType": "application/x-pkcs12"
  },
  "x509_props": {
    "subject": "CN=*.some.whitelisted.domain.net",
    "key_usage": [
      "cRLSign",
      "dataEncipherment",
      "digitalSignature",
      "keyEncipherment",
      "keyAgreement",
      "keyCertSign"
    ],
    "validity_months": 12
  },
  "lifetime_actions": [
    {
      "trigger": {
        "days_before_expiry": 60
      },
      "action": {
        "action_type": "AutoRenew"
      }
    }
  ],
  "issuer": {
    "name": "OneCertCA",
    "cert_transparency": true
  },
  "attributes": {}
}

**Expected behavior**

    The request should be successful instead of "The Self issuer does not support Certificate Transparency...".
    At least, if failed, the error message should not be "Self" issuer because it tries to create a cert with onecert issuer.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

    Windows-10 with latest CLI is installed.

**Additional context**

**Comment by jiasli** [comment]
I tried to repro and got `"The OneCert issuer does not support Certificate Transparency. Disable Certificate Transparency and try again."` from the raw HTTP request. I need further confirmation with Azure Key Vault service team. 

At the same time, could you check if `OneCertCA` is configured correctly by running
```
az keyvault certificate issuer list --vault-name "xxx"
```

Meanwhile, could you update to [Azure CLI 2.0.71](https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest) to make sure the latest REST version is used?

**Comment by Joon-L** [comment]
@jiasli I was able to repro this with the 2.0.71 CLI. The OneCertCA is correctly set up as I get the response
```
[
  {
    "id": "https://some-key-vault.vault.azure.net/certificates/issuers/OneCertCA",
    "provider": "OneCert"
  }
]
```

**Comment by Joon-L** [comment]
@jiasli Do we have any updates regarding this issue?

**Comment by jiasli** [comment]
Key Vault service team has been notified and is currently investigating it.

**Comment by Joon-L** [comment]
@jiasli Were there any updates from the Key Vault team?

**Comment by sebansal** [comment]
@jiasli can you remove keyvault label and add OneCert?

**Comment by yonzhan** [comment]
@bim-msft  to help with Keyvault.

**Comment by sebansal** [comment]
Adding @rashmi-jha @RandalliLama

**Comment by sebansal** [comment]
CT is supported.  CT will be on by default in any certs issued by OneCert.
