### ISSUE TITLE
Unable to load extension 'resource-graph'. Use --debug for more information.

### ISSUE THREAD

**Issue by kasunsjc** [Azure/azure-cli#10289]
> ### `az feedback` auto-generates most of the information requested below, as of CLI az --version
azure-cli                         2.0.71

command-modules-nspkg               2.0.3
core                              2.0.71
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
aks-preview                        0.4.5
azure-devops                      0.12.0
resource-graph                     0.1.8
interactive                        0.4.2

Python location '/usr/local/Cellar/azure-cli/2.0.71/libexec/bin/python'
Extensions directory '/Users/kasunrajapakse/.azure/cliextensions'

Python (Darwin) 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Terraform Version - Terraform v0.12.6

**Describe the bug**
When I run terraform plan it says the bellow Azure CLI Error 
**Error obtaining Authorization Token from the Azure CLI: Error retrieving access token from Azure CLI: WARNING: Unable to load extension 'resource-graph'. Use --debug for more information.**

**To Reproduce**
I notice that when I run az it shows the same error in yellow color

az
Unable to load extension 'resource-graph'. Use --debug for more information.

     /\
    /  \    _____   _ _  ___ _
   / /\ \  |_  / | | | \'__/ _\
  / ____ \  / /| |_| | | |  __/
 /_/    \_\/___|\__,_|_|  \___|

Welcome to the cool new Azure CLI!

Use `az --version` to display the current version.
Here are the base commands:

**Environment summary**
Using MacOS latest version

**Additional context**

**Comment by dharmab** [comment]
I get this when running various commands as well.

**Comment by kasunsjc** [comment]
Below will resolve the issue

You can remove it and add it again. I got similar error Error obtaining Authorization Token from the Azure CLI: Error retrieving access token from Azure CLI: WARNING: Unable to load extension 'resource-graph'. Use --debug for more information. . This was fixed after following commands

az extension remove --name resource-graph
az extension add --name resource-graph

This will update to latest version

**Comment by yonzhan** [comment]
Can we close this issue ?

**Comment by jimsander** [comment]
I had the same issue and it was resolved with fix by @kasunsjc 

```
$ az account list -o tsv --query "[? isDefault ].name"
Unable to load extension 'resource-graph'. Use --debug for more information.
_REDACTED_.Services
$ sh -x /tmp/fix
+ az extension remove --name resource-graph
Unable to load extension 'resource-graph'. Use --debug for more information.
+ az extension add --name resource-graph

$ az account list -o tsv --query "[? isDefault ].name"
_REDACTED_.Services
```

**Comment by jiasli** [comment]
You may also use `az extension update -n resource-graph` to update to the latest version. If the issue persists, please provide the detailed log with `--debug`.
