### ISSUE TITLE
--add parameter?

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-cli#10287]
What is the --add parameter for (on az sql server conn-policy update)? The info about "objects" is very vague (and seems to have maybe come from az resource update). Can you add multiple servers or DBs or something here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d84bcc6-6274-7c1b-3394-c8be820ec786
* Version Independent ID: 67fc9ae8-4e2b-f58b-fde9-0c3f5ab8a24d
* Content: [az sql server conn-policy](https://docs.microsoft.com/en-us/cli/azure/sql/server/conn-policy?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
`--add` is a **generic update** operation which applies to all resources. Yes, it does similar things as `az resource update`, but you only need to provide elements to be added. Please see https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#using-the-generic-update-arguments for more detailed usages.

The structure of `connectionPolicies` is at https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/2014-04-01/servers/connectionpolicies

**Comment by dcbrown16** [comment]
Ah, I see, so in this particular case it's pretty meaningless since there is only that one property which already has its own parameter. Great info, thanks for the quick response! Closing.
