### ISSUE TITLE
Log profile location being set to null when updating categories

### ISSUE THREAD

**Issue by khabbabs** [Azure/azure-cli#10283]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
First I created a log profile with one of the three defined categories  of Delete Write Action.
when attempting to update the categories I get an error where the location is being set to null

**To Reproduce**
create log profile 
example:
 az monitor log-profiles create --categories "Action" "Delete" --days 0 --enabled true --location eastus --locations centralus --name MyLogProfile --storage-account-id "STORAGE_ID"

this creates a log profile which looks like this...
{
  "categories": [
    "Action",
    "Delete"
  ],
  "id": "",
  "identity": null,
  "kind": null,
  "location": "eastus",
  "locations": [
    "centralus"
  ],
  "name": "MyLogProfile",
  "retentionPolicy": {
    "days": 0,
    "enabled": true
  },
  "serviceBusRuleId": null,
  "storageAccountId": "",
  "tags": null,
  "type": null
}

attempt to update the categories to include all 3 with the update command

az monitor log-profiles update --name MyLogProfile --set categories=["Action","Delete","Write"]

error output

*validation error: Parameter 'LogProfileResource.location' can not be None.*

**Expected behavior**

expected behavior is for the update command to properly update the log profile 

{
  "categories": [
    "Action",
    "Delete",
    "Write"
  ],
  "id": "",
  "identity": null,
  "kind": null,
  "location": "eastus",
  "locations": [
    "centralus"
  ],
  "name": "MyLogProfile",
  "retentionPolicy": {
    "days": 0,
    "enabled": true
  },
  "serviceBusRuleId": null,
  "storageAccountId": "",
  "tags": null,
  "type": null
}

**Environment summary**

on azure cli cloud shell

az --version
azure-cli                         2.0.71

command-modules-nspkg               2.0.3
core                              2.0.71
nspkg                              3.0.4
telemetry                          1.0.3

**Additional context**
I'm getting the same error when attempting to update the list of locations. maybe my syntax is incorrect? but I can't find much help from the available documentation.

**Comment by MyronFanQiu** [comment]
@khabbabs Hello. I think you're right. I tested the command "az monitor log-profiles show" and the response showed that the location was set to null. So I will invite service attention. Meanwhile, I will try to figure out a workaround to unblock you.

**Comment by MyronFanQiu** [comment]
@snehithm @Dalubash Hello. I'm not sure whether you're the right person I should contact. Could you please take a look at this issue and help me figure out who is the right person I should contact?

**Comment by Dalubash** [comment]
@nkiest Please update.

**Comment by nkiest** [comment]
@asheniam can you help here?

**Comment by asheniam** [comment]
We are looking at a fix in GET logprofiles API which will populate the location property correctly to 'global'.  I believe that should address the issue the customer is facing.  The fix is under testing and we want to roll it out in the next few weeks.

**Comment by prbdwd** [comment]
Seems like the issue still exists. CLI `az monitor log-profiles update --name MyLogProfile --set categories=["Action","Delete","Write"]` is not working throws same 'validation error: Parameter 'LogProfileResource.location' can not be None.'

**Comment by MyronFanQiu** [comment]
@asheniam Hello. Did you solve this issue on server side?

**Comment by yonzhan** [comment]
@asheniam any update?

**Comment by yonzhan** [comment]
Per Andy, Log profile will be replaced by diagnostic settings. Do you think we can close this issue or wait for service team to fix this bug ?

**Comment by teamcitytest3** [comment]
any updates here?
