### ISSUE TITLE
Issue with ResourceGroup when creating a new WebApp

### ISSUE THREAD

**Issue by Trinakriae** [Azure/azure-cli#10280]
**Describe the bug**
I am trying to create a WebApp using the CLI but I get an error `'NoneType' object has no attribute location` when launching `az webapp create`. I guess this error happens since it is targeted the wrong ResourceGroup.
When I launch the command `az webapp list` I get the error `ResourceGroupNotFound - Resource group <resourceGroupName> could not be found` where `<resourceGroupName>` is not a ResourceGroup that exists in any of my Azure subscriptions. I verified this with both the web portal and the CLI command `az group list`. 

**To Reproduce**
1) Login into my Azure account with `az login`,
2) Check my active subscriptions with `az account list --output table`,
3) Select the desired subscription from the list shown at point (2) with `az account set --subscription <subscriptionName>`,
4) Create the webapp with `az webapp create --resource-group <resourceGroupName> --plan <subscriptionName> --name <appName>`. I get the error `'NoneType' object has no attribute location` 
5) I check the existing web apps by executing `az webapp list` and I get the error `ResourceGroupNotFound - Resource group <resourceGroupName> could not be found` where `<resourceGroupName>` is not a ResourceGroup that exists in any of my Azure subscriptions

**Expected behavior**
I expect to have the web app correcly created in point (4) and to see the correct list of web apps in point (5). There should be a way to uniquely target the ResourceGroup as it happens for the Subscription

**Environment summary**
CLI version:  2.0.71 / OS version: Windows 10 / Shell Type: Powershell

**Comment by panchagnula** [comment]
Run the command with --debug flag to see what the error message is. I assume its because the RG doesn't exist or is not not in the right subscription.  you can also to try to run the command with --subscription parameter to see if that resolves this as well.

**Comment by Trinakriae** [comment]
@panchagnula thanks for your help. However the issue solved itself, I still do not know why it wasn't targeting the wrong resource group, I tried again the command batch and it worked.
