### ISSUE TITLE
CosmosDB update / enable-multiple-write-locations = false is not allowed

### ISSUE THREAD

**Issue by chshihMSFT** [Azure/azure-cli#10282]
The option for disable the Azure Cosmos DB Multi-region Write feature is not available anymore. 
Azure CLI command would fail as shown below which is expected and intended.    
```az cosmosdb update -n cosmosdbname -g resourcename --enable-multiple-write-locations false```
> Operation failed with status: 'BadRequest'. Details: Setting EnableMultipleWriteLocations = false is not allowed for existing accounts. Please visit https://aka.ms/multi-master-benefits for more information.
> ActivityId: 6e03cd0a-c357-11e9-8782-4845205e9f06, Microsoft.Azure.Documents.Common/2.5.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc8d652-2eda-296f-28ea-8d5f1ea855b3
* Version Independent ID: 80b87995-d339-61e9-1cac-b5c9ad6efe5e
* Content: [az cosmosdb](https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest#az-cosmosdb-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by shurd** [comment]
Hi @chshihMSFT thank you for opening this issue. You are correct that we no longer allow you to disable multiple write locations via the CLI. As you point out, you get the BadRequest error. Is there a question regarding this behavior? We have the flag as an option because you can enable multiple write locations via the CLI.

**Comment by shurd** [comment]
I am going to close this issue now. If you have a question regarding this behavior, you can open another issue.

**Comment by xtianus79** [comment]
> Hi @chshihMSFT thank you for opening this issue. You are correct that we no longer allow you to disable multiple write locations via the CLI. As you point out, you get the BadRequest error. Is there a question regarding this behavior? We have the flag as an option because you can enable multiple write locations via the CLI.

What does this mean? lol they literally contradict each other.

**Comment by jainpr** [comment]
@xtianus79 : Don't think they contradict. The CLI option is there to allow enabling. Using the same option to disable is however not allowed.

**Comment by chshihMSFT** [comment]
Update:
This parameter **--enable-multiple-write-locations** has been updated already, now you can pass value "**true**" to enable multi-region writes feature, or "**false**" to disable it.
