### ISSUE TITLE
Cannot remove VNET subnet for KeyVault when subnet ID contains uppercase letters

### ISSUE THREAD

**Issue by jasonxdhu** [Azure/azure-cli#10286]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When run 
az keyvault network-rule remove --subnet "<my-subnet-id>" --resource-group "<my-resource-group>" --name "<my-key-vault-name>"
It fails to remove the subnet without error when "<my-subnet-id>" contains upper-case letters.

**To Reproduce**
Steps to reproduce the behavior.

The following command will not remove subnet because text “/Microsoft.Network/virtualNetworks/”:
az keyvault network-rule remove --subnet "/subscriptions/11111111-aa7f-4b05-86b7-61be294b8be0/resourcegroups/foo-vnet-res-group/providers/Microsoft.Network/virtualNetworks/foo-vnet-test-02/subnets/foo-test02" --resource-group "foo-vnet-res-group" --name "foo-vnet-test-33"

The following command does work because subnet-id contains all lower-case letters:
az keyvault network-rule remove --subnet "/subscriptions/11111111-aa7f-4b05-86b7-61be294b8be0/resourcegroups/foo-vnet-res-group/providers/microsoft.network/virtualnetworks/foo-vnet-test-02/subnets/foo-test02" --resource-group "foo-vnet-res-group" --name "foo-vnet-test-33"

**Expected behavior**
The subnet should be removed, e.g. the command “az keyvault network-rule list” should not include removed subnet ID.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
Latest CLI in Window 10

**Additional context**

**Comment by jiasli** [comment]
Created PR #10365 to fix this issue.
