### ISSUE TITLE
--set documentation

### ISSUE THREAD

**Issue by khabbabs** [Azure/azure-cli#10297]
--set needs more verbose documentation showing examples of how to update locations and categories.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58a5a5bd-c481-72b8-0cec-05c8795b4469
* Version Independent ID: dba52140-3799-cbc3-4628-c2e77d246eb1
* Content: [az monitor log-profiles](https://docs.microsoft.com/en-us/cli/azure/monitor/log-profiles?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
`--set` is a **generic update** operation which applies to all resources. Please see https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#using-the-generic-update-arguments for more detailed usages.

As for the structure of JSON body, please check [Log Profiles - Create Or Update](https://docs.microsoft.com/en-us/rest/api/monitor/logprofiles/createorupdate) REST API.
