### ISSUE TITLE
functionapp:Python function App .zip file issue 

### ISSUE THREAD

**Issue by srini99mkl** [Azure/azure-cli#10293]
Hello, I have created my Python code as function app and the published to Azure, it uploaded as .zip file., How do i call my function in Azure?

**Comment by MyronFanQiu** [comment]
@srini99mkl I'm not sure is this question related with CLI. Usually, you need to set the trigger for you function. Here is the doc you can refer. https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-cosmos-db-triggered-function

**Comment by srini99mkl** [comment]
Thank you for the quick reply.  My code is not related to cosmosDB. My code reads a files from Gen2 file storage and writes into SQLDW.  Why can’t I see my function at all. How do I pass parameters to my function when I call it.

To my main.py, I will have to pass three parameters… any help would be greatly appreciated.

Thanks,
Srini

**Comment by ahmedelnably** [comment]
@srini99mkl this is a general Azure Functions questions, please open an issue here https://github.com/Azure/azure-functions
