### ISSUE TITLE
storage container create when name existing no error message

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-cli#10300]
**Describe the bug**
`az storage container create` using a existing name

return `created: fasle` no error message to show name existed

**To Reproduce**
`az storage container create` using a existing name

**Expected behavior**
Show correct message "The name exists"

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by Juliehzl** [comment]
For my traige only

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
--fail-on-exist can help.
