### ISSUE TITLE
webapp:Accessing Storage from another subscription

### ISSUE THREAD

**Issue by svelango** [Azure/azure-cli#10303]
Can az webapp config storage-account add  access storage account in another subscription if roles are set? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4892bb1c-5cb4-91fa-325b-f5180cd05c3a
* Version Independent ID: 8c9a9a0e-5b36-4039-72c5-b28fd0bb9fd4
* Content: [az webapp config storage-account](https://docs.microsoft.com/en-us/cli/azure/webapp/config/storage-account?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp/config/storage-account.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/storage-account.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
i am not sure i completely understand the question but have you tried using the --subscription parameter from the command? https://docs.microsoft.com/en-us/cli/azure/webapp/config/storage-account?view=azure-cli-latest#feedback

**Comment by svelango** [comment]
I have a Webapp running in A subscription but want to mount a storage account in B subscrption. The --subscription if I understand right it the subscription where webapp lives.

**Comment by yonzhan** [comment]
webapp

**Comment by btardif** [comment]
This is not a limitation of the CLI, using a storage account across subscriptions as a BYOS mount is not currently supported.

The right forum to request this is Uservoice: https://feedback.azure.com/forums/169385-web-apps/filters/top
