### ISSUE TITLE
az storage blog sync sets content-type on .js files to text/plain

### ISSUE THREAD

**Issue by vidarkongsli** [Azure/azure-cli#10302]
**Bug description**
When using `az storage blob sync` to synchronize files to an Azure storage blob container, `.js` files get content-type `text/plain`.

**Expected behavior**
Content type should be `application/javascript`.

**Environment summary**
* azure-cli                         2.0.70
* command-modules-nspkg               2.0.3
* core                              2.0.70 **
* nspkg                              3.0.4
* telemetry                          1.0.3
* Extension: azure-devops                      0.12.0
* Running in Azure DevOps task 'Azure CLI' version 1.155.1

**Additional context**
Using Azure DevOps task 'AzCopy' instead yields the correct content type.

**Comment by vidarkongsli** [comment]
Actual command run by the Azure DevOps task: `az storage blob sync --container $web --source D:\a\r1\a\_web\drop --account-name nottherealname`

**Comment by Juliehzl** [comment]
@vidarkongsli  Have you specify content-type when using AzCopy? If you just using `azcopy sync “D:\a\r1\a\_web\drop” $destination_container_url` , I think the .js file may still in text/plain. But I think we should support specifying content-type for such command.

**Comment by vidarkongsli** [comment]
The AzCopy Azure DevOps Task runs the following, which works as far as content-type is concerned: `& "AzCopy\AzCopy.exe" /Source:"d:\a\r1\a\_web\drop" /Dest:"https://nottherealname.blob.core.windows.net/``$web" /@:"d:\a\_temp\xpegyge5mi8mvvhfle67ds4i" /XO /Y /SetContentType /Z:"AzCopy" /V:"AzCopy\AzCopyVerbose_de1f860a-99a8-44d6-9a60-1877695d89d2.log" /S`

So yes, the switch `/SetContentType` is used.

**Comment by yonzhan** [comment]
It is blocked by azcopy issue.

**Comment by Juliehzl** [comment]
@vidarkongsli  we will add content-type flag for azure cli command later, but need some support from azcopy team.

**Comment by rerime** [comment]
Is any progress?

**Comment by Lectem** [comment]
I just encountered the issue too while using the AzureFileCopy task.
It seems like by default, windows does not have the content type set for .js (or some application removes it).

a workaround is to have the following script:

```yaml

        - script: reg add HKCR\.js /v "Content Type" /d application/javascript /f
          displayName: Add .js content type to registry
```

**Comment by Juliehzl** [comment]
`az storage blob sync` depends on AzCopy and in latest AzCopy 10.3.4, setting content type is not supported. @zezha-msft Can you help plan for content type setting in AzCopy support?

**Comment by zezha-msft** [comment]
Hi @Juliehzl, we will target 10.5 for this fix. Thanks for the reminder!

**Comment by yonzhan** [comment]
@zezha-msft was this issue resolved?

**Comment by Juliehzl** [comment]
please try in next release.
