### ISSUE TITLE
--verbose is way to verbose for "normal" use

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#1030]
We should clean up the spew from --verbose to address "normal" usage where the user just wants to see some progress indicators. Today, there is way too much stuff being output for the casual observer. 

Related: #987 #1010

**Comment by tjprescott** [comment]
First target should be the command table dump. It has no value in --verbose.

**Comment by johanste** [comment]
That is a reasonable first step :). 

My suggestion is that we (whoever tackles this) comes up with a suggestion on what they'd like to see for a couple of commands w. the --verbose flag set:

- Simple paged list command (i.e. vm list)
- Simple show command (i.e. vm show)
- Long running post operation (i.e. vm stop)
- Long running resource create (i.e. vm create)

and make sure that get the appropriate tracing/level in place to match.

**Comment by mayurid** [comment]
@johanste : take a look
