### ISSUE TITLE
The default for queue is 5GB, not 1GB

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-cli#10304]
[`az servicebus queue create`](https://docs.microsoft.com/en-us/cli/azure/servicebus/queue?view=azure-cli-latest#az-servicebus-queue-create) creates a queue of 5GB by default on Standard tier, not 1GB as stated in the document.

Have not validated the Premium tier.

> --max-size
> Maximum size of queue in megabytes, which is the size of the memory allocated for the queue. Default is 1024. Max for Standard SKU is 5120 and for Premium SKU is 81920.
>
> accepted values: 1024, 10240, 2048, 20480, 3072, 4096, 40960, 5120, 81920

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2889060b-e555-544f-e968-34bf40efb5eb
* Version Independent ID: 70d5931b-5343-f6f8-ebf0-0e79cb0541f5
* Content: [az servicebus queue](https://docs.microsoft.com/en-us/cli/azure/servicebus/queue?view=azure-cli-latest#az-servicebus-queue-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/servicebus/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/servicebus/_help.py)
* Service: **service-bus**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jfggdl** [comment]
Just got this in our queue. @axisc should be able to validate the queue size and update the documentation, if needed. Thanks for reporting this documentation issue.

**Comment by axisc** [comment]
Thanks for raising this, @SeanFeldman. It's 1 GB for Premium.
We'll update the documentation appropriately.

**Comment by v-Ajnava** [comment]
Fixed,  please use latest CLI release
