### ISSUE TITLE
CSS 

### ISSUE THREAD

**Issue by asoccer** [Azure/azure-cli#10316]
Text box at the top is way out of page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2081b80b-2200-ea1a-2131-65602af2ae55
* Version Independent ID: 90a394bc-0235-b9af-fa5d-4d7e235f50df
* Content: [az vm unmanaged-disk](https://docs.microsoft.com/en-us/cli/azure/vm/unmanaged-disk?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by qwordy** [comment]
Thank you for your feedback. We will try to fix it.

**Comment by Juliehzl** [comment]
@daxianji007 Please help deal with malformed docs. Thanks.

**Comment by Juliehzl** [comment]
@asoccer After our investigation, this is a bug for docs team. I open a similar issue for docs team https://github.com/MicrosoftDocs/azure-docs-cli/issues/1569. @daxianji007 will follow up it and let's waiting for his update.

**Comment by Juliehzl** [comment]
@asoccer It is already fixed. Thanks for you feedback!
