### ISSUE TITLE
NodeJS Runtime Is Not Created

### ISSUE THREAD

**Issue by opticyclic** [Azure/azure-cli#10310]
Running this command:

    az webapp create -g test -p Test-App-Service  -n AzCommandPlan --runtime "node|8.10"

Does not create a web app with a Node.JS runtime of 8.10.

When I go to the portal after it has created I see the Application property `WEBSITE_NODE_DEFAULT_VERSION 8.10`.

However, when I go to the web console in the portal and check I see:

    node --version
    v0.10.40

Whereas if I create the web app in the portal I see:

    node --version
    v8.10.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-create)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by opticyclic** [comment]
What is interesting is that `Node 8.10` is available in the portal and `8.10` is listed in the runtimes

    az webapp list-runtimes|grep "8.10"
    "node|8.10",

However, when you actually go onto the server that is created from the portal you will see that the version installed is `D:\Program Files (x86)\nodejs\8.10.0`

**Comment by panchagnula** [comment]
i am not sure what the console on portal you are referring to. The one way to figure out on portal the runtime/stack set is go to Configuration ->General Settings tab & check what the stack & version values are.

if this doesn't match 8.10 let us know - this could be a portal issue & not really a CLI issue. 

The version on the app is set by kudu/scm so i would navigate to https://<appname>.scm.azurewebsites.net/Env#envVariables -> & check the Framework & Framework_version. If this not match the expected values please do share that info here & re-open the issue.

**Comment by opticyclic** [comment]
Why is this closed?
When you check the runtimes from the command line you get this:

    az webapp list-runtimes|grep "8.10"
    "node|8.10",

Then when you try to use that in the command it doesn't create an 8.10 runime:

    az webapp create -g test -p Test-App-Service  -n AzCommandPlan --runtime "node|8.10"

**Comment by panchagnula** [comment]
I am trying to understand how you are verifying the command line is not creating the right runtime - like I mentioned above if you are trying to use portal to confirm use the Configuration menu to check the setting or the scm site - & let us know what you see. Thanks!

**Comment by opticyclic** [comment]
Interestingly the runtime list is now different.

```
az webapp list-runtimes
[
  "aspnet|V4.8",
  "aspnet|V3.5",
  "DOTNETCORE|2.1",
  "DOTNETCORE|3.1",
  "DOTNET|5.0",
  "node|10.6",
  "node|10.10",
  "node|10.14",
  "node|12-lts",
  "php|7.2",
  "php|7.3",
  "php|7.4",
  "python|3.6",
  "java|1.8|Tomcat|7.0",
  "java|1.8|Tomcat|8.0",
  "java|1.8|Tomcat|8.5",
  "java|1.8|Tomcat|9.0",
  "java|1.8|Java SE|8",
  "java|11|Tomcat|7.0",
  "java|11|Tomcat|8.0",
  "java|11|Tomcat|8.5",
  "java|11|Tomcat|9.0",
  "java|11|Java SE|8"
]
```

Probably due to 8 reaching EOL.
