### ISSUE TITLE
data lake gen2 error

### ISSUE THREAD

**Issue by jumping** [Azure/azure-cli#10318]
## Describe the bug

**Command Name**
`az storage blob list`

**Errors:**
```
Blob API is not yet supported for hierarchical namespace accounts. ErrorCode: BlobApiNotYetSupportedForHierarchicalNamespaceAccounts
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobApiNotYetSupportedForHierarchicalNamespaceAccounts</Code><Message>Blob API is not yet supported for hierarchical namespace accounts.
RequestId:938dd0ec-e01e-0014-79dc-5b07fc000000
Time:2019-08-26T07:07:52.6899317Z</Message></Error>
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
...
RequestId:938dd0ec-e01e-0014-79dc-5b07fc000000
Time:2019-08-26T07:07:52.6899317Z</Message></Error>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob list --container-name {} --output {}`

## Environment Summary
```
Linux-4.4.184-1.el7.elrepo.x86_64-x86_64-with-centos-7.6.1810-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.71

```

**Comment by Juliehzl** [comment]
Hi @jumping, ADLS gen2 haven't been integrated in storage commands but it will come in the future. I think you can try it next sprint in storage-preview extension.

**Comment by Juliehzl** [comment]
Hi @jumping, you can use `az storage fs file list` for ADLS Gen2 account files.

**Comment by gkdekko** [comment]
Hi, @Juliehzl I'm trying to create index tags but I'm getting the same error message. Do you know if there are new commands or functionality to be able to create index tags?
