### ISSUE TITLE
How to get autocomplete tabbing working on Fish Shell?

### ISSUE THREAD

**Issue by singhkays** [Azure/azure-cli#1031]
I read through the README and couldn't find what I need to get the autocomplete tabbing to work on a different shell. I've tested it working on a Linux machine using bash shell but can't seem to find how to get it working in Fish Shell

https://fishshell.com/

**Comment by mayurid** [comment]
@derekbekoe: Any ideas?

**Comment by johanste** [comment]
https://github.com/kislyuk/argcomplete/issues/68 has a discussion on this...

**Comment by derekbekoe** [comment]
I haven't looked at other shells in detail but we use argcomplete and as Johan points out, there's an issue on argcomplete to support Fish.

**Comment by singhkays** [comment]
@johanste @derekbekoe Thanks for linking guys, looks like it's not supported currently.

**Comment by jemag** [comment]
Seems like argcomplete now supports fish. 

Any update in being able to use az cli completion in fish?

**Comment by johanste** [comment]
@yugangw-msft, FYI.

**Comment by jemag** [comment]
Would it be possible to at least re-open the issue?

**Comment by jay-to-the-dee** [comment]
Yeah would also appreciate this being reopened

**Comment by geekyarthurs** [comment]
reopen it please

**Comment by malramsay64** [comment]
For fish you can run the below script to get the autocompletions working

```fish
register-python-argcomplete --shell fish az > ~/.config/fish/completions/az.fish
```

This comes from the setup instructions for the argcomplete library https://github.com/kislyuk/argcomplete
