### ISSUE TITLE
The top text formating is off

### ISSUE THREAD

**Issue by albecker1** [Azure/azure-cli#10314]
The first text and text box's format bleeds to far right and run's into the "is the page helpful" question and "in this article" navigation sections on the right

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbc06453-93e1-e616-9649-c1487c605a65
* Version Independent ID: 76d52328-613f-bd5f-7daf-f62841300e2b
* Content: [az vm disk](https://docs.microsoft.com/en-us/cli/azure/vm/disk?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by qwordy** [comment]
Thank you for your feedback. The bug has been confirmed. The doc text format has problems. We are fixing it.

**Comment by qwordy** [comment]
Fixed.
https://docs.microsoft.com/en-us/cli/azure/disk?view=azure-cli-latest
https://docs.microsoft.com/en-us/cli/azure/vm/disk?view=azure-cli-latest
https://docs.microsoft.com/en-us/cli/azure/vm/unmanaged-disk?view=azure-cli-latest
