### ISSUE TITLE
Support new Azure Monitor Metrics Alerts features

### ISSUE THREAD

**Issue by meday89** [Azure/azure-cli#10322]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.Insights - Azure monitor

**Description of Feature or Work Requested**
Metric Alerts overview. [Read docs](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-metric)
Metric Alerts API. [Read docs]( https://docs.microsoft.com/en-us/rest/api/monitor/metricalerts/createorupdate)

Metric alerts is currently supported in CLI but it is outdated.
Some of the missing features.
•	Support monitor multiple resources on a single rule. [Read blog]( https://azure.microsoft.com/en-us/blog/monitor-at-scale-in-azure-monitor-with-multi-resource-metric-alerts/)
•	Support monitor using a dynamic threshold. [Read blog]( https://azure.microsoft.com/en-us/blog/announcing-azure-monitor-aiops-alerts-with-dynamic-thresholds/).
We’re currently in progress of updating the powershell to support dynamic thresholds alerts.
You can find the PR [here]( https://github.com/Azure/azure-powershell/pull/9763).

**Minimum API Version Required**
2018-03-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-03-01/metricAlert_API.json

**Target Date**
Wherever possible

**Comment by David-Stark** [comment]
What is the status on this ?

**Comment by harelbr** [comment]
Supporting all metric alerts capabilities in the Azure CLI is planned for H1 2020.

With regards to support creating metric alert rules that use a dynamic threshold in PowerShell, that's already available: [Create a metric alert rule](https://docs.microsoft.com/en-us/powershell/module/az.monitor/add-azmetricalertrulev2?view=azps-3.3.0) and provide a [criteria object set to use dynamic threshold](https://docs.microsoft.com/en-us/powershell/module/Az.Monitor/New-AzMetricAlertRuleV2Criteria?view=azps-3.3.0).
