### ISSUE TITLE
The filename or extension is too long error while Combining Commands if count is greater than 40

### ISSUE THREAD

**Issue by ChendrayanV** [Azure/azure-cli#10339]
**az version**
2.0.71

**Describe the bug**
If VM count is more than 40 az cli throws below error while combining az commands. 
**Program 'az.cmd' failed to run: The filename or extension is too long**

**To Reproduce**
```PowerShell
# SET ACCOUNT - WHERE VM COUNT IS GREATER THAN 40
az vm get-instance-view --ids $(az vm list --query "[].id" --output tsv)
```

**Expected behavior**
As per the documentation no limitations are defined to query and combine commands.
```PowerShell 
# SHOULD WORK
$r = az vm get-instance-view --ids $(az vm list --subscription '**SUBSCRIPTION WITH MORE THAN 40 VM**' --query "[].id" --output tsv) | ConvertFrom-Json
$r  | Select location  , @{n = 'powerState'; e = {$_.instanceView.statuses.code[1]}} , type
```
**Workaround**
As a workaround we looped / selected subsets - Both works! But, native solution is must to have. 

**Environment summary**
Windows 10

**Comment by qwordy** [comment]
It seems cmd has a length limit. Try powershell or bash. Thanks.

**Comment by ChendrayanV** [comment]
I am not clear about the statement! You mean it's a limitation in CMD (Command Prompt)? I am running the az commands (above mentioned) in PowerShell!

**Comment by qwordy** [comment]
Sorry. I thought you were using Command Prompt. I try your command in PowerShell. PowerShell says "The command line is too long.". Maybe you can open a issue in PowerShell project.
Similar question:
https://stackoverflow.com/questions/29354602/powershell-error-the-command-line-is-too-long

**Comment by j-windsor** [comment]
This is a weakness in the implementation of azure-cli. I have a similar issue and the error is in az.cmd, meaning that even if you use powershell, its running a windows command prompt command, not a powershell module. @qwordy, it would be great if you could build a powershell module as well. For now, I am going to try AzureRM as my workaround, but I would consider this issue open.

**Comment by qwordy** [comment]
After debug, I found the problem happens before the Azure CLI entrance function. It's not recommended to use a too long command. For-loop is pervasive in most shell environments like bash, cmd, powershell.

**Comment by junaidahmed92** [comment]
Actually now I am getting another error:

> Program 'az.cmd' failed to run: The filename or extension is too longAt line:1 char:1
> + az webapp show --ids /subscriptions/af8209e5-4154-4460-8e82-5e1eac156 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
> At line:1 char:1
> + az webapp show --ids /subscriptions/af8209e5-4154-4460-8e82-5e1eac156 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
>     + FullyQualifiedErrorId : NativeCommandFailed

**Comment by junaidahmed92** [comment]
Actually now I am getting another error:

> Program 'az.cmd' failed to run: The filename or extension is too longAt line:1 char:1
> + az webapp show --ids /subscriptions/<--subscriptionID--> ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
> At line:1 char:1
> + az webapp show --ids /subscriptions/<--subscriptionID--> ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
>     + FullyQualifiedErrorId : NativeCommandFailed
