### ISSUE TITLE
ARM Component Omnibus

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#1033]
The following feedback came out of our ARM review meeting
- [x] Update ARM to use general api-version logic and follow-up [@yugangw-msft, if no supplied, we will query provider for the latest api-version]
- [ ] ~~Resource delete should not have --parent~~ (@yugangw-msft, we will keep it to maintain consistent interface across `show`, `delete` and `tag` )
- [x] Resource exists should be removed (as it is not supported by ARM)
- [x] Support auto-complete for --resource-type
- [ ] ~~Remove resource tag command~~ (@yugangw-msft, we will keep, as it is working pretty well with resource id)
- [x] Resource management commands should work accept resource ID
- Policy
  - [x] Definitions and assignments should both be groups
- Policy Assignment 
  - [x] commands should use --scope, not --resource-id (@yugangw-msft fixed by PR#1041)
  - [x] List should remove --show-all (@yugangw-msft reviewed with @vivsriaus, due to api inconsistency, we will by default do strict scope match, but offer option to let people do loose match to show everything on group or individual  resource, same deal when you use `-g` or `--scope`)
- Provider
  - [x] List should show resource type and location (requires 2nd call for location info) (@yugangw-msft, verified azure-cli does and with more comprehensive content)
  - [x] Register should return right away and not wait
- Group
  - [ ] ~~Update does not have a use for --add~~ (@yugangw-msft, chatted with colleagues , and we decide to keep as it can be used for adding tag)
- Deployment
  - [x] Create should allow default name using same naming logic (if not created server side)
  - [x] Create should support ~~@ syntax~~ template from an uri (edited by @yugangw-msft)
  - [x] Remove 'exists'

**Comment by mayurid** [comment]
moving to Sprint 5 as this is spanning 2 sprints.
