### ISSUE TITLE
Login to tenant without a subscription

### ISSUE THREAD

**Issue by jkewley** [Azure/azure-cli#10349]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to work with an Active Directory which doesn't have a subscription using `az ad` commands

**Describe the solution you'd like**
Currently one needs to select context for the CLI by providing a subscription identifier. I'd like to be able to specify a tenant id as an alternative so I can have access to the `az ad` commands.

**Describe alternatives you've considered**
The Powershell AD commandlets support commands such as `Get-AzureAdUser` but I'm trying to move to the CLI and would like an alternative.

**Comment by jiasli** [comment]
You may use `az login --allow-no-subscriptions` to enable tenant access: https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login
