### ISSUE TITLE
--scopes is defined by "Space-separated list", which cannot be used in practice

### ISSUE THREAD

**Issue by gstolz** [Azure/azure-cli#10348]
I tried to create an alert rule on a webtest by providing webtest-ID and appInsights-ID as array. (just as shown by existing resource in resource.azure.com). This gives an error:

Scopes property is invalid. Only single resource is allowed for criteria type SingleResourceMultipleMetricCriteria. If you want to create an alert on multiple resources, use MultipleResourceMultipleMetricCriteria odata.type.. [Code: "BadRequest"]

I cannot find any hint on how get this running. Hope anyone can help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d97968df-72c9-e50c-d5b1-54562c1bdef7
* Version Independent ID: 0cde4f15-6464-3106-b787-3ee37c7de0ee
* Content: [az monitor metrics alert](https://docs.microsoft.com/en-us/cli/azure/monitor/metrics/alert?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by macrogreg** [comment]
Is this about Classic or Near-Real-Time alerts?

For the later, the criteria to use for x-out-of-y locations availability alerts if `WebtestLocationAvailabilityCriteria`.

Let me notify some experts of this thread.

**Comment by macrogreg** [comment]
@gstolz, I am also not fully clear about the details of what exactly you did not encounter the issue. Can you please provide details?

**Comment by snehithm** [comment]
Hi @gstolz,

CLI commands dont yet support creating webtest alerts. Please use [ARM template](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-metric-create-templates#template-for-a-availability-test-along-with-availability-test-alert) to deploy as an alternative. 
 
Regards,
Snehith

**Comment by gstolz** [comment]
Hi @snehithm ,
thanks for the info! I don't really understand why MS cut off support for "classic" alerts in such a hurry when the alternative alerting is not fully supported yet.
ARM template instead of cli commands is a lot of overhead in the implementation. Is there any plan when this will be usable in az cli?
BR

**Comment by MyronFanQiu** [comment]
@gstolz I will investigate the efforts and confirm the date with you later.
