### ISSUE TITLE
az cli repository http://ppa.launchpad.net/ansible/ansible/ubuntu does not have a release file

### ISSUE THREAD

**Issue by vogd** [Azure/azure-cli#10351]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Installation one liner from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest is not working :
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

**To Reproduce**
Steps to reproduce the behavior.
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
apt-get update
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch Release 
Ign:6 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan InRelease          
Ign:7 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan Release
Ign:8 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan/main amd64 Packages
Ign:9 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan/main all Packages
Ign:8 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan/main amd64 Packages
Ign:9 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan/main all Packages
Ign:8 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan/main amd64 Packages
Ign:9 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan/main all Packages
Ign:8 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan/main amd64 Packages
Ign:9 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan/main all Packages
Ign:8 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan/main amd64 Packages
Ign:9 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan/main all Packages
Err:8 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan/main amd64 Packages
  404  Not Found
Ign:9 http://ppa.launchpad.net/ansible/ansible/ubuntu eoan/main all Packages
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu eoan Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/eoan/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
**Expected behavior**

**Environment summary**
bash oneliner taken from site can not be executed on ubuntu 18.04.
Was able to install the client a month ago using the same command

**Additional context**
4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux

**Comment by zikalino** [comment]
@vogd This issue doesn't seem to be related to Azure CLI, but rather to your environment.

You can try to run **apt-get update** command and you will see the same errors.

From what I see they are related to Ansible

https://launchpad.net/~ansible/+archive/ubuntu/ansible

**Comment by yonzhan** [comment]
We will close it currently since it is not related to Azure CLI. Please let us know if any further questions.
