### ISSUE TITLE
'az vm encryption show' gives no indication of progress from a Linux VM, and the status is misleading

### ISSUE THREAD

**Issue by jlucktay** [Azure/azure-cli#10356]
I enabled encryption on a Linux VM and the JSON response from this command shows:

          "code": "EncryptionState/encrypted",
          "displayStatus": "Encryption is enabled on disk",

However, when logged in to the VM I can see with 'ps -Af' that the encryption process is still running.
The Azure CLI does not seem to give an accurate indication of encryption progress, just a binary enabled/disabled.
With a Windows VM, I know that BitLocker would give me a percentage of completion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4762f857-8a1e-f1bb-7843-3d8fefe28f8e
* Version Independent ID: 91ce956c-c915-5053-56b0-a489fb2f7b00
* Content: [az vm encryption](https://docs.microsoft.com/en-us/cli/azure/vm/encryption?view=azure-cli-latest#az-vm-encryption-show)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by achandmsft** [comment]
Thanks for the feedback @jlucktay.  @qwordy, could you please take a look?

**Comment by qwordy** [comment]
"Enable" does not mean encryption is finished.
`az vm encryption enable` and `az vm encryption show` can't get a percentage of completion from server yet.
`az vm encryption enable` returns "The encryption request was accepted. Please use 'show' command to monitor the progress.".
`az vm encryption show` can show more information about the encryption process.  e.g.
```
"message": "{\"os\": \"EncryptionInProgress\", \"data\": \"NotMounted\"}"
```

Related API:
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/instanceview

Service team:
How can client get percentage of completion?
If not, do you have any plan to support percentage of completion?

**Comment by Drewm3** [comment]
Hi @jlucktay, I have logged this as a feature suggestion in UserVoice: https://feedback.azure.com/forums/216843-virtual-machines/suggestions/38505424-show-encryption-status-after-enabling-encryption.

Please upvote this item and we will continue to triage the feature suggestions receiving significant votes through UserVoice.
