### ISSUE TITLE
ARM templates with '//' comments and multi-line strings fail to be deployed

### ISSUE THREAD

**Issue by alex-frankel** [Azure/azure-cli#10354]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
ARM templates with '//' comments and multi-line strings fail to be deployed

**Additional context**
az cli team already has context. This is to help get this triaged.

**Comment by yonzhan** [comment]
@Juliehzl please fix this issue by end of this week.
