### ISSUE TITLE
keyvault show secret quickly fails after they are recently set

### ISSUE THREAD

**Issue by smartpcr** [Azure/azure-cli#10363]
## Describe the bug

**Command Name**
`az keyvault secret show`

**Errors:**

:confused:

```Max retries exceeded attempting to connect to vault. The vault may not exist or you may need to flush your DNS cache and try again later.```

## To Reproduce:
turn on soft-delete on keyvault 

- `Fill in additional info here`
- `Run: az keyvault secret show --vault-name {} --name {}`

## Expected Behavior
should not throw error

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli                         2.0.62 *

Extensions:
dev-spaces-preview                 0.1.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xiaodoli\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

```
## Additional Context

To print out the issue body locally, run `az feedback --verbose`

**Comment by achandmsft** [comment]
@smartpcr could you please provide more details around this issue using az feedback? Have you followed the guidance here for soft delete - https://docs.microsoft.com/en-us/azure/key-vault/key-vault-soft-delete-cli ?

@jiasli, could you please take a look as well to see if you can repro this issue?

**Comment by smartpcr** [comment]
right now, this is only happening for machines that are domain joined (microsoft)
ping me `xiaodoli@microsoft.com` if you have questions.

**Comment by jiasli** [comment]
Could you please
1. Update to the latest CLI version (currently 2.0.72)
2. Test if this happens with [PowerShell](https://docs.microsoft.com/en-us/azure/key-vault/key-vault-soft-delete-powershell)
3. Test if there is DNS change after run ` --enable-soft-delete true`

Also, does the keyvault recover after some time?

**Comment by jiasli** [comment]
Closing due to no response. If the issue happens again, please let us know.
