### ISSUE TITLE
No Example

### ISSUE THREAD

**Issue by craiginscotland** [Azure/azure-cli#10367]
If there was an example, then I'd know the format of the parameters.
e.g. "--subscription" - does that mean I type "--subscription &lt;value here&gt;" or do I replace "subscription" with my actual information (I suspect not).
None of the commands on this page tell you how, in general, command line arguments are parsed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6834da14-38b9-e004-82cc-3fb9a24a2633
* Version Independent ID: d336a4c9-4243-6933-7f5e-a3763e459f7b
* Content: [az batch account](https://docs.microsoft.com/en-us/cli/azure/batch/account?view=azure-cli-latest#az-batch-account-login)
* Content Source: [src/azure-cli/azure/cli/command_modules/batch/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/batch/_help.py)
* Service: **batch**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
`--subscription <value here>` should be the correct format, you may check [other examples](https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?view=azure-cli-latest). We will improve our examples for batch module. Thank you for the feedback.
