### ISSUE TITLE
`az group list` gives `cannot import name 'PolicyMode'`

### ISSUE THREAD

**Issue by ayekat** [Azure/azure-cli#10369]
**Describe the bug**
Running `az group list` (after logging in) results in the following error:

```
The command failed with an unexpected error. Here is the traceback:

cannot import name 'PolicyMode' from 'azure.mgmt.resource.policy.models' (/usr/lib/python3.7/site-packages/azure/mgmt/resource/policy/models.py)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 523, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 292, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib/python3.7/site-packages/azure/cli/command_modules/resource/__init__.py", line 31, in load_arguments
    load_arguments(self, command)
  File "/usr/lib/python3.7/site-packages/azure/cli/command_modules/resource/_params.py", line 105, in load_arguments
    from azure.mgmt.resource.policy.models import PolicyMode
ImportError: cannot import name 'PolicyMode' from 'azure.mgmt.resource.policy.models' (/usr/lib/python3.7/site-packages/azure/mgmt/resource/policy/models.py)
```

**To Reproduce**
1. Login to Azure as described in the [*Get started with Azure CLI*][ms:azcli] article.
2. Run `az group list`.
3. See the error given above.

[ms:azcli]: https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest

**Expected behavior**
`az group list` should return a list of existing resource groups.

**Environment summary**
* Install Method: package built from PKGBUILD in the Arch User Repository ([python-azure-cli][aur:azcli])
* CLI version:
  ```
  azure-cli                         2.0.72
  
  command-modules-nspkg               2.0.3
  core                              2.0.72
  nspkg                              3.0.4
  
  Python location '/usr/bin/python'
  Extensions directory '/home/ayekat/.azure/cliextensions'
  
  Python (Linux) 3.7.4 (default, Jul 16 2019, 07:12:58) 
  [GCC 9.1.0]
  ```
  Note: `~/.azure/cliextensions` does not exist.
* OS Version: Arch Linux
* Shell Type: zsh

[aur:azcli]: https://aur.archlinux.org/packages/python-azure-cli/

**Additional context**
Looking at `/usr/lib/python3.7/site-packages/azure/mgmt/resource/policy/models.py`, it appears that it includes everything from `v2019_01_01` in the same directory. Looking at the files in there (and comparing with `v2018_05_01`), it appears that `v2019_01_01/models/_policy_client_enums.py` is missing the declaration of the `PolicyMode` class.

I have naively copied the class implementation from `v2018_05_01` (and adapted the `v2019_01_01/models/__init__.py`), and this makes `az group list` work again.

However, I am not sure if this is a clean solution, so I would appreciate some feedback on that approach.

**Comment by wmeints** [comment]
We're running into the exact same issue with the command `az keyvault create`.

**Comment by jiasli** [comment]
Hi @yugangw-msft , looks like this issue is caused by merge #10340.

**Comment by yugangw-msft** [comment]
please reactivate if @jiasli's suggestion still doesn't work
