### ISSUE TITLE
bug on get version

### ISSUE THREAD

**Issue by varuns-zetaris** [Azure/azure-cli#10360]
## Describe the bug

**Command Name**
`az aks get-versions`

**Errors:**
```
az aks get-versions: error: argument --location/-l is required
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-versions`

## Environment Summary
```
Linux-3.10.0-514.16.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.72

Extensions:
aks-preview 0.4.11

```

**Comment by seanmck** [comment]
Don't really understand the issue here. The location parameter is required because there may be different versions available in different regions at a given time.
