### ISSUE TITLE
az login missing documentation for return object

### ISSUE THREAD

**Issue by raydixon** [Azure/azure-cli#10372]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
In the documentation for [`az login`](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login) there is no mention of nor description for the object that `az login` returns.

**To Reproduce**

1. Read the [documentation for `az login`](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login).

**Expected behavior**
You can find information about the object that the `az login` command returns.

**Actual behavior**
There is no mention at all that `az login` returns an object at all, let alone anything about the object.

**Environment summary**
N/A

**Additional context**
It would be very handy to have reference documentation for the objects returned for _all_ of the `az` commands.

**Comment by jiasli** [comment]
Due to the limitation of Bash and Command Prompt that only string can be returned (unlike PowerShell), `az login` returns a JSON in the form of

```
[
  {
    "cloudName": "AzureCloud",
    "id": "00000000-0000-0000-0000-000000000000",
    "isDefault": true,
    "name": "xxx",
    "state": "Enabled",
    "tenantId": "00000000-0000-0000-0000-000000000000",
    "user": {
      "name": "xxx@xxx.com",
      "type": "user"
    }
  },
  ...
]
```

For other commands like `az storage account show`, the returned JSON is the same as those defined in [Azure REST API](https://docs.microsoft.com/en-us/rest/api/azure/).

**Comment by raydixon** [comment]
Thanks for the prompt response @jiasli. Even thought the az login command returns a string, it's in the form of a JSON object (the "O" in JSON) and should be documented. If other commands simply return the same JSON object(s) as the REST API, stating that with a link to the reference documentation for the REST API object would be sufficient.

**Comment by jiasli** [comment]
Thanks for the great suggestion. We are considering linking CLI and underlying REST API in the doc in the future.
