### ISSUE TITLE
--settings or --slot-settings @<json_file>

### ISSUE THREAD

**Issue by KenSpur** [Azure/azure-cli#10386]
Hey,

The --settings or --slot-settings parameter seems to be acting out ^^.

It either miss reads  the json file that is passed trough.

With a content like key='value' it will translate to key : "value'" adding a ' at the end of the value within the web app configuration.

Also { "key" : "Data Source=value" } will translate to "{"key" :Data Source" : "value"}" 

It seems just to look for the first '=' to split into a key and value, i would expect it to work like the az webapp config appsettings version.

Also it does not seem to support multiple  connection strings :(

I am useing the AzureCliV1 task within a vmImage: 'ubuntu-latest' in a AzureDevops Pipeline 

Anyway &lt;3, keep up the good work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2b885be-54f8-23f0-9fff-ec4feb157553
* Version Independent ID: 2ad01dad-e05d-e129-13b6-d1ed09db7086
* Content: [az webapp config connection-string](https://docs.microsoft.com/en-us/cli/azure/webapp/config/connection-string?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp/config/connection-string.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/connection-string.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
@KenSpur unfortunately this command doesn't support a JSON input or json file as input.
needs to be a key-value pair separated by = https://github.com/Azure/azure-cli/blob/b33944353f474a35cae113b1496e90822d2eb8c6/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L870

**Comment by panchagnula** [comment]
Closing this out due to lack of activity
