### ISSUE TITLE
`list` fails when one of names contains the dollarsign (bash)

### ISSUE THREAD

**Issue by kizerkizer** [Azure/azure-cli#10385]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
For example, $web is the default name for a blob container when using the static site setup. However, do get `list`, I had to quote it and escape the $ "\$web" (to avoid reffing bash variable, right?).  Although this is expected when using bash, so perhaps $web (the default, I think? I hope I didn't name it that.) should have $ removed.

**To Reproduce**
`az storage blob list --container-name "web" --account-name <...>`
`az storage blob list --container-name "$web" --account-name <...>`
`az storage blob list --container-name $web --account-name <...>`

Only
`az storage blob list --container-name "\$web" --account-name <...>`
worked for me.

**Expected behavior**
I guess this is expected, although it's an awkward coincidence that the default name for the blob was $web.

**Environment summary**
homebrew, macOS
```
az --version
azure-cli                         2.0.72
```

**Additional context**

**Comment by Juliehzl** [comment]
Hi @kizerkizer, thanks for your feedback first and your guess is right. Just as shown in https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website, default blob name for static website is $web, which is by design. This is more about Service side, not azure cli. Let's make service team involved.

**Comment by kizerkizer** [comment]
It's a recipe for a "disaster" (maybe not that severe), but it will certainly be common for users to manage their static site with azure-cli, and the fact that only "\$web", with the dollar sign escaped, would work will cause a few headaches.

**Comment by xiafu-msft** [comment]
it looks like there's not much Python SDK can do here, it's a service feature by design.

**Comment by amishra-dev** [comment]
by design.
