### ISSUE TITLE
az network vnet subnet list required parameters

### ISSUE THREAD

**Issue by thelethalkind** [Azure/azure-cli#10401]
(--resource-group --vnet-name | --ids) are required parameters, but are marked as optional in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 385e420c-4bd0-3ddd-d9cd-a9a411ec1f7b
* Version Independent ID: 65172372-f485-3d2b-64aa-57c38ac11538
* Content: [az network vnet subnet](https://docs.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#az-network-vnet-subnet-list)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@thelethalkind Thanks. I will fix it soon.
