### ISSUE TITLE
Table output supresses IDs and Types but in some cases, it would be beneficial

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1040]
Table output hides IDs and types by default as ids aren't table-friendly and types are typically not needed. e.g. az vm list -otable would show Microsoft.Compute/virtualMachines in each row of the table.
However, there are special cases (e.g. Storage data-plane commands and `az resource show -otable`) where showing IDs/types in table output would be useful.

A workaround is to create a custom callable table format for those specific commands that need to display IDs or Types.

Related to https://github.com/Azure/azure-cli/issues/1003 and https://github.com/Azure/azure-cli/issues/1039.

**Comment by johanste** [comment]
At a minimum, type should be there for resource list (without it, the output is...less than useful!)

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
