### ISSUE TITLE
AZ postgres support for schema creation

### ISSUE THREAD

**Issue by msbhanuprakash** [Azure/azure-cli#10419]
**Resource Provider**
What is the Azure resource provider your feature is part of?  Azure DB for postgresql

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.

I am trying to automate creation of postgresql server from azure portal for the project and create database and schema inside the server.   i am using azure devops pipeline for creation for Azure Database for postgresql

i have automated using az cli in my pipeline upto creation of database using 
az postgres db create -g $rg_name -s $postgres_name -n $PostgresdbName 

but i want to create schema inside this database 

can anyone help me with command to be used.
regards

Bhanuprakash 

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. This should be on the master branch
of the REST API specs repo.

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

**Comment by msbhanuprakash** [comment]
Hi All,

I just thought that i would follow up and give updated information.

I have tried with command like below with no luck

az postgres db create schema -g $rg_name -s $postgres_name -n $PostgresdbName

I was referring to   this documentation from microsoft site  https://docs.microsoft.com/en-us/cli/azure/postgres/db?view=azure-cli-latest 

I have need for implementing multiple schemas for a database  for repository management system.

It would be great if have the db create option for schema as well   which will ease my work

regards

Bhanuprakash

**Comment by rachel-msft** [comment]
Hi Bhanuprakash. Thanks for reaching out Azure Database for PostgreSQL doesn't support using the Azure CLI to create a schema or other database commands ([apart from the ones listed at the link you provided](https://docs.microsoft.com/cli/azure/postgres/db?view=azure-cli-latest)). To create a schema, you would need to connect directly to the Postgres server using your preferred client (same as you would to insert data, alter tables etc).

**Comment by rachel-msft** [comment]
#please-close

**Comment by rachel-msft** [comment]
#please-close

**Comment by rachel-msft** [comment]
@jiasli can you please close this item?
