### ISSUE TITLE
az dls join command not work properly.

### ISSUE THREAD

**Issue by NikunjPatelv24** [Azure/azure-cli#10414]
## Describe the bug

**Command Name**
`az dls fs join`

**Errors:**
```
Input/VMS/dbo.ReqStatus_test.txt
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
azure/datalake/store/lib.py, ln 439, in call
    self.log_response_and_raise(response, FileNotFoundError(path), level=exception_log_level)
azure/datalake/store/lib.py, ln 345, in log_response_and_raise
    raise exception
FileNotFoundError: Input/VMS/dbo.ReqStatus_test.txt
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az dls fs join --destination-path {} --source-paths {} {} --account {} --force`

## Environment Summary
```
Linux-4.15.0-1055-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.72

```

**Comment by NikunjPatelv24** [comment]
When I was join two files into destination path then destination path file was deleted by join command. And because of this it raise File not found exception.

**Comment by sumantmehtams** [comment]
Hi @NikunjPatelv24 ,

Could you open a support ticket using the Azure portal. We might need more details like the activity Id, if the issue always happens, account, paths, timestamp, etc. 

I'll go ahead and close this issue and we can look at the support ticket instead. Let me know if that sounds ok.

Thanks,
Sumant

**Comment by sumantmehtams** [comment]
Also, please include the link for this issue in the support ticket.

Thanks,
Sumant

**Comment by sumantmehtams** [comment]
Closing issue.
