### ISSUE TITLE
Enable creation of Azure app Push Notifications with az monitor action-group create

### ISSUE THREAD

**Issue by svaenn** [Azure/azure-cli#10417]
When I create action groups with az cli I can not configure Azure app Push Notifications. The help only shows actions for Email, SMS and Webhook:

Actions Arguments
    --action -a                    : Add receivers to the action group during the creation.
        Usage:   --action TYPE NAME [ARG ...]
        Email:   --action email bob bob@contoso.com
        SMS:     --action sms charli 1 5551234567
        Webhook: --action webhook alert_hook https://www.contoso.com/alert

Please add -action parameters (and help) to configure Azure app Push Notifications.

When creating action groups automatically e.g. in a Azure DevOps pipeleine the configuration for Azure app Push Notifications added manually will always be reset.

**Comment by Dalubash** [comment]
@dkamstra Duke can you respond on this request please.

**Comment by dkamstra** [comment]
The updates to PowerShell were merged into the public repo over the past couple days. Current ETA for corresponding updates to the CLI is late November.

**Comment by dkamstra** [comment]
Just closing the loop here. The functionality was delivered. This issue is #closed
