### ISSUE TITLE
Add availabilityZone boolean to `az account list-locations`

### ISSUE THREAD

**Issue by richeney** [Azure/azure-cli#10421]
Please add the availability zone support as an additional field in the output json.  

This would allow JMESPATH filtering on all regions that support availability zones.

E.g.

`az account list-locations --query "[?availabilityZone == true]"`

**Comment by jiasli** [comment]
Thank you for raising this feature request. We will look into it.

**Comment by jiasli** [comment]
As `availabilityZone` is not provided by REST API [Subscriptions - List Locations](https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/listlocations), it is impossible for Azure CLI to retrieve such information.

**Comment by Paul-at-Seequent** [comment]
Shouldn't you be adding it to the rest API as well? It seems to me it is a key piece of information about a region.

**Comment by jiasli** [comment]
@Paul-at-Seequent, for REST API and service-related feature request, please feel free to submit a feedback at https://feedback.azure.com/. The corresponding service team will review the feedback and evaluate whether it should be implemented. Thanks for your understanding.
