### ISSUE TITLE
Support python3 executable when running az

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1043]
The script files, 'az' and 'az.bat', that are installed through the `pip install` do not support machine configurations that only have `python3`.

An error is shown that `python` was not found as it has been named `python 3`.

The script files should potentially have a way to determine the correct python executable to use.

Related to these issues that were closed previously: https://github.com/Azure/azure-cli/issues/1016, https://github.com/Azure/azure-cli/issues/1008

**Comment by derekbekoe** [comment]
cc @tjprescott

**Comment by derekbekoe** [comment]
Related to PEP 394 -- The "python" Command on Unix-Like Systems - https://www.python.org/dev/peps/pep-0394/

**Comment by tjprescott** [comment]
The only team that clamored for this was Datalake, and they were more than happy with the virtual environment solution.  Given that we have packaged released that include Python3... @derekbekoe can we close this issue?

**Comment by kostrse** [comment]
Folks, this issue still persists and annoying...

**Comment by pmarques** [comment]
@derekbekoe this bug annoying specially when dealing with custom stuff like brew for OS X. What is the propose of that bash script wrapper for az?
I'm not a python expert, but if this was a python script (with shebang pointing to python), pip would update the script to use the right python version. For instance:

pip2 install azure-cli would use python2(...)
pip3 install azure-cli would use python3(...)

**Comment by kwakayama** [comment]
> Folks, this issue still persists and annoying...

Should this issue be re-opened?
