### ISSUE TITLE
Error during MacOS installation via brew

### ISSUE THREAD

**Issue by gmowhiz** [Azure/azure-cli#10438]
**Describe the bug**
Attempting to install azure-cli via brew on MacOS is resulting in the following error:

> ==> Pouring python-3.7.4.mojave.bottle.tar.gz
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
Permission denied @ dir_s_mkdir - /usr/local/Frameworks
Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks

**To Reproduce**
Run the following in a terminal: 
`brew install azure-cli`

**Expected behavior**
The installation should proceed error-free.

**Environment summary**
Install Method: brew
CLI version: stable 2.0.72 (bottled), HEAD
OS version: MacOS mojave 10.14.6
Shell Type: bash via iTerm2

**Comment by gmowhiz** [comment]
This is potentially not an issue with azure-cli specifically. A little searching turned up this solution:
`sudo install -d -o $(whoami) -g admin /usr/local/Frameworks`

After running the above, I was able to successfully install it.

**Comment by jiasli** [comment]
I am glad it is solved. If any issue comes up, please don't hesitate to let us know.
