### ISSUE TITLE
az storage blob list not working properly within Azure environment

### ISSUE THREAD

**Issue by kloeffler** [Azure/azure-cli#10436]
## Describe the bug

**Command Name**
`az storage blob list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/output.py", line 132, in out
    output = formatter(obj)
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
```

This command works fine from VMs outside of the Azure environment, but not within. 
Roles are set properly, the same command will produce valid output.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login --service-principal -u{} -p{}`
- `az storage blob list --container-name {} --auth-mode {} --account-name {}`

## Expected Behavior
Output of blob list, e.g.:
[]

## Environment Summary
```
Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.71 *

```

**Comment by yonzhan** [comment]
@Juliehzl  please take a look

**Comment by Juliehzl** [comment]
@kloeffler can you show me more information using `az storage blob list --debug` ? P.S. Remember not post your account key information in the Internet.

**Comment by kloeffler** [comment]
``
Command arguments: ['storage', 'blob', 'list', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function on_global_arguments at 0x7f86f0ed6f50>, <function on_global_arguments at 0x7f86f0a58aa0>, <function on_global_arguments at 0x7f86f0a5cd70>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appconfig', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.005 seconds.
Loaded module 'acs' in 0.006 seconds.
Loaded module 'advisor' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.006 seconds.
Loaded module 'appconfig' in 0.001 seconds.
Loaded module 'appservice' in 0.025 seconds.
Loaded module 'backup' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.008 seconds.
Loaded module 'batchai' in 0.003 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'botservice' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.002 seconds.
Loaded module 'container' in 0.001 seconds.
Loaded module 'cosmosdb' in 0.008 seconds.
Loaded module 'deploymentmanager' in 0.003 seconds.
Loaded module 'dla' in 0.004 seconds.
Loaded module 'dls' in 0.003 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.003 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.000 seconds.
Loaded module 'find' in 0.000 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.005 seconds.
Loaded module 'iotcentral' in 0.002 seconds.
Loaded module 'keyvault' in 0.005 seconds.
Loaded module 'kusto' in 0.001 seconds.
Loaded module 'lab' in 0.003 seconds.
Loaded module 'managedservices' in 0.001 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.004 seconds.
Loaded module 'natgateway' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.003 seconds.
Loaded module 'network' in 0.033 seconds.
Loaded module 'policyinsights' in 0.001 seconds.
Loaded module 'privatedns' in 0.005 seconds.
Loaded module 'profile' in 0.001 seconds.
Loaded module 'rdbms' in 0.006 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.001 seconds.
Loaded module 'resource' in 0.008 seconds.
Loaded module 'role' in 0.005 seconds.
Loaded module 'search' in 0.001 seconds.
Loaded module 'security' in 0.002 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.001 seconds.
Loaded module 'signalr' in 0.001 seconds.
Loaded module 'sql' in 0.008 seconds.
Loaded module 'sqlvm' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.037 seconds.
Loaded module 'vm' in 0.019 seconds.
Loaded all modules in 0.266 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/kloeffler/.azure/cliextensions'
Event: CommandInvoker.OnPreCommandTableTruncate [<function init_command_file_logging at 0x7f86f0605578>]
az_command_data_logger : command args: storage blob list --debug
metadata file logging enabled - writing logs to '/home/kloeffler/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function add_subscription_parameter at 0x7f86f051a0c8>]
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function add_ids_arguments at 0x7f86f051a320>, <function add_cache_arguments at 0x7f86f42f3d70>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f86ee123d70>]
``

**Comment by Juliehzl** [comment]
@kloeffler Thanks for your more information. 
From the debug information, it looks that you don't have the permission to access the storage account. What kind of --auth-mode is used here? Can you try to remove `--auth-mode` in your command? 
In addition, what is your (service principal) role for the storage account? 
And what do you mean for "outside of the Azure environment and within Azure"?

**Comment by kloeffler** [comment]
I apologize for the late response.
I did not provide any auth-mode running the command.
After it failed I tried using auth-mode login and key. Neither brought any other results.

"In addition, what is your (service principal) role for the storage account?" - what do you mean?

I meant on premise VMs, work laptops, desktops, etc... It will work fine from non-Azure-environment machines but fail from VMs within Azure.

**Comment by kloeffler** [comment]
The problem has been solved. It was a firewall issue after all.
The error message was confusing though.
Thank you.
