### ISSUE TITLE
az network watcher flow-log configure --interval error

### ISSUE THREAD

**Issue by aandroulakas** [Azure/azure-cli#10437]
> ### `az feedback` auto-generates most of the information requested below, as of CLI 

azure-cli                         2.0.72

command-modules-nspkg               2.0.3
core                              2.0.72
nspkg                              3.0.4
telemetry                          1.0.3

Python (Darwin) 3.7.4

**Describe the bug**

az network watcher flow-log configure: error: unrecognized argument: --interval 10

**To Reproduce**

**Expected behavior**
Expecting --interval 10 or 60 to work

**Environment summary**
$ brew update && brew upgrade azure-cli

**Comment by yonzhan** [comment]
@MyronFanQiu please take a look

**Comment by MyronFanQiu** [comment]
@aandroulakas Hello. This has been fixed and will be release soon.

**Comment by MyronFanQiu** [comment]
https://github.com/Azure/azure-cli/pull/10347

**Comment by MyronFanQiu** [comment]
@aandroulakas Hello. This has been fixed in the latest release. Please check it. I will close this issue. Please feel free to reopen it or open a new issue. 😄
