### ISSUE TITLE
Updating Indexing Policy 

### ISSUE THREAD

**Issue by rgherta** [Azure/azure-cli#10434]
Regarding this line 

"Indexing Policy, you can enter it as a string or as a file, e.g., --indexing-policy @policy-file.json)"

Please provide example. I tried updating the indexing policy without success. I gave json as string argument but it fails with all sort of parsing errors, also involving this '$v' workaround that you should recognize. 

The proper way to update would be to save the policy on a disk file. However, I tried passing the file path as argument and still it throws error even at first caracter. So it is not clear to me how exactly would you pass an entire file as argument and what exactly is that @ character. 

I am using CosmosDB Mongo Enabled API and updating using Az CLI from the Windows CMD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d791e10-4181-cf15-1398-499eb0918c9c
* Version Independent ID: 2e5f864d-29bd-da4f-b964-a87a39f988c0
* Content: [az cosmosdb collection](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/collection?view=azure-cli-latest#az-cosmosdb-collection-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rgherta** [comment]
The @file.json is the '@' character followed by the name of the file located in the same path as the terminal.

**Comment by raswinraaj** [comment]
What was the fix for this @rgherta ? I am also getting the same error?

**Comment by rgherta** [comment]
> What was the fix for this @rgherta ? I am also getting the same error?

Create a file called myfile.json then in the cmd navigate to the folder where this file resides and call the az command like az collection update ..... @policy-file.json
