### ISSUE TITLE
RFE can we get RPM packages as well 

### ISSUE THREAD

**Issue by kbsingh** [Azure/azure-cli#1045]
Can we get RPM packages for CentOS Linux 6 and 7 please ?

**Comment by mayurid** [comment]
@kbsingh : We have added this to stack of items on our side to take look at in near future. Out of curiosity are you having any issues with pip install?
/cc: @derekbekoe

**Comment by kbsingh** [comment]
@mayurid thanks for the consideration.

Pip installs cant be managed in anyway, so while they are a great onramp for developer and transient workloads, its never a good solution for either production or any sort of managed environment. 

Beyond that, my specific case here is to consume this content in upstream CentOS Project build and validation services. We need the rpms, so we can work through the dep chains and ensure the entire stack can be managed cleanly etc. All of our existing tooling for these, as you might imagine, is rpm centric.

cheers,

**Comment by kfiresmith** [comment]
+1 for this.
We've discovered a number of problems with the current approach.

- UrlLib does not play well with our enterprise Bluecoat proxies, no matter how lenient we set the target pypi URL destination in the proxy to not check for sane TLS requests.
- While we can manage pips and pip3s using Puppet, we'd much rather manage RPMs as we do for everything else in our RHEL infra.
- The pips available in PyPi don't seem to work properly out of the box on a standard RHEL 7 host.

**Comment by mayurid** [comment]
@derekbekoe : Lets look into this for upcoming sprint.

**Comment by derekbekoe** [comment]
Created RPM package. All are welcome to test it out.
It installs CLI release 2.0.16.

RHEL, Fedora and CentOS based distributions:
```
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'
yum check-update
sudo yum install -y azure-cli
```

openSUSE and SLE based distributions:
```
sudo sh -c 'echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/zypp/repos.d/azure-cli.repo'
sudo zypper refresh
sudo zypper install code
```

This information should appear on a docs.microsoft.com page soon if all is well.
