### ISSUE TITLE
Azure CLI command Az login wont process cross domain AD authentication when proxy its involved.

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/azure-cli#10463]
**Describe the bug**
2 AD domains, 1 azure, 1 customer domain 
users from customer domain will use az login to authenticate to our services for example ACR and fail when the customer has a proxy in the middle:

> SSLError (SSLError (" bad handshake: Error ([(' SSL routines ', ' tls_process_server_certificate ', ' certificate verify failed ' when authenticating against management.azure.com:443

**To Reproduce**

az login 
az acr login --name <registryname> --debug --verbose
using external AD.

**Expected behavior**
Authentication to work.

**Environment summary**
computer ---> proxy -- custom ad --- ACR.

**Comment by jiasli** [comment]
Thank you @porrascarlos802018. I have updated the initial description as well.
