### ISSUE TITLE
Add zone redundant parameter to az servicebus create command

### ISSUE THREAD

**Issue by rajrao** [Azure/azure-cli#10468]
ServiceBus supports ZoneRedundancy in Premium SKU. There is currently not a mechanism to create ASB with ZoneRedundancy in premium tier using the CLI
https://docs.microsoft.com/en-us/cli/azure/servicebus/namespace?view=azure-cli-latest#az-servicebus-namespace-create

Ideally, this should be implemented similar to how SQL dbs can be created with Zone-Redundancy turned on (by applying --zone-redundant true)
https://docs.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#az-sql-db-create

If Zone-Redundancy is requested for basic or standard tiers, the command should fail.

**Comment by rajrao** [comment]
For reference: Zone-Redundancy was added to Sql commands via this issue: https://github.com/Azure/azure-cli/pull/5560

**Comment by v-Ajnava** [comment]
@rajrao , Thanks for submitting the bug, right now the ZoneRedundancy is available in 2018-01-01-preview, we are working on making it available in current stable version. 

we will update the CLI with --zone-redundant parameter, for now, supporting 2018-01-01-preview API version.

will keep thread posted

**Comment by yonzhan** [comment]
@v-Ajnava  any update for this issue?

**Comment by yonzhan** [comment]
@v-Ajnava how about the current status of this issue?

**Comment by Marco10101** [comment]
Is there a way to already use --zone-redundant parameter now? it seems that it is supported in the 2018-01-01-preview API version. But I would like to known how to actually use that version of the az cli.
