### ISSUE TITLE
Failure in running az vmss update on diskprofile

### ISSUE THREAD

**Issue by naragati** [Azure/azure-cli#10464]
## Describe the bug

**Command Name**
`az vmss update`

**Errors:**
```
pop from empty list
Traceback (most recent call last):
Temp\pip-install-qxmmnr17\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 654, in _run_job
Local\Temp\pip-install-qxmmnr17\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 305, in __call__
azure\cli\core\commands\arm.py, ln 525, in handler
azure\cli\core\commands\arm.py, ln 806, in set_properties
azure\cli\core\commands\arm.py, ln 968, in _get_name_path
IndexError: pop from empty list
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss update -g {} -n {} --set {} {} {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.72

```

**Comment by naragati** [comment]
### **This is autogenerated. Please review and update as needed.**

## Describe the bug

**Command Name**
`az vmss update`

**Errors:**
```
pop from empty list
Traceback (most recent call last):
Temp\pip-install-qxmmnr17\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 654, in _run_job
Local\Temp\pip-install-qxmmnr17\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 305, in __call__
azure\cli\core\commands\arm.py, ln 525, in handler
azure\cli\core\commands\arm.py, ln 806, in set_properties
azure\cli\core\commands\arm.py, ln 968, in _get_name_path
IndexError: pop from empty list
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss update --name {} -g {} --set {} {} {}`

## Expected Behavior

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.72

```
## Additional Context

**Comment by naragati** [comment]
The same works from Powershell

PS C:\Users\naragati> $vmss = Get-AzVmss -ResourceGroupName "inmobilab" -VMScaleSetName "navininmboi"
PS C:\Users\naragati> $vmss.VirtualMachineProfile.StorageProfile.OsDisk.DiskSizeGB = 512
PS C:\Users\naragati> $vmss | Update-AzVmss


ResourceGroupName                      : inmobilab
Sku                                    :
  Name                                 : Standard_DS1_v2
  Tier                                 : Standard
  Capacity                             : 2
UpgradePolicy                          :
  Mode                                 : Manual
VirtualMachineProfile                  :
  OsProfile                            :
    ComputerNamePrefix                 : navininmb
    AdminUsername                      : navin
    LinuxConfiguration                 :
      DisablePasswordAuthentication    : False
      ProvisionVMAgent                 : True
  StorageProfile                       :
    ImageReference                     :
      Publisher                        : Canonical
      Offer                            : UbuntuServer
      Sku                              : 16.04-LTS
      Version                          : latest
    OsDisk                             :
      Caching                          : ReadWrite
      CreateOption                     : FromImage
      DiskSizeGB                       : 512
      ManagedDisk                      :
        StorageAccountType             : Premium_LRS
  NetworkProfile                       :
    NetworkInterfaceConfigurations[0]  :
      Name                             : navininmboiNic
      Primary                          : True
      EnableAcceleratedNetworking      : False
      NetworkSecurityGroup             :
        Id                             : /subscriptions/8d2d94f8-2e1c-428f-9e66-d36fd0b60f42/resourceGroups/inmobilab/p
roviders/Microsoft.Network/networkSecurityGroups/navininmboinsg
      DnsSettings                      :
      IpConfigurations[0]              :
        Name                           : navininmboiIpConfig
        Subnet                         :
          Id                           : /subscriptions/8d2d94f8-2e1c-428f-9e66-d36fd0b60f42/resourceGroups/inmobilab/p
roviders/Microsoft.Network/virtualNetworks/inmobi/subnets/default
        PublicIPAddressConfiguration   :
          Name                         : pub1
          IdleTimeoutInMinutes         : 15
        PrivateIPAddressVersion        : IPv4
      EnableIPForwarding               : False
  Priority                             : Regular
ProvisioningState                      : Succeeded
Overprovision                          : True
DoNotRunExtensionsOnOverprovisionedVMs : False
UniqueId                               : 78e029f1-e242-42ac-9c62-a4fa2fe1b388
SinglePlacementGroup                   : True
PlatformFaultDomainCount               : 5
Id                                     : /subscriptions/8d2d94f8-2e1c-428f-9e66-d36fd0b60f42/resourceGroups/inmobilab/p
roviders/Microsoft.Compute/virtualMachineScaleSets/navininmboi
Name                                   : navininmboi
Type                                   : Microsoft.Compute/virtualMachineScaleSets
Location                               : centralus
Tags                                   : {}

**Comment by yonzhan** [comment]
@qwordy  please take a look and response.

**Comment by qwordy** [comment]
Thanks for you feedback.
Could you please run `az vmss update --name {} -g {} --set {} {} {} --debug` and paste the output here

**Comment by qwordy** [comment]
Hi, could you provide more detailed info? You can paste the full command here except sensitive information like resource group or name, so that I can diagnose it.

**Comment by naragati** [comment]
Hi,

I’ve updated the outputs in the github page on same day.

Regards,
Navin

**Comment by naragati** [comment]
This is the same command that I ran the other day for my internal lab

C:\Users\naragati>az vmss update -g inmobilab -n navininmboi --set VirtualMachineProfile.StorageProfile.OsDisk.DiskSizeGB = 512

**Comment by qwordy** [comment]
Do you have a space between DiskSizeGB and 512?
It's the problem. I see the same error if I insert space between key and value.
Space is used to separate multiple key-value pairs in --set.
However, I think the error message is confusing. I plan to make it more user-friendly.

**Comment by naragati** [comment]
Thanks for the feedback, yeah if the error message can be user friendly it would help in self-serving.

**Comment by qwordy** [comment]
Add to Sprint 75. Make error message more understandable.

**Comment by qwordy** [comment]
The user's problem has been solved. However, we'll improve user experience by providing more accurate error information in future release. Close the issue.

**Comment by qwordy** [comment]
I have made the error message more clear. PR merged.
