### ISSUE TITLE
License add.py script corrupts local Python libraries

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1046]
When I tried running `python scripts\license\add.py` to add the license headers to my KeyVault generated files, I noticed a few things:
1. It still fails the CI despite the files having the required license headers
2. It adds the headers to my virtual environment site-packages.

Item 2 results in my files being corrupted:

```
SyntaxError: Non-ASCII character '\xef' in file /Users/travisprescott/github/azure-cli/env/lib/python2.7/site-packages/azure/__init__.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

When I delete my virtual environment and try to recreate using `python -m virtualenv env` I get the following error:

```
SyntaxError: Non-ASCII character '\xc4' in file /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.py on line 37, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

It seems the add.py script is also adding the header to my Python 2.7 frameworks library files (and corrupting them)! Once I delete the offending header, I can proceed but other files have the header as well that shouldn't.

**Comment by tjprescott** [comment]
This was on Mac, Python 2.7.11.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
