### ISSUE TITLE
Update Azure Compute VM/VMSS cmdlets with the changes in the PR "Added priority, eviction policy and billing profile to VirtualMachineProperties. Also, adding optional billing profile to VMSS Create and Update APIs"

### ISSUE THREAD

**Issue by rakeshakkera** [Azure/azure-cli#10478]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Azure Compute

**Description of Feature or Work Requested**
Ability to create low-priority standalone VMs with variable pricing. Also adding variable pricing to low priority VMSS.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2019-03-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. This should be on the master branch
of the REST API specs repo.
PR: https://github.com/Azure/azure-rest-api-specs/commit/fb8f078deac2367f3dbcfbd8a542c77083c28a5b

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
09/24/2019

**Comment by yonzhan** [comment]
@qwordy , please take a look and response whether we can finish this by this sprint.

**Comment by qwordy** [comment]
> 
> 
> @qwordy , please take a look and response whether we can finish this by this sprint.

My answer is yes by my estimation

**Comment by qwordy** [comment]
PR has been merged. Close.
