### ISSUE TITLE
[DiskRP] Microsoft.Azure.Management.Compute CLI

### ISSUE THREAD

**Issue by pollock4595** [Azure/azure-cli#10477]
**Resource Provider**
DiskRP

**Description of Feature or Work Requested**
We need a Azure CLI support for the new API version for managed disks. This API version change allows direct upload (specifying the exact size of the upload for customers who upload their disks directly) , incremental snapshots for managed disks, and 'encryptionSettingsVersion'. It also returns some previously privileged fields to the user: 'diskSizeBytes', 'uniqueId', and 'sourceUniqueId'.

**Minimum API Version Required**
2019-03-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-03-01/disk.json

Changes from pervious version can be seen here (although the description for 'uploadSizeBytes' has the wrong lower bound under description): https://github.com/Azure/azure-rest-api-specs/compare/1a3b855...4f5dbad

**Target Date**
September 13th

**Comment by yonzhan** [comment]
@qwordy , please take a look and response whether we can finish this by September 13th.

**Comment by qwordy** [comment]
> 
> 
> @qwordy , please take a look and response whether we can finish this by September 13th.

Yes, we can. I think I can provide a initial version on time. However, it may need review and revision.

**Comment by qwordy** [comment]
Hi Joshua, I can't find the definition in Python SDK of the new features.
The Python SDK owner said
> they modified readme, but didn't add the tag to python release

I don't know the specific rules. Just remind if you forget doing something. Thanks.

**Comment by qwordy** [comment]
`CreationData` is also used by snapshot. Does snapshot support `uploadSizeBytes` too?
Disk and snapshot share some common functions in our project.

**Comment by qwordy** [comment]
After experiment, I know uploadSizeBytes must be a multiple of MiB + 512.
But still fail:
```
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidParameter
Message: The value of parameter creationData.uploadSizeBytes is invalid.
Target: creationData.uploadSizeBytes
```
Can you help me with it?

**Comment by qwordy** [comment]
> It also returns some previously privileged fields to the user: 'diskSizeBytes', 'uniqueId', and 'sourceUniqueId'.

This doesn't need modification of CLI.  CLI users can see them as long as the server provides them.

I can set `incremental` property in creation without error. But how can I know whether it is successful? I can't see this property in the returned JSON string.

**Comment by qwordy** [comment]
> 
> 
> After experiment, I know uploadSizeBytes must be a multiple of MiB + 512.
> But still fail:
> 
> ```
> msrestazure.azure_exceptions.CloudError: Azure Error: InvalidParameter
> Message: The value of parameter creationData.uploadSizeBytes is invalid.
> Target: creationData.uploadSizeBytes
> ```
> 
> Can you help me with this?

Already solved. It must be used together with --for-upload.

**Comment by pollock4595** [comment]
@qwordy


> CreationData is also used by snapshot. Does snapshot support uploadSizeBytes too? Disk and snapshot share some common logic in our project now.
> I notice that diskSizeBytes is read only. So is "size in byte" only available in create?
> --size-gb is a common argument in several commands like az disk, az snapshot, az vm disk. We need to confirm the influenced commands.

The `uploadSizeBytes` field will only be valid for disks created with the , `--for-upload` option, not snapshots nor any other disks. 

`diskSizeBytes` isn't available in create. For disks with `--for-upload` `uploadSzeBytes` is used, and for all other disks/snapshots `diskSizeGB` is used. We just want to return the size of a customer's disk/snapshot to them in bytes too, but they can't use this field to resize or set the size of disks/snapshots. 

`az disk create` will definitely be affected and needs a new parameter `uploadSizeBytes`. `az vm disk attach` shouldn't be affected since this command will attach a new disk to a VM and upload disks must be acted upon before attaching them to VM's. `az snapshot` shouldn't be affected by `uploadSizeBytes` since there's not `--for-upload` option for them.

**Comment by qwordy** [comment]
> 
> 
> @qwordy
> 
> > CreationData is also used by snapshot. Does snapshot support uploadSizeBytes too? Disk and snapshot share some common logic in our project now.
> > I notice that diskSizeBytes is read only. So is "size in byte" only available in create?
> > --size-gb is a common argument in several commands like az disk, az snapshot, az vm disk. We need to confirm the influenced commands.
> 
> The `uploadSizeBytes` field will only be valid for disks created with the , `--for-upload` option, not snapshots nor any other disks.
> 
> `diskSizeBytes` isn't available in create. For disks with `--for-upload` `uploadSzeBytes` is used, and for all other disks/snapshots `diskSizeGB` is used. We just want to return the size of a customer's disk/snapshot to them in bytes too, but they can't use this field to resize or set the size of disks/snapshots.
> 
> `az disk create` will definitely be affected and needs a new parameter `uploadSizeBytes`. `az vm disk attach` shouldn't be affected since this command will attach a new disk to a VM and upload disks must be acted upon before attaching them to VM's. `az snapshot` shouldn't be affected by `uploadSizeBytes` since there's not `--for-upload` option for them.
> 
> I'll ask about the Python and Incremental properties in the email thread

Thanks a lot. Useful information.

**Comment by qwordy** [comment]
PR has been merged. Close.
