### ISSUE TITLE
Issues with retrieving monitor metrics data

### ISSUE THREAD

**Issue by itelligence** [Azure/azure-cli#10472]
**Resource Provider**
Azure EA

**Description of Feature or Work Requested**
Our company had been using az command to retrieve resource usage/costs stats from our subscriptions. Up until the last 3 days all the reports were returning all the data as expected however now we are getting null values.

The command we execute is:
az monitor metrics list --resource /subscriptions/[subscription-id]/resourceGroups/[resource-group]/providers/Microsoft.CognitiveServices/accounts/[account] --interval P1D --start-time 2019-09-01T00:00:00Z --end-time 2019-10-01T00:00:00Z

Data from Azure suddenly started coming back with null values.

**Minimum API Version Required**
v7

**Comment by MyronFanQiu** [comment]
@itelligence Hello. Azure CLI doesn't do anything else except for calling the service endpoint. I will invite service team to take a look. Meanwhile, could you please run the command with `--debug` and paste the log to see whether the http response contains values or not?

**Comment by itelligence** [comment]
This will contain a lot of sensitive information. How can I send this to you without making this public?

**Comment by MyronFanQiu** [comment]
@itelligence Can you open a ticket through Azure portal? Or you can just check the debug information by yourself to see whether the content is null value or not? My assumption is that this issue is a service issue. I want to double confirm my assumption with the debug information.

**Comment by itelligence** [comment]
For your reference ticket id 119091024000322. All the details are there.

**Comment by MyronFanQiu** [comment]
@itelligence Thanks~

**Comment by MyronFanQiu** [comment]
@itelligence Hello. Based on the debug information, looks like this is a service issue. I talked with our CSS team, they will help you route this problem to the service team. Meanwhile, there are some bugs for our system in github page. There should be a robot appearing. I'm tracking this problem. I will leave this issue open. Please close it after your problem solved.

**Comment by itelligence** [comment]
@MyronFanQiu Thanks

**Comment by KevinBlasko** [comment]
This issue was resolved through the Azure Support Ticket.
