### ISSUE TITLE
EventGrid create should not log handshake warning for EventGrid trigger based Azure functions V2

### ISSUE THREAD

**Issue by HWouters** [Azure/azure-cli#10471]
Every time an eventgrid subscription is created for Azure Functions V2, it logs a warning 'If the provided endpoint does not support subscription validation handshake...' 

It should not show this warning for known EventGrid trigger based Functions, similar to V1 trigger based functions.

I think the following function should be extend for azure functions V2
https://github.com/Azure/azure-cli/blob/5573b5fbbc256574308822588b52fbcd7c450fea/src/azure-cli/azure/cli/command_modules/eventgrid/custom.py#L559

Difference between V1 and V2: https://docs.microsoft.com/nl-nl/azure/azure-functions/functions-bindings-event-grid#azure-cli

**Comment by ahamad-MS** [comment]
Thanks @HWouters for the feedback. We are adding this into our backlog and will handle it appropriately if needed.

**Comment by jfggdl** [comment]
@HWouters, Thanks again for requesting this change. I am going to be closing this issue as we have this item tracked in our internal backlog. If you feel that you need to reopen the issues, please let us know and we will reopen it.
