### ISSUE TITLE
az webapp deployment source config-zip command results in an error

### ISSUE THREAD

**Issue by xor-ranavikrant** [Azure/azure-cli#10487]
**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
[Errno 2] No such file or directory: 'C:\\Windows\\system32\\outfile.zip'
Traceback (most recent call last):
Temp\pip-install-qxmmnr17\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 654, in _run_job
Local\Temp\pip-install-qxmmnr17\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 305, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 485, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 322, in enable_zip_deploy
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Windows\\system32\\outfile.zip'
```

## To Reproduce:
Steps to reproduce the behaviour:

-az webapp deployment source config-zip --resource-group {} --name {} --src 'C:\Windows\system32\outfile.zip'

## Expected Behavior
Command should accept single '\\' in the source path
## Environment Summary
```
Windows-10-10.0.15063-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.72

```
## Additional Context
The command tries to take double backward slash(\\) in the src path instead of single slash that I have provided. This results in file not found error whereas the file is present at the specified path.

**Comment by panchagnula** [comment]
@xor-ranavikrant are you saying that if you run the command with the \\ in the filePath it works?

**Comment by xor-ranavikrant** [comment]
@panchagnula  No, what I'm saying is the command that I have written (-az webapp deployment source config-zip --resource-group {} --name {} --src 'C:\Windows\system32\outfile.zip') returns me file not found error despite the file being present at that location. From the error message I tried to navigate to the path 'C:\\Windows\\system32\\outfile.zip'  from file explorer and it gave the same error as file not found.My question is why is the command taking '\\' in the path when i'm providing it a value with '\' in it.

**Comment by panchagnula** [comment]
Python language uses '\' for escaping special characters in string. I don't think \\ is the problem here - can you try by having the same file in a different directory under your user profile & not system32 , I believe CLI doesn't have the privileges to read the file.

One more thing to check is are you running the CLI command line where you are running this command from as ADMIN.

**Comment by panchagnula** [comment]
Please re-activate if this still happens. with more info after trying the instructions above
