### ISSUE TITLE
Add AAD authentication options to 'az network vnet-gateway'

### ISSUE THREAD

**Issue by number213** [Azure/azure-cli#10481]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
Need to add three string properties used to configure AAD authentication in VirtualNeworkGateway

**Minimum API Version Required**
2019-04-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/5935

**Target Date**
No specific target, these are missing properties found by comparing Swagger and CLI

**Comment by number213** [comment]
cc: @Nilambari

**Comment by MyronFanQiu** [comment]
@number213 Thanks. I will put this one into our work list.

**Comment by haroldrandom** [comment]
@number213 Hi, I have some questions for you to make this request more clear.

Do you want us to add three keyword arguments to only those three commands `az network vnet-gateway create`, `az network vnet-gateway show`, `az network vnet-gateway list` ?

**Comment by number213** [comment]
Also to `az network vnet-gateway update`

**Comment by haroldrandom** [comment]
Working on it.

Could you provide some examples to demonstrate how to use these three arguments?

**Comment by number213** [comment]
Like `create/update -aad-tenant-uri "https://login.microsoftonline.com/99163270-c9ab-4279-bb12-5353ed9bf6e1" -aad-audience-id "fd11706c-e78c-4828-8be7-ac7dcefd4b17" -aad-issuer-uri "https://sts.windows.net/99163270-c9ab-4279-bb12-5353ed9bf6e1/"`
Also there should be a way to clear those three properties. I'm not sure which would be the best way to do that in CLI, maybe instead of adding new parameters to `vnet-gateway` it would be better to create subcategory `vnet-gateway aad-authorization` with `create/update/delete`.
If you have access to the repo for PowerShell cmdlet reviews, you can see discussion regarding behavior of this feature: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/309

**Comment by haroldrandom** [comment]
I would prefer the first style.
```
--aad-audience
--aad-issuer
--aad-tenant
```
Because it is the properties of VpnClientConfiguration. I would prefer to put those three under `VPN Client Arguments` like below:
![image](https://user-images.githubusercontent.com/14357159/68012957-8a911980-fcc6-11e9-8baf-f024b37a0fd0.png)

there is no need to add a subgroup.

**Comment by haroldrandom** [comment]
I would prefer the first way. 

![image](https://user-images.githubusercontent.com/14357159/68065879-93d3c200-fd6a-11e9-83cd-ac0989a3679e.png)


I think those three arguments are properties of a VirtualNetworkGateway. For now, AAD is regarded as property, not resource/sub-resource in azure-cli. The user could remove those properties like `az network vnet-gateway update --remove aad-tenant-uri`

But for now, there is a subgroup called **identity** for _ManagedIdentity_ which follows a pattern like this `network application-gateway identity assign/remove/show`. So I think maybe the style could be: ``` az network vnet-gateway ad assign/remove/show ```

What do you think? @number213 @MyronFanQiu

**Comment by number213** [comment]
Looks good to me

**Comment by haroldrandom** [comment]
I would also add those three parameters to `az network vnet-gateway update/create` for the convenience when user creates/updates under **VPN Client Arguments** section.
![image](https://user-images.githubusercontent.com/14357159/68176618-8a439780-ffc0-11e9-8d5e-d29cedf0bd26.png)

**Comment by haroldrandom** [comment]
@number213 Why I got this error after I tried `z network vnet-gateway aad assign -g "harold-rsg-01" --gateway-name "harold-vent-gw03" --aad-tenant "https://login.microsoftonline.com/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a" --aad-audience "0b1f6471-1bf0-4dda-aec3-cb9272f09590" --aad-issuer https://sts.windows.net/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a`

```
Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Network/locations/westus/operations/41cdd5fd-cb64-42de-af5f-d92bf8fe2ac0?api-version=2019-09-01.
```

Anything I missing?

**Comment by number213** [comment]
Please reach out to @Nilambari

**Comment by Nilambari** [comment]
Yes we want to add 3 AAD parameters to same command let. For removing AAD parameters from existing gateway, you can add one switch parameter:-RemoveAadAuthentication
You can check how its done for PS commit:- https://github.com/Azure/azure-powershell/commit/45a074d6af298a5b580dc44db06a0cbf469a1478#diff-ee524d96b93a8e2193479dd5bce384d8
Test example :- https://raw.githubusercontent.com/Azure/azure-powershell/master/src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayTests.ps1 Function:-Test-VirtualNetworkGatewayOpenVPNAADAuth

**Comment by haroldrandom** [comment]
@Nilambari Seems like some resources are still preparing after I create a virtual network gateway.
Last night I got the error below, but morniny today, it succeeded. Nothing changed on my code.

BTW, how can I get an AAD?

**Comment by haroldrandom** [comment]
> Yes we want to add 3 AAD parameters to same command let. For removing AAD parameters from existing gateway, you can add one switch parameter:-RemoveAadAuthentication
> You can check how its done for PS commit:- [Azure/azure-powershell@45a074d#diff-ee524d96b93a8e2193479dd5bce384d8](https://github.com/Azure/azure-powershell/commit/45a074d6af298a5b580dc44db06a0cbf469a1478#diff-ee524d96b93a8e2193479dd5bce384d8)
> Test example :- https://raw.githubusercontent.com/Azure/azure-powershell/master/src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayTests.ps1 Function:-Test-VirtualNetworkGatewayOpenVPNAADAuth

I saw it. And one question, when creatiing with aad options. Why aad authentication info not set after creation, and succeded until `Set-AzVirtualNetworkGateway -VirtualNetworkGateway $actual -AadTenant $aadTenant -AadIssuer $aadIssuer -AadAudience $aadAudienceNew` run again?

Is is expected? If so, why bother adding those three parameters when creating?

**Comment by Nilambari** [comment]
There was a bug in service due to which creation of gateway with AAD params was not setting those values. But, that bug was fixed and it should work fine now.

**Comment by haroldrandom** [comment]
No. it did't.  Look at this changes https://github.com/Azure/azure-powershell/commit/45a074d6af298a5b580dc44db06a0cbf469a1478#diff-d59c42ac6511e0efb4112829fa209a1fR695,  
specifically the function `Test-VirtualNetworkGatewayOpenVPNAADAuth`

I follow these steps and can not set AAD in the mean time I was creating a vnet-gateway.

You can try to test whehter I am wrong or not. Keep me posted.

**Comment by Nilambari** [comment]
Actually, previously we were not allowing to create gateway with AAD options. Later we removed that validation and that code is getting rolled out to production right now, will be done within a week. After that, creation of gateway with AAD params will work fine. So, we need AAD options added to create cmd let. Thanks!

**Comment by haroldrandom** [comment]
Of course.

Once the bug is done, I can write test as expected and our team will review my PR. Which won't be long
Otherwise, release this feature to the user will incur complains.

**Comment by haroldrandom** [comment]
Done.

You can use `az network vnet-gateway aad -h` for you convenience to assign/remove/show AAD info of a gateway.

Maybe we can add it to create command of vnet-gateway once the bug is fixed.
