### ISSUE TITLE
web.cofig is not getting created

### ISSUE THREAD

**Issue by SreekanthOAuth** [Azure/azure-cli#10483]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
To publish the bot, we are using publish.ps1 script. While executing seeing below error at web.config creation
Command is : 

if (-not (Test-Path (Join-Path $projFolder 'web.config'))) {
	az bot prepare-deploy --code-dir $projFolder --lang Typescript
}
az bot: 'prepare-deploy' is not in the 'az bot' command group.

**To Reproduce**
Run publish.ps1 script

**Expected behavior**
web.config file should be generated.

**Environment summary**
CLI version: 2.0.54
OS version: Windows 10
Shell Type: PowerShell on Windows)  

**Additional context**
Once the deployment is done the service is not accessible. Presuming web.config is the reason behind it.

**Comment by stevengum** [comment]
This looks to be due to using an older version of the CLI. az bot prepare-deploy was added to the command group in the March 26, 2019 release. The version of Azure CLI that needs to be used is at least 2.0.61. Can you upgrade to a later version and try running the power shell script again?

**Comment by SreekanthOAuth** [comment]
Thanks. After upgrading web.config is getting created.
