### ISSUE TITLE
Intermittent "mismatched OAuth state" when logging in; succeeds anyway

### ISSUE THREAD

**Issue by grjw** [Azure/azure-cli#10488]
## Describe the bug

When logging in to azure using the `az login` command, I sometimes get the following error stack trace as below. However the next command in the script always automatically runs and succeeds, as if the login request was successful. I receive message this only some days. Other days, I receive the normal message (in expected behavior section)

**Command Name**
`az login`

**Errors:**
```
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\_profile.py", line 1135, in _get_authorization_code_worker
RuntimeError: mismatched OAuth state

Login failed
```

## To Reproduce:
- Run the following script using powershell
```
    az login
    az vm start --subscription "aaaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee" --resource-group "MyResourceGroup" --name "MyVM"
```

- A browser window prompts up to log in to Microsoft. 
- I'm already signed in so I pick the account to use.
- The exception is then displayed. 
- Regardless whether the error is displayed, the VM is always started.

## Expected Behavior

"You have now logged in. Let's see what subscriptions you have access to...

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.65 *

```

**Comment by jiasli** [comment]
Every time `az login` is executed, a new `state` is generated in the URL. Please make sure the login page is from the same login session.

**Comment by grjw** [comment]
Ah. I'm starting two VMs in quick succession (via separate shortcuts). This pops up two login pages. Perhaps i'm logging in to the pages in the wrong order? I will try doing them consecutively and see if that resolves the issue.

Thanks!

**Comment by yonzhan** [comment]
add to S171

**Comment by qianwens** [comment]
Hi @grjw , does login consecutively solve your issue?

**Comment by grjw** [comment]
> Hi @grjw , does login consecutively solve your issue?

Hi @qianwens.

I can confirm that logging in consecutively (i.e. completing the login process before starting the next VM) appeared to fix the issue; I never had the issue after that.

**Comment by qianwens** [comment]
Thanks @grjw for confirming, glad the solution works.
