### ISSUE TITLE
Restore Point in Time not working

### ISSUE THREAD

**Issue by Thiago4breu** [Azure/azure-cli#10480]
## Describe the bug
Restore to point in time not working.

**Command Name**
`az mysql server restore`

**Behavior:**
After an issue, I needed to restore my MySql Azure database to a point in time (some hours ago). Using the Azure Portal interface, I had no luck, the command executes successfully, but when I analyze my database, it's just restore with some minutes ago, not the time I provided.

I just had provided a lot of times, and all the operations seems not to respect the parameter to restore in that point of time need.

So I went to *az mysql* to provide the necessary command to perform the operation, and according with the documentation (https://docs.microsoft.com/en-us/cli/azure/mysql/server?view=azure-cli-latest#az-mysql-server-restore) I provided the parameter --restore-point-in-time exactly in the same format, and the behavior seems the same reported above.

Tried another date formats specifying my current timezone -03:00 and no luck, all the operations have been complete, but the data seems to be the same. 

To check this, I have a database that generates a lot of logs recording the date and time of the record. After the restore, I just had connected in that database and lookup for the lasts records that show me the almost same records times and count of my production database.

## To Reproduce:
Just go to mysql resource, and execute the command to restore providing any past time to be restored.

I just used the values:
2019-09-09 10:20
2019-09-09 08:00
2019-09-08 22:00

and variations with timezone explicity in the argument --restore-point-in-time.

All the commands were executed after 2019-09-09 14:30

- _Put any pre-requisite steps here..._
- `az mysql server restore -g {} -n {} --source-server {} --restore-point-in-time {}`

## Expected Behavior
A new database version with the database records until 10:20 AM.

## Environment Summary
```
Linux-4.15.0-1055-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.72

```

**Comment by ajlam** [comment]
@Thiago4breu, I am working on reproducing the issue. 

Can you confirm if after restore, you are connecting to the newly restored server by updating your connection string to `username@<newlyrestoredserver>`?

**Comment by Thiago4breu** [comment]
Hi @ajlam, so, about your question. At the time we ran that problem, yes. I'm completely sure about connecting in the new server. Can it be something related to my account? I will try again, we had not digg too much in this issue due the fact we lost realiability in the restore service and we've setup a new backup process to ensure all the databases are safety.

I'll make a new test and send this information here soon.

**Comment by ajlam** [comment]
Hi @Thiago4breu - thanks for following up. Look forward to your response.

**Comment by ajlam** [comment]
Hi @Thiago4breu - have you had a change to test?

**Comment by ajlam** [comment]
Closing issue. Please reopen if required.

**Comment by foben** [comment]
I have the same issue with a larger MySQL database. It's a chat system database, so it's easy to see that it contains posts from a point in time after the given restore point.

**Comment by Thiago4breu** [comment]
Hi @ajlam its me again, sorry for not have check before due a lot of things happening. But, for now I have the same situation presented before....I need to restore a database and I choose the last restore point and all the restored database are uptodate.

Correlation ID: c80edc19-11fe-4de4-824a-114b1192ed1d
Tracking ID: 53c6a2fb-abc6-41d6-a911-f5f5d395b64e

I'm completely sure that I have selected the restore point in 11-Mar-2020 15:00:00 UTC.
