### ISSUE TITLE
 az storage blob upload returns TypeError

### ISSUE THREAD

**Issue by khowling** [Azure/azure-cli#1048]
az storage blob upload -c [container]-f assets/stylesheets/style.css -n style.css  --account-name [accont] --account-key [key]

this shows 0% for 10seconds, then crashes with "TypeError"

**Comment by mayurid** [comment]
//cc @tjprescott 
Could you run with the --debug option and provide the complete call stack?

**Comment by tjprescott** [comment]
@khowling also, could you provide some insight into what kind of storage account (sku) you are using along with the --debug trace?

**Comment by khowling** [comment]
@tjprescott 

--sku Standard_LRS

with --debug, the last line is
> Getting data service client service_type=BlockBlobService

Then nothing for 10seconds, then just before existing
> TypeError

I've switched to using the AZURE_STORAGE_CONNECTION_STRING method to authenticate, and that works OK

**Comment by sitano** [comment]
It's something with forged connection string which must be of the form: ${account}.blob.core.windows.net. But instead it tries to connect to:

> Getting data service client service_type=BlockBlobService
> Percent complete: %  0.0requests.packages.urllib3.connectionpool : Starting new HTTPS connection (1): 2uyv4zjhaakibs

**Comment by tjprescott** [comment]
Were you using a custom storage endpoint?

**Comment by tjprescott** [comment]
Unable to reproduce. This may have been fixed through earlier PRs. If you still experience this issue, please re-open.
