### ISSUE TITLE
az ad sp delete --id "{sp-object-id}" should not fail when Application object is not found

### ISSUE THREAD

**Issue by psignoret** [Azure/azure-cli#10493]
## Describe the bug

In Azure AD, a backing Application object will not always be present in the same tenant as the app's ServicePrincipal object. In this situation, a user should still be able to delete just the ServicePrincipal object in their tenant. The call to `_get_app_object_id_from_sp_object_id` in `delete_service_principal` should not raise an exception if the Application object is not found (or it should be caught and ignored, or it should return Empty like it used to). 

This issue was introduced in https://github.com/Azure/azure-cli/pull/9337

**Command Name**
`az ad sp delete`

**Errors:**
```
Can't find associated application id from '0a33b545-3403-4030-8793-b21f9175c299'
```

## To Reproduce:

- Register multi-tenant app in tenant A
- Instantiate app in tenant B (e.g. `az ad sp create --id "{app-id}"`, or regular consent)
- Use Azure CLI to attempt to delete ServicePrincipal object in tenant B: `az ad sp delete --id "{sp-object-id}"`

## Expected Behavior

ServicePrincipal object should be deleted, even if the backing Application object is not found in the tenant.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.72

```

**Comment by jiasli** [comment]
Similar to https://github.com/Azure/azure-cli/issues/8467. We will take a look.

**Comment by stremovsky** [comment]
Hello guys,

I initially reported this issue, so I decided to test it now with the current cloud I have in Azure.

Again, I am getting the following error:
Can't find associated application id from '6bdd92b1-xxxxxxxxx-xxx-xx'

**Comment by oomichi** [comment]
I also am still facing this issue for using Azure service.
Do we have a workaround to remove service principal forcibly?

**Comment by oomichi** [comment]
Humm, https://github.com/Azure/azure-cli/commit/a6dfefb6b07b40ee793ffc52a6a0ba9338c07eff seems to fix this issue.

**Comment by stremovsky** [comment]
@oomichi Microsoft support gave me a workaround. I published it in my blog:
https://cloudinvent.com/blog/how-to-do-assumerole-in-azure/
