### ISSUE TITLE
CommandResultItem is not iterable

### ISSUE THREAD

**Issue by kalkun** [Azure/azure-cli#10490]
## Describe the bug

**Command Name**
`az storage blob upload-batch`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 132, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload-batch -d {} --source {} --connection-string {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.72

```
## Additional Context

To add to the above: I also tried listing the content through the Portal, however it failed with a _This request is not authorized to perform this operation_. My role is set as _contributor_ on the storage account, I have not previously had problems doing either operation.

**Comment by Juliehzl** [comment]
@kalkun Can you show me more information with `--debug` for your command? Please note that don't put connection-string information here.

**Comment by Juliehzl** [comment]
One more thing to check is that if there is firewall for target storage account.

**Comment by kalkun** [comment]
(un)fortunately its working again. To my knowledge there has not been changes on our side from when these commands worked, then did not work and now are working again.
In any case, I cannot replicate it again.

**Comment by Juliehzl** [comment]
> (un)fortunately its working again. To my knowledge there has not been changes on our side from when these commands worked, then did not work and now are working again.
> In any case, I cannot replicate it again.

OK. In this way, I will close this issue and if you have any problem, feel free to open a new one or reopen it.

**Comment by rswlkr** [comment]
I am having the same issue - seems to go away if I allow access to all networks but does seem to also intermittently work when deploying through arm. I am getting the issue when restricting to one VNET and one public IP.
