### ISSUE TITLE
webapp up:This does not work for subsequent deployments.

### ISSUE THREAD

**Issue by kyallanum** [Azure/azure-cli#10492]
I know this would make sense for most developers, but something that should be noted in these docs is that subsequent deployments will error out. It looks like it may even create an "async" task and then later come back with a 204 response "No Content". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by kyallanum** [comment]
My apologies let me clarify since it made the issue for the whole page. az webapp up does not work for subsequent deployments because it is already created.

**Comment by panchagnula** [comment]
i am not sure what the issue here is pointing to => az webapp up does work for subsequent deployments - what exactly are you seeing?

**Comment by panchagnula** [comment]
please give us more info here & re-activate az web app up will work for subsequent deployments if the app is already created - only thing is if the app Name is already taken by another customer then  we throw an error.
