### ISSUE TITLE
traffic-mangaer create failed with timeout 10 set

### ISSUE THREAD

**Issue by PuffTMD** [Azure/azure-cli#10491]
## Describe the bug
When enter the command, below (👇) I receive Operation failed with status: 'Bad Request'. Details: Monitor timeout must be between 5 and 10 seconds. the timeout value is 10.  If i change this to any other value the command work.

**Command Name**
`az network traffic-manager profile create`

**Errors:**
```
Operation failed with status: 'Bad Request'. Details: Monitor timeout must be between 5 and 10 seconds.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network traffic-manager profile create --name {} --resource-group {} --routing-method {Priority} --unique-dns-name {} --custom-headers {} --status-code-ranges {200-299} {404-404} --protocol {HTTPS} --port {443} --path {} --interval {10} --max-failures {3} --timeout {10}`

## Expected Behavior

Command should execute with timeout set to 10

## Environment Summary
```
Linux-4.18.0-1018-azure-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.72

Extensions:
azure-devops 0.11.0
interactive 0.4.3
application-insights 0.1.1

```

**Comment by MyronFanQiu** [comment]
@PuffTMD Hello. Thanks for opening this issue. I checked the logic, this issue happened on server side. I will invite service team to answer.

**Comment by MyronFanQiu** [comment]
@sfiguemsft Hello. Please take a look at this issue.

**Comment by PuffTMD** [comment]
Did you manage to investigate this issue after ?

**Comment by rohinkoul** [comment]
@PuffTMD the timeout value should be between 5 and 10 and it must be less than probing interval. Since you have set the probing interval as 10 you can't set the timeout to 10. Try setting probing interval to 30 if required or set the timeout value to be <10
See https://docs.microsoft.com/en-us/azure/traffic-manager/traffic-manager-monitoring

**Comment by rohinkoul** [comment]
@sfiguemsft please close once @PuffTMD confirms.

**Comment by KarenHammons** [comment]
HI @PuffTMD, we are going to close this issue.  Please reach out if any additional questions remain.
