### ISSUE TITLE
Windows: CLI very slow if CDROM/BLURAY is assigned as D drive

### ISSUE THREAD

**Issue by chezuma** [Azure/azure-cli#10506]
**Describe the bug**
If you have a CD-ROM / BLURAY as D drive, the cli uses ages to start because of the cli tries to read, for instance: 
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\lib\site-packages\pkg_resources\__init__.py", line 76, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\lib\site-packages\pkg_resources\_vendor\packaging\specifiers.py", line 11, in <module>

**To Reproduce**
Empty your CDROM / BLURAY drive, and assign it the D letter for the drive 

**Expected behavior**
Should not read files from D drive 

**Environment summary**
2.0.73 Windows
command-modules-nspkg   2.0.3
core                              2.0.73
nspkg                              3.0.4
telemetry                          1.0.3

Installed via MSI

**Comment by yonzhan** [comment]
@fengzhou-msft add to next Sprint.

**Comment by fengzhou-msft** [comment]
`pkg_resource` is known to be slow when importing, as reported by https://github.com/Azure/azure-cli/issues/13293. We are working on removing it. 

The behavior to read from D drive is weird. Do you have some python setup in your D drive?

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please try the latest version of `azure-cli` and feel free to reopen the issue or submit a new one if it still has a problem.
