### ISSUE TITLE
Command 'az network private-resource show' does not exist

### ISSUE THREAD

**Issue by jochenvanwylick** [Azure/azure-cli#10505]
In the current CLI (2.0.73) does not have any 'az network private-resource' commands as suggested under Optional Parameters &gt; --group-id . Any idea when we can expect this?
Also the styling seems a bit off, maybe put ticks (`) around it to make Markdown understand that it's code ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8911e94f-9496-a68d-50c0-b5d536a375a4
* Version Independent ID: cc37b77b-0fa2-991b-e16b-fcdbbf183853
* Content: [az network private-endpoint](https://docs.microsoft.com/en-us/cli/azure/network/private-endpoint?view=azure-cli-latest#az-network-private-endpoint-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@jochenvanwylick These commands are under preview version. Based on my knowledge, the server side was not ready days ago. The rest api swagger and the python SDK are not ready yet. I don't know when we can expect private-resource. Currently, the private-endpoint can be created for private link service. You can just ignore the `--group-ids` since the private link service doesn't accept a group-id. I'm sorry I will adjust the help information to prevent increasing misunderstanding again.

**Comment by MyronFanQiu** [comment]
I will leave this issue open as a tracker for private-resource. @malopMSFT Hi. I'm not sure about the current status about the first party resource for private endpoint. If there is any update, can you share the information here?

**Comment by jochenvw** [comment]
@MyronFanQiu - thanks ! Can you suggest a workaround to get the group ids ? Because I think we need it in order to set up the private resource for an Azure SQL database.

**Comment by MyronFanQiu** [comment]
@malopMSFT Hello. Could you please answer the question? @jochenvanwylick  I checked the swagger spec. Looks like you can use this path `"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/privateLinkResources"` to get the group-ids. https://github.com/Azure/azure-rest-api-specs/pull/6866/files. I will sync with @malopMSFT to support new feature in Azure CLI

**Comment by MyronFanQiu** [comment]
@jochenvanwylick Hello. we have fixed the help message. In the near future, we will onboard more commands to get group id. Thanks.

**Comment by jochenvw** [comment]
Thanks !
