### ISSUE TITLE
Azure Functions - command says failed with a 200 code

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-cli#10500]
When using the command below with a GitLab repo, --
`az functionapp deployment source config --repo-url --branch  --name --resource-group --manual-integration`

the output says
`Deployment failed. Correlation ID:<id>. Operation failed with status: 200. Details: Resource state Failed`

It looks like it actually succeeded because it's a 200. But I am guessing it shows failed because it's only looking for a 202 or something similar.

**Comment by VishmayShah** [comment]
I got the same issue but it was solved when i retryed!

**Comment by RakeshMohanMSFT** [comment]
@ankitkumarr Closing this issue, if it resurfaces let us know.
