### ISSUE TITLE
Modifications to New-az vmss create CLI cmdlet to introduce new field --public-ip-per-vm-address-version

### ISSUE THREAD

**Issue by sm947** [Azure/azure-cli#10519]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Compute Resource Provider of API Version 2019-07-01 and related changes in Network Resource Provider 

**Description of Feature or Work Requested**
We are extending support for Ipv6 public Ips to be created in normal VM scenarios in addition to Ipv4 instance level public ips and we use **publicIpAddressVersion** field to distinguish between Ipv4/Ipv6. Extending similar scenario to VMSS role instanaces to also support IPv6 public ips for role instance and therefore this command needs to be introduced which will help in creating Ipv4/Ipv6 role instance public ips. publicIpAddressVersion new field related changes are already made in NRP and submitted pull request for swagger. 
Sample template use case - if user specifies [--public-ip-per-vm-address-version]and pass accepted values  Ipv4 and ipv6, then Ipv4 and Ipv6  public ips will be created for VMSS role instances 

CLI details for az vmss create  : This field needs to be created below --public-ip-per-vm if possible. 
**--public-ip-per-vm-address-version**
IP address type of public ip per vm.

accepted values: IPv4, IPv6
default value: IPv4

**Minimum API Version Required**
2019-07-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
PR Link : https://github.com/Azure/azure-rest-api-specs/commit/1307bde34f4218f5fb707579693e7216e565beb7
Changes are in compute-2019-7 branch soon to be merged to master 
https://github.com/Azure/azure-rest-api-specs/tree/compute-2019-07

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
10/01/2019

**Comment by yonzhan** [comment]
@qwordy  please take a look and comment.

**Comment by qwordy** [comment]
Your feature request has been added to Sprint 75.

**Comment by mzms** [comment]
Is this on track for Sprint 75? We need this for GA that we are announcing on Oct 15. So this absolutely MUST come.

**Comment by qwordy** [comment]
Have you merged it to master branch? I need the Python SDK which contains this feature.

**Comment by yonzhan** [comment]
@mzms  Please help to make the swagger spec and related Python SDK PRs ready in public repo for us to implement the CLI.

**Comment by yonzhan** [comment]
@mzms CLI implementation is blocked. Any update ?

**Comment by yonzhan** [comment]
@mzms  any update?

**Comment by qwordy** [comment]
@sm947 @mzms Any update?
