### ISSUE TITLE
az network nic show  command fails with Python error

### ISSUE THREAD

**Issue by DaveKlassen** [Azure/azure-cli#10511]
## Describe the bug

**Command Name**
`az network nic show`

**Errors:**
```
nothing to repeat
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 523, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 292, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
cli/command_modules/network/__init__.py, ln 38, in load_arguments
    from azure.cli.command_modules.network._params import load_arguments
...
usr/lib64/python2.7/re.py, ln 190, in compile
    return _compile(pattern, flags)
usr/lib64/python2.7/re.py, ln 242, in _compile
    raise error, v # invalid expression
error: nothing to repeat
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network nic show --name {} --resource-group {}`

## Environment Summary
```
Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.72 *

```

**Comment by MyronFanQiu** [comment]
@DaveKlassen Hello. I tested the command on linux and python 2.7.15. However I cannot reproduce same error. Can you run the command with `--debug`? Did this command fail for your all nic resource? This command in all versions from v2.0.65 to v2.0.72 CLI has failed for you. Right?

**Comment by yonzhan** [comment]
@MyronFanQiu  please take a look and comment.

**Comment by MyronFanQiu** [comment]
@DaveKlassen Thanks. Based on your trace, this issue isn't related with nic. I will check the dns part in detail. Meanwhile, is it possible for you to try other python version?

**Comment by yonzhan** [comment]
add to S169

**Comment by MyronFanQiu** [comment]
@DaveKlassen Hello. We don't support python 2 anymore. Please use python 3 instead.
