### ISSUE TITLE
Tab completion pauses standard input 

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-cli#1051]
When using tab completion, it seems that there's a long delay after hitting the TAB key. If you hit the TAB key a few times, then it seems to queue up these pauses, causing an unnecessarily large delay. 

I'm using the Docker image on a large AWS VM (4 cores, 8 GB RAM), via PuTTY. Normally, tab completion for other applications, such as tmux, run in a few milliseconds.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by mayurid** [comment]
@pcgeek86 : Thanks for the report. We are looking into this //cc @derekbekoe

**Comment by derekbekoe** [comment]
@pcgeek86 thanks for the feedback.
In our latest release (0.1.0b9), we have made some performance changes that improve tab completion speed (by ~50%).
I have created https://github.com/Azure/azure-cli/issues/1340 to track further improvements.
