### ISSUE TITLE
az ad app update Insufficient privileges in yaml build pipeline

### ISSUE THREAD

**Issue by michaelw85** [Azure/azure-cli#10515]
az cli version: 2.0.73

**Describe the bug**
Command: `az ad app update --id <xxx-yyyy-zzzz> --add replyUrls https://test.something`
Error: `ERROR: Insufficient privileges to complete the operation.`

Command is run from a yaml multistage build pipeline with a service principle where I enabled literally all permissions from all api's and used grant permissions after

**To Reproduce**
Run command using the azure cli yaml task as inline script with a ARM service connection.

**Expected behavior**
Expected to be able to add a reply url

**Environment summary**
Azure cli was installed using the latest msi installer on a locally hosted VM.

**Additional context**
I can run the command using my own account from my own device without any problems.

Edit: I have an existing app registration which I created via the portal. I just tested what happens if I make the service principle create the app registration and than add the reply url. This works fine. I also tested if a colleague could add the url since he's not an owner on the app registration (he is an owner on subscription level) and he can also add it just fine.

**Comment by jiasli** [comment]
As CLI is still using AAD Graph. The Service Principal used to login needs to have corresponding permissions. 

Go to Azure Portal > Azure Active Directory > App registrations > {app} > API permissions > Add a permission > Add **Azure Active Directory Graph** related permissions. 

Then click **Grant admin consent for {tenant}**.

Corresponding CLI commands are https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest. But it uses GUIDs which may not be easily fetched currently. We are working on improving it.

**Comment by yonzhan** [comment]
solution provided
