### ISSUE TITLE
PublicIpPrefix: add parameters PublicIpAddressVersion and IpTags

### ISSUE THREAD

**Issue by number213** [Azure/azure-cli#10527]
**Resource Provider**
`Microsoft.Network`

**Description of Feature or Work Requested**
Two parameters that are the same as in PublicIpAddress: `PublicIpAddressVersion` which is either a `IPv4` or `IPv6` and a list of `IpTags`

**Minimum API Version Required**
2018-07-01

**Swagger Link**
Initial PR: https://github.com/Azure/azure-rest-api-specs/pull/3520
Current spec: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-07-01/publicIpPrefix.json

**Target Date**
No specific target date

**Comment by MyronFanQiu** [comment]
@number213  Hello. Which command needs this new feature?

**Comment by number213** [comment]
@MyronFanQiu `network public-ip prefix`'s create/update

**Comment by MyronFanQiu** [comment]
Duplicated with https://github.com/Azure/azure-cli/issues/10757. Will close it. Feel free to re-open it if I made any mistake.
