### ISSUE TITLE
--ttl parameter not working

### ISSUE THREAD

**Issue by sbhuttan** [Azure/azure-cli#10520]
Getting following error while trying to create a CName with TTL parameter, using Azure CLI - 

```
az: error: unrecognized arguments: --ttl 300
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {network} ...
```
Azure command used: 
az network dns record-set cname set-record 

Version of azure-cli - 2.0.73 (latest as of 9/12)

Environment - Tried on both - Visual Studio Code and shell.azure.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bf2496b-338d-9d05-7c91-63b9ed576dae
* Version Independent ID: 0ae8e4a4-59ae-c756-9e5b-44239188882f
* Content: [az network dns record-set cname](https://docs.microsoft.com/en-us/cli/azure/network/dns/record-set/cname?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by sbhuttan** [comment]
Thanks for looking into this. TTL is still supported through the portal. Is support going away from portal as well? Or just not supported through CLI at this point?

**Comment by MyronFanQiu** [comment]
@sbhuttan I assume that CLI doesn't support this feature at this point. I cannot image any reason that this feature will go away from portal.

**Comment by haroldrandom** [comment]
Hi @sbhuttan , so. In this case, we only need to add _ttl_ to CNAME? What about other types of DNS record? We can add it at the same time.
