### ISSUE TITLE
"az sql vm create" description is not correct

### ISSUE THREAD

**Issue by giovannifl** [Azure/azure-cli#10533]
Hello,
I believe it should be updated "az sql vm create" definition because what this command does is to "Register SQL Server IaaS extension in Full or Lightmode "

https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/virtual-machines/windows/sql/virtual-machines-windows-sql-register-with-resource-provider.md

It doesn't literally create a SQL virtual machine  as stated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a502befd-c5a3-8aa4-3f03-a65133e73583
* Version Independent ID: 33f1db2e-73f1-e786-c1d1-6a9bb570de7b
* Content: [az sql vm](https://docs.microsoft.com/en-us/cli/azure/sql/vm?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yareyes** [comment]
Hello @giovannifl,

Thank you for your suggestion. Let me clarify how the command works: 

Once you run the "az sql vm create", we create a new SQL Virtual Machine resource available in Portal which will allow you to manage your SQL Server and do licensing changes.

![image](https://user-images.githubusercontent.com/36422356/66677449-83727080-ec1e-11e9-8052-99339dff917f.png)

This command will not create the underlying Virtual Machine. 

As part of creating a new SQL Virtual Machine resource, we install the SQL IaaS Extension on the existing Virtual Machine. Depending of customer's preference, we have LightWeight and Full extension mode. For more information, please refer to this [document.](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sql/virtual-machines-windows-sql-register-with-resource-provider?tabs=powershell#change-management-modes)

**Comment by jeroenterheerdt** [comment]
Closing this issue - @giovannifl do not hesitate to respond if you need more help.

**Comment by jeroenterheerdt** [comment]
@qwordy please close this issue
