### ISSUE TITLE
webapp:[('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')] when attempting to upload new certificate

### ISSUE THREAD

**Issue by DaveSin** [Azure/azure-cli#10531]
## Describe the bug

**Command Name**
`az webapp config ssl upload`

**Errors:**
```
[('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/OpenSSL/crypto.py, ln 3067, in load_pkcs12
    _raise_current_error()
python3.6/site-packages/OpenSSL/_util.py, ln 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('PKCS12 routines', 'PKCS12_parse', 'mac verify failure')]
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config ssl upload --name {} --resource-group {} --certificate-file {} --certificate-password {} --query {}`

## Environment Summary
```
Linux-4.9.184-linuxkit-x86_64-with-debian-9.11
Python 3.6.5
Shell: bash

azure-cli 2.0.73

```

**Comment by panchagnula** [comment]
Can you run the command with --debug & share the details please excluding any sensitive info. Thank you.

**Comment by panchagnula** [comment]
@DaveSin can you please share more details here for debugging please, after trying this with the latest version of CLI? Thank you.

Reactivate when you add more details here.

**Comment by Ado77** [comment]
Hi All, I found I had this error when my password contained special characters such as @ or $ etc...

**Comment by anuradhaarao** [comment]
Hi, I am still facing this issue and my password is just alphabets.

**Comment by panchagnula** [comment]
@anuradhaarao can you open a new issue if possible - since this was originally opened on a very old version of CLI so I'd like to get more details on this if possible. Thanks!

**Comment by anuradhaarao** [comment]
@panchagnula  - opened up a new one here : https://github.com/Azure/azure-cli/issues/1472.
