### ISSUE TITLE
Add support for Azure Bastion

### ISSUE THREAD

**Issue by rgherta** [Azure/azure-cli#10539]
Hello It would be nice to add support for Azure Bastion to Azure CLI

**Comment by MyronFanQiu** [comment]
@rgherta Hello. Thanks for opening this issue. I need check the current status of this service and make a plan for it. It may take some time. I will share the update here later.

**Comment by dduleep** [comment]
+++

**Comment by msabansal** [comment]
@ashjain Please take a look

**Comment by hm033** [comment]
@MyronFanQiu Hi. Is there any update on creating azure bastion host using azure cli?

**Comment by msabansal** [comment]
@hm033 We don't have any update on this. Part of our roadmap but needs resourcing allocated. Sorry about that
