### ISSUE TITLE
The az webapp command is missing 'Hybrid-Connection'

### ISSUE THREAD

**Issue by sorensenp** [Azure/azure-cli#10530]
When I run the 'az webapp hybrid-connection' command locally or in Azure DevOps the 'hybrid-connection' subgroup is not listed and I receive the message:
'hybrid-connection' is not in the 'az webapp' command group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c7cfef-5b38-2f56-5016-93dd4c248b6c
* Version Independent ID: 60ae2f63-be6f-02b7-3304-ba97a644e082
* Content: [az webapp hybrid-connection](https://docs.microsoft.com/en-us/cli/azure/webapp/hybrid-connection?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp/hybrid-connection.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/hybrid-connection.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
@sorensenp what is the version of CLI you are using?

**Comment by sorensenp** [comment]
Hi Sisira,

I have updated my CLI to the latest version and the switch is now appearing.

Thanks for your help.

Kind Regards,
Paul.

**Comment by panchagnula** [comment]
Great thanks for the update @sorensenp
