### ISSUE TITLE
az webapp up: error: argument --name/-n: expected one argument

### ISSUE THREAD

**Issue by lawsuf** [Azure/azure-cli#10532]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
az webapp up: error: argument --name/-n: expected one argument
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --name --resource-group --plan --sku --location {}`

## Environment Summary
```
Linux-4.15.0-1057-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.72 *

```

**Comment by panchagnula** [comment]
This means that the command parameters are being parsed correctly. I see that you are using -l  if this value has spaces make sure you use the value in double quotes ""

**Comment by panchagnula** [comment]
Closing this since I haven't heard back on this for 4 days now. Please let us know if you are still seeing this. Thanks!

**Comment by saumyasanghvi03** [comment]
argument --name/-n: expected one argument
me too getting this error - while creating web app plz help
