### ISSUE TITLE
Install on Windows 10 Bash Subsystem Fails

### ISSUE THREAD

**Issue by mayurshintre** [Azure/azure-cli#1053]
Install for CLI 2.0 fails with the _error _unable to execute 'x86_64-linux-gnu-gcc': No such file or directory_. Please provide instructions on any prerequisite libraries required to install CLI 2.0 or fix the installer.

**Comment by derekbekoe** [comment]
@mayurshintre from the [Preview Install Guide](https://github.com/Azure/azure-cli/blob/master/doc/preview_install_guide.md#ubuntu-1404-lts-and-bash-on-windows-build-14362), please run the commands below as a prerequisite before installing the CLI.

```
sudo apt-get update
sudo apt-get install -y libssl-dev libffi-dev
sudo apt-get install -y python-dev
```

**Comment by mayurshintre** [comment]
@derekbekoe This is for CLI, error is for CLI 2.0.

**Comment by derekbekoe** [comment]
@mayurshintre The instructions I provided are for the CLI that's in this GitHub repo.
This CLI is run with the `az` command.

**Comment by yugangw-msft** [comment]
@mayurshintre, there are more comprehensive instructions at https://msftstack.wordpress.com/2016/10/09/install-azure-cli-2-0-on-windows-10-linux-bash-on-ubuntu/.
I have not tried out myself (plan to do it in the next couple of days), but hope it helps
