### ISSUE TITLE
Add versioning support for linux consumption function apps 

### ISSUE THREAD

**Issue by divyagandhii** [Azure/azure-cli#10541]

**Comment by divyagandhii** [comment]
cc @ahmedelnably @ankitkumarr

**Comment by kulkarnisonia16** [comment]
For Linux Consumption and Dedicated.

**Comment by divyagandhii** [comment]
cc @pragnagopa

**Comment by fabiocav** [comment]
@divyagandhii / @pragnagopa do we have an owner for this?

**Comment by ahmedelnably** [comment]
closing this one, will track the work for Windows and Linux in https://github.com/Azure/azure-cli/issues/10549
