### ISSUE TITLE
Add support for Firewall Policy

### ISSUE THREAD

**Issue by number213** [Azure/azure-cli#10543]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
Please add new top-level resource Firewall Policy, it's child resource Rule Group and related reference to firewall policy in Azure Firewall.

**Minimum API Version Required**
2019-06-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/6708

**Target Date**
No specific date unless @gimotwanMSFT can provide one

**Comment by MyronFanQiu** [comment]
@number213 Thanks. I will take a look soon.
