### ISSUE TITLE
az webapp up is Failing consistently due to permissions on /home/krishnan.zip file

### ISSUE THREAD

**Issue by KrishnanHumanize** [Azure/azure-cli#10548]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
[Errno 13] Permission denied: '/home/krishnan.zip'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 652, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/command_modules/appservice/custom.py, ln 2932, in webapp_up
    zip_file_path = zip_contents_from_dir(src_dir, language)
cli/command_modules/appservice/_create_util.py, ln 31, in zip_contents_from_dir
    with zipfile.ZipFile("{}".format(zip_file_path), "w", zipfile.ZIP_DEFLATED) as zf:
az/lib/python3.6/zipfile.py, ln 1090, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: '/home/krishnan.zip'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --location {} --name {}`

## Environment Summary
```
Linux-4.15.0-1057-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.72 *

```

**Comment by panchagnula** [comment]
@KrishnanHumanize how are you running this command? are you using cloudShell or running from a command line - if you are using a commandline make sure you run as ADMIN since the command creates a .zip file & needs permissions to write

**Comment by KrishnanHumanize** [comment]
Got it, Will go check on it. Good suggestion.

Best Regards
—
Krishnan

________________________________

**Comment by KrishnanHumanize** [comment]
Hi Sisira, Can you help me get the command to give azure admin permissions? I am using the Azure CLI console from the portal.azure.com location. Thanks much. I could not find it.. on google.. or bing

**Comment by KrishnanHumanize** [comment]
Sisira did you see my message ?

Best Regards
—
Krishnan

________________________________

**Comment by panchagnula** [comment]
@KrishnanHumanize i am confused on how you are trying to use the az webapp up command from the portal cloudShell , webapp up creates its own zip with the contents - there is nothing you need to do in this case for Admin permissions.  can you follow the tutorial here https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python#use-azure-cloud-shell

**Comment by KrishnanHumanize** [comment]
Hi Sisira, thank you for your response. I am trying to push configuration for a website from github over to Azure. One of my developers was able to do that and it worked. But when I try to do it – it fails in the zip file step.

git clone git@github.com:<git<mailto:git@github.com:%3cgit> repository>
az webapp up --location <locale>  --name <websitename>

Does this clear things up?

Thanks

**Comment by panchagnula** [comment]
if you look at the tutorial link you will see that you need to run az webapp up from the context of the dir where the content of the code to be deployed is.
So after git clone git@github.com:<git<mailto:git@github.com:%3cgit> repository> 

you need to cd to the directory where the repo is cloned to

see the first line of this https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python#create-a-web-app

**Comment by KrishnanHumanize** [comment]
Ok got it!! I did just that and it worked. Thank you so much. Appreciate it.

**Comment by KrishnanHumanize** [comment]
Sisira – sorry one more thing – maybe permissions related. When I go to that website URL it says
“ You do not have permission to view this directory or page. “

The new directory I created do I have to give it permissions? I did not see any permission steps in the link you sent me.

Thanks
--
Krishnan

**Comment by panchagnula** [comment]
that just means on loading the site we are receiving a 500, which means for the repo you are using you might need some extra set up to be complete like connect a DB or something. All this command does is takes the content & deploys it.

**Comment by KrishnanHumanize** [comment]
Ok got it. Really appreciate it – this is the first time we are deploying the DB – so maybe that’s why its broken. Is there a way I can create a diagnostic log that I can share with the developers?

We know it works without the Database portions.

Thanks
--
Krishnan

**Comment by panchagnula** [comment]
NP - happy to help however we can. if you open the app on the Portal & select 'Diagnose and Solve Problems' you can see if that gives you some useful information for debugging. One thing you can also try is that you stop & restart the App & see if some configuration on app needs an app restart.
