### ISSUE TITLE
az functionapp create and config needs to have a way to specify & config the runtime version

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#10549]
az functionapp create and config needs to have a way to specify & config the runtime version

**Comment by pragnagopa** [comment]
Please ensure this follows same semantics as webapp. Here is an example for linux webapp: https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-create

**Comment by pragnagopa** [comment]
is this issue a dup of #Azure/azure-cli#10541 ?

**Comment by pragnagopa** [comment]
cc @fabiocav  @Francisco-Gamino 
@ankitkumarr / @ahmedelnably - can you please share proposed design for create flow?

**Comment by ahmedelnably** [comment]
We will introduce a new optional parameter called `--runtime-version` instead of aligning with az webapp

**Comment by divyagandhii** [comment]
@ahmedelnably @ankitkumarr Is there a specific reason for not aligning with the web app experience? We just need to update the existing --runtime flag to accept the version as well (--runtime "PYTHON|3.7") to align with webapps

**Comment by ahmedelnably** [comment]
it came down to consistency between the **Functions** experiences. As I believe the portal will be 2 drop down lists.

**Comment by pragnagopa** [comment]
Can you please clarify what do you mean by 
> Functions experiences

**Comment by kulkarnisonia16** [comment]
This is waiting on Ant85 release.
