### ISSUE TITLE
[Storage] Storage Endpoint needs to be updated for other clouds 

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1054]
Currently the default storage endpoint is based on public Azure. Xplat has storage suffixes for other common clouds. This code will need to be updated:

1. Once a generic multi-cloud solution is implemented, OR
2. By adding this suffix to the existing `_azure_env.py` and plumbing it through

Option 1 is preferrable, but option 2 is viable is a near term solution is necessary.

**Comment by mayurid** [comment]
/cc @derekbekoe
Keeping it in upcoming milestone as we look at multi-cloud story

**Comment by derekbekoe** [comment]
@tjprescott This has been completed now that we support multi-cloud right?

**Comment by tjprescott** [comment]
@derekbekoe, yes this issue can be closed. It looks like work will still need to be done to account for the fact that you have have custom suffixes for the different storage types, but that is separate from multi-cloud and I'll create a different issue for that.
