### ISSUE TITLE
Add support for VirtualHub in Azure Firewall

### ISSUE THREAD

**Issue by number213** [Azure/azure-cli#10544]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
There is a way to attach Azure Firewall to Virtual Hub by adding reference in Azure Firewall's properties.
```json
"properties": {
  "virtualHub": {
    "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualHubs/hub1"
  }
}
```
Please add support for that

**Minimum API Version Required**
2019-06-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/6708

**Target Date**
No specific target date

**Comment by MyronFanQiu** [comment]
@number213 Hello. The link is under private repo. Could you please give me the corresponding PR in public repo?

**Comment by number213** [comment]
@MyronFanQiu sorry, copied the wrong one. This is the PR in public repo: https://github.com/Azure/azure-rest-api-specs/pull/6708

**Comment by MyronFanQiu** [comment]
This should have been done. Thanks.
