### ISSUE TITLE
Create new CLi for ManagedNetwork

### ISSUE THREAD

**Issue by yanfa317** [Azure/azure-cli#10554]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.Azure.Management.ManagedNetwork

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.

ManagedNetwork will enable customer to control and configure their network from one single place. It will help users to manage features such as peering, security and so forth.

The following is our repo link:
https://msazure.visualstudio.com/One/_git/Networking-MNC

The following is our PR for Python SDK:
https://github.com/Azure/azure-sdk-for-python/pull/7364

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2019-06-01-preview

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/managednetwork/resource-manager

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
As early as possible

**Comment by MyronFanQiu** [comment]
@yanfa317 Thanks. I will check it soon and it's better for us to have a short meeting next week.

**Comment by MyronFanQiu** [comment]
@yanfa317 Hello. Could you share the current state of service? Private Review/Public Review/GA?

**Comment by yanfa317** [comment]
@MyronFanQiu Hi. Our service will take private review around End of Jan. Before it, we will have a big change for swagger/sdk/cli, and we are working on it. Thanks.

**Comment by MyronFanQiu** [comment]
@yanfa317 Thanks

**Comment by MyronFanQiu** [comment]
@yanfa317 Since the service is still under private review and you will have a big change for swagger. Is it ok to close this issue first and you can create a new one in the future?

**Comment by yanfa317** [comment]
@MyronFanQiu We found a bug in current cli, and @zikalino is helping us to fix it. But it seems that he is busy for something else now. I hope that we can solve the bug first before we close it.

**Comment by yonzhan** [comment]
Any update for this issue?

**Comment by yanfa317** [comment]
@yonzhan I will close it for now since we have big change in our design and will move our service into Network.
