### ISSUE TITLE
Azure VM Image Builder

### ISSUE THREAD

**Issue by danielsollondon** [Azure/azure-cli#10551]
**Resource Provider**
Microsoft.VirtualMachineImages

**Description of Feature or Work Requested**
Image builder simplifies custom image building for Windows and Linux, aiding migration, building more reliable images, without customers needing to learn how to build custom images for Azure.
 
Here is an intro video: https://www.youtube.com/watch?v=nalr2rHRDew&feature=youtu.be
 
For your team, here is the official docs, but we also have a GitHub repo, with lots of quickstarts, and solutions for you to test with.

https://github.com/danielsollondon/azvmimagebuilder
 
The CLI should be in the Azure CLI Repo and be part of the ‘az vm image’ command, covering the scenarios below.

**Minimum API Version Required**
2019-05-01-preview, note, there will be a new version in December

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/imagebuilder/resource-manager/Microsoft.VirtualMachineImages/preview

**Target Date**
We have a GA of 2/14 next year, what is the possibility of getting something by then?

**Comment by qwordy** [comment]
We have received your feature request. I will reply later after I watch the video and read the link.

**Comment by danielsollondon** [comment]
Hi @qwordy, have you checked out the video and reading material?

**Comment by danielsollondon** [comment]
Can you share your designs please, we have common scenarios we would like to achieve?

**Comment by qwordy** [comment]
Sorry for reply late. I checked the material very quickly when this issue was created. I think I need to check it again. And share my design and thought. After the release tomorrow, I'll spend more time on this.

**Comment by qwordy** [comment]
Hi Daniel, I've checked the material and understand the basic idea of image builder. It is like dockerfile in my opinion. After Ignite, we may need to schedule meetings to design CLI commands.

**Comment by yonzhan** [comment]
@qwordy add to S161.

**Comment by danielsollondon** [comment]
@qwordy - I have a spec for the CLI commands, I want these to be consistent with PS Cmdlets, and user experience required. I will send these over mid week, and schedule a meeting to review. thanks

**Comment by qwordy** [comment]
@danielsollondon 
We have published commands of image builder. You can try them and give feedback. Thanks.
https://docs.microsoft.com/en-us/cli/azure/image/template?view=azure-cli-latest

**Comment by qwordy** [comment]
We have the following issues to track the further work of image builder. So close this one.
https://github.com/Azure/azure-cli/issues/12184
https://github.com/Azure/azure-cli/issues/12196
