### ISSUE TITLE
Merge all packages in a single pypi package (for real)

### ISSUE THREAD

**Issue by Fale** [Azure/azure-cli#1055]
Having ten+ pypi packages that are kind of united but not really makes it very difficult to package it in distros, please fix it (also because due to how python includes works there is no real advantage in doing a huge amount of small packages)

**Comment by derekbekoe** [comment]
Hi @Fale 
Thanks for the feedback.
The CLI is composed of several packages for reasons similar to the Python SDK (issue referenced):
- Azure services release at different cadences.
- A full CLI with support for all Azure services as the default install would be larger.
- The CLI has a component module that allows components (commands/sets of commands) to be installed/removed so support for additional Azure services is always available for those users that require it.

**Comment by JasonRShaver** [comment]
Linking to the PythonSDK thread on the same:
https://github.com/Azure/azure-sdk-for-python/issues/815

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
