### ISSUE TITLE
az rest fails to parse json whitespace

### ISSUE THREAD

**Issue by jurgyy** [Azure/azure-cli#10562]
**Describe the bug**
Using powershell, az rest fails to parse my json correctly. I already read issue #9742 where @konrad-jamrozik had troubles parsing json correctly and he ended up having to escape the quotes (with `\"` not `` `" ``, the .ps1 escape character). So I tried that, but it didn't solve all my problems. After some fiddling I found the problem: It was the whitespace in a string.

**To Reproduce**

The following code fails:
```powershell

$uri = "https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/myRsg/providers/Microsoft.ApiManagement/service/myApim/apis/myApi?api-version=2019-01-01"

$oauthServiceName = "myOauthService"
$description = "my api description"
$displayName = "my api"
$serviceUrl = "http://localhost"
$uniqueApiPath = "myapi/"

$payloadBody = @{
    properties = @{
        authenticationSettings = @{
            authorizationServerId = $oauthServiceName
        }
        description = $description
        displayName = $displayName
        serviceUrl = $serviceUrl
        path = $uniqueApiPath
        protocols = @(
            "http"
        )
    }
}| ConvertTo-Json -Compress

$payloadBody = $payloadBody -replace "`"", "\`""

az rest --method put --headers "Content-Type=application/json" --uri $uri --body $payloadBody
```
Error:
```
az: error: unrecognized arguments: api description","serviceUrl":"http://localhost","authenticationSettings":{"authorizationServerId":"myOauthService"},"path":"myapi/","protocols":["http"],"displayName":"my api"}}
```

While if we remove the whitespace from both the description and display name it will succeed:
```powershell
$description = "myApiDescription"
$displayName = "myApi"
```

**Expected behavior**
When using the portal whitespace is allowed, so I expect the json to parse correctly when using whitespace.

**Environment summary**
Install Method: MSI  
CLI version: 2.0.73  
OS: Windows 10  
Shell Type: Powershell

**Comment by Juliehzl** [comment]
@jurgyy Thanks a lot for your feedback. I am out of office now and I will have a look when come back.

**Comment by jurgyy** [comment]
Any updates?

In the meanwhile, some debug information:

With the following body  

    {\"foo\":\"this is foo\",\"bar\":\"this is bar\",\"description\":\"this is desc\",\"baz\":\"this is baz\"}

`az rest` with the `--debug` flag shows the problem

```
 Command arguments: [
    'rest',
    '-m',
    'put',
    '--headers',
    'Content-Type=application/json',
    '-u',
    'https://management.azure.com/subscriptions/{subscriptionId}?api-version=2019-01-01',
    '-b',
    '{"foo":"this', 'is', 'foo","bar":"this', 'is', 'bar","description":"this', 'is', 'desc","baz":"this', 'is', 'baz"}',
    '--debug'
]
...
az_command_data_logger : command args: rest -m {} --headers {} -u {} -b {} {} {} {} {} {} {} {} {} --debug
...
cli.azure.cli.core.parser : az: error: unrecognized arguments: is foo","bar":"this is bar","description":"this is desc","baz":"this is baz"}
az: error: unrecognized arguments: is foo","bar":"this is bar","description":"this is desc","baz":"this is baz"}
```

Notice the strange comma separation of the json in the command arguments and the number of `{}` in az_command_data_logger.

**Comment by jurgyy** [comment]
If anyone encounters this issue before it is fixed I've found that writing the json to a temporary file and reference that works fine:

```ps1
$dict | ConvertTo-Json -Depth 100 > "./tmp/body.json"  
az rest -m put --headers "Content-Type=application/json" -u $uri -b "@tmp/body.json"
```

**Comment by zhoxing-ms** [comment]
@jurgyy Hi, this problem is also related to the parsing of `:\`, which has a special meaning in PowerShell, like: [about_providers](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_providers?view=powershell-7), [about_locations](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_locations?view=powershell-7)
So `:` and `\` can be separated by spaces in the script as work around, like:
```
$payloadBody = $payloadBody -replace "`"", "\`"" -replace ":\\", ": \"
```
You can have a try. If you still have any questions, please feel free to let us know~

**Comment by yonzhan** [comment]
@jurgyy any feedback ?

**Comment by jurgyy** [comment]
I haven't tested it myself yet, but if it works this workaround is fine I guess. Not much you can do about Powershell's special characters anyway. Thanks!

**Comment by zhoxing-ms** [comment]
@jurgyy OK, I'll close it first. If you still have any other questions, please feel free to let us know~
