### ISSUE TITLE
The command az aks create failed with an unexpected error

### ISSUE THREAD

**Issue by SatishRanjan** [Azure/azure-cli#10569]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
'registrationState'
Traceback (most recent call last):
pip-install-rg707cll\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 654, in _run_job
Temp\pip-install-rg707cll\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 631, in _run_job
cli\core\commands\__init__.py, ln 306, in __call__
...
pip-install-rg707cll\requests\requests\hooks.py, ln 31, in dispatch_hook
msrest\msrest\universal_http\requests.py, ln 275, in user_hook_cb
pip-install-rg707cll\msrestazure\msrestazure\tools.py, ln 57, in register_rp_hook
pip-install-rg707cll\msrestazure\msrestazure\tools.py, ln 102, in _register_rp
KeyError: 'registrationState'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --enable-addons {} --generate-ssh-keys`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.73

```

**Comment by seanmck** [comment]
@SatishRanjan which add-ons were you trying to enable on your cluster?

**Comment by seanmck** [comment]
Need more information to investigate. Please reopen if this is still happening and you can answer my question above.

**Comment by gurupasupathy** [comment]
I am able to repro this issue. I used the below to create a cluster and got the error. The addon I tired for was http_application_routing

az aks create --resource-group RG-XX-XX --name myAKSCluster --service-principal xxxxxxxxxxxxxxxxxxx --client-secret xxxxxxxxx --node-count 1 --enable-addons http_application_routing`


'registrationState'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-6nyhv9qe\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
 ...
if rp_info['registrationState'] == 'Registered':
KeyError: 'registrationState'
