### ISSUE TITLE
Cant login and get subscriptions in CLI 

### ISSUE THREAD

**Issue by adodado** [Azure/azure-cli#10564]
When i try to login with Azure CLI i cannot get my subscriptions. But if i login via browser there is no issue. Please help. 

**Command Name**
`az login`

**Errors:**
```
No subscriptions were found for 'None'. If this is expected, use '--allow-no-subscriptions' to have tenant level accesses
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.73

```

**Comment by jiasli** [comment]
Is `-t` used or simply `az login`? Could you share the `--debug` output to my email?

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
@adodado any update?

**Comment by qianwens** [comment]
Close this issue since there is no response for more than 15 days. Please help file a new issue if you have questions.

**Comment by ufalak** [comment]
Im having the same issue
