### ISSUE TITLE
az ad app permission list gives error when a permission is not granted

### ISSUE THREAD

**Issue by pascalnaber** [Azure/azure-cli#10563]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.73

**Describe the bug**
When a permission is added which needs a grant, "az ad app permission list" gives an exception.
After the grant it works again as it should.

**To Reproduce**
Create Client SPN
Create Backend SPN
Configure Oauth on BackendSPN

Request Permissions from Client SPN
az ad app permission list --id $SPN_CLIENT_ID 

Add Permissions
az ad app permission add --id $SPN_CLIENT_ID --api $SPN_BACKEND_ID --api-permissions $OAUTH_UNIQUEID=Scope

Request Permissions from Client SPN
az ad app permission list --id $SPN_CLIENT_ID 
Operation failed with status: 'Not Found'. Details: 404 Client Error: Not Found for url: https://graph.windows.net/<tenantid>/oauth2PermissionGrants?$filter=clientId%20eq%20%<SPN_CLIENT_ID>%27&api-version=1.6

**Expected behavior**
To have a successful behavior again:
Step: Grant the new permission 
Now it succeeds again:
az ad app permission list --id $SPN_CLIENT_ID

**Comment by jiasli** [comment]
Thank you for reaching us. We will investigate this issue.

**Comment by yonzhan** [comment]
add to S171

**Comment by qianwens** [comment]
Hi @pascalnaber , to better understand your requirement, do you expect the list to return [] instead of giving an error if permission not granted?

**Comment by pascalnaber** [comment]
Yes, I think so

**Comment by jiasli** [comment]
Looks like the AD Graph API `oauth2PermissionGrants` doesn't return 404 anymore:

```
msrest.http_logger : Request URL: 'https://graph.windows.net/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/oauth2PermissionGrants?$filter=clientId eq 'c726656d-b23f-4f6f-b01e-9db96e3f0c4f'&api-version=1.6'
msrest.http_logger : Request method: 'GET'
...

msrest.http_logger : Response status: 200
...
msrest.http_logger : Response content:
msrest.http_logger : {"odata.metadata":"https://graph.windows.net/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/$metadata#oauth2PermissionGrants","value":[]}
```

@pascalnaber, is the issue still happening for you? If so, could you provide the raw `--debug` log.

**Comment by jiasli** [comment]
If you are able to reproduce again, please kindly reply here.
