### ISSUE TITLE
Create CLI for Microsoft Azure Peering Service

### ISSUE THREAD

**Issue by somesh84** [Azure/azure-cli#10570]
**Is your feature request related to a problem? Please describe.**
Microsoft Azure peering service is a new service for Microsoft customers to connect using Internet. This service provides reliable and fast internet path from customers branch office to Microsoft network.

**Describe the solution you'd like**
We have powershell today, we would like to add CLI.

**Describe alternatives you've considered**
NA

**Additional context**
1. Documentation - https://peering-docs.azurewebsites.net/en-us/azure/peering/ 
2. Swagger - https://msazure.visualstudio.com/One/_git/Networking-WANDP/?path=%2Fsrc%2Fconfig%2FSwaggerSpecifications%2F2019-08-01-preview%2Fpeering.json&version=GBmaster
3. Contact - prsanapa, rimckenn, someshch

**ETA**
Ignite

**Comment by MyronFanQiu** [comment]
@somesh84 Thanks. I will take a look soon.

**Comment by somesh84** [comment]
thanks
________________________________

**Comment by MyronFanQiu** [comment]
@psanapathi Hello. Is [this](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/peering/resource-manager/Microsoft.Peering/preview/2019-08-01-preview/peering.json) the public swagger spec? I checked the python SDK, however I cannot find the corresponding SDK. Do we have python SDK?

**Comment by somesh84** [comment]
+ Praneeth
________________________________

**Comment by psanapathi** [comment]
> @psanapathi Hello. Is [this](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/peering/resource-manager/Microsoft.Peering/preview/2019-08-01-preview/peering.json) the public swagger spec? I checked the python SDK, however I cannot find the corresponding SDK. Do we have python SDK?

Yes, that's the public spec. And, yes, we don't have Python SDK. We have [readme](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/peering/resource-manager/readme.python.md) for generating Python SDK automatically but AutorestCI doesn't pick this up.
![image](https://user-images.githubusercontent.com/1693630/65293273-87274180-db0f-11e9-9758-99f588d0d793.png)

**Comment by MyronFanQiu** [comment]
@psanapathi Hi. You can send a request for python SDK through https://portal.azure-devex-tools.com/

**Comment by MyronFanQiu** [comment]
https://github.com/Azure/azure-cli-extensions/tree/master/src/peering Please check.
