### ISSUE TITLE
"az apim update" does not work

### ISSUE THREAD

**Issue by amiraliw** [Azure/azure-cli#10575]
## Describe the bug

**Command Name**
`az apim update`

**Errors:**
```
No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
Traceback (most recent call last):
pip-install-rg707cll\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 523, in execute
azure\cli\core\__init__.py, ln 291, in load_arguments
cli\core\commands\__init__.py, ln 291, in load_arguments
pip-install-rg707cll\knack\knack\commands.py, ln 97, in load_arguments
cli\core\commands\arm.py, ln 427, in generic_update_arguments_loader
...
<frozen importlib._bootstrap_external>, ln 678, in exec_module
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
cli\command_modules\apim\custom.py, ln 9, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim update --resource-groups {} --name {} --publisher-mail {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.73

```

**Comment by jurgyy** [comment]
Same problem as #10496 and #10422. I've issued a pull request that should solve this: #10623

**Comment by navba-MSFT** [comment]
@amiraliw Apologies for the delayed response. I was able to run the [az apim update](https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest#az-apim-update) command:

>az apim update --resource-group 'ApimRG' --name 'ApimName' --publisher-email 'test@test.com'

Please check if you are still facing this issue. This github issue has been open for quite some time now. Please let us know if you need any further help. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@amiraliw This is a quick follow-up to check if you had a chance to follow the action plan in my above comment. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@amiraliw We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
