### ISSUE TITLE
webapp: Seems like more attributes are required then specified here

### ISSUE THREAD

**Issue by olesjo** [Azure/azure-cli#10587]
When running the command 

az webapp webjob triggered run --webjob-name nameofmywebjobhere

I get the following error in azure devops: ERROR: (--resource-group --name | --ids) are required

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: 658f1fef-16b7-df78-9d60-926f6699943a
* Version Independent ID: d3354ba5-8dba-1c56-64bd-d782c5676b53
* Content: [az webapp webjob triggered](https://docs.microsoft.com/nb-no/cli/azure/webapp/webjob/triggered?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp/webjob/triggered.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/webjob/triggered.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
the command is sets this as optional because you can set a default value for it using az configure --defaults group=<name>, otherwise you either need a RG or resource ID
