### ISSUE TITLE
Minor grammar issue

### ISSUE THREAD

**Issue by nwohlgemuth** [Azure/azure-cli#10592]
Documentation for --timeout option "The time in seconds allowed for endpoints to response to a health check." has a minor grammar issue - should be "respond" instead of "response".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8f3db91-d932-fd75-a98e-e125bc297ca8
* Version Independent ID: 985b32d5-634c-9883-6e27-223cb83f21cf
* Content: [az network traffic-manager profile](https://docs.microsoft.com/en-us/cli/azure/network/traffic-manager/profile?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@nwohlgemuth Thanks. I will make a fix for this issue soon.
