### ISSUE TITLE
Error when running the az webapp up on my debian 10 box running azure-cli version 2.70

### ISSUE THREAD

**Issue by sumgr0** [Azure/azure-cli#10606]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


glob() got an unexpected keyword argument 'recursive'
Traceback (most recent call last):
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
TypeError: glob() got an unexpected keyword argument 'recursive'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --location {} --name {}`

## Environment Summary
```
Linux-4.19.0-5-cloud-amd64-x86_64-with-debian-10.1
Python 2.7.16
Shell: bash

azure-cli 2.0.70 *

```

**Comment by panchagnula** [comment]
this is a known issue that was fixed on a later version. You can fix this either by installing the newer cli version https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.0.72 or install Python 3.5 on your machine.

**Comment by sumgr0** [comment]
Thanks for the quick revert @panchagnula. I've already got the python3.7.3 installed, so as a workaround, created an alias to python pointing to my python3 location.

What is the best way to install the azure-cli2.0.72 on debian 10, since the repos are not available yet?

**Comment by panchagnula** [comment]
Have you tried using this command pip install azure-cli==2.0.72

**Comment by sumgr0** [comment]
> Have you tried using this command pip install azure-cli==2.0.72

This worked, thanks @panchagnula

**Comment by panchagnula** [comment]
I am going to close this one out.
