### ISSUE TITLE
az acr --login requires Docker

### ISSUE THREAD

**Issue by Salamandastron1** [Azure/azure-cli#10608]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
`az acr login` requires that docker be running a docker daemon as the azure cli runs `docker ps`. I am trying to run the login command as part of a pipeline with with microsoft azure cli docker image. I don't care about docker, I care about the azure login. Please remove the tight coupling.

**To Reproduce**
Steps to reproduce the behavior.
Run the azure cli as part of a Concourse (or any) CI pipeline.
from shell run
```
$ az acr login -name <redacted> -u <redacted> -p <redacted>
```
receive error: `Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

**Expected behavior**
A clear and concise description of what you expected to happen.j
I expect to login into the azure oci repository. 

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

install method: microsoft azure cli docker image, on docker hub. Latest
os: linux-ubuntu
shell: bash

**Additional context**
The coupling is too tight between docker and the acr repositories. I understand the desire with `docker ps` being called but it assumes too much. I should be able to login into azure without docker.

**Comment by cegraybl** [comment]
Hello @Salamandastron1, I'm not sure if I'm getting the question right, if not please elaborate further.

If you just need the Azure login you should just run "az login", which is independent from docker.

The "az acr login" is a different command which is actually a wrapper for "docker login" to get access to the registry itself, so it is a dependency.

**Comment by Salamandastron1** [comment]
My desire to use `az acr login` was to limit the scope of users access as part of pipeline. As it only points to that repository.

The cli runs a `docker ps`. Which errors: 
```
ERROR: An error occurred: DOCKER_COMMAND_ERROR
Please verify if Docker client is installed and running.
```

Perhaps the issue is better brought forward to those who maintain the container image on dockerhub? Thanks for taking the time to look this over.

**Comment by rosanch** [comment]
@Salamandastron1 if you want to get only access to the registry without docker. I'd recommend creating a service principal and give access it access to only the registry (in the registry access policy). 
Then do:
az login --service-principal --username APP_ID --password PASSWORD --tenant TENANT_ID
You don't even need admin enable in the registry with this method, and still, ensure you only share user and password to access only the registry. 
You could do the same with other Azure Resources if you like as well.

**Comment by yugangw-msft** [comment]
Closing, based on the clarification the right command to run in the Azure CLI container is `az login`, though feel free to reactivate if there are issues specific to ACR
