### ISSUE TITLE
webapp:App service configuration variables

### ISSUE THREAD

**Issue by carlosMedrano27** [Azure/azure-cli#10607]
I'm running an app service on azure using Ruby on Rails and Ubuntu, the problem is that with Application settings, I add a variable for Azure Container Key is not recognizing the '==' that are at the end of the key, I try to add '/=/=' instead and is not working, I also try to put the hole key around double quotes but still not working, I also try to generate new keys but it seems that every keys end with the '==' characters

**Comment by panchagnula** [comment]
can you share more details on the actual command you are trying to run plus the appsetting you are try to set? Thanks! is this the command you are referring to here? https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az-webapp-config-appsettings-set

**Comment by panchagnula** [comment]
Closing this due to lack of response, please reactivate if you are still facing this and also providing us more information for debugging this like we requested above. Thanks!
