### ISSUE TITLE
Duplicate field names in JSON of `az postgres server list`

### ISSUE THREAD

**Issue by danielbecroft** [Azure/azure-cli#10614]
## Describe the bug
There are duplicate fields with names that differ only by case appearing in the `storageProfile` node of the JSON output.

**Command Name**
`az postgres server list`

**Errors:**
There are duplicate fields appearing under the `storageProfile` node:

```
"storageProfile": {
  "backupRetentionDays": 7,
  "geoRedundantBackup": "Disabled",
  "storageAutoGrow": "Disabled",
  "storageAutogrow": null,
  "storageMb": 10240
},
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az postgres server list --resource-group {}`

## Expected Behavior
Only a single entry would be reported.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.73

Extensions:
db-up 0.1.13
interactive 0.4.2

```

**Comment by rachel-msft** [comment]
@danielbecroft Thank you for your feedback. We are aware of the issue and working to fix it. We expect the fix to be available by end of November.

(523139)

**Comment by rachel-msft** [comment]
Work on this is in progress. Still expected to be available November end.

**Comment by rachel-msft** [comment]
@danielbecroft Unfortunately, our deployment train for this has experienced delays. This, combined with our no-fly zones for the Christmas/New Year season, means that this fix will be delayed to January. We apologize for the delay.

**Comment by rachel-msft** [comment]
My apologies, the deployment train for this is still undergoing some delays. Updated ETA is February end.

**Comment by rachel-msft** [comment]
This has been fixed. Thank you for your patience.

`  "sslEnforcement": "Enabled",
"storageProfile": {
    "backupRetentionDays": 7,
    "geoRedundantBackup": "Disabled",
    "storageAutogrow": "Enabled",
    "storageMb": 5120`
