### ISSUE TITLE
What algorithm used for secret

### ISSUE THREAD

**Issue by cicorias** [Azure/azure-cli#10615]
What is the specific algorithm used for `az ad sp create` for the generated password that is returned? How is it attempting randomization and obscurity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by pjirsa** [comment]
Looks like it is just using a new uuid
https://github.com/Azure/azure-cli/blob/f8aeed58c3af83a2ab8ce57bf060fab29088e81b/src/azure-cli/azure/cli/command_modules/role/custom.py#L1197

**Comment by cicorias** [comment]
Thanks for finding, seems all are using whatever uuid package comes in as some connected dependency as I don’t see any explicit demand in setup

https://github.com/Azure/azure-cli/blob/c83710e4176cf598fccd57180263a4c5b0fc561e/src/azure-cli-core/azure/cli/core/commands/arm.py#L1096
