### ISSUE TITLE
Batch file stopped after az command.

### ISSUE THREAD

**Issue by vwxyzh** [Azure/azure-cli#10613]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Command line stopped after execute az command.

**To Reproduce**
Create an batch file like following:
```
az --help
echo Great!
```

**Expected behavior**
Show Great! after run `az --help`

**Environment summary**
* Install Method: MSI
* CLI version:
> azure-cli                         2.0.73
>
> command-modules-nspkg               2.0.3
> core                              2.0.73
> nspkg                              3.0.4
> telemetry                          1.0.3

* OS version: Win 10
* Shell Type: cmd.exe

**Additional context**

**Comment by qwordy** [comment]
I have reproduced your problem. Very interesting!

**Comment by qwordy** [comment]
Use `call`

```
call az --help
echo Great!
```

**Comment by qwordy** [comment]
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/call

**Comment by qwordy** [comment]
If you have any other questions, reopen this issue or open a new issue. Thanks.

**Comment by joergkrause** [comment]
For understanding: az is a Python based batch environment, not an executable. Just type `where az` and see that it points to "az.cmd" itself (not an *az.exe*). That's why the `call` command is required.
