### ISSUE TITLE
webapp:Was trying to set the clientCertEnabled = true but it failed with the following error

### ISSUE THREAD

**Issue by DrReedo** [Azure/azure-cli#10616]
## Describe the bug
Was trying to set the clientCertEnabled = true for my API in my resource group as described here:
https://docs.microsoft.com/en-us/azure/app-service/app-service-web-configure-tls-mutual-auth but it failed as below.

**Command Name**
`az webapp update`

**Errors:**
```
'NoneType' object has no attribute 'kind'
Traceback (most recent call last):
Temp\pip-install-rg707cll\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 654, in _run_job
Local\Temp\pip-install-rg707cll\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure\cli\core\commands\arm.py, ln 515, in handler
azure\cli\command_modules\appservice\custom.py, ln 431, in update_webapp
AttributeError: 'NoneType' object has no attribute 'kind'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp update --set {} --name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.10586-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.73

```

**Comment by panchagnula** [comment]
when using CLI make sure the subscription you are using is the  one that has the RG you are using in the command. 

you can az account show to verify this. This error indicates that App or RG values are either incorrect or are not on the subscription that is being used
