### ISSUE TITLE
Missing command to create resource group & deploy template

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1061]
azure-xplat-cli allowed me to do `azure group create -f <blah.json> -e <parameters.json>`.

This short-hand is missing in the new CLI, so I have to create the group manually, and then the deployment.

**Comment by yugangw-msft** [comment]
We have reviewed this with ARM team, and we are fine with `group create` be just a simple group create, as the group itself will live much longer, and will contain more deployments, so people need to use `group deployment` individual anyway.
But let me know if you feel this will be a significant inconvenience.

**Comment by colemickens** [comment]
Hm, I understand not having `group create` take the file/parameters input.

But why not have `group deployment create` create the resource group if it's missing?

**Comment by colemickens** [comment]
Yeah, this should definitely be changed. As is, I can't have idempotent scripts to deploy stuff because I get stuff like this now:

```shell
resource group colemick-blah already exists
```

This makes things that were easy in xplat-cli needlessly difficult to script.

**Comment by colemickens** [comment]
Is this still true, even after the reshuffle that has `az group list` returning rather than `az resource group list` ?

**Comment by lostintangent** [comment]
Would #1771 be relevant here? That way, you could run `az group deployment create`, and it would create the resource group if necessary.

**Comment by yugangw-msft** [comment]
@johanste, please triage

**Comment by johanste** [comment]
It is a bug that resource group create fails if it already exists. That should be fixed. And this should make the idempotent:ness of the script easier as well.

**Comment by johanste** [comment]
The resource group create failing on recreating has been addressed. The automatic creation of the resource group is something that we will consider in a future release, but not right now. 

There are some subtle (but important) nuances that would have to be worked through related to issues like #1377 that would likely introduce breaking changes if they were not considered at the same time.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
