### ISSUE TITLE
Install Cli error 

### ISSUE THREAD

**Issue by paulliu10** [Azure/azure-cli#10624]
In my local CENTOS 7.x  environment when I install the Cli have below error, any idea for this issue?

============================================
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package azure-cli.x86_64 0:2.0.74-1.el7 will be installed
--> Processing Dependency: python-virtualenv for package: azure-cli-2.0.74-1.el7.x86_64
--> Running transaction check
---> Package python-virtualenv.noarch 0:15.1.0-2.el7 will be installed
--> Processing Dependency: python2-devel for package: python-virtualenv-15.1.0-2.el7.noarch
--> Running transaction check
---> Package python-devel.x86_64 0:2.7.5-76.el7 will be installed
--> Processing Dependency: python(x86-64) = 2.7.5-76.el7 for package: python-devel-2.7.5-76.el7.x86_64
--> Finished Dependency Resolution
Error: Package: python-devel-2.7.5-76.el7.x86_64 (base)
           Requires: python(x86-64) = 2.7.5-76.el7
           Installed: python-2.7.5-77.el7_6.x86_64 (@updates)
               python(x86-64) = 2.7.5-77.el7_6
           Available: python-2.7.5-76.el7.x86_64 (base)
               python(x86-64) = 2.7.5-76.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest 
=====================================================

Thank you very much!

Paul

**Comment by paulliu10** [comment]
Any Suggestions on this?


Thanks!

Paul

**Comment by fengzhou-msft** [comment]
@paulliu10 I cannot reproduce this issue on Centos 7. It seems in your environment azure-cli requires 2.7.5-76.el7, on my side the required version is 2.7.5-86.el7. According to the error message, do you have python-devel 2.7.5-77.el7_6 installed on your machine? Please run `yum --showduplicates list python-devel` and paste the result here.

**Comment by paulliu10** [comment]
Hi Fengzhou,

Thank you for reply, the result as below:

yum --showduplicates list python-devel
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Available Packages
python-devel.x86_64                                                                                          2.7.5-76.el7                                                                                           base

**Comment by fengzhou-msft** [comment]
@paulliu10 from the message, no python-devel package is installed on your centos and the available package matches azure-cli's requirement. Please run `sudo yum update` and `sudo yum install azure-cli` to try again. If it's still not working, please run `cat /etc/centos-release` and paste the exact centos verison here.

**Comment by paulliu10** [comment]
Hi Fengzhou

When run yum update got below information:
=====================================
---> Package tuned.noarch 0:2.10.0-6.el7_6.3 will be updated
---> Package tuned.noarch 0:2.11.0-5.el7_7.1 will be an update
--> Finished Dependency Resolution
Error: Package: kernel-3.10.0-1062.1.1.el7.x86_64 (updates)
           Requires: linux-firmware >= 20190429-72
           Installed: linux-firmware-20180911-69.git85c5d90.el7.noarch (@base)
               linux-firmware = 20180911-69.git85c5d90.el7
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles –nodigest

[~]$
=================================

**Comment by fengzhou-msft** [comment]
@paulliu10  run `cat /etc/centos-release` and paste the exact centos verison here. I'll try to reproduce with your centos verison

**Comment by fengzhou-msft** [comment]
Great. Thanks.
