### ISSUE TITLE
Able to link the same iothub twice to IoT Device Provisioning Service

### ISSUE THREAD

**Issue by perkops** [Azure/azure-cli#10628]
## Describe the bug
When linking an IoTHub, through the portal, to a Device Provisioning Service, you are not able to link the same IotHub twice. This is possible through the az cli.

The az cli accepts the command twice, but the third time, the error below is thrown:

Cannot have duplicate iot hubs in description. If you contact a support representative please include this correlation identifier: xxxxx, timestamp: , errorcode: IH400303.

**Command Name**
`az iot dps linked-hub create`

**Errors:**
It is possible to link the same IoTHub twice to a DPS service.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az iot hub create --name {} --resource-group {}`
- `az iot dps create --name {} --resource-group {}`
- `az iot dps linked-hub create --connection-string {} --dps-name {} --location {} --resource-group {}`
- `az iot dps linked-hub create --connection-string {} --dps-name {} --location {} --resource-group {}`

## Expected Behavior
It should not be possible to link the same IoTHub twice.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.73 *

Extensions:
azure-cli-iot-ext 0.8.0

```

**Comment by jlian** [comment]
Adding a label for DPS. @iluican can you confirm that this is a bug on the CLI? Also @nberdy for FYI

**Comment by SaurabhSharma-MSFT** [comment]
@iluican @nberdy Do you have any updates ?

**Comment by vilit1** [comment]
This issue has been fixed in the new azure-iot extension. If you have any other issues, feel free to reopen
