### ISSUE TITLE
Using az webapp config appsettings set from Powershell results in python error

### ISSUE THREAD

**Issue by n3rd253** [Azure/azure-cli#10625]
## Describe the bug

**Command Name**
`az webapp config appsettings set`

**Errors:**
```
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
azure/cli/core/util.py, ln 244, in shell_safe_json_parse
    return json.loads(json_or_dict_string)
lib/python3.7/json/__init__.py, ln 348, in loads
    return _default_decoder.decode(s)
lib/python3.7/json/decoder.py, ln 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.7/json/decoder.py, ln 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

...

cli/command_modules/appservice/custom.py, ln 192, in update_app_settings
    setting_name, value = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config appsettings set --name {} --resource-group {} --settings {} {}`

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.72

```

**Comment by panchagnula** [comment]
This is not specific to webapp commands make sure you escape the parameters correctly when using CLI commands in Powershell. @qwordy do you have any tips on using CLI comamnds with Powershell?

**Comment by qwordy** [comment]
Could you provide the concrete command you run? Thanks.

**Comment by qwordy** [comment]
> 
> 
> This is not specific to webapp commands make sure you escape the parameters correctly when using CLI commands in Powershell. @qwordy do you have any tips on using CLI comamnds with Powershell?

I guess the user adds space around '='.

**Comment by panchagnula** [comment]
@n3rd253 please re-activate this if you are still having trouble - also make sure before you reactivate you follow the suggestions @qwordy stated above plus give us more info (concrete command you are using). Thanks!
