### ISSUE TITLE
ADLS Gen 2 inter-op work

### ISSUE THREAD

**Issue by zezha-msft** [Azure/azure-cli#10620]
**Resource Provider**
Storage

**Description of Feature or Work Requested**
Expectations for ADLS Gen 2 inter-op work in the CLI:

1. Targeting October 25th, but may be ready earlier.
2. The scope includes the directory operations (create/rename/delete), and access control operations (get/set).
3. Private drop will be made available for testing purposes.
4. Sample scripts will be shown in the help messages, and documentation published on the docs site.
5. Documentation for mapping between ADLS Gen 1 -> ADLS Gen 2 commands.
 

**Minimum API Version Required**
2019-02-02

**Target Date**
October 25th, 2019

**Comment by yonzhan** [comment]
@Juliehzl  please take a look and response.

**Comment by Juliehzl** [comment]
CLI team already have a plan for your feature request.

**Comment by yonzhan** [comment]
@Juliehzl you can link the PR and I will close this issue right now.
