### ISSUE TITLE
Incorrect documentation. 

### ISSUE THREAD

**Issue by psgivens** [Azure/azure-cli#10626]
## Describe the bug
The introduction blog for [Query Previous Command](https://azure.microsoft.com/en-us/blog/welcome-to-azure-cli-shell)] is incorrect. It shows a single question mark (?) where there should be two. 

The [official documentation](https://docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?view=azure-cli-latest) does not do a good job of explaining that gestures are even a thing. 

Also, on Ubuntu 18.04, cli version 2.0.74, (interactive 0.4.3), F3 does not do anything useful. 

**Command Name**
`Unknown`

**Errors:**
```
az: '?' is not in the 'az' command group. See 'az --help'.

az: '?[*].name' is not in the 'az' command group. See 'az --help'.

az: error: unrecognized arguments: The documentation is incorrect about jmesfeedback. It shows a single question mark (?), when it should show two. https://azure.microsoft.com/en-us/blog/welcome-to-azure-cli-shell/
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ? [*].name`

## Environment Summary
```
Linux-5.0.0-29-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.74

Extensions:
interactive 0.4.3

```

**Comment by jiasli** [comment]
Thank you for raising this issue. The blog is not the current official channel for CLI documentation. We will improve the [official documentation](https://docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?view=azure-cli-latest). Since `az interactive` is still under preview, we are actively working on it.

**Comment by navba-MSFT** [comment]
@psgivens Apologies for the late reply. [This](https://docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?view=azure-cli-latest) official article has the right documentation. Could you please look into it and let us know if there are any issues? We would be happy to address it. Awaiting your reply.
