### ISSUE TITLE
There's no way to create a secondary managed instance for use in a failover group

### ISSUE THREAD

**Issue by simonmckenzie** [Azure/azure-cli#10629]
When creating a managed instance for use as a secondary within a failover group, it must share the DNS Zone Partner of the primary managed instance. There does not appear to be a way to specify the DNS Zone Partner (or the name of the primary managed instance) using `az sql mi`.

[Microsoft documentation on failover groups](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-auto-failover-group) (under **Create the secondary instance in the same DNS zone as the primary instance**)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06c9a36f-c18a-748b-559a-927c7f4988fb
* Version Independent ID: 7af90d97-d085-b8fa-4e02-d3e601a1846d
* Content: [az sql mi](https://docs.microsoft.com/en-us/cli/azure/sql/mi?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ziwa-msft** [comment]
Yes the support for creating managed instance with the correct Dns Zone is still pending. I apologize for the gap in the experience. Please use Azure Portal or Azure PowerShell to create the managed instances needed as a temporary workaround.

**Comment by archmangler** [comment]
@ziwa-msft  - that's not an acceptable solution. this means Azure's SQL MI is essentially un-automatable. Is there a scripted option, perhaps in powershell for this?

**Comment by archmangler** [comment]
Hi, has this been fixed yet? We rely on az cli for our deployment automation, and need this feature as we do not support powershell.

**Comment by archmangler** [comment]
@ziwa-msft - even with powershell there is no documented way to set up failover instances specifically with the DNSZonePartner parameter. So it appears SQL MI in HA is essentially un-automatable at present, either with powershell or az cli. The portal is not an option for enterprise deployments.

Is there a workaround?

**Comment by ziwa-msft** [comment]
Hi. Sorry for the late reply on this. there is an option to user Powershell which is detailed here: 
https://docs.microsoft.com/en-us/powershell/module/az.sql/new-azsqlinstance?view=azps-3.1.0

Basically you would need to create the secondary managed instance with a DnsZonePartner parameter and the rest should be just setting up FoG on them.

Cli param is not available yet but it should be soon. 

Thanks,
Mike

**Comment by jeroenterheerdt** [comment]
@archmangler please reply by 1/10 otherwise we will proceed to close this issue.
