### ISSUE TITLE
Azure Files AD DS Authentication

### ISSUE THREAD

**Issue by yuemlu** [Azure/azure-cli#10633]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Azure Storage

**Description of Feature or Work Requested**
We would like to release a Preview Module for Azure Files native AD Authentication in Mid Oct. Zhenfeng from SRP team is working on the SRP changes and the changes including swaggers will be available by 9/13. We would need your help to assess the dev cost and priority for the next CLI release. I have also attached the discussion thread we had with Wei on PSH. Unlike PSH, we are only extending the existing commands without introducing new ones.
 
1.	Extend az storage account keys list and az storage account keys renew to support two new Kerb keys
2.	Support new flag --enable-files-adds for az storage account create and update
You can find the feature enablement matrix similar as what is proposed for PSH

Initial DirectoryServiceOptions of Account | None | AADDS | AD
-- | -- | -- | --
Set   Account with “–EnableAzureActiveDirectoryDomainServicesForFile $false”, | None | None | AD
Set   Account with “–EnableAzureActiveDirectoryDomainServicesForFile $true”, | AADDS | AADDS | Blocked   with error msg above
Set   Account with “–EnableActiveDirectoryDomainServicesForFile $false”, | None | AADDS | None
Set   Account with “–EnableActiveDirectoryDomainServicesForFile $true”, | AD | Blocked   with error msg above | AD

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

**Target Date**
Before Ignite Nov 4th

**Comment by Juliehzl** [comment]
Thanks @yuemlu. We will plan it in this sprint.

**Comment by Juliehzl** [comment]
@yuemlu do you have any update now?
