### ISSUE TITLE
Missing support for subnet-id when creating a volume with netappfiles (reopening again)

### ISSUE THREAD

**Issue by edwardsp** [Azure/azure-cli#10636]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.72

**Describe the bug**
Previously a subnet id could be used when creating volumes when it was an extension.  Since being moved to the main cli this is not available.  The impact here is that I cannot create a volume in a separate resource group to where the vnet is located.

With the previous bug report it has been changed such that a subnet_id can be passed as the subnet parameter but the code only extracts the subnet name (and ignores the resource group).  This means it is not possible to use a vnet in a different resource group.

**To Reproduce**
az netappfiles volume create --resource-group <volume-resource-group> --vnet <vname-name> --subnet <subnet-id> ...

This will fail unless the vnet is in the same resource group as the netappfiles.  

**Expected behavior**
If a different resource group is specified in the subnet it should be used.

**Environment summary**
Linux latest azure-cli.

**Additional context**
It works in the portal.

This is where the subnet is now parsed but the resource group is ignored:

https://github.com/Azure/azure-cli/blob/20a25fff6775e5dbc8d7ecae1c037426a25a927a/src/azure-cli/azure/cli/command_modules/netappfiles/custom.py#L93

**Comment by RakeshMohanMSFT** [comment]
This issue is resolved
