### ISSUE TITLE
Unclear what this error means? 

### ISSUE THREAD

**Issue by rodbutters** [Azure/azure-cli#10639]
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
lib/python3.7/json/__init__.py, ln 348, in loads
    return _default_decoder.decode(s)
lib/python3.7/json/decoder.py, ln 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.7/json/decoder.py, ln 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- was running a deployment for a large function app - zip file is 227705146 bytes. 
- `az functionapp deployment source config-zip --name {} --resource-group {} --src {}`

## Expected Behavior

Not clear what this error message means - is this for either the host.json or function.json or a response from the server? 

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.72 *

```

**Comment by SaurabhSharma-MSFT** [comment]
@rodbutters I believe this issue has been fixed and can be closed. Please let us know.
