### ISSUE TITLE
Ability to set per-document TTL via azure cli

### ISSUE THREAD

**Issue by ragoragino** [Azure/azure-cli#10635]
**Is your feature request related to a problem? Please describe.**
Currently, as far as I have been able to look up, one can enable per-document TTL on CosmosDB collections only via Azure Portal. It would be great to be able to enable this feature via az cli.

**Describe the solution you'd like**
Adding another option to create and update commands for az CosmosDB:
az cosmosdb collection create/update ... --enable-per-doc-ttl

**Comment by shurd** [comment]
Hi @ragoragino thank you for this question. The CLI does support TTL for APIs that have TTL. You can see some examples here:
[SQL](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/sql/container?view=azure-cli-latest#az-cosmosdb-sql-container-update)
[Cassandra](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/cassandra/table/throughput?view=azure-cli-latest#az-cosmosdb-cassandra-table-throughput-update)
[Gremlin](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/gremlin/graph?view=azure-cli-latest#az-cosmosdb-gremlin-graph-update)

These new API-specific commands were added in version 2.0.71

**Comment by ragoragino** [comment]
Hi @shurd,

thanks for your reply. However, I believe the links you sent me provide a way to enable just the default TTL. But what I meant was to enable per-document TTL which is currently Azure preview feature. I cannot find a way to enable that via az cli.

Nonetheless, I have found that terraform provides this feature via capabilities option (setting mongoEnableDocLevelTTL): https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_account.html. This solves our issue.
