### ISSUE TITLE
az vm disk attach-new --caching should be --host-caching

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#1063]
The portal and V1 CLI call the caching parameter --host-caching, but the V2 CLI uses "caching" which is inconsistent and probably less clear.

**Comment by yugangw-msft** [comment]
`caching` is used by SDK, but I agree, we should use `host-caching` regardless of the implementation details.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
