### ISSUE TITLE
Add support for large file shares (LFS) proprety for storage account

### ISSUE THREAD

**Issue by gunjanj** [Azure/azure-cli#10638]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Storage
Contacts: Zhenfeng Chen <Zhenfeng.Chen@microsoft.com> (SRP),
LFS Dev: Sehgal Vipin <Vipin.Sehgal@microsoft.com> 
PM owner: Gunjanj

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
(more details shared in mail with Zunli)
Add new property for Large File Shares on storage account API (Create, Get/Set) for Azure Files LFS GA. (Planned for Oct 17)

References:
https://microsoft.sharepoint.com/teams/AzureStorage/_layouts/OneNote.aspx?id=%2Fteams%2FAzureStorage%2FShared%20Documents%2FXFiles%2FXFile%20Development&wd=target%28Feature%20Areas%2FLFS.one%7CE1DBC0CB-1499-459E-AC37-F61FBDFFD8C8%2FAccount%20Level%20Sign-up%20For%20LFS%7CF04E07DE-8815-4AFA-BFE0-5086C8B0188C%2F%29 – Spec

https://aka.ms/largefilesharesdocs - external doc

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
Swagger PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/776 
Owner (Chris Ashton SRP Team - Zhenfeng Chen <Zhenfeng.Chen@microsoft.com>

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
Oct 17, 2019 GA

**Comment by Juliehzl** [comment]
We have received your feature request and we plan to do it in this sprint. If there is any question, I will reach out you. Thanks 😊

**Comment by Juliehzl** [comment]
@gunjanj If the swagger file is in public repo, please help update your template and let me know.

**Comment by yonzhan** [comment]
@gunjanj  any update for swagger spec and python SDK PRs ?
