### ISSUE TITLE
Tabulate fails to install on Windows

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#10644]
Tabulate library issue. Tracking https://bitbucket.org/astanin/python-tabulate/issues/182/tabulate-fails-to-install-on-windows

PR https://github.com/Azure/azure-cli/pull/10634 created to lock version.

**Comment by fengzhou-msft** [comment]
tabulate released [0.8.5](https://pypi.org/project/tabulate/0.8.5/#history) and fixed the issue. tabulate is imported by [knack](https://github.com/microsoft/knack), will set tabulate version there.

**Comment by fengzhou-msft** [comment]
As per team discussion, it is not a good practice to lock versions with upper bound in setup file, since other software may depend on a higher version of the same package. We will take no further actions with this issue. This issue is unblocked with the release of tablulate 0.8.5,

**Comment by jiasli** [comment]
Fixed in https://github.com/astanin/python-tabulate/issues/4
