### ISSUE TITLE
Unknown or Invalid instance during login with custom cloud

### ISSUE THREAD

**Issue by tmacro** [Azure/azure-cli#10643]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Azure-adal (on which azure-cli depends, and uses for auth) defines a static list of authority servers [here](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/094812ca3b7651d87d637e4719a3a5f546d21ec0/adal/constants.py#L212). It then uses this list [here](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/094812ca3b7651d87d637e4719a3a5f546d21ec0/adal/authority.py#L99) to limit the authority servers used for discovery. Why is this a problem? If I register a custom cloud using `az cloud register ...` with a custom authority server, `az login` fails with the error
```
Instance Discovery request returned http error: 400 and server response: {
  "error": "invalid_instance",
  "error_description": "AADSTS50049: Unknown or invalid instance.\r\nTrace ID: d4f1f445-d340-4f65-a0ec-f7e384560000\r\nCorrelation ID: 1e59253d-4595-4082-9daf-6e85c3b73313\r\nTimestamp: 2019-09-23 21:37:56Z",
  "error_codes": [
    50049
  ],
  "timestamp": "2019-09-23 21:37:56Z",
  "trace_id": "d4f1f445-d340-4f65-a0ec-f7e384560000",
  "correlation_id": "1e59253d-4595-4082-9daf-6e85c3b73313",
  "error_uri": "https://login.windows.net/error?code=50049"
}
```
This occurs after the oauth flow has been completed and the access tokens returned, and seems to be related to account (capability?) discovery
I've opened a similar issue against AzureAD/azure-activedirectory-library-for-python, [here](https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/213) and was told that python-adal supports custom authority servers, and I should try opening one here.

**To Reproduce**
Register a custom cloud using
```shell
az cloud register \
    -n customCloud \
    --endpoint-resource-manager "https://example.com" \
    --suffix-storage-endpoint "blob.example.com" \
    --endpoint-active-directory "https://example.com"
```
Attempt to login
```shell
az login
```
**Expected behavior**
login to complete successfully

**Environment summary**
```
Linux-5.2.13-arch1-1-ARCH-x86_64-with-arch
Python 3.7.4
Shell: fish

azure-cli 2.0.70 *

Extensions:
storage-preview 0.2.8

```

**Additional context**

**Comment by jiasli** [comment]
`AuthenticationContext` is created at https://github.com/Azure/azure-cli/blob/1beb6352ece2d06187bbccd66f1638f45b0340f7/src/azure-cli-core/azure/cli/core/_profile.py#L97

What is URL for `--endpoint-active-directory` you have registered? It will be examined at https://github.com/Azure/azure-cli/blob/1beb6352ece2d06187bbccd66f1638f45b0340f7/src/azure-cli-core/azure/cli/core/_profile.py#L84 to decide the value of `is_adfs`.

**Comment by jiasli** [comment]
`AuthenticationContext` is created at https://github.com/Azure/azure-cli/blob/1beb6352ece2d06187bbccd66f1638f45b0340f7/src/azure-cli-core/azure/cli/core/_profile.py#L97

What is the URL for `--endpoint-active-directory` you have registered? It will be examined at https://github.com/Azure/azure-cli/blob/1beb6352ece2d06187bbccd66f1638f45b0340f7/src/azure-cli-core/azure/cli/core/_profile.py#L84 to decide the value of `is_adfs`.

**Comment by tmacro** [comment]
something in the format of `https://manage.blob.local`

**Comment by tmacro** [comment]
@jiasli Any update on this?

**Comment by jiasli** [comment]
Yes. Currently the URL needs to end with `/adfs` to disable verification. Is there any factor that is preventing using this URL?

**Comment by tmacro** [comment]
Works perfectly, Thanks!
