### ISSUE TITLE
Not able to connect to adls gen2 account with cli dls command

### ISSUE THREAD

**Issue by bgall-teainc** [Azure/azure-cli#10640]
## Describe the bug

**Command Name**
`az dls fs list`

**Errors:**
```
HTTP error: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='sateaca.azuredatalakestore.net', port=443): Max retries exceeded with url: /webhdfs/v1/client/raw?OP=LISTSTATUS&api-version=2018-09-01&listSize=4000 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5ae9465710>: Failed to establish a new connection: [Errno -2] Name or service not known',))",),)
Traceback (most recent call last):
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az dls fs list -n {} --path {}`

## Environment Summary
```
Linux-4.15.0-1059-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.74

```

**Comment by sumantmehtams** [comment]
The az dls fs commands are for ADLS Gen1; they will not work for ADLS Gen2. Use appropriate commands here:
https://docs.microsoft.com/en-us/cli/azure/storage?view=azure-cli-latest

Will close this. Reopen if needed.

Thanks,
Sumant
