### ISSUE TITLE
Fishshell autocompletion

### ISSUE THREAD

**Issue by marchenm** [Azure/azure-cli#10642]
Is it possible to add auto-completion for fishshell?

**Comment by jiasli** [comment]
I tried to enable **argcomplete** in **fish** following https://pypi.org/project/argcomplete/, but the actual functionality is half-broken, as CLI is trying to execute the command first, and results in an error. I will look into it.

**Comment by jemag** [comment]
@jiasli support for fish was apparently implemented in argcomplete v1.10.0, but I am not sure how extensively it has been tested. If there are still problems with it, it might be good to re-open an issue on the subject on their github.

**Comment by jiasli** [comment]
@jemag, I understand your concern, but currently we are working on other high priority tasks and fish is not officially supported by Azure CLI. Please consider using Bash instead. Thanks for your understanding.

**Comment by kfkonrad** [comment]
Please consider reopening the issue.

**Comment by DimanNe** [comment]
@jiasli Any updates on the issue? Pretty much everything (apart from azure) has fish completion:
* `kubectl completion fish`
* `helm completion fish`
* `kind completion fish`
* ...

**Comment by kfkonrad** [comment]
`az` actually supported fish completion since 2019, but it's never been documented. `az` uses `argcomplete` internally which in turn has supported fish completion since 2019.  `az` simply inherited that feature. See https://github.com/kislyuk/argcomplete/pull/260 for details

I've implemented the completion for fish in https://github.com/fish-shell/fish-shell/pull/8141. It's available in fish 3.4.0 or greater

**Comment by bebound** [comment]
Creating `~/.config/fish/completions/az.fish` should work.
``` fish
function __fish_az_complete  
    set -x _ARGCOMPLETE 1  
    set -x _ARGCOMPLETE_DFS \t  
    set -x _ARGCOMPLETE_IFS \n  
    set -x _ARGCOMPLETE_SUPPRESS_SPACE 1  
    set -x _ARGCOMPLETE_SHELL fish  
    set -x COMP_LINE (commandline -p)  
    set -x COMP_POINT (string length (commandline -cp))  
    set -x COMP_TYPE  
    if set -q _ARC_DEBUG  
        az 8>&1 9>&2 1>&9 2>&1  
    else  
        az 8>&1 9>&2 1>/dev/null 2>&1  
    end  
end  
complete --command az -f -a '(__fish_az_complete)'
```

**Comment by kfkonrad** [comment]
This is functionally identical to my implementation in upstream fish: https://github.com/fish-shell/fish-shell/blob/master/share/completions/az.fish and https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_argcomplete_complete.fish (also see my previous comment)

Just update your fish and you're good to go, no need to reimplement the wheel

**Comment by bebound** [comment]
These scripts should be identical as I use `register-python-argcomplete --shell fish az` to generate it.

I post it here to provide a solution for older version fish. If there is no further question, this issue could be closed later.

**Comment by danmacode** [comment]
@bebound can you please help? When using `~/.config/fish/completions/az.fish` the completions showed a help comment for each option, whereas the current fish v4.0.2 autocompletes `az` automatically but shows no help comment.

Can I restore that functionality in upstream fish without manually creating the completion file?

**Comment by bebound** [comment]
Hi @danmacode, you don't need to create `~/.config/fish/completions/az.fish` in latest Fish, as it includes built-in az completion.

**Comment by danmacode** [comment]
@bebound thanks, but can I restore the help comment for each completion? I preferred that
