### ISSUE TITLE
az cosmosdb update Error: cannot import name SqlDatabaseResource

### ISSUE THREAD

**Issue by crucibles** [Azure/azure-cli#10650]
%23%23%23 **This is autogenerated. Please review and update as needed.**

%23%23 Describe the bug

**Command Name**
`az cosmosdb update`

**Errors:**
```
cannot import name SqlDatabaseResource
Traceback (most recent call last):
python2.7/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 523, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 291, in load_arguments
    self.command_table[command].load_arguments()  %23 this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
azure/cli/core/__init__.py, ln 528, in get_op_handler
    op = import_module(mod_to_import)
lib/python2.7/importlib/__init__.py, ln 37, in import_module
    __import__(name)
cli/command_modules/cosmosdb/custom.py, ln 12, in <module>
    from azure.mgmt.cosmosdb.models import (
ImportError: cannot import name SqlDatabaseResource
```

%23%23 To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cosmosdb update --name {} --resource-group {} --ip-range-filter {}`

%23%23 Expected Behavior

%23%23 Environment Summary
```
Linux-4.4.0-96-generic-x86_64-with-Ubuntu-16.04-xenial
Python 2.7.12
Shell: bash

azure-cli 2.0.74

```
%23%23 Additional Context

**Comment by shurd** [comment]
Hi @crucibles thank you for opening this issue. We are working on trying to replicate this behavior. Do you know if a previous version of the CLI worked as expected on your machine?

**Comment by shurd** [comment]
Hi @crucibles, can you please retry the command and also specify `--debug` as a parameter? This will show more details about what is happening. Based on the error message, it looks like "azure-mgmt-cosmosdb" is not properly loaded.

**Comment by shurd** [comment]
Hi @crucibles, I am going to close this issue for now. If you are still experiencing this problem, you can open another issue and provide the debug output from the terminal.
