### ISSUE TITLE
az role definition create --role-definition @params.json crashes

### ISSUE THREAD

**Issue by mangobanaani** [Azure/azure-cli#10657]
## Describe the bug

**Command Name**
`az role definition create`

**Errors:**
```
'9a42ee42-53d8-4dc1-9d6b-796a2f2c667d'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.7/site-packages/msrest/service_client.py, ln 108, in _request
    request = ClientRequest(method, self.format_url(url))
python3.7/site-packages/msrest/service_client.py, ln 151, in format_url
    url = url.format(**kwargs)
KeyError: '9a42ee42-53d8-4dc1-9d6b-796a2f2c667d'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role definition create --role-definition {}`

## Expected Behavior

role created or some error from processing the json parameters

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.72 *

Extensions:
aks-preview 0.4.6

```

**Comment by yonzhan** [comment]
@jiasli  please take a look and comment.

**Comment by jiasli** [comment]
Looks like the issue is caused by malformed JSON arg. Please follow the sample https://docs.microsoft.com/en-us/cli/azure/role/definition?view=azure-cli-latest#az-role-definition-create

If the issue persists, please share the full command.

**Comment by yonzhan** [comment]
solution provided
