### ISSUE TITLE
Set python3 as default dependency on rpm package

### ISSUE THREAD

**Issue by gfoligna** [Azure/azure-cli#10659]
Based on python2.7's deprecation soon (Jan 2020) I would like to have the rpm package defaulting to python3 as dependency and as it is recommended in the manual linux install.

Thanks.

**Comment by yonzhan** [comment]
@fengzhou-msft  please take a look and comment.

**Comment by fengzhou-msft** [comment]
@gfoligna Thanks for the suggestion. We will evaulate this change.

**Comment by fengzhou-msft** [comment]
azure-cli 2.0.77 rpm uses python3 as dependency now.
