### ISSUE TITLE
 No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'

### ISSUE THREAD

**Issue by dscpl** [Azure/azure-cli#10663]
## Describe the bug

**Command Name**
`az interactive`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.74

Extensions:
interactive 0.4.3

```
## Additional Context

az>> Exception in thread Thread-1:                                                                                       Traceback (most recent call last):                                                                                         File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner                    self.run()                                                                                                             File "C:\Users\user\.azure\cliextensions\interactive\azext_interactive\azclishell\threads.py", line 21, in run          FreshTable(self.shell).dump_command_table(self.shell)                                                                  File "C:\Users\user\.azure\cliextensions\interactive\azext_interactive\azclishell\_dump_commands.py", line 88, in d ump_command_table                                                                                                            main_loader.load_arguments(None)-----------------------------------------------------------------------------------    File "C:\Users\user\.azure\cliextensions\interactive\azext_interactive\azclishell\_dump_commands.py", line 49, in l oad_arguments----------------------------------------------------------------------------------------------------------      command.load_arguments()                                                                                               File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\commands\__init__.py", l ine 291, in load_arguments  : use commands outside the application                                                         File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\commands.py", line 97, in load_arguments     File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\__init__.py", line 488,  in default_arguments_loader : do a step by step tutorial of example                                                        File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli-core\azure\cli\core\__init__.py", line 528,  in get_op_handler           : set a scope, and scopes can be chained with spaces                                           File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\importlib\__init__.py", line 126, in import_module              return _bootstrap._gcd_import(name[level:], package, level)                                                            File "<frozen importlib._bootstrap>", line 994, in _gcd_import                                Hit [enter] to refresh     File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\azure-cli\azure\cli\command_modules\apim\custom.py", l ine 9, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'

**Comment by yonzhan** [comment]
@jiasli  please take a look and comment.

**Comment by jiasli** [comment]
This issue is already addressed. If it still happens, please let us know.

**Comment by tarunkdawar** [comment]
i am getting the same error

**Comment by jiasli** [comment]
Hi @tarunkdawar, may I know which version of Azure CLI you are using? You may run `az --version` to check that. Please update to the latest version and see if the issue is addressed.

**Comment by tarunkdawar** [comment]
working now , i was able to update by downloading the msi installer. for some reason , updating via powershell using the command on Microsoft Docs did not actually install the latest version. 

Its working now afer updating to 2.0.81

**Comment by jiasli** [comment]
To [install via PowerShell](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#install-or-update), you need to run the command as administrator. Since `/quiet` is specified, it will fail without warning if not run as administrator.
