### ISSUE TITLE
az storage container list --help isn't helpful.

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#1066]
It looks like we're presenting the auto-generated help from the SDK for this command, as it isn't relevant in the context of the CLI:
`az storage container list: Returns a generator to list the containers under the specified
    account.
        The generator will lazily follow the continuation tokens returned by
        the service and stop when all containers have been returned or num_results is reached.
`

`If num_results is specified and the account has more than that number of
        containers, the generator will have a populated next_marker field once it
        finishes. This marker can be used to create a new generator if more
        results are desired.
`

**Comment by mayurid** [comment]
@tjprescott : do we need to open and issue for the Storage sdk for this?

**Comment by tjprescott** [comment]
@mayurid that is an option. The easiest thing to do would be to override the help text, since arguably the existing text is helpful(ish) to an SDK user.

**Comment by mayurid** [comment]
Lets overwrite it in that case
