### ISSUE TITLE
az storage account network-rule add is not idempotent

### ISSUE THREAD

**Issue by jurjenoskam** [Azure/azure-cli#10673]
(azure-cli 2.0.74, I did not try other versions)

`az storage account network-rule add` is not idempotent. The first time I run it it works, subsequent invocations result in:

`Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id(unique). For more information, see - https://aka.ms/storagenetworkruleset`

In the spirit of https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#standard-command-types I believe the subsequent operations should not result in an error, but be a no-op instead (making this command idempotent).

**Comment by Juliehzl** [comment]
Hi @jurjenoskam , thanks for your feedback. We are looking into it.

**Comment by toddplu** [comment]
Any updates?

**Comment by GeeWee** [comment]
I have also had to create custom workarounds for this error.

**Comment by yonzhan** [comment]
add to S166.

**Comment by qianwens** [comment]
Hi @jurjenoskam , this error is thrown from the service side. "add" a network-rule in a storage account is a patch operation because it is a partial update of a resource which is not guaranteed to be idempotent -> https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design. 
You can run az storage account network-rule list first to check if the networkrule exists first.

**Comment by jurjenoskam** [comment]
Hi @qianwens , thank you for your response. I understand the error is thrown from the service side, and I have been adding code to my scripts to circumvent that this operation is not idempotent. The issue is that I have to do this *each time* in *every script* where this operation is done, and this applies to everybody else writing Azure CLI scripts as well. In other words, lots and *lots* of duplicated work and code, while if this were done once (in Azure CLI itself) it would making writing scripts much simpler and make those script more robust.

Surely Azure CLI is not meant to be a direct passthrough of service API behavior? There are already many places where Azure CLI abstracts away service API behavior, from implementing retry logic when a service API call returns an error (e.g. many App Service commands) to building entire ARM templates and deploying them (VM commands). 

It would really add value to Azure CLI if it would make its CLI commands idempotent, irrespective of the behavior of the underlying API call; so I hope you'll consider adding this logic in Azure CLI.

**Comment by qianwens** [comment]
@jurjenoskam , thanks for your feedback. This is a bug in Azure CLI and we will fix it.

**Comment by yonzhan** [comment]
PR merged and will be released in this Sprint.
