### ISSUE TITLE
azure cli 2.0.74 create nsg rule fails when attempting to use an ASG that is not in the same resource group

### ISSUE THREAD

**Issue by Fastdruid** [Azure/azure-cli#10672]
Creating an NSG rule that uses a ASG that resides in a different resource group fails with the error:

Resource /subscriptions/_subscription-id_/ResourceGroups/_NSG-Resource-Group_/providers/Microsoft.Network/applicationSecurityGroups/_ASG-Name_ not found.

This is possible to perform from the portal. 

Actions to reproduce:
1) Create two resource groups
2) First resource group create an ASG
3) Second resource group create an NSG
4) Create a rule in the NSG attempting to use the ASG from the first resource group.

Create fails. 

Workround
1) Create ASG in same Resource Group as NSG
2) Create NSG rule
3) Move ASG to planned Resource Group

Example code to test **FAILURE**.
```
az group create --name ASG-RSG --location westeurope  
az group create --name NSG-RSG --location westeurope 
az network asg create --name ASG-EXAMPLE --location westeurope --resource-group ASG-RSG
az network nsg create --name NSG-EXAMPLE --location westeurope --resource-group NSG-RSG
az network nsg rule create --resource-group NSG-RSG --nsg-name NSG-EXAMPLE --name ASG-RULE --priority 100 --source-asgs ASG-EXAMPLE
```

Example code to test **SUCCESS** (ASG in same resource group as NSG):
```
az group create --name ASG-RSG --location westeurope  
az group create --name NSG-RSG --location westeurope
az network asg create --name ASG-EXAMPLE --location westeurope --resource-group NSG-RSG
az network nsg create --name NSG-EXAMPLE --location westeurope --resource-group NSG-RSG
az network nsg rule create --resource-group NSG-RSG --nsg-name NSG-EXAMPLE --name ASG-RULE --priority 100 --source-asgs ASG-EXAMPLE
```

**Comment by yonzhan** [comment]
@MyronFanQiu please take a look and comment.

**Comment by MyronFanQiu** [comment]
@Fastdruid Hello. If you want to use an ASG that is not in the same resource group. Please provide the resource ID for `--source-asgs` and have a try again. I think it will work.

**Comment by MyronFanQiu** [comment]
like `--source-asgs ASG-ID`

**Comment by MyronFanQiu** [comment]
@Fastdruid Hello. Could we close this issue? Did you meet more questions?

**Comment by MyronFanQiu** [comment]
@Fastdruid Do not hesitate to re-open this issue if you have any question.
