### ISSUE TITLE
--handle-extended-json-format missing from subscription level az deployment create command

### ISSUE THREAD

**Issue by alex-frankel** [Azure/azure-cli#10674]
**Describe the bug**
As of .74, the group deployment create command has the flag for --handle-extended-json-format, but it is missing from az deployment create. We will need it there as well.

As a side-note, can we have a short version of the flag? Maybe -j?

**Comment by Juliehzl** [comment]
Hi @alex-frankel , thanks for your reaching out. I will add the --handle-extended-json-format parameter for `az deployment create` command and give it a short version for both two commands soon.
