### ISSUE TITLE
Can't use a list of arguments/values stored in a variable for az commands

### ISSUE THREAD

**Issue by nofunatall** [Azure/azure-cli#10688]
## Describe the bug

I can't seem to get az storage commands (possibly might effect all commands haven't tested) to work using a list of arguments stored in a variable.

**Command Name**
`az storage blob list`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
1) Set variables containing account details and such
export KEY='somestoragekey'
export ACCOUNT='somestorageaccount'
export CONTAINER='test'
export PREFIX='files'
export BATCH_SIZE='10'

2) Combine them all into a single variable along with the az storage arguments
export AZURE_ARGS="--prefix \"$PREFIX\" \
                   --num-results $BATCH_SIZE \
                   --account-name \"$ACCOUNT\" \
                   --account-key \"$KEY\" \
                   --container-name \"$CONTAINER\" \
                   --output tsv \
                   --query \"[][name]\""

3) Check the variable matches something you would manually type in
user@ubuntu-vm:~$ echo $AZURE_ARGS
--prefix "files" --num-results 10 --account-name "somestorageaccount" --account-key "somestoragekey" --container-name "test" --output tsv --query "[][name]"

4) Run the storage command with the arguments from variable $AZURE_ARGS
user@ubuntu-vm:~$ az storage blob list $AZURE_ARGS
- `az storage blob list --prefix {} --num-results {} --account-name {} --account-key {} --container-name {} --output {} --query {}`

## Expected Behavior
Should be no different from manually running and getting something like:
user@ubuntu-vm:~$ az storage blob list --prefix "files" --num-results 10 --account-name "somestorageaccount" --account-key "somestoragekey" --container-name "test" --output tsv --query "[][name]"
Next Marker:
2!112!MDAwMDM4IWZpbGVzLzAzeGVtMzZkNHk2OTAweTUybjM3b2k1Y3d0OG4wbDNxITAwMDAyOCE5OTk5LTEyLTMxVDIzOjU5OjU5Ljk5OTk5OTlaIQ--
files/003kl4559qwbqkndwi9p0e9e7wscc7kk
files/00q5mgem83h9ndj4xw4hld40fy1mgcnz
files/01c0eyvzai3u31wfb8tu078t9vru7w4a
files/01nq9auv0aitqcki7fubfsn4gpk1kjb0
files/023uzdq6m8fs1q3vr8rlkffbe3ck8i0l
files/02llklabw9y6t61y40jjdvs7df4hej4j
files/02u1gilq2h31ddodds3518wzcpb5ktty
files/031e2bk3w3tq16e3b01x47s81eb1trsw
files/03ebujqj5u1pxq58purskavo6gllhdag
files/03eryt578h4uevz5su3uovdpdl0mw29a

## Environment Summary
```
Linux-5.0.0-1018-azure-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.74

Extensions:
interactive 0.4.3

```

**Comment by jiasli** [comment]
Tested on Ubuntu Bash and it works well:

```sh
export ACCOUNT='{}'
export KEY='{}'
export CONTAINER='{}'
export PREFIX='{}'
export BATCH_SIZE='10'

export AZURE_ARGS="--prefix "$PREFIX"
--num-results $BATCH_SIZE
--account-name "$ACCOUNT"
--account-key "$KEY"
--container-name "$CONTAINER"
--output tsv
--query "[].name""

echo $AZURE_ARGS

az storage blob list $AZURE_ARGS [--debug]
```

(To get a list of blob names, use `--query [].name`.)

You may append `--debug` to `az` to check the args received. In this case, it is correct:

> Command arguments: ['storage', 'blob', 'list', '--prefix', '{}', '--num-results', '10', '--account-name', '{}', '--account-key', '{}', '--container-name', '{}', '--output', 'tsv', '--query', '[].name', '--debug']

If there is still problem, please kindly share the error message. Thanks.

**Comment by nofunatall** [comment]
I had \ for line breaks in the arguments which was breaking it.
Close this thread then.

**Comment by jiasli** [comment]
Thanks for letting us know. Actually `\` shouldn't break the arg list. 
```
$ export AZURE_ARGS="--prefix "$PREFIX" \
> --num-results $BATCH_SIZE             \
> --account-name "$ACCOUNT"             \
> --account-key "$KEY"                  \
> --container-name "$CONTAINER"         \
> --output tsv                          \
> --query "[].name""

$ echo $AZURE_ARGS
--prefix 4 --num-results 10 --account-name {} --account-key {} --container-name {} --output tsv --query [].name
```

**Comment by jiasli** [comment]
Thanks for letting us know. Actually `\` shouldn't break the arg list. 

```sh
$ export AZURE_ARGS="--account-name $ACCOUNT \
--account-key $KEY                           \
--container-name $CONTAINER                  \
--prefix $PREFIX                             \
--num-results $BATCH_SIZE                    \
--output tsv                                 \
--query [].name"

$ echo $AZURE_ARGS
--prefix 4 --num-results 10 --account-name {} --account-key {} --container-name {} --output tsv --query [].name
```

**Comment by jiasli** [comment]
Thanks for letting us know. Actually `\` shouldn't break the arg list. Make sure there is no space following `\`.

```sh
$ export AZURE_ARGS="--account-name $ACCOUNT \
--account-key $KEY                           \
--container-name $CONTAINER                  \
--prefix $PREFIX                             \
--num-results $BATCH_SIZE                    \
--output tsv                                 \
--query [].name"

$ echo $AZURE_ARGS
--prefix 4 --num-results 10 --account-name {} --account-key {} --container-name {} --output tsv --query [].name
```

**Comment by nofunatall** [comment]
Put them within the quotes and it breaks.
________________________________
