### ISSUE TITLE
az storage account create succeed but returns an invalid json

### ISSUE THREAD

**Issue by tamirkamara** [Azure/azure-cli#10687]
**Describe the bug**
A [recent change](https://github.com/Azure/azure-cli/blob/93bbc71faccbef32fe3df3fc5cc953fa1277208d/src/azure-cli/azure/cli/command_modules/storage/operations/account.py#L24) in the storage account create command introduced a fixed warning about the default kind moving to StorageV2 in the near future. It is printed even when the output is requested in json which makes downstream apps or extensions (like image copy) fail in parsing. 
Since the message is fixed without any conditions there's no way to avoid the problem. 
I don't expect warnings to be printed when output is set to json, or, at the very least, this specific warning to only be printed when the user doesn't specify the kind and relies on the default.

**To Reproduce**
run this command:
az storage account create --name uksouth0fpcpuevwgzndpb4c --resource-group image-copy-rg --location uksouth --sku Standard_LRS **--output json**

**Expected behavior**
A valid json is printed on the screen

**Environment summary**
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.74

Extensions:
imagecopyextension 0.2.1

## Additional Context
At current state, this break the image-copy extension in all scenarios and impacts several customers already.

**Comment by jiasli** [comment]
All `logger` messages are written to std.err which will not be saved to files or variables.

To save to a variable (on Linux), `out=$(az storage account create --name {} --resource-group {} --location eastus2 --sku Standard_LRS --output json)`

To save to a file, `az storage account create --name {} --resource-group {} --location eastus2 --sku Standard_LRS --output json > output.json`

To disable the warning, append `2>NUL` in cmd, `2>$null` in PowerShell or `2>/dev/null` on Linux (2 stands for std.err).

If there is still problem, please kindly share the full script. Thanks.

**Comment by tamirkamara** [comment]
Hi,
Thank you @jiasli however I don't think your suggestion is practical in my scenario - I'm working from within python as a cli extension and calling other cli commands. This was the decision back when the extension was created...
You can view the section where this happens here: https://github.com/Azure/azure-cli-extensions/blob/master/src/image-copy/azext_imagecopy/cli_utils.py#L21

@tjprescott was in the loop then.

**Comment by yonzhan** [comment]
@jiasli put to next Sprint.

**Comment by Aanerud** [comment]
+1 This is urgent, as Azure is getting now two new local sites, and I can't migrate to the local sites, a s this does not work.

**Comment by jiasli** [comment]
Is it possible not to capture standard error? 
https://docs.python.org/3.8/library/subprocess.html#subprocess.check_output

This has actually been discussed before in https://github.com/Azure/azure-cli/issues/9891#issuecomment-539316006.

**Comment by yonzhan** [comment]
@Aanerud  any update for this issue?

**Comment by yonzhan** [comment]
@Aanerud any update ?

**Comment by Aanerud** [comment]
I used the workaround described in the a similar ticket. I have not updated Azure CLI after, as the workaround works.

**Comment by yonzhan** [comment]
@Aanerud  so can we close this issue ?

**Comment by Aanerud** [comment]
Is the bug fixed ? 

Andreas.

**Comment by jiasli** [comment]
According to the doc of [`subprocess.check_output`](https://docs.python.org/3.8/library/subprocess.html#subprocess.check_output), please use `stderr=None` to discard `stderr`.

**Comment by jiasli** [comment]
As an alternative, we have added option `--only-show-errors` in #12604 to disable warnings that are written to `stderr`. It will be included in [S167](https://github.com/Azure/azure-cli/milestone/84) release.
