### ISSUE TITLE
How to disassociate routetable from subnet ?

### ISSUE THREAD

**Issue by jjindrich** [Azure/azure-cli#10694]
Hi, how can I remove route table association from existing subnet ?
For association using this:
az network vnet subnet update -g $rg -n XXX --vnet-name YYY --route-table RTNAME
What to use to remove association ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 385e420c-4bd0-3ddd-d9cd-a9a411ec1f7b
* Version Independent ID: 65172372-f485-3d2b-64aa-57c38ac11538
* Content: [az network vnet subnet](https://docs.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#az-network-vnet-subnet-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by CharmanderJieniJieni** [comment]
+1

**Comment by CharmanderJieniJieni** [comment]
foud it, use --remove routeTable

**Comment by jjindrich** [comment]
@CharmanderJieniJieni thank you ! I would suggest to update documentation.

**Comment by MyronFanQiu** [comment]
@jjindrich Thanks. We will take a look and improve the doc.
