### ISSUE TITLE
Arguments start with "-" cause error

### ISSUE THREAD

**Issue by peizhou298** [Azure/azure-cli#10692]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
If your command input starts with "-", it would throw an error "Excepted one argument". 

**To Reproduce**
Type any command with a string argument, and give input starts with "-".  
eg. this is our cli extension:
![Capture](https://user-images.githubusercontent.com/53513383/65847151-f18f7b80-e372-11e9-8598-1e27f86c5afd.PNG)

**Comment by jiasli** [comment]
This is actually an issue with python's **argparse**. See https://stackoverflow.com/questions/16174992/cant-get-argparse-to-read-quoted-string-with-dashes-in-it

`--jvm-options="-XxMaxSize=1024"` should work.
