### ISSUE TITLE
Adding CORS to Storage account blob failed with invalid xml error

### ISSUE THREAD

**Issue by shiv-rajawat** [Azure/azure-cli#10693]
**Command Name**
`az storage cors add`

**Errors:**
```
The value for one of the XML nodes is not in the correct format. ErrorCode: InvalidXmlNodeValue
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidXmlNodeValue</Code><Message>The value for one of the XML nodes is not in the correct format.
RequestId:c5706352-701e-00a5-4339-751d66000000
Time:2019-09-27T13:40:39.7589152Z</Message><XmlNodeName>ExposedHeaders</XmlNodeName><XmlNodeValue>'*'</XmlNodeValue></Error>
Traceback (most recent call last):
pip-install-wl9gly17\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 566, in execute
...
RequestId:c5706352-701e-00a5-4339-751d66000000
Time:2019-09-27T13:40:39.7589152Z</Message><XmlNodeName>ExposedHeaders</XmlNodeName><XmlNodeValue>'*'</XmlNodeValue></Error>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
- `az storage cors add --account-name {} --origins {} --methods {} --allowed-headers {} --exposed-headers {} --max-age {} --services {}`

## Expected Behavior
A CORS entry should be added to specified resource.

## Actual Behavior
Command fails with invalid XML error, if run through CMD. But, succeeds if run through powershell.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.67 *

```

**Comment by Juliehzl** [comment]
Hi @shiv-rajawat, I can't see the command details you run. But typically, this is because cmd doesn't parse single quote `'*'`, can you try  bare * instead? e.g.  `--allowed-headers *`. If it still don't work, please show me your command details with `--debug` in your command.

**Comment by shiv-rajawat** [comment]
@Juliehzl Yes it was the single quotes. Closing the issue, and thanks a lot for the help.
