### ISSUE TITLE
Enable setting "auto pause" value when creating databases

### ISSUE THREAD

**Issue by mrwizard82d1** [Azure/azure-cli#10702]
**Is your feature request related to a problem? Please describe.**
I want to create a SQL database with a non-default auto-pause delay. I see no option to accomplish via azure cli (although it appears available via Powershell).

**Describe the solution you'd like**
I'd like to run the command
`az sql db create ... --auto-pause-delay-hours 2` to set the auto-pause delay to 2 hours

**Describe alternatives you've considered**
I can use Powershell; however, all my current scripts use Python with the azure-cli package. Using Powershell requires users to install yet another tool / module to create the database.

**Additional context**
I've found the azure CLI and the underlying Python code very useful in scripting deployments. Having to move to Powershell for this single piece is disappointing.

**Comment by jaredmoo** [comment]
Thank you for the feedback! Let me chat with the team and find out what our plans are.

**Comment by jaredmoo** [comment]
Looks like we plan to implement this in the next 1-2 months :)

**Comment by jeroenterheerdt** [comment]
since this was implemented, let's go ahead and close this @jaredmoo
