### ISSUE TITLE
AZ CLI support for Firewall Policy

### ISSUE THREAD

**Issue by maravmsft** [Azure/azure-cli#10703]
**Resource Provider**
What is the Azure resource provider your feature is part of?
NFVRP (Microsoft.Network)

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
Firewall manager is a new service we are launching which manages several Azure Firewalls in Hub. As part of this we have a new resource called FirewallPolicy which has the firewall rules config which will be applied to Firewall.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
06-01-2019

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-07-01/firewallPolicy.json

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

We are planning on making the announcement for this new resource and service at 2019 Ignite. Target date 11/4/2019

**Comment by MyronFanQiu** [comment]
@maravmsft We will plan for it. Thanks.

**Comment by yonzhan** [comment]
@MyronFanQiu  this is planned for Ignite release.

**Comment by MyronFanQiu** [comment]
This has been supported in new azure-firewall extension. Please check them.
