### ISSUE TITLE
Unclear how to start using (this) preview feature

### ISSUE THREAD

**Issue by michaelw85** [Azure/azure-cli#10708]
It took me quite some time to find a blog where it shown to use `az extension add --name azure-devops` to be able to start using the az pipelines command. It would be nice if there would be some explanation that this is part of the azure-devops extension and should be installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f0311f-8316-ea52-6171-9eb14b9f7bc7
* Version Independent ID: e79f2bc9-543d-9a14-a08c-911d037e108a
* Content: [az pipelines](https://docs.microsoft.com/en-us/cli/azure/pipelines?view=azure-cli-latest#code-try-1)
* Content Source: [latest/docs-ref-autogen/pipelines.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/pipelines.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by maggiepint** [comment]
Issue moved to [Azure/azure-cli-extensions #976](https://github.com/Azure/azure-cli-extensions/issues/976) via [**ZenHub**](https://www.zenhub.com/)

**Comment by maggiepint** [comment]
Hey - moved this over to the extensions repo. Happy to help you there.
