### ISSUE TITLE
Cannot create DataLake Gen2 container using AZ CLI yet

### ISSUE THREAD

**Issue by pangiole** [Azure/azure-cli#10700]
## Describe the bug

**Command Name**
`az storage container create`

**Errors:**
```
Blob API is not yet supported for hierarchical namespace accounts. ErrorCode: BlobApiNotYetSupportedForHierarchicalNamespaceAccounts
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobApiNotYetSupportedForHierarchicalNamespaceAccounts</Code><Message>Blob API is not yet supported for hierarchical namespace accounts.
RequestId:9e747912-c01e-00e3-5cb3-776430000000
Time:2019-09-30T17:25:00.0406002Z</Message></Error>
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
...
RequestId:9e747912-c01e-00e3-5cb3-776430000000
Time:2019-09-30T17:25:00.0406002Z</Message></Error>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container create --name {} --account-name {} --account-key {} --auth-mode {}`

## Environment Summary
```
Darwin-17.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.74

Extensions:
storage-preview 0.2.8

```

**Comment by Juliehzl** [comment]
Hi @angiolep, thanks for your reaching out. We already have planned for it with service team. We will do it as soon as possible.

**Comment by Riccardo-Fiorentino** [comment]
I have a similar issue when using ARM templates
{
    "error": {
        "code": "ContainerOperationFailure",
        "message": "Specified feature is not yet supported for hierarchical namespace accounts.\nRequestId:fcce3e69-301e-001e-5cef-b1cc8b000000\nTime:2020-11-03T14:43:26.0342864Z"
    }
}

To recreate just try create a container through an ARM template for a storage account that has Hierarchical enabled.

Any update as to when this will be enabled, I see it was reported over 12 months ago.

**Comment by Juliehzl** [comment]
@Riccardo-Fiorentino May I know your azure CLI version? It is supported in azure cli already. But for ARM template, add @zhoxing-ms  for help.
@angiolep CLI command is `az storage fs create` with azure cli >= 2.6.0.

**Comment by Riccardo-Fiorentino** [comment]
> @Riccardo-Fiorentino May I know your azure CLI version? It is supported in azure cli already. But for ARM template, add @zhoxing-ms for help.
> @angiolep CLI command is `az storage fs create` with azure cli >= 2.6.0.

Good day Juliezl, not using cli. Tried using an older API for the ARM, but not functioning.

**Comment by zhoxing-ms** [comment]
It is a known issue of service that some features are not supported in hierarchical namespace accounts.
As for Blob REST APIs, [doc link:](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-known-issues#blob-storage-apis)

>These Blob REST APIs aren't supported:
>- Put Blob (Page)
>- Put Page
>- Get Page Ranges
>- Incremental Copy Blob
>- Put Page from URL
>- Append Block from URL

**Comment by zhoxing-ms** [comment]
For the error of ARM template, it should also be caused by some features not supported by hierarchical namespace accounts.
This requires service team to confirm what and why it is not supported~
```
{
"error": {
"code": "ContainerOperationFailure",
"message": "Specified feature is not yet supported for hierarchical namespace accounts.\nRequestId:fcce3e69-301e-001e-5cef-b1cc8b000000\nTime:2020-11-03T14:43:26.0342864Z"
}
}
```
**RequestId: 9e747912-c01e-00e3-5cb3-776430000000**

**Comment by genegc** [comment]
I'm seeing the same issue when using "Deploy a custom template" in azure portal.
`    "status": "Failed",
    "error": {
        "code": "ContainerOperationFailure",
        "message": "Specified feature is not yet supported for hierarchical namespace accounts.\nRequestId:93d51b66-701e-0031-312b-b901ed000000\nTime:2020-11-12T19:36:20.2453796Z"
    }`

The template is here:
`{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "storageAccounts_steduanalytics2_name": {
            "defaultValue": "steduanalytics2",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.Storage/storageAccounts",
            "apiVersion": "2020-08-01-preview",
            "name": "[parameters('storageAccounts_steduanalytics2_name')]",
            "location": "eastus",
            "sku": {
                "name": "Standard_RAGRS",
                "tier": "Standard"
            },
            "kind": "StorageV2",
            "properties": {
                "minimumTlsVersion": "TLS1_2",
                "allowBlobPublicAccess": true,
                "isHnsEnabled": true,
                "networkAcls": {
                    "bypass": "AzureServices",
                    "virtualNetworkRules": [],
                    "ipRules": [],
                    "defaultAction": "Allow"
                },
                "supportsHttpsTrafficOnly": true,
                "encryption": {
                    "services": {
                        "file": {
                            "keyType": "Account",
                            "enabled": true
                        },
                        "blob": {
                            "keyType": "Account",
                            "enabled": true
                        }
                    },
                    "keySource": "Microsoft.Storage"
                },
                "accessTier": "Hot"
            }
        },
        {
            "type": "Microsoft.Storage/storageAccounts/blobServices",
            "apiVersion": "2020-08-01-preview",
            "name": "[concat(parameters('storageAccounts_steduanalytics2_name'), '/default')]",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_steduanalytics2_name'))]"
            ],
            "sku": {
                "name": "Standard_RAGRS",
                "tier": "Standard"
            },
            "properties": {
                "cors": {
                    "corsRules": []
                },
                "deleteRetentionPolicy": {
                    "enabled": false
                }
            }
        },
        {
            "type": "Microsoft.Storage/storageAccounts/fileServices",
            "apiVersion": "2020-08-01-preview",
            "name": "[concat(parameters('storageAccounts_steduanalytics2_name'), '/default')]",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_steduanalytics2_name'))]"
            ],
            "sku": {
                "name": "Standard_RAGRS",
                "tier": "Standard"
            },
            "properties": {
                "cors": {
                    "corsRules": []
                }
            }
        },
        {
            "type": "Microsoft.Storage/storageAccounts/queueServices",
            "apiVersion": "2020-08-01-preview",
            "name": "[concat(parameters('storageAccounts_steduanalytics2_name'), '/default')]",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_steduanalytics2_name'))]"
            ],
            "properties": {
                "cors": {
                    "corsRules": []
                }
            }
        },
        {
            "type": "Microsoft.Storage/storageAccounts/tableServices",
            "apiVersion": "2020-08-01-preview",
            "name": "[concat(parameters('storageAccounts_steduanalytics2_name'), '/default')]",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_steduanalytics2_name'))]"
            ],
            "properties": {
                "cors": {
                    "corsRules": []
                }
            }
        },
        {
            "type": "Microsoft.Storage/storageAccounts/blobServices/containers",
            "apiVersion": "2020-08-01-preview",
            "name": "[concat(parameters('storageAccounts_steduanalytics2_name'), '/default/stage1')]",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts/blobServices', parameters('storageAccounts_steduanalytics2_name'), 'default')]",
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_steduanalytics2_name'))]"
            ],
            "properties": {
                "defaultEncryptionScope": "$account-encryption-key",
                "denyEncryptionScopeOverride": false,
                "publicAccess": "None"
            }
        },
        {
            "type": "Microsoft.Storage/storageAccounts/blobServices/containers",
            "apiVersion": "2020-08-01-preview",
            "name": "[concat(parameters('storageAccounts_steduanalytics2_name'), '/default/stage2')]",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts/blobServices', parameters('storageAccounts_steduanalytics2_name'), 'default')]",
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_steduanalytics2_name'))]"
            ],
            "properties": {
                "defaultEncryptionScope": "$account-encryption-key",
                "denyEncryptionScopeOverride": false,
                "publicAccess": "None"
            }
        },
        {
            "type": "Microsoft.Storage/storageAccounts/blobServices/containers",
            "apiVersion": "2020-08-01-preview",
            "name": "[concat(parameters('storageAccounts_steduanalytics2_name'), '/default/stage3')]",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts/blobServices', parameters('storageAccounts_steduanalytics2_name'), 'default')]",
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_steduanalytics2_name'))]"
            ],
            "properties": {
                "defaultEncryptionScope": "$account-encryption-key",
                "denyEncryptionScopeOverride": false,
                "publicAccess": "None"
            }
        },
        {
            "type": "Microsoft.Storage/storageAccounts/blobServices/containers",
            "apiVersion": "2020-08-01-preview",
            "name": "[concat(parameters('storageAccounts_steduanalytics2_name'), '/default/synapse')]",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts/blobServices', parameters('storageAccounts_steduanalytics2_name'), 'default')]",
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_steduanalytics2_name'))]"
            ],
            "properties": {
                "defaultEncryptionScope": "$account-encryption-key",
                "denyEncryptionScopeOverride": false,
                "publicAccess": "None"
            }
        }
    ]
}`

**Comment by SvenAeltermanInfo** [comment]
@armleads-azure Is there an update? 

Essentially, when exporting an ARM template of an ADLS Gen 2 storage account, you can't re-apply as exported. Only by removing the `properties` property entirely does the template deploy.

It seems the error might be related to the `defaultEncryptionScope` property of `properties`. When it's the only property present, the error changes to this:

**Container encryption policy missing header: x-ms-default-encryption-scope and x-ms-deny-encryption-scope-override are required.**

When specifying both `defaultEncryptionScope` and `defaultEncryptionScopeOverride`, it still fails to deploy.

**Comment by mwc360** [comment]
I confirmed the same behavior as @SvenAeltermanInfo . The export template cannot be deployed as is, both `defaultEncryptionScope` and `defaultEncryptionScopeOverride` need to be removed from the container properties and then the template will deploy.

Very frustrating, it took me about 20 failed test deployments to figure this out. Bicep syntax highlighter even shows it's correct when it is not.

**Comment by bqstony** [comment]
I had to remove the following two properties in the properies element to work.

```json
"properties": {
   "defaultEncryptionScope": "$account-encryption-key",
   "denyEncryptionScopeOverride": false,
}
```

now i have access issues

**Comment by azurevivekgarg** [comment]
Hi Team,

Even after removing those 2 properties from the template.json, there is an undisclosed/unknown error I have encountered within the release pipeline.

![image](https://user-images.githubusercontent.com/100330815/166877225-b451003c-ac3f-467c-9db3-990a33476dd3.png)


Any help would be appriciated.

Thanks
Vivek Garg

**Comment by mkulisic** [comment]
I am encountering the exact same issues. Are there any updates on this?

**Comment by evelyn-ys** [comment]
Customer can create container(file system) in Data Lake Gen2 storage account using `az storage fs create` command

**Comment by zhoxing-ms** [comment]
The problem of ARM deployment still exists. The error information returned by the service is as follows:
```
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"error\": {\r\n    \"code\": \"ContainerOperationFailure\",\r\n    \"message\": \"Specified feature is not yet supported for hierarchical namespace accounts.\\nRequestId:9bd4b751-301e-0046-3900-8651e7000000\\nTime:2022-06-22T06:20:10.4386498Z\"\r\n  }\r\n}"}]}}
```

**'x-ms-correlation-request-id': '1aad2908-4970-4723-b1da-8d31eb0e35ef'**

@alex-frankel May I ask do you know who in the ARM service team can help us investigate this issue?

**Comment by TheoDoreW** [comment]
Hi, there 

I use azcopy command line copy file from Azure blob to Azure Datalake Gen2, also meet with the following error:

409 : 409 Specified feature is not yet supported for hierarchical namespace accounts.. When Creating blob. X-Ms-Request-Id: f9c8b27b-d01e-006c-3c8e-ac78b6000000

both with aad auth and sas key.

Anyone know how to solve this problem? Thanks in advance.

**Comment by zhoxing-ms** [comment]
> CLI command is az storage fs create with azure cli >= 2.6.0.
> Customer can create container(file system) in Data Lake Gen2 storage account using az storage fs create command

Since there is no problem with storage command `az storage fs create` at present, so the second issue should be a problem of ARM deployment. 
I guess this may be a problem when the ARM service invokes Storage RP. Could you please help have look at this problem? https://github.com/Azure/azure-cli/issues/10700#issuecomment-1162698536

**Comment by navba-MSFT** [comment]
Apologies for the late reply. [This ](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-feature-support-in-storage-accounts#standard-general-purpose-v2-accounts) article talks about the Blob Storage features and describes whether a feature is supported in a standard general-purpose v2 account when you enable a hierarchical namespace (HNS) (ADLS Gen 2).

You can upgrade Azure Blob Storage with Azure Data Lake Storage Gen2 capabilities by following this article. An upgrade is one-way. There's no way to revert your account once you've performed the upgrade. We recommend that you validate your upgrade in a nonproduction environment. More Info [here](https://learn.microsoft.com/en-us/azure/storage/blobs/upgrade-to-data-lake-storage-gen2-how-to?source=recommendations&tabs=azure-portal).

@TheoDoreW  Do you still need any assistance on [this ](https://github.com/Azure/azure-cli/issues/10700#issuecomment-1210310481)issue ?

@mkulisic Do you need any assistance on [this ](https://github.com/Azure/azure-cli/issues/10700#issuecomment-1162114467)issue ?
