### ISSUE TITLE
AKS VMSS - Cannot enable on existing cluster. 

### ISSUE THREAD

**Issue by poochwashere** [Azure/azure-cli#10717]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.74

**Describe the bug**
I am trying to enable `VMSS` on an existing `AKS` cluster. Per the latest AKS announcement this should be GA now. 

```
NOTE: Official support in the Azure CLI for AKS+VMSS will be released
on 2019-09-24 (version 2.0.74 https://github.com/Azure/azure-cli/milestone/73)
```

https://github.com/Azure/AKS/releases/tag/2019-09-09

**To Reproduce**

```
az aks nodepool update \
  --resource-group <my-rg> \
  --cluster-name <my-cluster> \
  --name dev-nodepool \
  --enable-cluster-autoscaler \
  --min-count 1 \
  --max-count 8

az aks: 'nodepool' is not in the 'az aks' command group. See 'az aks --help'.
```

**Expected behavior**
Enable autoscaler on cluster... 

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

`kubernetes-cli` has been upgraded to the latest version `2.0.74`

```
❯ az --version
azure-cli                         2.0.74

command-modules-nspkg              2.0.3
core                              2.0.74
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
image-copy-extension               0.0.9

Python location '/usr/local/Cellar/azure-cli/2.0.74/libexec/bin/python'
Extensions directory '/Users/puccinelli/.azure/cliextensions'

Python (Darwin) 3.7.4 (default, Sep  7 2019, 18:27:02)
[Clang 10.0.1 (clang-1001.0.46.4)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:57:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by Drewm3** [comment]
AKS team, could you please look into this issue.

**Comment by jluk** [comment]
@poochwashere the az aks nodepool command set is still in public preview, please reference the multiple node pools document. In addition the cluster autoscaler feature is also in preview.
https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#before-you-begin

The release notes describe the availability of being able to select a cluster backed by VMSS or VMAS, please refer to these release notes. Closing as a result, hope it helps.
https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.0.74
* Added --vm-set-type parameter to aks create command, which allows to specify vm types of an AKS Cluster (vmas or vmss)

**Comment by madhav5589** [comment]
Is this feature available now? If yes, can someone please share the command and parameter to pass in order to enable VMSS nodepool in existing cluster? Thanks.
