### ISSUE TITLE
MSI Install as User Context

### ISSUE THREAD

**Issue by gettek** [Azure/azure-cli#10715]
**Is your feature request related to a problem? Please describe.**
As a Windows user without Administrative privileges it would be beneficial to have the option to install the MSI under the **per-user installation** context instead of **per-machine**

**Describe the solution you'd like**
Current [install instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#install-or-update):
```
Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'
```

Desired installation flags as per [msiexec.exe property reference](https://docs.microsoft.com/en-us/windows/win32/msi/allusers)
```
Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList "/I AzureCLI.msi /quiet ALLUSERS=2 MSIINSTALLPERUSER=1 EXECUTEMODE=None TARGETDIR=$env:APPDATA\azure-cli"
```

**Describe alternatives you've considered**
Installation via Python virtual environments using the below command results in an unmanageable installation with az authentication issues
```
python -m venv $env:APPDATA\azure-cli
cd $env:APPDATA\azure-cli\Scripts
activate
pip install --user azure-cli
```

**Additional context**
Developer machines are unfortunately very restrictive at some places of work and this will be an excellent way to provide an acceptable and manageable approach

**Comment by maggiepint** [comment]
@mozehgir can you route this request appropriately?

**Comment by gettek** [comment]
Have found a work around with `/qb TARGETDIR=$env:APPDATA\azure-cli` !!:

```powershell
Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile $env:USERPROFILE\Downloads\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList "/a AzureCLI.msi /qb TARGETDIR=$env:APPDATA\azure-cli /quiet"
```
Thanks for the help
