### ISSUE TITLE
`az resource group delete` should accept a `--fast` or `--nowait` flag

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1071]
It looks like `az resource group delete` polls on the long-running operation and forces the user to wait for the deletion to complete.

I don't really ever want to wait on a resource group deployment. I'm usually issuing this command frequently when testing template deployments, so it would be really great to have a `--fast` or `--nowait` command so that I don't have to do tricks like `timeout 5 az resource group delete RGNAME`.

**Comment by tjprescott** [comment]
You can also use Ctrl+C to break out of the waiting, but yes I think we have many requests for something like that that applies to all LRO, not just RG delete.

**Comment by colemickens** [comment]
Yeah, that's what the `timeout` workaround I mentioned does effectively and is what I do by-hand right now... but it's a bit awkward when scripting. A flag that applies to all LRO calls sounds great though! (As long as it's a per-call flag and not a global/env var sort of thing... I want to wait on Creates, for example, but not Deletes).

Thanks!

**Comment by ahmetalpbalkan** [comment]
+1 on scripting purposes. `timeout` command cannot really guarantee success. when the deadline comes, the CLI might be doing garbage collection, retries or some other thing and might not have initialized the `delete` LRO.

**Comment by mayurid** [comment]
Sounds like a good idea. @yugangw-msft: thoughts on this?
Also we should consider for other delete commands which poll?

**Comment by johanste** [comment]
I see no reason to not have it as a global parameter and disable polling for any long running/asynchronous operations. Or, at least no reason to not have it for all azure mgmt operations - we may have to think a bit on how it affects data plane operations where polling is done in different ways, or for interactive commands like az configure (although I'd be perfectly happy to ignore the --nowait for az configure :))

**Comment by tjprescott** [comment]
Agree with Johan. We should have this option on most if not all LROs. Is `az configure` a LRO? I thought the issue is that we didn't want to just fire and forget, which is what "not polling" would do, but we wanted to at least confirm that the server accepted the initial request and get back some kind of ID to query it later?

**Comment by johngossman** [comment]
+1

Even when it is waiting it should show progress

**Comment by yugangw-msft** [comment]
You will get  a flag of "--no-wait" which ensures the delete gets accepted by server and then quit. You will get a matched "wait" to wait on any conditions.

**Comment by colemickens** [comment]
@yugangw-msft I didn't totally understand that.

`--no-wait` will cause the default waiting behavior to be skipped.

When would I use `--wait` though? Or are you saying I can fire off a long running operation with `--no-wait` and then somehow re-wait on it later on? That sounds very cool, just curious if you could give a couple sample commands to illustrate that behavior...

The PR is confusing to me. Why is `wait` a subcommand of VM? We want to wait on lots of things beyond just a VM creation.

**Comment by tjprescott** [comment]
See PR #1463.  Wait is actually a command, not an option flag.
