### ISSUE TITLE
Generate a test CLI build for Gallery API version 2019-07-01

### ISSUE THREAD

**Issue by singhkays** [Azure/azure-cli#10716]
**Resource Provider**
Azure.Compute

**Description of Feature or Work Requested**
We need help from CLI team to generate test CLI tooling for Shared Image Gallery service from our new swagger file. The new swagger file contains a new api-version and a few new API fields: https://github.com/Azure/azure-rest-api-specs/pull/6745 

**Minimum API Version Required**
2018-06-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/gallery.json

**Target Date**
ASAP

**Comment by yonzhan** [comment]
@qwordy please take a look and comment.

**Comment by qwordy** [comment]
We have received the feature request.

**Comment by qwordy** [comment]
@singhkays What platform do you require? Windows, Linux or Mac?

**Comment by yonzhan** [comment]
@qwordy this issue can be closed, right ?

**Comment by qwordy** [comment]
> 
> 
> @qwordy this issue can be closed, right ?

Yes. Thank you for closing it.
