### ISSUE TITLE
Support for Destination FQDNs in Network Rule and Translated FQDN in NAT Rule

### ISSUE THREAD

**Issue by tejasshah7** [Azure/azure-cli#10725]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Network (NRP)

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.

Need support for following 2 things:

- Just like the option to specify Destination IPs while configuring Network Rule, need a new option to specify Destination FQDNs (list of strings) while configuring Network Rule. This field will be optional.

- Just like the option to specify Translated IP while configuring NAT Rule, need a new option to specify Translated FQDN (string type) while configuring NAT Rule. This field will be optional.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

2019-09-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

Yet to be done.

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

End of October

**Comment by MyronFanQiu** [comment]
@tejasshah7 Thanks. We will include this issue in the plan for Ignite.

**Comment by tejasshah7** [comment]
Here is a link to the Swagger PR for this that has been merged in now:
https://github.com/Azure/azure-rest-api-specs/pull/7427

**Comment by tejasshah7** [comment]
> @tejasshah7 Thanks. We will include this issue in the plan for Ignite.

Added the swagger changes link for reference.

**Comment by MyronFanQiu** [comment]
This has been supported in new azure-firewall extension. Please check them.
