### ISSUE TITLE
Azure CLI not working in command-prompt

### ISSUE THREAD

**Issue by ianemv** [Azure/azure-cli#10729]
## Describe the bug

**Command Name**
`az storage blob upload-batch`

**Errors:**
```
HTTPSConnectionPool(host="'anothervue'.blob.core.windows.net", port=443): Max retries exceeded with url: /'$web'/error.html (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04D988B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Traceback (most recent call last):
pip-install-hn3yvyc1\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 57, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Run an az storage upload-batch to Powershell command and command prompt.

- _Put any pre-requisite steps here..._
- `az storage blob upload-batch --account-name {} --account-key {} --destination {} --source {} --debug`

## Expected Behavior

Upload all files and folder on current current all

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.74

```

**Comment by Juliehzl** [comment]
Hi @ianemv , accourding to your message `(host="'anothervue'.blob.core.windows.net", port=443)` , your storage account name is `'anothervue'` , which has single quotes and is not valid here. Can you check your storage account name again? If you still have problem, please post the full debug information by running your original command with `--debug`.

**Comment by ianemv** [comment]
Working now using Ubuntu instance. azure cli doesn't work windows command prompt both on my computer and Azure devops

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
Hi @ianemv, may I know your storage account name here?
