### ISSUE TITLE
Error in az ad app create --credential-description

### ISSUE THREAD

**Issue by ArgTang** [Azure/azure-cli#10720]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.74

**Describe the bug**
When creating ad app with credentials-description you may get an error if it is too long
```
λ  az ad app create --display-name "mytestapp" --password  "apassword" --credential-description "superlongdescriptionforpasswordonthisperticularadtestapp"
# When present, application key identifier cannot be empty and can be at most 32 bytes.
# Parameter name: applicationKeyIdentifierValue
```

**Expected behavior**
If this is intended behaviour, a better logmessage would be very helpful in identifying which argument is wrong. there is no argument called `applicationKeyIdentifierValue` in the command so it is hard to know what went wrong here

**Comment by maggiepint** [comment]
Thanks for the feedback - I have routed to the appropriate team for follow up.

**Comment by avishnyakov** [comment]
Hi team, having the same problem.

Azure Portal UI allows creation of secrets with long description, yet az cli fails.

What might be a path forward for automated secrets creation? @maggiepint  @haroldrandom 

```
# ok
az ad sp credential reset --name $appName --append --credential-description "ado-platform123"

# fails
az ad sp credential reset --name $appName --append --credential-description "ado-platform1234"
> az : ERROR: When present, application key identifier cannot be empty and can be at most 32 bytes.
```

![image](https://user-images.githubusercontent.com/3785585/109246765-efb33b80-7836-11eb-8515-e9ba9e54c0fc.png)

**Comment by avishnyakov** [comment]
Whoever needs this functionality, here is a working path forward
* get the app registration objectId
* use `az cli` rest call against `addPassword` endpoint 

Reference
* https://docs.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-1.0&tabs=http
* https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az_rest

```ps1
function Get-AppObjectId($appName) {
     $appId = [guid]$(az ad app list --query "[?displayName=='$appName'].objectId" --all -o tsv)
     return $appId
}

$appObjectId = Get-AppObjectId "my-app-registration-display-name"

$body = @{
    "passwordCredential" = @{
        "displayName" =  "123456789_123456789_123456789_123456789" 
    }
}

$bodyValue = $body | ConvertTo-Json -Compress
$bodyValue = $bodyValue.Replace('"', '\"')

$url = "https://graph.microsoft.com/v1.0/applications/$appObjectId/addPassword"

Write-Host "[~] posting: $url" -Fore Green

az rest --method POST `
    --uri $url `
    --headers "Content-Type=application/json" `
    --body "$bodyValue"

```

**Comment by SaurabhSharma-MSFT** [comment]
@ArgTang Apologies for the delayed response. This GitHub issue has been open for quite some time. Could you please let us know if you still facing this issue and need assistance? Awaiting your reply.

**Comment by ArgTang** [comment]
@SaurabhSharma-MSFT 
Yes this is still an issue we run into regurarly. my understanding is that this ties into the azcli graph migration, do you have any eta on that one?

**Comment by jiasli** [comment]
Same as https://github.com/Azure/azure-cli/issues/20561
