### ISSUE TITLE
web app update for slot doesn't work

### ISSUE THREAD

**Issue by mmulhearn** [Azure/azure-cli#10733]
**Versions**
azure-cli                         2.0.74
command-modules-nspkg              2.0.3
core                              2.0.74
nspkg                              3.0.4
telemetry                          1.0.3

**Describe the bug**
I'm attempting to automate resource tagging in across different subscriptions for reporting purposes.  My script works fine against production-slots, however, non-production slot updates end up targeting the production slot.

For example, our dev environments are slots on qa resources.  Adding a QA tag to the production slot (qa) works, but once I target the dev slot I get information back about the production slot and looking at portal.azure.com indicates the dev slot was not updated.

I do not see anything in the slot-specific commands to update a slot so I'm assuming slots are updateable just like it's a normal production-slot.

**To Reproduce**
Create a web app.  Add a slot to it.  Run the following command:

`az webapp update --ids $resource.id --set tags.environment=$env`

$.resource.id should be the full ID pointing to the non-production slot, e.g. `/subscriptions/subscriptionId/resourceGroups/resourceGroup/providers/Microsoft.Web/sites/webAppName/slots/dev`

**Expected behavior**
The slot should be updated, not the production app.

**Comment by panchagnula** [comment]
Thanks for reporting - what happens when you run the command using the --slot parameter instead of the --resourceId? https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-update

**Comment by mmulhearn** [comment]
Yup that did it.  I overlooked that argument.
