### ISSUE TITLE
Required fields are not listed in --help output

### ISSUE THREAD

**Issue by ezzy1337** [Azure/azure-cli#10734]
### **This is autogenerated. Please review and update as needed.**
A user must specify either `--resource-group` and  `--name` parameters or the `--ids` parameter when setting a connection string. None of these fields are documented in the `--help` output.

## Describe the bug

**Command Name**
`az webapp config connection-string set --help`

**Errors:**
The `--help` output does not mark `--resource-group`, `--name`, or `--ids` as required. running the command above results in the following error. 
```
(--resource-group --name | --ids) are required
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config connection-string set -t {} --settings {}`

## Expected Behavior
`az webapp config connection-string set --help` should output something similar to
```
Resource Id Arguments
    --ids [Required]               : One or more resource IDs (space-delimited). If
                                     provided, no other 'Resource Id' arguments should be specified.
    --name -n [Required]           : Name of the web app. You can configure the default
                                     using 'az configure --defaults web=<name>'.
    --resource-group -g [Required] : Name of resource group. You can configure the default
                                     group using `az configure --defaults group=<name>`.
```

## Environment Summary
```
Darwin-17.4.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.72 *

```

**Comment by ezzy1337** [comment]
I'm game for fixing this but could use help understanding how the documentation is being generated. I've found the `_params.py` file where I think the change needs to be made, just can't find any examples of how to do it.

**Comment by ezzy1337** [comment]
I did throw up a PR #10738 for what I thought could be a fix. Again don't mind making any updates needed.

**Comment by panchagnula** [comment]
Closing this since the linked PR is merged.
