### ISSUE TITLE
Add doc on how to pass array parameters

### ISSUE THREAD

**Issue by algattik** [Azure/azure-cli#10731]
This is explained at https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-deploy-cli#inline-parameters but missing in this doc page.

To pass inline parameters, provide the values in parameters. For example, to pass a string and array to a template is a Bash shell, use:

Azure CLI

Copy
az group deployment create \
  --resource-group testgroup \
  --template-file demotemplate.json \
  --parameters exampleString='inline string' exampleArray='("value1", "value2")'
If you're using Azure CLI with Windows Command Prompt (CMD) or PowerShell, pass the array in the format: exampleArray="['value1','value2']".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de233487-a2e5-00ab-30e9-f68866735957
* Version Independent ID: 2cd3ed9f-113f-a6c2-6a36-2925a044edf8
* Content: [az group deployment](https://docs.microsoft.com/en-us/cli/azure/group/deployment?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@haroldrandom  please take a look and comment.

**Comment by Juliehzl** [comment]
Hi @algattik, thanks for you feedback. We will improve it soon.
