### ISSUE TITLE
JMESPATH query fails when using az cli with gitbash

### ISSUE THREAD

**Issue by milkshakeuk** [Azure/azure-cli#10730]
**Describe the bug**
When trying to use any az cli command which supports JMESPATH under gitbash the command fails.

**Example**
```
az.cmd account show --query "keys(@)"
az account show: error: argument --query: invalid jmespath_type value: 'keys(@'
usage: az account show [-h] [--verbose] [--debug]
                       [--output {json,jsonc,table,tsv,yaml,none}]
                       [--query JMESPATH] [--subscription SUBSCRIPTION]
                       [--sdk-auth]
```

If I run the same command with cmd.exe:

```
az.cmd account show --query "keys(@)"
[
  "id",
  "name",
  "state",
  "user",
  "isDefault",
  "tenantId",
  "environmentName"
]
```

**To Reproduce**
See example above

**Expected behavior**
I would expect gitbash to work the same as cmd.exe

**Environment summary**
installed azure cli using the msi installer

Windows-10-10.0.18362-SP0
Python 3.6.6
Git: 2.23.0.windows.1 (64 bit)
Shell: gitbash
Shell Host: Windows Terminal (Preview) 0.5.2681.0

azure-cli 2.0.74

Extensions:
azure-devops 0.12.0

**Additional context**

**Comment by yonzhan** [comment]
@jiasli please take a look.

**Comment by jiasli** [comment]
This seems to be a bug with gitbash. 

If I add `echo %*` to C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd, double quotes are lost. 

```
$ az.cmd account show --query "keys(@)"

D:\cert>echo account show --query keys(@)
account show --query keys(@)
```
That's why az.cmd fails to parse it. 

Even this fails:

```
$ az.cmd "a b"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

Gitbash is currently not supported by Azure CLI.

**Comment by jamars** [comment]
@milkshakeuk, don't know if this helps, but you are still able to run these commands from gitbash with

`$COMSPEC /c "az.cmd account show --query \"keys(@)\""`
