### ISSUE TITLE
Role definition update failure

### ISSUE THREAD

**Issue by arnoldna** [Azure/azure-cli#10739]
### **This is autogenerated. Please review and update as needed.**

I received the following error while trying to update an existing RBAC role. 
**Command Name**
`az role definition update`

**Errors:**
```
'roleName'
Traceback (most recent call last):
Temp\pip-install-ygnynjtx\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 560, in execute
azure\cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 611, in _run_job
Local\Temp\pip-install-ygnynjtx\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 588, in _run_job
azure\cli\core\commands\__init__.py, ln 297, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 461, in default_command_handler
azure\cli\command_modules\role\custom.py, ln 55, in update_role_definition
azure\cli\command_modules\role\custom.py, ln 84, in _create_update_role_definition
KeyError: 'roleName'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._

I updated my json file with the "id" and "name" provided as part of the output in the initial role creation

- `az role definition update --role-definition {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.66 *

Extensions:
alias 0.5.2
azure-firewall 0.1.3
image-copy-extension 0.2.1

```

**Comment by yonzhan** [comment]
@jiasli please take a look and comment.

**Comment by jiasli** [comment]
Please note in `az role definition update` the json has `roleName`, instead of `Name`. The sample works as expected: https://docs.microsoft.com/en-us/cli/azure/role/definition?view=azure-cli-latest#az-role-definition-update

If the issue persists, please share the input json.

**Comment by jiasli** [comment]
Detailed explanations can be found at https://github.com/Azure/azure-cli/issues/12027#issuecomment-618901218.
