### ISSUE TITLE
Required fields are not listed in apim create --help output

### ISSUE THREAD

**Issue by ezzy1337** [Azure/azure-cli#10735]
## Describe the bug
A user must specify `--publisher-name` when creating a new APIM resource. This is not currently documented.

**Command Name**
`az apim create`

**Errors:**
```
validation error: Parameter 'ApiManagementServiceResource.publisher_name' can not be None.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim create --name {} -g {} -l {} --publisher-email {}`

## Expected Behavior
The output of `--help` should look something like
```
--publisher-name [Required] : The name of your organization for use in the developer portal
                                     and e-mail notifications.
```
## Environment Summary
```
Darwin-17.4.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.72 *

```

**Comment by yonzhan** [comment]
@zikalino please take a look.
