### ISSUE TITLE
Issues running ADF script

### ISSUE THREAD

**Issue by sinhru** [Azure/azure-cli#10742]
## Describe the bug

**Command Name**
`az ad sp create-for-rbac`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad sp create-for-rbac --role {} --scope {}`

## Environment Summary
```
Linux-4.15.0-1060-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.74

```

**Comment by yonzhan** [comment]
@jiasli please take a look and comment.

**Comment by qianwens** [comment]
Hi @sinhru , the bad request error may happen if the parameter value is not correctly set, could you please help provide a sample of your command?

**Comment by jiasli** [comment]
This is a known issue of Cloud Shell, please see https://github.com/Azure/azure-cli/issues/11749#issuecomment-570975762 for workaround.
