### ISSUE TITLE
The article doesn't list any samples.

### ISSUE THREAD

**Issue by pagariyaalok** [Azure/azure-cli#10744]
Please refer this page. It has all the details required with examples :
https://docs.microsoft.com/en-us/rest/api/monitor/diagnosticsettingscategory/list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55b103cb-dc59-8949-663f-f968a48d204e
* Version Independent ID: 387ce519-f57b-e817-6046-08552966744a
* Content: [az monitor diagnostic-settings categories](https://docs.microsoft.com/en-us/cli/azure/monitor/diagnostic-settings/categories?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@pagariyaalok Hello. I cannot fully understand your request. The reference is a article related with rest API. So do you mean that CLI should contain same information?

**Comment by pagariyaalok** [comment]
Apologies if it wasn't clear. My suggestion was to add examples in cli document for each command. For example, you can refer the above api documentation link which has good summarization of the operations with examples.
