### ISSUE TITLE
Support new Network resource VirtualRouter and VirtualRouterPeer

### ISSUE THREAD

**Issue by naveenchekuri** [Azure/azure-cli#10748]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
This feature is to support customer creating new resource called VirtualRouter under Microsoft.Network and peerings child resource under virtualRouter. Customer can choose to reference VirtualNetworkGateway or Subnet where VirtualRouter would be hosted

Following is the work flow by customers using this feature

- Create WorkFlow:
   - Create VirtualRouter inside a virtual network
   - Create one or more VirtualRouterPeers inside VirtualRouter

- Update WorkFlow:
   - Update one or more VirtualRouterPeers inside VirtualRouter

- Delete WorkFlow:
   - Delete one or more VirtualRouterPeers inside VirtualRouter
   - Delete VirtualRouter inside a virtual network

**Minimum API Version Required**
2019-08-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-08-01/virtualRouter.json

**1. VirtualRouterProperties** 

    "VirtualRouterPropertiesFormat": {
      "properties": {
        "virtualRouterAsn": {
          "type": "integer",
          "readOnly": false,
          "format": "int64",
          "minimum": 1,
          "maximum": 4294967295,
          "description": "VirtualRouter ASN."
        },
        "virtualRouterIps": {
          "type": "array",
          "readOnly": false,
          "description": "VirtualRouter IPs",
          "items": {
            "type": "string"
          }
        },
        "hostedSubnet": {
          "readOnly": false,
          "$ref": "./network.json#/definitions/SubResource",
          "description": "The Subnet on which VirtualRouter is hosted."
        },
        "hostedGateway": {
          "readOnly": false,
          "$ref": "./network.json#/definitions/SubResource",
          "description": "The Gateway on which VirtualRouter is hosted."
        },
        "peerings": {
          "type": "array",
          "readOnly": true,
          "description": "List of references to VirtualRouterPeerings",
          "items": {
            "$ref": "./network.json#/definitions/SubResource"
          }
        },
        "provisioningState": {
          "description": "The provisioning state of the resource.",
          "readOnly": true,
          "$ref": "./network.json#/definitions/ProvisioningState"
        }
      },
      "description": "Virtual Router definition"
    }

**2. VirtualRouterPeering properties**

     "VirtualRouterPeeringProperties": {
      "properties": {
        "peerAsn": {
          "type": "integer",
          "readOnly": false,
          "format": "int64",
          "minimum": 1,
          "maximum": 4294967295,
          "description": "Peer ASN."
        },
        "peerIp": {
          "type": "string",
          "readOnly": false,
          "description": "Peer IP."
        },
        "provisioningState": {
          "description": "The provisioning state of the resource.",
          "readOnly": true,
          "$ref": "./network.json#/definitions/ProvisioningState"
        }
      },
      "description": "Properties of the rule group."
    }

**Target Date**
We are targeting this feature for Ignite. Please help us with this feature

**Comment by MyronFanQiu** [comment]
@naveenchekuri Thanks. We will make a plan for it.

**Comment by MyronFanQiu** [comment]
just need hostedGateway(express-route gateway) for virtualrouter. peerIp and peerAsn can be arbitrary values.

**Comment by MyronFanQiu** [comment]
https://github.com/Azure/azure-cli/pull/10994 Please check.
