### ISSUE TITLE
Add Identity under ExpressRoutePort and MacSec fields under ExpressRouteLink

### ISSUE THREAD

**Issue by naveenchekuri** [Azure/azure-cli#10747]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
We are adding MacSec support for ExpressRoute Direct Port. ExpressRoute Direct Port is an existing feature which gives customers ability to create dedicated port for them. Customers could choose to enable Mac Security for direct ports.

Following are the workflow steps of customer to enable Mac Security on Direct Ports

Create User Assigned Identity 
Create Keyvault with MacSec CAK and CKN secrets 
Set Identity in ExpressRoutePort and MacSec CAK, CKN Secret identifier in ExpressRoutePortLink

**Minimum API Version Required**
2019-08-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-08-01/expressRoutePort.json

**1. Identity under ExpressRoutePort**

    "ExpressRoutePort": {
      "title": "ExpressRoute Port",
      "description": "ExpressRoutePort resource definition.",
      "properties": {
        "properties": {
          "x-ms-client-flatten": true,
          "$ref": "#/definitions/ExpressRoutePortPropertiesFormat",
          "description": "ExpressRoutePort properties."
        },
        "etag": {
          "readOnly": true,
          "type": "string",
          "description": "A unique read-only string that changes whenever the resource is updated."
        },
        "identity": {
          "$ref": "./network.json#/definitions/ManagedServiceIdentity",
          "description": "The identity of ExpressRoutePort, if configured."
        }
      }

** MacSec configuration under ExpressRouteLink **

    "ExpressRouteLinkMacSecConfig": {
      "description": "ExpressRouteLink Mac Security Configuration.",
      "title": "Definition of ExpressRouteLink Mac Security configuration.",
      "properties": {
        "cknSecretIdentifier": {
          "type": "string",
          "description": "Keyvault Secret Identifier URL containing Mac security CKN key."
        },
        "cakSecretIdentifier": {
          "type": "string",
          "description": "Keyvault Secret Identifier URL containing Mac security CAK key."
        },
        "cipher": {
          "type": "string",
          "description": "Mac security cipher.",
          "enum": [
            "gcm-aes-128",
            "gcm-aes-256"
          ],
          "x-ms-enum": {
            "name": "ExpressRouteLinkMacSecCipher",
            "modelAsString": true
          }
        }
      }

**Target Date**
We are targeting this feature for Ignite. Please help us with this feature

**Comment by MyronFanQiu** [comment]
@naveenchekuri Thanks. We will make a plan for it.

**Comment by haroldrandom** [comment]
@naveenchekuri For a `ManagedServiceIdentity` which a `ExpressRoutePort` need, this [doc](https://docs.microsoft.com/en-us/azure/expressroute/expressroute-howto-macsec) told me it's actually a `AzUserAssignedIdentity `,  
![Jietu20191017-013344](https://user-images.githubusercontent.com/14357159/66943671-3e1acc80-f07e-11e9-8c22-0b55f56aa1a2.jpg)


then I look for the definition of something like `UserAssignedIdentity`, I found one in [a swagger file: network.json](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-08-01/network.json)

```JSON
"ManagedServiceIdentity": {
      "properties": {
        "principalId": {
          "readOnly": true,
          "type": "string",
          "description": "The principal id of the system assigned identity. This property will only be provided for a system assigned identity."
        },
        "tenantId": {
          "readOnly": true,
          "type": "string",
          "description": "The tenant id of the system assigned identity. This property will only be provided for a system assigned identity."
        },
        "type": {
          "type": "string",
          "description": "The type of identity used for the resource. The type 'SystemAssigned, UserAssigned' includes both an implicitly created identity and a set of user assigned identities. The type 'None' will remove any identities from the virtual machine.",
          "enum": [
            "SystemAssigned",
            "UserAssigned",
            "SystemAssigned, UserAssigned",
            "None"
          ],
          "x-ms-enum": {
            "name": "ResourceIdentityType",
            "modelAsString": false
          }
        },
        "userAssignedIdentities": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "principalId": {
                "readOnly": true,
                "type": "string",
                "description": "The principal id of user assigned identity."
              },
              "clientId": {
                "readOnly": true,
                "type": "string",
                "description": "The client id of user assigned identity."
              }
            }
          },
          "description": "The list of user identities associated with resource. The user identity dictionary key references will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}'."
        }
      },
      "description": "Identity for the resource."
    },
```

My question is **what the actual properties of an `ManagedServiceIdentity` do you need?**

**Comment by naveenchekuri** [comment]
@haroldrandom We would need "Id" field as string from ManagerServiceIdentity. Sample example for that would be "/subscriptions/ae4fd9c1-f57f-4077-8cb5-e9c0a1bb8796/resourcegroups/SeaMACsecCkt/providers/Microsoft.ManagedIdentity/user
AssignedIdentities/macSecTestIdentity". Let me know if you need anything else

**Comment by haroldrandom** [comment]
So, the Object I need to set actually is the `userAssignedIdentities` of `ManagedServiceIdentity`, but which has two properties: `principalId` and `clientId`. Which one I should set?

**Comment by haroldrandom** [comment]
Features Added in #10939 . If have any questions, feel free to reopen.
