### ISSUE TITLE
It's always good to add actual example of each command.

### ISSUE THREAD

**Issue by pagariyaalok** [Azure/azure-cli#10743]
It's always good to add actual example of each command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abfaa54-0895-29f7-f3bb-ff604912b2ac
* Version Independent ID: d1ff3478-8a86-59e4-62ef-449900132a67
* Content: [az account](https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest#az-account-set)
* Content Source: [src/azure-cli/azure/cli/command_modules/profile/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/profile/_help.py)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by zikalino** [comment]
This is pretty generic issue

**Comment by yonzhan** [comment]
add to S163.

**Comment by haroldrandom** [comment]
The `account` command groupd is simple enough I guess, personally, most of sub-commands doesn't have more than 3 parameters even 0 parameter, is it necessary to add example?

**Comment by haroldrandom** [comment]
If you mean every command instead of account commands only, we are leveraging Aladdin to do it who is an AI that that could learn from Internet automatically to find valueable comamnd examples to supplement those commands that missing examples.
