### ISSUE TITLE
Opion to specify precise credential end date for Service Principal secrets

### ISSUE THREAD

**Issue by cocowalla** [Azure/azure-cli#10746]
At present, the Azure CLI lets you specify an end date in _years_ for Service Principal client secrets.

I'd like to be able to specify a _precise_ end date for Service Principal secrets, when creating new Service Principals using `az ad sp create-for-rbac`, but especially when adding/updating secrets using `az ad sp credential reset --append`.

An alternative is to use certificates, which allow you to specify a precise end date - the end date of the certificate is the end date of the secret - this is a great option for many use cases, but it's harder to pass around a file than a simple string.

Another alternative is to use Az Powershell, which already lets you [specify an exact end date](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-2.7.0#create-a-service-principal).

Perhaps another way of putting this is that I'd like Az CLI to reach feature parity with `az ad sp credential`.

**Comment by yonzhan** [comment]
@jiasli  please take a look and comment.

**Comment by cocowalla** [comment]
I should add that the REST API also let's you specify a precise end date, both the "application/addPassword" and "update service principal credentials" endpoints (on mobile right now, and can't remember the exact endpoint names!).

**Comment by jiasli** [comment]
Thank you for the feedback. We will consider this as a feature request.
