### ISSUE TITLE
"az storage file upload-batch" does not work with connectionstring and account key

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-cli#10740]
When trying to use the command  - az storage file upload-batch with --connection-string am getting the below error

Suppress exception There are no active accounts.
Suppress exception Please run 'az login' to setup account.

The purpose of using --connection-string is to suppress the need to login, and that does not work.

**Command used:**

az storage blob upload-batch --connection-string "DefaultEndpointsProtocol=https;AccountName=xxxx;AccountKey=secret;EndpointSuffix=core.windows.net" -s "C:\Users\secret\Documents\config" -d Secret/Folder1/Folder2 --auth-mode Key

**Azure CLI Version:** 2.0.74
**OS:** 10.14.6 macOS Mojave
**Python** 2.7.5

Thanks!

**Comment by Juliehzl** [comment]
@rajaprad Do you specify your storage account name with `--account-name` parameter in your command?

**Comment by rajaprad** [comment]
@juliehzl, I have tried two scenarios.

1. With --connection-string (this does not require --account-name)

2. With --account-name and --account-key.

Both does not work in MAC OS, works in Windows and Linux machines. Same version of azure-cli in all 3 OS.

**Comment by yonzhan** [comment]
add to S173

**Comment by Juliehzl** [comment]
Hi @rajaprad, I have tried with latest [azure cli](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) in MacOS and it works.

could you try with latest azure cli first?  if it still doesn't work, could you add `--debug` in you command and provide more information for your scenario?

**Comment by yonzhan** [comment]
@rajaprad, any update?

**Comment by Juliehzl** [comment]
closed given there is no response for a long time
