### ISSUE TITLE
--public-ip-address "" needs space in documentation

### ISSUE THREAD

**Issue by MachLearnPort** [Azure/azure-cli#10758]
Received an error when not using space between quotes (i.e. az vm create: error: argument --public-ip-address: expected one argument)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by qwordy** [comment]
Received. National day holiday: 1st Oct ~ 7th Oct.

**Comment by qwordy** [comment]
Hi @MachLearnPort, thank you for finding this problem.
I think it's a mistake of doc.
```or specify "" for None```

**Comment by qwordy** [comment]
I guess you are using Powershell. Powershell will remove " for you automatically. Use %--"%--" instead of "" in Powershell. Similar to #10786.
