### ISSUE TITLE
Modifications to az network public-ip prefix CLI cmdlet to introduce new optional parameter --version

### ISSUE THREAD

**Issue by sm947** [Azure/azure-cli#10757]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Network Resource Provider

**Description of Feature or Work Requested**
We are extending support for IPv6 Public IP prefixes for Standard SKUs in addition to existing IPv4 public ip prefixes and we need newer **version** optional parameter to distinguish between IPv4/IPv6 Public IP address prefix to be created. 

Sample use case - if user specifies -version in CLI command and pass accepted values Ipv4 or ipv6 in optional version parameter, then Ipv4 or Ipv6 public ip prefixes need to be created. If user doesn't pass version field parameter in CLI create command, then Ipv4 is the default value that needs to be tagged to **PublicIpAddressVersion** field in swagger. 

Modified  az network public-ip prefix CLI cmdlet after introducing new field **version**
az network public-ip prefix create --length
                                   --name
                                   --resource-group
                                   [--location]
                                   [--subscription]
                                   [--tags]
                                   [--zone {1, 2, 3}]
                                   **[--version {IPv4, IPv6}]**
where **--version** field is an optional parameter of IP address type.
accepted values: IPv4, IPv6
default value: IPv4

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2019-08-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
publicipprefix.json file in swagger master branch (link below) already has PublicIpAddressVersion field which will distinguish IPv4/IPv6 
**https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-08-01/publicIpPrefix.json**

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
10/15/2019 since IPv6 feature is planned for GA soon.

**Comment by MyronFanQiu** [comment]
@sm947 Thanks. We will make a plan for it.
