### ISSUE TITLE
Unable to create storage containers

### ISSUE THREAD

**Issue by gambtho** [Azure/azure-cli#10753]
## Describe the bug

**Command Name**
`az storage container create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 132, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container create --name {} --account-name {}`

## Environment Summary
```
Linux-4.19.67-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.74

```

**Comment by Juliehzl** [comment]
Hi @gambtho, can you show me more information with `--debug` in your command?

**Comment by yonzhan** [comment]
Hi @gambtho, any update for above?

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
Hi @gambtho, there is no response for a long time. There is a server issue before, but it should be fixed already.

Please have a try again and if there is any issue, feel free to reopen the issue or create a new one.
