### ISSUE TITLE
Change node version at functionapp creation

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#10766]
We need to set the "WEBSITE_NODE_DEFAULT_VERSION" app setting should have a value of "~10" instead of current value

**Comment by MyronFanQiu** [comment]
@ahmedelnably  Hello. Looks like you are from service team. I'm not sure. Was CLI maintained by yourselves or CLI team?

**Comment by ahmedelnably** [comment]
@MyronFanQiu The Functions CLI maintained by the Functions CLI team, myself, @fabiocav, and others on the team

**Comment by ankitkumarr** [comment]
Assuming this is just for Windows.

Linux doesn't care about that setting.
