### ISSUE TITLE
more info Needed

### ISSUE THREAD

**Issue by Rakesh-Gnana-Selvan-888** [Azure/azure-cli#10761]
Please add samples as this is very confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44e1bd9c-c9ca-3abd-9c9f-0a1318d88c4e
* Version Independent ID: 0e999302-0e64-083f-718b-0ee575d235df
* Content: [az monitor activity-log alert scope](https://docs.microsoft.com/en-us/cli/azure/monitor/activity-log/alert/scope?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@Rakesh-Gnana-Selvan-888 Thanks. We will take a look at this issue and improve the help information.
