### ISSUE TITLE
az policy set-definition create is missing metadata argument

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-cli#10768]
**Describe the bug**
az policy set-definition create is missing the metadata argument. This is necessary to provide, among else, the category information.

This is similar to #5798

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
azure-cli                         2.0.74

command-modules-nspkg              2.0.3
core                              2.0.74
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
aks-preview                        0.4.5
azure-devops                      0.13.0

Python location '/usr/local/Cellar/azure-cli/2.0.74/libexec/bin/python'
Extensions directory '/Users/bengelens/.azure/cliextensions'

Python (Darwin) 3.7.4 (default, Sep  7 2019, 18:27:02) 
[Clang 10.0.1 (clang-1001.0.46.4)
```

**Comment by yonzhan** [comment]
How is the status of this issue?
