### ISSUE TITLE
az login crashes if subscription has no name

### ISSUE THREAD

**Issue by thomas-schilling-adn** [Azure/azure-cli#10760]
Somehow, somebody created a nameless subscription in our Azure enterprise account. This breaks "az login". See below for details

## Describe the bug

**Command Name**
`az login`

**Errors:**
```
'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.7/site-packages/six.py, ln 693, in reraise
    raise value
...
azure/cli/core/__init__.py, ln 485, in default_command_handler
    return op(**command_args)
cli/command_modules/profile/custom.py, ln 147, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
azure/cli/core/_profile.py, ln 230, in find_subscriptions_on_login
    is_service_principal, bool(use_cert_sn_issuer))
azure/cli/core/_profile.py, ln 243, in _normalize_properties
    s.display_name.encode(sys.getdefaultencoding())
AttributeError: 'NoneType' object has no attribute 'encode'
```

## To Reproduce:

Have a subscription with no display name, i.e. `None`. I honestly don't know how that can happen, but it did.

- `az login`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.74

```

**Comment by thomas-schilling-adn** [comment]
Manually editing the files to the following fixes the issue:
```python
        for s in subscriptions:
            display_name = s.display_name
            if display_name is None:
                display_name = ''
            try:
                display_name.encode(sys.getdefaultencoding())     # removed the "s." here
```

**Comment by jiasli** [comment]
Actually when you change the subscription name in Azure Portal and leave it empty, it say 

>The name cannot be empty, more than 64 characters, or contain the following characters: < > ; |

I have created PR #10771 to make CLI more robust. Could you open a support ticket to Azure subscription team to report this issue as well? (I don't have your subscription's detail.) Thank you.

**Comment by thomas-schilling-adn** [comment]
It seems to be a permission issue. The subscription was created by someone else and for him it does show a name. It's not part of our enterprise agreement but some other offer. It also has a different symbol (stock chart with arrow vs three dots for most other subscriptions).
