### ISSUE TITLE
Azure blob storage quickstart fails on container creation

### ISSUE THREAD

**Issue by craigc40** [Azure/azure-cli#10765]
## Describe the bug

**Command Name**
`az storage container create`

**Errors:**
```
Incorrect padding
Traceback (most recent call last):
storage\v2018_11_09\common\_auth.py, ln 69, in _add_authorization_header
storage\v2018_11_09\common\_common_conversion.py, ln 91, in _sign_string
storage\v2018_11_09\common\_common_conversion.py, ln 81, in _decode_base64_to_bytes
Azure\CLI2\lib\base64.py, ln 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

...

storage\v2018_11_09\common\_auth.py, ln 94, in sign_request
storage\v2018_11_09\common\_auth.py, ln 75, in _add_authorization_header
azure.multiapi.storage.v2018_11_09.common._error.AzureSigningError: Incorrect padding
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container create --name {}`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.74

```

**Comment by Juliehzl** [comment]
@craigc40  How do you do the authentication for your command? Can you check if your storage account key or connection string is valid value?

**Comment by craigc40** [comment]
This appears to be user error, but the quickstart (https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-cli) is not very helpful. I'm not sure if this is the place to provide feedback about it.

It says to set these environment variables:
export AZURE_STORAGE_ACCOUNT="mystorageaccountname"
export AZURE_STORAGE_KEY="myStorageAccountKey"

Despite the fact that the above use quotes, they should not be used.

This is the first time 'mystorageaccountname' is used. It is supposed to be the same value as 'mystorageaccount'.  Why the name change?

Even though it doesn't explicitly say so, I am to replace 'myStorageAccountKey' with one of the keys from the 'az storage account keys list' command. That command lists two keys. I picked the first one, but there is no information saying to do that or whether it matters which key is chosen.

If there is a bug to report here, it is that there should not be a python exception raised when the key is bad (in this case, I assume it was bad because I had included the quotes). To a newbie like me, 'padding error' is not a useful message to help me figure out what I did wrong.

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
will refine the error message for incorrect padding.
