### ISSUE TITLE
Usage strings must be printed to stderr

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#1077]
I was running:

```
$ az group list | jq -r '.[].name'
parse error: Invalid numeric literal at line 1, column 6
```

until it took me quite a while to realize it's actually a bad command but the error is printed to `STDOUT` instead of `STDERR` so it was fed to jq over the pipe ===very dangerous.

Unix tools must print usage strings and other errors to `STDERR`. Please look at some other unix tools as examples.

**Comment by johanste** [comment]
@ahmetalpbalkan, completely agreed on printing errors/warnings/non "output" messages to stderr. 

Which version of python/os are you running on? And which version of jq? I tried running the az group list part above, and the usage string goes to stderr. Are you 100% sure that the output isn't from jq?

**Comment by ahmetalpbalkan** [comment]
@johanste it looks like a bug on my side. When I run a container interactively and started `az` from there it went to stderr. When I run it as `docker run -t -i azuresdk/azure-cli-python az group list 2>/dev/null` it didn't go to stderr. I guess a docker-cli issue.

Sorry for the trouble.
