### ISSUE TITLE
'NoneType' object has no attribute 'server_farm_id'

### ISSUE THREAD

**Issue by evandervalk** [Azure/azure-cli#10773]
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
'NoneType' object has no attribute 'server_farm_id'
Traceback (most recent call last):
Temp\pip-install-6e754znd\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 654, in _run_job
Local\Temp\pip-install-6e754znd\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 485, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 314, in enable_zip_deploy_functionapp
AttributeError: 'NoneType' object has no attribute 'server_farm_id'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az functionapp create ...`
- `az functionapp deployment source config-zip --src {} --name {} --resource-group {}`

## Expected Behavior

I expect it to deploy. Instead I get an error.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.74

```

**Comment by BrixSat** [comment]
Same issue here 

az --version

azure-cli                         2.0.74 *

command-modules-nspkg              2.0.3
core                              2.0.74 *
nspkg                              3.0.4
telemetry                          1.0.3 *

Python location '/opt/az/bin/python3'
Extensions directory '/home/xarevision/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Sep 20 2019, 05:43:07) 
[GCC 8.3.0]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by mlomat** [comment]
I had exactly this same issue. This tip to set subscription helped. Maybe it will help you also. 

https://stuart-moore.com/azure-cli-error-nonetype-object-has-no-attribute-server_farm_id/

**Comment by jalajmsft** [comment]
This issue also seems to be happening intermittently for **webapp deployment**. 

`az webapp deployment source config-zip -g {} -n {} --src {}`

This was raised at [azure-pipelines-tasks repo](https://github.com/microsoft/azure-pipelines-tasks/issues/11862).

**Comment by evandervalk** [comment]
Any update on this issue? Hoping to get this fixed soon so I can just use Azure CLI instead of a combination of Azure CLI and Azure Function Core Tools (which bloats my Docker image).

**Comment by MarkHerhold** [comment]
I hit this issue and it turns out that I typo'd a resource name (the function app itself). The CLI errors are terrible and make it look like a CLI bug when it actually was mine.

I used `--debug` at the end of my CLI command to help figure out the issue - there was a 404 HTTP response.

Hope this helps someone.

**Comment by amac44** [comment]
Confused about the 404 error mentioned above (which I am also getting) - Does the target function app have to already exist? So to copy a function app from resource group A to resource group B using config-zip, one would have to (1) create app plan on target, (2) create function app on target than uses that plan, (3) run az functionapp deployment source config-zip ?

**Comment by MarkHerhold** [comment]
> Confused about the 404 error mentioned above (which I am also getting) - Does the target function app have to already exist? So to copy a function app from resource group A to resource group B using config-zip, one would have to (1) create app plan on target, (2) create function app on target than uses that plan, (3) run az functionapp deployment source config-zip ?

I believe so, yes. The CLI won't create anything. You'd probably want to use a deploy template.

**Comment by navba-MSFT** [comment]
@evandervalk Apologies for the late reply. Could you please let me know if you are still facing the same issue with [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of Az CLI? Awaiting you reply.

**Comment by evandervalk** [comment]
Seeing as I created this ticket 2 years ago, we've since worked around the problem and I don't even know if the workaround is still in place. I'd have to check and get into it when I'm not busy, which I'm happy to do but it will take some time.

On that note, it's interesting to see that it can take 2 years for a reply from Microsoft but I'm expected to solve this in 14 days 😕.

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed. Please upgrade to latest version of az cli 2.40.0 and retry
