### ISSUE TITLE
az storage account network-rule add does not work for two different resource groups

### ISSUE THREAD

**Issue by milodotnet** [Azure/azure-cli#10772]
I'm trying to use

az storage account network-rule add 

with the vnet and subnet flag

If the storage account and network are in different resource group the cli fails to find one or the other depending on which resource group you specify in the resource-group flag

azure cli version 2.0.74

**Comment by Juliehzl** [comment]
Hi @milodotnet, sorry for inconvenience. You are right for the scenario when you specify vnet and subnet using their name, we will think it is in the same resource group with what you specify for your storage account. If you want to use a subnet in different resource group, you need to specify your subnet with subnet id. e.g. `az storage account network-rule add --subnet /subscriptions/0vdsdbgns/resourceGroups/myresourcegroup/providers/Microsoft.Network/virtualNetworks/test/subnets/testsubnet -g anotherrg --account-name storagetestaccount`.
I will add an example for `az storage network-rule add` command to help better user experience soon.

**Comment by para0056** [comment]
Any updates as to when this will be resolved?
Thanks

**Comment by yonzhan** [comment]
add to S168

**Comment by Juliehzl** [comment]
@para0056 Could you please try with subnet id as I shown above? You can use a subnet in another resource group with resource id. 

If there is any problem, feel free to let me know.

**Comment by Juliehzl** [comment]
@milodotnet Because there is no response for 24 days, I will close this issue and feel free to reopen it.

**Comment by syunwei** [comment]
Using the subnet id is working...
