### ISSUE TITLE
Can't create VM without NSG

### ISSUE THREAD

**Issue by rerime** [Azure/azure-cli#10786]
**Describe the bug**
Can't create VM without NSG

> --nsg
The name to use when creating a new Network Security Group (default) or referencing an existing one. Can also reference an existing NSG by ID or specify "" for none.
https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create

**To Reproduce**
`az vm create --name name --resource-group group --admin-username user --admin-password pass --availability-set AVS --public-ip-address vmName-ip --public-ip-address-allocation static --subnet id_of_subnet --storage-sku Standard_LRS --size Standard_B2ms --image Win2019Datacenter --nsg ""`

**Expected behavior**
Create VM without NSG attached to network interface

**Environment summary**
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.74
```

**Comment by qwordy** [comment]
What's the output of the command?

**Comment by rerime** [comment]
> az : ERROR: az vm create: error: argument --nsg: expected one argument

**Comment by qwordy** [comment]
Hi rerime, could you try:
`az vm create --name name --resource-group group --admin-username user --admin-password pass --availability-set AVS --public-ip-address vmName-ip --public-ip-address-allocation static --subnet id_of_subnet --storage-sku Standard_LRS --size Standard_B2ms --image Win2019Datacenter`

Thank you for the feedback. The doc is inconsistent with actual behavior of Azure CLI. "" is not treated as an argument in the command parsing phase.

I will do one of following options:
(1) Update the doc.
(2) Update the code so that Azure CLI can receive an empty string.

I prefer (1). If you don't want use a nsg, just ignore this parameter. --nsg "" is redundant.
Any ideas? @MyronFanQiu @yonzhan

**Comment by MyronFanQiu** [comment]
@qwordy If `--nsg` is not a required argument for the command, I think we should modify the help information.

**Comment by rerime** [comment]
Without `--nsg`, it generate it with some random name.

**Comment by qwordy** [comment]
@rerime I understand now. The default NSG name is "{vm_name}NSG" in my experimentation where no --nsg is given.
@Drewm3 Do you know whether Azure supports VM without NSG?
Thanks.

**Comment by Drewm3** [comment]
I believe it is possible to have a VM without an NSG, but it is highly discouraged to create a VM with a public IP address without an NSG. This would mean the VM has all ports open to all traffic on the internet. We should never do something like this as a default behavior.

**Comment by qwordy** [comment]
> 
> 
> I believe it is possible to have a VM without an NSG, but it is highly discouraged to create a VM with a public IP address without an NSG. This would mean the VM has all ports open to all traffic on the internet. We should never do something like this as a default behavior.

Thank you for your reply. I tried in portal. NSG can be set to None. So Azure CLI should also be able to offer this option although it's not recommended.

**Comment by qwordy** [comment]
> 
> 
> `az : ERROR: az vm create: error: argument --nsg: expected one argument`

I guess this line is wrong. --nsg "" will not generate this error.

**Comment by qwordy** [comment]
Are you using Powershell? Powershell will remove "" for you so you will see `error: argument --nsg: expected one argument`. I'm using Powershell and I am deceived. We support this "" value of --nsg in Azure CLI. Try using command prompt or bash. Or use `%--"%--"` to represent "" in Powershell.

**Comment by bakerm00** [comment]
--nsg **'**""**'** works - the stop-parsing affects variables
