### ISSUE TITLE
Adding Public IP to each scale set command missing in CLI

### ISSUE THREAD

**Issue by anavinahar** [Azure/azure-cli#10787]
**Resource Provider**
What is the Azure resource provider your feature is part of?
ARM

**Description of Feature or Work Requested**
Here are the docs for templates. https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-networking#public-ipv4-per-virtual-machine
But looks like CLI needs to be updated for VMSS.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/createorupdate

**Swagger Link**
Link above should be enough since already released.

**Target Date**
ASAP as this is already live.

**Comment by qwordy** [comment]
I have received your feature request.

**Comment by yonzhan** [comment]
We will plan this during next sprint.

**Comment by qwordy** [comment]
Hi Anavi, 
Azure CLI has the following parameters for `vmss create` related to public IP
```
[--public-ip-address]
[--public-ip-address-allocation {dynamic, static}]
[--public-ip-address-dns-name]
[--public-ip-per-vm]
```
Could you tell me more details? What's the feature you expect?

**Comment by qwordy** [comment]
@anavinahar
