### ISSUE TITLE
ARM: Add management lock commands

### ISSUE THREAD

**Issue by vivsriaus** [Azure/azure-cli#1078]

**Comment by mayurid** [comment]
@vivsriaus : This is for post-connect. Let us know if you disagree.

**Comment by brendandburns** [comment]
Is this still an active work stream?  I can add support for this if no one is working on it.

**Comment by vivsriaus** [comment]
@brendandburns Yes, lock commands are still pending. I'd check with @yugangw-msft and @mayurid to ensure they're not already working on it, to ensure no overlap. Thanks!

**Comment by yugangw-msft** [comment]
@vivsriaus, we are not working on it, and contributions are very much welcome

**Comment by brendandburns** [comment]
ok, I'll add this to my todo list.

**Comment by brendandburns** [comment]
@yugangw-msft if you add me as a maintainer I can assign issues to myself :)
