### ISSUE TITLE
CLI module for object replication service

### ISSUE THREAD

**Issue by artemuwka** [Azure/azure-cli#10794]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Azure Storage

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
Adding ORS configuration to CLI: Set/Get/Remove-AzStorageObjectReplicationPolicy, New-AzStorageObjectReplicationPolicyRule, New-AzStorageObjectReplicationPolicyRuleFilter - these are the 5 commands we'd like to have available in CLI.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

**Target Date**
*Mid-October* is ideal. 
We're preparing a demo for MarkRus at Ignite and need a way to perform ORS operations using public APIs/tools.

**Comment by Juliehzl** [comment]
Hi @artemuwka, if there is any update for swagger file, please let me know and provide the link in your template.

**Comment by Juliehzl** [comment]
The private package is delivered, but wait for feedback. In this way, it is fine to close it now
