### ISSUE TITLE
Popup during linux script blocks install

### ISSUE THREAD

**Issue by DavidLangworthy** [Azure/azure-cli#10793]
On mint and WSL a popup comes up when running the one line install script from an XTerm. This does not occur over ssh. The title is Configuring libssl1.1:amd64 and it asks for permission to restart services.

See

[https://github.com/MicrosoftDocs/azure-docs-cli/issues/1607#issuecomment-540241416](url)

> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by MaurGi** [comment]
Happened to me as well, real nasty - 
repro: 
- Install WSL2 on Win build 18999
- Instal Ubuntu 18.04 
- Instal Windows Terminal (https://github.com/microsoft/terminal)
- Run the script

**Comment by MaurGi** [comment]
The step that creates the popup is: 
```
curl -sL https://packages.microsoft.com/keys/microsoft.asc | 
    gpg --dearmor | 
    sudo tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null
```

Here is what I see:
![image](https://user-images.githubusercontent.com/13138584/66593377-b8fa5980-eb4b-11e9-8beb-951f5868a906.png)

I can't get past this

**Comment by fengzhou-msft** [comment]
We can disable the popup through debconf settings before starting the installation of azure-cli:
`sudo apt-get update && sudo apt-get -y install debconf-utils`
`echo 'libssl1.1 libraries/restart-without-asking boolean true' | sudo debconf-set-selections`

**Comment by DavidLangworthy** [comment]
That sounds good.  

Are you putting that into the script or is that a workaround that goes into the doc?

**Comment by epleterte** [comment]
Have you considered `export DEBIAN_FRONTEND=noninteractive` instead of permanently setting/changing this?

**Comment by DavidLangworthy** [comment]
Any solution is fine.  I'd like it to be added to the script so it just runs independent of platform.

**Comment by yonzhan** [comment]
Was this issue resolved?

**Comment by epleterte** [comment]
@yonzhan Comment from @fengzhou-msft only suggests a change?

@DavidLangworthy   ...that's the discussion. "Just fix it for me", which is my takeback from your comment, isn't very useful. Of course a fix needs to be added somewhere for it to be a fix :)

@fengzhou-msft I really suggest you only set this temporarily. People do stuff like this all the time - scripting installations where interaction is disabled - setting this permanently would be bad and invading. It would mean everyone installing the CLI on a Debian based distro will have all their services automatically restarted under their feet during updates (regardless of any Azure CLI updates), no questions asked. This is not the default, and it's absolutely not the path of least surprise. Silently changing this and making this the permanent choice for every Debian admin wanting to run azure CLI is not acceptable. It's just a random package - it absolutely should not change system settings as proposed. A temporary change for the scripted session that is the install is the way to go :)

**Comment by DavidLangworthy** [comment]
That was not my intent. Broadly, there are two ways to fix this issue, one is a doc fix which gives the user some extra step to take and one is a code fix which lets the user invoke the script as described.  I am recommending a code fix.  

You correctly note that the proposed code fix restarts the users services without warning or consent, which is not appropriate.  It would be best to ask the user inline as I assume is done when running this over ssh.

**Comment by fengzhou-msft** [comment]
Thanks for the discussion. I've tried setting `DEBIAN_FRONTEND` and it works. So I will put it in the script before running `apt-get install`. The setting won't persist if run with `bash` as documented and it's a code fix.
