### ISSUE TITLE
AZ CLI Support for RouteTable - Child of Virtual Hub

### ISSUE THREAD

**Issue by dedhar** [Azure/azure-cli#10792]
Resource Provider
What is the Azure resource provider your feature is part of?
NRP (Microsoft.Network)

Description of Feature or Work Requested
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
Virtual Hub is an existing top level resource. We want to add support for RouteTable which is child resource of Virtual Hub and needed in Firewall manager

Minimum API Version Required
What is the minimum API version of your service required to implement your feature?
Nrp API Version 07-01-2019 but Swagger API Version is 09-01-2019

Swagger Link
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

https://github.com/Azure/azure-rest-api-specs/blob/6d05a76a8b2119c83f5fd99c812ad0b8752649b1/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/virtualWan.json#L2906

Target Date
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

We are planning on making the announcement for this new resource and service at 2019 Ignite. Target date 11/4/2019

**Comment by MyronFanQiu** [comment]
@dedhar We will make a plan for it and let you know the ETA latter.

**Comment by MyronFanQiu** [comment]
https://github.com/Azure/azure-cli-extensions/pull/1020 please check.
