### ISSUE TITLE
Updating app display name does not seem to work

### ISSUE THREAD

**Issue by johnhof** [Azure/azure-cli#10807]
## Describe the bug

Updating app displayName does not seem to work.

**Command Name**

`az ad app update`

**Errors:**

No errors logged.

## To Reproduce:

- `az ad app create --display-name "tmp"`
- `az ad app update --id {} --display-name "tmp - renamed" --debug`
- `az ad app show --id {}`
- Observe that `displayName` still reads `tmp`

## Expected Behavior

The apps display name should be changed from `tmp` to `tmp - renamed`

## Environment Summary

```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.74
```
## Additional Context

The debug logs show that the `PATCH` request still submits `"displayName": "tmp"`. My guess is that the `--display-name` flag is being overwritten somewhere client side.

**Comment by yonzhan** [comment]
@jiasli please take a look.

**Comment by jiasli** [comment]
The issue is fixed. Thanks for the feedback.
