### ISSUE TITLE
MacOs catalina is not supported

### ISSUE THREAD

**Issue by swapnild2111** [Azure/azure-cli#10814]
Hello Team,

I upgraded my MacOS to Catalina and `az aks` stopped working. I do not see `aks` option anymore.
Does azure-cli supports this new version of MacOS or is there any plan to release its support?

Best regards,
Swapnil

**Comment by yonzhan** [comment]
@fengzhou-msft  please take a look.

**Comment by fengzhou-msft** [comment]
@swapnild2111 can you tell me more about how you installed azure-cli, what is the version you use(are you able to run `az --version`)?

**Comment by swapnild2111** [comment]
I have installed `az` with `homebrew` on mac.
`$az --version   
azure-cli (2.0.17)

acr (2.0.11)
acs (2.0.15)
appservice (0.1.16)
batch (3.1.3)
billing (0.1.4)
cdn (0.0.8)
cloud (2.0.7)
cognitiveservices (0.1.7)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.4)
container (0.1.10)
core (2.0.16)
cosmosdb (0.1.12)
dla (0.0.11)
dls (0.0.13)
eventgrid (0.1.3)
extension (0.0.2)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.9)
iot (0.1.11)
keyvault (2.0.10)
lab (0.0.10)
monitor (0.0.9)
network (2.0.14)
nspkg (3.0.1)
profile (2.0.12)
rdbms (0.0.6)
redis (0.2.8)
resource (2.0.14)
role (2.0.11)
servicefabric (0.0.3)
sf (1.0.8)
sql (2.0.11)
storage (2.0.15)
vm (2.0.14)

Python location '/Users/swapnil/lib/azure-cli/bin/python'
Extensions directory '/Users/swapnil/.azure/cliextensions'

Python (Darwin) 2.7.16 (default, Aug 24 2019, 18:37:03)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s

Legal docs and information: aka.ms/AzureCliLegal`

**Comment by fengzhou-msft** [comment]
2.0.17 is quite old now. Please run `brew upgrade azure-cli` to upgrade to the latest version.

**Comment by swapnild2111** [comment]
Thank you :)
