### ISSUE TITLE
Bug: Minor typo for list command help when using "az sql midb --help"

### ISSUE THREAD

**Issue by blmeyers** [Azure/azure-cli#10817]
## Describe the bug

**Command Name**
`az sql midb`

**Errors:**
Typo in the help documentation shown for the az sql midb list command, "maanged databases" instead of "managed databases".

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az sql midb --help`
- `az sql midb list --help`

## Expected Behavior
Docs updated to "managed databases"
## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.74

Extensions:
interactive 0.4.3

```
## Additional Context
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py/#L521 seems to be the doc definition.

**Comment by haroldrandom** [comment]
Partially fixed, typo problom in #10825

**Comment by jaredmoo** [comment]
Where is the remaining typo that isn't fixed?

**Comment by jaredmoo** [comment]
I am closing because it seems to be fixed. Please reopen or file a new issue if you see any more typos that can be fixed :)
