### ISSUE TITLE
Update samples repo

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#1081]
Generate content for our Samples repo: https://github.com/Azure/azure-cli-samples
- General
  - [ ] Landing page
  - [ ] Using account (login, logout, account set, account list, configure)
  - [ ] Using --query and JMESPath
  - [ ] Using --output
  - [ ] Automating the CLI
- Services
  - [ ] Network
  - [ ] Compute (VM and VMSS)
  - [x] Storage
  - [ ] RBAC and AD
  - [ ] ARM 
  - [ ] App Service and Web App
  - [ ] KeyVault
  - [ ] Insights
- Scenarios
  - TBD, anything that isn't likely to be covered by the service sample

**Comment by johanste** [comment]
Since this is not directly related to work required for the Azure CLI 2.0, I'm closing this. Feel free to open an issue somewhere else if this is for personal work item tracking.
