### ISSUE TITLE
Firewalls and virtual network blob on a storage account show authentication error rather than firewall error

### ISSUE THREAD

**Issue by lufussel** [Azure/azure-cli#10815]
## Describe the bug

**Command Name**
`az storage container create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 132, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container create --name {} --account-name {}`

## Environment Summary
```
Linux-4.15.0-1059-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.74

Extensions:
aks-preview 0.4.5
storage-preview 0.2.8

```

**Comment by lufussel** [comment]
"Storage Blob Data Contributor" role is assigned to the user. Containers create without firewall rules, but are blocked when locked by firewall. Error message is not accurate.

**Comment by Juliehzl** [comment]
Hi @lufussel, thanks for your feedback. What you said is really right. I think you are unblocked now with root cause found, right? We will improve error message for firewall scenario.

**Comment by Juliehzl** [comment]
Hi @lufussel, given there is no response for a long time, I will close the issue and error message should already be update. If there is any issue, feel free to create a new one.
