### ISSUE TITLE
Auth instructions result in unrecognized arguments

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-cli#10828]
The instructions [here](https://github.com/Azure/azure-libraries-for-net/blob/master/AUTH.md) for creating a SP results in an error

> az: error: unrecognized arguments: --sdk-auth

Here's the call:

> D:\Repos\> az ad sp create-for-rbac --sdk-auth > my.azureauth
> az: error: unrecognized arguments: --sdk-auth
> usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
>           [--query JMESPATH]
>           {ad} ...

azure-cli (2.0.9)

**Comment by yaohaizh** [comment]
CLI issue, not sure if this is reproed.

**Comment by yonzhan** [comment]
@jiasli please take a look.

**Comment by jiasli** [comment]
Please update to the latest version. 

```
az ad sp create-for-rbac -h

--sdk-auth        : Output result in compatible with Azure SDK auth file.  Allowed values:
                    false, true.
```
`--sdk-auth` should be used with `false, true`.

So the command is like
```
>az ad sp create-for-rbac --sdk-auth true --skip-assignment

{
  "clientId": "",
  "clientSecret": "",
  "subscriptionId": "",
  ...
}
```
