### ISSUE TITLE
Can't access blob storage from AZ CLI

### ISSUE THREAD

**Issue by andrePKI** [Azure/azure-cli#10826]
## Describe the bug
Account is signed in correctly, has the appropriate roles. However commands fail with "You do not have the required permissions" and listing roles the account is member of

**Command Name**
`az storage blob upload`

**Errors:**
```

C:\WINDOWS\system32>az logout

C:\WINDOWS\system32>az login -u dataman@adhoekstra.ddns.net -p <erased>
[
  {
    "cloudName": "AzureCloud",
    "id": "b069085a-22df-4c6f-ab7e-f4f6f1d52d48",
    "isDefault": true,
    "name": "Pay-As-You-Go",
    "state": "Enabled",
    "tenantId": "cb356271-ecee-4f09-8c38-3a98bb49b3dd",
    "user": {
      "name": "DataMan@adhoekstra.ddns.net",
      "type": "user"
    }
  }
]

C:\WINDOWS\system32>az role assignment list --all
[
  {
    "canDelegate": null,
    "id": "/subscriptions/b069085a-22df-4c6f-ab7e-f4f6f1d52d48/resourceGroups/throw-away/providers/Microsoft.Storage/storageAccounts/koffiestorage/providers/Microsoft.Authorization/roleAssignments/a7ef4aa0-fa19-40ab-ae8e-d397de65a166",
    "name": "a7ef4aa0-fa19-40ab-ae8e-d397de65a166",
    "principalId": "caa984b3-ddc2-4359-b1e3-6b94a91d6acb",
    "principalName": "DataMan@adhoekstra.ddns.net",
    "principalType": "User",
    "resourceGroup": "throw-away",
    "roleDefinitionId": "/subscriptions/b069085a-22df-4c6f-ab7e-f4f6f1d52d48/providers/Microsoft.Authorization/roleDefinitions/17d1049b-9a84-46fb-8f53-869881c3d3ab",
    "roleDefinitionName": "Storage Account Contributor",
    "scope": "/subscriptions/b069085a-22df-4c6f-ab7e-f4f6f1d52d48/resourceGroups/throw-away/providers/Microsoft.Storage/storageAccounts/koffiestorage",
    "type": "Microsoft.Authorization/roleAssignments"
  }
]

C:\WINDOWS\system32>az storage blob upload --file "c:\Temp\2019_5_10_nota.pdf" -c docs -n nota.pdf --account-name koffiestorage --account-key pa6HqkvTvY8ujjbc39lS67CbIfBlNdo82ai7DtgOZ1bjCQJG1iu9dz8/fy9bljNIUhGLwaIayKAVt2j85UDOng==

You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.

The command failed with an unexpected error. Here is the traceback:

'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\cli.py", line 212, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\output.py", line 132, in out
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\output.py", line 38, in format_json
TypeError: 'CommandResultItem' object is not iterable

To open an issue, please run: 'az feedback'

C:\WINDOWS\system32>az storage blob list --account-name koffiestorage -c docs --account-key pa6HqkvTvY8ujjbc39lS67CbIfBlNdo82ai7DtgOZ1bjCQJG1iu9dz8/fy9bljNIUhGLwaIayKAVt2j85UDOng==

You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.

The command failed with an unexpected error. Here is the traceback:

'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\cli.py", line 212, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\output.py", line 132, in out
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\output.py", line 38, in format_json
TypeError: 'CommandResultItem' object is not iterable

To open an issue, please run: 'az feedback'


C:\WINDOWS\system32>az storage account keys list --account-name koffiestorage
[
  {
    "keyName": "key1",
    "permissions": "Full",
    "value": "K/n3hLaabpX7WWYvjbGtfqd8VmhOFKYwr6weC4p7QGL0Xa73bf3Sj78OARIEl3WyX6yqFEhIvtyzFn+xOMyQCg=="
  },
  {
    "keyName": "key2",
    "permissions": "Full",
    "value": "RpRlEa5URBXRlmSe1npMHBb2ZbRqTBpRCNlMG513PTgx5eCzmueRKVvriXsLP6d9IRc3rGS1alwzgem+317m3Q=="
  }
]

C:\WINDOWS\system32>az storage container list --account-name koffiestorage --account-key pa6HqkvTvY8ujjbc39lS67CbIfBlNdo82ai7DtgOZ1bjCQJG1iu9dz8/fy9bljNIUhGLwaIayKAVt2j85UDOng==

You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.

The command failed with an unexpected error. Here is the traceback:

'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\cli.py", line 212, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\output.py", line 132, in out
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-6e754znd\knack\knack\output.py", line 38, in format_json
TypeError: 'CommandResultItem' object is not iterable

To open an issue, please run: 'az feedback'

C:\WINDOWS\system32>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload {} --account-name {} --account-key {}`
and see transcript above
## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.74

```

**Comment by Juliehzl** [comment]
@andrePKI Please don't show up your storage account key in github.  To upload a file, you need ""Storage Blob Data Contributor"  not  "Storage Account Contributor" role. In addition, when you already have the account key, no matter what role you have for the storage account, you should have the permission to the storage account.
From your posted information, can you check the storage account key again? For storage account koffiestorage, you should use:
` az storage container list --account-name koffiestorage --account-key "K/n3hLaabpX7WWYvjbGtfqd8VmhOFKYwr6weC4p7QGL0Xa73bf3Sj78OARIEl3WyX6yqFEhIvtyzFn+xOMyQCg=="`
or
`az storage blob upload -c test -n test -f a.txt --account-name koffiestorage --account-key "K/n3hLaabpX7WWYvjbGtfqd8VmhOFKYwr6weC4p7QGL0Xa73bf3Sj78OARIEl3WyX6yqFEhIvtyzFn+xOMyQCg=="`

**Comment by andrePKI** [comment]
No worries - I rotated the keys ;-)
I already added the Storage Account Data Contributor role - but somehow didn't find the expected results... When trying today with a fresh mind, I found:
`C:\WINDOWS\system32>az role assignment list --all
Principal                    Role                                       Scope
---------------------------  -----------------------------------------  ---------------------------------------------------------------------------------------------------------------------------------------
DataMan@adhoekstra.ddns.net  Storage Account Contributor                /subscriptions/{subsid}/resourceGroups/throw-away/providers/Microsoft.Storage/storageAccounts/koffiestorage
DataMan@adhoekstra.ddns.net  Storage Account Key Operator Service Role  /subscriptions/{subsid}/resourceGroups/throw-away/providers/Microsoft.Storage/storageAccounts/koffiestorage
DataMan@adhoekstra.ddns.net  Storage Blob Data Contributor              /subscriptions/{subsid}/resourceGroups/throw-away/providers/Microsoft.Storage/storageAccounts/koffiestorage`
and I could upload/list/delete blobs ;-) 
`C:\WINDOWS\system32>az storage blob upload -c docs -n nota.pdf -f c:\temp\2019_5_10_nota.pdf --account-key {key} --account-name koffiestorage
Finished[#############################################################]  100.0000%
LastModified
-------------------------
2019-10-14T07:52:55+00:00

C:\WINDOWS\system32>az storage blob list -c docs --account-key {key} --account-name koffiestorage
Name      Blob Type    Blob Tier    Length    Content Type     Last Modified              Snapshot
--------  -----------  -----------  --------  ---------------  -------------------------  ----------
nota.pdf  BlockBlob    Hot          148076    application/pdf  2019-10-14T07:52:55+00:00

C:\WINDOWS\system32>az storage blob delete -c docs -n nota.pdf --account-key {key} --account-name koffiestorage

C:\WINDOWS\system32>
`
