### ISSUE TITLE
az monitor alert and action group

### ISSUE THREAD

**Issue by arianpopalyar** [Azure/azure-cli#10837]
**Resource Provider**
I want to be able to create alert and link it to the action  group
**Description of Feature or Work Requested**
current documentation gives you example of setting alert but with webhook, I want to use the default feature of sending email and sms.
all the example code that i come up with did not work for example this one will only create the alert 
![image](https://user-images.githubusercontent.com/3668538/66765837-a615bb00-eea4-11e9-940f-345876505299.png)
but does not actually link it to the alert group

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

**Comment by MyronFanQiu** [comment]
@arianpopalyar  Hello. we had another feature request about alertmanagement days ago. This feature request may be related with that one. We had a discussion with service team trying to create a new umbrella called "monitor alert". It may have impact on this feature and I will update the status  later in this issue.

**Comment by arianpopalyar** [comment]
@MyronFanQiu thanks for that, I will be looking forward to your response, about this in future.

**Comment by yonzhan** [comment]
add to S170

**Comment by jsntcy** [comment]
@arianpopalyar, 
- `az monitor activity-log alert create --action-group` already supports sending email and sms by linking to action group, could you explain why it doesn't work for you?
- Also could you explain "but does not actually link it to the alert group"? I don't find "alert group" in monitor.

**Comment by jsntcy** [comment]
@arianpopalyar, any update on this issue.

**Comment by jsntcy** [comment]
Close this now as no response is from customer for a long time.
@arianpopalyar, if you think the issue still exists, please reopen this issue.
