### ISSUE TITLE
az find

### ISSUE THREAD

**Issue by billbertrand** [Azure/azure-cli#10839]
## Describe the bug
The azure training has the user issue "az find blob" in the cli.  I will check proxy settings
**Command Name**
`az find blob`

**Errors:**
```
HTTPSConnectionPool(host='app.aladdin.microsoft.com', port=443): Max retries exceeded with url: /api/v1.0/examples?query=blob&clientType=AzureCli&context=%7B%22sessionId%22%3A+%22bd8d2d10-83b5-47e0-8ace-0a341e29dd98%22%2C+%22subscriptionId%22%3A+null%2C+%22clientRequestId%22%3A+%22c176663a-eeb4-11e9-8b26-983b8f8c9299%22%2C+%22installationId%22%3A+%2208936626-eeb2-11e9-b4c0-983b8f8c9299%22%2C+%22versionNumber%22%3A+%222.0.74%22%7D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x07CF8B90>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
Traceback (most recent call last):
pip-install-hn3yvyc1\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az find {}`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.74

```

**Comment by jiasli** [comment]
This issue is caused by app.aladdin.microsoft.com temporarily being unavailable and is now resolved.

**Comment by HujinoKun** [comment]
> [@jiasli](https://github.com/jiasli) What is 'app.aladdin.microsoft.com'? I can't find any documentation on it.

Hello,

I think this is used for an Asset Lifecycle Management solution
