### ISSUE TITLE
Cannot move blob to different tier using "az storage blob set-tier" in Azure CLI

### ISSUE THREAD

**Issue by grimstoner** [Azure/azure-cli#10836]
## Describe the bug

**Command Name**
`az storage blob set-tier`

**Errors:**
```
The value for one of the HTTP headers is not in the correct format. ErrorCode: InvalidHeaderValue
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.
RequestId:77940443-501e-001d-42a2-82e0e2000000
Time:2019-10-14T15:17:52.4501571Z</Message><HeaderName>x-ms-access-tier</HeaderName><HeaderValue>Archive</HeaderValue></Error>
Traceback (most recent call last):
...
RequestId:77940443-501e-001d-42a2-82e0e2000000
Time:2019-10-14T15:17:52.4501571Z</Message><HeaderName>x-ms-access-tier</HeaderName><HeaderValue>Archive</HeaderValue></Error>
```

## To Reproduce:
Nothing funny... just tried to move a blob to the archive tier.

- `az storage blob set-tier --account-name {} --container-name {} --name {} --tier {}`

## Expected Behavior
The selected blob is moved to the specified tier.

## Environment Summary
```
Linux-4.15.0-1060-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.74

```

**Comment by Juliehzl** [comment]
Hi @grimstoner, I try to reproduce your issue but failed. Can you provide more information for your scenario? e.g. storage account type and blob type. 
Through your error message, it shows that the access tier value you want to set is invalid, which is "Archive". But it should be valid. It will help a lot if you can also provide more debug information with  `--debug` in your command.

**Comment by grimstoner** [comment]
According to Microsoft support, this is due to the Archive tier not begin supported in the region where the storage account is hosted.

**Comment by suterma** [comment]
I can confirm this works in UK West Location.
