### ISSUE TITLE
webapp: Cannot create app

### ISSUE THREAD

**Issue by nitishrsingh** [Azure/azure-cli#10844]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
validation error: Parameter 'ResourceGroup.location' can not be None.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up -n {}`

## Environment Summary
```
Linux-4.15.0-1060-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.74 *

```

**Comment by panchagnula** [comment]
@nitishrsingh apologize for the delay in the response here.
We had a regression in az webapp up with 2.0.74, can you re-try with the latest version 2.0.75?
If the latest version doesn't fix this as well, please share the following info:
1. Are you running this command with an existing webapp? or trying to Create a new one?
2. Run the command with --debug & see if you get some more useful info.

Thanks

**Comment by panchagnula** [comment]
Please reactivate if this still repros with the info for the question above. Thanks!
