### ISSUE TITLE
Incorrect english in warning message

### ISSUE THREAD

**Issue by Petermarcu** [Azure/azure-cli#10849]
c:\>az login
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"

Should be:
Note, we have launched a browser for you to login. For the old experience with device code, use "az login --use-device-code"

**Comment by kishdubey** [comment]
Hello,
I have just started to look into this issue. You should be expecting a pull request within the next few minutes. Thanks!

**Comment by kishdubey** [comment]
@jiasli thank you for letting us know. Would you like for the warning to be completely removed in the PR?

**Comment by yonzhan** [comment]
PR is merged.
