### ISSUE TITLE
az ad app update --id OBJID --remove replyUrls "http://my-reply-url" fails

### ISSUE THREAD

**Issue by trevonmckay** [Azure/azure-cli#10845]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I am unable to remove a reply URL from an Azure AD app, I receive the error 
```
az : ERROR: invalid syntax: --remove property.list <indexToRemove> OR --remove propertyToRemove
At line:6 char:4
+    az ad app update --id 3bff69b3-2b49-4d89-8247-a5cc1b0fce99 --remov ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: invalid ...ropertyToRemove:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**To Reproduce**
```
$replyUrl = "https://existingreplyurl.co"
az ad app update --id OBJ-ID --remove replyUrls $replyUrl
```

**Expected behavior**
The item to be removed from the replyUrls array

**Environment summary**
```
azure-cli                         2.0.74 *

command-modules-nspkg              2.0.3
core                              2.0.74 *
nspkg                              3.0.4
telemetry                          1.0.3 *

Extensions:
azure-devops                      0.11.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\trevo\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
```
**Additional context**
#9895

**Comment by jiasli** [comment]
As the error suggests: `--remove property.list <indexToRemove> OR --remove propertyToRemove`, `--remove` can only remove by index or the whole property. For example:

https://github.com/Azure/azure-cli/blob/5377c20e9651e629a2522527d988a6037c901eb6/src/azure-cli/azure/cli/command_modules/role/tests/latest/test_graph.py#L162

It doesn't support remove by value.
