### ISSUE TITLE
[AppGw] Rewrite rule set can't be associated with Request routing rules

### ISSUE THREAD

**Issue by sai-manoj-kumar** [Azure/azure-cli#10854]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

Support request for reference: https://azuresupportcenter.msftcloudes.com/caseoverview?srId=119100425000173

**Describe the bug**
Application Gateway RewriteRuleSet can not be referenced in requestRoutingRule.
Similar to the backendPool, Listener, and HttpSettings, users should be able to *update* a requestRoutingRule with a RewriteRuleSet. Same for the UrlPathMap and PathRules in UrlPathMap.

**To Reproduce**
For the command, 
az network application-gateway rule update,
there is no option called "--rewrite-rule-set"

For this command,
az network application-gateway url-path-map update,
there is no option to add rewrite rule set.

There is no command to update an existing Path Rules to add a rewrite rule set.

**Expected behavior**
Explained above

**Environment summary**
Azure Cloud Shell

**Comment by MyronFanQiu** [comment]
@sai-manoj-kumar Thanks. I'm a little bit busy right now. I will take a look later to check the reasons.

**Comment by PaulCharlton** [comment]
+1

**Comment by sai-manoj-kumar** [comment]
@MyronFanQiu Thanks for looking into this. Could you assign a milestone in which it may be picked up?

**Comment by MyronFanQiu** [comment]
@sai-manoj-kumar Hello. I put this into the S162. I might be able to solve it in the following milestone.
