### ISSUE TITLE
Error with no reason

### ISSUE THREAD

**Issue by microkost** [Azure/azure-cli#10857]
I experienced the following error:

az : 
At C:\dev\azure\test.ps1:12 char:1
+ az storage file upload --share-name shname --account-name ...
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
Alive[################################################################]  100.0000%
Finished[#############################################################]  100.0000%

Command: 
az storage file upload --share-name shname --path file.txt --source ".\content.txt" --account-name "$STORAGEACCT" --account-key "$STORAGEKEY"

**It upload file, it is working**, just there is error "FullyQualifiedErrorId : NativeCommandError"

**Comment by Juliehzl** [comment]
Hi @microkost, this command works well in cmd and PS without variable. I am not sure about if it is a PS client issue because you are using PS script. 
Can you try this command in PS not using script again?

**Comment by rfoltz** [comment]
I have this exact same error as well when using a similar storage command in a PS script, but I'm using the `az storage blob download-batch` command instead.

I can also confirm that running the command outside the script doesn't response with this error but in my case this error doesn't actually make the command stop it still downloads everything from the container. Should we be moving to the Azure Powershell module instead?

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
@microkost  could you add `--only-show-errors` in your command with latest azure cli? I am thinking that it may be caused that stderr string is converted to a NativeCommandError object and cli warning will be write to stderr.
