### ISSUE TITLE
Aladdin: Add help and examples to failed commands/groups

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#10868]
For more context, contact JasonSha

Current experience
```
$ az tag
az tag: error: the following arguments are required: _subcommand
usage: az tag [-h] {list,create,delete,add-value,remove-value} ...
$
```

Proposed experience for Groups
```
$ az tag
az tag: error: the following arguments are required: _subcommand
usage: az tag [-h] {list,create,delete,add-value,remove-value} ...

Here are the most common ways to use [az tag]:

Creates a tag in the subscription. (autogenerated)
az tag create --name MyTag

Deletes a tag from the subscription. (autogenerated)
az tag delete --name MyTag

Creates a tag value. (autogenerated)
az tag add-value --name MyTag --value {value}

$
```

Proposed experience for Commands
```
$ az tag add-value -s sa
az tag add-value: error: the following arguments are required: --name/-n, --value
usage: az tag add-value [-h] [--verbose] [--debug]
                        [--output {json,jsonc,table,tsv,yaml,none}]
                        [--query JMESPATH] [--subscription _SUBSCRIPTION]
                        --name TAG_NAME --value TAG_VALUE

Did you mean:
   az tag add-value --name MyTag --value {value}

```

**Comment by JasonRShaver** [comment]
@glGarg @albaloo

**Comment by Juliehzl** [comment]
Hi @JasonRShaver, according to  your request, I think maybe you hope we can throw out more accurate error message, right? Especially when incorrect parameters usage, CLI should give correct guide? You suggestion is really good!

**Comment by yonzhan** [comment]
add to S171

**Comment by zhoxing-ms** [comment]
@achandmsft This issue seems to help optimize error messages more accurately and recommend executable commands. This topic is similar to our recent OKR of optimizing error output. Do we have any plans for this topic in the near future?

**Comment by zhoxing-ms** [comment]
@JasonRShaver May I ask whether the Aladdin extension of `ai-did-you-mean-this` is designed to support this requirement? What do you need from the CLI side?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
