### ISSUE TITLE
az login error

### ISSUE THREAD

**Issue by alibutt30** [Azure/azure-cli#10860]
**Command Name**
`az login`

**Errors:**
```
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`

## Expected Behavior
Expect list of subscriptions

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.72 *

```
## Additional Context

The command used to work fine till yesterday. Today is giving this error.

**Comment by yonzhan** [comment]
@jiasli planned in next Sprint.

**Comment by jiasli** [comment]
Please see [the doc for using CLI behind a proxy](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy). We have also improved the error message.
