### ISSUE TITLE
AZ CLI Support : Add flag Internet-Security to ExpressRouteGatewayConnection

### ISSUE THREAD

**Issue by dedhar** [Azure/azure-cli#10863]
Can we also add support for enableInternetSecurity property to the following command? The customer facing property would have name internet-security
https://docs.microsoft.com/en-us/cli/azure/ext/express-route/network/express-route/gateway/connection?view=azure-cli-latest#ext-express-route-az-network-express-route-gateway-connection-create

EnableInternetSecurity is a property on VpnConnection, ExpressRouteGatewayConnection and HubVnetConnection resource.
https://github.com/nagula-ritvika/azure-rest-api-specs/blob/cff16424eb313b92bfc4780101a55711b813d219/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/virtualWan.json#L3647
https://github.com/nagula-ritvika/azure-rest-api-specs/blob/cff16424eb313b92bfc4780101a55711b813d219/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/virtualWan.json#L3838
https://github.com/nagula-ritvika/azure-rest-api-specs/blob/cff16424eb313b92bfc4780101a55711b813d219/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/expressRouteGateway.json#L602

We already have support for the property on VpnConnection and HubVnetConnection. We need to add support for ExpressRouteGatewayConnection.
https://docs.microsoft.com/en-us/cli/azure/ext/virtual-wan/network/vhub/connection?view=azure-cli-latest#ext-virtual-wan-az-network-vhub-connection-create
https://docs.microsoft.com/en-us/cli/azure/ext/virtual-wan/network/vpn-gateway/connection?view=azure-cli-latest#ext-virtual-wan-az-network-vpn-gateway-connection-create

**Comment by MyronFanQiu** [comment]
@dedhar. Hello. I will try my best

**Comment by MyronFanQiu** [comment]
https://github.com/Azure/azure-cli/pull/10992 merged. Please check.
