### ISSUE TITLE
'KeyError' after running 'az login'

### ISSUE THREAD

**Issue by yuyalush** [Azure/azure-cli#1086]
I have seen the following error after runnning "az login".
This message was displayed after devicelogin page.

I use bash on Ubuntu on Windows(build 14393.321)

> pakue@DESKTOP-TPETLAO:~$ az login
> To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code GGV286GQY to authenticate.
> 'userId'
> Traceback (most recent call last):
>   File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/main.py", line 35, in main
>     cmd_result = APPLICATION.execute(args)
>   File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 120, in execute
>     result = expanded_arg.func(params)
>   File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/core/commands/**init**.py", line 229, in _execute_command
>     result = operation(client, **kwargs) if client else operation(**kwargs)
>   File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/command_modules/profile/custom.py", line 58, in login
>     tenant)
>   File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 88, in find_subscriptions_on_login
>     self._management_resource_uri)
>   File "/usr/local/az/local/lib/python2.7/site-packages/azure/cli/core/_profile.py", line 274, in find_through_interactive_flow
>     self.user_id = token_entry[_TOKEN_ENTRY_USER_ID]
> KeyError: 'userId'

**Comment by yugangw-msft** [comment]
what kind of user account you are using? Live id, org-id?
This error indicates the token returned from AAD has no "use name" field, which is very unusual...

**Comment by yuyalush** [comment]
When I used Microsoft Account, I got error.

**Comment by benjguin** [comment]
same for me with my org account (@microsoft.com)

**Comment by mayurid** [comment]
@yuyalush and @benjguin : Could you guys run the command with the --debug option and share the logs? We can investigate more with those.

**Comment by benjguin** [comment]
Sure
Do you have an @microsoft.com address.
The result contains tokens…

☺
Benjamin

**Comment by yugangw-msft** [comment]
Please send over to yugangw at microsoft dot com

**Comment by yugangw-msft** [comment]
Issue is repro'd. 
No repro'd on python 3.5 in a windows box, butrepro'd in osx with 2.7. 
Some non ansi characters in user full name causes decoding errors on JWT token blobs.
ETA, fix by upcoming release.

**Comment by yugangw-msft** [comment]
To get unblocked soon, use the nightly drop tomorrow: 
https://github.com/Azure/azure-cli/blob/master/doc/nightly/installing_nightly.md
