### ISSUE TITLE
Ability to associate application-gateway rewrite-rule sets to request routing rules

### ISSUE THREAD

**Issue by nesteffe** [Azure/azure-cli#10869]
I am unable to find a way to associate a rewrite rule set to a request routing rule using the CLI. I am not sure if I am just missing this or if it was an oversight when the rewrite-rule commands were added.

I believe the rule create & update commands should have a rewrite-rule-set-name switch or something similar. For example:

`az network application-gateway rule update -g MyResourceGroup --gateway-name MyAppGateway -n MyRule --rewrite-rule-set-name MyRewriteRuleSet`

I read in another issue about the --add and --set switches for the update commands that appear to allow setting arbitrary properties on the underlying objects but I can't seem to figure out how to make them work, or if this is even an appropriate use case for these methods.

In powershell the New/Set-AzApplicationGatewayRequestRoutingRule commands have a -RewriteRuleSet switch to make this association, but it doesn't appear this is surfaced in the CLI.

**Comment by PaulCharlton** [comment]
+1

**Comment by MyronFanQiu** [comment]
@nesteffe Hello. Is this issue similar with this one? https://github.com/Azure/azure-cli/issues/10854

**Comment by nesteffe** [comment]
> @nesteffe Hello. Is this issue similar with this one? #10854

Yes, this is the same issue. Sorry, that issue didn't show up when I was searching for this earlier today.

**Comment by MyronFanQiu** [comment]
@nesteffe oh. No problem. I just want to double check. We can leave this issue open. I'm quite busy right now for the Ignite. So I may need some time to take a look at this issue later. I'm sorry for it.

**Comment by HeShaobo1** [comment]
hi all,

you can use Azure PowerShell by solving this probem. 

$requestHeaderConfiguration = New-AzApplicationGatewayRewriteRuleHeaderConfiguration -HeaderName "Strict-Transport-Security" -HeaderValue "max-age=3600"
$actionset = New-AzApplicationGatewayRewriteRuleActionSet -RequestHeaderConfiguration $requestHeaderConfiguration
$rewriterule = New-AzApplicationGatewayRewriteRule -Name hsts -ActionSet $actionset             
$rewriteruleset = New-AzApplicationGatewayRewriteRuleSet -Name hsts1rewriteruleset -RewriteRule $rewriterule 

#获取当前的APPGW
$appgw = Get-AzApplicationGateway -Name appgwv2 -ResourceGroupName shawnbian 

#获取当前需要添加重写的规则rule
$reqRoutingRule = Get-AzApplicationGatewayRequestRoutingRule -ApplicationGateway $appgw     

#将创建的重写规则集关联到此APPGW上，并配置生效
Add-AzApplicationGatewayRewriteRuleSet -ApplicationGateway $appgw -Name requestHeaderRewrite -RewriteRule $rewriteRuleSet.RewriteRules
Set-AzApplicationGateway -ApplicationGateway $appgw 

#将APPGW 所关联的重写规则集和路由规则rule 关联
**$reqRoutingRule.RewriteRuleSet = $appgw.RewriteRuleSets[0] 
$appgw.RequestRoutingRules[0]=$reqRoutingRule**    

#使配置生效
Set-AzApplicationGateway -ApplicationGateway $appgw  

#检查当前路由规则所使用的重写规则集：

$appgw = Get-AzApplicationGateway -Name appgwv2 -ResourceGroupName shawnbian
$appgw.RewriteRuleSets

**Comment by MyronFanQiu** [comment]
This issue has been fixed in #11421.
