### ISSUE TITLE
Add cli support to expose Type in VirtualWan and Sku in VirtualHub 

### ISSUE THREAD

**Issue by nagula-ritvika** [Azure/azure-cli#10875]
**Resource Provider**
What is the Azure resource provider your feature is part of?
NRP (Microsoft.Network)

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
We have added a new property called Sku to VirtualHub and Type to VirtualWan and need these properties exposed. 

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
09-01-2019

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
1, Virtual Wan Type - [https://github.com/Azure/azure-rest-api-specs/blob/6d05a76a8b2119c83f5fd99c812ad0b8752649b1/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/virtualWan.json#L3180](https://github.com/Azure/azure-rest-api-specs/blob/6d05a76a8b2119c83f5fd99c812ad0b8752649b1/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/virtualWan.json#L3180)
2. Virtual Hub Sku - [https://github.com/Azure/azure-rest-api-specs/blob/6d05a76a8b2119c83f5fd99c812ad0b8752649b1/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/virtualWan.json#L3446](https://github.com/Azure/azure-rest-api-specs/blob/6d05a76a8b2119c83f5fd99c812ad0b8752649b1/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/virtualWan.json#L3446)

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
11/04/2019 if possible (not compulsory)

**Comment by MyronFanQiu** [comment]
@nagula-ritvika Thanks! We will try our best to finish it before Ignite.

**Comment by MyronFanQiu** [comment]
@nagula-ritvika Hello. What are the valid values for these two field separately? Could them be updated after the creation?

**Comment by yonzhan** [comment]
@nagula-ritvika any update for above questions ?

**Comment by nagula-ritvika** [comment]
@MyronFanQiu the valid values for both the fields can be **Basic** or **Standard**. The fields can be updated after creation too.

**Comment by MyronFanQiu** [comment]
Does the `type` in virtual wan also mean `sku`? Is it ok to expose `--sku` to represent `type` of the virtual wan? Or in the future, there will be other types.
