### ISSUE TITLE
Azure Key Vault Feature Request for Vendor Agnostic BYOK CLI Changes

### ISSUE THREAD

**Issue by amitbapat** [Azure/azure-cli#10876]
Dummy ticket

**Comment by yonzhan** [comment]
@jiasli this is dummy Ticket for Vendor Agnostic BYOK CLI Changes.

**Comment by yungezz** [comment]
code ready against private swagger/sdk, communicating with service team to get service readiness date.

**Comment by yungezz** [comment]
#12003 is part of the whole feature.

**Comment by bim-msft** [comment]
#11912 is another part, all BYOK changes will be released on Feb 18 officially.
