### ISSUE TITLE
Azure Key Vault Feature Request for Key Vault with managed HSM

### ISSUE THREAD

**Issue by amitbapat** [Azure/azure-cli#10877]
Dummy ticket

**Comment by yonzhan** [comment]
@jiasli this request is for Key Vault with managed HSM.

**Comment by yungezz** [comment]
move to later sprint due to previous priority change. working on it now.

**Comment by yungezz** [comment]
# 12328

**Comment by yungezz** [comment]
move to later Sprint, managed HSM control plane will be ready around April.

**Comment by yungezz** [comment]
move all MSHM related feature to backlog. current status is CLI feature ready for features with Swagger, but not released due to service not public yet. Public preview maybe around June/July timeline, but not locked down yet. Will close the issue when service public and CLI feature merged/released.

**Comment by bim-msft** [comment]
PR for Ignite has been merged. Closing this one.
