### ISSUE TITLE
"az webapp config ssl bind" wipes tags

### ISSUE THREAD

**Issue by kenoby-dev** [Azure/azure-cli#10881]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When "az webapp config ssl bind" command is run (including within the Azure Cloud Shell) the tags that were applied to the App Service are removed.

**To Reproduce**
- Apply tags to the App Service
- Run the "az webapp config ssl bind" command to bind a TLS certificate to the App Service
- Check the tags on the App Service

**Expected behavior**
The tags of the App Service should not be removed.  The tags should be maintained throughout this operation.

**Environment summary**
Cloud Shell (bash)

**Additional context**
We have tag policies applied in our environment.  Running this command and wiping the tags causes the resource to become non-compliant, preventing the command from being run.

**Comment by panchagnula** [comment]
will take a look, thanks for reporting.
