### ISSUE TITLE
az storage commands do not work on classic Storage accounts

### ISSUE THREAD

**Issue by chaami** [Azure/azure-cli#10899]
Hi,
These command are not working on the classic storage account.
That's a major blind spot.. is this expected or are you planning to add that in the future ?
Thanks and kind regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92115d19-d7a0-93a8-bf2b-5126d1cddcd0
* Version Independent ID: a657f09b-e1ac-12a2-4b9c-7aaa1f0e3f5c
* Content: [az storage account](https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az-storage-account-generate-sas)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Juliehzl** [comment]
Hi @chaami  you mean the examples don't work, right? Or can you describe your scenario in detail?

**Comment by chaami** [comment]
Hi @Juliehzl 
I thought I had put an example of commands facing the blind spot but I can't find them anywhere...
What I meant is that if you run a `Get-AzStorageAccount` on a subscription containing classic Storage accounts you will only get the Storage accounts and not the old ones.
I managed workaround the issue by using `New-AzStorageContext` with the connection string.
Kind regards.

**Comment by chaami** [comment]
Sorry,
I commented with the Azure PowerShell commands counterparts, but it's the same issue with the Azure cli:
```
 az storage account generate-sas --account-name legacyaccountname --service b --resource-types sco --permission rl --expiry 2019-10-19
```
Returns an error saying that the Storage account was not found, trying on a newer Storage accounts works as intended.
I didn't try to cook up a workaround with the Azure cli...

**Comment by yonzhan** [comment]
add to S171

**Comment by Juliehzl** [comment]
@chaami You are right. We doesn't support classic storage account any more.
