### ISSUE TITLE
'az network application-gateway create' doesn't work when associating WAF policy with AppGW.

### ISSUE THREAD

**Issue by KosukeHosoda** [Azure/azure-cli#10897]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.75

**Describe the bug**
'az network application-gateway create' doesn't work when associating WAF policy with AppGW.
we might have succeeded in creating AppGW associated with WAF policy when Azure CLI version was 2.0.70.

**To Reproduce**
You can repro when using the following commands.
*******
$lacation = "japaneast";
$vnetName = "AppGW-VNet";
$subnetName = "AppGW-Subnet";
$rgpVnetName = "AppGwGroup";
$rgpAppName = "AppGwGroup";
$apgwName = "Test-AppGW";
$wp_name = "${apgwName}-waf-policy01";
$sbntInfoId = $(az network vnet subnet show --name "${subnetName}" --vnet-name "${vnetName}" --resource-group "${rgpVnetName}" --query id --output tsv)
$publicip_name = $apgwName + "-ip";
az network public-ip create --name "${publicip_name}" --allocation-method "Static" --sku "Standard" --resource-group "${rgpVnetName}";
$publicIpId = $(az network public-ip show --name "${publicip_name}" --resource-group "${rgpVnetName}" --query id --output tsv)
az network application-gateway create `
    --name "${apgwName}" `
    --location "${lacation}" `
    --resource-group "${rgpAppName}" `
    --subnet "${sbntInfoId}" `
    --min-capacity 2 `
    --max-capacity 10 `
    --sku "WAF_v2" `
    --zones 1 2 3 `
    --http-settings-cookie-based-affinity Disabled `
    --frontend-port 80 `
    --http-settings-port 80 `
    --http-settings-protocol "Http" `
    --public-ip-address "${publicIpId}" `
    --waf-policy "${wp_name}"
*******

And then, you would encounter the following error message.
*******
Deployment failed. Correlation ID: c136dab2-a462-4268-8267-0f92d08cdb75. {
  "error": {-capacity 2 `
    "code": "ApplicationGatewayWithoutWafConfigurationCannotBeAddedWithCustomRuleOnlyFirewallPolicy",
    "message": "CustomRule only firewall policy /subscriptions/49dac445-53b8-451a-b1a0-e47c9fdc93d3/resourceGroups/AppGwGroup/providers/Microsoft.Network/ApplicationGatewayWebApplicationFir
ewallPolicies/Test-AppGW-waf-policy01 cannot be applied to an Application Gateway  /subscriptions/49dac445-53b8-451a-b1a0-e47c9fdc93d3/resourceGroups/AppGwGroup/providers/Microsoft.Network/
applicationGateways/Test-AppGW which doesnt have any WebApplicationFirewallConfiguration.",
*******

As per the error message it says "ApplicationGatewayWithoutWafConfigurationCannotBeAddedWithCustomRuleOnlyFirewallPolicy"

However, we are unable to set WAF mode enable because Azure CLI command can't set WAF mode as per the following document.
https://docs.microsoft.com/en-us/cli/azure/network/application-gateway?view=azure-cli-latest#az-network-application-gateway-create
 

**Expected behavior**
succeed in creating AppGW associated with WAF policy

**Environment summary**
Cloud shell / CLI version 2.0.75 / OS version / Shell Type : bash or PS

**Comment by haroldrandom** [comment]
Thanks for the feedback! We will make a plan for it.

**Comment by haroldrandom** [comment]
Once the feature [App Gateway WAF Ignite features](https://github.com/Azure/azure-cli/issues/11046) release, waf-policy have the capality to config those things and can apply among not only different application-gateways. Please have a try.

Feel free to reopen. If you have any futher question.

**Comment by haroldrandom** [comment]
Once 2.0.77 ( 20/11/2019 ) release, you can use

`az network applicate-gateway waf-policy ` to config a waf-policy. And waf-policy can work among multi applicatin-gateways.
You can:
1. Add pre-defined managed rules by `az network applicate-gateway waf-policy managed-rule rule-set`, lke SQL Injection pretection.
2. Add custom rule you would like to filter on your requests: `az network applicate-gateway waf-policy managed-rule custom-rule`
3. You can also configure this waf policy by `az network applicate-gateway waf-policy policy-setting`, configurable properties include: state, mode, request_body_check, max_request_body_size_in_kb and file_upload_limit_in_mb.

Sorry for the inconvenience and confusion.

Feel reopen to issue bug or feature if you have any futher question.
