### ISSUE TITLE
[Functions] Add support for Java on Linux in create flow

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#10905]
[Functions] Add support for Java on Linux in create flow

**Comment by ahmedelnably** [comment]
this only need to be added for Functions v3

cc/ @amamounelsayed @kulkarnisonia16

**Comment by yonzhan** [comment]
@amamounelsayed @kulkarnisonia16 how is the status of this issue?

**Comment by ahmedelnably** [comment]
This will be done in Q1 CY2020

**Comment by yonzhan** [comment]
@ahmedelnably If the CLI commands are contributed by service team and CLI team currently does not take over, we will mark the Service Attention label. Do you think it is not the case?
