### ISSUE TITLE
Error in az function identity assign example

### ISSUE THREAD

**Issue by OmegaMadLab** [Azure/azure-cli#10904]
There's an error in _az function identity assign_ command, that leads to a "wrong api" error.

The command:
_az functionapp identity assign -g MyResourceGroup -n MyUniqueApp --role reader --scope /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/MyResourceGroup_

should be corrected with:
_az functionapp identity assign -g MyResourceGroup -n MyUniqueApp --role reader --scope /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/**resourceGroups**/MyResourceGroup"_

Best regards,
Marco

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b8e3faa-175b-9296-4172-3976edfaa69b
* Version Independent ID: 6f52e30c-63e4-da3c-f3c6-da1f539f0d4d
* Content: [az functionapp identity](https://docs.microsoft.com/en-us/cli/azure/functionapp/identity?view=azure-cli-latest#az-functionapp-identity-assign)
* Content Source: [src/azure-cli/azure/cli/command_modules/appservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/_help.py)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ahmedelnably** [comment]
@panchagnula do you know if that is also the case for `az webapp identity assign`

**Comment by panchagnula** [comment]
Not that I know of - don't have any open issues for webapp & the unit test case for identity hasn't been failing. Thanks!

**Comment by SeaDude** [comment]
To piggy back onto this... I can't find any Azure documentation on the `--scope` syntax. What the format is, what permissions are granted for each level, etc. Does anyone have a resource that illustrates this?

**Comment by navba-MSFT** [comment]
@OmegaMadLab Apologies for the late reply. The above PR has been created for fixing the issue. It is currently under the review phase. In the meantime if you have any questions on this, please feel free to ask.

@SeaDude If you want to set it at the resource group level then here is the sample value for the `--scope `parameter /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroup/MyResourceGroup.
