### ISSUE TITLE
Unable to set Service Bus name space capacity to 8 using AZ

### ISSUE THREAD

**Issue by reddymaddi** [Azure/azure-cli#10912]
## Describe the bug

**Command Name**
`az servicebus namespace update`

**Errors:**
```
az servicebus namespace update: '8' is not a valid value for '--capacity'. See 'az servicebus namespace update --help'.

'int' object is not iterable
Traceback (most recent call last):
pip-install-qxmmnr17\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 549, in execute
pip-install-qxmmnr17\knack\knack\parser.py, ln 259, in parse_args
Azure\CLI2\lib\argparse.py, ln 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
Azure\CLI2\lib\argparse.py, ln 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
...
    s.set_seq2(word)
Azure\CLI2\lib\difflib.py, ln 279, in set_seq2
    self.__chain_b()
Azure\CLI2\lib\difflib.py, ln 311, in __chain_b
    for i, elt in enumerate(b):
TypeError: 'int' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az servicebus namespace update --name {} --resource-group {} --sku {} --capacity {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.72

```

**Comment by apraovjr** [comment]
@reddymaddi According to the documentation, the accepted values are 1,2,4 and is only applicable for premium namespace 
https://docs.microsoft.com/en-us/cli/azure/servicebus/namespace?view=azure-cli-latest#az-servicebus-namespace-update

**Comment by reddymaddi** [comment]
@apraovjr That's correct Document says the accepted values as 1,2,4 for premium namespace but portal allows to set the capacity to 8. see the attached image.

![SB capacity](https://user-images.githubusercontent.com/30122162/67296318-4a57bd00-f4b6-11e9-9798-b0e2c4c4de37.jpg)

**Comment by apraovjr** [comment]
@reddymaddi I will look into it and update accordingly. @axisc Do you know if we need to allow capacity change to 8 through cli?

**Comment by apraovjr** [comment]
@reddymaddi The `az servicebus` definately needs update after confirming from service bus team.Will open PR shortly for this.
