### ISSUE TITLE
Would it be possible to add an example showing how to use --additional-properties?

### ISSUE THREAD

**Issue by DaveAurionix** [Azure/azure-cli#10911]
I'm trying to set group membership TTL using az ad group member add with --additional-properties, but the syntax expected by --additional-properties isn't clear to me and the error messages from the tool aren't helping much.  I can't seem to find any documentation about the expected syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c659a298-8897-6d50-c1d9-c14a3b0e6364
* Version Independent ID: 2d2bec5b-ef92-f65f-bfd0-ccdabda52a41
* Content: [az ad group member](https://docs.microsoft.com/en-us/cli/azure/ad/group/member?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli please take a look after Ignite.

**Comment by jiasli** [comment]
is a result of 

https://github.com/Azure/azure-rest-api-specs/blob/a3182203860809ab5e9789ce032a42fc1b188fdc/specification/graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6/graphrbac.json#L3388

**Comment by DaveAurionix** [comment]
Thank you @jiasli
