### ISSUE TITLE
az sf cluster migrate vmss node disk storage to managed disks for consistency

### ISSUE THREAD

**Issue by jagilber** [Azure/azure-cli#10916]
az sf cluster
- migrate vmss node disk storage to managed disks for consistency.
- other service fabric deployment methods such as portal have been converted to managed disks.
- similar / same as documented [here](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-convert-template-to-md)
- submitting PR to convert windows and linux service fabric (sf) template.json to managed disks.

**Comment by qwordy** [comment]
https://github.com/Azure/azure-cli/pull/10918
Is this issue solved? @jagilber

**Comment by peterpogorski** [comment]
@jagilber is there any other information that you require?
