### ISSUE TITLE
Cannot login in AZ CLI from IIS

### ISSUE THREAD

**Issue by hermanknol123** [Azure/azure-cli#10910]
I can't seem to login from an DotNet Core application running in IIS (Windows 10) when setting the environment variable _"AzureServicesAuthConnectionString" to "RunAs=Developer; DeveloperTool=AzureCli"_

I am trying to access key-vault on Azure.

Used:
_https://docs.microsoft.com/nl-nl/azure/key-vault/service-to-service-authentication_ 
to set this.

The error i get is:
`Application startup exception: Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: RunAs=Developer; DeveloperTool=AzureCli, Resource: https://vault.azure.net, Authority: https://login.windows.net/**************************. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. ERROR: Please run 'az login' to setup account.`

I already executed 'az login' several times and when i open CMD or Azure CLI and run 
_az account get-access-token --resource=https://vault.azure.net_
i do get a token.

running from Visual Studio all works fine, but that does not use the Azure-CLI.

Anyone any ideas??

**Comment by yonzhan** [comment]
@jiasli please take a look after Ignite.

**Comment by jiasli** [comment]
It may be caused by IIS running the app under a different user context, thus CLI can't fetch the token of 
 the current user. Could you configure IIS and see if that works? https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#cant-retrieve-tokens-when-debugging-app-in-iis
