### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 using az webapp deployment source config-zip

### ISSUE THREAD

**Issue by sethjuarez** [Azure/azure-cli#10919]
## Describe the bug
When deploying from the az command line I am getting the following:

`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

This command was working properly before. 

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
pip-install-ygnynjtx\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 560, in execute
cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
cli\core\commands\__init__.py, ln 611, in _run_job
Temp\pip-install-ygnynjtx\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 588, in _run_job
cli\core\commands\__init__.py, ln 297, in __call__
azure\cli\core\__init__.py, ln 461, in default_command_handler
...
    return _default_decoder.decode(s)
CLI2\lib\json\decoder.py, ln 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
CLI2\lib\json\decoder.py, ln 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Zipped up deploy
- ran the following command:
- `az webapp deployment source config-zip -g myrg -n myapp --src myzip.zip`

## Expected Behavior
Successful deployment

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.66 *
azure-cli-ml 1.0.53.1

Extensions:
azure-cli-ml 1.0.53.1

```

**Comment by panchagnula** [comment]
@sethjuarez please re-try & let us know if you still see this. I have seen this reported earlier too where sometimes the API that checks for the status of the deployment, doesn't return a valid JSON object. I will try to get a repro on our end, & add some error handling.

**Comment by sethjuarez** [comment]
It looks like for some reason the *.scm.azurewebsites.net service was down. I had to rebuild the whole thing for it to work again :/

**Comment by panchagnula** [comment]
Can you say what you mean by you had to rebuild the whole thing? Its possible that for a freshly minted site scm site might have been going through a cold start the first time

**Comment by sethjuarez** [comment]
I basically removed the resource group and rebuilt everything up from scratch.

**Comment by khairop** [comment]
i receive an expecting char error (line 7 char 1)  executing the following command. Please advise.

Thank you
Kostas
------
az group deployment create --name TestDeployment --resource-group $resourceGroup \
--template-uri $uri1 \
--parameters \
'mysqlPassword=K0Sta$626262!' \
'adminUsername=adminkostas' \
'dnsNameForPublicIP=mypublicip72' \
'authenticationType=password'  \
'adminPasswordOrKey=YYYYYYYYYY' \
'newStorageAccountName=XXXXXXXXX'


please advise
[azure_cli_log_kostas.txt](https://github.com/Azure/azure-cli/files/3995370/azure_cli_log_kostas.txt)
