### ISSUE TITLE
az storage blob upload-batch fails when using current directory as source

### ISSUE THREAD

**Issue by ssemyan** [Azure/azure-cli#10914]
**upload-batch** fails when using the current directory as the source directory

**To Reproduce**
Create two files:
echo "foo" > foo.txt
echo "bar" > bar.txt

Try to upload them (from current directory):
az storage blob upload-batch -d mycontainer -s . --pattern *.txt --account-name myaccount --debug                      

Result:
Command arguments: ['storage', 'blob', 'upload-batch', '-d', 'vnetgatewayautomationassets', '-s', '.', '--pattern', 'bar.txt', 'foo.txt', '--account-name', 'tmobautodiag', '--debug']
cli.azure.cli.core.parser : az: error: unrecognized arguments: foo.txt
az: error: unrecognized arguments: foo.txt

Notice, the command arguments expanded out the pattern into the two files. This happens even if I fully qualify the source directory.

Create a directory foo and move the files into it:
mkdir foo
mv *.txt foo

Rerun the command:
az storage blob upload-batch -d mycontainer -s foo --pattern *.txt --account-name myaccount --debug                      

It works fine. 

**Environment summary**
Linux-4.9.184-linuxkit-x86_64-with-debian-9.11
Python 3.6.5
Shell: bash
azure-cli 2.0.74 *

**Comment by yonzhan** [comment]
@Juliehzl  put in next Sprint.

**Comment by ssemyan** [comment]
Actually the command fails if there are files inside the current working directory that match the pattern. 

To repro:
In the above repo, copy the files to the sub dir instead of moving them (leaving foo.txt and bar.txt in the current working directory). The command will fail with the same message.

**Comment by Juliehzl** [comment]
Hi @ssemyan, you need to use "" for pattern value in linux machine. Please try `az storage blob upload-batch -d mycontainer -s . --pattern "*.txt"--account-name myaccount --debug` in linux machine.

**Comment by yonzhan** [comment]
@ssemyan, have you tried the solution @Juliehzl  provided ?

**Comment by ssemyan** [comment]
Yes, that seems to work. I suppose this can be closed.
