### ISSUE TITLE
Docker image not tagged with immutable version

### ISSUE THREAD

**Issue by hameno** [Azure/azure-cli#10926]
The docker image https://hub.docker.com/r/microsoft/azure-cli has no immutable tags for each release version of 2.x
Please tag each release and not only use "latest".

**Comment by fengzhou-msft** [comment]
We are in the process of rewriting the page which should follow the format similar to https://hub.docker.com/_/microsoft-dotnet-framework-sdk/

**Comment by fengzhou-msft** [comment]
We have migrated the image to Microsoft Container Registry, which creates a new page on dockerhub: https://hub.docker.com/_/microsoft-azure-cli. It has a link to all available tags in `Full Tag Listing` section. As for the original https://hub.docker.com/r/microsoft/azure-cli page, we are contacting dockerhub team to redirect to the new page.
