### ISSUE TITLE
azurecliprod storage account missing 2.0.61 msi breaking Chocolatey install

### ISSUE THREAD

**Issue by inuvano-labs** [Azure/azure-cli#10925]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.61

**Describe the bug**

install-package -Name "azure-cli" -ProviderName Chocolatey -Force -ForceBootstrap -RequiredVersion 2.0.61

Results in:

WARNING: Unable to download from URI 'https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.0.61.msi' to ''.

**To Reproduce**
Run the above command

**Expected behavior**
To download msi 2.0.61 from container and install 2.0.61

**Environment summary**
Windows

**Additional context**
Seems that any release binaries have been pruned prior to 2.0.64

**Comment by fengzhou-msft** [comment]
I only see versions from 2.0.64 onwards in the msi storage container.

**Comment by inuvano-labs** [comment]
we have existing iac which has a dependency on 2.0.61 - is there a policy in place to remove msi from the container? what I mean is, if I update our scripts to 2.0.64 - how long will it be until 2.0.64 blob is removed from the container?

**Comment by fengzhou-msft** [comment]
We won't remove old version installers on purpose without good reason. I found #9535 to recover old MSI, it may be deleted by mistake. Are you using newer versions or you still prefer 2.0.61?

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please feel free to repoen the issue if you have any further request regarding the old MSI.
