### ISSUE TITLE
please help with az login issue, certificate verify failed

### ISSUE THREAD

**Issue by f14eagle** [Azure/azure-cli#10921]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.72

```

**Comment by jiasli** [comment]
This looks like a proxy intercepting certificate issue. Please add root certificate of the proxy to CLI's CA bundle: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy
