### ISSUE TITLE
Last login date?

### ISSUE THREAD

**Issue by ereyes-axon** [Azure/azure-cli#10931]
## When pulling user listings from a subscription, there seems to be no easy way to verify a user's last login date. Other than creation date and RefreshTokensValidFromDateTime, is there a way to pull any other time-based information on user listings? Having the date of last login would be very helpful for my team's period user access reviews.

**Command Name**
`az ad user list`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad user list -o {}`

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.64 *

```

**Comment by jiasli** [comment]
Thank you for the feedback. Azure CLI currently internally uses AD Graph to list users: https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/users-operations

The latest MS Graph doesn't support this either: https://docs.microsoft.com/en-us/graph/api/user-list

You may create a feedback at https://feedback.azure.com/forums/169401-azure-active-directory
