### ISSUE TITLE
Storage server side encryption with customer managed keys for managed disks 

### ISSUE THREAD

**Issue by ramankumarlive** [Azure/azure-cli#10948]
**Resource Provider**
What is the Azure resource provider your feature is part of?

Disk Resource Provider 
Compute Resource Provider (VM, VMSS)

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.

Conceptual doc: https://microsoft.sharepoint.com/:w:/t/MDSSEwithCMKprivatepreview/Ebp9PMK4gPFHhGG8OVgLB3YBi7yazrti-EGB8MpBWMm0RA?e=juMM5h

Design docs:

https://microsoft.sharepoint.com/:w:/t/ComputeVM/EZZCeyRJSbFAiBXq-VVgRBUBrz3c7vgA9lDC0j16Nx4hnQ?e=ec5pwL

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

2019-07-01 

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

https://github.com/Azure/azure-rest-api-specs/pull/7094

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

11/04/2019

**Comment by qwordy** [comment]
We have received your feature request. Thank you!

**Comment by qwordy** [comment]
The PR is merged. You can see the new features in the new version that will be released on 12/17/2019. Look forward to your feedback.

Added `disk-encryption-set create`, `disk-encryption-set show`, `disk-encryption-set list`, `disk-encryption-set delete`, `disk-encryption-set update`
Added `--encryption-type` and `--disk-encryption-set` to `disk create`
Added `--os-disk-encryption-set` and `--data-disk-encryption-sets` to `vm create`
Added `--os-disk-encryption-set` and `--data-disk-encryption-sets` to `vmss create`
