### ISSUE TITLE
ACS: support scale out by updating private agents number

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#1094]
We should at least expose this parameter in the generic update command

**Comment by tjprescott** [comment]
Do you mean expose it as a convenience argument in the update (--private-agent-number)? If there's a generic update, you should already be able to set this using that.

**Comment by yugangw-msft** [comment]
> Do you mean expose it as a convenience argument in the update (--private-agent-number)? 

Yes, and good to know it would be simple.
