### ISSUE TITLE
az functionapp list fails

### ISSUE THREAD

**Issue by irwinwilliams** [Azure/azure-cli#10944]
Whenever I try the command, 
az functionapp list

I get:
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/**[GUID]**/providers/Microsoft.Web/sites?api-version=2018-11-01 (Caused by ResponseError('too many 502 error responses',))

**Comment by SaurabhSharma-MSFT** [comment]
@irwinwilliams Apologies for the delayed response. This GitHub issue has been open for quite some time. Could you please let us know if you still facing this issue and need assistance? Awaiting your reply.
