### ISSUE TITLE
Add a flag to allow updating a VM/VMSS to support Ultra Disk

### ISSUE THREAD

**Issue by anasouma** [Azure/azure-cli#10943]
**Resource Provider**
What is the Azure resource provider your feature is part of? CRP/DiskRP

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
I would like to add a flag for az vm update and az vmss update to take --ultra-ssd-enabled true as an option. We have to do this instead: --set additionalCapabilities.ultraSSDEnabled=true 
which is too long. 

az vm update -n "ultrassd-test" --ultra-ssd-enabled true
az: error: unrecognized arguments: --ultra-ssd-enabled true

Looks like this does exist for the "create" sub command but not the update:

    --ultra-ssd-enabled  [Preview] : Enables or disables the capability to have 1 or more
                                     managed data disks with UltraSSD_LRS storage account.  Allowed
                                     values: false, true.
        Argument '--ultra-ssd-enabled' is in preview. It may be changed/removed in a future
        release.

We also need to remove this comment about preview:  _Argument '--ultra-ssd-enabled' is in preview. It may be changed/removed in a future release._ The feature is not in preview anymore.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature? been there for a while

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo. N/A

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests. N/A

**Comment by qwordy** [comment]
We have received your feature request. Planned in S162.

**Comment by qwordy** [comment]
It's not in preview in the latest version.
The gap is --ultra-ssd-enabled in update.

**Comment by qwordy** [comment]
I've added it to update command. It will be public in Azure 2.0.76. Official Release: 11/04/2019.
