### ISSUE TITLE
Can't set cors.supportCredentials property to true

### ISSUE THREAD

**Issue by bsvTag** [Azure/azure-cli#10956]
## Describe the bug

**Command Name**
`az webapp config set`

**Errors:**
```
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
azure/cli/core/util.py, ln 244, in shell_safe_json_parse
    return json.loads(json_or_dict_string)
lib64/python3.7/json/__init__.py, ln 348, in loads
    return _default_decoder.decode(s)
lib64/python3.7/json/decoder.py, ln 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib64/python3.7/json/decoder.py, ln 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

...

cli/command_modules/appservice/custom.py, ln 813, in update_site_configs
    config_name, value = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config set -g {} -n {} --generic-configurations "{"cors":{"supportCredentials":true}}"`

## Expected Behavior

supportCredentials is set to true

## Environment Summary
```
Linux-5.3.6-1-MANJARO-x86_64-with-arch-Manjaro-Linux
Python 3.7.4
Shell: bash

azure-cli 2.0.75

```

**Comment by Juliehzl** [comment]
cc @AzureAppServiceCLI @antcp

**Comment by Busch** [comment]
Same here. I got it fixed by using:

az resource update --ids subscriptions/{yoursubscriptionid}/resourceGroups/{yourresourcegroup}/providers/Microsoft.Web/sites/{yourfunctionappname}/config/web --set properties.cors.supportCredentials="true"

You can find your URL here: https://resources.azure.com/

**Comment by panchagnula** [comment]
This is the only way to support this currently. Thanks!
