### ISSUE TITLE
support list-policy for az keyvault

### ISSUE THREAD

**Issue by smartpcr** [Azure/azure-cli#10958]
As a developer, I would like to see existing access policies assigned to a given key vault.

``` bash
az keyvault list-policy ***
```

**Comment by yonzhan** [comment]
@jiasli add to next Sprint.

**Comment by jiasli** [comment]
Access policies are shown in `az keyvault show`. There is no corresponding REST API to list policies: https://docs.microsoft.com/en-us/rest/api/keyvault/vaults

You may filter the result to show only the access policies:

```
az keyvault show -n {} --query "properties.accessPolicies"
```
