### ISSUE TITLE
Azure acr helm push error

### ISSUE THREAD

**Issue by luanbon** [Azure/azure-cli#10959]
**Describe the bug**
I have an azure devops pipeline that pushes a helm chart to azure acr, but i am facing the following error:

**ERROR: Error: authentication required. Correlation ID: 8e639743-b3ae-4aa2-86fe-bdff31d82894.**

I tried with az login before push and occurred the same error.

According to this issue, is not required anymore to login with az login.

[https://github.com/Azure/azure-cli/issues/9010](url)

**To Reproduce**
az acr helm push --name $(registryName) -u $(registryUsername) -p $(registryPassword) $(build.artifactStagingDirectory)/$(projectName)-$(GitVersion.SemVer).tgz

**Comment by shizhMSFT** [comment]
When you specify `-u` and `-p` options, the `az acr helm push` command uses the specified credential to do push. Please remove `-u $(registryUsername) -p $(registryPassword)` and do
```
az acr helm push --name $(registryName) $(build.artifactStagingDirectory)/$(projectName)-$(GitVersion.SemVer).tgz
```
instead and try again.

If you do need to override the credentials, please double check if `$(registryUsername)` and `$(registryPassword)` are valid.

**Comment by yugangw-msft** [comment]
@luanbon, please reactivate when it what @shizhMSFT recommended doesn't work
