### ISSUE TITLE
ServiceBus Queue Create - Wrong default value for max-size

### ISSUE THREAD

**Issue by perkops** [Azure/azure-cli#10967]
## Describe the bug

**Command Name**
`az servicebus queue create -h`

**Errors:**
The documentation for the --max-size argument states that the default value is 1024.

--max-size                                    : Maximum size of queue in megabytes, which is the
                                                    size of the memory allocated for the queue.
                                                    Default is 1024. Max for Standard SKU is 5120
                                                    and for Premium SKU is 81920.  Allowed values:
                                                    1024, 10240, 2048, 20480, 3072, 4096, 40960,
                                                    5120, 81920.

However once a standard queue is provisioned, the size is set at 5 GB.

## To Reproduce:
First provision a ServiceHub namespace:
az servicebus namespace create --name xyzuniquename --resource-group xyzuniquenameresourcegroup

Then provision a servicebus queue:
az servicebus queue create --name xyzuniquequeuename --namespace-name xyzuniquename --resource-group xyzuniquenameresourcegroup

Then query the queues on the servicebus namespace
az servicebus queue list --namespace-name xyzuniquename --resource-group xyzuniquenameresourcegroup

The output states the following
""maxSizeInMegabytes": 5120"

## Expected Behavior
maxSizeInMegabytes should be 1024.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.75

```

**Comment by v-Ajnava** [comment]
fixed, please use latest CLI release
