### ISSUE TITLE
Adding new node type with durability level Gold will always throw CLI error

### ISSUE THREAD

**Issue by AnaTrajkovic** [Azure/azure-cli#10963]
**Describe the bug**
Few issues in this line of code:
   1) lower() is used here - it should be compared to 'standard_d15_v2' and 'standard_g5'
       (not 'Standard_D15_v2' and 'Standard_G5')
   2) Use 'and' instead of 'or' 

**To Reproduce**
Issue was caught by code investigation.
It will be reproduced each time when new node type is being added and durability level is Gold.

**Expected behavior**
CLI error will occur no matter what value vm_sku is set to if new node type is being added and durability level is Gold.

**Comment by peterpogorski** [comment]
Thanks for reporting the bug @AnaTrajkovic, @a-santamaria can you please triage this bug and provide an ETA?

**Comment by a-santamaria** [comment]
pr with the fix created here #11171. It should be available with the next release.
