### ISSUE TITLE
az login error: Unsupported wstrust endpoint version.

### ISSUE THREAD

**Issue by marckassay** [Azure/azure-cli#10979]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.
```

## To Reproduce:

- `az login -u marc@example.com -p abc123`

## Expected Behavior

To be able to login using the method that's used in the 2nd example [here](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login). 

## Environment Summary
```
Windows-10-10.0.18990-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.70 *

Extensions:
interactive 0.4.3

```

**Comment by jiasli** [comment]
Your account may require interactive login. Could you try `az login` and see if that works? 

If you need silent login, you may use service principal: https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli

**Comment by marckassay** [comment]
Executing `az login` with an arity of nil works as expected. But that does change the behavior slightly as it requires a browser window to be interacted with.

However, executing as I mentioned in my original post, worked recently. And according to the doc link I provided, it's still supported. You mentioned:

> Your account may require interactive login

How can I remove this requirement? Or can I?

**Comment by jiasli** [comment]
The error comes from https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/094812ca3b7651d87d637e4719a3a5f546d21ec0/adal/wstrust_request.py#L131

@marckassay, is it a **Microsoft account** or **Work or school account**?

I can reproduce with my outlook.com email address. Per [MSAL's wiki](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication):

> By design and policy, the username/password authentication works only for Work and school accounts, but not for Microsoft Accounts (MSA). 

Also see: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/33#issuecomment-481843088

This information is shown under `az login -h`:

    Log in with user name and password. This doesn't work with Microsoft accounts or accounts that
    have two-factor authentication enabled.
        az login -u johndoe@contoso.com -p VerySecret

We will improve the error message.

**Comment by marckassay** [comment]
It's a Microsoft account.

**Comment by jiasli** [comment]
Improved error in MSAL https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/34

**Comment by rayluo** [comment]
From another mail thread, I was reminded again that the azure-cli and MSAL integration was started but not yet finished. That's why our customers are not yet seeing those improvements. @jiasli feel free to contact us when you plan to pick up that work. Thanks!
