### ISSUE TITLE
Cannot create sample database other than AdventureWorksLT

### ISSUE THREAD

**Issue by yorek** [Azure/azure-cli#10975]
## Describe the bug
The only sample than can be create is AdventureWorksLT. All other sample database will fail to be created

**Command Name**
`az sql db create`

**Errors:**
```
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/fa58cf66-caaf-4ba9-875d-f310d3694845/resourceGroups/dm-sql/providers/Microsoft.Sql/servers/dmmssqlsrv/databases/WideWorldImportersFull?api-version=2017-10-01-preview (Caused by ResponseError('too many 500 error responses',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az sql db create -g *** --server *** -n WideWorldImportersFull --sample-name WideWorldImportersFull --service-objective BC_Gen5_4`

## Expected Behavior
Sample database should be created

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.75

```

**Comment by jaredmoo** [comment]
Thank you for logging this issue! I believe AdventureWorksLT is the only sample with builtin support for creation. Please see corresponding UI in Azure Portal:

![image](https://user-images.githubusercontent.com/3248887/68809994-fc9c2380-0621-11ea-9c03-f3cc046ae2a8.png)

**Comment by yorek** [comment]
Right, can we extend the options to also include well known AdventureWorks, WideWorldImporters and AdventureWorksDW? It would be great and will help customers to start to play with Azure SQL right away.

**Comment by yorek** [comment]
Closing as moved the issue to a different tracking system
