### ISSUE TITLE
Build out alternative authentication for SDKs

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#1097]
The Java and C# SDKs use the auth format as described here:
https://github.com/Azure/azure-sdk-for-java/blob/master/AUTH.md

We should generate this file when users login to enable single-sign-on across SDKs.

**Comment by yugangw-msft** [comment]
I am fine with generating this file, 2 things to clarify 
1. I assume this is for service principal only?
2. A service principal can have more than one subscription, we need a clearly definition for what is the 'default' subscription; otherwsie this filed should be an array
3. If we also support user account, then "tenant" can also be a list, we need mechanism to choose which is the default. Again, this field should be an array.

**Comment by mayurid** [comment]
@JasonRShaver : Why cant the existing information that is there in the current accesstokens file? Using that would enable them to work when there is no Py CLI in picture but Xplat is there.

**Comment by JasonRShaver** [comment]
Add an `--export-auth` param to the `az account show` command.  

If the user is logged in as a user instead of a service principal, it outputs an error `Auth files can only be generated for service principal identities.  Use 'az ad sp create-for-rbac' to generate a new service principal`

```
az account show -h

Command
    az account show: Show the specified subscription.  If no subscription is provided, the default subscription is shown 

Arguments
    --subscription      : Show the specified, by name or id, subscription
    --export-auth      : Export an auth file to the provided path for use with the Java and .NET Azure SDKs.  Default: my.azureauth

Global Arguments
    --debug    : Increase logging verbosity to show all debug logs.
    --help -h  : Show this help message and exit.
    --output -o: Output format.  Allowed values: json, jsonc, list, table, tsv.  Default: json.
    --query    : JMESPath query string. See http://jmespath.org/ for more information and examples.
    --verbose  : Increase logging verbosity. Use --debug for full debug logs.
```
