### ISSUE TITLE
Unable to upload after failed sync 

### ISSUE THREAD

**Issue by EricJPogue** [Azure/azure-cli#10974]
After attempting to sync a local directory utilizing azcopy (the sync failed for an unknown reason), I am unable to upload files to the blob storage container utilizing methods that had worked previously including "az storage blob update" (error below). I am also unable to upload file to the container utilizing the standard portal web browser upload function after the azcopy sync failure. 

Eric

## Describe the bug

**Command Name**
`az storage blob upload`

**Errors:**
```
The specified blob or block content is invalid. ErrorCode: InvalidBlobOrBlock
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlobOrBlock</Code><Message>The specified blob or block content is invalid.
RequestId:f1a07b59-201e-0061-58a2-8a0aa5000000
Time:2019-10-24T19:37:44.3823155Z</Message></Error>
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 566, in execute
    raise ex
...
azure.common.AzureHttpError: The specified blob or block content is invalid. ErrorCode: InvalidBlobOrBlock
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlobOrBlock</Code><Message>The specified blob or block content is invalid.
RequestId:f1a07b59-201e-0061-58a2-8a0aa5000000
Time:2019-10-24T19:37:44.3823155Z</Message></Error>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload --container-name {} --file {} --name {}`

## Environment Summary
```
Darwin-19.0.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.67 *

```

**Comment by Juliehzl** [comment]
It looks your blob is invalid. Because you also cannot do that in Portal, it may not cli related error. But to let me know what happedned, can you provide me more information with `--debug` in you command?

**Comment by Juliehzl** [comment]
Hi @EricJPogue , close the issue given no response for a long time. If you still have problems, feel free to reopen it or create a new one.

**Comment by Gambit-14** [comment]
Hi guys. Good day. I am also encountering this problem. How did you fix it? Thanks in advance!
