### ISSUE TITLE
az vmss update --set command to update Application Security Group fails with the below error.

### ISSUE THREAD

**Issue by ameetkonnur** [Azure/azure-cli#10980]
## Describe the bug

**Command Name**
`az vmss update`

**Errors:**
```
Unable to build a model: Cannot deserialize as [SubResource] an object of type <class 'str'>, DeserializationError: Cannot deserialize as [SubResource] an object of type <class 'str'>
Traceback (most recent call last):
python3.6/site-packages/msrest/serialization.py, ln 571, in body
    data = deserializer._deserialize(data_type, data)
python3.6/site-packages/msrest/serialization.py, ln 1261, in _deserialize
    self._deserialize(local_type, value)
...

python3.6/site-packages/msrest/serialization.py, ln 1479, in deserialize_iter
    type(attr)
msrest.exceptions.SerializationError: Unable to build a model: Cannot deserialize as [SubResource] an object of type <class 'str'>, DeserializationError: Cannot deserialize as [SubResource] an object of type <class 'str'>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss update -n {} -g {} --set {}`

## Environment Summary
```
Linux-4.15.0-1061-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.75

Extensions:
aks-preview 0.3.1

```

**Comment by yonzhan** [comment]
@qwordy add to next Sprint.

**Comment by qwordy** [comment]
Hi Ameet, What's you complete command? You can omit sensitive data.

**Comment by ameetkonnur** [comment]
az vmss update -n <VMSS NAME> -g <VMSS RESOURCE GROUP> --set virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].applicationSecurityGroups='[{"id":"/subscriptions/<subscription ID>/resourceGroups/<Resource Group of NIC & ASG>/providers/Microsoft.Network/applicationSecurityGroups/<ASG NAME>"}]'

Above, the command that I used.
I used the same command on a non-AKS VMSS and it worked fine. The difference I see is AKS creates a VMSS with 30 ipConfigurations ir-respective of the no of nodes actually running and VMSS API is checking if the ASG is the same across all ipConfigurations, but doesn’t provide an option to update all.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by qwordy** [comment]
I have reproduced the same result using your command. You can try this command.
```
az vmss update -g <> -n <> --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].applicationSecurityGroups id="/subscriptions/<>/resourceGroups/<>/providers/Microsoft.Network/applicationSecurityGroups/<>"
```
--add

Add an object to a list of objects by specifying a path and key value pairs. Example: --add property.listProperty <key=value, string or JSON string>.

**Comment by yungezz** [comment]
hi @ameetkonnur pls try above solution and let us know if it resolves your problem.

**Comment by ameetkonnur** [comment]
Thanks for getting back on this. I tried the above but it gives the error below. This VMSS is of an AKS cluster

All IPConfigurations on a Network Interface should reference the same set of Application Security Groups. IPConfiguration ipconfig2 references ASG(s) , wheras IPConfiguration /subscriptions/<>/resourceGroups/<>/providers/Microsoft.Compute/virtualMachineScaleSets/<>/updateGroups/<>/networkInterfaceConfigurations/<>/ipConfigurations/ipconfig1 references ASG(s) /subscriptions/<>/resourceGroups/<>/providers/Microsoft.Network/applicationSecurityGroups/<>.

**Comment by qwordy** [comment]
I am not an expert of AKS. It seems a limitation of AKS according to the error message. All IPConfigurations on a Network Interface should reference the same set of Application Security Groups. @andyzhangx Do you have more information?

**Comment by iverberk** [comment]
We are running into the same issue, also with an AKS vmss. We need this functionality to manage network security rules for the different nodepools (=vmss). A solution would be much appreciated.

**Comment by wangjun-jwa** [comment]
@qwordy , @ameetkonnur  is asking for how CLI support setting multiple properties in VMSS in same command, because it's required to add Application Security Groups for all 50 IpConfigurations in a single call.

**Comment by iverberk** [comment]
Just to add some info, I've created an issue here: https://github.com/Azure/AKS/issues/1388 as requested in this issue: https://github.com/MicrosoftDocs/azure-docs/issues/41470 . There are multiple places where this is now opened as an issue.

**Comment by iverberk** [comment]
@wangjun-jwa Is there any news regarding CLI/API support for this?

**Comment by qwordy** [comment]
It's not supported to add Application Security Groups for all 50 IpConfigurations in a single call. Maybe you need to write a PowerShell or Bash script.

**Comment by iverberk** [comment]
Thanks @qwordy . Is it possible to do this with a script? Could you maybe give a small example or doc links on how to do this? Pseudocode is fine.

**Comment by Drewm3** [comment]
Removing VMSS and ServiceAttention labels because this appears to be an issue with the az CLI as compared to a API issue.

**Comment by iverberk** [comment]
So you guys are saying that we can in fact add an application security group to a AKS nodepool vmss in an automated way? The API allows this? Could someone please provide a pointer on how to achieve this if you cannot use the default CLI command for this?

**Comment by qwordy** [comment]
> 
> 
> Thanks @qwordy . Is it possible to do this with a script? Could you maybe give a small example or doc links on how to do this? Pseudocode is fine.

You can refer to these articles. It's not difficult. It will cost you several minutes to learn it.
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_for?view=powershell-7
https://www.gnu.org/software/bash/manual/html_node/Looping-Constructs.html

**Comment by iverberk** [comment]
Sorry, I know how to create a loop. What I want to know is which API I can call in the loop and with which parameters, since it is not possible to make the vmss API call to set an ASG on the vmss created by the nodepool. There has to be some kind of API call that does it one-at-a-time but I can't find it.

**Comment by qwordy** [comment]
1. Try this command. It should fail, it is a limitation of AKS VMSS according to the error message.
az vmss update -g <> -n <> --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].applicationSecurityGroups id="/subscriptions/<>/resourceGroups/<>/providers/Microsoft.Network/applicationSecurityGroups/<>"
2. You want to set multiple ip configurations.
Method 1: copy the command and modify the index of ipConfigurations.
az vmss update -g <> -n <> --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].applicationSecurityGroups id="/subscriptions/<>/resourceGroups/<>/providers/Microsoft.Network/applicationSecurityGroups/<>"
az vmss update -g <> -n <> --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[1].ipConfigurations[0].applicationSecurityGroups id="/subscriptions/<>/resourceGroups/<>/providers/Microsoft.Network/applicationSecurityGroups/<>"
...
Method 2: Write a script. You can use your favorite language.
An example in bash:
for i in {1..50}
do
    az vmss update -g <> -n <> --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[1].ipConfigurations[$i].applicationSecurityGroups id="/subscriptions/<>/resourceGroups/<>/providers/Microsoft.Network/applicationSecurityGroups/<>"
done

**Comment by qwordy** [comment]
You can ping Azure/AKS#1388
