### ISSUE TITLE
Pass IOPS/Throughput to VMScaleSet in Create and Update

### ISSUE THREAD

**Issue by robhat1** [Azure/azure-cli#10986]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.Compute (CRP)

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
We have introduced new properties that apply to DataDisks when StorageAccountType is UltraSSD_LRS. Please note that they do not apply to OSDisk currently.
diskIOPSReadWrite: Used to specify IOPS for the Data disk.
diskMBpsReadWrite: Used to specify throughput in MB per second for the Data disk.
These properties can be set or updated only via Create or Update on the VMScaleSet. At a VMScaleSet VM level, these properties are ReadOnly. This means that an update on the VMScaleSet VM cannot modify the values of these properties on the disk but a GET on the VMScaleSetVM would return these properties and they should be displayed to the user.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2019-07-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json

Specific commit: https://github.com/Azure/azure-rest-api-specs/pull/7094/commits/e0a2452d7a449c0e278b3d9ecfcdcf4ac7d6eb4f

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
November 4, 2019

**Comment by yonzhan** [comment]
@qwordy add to S162

**Comment by qwordy** [comment]
I find different property names in responses, diskIOPSReadWrite, diskIopsReadWrite, diskMBpsReadWrite diskMbpsReadWrite. Can you help confirm?

**Comment by qwordy** [comment]
@robhat1

**Comment by qwordy** [comment]
This feature is published. You can download the latest Azure CLI and use it.
