### ISSUE TITLE
If you use az ad app update from PowerShell

### ISSUE THREAD

**Issue by Damag3d** [Azure/azure-cli#10997]
```
$ex = "az ad app update --id ```"yourappidGUID```" --debug --reply-urls ```"https://yourSPAURL.z6.web.core.windows.net/```" ```"msalyourappidGUID://auth```""
Invoke-Expression -Command $ex
```

Hope this will be useful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by jiasli** [comment]
Directly calling the command work fine:
```
az ad app update --id "yourappidGUID" --reply-urls "msalyourappidGUID://auth"
```

Any reason to use `Invoke-Expression`?

**Comment by jiasli** [comment]
Directly calling the command works fine:

```
az ad app update --id "yourappidGUID" --reply-urls "msalyourappidGUID://auth"
```

Any reason to use `Invoke-Expression`?

**Comment by Damag3d** [comment]
I wrote a scipt that accepts ScriptBlocks where I could use Invoke-Command it looks like that:

```
function global:Invoke-AzCLI {
	Param(
		[Parameter(Mandatory=$true, Position=0)]
		[ScriptBlock]$Command)

	[string]$clijson = ""
	$clijson = Invoke-Command -ScriptBlock $Command

	if ($LASTEXITCODE -ne 0) { 
		LogCLIException -LoggedText ("Az CLI command '{0}' failed. Exiting." -f $Command) -StopExecution $true
		return
	}

	if ($clijson.Length -eq 0) {
		return $null
	} else {
		$cliresults = ConvertFrom-Json -InputObject $clijson
		return $cliresults
	}
}
```
Fantastic. you can use `Invoke-AzCLI { az ad app update ...... }` However the problem is with az parameters that are "space delimited list of URIs". 
1. getting file not find error
2. az cli reacts to --% and treats it as parameter giving invalid parameter error
What you actually need is to shut up both of them az cli and PowerShell core and stop parsing everything. So Invoke-AzCLI example with scriptblock as a parameter does not work. Invoke-Expression helps.

**Comment by jiasli** [comment]
Thanks for the expalantion. But I still didn't see where the problem is. Following command works fine:

```
Invoke-AzCLI { az ad app update --id {} 
--reply-urls "https://yourSPAURL.z6.web.core.windows.net/" "msalyourappidGUID://auth" --debug}
```
CLI receives the args correctly: 
```
Command arguments: ['ad', 'app', 'update', '--id', '2a01b07a-72c5-463a-9721-7de2fe41af50',
 '--reply-urls', 'https://yourSPAURL.z6.web.core.windows.net/', 'msalyourappidGUID://auth', 
'--debug']
```

Could you provide the command to trigger `file not found` and `--%` errors?

We have a sample here to read the output of a command: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#windows-powershell-scrips-for-saving-to-variables-and-using-it-later

**Comment by Damag3d** [comment]
When reply URLs are provided as set of strings yes. Try doing with --reply-urls $replyurls, where $replyurls contains indicated URLs

**Comment by jiasli** [comment]
Could you test if array works for you? I tested and CLI receives the args correctly. 

```powershell
> $replyurls='https://yourSPAURL.z6.web.core.windows.net/','msalyourappidGUID://auth'
> az $replyurls --debug
Command arguments: ['https://yourSPAURL.z6.web.core.windows.net/', 'msalyourappidGUID://auth', '--debug']

# also works for bare python
> python -c "import sys; print(sys.argv)" $replyurls
['-c', 'https://yourSPAURL.z6.web.core.windows.net/', 'msalyourappidGUID://auth']
```

**Comment by qianwens** [comment]
Close this issue since there is no response for more than one month, please help create a new issue if you still have problem to run this command in Powershell.
