### ISSUE TITLE
Import of bacpac fails

### ISSUE THREAD

**Issue by yorek** [Azure/azure-cli#10991]
## Describe the bug
Importing a bacpac into a database  fails with error HTTP 504

**Command Name**
`az sql db import`

**Errors:**
https://management.azure.com:443 "PUT /subscriptions/XXX/resourceGroups/YYY/providers/Microsoft.Sql/servers/ZZZ/databases/DDD/extensions/import?api-version=2014-04-01 HTTP/1.1" 504 141

## To Reproduce:
`az sql db import -s {} -n {} -g {} -p {} -u {} --storage-key {} --storage-key-type {} --storage-uri {} --debug`

## Expected Behavior
Import is successful

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash
azure-cli 2.0.75
```

**Comment by yorek** [comment]
I'm using the official WideWorldImporters sample available here: https://github.com/Microsoft/sql-server-samples/releases/tag/wide-world-importers-v1.0

**Comment by yorek** [comment]
Closing as moved the issue to a different tracking system

**Comment by yorek** [comment]
Also, fixed

**Comment by t-l-k** [comment]
@yorek - can you clarify "fixed"? And what other issue tracking system has this been published on? 

Running this command `az sql db import` is throwing a 504 for me at the moment. An `export` ran to completion fine.

I updated my `azure-cli` today to make sure. This is failing for me on: 

```
azure-cli                         2.0.80

command-modules-nspkg              2.0.3
core                              2.0.80
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
interactive                        0.4.3
```

**Comment by yorek** [comment]
The import command worked for me: 

az sql db import -s <server> -n ... -g ... -p ... -u ... --storage-key ... --storage-key-type StorageAccessKey --storage-uri https://mystorage.blob.core.windows.net/bak/WideWorldImporters-Full.bacpac

Of course you need to make sure that the existing database supports the feature used in the database to be imported. For the WideWorldImportersFull, for example, Premium or BusinessCritical are needed

**Comment by t-l-k** [comment]
Thanks for replying, I gave up in the end as `az sql copy` was way faster for inter-server transfers, and if I really needed a bacpac it would only be for local desktop use. Importing it was not really a hard requirement, as I was only experimenting.
