### ISSUE TITLE
Please provide example for az ad user update

### ISSUE THREAD

**Issue by jasonshave** [Azure/azure-cli#10996]
I'm attempting to use the --force-change-password-next-login option and set it to "false" as follows:

`az ad user update --id someone@example.com --force-change-password-next-login false`

This produces  the following error: "validation error: Parameter 'PasswordProfile.password' can not be None."

If another required parameter or information is required, our documentation should clearly describe this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57b0bbf2-3dca-90b2-1734-a38e78104b41
* Version Independent ID: 39842113-e499-d863-0f61-795089d844d9
* Content: [az ad user](https://docs.microsoft.com/en-us/cli/azure/ad/user?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
CLI uses AD Graph to update password: https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/users-operations#reset-a-users-password--

`--force-change-password-next-login` is a supplemental argument for `--password`, which is only valid when `--password` is provided. 

We will improve the doc.
