### ISSUE TITLE
az acr list -g ResourceGroupName returns ACR from other resource group

### ISSUE THREAD

**Issue by eiximenis** [Azure/azure-cli#11004]
## Describe the bug

**Command Name**
`az acr list -g MyResourceGroup -o table`

**Errors:**
Is expected to return only the ACRs belonging to this RG, but another ACR is also returned.
The subscription contains OTHER ACRs which are not returned.

## To Reproduce:
![image](https://user-images.githubusercontent.com/5191049/67676385-a2446700-f981-11e9-93b4-5162fde32106.png)

**Note**: This subscription has 5 ACRs in different resources groups.

## Expected Behavior
Only ACR from specified RG are expected to be returned

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.75

Extensions:
aks-preview 0.4.14
application-insights 0.1.1
dev-spaces 1.0.3

```

**Comment by Juliehzl** [comment]
@djyou can you have a look at this?

**Comment by shizhMSFT** [comment]
Thank you for openning this issue. We are investigating, and will reply soon once we have progress.

**Comment by yugangw-msft** [comment]
@eiximenis, for workaround, please avoid naming the resource group with `-` in the middle.

**Comment by yugangw-msft** [comment]
To fix this requires the service end change.

**Comment by adewaleo** [comment]
This has been fixed. Please feel free to verify @eiximenis. Thanks for bringing this up.

**Comment by adewaleo** [comment]
@yonzhan can this issue be closed?
