### ISSUE TITLE
Unable to add or list extensions in CLI 2.0.75

### ISSUE THREAD

**Issue by holleye** [Azure/azure-cli#11006]
I'm trying to install the Azure DevOps extension, but am unable to get the extension index. I attempted to list the extensions and got the same error. Is there an additional configuration step I'm missing for my environment? I'm able to successfully login via the Azure CLI.

Sample error:

az extension list-available --output table
az : ERROR: Unable to get extension index.
At line:1 char:1
+ az extension list-available --output table
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Unable to get extension index.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='aka.ms', port=443): Max retries 
exceeded with url: /azure-cli-extension-index-v1 (Caused by SSLError(SSLError("bad handshake: Error([('SSL 
routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by yonzhan** [comment]
@zikalino  please take a look.

**Comment by haroldrandom** [comment]
I think it's just a common connection error that can be fixed by retry and not related to azure-cli.

Maybe a network congestion.

It wored fine for me.
![image](https://user-images.githubusercontent.com/14357159/70874352-b5bc9780-1fec-11ea-9de7-2622b196bbfb.png)

Can try against the latest azure-cli?

**Comment by itsho** [comment]
Hi.

I'm getting the very same error. tried multiple times, and I do have internet access.
any idea how to go on from here?

thank you.

![UnableToInstallExtensions](https://user-images.githubusercontent.com/1774797/87233288-ad83d980-c3ce-11ea-8a1c-19849e34dd83.png)

**Comment by JeffWRush** [comment]
I know this is old, but the error is certificate validation error. I'm getting the same due to some HTTPS inspector that our company is using, and I'm looking for a way to add trust or ignore cert validation errors.

**Comment by jiasli** [comment]
@JeffWRush, please see https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#work-behind-a-proxy for detailed instruction. If there are any questions, please let us know.
