### ISSUE TITLE
Add az network service-aliases list

### ISSUE THREAD

**Issue by jkhurana19** [Azure/azure-cli#11018]
**Is your feature request related to a problem? Please describe.**
Add CLI corresponding to the Add Get-AzAvailableServiceAliases work 
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/395
https://github.com/Azure/azure-powershell/pull/10198

**Describe the solution you'd like**
We would want to have CLI support for the get aliases, please refer to the issue above, the corresponding work needs to be done for Azure CLI.

It would be something like:

az network service-aliases list

it can take -location and -resourcegroup as parameters. Please look at the rest api below.

**Describe alternatives you've considered**
We already have the rest api in swagger over here.

It was checked in as part of:
https://github.com/Azure/azure-rest-api-specs/pull/7362
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-08-01/availableServiceAliases.json

**Additional context**
Please call the rest api in the swagger and expose the functionality of the rest api from cli.

**Comment by MyronFanQiu** [comment]
@jkhurana19 Thanks. Will make a plan for it.
