### ISSUE TITLE
az vm wait public ip address of vm?

### ISSUE THREAD

**Issue by Lelelo1** [Azure/azure-cli#11016]
I am trying to write a script that connects to my Azure vm. Is it possible with [az vm wait](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-wait)?

With `az vm list-ip-addresses` I can get a json containing the `ipAddress` but it returns null - if the vm was just started by the script.

Is there any way I can wait and get the ip adress when i'ts ready? Note Im on Mac.

**Comment by qwordy** [comment]
We have received your problem. I need a little time to try it. I will reply you soon.

**Comment by qwordy** [comment]
```
az vm wait -g MyResourceGroup -n MyVm --created
az vm list-ip-addresses -g MyResourceGroup -n MyVm
```
Have a try

**Comment by qwordy** [comment]
The output of `az vm create` should contain ip address
```
az vm create -g fytest2 -n vm1 --image centos
{
  "fqdns": "",
  "id": "/subscriptions/***/resourceGroups/fytest2/providers/Microsoft.Compute/virtualMachines/vm1",
  "location": "westus",
  "macAddress": "00-0D-3A-36-95-37",
  "powerState": "VM running",
  "privateIpAddress": "10.0.0.4",
  "publicIpAddress": "104.42.158.11",
  "resourceGroup": "fytest2",
  "zones": ""
}
```

**Comment by Lelelo1** [comment]
I am looking for `az vm wait -g MyResourceGroup -n MyVm --started` - as I already have a vm that I use persistently. Every time I am going to work in windows on the vm I have to navigate to the azure portal to see the ip to enter into Microsoft Remote Desktop.
It would be great if my current script could echo out the ip adress for me (when it is ready).

**Comment by yungezz** [comment]
HI @Lelelo1 , you could use below commands to wait for a VM created ready, and get IP address forr remote access. Let us know if this resolves your problem, then we'll go ahead to close the issue.

```
# create azure vm and wait for creation done
az vm wait -g MyResourceGroup -n MyVm --created

# get IP address of the created VM
az vm list-ip-addresses -g MyResourceGroup  -n MyVm --query [0].virtualMachine.network.publicIpAddresses[0].ipAddress
```

**Comment by Lelelo1** [comment]
It seems `az vm start` now [is waiting](https://github.com/Azure/azure-cli/issues/10017) by default. So it is possible to to query for the public ip address like @yungezz described.

**Comment by yungezz** [comment]
thanks @Lelelo1 for the update. Will close the issue for now then. Feel free to create new one if any issue met or reopen this one. Thanks.
