### ISSUE TITLE
Link missing under --destination parameter

### ISSUE THREAD

**Issue by ginomessmer** [Azure/azure-cli#11028]
It says `[link here]` beneath `--destination -d` on this page: https://docs.microsoft.com/en-us/cli/azure/storage?view=azure-cli-latest#optional-parameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c4e415-fc8d-26d5-3213-da937fd6932c
* Version Independent ID: dcb2f2d6-fd80-495d-8582-8be859d68792
* Content: [az storage](https://docs.microsoft.com/en-us/cli/azure/storage?view=azure-cli-latest#optional-parameters)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Juliehzl** [comment]
Thanks for your feedback and reminder. We will improve it soon.
