### ISSUE TITLE
Suggestions for improvements to `az configure`

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1102]
I think this would be more idiomatic/intuitive than the interactive wizard:

```
$ az config output tsv

$ az config telemetry on
```

Note the subcommand format and `config` in favor of `configure`.

**Comment by jimsander** [comment]
The options SEEMS to exist (at least or `-output`) but still goes interactive:
``` # az configure --output table

Welcome to the Azure CLI! This command will guide you through logging in and setting some default values.

Your settings can be found at /Users/jimsander/.azure/config
Your current configuration is as follows:

[cloud]
name = AzureCloud

[core]
first_run = yes
output = tsv
collect_telemetry = yes

[logging]
enable_log_file = yes

Environment variables:
AZURE_STORAGE_KEY = REDACTED
AZURE_STORAGE_ACCOUNT = REDACTED

Do you wish to change your settings? (y/N):```

**Comment by msleal** [comment]
Hi there,

   We have the ‘az configure’ command that is *interactive*.
   We have the ‘az xxx  –output’ option to change the output for a specific execution…
   But would be good to have an option to change the configuration ‘globally’ in a *non-interactive* way?
   Ex.: az configure –output tsv
 
   If we need to change just one option of our global configuration, it’s not nice to go through all the configure ‘(y|n)’ prompts.

   I know we have the option to just go to the configuration file (~/.azure/config) and change it, but as we have a tool to do it, I think would make sense to have a “non-interactive* way to re-configure it.

**Comment by derekbekoe** [comment]
Just to update this issue, the config options can be set with environment variables as well which would be for non-interactive scenarios.

e.g. for setting the default output type, `export AZURE_CORE_OUTPUT=table`

See https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-values-and-environment-variables

**Comment by derekbekoe** [comment]
Closed the issue as this seems like a good option for users though it's a different approach to `$ az config output tsv` or `$ az config telemetry on`
