### ISSUE TITLE
permissions for  az ad user show

### ISSUE THREAD

**Issue by abelal83** [Azure/azure-cli#11029]
what graph permissions are required for az ad user show to work?

I'm using az cli with a service principal and have granted this service principal the following API Application permissions

1. Directory.Read.All
2. User.Read.All

but when running az ad user show I get an error
cli.azure.cli.core.util : Insufficient privileges to complete the operation.
Insufficient privileges to complete the operation.

I'm not sure what other permissions this command needs because according to https://docs.microsoft.com/en-us/graph/permissions-reference#user-and-group-search-limitations-for-guest-users-in-organizations the permissions I've granted should be enough when calling 

urllib3.connectionpool : https://graph.windows.net:443 "GET /ced47db0-xxxxxxx/users/abelal83%40mycompany.com?api-version=1.6 HTTP/1.1" 403 219

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by jiasli** [comment]
Please also see https://github.com/Azure/azure-cli/issues/6058#issuecomment-379888615. Make sure the permission is granted for **Azure Active Directory Graph** as Azure CLI currently uses **Azure Active Directory Graph** instead of **Microsoft Graph**. 

After granting **Azure Active Directory Graph -> Directory.Read.All**, I am able to use `az ad user show --id {}` correctly.

**Comment by thiagottss** [comment]
> Please also see [#6058 (comment)](https://github.com/Azure/azure-cli/issues/6058#issuecomment-379888615). Make sure the permission is granted for **Azure Active Directory Graph** as Azure CLI currently uses **Azure Active Directory Graph** instead of **Microsoft Graph**.
> 
> After granting **Azure Active Directory Graph -> Directory.Read.All**, I am able to use `az ad user show --id {}` correctly.

It worked here for me... I wasn't using this one as it states "deprecated" ... 

Thanks.
