### ISSUE TITLE
Clarification of --scopes parameter for `az ad sp create-for-rbac --skip-assignment ...`

### ISSUE THREAD

**Issue by BenjaminHerbert** [Azure/azure-cli#11031]
Could you explain the meaning of the `--scopes` parameter for the command 
`az ad sp create-for-rbac --skip-assignment ...`.

The help says:

> --scopes          : Space-separated list of scopes the service principal's role assignment applies to. Defaults to the root of the current subscription.

As I have no assignment due to `--skip-assignment`, there is no assignment yet...

What does `--scopes` do? Does it limit the scope where a role can be assigned to the service principal?
```
az role assignment create --assignee $ASSIGNEE --scope $SCOPE --role $ROLE
```

Or does it just do nothing in the `--skip-assignment` case? 

I'd be glad if you could clarify this and add some more information to the documentation regarding `--scopes`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-create-for-rbac)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli add to S162.

**Comment by jiasli** [comment]
@BenjaminHerbert, thanks for this nice feedback. Please https://github.com/Azure/azure-cli/issues/10724#issuecomment-539345221 where I described what a scope is. 

I will improve the help message and make it clearer.

**Comment by yonzhan** [comment]
add to S171
