### ISSUE TITLE
exactVersion property missing from az vm show output

### ISSUE THREAD

**Issue by craiglandis** [Azure/azure-cli#11035]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
exactVersion property not returned by "az vm show"

**To Reproduce**
Steps to reproduce the behavior.

az vm show -g ubuntu -n ubuntu --query storageProfile.imageReference
{
  "id": null,
  "offer": "UbuntuServer",
  "publisher": "Canonical",
  "sku": "16.04-LTS",
  "version": "latest"
}

**Expected behavior**

The exactVersion property was added in API version 2019-07-01, so CLI should return it too.

Use Try It and change API version to 2019-07-01 - https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get

    "storageProfile": {
      "imageReference": {
        "publisher": "Canonical",
        "offer": "UbuntuServer",
        "sku": "16.04-LTS",
        "version": "latest",
        "exactVersion": "16.04.201909091"
      },

**Environment summary**
azure-cli 2.0.75

**Additional context**

**Comment by qwordy** [comment]
We have received your feedback. We'll investigate it.

**Comment by qwordy** [comment]
The definition of ImageReference has no exactVersion. So even the response has exactVersion, the model we build cannot have exactVersion field. Added a service attention to try to make it consistent.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
```
"ImageReference": {
      "properties": {
        "publisher": {
          "type": "string",
          "description": "The image publisher."
        },
        "offer": {
          "type": "string",
          "description": "Specifies the offer of the platform image or marketplace image used to create the virtual machine."
        },
        "sku": {
          "type": "string",
          "description": "The image SKU."
        },
        "version": {
          "type": "string",
          "description": "Specifies the version of the platform image or marketplace image used to create the virtual machine. The allowed formats are Major.Minor.Build or 'latest'. Major, Minor, and Build are decimal numbers. Specify 'latest' to use the latest version of an image available at deploy time. Even if you use 'latest', the VM image will not automatically update after deploy time even if a new version becomes available."
        }
      },
      "allOf": [
        {
          "$ref": "#/definitions/SubResource"
        }
      ],
      "description": "Specifies information about the image to use. You can specify information about platform images, marketplace images, or virtual machine images. This element is required when you want to use a platform image, marketplace image, or virtual machine image, but is not used in other creation operations."
    },
```

**Comment by Drewm3** [comment]
It looks like the the API spec has been updated. So this should be available in an upcoming release of the CLI: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json

**Comment by qwordy** [comment]
This issue is fixed. Download the latest Azure CLI and have a try!
