### ISSUE TITLE
DNS Zone import Unable to parse @ in RDATA

### ISSUE THREAD

**Issue by NeighborGeek** [Azure/azure-cli#11032]
## Describe the bug

DNS Zone import fails on records containing @ in RDATA 
**Command Name**
`az network dns zone import`

**Errors:**
```
Unable to parse: ftp 3600 IN CNAME '@'
```

## To Reproduce:
Import a DNS Zone file containing one or more records with @ in RDATA.  For example:

ftp	3600	 IN 	CNAME	@ 

## Expected Behavior
Where an @ appears in RDATA, it should be replaced by $ORIGIN.  For example, the record: 
ftp	3600	 IN 	CNAME	@ 

should be imported as ftp.<$ORIGIN>

## Environment Summary
Aure Cloud Shell

```
Linux-4.15.0-1061-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.75

```

**Comment by MyronFanQiu** [comment]
@NeighborGeek  Hello. Could you please share me with a tiny example file which will cause this error?

**Comment by ioan-agopian** [comment]
I've encountered this as well.
@MyronFanQiu please find attached a file that throws this error.

[testdomainrsk.hosts.txt](https://github.com/Azure/azure-cli/files/4148995/testdomainrsk.hosts.txt)

**Comment by NeighborGeek** [comment]
@ioan-agopian Thanks for adding that.  I must have overlooked the reply, and never submitted the sample they requested.

**Comment by navarro-chamberlain** [comment]
Was there any resolution to this. Encountering the same error

**Comment by jsntcy** [comment]
@navarro-chamberlain, Could you replace `@` with $ORIGIN in RDATA in DNS Zone file to workaround this issue?

**Comment by compusaurusrex** [comment]
I am also getting this error when importing a zone file:
Unable to parse: @ 3600 MX idctelemed-com.mail.protection.outlook.com. 0
Does anyone know of a solution to this problem?

**Comment by yonzhan** [comment]
@haroldrandom to help with.
