### ISSUE TITLE
Add CLI Support for Private Link for Key Vault 

### ISSUE THREAD

**Issue by ShaneBala-keyvault** [Azure/azure-cli#11038]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Azure Key Vault

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
Add CLI Support for Private Link for Azure Key Vault 

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
See Swagger Doc Below

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
https://github.com/Azure/azure-rest-api-specs/pull/7631

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
End of November 2019

**Comment by yonzhan** [comment]
@jiasli  planned in S162.

**Comment by bim-msft** [comment]
The creation and the deletion of Private Endpoint should be restrained in `network` command, which already supports command groups `private-endpoint` and `private-link-service`. @MyronFanQiu needs additional work for full support (see #11667)

For `keyvault` command, should we do the same thing as network command? Or just adding functionality like `show/get/list` for private endpoints is enough?

How do you think? @ShaneBala-keyvault @yungezz

**Comment by bim-msft** [comment]
PR merged, will release on Feb 18.
