### ISSUE TITLE
Soft-delete on by default via the Azure CLI

### ISSUE THREAD

**Issue by ravijan** [Azure/azure-cli#11039]
**Is your feature request related to a problem? Please describe.**
For Azure Key Vault, the new version of the API enables by default that soft-delete is true.  We are asking the CLI team to support "on" or true by default.

**Describe the solution you'd like**
The existing behavior will now change.  By default, the CLI should set this to true by default.  If they leave it blank, this will now default to true.  They will need to specific false specifically to ensure this is off.

Today's behavior is as follows:
https://docs.microsoft.com/en-us/azure/key-vault/key-vault-soft-delete-cli

Specifying blank should enable this to be true (not false) as it is today.

**Comment by yonzhan** [comment]
@jiasli planned in S161.
