### ISSUE TITLE
Error trying "az interactive" on Debian Linux

### ISSUE THREAD

**Issue by vlijmenfileer** [Azure/azure-cli#11042]
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
cannot import name 'DEFAULTS_SECTION'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/interactive/custom.py, ln 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
cliextensions/interactive/azext_interactive/__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
interactive/azext_interactive/azclishell/app.py, ln 35, in <module>
    from azure.cli.core._config import DEFAULTS_SECTION
ImportError: cannot import name 'DEFAULTS_SECTION'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Linux-4.19.0-6-amd64-x86_64-with-debian-10.1
Python 3.6.5
Shell: bash

azure-cli 2.0.75

Extensions:
interactive 0.4.1

```

**Comment by yonzhan** [comment]
@jiasli add to S162.

**Comment by jiasli** [comment]
`interactive` has been updated to 0.4.3. Please try 
```
az extension update -n interactive
```

**Comment by vlijmenfileer** [comment]
I first tested I still got the original error.  I did.
I ran the update command as suggested, and tested again, see under.
Seems OK again now.  Thanks :)

"PS /home/user01/0_local_Volatile/0_tmp> az extension update -n interactive                                       
PS /home/user01/0_local_Volatile/0_tmp> az interactive                    
This command is in preview. It may be changed/removed in a future release.
az>> "
Plus the rest of the normal interface under it.
