### ISSUE TITLE
Error on batch-delete

### ISSUE THREAD

**Issue by 15pratik** [Azure/azure-cli#11043]
## Describe the bug

**Command Name**
`az storage blob delete-batch`

**Errors:**
```
('Connection broken: OSError("(104, \'ECONNRESET\')",)', OSError("(104, 'ECONNRESET')",))
Traceback (most recent call last):
site-packages/urllib3/contrib/pyopenssl.py, ln 304, in recv_into
    return self.connection.recv_into(*args, **kwargs)
python3.6/site-packages/OpenSSL/SSL.py, ln 1822, in recv_into
    self._raise_ssl_error(self._ssl, result)
python3.6/site-packages/OpenSSL/SSL.py, ln 1622, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

...

storage/v2018_11_09/common/storageclient.py, ln 361, in _perform_request
    raise _wrap_exception(ex, AzureException)
azure.common.AzureException: ('Connection broken: OSError("(104, \'ECONNRESET\')",)', OSError("(104, 'ECONNRESET')",))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob delete-batch -s {} --account-name {}`

## Environment Summary
```
Linux-4.15.0-66-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.75

```

**Comment by Juliehzl** [comment]
Hi @15pratik , your problem is a connection error. Can you try it again when you have good internet with --debug?
If it still  doesn't work, can you show me your debug output?

**Comment by 15pratik** [comment]
> Hi @15pratik , your problem is a connection error. Can you try it again when you have good internet with --debug?
> If it still doesn't work, can you show me your debug output?

I do not think the issue was with the internet, I think there are some scalability issues with it, I tried deleting files from 2 different containers, one of which had large number of files and one with lesser files. The one with lesser files way always successfully deleted, however, the container with large number of files faced issues.
I even tried to just list the blobs for the container with a large number of files, I was facing the same error.

I would also suggest you give additional functionality to delete all blobs in a container.

**Comment by Juliehzl** [comment]
Hi @15pratik, thanks a lot for your information. There are something we have to do for deleting all blobs in a container. We are developing a new `az storage remove` to delete blobs/files more effectively. I will add a functionality in `az storage remove` to delete all blobs in a container.
