### ISSUE TITLE
[az image create] Provide a way to set DATA disk caching

### ISSUE THREAD

**Issue by grecko123** [Azure/azure-cli#11045]
Using azure cli to deploy custom images (from a vhd file), leads to images with a default host caching to "None".

We should be able, by using arguments like '--storage-caching' and '--data-disk-caching' (like with 'az vm create'), to set the default host caching for the data disks like what is avaliable for OS disks.

**Comment by yonzhan** [comment]
@qwordy  add to S162.

**Comment by qwordy** [comment]
Yes. I do remember there is a host caching parameter in REST API.

**Comment by grecko123** [comment]
> Yes. I do remember there is a host caching parameter in REST API.

But only for OS disks, not for data disks

**Comment by qwordy** [comment]
I've created a PR

**Comment by qwordy** [comment]
Do you know is it able to update the caching type?

**Comment by qwordy** [comment]
If you have more questions, you can comment in this issue or open a new one.
