### ISSUE TITLE
az cli errors out on new installation on Fedora 31

### ISSUE THREAD

**Issue by dwaiba** [Azure/azure-cli#11058]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
`sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc

 sudo sh -c 'echo -e "[azure-cli]
> name=Azure CLI
> baseurl=https://packages.microsoft.com/yumrepos/azure-cli
> enabled=1
> gpgcheck=1
> gpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'

sudo yum install azure-cli
Azure CLI                                                                                                                                2.7 MB/s |  12 MB     00:04    
Docker CE Stable - x86_64                                                                                                                 10 kB/s | 3.5 kB     00:00    
Fedora Modular 31 - x86_64                                                                                                               5.5 kB/s | 5.1 kB     00:00    
Fedora Modular 31 - x86_64 - Updates                                                                                                     4.8 kB/s | 4.8 kB     00:01    
Fedora 31 - x86_64 - Updates                                                                                                             6.9 kB/s | 5.8 kB     00:00    
Fedora 31 - x86_64                                                                                                                       6.9 kB/s | 5.2 kB     00:00    
google-chrome                                                                                                                            7.6 kB/s | 1.3 kB     00:00    
RPM Fusion for Fedora 31 - Free - Updates                                                                                                 21 kB/s |  13 kB     00:00    
RPM Fusion for Fedora 31 - Free                                                                                                           19 kB/s |  15 kB     00:00    
Visual Studio Code                                                                                                                        11 kB/s | 2.9 kB     00:00    
Dependencies resolved.
=========================================================================================================================================================================
 Package                                             Architecture                    Version                                    Repository                          Size
=========================================================================================================================================================================
Installing:
 azure-cli                                           x86_64                          2.0.75-1.el7                               azure-cli                           27 M
Installing dependencies:
 python-unversioned-command                          noarch                          3.7.4-5.fc31                               fedora                              17 k
 python-wheel-wheel                                  noarch                          1:0.33.1-3.fc31                            fedora                              29 k
 python3-virtualenv                                  noarch                          16.6.1-2.fc31                              fedora                              98 k

Transaction Summary
=========================================================================================================================================================================
Install  4 Packages

Total download size: 27 M
Installed size: 237 M
Is this ok [y/N]: y
Downloading Packages:
(1/4): python-wheel-wheel-0.33.1-3.fc31.noarch.rpm                                                                                        75 kB/s |  29 kB     00:00    
(2/4): python-unversioned-command-3.7.4-5.fc31.noarch.rpm                                                                                 43 kB/s |  17 kB     00:00    
(3/4): python3-virtualenv-16.6.1-2.fc31.noarch.rpm                                                                                       182 kB/s |  98 kB     00:00    
(4/4): azure-cli-2.0.75-1.el7.x86_64.rpm                                                                                                 4.0 MB/s |  27 MB     00:06    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                    3.5 MB/s |  27 MB     00:07     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                 1/1 
  Installing       : python-wheel-wheel-1:0.33.1-3.fc31.noarch                                                                                                       1/4 
  Installing       : python3-virtualenv-16.6.1-2.fc31.noarch                                                                                                         2/4 
  Installing       : python-unversioned-command-3.7.4-5.fc31.noarch                                                                                                  3/4 
  Installing       : azure-cli-2.0.75-1.el7.x86_64                                                                                                                   4/4 
  Running scriptlet: azure-cli-2.0.75-1.el7.x86_64                                                                                                                   4/4 
  Verifying        : azure-cli-2.0.75-1.el7.x86_64                                                                                                                   1/4 
  Verifying        : python-unversioned-command-3.7.4-5.fc31.noarch                                                                                                  2/4 
  Verifying        : python-wheel-wheel-1:0.33.1-3.fc31.noarch                                                                                                       3/4 
  Verifying        : python3-virtualenv-16.6.1-2.fc31.noarch                                                                                                         4/4 

Installed:
  azure-cli-2.0.75-1.el7.x86_64   python-unversioned-command-3.7.4-5.fc31.noarch   python-wheel-wheel-1:0.33.1-3.fc31.noarch   python3-virtualenv-16.6.1-2.fc31.noarch  

Complete!
az login
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/__init__.py", line 1, in <module>
    ﻿__import__('pkg_resources').declare_namespace(__name__)
  File "/usr/lib64/az/lib/python2.7/site-packages/pkg_resources/__init__.py", line 24, in <module>
    import re
  File "/usr/lib64/python3.7/re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
`

**To Reproduce**
Install as per standard rocedure of rpm on Fedora 31

**Expected behavior**
az login should not throw error

**Environment summary**
rpm install
Fedora 31

**Additional context**

**Comment by yonzhan** [comment]
@fengzhou-msft  add to S161.

**Comment by fengzhou-msft** [comment]
will be fixed with 2.0.76, release soon.

**Comment by fengzhou-msft** [comment]
2.0.76 is released. Please yum update and reinstall azure-cli.
