### ISSUE TITLE
Trying to take class on Azure fundamentals - Login issue inside Microsoft

### ISSUE THREAD

**Issue by JeffGreenlee42** [Azure/azure-cli#11054]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Taking a class on Azure fundamentals:  https://lms.azedx.com/courses/course-v1:Microsoft+AZ-900+2019_T1/courseware/881ee5c0-b525-fe76-210c-7c479b6db568/958ef7f4-9d27-ea76-aa73-24b4e56f60fb/

**To Reproduce**

1 Walkthrough on interacting through AZ  CLI.   I am enrolled into AZ with a different account than my Microsoft alias...  I am able to create interactive prompt.. but when I try to log into the Azure account from within Microsoft domain.. I encounter a "problem".  

**Expected behavior**
It seems that one should be able to login to an Azure account regardless of where you are.  .

**Environment summary**
Your CLI is up-to-date.
PS C:\WINDOWS\system32> az --version
azure-cli                         2.0.75

command-modules-nspkg              2.0.3
core                              2.0.75
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\v-jefg\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal
**Additional context**

**Comment by yonzhan** [comment]
@jiasli  planned in S162.

**Comment by yonzhan** [comment]
add to S169

**Comment by jiasli** [comment]
@JeffGreenlee42, do you mind sharing what exactly the "problem" is?

**Comment by yonzhan** [comment]
add to S171

**Comment by jiasli** [comment]
Closing due to no detailed information. I will reopen once more information is provided.
