### ISSUE TITLE
Can't sign in with the -allow-no-subscriptions parameter

### ISSUE THREAD

**Issue by v-akhana** [Azure/azure-cli#11059]
**Resource Provider**
AZ CLI
az login
https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login

**Description of Feature or Work Requested**
Cannot sign in with the following command:
az login --service-principal -u <principal-id>-password <password>-tenant <tenant-id>--allow-no-subscriptions

If don't have the --allow-no-subscriptions parameter,  can sign in.

**Minimum API Version Required**
AZ CLI version 2.0.75

**Comment by yonzhan** [comment]
@jiasli  add to S161.
