### ISSUE TITLE
Out of memory when running az storage blob upload

### ISSUE THREAD

**Issue by sebasmannem** [Azure/azure-cli#1105]
I'm using az to upload an image to azure.
I'm using python3, but have seen the same issue with python2.
Image is 30G (although only 1,5 G sparse).
Eventually I managed to upload using --max-connections 1.
I traced the issue down to this little piece of code:
file: storage/blob/_upload_chunking.py, line:70
``` python
    if max_connections > 1:
        import concurrent.futures
        executor = concurrent.futures.ThreadPoolExecutor(max_connections)
        range_ids = list(executor.map(uploader.process_chunk, uploader.get_chunk_streams()))
    else:
        range_ids = [uploader.process_chunk(result) for result in uploader.get_chunk_streams()]
```
Problem is with the line
``` python
        range_ids = list(executor.map(uploader.process_chunk, uploader.get_chunk_streams()))
```
calling executor.map with parameter uploader.get_chunk_streams() creates a list with all the element that are yielded in get_chunk_streams().
This list holds all 30G of file data and is built in memory before passing it on to executor.map().

So, if you want to upload with maxconnections > 1, basically, you need at least (memory+swap) larger than file you wish to upload...

**Comment by tjprescott** [comment]
Hi @sebasmannem thank you for the issue report!

**Comment by tjprescott** [comment]
It appears this is a bug in the python storage SDK. https://github.com/Azure/azure-storage-python/issues/190

I've referenced your issue in that thread.

**Comment by tjprescott** [comment]
@troydai since you are working on the upload command, we should probably implement a workaround until this is fixed in the service. Basically set max_connections to 1 if the file being uploaded is large. Possibly log a warning when we do so.

**Comment by mayurid** [comment]
Updating sprint

**Comment by tjprescott** [comment]
Workaround is in, so I'm moving this to the backlog. When the SDK is fixed, the workaround can be removed and this can be closed.

**Comment by matthchr** [comment]
@tjprescott Any ETA on when the fix for this will be public on pypi? Also, won't it negatively impact performance significantly to only use `max_connections = 1` for large files?

**Comment by tjprescott** [comment]
@mattchr the fix will be in for the January 14th release. It will slow performance for large files, but that's better than crashing due to running out of memory. When the storage SDK is fixed, we will remove the workaround.

**Comment by williexu** [comment]
This should be fixed, I'll take a look to make sure

**Comment by williexu** [comment]
Was fixed with https://github.com/Azure/azure-storage-python/issues/190
