### ISSUE TITLE
How About Fixing az login

### ISSUE THREAD

**Issue by ssanbeg** [Azure/azure-cli#11069]
Hundreds of tickets opened. NO solutions. HOURS wasted on this crap.

How about fixing 
  az login
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

 ↵ 1  az --version
azure-cli                         2.0.75

command-modules-nspkg              2.0.3
core                              2.0.75
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/local/Cellar/azure-cli/2.0.75/libexec/bin/python'
Extensions directory '/Users/scsanbeg/.azure/cliextensions'

Python (Darwin) 3.7.5 (default, Nov  1 2019, 02:16:32)
[Clang 11.0.0 (clang-1100.0.33.8)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Mac OS Mojave 10.14.6
Python versions used: 2.7 3.7 3.8.0 - all fail

**Comment by yonzhan** [comment]
@jiasli  add to S161.

**Comment by jiasli** [comment]
Please see [the doc for using CLI behind a proxy](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy).
