### ISSUE TITLE
Trying to bring up the education data web project 

### ISSUE THREAD

**Issue by seanmunson** [Azure/azure-cli#11065]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
az webapp up: error: argument --name/-n: expected one argument
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --resource-group {} --sku {} --name`

## Environment Summary
```
Linux-4.15.0-1061-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.75

```

**Comment by panchagnula** [comment]
the command needs to run from the run from the context of local dir where the code is &  needs name for the webapp.
