### ISSUE TITLE
Ability to Create CorrelationFilter on ServiceBus Subscription

### ISSUE THREAD

**Issue by mreyeros** [Azure/azure-cli#11067]
Cannot create a CorrelationFilter rule on a ServiceBus Subscription via the CLI; cannot seem to find any available documentation for doing the same using the following CLI command:

az servicebus topic subscription rule create --resource-group myresourcegroup --namespace-name mynamespace --topic-name mytopic --subscription-name mysubscription --name myrule

**Comment by axisc** [comment]
[Here](https://docs.microsoft.com/en-us/cli/azure/servicebus/topic/subscription/rule?view=azure-cli-latest#az_servicebus_topic_subscription_rule_create) is the documentation for the subscription creation CLI command. The correlation filter must be created using the portal or programmatically.
