### ISSUE TITLE
Error running az storage container create -n messages --connection-string ...

### ISSUE THREAD

**Issue by ahalil000** [Azure/azure-cli#11064]
## Describe the bug

**Command Name**
`az storage container create`

**Errors:**
```
HTTPSConnectionPool(host='storage_account_name.blob.core.windows.net', port=443): Max retries exceeded with url: /messages?restype=container (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe90e074c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
python3.6/site-packages/urllib3/connection.py, ln 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
...
    raise _wrap_exception(ex, AzureException)
azure.common.AzureException: HTTPSConnectionPool(host='storage_account_name.blob.core.windows.net', port=443): Max retries exceeded with url: /messages?restype=container (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe90e074c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._

- az storage account create --name [storage account] --sku Standard_RAGRS --encryption blob
- `az storage container create -n {} --connection-string {}`

## Environment Summary
```
Linux-4.15.0-1061-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.75

```

**Comment by Juliehzl** [comment]
@ahalil000  According the error message, you cannot connect to the storage account endpoint, which is usually cause by poor Internet. Can you try again in a machine with good Internet?

**Comment by Juliehzl** [comment]
@ahalil000 Have your problem been solved? If yes, can you close the issue? If not, please share more information with us. If no more response, we will think your problem has been solved.
