### ISSUE TITLE
Azure cli -"bad handshake: error"

### ISSUE THREAD

**Issue by sudheeshvelangaraparambil** [Azure/azure-cli#11068]
I am getting error while using azure cli.

Getting error while doing 'az login' in terminal window.
Error is:
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

**To Reproduce**
Mac OS
Install azure-cli 2.0.75
Python 3.7.3 
'az login'

**Expected behavior**
Login success.

**Environment summary**
Installed azure cli using brew.

**Additional context**

**Comment by yonzhan** [comment]
@jiasli  add to S161.

**Comment by jiasli** [comment]
Please see [the doc for using CLI behind a proxy](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy).
