### ISSUE TITLE
acr module should use their mgmt SDK instead of including code in module

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1107]
Whilst https://github.com/Azure/azure-cli/pull/859 has been merged, it includes `mgmt_acr` in the module code.

Instead, it should depend on an mgmt SDK.
When that mgmt SDK has been packaged and published, the acr module should be updated accordingly.

This requires the swagger spec to be merged first https://github.com/Azure/azure-rest-api-specs/pull/549.

FYI: @djyou, @SajayAntony, @mayurid

**Comment by derekbekoe** [comment]
@JasonRShaver can we create an 'ACR' service label so we can label this issue?

**Comment by mayurid** [comment]
Marking this for Connect Milestone as Swagger is in review and believe this will happen for that. Let me know if there are concerns.

**Comment by mayurid** [comment]
@jasonrshaver and @derekbekoe : the label is created as well.

**Comment by SajayAntony** [comment]
@amarzavery can you please light up the SDK.

**Comment by mayurid** [comment]
@SajayAntony : I believe you are looking for the Python SDK to be published. You will need to work with @lmazuel who owns the https://github.com/Azure/azure-sdk-for-python repo

**Comment by lmazuel** [comment]
If the swagger is merged I can do that :). Is it?

Le mer. 2 nov. 2016 à 17:04, Mayuri Diwan <notifications@github.com> a
écrit :

**Comment by lmazuel** [comment]
@SajayAntony Building the SDK, I have:
```
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidResourceNamespace
Message: The resource namespace 'Microsoft.ContainerRegistry' is invalid.
```
Do you need my subscription id for me to be able to test this?

**Comment by SajayAntony** [comment]
@lmazuel yes you need an approved subscription.

**Comment by lmazuel** [comment]
@derekbekoe @SajayAntony Released as a Python SDK:
https://pypi.python.org/pypi/azure-mgmt-containerregistry/0.1.0

**Comment by derekbekoe** [comment]
PR merged. Closing issue.
