### ISSUE TITLE
Calling az extension update -n azure-cli-ml throws the exception

### ISSUE THREAD

**Issue by michaelnemtsev** [Azure/azure-cli#11078]
## Describe the bug

**Command Name**
`az extension update`

**Errors:**
```
[WinError 5] Access is denied: 'C:\\Users\\michaeln\\.azure\\cliextensions\\azure-cli-ml\\_ruamel_yaml.cp36-win32.pyd'
Traceback (most recent call last):
pip-install-p8t_6awn\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 654, in _run_job
Temp\pip-install-p8t_6awn\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 631, in _run_job
cli\core\commands\__init__.py, ln 306, in __call__
...
Azure\CLI2\lib\shutil.py, ln 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
Azure\CLI2\lib\shutil.py, ln 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\michaeln\\.azure\\cliextensions\\azure-cli-ml\\_ruamel_yaml.cp36-win32.pyd'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension update -n {}`

## Environment Summary
```
Windows-10-10.0.19013-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.75

```

**Comment by yonzhan** [comment]
@zikalino  add to S161.

**Comment by haroldrandom** [comment]
I could update vmware-cs
![image](https://user-images.githubusercontent.com/14357159/70400888-10dc1080-1a68-11ea-8f8f-fef45f6d7196.png)

I encountered the same error as yours when I was tring to delete and update azure-cli-ml extension under PowerShell.

It's related to a file named _**_ruamel_yaml.cp36-win32.pyd**_ , I can not see their code, so please service team of Machine Learning take a look

**Comment by yonzhan** [comment]
@haroldrandom did you find who from service team can deal with this issue?

**Comment by lostmygithubaccount** [comment]
@michaelnemtsev are you still facing this issue?

**Comment by v-strudm-msft** [comment]
Since there hasn't been a response to this issue in the last several months, we assume it was resolve and will close it. Should there still be a question, please open a new issue and we will respond on a timely basis. Thank you.
