### ISSUE TITLE
Missing spaces in function app create warning message

### ISSUE THREAD

**Issue by balag0** [Azure/azure-cli#11071]
Add spaces 

https://github.com/Azure/azure-cli/blob/ea5496bf7ee188da599dd3b009fc63d24967154a/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L2337-L2339

Current output looks like
**that uses a consumption plan has been successfullycreated but is not active until content is published usingAzure Portal**

**Comment by RakeshMohanMSFT** [comment]
@balag0 This is fixed
