### ISSUE TITLE
exception during 'az webapp up' on 'Exercise - Deploy an application that uses OpenID Connect to authenticate users' page

### ISSUE THREAD

**Issue by SergiiGalai** [Azure/azure-cli#11076]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
'NoneType' object has no attribute 'upper'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 652, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/command_modules/appservice/custom.py, ln 2993, in webapp_up
    create_app_service_plan(cmd, rg_name, plan, _is_linux, False, sku, 1 if _is_linux else None, location)
cli/command_modules/appservice/custom.py, ln 1390, in create_app_service_plan
    sku = _normalize_sku(sku)
cli/command_modules/appservice/utils.py, ln 20, in _normalize_sku
    sku = sku.upper()
AttributeError: 'NoneType' object has no attribute 'upper'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- https://docs.microsoft.com/en-us/learn/modules/secure-app-with-oidc-and-azure-ad/5-exercise-deploy-app-with-oidc-auth
- git clone https://github.com/MicrosoftDocs/mslearn-secure-app-with-oidc-and-azure-ad.git
- cd ~/mslearn-secure-app-with-oidc-and-azure-ad/app
- code appsettings.json
enter client id, tenant id, domain name, save and close editor
- `az webapp up --resource-group learn-11042bc3-4e4e-4d35-94b0-08d08f06ee6c --sku F1 --name educationapp-$RANDOM`

## Environment Summary
```
Linux-4.15.0-1061-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```

**Comment by mcurko** [comment]
Same problem here:
https://docs.microsoft.com/en-us/learn/modules/secure-aspnet-core-identity/3-add-identity?pivots=sql
after the step:
az webapp up

**Comment by panchagnula** [comment]
Fixed by https://github.com/Azure/azure-cli/pull/11019
