### ISSUE TITLE
Confusing encoding information

### ISSUE THREAD

**Issue by leighghunt** [Azure/azure-cli#11084]
The documentation for `az keyvault secret download --encoding` is IMHO a bit confusing.

**Documentation**: 

> Encoding of the destination file. By default, will look for the 'file-encoding' tag on the secret. Otherwise will assume 'utf-8'.

However the `--encoding` argument is actually referring to the encoding of the stored secret, not the encoding to use on the downloaded destination file. Would "source secret" be more accurate than "destination file"?

**More information:**
Consider the following, where I've created a certificate and am downloading the PFX - which is stored as base64 encoded text.

Specifying either `--encoding ascii ` or no `--encoding` argument downloads the file as text.
Specifying `--encoding base64` decodes the contents from base64 and downloads the file as binary.

```
✔ ~/azure-secrets-test 
13:13 $ az keyvault secret download --name spvenaripemname  --file secret.ascii.pem --encoding ascii --vault-name venari-test1-keyvault
✔ ~/azure-secrets-test 
13:14 $ az keyvault secret download --name spvenaripemname  --file secret.base64.pem --encoding base64 --vault-name venari-test1-keyvault
✔ ~/azure-secrets-test 
13:14 $ az keyvault secret download --name spvenaripemname  --file secret.raw.pem --vault-name venari-test1-keyvault
✔ ~/azure-secrets-test 

13:14 $ cat secret.ascii.pem 
MIIKTAIBAz.....YTntgG1IbfJbI4x6yU
✔ ~/azure-secrets-test 

13:15 $ cat secret.base64.pem 
0?
L0?
...
...
?	Ҡ(?Տr㕛?p??B?H??w3C?O?{Р??iJgcLwO?e2??x#??H?0700+?"^^r?S??
T??M
    ??~?i.l???Ԇ?%?8Ǭ?
✔ ~/azure-secrets-test 

13:15 $ cat secret.raw.pem 
MIIKTAIBAz.....YTntgG1IbfJbI4x6yU
✔ ~/azure-secrets-test 

13:15 $ base64 secret.base64.pem 
MIIKTAIBAz.....YTntgG1IbfJbI4x6yU
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39cfb8ed-c246-2ffb-9dff-070b90c18b21
* Version Independent ID: c09c1597-1b6c-b0a2-b3fc-bdc16764d096
* Content: [az keyvault secret](https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli add to S162.

**Comment by bim-msft** [comment]
@leighghunt Thanks for your feedback, this advice sounds reasonable, I'll make some modifications in documents and help messages.
