### ISSUE TITLE
[ACI] terminal window size not resizing when doing az container exec into bash shell

### ISSUE THREAD

**Issue by nofunatall** [Azure/azure-cli#11083]
## Describe the bug
The terminal doesn't fit to window correctly when doing az container exec into a bash shell
Possibly related to this docker issue?
https://github.com/moby/moby/issues/35407
https://github.com/docker/for-linux/issues/314

**Command Name**
`az container exec`

## To Reproduce:
- `az container exec --container-name somecontainer --name someinstance --resource-group somegroup --exec-command /bin/bash`

![Screenshot from 2019-11-04 13-31-05](https://user-images.githubusercontent.com/23159875/68094710-134ac800-ff08-11e9-823e-d0ec86b8c2ce.png)

## Environment Summary
```
Linux-5.3.0-19-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.75

```

**Comment by navba-MSFT** [comment]
@nofunatall Apologies for the late reply. Could you please confirm if you are still running into this issue ? This issue is open for quite sometime. Please let us know if you need any further assistance on this.
