### ISSUE TITLE
Can't do API Management Learn Modile

### ISSUE THREAD

**Issue by robzison** [Azure/azure-cli#11098]
## Describe the bug

**Command Name**
`az functionapp create`

**Errors:**
```
The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Run bash setup.sh from step 2 of the instructions on https://docs.microsoft.com/en-us/learn/modules/build-serverless-api-with-functions-api-management/3-exercise-import-function-app-api-management?source=learn
- `az functionapp create --resource-group {} --consumption-plan-location {} --name {} --storage-account {} --runtime {}`

## Environment Summary
```
Linux-4.15.0-1061-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```

**Comment by ahmedelnably** [comment]
This is not an Azure CLI issue, the script in the Learn module is written against westus region, please change it to another US region (ex. centralus)
