### ISSUE TITLE
Azure Storage Blob Delete should not require container name

### ISSUE THREAD

**Issue by MadDenker** [Azure/azure-cli#11097]
I am unable to delete a blob because I do not have a container name.  I believe this was changed when storage accounts were upgraded to v2.  Can you update the syntax?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-delete)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by fengzhou-msft** [comment]
@Juliehzl please take a look at this issue.

**Comment by Juliehzl** [comment]
Hi @MadDenker , container name is required based on python SDK. Could you please tell me why you have such conclusion to give us more information?

**Comment by MadDenker** [comment]
When I try to delete a blob with 'az storage blob delete, it requires a blob name and a container name. 
![image](https://user-images.githubusercontent.com/16837956/68310064-6003df80-007d-11ea-9e42-230a22934b15.png)
Where do I find these?  They seem like the same thing to me.  In fact, Storage Explorer calls them Blob Containers.  
![image](https://user-images.githubusercontent.com/16837956/68310144-7f9b0800-007d-11ea-8ded-5221c054aa34.png)
This is extremely confusing to users.

**Comment by Juliehzl** [comment]
Hi @MadDenker, you can find the blob storage structure [here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction#blob-storage-resources). Blob Containers in Storage Explorer is just container in storage account.
If you want to delete a blob in container, you should use `az storage blob delete`. If you want to delete a container including all the blobs inside, you can use `az storage container delete`. Hope it is clear enough to you.
It is not CLI bug and I will close the issue now. If you still have problems, feel free to reopen it. 
Anyway, thanks a lot for your feedback. 😊
