### ISSUE TITLE
az cli is missing eoan (19.10) release files

### ISSUE THREAD

**Issue by heytjr** [Azure/azure-cli#11096]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 
n/a Cloud install fails 

**Describe the bug**
Current the az cli team does not publish an 19.10 release file 

**To Reproduce**
Steps to reproduce the behavior.
- Install Ubuntu 19.10
- curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

**Expected behavior**
That the az cli team supports major Ubuntu releases. 

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
Fetched 374 kB in 2s (177 kB/s)                              
Reading package lists... Done
apt-get install -y apt-transport-https lsb-release gnupg curl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.65.3-1ubuntu3).
gnupg is already the newest version (2.2.12-1ubuntu3).
gnupg set to manually installed.
lsb-release is already the newest version (11.0.1ubuntu1).
lsb-release set to manually installed.
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 1,704 B of archives.
After this operation, 157 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 apt-transport-https all 1.9.4 [1,704 B]
Fetched 1,704 B in 0s (9,722 B/s)               
Selecting previously unselected package apt-transport-https.
(Reading database ... 177803 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.9.4_all.deb ...
Unpacking apt-transport-https (1.9.4) ...
Setting up apt-transport-https (1.9.4) ...
set +v
curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.asc.gpg
set +v
CLI_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ ${CLI_REPO} main" \
    > /etc/apt/sources.list.d/azure-cli.list
apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable Release                                                                  
Ign:3 http://www.scootersoftware.com bcompare4 InRelease                                                                    
**Ign:4 https://packages.microsoft.com/repos/azure-cli eoan InRelease**                                                         
Hit:5 http://www.scootersoftware.com bcompare4 Release                                                                      
Err:6 https://packages.microsoft.com/repos/azure-cli eoan Release                                          
  404  Not Found [IP: 13.91.48.226 443]
Hit:7 http://us.archive.ubuntu.com/ubuntu eoan InRelease                                                   
Hit:9 http://security.ubuntu.com/ubuntu eoan-security InRelease                   
Hit:10 http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease                 
Hit:12 http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease
Reading package lists... Done
**E: The repository 'https://packages.microsoft.com/repos/azure-cli eoan Release' does not have a Release file.**
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by fengzhou-msft** [comment]
Thanks for reporting the issue. We will evaulate the effort to add eoan support.

**Comment by AkihiroSuda** [comment]
any update?

**Comment by fengzhou-msft** [comment]
Currently we don't have plans to add support for non-LTS Ubuntu distributions. But you can make use of bionic release file by making `AZ_REPO=bionic` in step 3 of [Manual install instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#manual-install-instructions). 

I will also improve the script for better compatibility.

**Comment by fengzhou-msft** [comment]
Actually we should support [current ubuntu releases](https://wiki.ubuntu.com/Releases) including eoan. I will push this forward.

**Comment by fengzhou-msft** [comment]
Added support for eoan. Please try again.

**Comment by qidydl** [comment]
Looks to be working, I was able to update to version 2.0.77.

**Comment by fearphage** [comment]
> Actually we should support [current ubuntu releases](https://wiki.ubuntu.com/Releases) including eoan. I will push this forward.

@fengzhou-msft  Any way to add this when the release are in alpha/beta instead of almost 2 months after release? For the record, Eoan was released October 17, 2019.
