### ISSUE TITLE
az backup - Invalid API version for GetBackupProtectedItems

### ISSUE THREAD

**Issue by KingOfSpades** [Azure/azure-cli#11107]
## Describe the bug
When running az backup item list the CLI produces an error:

```
Invalid API version for GetBackupProtectedItems.
Please user api version 2019-05-13 or higher.
```

**Command Name**
`az backup item list`

**Errors:**
```
Invalid API version for GetBackupProtectedItems.
Please user api version 2019-05-13 or higher.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Run Azure Backup command to list items_
- `az backup item list -g resource-group -v vaultName`

## Expected Behavior
A list of backup items.

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```

**Comment by KingOfSpades** [comment]
Any updates on this? I understand that this is not a break/fix issue but it would be nice for the functionality to be restored.

**Comment by mindcurv-jaison** [comment]
Still facing the same problem at my end.
`Invalid API version for GetBackupProtectedItems.
Please user api version 2019-05-13 or higher.`

**Comment by KingOfSpades** [comment]
Seems to work again! Using :

```
azure-cli                         2.0.77

command-modules-nspkg              2.0.3
core                              2.0.77
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/local/Cellar/azure-cli/2.0.77/libexec/bin/python'
Extensions directory '/Users/christian/.azure/cliextensions'

Python (Darwin) 3.7.5 (default, Nov  1 2019, 02:16:23) 
[Clang 11.0.0 (clang-1100.0.33.8)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
```

**Comment by pvrk** [comment]
We have updated CLI, PS versions and released compatible SDKs by end of Nov. Thanks for verifying. Closing this issue.
