### ISSUE TITLE
The specified resource does not exist. ErrorCode: ResourceNotFound

### ISSUE THREAD

**Issue by vb167638** [Azure/azure-cli#11105]
## Describe the bug

**Command Name**
`az storage blob upload`

**Errors:**
```
The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:4aaba46f-301e-012d-2fae-93e969000000
Time:2019-11-05T07:53:49.7873039Z</Message></Error>
Traceback (most recent call last):
pip-install-ygnynjtx\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 560, in execute
cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
...
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:4aaba46f-301e-012d-2fae-93e969000000
Time:2019-11-05T07:53:49.7873039Z</Message></Error>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload -c {} -f {} -n {} --account-name {} --sas-token {}`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.66

```

**Comment by fengzhou-msft** [comment]
@Juliehzl please take a look.

**Comment by Juliehzl** [comment]
@vb167638 Can you show me more information with `--debug` in your command? Please confirm container exists in your storage account and upgrade azure-cli to the latest version to use new features if no specific requirements in your current azure cli version.

**Comment by zffocussss** [comment]
I use az storage share create to create a share,it throws exceptions.
he command failed with an unexpected error. Here is the traceback:

The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:a0e04024-d01a-0011-47bc-a51aaf000000

**Comment by zffocussss** [comment]
 ↵ 1  az --version
azure-cli                         2.0.71 *

command-modules-nspkg               2.0.3
core                              2.0.71 *
nspkg                              3.0.4
telemetry                          1.0.3 *

Python location '/usr/local/Cellar/azure-cli/2.0.71/libexec/bin/python'
Extensions directory '/Users/focus/.azure/cliextensions'

Python (Darwin) 3.7.5 (default, Nov 19 2019, 14:29:27)
[Clang 10.0.0 (clang-1000.10.44.4)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by Juliehzl** [comment]
Hi @zffocussss , can you show more information with `--debug` in your command?

**Comment by yonzhan** [comment]
Hi @zffocussss, any feedback/update for this ?

**Comment by Juliehzl** [comment]
Because there is no response for several days, I will close this issue and if there is still a problem, please feel free to reopen it.
