### ISSUE TITLE
Is there any way to get an access token with scopes?

### ISSUE THREAD

**Issue by 0GiS0** [Azure/azure-cli#11109]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named api://weather/weather.read was not found in the tenant named 7a8513af-dca8-4b25-b005-42d3a863dd07. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: d394a935-ff23-4f93-b445-6a74b8067000\r\nCorrelation ID: e2f3cb11-0e86-4af1-b8b9-81ab0039ec3e\r\nTimestamp: 2019-11-05 13:23:18Z","error_codes":[500011],"timestamp":"2019-11-05 13:23:18Z","trace_id":"d394a935-ff23-4f93-b445-6a74b8067000","correlation_id":"e2f3cb11-0e86-4af1-b8b9-81ab0039ec3e","error_uri":"https://login.microsoftonline.com/error?code=500011"}
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --audience {} --scopes {}`

## Expected Behavior

Get an access token with the scopes

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.5
Shell: bash

azure-cli 2.0.75 *

Extensions:
dev-spaces-preview 0.1.6

```

**Comment by jiasli** [comment]
May I know what `scopes` means here? RBAC or tenant? 

`az account get-access-token` only supports 3 arguments `--resource`, `--resource-type`, `--subscription -s` (get help by running `az account get-access-token -h`). Since access token is issued for a specific service principal or user from a tenant/directory, it doesn't have any information regarding RBAC scope. 

More info: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

**Comment by 0GiS0** [comment]
Hi @jiasli,

Imagine that I want to get an access token with the scopes https://graph.microsoft.com/User.Read and https://graph.microsoft.com/Calendar.Read 

Can I specify in some way what scopes I need to be include them in the access token? I think the answer is no...

Thanks again,

**Comment by jiasli** [comment]
Hi @0GiS0, your understanding is correct. Access token only represents a user/SP, it can't have any scope in it.

**Comment by spoelstraethan** [comment]
Apparently scopes did get added at some point. https://techcommunity.microsoft.com/t5/healthcare-and-life-sciences/just-give-me-an-access-token/ba-p/3292215
