### ISSUE TITLE
Specialized Image Support + Snapshot as creation source in Az CLI for Shared Image Gallery

### ISSUE THREAD

**Issue by agrawalkshitij** [Azure/azure-cli#11117]
**Resource Provider**
What is the Azure resource provider your feature is part of? Microsoft.Compute

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
Support OSState = Specialized in Gallery image-definition

And Snapshots ids in storageProfile.osdiskImage.source.id, make managed-image as optional.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?2019-07-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.[gallery.json]

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests. 11/06/2019

**Comment by fengzhou-msft** [comment]
@qwordy please take a look and evaluate the work.

**Comment by yonzhan** [comment]
@qwordy  add to S161.

**Comment by qwordy** [comment]
I have modified code to use storage profile in #11092, commit - Fix VMGalleryImage.test_gallery_e2e
Full features will be covered in another PR.

**Comment by qwordy** [comment]
I've added --os-state and --hyper-v-generation.

**Comment by qwordy** [comment]
If you have other questions, comment in this issue or open a new issue. Thanks.
