### ISSUE TITLE
Azure AD application for Azure CLI supporting personal accounts

### ISSUE THREAD

**Issue by FeodorFitsner** [Azure/azure-cli#11115]
Hello,

I'm sorry if this is the wrong place to ask, but I still want to give it a try hoping Azure CLI developers could know the answer.

We've been trying to setup Azure AD application that could manage https://management.core.windows.net/ resource/scope and allow both personal and company/school AD accounts. Right now if you create a new App registration with `	Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)` option and then try using [OAuth 2.0 code grant flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code) with your app Client ID and `https://management.core.windows.net/` resource it won't allow personal accounts with `AADSTS50020: User account from identity provider 'live.com' does not exist in tenant 'Default Directory' and cannot access the application in that tenant.` error.

At the same time Azure CLI uses the same [v1 OAuth endpoint](https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/_profile.py#L1109-L1112) to get a token with the same [`resource` value](https://github.com/Azure/azure-cli/blob/8adf97355a605d147afc26f6c1b6f6afb6651c2f/src/azure-cli-core/azure/cli/core/cloud.py#L165) and personal accounts **are** allowed.

Could you please share how did you setup the application (or are there any tricks in OAuth flow) to support personal accounts with https://management.core.windows.net/ resource/scope.

Thank you in advance!

**Comment by jiasli** [comment]
Hi Feodor, we are willing to help but we don't support AAD product. You may raise an Azure support request at https://azure.microsoft.com/en-us/support/create-ticket/. A support engineer will be glad to help you.

**Comment by FeodorFitsner** [comment]
@jiasli I'm not actually asking for support, but I was hoping you guys could share your experience. I saw people suggesting on the internet that it's not possible to manage https://management.core.windows.net/ resource with "personal" live.com-ish account, but the [AD application for Azure CLI](https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/_profile.py#L64) is able to authenticate with personal account. How did you configure it?

**Comment by qianwens** [comment]
Hi @FeodorFitsner , Azure CLI has its own client application id, the question you asked is out of our profession, We would suggest you raise an Azure support request https://azure.microsoft.com/en-us/support/create-ticket/ for this kind of question.
