### ISSUE TITLE
limitations on --name are not documented

### ISSUE THREAD

**Issue by ausfestivus** [Azure/azure-cli#11124]
There appears to be a restriction on the valid characters for use in the --name parameter. eg.

A rule creation with this name fails: `--name Allow-XXX.XXX.XXX.XXX-All` where XXX is a normal dotted-quad IPv4 address.
A rule creation with this name succeeds: `--name Allow-TEXT-All`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca574ee0-11f3-5eb3-4ab6-3fed9e42d6d6
* Version Independent ID: d4febc64-c4a8-742e-63fc-1bcab825d36c
* Content: [az postgres server firewall-rule](https://docs.microsoft.com/en-us/cli/azure/postgres/server/firewall-rule?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/postgres/server/firewall-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/postgres/server/firewall-rule.yml)
* Service: **postgres**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rachel-msft** [comment]
Thank you for getting in touch. We will provide a date at which the requirements documentation will be available.

**Comment by rachel-msft** [comment]
We expect the update in the document to be available in January.
(Internal tracking number: 551931)

**Comment by rachel-msft** [comment]
Documentation has been updated.
