### ISSUE TITLE
Updates for VMSS Orchestration Mode Parameters

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#11123]
**Resource Provider**
What is the Azure resource provider your feature is part of?

Compute Resource Provider

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.

Update VMSS Orchestration mode parameters as discussed:
1.	Support availability zone
2.	Should not need to specify credentials
3.	Remove LB, PIP, NSG Create when creating in VM mode
4.	Check VMSS zonal constraints

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2019-03-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-03-01/compute.json

More specifically
https://github.com/Azure/azure-rest-api-specs/blob/cb742dc4f7afe52a95e1ae79c1aa5a5906e49c08/specification/compute/resource-manager/Microsoft.Compute/stable/2019-03-01/compute.json#L3049

Here are some example templates
https://github.com/fitzgeraldsteele/azure-quickstart-templates/tree/master/201-vm-vmss-orchestrator

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
12-31-2019

**Comment by fengzhou-msft** [comment]
@qwordy please take a look and evaulate the work.

**Comment by yonzhan** [comment]
@qwordy  add to S161.

**Comment by qwordy** [comment]
> 
> 
> @qwordy add to S161.

OK.

**Comment by qwordy** [comment]
You will see the changes in Azure CLI 2.0.77. Code complete: 11/20/2019 Build to Cloud Shell: 11/22/2019 Official Release: 11/26/2019

**Comment by qwordy** [comment]
If you have other problems, you can comment here or open a new one.
