### ISSUE TITLE
My command doesn't work more

### ISSUE THREAD

**Issue by angelomelgar** [Azure/azure-cli#11135]
## Describe the bug

**Command Name**
`az storage directory create`

**Errors:**
```
Incorrect padding
Traceback (most recent call last):
storage\v2018_11_09\common\_auth.py, ln 69, in _add_authorization_header
storage\v2018_11_09\common\_common_conversion.py, ln 91, in _sign_string
storage\v2018_11_09\common\_common_conversion.py, ln 81, in _decode_base64_to_bytes
Azure\CLI2\lib\base64.py, ln 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

...

storage\v2018_11_09\common\_auth.py, ln 94, in sign_request
storage\v2018_11_09\common\_auth.py, ln 75, in _add_authorization_header
azure.multiapi.storage.v2018_11_09.common._error.AzureSigningError: Incorrect padding
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage directory create --name {} --share-name {} --account-name {} --account-key {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.72 *

```

**Comment by fengzhou-msft** [comment]
@Juliehzl please take a look.

**Comment by Juliehzl** [comment]
@angelomelgar Can you double check your account key value? This kind of error is typically caused by wrong account key format or value.

**Comment by angelomelgar** [comment]
Thanks so much, was the key.
