### ISSUE TITLE
Add support for auto-pilot throughput feature for cosmosdb

### ISSUE THREAD

**Issue by thisisbrianstewart** [Azure/azure-cli#11137]
**Is your feature request related to a problem? Please describe.**
I manage all of my infrastructure as code, using az cli scripts.  When provisioning cosmosdb resources, I want to be able to configure the auto-pilot preview feature for throughput rather than just the numeric R/U option via --throughput flag.  While I understand this feature is in preview, this feature massively eases the billing burden of spiky loads and I recommend it to all of my colleagues and use it myself.  It really pains me to manage all my infrastructure as code, but have to manage cosmosdb by using the portal -- especially when recommending to others.

**Describe the solution you'd like**
Add options to az cosmosdb create/update to allow input for using auto-pilot throughput & auto-pilot throughput range (the portal displays these options).  E.g.
`az cosmosdb database create ... --auto-pilot true --auto-pilot-max-throughput 1000 ...`

**Describe alternatives you've considered**
You have to manage cosmosdb via the portal -- it has disrupted my workflow and GitOps pipelines, as I now have a manual step (which unfortunately is worth it for the auto-pilot benefit).

**Additional context**
![Untitled](https://user-images.githubusercontent.com/20962640/68359146-27452400-00d8-11ea-97ce-b50530af3148.jpg)

**Comment by shurd** [comment]
Hi @thisisbrianstewart thank you for opening this issue. As this feature is still in preview, we are going to wait to add support via the CLI for now. We do not yet have a timeline for adding this feature, but we plan on adding it once we have more feedback. We are tracking this internally as work item 541736. I will update once we get closer to adding support.

**Comment by yonzhan** [comment]
move to S167

**Comment by yonzhan** [comment]
move to S168

**Comment by yonzhan** [comment]
move to S169

**Comment by yonzhan** [comment]
move to S170

**Comment by yonzhan** [comment]
move to S171

**Comment by shurd** [comment]
I believe @ravgill is working on adding support for this in the CLI now.

**Comment by MehaKaushik** [comment]
This was merged in the last release branch.
