### ISSUE TITLE
Cannot update azure-cli to release 2.0.76 on osx

### ISSUE THREAD

**Issue by explora21** [Azure/azure-cli#11133]
Trying to install the latest version of Azure-cli on osx using homebrew, but no matter what I'm doing:
- Upgrade
- reinstall
- remove then install
I'm still getting the version 2.0.75 of Azure-cli

**Comment by fengzhou-msft** [comment]
we are waiting for Homebrew team to merge PR: https://github.com/Homebrew/homebrew-core/pull/46244

**Comment by fengzhou-msft** [comment]
2.0.76 is now available on Homebrew.
