### ISSUE TITLE
unregistering backup container of backup management type 'azureiaasvm' is not working

### ISSUE THREAD

**Issue by ahanaseem-gitid** [Azure/azure-cli#11141]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Following az cli command in not working as expected, when run inside azure cloud shell

az backup container unregister

When we issue the command unregister the backup container, reports as completed with return code of '0'. But the backup container still excists.

**To Reproduce**
Steps to reproduce the behavior.

Note: command output has been redacted with subscription id  being masked.

PS Azure:\> az backup container unregister --container-name "myvm" --resource-group MyResourceGroupvm --vault-name vault295 --backup-management-type azureiaasvm --debug

Command arguments: ['backup', 'container', 'unregister', '--container-name', 'myvm', '--resource-group', 'MyResourceGroupvm', '--vault-name', 'vault295', '--backup-management-type', 'azureiaasvm', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f6cc5f7ad08>, <function OutputProducer.on_global_arguments at 0x7f6cc5ab5b70>, <function CLIQuery.on_global_arguments at 0x7f6cc5adebf8>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql','sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.017 seconds.
Loaded module 'acs' in 0.007 seconds.
Loaded module 'advisor' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.005 seconds.
Loaded module 'apim' in 0.002 seconds.
Loaded module 'appconfig' in 0.003 seconds.
Loaded module 'appservice' in 0.010 seconds.
Loaded module 'backup' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.009 seconds.
Loaded module 'batchai' in 0.003 seconds.
Loaded module 'billing' in 0.002 seconds.
Loaded module 'botservice' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.002 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.002 seconds.
Loaded module 'consumption' in 0.002 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.006 seconds.
Loaded module 'deploymentmanager' in 0.002 seconds.
Loaded module 'dla' in 0.004 seconds.
Loaded module 'dls' in 0.003 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.003 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.002 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.005 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.005 seconds.
Loaded module 'kusto' in 0.003 seconds.
Loaded module 'lab' in 0.003 seconds.
Loaded module 'managedservices' in 0.002 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.006 seconds.
Loaded module 'natgateway' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.003 seconds.
Loaded module 'network' in 0.030 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.004 seconds.
Loaded module 'profile' in 0.001 seconds.
Loaded module 'rdbms' in 0.006 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.002 seconds.
Loaded module 'resource' in 0.007 seconds.
Loaded module 'role' in 0.005 seconds.
Loaded module 'search' in 0.004 seconds.
Loaded module 'security' in 0.003 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.003 seconds.
Loaded module 'signalr' in 0.002 seconds.
Loaded module 'sql' in 0.007 seconds.
Loaded module 'sqlvm' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.031 seconds.
Loaded module 'vm' in 0.015 seconds.
Loaded all modules in 0.268 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/naseem/.azure/cliextensions'
Found 2 extensions: ['interactive', 'storage-preview']
Extensions directory: '/home/naseem/.azure/cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.76 min_required=2.0.62 max_required=None
Loaded extension 'interactive' in 0.000 seconds.
Extensions directory: '/home/naseem/.azure/cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.76 min_required=2.0.52 max_required=None
Event: CommandLoader.OnLoadCommandTable []
Extensions directory: '/home/naseem/.azure/cliextensions'
Loaded extension 'storage-preview' in 0.006 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f6cc585cea0>]
az_command_data_logger : command args: backup container unregister --container-name {} --resource-group {} --vault-name {} --backup-management-type {} --debug
metadata file logging enabled - writing logs to '/home/naseem/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f6cc57feea0>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f6cc57b5a60>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f6cc57b5bf8>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f6cc3393bf8>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f6cc5ab5bf8>, <function CLIQuery.handle_query_parameter at 0x7f6cc5adec80>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f6cc57b5ae8>, <function handler at 0x7f6cc3258ea0>]
Command group 'backup' is in preview. It may be changed/removed in a future release.
Are you sure you want to perform this operation? (y/n): y
Getting management service client client_type=RecoveryServicesBackupClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
Getting management service client client_type=RecoveryServicesBackupClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.async_paging : Paging async iterator protocol is not available for ProtectionContainerResourcePaged
urllib3.connectionpool : Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool : http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 1893
msrestazure.azure_active_directory : MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
urllib3.connectionpool : Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool : http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 1893
msrestazure.azure_active_directory : MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
msrest.http_logger : Request URL: 'https://management.azure.com/Subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/MyResourceGroupvm/providers/Microsoft.RecoveryServices/vaults/vault295/backupProtectionContainers?api-version=2016-12-01&$filter=backupManagementType%20eq%20%27AzureIaasVM%27%20and%20friendlyName%20eq%20%27myvm%27%20and%20status%20eq%20%27Registered%27'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'User-Agent': 'python/3.6.5 (Linux-4.15.0-1061-azure-x86_64-with-debian-stretch-sid) msrest/0.6.9 cloud-shell/1.0 msrest_azure/0.6.2 azure-mgmt-recoveryservicesbackup/0.4.0 Azure-SDK-For-Python AZURECLI/2.0.76 cloud-shell/1.0'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "GET /Subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/MyResourceGroupvm/providers/Microsoft.RecoveryServices/vaults/vault295/backupProtectionContainers?api-version=2016-12-01&$filter=backupManagementType%20eq%20%27AzureIaasVM%27%20and%20friendlyName%20eq%20%27myvm%27%20and%20status%20eq%20%27Registered%27 HTTP/1.1" 200 None
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Transfer-Encoding': 'chunked'
msrest.http_logger :     'Content-Type': 'application/json'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'x-ms-request-id': '6faa89c7-ba0d-4e9f-92a3-732917619f58'
msrest.http_logger :     'x-ms-client-request-id': 'f8f74308-0127-11ea-8f72-0a580af46964, f8f74308-0127-11ea-8f72-0a580af46964'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Server': 'Microsoft-IIS/10.0'
msrest.http_logger :     'X-Powered-By': 'ASP.NET'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-reads': '11995'
msrest.http_logger :     'x-ms-correlation-request-id': '6faa89c7-ba0d-4e9f-92a3-732917619f58'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTINDIA:20191107T062946Z:6faa89c7-ba0d-4e9f-92a3-732917619f58'
msrest.http_logger :     'Date': 'Thu, 07 Nov 2019 06:29:45 GMT'
msrest.http_logger : Response content:
msrest.http_logger : {"value":[{"id":"/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourcegroups/myresourcegroupvm/providers/microsoft.recoveryservices/vaults/vault295/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;myresourcegroupvm;myvm","name":"IaasVMContainer;iaasvmcontainerv2;myresourcegroupvm;myvm","type":"Microsoft.RecoveryServices/vaults/backupFabrics/protectionContainers","properties":{"virtualMachineId":"/subscriptions/a50e62e8-faa1-47c5-b9c3-2d4ddaca60dc/resourceGroups/myResourceGroupVM/providers/Microsoft.Compute/virtualMachines/myvm","virtualMachineVersion":"Compute","resourceGroup":"myResourceGroupVM","friendlyName":"myvm","backupManagementType":"AzureIaasVM","registrationStatus":"Registered","healthStatus":"Healthy","containerType":"Microsoft.Compute/virtualMachines","protectableObjectType":"Microsoft.Compute/virtualMachines"}}]}
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7f6cc57af488>, <function _x509_from_base64_to_hex_transform at 0x7f6cc57af510>]
Event: CommandInvoker.OnFilterResult []
Event: Cli.PostExecute []
az_command_data_logger : exit code: 0
command ran in 8.657 seconds.

===========================

After unregistering, it still show's , when we do the listing

PS Azure:\> az backup container list  --resource-group myresourcegroupvm  --vault-name vault295   --backup-management-type azureiaasvm
Command group 'backup' is in preview. It may be changed/removed in a future release.
[
  {
    "eTag": null,
    "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourcegroups/myresourcegroupvm/providers/microsoft.recoveryservices/vaults/vault295/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;myResourceGroupVM;myvm",
    "location": null,
    "name": "IaasVMContainer;iaasvmcontainerv2;myResourceGroupVM;myvm",
    "properties": {
      "backupManagementType": "AzureIaasVM",
      "containerType": "Microsoft.Compute/virtualMachines",
      "friendlyName": "myvm",
      "healthStatus": "Healthy",
      "protectableObjectType": "Microsoft.Compute/virtualMachines",
      "registrationStatus": "Registered",
      "resourceGroup": "myResourceGroupVM",
      "virtualMachineId": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/myResourceGroupVM/providers/Microsoft.Compute/virtualMachines/myvm",
      "virtualMachineVersion": "Compute"
    },
    "resourceGroup": "myresourcegroupvm",
    "tags": null,
    "type": "Microsoft.RecoveryServices/vaults/backupFabrics/protectionContainers"
  }
]
Azure:/
PS Azure:\>

**Expected behavior**

Command is expected to unregister the backup container

**Environment summary**

Azure:/
PS Azure:\> az --version
azure-cli                         2.0.76

command-modules-nspkg              2.0.3
core                              2.0.76
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
interactive                        0.4.3
storage-preview                    0.2.7

Python location '/opt/az/bin/python3'
Extensions directory '/home/naseem/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Oct 30 2019, 06:32:16)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
Azure:/
PS Azure:\>

**Additional context**

**Comment by ahanaseem-gitid** [comment]
Added Environment

Linux-4.15.0-1061-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

Extensions:
interactive 0.4.3
storage-preview 0.2.7

**Comment by Juliehzl** [comment]
cc @sambitratha

**Comment by pvrk** [comment]
Unregistration is not required for Azure VM backups. Will update the help text.

**Comment by pvrk** [comment]
Will update the help text for the March 30th release.
