### ISSUE TITLE
List available categories before creating resource

### ISSUE THREAD

**Issue by tesharp** [Azure/azure-cli#11157]
Using terraform I would like to list available categories for a type of resource before resource is created. Possible to support listing categories just by setting --resource-type, not requiring --resource?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55b103cb-dc59-8949-663f-f968a48d204e
* Version Independent ID: 387ce519-f57b-e817-6046-08552966744a
* Content: [az monitor diagnostic-settings categories](https://docs.microsoft.com/en-us/cli/azure/monitor/diagnostic-settings/categories?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by fengzhou-msft** [comment]
@MyronFanQiu please take a look.

**Comment by MyronFanQiu** [comment]
@tesharp Hello. I need to check the server whether it's possible or not. Do you mean that terraform can  support such feature?

**Comment by tesharp** [comment]
Terraform supports the data source `azurerm_monitor_diagnostic_categories` today, but that requires a resource_id as input. So if I want to create a resource + diagnostic settings for it in same module I would like to do something like:

```hcl
resource "azurerm_something" "main" {
  ...
}

data "azurerm_monitor_diagnostic_categories" "main" {
  resource_id = azurerm_something.main.rd
}

resource "azurerm_monitor_diagnostic" "main" {
  dynamic "log" {
    for_each = azurerm_monitor_diagnostic_categories.main.logs
    ....
  }
}
```

However, what happens now is that since the resource `azurerm_something` does not exist the data source returns a list with 1 entry it seems when running plan. So last monitor resource says it want to create 1 log entry in dynamic block. It does calculate the correct order, so when applying resources the data source can return many more entries since resource now exists and it apply fails since there is an inconsistency between plan and apply.

As long as the underlying azure command requires resource_id I don't see a way to solve it in terraform unless underlying command can support asking on resource type. Then terraform could instead of referencing resource_id use resource_type and plan would be correct as it knows beforehand what log entries to make.

**Comment by MyronFanQiu** [comment]
@tesharp Hello. I checked the dependency, looks like we cannot do it currently. I will invite the corresponding people to take a look at this issue.

**Comment by MyronFanQiu** [comment]
@gucalder Hello. I saw your commit in swagger spec repo. Could you help me about this issue or help me route this issue to the right person?

**Comment by yonzhan** [comment]
@gucalder  and update ?

**Comment by asheniam** [comment]
The Diagnostic Setting Category API is only available on a per Resource ID. For some resource types, it's possible that the available list of log categories may vary across each ResourceID.

If you want to see what are the supported Azure resource types for platform logs, please refer to the following documentation.

https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-logs-schema
