### ISSUE TITLE
Az Login command should timeout or error if account does not have access

### ISSUE THREAD

**Issue by gminer485** [Azure/azure-cli#11150]
## Describe the bug

**Command Name**
`az login`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Expected Behavior
Time out after 60 seconds of attempted login.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.76

```
## Additional Context
I used the account signed into Windows, which does not have access. It should have timed out, rather than just sitting there for ten minutes.

**Comment by fengzhou-msft** [comment]
@jiasli please take a look.

**Comment by jiasli** [comment]
I have fixed `az login` hang issue in https://github.com/Azure/azure-cli/pull/10955. If the account doesn't have access, instead of hanging, CLI will show 

> No subscriptions were found for 'xxx'. If this is expected, use '--allow-no-subscriptions' to have tenant level access

If you still see this issue, please run `az login --debug` and share the result to my email <my_github_id>@microsoft.com
