### ISSUE TITLE
Support Cross-Tenant for az group deployment (arm template deployments) by taking auxilliary-tenant-id in input

### ISSUE THREAD

**Issue by agrawalkshitij** [Azure/azure-cli#11151]
**Resource Provider** 
Microsoft.Compute, ARM

**Description of Feature or Work Requested**
Today, with SIG we support cross tenant vm deployment, i.e. the share image gallery (sig) is in different tenant than the vm being deployed to. This is only supported in az vm create. The way it works is cli takes a token from sig's tenant and also from vm's tenant (target) and passes both of them to ARM.
But this confuses the customers today, as they expect it to work from az group deployment (template deployments) also, but it doesnt work. It might be difficult to parse template, so that's why I request cli team supports an auxilliary tenant id in input to the az group deployment, and passes along the token to arm along with template deployment create request.

**Minimum API Version Required**
Not related

**Swagger Link**
N/A

**Target Date**
It is causing customer pain, and confusion. It will also unblock a major scneario in azure, and the work might turn out to be small. If it is a low hanging fruit, we will really appreciate your help to ease the customer pain.

**Comment by Juliehzl** [comment]
@Tiano2017 Can you have a look at this feature? There are several requests for this feature already.

**Comment by yonzhan** [comment]
@Tiano2017 please take it higher priority since there are many requests pending on it. Appreciated that you can help.

**Comment by Tiano2017** [comment]
@alex-frankel to triage.

**Comment by Juliehzl** [comment]
> @alex-frankel to triage.

@alex-frankel @Tiano2017 Is it possible to make it available in Sprint 161?
