### ISSUE TITLE
az keyvault parameter "--tags" fails when value is passed as a single argument

### ISSUE THREAD

**Issue by GarrettGeorge** [Azure/azure-cli#11165]
## Describe the bug

**Command Name**
`az keyvault create`

**Errors:**
This was the error in the activity log of the Resource Group containing the Keyvault I was trying to create.
```
Resource '[REDACTED]' was disallowed by policy. 
Policy identifiers: '[{"policyAssignment":{"name":"Enforce product tag","id":"/subscriptions/[REDACTED]/providers/Microsoft.Authorization/policyAssignments/Enforce product tag"},"policyDefinition":{"name":"Enforces a tag and its allowed values","id":"/subscriptions/[REDACTED]/providers/Microsoft.Authorization/policyDefinitions/enforceTagAndAllowedValues"}}]'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `RESOURCE_TAGS_ENV_VARIABLE="key1=val1 key2=val2"
- `az keyvault create --name abc --resource-group MyResourceGroup --location westus --tags "${RESOURCE_TAGS_ENV_VARIABLE}"`

## Expected Behavior

Wrapping the environment variable in double quotes treats the entire string as a single argument when I assume messed with the `azure-cli` tool which likely uses `shift` to build and handle the various key value pairs. 

When I remove the quotes from the command, it works just fine and the expected behavior is that a keyvault is created and passes my team's auditPolicies for the tags field.

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.72 *

```

**Comment by fengzhou-msft** [comment]
@jiasli please take a look.

**Comment by jiasli** [comment]
This is the convention of Shell and CMD, not Azure CLI. Double quotes tell shell to include SPACE in the arg. Then CLI split the arg at the first `=`.
https://github.com/Azure/azure-cli/blob/be84df6aa4c47249abe8e9e89954bf344b53bc02/src/azure-cli-core/azure/cli/core/commands/validators.py#L38-L53

To split the tags, you may run the command as
```
az keyvault create --name {} --resource-group {} --location {} --tags $RESOURCE_TAGS_ENV_VARIABLE
```
