### ISSUE TITLE
az fails to set mysql firewall rule with resource lock, Portal works fine

### ISSUE THREAD

**Issue by BenjaminAbt** [Azure/azure-cli#11162]
CLI version 2.0.75

**Describe the bug**
We want to perform database deployments via Azure DevOps and have to temporarily add the AzD agent to the database firewall exemptions.
After deployment - no matter if successful or not - the agent should be removed from the firewall permissions in any case.

Apparently the currently recommended way is to get the IP address of the agent in the build and add it via Azure CLI.
Azure DevOps is not considered as "Azure Service" in the firewall exception rules...

I have a MySQL database in Azure that has a delete lock.
![image](https://user-images.githubusercontent.com/6189336/68498230-a52f3980-0256-11ea-9cf5-f3361b275531.png)

If I try to set the firewall via Azure DevOps and an Azure CLI task, the task throws an error:

```sh
ERROR: The scope '...../MyServerHere/firewallRules/Azd' cannot perform delete operation because following scope(s) are locked: '...../MyServerHere'. Please remove the lock and try again.
##[error]Script failed with error: Error: The process '/bin/bash' failed with exit code 1
```` 
Despite the lock, it is no problem to add or remove firewall rules in the portal via the browser. So there is obviously a different behavior between browser and Azure CLI.

**To Reproduce**
- Azure MySQL
- Add Delete Lock
- Execute AzD YAML:
```sh
pool:
  name: Azure Pipelines
  SubscriptionName: Hello
  MySql.FirewallRuleName: AzD
  MySql.ResourceGroup: 'ResourceGroup'
  MySql.ServerName: 'MySqlServer'

steps:
- task: AzureCLI@1
  displayName: 'Soft Delete Firewall Rule if exists'
  inputs:
    azureSubscription: $(SubscriptionName)
    scriptLocation: inlineScript
    inlineScript: 'az mysql server firewall-rule delete -n $(MySql.FirewallRuleName) -g $(MySql.ResourceGroup) -s $(MySql.ServerName) --yes'
  continueOnError: true

- powershell: |
   $ip = Invoke-RestMethod https://ipinfo.io/json | select -ExpandProperty ip
   Write-Host ("##vso[task.setvariable variable=AgentIPAddress;]$ip")
  displayName: 'Get IP Address'

- task: AzureCLI@1
  displayName: 'Add Firewall Rule'
  inputs:
    azureSubscription: $(SubscriptionName)
    scriptLocation: inlineScript
    inlineScript: 'az mysql server firewall-rule create -g $(MySql.ResourceGroup) -s $(MySql.ServerName) -n $(MySql.FirewallRuleName) --start-ip-address $(AgentIPAddress) --end-ip-address $(AgentIPAddress)  --yes'

# some DB Deployment Tasks here

- task: AzureCLI@1
  displayName: 'Remove Firewall Rule'
  inputs:
    azureSubscription: $(SubscriptionName)
    scriptLocation: inlineScript
    inlineScript: 'az mysql server firewall-rule delete -n $(MySql.FirewallRuleName) -g $(MySql.ResourceGroup) -s $(MySql.ServerName) --yes'
  condition: succeededOrFailed()

```

**Expected behavior**
CLI should have the same behavior like the portal.
I would expect to be able to add and remove a rule despite the lock.

**Environment summary**
Azure DevOps - ubuntu-18.04 Agent
Default AzCli capabilities (2.0.75)

Should this not be a recommended way, I would be grateful for a corresponding hint :-)
Thanks.

**Comment by ajlam** [comment]
@BenjaminAbt, thanks for filing this issue. We were able to successfully reproduce the issue. Following up with portal and CLI teams to understand expected behaviors.

**Comment by MarcusJung-divae** [comment]
Any news ?

**Comment by ajlam** [comment]
Hi all, sorry for the delayed update. 

The firewall rule delete behavior for the Azure portal was a bug. We have now updated the portal behavior to match the Azure CLI so that when a "delete" resource lock is set on a server, firewall rules cannot be deleted.

**Comment by maqshifengw** [comment]
Hello @ajlam, this issue still existing, can you please check?

We can't remove the firewall rules from API when the lock is ON. (Which is expected)
![image](https://user-images.githubusercontent.com/77037916/105430679-e7009180-5c08-11eb-84c1-bb749d92b49b.png)

But we can remove the firewall via Portal when the lock is ON. (Which is not expected)
![image](https://user-images.githubusercontent.com/77037916/105431392-617de100-5c0a-11eb-84c9-55847899c731.png)
![image](https://user-images.githubusercontent.com/77037916/105431425-6d69a300-5c0a-11eb-898b-c99d73f9cb5a.png)

**Comment by ajlam** [comment]
@mksuni - would you be able to follow-up?

**Comment by mksuni** [comment]
@BenjaminAbt  Hi , sorry for the delay. After speaking with the team the CLI experience is by design . For portal the experience should be the same as CLI and technically should not allow any delete operations firewall , service endpoint etc on the database server.

If you can share more details on your use case that your require to delete the firewall rule. is this automation related ?

**Comment by BenjaminAbt** [comment]
@mksuni I guess u marked the wrong person. 

Likewise, I think we understood that the CLI was correct but the portal was not. But the bug has apparently reappeared according to @maqshifengw.

**Comment by raffaelviotti** [comment]
Hello, could you please re-open the issue as I cannot delete a firewall rule from CLI when my sql server is locked (I can with powershell and the portal)
When I am doing this :  `az sql server firewall-rule delete`
I get :
`"cannot perform delete operation because following scope(s) are locked"`
When I am doing this in powershell: `Remove-AzSqlServerFirewallRule` it works
