### ISSUE TITLE
Couldn't create Image Builder resource

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#11184]
## Describe the bug

**Command Name**
`az resource create`

**Errors:**
```
Error occurred in request., ConnectionError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/576f5e67-b043-4ec9-81e9-47c7e8692cc4/providers/Microsoft.VirtualMachineImages?api-version=2018-05-01 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8b608cc470>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
Trying to create an Azure Image Builder resource
- `az resource create --resource-group {} --properties {} --is-full-object --resource-type {} -n {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.63 *

Extensions:
interactive 0.4.3

```

**Comment by yonzhan** [comment]
@Juliehzl  add to S162.

**Comment by Juliehzl** [comment]
@fitzgeraldsteele Could you share with me your properties value to help me repro your issue?

**Comment by Juliehzl** [comment]
Given no response, I will close this issue and if you still have any problem, feel free to reopen it or create a new one. 😊
