### ISSUE TITLE
Adding 'Spot' to 'Priority' enum property (Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/7748); Updating '--max-billing' parameter to '--max-price'; Making '--max-price' updatable in VM and VMSS

### ISSUE THREAD

**Issue by rakeshakkera** [Azure/azure-cli#11187]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Azure Compute

**Description of Feature or Work Requested**
    - Add 'Spot' enum value to 'Priority' enum. 
    - Rename '--max-billing' parameter to '--max-price', for both VM and VMSS, to be consistent with Swagger and Powershell cmdlets (link to PS cmdlet https://docs.microsoft.com/en-us/powershell/module/az.compute/new-azvm?view=azps-3.0.0). This might be considered as a breaking change but it should be okay since the feature is still in private preview.
    - We now support update of priority only between 'Low' and 'Spot' for both VM and VMSS. So 'az vm update' and 'az vmss update' should support the update of priority between 'Low' and 'Spot' enum values. Note: Update of priority between 'Low' and 'Regular', also between 'Spot' and 'Regular' are not allowed. 
    - VM supports the update of '--max-price' when the VM is deallocated. So the cmdlet 'az vm update' should support the update of '--max-price'. The service already supports this.
    - VMSS supports the update of '--max-price' when the VMSS VMs are deallocated. So the cmdlet 'az vmss update' should support the update of '--max-price'. The service already supports this.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2019-03-01.

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
https://github.com/Azure/azure-rest-api-specs/pull/7748

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
S161 - 11/26/2019

**Comment by fengzhou-msft** [comment]
@qwordy please take a look.

**Comment by qwordy** [comment]
Do you have any description of the 'Spot' enum value?

**Comment by rakeshakkera** [comment]
@qwordy : I am not sure why you are not seeing the Spot value in Compute 2019-07-01. Looks at the snapshot below. It clearly show that VirtualMachinePriorityTypes has 'Spot' Enum value.
![image](https://user-images.githubusercontent.com/52220364/69080804-7ef56080-09f1-11ea-91bf-be9f92f20947.png)

**Comment by qwordy** [comment]
Had a call with Rakesh. Prioritize first two features. Put the rest into next sprint.

**Comment by qwordy** [comment]
#11035 is merged.

**Comment by qwordy** [comment]
> 
> 
> @qwordy : I am not sure why you are not seeing the Spot value in Compute 2019-07-01. Looks at the snapshot below. It clearly show that VirtualMachinePriorityTypes has 'Spot' Enum value.
> ![image](https://user-images.githubusercontent.com/52220364/69080804-7ef56080-09f1-11ea-91bf-be9f92f20947.png)

No problem now. There is a delay between Python SDK and swagger. Python SDK is not auto released when there is a update in swagger. So I manually ask the owner of Python SDK to release a new version.

**Comment by qwordy** [comment]
The features are ready to release. Official Release: 12/17/2019.
