### ISSUE TITLE
Question: Add VMSS as address pool

### ISSUE THREAD

**Issue by stmaute** [Azure/azure-cli#11192]
Actually I see no way to add a VMSS as address pool to my application gateway. 
Do I miss out anything here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb7977f-f67a-b7f1-9c55-5fe3ceef1148
* Version Independent ID: 855b66dc-6a1b-a182-8670-2a8b8ca8b10a
* Content: [az network application-gateway address-pool](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/address-pool?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@stmaute Hello. Currently we don't support adding a VMSS as the address pool. You can add the IPs of the VMSS as the address pool.

**Comment by stmaute** [comment]
@MyronFanQiu Thank you for answer. Are there any efforts to support this via cli?

**Comment by stmaute** [comment]
And another question is how do I get the private IP addresses of the VMSS via cli? I didn't find any command to do so. Maybe you can help me with this too?

**Comment by MyronFanQiu** [comment]
@qwordy Could you answer the above question? I need to investigate the effort to support this feature request.

**Comment by qwordy** [comment]
> 
> 
> @qwordy Could you answer the above question? I need to investigate the effort to support this feature request.

There is a `az vmss list-instance-public-ips` command.
@shpa-microsoft, can we get the private IP addresses of the VMSS?

**Comment by yonzhan** [comment]
@shpa-microsoft, any update ?

**Comment by shpa-microsoft** [comment]
Unfortunately this is not my area of expertise. Encourage you to try reaching out to scalesetdev DL and then a broader crphotissues DL if results arent found.

**Comment by MyronFanQiu** [comment]
@qwordy Hi. Can you help reach out to the correct DL and cc me？

**Comment by yonzhan** [comment]
@qwordy any update for this issue?

**Comment by yonzhan** [comment]
move to S166.

**Comment by arrownj** [comment]
Hi @stmaute , sorry for reply late. I think you can use `az vmss nic list` to get private ip of each instance.

**Comment by arrownj** [comment]
Hi @stmaute, if you have no more questions, I will close this issue first. You can reopen it or submit a new one if you have other questions. Thanks
