### ISSUE TITLE
`az aks install-cli` doc issues

### ISSUE THREAD

**Issue by algattik** [Azure/azure-cli#11191]
(1) DC/OS should be replaced by kubectl. (2) in Mac OS, the default install-location turns out to actually be /usr/local/bin.

```
--install-location
Path at which to install DC/OS.
default value: ~/.azure-kubectl/kubectl.exe
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-install-cli)
* Content Source: [src/azure-cli/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jluk** [comment]
Thanks for the report @algattik it looks like @seanmck has opened a PR to update this.

**Comment by NillsF** [comment]
Additionally, the default install location on Linux is not ~/.azure-kubectl/kubectl.exe but rather "/usr/local/bin/kubectl". I looked through the docs to make the PR myself but couldn't find the location, so just piling on to this issue.
