### ISSUE TITLE
Provision OpenShift v3.11 in Azure fails with error: 400 client error: bad request for url: http://localhost:50342/oauth2/token

### ISSUE THREAD

**Issue by marciasheila** [Azure/azure-cli#11209]
Hello, I'm following Microsoft oficial steps to provision a Openshift cluster v3.11

## After following all the described steps here https://docs.microsoft.com/en-us/azure/openshift/tutorial-create-cluster I executed the bash command to create the OpenShift cluster but suddenly crashes.

**az openshift create**
`az openshift create --resource-group $CLUSTER_NAME --name $CLUSTER_NAME -l $LOCATION --aad-client-app-id $APPID --aad-client-app-secret $SECRET --aad-tenant-id $TENANT --customer-admin-group-id $GROUPID`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Followed: https://docs.microsoft.com/en-us/azure/openshift/tutorial-create-cluster

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```

**Comment by navba-MSFT** [comment]
@marciasheila  Apologies for the late reply. Could you please use the most [recent version of Azure CLI ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and let us know if you still see the issue? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@marciasheila Please let us know if you are still facing this issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@marciasheila We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
