### ISSUE TITLE
Add new "reapply" command action for az vm

### ISSUE THREAD

**Issue by avinashakka** [Azure/azure-cli#11203]
**Resource Provider**
What is the Azure resource provider your feature is part of?
- Compute Resource Provider (Microsoft.Compute)

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
- **Reapply** POST API for a Azure virtual machine will reapply a virtual machines's state. It should rerun the VM provisioning and help mitigate the VM's state if it was in a failed state. Its more like a nudge to a virtual machines's state if it has failed while executing a previous client action and is provided to help client/user try self-mitigate if it was due to a transient internal failure.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
- 2019-07-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
- https://github.com/Azure/azure-rest-api-specs/blob/53d1252d861bfcddb075ace5d4f98e3f43d7a5a5/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json#L2864

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
- The feature/API is already GA. Can this be prioritized in this semester or early **Manganese** semester as this is to be provided as one of the mitigation steps to be recommended in TSG for customer support cases.

**Comment by yonzhan** [comment]
@qwordy add to S162.

**Comment by qwordy** [comment]
> 
> 
> @qwordy add to S162.

OK

**Comment by yungezz** [comment]
HI @avinashakka the feature is released in az cli 2.0.79 version. Pls try it and let us know your feedback by creating new issue. thanks.
