### ISSUE TITLE
az role assignment list not seeing groups 

### ISSUE THREAD

**Issue by kevin-dfo** [Azure/azure-cli#11210]
## Describe the bug
Updated to the lasted cli 2.0.76 and no longer view groups when running az role assignment list
This worked on 2.0.5X (not sure the exact version)

**Command Name**
`az role assignment list`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role assignment list --all --assignee {} --subscription {} --include-groups --include-inherited --include-classic-administrators -o {}`

## Expected Behavior
List Groups & Users role assignments.

## Environment Summary
```
Windows-10-10.0.15063-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.76

Extensions:
aks-preview 0.4.4

```

**Comment by fengzhou-msft** [comment]
@jiasli please take a look.

**Comment by jemag** [comment]
Same issue here with azure-cli version 2.0.76. I cannot see the permissions of the group I am a part of, only the permissions attributed directly to me. (with same command as OP)

**Comment by hausec** [comment]
I'm also having this issue. 
` az role assignment list --assignee reader@domain.onmicrosoft.com`

Lists nothing. Version 2.0.79

**Comment by nbfowler** [comment]
I also have this issue, using Version 2.0.67.

**Comment by qianwens** [comment]
@jiasli please help investigate if this is a cli issue or service issue.

**Comment by qianwens** [comment]
@kevin-dfo I can not repro your issue with latest Az CLI. Could you please help run your command with --debug and provide the output to us for further investigation?

**Comment by jemag** [comment]
I have just re-tested with version 2.5.1 and problem is still there. I have used: 
`az role assignment list --all --assignee "********" --subscription "*****" --include-groups --include-inherited --include-classic-administrators -o table --debug`

However, I am not sure how I feel about posting the debug output here since it contains a decent amount of personal information. Perhaps if you could provide an email to send it to?

What I can tell you from the output though is that the group assignments are properly returned by the api request:
![image](https://user-images.githubusercontent.com/7985687/82056290-bdfa2b00-968f-11ea-852b-8b32d3c70518.png)
However although there is 30+ of those assignments returned they do not show up in the final command output.

**Comment by jemag** [comment]
@qianwens Let me know if you need more information than what I provided. If not, perhaps it would be better to remove the "customer-response-expected" label

**Comment by qianwens** [comment]
> I have just re-tested with version 2.5.1 and problem is still there. I have used:
> `az role assignment list --all --assignee "********" --subscription "*****" --include-groups --include-inherited --include-classic-administrators -o table --debug`
> 
> However, I am not sure how I feel about posting the debug output here since it contains a decent amount of personal information. Perhaps if you could provide an email to send it to?
> 
> What I can tell you from the output though is that the group assignments are properly returned by the api request:
> ![image](https://user-images.githubusercontent.com/7985687/82056290-bdfa2b00-968f-11ea-852b-8b32d3c70518.png)
> However although there is 30+ of those assignments returned they do not show up in the final command output.

Hi @jemag , please help remove your personal information from the output and send it to my email qianwens@microsoft.com. Thanks.

**Comment by jemag** [comment]
@qianwens output sent to your email

**Comment by qianwens** [comment]
@jemag , it is a regression in Azure CLI. We will fix it next release. Thanks for reporting this issue.

**Comment by subesokun** [comment]
I'm using AZ CLI v2.12.1 but still having this issue. I've a user included into a group on subscription level that has read permissions on the subscription but `az role assignment list --all --include-classic-administrators --include-groups --include-inherited` doesn't list the user.

```
❯ az --version
azure-cli                         2.12.1

core                              2.12.1
telemetry                          1.0.6

Python location '/usr/local/Cellar/azure-cli/2.12.1/libexec/bin/python'
Extensions directory '/Users/subesokun/.azure/cliextensions'

Python (Darwin) 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

Any ideas?

**Comment by guillermoabdon** [comment]
Hello all!
I'm getting problems to use all the flags except --all
When I use this query to get the roles assigned to a user, for all the components under a subscription, only receive the users added directly to the component, but isn't show me the permissions Inherited. I'm using this query to get that values:     **az role assignment list --all --query "[?principalName=='$USR'].principalName:principalName,roleDefinitionName:roleDefinitionName,resourceGroup:resourceGroup,scope:scope}" -o table** 
But I've tried replacing --all with another flags (--include-inherited) without the expected result.

AZ Version:

  "azure-cli": "2.36.0",
  "azure-cli-core": "2.36.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}

Any approach to get the inherited roles on my query?
