### ISSUE TITLE
az sql server firewall-rule create fails with misleading Not Found message if name is duplicated but different case

### ISSUE THREAD

**Issue by leighghunt** [Azure/azure-cli#11215]
## Describe the bug

**Command Name**
`az sql server firewall-rule create`

**Errors:**
```
Operation failed with status: 'Not Found'. Details:
```

## To Reproduce:
Attempt to create firewall rule but name is duplicate, albeit with different case.

- _Put any pre-requisite steps here..._
- `az sql server firewall-rule create --name TEST1 --server {} --resource-group {} --start-ip-address {} --end-ip-address {}`
- `az sql server firewall-rule create --name Test1 --server {} --resource-group {} --start-ip-address {} --end-ip-address {}`

## Expected Behavior
- Either first firewall rule should be overwritten, or a new rule should be created. The Not Found error is confusing.

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.74 *

Extensions:
interactive 0.4.3

```

**Comment by RakeshMohanMSFT** [comment]
@leighghunt This issue is fixed, please upgrade to the latest version of azure cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
