### ISSUE TITLE
az extension remove error saying --name is required

### ISSUE THREAD

**Issue by gbowerman** [Azure/azure-cli#11212]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.76

**Describe the bug**
Trying to remove an old functionapp extension, the error message states that --name argument is missing, even though it is present:

az extension remove -–name functionapp
Unable to load extension 'functionapp'. Use --debug for more information.
az extension remove: error: the following arguments are required: --name/-n
usage: az extension remove [-h] [--verbose] [--debug]
                           [--output {json,jsonc,table,tsv,yaml,none}]
                           [--query JMESPATH] --name EXTENSION_NAME

**To Reproduce**
Not sure if this repros in all circumstances or just when trying to remove an old functionapp extension.

**Expected behavior**
Successful execution of: az extension remove -–name functionapp

**Environment summary**
Azure Cloud Shell (bash) cli --version
command-modules-nspkg              2.0.3
core                              2.0.76
nspkg                              3.0.4
telemetry                          1.0.4
Extensions:
functionapp                        0.0.2

**Additional context**

**Comment by fengzhou-msft** [comment]
Thanks for reporting the issue. We will take a look.

**Comment by fengzhou-msft** [comment]
`functionapp` is moved from extensions to core under [appservice](https://github.com/Azure/azure-cli/tree/dev/src/azure-cli/azure/cli/command_modules/appservice), you cannot remove it now. We should improve the error message though.

**Comment by fengzhou-msft** [comment]
It seems that the command you typed(`az extension remove -–name functionapp`) includes a symbol that is not '-', so name option is not recognized.
