### ISSUE TITLE
Add ability to set the zoneRedundant property when creating eventhub namespaces

### ISSUE THREAD

**Issue by ablyler** [Azure/azure-cli#11213]
**Is your feature request related to a problem? Please describe.**
Currently you can set zoneRedundant via ARM templates and via the portal, but not via the az CLI.

**Describe the solution you'd like**
I would like to be able to set the zoneRedundant property when creating eventhub namespaces via the az CLI.

**Additional context**
* https://azure.microsoft.com/en-us/blog/azure-event-hubs-is-now-offering-support-for-availability-zones-in-preview/

**Comment by jfggdl** [comment]
Thank you for creating this issue. We  are validating this gap and we will be reporting our findings and next steps.

**Comment by pascalnaber** [comment]
Any update on this?

**Comment by v-Ajnava** [comment]
@ablyler sorry for late response, --zone-redundant property is added to az eventhubs namespace create command. please use the latest release. 

I am closing the issue, if you have any question please feel to open this one or new issue. Thanks !
