### ISSUE TITLE
i cant run command az aks update

### ISSUE THREAD

**Issue by ronaldmiranda** [Azure/azure-cli#11228]
## Describe the bug

**Command Name**
`az aks update`

**Errors:**
```
No module named 'azure.mgmt.containerservice.v2019_08_01'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 523, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 291, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 75, in <module>
    from ._helpers import _populate_api_server_access_profile, _set_load_balancer_sku, _set_vm_set_type
cliextensions/aks-preview/azext_aks_preview/_helpers.py, ln 8, in <module>
    from azure.mgmt.containerservice.v2019_08_01.models import ManagedClusterAPIServerAccessProfile
ModuleNotFoundError: No module named 'azure.mgmt.containerservice.v2019_08_01'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update`

## Environment Summary
```
Linux-4.14.150-boot2docker-x86_64-with-debian-9.8
Python 3.6.5
Shell: bash

azure-cli 2.0.70 *

Extensions:
aks-preview 0.4.23

```

**Comment by ronaldmiranda** [comment]
i just resolved this issue updating the client.

**Comment by PrabhuMathi** [comment]
> i just resolved this issue updating the client.

Hi, which client is update for this please?

**Comment by ptylenda** [comment]
@PrabhuMathi, updating Azure CLI (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) to the latest version fixes the issue.

**Comment by PrabhuMathi** [comment]
> 
> 
> @PrabhuMathi, updating Azure CLI (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) to the latest version fixes the issue.

Hi, Thanks have tried it and working fine :)
