### ISSUE TITLE
Issues with 'az network dns zone create'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1122]
Issues with 'az network dns zone create':
1. Help text ('-h') shows 'Create or update a virtual machine'.  That is wrong, nothing to do with VMs.
2. Allows me to create or update (operations on existing resources are successful).  Given that we have a separate command for updates, should this command be create only, i.e. use 'If-none-match *' request header?  At the least we need to give the option of create-only vs create-or-update
3. Supports '--location -l' with default 'global'.  Given that the only supported value for DNS zones is 'global', this parameter is useless and should be removed.
4. In the help text, --name -n is described as "The name of the zone without a terminating dot." Whilst the service cares about terminating dots, the CLI should not.  I.e. the text should be "The name of the zone, for example 'contoso.com'."  And if a terminating dot is provided, the CLI should simply silently remove it before calling the service. In this way we optimize for usability by humans.

**Comment by JasonRShaver** [comment]
* fix help
* add if-none-match
* force --location to global

Discuss #4

**Comment by jtuliani** [comment]
Discussed #4 with Jason...agreed this needs to be done client side.

**Comment by troydai** [comment]
- [ ] Help text ('-h') shows 'Create or update a virtual machine'. That is wrong, nothing to do with VMs.
- [ ] Allows me to create or update (operations on existing resources are successful). Given that we have a separate command for updates, should this command be create only, i.e. use 'If-none-match *' request header? At the least we need to give the option of create-only vs create-or-update
- [ ] Supports '--location -l' with default 'global'. Given that the only supported value for DNS zones is 'global', this parameter is useless and should be removed.
- [ ] In the help text, --name -n is described as "The name of the zone without a terminating dot." Whilst the service cares about terminating dots, the CLI should not. I.e. the text should be "The name of the zone, for example 'contoso.com'." And if a terminating dot is provided, the CLI should simply silently remove it before calling the service. In this way we optimize for usability by humans.
