### ISSUE TITLE
Unexpected error when running enable-for-azurefileshare when already enabled

### ISSUE THREAD

**Issue by jannyg** [Azure/azure-cli#11225]
## Describe the bug
Unexpected error when running enable-for-azurefileshare when running on a fileshare with protection already enabled 

**Command Name**
`az backup protection enable-for-azurefileshare`

**Errors:**
```
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/backup/custom_base.py, ln 189, in enable_for_azurefileshare
    storage_account, policy_name)
cli/command_modules/backup/custom_afs.py, ln 66, in enable_for_AzureFileShare
    container_uri = helper.get_protection_container_uri_from_id(protectable_item.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Create storage account with file share
- `az backup protection enable-for-azurefileshare --policy-name {} --resource-group {} --vault-name {} --storage-account {} --azure-file-share {}`

## Expected Behavior

Check if protection is enabled first and give output.

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.5
Shell: bash

azure-cli 2.0.76

Extensions:
interactive 0.4.3

```

**Comment by pvrk** [comment]
@jannyg : We are not able to reproduce this error on our side. Can you please let us know if you are able to re-produce this? Adding @sambitratha for info.

**Comment by pvrk** [comment]
Can re-open the issue with details, if it re-produces. Can't reproduce internally.
