### ISSUE TITLE
AKS Creation Without Public Load Balancer

### ISSUE THREAD

**Issue by LukeRH** [Azure/azure-cli#11233]
Hi,
Is it possible to create an AKS cluster without having to create a public load balancer and use an internal load balancer instead? We are blocked from creating a public load balancer by our network team and we only want to expose the cluster internally.

Its seems like this is only an issue through using the portal, if i create the AKS through the portal it creates a public ip load balancer. If i create the AKS using Azure CLI e.g.
 az aks create \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --network-plugin azure \
    --vnet-subnet-id <subnet-id> \
    --docker-bridge-address 172.17.0.1/16 \
    --dns-service-ip 10.2.0.10 \
    --service-cidr 10.2.0.0/24 \
    --generate-ssh-keys

It does not create the public load balancer.

Thanks
Luke

**Comment by palma21** [comment]
That will only happen if you CLI version is older, which means the default will be using Basic Load Balancer. Newer CLI versions will be defaulting to SLB wich requires a public IP and and LB for egress.

**Comment by LukeRH** [comment]
Ok so it is not possible to create an Azure K8s services using a private IP and LB for egress from the outset?

**Comment by palma21** [comment]
It is possible the SLB IP is just for egress.

Let me try to clarify.

AKS with Basic Load Balancer
* You can create it by passing the load balancer sku parameter
* Has implicit Egress (you won't see a public IP, although it is there on the Azure infrastructure)
* You can create private services accessible only through private IPs using the internal annotation. 
https://docs.microsoft.com/en-us/azure/aks/internal-lb

AKS with Standard Load Balancer
* Used by default on latest clientes, or explicitly by using the same parameter as above 
* Has only explicit egress, which means if there isn't an egress IP the cluster won't have egress and will be broken. This is like the gateway to the internet IP. You can control, pre-create or change this IP (or have more than one)
* You can create private services accessible through private IPs using the internal annotation. 
https://docs.microsoft.com/en-us/azure/aks/internal-lb

**Comment by LukeRH** [comment]
Great thanks for your clarification

**Comment by rafagsiqueira** [comment]
@palma21 you mentioned: "We are now working on a UDR outbound type for SLB that will allow users to confirm they have egress through UDRs and in this case the SLB won't be created with a Public IP for egress". Is this on a roadmap somewhere? Is it already available?

**Comment by jluk** [comment]
Yes this capability is GA, please use this documentation.

aka.ms/aks/outboundtype
