### ISSUE TITLE
azure-cli yum package is using Python 2.7, should use Python 3.6

### ISSUE THREAD

**Issue by rodrigc** [Azure/azure-cli#11234]
## Describe the bug

When following the instructions to install the Azure-cli via yum:

`yum install azure-cli`

This is installed:

```
Name        : azure-cli
Version     : 2.0.76
Release     : 1.el7
Architecture: x86_64
Install Date: Fri Nov  8 17:24:30 2019
Group       : Unspecified
Size        : 265584182
License     : MIT
Signature   : RSA/SHA256, Wed Oct 30 07:52:34 2019, Key ID eb3e94adbe1229cf
Source RPM  : azure-cli-2.0.76-1.el7.src.rpm
Build Date  : Wed Oct 30 06:42:28 2019
Build Host  : 3554ed41ff72
Relocations : (not relocatable)
URL         : https://docs.microsoft.com/cli/azure/install-azure-cli
Summary     : Azure CLI
Description :
A great cloud needs great tools; we're excited to introduce Azure CLI,
 our next generation multi-platform command line experience for Azure.
```

The `/usr/bin/az` command contains this:

```
#!/usr/bin/env bash
PYTHONPATH=/usr/lib64/az/lib/python2.7/site-packages python2.7 -sm azure.cli "$@"
```

This should be changed to use Python 3.6.

There are some extensions to the azure-cli which are using Python 3 specific features that
do not work with Python 2.  This is causing the azure cli to fail on Python 2.7.

See: https://github.com/Azure/azure-cli/issues/11206#issuecomment-553670416

**Command Name**
``

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.76

```

**Comment by fengzhou-msft** [comment]
Thanks for submitting the issue. We're working on the switch now.
