### ISSUE TITLE
az webapp up --->error webapp doesn't exist

### ISSUE THREAD

**Issue by sspearsLCBCC** [Azure/azure-cli#11237]
## Describe the bug

**Command Name**
az webapp up --resource-group learn-c38dc864-20ad-4d06-8c3b-bb014cd8718a --sku F1 -n educationapp-$RANDOM

**Errors:**
webapp educationapp-30191 doesn't exist

'NoneType' object has no attribute 'upper'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 652, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/command_modules/appservice/custom.py, ln 2993, in webapp_up
    create_app_service_plan(cmd, rg_name, plan, _is_linux, False, sku, 1 if _is_linux else None, location)
cli/command_modules/appservice/custom.py, ln 1390, in create_app_service_plan
    sku = _normalize_sku(sku)
cli/command_modules/appservice/utils.py, ln 20, in _normalize_sku
    sku = sku.upper()
AttributeError: 'NoneType' object has no attribute 'upper'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --resource-group {} --sku {} -n {}`

## Expected Behavior

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```
## Additional Context

<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by fengzhou-msft** [comment]
This is fixed by #11019

**Comment by sspearsLCBCC** [comment]
Still getting the same issue.  webapp doesn't exist.

**Comment by fengzhou-msft** [comment]
The fix will be released with 2.0.77

**Comment by panchagnula** [comment]
Please downgrade to 2.0.75 for this to work. Sorry for the inconvinience

pip install azure-cli==2.0.75

**Comment by panchagnula** [comment]
Please update to the latest version of CLI https://pypi.org/project/azure-cli/ version 2.0.77 and re-try. there was a known regression with version 2.0.76

**Comment by johseffer** [comment]
Same problem here.

az --version
azure-cli                         2.11.1 *

core                              2.11.1 *
telemetry                          1.0.5 *

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory '\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 3 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
