### ISSUE TITLE
az webapp deployment source config-zip does not respect existing SCM_DO_BUILD_DURING_DEPLOYMENT

### ISSUE THREAD

**Issue by nathanlindorff** [Azure/azure-cli#11246]
I've run into the issue where running the zip deploy via the cli explicitly sets SCM_DO_BUILD_DURING_DEPLOYMENT to false in the app setting, even when it is set to true, or the .deployment file in the zip has the value set as true. 

I've not seen it mentioned in any documentation that forcing this to false is now the standard behaviour. 

Existing documentation explicitly says to set this setting for zip deploys that you want to build (eg run npm install) on the server. (See https://github.com/projectkudu/kudu/wiki/Configurable-settings#enabledisable-build-actions)

Scripts that had previously worked are now silently failing because the node_modules are not being downloaded on the server. Even some current Microsoft scripts are failing such as the Virtual Assistant Template (https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/deployment/scripts/publish.ps1) 

I did update my az cli recently, so i'm assuming the change has happened recently.

If this is the new standard behaviour, could this please be explicitly documented? Or preferably, can there be a flag that tells it not to override provided settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b238907f-0676-8e20-66ac-89a542aa8c20
* Version Independent ID: 60659c33-bfea-eecb-6681-9240191820be
* Content: [az webapp deployment source](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp/deployment/source.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/deployment/source.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
Sorry you are correct this was a new regression with the following change  https://github.com/Azure/azure-cli/pull/10706
we have a fix for this & working on rolling out the changes - in the meanwhile you can downgrade to an older version of CLI using 

pip install azure-cli==2.0.75

Fixed by https://github.com/Azure/azure-cli/pull/11019

**Comment by panchagnula** [comment]
The fix is now available please pdate to the latest version of CLI https://pypi.org/project/azure-cli/ version 2.0.77
