### ISSUE TITLE
Upload functionapp configurations from Json file

### ISSUE THREAD

**Issue by andigwandi** [Azure/azure-cli#11243]
Is there a way to upload multiple configuration from json file using following cmdline syntax?

az functionapp config appsettings set --name MyFunctionApp --resource-group MyResourceGroup --settings <JsonFile>

**Comment by ajklotz** [comment]
I need this.

**Comment by ajklotz** [comment]
@andigwandi Please see my github issue that was closed yesterday. They answered my question about how to use a json file to upload multiple configurations.

https://github.com/Azure/azure-cli/issues/11552#issuecomment-565154393

**Comment by navba-MSFT** [comment]
@andigwandi Apologies for the late reply. I am hoping that you have followed the suggestions in the above comment. Could you please let me know if you need any further assistance on this ? Awaiting your reply.

**Comment by andigwandi** [comment]
No action is required as of now. Thank you for following up.
