### ISSUE TITLE
Issues with 'az network dns zone list'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1124]
Issues with 'az network dns zone list':
1. In the help text, explain that the --resource-group -g parameter is optional, and that when omitted the command will enumerate zones across the subscription.

**Comment by JasonRShaver** [comment]
By being optional, -g follows the pattern of all list commands defaulting to enumerating resources scoped to subscription.

**Comment by jtuliani** [comment]
Not possible to use help text from Swagger since there are two different API calls behind this command (one for subscription level, one for zone level).

Command overview help text should be as per #1121 

Proposed text for --resource-group -g parameter: (Optional) The name of the resource group. If specified, all DNS zones in this resource group are returned.  If omitted, all DNS zones in the Azure subscription are returned.

**Comment by tjprescott** [comment]
The help text has been fixed in #1270 for the command and follows the pattern for all other commands in the CLI which list resources within a subscription or resource group, if specified.
