### ISSUE TITLE
az webapp auth update command doesn't allow to set the certificate

### ISSUE THREAD

**Issue by baywet** [Azure/azure-cli#11244]
The authSettings object has a `clientSecretCertificateThumbprint` property, which is exposed by arm templates. It is also carried in the appsettings as `WEBSITE_AUTH_CLIENT_SECRET_CERTIFICATE_THUMBPRINT`.
This setting is missing from the CLI. If you try to set this setting from the appsetting command, you get the following error `AppSetting with name 'WEBSITE_AUTH_CLIENT_SECRET_CERTIFICATE_THUMBPRINT' is not allowed.`
It'd be nice to have an additional setting name clientSecretCertificateThumbprint so we can set it up programmatically, or something similar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeb196c8-e408-8563-26ba-5c3ae6e38c48
* Version Independent ID: 5f150c9a-e142-2fd7-fe84-b298dc83fd02
* Content: [az webapp auth](https://docs.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest#az-webapp-auth-update)
* Content Source: [latest/docs-ref-autogen/webapp/auth.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/auth.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
Please use the upsettings command with --setting property which take a name value pair 
Ex. az webapp config appsettings set -g MyResourceGroup -n MyUniqueApp --settings WEBSITE_NODE_DEFAULT_VERSION=6.9.1

See this for more details https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az-webapp-config-appsettings-set

**Comment by baywet** [comment]
thank you for your answer, it is the command I'm running with the setting name I provided in my first message and I'm getting the error message mentioned above.

**Comment by yonzhan** [comment]
How about the status of this issue?

**Comment by yonzhan** [comment]
move to S165.

**Comment by yonzhan** [comment]
move to S166.

**Comment by panchagnula** [comment]
@calvinsID might be good issue for you to start with.

**Comment by panchagnula** [comment]
@mkarmark like we chatted online - if you could take care of supporting this please. Thanks!
