### ISSUE TITLE
az webapp up reads in the SKU as an int, but then calls string methods on it.

### ISSUE THREAD

**Issue by phobson** [Azure/azure-cli#11259]
## Describe the bug

I was following [this tutorial](https://docs.microsoft.com/en-us/cli/azure/appservice?view=azure-cli-latest&viewFallbackFrom=azure-cli-latest.md#az-appservice-list-locations) and was ready to deploy.

When I deployed, the `az` CLI had trouble parsing the SKU

**Command Name**
`az webapp up`

**Errors:**
```
'int' object has no attribute 'upper'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 652, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/command_modules/appservice/custom.py, ln 2993, in webapp_up
    create_app_service_plan(cmd, rg_name, plan, _is_linux, False, sku, 1 if _is_linux else None, location)
cli/command_modules/appservice/custom.py, ln 1390, in create_app_service_plan
    sku = _normalize_sku(sku)
cli/command_modules/appservice/utils.py, ln 20, in _normalize_sku
    sku = sku.upper()
AttributeError: 'int' object has no attribute 'upper'
```

The last line of the error is strange, as I used "F1" as the SKU, which I figured would be parsed as a string. I also tried "FREE" per the [MS Docs](https://docs.microsoft.com/en-us/cli/azure/appservice?view=azure-cli-latest&viewFallbackFrom=azure-cli-latest.md#az-appservice-list-locations) 

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az configure --default location="West US 2"`
- `az webapp up --sku F1 -n {myappname}`

("myappname" is just a place holder. I did try to use "F1" as the `sku` though)

## Expected Behavior

Expected the small web app to be deployed to the a free tier

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```
## Additional Context

None

**Comment by panchagnula** [comment]
This is a known issue with the latest version of CLI we have a new build with the fix that will roll out in the mean time you can use the following version  
pip intall azure-cli==2.0.75

**Comment by panchagnula** [comment]
Fixed by https://github.com/Azure/azure-cli/pull/11019

**Comment by phobson** [comment]
thanks @panchagnula !

**Comment by afeld** [comment]
For anyone else who comes across this, here's how to downgrade on Ubuntu/Debian:

```sh
sudo apt-get update
sudo apt-get install -y --allow-downgrades azure-cli=2.0.75-1~stretch
```

**Comment by panchagnula** [comment]
also btw the changes are merged to dev so feel free to use the edge builds https://github.com/Azure/azure-cli#edge-builds

**Comment by panchagnula** [comment]
Please update to the latest version of CLI https://pypi.org/project/azure-cli/ version 2.0.77 and re-try. there was a known regression with version 2.0.76
