### ISSUE TITLE
Issues with 'az network dns zone delete'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1125]
Issues with 'az network dns zone delete':
- [x] 1. Description text must give much stronger warning.  "Deletes a DNS zone from a resource group.  All DNS records within the zone will also be deleted.  WARNING: This operation cannot be undone."
- [ ] ~~2. Given the potential impact of a mistake, this command ideally should include a confirmation prompt (plus --force parameter to suppress the prompt).~~ (Issue #1355)
- [x] 3. As with 'az network dns zone create' the CLI should not care about the presence or otherwise of terminating dots on the zone name.  Replace with "The name of the DNS zone, for example 'contoso.com'."  If the user provides a terminating dot, then just silently drop it before calling the service. (PR #1592)
- [ ] 4. ~~Supporting If-None-Match makes no sense for a delete operation. Remove.~~ (_should be removed from the Swagger spec and SDK if it doesn't apply_)

**Comment by JasonRShaver** [comment]
* add short summary
* remove if-none-match

Discussion:
Why should #3 logic be in CLI and not service side?

**Comment by jtuliani** [comment]
Re #3, as discussed with Jason, this needs to be client side
