### ISSUE TITLE
az backup protection enable-for-vm fails if vm and vault are on different resourcegroups

### ISSUE THREAD

**Issue by lserpietri** [Azure/azure-cli#11266]
## Describe the bug

**Command Name**
`az backup protection enable-for-vm`

**Errors:**
```
The Resource 'Microsoft.RecoveryServices/vaults/recoveryvault' under resource group 'backups' was not found.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- have the Recovery Service Vault and the VM to protect on different resource groups.
- `az backup protection enable-for-vm --policy-name {} --vm {} --resource-group {} --vault-name {}`

## Expected Behavior
I would expect this command to complete. If you point the command to the RG of the VM or the RG of the Vault it doesn't matter: it checks if they're on the same RG before continuing. On the Portal such task can be completed.

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

Extensions:
interactive 0.4.3

```

**Comment by sambitratha** [comment]
You can configure protection of VMs in different resource groups by passing the resourceID of the VM in --vm parameter. 

Hope this helps,
Thanks

**Comment by pvrk** [comment]
@lserpietri : As Sambit mentioned, please pass the full VM resource ID in the parameter. It is also documented [here](https://docs.microsoft.com/azure/backup/quick-backup-vm-cli#enable-backup-for-an-azure-vm) as a note.

**Comment by pvrk** [comment]
Closing this since documentation is present.
