### ISSUE TITLE
[DNS] 'az network dns zone import' doesn't work

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1126]
Attempted to import the attached zone file via the following command:

az network dns zone import -g rg1 -n mytestzone.com --file-name "C:\Users\jonatul\Desktop\Zone Files\mytestzone.com.dns.txt"

I just get a screen full of red error/call stack text.

The equivalent command via the old CLI works fine.
[mytestzone.com.dns.txt](https://github.com/Azure/azure-cli/files/547932/mytestzone.com.dns.txt)

**Comment by tjprescott** [comment]
The current import command is designed to consume the DNS zone file in the format that the export command outputs. We will overhaul them in tandem.

**Comment by tjprescott** [comment]
The main reason for the crash is because the current implementation cannot handle multiple TXT entries per record. I am adding your zone file to the test suite to guard against future regressions.
