### ISSUE TITLE
delete azure resource group when using azure cli

### ISSUE THREAD

**Issue by jerryeml** [Azure/azure-cli#11277]
## Describe the bug

**Command Name**
`az group delete`

**Errors:**
```
Deployment failed. Correlation ID: 8af52db8-f723-4e58-bfed-0a0502ad360e. Operation failed with status: 'Conflict'. Details: 409 Client Error: Conflict for url: https://management.azure.com/subscriptions/00e1eba3-cc83-42c4-a1c1-2542ceb993b1/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1TQUFTOjVGQUdFTlQ6NUZHT09EOjVGQlVJTEQtQ0VOVFJBTFVTIiwiam9iTG9jYXRpb24iOiJjZW50cmFsdXMifQ?api-version=2019-07-01
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group delete --resource-group {} --yes`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.76

Extensions:
azure-devops 0.12.0

```

**Comment by jerryeml** [comment]
Before last Sunday, every thing is fine.
But after that, I did not do anything change and get fail with the same command

**Comment by fengzhou-msft** [comment]
@Juliehzl please take a look.

**Comment by AhmedAbdoOrtiga** [comment]
any update?

**Comment by yonzhan** [comment]
add to S167

**Comment by zhoxing-ms** [comment]
@jerryeml Hi, may I ask if this question can be reproduced now?            
If the problem can still be reproduced, could you please look at the activity log of the undeleted resource on the portal? After clicking the failed operation name, there is a JSON information corresponding to the failure reason, please then tell me what is the error message and correlationId of the failure, thanks.

**Comment by jerryeml** [comment]
Hi, This issue has been resolved
Many thanks




何柏儒
國立中央大學網路學習科技研究所
HE,Bo-Ru
Graduate Institute of Network Learning Technology,
National Central University
E-mail: jerryeml1004615@g.ncu.edu.tw


Xing Zhou <notifications@github.com> 於 2020年3月16日 週一 下午3:12寫道：
