### ISSUE TITLE
az aks install helm

### ISSUE THREAD

**Issue by karok2m** [Azure/azure-cli#11278]
**Is your feature request related to a problem? Please describe.**
I would like to have option to install and setup Helm through az cli, similar to installation of kubect through [az aks install-cli](https://docs.microsoft.com/cli/azure/aks?view=azure-cli-latest#az-aks-install-cli).

**Describe the solution you'd like**
* az cli operation similar to `az aks install-cli` to install Helm.
* An az cli operation to setup [SSL/TLS connection between Helm and Tiller](https://v2.helm.sh/docs/using_helm/#using-ssl-between-helm-and-tiller) would also be very usefull.

**Describe alternatives you've considered**
Right now the only alternative is to manually install Helm and set up connection to the cluster.

**Additional context**
None

**Comment by palma21** [comment]
Seems like a good request! You mind filling it out on https://github.com/azure/aks as a feature request? We will triage it

**Comment by karok2m** [comment]
Opened [Feature: az aks install helm #1331](#1331) there.
