### ISSUE TITLE
Issues with 'az network dns zone export'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1128]
Issues with 'az network dns zone export'.  Compare with the output of the same command on the old CLI (see attached):
1. Missing heading comments giving zone name, RG, time, date etc.
2. Missing $TTL directive
3. Formatting is hard to read--add spaces between record sets, don't repeat record name on each record within a record set.
   [test-newCLI.txt](https://github.com/Azure/azure-cli/files/547961/test-newCLI.txt)
   [test-oldCLI.txt](https://github.com/Azure/azure-cli/files/547962/test-oldCLI.txt)

**Comment by JasonRShaver** [comment]
Discuss formats of these files
