### ISSUE TITLE
[create-remote-connection] - Option to ignore SSL certificate

### ISSUE THREAD

**Issue by sioakim** [Azure/azure-cli#11280]
I couldn't find an option to ignore SSL certification verification.
This is because of a custom SSL certificate on an ASE. 

Is there a way to ignore it and if not can you please add an option in the command line to override?

(domain name has been changed for security reasons)

## Describe the bug

**Command Name**
`az webapp create-remote-connection`

**Errors:**
```
HTTPSConnectionPool(host='bl.scm.zscusswsase00.web.domain.com', port=443): Max retries exceeded with url: /api/settings (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Traceback (most recent call last):
urllib3\urllib3\contrib\pyopenssl.py, ln 456, in wrap_socket
pip-install-dsvrkf2x\pyOpenSSL\OpenSSL\SSL.py, ln 1915, in do_handshake
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create-remote-connection --subscription {} --resource-group {} -n {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.65 *

Extensions:
webapp 0.2.24

```

**Comment by panchagnula** [comment]
@patricklee2 & @btardif please look at this. Thanks!

**Comment by ritchiefitz** [comment]
I am facing the same issue as well. Is there a way to ignore SSL certificate?

**Comment by panchagnula** [comment]
@btardif  can you take a look at this please?

**Comment by btardif** [comment]
FYI @sanchitmehta

**Comment by jiasli** [comment]
We do have an option `AZURE_CLI_DISABLE_CONNECTION_VERIFICATION` to ignore SSL certificate, but it doesn't work in many cases and has been nearly deprecated. To trust the custom root certificate, please see https://github.com/Azure/azure-cli/issues/1572#issuecomment-894029686.
