### ISSUE TITLE
Issues with 'az network dns record-set delete'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1130]
Issues with 'az network dns record-set delete':
- [ ] 1. ~~Remove support for --if-none-match.  This makes no sense for delete operations.~~
- [x] 2. SOA record sets are deleted with the zone, they cannot be deleted separately.  Remove from allowed values text. (PR #1129)
- [x] 3. --zone-name and --type should support short-form e.g. -z  and -t.  See comments on '...record-set create'
 (PR #1129)

**Comment by JasonRShaver** [comment]
* remove --if-none-match
* remove SOA
* add short names

**Comment by tjprescott** [comment]
@jtuliani if the `if_none_match` field makes so sense for delete operations, then why is it in the SDK? Whatever reason that may have for being there (however obscure) might apply to a user of the CLI.

**Comment by tjprescott** [comment]
Based on the above, for now we will continue to expose `if_none_match` on delete. If you decide to remove it from the SDK, the CLI will automatically reflect this.
