### ISSUE TITLE
generate-sas does not return json format

### ISSUE THREAD

**Issue by chbe8475** [Azure/azure-cli#11309]
When running the generate-sas I do not get the response in json, not even if specified with -o json.

az storage container generate-sas --policy-name writePolicy --account-name myStorageAccount -n containerName --subscription mySubscription -o json

Anyway to fix this?

/Christer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcba5ed-e693-6345-2c1b-c17422d7b8f9
* Version Independent ID: 58297400-b777-6868-1687-0af3a512a16f
* Content: [az storage container](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by fengzhou-msft** [comment]
@Juliehzl please take a look.

**Comment by Juliehzl** [comment]
Hi @chbe8475, sas token is in the format of string. May I know why you want json format?

**Comment by chbe8475** [comment]
Hi @Juliehzl , to conform with the format which other az commands returns.
I am scripting the use of a lot of az commands. When running this command it breaks my script since the returned object is a plain string, not json.
I was expecting something like:
```
{
   "generated-sas": "xyz"
}
```

**Comment by Juliehzl** [comment]
Most users expect sas token is returned as string. There is no much difference to get command result with string or json format in scripts. For more information , please refer to [here](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#use-the-right-output-mode-for-your-work-json-table-or-tsv). Given most users using current result format, we cannot change its output, which will breaking many customers. I think it is easy for you to adjust your script to get sas token value correctly.
Thanks a lot for your feedback. 😊 I will close this issue, but if you still have problems in usage, feel free to let me know and reopen it.
