### ISSUE TITLE
Improve update available message

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cli#11302]
Right now when I run `az -v` I get this:

`You have 4 updates available. Consider updating your CLI installation.`

It would be helpful to include a message on how the users should update or point them to the az cli install page.

`You have 4 updates available. Please consider updating your CLI installation.  Full instructions on how to update the Azure CLI can be found here: https://aka.ms/azurecliinstall`

Which points to `https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest`

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by fengzhou-msft** [comment]
similar to #10250
