### ISSUE TITLE
Is allowGatewayTransit support for cross subscription peering?

### ISSUE THREAD

**Issue by datafisk** [Azure/azure-cli#11319]
Hello,

Allowed via custom role / app another subscription to create peering between VNets across our separate subscriptions, we want to use Gateway Transit with the Gateway in the vpc-peered-cce-se-vnet. The peering was setup by the other side from  VNet k8s-se-team.westus2.azure.confluent.cloud. When trying to update the peering with Gateway Transit using the CLI it gives the following error, trying via the Portal UI just shows a red x with no info/text at all:

`az network vnet peering update -g vpc-peered-cce-se -n se-team --vnet-name vpc-peered-cce-se-vnet --set allowGatewayTransit=true`

**Subscription '1610debc-06e7-43ea-XXX-9ce83d3fee34' not found**. Check the spelling and casing and try again.

Running the show command gives the following output:
```
{
  "allowForwardedTraffic": true,
  "allowGatewayTransit": false,
  "allowVirtualNetworkAccess": true,
  "etag": "W/\"5e5d7bf9-9653-403a-ae5c-ec13c8a72315\"",
  "id": "/subscriptions/54ff81a0-e7f6-4919-XXXX-4cdd1c5f5ae1/resourceGroups/vpc-peered-cce-se/providers/Microsoft.Network/virtualNetworks/vpc-peered-cce-se-vnet/virtualNetworkPeerings/se-team",
  "name": "se-team",
  "peeringState": "Connected",
  "provisioningState": "Succeeded",
  "remoteAddressSpace": {
    "addressPrefixes": [
      "10.100.0.0/18"
    ]
  },
  "remoteVirtualNetwork": {
    "id": "/subscriptions/1610debc-06e7-43ea-XXXX-9ce83d3fee34/resourceGroups/ccloud-k8s-se-team.westus2.azure.confluent.cloud/providers/Microsoft.Network/virtualNetworks/k8s-se-team.westus2.azure.confluent.cloud",
    "resourceGroup": "ccloud-k8s-se-team.westus2.azure.confluent.cloud"
  },
  "resourceGroup": "vpc-peered-cce-se",
  "type": "Microsoft.Network/virtualNetworks/virtualNetworkPeerings",
  "useRemoteGateways": false
}
```

Is this setup supported?

regards,

Peter

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: e6754f86-e867-36a8-ad76-26ef330f5c28
* Version Independent ID: 2542c6dd-cece-3fce-8738-02c43f6496f4
* Content: [az network vnet peering](https://docs.microsoft.com/sv-se/cli/azure/network/vnet/peering?view=azure-cli-latest#az-network-vnet-peering-show)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@datafisk Thanks for reporting this issue. `Subscription '1610debc-06e7-43ea-XXX-9ce83d3fee34' not found.` Such error message is quite strange. Are you using a hybrid-cloud?

**Comment by datafisk** [comment]
@MyronFanQiu  thanks for the response, when you say hybrid, what feature(s) do you mean? I have a ipsec VPN connection from another VNet VGW landing on a VGW in the same VNet (vpc-peered-cce-se-vnet) that is as hybrid as this setup is. Let me know what info you need and i will be happy so provide.

**Comment by haroldrandom** [comment]
From our side, we can udpate the vnet peering across subscription as shown below.

![image](https://user-images.githubusercontent.com/14357159/69938401-32914100-1518-11ea-94a0-b0a9c2628479.png)

**Comment by haroldrandom** [comment]
@datafisk Are the resource group "ccloud-k8s-se-team.westus2.azure.confluent.cloud" in a private cloud?

**Comment by datafisk** [comment]
Hi Harold, thanks for the reply. The resource group is in a 3rd party Azure subscription that hosts a PaaS/IaaS service, Apache Kafka via Confluent Cloud, running on top of your AKS. 

Overall we got this to work across subscriptions as per the docs if it is initiated from the spoke, so the hub with the gateway is on my side, the spoke uses a custom role with the below permissions to manage the peerings on my side, i have no permissions ion the private cloud / resource group:
           \"Microsoft.Network/virtualNetworks/read\",
            \"Microsoft.Network/virtualNetworks/virtualNetworkPeerings/read\",
            \"Microsoft.Network/virtualNetworks/virtualNetworkPeerings/write\",
            \"Microsoft.Network/virtualNetworks/virtualNetworkPeerings/delete\",
            \"Microsoft.Network/virtualNetworks/peer/action\"

All looks as expected from the CLI when viewing the peering connection, but from the Azure Portal it shows a red x by the gateway transit checkbox.. 
<img width="356" alt="Screenshot 2019-11-21 at 18 07 54" src="https://user-images.githubusercontent.com/32514589/69966940-b0a11800-1517-11ea-9245-b609f08f0e0e.png">

I was thinking the GUI error could be a permissions thing, not sure what lookups are performed that causes the red x. 

Hope this helps, it works as expected albeit a bit strange output in the UI that we right now think is something with permissions.

**Comment by haroldrandom** [comment]
@datafisk Have you tried to reach help from Azure Support? 
It's the first time I meet an issue about acrosing cloud. I will search help for you inside company too.

**Comment by datafisk** [comment]
thanks @haroldrandom we have some Azure contacts that i will pursue as well on my side, thanks for helping out.
