### ISSUE TITLE
VM Scale set issue

### ISSUE THREAD

**Issue by aasif2310** [Azure/azure-cli#11327]
## Describe the bug

**Command Name**
`az vmss create`

**Errors:**
```
Azure Error: InvalidTemplateDeployment
Message: The template deployment 'vmss_deploy_hxmDzLnbc9mp3uxmdeaL91MFUrdvyEC7' is not valid according to the validation procedure. The tracking id is 'b05fb8d5-f1e8-4dd7-be6a-550dfc7cdd49'. See inner errors for details.
Exception Details:
	Error Code: QuotaExceeded
	Message: The operation couldn't be completed as it results in exceeding quota limit of Core. Maximum allowed: 4, Current in use: 4, Additional requested: 1. Read more about quota limits at https://aka.ms/AzurePerVMQuotaLimits. Submit a request for Quota increase using the link https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%2224b14b93-0bf2-4340-9c3e-16f1a7848e0f%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss create --resource-group {} --name {} --image {} --upgrade-policy-mode {} --instance-count {} --admin-username {} --generate-ssh-keys`

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

```

**Comment by fengzhou-msft** [comment]
@qwordy please take a look.

**Comment by qwordy** [comment]
The error message said it exceeded the quota. Have you try increasing quota using the given link?

**Comment by aasif2310** [comment]
Hi,

No i did not increase the quote, I was trying to create a scale set with 4
machine and it started giving me the error.
Question:
Can we have more 3 vm machine in the scale set with Trail license in azure?

Regards,
Aasif Faheem Ansari
Principal Consultant - AST Pvt Ltd.
*India : +91-98 60 442310*
Blog: http://siebel-ansari.blogspot.com <http://ansarifa.blogspot.com/>

**Comment by qwordy** [comment]
@shpa-microsoft, Hi Shalaka, Can we have more 3 virtual machines in the scale set with Trail license in azure?

**Comment by shpa-microsoft** [comment]
HI, So this quota is not per VMSS. It is per subscription. Do we have anything outside of this VMSS in this subscription? If we already have another VMSS. or VM then this can happen. In that case you can try deleting existing VM and then redo this operation OR increase quota limits

**Comment by shpa-microsoft** [comment]
Adding @Jun Wang (AZURE)<mailto:jwa@microsoft.com> to help with Trail license.

**Comment by wangjun-jwa** [comment]
Free trail allows for 4 vCPU per region.

**Comment by aasif2310** [comment]
Hello Team,

Thank you very much for the response and help here.

Regards,
Aasif Faheem Ansari
Principal Consultant - AST Pvt Ltd.
*India : +91-98 60 442310*
Blog: http://siebel-ansari.blogspot.com <http://ansarifa.blogspot.com/>

**Comment by yonzhan** [comment]
move to S163.

**Comment by yungezz** [comment]
hi @aasif2310 we'll close the issue for now, free trial allows for 4 vCPU per region, which could resolve the quota limit error, pls give it a try and reopen or create new issue if you met any other issue. thanks.
