### ISSUE TITLE
DevTest Labs VM Expand Properties Failing

### ISSUE THREAD

**Issue by adstep** [Azure/azure-cli#11320]
## Describe the bug

**Command Name**
`az lab vm show`

**Errors:**
```
Invalid properties were specified in the $expand query string parameter.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az lab vm show --lab-name $labName --name $vmName --resource-group $resourceGroupName --expand 'properties($expand=ComputeVm,NetworkInterface)' --query '{status: computeVm.statuses[0].displayStatus, fqdn: fqdn, ipAddress: networkInterface.publicIpAddress}'`

## Expected Behavior
```
{
  "fqdn": "lisalabvm.southcentralus.cloudapp.azure.com",
  "ipAddress": "13.85.228.112",
  "status": "Provisioning succeeded"
}
```
## Environment Summary
```
Windows-10-10.0.19028-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.74 *

Extensions:
azure-devops 0.3.0

```
## Additional Context
Running the exact command listed [in the documentation](https://docs.microsoft.com/en-us/azure/lab-services/devtest-lab-vmcli#verify-that-the-vm-is-available) and its failing.

**Comment by adstep** [comment]
Found a workaround. Wrap the expand query parameters in quotes.
```
az lab vm show --lab-name $labName --name $vmName --resource-group $resourceGroupName --expand '"properties($expand=ComputeVm,NetworkInterface)"' --query '"{status: computeVm.statuses[0].displayStatus, fqdn: fqdn, ipAddress: networkInterface.publicIpAddress}"'
```

**Comment by fengzhou-msft** [comment]
This is a known issue with Powershell. The double quotes in params are lost when passing through "%*" in a batch script. Command Prompt does not have this issue.
