### ISSUE TITLE
Install Azure CLI on AWS VM Centos 7.4

### ISSUE THREAD

**Issue by BharathNimmala-MSFT** [Azure/azure-cli#11338]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
This is a escalation from GitHub docs Repo for CLI 
https://github.com/microsoftdocs/azure-docs-cli/issues/1667 

**To Reproduce**

Customer is trying to do the below : 

I have installed Terraform CLI on an AWS instance as part of cross platform provisioning need to test few templates on Azure as well.

To get this, Terraform is prompting to install Azure CLI, when I try to install Azure CLI on AWS server where terraform CLI is installed i see below error -
Error: python-libs conflicts with python-virtualenv-1.10.1-4.el7.noarch
Error: Package: python-devel-2.7.5-58.el7.x86_64 (ultra-centos-7.4-base)
Requires: python(x86-64) = 2.7.5-58.el7
Installed: python-2.7.5-68.el7.x86_64 (installed)
python(x86-64) = 2.7.5-68.el7
Available: python-2.7.5-58.el7.x86_64 (ultra-centos-7.4-base)
python(x86-64) = 2.7.5-58.el7
How can I address this. Can we install Azur-CLI on AWS server to make Terraform work?
OS - CentOS Linux release 7.4.1708 (Core)

**Expected behavior**

**Environment summary**
OS - CentOS Linux release 7.4.1708 (Core)

**Additional context**
Customer wants to understand if we can install Azure-CLI on AWS server to make Terraform work.

**Comment by haroldrandom** [comment]
Which way were you using when installing?

**Comment by fengzhou-msft** [comment]
Please try agian with azure-cli 2.0.77, it depends on python3 now.

**Comment by haroldrandom** [comment]
progress on https://github.com/MicrosoftDocs/azure-docs-cli/issues/1667#event-2825712170
