### ISSUE TITLE
az group list --tag works for tag name=value but not tag name only

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#11342]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
These work:
az resource list --tag 'Cost Center'
az resource list --tag 'Environment=Production'
az group list --tag 'Environment=Production'

This should work but does not:
az group list --tag 'Cost Center' 

**To Reproduce**
Create resources and resource groups with tags matching queries above
Try the 4 commands above.

**Expected behavior**
Resource groups with matching tag returned

**Environment summary**
Cloud Shell

**Additional context**

**Comment by fengzhou-msft** [comment]
@Juliehzl please take a look.

**Comment by hihorika** [comment]
According to the command execution with `--debug` flag, the following endpoint is accessed, so it seems that tag value is handled as empty string ('') if only tag name is specified.

https://management.azure.com/subscriptions/<subscriptionId&gt;/resourcegroups?$filter=tagname%20eq%20%27<tagName&gt;%27%20and%20tagvalue%20eq%20%27%27&api-version=2019-07-01

**Comment by zhoxing-ms** [comment]
@jtuliani Hi, could you please download the latest version of azure-cli and try it? This problem no longer exists in the latest version.

**Comment by yonzhan** [comment]
@jtuliani any update?

**Comment by zhoxing-ms** [comment]
Because I haven't received any reply for a long time, I will close this issue first. If you still have questions, please feel free to give feedback.

**Comment by ggirard07** [comment]
Just running inside this same issue with v2.29.0 while running command such as `az group list --tag my-tag`.
Only way to get this working seems to be to specify an actual tag value `az group list --tag my-tag=tag-value`.

**Comment by zhoxing-ms** [comment]
@@ggirard07 This issue is due to the fact that service is not yet supported. If you have relevant needs, you can create feature request on https://github.com/Azure/azure-cli/issues/new?assignees=&labels=&template=Feature_request.md&title= and we will transfer it to service team
