### ISSUE TITLE
[DNS] Issues with adding/removing DNS records in new CLI 2.0

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1134]
DNS record add/remove has currently been implemented via:

az network dns record <record type> add
az network dns record <record type> remove

The help at 'az network dns record -h' is very cryptic and unhelpful, it has no explanation of what the user is supposed to do.

Specifying the record type as above is confusing since in other commands (record-set commands) the type is specified via a parameter (--type).  It's confusing to support type in two different ways.

It is not possible to create a record set and a record in a single command.  That should be possible and would be very useful.  Likewise to remove.

I think we need to meet discuss the options here, work out the best way forward.

**Comment by jtuliani** [comment]
As discussed:

- Go with: 'az network dns record-set add <record type> <type-specific args>
- This keeps the advantage of the az vs azure CLI that each record type has a dedicated command, thus you don't end up with a monster command with loads of parameters all mixed up covering every record type.
- Record data should use parameter long names exactly as azure cli (e.g. --nsdname not --dname) as these are DNS terminology
- Choose new short parameter names as best you can to fit.
- SOA is tricky, since these can't be added or removed.  Having considered options, for now we'll use the 'az network dns record-set add SOA <parameters>' command, and the help will simply have to explain that in this case the command does a replace rather than an add.

**Comment by jmspring** [comment]
The "help" around `az network dns record-set add` is completely lacking the necessary fields like `ipv4-address` for A records.

With the `az` cli, I went with:

`az network dns record-set create --resource-group="deisonk8srg" --zone-name="plusonetechnology.net" --type="A" --name="*"` 

then add the ipv4-address:

`az network dns record a add --resource-group="deisonk8srg" --zone-name="plusonetechnology.net" --record-set-name="*" --ipv4-address="168.61.71.200"`

The command `az network dns record-set add` does not exist:

```
jims@dockeropolis:~$ az network dns record-set add --help
usage: az network dns record-set [-h] {create,show,update,list,delete} ...
az network dns record-set: error: argument subcommand: invalid choice: 'add' (choose from 'create', 'show', 'update', 'list', 'delete')
```

The `az network dns record-set create` help is completely lacking detail:

```
jims@dockeropolis:~$ az network dns record-set create --type A --help

Command
    az network dns record-set create

Arguments
    --name -n           [Required]: The name of the RecordSet, relative to the name of the zone.
    --resource-group -g [Required]: Name of resource group.
    --type              [Required]: The type of DNS records in the record set.  Allowed values: A,
                                    AAAA, CNAME, MX, NS, PTR, SOA, SRV, TXT.
    --zone-name         [Required]: The name of the zone without a terminating dot.
    --ttl                         : Record set TTL (time-to-live).  Default: 3600.

Global Arguments
    --debug                       : Increase logging verbosity to show all debug logs.
    --help -h                     : Show this help message and exit.
    --output -o                   : Output format.  Allowed values: json, jsonc, list, table, tsv.
                                    Default: json.
    --query                       : JMESPath query string. See http://jmespath.org/ for more
                                    information and examples.
    --verbose                     : Increase logging verbosity. Use --debug for full debug logs.
```

And you are required to create a `record set` before adding records.  Per `az network dns record add --help`:

```
jims@dockeropolis:~$ az network dns record a add --help

Command
    az network dns record a add

Arguments
    --ipv4-address      [Required]: IPV4 address in string notation.
    --record-set-name   [Required]: The name of the RecordSet, relative to the name of the zone.
    --resource-group -g [Required]: Name of resource group.
    --zone-name         [Required]: The name of the zone without a terminating dot.

Global Arguments
    --debug                       : Increase logging verbosity to show all debug logs.
    --help -h                     : Show this help message and exit.
    --output -o                   : Output format.  Allowed values: json, jsonc, list, table, tsv.
                                    Default: json.
    --query                       : JMESPath query string. See http://jmespath.org/ for more
                                    information and examples.
    --verbose                     : Increase logging verbosity. Use --debug for full debug logs.
```

Try and add a record w/o a record set:

```
jims@dockeropolis:~$ az network dns record a add --resource-group="deisonk8srg" --zone-name="plusonetechnology.net" --record-set-name="bar" --ipv4-address="10.211.55.1"
The resource record 'bar' does not exist in resource group 'deisonk8srg' of subscription '04f7ec88-8e28-41ed-8537-5e17766001f5'.
```

**Comment by jtuliani** [comment]
@tjprescott Please can you clarify what the open issue is here which we are trying to resolve?

I think the existing commands are OK:

- the 'record-set' commands can create empty record sets, and delete record sets (including their contents).
- the 'record' commands can add and remove records, and can create/remove record sets implicitly

Most customers can do everything they need via the 'record' commands. The 'record-set' commands simply round out a couple of additional scenarios.

There is however an inconsistency in how the record type is specified between the 'record' and 'record-set' commands. Is that the issue we want to close on, or is it something else?

Thanks!

**Comment by tjprescott** [comment]
Well, originally I kept it open because the ask was to create records at the same time as creating the set, and even creating multiple records. However, I agree with you that since the record set is created implicitly through record add that the record-set commands are less relevant.

Ultimately, we need to nail down what the command tree should look like, since we don't want to avoid post-GA breaking changes.

**Comment by tjprescott** [comment]
I sent you an e-mail with a proposed restructuring that I think will address this and another issue. Please let me know ASAP if you'd like me to implement it.
