### ISSUE TITLE
[Functions] Add the ability to create v3 function apps

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#11349]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ahmedelnably** [comment]
Add the ability to choose a host version, with a default of ~2 (to be changed in the future to ~3)

**Comment by ahmedelnably** [comment]
cc/ @ankitkumarr

**Comment by yonzhan** [comment]
@ahmedelnably  How about the status of this issue?

**Comment by ahmedelnably** [comment]
This will be done in Q1 CY2020

**Comment by yonzhan** [comment]
move to S165.
