### ISSUE TITLE
Upgrade pip to a newer version when install via curl to support Python 3.8

### ISSUE THREAD

**Issue by MrStrik3** [Azure/azure-cli#11344]
**Describe the bug**
The installation of azure-cli with python 3.8 doesn't work anymore. The installation uses the attribute "linux_distribution" of the module platform and linux_distribution has been marked as deprecated since python 3.5 and has been remove in python 3.8.

**To Reproduce**
(needs python 3.8 installed as default python)
curl -L https://aka.ms/InstallAzureCli | bash 

**Expected behavior**
Should install, get this instead
➜  azure-cli curl -L https://aka.ms/InstallAzureCli | bash                  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1369  100  1369    0     0   1444      0 --:--:-- --:--:-- --:--:--  3048
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /tmp/azure_cli_install_tmp_jJk8ou.
######################################################################## 100.0%
/tmp/azure_cli_install_tmp_jJk8ou: OK
Running install script.
-- Verifying Python version.
-- Python version 3.8.0 okay.
Traceback (most recent call last):
  File "/tmp/azure_cli_install_tmp_jJk8ou", line 370, in <module>
    main()
  File "/tmp/azure_cli_install_tmp_jJk8ou", line 349, in main
    verify_native_dependencies()
  File "/tmp/azure_cli_install_tmp_jJk8ou", line 309, in verify_native_dependencies
    distname, version, _ = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

**Environment summary**
ArchLinux, python 3.8, bash

**Comment by rnnr** [comment]
The function platform.linux_distribution() is deprecated since python 3.5 and was removed in Python 3.8, according to this: https://bugs.python.org/issue28167

**Comment by rnnr** [comment]
Aside the install.py script using that function, also pip has to be updated to a newer version - currently used version 8.1.0 (3.5 years old) is using it too in download.py. I did no investigation beyond this point.

**Comment by fengzhou-msft** [comment]
@rnnr The fix https://github.com/Azure/azure-cli/pull/11322 will be release next week.

**Comment by haroldrandom** [comment]
Should be fixed here https://github.com/Azure/azure-cli/pull/11322

**Comment by fengzhou-msft** [comment]
@haroldrandom please take a look at the pip version issue mentioned above.

**Comment by haroldrandom** [comment]
1. @MrStrik3 Currently, azure-cli didn't support ArchLinux
2. `platform.linux_distribution()` deprecation proble should be fixed [here](https://github.com/Azure/azure-cli/issues/11344). Please have a wait until the latest azrure-cli release.
3. @rnnr Thanks for the feedback. We will consider upgrading the `pip`.

**Comment by haroldrandom** [comment]
@MrStrik3 we have no plan for support install azure-cli on ArchLinux for now. Maybe later if users from ArchLinux request more.

I think this can be closed if a new version of pip is not your request.

**Comment by rnnr** [comment]
This is IMHO not about Arch Linux but about Python 3.8 and using outdated
libs - manifestation in Arch Linux is just matter of "luck" and some unwise
decisions about Python made by the maintainers of the distro.

The same would happen to anybody trying to use Python 3.8, Arch Linux is
just the first affected.

**Comment by haroldrandom** [comment]
The question block you isn't pip but `platform.linux_distribution()` deprecation in Python 3.8 instead.
 
Reopen and title changed to "Upgrade pip to a newer version when install via curl"

**Comment by haroldrandom** [comment]
@rnnr Please have a test against the related PR.
