### ISSUE TITLE
Kudu ZipDeploy through Azure CLI fails due to autoswap

### ISSUE THREAD

**Issue by JiriKovar** [Azure/azure-cli#11343]
Hi,

During the past couple of weeks, we've started getting lots of errors when deploying to web app via Kudu ZipDeploy run through Azure CLI ('az webapp deployment source config-zip' command). The problem seems to be that Azure CLI is polling for deployment completion is not robust enough. Based on the kudu logs, most of the problems are caused by autoswapping causing a race condition with the polling mechanism, where the request polling for release completion is either unfinished (the request trace log in Kudu of the request is unfinished), or the request hits the staging slot after the swap and Azure CLI command reports it as an error.

Here's an example of the trace of an aforementioned unfinished request (by the way the name of the trace is 2019-11-20T14-16-18_9762c3_006_GET_api-deployments-latest_**pending**.xml:
`<step title="Incoming Request" date="2019-11-20T14:16:18.457" instance="9762c3" url="/api/deployments/latest" method="GET" type="request" pid="23376,2,10" Connection="Keep-Alive" Content-Type="application/octet-stream" Accept="*/*" Accept-Encoding="gzip, deflate" Authorization="Bas..." Host="deliver-api-qa-us-staging.scm.azurewebsites.net" User-Agent="AZURECLI/2.0.74" X-WAWS-Unencoded-URL="/api/deployments/latest" CLIENT-IP="85.93.116.83:37150" X-ARR-LOG-ID="032bba42-f5a6-4728-87ed-d689ebb932d0" X-SITE-DEPLOYMENT-ID="deliver-api-qa-us" WAS-DEFAULT-HOSTNAME="deliver-api-qa-us-staging.scm.azurewebsites.net" X-Forwarded-Proto="https" X-AppService-Proto="https" >
  <step title="Cleanup Xml Logs" date="2019-11-20T14:16:19.282" />
  <step title="DeploymentService.GetResult" date="2019-11-20T14:16:25.831" >
    <step title="DeploymentService.GetLatestDeployment" date="2019-11-20T14:16:27.720" >
      <step title="DeploymentManager.GetResults" date="2019-11-20T14:16:29.829" `

**Environment:**
azure-cli                         2.0.74 *

command-modules-nspkg              2.0.3
core                              2.0.74 *
nspkg                              3.0.4
telemetry                          1.0.3 *

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

**Comment by panchagnula** [comment]
@JiriKovar are you still seeing this with the latest version of CLI. I believe Kudu itself has made some fixes here. Please let us know. Thanks!

**Comment by JiriKovar** [comment]
Hi @panchagnula,

everything looks fine now. 

Thank you very much.
