### ISSUE TITLE
Managed identity commands do not work for functionsapps

### ISSUE THREAD

**Issue by mathiasmaerker** [Azure/azure-cli#11341]
## Describe the bug

**Command Name**
`az functionapp identity show`

**Errors:**
```
'NoneType' object has no attribute 'identity'
Traceback (most recent call last):
Temp\pip-install-umfcm_n2\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 654, in _run_job
Local\Temp\pip-install-umfcm_n2\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure\cli\core\commands\arm.py, ln 738, in handler
azure\cli\core\commands\arm.py, ln 750, in show_exception_handler
azure\cli\core\commands\arm.py, ln 736, in handler
azure\cli\command_modules\appservice\custom.py, ln 652, in show_identity
AttributeError: 'NoneType' object has no attribute 'identity'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp identity show --name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.76

```

**Comment by mizrael** [comment]
any chance we can get an update on this?

**Comment by navba-MSFT** [comment]
@mathiasmaerker Apologies for the late reply. Could you please let me know if you are still facing the same issue with [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of Az CLI? Awaiting you reply.
