### ISSUE TITLE
az eventgrid event-subscription create --event-delivery-schema cloudeventsv1_0 with WebHook does not use the correct event schema

### ISSUE THREAD

**Issue by pableess** [Azure/azure-cli#11358]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
using 
"az eventgrid event-subscription create --event-delivery-schema cloudeventsv1_0" for a web hook is not working.  It is calling WebHook validation using EventGrid schema instead of CE schema

**To Reproduce**
Create an EventGrid Domain (with input-schema cloudeventsv1_0)

Run command
az eventgrid event-subscription create --event-delivery-schema cloudeventsv1_0

In my logs of my web hook the Event Grid Validation is doing a POST to my endpoint using Event Grid Validation.  It should be doing an OPTIONS request (respecting CloudEvents validation protocol)

It works when creating subscription from Azure portal but not from CLI 

**Expected behavior**
It should be doing an OPTIONS request (respecting CloudEvents validation protocol)

**Environment summary**
Window MSI install latest version 
az extension add -n eventgrid

**Comment by ahamad-MS** [comment]
Hello @pableess Thanks for reporting this issue. Can you please provide us with the following information:

1. Name of the domain and event subscription.
2. Region.
3. Time (Day/hour/minute) when this is happening.
4. Is this still repro for you?
5. Is this happening when trying to use CLI only?

**Comment by pableess** [comment]
Hi this issue occurred last week. I ran the exact same CLI command today
and it did cloud event schema validation correctly. It appears that MS must
have fixed this recently .

   1. Name of the domain and event subscription.    Oralcare-cloudevents-dev


   1. Region. CentralUS
   2. Time (Day/hour/minute) when this is happening. All day Friday Nov 22.
   3. Is this still repro for you?
   4. Is this happening when trying  to use CLI only? On when using CLI.
   Portal worked ok.

**Comment by ahamad-MS** [comment]
Thanks @pableess . We had couple of fixes in this area recently hence we wanted to confirm if the issue still persists for you. I am closing this issue but please feel free to open a support ticket with related information specified earlier if the issue happened again.

thanks
