### ISSUE TITLE
Drop support for Python 2 in azure-cli

### ISSUE THREAD

**Issue by rodrigc** [Azure/azure-cli#11362]
**Is your feature request related to a problem? Please describe.**
Certain new features of azure-cli and its extensions are using Python-3 only features, causing problems on Python-2, such as https://github.com/Azure/azure-cli/issues/11206 .

Since the Python project is dropping support for Python 2 in 2020: https://pythonclock.org/

At some point azure-cli should probably drop support for Python 2 as well,
since maintaining code which can work perfectly on Python 2 and Python 3 is a maintenance burden.

**Describe the solution you'd like**
Drop support for Python-2 in azure-cli, and error out if you try to install azure-cli with Python-2.

**Comment by fengzhou-msft** [comment]
Thanks for submitting this issue and a PR to fix it. RPM with Python 3 will roll out before Thanksgiving thanks to your previous PR #11235. Let's see how people react to that change. We will then evaluate when to officially drop support for Python 2.

**Comment by fengzhou-msft** [comment]
We still have about 10% active users on Python 2. We may defer the drop for Python 2 for a bit longer. As more users install RPM with Python 3, I believe the number of Python 2 would drop significantly since the majority of our Python 2 users are on centos or redhat.
