### ISSUE TITLE
[Functions] Add support for Node 12

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-cli#11364]
The functions service will soon allow the hosting of Node 12 applications, and we should support creating apps with Node 12. By the time this is available this should default to V3 (and maybe Linux, depending on timelines).

**Comment by ColbyTresness** [comment]
@ahmedelnably as FYI

**Comment by ColbyTresness** [comment]
Scenarios we care about:
* Creation of Node 12 app
* Validation that versions match on publishing
* When a user upgrades to V3, ensure that their Node versions are compatible

**Comment by ahmedelnably** [comment]
@ColbyTresness 

- Creation of Node 12 app --> this will be supported
- Validation that versions match on publishing --> not in scope for Az CLI
- When a user upgrades to V3, ensure that their Node versions are compatible --> Can we make sure that this get added to the stacks API

**Comment by ColbyTresness** [comment]
Re #3, we'll do this on the server side as well, but we want to make sure the tooling pushes people down the right path

**Comment by ahmedelnably** [comment]
This will be done in Q1 CY2020

**Comment by yonzhan** [comment]
@ahmedelnably If the CLI commands are contributed by service team and CLI team currently does not take over, we will mark the Service Attention label. Do you think it is not the case?
