### ISSUE TITLE
azure cli doesn't use python from pyenv

### ISSUE THREAD

**Issue by qubitron** [Azure/azure-cli#11372]
**Describe the bug**
The azure cli fails to run on mac when the user is running in a pyenv environment in the terminal, and the current environment is not a python 3.7 environment. 

The relevant code from the cli:
```
cat /usr/local/bin/az

#!/usr/bin/env bash
export PYTHONPATH="/usr/local/Cellar/azure-cli/2.0.59/libexec/lib/python3.7/site-packages"

if command -v python3.7 >/dev/null 2>&1; then
  python3.7 -m azure.cli "$@"
else
  python3 -m azure.cli "$@"
fi
```

**To Reproduce**
Install the azure cli
Install pyenv
Install and switch to a python 3.6 interpreter
Try to run the azure cli

**Expected behavior**
The CLI should fall back to its own private copy of python in this case

**Environment summary**
Described above

**Additional context**

**Comment by haroldrandom** [comment]
I think the output is fine.

You should install azure-cli after active `pyenv active {YOUR_VIRTUALENV_CREATED_BY_PYENV}`

**Comment by haroldrandom** [comment]
Can this be closed?

**Comment by qubitron** [comment]
@haroldrandom I wanted to make sure you have covered the repro for this issue, have you tried using a python 3.6 environment with pyenv and using the azure CLI?

@kulkarnisonia16 would you be able to to check if this issue still repros for you on the latest cli version?

**Comment by haroldrandom** [comment]
@qubitron Yes, I have. Please have a look. 
![image](https://user-images.githubusercontent.com/14357159/69601159-391e4500-104e-11ea-8064-22f014835727.png)

I think **You should install azure-cli after active pyenv active {YOUR_VIRTUALENV_CREATED_BY_PYENV}**

**Comment by haroldrandom** [comment]
you currently installed azure-cli is placed in system-wide Python environment which is different from pyenv installed Python interpreter.

you should use the Python intepreter that pyenv used and install azure-cli via pip install, and create a virtual python environment using the same Python intepreter such that azure-cli can be inherited automatically.

**Comment by qubitron** [comment]
@haroldrandom I believe the expectation here is that the az command continues to use the private install of python, and doesn't require the user to install into their virtual environment. Installing the az cli into your virtual environment can break dependencies for your app.

@zooba can you advise?

**Comment by haroldrandom** [comment]
@fengzhou-msft Please take a look.

**Comment by fengzhou-msft** [comment]
Please indicate which version of azure-cli you are using.

**Comment by qubitron** [comment]
@kulkarnisonia16 could you confirm if this still repros with the latest azure CLI

**Comment by fengzhou-msft** [comment]
Close now as we resolved it in email.
