### ISSUE TITLE
ACS create fails with no username

### ISSUE THREAD

**Issue by rgardler** [Azure/azure-cli#1137]
--admin-username defaults to 'root' which is not allowed:

$ az acs create --resource-group rgacsazcli --orchestrator-type DCOS --name rgacsazcli --dns-name-prefix rgacsazcli
Error loading command module 'iot'
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "error": {
    "code": "InvalidParameter",
    "target": "windowsProfile.adminUsername",
    "message": "Linux admin user name cannot be 'root' or be longer than 64 characters."
  }
}

**Comment by rgardler** [comment]
//cc @sauryadas

**Comment by mayurid** [comment]
//cc @yugangw-msft to take a look

**Comment by yugangw-msft** [comment]
We defaults the `--admin-username` to the current user which invokes the command through a standard python api of `getpass.getuser()`
@rgardler, I also know `admin` is not allowed. We can do client side validation under following context:
1. Server side can't fail fast by doing validating
2. We know well the blacklist.

**Comment by yugangw-msft** [comment]
@rgardler @sauryadas, I don't plan to work on this issue until the point 2 gets consolidated. 
Otherwise, I suggest we live with it for now

**Comment by sauryadas** [comment]
@yugangw-msft the default username should be 'azureuser' , thats what we default in the portal as well

**Comment by rgardler** [comment]
@yugangw-msft if you run by one of the recommended options for the az cli (Docker) then the user is 'root' and will always be 'root'. For this reason I don't believe 'live with it' is an option here since it will always fail (when run in Docker) when this optional parameter is not provided

As @sauryadas indicates the expected default is 'azureuser', it should not be the user I happen to be logged in as at the time of executing the command.

**Comment by yugangw-msft** [comment]
@sauryadas, @yugangw-msft , to get it clear, portal doesn't defaults to 'azureuser', rather it is a required field you have to input a name. 
But, due to the scenario you outlined, plus I also ran into it, i am fine to make the switch.
