### ISSUE TITLE
Error when try to follow Microsoft tutorial https://docs.microsoft.com/en-us/learn/modules/develop-app-that-queries-azure-sql/5-exercise-connect-aspnet-to-azure-sql

### ISSUE THREAD

**Issue by noelram** [Azure/azure-cli#11384]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- Follow the steps in https://docs.microsoft.com/en-us/learn/modules/develop-app-that-queries-azure-sql/5-exercise-connect-aspnet-to-azure-sql. It fails in command:
WEBAPPNAME=educationapp-$RANDOM
az webapp up \
    --resource-group learn- ... XXX-7afdfd35530e \
    --sku F1 \
    --name $WEBAPPNAME

- `az webapp up --resource-group {} --sku {} --name {}`

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

```

**Comment by fengzhou-msft** [comment]
Please upgrade to azure-cli 2.0.77 and try again.

**Comment by panchagnula** [comment]
Make sure you are using the latest version of Azure-cli & running the command from the context of the local directory where the code is - please reactivate if this still an issue.
