### ISSUE TITLE
ctrl-D exits cli

### ISSUE THREAD

**Issue by exFalso** [Azure/azure-cli#11382]
## Describe the bug

**Command Name**
no command

**Errors:**
no errors

## To Reproduce:

Input command, put cursor at to-be-deleted character, Ctrl-D. Instead of deleting the character it exits the cli

## Expected Behavior

Character at cursor should be deleted

## Environment Summary
```
Linux-5.3.11-arch1-1-x86_64-with-arch
Python 3.6.8
Shell: bash

azure-cli 2.0.76

Extensions:
interactive 0.4.3

```

**Comment by jiasli** [comment]
<kbd>Ctrl</kbd>+<kbd>D</kbd> is the official shortcut to exit the interactive python or bash. Though I understand it deletes a character after the cursor in Emacs. 😃

https://docs.python.org/3/using/cmdline.html#interface-options
> When called with standard input connected to a tty device, it prompts for commands and executes them until an EOF (an end-of-file character, you can produce that with Ctrl-D on UNIX or Ctrl-Z, Enter on Windows) is read.

Maybe consider using <kbd>Del</kbd>?
