### ISSUE TITLE
Multiple arguments to script action

### ISSUE THREAD

**Issue by JordanSimba** [Azure/azure-cli#11398]
Is there an elegant way to reliably pass multiple arguments into the --script-parameters option for the az hdinsight script-action api?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1afaecd-2586-7ba4-9984-37ae8fa3c8db
* Version Independent ID: 3f5512bf-2710-e0ac-2da7-f4f5b31b6b56
* Content: [az hdinsight script-action](https://docs.microsoft.com/en-us/cli/azure/hdinsight/script-action?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/hdinsight/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/hdinsight/_help.py)
* Service: **hdinsight**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by aim-for-better** [comment]
This parameter needs a string. Per our side how to handle this string parameter is related with customer's specific script.

Could you please provide more details about your scenario to help us understand more?

**Comment by aim-for-better** [comment]
This issue is a question. ` --script-parameters` needs a string, this is by design.
