### ISSUE TITLE
Remove support for Python 3.4

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-cli#11391]
Python 3.4 has been removed from [azure-sdk-for-python](https://github.com/Azure/azure-sdk-for-python#azure-sdk-for-python) and is not supported for some features. Azure CLI should also remove it.

**Comment by haroldrandom** [comment]
Add it to S162

**Comment by haroldrandom** [comment]
@fengzhou-msft Could you reference more issues or problems?

Offering a case, but not related to OpenSSL.
I test to install azure-cli in Ubuntu 18.04 under Python 3.4. Breaks by requests~2.22 not supported.

![image](https://user-images.githubusercontent.com/14357159/70292659-b8173880-1819-11ea-9296-afd0708f5443.png)

**Comment by fengzhou-msft** [comment]
Python 3.4 has been retired(https://www.python.org/dev/peps/pep-0429/#release-schedule). And this is the related [PR](https://github.com/Azure/azure-sdk-for-python/pull/6131) in azure-sdk-for-python.

@haroldrandom you already proved that azure cli is not compatible with python 3.4 now, and since python 3.4 is already dead, we should just remove it in the support list.

**Comment by haroldrandom** [comment]
> Python 3.4 has been retired(https://www.python.org/dev/peps/pep-0429/#release-schedule). And this is the related [PR](https://github.com/Azure/azure-sdk-for-python/pull/6131) in azure-sdk-for-python.
> 
> @haroldrandom you already proved that azure cli is not compatible with python 3.4 now, and since python 3.4 is already dead, we should just remove it in the support list.

But, what if we downgrade request to a lower version? It may work.

Python 3.4 has a higher market share than 3.7's. Does we have a number about how many issues runing on Python 3.4? If not so many, I think this PR is good.
