### ISSUE TITLE
Docs do not have a link to "Create a Custom Extension"

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cli#11399]
When here: https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview?view=azure-cli-latest

I expect to see a "Create a Custom Extension" link in the TOC which points to: https://github.com/Azure/azure-cli-dev-tools

In this tree: 
![image](https://user-images.githubusercontent.com/2163001/69637532-a958a680-100d-11ea-80a0-10fce307cf85.png)

**Comment by haroldrandom** [comment]
Thansk for the suggestion. We will take a look on it soon.

**Comment by haroldrandom** [comment]
I would suggest this link https://github.com/Azure/azure-cli/tree/master/doc/extensions be more official even though they point to the same page eventually.
