### ISSUE TITLE
other Service Tags supported, but not documented

### ISSUE THREAD

**Issue by dr-ivan** [Azure/azure-cli#11406]
The below statements are part-true, as they imply a finite list. Can it be reworded to state that it supports all available 'service tags' including AzureCloud. 

"--source-address-prefixes & --destination-address-prefixes
Space-separated list of CIDR prefixes or IP ranges. Alternatively, specify ONE of 'VirtualNetwork', 'AzureLoadBalancer', 'Internet' or '*' to match all IPs."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe4941c-7b46-b9fb-1c52-98e68f6354cc
* Version Independent ID: d1bc72fb-ccf9-9645-7b1d-98c91bc75a55
* Content: [az network nsg rule](https://docs.microsoft.com/en-us/cli/azure/network/nsg/rule?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
Thansk for the suggestion! We will look into it.
