### ISSUE TITLE
query related to az command of load balancer

### ISSUE THREAD

**Issue by vermaaakansha** [Azure/azure-cli#11401]
query related to az command of load balancer

what does [**--expand**] property means in command **az network lb show [--expand]**

Documentation given on the link - https://docs.microsoft.com/en-us/cli/azure/network/lb?view=azure-cli-latest#az-network-lb-show doesnt seems to be satisfying and unclear. 

Can you please explain the property. thank you.

**Comment by haroldrandom** [comment]
Thansk for the feedback!
We need to take a look that code and reach back to you soon.

**Comment by haroldrandom** [comment]
Hi, @vermaaakansha --expand is used to expand the referenced resource I think.
For example, the lb may refer to other resources. But IMO, the option seems like  doesn't work for lb.

**Comment by MyronFanQiu** [comment]
@vermaaakansha Hello. Do you have any other question?

**Comment by haroldrandom** [comment]
Closed as long time no response. Feel free to reopen. :)
