### ISSUE TITLE
Move Aladdin content to single file

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#11405]
This work item is for tracking the project discussed between Arun, Yong, Jason, and @albaloo 

Details (copied from email, contact jasonsha@microsoft for details)

Today, example content is loaded from the module’s _help.py file.  
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/lab/_help.py

When Aladdin wants to add a new managed (generated) example, it submits a PR for a specific module:
https://github.com/Azure/azure-cli/pull/10890

This results in a limit on how many commands can be onboarded to Aladdin by how many PRs the CLI team can handle, for example, this is a subset of PRs generated by a single Aladdin update:

Instead, the Aladdin team proposes 
•	Aladdin team produces a single “azure-cli/src/azure-cli-core/azure/cli/core/_aladdin_kb.py” file that contains the entire Aladdin example KB
•	The CLI team then writes new client-side logic that, at runtime, merges Aladdin and _help.py content and displays to the user
o	CLI team controls logic for how many to display and the order (Aladdin will give rank values for each Example)
•	The CLI team adds a flag to _help.py to define an example as being ‘pinned’ (always shown before Aladdin content)

**Comment by haroldrandom** [comment]
Thanks for the suggestions! We will look into it.

**Comment by yonzhan** [comment]
add to S163, high priority.

**Comment by haroldrandom** [comment]
Hi, Jason, I found it will cause error if `aladdin.py` is in `src/azure-cli/azure/cli/commands_modules/`

Also, the file get put into `src/` will get CI scaned, currently, there are some violiations which failed CI.

I put your file in a dedicated folder `scripts/ci/aladdin` and it's in a detacted branch `Aladdin-src`, which will won't get pylint and flake8 scanned if you guys don't want to deal with Python style detail 
Please take a look this PR https://github.com/Azure/azure-cli/pull/11694 which is automatically create by Pipeline.
