### ISSUE TITLE
Blob Update with Storage Blob Data Contributor

### ISSUE THREAD

**Issue by mhennecke** [Azure/azure-cli#11414]
## Describe the bug

**Command Name**
`az storage blob update`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob update --debug --verbose --account-name {} --container-name {} --auth-mode {} --name {} --content-cache-control {} --auth-mode {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.69 *
azure-cli-iot-ext 0.7.1

Extensions:
azure-cli-iot-ext 0.7.1

```

**Comment by haroldrandom** [comment]
Thanks for the feedback, please @Juliehzl take a look.

**Comment by Juliehzl** [comment]
@mhennecke  can you try again with the latest azure cli version? If you still have the problem, please provide debug information with `--debug` in your command.
I cannot reproduce it with azure cli 2.0.78.

**Comment by mhennecke** [comment]
Duplicate of #11415
