### ISSUE TITLE
az webapp create is removing existing application settings

### ISSUE THREAD

**Issue by pajzo** [Azure/azure-cli#11412]
## Describe the bug
When `az webapp create` is called every time a new pipeline is running, all existing appsettings is removed and it's force the site to break down if ex. WEBSITE_RUN_FROM_PACKAGE=1

**Command Name**
`az webapp create`

**Errors:**
See above description.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create --name {} --plan {}`

Trough the portal or anywhere you can add an application setting do that. Then run the same command again.

- `az webapp create --name {} --plan {}`

Now the application setting you created before is deleted.

We are using Azure CLI in our CI/CD pipeline so we are running the same command over and over again. Previous we used Azure ARM, which has not the same issue.

## Expected Behavior
Keep existing application settings.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.76 *

Extensions:
azure-devops 0.8.0
dev-spaces-preview 0.1.6
interactive 0.4.3

```
## Additional Context

It looks like `az webapp deployment slot create` is not removing existing application settings when called, so it would be cool if `az webapp create` can act the same way.

**Comment by panchagnula** [comment]
Need to look further into this. @ammanifold  FYI.

**Comment by yonzhan** [comment]
@ammanifold any update for this issue?

**Comment by ammanifold** [comment]
WIP

**Comment by yonzhan** [comment]
move to S165.

**Comment by yonzhan** [comment]
move to S166.

**Comment by yonzhan** [comment]
move to S167.

**Comment by yonzhan** [comment]
@ammanifold any update for this issue?

**Comment by panchagnula** [comment]
@kotasudhakarreddy can you check if this still repros with the latest version please? Thanks!

**Comment by Kotasudhakarreddy** [comment]
looking in to it.

**Comment by Kotasudhakarreddy** [comment]
@panchagnula yes I am able to repro this is issue. looking further to fix the issue.
