### ISSUE TITLE
Can't upload django app to webapp

### ISSUE THREAD

**Issue by aclark-ax** [Azure/azure-cli#11417]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
[Errno 2] No such file or directory: ''
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 652, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/command_modules/appservice/_create_util.py, ln 192, in parse_netcore_version
    parsed_file = ET.parse(file_path)
python3.7/xml/etree/ElementTree.py, ln 1197, in parse
    tree.parse(source, parser)
python3.7/xml/etree/ElementTree.py, ln 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: ''
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --sku {} -n {} -l {} --resource-group {}`

## Environment Summary
```
Darwin-18.2.0-x86_64-i386-64bit
Python 3.7.5
Shell: bash

azure-cli 2.0.76

```

**Comment by panchagnula** [comment]
Please use the latest version 2.0.77  this was a regression in 2.0.76. Please feel free to re-open if latest version doesn't resolve the issue. Thank you.

**Comment by aclark-ax** [comment]
When you say latest version of 2.0.77, latest version of what?

**Comment by panchagnula** [comment]
@aclark-ax latest version of CLI https://pypi.org/project/azure-cli/
