### ISSUE TITLE
--private-ip-address "" is not working to set DHCP

### ISSUE THREAD

**Issue by motaba1** [Azure/azure-cli#11416]
commend:
az network nic ip-config update --name $ipconfigname --nic-name $MyNic --resource-group $MyResourceGroup --private-ip-address ""
gives me this error message (and I am unable to change static IP address to DHCP address):
az network nic ip-config update: error: argument --private-ip-address: expected one argument

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79836d6b-b885-294c-cbeb-0e4d4be3d250
* Version Independent ID: e05e7ff9-fd88-663b-eecf-9d6ae2c75d40
* Content: [az network nic ip-config](https://docs.microsoft.com/en-us/cli/azure/network/nic/ip-config?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
@MyronFanQiu Please take a look

**Comment by motaba1** [comment]
this is my AZ version:
az --version
azure-cli                         2.0.77

command-modules-nspkg              2.0.3
core                              2.0.77
nspkg                              3.0.4
telemetry                          1.0.4

**Comment by haroldrandom** [comment]
By passing --private-ip-address "", do you want to clear up the privateIPAddress of the nic?

**Comment by haroldrandom** [comment]
tyr `--private-ip-address=""` ?

**Comment by haroldrandom** [comment]
BTW, which shell do you use? Windows CMD / PowerShell / Git-Bash?

**Comment by MyronFanQiu** [comment]
@motaba1 Hello. This might be a issue of powershell. Did you solve your issue?

**Comment by haroldrandom** [comment]
Close as long time no response. Feel free to reopen. :)
