### ISSUE TITLE
Implement list all functionality for acs

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-cli#1141]
We will update the acs list functionality to have list-all behavior when a RG is not provided.
yugangw-msft: Can you work on this.

//cc: @sauryadas

**Comment by sauryadas** [comment]
Thanks @mayurid 

@yugangw-msft here are the 2 API's

https://msdn.microsoft.com/en-us/library/azure/mt711473.aspx 
https://msdn.microsoft.com/en-us/library/azure/mt703445.aspx

**Comment by yugangw-msft** [comment]
Opened a Azure/azure-rest-api-specs#630, which should be fixed first.

**Comment by mayurid** [comment]
@yugangw-msft : Did we get unblocked for this with an updated SDK?

**Comment by yugangw-msft** [comment]
it is in
