### ISSUE TITLE
az --version: CLI version cannot be parsed programmatically -> have -json switch or switch to output only version number

### ISSUE THREAD

**Issue by bergmeister** [Azure/azure-cli#11425]
**Is your feature request related to a problem? Please describe.**
`az --version` outputs a lot of text that cannot be parsed easily and in a reliable way in order to determine the CLI version programmatically (e.g. from PowerShell)

**Describe the solution you'd like**
Either an option to output a machine parse-able output such as e.g. JSON or a switch to output only the version of the CLI as one string

**Describe alternatives you've considered**
No alternative, hacks like awk/grep/sed are common in the Unix world but are too much effort, too brittle and some of those are not available on Windows where the main automation tool is PowerShell (sometimes the `az` still has to be used though due to feature gaps of the azure powershell module)

**Additional context**
I had to check the az version to be greater than `v2.0.69` as this is a minim requirement for the azure devops CLI extension.

**Comment by haroldrandom** [comment]
Yes, good suggestion!

For your question, there should be a way to parse version string.

For too many outputs, we will think about it.

**Comment by yonzhan** [comment]
add to S163.

**Comment by fengzhou-msft** [comment]
A potential solution is to add `--short/-s` option for `az --version` to output just the version of CLI. This involves changing code in knack. `az --version` is handled specially by [checking `args[0] == '--version' or args[0] == '-v'`](https://github.com/microsoft/knack/blob/44ee1799c891213c90916f186ab9aee7b9ff8344/knack/cli.py#L96), then [invoke show_version()](https://github.com/microsoft/knack/blob/44ee1799c891213c90916f186ab9aee7b9ff8344/knack/cli.py#L198) without passing in the args. 

To avoid breaking changes in knack, we may want to add a `show_short_version()` method or more generic `show_version_with_args()`.

**Comment by fengzhou-msft** [comment]
After some discussion, we do not want overcomplicate the special case of `az --version`. @jiasli will author a new command to output short version.

**Comment by MikeMorawski** [comment]
This is the way I have done it:

`(-join (az version) | convertFrom-Json).'azure-cli'`
