### ISSUE TITLE
Update CLI specifications for Resources to be created/updated as part of Microsoft.Compute/ProximityPlacementGroup

### ISSUE THREAD

**Issue by rosingla** [Azure/azure-cli#11420]
**Resource Provider**
Microsoft.Compute

**Description of Feature or Work Requested**
This issue propose changes in cmdlet w.r.t. Proximity Placement Group to support following features.

- To update the Proximity Placement Group reference of a resource (VM/AvSet/VMSS)
- To show colocation status of a Proximity Placement Group.

More details alongwith the proposed changes in the corresponding powershell commands can be found at : https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/431#event-2826967563

**Minimum API Version Required**

Min versions for the below two items:
- To update the Proximity Placement Group reference of a resource (VM/AvSet/VMSS) **[2018-04-01]**
- To show colocation status of a Proximity Placement Group. **[2019-07-01]**

**Swagger Link**
Swagger changes are checked in through : 
Azure/azure-rest-api-specs#7745
https://github.com/Azure/azure-rest-api-specs/pull/7745/files

**Target Date**
Proximity Placement Group feature is already in GA

**Comment by haroldrandom** [comment]
@qwordy Please take a look

**Comment by qwordy** [comment]
> 
> 
> @qwordy Please take a look

OK

**Comment by qwordy** [comment]
> To update the Proximity Placement Group reference of a resource (VM/AvSet/VMSS)

PR is merged.

> To show colocation status of a Proximity Placement Group.

Will implement in a separate PR

**Comment by qwordy** [comment]
Azure CLI already has a parameter --include-colocation-status. However, Azure Python SDK is not up-to-date. I have requested an update. Once the new version of SDK is published, we can see colocation status in output. This feature will be available in next release of Azure CLI. Release date: 03/10/2020
