### ISSUE TITLE
Unable to assign user_impersonation permission to an App Registration’s API permissions.

### ISSUE THREAD

**Issue by springcomp** [Azure/azure-cli#11428]
## Description

From the Azure Cloud Shell (using PowerShell) I can successfully create an App Registration using az CLI. However, the following command fails:

**Command Name**
`az ad app permission grant`

**Errors:**
```
Operation failed with status: 'Forbidden'. Details: 403 Client Error: Forbidden for url: https://graph.windows.net/2a35d8fd-574d-48e3-927c-8c398e225a01/oauth2PermissionGrants?api-version=1.6
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad app permission grant --id {} --api {}`

## Expected Behavior

Given the appropriate values for command-line parameters:

- `--id` : the application id to which I want to grant new permissions.
- `--api` : the application id holding the `user_impersonation` permission.

I would expect this command to have the same effect as
- using the `Add permission` button from the Azure Portal,
- selecting the `My APIs` tab, 
- locating the application holding the requested permission,
- checking the `user_impersonation` permission.

![image](https://user-images.githubusercontent.com/8488398/69817601-3e6cc280-11fb-11ea-9e00-17c08b031798.png)

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

```

**Comment by haroldrandom** [comment]
@jiasli Please take a look here

**Comment by jiasli** [comment]
`az ad app permission grant` is for granting permissions on an app for all or one users. For example, to allow the app to access Microsoft Graph API `00000003-0000-0000-c000-000000000000` for `AllPrincipals`:

```
az ad app permission grant --id d8a43c98-4c46-4808-b245-c5c5205d665c --api 00000003-0000-0000-c000-000000000000 --expires 2
```

For an app admin to add permissions to the app as shown in the screenshot, use `az ad app permission add`. For example, to add permission `user_impersonation` from Azure Key Vault to the app

```
az ad app permission add --id d8a43c98-4c46-4808-b245-c5c5205d665c --api cfa8b339-82a2-471a-a3c9-0fc0be7a4093 --api-permissions f53da476-18e3-4152-8e01-aec403e6edc0=Scope
```

As for acquiring the api id for `--api-permissions`, you may use browser's F12 developer tools to capture the network trace when adding permissions from Azure Portal. The captured the network trace will show the required information for command line. 

If you receive 403, that means you don't have permission to invoke [OAuth2PermissionGrant](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/entity-and-complex-type-reference#oauth2permissiongrant-entity) API. Make sure you have corresponding [admin permission](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles) for the action.

**Comment by springcomp** [comment]
Thank you that makes sense.
I will try that on Monday and report back but I'm sure this clears any confusion I had.

**Comment by yonzhan** [comment]
@springcomp please let us know if the issue can be closed.
