### ISSUE TITLE
az rest in AzureChinaCloud fails on missing active_directory_data_lake_resource_id

### ISSUE THREAD

**Issue by stan-sz** [Azure/azure-cli#11424]
**Describe the bug**
`az rest` fails in `AzureChinaCloud` with information about missing endpoint `active_directory_data_lake_resource_id`

**To Reproduce**
```
>az cloud set --name AzureChinaCloud

Switched active cloud to 'AzureChinaCloud'.
Use 'az login' to log in to this cloud.
Use 'az account set' to set the active subscription.

>az rest --method get --uri https://microsoftgraph.chinacloudapi.cn/beta/auditLogs/directoryAudits

The endpoint 'active_directory_data_lake_resource_id' for this cloud is not set but is used.
C:\Users\<username>\.azure\clouds.config may be corrupt or invalid.
Resolve the error or delete this file and try again.  
```
The uri can be anything, it even reproduces with `az rest --method get --uri h`

**Expected behavior**
The `rest` command should not error out on non-related issue. It should execute correctly (if logged on to the cloud) or give an error related to not being logged on. 

**Environment summary**
Install Method: MSI / CLI version 2.0.77 / Win 10 1909 / Shell Type: pwsh

**Additional context**
The same error occurs even if I log on to AzureChinaCloud with `az login`

**Comment by haroldrandom** [comment]
@Juliehzl Please take a look

**Comment by Juliehzl** [comment]
cc @jiasli
