### ISSUE TITLE
container create --unique-keys-policy string-arg example does not work

### ISSUE THREAD

**Issue by pwl-kdk** [Azure/azure-cli#11430]
I tried to used the example string arg to supply a --unique-keys-policy (container create) however it does not work because of syntax errors (Powershell).  A number of variations yielded only cryptic error messages.

Perhaps this and other examples of supplying json-formatted configuration could be updated with usable examples?

Thank you in advance.

Attempts....

Example supplied: "{"uniqueKeys": [{"paths": ["/path/to/key1"]}, {"paths": ["/path/to/key2"]}]}"
Problem: Does not parse

Tried:  '{"uniqueKeys": [{"paths": ["/ordinal"]}]}'
Problem: "Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"

Tried: '"uniqueKeys": [{"paths": ["/ordinal"]}]'
Problem: "Expecting value: line 1 column 1 (char 0)"

Tried:  '"{"uniqueKeys": [{"paths": ["/ordinal"]}]}"'
Problem: "Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e20da33-a85d-abf3-88d4-2c9c6d5c1ad9
* Version Independent ID: ac38600c-6df4-5898-4bd7-fe880eb36819
* Content: [az cosmosdb sql container](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/sql/container?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by shurd** [comment]
Hi @pwl-kdk thank you for opening this issue. Can you try escaping the quotes in the string and surrounding the object with single-quotes? 

For example: -u '{\"uniqueKeys\": [{\"paths\":[\"/path/to/key1\"]}, {\"paths\": [\"/path/to/key2\"]}]}'

**Comment by pwl-kdk** [comment]
Hi @shurd, thanks for your reply.  Doing 2x double quote works.  Maybe the documentation could be updated accordingly?
EG: `--unique-key-policy '{""uniqueKeys"": [{""paths"": [""/ordinal""]}]}'`

**Comment by shurd** [comment]
I just ran the example from the command prompt with CLI 2.0.77 and it worked. It looks like Powershell likely parses input JSON differently. Referencing a JSON file, which is referenced in the 'help' text as a valid option, should work for both terminals. We are going to leave the example as-is for now since the solution you provided would not work in the command line.

```az cosmosdb sql container create -g {rg} -d {database} -a {account} -n {container} -u "{\"uniqueKeys\": [{\"paths\":[\"/id2\"]}]}" -p /id```
