### ISSUE TITLE
[compose] - Webapp create fails with docker-compose.yaml file from Github

### ISSUE THREAD

**Issue by f-r-o-g** [Azure/azure-cli#11434]
## Describe the bug

**Command Name**
`az webapp create`

**Errors:**
```
'str' object has no attribute 'system'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/command_modules/appservice/custom.py, ln 840, in _get_linux_multicontainer_encoded_config_from_file
    response = urlopen(file_name, context=_ssl_context())
cli/command_modules/appservice/custom.py, ln 951, in _ssl_context
    if sys.version_info < (3, 4) or (in_cloud_console() and sys.platform.system() == 'Windows'):
AttributeError: 'str' object has no attribute 'system'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create --name {} --plan {} --resource-group {} --subscription {} --tags {} {} --multicontainer-config-file {} --multicontainer-config-type {}`

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

```

**Comment by panchagnula** [comment]
@patricklee2 can you take a look please?

**Comment by panchagnula** [comment]
@btardif I am assigning this to you so that you can have Patrick or someone from the Linux team take a look at this. Thanks.

**Comment by btardif** [comment]
This is not supported
