### ISSUE TITLE
Azure RedHat OpenShift deployment fails with 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token

### ISSUE THREAD

**Issue by michaelshire** [Azure/azure-cli#11439]
## Describe the bug

**Command Name**
`az openshift create`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az openshift create --resource-group {} --name {} -l {} --aad-client-app-id {} --aad-client-app-secret {} --aad-tenant-id {} --customer-admin-group-id {} --vnet-prefix {} --subnet-prefix {} --tags {} {} {} {} {}`

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

```

**Comment by michaelshire** [comment]
Similar issue:
https://github.com/Azure/azure-cli/issues/11209

**Comment by navba-MSFT** [comment]
@michaelshire Apologies for the late reply. Could you please use the most [recent version of Azure CLI ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and let us know if you still see the issue? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@michaelshire Please let us know if you are still facing this issue. If no further assistance is required on this, can we proceed with closure of this issue? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@michaelshire We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
