### ISSUE TITLE
Could we remove this functional token?

### ISSUE THREAD

**Issue by mmyyrroonn** [Azure/azure-cli#11431]
**Is your feature request related to a problem? Please describe.**
Looks like this token is still valid and we should remove it.

**Comment by haroldrandom** [comment]
add it to S163

**Comment by MyronFanQiu** [comment]
@haroldrandom Please take a look at these two lines https://github.com/Azure/azure-cli/blob/807faccca1009e75e41c663d56b6d3171e630484/CredScanSuppressions.json#L285 and https://github.com/Azure/azure-cli/blob/807faccca1009e75e41c663d56b6d3171e630484/CredScanSuppressions.json#L293

**Comment by haroldrandom** [comment]
I think it should own by service team. The accessToken is used in test_ams_live_event_scenarios.py is hard coded. Should be get online through command. 
Added "Service Attension" for help.

**Comment by yonzhan** [comment]
@fredericky @akucer @yulei, could you please help with above hard coded accessToken issue from Media Services team?

**Comment by haroldrandom** [comment]
Add an example https://github.com/Azure/azure-cli/pull/12589#issuecomment-599158870

**Comment by hivyas** [comment]
The accessToken is used in test_ams_live_event_scenarios.py is actually named poorly because it is a GUID and not an actual security token. I have updated the code to use a generated GUID instead of a hardcoded one in order to avoid confusion: https://github.com/Azure/azure-cli/pull/13948.

The second hardcoded string is found in the container module and AMS does not own that.

**Comment by haroldrandom** [comment]
Add one related issue https://github.com/Azure/azure-cli-dev-tools/issues/215

**Comment by akucer** [comment]
@haroldrandom - I removed the Media Services label and assignment to AMS team members as AMS issue has been fixed. As per previous comment the other hardcoded string is not owned by AMS and needs assignment to appropriate team / owner. Thanks.
