### ISSUE TITLE
Cannot use storage data-plane commands with other clouds

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1143]
Due to a bug in azure-storage (https://github.com/Azure/azure-storage-python/issues/229), using storage data-plane commands with a different cloud will hang/not terminate.

Repro with:
1. Point the CLI to a different cloud.
2. `export AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=<account_name>;AccountKey=<account_key>"`
3. `az storage container list --debug`

The Azure Storage SDK will attempt to connect to <account_name>.blob.core.windows.net instead of using the correct endpoint suffix for the cloud.

When the issue is fixed in the SDK, it can be verified in the CLI.

**Comment by derekbekoe** [comment]
A workaround is to specify `EndpointSuffix` in the connection string.

**Comment by tjprescott** [comment]
The connection string method is a purely CLI convenience method so if we add the EndpointSuffix there, it should solve this problem.
