### ISSUE TITLE
Remove Az acs create requires --location parameter

### ISSUE THREAD

**Issue by sauryadas** [Azure/azure-cli#1144]
@yugangw-msft if user has to create a resource group first, then the location becomes meaningless in the az acs create command. In fact, if a user provides a different location than the one provided during the resource group creation, the create command will fail.

**Comment by yugangw-msft** [comment]
@sauryadas
Interesting, is it by-design that the ACS must be created in the same region of the resource group? I don't think this applies on other services

**Comment by sauryadas** [comment]
@yugangw-msft looks like you can create a resource group in one location and resources in another location. The rationale for thus us that metadata such as RBAC rules, policies, etc can be stored at one central location while you can replicate resources across multiple regions.. So this looks okay to me for now.
