### ISSUE TITLE
Plugging in HaTs survey to Azure CLI

### ISSUE THREAD

**Issue by yonzhan** [Azure/azure-cli#11444]
this survey would be adequate for getting a HaTs baseline score for the Azure CLI. Based on what has worked in the past, I wanted something that has no more than 3 mandatory questions and no more than 10 questions all up. 

https://aka.ms/clihats

Once this is scrubbed, we plan to rollout the same kind of survey for our other command line tools (Azure PowerShell, Azure Terraform provider,  Ansible, etc). 

Can plug in HasTs survey during Bootstrap/reminder me later (never or 3 months).

**Comment by yonzhan** [comment]
Planned in S162.

**Comment by fengzhou-msft** [comment]
We need to figure out the following to implement this feature:
1. Ways to identify user.
2.Where to save users' selected options (reminder me later, never or 3 months), whether the user has already done the survey.
3.Are we targeting all users or selected users?
4. When/How often do we check whether to show the survey?
