### ISSUE TITLE
(query) No az lab create command

### ISSUE THREAD

**Issue by VamsiSangam** [Azure/azure-cli#11449]
Why isn't there an `az lab create` command? Is it scheduled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a8126c7-b3a9-7386-f272-debc5e8ab62f
* Version Independent ID: d9a0e027-9a46-04d3-f20d-1ea4d7dbca1b
* Content: [az lab](https://docs.microsoft.com/en-us/cli/azure/lab?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/lab/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/lab/_help.py)
* Service: **devtest-lab**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
Which version of az do you use? Have tried the latest 2.0.77?

**Comment by yonzhan** [comment]
How is the status of this issue?

**Comment by thisisbrianstewart** [comment]
Hi @yonzhan -- Is there an update on this?  the az lab create command still does not exist, and no info was given on an implementation plan or update.

**Comment by yonzhan** [comment]
lab related commands are owned by lab service team.
