### ISSUE TITLE
Link to run variables documentation

### ISSUE THREAD

**Issue by juhap** [Azure/azure-cli#11446]
The "az acr build" examples use for example "{{.Run.ID}" pattern for variables, but there's no further information about these. Might be good for example to provide a link to the following page:
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-reference-yaml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-build)
* Content Source: [src/azure-cli/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
@northtyphoon Any idea about these related links?

**Comment by northtyphoon** [comment]
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-reference-yaml#run-variables

**Comment by northtyphoon** [comment]
@jaysterp  @dlepow
