### ISSUE TITLE
az resource move ResourceID case issue

### ISSUE THREAD

**Issue by timio73** [Azure/azure-cli#11457]
**Describe the bug**
When trying to move a collection of resources ids with `az resource move --ids $IDs --destination-group $DestinationGroup`, the command fails with the error `All resources should be under the same group` even though all resources /are/ under the same group.

It seems that this occurs when the resource ID collection contains resources where the group is in a different case, eg. ResourceGroup, RESOURCEGROUP.  All of these IDs are gleaned from the `az resource show` command.

Using the Az Powershell module and the portal succeed without issue.  Manually changing the ResourceGroup in the ResourceID to match across the entire collection succeeds.

The difference seems to be localized to disk IDs in this case.

**To Reproduce**
$VM = az vm show --resource-group $SourceResourceGroup --name $VMName --resource-type "Microsoft.Compute/virtualMachines" | convertfrom-json

*Add VMid and OS Disk*

$IDsToMove += ($VM.id , $VM.properties.storageProfile.osDisk.managedDisk.id )

*Add NIC(s)*

($VM.properties.networkProfile.networkInterfaces | ForEach-Object { if ($_.id -match {$IDsToMove += $_.id} )

*Add Data disk(s)*

($VM.properties.storageProfile.dataDisks.managedDisk | ForEach-Object {$IdsToMove += $_.id})

az resource move --destination-group $DestinationGroup --ids $Ids

**Expected behavior**
The resources are all in the same source resource group, so they should move without error with case not being a consideration in the validation.

**Environment summary**
MSI / 2.0.77 / Windows 10 17763 / Powershell Core 6.23 / VS Code 1.40.1

**Additional context**
This may be related to GH Issue #8283
My workaround is to manually create the resource ID to be the same case, which works.

**Comment by haroldrandom** [comment]
@Juliehzl Please take a look

**Comment by zhoxing-ms** [comment]
@timio73 Yes, the question seems to be related to #8283

**Comment by zhoxing-ms** [comment]
Service: [Resources - Move Resources](https://docs.microsoft.com/zh-cn/rest/api/resources/resources/moveresources)
Parameters: {"resources": ["/subscriptions/${subscription-id}/resourceGroups/${original-resourceGroup}/providers/**Microsoft.Compute/virtualMachines**/${resource-name}"], 
"targetResourceGroup": "/subscriptions/${subscription-id}/resourceGroups/${target-resourceGroup}"}

When the above service is called to successfully move a resource to the ${target-resourceGroup}, if the resource type of providers is **Microsoft.Compute/virtualMachines**, after querying this resource [(use get service)](https://docs.microsoft.com/zh-cn/rest/api/resources/resources/get)) will find that ${target-resourceGroup} becomes all uppercase.

**Comment by zhoxing-ms** [comment]
For example: 
When the ${target-resourceGroup} is **"test"**, if we executing the service of **Resources - Move Resources** to move the resource, the id of resource will become /subscriptions/${subscription-id}/resourceGroups/**TEST**/providers/Microsoft.Compute/disks/${resource-name}_diskx_xxx

**Comment by zhoxing-ms** [comment]
@Tiano2017 Please take a look~

**Comment by yonzhan** [comment]
@Tiano2017 any update for this issue?

**Comment by yonzhan** [comment]
@Tiano2017 any update for this issue?

**Comment by Tiano2017** [comment]
@ifeoluwaokunoren to take a look and triage.

**Comment by yonzhan** [comment]
@ifeoluwaokunoren any update for this issue?

**Comment by lmeyerov** [comment]
We're still seeing this, any reason it's closed?

**Comment by lmeyerov** [comment]
In particular, when we create a vm under some rg `abc`, the osDisk is labeled as rg `ABC`, and trying to move all entries of `show -g abc` fails with the mismatch error.

**Comment by zhoxing-ms** [comment]
@ifeoluwaokunoren Hi, could you please take a look and triage it. There are some customers need to solve relevant problems~

**Comment by zhoxing-ms** [comment]
@lmeyerov Hi, this problem does not belong to our team. I have communicated with relevant teams to solve this problem

**Comment by smokedlinq** [comment]
FYI, using the latest api-version (2021-04-01) with the same payload works, if the CLI command gets updated to that then this should just work as intended. For now, I'm using the `az rest` command.

**Comment by navba-MSFT** [comment]
@timio73 Apologies for the late reply. I hope you had a chance to look at the above comment. Could you please let me know if you are still facing this issue ? Awaiting your reply.
