### ISSUE TITLE
Creating tasks for Private Github repositories

### ISSUE THREAD

**Issue by jmeijrink** [Azure/azure-cli#11455]
Hi, the examples only show public Github repo's and private Azure DevOps repos. We're trying to make it work for a private Github repo. Is this supported? The documentation does not specifically say whether it is or is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0e3f3c-5aed-28b6-1e28-22ff32a8521d
* Version Independent ID: 128e5bc6-e518-bd5a-f511-48e0ed185739
* Content: [az acr task](https://docs.microsoft.com/en-us/cli/azure/acr/task?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by northtyphoon** [comment]
It's supported. 
1. Create a qualified github [personal access token](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-build-task#create-a-github-personal-access-token)
2. Pass the above PAT to `--git-access-token`

**Comment by northtyphoon** [comment]
@jaysterp @dlepow

**Comment by jmeijrink** [comment]
Ok, good to know that it should be possible. Unfortunately, I don't get it to work. Please advice. I run the following command:
`az acr task create --registry <ourregistry> --name twinfield-addresses --image <ourregistry>.azurecr.io/twinfield.addresses:{{.Run.ID}} --context https://github.com/Twinfield/Twinfield.git#ARC-P42-6 --file Generic/Addresses/Addresses.Service/Dockerfile --git-access-token <valid PAT token> --platform linux`

Which succeeds, so webhooks are created, with following output:
```json
{
  "agentConfiguration": {
    "cpu": 2
  },
  "creationDate": "2019-11-29T10:54:13.436100+00:00",
  "credentials": null,
  "id": "/subscriptions/<oursubscription>/resourceGroups/<ourresourcegroup>/providers/Microsoft.ContainerRegistry/registries/<ourregistry>/tasks/twinfield-addresses",
  "identity": null,
  "location": "westeurope",
  "name": "twinfield-addresses",
  "platform": {
    "architecture": "amd64",
    "os": "linux",
    "variant": null
  },
  "provisioningState": "Succeeded",
  "resourceGroup": "<ourresourcegroup>",
  "status": "Enabled",
  "step": {
    "arguments": [],
    "baseImageDependencies": null,
    "contextAccessToken": null,
    "contextPath": "https://github.com/Twinfield/Twinfield.git#ARC-P42-6",
    "dockerFilePath": "Generic/Addresses/Addresses.Service/Dockerfile",
    "imageNames": [
      "<ourregistry>.azurecr.io/twinfield.addresses:{{.Run.ID}}"
    ],
    "isPushEnabled": true,
    "noCache": false,
    "target": null,
    "type": "Docker"
  },
  "tags": null,
  "timeout": 3600,
  "trigger": {
    "baseImageTrigger": {
      "baseImageTriggerType": "Runtime",
      "name": "defaultBaseimageTriggerName",
      "status": "Enabled",
      "updateTriggerEndpoint": null,
      "updateTriggerPayloadType": "Default"
    },
    "sourceTriggers": [
      {
        "name": "defaultSourceTriggerName",
        "sourceRepository": {
          "branch": "ARC-P42-6",
          "repositoryUrl": "https://github.com/Twinfield/Twinfield.git#ARC-P42-6",
          "sourceControlAuthProperties": null,
          "sourceControlType": "Github"
        },
        "sourceTriggerEvents": [
          "commit"
        ],
        "status": "Enabled"
      }
    ],
    "timerTriggers": null
  },
  "type": "Microsoft.ContainerRegistry/registries/tasks"
}
```
Things that make us wonder:
- contextAccessToken and sourceControlAuthProperties are null, while I also would not have expected the actual access token to be shown, it is also strange it shows as null

When we then run: `az acr task run --registry <ourregistry> --name twinfield-addresses`
The output is as follows:
```
Queued a run with ID: cbh
Waiting for an agent...
2019/12/02 19:05:33 Downloading source code...
Run ID: cbh failed after 12s. Error: failed to download context. Please check if the URL is incorrect. If it has credentials, please check if they are expired
```

The PAT has the following permissions assigned:
- repo Full control of private repositories
  - repo:status Access commit status
  - repo_deployment Access deployment status
  - public_repo Access public repositories
  - repo:invite Access repository invitations
- admin:repo_hook Full control of repository hooks
  - write:repo_hook Write repository hooks
  - read:repo_hook Read repository hooks
- admin:org_hook Full control of organization hooks

We found somewhere in closed questions underneath one of the documentation pages (which I could try to find later if you're interested) that the hook rights were necessary for private repositories.

@northtyphoon @jaysterp @dlepow

**Comment by northtyphoon** [comment]
@jmeijrink it looks your repository includes submodules. We are deploying a fix to support private git repo with submodule. I will let you know once we finish the deployment.

**Comment by northtyphoon** [comment]
@jmeijrink can you try rerun the task to see if it works?

**Comment by jmeijrink** [comment]
Hi @northtyphoon, I tried it again. Unfortunately I still get the same error. I could share output of the command running with --debug, but am not sure whether it will contain any sensitive keys.

**Comment by northtyphoon** [comment]
@jmeijrink can you send your .gitmodules file to acrsup@microsoft.com? We can continue the investigation there.

**Comment by itpropro** [comment]
If anyone finds this issue and has a problem with `Error: failed to download context. Please check if the URL is incorrect.` note that GitHub's default branch is `main` and ACR tries to pull from `master`, if nothing else is specified. I saw this problem a few times already, just add `#main` to the end of your repository url. This will probably not help the issue author, but other people, who are coming across this.

**Comment by SQLHorizons** [comment]
@itpropro thank you, that helped. Especially when you have applied the same branch name policy to ADO

**Comment by navba-MSFT** [comment]
@jmeijrink Apologies for the late reply. Could you please let us know if you are still facing this issue ? This issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by ramgopal24** [comment]
> If anyone finds this issue and has a problem with `Error: failed to download context. Please check if the URL is incorrect.` note that GitHub's default branch is `main` and ACR tries to pull from `master`, if nothing else is specified. I saw this problem a few times already, just add `#main` to the end of your repository url. This will probably not help the issue author, but other people, who are coming across this.
---------
Thanks #main was what I was missing !!!

**Comment by anan235** [comment]
We've also been facing this issue for the last few days. We've Tried changing credentials with new ones, Tenant ID, and upgrading/downgrading the Azure CLI version but nothing seems to be working. 

Any idea what could be happening?


<img width="1050" alt="image" src="https://user-images.githubusercontent.com/5264656/224496164-ba10da55-5f5f-4a30-9f41-a002f564d1d0.png">

**Comment by dasmochael** [comment]
Have the same issue - was there a resolution given to the author?
