### ISSUE TITLE
[CI] Should support tests run in Windows platform

### ISSUE THREAD

**Issue by haroldrandom** [Azure/azure-cli#11450]
**Is your feature request related to a problem? Please describe.**
Some tests should be test on Windows platform or netural platform:
- Automation test
- Integration test
- Test agains profiles.

Currently, just on ubuntu:
https://github.com/Azure/azure-cli/blob/807faccca1009e75e41c663d56b6d3171e630484/azure-pipelines.yml#L389-L395
https://github.com/Azure/azure-cli/blob/807faccca1009e75e41c663d56b6d3171e630484/azure-pipelines.yml#L416-L421

**Describe the solution you'd like**
Add Job written in PowerShell/*.bat or pure python scripts.

**Describe alternatives you've considered**
We can leverage azdev capability.

**Additional context**
None

**Comment by yonzhan** [comment]
add to S163.

**Comment by haroldrandom** [comment]
Closed as low priority for now.
