### ISSUE TITLE
az ad sp credential reset doesn't reset service principal credential, resets app credential

### ISSUE THREAD

**Issue by mikeliddle** [Azure/azure-cli#11458]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
We have a multi-tenant app registration defined in Azure. We create a service principal in a *separate tenant* for that app, but when we try to provide a credential using the `az ad sp credential reset` command it tries to look up the app resource and can't find it in the tenant (because it isn't there). Why doesn't it look up the service principal resource like the corresponding [powershell command?](https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azadspcredential?view=azps-3.1.0)

**To Reproduce**
```
> az ad sp create --id <app_id>
> az ad sp credential reset -n <app_id> --append
Resource '<app_id>' does not exist or one of its queried reference-property objects are not present.
```

**Expected behavior**
Similar behavior to the powershell command provided, the service principal should receive a new credential, which will be returned by the command, or provided by the user using the --password parameter.

**Environment summary**
cmd.exe on windows 
```
> az --version
azure-cli                         2.0.75 *

command-modules-nspkg              2.0.3
core                              2.0.75 *
nspkg                              3.0.4
telemetry                          1.0.4
```

**Additional context**
The documentation clearly states that this command operates the same as az ad app credential, but the reset command says it resets the service principal's credential. Is there actually a way to reset the service principal's credentials using azure cli?

**Comment by haroldrandom** [comment]
@jiasli Please help here

**Comment by jiasli** [comment]
We need to discuss with Azure CLI PM and AAD team whether this behavior needs to be changed.

**Comment by jiasli** [comment]
`az ad sp credential reset` and `az ad app credential reset`'s functionality will be split in https://github.com/Azure/azure-cli/issues/12946.

**Comment by Icybiubiubiu** [comment]
Dear Team~
More and more services were impacted by this az ad sp issue. Like SP based AKS, if the credential is expired, customer need to reset SP suggested by this Doc: 
https://docs.microsoft.com/en-us/azure/aks/update-credentials#update-aks-cluster-with-new-service-principal-credentials

then the result is to reset app credential instead of sp's credential.

Please help to fix this az ad sp issue at your earliest convenience.

**Comment by jiasli** [comment]
This is already changed in the beta version which uses Microsoft Graph. 😊 Please see https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration?tabs=powershell.
