### ISSUE TITLE
Why was `--template-file-path` and `--parameters-file-path` changed?

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1146]

**Comment by colemickens** [comment]
```
    --parameters                  : Provide deployment parameter values, either json string, or use                                                                                                                                                 '@<file path>' to load from a file.
```

seems very unintuitive to me. Why can't it just take `--parameters-file`?

I much preferred the way it was before this change.

**Comment by tjprescott** [comment]
You can still provide a parameters file using the @ notation. So if you wanted to use the file, you would specify --parameters @myfile.json. In general, we are trying to eliminate redundant options that were present in Xplat, which might have for example --parameters and --parameters-file (not saying it does, but I have seen that pattern used).

Unless we need to do additional processing on the file (for example say a PEM file), especially if it is simply a JSON config file, we are moving to make the @ syntax the standard way of invoking this across the CLI.

**Comment by colemickens** [comment]
Okay, I see. Out of curiosity, was this pattern adopted from another CLI? It's an interesting convention.

**Comment by tjprescott** [comment]
@johanste would be the authority on this. That's his baby 😄

**Comment by johanste** [comment]
It is a slight twist on argparse's fromfile functionality: https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars

**Comment by colemickens** [comment]
Nice; thanks for the link. Closing this out.
