### ISSUE TITLE
AzureFirewall with IpGroups

### ISSUE THREAD

**Issue by ssripadham** [Azure/azure-cli#11462]
### **Resource Provider**
 Microsoft.Network

### Description of Feature or Work Requested
 
We are building a facility in Azure Networking that will allow Azure customers to group of Ip Address prefixes to define rules in Azure Networking. This will help customers manage & minimize the overall complexity for security rules creation.  
 
Customer will create an IpGroups (new top-level resource) and specify a set of IP addresses to include within the tag. These tags will then be used by existing resources as Azure Firewall.  

### AzureFirewall Changes
Azure Firewall will  support IpGroups can be used in the network/application/dnat rules as described below. 

- As a source or destination address in AZFW network rules 
- As a source address in AZFW application rules 
- As a source address in DNAT rules. 

Need support for following 2 things:

**1. Azure Firewall Application Rules**

         "AzureFirewallApplicationRule": {
             "properties": {
               "name": {
                 "type": "string",
                 "description": "Name of the application rule."
               },
               "description": {
                 "type": "string",
                 "description": "Description of the rule."
               },
               ...
               "sourceIpGroups": {
                 "type": "array",
                 "description": "List of source IP Groups for this rule.",
                 "items": {
                   "type": "string"
                 }
               },
           ...
         }
        }

**2. Azure Firewall  NAT Rules**

       "AzureFirewallNatRule": {
             "properties": {
               "name": {
                 "type": "string",
                 "description": "Name of the NAT rule."
               },
               "description": {
                 "type": "string",
                 "description": "Description of the rule."
               },
              ...

        "sourceIpGroups": {
          "type": "array",
          "description": "List of source IP Groups for this rule.",
          "items": {
            "type": "string"
          }
        }
           …
       }
       }

**3. Azure Firewall  Network Rules**

        "AzureFirewallNetworkRule": {
             "properties": {
               "name": {
                 "type": "string",
                 "description": "Name of the network rule."
               },
               "description": {
                 "type": "string",
                 "description": "Description of the rule."
               },
              ...
               "sourceIpGroups": {
                 "type": "array",
                 "description": "List of source IP Groups for this rule.",
                 "items": {
                   "type": "string"
                 }
               },
               "destinationIpGroups": {
                 "type": "array",
                 "description": "List of destination IP Groups for this rule.",
                 "items": {
                   "type": "string"
                 }
               },
           ...
        }
       }

### **Minimum API Version Required**
2019-09-01

**Swagger Link**

The Swagger Changes will be in ![image](https://user-images.githubusercontent.com/4796246/66084365-52f64c80-e523-11e9-8445-be68746e712b.png)

**Swagger from reviewed branch:**

[Azure Firewall Swagger](https://github.com/ssripadham/azure-rest-api-specs/blob/2f3e41d17b95cc051a9dd42402496dbf789cee45/specification/network/resource-manager/Microsoft.Network/stable/2019-07-01/azureFirewall.json)

### Target Date

This is Public preview feature for 12/31/2019

**Comment by MyronFanQiu** [comment]
@ssripadham Let me check the current status and update with you later.

**Comment by ssripadham** [comment]
Please update

**Comment by MyronFanQiu** [comment]
@ssripadham Sorry for the delay. I remembered that we saw these swaggers before. Well, I just checked the current status and cannot find the feature. It's planned in S163. Thanks.

**Comment by ssripadham** [comment]
When does S163 ship? Where can I find CLI timelines

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/milestones

**Comment by ssripadham** [comment]
Please contact Jiejiong.Wu@microsoft.com with any question
