### ISSUE TITLE
delete-batch is throwing `permission denied` error

### ISSUE THREAD

**Issue by kumarks1122** [Azure/azure-cli#11473]
## Describe the bug

**Command Name**
`az storage blob delete-batch`

**Errors:**
```
az: error: unrecognized arguments: -dryrun
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob delete-batch --source {} --connection-string {} --pattern {} -d{}`

## Environment Summary
```
Darwin-19.0.0-x86_64-i386-64bit
Python 3.7.5
Shell: bash

azure-cli 2.0.76 *

```

**Comment by haroldrandom** [comment]
@ZhouXing244266602 Please take a look

**Comment by kumarks1122** [comment]
@haroldrandom @ZhouXing244266602 I found out the issue. This was because I have used `-dryrun` instead of `--dryrun`. Thanks for the response.
