### ISSUE TITLE
what is location used for

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [Azure/azure-cli#11477]
Could you clarify what the location params is used for? The documentation does not really tell this information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c6760bb-c278-da56-a95c-4e82e221f1e8
* Version Independent ID: e25cbd2a-b415-214f-7d50-c403992c9361
* Content: [az policy assignment](https://docs.microsoft.com/en-us/cli/azure/policy/assignment?view=azure-cli-latest#az-policy-assignment-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
@Juliehzl Please have a look

**Comment by zhoxing-ms** [comment]
@CharmanderJieniJieni I don't see that the command related to `az policy assignment` has the parameter `--location\-l`, may I ask you 2 questions?
1. Does this location refer to `allowedLocations` in the `--params\-p` parameter of the `az policy assignment create` command?
2. Which version of azure-cli do you use?

**Comment by CharmanderJieniJieni** [comment]
Hi, this is for az policy assignment create, there is a --location params.

**Comment by zhoxing-ms** [comment]
@CharmanderJieniJieni Which version of azure-cli do you use? I see that the latest version of azure-cli no longer has this parameter.

**Comment by zhoxing-ms** [comment]
@CharmanderJieniJieni Its function is: The location of the policy assignment. Only required when utilizing managed identity. 
I'll add this description to help, do you have any other questions?

**Comment by CharmanderJieniJieni** [comment]
Good on my side, please update this doc and remove [--location]

**Comment by zhoxing-ms** [comment]
@CharmanderJieniJieni I will update the document with the parameter description, but the `-- location` parameter will not be deleted because it works when utilizing managed identity.

**Comment by yonzhan** [comment]
fixed by the PR.
