### ISSUE TITLE
How to use the update command to update the name of a Host?

### ISSUE THREAD

**Issue by OzBob** [Azure/azure-cli#11479]
Can this command be used to update the name of a App Service Plan?
e.g.
az appservice plan update --ids "{id}" --name "newname"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f99cdf3a-4fd3-e949-aabe-1b26fe828444
* Version Independent ID: 1c2e7517-1275-9e30-db67-393c0451055f
* Content: [az appservice plan](https://docs.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest&source=docs#az-appservice-plan-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/appservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/_help.py)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by OzBob** [comment]
also posted to SO: https://stackoverflow.com/questions/59188644/how-to-update-the-name-of-a-app-service-plan-using-azure-portal-or-cli

**Comment by OzBob** [comment]
What would be also awesome. Is that if the Docs were to include how to

CHANGE app Service plan for a WebApp, 

then it would work around a bug in the Azure Portal.

**Comment by panchagnula** [comment]
there is no way to rename & existing resource. Thanks.
