### ISSUE TITLE
Error when creating an aks cluster and passing a public key

### ISSUE THREAD

**Issue by ricardolupo** [Azure/azure-cli#11478]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
invalid literal for int() with base 10: '100G'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 306, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 487, in default_command_handler
    return op(**command_args)
cli/command_modules/acs/custom.py, ln 1672, in aks_create
    agent_pool_profile.os_disk_size_gb = int(node_osdisk_size)
ValueError: invalid literal for int() with base 10: '100G'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --ssh-key-value {} --location {} --admin-username {} --node-vm-size {} --node-osdisk-size {}`

## Environment Summary
```
Darwin-19.0.0-x86_64-i386-64bit
Python 3.7.5
Shell: bash

azure-cli 2.0.77

```

**Comment by palma21** [comment]
That does not look like anything related to public key.

The error states invalid literal for int() with base 10: '100G'

Please use 100 integer value

**Comment by jluk** [comment]
Closing as the error is found within the input provided for os disk size is expecting an int.
