### ISSUE TITLE
az acs create --dns-name-prefix longer than necessary

### ISSUE THREAD

**Issue by SteveLasker** [Azure/azure-cli#1147]
To minimize the words required to type, while still making sure customers can understand the meaning, dns-name-prefix should be shortened as name is overly redundant.

Change `dns-name-prefix` to `dns-prefix`

**Comment by sauryadas** [comment]
@yugangw-msft Can we please have a single letter flag like we have for name (-n) and resource group(-g) ?

**Comment by SteveLasker** [comment]
Single letter would be nice. But do we need name in the parameter name?

**Comment by sauryadas** [comment]
@SteveLasker yes i meant a single letter in addition to the removal of the "name" in the dns-name-prefix

**Comment by yugangw-msft** [comment]
I will add `-d`

**Comment by SteveLasker** [comment]
@yugangw-msft can you confirm changing the parameter name, to `dns-prefix` as well?

**Comment by yugangw-msft** [comment]
I can confirm.
