### ISSUE TITLE
az acs list should list all acs instances with resource group as an optional value

### ISSUE THREAD

**Issue by SteveLasker** [Azure/azure-cli#1148]
In most cases customers will place ACS instances in its own resource group as each acs instance creates a lot of resources. 
Yes, they can put multiples in one rg, However, having to add yet another parameter to get the norm feels overly complex. I can't speak for VM, vmss but I'd suggest we go the opposite standard. If I call az VM list, the default behavior is to list them all, and if I want a specific rg I pass it in as rg is a standard parameter. 

From @rgardler 
+1

I do not want acs commands to have to conform to a model designed for VMs. ACS is about managing containers, not VMS. Our users should not need to worry about the underlying Azure concepts such as resource group, VMSS, VM, NSG, LB etc. etc. Our job is to abstract away from these as much as possible.

Today ACS is only an IaaS service. We will always see customers using it as IaaS and enjoying the flexibility this brings, but at the same time we will be moving more and more towards a managed service and we should, wherever possible, define the CLI tools to account for this.

**Comment by yugangw-msft** [comment]
#1141 was opened already for this.
