### ISSUE TITLE
`az acr create`: Update 'sku' parameter description to remove 'Classic' as allowed value

### ISSUE THREAD

**Issue by dlepow** [Azure/azure-cli#11487]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
`sku` parameter description in `az acr create` lists `Classic` as an allowed value but `Classic` SKU is now deprecated and unsupported.

**To Reproduce**

`az acr create` help text shows:
`  --sku               [Required] : The SKU of the container registry.  Allowed values: Basic,
                                     Classic, Premium, Standard.`

Run:

`az acr create -n myregistry -g mygroup --sku Classic` returns

`Classic SKU is no longer supported. Please select a managed SKU.`

**Expected behavior**
No mention of `Classic` as allowed SKU value: 
`--sku               [Required] : The SKU of the container registry.  Allowed values: Basic, Premium, Standard.`

**Environment summary**
CloudShell, CLI v.  2.0.77

**Additional context**

**Comment by yugangw-msft** [comment]
should fix for this release

**Comment by ReddyMalathi** [comment]
Hi ... 

I also faced the same issue . I created ACR using Azure portal with Basic SKU it worked... Hope this helps...

**Comment by dlepow** [comment]
Closing - no action
