### ISSUE TITLE
[CI] Incomplete usage of test_help_doc_arguments.py which has bug

### ISSUE THREAD

**Issue by haroldrandom** [Azure/azure-cli#11495]
**Describe the bug**
According to this:
https://github.com/Azure/azure-cli/blob/863083aee43f96793ad10918487d47cfd45b8a2a/scripts/ci/test_ref_doc.sh#L22

This line, test_commands will always be default_commands
https://github.com/Azure/azure-cli/blob/863083aee43f96793ad10918487d47cfd45b8a2a/scripts/ci/test_help_doc_arguments.py#L115

So this job in CI just worked for a small part of commands.

It will failed. So this script and **test_ref_doc.sh** is not functional as its name

**To Reproduce**
None

**Expected behavior**
Should run against all files instead.

**Environment summary**
No restriction

**Additional context**
None

**Comment by yonzhan** [comment]
add to S163.

**Comment by haroldrandom** [comment]
Closed as unnecessary. It's false alarm, maybe by designed.
