### ISSUE TITLE
Create a static HTML web app in Azure tutorial error

### ISSUE THREAD

**Issue by holumyn** [Azure/azure-cli#11493]
**Description**
I got the error message `Could not auto-detect the runtime stack of your app, see 'https://go.microsoft.com/fwlink/?linkid=2109470' for more information` when i ran the command `az webapp up --location westeurope --name myapp-landing-page` as described in the doc https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-html

**To Reproduce**
Steps to reproduce the behavior.
Start cloud shell when logged in to your azure account
mkdir quickstart
cd $HOME/quickstart
git clone https://github.com/Azure-Samples/html-docs-hello-world.git
cd html-docs-hello-world
az webapp up --location westeurope --name myapp-landing-page

**Expected behavior**
App should be created

**Comment by ammanifold** [comment]
Related to: #11592

**Comment by panchagnula** [comment]
Closing this since this is tracked by the primary to track the work #11592
