### ISSUE TITLE
Create commands need parameter renaming

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#115]
BUG: we are waiting on autorest to support this rename (https://github.com/Azure/autorest/issues/941)

Once this is fixed, we need to remove the parameter aliasing from the Create commands (search for the autorest URL in code)

**Comment by tjprescott** [comment]
@BurtBiel can this be closed?

**Comment by BurtBiel** [comment]
yes, this is fixed and we are using the new functionality
