### ISSUE TITLE
is --os-family 6 option supported?

### ISSUE THREAD

**Issue by eltoncarr** [Azure/azure-cli#11506]
For az batch pool create --os-family , the documentation shows that accepted values are: {2, 3, 4, 5}. Meanwhile, the documentation describes --os-family 6 as " 6 - OS Family 6, equivalent to Windows Server 2019". If option 6 is available, you may want to add it to the acceptable values or remove the option since if it is not available. As it stands, the doc creates a bit of confusion on support for option 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 065a1d73-5ead-81c2-8b7b-5405c2a112b1
* Version Independent ID: fbae9a55-b731-ed86-ff6a-22c1a97d4e53
* Content: [az batch pool](https://docs.microsoft.com/en-us/cli/azure/batch/pool?view=azure-cli-latest#az-batch-pool-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/batch/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/batch/_help.py)
* Service: **batch**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bgklein** [comment]
This help text must have been missed when the CLI was updated. I'll go ahead and send a PR to add family 6

**Comment by bgklein** [comment]
Fixed in #11537
