### ISSUE TITLE
Question: Use Host header from RequestHeaders

### ISSUE THREAD

**Issue by stmaute** [Azure/azure-cli#11511]
I want to create a custom rule which checks if the Host header is set to a specific hostname. How can this be done via cli?
I can use '--match-label RequestHeaders'. But how do I specify the selector 'Host' via cli?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eae3c03c-db11-6d8e-a701-ef1a95e588db
* Version Independent ID: 5be6d86e-5ed1-fd02-eaaa-6e54bd2d7b44
* Content: [az network application-gateway waf-policy custom-rule match-condition](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/waf-policy/custom-rule/match-condition?view=azure-cli-latest#az-network-application-gateway-waf-policy-custom-rule-match-condition-add)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
Please take a look, https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/custom-waf-rules-overview

Currently, variable **RemoteAddr** should take the place of your demand.
![image](https://user-images.githubusercontent.com/14357159/70434512-5b3cac00-1abf-11ea-8c35-b054a9978b5e.png)

**Comment by haroldrandom** [comment]
Or maybe I could filter **Host** from **RequestHeaders** using RegEx?

**Comment by stmaute** [comment]
@haroldrandom Thanks for the tip. I will give it a try.

**Comment by haroldrandom** [comment]
@stmaute Can it work?

**Comment by haroldrandom** [comment]
And another workaround for this is we can grab "Host:" via RegEx since currently there is no specific variable stands for **Host**.

**Comment by stmaute** [comment]
@haroldrandom I didn't have time to test the workaround. Actually I create the WAF policy in the console and export the template which is working fine for me. 
Thanks for your support.

**Comment by haroldrandom** [comment]
Feel free to reopen if any further question. :)
