### ISSUE TITLE
az group create --tag behaviour

### ISSUE THREAD

**Issue by leyshon** [Azure/azure-cli#11513]
**Describe the bug**
If you execute `az group create -n my-test-rg -l northeurope` against a resource group which already has tags, then the tags are cleared.

**To Reproduce**
`az group create -n my-test-rg -l northeurope --tags test_tag` 
See that the group is created with the tag
`az group create -n my-test-rg -l northeurope`
See that the group has its tag removed

**Expected behavior**
The tag test_tag remains in place after the second command

**Additional context**
The documentation found here (https://docs.microsoft.com/en-us/cli/azure/group?view=azure-cli-latest#az-group-create) says 
```
--tags 
Space-separated tags in 'key[=value]' format. Use "" to clear existing tags.
```
I read this as the tags are unset if you explicitly set them to blank, not when they are undefined. 
It may just be that it should be made clearer that not including the --tags parameter has the same effect as setting them to "".

**Comment by haroldrandom** [comment]
@Juliehzl Please have a look

**Comment by yonzhan** [comment]
add to S164.

**Comment by zhoxing-ms** [comment]
@leyshon That's how it was designed. The `create` operation usually corresponds to the `PUT` operation of the restful API by server-side. It will maintain the idempotence of the interface, so when you create an existing resource, the new resource will directly overwrite the original resource.
doc link: [click](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#standard-command-types)

If you just want to modify some properties of a resource, the `update` operation is recommended.

**Comment by zhoxing-ms** [comment]
@leyshon Do you have any other questions?
