### ISSUE TITLE
az webapp config ssl upload: name argument seems unnecessary

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-cli#11515]
An uploaded certificate is available to all apps in the specified resource group, so the requirement to specify an app name or resources ID(s) seems irrelevant. (The HTTP request to upload the cert doesn't even use the app name, although it won't allow you to upload with a nonexistent name.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3f984d-0d48-e075-7e2f-2da5667b15cf
* Version Independent ID: 98e06d47-0ed4-4d8e-ccf5-d3a78e510539
* Content: [az webapp config ssl](https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest#az-webapp-config-ssl-upload)
* Content Source: [latest/docs-ref-autogen/webapp/config/ssl.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/ssl.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
Thanks for the feedback. We are working on improving these commands, & will take this into consideration. However, currently there are no plans to update the existing one. @madsd FYI
