### ISSUE TITLE
[Breadth Coverage] Onboard Data Factory Commands

### ISSUE THREAD

**Issue by arrownj** [Azure/azure-cli#11527]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
collaborate with autogen team to generate data factory extension code base automatically.

Input swagger files are located [here](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/datafactory/resource-manager).

The tool being used is [here](https://github.com/Azure/autorest.cli)

**Describe alternatives you've considered**
No

**Additional context**
autogen team will do the code generation work. We need provide the e2e tests for azure cli extension(also generated from swagger files). Also we need to verify the extensions can work well from user's perspective.

**Comment by haroldrandom** [comment]
https://github.com/Azure/azure-cli-extensions/pull/1142 on going

**Comment by yungezz** [comment]
move it to backlog since no release plan so far. will put it back after talking with @RodgeFu ' s team when ready to release.

**Comment by shawnxzq** [comment]
@RodgeFu Shall close this since we already have the autogen for now? Thanks!

**Comment by RodgeFu** [comment]
DataFactory CLI has been released. @yungezz , @yonzhan , I think you can close this one. thanks.
