### ISSUE TITLE
[Breadth Coverage] Onboard NotificationHubs Commands

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-cli#11524]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Onboard NotificationHubs, the spec is [here](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/notificationhubs/resource-manager).

**Describe alternatives you've considered**

**Additional context**
Use [autorest.cli](https://github.com/Azure/autorest.cli) to auto-generate the code.

**Comment by haroldrandom** [comment]
Plan S163?

**Comment by fengzhou-msft** [comment]
in S164.

**Comment by fengzhou-msft** [comment]
extension released, can be installed by `az extension add -n notification-hub`.
