### ISSUE TITLE
secret name not displayed

### ISSUE THREAD

**Issue by avbhaskar** [Azure/azure-cli#11538]
[Enter feedback here]
Powershell Command "Get-AzKeyVaultSecret -VaultName 'Contoso'" lists secret name where as CLI Comamnd "az keyvault secret list  --vault-name Contoso " does not list name.  Listing name of secret is super helpful for devOps pipleline automation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39cfb8ed-c246-2ffb-9dff-070b90c18b21
* Version Independent ID: c09c1597-1b6c-b0a2-b3fc-bdc16764d096
* Content: [az keyvault secret](https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az-keyvault-secret-show)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
@bim-msft Please take a look

**Comment by bim-msft** [comment]
This was supported, release date: Mar 31
