### ISSUE TITLE
Vmaas Extension List not working

### ISSUE THREAD

**Issue by kotharij** [Azure/azure-cli#11533]
ubuntu@ubuntu$ az vmss  extension list --resource-group coke-b375c-tms-loc_gateway --vmss-name vmscaleset --subscription &lt;...&gt;
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'extension_profile'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 487, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 2645, in list_vmss_extensions
    return None if not vmss.virtual_machine_profile.extension_profile \
AttributeError: 'NoneType' object has no attribute 'extension_profile'

To open an issue, please run: 'az feedback'

ubuntu@ubuntu$ az vmss list
[
  {
    "additionalCapabilities": null,
    "automaticRepairsPolicy": null,
    "doNotRunExtensionsOnOverprovisionedVms": null,
    "id": "/subscriptions/&lt;...&gt;/resourceGroups/COKE-B375C-TMS-LOC_GATEWAY/providers/Microsoft.Compute/virtualMachineScaleSets/vmscaleset",
    "identity": null,
    "location": "eastus",
    "name": "vmscaleset",
    "overprovision": null,
    "plan": null,
    "platformFaultDomainCount": 5,
    "provisioningState": "Succeeded",
    "proximityPlacementGroup": null,
    "resourceGroup": "COKE-B375C-TMS-LOC_GATEWAY",
    "scaleInPolicy": null,
    "singlePlacementGroup": true,
    "sku": null,
    "tags": null,
    "type": "Microsoft.Compute/virtualMachineScaleSets",
    "uniqueId": "a2655ed3-cdb3-4f6c-99bd-886830654263",
    "upgradePolicy": null,
    "virtualMachineProfile": null,
    "zoneBalance": null,
    "zones": [
      "2"
    ]
  }
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29233b11-4e55-8560-9dad-43ac44b818c2
* Version Independent ID: b60ca5ef-f607-80b6-c641-0278cd8bdc61
* Content: [az vmss extension](https://docs.microsoft.com/en-us/cli/azure/vmss/extension?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
@qwordy Please take a look

**Comment by qwordy** [comment]
Could you share the complete commands? What extension are you using? How do you create the vmss and set the extension? Thanks.

**Comment by yungezz** [comment]
HI @kotharij could you pls share more context on your vmss extensions setup? we did a fix to avoid NoneType exception but show empty to indicate no extension. Need your input on the specific case to figure out why no extension found. thanks.

**Comment by qwordy** [comment]
Close the issue for now. The fix will be available in the next version of Azure CLI. It will be released on 03/10/2020.

**Comment by yungezz** [comment]
@kotharij feel free to open a new issue when you see extension listed is not matching expectation with reproduce steps, especially extension setup detail. thanks.
