### ISSUE TITLE
Azure Role create with the following error

### ISSUE THREAD

**Issue by jbnetapp** [Azure/azure-cli#11536]
## Describe the bug

**Command Name**
`az role definition create`

**Errors:**
```
Refuse str type as a valid iter type.
Traceback (most recent call last):
pip-install-mjd5h3hf\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 654, in _run_job
Temp\pip-install-mjd5h3hf\six\six.py, ln 696, in reraise
cli\core\commands\__init__.py, ln 631, in _run_job
cli\core\commands\__init__.py, ln 306, in __call__
...
pip-install-mjd5h3hf\msrest\msrest\serialization.py, ln 481, in _serialize
pip-install-mjd5h3hf\msrest\msrest\serialization.py, ln 707, in serialize_data
pip-install-mjd5h3hf\msrest\msrest\serialization.py, ln 778, in serialize_iter
msrest.exceptions.SerializationError: Refuse str type as a valid iter type.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role definition create --role-definition {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.77

```

**Comment by haroldrandom** [comment]
@jiasli Please take a look.

**Comment by arrownj** [comment]
Hi @jbnetapp , thanks for reporting. Could you please share more about your command ? It seems that the value type you used is not right. 

Please kindly be noted that the --role-definition value should be a valid json string or file path to a file containing valid json string.

You can use `az role definition create -h` to get help about how to use this command. You can also get some example at the end of this help message.

**Comment by arrownj** [comment]
Hi @jbnetapp , if there are no more problems, I will close this issue first. If you have other problems about this, you can reopen it or submit a new one. Thanks
