### ISSUE TITLE
acs: list and show with table option shows same output 

### ISSUE THREAD

**Issue by sauryadas** [Azure/azure-cli#1153]
@yuganagw-msft Show should display agent count, master count, orchestrator, public ssh key, resource group, location , dns-prefix, Master and agent FQDN's, vm size

<img width="582" alt="screen shot 2016-10-24 at 11 36 40 pm" src="https://cloud.githubusercontent.com/assets/15387759/19675378/d7ee9a66-9a42-11e6-973a-6f659b538ec8.png">

**Comment by yugangw-msft** [comment]
@sauryadas
For table, that is too many fields to fit in one line.
How about you try out yourself using query expression such as `--query "{name:name, masterAccount:masterProfile.count}"`, when are satisfied with the display, let me know the fields list

**Comment by brendandburns** [comment]
Can we close this, I'm doing some of this work here:

https://github.com/Azure/azure-cli/pull/1641

@sauryadas please comment on that PR for the set of fields you'd like to see.

**Comment by sauryadas** [comment]
closing will be fixed as a part of #1641
