### ISSUE TITLE
az cosmosdb throws exception trying to show throughput value

### ISSUE THREAD

**Issue by vinnytheviking** [Azure/azure-cli#11532]
## Describe the bug

**Command Name**
`az cosmosdb mongodb database throughput show`

**Errors:**
```
Operation failed with status: 'NotFound'. Details: Entity with the specified id does not exist in the system.

ActivityId: 27fcdbe6-1b33-11ea-8a50-00155d72bc93, Microsoft.Azure.Documents.Common/2.7.0
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cosmosdb mongodb database throughput show -g {} -a {} -n {}`

## Expected Behavior

Show throughput value

## Environment Summary
```
Windows-10-10.0.19035-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.76 *

Extensions:
azure-devops 0.15.0

```

**Comment by shurd** [comment]
Hi @vinnytheviking thank you for opening this issue. It appears from the command that you are trying to get the offer at a database level. Is this a shared throughput database? If not, then there will be no offer at the database level. Try getting the throughput at the collection level.

`az cosmosdb mongodb collection throughput show -g {} -a {} -d {} -n {}`

**Comment by shurd** [comment]
I am going to close this issue for now. Please open another issue if the problem persists and my previous comment did not solve the problem.
