### ISSUE TITLE
webapp config container set fail after network reset

### ISSUE THREAD

**Issue by gerhardcit** [Azure/azure-cli#11549]
## Describe the bug
Command fails during network outage. Cannot run if again.

**Command Name**
`az webapp config container set`

**Errors:**
```
'NoneType' object has no attribute 'reserved'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/appservice/custom.py, ln 1049, in update_container_settings
    _add_fx_version(cmd, resource_group_name, name, docker_custom_image_name, slot)
cli/command_modules/appservice/custom.py, ln 804, in _add_fx_version
    linux_fx = fx_version if web_app.reserved else None
AttributeError: 'NoneType' object has no attribute 'reserved'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config container set --name {} --resource-group {} --docker-custom-image-name {}`

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.5
Shell: bash

azure-cli 2.0.77

Extensions:
front-door 1.0.2
webapp 0.2.24

```

**Comment by panchagnula** [comment]
Please re-try there is no  change on our end here . Who re-trying run with --debug flag to get detailed errors.

**Comment by panchagnula** [comment]
Closing since there was no update on this for more than 3 days. Please re-activate if this is still an issue. Thanks!

**Comment by JeffinBao** [comment]
I am experiencing the same error with the same `az webapp config container set --name {} --resource-group {} --docker-custom-image-name {}`. Is there any update?
