### ISSUE TITLE
Creating Function App with custom container fails to deploy actual functions on Azure

### ISSUE THREAD

**Issue by davidmosen** [Azure/azure-cli#11541]
I'm following the instructions indicated here:
[https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image)

The Function App gets created with `az functionapp create`, but no Function (i.e. the example MyHttpTrigger) appears in Azure Portal and, when I run the final step `az functionapp config appsettings set`, I get the error below. Thus, I am unsure whether the Functions of the Function App do not appear because of the error or because of some silent error with the previous `az functionapp create`.

The only difference with the tutorial is that I'm using ´--consumption-plan-location westeurope´.

Because using DockerHub is simpler and because instructions in the tutorial for using ACR are not very detailed, the toy image I use for reproducing the error is on DockerHub. Locally running the image works flawlessly.

**Command Name**
`az functionapp config appsettings set`

**Errors:**
```
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
azure/cli/core/util.py, ln 260, in shell_safe_json_parse
    return json.loads(json_or_dict_string)
lib/python3.6/json/__init__.py, ln 354, in loads
    return _default_decoder.decode(s)
lib/python3.6/json/decoder.py, ln 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 19 (char 18)

...

cli/command_modules/appservice/custom.py, ln 219, in update_app_settings
    setting_name, value = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

## To Reproduce:

I have uploaded a Docker image to Docker Hub with the contents autogenerated, as per the instructions, by:
`func init MyFunctionProj --docker`

Then, after `az login`:

```
az functionapp create --resource-group ${RESOURCE_GROUP} \
--consumption-plan-location westeurope --storage-account ${STORAGE_ACCOUNT} \
--name ${FUNCTION_NAME} --deployment-container-image-name davidmosen/endpointfunction:1

storageConnectionString=$(az storage account show-connection-string -g ${RESOURCE_GROUP} -n ${STORAGE_ACCOUNT})

az functionapp config appsettings set --name ${FUNCTION_NAME} \
--resource-group ${RESOURCE_GROUP} \
--settings AzureWebJobsDashboard=$storageConnectionString \
AzureWebJobsStorage=$storageConnectionString
```

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

```

**Comment by ahmedelnably** [comment]
Having a custom docker container is not supported on the linux consumption hosting options.
The tutorial that you are referencing is targeting Linux Premium hosting option.
