### ISSUE TITLE
Unable to perform az apim backup

### ISSUE THREAD

**Issue by azaslonov** [Azure/azure-cli#11556]
## Describe the bug

**Command Name**
`az apim backup`

**Errors:**
```
No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
Traceback (most recent call last):
Temp\pip-install-mjd5h3hf\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 523, in execute
azure-cli-core\azure\cli\core\__init__.py, ln 294, in load_arguments
azure\cli\command_modules\apim\__init__.py, ln 28, in load_arguments
azure\cli\command_modules\apim\_params.py, ln 11, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim backup --verbose --debug --output {} --subscription {} --resource-group {} --name {} --no-wait`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.77

```

**Comment by kevinhillinger** [comment]
This should be fixed now. Recommend closing.

**Comment by RakeshMohanMSFT** [comment]
This is fixed now.
