### ISSUE TITLE
Feedback opportunity: https://aka.ms/azcligithats 

### ISSUE THREAD

**Issue by achandmsft** [Azure/azure-cli#11558]
Please tell us about your experience with the Azure CLI by filling in this survey - **[https://aka.ms/azcligithats](https://aka.ms/azcligithats)**. 

A few of you who agree to be contacted will also get to talk 1:1 with one of us (from the Azure CLI product team in Microsoft).

Thanks in advance for your valuable feedback!

Regards,
Arun 

Arun Chandrasekhar
Principal Program Manager 
Azure CLI

**Comment by haroldrandom** [comment]
@fengzhou-msft Please take a look

**Comment by yonzhan** [comment]
Welcome to any valuable feedback to Azure CLI team.

**Comment by fengzhou-msft** [comment]
Close issue as the survey is closed now. Please open another issue for future surveys.
