### ISSUE TITLE
Management-group create allows MGs to be created under TenantRoot without permissions

### ISSUE THREAD

**Issue by ikiris04** [Azure/azure-cli#11553]
## Describe the bug
Users without RBAC permissions (management group contributor or otherwise) can create management groups in Tenant.

**Command Name**
`az account management-group create`

**Errors:**
No errors from the command

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account management-group create --name {}`

## Expected Behavior
If user DOES NOT have RBAC permissions, the command should fail

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

Extensions:
resource-graph 0.1.8

```

**Comment by haroldrandom** [comment]
@jiasli Please take a look

**Comment by arrownj** [comment]
Hi @ikiris04 , according to management group document:


> Any Azure AD user in the tenant can create a management group without the management group write permission assigned to that user.
**Document Link:** https://docs.microsoft.com/en-us/azure/governance/management-groups/create#create-a-management-group

So I think this is a by-design feature of managment group. Please help check whether it answer your question. Thanks

**Comment by arrownj** [comment]
Hi @ikiris04 , if there are no more problems, I will close this issue first. If you have other problems about this, you can reopen it or submit a new one. Thanks
