### ISSUE TITLE
bug when trying to lauch azure cli in interactive mode on windows 10

### ISSUE THREAD

**Issue by gisairo** [Azure/azure-cli#11550]
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
pip-install-rtk110ve\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 654, in _run_job
Temp\pip-install-rtk110ve\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 631, in _run_job
cli\core\commands\__init__.py, ln 305, in __call__
azure\cli\core\__init__.py, ln 485, in default_command_handler
cli\command_modules\interactive\custom.py, ln 41, in start_shell
cliextensions\interactive\azext_interactive\__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
interactive\azext_interactive\azclishell\app.py, ln 27, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive --style {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.70

Extensions:
interactive 0.4.3

```

**Comment by haroldrandom** [comment]
@jiasli Please take a look

**Comment by arrownj** [comment]
Hi @gisairo , it seems that your `prompt_toolkit` version is not right. We use 1.0.x in interactive extension, for somehow, your version is 2.x or 3.x. 

You can reinstall it by this command:
`pip install prompt_toolkit~=1.0 --force-reinstall -t C:\Users\<USERNAME>\.azure\cliextensions\interactive`

Let me know if you have other problems. Thanks

**Comment by arrownj** [comment]
Hi @gisairo , close this first. You can reopen it or submit a new one if you have other concerns.
