### ISSUE TITLE
Azure failed Login

### ISSUE THREAD

**Issue by conerlyg** [Azure/azure-cli#11567]
Request Id: a8b0b699-8395-45a8-863e-d84fea702400 
Correlation Id: 773769ed-5b9a-4291-86a1-3c30936391fe 
Timestamp: 2019-12-12T19:06:42.369Z 
App name: Microsoft Azure CLI
App id: 04b07795-8ddb-461a-bbee-02f9e1bf7b46
IP address: 68.90.109.215
Device identifier: c2690745-1bcb-4039-b158-81e3c2f81554
Device platform: Windows 10
Device state: Registered
Advanced diagnostics: Enable 
If you plan on getting support for an issue, turn this on and try to reproduce the error. This will collect additional information that will help troubleshoot the issue.

**Comment by conerlyg** [comment]
gc3865@att.com
 
 
You cannot access this right now 
 

Your sign-in was successful but does not meet the criteria to access this resource. For example, you might be signing in from a browser, app, or location that is restricted by your admin.

**Comment by haroldrandom** [comment]
@jiasli Please have a look

**Comment by jiasli** [comment]
Your organization's Azure Active Directory may require interactive login for multi-factor authentication. Please use `az login` and continue the login in the opened browser.

**Comment by arrownj** [comment]
Hi @conerlyg , as @jiasli described before, the error message you meet was normally because of multi-factor authentication. Could you please advice whether there are other problems ? If not, I will close this issue first. And you can reopen it or submit a new one if you have other problems. Thanks

**Comment by mtricolici** [comment]
How do you close the issues without solutions? I have exactly the same damn issue and I don't know how to fix it.

**Comment by mtricolici** [comment]
If you are running this in linux then workaround is: in your default browser install an extension that changes user agent....
set it to a windows user agent.. azure portal think you're on windows.. and accepts it.
