### ISSUE TITLE
az network application-gateway url-path-map create: error: 'Namespace' object has no attribute 'firewall_policy'

### ISSUE THREAD

**Issue by mathieugravil** [Azure/azure-cli#11569]
Command doesn't work. It failed with error:
usage: az network application-gateway url-path-map create [-h] [--verbose]
                                                          [--debug]
                                                          [--output {json,jsonc,table,tsv,yaml,none}]
                                                          [--query JMESPATH]
                                                          [--subscription _SUBSCRIPTION]
                                                          --resource-group
                                                          RESOURCE_GROUP_NAME
                                                          --gateway-name
                                                          APPLICATION_GATEWAY_NAME
                                                          --name ITEM_NAME
                                                          --paths PATHS
                                                          [PATHS ...]
                                                          [--address-pool ADDRESS_POOL]
                                                          [--http-settings HTTP_SETTINGS]
                                                          [--redirect-config REDIRECT_CONFIG]
                                                          [--default-address-pool DEFAULT_ADDRESS_POOL]
                                                          [--default-http-settings DEFAULT_HTTP_SETTINGS]
                                                          [--default-redirect-config DEFAULT_REDIRECT_CONFIG]
                                                          [--rule-name RULE_NAME]
                                                          [--no-wait]
az network application-gateway url-path-map create: error: 'Namespace' object has no attribute 'firewall_policy'

Whereas it works in older version on az cli.

**Command Name**
`az network application-gateway url-path-map create`

**Errors:**
usage: az network application-gateway url-path-map create [-h] [--verbose]
                                                          [--debug]
                                                          [--output {json,jsonc,table,tsv,yaml,none}]
                                                          [--query JMESPATH]
                                                          [--subscription _SUBSCRIPTION]
                                                          --resource-group
                                                          RESOURCE_GROUP_NAME
                                                          --gateway-name
                                                          APPLICATION_GATEWAY_NAME
                                                          --name ITEM_NAME
                                                          --paths PATHS
                                                          [PATHS ...]
                                                          [--address-pool ADDRESS_POOL]
                                                          [--http-settings HTTP_SETTINGS]
                                                          [--redirect-config REDIRECT_CONFIG]
                                                          [--default-address-pool DEFAULT_ADDRESS_POOL]
                                                          [--default-http-settings DEFAULT_HTTP_SETTINGS]
                                                          [--default-redirect-config DEFAULT_REDIRECT_CONFIG]
                                                          [--rule-name RULE_NAME]
                                                          [--no-wait]
az network application-gateway url-path-map create: error: 'Namespace' object has no attribute 'firewall_policy'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
az network application-gateway url-path-map create --resource-group rg-total-hp2-we-msapprd --gateway-name MSAPPRD-APGA-WE-HP2 --name msa-api-pprodmyPathMap --paths '/document/*'  --subscription xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx --address-pool "msa-pprod-document-service-backendpool"  --default-address-pool "MSAPPRD-HP2-AKS"  --default-http-settings "msa-pprod-document-service-http-settings"  --http-settings "msa-pprod-document-service-http-settings"   --rule-name "msa-pprod-document-service-rule" --verbose --debug -o table

- _Put any pre-requisite steps here..._
- `az network application-gateway url-path-map create --gateway-name {} --name {} --paths {} -g {} --subscription {} --address-pool {} --default-address-pool {} --default-http-settings {} --http-settings {} --rule-name {} --debug -o {}`

## Expected Behavior
Creation of url map

## Environment Summary
```
Linux-4.15.0-1064-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

Extensions:
azure-devops 0.16.0
aks-preview 0.4.24

```

**Comment by MyronFanQiu** [comment]
@mathieugravil Hi. There is a bug in it and we have fixed it in https://github.com/Azure/azure-cli/pull/11421/files#diff-f5144ef44d9b9f354c14ee541233e678R799. The latest package will be released in the next week. Please upgrade your CLI and to see if it works. 😄

**Comment by MyronFanQiu** [comment]
@mathieugravil This should be fixed. Please upgrade your azure-cli. You can ref to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest for more details. Thanks.
