### ISSUE TITLE
ON specific VM

### ISSUE THREAD

**Issue by 5sfayas** [Azure/azure-cli#11560]
how do I get metrics for specific VM fro mresource group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c722777b-9914-5c57-b869-a92bb16e159e
* Version Independent ID: 19b7e250-35b0-6e41-6662-b86791cf4c78
* Content: [az monitor metrics](https://docs.microsoft.com/en-us/cli/azure/monitor/metrics?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
@qwordy Please take a look

**Comment by yungezz** [comment]
reassign this since user is trying to get metrics of VM. Hi @MyronFanQiu  could you pls help to confirm? if it's VM issue feel free to redirect the i ssue.

**Comment by MyronFanQiu** [comment]
@5sfayas Hello. Currently, you can get metrics through 
```
az monitor metrics list --resource /subscriptions/xxxxxxx/resourceGroups/myrg/providers/Microsoft.Compute/virtualMachines/myvm
```

**Comment by MyronFanQiu** [comment]
@5sfayas Hello. Did you solve your issue?

**Comment by 5sfayas** [comment]
IT worked
