### ISSUE TITLE
Hello , I am unable to run a powershell script in your terminal. Also your command for backup in azure cli are missing a backup option for key-vault certificates. 

### ISSUE THREAD

**Issue by brism17** [Azure/azure-cli#11565]
## Describe the bug

**Command Name**
``

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-4.15.0-1063-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

```

**Comment by haroldrandom** [comment]
@bim-msft Please take a look

**Comment by bim-msft** [comment]
@brism17 Could you please explain your questions further? Such as what command you used and the related error messages.

**Comment by bim-msft** [comment]
Also, according to the title `Also your command for backup in azure cli are missing a backup option for key-vault certificates`, this issue should not be labeled as `KeyVault`, it should be labeld as `Recovery Services Backup`, relabeled.

**Comment by pvrk** [comment]
@bim-msft : Azure Backup doesn't deal with Key-vault certificates. So, this should be seen by the key-vault team. Please relabel for Key-vault. Giving the command that is being tested will help confirm.

**Comment by pvrk** [comment]
@bim-msft : Please re-label to key vault team. We don't deal with backup of key vault certificates yet.

**Comment by bim-msft** [comment]
> @bim-msft : Please re-label to key vault team. We don't deal with backup of key vault certificates yet.

@pvrk Thanks for the notification!

**Comment by bim-msft** [comment]
Certificate backup/restore was supported now, the release time is Mar 31.
