### ISSUE TITLE
Non-Descriptive Error Message 

### ISSUE THREAD

**Issue by allegradomel** [Azure/azure-cli#11579]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Trying to improve [this error message](https://github.com/Azure/azure-cli/issues/10917). My question is:  **_Is CLI doing the validation here or is it simply passing it on from NRP_**?

**To Reproduce**
See above issue. 

**Expected behavior**
See above issue. 
**Environment summary**
See above issue. 
**Additional context**
Working on closing our open GitHub issues over on SDN team :)

**Comment by haroldrandom** [comment]
@MyronFanQiu Please take a look

**Comment by MyronFanQiu** [comment]
@allegradomel Hello. We simply pass this parameter to the server. The only requirement to reproduce this issue is to create a subnet with an overlapping address range on another subnet (set with the --address-prefixes option) .

**Comment by allegradomel** [comment]
Thank you !
