### ISSUE TITLE
az vm create --no-nsg

### ISSUE THREAD

**Issue by ElanShudnow** [Azure/azure-cli#11578]
Would be great when using az vm create if we could create a VM without any NSG.  It's getting assigned to an existing subnet using  --subnet $(az network vnet subnet show -g RGHERE--vnet-name VNETHERE -n default -o tsv --query id) that already has an NSG.  I dont' want an NSG assigned to the VM NIC directly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
@qwordy Please take a look

**Comment by qwordy** [comment]
You can use `--nsg ""`.
But if the NIC already has a NSG, I don't think you can remove it using `vm` command. Try to use `az network`. @MyronFanQiu do you know which command can do this?

**Comment by MyronFanQiu** [comment]
@ElanShudnow you can use this command to remove the existed nsg.
```
az network nic update --ids /subscriptions/xxxxxxxx/resourceGroups/nsg-test-xxxx/providers/Microsoft.Network/networkInterfaces/ddddd --remove networkSecurityGroup
```

**Comment by qwordy** [comment]
@ElanShudnow Do we solve your issue?

**Comment by qwordy** [comment]
Hope your issue is solved. If you have any other problems, please open a new issue. Your voice is welcome.
