### ISSUE TITLE
pfx password lost after importing the pfx certificate

### ISSUE THREAD

**Issue by evmimagina** [Azure/azure-cli#11576]
Hi,

I feel really disappointed when the password that protects the pfx file imported to keyvault using the "az keyvault certificate import" gets lost (if you download the pfx it's no longer password protected!) 
I can't find any option to protect that certificate with a password once it's uploaded.

Also trying to use "az keyvault secret set" and store the whole pfx as a secret, doesn't work either…

Seems to me there's no option to store a pfx cert with password protection. anoying!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9c661d7-bf43-5354-015e-3859f30a42a2
* Version Independent ID: fa69e552-5904-ce97-d02c-915c819bdde1
* Content: [az keyvault certificate](https://docs.microsoft.com/en-us/cli/azure/keyvault/certificate?view=azure-cli-latest#az-keyvault-certificate-import)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
@bim-msft Please take a look

**Comment by xiangyuerw** [comment]
I am confused about this, too. 
I can do the following because the cert on Keyvault doesn't have password:
1) download the cert with private key without password
2) install the cert without private key on pc

Then some risks:
1) anyone who get the unprotected cert can use it for malicious purpose
2) anyone who has access to the pc can export the cert for malicious purpose.

I am curious about what's the consideration behind. Does this means it all depends on the user to guarantee the security of the cert?

**Comment by thall** [comment]
I have the same problem, very very confusing! Why is the password removed?
I want my clients to download the password protected pkcs12 certificate. I don't want to give them access to `keys` or `secrets`. 

@haroldrandom @bim-msft

**Comment by evmimagina** [comment]
Hi all,

My 5 cents on this. 

A workaround all around this, create the certificate as a secret, leaves the password on the PFX (but not easy to import a pfx file as a secret neither!) so I wrote this script;

#START OF PS SCRIPT
write-host " ========= Set Variables =========="
write-host "kvname=$kvname"
write-host "pfxFilePath=$pfxFilePath"
write-host "pwd=$pwd"
write-host "kvsecretname=$kvsecretname"
#force error stop on Linux Agents using Powershell Core Script
#https://github.com/Microsoft/azure-pipelines-tasks/issues/10125

write-host " == Import Public Cert to KV == "
$secretContentType = 'application/x-pkcs12'
##Remove PFX password approach
#$flag = [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable
#$collection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection 
#$collection.Import($pfxFilePath, $pwd, $flag)
#$pkcs12ContentType = [System.Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12
#$clearBytes = $collection.Export($pkcs12ContentType)
#$fileContentEncoded = [System.Convert]::ToBase64String($clearBytes)

#Leave PFX password approach
$fileContentEncoded = [Convert]::ToBase64String([IO.File]::ReadAllBytes($pfxFilePath))

##Powershell fails as no module is present on agent and impossible to install
#Set-AzureKeyVaultSecret -VaultName $kvname -Name $kvsecretname -SecretValue $Secret -ContentType $secretContentType
#AZ CLI
write-host "Trying to wipe previous secret: $kvsecretname"
$output = az keyvault secret delete --vault-name $kvname --name $kvsecretname 
if (!$output) {
    Write-host "Secret does not exists on KV?, first time execution?, ok, no problem...."
}

write-host "Trying to set KV secret value for: $kvsecretname"
$output = az keyvault secret set --vault-name $kvname --name $kvsecretname --value $fileContentEncoded #--encoding base64
if (!$output) {
    Write-Error "ERROR!, Unable to set secret, abort script"
    exit 1
}

write-host "Trying to set KV secret property on: $kvsecretname"
$output = az keyvault secret set-attributes --content-type $secretContentType --vault-name $kvname --name $kvsecretname
if (!$output) {
    Write-Error "ERROR!, Unable to set secret property, abort script"
    exit 1
}

write-host "EOS"
exit 0
#END OF SCRIPT

Adapt as needed.

Cheers,

**Comment by yungezz** [comment]
HI @bim-msft could you pls help to confirm is this ask supported in keyvault service firstly? thanks.

**Comment by bim-msft** [comment]
@yungezz I've investigated our code and nothing unexpected found, I believe this is a service side error (or by design?) since we didn't change the certificate binary data in CLI code, and we always pass the password into the rest call.
I did the import/export experiment on portal too, the password was also lost.

```python
def import_certificate(cmd, client, vault_base_url, certificate_name, certificate_data,
                       disabled=False, password=None, certificate_policy=None, tags=None):
    import binascii
    CertificateAttributes = cmd.get_models('CertificateAttributes', resource_type=ResourceType.DATA_KEYVAULT)
    SecretProperties = cmd.get_models('SecretProperties', resource_type=ResourceType.DATA_KEYVAULT)
    CertificatePolicy = cmd.get_models('CertificatePolicy', resource_type=ResourceType.DATA_KEYVAULT)
    x509 = None
    content_type = None
    try:
        x509 = crypto.load_certificate(crypto.FILETYPE_PEM, certificate_data)
        # if we get here, we know it was a PEM file
        content_type = 'application/x-pem-file'
        try:
            # for PEM files (including automatic endline conversion for Windows)
            certificate_data = certificate_data.decode('utf-8').replace('\r\n', '\n')
        except UnicodeDecodeError:
            certificate_data = binascii.b2a_base64(certificate_data).decode('utf-8')
    except (ValueError, crypto.Error):
        pass


    if not x509:
        try:
            if password:
                x509 = crypto.load_pkcs12(certificate_data, password).get_certificate()
            else:
                x509 = crypto.load_pkcs12(certificate_data).get_certificate()
            content_type = 'application/x-pkcs12'
            certificate_data = binascii.b2a_base64(certificate_data).decode('utf-8')
        except crypto.Error:
            raise CLIError(
                'We could not parse the provided certificate as .pem or .pfx. Please verify the certificate with OpenSSL.')  # pylint: disable=line-too-long


    not_before, not_after = None, None


    if x509.get_notBefore():
        not_before = _asn1_to_iso8601(x509.get_notBefore())


    if x509.get_notAfter():
        not_after = _asn1_to_iso8601(x509.get_notAfter())


    cert_attrs = CertificateAttributes(
        enabled=not disabled,
        not_before=not_before,
        expires=not_after)


    if certificate_policy:
        secret_props = certificate_policy.get('secret_properties')
        if secret_props:
            secret_props['content_type'] = content_type
        elif certificate_policy and not secret_props:
            certificate_policy['secret_properties'] = SecretProperties(content_type=content_type)
    else:
        certificate_policy = CertificatePolicy(
            secret_properties=SecretProperties(content_type=content_type))


    logger.info("Starting 'keyvault certificate import'")
    result = client.import_certificate(vault_base_url=vault_base_url,
                                       certificate_name=certificate_name,
                                       base64_encoded_certificate=certificate_data,
                                       certificate_attributes=cert_attrs,
                                       certificate_policy=certificate_policy,
                                       tags=tags,
                                       password=password)
    logger.info("Finished 'keyvault certificate import'")
    return result
```

**Comment by yungezz** [comment]
thanks @bim-msft for investigation, add service attention label .

**Comment by rushilShetty** [comment]
Hello, we're facing the same issue here. Is this a known service side issue or is it by design? Can someone please confirm?

**Comment by KZeronimo** [comment]
Bumping this issue - and referencing this [feedback](https://feedback.azure.com/forums/906355-azure-key-vault/suggestions/35895037-export-certificate-as-pkcs12-pfx-does-not-provide)

Preserving the password on pfx import and/or allowing a password to be set on pfx download is desired and needed!

@evmimagina I'm using the same approach; however, the certificate functionality is preferable since the pfx is decomposed and 3 parts stored (cert, key, and secret) [as described in the docs](https://docs.microsoft.com/en-us/azure/key-vault/certificates/certificate-scenarios#certificates-are-complex-objects)

**Comment by aggerritsen** [comment]
This issue is persist. I found some help at https://coombes.nz/blog/azure-keyvault-export-certificate/
Please read the comments of Alex Angas on that article. The combined workaround that worked for me was:

```
# Replace these variables with your own values
$vaultName = "#######"                
$certificateName = "#######"         
$pfxPath = "#######" 
$PlainTextPassword = "#######"                

$password = ConvertTo-SecureString -String $PlainTextPassword -Force -AsPlainText 

# Fix from https://coombes.nz/blog/azure-keyvault-export-certificate/
$pfxSecret = Get-AzKeyVaultSecret -VaultName $vaultName -Name $certificateName
$pfxUnprotectedBytes = [Convert]::FromBase64String($pfxSecret.SecretValueText)

# Fix to the fix as commented by Alex Angas
$pfx = New-Object Security.Cryptography.X509Certificates.X509Certificate2($pfxUnprotectedBytes, "", [Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)

# Stick the password back into the file
$pfxProtectedBytes = $pfx.Export([Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12, $password)
[IO.File]::WriteAllBytes($pfxPath, $pfxProtectedBytes)
```

But I would highly appriciate when this issue gets solved in Azure KeyVault itself,

Kind regards, Arjen Gerritsen

**Comment by sebansal** [comment]
@bim-msft can you add feature request label
Key vault does not store the password once cert is imported.
https://docs.microsoft.com/en-us/azure/key-vault/certificates/import-cert-faqs#after-importing-password-protected-certificate-into-the-key-vault-and-then-downloading-it-i-am-not-able-to-see-the-password-associated-with-the-certificate

**Comment by sebansal** [comment]
it is by design that key vault would not return exported cert file with password.

**Comment by msft-tacox** [comment]
Why is this by design? What happens when we use KV to store a certificate that we expect to be protected by a password when used in our service/by our end users? How can we keep the password intact? @houk-ms

**Comment by sebansal** [comment]
When designing your application, from security perspective, we recommend using the principle of least privilege and only grant Access policy or RBAC permissions to the identified user/service principal.

**Comment by msft-tacox** [comment]
That sounds fine, but isn't AKV just meant to be a (simple) place to store secrets, certs and so on? Why would I (as a customer) want AKV to change the properties of my cert when I upload it (regardless of any recommended principals)?

**Comment by jlichwa** [comment]
In case of secrets we just store as it is, but for certificates we have to parse through pfx file and as of now our parser does not handle passwords. There is feature request you can vote on here https://feedback.azure.com/forums/906355-azure-key-vault/suggestions/32603098-add-support-for-storage-and-retrieval-of-password

**Comment by msft-tacox** [comment]
@jlichwa Seems more like a bug as opposed to a feature to develop, no? As a customer, I expect AKV to store my secrets/certificates exactly as they are. Since AKV has failed to preserve the password, AKV has effectively corrupted my certificate. 

It seems like there are others asking the same question - https://github.com/MicrosoftDocs/azure-docs/issues/64609

**Comment by Ajay250496** [comment]
> 

Sorry may be missing your workaround here. While you are importing the secret as a base64 encoded contents. It doesn't show up in azure as a cert so you will automatically have to download the base64 file and convert it back to pfx? Also does the 'content-type' : 'application/x-pkcs12' actually make any difference? I've set it and havent really noticed any difference.  

Ofc your workaround may not work for me as I'd ideally want my users to download the pfx file from the portal with the password already attached.
