### ISSUE TITLE
az aks browse: error: the following arguments are required: --resource-group/-g, --name/-n

### ISSUE THREAD

**Issue by danialram** [Azure/azure-cli#11575]
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
az aks browse: error: the following arguments are required: --resource-group/-g, --name/-n
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.77

```

**Comment by seanmck** [comment]
Yes, these arguments are required to indicate the cluster for which you want to open the dashboard. See doc here:

https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard
