### ISSUE TITLE
[Engineer Excellence] automatic release pipeline

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#11573]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Today release is manual, which is error-prone and time-consuming. It's necessary to automatic release pipeline.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by haroldrandom** [comment]
@fengzhou-msft Please plan in S164

**Comment by yonzhan** [comment]
Thanks @yungezz @fengzhou-msft to drive this engineer excellence feature to improve the whole team productivity.

**Comment by fengzhou-msft** [comment]
The automated pipelines have been created and ran for 2 releases. While I will continue to work on further improvement including automating history notes, automating sending e-mails, this issue can be closed as we have the initial version running.
