### ISSUE TITLE
advanced filter in eventubscription update

### ISSUE THREAD

**Issue by subashsivaji** [Azure/azure-cli#11589]
There is no --advanced-filter option in az eventgrid event-subscription update. Is this by design?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e73e1b-aad9-0ce8-be1f-a9b9d02ca6d4
* Version Independent ID: 73525c5f-94f3-1c07-e3b6-3a022aab2a10
* Content: [az eventgrid event-subscription](https://docs.microsoft.com/en-us/cli/azure/eventgrid/event-subscription?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/eventgrid/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/eventgrid/_help.py)
* Service: **event-grid**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
The related IcM ticket is: https://icm.ad.msft.net/imp/v3/incidents/details/163274315/home, @jfggdl, please help to take a look.

**Comment by jfggdl** [comment]
Thanks for reporting this and thanks for the IcM reference. We are working on this issue and determining a path forward to a fix/clarification.

**Comment by ahamad-MS** [comment]
Hello @yonzhan 

AdvancedFilter is supported in mainstream CLI. I am not sure what is your running environment and/or if you currently running any old "cli extension" module.

please go to shell.azure.com and type the following:

~$az extension list
[]

If you are seeing eventgrid in the list, then please go ahead and remove it

~$az extension remove --name eventgrid

For me, here is the help output where AdvancedFilters are supported in non-extension cli environment.

ashraf@Azure:~$ az eventgrid event-subscription create --help

Command
    az eventgrid event-subscription create : Create a new event subscription.

Arguments
    --endpoint    [Required] : Endpoint where EventGrid should deliver events matching this event
                               subscription. For webhook endpoint type, this should be the
                               corresponding webhook URL. For other endpoint types, this should be
                               the Azure resource identifier of the endpoint. It is expected that
                               the destination endpoint to be already created and available for use
                               before executing any Event Grid command.
    --name -n     [Required] : Name of the event subscription.
    **--advanced-filter        : An advanced filter enables filtering of events based on a specific
                               event property.
        Usage:                     --advanced-filter KEY[.INNERKEY] FILTEROPERATOR VALUE [VALUE ...]
        StringIn:                  --advanced-filter data.Color StringIn Blue Red Orange Yellow
        StringNotIn:               --advanced-filter data.Color StringNotIn Blue Red Orange Yellow
        StringContains:            --advanced-filter subject StringContains Blue Red
        StringBeginsWith:          --advanced-filter subject StringBeginsWith Blue Red
        StringEndsWith:            --advanced-filter subject StringEndsWith img png jpg
        NumberIn:                  --advanced-filter data.property1 NumberIn 5 10 20
        NumberNotIn:               --advanced-filter data.property2 NumberNotIn 100 200 300
        NumberLessThan:            --advanced-filter data.property3 NumberLessThan 100
        NumberLessThanOrEquals:    --advanced-filter data.property2 NumberLessThanOrEquals 100
        NumberGreaterThan:         --advanced-filter data.property3 NumberGreaterThan 100
        NumberGreaterThanOrEquals: --advanced-filter data.property2 NumberGreaterThanOrEquals 100**
        BoolEquals:                --advanced-filter data.property3 BoolEquals true
        Multiple advanced filters can be specified by using more than one `--advanced-filter`
        argument.
    --deadletter-endpoint    : The Azure resource ID of an Azure Storage blob container destination
                               where EventGrid should deadletter undeliverable events for this event

**Comment by c4rlosmarin** [comment]
Hi there, just wanted to reach out and say this is about the az eventgrid event-subscription UPDATE command, not the create one. Thanks

**Comment by ahamad-MS** [comment]
Thanks @c4rlosmarin  .. you are right. I missed the update part.

It seems we missed adding the AdvancedFilter functioinality in update command. We will add this to our backlog and fix this.

In the meantime, you can use either:
1. Delete existing event subscription and create new one with the new advanced filter.
2. Use the Create command with the same name and information and with the new advanced filter. This should trigger an update too.

**Comment by ahamad-MS** [comment]
As mentioned earlier, we are addressing this issue as part of our next cli work and customer should be unblocked by using create with same resource name to update the advanced filter. Per our triage policy, we are closing this issue due to lack of response from customer. Please feel free to contact us again if mitigation step is not working for you for whatever reason or for any other issues. thanks.
