### ISSUE TITLE
"az containter attach" returns `Back-off restarting failed container`

### ISSUE THREAD

**Issue by Abdelkrim** [Azure/azure-cli#11584]
# The issue

1. I have followed the following tutorial `Tutorial: Build and deploy container images in the cloud with Azure Container Registry Task`

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-quick-task?source=docs#feedback

2. All actions work until the chapter **verify the deployment** 

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-quick-task?source=docs#verify-the-deployment

3. Running ` az container attach` command generates a `Back-off restarting failed container` error

# The detailed error

> az container attach --resource-group %RES_GROUP% --name acr-tasks
> Container 'acr-tasks' is in state 'Waiting'...
> Container 'acr-tasks' is in state 'Terminated'...
> ......
> (count: 3) (last timestamp: 2019-12-15 22:03:32+00:00) pulling image "my_project.azurecr.io/my_project.my_sub_project:v2019-12-15"
> Container 'acr-tasks' is in state 'Terminated'...
> Container 'acr-tasks' is in state 'Waiting'...
> (count: 3) (last timestamp: 2019-12-15 22:03:32+00:00) pulling image "my_project.azurecr.io/my_project.my_sub_project:v2019-12-15"
> (count: 3) (last timestamp: 2019-12-15 22:03:32+00:00) Successfully pulled image "my_project.azurecr.io/my_project.my_sub_project:v2019-12-15"
> (count: 3) (last timestamp: 2019-12-15 22:03:32+00:00) Created container
> (count: 3) (last timestamp: 2019-12-15 22:03:32+00:00) Started container

**Comment by cox-antohi** [comment]
I'm having the exact same issue. Is there any fix?

**Comment by yonzhan** [comment]
containter service team needs to look into this.

**Comment by navba-MSFT** [comment]
@Abdelkrim Apologies for the late reply. If you are still facing this issue, Could you please check for any failure error messages in the [container logs ](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-logs)? Also this issue is open for quite sometime, Please let us know if you still need assistance on this.  Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Abdelkrim I wanted to do quick follow-up to check if you had a chance to look at my above comment. This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by Abdelkrim** [comment]
@navba-MSFT I'll close the issue.

I don't recall what i did to overcome the issue.

thank you for popping it up
