### ISSUE TITLE
az container release create --vsts-account-name not clear what value is required

### ISSUE THREAD

**Issue by SteveLasker** [Azure/azure-cli#1158]
When passing in the account name, it wasn't clear whether I should pass in:
dockerdemos
dockerdemos.visualstudio.com
http://dockerdemos.visualstudio.com
https://dockerdemos.visualstudio.com

An example should be added to the parameter name 
`--vsts-account-name           : VSTS account name to create the build and release definitions. Anew VSTS account is created if omitted or does not exist. eg: contoso`

Example calls should be added to the release create --help information

**Comment by YuzorMa** [comment]
Fixed with #1261.
