### ISSUE TITLE
UserAgent is not recorded in server telemetry for az login

### ISSUE THREAD

**Issue by yonzhan** [Azure/azure-cli#11586]
This is a bug in Azure CLI for server telemetry not appearing.

The root cause is because when creating the list subscription client, CLI is not calling the generalized client factory, thus configure_common_settings is not called which involves setting up user agent and additional header CommandName, ParameterSetName.

**Comment by yonzhan** [comment]
add to S163.

**Comment by jiasli** [comment]
This issue has been address in above PR.
