### ISSUE TITLE
running `brew install wget` seems to have broken the openssl dependency for az

### ISSUE THREAD

**Issue by robertjf** [Azure/azure-cli#11585]
## Describe the bug
running `brew install wget` seems to have broken the openssl dependency for az.

**Command Name**
`az aks list`

**Errors:**
```
dlopen(/usr/local/Cellar/azure-cli/2.0.66/libexec/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/azure-cli/2.0.66/libexec/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so
  Reason: image not found
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
...
ImportError: dlopen(/usr/local/Cellar/azure-cli/2.0.66/libexec/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/azure-cli/2.0.66/libexec/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so
  Reason: image not found
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks list -g {} --query {} -o {}`

## Environment Summary
```
Darwin-19.0.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.66

Extensions:
dev-spaces 1.0.3

```

**Comment by jluk** [comment]
@robertjf can you please update your build to 2.0.77 an retry some commands? It sounds like this isn't AKS specific but I'd like to see if upgrading resolves some of this since your build is old.

**Comment by robertjf** [comment]
@jluk thanks, that's worked a treat.
