### ISSUE TITLE
AZ cli returning error

### ISSUE THREAD

**Issue by ndixita** [Azure/azure-cli#11591]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials -g {} -n {} --file {}`

## Environment Summary
```
Linux-4.15.0-1064-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

```

**Comment by jluk** [comment]
There is no error on this... @ndixita can you please review these autogenerated tests?

Closing.
