### ISSUE TITLE
az webapp up flag for html static sites

### ISSUE THREAD

**Issue by btardif** [Azure/azure-cli#11592]
There is no reliable detection logic for plain old html apps.

we should add a -html flag that ignores detection logic and deploys this as a html app.

See:
- https://github.com/MicrosoftDocs/azure-docs/issues/44124

**Comment by btardif** [comment]
@panchagnula can we add @ammanifold to this team so that I can assign stuff to her?

**Comment by yonzhan** [comment]
@ammanifold any update for this issue?

**Comment by ammanifold** [comment]
Waiting for the PR to be merged

**Comment by panchagnula** [comment]
@yonzhan this fix has been ready for PR & wasn't merged please have this merged for the current release - we have had several requests on this one. Thanks!
