### ISSUE TITLE
single group subcommand values treated as regex

### ISSUE THREAD

**Issue by jimsander** [Azure/azure-cli#11599]
azure-cli                         2.0.75 

```

az ad group list -o tsv --query "[? displayName == 'PAC.G.ODTA' || mailNickname == 'PAC.G.ODTA' ].[objectId,displayName]"
1__REDACTED__4	PAC.G.ODTA

az ad group show --group 'PAC.G.ODTA' -o tsv --query "[objectId,displayName]"
More than one groups match the name of 'PAC.G.ODTA'
```

**Comment by MyronFanQiu** [comment]
@jiasli Please take care of this issue. Thanks.

**Comment by jiasli** [comment]
Nice catch. I am able to reproduce. 

With `--debug`, the log reviews the URL being called: `
https://graph.windows.net/{}/groups?$filter=startswith(displayName,'adgroup2110') or displayName eq 'adgroup2110'&api-version=1.6`. The `or` operator is causing problem. 

The error `More than one groups match the name of {}` appears when one group name starts with another, like:

```
adgroup2110
adgroup21101
```

The erroneous logic is at https://github.com/Azure/azure-cli/blob/4d5b1a942e48ce6f8674420f2b18d50f19ed860e/src/azure-cli/azure/cli/command_modules/role/_validators.py#L25-L27
I will submit a PR to fix it.
