### ISSUE TITLE
[VSTS] Release/build creation assumes that Git 2.7+ is installed

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1159]
When trying to run `az vsts build create` or `az vsts release create` on a Git-managed project, I get the following error:

<img width="925" alt="screen shot 2016-10-25 at 10 00 40 am" src="https://cloud.githubusercontent.com/assets/116461/19695946/f026c55c-9a99-11e6-853c-32a64d0470d1.png">

I'm running OS X El Capitan, and have Git 2.6.4 installed. The `git remote get-url` method wasn't added until [v2.7.0](https://git-scm.com/docs/git-remote/2.7.0), which explains why the above error occurs. When I updated my Git installation, the error was resolved, but it would be ideal if the commands either let you know that you need a newer version of Git to continue, or employed a workaround of some kind.

**Comment by YuzorMa** [comment]
Fixed by #1367
