### ISSUE TITLE
--assignee-principal-type documents wrong list of expected values

### ISSUE THREAD

**Issue by astaykov** [Azure/azure-cli#11594]
Environment: Cloud Shell
Version of tool: 
azure@Azure:~/clouddrive$ az --version
azure-cli                         2.0.77

command-modules-nspkg              2.0.3
core                              2.0.77
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/azure/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Nov 22 2019, 05:32:22)
[GCC 5.4.0 20160609]

Documented expected values for --assignee-principal-type:
 --assignee-principal-type : Use with --assignee-object-id to avoid errors caused by propagation
                                latency in AAD Graph.  Allowed values: Application,
                                DirectoryObjectOrGroup, DirectoryRoleTemplate, Everyone,
                                ForeignGroup, Group, MSI, ServicePrincipal, Unknown, User.

Actual result when used with `MSI`:
**ERROR: The PrincipalType property 'MSI' is not valid. It must be 'User', 'Group' or 'ServicePrincipal'.**

Either documentation or CLI must be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dacfad8-cb2f-2534-3b29-89b0930a2252
* Version Independent ID: 17325cd4-44c5-4069-d9f6-940a55f0f7c9
* Content: [az role assignment](https://docs.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@jiasli Please take care of this issue. Thanks.

**Comment by zincob** [comment]
When should we expect to get a fix on this issue?

**Comment by arrownj** [comment]
Hi @astaykov @zincob , the allowed value is defined in swagger file (https://github.com/Azure/azure-rest-api-specs/blob/729474ae2b674d2ddfc4d5d8e990318d87f04202/specification/authorization/resource-manager/Microsoft.Authorization/preview/2018-09-01-preview/authorization-RoleAssignmentsCalls.json#L511). We will try to find out whether the definition is wrong or there is some usage tricks.

**Comment by yungezz** [comment]
@arrownj could you pls update here with communication from Swagger related engrs? need service team's clarification on allowed value.

**Comment by lukasmrtvy** [comment]
Same problem with azure-cli 2.9.1

**Comment by audunsolemdal** [comment]
ARM template gives exact same error.

**Comment by jiasli** [comment]
As @arrownj stated, the available types are defined in the REST spec of `principalType`:

https://github.com/Azure/azure-rest-api-specs/blob/bf2b0b5dbc0cb59b44a4a2c9eb24770754ad1056/specification/authorization/resource-manager/Microsoft.Authorization/preview/2018-09-01-preview/authorization-RoleAssignmentsCalls.json#L508-L522

```
        "principalType": {
          "type": "string",
          "description": "The principal type of the assigned principal ID.",
          "enum": [
            "User",
            "Group",
            "ServicePrincipal",
            "Unknown",
            "DirectoryRoleTemplate",
            "ForeignGroup",
            "Application",
            "MSI",
            "DirectoryObjectOrGroup",
            "Everyone"
          ],
```

We have confirmed with RBAC service team that **some types are used only internally and should not be exposed in the REST spec**.

For now, please only use `User`, `Group` or `ServicePrincipal`.

For Microsoft internal reference, see email: _BadRequestError: The PrincipalType property 'MSI' is not valid. It must be 'User', 'Group' or 'ServicePrincipal'_
