### ISSUE TITLE
`az webapp config appsettings set --settings` from file path

### ISSUE THREAD

**Issue by rick-hayek** [Azure/azure-cli#11607]
i'm trying to use following command to update settings:
```
az webapp config appsettings set --name $app --settings "c:\my\full\path\to\appsetting.json"
```

and got bunch of py errors. 

does this command support settings from any arbitrary json file other than @file-from-current-folder.json ? and if true, how to get this work?

please help. thank you

**Comment by ajklotz** [comment]
@rick-hayek I have another issue open just like this.

https://github.com/Azure/azure-cli/issues/11600

**Comment by panchagnula** [comment]
Yes this command does support passing a valid JSON to the --settings parameter. Can you validate that the JSON object you have in the json file I valid? if not share the settings you have in the file & I can help you investigate further. Thanks!

**Comment by ajklotz** [comment]
Hey @panchagnula please take a look at #11600 I believe @rick-hayek is basically having the same issue described in my issue. The problem seems to be when the JSON file in a different directory than the working directory of powershell. So if you attempt to use a path to the JSON, it fails. If the JSON file is referenced in the same path, everything works fine.

**Comment by panchagnula** [comment]
@ajklotz thanks for the update wanted to clarify something - are you using PowerShell to run these commands instead of Bash window? I have run these from different DIR than working DIR & has worked for me - I never used PowerShell for this though.

**Comment by ajklotz** [comment]
Yes, I'm using Powershell. @panchagnula

**Comment by panchagnula** [comment]
@ajklotz  thanks for confirming @rick-hayek is your issue also because of the use of PowerShell?

**Comment by ajklotz** [comment]
@rick-hayek @panchagnula My issue was closed. I was given a solution and it works using a relative path. I had to remove a slash after the @ symbol. 

https://github.com/Azure/azure-cli/issues/11600#issuecomment-569865850

**Comment by panchagnula** [comment]
thanks for confirming @ajklotz . Closing this @rick-hayek please re-activate or file a new issue if this doesn't solve the issue you filed. Thanks!
