### ISSUE TITLE
az sig does not work

### ISSUE THREAD

**Issue by jakub-xen** [Azure/azure-cli#11604]
## Describe the bug

**Command Name**
`az sig list`

**Errors:**
```
APIVersion 2019-07-01 is not available
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.6/site-packages/six.py, ln 693, in reraise
    raise value
...
azure/cli/core/__init__.py, ln 485, in default_command_handler
    return op(**command_args)
cli/command_modules/vm/custom.py, ln 2688, in list_image_galleries
    return client.galleries.list()
azure/mgmt/compute/_compute_management_client.py, ln 252, in galleries
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-07-01 is not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sig list`

## Environment Summary
```
Darwin-19.0.0-x86_64-i386-64bit
Python 3.6.5
Shell: bash

azure-cli 2.0.76 *

```

**Comment by MyronFanQiu** [comment]
@qwordy Please take care of this issue. Thanks.

**Comment by qwordy** [comment]
Could you upgrade to 2.0.78 and have another try? I can run this command successfully.

**Comment by jakub-xen** [comment]
Hi

Thanks update to 78 fixed the issue.

cheers,
Jakub
  Jakub Szarlat
  Senior Systems Architect, XENON Systems Pty Ltd

  M   +61 425 706 806   |   F   +61 3 9549 1199   |   E   jakubs@xenon.com.au<mailto:jakubs@xenon.com.au>

  [XENON Systems logo] <http://www.xenon.com.au/>

  XENON Systems Pty Ltd
  10 Westall Road, Clayton South, Victoria 3169, Australia (map)<https://www.google.com.au/maps/place/XENON/@-37.9329833,145.1425729,16z/data=!4m7!1m4!3m3!1s0x6ad638c6caee8011:0xf98420d4cf5b9c96!2sXENON!3b1!3m1!1s0x6ad638c6caee8011:0xf98420d4cf5b9c96?hl=en>
  www.xenon.com.au<http://www.xenon.com.au/>

  Follow us:
  Blog<http://www.xenon.com.au/press/blog/>   |   Facebook<https://www.facebook.com/XENONSystemsPtyLtd>   |   LinkedIn<http://www.linkedin.com/company/xenon-systems>   |   Twitter<https://twitter.com/XENONSystems>   |   YouTube<https://www.youtube.com/c/xenonausystemsptyltd>

  XENON Systems Pty Ltd is a member of the XENON Technology Group which includes:
  Mediaproxy Pty Ltd<http://www.mediaproxy.com/>   |   Catapult<http://www.xdt.com.au/>


________________________________

This email (and any attachment/s) is intended solely for use by the Addressee(s) named above. It may contain confidential or proprietary information of the XENON Technology Group, its affiliates and/or business partners. If you are not the intended Recipient of this email or are an Unauthorised Recipient of this information, you are hereby notified that any dissemination, distribution or copying of this email or any attachment/s is strictly prohibited. If you have received this e-mail in error, please immediately notify the Sender by reply email and permanently delete the original and any copies or printouts. Thank you for your kind cooperation.

Please be mindful of our environment and do not print this email unless it is absolutely necessary.



On 19 Dec 2019, at 8:18 pm, Feiyue Yu <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you upgrade to 2.0.78 and have another try? I can run this command successfully.

**Comment by yungezz** [comment]
hi @jakub-xen can we close the issue since your problem solved? thanks.

**Comment by jakub-xen** [comment]
Yes Thanks.
  Jakub Szarlat
  Senior Systems Architect, XENON Systems Pty Ltd

  M   +61 425 706 806   |   F   +61 3 9549 1199   |   E   jakubs@xenon.com.au<mailto:jakubs@xenon.com.au>

  [XENON Systems logo] <http://www.xenon.com.au/>

  XENON Systems Pty Ltd
  10 Westall Road, Clayton South, Victoria 3169, Australia (map)<https://www.google.com.au/maps/place/XENON/@-37.9329833,145.1425729,16z/data=!4m7!1m4!3m3!1s0x6ad638c6caee8011:0xf98420d4cf5b9c96!2sXENON!3b1!3m1!1s0x6ad638c6caee8011:0xf98420d4cf5b9c96?hl=en>
  www.xenon.com.au<http://www.xenon.com.au/>

  Follow us:
  Blog<http://www.xenon.com.au/press/blog/>   |   Facebook<https://www.facebook.com/XENONSystemsPtyLtd>   |   LinkedIn<http://www.linkedin.com/company/xenon-systems>   |   Twitter<https://twitter.com/XENONSystems>   |   YouTube<https://www.youtube.com/c/xenonausystemsptyltd>

  XENON Systems Pty Ltd is a member of the XENON Technology Group which includes:
  Mediaproxy Pty Ltd<http://www.mediaproxy.com/>   |   Catapult<http://www.xdt.com.au/>


________________________________

This email (and any attachment/s) is intended solely for use by the Addressee(s) named above. It may contain confidential or proprietary information of the XENON Technology Group, its affiliates and/or business partners. If you are not the intended Recipient of this email or are an Unauthorised Recipient of this information, you are hereby notified that any dissemination, distribution or copying of this email or any attachment/s is strictly prohibited. If you have received this e-mail in error, please immediately notify the Sender by reply email and permanently delete the original and any copies or printouts. Thank you for your kind cooperation.

Please be mindful of our environment and do not print this email unless it is absolutely necessary.



On 20 Dec 2019, at 1:05 pm, Yunge Zhu <notifications@github.com<mailto:notifications@github.com>> wrote:


hi @jakub-xen<https://github.com/jakub-xen> can we close the issue since your problem solved? thanks.
