### ISSUE TITLE
DiskEncryptionSet not supported by Azure Stack

### ISSUE THREAD

**Issue by viananth** [Azure/azure-cli#11615]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version C:\Windows\system32>az -v
azure-cli                         2.0.77 *

command-modules-nspkg              2.0.3
core                              2.0.77 *
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Python35\python.exe'
Extensions directory 'C:\Users\Administrator\.azure\cliextensions'

Python (Windows) 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Describe the bug**
There is a recent commit in Azure CLI that introduces DiskEncryptionSet parameter for managed disk. This parameter is not supported by Azure Stack and it will break our customers if they try to create a VM. 
Commit: https://github.com/Azure/azure-cli/commit/4c19a9695b4947964a1b54fdaee06095c84c8acd

**To Reproduce**
az cloud update --profile 2019-03-01-hybrid
az vm create

**Expected behavior**
Should be able to create a vm in 2019-03-01-hybrid profile

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
edge build
cmd
windows

**Additional context**
Example fix:
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/custom.py#L347

**Comment by MyronFanQiu** [comment]
@qwordy Please take care of this issue.

**Comment by qwordy** [comment]
Oh, I am sorry about that. I should add a constraint for api-version. I’ll fix it as soon as possible.

**Comment by HassanAlmanasrah** [comment]
I was doing test today and got the same issue in Azure Stack. Could you advise if the constraint was put in place for minimum api or it is still working with api 2019-03-01-hybrid for VM provisioning?

**Comment by bganapa** [comment]
@qwordy I thought the fix was in immediately and never got shipped in a released build. Is that not the case?

**Comment by qwordy** [comment]
Oh. Sorry. I didn't mention when will the new version be released. The latest version 2.0.79 has been released. It contains the fix.

**Comment by HassanAlmanasrah** [comment]
Thanks. Just upgraded to 2.0.79 and successfully deployed VM.
