### ISSUE TITLE
securestring parameters are revealed in verbose output

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1161]
I understand that secrets are exposed when running with `--debug` (if nothing else the oauth token is visible).

But I was hoping to be able to use `--verbose` in CI jobs that might eventually be exposed to the public... but one of the things we do is a template deployment with a parameters file that includes private keys.

It'd be nice if `az resource group deployment create --verbose` would filter `securestring` parameters out of the verbose output.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
