### ISSUE TITLE
Improvements to Python search paths on Windows

### ISSUE THREAD

**Issue by zooba** [Azure/azure-cli#11613]
I was reviewing some CLI sources and noticed this section of code:

https://github.com/Azure/azure-cli/blob/6887c5badd7246fea1c4586e835224d39acfcc4e/src/azure-cli-telemetry/azure/cli/telemetry/__init__.py#L15-L22

The Windows package should be using a `python._pth` file (possibly with the version number in there), which means you can simply add these directories to that file and they'll be put onto `sys.path`.

You also shouldn't need the `%PATH%` modification, but should `import pywin32_bootstrap` [(source)](https://github.com/mhammond/pywin32/blob/master/win32/Lib/pywin32_bootstrap.py) instead. That will also handle the [change on Python 3.8](https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew) that prevents `%PATH%` being used for DLL resolution, which is presumably what this is attempting.

**Comment by MyronFanQiu** [comment]
@jiasli Please take care of this issue. We can discuss it together later. 😄

**Comment by jiasli** [comment]
Based on my understanding, according to https://docs.python.org/3.8/library/site.html

>This module (site) is automatically imported during initialization. 

> An executable line in a .pth file is run at every Python startup, regardless of whether a particular module is actually going to be used. 

[pywin32.pth](https://github.com/mhammond/pywin32/blob/master/pywin32.pth) contains 

```python
# .pth file for the PyWin32 extensions
win32
win32\lib
Pythonwin
# And some hackery to deal with environments where the post_install script
# isn't run.
import pywin32_bootstrap
```

So `win32`, `win32\lib` should be automatically added to `sys.path` and `pywin32_bootstrap` should be imported when Python is launched. 

When I run the python.exe installed by msi installer, `sys.path` already contains `win32`, `win32\lib`:

```
"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe"
>>> import sys
>>> sys.path
[
  ...,
  'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\lib\\site-packages\\win32', 
  'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\lib\\site-packages\\win32\\lib', 
  'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\lib\\site-packages\\Pythonwin'
]
```

I am not sure if these four lines are still necessary https://github.com/Azure/azure-cli/blob/6887c5badd7246fea1c4586e835224d39acfcc4e/src/azure-cli-telemetry/azure/cli/telemetry/__init__.py#L15-L22

@fengzhou-msft, could you please help verify this?

**Comment by fengzhou-msft** [comment]
I have verified that `pywin32.pth` is honored by the embeddable Python in MSI and we don't need these patch code now.
