### ISSUE TITLE
Error to create myResouceGroup myCluster

### ISSUE THREAD

**Issue by JasonVolney** [Azure/azure-cli#11617]
Hi, everybody!

When I tried to create a ResourceGroup running the following command it's happening this error. 

Please see the file .txt in attachment.  

Thanks for advance.

[Error to create myResouceGroup.txt](https://github.com/Azure/azure-cli/files/3981176/Error.to.create.myResouceGroup.txt)

**Comment by JasonVolney** [comment]
After new try I got it.

**Comment by JasonVolney** [comment]
Other errors related:

Azure:/
PS Azure:\> az aks list –o table
az: error: unrecognized arguments: –o table
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {aks} ...


PS Azure:\> **az aks install-cli**
Downloading client to "/usr/local/bin/kubectl" from "https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl"
Connection error while attempting to download client ([Errno 13] Permission denied: '/usr/local/bin/kubectl')

**Comment by lilyjma** [comment]
@Azure/aks-pm please take a look!

**Comment by navba-MSFT** [comment]
@JasonVolney Apologies for the late reply. This issue is open for quite sometime now. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by JasonVolney** [comment]
> @JasonVolney Apologies for the late reply. This issue is open for quite sometime now. Please let us know if you need any further assistance on this. Awaiting your reply.

Hi, @navba-MSFT Thanks you so much. But I don't need support for that no more.

**Comment by navba-MSFT** [comment]
@JasonVolney Thanks for your reply. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
