### ISSUE TITLE
az appconfig preview message interpreted as error by Powershell breaking azure devops pipelines

### ISSUE THREAD

**Issue by haymansfield** [Azure/azure-cli#11610]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
The az appconfig preview message is interpreted by powershell as an error which will kill Azure Devops pipelines.

**To Reproduce**
- task: AzureCLI@2
  inputs:
    azureSubscription:
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    scriptPath: '.\deploy.ps1'

With deploy.ps1 containing an az appconfig call.

**Expected behavior**
Should really work without workaround.

**Environment summary**
vmImage: 'windows-latest'

**Additional context**
Realise this is more of an Azure DevOps/Powershell issue, but is there some other way the preview could be signalled without causing the Powershell error.
Can be worked around using powerShellErrorActionPreference: 'continue' but this will mask other errors.

**Comment by shenmuxiaosen** [comment]
May I know what specific ```az appconfig``` command do you use in your powershell?

**Comment by haymansfield** [comment]
Here's an example:
az appconfig kv set --name $appConfigName --key "<key>" --value "<value>" --yes

**Comment by shenmuxiaosen** [comment]
As we are GA now, preview tags has been removed for most ```az appconfig ``` commands. So please just update the CLI version. The preview tags is not controlled by service team but CLI framework. @yonzhan Can you take a look?

**Comment by yonzhan** [comment]
Yes, preview tag is controlled by CLI framework. https://github.com/Azure/azure-cli/blob/dev/doc/onboarding_guide.md#preview-extensionmodule-to-ga-module

**Comment by jkewley** [comment]
This is a larger issue with the CLI. Writing preview notices to stderr causes `$?` to report `false` from `az` commands in both PowerShell 5 and PowerShell Core

**Comment by navba-MSFT** [comment]
@haymansfield Apologies for the late reply. This issue is open for quite sometime. Could you please let us know if you still need any assistance on this ?
