### ISSUE TITLE
Install documentation for apt fails to provide working signing key

### ISSUE THREAD

**Issue by szurcher** [Azure/azure-cli#11612]
**Describe the bug**
The install documentation for apt (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest) does not provide a working signing key for the azure cli repo.

**To Reproduce**
Follow the steps at the link provided in description. Both 'one command' and 'manual install' result in the same error when running `sudo apt update`:
```
W: GPG error: https://packages.microsoft.com/repos/azure-cli bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/repos/azure-cli bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**Expected behavior**
azure-cli should be installable using apt

**Environment summary**
apt / no azure-cli version installed / windows 10 / Bash on Windows (Ubuntu (bionic))

**Additional context**
The correct key and command to add it to apt can be found in this previous (closed) issue:
https://github.com/Azure/azure-cli/issues/6427#issuecomment-391805880
```
curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
```

**Comment by MyronFanQiu** [comment]
@fengzhou-msft Please take care of this issue.

**Comment by fengzhou-msft** [comment]
The second step in the instruction should install the key for you:
```
curl -sL https://packages.microsoft.com/keys/microsoft.asc | 
    gpg --dearmor | 
    sudo tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null
```

@szurcher Can you give me more details on how to setup your environment?

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please feel free to reopen this issue if it still exists for you.
