### ISSUE TITLE
az apim create fails when --enable-managed-identity is provided

### ISSUE THREAD

**Issue by thisisbrianstewart** [Azure/azure-cli#11614]
## Describe the bug

**Command Name**
`az apim create`

**Errors:**
```
'ApiManagementServiceResource' object does not support item assignment
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/cli/core/__init__.py, ln 490, in default_command_handler
    return op(**command_args)
cli/command_modules/apim/custom.py, ln 29, in create_apim
    resource['identity'] = ApiManagementServiceIdentity(type="SystemAssigned")
TypeError: 'ApiManagementServiceResource' object does not support item assignment
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az apim create --name apimname -g apimrg -l centralus --sku-name Developer --publisher-email pub@microsoft.com --publisher-name Microsoft --enable-managed-identity true`

## Expected Behavior

apim is created and a managed identity is created for it

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.78
azure-cli-ml 1.0.72.1

Extensions:
application-insights 0.1.1
azure-cli-ml 1.0.72.1
interactive 0.4.3

```

**Comment by thisisbrianstewart** [comment]
Any feedback here?

**Comment by dearsi-mocha** [comment]
I was having the same issue today.. I found a workaround https://dearsi-mocha.github.io/cloudsauce/2020/04/23/azure-apim-cli-woes/

**Comment by MikePennington** [comment]
This still seems to be an issue. Any update here?

**Comment by yonzhan** [comment]
API Management service team should look into this.

**Comment by pukauw** [comment]
This issue has been open since December 2019 and still doesn't appear to have been resolved, judging by my inability to deploy with a managed identity today. 

Is there any update or any plan to resolve this?

**Comment by navba-MSFT** [comment]
@thisisbrianstewart Apologies for the late reply. I was able to run the below command in azure cloud shell and it worked fine.

>***/Azure:~$ az apim create --name MyApim -g MyRG -l eastus --publisher-email [Myemail@contoso.com](mailto:Myemail@contoso.com) --publisher-name Contoso **--enable-managed-identity true**

More Info [here](https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest). Could you please test the same using [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) of AzCLI and let me know if you face any issues ? Awaiting your reply.
