### ISSUE TITLE
Taolam

### ISSUE THREAD

**Issue by buocnhay** [Azure/azure-cli#11619]
[Enter feedback here]
No

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9dc8c24-cda6-8672-8017-b66435eadbb7
* Version Independent ID: a0be523a-ff1f-18ed-0fc4-ba0e0befe4d1
* Content: [az appservice](https://docs.microsoft.com/en-us/cli/azure/appservice?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/appservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/_help.py)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by buocnhay** [comment]
Bấm

**Comment by MyronFanQiu** [comment]
@buocnhay Hello. Can you explain the problem you met in detail?

**Comment by panchagnula** [comment]
closing since there is no info here for this to be actionable
