### ISSUE TITLE
Issue with Display of export of activity log to Event Hub in portal

### ISSUE THREAD

**Issue by Garyhardy** [Azure/azure-cli#11611]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Following this command :

az monitor  log-profiles create --enabled true
--service-bus-rule-id '/subscriptions/*/Microsoft.EventHub/namespaces/*/RootManageSharedAccessKey' --locations $loc --categories "Write" "Action" "Delete"  --name MyLogProfile -l francecentral --days 1

When I type in cli : az monitor log-profiles list --subscription mysub
I can see 
servicebusruleid="/subscription/.../namespace/..."

is filled in meaning that the activity logs of my subscription is exported to my specified EventHub.

However from the portal, in subscription/Activity Logs/Diagnostic settings/
I see it blanck.
If I correct, I should see also here the name of my Event Hub.

**To Reproduce**
the description of the bug explains the issue to reproduce

**Expected behavior**
the description of the bug explains the expected issue.

**Environment summary**
CLI & portal

**Additional context**

**Comment by MyronFanQiu** [comment]
@Garyhardy Thanks. I need to investigate this issue.

**Comment by MyronFanQiu** [comment]
@Garyhardy I want to double-confirm the issue. Azure CLI is doing the right thing and you want the portal to show the same information. Is that correct?

**Comment by Garyhardy** [comment]
Yes you are correct.

**Comment by MyronFanQiu** [comment]
@Garyhardy Hello. Since this is the repo for Azure CLI. I'm not sure whether the correct person can see this issue or not. You can also open a ticket in the portal page.

**Comment by Garyhardy** [comment]
@MyronFanQiu thanks for your feedback. I have also open a ticket in the portal page.

**Comment by asheniam** [comment]
There is a new feature called subscription diagnostic settings released in Azure Portal to route Activity Logs to customer storage, customer EventHub, and Log Analytics.  This experience is currently in preview and over time, it will replace the existing log profile experience.  For created log profiles, you will need to refer to the legacy Portal experience described in the below link to view these.

For subscription diagnostic settings, today we don't have any first class PowerShell/CLI but we are working to publish a sample of ARM template for customers to use who want to automate this configuration.

https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-settings-legacy
