### ISSUE TITLE
Az eventgrid event-subscription show error - Invalid event subscription request: Supplied URL is invalid. It cannot be null or empty and should be a proper HTTPS URL like https://www.example.com.

### ISSUE THREAD

**Issue by matt-darwin** [Azure/azure-cli#11627]
**Describe the bug**
According to the [documentation](https://docs.microsoft.com/en-us/cli/azure/eventgrid/event-subscription?view=azure-cli-latest#az-eventgrid-event-subscription-show), when attempting to use az eventgrid event-subscription show, the 
--source-resource-id parameter should be provided as
```
/subscriptions/{SubID}/resourceGroups/{resourcegroup}/providers/microsoft.storage/storageaccounts/{storage account}
```

However, doing so returns the following error:-
`Invalid event subscription request: Supplied URL is invalid. It cannot be null or empty and should be a proper HTTPS URL like https://www.example.com.`

**To Reproduce**
Create an event grid subscription on an azure storage account.

Run the following in az cli in order to return the event grid source resource id, then use that to run the az eventgrid event-subscription show:-

```
eventtopic=$(az eventgrid event-subscription list --resource-group {your resource group} --query "[?name=='{your event subscription}'].topic" --output tsv)

az eventgrid event-subscription show --name {your event subscription} --source-resource-id $eventtopic
```

**Expected behavior**
The json object of the event subscription to be returned.

**Environment summary**
Linux-5.0.0-37-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.78

**Additional context**

**Comment by banisadr** [comment]
Hi @matt-darwin, looks like there's a missing required flag in your command. az eventgrid event-subscription list should also require --location in order to return a list of event subscriptions.

Trying this in az cli 2.0.80, adding that to your command does result in a full resource URI for a topic and plugging that into the show command also results in the full JSON payload of the event subscription. 

Moreover giving an invalid URI in the event-subscription show command with other properties valid results in the following correct error `The request did not have a subscription or a valid tenant level resource provider.`

I'm unable to reproduce your error with the above commands and adding location seems to resolve any issue.

**Comment by stu0292** [comment]
I'm getting a similar error message although it doesn't let me include the location parameter.  

The weird thing is I get the same error when using powershell Get-AzResource or az cli

Create an event grid system topic subscription (in this case for a Blob.Created event in Storage) and run the script below. I've copied the output from the az cli command using --debug (have skipped the middle part of the debug output)

Az CLI:
 "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",

Az.Resources:
Version              Name
-------              ----
6.5.2                Az.Resources    

Running from powershell in VSCode on Windows 10

# Script: 

$esubResource = Get-AzResource -ResourceId $id
'resource exists:'
$esubResource.Properties.filter.subjectBeginsWith

'trying to update the event subscription resource:'
$esubResource.Properties.filter.subjectBeginsWith = '/blobServices/default/'
$esubResource | Set-AzResource -Force

'same error if we use Az CLI:'
az resource update --ids $id --set properties.filter.subjectBeginsWith='/blobServices/default/'

'try with debug:'
az resource update --ids $id --set properties.filter.subjectBeginsWith='/blobServices/default/' --debug


# Output:

resource exists:
/blobServices/default/containers/uploads/blobs/



trying to update the event subscription resource:
Set-AzResource: C:\Users\...
Line |
  43 |  $esubResource | Set-AzResource -Force
     |                  ~~~~~~~~~~~~~~~~~~~~~
     | InvalidRequest : Invalid event subscription request: Supplied URL is invalid. It cannot be null or empty and should be a proper 
     | HTTPS URL like https://www.example.com. CorrelationId: ...


same error if we use Az CLI:
(InvalidRequest) Invalid event subscription request: Supplied URL is invalid. It cannot be null or empty and should be a proper HTTPS URL like https://www.example.com.
Code: InvalidRequest
Message: Invalid event subscription request: Supplied URL is invalid. It cannot be null or empty and should be a proper HTTPS URL like 
https://www.example.com.



try with debug:
cli.knack.cli: Command arguments: ['resource', 'update', '--ids', '/subscriptions/.../resourceGroups/.../providers/Microsoft.EventGrid/systemTopics/.../eventSubscriptions/...', '--set', 'properties.filter.subjectBeginsWith=/blobServices/default/', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []

...
...
...

cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/.../resourceGroups/.../providers/Microsoft.EventGrid/systemTopics/.../eventSubscriptions/...915eeac66?api-version=2022-06-15'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '1017'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '...'
cli.azure.cli.core.sdk.policies:     'CommandName': 'resource update'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--ids --set --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.38.0 (MSI) azsdk-python-azure-mgmt-resource/21.1.0b1 Python/3.10.5 (Windows-10-10.0.19045-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"topic": "/subscriptions/.../resourceGroups/.../providers/Microsoft.EventGrid/systemTopics/...", "provisioningState": "Succeeded", "destination": {"properties": {"endpointUrl": null, "endpointBaseUrl": "https://pm...azure.com:4443/triggerevent/BlobEventsTrigger/...", "maxEventsPerBatch": 1, "preferredBatchSizeInKilobytes": 64}, "endpointType": "WebHook"}, "filter": {"subjectBeginsWith": "/blobServices/default/", "subjectEndsWith": "", "includedEventTypes": ["Microsoft.Storage.BlobDeleted"], "advancedFilters": [{"values": ["CopyBlob", "PutBlob", "PutBlockList", "FlushWithClose", "DeleteBlob", "CreateFile", "DeleteFile"], "operatorType": "StringIn", 
"key": "data.api"}, {"value": 0.0, "operatorType": "NumberGreaterThan", "key": "data.contentLength"}]}, "labels": null, "eventDeliverySchema": "EventGridSchema", "retryPolicy": {"maxDeliveryAttempts": 30, "eventTimeToLiveInMinutes": 1440}}}
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/.../resourceGroups/.../providers/Microsoft.EventGrid/systemTopics/.../eventSubscriptions/...?api-version=2022-06-15 HTTP/1.1" 400 198
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '198'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': ''
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': ''
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'UKSOUTH:20230317T171212Z:e3fa54ad-7902-43ab-8bd3-3db702f33a59'        
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 17 Mar 2023 17:12:12 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InvalidRequest","message":"Invalid event subscription request: Supplied URL is invalid. It cannot be null or empty and should be a proper HTTPS URL like https://www.example.com."}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute      
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job     
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__     
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 240, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 452, in cached_put   
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 446, in _put_operation
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 1793, in update_resource
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 1793, in <listcomp>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3473, in update
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/resources/v2021_04_01/operations/_operations.py", line 9476, in begin_create_or_update_by_id
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/resources/v2021_04_01/operations/_operations.py", line 9418, in _create_or_update_by_id_initial
azure.core.exceptions.HttpResponseError: (InvalidRequest) Invalid event subscription request: Supplied URL is invalid. It cannot be null or empty and should be a proper HTTPS URL like https://www.example.com.
Code: InvalidRequest
Message: Invalid event subscription request: Supplied URL is invalid. It cannot be null or empty and should be a proper HTTPS URL like 
https://www.example.com.

cli.azure.cli.core.azclierror: (InvalidRequest) Invalid event subscription request: Supplied URL is invalid. It cannot be null or empty and should be a proper HTTPS URL like https://www.example.com.
Code: InvalidRequest
Message: Invalid event subscription request: Supplied URL is invalid. It cannot be null or empty and should be a proper HTTPS URL like 
https://www.example.com.
az_command_data_logger: (InvalidRequest) Invalid event subscription request: Supplied URL is invalid. It cannot be null or empty and should be a proper HTTPS URL like https://www.example.com.
Code: InvalidRequest
Message: Invalid event subscription request: Supplied URL is invalid. It cannot be null or empty and should be a proper HTTPS URL like 
https://www.example.com.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03E65148>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 3.981 seconds (init: 1.272, invoke: 2.709)
telemetry.save: Save telemetry record of length 3336 in cache
