### ISSUE TITLE
Poll more frequently for long running operations

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1162]
Currently the default polling interval for many long running operations is 30 seconds.

Should consider reducing this interval, maybe to 10 seconds.

**Comment by mayurid** [comment]
@derekbekoe : Is there any impact of reducing the interval other than potential gain we see? Also is 30s our default?

**Comment by derekbekoe** [comment]
Yes 30 seconds is the default from the SDK (and msrestazure) so we use that as is.
Here's an example from the Compute Client in the SDK - https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/compute_management_client.py#L45.

The downside to consider is that we'd be more likely to run into ARM API limits on the number of requests that can be made per hour.

e.g. If the polling interval is too short and a user tries to execute several long running operations concurrently (e.g. with multiple instances of the CLI), they'd be more likely to run into the API limit.

"For each subscription and tenant, Resource Manager limits read requests to 15,000 per hour and write requests to 1,200 per hour. **If your application or script reaches these limits, you need to throttle your requests.**"
from: https://azure.microsoft.com/en-us/documentation/articles/resource-manager-request-limits/

**Comment by johanste** [comment]
I assume that we are honoring any retry-after headers, correct? And that we only fall back to default values if no retry-after header is provided...

**Comment by derekbekoe** [comment]
Yes in `msrestazure/azure_operation.py`, class `AzureOperationPoller` there is the following:

```
def _delay(self):
        """Check for a 'retry-after' header to set timeout,
        otherwise use configured timeout.
        """
        if self._response is None:
            return
        if self._response.headers.get('retry-after'):
            time.sleep(int(self._response.headers['retry-after']))
        else:
            time.sleep(self._timeout)
```

By default, `self._timeout` is `30` seconds.

**Comment by JasonRShaver** [comment]
We should use 5 seconds instead of 10 per Murtaza (in reference to VM create).  

15k RPH = ~4 RPS, so this would eat about 5% of their hourly limit max, which seems reasonable.

**Comment by ravbhatnagar** [comment]
We should ideally fix all the instances where a <Retry-after> is not provided :). But in absence of that, yes 5 seconds seems reasonable for VM scenario. 

For template deployments, how does Python CLI handle polling for deployment status? Does it do a GET for each deployment operation every time it checks for status? If yes, then there are chances of folks running into the ARM throttle limits as the above calculation won't hold in that case. There are ways to get around this too but it will need some smart defaults. 

Also, have you thought about making this configurable by customers? That would be awesome. We can have default as 5 secs and based on the need it can be customized.

**Comment by yugangw-msft** [comment]
I am closing this bug as VM creation scenario has been addressed through linked PR
For suggestion of `making this configurable by customers` from @ravbhatnagar, Iet us open a separate bug, we either do it through a common command parameter or through an environment variable.
