### ISSUE TITLE
Powershell Install Instructions

### ISSUE THREAD

**Issue by isa56k** [Azure/azure-cli#11621]
The instructions to install AzureCLI.msi via powershell don't seem to work correctly?

Followed the instructions here:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest

Issued the following via ps prompt to install:
`Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'`

All appears to complete ok.

When tried to run az, I get the following:
`az : The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the     spelling of the name, or if a path was included, verify that the path is correct and try again.                         At line:1 char:1                                                                                                        + az                                                                                                                    + ~~                                                                                                                        + CategoryInfo          : ObjectNotFound: (az:String) [], CommandNotFoundException                                      + FullyQualifiedErrorId : CommandNotFoundException        `      

Closed CMD prompt and opened a new one, same result.

Manually installed the AzureCLI via the MSI that was downloaded in the previous command, run az and all works ok.

**Comment by MyronFanQiu** [comment]
@fengzhou-msft Could you take care of this issue?

**Comment by fengzhou-msft** [comment]
@isa56k Please start PowerShell as administrator and run the installation command, after installation just start another Powershell normally to run `az` command.

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please feel free to reopen this issue if it still exists for you.
