### ISSUE TITLE
az vm user update using VMAccessAgent version 2.0 instead of 2.4

### ISSUE THREAD

**Issue by axelgMS** [Azure/azure-cli#11626]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

az vm user update -u <user>-p <password> -n <VMName> -g <RGName>

this commands sends the following JSON template

_Invoking action VMExtensions.VMExtensionOperation.PUT(subscriptionId=<SubID>, resourceGroupName=<RGName>, vmName=<VMName>, extensionName=enablevmaccess, vmExtension={
  "location": "<location>",
  "properties": {
    **"autoUpgradeMinorVersion": false,**
    "provisioningState": 0,
    "publisher": "Microsoft.Compute",
    "type": "VMAccessAgent",
    **"typeHandlerVersion": "2.0",**
    "settings": {"UserName":"<user>"}
  }
})_

VMAccessAgent (Windows Extension) version 2.0 is pretty old and has a different behavior than latest version 2.4.5.

so the "az vm user update" command should use     **"typeHandlerVersion": "2.4",** and     **"autoUpgradeMinorVersion": true,**

**To Reproduce**

execute command from CLI
_az vm user update -u <user>-p <password> -n <VMName> -g <RGName>_

this will install version 2.0.2 in the VM

then if you run the same VMAccess extension from **Azure Portal**, you'll see

_Invoking action VMExtensions.VMExtensionOperation.PUT(subscriptionId=<SubID>, resourceGroupName=<RGName>, vmName=<VMName>, extensionName=enablevmaccess, vmExtension={
  "location": "<location>",
  "properties": {
    **"autoUpgradeMinorVersion": true,**
    "provisioningState": 0,
    "publisher": "Microsoft.Compute",
    "type": "VMAccessAgent",
    **"typeHandlerVersion": "2.0",**
    "settings": {"UserName":"<user>"}
  }
})_

so CRP will install latest version (currently 2.4.5) on the VM - which works fine.

**Expected behavior**

CLI should use      **"autoUpgradeMinorVersion": true,** instead of     "autoUpgradeMinorVersion": false,

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by yonzhan** [comment]
Issue triaged.

**Comment by qwordy** [comment]
PR to fix it: https://github.com/Azure/azure-cli/pull/12687

**Comment by yungezz** [comment]
the fix is released in Azure CLI latest 2.3.0. pls give a try and let us know if there's any other issue. Close the issue for now. Pls feel free to open new issue or reopen this one if any issue met.
