### ISSUE TITLE
.env file is included when deploying using az webapp up, different from extension behavior

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#11628]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
_"
Using the extension's version of zip deployment, the .env file is not included in the deploy.

I'm not sure this is the best behavior -- I believe it's one that the user should have a choice over. Regardless, the extension and az webapp up should exhibit the same behavior."_

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
"Could look into what the right behavior is here. I think it's best that az webapp excludes the .env file, but then this means we should have
a) an easy way to override this behavior (configure what files are skipped)
b) the CLI should offer an easy way to apply .env files as app settings (like the VS Code extension does)
c) the output should indicate which files are being skipped"

**Comment by panchagnula** [comment]
2.0.62 is an older version of Azure-cli we have had several updates/ fixes to az webapp up please use the latest 2.0.77 & let us know if you still see the issue.

**Comment by timja** [comment]
This is still an issue...
