### ISSUE TITLE
Required parameter 'storageAccountId' is missing (null).

### ISSUE THREAD

**Issue by jonathanclarke** [Azure/azure-cli#11625]
## Describe the bug

**Command Name**
`az snapshot create`

**Errors:**
```
Required parameter 'storageAccountId' is missing (null).
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az snapshot create --resource-group {} --name {} --location {} --source {} --output {} --tags {}`

## Environment Summary
```
Linux-4.19.0-041900-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.78

Extensions:
image-copy-extension 0.2.2

```

**Comment by jonathanclarke** [comment]
Resolved it by downgrading the azure-cli on Linux

sudo apt-get install azure-cli=2.0.72-1~bionic

**Comment by MyronFanQiu** [comment]
@qwordy Please take a look. There might be a regression.

**Comment by qwordy** [comment]
Hi Jonathan, Are you creating a snapshot by importing from a blob URI?

**Comment by jonathanclarke** [comment]
Downgraded and I was able to run the following command:

az image copy --source-resource-group staging --source-object-name
staging-image-4234234234 --target-location  westus2 --target-resource-group
"production" --cleanup

Basically was copying an image from one location to another, us-west to
us-west-2.

**Comment by qwordy** [comment]
I have reproduced this issue. It's a recent change of snapshot service. I also dislike this kind of breaking change. I will try to update image copy command to specify storageAccountId explicitly.

**Comment by qwordy** [comment]
image-copy 0.2.3 is released. It should fix this issue.
https://github.com/Azure/azure-cli-extensions/pull/1211
