### ISSUE TITLE
az postgres up: When creating a database, the printed connection string for Python wasn't useful

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#11632]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
"
When creating a database, the printed connection string for Python wasn't useful.

I ended up copying the information I needed from the Java/JDBC connection string instead.

(removed link)

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by yonzhan** [comment]
add to S164.

**Comment by Juliehzl** [comment]
Printed message during deployment.
```
Creating PostgreSQL Server 'server017526815' in group 'zuh'...
Creating PostgreSQL database 'sampledb'...
Checking your ip address...
Configuring server firewall rule, 'devbox', to allow for your ip address: 167.220.255.1
If PostgreSQL server declines your IP address, please create a new firewall rule using:
	 `az postgres server firewall-rule create -g zuh -s server017526815 -n {rule_name} --start-ip-address {ip_address} --end-ip-address {ip_address}`
Configuring server firewall rule, 'azure-access', to accept connections from all Azure resources...
Successfully Connected to PostgreSQL.
Ran Database Query: `CREATE USER root WITH ENCRYPTED PASSWORD 'Sampledb1'`
Ran Database Query: `GRANT ALL PRIVILEGES ON DATABASE sampledb TO root`
```

**Comment by yonzhan** [comment]
any feedback for this issue?

**Comment by nachoalonsoportillo** [comment]
@chenlomis Thanks for having created this issue. As of today, the JSON returned after the command executes successfully includes a connectionStrings nested object whose python attribute has a valid connection string to be used from Python, provided you've imported psycopg2 library.

**Comment by nachoalonsoportillo** [comment]
@yonzhan Please, close this issue. Thanks!
