### ISSUE TITLE
Reliability dashboard for az webapp (was: first time using az webapp up failed due to a regression in the CLI)

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#11630]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Failed with error:
AttributeError 'NoneType' object has no attribute 'resource_group'

It seems like the regression was fixed in CLI 2.0.75, and then potentially reintroduced.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
Related GitHub Issues:
(Nina filed) https://github.com/Azure/azure-cli/issues/10818
https://github.com/Azure/azure-cli/issues/10818#issuecomment-549204655
https://github.com/Azure/azure-cli/issues/10802
https://github.com/Azure/azure-cli/issues/10713
https://github.com/Azure/azure-cli/issues/11089

**Comment by panchagnula** [comment]
Please use 2.0.77 which is the latest & let us know if this still repros. Thanks!
