### ISSUE TITLE
 Magic .azure files created in my development environment during deploy

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#11634]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

During the deployment two magic files were created in my development environment — .azure and .deployment. These files didn't have comments or links to any documentation regarding what these files were for, what they contained, or if the options were configurable

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by panchagnula** [comment]
Running az webapp up configures local context for which is included in the .Azure files see https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-configure for more details.

Adding @btardif  as FYI.

**Comment by btardif** [comment]
We should add a comment to the content of the files with links to more info or explanation of what they are and what they are used for... re-opening this and assigning to me to come up with plan

**Comment by yonzhan** [comment]
move to S166.

**Comment by yonzhan** [comment]
@btardif any update for this issue?

**Comment by yonzhan** [comment]
move to S167

**Comment by chenlomis** [comment]
@yonzhan , @btardif and I just had a quick chat about this issue and the webapp team is suspecting that the magical .azure file is being created via the CLI rather than the az webapp up command. There's confusion on what this file is and how to make use of it. It'd be great if we could investigate and confirm on what's happening and the next steps

**Comment by yonzhan** [comment]
@Juliehzl please help to investigate the issue mentioned above.

**Comment by yonzhan** [comment]
move to S169

**Comment by btardif** [comment]
@chenlomis this is the same issue being discussed here: https://dev.azure.com/azuretracking/Azure%20tracking/_workitems/edit/680

**Comment by yonzhan** [comment]
add to S173

**Comment by jiasli** [comment]
`.azure` should be a **folder** instead of a **file**, created by Azure CLI as the configuration folder. 

https://github.com/Azure/azure-cli/blob/3b4d10d473a8d72dc2a1607478beb14424ce2004/src/azure-cli-core/azure/cli/core/_environment.py#L12

It is by-default created under the user's home folder, unless 

1. [`AZURE_EXTENSION_DIR`](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#cli-environment-variables) is set
2. `az configure --scope local` is used
3. `local-context` is turn on

`.deployment` seems to be created by `botservice`:

https://github.com/Azure/azure-cli/blob/9370ec21d5febcb0e7099f1a3969a42d04c4ceb1/src/azure-cli/azure/cli/command_modules/botservice/custom.py#L560

Please share the full deployment script for us to further analyze the issue.

**Comment by qubitron** [comment]
The deployment path used is here:
https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python?tabs=bash

This generates a .azure/config file with no comment explaining what it is for.

The `.deployment` file comes from VS Code deploy so that is a separate issue.

**Comment by jiasli** [comment]
We have a document [Azure CLI configuration](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest) explaining what `.azure/config` is. 

Indeed, we can put a comments in `.azure/config` explaining what it is. @yonzhan @achandmsft @chenlomis, any thoughts?

**Comment by chenlomis** [comment]
Sounds like a plan to me
Something along the lines of:" this is where your CLI configs are stored"
@qubitron that aligns with your proposal right?

**Comment by qubitron** [comment]
Yep something like "This file contains saved configurations for your CLI, read more at: aka.ms/1234".

We probably want an aka link in case we change where this points to.

**Comment by qubitron** [comment]
@jiasli @chenlomis should we re-open the issue?

**Comment by jiasli** [comment]
Created issue https://github.com/Azure/azure-cli/issues/15001 to track.
