### ISSUE TITLE
[Provider] Register command outputs invalid help text

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1163]
After running `az provider register`, it outputs the following text: `Registering is still on-going. You can monitor using 'az resource provider show -n <PROVIDER>'`.

However, `az resource provider show` isn't a valid command. Using `az provider show` works correctly, but I'm not sure whether that's the correct command. It would be great if the help text pointed you in the right direction.

**Comment by mayurid** [comment]
@yugangw-msft as fyi.
Thanks @lostintangent for reporting this.
