### ISSUE TITLE
az postgres up: created database doesn't have SSL enforcement turned on

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#11635]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
By default, the postgres database created with az postgres up doesn't have SSL enforcement turned on.

Combined with not offering SSL by default for deployed apps (See 682 By default, deployed web app is not SSL enabled

Active
) and allowing access from all Azure IPs as a default firewall setting this encourages insecure practices.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by yonzhan** [comment]
add to S164.

**Comment by Juliehzl** [comment]
Yes. For the simplest `az postgres up`, we don't enable SSL enforcement by design.
We will discuss if we need to enable it by default.
