### ISSUE TITLE
CLI help text for default LB & vm type documentation outdated

### ISSUE THREAD

**Issue by sxmon** [Azure/azure-cli#11642]
"Create a kubernetes cluster with default kubernetes version, default SKU load balancer(basic) and default vm set type(AvailabilitySet)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by sxmon** [comment]
October 15, 2019
Version 2.0.75

AKS
Changed --load-balancer-sku default value to standard if supported by the kubernetes version
Changed --vm-set-type default value to virtualmachinescalesets if supported by the kubernetes version

**Comment by jluk** [comment]
Thanks @sxmon for notifying us - we've logged this issue to be fixed.

Ticket reference: 5965921
