### ISSUE TITLE
Extend AzureFirewall Features (ThreatIntel Whitelisting and No SNAT)

### ISSUE THREAD

**Issue by b564518128** [Azure/azure-cli#11647]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
In backend, we are using key-value pairs called AdditionalProperties to extend AzureFirewall Features. However, in frontend, we would like to hide this generic field and expose specific fields to customer. Currently, we are adding two features: Threat Intelligence Whitelisting and No SNAT.

We will use Powershell interfaces as references to the wanted frontend config
1. Creating New AzureFirewall with New Features
```powershell
$tiwhitelist = New-AzFirewallThreatIntelWhitelist -IpAddress @("ip1", "ip2") -FQDN @("fqdn1", "fqdn2")
New-AzFirewall ... -ThreatIntelWhitelist $tiwhitelist -PrivateRange @("privateRange1", "privateRange2")
```

2. Setting New Features in Existing Firewall
```powershell
$fw = Get-AzFirewall -name "firewall" -ResourceGroupName "rg"
$fw.ThreatIntelWhitelist.IpAddress = @("ip1", "ip2")
$fw.ThreatIntelWhitelist.FQDN = @("fqdn1", fqdn2")
$fw.PrivateRange = @("privateRange1", "privateRange2")
Set-AzFirewall -AzureFirewall $fw
```

3. REST Request Body for the above two cases
```json
{
  ...
  "properties": {
    ...
    "additionalProperties": {
      "ThreatIntel.Whitelist.IpAddresses": "ip1, ip2",
      "ThreatIntel.Whitelist.FQDNs": "fqdn1, fqdn2",
      "Network.SNAT.PrivateRanges": "privateRange1, privateRange2"
    }
  }
}
```

**Minimum API Version Required**
2019-09-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/azureFirewall.json

**Target Date**
12/31/2019

**Comment by MyronFanQiu** [comment]
@b564518128 What's the validate values for PrivateRanges? I don't understand this field. Could you give more examples? Meanwhile, it's too close to target Date that we cannot make it. We put it in S164 plan.

**Comment by b564518128** [comment]
@MyronFanQiu
Valid values for PrivateRanges:
    1. Single Ips: "11.22.33.4", "222.21.44.55"
    2. Ip Prefixes denoted with slashes: "99.99.0.0/16", "23.44.55.0/24"
    3. a single special value "IANAPrivateRanges"
Valid values for ThreatIntel.Whitelist.IpAddresses:
    1. Single Ips: "11.22.33.4", "222.21.44.55"
Valid values for ThreatIntel.Whitelist.FQDNs:
    1. full fqdns: "www.microsoft.com", "www.google.com"
    2. fqdn wildcards with only "*" at the beginning: "*.microsoft.com", "*google.com"

**Comment by b564518128** [comment]
@MyronFanQiu The example given in the description are under PowerShell style. Please make it in CLI style when working on it. I am available for any questions.

**Comment by MyronFanQiu** [comment]
@b564518128 Thanks. This has been added into S164. I will sync with you later.
