### ISSUE TITLE
Need example to run CMD command on a Windows VM

### ISSUE THREAD

**Issue by para0056** [Azure/azure-cli#11645]
This would be incredibly helpful in automating the sysprep/generalize process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f04b196d-7d11-7213-f037-f12b85b19c52
* Version Independent ID: adc05d8e-b13b-134b-5f61-42aaf23666df
* Content: [az vm run-command](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@qwordy Please take a look.

**Comment by qwordy** [comment]
You can use `az vm run-command list` to list all available run commands for a subscription in a location.

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/run-command

I do not find CMD support. So just use PowerShell. It's very powerful.

**Comment by para0056** [comment]
Thanks for your response.
In light of this limitation, what is the recommended approach to invoking SYSPREP on a Windows VM using AzureCLI?

Thanks again for your time.

**Comment by qwordy** [comment]
You can run .bat file in PowerShell. And you can try `cmd /c`
https://stackoverflow.com/questions/24940243/running-cmd-command-in-powershell

**Comment by qwordy** [comment]
@para0056 Can you use SYSPREP now?

**Comment by para0056** [comment]
We're trying to do this in an Azure DevOps pipeline and we've got some work to do on our end before we can test it out.

**Comment by qwordy** [comment]
@para0056 Any update?

**Comment by para0056** [comment]
@qwordy We were able to get SYSPREP to work using an inline CMD script. Thanks!

**Comment by qwordy** [comment]
Glad to hear that!
