### ISSUE TITLE
az storage container create breaks when using none usable name parameter

### ISSUE THREAD

**Issue by dsk-1337** [Azure/azure-cli#11644]
## Describe the bug

**Command Name**
`az storage container create`

**Errors:**
```
The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:2dec212f-101e-0033-117b-b976bc000000
Time:2019-12-23T10:30:05.7682911Z</Message></Error>
Traceback (most recent call last):
pip-install-xo02umyl\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
...
RequestId:2dec212f-101e-0033-117b-b976bc000000
Time:2019-12-23T10:30:05.7682911Z</Message></Error>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

az login
`az storage container create --name {foo.bar.something} --account-name {} --account-key {}`

## Expected Behavior
The function should fail gracefully like az storage account create that fails with:
validation error: Parameter 'account_name' must have length less than 24.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.71 *

Extensions:


```

**Comment by Juliehzl** [comment]
Hi @dsk-1337, can you check first if your account name is less than 24? If yes and still have the error, please provide debug info with `--debug` in your command, which will help me figure out what happened.

**Comment by yonzhan** [comment]
Hi @dsk-1337, any update for this issue?
