### ISSUE TITLE
--full-uri parameter should return a fully encoded URI

### ISSUE THREAD

**Issue by elenaterenzi** [Azure/azure-cli#11643]
> ### `--full-uri` param in `az storage blob generate-sas` should return a fully encoded URI

**Describe the bug**
calling `az storage blob generate-sas` with the --full-uri param returns a non encoded URI.

**To Reproduce**
To reproduce easily you can use a blob with a name which contains spaces. Example:
 ```bash
#set your params
acct="mystorageaccount"
cnt="mytestcontainer"
blob="myfolder/file with spaces in name.txt"
end=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'

#issue command
az storage blob generate-sas --account-name $acct -c $cnt -n "$blob" --permissions r --expiry $end --https-o
nly --full-uri
```
the returned value will be:
```
"https://mystorageaccount.blob.core.windows.net/mytestcontainer/myfolder/file with spaces in name.txt?se=2019-12-23T10%3A08Z&sp=r&spr=https&sv=2018-11-09&sr=b&sig=omittedSAStoken"
```
>**Note 1**: SAS token here is replaced with "omittedSAStoken". 
>**Note 2**: There was **no problem with the SAS token**, it was **correctly encoded**. Only the blob URI (i.e. the text before the `?` sign) is **not correctly encoded**

**Expected behavior**
The expected result **should be a fully encoded URI** where spaces and other characters which would be illegal in a URI are instead correctly encoded as per below example:
```
"https://mystorageaccount.blob.core.windows.net/mytestcontainer/myfolder/file%20with%20spaces%20in%20name.txt?se=2019-12-23T10%3A08Z&sp=r&spr=https&sv=2018-11-09&sr=b&sig=omittedSAStoken"
```

**Environment summary**
CLI version: 2.0.78
OS version: Windows 10, Ubuntu 18.04 LTS
Shell Type: /bin/bash on WSL, /bin/bash on Ubuntu

**Comment by Juliehzl** [comment]
Hi @elenaterenzi, thanks a lot for your feedback.  `?` sign in sas url is designed in SDK level. But I wonder what the problem is with `?` sign in url.

**Comment by elenaterenzi** [comment]
As pointed in my feedback the problem is that the uri is not encoded and in particular the path to the blob is not encoded while the second part of the uri is chiediti encoded, so the full uri will not work/is not correct because of spaces in the uri (see the blob name, it has spaces as per my example above)


Sent from Outlook for Android
________________________________

**Comment by Juliehzl** [comment]
Verified current command behavior with "file 1.txt". The output is "https://zuhors1.blob.core.windows.net/test/file 1.txt?sv=2018-11-09&sr=b&sig=yIveRn2O5hWBXMeTFnF42Ryxox8ZOnWWNj3hIlxAahU%3D", which is the same as user reported.

**Comment by Juliehzl** [comment]
potential solution: 
- use urllib.parse.quote() to encode url.
- for both `blob url` and `blob generate-sas`
