### ISSUE TITLE
azure cli cannot work with https proxy 

### ISSUE THREAD

**Issue by medvedeffalexandr** [Azure/azure-cli#11654]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by bim-msft** [comment]
@medvedeffalexandr Please provide us a more detailed description, paste the error message at least.

**Comment by MyronFanQiu** [comment]
@bim-msft Hi. `Network` label represents `az network`. Since this issue is related with general azure cli, I add core instead.

**Comment by yonzhan** [comment]
add to S164.

**Comment by jiasli** [comment]
Please check the doc and see if you can be unblocked: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy
