### ISSUE TITLE
CLI command to provision a MariaDB Database

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-cli#11656]
**Is your feature request related to a problem? Please describe.**
Tracked issue in https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/3624302

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Juliehzl** [comment]
@selvasingh Can you provide more information for your feature request?

**Comment by ajlam** [comment]
We are still discussing the requirement for an "az mariadb db up" command given the usage of what we've seen for the existing "az mysql up" and "az postgres up" commands.

**Comment by ajlam** [comment]
Closing for long-term planning.

**Comment by ajlam** [comment]
Closing for long-term planning.
