### ISSUE TITLE
[App Service] Default table output for the "plan [list|show]" commands seems a little verbose

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1165]
Running `az appservice plan list` (or `az appservice plan show`), when using table output, results in output that seems a little verbose, and wraps even when my terminal is full screen:

<img width="1253" alt="screen shot 2016-10-25 at 4 48 30 pm" src="https://cloud.githubusercontent.com/assets/116461/19708386/067059a2-9ad3-11e6-8aca-7a9e65cde295.png">

Some of this metadata doesn't seem necessary to be displayed by default (e.g. subscription ID, "ServerFarmWithRichSkuName"), but I could be wrong. This is one of the cases where using JSON output + jq is actually more readable than the table output :)

As an aside, it seems kind of non-ideal that the default table displays `MaximumNumberOfWorkers`, but in order to see the current number of instances (as set via the `az appservice plan update` command), you need to view the JSON output.

**Comment by mayurid** [comment]
@lostintangent : did you try using the --query option with -o table?

**Comment by lostintangent** [comment]
@mayuri In this specific situation, I didn't, but that would be another good workaround. The JSON output and custom querying capabilities of the CLI definitely make for a really great experience, and provide the right "escape hatches" as necessary!

This issue definitely isn't blocking, but I wasn't sure whether it would be valuable to have a more curated default experience so that the first impression was nice and simple. In general, the app Service commands seem to output more verbose table data by default, so it also feels a little inconsistent with other commands. That's highly subjective though, so it's less an issue, and more just my initial impression.

**Comment by lostintangent** [comment]
Any thoughts on this? In general, is having a simple/curated default experience for table outputs a goal of the CLI? Or do you expect for users to need to rely on JSON output or custom queries in order to reduce noise?

**Comment by derekbekoe** [comment]
@lostintangent In general, our aim for table output was to be as automated/generated as possible. Currently, it picks the top-level attributes of objects (excluding things like ids as they're long and less useful in a table).
The thinking was that if users want specific columns/rows, a `--query` can be provided to get the exact table output you want.

Automated table output is preferred because in the future, the CLI will support multiple service API versions. These API versions could return different response objects. By making table output dynamic and automated, it would 'just work'.

There are commands where the default table format isn't useful so we've augmented these commands.
For example https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/commands.py#L36.

That was the reasoning but as always, we're open to feedback.

**Comment by lostintangent** [comment]
@derekbekoe That makes complete sense! Thanks for the explanation.

I guess my feedback here is related to the fact that in my mind, it would be great if the default table output for every command felt "curated" and actionable for the most common cases, with `-ojson` and `--query` being the escape hatches for additional needs. Some of the commands don't quite feel this way, but that might just be me.

**Comment by yugangw-msft** [comment]
I am fine with what we have. We can reopen if we have other user voices

**Comment by lostintangent** [comment]
@yugangw-msft How do you interpret #2333? In general, many of the default table outputs for Az CLI 2.0 feel like a non-curated data dump from a REST API, which IMO can feel pretty unpolished.

I don't feel particularly strongly about this specific issue (especially since I'm hoping we can create plans transparently anyways!), but the general philosophy of wanting the default output to be great seems like a reasonable goal to have.

**Comment by yugangw-msft** [comment]
I have commented #2333. This issue is a bit different because that one talks about too few fields, and this one is about too many & redundant fields, and it is not particular to table output. 
Either I am pruning away those fields, and now the default view has more sanities
```
Kind    Location      MaximumNumberOfWorkers  Name                  ResourceGroup    Status
------  ----------  ------------------------  --------------------  ---------------  --------
app     West US                            1  testplan45403-WestUS  clutst16342      Ready
app     West US                            1  testplan41547-WestUS  clutst35947      Ready
app     West US                            1  testplan70443-WestUS  clutst44215      Ready
```

**Comment by lostintangent** [comment]
@yugangw-msft That looks great! 👍
