### ISSUE TITLE
az deployment list missing filter which exists in REST API

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#11651]
**Is your feature request related to a problem? Please describe.**
CSS reported. Customer wants to use filter to query deployments.

REST API supports filter parameter to filter on ProvisionState
https://docs.microsoft.com/en-us/rest/api/resources/deployments/listatsubscriptionscope

CLI does not support the same
https://docs.microsoft.com/en-us/cli/azure/deployment?view=azure-cli-latest#az-deployment-list

**Describe the solution you'd like**
CLI should have `--filter` in `az deployment list`.

**Describe alternatives you've considered**
Use `--query` or `az rest` as a workaround.

**Comment by jiasli** [comment]
@Juliehzl Please help implement this feature.

**Comment by yonzhan** [comment]
add to S163.

**Comment by Juliehzl** [comment]
@zhoxing-ms Let's wait for Alex's feedback and then decide the next step to do. Please keep track of this.
