### ISSUE TITLE
CLI command to get connection info for a MariaDB Database

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-cli#11655]
**Is your feature request related to a problem? Please describe.**
Tracked feature request in https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/3728949

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Juliehzl** [comment]
@selvasingh Can you provide more information for your feature request?

**Comment by ajlam** [comment]
This API is linked to the "az mariadb up" command (#11656)

We are still discussing the requirement for an "az mariadb db up" command given the usage of what we've seen for the existing "az mysql up" and "az postgres up" commands.

**Comment by ajlam** [comment]
Closing this item and #11656 for long-term planning.
