### ISSUE TITLE
az group export: query/output parameters not supported

### ISSUE THREAD

**Issue by 0816KK** [Azure/azure-cli#11658]
The --Query switch is not working for the az group export command and either no information is available or all resource information in the resource group is displayed as a result.
Is there a way to modify --Query or get only specific resources (eg NSGs only)?

Same problem as below?
https://github.com/Azure/azure-cli/issues/5777

**Comment by bim-msft** [comment]
@Juliehzl Please take a look.

**Comment by yonzhan** [comment]
add to S165.

**Comment by 0816KK** [comment]
Is there an update for this issue?

**Comment by zhoxing-ms** [comment]
@0816KK Thanks for your feedback, I will submit a PR to fix it.
