### ISSUE TITLE
ERROR: az network application-gateway: 'waf-policy' is not in the 'az network application-gateway' command group.

### ISSUE THREAD

**Issue by CoderKooke** [Azure/azure-cli#11659]
I get the above error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738419fe-b1c0-c9d2-d012-790f6f77414f
* Version Independent ID: 51fa7a4f-8c26-d5dc-8c70-8c4507bc6f53
* Content: [az network application-gateway waf-policy custom-rule](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/waf-policy/custom-rule?view=azure-cli-latest#az-network-application-gateway-waf-policy-custom-rule-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bim-msft** [comment]
@MyronFanQiu Please take a look.

**Comment by MyronFanQiu** [comment]
@CoderKooke Can you run the command with `--debug` and paste the log here? Which platform and which terminal? Could you try `az network application-gateway waf-policy -h` to see if it works or not?

**Comment by haroldrandom** [comment]
Close as long time no response. 
Please feel feel to reopen if anything you want us to catch up. :)
