### ISSUE TITLE
CLI Support for Account Encryption Key use with Storage Tables and Queues

### ISSUE THREAD

**Issue by cbrooksmsft** [Azure/azure-cli#11663]
**Resource Provider**
What is the Azure resource provider your feature is part of?  

Microsoft.Storage

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.

We are adding support for use of the Account Encryption for the Tables and Queues service to enable the use of Customer Managed Keys with these services.  previously these services only used Microsoft managed encryption keys through he use of a shared service key.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

2019-06-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

https://github.com/Azure/azure-rest-api-specs-pr/pull/1045

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

Targeting for Jan 13 release

**Comment by bim-msft** [comment]
@Juliehzl Please take a look.

**Comment by yonzhan** [comment]
add to S163 with high priority.
