### ISSUE TITLE
Include Azure SQL Hyperscale create sample

### ISSUE THREAD

**Issue by gmsantos** [Azure/azure-cli#11662]
Hyperscale is a undocumented tier in documentation:

--edition --tier -e

The edition component of the sku. Allowed values include: Basic, Standard, Premium, GeneralPurpose, BusinessCritical.

Running list-editions command:

```
gabriel@Azure:~$ az sql db list-editions -l westus --query "[].name"
[
  "System",
  "Free",
  "Basic",
  "Standard",
  "Premium",
  "DataWarehouse",
  "Stretch",
  "GeneralPurpose",
  "BusinessCritical",
  "Hyperscale"
]
```
A example could also be included with other commom parameters:

Create a Hyperscale database with five read replicas
```
az sql db create -g mygroup -s myserver -n mydb -e Hyperscale --read-replicas 5
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bdd674-b454-e863-c943-9c979b466a92
* Version Independent ID: b15341f9-3f1b-00e0-a1c2-970f25a6ab03
* Content: [az sql db](https://docs.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#az-sql-db-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bim-msft** [comment]
@Juliehzl Please take a look.

**Comment by yonzhan** [comment]
Add service attention label since az sql is not owned by Azure CLI team.

**Comment by jaredmoo** [comment]
Thanks for the feedback! I can add the example and update the "allowed values include" text.
