### ISSUE TITLE
Az CLI resource graph Bug in PowerShell console host

### ISSUE THREAD

**Issue by ChendrayanV** [Azure/azure-cli#11668]
## Describe the bug
Issue in the below query 
```PowerShell
az graph query -q "where type =~ 'Microsoft.Compute/virtualMachines'" --include displayNames --first 5 --query "[?contains(subscriptionDisplayName,'STRING')]"
```
**Works fine in cmd prompt but not in PowerShell console host**
**Command Name**
``

**Errors:**
] was unexpected at this time.
C:\Solutions>  "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\\..\python.exe" -IBm azure.cli graph query -q "where type =~ 'Microsoft.Compute/virtualMachines'" --include displayNames --first 5 --query [?contains(subscriptionDisplayName,'STRING')]

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Expected Behavior
Should work like in AZ CLI host

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.74 *

Extensions:
log-analytics 0.1.3
resource-graph 1.0.0

```

**Comment by bim-msft** [comment]
@jiasli Please take a look.

**Comment by qianwens** [comment]
Hi @ChendrayanV , this is an issue in PowerShell, you can fix this issue by adding a space between ] and ", here is the correct command: az graph query -q "where type =~ 'Microsoft.Compute/virtualMachines'" --include displayNames --first 5 --query "[?contains(subscriptionDisplayName,'STRING')] "

**Comment by jiasli** [comment]
I didn't get error running this command, and CLI receives the argument correctly. 

```
> az graph query -q "where type =~ 'Microsoft.Compute/virtualMachines'" --include displayNames --first 5 --query "[?contains(subscriptionDisplayName,'STRING')]" --debug
Command arguments: ['graph', 'query', '-q', "where type =~ 'Microsoft.Compute/virtualMachines'", 
'--include', 'displayNames', '--first', '5', '--query', "[?contains(subscriptionDisplayName,'STRING')]", 
'--debug']
```

Could you share the real command? I doubt there may be special characters in `STRING`. 

We have a doc talking about quoting issues in PowerShell terminal: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues

**Comment by jiasli** [comment]
My Windows 10 is 1909 and has PowerShell Core installed:

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.3
PSEdition                      Core
GitCommitId                    7.0.0-rc.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

This issue doesn't occur on any of these versions. CLI receives the arguments correctly:

```
> az graph query -q "where type =~ 'Microsoft.Compute/virtualMachines'" --include displayNames --first 5 --query "[?contains(subscriptionDisplayName,'STRING')]" --debug
Command arguments: ['graph', 'query', '-q', "where type =~ 'Microsoft.Compute/virtualMachines'", 
'--include', 'displayNames', '--first', '5', '--query', "[?contains(subscriptionDisplayName,'STRING')]", 
'--debug']
```

While @qianwens's solution is correct for old versions of PowerShell, you may also update the Windows or PowerShell version to solve this. 

In addition, we have a doc talking about quoting issues in PowerShell terminal: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues
