### ISSUE TITLE
Client font color will be broken after pipeline and `findstr` command are used in Windows CMD

### ISSUE THREAD

**Issue by bim-msft** [Azure/azure-cli#11671]
**Describe the bug**
![微信截图_20191226160908](https://user-images.githubusercontent.com/3250203/71466287-15d7e880-27fa-11ea-9b30-f77296aef057.png)

**To Reproduce**
1. Run `az network private-endpoint list-types -l eastus2euap`
2. Then run `az network private-endpoint list-types -l eastus2euap | findstr vault`

**Environment summary**
azure-cli dev branch 93a50bb
knack 0.6.3

**Comment by bim-msft** [comment]
@jiasli Please take a look.

**Comment by jiasli** [comment]
Will be fixed by https://github.com/microsoft/knack/pull/181, https://github.com/Azure/azure-cli/pull/12604

**Comment by jiasli** [comment]
Duplicate of #6080

**Comment by jiasli** [comment]
This issue has been fixed. Please see https://github.com/Azure/azure-cli/issues/6080#issuecomment-763294594 for the solution.
