### ISSUE TITLE
Does this azure-cli support on-premises DevOps?

### ISSUE THREAD

**Issue by Wang-XiaoGao** [Azure/azure-cli#11672]
This azure-cli replace vsts cli, but I try many times and look for materials from internet. I could not confirm whether it could support on-premises DevOps 2019, not Azure at cloud.
Could anybody give me a confirm? Thanks a lot!

**Comment by bim-msft** [comment]
@Wang-XiaoGao Is this helpful? https://azure.microsoft.com/en-us/resources/videos/microsoft-azure-stack-azure-services-on-premises/

**Comment by yonzhan** [comment]
@Wang-XiaoGao  you can create an issue in below repo https://github.com/Azure/azure-devops-cli-extension. For questions, you can contact https://github.com/atbagga

**Comment by yungezz** [comment]
HI @Wang-XiaoGao Azure CLI supports Azure resources only, not on-premises services. You might want to contact Azure DevOps support to see how to manage on-premises instances. Will close the issue. let us know any other asks.
