### ISSUE TITLE
az provider registry help message is not working

### ISSUE THREAD

**Issue by lolodi** [Azure/azure-cli#1168]
![image](https://cloud.githubusercontent.com/assets/18540925/19742895/dae652ba-9b7b-11e6-811b-6059b1a7af5e.png)

If you run the help message command you get an error

**Comment by johanste** [comment]
Did you mean `az provider show`?

**Comment by mayurid** [comment]
@johanste : I believe the issue is that the help or the previous command az provider register says  "az resource provider show" which is misleading. @lolodi let us know if that's right?
Adding existing issue on this.

**Comment by johanste** [comment]
Ah, missed that little nugget 😃.

**Comment by lolodi** [comment]
@mayurid Correct!

**Comment by yugangw-msft** [comment]
This has been fixed #1176
