### ISSUE TITLE
`az bot create` is not idempotent

### ISSUE THREAD

**Issue by maxnorth** [Azure/azure-cli#11697]
**Describe the bug**
Calling 'az bot create' a second time returns an error instead of just returning the existing resource.

**To Reproduce**
1) Call `az bot create -n examplename -g examplegroup -k registration <...etc>` once. Request will succeed with newly created resource with the specified name in the specified resource group. No trouble so far.
2) Call `az bot create` a second time with the exact same arguments as in step 1. The request will fail with a message `Unable to create a bot with a name of "examplename".
Reason: The requested bot name is not available`

**Expected behavior**
Like other 'create' commands in the Azure CLI, I would expect this request to succeed the second time and simply return the json for the existing resource instead of trying to create a new one.

**Environment summary**
OS is Windows 10 Enterprise 1909
Installed via MSI installer
Versions:
azure-cli - 2.0.78

command-modules-nspkg - 2.0.3
core - 2.0.78
nspkg - 3.0.4
telemetry - 1.0.4

Extensions:
application-insights - 0.1.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory '~\.azure\cliextensions'

**Additional context**
N/A

**Comment by stevengum** [comment]
This is true @maxnorth, thank you for raising this issue! Per the [Command Guidelines](https://github.com/Azure/azure-cli/blob/4f89b707cc28658d41b38a1e03bb240894975f15/doc/command_guidelines.md#standard-command-types) `create` commands should be idempotent. I'll add this work to our planning for the upcoming sprints.

**Comment by stevengum** [comment]
Sorry for the delay in response! I'm planning on milestone [S164](https://github.com/Azure/azure-cli/milestone/81) for shipping this change.

**Comment by stevengum** [comment]
As indicated via GitHub, PR 11935 is out with a change that makes the `az bot create` command idempotent. This only affects the actual Azure Bot Service Resource itself, not any additional resources that may be spun up (e.g. App Service, App Service Plans).
