### ISSUE TITLE
az image copy generates error: "Required parameter 'storageAccountId' is missing (null)."

### ISSUE THREAD

**Issue by MisiekBest** [Azure/azure-cli#11713]
## Describe the bug

**Command Name**
`az snapshot create` as part of `az image copy`

**Errors:**
```
Required parameter 'storageAccountId' is missing (null).
```

## To Reproduce:
When I run `az image copy` in Azure cloud shell (bash) using this command:

```
az image copy --source-resource-group my-source-rg--source-object-name "my-image" --target-location westeurope --target-resource-group my-target-rg --target-subscription target_subscription_id --target-name "new_image_name" --cleanup
```

it generates the error:

```
Required parameter 'storageAccountId' is missing (null).
```

Screenshot: 
<img width="1269" alt="azcopy_problem" src="https://user-images.githubusercontent.com/14282144/71583523-25fc0a80-2b0f-11ea-8bb9-b0570bab9734.png">

## Environment Summary
```
Linux-4.15.0-1064-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.78

Extensions:
image-copy-extension 0.2.2

```

**Comment by MisiekBest** [comment]
Ok, sorry, looks like it's duplicated https://github.com/Azure/azure-cli/issues/11625

**Comment by MisiekBest** [comment]
I just want to confirm, that downgrading az cli to 2.0.72 on Windows helped me too.

**Comment by bim-msft** [comment]
@MisiekBest Yes, this is duplicated with #11625, we can go to the existing issue for further discussion, thanks.
