### ISSUE TITLE
I can't disable omsagent on running aks cluster

### ISSUE THREAD

**Issue by zielartgithub** [Azure/azure-cli#11728]
I want to remove omsagent and disconnect logs workspace from my AKS cluster. 
When I want to disable omsagent I have a following error:

## Describe the bug

**Command Name**
`az aks disable-addons`

**Errors:**
```
'omsagent'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.6/site-packages/six.py, ln 693, in reraise
    raise value
...
azure/cli/core/__init__.py, ln 490, in default_command_handler
    return op(**command_args)
cli/command_modules/acs/custom.py, ln 1828, in aks_disable_addons
    no_wait=no_wait
cli/command_modules/acs/custom.py, ln 2188, in _update_addons
    addon = ADDONS[addon_arg]
KeyError: 'omsagent'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks disable-addons -a {} -n {} -g {}`

## Environment Summary
```
Linux-4.15.0-1064-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.78

```
## Additional Context

part of command 
```az aks show -n prodCluster -g prod-aks
{
  "aadProfile": null,
  "addonProfiles": {
    "omsagent": {
      "config": {
        "logAnalyticsWorkspaceResourceID": "/subscriptions/***/resourcegroups/prod-aks/providers/microsoft.operationalinsights/workspaces/aksmonitor-10847902892197788931"
      },
      "enabled": true
    }
  },````
Kubernetes version 1.15.4

**Comment by palma21** [comment]
The name of the addon is "monitoring"  not "omsagent". Have you tried that?

**Comment by zielartgithub** [comment]
No, I haven't tried to disable monitoring. I use vm scale set with AKS. Will autoscaling work without monitoring feature disabled?

**Comment by palma21** [comment]
Sorry I'm a bit confused. What are you trying to do?

On the title and from the error I see you are trying to disable the omsagent aka monitoring.

On the CLI the command for that is `az aks disable-addons -a monitoring`

When you say autoscaling you mean Horizontal Pod Autoscaling or Cluster Autoscaling, none of this depends by default on Azure Monitor metrics, thought you can configure HPA to use custom metrics.

**Comment by zielartgithub** [comment]
This is an answer for my question. I will disable monitoring because Cluster Autoscaling not depends on Azure Metric by deafult.
