### ISSUE TITLE
[Breadth Coverage] Onboard Storage Sync Commands

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#11737]
**Spec Link**
https://microsoft.sharepoint.com/:w:/r/teams/AzureManagementExperience/_layouts/15/Doc.aspx?sourcedoc=%7B1737556B-6C09-4207-AB0D-CB20488190C1%7D&file=STORAGESYNC%20RP%20Speclet.docx&action=default&mobileredirect=true

**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.StorageSync

**Description of Feature or Work Requested**
Support Azure CLI commands for storage sync service

**Minimum API Version Required**
Microsoft.StorageSync 2019-06-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storagesync/resource-manager/Microsoft.StorageSync/stable/2019-06-01/storagesync.json

**Python SDK Link**
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-mgmt-storagesync

**Target Date**
02/18/2020

**Addtional context**
We'll use [autorest.cli](https://github.com/Azure/autorest.cli) from code gen team to auto-generate the code. We need provide the e2e tests for azure cli extension(also generated from swagger files). Also we need to verify the extensions can work well from user's perspective.

**Comment by yonzhan** [comment]
add to S164.
