### ISSUE TITLE
Unable to set up tab completion when installing azure-cli on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-cli#11740]
## Describe the bug

**Command Name**
`curl -L https://aka.ms/InstallAzureCli | sudo bash`

**Errors:**
===> Enter a path to an rc file to update (leave blank to use '/home/user/.bashrc'):
-- Backed up '/home/user/.bashrc' to '/home/user/.bashrc.backup'
-- Unable to set up tab completion. ERROR: 'encoding' is an invalid keyword argument for this function
-- Installation successful.
-- Run the CLI with /usr/local/bin/az --help

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Ubuntu 18.04.3 LTS (GNU/Linux 5.0.0-1027-azure x86_64)
- `curl -L https://aka.ms/InstallAzureCli | sudo bash`

## Environment Summary
```
Linux-5.0.0-1027-azure-x86_64-with-Ubuntu-18.04-bionic
Python 2.7.17
Shell: bash

azure-cli 2.0.78

```

**Comment by bim-msft** [comment]
@fengzhou-msft Please take a look.

**Comment by msglueck** [comment]
Same on macOS Mojave:
```
===> Enter a path to an rc file to update (leave blank to use '/Users/user/.bash_profile'): 
-- Backed up '/Users/user/.bash_profile' to '/Users/user/.bash_profile.backup'
-- Unable to set up tab completion. ERROR: 'encoding' is an invalid keyword argument for this function
-- Installation successful.
-- Run the CLI with /Users/user/bin/az --help
```
had to manually add the path to az and `source /Users/user/lib/azure-cli/az.completion` to my .bash_profile

**Comment by fengzhou-msft** [comment]
Issue caused by python 2 not supporting the encoding keyword argument in the [open ](https://github.com/Azure/azure-cli/blob/664c6940666e51488cef343c9c5fabf44fb991e9/scripts/curl_install_pypi/install.py#L248)function.

We're going to drop support for python 2. Instead of fixing it for python 2, I will make this script to use python 3 by default.

**Comment by fengzhou-msft** [comment]
BTW, we recommend using [APT](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest) to install azure-cli on Ubuntu and [Homebrew](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest) on MacOS.

**Comment by msglueck** [comment]
Yep, did use homebrew, but the error was exactly the same. Will retry with python alias pointing to python3. Thx!

**Comment by AbelHu** [comment]
@fengzhou-msft , thanks for the help. The script does not work now so I used pip3 to install azure_cli.
