### ISSUE TITLE
az vm extension set: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by Nilsas** [Azure/azure-cli#11748]
**Describe the bug**
When setting LinuxDiagnostic VM extension with command 
`az vm extension set --publisher Microsoft.Azure.Diagnostics --name LinuxDiagnostic --version 3.0 --resource-group $my_resource_group --vm-name $my_linux_vm`
I receive the following error:

**"Extension operation Enable failed:unsupported operand type(s) for +: 'NoneType' and 'str'"**

**To Reproduce**
`az vm extension set --publisher Microsoft.Azure.Diagnostics --name LinuxDiagnostic --version 3.0 --resource-group $my_resource_group --vm-name $my_linux_vm`

I've also tried passings settings suggested here: https://github.com/Azure/azure-linux-extensions/blob/master/Diagnostic/tests/lad_2_3_compatible_portal_pub_settings.json and received the same error

**Expected behavior**
Expected the command to finish successfully by adding the LinuxDiagnostic extension with default parameters provided here: https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_vm_diagnostics_templates.py

**Environment summary**
Install Method `choco install azure-cli` 
**CLI version (`az --version`)** 
```
azure-cli                         2.0.78

command-modules-nspkg              2.0.3
core                              2.0.78
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-devops                       0.8.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
```
**OS version**
```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
```

**Shell Type - Powershell**
```
PSVersion                      5.1.18362.145
PSEdition                      Desktop
```

**Additional context**
At first I had this issue with Terraform v0.12.16 until I realized that Az-CLI might have something to do with it

**Comment by bim-msft** [comment]
@qwordy Please take a look.

**Comment by kgopi05** [comment]
experiencing the same issue ..

**Comment by qwordy** [comment]
I tried your command
```
az vm extension set --publisher Microsoft.Azure.Diagnostics --name LinuxDiagnostic --version 3.0 --resource-group $my_resource_group --vm-name $my_linux_vm
```
I got a result of 
```
{
  "autoUpgradeMinorVersion": true,
  "forceUpdateTag": null,
  "id": "/subscriptions/***/resourceGroups/fytest2/providers/Microsoft.Compute/virtualMachines/vm1/extensions/LinuxDiagnostic",
  "instanceView": null,
  "location": "westus",
  "name": "LinuxDiagnostic",
  "protectedSettings": null,
  "provisioningState": "Succeeded",
  "publisher": "Microsoft.Azure.Diagnostics",
  "resourceGroup": "fytest2",
  "settings": null,
  "tags": null,
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "typeHandlerVersion": "3.0",
  "virtualMachineExtensionType": "LinuxDiagnostic"
}
```
Can you add a `--debug` to the end of this command and send the output here?
And how do you create the VM?

**Comment by qwordy** [comment]
Hello?

**Comment by Nilsas** [comment]
Alright, I've ran the same thing, although I've updated Az CLI since the original post
```
azure-cli                          2.1.0 *
command-modules-nspkg              2.0.3
core                               2.1.0 *
nspkg                              3.0.4
telemetry                          1.0.4
```

Now I've got a satisfactory result
```
{
  "autoUpgradeMinorVersion": true,
  "forceUpdateTag": null,
  "id": "/subscriptions/***/resourceGroups/vm-ext-test/providers/Microsoft.Compute/virtualMachines/vm-ext-test/extensions/LinuxDiagnostic",
  "instanceView": null,
  "location": "westeurope",
  "name": "LinuxDiagnostic",
  "protectedSettings": null,
  "provisioningState": "Succeeded",
  "resourceGroup": "vm-ext-test",
  "settings": null,
  "tags": null,
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "typeHandlerVersion": "3.0",
  "virtualMachineExtensionType": "LinuxDiagnostic"
}
```

I shall close this issue now.

**Comment by qwordy** [comment]
Very tricky.
