### ISSUE TITLE
CLI support for Wildcard Listener in Application Gateway

### ISSUE THREAD

**Issue by surajmb** [Azure/azure-cli#11743]
**What is the Azure resource provider your feature is part of?**

NRP

**Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.**

CLI support is needed to add wildcard hostnames in a listener of Application Gateway. This will add an additional parameter 'host-names' in 'az network application-gateway http-listener' command - https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/http-listener?view=azure-cli-latest. This parameter will be valid only for Application Gateway Standard_v2 and WAF_v2 SKUs. The validations in NRP are in place for the SKU verification.
This parameter takes values as an array of strings.

**What is the minimum API version of your service required to implement your feature?**

2019-09-01

**Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.**

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/applicationGateway.json

**If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.**

End of January 2020. The API is already out and we are working on PS and Portal, once done, we'll be targeting Public Preview.

**Comment by bim-msft** [comment]
@MyronFanQiu Please take a look.

**Comment by MyronFanQiu** [comment]
@surajmb Hello. Do you mean this filed? https://github.com/Azure/azure-rest-api-specs/blob/6e1747c9ae9975e78d04074eaf409d5a9ae6f32a/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/applicationGateway.json#L1544

**Comment by surajmb** [comment]
@MyronFanQiu It's in L1572 (HostNames)
https://github.com/Azure/azure-rest-api-specs/blob/6e1747c9ae9975e78d04074eaf409d5a9ae6f32a/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/applicationGateway.json#L1572

**Comment by MyronFanQiu** [comment]
@surajmb Thanks. I'm a little confused about hostName and hostnames. Since `az network application-gateway http-listener` already has one argument called `--host-name`, it might cause confusion to have another argument called `--host-names`. Can you share the designs of PS or portal? Is it ok to name it like `--wildcard-host-names`?

**Comment by surajmb** [comment]
@MyronFanQiu , this has been checked in to the swagger and PowerShell already. Please find the PRs below

Swagger Link: https://github.com/Azure/azure-rest-api-specs/pull/7453
PS Cmdlet: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/463
PS PR: https://github.com/Azure/azure-powershell/pull/10878

We already have plural arguments like "backendIPAddresses" and "backendFqdns" in backend pool configuration. We will publish documents on how to use the new parameter. The reason behind going for "hostNames" instead of "wildcardHostNames" is because it can take multiple non-wildcard hostnames as well. I guess it is okay to have --host-names as long we give clear instructions to the users on when to use which.

**Comment by MyronFanQiu** [comment]
@surajmb ok. I see.

**Comment by KarenHammons** [comment]
@yonzhan removing Service Attention label since this was internally opened.  @surajmb please close when we're able.
