### ISSUE TITLE
[Breadth Coverage] Onboard Azure StreramAnalytics Commands

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#11759]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
Support StreamAnalytics service.
https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftstreamanalytics

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
in S165.

**Comment by yungezz** [comment]
> in S165.

starts from S164.

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli-extensions/pull/1386
