### ISSUE TITLE
not able to create Auto scale Rule on Azure app service plan using cli

### ISSUE THREAD

**Issue by abhiramani-iptiq** [Azure/azure-cli#11754]
This command

az monitor autoscale rule create  --resource-group rgname \
--resource planname \
--resource-type 'Microsoft.Web/serverfarms' \
--autoscale-name test \
--profile-name 'Auto created scale condition' \
--condition "Percentage CPU > 75 avg 5m" \
--scale out 2

fails with error:The Resource 'microsoft.insights/autoscalesettings/test' under resource group rgname was not found.. [Code: "ResourceNotFound"]

I am really trying to create rule named test. why its looking for that resource?

**Comment by bim-msft** [comment]
@MyronFanQiu Please take a look.

**Comment by MyronFanQiu** [comment]
@abhiramani-iptiq Hello. autoscale rule is a sub-resource of autoscale. There is an argument `--autoscale-name` which is required. You should create a autoscale first by using `az monitor autoscale create`.

**Comment by MyronFanQiu** [comment]
Close this issue since no response. Feel free to re-open it or open a new issue if you still have any question or problem.
