### ISSUE TITLE
[Network] ExpressRoute - Missing Microsoft Peering settings

### ISSUE THREAD

**Issue by anzaman** [Azure/azure-cli#1175]
Cannot create Microsoft peering with the following command:
az network express-route circuit-peering create --circuit-name CLITestCircuit --peer-asn 111 --primary-peer-address-prefix 30.0.0.0/30 -g CLITest --secondary-peer-address-prefix 30.0.0.4/30 --vlan-id 552 --peering-type MicrosoftPeering --service-provider-name "Microsoft ER Test" --bandwidth-in-mbps 50 --peering-location Area51

Error:
The template deployment 'azurecli1477525782.360155645465' is not valid according to the validation procedure. The tracking id is '46a4f4d2-9cc0-404e-b15f-8d481d4f633f'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details. Microsoft Peering Config is not specified for Express Route Bgp Peering /subscriptions/97f32854-5b96-4c2e-af52-378713b34132/resourceGroups/CLITest/providers/Microsoft.Network/expressRouteCircuits/CLITestCircuit/peerings/MicrosoftPeering.

**Comment by JasonRShaver** [comment]
This is a blocking issue for network sign-off.

**Comment by tjprescott** [comment]
@anzaman is there a specific scenario you are following? It should help me to diagnose the problem. Are you able to create the Microsoft Peering using Xplat?

**Comment by tjprescott** [comment]
It looks like the command is just plain missing the configuration parameters needed for MicrosoftPeering.

**Comment by anzaman** [comment]
I am following the help text in the command itself, and provided all the parameters that were called for.  Infact, the help text does not even have a parameter for "AdvertisedPrefixes"

**Comment by anzaman** [comment]
There is no option for “AdvertisedPrefixes”.

-Ali

C:\Temp>az network express-route circuit-peering create  -h

Command
    az network express-route circuit-peering create: Create or update a virtual machine.

Arguments
    --bandwidth-in-mbps             [Required]: Bandwidth in Mbps of the circuit being created. It
                                                must exactly match one of the available bandwidth
                                                offers List ExpressRoute Service Providers API call.
    --circuit-name                  [Required]: Name of the ExpressRoute circuit.
    --peer-asn                      [Required]: The autonomous system number of the
                                                customer/connectivity provider.
    --peering-location              [Required]: Name of the peering location and not the ARM
                                                resource location. It must exactly match one of the
                                                available peering locations from List ExpressRoute
                                                Service Providers API call.
    --primary-peer-address-prefix   [Required]: /30 subnet used to configure IP addresses for
                                                interfaces on Link1.
    --resource-group -g             [Required]: Name of resource group.
    --secondary-peer-address-prefix [Required]: /30 subnet used to configure IP addresses for
                                                interfaces on Link2.
    --service-provider-name         [Required]: Name of the ExpressRoute Service Provider. It must
                                                exactly match one of the Service Providers from List
                                                ExpressRoute Service Providers API call.
    --vlan-id                       [Required]: Specifies the identifier that is used to identify
                                                the customer.
    --location -l                             : Location.
    --peering-type                            : BGP peering type for the Circuit.  Allowed values:
                                                AzurePrivatePeering, AzurePublicPeering,
                                                MicrosoftPeering.  Default: AzurePrivatePeering.
    --sku-family                              : Chosen SKU family of ExpressRoute circuit.  Allowed
                                                values: MeteredData, UnlimitedData.  Default:
                                                MeteredData.
    --sku-tier                                : Chosen SKU Tier of ExpressRoute circuit.  Allowed
                                                values: Premium, Standard.  Default: Standard.
    --tags                                    : Space separated tags in 'key[=value]' format. Use ""
                                                to clear existing tags.

Global Arguments
    --debug                                   : Increase logging verbosity to show all debug logs.
    --help -h                                 : Show this help message and exit.
    --output -o                               : Output format.  Allowed values: json, jsonc, list,
                                                table, tsv.  Default: json.
    --query                                   : JMESPath query string. See http://jmespath.org/ for
                                                more information and examples.
    --verbose                                 : Increase logging verbosity. Use --debug for full
