### ISSUE TITLE
[Breadth Coverage] Onboard Azure Blueprints Commands

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#11758]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
Support azure services:  Azure Blueprints. https://github.com/Azure/azure-rest-api-specs/tree/2f48d306ba63a7ea3c19bd122a274dc465a84e4c/specification/blueprint/resource-manager/Microsoft.Blueprint

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
in S164.

**Comment by yungezz** [comment]
release of this RP is holding off since open questions on RP. will resume until go signal. move to backlog.

**Comment by thisisbrianstewart** [comment]
Hi @yungezz and @yonzhan -- any updates or timeline on this?  Would love to build this into our cli-based pipelines and automation rather than using powershell to cover the gap temporarily.

**Comment by yungezz** [comment]
HI @thisisbrianstewart we're pending on some internal sanity check for this RP. Roughly estimation it would be ready around end of March. Let us know there's any other question.

**Comment by zaluznoi** [comment]
Hi @fengzhou-msft  was it ever delivered? cannot find any reference to blueprint related changes.

**Comment by fengzhou-msft** [comment]
> Hi @fengzhou-msft was it ever delivered? cannot find any reference to blueprint related changes.

Yes. Please install azure-cli 2.3.1 to add the blueprint extension. Reference doc is [here](https://docs.microsoft.com/en-us/cli/azure/ext/blueprint/blueprint?view=azure-cli-latest).
