### ISSUE TITLE
AKS addons dashboard enable failed

### ISSUE THREAD

**Issue by noaheh** [Azure/azure-cli#11768]
## Describe the bug

Attempting to enable dashboard, which appears to be disabled by default, generates the traceback

**Command Name**
`az aks enable-addons`

**Errors:**
```
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 654, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/acs/custom.py, ln 1845, in aks_enable_addons
    _ensure_container_insights_for_monitoring(cmd, instance.addon_profiles['omsagent'])
cli/command_modules/acs/custom.py, ln 2488, in _ensure_container_insights_for_monitoring
    if 'loganalyticsworkspaceresourceid' in addon.config:
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Build new AKS cluster deployed according to Terrafrom guide here:
https://www.hashicorp.com/blog/kubernetes-cluster-with-aks-and-terraform/

- _Put any pre-requisite steps here..._
- `az aks enable-addons --addons kube-dashboard --resource-group TESTAKS --name azure-k8s-cluster1`

## Expected Behavior
Expected to have addon enabled

## Environment Summary
```
WSL on Win 10 1809 build 17763.864
Linux-4.4.0-17763-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77 *

```

**Comment by jluk** [comment]
Related to #11456

**Comment by jluk** [comment]
We believe a fix has been made, please reference this issue for the latest tracking. I am going to close this to consolidate info to one thread. If you still hit issues after the S166 milestone release, feel free to recomment.

https://github.com/Azure/azure-cli/issues/11456
