### ISSUE TITLE
Az tag delete/ remove-value fails to remove tags 

### ISSUE THREAD

**Issue by vinoth-cyber90** [Azure/azure-cli#11761]
Hi Team, 

Az tag delete/ remove-value fails to remove tags from the subscription. 

Do we have any commands to remove the tags from the resource and resource group level using Azure CLI bash.  

Please find the details below 

vinoth@Azure:~$ az tag remove-value --name Env --value stage1 --subscription vinoth
The tag cannot be deleted. It is associated to one or more resources. Tag name 'Env' and tag value 'stage1'.

vinoth@Azure:~$ az tag delete --name Env --subscription vinoth
The tag name 'Env' cannot be deleted. It is associated to one or more resources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9984dc8-c276-354c-6c40-db77fad8e7cc
* Version Independent ID: f785cf84-06f2-946e-c8c6-c2a227394335
* Content: [az tag](https://docs.microsoft.com/en-us/cli/azure/tag?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bim-msft** [comment]
@zhoxing-ms Please take a look.

**Comment by zhoxing-ms** [comment]
Because the tag you want to delete is bound to some resources, you cannot delete it directly with `az tag` command. Maybe you can try to delete tags that is bound to some resources in the following ways
resource level:  `az group update --tags {NewTags}`
resource group level:  `az resource tag --tags {NewTags}`

**Comment by zhoxing-ms** [comment]
@vinoth-cyber90 Do you still have any other questions?

**Comment by vinoth-cyber90** [comment]
Thanks Xing..

No more queries related to this topic
