### ISSUE TITLE
[Breadth Coverage] Onboard Azure LightHouse Commands

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#11760]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
Support Azure Lighthouse service
https://docs.microsoft.com/en-us/azure/lighthouse/

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
in S164.

**Comment by yungezz** [comment]
so far besides cross tenant support, nothing need to be done for LightHouse.  Close it for now, will reopen if get new requirements.
