### ISSUE TITLE
AKS - Cant browse to dashboard and enable-addons dashboard fails

### ISSUE THREAD

**Issue by balajivenkataraman** [Azure/azure-cli#11770]
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
The Resource 'Microsoft.ContainerService/managedClusters/aks_dev' under resource group 'RG-vNet-HUB-01' was not found.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.76 *

```

**Comment by jluk** [comment]
The error is stating you have specified a cluster in an RG that does not exist. Please review the command that it is referencing existing objects.
