### ISSUE TITLE
CLI support for New Vpn gateway Generations

### ISSUE THREAD

**Issue by ritwikbasu** [Azure/azure-cli#11772]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.Network

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
https://github.com/Azure/azure-rest-api-specs/pull/7089 

This PR introduces a new optional parameter **vpnGatewayGeneration** with possible values of "None", "Generation1" and "Generation2". This PR also introduces new SKUs that can be used to create VPN gateways. Although the new SKU options are available in the latest CLI, the new optional parameter is not available. 

We need to expose this optional parameter for the "az network vnet-gateway create" command.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2019-07-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
https://github.com/Azure/azure-rest-api-specs/pull/7089

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates, it will help us prioritize your request against other requests.

This feature was released as part of Ignite and users have been asking for CLI support. Please prioritize this request accordingly.

**Comment by bim-msft** [comment]
@MyronFanQiu Please take a look.

**Comment by yonzhan** [comment]
add to S165.

**Comment by jsntcy** [comment]
add optional parameter `--vpn-gateway-generation` for `az network vnet-gateway create` command

**Comment by jsntcy** [comment]
Close this issue as it is resolved by #12740 (PR)
