### ISSUE TITLE
az keyvault set-policy: Requesting for an optional parameters as required

### ISSUE THREAD

**Issue by MauricioP92** [Azure/azure-cli#11771]
As per this documentation, for az keyvault set-policy command, the --resource-group -g parameter should be optional, but for customer it's returning an error asking for this parameter as a required parameter in order to accept the command.
Using the latest version of CLI 2.0.78.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226e5769-f6c8-a480-db78-727fb96348ec
* Version Independent ID: 8ee06a2a-6eda-11be-3c8e-6ad948be207e
* Content: [az keyvault](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az-keyvault-set-policy)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bim-msft** [comment]
Thanks for your feed back, working on it.

**Comment by bim-msft** [comment]
@MauricioP92 Hi, I just cannot reproduce this scenario. For me, the `--resource-group-id` is always not required when you specify the parameter `--vault-name` or `-n`, here is my screenshot:
![image](https://user-images.githubusercontent.com/3250203/71801075-ca90c600-3094-11ea-9062-bc0cdd65370d.png)

I'm using the same version as yours:

```
bim@Azure:~$ az --version
azure-cli                         2.0.78

command-modules-nspkg              2.0.3
core                              2.0.78
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/bim/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Dec 12 2019, 11:11:32)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal
```

Could you please share your detailed error message?

**Comment by MauricioP92** [comment]
Hi, I am also able to reproduce this without issues but my customer is receiving the following error message: "Microsoft.KeyVault/vaults/KVname not found within subscription" when doing it from PowerShell and "Resource group RGname could not be found" when he does it from the Azure Portal CLI. The thing is this resource group was deleted about two months ago and for some reason it's still pointing to an inexistent resource group.

**Comment by bim-msft** [comment]
@MauricioP92 You mean the Key Vault can be accessed but its resource group was deleted long time ago?
For the normal case (the vault and its resource group are both exist), you don't have to specify `--resource-group` or `-g`, it's optional.

**Comment by bim-msft** [comment]
@MauricioP92 If there are any updates on your side, please feel free to share with us, thanks.

**Comment by bim-msft** [comment]
Issue closed, feel free to reopen it if necessary.

**Comment by bim-msft** [comment]
@MauricioP92 Hi, we figured out the root cause recently:
For key vault commands, `-n {vault_name} -g {rg}` is case insensitive, `-n {vault_name}` is case sensitive.
For instance, you created a vault named `kvTest`, and you queried it by name `kvtest`

`az keyvault show -n kvtest`: "Microsoft.KeyVault/vaults/KVname not found within subscription"
`az keyvault show -n kvTest`: works fine
`az keyvault show -n kvtest -g myrg`: works fine
