### ISSUE TITLE
get_raw_token should take tenant name/id as input

### ISSUE THREAD

**Issue by mit2nil** [Azure/azure-cli#11780]
Current interface as shown below takes only subscription and resource as inputs. However, auth token are specific to a tenant and not a subscription. Lack of tenant input also complicates design for scenarios requiring auth token for tenants with no subscription. 

`def get_raw_token(self, resource=None, subscription=None):`

**Comment by bim-msft** [comment]
@jiasli Please take a look.

**Comment by yonzhan** [comment]
add to S165.

**Comment by mit2nil** [comment]
> add to S165.
@jiasli @yonzhan Is it possible to pull this into S164?

**Comment by yonzhan** [comment]
@mit2nil  add to S164.
