### ISSUE TITLE
az acr create lists service principal actions with inconsistent parameter names

### ISSUE THREAD

**Issue by SajayAntony** [Azure/azure-cli#1178]
az acr create -l <location>-n <MYAPP> -g <MYAPP>

returns
az ad sp create-for-rbac --scopes /subscriptions/<subscription>/resourcegroups/<MYAPP>/providers/Microsoft.ContainerRegistry/registries/<MYAPP> --role Owner --secret <passwo
rd>
az role assignment create --scope /subscriptions/<subscription>/resourcegroups/<MYAPP>/providers/Microsoft.ContainerRegistry/registries/<MYAPP> --role Owner --assignee <app-
id>

However, calling
az ad sp create-for-rbac --scopes /subscriptions/<subscription>/resourcegroups/<MYAPP>/providers/Microsoft.ContainerRegistry/registries/<MYAPP> --role Owner --secret bikeshare
Returns:
Client_id                             Sp_name                               Client_secret    Tenant
------------------------------------  ------------------------------------  ---------------  ------------------------------------
<CLIENTID>                   http://<something>  bikeshare        

Our helper text says app-d, however az ad sp create returns Client_Id, sp_name, Client_secret, ...

I then tried az ad sp list - which never returned https://github.com/Azure/azure-cli/issues/1150
Possibly provide help for calling az ad sp show --id <ID>

/cc @djyou

**Comment by djyou** [comment]
@yugangw-msft As specified in Graph API's spec, `AppId` should be the right name (or Application ID as used in the portal) rather than `Client id`. `Key` is the right name rather than `Client secret`. It has been rather confusing to the users. I would prefer if the output can retain the original property names returned by the server rather than rename them to the ones people may not be familiar with.
```
{
  "appId": "",
  "displayName": "",
  "objectId": ",
  "objectType": "ServicePrincipal",
  "servicePrincipalNames": [
    "",
    ""
  ]
}
```

**Comment by yugangw-msft** [comment]
Portal uses `Client Id`

**Comment by djyou** [comment]
![image](https://cloud.githubusercontent.com/assets/3630974/19785669/22af0636-9c4f-11e6-98ee-32936b963f41.png)

**Comment by djyou** [comment]
![image](https://cloud.githubusercontent.com/assets/3630974/19785687/3da11434-9c4f-11e6-9cf7-a829e40e5998.png)
Or `APP ID` in properties blade.

**Comment by djyou** [comment]
So is the spec
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-graphrbac/1.6/swagger/graphrbac.json#L2153

**Comment by yugangw-msft** [comment]
Could you share out the steps of how to get to you snapshot? I was talking about the classic portal which lots of walkthroughes, say [this one](https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-service-principal-portal/),  uses to show people how to create service principal to login. 
The `create-for-rbac` created the SP for people for login through the client id and secret flow. So using the client id and secret wording is more closely connected to the next step.  Remember these 2 words are commonly used in oauth flow which the `login` goes through. Check out the [API](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/adal/authentication_context.py#L127)  
So azure-cli doesn't cause the confusions from the start , rather it picks the less worse.
Of course, I can consider to changing, but the justification should be scenario driven, rather from the graph apis, which existed decades ago and originally was from ADFS, not for RBAC
![image](https://cloud.githubusercontent.com/assets/6014209/19785831/e2c9364e-9c4f-11e6-960b-6d0bf4244794.png)

**Comment by djyou** [comment]
I was looking at the new portal Azure Active Directory extension. The inconsistency is from the fact that the result of `az ad sp show --id` shows `AppId` while `create-for-rbac` shows `Client_id`. Either name would work for us, but after `create-for-rbac`, the user won't see `Client_id` again from `az ad sp list` or `az ad sp show`.

**Comment by yugangw-msft** [comment]
I can add a new field of `appid` in the output with same value with `client_id`. We probably can't just rename it. `client_id` is also a well known concept like i mentioned earlier

**Comment by SajayAntony** [comment]
@yugangw-msft either way we just want to be consistent. I guess the fact that CLIENT_ID was not used in the new portal might indicate that it the new name. Either way given that our service is preview we can pick up what ever is you recommend provided it is consistency.

**Comment by yugangw-msft** [comment]
Let me just switch to appId then.  I will take this bug.

**Comment by JasonRShaver** [comment]
merged
