### ISSUE TITLE
While getting Azure File Shares

### ISSUE THREAD

**Issue by dhbl-in** [Azure/azure-cli#11788]
## Describe the bug

**Command Name**
`az storage share list`

**Errors:**
```
HTTPSConnectionPool(host='nq2cyclecloudrgdiag.file.core.windows.net', port=443): Max retries exceeded with url: /?comp=list&maxresults=5000 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x07A65550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Traceback (most recent call last):
pip-install-q_27sn_r\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 57, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage share list --account-name {} --account-key {}`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.71 *

```

**Comment by bim-msft** [comment]
@Juliehzl Please take a look.

**Comment by yonzhan** [comment]
add to S165.

**Comment by qianwens** [comment]
@dhbl-in , it seems CLI failed to resolve the host name nq2cyclecloudrgdiag.file.core.windows.net. Is there any network proxy configured in your network?
