### ISSUE TITLE
'NoneType' object is not iterable on az aks list

### ISSUE THREAD

**Issue by yonatan-shorani** [Azure/azure-cli#11781]
## Describe the bug

**Command Name**
`az aks list`

**Errors:**
```
'NoneType' object is not iterable
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.7/site-packages/six.py, ln 696, in reraise
    raise value
...
azure/cli/core/__init__.py, ln 490, in default_command_handler
    return op(**command_args)
cli/command_modules/acs/custom.py, ln 1899, in aks_list
    return _remove_nulls(list(managed_clusters))
cli/command_modules/acs/custom.py, ln 3043, in _remove_nulls
    for ap_profile in managed_cluster.agent_pool_profiles:
TypeError: 'NoneType' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks list`

## Environment Summary
```
Darwin-19.2.0-x86_64-i386-64bit
Python 3.7.6
Shell: bash

azure-cli 2.0.78

```

**Comment by jluk** [comment]
Looking into this.

Pasting CLI lines reported in error:
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/custom.py#L3043

**Comment by jluk** [comment]
As mentioned we are looking into this, replying so the bot sees our ack.

**Comment by jluk** [comment]
A fix has been made, please reference this issue for the latest tracking. I am going to close this to consolidate info to one thread.

https://github.com/Azure/azure-cli/issues/11456
