### ISSUE TITLE
Add support for Azure CDN Rules Engine

### ISSUE THREAD

**Issue by jjinxn** [Azure/azure-cli#11789]
**Is your feature request related to a problem? Please describe.**
Some of our sites need custom headers to be set. At the moment we are using Rules Engine in CDN profiles to achieve that. This is manual and time consuming. A much better option would be for Azure CLI to support controlling rules engine from the code.

**Describe the solution you'd like**
We would like az to support rules engine so that we can add custom rules for particular endpoints from the code. This would help to automate creating rules during the deploy time.

**Describe alternatives you've considered**
Setting rules manually through Azure Portal. Alternatively, we tried PowerShell but there are some bugs that [prevent ](https://github.com/Azure/azure-powershell/issues/10846) us from doing it.

**Comment by hytao** [comment]
I'm working on RulesEngine for Azure CLI. The changes has been approved and will be checked in soon.

**Comment by hytao** [comment]
The CLI support for Azure CDN rules Engine is in place. Please close this issue.
