### ISSUE TITLE
az network nic ip-config lacks information

### ISSUE THREAD

**Issue by stevenkaras** [Azure/azure-cli#11783]
## Describe the bug

**Command Name**
`az network nic ip-config show`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network nic ip-config show --ids {}`

## Expected Behavior

A fair assumption is that a command that displays information regarding a resource will include sufficient information to recreate that resource. Specifically, no identifying information about the NIC for the given ip-configuration is included in the output. This means that given a public IP, the only way to find the NIC attached is to filter the list of NICs in the resource group for the one with the the same IP config as the public IP. This runs slowly for resource groups with several hundred IPs and NICs.

## Environment Summary
```
Linux-4.15.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
Python 2.7.12
Shell: bash

azure-cli 2.0.64 *

```

**Comment by MyronFanQiu** [comment]
@stevenkaras Hello. Which kind of identifying information do you want? Do you mean resource id of this NIC?

**Comment by MyronFanQiu** [comment]
@stevenkaras If you want to get NIC for a public ip, could you try `az public-ip show`?

**Comment by stevenkaras** [comment]
@MyronFanQiu the resource id of the NIC associated with the ip configuration would be ideal so it's possible to discover the specific NIC without needing to list all the NICs in a resource group.

The output of `az network public-ip show` does not include the NIC, only the ip configuration.

**Comment by yonzhan** [comment]
add to S167

**Comment by jsntcy** [comment]
@stevenkaras, when you run the either `az network nic ip-config show`  or `az network public-ip show`, the response will include  `"id": "/subscriptions/test-sub/resourceGroups/test-rg/providers/Microsoft.Network/networkInterfaces/nic-name/ipConfigurations/ipconfig1"` and `/subscriptions/test-sub/resourceGroups/test-rg/providers/Microsoft.Network/networkInterfaces/nic-name` is the NIC id, is it enough for you?

**Comment by stevenkaras** [comment]
@jsntcy Is the ID format fully stable and intended for use in that manner? Are you willing to commit to that stability?

If so, where is the ID format documented? If Azure partners with a thirdparty provider of cloud compute or networking, how will it show up in the ID format? Will it follow the exact same format as your ids, or will it be per-provider?

**Comment by jsntcy** [comment]
> @jsntcy Yu Chen FTE Is the ID format fully stable and intended for use in that manner? Are you willing to commit to that stability?
> 
> If so, where is the ID format documented? If Azure partners with a thirdparty provider of cloud compute or networking, how will it show up in the ID format? Will it follow the exact same format as your ids, or will it be per-provider?

Yes, I think the ID format is fully stable as it conforms to Azure Resource Manager schema. You can find the resource id format in https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-resource#return-value-5

Even if a third-party provider, it should also conform to Azure Resource Manager schema as all traffic will be through ARM service.

**Comment by jsntcy** [comment]
@stevenkaras, did you have a chance to take a look at my comments?

**Comment by stevenkaras** [comment]
@jsntcy I have not had a chance until now due to other more urgent work.

That should be sufficient, but an explicit response for nested resources would be easier to discover.

**Comment by jsntcy** [comment]
It's not a reasonable way to add another explicit id for nested resource as it is duplicated information for response. 
For solution, You can extract id for nested resource from resource id or you can "show" command for nested resource, for example `az network nic show` to get nic id.

Based on the discussion above, I'll close this issue.
