### ISSUE TITLE
Wrong example for remove exclude

### ISSUE THREAD

**Issue by subashsivaji** [Azure/azure-cli#11799]
Explanation is for exclude and example is for include. Change the following command 
_az storage remove -c MyContainer -n path/to/directory --recursive --include "foo*;*bar"_
to
_az storage remove -c MyContainer -n path/to/directory --recursive --exclude "foo*;*bar"_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c4e415-fc8d-26d5-3213-da937fd6932c
* Version Independent ID: dcb2f2d6-fd80-495d-8582-8be859d68792
* Content: [az storage](https://docs.microsoft.com/en-us/cli/azure/storage?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S165.

**Comment by jsntcy** [comment]
@Juliehzl, @jsntcy , please help take a look.

**Comment by Juliehzl** [comment]
Hi @subashsivaji, thanks a lot for your feedback!
What I hope you know is that there is a **breaking change** in `az storage remove` command: `--include` and `--exclude` parameters have been changed to -`-include-path`, `--include-pattern`, `--exclude-path` and `--exclude-pattern` parameters to have more flexibility.
