### ISSUE TITLE
Adding ManagementPublicIp to Azure Firewall

### ISSUE THREAD

**Issue by b564518128** [Azure/azure-cli#11793]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
Adding a new optional feature called "ManagementIpConfiguration" to Azure Firewall. Setting this feature requires that the VNet in which the firewall is deployed to has a Subnet with name "AzureFirewallManagementSubnet"

We will use PowerShell to showcase the use case of the feature
1. Creating a firewall with this feature
```powershell
$mgmtPublicIp = New-AzPublicIpAddress ...
$azureFirewall = New-AzFirewall ... -VirtualNetwork $vnet -ManagementPublicIpAddress $mgmtPublicIp
```
Note: ```$vnet``` MUST contain a subnet called "AzureFirewallManagementSubnet"

2. Updating a firewall to enable this feature or to change the ip config
```powershell
$mgmtPublicIp = New-AzPublicIpAddress ...
$fw = Get-AzFirewall -name $fwName -ResourceGroupName $rgName
$fw.SetManagementIpConfiguration($vnet, $mgmtPublicIp)
Set-AzFirewall -AzureFirewall $getAzureFirewall
```
Note: ```$vnet``` is the Virtual Network that the firewall is deployed into, and it MUST contain a subnet called "AzureFirewallManagementSubnet"

3. REST API Payload for above request
```json
{
  ...
  "properties": {
    ...
    "managementIpConfiguration": mgmtPublicIp,
    ...
    },
  ...
}
```
Note: ```mgmtPublicIp``` should be a json serialized IpConfiguration object. It should binds to a subnet with name "AzureFirewallManagementSubnet".
Example  ```mgmtPublicIp``` looks like this:
```json
 {
  "name": "mgmtIpConf0",
  "id": "/subscriptions/8897e8a2-84e5-44d7-915d-60188052a731/resourceGroups/iavor-ft-dupPIP/providers/Microsoft.Network/azureFirewalls/firewall1/azureFirewallIpConfigurations/mgmtIpConf0",
  "etag": "W/\"223e5e14-013e-43fc-9e57-040d5ac84885\"",
  "type": "Microsoft.Network/azureFirewalls/azureFirewallIpConfigurations",
  "properties": {
    "provisioningState": "Succeeded",
    "privateIPAllocationMethod": "Dynamic",
    "publicIPAddress": {
    "id": "/subscriptions/8897e8a2-84e5-44d7-915d-60188052a731/resourceGroups/iavor-ft-dupPIP/providers/Microsoft.Network/publicIPAddresses/mgmpip1"
  },
  "subnet": {
    "id": "/subscriptions/8897e8a2-84e5-44d7-915d-60188052a731/resourceGroups/iavor-ft-dupPIP/providers/Microsoft.Network/virtualNetworks/test-vnet/subnets/AzureFirewallManagementSubnet"
  }
}
```

**Minimum API Version Required**
2019-11-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/network-december-release/specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/azureFirewall.json

**Target Date**
1/31/2020

**PS Reference**
https://github.com/Azure/azure-powershell/pull/10644

**Comment by b564518128** [comment]
Please contact @iatodoro for more details

**Comment by bim-msft** [comment]
@MyronFanQiu Please take a look.
