### ISSUE TITLE
Option to set default output format of the cli

### ISSUE THREAD

**Issue by naioja** [Azure/azure-cli#11808]
## Describe the bug

**Command Name**
`az configure --defaults output = table`

**Errors:**
It's impossible to set the default output of the az cli command. 
For example I want by default that all outputs to be in table format rather than json.
I'm expecting to have an option something like output = table in the configuration file under defaults.

## Environment Summary
```
Linux-4.15.0-74-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.79

Extensions:
interactive 0.4.3

```

**Comment by jsntcy** [comment]
@jiasli , please help take a look.

**Comment by jiasli** [comment]
`az configure --defaults` is for command parameters. Global parameters like `--output` can be configured under the [config file](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-values-and-environment-variables)'s `[core]` section:

```ini
[core]
output = jsonc
```

**Comment by ModernRonin** [comment]
say you are writing a script that uses az cli and just for the scope of the script you want to change the output, for example, deactivate it completely except for errors (output=none). and you don't want to have to append the `--output=none` to each az command. 

how'd you do that? write a local config file out at the beginning of the script?

**Comment by jiasli** [comment]
We have introduced a new experimental commend group `az config` (#14436). You may now use `az config set core.output=none`. Please give it a try and send any feedback here. 😊

**Comment by ModernRonin** [comment]
will do and let you know within the next few days how it goes :-)
