### ISSUE TITLE
Allow customers to encrypt existing disks and snapshots with customer managed keys via CLI

### ISSUE THREAD

**Issue by ramankumarlive** [Azure/azure-cli#11801]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Disk Resource Provider

**Description of Feature or Work Requested**

Allow customers to encrypt existing disks and snapshots with customer managed keys.

Conceptual doc: https://microsoft.sharepoint.com/:w:/t/MDSSEwithCMKprivatepreview/Ebp9PMK4gPFHhGG8OVgLB3YBi7yazrti-EGB8MpBWMm0RA?e=juMM5h

Design docs:
https://microsoft.sharepoint.com/:w:/t/ComputeVM/EZZCeyRJSbFAiBXq-VVgRBUBrz3c7vgA9lDC0j16Nx4hnQ?e=ec5pwL

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

2019-07-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

https://github.com/Azure/azure-rest-api-specs/pull/7913

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

Jan 13 2019

**Comment by jsntcy** [comment]
@qwordy , please help take a look.

**Comment by qwordy** [comment]
I find that there is another missing command, `snapshot create` with disk encryption set support.

**Comment by qwordy** [comment]
The features have been published in Azure 2.0.80.
