### ISSUE TITLE
urllib3.PoolManager does not use proxy settings

### ISSUE THREAD

**Issue by FirePho** [Azure/azure-cli#11818]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Unable to execute commands

- az webapp log
- az webapp create-remote-connection

being behind the proxy server

**To Reproduce**
az webapp log tail -g _resource-group_ -n _webapp-name_

**Expected behavior**
I expect to see the tail of the log

**Environment summary**
HTTP_PROXY=http://localhost:3128
HTTPS_PROXY=https://localhost:3128

**Additional context**
Both commands use PoolManager from urllib3 which does not work with proxy.
If change urllib3.PoolManager() to urllib3.ProxyManager(os.environ['HTTPS_PROXY']) commands work as it should

**Comment by panchagnula** [comment]
closing since linked PR has been merged.
