### ISSUE TITLE
Optional Parameters

### ISSUE THREAD

**Issue by ITEMuyideen** [Azure/azure-cli#11812]
Using bash certain create command and api calls might require location . in this instance, I could not create the nic , until I was advised to use location, if so kindly update. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29b6bb22-cb91-c7f8-995e-134d0fe5627f
* Version Independent ID: a92f24e8-36a0-808b-a9e7-598f85560b0f
* Content: [az network nic](https://docs.microsoft.com/en-us/cli/azure/network/nic?view=azure-cli-latest#az-network-nic-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsntcy** [comment]
@MyronFanQiu , please help take a look.

**Comment by MyronFanQiu** [comment]
@ITEMuyideen Hello. I just tried `az network nic create`. We don't make `--location` as a required parameter. If you don't provide it, it will use the location of your resource group as default. Did I misunderstand your issue? I don't think we should update `az network nic` command.

**Comment by MyronFanQiu** [comment]
@ITEMuyideen Hello. Did you still meet such issue? If not, I will close this one later.

**Comment by MyronFanQiu** [comment]
Close this one since no response. Feel free to re-open it or open a new one if you meet any more issues.
