### ISSUE TITLE
az vmss extension set fails because "Max price change is not allowed"

### ISSUE THREAD

**Issue by ecalder6** [Azure/azure-cli#11822]
Command "az vmss extension set" for low priority VMSS is failing with error "Max price change is not allowed. For more information, see http://aka.ms/AzureSpot/errormessages".

I've deployed my vmss with "az vmss create" without populating the max-price field. 

I'm using version
azure-cli                         2.0.78 *

command-modules-nspkg              2.0.3
core                              2.0.78 *
nspkg                              3.0.4
telemetry                          1.0.4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29233b11-4e55-8560-9dad-43ac44b818c2
* Version Independent ID: b60ca5ef-f607-80b6-c641-0278cd8bdc61
* Content: [az vmss extension](https://docs.microsoft.com/en-us/cli/azure/vmss/extension?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by dNetGuru** [comment]
Running into the same issue when trying to change a scaleset's image (setting the `virtualMachineProfile.storageProfile.imageReference.id` property)

**Comment by jsntcy** [comment]
@qwordy , please take a look, thanks.

**Comment by ecalder6** [comment]
Bump.

**Comment by josh-AppSheet** [comment]
Looking for an answer for this as well.

**Comment by qwordy** [comment]
```
az vmss create -g fytest3 -n vmss2 --image centos --priority Spot --lb-sku Standard
az vmss extension set --vmss-name vmss2 -g fytest3 --name customScript  --version 2.0 --publisher 
Microsoft.Azure.Extensions --settings '{"commandToExecute": "echo testing"}'
```
I run the above command with no error.
Can you paste the complete command and paste output the command with --debug?

**Comment by qwordy** [comment]
@dNetGuru @ecalder6  For imageReference.id, Can you paste the complete command and paste output the command with --debug? Thanks!

**Comment by qwordy** [comment]
Any update?

**Comment by qwordy** [comment]
Close the issue. If the issue still exists, open a new one.
