### ISSUE TITLE
Azure Firewall with Firewall Policy

### ISSUE THREAD

**Issue by saisujithreddym** [Azure/azure-cli#11834]
**Is your feature request related to a problem? Please describe.**
1. Azure Firewall supports properties like application rule collection,network rule collection and dnat rule collection. We would like to extract these into a separate entity called firewall policy. So the user can just specify the firewall policy on the azure firewall instead of the rule collections. We should have a check on firewall. The user can either have firewall policy OR rule collections.

2. Azure Firewall should have a support for the field called virtual hub. This field indicated the virtual hub Id the firewall is attached to.

3. Azure Firewall should have a support for the field called Sku. This Sku indicates if the firewall is on Virtual Hub or Virtual Network

**Describe the solution you'd like**
The above details indicate the changes needed

**Describe alternatives you've considered**

**Additional context**

**Sample firewall**
 Firewall policy and the rule collections are mutually exclusive

With Firewall Policy 
`{
  "name": "sujith-fw5",
  "id": "/subscriptions/aeb5b02a-0f18-45a4-86d6-81808115cacf/resourceGroups/ankapooFPTest1/providers/Microsoft.Network/azureFirewalls/sujith-fw5",
  "etag": "W/\"e250cec4-d2de-4600-b39e-bc530dd0f9e8\"",
  "type": "Microsoft.Network/azureFirewalls",
  "location": "centraluseuap",
  "tags": {},
  "properties": {
    "provisioningState": "Succeeded",
    "sku": {
      "name": "AZFW_VNet",
      "tier": "Standard"
    },
    "threatIntelMode": "Alert",
    "ipConfigurations": [
      {
        "name": "IpConf",
        "id": "/subscriptions/aeb5b02a-0f18-45a4-86d6-81808115cacf/resourceGroups/ankapooFPTest1/providers/Microsoft.Network/azureFirewalls/sujith-fw5/azureFirewallIpConfigurations/IpConf",
        "etag": "W/\"e250cec4-d2de-4600-b39e-bc530dd0f9e8\"",
        "type": "Microsoft.Network/azureFirewalls/azureFirewallIpConfigurations",
        "properties": {
          "provisioningState": "Succeeded",
          "privateIPAddress": "10.0.0.4",
          "privateIPAllocationMethod": "Dynamic",
          "publicIPAddress": {
            "id": "/subscriptions/aeb5b02a-0f18-45a4-86d6-81808115cacf/resourceGroups/ankapooFPTest1/providers/Microsoft.Network/publicIPAddresses/sujith-pip5"
          },
          "subnet": {
            "id": "/subscriptions/aeb5b02a-0f18-45a4-86d6-81808115cacf/resourceGroups/ankapooFPTest1/providers/Microsoft.Network/virtualNetworks/sujith-vnet5/subnets/AzureFirewallSubnet"
          }
        }
      }
    ],
    "networkRuleCollections": [],
    "applicationRuleCollections": [],
    "natRuleCollections": [],
    "firewallPolicy": {
      "id": "/subscriptions/aeb5b02a-0f18-45a4-86d6-81808115cacf/resourceGroups/ankapooFPTest1/providers/Microsoft.Network/firewallPolicies/isguSujithP4"
    }
  }
}`

With Rule Collections:
`{
  "name": "sujith-fw3",
  "id": "/subscriptions/aeb5b02a-0f18-45a4-86d6-81808115cacf/resourceGroups/ankapooFPTest1/providers/Microsoft.Network/azureFirewalls/sujith-fw3",
  "etag": "W/\"edfc5eb5-734f-48f7-ab68-984c578df90d\"",
  "type": "Microsoft.Network/azureFirewalls",
  "location": "centraluseuap",
  "tags": {},
  "properties": {
    "provisioningState": "Failed",
    "sku": {
      "name": "AZFW_VNet",
      "tier": "Standard"
    },
    "threatIntelMode": "Alert",
    "ipConfigurations": [
      {
        "name": "IpConf",
        "id": "/subscriptions/aeb5b02a-0f18-45a4-86d6-81808115cacf/resourceGroups/ankapooFPTest1/providers/Microsoft.Network/azureFirewalls/sujith-fw3/azureFirewallIpConfigurations/IpConf",
        "etag": "W/\"edfc5eb5-734f-48f7-ab68-984c578df90d\"",
        "type": "Microsoft.Network/azureFirewalls/azureFirewallIpConfigurations",
        "properties": {
          "provisioningState": "Succeeded",
          "privateIPAddress": "10.0.0.4",
          "privateIPAllocationMethod": "Dynamic",
          "publicIPAddress": {
            "id": "/subscriptions/aeb5b02a-0f18-45a4-86d6-81808115cacf/resourceGroups/centralUSE_Liz/providers/Microsoft.Network/publicIPAddresses/fafa"
          },
          "subnet": {
            "id": "/subscriptions/aeb5b02a-0f18-45a4-86d6-81808115cacf/resourceGroups/ankapooFPTest1/providers/Microsoft.Network/virtualNetworks/sujith-vnet3/subnets/AzureFirewallSubnet"
          }
        }
      }
    ],
    "networkRuleCollections": [],
    "applicationRuleCollections": [
      {
        "name": "apprc1",
        "id": "/subscriptions/aeb5b02a-0f18-45a4-86d6-81808115cacf/resourceGroups/ankapooFPTest1/providers/Microsoft.Network/azureFirewalls/sujith-fw3/applicationRuleCollections/apprc1",
        "etag": "W/\"edfc5eb5-734f-48f7-ab68-984c578df90d\"",
        "properties": {
          "provisioningState": "Failed",
          "priority": 200,
          "action": {
            "type": "Allow"
          },
          "rules": [
            {
              "name": "goog",
              "priority": 0,
              "direction": "Inbound",
              "protocols": [
                {
                  "protocolType": "Http",
                  "port": 80
                }
              ],
              "fqdnTags": [],
              "targetFqdns": [
                "www.google.com"
              ],
              "actions": [],
              "sourceAddresses": [
                "*"
              ]
            }
          ]
        },
        "type": "Microsoft.Network/azureFirewalls/applicationRuleCollections"
      }
    ],
    "natRuleCollections": []
  }
}`

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/network-december-release/specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/azureFirewall.json

**PowerShell reference**
https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs

We have pending powershell changes to have a check to allow just either firewall policy or rule collections on the firewall. This is work in progress

**Comment by jsntcy** [comment]
@MyronFanQiu , please help take a look, thanks.

**Comment by saisujithreddym** [comment]
Do we have an ETA on this? Please let me know when this would be released

**Comment by yonzhan** [comment]
planned in S165.

**Comment by saisujithreddym** [comment]
I just wanted to follow up if we are on track for the release for feb 18 :)

**Comment by MyronFanQiu** [comment]
@saisujithreddym should be fine. I will do it in this week.
