### ISSUE TITLE
Unable to set indexes for CosmosDB/MongoDB collection

### ISSUE THREAD

**Issue by Ulrich208** [Azure/azure-cli#11831]
## Describe the bug

When I provide index information via `az cosmosdb mongodb collection create` or `update` with the `--idx` parameter, I do not find these indexes afterwards.

The commands do not show any errors (beside the "preview" warning).

Creating the indexes with the [mongo shell](https://docs.mongodb.com/manual/reference/method/db.collection.createIndex/) works as expected. These indexes could successfully be queried with `az comosdb mongodb collection show`. So querying indexes seems to work.

Possibly the format of the JSON information to the `--idx` parameter in my example is wrong, but it is at least accepted by the commands. A link to deeper format documentation would be welcome.

I also tried to add a document containing the used key (`bar`, in my example) to the collection to no avail.

## To Reproduce:

- `az login` with your Azure account
- Change COSMOSDB_ACCOUNT in the snippet below, as this needs to be unique
```
#!/usr/bin/env bash

set -euxo pipefail

COSMOSDB_ACCOUNT=14ac9636-35dd-11ea-9645-00155d3e2722

RESOURCE_GROUP_NAME='index-test'
DATABASE_NAME='testdb'
LOCATION='westeurope'

az group create --name "$RESOURCE_GROUP_NAME" --location "$LOCATION"
az cosmosdb create \
    --resource-group "$RESOURCE_GROUP_NAME" \
    --name "$COSMOSDB_ACCOUNT" \
    --kind MongoDB \
    --locations "regionName=$LOCATION" failoverPriority=0 isZoneRedundant=False
az cosmosdb mongodb database create \
    --account-name "$COSMOSDB_ACCOUNT" \
    --resource-group "$RESOURCE_GROUP_NAME" \
    --name "$DATABASE_NAME"
az cosmosdb mongodb collection create \
    --account-name "$COSMOSDB_ACCOUNT" \
    --resource-group "$RESOURCE_GROUP_NAME" \
    --database-name "$DATABASE_NAME" \
    --name testcollection \
    --shard 'foo' \
    --idx '[{"key":{"keys":["bar"]}}]'
```

## Expected Behavior

I would expect the index to be shown in the output of `az cosmosdb mongodb collection create` or `show` as it is with indexes created otherwise, but it is not:

```
{
  "id": "/subscriptions/[...]/mongodbDatabases/testdb/collections/testcollection",
  "location": null,
  "name": "testcollection",
  "resource": {
    "id": "testcollection",
    "indexes": [
      {
        "key": {
          "keys": [
            "_id"
          ]
        },
        "options": {
          "expireAfterSeconds": null,
          "unique": null
        }
      }
    ],
    "shardKey": {
      "foo": "Hash"
    }
  },
  "resourceGroup": "index-test",
  "tags": null,
  "type": "Microsoft.DocumentDB/databaseAccounts/mongodbDatabases/collections"
}
```

Hence I worry whether the index was created at all.

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.80
```
## Additional Context

- I see this with our Enterprise Agreement as well as with my personal MSDN account.

**Comment by shurd** [comment]
Hi @Ulrich208 thank you for opening this issue. We have confirmed that we can reproduce this issue, but are still investigating the cause. We will update when we have more information.

**Comment by shurd** [comment]
Hi @Ulrich208 sorry for the delay in responding. It looks like this issue has been resolved as I can no longer replicate it. Can you please retry the command?

az cosmosdb mongodb collection create -a {} -g {} -d {} -n {} --shard id --idx "[{\"key\": {\"keys\": [\"bar\"]}}]"

The result contains this index:
{
        "key": {
          "keys": [
            "bar"
          ]
        },
        "options": {
          "expireAfterSeconds": null,
          "unique": null
        }
      }

**Comment by Ulrich208** [comment]
Hey @shurd,

I could confirm that the created index is contained in the output of the `az cosmosdb mongodb collection create` and `show` commands.

Thanks for letting me know!
