### ISSUE TITLE
az acr helm push is hanging

### ISSUE THREAD

**Issue by sachinmsft** [Azure/azure-cli#11836]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**
1) az login
2) az account set -s 2b5419f3-0ad0-408e-9985-b2a27f4a3982
3) az configure --defaults group=sackumar_TestExecution
4) az configure --defaults acr=sackumar
5) az acr helm repo add

Error:
Unable to get AAD authorization tokens with message: An error occurred: CONNECTIVITY_CHALLENGE_ERROR
Registry 'sackumar.azurecr.io' did not issue a challenge.
"sackumar" has been added to your repositories

az acr helm push < chart >   ****** this is hanging**
**Expected behavior**
az acr helm push < chart > should upload the chart to repo.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by yugangw-msft** [comment]
@sachinmsft, can you please run "az acr check-health" and share the output here?

**Comment by yugangw-msft** [comment]
please reactivate when you have a repro, thanks!
