### ISSUE TITLE
Generate Homebrew Formula based on existing one

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-cli#11839]
Currently we generate Homebrew formula based on a [template](https://github.com/Azure/azure-cli/blob/dev/scripts/release/homebrew/docker/formula_template.txt).

From time to time Homewbrew team may help fix some issues such as https://github.com/Homebrew/homebrew-core/pull/48846, [fix for Xcode 11](https://github.com/Homebrew/homebrew-core/commit/644b9f78e7e13560f752a2e1137da754f11b8124#diff-279b5540b1246df8d64827e6e2ef62be). We may not get notified well with such changes, and the template is not updated with the changes. A regeneration of formula based on the template will lose the changes.

A proposed solution is to generate the new formula based on existing one and only update the version of azure-cli, resource url and resource sha256.

**Comment by yonzhan** [comment]
Generate the new formula based on existing one.
