### ISSUE TITLE
Azure CLI installer has encountered unexpected error. The error code is 2503 and 2502.

### ISSUE THREAD

**Issue by LukeLix** [Azure/azure-cli#11830]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Encountered an error during the installation if  Azure CLI.
error log: The installer has encountered an unexpected  error installer this package. This may indicate a problem with this package. The error code is 2503 and 2502.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
My PC OS is windows10 home version.

**Additional context**

**Comment by jsntcy** [comment]
@fengzhou-msft, please help take a look, thanks.

**Comment by fengzhou-msft** [comment]
Not sure if this would help, please try: https://www.urtech.ca/2016/02/solved-how-to-fix-error-2503-2502-on-windows-10-when-installing-software/

**Comment by LukeLix** [comment]
> Not sure if this would help, please try: https://www.urtech.ca/2016/02/solved-how-to-fix-error-2503-2502-on-windows-10-when-installing-software/

Thank you very mach, The problem I encountered has been resolved.

**Comment by LukeLix** [comment]
@fengzhou-msft  Thank you very mach. This problem I encountered has been resolved.
