### ISSUE TITLE
Incorrect security group error message when creating a rule

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#1184]
"mysg" doesn't exist, "myrg" does

`azure network nsg rule create -g myrg -a mysg -n ssh ...`

results in 

`error:   A network security group with name "ssh" not found in the resource group "myrg"`

It should say:   ... with name "mysg" ... - it's showing the name of the rule and not the name of the group.

**Comment by nneul** [comment]
0.10.6 btw.

**Comment by derekbekoe** [comment]
Looks like this is for the Node-based CLI.
If it is, please file an issue here instead:
https://github.com/Azure/azure-xplat-cli/issues

**Comment by mayurid** [comment]
@nneul : Once issue is filed please close this.

**Comment by nneul** [comment]
Ah, sorry, didn't even look - assumed you had already done so when you sent that message. It's filed and already fixed:

https://github.com/Azure/azure-xplat-cli/issues/3279
