### ISSUE TITLE
az vm create command | Error: PropertyChangeNotAllowed 

### ISSUE THREAD

**Issue by mimckitt** [Azure/azure-cli#11840]
Moving issue: https://github.com/MicrosoftDocs/azure-docs/issues/21749

We believe this is better suited here

##Details 

@nealmcb
----------------

When running az vm create I get this over and over no matter what ssh key options I use.
Finally I figured out that it was just trying to tell me that I had another vm by the same name.

Deployment failed. Correlation ID: 163b5780-ef30-4a2a-8805-2db89193e745. {
  "error": {
"code": "PropertyChangeNotAllowed",
"message": "Changing property 'linuxConfiguration.ssh.publicKeys' is not allowed.",
"target": "linuxConfiguration.ssh.publicKeys"
  }
}

The command is "vm create". So the error should make sense in that context, and/or the documentation should be changed to note that vm create can also modify an existing vm, which would be a very confusing and dangerous behavior, I figure.

That --generate-ssh-keys option and note is irrelevant as I see it, and refers to the local id_rsa.pub file. l I recall seeing the same error with and without that option.

The only file that would be changed in the various scenarios I changed is the .ssh/authorized_keys file.

---------

**Comment by jsntcy** [comment]
@qwordy, please help take a look, thanks.
