### ISSUE TITLE
az vm create preemptible VM

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#11857]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.79

**Describe the bug**
I cannot find 'az' option to create preemptible VM
pls. look here - https://cloud.google.com/preemptible-vms/

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by jsntcy** [comment]
@qwordy, please help take a look, thanks.

**Comment by qwordy** [comment]
I find some useful articles:
https://azure.microsoft.com/en-in/blog/low-priority-scale-sets/
https://spotinst.com/blog/amazon-ec2-spot-vs-azure-lpvms-vs-google-pvms-vs-ibm-transient-servers/

There is a parameter in vm create and vmss create:
--priority
Priority. Use 'Spot' to run short-lived workloads in a cost-effective way. 'Low' enum will be deprecated in the future. Please use 'Spot' to deploy Azure spot VM and/or VMSS.
accepted values: Low, Regular, Spot

**Comment by alexeyshishkin01** [comment]
hello, all, thanks for that!

corresponding documentation needs to be updated:
https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create

1)
--priority
accepted values: Low, Regular, Spot
what exactly do they mean?
what is the default value?

2)
--eviction-policy
accepted values: Deallocate, Delete
what is the default value?

I did basic tests:

root@Alexey-HP:~# az vm show --name centos-ent10-prepare --resource-group centosresourcegroup --o json | grep eviction
  "evictionPolicy": "Deallocate",
root@Alexey-HP:~# az vm show --name centos-ent10-prepare --resource-group centosresourcegroup --o json | grep priority
  "priority": "Spot",

root@Alexey-HP:~# az vm show --name centos-ent10-prepare2 --resource-group centosresourcegroup --o json | grep eviction
  "evictionPolicy": null,
root@Alexey-HP:~# az vm show --name centos-ent10-prepare2 --resource-group centosresourcegroup --o json | grep priority
  "priority": "Regular",

root@Alexey-HP:~# az vm show --name centos-ent10-prepare3 --resource-group centosresourcegroup --o json | grep eviction
  "evictionPolicy": null,
root@Alexey-HP:~# az vm show --name centos-ent10-prepare3 --resource-group centosresourcegroup --o json | grep priority
  "priority": null,

If priority is 'Spot', default eviction-policy is 'Deallocate'
If priority is 'Regular', default eviction-policy is 'null'
If priority is omitted in 'az vm create', default eviction-policy is 'null'

It all sound logical, but it'd be nice to have it documented in order not to double-check.

**Comment by qwordy** [comment]
Thanks for you advice. We'll improve the documentation.

**Comment by qwordy** [comment]
I opened a pull request for this issue.

**Comment by qwordy** [comment]
The update will be available in next version of Azure CLI. Release: 03/31/2020

**Comment by qwordy** [comment]
I should close this issue on 3/31/2020.
