### ISSUE TITLE
Enable update management for a VM using Azure CLI

### ISSUE THREAD

**Issue by ajay15283** [Azure/azure-cli#11850]
How to enable update management for a specific VM using azure cli

**Comment by jsntcy** [comment]
@qwordy, please help take a look, thanks.

**Comment by qwordy** [comment]
Do you mean https://docs.microsoft.com/en-us/azure/automation/automation-update-management?
It's not supported in Azure CLI yet. We have planned to support it.
You can use PowerShell, .NET, or REST. Click "Reference" in the left column of the page of above link.

**Comment by qwordy** [comment]
> 
> 
> @qwordy, please help take a look, thanks.

Please add the top-level label "Compute"

**Comment by ajay15283** [comment]
> Do you mean https://docs.microsoft.com/en-us/azure/automation/automation-update-management?
> It's not supported in Azure CLI yet. We have planned to support it.
> You can use PowerShell, .NET, or REST. Click "Reference" in the left column of the page of above link.

Yes, automation update management using azure-cli. Thanks for the details

**Comment by Jeya888** [comment]
Is this support now?  or still not yet
