### ISSUE TITLE
`az acr task identity show -n Name -r Registry -o table` shows wrong table headers and no output

### ISSUE THREAD

**Issue by BenjaminHerbert** [Azure/azure-cli#11868]
**Describe the bug**

`az acr task identity show` renders incorrect result for output formats table and tsv.

In particular:
`az acr task identity show -n redactedName -r redactedRegistry -o table` renders wrong headers and no meaningful output.

Output format that shows the expected output: 

- json
- jsonc
- yaml
- (none)

Output format that _does not show the expected data_:

- table
- tsv

**To Reproduce**

`az acr task identity show -n redactedName -r redactedRegistry -o table`
```
NAME    PLATFORM    STATUS    SOURCE REPOSITORY    TRIGGERS
------  ----------  --------  -------------------  ----------

```
One entry would be expected with different headers. (The printed headers look like the headers of `az acr task list -r ... -o table`.)

`az acr task identity show -n redactedName -r redactedRegistry -o json` renders _expected output_:
```
{
  "principalId": null,
  "tenantId": null,
  "type": "UserAssigned",
  "userAssignedIdentities": {
    "/subscriptions/redacted": {
      "clientId": "redacted",
      "principalId": "redacted"
    }
  }
}
```

**Expected behavior**
I expect some meaningful output data, regardless of --output format.

**Errors:**
No errors are thrown.

**Comment by yugangw-msft** [comment]
/CC: @northtyphoon, a table transformer is needed like [other command](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/commands.py#L228) . 
@wwwsylvia, consider this as the next batch of CLI work. @shizhMSFT
