### ISSUE TITLE
webapp: I can't Create a book REST service

### ISSUE THREAD

**Issue by Roeche** [Azure/azure-cli#11869]
## Describe the bug

**Command Name**
`Unknown`

**Errors:**
The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.

## To Reproduce:
I am following the Exercise - Consume a REST service with HttpClient at Learn:
https://docs.microsoft.com/en-us/learn/modules/consume-rest-services/4-exercise-consume-rest-service-with-httpclient.

There are 8 steps for Creating a book REST service. However, when attempting the 4th:
4. Create an Azure App Service plan in the free tier.
az appservice plan create --name $webappname --resource-group learn-342bb062-2f96-448e-b5ef-5225519974ff --sku FREE

I am getting the following: 
2f96-448e-b5ef-5225519974ff --sku FREE
The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.

Please assist.
Thanks

- _Put any pre-requisite steps here..._
- `az help`

## Environment Summary
```

```

**Comment by panchagnula** [comment]
@Roeche just to be clear you are seeing this error when you are trying to create an appservice plan? This appservice plan doesn't already exist with a different SKU? It could mean that you are out of quota (allowed number for FREE appservice plans). Can you run the same command with --debug flag & share the details? Thank you.

**Comment by panchagnula** [comment]
closing due to lack of response.

**Comment by DavidEPatrick** [comment]
I'm experiencing this issue. It appears to be permissions related to the sandbox environment.
