### ISSUE TITLE
DOTNETCORE|Latest runtime issue with az webapp config set

### ISSUE THREAD

**Issue by chrisxpr** [Azure/azure-cli#11876]
I noticed that if you update the Linux FX Version to Stack '.NetCore' and MajorVersion 'Latest' in the azure portal (App Service->Configuration->General Settings)
when you run the command:
az webapp config show --resource-group rg --name webapp

The value returned in the json is:   
"linuxFxVersion": "DOTNETCORE|latest"

with 'latest' in full lowercase.

When you run az webapp list-runtimes --linux the suggested string is 'DOTNETCORE|Latest' with slightly different casing of 'Latest' 

If you try to update the app service stack via the command:

az webapp config set --resource-group rg --name webapp --linux-fx-version "DOTNETCORE|Latest"

The command succeeds but navigating to App Service->Configuration->General Settings in the azure portal does not highlight the Stack and MajorVersion as expected, displaying empty drop downs.

Whereas after running the command (lower case 'l')

az webapp config set --resource-group cs-test-application-linux-syd --name cs-api-test-mel --linux-fx-version "DOTNETCORE|latest"

Navigating to App Service->Configuration->General Settings in the azure portal does highlight the correct Stack and MajorVersion

Just want to confirm if this is a known issue and whether the names can be made consistent in az webapp list-runtimes.

**Comment by panchagnula** [comment]
Not a known issue I have shared this Portal team as well, We will take a look, as per the list-runtimes it directly returns the value the API returns.

**Comment by Kotasudhakarreddy** [comment]
taking a look in to this.

**Comment by panchagnula** [comment]
should be fixed by https://github.com/Azure/azure-cli/pull/13688
