### ISSUE TITLE
pydocumentdb listed as dependency together with its replacement azure-cosmos

### ISSUE THREAD

**Issue by bluca** [Azure/azure-cli#11879]
azure-cli's setup.py lists both pydocumentdb, which is deprecated and out of support in August this year, and its newly renamed replacement azure-cosmos as dependencies:

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/setup.py#L61
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/setup.py#L138

https://pypi.org/project/pydocumentdb/
https://pypi.org/project/azure-cosmos/

Are both of them really required at the same time?

**Comment by jsntcy** [comment]
@fengzhou-msft, please take a look, thanks.

**Comment by fengzhou-msft** [comment]
Thanks for bringing this up. We'll reevaluate the use of pydocumentdb.

**Comment by bluca** [comment]
@fengzhou-msft so at the moment they are both used? I ask as I'm preparing to upload azure-cli to Debian, and this dependency is the last issue remaining that I need to sort. At the moment I have uploaded pydocumentdb but not azure-cosmos. Thanks.

**Comment by fengzhou-msft** [comment]
> @fengzhou-msft so at the moment they are both used? I ask as I'm preparing to upload azure-cli to Debian, and this dependency is the last issue remaining that I need to sort. At the moment I have uploaded pydocumentdb but not azure-cosmos. Thanks.

A quick search showed no usage of pydocumentdb. I added service team here. 

Hi cosmos team, please help check whether pydocumentdb can be removed from azure-cli for az cosmosdb.

**Comment by fengzhou-msft** [comment]
bot is not working. cc @kushagraThapar @srinathnarayanan @southpolesteve @shurd

**Comment by bluca** [comment]
Ok, thanks. I'll update azure-cosmos-db in debian to the latest version, and drop pydocumentdb from azure-cli's dependency list.

**Comment by shurd** [comment]
That package can be removed from setup.py from the Cosmos DB perspective. I removed it from the setup.py file underneath our command module at the time, but I did not remove it from the global setup. 

https://github.com/Azure/azure-cli/pull/9656/files

**Comment by bluca** [comment]
Fixed by https://github.com/Azure/azure-cli/pull/11918 - thanks!
