### ISSUE TITLE
AKV10032: Invalid issuer error for listing of key vault secrets from nondefault tenant subscription

### ISSUE THREAD

**Issue by t3mi** [Azure/azure-cli#11871]
## Describe the bug

**Command Name**
`az keyvault secret list`

**Errors:**
```
AKV10032: Invalid issuer. Expected one of https://sts.windows.net/<nondefault tenant>/, found https://sts.windows.net/<default tenant>/.
```

## To Reproduce:
Steps to reproduce the behavior.

- `az login` // login with one tenant
- `az login` // login with second tenant
- `az account list` // verify multiple subscriptions exist with different tenants
- `az keyvault secret list --subscription <subscription from nondefault tenant> --vault-name {} --query '[].id'`

## Expected Behavior
Secret ids are printed.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.80

```
## Additional Context
- `az account list`
```json
[
  {
    "cloudName": "AzureCloud",
    "id": "<default subscription>",
    "isDefault": true,
    "name": "Visual Studio Enterprise with MSDN",
    "state": "Enabled",
    "tenantId": "<default tenant>",
    "user": {
      "name": "<email>",
      "type": "user"
    }
  },
  {
    "cloudName": "AzureCloud",
    "id": "<subscription from nondefault tenant>",
    "isDefault": false,
    "name": "Visual Studio Enterprise",
    "state": "Enabled",
    "tenantId": "<nondefault tenant>",
    "user": {
      "name": "<email>",
      "type": "user"
    }
  }
]
```

**Comment by jsntcy** [comment]
@bim-msft, please help take a look, thanks.

**Comment by t3mi** [comment]
Any updates on this?

**Comment by bim-msft** [comment]
@t3mi This is a cross-tenants issue, I believe it's similar with #7607 , the parameter `--subscription` seems broken now as we are facing some complicated cross-tenants problems, please avoid using this parameter as a workaround. For more info, please refer to: #7902

**Comment by jjnwu** [comment]
Our deployment is blocked due to the same error code

2020-03-12T19:23:08.4378500Z        Operation Info:
2020-03-12T19:23:08.4386094Z            Start Time: 03/12/2020 19:22:40
2020-03-12T19:23:08.4392880Z            End Time: 03/12/2020 19:22:40
2020-03-12T19:23:08.4439932Z            Error Reason: Error in 'payloadProperties' for extension 'Microsoft.Azure.Portal.HostingService/DeployPortalExtension'. Error Message: Rollout action failed. Please check the help link for more information.
2020-03-12T19:23:08.4442589Z AKV10032: Invalid issuer. Expected one of ....

**Comment by yungezz** [comment]
the scenario in keyvault requires global `--subscription` works well for cross-tenant scenarios firstly.

**Comment by t3mi** [comment]
@yungezz please mark this as a bug There is a key and it's not working properly, it's not a feature request.

**Comment by bendubuisson** [comment]
I have experienced the same bug with `secret set` with the subscription flag

**Comment by bendubuisson** [comment]
That being said, if you set the sub as default just before, it works, so:
```
az account set --subscription {SubID}
az keyvault secret list --vault-name myVault
```

**Comment by juniwang** [comment]
`az keyvault storage list --vault-name <Vault Name>` doesn't work. Neither with `--subscription <sub>` nor without `--subscription` works.

**Comment by dosani** [comment]
> @t3mi This is a cross-tenants issue, I believe it's similar with #7607 , the parameter `--subscription` seems broken now as we are facing some complicated cross-tenants problems, please avoid using this parameter as a workaround. For more info, please refer to: #7902

any update? we are also running into this issue while attempting cross tenant key access. tried both with and without subscription parameter.

**Comment by MikePennington** [comment]
I am receiving this error even on the _default_ subscription.

```
az account show
{
  "environmentName": "AzureCloud",
  "homeTenantId": "REDACTED",
  "id": "REDACTED",
  "isDefault": true,
  "managedByTenants": [
    {
      "tenantId": "REDACTED"
    }
  ],
  "name": "Enterprise Dev/Test",
  "state": "Enabled",
  "tenantId": "REDACTED",
  "user": {
    "name": "mike.pennington@REDACTED",
    "type": "user"
  }
}
```

```
az keyvault secret list --vault-name keyvault-test
AKV10032: Invalid issuer. Expected one of https://sts.windows.net/ab8cb611-0add-432b-9975-ae87e1ebe6f7/, https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/, https://sts.windows.net/e2d54eb5-3869-4f70-8578-dee5fc7331f4/, found https://sts.windows.net/71fdf23f-162c-4ca1-a83b-7a68e8b5ea85/.
```

The `keyvault-test` keyvault is in the default subscription listed above. I am certain that this used to work.

**Comment by c0dezer019** [comment]
The day a bug becomes a feature request. (I can confirm this bug, it is still on-going)

**Comment by lvisterin** [comment]
For the people running into this even when the subscription ID is set correctly, you should check the `--vault-name` for typos. You may be trying to talk to the wrong Key Vault (that's what happened in my case).

**Comment by yungezz** [comment]
hi @houk-ms could you have a look? thanks

**Comment by inverted360** [comment]
I can confirm this is still a concern and the work-around of reasserting subscription before each 'az keyvault' call mitigates it.

**Comment by tobbin2** [comment]
Is this still active? We have the same problem. AKV10032. Invalid Issuer,

- made sure the user has permission to check key-vault
- logged in to the correct subscription

weird thing is that we tried another user with the same code and subscription which worked well

**Comment by mira-mayhem** [comment]
I don't get this error in powershell with AZ CLI. I get this error running code from Visual Studio:
`.AddAzureKeyVault(keyVaultUri, new DefaultAzureCredential(true))` (browser window popping up)
and the same error with:
`.AddAzureKeyVault(keyVaultUri, new SharedTokenCacheCredential("my.email@company.com"))` 

I have logged in and out in VS (2019), the Azure Service Authentication under Tools > Options looks good

It's working when using the old nuget (Microsoft.Extensions.Configuration.AzureKeyVault 3.1.14) - without supplying any credentials.

**Comment by thuannguy** [comment]
This happens to me today. Pretty much blocking our deployment

**Comment by MaDOS** [comment]
Can confirm this also happens with `InteractiveBrowserCredential`. Trying to access a keyvault with my work account which is permitted in azure to access the keyvault. Pretty sure the keyvault I am trying to access resides in a non-default azure subscription.

**Comment by Rob97** [comment]
Just ran into the same issue as well...why would they allow us to transfer a vault if it is essentially useless outside of it's "birth" tenant??

**Comment by MRVDH** [comment]
I am having a similar, if not the same, issue. Could it be related to this? https://github.com/Azure/AppConfiguration/issues/511

**Comment by dawwa** [comment]
anyone discovered any workaround while waiting for this forever? :)

**Comment by jaredpar** [comment]
I am also hitting the following and am stuck.

**Comment by fouufi** [comment]
I have the same issue, it works when i use the sdk3
var azureServiceTokenProvider = new AzureServiceTokenProvider();
                       var keyVaultClient = new KeyVaultClient(
                           new KeyVaultClient.AuthenticationCallback(
                               azureServiceTokenProvider.KeyVaultTokenCallback));
                       builder.AddAzureKeyVault(
                           keyVaultEndpoint, keyVaultClient, new DefaultKeyVaultSecretManager());

But this one doesn't work : client = new SecretClient(new Uri(kvUri), new DefaultAzureCredential());

**Comment by rozek1szymon** [comment]
I have same problem as @fouufi has

**Comment by jaredpar** [comment]
@evelyn-ys how do get this fix so we can unblock these scenarios?

**Comment by evelyn-ys** [comment]
> @evelyn-ys how do get this fix so we can unblock these scenarios?

@jaredpar This will be released in [S188](https://github.com/Azure/azure-cli/milestone/106). Stay in tune and upgrade to new version after the release in 06/15/2021

**Comment by dgaspar** [comment]
A couple workarounds that worked for me were to use `AZURE_TENANT_ID` env var or to get it from the config and set the `VisualStudioTenantId` option:
```csharp
var o = new DefaultAzureCredentialOptions();
o.VisualStudioTenantId = preConfig["AzureTenantId"];
configurationBuilder.AddAzureKeyVault(new Uri(preConfig["KeyVaultName"]), new DefaultAzureCredential(o));
```

**Comment by ladenedge** [comment]
The above series of commands (which are exactly the commands I want to work) do not work for me. 🙁

```
Set-AzKeyVaultSecret: Operation returned an invalid status code 'Unauthorized'
Code: Unauthorized
Message: AKV10032: Invalid issuer. Expected one of ...
```

**Comment by flamaniac** [comment]
If you have this problem, you have selected the correct account in options->Azure Service Authentication->Account Selection, and this (censored) still doesn't work...
Probably you have also diffrent version of Visual Studio installed on you machine (2019 in my case) : ] Despite all those settings, values stored in browser or Control Panel\All Control Panel Items\Credential Manager VS has local settings SHARED between versions (to be precise those settings are shared "sometimes" because in options is showing always state of the "version" that you are currently running (2022) and will use this setting once than, on the next try It will is use settings set in vs 2019 .)
JUST SET VALID ACCOUNT ( options->Azure Service Authentication->Account Selectio) IN ALL  VISUAL STUDIOS installed on your machine.
If helped please put like because I wasted, a  lot of time here. Thanks.

**Comment by luckyboykg** [comment]
> A solution I've found for both Core/Classic .NET frameworks was to set an `AZURE_TENANT_ID` env var or set the value via credential options:
> 
> ```cs
> var o = new DefaultAzureCredentialOptions();
> o.VisualStudioTenantId = preConfig["AzureTenantId"];
> configurationBuilder.AddAzureKeyVault(new Uri(preConfig["KeyVaultName"]), new DefaultAzureCredential(o));
> ```
> 
> .NET Classic `MicrosoftConfigurationBuilders` don't seem to accept options, though. https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/main/src/Azure/AzureKeyVaultConfigBuilder.cs#L93 Env var was the only option that worked..

You're right.
I must set `TanentId` to make it work.

``` 
  string keyVaultUrl = _configuration.GetValue<string>("AzureKeyVault:AzureKeyVaultURL");
  var credentialOption = new DefaultAzureCredentialOptions
  {
      TenantId = _configuration.GetValue<string>("AzureKeyVault:AzureClientTenantId")
  };
  var credential = new DefaultAzureCredential(credentialOption);
  _secretClient = new SecretClient(new Uri(keyVaultUrl), credential);```
