### ISSUE TITLE
az version no longer works

### ISSUE THREAD

**Issue by MrCNeale** [Azure/azure-cli#11882]
Either locally, or via cloud shell (bash or powershell) running
az version
reports that version is not in the az command group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeedb9a7-2aed-6727-4cfb-1515809d676e
* Version Independent ID: 2c83180d-22ad-db42-e2eb-f27f11977963
* Content: [az](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-version)
* Content Source: [src/azure-cli/azure/cli/command_modules/profile/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/profile/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsntcy** [comment]
@jiasli, please take a look, thanks.

**Comment by jiasli** [comment]
`az version` is a new command introduced in https://github.com/Azure/azure-cli/pull/11680. Please install the latest version to use this command.
