### ISSUE TITLE
az aks get-credentials fails on empty or non-existent KUBECONFIG

### ISSUE THREAD

**Issue by sudermanjr** [Azure/azure-cli#11881]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
'clusters'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/acs/custom.py, ln 1182, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
cli/command_modules/acs/custom.py, ln 1117, in _handle_merge
    if existing[key] is None:
KeyError: 'clusters'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --overwrite --resource-group {} --name {}`

## Environment Summary
```
macOS-10.15.2-x86_64-i386-64bit
Python 3.8.1
Shell: bash

azure-cli 2.0.79 *

```
Also tried with `2.0.80`

**Comment by jessemillar** [comment]
For any other internet people that find this when they're too tired to think, removing your `KUBECONFIG` file (e.g. `rm ~/.kube/config`) and re-running the `get-credentials` command appears to fix things.
