### ISSUE TITLE
Azure Function - Unclear error on deployment if invalid resource group name specified.

### ISSUE THREAD

**Issue by mcollier** [Azure/azure-cli#11893]
**Describe the bug**
When executing the command below, if the specified resource group does not exist, an error is returned. The error message is very unclear as to what the problem is (invalid resource group).
`az functionapp deployment source config-zip -g "this-rg-does-not-exist" -n CSEFeedbackFunctionApp123 --src "C:\src\msft\csefeedback-function-wrong-rg-name\bin\Debug\netcoreapp2.1\MyFunction.zip"`

**To Reproduce**

- Create an Azure Function app
- Create an Azure Function (e.g. HTTP-triggered function)
- Zip the function content
- Deploy using Azure CLI

**Expected behavior**
If an invalid resource group is specified, the error message should indicate that the resource group is invalid or doesn't exist.

**Environment summary**
Windows 10 1909
Azure CLI version 2.0.80

**Additional context**
Similar to #10773 and #10639

**Comment by dariagrigoriu** [comment]
Pending milestone assignment.
