### ISSUE TITLE
az acr login - requires Docker engine

### ISSUE THREAD

**Issue by Simas1** [Azure/azure-cli#11895]
**Describe the bug**
az acr login requires that docker be running a docker daemon as the azure cli runs docker ps. 
This is false behaviour, login command shouldn't run "docker ps" - because this command expect to have docker daemon running, which is not always true. For example, I want to use az acr from ACI (Azure Container Instance), so there is no Docker daemon, we can't run Docker in Docker.
I would like to execute in ACI: _az acr build_, or _az acr task create_ - which will build image on ACR.
But to use this I need to login to ACR, where I can't, because it wants docker daemon.
**To Reproduce**
Steps to reproduce the behavior.
Run the azure cli on ACI container (image: ubuntu 16.04).
From shell run (attach to the container):
`az acr login --name <name>`
Error message:
```
An error occurred: DOCKER_COMMAND_ERROR
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
**Expected behavior**
I don't care about docker, I need to use ACR - so I need to logon to ACR without docker daemon. Please remove this dependency of Docker daemon!
If _az acr_ - is hard dependency on Docker (docker wrapper), maybe that dependency could be only for Docker cli - but not Docker daemon.

**Comment by jt55401** [comment]
This is also an issue for us - is there a workaround anyone is using?

**Comment by yugangw-msft** [comment]
ACR has integration with Azure Resource Manager, hence if the user account or service principal account has permission to the registry, running `az login` should be sufficient for subsequent commands to work including `az acr build`.
@jt55401 @Simas1, please let me know whether this answers your question

**Comment by jt55401** [comment]
We already worked around it by building our own docker image that includes both tools, which cleaned up our build process a bit anyway. Thanks.

**Comment by Simas1** [comment]
Az login - with ACR will not work with regular user unfortunately - I get access denied (even I'm root of this tenant/subscription).  I know I can create service principal, grant permissions to ARC and it will work, only this way work. But that is workaround, and I would expect solid solution. And in some cases I don't want to use service principal. So separation should be done with "az acr" command implementation - even Docker separated Docker-CLI from Docker engine, so we can install only Docker-cli without docker engine (which is not possible inside container)

**Comment by yugangw-msft** [comment]
`az login` is supposed to work with ACR thoygh user account. Lots of ACR commands don't require docker. Say if you grant a user account a reader role on a ACR registry through `az role assignment create`, then your `az acr repository` commands will work. If you are the owner of a registry, then almost all `az acr` commands will work out of box. If you can share with me the error message, then I can look further

**Comment by Simas1** [comment]
Strange, now it seems some commands working when logon with "az login", I can't recall which one was failing, sorry I didn't record that (some kind of authentication issue was with ACR)
But anyway "az acr login" - should not try to launch commands which expect Docker daemon.

**Comment by yugangw-msft** [comment]
> az acr login" - should not try to launch commands which expect Docker daemon.

Agreed, we have #9442 to track the de-coupling work

**Comment by yugangw-msft** [comment]
Given no new issues to track, I am closing this one.
