### ISSUE TITLE
Failure when running an image copy

### ISSUE THREAD

**Issue by wnmct** [Azure/azure-cli#11892]
## Describe the bug

**Command Name**
`az snapshot create`

**Errors:**
```
Required parameter 'storageAccountId' is missing (null).
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az snapshot create --resource-group {} --name {} --location {} --source {} --output {} --tags {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.80

Extensions:
image-copy-extension 0.2.2

```

**Comment by jsntcy** [comment]
@qwordy, please help take a look, thanks.

**Comment by qwordy** [comment]
There is a patch to fix it. https://github.com/Azure/azure-cli-extensions/pull/1172
@tamirkamara Can you help publish the new version?

**Comment by tamirkamara** [comment]
The PR for the new version with the fix is underway.
https://github.com/Azure/azure-cli-extensions/pull/1211

**Comment by qwordy** [comment]
image-copy 0.2.3 is released. It should fix this issue.
https://github.com/Azure/azure-cli-extensions/pull/1211
