### ISSUE TITLE
az sql server update -p returns zero exit code when password does not have sufficient complexity

### ISSUE THREAD

**Issue by jabbera** [Azure/azure-cli#11917]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
A failed az sql server update still retuns 0 as an exit code

**To Reproduce**
powershell

az sql server update --name <name> --resource-group <group> -p "A"
$LASTEXITCODE

**Expected behavior**
A non-zero exit code

**Environment summary**
Windows 10 Powershell 6

![image](https://user-images.githubusercontent.com/301208/72843247-2435ea80-3c68-11ea-9221-b570e0b8670b.png)

**Comment by jaredmoo** [comment]
Thank you for the feedback! I tried to repro, but I did get nonzero error code:

![image](https://user-images.githubusercontent.com/3248887/72918903-4b89c780-3cfb-11ea-90b0-1c6fe88a88a1.png)

From az-cli-sql module perspective, we are doing nothing special here - just passing your request to REST API. az-cli core is taking care of handling response message and setting exit code. I'll set tags on this issue for az-cli core team to take a look.

**Comment by jiasli** [comment]
The command behaves correctly in a pure PowerShell console:

```powershell
> az sql server update --name {} --resource-group {} -p "A"
Password validation failed. The password does not meet policy requirements because it is too short.
> $LASTEXITCODE
1
```

After activating posh-git and oh-my-posh and switch to a git repo folder, I am able to reproduce the wrong exit code even without Azure CLI.

```powershell
> Install-Module posh-git -Scope CurrentUser
> Install-Module oh-my-posh -Scope CurrentUser
> Import-Module posh-git
> Import-Module oh-my-posh
> Set-Theme Paradox
> cd D:\cli\azure-cli
> powershell.exe -Command "Exit 1"
> echo $LASTEXITCODE
0
```

![Screenshot_2](https://user-images.githubusercontent.com/4003950/72958166-443ce980-3de1-11ea-8f29-f98c00b8a2e6.png)

This appears to be a known issue: https://github.com/JanDeDobbeleer/oh-my-posh/issues/162#issuecomment-537449887

As posh-git and oh-my-posh are not maintained by Microsoft, please use Azure CLI in a pure PowerShell or CMD console.
