### ISSUE TITLE
issue while browsing for aks cluster

### ISSUE THREAD

**Issue by patelkashyap3190** [Azure/azure-cli#11922]
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
Can not find kubectl executable in PATH
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Windows-7-6.1.7601-SP1
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.80

```

**Comment by jluk** [comment]
You have to install kubectl.

Run az aks install-cli.
