### ISSUE TITLE
owner-object-id cannot be a group

### ISSUE THREAD

**Issue by DonPetry-EY** [Azure/azure-cli#11924]
I was surprised to find that this parameter will not accept the object-id of a group.  It seems to only accept User and SPN ID's.  

The reference target 'Group_01234567a-1de1-4d1b-a5a8-2de913801c69' of type 'Group' is invalid for the 'owners' reference.

Please add a note that Owner cannot be a Group in this context.  Would also like to request this be made possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af83ae6-8be6-c2a3-e994-d09b60ddc167
* Version Independent ID: 70f8a6b9-5cba-2e41-1046-423405782c4c
* Content: [az ad app owner](https://docs.microsoft.com/en-us/cli/azure/ad/app/owner?view=azure-cli-latest#az-ad-app-owner-add)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
Thanks for the feedback. We will look into it.

**Comment by adlangx** [comment]
Application Service principals also cannot have ownership apparently.

The reference target '<OWNER_OBJECT_ID>' of type 'Application' is invalid for the 'owners' reference.

**Comment by yonzhan** [comment]
add to S168.

**Comment by jiasli** [comment]
I have provided explanation at https://github.com/Azure/azure-cli/issues/9250#issuecomment-603622786. You may vote on feedback page.

**Comment by jiasli** [comment]
> Application Service principals also cannot have ownership apparently.
> 
> The reference target '<OWNER_OBJECT_ID>' of type 'Application' is invalid for the 'owners' reference.

Hi @adlangx, the owner can only be a user or service principal, please see https://github.com/Azure/azure-cli/issues/9250#issuecomment-603621148.
