### ISSUE TITLE
webapp: az webapp up not creating RG when using -g flag

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#11925]
reported by internal customer

Reprod this on CLI 2.0.80. 

Running the az webapp command with -g makes you expect that the resource group specified would be created, but it's not, and the app is just put into a default resource group like before. Especially since the App Service plan is created, why not the resource group? See repro command line output:

bash-5.0# az webapp up -g cephalin-python -n cephalin-python -p cephalin-python -l westeurope --sku B1
webapp cephalin-python doesn't exist​
Creating webapp 'cephalin-python' ...​
Configuring default logging for the app, if not already enabled​
Creating zip with contents of dir /root/Repos/python-docs-hello-world ...​
Getting scm site credentials for zip deployment​
Starting zip deployment. This operation can take a while to complete ...​
Deployment endpoint responded with status code 202​
You can launch the app at http://cephalin-python.azurewebsites.net​
{​
  "URL": "http://cephalin-python.azurewebsites.net",​
  "appserviceplan": "cephalin-python",​
  "location": "westeurope",​
  "name": "cephalin-python",​
  "os": "Linux",​
  "resourcegroup": "cephalin_rg_Linux_westeurope",​
  "runtime_version": "python|3.7",​
  "runtime_version_detected": "-",​
  "sku": "BASIC",​
  "src_path": "//root//Repos//python-docs-hello-world"​
}​

**Comment by yonzhan** [comment]
move to S167.

**Comment by Kotasudhakarreddy** [comment]
Looking in to it.

**Comment by Kotasudhakarreddy** [comment]
I am able to repro the issue. Working on the fix.
