### ISSUE TITLE
Problems with az sql vm create

### ISSUE THREAD

**Issue by dbamaster** [Azure/azure-cli#11928]
**Describe the bug**
Not able to create SQL Server VM using AZ CLI, the "Resource does not exist" message is returned while I'm trying to create the actual resource.

I already checked, the Microsoft.SqlVirtualMachine provider is registered.

```
[dba mastery] $  az provider list --output table | grep "SqlVirtualMachine"
Microsoft.SqlVirtualMachine             RegistrationRequired  Registered
```

**Environment summary**
OS type: macOS
az-cli version: 2.0.79

**How to reproduce**
```
[dba mastery] $  az sql vm create \
> --name sqlmv01 \
> --resource-group MyRG \
> --location westcentralus \
> --license-type PAYG \
> --image-sku Developer \
> --image-offer SQL2017-WS2016 \
> --connectivity-type PUBLIC \
> --port 1433
Command group 'sql vm' is in preview. It may be changed/removed in a future release.
Azure Error: ResourceDoesNotExist
Message: Resource '/subscriptions/XXX/resourceGroups/MyRG/providers/Microsoft.Compute/virtualMachines/sqlmv01' does not exist.
```

**Comment by jeroenterheerdt** [comment]
@jaredmoo

**Comment by yareyes** [comment]
@dbamaster sql vm command will create a SQL virtual machine for an existing underlying Virtual Machine with SQL installed. The error is indicating that the VM resource does not exist. If you want to use the command, please create a Virtual Machine with one of our SQL images and register using the above command. 

Please refer to [Register a SQL Server virtual machine in Azure with the SQL VM resource provider.](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sql/virtual-machines-windows-sql-register-with-resource-provider)

**Comment by dbamaster** [comment]
> @dbamaster sql vm command will create a SQL virtual machine for an existing underlying Virtual Machine with SQL installed. The error is indicating that the VM resource does not exist. If you want to use the command, please create a Virtual Machine with one of our SQL images and register using the above command.
> 
> Please refer to [Register a SQL Server virtual machine in Azure with the SQL VM resource provider.](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sql/virtual-machines-windows-sql-register-with-resource-provider)

You're correct. I was trying to create the VM from the ```az sql vm create``` command, I have addressed the problem. Thank you!
