### ISSUE TITLE
az webapp up not working as expected in dotnet core 2.2 project

### ISSUE THREAD

**Issue by fernandogutierrez27** [Azure/azure-cli#11920]
**Command Name**
`az webapp up`

**Describe the bug**
Following this [tutorial] with the C# development language, the final step was apply the `az webapp up` command but the deployed site only had a message saying *"You do not have permission to view this directory or page"*. That means that no site was detected on the deployed site folder.

I applied the `dotnet publish` command and tried to run `az webapp run` from the published folder but the result was: *"Could not auto-detect the runtime stack of your app, see 'https://go.microsoft.com/fwlink/?linkid=2109470' for more information."*

Finally, from the **root project folder** I ran `dotnet publish -o .` and then `az webapp up` and got the deployment working as expected. This sounds really crazy because I finally got merged the published files with the source code.

This is my first attemp to use `az webapp up`, I hope that this feedback helps you to fix some issue.

**To Reproduce**
Follow this [tutorial] with the C# development language.

**Expected behavior**
The site is deployed and working when using `az webapp up` from root project folder.

**Environment summary**
```
Running Azure Cloud Shell from tutorial site:
Linux-4.15.0-1066-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.80

```
[tutorial]: https://docs.microsoft.com/es-es/learn/modules/host-a-web-app-with-azure-app-service/index

**Additional context**
This could be a related issue, it helped me to find a solution to deploy my app.
https://stackoverflow.com/questions/59746058/az-webapp-up-no-longer-works-from-dotnet-publish-directory/59859611

**Comment by panchagnula** [comment]
if you are still seeing this can you run the webapp up command with --debug flag at the end and share the details. The message you are seeing means that we were not able to detect a runtime stack

**Comment by panchagnula** [comment]
Closing due to lack of response- please re-open or file a new issue if this is still a problem. Thanks!
