### ISSUE TITLE
Permissions for SharedAccessKey in `az sql db export`

### ISSUE THREAD

**Issue by nikoudel** [Azure/azure-cli#11921]
The documentation covers the case of generating a SAS token for specific blob (`-n myBacpac.bacpac`).
That is not very practical because a more useful scenario is to generate a token for the whole container and create daily backups periodically, each named differently, e.g. `backup-2020-01-22.bacpac`.
However, in that case the write permission (`--permissions w`) is not enough and exporting will fail with a vague error message.

The documentation could help by mentioning a read permission (`--permissions rw`) is required as well in that case.

PS. Also wondering why the read permission is required in the first place - that enables potential attacker to steal all the backups if token was compromised.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bdd674-b454-e863-c943-9c979b466a92
* Version Independent ID: b15341f9-3f1b-00e0-a1c2-970f25a6ab03
* Content: [az sql db](https://docs.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#az-sql-db-export)
* Content Source: [src/azure-cli/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adeal** [comment]
@nikoudel thanks for the feedback here!
The document is just intended to be an example. Depending on use case, I would agree that the generating a credential for the entire container could be beneficial.

We'll take a look at why both `rw` permissions are required when generating a container SAS.

**Comment by lilyjma** [comment]
Hi, this issue seems to be resolved, so I'll close it for now. Please reopen if you have more questions.
