### ISSUE TITLE
The suggested command for changing the Active Directory Administrator updates the name shown in the portal page but it does not set  the AD admin properly

### ISSUE THREAD

**Issue by axthosarouris** [Azure/azure-cli#11934]
Hi,
My problem is that I want to update the Azure AD admin of an SQL server using the CLI. However, the results when I run the command and when I update it manually through the portal are different.

**Input commands (from a script):**
```
call az sql server ad-admin update -g ResourceGroup --subscription  Subscription name"  --set login=%3 --server-name %servername%
call az sql db delete -g ResourceGroup--subscription "Subscription name" -s %servername% --name %database% --yes
call az sql db create -g ResourceGroup--subscription "Subscription name" -s %servername% --name %database% --service-objective S4 --max-size 250GB

sqlcmd -f 65001 -S %servername%.database.windows.net -d %database% -i %working_dir%\V1_1_02__CreateSchemas.sql
<more sqlcmd options>
```
**Output:** 
```
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'..

```
However, if I go to the Azure portal and I set the AD admin as my user manually, then the exact same commands  work fine. In other words, if the `az sql server ad-admin update` does not perform an actual update then the scripts work fine. 

I have the same experience with the SQL Server Management Studio. If I update the Azure AD admin through CLI, I do not have access to my database as a dbo (In fact I get the same error as the sqlcmd error). If I update the Azure AD through the portal then I access the database as dbo.

**Full Output of the commands above:**(Sensitive data have been replaced)

```
{
  "id": "/subscriptions/1111111111111/resourceGroups/ResourceGroupName/providers/Microsoft.Sql/servers/sqlserverName/administratorOperationResults/ActiveDirectory",
  "kind": null,
  "location": "North Europe",
  "login": "OGK@mycompany.com",
  "name": "ActiveDirectory",
  "resourceGroup": "ResourceGroupName",
  "sid": "234245-8e221a-4267-89e5-df6af6206313",
  "tenantId": "4354353535353",
  "type": "Microsoft.Sql/servers/administrators"
}
{
  "catalogCollation": "SQL_Latin1_General_CP1_CI_AS",
  "collation": "SQL_Latin1_General_CP1_CI_AS",
  "createMode": null,
  "creationDate": "2020-01-23T12:42:18.387000+00:00",
  "currentServiceObjectiveName": "S4",
  "currentSku": {
    "capacity": 200,
    "family": null,
    "name": "Standard",
    "size": null,
    "tier": "Standard"
  },
  "databaseId": "143534543533fab381",
  "defaultSecondaryLocation": "westeurope",
  "earliestRestoreDate": "2020-01-23T13:12:18.387000+00:00",
  "edition": "Standard",
  "elasticPoolId": null,
  "elasticPoolName": null,
  "failoverGroupId": null,
  "id": "/subscriptions/8f4920e7-d1a4-470f-ac60-d14467d00350/resourceGroups/ResourceGroupName/providers/Microsoft.Sql/servers/centuries-dev/databases/database-test2",
  "kind": "v12.0,user",
  "licenseType": null,
  "location": "northeurope",
  "longTermRetentionBackupResourceId": null,
  "managedBy": null,
  "maxLogSizeBytes": null,
  "maxSizeBytes": 268435456000,
  "name": "centuries-orestis2",
  "readScale": "Disabled",
  "recoverableDatabaseId": null,
  "recoveryServicesRecoveryPointId": null,
  "requestedServiceObjectiveName": "S4",
  "resourceGroup": "ResourceGroupName",
  "restorableDroppedDatabaseId": null,
  "restorePointInTime": null,
  "sampleName": null,
  "sku": {
    "capacity": 200,
    "family": null,
    "name": "Standard",
    "size": null,
    "tier": "Standard"
  },
  "sourceDatabaseDeletionDate": null,
  "sourceDatabaseId": null,
  "status": "Online",
  "tags": {
    "CostAllocationCode": "CostAllocationCode",
    "CostAllocationType": "CostAllocationType",
    "Environment": "Dev"
  },
  "type": "Microsoft.Sql/servers/databases",
  "zoneRedundant": false
}
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'..
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'..
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'..


```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bca10a0-5310-1ed6-8391-57a8ccafb27f
* Version Independent ID: 4144f2fa-35f1-533c-e48b-17180f03203e
* Content: [az sql server ad-admin](https://docs.microsoft.com/en-us/cli/azure/sql/server/ad-admin?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amolagar5** [comment]
Hello @axthosarouris , can you please check if Sys.database_principals is getting the right sid value. Also, does powershell work for you, portal\cli\powershell call the same REST ARM APIs. 
Topic 3 here has more details on troubleshooting steps to figure out why login is not working. 
https://techcommunity.microsoft.com/t5/azure-sql-database/troubleshooting-problems-related-to-azure-ad-authentication-with/ba-p/1062991

**Comment by axthosarouris** [comment]
Solved. I had to specify the object-id explicitly although it is an optional argument when updating the Azure AD admin

**Comment by abhiramani-iptiq** [comment]
@axthosarouris  can you pls give full command for update.i am facing same issue
