### ISSUE TITLE
az webapp deployment source config-zip keeps giving "zip deployment failed"

### ISSUE THREAD

**Issue by SidShetye** [Azure/azure-cli#11937]
**Describe the bug**
az webapp deployment source config-zip keeps giving "zip deployment failed". Note that the same .zip file can be deployed to other app service "apps" and "slots". Also note that the app-slot that fails in our CI/CD script CAN be deployed from within VS2019 (right click proj -> publish).

**To Reproduce**
`az webapp deployment source config-zip --resource-group my-res-group --name myapp --slot hot-standby --src C:\projects\service-2020.1.23.1428.zip --debug --timeout 3600`

The entire thing fails like this in just a few minutes, with or without `--debug --timeout 3600`

**Expected behavior**
web app is deployed reliably and successfully

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Windows 10, Installed via the MSI installer. Within Powershell core with `az --version` shows `2.0.80`

**Diagnostic info**

using `--debug` on the CLI, this is seen. Note, some parts are redacted for a public forum like this and I have formatted the object for better readability.

```
cli.azure.cli.core.util : Zip deployment failed. 
{'id': 'temp-0689b8f8', 
'status': 3, 
'status_text': '', 
'author_email': 'N/A', 
'author': 'N/A', 
'deployer': 'Push-Deployer', 
'message': 'Deploying from pushed zip file', 
'progress': '', 
'received_time': '2020-01-23T23:05:16.271491Z', 
'start_time': '2020-01-23T23:05:16.271491Z', 
'end_time': '2020-01-23T23:05:19.7715607Z', 
'last_success_end_time': None, 
'complete': True, 
'active': False, 
'is_temp': True, 
'is_readonly': False, 
'url': 'https://<app>-<slot>.scm.azurewebsites.net/api/deployments/latest', 
'log_url': 'https://<app>-<slot>.scm.azurewebsites.net/api/deployments/latest/log', 
'site_name': '<app>', 
'provisioningState': None
}. Please run the command az webapp log tail
                           -n <app> -g <resourcegroup>
```
Leaving aside that the CLI injects an invalid line-break on the last line (breaking the recommended command `az webapp log tail`), going to the log_url shows this:

```
{
  "Message": "An error has occurred.",
  "ExceptionMessage": "No log found for 'latest'.",
  "ExceptionType": "System.IO.FileNotFoundException",
  "StackTrace": "   at Kudu.Core.Deployment.DeploymentManager.GetLogEntries(String id) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Deployment\\DeploymentManager.cs:line 94
   at Kudu.Services.Deployment.DeploymentController.GetLogEntry(String id) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Deployment\\DeploymentController.cs:line 375"
}
```

**Additional context**

This issue seems to have been reported multiple times https://github.com/Azure/azure-cli/issues/10061 https://github.com/Azure/azure-cli/issues/7282 https://github.com/Azure/azure-cli/issues/10487 but everytime it's been closed out without any investment or investigation from Microsoft. You cannot entirely rely on customers performing all the troubleshooting to improve the quality of your products. Please improve this mindset.

If this belongs to another group (kudu?) please triage and move.

**Comment by SidShetye** [comment]
To add, we're open to other ways of deployment that could be more reliable as long as we can script it and the production build can be locally built on our CI/CD servers. Thanks

**Comment by panchagnula** [comment]
@SidShetye is this is a Linux or windows app? Are you still seeing this?

**Comment by SidShetye** [comment]
Windows app and this still happens.

**Comment by panchagnula** [comment]
@SidShetye if you  have a more recent repro for this can you send me an email at sisirap@microsoft.com with the full debug log - I need the name of the app & the timestamp in UTC so that I can check the logs on our end & contact Kudu folks. Thanks!

**Comment by SidShetye** [comment]
Let me check shortly and I’ll let you know.

**Comment by SidShetye** [comment]
Yes, still failing with latest az cli tools. I just sent the info over to your email.

**Comment by phuot** [comment]
cross referencing similar issue: https://github.com/Azure/azure-cli/issues/12125

I have a theory on why such issue occurs and I think I have found a workaround.

I suspect that the following happens:

1. Our deployment script Creates a new slot
2. Then it applies some appSetting config change (which would be detected within 30 sec)
3. Then is starts the az webapp deployment

While the deployment is in progress, the web app detect that the AppSettings changed and the AppPool is recycled (slot is restarted). Hence the Az deployment loose its connection and get cancelled.

Workaround would be to add a sleep of a little more than 30 seconds after updating the configuration, before executing the deployment step.

So far this workaround works for me, but is would be nicer the az webapp deployment was resilient to this and was able to reconnect without having to do the workaround. .

**Comment by panchagnula** [comment]
we are adding a new command az webapp log deployment to check the logs if you hit this issue, given this sounds more like a kudu deployment issue, we can use these logs to report the issue on Kudu project

**Comment by panchagnula** [comment]
Please use the following command to debug if you still see these issues during deployment https://docs.microsoft.com/en-us/cli/azure/webapp/log/deployment?view=azure-cli-latest#az-webapp-log-deployment-show

**Comment by MatthiasGwiozda** [comment]
I Had the same issue. I fixed it by disconnecting the deployment in the deployment - center of the app Service:
![image](https://user-images.githubusercontent.com/22172694/100196951-e9d95180-2ef9-11eb-8979-28eb7c2f96e2.png)

It seems like there is some magic going on when the deployment center is activated. Furthermore I removed this files on the server and in the git - repository:

- .deployment
- deploy.cmd

Afterwards I could deploy with `az webapp deployment source config-zip` without errors

**Comment by faceoffers28** [comment]
Same issue. I'm deploying a BOT using the CLI instructions. When I leave out the .deployment file, the Zip Deployment works, but my BOT doesn't. :(

When I include a .deployment file in the Bots root directory zip file, I get this error message in Deployment Center (Preview) for the App Service. I also get a Zip Deployment Failed message in the Command Prompt window.

Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "D:\local\Temp\zipdeploy\extracted" -o "D:\home\site\deployments\tools" --aspNetCore "C:\Users<username>\Source\Repos\MyBot\MyBot\MyBot.csproj"'. D:\Program Files (x86)\SiteExtensions\Kudu\91.21119.4922\bin\node_modules\kuduscript\lib\generator.js:90 throw new Error("The project file path should be a sub-directory of the repository root"); } ; ^

Here are my CLI commands.

az bot prepare-deploy --lang Csharp --code-dir "./Source/Repos/MyBot.Bot/MyBot.Bot" --proj-file-path "C:\Users\<username>\Source\Repos\MyBot.Bot\MyBot.Bot\MyBot.Bot.csproj"

az webapp deployment source config-zip --resource-group "BOTQnARG" --name "MYBOTAPP" --src "C:\Users\<username>\Source\Repos\MyBot.Bot\MyBot.Bot\Data.zip" --timeout 3600

I can't imagine the MyBot\MyBot directory structure (didn't check the box when creating the Project) or a . in the Project name could be the issue, but who knows.

**Comment by faceoffers28** [comment]
I removed the . in the Project name and folders, but it still didn't work.

Here is my new .deployment file.

[config]
SCM_SCRIPT_GENERATOR_ARGS=--aspNetCore "C:\Users\Brian\Source\Repos\MyBot\MyBot\MyBot.csproj"

**Comment by faceoffers28** [comment]
I finally got it to work. The .deployment file should look like this. I used Notepad++ to edit it.

    ```
[config]
    SCM_SCRIPT_GENERATOR_ARGS=--aspNetCore "MyBot.csproj"

```
When you run the following command, it creates the wrong file.

    `az bot prepare-deploy --lang Csharp --code-dir "./Source/Repos/MyBot/MyBot" --proj-file-path "C:\Users\<username>\Source\Repos\MyBot\MyBot\MyBot.csproj"
`
