### ISSUE TITLE
After adding extension named aks-preview ("az extension add --name aks-preview"), SyntaxError occurs

### ISSUE THREAD

**Issue by zer0big** [Azure/azure-cli#11930]
## Describe the bug

**Command Name**
`az aks update`

**Errors:**
```
invalid syntax (custom.py, line 1181)
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 523, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 291, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 290, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
azure/cli/core/__init__.py, ln 528, in get_op_handler
    op = import_module(mod_to_import)
lib64/python2.7/importlib/__init__.py, ln 37, in import_module
    __import__(name)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 1181
    f'save them to the storage account '
    ^
SyntaxError: invalid syntax
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update -n {} -g {} --attach-acr {}`

## Environment Summary
```
Linux-3.10.0-957.12.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.70 *

Extensions:
aks-preview 0.4.27

```
## Additional Context

I'm trying to configure ACR integration for existing AKS clusters refer to [this page](https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration?toc=/azure/container-registry/toc.json&bc=/azure/container-registry/breadcrumb/toc.json)

But error occurs like following. 
`[root@zerovm CoreAppDemo]# az aks update -n zeroaksdemo -g demo0123 --attach-acr $acrName
az aks: 'update' is not in the 'az aks' command group. See 'az aks --help'.
[root@zerovm CoreAppDemo]# az extension add --name aks-preview
The installed extension 'aks-preview' is in preview.
[root@zerovm CoreAppDemo]# az aks update -n zeroaksdemo -g demo0123 --attach-acr $acrName
The command failed with an unexpected error. Here is the traceback:

invalid syntax (custom.py, line 1181)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 523, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 291, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 290, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/commands.py", line 97, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 488, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 528, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1181
    f'save them to the storage account '
    ^
SyntaxError: invalid syntax

To open an issue, please run: 'az feedback'`

So I open this issue. 
Help me please.
Thank you in advance.

**Comment by jluk** [comment]
@zer0big can you update you az version and try again since you're on an older build?

@sauryadas for the attach acr issues with what looks like a storage error.

**Comment by zer0big** [comment]
@jluk Thank you so so much :) After updating az version, It works perfectly.
