### ISSUE TITLE
webapp: Web app container memory issue.Cannot set increased memory

### ISSUE THREAD

**Issue by clg-rd** [Azure/azure-cli#11939]
## Describe the bug

**Command Name**
`az webapp config appsettings set`

**Errors:**
```
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
azure/cli/core/util.py, ln 273, in shell_safe_json_parse
    return json.loads(json_or_dict_string)
lib/python3.6/json/__init__.py, ln 354, in loads
    return _default_decoder.decode(s)
lib/python3.6/json/decoder.py, ln 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.6/json/decoder.py, ln 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

...

cli/command_modules/appservice/custom.py, ln 220, in update_app_settings
    setting_name, value = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config appsettings set --resource-group {} --name {} --settings {} {} {}`

## Environment Summary
```
Linux-4.15.0-74-generic-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.79 *

```

**Comment by panchagnula** [comment]
Can you share more details on how you are using the command -set needs a key-value pair. see example for more details https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az-webapp-config-appsettings-set

**Comment by panchagnula** [comment]
Closing this due to lack of response If this is still an issue with the latest version of CLI please reactivate. Thanks!
