### ISSUE TITLE
az webapp up --name <name> always fails with <name> already exists

### ISSUE THREAD

**Issue by nnja** [Azure/azure-cli#11944]
## Describe the bug

Running az webapp up with any arguments to name always fails, saying the app already exists no matter what arguments are provided.

**Command Name**
`az webapp up`

**Errors:**
```
Webapp deploy_python_polls_app_test_12i20301901 already exists. The command will deploy contents to the existing app.

Unable to retrieve details of the existing app deploy_python_polls_app_test_12i20301901. Please check that the app is a part of the current subscription
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --name {}`

## Expected Behavior

`az webapp up` command always fails, no matter the app name provided

## Environment Summary
```
macOS-10.15.2-x86_64-i386-64bit
Python 3.8.1
Shell: bash

azure-cli 2.0.80

```

**Comment by nnja** [comment]
@AzureAppServiceCLI @antcp @panchagnula Any updates on this issue?

**Comment by panchagnula** [comment]
Looking from the error message what is the active subscription set on CLI?
Do az login 
check az account show - see what the default Subscription is. If the Subscription is not the same as the Sub the app is on - then this might occur. Not something i have seen.

**Comment by panchagnula** [comment]
@nnja just to clarify this is the failure message Unable to retrieve details of the existing app deploy_python_polls_app_test_12i20301901. Please check that the app is a part of the current subscription - not that the app already exists. Please try what i commented above. Alternately run the command with --debug flag & share the details with Byron or me via email. Thanks.

**Comment by nnja** [comment]
Note that I ran into the issue trying to deploy a brand new app, not update an existing one.

I'll try the additional steps tomorrow and provide updates.

**Comment by panchagnula** [comment]
@nnja please do let me know - App Names are unique per subscription so if another Sub is already using the name then its not available - in this case probably that is what happened, in case this was for a brand new app.

**Comment by panchagnula** [comment]
@nnja please re-activate if this is still an issue

**Comment by sean-yao** [comment]
I'm getting the same error when creating a brand new hellodotnetcore app following the QuickStarts tutorial in an empty subscription:

rllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/_<mysubid**>_/providers/Microsoft.Web/sites?api-version=2019-08-01 HTTP/1.1" 200 133
msrest.http_logger: Response status: 200
msrest.http_logger: Response headers:
msrest.http_logger:     'Cache-Control': 'no-cache'
msrest.http_logger:     'Pragma': 'no-cache'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'Content-Encoding': 'gzip'
msrest.http_logger:     'Expires': '-1'
msrest.http_logger:     'Vary': 'Accept-Encoding'
msrest.http_logger:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
msrest.http_logger:     'x-ms-request-id': 'af17a3d1-9b9f-4fae-a7ff-fd6be46fa448'
msrest.http_logger:     'x-ms-correlation-request-id': 'af17a3d1-9b9f-4fae-a7ff-fd6be46fa448'
msrest.http_logger:     'x-ms-routing-request-id': 'WESTUS2:20210207T230701Z:af17a3d1-9b9f-4fae-a7ff-fd6be46fa448'
msrest.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger:     'X-Content-Type-Options': 'nosniff'
msrest.http_logger:     'Date': 'Sun, 07 Feb 2021 23:07:01 GMT'
msrest.http_logger:     'Content-Length': '133'
msrest.http_logger: Response content:
msrest.http_logger: {"value":[]}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-pwfpui04\knack\cli.py", line 233, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 659, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 722, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 714, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-o9w9ubks\azure\cli\command_modules\appservice\commands.py", line 37, in _ex_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 693, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\commands\__init__.py", line 330, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c2pcumlb\azure\cli\core\__init__.py", line 786, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-o9w9ubks\azure\cli\command_modules\appservice\custom.py", line 3701, in webapp_up
knack.util.CLIError: Unable to retrieve details of the existing app 'hellodotnetcore'. Please check that the app is a part of the current subscription

cli.azure.cli.core.azclierror: Unable to retrieve details of the existing app 'hellodotnetcore'. Please check that the app is a part of the current subscription
cli.azure.cli.core.azclierror: Unable to retrieve details of the existing app 'hellodotnetcore'. Please check that the app is a part of the current subscription

**Comment by sean-yao** [comment]
Can we reactivate this issue?

**Comment by sean-yao** [comment]
Find the cause, the webapp name should be globally unique instead of just unique under my subscription. The [docs](https://docs.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=netcore31&pivots=platform-linux)  should point out this restriction.
