### ISSUE TITLE
GeographyGroup is missed in az account list-locations result

### ISSUE THREAD

**Issue by blrchen** [Azure/azure-cli#11949]
### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.80

**Describe the bug**
GeographyGroup is missed in az account list-locations result

**To Reproduce**
az account list-locations

**Expected behavior**
GeographyGroup info for each region should be return

**Environment summary**
cli version: 2.0.80

**Additional context**
This seems introduced by recent REST api upgrade, cli should be updated to include these new location metadatas

**Comment by fengzhou-msft** [comment]
@jiasli please take a look.

**Comment by blrchen** [comment]
Would you mind sharing which release rollout would include this fix?

**Comment by yonzhan** [comment]
planned in  https://github.com/Azure/azure-cli/milestone/82

**Comment by jiasli** [comment]
Corresponding PowerShell issue: https://github.com/Azure/azure-powershell/issues/10974

**Comment by yonzhan** [comment]
service issue

**Comment by blrchen** [comment]
Any ETA for when the fix will be ready?

**Comment by yonzhan** [comment]
service team should look into this.

**Comment by jiasli** [comment]
We have bumped the SDK and API version. The feature will be released in version 2.9.0 on 07/14/2020.
