### ISSUE TITLE
az storage blob generate-sas does not support (l)ist permission

### ISSUE THREAD

**Issue by kimitake** [Azure/azure-cli#11945]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.80

**Describe the bug**
According to document, https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#az-storage-container-generate-sas, the permission supports (a)dd (c)reate (d)elete (l)ist (r)ead (w)rite, but when I set (l), the az command shows the following error message.

> az storage blob generate-sas: error: valid values are (a)dd (c)reate (d)elete (r)ead (w)rite or a combination thereof.

BTW, azure portal supports Read, Write, Delete, List, Add, Create, Update, Process

**To Reproduce**
execute az storage blob generate-sas command with --permission l

**Expected behavior**
generate sas token that has (l)list permission

**Environment summary**
OS: Ubuntu 16.04.5 LTS
installed by apt command

**Additional context**
This is same as windows cli (2.0.73)

**Comment by MyronFanQiu** [comment]
@Juliehzl Please take a look.

**Comment by kimitake** [comment]
I checked https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas
az storage **blob** generate-sas command does not support (l)ist permission but
az storage **container** generate-sas command works
So this is not a bug...

btw I have tried the following at first...
> az storage blob generate-sas --container-name containerName

**Comment by yonzhan** [comment]
@kimitake was this issue resolved?

**Comment by kimitake** [comment]
@yonzhan yes.

**Comment by vveider** [comment]
@kimitake — so how did you resolved the issue?

**Comment by Juliehzl** [comment]
> @kimitake — so how did you resolve the issue?

please use `az storage container generate-sas` instead of `az storage blob generate-sas`.

**Comment by vveider** [comment]
It does not work ¯\_(ツ)_/¯
https://github.com/Azure/azure-cli/issues/17453
