### ISSUE TITLE
az batch account show throws an exception without required arguments

### ISSUE THREAD

**Issue by sputnik13** [Azure/azure-cli#11946]
## Describe the bug

**Command Name**
`az batch account show`

**Errors:**
```
Missing required arguments. Either specify --resource-group-name and --account-name or must be logged into a batch account
Traceback (most recent call last):
cli/command_modules/batch/custom.py, ln 55, in get_account
    account_endpoint = cmd.cli_ctx.config.get('batch', 'endpoint')
python/site-packages/knack/config.py, ln 89, in get
    raise last_ex  # pylint:disable=raising-bad-type
python/site-packages/knack/config.py, ln 84, in get
    return config.get(section, option)
python/site-packages/knack/config.py, ln 155, in get
    return self.config_parser.get(section, option)
...
configparser.NoSectionError: No section: 'batch'


cli/command_modules/batch/custom.py, ln 66, in get_account
    "Missing required arguments. Either specify --resource-group-name and "
ValueError: Missing required arguments. Either specify --resource-group-name and --account-name or must be logged into a batch account
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az batch account show`

## Expected Behavior
An message should be shown to the user rather than bubbling up an exception.  This is inconsistent with how all other commands work when required parameters are not provided.

```09:17 $ az vm show
(--name | --ids) are required```

## Environment Summary
```
Darwin-19.2.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.80
azure-cli-iot-ext 0.8.3

Extensions:
azure-cli-iot-ext 0.8.3
application-insights 0.1.2

```
## Additional Context

<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by bgklein** [comment]
A message is provided for this case `Missing required arguments. Either specify --resource-group-name and --account-name or must be logged into a batch account`

With regards to the exception trace we can look into catching it in future releases.

**Comment by sputnik13** [comment]
@bgklein I understand the information is there, the bug is that this is not really an application exception, so a stacktrace shouldn't be provided, instead a user message should be output to make it consistent with the overall user experience provided by other commands.
