### ISSUE TITLE
--source-address-prefixes does not accept 'Internet' value as described in help

### ISSUE THREAD

**Issue by petermicuch** [Azure/azure-cli#11943]
When I use --source-address-prefixes 'Internet' during creation of new rule, then I get an error:
A function or parameter in policy assignment '0b6d333531ff403b84fa005d' associated with the policy definition 'b0da5005-26d0-4844-a0d0-9c7cabfbaa96' could not be validated. Please either fix the policy or remove the policy assignment to unblock. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures. The inner exception 'The template language function 'int' cannot convert provided value 'Internet' to integer value. Please see https://aka.ms/arm-template-expressions/#int for usage details.'.

Using IP address in there works fine. But literal values that are suppose to work, do not.
azure-cli                         2.0.80
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe4941c-7b46-b9fb-1c52-98e68f6354cc
* Version Independent ID: d1bc72fb-ccf9-9645-7b1d-98c91bc75a55
* Content: [az network nsg rule](https://docs.microsoft.com/en-us/cli/azure/network/nsg/rule?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
Hello. Do you mean that you meet such error when you tried to create a rule with ` --source-address-prefixes 'Internet'`?

**Comment by petermicuch** [comment]
Hello. I am terribly sorry. I tried this in other subscription that I have and it worked fine. It seems that on the one where this failed, someone from our internal IT set new policy that does not make much sense.
