### ISSUE TITLE
az keyvault set-policy: passing a variable to --object-id fails.

### ISSUE THREAD

**Issue by ghstahl** [Azure/azure-cli#11950]
## Describe the bug

**Command Name**
`az keyvault set-policy`

**Errors:**
```
An invalid value was provided for 'accessPolicies'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```
AZ_FUNC_NAME="azfun-oauth2"
APP_FRIENDLY_NAME="organics"
LOCATION="eastus2"
RESOURCE_GROUP_NAME="rg-$APP_FRIENDLY_NAME-openhack"
KEYVAULT_NAME="kv-$APP_FRIENDLY_NAME"



az webapp identity assign \
    --name $AZ_FUNC_NAME  \
    --resource-group $RESOURCE_GROUP_NAME
PRINCIPAL_ID=$(az webapp show -n $AZ_FUNC_NAME -g $RESOURCE_GROUP_NAME --query 'identity.principalId' -o json)
echo "KEYVAULT_NAME:$KEYVAULT_NAME"
echo "principalId:$PRINCIPAL_ID"



az keyvault set-policy \
    --name $KEYVAULT_NAME \
    --object-id $PRINCIPAL_ID \
    --secret-permissions get list \
    --key-permissions get list sign verify create \
    --certificate-permissions get list getissuers listissuers
```
## The Problem
```
--object-id $PRINCIPAL_ID \
```
## This Works
```
--object-id "02c27055-efb4-4b9d-bd5d-acd671ea5a10" \
```

I query for the **identity.principalId** and assign it to **PRINCIPAL_ID**.
Passing **$PRINCIPAL_ID** as the argument to **--object-id** FAILS.
Hardcoding it works.  

## Expected Behavior
Passing **$PRINCIPAL_ID** as the argument to **--object-id** SHOULD SUCCEED.

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.78 *

Extensions:
azure-devops 0.16.0

```

**Comment by fengzhou-msft** [comment]
@bim-msft please take a look.

**Comment by bim-msft** [comment]
@ghstahl Hi, could you please upgrade your cli client to the latest (2.4.0) and try it again? Thanks.
I cannot reproduce your issue, this works for me:

![image](https://user-images.githubusercontent.com/3250203/80073315-261a8d00-857a-11ea-88b3-b75762a48249.png)
![image](https://user-images.githubusercontent.com/3250203/80073356-3e8aa780-857a-11ea-9dc7-dfb851665494.png)

**Comment by ghstahl** [comment]
@bim-msft The problem is a QUOTED ```"02c27055-efb4-4b9d-bd5d-acd671ea5a10"```.
```
PRINCIPAL_ID=$(az webapp show -n $AZ_FUNC_NAME -g $RESOURCE_GROUP_NAME --query 'identity.principalId' -o json)
echo "principalId: $PRINCIPAL_ID"
PRINCIPAL_ID=$(az functionapp identity show -n $AZ_FUNC_NAME -g $RESOURCE_GROUP_NAME --query principalId -o tsv)
echo "principalId: $PRINCIPAL_ID"
```  
produces
```
principalId: "02c27055-efb4-4b9d-bd5d-acd671ea5a10"
principalId: 02c27055-efb4-4b9d-bd5d-acd671ea5a10
```
passing in the QUOTED $PRINCIPAL_ID I got from the json query FAILS.
passing in the NON-QUOTED $PRINCIPAL_ID I got from the tsv query WORKS.

So I guess user problem on my end, unless passing in that QUOTED one should be allowed.

**Comment by bim-msft** [comment]
@ghstahl Thanks, I reproduced this:
![image](https://user-images.githubusercontent.com/3250203/80172031-73e8d100-861e-11ea-97a2-65aeddeded63.png)

I will add a quick patch to support this case, and the next release date is around 4/30, which is the version 2.5.0.

**Comment by anujelanco** [comment]
AZ_FUNC_NAME="BDAZE1EBISNFA01"
RESOURCE_GROUP_NAME="BDAZE1EBISNRG01"
KEYVAULT_NAME="BDAZE1EBISNKV01"
az functionapp identity show \
    --name $AZ_FUNC_NAME  \
    --resource-group $RESOURCE_GROUP_NAME
PRINCIPAL_ID=$(az functionapp identity show -n $AZ_FUNC_NAME -g $RESOURCE_GROUP_NAME --query 'identity.principalId' -o json)
echo "principalId: $PRINCIPAL_ID"
PRINCIPAL_ID=$(az functionapp identity show -n $AZ_FUNC_NAME -g $RESOURCE_GROUP_NAME --query principalId -o tsv)
echo "principalId: $PRINCIPAL_ID" 
az keyvault set-policy \
    --name $KEYVAULT_NAME \
    --object-id $PRINCIPAL_ID \
    --secret-permissions get list \
    --key-permissions get list sign verify create \

Hey folks when I am running above command in azre cli task in azure devops I am getting a error
bash exited with code '127'.
However it is ruuning fine azure cloud shell bash script mode.

**Comment by bim-msft** [comment]
> AZ_FUNC_NAME="BDAZE1ESNFA01"
> RESOURCE_GROUP_NAME="BDAZE1ESNRG01"
> KEYVAULT_NAME="BDAZE1ESNKV01"
> az functionapp identity show
> --name $AZ_FUNC_NAME
> --resource-group $RESOURCE_GROUP_NAME
> PRINCIPAL_ID=$(az functionapp identity show -n $AZ_FUNC_NAME -g $RESOURCE_GROUP_NAME --query 'identity.principalId' -o json)
> echo "principalId: $PRINCIPAL_ID"
> PRINCIPAL_ID=$(az functionapp identity show -n $AZ_FUNC_NAME -g $RESOURCE_GROUP_NAME --query principalId -o tsv)
> echo "principalId: $PRINCIPAL_ID"
> az keyvault set-policy
> --name $KEYVAULT_NAME
> --object-id $PRINCIPAL_ID
> --secret-permissions get list
> --key-permissions get list sign verify create \
> 
> Hey folks when I am running above command in azre cli task in azure devops I am getting a error
> bash exited with code '127'.
> However it is ruuning fine azure cloud shell bash script mode.

@anujelanco Hi, we will investigate this. Gentle reminder: you can open a new issue to better describe the question, and this also help us to better track the process.
