### ISSUE TITLE
AZ Cli not working with Python > 3.6

### ISSUE THREAD

**Issue by AnassKartit** [Azure/azure-cli#11953]
## Describe the bug
when running az an error message is received if python version is not equal to python 3.6
**Command Name**
`az`

**Errors:**

-bash: /usr/local/bin/az: /usr/local/opt/python/bin/python3.6: bad interpreter: No such file or directory

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7
Shell: bash

azure-cli 2.0.77 *

Extensions:
aks-preview 0.4.17

```

**Comment by fengzhou-msft** [comment]
@AnassKartit are you running on a MacOS? How did you install azure-cli?

**Comment by fengzhou-msft** [comment]
@AnassKartit can you provide more information on how your installed azure-cli?

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please feel free to reopen the issue if it still exists.
