### ISSUE TITLE
--runtime-version & Node 12

### ISSUE THREAD

**Issue by p33t** [Azure/azure-cli#11957]
Hi,

I'd like to use Node 12:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#languages

How do I use Node 12 please?  The '--runtime-version' only accepts 8, 10.

Is it enough to specify FUNCTIONS_EXTENSION_VERSION?
https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#changing-version-of-apps-in-azure

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f254bb-7dfd-417b-b08d-f2ac34247d99
* Version Independent ID: 9d22f523-579b-ea66-04ed-20f09c72bcbb
* Content: [az functionapp](https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/appservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/_help.py)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by p33t** [comment]
FYI, I set the following two configuration app settings as things appear to be working.  I assume it's using Node 12....
        FUNCTIONS_EXTENSION_VERSION=~3
        WEBSITE_NODE_DEFAULT_VERSION=~12

**Comment by p33t** [comment]
Worth noting that **core tools 3 uses 'func.cmd'**.  Calling 'func.exe' will invoke the older core tools 2.7.

**Comment by fabiocav** [comment]
This is a good candidate for the new "stacks API" that has been exposed.

**Comment by fabiocav** [comment]
@pragnagopa for awareness. We need to wait until the API is fully available before we can leverage it here.

**Comment by pragnagopa** [comment]
Providing runtime version as part of creating function app was addressed as part issue https://github.com/Azure/azure-cli/issues/10549

@ankitkumarr - is there a restriction the values provided for `--runtime-version`? If yes, list needs to be updated to include node 12. Leveraging information in stacks api will help with validating combinations for functions extension version and runtime version.

**Comment by kamperiadis** [comment]
Closing this as we already use the API to determine what runtime versions are supported. You can view that list using the `az functionapp list-runtimes` command.
