### ISSUE TITLE
az ad sp create-for-rbac need proper example of what to expect from the result

### ISSUE THREAD

**Issue by wjia7** [Azure/azure-cli#11956]
In general, I would be much appreciated to know what is the resulting output from each of the az ad command. Like what is the output looks like and how can they be used.
For example, I am running some tests with 'az ad sp create-for-rbac'. The result of this CLI return a JSON object that contains appId,displayName, Name, password and tenant. What is this "password" field? Is this the client's secret for my service principal app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by fengzhou-msft** [comment]
@jiasli please take a look.

**Comment by yonzhan** [comment]
add to S168

**Comment by qianwens** [comment]
@wjia7 yes, it is a random password generated by CLI which is the secret of the created service principle app.
