### ISSUE TITLE
When trying to install AZ AKS CLI

### ISSUE THREAD

**Issue by srcsakthivel** [Azure/azure-cli#11958]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
<urlopen error [Errno 11001] getaddrinfo failed>
Traceback (most recent call last):
CLI2\lib\urllib\request.py, ln 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
CLI2\lib\http\client.py, ln 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
CLI2\lib\http\client.py, ln 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
CLI2\lib\http\client.py, ln 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
CLI2\lib\http\client.py, ln 1026, in _send_output
    self.send(msg)
...
Azure\CLI2\lib\socket.py, ln 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed


CLI2\lib\urllib\request.py, ln 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.75 *

```

**Comment by jluk** [comment]
@fengzhou-msft can you validate why the msftbot is pinging us multiple times?

@srcsakthivel can you retry this with the latest CLI build? otherwise let's visit the repros in person.

**Comment by srcsakthivel** [comment]
Thanks, that error is gone after updating the CLI.

Now I'm getting this now, 

kubectl get nodes

Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

Should I submit a separate issue?

**Comment by jluk** [comment]
Can you double check you have the right credentials setup in config/az aks get-credentials? That error usually means its permission failure and your config file isn't setup correctly.

**Comment by fengzhou-msft** [comment]
@jluk due to some network latency, I accidentally added back `triage` label.

**Comment by jluk** [comment]
Closing this issue to resolve in person if needed.
