### ISSUE TITLE
SIG name must be unique within subscription

### ISSUE THREAD

**Issue by ebuzek** [Azure/azure-cli#11967]
Shared Image Gallery name must be unique within subscription (regardless of resource group), but CLI does not provide a way to check if gallery with this name exists.

**Errors:**
```
The gallery name '${gallery_name}' is not unique within the subscription 'xxxx'. Please pick another gallery name.
```

## Synopsis
- our scripts generating images and pushing them to SIG need to ensure that the SIG exists
- to check if SIG with some name exists, CLI requires `--resource-group` parameter and checks only within the specified resource group
- however, when creating SIG with the same name under a different resource group, error occurs since SIG names must be unique within subscription.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```
# create rg 'groupA'
az group create -g groupA -l westus

# create SIG 'sig' in groupA:
az sig create -g groupA -r sig

# create rg 'groupB'
az group create -g groupB -l westus

# check if gallery 'sig' exists in groupB:
az sig show -g groupB -r sig
The Resource 'Microsoft.Compute/galleries/sig' under resource group 'groupB' was not found.

# Try creating it in groupB
az sig create -g groupB -r sig
The gallery name 'sig' is not unique within the subscription 'xxxx'. Please pick another gallery name.
```

## Expected Behavior

Either
a) Make SIG names unique only within resource groups
b) Provide a way to work with SIG globally (i.e. allow checking if SIG exists without specifying resource group) 

## Environment Summary

azure-cli 2.0.80

```
## Additional Context

Started running into this issue after upgrading from 2.0.29 to 2.0.80

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
add to S168

**Comment by qwordy** [comment]
This is a known behavior. I'll contact SIG people. I think method b) is more promising.

**Comment by qwordy** [comment]
You can also use `az sig list --query [].name` to list all sig names in the subscription.

**Comment by qwordy** [comment]
`az sig show` calls the following HTTP GET method. Resource group is required.
https://docs.microsoft.com/en-us/rest/api/compute/galleries/get

**Comment by yungezz** [comment]
hi @ebuzek could you pls try @qwordy suggestion to show existing sig names?

**Comment by qwordy** [comment]
Quotes from a senior engineer of SIG team.
> Actually this is because galleryuniqueid is made up of subid-galleryname. And we want galleryUniqueId to be unique across the whole world
