### ISSUE TITLE
Unable to create cosmosdb collection using new CLI commands

### ISSUE THREAD

**Issue by rudolphjacksonm** [Azure/azure-cli#11962]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I'm unable to create a CosmosDB Mongodb collection using the new syntax that replaces the deprecated `az cosmosdb collection create` command:

```
az cosmosdb mongodb collection show --account-name "<my-cosmosdb-account>" --database-name "<cosmosdb-name>" --resource-group "<my-rg>" --name "<app-mongo>"
```
When I try this, I receive this error: `Operation failed with status: 'MethodNotAllowed'. Details: Requests for API mongodb are not supported for this account.` Unfortunately it doesn't tell me exactly what is wrong with the CosmosDB account I have set up. I've tried deleting and recreating it with the MongoDB API set to 3.6 instead of 3.2, but that doesn't make any difference.

I've also tried running the command with the `--verbose` flag, but this just adds time measurement to the output.

**To Reproduce**
1. Create a CosmosDB account in UK South. Create a MongoDB database in the CosmosDB account with reserved throughput of 400 Request Units.
2. Attempt to create collection via `az cosmosdb mongodb collection create`

**Expected behavior**
I expect to be able to create a MongoDB collection in the database. If this operation can't be completed, I would expect the error to specify what is wrong with the CosmosDB account/database that prevents collections from being created via the CLI.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
➜ az --version
azure-cli                         2.0.80

command-modules-nspkg              2.0.3
core                              2.0.80
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
aks-preview                       0.4.16
```

**Additional context**

**Comment by shurd** [comment]
Hi @rudolphjacksonm thank you for opening this issue. Based on the error message, it seems as though the account is not a MongoDB account. Could you share an activity id or a sample account name where you saw the problem so we can investigate? You can also open a support case via the portal and share the information there.

**Comment by rudolphjacksonm** [comment]
Hi @shurd , turns out this was a silly typo on my end that led me to try sending these commands to a SQL account that was similarly named to our MongoDB account. In hindsight the error message makes sense, however it may be a bit clearer for it to state something like `Requests for API mongodb are not supported for this account of kind: GlobalDocumentDB`
