### ISSUE TITLE
VMSS Extension version may not match compare to TypeHandlerVersion 

### ISSUE THREAD

**Issue by rayifu** [Azure/azure-cli#11961]
Background: 
I wanted to create the same environment to verify the production environment and created it.
I found may the issue.
But Not in a hurry.  Slowly OK.
It may OmsAgentForLinux issue.  I don't know where to ask for an issue.

**Describe the bug**
- The installing extension may not parse version.
    - I choose version 1.11 by az-cli, but VMSS was installed 1.12.15 by waagent.
        ```log
        [JohnSmith01@000001 ~]$ rpm -aq |grep -i oms
        omsagent-1.12.15-0.x86_64
        omsconfig-1.1.1-927.x86_64
        auoms-2.0.1-19.x86_64
        [JohnSmith01@000001 ~]$ 
        ##----
        AutoUpgradeMinorVersion    Name              Publisher                             TypeHandlerVersion
        ##--------------------------  ----------------  ------------------------------------  --------------------
        True                       OmsAgentForLinux  Microsoft.EnterpriseCloud.Monitoring  1.11
        ```
- I guess that it is depends to  Azure internal feature or program.

**To Reproduce**
1. Set vmss extention 
    ```bash
    az vmss extension set \
        --resource-group $vmssRG \
        --vmss-name $vmssName \
        --name OmsAgentForLinux \
        --publisher Microsoft.EnterpriseCloud.Monitoring \
        --settings "{'workspaceId':'xxxx'}" \
        --protected-settings "{'workspaceKey':'xxxxx'}" \
        --version 1.11
    ```
2. Upgrade instance
   ```bash
   az vmss update-instances --instance-ids "*" --name $vmssName --resource-group $vmssRG
   ```
3. Check OmsAgentForLinux version on VMSS (with login)
   ```bash
   rpm -aq |grep -i oms
   ```
**Expected behavior**
- I expect that OmsAgentForLinux version can choose by `--version` on command of `az vmss extention set`.
- But if the Extension TypeHandlerVersion don't select for OmsAgentForLinux version, then would you please teach me info.
- I guess the issue may affect to not only VMSS and but also VM.

**Environment summary**
- My PC
    - azure-cli version: 2.0.79
    - Shell type: Bash
    - Excute on: Ubuntu 18.04.3 LTS on WSL
    - OS: Microsoft Windows 10

- VMSS 
    - OS: RHEL 7.6

**Additional context**
None.

**Comment by yungezz** [comment]
thanks for reporting the issue. we'll look at and update whether it's azure CLI issue or not.

**Comment by rayifu** [comment]
@yungezz  I retry to create VMSS by az-cli with add option `--no-auto-upgrade true`.
I successd older version.
```bash
[JohnSmith01@000001 ~]$ rpm -aq |grep -i oms
omsagent-1.11.0-9.x86_64
omsconfig-1.1.1-926.x86_64
auoms-2.0.0-13.x86_64
[JohnSmith01@000001 ~]$
```

My mission completed.
It is self resolved.  Im glad.

So the issue was cleared. Would you please close the issue?

Thanks you for your supporting.

**Comment by rayifu** [comment]
I have a good idea of feature.
- reqired option --no-auto-upgrade when `--version` option  selected.

then everyone

**Comment by rayifu** [comment]
@qwordy  @yungezz How do you feel my comment?
> I have a good idea of feature.
> - reqired option `--no-auto-upgrade` when `--version` option  selected.
> 
> then everyone will realize to need option. And they wil not happen like me same this issue.
> 
> would you please discuss this as it may be a rare case, please include this feature if possible.

**Comment by qwordy** [comment]
I update help of --version first. Changing it to required when --version is set needs more discussion. It is a breaking change.

**Comment by qwordy** [comment]
The update is available in latest version of Azure CLI.
