### ISSUE TITLE
Error message for param errors during VM creation not useful

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#11968]
in the following example, the create fails because of the ':' in the VM name, but the `az vm create` command displays the template deployment error message, but not the useful inner one.  

```
jason@Azure:~$ az vm create -n https: -g jrs-deleteme --image ubuntults
Azure Error: InvalidTemplateDeployment
Message: The template deployment 'vm_deploy_HhIGshnclhLPK2tHxoMz2MgZ4OOaCnhE' is not valid according to the validation procedure. The tracking id is '5410215d-72d0-4e1d-a26d-428146b8d4e4'. See inner errors for details.
Exception Details:
        Error Code: TemplateFailedPrevalidation
        Message: The template request has multiple validation failures involving one or more Microsoft.Network resources. Please check details for information about each resource.
```

**Comment by yonzhan** [comment]
@qwordy  please take a look.

**Comment by qwordy** [comment]
The response has detailed information, but the output does not show details.
I have two options:
(1) Add validation of VM name in Azure CLI.
(2) Output complete information.

Response:
{"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'vm_deploy_v0m1MchXeatew9f78OVNmINKGNRbUBAG' is not valid according to the validation procedure. The tracking id is 'a99297db-5bc7-4720-9703-ecd3094dc51c'. See inner errors for details.","details":[{"code":"TemplateFailedPrevalidation","message":"The template request has multiple validation failures involving one or more Microsoft.Network resources. Please check details for information about each resource.","details":[{"code":"InvalidResourceName","message":"Resource name https:VNET is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."},{"code":"InvalidResourceName","message":"Resource name https:NSG is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."},{"code":"InvalidResourceName","message":"Resource name https:PublicIP is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."},{"code":"InvalidResourceName","message":"Resource name https:VMNic is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."}]}]}}

**Comment by qwordy** [comment]
I opened a PR to fix it. I adopted option 2.

**Comment by qwordy** [comment]
The update is available in latest version of Azure CLI.
