### ISSUE TITLE
Support option equivalent to `SkipTemplateParameterPrompt` from PowerShell for ARM template validation

### ISSUE THREAD

**Issue by ggirard07** [Azure/azure-cli#11972]
**Is your feature request related to a problem? Please describe.**
While validating ARM template and parameter file, there is no way to avoid prompting for missing parameters.
When this is automated in a pipeline to proceed to template validation, the pipeline will hang until timeout.

By having an option to disable prompting for missing parameters, this will allow to get validation result right away when we expect parameter file or command line to contains all required parameters.

**Describe the solution you'd like**
Add a new parameter to `az group deployment validate` to support not prompting for missing parameter.

**Describe alternatives you've considered**
Only alternative right now is to decrease the task timeout in the pipeline to get it to fail more quickly... but this still does not indicate the real issue.

**Additional context**
It looks like the Az PowerShell module already support this kind of option with `SkipTemplateParameterPrompt` for both `Test-AzResourceGroupDeployment` and `New-AzDeployment`

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
add to S168
