### ISSUE TITLE
az webapp config show and set use different spellings for the runtime "linuxFxVersion" and "linux-fx-version" respectively 

### ISSUE THREAD

**Issue by TimSBenjamin** [Azure/azure-cli#11971]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az webapp config show and set use different spellings for the runtime "linuxFxVersion" and "linux-fx-version" respectively 

**To Reproduce**
set runtime version & attempt to get the runtime version you need to re-spell. 

**Expected behavior**
Typically you arrow up and expect to just change set to show and add query, the different spelling is not obvious

**Environment summary**
Cloud Shell

**Additional context**

**Comment by panchagnula** [comment]
@Kotasudhakarreddy can you take a look at this issue please. Thank you.

**Comment by Kotasudhakarreddy** [comment]
will look in to it.

**Comment by Kotasudhakarreddy** [comment]
able to repro the issue and will look further to fix the issue.

**Comment by panchagnula** [comment]
@TimSBenjamin - assuming I am understanding the question correctly,
The command using the property name as linux-fx-version, https://docs.microsoft.com/en-us/cli/azure/webapp/config?view=azure-cli-latest#az-webapp-config-set
is following the CLI naming conventions. The JSON output in all cases does return the properties as per the api-defintion (minus the hyphen '-') Hope this answers your question. Thanks!

**Comment by TimSBenjamin** [comment]
@panchagnula - I'm not sure we are talking about the same thing. I don't mean the output of the commands. I mean the commands to set and show independently. See below. The two should be the same, which one doesn't matter.

- az webapp config show linuxFxVersion

- az webapp config set linux-fx-versiony
