### ISSUE TITLE
application-gateway does not select https when key-vault-secret-id is provided

### ISSUE THREAD

**Issue by sputnik13** [Azure/azure-cli#11973]
## Describe the bug

**Command Name**
`az network application-gateway create`

**Errors:**
`Azure Error: InvalidTemplateDeployment
Message: The template deployment 'ag_deploy_a1KNUFoglHPEILIat6AQYPFZ68M2uwz6' is not valid according to the validation procedure. The tracking id is '9a36237b-b1bd-41ee-8e56-382b89e12ce0'. See inner errors for details.
Exception Details:
        Error Code: ApplicationGatewayPortNotValidForProtocol
        Message: Port 443 is not valid for protocol Http in httpListeners /subscriptions/c647028f-2fe0-4de2-b47e-882734a9b02a/resourceGroups/mpae-ep-eastus/providers/Microsoft.Network/applicationGateways/app-gateway-de75be87/httpListeners/appGatewayHttpListener.
`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network application-gateway create ... --key-vault-secret-id <secret_id> ...`

## Expected Behavior
application gateway is created with a front end listener set to use HTTPS as the front end protocol.

## Environment Summary
```
Darwin-19.2.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.80
azure-cli-iot-ext 0.8.3

Extensions:
azure-cli-iot-ext 0.8.3
application-insights 0.1.2

```

**Comment by yonzhan** [comment]
add to S165.

**Comment by sputnik13** [comment]
fixed as of https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.0.81
