### ISSUE TITLE
az webapp config show "phpversion" is inconsistent across Windows & Linux WebApps

### ISSUE THREAD

**Issue by TimSBenjamin** [Azure/azure-cli#11970]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
On Windows the php Version is stored in "phpVersion" on linux it is stored in "linuxFxVersion" and on linux "phpVersion" is blank. This is very confusing and the user may easily think that setting the php version is not working. 

**To Reproduce**
run az webapp config show --resource-group <resource-group-name> against a Web App configured for PHP on Windows & Linux respectively. See the difference

**Expected behavior**
populate phpversion on both Windows & Linux

**Environment summary**
Cloud shell

**Additional context**
The PowerShell version of the same get-AzWebApp returns nothing related to PHP on Linux or Windows

**Comment by panchagnula** [comment]
Not a CLI issue but an API issue and we are aware of this. @btardif FYI.

**Comment by Kon-formity** [comment]
This is still an issue with the API - would be great to address this
Also raised here https://feedback.azure.com/d365community/idea/76bc18bd-e56e-ed11-a81b-000d3ae49307
