### ISSUE TITLE
What is an OData filter?  

### ISSUE THREAD

**Issue by armtuk** [Azure/azure-cli#11985]
The term 'OData' filter under --filter option for az ad sp list should be a link here to a description of what that means.

This is REALLY important because az ad sp list shows pages and pages and pages of information, most of which isn't relevant, so filtering feels critical.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
add to S168

**Comment by richeney** [comment]
I was really hoping this issue would have an explanation and examples for OData filters!

**Comment by richeney** [comment]
Some old documentation:
<https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/howto/azure-ad-graph-api-supported-queries-filters-and-paging-options#filter>

Examples: 
```
az ad sp list --filter "displayName eq 'governance'" --output jsonc
az ad sp list --filter "startswith(displayName, 'gov')" --query "[].displayName" --output yaml
```

**Comment by qianwens** [comment]
This issue is fixed in the sprint 167
