### ISSUE TITLE
AppConfiguration: Missing example of referencing secret from KeyVault

### ISSUE THREAD

**Issue by djsowa** [Azure/azure-cli#11992]
Hi.

Do You have any example of adding reference to KeyVault using CLI ?

M.

Based on: https://github.com/Azure/azure-cli-extensions/issues/1225

**Comment by yonzhan** [comment]
@bim-msft  do you have any context about this issue ?

**Comment by djsowa** [comment]
Sure.
There is no example how to reference secrets from KeyVault to AppConfiguration instance.
it took me some time to figure out how to add this reference using CLI.


You can find example in original issue,

**Comment by bim-msft** [comment]
> @bim-msft do you have any context about this issue ?

@yonzhan Sorry I'm not familiar with this, seems this issue is related to `az appconfig`

**Comment by djsowa** [comment]
It seems that `az appconfig` has been merged to main CLI, it's no longer extension I guess.

**Comment by yonzhan** [comment]
@djsowa  you may need to get help from appconfig service team since CLI team does not own appconfig related commands.

**Comment by shenmuxiaosen** [comment]
Hi @djsowa we are not shipping extension anymore as we have merged to main CLI. Regarding to your question about adding keyvault reference, please download the latest CLI and do                    
```az appconfig kv set-keyvault -h``` and you will see explanations and examples. We will update the official CLI doc shortly.

**Comment by djsowa** [comment]
I see this documentation is already available. So this issue can be closed since documentation was all I want to solve ;)
Thanks.
