### ISSUE TITLE
Error parsing comments after the last parameter, variable or output

### ISSUE THREAD

**Issue by nilshedstrom** [Azure/azure-cli#11995]
If you write a comment after the last parameter, variable or output you will get a error message.
If you try to deploy the template you will get the same error message.

If you validate the file with 
Test-AzResourceGroupDeployment -ResourceGroupName <rg> -TemplateFile <file>
it does not report any errors.

## Describe the bug

**Command Name**
`az group deployment validate`

**Errors:**
```
Expecting ',' delimiter: line 1 column 169 (char 168)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group deployment validate -g {} --template-file {} -j`

## Expected Behavior
This is a valid ARM template and should be reported as such.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.80

```
## Additional Context
This is the ARM template that I used
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "variables": {
        "variable1": "value"
        //Comment
    },
    "resources": [],
    "outputs": {},
    "functions": []
}
```

**Comment by nilshedstrom** [comment]
The following arm-template validates and ok:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "variables": {
        //Comment
        "variable1": "value"
    },
    "resources": [],
    "outputs": {},
    "functions": []
}
```

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
add to S168
