### ISSUE TITLE
Metadata comments in param file throw an error 

### ISSUE THREAD

**Issue by ovidiu10** [Azure/azure-cli#12009]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.80

**Describe the bug**
using in param file metadata for validate ARM template will get an error
 "message": "The request content was invalid and could not be deserialized: 'Could not find member 'metadata' on object of type 'DeploymentParameterDefinition'. Path 'properties.parameters.storageAccountType.metadata'

**To Reproduce**
JSON - ARM Template 
JSON - ARM Param File should contains metadata 
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {   
    "storageAccountType": {
      "value": "Standard_LRS",
      "metadata": {
        "description": "AAA"
      }
    }
  }
}
run cli command 
az group deployment validate -g rg-test -j --template-file storage.json --parameters @storage.param.json

throw error:
{
  "error": {
    "additionalInfo": null,
    "code": "InvalidRequestContent",
    "details": null,
    "message": "The request content was invalid and could not be deserialized: 'Could not find member 'metadata' on object of type 'DeploymentParameterDefinition'. Path 'properties.parameters.storageAccountType.metadata', line 1, position 90.'.",
    "target": null
  },
  "properties": null
}

**Expected behavior**
No error 

**Environment summary**
azure-cli                         2.0.80
command-modules-nspkg              2.0.3
core                              2.0.80
nspkg                              3.0.4
telemetry                          1.0.4
Python (Linux) 3.6.5 (default, Jan 13 2020, 05:04:39)
[GCC 7.4.0]
But I try also with Windows OS same issue

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
@zhoxing-ms  please take a look.

**Comment by zhoxing-ms** [comment]
@ovidiu10 Service does not support the `metadata` in template parameters file, azure-cli sends the user's parameters file to the Service without modification, so the situation is in line with expectations.

**Comment by zhoxing-ms** [comment]
So this is implemented according to the Service design. Do you have any other questions? @ovidiu10

**Comment by yonzhan** [comment]
@ovidiu10 any update for this issue?

**Comment by alex-frankel** [comment]
We are taking a look at this. The ARM backend is validating this schema incorrectly, as it should allow the metadata property. This works if you deploy with powershell, but that is because powershell is stripping this property before it sends it to ARM.

cc @filizt and @anthony-c-martin who are looking at swagger & schema updates for Microsoft.Resources.

**Comment by ovidiu10** [comment]
thanks

**Comment by yonzhan** [comment]
@alex-frankel @filizt @anthony-c-martin  any update for this issue?

**Comment by alex-frankel** [comment]
Did this get implemented? Are we ignoring the metadata property?

**Comment by zhoxing-ms** [comment]
@alex-frankel No, as previously communicated, CLI does not modify the customer's ARM template, but instead the validation by the Service allows metadata properties.

**Comment by kamilzzz** [comment]
I'm getting the same error but according to the schema the metadata should be supported.

https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#

@yonzhan @zhoxing-ms

**Comment by zhoxing-ms** [comment]
@alex-frankel @filizt @anthony-c-martin  May I ask if the service is currently adding the support for `metadata`?

**Comment by joem-msft** [comment]
Why was this closed? It's fine if the CLI chooses to use service as validation. But the end result to the user is an inconsistent behavior when using the same parameters file using Az DevOps deployment task (PowerShell based?) vs a local `az deployment group validate` command.

**Comment by alex-frankel** [comment]
I think it got closed because it is not an Az CLI issue, but rather an ARM service side issue that is validating incorrectly and generating the false-positive error. 

Adding the internal work item here for reference, but don't have an ETA for when it will be resolved:
https://msazure.visualstudio.com/One/_workitems/edit/7378495

**Comment by MarekLani** [comment]
same goes for allowedValues field, min and maxLength ! faced this issue with auto generated Azure Stream Analytics template which is not usable when deploying using Azure CLI.
