### ISSUE TITLE
Is it possible to take the output of one gateway setting, and use it to configure another?

### ISSUE THREAD

**Issue by NiryaAestus** [Azure/azure-cli#12001]
I have a dev enviroment in one subscription and a Live one in another. I would like to copy the rules from one to another. It'd be nice if I could use the output of: "az network application-gateway waf-config show" and set them using "az network application-gateway waf-config set"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68725488-1e3a-ac2d-c454-bcedd26e4b70
* Version Independent ID: 706d7f46-f132-10ab-423c-4a640d65d2dc
* Content: [az network application-gateway waf-config](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/waf-config?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsntcy** [comment]
@MyronFanQiu, please help take a look, thanks.

**Comment by MyronFanQiu** [comment]
@NiryaAestus Hello. Currently, the format of CLI's response is json. Natively, we cannot use `az network application-gateway waf-config set` to send them back. You have to write a script to do this. If you want, you can try `az resourse update`. This should be simpler for you.

**Comment by MyronFanQiu** [comment]
@NiryaAestus Hi. Do you have any other question? It's possible to use python sdk, `az rest` or `az resource` directly to send back the response. But currently, we don't support json input in each command.

**Comment by NiryaAestus** [comment]
Ok thaink you. No I don't any other questions.

**Comment by MyronFanQiu** [comment]
@NiryaAestus Thanks for raising this issue. Actually some of our team members are trying to support such usage. But it should be a big feature and need some time to design and implement. I close this issue first.
