### ISSUE TITLE
Unclear of what "server" and "name" should be when using azure sql db import 

### ISSUE THREAD

**Issue by hulvei3** [Azure/azure-cli#12007]
When using `azure sql db import` to create a new db from a bacpac file from storage, I get the "Can not perform requested operation on nested resource." as it would require the to-be database to already be present. "Can not perform requested operation on nested resource. Parent resource '&lt;server&gt;/&lt;db-name&gt;' not found."

When trying to omit it, it also fails. When running with --debug I can see I get a 400 on /Microsoft.Sql/servers/testenv-westeurope/databases/principal-portal-db/extensions/import which makes sense as this database doesn't exist yet. But how should I then be able to create it? Create first and then import?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bdd674-b454-e863-c943-9c979b466a92
* Version Independent ID: b15341f9-3f1b-00e0-a1c2-970f25a6ab03
* Content: [az sql db](https://docs.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#az-sql-db-import)
* Content Source: [src/azure-cli/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jaredmoo** [comment]
The database must be already created and must be empty before executing import.
