### ISSUE TITLE
Keyvault: Create key via importing - BYOK preview

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#12003]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Keyvault

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
To support create key via importing. such as
`az keyvault key create --vault-name bim-kv6 --name mykek --kty RSA-HSM --size 2048 --ops import`

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
https://github.com/Azure/azure-rest-api-specs/pull/8175/files

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

**Comment by yonzhan** [comment]
Keyvault BYOK

**Comment by yungezz** [comment]
> Keyvault BYOK

? :)

**Comment by bim-msft** [comment]
Supported in PR: #12030 
This feature is only supported on canary regions (region with suffix `euap`, like `eastus2euap`)
