### ISSUE TITLE
SQL Server Admin Password Update Doesn't Work From Azure CLI on Powershell

### ISSUE THREAD

**Issue by abushokry** [Azure/azure-cli#12017]
**Command Name**
`az sql server update`

Updating the --admin-password doesn't work if I use powershell but works if I use the az interactive shell

**Errors:**
No Errors get displayed, and a JSON representation of the SQL Server is returned as if the command succeeded

## To Reproduce:
1- Run this command in _Powershell_
`az sql server update --admin-password <PASSWORD> --name <SQLSRVNAME> --resource-group <RESGROUP>`

2- Test connecting to the SQL Server. This would give you a "Login Failed" error

3- Run the exact same command in the _az interactive_ shell. 

4- Test connecting to the SQL Server. You will login successfully

## Expected Behavior
The command should work in Powershell

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.78 *

Extensions:
application-insights 0.1.1
interactive 0.4.3
resource-graph 1.0.0

```

**Comment by jaredmoo** [comment]
I am positive that setting password works in general. If you are encountering problems in one specific command shell, it is very likely to be a symbol escaping problem. For example, powershell will intepret `$` character as variable substitution.

**Comment by abushokry** [comment]
> I am positive that setting password works in general. If you are encountering problems in one specific command shell, it is very likely to be a symbol escaping problem. For example, powershell will intepret `$` character as variable substitution.

Please take this string "TZ!bj*ORFhueC4J4UeoT_kNuo0^oSeuV" nothing in this password string would cause a powershell parsing problem, yet it doesn't work.

**Comment by jaredmoo** [comment]
I believe `^` is a special character in powershell :)
