### ISSUE TITLE
functionapp:Show Python version in Azure Functions

### ISSUE THREAD

**Issue by Hazhzeng** [Azure/azure-cli#12012]
**Is your feature request related to a problem? Please describe.**
Currently, Azure Functions support multiple versions of language worker (Python 3.6, 3.7 and 3.8). 
We need some visualization in the worker version.

**Describe the solution you'd like**
In `az functionapp show`, we should have a panel showing the function app runtime (node, python, dotnet) and runtime version (~8, 3.6, ~3).

**Comment by Hazhzeng** [comment]
This is a feature request, mod, please assign to me.

**Comment by kamperiadis** [comment]
Hi @Hazhzeng currently, you can view the Python version by looking at the linuxFxVersion attribute in your function app. Is that what you were looking for?
