### ISSUE TITLE
"git add --patch" fails due to missing perl package

### ISSUE THREAD

**Issue by ossm1db** [Azure/azure-cli#12015]
### Azure CLI Version
2.0.80

### Expected Behavior
No error

### Actual Behavior
`git: 'add--interactive' is not a git command. See 'git --help'.`

### Steps to Reproduce
```
docker run -it --rm mcr.microsoft.com/azure-cli:2.0.80
bash-5.0# git clone https://github.com/Azure/azure-cli.git
Cloning into 'azure-cli'...
...
bash-5.0# cd azure-cli/
modify any file, e.g. README.md
bash-5.0# git add -p
git: 'add--interactive' is not a git command. See 'git --help'.
```

### Important Factoids
To fix: `apk add --no-cache perl`

**Comment by yungezz** [comment]
thanks for reporting the issue. we'll investigate it.

**Comment by fengzhou-msft** [comment]
@ossm1db This docker image has azure-cli installed. Its main purpose is for a quick run of azure cli commands. Why do you need to clone source code and modify it inside the container?

**Comment by ossm1db** [comment]
I am using it for exactly that. I created an image based on azure-cli which adds Terraform, Helm, and kubectl to provide an encapsulated development environment for Azure with no setup required. I use Visual Studio Code with the Remote Containers extension to attach to the container and edit files. A volume is connected for persistence.

Aside from my purposes, git is installed by the azure-cli Dockerfile. While it may be a fault of the packaging system since git depends on perl, git is incompletely installed at the moment and cannot provide the missing functionality without an adjustment.
