### ISSUE TITLE
public-ip-addresses not listing ips correctly.

### ISSUE THREAD

**Issue by giorni** [Azure/azure-cli#12013]
## Describe the bug

**Command Name**
`az vm list-ip-addresses`

**Errors:**
```
'/subscriptions/b5b.../resourceGroups/rck.../providers/Microsoft.Network/publicIPAddresses/rck...'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/cli/core/__init__.py, ln 493, in default_command_handler
    return op(**command_args)
cli/command_modules/vm/custom.py, ln 923, in list_vm_ip_addresses
    public_ip_address = ip_address_lookup[ip_configuration.public_ip_address.id]
KeyError: '/subscriptions/b5b.../resourceGroups/rck.../providers/Microsoft.Network/publicIPAddresses/rck...'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az vm list-ip-addresses -g {}`

## Expected Behavior

List the public ips that do exist at the context, or show proper error (maybe regarding permission at 'Microsoft.Network/publicIPAddresses'?)

## Environment Summary
```
Linux-4.4.0-154-generic-x86_64-with-debian-jessie-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.80

```
## Additional Context

`public_ip_addresses` which is used to create the `ip_adress_lookup` is empty, but there is public ip information set on vms.

Custom role has this permissions:
```
"permissions": [
      {
        "actions": [
          "Microsoft.Compute/virtualMachines/read",
          "Microsoft.Compute/virtualMachines/instanceView/read",
          "Microsoft.Network/networkInterfaces/ipconfigurations/read",
          "Microsoft.Network/networkInterfaces/read",
          "Microsoft.Network/virtualNetworks/read",
          "Microsoft.Network/virtualNetworks/subnets/read",
          "Microsoft.ClassicNetwork/virtualNetworks/read",
          "Microsoft.Network/networkInterfaces/ipconfigurations/read",
          "Microsoft.Network/networkInterfaces/read",
          "Microsoft.Network/routeTables/read",
          "Microsoft.Network/routeTables/routes/read",
          "Microsoft.Network/routeTables/routes/write",
          "Microsoft.Network/routeTables/write"
        ],
        "dataActions": [],
        "notActions": [],
        "notDataActions": []
      }
    ]
```

**Comment by jsntcy** [comment]
@qwordy, please help take a look, thanks.

**Comment by qwordy** [comment]
I haven't reproduced you issue. public_ip_addresses is assigned to
```
public_ip_addresses = network_client.public_ip_addresses.list_all()
```
It's equivalent to `az network public-ip list`. What's the output of `az network public-ip list` in your environment?

**Comment by giorni** [comment]
Yes. `az network public-ip list` is returning an empty array, which I discovered due to one missing permission. What happens is that after returning the empty array when running `az vm list-ip-addresses` it tries to access builds a dict and tries to access it, breaking. It probably had the right permission to list NIC ip configurations, which are then used to make this access.

At this method:
```
public_ip_addresses = network_client.public_ip_addresses.list_all()
ip_address_lookup = {pip.id: pip for pip in list(public_ip_addresses)}

...

for ip_configuration in nic.ip_configurations:
    network_info['privateIpAddresses'].append(ip_configuration.private_ip_address)
    if ip_configuration.public_ip_address:
        public_ip_address = ip_address_lookup[ip_configuration.public_ip_address.id]
```

**Comment by qwordy** [comment]
Hi giorini, what's the current status? Can you list IP address now?

**Comment by giorni** [comment]
With the right permissions I was able to list it properly, thank you.

**Comment by yonzhan** [comment]
@giorni  was this issue resolved?

**Comment by giorni** [comment]
The pull request by @qwordy would fix it. Right now the client still breaks when I haven't set the proper permissions.

**Comment by qwordy** [comment]
> 
> 
> With the right permissions I was able to list it properly, thank you.

Glad to see that. You are welcome.

**Comment by qwordy** [comment]
> 
> 
> The pull request by @qwordy would fix it. Right now the client still breaks when I haven't set the proper permissions.

The PR is merged. It will be released on 05/19/2020.
