### ISSUE TITLE
Operation failed with status: 'Unauthorized'. Details: Required Header authorization is missing. 

### ISSUE THREAD

**Issue by jjlauterbach** [Azure/azure-cli#12025]
## Describe the bug

**Command Name**
`az cosmosdb sql database create`

**Errors:**
```
Operation failed with status: 'Unauthorized'. Details: Required Header authorization is missing. Ensure a valid Authorization token is passed.
ActivityId: d3f22954-c56e-45ed-bfdd-c6e4d70138df, Microsoft.Azure.Documents.Common/2.9.2
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az cosmosdb sql database create --account-name {} --name {} --resource-group {} --debug`

## Environment Summary
```
macOS-10.13.4-x86_64-i386-64bit
Python 3.8.1
Shell: bash

azure-cli 2.0.80

```

**Comment by jjlauterbach** [comment]
After some continued investigation, it turns out the it may be due to special characters (forward slash) being used in the name of the cosmos database.  

I removed those and the error went away.

**Comment by shurd** [comment]
Hi @jjlauterbach thank you for following up. I am going to close this issue now. If you encounter any other problems, please open another issue.
