### ISSUE TITLE
Role definition update fails with KeyError: 'roleName'

### ISSUE THREAD

**Issue by Krystof-pl** [Azure/azure-cli#12027]
## Describe the bug

**Command Name**
`az role definition update`

**Errors:**
```
'roleName'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.6/site-packages/six.py, ln 693, in reraise
    raise value
...
azure/cli/core/__init__.py, ln 493, in default_command_handler
    return op(**command_args)
cli/command_modules/role/custom.py, ln 55, in update_role_definition
    return _create_update_role_definition(cmd, role_definition, for_update=True)
cli/command_modules/role/custom.py, ln 84, in _create_update_role_definition
    role_name = role_definition['roleName']
KeyError: 'roleName'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role definition update --role-definition {}`

## Environment Summary
```
Linux-4.15.0-76-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.80

```

**Comment by arrownj** [comment]
Hi @jiasli , could you please help take a look at this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by jiasli** [comment]
It seems the `--role-definition` parameter lacks `roleName`. Please make sure `--role-definition` is provided in the correct format. You may check the example with 

```jsonc
> az role definition update -h

Command
    az role definition update : Update a role definition.

Arguments
    --role-definition [Required] : Description of an existing role as JSON, or a path to a file
                                   containing a JSON description.
...

Examples
    Update a role using the output of "az role definition list"
        az role definition update --role-definition '{ \
>>          "roleName": "Contoso On-call", \ 
            "Description": "Perform VM actions and read storage and network information.", \
            "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-
        xxxxxxxxxxxx/providers/Microsoft.Authorization/roleDefinitions/xxxxxxxx-xxxx-xxxx-xxxx-
        xxxxxxxxxxxx", \
            "roleType": "CustomRole", \
```

**Comment by gcormier** [comment]
This is not an end user issue. The role definition is here : https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles

There is no `roleName` element in the format as defined by Microsoft.

**Comment by jiasli** [comment]
Years ago, Azure used **Azure Service Management (ASM)**, then migrated to **Azure Resource Manager (ARM)**. 

- The JSON in doc [Custom roles for Azure resources](https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles#custom-role-example) is the old-fashioned PascalCase ASM-style JSON
- The ARM-style JSON is defined in the [Role Definitions - Create Or Update](https://docs.microsoft.com/en-us/rest/api/authorization/roledefinitions/createorupdate) REST API

The mapping is 

| ASM      | ARM REST spec       | Definition
|----------|---------------------|-------------
| Name     | properties.roleName | The literal name,  like `Virtual Machine Operator`
| Id       | name                | A GUID, like `6134dd49-621f-4c59-94db-a56b3f7e45f8`
| -        | id                  | A resource ID, like `/subscriptions/subID/providers/Microsoft.Authorization/roleDefinitions/6134dd49-621f-4c59-94db-a56b3f7e45f8`

I have created issue https://github.com/MicrosoftDocs/azure-docs/issues/53213 to inform ARM team about the inconsistency.

The design of Azure CLI is to maintain backward compatibility: 

```         
           1                    
ASM JSON ─────→ az role definition create ─────→ ARM JSON 
   │                                               │ ↑
   │       ┌───────────────────────────────────────┘ │
   │2.1    │2.2                                      │
   └───────┴──→ az role definition update ───────────┘
```

1. In `az role definition create`, `--role-definition` only accepts the ASM-style JSON. CLI retrieves the literal name from `Name` property: https://github.com/Azure/azure-cli/blob/1f34245e83fbb68777c26a764f9cb5e8b86c0051/src/azure-cli/azure/cli/command_modules/role/custom.py#L97-L98

    The response is an ARM JSON, where `name` becomes a GUID and the literal name is stored in `roleName`. 
    
    ```
    > az role definition create --role-definition '@role.json'
    {
        ...
        "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Authorization/roleDefinitions/c7fb3da9-7b6c-41ff-9c78-30984334ab79",
        "name": "c7fb3da9-7b6c-41ff-9c78-30984334ab79",
        ...
        "roleName": "Virtual Machine Operator",
        "roleType": "CustomRole",
        "type": "Microsoft.Authorization/roleDefinitions"
    }
    ```

2. In `az role definition update`, 

    1. If `--role-definition` doesn't contain `id` (which indicates this is an ASM-style request), CLI retrieves `Name`, as `az role definition create` does (but this is problematic as ARM JSON may also have `name`): https://github.com/Azure/azure-cli/blob/1f34245e83fbb68777c26a764f9cb5e8b86c0051/src/azure-cli/azure/cli/command_modules/role/custom.py#L87

    2. If `--role-definition` contains `id` (which indicates this is an ARM-style response), CLI retrieves `roleName`: https://github.com/Azure/azure-cli/blob/1f34245e83fbb68777c26a764f9cb5e8b86c0051/src/azure-cli/azure/cli/command_modules/role/custom.py#L82-L85

We will move to ARM style and deprecate ASM style in the future. For now, please always refer to `--help` for CLI's usage.

**Comment by jiasli** [comment]
To summarize, the output of `az role definition create` and `az role definition update` is **ARM-style response JSON**.

As for the input:

| Supported? | `az role definition create` | `az role definition update` 
| - |:-:|:-:
| ASM-style request JSON | ✔ | ✔
| ASM-style response JSON | ❌ | ❌
| ARM-style request JSON | ❌ | ❌
| ARM-style response JSON | ❌ | ✔

❌ indicates the actual behavior is undefined.
