### ISSUE TITLE
--policy example request

### ISSUE THREAD

**Issue by vtjc2002** [Azure/azure-cli#12039]
Is there an example of "az storage account management-policy create" where it shows how to pass in --policy as JSON?

**Comment by arrownj** [comment]
Hi @Juliehzl , could you please help take a look at this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by qianwens** [comment]
@vtjc2002 , you can find some json samples for policy here https://docs.microsoft.com/en-us/azure/storage/blobs/storage-lifecycle-management-concepts?tabs=azure-portal
