### ISSUE TITLE
az deployment validate returns exit code 0 when an error is encountered in json

### ISSUE THREAD

**Issue by chaos-panda** [Azure/azure-cli#12031]
## Describe the bug
When you run az deployment validate command against your ARM templates locally or on a CI/CD returns exit code 0 even though you encountered an error and your json error response is not null.

**Command Name**
`az deployment validate`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az deployment validate --location {} --subscription {} --template-file {} --parameters {} --parameters {} --parameters {}`

## Expected Behavior
Expected to have other than 0 exit code for non-valid templates so those can be captured locally or in CI/CD pipelines.

## Environment Summary
```
Linux-4.15.0-76-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.81

Extensions:
aks-preview 0.4.11

```

**Comment by arrownj** [comment]
Hi @zhoxing-ms , could you please help take a look at this ?

**Comment by yonzhan** [comment]
add to S166.
