### ISSUE TITLE
az extension add: "Unknown extension type. Only Python wheels are supported."

### ISSUE THREAD

**Issue by SimonAlling** [Azure/azure-cli#12034]
## Describe the bug

**Command Name**
`az extension add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


Unknown extension type. Only Python wheels are supported.
Traceback (most recent call last):
  File "/home/alling/lib/azure-cli/local/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/alling/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
ValueError: Unknown extension type. Only Python wheels are supported.
```

## To Reproduce:
- `az extension add --source azure-devops`

## Expected Behavior

I was hoping the extension would install correctly.

## Environment Summary
```
Linux-5.0.0-38-generic-x86_64-with-Ubuntu-19.04-disco
Python 2.7.16
Shell: bash

azure-cli 2.0.81

```
## Additional Context

When I first encountered the error, I had Azure CLI 2.0.79. I updated to 2.0.81 to see if that would help; my Azure CLI now has Python 2 instead of Python 3:

```
$ az --version
azure-cli                         2.0.81

command-modules-nspkg              2.0.3
core                              2.0.81
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/home/alling/lib/azure-cli/bin/python'
Extensions directory '/home/alling/.azure/cliextensions'

Python (Linux) 2.7.16 (default, Oct  7 2019, 17:36:04) 
[GCC 8.3.0]

Legal docs and information: aka.ms/AzureCliLegal

* DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. 
A future version of Azure CLI will drop support for Python 2.7.


Your CLI is up-to-date.
```

**Comment by arrownj** [comment]
Hi @jsntcy , could you please help to check this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by jsntcy** [comment]
@SimonAlling,
If you run help command `az extension add -h`, you'll see the following help messages and examples
![image](https://user-images.githubusercontent.com/16348853/81150816-f3798700-8fb2-11ea-8787-b3079533d053.png)

You can see that if you want to install extension by name, you need run `az extension add --name azure-devops` instead of `az extension add --source azure-devops`

**Comment by SimonAlling** [comment]
> @SimonAlling,
> If you run help command `az extension add -h`, you'll see the following help messages and examples
> ![image](https://user-images.githubusercontent.com/16348853/81150816-f3798700-8fb2-11ea-8787-b3079533d053.png)
> 
> You can see that if you want to install extension by name, you need run `az extension add --name azure-devops` instead of `az extension add --source azure-devops`

Aha. I think `az` should definitely warn if `--source` is used with a non-URL then, instead of throwing a completely incomprehensible error. Although that may not be easily implemented if `--source` works with local files too.
