### ISSUE TITLE
functionapp: Need to add support for PowerShell 7 for Azure Functions in the --runtime-version property 

### ISSUE THREAD

**Issue by eamonoreilly** [Azure/azure-cli#12044]
When PowerShell is selected for --runtime in az functionapp create, we need to allow for --runtime-version a value of [6,7]

This should then set the site config property with:

"siteProperties": {
      "properties": [
        {
          "name": "PowerShellVersion",
          "value": "~7"
        }

**Comment by arrownj** [comment]
@eamonoreilly , thanks for reporting, we are looking at it.

**Comment by pierrejeandev** [comment]
For future visitors.
Can be done with:
`az functionapp update --resource-group rg-myapp-weu-int  --name func-myapp-myfunction-weu-int --set siteConfig.powerShellVersion=~7`

**Comment by kamperiadis** [comment]
Closing as this is no longer relevant since we rely on the stacks API to determine what runtime versions are supported.
