### ISSUE TITLE
az aks get-credentials fails after upgrading to v2.0.81

### ISSUE THREAD

**Issue by jyennaco** [Azure/azure-cli#12042]
## Describe the bug

After upgrading Azure CLI from version 2.0.79 to 2.0.81 I was not unable to run:

`az cloud set --name AzureUSGovernment`
`az configure --defaults location=usgovvirginia`
`az aks install-cli`
`az login --service-principal --username USERNAME --password PASS --tenant TENANT`
`az aks get-credentials --resource-group kube-resource-group --name kube-name`
```
No registered resource provider found for location 'usgovvirginia' and API version '2019-11-01' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31, 2019-02-01, 2019-04-01, 2019-06-01, 2019-08-01, 2019-10-01'. The supported locations are 'usgovvirginia'.
```

* I am in a CSP account, in environment `AzureUSGovernment `, location `usgovvirginia`
* Observed on the MacOS version of Azure CLI
* Observed on microsoft/azure-cli docker container:(https://hub.docker.com/r/microsoft/azure-cli 
* Workaround: Rolled back to an older docker container

**Command Name**
`az aks get-credentials`

**Errors:**
```
No registered resource provider found for location 'usgovvirginia' and API version '2019-11-01' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31, 2019-02-01, 2019-04-01, 2019-06-01, 2019-08-01, 2019-10-01'. The supported locations are 'usgovvirginia'.
```

##### Output minutes prior to upgrading the Azure CLI:

$ az --version
azure-cli                         2.0.79 *

command-modules-nspkg              2.0.3
core                              2.0.79 *
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/local/Cellar/azure-cli/2.0.79_1/libexec/bin/python'
Extensions directory '/Users/yennaco/.azure/cliextensions'

Python (Darwin) 3.8.1 (default, Dec 27 2019, 18:06:00) 
[Clang 11.0.0 (clang-1100.0.33.16)]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 updates available. Consider updating your CLI installation. Instructions can be found at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

Please let us know how we are doing: https://aka.ms/clihats
$ `az aks get-credentials --resource-group kube-resource-group --name kube-name`
```
Merged "jcf-azure-kubernetes" as current context in /Users/yennaco/.kube/config
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Upgrade Azure CLI to 2.0.81
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
macOS-10.15.2-x86_64-i386-64bit
Python 3.8.1
Shell: bash

azure-cli 2.0.81

```

**Comment by arrownj** [comment]
@jyennaco , thanks for reporting, we are looking at it.

**Comment by jyennaco** [comment]
Thanks so much! 😀

**Comment by arrownj** [comment]
Hi @Azure/aks-pm , could you please help with this issue ? Seems there are several similar issues about this recently.

**Comment by jluk** [comment]
@sauryadas do you know if 2019-11-01 is supported in US Gov? The error seems to say no, sounds like we might need to rev new API version compat for sovereign clouds.

**Comment by karataliu** [comment]
'2019-11-01' is available in US Gov now, please retry.

**Comment by jluk** [comment]
Closing as this looks resolved according to @karataliu - please comment if this is not the case though.

**Comment by jgull77** [comment]
Issue seems to be reoccuring:
Mac az cli version:  2.3.1
az aks get-credentials --resource-group oneid-pre --name oneid-int-pre-1
No registered resource provider found for location 'usgovvirginia' and API version '2020-03-01' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31, 2019-02-01, 2019-04-01, 2019-06-01, 2019-08-01, 2019-10-01, 2019-11-01, 2020-01-01, 2020-02-01'. The supported locations are 'usgovvirginia, usgovarizona, usgovtexas'.

**Comment by jluk** [comment]
@jgull77 you are hitting a different error, above was triggered by the cluster dep on 2019-11-01 which is available now as you can see in your error message.

The cluster you're trying to access seems to be dependent on the 2020-03-01 API which has not been released for AzureGov yet.

@karataliu do you have an ETA for 2020-03-01 release?

**Comment by mihaimircea** [comment]
Hi, I'm getting this from Azure Cloud Shell trying to execute `az aks show` on a 1.18.14 cluster
```
No registered resource provider found for location 'usgovvirginia' and API version '2021-02-01' for type 'managedClusters'
```
So the version of the cluster dictates the API version az cli will use ?

**Comment by karataliu** [comment]
@mihaimircea azure-cli version will control api version to use, should be working now(api rollout out done there)

**Comment by mihaimircea** [comment]
Yes, working now, thanks!
