### ISSUE TITLE
functionapp:Azure Function is not disabled when using Azure CLI command to disable it

### ISSUE THREAD

**Issue by ajklotz** [Azure/azure-cli#12041]
## Describe the bug
According to this documentation, a function in a function app can be disabled by running the command. It creates a name value pair in application settings which then disables the function. While it does create the name value pair, the function state does not toggle according to the desired state. 

**Command Name**
`az functionapp config appsettings set`

**Errors:**
n/a

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp config appsettings set --name $functionAppName --resource-group $resourceGroup --setting AzureWebJobs.functionName.Disabled=false`

## Expected Behavior
The function should be disabled just as when you go into Azure Portal to manually disable/enable a function
## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.78 *
Azure Function version ~1
```

**Comment by ajklotz** [comment]
This appears to be a bug with Azure Function version 1. If I upgrade to Azure Function 2, the Azure CLI command successfully toggles the state of the function.

**Comment by arrownj** [comment]
@ajklotz , thanks for reporting, we are looking at it.

**Comment by kamperiadis** [comment]
Hi @ajklotz Is this an issue you are still experiencing? This does not appear to be CLI related since the CLI would just add the app setting.
