### ISSUE TITLE
Loading az completion in ZSH adds a debug line

### ISSUE THREAD

**Issue by uda** [Azure/azure-cli#12046]
**Describe the bug**
Adding `source /opt/az/bin/az.completion.sh` to `.zshrc` or any other relevant shell profile file causes each shell session to start with an output saying `Enabling ZSH compatibility mode`

**To Reproduce**
Add `source /opt/az/bin/az.completion.sh` to `.zshrc`
Open a new shell

**Expected behavior**
Nothing to be printed to the shell when opening a new session

**Environment summary**
Installed using apt repository for ubuntu

**Additional context**
It is a simple fix, I just don't want to sign the CLA

https://github.com/Azure/azure-cli/blob/5000b3582d4fe4224a90ba7556fa213af482bc9c/src/azure-cli/az.completion.sh#L3

**Comment by yungezz** [comment]
Thanks for reporting the issue, we'll look at it.

**Comment by yonzhan** [comment]
add to S166.

**Comment by goodwillhacking** [comment]
@uda This was bugging me too. As a temporary fix in az.completion.sh - comment out the
`echo 'Enabling ZSH compatibility mode';
`
Assuming az is installed in /opt/ - the file will be in /opt/az/bin 
I am on Ubuntu 18.0.4 
Hope this helps

![image](https://user-images.githubusercontent.com/3004543/74209103-ef57fa80-4c4b-11ea-8ba8-1539c8866120.png)

**Comment by uda** [comment]
Thanks @goodwillhacking, I did that initially, but since the package is constantly being updated, it gets overwritten every time, so I got tired from doing it every week or two

**Comment by jiasli** [comment]
We have fixed this issue by removing the warning, and will release it in this sprint [S168](https://github.com/Azure/azure-cli/milestone/85).
