### ISSUE TITLE
az role definition create

### ISSUE THREAD

**Issue by dmartinezrubio** [Azure/azure-cli#12053]
## Describe the bug

**Command Name**
`az role definition create`

**Errors:**
```
'7558107e-6142-4c86-9443-3eb65200b47c'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrest/service_client.py, ln 181, in put
    request = self._request('PUT', url, params, headers, content, form_content)
python3.6/site-packages/msrest/service_client.py, ln 108, in _request
    request = ClientRequest(method, self.format_url(url))
python3.6/site-packages/msrest/service_client.py, ln 151, in format_url
    url = url.format(**kwargs)
KeyError: '7558107e-6142-4c86-9443-3eb65200b47c'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role definition create --role-definition {}`

## Environment Summary
```
Linux-5.0.0-37-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.81

```

**Comment by yungezz** [comment]
thanks for reporting the issue, we're looking at it.

**Comment by arrownj** [comment]
Hi @dmartinezrubio , it seems that the error log in truncated in the middle. Could you please help paste the full log to us? And may I ask does his exception always happen for `az role definition create` in your environment?

It probably that the format of your `--role-definition` is not right. Could you also share the json file you used to us ? Thanks in advance.

**Comment by arrownj** [comment]
Hi @dmartinezrubio , you can use `az role definition create -h` to see the example of json format. I will close this issue first if there is no more problems. You can reopen it or submit a new one if you have other concerns. Thanks
