### ISSUE TITLE
Cannot execute command "az ad app create"

### ISSUE THREAD

**Issue by mamhh** [Azure/azure-cli#12051]
Dears,
I've the role "Owner" on my subscription and when I try to execute below command
` az ad app create --display-name "MyApp" `  using AZURE CLI
I get below error message
`Insufficient privileges to complete the operation.`

Please advise ..

**Comment by arrownj** [comment]
Hi @jiasli , could you please help check this ?

**Comment by jiasli** [comment]
[Owner](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#owner) is an ARM RBAC concept on subscription level. To create AAD app, you will need AAD permission equal or higher than [Application Administrator](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#application-administrator).

**Comment by mamhh** [comment]
Thanks a lot @jiasli , I can execute the command now
