### ISSUE TITLE
az network application-gateway create creates a basic public IP (v2 SKU)

### ISSUE THREAD

**Issue by mohamedsaif** [Azure/azure-cli#12059]
[Enter feedback here]
When providing a name for the --public-ip-address $AGW_PIP_NAME argument for non-existing IP address, the CLI will provision a basic IP address which is not compatible with AG v2 which will cause the command to fail.

Expected behavior to provision a Standard IP address instead.

```
Deployment failed. Correlation ID: 624f4f0b-a03d-4e18-8d15-986f258df939. {
  "error": {
    "code": "ApplicationGatewayInvalidPublicIpSku",
    "message": "Application gateway /subscriptions/ID/resourceGroups/central-infosec-weu/providers/Microsoft.Network/applicationGateways/devcap-agw-weu with SKU WAF_v2 can only reference public ip with Standard SKU.",
    "details": []
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d85e1042-f9fe-a899-7a64-99796558a7aa
* Version Independent ID: 2573afce-d2fa-6f5f-3647-ea8696b8d0e2
* Content: [az network application-gateway](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arrownj** [comment]
Hi @MyronFanQiu , could you please help with this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by MyronFanQiu** [comment]
@mohamedsaif Hello. CLI cannot get such limitation information. We just to create a general default public ip. If you want to create WAF_v2 application-gateway, you'd better to create a standard public ip using `az network public-ip create`.

**Comment by mohamedsaif** [comment]
> @mohamedsaif Hello. CLI cannot get such limitation information. We just to create a general default public ip. If you want to create WAF_v2 application-gateway, you'd better to create a standard public ip using `az network public-ip create`.

@MyronFanQiu I understand your point. This is not the issue. Issue is when a missing public IP name is sent to az network application-gateway create with a v2 sku, the command will create a new basic public IP (behind the scenes) and then fails (because of the automatically created PIP by the CLI command is basic not standard)
