### ISSUE TITLE
Automation AD B2C tenant Creation

### ISSUE THREAD

**Issue by houssems** [Azure/azure-cli#12058]
I want to automate creation of AD B2C Create Tenant and linked to my existing AD. So I'm asking if there's a CLI or ansible playbook can automate this.

**Comment by arrownj** [comment]
Hi @jiasli , could you please help with this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by jiasli** [comment]
I don't think Azure CLI currently can have the ability to manage B2C tenants without public API or SDK from AAD, as shown in [Deploy and manage Active Directory B2C using ARM templates and RM PowerShell cmdlets](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/18960694-deploy-and-manage-active-directory-b2c-using-arm-t). 

If the API is published, you may use `az rest` with the API for automation.
