### ISSUE TITLE
az webapp list-runtimes

### ISSUE THREAD

**Issue by TomBonnerAtTFL** [Azure/azure-cli#12057]
## Describe the bug
Running `az webapp list-runtimes` is the easiest way to cause a crash likely related to a host of other failures we're seeing, all related to `knack\cli.py`.

**Command Name**
`az webapp list-runtimes`

**Errors:**
```
'bool' object has no attribute 'provider'
Traceback (most recent call last):
Temp\pip-install-1o1fsnhi\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 608, in execute
azure\cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 659, in _run_job
Local\Temp\pip-install-1o1fsnhi\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 636, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 493, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 704, in list_runtimes
azure\cli\command_modules\appservice\custom.py, ln 2159, in stacks
azure\cli\command_modules\appservice\custom.py, ln 2180, in _load_stacks
AttributeError: 'bool' object has no attribute 'provider'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az webapp list-runtimes`

## Expected Behavior

Not crash.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Shell: Windows Terminal

azure-cli 2.0.81

Extensions:
application-insights 0.1.1
interactive 0.4.3

```

**Comment by arrownj** [comment]
@TomBonnerAtTFL , thanks for reporting, we are looking at it.

**Comment by TomBonnerAtTFL** [comment]
Hi @arrownj, is there any way to roll-back a version of Az-cli? Our CI pipeline is using the latest and it's now blocking our release.

**Comment by TomBonnerAtTFL** [comment]
If anyone else is finding this issue, you can roll-back by using direct version referencing:
```
apt-get install azure-cli=2.0.79-1~xenial --allow-downgrades 
```

**Comment by panchagnula** [comment]
issue will be fixed in 2.0.82 - please use the edge builds in the meantime Same as #12159.

**Comment by mrscommentor** [comment]
It is failing even in your own Cloud Shell for both bash and Powershell, maybe you should prioritize this, we are people running production here.

**Comment by panchagnula** [comment]
@mrscommentor this fix has already been merged to our dev branch - and is available with this release https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md

Not sure what version cloud shell is using .

**Comment by mrscommentor** [comment]
Thanks I see that, and cloud shell has now been upgraded to 2.1.0 I can see. Unfortunately the list does no longer contain DOTNETCORE versions, why is that?

``` sh
mrs@Azure:~$ az webapp list-runtimes
[
  "aspnet|V4.7",
  "aspnet|V3.5",
  "node|0.6",
  "node|0.8",
  "node|0.10",
  "node|0.12",
  "node|4.8",
  "node|6.5",
  "node|6.9",
  "node|6.12",
  "node|7.10",
  "node|8.1",
  "node|8.4",
  "node|8.5",
  "node|8.9",
  "node|8.10",
  "node|8.11",
  "node|10.0",
  "node|10.6",
  "node|10.14",
  "node|10.15",
  "php|5.6",
  "php|7.0",
  "php|7.1",
  "php|7.2",
  "php|7.3",
  "python|2.7",
  "python|3.6",
  "java|1.7|Tomcat|7.0",
  "java|1.7|Tomcat|8.0",
  "java|1.7|Tomcat|8.5",
  "java|1.7|Tomcat|9.0",
  "java|1.7|Jetty|9.1",
  "java|1.7|Jetty|9.3",
  "java|1.7|Java|SE",
  "java|1.8|Tomcat|7.0",
  "java|1.8|Tomcat|8.0",
  "java|1.8|Tomcat|8.5",
  "java|1.8|Tomcat|9.0",
  "java|1.8|Jetty|9.1",
  "java|1.8|Jetty|9.3",
  "java|1.8|Java|SE",
  "java|11|Tomcat|7.0",
  "java|11|Tomcat|8.0",
  "java|11|Tomcat|8.5",
  "java|11|Tomcat|9.0",
  "java|11|Jetty|9.1",
  "java|11|Jetty|9.3",
  "java|11|Java|SE"
]
```

**Comment by michaelringholm** [comment]
So I wrote in the previous post that dotnet core is missing completely from the list, and it **still is** I can see, why close it then?
