### ISSUE TITLE
Make "az deployment create" commands use --handle-extended-json-format by default

### ISSUE THREAD

**Issue by alex-frankel** [Azure/azure-cli#12066]
**Resource Provider**
Microsoft.Resources/deployments

**Description of Feature or Work Requested**
Make the flag `--handle-extended-json-format` the default behavior for all variants of `az deployment create` (`deployment group create`, `deployment sub create`, `deployment tenant create`, `deployment mg create`)

**Minimum API Version Required**
all

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
N/A

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
2/14

**Comment by yonzhan** [comment]
add to S166.
