### ISSUE TITLE
Command to add RdpGateway setting for DevTest Lab

### ISSUE THREAD

**Issue by gaburn** [Azure/azure-cli#12063]
**Is your feature request related to a problem? Please describe.**
I can't find a way to programatically add an RdpGateway to a DevTest Lab. 

**Describe the solution you'd like**
This command works for updating the vmCreationResourceGroupId which is displayed in the same configuration pane in the azure portal as the RdpGateway setting:

az resource update -g $labResourceGroup -n $labName --resource-type "Microsoft.DevTestLab/labs" --api-version 2018-10-15-preview --set properties.vmCreationResourceGroupId=$rgId

However, this command does not work:
    az resource update -g $labResourceGroup -n $labName --resource-type "Microsoft.DevTestLab/labs" --api-version 2018-10-15-preview --set properties.extendedProperties.RdpGateway="gateway.mydomain.net"

az : ERROR: Couldn't find 'extendedProperties' in 'properties'.

It looks like 'extendedProperties' only appears in the resource after an RdpGateway is manually added through the portal. I need a way to perform this update with code. Thanks!

**Describe alternatives you've considered**

**Additional context**

**Comment by arrownj** [comment]
Hi @zhoxing-ms , could you please help with this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by zhoxing-ms** [comment]
@gaburn What kind of resource is the RdpGateway? How did you create the RdpGateway on portal?

**Comment by zhoxing-ms** [comment]
Because I haven't received any reply for a long time, I will close this issue first. If you still have questions, please feel free to give feedback.
