### ISSUE TITLE
Include IotHub part of the API profile 2019-03-01-hybrid

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-cli#12069]
**Resource Provider**
IOTHub , AzureStack

**Description of Feature or Work Requested**
Azurestack recently added IotHub as one of the supported services. We have decided to add the IOTHub as part of the existing profile 2019-03-01-hybrid profile. 2019-03-01-hybrid profile for CLI does not include IOTHub. This request is to add the IOTHub part of the profile and add necessary conditions if needed

**Minimum API Version Required**
https://aka.ms/2019profile defines the api versions needed for each supported resource types in azurestack

**Swagger Link**
https://aka.ms/2019profile

**Target Date**
March 16th

**Comment by yonzhan** [comment]
add to S166.
