### ISSUE TITLE
CLI calls the wrong version SDK when a different version SDK is installed in current pyenv

### ISSUE THREAD

**Issue by gogowings** [Azure/azure-cli#12062]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Details are in https://github.com/microsoft/MLOpsPython/issues/136

**To Reproduce**
NOTE: to repro the error reported in https://github.com/microsoft/MLOpsPython/issues/136 you will need more setup, such as creating ML workspace, register a model etc. The following repro step is simplified. You won't see an error but you will see the symptom of different version SDK is loaded.

step 1: install latest azure-cli-ml: az extension add -n azure-cli-ml (or az extension update -n azure-cli-ml). 
   You should get version 1.0.85. SDK version is correct as you can see from 
      $HOME/.azure/cliextensions/azure-cli-ml/azureml_core*

step 2: create a pyenv, can be conda, venv, doesn't matter. I use venv
    python -m venv test-venv
    source test-venv/bin/activate

step 3: install a different version of azureml-core
    pip install azureml-core==1.0.79

step 4: run an ml CLI command:  az ml workspace list -g abc --debug (doesn't matter whether resource group abc exists or not)
    In the debug level log, you will see SDK 1.0.79 is loaded (you will see 'azureml-core 1.0.79' in debug output)

In the real error case, there is a change in azureml-core 1.0.81 which introduces a new required parameter.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by yungezz** [comment]
thanks for reporting the issue. @fengzhou-msft  is on this.

**Comment by fengzhou-msft** [comment]
need to figure out how to reproduce this issue.

**Comment by fengzhou-msft** [comment]
There's security concerns for putting extension directory in front position of sys.path in the above fix PR. And it can not solve the conflicts when 2 extensions depend on the same SDK but with different versions.

We recommend to use vendored SDKs in extensions. An example: https://github.com/Azure/azure-cli-extensions/tree/master/src/storage-preview/azext_storage_preview/vendored_sdks
