### ISSUE TITLE
Include Eventhub part of the azurestack profile 2019-03-01-hybrid 

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-cli#12068]
**Resource Provider**
EventHub - AzureStack

**Description of Feature or Work Requested**
 Azurestack recently added EventHub as one of the supported services. We have decided to add the EventHub as part of the existing profile 2019-03-01-hybrid profile. 2019-03-01-hybrid profile for CLI does not include eventhub. This request is to add the EventHub part of the profile and add necessary conditions if needed

**Minimum API Version Required**
https://aka.ms/2019profile defines the api versions needed for each supported resource types in azurestack

**Swagger Link**
https://aka.ms/2019profile

**Target Date**
March 16

**Comment by yonzhan** [comment]
add to S166.
