### ISSUE TITLE
--dns-servers

### ISSUE THREAD

**Issue by kylecweeks** [Azure/azure-cli#12079]
When executing az network vnet create including --dns-servers the space-separated list is returned as invalid. It functions when submitted as an array.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc99d572-abdb-ab6b-7a9a-c6951a1c1466
* Version Independent ID: 0a50e966-cbc8-8960-c01f-e117cac842d4
* Content: [az network vnet](https://docs.microsoft.com/en-us/cli/azure/network/vnet?view=azure-cli-latest#az-network-vnet-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arrownj** [comment]
Hi @MyronFanQiu , could you please help take a look at this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by MyronFanQiu** [comment]
@kylecweeks Hello. What's the meaning of `invalid`?

**Comment by kylecweeks** [comment]
The error from the CLI is that the provided DNS Servers are invalid when providing them as space separated. The command worked when the dns servers were provided as an array object.

**Comment by MyronFanQiu** [comment]
> The error from the CLI is that the provided DNS Servers are invalid when providing them as space separated. The command worked when the dns servers were provided as an array object.

Hi. I checked the code and I think it should work. Could you give me an example and the error message? It's better run the command with `--debug`.

**Comment by MyronFanQiu** [comment]
@kylecweeks Hi kindly ping?

**Comment by MyronFanQiu** [comment]
@kylecweeks Hi. Do you still meet this issue?

**Comment by MyronFanQiu** [comment]
close this issue since no response. Feel free to open a new issue if you encounter any issue.
