### ISSUE TITLE
'Create a rule for http to https redirect'  - Example error.

### ISSUE THREAD

**Issue by sondretj** [Azure/azure-cli#12072]
When testing out the example the following error occurs:

"validation error: Parameter 'UrlPathMatchConditionParameters.operator' can not be None"

azure-cli 2.0.81

The only thing i've changed is the resource-group, profile-name, endpoint-name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fef54fc4-b4a8-d366-40de-a0ae2586961d
* Version Independent ID: 1231852d-d3b4-9bcf-e9d4-ba12cffb7603
* Content: [az cdn endpoint rule](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint/rule?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/cdn/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cdn/_help.py)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S166

**Comment by MyronFanQiu** [comment]
@lsmith130 Hello. Can you take a look or help us find the correct person?

**Comment by lsmith130** [comment]
@hytao can you take a look at this?

**Comment by lsmith130** [comment]
@sondretj, could you please provide the full command you're executing? Feel free to redact the resource group, profile, and endpoint names from the command.

**Comment by sseveringhaus-newclassrooms** [comment]
I see an error [here](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint/rule?view=azure-cli-latest#examples). The `--match-values` has `HTTPS`, but you want to match on `HTTP`. Full example should look more like this:
```
az cdn endpoint rule add --resource-group xxx --profile-name xxx --name xxx \
    --order 1 --rule-name RedirectToHTTPS --match-variable RequestScheme \
    --operator Equal --match-values HTTP --action-name UrlRedirect \
    --redirect-protocol Https --redirect-type Found
```
I more or less reconstructed this from a `az cdn endpoint rule show` against an endpoint I have that I think is working correctly.

**Comment by Masahigo** [comment]
@sseveringhaus-newclassrooms Thanks, saved my day!

One question though: why the param value for `action-name` needs to be given fixed value?

The documentation gives the impression you could define it freely: 
https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint/rule?view=azure-cli-latest#required-parameters

**Comment by sseveringhaus-newclassrooms** [comment]
True, but I believe the action name is one of the options in the dropdown in the Azure Portal:
* Cache Expiration
* Cache Key Query String
* Modify Request Header
* Modify Response Header
* URL Redirect
* URL Rewrite

Exactly how those translate to action names, I'm not sure, but you could probably make educated guesses. This should be added to the docs, I suppose.

**Comment by Masahigo** [comment]
> True, but I believe the action name is one of the options in the dropdown in the Azure Portal:
> 
> * Cache Expiration
> * Cache Key Query String
> * Modify Request Header
> * Modify Response Header
> * URL Redirect
> * URL Rewrite
> 
> Exactly how those translate to action names, I'm not sure, but you could probably make educated guesses. This should be added to the docs, I suppose.

@sseveringhaus-newclassrooms  Thanks again!

@lsmith130  So I guess following detail should be added to documentation

--action-name
Name of the action.

_accepted values: CacheExpiration, CacheKeyQueryString, ModifyRequestHeader, ModifyResponseHeader, URLRedirect, URLRewrite_

**Comment by KarenHammons** [comment]
Issue appears resolved; closing.  Please re-comment if there's something we missed.

**Comment by sseveringhaus-newclassrooms** [comment]
@KarenHammons, it doesn't look like either of the issues I brought up have been addressed, at least not in the published documentation. Is there a commit somewhere that resolved this, and perhaps it just hasn't been published yet?
