### ISSUE TITLE
CLI support for URL Rewrite in Application Gateway

### ISSUE THREAD

**Issue by sobaner** [Azure/azure-cli#12088]
**Resource Provider**
What is the Azure resource provider your feature is part of?

NRP

**Description of Feature or Work Requested**
URL Rewrite refers to that action by the Application Gateway that replaces the original URL path with a new URL path while it routes the incoming request to the backend. Using URL Rewrite, user can use the App Gateway to rewrite request URL path before it is processed by the backend pools. User can define URL path rewriting logic that includes regular expressions, capture groups and rules can be applied based on the request URL, HTTP headers, and server. User has an option to rewrite the URL path and use that URL path either to go to the route to same backend pool or reroute to the new path based rule based on rewritten URL path inside same listener. User can also change the host header but the updated host header.

This parameter will be valid only for Application Gateway Standard_v2 and WAF_v2 SKUs. The validations in NRP are in place for the SKU verification.

**Minimum API Version Required**
2019-09-01

**Swagger Link**
PR: https://github.com/Azure/azure-rest-api-specs/pull/7905/files
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/applicationGateway.json

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

End of Feb, 2020. The API is already out and we are working on PS and Portal, once done, we'll be targeting Public Preview.

**Comment by MyronFanQiu** [comment]
@sobaner Hello. Do you mean this part?

**Comment by yonzhan** [comment]
add to S166.

**Comment by MyronFanQiu** [comment]
@sobaner Hello. Could you give the PR link?  Do you mean this fields？ https://github.com/Azure/azure-rest-api-specs/blob/6e1747c9ae9975e78d04074eaf409d5a9ae6f32a/specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/applicationGateway.json#L1921

**Comment by sobaner** [comment]
Here is the swagger for this feature: https://github.com/Azure/azure-rest-api-specs/pull/7905

**Comment by MyronFanQiu** [comment]
@sobaner Thanks. I check our current status and I have a question. `urlConfiguration` is part of `ApplicationGatewayRewriteRuleActionSet`. However, I don't see any command to set `requestHeaderConfigurations` and `responseHeaderConfigurations`. However, I saw two commands to list the request header and response header. Can customer set these two headers as well?
