### ISSUE TITLE
Weird output in powershell for commands tagged as preview.

### ISSUE THREAD

**Issue by shenmuxiaosen** [Azure/azure-cli#12084]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When I run CLI preview commands in Powershell script, the output messed up. It returned a message "Command group is in preview. It may be changed/removed in a future release" as expected but followed by a black chunk. It looks like the command hanged but actually it has return value just not able to see it in terminal. When I copied and pasted to notepad, I can see the expected return value. 

Also when I started virtual environment and removed ```is_preview=True``` for the same command, the problem resolved. So I believe the preview help message somehow changed the Powershell background color or font color to be invisible in terminal. 

**To Reproduce**
Run any preview CLI commands in Powershell. For example:
```$x = $(az appconfig list -g YourResourceGroup)```
```Write-Host $x```

This issue only happened when I run in a standalone Powershell script. It worked fine in Powershell ISE. 

**Expected behavior**
It should return properly instead of a black chunk. 

**Environment summary**
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe (PowerShell Core 6.2.4 64-bit)

azure-cli 2.0.80

**Additional context**
None

**Comment by arrownj** [comment]
Hi @jiasli , could you please help take a look at this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by jiasli** [comment]
Here is a similar screenshot of what is happening:

![](https://user-images.githubusercontent.com/4003950/66366994-ebc61580-e9c4-11e9-9764-8ef29a3257b9.png)

This is the same issue as #6080. 

Root cause: https://github.com/Azure/azure-cli/issues/6080#issuecomment-542106546 
Fix (TODO): https://github.com/Azure/azure-cli/issues/6080#issuecomment-561107810

**Comment by jiasli** [comment]
Without a proper fix from Colorama, we have added an option to disable color in https://github.com/Azure/azure-cli/pull/12604:

[Core] PREVIEW: Allow disabling color by setting `AZURE_CORE_NO_COLOR` environment variable to `True` or `[core] no_color=True` config (#12601)

**Comment by jiasli** [comment]
This issue has been fixed. Please see #6080 (comment) for the solution.

**Comment by jiasli** [comment]
Duplicate of #6080. Please see https://github.com/Azure/azure-cli/issues/6080#issuecomment-763294594 for the solution.

**Comment by jiasli** [comment]
This issue has been fixed. Please see https://github.com/Azure/azure-cli/issues/6080#issuecomment-763294594 for the solution.
