### ISSUE TITLE
dx: Add more context around the `--subscription` flag in the `az account set` command.

### ISSUE THREAD

**Issue by bnb** [Azure/azure-cli#12085]
**Is your feature request related to a problem? Please describe.**
Yes. When trying to figure out a subscription ID, I realized I was on the wrong subscription. Using `az account set`, I was trying to change my subscription to the one I was looking for and realized that I have no clue what the argument for the `--subscription` flag is.

**Describe the solution you'd like**
Have either an example of what the argument for the `--subscription` flag would be or have a textual description of what it is looking for.

**Describe alternatives you've considered**
- Status Quo: Do nothing. This is a non-ideal state since it's hard to figure out what is needed.
- Link to docs: I would rather not have to leave my terminal.

**Comment by bnb** [comment]
Here's an example of what it currently spits out. The only indicator is "SUBSCRIPTION"
![image](https://user-images.githubusercontent.com/502396/73973055-b67bf680-48d6-11ea-851e-67280cbea22d.png)

**Comment by arrownj** [comment]
Hi @jiasli , could you please help take a look at this ?

**Comment by jiasli** [comment]
Hi @bnb, the error message only reviews the root cause itself. You may always use `-h` in every command like `az account set -h` to view the details about each parameter, which will tell you:

```
>az account set -h

Command
    az account set : Set a subscription to be the current active subscription.

Arguments
    --subscription -s [Required] : Name or ID of subscription.
```

This is the convention of terminal applications, like `git pull -h`, `pip install -h`.

**Comment by yonzhan** [comment]
add to S166.

**Comment by bnb** [comment]
@jiasli definitely familiar with the `-h` flag, but it would nice if – like `git pull` in a non-repo and `pip install` without a requirement (see below) –  additional context that could lead the user to success 👍

Here's what `git pull` does in a non-git directory: 

```sh
$ git pull
fatal: not a git repository (or any of the parent directories): .git
```

This is specifically useful since it gives you the specific context you need - the current directory and none of its parents are a git repo, and it's missing a `.git` directory.

Here's what `pip install` does when not passed requirement:

```
$ pip install
ERROR: You must give at least one requirement to install (see "pip help install")
```

It specifically details in a human-readable way what you need to do and how to figure that out.

**Comment by yonzhan** [comment]
@bnb was your issue resolved?

**Comment by bnb** [comment]
It has been closed on the internal tracker with no further work being committed to it at present, from what I understand.

**Comment by jiasli** [comment]
I believe the errors message from `git pull` and `pip install` you provided are in a different category as the original argument missing issue. If required arguments are provided, we also give comprehensive error messages like 

```sh
$ az account set -s foo
The subscription of 'foo' doesn't exist in cloud 'AzureCloud'.
```

But when required arguments are unspecified, the error message is actually from python's [argparse](https://docs.python.org/3/library/argparse.html) module and we have little control over that:

```
>>> parser.parse_args(['--foo', 'FOO'])
usage: PROG [-h] [-f FOO] bar
PROG: error: the following arguments are required: bar
```
