### ISSUE TITLE
deploy specified folder in GitHub repository for webapp

### ISSUE THREAD

**Issue by eriolchan** [Azure/azure-cli#12094]
**Resource Provider**
WebApp

**Description of Feature or Work Requested**
When I use command "az webapp deployment source config" to deploy webapp from GitHub repository, is there any way to deploy the source code of specified folder instead of root of GitHub repository. 

E.g. If I want to deploy the ChatRoom sample from this [link](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/ChatRoom), since the repository is a collection of samples, how can I try to deploy ChatRoom sample from it?

In this case, the parameter of "--repo-url" is "https://github.com/aspnet/AzureSignalR-samples". I try to use parameter of "--app-working-dir", but it seems this parameter only can be used with "--cd-project-url" which is VSTS project.

**Comment by yungezz** [comment]
thanks for reporting the issue. we'll look at it.

**Comment by eriolchan** [comment]
I think I find a solution that configure the WebApp appsettings with "PROJECT" to identify the source code folder. Please help confirm if this is the official recommendation.

**Comment by hoff2-ACN** [comment]
@eriolchan Adding an Application Setting named PROJECT pointing to the `.csproj` file also seems to be working for us. Thanks

**Comment by panchagnula** [comment]
please re-open if this is still an open issue
