### ISSUE TITLE
Limitation using ASG arguments

### ISSUE THREAD

**Issue by para0056** [Azure/azure-cli#12099]
According to the documentation, when using either the `--source-asgs` or `--desination-asgs `arguments, there is a limitation in that only one application group name or ID can be used.

Has this limitation been addressed?
If so, can the documentation be updated?

Thanks,
NP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe4941c-7b46-b9fb-1c52-98e68f6354cc
* Version Independent ID: d1bc72fb-ccf9-9645-7b1d-98c91bc75a55
* Content: [az network nsg rule](https://docs.microsoft.com/en-us/cli/azure/network/nsg/rule?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
thanks for reporting the issue. hi @MyronFanQiu could you pls help to have a look? thanks.

**Comment by yonzhan** [comment]
add to S166.

**Comment by MyronFanQiu** [comment]
@para0056 Hello. I checked the code and found that this limitation happened in server side. @malopMSFT Could you help us confirm that?

**Comment by malopMSFT** [comment]
limitation still applies :)

**Comment by para0056** [comment]
Are there plans to remove this limitation and allow multiple ASGs to be tagged under the `--source-asgs` or `--destination-asgs` ?

**Comment by KarenHammons** [comment]
@malopMSFT ?

**Comment by malopMSFT** [comment]
We don't have near term roadmap to remove this limitation
