### ISSUE TITLE
Unable to download the Blob.

### ISSUE THREAD

**Issue by saaj562** [Azure/azure-cli#12093]
## Describe the bug

**Command Name**
`az storage blob download`

**Errors:**
```
[Errno 13] Permission denied: 'C:\\Users\\sajjada\\Downloads'
Traceback (most recent call last):
Temp\pip-install-0u_uiwkq\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 608, in execute
azure\cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 657, in _run_job
azure\cli\command_modules\storage\__init__.py, ln 257, in new_handler
azure\cli\core\commands\__init__.py, ln 636, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 493, in default_command_handler
multiapi\storage\v2018_11_09\blob\baseblobservice.py, ln 1968, in get_blob_to_path
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\sajjada\\Downloads'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob download -f {} -c {} -n {} --account-name {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.80

```

**Comment by yungezz** [comment]
hi @saaj562 which user you're when running the az command. From the error, seems it's permission issue to local dir.

**Comment by yonzhan** [comment]
add to S166.

**Comment by Juliehzl** [comment]
Hi @saaj562, can you check the permission for your local dir and if there is still a problem, please share the debug information with `--debug` in your command.

**Comment by yonzhan** [comment]
Hi @saaj562, any update?
