### ISSUE TITLE
Creating event grid topic subscription to Azure Function

### ISSUE THREAD

**Issue by daledev-uk** [Azure/azure-cli#12092]
I am trying to subscribe to one of my functions to topic events. Via the Azure portal, this can be done easily.

![](https://i.imgur.com/wjQG1XP.png)

The Advanced editor shows the config like so

```
{
	"name": "FuncTest",
	"properties": {
		"topic": "/subscriptions/{SubscriptionId}/resourceGroups/dmeukseventgrid/providers/Microsoft.EventGrid/topics/AppUser-Delete",
		"destination": {
			"endpointType": "AzureFunction",
			"properties": {
				"resourceId": "/subscriptions/{SubscriptionId}/resourceGroups/dmeuksmessaging/providers/Microsoft.Web/sites/dmeuksmessagingapp/functions/DeleteAppUser",
				"maxEventsPerBatch": 1,
				"preferredBatchSizeInKilobytes": 64
			}
		},
		"filter": {
			"advancedFilters": []
		},
		"labels": [],
		"eventDeliverySchema": "EventGridSchema"
	}
}
```

However, when it comes to doing this via the Azure CLI, it doesn't seem possible. I've been reading documentation and try all kinds of variants and nothing seems to work.

The documentation from here https://docs.microsoft.com/en-us/cli/azure/eventgrid/event-subscription?view=azure-cli-latest#az-eventgrid-event-subscription-create

States

```
--endpoint
Endpoint where EventGrid should deliver events matching this event subscription. For webhook endpoint type, this should be the corresponding webhook URL. For other endpoint types, this should be the Azure resource identifier of the endpoint. It is expected that the destination endpoint to be already created and available for use before executing any Event Grid command.
```
```
--endpoint-type
The type of the destination endpoint.

accepted values: eventhub, hybridconnection, servicebusqueue, storagequeue, webhook
default value: webhook
```

So there is no endpoint type for a `AzureFunction`, so I have to leave it as `webhook`, but doing so means I can't add the resource of `/subscriptions/{SubscriptionId}/resourceGroups/dmeuksmessaging/providers/Microsoft.Web/sites/dmeuksmessagingapp/functions/DeleteAppUser` as it's not a proper URI. Adding a URL to the function endpoint `https://dmeuksmessagingapp.azurewebsites.net/runtime/webhooks/EventGrid?functionName=DeleteAppUser` gives validation errors.

How can I achieve this, please? Is this missing functionality or am I doing something wrong?

**Comment by yungezz** [comment]
thanks for reporting the issue. we'll look at it.

**Comment by ahamad-MS** [comment]
Hello @daledev-uk  Thanks for reaching out.

AzureFunction as destination is supported in CLI through the event grid extension version 0.4.4 as this still in Preview. It will become part of mainsteam CLI soon.

To use the extension, please follow these steps:

1. Please make sure you remove any older eventgrid extension by running this command
@Azure:~$ az extension remove --n eventgrid

2. Make sure there is no installed eventgrid extension by running this command:
@Azure:~$ az extension list
[]

3. Install latest eventgrid extension
@Azure:~$ az extension add --n eventgrid
The installed extension 'eventgrid' is in preview.

4. make sure the new extension is installed and has version 0.4.4
@Azure:~$ az extension list
[
  {
    "extensionType": "whl",
    "name": "eventgrid",
    "version": "0.4.4"
  }
]

5. Get the help text for create operation of event-subscription
@Azure:~$ az eventgrid event-subscription create --h

--endpoint-type  hasd the azurefunction destination support

 --endpoint-type                                : The type of the destination endpoint.  Allowed
                                                     values: azurefunction, eventhub,
                                                     hybridconnection, servicebusqueue,
                                                     servicebustopic, storagequeue, webhook.
                                                     Default: webhook.

**Comment by ahamad-MS** [comment]
Please let us know if you are hitting any additional issue. Closing this issue as addressed.
