### ISSUE TITLE
az can't enable addons

### ISSUE THREAD

**Issue by comrade-sre** [Azure/azure-cli#12091]
## Describe the bug

**Command Name**
`az aks enable-addons`

**Errors:**
```
az aks enable-addons: error: the following arguments are required: --resource-group/-g, --name/-n
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons --addons {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.81

```

**Comment by yungezz** [comment]
thanks for reporting the issue. we'll look at it.

**Comment by jluk** [comment]
@comrade-sre the error shows you did not pass in all the required parameters. can you please retry by passing in a valid resource group and cluster name? Closing, but feel free to open a new issue if that again does not work.
