### ISSUE TITLE
Long running operations need to keep quiet.

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#121]
Long-running operations such as vm start use PoSH style progress reporting, which is super annoying in any sort of real scenario.  

Consider
`az vm list -g <resource-group> --query "[].name" --output tsv | xargs -I {} -P 10 az vm start -g <resource-group> --vm-name "{}"`

You'll get a bizarre mish-mash of dots and gratuitous text.  The desired behavior is to have the command print nothing and return an appropriate error code when the operation completes

**Comment by tjprescott** [comment]
@derekbekoe With your recent PR that squashed the last of the LRO outputs, can this be closed?
