### ISSUE TITLE
az appservice plan list shouldn't require a resource group

### ISSUE THREAD

**Issue by SteveLasker** [Azure/azure-cli#1210]
Similar to the az acs list issue, I shouldn't have to specify a resource group to find all the instances. If I knew the resource group, I wouldn't really need to list all the appervices

**Comment by mayurid** [comment]
@yugangw-msft: I believe we do have list and list-all here. Can you check?

**Comment by yugangw-msft** [comment]
@mayurid, that is correct.
Moving forward, let us always cross check command set has this implemented

**Comment by SteveLasker** [comment]
Why do we need yet another command? How many times do I need to type --help?  I tried az ACR list, that works as I'd expect. When I'm looking for all instances of something, forcing me to give a second parameter that most likely limits to one isn't very useful. 
Why should I have to find and call yet another command that needs to be documented, rather than calling the list command with an optional parameter. 
I get why we need rg for creation. I don't see why we require it for list. The list should report back the rg it's in.

**Comment by yugangw-msft** [comment]
@SteveLasker, no new command was created. Still `list`, rather the implementation has been changed to a wrapper function which decides which API should invoke `list` vs `list-all`. Make sense?
