### ISSUE TITLE
Cannot execute command "az group deployment create" using an existing App Service Plan

### ISSUE THREAD

**Issue by mamhh** [Azure/azure-cli#12103]
Dears,
I'm trying to execute the command `az group deployment create ...`  to deploy a bot to an existing app service plan using an ARM template. I get below error 
`The specified app service plan was not found.`

Please advise ..

**Comment by arrownj** [comment]
Hi @zhoxing-ms , could you please help take a look at this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by zhoxing-ms** [comment]
@mamhh Hi, I need some more specific information:

1. Could you please send me the specific parameters and ARM template by email? 
2. Please use `az appservice plan show` to query the app service plan which you are using, and send me the information obtained from the query.

My email is Zhou.Xing@microsoft.com, Thank you.

**Comment by zhoxing-ms** [comment]
Because I haven't received any reply for a long time, I will close this issue first. If you still have questions, please feel free to give feedback.
