### ISSUE TITLE
Powershell with Az CLI module on Linux - Unable to disable SSL Certificate check

### ISSUE THREAD

**Issue by marinnedea** [Azure/azure-cli#12122]
**Describe the bug**
If you need to pass with your az cli through a proxy/firewall that does SSL inspect, your SSL fingerprint will change and the system will see it as "self signed" instead of CA verified. 

Now, in normal Az Cli , installed directly into Linux, you have the option to disable the SSL check.
Same goes when you install AzCli as a module inside PowerShell on Windows.

However, none of the existing methods work for **AzCli installed as a module inside PowerShell on Linux.**

**To Reproduce**
- Install PS on any supported Linux distribution
- Install the AzCli module in the PS on Linux
**- Configure the Linux machine to connect through a proxy/firewall that does a SSL check, causing the certificate to be self-signed**
- run "az connect" command.

**Expected behavior**
   - will provide some way to either disable certificate check or use local repository

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Az Cli module on PowerShell running in Linux.

**Additional context**
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

I already created an issue report on PowerShell github page, but they closed it saying this needs to be moved to AzCli. If this is not true, please clarify with them directly. 

https://github.com/PowerShell/PowerShell/issues/11769

**Comment by arrownj** [comment]
Hi @jiasli , could you please help with this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by jiasli** [comment]
Python uses its own certificate store instead of the systems. We have polished the error with https://github.com/Azure/azure-cli/pull/11093

Please check this doc and see if you can get unblocked: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy

**Comment by marinnedea** [comment]
@jiasli that make sense when running AzCli directly in Linux or when running in through PowerShell on Windows. 

The issue is when running **AzCli through PowerShell on Linux**

**Comment by jiasli** [comment]
I am not aware of such "AzCli module" and we don't have the `az connect` command. For Azure CLI, it is `az login`. For PowerShell, it is `Connect-AzAccount`.

Could you elaborate:

1. How you installed "AzCli module"
2. How you disabled certificate check
3. What the error message is

**Comment by marinnedea** [comment]
@jiasli  - finally, you asked the right questions, which made me realize how wrong I was. Thank you!

I was confusing Az Cli with the "Az" module from PowerShell, which is actually the newest PowerShell module for Azure and has nothing to do with the Az Cli.
The confusion was due to the fact I had Az Cli installed on the same system, and it works even if it's called from the pwsh shell (which is normal, actually). However, this made me believe I have "Az Cli" running as a PowerShell module .. 

I figured out when you asked me what I'm doing and started putting everything togetehr from scratch, eg.. install a Linux machine, install PS on it.. install Az module.. and then it hit me.. 


Sorry for this all misunderstanding. 
Please close this issue.

**Comment by jiasli** [comment]
Glad to know you are able to solve it. 😃
