### ISSUE TITLE
Login with user managed identity fails

### ISSUE THREAD

**Issue by ramniwaschaurasiaTR** [Azure/azure-cli#12136]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 649, in get_token
    token_entry = self._retrieve_token_from_imds_with_retry(resource)
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 704, in _retrieve_token_from_imds_with_retry
    raise HTTPError(request=result.request, response=result.raw)
requests.exceptions.HTTPError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity -u {}`

## Environment Summary
```
Linux-3.10.0-1062.4.1.el7.x86_64-x86_64-with-redhat-7.7-Maipo
Python 3.6.8
Shell: bash

azure-cli 2.0.81

```

**Comment by arrownj** [comment]
@jiasli , could you please help take a look at this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by qianwens** [comment]
@ramniwaschaurasiaTR , it seems that you are trying to login within MSI credential `az login --identity -u {}`. MSI credential login is only supported in Azure VM and you need to assigned a managed identity to the VM https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-portal-windows-vm#assign-a-user-assigned-identity-during-the-creation-of-a-vm
