### ISSUE TITLE
az lock delete does not work on Microsoft.DocumentDB

### ISSUE THREAD

**Issue by ARCHIMEDES25** [Azure/azure-cli#12131]
Azure CLI "az lock delete" command does not seem to work on `providers/Microsoft.DocumentDB`

In my specific scenario, the locks are created for the collections within a cosmos db, when I try to delete the lock as below:

`az lock delete --ids /subscriptions/mySubcription/resourcegroups/myRG/providers/Microsoft.DocumentDB/databaseAccounts/myDB/apis/mongodb/databases/myCollection/providers/Microsoft.Authorization/locks/myLock --debug`

the error I get as below:

```

cli.azure.cli.core.util : Unexpected --parent for lock myLock, 
expected databaseAccounts/myDB

```

If I try to include the --parent attribute, I also receive the following error:
```
cli.azure.cli.core.util : --parent is ignored if --resource-group is not given.
--parent is ignored if --resource-group is not given.
```

I've tried a number of different variations of the command as suggested in the output, however none of them seem to work.

Any suggestions on what is the proper way to use az lock delete cli command on databases?

The version of the cli I'm using is `2.0.77`

**Comment by yonzhan** [comment]
add to S167.

**Comment by qianwens** [comment]
This issue is fixed in sprint 167.
