### ISSUE TITLE
[ACR] Fix instruction for RBAC 

### ISSUE THREAD

**Issue by SajayAntony** [Azure/azure-cli#1213]
The instructions displayed for setting permissions is incorrect. 
```
ad sp create-for-rbac --scopes resourceid --role Owner --secret password
```

it should be`--password`

**Comment by mayurid** [comment]
@SajayAntony : Feel free to use the Milestones as well to mark the bugs that you are tracking for upcoming release

**Comment by SajayAntony** [comment]
@mayurid I dont have permissions to label or add milestones. We need to figure out partners can contribute to this and track issues under their labels appropriately.
