### ISSUE TITLE
az webapp up -n MyApp => unable to publish to Linux App Service

### ISSUE THREAD

**Issue by contento** [Azure/azure-cli#12135]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version:
azure-cli                         2.0.81
command-modules-nspkg              2.0.3
core                              2.0.81
nspkg                              3.0.4
telemetry                          1.0.4

**Describe the bug**
az webapp fails to deploy .NET Core API as  Linux App Service

**To Reproduce**
az webapp up -n MyApp

Renders:
The webapp MyApp is a Linux app. The code detected at 'C:\Projects\MyApp' will default to '<module 'os' from 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\lib\\os.py'>'. Please create a new app to continue this operation.

**Expected behavior**
Publish it or If something is missing, the error should mention how to either force or create a setting that informs explicity [az webapp] that this an application that should be deployed as a Linux App Service

**Environment summary**
Tested on both PowerShell Core 6.2.4 and Ubuntu 18.04

**Additional context**
I am able to publish from Visual Studio and VS-Code with no issues

**Comment by arrownj** [comment]
@contento , thanks for reporting, we are looking at it.

**Comment by panchagnula** [comment]
Currently .NETCore app defaults to windows using az webapp up - this is by design

**Comment by atlemagnussen** [comment]
Really, something is default by design?
If something is default, it sounds like you can override it. So can you at least tell us **IF** it is at all possible to use `az webapp up` for app services for Linux?
And if yes; how?

**Comment by panchagnula** [comment]
for az webapp up for Linux for Node and Python Linux is the default, How to use it? run the command from the context of directory where the code to deploy is located and az webapp up will try to auto detect language & based on it set the defaults. If you don't want the defaults or need to override it use az webapp create

**Comment by atlemagnussen** [comment]
@panchagnula sorry, I meant to specify ASP.NET Core app.
Ok. So you can't use "az webapp up" to deploy Asp.net Core on Azure App Service for Linux, is what I wanted to clarify. Thanks

**Comment by kyoun** [comment]
@atlemagnussen 

try `az webapp up --os-type linux`

**Comment by vivaladan** [comment]
I realise this is closed, and you can always supply the --os-type Linux arg to work around it, but it doesn't work like I'd expect it to. First time az webapp up is performed (given optional parameters) it'll write it's state to the .azure/config file. However it doesn't write the os-type of the new or existing app service. If it were to, then it could deploy to Linux just fine without having the arg always present.
