### ISSUE TITLE
az keyvault rbac change

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#12132]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
RBAC feature in azure keyvault is depending on swagger new property `enable-rbac-authoriazation`, the swagger is not ready yet. create the issue to track the effort to work to call into SDK for rbac.

same story for BYOK create key importing.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by yungezz** [comment]
put in backlog for now since no determined timeline yet.

**Comment by bim-msft** [comment]
This is done, closed.
