### ISSUE TITLE
az storage blob copy start-batch: error: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by rosanch** [Azure/azure-cli#12130]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I'm trying to copy files from different clouds my command looks as follows:
 az storage blob copy start-batch --account-key <dest-key> --account-name <dest-name> --destination-container <dest-container-name> --source-sas <SAS-Token> --source-uri <container-source-uri>
I'm currently connected to destination cloud

**To Reproduce**
run in a sovereign cloud and try to copy files from another cloud.

**Expected behavior**
Should copy all files inside the source container to dest container

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by Juliehzl** [comment]
Hi @rosanch, because your scenario is a little complicated and we need some time to reproduce for different clouds, can you show me your debug information first with `--debug` in your command?
Secondly, can you try `az storage copy` command with latest azure cli?

**Comment by yonzhan** [comment]
Hi @rosanch, any update?

**Comment by rosanch** [comment]
I used az storage copy instead that is working
