### ISSUE TITLE
Incorrect help doc of az storage container list

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1214]
The content of the help doc is extracted from azure python sdk, which doesn't apply to the context of cli. For example, the concept _generator_ doesn't apply here.
```
Command
    az storage container list: Returns a generator to list the containers under the specified
    account.
        The generator will lazily follow the continuation tokens returned by the service and stop
        when all containers have been returned or num_results is reached.  If num_results is
        specified and the account has more than that number of  containers, the generator will have
        a populated next_marker field once it  finishes. This marker can be used to create a new
        generator if more  results are desired.
```

**Comment by mayurid** [comment]
@jasonrshaver: can we look at it as part of doc bugs.
@tjprescott: Should we open sdk bug?

**Comment by troydai** [comment]
The doc is extracted from [here](https://github.com/Azure/azure-storage-python/blob/master/azure/storage/blob/baseblobservice.py#L473). The content itself is correct in the context of the python API but it doesn't fit to be exposed as CLI help doc directly.

**Comment by tjprescott** [comment]
@mayurid I think the SDK would agree with Troy that it is adequate within the context of the SDK. That it is not helpful for the CLI isn't really their problem, and unless we create standard for help documentation across services, I doubt they would do anything. I would suggest we simply override it in the `_help.py` file.

**Comment by troydai** [comment]
I believe there will be more cases like this across CLI as long as we direct extract documentation from SDK.

**Comment by tjprescott** [comment]
Yes, this will. Originally we did this to have placeholder text when we were supposed to get dedicated help doc writers. Now that this isn't the case, what I do when I "touch" a module is review the help text and update the _help.py file as appropriate. I recommend we simply do this as a team.

**Comment by tjprescott** [comment]
This has been fixed in another PR.
