### ISSUE TITLE
az webapp create-remote-connection SSL certificate error

### ISSUE THREAD

**Issue by dpippert** [Azure/azure-cli#12141]
![cert_error](https://user-images.githubusercontent.com/7669192/74278330-0bf54080-4ce7-11ea-92b2-2974a5d5e596.png)

## Describe the bug

**Command Name**
`az webapp create-remote-connection`

**Errors:**
```
HTTPSConnectionPool(host='pspmeb10.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/settings (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Traceback (most recent call last):
urllib3\urllib3\contrib\pyopenssl.py, ln 456, in wrap_socket
pip-install-1o1fsnhi\pyOpenSSL\OpenSSL\SSL.py, ln 1934, in do_handshake
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create-remote-connection --subscription {} -g {} -n {} -p {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.81

Extensions:
webapp 0.2.16

```

**Comment by arrownj** [comment]
@dpippert , thanks for reporting, we are looking at this.

**Comment by panchagnula** [comment]
@btardif can you check with Patrick on this since he is owner of this. Thanks.

**Comment by btardif** [comment]
FYI @sanchitmehta

**Comment by navba-MSFT** [comment]
@dpippert Apologies for the late reply. Is there a proxy in your environment ? Could you please try to run the command on a another machine which is on a different network and check if that works fine ? If this is not feasible you can append your corporate proxy certificate(s) to the end of the certifi library's cacert.pem file. Sharing the location of this on Windows: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\certifi\cacert.pem

Please let me know if you face any issue while testing this. Awaiting your reply.
