### ISSUE TITLE
[Storage] Support PITR (point in time restore) in SRP

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-cli#12147]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Storage

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.

`Point in Time restore helps to undo (block blob) changes until the time that is deemed to be good (like the time before the last deployment). Point in Time Restore leverages the data protections features like soft delete, lifecycle management to restore both the data and metadata associated with the blob at that point in time. This is a fully managed feature that performs the necessary undo operation on-behalf-of the user to restore the entire storage account or parts of it. 
`
[Feature Spec link](https://microsoft.sharepoint.com/:w:/t/AzureStorage/EYewz5lNqkRFpcdLuvX7AH0Bu8YabJTNDACZ1xkbocu_hw?e=meWe9G)

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2019-06-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

https://github.com/Azure/azure-rest-api-specs/pull/8159/files

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

End of Feb.

**Comment by Juliehzl** [comment]
Requested by service team.

**Comment by yonzhan** [comment]
add to S165.
