### ISSUE TITLE
az resource create --properties not accepting JSON

### ISSUE THREAD

**Issue by happyiphone** [Azure/azure-cli#12143]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Run the example on [`az resource create`](https://docs.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#az-resource-create)  and it will fail.

```
az resource create -g myRG -n myApiApp --resource-type Microsoft.web/sites --is-full-object --properties '{
            "kind": "api",
            "location": "West US",
            "properties": {
                "serverFarmId": "/subscriptions/{SubID}/resourcegroups/{ResourceGroup}/providers/Microsoft.Web/serverfarms/{ServicePlan}"
            }
        }'
```

```
Error parsing JSON.
{
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```
**To Reproduce**
Just the above line of code will fail, it won't even check the existance of the resource group or the other parameters.

**Expected behavior**
Parse the JSON passed so it can read the default values for creating new resources.

**Environment summary**
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe
azure-cli 2.0.81
Extensions:
interactive 0.4.3

**Additional context**
Nothing else.

**Comment by arrownj** [comment]
Hi @zhoxing-ms , could you please help take a look at this ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by zhoxing-ms** [comment]
This is a duplicate question which has been answered in another issue #11981
