### ISSUE TITLE
Azure CLI support for Per-Site and Per URI WAF Policies

### ISSUE THREAD

**Issue by winthrop28** [Azure/azure-cli#12144]
**Resource Provider**
Network

**Description of Feature or Work Requested**
Global WAF Policies already exist. This feature is now being extended to apply to Application Gateway Listeners for per-site coverage, and to URL Path Maps for per-URI coverage. 

**Minimum API Version Required**
2019-09-01

**Swagger Link**
App GW:https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/applicationGateway.json
WAF Policies: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/webapplicationfirewall.json

**Target Date**
March 1st

**Comment by winthrop28** [comment]
We also need to Add GeoMatch custom rule support and the Bot Mitigation ruleset for Application Gateway WAF. Let me know if I should create another request or if we can just use this one.

**Comment by arrownj** [comment]
@MyronFanQiu , could you please help take a look at this?

**Comment by yonzhan** [comment]
@winthrop28 it is better that you can create a separate one.

**Comment by yonzhan** [comment]
add to S166.

**Comment by jsntcy** [comment]
@winthrop28, as we are busy on other urgent features, we'll plan this issue to next sprint and the release date is 03/31/2020.

**Comment by jsntcy** [comment]
We already supported per-site and per-uri coverage for WAF policies, so close this issue. Here are related Azure CLI commands:
- per-site: https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/http-listener?view=azure-cli-latest#az-network-application-gateway-http-listener-create
- per-uri: https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/url-path-map/rule?view=azure-cli-latest
