### ISSUE TITLE
--policy parameter in the create command is a required one

### ISSUE THREAD

**Issue by stan-sz** [Azure/azure-cli#12153]
When running the command without the --policy parameter, we get:

`validation error: Parameter 'ManagementPolicy.policy' can not be None.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f84b325-33af-86ab-749e-faec2e01a1f3
* Version Independent ID: 87036460-df59-9239-680d-29c68a0490bb
* Content: [az storage account management-policy](https://docs.microsoft.com/en-us/cli/azure/storage/account/management-policy?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arrownj** [comment]
Hi @Juliehzl , could you please help take a look at it ?

**Comment by yonzhan** [comment]
add to S166.
