### ISSUE TITLE
--attach-acr is inconsistent

### ISSUE THREAD

**Issue by jacekmackiewicz** [Azure/azure-cli#12158]
Depending on using the --attach-acr parameter with az aks create or az aks update we're supposed to use registry ID or only the name. For both the parameter description points to using the registry ID but the example of az aks update says to use the name of acr.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arrownj** [comment]
@jacekmackiewicz , thanks for reporting, we are looking at it.

**Comment by sauryadas** [comment]
in both the instance the description is : Grant the 'acrpull' role assignment to the ACR
                                                specified by name or resource ID.

Can you point to the specific example? Also what version of CLI are you on?

**Comment by jacekmackiewicz** [comment]
Close issue.
