### ISSUE TITLE
webapp: Please make a command that accepts SubnetId for Vnet itegration

### ISSUE THREAD

**Issue by stefan-stojkovski** [Azure/azure-cli#12150]
Hi,
Currently the az webapp vnet-integration add only supports specifying Vnet Name and Subnet Name.
It would be nice if you can add support for SubnetId as this is the case for most of the other Azure Services.
Also it is not clear which Resource Group to specify, either that where the WebApp is located, or the RG where the Vnet is located. This can be described more clearly
Kind regards,
Stefan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cf5a035-926f-1cef-8335-963b497cbed8
* Version Independent ID: 296a49f5-bc7a-d56a-6fe2-914d276b2a9e
* Content: [az webapp vnet-integration](https://docs.microsoft.com/en-us/cli/azure/webapp/vnet-integration?view=azure-cli-latest#az-webapp-vnet-integration-add)
* Content Source: [latest/docs-ref-autogen/webapp/vnet-integration.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/vnet-integration.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arrownj** [comment]
@stefan-stojkovski , thanks for reporting, we are looking at it.

**Comment by panchagnula** [comment]
Not sure if we will support  this - but keeping it in backlog so we can reach out to the feature crew.

**Comment by ThejaChoudary** [comment]
After analysing if we can support this ,will consider this for feature request.
FYI @panchagnula

**Comment by panchagnula** [comment]
@madsd what do you think?

**Comment by madsd** [comment]
@panchagnula you can assign it to me.
