### ISSUE TITLE
az webapp list-runtimes

### ISSUE THREAD

**Issue by larryclaman** [Azure/azure-cli#12159]
## Describe the bug

**Command Name**
`az webapp list-runtimes`

**Errors:**
```
'bool' object has no attribute 'provider'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/appservice/custom.py, ln 704, in list_runtimes
    return [s['displayName'] for s in runtime_helper.stacks]
cli/command_modules/appservice/custom.py, ln 2159, in stacks
    self._load_stacks()
cli/command_modules/appservice/custom.py, ln 2180, in _load_stacks
    raw_stacks = self._client.provider.get_available_stacks(os_type_selected=os_type, raw=True)
AttributeError: 'bool' object has no attribute 'provider'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp list-runtimes`

## Environment Summary
```
Linux-4.15.0-1067-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.81

```
## Additional Context
I'm trying to run the example from https://docs.microsoft.com/en-us/azure/app-service/web-sites-php-configure

**Comment by arrownj** [comment]
@larryclaman , thanks for reporting, we are looking at it.

**Comment by arrownj** [comment]
Hi @panchagnula , could you please help with this ? There are several similar issues recently(#12159, #12160 , #12164 )

**Comment by panchagnula** [comment]
@arrownj i will take a look - this seems like a regression from the hybrid profile support change.

**Comment by AgnosticCoder** [comment]
Hello All, I am facing same error as #12164 , #12160  while creating a .NetCore web app. Here is the link https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-dotnetcore#create-a-web-app. Any workaround ?

I am trying to create a webapp 
$ az webapp create -n tail-spinxxxx -g tailspin-space-gamexxx -p tail-spinxxx --runtime "DOTNETCORE|3.1"
Runtime 'DOTNETCORE|3.1' is not supported. Please invoke 'list-runtimes' to cross check

**Comment by panchagnula** [comment]
@AgnosticCoder the fix will be available with the next release please use the Edge builds in the mean time. https://github.com/Azure/azure-cli#edge-builds

**Comment by Poil** [comment]
Hi,

Not better on edge this morning

```
The command failed with an unexpected error. Here is the traceback:

cannot import name 'AzureStorageType' from 'azure.mgmt.web.models' (/usr/local/lib/python3.7/dist-packages/azure/mgmt/web/models/__init__.py)
Traceback (most recent call last):
  File "/home/xxxx/.local/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/xxxx/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 528, in execute
    self.commands_loader.load_arguments(command)
  File "/home/xxxx/.local/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/home/xxxx/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/home/xxxx/.local/lib/python3.7/site-packages/knack/commands.py", line 97, in load_arguments
    cmd_args = self.arguments_loader()
  File "/home/xxxx/.local/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 496, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/home/xxxx/.local/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 536, in get_op_handler
    op = import_module(mod_to_import)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xxxx/.local/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 52, in <module>
    from ._params import AUTH_TYPES, MULTI_CONTAINER_TYPES, LINUX_RUNTIMES, WINDOWS_RUNTIMES
  File "/home/xxxx/.local/lib/python3.7/site-packages/azure/cli/command_modules/appservice/_params.py", line 13, in <module>
    from azure.mgmt.web.models import DatabaseType, ConnectionStringType, BuiltInAuthenticationProvider, AzureStorageType
ImportError: cannot import name 'AzureStorageType' from 'azure.mgmt.web.models' (/usr/local/lib/python3.7/dist-packages/azure/mgmt/web/models/__init__.py)
```

**Comment by itsforbrijesh** [comment]
I still sees this issue with CLI 2.1.0


OS: Ubuntu
azure-cli                          2.1.0

command-modules-nspkg              2.0.3
core                               2.1.0
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/..../.azure/cliextensions'

Python (Linux) 3.6.5 (default, Feb 14 2020, 05:22:53)
[GCC 7.4.0]

Legal docs and information: aka.ms/AzureCliLegal



Your CLI is up-to-date.

Here is command:
$az webapp create -n $AppName -g $ResourceGroup -p $ServicePlanName   --tags Environment="$Environment" CostCenter="$CostCenter" Contact="$contact" "IT Owner"="$ITOwner" --runtime "java|11|Tomcat|8.5"

Error: TypeError: update_site_config() takes 2 positional arguments but 3 were given

**Comment by chriswue** [comment]
This is still broken on Azure CLI 2.2 which was released yesterday:

    chrisw@home$ az webapp create -n XXX -p YYY --runtime 'DOTNETCORE|2.2'
    Runtime 'DOTNETCORE|2.2' is not supported. Please invoke 'list-runtimes' to cross check
    chrisw@home$ az --version

```
azure-cli                          2.2.0

command-modules-nspkg              2.0.3
core                               2.2.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
application-insights               0.1.4
azure-cli-iot-ext                  0.8.9
azure-devops                      0.17.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/chrisw/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Mar  6 2020, 14:41:24)
[GCC 7.4.0]

Legal docs and information: aka.ms/AzureCliLegal



Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/clihats
```

**Comment by panchagnula** [comment]
@chriswue note the difference in the stack trace error message
looks like in this case you are trying ti create a windows app with the following runtime version & as per az webapp list-runtimes this is not a supported runtime version. If you are trying to create a linux app make sure you use an ASP that supports Linux. Also if you still believe you have an issue please file a new issue. since the original issue here is fixed & this marked closed.

**Comment by chriswue** [comment]
@panchagnula Indeed - I'm sure I checked it many time, still missed it. Thanks.

**Comment by VladimirSuhovRepository** [comment]
same issue for me

**Comment by Macro21** [comment]
Same here: 

![image](https://user-images.githubusercontent.com/24574303/132364171-5ccdf9ba-ac58-4541-bfb0-9602cc3186f5.png)

**Comment by Macro21** [comment]
> @Macro21 - you forgot the `V` in front of the `4.8`

I try with 'V' in front, but same error. The solution is: --runtime '"aspnet|V4.8"'.

The error was put the runtime value only with double quotes. The solution is **'**"value"**'**
