### ISSUE TITLE
az aks create unrecognized arguments: --vm-set-type VirtualMachineScaleSets

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-cli#12166]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Tested in linux VM and CloudShell unrecognized arguments: --vm-set-type VirtualMachineScaleSets

az: error: unrecognized arguments: --vm-set-type VirtualMachineScaleSets --load-balancer-sku standard

![image](https://user-images.githubusercontent.com/4621560/74391877-5963d180-4dfd-11ea-8512-6dce365d4bea.png)

**To Reproduce**
Steps to reproduce the behavior.
Go to Linux VM or Cloud Shell use command to create a AKS cluster with cluster autoscaler enabled 

Sample command 

az aks create \
--resource-group msaksworkshop-rg \
--name $AKS_CLUSTER_NAME \
--vm-set-type VirtualMachineScaleSets \
--load-balancer-sku standard \
--location eastus \
--kubernetes-version $VERSION \
--network-plugin azure \
--vnet-subnet-id $SUBNET_ID \
--service-cidr 10.2.0.0/24 \
--dns-service-ip 10.2.0.10 \
--docker-bridge-address 172.17.0.1/16 \
--generate-ssh-keys

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by arrownj** [comment]
@cloudmelon , thanks for reporting, we are looking at it.

**Comment by waseemjda** [comment]
Upgrade the version of CLI , i faced the same error but after upgrading it works fine

**Comment by cloudmelon** [comment]
Hello the error is on Cloudshell. I have latest version on my laptop, it works fine. Thanks
