### ISSUE TITLE
Cannot create custom alerts trought az 

### ISSUE THREAD

**Issue by rmtier** [Azure/azure-cli#12163]
Same issue was closed #9640, but it looks like its not working. I am using azure-cli 2.0.81.
Non of whis works:

az monitor metrics alert create -n xxx -g xxxx --scopes "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Insights/components/Insights" --condition "avg 'Azure.ApplicationInsights.xxx/Failed' > 10" --description "xxxx"

az monitor metrics alert create -n xxx -g xxxx --scopes "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Insights/components/Insights" --condition "avg 'xxx/Failed' > 10" --description "xxxx"

I get: The metric names were not found xxxx [Code: "BadRequest"] ...., but with **az rest** i can create alert on custom metric.

**Comment by arrownj** [comment]
Hi @MyronFanQiu , could you please help take a look at it ?

**Comment by yonzhan** [comment]
add to S166.

**Comment by iyerusad** [comment]
@yonzhan I don't believe this is feature request - looks like a regression.

This code ran successfully over 100 releases (1 year+):
```
az monitor metrics alert create \
  -g "$RSGROUP" \
  -n "Alert on Exceptions" \
  --description "All exceptions" \
  --scopes $AppInsightsID --action "$alertgroupname" \
  --condition "count exceptions/count >= 1"
```
Just recently stopped working with same error:

> Unable to find the resource /subscriptions/{mysubscriptionID}/resourceGroups/my-project/providers/microsoft.insights/components/my-project-AppI, please confirm that it exists.. [Code: "BadRequest"]

`resourceGroups/my-project/my-project-AppI` exists

---

Tested against hosted Azure DevOps agents and fresh local install of `az-cli`:

> azure-cli                          2.5.1
> command-modules-nspkg              2.0.3
> core                               2.5.1
> nspkg                              3.0.4
> telemetry                          1.0.4

**Comment by jsntcy** [comment]
@rmtier, could you provide your real `condition` which is critical for our troubleshooting?
 `condition "avg 'Azure.ApplicationInsights.xxx/Failed' > 10"` (provide `xxx` as I guess `xxx` include some special characters that CLI doesn't support.)

**Comment by jsntcy** [comment]
@iyerusad,
I cannot reproduce the issue you mentioned as I can create alert successfully using the following command,
`az monitor metrics alert create -g my-rg -n "Alert on Exceptions" --description "All exceptions" --scopes /subscriptions/my-sub/resourceGroups/my-rg/providers/microsoft.insights/components/my-ai --action my-action-group --condition "count exceptions/count >= 1"`
- Could you provide more details about your command? for example, how it is used (in command window or script)? 
- Could you add `--debug` after your command to capture more debug information?

BTW, the issue rmtier encountered is the different issue from yours. (It is probably a feature request as CLI need support some new special characters in metric/namespace name)

**Comment by jsntcy** [comment]
@rmtier, could you help provide the information I mentioned above for us to troubleshoot?

**Comment by iyerusad** [comment]
> @iyerusad,
> I cannot reproduce the issue you mentioned [...snipped]

Odd - the issue has seemingly self resolved. I am 100% positive it was failing from multiple environments - tested in Azure DevOps Pipeline and on a fresh local instance on my machine. We run this command as part of a Azure DevOps Pipeline deploying a WebApp on ubuntu 18.04 agent/bash in azure cli 1.* task.

Since unable to repo, and lacking `--debug` output of failure, will have to chalk this up to possible upstream API issue.  Safe to shelve my datapoint as potentially benign anomaly.

**Comment by jsntcy** [comment]
@rmtier, could you help provide the information I mentioned above for us to troubleshoot?

**Comment by yonzhan** [comment]
@rmtier, any feedback?

**Comment by jsntcy** [comment]
@rmtier, could you help provide the information I mentioned above for us to troubleshoot?

**Comment by jsntcy** [comment]
I'll close this issue now as there is no response from customer.
@rmtier, if you provided the context, you can reopen this issue.
