### ISSUE TITLE
"az container attach" doesn't writing in the stderr

### ISSUE THREAD

**Issue by alexis-landrieu-avanade** [Azure/azure-cli#12178]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Exit code is not well returned through the stderr when ```az container --attach``` is used.

**To Reproduce**
Steps to reproduce the behavior.

1. Create simple docker image:
```dockerfile
FROM alpine
WORKDIR /ws
COPY . .
CMD exit 1
```

2. Push the image to an ACR or any other image registry.
3. Start your container with Azure CLI.
```sh
az container start -n $container_name -g  $resource_groupe --subscription $sub
az container attach -n $container_name -g  $resource_groupe --subscription $sub
rc=$?
echo $rc # print 0
```
Exit code must be 1 instead of 0.

**Expected behavior**
If you make the same scenario through docker it works as expected.

```sh
docker container start $container_name ;
docker container attach $container_name ;
rc=$?
echo $rc # print 1
```

**Environment summary**
I'm using Azure Cloud Shell.
```sh
~/workspace$ az -v
azure-cli                         2.0.81

command-modules-nspkg              2.0.3
core                              2.0.81
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/alexis_landrieu/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Jan 31 2020, 12:46:26)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal
```

**Additional context**

**Comment by arrownj** [comment]
@alexis-landrieu-avanade , thanks for reporting, we are looking at it.

**Comment by arrownj** [comment]
Hi @tjprescott , could you please help take a look at this ?

**Comment by tjprescott** [comment]
@arrownj I am no longer on the CLI team and am not on a service team, so I do not have any context on this issue.

**Comment by navba-MSFT** [comment]
@alexis-landrieu-avanade Apologies for the late reply. This issue is open for quite sometime. Could you please let us know if you are still looking for assistance on this issue ? Awaiting your reply.

**Comment by alexis-landrieu-avanade** [comment]
@navba-MSFT Hum, not really it was just an improvement request for those that are using the `az container` command line. We can do without.
