### ISSUE TITLE
ImageBuilder commands improve and new features

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#12184]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.VirtualMachineImages

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
1. Rename `image template` to `image builder`.
2. Support specifying image template in `image builder create` , e.g. `--image-template-path`.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2019-05-01-preview

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/imagebuilder/resource-manager/Microsoft.VirtualMachineImages/preview

**Comment by arrownj** [comment]
Hi @qwordy , please help take this issue.

**Comment by qwordy** [comment]
Usage of image template:
"NumInvocations": 46,
"UniqueSubscriptions": 17,

Query:
HttpIncomingRequests
| where TIMESTAMP > ago(30d)
| where userAgent contains 'AzureCLI/2.'
| where commandName startswith 'image template'
| summarize NumInvocations=dcount(clientRequestId), UniqueSubscriptions=dcount(subscriptionId)

No risk to rename "template" to "builder"

**Comment by yungezz** [comment]
thanks @qwordy , it's great that impact of renaming `template` to `builder`. Let's use this issue for item 1 and 2. for further asks, let's use new issue.

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/pull/11865
