### ISSUE TITLE
argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by tfedalto** [Azure/azure-cli#12189]
## Describe the bug

**Command Name**
`az network dns zone import`

**Errors:**
```
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
Temp\pip-install-1o1fsnhi\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 608, in execute
azure\cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 659, in _run_job
Local\Temp\pip-install-1o1fsnhi\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 636, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 493, in default_command_handler
azure\cli\command_modules\network\custom.py, ln 1651, in import_zone
cli\command_modules\network\zone_file\parse_zone_file.py, ln 413, in parse_zone_file
cli\command_modules\network\zone_file\parse_zone_file.py, ln 305, in _add_record_names
cli\command_modules\network\zone_file\parse_zone_file.py, ln 205, in _serialize
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network dns zone import -g {} -n {} -f {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.81

```

**Comment by arrownj** [comment]
Hi @MyronFanQiu , could you please help take a look at it ?

**Comment by MyronFanQiu** [comment]
@tfedalto Hello. Did you fetch the correct file? Looks like it cannot find the file.

**Comment by yonzhan** [comment]
add to S167.

**Comment by MyronFanQiu** [comment]
@tfedalto Hi. Did you solve the issue?

**Comment by tfedalto** [comment]
Hi, not yet. I did the zone import using a powershell script

**Comment by MyronFanQiu** [comment]
@tfedalto Could you share an example about the file path and an tiny example about the content which cause this issue? We can have a further investigation.

**Comment by MyronFanQiu** [comment]
close this issue first. If we still meet this issue later we can reopen it.
