### ISSUE TITLE
[Role] Help text for the definition create/update commands isn't clear

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1218]
Both the `az role definition create` and `az role definition update` commands include a `--role-definition` flag, whose help context refers to a `show-create-template` command (?), but it's unclear where that command is. I don't see it listed underneath the `role` or `role definition` command groups, and it doesn't appear to be a flag either. Am I missing something, or does the help text need to be updated here?

**Comment by yugangw-msft** [comment]
@lostintangent , the help needs update, it fell through the crack when we shuffled the content around

**Comment by lostintangent** [comment]
@yugangw-msft Makes sense. Your PR looks great, thanks!
