### ISSUE TITLE
az container exec cursor keys don't work

### ISSUE THREAD

**Issue by stmax82** [Azure/azure-cli#12180]
## Describe the bug

When I log into a container's shell (bash or similar) cursor keys don't work. Makes it impossible to use text editors like vi, nano,...

**Command Name**
`az container exec --exec-command bash`

**Errors:**

This is what I get when I press up / down / left / right cursor keys...:

![image](https://user-images.githubusercontent.com/6381927/74430024-54823a80-4e5c-11ea-9e2a-674777a5e512.png)

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container exec -g {} -n {} --exec-command bash`
- use cursor keys

## Expected Behavior

Cursor keys do what they're supposed to do.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.81
azure-cli-iot-ext 0.8.7

Extensions:
azure-cli-iot-ext 0.8.7

```

**Comment by arrownj** [comment]
@stmax82 , thanks for reporting, we are looking at it.

**Comment by arrownj** [comment]
Hi @tjprescott , could you please help take a look at this ?

**Comment by flexthink** [comment]
+1

**Comment by navba-MSFT** [comment]
@stmax82 Apologies for the late reply. Could you please let us know if you are still facing this issue ? This issue is open for quite sometime. Please let us know if you still need any assistance on this. Awaiting your reply.

**Comment by stmax82** [comment]
@navba-MSFT no, we stopped using Azure Container Instances due to all kinds of weird problems.

**Comment by navba-MSFT** [comment]
@stmax82 Sorry to hear about that. Please feel free to reopen this thread in future if you have plans of using the ACI and face any issues with that. We would be happy to assist you further.
