### ISSUE TITLE
Add application insight endpoint to azure cli

### ISSUE THREAD

**Issue by kicha0** [Azure/azure-cli#12185]
**Is your feature request related to a problem? Please describe.**
Currently azure cli does not provide some of the application insight endpoint for different cloud regions. For example, ingestion endpoint for application insight in us government region is
https://dc.applicationinsights.us/v2/track

**Describe the solution you'd like**
Azure cli team maintain application insight endpoint mapping and provide the information in az cloud show.
The current endpoint list for application insight can be found here:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-endpoints

**Describe alternatives you've considered**
We currently maintain a mapping from cloud region to application insight ingestion endpoint in our application. 

**Additional context**
As part of effort to automate azureml service deployment in new region, we would like to be able to query the correct application insight endpoint given cloud region so that correct endpoint can be consumed at build time.

**Comment by arrownj** [comment]
@kicha0 , thanks for reporting, we are looking at it.

**Comment by yungezz** [comment]
the feature is released in Azure CLI 2.2.0. close the issue
