### ISSUE TITLE
Request to support Encryption Scopes for Microsoft.Storage.

### ISSUE THREAD

**Issue by anthonykjose** [Azure/azure-cli#12188]
**Resource Provider**
Microsoft.Storage

**Description of Feature or Work Requested**
Encryption scopes provide the ability to create isolated encryption enclaves within a storage account. Currently, Storage provides server-side encryption through AES-256 symmetric encryption in 2 flavors – using platform-managed keys(i.e. Storage creates and manages the life-cycle of these keys internally) & BYOK (Bring Your Own Key) using Azure Key Vaults. However, customers using a single storage account for multi-tenancy scenarios were limited to using a single account-scoped encryption key for all the data in the account. 
With encryption scopes, a customer creates and manages the life-time of this key material and is able to apply it at a blob-level or default it at a container level. These scopes are created via the control plane through the API’s described in the swagger PR and are referenced in data-plane operations via headers. Particularly, when an encryption scope is created, a customer can: 
-	Create a blob using the referenced encryption scope by passing the name in the HTTP request headers.
-	Create a container setting the default encryption scope for all blobs created in it via HTTP request headers. 

This allows for customer blobs within a container/storage account to be isolated between encryption scope boundaries, since the key material used by each encryption scope is different. At the same time, customers don’t explicitly need to see/store the key itself – while the customer has control over it’s lifecycle, Storage manages the key itself and customers simply reference them by encryption scope name in requests. 

Re-iterating a few customer scenarios:
For eg. 
-	A customer can create an encryption scope and by passing a reference to this created scope while creating a blob, this blob will be encrypted on server-side using key material from this encryption scope. Note that once a scope is assigned to a blob, this cannot be changed. 
-	A customer can assign an encryption scope to a container during container creation time and this will default all blob creates within this container to use the key material from the specified scope. 
-	A customer can optionally explicitly override the default container encryption scope by passing a custom header during blob create. 
-	A customer can choose to opt-in to use platform-managed or BYOK with Azure Key Vault for the encryption scope. To opt-in to platform-managed, he would specify source=”Microsoft.Storage”. For BYOK, he would specify source=”Microsoft.KeyVault” with a reference to the keyUri in the “keyVaultProperties” attribute. Note that customers can freely move between these 2 flavors just as is the case with server-side encryption on storage accounts. 
-	Encryption scopes are created as state=”Enabled” by default. But, a customer can move the encryption scope state to “Disabled” which will cause all blob read/write operations which use this encryption scope to fail on the data-plane. Additionally, the customer will no longer be billed for this encryption scope once the state is set to “Disabled”. 

Below is the API specification doc for the REST changes we effected to support this in case this is useful. 
[SRP Encryption Scopes](https://microsoft.sharepoint.com/:w:/t/AzureStorage/EdGMgSU6-rRGiOnD6Bl3OFIBIoMkS3Q66cFUI4wK7r2AZw?e=7vVRUv)

**Minimum API Version Required**
2019-06-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/8381

**Target Date**
As soon as possible.

**Comment by arrownj** [comment]
Hi @Juliehzl , could you please help take a look at it?

**Comment by Juliehzl** [comment]
Planned in next sprint.
