### ISSUE TITLE
Azure CLI copying entire storage account recursively failed. 

### ISSUE THREAD

**Issue by mzkaramat** [Azure/azure-cli#12186]
## Describe the bug

**Command Name**
`az storage copy`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


File is not a zip file
Traceback (most recent call last):
  File "/Users/xyz/lib/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/xyz/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
BadZipfile: File is not a zip file
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage copy -s {} -d {} --recursive`

## Environment Summary
```
Darwin-19.2.0-x86_64-i386-64bit
Python 2.7.16
Shell: bash

azure-cli 2.0.79 *

```

**Comment by arrownj** [comment]
Hi @Juliehzl , could you please help take a look at it?

**Comment by yonzhan** [comment]
add to S167.

**Comment by qianwens** [comment]
@mzkaramat , it seems you are using Python 2 which is not supported by CLI now. Could you please help try to install CLI with Python 3 and try again?

**Comment by mzkaramat** [comment]
thanks, I have tried with python3 and it works.
