### ISSUE TITLE
az keyvault command to download certificate private key?

### ISSUE THREAD

**Issue by ynambiar** [Azure/azure-cli#12192]
Is there an Azure CLI command to download a certificate's private key? I've tried "az keyvault secret download" and "az keyvault certificate download" and both give me the certificate value. 

I was able to download the certificate from the Portal in pem/pfx format but when I try to use openssl to split it, it asks for an import password which I don't have or know about.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9c661d7-bf43-5354-015e-3859f30a42a2
* Version Independent ID: fa69e552-5904-ce97-d02c-915c819bdde1
* Content: [az keyvault certificate](https://docs.microsoft.com/en-us/cli/azure/keyvault/certificate?view=azure-cli-latest#az-keyvault-certificate-download)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @bim-msft could you pls help to have a look? Thanks.

**Comment by bim-msft** [comment]
@ynambiar Hi, for security concern, there is no way to download/show a private key from Key Vault, once it was imported/created, it can only be used via internal ways.

**Comment by ynambiar** [comment]
Okay, thanks for the info @bim-msft

**Comment by mattduguid** [comment]
I got both the private and public key exported using the following, worth noting in my test the certificate in keyvault had no password protection and was marked as exportable

az keyvault secret download --id https://<YOUR_VAULT_NAME>.vault.azure.net/secrets/<YOUR_CERTIFICATE_NAME> --file certificate.pem

**Comment by chirangaalwis** [comment]
> @ynambiar I got both the private and public key exported using the following, worth noting in my test the certificate in keyvault had no password protection and was marked as exportable, the other key bits were using "az keyvault secret download" and in the vault URL even though its a certifcate we are after it must use "../secrets/.." instead of "../certificates/.."
> 
> az keyvault secret download --id https://<YOUR_VAULT_NAME>.vault.azure.net/secrets/<YOUR_CERTIFICATE_NAME> --file certificate.pem

@ynambiar @mattduguid I think [this](https://docs.microsoft.com/en-us/azure/key-vault/certificates/how-to-export-certificate?tabs=azure-cli) documentation pretty much sums up the behavior.

**Comment by zioalex** [comment]
I think it should be documented also here https://docs.microsoft.com/en-us/cli/azure/keyvault/certificate?view=azure-cli-latest
