### ISSUE TITLE
Breaking change warning

### ISSUE THREAD

**Issue by anavinahar** [Azure/azure-cli#12197]
**Is your feature request related to a problem? Please describe.**
When creating a Standard Public IP, today by default, customers get a zone-redundant IP (indicated by zones: [] in ARM templates)
We are changing the default to be no-zone (indicated by zones: [] in ARM templates) and zone redundant to be indicated by zones [“1”, “2”, “3”] or a combination of any of the 2 zones.

**Describe the solution you'd like**
A warning to notify customers of the breaking change
https://docs.microsoft.com/en-us/cli/azure/network/public-ip?view=azure-cli-latest#az-network-public-ip-create
Specifically only applicable when selecting sku = Standard

**Comment by yungezz** [comment]
HI @MyronFanQiu, could you pls help to have a look? thanks.

**Comment by yonzhan** [comment]
add to S167.

**Comment by jsntcy** [comment]
@anavinahar,  
(Also reply the following questions in an email thread in case you miss it)
We are working on this issue this sprint and we have some questions need your clarification,

- Is the default behavior changed only when SKU=Standard and not specifying a zone?
- I’m confused by “We are changing the default to be no-zone (indicated by zones: [] in ARM templates) and zone redundant to be indicated by zones [“1”, “2”, “3”] or a combination of any of the 2 zones.”, could you help clarify?
  - Per my understanding, the default is changed to no-zone only?
- Is this change transparent to CLI users? If no, how can CLI users know the changes from CLI command response?
  - If I want to test the behavior change, how can I check the result?
- Is this behavior change already released? (I saw the document still uses the old behavior https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-public-ip-address)
