### ISSUE TITLE
[AD] SP/Group list commands never seem to complete

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1219]
Running `az ad sp list` or `az ad group list` seem to hang, and I've never seen either one actually complete. When I add the `--debug` flag, it appears like they're just continuously pinging the server, even though they seem to be getting 200 responses back.

**Comment by yugangw-msft** [comment]
@lostintangent, the result is paged, and command is trying to grab all items before display it. This will take a long time particularly you are in microsoft tenant.
We are looking at whether we can start to display it before reach to the end

**Comment by yugangw-msft** [comment]
Same with #1150
