### ISSUE TITLE
ARM deployment with AKS always triggers an update

### ISSUE THREAD

**Issue by OvervCW** [Azure/azure-cli#12209]
I have a deployment template for an AKS cluster with two non-autoscaling nodepools. Whenever I redeploy it using `az group deployment create` it results in the cluster status changing to "Updating" for 2 minutes, even when the template or its parameters have not changed.

I haven't seen this happen for any other type of resource, why is AKS different in this regard?

**Comment by djsly** [comment]
@OvervCW  it seems that the reconciliation of the the containerService ManagedCluster resource can take some time indeed. 

It depends on the number of nodepool and the node count they have. When issuing an empty put on the AKS resource (resources.azure.com) it does take ~2 mins even longer for the reconciliation process to complete. 

I have been told that it needs to run a check on each vm for proper extension script execution, it verifies the control plane, etc.

While we would be expecting a simple, no change, return right away, the empty PUT is often used to reconcile a failed resource during error time.

**Comment by OvervCW** [comment]
@djsly That makes sense, thanks for the response.
