### ISSUE TITLE
Cannot create diagnostic settings for a subscription

### ISSUE THREAD

**Issue by larsakerlund** [Azure/azure-cli#12213]
**Describe the bug**
When trying to create diagnostic settings for a subscription, the command fails. Error seem to indicate that a resource group is required, but since its a subscription this cannot be provided.

```bash
$ az monitor diagnostic-settings create --name "Event logs" --resource "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
usage: az monitor diagnostic-settings create [-h] [--verbose] [--debug] [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
                                             [--subscription _SUBSCRIPTION] --name NAME --resource RESOURCE_URI [--logs LOGS]
                                             [--metrics METRICS] [--event-hub EVENT_HUB] [--event-hub-rule EVENT_HUB_RULE]
                                             [--storage-account STORAGE_ACCOUNT] [--workspace WORKSPACE] [--resource-namespace NAMESPACE]
                                             [--resource-parent PARENT] [--resource-type RESOURCE_TYPE]
                                             [--resource-group RESOURCE_GROUP_NAME]
az monitor diagnostic-settings create: error: 'resource_group'
```

**To Reproduce**
Run the following command:

```bash
az monitor diagnostic-settings create --name "Event logs" --resource "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
```

Additional parameters does not alter the outcome.

**Expected behavior**
Expected a diagnostic setting to be created for the subscription.

**Environment summary**
Tested on both MacOS and Windows.

MacOS:
macOS-10.15.3-x86_64-i386-64bit
Python 3.8.1
Shell: bash
azure-cli 2.0.79

Ubuntu (WSL):
Linux-4.4.0-17134-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash
azure-cli 2.0.81

**Additional context**
Ran into the issue when trying to send activity logs from a subscription to an event hub.

**Comment by yungezz** [comment]
hi @MyronFanQiu could you pls have a look? thanks.

**Comment by larsakerlund** [comment]
Seems like it only possible to set the activity log diagnostic setting via ARM templates: https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-settings-template

**Comment by yonzhan** [comment]
add to S167.

**Comment by larsakerlund** [comment]
This seems to be what causes my issue, resource ID is expected to contain a resource group: https://github.com/Azure/azure-cli/blob/85ad0a4219c67289080d95ab26af67bd5ecd6460/src/azure-cli/azure/cli/command_modules/monitor/validators.py#L147-L149

When using `az monitor diagnostic-settings list`, the command uses Azure SDK instead which can fetch the resource by subscription ID: https://github.com/Azure/azure-sdk-for-python/blob/a1e731815288831c1c11750db734c6735934987c/sdk/monitor/azure-mgmt-monitor/azure/mgmt/monitor/v2017_05_01_preview/operations/_diagnostic_settings_operations.py#L61

**Comment by MyronFanQiu** [comment]
@larsakerlund Hello. Thanks for the investigation. Currently, resourceUri must be a resource id of a resource. CLI cannot create a diagnostic settings for a subscription. 
```
 Note

Since you can't create a diagnostic setting for the Azure Activity log using PowerShell or CLI like diagnostic settings for other Azure resources, create a Resource Manager template for the Activity log using the information in this article and deploy the template using PowerShell or CLI.
```
Looks like it's the limitation of the service. I will add service attention to invite someone to help you answer the question.

**Comment by asheniam** [comment]
This is a limitation of CLI today.  If you are trying to create a diagnostic setting for subscription to export Activity Logs, you can automate it via Azure Resource Manager (ARM) template

https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-settings-template

**Comment by nishantsondhi16** [comment]
https://medium.com/@sondhi.nishant/azure-activity-logs-eventhub-using-arm-template-295147558cfd

**Comment by nishantsondhi16** [comment]
https://medium.com/@sondhi.nishant/azure-activity-logs-eventhub-using-arm-template-295147558cfd
