### ISSUE TITLE
az apim commands dont work looking for missing module

### ISSUE THREAD

**Issue by ghost** [Azure/azure-cli#12216]
I uninstalled cli, rebooted, and installed latest version and same issue still occurs.

Have tried in powershell from portal and it works fine, installer seems to be missing files?

## Describe the bug

**Command Name**
`az apim list`

**Errors:**
```
No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
Traceback (most recent call last):
Temp\pip-install-1o1fsnhi\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 528, in execute
azure-cli-core\azure\cli\core\__init__.py, ln 300, in load_arguments
azure\cli\command_modules\apim\__init__.py, ln 28, in load_arguments
azure\cli\command_modules\apim\_params.py, ln 11, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim list`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.81

Extensions:
application-insights 0.1.3
azure-devops 0.17.0
azure-firewall 0.2.0
find 0.3.0
interactive 0.4.3

```

**Comment by PramodValavala-MSFT** [comment]
@ghost Looks like this has since been fixed and I can confirm that there is no error now. Apologies for no updates on this issue sooner. Unless you are still seeing this error on your end, I believe this could be closed.
