### ISSUE TITLE
FarmBeats - AAD Creation error 

### ISSUE THREAD

**Issue by BrahmaFarmBeats** [Azure/azure-cli#12218]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --resource {}`

## Environment Summary
```
Linux-4.15.0-1067-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.81

```

**Comment by yungezz** [comment]
Hi @BrahmaFarmBeats , thanks for reporting. Could you pls share the error detail for investigation? thanks.

**Comment by yonzhan** [comment]
add to S167.

**Comment by qianwens** [comment]
@BrahmaFarmBeats, you have opened another issue [#12224](https://github.com/Azure/azure-cli/issues/12224) with the same problem, let's track this issue in #12224 , I will close this one.
