### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hatsem78** [Azure/azure-cli#12214]
## Describe the bug

**Command Name**
``

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-5.3.0-28-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.81

```

**Comment by yungezz** [comment]
HI @hatsem78  thanks for reporting. Could you pls add more detail about which commands and what's error? thanks.
