### ISSUE TITLE
az: error: unrecognized arguments: aksmsmelonacr 

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-cli#12226]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

URL doc:
https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-update

**Describe the bug**

Use the same command as follows with different outcomes while testing with Cloud Shell and Windows Command Processor:
az aks update --name aksworkshopk8s --resource-group msaksworkshop-rg--attach-acr aksmsmelonacr

When testing with cloud Shell:
![image](https://user-images.githubusercontent.com/4621560/74593150-45e48080-5020-11ea-910e-dc685f65153f.png)

It works with Windows Command Processor : 
![image](https://user-images.githubusercontent.com/4621560/74593174-7af0d300-5020-11ea-9000-78eb0564f3cb.png)

**To Reproduce**
Steps to reproduce the behavior.

Please testing use the following command : 
az aks update --name aksworkshopk8s --resource-group msaksworkshop-rg--attach-acr aksmsmelonacr

Via CloudShell and Windows Command Processor

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by arrownj** [comment]
@cloudmelon , thanks for reporting, we will have a look.

**Comment by sauryadas** [comment]
you are missing a space between the rg name and --attach-acr flag.. come on!!

**Comment by sauryadas** [comment]
@cloudmelon please run the command with a space between the rg name and --attach-acr flag and you should be good.
