### ISSUE TITLE
[Breadth Coverage] Onboard TimeSeriesInsights Commands

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#12223]
**Spec Link**
https://microsoft.sharepoint.com/:w:/t/AzureManagementExperience/EeASGSS9OH5EoETiy56ZqKYBr85-KD5u6uxLJt3QIVNg8A?e=ZGZqHW

**ADO Item Link**
https://dev.azure.com/azure-mgmt-ex/Onboarding/_workitems/edit/126

**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.TimeSeriesInsights

**Description of Feature or Work Requested**
Support Azure CLI commands for TimeSeriesInsights

**Minimum API Version Required**
Microsoft.Databox 2018-08-15-preview

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights/preview/2018-08-15-preview

**Python SDK Link**
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/timeseriesinsights/azure-mgmt-timeseriesinsights

**Target Date**
03/06/2020

**Addtional context**
We'll use [autorest.az](https://github.com/Azure/autorest.az) from code gen team to auto-generate the code. We need provide the e2e tests for azure cli extension(also generated from swagger files). Also we need to verify the extensions can work well from user's perspective.

**Comment by yonzhan** [comment]
add to S166.
