### ISSUE TITLE
FarmBeats Error (AAD)

### ISSUE THREAD

**Issue by BrahmaFarmBeats** [Azure/azure-cli#12224]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --resource {}`

## Environment Summary
```
Linux-4.15.0-1067-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.81

```

**Comment by yonzhan** [comment]
add to S166.

**Comment by qianwens** [comment]
Hi @BrahmaFarmBeats , it seems you are using MSI authentication (Az login --identity) in Azure VM.  This error may happen if the resource type does not support MSI authentication.
Could you please help provide the parameter value of --resource?

**Comment by qianwens** [comment]
Close this issue since there is no response. Please help create a new issue if you still have questions.
