### ISSUE TITLE
az backup protectable-item list

### ISSUE THREAD

**Issue by stephenmontgomery** [Azure/azure-cli#12225]
## Describe the bug

**Command Name**
`az backup protectable-item list`

**Errors:**
```
'AzureFileShare'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.8/site-packages/six.py, ln 703, in reraise
    raise value
...
azure/cli/core/__init__.py, ln 493, in default_command_handler
    return op(**command_args)
cli/command_modules/backup/custom_base.py, ln 195, in list_protectable_items
    return custom_wl.list_protectable_items(client, resource_group_name, vault_name, workload_type, container_uri)
cli/command_modules/backup/custom_wl.py, ln 261, in list_protectable_items
    workload_type = workload_type_map[workload_type]
KeyError: 'AzureFileShare'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup protectable-item list --resource-group {} --vault-name {} --workload-type {}`

## Environment Summary
```
macOS-10.15.3-x86_64-i386-64bit
Python 3.8.1
Shell: bash

azure-cli 2.0.81

```

**Comment by arrownj** [comment]
@stephenmontgomery , thanks for reporting, we are looking at it.

**Comment by pvrk** [comment]
@sambitratha : Can you please look into this?

**Comment by pvrk** [comment]
This command is not applicable to Azure File share. Protectable items are only for DBs such as SQL and HANA. The help text seems to be wrong. Will update the help text and examples.

**Comment by pvrk** [comment]
Will update the help text for the March 30th release.
