### ISSUE TITLE
[Breadth Coverage] Onboard Databox Commands

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#12222]
**Spec Link**
https://microsoft.sharepoint.com/:w:/t/AzureManagementExperience/EXmYKGg6W21JgsJLXb_E59gBWWxPSzu955FRSDGG2UCf0g?e=I8QY8W

**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.Databox

**Description of Feature or Work Requested**
Support Azure CLI commands for databox

**Minimum API Version Required**
Microsoft.Databox 2019-09-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/databox/resource-manager/Microsoft.DataBox/stable/2019-09-01/databox.json

**Python SDK Link**
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/databox/azure-mgmt-databox

**Target Date**
03/06/2020

**Addtional context**
We'll use [autorest.az](https://github.com/Azure/autorest.az) from code gen team to auto-generate the code. We need provide the e2e tests for azure cli extension(also generated from swagger files). Also we need to verify the extensions can work well from user's perspective.

**Comment by yonzhan** [comment]
add to S166.
