### ISSUE TITLE
Provide actionable help when get error of "provider not yet registered"

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#1223]
It is possible the provider commands work with is not yet registered, say `acr`
2 options: 
1. Polish the error and tell users to run `az prvoider register`. This is xpalt does
2. Auto register it, and output a warning which tells users about this and prepare the command might still fail if the region was not propagated in time

Either way, we need to have a common step to capture the error.

**Comment by mayurid** [comment]
@yugangw-msft : As discussed we should definitely do #1.
We can discuss #2 with ACR guys as the ARM team's recommendation is to avoid this.

**Comment by SajayAntony** [comment]
We don't this auto register is a good option. Submitting a request on users behalf unintentionally seems wrong. But this applies broadly to the CLI and hence we will probably take your recommendation on this.
