### ISSUE TITLE
az group deployment validate v2.0.81 does not return error message details

### ISSUE THREAD

**Issue by petegrimsdale** [Azure/azure-cli#12241]
## Describe the bug
When runninng az group deployment validate in version 2.0.81 the detailed error status message is not returned as with previous versions of the cli.

**Command Name**
`az group deployment validate`

**Errors:**
```
{'additional_properties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'deployment_dry_run' is not valid according to the validation procedure. The tracking id is '111f0d8f-63ea-4110-b24f-ea302f4c8d3e'. See inner errors for details.", 'target': None, 'details': [<azure.mgmt.resource.resources.v2019_07_01.models._models_py3.ErrorResponse object at 0x7fc15f4a6278>], 'additional_info': None}
```

As above the Error response is not returned.  Version 2.0.73 for example returns the following from the same command:

 az group deployment validate -g rg-gateway-test --template-file deploygw_ilb.json --verbose
{
  "error": {
    "code": "InvalidTemplateDeployment",
    "details": [
      {
        "code": "ApplicationGatewayHttpsListenerSniValidOnlyForHttps",
        "details": [],
        "message": "RequireServerNameIndication can be true only if protocol is Https in Http Listener /subscriptions/f3a3b160-1d09-4e35-81d7-2f2f1461d084/resourceGroups/rg-gateway-test/providers/Microsoft.Network/applicationGateways/myghsvmssappGw/httpListeners/main_hello_dev_listener.",
        "target": null
      }
    ],
    "message": "The template deployment 'deployment_dry_run' is not valid according to the validation procedure. The tracking id is '6e714dae-8095-48a3-a6a4-42c48c6d780b'. See inner errors for details.",
    "target": null
  },
  "properties": null
}
command ran in 0.969 seconds.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

1. Run the command in version 2.0.81 of the cli

- _Put any pre-requisite steps here..._
- `az group deployment validate -g {} --template-file {} --verbose`

## Expected Behavior
To be returned the correct error status message as per previous versions of the cli

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.81 *

Extensions:
aks-preview 0.4.19
image-copy-extension 0.2.1

```

**Comment by jiasli** [comment]
@Juliehzl Please help with this issue.

**Comment by tmakin** [comment]
This problem also seems to affect `cli 2.1.0`. I'm getting the same ErrorResponse object embedded in the error message as reported above.
```
{'additional_properties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'deployment_dry_run' is not valid according to the validation procedure. The tracking id is 'f281a59f-3f72-4312-a889-d574aaf6cc91'. See inner errors for details.", 'target': None, 'details': [<azure.mgmt.resource.resources.v2019_07_01.models._models.ErrorResponse object at 0x04F31C30>], 'additional_info': None}
```

**Comment by yonzhan** [comment]
add to S167.

**Comment by naman1901** [comment]
This affects CLI v2.3.1 as well.
My error body looks like this:
`{'additional_properties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'deployment_dry_run' is not valid according to the validation procedure. The tracking id is '0bc402da-dc50-4f34-8416-6834ccbe7edd'. See inner errors for details.", 'target': None, 'details': [<azure.mgmt.resource.resources.v2019_07_01.models._models.ErrorResponse object at 0x04E4E250>], 'additional_info': None}`
