### ISSUE TITLE
How to provide customer provided key for server side encrypted blob in azure cli?

### ISSUE THREAD

**Issue by lsong0905** [Azure/azure-cli#12255]
Hello,

How can I upload/download blobs with server side encryption with customer provided key? I have not found any article that explains how to pass customer provided key and its sha256 which would be used to encrypt the blobs. If it is possible option in azure cli, would you please give an example how to pass the information in connection string? 

I am using azure-cli 2.0.37.

**Comment by Juliehzl** [comment]
Hi @lsong0905, for azure storage blob, there are two kinds of encryption, one is Microsoft.Storage managed key, another one is customer managed key. 

At first, please find which kind of encryption is used for your storage account using `az storage account show --account-name xxx ` and you can find encryption information as follows:
```
"encryption": {
    "keySource": "Microsoft.Storage",
    "keyVaultProperties": null,
    "services": {
      "blob": {
        "enabled": true,
        "lastEnabledTime": "2020-01-21T10:48:36.539558+00:00"
      },
      "file": {
        "enabled": true,
        "lastEnabledTime": "2020-01-21T10:48:36.539558+00:00"
      },
      "queue": null,
      "table": null
    }
  },
```

"Microsoft.Storage" means microsoft managed key. To use customer managed key, you need to store your key in Azure Key vault first and configure your storage account encryption method using `az storage account update` with arguments in `Customer managed key Arguments`. 
You can find more information according to https://docs.microsoft.com/en-us/azure/storage/common/storage-encryption-key-model-get?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=portal。

If you want to use cli for the operation, can you upgrade your cli version to the latest one if no other concern? azure cli 2.0.37 is very old and misses many new features.

**Comment by lsong0905** [comment]
@Juliehzl Thank you for the reply and the link! What about SSE with customer provided key, not customer managed key as explain in the link here (https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption?toc=%2fazure%2fstorage%2fblobs%2ftoc.json)?

**Comment by lsong0905** [comment]
@Juliehzl Any update on this?

**Comment by qianwens** [comment]
@lsong0905 Customer provided key is used in Rest API request or Storage SDK which is used to secure the data per request. https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption?toc=%2fazure%2fstorage%2fblobs%2ftoc.json#about-encryption-key-management
So that it is not supported in Azure CLI.

**Comment by lsong0905** [comment]
@qianwens Ok. Is there any plan that this feature will be supported in Azure CLI in future?

**Comment by qianwens** [comment]
@lsong0905 , there is no plan to support the customer provided key in CLI now since it is designed for SDK for Rest API to use. Could you please let us know why you need this support? Does customer managed key not meet your requirements?

**Comment by lsong0905** [comment]
@qianwens It is not 'must have' feature to our organization; I would say it is rather a 'good to have' feature in CLI so that when we need to diagnose issues, it would be easier to do via CLI. Thank you for the help.
