### ISSUE TITLE
Fail to deploy using az functionapp deployment source config-zip

### ISSUE THREAD

**Issue by Hazhzeng** [Azure/azure-cli#12251]
**CLI version**
2.0.81

**Describe the bug**
When deploying a local function app content to Azure Functions on Linux, the deployment can possibly fails if it requires **changes in app settings**.

There's a race condition here:
1. If the app settings are changed before the deployment is initiated, the build **succeeds**.
2. If the app settings are changed at the same time as the deployment is initiated, the /deployments/latest endpoint will return **5xx** errors due to KuduLite restart.
3. If the app settings are changed after the deployment is started, **the build will be interrupted and marked as failed deployment**.

**To Reproduce**
1. Create a Python Function App in Linux Premium Plan
2. Prepare a simple Python app content, and compress it into a zip file.
3. Run the command `az functionapp deployment source config-zip -g <resource_group> -n <app_name> --src <local_zip_file>`
4. Wait a while and will see the deployment failure error

**Expected behavior**
The deployment should succeed.

**Comment by Hazhzeng** [comment]
Please assign this issue to me. This issue is for tracking.

**Comment by gangularamya** [comment]
@Hazhzeng is there any update on the issue ?

**Comment by rohank-proarch** [comment]
I am still facing this issue while using Ubuntu 16.04 DevOps Hosted Agent. See az --version
azure-cli                          2.2.0

command-modules-nspkg              2.0.3
core                               2.2.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-devops                      0.17.0

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.6.5 (default, Mar  6 2020, 14:41:35) 
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal



Your CLI is up-to-date.
