### ISSUE TITLE
Azure CLI support for GeoMatch WAF custom rules

### ISSUE THREAD

**Issue by winthrop28** [Azure/azure-cli#12253]
**Resource Provider**
Network

**Description of Feature or Work Requested**
Adding GeoMatch as an operator for custom rules to allow/block by country code. 

**Minimum API Version Required**
2019-09-01

**Swagger Link**
App GW:https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/applicationGateway.json
WAF Policies: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/webapplicationfirewall.json

**Target Date**
March 1st

**Comment by MyronFanQiu** [comment]
@winthrop28 Hello. Could you give the PR link. If we already have PS cmdlet, it's nice to have it too.

**Comment by yonzhan** [comment]
add to S167.

**Comment by winthrop28** [comment]
Here is the concept article and the powershell how-to guide. 
https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/geomatch-custom-rules
https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/configure-waf-custom-rules

It's just another type of custom rule.

**Comment by MyronFanQiu** [comment]
@winthrop28 Hi. If I understand correctly, we just need support another type of operator in condition. Since there is not any new api and definition. It should be supported already. 
![image](https://user-images.githubusercontent.com/49134743/76185899-96a85d00-620b-11ea-8489-e864c8e562a7.png)
Could you confirm that?

**Comment by MyronFanQiu** [comment]
close this issue since it's already supported.
