### ISSUE TITLE
Stop / Cancel command?

### ISSUE THREAD

**Issue by adam-pursley** [Azure/azure-cli#12252]
Any plans to add a stop or cancel command for stopping a deployment that is already in progress, similar to the Stop-AzureRmResourceGroupDeployment PowerShell command?
https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/stop-azurermresourcegroupdeployment?view=azurermps-6.13.0
The delete command cannot delete a deployment if it's still active.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de233487-a2e5-00ab-30e9-f68866735957
* Version Independent ID: 2cd3ed9f-113f-a6c2-6a36-2925a044edf8
* Content: [az group deployment](https://docs.microsoft.com/en-us/cli/azure/group/deployment?view=azure-cli-latest#az-group-deployment-delete)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
@Juliehzl Please help with this issue.

**Comment by yonzhan** [comment]
add to S167.
