### ISSUE TITLE
"az bot msteams create" commands fails in local powershell but works in azure cloud shell

### ISSUE THREAD

**Issue by jaijitendra** [Azure/azure-cli#12257]
Bug:
"az bot msteams create" command fails in local PowerShell but works in azure cloud shell. 

Local powershell:
az cli version :  2.0.81
![image](https://user-images.githubusercontent.com/907483/74782470-5c751c80-5258-11ea-9b33-8c2324531a29.png)

Azure cloud powershell shell:
az cli version :  2.0.81
![image](https://user-images.githubusercontent.com/907483/74782920-516ebc00-5259-11ea-965e-1be9a1d578ca.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbc87f36-7863-7634-6999-ea8bdc999b1a
* Version Independent ID: 79c7e0a8-ed78-05e6-b258-ff8f09f91ccb
* Content: [az bot msteams](https://docs.microsoft.com/en-us/cli/azure/bot/msteams?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/botservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/botservice/_help.py)
* Service: **bot-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
I believe you are running this command in `[DBG]` mode which warns about messages in `stderr`. The command actually succeeds. If you check `$result`, it should contain the correct result. 

I can repro in vscode while in `[DBG]` mode:

```
[DBG]: PS C:\Users\xxx> $result = az group list --verbose
az : INFO: command ran in 1.486 seconds.
At line:1 char:11
+ $result = az group list --verbose
+           ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (INFO: command ran in 1.486 seconds.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

You may mute it with `$result = az group list --verbose 2>$null`. If you run the command in normal mode, it won't trigger this warning.

**Comment by jaijitendra** [comment]
jiasli, you are right. It works in non-debug mode but command still fails in debug mode even though I have added `--verbose 2>$null ` 

![image](https://user-images.githubusercontent.com/907483/74807451-58b7b900-529d-11ea-83d7-6d82fe56399b.png)

**Comment by jiasli** [comment]
This seems like a PowerShell issue https://github.com/PowerShell/PowerShell/issues/11133

1. What is your system?
2. Which is your PowerShell version?
3. How did you enter DBG mode?

**Comment by jaijitendra** [comment]
What is your system?
Ans : Windows 10 build 19041.113
Which is your PowerShell version?
Ans: v7.0.0-rc3
How did you enter DBG mode?
Ans: From PS integrated console in VS code.

**Comment by jiasli** [comment]
Thank you @jaijitendra, I tested in PowerShell 7.0.0 again and the issue seems to be gone. 

```pwsh
[DBG]: PS C:\Users\me> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

[DBG]: PS C:\Users\me> $result = az group list --verbose    

command ran in 2.633 seconds.
[DBG]: PS C:\Users\me> 
```

Another option is to turn off the warning. 

```pwsh
[DBG]: PS C:\Users\me> $ErrorActionPreference="SilentlyContinue"

[DBG]: PS C:\Users\me> $result = az group list --verbose        

[DBG]: PS C:\Users\me> 
```

If the preview warning is causing problem, you may use `--only-show-errors` of Azure CLI to disable that. We introduced it in https://github.com/Azure/azure-cli/pull/12604:

[Core] PREVIEW: Add `--only-show-errors` global argument to mute all warning, info and debug output. It can also be enabled by setting `AZURE_CORE_ONLY_SHOW_ERRORS` environment variable to `True` or `[core] only_show_errors=True` config (#12544)
