### ISSUE TITLE
Azure CLI support for WAF Bot Mitigation ruleset

### ISSUE THREAD

**Issue by winthrop28** [Azure/azure-cli#12254]
**Resource Provider**
Network

**Description of Feature or Work Requested**
Adding the Bot Mitigation ruleset. It can be used alongside 1 OWASP CRS ruleset. 

**Minimum API Version Required**
2019-09-01

**Swagger Link**
App GW:https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/applicationGateway.json
WAF Policies: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/webapplicationfirewall.json

**Target Date**
March 1st

**Comment by jiasli** [comment]
@MyronFanQiu

**Comment by MyronFanQiu** [comment]
@winthrop28 Hello. Could you give the PR link. If we already have PS cmdlet, it's nice to have it too.

**Comment by MyronFanQiu** [comment]
meanwhile, we're too close to March 1st. Currently, we received five feature requests about application-gateway. #12088 #11743 #12254 #12253 #12144. I don't think we have enough bandwidth to support all these features. Do you have a priority list? cc @yonzhan

**Comment by yonzhan** [comment]
add to S167.
