### ISSUE TITLE
Need an option to specify the number of the recent snapshot in the query connection monitor command

### ISSUE THREAD

**Issue by dominicha64** [Azure/azure-cli#12261]
Looks like the query commands was set to query 10 snapshots of the most recent connection state of a connection monitor by default. It took around 34 seconds for my query.
date;az network watcher connection-monitor query -l eastus -n connectionName | grep "probesFailed";date
Wed Feb 19 01:11:49 UTC 2020
      "probesFailed": 0,
      "probesFailed": 0,
      "probesFailed": 0,
      "probesFailed": 0,
      "probesFailed": 0,
      "probesFailed": 0,
      "probesFailed": 0,
      "probesFailed": 0,
      "probesFailed": 0,
      "probesFailed": 0,
Wed Feb 19 01:12:24 UTC 2020
I have a scheduled job to check the connection state of a hundred Connection Monitors, which means it would take an hour for that checking. It would be helpful if there is an option to specify the number of the recent snapshots in the Connection Monitor query command. It would help to query the recent snapshots flexibly. In my case, I only need to query 3-5 recent snapshots, and it would help to reduce the amount of time for running the scheduled job.
e.g: az network watcher connection-monitor query -l eastus -n sampleConnectionName --numberOfRecentSnapshot 3

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0800fdc3-05ed-9fa8-888a-a8997c6a5a8e
* Version Independent ID: 5d6188b7-5eb4-835d-d63a-32aa1a1f49ca
* Content: [az network watcher connection-monitor](https://docs.microsoft.com/en-us/cli/azure/network/watcher/connection-monitor?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
@MyronFanQiu Please help take a look.

**Comment by MyronFanQiu** [comment]
@haroldrandom Could you take a look~

**Comment by yonzhan** [comment]
add to S167.

**Comment by dominicha64** [comment]
Thank you @yonzhan @MyronFanQiu  @haroldrandom

**Comment by haroldrandom** [comment]
@dominicha64 I got answer from service team, the API currently don't support this feature.

Currently, there 2 version connection monitor, CMv1 and CMv2, CMv1 is deprecating. They are going to migrating to CMv2 totally.

Snapshots query API is only supported in CMv1. 

Our service teammates sugguest you to try CMv2 instead because all the snapshots are avaliable in Log Analytics. Such that, you can use [Log Analytics Workspace APIs](https://docs.microsoft.com/en-us/azure/azure-monitor/log-query/get-started-portal) to read the data in the way you like.

Something like this:
```SQL
ConnectionMonitor_CL
| where ConnectionMonitorResourceId_s == '/subscriptions/c9acd95d-34fe-4603-b50a-89c27c045b02/resourceGroups/networkwatcherrg/providers/Microsoft.Network/networkWatchers/NetworkWatcher_northeurope/connectionMonitors/Teams_MP_EUNO'
```

And maybe you need the extension `az extension add -n log-analytics`:
```Shell
$ az monitor log-analytics query -h 
This command is from the following extension: log-analytics

Command
    az monitor log-analytics query : Query a Log Analytics workspace.

Arguments
    --analytics-query [Required] : Query to execute over Log Analytics data.
    --workspace -w    [Required] : GUID of the Log Analytics Workspace.
    --timespan -t                : Timespan over which to query. Defaults to querying all available
                                   data.
    --workspaces                 : Additional workspaces to union data for querying. Specify
                                   additional workspace IDs separated by space.

Global Arguments
    --debug                      : Increase logging verbosity to show all debug logs.
    --help -h                    : Show this help message and exit.
    --only-show-errors           : Only show errors, suppressing warnings.
    --output -o                  : Output format.  Allowed values: json, jsonc, none, table, tsv,
                                   yaml, yamlc.  Default: json.
    --query                      : JMESPath query string. See http://jmespath.org/ for more
                                   information and examples.
    --subscription               : Name or ID of subscription. You can configure the default
                                   subscription using `az account set -s NAME_OR_ID`.
    --verbose                    : Increase logging verbosity. Use --debug for full debug logs.

Examples
    Execute a simple query over past 3.5 days.
        az monitor log-analytics query -w b8317023-66e4-4edc-8a5b-7c002b22f92f --analytics-query
        "AzureActivity | summarize count() by bin(timestamp, 1h)" -t P3DT12H
```

**Comment by navba-MSFT** [comment]
@dominicha64 Apologies for the late reply. This github issue has been open for quite sometime. Could you please let us know if you still need any assistance on this issue? Awaiting your reply.

**Comment by dominicha64** [comment]
I am good now, thanks very much. We already migrated to CMv2 now.

**Comment by navba-MSFT** [comment]
@dominicha64 Thanks for getting back. We will proceed with closure of this issue now. If you need any further assistance in future, please feel free to reopen this ticket and we would be happy to assist.
