### ISSUE TITLE
az lock create does not allow to set resource locks for VNet subnets

### ISSUE THREAD

**Issue by fawohlsc** [Azure/azure-cli#12268]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 
2.0.81

**Describe the bug**
`az lock create` does not allow to set resource locks for VNet subnets. The following error is shown:

> validation error: Parameter 'resource_provider_namespace' can not be None.

**To Reproduce**
See this screenshot below - basically setting a resource lock on a VNet works, but setting a resource lock in one of it's VNet subnets results in an error:
![Bug](https://user-images.githubusercontent.com/41372128/74825501-56d80f00-530a-11ea-8c16-393d7588efa8.png)

**Expected behavior**
Locking a VNet subnet should be supported.

**Environment summary**
Azure Cloud Shell (Bash) with Azure CLI 2.0.81 installed

**Additional context**
Not sure if resource locking a VNet subnet is supported by Azure in general.

**Comment by yonzhan** [comment]
add to S167.

**Comment by fawohlsc** [comment]
@yonzhan Many thanks. I assume S167 is sprint 167. What are your spring lengths and what is the current sprint? Many thanks :-)

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/milestones  three weeks cadence.

**Comment by zhoxing-ms** [comment]
@fawohlsc Hi, if you want to lock subnets, the service needs to know which virtualNetworks the subnets belong to. So `--resource` should be `{virtualNetwork-name}/subnets/{subnet-name}` and `--resource-type` should be `Microsoft.Network/virtualNetworks`.
The correct command format is as follows:
`az lock create --name {lock-name} --lock-type ReadOnly --resource-group {resource-group} --resource-type Microsoft.Network/virtualNetworks --resource {virtualNetwork-name}/subnets/{subnet-name}`

**Comment by zhoxing-ms** [comment]
@fawohlsc However, I found that there is no entry on portal to support locking subnets granular resources, please help to confirm whether this function is reasonable and needed?
If so, please contact members of the portal team to add the ability to lock subnets granular resources. And I will supplement this example in the CLI help documentation.

**Comment by fawohlsc** [comment]
@zhoxing-ms first of all many thanks for your insightful response and proactivity to add this to the documentation. Great job! 🥇 

Many customers want to empower their developers to create or change VNet subnets, i.e. all auto-scalable resources in Azure usually require a dedicated subnet (VMSS, AAG, APIM, ...). But some of the subnets contain shared resources or resources managed by central IT - here we require a lock for the subnets. Following I think we should add this feature to the portal as well. Can you point me to their repository? Was not able to find it... Many thanks in advance!

**Comment by allegradomel** [comment]
If this issue concerns only Portal side I will untag SDN

**Comment by fawohlsc** [comment]
@allegradomel issue works in Azure CLI but not documented. @zhoxing-ms opened a pull request to enhance documentation. Feature is unfortunately not available in Azure Portal.
