### ISSUE TITLE
apply-network-updates doc is incorrect as it doesn't reflects its right purpose

### ISSUE THREAD

**Issue by meetamitbhatia** [Azure/azure-cli#12275]
The az apim apply-network-updates should be updating APIM resource running in the Virtual network to pick the updated network settings. However, docs suggests that it "Back up an API Management service to the configured storage account" which is wrong.

More details:
az apim apply-network-updates calls below REST call internally which should update the network settings.
https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/applynetworkconfigurationupdates?api-version=2019-01-01

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 197d8382-ee16-6001-4941-768877379c0d
* Version Independent ID: 1423fa76-977f-ad88-8129-0b52a38e68e6
* Content: [az apim](https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/apim/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/apim/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by joozek78** [comment]
Almost 2 years have passed and this trivial issue hasn't been solved yet. Is anyone looking at those?

**Comment by yonzhan** [comment]
API management service team should take a look

**Comment by RakeshMohanMSFT** [comment]
@meetamitbhatia We are really sorry for the delay and thank you reaching out we are looking into the issue and will help you with an update as soon as possible. Thank you for your patience and understanding.

**Comment by RakeshMohanMSFT** [comment]
@meetamitbhatia This issue is fixed https://github.com/Azure/azure-cli/pull/21708
