### ISSUE TITLE
Failed to update task with "--commit-trigger-enabled true"

### ISSUE THREAD

**Issue by RogerBestMsft** [Azure/azure-cli#12276]
## Describe the bug
Unable to update an existing task to enable commit trigger.

**Command Name**
`az acr task update`

**Errors:**
```
expected string or bytes-like object
Traceback (most recent call last):
Temp\pip-install-0u_uiwkq\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 608, in execute
azure\cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 659, in _run_job
Local\Temp\pip-install-0u_uiwkq\six\six.py, ln 696, in reraise
azure\cli\core\commands\__init__.py, ln 636, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 493, in default_command_handler
azure\cli\command_modules\acr\task.py, ln 392, in acr_task_update
azure\cli\command_modules\acr\task.py, ln 997, in _get_branch_name
Microsoft SDKs\Azure\CLI2\lib\re.py, ln 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr task update -n {} -r {} -f {} --commit-trigger-enabled true`

## Expected Behavior
Update the task

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.80 *

Extensions:
azure-devops 0.8.0
dev-spaces 1.0.4
interactive 0.4.3

```

**Comment by northtyphoon** [comment]
@rosanch can you please take a look? If `context_path` is not passed to`task update` command, it can throw error in _get_branch_name function 

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/task.py#L397

**Comment by yugangw-msft** [comment]
fixed
