### ISSUE TITLE
Could not enable aks dashboard on aks cluster

### ISSUE THREAD

**Issue by fgauna12** [Azure/azure-cli#12274]
## Describe the bug

Was trying to enable the kubernetes dashboard on an existing aks cluster deployed through Terraform. 

**Command Name**
`az aks enable-addons`

**Errors:**
```
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
Temp\pip-install-0u_uiwkq\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 608, in execute
azure\cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 659, in _run_job
Local\Temp\pip-install-0u_uiwkq\six\six.py, ln 696, in reraise
azure\cli\core\commands\__init__.py, ln 636, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 493, in default_command_handler
azure\cli\command_modules\acs\custom.py, ln 1844, in aks_enable_addons
azure\cli\command_modules\acs\custom.py, ln 2487, in _ensure_container_insights_for_monitoring
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons --addons {} -n {} -g {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.80 *

Extensions:
azure-devops 0.17.0

```

**Comment by jluk** [comment]
We believe a fix has been made, please reference this issue for the latest tracking. I am going to close this to consolidate info to one thread. If you still hit issues after the S166 milestone release, feel free to recomment.

https://github.com/Azure/azure-cli/issues/11456
