### ISSUE TITLE
CLI support for file share soft delete

### ISSUE THREAD

**Issue by zfchen95** [Azure/azure-cli#12278]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Storage
**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
Storage RP will provide the API for user to list and restore deleted file shares once the share retention policy is set.
https://microsoft-my.sharepoint.com/:w:/p/zhenche/EQKJgqPYXSVLt35pesoLEfIBw_L9wJ7zYVZHOpKqj1eHWw?e=Zu17bt
**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2019-06-01
**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
https://github.com/Azure/azure-rest-api-specs/pull/7988
**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

**Comment by Juliehzl** [comment]
Thanks @zfchen95. Could you please share with us the target date for your feature?
