### ISSUE TITLE
Distribute Self-Signed Client Certificates

### ISSUE THREAD

**Issue by thall** [Azure/azure-cli#12288]
Hi,

I have created self-signed root ca certificate, intermediate certficate and client certificates.
I have imported the certificates to the KeyVault (in both formats, pem and pkcs12 (without password, seems to be removed..)).

The problem I'm facing is how I can distribute my password protected client certificate in pkcs12 format. I don't want to give access to download my `keys` or `secrets` in the KeyVault, because then i will expose other secrets that should not be revealed. 

I want my users to use `az login` and `az keyvault certificate download` and download the password protected pkcs12 certificate and unpack it using a password i supply via another channel, how can i achieve this?

Related issue: https://github.com/Azure/azure-cli/issues/11576

**Comment by yungezz** [comment]
thanks for reporting, we'll look at it.

**Comment by bim-msft** [comment]
Related to #11576 , we are investigating this.

**Comment by sebansal** [comment]
@bim-msft It's a feature request (Related to #11576)
Can you please mark appropriately

**Comment by sebansal** [comment]
It is by design that key vault does not export certs with password.

**Comment by thall** [comment]
Then azure key vault and azure cloud not an option.

**Comment by sebansal** [comment]
To address this - **I don't want to give access to download my keys or secrets in the KeyVault, because then i will expose other secrets that should not be revealed.**

You can grant role based access to provide fine-grained access management https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide

**Comment by thall** [comment]
How will that solve my initial issue? I don't see how I can achieve it  with your suggestion, or did I miss something?

**Comment by jlichwa** [comment]
@thall password protected certificates are not supported today. Please vote on User Voice for new feature request: https://feedback.azure.com/forums/906355-azure-key-vault/suggestions/32603098-add-support-for-storage-and-retrieval-of-password so we can push internally to provide that feature in the future.

**Comment by thall** [comment]
Thanks for clarification @jlichwa! Then Azure Key Vault isn't not a option for me.
