### ISSUE TITLE
functionapp: az cli disables build on deploy for windows function apps

### ISSUE THREAD

**Issue by jikuja** [Azure/azure-cli#12289]
**Describe the bug**
https://github.com/Azure/azure-cli/pull/10706 effective disables remote builds for windows consumption plan function apps. 

Changelog does not mention that new flag is for linux function apps only:
> Added --build-remote flag for az functionapp deployment source config-zip to support remote build action during function app deployment.

Also no deprecation warning for have been given for windows consumption plan with SCM_DO_BUILD_DURING_DEPLOYMENT=true

Documentation[1] does not specify any ways to trigger `npm install`.

**To Reproduce**
Running `az functionapp deployment source config-zip --build-remote ...` fails with `Remote build is only available on Linux function apps`

Alternative running `az functionapp deployment source config-zip` without --build-remote flag **changes function app settings** and does **not trigger `npm install`**:

```
Setting ENABLE_ORYX_BUILD to false
Setting SCM_DO_BUILD_DURING_DEPLOYMENT to false
```

**Expected behavior**
After zip deployment function host should trigger `npm install`(or other installation method) like az cli did before the pull request.

Alternative fix: another way to trigger `npm install` after deployment with az cli should be documented.

**Environment summary**
```
azure-cli                          2.1.0

command-modules-nspkg              2.0.3
core                               2.1.0
nspkg                              3.0.4
telemetry                          1.0.4
```

**Additional context**

[1] https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#remote-build

**Workrounds**

- Trigger npm install manually in kudu console
- fetch publishing profile with az cli and trigger npm install through kudu REST API

**Comment by anthonychu** [comment]
Thanks. Created issue to track this for the Functions team: https://github.com/Azure/Azure-Functions/issues/1509

Also look into the same for Core Tools: https://github.com/Azure/azure-functions-core-tools/issues/1854

**Comment by jikuja** [comment]
For Azure web apps this bug was fixed in one month.

It's now 2,5 half months since bug report and over six month since breaking commit. Is this going to be fixed or should we start building workarounds and create bug tickets for existing documentations referring usage of SCM_DO_BUILD_DURING_DEPLOYMENT for controlling remote builds?

**Comment by anthonychu** [comment]
@Hazhzeng Can you please take a look at this and see if we can fix it for functionapp as well? Thanks.

**Comment by mortezasoft** [comment]
What is the latest status of this issue? I have the same issue with the latest version of Azure CLI.

**Comment by esmcelroy-rci** [comment]
This is still an issue to date! Would love to see this resolved. Even if you force the SCM_DO_BUILD_DURING_DEPLOYMENT in your .deployment, on the function app and all slots, it forces it back to false! Not looking forward to publishing using the REST API, but I'm going to have to build a workaround for this issue...
I'm trying to deploy a .NET Core function app as well, and this is still a problem! 
@Hazhzeng any updates on this?

**Comment by pniederlag** [comment]
any way to trigger "npm install" (or even better npm ci) when using "az functionapp deployment source config-zip" on a windows host by now?

**Comment by Stateofminf** [comment]
s

**Comment by rajaprad** [comment]
@Hazhzeng @alexkarcher-msft  any updates to this issue. This has broken an working deployment flow.  SCM_DO_BUILD_DURING_DEPLOYMENT has to be allowed to be set to true for windows as well. What is the workaround till the issue is addressed. Please share documentation on the workaround.

**Comment by esmcelroy-rci** [comment]
@rajaprad @pniederlag What worked for me was to change my installation from using `az functionapp deployment source config-zip` to using `az webapp deployment source config-zip`

Not sure if there are other impacts from switching from functionapp to webapp, but it worked for our .NET 3.x function app being deployed on Windows hosts.

**Comment by anthonychu** [comment]
@panchagnula Can you please take a look at this?

**Comment by panchagnula** [comment]
@StrawnSC can you investigate - AFAIK no changes were to function app deployment that should regress this.
