### ISSUE TITLE
Azure cli uptime

### ISSUE THREAD

**Issue by vsnarkhede13** [Azure/azure-cli#12281]
Is it possible to fetch uptime for each resource through azure cli without using additional service like cloudyn? If yes then how?

**Comment by yonzhan** [comment]
add to S167.

**Comment by ms-premp** [comment]
No, this is not possible. The consumption module only gives the consumption and cost. There is no concept of uptime. 
Please use individual service SDKs to get that data.

**Comment by ramaganesan-rg** [comment]
closing the issue based on comments above.
