### ISSUE TITLE
Telemetry enabled flag should be easy to query from azure cli extensions 

### ISSUE THREAD

**Issue by atbagga** [Azure/azure-cli#12285]
**Is your feature request related to a problem? Please describe.**
We have an extensions where we log telemetry after user permission. Since Azure CLI allows users to set this we depend on reading this value. 

There should be a way to query this using azure cli core api so the logic is consistent. 

**Describe the solution you'd like**
Azure CLI core telemetry module should have a is_telemetry_enabled() function which returns whether telemetry collection is allowed or not. 

This is with reference to issue: https://github.com/Azure/azure-devops-cli-extension/issues/950

**Comment by yungezz** [comment]
good suggestion, will look at it.

**Comment by fengzhou-msft** [comment]
Planned in S166.
