### ISSUE TITLE
az acr login returns with error 1

### ISSUE THREAD

**Issue by szaboferee** [Azure/azure-cli#12280]
## Describe the bug
Using the official microsoft/azure-cli docker image, the az acr login command returns with a simple docker login warning and an error code. This warning was present before and didn't cause any issue. 

the warning is the following:
```
docker: WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

it looks like the root cause is this change: 
https://github.com/Azure/azure-cli/pull/12156/files

**Command Name**
`az acr login`

**Errors:**
return code is 1

## To Reproduce:
- `az acr login --name {}`

## Expected Behavior
return code should be 0 as before because it is only a warning from docker

## Environment Summary
```
Linux-5.3.0-40-generic-x86_64-with
Python 3.6.9

azure-cli 2.1.0

```
## Additional Context
An alternative solution would be to add a docker-credential-helper to the docker image, however alpine linux has no released packages of either `pass` or `secretservice` to provide that. Only `pass` is available on the edge branch in the testing repository.

**Comment by yugangw-msft** [comment]
This is fixed by #12282, that we will respect the exit code of docker, instead of sniffing out the stderr
@szaboferee, thanks for the reporting this.

**Comment by szaboferee** [comment]
Thank you for the quick response and fix @yugangw-msft

**Comment by tjcrone** [comment]
Thanks for helping to fix this @yugangw-msft. We would like to get this merge incorporated, but it's not clear how to pip install the CLI from a development branch. Are there instructions on how to do this?

**Comment by yugangw-msft** [comment]
The most efficient way was to 
```bash
1. pip install azdev
2. azdev setup -c
```
Check out the doc for more details
