### ISSUE TITLE
CLI immutable append blob support

### ISSUE THREAD

**Issue by xyh1** [Azure/azure-cli#12293]
**Resource Provider**
Azure Storage
Blob service
containers
immutability policies

**Description of Feature or Work Requested**

Extension of blob container immutability feature that allows append blobs to be appended to even within a WORM policy as previous data cannot be modified or deleted. Only new data is added.

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-immutable-storage#allow-protected-append-blobs-writes

**Minimum API Version Required**

2019-06-01 

**Swagger Link**
privatebranch PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/1105
Will be merged before 2/30

**Target Date**
~3/15

**Comment by yonzhan** [comment]
add to S166.
