### ISSUE TITLE
Cannot use az login with user assigned managed identity

### ISSUE THREAD

**Issue by williamamincey** [Azure/azure-cli#12294]
## Describe the bug
Cannot login to subscription using user assigned managed identity

**Command Name**
`az login`

**Errors:**
```
HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01&msi_res_id=%2Fsubscriptions%2F50196bc3-8713-44fa-959d-2e6685b3d73f%2FresourceGroups%2Fsastst_pb_westus%2Fproviders%2FMicrosoft.ManagedIdentity%2FuserAssignedIdentities%2Fsastst-mi-pb-westus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0567C390>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network',))
Traceback (most recent call last):
pip-install-0h4gq3wj\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

-  Create user assigned managed identity in a subscription
- Attempt to login from local machine using CLI
-- `az login --identity -u {user assigned managed service identity id (from portal)}`

## Expected Behavior
- successful login

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.73 *

Extensions:
dev-spaces 1.0.3
interactive 0.4.3

```

**Comment by yonzhan** [comment]
add to S167.

**Comment by qianwens** [comment]
@williamamincey , MSI credential login is only supported in Azure VM and you need to assign a managed identity to the VM https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-portal-windows-vm#assign-a-user-assigned-identity-during-the-creation-of-a-vm

**Comment by jiasli** [comment]
Duplicate of #10998

**Comment by oskaremil** [comment]
It would be helpful if this page https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli-managed-identity mentioned that.

**Comment by jiasli** [comment]
> It would be helpful if this page https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli-managed-identity mentioned that.

The document does contain
