### ISSUE TITLE
Ability to specify lun while creating a SIG Image Version with snapshots

### ISSUE THREAD

**Issue by axayjo** [Azure/azure-cli#12299]
In the sample below, 
'sig image-version create -g {rg} --gallery-name {gallery} --gallery-image-definition {image} --gallery-image-version 1.0.0 --os-snapshot s1 --data-snapshots s2 s’
 
How do we specify LUN for data disks?

Code:
if data_snapshots:
    data_disk_images = []
    for i, s in enumerate(data_snapshots):
        data_disk_images.append(GalleryDataDiskImage(source=GalleryArtifactVersionSource(id=s), lun=i))
lun is set automatically from 0, 1, 2 ...

I can add a parameter to specify lun, like --data-snapshot-luns. It receives a list of luns, separated by space.

**Comment by yungezz** [comment]
we're working on in this release.

**Comment by qwordy** [comment]
This feature will be available on 03/10/2020. If any problem, you can comment here or open a new issue.
