### ISSUE TITLE
az ams account sp create fails on cloud shell (bash)

### ISSUE THREAD

**Issue by NickDrouin** [Azure/azure-cli#12297]
Are additional params needed when using azure cloud shell?
I get: 
(InvalidAuthenticationTokenAudience) The access token has been obtained for wrong audience or resource 'https://graph.windows.net/'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac1591fe-2c4e-ff7f-8bd3-147af242f417
* Version Independent ID: 62004fa4-3041-55bc-52f9-62d47a501dc5
* Content: [az ams account sp](https://docs.microsoft.com/en-us/cli/azure/ams/account/sp?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/ams/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/ams/_help.py)
* Service: **media-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by mbsnl** [comment]
We observe similair issues from CloudShell. This command is also not reliable and doesnot work every now and then and aprox. 30 minutes later it's fine:
`azureuser@Azure:~$ az acr list
The access token has been obtained for wrong audience or resource 'https://graph.windows.net/'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'.`

**Comment by KarenTazayan** [comment]
I have the same issue. Any news?

**Comment by hivyas** [comment]
Hi there, we opened a Ticket 7432363 on our team, will be working on fixing this issue.

**Comment by NickDrouin** [comment]
At the time, the steps were similar to:

SALT="somename"
az group create --name rg-ams-"$SALT" --location eastus
az storage account create --name saams"$SALT" -g rg-ams-"$SALT"
az ams account create --name ams"$SALT" -g rg-ams-"$SALT" --storage-account saams"$SALT"
az ams account sp create --account-name ams"$SALT" -g rg-ams-"$SALT"

**Comment by hivyas** [comment]
Hi there, using the repro steps above this issue is no longer present so we are closing the ticket on our team. 
Please reach out if the issue persists.
