### ISSUE TITLE
0.4.30 aks-preview failed to add an agent pool to a new created aks cluster

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-cli#12304]
## Describe the bug
0.4.30 aks-preview failed to add an agent pool to a new created aks cluster

**Command Name**
`az aks nodepool add     --resource-group spot     --cluster-name k8s     --os-type Linux     --name nplinux     --node-count 1     --kubernetes-version 1.15.5`

**Errors:**
--spot_max_price can only be set when --priority is Spot

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```
az extension add --name aks-preview
az extension update --name aks-preview
az group create --name spot --location westeurope
PASSWORD_WIN="XXXXXXXXXXXXXXX
az aks create \
    --resource-group spot \
    --name k8s \
    --node-count 1 \
    --enable-addons monitoring \
    --kubernetes-version 1.15.5\
    --generate-ssh-keys \
    --windows-admin-password $PASSWORD_WIN \
    --windows-admin-username azureuser \
    --vm-set-type VirtualMachineScaleSets \
    --load-balancer-sku standard \
    --network-plugin azure
az aks nodepool add \
    --resource-group spot \
    --cluster-name k8s \
    --os-type Windows \
    --name npwin \
    --node-count 1 \
    --kubernetes-version 1.15.5
```
- _Put any pre-requisite steps here..._
- ``

## Expected Behavior
The agent pool is added successfully
## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.77

Extensions:
aks-preview 0.4.30

```

**Comment by AbelHu** [comment]
Could anyone provide a source url to install an old work version? Thanks.

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli-extensions/pull/1304/files

**Comment by yonzhan** [comment]
move to S167

**Comment by AbelHu** [comment]
Thanks.
