### ISSUE TITLE
Webapp create with runtime aspnet|V4.7 fails

### ISSUE THREAD

**Issue by clinsted** [Azure/azure-cli#12302]
## Describe the bug
When creating a webapp with the --runtime arg and specifying "aspnet|V4.7". The same command succeeds with "node|10.6", or any of the node runtime values (and possibly others).

**Command Name**
`az webapp create`

**Errors:**
```
update_site_config() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
Temp\pip-install-3pnsb50r\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 608, in execute
azure\cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 657, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 55, in _polish_bad_errors
azure\cli\core\commands\__init__.py, ln 636, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 493, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 135, in create_webapp
TypeError: update_site_config() takes 2 positional arguments but 3 were given
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
az group create...
az appservice plan create...

- `az webapp create --name {} --plan {} --resource-group {} --subscription {}  --% --runtime "aspnet|V4.7"`

or 

- `az --% webapp create --name {} --plan {} --resource-group {} --subscription {} --runtime "aspnet|V4.7"`

## Expected Behavior
I expect the web app to be created with .net 4.7 configured as the stack.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6

azure-cli 2.1.0

Extensions:
application-insights 0.1.3
interactive 0.4.3
storage-preview 0.2.10

```
## Additional Context
After creating the app with node as the runtime, then navigating to the app thru the Azure portal the stack is listed as .net V4.7.

Tried PowerShell & Bash

**Comment by panchagnula** [comment]
This is fixed with the latest version https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#appservice please upgrade & re-try. Thanks!

**Comment by dariuszbz** [comment]
PS F:\Repos\Offline\Auth-Hub> az version

This command is in preview. It may be changed/removed in a future release.
{
  "azure-cli": "2.2.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.2.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.33",
    "dev-spaces": "1.0.3",
    "front-door": "1.0.2"
  }
}


and still getting an error: 'V4.7' is not recognized as an internal or external command. web app not created.

**Comment by clinsted** [comment]
This is now working for me:
az webapp create --name {} --plan {} --resource-group {} --subscription {} --% --runtime "aspnet|V4.7"

webapp was created successfully with the correct stack.

az version

{
  "azure-cli": "2.2.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.2.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "application-insights": "0.1.3",
    "azure-devops": "0.17.0",
    "interactive": "0.4.3",
    "storage-preview": "0.2.10"
  }
}
