### ISSUE TITLE
Remove Windows binary propagate_env_change.exe from source repository

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#12307]
Original PR: https://github.com/Azure/azure-cli/pull/12296

`build_scripts/windows/propagate_env_change/propagate_env_change.exe` shouldn't be included in the repro and will trigger warnings in some customer's pipelines. 

Let's move it to `https://azurecliprod.blob.core.windows.net/util/` just like the built-in python:

https://github.com/Azure/azure-cli/blob/62307e97c96ba739568e96d7815ec51d35ae6fef/build_scripts/windows/scripts/build.cmd#L15

**Comment by fengzhou-msft** [comment]
Thanks. I will take a look.

**Comment by jiasli** [comment]
I did some more research and maybe we can use [WixBroadcastEnvironmentChange Custom Action](https://wixtoolset.org/documentation/manual/v3/customactions/wixsettingchange.html) instead.

**Comment by jiasli** [comment]
An alternative is to use [WixBroadcastEnvironmentChange Custom Action](https://wixtoolset.org/documentation/manual/v3/customactions/wixsettingchange.html) instead. But this introduces more dependency.
