### ISSUE TITLE
AZ login command in Powershell does not work as expected

### ISSUE THREAD

**Issue by rinaldochristy** [Azure/azure-cli#12310]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When I run the AZ login command in Powershell (Run as Admin), I am able to authenticate however powershell throws the below error:

Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x049C0770>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

PLEASE NOTE: I AM NOT USING ANY PROXY.

**To Reproduce**

I checked if there is any proxy thats blocking me, but I do not have any proxies set up.

**Expected behavior**
What I expected to happen is, after running the az login command, and after I authenticate my credentials, powershell should say - You have logged in. Now let us find all the subscriptions to which you have access... and then it should show my subscription details, tenant ID, cloud name etc.

**Environment summary**
I am using Windows 10.
Azure CLI (2.1.0) through PowerShell

**Additional context**
Below is the screenshot of the window that shows that I was able to authenticate successfully.
![Capture](https://user-images.githubusercontent.com/45920198/75045725-21772100-54c4-11ea-9de0-c87fb13390bf.PNG)

**Comment by yonzhan** [comment]
add to S167.

**Comment by yonzhan** [comment]
add to S167.

**Comment by AllonJunior** [comment]
I also encoutered this error, is there any update?

**Comment by rinaldochristy** [comment]
Hi @AllonJunior ,

I was able to solve this problem by creating an environment variable as described in the link below:

https://stackoverflow.com/questions/20500613/how-to-set-a-proxy-for-the-azure-cli-command-line-tool

**Comment by jiasli** [comment]
Please make sure the python environment has internet access:

```
python -c "import urllib.request; print(urllib.request.urlopen('https://www.azure.com/').info())"
```

More information on proxy-related issue: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy

**Comment by rinaldochristy** [comment]
Hi @jiasli ,

This is what I get when I run the cmdlet you sent me:

PS C:\WINDOWS\system32> python -c "import urllib.request; print(urllib.request.urlopen('https://www.azure.com/').info())"
Cache-Control: no-cache
Keep-Alive: timeout=10, max=100
Pragma: no-cache
Content-Length: 251649
Content-Type: text/html; charset=utf-8
Expires: -1
Set-Cookie: userInfo={"guid":"24366D7F69CB6078222B63FB68BA6102"}; expires=Fri, 05-Mar-2021 10:55:51 GMT; path=/; secure
Azure-Version: 20200304-1144-151358
Azure-SiteName: acom-prod-westeurope-02
Azure-InstanceId: 75ce112a088adede3d2a2eaa4b9273f9eea76541a198d6a5d467f064a6324249
Azure-RegionName: West Europe
Azure-SlotName: production
Request-Context: appId=cid-v1:271db03b-0de6-4bf7-8ebf-f90dccf4de6b
Access-Control-Expose-Headers: Request-Context
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
Arr-Disable-Session-Affinity: true
Access-Control-Allow-Methods: GET,HEAD
Strict-Transport-Security: max-age=31536000
X-MSEdge-Ref: Ref A: B938D954FD7E45C4AB5748098E801139 Ref B: FRAEDGE0819 Ref C: 2020-03-05T10:55:51Z
Date: Thu, 05 Mar 2020 10:55:50 GMT
Connection: close

So am I all set?

**Comment by jiasli** [comment]
Hello! Yes, this is the expected result and it indicates your python environment is correctly set up. Don't hesitate to let me know if there are any further issues.
