### ISSUE TITLE
az webapp up with a basic nodejs api: Permission denied

### ISSUE THREAD

**Issue by MaximRouiller** [Azure/azure-cli#12316]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
[Errno 13] Permission denied: 'C:\\\\tests.zip'
Traceback (most recent call last):
Temp\pip-install-64vfp5fb\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 608, in execute
azure\cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 657, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 55, in _polish_bad_errors
azure\cli\core\commands\__init__.py, ln 636, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 493, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 3081, in webapp_up
azure\cli\command_modules\appservice\_create_util.py, ln 37, in zip_contents_from_dir
Microsoft SDKs\Azure\CLI2\lib\zipfile.py, ln 1090, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'C:\\\\tests.zip'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az webapp up -n msp001 -l eastus --debug`

The application had already had GitHub Actions integrated with it. No idea if it's relevant.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.79 *

```

**Comment by yonzhan** [comment]
az webapp

**Comment by panchagnula** [comment]
This command tries to create and add a zip file at the location where the command is run from - does CLI have write access on this folder.

**Comment by MaximRouiller** [comment]
Yes it did.

**Comment by panchagnula** [comment]
The error here as per the stack trace is the Python Zip library is having issues unable to access to the folder or permissions to write. Not specific to CLI or the command can you make sure you have the right permissions .
