### ISSUE TITLE
Unable to use colon in tag name for CDN profile

### ISSUE THREAD

**Issue by sseveringhaus-newclassrooms** [Azure/azure-cli#12314]
**Describe the bug**
When adding a tag to a CDN profile resource, if the tag name contains a colon, the error `Tag cannot contain special characters.` is returned.

**To Reproduce**
Pick a CDN profile resource (`Microsoft.Cdn/profiles`), try to run `az resource tag` with a tag containing a colon.

**Expected behavior**
The tag should be added to the resource, or the [documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support#microsoftcdn) should note this limitation.

**Environment summary**
`azure-cli` 2.1.0 on Ubuntu 18.04

**Additional context**
Here's an example:
```
$ az resource tag --ids xxx --tags foo:bar=baz
Tag cannot contain special characters.
```
This is distinct from the "reserved characters" error message, which is [documented](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources#limitations) clearly:
```
$ az resource tag --ids xxx --tags foo%bar=baz
The tag names 'foo%bar' have reserved characters '<,>,%,&,\,?,/' or control characters. These characters are only allowed for tags that start with the prefix 'hidden, link'.
```
Trying to save a tag with a colon in the Azure Portal results in a 400 error from the batch API, which sometimes leads to a silent failure to save the tags and sometimes results in a visible error message, `Could not save the tags for the resource...`.

This error seems to have surfaced for other resource types in the past:
* https://github.com/MicrosoftDocs/azure-docs/issues/20850
* https://github.com/MicrosoftDocs/azure-docs/issues/11340

**Comment by yonzhan** [comment]
add to S167.

**Comment by sseveringhaus-newclassrooms** [comment]
I can't do extensive testing on it right now, but I believe the same problem exists with CDN endpoints. I'll just quote the error that Terraform is giving me:
```
Error: Error updating CDN Endpoint "nccrtxcdntest" (Profile "xxx" / Resource Group "xxx"):
    cdn.EndpointsClient#Update: Failure sending request: StatusCode=400 --
    Original Error: Code="BadRequest" Message="Tag cannot contain special characters."
```

**Comment by zhoxing-ms** [comment]
@nachakra Hi, when we call this Service [(Profiles - Create)](https://docs.microsoft.com/en-us/rest/api/cdn/profiles/create), if the tag in the parameter contains a colon, Service will return the following error:
```
{
  "error": {
    "code": "BadRequest",
    "message": "Tag cannot contain special characters."
  }
}
```
Could you please take a look~

**Comment by yonzhan** [comment]
@nachakra any update?

**Comment by idatum** [comment]
CDN has unique limitations on keys and only allows the following characters (per regex):
`^([a-zA-Z0-9-_\s]+)$`

We don't have a timeline when this limitation will ultimately be lifted. In the meantime, we will update our tag documentation for CDNs.

Our goal is to make tags consistent across all resource providers, including acceptable key characters.

**Comment by navba-MSFT** [comment]
@sseveringhaus-newclassrooms Apologies for the late reply. I was able to run the AzCLI command and set the tags with colon on CDN resource. Could you please test the same and get back to me if you face any issues ? 

Also this issue is open for quite sometime. Please let me know if you need any further assistance on this. Awaiting your reply.

**Comment by sseveringhaus-newclassrooms** [comment]
Thanks for following up, but we're no longer using Azure CDN, so I don't have a way to test this. Please feel free to close the issue.

**Comment by navba-MSFT** [comment]
@sseveringhaus-newclassrooms Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
