### ISSUE TITLE
az container exec shows color codes instead of colors

### ISSUE THREAD

**Issue by stmax82** [Azure/azure-cli#12329]
## Describe the bug

When I open a remote shell in a container using `az container exec` and it tries to output colors I get weird color codes instead of fancy colors:

PowerShell:

![image](https://user-images.githubusercontent.com/6381927/75133346-b0f61d00-56da-11ea-8ccf-8818abbf9d03.png)

Command Line:

![image](https://user-images.githubusercontent.com/6381927/75133772-46de7780-56dc-11ea-9601-7c04524b76bb.png)

Colors seem to work fine in the same powershell though, here's a python script that prints some colored text:

![image](https://user-images.githubusercontent.com/6381927/75133381-d97e1700-56da-11ea-9975-221e8a7d736c.png)

When I run az container exec in a powershell window within VS Code, colors are displayed correctly:

![image](https://user-images.githubusercontent.com/6381927/75133487-4e515100-56db-11ea-9400-c671f1e7dd14.png)

Colors also work when logged in through the azure portal:

![image](https://user-images.githubusercontent.com/6381927/75133549-8f496580-56db-11ea-91aa-fcf5a2892d20.png)

## Expected behaviour

`az container exec` should either display colors or stop pretending to be a terminal that can display colors (i.e. show no colors at all).

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.76 *
azure-cli-iot-ext 0.8.7

Extensions:
azure-cli-iot-ext 0.8.7

```

**Comment by stmax82** [comment]
Here's me trying to type "use mydb" :/ this is unusable right now...

![image](https://user-images.githubusercontent.com/6381927/75134788-9ecaad80-56df-11ea-8477-181aa5166cb7.png)

**Comment by yonzhan** [comment]
container

**Comment by navba-MSFT** [comment]
@stmax82 Apologies for the late reply. I tried to repro the issue at my end. Though the colors are not displayed. I couldn't see any color codes this time in the _cmd_ prompt. This issue is open for quite sometime now. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@stmax82 Sorry to hear about that. Please feel free to reopen this thread in future if you have plans of using the ACI and face any issues with that. We would be happy to assist you further.
