### ISSUE TITLE
[Keyvault] AES Key Support - Managed HSM

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#12328]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Keyvault

**Description of Feature or Work Requested**
AES Key Support for Managed HSM.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

**Swagger Link**
will add later.

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

**Comment by yungezz** [comment]
one item of keyvault managed HSM feature. Looking at it.

**Comment by yungezz** [comment]
feature work done and tested by service team. release is pending on service side public, currently private preview.

**Comment by yungezz** [comment]
move all MSHM related feature to backlog. current status is CLI feature ready for features with Swagger, but not released due to service not public yet.  Public preview maybe around June/July timeline, but not locked down yet. Will close the issue when service public and CLI feature merged/released.

**Comment by bim-msft** [comment]
Already delivered privately.
