### ISSUE TITLE
webapp: power shell command fails at its own example.

### ISSUE THREAD

**Issue by jukkamaljanen** [Azure/azure-cli#12334]
Simply put: `az --% webapp create --runtime "aspnet|V4.7"` fails. The `--%` makes no difference if it's there or not. The problem is in the pipe thats within "aspnet|V4.7". That value is taken from whitelist of values, which all have pipes. 

How can you not parse pipe correctly when it's quoted?

## Describe the bug

**Command Name**
`az webapp create`

**Errors:**
```
Runtime 'aspnet' is not supported. Please invoke 'list-runtimes' to cross check
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create -g {} -p {} -n {} --runtime {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6

azure-cli 2.1.0

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
Is there a reason you are using PowerShell to run these commands instead of bash or windows command prompt?

**Comment by jukkamaljanen** [comment]
1) Uploading files. Getting a publish profile, using it to authenticate and pushing things to the webapp without too many third party apps.
2) Should the PS be able to execute the syntax that its own help files print? This is a bug, people!

**Comment by panchagnula** [comment]
Are you saying this is a bug in Powershell and not the command. You can use a non PowerShell command (Ex. CommandPrompt in Windows , Terminal in Mac) and the current syntax will work.  We might change the runtime syntax to not use | in the future, which will not be a problem for Powershell.
