### ISSUE TITLE
az sql db restore command used to work and now comes back with ERROR

### ISSUE THREAD

**Issue by amthomas46** [Azure/azure-cli#12338]
The error is 

ERROR: Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://management.
azure.com/subscriptions/&lt;sub_id&gt;/resourceGroups/azuresqlworkshop0221/providers/Microsoft.Sq
l/servers/aw-server0221/databases/AdventureWorks0221-copy?api-version=2017-10-01-preview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bdd674-b454-e863-c943-9c979b466a92
* Version Independent ID: b15341f9-3f1b-00e0-a1c2-970f25a6ab03
* Content: [az sql db](https://docs.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by dalshamaa** [comment]
Followed up offline with @amthomas46 The requests were failing because the specified point in time is not valid.

**Comment by azureSQLGitHub** [comment]
Btw how do I mark this as closed?

**Comment by amthomas46** [comment]
Thanks Deema - I can close it..
