### ISSUE TITLE
az resource create --location 'canadacentral' fails.

### ISSUE THREAD

**Issue by happyiphone** [Azure/azure-cli#12339]
### **This is autogenerated. Please review and update as needed.**

While running 

`az resource create --location 'canadacentral' --name 'Unique-Resource-Namebgw-g' --properties '{}' --resource-group 'UniqueResourceGroupName' --resource-type 'Microsoft.ClassicCompute/domainNames'` 

I get the following error:

`Unable to create domain name 'Unique-Resource-Namebgw-g': 'The location constraint is not valid'.`

Funny thing is that the creation of the Resource Group worked just fine:

```
az group create --location 'canadacentral' --name 'UniqueResourceGroupName'
>>
{
  "id": "/subscriptions/2b662f63-8485-47ac-aa45-92ba0b0e5b79/resourceGroups/UniqueResourceGroupName",
  "location": "canadacentral",
  "managedBy": null,
  "name": "UniqueResourceGroupName",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": "Microsoft.Resources/resourceGroups"
}

```
**Command Name**
`az resource create`

**Errors:**
```
Unable to create domain name 'Unique-Resource-Namebgw-g': 'The location constraint is not valid'.
```

## To Reproduce:
Just by running the command above will trigger the error. Not sure what is going on but it works just fine for other regions like `az resource create --location 'westus' --name 'Unique-Resource-Namebgw-g' --properties '{}' --resource-group 'UniqueResourceGroupName' --resource-type 'Microsoft.ClassicCompute/domainNames'`

- _Put any pre-requisite steps here..._
- `az resource create --location {} --name {} --properties {} --resource-group {} --resource-type {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6

azure-cli 2.1.0

Extensions:
interactive 0.4.3

```

**Comment by qwordy** [comment]
Thanks for your feedback

**Comment by happyiphone** [comment]
Thank you for the rapid response! Anything that I can do as work around in the meantime?

**Comment by yonzhan** [comment]
add to S167.

**Comment by zhoxing-ms** [comment]
@happyiphone Hi, I cannot reproduce this issue. Do you still have this problem?  If so, please give me some of your log information:
1. You can view the Activity log of the Resource Group on the portal after the resource creation fails. After clicking the failed operation name, there is a JSON information corresponding to the failure reason, then tell me what is the error message and correlationId of the failure?
2. If there is no obvious clue in step 1, Could you add --debug to the original command? And then please show me the information returned by debug.

**Comment by happyiphone** [comment]
It has been fixed in one of the latest releases (S166 I think). Thanks for checking!
