### ISSUE TITLE
Certain passwords don't allow you to log-in

### ISSUE THREAD

**Issue by SimonTheLeg** [Azure/azure-cli#12332]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
az login: error: argument --password/-p: expected one argument
```

## To Reproduce:
- Create a SPP with the following password `-_-PZ4I11Aw&ao*!=%<adjB@Y<%_iFDKAMiRudu!m15mca=Z4A##EUm`
- Try to log-in `az login --service-principal -u <id> -p '-_-PZ4I11Aw&ao*!=%<adjB@Y<%_iFDKAMiRudu!m15mca=Z4A##EUm' --tenant <tenant>`

## Expected Behavior
Login succeeds

## Environment Summary
```
Darwin-19.2.0-x86_64-i386-64bit
Python 3.7.5
Shell: zsh (also tried with bash)

azure-cli 2.0.77 *

```

**Comment by yonzhan** [comment]
add to S167.

**Comment by qianwens** [comment]
@SimonTheLeg , this is a known issue in python that the leading character '-' will confusing the argument parser to make it as an option name. https://github.com/Azure/azure-cli/issues/7054 . You can fix this issue by adding '=' between the option name and value : `az login --username=$azureUserName --password=$azurePassword`

**Comment by SimonTheLeg** [comment]
ah okay. Well that explains why it was such a weird error :D 
But yeah with the workaround not too much of a problem. :) Maybe it would be good idea to add a small message stating this to the cli's output?

**Comment by qianwens** [comment]
Thanks for the advice. The help message is added in sprint 167.
