### ISSUE TITLE
Python error when trying to add an email action to an azure metrics alert

### ISSUE THREAD

**Issue by pjgeutjens** [Azure/azure-cli#12342]
## Describe the bug

**Command Name**
`az monitor metrics alert update`

**Errors:**
```
dictionary update sequence element #0 has length 1; 2 is required
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 554, in execute
    parsed_args = self.parser.parse_args(args)
python3.6/site-packages/knack/parser.py, ln 259, in parse_args
    return super(CLICommandParser, self).parse_args(args)
...
az/lib/python3.6/argparse.py, ln 1836, in take_action
    action(self, namespace, argument_values, option_string)
cli/command_modules/monitor/actions.py, ln 129, in __call__
    webhook_properties=dict(x.split('=', 1) for x in values[1:]) if len(values) > 1 else None
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor metrics alert update -g {resourceGroupName} --name {alertRuleName} --add-action email {emailAddress}`

## Expected Behavior
Add an action to an alert rule sending out an email when triggered

## Environment Summary
```
Linux-4.15.0-1071-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.1.0

Extensions:
interactive 0.4.3

```

**Comment by jiasli** [comment]
@MyronFanQiu Please help with this issue.

**Comment by MyronFanQiu** [comment]
@pjgeutjens Hi. The usage should be like this `--add-action ACTION_GROUP_NAME_OR_ID [KEY=VAL [KEY=VAL ...]]`. Please try something like `--add-action name email=xxx@xxx.com`

**Comment by pjgeutjens** [comment]
`--add-action name email=xxx@xxx.com ` does not work, what does work is --add-action <name of existing action group>, so without the _email_ parameter.

That fixed my issue, thanks!
