### ISSUE TITLE
az sql -h Missing module psycopg2 on MacOS

### ISSUE THREAD

**Issue by mortgagemetrix** [Azure/azure-cli#12340]
### **This is autogenerated. Please review and update as needed.**
When trying to access help for az sql, I get the error listed below. Other components of the az cli don't have issues with help.
## Describe the bug

**Command Name**
`az sql`

**Errors:**
```
No module named 'psycopg2._psycopg'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 554, in execute
    parsed_args = self.parser.parse_args(args)
python3.8/site-packages/knack/parser.py, ln 259, in parse_args
    return super(CLICommandParser, self).parse_args(args)
3.8/lib/python3.8/argparse.py, ln 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
...
cliextensions/db-up/azext_db_up/custom.py, ln 15, in <module>
    import psycopg2
cliextensions/db-up/psycopg2/__init__.py, ln 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ModuleNotFoundError: No module named 'psycopg2._psycopg'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sql -h`

## Expected Behavior
Help context menus should appear.
## Environment Summary
```
macOS-10.15.3-x86_64-i386-64bit
Python 3.8.1

azure-cli 2.1.0

Extensions:
db-up 0.1.13

```

**Comment by jaredmoo** [comment]
This error is in `cliextensions/db-up` which is not owned by SQL DB team. Tagging CLI core team to help triage.

**Comment by yonzhan** [comment]
add to S170

**Comment by Juliehzl** [comment]
dupe with #12854. Add @fengzhou-msft  for awareness.

**Comment by Juliehzl** [comment]
It is fixed in latest db-up. Please upgrade your version with `az extension update -n db-up`.
