### ISSUE TITLE
[Breadth Coverage] Onboard DataMigration

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#12345]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Azure CLI breadth coverage on DataMigration

**Spec**
https://microsoft.sharepoint.com/:w:/t/AzureManagementExperience/EZicF2azrCFHkvFN-UIf6DcBueAdMAktOCou0JObA5sYmg?e=prUu7a

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by yungezz** [comment]
Breadth coverage for DataMigration, start from release S167.

**Comment by fengzhou-msft** [comment]
DataMigration already covered with `az dms`.
