### ISSUE TITLE
az acr create includes help text for az ad sp that's no longer accurate

### ISSUE THREAD

**Issue by SteveLasker** [Azure/azure-cli#1235]
az acr create... completes with help text that references secret, which has changed to password
```
az ad sp create-for-rbac --scopes /subscriptions/[SUBSCRITION_ID]/resourcegroups/bikesharing-acr/providers/Microsoft.ContainerRegistry/registries/bikesharing --role Owner --secret [somepassword]
```

**Comment by djyou** [comment]
This has been fixed https://github.com/Azure/azure-cli/pull/1211/commits/5629c879bfe0e6cbc2731836b30d3c41733c6efa
Please close.
