### ISSUE TITLE
az container exec - unwanted characters inserted at shell prompt

### ISSUE THREAD

**Issue by dmoore44** [Azure/azure-cli#12351]
## Describe the bug
After executing a command on an azure container image, I cannot navigate the shell as normal. At the prompt, hitting the up arrow will cycle through history, but as soon as I press the left arrow to move the cursor to modify a command, I cycle to the previous command in history.

Additionally, when attempting to use a text editor within the container, navigating through the file with the arrow keys results in random inserts of the characters "A", "B", "C", or "D". This behavior happens regardless of editor used - I've tried vi, vim, and nano.

**Command Name**
`az container exec`

**Errors:**
No error codes printed, just unexpected behavior.

## To Reproduce:
- `az container exec -g {} --name {} --container-name {} --exec-command "/bin/bash"`

## Expected Behavior
I expect bash to behave as it would normally - either in a container on my local machine, or as run on a bare metal or virtualized OS.

## Environment Summary
```
macOS-10.14.1-x86_64-i386-64bit
Python 3.8.1
Shell: bash

azure-cli 2.0.81 *

```

**Comment by navba-MSFT** [comment]
@dmoore44 Apologies for the late reply. I wasn't able to reproduce this issue from the shell prompt. The arrow key and the editor did work fine. This issue is open for quite sometime. Could you please let me know if you need any further assistance on this ? Awaiting your reply.
