### ISSUE TITLE
How to delete an index

### ISSUE THREAD

**Issue by 0papen0** [Azure/azure-cli#12356]
Is there any way to delete an index of a Search service?

Apart from deleting the index directly via REST API, is it possible to delete it through this CLI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74208fd-b066-412d-ac3f-ffe3c62941d0
* Version Independent ID: 7b3c9510-9579-c510-c468-1e9ec872dde3
* Content: [az search](https://docs.microsoft.com/en-us/cli/azure/search?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/search/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/search/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
search.

**Comment by mrcarter8** [comment]
Just noticed this issue didn't receive a response.  Sorry for the delay.  Azure CLI for Azure Cognitive Search supports operations on the management plane, such as creating a new service, scaling a service up or down, or managing API keys.  Index operations, such as create or delete index, are on the data API plane, which does not currently have any Azure CLI or Powershell support.

We do appreciate the feedback and will consider this for a future release.

Thanks,
Mike Carter 
Azure Cognitive Search PM

**Comment by brjohnstmsft** [comment]
@0papen0 Closing this issue since an answer was provided. Please re-open if you need clarification.
