### ISSUE TITLE
az aks update ranges not clarified.

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/azure-cli#12358]
Customers doesnt have guidelines in regards to number of ports, number of nodes, number of IPs, the formula to calculate the right sizing is not published or advised here.

please clarify .

error received: Operation failed with status 'bad request' . Load balancer rofile allocated ports is not in an allowable range given the number of nodes and IPS provisioned.

How to calculate the right amount of ports? what is a good range based on the ips and nodes I have?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by porrascarlos802018** [comment]
"You can assign up to 64000 ports

if you have 10 nodes as backend for example, the ports can be allocated is “64000/10(nodes) =6400”

So depend of backend node, you should divide it on 64000/(# of nodes)
"

**Comment by yungezz** [comment]
Thanks for reporting, we'll have a look.

**Comment by TomGeske** [comment]
adding @jluk

**Comment by palma21** [comment]
https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#configure-outbound-ports-and-idle-timeout

https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#plan-ip-addressing-for-your-cluster

64k ports _per_ frontend IP, this is LB specific not AKS specific

**Comment by Jen7714** [comment]
Closing this since Jorge answered in the above response.
