### ISSUE TITLE
az appservice plan create --is-linux parameter should accept boolean values

### ISSUE THREAD

**Issue by jorritsandbrink** [Azure/azure-cli#12360]
I noticed there are some differences between the `az appservice plan create` and `az functionapp plan create` commands. 

For example: for the appservice variant the --is-linux parameter behaves like a flag (i.e. if you include it it's true, otherwise it's false), whereas for the functionapp variant this parameter requires a boolean value (i.e. true or false).

In my opinion, the commands for the appservice plan and function plan should be the same. I prefer the way it's done for the functionapp plan, because it allows you to control the parameter value by the setting of a variable, instead of having to change the CLI command itself. 

On a broader note: do we need both variants at all? In the end they represent the same functionally of creating an App Service Plan.

**Comment by yungezz** [comment]
thanks for reporting the issue, we'll have a look

**Comment by panchagnula** [comment]
Thanks for the feedback - for now this is by design & we will consider this when we re-create / rewrite support for webapp ASP create
