### ISSUE TITLE
Modification of application security groups of a NIC

### ISSUE THREAD

**Issue by knutsole** [Azure/azure-cli#12368]
It would be nice if the 'az network nic update' command had a '--application-security-group' or '--application-security-groups' switch since determining which ASGs a NIC will be associated with can apparently only be done at the time of creation currently

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29b6bb22-cb91-c7f8-995e-134d0fe5627f
* Version Independent ID: a92f24e8-36a0-808b-a9e7-598f85560b0f
* Content: [az network nic](https://docs.microsoft.com/en-us/cli/azure/network/nic?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S167.

**Comment by gaoruifeng** [comment]
there is already `az network nic ipconfig update` to update the application security groups
https://docs.microsoft.com/en-us/cli/azure/network/nic/ip-config?view=azure-cli-latest#az-network-nic-ip-config-update

**Comment by gaoruifeng** [comment]
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/custom.py#L3049
This code shows when creating NIC, an ip-config is created and ASG is associated to ip-config

According to doc https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-network-interface-addresses#secondary
>In addition to a primary IP configuration, a network interface may have zero or more secondary IP configurations assigned to it.

So to update ASG of a NIC, instead of updating NIC, we need to update its ip-configs

**Comment by MyronFanQiu** [comment]
@knutsole Hi. @gaoruifeng  is correct. Application-security-groups is not associated to nic directly. An ip-config is created when you run `az network nic create`. So please use `az network nic ip-config update` to update application security groups.

**Comment by knutsole** [comment]
I now understand and agree that asg modification is done by the ip-config associated with the nic instead of the nic itself. It does not help that the first (and originally only) asg allowed to be associated with a nic is done so via the auto-creation of the intermediate ip-config of the nic, which is not intuitive. (I'm not sure I'd want to be forced to create a nic in one command, which auto-creates the ip-config, and then associate the asg(s) I'd want associated with that autocreated in-config of the nic in a second command, but it would definitely make the process more understandable.) Thank you to @gaoruifeng and @MyronFanQiu for taking the time to comment and clarify.

**Comment by MyronFanQiu** [comment]
close this issue since it's been solved.
