### ISSUE TITLE
broken: az network application-gateway waf-policy managed-rule rule-set add 

### ISSUE THREAD

**Issue by PaulCharlton** [Azure/azure-cli#12387]
**Describe the bug**

broken: az network application-gateway waf-policy managed-rule rule-set add --resource-group {rg} --policy-name {policy}  --type OWASP --version 3.1  --group-name y --rules x

and ...
az network application-gateway waf-policy managed-rule rule-set add --resource-group {rg} --policy-name {policy}  --type OWASP --version 3.1 

both of the above forms of the command should work.  The AZ CLI mistakenly *requires* the "group-name" and "rules" arguments.   The PowerShell equivalent does not require those two parameters.  In the ARM template, those parameters are allowed to be null.

**To Reproduce**
use: az version
This command is in preview. It may be changed/removed in a future release.
{
  "azure-cli": "2.1.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.1.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "interactive": "0.4.3"
  }
}

**Expected behavior**
should behave the same as the Powershell equivalent.

**Additional context**
Without correct operation, there is no means with the AZ CLI to change the global policy default from "OWASP 3.0" to "OWASP 3.1" other than a raw ARM template.

**Comment by yonzhan** [comment]
add to S167.

**Comment by jsntcy** [comment]
It seems the fix is that we should make the "group-name" and "rules" arguments as optional.
