### ISSUE TITLE
az webapp create update_site_config() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by itsforbrijesh** [Azure/azure-cli#12388]
## Describe the bug
update_site_config() takes 2 positional arguments but 3 were given 

Also tried with 2.1.0 Edge build 

**Command Name**
`az webapp create`

**Errors:**
```
update_site_config() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 657, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/core/commands/__init__.py, ln 306, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 493, in default_command_handler
    return op(**command_args)
cli/command_modules/appservice/custom.py, ln 135, in create_webapp
    match['setter'](cmd, match, site_config)
TypeError: update_site_config() takes 2 positional arguments but 3 were given
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create -n {} -g {} -p {} --tags {} {} {} {} --runtime {}`

## Environment Summary
```
Linux-4.4.0-17134-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5

azure-cli 2.1.0

```

**Comment by yungezz** [comment]
thanks for reporting the issue, we'll have a look.

**Comment by panchagnula** [comment]
Fixed with this version https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#appservice please upgrade & re-try. Thanks!
