### ISSUE TITLE
In-line Comments in parameter file cause deployment failure

### ISSUE THREAD

**Issue by arnoldna** [Azure/azure-cli#12389]
When running a resource deployment with a parameters file, in-line comments causes a deployment error. 

![arm_parameter_comment_error](https://user-images.githubusercontent.com/10898493/75569526-81b11a00-5a12-11ea-846b-0d22dfc8dd7f.png)

**AZ Version**
azure-cli                         2.0.81 *

**To Reproduce**
Add an inline comment to an parameters file. Run "az group deployment create -g <resource-group> --parameters <name of parameters file> --template-file <Name of Template file>

**Expected behavior**
In-line comments in parameters files are treated the same as comments in deployment templates

**Comment by yungezz** [comment]
HI @Juliehzl could you pls help to have a look? thanks.

**Comment by yonzhan** [comment]
add to S167.

**Comment by zhoxing-ms** [comment]
@arnoldna We don't support this function yet. Could you please tell me what scenario do you need to add comments in the parameter file?

**Comment by yonzhan** [comment]
@arnoldna any update?
