### ISSUE TITLE
DiskRP 2019-11-01 CLI Change

### ISSUE THREAD

**Issue by laurawu19** [Azure/azure-cli#12380]
**Resource Provider**
Microsoft.Azure.Management.Compute (specifically DiskRP)
**Description of Feature or Work Requested**
We made it possible for users to create disks from shared image gallery versions with a new field called GalleryImageReference in a Disk's CreationData.
We also exposed some fields for shared disks. Here is the powershell design doc if this helps: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/502
**Minimum API Version Required**
2019-11-01
**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/8195
https://github.com/Azure/azure-rest-api-specs/commit/0fbc1f6f932eac621aab4f232c536edb8250764a
**Target Date**
Next CLI release

**Comment by yungezz** [comment]
put it in S167 for now.

**Comment by qwordy** [comment]
```
(env) PS C:\yfy\azure-cli> az disk create -g fytest2 -n d1 --size-gb 10 --max-shares 3
This subscription is not registered to use Microsoft.Compute/SharedDisksForPremium feature.
(env) PS C:\yfy\azure-cli> az feature register --namespace Microsoft.Compute --name SharedDisksForPremium
Once the feature 'SharedDisksForPremium' is registered, invoking 'az provider register -n Microsoft.Compute' is required to get the change propagated
The feature 'SharedDisksForPremium' does not support registration.
```
Can you help? Sent you subscription ID in teams.

**Comment by qwordy** [comment]
Azure CLI 2.3.0 is released. It contains the features described in this issue. Close now. You can still comment here if any problem or feedback.
