### ISSUE TITLE
functionapp: version 1 missing in --runtime-version

### ISSUE THREAD

**Issue by pramodhegde88** [Azure/azure-cli#12384]
We'are running most of our function apps in .net framework (v1). This is because we have the dependency on BrokeredMessage class which is supported only in V1.
Since the --runtime-version is missing V1, we're unable to create the new function apps using the Powershell or Azure-CLI. What's the alternative approach to create the new V1 apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f254bb-7dfd-417b-b08d-f2ac34247d99
* Version Independent ID: 9d22f523-579b-ea66-04ed-20f09c72bcbb
* Content: [az functionapp](https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/appservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/_help.py)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
thanks for reporting, we'll look at it

**Comment by RakeshMohanMSFT** [comment]
Supported version are mentioned here.
https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=azure-cli%2Cwindows%2Cin-process%2Cv4&pivots=programming-language-csharp
