### ISSUE TITLE
SDN create IP Config for NIC problem

### ISSUE THREAD

**Issue by malopMSFT** [Azure/azure-cli#1238]
When using the following command 
  **az network nic ip-config create** 

With required fields by documentation
az network nic ip-config create -g "IMDS_Demo" --nic-name "MyNICPortal" -n "MyIpConfig"
Subnet reference is required for ipconfiguration /subscriptions/23a27f7b-7bd9-4ef6-91f5-9bf25ea00d6a/resourceGroups/IMDS_Demo/providers/Microsoft.Network/networkInterfaces/MyNICPortal/ipConfigurations/MyIpConfig.

Unable to work around this, tested on CLI and worked fine.

**Comment by tjprescott** [comment]
cc/ @yugangw-msft. Also, the error message I'm getting is: 
`Subscription 0000 is not registered for feature Microsoft.Network/AllowMultipleIpConfigurationsPerNic required to carry out the requested operation.`

**Comment by tjprescott** [comment]
@malopMSFT can you show the output of this command with Xplat CLI showing the creation of the second IP configuration without subnet? I can easily make subnet required, but neither Xplat nor Powershell do this.

**Comment by malopMSFT** [comment]
Here is the same operation from CLI >

PS C:\> azure network nic ip-config create -g "IMDS_Demo" --nic-name "MyNICPortal" -n "MyIpConfig2"
info:    Executing command network nic ip-config create
+ Looking up the network interface "MyNICPortal"
+ Updating network interface "MyNICPortal"
data:    Id                              : /subscriptions/23a27f7b-7bd9-4ef6-91f5-9bf25ea00d6a/resourceGroups/IMDS_Demo/providers/Microsoft.Network/networkInterfaces/MyNICPortal
data:    Name                            : MyNICPortal
data:    Type                            : Microsoft.Network/networkInterfaces
data:    Location                        : eastus
data:    Provisioning state              : Succeeded
data:    Internal domain name suffix     : 5hwkucijcxfudhihfhmuraxfdg.bx.internal.cloudapp.net
data:    Enable IP forwarding            : false
data:    IP configurations:
data:      Name                          : ipconfig1
data:      Primary                       : true
data:      Provisioning state            : Succeeded
data:      Private IP address            : 10.3.0.4
data:      Private IP version            : IPv4
data:      Private IP allocation method  : Dynamic
data:      Subnet                        : /subscriptions/23a27f7b-7bd9-4ef6-91f5-9bf25ea00d6a/resourceGroups/DemoRG/providers/Microsoft.Network/virtualNetworks/myVNET2/subnets/subnet1
data:
data:      Name                          : MyIpConfig2
data:      Primary                       : false
data:      Provisioning state            : Succeeded
data:      Private IP address            : 10.3.0.5
data:      Private IP version            : IPv4
data:      Private IP allocation method  : Dynamic
data:      Subnet                        : /subscriptions/23a27f7b-7bd9-4ef6-91f5-9bf25ea00d6a/resourceGroups/DemoRG/providers/Microsoft.Network/virtualNetworks/myVNET2/subnets/subnet1
data:
info:    network nic ip-config create command OK

**Comment by tjprescott** [comment]
Moving to Sprint 7 as the permission our subscription requires to test this is still listed as "Pending". Working with the ARM team to resolve.
