### ISSUE TITLE
unrecognized arguments: --load-balancer-outbound-ips in az aks create

### ISSUE THREAD

**Issue by zbigniev** [Azure/azure-cli#12397]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
While trying to create aks cluster using `az aks create` and argument `--load-balancer-outbound-ips '<ip>'`, I get _unrecognized arguments : --load-balancer-outbound-ips_

**To Reproduce**
Run `az aks create --resource-group <resource_group> --name <name> --load-balancer-outbound-ips <ip1>` from cli.

**Expected behavior**
Cluster creation is initiated.

**Environment summary**
Install method: brew
Shell Type: zsh
OS: macOS Catalina (10.15.3)

➜ az --version
azure-cli                          2.1.0

command-modules-nspkg              2.0.3
core                               2.1.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
aks-preview                        0.4.5

**Additional context**

**Comment by zbigniev** [comment]
Installed `azure-cli 2.1.0`on an ubuntu-19.10 and `--load-balancer-outbound-ips` shows up with `az aks create -h`. 

But not on macOS

**Comment by jluk** [comment]
I'm seeing it on my versions, can you please update your aks-preview version to latest 0.4.33?

**Comment by zbigniev** [comment]
@jluk Updating preview to 0.4.33 indeed helped. Thanks.

However, this is interesting. Without aks-preview the option showed on v2.1.0, but with older version of extension aks-preview v0.4.5 it remained hidden and required update of aks-preview for it to work.

**Comment by jluk** [comment]
The Azure CLI uses an interesting preview model, in that if you have the preview installed it will override the core version build and ignore it. Thus it seems 0.4.5 didn't have the changes needed, but the preview v0.4.33 does and core build v2.1.0 does as well. Hope this helps!
