### ISSUE TITLE
OpenSuSe Tumbleweed 'cannot import name 'BlockBlobService' from 'azure.storage.blob'

### ISSUE THREAD

**Issue by Zaita** [Azure/azure-cli#12399]
## Describe the bug
I'm using today's release of OpenSuSe Tumbleweed
run 
$ az
Command not found
$ zypper install az
$ az login
Login successful
$ az webapp list
Errors out here....

**Command Name**
`az webapp list`

**Errors:**
```
cannot import name 'BlockBlobService' from 'azure.storage.blob' (/usr/lib/python3.7/site-packages/azure/storage/blob/__init__.py)
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
<frozen importlib._bootstrap_external>, ln 728, in exec_module
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
cli/command_modules/appservice/custom.py, ln 39, in <module>
    from azure.storage.blob import BlockBlobService, BlobPermissions
ImportError: cannot import name 'BlockBlobService' from 'azure.storage.blob' (/usr/lib/python3.7/site-packages/azure/storage/blob/__init__.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp list`

## Environment Summary
```
Linux-5.5.6-1-default-x86_64-with-glibc2.2.5
Python 3.7.3

azure-cli 2.1.0

```

**Comment by Zaita** [comment]
List of packages installed
[azure_packagelist.txt](https://github.com/Azure/azure-cli/files/4272814/azure_packagelist.txt)

**Comment by yonzhan** [comment]
@fengzhou-msft  please take a look.

**Comment by Zaita** [comment]
[azure_cli_error.txt](https://github.com/Azure/azure-cli/files/4273043/azure_cli_error.txt)
Uploading another related file, might help find root cause.

**Comment by fengzhou-msft** [comment]
@Zaita Your install method is different from our [doc](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper?view=azure-cli-latest). The package is named `azure-cli`. Can you give us more information about your OpenSuSe Tumbleweed system? Is it a VM on Azure? Did you add any package repos for it?

It seems OpenSuSe Tumbleweed does not provide python3.6. We have some [workaround](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper?view=azure-cli-latest#install-on-sles-12-or-other-systems-without-python-36) for it. From your azure_packagelist.txt, you have installed both python2 and python3 SDKs. You may want to clean up python 2 packages as latest version only works with python 3 now.

**Comment by Zaita** [comment]
@fengzhou-msft 
I've removed all of the Python2 that I can. Unfortunately some packages in SuSe still rely on it. I've tried the instructions listed in your doc, but these also fail.

Following the top install method in your doc fails with: 
[install_fail.txt](https://github.com/Azure/azure-cli/files/4277371/install_fail.txt)

Following the "Install on SLES 12 or other systems without Python 3.6" instructions fails with:
[wget_fail.txt](https://github.com/Azure/azure-cli/files/4277374/wget_fail.txt)

My OpenSuSe Tumbleweed system is bare-metal:
(Note. I have multiple bare-metal systems running Tumbleweed, problem is the same on all)
```bash
Osiris:~ # cat /proc/cpuinfo | grep "model name" | head -1
model name      : AMD A10-6790K APU with Radeon(tm) HD Graphics
Osiris:~ # cat /etc/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20200228"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20200228"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20200228"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
LOGO="distributor-logo"
```

**Comment by Zaita** [comment]
Adding to comment above. I downloaded the latest RPM from the URL where the wget failed and installed it: [working_rpm_download_fail.txt](https://github.com/Azure/azure-cli/files/4278625/working_rpm_download_fail.txt)

This still fails though.

**Comment by Zaita** [comment]
```bash
Osiris:~/tmp # az
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/__init__.py", line 1, in <module>
    ï»¿__import__('pkg_resources').declare_namespace(__name__)
  File "/usr/lib64/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 26, in <module>
    import zipfile
  File "/usr/local/lib/python3.6/zipfile.py", line 14, in <module>
    import struct
  File "/usr/local/lib/python3.6/struct.py", line 13, in <module>
    from _struct import *
ModuleNotFoundError: No module named '_struct'
Osiris:~/tmp # python -V
Python 3.6.9
Osiris:~/tmp # python
Python 3.6.9 (default, Mar  3 2020, 13:36:41)
[GCC 9.2.1 20200128 [revision 83f65674e78d97d27537361de1a9d74067ff228d]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from _struct import *
>>>
[8]+  Stopped                 python
Osiris:~/tmp # echo $PYTHONPATH
/usr/local/lib64/python3.6/lib-dynload
Osiris:~/tmp # ls -la /usr/local/lib64/python3.6/lib-dynload/ | grep "struct"
-rwxr-xr-x 1 root root  187616 Mar  3 13:30 _struct.cpython-36m-x86_64-linux-gnu.so
Osiris:~/tmp #
```

**Comment by bluca** [comment]
@fengzhou-msft the problem is that the BlockBlobService is in the old, deprecated https://github.com/Azure/azure-storage-python/tree/master/azure-storage-blob/azure/storage/blob but not in the new https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob/azure/storage/blob

Azure-cli seems to be using APIs from both incompatible versions at the same time. The situation around azure-storage is extremely confusing.

**Comment by fengzhou-msft** [comment]
@bluca I think we only used `azure-mgmt-storage` from the new `azure-sdk-for-python`. We are still using the old `azure-storage-blob` which is pinned in [setup.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/setup.py#L128) and [requirements](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/requirements.py3.Linux.txt#L85) file. We do have plans to upgrade to the new one after adoption of track2 SDKs.

@Zaita can you check the version of `azure-storage-blob` you installed? As @bluca pointed us in the right direction, you might have installed a wrong version of `azure-storage-blob`.

**Comment by bluca** [comment]
@fengzhou-msft do you have an ETA for the switch? We already transitioned in Debian Unstable

**Comment by fengzhou-msft** [comment]
> @fengzhou-msft Feng Zhou FTE do you have an ETA for the switch? We already transitioned in Debian Unstable

@Juliehzl is working on this and can give an ETA.

**Comment by Juliehzl** [comment]
@bluca For the latest `azure-storage-blob` we will support it in next sprint. I will let you know when supported. 
Current plan for the feature is 4/30 if no additional issues.

**Comment by bluca** [comment]
Thank you!

**Comment by bluca** [comment]
@Juliehzl hi - any update on the update to the latest azure-storage-blob?

**Comment by Juliehzl** [comment]
Hi @bluca , to prevent the issue, I am working on remove the dependency for azure.storage.blob  and use azure.multiapi.storage to keep compatible.
PR  is #13412

**Comment by bluca** [comment]
Great, thank you!

**Comment by fengzhou-msft** [comment]
The dependency of `azure.storage.blob` will be removed in https://github.com/Azure/azure-cli/pull/13490
