### ISSUE TITLE
Argument --capture-interval does not update the "intervalInSeconds"

### ISSUE THREAD

**Issue by bartjanson** [Azure/azure-cli#12406]
Initially a capture on a eventhub is created with the "intervalInSeconds" with 300, if we want to change this using the azure portal the value is correctly changed, if we change this value with az eventhubs eventhub update --capture-interval &lt;value between 60 and 300&gt; the value is not updated, only if we use --set captureDescription.intervalInSeconds=60.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa949ea-86b1-125e-e7d3-f0f88a2661ab
* Version Independent ID: c8351dbc-7358-ba5b-6757-3929a4a2b42b
* Content: [az eventhubs eventhub](https://docs.microsoft.com/en-us/cli/azure/eventhubs/eventhub?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/eventhubs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/eventhubs/_help.py)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
eventhubs

**Comment by v-Ajnava** [comment]
Hi @bartjanson,  thanks for details, I will investigate the issue and will submit a PR with fix.

**Comment by bartjanson** [comment]
Ajit,

just ask if there is something I can help you with.


Met vriendelijke groet,

Bart Janson
Processfive

E: b.janson@processfive.com <bart.janson@processfive.com>
I: www.processfive.com
M: 06 414 33 55 9
Vrijdagen altijd afwezig

**Comment by samuelkoppes** [comment]
We are confirming that this issue has been addressed, and will report back with an update by 11/4/2020.

**Comment by Saglodha** [comment]
Hi @bartjanson, I had tried to update the property using --capture-interval and could successfully update the value. Can you please confirm if you have been facing issues with the latest module?

**Comment by bartjanson** [comment]
@Saglodha tested using azure-cli version 2.32.0, works.
