### ISSUE TITLE
--kind has wrong default value according to documentation

### ISSUE THREAD

**Issue by chbe8475** [Azure/azure-cli#12402]
The --kind parameter has a default of 'Storage'.
Documentation says 'StorageV2'

Please change one or the other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92115d19-d7a0-93a8-bf2b-5126d1cddcd0
* Version Independent ID: a657f09b-e1ac-12a2-4b9c-7aaa1f0e3f5c
* Content: [az storage account](https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az-storage-account-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S167.

**Comment by Juliehzl** [comment]
Hi @chbe8475, thanks for your feedbac;=k.
CLI  has completed the change.  In latest profile, we are using StorageV2 for storage kind now in the latest CLI.
But if you are using CLI in Azure Stack with profile 2019-03-01-hybrid profile, the default kind will be Storage.
