### ISSUE TITLE
Please do not recommend to run a bash script from a $random URL with sudo

### ISSUE THREAD

**Issue by zobelhelas** [Azure/azure-cli#1241]
currently you suggest (as first point on Readme.rst) to run the following command:

` $ curl -L https://aka.ms/InstallAzureCli | sudo bash`

At this point you recommend to the users to run a random script with administrative privileges without even verifying if the script is actually yours. From a security point of view this is a very bad idea. At least you could verify a signature before you let the user run this script.

First idea: do not list this method as first item in your Readme.rst, but maybe pip instead.

**Comment by derekbekoe** [comment]
@zobelhelas thanks for your feedback.
The team have discussed this and we have work items for this.
I have created https://github.com/Azure/azure-cli/issues/1242 to track this.

**Comment by mayurid** [comment]
As mentioned this is tracked as #1242 and will be addressed in upcoming week. I am closing this but please feel free to reopen if u disagree
