### ISSUE TITLE
az ad sp create-for-rbac --name new-service-principal-name --skip-assignment --years ???

### ISSUE THREAD

**Issue by jbmitchell** [Azure/azure-cli#12412]
Is there a way to set the client secret to never expire from the command line? It seems when creating a new secret from the portal there is an option for never that just sets it to expire on 12/31/2299? A thousand years seems to work fine but 10,000 throws an error. What is the max time for "--years" parameter?

az ad sp create-for-rbac --name new-service-principal-name --skip-assignment --years 1000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S167

**Comment by jbmitchell** [comment]
It looks like the max value for years is (9999-current_year), or currently `7979`.

```bash
az ad sp create-for-rbac --name new-service-principal-name --skip-assignment --years 7979
```

**Comment by jiasli** [comment]
Azure CLI uses Python's built-in function `relativedelta` to compute the `app_end_date`. 

https://github.com/Azure/azure-cli/blob/1c0e9c3e18c34116d5a2e25cb7460d1af8a85969/src/azure-cli/azure/cli/command_modules/role/custom.py#L1301

[datetime.py](https://github.com/python/cpython/blob/ce305d641074931e4e790f7a83e28f74910644e5/Lib/datetime.py#L19) defines 
```py
MAXYEAR = 9999
```

So yes. The max value for `--year` is `9999-current_year`, or currently `7979`. The developer of Python may think Python 3.8.2 won't be used until the year of 9999. 😄
