### ISSUE TITLE
az webapp config access-restriction add is not idempotent

### ISSUE THREAD

**Issue by mcalnd70** [Azure/azure-cli#12415]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Running the same command multiple times re-adds the same entry again. The command is not idempotent and shouldn't add duplicate entries.

<img width="805" alt="Capture" src="https://user-images.githubusercontent.com/56595934/75709011-d0341200-5cb9-11ea-8512-5db8ac2c45e8.PNG">

**To Reproduce**
Run the following against any App Service...

**az webapp config access-restriction add --resource-group RG-TestResourceGroup --name WA-MyTestAppService --description MyRule1 --rule-name MyRule1 --action Allow --ip-address 5.6.7.8/32 --priority 101**

Re-run the same command a few times, a duplicate entry is made against the App Service's Access Restrictions list. 

This is impossible to achieve in the Azure Portal GUI as it recognises the IP address range already exists.

<img width="221" alt="Capture2" src="https://user-images.githubusercontent.com/56595934/75709013-d0cca880-5cb9-11ea-9e44-860731edff97.PNG">

**Expected behavior**
First run, add's the rule. 2nd and subsequent runs, detects the rule is already configure correctly and passes/reports already exists, but doesn't fail

**Environment summary**
Azure CLI - current version / Cloud shell version

**Additional context**
Running **az webapp config access-restriction show** command after displays the duplicates....

    {
      "action": "Allow",
      "additional_properties": {},
      "description": "MyRule1",
      "ip_address": "5.6.7.8/32",
      "name": "MyRule1",
      "priority": 101,
      "subnet_mask": null,
      "subnet_traffic_tag": null,
      "tag": "Default",
      "vnet_subnet_resource_id": null,
      "vnet_traffic_tag": null
    },
    {
      "action": "Allow",
      "additional_properties": {},
      "description": "MyRule1",
      "ip_address": "5.6.7.8/32",
      "name": "MyRule1",
      "priority": 101,
      "subnet_mask": null,
      "subnet_traffic_tag": null,
      "tag": "Default",
      "vnet_subnet_resource_id": null,
      "vnet_traffic_tag": null
    },
    {
      "action": "Allow",
      "additional_properties": {},
      "description": "MyRule1",
      "ip_address": "5.6.7.8/32",
      "name": "MyRule1",
      "priority": 101,
      "subnet_mask": null,
      "subnet_traffic_tag": null,
      "tag": "Default",
      "vnet_subnet_resource_id": null,
      "vnet_traffic_tag": null
    }

**Comment by yonzhan** [comment]
webapp

**Comment by mcalnd70** [comment]
For anyone else struggling with this, the Powershell Az module now has the ability to do this, and it is idempotent. 

You may need to update your installation of the Powershell Az module
https://github.com/Azure/azure-powershell/releases/tag/v3.5.0-February2020

e.g. 

**Add-AzWebAppAccessRestrictionRule -ResourceGroupName RG-TestResourceGroup -WebAppName WA-MyTestAppService -Name "MyRule1" -Priority 201 -Action Allow -IpAddress 5.6.7.8/32**

There doesn't appear a way unfortuantlye to tick the box to say the same restrictions at the SCM site level, so you might need to do a duplicate rule to the above with the -TargetScmSite switch...e.g.

Add-AzWebAppAccessRestrictionRule **-TargetScmSite** -ResourceGroupName RG-TestResourceGroup -WebAppName WA-MyTestAppService -Name "MyRule1" -Priority 201 -Action Allow -IpAddress 5.6.7.8/32

**Comment by panchagnula** [comment]
Once API updates to make this idempotent CLI will support it.

**Comment by ludovicbonivert** [comment]
@mcalnd70 tested your snippet and I have still duplicated ip addresses while I use same name and priority

**Comment by mcalnd70** [comment]
@ludovicbonivert which snippet? The Azure CLI one or the PowershellAz one?

**Comment by ludovicbonivert** [comment]
> For anyone else struggling with this, the Powershell Az module now has the ability to do this, and it is idempotent.
> 
> You may need to update your installation of the Powershell Az module
> https://github.com/Azure/azure-powershell/releases/tag/v3.5.0-February2020
> 
> e.g.
> 
> **Add-AzWebAppAccessRestrictionRule -ResourceGroupName RG-TestResourceGroup -WebAppName WA-MyTestAppService -Name "MyRule1" -Priority 201 -Action Allow -IpAddress 5.6.7.8/32**
> 
> There doesn't appear a way unfortunately to tick the box to say the same restrictions at the SCM site level, so you might need to do a duplicate rule to the above with the **-TargetScmSite** switch...e.g.
> 
> Add-AzWebAppAccessRestrictionRule **-TargetScmSite** -ResourceGroupName RG-TestResourceGroup -WebAppName WA-MyTestAppService -Name "MyRule1" -Priority 201 -Action Allow -IpAddress 5.6.7.8/32

I tested this in a Azure DevOps pipeline
My code looks like this

```
- task: AzurePowerShell@4
      displayName: network configuration
      inputs:
        azureSubscription: $(serviceConnection)
        azurePowerShellVersion: LatestVersion
        ScriptType: InlineScript
        inline: |

          $counter=0
          $ips=$("ip1", "ip2")
          
          ForEach($ip in $ips) {
            Add-AzWebAppAccessRestrictionRule -ResourceGroupName $(resourceGroupName) -WebAppName "functionName" -Name "microsoftip$counter" -Priority $counter -Action Allow -IpAddress $ip/32
            $counter=$counter+1;
          }
```

**Comment by gabriel-kohen-by** [comment]
Hi @panchagnula , I still see this. issue in this CLI version:
azure-cli                         2.0.80 *

command-modules-nspkg              2.0.3
core                              2.0.80 *
nspkg                              3.0.4
telemetry                          1.0.4 *
Is there an API issue you can point to that will resolve this issue when fixed?
Thanks

**Comment by jcmrva** [comment]
This is an issue for us because we're using lots of rules, some with multiple IPs & ranges. When those need to be updated, we have to delete the matching rule then re-add it. I'd prefer to reduce the complexity and runtime of that script.

PowerShell isn't an option due to internal policy.

**Comment by gabbsmo** [comment]
@panchagnula Where can we track the required API changes to make this idempotent?
