### ISSUE TITLE
"az keyvault create \     --resource-group learn-33b14343-8e20-4365-a4c2-afac1f90aaaa \     --location centralus \     --name <your-unique-vault-name>" ERROR

### ISSUE THREAD

**Issue by jaipaldom** [Azure/azure-cli#12423]
## Describe the bug

**Command Name**
`az keyvault create`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault create --resource-group {} --location {} --name {}`

## Environment Summary
```
Linux-4.15.0-1071-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.1.0

```

**Comment by justSteve** [comment]
Getting same -- reported to https://github.com/Azure/azure-cli/issues/9345

**Comment by qwordy** [comment]
We'll investigate it

**Comment by bim-msft** [comment]
Thanks @justSteve for the super useful information.
Hi @jaipaldom , as @justSteve just said that you would get this error when your vault name was too long, I'm not sure whether this is the exact same scenario as yours, but it worth a try! Thanks.

**Comment by bim-msft** [comment]
Hi @jaipaldom are you still being blocked by this issue? You may try the above workaround.
