### ISSUE TITLE
webapp: Import App Service Certificate

### ISSUE THREAD

**Issue by bertrandpons** [Azure/azure-cli#12427]
Hello,

Let's assume I created an App Service Certificate with the Azure dedicated service, is it possible to import it in the private key certificates of an App Service with CLI, instead of using the Azure Portal?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3f984d-0d48-e075-7e2f-2da5667b15cf
* Version Independent ID: 98e06d47-0ed4-4d8e-ccf5-d3a78e510539
* Content: [az webapp config ssl](https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest#az-webapp-config-ssl-import)
* Content Source: [latest/docs-ref-autogen/webapp/config/ssl.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/ssl.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
Not at this time - only support we have at this point is to import a cert from AKV https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest#az-webapp-config-ssl-import

**Comment by bertrandpons** [comment]
@panchagnula ok thank you too bad. Do you know if it is planned ?

**Comment by panchagnula** [comment]
Don't have an ETA at this point since portal has been the way to achieve this.

**Comment by panchagnula** [comment]
No ETA to share however you use the following blog to use an ARM template for deployment https://dotnetdevlife.wordpress.com/2020/02/18/purchase-app-service-certificate/

**Comment by navba-MSFT** [comment]
@bertrandpons Apologies for the late reply. Could you please refer [this](https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest#az-webapp-config-ssl-import) article and let us know if you need any further information on this ? Awaiting your reply.

**Comment by panchagnula** [comment]
no immediate plans currently for this using ARM template is the suggested approach.

**Comment by navba-MSFT** [comment]
@panchagnula Thanks for your reply.
@bertrandpons As a workaround, please follow the action plan mentioned in [this](https://github.com/Azure/azure-cli/issues/12427#issuecomment-635143335) comment and let us know if that helps. Awaiting your reply.

**Comment by bertrandpons** [comment]
@navba-MSFT thank you for your follow-up. You can close the issue.
