### ISSUE TITLE
az functionapp should not set `WEBSITE_NODE_DEFAULT_VERSION` for all Linux apps

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-cli#12429]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az function app should not set WEBSITE_NODE_DEFAULT_VERSION for Linux function apps
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L2438

**To Reproduce**
Create a Linux function app. Notice that the app setting `WEBSITE_NODE_DEFAULT_VERSION` is being set, but should not be the case. 

**Expected behavior**
The app setting `WEBSITE_NODE_DEFAULT_VERSION` should not be set.

**Comment by Francisco-Gamino** [comment]
cc: @gzuber @pragnagopa @ankitkumarr

**Comment by yonzhan** [comment]
functionapp.

**Comment by kamperiadis** [comment]
Closing as this is no longer relevant.
