### ISSUE TITLE
Syntax fix in doc

### ISSUE THREAD

**Issue by tameek** [Azure/azure-cli#12424]
Please change:

az vm deallocate --ids {vms_ids}
az vm generalize --ids {vms_ids}

to

az vm deallocate --ids ${vms_ids}
az vm generalize --ids ${vms_ids}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@qwordy please take a look.

**Comment by qwordy** [comment]
Thank you for the feedback. I know ${} is a valid bash syntax. But {} has appeared many times in _help.py. And it is also easy to understand. Users should replace {vms_ids} with real VM IDs when using this command. I think we can keep the current style.
