### ISSUE TITLE
[Breadth Coverage] Onboard StorageCache Commands

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#12434]
**Spec Link**
https://microsoft.sharepoint.com/:w:/t/AzureManagementExperience/EcJFauYB7JdHovw2P13_9_0B3hM6cI7G7Mk174gZFB4wiQ?e=KH8s1j

**ADO Work Item Link**
https://dev.azure.com/azure-mgmt-ex/Onboarding/_workitems/edit/194

**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.StorageCache

**Description of Feature or Work Requested**
Support Azure CLI commands for StorageCache

**Minimum API Version Required**
Microsoft.Storage 2019-11-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2019-11-01 

**Python SDK Link**
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-mgmt-storagecache

**Target Date**
03/31/2020

**Addtional context**
We'll use [autorest.az](https://github.com/Azure/autorest.az/blob/master/doc/01-authoring-azure-cli-commands-v1.md) from code gen team to auto-generate the code first and may need update some code manually if the generated code doesn't meet your requirements.

**Comment by yonzhan** [comment]
add to S167.
