### ISSUE TITLE
Upload-Batch with Write-Policy SAS Token Fails

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-cli#12433]
Command:

```
az storage blob upload-batch --destination "<target container name>" `
  --source "C:/scrap/packages" `
  --account-name <account-name> `
  --sas-token "<SAS Token>"
```

Which results in 

```
The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:b59e24c7-001e-0021-60b6-f16975000000
Time:2020-03-03T23:51:11.9831383Z</Message></Error>
'si' is not recognized as an internal or external command,
operable program or batch file.
'sr' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.
```

I am including the full SAS token. The SAS token takes the form

`?sv=2018-03-28&si=SAS-Write&sr=c&sig=<signature here>`

If I remove everything except the signature, the `si is not recognized...` error doesn't occur, but I still see the `resource does not exist` error.

I have successfully tried swapping to `--connection-string` instead of `--sas-token` and uploading. It works just fine. I'm super suspicious that there is a encoding issue that I'm not aware of.

This is the SAS policy definition for the SAS token that I am using.

![image](https://user-images.githubusercontent.com/45376673/75831226-cec12300-5d67-11ea-926b-1af834ed657c.png)

I have tried a fresh reinstall + restart of my powershell. No dice.

![image](https://user-images.githubusercontent.com/45376673/75831072-67a36e80-5d67-11ea-9674-8719961d40fe.png)

I am totally willing to accept that I'm doing something wrong with SAS tokens here. Could really use some assistance if it's indeed something I'm inflicting on myself.

**Comment by scbedd** [comment]
I did try URL decoding the SAS token just in case it was related to that. Tried both full token as well as just the signature.

**Comment by yonzhan** [comment]
add to S167

**Comment by scbedd** [comment]
@yonzhan what does the `add to S167` mean? By this I mean what is the significance of adding it to that milestone?

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/milestones

**Comment by qianwens** [comment]
@scbedd , This error is due to Powershell interpreting & as a new command. You can fix this issue by wrapping "<SAS Token>" with quotes like this : --sas-token '"<SAS Token>"'
