### ISSUE TITLE
az executable is not found

### ISSUE THREAD

**Issue by vveider** [Azure/azure-cli#12446]
**Describe the bug**
After installation on Windows 10 attempt to run from CMD exits with
```
az
'az' is not recognized as an internal or external command,
operable program or batch file.
```

Installed from https://aka.ms/installazurecliwindows
Rebooted after install

**Comment by yungezz** [comment]
HI @fengzhou-msft  could you pls have a look? thanks

**Comment by fengzhou-msft** [comment]
@vveider can you check if you have az installed in C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2? The installation should add the directory to path if no error occured.

**Comment by vveider** [comment]
I see `az` installed under `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin`.

PATH was not modified during installation, had to manually add path to binaries (see screenshot).
<img width="527" alt="Screenshot 2020-03-05 at 09 59 03" src="https://user-images.githubusercontent.com/2734985/75956027-1959b100-5ec8-11ea-8f9a-551da8b9f829.png">

**Comment by vveider** [comment]
UP!

**Comment by fengzhou-msft** [comment]
@vveider The source code to add the path is [here](https://github.com/Azure/azure-cli/blob/dev/build_scripts/windows/Product.wxs#L92). 

I removed the cli directory from my Path, unintalled azure-cli and then reinstall, the path is added back for me. Do you have any security software/settings that may prevent the msi to change the Path?

**Comment by vveider** [comment]
No, I have not. However — I use public unactivated image of Windows 10, can that be a problem?

**Comment by fengzhou-msft** [comment]
This is my path.
![image](https://user-images.githubusercontent.com/55177366/76320505-c181d680-631b-11ea-9cbb-350c477a54a5.png)

**Comment by vveider** [comment]
Ok, I guess without solid reproducer I have no chance to prove that sometimes PATH is not being modified. You can close issue then.
