### ISSUE TITLE
Command when creating identity for Terraform

### ISSUE THREAD

**Issue by nicotruc** [Azure/azure-cli#12445]
## Describe the bug
Tried to launch az ad sp create-for-rbac command to register a cliend id/secret for Terraform, but command failed

**Command Name**
`az ad sp create-for-rbac`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad sp create-for-rbac --role={} --scopes={}`

## Environment Summary
```
Linux-4.15.0-1071-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.1.0
azure-cli-iot-ext 0.8.9

Extensions:
azure-cli-iot-ext 0.8.9

```

**Comment by yungezz** [comment]
HI @arrownj  could you pls have a look? thanks

**Comment by arrownj** [comment]
Hi @nicotruc , this is a known issue of Cloud Shell. We have an issue to trace it in #11749 . For workaround, you can run `az login` and rerun the command. Close this first, we will keep tracking this problem in #11749 .
