### ISSUE TITLE
Unable to add multiple custom-routes

### ISSUE THREAD

**Issue by aaronyeung** [Azure/azure-cli#12449]
## Describe the bug
azure-cli does not support multiple custom-routes (but works with the Set-AzVirtualNetworkGateway PS cmdlet)

**Command Name**
`az network vnet-gateway update`

**Errors:**
```
The Custom routes specified for gateway /subscriptions/{...}/ has an invalid IP or CIDR notation.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network vnet-gateway update --resource-group {} --name {} --subscription {} --custom-routes {}`

I have put in a space separated list of CIDR prefixes, as indicated in the documentation.
Eg.  10.1.0.0/16 10.2.0.0/16 10.3.0.0/16

For reference, I also tried using the PS module's space + comma separated format, which did not work, and returned the same error message.

To that end, I was able to successfully add multiple custom routes using the PS Set-AzVirtualNetworkGateway cmdlet.

## Expected Behavior
All custom routes added

## Environment Summary
```
macOS-10.15.3-x86_64-i386-64bit
Python 3.8.1

azure-cli 2.1.0

```

**Comment by yungezz** [comment]
HI @MyronFanQiu could you pls have a look? thanks

**Comment by yonzhan** [comment]
add to S167.

**Comment by MyronFanQiu** [comment]
@jsntcy Hi. Could you please take a look?

**Comment by jsntcy** [comment]
@aaronyeung, Could you please provide more details for your command (better to attach the whole command)?
I cannot reproduce this issue with the following command `az network vnet-gateway update -g my-rg -n my-vnet-gw --sku VpnGw1 --custom-routes 101.168.0.6/32 102.168.0.6/32`

**Comment by jsntcy** [comment]
@aaronyeung , any update on this issue?

**Comment by aaronyeung** [comment]
Hey @jsntcy sorry it's been a while.

The whole command I used was in the original issue (minus the specific custom routes, and the names of my resources)

> `az network vnet-gateway update --resource-group {} --name {} --subscription {} --custom-routes {}`
> 
> I have put in a space separated list of CIDR prefixes, as indicated in the documentation.
> Eg. 10.1.0.0/16 10.2.0.0/16 10.3.0.0/16

I think the specific custom routes I used were very close to those above, plus several 172.16.x.x/22 networks too.

Going off memory here, it would have been something like the following:
`az network vnet-gateway update --resource-group my-rg --name my-vnetgw --subscription my-subscription-uuid --custom-routes 10.1.0.0/16 10.2.0.0/16 10.3.0.0/16 172.16.1.0/22 172.16.4.0/22`

When I ran the command it seemed like it worked, but when I checked the details it didn't update.
At the time I ended up using the PS module to do it and it worked to update the custom routes, and the updated routes showed up in both the PS module, plus azure-cli.

**Comment by jsntcy** [comment]
@aaronyeung, I ran the following commands,
`az network vnet-gateway create -g azure-cli-test-rg --vnet my-vnet -n my-vnet-gw --public-ip-addresses my-pub-ip`
`az network vnet-gateway update -g azure-cli-test-rg --vnet my-vnet -n my-vnet-gw --custom-routes 10.1.0.0/16 10.2.0.0/16 10.3.0.0/16`
`az network vnet-gateway show -g azure-cli-test-rg -n my-vnet-gw`

and the custom routes did update correctly. Could you provide more details for me to reproduce? (for example, command series you used)

`{
  "activeActive": false,
  "bgpSettings": {
    "asn": 65515,
    "bgpPeeringAddress": "10.0.0.254",
    "bgpPeeringAddresses": [
      {
        "customBgpIpAddresses": [],
        "defaultBgpIpAddresses": [
          "10.0.0.254"
        ],
        "ipconfigurationId": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/azure-cli-test-rg/providers/Microsoft.Network/virtualNetworkGateways/my-vnet-gw/ipConfigurations/vnetGatewayConfig0",
        "tunnelIpAddresses": [
          "104.42.27.128"
        ]
      }
    ],
    "peerWeight": 0
  },
  "customRoutes": {
    "addressPrefixes": [
      "10.1.0.0/16",
      "10.2.0.0/16",
      "10.3.0.0/16"
    ]
  },
  "enableBgp": false,
  "enableDnsForwarding": null,
  "enablePrivateIpAddress": false,
  "etag": "W/\"f4b13248-a90f-4d85-b3ae-bc573e0009fe\"",
  "gatewayDefaultSite": null,
  "gatewayType": "Vpn",
  "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/azure-cli-test-rg/providers/Microsoft.Network/virtualNetworkGateways/my-vnet-gw",
  "inboundDnsForwardingEndpoint": null,
  "ipConfigurations": [
    {
      "etag": "W/\"f4b13248-a90f-4d85-b3ae-bc573e0009fe\"",
      "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/azure-cli-test-rg/providers/Microsoft.Network/virtualNetworkGateways/my-vnet-gw/ipConfigurations/vnetGatewayConfig0",
      "name": "vnetGatewayConfig0",
      "privateIpAddress": null,
      "privateIpAllocationMethod": "Dynamic",
      "provisioningState": "Succeeded",
      "publicIpAddress": {
        "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/azure-cli-test-rg/providers/Microsoft.Network/publicIPAddresses/my-pub-ip",
        "resourceGroup": "azure-cli-test-rg"
      },
      "resourceGroup": "azure-cli-test-rg",
      "subnet": {
        "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/azure-cli-test-rg/providers/Microsoft.Network/virtualNetworks/my-vnet/subnets/GatewaySubnet",
        "resourceGroup": "azure-cli-test-rg"
      },
      "type": "Microsoft.Network/virtualNetworkGateways/ipConfigurations"
    }
  ],
  "location": "westus",
  "name": "my-vnet-gw",
  "provisioningState": "Succeeded",
  "resourceGroup": "azure-cli-test-rg",
  "resourceGuid": "8d03b1fc-2d71-473b-a511-54f458173fa6",
  "sku": {
    "capacity": 2,
    "name": "Basic",
    "tier": "Basic"
  },
  "tags": null,
  "type": "Microsoft.Network/virtualNetworkGateways",
  "vpnClientConfiguration": null,
  "vpnGatewayGeneration": "Generation1",
  "vpnType": "RouteBased"
}`

**Comment by jsntcy** [comment]
Close as no response from customer. @aaronyeung  If you still have the issue, you can reopen it.
