### ISSUE TITLE
can create snapshot and image to another subs

### ISSUE THREAD

**Issue by vrondan1983** [Azure/azure-cli#12444]
## Describe the bug

**Command Name**
`az snapshot create`

**Errors:**
```
The client has permission to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' on scope '/subscriptions/f18b457e-c07b-45ff-b7c8-6da277fd033d/resourceGroups/image-copy-rg/providers/Microsoft.Compute/snapshots/BCIDSRLWLGC3002-image-v1-2_os_disk_snapshot-eastus2', however the linked subscription 'BCIRG3CRTSUB' was not found.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az snapshot create --resource-group {} --name {} --location {} --source {} --source-storage-account-id {} --output {} --subscription {} --tags {}`

## Environment Summary
```
Darwin-19.3.0-x86_64-i386-64bit
Python 3.7.5
Shell: bash

azure-cli 2.0.76

Extensions:
managementpartner 0.1.2
aks-preview 0.4.24
image-copy-extension 0.2.3

```

**Comment by yungezz** [comment]
HI @qwordy  could you pls have a look? thanks

**Comment by qwordy** [comment]
Hi, how do you create the snapshot? Can you share the complete command? Are you using multiple subscriptions? Can you check existence of subscription "BCIRG3CRTSUB"?

**Comment by qwordy** [comment]
Any update?

**Comment by qwordy** [comment]
Any update?

**Comment by qwordy** [comment]
Close the issue.
