### ISSUE TITLE
[az vm create] "ssh-dest-key-path" does not work properly

### ISSUE THREAD

**Issue by kenzoohba** [Azure/azure-cli#12459]
az version is 3.4.0

**Describe the bug**
"--ssh-dest-key-path" for "az vm create" work only with "/home/azureuser/.ssh/authorized_keys"
the option should be work with specific path as user's intended

**To Reproduce**
az vm create --resource-group myResourceGroup --name myVM --image UbuntuLTS --admin-username azureuser --generate-ssh-keys --ssh-dest-key-path './'

**Expected behavior**
create keys on current directory

**Current result**
Deployment is failed with the message below.

Destination path for SSH public keys is currently limited to its default value /home/[username]/.ssh/authorized_keys due to a known issue in Linux provisioning agent.

**Comment by yonzhan** [comment]
@qwordy please take a look.

**Comment by juyama** [comment]
It seems that '--ssh-dest-key-path' property is not implemented. I found it in test code (e.g. test_vm_** file) only...

**Comment by qwordy** [comment]
I tried your command, but I got an error of "The value of parameter linuxConfiguration.ssh.publicKeys.path is invalid"
'--ssh-dest-key-path' is not a valid identifier in code. It is implemented in Azure CLI. According to your error message, it's not supported now.
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_template_builder.py#L788

**Comment by juyama** [comment]
if '--ssh-dest-key-path' is not supported now, please update following document.
https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create 
_--ssh-dest-key-path
Destination file path on the VM for the SSH key. If the file already exists, the specified key(s) are appended to the file._

**Comment by qwordy** [comment]
Agree. Add to milestone S168.

**Comment by qwordy** [comment]
I get a same error as you if I set `--ssh-dest-key-path "/home/fey/.ssh/authorized_keysaa"`
```
"error": {
    "code": "InvalidParameter",
    "message": "Destination path for SSH public keys is currently limited to its default value /home/fey/.ssh/authorized_keys  due to a known issue in Linux provisioning agent.",
    "target": "linuxConfiguration.ssh.publicKeys.path"
  }
```

**Comment by qwordy** [comment]
Create an issue for WALinuxAgent.
https://github.com/Azure/WALinuxAgent/issues/1852

**Comment by qwordy** [comment]
The updated help message is now available in Azure CLI 2.4.0. I will watch the issue that I create in WALinuxAgent.

**Comment by LarrySmith-1437** [comment]
Note that as of today, for azure-cli 2.9.1, the error message is still as unhelpful as it ever was:
Deployment failed. Correlation ID: xxxxxxxxxxxxxxxxxxxxxxxxx. {
  "error": {
    "code": "InvalidParameter",
    "message": "The value of parameter linuxConfiguration.ssh.publicKeys.path is invalid.",
    "target": "linuxConfiguration.ssh.publicKeys.path"
  }
}

**Comment by qwordy** [comment]
> 
> 
> Note that as of today, for azure-cli 2.9.1, the error message is still as unhelpful as it ever was:
> Deployment failed. Correlation ID: xxxxxxxxxxxxxxxxxxxxxxxxx. {
> "error": {
> "code": "InvalidParameter",
> "message": "The value of parameter linuxConfiguration.ssh.publicKeys.path is invalid.",
> "target": "linuxConfiguration.ssh.publicKeys.path"
> }
> }

@LarrySmith-1437 My result is Destination path for SSH public keys is currently limited to its default value /home/[username]/.ssh/authorized_keys due to a known issue in Linux provisioning agent.
How did you create the VM?
