### ISSUE TITLE
Feature suggestion - get rid of the dot after devicelogin 

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#1245]
The login prompt shows something along the lines of:

```
	To sign in, use a web browser to open the 
	page https://aka.ms/devicelogin. Enter the code xxxxxxxx to authenticate.
```

If you're in the habit of double clicking and copying a url from a terminal, this will often get:

`https://aka.ms/devicelogin.`

Suggestion is to either: 
  * Drop the dot / add a space / something to get it away from 'devicelogin'
or
  * Get the website to accept a . after 'devicelogin'

**Comment by nneul** [comment]
https://github.com/Azure/azure-xplat-cli/issues/3301

**Comment by nneul** [comment]
Even a rephrase would work:

```To sign in, use a web browser to open the 	page https://aka.ms/devicelogin and enter the code xxxxxxxx to authenticate.```

**Comment by mayurid** [comment]
@yugangw-msft: Is this us or the AD SDK that returns the message? We can plan accordingly
@nneul : Thanks for input.

**Comment by yugangw-msft** [comment]
It is from AAD server, ADAL just surface it.
Suggest do not analyze it unless we have more user voices. The work-around is to bookmark it in browser.
Note, this message is localized, so far cli uses `enu` version, if we open up the localization, the sniff might get more complicated.

**Comment by yugangw-msft** [comment]
In conversation with AAD team to improve the message, will post more updates here

**Comment by nneul** [comment]
I agree with @yugangw-msft should not be fixed in this app/sdk - better to address upstream. Hopefully request from devs on this project carries a bit more weight than request from general public.

**Comment by derekbekoe** [comment]
Looks like the dot has gone?

On Public Azure, I see:
```
$ az login
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code XXXXXXXX to authenticate.
```

**Comment by yugangw-msft** [comment]
Yep. Closing
