### ISSUE TITLE
az aks create: No registered resource provider found for location 'eastus' and API version '2015-11-01-preview' for type 'applicationGateways'.

### ISSUE THREAD

**Issue by crgarcia12** [Azure/azure-cli#12456]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 

**Describe the bug**
No registered resource provider found for location 'eastus' and API version '2015-11-01-preview' for type 'applicationGateways'. The supported api-versions are '2014-12-01-preview, 2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-06-01, 2016-07-01, 2016-08-01, 2016-09-01, 2016-10-01, 2016-11-01, 2016-12-01, 2017-03-01, 2017-04-01, 2017-06-01, 2017-08-01, 2017-09-01, 2017-10-01, 2017-11-01, 2018-01-01, 2018-02-01, 2018-03-01, 2018-04-01, 2018-05-01, 2018-06-01, 2018-07-01, 2018-08-01, 2018-10-01, 2018-11-01, 2018-12-01, 2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth, australiaeast, australiasoutheast, centralindia, southindia, westindia, canadacentral, canadaeast, westcentralus, westus2, ukwest, uksouth, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth, switzerlandnorth, germanywestcentral, norwayeast'.

**To Reproduce**
    az aks create -g $ResourceGroup `
        --name $ClusterName `
        -k $AksVersion `
        --location $Location `
        --node-count 2 `
        --generate-ssh-keys `
        --enable-addons monitoring `
        --workspace-resource-id $WorkSpaceIdUrl `
        --network-plugin azure `
        --network-policy azure `
        --service-cidr 10.41.0.0/16 `
        --dns-service-ip 10.41.0.10 `
        --docker-bridge-address 172.17.0.1/16 `
        --vnet-subnet-id $SubnetId `
        --service-principal $ServicePrincipal.appId `
        --client-secret $ServicePrincipal.password `
        --no-wait

**Expected behavior**
A cluster to be created

**Environment summary**
**Install Method:** apt-get

**CLI version** (`az --version`) /
azure-cli                          2.1.0
command-modules-nspkg              2.0.3
core                               2.1.0
nspkg                              3.0.4
telemetry                          1.0.4
Extensions:
azure-firewall                     0.3.0
Python location '/opt/az/bin/python3'
Extensions directory '/home/carlos/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Feb 14 2020, 05:22:53) 
[GCC 7.4.0]

**OS version** #32~~18.04.1-Ubuntu
**Shell Type**  bash or PowerShell 
**PowerShell Version**
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Additional context**
It used to work, the only think that i can remember that changed was updating some powershell modules (AZ)
**Get-Module Az**: Script     3.5.0      Az

If I do **az network application-gateway list --debug** it works, and I get this
...
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/930c11b0-5e6d-458f-b9e3-f3dda0734110/providers/Microsoft.Network/applicationGateways?**api-version=2019-11-01**
...

**Comment by yonzhan** [comment]
aks

**Comment by crgarcia12** [comment]
I found the issue. It is my mistake

I was getting $WorkSpaceIdUrl from `az group deployment ..... --query ....` and the query sometimes brings the app gateway uri (depending on how the deployment happened). Since this was in a pipeline I could not really see that value

I am not sure if you want to close the issue as "user has no clue what it is doing :)" or if you can improve the error message in case you have more users that have no clue what they are doing :)

It is ok to close this.
