### ISSUE TITLE
[Breadth Coverage] Onboard CustomProviders Commands

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#12452]
**Spec Link**
https://microsoft.sharepoint.com/:w:/t/AzureManagementExperience/Eea4hlXnO9pEjdvll9fxJ8ABfwn3NXpSo3Eo21KQYy3qIQ?e=9EcrDd

**ADO Work Item Link**
https://dev.azure.com/azure-mgmt-ex/Onboarding/_workitems/edit/150

**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.CustomProviders

**Description of Feature or Work Requested**
Support Azure CLI commands for CustomProviders

**Minimum API Version Required**
Microsoft.CustomProviders 2018-09-01-preview

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/customproviders/resource-manager/Microsoft.CustomProviders/preview/2018-09-01-preview/customproviders.json

**Python SDK Link**
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/customproviders/azure-mgmt-customproviders/azure/mgmt/customproviders

**Target Date**
03/31/2020

**Addtional context**
We'll use [autorest.az](https://github.com/Azure/autorest.az/blob/master/doc/01-authoring-azure-cli-commands-v1.md) from code gen team to auto-generate the code first and may need update some code manually if the generated code doesn't meet your requirements.

**Comment by yonzhan** [comment]
add to S167.
