### ISSUE TITLE
How do you disable/turn off logging?

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-cli#12451]
Is it possible? If so, how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c237378a-a708-8e2f-3c8c-0bc8b623d21c
* Version Independent ID: c4e27b67-9605-60f5-899d-8ffd727079b2
* Content: [az storage logging](https://docs.microsoft.com/en-us/cli/azure/storage/logging?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
HI @Juliehzl could you pls have a look? thanks

**Comment by brandonh-msft** [comment]
flagging `--retention 0` doesn't disable the logging, only the retention. an `az storage logging show` after doing this yields:
```json
"blob": {
    "delete": true,
    "read": true,
    "retentionPolicy": {
      "days": null,
      "enabled": false
    },
    "version": "1.0",
    "write": true
  },
```

**Comment by yonzhan** [comment]
add to S167.

**Comment by Juliehzl** [comment]
Please try `az storage logging off` after 2020/04/20 with latest azure cli.
