### ISSUE TITLE
Query for AppGW WAF rules

### ISSUE THREAD

**Issue by WSGomes11** [Azure/azure-cli#12465]
Hi, is there a way to query the .conf files from Azure WAF Rules? I'd like to validate the regular expressions. The "az network application-gateway waf-config list-rule-sets --group '*' --type OWASP --version 3.0" just list the rule names.

The RegEx showed by Log Analitycs "details_message_S" collum does not match the pattern displayed on "details_data_s"

I want to check the rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf

**Comment by yonzhan** [comment]
add to S167.

**Comment by MyronFanQiu** [comment]
@WSGomes11 Hi. Looks like we don't have command to show the details of .conf files. Based on the documentation, the concept should be general which is not created by Azure. https://docs.microsoft.com/en-gb/azure/web-application-firewall/ag/application-gateway-crs-rulegroups-rules?tabs=owasp31#crs911-31. I will add service attention label and invite them to take a look.

**Comment by MyronFanQiu** [comment]
@winthrop28 could you take a look at this issue?

**Comment by WSGomes11** [comment]
@MyronFanQiu Thank you for your answer, I was expecting that cause I explored some commands. What is happening: The pure information from Log Analytics doesn't match the pattern found, in some cases I'm using patterns from other fonts, like https://fossies.org/ and https://www.netnea.com/, curiously, some times the patterns from each font are a little bit different, even thinking both are bases on OWASP. Because of this I'd like to check the .conf file of Azure AppGW WAF to have another font to prove the pattern for customers.

**Comment by KarenHammons** [comment]
@WSGomes11 there is no short term plan for this; thank you for the feedback.  Note that we also monitor user requests through Feedback.azure.com (https://feedback.azure.com/forums/217313-networking?category_id=368350) where the user community can share their voice on ideas submitted.  We recommend submitting any feature requests there.  Thank you!
