### ISSUE TITLE
Help is wrong on vm image list --all

### ISSUE THREAD

**Issue by zobelhelas** [Azure/azure-cli#1246]
```
$ ./az vm image list -h                        

Command
    az vm image list: Vm image list.

Arguments
    --all        : Retrieve all versions of images from all publishers.
    --location -l: Location.
    --offer      : Image offer name.
    --publisher  : Image publisher name.
    --sku        : Image sku name.

```

if i do `$ ./az vm image list --all --publisher credativ` it shows me only my images instead of the one from all publishers.

You might want to change that to

`     --all        : Retrieve all versions of images from all publisher or all versions of images of a specific publishers.
`

**Comment by mayurid** [comment]
@jasonrshaver and @sauryadas as fyi
@zobelhelas : Thanks for the feedback.

**Comment by yugangw-msft** [comment]
#1813 fixed it.
