### ISSUE TITLE
Stopping Web Job doesn't work when using Run-From-Package

### ISSUE THREAD

**Issue by alohaninja** [Azure/azure-cli#12462]
Please let people know that you [cannot stop or disable webjobs when using the `WEBSITE_RUN_FROM_PACAKGE` app setting enabled](https://github.com/Azure/azure-webjobs-sdk/issues/2389) as it locks the filesystem preventing this action. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9169e28-f731-4772-6aa5-865c7f480a35
* Version Independent ID: 0decf749-52ca-1cc5-b20d-b5eed621281d
* Content: [az webapp webjob continuous](https://docs.microsoft.com/en-us/cli/azure/webapp/webjob/continuous?view=azure-cli-latest#az-webapp-webjob-continuous-stop)
* Content Source: [latest/docs-ref-autogen/webapp/webjob/continuous.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/webjob/continuous.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
this is not related to CLI please open an issue here https://github.com/projectkudu/kudu for tracking.

**Comment by panchagnula** [comment]
closing this since this is not related to azure-cli

**Comment by MDornian** [comment]
This is super frustrating as we have just spent a large number of resources developing a Webjob and now we can't stop or pause it when we need to without bringing down the whole website.   This problem is almost 5 years old so I don't expect to ever see a real solution
