### ISSUE TITLE
RPM /usr/bin/az relies on PATH for python3

### ISSUE THREAD

**Issue by mryan1539** [Azure/azure-cli#12468]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

The /usr/bin/az shell script wrapper in the RPM doesn't use a full path to the OS python.  This means, if the user has another python in their PATH, the az command may fail.  In particular, I've noticed this against an alternate build of python3 that doesn't have CFFI, where `az acr login -n REGNAME` fails with a traceback.

I note that python commands that come with CentOS/RHEL encode it as an absolute path (e.g., /usr/bin/yum).

This is known to occur in 2.0.80, 2.1.0 and dev.  I've submitted a PR with a potential fix: https://github.com/Azure/azure-cli/pull/12467

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to look at the issue? Thanks.
