### ISSUE TITLE
Adding Fairplay content-key-policy fails due to problems with 'ask' parameter

### ISSUE THREAD

**Issue by multiplexer2** [Azure/azure-cli#12469]
The command:
`az ams content-key-policy option add <various fairplay options> --ask "1234567890abcdef1234567890abcdef"`
Produces the following error:
(BadRequest) FairPlay configuration must have ASK. ASK must be 16 bytes.

It's expecting a byte array of 16 bytes as opposed to a normal hexadecimal ask string with 32 characters. This problem seems to have been fixed with the merging of [PR #10627](https://github.com/Azure/azure-cli/pull/10627), but for some strange reason the fix was reverted (by mistake?) a couple of months later when [PR #11240 ](https://github.com/Azure/azure-cli/pull/11240) was merged.

**Comment by yungezz** [comment]
thanks for reporting, we'll look at it.

**Comment by giakas** [comment]
Opened a Ticket 6426726 on our team, will be working on fixing this issue.

**Comment by hivyas** [comment]
Issue has been resolved in with this merge: https://github.com/Azure/azure-cli/pull/12610
