### ISSUE TITLE
Not able to deploy .Zip package to Azure App service

### ISSUE THREAD

**Issue by iamdevpk** [Azure/azure-cli#12460]
## Describe the bug

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
('Connection aborted.', OSError("(10054, 'WSAECONNRESET')",))
Traceback (most recent call last):
urllib3\urllib3\contrib\pyopenssl.py, ln 320, in _send_until_done
pip-install-wl9gly17\pyOpenSSL\OpenSSL\SSL.py, ln 1737, in send
pip-install-wl9gly17\pyOpenSSL\OpenSSL\SSL.py, ln 1639, in _raise_ssl_error
OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

...

pip-install-wl9gly17\requests\requests\sessions.py, ln 646, in send
pip-install-wl9gly17\requests\requests\adapters.py, ln 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')",))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip --resource-group {} --name {} --subscription {} --src {}`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.67 *

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
we are not able to repro this please upgrade to the latest version of CLI and re-try thanks!
