### ISSUE TITLE
az vm create attempts to modify vnets/subnets?

### ISSUE THREAD

**Issue by roy-work** [Azure/azure-cli#12473]
**Describe the bug**

An `az vm create` command we are attempting to run fails, because it cannot modify the address space of a peered vnet. But it should never have been trying to do that in the first place — it's supposed to be creating a *VM* — not modifying a vnet. **Why does the following `az vm create` attempt to modify an existing vnet/subnet?**

We are running a command similar to the following (some names changed due to business reasons):

```sh
az vm create \
    --name "$name" \
    --resource-group example-rg \
    --image 'Canonical:UbuntuServer:18.04-LTS:latest' \
    --size Standard_F8s_v2 \
    --os-disk-size-gb 50 \
    --admin-username ubuntu \
    --ssh-key-values "$ssh_pubkey_path" \
    --vnet example-vnet \
    --subnet example-subnet
```

In our case, both the specified vnet & subnet already exist. This fails with:

```
Deployment failed. Correlation ID: 59eb1119-e436-4b96-9081-fc28960bfeb3. {
  "error": {
    "code": "VnetAddressSpaceCannotChangeDueToPeerings",
    "message": "Address space of the virtual network /subscriptions/<subscript ID>/resourceGroups/example-rg/providers/Microsoft.Network/virtualNetworks/example-vnet cannot change when virtual network has peerings.",
    "details": []
  }
}
```

We're not requesting any changes to the vnet, so this error means `az` is doing something completely unexpected, and IMO, erroneous.

We ran it again with `--debug`; this emits most of the requests that `az` is making. The relevant bit seems to be that `az` creates a "deployment", which is how the meat of the work gets done. That request looks like this in the error case:

```
{
  "properties": {
    "template": {
      "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
      "contentVersion": "1.0.0.0",
      "parameters": {},
      "variables": {},
      "resources": [
        {
          "name": "example-vnet",
          "type": "Microsoft.Network/virtualNetworks",
          "location": "eastus2",
          "apiVersion": "2015-06-15",
          "dependsOn": [],
          "tags": {},
          "properties": {
            "addressSpace": {
              "addressPrefixes": [
                "10.0.0.0/16"
              ]
            },
            "subnets": [
              {
                "name": "example-vnet-subnet",
                "properties": {
                  "addressPrefix": "10.0.0.0/24"
                }
              }
            ]
          }
        },
        { < a resource for the NSG > },
        { < a resource for the public IP addr > },
        { < a resource for the NIC > },
        { < a resource for the VM > },
      ],
      "outputs": {}
    },
    "parameters": {},
    "mode": "Incremental"
  }
}
```

The first part of the deployment contains changes to the vnet & the subnet within it: but why? Why are we modifying the vnet?

(I've also attempted to reproduce this on a non-production setup. Unfortunately, there, I've not been successful: the VM is create successfully. Running it with `--debug` however, indicates that, for whatever reason, it is _not_ including the vnet changes, only the other resources — the NSG, IP, NIC, and VM. Likely, I do not understand how my test setup differs from my production setup in some manner, likely, the same difference is what causes `az` to add the vnet changes to the deployment.)

**To Reproduce**

We're not sure of exact reproduction steps at this time.

Our current setup consists of two vnets peered together; one vnet is `10.10.0.0/16` w/ two subnets, `10.10.0.0/18` and `10.10.64.0/28`; it is in the second subnet, `10.10.64.0/28` that we're attempting to create the VM. The other vnet is `10.100.0.0/16`.

(However, I've attempted to build a similar setup consisting of two vnets peered together in a test Azure account to reproduce the issue, but I've not had luck: the vnet is created successfully and does not attempt to modify the vnet AFAICT during the creation/deployment. So, it seems my test setup differs materially from our prod one in some manner, but I don't know what, yet.)

**Expected behavior**

Create a VM. Potentially create directly associated resources, but certainly not modifying the address space of an existing vnet when that wasn't requested.

**Environment summary**
Install Method: via `brew`
CLI version (`az --version`): (probably whatever is in `brew`.)
OS version: Mac OS X
Shell Type: `bash`, I think? (It only fails on our production cluster, which I do not have access to, so it's running under the shell of a coworker w/ the appropriate access. I don't know exactly what his shell is, but I don't think it's relevant.)

**Comment by yonzhan** [comment]
@qwordy please take a look.

**Comment by qwordy** [comment]
I did some experiments.

1. Create a vnet vnet1
2. Create a vnet vnet2
3. Add peering between vnet1 and vnet2
4. Modify address space of a subset in vnet1, success.
5. Add a subset in vnet1, success.
6. Modify address space of vnet1, error, "You can't add address ranges to or delete address ranges from a virtual network's address space once a virtual network is peered with another virtual network"

**Comment by qwordy** [comment]
Hi @roy-work , could you check if the vnet exists?

**Comment by qwordy** [comment]
@roy-work

**Comment by qwordy** [comment]
Close the issue for now. Open a new issue if there is any problem. Or you can still comment here.
