### ISSUE TITLE
az vm create: --nsg_rule's value is not used

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#12476]
`az vm create`'s `--nsg_rule` doesn't make it way to the deployment.

https://github.com/Azure/azure-cli/blob/e23571160166610197328144ea668017324ec2f7/src/azure-cli/azure/cli/command_modules/vm/custom.py#L586

Also, `--nsg_rule` should support `none` like 

```
    --nsg                          : The name to use when creating a new Network Security Group
                                     (default) or referencing an existing one. Can also reference an
                                     existing NSG by ID or specify "" for none ('""' in Azure CLI
                                     using PowerShell or --% operator).
```

so that the NSG can be created without public internet inbound rule.

**Comment by jiasli** [comment]
@qwordy please help take a look.

**Comment by qwordy** [comment]
I find nsg_rule is never used. Interesting.

**Comment by qwordy** [comment]
PR is merged. Release: 03/31/2020.
