### ISSUE TITLE
'failover' is not in the 'az storage account' command group

### ISSUE THREAD

**Issue by webyxdesign** [Azure/azure-cli#12478]
As mentioned here   https://docs.microsoft.com/en-us/azure/storage/common/storage-initiate-account-failover?tabs=azure-cli   the failover should be triggered with 

`az storage account show \ --name accountName \ --expand geoReplicationStats`

`az storage account failover \ --name accountName`

I also updated to CLI 2.1.0 - but I am getting the same result.

## Describe the bug

**Command Name**
`az storage account`

**Errors:**
```
az storage account: 'failover' is not in the 'az storage account' command group. See 'az storage account --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account {} -h`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.79 *

Extensions:
interactive 0.4.3

```

**Comment by yungezz** [comment]
HI @Juliehzl could you pls have a look? thanks

**Comment by yonzhan** [comment]
add to S167

**Comment by Juliehzl** [comment]
@webyxdesign To use `az storage account failover` command, you need to make sure `storage-preview` extension installed. 
Please run `az extension add -n storage-preview` to install the extension.
