### ISSUE TITLE
az rest does not work against dogfood

### ISSUE THREAD

**Issue by hiteshmadan** [Azure/azure-cli#12471]
## Describe the bug
I registered and used the dogfood environment (steps in the how to reproduce section below).
After this, az rest to even do a List Resource groups does not work.

**Command Name**
`az rest --method get --uri "https://api-dogfood.resources.windows-int.net/subscriptions/d48566a8-2428-4a6c-8347-9675d09fb851/resourcegroups?api-version=2019-10-01"`

**Errors:**
```
The endpoint 'active_directory_data_lake_resource_id' for this cloud is not set but is used.
/home/hitesh/.azure/clouds.config may be corrupt or invalid.
Resolve the error or delete this file and try again.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
```
az cloud register --name Dogfood --endpoint-active-directory-graph-resource-id https://graph.windows-ppe.net/ --endpoint-active-directory-resource-id https://management.core.windows.net/ --endpoint-gallery https://df.gallery.azure-test.net/ --endpoint-resource-manager https://api-dogfood.resources.windows-int.net/ --endpoint-active-directory https://login.windows-ppe.net/
az cloud set --name Dogfood
az login
```

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.72 *
azure-cli-iot-ext 0.7.1

Extensions:
azure-cli-iot-ext 0.7.1
interactive 0.4.3

```

**Comment by yungezz** [comment]
HI @zhoxing-ms could you pls have a look? thanks.

**Comment by zhoxing-ms** [comment]
@hiteshmadan The error message means that the parameter `--active-directory-data-lake-resource-id` is not set in the command `az cloud register`. May I ask if this setting is not required in your dogfood environment?

**Comment by yonzhan** [comment]
@hiteshmadan any update?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Comment by jiasli** [comment]
Tested with latest Azure CLI 2.31.0 and couldn't repro (following https://github.com/Azure/azure-cli/issues/20846#issue-1089659664):

```
$ az cloud register --name Dogfood --endpoint-active-directory-resource-id https://management.core.windows.net/ --endpoint-gallery https://df.gallery.azure-test.net/ --endpoint-resource-manager https://api-dogfood.resources.windows-int.net/ --endpoint-active-directory https://login.windows-ppe.net/ --endpoint-active-directory-graph-resource-id https://graph.ppe.windows.net/

$ az cloud set -n Dogfood

$ az login

$ az rest --method get --uri "https://api-dogfood.resources.windows-int.net/subscriptions/e4ced903-171b-4a34-a408-1b7185ea530a/resourcegroups?api-version=2019-10-01"
{
  "value": [
    {
      "id": "/subscriptions/e4ced903-171b-4a34-a408-1b7185ea530a/resourceGroups/yishitest",
      "location": "eastus",
      "name": "mytest",
      "properties": {
        "provisioningState": "Succeeded"
      },
      "tags": {},
      "type": "Microsoft.Resources/resourceGroups"
    }
  ]
}
```
