### ISSUE TITLE
az tag remove-value trims spaces

### ISSUE THREAD

**Issue by ghost** [Azure/azure-cli#12488]
**Describe the bug**
When running: `az tag remove-value --name 'TagName' --value 'TagValue' --subscription "SubscriptionName"`, if Tagvalue ends with a space, the space is trimmed.

Also note that symbols (like `%`) are double encoded.

**To Reproduce**
See above

**Expected behavior**
The space should not be trimmed.

**Environment summary**
Windows Powershell

**Additional context**
Both symbols and spaces are supported when creating tags (via the UI and ARM at least)

**Comment by yonzhan** [comment]
add to S167.

**Comment by jiasli** [comment]
What Azure Portal creates is **not** a predefined tag which can't be edited by Azure CLI. For example, I added a tag `testtag` to a resource group in Azure Portal, then run

```pwsh
> az tag add-value -n testtag --value "value2 "
Predefined tag name 'testtag' could not be found.
```

Create a predefined tag with CLI:

```pwsh
> az tag create -n pretag
{
  "count": {
    "type": "Total",
    "value": 0
  },
  "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag",
  "tagName": "pretag",
  "values": []
}
```

Then add value with space to it:

```pwsh
> az tag add-value -n pretag --value "value1 " --debug
Command arguments: ['tag', 'add-value', '-n', 'pretag', '--value', 'value1 ', '--debug']

msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/value1%20?api-version=2019-07-01'
msrest.http_logger : Request method: 'PUT'
msrest.http_logger : Request body:
msrest.http_logger : None

msrest.http_logger : Response status: 201
msrest.http_logger : Response content:
msrest.http_logger : {"id":"/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/value1","tagValue":"value1","count":{"type":"Total","value":0}}
{
  "count": {
    "type": "Total",
    "value": 0
  },
  "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/value1",
  "tagValue": "value1"
}
```

Note that the space `%20` does appear in the URL `https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/value1%20` for [Tags - Create Or Update Value](https://docs.microsoft.com/en-us/rest/api/resources/tags/createorupdatevalue) REST API, but is discarded in the response `"tagValue":"value1"`.

However, if the value is added by directly adding a `name: value` tag to a resource group, it can retain the space with `"pretag": "value2 "`:

```pwsh
> az group show -g rg1
{
  "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/rg1",
  "location": "southeastasia",
  "managedBy": null,
  "name": "rg1",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": {
    "pretag": "value2 "
  },
  "type": "Microsoft.Resources/resourceGroups"
}
```

The space is also retained when showing the tag:

```pwsh
> az tag list --query "[?tagName=='pretag']"
[
  {
    "count": {
      "type": "Total",
      "value": 1
    },
    "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag",
    "tagName": "pretag",
    "values": [
      {
        "count": {
          "type": "Total",
          "value": 0
        },
        "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/value1",
        "tagValue": "value1"
      },
      {
        "count": {
          "type": "Total",
          "value": 1
        },
        "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/value2 ",
        "tagValue": "value2 "
      }
    ]
  }
]
```

There may be some limitation or transformation on the on service API. @zhoxing-ms, I think we may need to confirm with service team whether this is by design.

**Comment by zhoxing-ms** [comment]
Hi @Grayer123,
As the comments from @jiasli:
1. The following two service API have the logic of trim the tail space of tag value (by the way, the space before tag value is not trimmed)
[Create Or Update Value](https://docs.microsoft.com/en-us/rest/api/resources/tags/createorupdatevalue)
[Delete Value](https://docs.microsoft.com/en-us/rest/api/resources/tags/deletevalue)
2. If the tag data in the resource/resource group itself is modified with a `PUT` request, the trailing spaces of tag value will not be trimmed.

Is the space handling logic of tag value in the Resource Provider ( used by `az resource tag` ) inconsistent with the handling logic of tag value in the ARM Service( used by `az tag` )? Is that how it was designed?

**Comment by Grayer123** [comment]
Hello @zhoxing-ms, I looked into our codebase and tried to add a test to put this URL:
"http://ran-wang:100/subscriptions/e14dfa7e-dee1-4fb4-9c6d-a9800e23ef2c/tagnames/pretag/tagvalues/%20%20value1%20%20?api-version=2014-04-01-preview".

And the response retains both the leading and trailing empty space:
**TagValue = "  value1  "**
There is no logic in our code to remove the trailing empty space, and it's not by design. Will have to look into the python sdk to figure out the issue.
Also tried with our new az tag create --resourceid and corresponding PowerShell cmdlet, they also maintain the trailing empty space.

**Comment by zhoxing-ms** [comment]
@Grayer123 But in fact, the same problem exists with using the command `az rest` to request the rest API directly :

```pwsh
> az rest --method put --uri "https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/%20%20value1%20%20?api-version=2019-07-01"
{
  "count": {
    "type": "Total",
    "value": 0
  },
  "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/  value1",
  "tagValue": "  value1"
}
```

It looks like it's still a Service API problem, two spaces after *value1* are trimmed. Is this because the processing logic of your deployed service( http://ran-wang:100 ) is different from that of the online service( https://management.azure.com )?

**Comment by Grayer123** [comment]
Hello @zhoxing-ms, thanks for the feedback. I took a look of **ARM kusto log** for **HttpIncomingRequests**:
``` sql
HttpIncomingRequests
| where subscriptionId == '0b1f6471-1bf0-4dda-aec3-cb9272f09590'
| where httpMethod == 'PUT' and authorizationAction == 'Microsoft.Resources/subscriptions/tagNames/tagValues/write'
| top 100 by TIMESTAMP desc 
| project TIMESTAMP,operationName, httpMethod, targetUri, apiVersion, commandName, parameterSetName
```

```
TIMESTAMP	operationName	httpMethod	targetUri	apiVersion	commandName	parameterSetName
2020-05-12 08:12:54.4412921	PUT/SUBSCRIPTIONS/TAGNAMES/TAGVALUES/	PUT	https://management.azure.com:443/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/%20%20value1?api-version=2019-07-01	2019-07-01	rest	--method --uri
2020-05-12 08:12:15.6327181	PUT/SUBSCRIPTIONS/TAGNAMES/TAGVALUES/	PUT	https://management.azure.com:443/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/%20%20value1?api-version=2014-04-01-preview	2014-04-01-preview	rest	--method --uri
2020-05-12 08:10:11.4823274	PUT/SUBSCRIPTIONS/TAGNAMES/TAGVALUES/	PUT	https://management.azure.com:443/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/value1?api-version=2014-04-01-preview	2014-04-01-preview	rest	--method --uri
2020-05-12 08:00:49.9752730	PUT/SUBSCRIPTIONS/TAGNAMES/TAGVALUES/	PUT	https://management.azure.com:443/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/value1?api-version=2019-07-01	2019-07-01	rest	--method --uri
2020-05-12 08:00:25.0529683	PUT/SUBSCRIPTIONS/TAGNAMES/TAGVALUES/	PUT	https://management.azure.com:443/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/value1?api-version=2019-07-01	2019-07-01	rest	--method --uri --debug
2020-04-29 05:57:05.4926106	PUT/SUBSCRIPTIONS/TAGNAMES/TAGVALUES/	PUT	https://management.azure.com:443/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/zhoxing-test/tagValues/value?api-version=2019-07-01	2019-07-01	tag add-value	-n --value
2020-04-29 05:53:39.9660755	PUT/SUBSCRIPTIONS/TAGNAMES/TAGVALUES/	PUT	https://management.azure.com:443/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/zhoxing-test/tagValues/%20%20value?api-version=2019-07-01	2019-07-01	tag add-value	-n --value
2020-04-29 05:52:14.6101614	PUT/SUBSCRIPTIONS/TAGNAMES/TAGVALUES/	PUT	https://management.azure.com:443/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/zhoxing-test/tagValues/value?api-version=2019-07-01	2019-07-01	tag add-value	-n --value
2020-04-29 05:50:57.3799229	PUT/SUBSCRIPTIONS/TAGNAMES/TAGVALUES/	PUT	https://management.azure.com:443/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/zhoxing-test/tagValues/value?api-version=2019-07-01	2019-07-01	tag add-value	-n --value --debug
```  
I found no matter cmd "rest" or "tag add-value	-n --value", when the request reached ARM, the trailing empty space of the targetUri had been trimmed:
https://management.azure.com:443/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/tagNames/pretag/tagValues/%20%20value1?api-version=2019-07-01

In light of this, I doubt if it's a Service API issue. Will sync with the team to see if they see similar issues.

**Comment by zhoxing-ms** [comment]
@Grayer123 OK, thanks for your help~

**Comment by Grayer123** [comment]
@zhoxing-ms This should be a Service API issue, and we can reproduce this issue in PowerShell cmdlet as well as armclient. But it should not be a direct code issue as I had a CIT to verify. We suspect it might be some IIS related issue and will investigate further.

**Comment by RakeshMohanMSFT** [comment]
@ghost This is still being worked upon and we do not have any ETA as of now. We will keep you updated of any progress made.

**Comment by neerja28** [comment]
Any update on this feature? Wrt to keys having a trailing space as well.
