### ISSUE TITLE
[Breadth Coverage] Onboard ResourceGraph Commands

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#12500]
**Spec Link**
https://microsoft.sharepoint.com/:w:/t/AzureManagementExperience/EQBmMO-KCIpLs4eiobq2j30BQvIr7UPQ2J2zq3KoVaPxuQ?e=w8hQRc

**ADO Work Item Link**
https://dev.azure.com/azure-mgmt-ex/Onboarding/_workitems/edit/185

**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.ResourceGraph

**Description of Feature or Work Requested**
Support Azure CLI commands for ResourceGraph

**Minimum API Version Required**
Microsoft.ResourceGraph 2018-09-01-preview

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resourcegraph/resource-manager/Microsoft.ResourceGraph/preview/2018-09-01-preview/graphquery.json 

**Python SDK Link**
Not ready

**Target Date**
03/31/2020

**Addtional context**
We'll use [autorest.az](https://github.com/Azure/autorest.az/blob/master/doc/01-authoring-azure-cli-commands-v1.md) from code gen team to auto-generate the code first and may need update some code manually if the generated code doesn't meet your requirements.

**Comment by yonzhan** [comment]
add to S167
