### ISSUE TITLE
Getting error in updatimg connectiion string of webapp

### ISSUE THREAD

**Issue by kirandongara** [Azure/azure-cli#12502]
## Describe the bug

**Command Name**
`az webapp config connection-string set`

**Errors:**
```
string index out of range
Traceback (most recent call last):
Temp\pip-install-i3p9pgjr\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 608, in execute
azure\cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 659, in _run_job
Local\Temp\pip-install-i3p9pgjr\six\six.py, ln 696, in reraise
azure\cli\core\commands\__init__.py, ln 636, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 490, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 981, in update_connection_strings
IndexError: string index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config connection-string set --name {} --resource-group {} --settings {} --connection-string-type {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.78 *

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@kirandongara we need more data here to figure out what must be causing this error as in what is the value of the connection-string you are trying to set.

**Comment by panchagnula** [comment]
closing due to lack of response
