### ISSUE TITLE
it is unclear how to attach multiple urlPathMaps to a single rule. 

### ISSUE THREAD

**Issue by droopy4096** [Azure/azure-cli#12506]
In Web UI option exists to add multiple urlPathMaps to a single rule, however CLI version seems to only allow for 1:1 relationship (vs 1:n)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d6ba93c-4a1c-c69d-f52a-001791e0220a
* Version Independent ID: 2dd75bbb-a92c-c8f5-354b-6d40e531190b
* Content: [az network application-gateway rule](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/rule?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S168

**Comment by MyronFanQiu** [comment]
@droopy4096 Hi. I checked the code and one application-gateway rule can only has one url-path-map. However, one url-path-map can have multiples rules inside one url-path-map by `az network application-gateway url-path-map rule create -h`. Is that what you want?

**Comment by MyronFanQiu** [comment]
@droopy4096 Do you have more question?
