### ISSUE TITLE
Azure CLI antlr4 error

### ISSUE THREAD

**Issue by Kamusta** [Azure/azure-cli#12504]
## Describe the bug

**Command Name**
`az vm list`

**Errors:**
```
No module named 'antlr4'
Traceback (most recent call last):
lib/python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
dist-packages/azure/cli/core/__init__.py, ln 300, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
azure/cli/command_modules/vm/__init__.py, ln 31, in load_arguments
    from azure.cli.command_modules.vm._params import load_arguments
azure/cli/command_modules/vm/_params.py, ln 31, in <module>
    from azure.cli.command_modules.monitor.actions import get_period_type
azure/cli/command_modules/monitor/actions.py, ln 7, in <module>
    import antlr4
ModuleNotFoundError: No module named 'antlr4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm list`

## Environment Summary
```
Linux-5.4.0-kali3-amd64-x86_64-with-debian-kali-rolling
Python 3.7.6
Shell: bash

azure-cli 2.0.81 *

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
@qwordy please take a look.

**Comment by qwordy** [comment]
I haven't seen this error before. It's a ModuleNotFoundError. How do you installed Azure CLI?

**Comment by yonzhan** [comment]
@Kamusta any update?

**Comment by Kamusta** [comment]
Hi Sorry this was installed on kali using this command "pip3 install --upgrade --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge --no-cache-dir --upgrade-strategy=eager"

**Comment by jiasli** [comment]
Looks like `anltr4` is somehow missing. Could you check whether `antlr4-python3-runtime` is installed correctly? 
```
> pip list | grep antlr

antlr4-python3-runtime    4.7.2
```
BTW, we recently moved the dependency of `antlr4-python3-runtime` from `azure-cli-core` to `azure-cli` in https://github.com/Azure/azure-cli/pull/12917, but it should't cause this problem. +@MyronFanQiu

**Comment by cure** [comment]
I have the same problem on Debian Buster.

{
  "azure-cli": "2.0.81",
  "azure-cli-core": "2.0.81",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "azure-devops": "0.17.0"
  }
}

Python 3.8.2

I installed the Azure cli from the debian packages you provide:

ii  azure-cli                             2.0.81+ds-3                          all          Azure Command-Line Interface (CLI)

> pip3 list | grep antl

returns nothing. There is a python3-antlr3 debian package available but it is not installed (and it's the wrong version of antlr).

This seems to be a missing dependency in the azure-cli packaging.

**Comment by jiasli** [comment]
Hi @cure, `2.0.81` is an old version. Could you let us know which package you installed and how? So that I can follow your steps to repro it. 

We do have the correct dependency as shown in https://github.com/Azure/azure-cli/pull/12917.

**Comment by cure** [comment]
hi @jiasli I installed azure-cli as per the instructions at

>  https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

The version I have installed is

> $ dpkg -l |grep azure-cli
> ii  azure-cli                             2.0.81+ds-3                          all          Azure Command-Line Interface (CLI)
> ii  python3-azure-cli                     2.0.81+ds-3                          all          Azure Command-Line Interface (CLI)
> ii  python3-azure-cli-core                2.0.81+ds-3                          all          Azure Command-Line Interface (CLI)
> ii  python3-azure-cli-telemetry           2.0.81+ds-3                          all          Azure Command-Line Interface (CLI)

The package came from the repository at

  deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ buster main

You are right that this is not the most recent version available (there is even a newer package available for the 2.0.81 version).

**Comment by jiasli** [comment]
I am installing Azure CLI with 

```sh
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
```

I tested on Ubuntu TLS 18.04 first:

```sh

$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ dpkg -l | grep azure-cli
ii  azure-cli                          2.4.0-1~bionic                              all          Azure CLI
```

Then on Debian Buster 

```sh
$ cat /etc/*-release
ID="azure"
VERSION="20200210-166"
AZURE_VERSION="0.20200210.166"
BUILD_INFO_URL="https://salsa.debian.org/cloud-admin-team/debian-cloud-images-daily/-/jobs/555200"
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ dpkg -l | grep azure-cli
ii  azure-cli                        2.4.0-1~buster              all          Azure CLI
```

`az vm list` works as expected on both platforms. 

The package [azure-cli (2.0.81+ds-3)](https://packages.debian.org/sid/azure-cli) is not distributed by us. Could you uninstall other packages of Azure CLI and try the official 2.4.0 version? + @fengzhou-msft to take a look.

**Comment by cure** [comment]
@jiasli I can confirm that this bug is not present on Debian Buster with the latest version 2.4.0 of the Azure CLI, installed as per https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

I tested on a fresh installation of Debian Buster. From my perspective, this issue can be closed. Thanks!

**Comment by jiasli** [comment]
@cure. You are welcome. I am glad the issue is solved. I doubt in your old Debian Buster https://packages.debian.org/ somehow overrides https://packages.microsoft.com/ for Azure CLI, so the installed Azure CLI is not the official release.
