### ISSUE TITLE
`az keyvault key download` dosent exist

### ISSUE THREAD

**Issue by akingscote** [Azure/azure-cli#12517]
Hello, the command az keyvault dosent exist on my az cli
https://docs.microsoft.com/en-us/cli/azure/keyvault/key?view=azure-cli-latest#az-keyvault-key-download

```
ashley@ubuntu:~/azcli$ az keyvault key --help

Group
    az keyvault key : Manage keys.

Commands:
    backup         : Requests that a backup of the specified key be downloaded to the client.
    create         : Creates a new key, stores it, then returns key parameters and attributes to the
                     client.
    delete         : Deletes a key of any type from storage in Azure Key Vault.
    import         : Import a private key.
    list           : List keys in the specified vault.
    list-deleted   : Lists the deleted keys in the specified vault.
    list-versions  : Retrieves a list of individual key versions with the same key name.
    purge          : Permanently deletes the specified key.
    recover        : Recovers the deleted key to its latest version.
    restore        : Restores a backed up key to a vault.
    set-attributes : The update key operation changes specified attributes of a stored key and can
                     be applied to any key type and key version stored in Azure Key Vault.
    show           : Gets the public part of a stored key.
    show-deleted   : Gets the public part of a deleted key.

Please let us know how we are doing: https://aka.ms/clihats
ashley@ubuntu:~/azcli$ az keyvault key download
az keyvault key: 'download' is not in the 'az keyvault key' command group. See 'az keyvault key --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
ashley@ubuntu:~/azcli$ 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0f363b-7f21-0ea9-3e27-da7866c94102
* Version Independent ID: 6cc413e4-4f7d-9baa-a365-c9275fc6a7ad
* Content: [az keyvault key](https://docs.microsoft.com/en-us/cli/azure/keyvault/key?view=azure-cli-latest#az-keyvault-key-download)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@bim-msft  please take a look.

**Comment by bim-msft** [comment]
@akingscote Hi, what's version are you using? You may run `az --version` to check your version. The key downloading feature is only available at versions that `>= 2.0.81`

**Comment by akingscote** [comment]
@bim-msft I assumed it would be something like this. Im using version 2.0.80.
Can you please add something more obvious to the documentation to say you need 2.0.81?
Thanks, Ashley

**Comment by bim-msft** [comment]
@akingscote It's a good idea to add the version limit info into the documentation, thanks for your suggestion, we'll find out a good way to implement this.

Actually, we have release notes here: https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#february-04-2020 , but it's still inconvenient (at least for me).

Issue closed, feel free to reopen if you have anything unresolved. Anyway, thanks for the feedback!
