### ISSUE TITLE
Enable paging in command results

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1251]
Today, for commands which produce large amount of result data and take long time to execute the user experience is poor. The command doesn't provide feedback to indicate progress. The final output can be huge and inconvenient to consume if it is not captured in file.

Many REST API our commands depend on actually provide server side and/or client side paging. By leveraging the paging feature, we can provide a friendlier user interaction. If user opt in, the command can print result piece by piece as each page arrives.

The goal of this task is to design and implement such a mechanism in the core of the CLI so that most of the commands can be equipped with paging feature without changes to the commands themselves as long as the underlying Azure API supports paging.

**Comment by troydai** [comment]
Per discussion with @johanste I'll looking into this one.

**Comment by troydai** [comment]
https://github.com/Azure/azure-cli/pull/1832

**Comment by tjprescott** [comment]
How does this differ from #3481?

**Comment by troydai** [comment]
No.

**Comment by troydai** [comment]
Let me close this one as dup...
