### ISSUE TITLE
Issue: Python Zip deployment not successful for FuncApp using azcli

### ISSUE THREAD

**Issue by infrageek** [Azure/azure-cli#12510]
## Describe the bug

**Zip deployment fails from az cli. The same code uploads successfully if done manually using vscode Azure Function plugin.**

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
Timeout reached by the command, however, the deployment operation
                       is still on-going. Navigate to your scm site to check the deployment status
```

^Croot@pipejenkinstf:/test# az webapp deployment source config-zip -g myrandrg -n myuniquefunctj --src ./deploy.zip  --timeout=180
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 503
Deployment status endpoint https://myuniquefunctj.scm.azurewebsites.net/api/deployments/latest returns malformed data. Retrying...
Deployment status endpoint https://myuniquefunctj.scm.azurewebsites.net/api/deployments/latest returns malformed data. Retrying...
Deployment status endpoint https://myuniquefunctj.scm.azurewebsites.net/api/deployments/latest returns malformed data. Retrying...
Deployment status endpoint https://myuniquefunctj.scm.azurewebsites.net/api/deployments/latest returns malformed data. Retrying...
Deployment status endpoint https://myuniquefunctj.scm.azurewebsites.net/api/deployments/latest returns malformed data. Retrying...

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip -g {} -n {} --src {} --timeout={}`

## Environment Summary
```
Linux-4.9.0-11-amd64-x86_64-with-debian-9.11
Python 3.6.5
Shell: bash

azure-cli 2.0.81 *

```

**Comment by yonzhan** [comment]
webapp

**Comment by schaijkw** [comment]
I have the same issue for a Python Function App. Is there any update or link on the follow-up issue?
