### ISSUE TITLE
Error on create Azure Red Hat Openshift with azure-cli-extensions

### ISSUE THREAD

**Issue by konosuke115** [Azure/azure-cli#12514]
## Describe the bug

**Command Name**
`az aro create
Extension Name: aro. Version: 0.1.0.`

**Errors:**
```
'NoneType' object has no attribute 'object_id'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 306, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 493, in default_command_handler
    return op(**command_args)
cliextensions/aro/azext_aro/custom.py, ln 65, in aro_create
    assign_contributor_to_vnet(cmd.cli_ctx, vnet, rp_client_sp.object_id)
AttributeError: 'NoneType' object has no attribute 'object_id'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aro create -g {} -n {} --vnet {} --master-subnet {} --worker-subnet {}`

## Environment Summary
```
Linux-4.15.0-1071-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.1.0

Extensions:
aro 0.1.0

```

**Comment by jluk** [comment]
We will need to reroute this to the ARO product team.

**Comment by sauryadas** [comment]
@amanohar

**Comment by amanohar** [comment]
`az openshift` & `az aro` commands are for different version of ARO: `az openshift` works for ARO 3.11 and `az aro` is for ARO 4.3 (and is currently under preview). Ack on the reported issue. We will take a look.

**Comment by konosuke115** [comment]
Thank you @amanohar 

I want to try creating ARO 4.3.

At the time of the first error, the documentation I used is below
> https://docs.microsoft.com/en-us/azure/openshift/howto-using-azure-redhat-openshift

**Comment by konosuke115** [comment]
Now I tried again and got another error.
> Konosuke115@Azure:~
 $ `az aro create -g giki-take-aro-rg -n giki-take-aro --vnet vnet --master-subnet aro-master --worker-subnet aro-worker`
This command group is in preview. It may be changed/removed in a future release.
**The resource type could not be found in the namespace 'Microsoft.RedHatOpenShift' for api version '2019-12-31-preview'.**

I'm sorry. [In the first run](https://github.com/Azure/azure-cli/issues/12514#issue-578302158), I may have forgotten to run the following command.
> `az provider register -n Microsoft.RedHatOpenShift --wait`

**Comment by jim-minter** [comment]
Thanks for the error report.  It makes sense that you got that error having not registered the RP first.  We'll add in a better error message at https://github.com/Azure/ARO-RP/pull/264 .

**Comment by Jen7714** [comment]
Looks like the error message has been updated. Closing this for now.
