### ISSUE TITLE
Sub-heading links do not function correctly

### ISSUE THREAD

**Issue by benradstone** [Azure/azure-cli#12527]
For example, when clicking on the 'Required Parameters' or 'Optional Parameters' subheading links for the 'az vm create' section, I am redirected to the equivalently named links for the 'az vm capture' section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#required-parameters)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look? thanks.

**Comment by qwordy** [comment]
Bug confirmed. It's a general problem. It occurs not only in vm. We will fix it.

**Comment by qwordy** [comment]
@jsntcy Do you know how Azure CLI web pages are generated? How can we fix it? Is the code owned by us?

**Comment by qwordy** [comment]
I have reported this issue to Docs team in internal channel.

**Comment by qwordy** [comment]
It is fixed now. Cheers!
