### ISSUE TITLE
az network front-door - dosen't exist

### ISSUE THREAD

**Issue by dariuszbz** [Azure/azure-cli#12528]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
based on documentation https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door?view=azure-cli-latest

but I can't see:

az network --help
Group
    az network : Manage Azure Network resources.

Subgroups:
    application-gateway    : Manage application-level routing and load balancing services.
    asg                    : Manage application security groups (ASGs).
    bastion      [Preview] : Manage Azure bastion host.
    ddos-protection        : Manage DDoS Protection Plans.
    dns                    : Manage DNS domains in Azure.
    express-route          : Manage dedicated private network fiber connections to Azure. 
    lb                     : Manage and configure load balancers.
    local-gateway          : Manage local gateways.
    nat                    : Commands to manage NAT resources.
    nic                    : Manage network interfaces.
    nsg                    : Manage Azure Network Security Groups (NSGs).
    private-dns            : Manage Private DNS domains in Azure.
    private-endpoint       : Manage private endpoints.
    private-link-service   : Manage private link services.
    profile                : Manage network profiles.
    public-ip              : Manage public IP addresses.
    route-filter [Preview] : Manage route filters.
    route-table            : Manage route tables.
    service-endpoint       : Manage policies related to service endpoints.
    traffic-manager        : Manage the routing of incoming traffic.
    vnet                   : Manage Azure Virtual Networks.
    vnet-gateway           : Use an Azure Virtual Network Gateway to establish secure, cross-
                             premises connectivity.
    vpn-connection         : Manage VPN connections.
    vrouter                : Manage the virtual router.
    watcher                : Manage the Azure Network Watcher.
**To Reproduce**
download azure-cli 2.2.0 (today release) and run:
az network --help

**Expected behavior**
there is front-door

**Environment summary**
{
  "azure-cli": "2.2.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.2.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.33",
    "dev-spaces": "1.0.3"
  }
}

**Additional context**

**Comment by bradcavanagh-ffs** [comment]
Have you added the front door extension by typing `az extension add --name front-door` first?

**Comment by yungezz** [comment]
hi @MyronFanQiu  could you pls have a look? thanks.

**Comment by MyronFanQiu** [comment]
@dariuszbz Hi. @bradcavanagh-ffs is correct. front-door is an CLI extension right now. We need to run `az extension add --name front-door` to add the extension first.

**Comment by dariuszbz** [comment]
Aha !!!!
🤔
I did not going the clue in documentation.

**Comment by MyronFanQiu** [comment]
@dariuszbz it's fine. 😄 If you don't have other question, we can close this issue.

**Comment by dariuszbz** [comment]
az extension add --name front-door - works :)
