### ISSUE TITLE
--ssh-key-value in the example for az vm create

### ISSUE THREAD

**Issue by jakaruna-MSFT** [Azure/azure-cli#12520]
** CLI version **
2.0.80

**Describe the bug**
In the `az vm create -h`, we replaced `--ssh-key-value` with `--ssh-key-values`.
One of the example is still using  `--ssh-key-value` . Its creating confusion among the customers.
I think we can update that to `--ssh-key-values`

Both options work well though.  May be because of the prefix matching
 
**To Reproduce**
`az vm create -h`
and look at the examples

**Expected behavior**
Help should reflect the options shown in the help

**Environment summary**
MSI installation

**Comment by jakaruna-MSFT** [comment]
https://github.com/Azure/azure-cli/issues/8669#issuecomment-492398459  Link to comment which had the info about the change from --ssh-key-value to --ssh-key-values

**Comment by jakaruna-MSFT** [comment]
@adewaleo Please add your comments

**Comment by jakaruna-MSFT** [comment]
@pipern    added you here for visibility since you raised the initial [issue ](https://github.com/MicrosoftDocs/azure-docs/issues/49728)in Azure docs

**Comment by jakaruna-MSFT** [comment]
https://github.com/Azure/azure-cli/blob/f6e542a5ab5b4115fc76e39c5b3509da0b7e3a44/src/azure-cli/azure/cli/command_modules/vm/_help.py#L834


this link has `--ssh-key-value`

**Comment by yonzhan** [comment]
@qwordy  please take a look.

**Comment by adewaleo** [comment]
You are right @jakaruna-MSFT, the CLI will match against a prefix if no other options share that prefix. Which is nice when we switched to --ssh-key-values as it isn't a breaking change. But we should update our examples to use the full option

**Comment by jakaruna-MSFT** [comment]
Thanks @adewaleo

**Comment by qwordy** [comment]
Opened a PR to fix it.

**Comment by qwordy** [comment]
PR is merged. You can see the changes in next version of Azure CLI. Official Release: 03/31/2020.
