### ISSUE TITLE
[CosmosDB] az cosmosdb list-connection-strings deprecation with incorrect replacement

### ISSUE THREAD

**Issue by sinedied** [Azure/azure-cli#12526]
## Describe the bug

**Command Name**
`az cosmosdb list-connection-strings`

**Errors:**
Report deprecation notice and tells us to use `az cosmosdb keys list` instead, but it's not the same thing and can't be used as a replacement. Keys alone are useless to me as a MondoDB user, I need the full connection string.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a CosmoDB account
- `az cosmosdb list-connection-strings --name {} --resource-group {}`

## Expected Behavior
No deprecation warning, or redirect me to an actual replacement of the command and not the one that list keys.

As a user, this is extremely confusing, not to mention the other deprecation notice that do not have actual replacements (yet?).
To avoid such issues, I suggest putting in place the replacement commands BEFORE adding deprecation notice otherwise it creates unnecessary confusion.

## Environment Summary
```
macOS-10.15.1-x86_64-i386-64bit
Python 3.8.1

azure-cli 2.2.0

```

**Comment by yungezz** [comment]
thanks for reporting, we'll have a look

**Comment by shurd** [comment]
Hi @sinedied, thank you for opening this issue. The "az cosmosdb keys list" accepts an optional parameter "--type" that can be "connection-strings", "keys", or "read-only-keys". If you want the connection strings for the account, you can use a command similar to:

`az cosmosdb keys list --name {} --resource-group {} --type connection-strings`

You can view all details about this command using `az cosmosdb keys list -h`

**Comment by sinedied** [comment]
Hi @shurd , that's good to heard 👍 
But then if the option is there, you should indicate it in the deprecation message, it would avoid needless confusion. Would you be open to a PR for this?
