### ISSUE TITLE
[Test] Run test cases in parallel to improve build efficiency. 

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1252]
Today it takes around 50 minutes to finish a CLI build task on Travis. The build is repeated on three platforms: python2.7, python3.5 and python3.5-dev. Therefore, the average time spent on each platform is around 16 minutes.

All of our tests are VCR.py based. That means the test executions are already encapsulated enough.

I'd like to explorer the possibility of running tests in parallel in order to shorten the build time on CI.

**Comment by tjprescott** [comment]
@troydai this can be closed, yes?

**Comment by troydai** [comment]
Partially.

We're able to run test modules in parallel, but not the tests in test suites.

**Comment by troydai** [comment]
This is done.
