### ISSUE TITLE
while creating a deployment through Azure CLI I am facing one issue as mentioned below.

### ISSUE THREAD

**Issue by Atif-byte** [Azure/azure-cli#12538]
**Resource Provider**
What is the Azure resource provider your feature is part of?

https://portal.azure.com/?quickstart=true#blade/HubsExtension/BrowseResourceGroups

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.

I am deploying DELL-EMC CLoudboost, Please refer below guide for reference
https://www.dellemc.com/en-us/collaterals/unauth/technical-guides-support-information/products/data-protection/docu96466.pdf

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

Error Message which I am getting in Azure CLI while creating this deployment

C:\>az group deployment create -n cloudboost18.1 -f C:\Users\atif.shakil\Downloads\CloudBoost-19.1.0.0.Build.7-azure\management\mgt_console\resources\scripts\autobuild\azuredeploy.json -g cloudboostemc
az: error: unrecognized arguments: -f C:\Users\atif.shakil\Downloads\CloudBoost-19.1.0.0.Build.7-azure\management\mgt_console\resources\scripts\autobuild\azuredeploy.json
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,yamlc,none}] [--query JMESPATH]
          {group} ...

**Comment by yonzhan** [comment]
add to S168

**Comment by Atif-byte** [comment]
Hi Yonzhan can you please update what is a"add to S168" all about? Do you need any further information from my end?

**Comment by yonzhan** [comment]
Planned in https://github.com/Azure/azure-cli/milestones

**Comment by Atif-byte** [comment]
Hello zhoxing-ms and yonzhan.. Can you help me on the above mentioned please?

**Comment by zhoxing-ms** [comment]
@Atif-byte Are you using the old version of azure-cli?
In the old version of azure-cli, the shorthand `-f` for `--template-file` is not supported. This shorthand can be used in the latest version of azure-cli (2.2.0), please try it.

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
