### ISSUE TITLE
Trying add rule on CDN sku MS

### ISSUE THREAD

**Issue by julianosecondo** [Azure/azure-cli#12545]
## Describe the bug

**Command Name**
`az cdn endpoint rule action add`

**Errors:**
```
'NoneType' object has no attribute 'rules'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 306, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 493, in default_command_handler
    return op(**command_args)
cli/command_modules/cdn/custom.py, ln 396, in add_action
    for i in range(0, len(policy.rules)):
AttributeError: 'NoneType' object has no attribute 'rules'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cdn endpoint rule action add -g {} -n {} --profile-name {} --rule-name {} --action-name {} --redirect-protocol {} --redirect-type {}`

## Environment Summary
```
Linux-5.3.0-40-generic-x86_64-with-debian-buster-sid
Python 3.6.5

azure-cli 2.2.0

```

**Comment by yonzhan** [comment]
cdn

**Comment by hytao** [comment]
Looks like client is trying to add a rule to an endpoint which doesn't exist. Can you share the full command including endpoint name resource group name?

**Comment by julianosecondo** [comment]
I changed the parameters that I was using and it works properly
az cdn endpoint rule add -g ${var.rgname} -n ${azurerm_cdn_endpoint.cdnstr[count.index].name} --profile-name ${azurerm_cdn_profile.cdnprofile[count.index].name} --order 1 --rule-name "RewriteSSL" --match-variable RequestScheme --operator Equal --match-values HTTP --action-name "UrlRedirect" --redirect-protocol Https --redirect-type PermanentRedirect --custom-hostname ${var.cdn-dns-str}
