### ISSUE TITLE
az network list-service-tags --location westus2 lists all regions

### ISSUE THREAD

**Issue by jwrightazure** [Azure/azure-cli#12546]
az network list-service-tags --location westus2 lists all regions, not just westus2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1f75594-b95b-a85d-b971-c06e207e3fe2
* Version Independent ID: 16a09479-ff9b-9029-aae4-6ba14ccc8260
* Content: [az network](https://docs.microsoft.com/en-us/cli/azure/network?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S168

**Comment by MyronFanQiu** [comment]
@jwrightazure Yes. I think you are right. Let me check.

**Comment by MyronFanQiu** [comment]
@chandrasekarsrinivasan Hi. I check the rest call and the endpoint is 
```
'https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx/providers/Microsoft.Network/locations/westus2/serviceTags?api-version=2019-11-01'
```
Could you take a look at this issue?

**Comment by allegradomel** [comment]
@jwrightazure - thanks for bringing this to our attention. @MyronFanQiu I will also try to follow up on this

**Comment by yonzhan** [comment]
@allegradomel  any update for this issue?

**Comment by allegradomel** [comment]
Hi @jwrightazure - providing an update here. The location parameter is described more accurately in the corresponding PowerShell command doc: 

"Please note that the Azure region information you specify will be used as a reference for version (not as a filter based on location). For example, even if you specify -Location eastus2 you will get the list of service tags with prefix details across all regions but limited to the cloud that your subscription belongs to (i.e. Public, US government, China or Germany)."

I created a PR to add this to the CLI doc as well. Please track its status here: https://github.com/Azure/azure-cli/pull/14935

#please-close
