### ISSUE TITLE
az network application-gateway waf-config want deprecation info on CLI Docs

### ISSUE THREAD

**Issue by ericrousse** [Azure/azure-cli#12549]
This page should reflect az cli, it says that waf-config is deprecated and replaced by waf-policy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68725488-1e3a-ac2d-c454-bcedd26e4b70
* Version Independent ID: 706d7f46-f132-10ab-423c-4a640d65d2dc
* Content: [az network application-gateway waf-config](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/waf-config?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S168

**Comment by MyronFanQiu** [comment]
@haroldrandom Could you please take a look at this issue?

**Comment by haroldrandom** [comment]
@ericrousse What does it mean "reflect az cli"?

**Comment by jsntcy** [comment]
Maybe we need add such deprecate information in our help; otherwise docs CI cannot know this.

**Comment by yonzhan** [comment]
We will work with doc team to show the deprecation info for all CLI commands.

**Comment by haroldrandom** [comment]
https://github.com/Azure/azure-cli/pull/15234 removed the deprecation info. So this issue is no longer necessary
