### ISSUE TITLE
webapps: incorrect docs and no "swap" command

### ISSUE THREAD

**Issue by jonathanong** [Azure/azure-cli#1255]
https://azure.microsoft.com/en-us/documentation/articles/web-sites-staged-publishing/#azure-command-line-interface-azure-cli-commands-for-deployment-slots

- it seems as though `site` was renamed to `webapp`. the docs do not reflect this change.
- the `swap` command seems to have been removed. how can i swap via CLI?

**Comment by mayurid** [comment]
@jonathanong : There are a couple of things here:-
1) This is the repo for the new CLI that the team is working on. The documentation that you are referring is regarding the existing CLI (https://github.com/Azure/azure-xplat-cli)
2) The site command still exists but is only available in the ASM mode. The ARM mode has the new commandlets which are under webapp.

Please move this issue to https://github.com/Azure/azure-xplat-cli and the webapp team will pick it up to update the documents accordingly.

**Comment by mayurid** [comment]
@Lukaszstem as FYI

**Comment by yugangw-msft** [comment]
JFYI, new cli does expose `swap`: `az appservice web deployment slot swap`, but the whole `slot` support end to end will be finalized later, so expect some commands might get moved around

**Comment by mayurid** [comment]
@jonathanong : Have you tried the new CLI? We would be happy to work with you and get some input on the new approach.

**Comment by jonathanong** [comment]
i will try the new CLI tomorrow! i am having trouble using the ASM at all in the node.js CLI for auth reasons.

**Comment by jonathanong** [comment]
i don't see the `appservice` command at all

```bash
$ az -h

For version info, use 'az --version'

Group
    az

Subgroups:
    account  : Manages stored and default subscriptions.
    acs      : Manage Azure container services.
    ad       : Synchronize on-premises directories and manage Azure Active Directory (AAD)
               resources.
    cloud    : Manage the Azure clouds registered.
    component: Manages and updates Azure CLI components.
    context  : Manage contexts.
    network  : Manages Network resources.
    provider : Manage resource providers.
    resource : Generic commands to manage Azure resources.
    role     : Use role assignments to manage access to your Azure resources.
    storage  : Durable, highly available, and massively scalable cloud storage.
    tag      : Manage resource tags.
    vm       : Provision Linux and Windows virtual machines in minutes.
    vmss     : Create highly available, auto-scalable Linux or Windows virtual machines.

Commands:
    configure: Interactive experience for setting up the Azure CLI.
    feedback : Loving or hating the CLI?  Let us know!
    login    : Log in to access Azure subscriptions.
    logout   : Log out to remove accesses to Azure subscriptions.

```

**Comment by derekbekoe** [comment]
Currently the appservice commands do not come with the default install.

The following command will install the `appservice` commands:
```
$ az component update --additional-component webapp
```

**Comment by jonathanong** [comment]
Ok I will try that. I did not see that command in the component help

**Comment by mayurid** [comment]
I believe it should be --add. @derekbekoe?

**Comment by derekbekoe** [comment]
@mayurid That pull request was merged after the current public version (0.1.0b8).

**Comment by jonathanong** [comment]
i now don't know how to create a slot with a git integration

```bash
$ az appservice web deployment slot create -h

Command
    az appservice web deployment slot create

Arguments
    --resource-group -g [Required]: Name of resource group.
    --slot              [Required]: The name of the slot.
    --webapp            [Required]: Name of the webapp.
    --configuration-source

Global Arguments
    --debug                       : Increase logging verbosity to show all debug logs.
    --help -h                     : Show this help message and exit.
    --output -o                   : Output format.  Allowed values: json, jsonc, list, table, tsv.
                                    Default: json.
    --query                       : JMESPath query string. See http://jmespath.org/ for more
                                    information and examples.
    --verbose                     : Increase logging verbosity. Use --debug for full debug logs.
```

what's an integration source?

**Comment by yugangw-msft** [comment]
The git integration command was committed to the repository, but have not been published yet. The e2e scenario is documented in the [test](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py#L273) 
To avoid all the hassles, I think the best time for you to use it would be next week, when we plan to release new drops across

**Comment by jonathanong** [comment]
No problem :+1: thanks

**Comment by derekbekoe** [comment]
Alternatively, we have nightly builds available:

```
$ export AZURE_COMPONENT_PACKAGE_INDEX_URL=https://azureclinightly.blob.core.windows.net/packages
$ az component update --add appservice --private
```
https://github.com/Azure/azure-cli/blob/master/doc/nightly/installing_nightly.md

**Comment by derekbekoe** [comment]
Note:
- The name of the module has changed from `webapp` to `appservice`
- We recently changed `--additional-component` to `--add`

**Comment by yugangw-msft** [comment]
We have addressed/clarified issues discussed in this issue. Closing
