### ISSUE TITLE
Linked as how-to

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-cli#12557]
It seems very irregular to me that this page is linked in the AKS How-to guides as "Create an AKS cluster" with the following link:
https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest&toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Faks%2FTOC.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json#az-aks-create

I expect how-to docs to be prose explanations of how to do something that could contain CLI, but not direct links to the CLI reference, which is available in the Reference section of the ToC already. Is this really a good place for this link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest&toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Faks%2FTOC.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json#az-aks-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
thanks for reporting the issue, we're looking at it

**Comment by jluk** [comment]
Thanks for the report - this is a docs issue we will get fixed. I am going to close this as this is the azure-cli repo and not azure docs, should be fixed in 2 days.

**Comment by jluk** [comment]
Given we have the full walkthrough of how to create/delete in the AKS tutorial, we will be removing those ToC references as we agree it is not the proper docs experience to link to a CLI help guide.

**Comment by dcbrown16** [comment]
Sounds good, thanks @jluk!
