### ISSUE TITLE
Remove deprecated option from example

### ISSUE THREAD

**Issue by shannawaz** [Azure/azure-cli#12552]
Modify example to change --name to --vmss-name. 
 Option '--name' has been deprecated and will be removed in a future release. Use '--vmss-name' instead.

az vmss disk attach --name MyVmss --resource-group MyResourceGroup --size-gb 50

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8adcfd37-16cb-c9b8-531b-b2811ed62bcd
* Version Independent ID: b7045192-cb7f-a065-af58-ddbcd3589860
* Content: [az vmss disk](https://docs.microsoft.com/en-us/cli/azure/vmss/disk?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by qwordy** [comment]
OK. Thank you for finding this issue! Planned in S167.

**Comment by qwordy** [comment]
I wrote a PR to fix it. It will be available in next version of Azure CLI. Release date: 03/31/2020.
