### ISSUE TITLE
The user or administrator has not consented to use the application with ID

### ISSUE THREAD

**Issue by enihcam** [Azure/azure-cli#12566]
## Describe the bug

**Command Name**
`az rest`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID '04b07795-8ddb-461a-bbee-02f9e1bf7b46' named 'Microsoft Azure CLI'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 02091fac-12c0-4122-a279-535ae06a0c00\r\nCorrelation ID: b97053e5-9a56-46f4-96ca-a4b99b8938bf\r\nTimestamp: 2020-03-12 12:04:38Z","error_codes":[65001],"timestamp":"2020-03-12 12:04:38Z","trace_id":"02091fac-12c0-4122-a279-535ae06a0c00","correlation_id":"b97053e5-9a56-46f4-96ca-a4b99b8938bf","suberror":"consent_required"}
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
- `az rest -m {} -u {}`

## Environment Summary
```
Linux-4.4.0-17763-Microsoft-x86_64-with-glibc2.2.5
Python 3.8.2

azure-cli 2.2.0

Extensions:
log-analytics 0.1.4
spring-cloud 0.2.2

```

**Comment by yungezz** [comment]
HI @zhoxing-ms could you pls have a look? thanks

**Comment by yonzhan** [comment]
add to S167

**Comment by jiasli** [comment]
@enihcam, as discussed offline, from the `az resource` log, the management endpoint you used is `https://api-dogfood.resources.windows-int.net/`, but it seems `az rest` fails to get the access token. 

- Please try `az account get-access-token --resource https://api-dogfood.resources.windows-int.net/ --debug` and share the output
- Please follow this doc to capture a Fiddler trace: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy
