### ISSUE TITLE
create aks cluster failture

### ISSUE THREAD

**Issue by winseng-ws** [Azure/azure-cli#12564]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
'registrationState'
Traceback (most recent call last):
pip-install-9101vebg\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 608, in execute
cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
cli\core\commands\__init__.py, ln 659, in _run_job
Temp\pip-install-9101vebg\six\six.py, ln 703, in reraise
cli\core\commands\__init__.py, ln 636, in _run_job
cli\core\commands\__init__.py, ln 306, in __call__
azure\cli\core\__init__.py, ln 493, in default_command_handler
cli\command_modules\acs\custom.py, ln 1857, in aks_create
...
pip-install-9101vebg\requests\requests\sessions.py, ln 650, in send
pip-install-9101vebg\requests\requests\hooks.py, ln 31, in dispatch_hook
msrest\msrest\universal_http\requests.py, ln 275, in user_hook_cb
pip-install-9101vebg\msrestazure\msrestazure\tools.py, ln 57, in register_rp_hook
pip-install-9101vebg\msrestazure\msrestazure\tools.py, ln 102, in _register_rp
KeyError: 'registrationState'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --enable-addons {} --generate-ssh-keys`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6

azure-cli 2.2.0

```

**Comment by yungezz** [comment]
thanks for reporting, we are looking at it

**Comment by jluk** [comment]
The error looks like a registration error, can you validate microsoft.containerservice is returned on `az provider list`?

If not you can register the provider with `az provider register -n microsoft.containerservice'

**Comment by winseng-ws** [comment]
I ran the command again and it runs successfully. Thank you.
