### ISSUE TITLE
az functionapp create should change LinuxFxVersion for dotnet

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-cli#12577]
For dotnet, the setting needs to be empty, rather than `Dotnet`. Setting it to `Dotnet` is not recommended and will fail to create on Linux Consumption.

We should set it to empty string for all skus for consistency.

**Comment by yungezz** [comment]
thanks for reporting, we'll have a look

**Comment by sixeyed** [comment]
Hi @ankitkumarr - do you have an ETA for the fix on this? I have a very smooth CI/CD pipeline which automates a ton of stuff, except for creating the function app which I need to do manually. It would be great to close that off.

**Comment by gzuber** [comment]
This should be fixed by https://github.com/Azure/azure-cli/pull/12817

@sixeyed sorry about that! Let us know if you experience any more issues after that fix is released

**Comment by ankitkumarr** [comment]
Thanks @gzuber.

Closing as this is fixed by https://github.com/Azure/azure-cli/pull/12817
