### ISSUE TITLE
Documented syntax is deprecated

### ISSUE THREAD

**Issue by lokijota** [Azure/azure-cli#12575]
For example when running "az cosmosdb database create ..." there's a warning saying:

"This command has been deprecated and will be removed in a future release. Use 'cosmosdb sql database, cosmosdb mongodb database, cosmosdb cassandra keyspace or cosmosdb gremlin database' instead."

This is with az cli version 2.0.79 (which is not the latest).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da15197a-eca2-19d6-72e3-be853337a759
* Version Independent ID: eb84d467-86df-121e-3b04-66b499342f7f
* Content: [az cosmosdb database](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/database?view=azure-cli-latest#az-cosmosdb-database-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
thanks for reporting, we'll look at it

**Comment by shurd** [comment]
Hi @lokijota thank you for opening this issue. Unfortunately there is not currently any way to exclude certain commands from the auto-generated documentation without removing support for the commands in the CLI.

The new API-specific commands are also documented, so you can review how to use them (one example is [here](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/sql/database?view=azure-cli-latest#az-cosmosdb-sql-database-create). We have hidden the deprecated commands from the "help" menu in the CLI.
