### ISSUE TITLE
SetOrchestrationServiceState CLI Request

### ISSUE THREAD

**Issue by cachuahu** [Azure/azure-cli#12571]
Hi,
 We have a new compute API that we want to release by March 31 2020.

So far, the swagger and SDK changes are not merged yet in public repo but its estimated to be merged by end of week or next week.

The swagger changes: https://github.com/Azure/azure-rest-api-specs/pull/8613
SDK changes: https://github.com/Azure/azure-sdk-for-net-pr/pull/967/commits
Powershell cmdlet design approved: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/479

Could someone let me know if its possible to get this done by March 31 release? Let me know if more information is needed.

@yungezz

**Comment by yungezz** [comment]
put it in S167

**Comment by yungezz** [comment]
automatic instance repair related

**Comment by yungezz** [comment]
the feature is released in latest 2.3.0 version, pls give it a try and let us know if any other issue. close the issue.
