### ISSUE TITLE
In "az vmss update --set" property value is calculated instead of using its string form

### ISSUE THREAD

**Issue by amergey** [Azure/azure-cli#12573]
I'd like to change a sku on a scale set. My sku is called "5-1" when I tried to change it using cli
 
`az vmss update --set virtualMachineProfile.storageProfile.imageReference.sku=5-1`

It seems 5-1 is calculated so 4 is used as a value, but I really want 5-1 to be used as the error message is _The platform image 'semarchy:xdm-solution-vm:4:latest' is not available._ 
the image I want is **semarchy:xdm-solution-vm:5-1:latest** (note it was 5-1 I asked for, not 4) 

**Command Name**
`az vmss update`

**Errors:**
```
The platform image 'semarchy:xdm-solution-vm:4:latest' is not available. Verify that all fields in the storage profile are correct. For more details about storage profile information, please refer to https://aka.ms/storageprofile
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss update --name {} --resource-group {} --set {}`

## Environment Summary
```
Linux-4.15.0-1071-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0

```

**Comment by yungezz** [comment]
HI @qwordy could you pls have a look? thanks.

**Comment by qwordy** [comment]
Issue confirmed. It happens in bash. But it works fine in PowerShell.
This line from log indicates that bash passes 5-1 to Azure CLI instead of 4.
```
Command arguments: ['vmss', 'update', '-g', 'fytest2', '-n', 'vmss1', '--set', 'virtualMachineProfile.storageProfile.imageReference.sku=5-1', '--debug']
```
It shows that Azure CLI has different behavior in different system.
I am investigating this issue. I will update here when I have promising findings.

**Comment by qwordy** [comment]
Please add `--force-string`.
When using 'set' or 'add', preserve string literals instead of attempting to convert to JSON.
Related code:
src/azure-cli-core/azure/cli/core/commands/arm.py: def set_properties
```
    if not force_string:
        try:
            value = shell_safe_json_parse(value)
```
