### ISSUE TITLE
update SKU

### ISSUE THREAD

**Issue by vbrinza** [Azure/azure-cli#12570]
What is the purpose of having the --sku flag into the update subcommand if the change is not allowed by the API?

az network public-ip update -g rg -n pip --sku Basic
Sku property is set at creation time and cannot be changed from Standard to Basic on resource update for resource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c12e07f8-d82f-a9ac-895a-b6d980c8c4c2
* Version Independent ID: 43924bb5-20bd-6a0e-9cdc-90b1db46e599
* Content: [az network public-ip](https://docs.microsoft.com/en-us/cli/azure/network/public-ip?view=azure-cli-latest#az-network-public-ip-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
HI @MyronFanQiu could you pls have a look? thanks

**Comment by MyronFanQiu** [comment]
@vbrinza You're right. Usually we cannot update it. But it's out of our control. For this scenario, I will check with service team to see whether we need to deprecate this one or not. Thanks for raising this issue.

**Comment by msyyc** [comment]
The deprecation is to fix https://github.com/Azure/azure-cli/issues/12570. In the future, sku can not be updated after creation for public ip.
