### ISSUE TITLE
[Role] Typo in "Role Assignment already exists" message

### ISSUE THREAD

**Issue by MarcPow** [Azure/azure-cli#12585]
Found an existing application instance of "97faf87e-9041-4703-b0b7-905c03f074a6". We will patch it
Creating a role assignment under the scope of "/subscriptions/ff5bfe84-dc63-4b4c-ad36-2324ae8480ad"
  Role assignment already **exits**.

**Comment by yonzhan** [comment]
add to S168

**Comment by jiasli** [comment]
Thanks for the contribution. I have merged https://github.com/Azure/azure-cli/pull/12586.
