### ISSUE TITLE
'az aks update --api-server-authorized-ip-ranges' will also enable private cluster

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-cli#12587]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 
2.2

**Describe the bug**
az aks update -g <>-n <> --api-server-authorized-ip-ranges '' --debug 

Will also update 'enablePrivateCluster' to true
"apiServerAccessProfile": {"authorizedIPRanges": [], "enablePrivateCluster": true}}}

This PR adds 2nd parameter instance to _populate_api_server_access_profile
https://github.com/Azure/azure-cli/pull/10976/files
This PR adds another parameter to _populate_api_server_access_profile, only updates aks_create call, didn't update aks_update call
https://github.com/Azure/azure-cli/pull/12353

**To Reproduce**
Run command above

**Expected behavior**
Do not touch enablePrivateCluster behaviour

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
This is being addressed with PR #12589
