### ISSUE TITLE
az keyvault list fails with NoneType error

### ISSUE THREAD

**Issue by alonisser** [Azure/azure-cli#12599]
## Describe the bug

**Command Name**
`az keyvault list`

**Errors:**
```
'NoneType' object has no attribute 'standard'
Traceback (most recent call last):
lib/python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
site-packages/azure/cli/core/__init__.py, ln 297, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
azure/cli/command_modules/keyvault/__init__.py, ln 42, in load_arguments
    load_arguments(self, command)
azure/cli/command_modules/keyvault/_params.py, ln 75, in load_arguments
    c.argument('sku', arg_type=get_enum_type(SkuName, default=SkuName.standard.value))
AttributeError: 'NoneType' object has no attribute 'standard'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault list`

## Environment Summary
```
Linux-4.15.0-88-generic-x86_64-with-debian-buster-sid
Python 3.6.6
Shell: bash

azure-cli 2.0.78 *

Extensions:
aks-preview 0.4.23
front-door 1.0.2

```

**Comment by yonzhan** [comment]
@bim-msft please take a look.

**Comment by alonisser** [comment]
pip install --upgrade azure-cli --user to the latest version 2.2.0 solved the issue

**Comment by bim-msft** [comment]
@alonisser Thanks for the feedback, glad to know that your issue was resolved in the latest version, maybe this is a bug exists in some old versions.
I will close this issue, if you have anything else need us to help with, feel free to reopen it, thanks!
