### ISSUE TITLE
{Core} The name of extension of dev is None if has incompatibility problem

### ISSUE THREAD

**Issue by haroldrandom** [Azure/azure-cli#12597]
**Describe the bug**
install an extension which has compatibility restriction, like connnection-monitor-preview (azure-cli-core <= 2.0.82 ). and some comamnds might give warning, but the name of the extension is 'None'.

**To Reproduce**
install connection-monitor-preivew exntension, and then `az -h`:
![image](https://user-images.githubusercontent.com/14357159/76735761-988c9600-67a0-11ea-8ba6-77d2a9587a3a.png)

**Expected behavior**
Show up the extension name.

**Environment summary**
No required

**Additional context**
1. [request for upgrade wheel](https://github.com/Azure/azure-cli/pull/12583)
2. [PEP 426, the metadata of Python Package](https://www.python.org/dev/peps/pep-0426/)
3. [Decided to pin wheel version in CLI](https://github.com/Azure/azure-cli/pull/8896)
4. [Change logs of wheel](https://github.com/pypa/wheel/blob/master/docs/news.rst)

**Comment by yonzhan** [comment]
add to S167
