### ISSUE TITLE
Command Error 

### ISSUE THREAD

**Issue by jose-lima2011** [Azure/azure-cli#12608]
az sql server tde-key Set --resource-group myresourcegroup --server myserver --server-key-type AzureKeyVault --kid "https://myresource.vault.azure.net/keys/mykeyname/key"

Deployment failed. Correlation ID: . The requested server key was not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea369391-5bd1-845a-83c8-f544d30728db
* Version Independent ID: 251e46ee-9f7a-2e64-8ae0-30837b23897b
* Content: [az sql server tde-key](https://docs.microsoft.com/en-us/cli/azure/sql/server/tde-key?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by paul-kr** [comment]
@jose-lima2011, how did you resolve this error?

**Comment by manishtulsiani** [comment]
we are also facing this exact same issue. the below command returns key not found whereas the key exists in the keyvault. the keyvault and sql server are in the same subscription.

az sql server tde-key set --resource-group myresourcegroup --server myserver --server-key-type AzureKeyVault --kid "https://myresource.vault.azure.net/keys/mykeyname/key"

Deployment failed. Correlation ID: . The requested server key was not found.

**Comment by paul-kr** [comment]
@manishtulsiani, we resolved this error by running two az cli commands: `az sql server key create <options> && az sql server tde-key set <options>`. Setting the tde key via the portal apparently takes care of both, but if you're doing it purely from the az cli, you have to take both actions to first create the key and then set it.

**Comment by Matka4** [comment]
> We resolved this error by running two az cli commands: `az sql server key create <options> && az sql server tde-key set <options>`. Setting the tde key via the portal apparently takes care of both, but if you're doing it purely from the az cli, you have to take both actions to first create the key and then set it.

Thank you @paul-kr
