### ISSUE TITLE
az webapp up -g parameter ignored

### ISSUE THREAD

**Issue by JonasJurczok** [Azure/azure-cli#12602]
**Describe the bug**
I tried adapting the quickstart tutorial for webapps to my companies setup.
The resource group that is created during `az webapp up` is always named after the default name, not after the one I provided.

**To Reproduce**
* create a static html file as content
* issue the command `az webapp up --name my-name --html -g my-resource-group`

**Expected behavior**
In the output the resource group should be named `my-resource-group`.
But it is named after my default resource group name.

**Environment summary**
Fresh installation of the latest version of az from the official sources.

**Additional context**
All other parameters work fine.
All variants of the resource group parameter produce the same result.
Using `--dryrun` does not change the behaviour.

I assume the problem stems from here: https://github.com/Azure/azure-cli/blob/10fea0291f1122db2780e1e7fbc4b031bf258d5c/src/azure-cli/azure/cli/command_modules/appservice/_create_util.py#L317
But I only did 5 min of digging.

**Comment by JonasJurczok** [comment]
After some more digging I assume the problem is upstream from the initial webapp_up call. But I'm just guessing.

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
Thanks for reporting due to limitation of not supporting windows and linux apps on same ASP, we make this check so that folks who are not aware of the limitations are not confused by this. However, I can see how this can still be confusing/ incorrect. Will discuss this with team further.

**Comment by JonasJurczok** [comment]
Hey,
thanks for looking into it. 

As I said my code references are a wild guess and most probably not connected to the problem. 

My main issue is that I cannot name resource groups via the command line :)

Have a great weekend and stay healthy.

**Comment by yonzhan** [comment]
move to S169

**Comment by panchagnula** [comment]
@JonasJurczok we made some latest fixes/updates to the command based on another bug can you check if you are still having a problem with the latest CLI version?

**Comment by JonasJurczok** [comment]
Thanks for the patch. I will verify within the next days.

**Comment by yonzhan** [comment]
move to S170

**Comment by panchagnula** [comment]
Closing this since we believe this is fixed. Please re-activate if this is not the case. Thanks!

**Comment by JonasJurczok** [comment]
Sorry I didn’t get back to you. We automated our whole deployment system so there is no need for the cli anymore. 

Thanks for the fix. If there is a problem I will reopen the issue.
