### ISSUE TITLE
Exprort/Import from file breaks keyvault references

### ISSUE THREAD

**Issue by nrjohnstone** [Azure/azure-cli#12605]
When exporting and then import from a file there is no metadata regarding wether it is a Value or KeyVault reference.
This means that all values get created as a Value, rendering an export/import from file useless if you have KeyVault references in your AppConfig

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e35da3a9-05a9-7727-fcc2-da501e89ee3f
* Version Independent ID: 679c47ba-0478-2023-a188-71d2d91ed903
* Content: [az appconfig kv](https://docs.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest#az-appconfig-kv-import)
* Content Source: [src/azure-cli/azure/cli/command_modules/appconfig/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appconfig/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
appconfig

**Comment by shenmuxiaosen** [comment]
Hi @nrjohnstone, do you have a user scenario that needs to import key-vault reference from files? Currently there is no way to tell the difference between a key-vault reference or a value which also contains something like ```
{"uri":"https://myUri"}```

**Comment by nrjohnstone** [comment]
Yes, we are keeping our configuration as code (yaml scripts) and using the
Azure CLI to import changes to it.

This allows us to have PR's and a second pair of eyes over the changes.

One of the main reasons for this is the abysmal user interface experience
of having to set up configuration values in the Azure Portal with
AppConfig, but for keyvault references it's even worse.

Also, if it can't tell the difference currently maybe you should make it
export only values and ignore key vault references, because if I currently
do an "export" to file, I get all the things and can mistakenly believe
that when I import it again, I will get key vault references (but I won't,
they get changes into values).

It's a nice flow having the config in yaml in the repo of the application
itself and then pushing them to Azure AppConfig when the pull request gets
merged.

Can you just make it support key vault references.

Something like this would easily work  (notice how it includes a version
number at the top so you can easily have backwards compatibility with the
existing functionalty)

Version: 2.0

SomeNamedKey:
  Type: kv
  Value: 100

SomeNamedKeyVaultReference:
  Type: keyvault
  Value: https://somekeyvault/secrets/foo

**Comment by shenmuxiaosen** [comment]
Thanks for the sharing your user scenario and suggestions. Currently there is a cr ongoing to add ```--skip-keyvault``` optional argument to exclude key vault references from kv exporting. https://github.com/Azure/azure-cli/pull/12650 Hopefully this can catch the next round of release. In the meanwhile, there are some other practices which can solve your problem if you want to stick with existing CLI version. For example, you can use label to separate your normal configurations and key vault reference. Then ```appconfig kv export --label myconfigLabel```. 

As for the long term solution, we are working on the design for importing items other than normal configurations such as key vault references, feature flags from files to App Configuration.

**Comment by navba-MSFT** [comment]
@nrjohnstone Apologies for the late reply. Could you please refer [this](https://docs.microsoft.com/en-us/cli/azure/appconfig?view=azure-cli-latest) article ? 

>--skip-keyvault
Export items excluding all key vault references. By default, all key vault references with the specified label will be exported.
accepted values: false, true t

This issue is open for quite sometime. Please let us know if you have any further questions on this. Awaiting your reply.
