### ISSUE TITLE
Using az appconfig on a VM with a managed identity throws error: Cannot find the App Configuration {{app config name}}. Check if it exists in the subscription that logged in.

### ISSUE THREAD

**Issue by olandese** [Azure/azure-cli#12606]
**Describe the bug**
With the Cli 2.2.0 on a Azure Windows VM with a Managed Identity a call like this:

az appconfig kv show --name my-appconfig-test --key test

Gives the following error: 

**Cannot find the App Configuration my-appconfig-test. Check if it exists in the subscription that logged in.**

The VM's Managed Identity has the "App Configuration Data Reader" role on the Azure App Configuration Instance .

**To Reproduce**
1. Create a WIndows Azure VM with a Managed Identity (Sytem or User assigned, doesn't matter)
2. Install Azure CLI (the error is with the 2.2.0 version)
3. Login with the Azure Cli with the Managed Identity (az login --identity)
4. Set the subscription where the App Configuration instance is: az account set -s {{app settings subscription id}}
5. Run an Az appconfig command, like az appconfig kv show --name my-appconfig-test --key test
6. This error appears:  **Cannot find the App Configuration my-appconfig-test. Check if it exists in the subscription that logged in.**
7 Retry the command several times, sometimes you get back a successful response. 

**Expected behavior**
The result of the command without the error

**Environment summary**
Ac CLI 2.2.0
Azure VM Windows Datacenter 2019 with a Managed Identity

**Comment by yungezz** [comment]
thanks for reporting, we'll look at it

**Comment by shenmuxiaosen** [comment]
Hi @olandese does the managed identity has access to the subscription where App Configuration has been created? Currently ```appconfig``` data plane does not support AAD(Azure Active Directory) yet. That explains adding App Configuration Data Reader role didn't work in your case. It only uses connection string to authenticate with App Configuration data plane server. So either directly passing in connection string or if passing in App Configuration name, then it will talk to management plane (Azure Resource Manager) to fetch the connection string, which will needs the ARM owner/contributor/reader role.

**Comment by olandese** [comment]
you are right, giving Contributor rights for the managed identity on the App Configuration work

**Comment by bennypowers** [comment]
Is it possible to grant read-only access?
I granted both `App Configuration Data Reader` and `Reader` roles to a user and they got this message, whereas `Contributor` worked, but I only want that user to have reads.

**Comment by shenmuxiaosen** [comment]
Hi bennypowers, currently ```appconfig``` does not support data plane AAD, which means it will only work with connection string to authenticate with server. However, CLI is able to use management plan AAD to fetch connection string. So that's the reason why ARM ```Contributor``` role works in this case.

**Comment by OskarKlintrot** [comment]
I think I might be running into the same issue. I have Access Key turned off and try to run a deployment script with a user assigned identity with roles `Contributor` and `Data Owner`. I get this error:
```
Cannot find a read write access key for the App Configuration <app config name>
```
I guess the CLI ignore the `Data Owner` role and that the solution is to turn on Access Key on the App Configuration?

**Comment by Kaloszer** [comment]
@OskarKlintrot had this just now, adding `--auth-mode login` helped if you output to a file also add `--yes` flag
