### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by arpitjain099** [Azure/azure-cli#12614]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Example has wrong braces.
URL: https://docs.microsoft.com/en-us/cli/azure/network/private-endpoint?view=azure-cli-latest#examples

will add more details later

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by yonzhan** [comment]
add to S168
