### ISSUE TITLE
Omit login server endpoint for `--registry` on `az acr`

### ISSUE THREAD

**Issue by shizhMSFT** [Azure/azure-cli#12631]
**Is your feature request related to a problem? Please describe.**
Many customers are frustrated in the experience of running the `az acr` command like below:
```
$ az acr run -f tasks.yaml . --registry myregistry.azurecr.io
The resource with name 'myregistry.azurecr.io' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription '<my subscription>'.
```
The correct input for `--registry` is `myregistry` but many customers mistype it with the login server `myregistry.azurecr.io`. When the customers read the error message, they are confused.

**Describe the solution you'd like**
To less confuse the customers, the `az acr` command sets should omit the `.azurecr.io` login server suffix for the customers if present.

**Describe alternatives you've considered**
If the above solution cannot be fulfilled, the `az acr` should at least prompt a friendly note to ask the customers omit the suffix by themselves instead of the confusing error message.

**Additional context**
Note that the domain prefix is available in
```
$ az cloud show --query "suffixes.acrLoginServerEndpoint"
".azurecr.io"
```

**Comment by yungezz** [comment]
thanks for reporting, we'll look at it

**Comment by northtyphoon** [comment]
--registry is a command option used in most `az acr` commands. So for consistency, it's better update all of them.

**Comment by Wwwsylvia** [comment]
Will look at it.
