### ISSUE TITLE
Unclear documentation for "az sql server ad-admin update" command

### ISSUE THREAD

**Issue by neilamoran** [Azure/azure-cli#12636]
Have started getting errors regarding the --parameters option with this command. It's not at all clear how it should be used - does it simply have to be present and prefix the other parameters?

Or are there some secret required parameters which you're not telling us and won't give an example of?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bca10a0-5310-1ed6-8391-57a8ccafb27f
* Version Independent ID: 4144f2fa-35f1-533c-e48b-17180f03203e
* Content: [az sql server ad-admin](https://docs.microsoft.com/en-us/cli/azure/sql/server/ad-admin?view=azure-cli-latest#az-sql-server-ad-admin-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
sql

**Comment by jaredmoo** [comment]
Fixed by #12541 . Thank you!

**Comment by melezhik** [comment]
how can I add _another_ admin to a sql server? it's not unclear from documentation.

**Comment by loopfish** [comment]
you can only ever have one AD admin.

**Comment by melezhik** [comment]
@loopfish  , thanks. It worth to reflect this fact in the documentation, as it is currently  ambiguous.
