### ISSUE TITLE
Connection Protocol IKEv1, IKEv2.

### ISSUE THREAD

**Issue by Make-Make** [Azure/azure-cli#12638]
I don't see parameter to choose between  IKEv1, IKEv2.
How to deploy IKEv1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9cd3cc3-90c6-19d0-1486-b779d65f6b97
* Version Independent ID: f3033d7d-e123-57a2-7eab-0837c3d9c8c0
* Content: [az network vpn-connection](https://docs.microsoft.com/en-us/cli/azure/network/vpn-connection?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S168

**Comment by MyronFanQiu** [comment]
@Make-Make Hi. Could you share the context or related documentation about IKEv1, IKEv2?

**Comment by MyronFanQiu** [comment]
Are you still meeting this issue?

**Comment by MyronFanQiu** [comment]
close this issue since no response. Feel free to open a new one.
