### ISSUE TITLE
Multiple tags

### ISSUE THREAD

**Issue by balazs92117** [Azure/azure-cli#12642]
At create: "Space-separated tags: key[=value] [key[=value] ...]. Use "" to clear existing tags." doesn't work. It craetes one long tag, it doen'st parse at space. It doesn't work with " " (space), "," or ", ".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d11bd3f4-efbf-691d-76a4-293ab97ad845
* Version Independent ID: a553d088-d838-f90f-d601-12fa312fe0cf
* Content: [az postgres server](https://docs.microsoft.com/en-us/cli/azure/postgres/server?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/postgres/server.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/postgres/server.yml)
* Service: **postgresql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy could you pls help to look at it? thanks

**Comment by qwordy** [comment]
`--tags` or  `--tags ""` can work.
What's your command and result?

**Comment by balazs92117** [comment]
Sorry, I figured out it's not a bug, it's just a stupid mistake, I misused "".
For anybody else who runs into this issue:
use `--tags "Key1=Value1" "Key2=Value2"` instead of `--tags "Key1=Value1 Key2=Value2"`

**Comment by qwordy** [comment]
Glad to see your problem is solved.
