### ISSUE TITLE
azure backup - enable VM backup with an recovery vault in different resource group 

### ISSUE THREAD

**Issue by ajay15283** [Azure/azure-cli#12643]
**Is your feature request related to a problem? Please describe.**
Enabling Backup for a VM with an recovery vault in different resource group. as it currently shows error as below 

az backup protection enable-for-vm \
    --resource-group <VM resourcegroup>  \
    --subscription <Sub ID> \
    --vault-name <Vault name> \
    --vm <VM name> \
    --policy-name DefaultPolicy

The Resource 'Microsoft.RecoveryServices/vaults/<Vault>' under resource group '<VM resourcegroup>' was not found.

**Describe the solution you'd like**
An option to mention the Vault resource group specifically 

**Describe alternatives you've considered**
It works from the portal 

**Additional context**

**Comment by yungezz** [comment]
thanks for reporting, we'll have a look

**Comment by pvrk** [comment]
How to backup a VM in a different resource group is already documented [here](https://docs.microsoft.com/azure/backup/quick-backup-vm-cli#enable-backup-for-an-azure-vm). Hope this helps. Please try us and let us know your response.

**Comment by pvrk** [comment]
@ajay15283 : How to backup a VM in a different resource group is already documented [here](https://docs.microsoft.com/azure/backup/quick-backup-vm-cli#enable-backup-for-an-azure-vm). Hope this helps. Please try us and let us know your response.

**Comment by ajay15283** [comment]
Thank you , it works with the mentioned documented procedure

**Comment by pvrk** [comment]
Thanks for the confirmation. Closing the issue.
