### ISSUE TITLE
az sql server ad-admin create gives error

### ISSUE THREAD

**Issue by Raka74** [Azure/azure-cli#12640]
## Describe the bug

az sql server ad-admin create -g {} -s {} -u {} -i {}`  - doesnt work , below error is displayed.

**Command Name**
`az sql server ad-admin create`

**Errors:**
```
create_or_update() missing 1 required positional argument: 'parameters'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 306, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 493, in default_command_handler
    return op(**command_args)
cli/command_modules/sql/custom.py, ln 2074, in server_ad_admin_set
    properties=kwargs)
TypeError: create_or_update() missing 1 required positional argument: 'parameters'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sql server ad-admin create -g {} -s {} -u {} -i {}`

## Environment Summary
```
Linux-4.15.0-1071-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0

Extensions:
storage-preview 0.2.8

```

**Comment by yonzhan** [comment]
sql

**Comment by skwasiborski** [comment]
The issue seems to be caused bu wrong argument name in /azure/cli/command_modules/sql/custom.py
line 2074 should be:
parameters=kwargs instead of the current properties=kwargs

**Comment by jaredmoo** [comment]
Fixed by #12541 . Thank you!

**Comment by venkatrajupalepu** [comment]
I'm facing the same issue. Is this in production?

**Comment by jaredmoo** [comment]
No, it's not released yet :( next release is https://github.com/Azure/azure-cli/milestone/84
