### ISSUE TITLE
Documentation for "az vm user delete" should say home directory is also deleted

### ISSUE THREAD

**Issue by jasonzio** [Azure/azure-cli#12652]
The `az vm user delete` command, when directed to a Linux VM, will also delete the user's home directory. The documentation should clarify this. (See #12649 )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0474c5a5-4231-0e39-f63f-f7bc05cb7797
* Version Independent ID: 22ea94c8-cc6f-97aa-77b1-4ffca845807e
* Content: [az vm user](https://docs.microsoft.com/en-us/cli/azure/vm/user?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
thansk for the reporting the issue and PR!

**Comment by yungezz** [comment]
The doc PR merged, close the issue
