### ISSUE TITLE
[Depth][JEDI] Databricks network isolation support

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#12655]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Databricks

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
Databricks will support network isolation, needs support it in Azure CLI.
rough timeline:
•	5/31 for CMDLet to have preview
•	6/30 for GA

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
Swagger not  ready yet.

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

**Comment by yungezz** [comment]
JEDI related ask

**Comment by yungezz** [comment]
this is postponed to Aug.

**Comment by bim-msft** [comment]
Pending due to Swagger not ready.
