### ISSUE TITLE
[Depth][JEDI]  DataBricks CMK support

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#12654]
**Resource Provider**
What is the Azure resource provider your feature is part of?
DataBricks
**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
Databricks will support CMK, rough timeline now:
•	5/31 for CMDLet to have preview
•	6/30 for GA

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

**Comment by yungezz** [comment]
JEDI related ask

**Comment by yungezz** [comment]
move it earlier, this is expected before May 15.

**Comment by fengzhou-msft** [comment]
PR submitted: https://github.com/Azure/azure-cli-extensions/pull/1603
