### ISSUE TITLE
Improve table output for Blobs

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#1266]
Currently:
```
$ az storage blob show -c democontainerjrs -n MyFile.gif 
Name
----------
MyFile.gif
```

Desired:
```
$ az storage blob show -c democontainerjrs -n MyFile.gif 
Name        BlobType    Length
---------- ----------- ------------ 
MyFile.gif  BlockBlob  30,639,408
```

Also for discussion, what about showing the copy id, which will give interactive users an easy way to see if there are outstanding operations.

**Comment by tjprescott** [comment]
You can generalize this issue as all of the storage data plane commands have crummy table outputs because of the structure of the returned storage objects. However, if we start writing callables for our table outputs, we will start seeing more issues created related to --query. cc/ @dekerebekoe

**Comment by derekbekoe** [comment]
For the other commands that do use callables for better table output, we haven't seen any feedback saying it's difficult to use with `--query` so far.
It could suggest it's not an issue for users.

**Comment by mayurid** [comment]
@derekbekoe and @tjprescott : We should do a quick look through and see if we can make the table output a little more friendly. I think as usage increases we may see more feedback here.
