### ISSUE TITLE
az aks update   --api-server-authorized-ip-ranges {}   results in "Changing enablePrivateCluster is not allowed. It can only be set while creating the cluster."

### ISSUE THREAD

**Issue by kevinwedwards** [Azure/azure-cli#12669]
## Describe the bug
Since Private AKS clusters went GA, we're unable to set --api-server-authorized-ip-ranges.  upon doing so we get an error saying we can't enablePrivateCluster.  Our cluster is public, and we're not attempting to enable a private cluster. 

**Command Name**
`az aks update`

**Errors:**
```
Operation failed with status: 'Bad Request'. Details: Changing enablePrivateCluster is not allowed. It can only be set while creating the cluster.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update -g {} -n {} --api-server-authorized-ip-ranges {} --verbose`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6

azure-cli 2.2.0

```

**Comment by yungezz** [comment]
thanks for reporting, we're routing to appropriate team to have a look.

**Comment by kevinwedwards** [comment]
My boss jun ran this with CLI v 2.1.0 and it didn't fail, succeeded and returned JSON.  I'd upgraded my CLI on Monday morning, to test out creating a Private AKS cluster....   I'm near certain it's related to v2.2.0 CLI.

**Comment by kevinwedwards** [comment]
test

**Comment by kevinwedwards** [comment]
We first noticed it on the 18.04 build agent in AzDevOps, 

18hrs ago the 'included software' documentation was updated ([see here](https://github.com/actions/virtual-environments/commit/0ddeb1ac4b2e81f45ba752d49ec5825b77141d40#diff-43bac3def16599ef5b79ea8b7d9e0a9a
))

About as close to 100% sure as I can be that it's a bug with CLI 2.2 issue and the "az aks update" command.

**Comment by jluk** [comment]
Thanks @kevinwedwards for the report, we're looking into it. cc @feiskyer

**Comment by feiskyer** [comment]
Fixed by https://github.com/Azure/azure-cli/pull/12589, pending a new release of CLI

**Comment by kevinwedwards** [comment]
Also a work around is here:
https://github.com/Azure/AKS/issues/1519

**Comment by Jen7714** [comment]
Looks like it's been fixed with the new CLI release. Closing for now.
