### ISSUE TITLE
az vmss encryption enable fails with azure-cli version 2.2.0 but works with version 2.0.78

### ISSUE THREAD

**Issue by shannawaz** [Azure/azure-cli#12672]
AZ cli versions -    2.2.0

**Describe the bug**
az vmss encryption enable fails with azure-cli version 2.2.0 but works with version 2.0.78
With  2.2.0 ,  you get the following error
cli.azure.cli.core.util : The value of parameter type is invalid.
The value of parameter type is invalid.

**To Reproduce**
Follow https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/disk-encryption-cli 

**Expected behavior**
vmss enable should encrypt hard disks

**Environment summary**
shnawa@MININT-JPHNAD7:~/.ssh$ az --version
azure-cli                          2.2.0

command-modules-nspkg              2.0.3
core                               2.2.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
aks-preview                       0.4.27

Python location '/opt/az/bin/python3'
Extensions directory '/home/shnawa/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Mar  6 2020, 14:41:24)
[GCC 7.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Additional context**

**Comment by yonzhan** [comment]
@qwordy please take a look.

**Comment by axelgMS** [comment]
Looks like Azure CLI version 2.2.0 forgot to pass the extension's type to the underlying Resource Provider.

eg. with CLI 2.1.0
        _"extensions": [
          {
            "name": "customScript",
            "properties": {
              "autoUpgradeMinorVersion": true,
              "publisher": "Microsoft.Azure.Extensions",
              **"type": "CustomScript",**
              "typeHandlerVersion": "2.0",
              "settings": {"commandToExecute":"echo testing"}
            }_



and with CLI 2.2.0
        _"extensions": [
          {
            "name": "customScript",
            "properties": {
              "autoUpgradeMinorVersion": true,
              "publisher": "Microsoft.Azure.Extensions",
              "typeHandlerVersion": "2.0",
              "settings": {"commandToExecute":"echo testing"}
            }_

**Comment by qwordy** [comment]
Similar issue: #12594

**Comment by qwordy** [comment]
Azure CLI 2.3.0 is released. It fixes this issue. Download it and have a try. Close the issue now.
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest
