### ISSUE TITLE
[Breadth Coverage] Onboard Datashare Commands

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-cli#12678]
**Spec Link**
https://microsoft.sharepoint.com/:w:/t/AzureManagementExperience/EQ-hQ0oBQv9Hsplk-sfJ97kBWBXiZR4D9_FEcX3pGTJ5MA?e=LLw4Go

**ADO Work Item Link**
https://dev.azure.com/azure-mgmt-ex/Onboarding/_boards/board/t/Onboarding%20Team/Features/?workitem=152

**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.DataShare

**Description of Feature or Work Requested**
Support Azure CLI commands for Datashare

**Minimum API Version Required**
Microsoft.DataSagre 2019-11-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datashare/resource-manager/Microsoft.DataShare/stable/2019-11-01/DataShare.json

**Comment by yonzhan** [comment]
Datashare
