### ISSUE TITLE
Az Login Throws error when reading .DER encoded certificate

### ISSUE THREAD

**Issue by pbstrein** [Azure/azure-cli#12673]
## Describe the bug
When logging in as a service principal and using a certificate, if a .DER encoded file is given (for example, .pfx) a error gets thrown, with no good description of what went wrong (for example, it needs to be in .PEM encoding and not .DER.)

**Command Name**
`az login`

**Errors:**
```
'charmap' codec can't decode byte 0x90 in position 98: character maps to <undefined>
Traceback (most recent call last):
pip-install-umfcm_n2\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 654, in _run_job
Temp\pip-install-umfcm_n2\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 631, in _run_job
cli\core\commands\__init__.py, ln 306, in __call__
azure\cli\core\__init__.py, ln 485, in default_command_handler
cli\command_modules\profile\custom.py, ln 147, in login
azure\cli\core\_profile.py, ln 202, in find_subscriptions_on_login
azure\cli\core\_profile.py, ln 1021, in __init__
CLI2\lib\encodings\cp1252.py, ln 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 98: character maps to <undefined>
```

## To Reproduce:

Login using a service principal and a .DER encoded certificate (eg .pfx.)
- `az login --service-principal --username <app Id> --tenant <tenant Id> --password "/path/to/cert.pfx"`

## Expected Behavior
The certificate should be able to be read. At the very least, a better error should be thrown stating that the certificate is in .DER encoding, and should be in .PEM encoding. 

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.76 *

```

**Comment by yungezz** [comment]
hi @arrownj could you pls have a look? thanks.
