### ISSUE TITLE
Unable to create AKS cluster using cloudshell

### ISSUE THREAD

**Issue by clarkezone** [Azure/azure-cli#12675]
## Describe the bug
Following the steps in the book k8s up and running to create a kube cluster on Azure.  Unclear what's wrong based on the error.  If I do the same thing using the Azure CLI installed locally in WSL everything works OK hence this looks like a cloudshell issue.

**Command Name**
`az aks create`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group={} --name={} --generate-ssh-keys`

## Environment Summary
```
Linux-4.15.0-1071-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0

```

**Comment by yungezz** [comment]
thanks for reporting, routing to appropriate team

**Comment by jluk** [comment]
This looks like an issue to call the cloud shell MI endpoint, @yungezz could you ping the cloud shell team?

**Comment by yungezz** [comment]
HI @arrownj could you pls have a look? thanks.

**Comment by jiasli** [comment]
Possibly similar to https://github.com/Azure/azure-cli/issues/11749#issuecomment-570975762

`400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token` is a known issue of Cloud Shell that it intermittently fails with this error.

To solve it, please use Azure CLI on a local machine or run `az login` in Cloud Shell and retry the command.

**Comment by arrownj** [comment]
Close this first, we will track this Cloud Shell issue in #11749 .
