### ISSUE TITLE
Warning (to stderr) about a future (non-existent) argument being required

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-cli#12697]
You guys have added this warning:

`WARNING: The record set doesn't exist and is automatically created. In the future, an extra argument will be supported to confirm this auto creation.`

Which appears when we run `az network dns record-set txt add-record ...` to add a new record.

This broke our pipeline because it's written to `stderr`.  

It's no *big* deal - we just run it again and it's fine.  And easily workaroundable with a redirect to /dev/null or /some-file.  

But... there doesn't seem to be an argument at all to silence the warning, right now.  Seems there should be.  Guess it's coming "In the future", as the warning says :D

**Comment by yonzhan** [comment]
add to S168

**Comment by jiasli** [comment]
We have introduced `--only-show-errors` to prevent writing to `stderr`. Please see https://github.com/Azure/azure-cli/pull/12604 for details.
