### ISSUE TITLE
generate-sas needed Contributor role

### ISSUE THREAD

**Issue by ghstahl** [Azure/azure-cli#12695]
## Describe the bug
I created an app registration via AD.  I assigned the role: Storage Blob Data Contributor at the container and account level.    I received the permissions error. 

```bash
az login --service-principal --username <redacted> --password <redacted> --tenant <redacted> 

EXPIRE=$(date -u -d "1 day" '+%Y-%m-%dT%H:%M:%SZ')
START=$(date -u -d "-1 day" '+%Y-%m-%dT%H:%M:%SZ')
 
ACCOUNT="stsecureupload"
CONTAINER="intake"
SAS=$(az storage container generate-sas --account-name "$ACCOUNT" --name "$CONTAINER" --start "$START" --expiry "$EXPIRE" --https-only --permissions acdlrw --auth-mode login --as-user)

SAS=$(sed -e 's/^"//' -e 's/"$//' <<<"$SAS")
echo $SAS 

```

I then assigned the Contributor Role to the App Registration and then it finally created a SAS.

**Command Name**
`az storage container generate-sas`

**Errors:**
```
You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container generate-sas --account-name {} --name {} --start {} --expiry {} --https-only --permissions {} --auth-mode {} --as-user`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.78 *

Extensions:
azure-devops 0.16.0

```

**Comment by zhoxing-ms** [comment]
The App Registration as service principal is a kind of Azure AD security principal. To request the user delegation key, a security principal must be assigned the `Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey action.` The following built-in RBAC roles include the `Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey action`, either explicitly or as part of a wildcard definition:
>Contributor
Storage Account Contributor
Storage Blob Data Contributor
Storage Blob Data Owner
Storage Blob Data Reader
Storage Blob Delegator

If the security principal is assigned any of the built-in roles listed above, or a custom role that includes the `Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey action`, at the level of the storage account, the resource group, or the subscription, the security principal will be able to request the user delegation key.

Therefore, no matter App Registration is given the role of `Contributor` or `Storage Blob Data Contributor`, as long as `Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey action` permission is given, so the user delegation sas can be generated.

**Comment by zhoxing-ms** [comment]
Therefore, no matter App Registration is given the role of `Contributor` or `Storage Blob Data Contributor`, as long as `Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey action` permission is given, the user delegation sas can be generated. 

@ghstahl May I ask did you give App Registration the role of `Storage Blob Data Contributor` when this problem arises? You can use the command `az role assignment list --role 'Storage Blob Data Contributor'` to have a check~

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
