### ISSUE TITLE
Feature request: Auto-shutdown

### ISSUE THREAD

**Issue by evandropomatti** [Azure/azure-cli#12701]
**Is your feature request related to a problem? Please describe.**
I am unable to set auto-shutdown schedule when creating a VM from Azure CLI.

**Describe the solution you'd like**
The possibility to create a VM with auto-shutdown and edit the auto-shutdown from Azure CLI.

Something like this:

```s
az vm create -n  -g MyResourceGroup --image UbuntuLTS --auto-shutdown-schedule ... --auto-shutdown-timezone ...
```
**Describe alternatives you've considered**
It would be nice to have it on the `create` command creating a dedicated command for it would be OK too.

**Comment by yonzhan** [comment]
add to S169

**Comment by evandropomatti** [comment]
Community team:

Please check issue #7234 as it is older and has more support.
Somehow it does not have the "Feature Request" label, it got removed in December.
I suggest adding the correct labels to that issue and closing this one.

**Comment by qwordy** [comment]
Portal has an auto-shotdown feature for VM. It calls https://management.azure.com/subscriptions/.../resourcegroups/.../providers/Microsoft.DevTestLab/schedules/shutdown-computevm-vm1?api-version=2018-10-15-preview
https://azure.microsoft.com/en-us/services/devtest-lab/
I think it's an useful feature.

**Comment by qwordy** [comment]
I drafted a PR for this feature.

**Comment by qwordy** [comment]
This feature is available in the latest Azure CLI verison. Feel free to try it and feedback.

**Comment by evandropomatti** [comment]
@qwordy which version number? I looked up release notes for 2.5.1 (latest, April 30th) and it doesn't list such change.

https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#azure-cli-release-notes

**Comment by qwordy** [comment]
Sorry. It will be in next release on 05/19/2020.
The PR is merged on April 27. 2.5.1 is released on April 30. I thought it is in 2.5.1. But in fact it is not.
