### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'reserved'

### ISSUE THREAD

**Issue by Elthas17** [Azure/azure-cli#12700]
## Describe the bug

Hi,

trying to run the hello world github code of the following tutorial https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python?tabs=bash , with a app service created manually in portal.azure

the command az webapp up recognizes it is an exising app service (notice the typo 'exits') 

```
Webapp {appname} already exits. The command will deploy contents to the existing app
```
**Command Name**
`az webapp up`

**Errors:**
```
'NoneType' object has no attribute 'reserved'
Traceback (most recent call last):
Temp\pip-install-6e754znd\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 652, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 55, in _polish_bad_errors
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 485, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 2811, in webapp_up
AttributeError: 'NoneType' object has no attribute 'reserved'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- create an app service in azure portal with same environment and app name as used in commands below
- `az webapp up --sku {} -n {} -l {}`

## Expected Behavior
the https://github.com/Azure-Samples/python-docs-hello-world running in the app service

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.74 *

```

**Comment by yungezz** [comment]
thanks for reporting, routing to appropriate team

**Comment by panchagnula** [comment]
Please re-try with latest version of CLI we added validation checks to az webapp up so you shouldn't see null validation errors.

**Comment by Paprika-a11y** [comment]
Did this problem solved?
