### ISSUE TITLE
docker run -it mcr.microsoft.com/azure-cli does not work on Windows Mode Docker Container

### ISSUE THREAD

**Issue by Astersss** [Azure/azure-cli#12707]
**Is your feature request related to a problem? Please describe.**
I tried to install Azure CLI on docker with Windows Mode not Linux mode using: docker run -it mcr.microsoft.com/azure-cli and it throws error: C:\Program Files\Docker\Docker\resources\bin\docker.exe: image operating system "linux" cannot be used on this platform.

**Describe the solution you'd like**
Any command line for installing Azure CLI on Windows mode container?

**Describe alternatives you've considered**
Any other way to install Azure CLI on Windows mode container

**Additional context**
N/A

**Comment by yungezz** [comment]
HI @fengzhou-msft could you pls have a  look? thanks.

**Comment by fengzhou-msft** [comment]
@Astersss the image is for linux. For windows, we have the [dockerfile](https://github.com/Azure/azure-cli/blob/dev/Dockerfile.nanoserver), but we don't release the image built on that. You can build it by yourself.
