### ISSUE TITLE
[Breadth Coverage] Onboard OperationsManagement Commands

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#12706]
**Spec Link**
https://microsoft.sharepoint.com/:w:/t/AzureManagementExperience/EUNqd7JD34xNhxzKqbsMQ1sBqk305EwnAfgfZpv6yuC5vw?e=BkPS5O

**ADO Work Item Link**
https://dev.azure.com/azure-mgmt-ex/Onboarding/_workitems/edit/98

**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.OperationsManagement 

**Description of Feature or Work Requested**
Support Azure CLI commands for OperationsManagement 

**Minimum API Version Required**
Microsoft.OperationsManagement 2015-11-01-preview

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/operationsmanagement/resource-manager/Microsoft.OperationsManagement/preview/2015-11-01-preview

**Python SDK Link**
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/operationsmanagement/azure-mgmt-operationsmanagement/azure/mgmt

**Target Date**
04/21/2020

**Addtional context**
We'll use [autorest.az](https://github.com/Azure/autorest.az/blob/master/doc/01-authoring-azure-cli-commands-v1.md) from code gen team to auto-generate the code first and may need update some code manually if the generated code doesn't meet your requirements.

**Comment by yonzhan** [comment]
add to S168
