### ISSUE TITLE
Rerunning `az aks create` with updated service principal fails

### ISSUE THREAD

**Issue by GeeWee** [Azure/azure-cli#12713]
## Describe the bug
I have a script that creates a service principal and a AKS cluster.
It fails when I run it the second time.
Seeing as the Azure CLI is supposed to be idempotent, I would expect the following to work.

- I update an existing service principal with the same name:
`az ad sp create-for-rbac --skip-assignment --name "http://sp-foo-bar"`
This seems to work, as the azure cli responds with:
`Found an existing application instance of "c3d04f78-***(truncated)-517157647687". We will patch it`

I then expect when I call `aks create` on an existing cluster with my new service principal secret, that it will do the update steps necessary to rotate the credentials. What it does is, it throws an error:

```
Operation failed with status: 'Bad Request'. Details: Changing property 'servicePrincipalProfile.secret' is not allowed.
```

Other people seem to have the same issues with arm templates here: https://github.com/MicrosoftDocs/azure-docs/issues/39788#issuecomment-551861676

**Command Name**
```
az ad sp create-for-rbac --skip-assignment --name "http://sp-foo-bar"

az aks create -n mycoolcluster `
    --generate-ssh-keys `
    --attach-acr ${ContainerRegistryName} `
    --location ${Location} `
    --vnet-subnet-id ${SubnetId} `
    --service-principal ${ServicePrincipalAppId} `
    --client-secret ${ServicePrincipalClientSecret} `
    -o none
```

**Errors:**
```
Operation failed with status: 'Bad Request'. Details: Changing property 'servicePrincipalProfile.secret' is not allowed.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create an AKS cluster with a custom provided service principal
- Update the service principal with `az ad sp create`
- Call `aks create` with the updated service principal

## Environment Summary
```
Linux-5.5.9-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
Python 3.7.6

azure-cli 2.2.0

Extensions:
application-insights 0.1.4

```

**Comment by yungezz** [comment]
thanks for reporting, routing to appropriate team

**Comment by krowlandson** [comment]
I've come across this issue too, but after researching this I came to the conclusion that this may be by design. You appear to have already followed the best practice of creating a custom SPN rather than relying on `az aks create` but this command doesn't provide the ability to change the SPN.

The following article provides the recommended approach to update or rotate the credentials for Azure Kubernetes Service (AKS):
https://docs.microsoft.com/en-us/azure/aks/update-credentials

As long as you follow a suitable method to generate a new secret for your SPN, you can use the following command to update your cluster configuration:

```
az aks update-credentials \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --reset-service-principal \
    --service-principal $SP_ID \
    --client-secret $SP_SECRET
```

Once updated, you can delete the old secret.

During my research, I also tried generating secrets using the Azure Portal. This uncovered an unexpected issue where the auto-generated value often started with a non-alphanumeric character causing the above to fail. I'd recommend using the approach documented above as it will be much more robust.

As an alternative, have you considered using a Managed Identity? This greatly simplifies setup and operations, and even handles key rotation automatically:
https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

**Comment by GeeWee** [comment]
I think it's true that it's by design. It does mention how you should create the credentials.

However with the design goal that the azure cli is idempotent, I would expect that I could run these snippets of code twice, and not get an error. I would assume it would translate the `create` commands into the required update commands to make that work.

**Comment by brandonmartinez** [comment]
I've also run into this same issue, but when deploying an ARM template. I can run an ARM template to create the resources, but if I need to rerun the template (e.g. to update any settings in my cluster/nodes), it will fail even if the SPN hasn't changed. Currently, I would need to have to two ARM templates (one with and one without the SPN stuff).

**Comment by VincentVerweij** [comment]
@brandonmartinez I have the exact same issue, but I don't understand what you mean by 
> Currently, I would need to have to two ARM templates (one with and one without the SPN stuff).

Could you elaborate on this? So you have an ARM template where you don't specify `servicePrincipalProfile` and a second one where you do. But that second one will still fail, as it can't cope with the update of the service principal with the error stated author's message.

**Comment by brandonmartinez** [comment]
@VincentVerweij I was just saying that if I wanted to automate my deployments, I would need two templates: one for initial create, and one for updates. Ideally, I just want the one template.

**Comment by tonystz** [comment]
Is anyone has solution via ARM avoid the error "Changing property 'servicePrincipalProfile.secret' is not allowed", when update?

**Comment by cwe1ss** [comment]
You could change the script in a way that it stores the service principal password in Azure Key Vault when the service principal is created. Subsequent calls to the script should then just load the password from Key Vault.

**Comment by navba-MSFT** [comment]
@GeeWee Apologies for the late reply. Could you please try the plan suggested [here](https://github.com/MicrosoftDocs/azure-docs/issues/39788#issuecomment-536779280) ? Also this issue thread is open for quite sometime. Please let me know if you still need any assistance on this. Awaiting your reply.

**Comment by GeeWee** [comment]
Ah, sorry I'm not using AKS anymore here two years later.. If you consider this a question, feel free to close it. If you consider it a bug feel free to close it.

**Comment by navba-MSFT** [comment]
@GeeWee The plan suggested [here](https://github.com/MicrosoftDocs/azure-docs/issues/39788#issuecomment-536779280) should help in this scenario. We will now proceed with closure. If you face the similar issue with most recent version of CLI, feel free to reopen this thread. We would be happy to assist you further.
