### ISSUE TITLE
Azure-cli install on Codeship.com failing missing Public Key.

### ISSUE THREAD

**Issue by devallish** [Azure/azure-cli#12714]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
While running install on Codeship.com we are seeing missing public key error.
Below are logged steps around error message.

Get:13 https://dl.yarnpkg.com/debian stable/main amd64 Packages [9,953 B]
**Err:3 https://cli-assets.heroku.com/branches/stable/apt ./ InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5DC22404A6F9F1CA**
Get:15 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease [46.3 kB]
Get:16 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease [15.4 kB]

Get:52 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [10.3 kB]
Get:53 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Translation-en [4,664 B]
Reading package lists... Done
**W: GPG error: https://cli-assets.heroku.com/branches/stable/apt ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5DC22404A6F9F1CA
E: The repository 'https://cli-assets.heroku.com/branches/stable/apt ./ InRelease' is not signed.**
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**To Reproduce**
This command is used as pre build step 
sudo apt-get update && sudo apt-get install azure-cli

**Expected behavior**
To install the azure-cli. Which is has been doing fine for months now.

**Environment summary**
Codeship.com

**Additional context**

**Comment by yungezz** [comment]
HI @fengzhou-msft could you pls have a  look? thanks.

**Comment by fengzhou-msft** [comment]
@devallish the error seems to be caused by the https://cli-assets.heroku.com/branches/stable/apt repo.  There's an existing issue https://github.com/heroku/cli/issues/497 which was referenced multiple times recently. 

azure-cli is not from this repo. Please follow our [installation instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest) for Ubuntu. You may want to temporarily disable the above repo or wait for their fix.
