### ISSUE TITLE
Add command to az policy to trigger on-demand evaluation scan

### ISSUE THREAD

**Issue by fawohlsc** [Azure/azure-cli#12718]
**Is your feature request related to a problem? Please describe.**
When developing Azure Policies, it can take up to 30 min for a policy assignment to be applied to a defined scope and even some more time for the evaluation cycle to be processed (see [Evaluation triggers](https://docs.microsoft.com/en-us/azure/governance/policy/how-to/get-compliance-data#evaluation-triggers)). Therefore, developers usually rely on triggering [on-demand evaluation scans](https://docs.microsoft.com/en-us/azure/governance/policy/how-to/get-compliance-data) by calling the REST API to verify the Azure Policy.

**Describe the solution you'd like**
Instead of low-level REST API calls, it would be much more convenient to trigger the on-demand policy evaluation via Azure CLI, i.e. '''az policy evaluate --scope ...'''

**Describe alternatives you've considered**
An alternative would be to add this feature to the [Azure CLI Extensions](https://github.com/Azure/azure-cli-extensions)

**Additional context**
None

**Comment by yonzhan** [comment]
add to S168

**Comment by fawohlsc** [comment]
Based on the docs of [on-demand evaluation scans](https://docs.microsoft.com/en-us/azure/governance/policy/how-to/get-compliance-data#on-demand-evaluation-scan), there is the possibility to retrieve the status of the on-demand evaluation scan. A REST API GET command to `https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.PolicyInsights/asyncOperationResults/{ResourceContainerGUID}?api-version=2018-07-01-preview`  
returns a 202 Accepted while the evaluation is ongoing. When the evaluation scan has completed, it returns a 200 OK status. The body of a completed scan is a JSON response with the status:
```
{
    "status": "Succeeded"
}
```
Hence it might make a lot of sense to include a `--wait` flag in the `az policy evaluate --scope ...` command.

**Comment by zhoxing-ms** [comment]
@calecarter Hi, please pay attention to this issue. Here are the same requirements for adding `https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.PolicyInsights/asyncOperationResults/{ResourceContainerGUID}?api-version=2018-07-01-preview` to the Python SDK.
After that I will support this feature in CLI.

**Comment by kenieva** [comment]
Hi zhoxing-ms, we don't have this in the upcoming plans due to other features in the pipeline. One of which is to improve the time for compliance evaluation to surface. With this exciting change, there will be little to no need to trigger an evaluation. Thanks!
