### ISSUE TITLE
Zypper error after Installing Python3.6 on SLES12SP4 

### ISSUE THREAD

**Issue by ajay15283** [Azure/azure-cli#12719]
Hello,

After installing python3.6.9 as mentioned in the document https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper?view=azure-cli-latest 

zypper failed to retrieve the metadata and forcing cloudregistration failed with SSL error . Other systems without Python3.6.9 doesn't have this problem

**Comment by ajay15283** [comment]
[azurecli-error.docx](https://github.com/Azure/azure-cli/files/4371204/azurecli-error.docx)

**Comment by yonzhan** [comment]
@fengzhou-msft  please take a look.

**Comment by fengzhou-msft** [comment]
@ajay15283 can you provide more information about your system? Is it a VM? The error seems to be in registercloudguest, which is not part of azure-cli.

**Comment by ajay15283** [comment]
The VM is hosted on azure and its a SUSE machine to be specific urn = SUSE:SLES:12-SP4:2019.11.13. 

"registercloudguest" is a cloud init automation which registers the VM with SUSE SMT servers once the VM is provisioned and after the installation of Python3.6 and few other libraries i faced connection issue to the SMT servers and execution of cloud init script also failed with SSL errors .Recently found "urllib3" library is causing the SSL problem .As it happened after installing 3.6 I opened this issue but it seems to be a specific library which is causing the issue so this case can be closed 

Please suggest if we can install Python3.6 in virtual environment 

Thanks

**Comment by fengzhou-msft** [comment]
It looks like some networking issue or SUSE configure issue of the VM. `zypper fresh` alos failed. I have created a new SLES12SP4 VM and got similar errors without installing python 3.6.

**Comment by fengzhou-msft** [comment]
Close as not caused by azure cli.
