### ISSUE TITLE
Failed to purge a secret right after it was removed

### ISSUE THREAD

**Issue by t3mi** [Azure/azure-cli#12722]
## Describe the bug

**Command Name**
`az keyvault secret purge`

**Errors:**
```
Secret is currently being deleted.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `id=$(az keyvault secret delete -n 'test-secret' --vault-name 'test-vault' --query recoveryId --output tsv) && az keyvault secret purge --id $id`

## Expected Behavior
Secret purged successfully.

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5

azure-cli 2.2.0

```
## Additional Context
Same issue with certificates.
```
Certificate is currently being deleted.
```

**Comment by yungezz** [comment]
hi @bim-msft could you pls have a look?

**Comment by bim-msft** [comment]
Hi @t3mi , based on my experience, you should wait several seconds before `purge` operation since the `delete` operation is an async operation inside the backend.

This is our scenario test code for delete/purge, we use a `time.sleep` here:
https://github.com/Azure/azure-cli/blob/b8449a869207f26eec7ec3a768b67f46b5d5a7da/src/azure-cli/azure/cli/command_modules/keyvault/tests/latest/test_keyvault_commands.py#L1056-L1075

**Comment by t3mi** [comment]
Thanks, I'm using that as a workaround. But any chance that could be updated to a blocking operation? So that response for 'delete' could be process right away.

**Comment by bim-msft** [comment]
> Thanks, I'm using that as a workaround. But any chance that could be updated to a blocking operation? So that response for 'delete' could be process right away.

@t3mi This is decided by service back-end implementation which is owned by another team, currently Azure CLI can do nothing about this (Actually we can do a sleep in `delete`, but it will impact the performance).
How about disable the `soft-delete`? If it was disabled, you don't need to `purge` anymore, thanks!

**Comment by bim-msft** [comment]
If there are updates on service implementation about this, I will let you know. :-)

**Comment by codeayra** [comment]
@bim-msft now there is no option to disable soft-delete in key vault. so any solution to avoid sleep in the code/script?

**Comment by bim-msft** [comment]
@codeayra Unfortunately I think there is still no way to avoid sleeping.
May I know why you need to purge it immediately? It's fine to just leave it in the "Recycle bin".

**Comment by hg-test3** [comment]
I want to replace the secret, and the only option is to first delete it and then purge it and set it with new value. I do not want to make multiple version of the same secret, just want to replace it. Any other way to do it?

**Comment by se-kolb** [comment]
Am doing this through Python SDK - same problem - we are automating destruction of vm's in parallel and it is a blocker.

**Comment by codeayra** [comment]
Unfortunately, there is no way  to solve this. the only way is to either wait/sleep and check again if its purged completely or poll it continuously to check if it purged completely and then do your next operation.
Something like this.

` @Async
    public Object deleteAndPurgeSecret(KeyVaultClient client, String keyVaultUrl, String secret) {
        try {
            client.deleteSecret(keyVaultUrl, secret);
            boolean flag = true;
            long start_time = System.currentTimeMillis();
            long wait_time = 60000;
            long end_time = start_time + wait_time;
            // max wait for a minute for delete and purge.
            while (flag && System.currentTimeMillis() < end_time) {
                try {
                    client.purgeDeletedSecret(keyVaultUrl, secret);
                    flag = false;
                } catch (Exception e) {
                    //for older key vaults
                    if(e.getMessage().contains("NotSupported")) {
                        break;
                    }
                    log.error("Error {} purging secret {} trying again.", e.getMessage(), secret);
                }
            }
        } catch (Exception e) {
            log.error("Error {} deleting secret {}", e.getMessage(), secret);
        }
        return new Object();
    }`

**Comment by harmasingh** [comment]
Hi,

I am facing a similar issue in which I am using Az Powershell library to do KV operations.
I am deleting a secret using ` Remove-AzKeyVaultSecret -VaultName $XYZ -Name $Secret`
and purging it using `Remove-AzKeyVaultSecret -VaultName $XYZ -Name $Secret -InRemovedState`

and I am getting the error:

> Secret is currently being deleted.

Is there any command that returns the result only after the DELETE operation is completed?
I understand that it is an async operation in the backend, and if the above is not possible, what is the approximate number of retries I should execute and with how much sleep time? What is the SLA? Currently, I have 20 seconds of sleep with 5 retries, and once in a while I am still getting the error.
