### ISSUE TITLE
az aks upgrade fails with Error occurred in request

### ISSUE THREAD

**Issue by matthewdchambers** [Azure/azure-cli#12725]
**Describe the bug**
Upgrade from 1.11.8 to 1.13.12 using `az aks upgrade` fails with 

> request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/----/resourceGroups/----/providers/Microsoft.ContainerService/managedClusters/cluster?api-version=2019-11-01 (Caused by ResponseError('too many 500 error responses'))

**To Reproduce**
run `az aks upgrade  --resource-group rgroup --name name --kubernetes-version 1.13.12` on cluster currently running 1.11.8

**Expected behavior**
Cluster upgraded to 1.13.12

**Environment summary**

> azure-cli                          2.2.0
> 
> command-modules-nspkg              2.0.3
> core                               2.2.0
> nspkg                              3.0.4
> telemetry                          1.0.4
> 
> Python location '/usr/local/Cellar/azure-cli/2.2.0_1/libexec/bin/python'
> Extensions directory '/Users/---/.azure/cliextensions'
> 
> Python (Darwin) 3.8.2 (default, Mar 11 2020, 00:28:52) 
> [Clang 11.0.0 (clang-1100.0.33.17)]

**Comment by yungezz** [comment]
thanks for reporting, routing to appropriate team

**Comment by Jen7714** [comment]
Hello! Please try again with the latest Azure CLI version. Feel free to reopen an issue if it still doesn't work.
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest
