### ISSUE TITLE
Refresh page

### ISSUE THREAD

**Issue by wonderplayer** [Azure/azure-cli#12728]
If anybody besides me is using reset and wondering why secret doesn't appear, then please, refresh the secret page. It will appear only then as it turns out.
Spent too much time with this...
P.S. Might be good to add this as an instruction under reset command :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 364ccdfb-268e-08f0-a357-94a19c5213fd
* Version Independent ID: d2c1a19f-bfbd-b273-77e2-9fdb596181b5
* Content: [az ad app credential](https://docs.microsoft.com/en-us/cli/azure/ad/app/credential?view=azure-cli-latest#az-ad-app-credential-reset)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @arrownj could you ps have a look? thanks

**Comment by arrownj** [comment]
Hi @wonderplayer , @rloutlaw, do you mean the secret is to displayed in the output of `az ad app credential reset` ? If yes, there is actually the `password` property in the output, below is an example:

> PS D:\code\cli\azure-cli> az ad app credential reset --id 448488a7-becf-4d79-aa9e-8262f8******
{
  "appId": "448488a7-becf-4d79-aa9e-8262f8******",
  "name": "448488a7-becf-4d79-aa9e-8262f8******",
  "password": "P!CC;jw?F]p{;${I5P4n[T`[ge******",
  "tenant": "54826b22-38d6-4fb2-bad9-b7b93a******"
}

If it's not this case, could you please help provide us the exact commands you are using ? Thanks very much.

**Comment by wonderplayer** [comment]
Hi @arrownj, I meant in the interface. Command output is fine.
I was creating secrets and then moving between blades, but what I really needed is to refresh the page to see my newly created secret.

**Comment by arrownj** [comment]
> Hi @arrownj Xiaojian Xu FTE, I meant in the interface. Command output is fine.
> I was creating secrets and then moving between blades, but what I really needed is to refresh the page to see my newly created secret.

I'm not sure I understand your problem exactly. Are all these done with CLI commands? And what is 'refresh the page` ? Could you please help give a reproduce steps ? Thanks

**Comment by wonderplayer** [comment]
So, you can create a secret in Azure portal at http://portal.azure.com. There in the interface I see that no secrets are created for my app registration when I execute command. But, when I refresh the browser page, I see that it is created.

**Comment by arrownj** [comment]
Do you mean you create a secret via CLI but it's not shown in portal unless you refresh the browser ? Could you please provide the exact reproduce steps? What's the actual and expected behavior you have for CLI ? Thanks very much.

**Comment by arrownj** [comment]
Hi @wonderplayer , any feedback ?

**Comment by arrownj** [comment]
Hi @wonderplayer , will close this issue first as lacking of further feedback. You can reopen it or submit a new one if you still have problems with it. Thanks
