### ISSUE TITLE
Warnings should not be writton on stderr

### ISSUE THREAD

**Issue by qetza** [Azure/azure-cli#12735]
Currently warnings (preview feature, deprecated feature...) is written to stderr but those are not errors.

This behaviors can break scripts in powershell if we make them fail automatically if something is written to stderr.

Those outputs should be written to the standard output to avoid false error.

**Comment by yungezz** [comment]
thanks for reporting, this is a known issue, and there's a fix in underlying framework to fix it. @jiasli can share more detail

**Comment by jiasli** [comment]
We have added option `--only-show-errors` to disable warnings in https://github.com/Azure/azure-cli/pull/12604. We will release this version at 2020-04-31.
