### ISSUE TITLE
'central' is not in the 'az iot' command group

### ISSUE THREAD

**Issue by juliuszsielski** [Azure/azure-cli#12733]
# Describe the bug
**Command Name**
` az iot central app monitor-events --app-id <Application ID> --properties all`

**Error**
`az iot: 'central' is not in the 'az iot' command group`

# Expected behavior
Connect to IOTC instance and monitor all incoming messages.

**Environment summary**
`Windows 10, Powershell`
`azure-cli 2.2`

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by juliuszsielski** [comment]
Response on `az --version`
```
azure-cli 2.2.0

command-modules-nspkg 2.0.3
core 2.2.0
nspkg 3.0.4
telemetry 1.0.4

Extensions:
azure-cli-iot-ext 0.7.1
azure-cli-ml 1.0.85
azure-iot 0.9.1
```

**Comment by Jackbk** [comment]
Hi @juliuszsielski ,
The IoT CLI extension name as recently changed.  It looks like you have an old and a new version installed which may be conflicting.

Can you please try remove azure-cli-iot-ext ?

`az extension remove --name azure-iot`

**Comment by juliuszsielski** [comment]
I removed az cli and all dependencies and installed fresh ones. Then I add 
`azure-iot extension`
and run
`az iot central app monitor-events --app-id xxxxxxxxxxxxxxxxxxxxxxxxxxxx`

Now I got an error 
`Error 403.043.004.005 getting tokens. User principals must get tokens from the common tenant.`
I read that I need to set up my tenant. I did this but still I got the error above. I can see that my role in subscription is an user. Maybe this cause the problem?

**Comment by atilcock** [comment]
Had the same issue and determined it's because I have multiple subscriptions, after I ran "azure account set "  with the right subscriptionID it resolved the issue.

**Comment by navba-MSFT** [comment]
@juliuszsielski Apologies for the late reply. Could you please upgrade the Azure CLI to the [latest version ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and run the command mentioned [here](https://docs.microsoft.com/en-us/cli/azure/iot/central/diagnostics?view=azure-cli-latest#az-iot-central-diagnostics-monitor-events) ? Also this github issue is open for quite sometime now. So please let us know if you still require assistance on this ?  Awaiting your reply.

**Comment by juliuszsielski** [comment]
@navba-MSFT I am no longer support iot projects so I can't verify this. Thank you for your help.

**Comment by navba-MSFT** [comment]
@juliuszsielski Thanks for getting back. We will proceed with closure of this for now. If you need any further assistance, please feel free to reopen this issue. We would be happy to help you.
