### ISSUE TITLE
CloudShell & Azure CLI Azure Command Builder Concept

### ISSUE THREAD

**Issue by compusaurusrex** [Azure/azure-cli#12746]
One of my frustrations using CloudShell and PowerShell is that I often need to spend a significant amount of time researching the options and option values required to implement a command. This is frustrating because Azure should know and could make all of the command options and many of the option values, like VMs, NIC and disk names, resource groups and subscription IDs available for selection.

The CloudShell & PowerShell Azure Command Builder Concept would make it easier to quickly build command line commands which have the correct syntax and options selected on the first attempt, minimizing research required to collect available options and option values and multiple execution attempts with missing options or incorrect option values.

The concept would make primary and secondary options as well as option values available via popup menus.
[CloudShell & PowerShell Azure Command Builder Concept.pdf](https://github.com/Azure/azure-cli/files/4381691/CloudShell.PowerShell.Azure.Command.Builder.Concept.pdf)

**Comment by yonzhan** [comment]
@arrownj  please take a look.

**Comment by arrownj** [comment]
Hi @compusaurusrex , CLI has an interactive mode, it is similar to your requirements. You can try it with `az interactive`.

**Comment by yungezz** [comment]
hi @compusaurusrex thanks for the detail issue with mock up doc. The proposal is the `auto-complete` concept in Azure CLI today. You can use in on linux machines.

**Comment by arrownj** [comment]
Hi @compusaurusrex , I will close this issue first as there is no feedback for a long time. And your proposal can leverage current `az interactive` and auto-complete. You can reopen it or submit a new one. You can also email to azpycli@microsoft.com if further discussion is needed.
