### ISSUE TITLE
Typo in az aks create -h

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-cli#12745]
**Describe the bug**
az aks create -h, the output:

>     --nodepool-name                           : Node pool name, upto 12 alphanumeric characters.
>                                                 Default: nodepool1.

**Expected behavior**
It should be **_up to_**?

**Environment summary**
Windows

**Comment by yonzhan** [comment]
aks

**Comment by Jen7714** [comment]
This should be fixed! Closing for now.
