### ISSUE TITLE
No release for tricia?

### ISSUE THREAD

**Issue by shmink** [Azure/azure-cli#12758]
OS: Mint 19.3 tricia
Kernel: x86_64 Linux 5.3.0-42-generic

```
Err:12 https://packages.microsoft.com/repos/azure-cli tricia Release                                  
  404  Not Found [IP: 13.80.99.124 443]
...
E: The repository 'https://packages.microsoft.com/repos/azure-cli tricia Release' does not have a Release file.
```

Running `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash` gives me the above error.

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look.

**Comment by shmink** [comment]
Any update on this?

**Comment by fengzhou-msft** [comment]
@shmink Currently we don't have packages for Mint. Please use pip install or try a Ubuntu package: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#no-package-for-your-distribution

**Comment by shmink** [comment]
It's based upon Ubuntu 18.04. That version will work, is there any kind of symlink or forwarder you can do on your end?

**Comment by fengzhou-msft** [comment]
@shmink We could add extra logic for Mint in the script. How can I know which Ubuntu it is based on? I assume there are other Mint versions as well.

**Comment by shmink** [comment]
[Programatically](https://unix.stackexchange.com/questions/270199/which-version-of-ubuntu-is-my-linux-mint-installation-based-on)

Also, [this list](https://en.wikipedia.org/wiki/Linux_Mint_version_history#Release_history) normally helps me.

**Comment by shmink** [comment]
The command in the manual install process:
```
AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
    sudo tee /etc/apt/sources.list.d/azure-cli.list
``` 
The `lsb_release -cs` is the issue as it returns the codename for the distribution. Instead you could return the upstream release:
```
$ cat /etc/upstream-release/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

And with a bit of regex:
```
$ cat /etc/upstream-release/lsb-release | grep -Po 'DISTRIB_CODENAME=\K.*' 
bionic
```
---
I installed azure-cli simple with 
```
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main" |
    sudo tee /etc/apt/sources.list.d/azure-cli.list
```
for example.

**Comment by fengzhou-msft** [comment]
@shmink I can only access the tricia docker image and it does not have the `/etc/upstream-release/lsb-release` file. Instead I used this command: `cat /etc/os-release | grep -Po 'UBUNTU_CODENAME=\K.*'`. Can you confirm whether it works for your system as well?

**Comment by fengzhou-msft** [comment]
The script is updated. Please try with `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash` on tricia.

**Comment by artnkfv** [comment]
Hi.
The script does'n work for Mint Tricia 19.3 (the same error).
Solution of @shmink work.
