### ISSUE TITLE
MemoryError on up with large binary files

### ISSUE THREAD

**Issue by harals** [Azure/azure-cli#12759]
## Describe the bug
I'm trying to update an application which has some large ZIP-files to be served statically, e.g. 5 GB in total.

On update, the process runs for a few minutes, and then terminates with a "MemoryError".

**Command Name**
`az webapp up`

**Errors:**
```
Traceback (most recent call last):
Temp\pip-install-mjd5h3hf\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 603, in execute
azure\cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 652, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 55, in _polish_bad_errors
azure\cli\core\commands\__init__.py, ln 631, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 487, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 3033, in webapp_up
azure\cli\command_modules\appservice\custom.py, ln 369, in enable_zip_deploy
MemoryError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up -n {} -l {}`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.77

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@calvinsID can you check if we can repro this with up? Thanks

**Comment by navba-MSFT** [comment]
@harals Apologies for the late reply. Could you please refer this thread for the similar issue #12325 and let us know if the suggestion provided there helps? Awaiting your reply.
