### ISSUE TITLE
Not able to get access token from cloud shell for resource type oss-rdbms

### ISSUE THREAD

**Issue by wudong** [Azure/azure-cli#12757]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --resource-type oss-rdbms`
## Expected Behavior
receive the access token. 

## Environment Summary
```
Linux-4.15.0-1071-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0

```

**Comment by yonzhan** [comment]
add to S169

**Comment by jiasli** [comment]
This is a known issue that Cloud Shell doesn't accept `--resource-type oss-rdbms`. 

As a workaround, please use Azure CLI on a local machine or run `az login` in Cloud Shell and retry the command.

**Comment by maertendMSFT** [comment]
This should be fixed now.  I cannot repro, please close.
