### ISSUE TITLE
Ability to set blob tier directly on upload

### ISSUE THREAD

**Issue by tstibbs** [Azure/azure-cli#12766]
**Is your feature request related to a problem? Please describe.**
When uploading to archive storage, you have to first upload to standard storage, then move it to archive. Functionally, this works fine, but you pay for the initial write to standard storage and then pay to move to archive.

**Describe the solution you'd like**
It would be better if you could upload directly to archive storage, and avoid paying for the write to standard storage and just pay for the write to archive. This functionality would need to be available on both `upload` and `upload-batch`.

**Describe alternatives you've considered**
`upload` (though not `upload-batch`) does have a `--tier` option, but it only accepts values `P10, P20, P30, P4, P40, P50, P6, P60` and appears to be unrelated to the blob tier.

**Additional context**
Note that the equivalent powershell module's [Set-AzStorageBlobContent](https://docs.microsoft.com/en-us/powershell/module/az.storage/set-azstorageblobcontent) has a `-StandardBlobTier` option which allows you to specify `Archive`.

**Comment by yonzhan** [comment]
add to S169

**Comment by xyh1** [comment]
a. Should support access tier and rehydrate priority
az storage blob copy start 
az storage blob copy start-batch 

b. Should support access tier
az storage blob upload
az storage blob upload-batch

**Comment by zhoxing-ms** [comment]
@tstibbs 
Hi, I have submitted a PR #14333 that make the command `az storage blob upload` can support setting access tier for block blob, like:
```bash
--tier                         : The tier to be set on blob. For page blobs, supported on a
                                 premium storage account, valid values are P10, P20, P30, P4,
                                 P40, P50, P6, P60. For block blobs, supported on blob storage
                                 or general purpose v2 accounts, valid values are
                                 Hot/Cool/Archive.
```

However, for command `az storage blob upload-batch`, I personally think that there are not many scenarios where access tier needs to be set, because this must ensure that all the blobs uploaded in the same batch need the same access tier.
May I ask in what scenarios do you need command `az storage blob upload-batch` to support setting access tier? 
If there are not many such scenarios, I think we can support it later when there are more feedback from customers.

**Comment by tstibbs** [comment]
@zhoxing-ms thanks for looking at this. Regarding `upload-batch` I generally find that everything I upload in a batch is going to the same tier, so for me it makes sense to have the option there too. If uploading as a batch, it normally means I've got a load of files on disk that I want to transfer into a blob all in one go, and normally therefore the tier is likely to be the same. Specific use-cases I've had recently:

- Archiving files from an on-premise file server - thus I want to set the tier to 'archive' for all of them (and you can't set a blob to default to 'archive' so the only way is to set it when uploading).
- Uploading static assets for a website/cms - again, the whole upload tends to need the same tier (usually this would be hot I suppose, but for example if uploading assets for deprecated website functionality that is less frequently accessed you might want to set the tier to cool even though the container as a whole might be set to hot)

**Comment by Juliehzl** [comment]
HI @tstibbs , uploading with --tier is supported in cli extension `storage-blob-preview`. You could install with `az extension add -n storage-blob-preview` and try upload again. For `upload-batch`, we don't have support plan for limited bandwidth.
