### ISSUE TITLE
'az ad group member add' does not return any result

### ISSUE THREAD

**Issue by egeyer** [Azure/azure-cli#12767]
**Is your feature request related to a problem? Please describe.**
Most az cli commands that I've used so far return some sort of json object on success.  I've been using the presence of a valid json object to check for successful completion of the command in my automation scripts.  However, `az ad group member add` does not return anything even when the command is successful.  

**Describe the solution you'd like**
It would be nice if this command would return a json object on success to be consistent with other commands.

**Comment by yonzhan** [comment]
add to S169

**Comment by jiasli** [comment]
@egeyer, thanks for the feedback.

However, this is the design of AD Graph REST API [Add group members](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/groups-operations#add-group-members--) to return `204 No Content`:

Status Code | Description
-- | --
204 | No Content. Indicates success. No response body is returned.

If you run the command with `--debug`, you can see the actual REST request:

```
> az ad group member add -g testgroup --member-id 0d504196-1423-4569-9a6e-15149656f0ee --debug

msrest.http_logger : Request URL: 'https://graph.windows.net/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/groups/2cde37aa-6fd0-42ad-849a-33d06c0da145/$links/members?api-version=1.6'
msrest.http_logger : Request method: 'POST'
msrest.http_logger : Request headers:
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Accept': 'application/json'
...
msrest.http_logger : Request body:
msrest.http_logger : {"url": "https://graph.windows.net/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/directoryObjects/0d504196-1423-4569-9a6e-15149656f0ee"}

msrest.http_logger : Response status: 204
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
...
msrest.http_logger : Response content:
msrest.http_logger :
```
MS Graph API [Add member](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http#response) also has this behavior:

> ## Response
> If successful, this method returns a `204 No Content` response code. It does not return anything in the response body.

You may check the [exit code](https://github.com/Azure/azure-cli#exit-codes) to determine whether the command is successful.

```sh
# bash
echo $?

# cmd
echo %ERRORLEVEL%

# pwsh
echo $LastExitCode
```

You may also use [`az ad group member check`](https://docs.microsoft.com/en-us/cli/azure/ad/group/member?view=azure-cli-latest#az-ad-group-member-check):

```sh
az ad group member check -g testgroup --member-id 0d504196-1423-4569-9a6e-15149656f0ee

{
  "odata.metadata": "https://graph.windows.net/54826b22-38d6-4fb2-bad9-b7b93a3e9c5a/$metadata#Edm.Boolean",
  "value": true
}
```
