### ISSUE TITLE
Azure Container Instance to download blob from storage

### ISSUE THREAD

**Issue by RogerBestMsft** [Azure/azure-cli#12762]
## Describe the bug
I have a bash script that logs in using a User assigned identity that has access to the storage and runs the download-batch which fails

**Command Name**
`az storage blob download-batch`

**Errors:**
```
cannot import name timezone
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
azure/cli/core/__init__.py, ln 536, in get_op_handler
    op = import_module(mod_to_import)
lib/python2.7/importlib/__init__.py, ln 37, in import_module
    __import__(name)
command_modules/storage/operations/blob.py, ln 9, in <module>
    from datetime import datetime, timezone
ImportError: cannot import name timezone
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Docker container with Terraform, Azure CLI, and Azcopy
- az login --identity -u $EnvironmentUserId
- `az storage blob download-batch -d {} -s {} --pattern {} --account-name {}`

## Environment Summary
```
Linux-4.15.0-1075-azure-x86_64-with
Python 2.7.16

azure-cli 2.2.0

```

**Comment by qwordy** [comment]
@Juliehzl

**Comment by yonzhan** [comment]
add to S169

**Comment by Juliehzl** [comment]
Hi @RogerBestMsft, I think it may be caused by the python version you are using. We are deprecated the support for python 2.x. Could you please upgrade python version in your machine, or you can consider using linux related package not `pip install`? For more info, please refer to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest.

**Comment by Juliehzl** [comment]
Because no response for several days, I will close the issue and if there is any problem, please create a new one.
