### ISSUE TITLE
az vm create: add flag for "requireGuestProvisionSignal" api field

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#12775]
**Is your feature request related to a problem? Please describe.**
Yes. I would like to boot VMs without the agent, but I do want to boot them through the CLI.

**Describe the solution you'd like**
Expose a `az vm create` flag that corresponds to the `requireGuestProvisionSignal` that is part of hte VM Create REST API.

Ex: 
```
az vm create --image /sub/image-without-agent --require-guest-provisioning-signal false
```

**Describe alternatives you've considered**
I can't come up with any.

**Comment by yonzhan** [comment]
@qwordy please take a look.

**Comment by qwordy** [comment]
I get an error when testing this field.
```
The property 'requireGuestProvisionSignal' is not valid because the 'Microsoft.Compute/Agentless' feature is not enabled for this subscription
```
When I try to register it, I get
```
The feature 'Agentless' could not be found.
```
Can you use this field successfully?

**Comment by colemickens** [comment]
It seems like it's been part of the public Compute API for years, I just assumed it was available. I was waiting for CLI support to test it out.

**Comment by adritrix** [comment]
@qwordy I’m having the same problem with the 'requireGuestProvisionSignal' error. Did you find a solution? If so I would appreciate the help you could provide me.

**Comment by qwordy** [comment]
Hi service team, do you know how to use requireGuestProvisionSignal? I try to register the feature, I get "The feature 'Agentless' could not be found."

**Comment by adritrix** [comment]
@qwordy In my case, I received that error while trying to deploy Rome resources through a template. I fixed it by removing the line. 

  **"requireGuestProvisionSignal": true**

**Comment by Drewm3** [comment]
This property was inappropriately added to the public APIs, and it is not currently supported. This was added at one point in the past by someone doing experimentation, but it should not have shown up in the public APIs. 

I will work with the team to get this property removed from the public APIs because it is not supported for general usage.

**Comment by colemickens** [comment]
Okay, I'll explore other options in the meantime. I don't know if y'all want to leave this open to track removal from API, but we can close this one whenever. Thanks for the update @Drewm3!

**Comment by colemickens** [comment]
Also, since I didn't link them already... for anyone else here following breadcrumbs, the related `walinuxagent` issue: https://github.com/Azure/WALinuxAgent/issues/1888

**Comment by qwordy** [comment]
Thank you @Drewm3

**Comment by davejdyer** [comment]
This parameter is also showing up in VM templates exported from the portal which causes an error when trying to use said template. Then I had to track down this thread to figure out what was going on.

**Comment by morf96** [comment]
Currently, the error still exist:
The property 'requireGuestProvisionSignal' is not valid because the 'Microsoft.Compute/Agentless' feature is not enabled for this subscription.
Will it be available under Microsoft.Compute resource provider?
It was in a template generated from Azure Portal for automation.
