### ISSUE TITLE
lack of the documentation about the policy object

### ISSUE THREAD

**Issue by sengokyu** [Azure/azure-cli#12789]
&gt; Use the show command with JSON output to obtain a policy object. 

`az backup policy show` command outputs many fields. Which is a policy object? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86a3dc2c-442c-f2b9-7303-1b008e7713bd
* Version Independent ID: 8b695b10-a26d-caac-5206-38edeb1859c1
* Content: [az backup policy](https://docs.microsoft.com/en-us/cli/azure/backup/policy?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/backup/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/backup/_help.py)
* Service: **backup**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
backup

**Comment by pvrk** [comment]
@sengokyu : The output of the command is the "object". You can re-direct them to a file, edit the properties and give the file back as input to the ```az backup policy set``` command. May I know what is the ultimate goal/intent?

**Comment by pvrk** [comment]
@sengokyu : A gentle reminder.

**Comment by pvrk** [comment]
@sengokyu : Closing this issue since we didn't get updates. Please feel free to re-open if there are more clarifications.
