### ISSUE TITLE
az login NotImplementedError: APIVersion 2019-06-01 is not available

### ISSUE THREAD

**Issue by nrodrigues11** [Azure/azure-cli#12783]
## Describe the bug

When I try to execute az login the command fails with the below error.

**Command Name**
`az login`

**Errors:**
```
APIVersion 2019-06-01 is not available
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/cli/core/_profile.py, ln 867, in _find_using_common_tenant
    tenants = client.tenants.list()
mgmt/resource/subscriptions/subscription_client.py, ln 148, in tenants
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-06-01 is not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-3.10.0-1062.4.1.el7.x86_64-x86_64-with-redhat-7.7-Maipo
Python 3.6.9

azure-cli 2.1.0

Extensions:
interactive 0.4.3

```

**Comment by yonzhan** [comment]
add to S169

**Comment by qianwens** [comment]
@nrodrigues11 it seems some package is missed in your environment, could you please help provide more information like how did you install Az CLI? Can you run `pip list` in your machine and share the output with us?
