### ISSUE TITLE
vnet integration getting failed using azure CLI

### ISSUE THREAD

**Issue by vishalsinghdev** [Azure/azure-cli#12787]
While I am trying to do vnet integration between linux WebApp(App service plan: P1V2) and Vnet using Azure CLI.
I getting error: **az webapp vnet-integration add: error: 'NoneType' object has no attribute 'location'**
Below is Error ScreenShot:
![image](https://user-images.githubusercontent.com/55273655/77889792-1023f000-728c-11ea-948f-5ee281bde0d8.png)

**Comment by yungezz** [comment]
routing to appriopriate team

**Comment by vishalsinghdev** [comment]
@SnehaAgrawal-MSFT please do have look in this issue
