### ISSUE TITLE
az backup protection resume is not working as expected

### ISSUE THREAD

**Issue by watsonb** [Azure/azure-cli#12792]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
After disabling backups via `az backup protection disable`, I would like to resume backups via `az backup protection resume`.  Backups are not being reflected as `enabled` via the Azure portal after resuming backups on a previously `disabled` backup.

**To Reproduce**
1. Check VM current backup status via `az backup protection check-vm`

2. If the output of step 1 is empty/null, enroll the VM for the first time via `az backup protection enable-for-vm`, and validate backup protection via Azure portal

3. Disable VM protection via the following procedure:
a. Get the container of the VM via `az backup container list`, filtering out for the specific VM
b. Get the item name via `az backup item list`, feeding it the returned container name from step 3a
c. Disable backups via `az backup protection disable` using the container and item names from steps 3a and 3b, then confirm backups are disabled via Azure portal

4. Resume VM protection via the following procedure:
a. Get the container of the VM via `az backup container list`, filtering out for the specific VM
b. Get the item name via `az backup item list`, feeding it the returned container name from step 4a
c. Resume backups via `az backup protection resume` using the container and item names from steps 4a and 4b, then confirm backups are enabled via Azure portal

**Expected behavior**
Steps 1, 2, and 3 function as I expect.  I can enroll a new VM that has never had backups and I can even disable them.  Moreover, I can disable them and retain the current backup, or disable them and opt to delete the current backup.  All of these actions performed via the CLI reflect my desired state/intention in the Azure portal.  However, after attempting to resume backups of a previously disabled backup (whether or not the initial backups are retained), the Azure portal still reflects "Warning (Backup disabled").  See screenshot below:

![az_cli_backup_resume_fail](https://user-images.githubusercontent.com/1863643/77913288-9bd05900-7259-11ea-9c2d-5b55bfef7f19.png)

I can, however, go to the Azure portal, select an individual VM and re-enable backups:

![azure_portal_resume_backup](https://user-images.githubusercontent.com/1863643/77913774-7abc3800-725a-11ea-9398-318aaccd3b28.png)

You can see that of the 5 that were previously disabled, now one of them has backups enabled (still pending initial backup).

![azure_portal_backup_enabled](https://user-images.githubusercontent.com/1863643/77913988-d25aa380-725a-11ea-9300-accb7ec79076.png)

I would expect this same behavior using the `az backup protection resume` commands.

**Environment summary**

Install method: pip

Version:
```bash
$ az --version
azure-cli                          2.2.0

command-modules-nspkg              2.0.3
core                               2.2.0
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/ben/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Mar  6 2020, 14:41:24) 
[GCC 7.4.0]

Legal docs and information: aka.ms/AzureCliLegal



Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/clihats
```

OS version:
Ubuntu 18.04 LTS

Shell Type:
bash

**Additional context**
This feels semi-related to #7493.

**Comment by yonzhan** [comment]
backup

**Comment by watsonb** [comment]
I suspect the problem is here:

https://github.com/Azure/azure-cli/blob/f6dbd25b57111a3e089cb08bbca0580001a26723/src/azure-cli/azure/cli/command_modules/backup/custom_base.py#L342

The documentation for `az backup protection resume --help` references `--backup-management-type` can take on one of 3 valid values: AzureIaasVM, AzureStorage, or AzureWorkload.

The above referenced method appears not to handle the AzureIaasVM type at all.  I've just updated to `2.3.0` today and the problem persists.

Any idea when `resume` will handle AzureIaasVM backup management types?

**Comment by pvrk** [comment]
@watsonb : Thanks for bringing this to our attention. We will fix this issue with the next release in mind (May 13th). Until then, to unblock yourselves, please use the ```az backup item set-policy``` command. After disabling the VM's protection, just pass the relevant policy to this command so that protection is enabled using this policy.

**Comment by watsonb** [comment]
I can confirm that the `az backup item set-policy` works.  Thanks for the suggestion.

**Comment by pvrk** [comment]
Added the ```resume``` functionality for VMs as well with Az CLI 2.6.0.
Thanks for the feedback. Closing the bug.
