### ISSUE TITLE
unable to delete an event-subscription that targets a resource that doesn't exist

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-cli#12796]
**Describe the bug**
Unable to delete an event-subscription that doesn't exist anymore.

I have an event subscription that targets a resource that in a deleted resource group.  When I try to delete it, via:

az eventgrid event-subscription delete --name <name> --source-resource-id <id>, I get back:

Resource group 'GROUPNAME' could not be found.

When I recreate the resource group, I get:

The Resource 'Microsoft.Storage/storageAccounts/STORAGENAME' under resource group 'GROUPNAME' was not found.

When I recreate the storage account, I get:

```
The request url http://10.0.34.97:30013/<GUID>/132299720350923755/<GUID>/subscriptions/<GUID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Storage/storageAccounts/<STORAGENAME>/providers/Microsoft.EventGrid/eventSubscriptions/<EVENTNAME>/providers/Microsoft.EventGrid/eventSubscriptions/<EVENTNAME>?api-version=2019-06-01 is not found.
```

The event, according to az eventgrid event-subscription list is:
```
{
    "deadLetterDestination": null,
    "destination": {
      "endpointType": "StorageQueue",
      "queueName": "file-changes",
      "resourceId": "/subscriptions/XXX/resourceGroups/YYY/providers/Microsoft.Storage/storageAccounts/ZZZ"
    },
    "expirationTimeUtc": null,
    "filter": {
      "advancedFilters": null,
      "includedEventTypes": [
        "Microsoft.Storage.BlobCreated",
        "Microsoft.Storage.BlobDeleted"
      ],
      "isSubjectCaseSensitive": null,
      "subjectBeginsWith": "",
      "subjectEndsWith": ""
    },
    "id": "/subscriptions/XXX/resourceGroups/YYY/providers/Microsoft.Storage/storageAccounts/AAA/providers/Microsoft.EventGrid/eventSubscriptions/BBB",
    "labels": null,
    "name": "onefuzz1",
    "provisioningState": "Succeeded",
    "resourceGroup": "GROUPNAME",
    "retryPolicy": {
      "eventTimeToLiveInMinutes": 1440,
      "maxDeliveryAttempts": 30
    },
    "topic": "/subscriptions/XXX/resourceGroups/YYY/providers/microsoft.storage/storageaccounts/ZZZ",
    "type": "Microsoft.EventGrid/eventSubscriptions"
  }
```

**To Reproduce**
Create resource group.  Create storage account.  Create event grid subscription monitoring file changes, targeting a storage queue.  Delete resource group.  

Now you can't delete event grid subscription.

**Expected behavior**
Deleting event grid subscriptions that target resources that don't exist should be ok.

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
eventgrid

**Comment by ahamad-MS** [comment]
@bmc-msft  thanks for reporting this issue. The issue described is by design and in adherence of how Azure Resource Manager (ARM) is forcing the resources models. When resource group is deleted all the resources in this resource group is deleted. This operation is stateless namely we don't remember if the resource group was created before and what resources in it was added. We cannot know if the user intension is to do full cleanup and restart over or restore.

If you still have any issue, please open an IcM/support ticket for Azure Event Grid team or reach out directly to askgrid@microsoft.com

thanks

**Comment by bmc-msft** [comment]
It's "as designed" to be unable to delete eventgrid event subscriptions that target something that has been deleted?

Additionally, it's "as designed" to leak internal IP addresses of resources when that happens?
