### ISSUE TITLE
vnet integration getting failed using azure CLI

### ISSUE THREAD

**Issue by vishalsinghdev** [Azure/azure-cli#12791]
While I am trying to do vnet integration between linux WebApp(App service plan: P1V2) and Vnet using Azure CLI.
I getting error: **az webapp vnet-integration add: error: 'NoneType' object has no attribute 'location'**
Below is Error ScreenShot:
![image](https://user-images.githubusercontent.com/55273655/77897999-115b1a00-7298-11ea-8886-cdedcb1819b6.png)

**Comment by yonzhan** [comment]
webapp

**Comment by RobCoPKC** [comment]
So what was the solution? We're facing the same issue.

Cheers,
Robin
