### ISSUE TITLE
Az webapp create cannot parse runtime

### ISSUE THREAD

**Issue by brunomartinspro** [Azure/azure-cli#12795]
When attempting to create a webapp for linux using the latest version of the Azure CLI on Azure DevOps the command does not work.

It gives the error:

```powershell 
az : '3.0' is not recognized as an internal or external command,
```

The [solution](https://social.msdn.microsoft.com/Forums/en-US/b6febeba-8f5e-4134-8189-04294bbcb766/az-webapp-create-runtime-quotnode610quot-quot610-is-not-recognized-as-an-internal?forum=windowsazurewebsitespreview) was to escape the entire command like this:

```powershell
az --% webapp create --name "${{ parameters.appServiceName }}" --plan "${{ parameters.appServicePlanName }}" --resource-group "${{ parameters.resourceGroup }}" --runtime "DOTNETCORE|3.0"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest&source=docs#feedback)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
Looks like you are using Powershell for running the CLI command if so yes you need to escape the command since runtime contains character "|" which has special meaning in PowerShell
