### ISSUE TITLE
Error when attempting to decrypt disks

### ISSUE THREAD

**Issue by pgbconfirmit** [Azure/azure-cli#12809]
The following command throws an error:
az vm encryption disable --name VMName -g ResourceGroup --volume-type ALL

Multiple VMExtensions per handler not supported for OS type 'Windows'. VMExtension 'AzureDiskEncryption' with handler 'Microsoft.Azure.Security.AzureDiskEncryption' already added or specified in input.

Is this a bug, or some limitation I'm unaware of? I found little to no help with searching the web for this error.

**Comment by pgbconfirmit** [comment]
If there are limitations based on certain scenarios, the instruction page should at least be updated here - https://docs.microsoft.com/en-us/cli/azure/vm/encryption?view=azure-cli-latest

**Comment by yonzhan** [comment]
@qwordy  please take a look

**Comment by qwordy** [comment]
How do you create the VM and enable encryption? I tried and didn't reproduce your error following the quickstart.
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption-cli-quickstart

**Comment by pgbconfirmit** [comment]
> How do you create the VM and enable encryption? I tried and didn't reproduce your error following the quickstart.
> https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption-cli-quickstart

We created the all the VMs using Terraform.

**Comment by pgbconfirmit** [comment]
When installing the VMs using Terraform, we pre-pended the name of the VM to the name of the encryption extension when installing the extension, so perhaps this causes unexpected behavior when trying to decrypt the drives in the portal?

If you want to replicate our problem, I would suggest building a VM using the same process in terraform, with the VM name pre-pended to the extension name when installing encryption.

**Comment by houk-ms** [comment]
I could not reproduce it, @qwordy need your more investigations.

@pgbconfirmit Sorry for the long time to response. May I ask that do you always encounter the problem when using Terraform to deploy while CLI to operate?

**Comment by pgbconfirmit** [comment]
We don't encrypt the drives anymore using Terraform, but when we did, yes, we encountered this every time we deployed a new VM using Terraform and pre-pended the name of the VM to the encryption extension.
It is my theory that if we had left the name of the encryption extension as the default, and not renamed it in the YAML, then perhaps this problem would not have happened. But since we don't encrypt the disks anymore with Bitlocker, I can't say for sure. We have moved on.

**Comment by pgbconfirmit** [comment]
Maybe this will be helpful ... here is a snippet from the .tf file we used in the past, relevant to the disk encryption:

// ## Disk encryption ##
// resource "azurerm_virtual_machine_extension" "FE01-Disk-encryption" {
//   name                 = "${var.env-name}-FE01-Disk-encryption"
//   location             = var.azure_location
//   resource_group_name  = azurerm_resource_group.RG.name
//   virtual_machine_name = azurerm_virtual_machine.FE01.name
//   publisher            = "Microsoft.Azure.Security"
//   type                 = "AzureDiskEncryption"
//   type_handler_version = "2.2"

//   settings = <<SETTINGS
// {
//   "EncryptionOperation": "EnableEncryption",
//   "KeyVaultURL": "https://${azurerm_key_vault.KeyVault.name}.vault.azure.net",
//   "KeyVaultResourceId": "${azurerm_key_vault.KeyVault.id}",
//   "KeyEncryptionSecretURL": "${azurerm_key_vault_secret.diskencryption.id}",
//   "KeyEncryptionAlgorithm": "RSA-OAEP",
//   "VolumeType": "All"
// }
// SETTINGS
// }

**Comment by yungezz** [comment]
hi @qwordy @houk-ms any update on this issue?

**Comment by qwordy** [comment]
I follow this article and it works well. I also run "disable" command. No error.
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disk-encryption-cli-quickstart
Maybe you can ask for help in https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/agent-windows#feedback
