### ISSUE TITLE
Command expects virtual network to be in same resource group as private endpoint

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-cli#12807]
During execution of command with create option using --vnet-name, the command errors out since it tries to locate vnet in same resource group specific for creation of private endpoint.

If we can highlight same that'll be helpful. If vnet resource group is different than private endpoint than we need to use subnet ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8911e94f-9496-a68d-50c0-b5d536a375a4
* Version Independent ID: cc37b77b-0fa2-991b-e16b-fcdbbf183853
* Content: [az network private-endpoint](https://docs.microsoft.com/en-us/cli/azure/network/private-endpoint?view=azure-cli-latest#az-network-private-endpoint-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S169

**Comment by MyronFanQiu** [comment]
@AjKundnani Hi. It's a quite common design in Azure CLI and exists for a quite long time. I don't want to change the help message for vnet-name. But I agree with your point and I think we can output extra warning logs. I will improve this part later.
