### ISSUE TITLE
az account get-access-token from command line results into resource not found

### ISSUE THREAD

**Issue by rfcdejong** [Azure/azure-cli#12803]
## Describe the bug
I'm owner of the subscription in the tenant. I created the keyvault myself and added a certificate, configured rbac correctly. I know how it works, I did it often. From Visual Studio using the KeyVaultClient with AuthenticationCallback it resulted into Unauthenticated while I configured my account in Visual Studio options->tools. 

This is why I try using Azure SDK Environment command prompt, it results into the following bad request. I did set subscription identifier correctly and 'account show' shows the correct subscription. The resource url is correct..

Perhaps related to #12802 

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://diascertificateskv.vault.azure.net was not found in the tenant named c2557dc9-987f-4827-af2a-8532ab931198. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 27bb898d-f93b-46aa-82ec-6a68469d0f00\r\nCorrelation ID: 38c48dbe-76aa-4665-8691-9cb56c529d91\r\nTimestamp: 2020-03-31 11:08:11Z","error_codes":[500011],"timestamp":"2020-03-31 11:08:11Z","trace_id":"27bb898d-f93b-46aa-82ec-6a68469d0f00","correlation_id":"38c48dbe-76aa-4665-8691-9cb56c529d91","error_uri":"https://login.microsoftonline.com/error?code=500011"}
Traceback (most recent call last):
pip-install-i2ys5wad\knack\knack\cli.py, ln 215, in invoke
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- az login
- `az account get-access-token --resource {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.0

```

**Comment by yungezz** [comment]
hi @arrownj could you pls have a look? thanks

**Comment by jiasli** [comment]
It looks like the `resource` `https://diascertificateskv.vault.azure.net` is not correct. If you debug into 

https://github.com/Azure/azure-cli/blob/bb9c5f28db8f0629bb64521809c71e10820daa02/src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py#L36

You can see `resource` should be `https://vault.azure.net`.

![image](https://user-images.githubusercontent.com/4003950/78115679-bb23dd80-7435-11ea-94b6-6e8b59003bcf.png)

This is also mentioned at https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#authenticating-with-azure-cli

**Comment by rfcdejong** [comment]
> It looks like the `resource` `https://diascertificateskv.vault.azure.net` is not correct. If you debug into this line with command `az keyvault key list --vault-name {mykv}`
> 
> https://github.com/Azure/azure-cli/blob/bb9c5f28db8f0629bb64521809c71e10820daa02/src/azure-cli/azure/cli/command_modules/keyvault/_client_factory.py#L36
> 
> You can see `resource` should be `https://vault.azure.net`.
> 
> ![image](https://user-images.githubusercontent.com/4003950/78115679-bb23dd80-7435-11ea-94b6-6e8b59003bcf.png)
> 
> This is also mentioned at https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#authenticating-with-azure-cli

Yes, that explains why the cli command returned this bad request. The command now works, now I get an access token. Thank you.

Perhaps update the response for the bad request with a suggestion? Else close it

**Comment by jiasli** [comment]
Hi @rfcdejong, glad to know it is working for you and thanks for the suggestion. But since user can provide all kinds of resources, and may hit different errors, we prefer to keep the message from AAD token server intact:

> Get Token request returned http error: 400 and server response: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://diascertificateskv.vault.azure.net was not found in the tenant named c2557dc9-987f-4827-af2a-8532ab931198. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.}

By the way, this message is already very clear to me about the root cause. Instead, I do agree that key vault's doc can be improved to make it easier to find. 😉
