### ISSUE TITLE
Error on testing Multi-container using Docker Compose in Azure Web App for Containers

### ISSUE THREAD

**Issue by acidsunburn** [Azure/azure-cli#12801]
## Describe the bug

**Command Name**
`az webapp create`

**Errors:**
```
'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 657, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/command_modules/appservice/custom.py, ln 125, in create_webapp
    site_config.windows_fx_version = _format_fx_version(deployment_container_image_name)
cli/command_modules/appservice/custom.py, ln 871, in _format_fx_version
    fx_version = custom_image_name.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._

git fetch  https://github.com/acidsunburn/inhubtest

az group create --name myInHubResourceGroup --location "northeurope"

az appservice plan create --name myAppServicePlan --resource-group myInHubResourceGroup --sku PCV2 --hyper-v

az webapp create --resource-group myInHubResourceGroup --plan myAppServicePlan --name inHub --multicontainer-config-type compose --multicontainer-config-file docker-compose.yml

## Expected Behavior
At least the container instance should be created. Startup will fail as there is a on premise database connection needed

## Environment Summary
```
Linux-4.15.0-1075-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@Kotasudhakarreddy can you check if you can repro this using the steps provided?

**Comment by navba-MSFT** [comment]
@acidsunburn Apologies for the late reply. Could you please update the [python libraries](https://www.python.org/downloads/) and use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) of the CLI and let us know if you are still running into the same issue ? Awaiting your reply.
