### ISSUE TITLE
Bug with TTL in DNS record sets

### ISSUE THREAD

**Issue by mal-risma** [Azure/azure-cli#12804]
**Describe the bug**
We're having issues with setting TTL for TXT records using the CLI. I'm trying to first create an empty record set and then adding records to it. Setting the TTL when creating an empty set works. But when calling add-record, the TTL os overridden with 3600. 
Also it is not possible to set TTL with the add-record command. 
I'm guessing this behaviour is related to this PR: https://github.com/Azure/azure-cli/pull/11365 especially on line 1921: `record_set.ttl = ttl if ttl is not None else 3600` setting the ttl to 3600 if it is not provided, but the support was never added to the function `add_dns_txt_record` 

**To Reproduce**
First call 
```az network dns record-set txt create -g something_dns -z example.com -n _acme-challenge --ttl 1 --output json```
Then call 
```az network dns record-set txt add-record -g something_dns -z example.com -n _acme-challenge --value some-value --output json``` 
See that the TTL is 3600 instead of 1. 

**Expected behavior**
Expect the record set to have a ttl of 1

**Environment summary**
azure-cli                          2.3.0

command-modules-nspkg              2.0.3
core                               2.3.0
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/mal/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Mar 30 2020, 09:18:43) 
[GCC 7.5.0]

**Comment by yonzhan** [comment]
add to S169

**Comment by MyronFanQiu** [comment]
@jsntcy Hi. Could you please take a look?

**Comment by MyronFanQiu** [comment]
@haroldrandom add the original author. Please take a look.

**Comment by abhisheksinghrathod** [comment]
Is this issue resolved? I dont see `--ttl` option available with command `az network dns record-set txt add-record` and it defaults to 3600 which is way too high for my usecase.

Thanks,
Abhishek

**Comment by mal-risma** [comment]
I haven't actually tested this since the bug was closed, but I think the idea is that you have to first create a record set with for example: 
`az network dns record-set txt create -g something_dns -z example.com -n _acme-challenge --ttl 1 --output json`
And then you add records to it with: 
`az network dns record-set txt add-record -g something_dns -z example.com -n _acme-challenge --value some-value --output json`

If the bug has been fixed correctly you should get a TTL of 1 for all records added to the record-set.

**Comment by fentas** [comment]
This is inconsistent.
For everything it is `add-record` but for `cname`, it is `set-record`.
You can set `--ttl` everywhere but not for `txt`, where you can only set it on `create`?

Ouch.
