### ISSUE TITLE
How do I set default subscription for connection.

### ISSUE THREAD

**Issue by ktl-lane** [Azure/azure-cli#12810]
## Describe the bug

**Command Name**
`az configure`

**Errors:**
```
az: error: unrecognized arguments: set subscritpion.Default c43b66ef-9e4d-4889-be45-1be77b159110
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az configure {} {} {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.3.0

```

**Comment by yungezz** [comment]
hi @arrownj could you pls help on this? thanks

**Comment by arrownj** [comment]
Hi @ktl-lane , there is no `set` command for `az configure`. You can use `az configure -h` to see how to use it. 

If you want to set default value to `az configure`, it would be something like this:
`az configure --defaults group=myRG`

**Comment by arrownj** [comment]
Hi @ktl-lane , if there is no more questions, we will close this issue first. You can reopen it or just submit a new one if you have other concerns. Thanks
