### ISSUE TITLE
Add new SIG API Version 2019-12-01; Add an encryption field to targetRegions

### ISSUE THREAD

**Issue by jerryc3** [Azure/azure-cli#12815]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
az sig image-version

### Description of issue (in as much detail as possible)
-----
SIG recently published a new API version (2019-12-01) to add an encryption field to targetRegions. This is the completed swagger PR https://github.com/Azure/azure-rest-api-specs/pull/8364.

This is immutable and should only be allowed on create. It should also show up in GETs if returned.

**Comment by qwordy** [comment]
Azure CLI 2.4.0 is released. It contains the feature requested in this issue.
