### ISSUE TITLE
az acs is missing kubernetes support

### ISSUE THREAD

**Issue by mulcahys** [Azure/azure-cli#1281]
e.g. (for an ACS created via the web interface)

```
$ az acs list -g foo
u'Kubernetes' is not valid value for enum <enum 'ContainerServiceOchestratorTypes'>

```

adding the type to azure/mgmt/compute/models/compute_management_client_enums.py seemed to be sufficient to display the service, haven't tried creating one yet

**Comment by yugangw-msft** [comment]
Same thing like #1282
