### ISSUE TITLE
Extension needed?

### ISSUE THREAD

**Issue by microkost** [Azure/azure-cli#12826]
az network: 'bastion' is not in the 'az network' command group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c10d6dab-e042-91dc-a213-943af0d5ad0e
* Version Independent ID: 399a501c-b96d-8867-078f-73dd9b8b3da2
* Content: [az network bastion](https://docs.microsoft.com/en-us/cli/azure/network/bastion?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by microkost** [comment]
az version
{
  "azure-cli": "2.1.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.1.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.34"
  }

**Comment by yonzhan** [comment]
add to S169

**Comment by MyronFanQiu** [comment]
Hi. This feature starts from 2.2.0. Please upgrade your Azure CLI.

**Comment by microkost** [comment]
Confirmed! Works now, thank you.
az version
{
  "azure-cli": "2.3.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.3.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.34"
  }
}

Command group 'network bastion' is in preview. It may be changed/removed in a future release.
