### ISSUE TITLE
az acs kubernetes subcommand is missing

### ISSUE THREAD

**Issue by mulcahys** [Azure/azure-cli#1282]
I'm attempting to follow https://www.youtube.com/watch?v=nhY9XdzNbbY but the kubernetes subcommand doesn't seem to be available after a `pip install azure-cli`

```
$ az acs kubernetes
usage: az acs [-h] {create,delete,show,update,list} ...
az acs: error: argument subcommand: invalid choice: 'kubernetes' (choose from 'create', 'delete', 'show', 'update', 'list')

```

**Comment by jdumars** [comment]
+1 
```
az acs create: error: argument --orchestrator-type: invalid choice: 'kubernetes' (choose from 'DCOS', 'Swarm')
```

**Comment by yugangw-msft** [comment]
It is not available in public release, but it is in nightly drop. 
Check out the [nightly installation doc](https://github.com/Azure/azure-cli/blob/master/doc/nightly/installing_nightly.md) if you are interested, and make sure you install the extra `acs` component `az component update --add acs --private`

**Comment by mulcahys** [comment]
Thanks for the update and that link @yugangw-msft.
