### ISSUE TITLE
After successful 8 submission it fail with the same credentials. 

### ISSUE THREAD

**Issue by pmblr2020** [Azure/azure-cli#12832]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
('Connection aborted.', OSError("(10060, 'WSAETIMEDOUT')",))
Traceback (most recent call last):
pip-install-89s0l3uh\urllib3\urllib3\connectionpool.py, ln 600, in urlopen
pip-install-89s0l3uh\urllib3\urllib3\connectionpool.py, ln 384, in _make_request
<string>, ln 2, in raise_from
pip-install-89s0l3uh\urllib3\urllib3\connectionpool.py, ln 380, in _make_request
CLI2\lib\http\client.py, ln 1331, in getresponse
    response.begin()
CLI2\lib\http\client.py, ln 297, in begin
    version, status, reason = self._read_status()
...
urllib3\urllib3\contrib\pyopenssl.py, ln 302, in recv_into
OSError: (10060, 'WSAETIMEDOUT')


pip-install-i2ys5wad\requests\requests\sessions.py, ln 643, in send
pip-install-i2ys5wad\requests\requests\adapters.py, ln 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(10060, 'WSAETIMEDOUT')",))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --sku {} -n {} -l {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.0 *

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
Hmm not sure if this is specific to az webapp up from the stack trace it hasn't even reached the az webapp up execution; are you still seeing this?

**Comment by navba-MSFT** [comment]
@pmblr2020 Apologies for the late reply. The error message seems like a failure at the network layer due to connectivity issues. Could you please let us know if you are still facing this issue ? Awaiting your reply.
