### ISSUE TITLE
Support "Premium_LRS" as valid storage account type in sig image versions.

### ISSUE THREAD

**Issue by KshitijAgrawal** [Azure/azure-cli#12838]
**Resource Provider**
Microsoft.Compute

**Description of Feature or Work Requested**
Premium_LRS needs to be supported in sig image versions as a valid storageAccountType.

**Minimum API Version Required**
2019-07-01

**Swagger Link**

**Target Date**
This was missed. Premium_LRS is already going GA. So please treat this as urgent.

Sample the needs to work:
az sig image-version create --resource-group myrg--gallery-name myg -i myi -e 2.9.0 --managed-image "/subscriptions/mysub/resourceGroups/myrg/providers/Microsoft.Compute/images/mygallerysourcevmubuntu" --target-regions centraluseuap=1=**_premium_lrs_**  =>doesn't work

**Comment by yonzhan** [comment]
@qwordy please take a look.

**Comment by yungezz** [comment]
Add enum values. Hi @qwordy  pls check if there's any other new enum values added.

**Comment by qwordy** [comment]
The PR is merged. It will be release on 04/21/2020.

**Comment by qwordy** [comment]
Azure CLI 2.4.0 is released. It contains the feature requested in this issue.
