### ISSUE TITLE
[KeyVault] There is no way to list pending certificates

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1283]
Certificates that are in the process of being created by taking a pending CSR to a CA cannot be discovered.

The `az keyvault certificate list` command only returns certificates which have been fully created.
There is no API call to list certificate operations.

As a result, there is no `az keyvault certificate pending list` command (but there should be).

The problem is that if you are in the process of getting a certificate from a CA, when you get the certificate and try to use `az keyvault certificate merge`, if you don't remember you used, you will not be able to complete the process. Or, if you decide NOT to get the certificate from the CA and abort the process, you can delete the operation _only if_ you remember the name (you ALSO have to delete the certificate object, because the two are independent objects, but you can't list either of them).

This issue is also applicable to Xplat and Powershell.

cc/ @amarzavery

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by bim-msft** [comment]
@tjprescott Hi, we have already added a new parameter `--include-pending` for command `az keyvault certificate list` and `az keyvault certificate list-deleted` in the latest version of CLI.
