### ISSUE TITLE
Azure CLI Python installation

### ISSUE THREAD

**Issue by dikokob** [Azure/azure-cli#12846]
pip install azure-cli

**Bug**
```
ERROR: Could not find a version that satisfies the requirement mock~=4.0 (from azure-cli->-r /code/requirements.txt (line 7)) (from versions: 0.5.0, 0.6.0, 0.7.0b1, 0.7.0b2, 0.7.0b3, 0.7.0b4, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 1.0b1, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.0, 1.3.0, 2.0.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5)
ERROR: No matching distribution found for mock~=4.0 (from azure-cli->-r /code/requirements.txt (line 7))
```
**To Reproduce**
Use the following command pip install azure-cli

**Environment summary**
Python 3.5
Ubuntu-16.04 Docker Container

**Comment by dikokob** [comment]
I used the following version 2.2.0 of azure-cli, and that seems to work.

**Comment by yungezz** [comment]
@fengzhou-msft  could you pls look at the duplicate issue from user

**Comment by fengzhou-msft** [comment]
@dikokob azure-cli 2.3.x dropped support for python 3.5. Can you use apt to install azure-cli: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

**Comment by tnguyen14** [comment]
@fengzhou-msft I'm on a system where I don't have sudo access, so can't use `apt` or `yum`. Is there a way to get around this issue with the install script?

**Comment by fengzhou-msft** [comment]
> @fengzhou-msft I'm on a system where I don't have sudo access, so can't use `apt` or `yum`. Is there a way to get around this issue with the install script?

You'll need a python 3.6+ environment to run azure-cli 2.3.x, either a virtual environment or build from source, but since you don't have sudo access, I'm not sure if it's possible for you.

**Comment by jkdey** [comment]
Encountering the same issue with Python 3.7.5

**Comment by fengzhou-msft** [comment]
@jkdey I cannot reproduce the issue with Python 3.7.5. Can you double check?

**Comment by jkdey** [comment]
@fengzhou-msft I saw this behavior in an alpine container, which might have made the difference

**Comment by fengzhou-msft** [comment]
Close as Azure CLI no longer supports Python 3.5.
