### ISSUE TITLE
Redefine location in Azure CLI

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#12841]
**Is your feature request related to a problem? Please describe.**

In Azure CLI, location is a global parameter. Some commands has it's own customization. It inherit location from resource group if it is not specified. It's a common practice based on my observation.
It registers location in the command,
```
c.argument('location', validator=get_default_location_from_resource_group)
```
or
Manipulate location in custom function.
However, the behavior is not documented in help.
**I recommend adding this common behavior to global location definition and update global help message.**
It has no effect on commands that succeed before, while it has effect on commands that failed before. It is an acceptable result.

A related PR:
https://github.com/Azure/azure-cli/pull/12828

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qwordy** [comment]
OK!

**Comment by yonzhan** [comment]
S168

**Comment by qwordy** [comment]
I find some example with special behavior. This is a validator of `vm create`.
```
def _validate_location(cmd, namespace, zone_info, size_info):
    from ._vm_utils import list_sku_info
    if not namespace.location:
        get_default_location_from_resource_group(cmd, namespace)
        if zone_info:
            sku_infos = list_sku_info(cmd.cli_ctx, namespace.location)
            temp = next((x for x in sku_infos if x.name.lower() == size_info.lower()), None)
            # For Stack (compute - 2017-03-30), Resource_sku doesn't implement location_info property
            if not hasattr(temp, 'location_info'):
                return
            if not temp or not [x for x in (temp.location_info or []) if x.zones]:
                raise CLIError("{}'s location can't be used to create the VM/VMSS because availability zone is not yet "
                               "supported. Please use '--location' to specify a capable one. 'az vm list-skus' can be "
                               "used to find such locations".format(namespace.resource_group_name))
```

**Comment by qwordy** [comment]
Due to some existing special customized behavior of location in some commands. This issue is abandoned.
