### ISSUE TITLE
Provide version option for Ubuntu user to install

### ISSUE THREAD

**Issue by Joe-TJ** [Azure/azure-cli#12845]
**Is your feature request related to a problem? Please describe.**

When we update Azure-Cli to 2.3.1 on Ubuntu, we cannot connect to AKS on China Azure. 
Error text:
No registered resource provider found for location 'chinaeast2' and API version '2020-03-01' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31, 2019-02-01, 2019-04-01, 2019-06-01, 2019-08-01, 2019-10-01, 2019-11-01, 2020-01-01, 2020-02-01'. The supported locations are 'chinaeast2, chinanorth2'. No registered resource provider found for location 'chinaeast2' and API version '2020-03-01' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31, 2019-02-01, 2019-04-01, 2019-06-01, 2019-08-01, 2019-10-01, 2019-11-01, 2020-01-01, 2020-02-01'. The supported locations are 'chinaeast2, chinanorth2'. No registered resource provider found for location 'chinaeast2' and API version '2020-03-01' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31, 2019-02-01, 2019-04-01, 2019-06-01, 2019-08-01, 2019-10-01, 2019-11-01, 2020-01-01, 2020-02-01'. The supported locations are 'chinaeast2, chinanorth2'.

We get response from Azure support that: if we want to use Cli to connect to AKS we have to install older version (2.0.68) on Ubuntu. But we found nowhere to download older version Cli of Ubuntu.

**Proposed solution**
Provide version option for Ubuntu user to install Cli

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
@Joe-TJ please run `apt-cache policy azure-cli` to list the available versions. Then install with `sudo apt-get install azure-cli=<version-name>`. For instance on bionic:
`sudo apt-get install azure-cli=2.0.68-1~bionic`
