### ISSUE TITLE
[AppService] Fix WEBSITE_RUN_FROM_PACKAGE race condition

### ISSUE THREAD

**Issue by gzuber** [Azure/azure-cli#12840]
We've seen a case where an app is having deployment issues because the `WEBSITE_RUN_FROM_PACKAGE` app setting isn't being set at app creation but rather during deployment. Because of this, the app setting didn't have enough time to propogate to workers. See details from the RCA below:

> This was due to a race condition in adjust WEBSITE_RUN_FROM_PACKAGE property, delay propagation on the settings and deployment.  The workaround is to make sure to create the site with WEBSITE_RUN_FROM_PACKAGE set from the beginning (in the case the python CLI).  
> 
> Timeline:
> 
> 2020-03-17 09:43:40 Python CLI update appSetting w/o WEBSITE_RUN_FROM_PACKAGE
> 
> 2020-03-17 09:44:20 VSTS update appSetting with WEBSITE_RUN_FROM_PACKAGE (however it is yet to propagate to workers).
> 
> 2020-03-17 09:44:21 ZipDeploy without WEBSITE_RUN_FROM_PACKAGE - which will fail the runtime if WEBSITE_RUN_FROM_PACKAGE is set.

**Comment by yonzhan** [comment]
AppService

**Comment by panchagnula** [comment]
@gzuber is this for a function app specifically? currently we don't support the run_from_package in CLI and definitely not during create.AppSettings currently are always added after the APP is created in both portal and CLI.
