### ISSUE TITLE
Status of 'az storage blob restore' command

### ISSUE THREAD

**Issue by alangner** [Azure/azure-cli#12847]
I couldn't find any further documentation for this command. Is it limited to certain regions, and if yes to which ones?
Tried it on a blob storage in westeurope and I get: 
A feature was requested which is not yet available in this location

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S168

**Comment by Juliehzl** [comment]
Hi @alangner, because this feature is just in private preview and only several regions are available now,   after public preview Storage team will provide detailed documentation for this feature.
Currently the following regions are available:
```
westcentralus
westus2
eastus2euap
centraluseuap
```
