### ISSUE TITLE
in azure-cli 2.2.0, when add '--output table' option, encounter an error. It doesn't exist in old version 2.0.*

### ISSUE THREAD

**Issue by Wang-Caixing** [Azure/azure-cli#12843]
azure-cli : 2.2.0

When run command:  
az aks get-upgrades --resource-group <ResourceGroup Name> --name <AKSCluster Name> --output table
It reports an error:   Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info. 

Please refer to the screenshot as below: 
![azurecli_error](https://user-images.githubusercontent.com/8428301/78216516-9a6a8f00-74ec-11ea-9461-4c24b6f4cc2d.png)

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
I'm not able to reproduce this on 2.3.1

```
➜  ~ az aks get-upgrades -g contosofin-rg -n contosofinaks --output table
Name     ResourceGroup    MasterVersion    Upgrades
-------  ---------------  ---------------  -----------------------
default  contosofin-rg    1.16.1           1.16.7, 1.17.3(preview)
```

Could you try an upgrade and repro?

**Comment by Jen7714** [comment]
Hello! Please try again with the latest Azure CLI version. Feel free to reopen an issue if it still doesn't work.
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest
