### ISSUE TITLE
[SSH] - az webapp ssh is not working on windows OS

### ISSUE THREAD

**Issue by Kotasudhakarreddy** [Azure/azure-cli#12844]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
`az webapp ssh` command is throwing an error:`webapp ssh is only supported on linux and mac
` when runs from windows machine.

**To Reproduce**
1. run below command from windows machine
`az webapp ssh -n MyUniqueAppName -g MyResourceGroup`

**Expected behavior**
It should work as on other OS like Mac or Linux

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@btardif FYI.

**Comment by mloskot** [comment]
IMHO, the error message is unclear, see https://github.com/Azure/azure-cli/issues/12940#issuecomment-737152145

**Comment by btardif** [comment]
This is being tracked here: #16125
