### ISSUE TITLE
Please bump dependency for azure-batch if possible

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-cli#12850]
```azure-cli``` still has ```'azure-batch~=8.0'``` in its ```setup.py``` but the current upstream version is 9.0.

Could that dependency be raised? Otherwise Linux distributions such as openSUSE Tumbleweed who always package the latest versions run into dependency issues.

**Comment by yonzhan** [comment]
@fengzhou-msft  please take a look

**Comment by fengzhou-msft** [comment]
Bumped in this [PR](https://github.com/Azure/azure-cli/pull/12813).
