### ISSUE TITLE
Unable to get the credentials 

### ISSUE THREAD

**Issue by raipra** [Azure/azure-cli#12852]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
dlopen(/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so
  Reason: image not found
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
...
ImportError: dlopen(/usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/azure-cli/2.0.70/libexec/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so
  Reason: image not found
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Darwin-19.3.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.70

```

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
@raipra I'm unable to reproduce on the latest 2.3.1 build, could you upgrade and try again?

**Comment by Jen7714** [comment]
Hello! Please try again with the latest Azure CLI version. Feel free to reopen an issue if it still doesn't work.
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest
