### ISSUE TITLE
Error when upgrading CLI in Azure Cloud Shell

### ISSUE THREAD

**Issue by jyee021** [Azure/azure-cli#12859]
Trying to upgrade the az cli version in cloud shell to 2.3.x from 2.2.0 using the "curl -L https://aka.ms/InstallAzureCli | bash" command

Getting the following error message:

Collecting azure-mgmt-maps~=0.1.0
  Downloading azure_mgmt_maps-0.1.0-py2.py3-none-any.whl (31 kB)
ERROR: Could not find a version that satisfies the requirement mock~=4.0 (from azure-cli) (from versions: 0.5.0, 0.6.0, 0.7.0b1, 0.7.0b2, 0.7.0b3, 0.7.0b4, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 1.0b1, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.0, 1.3.0, 2.0.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5)
ERROR: No matching distribution found for mock~=4.0 (from azure-cli)
Traceback (most recent call last):
  File "/tmp/azure_cli_install_tmp_AmTxAE", line 420, in <module>
    main()
  File "/tmp/azure_cli_install_tmp_AmTxAE", line 405, in main
    install_cli(install_dir, tmp_dir)
  File "/tmp/azure_cli_install_tmp_AmTxAE", line 151, in install_cli
    exec_command(cmd)
  File "/tmp/azure_cli_install_tmp_AmTxAE", line 106, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)

**Comment by yungezz** [comment]
any instance

**Comment by jyee021** [comment]
Sorry, is that a question for me? my current az cli version is 2.2.0 in the bash shell

john@Azure:~$ az --version
azure-cli                          2.2.0 *

command-modules-nspkg              2.0.3
core                               2.2.0 *
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
interactive                        0.4.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/john/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Mar  6 2020, 14:41:35)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 updates available. Consider updating your CLI installation. Instructions can be found at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**Comment by brianbar-MSFT** [comment]
AFAIK, we have to wait for the Azure CLI instance in the Azure Cloud Shell container to be updated to the latest release.

**Comment by MichaelCosby** [comment]
I had the same error. In my case, the problem is that azure cli now requires mock 4.0+, and mock (as of version 4) is no longer compatible with python < 3.6 (I am on ubuntu 16.04 until 20.04 comes out, so I have python 3.5.2). As far as I know, the only solution is to upgrade your python version.

**Comment by fengzhou-msft** [comment]
Cloud Shell has Azure CLI 2.4.0 now.

Currently, the only way to have a new Azure CLI version is through Cloud Shell release that happens every three weeks. Azure CLI's release cadence usually keeps pace with Cloud Shell except when there's code freeze for Cloud Shell which is the case during 2.3.x or Azure CLI has some urgent releases such as the latest 2.5.0.

**Comment by fengzhou-msft** [comment]
Cloud Shell is not going to upgrade their Python version in the short term. So `pip install azure-cli` is not supported. I have updated the [message](https://github.com/Azure/azure-cli/blob/58198af0d650df1433f329f2ab42572836bae62e/src/azure-cli-core/azure/cli/core/util.py#L307-L308) in `az --version` to avoid confusion.
