### ISSUE TITLE
Is this command deprecated?

### ISSUE THREAD

**Issue by itrelouis** [Azure/azure-cli#12860]
The output when using this command warns that it's been superseded by 'az deployment group'. I found this from an ADO Azure CLI release task that executed this command and started failing because of that warning -- changing it to 'az deployment group' fixed it.

It would be worth mentioning on this page if it's been deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de233487-a2e5-00ab-30e9-f68866735957
* Version Independent ID: 2cd3ed9f-113f-a6c2-6a36-2925a044edf8
* Content: [az group deployment](https://docs.microsoft.com/en-us/cli/azure/group/deployment?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @zhoxing-ms could  you pls have a look

**Comment by yonzhan** [comment]
add to S168

**Comment by zhoxing-ms** [comment]
@itrelouis Yes, `az deployment group` will be used instead of `az group deployment`. 
And there are prompts when executing the command or using `az group deployment -h`:
> This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.

Do you have any other questions?

**Comment by itrelouis** [comment]
@zhoxing-ms Ok that makes sense -- the reason I posted my question though was that this page:

https://docs.microsoft.com/en-us/cli/azure/group/deployment?view=azure-cli-latest

does not seem to indicate that the command is deprecated. I think the documentation should make that clear and point users to use the az deployment group command instead.

**Comment by haroldrandom** [comment]
same request as https://github.com/Azure/azure-cli/issues/12549

**Comment by zhoxing-ms** [comment]
@itrelouis This is a known issue and we have a long-term plan with the document related team.

**Comment by itrelouis** [comment]
Understood, thanks @zhoxing-ms !

**Comment by robdmoore** [comment]
Hi @zhoxing-ms,

I'm confused. I've seen a number of reports like this one that `az group deployment` is being deprecated for `az deployment group`, but I've just updated to the latest version of az CLI and I don't get the deprecation warning, and the `az group deployment` docs pages don't mention it either:

![image](https://user-images.githubusercontent.com/573791/90327194-bbc3a780-dfc3-11ea-82a1-401a859c532b.png)

Has the decision to deprecate that command been reversed or is it still going ahead?

I have an A Cloud Guru course that has references to the old command so I need to know if I need to update that.

Thanks

**Comment by zhoxing-ms** [comment]
@robdmoore Sorry, I cannot reproduce your question, and the prompt message of deprecate on my side is as follows:
```pwsh
(env) PS C:\Users\zhoxing.FAREAST\Desktop\project> az group deployment -h

Group
    az group deployment : Manage Azure Resource Manager deployments.
        This command group has been deprecated and will be removed in a future release. Use
        'deployment group' instead.
```
May I ask how you install CLI and what is the specific environment you use?

The document does not mention the deprecate information which is a known issue, and we have a long-term plan to improve it in the future

This command `az group deployment` is still be deprecated, so please use the recommended command `az deployment group` instead of it~
