### ISSUE TITLE
az login APIVersion 2019-06-01 is not available on Archlinux

### ISSUE THREAD

**Issue by boogy** [Azure/azure-cli#12878]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
APIVersion 2019-06-01 is not available
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 625, in execute
    raise ex
cli/core/commands/__init__.py, ln 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 682, in _run_job
    six.reraise(*sys.exc_info())
...
azure/cli/core/_profile.py, ln 844, in find_through_interactive_flow
    result = self._find_using_common_tenant(token_entry[_ACCESS_TOKEN], resource)
azure/cli/core/_profile.py, ln 877, in _find_using_common_tenant
    tenants = client.tenants.list()
mgmt/resource/subscriptions/_subscription_client.py, ln 127, in tenants
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-06-01 is not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.5.13-arch2-1-x86_64-with-glibc2.2.5
Python 3.8.2
Installer: PIP

azure-cli 2.3.1

```

**Comment by yungezz** [comment]
hi @arrownj could you pls have a look

**Comment by arrownj** [comment]
Hi @boogy , it seems that your azure-mgmt-resource version is not right. Could you please help tell what platform you are using? If you are on Windows, maybe you can check the SDK version by open folder C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages and check its child folder which starts with azure_mgmt_resource (it should be something like azure_mgmt_resource-8.0.1.dist-info).

**Comment by arrownj** [comment]
Similar to #12779 . Please use the official `azure_mgmt_resource` sdk and let us know if there are other problems.
