### ISSUE TITLE
Cannot Combine Service Types 

### ISSUE THREAD

**Issue by almero2020** [Azure/azure-cli#12879]
**Describe the bug**
XML specified is not syntactically valid.

**To Reproduce**
az storage logging update --services btq --log rwd --version 2 --retention 9 --account-name "mytest" --account-key "I am not showing my key here due to security reasons "

**Expected behavior**
KB states block , table and queue can be combined . When I run just b it works , or just q it works , but when I use bqt , or b, q, t or b q t i get XML syntax error . 

**Environment summary**
azure-cli                          2.1.0 *

command-modules-nspkg              2.0.3
core                               2.1.0 *
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/bin/python3'
Extensions directory '/home/automation/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Aug  7 2019, 17:28:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

**Additional context**

**Comment by yungezz** [comment]
hi @Juliehzl could  you pls have a look?

**Comment by yonzhan** [comment]
add to S168

**Comment by almero2020** [comment]
Hi Team , further investigation shows that bq can in fact be run , but t ( table ) alone will cause the error .  That is most likely why bqt does not work , because of t .

**Comment by Juliehzl** [comment]
@almero2020 Thanks for your feedback! It is because table service doesn't support `version 2`. You can user version 1 for logging.
@srinathnarayanan Could you please help confirm the valid version number in request for table service logging?

**Comment by almero2020** [comment]
Hi Julie . You are a 100% correct .
I can confirm that using v1 for Table works . 
We can close this ticket THANK YOU . 

Hoping to see all 4 type ( qbtf ) supported and v2 for all so we can standardize our scripts .
