### ISSUE TITLE
webapp: Fix html a href link

### ISSUE THREAD

**Issue by dmpe** [Azure/azure-cli#12876]
Update an app service plan. See &lt;a href="https://docs.microsoft.com/azure/app-service/app-service-plan-manage#move-an-app-to-another-app-service-plan"&gt;https://docs.microsoft.com/azure/app-service/app-service-plan-manage#move-an-app-to-another-app-service-plan&lt;/a&gt; to learn more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9dc8c24-cda6-8672-8017-b66435eadbb7
* Version Independent ID: a0be523a-ff1f-18ed-0fc4-ba0e0befe4d1
* Content: [az appservice](https://docs.microsoft.com/en-us/cli/azure/appservice?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/appservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/_help.py)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
appservice

**Comment by panchagnula** [comment]
@calvinsID can you take care of this during some other existing PRs?

**Comment by btardif** [comment]
![image](https://user-images.githubusercontent.com/4119816/85628015-49b68e00-b624-11ea-9da7-96b748e53eff.png)

Use this FWLink --> https://go.microsoft.com/fwlink/?linkid=2133856

See: https://go.microsoft.com/fwlink/?linkid=2133856
