### ISSUE TITLE
Facing issue with azure blob upload with caching

### ISSUE THREAD

**Issue by AmitBarthwal** [Azure/azure-cli#12875]
I am uploading the static website contents to QA environment blob storage.
It is uploaded successfully but the changes reflecting in the application after 5 to 6 hour time interval.Sometimes the time interval is around 8 hours.

Same upload i am doing in my Dev environment, it is working fine after the blob upload.
I am using below command

az storage blob upload-batch -s ./ -d "$web" --connection-string "DefaultEndpointsProtocol=https;AccountName=*********;AccountKey=*********;EndpointSuffix=core.windows.net"

I have checked the configuration is same as in DEV and QA.
Anyone help in this issue ??

**Comment by yonzhan** [comment]
add to S169

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
@AmitBarthwal after uploading, have you check the existence of your content in Portal or using `az storage blob list`?

**Comment by AmitBarthwal** [comment]
@Juliehzl  yes, i checked on the portal, that the files are uploaded. But when running the application it shows previous version of application. Instead this is not happening on all the Blob storage accounts.
As on dev and prod, i am able to update the file and gets reflected as the same instant.

I am using VSTS devops to upload the project on the blob storage.

**Comment by Juliehzl** [comment]
it seems there are some issues in server side. @vinjiang do you have any idea about such scenario?

**Comment by xiafu-msft** [comment]
Hi @AmitBarthwal 

Were you able to get this figured out?
If not can you please share the http response info of the operation which has the 8 hours delay to show up?
Thanks!

**Comment by amishra-dev** [comment]
please reactivate if you are still hitting this
