### ISSUE TITLE
az group create failed

### ISSUE THREAD

**Issue by Andriy-dev** [Azure/azure-cli#12874]
## Describe the bug

**Command Name**
`az group create`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group create -l {} -n {}`

## Environment Summary
```
Linux-4.15.0-1075-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

Extensions:
aks-preview 0.4.42

```

**Comment by yonzhan** [comment]
add to S169

**Comment by zhoxing-ms** [comment]
Hello @Andriy-dev, the host of `http://localhost:50342/oauth2/token` for oauth is `localhost`, which doesn't look right. 
May I ask what you have configured locally? For example, Is there an agent?

**Comment by Andriy-dev** [comment]
Hello @zhoxing-ms , I used standard procedure, az login and than az group create. In ether case right now it works fine. 

What kind of debugs / outputs should I collect if this happens again ?

**Comment by zhoxing-ms** [comment]
You could probably add `--debug` to the original command. Can your question be reproduced?

**Comment by yonzhan** [comment]
@Andriy-dev  any update for this ?

**Comment by Andriy-dev** [comment]
Thank you. It cannot be reproduced, I will create another issue if it happens again
