### ISSUE TITLE
Assign a policy through CLI not working.

### ISSUE THREAD

**Issue by godlike0108** [Azure/azure-cli#12880]
## Describe the bug

**Command Name**
`az policy assignment create`

**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
python3.8/site-packages/msrest/serialization.py, ln 1328, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
python3.8/site-packages/msrest/serialization.py, ln 1114, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
...

python3.8/site-packages/msrest/serialization.py, ln 1137, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az policy assignment create --scope {} --policy {} -p {}`

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.3.1

```

**Comment by yungezz** [comment]
hi @jiasli could you pls have a look

**Comment by yonzhan** [comment]
add to S168

**Comment by jiasli** [comment]
@godlike0108, I suspect the JSON string is interpreted by the shell. On MacOS/Bash, the easiest way to bypass that is to surround the JSON string with single quotes, like

```
-p '{"allowedLocations":{"value":["australiaeast","eastus","japaneast"]}}'
```

You may run `az policy assignment create -h` for examples. 

If that doesn't solve the issue, could you share the full command with arguments?

**Comment by godlike0108** [comment]
My full command with arguments looks like this:
```
az policy assignment create \
--scope "/subscriptions/<subscription-id>/resourceGroups/test-group" \
--policy <require-tag-policy-name> \
-p "{\"tagName\":\"test\"}"
```
And I just figure out that I should always provide a key called `value` to prevent from this error. 
```
az policy assignment create \
--scope "/subscriptions/<subscription-id>/resourceGroups/test-group" \
--policy <require-tag-policy-name> \
-p "{\"tagName\":{"\value\":\"test\"}}"
```

**Comment by zhoxing-ms** [comment]
It's the same problem as #12298

**Comment by zhoxing-ms** [comment]
@godlike0108 This is because the parameters structure of policy assignment is designed in this way  [assignment-structure#parameters](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/assignment-structure#parameters)
Do you have any other questions about this?

**Comment by godlike0108** [comment]
Thanks for the information. I have no questions.
