### ISSUE TITLE
AZure-CLI@2.3.1 not work very well for Azure-China

### ISSUE THREAD

**Issue by lzzgeo** [Azure/azure-cli#12881]
**Describe the bug**
  Can't jump to web-browser when executing 
`az aks browse --resource-group <resource-group-name> --name <k8s-name>`, 
The following is console log:
No registered resource provider found for location 'chinaeast2' and API version '2020-03-01' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31, 2019-02-01, 2019-04-01, 2019-06-01, 2019-08-01, 2019-10-01, 2019-11-01, 2020-01-01, 2020-02-01'. The supported locations are 'chinaeast2, chinanorth2'.

**To Reproduce**
```
brew upgrade azure-cli
az cloud set --name AzureChinaCloud 
az account set --subscription <subscription name>
kubectl config use-context <k8s context>
az aks browse --resource-group <resource-group-name> --name <k8s-name>
```

**Expected behavior**
open a browser tab to show the k8s' status

**Environment summary**
OS:    MacOS Catalina  10.15.3
AZure CLI  Version:  2.3.1

**Additional context**
When switching to k8s in Central US, one browser tab will be opened and show the k8s' status

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
This is due to 2020-03-01 not being available in AzChina yet.

cc @andyzhangx @feiskyer if they know any ETAs

**Comment by andyzhangx** [comment]
cc @karataliu @fseldow

**Comment by andyzhangx** [comment]
try to use an older version by running azure-cli container:
https://github.com/Azure/azure-cli#docker

e.g.
```console
docker run -v ${HOME}:/root -v /usr/local/bin/:/kube -it mcr.microsoft.com/azure-cli:2.2.0
```

**Comment by karataliu** [comment]
The api 2020-03-01 was published, should work now
