### ISSUE TITLE
 az storage account incorrectly requires >3 characters

### ISSUE THREAD

**Issue by mossywell** [Azure/azure-cli#12886]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When running the command 'az storage account keys list' on a storage account with only 3 characters, it errors 'validation error: Parameter 'account_name' must have length greater than 3'. But,  a 3-character storage account name is valid. https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/error-storage-account-name.

**To Reproduce**
az login; az storage account keys list --account-name "yyz" --query [0].value

**Expected behavior**
The command should work as if the storage account had 4 characters. The command should test for >=3 not >3 characters.

**Environment summary**
This can be run from the Bash cloud shell.

**Additional context**
None

**Comment by yonzhan** [comment]
add to S169

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to backlog

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed. Please upgrade to the latest version of azure cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)

az storage account keys list -g issue12886 -n "1bd" --query [0].value
"sWJXsX****************************************************************=="
