### ISSUE TITLE
MariaDB Server does not accept --public-network-access

### ISSUE THREAD

**Issue by odqahn** [Azure/azure-cli#12887]
## Description:
**Command Name**
```
az mariadb server create
az mariadb server update
```

**Errors:**
```
az: error: unrecognized arguments: --public-network-access Disabled
```

## To Reproduce:
Simply try to create or update a mariadb server and disabling the public network access

 `az mariadb server update --name $mariadbServerName --resource-group $rg --public-network-access 'Disabled'`

## Expected Behavior
Should be accepted as documented here: [https://docs.microsoft.com/en-us/cli/azure/mariadb/server?view=azure-cli-latest#az-mariadb-server-create](https://docs.microsoft.com/en-us/cli/azure/mariadb/server?view=azure-cli-latest#az-mariadb-server-create)
and here: [https://docs.microsoft.com/en-us/cli/azure/mariadb/server?view=azure-cli-latest#az-mariadb-server-update](https://docs.microsoft.com/en-us/cli/azure/mariadb/server?view=azure-cli-latest#az-mariadb-server-update)
## Environment Summary
```
Linux-4.15.0-1075-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

```

**Comment by yonzhan** [comment]
mariadb

**Comment by ajlam** [comment]
@kummanish - can you take a look?

**Comment by kummanish** [comment]
The CLI version needs to be changed to : azure-cli 2.3.0
It should work with that version.

**Comment by ramnov** [comment]
Please use [latest cli version 2.3.1](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)

You can check if --public-network-access is a supported argument using the help option : 
az mariadb server create -h
az mariadb server update -h

**Comment by odqahn** [comment]
Thank you for your answer!

I am using cloud shell and I have no idea how to update the CLI there. Tried to restart my session but it did not change anything. And I can't install CLI on my own computer (company restrictions).

I guess this is another issue.

**Comment by ramnov** [comment]
@yonzhan. @Juliehzl  : Why is Azure Cloud Shell still pointing to an older version of azure-cli 2.2.0 ?

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/milestone/85 We plan to build to Cloud Shell three days later.

**Comment by odqahn** [comment]
Tested with latest version of cli, this is indeed working. Once updated in cloud shell, it'll all be ok.

Thank you!
