### ISSUE TITLE
az role assignment delete does not filter using the filter condition passed in --query

### ISSUE THREAD

**Issue by divyamoorthyTR** [Azure/azure-cli#12883]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

az role assignment delete does not filter using the filter condition passed in --query

**To Reproduce**

Execute az role assignments delete request using the --query parameter , still all the role assignments are deleted

**Expected behavior**

On using the --query it should filter out the results before deletion

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
add to S169

**Comment by jiasli** [comment]
`--query` is designed to filter the output. It doesn't affect the input. Besides, the underlying API [Role Assignments - Delete](https://docs.microsoft.com/en-us/rest/api/authorization/roleassignments/delete) doesn't support filtering. 

You may run `az role assignment delete -h` to check supported parameters.
