### ISSUE TITLE
az monitor metrics alert create returns invalid JSON on success.

### ISSUE THREAD

**Issue by bmukes** [Azure/azure-cli#12892]
**Describe the bug**
After a successful call to _az monitor metrics alert create_ in PowerShell 7,  I expect to get a [String] of JSON returned.  Instead I am getting an [Object[50]] because the first two lines of the response are

_ANTLR runtime and generated code versions disagree: 4.8!=4.7.2_

followed by 48 array elements containing the JSON return value.

**See returned value below:**

```
ANTLR runtime and generated code versions disagree: 4.8!=4.7.2
ANTLR runtime and generated code versions disagree: 4.8!=4.7.2
{
	"actions": [{
		"actionGroupId": "/subscriptions/#####/resourceGroups/####/providers/microsoft.insights/actionGroups/###",
		"webhookProperties": null
	}],
	"autoMitigate": null,
	"criteria": {
		"additionalProperties": null,
		"allOf": [{
			"additionalProperties": null,
			"criterionType": "StaticThresholdCriterion",
			"dimensions": [],
			"metricName": "AverageMemoryWorkingSet",
			"metricNamespace": "microsoft.web/sites",
			"name": "cond0",
			"operator": "GreaterThan",
			"threshold": 15032385534.0,
			"timeAggregation": "Average"
		}],
		"odatatype": "Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria"
	},
	"description": "This instance memory working set above 1.4GB.",
	"enabled": true,
	"evaluationFrequency": "0:01:00",
	"id": "/subscriptions/###/resourceGroups/###/providers/Microsoft.Insights/metricAlerts/App Memory Exceeded Threshold",
	"lastUpdatedTime": null,
	"location": "global",
	"name": "App Memory Exceeded Threshold",
	"resourceGroup": "#####",
	"scopes": ["/subscriptions/#####/resourceGroups/#####/providers/Microsoft.Web/sites/#####"],
	"severity": 2,
	"tags": {
		"Environment": "prod",
		"OrganizationIdentifier": "aaa",
		"ProductName": "fse",
		"ResourceType": "Web App Metric Alert"
	},
	"targetResourceRegion": null,
	"targetResourceType": "microsoft.web/sites",
	"type": "Microsoft.Insights/metricAlerts",
	"windowSize": "0:05:00"
}
```
**To Reproduce**
run az monitor metrics alert create for the following values

              "AlertScopeType": "WebApp",
              "AlertName": "App Memory Exceeded Threshold",
              "Evaluationfrequency": "1m",
              "Severity": 2,
              "WindowSize": "5m",
              "Condition": "avg AverageMemoryWorkingSet > 15032385534.0",
              "Description": "This instance memory working set above 1.4GB."

**Expected behavior**
that the response would be JSON as indicated below after I removed two lines indicated above

```
{
	"actions": [{
		"actionGroupId": "/subscriptions/#####/resourceGroups/####/providers/microsoft.insights/actionGroups/###",
		"webhookProperties": null
	}],
	"autoMitigate": null,
	"criteria": {
		"additionalProperties": null,
		"allOf": [{
			"additionalProperties": null,
			"criterionType": "StaticThresholdCriterion",
			"dimensions": [],
			"metricName": "AverageMemoryWorkingSet",
			"metricNamespace": "microsoft.web/sites",
			"name": "cond0",
			"operator": "GreaterThan",
			"threshold": 15032385534.0,
			"timeAggregation": "Average"
		}],
		"odatatype": "Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria"
	},
	"description": "This instance memory working set above 1.4GB.",
	"enabled": true,
	"evaluationFrequency": "0:01:00",
	"id": "/subscriptions/###/resourceGroups/###/providers/Microsoft.Insights/metricAlerts/App Memory Exceeded Threshold",
	"lastUpdatedTime": null,
	"location": "global",
	"name": "App Memory Exceeded Threshold",
	"resourceGroup": "#####",
	"scopes": ["/subscriptions/#####/resourceGroups/#####/providers/Microsoft.Web/sites/#####"],
	"severity": 2,
	"tags": {
		"Environment": "prod",
		"OrganizationIdentifier": "aaa",
		"ProductName": "fse",
		"ResourceType": "Web App Metric Alert"
	},
	"targetResourceRegion": null,
	"targetResourceType": "microsoft.web/sites",
	"type": "Microsoft.Insights/metricAlerts",
	"windowSize": "0:05:00"
}
```

**Environment summary**
### az --version

azure-cli                                           2.3.1

command-modules-nspkg              2.0.3
core                                                  2.3.1
nspkg                                               3.0.4
telemetry                                          1.0.4

Extensions:
azure-firewall                                    0.1.8

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\bdm0609\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLega

 **$PSVERSIONTABLE**

|Name |                          Value
|----   |                        -----
|PSVersion         |             7.0.0
|PSEdition       |               Core
|GitCommitId    |                7.0.0
|OS               |              Microsoft Windows 10.0.18363
|Platform      |                 Win32NT
|PSCompatibleVersions    |       {1.0, 2.0, 3.0, 4.0…}
|PSRemotingProtocolVersion  |    2.3
|SerializationVersion       |    1.1.0.1
|WSManStackVersion      |        3.0

**Additional context**
replaced the subscriptionid, resource group, and web application name in the JSON shown.

**Comment by yonzhan** [comment]
add to S169

**Comment by MyronFanQiu** [comment]
@bmukes Hi. Looks like you installed a new version of ANTLR4 runtime. Could you please run `pip show antlr4-python3-runtime` to see which version you are using? It should be 4.7.2 but you should see 4.8. I'm investigating the root cause right now. To unblock you quickly, you can install the 4.7.2 instead by `pip install antlr4-python3-runtime==4.7.2`

**Comment by MyronFanQiu** [comment]
@jiasli  I just found that in azure-cli-core, we have extra dependency antlr4-python3-runtime. Can you confirm can we remove this one from azure-cli-core package? I would add it into azure-cli setup.py

**Comment by bmukes** [comment]
OK I do not use python and after checking add/remove programs I do not have ANTLR installed.  After using Google I went into Visual Studio 2019 and opened the python environment window and provided screen shots of what I saw there.  Ran the pip show command using the open in powershell window and got no response.

I checked Visual Studio code
```
Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

and I have NO python or ANTLR extensions installed.  I attached a screen shot of enabled extensions in Visual Studio Code.  I am running Windows Terminal version 0.10.781.0 but NOT the Windows Subsystem for Linux. As far as I can tell I have no plugins for ANTLR installed.  My development PC is normally an up to date Windows 10 Professional with Visual Studio 2017,  Visual Studio 2019, Visual Studio Code, Office 365 and Docker.  All development is usually C# and powershell so other items are not installed.  

Please advise what else I can provide to help you with this issue. 

![VisualStudioPythonEnv3 6](https://user-images.githubusercontent.com/2730181/78680509-d153f280-78a8-11ea-8911-810ec31d4a8c.jpg)
![VisualStudioPythonEnv3 7](https://user-images.githubusercontent.com/2730181/78680510-d1ec8900-78a8-11ea-9400-7bbd8eb6548f.jpg)

![VisualStudioextensions](https://user-images.githubusercontent.com/2730181/78681025-74a50780-78a9-11ea-8adc-e02d91299b56.jpg)

**Comment by bmukes** [comment]
sorry did not mean to close it press the wrong button

**Comment by bmukes** [comment]
I also checked the Python location specified in the AZ --version command and could not find a pip command

**Comment by MyronFanQiu** [comment]
@bmukes Hi. Can you share your installation steps for Azure CLI? Which source are you using from? msi or pip?

**Comment by jiasli** [comment]
This dependency was introduced by https://github.com/Azure/azure-cli/pull/7037
```py
if sys.version_info < (3, 0):
    DEPENDENCIES.append('antlr4-python2-runtime')
else:
    DEPENDENCIES.append('antlr4-python3-runtime')
```

`azure-cli-core` doesn't rely on antlr. We can move the dependency to `src/azure-cli/setup.py` instead.

**Comment by MyronFanQiu** [comment]
@bmukes Hi. If you install azure cli through msi, I think you need to wait for the release of new version of Azure CLI. You can also install it again via pip and overwrite the antlr4-python3-runtime to the 4.7.2 version.

**Comment by bmukes** [comment]
My installation is via msi.  I will wait on the release of the new version.  Thanks
