### ISSUE TITLE
AKS missing API 2020-03-01 in Azure Government

### ISSUE THREAD

**Issue by kringen** [Azure/azure-cli#12894]
## Describe the bug

**Command Name**
`az aks show`

**Errors:**
```
No registered resource provider found for location 'usgovvirginia' and API version '2020-03-01' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31, 2019-02-01, 2019-04-01, 2019-06-01, 2019-08-01, 2019-10-01, 2019-11-01, 2020-01-01, 2020-02-01'. The supported locations are 'usgovvirginia, usgovarizona, usgovtexas'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks show -g {} -n {}`

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1

```

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
This is a known issue in the latest API not being published in Azure Gov, AKS team is investigating a resolution. cc @feiskyer

**Comment by coreywagehoft** [comment]
@jluk any updates when this will be resolved?

**Comment by jluk** [comment]
Working on it, should have an ETA this week thank you for the patience. cc @tomgeske

**Comment by TomGeske** [comment]
Deployment should be finished. @kringen let us know in case it still doesn't work.
