### ISSUE TITLE
az sf application update --application-parameters removes old parameters that are not in the request

### ISSUE THREAD

**Issue by a-santamaria** [Azure/azure-cli#12891]
## Describe the bug
Update application using --application-parameters replaces all the current parameters with the ones provided in the command instead of adding and updating them, so it will remove previous parameters that are not passed in the command.

**Command Name**
`az sf application update` 

## To Reproduce:
run az sf application update with parameter `--application-parameters`

## Expected Behavior
Don't remove old parameters. only update/add the ones provided in the cmdlet.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.7.1
Installer: PIP

azure-cli 2.3.0 *

Extensions:
interactive 0.4.3

```

**Comment by yonzhan** [comment]
sf
