### ISSUE TITLE
AKS - Azure China missing 2020-03-01 in cli 2.3.1

### ISSUE THREAD

**Issue by xinlizhou** [Azure/azure-cli#12895]
> ### No registered resource provider found for  API version '2020-03-01' for  type 'managedClusters'

**Describe the bug**
Command Name
az aks get-credentials 

Errors:
No registered resource provider found for location 'chinaeast2' and API version '2020-03-01' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31, 2019-02-01, 2019-04-01, 2019-06-01, 2019-08-01, 2019-10-01, 2019-11-01, 2020-01-01, 2020-02-01'. The supported locations are 'chinaeast2, chinanorth2'.

**To Reproduce**
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

az aks get-credentials --resource-group {} --name {}

**Expected behavior**

**Environment summary**
Windows-10-10.0.18362
Python  3.8.2
Installer: MSI

azure-cli 2.3.1

**Additional context**

**Comment by yungezz** [comment]
thanks for reporting, routing to appropriate team

**Comment by jluk** [comment]
This is a known issue and is being investigated cc @feiskyer

**Comment by feiskyer** [comment]
@xinlizhou Could you use an older version of CLI as a mitigation? API version 2020-03-01 is not supported yet on AKS China.

**Comment by andyzhangx** [comment]
try to use an older version by running azure-cli container:
https://github.com/Azure/azure-cli#docker

e.g.
```console
docker run -v ${HOME}:/root -v /usr/local/bin/:/kube -it mcr.microsoft.com/azure-cli:2.2.0
```

**Comment by xinlizhou** [comment]
Thanks a lot@andyzhangx @feiskyer!

**Comment by Icybiubiubiu** [comment]
Hi~
if I want to use azcli on Mac OS client, how can download the old version, 2.2.0 for example.

**Comment by feiskyer** [comment]
@yonzhan do we have guides to install older versions for Windows and MacOS?

**Comment by yonzhan** [comment]
@fengzhou-msft to provide guidance.

**Comment by fjferdiez** [comment]
For windows installation I found that this link would work:
https://azurecliprod.azureedge.net/msi/azure-cli-2.2.0.msi

**Comment by feiskyer** [comment]
thanks @yonzhan @fjferdiez for the guides.

**Comment by Jen7714** [comment]
Please see the fix here: https://github.com/Azure/azure-cli/issues/13047
