### ISSUE TITLE
Some more advanced examples would be nice

### ISSUE THREAD

**Issue by batanun** [Azure/azure-cli#12901]
An example of an advance example could be how to add an IP to a security rule.

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: d1559576-e557-21a3-cd99-81df8978e8d2
* Version Independent ID: e33f3fe2-041f-324c-4f42-3cc82ac40c80
* Content: [az network nsg](https://docs.microsoft.com/sv-se/cli/azure/network/nsg?view=azure-cli-latest#az-network-nsg-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by qianwens** [comment]
@MyronFanQiu, please help take a look.

**Comment by yonzhan** [comment]
add to S169

**Comment by yonzhan** [comment]
add to S171

**Comment by MyronFanQiu** [comment]
@batanun Please take a look at `az network nsg rule create -h`. I think we have enough examples.

**Comment by MyronFanQiu** [comment]
closed this issue since it's by design.
