### ISSUE TITLE
Bypass firewall for Microsoft service option in 'az eventhubs namespace network-rule add' 

### ISSUE THREAD

**Issue by gandhirajan** [Azure/azure-cli#12903]
When I create an eventhub namespace and eventhub using Azure CLI, by default 'Allow trusted Microsoft services to bypass this firewall?' option is set to 'No' under 'Firewalls and virtual networks'.

I don't see any option to turn this to 'Yes' in 'az eventhubs namespace network-rule add' CLI command. Can't this option be turned to 'Yes' from CLI command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6521201-7341-0a6c-b9f6-dbbacf79ca0b
* Version Independent ID: 71ec7f9a-9e01-a9b2-de00-0b5966238921
* Content: [az eventhubs namespace network-rule](https://docs.microsoft.com/en-us/cli/azure/eventhubs/namespace/network-rule?view=azure-cli-latest#az-eventhubs-namespace-network-rule-add)
* Content Source: [src/azure-cli/azure/cli/command_modules/eventhubs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/eventhubs/_help.py)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
eventhubs

**Comment by gandhirajan** [comment]
@jfggdl @yonzhan Hi Team, Any update on this?

**Comment by yonzhan** [comment]
eventhubs service can help update.

**Comment by gandhirajan** [comment]
@dsouzaarun @v-Ajnava  Hi, Its been a month now and I dont see any update on this issue. Can you please provide me some details on this?

**Comment by PaulCharlton** [comment]
+1 -- same issue.    "network-policy add" does not work for this purpose either.

**Comment by PaulCharlton** [comment]
Is there any means via the az CLI to set the "defaultAction" in the resource below?    I have only been able to change it manually via the online portal.

`az eventhubs namespace network-rule list --resource-group {redacted} --namespace-name {redacted}`

`{
  "defaultAction": "Deny",
  "id": "/subscriptions/{redacted}/resourceGroups/{redacted}/providers/Microsoft.EventHub/namespaces/{redacted}/networkRuleSets/default",
  "ipRules": [ ],
  "location": "East US",
  "name": "default",
  "resourceGroup": "{redacted}",
  "type": "Microsoft.EventHub/Namespaces/NetworkRuleSets",
  "virtualNetworkRules": []
}`

**Comment by Suseelraj** [comment]
Any updates on this feature yet? Everytime I update the settings, it redacts to "no" bit frustrating

**Comment by samuelkoppes** [comment]
We are investigating this issue and will share an update by 11/4/2020.

**Comment by kvendingoldo** [comment]
@samuelkoppes do you have any updates? I wanna introduce this option to TF provider

**Comment by kvendingoldo** [comment]
@samuelkoppes looks like that package eventhub = 2018-01-01-preview do not have the suitable option ...

**Comment by kvendingoldo** [comment]
Issue https://github.com/Azure/azure-rest-api-specs/issues/11425 created, let's wait for an answer.

**Comment by navba-MSFT** [comment]
@gandhirajan @kvendingoldo Apologies for the late reply. We are looking into this issue. We will update this thread once we have more details on this. 

@jfggdl Could you please look into this issue and provide an update on this ? Awaiting your reply.

**Comment by gandhirajan** [comment]
@Saglodha I guess its 'enable-trusted-service-access' as per the document. Will check on this.

**Comment by gandhirajan** [comment]
Works as expected using the new 'enable-trusted-service-access' parameter. Thanks, everyone for fixing this finally.
