### ISSUE TITLE
Add ability to attach subnet to NSG when using az network vnet create

### ISSUE THREAD

**Issue by adhodgson1** [Azure/azure-cli#12905]
**Is your feature request related to a problem? Please describe.**
Using a subscription with a subnet NSG enforced policy as per this link:
https://github.com/Azure/azure-policy/tree/master/samples/Network/enforce-nsg-on-subnet
It is not possible to create a new virtual network using the Azure CLI.

Creating the vnet without a subnet fails due to the policy with the following command:
az network vnet create -n my-vnet -g my-resource-group --address-prefixes 10.0.0.0/8

When I tried to create the subnet in the same command I realised there was no way of attaching the nsg to the subnet in one step using the az network vnet create command.

**Describe the solution you'd like**
Add an option to attach an existing nsg to the subnet as part of the az network vnet create command. I am up for looking at alternative policy solutions as well as this doesn't just affect the Azure CLI, any orchestration tool which creates the vnet and subnet in separate requests are also failing, I was looking at using the Azure CLI to work around this issue temporairily.

**Describe alternatives you've considered**
Currently the only way I can create the vnet and subnet in this subscription is to use an ARM template which defines the vnet and subnet as a single resource.

**Additional context**
Here is the policy we currently have deployed:
```
{
  "properties": {
    "mode": "all",
    "displayName": "Network Security Groups (Subnets)",
    "description": "This policy restricts the creation of Subnets unless they have an NSG assigned to them",
    "policyRule": {
      "if": {
        "anyOf": [
          {
            "allOf": [
              {
                "field": "type",
                "equals": "Microsoft.Network/virtualNetworks"
              },
              {
                "field": "Microsoft.Network/virtualNetworks/subnets[*].networkSecurityGroup.id",
                "exists": "false"
              }
            ]
          },
          {
            "allOf": [
              {
                "field": "type",
                "equals": "Microsoft.Network/virtualNetworks/subnets"
              },
              {
                "field": "Microsoft.Network/virtualNetworks/subnets/networkSecurityGroup.id",
                "exists": "false"
              }
            ]
          }
        ]
      },
      "then": {
        "effect": "deny"
      }
    },
    "parameters": {}
  }
}
```

**Comment by qianwens** [comment]
@MyronFanQiu , please help take a look at this issue.

**Comment by yonzhan** [comment]
add to S169

**Comment by yonzhan** [comment]
add to S171
