### ISSUE TITLE
Do the samples work?

### ISSUE THREAD

**Issue by pvanroos** [Azure/azure-cli#12906]
Did you test them?  I can't get some of them to work.  For example, this one doesn't work even when I put in a valid subscription id:
az policy set-definition create -n readOnlyStorage --definitions '[
        { "policyDefinitionId": "/subscriptions/mySubId/providers/Microsoft.Authorization/policyDefinitions/storagePolicy" }
    ]'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe29c90-ab37-174c-3365-d33044447272
* Version Independent ID: 3118d6a2-bb53-a881-0017-0313a15c9ef1
* Content: [az policy set-definition](https://docs.microsoft.com/en-us/cli/azure/policy/set-definition?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by qianwens** [comment]
@zhoxing-ms please help take a look.

**Comment by yonzhan** [comment]
add to S169

**Comment by zhoxing-ms** [comment]
@pvanroos Thanks for your feedback, it seems that example is not friendly to users, I have submitted a PR to improve it.

For the `az policy set-definition create` command, please use it like this:
```
az policy set-definition create -n readOnlyStorage --definitions '[ { \"policyDefinitionId\": \"/subscriptions/mySubId/providers/Microsoft.Authorization/policyDefinitions/storagePolicy\" } ]'
```
