### ISSUE TITLE
[Breadth Coverage] Onboard CostManagement Commands

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#12912]
**Spec Link**
https://microsoft.sharepoint.com/:w:/t/AzureManagementExperience/EQkYn3bWYbxFhl7xfVAIHLsBgU4uf0IfwSbBRnm7Xgy-_Q?e=HIdYqk

**ADO Work Item Link**
https://dev.azure.com/azure-mgmt-ex/Onboarding/_workitems/edit/146

**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.CostManagement

**Description of Feature or Work Requested**
Support Azure CLI commands for CostManagement 

**Minimum API Version Required**
Microsoft.CostManagement 2019-11-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2019-11-01

**Python SDK Link**
Not ready

**Target Date**
05/19/2020

**Addtional context**
We'll use [autorest.az](https://github.com/Azure/autorest.az/blob/master/doc/01-authoring-azure-cli-commands.md) from code gen team to auto-generate the code first and may need update some code manually if the generated code doesn't meet your requirements.

**Comment by jsntcy** [comment]
@haroldrandom, if you have time, you can review the spec and play with the key use cases in Azure portal first.

**Comment by yonzhan** [comment]
add to S169

**Comment by haroldrandom** [comment]
@jsntcy What's the status of this command? is preview, is experimental or neither?

**Comment by yonzhan** [comment]
@haroldrandom  is experimental for new breadth coverage
