### ISSUE TITLE
SSL Certificate Verification Can't be turned off for azure-ml 

### ISSUE THREAD

**Issue by ameert** [Azure/azure-cli#12911]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
AZURE_CLI_DISABLE_CONNECTION_VERIFICATION doesn't work with az-ml operations. https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy

**To Reproduce**
Install the CLI on a computer that requires AZURE_CLI_DISABLE_CONNECTION_VERIFICATION =1 to successfully connect to azure. Then install the az-ml-cli. Then try to run ml commands (connect to a workspace). This fails with 
ClientRequestError: Error occurred in request., SSLError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded
 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

**Expected behavior**
ML commands should work successfully without requiring certificate verification, since it was disabled.

**Environment summary**
Windows 10 computer. Installed using the standard msi installer

**Additional context**

**Comment by yonzhan** [comment]
ML

**Comment by swatig007** [comment]
@ameert apologies for the delayed response. is this still an issue?

**Comment by swatig007** [comment]
closing due to no response
