### ISSUE TITLE
SDN Missing properties on multiple commands & column order incorrect

### ISSUE THREAD

**Issue by malopMSFT** [Azure/azure-cli#1292]
Missing properties on all SDN commands
Attached is the analysis made comparing Python CLI with PS CLI

[az_network_table_output.txt](https://github.com/Azure/azure-cli/files/584652/az_network_table_output.txt)

[azure_network_table_output.txt](https://github.com/Azure/azure-cli/files/584653/azure_network_table_output.txt)

Files are Sync for easy comparison with lock scroll, same lines for same commands.
The following format after each command
#+ExtraProperty1, +ExtraPropertyN #*ChangedProperty  # -MissingProperty1, -MissingProperty2

Extra properties are ok, but missing must be included.

Additional with low priority, sync property order since some of those cases are not easy to read due the random column order.

**Comment by tjprescott** [comment]
- [ ] vnet: Add type, address prefixes, subnets
- [ ] vnet peering show: Add 'allow_virtual_network_access', 'allow_forwarded_traffic', 'allow_gateway_transit', 'use_remote_gateways', 'remove_virtual_network'
- [ ] lb list: Add probe, FIP, backend pool, rule, inbound NAT rule, inbound NAT pool, outbound nat rule
- [ ] lb show: Add type, frontend IP configs, probes, BAP, LB rules, inbound NAT rules
- [ ] lb frontend-ip list: Add private IP, subnet, public IP
- [ ] lb proble list: Add path
- [ ] lb rule list: Add "enable_floating_ip"
- [ ] lb inbound-nat-rule list: Add enable_floating_ip
- [ ] public-ip list: Add FQDN
- [ ] public-ip show: Add type, IP config ID
- [ ] nic list: Add IP forwarding, internal DNS name, internal FQDN, internal domain name suffix
- [ ] nic show: Add type, internal domain name suffix, enable IP forwarding, IP configs
- [ ] nic list-effective-nsg, show-effective-route-table: not supported
- [ ] nic ip-config list: primary, subnet, public-ip
- [ ] nic ip-config show: primary, subnet
- [ ] nsg list: rules number
- [ ] nsg show: type, security rules
- [ ] nsg rule show: type

**Comment by MyronFanQiu** [comment]
@malopMSFT Hello. Is this issue still used? or will us use the CLI Gap V2?

**Comment by yonzhan** [comment]
@malopMSFT any update for this issue?

**Comment by MyronFanQiu** [comment]
@malopMSFT Hello. Since this one is quite old and this issue is quite hard for us to track, I closed this one first. If necessary, could we open separated issue?
