### ISSUE TITLE
cannot attach ACR to AKS cluster

### ISSUE THREAD

**Issue by T-Grave** [Azure/azure-cli#12924]
## Describe the bug

**Command Name**
`az aks update`

**Errors:**
```
Operation failed with status: 'Bad Request'. Details: UnmarshalEntity encountered error: json: cannot unmarshal bool into Go struct field Properties.properties.autoScalerProfile of type string.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update -n {} --resource-group {} --attach-acr {}`

## Expected Behavior
To not return this error

## Environment Summary
```
Linux-5.3.0-7642-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.3.1

```

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
@T-Grave could you reproduce the error and share the full debug error produced from azcli?

If this is the error returned from the AKS service we'll need to take a look via a support ticket.

**Comment by T-Grave** [comment]
Oh I'm sorry, I can't. I already removed my entire `.azure`  folder, setup az cli again and it's been working fine ever since :)

My issue is solved, so I guess we can close this?

**Comment by jluk** [comment]
Thanks for confirm!
