### ISSUE TITLE
Create VM/VMSS CLI command needs to support specialized SIG Image Version based deployments

### ISSUE THREAD

**Issue by axayjo** [Azure/azure-cli#12927]
**Is your feature request related to a problem? Please describe.**

We launched specialized image support in SIG and there's no way to create a VM/VMSS with a specialized SIG image today. 

**Describe the solution you'd like**

The current command needs to support a specialized flag which when passed shouldn't pass the OSProfile to the PUT VM call:

az vm create\
   --resource-group myGalleryRG \
   --name myVM \
   --image "/subscriptions/subscription ID where the gallery is located>/resourceGroups/myGalleryRG/providers/Microsoft.Compute/galleries/myGallery/images/myImageDefinition/versions/1.0.0" \
   --specialized 
   --generate-ssh-keys
The OSState property on the Image Definition determines if an image is Generalized/Specialized. 

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by axayjo** [comment]
Thanks @qwordy!

**Comment by qwordy** [comment]
You are welcome

**Comment by qwordy** [comment]
Azure CLI 2.4.0 is released. Now you can try this feature.
