### ISSUE TITLE
Example error for "az cdn endpoint rule add"

### ISSUE THREAD

**Issue by t-bzhan** [Azure/azure-cli#12929]
The example for "Create a rule for http to https redirect" at
https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint/rule?view=azure-cli-latest#az-cdn-endpoint-rule-add is wrong. Match value should be "HTTP" instead of "HTTPS"

I see this is mentioned in https://github.com/Azure/azure-cli/issues/12072#issuecomment-589829200, but it is still not fixed yet.

![image](https://user-images.githubusercontent.com/61817681/78857135-2a638800-7a5b-11ea-920d-0cd34b5d1147.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fef54fc4-b4a8-d366-40de-a0ae2586961d
* Version Independent ID: 1231852d-d3b4-9bcf-e9d4-ba12cffb7603
* Content: [az cdn endpoint rule](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint/rule?view=azure-cli-latest#az-cdn-endpoint-rule-add)
* Content Source: [src/azure-cli/azure/cli/command_modules/cdn/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cdn/_help.py)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cdn

**Comment by hytao** [comment]
This is a typo and we'll fix it in the future update.
