### ISSUE TITLE
invalid SAS token 'az storage container generate-sas'

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/azure-cli#12935]
## Describe the bug

SAS generated with 'az storage container generate-sas' does not work.

**Command Name**
`az storage container generate-sas`

**Errors:**

When copying a file to storage account container, using 'azcopy copy' and the SAS generated, get AuthorizationPermissionMismatch error.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

`az storage container generate-sas --account-name <accountname> --name <containername> --permissions acdlrw --start 2020-04-09T16:01:42Z --expiry 2020-04-10T00:01:42Z --auth-mode login --as-user`

Returns:

`"st=2020-04-09T16%3A01%3A42Z&se=2020-04-10T00%3A01%3A42Z&sp=racwdl&sv=2018-11-09&sr=c&skoid=718cba0a-f84a-4f0a-880b-51d980a5d11a&sktid=97665603-7deb-45ac-87ad-7f5c6951c211&skt=2020-04-09T16%3A01%3A42Z&ske=2020-04-10T00%3A01%3A42Z&sks=b&skv=2018-11-09&sig=<sig>"`

Then try and use in a azcopy copy command:

`azcopy copy test.txt "https://<accountname>.blob.core.windows.net/<containername>?st=2020-04-09T16%3A01%3A42Z&se=2020-04-10T00%3A01%3A42Z&sp=racwdl&sv=2018-11-09&sr=c&skoid=718cba0a-f84a-4f0a-880b-51d980a5d11a&sktid=97665603-7deb-45ac-87ad-7f5c6951c211&skt=2020-04-09T16%3A01%3A42Z&ske=2020-04-10T00%3A01%3A42Z&sks=b&skv=2018-11-09&sig=<sig>"`

```
RESPONSE ERROR (ServiceCode=AuthorizationPermissionMismatch)
Description=This request is not authorized to perform this operation using this permission.
RequestId:194d2950-e01e-0025-668c-0eae12000000
Time:2020-04-09T16:34:31.8382045Z, Details:
   Code: AuthorizationPermissionMismatch
   PUT https://acdevcadevicesim.blob.core.windows.net/devicesim/test.txt?se=2020-04-10t00%3A01%3A42z&sig=-REDACTED-&ske=2020-04-10t00%3A01%3A42z&skoid=718cba0a-f84a-4f0a-880b-51d980a5d11a&sks=b&skt=2020-04-09t16%3A01%3A42z&sktid=97665603-7deb-45ac-87ad-7f5c6951c211&skv=2018-11-09&sp=racwdl&sr=c&st=2020-04-09t16%3A01%3A42z&sv=2018-11-09&timeout=901
   Content-Length: [14]
   User-Agent: [AzCopy/10.3.4 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Md5: []
   X-Ms-Blob-Content-Type: [text/plain; charset=utf-8]
   X-Ms-Blob-Type: [BlockBlob]
   X-Ms-Client-Request-Id: [5d20c6e9-7528-41ff-4b83-894efaf6ad4a]
   X-Ms-Version: [2018-03-28]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
   Content-Length: [279]
   Content-Type: [application/xml]
   Date: [Thu, 09 Apr 2020 16:34:31 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthorizationPermissionMismatch]
   X-Ms-Request-Id: [194d2950-e01e-0025-668c-0eae12000000]
   X-Ms-Version: [2018-03-28]`

```

If I then run the following 'azcopy copy' command with an SAS directly generated in the portal, it works.

`azcopy copy test.txt "https://<accountname>.blob.core.windows.net/<containername>?sv=2019-02-02&ss=b&srt=sco&sp=rwdlac&se=2020-04-10T00:01:42Z&st=2020-04-09T16:01:42Z&spr=https&sig=<sig>`

## Expected Behavior

File copy to container.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1

```

**Comment by yonzhan** [comment]
add to S169

**Comment by yonzhan** [comment]
add to S171

**Comment by spoltier** [comment]
I encounter a similar / the same issue.

I'm getting 

```
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:d11ca53b-701a-001f-0d2f-29a889000000
Time:2020-05-13T14:02:27.8312131Z, Details:
   AuthenticationErrorDetail: Signature fields not well formed.
   Code: AuthenticationFailed
   GET https://lrpstorage.file.core.windows.net/lrppermanenttest/path_omitted?restype=directory&se=2020-05-14t12%3A00%3A00z&sig=-REDACTED-&ske=2020-05-14t12%3A00%3A00z&skoid=f84a8784-1e2b-4bfc-b156-c58b7824d28a&sks=b&skt=2020-05-13t12%3A25%3A57z&sktid=473672ba-cd07-4371-a2ae-788b4c61840e&skv=2018-11-09&sp=racwdl&sr=c&sv=2018-11-09&timeout=901
   User-Agent: [AzCopy/10.4.3 Azure-Storage/0.7.0 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [a9ae795a-8223-4cf0-7852-82a3441d8d75]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [408]
   Content-Type: [application/xml]
   Date: [Wed, 13 May 2020 14:02:27 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [d11ca53b-701a-001f-0d2f-29a889000000]
```

What I have noticed is that the `sig=...`part of the URL, which is redacted for obvious reasons, contains a literal slash (`/`) character, which is _not_ URL encoded.

Let me know if I should open a different issue.

**Comment by Juliehzl** [comment]
@RotateAt60MPH Could you check your RBAC role for the storage account? To copy files to the storage account, you will need at least "Storage Blob Data Contributor" role to perform the operation. For more information, you can refer to https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas
