### ISSUE TITLE
Unable to add target to Application gateway backend pool list

### ISSUE THREAD

**Issue by agaponenko-incomm** [Azure/azure-cli#12934]
## Describe the bug

**Command Name**
`az network application-gateway address-pool update`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network application-gateway address-pool update --resource-group glx-qa1-rg --gateway-name glx-qa1-agw01 --name pool01 --add backendAddresses {\"ip_address\":\"10.20.0.68\"}`
- `az network application-gateway address-pool update --resource-group glx-qa1-rg --gateway-name glx-qa1-agw01 --name pool01 --add backendAddresses {\"ip_address\":\"10.20.0.69\"}`

## Expected Behavior
I expect Application Gateway pool01 contains 2 endpoints: 10.20.0.68 and 10.20.0.69, but this commands rewrites backend pool and it contains only last address 10.20.0.69.

## Environment Summary
```
Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
Python 3.6.8
Installer: RPM

azure-cli 2.3.1

```

**Comment by yonzhan** [comment]
add to S169

**Comment by yonzhan** [comment]
add to S171

**Comment by MyronFanQiu** [comment]
`az network application-gateway address-pool update --gateway-name dekey-firewall --name test-apps --resource-group dekey --servers 20191030R2-Ontwikkel.azurewebsites.net 10.20.0.68` should work

**Comment by subhasishdc** [comment]
@MyronFanQiu : The command you mentioned does not work and has the same behavior as mentioned in the bug. It removes the existing hosts in the backend pool and adds the ones which are part of the "--servers" directive. A workaround for this is providing the entire pool list (existing ones and new ones being added) as part of the "--servers" directive. 

The documentation for this is very vague and more clarity should be provided in the documentation regarding this: https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/address-pool?view=azure-cli-latest#az-network-application-gateway-address-pool-update

**Comment by MyronFanQiu** [comment]
@subhasishdc You're correct. It's an update command instead of add. We would refine help message based on your suggestion. Thank!

**Comment by subhasishdc** [comment]
@MyronFanQiu : Thanks, do you accept contributions from users on this. If yes, I can submit the change in the help message for review. If not, will wait for you/the team to do it.

**Comment by MyronFanQiu** [comment]
> @MyronFanQiu : Thanks, do you accept contributions from users on this. If yes, I can submit the change in the help message for review. If not, will wait for you/the team to do it.

That's very nice. We're eager for community's contributions. If you want, you can open a PR and invite me as the reviewer.

**Comment by subhasishdc** [comment]
@MyronFanQiu : I opened a PR for refining the help message and adding examples - https://github.com/Azure/azure-cli/pull/13780

**Comment by MyronFanQiu** [comment]
@agaponenko-incomm Looks like this is the same issue with #13599. Is it ok to close this one and we can discuss in #13599?

**Comment by agaponenko-incomm** [comment]
> @agaponenko-incomm Looks like this is the same issue with #13599. Is it ok to close this one and we can discuss in #13599?

Do everything that helps you to resolve this issue. I'm the first who register this trouble and it's not obvious for me why you want to close my issue instead of duplicate.

**Comment by MyronFanQiu** [comment]
Oh. glad to see you. 😄 Let's keep both issues.
