### ISSUE TITLE
[Service Team Request] CLI support needed for New LB backend format

### ISSUE THREAD

**Issue by ninzavivek** [Azure/azure-cli#12937]
**Resource Provider**
Networking (NRP)

**Description of Feature or Work Requested**
CLI changes to support newly added Create/Update operation for backend pool and format.

**Minimum API Version Required**
2020-04-01

**Swagger Link**
Here is the PR link : https://github.com/Azure/azure-rest-api-specs/pull/8993

**Target Date**
May-end ( Manganese end).

**Comment by ninzavivek** [comment]
@gmainar - FYI

**Comment by MyronFanQiu** [comment]
@ninzavivek Hi, I want to confirm one thing. Before this issue and your PR, can customer create backend pool? I cannot do it in Azure CLI.

**Comment by ninzavivek** [comment]
> @ninzavivek Hi, I want to confirm one thing. Before this issue and your PR, can customer create backend pool? I cannot do it in Azure CLI.

**Comment by ninzavivek** [comment]
closed by mistake.

**Comment by ninzavivek** [comment]
> @ninzavivek Hi, I want to confirm one thing. Before this issue and your PR, can customer create backend pool? I cannot do it in Azure CLI.

Yes, earlier it was done as part of whole LB put operation.

**Comment by ninzavivek** [comment]
DEL operation support is also needed - https://github.com/Azure/azure-rest-api-specs/pull/9040

**Comment by anavinahar** [comment]
Can we get an ETA for this?

**Comment by MyronFanQiu** [comment]
@ninzavivek This new feature need 2020-04-01 api-version which has not been released yet. After the release of new sdk, we need to bump version first. Currently, we have another issue with higher priority to solve. If everything goes well, we might be able to catch S169(Official Release: 05/19/2020) release train. If we don't have enough bandwidth in this sprint, we should be able to catch S160, whose release date is 06/02/2020.

**Comment by anavinahar** [comment]
Please confirm as we need to align on preview dates and GA dates accordingly. @MyronFanQiu

**Comment by yonzhan** [comment]
We can set 06/02/2020 as release date.

**Comment by erichrt** [comment]
Hi @yonzhan, @MyronFanQiu thanks for the update on release date. Do we already have a design of the CLI commands? 

I will set up a meeting so we can collaborate on the release of these commands as part of the feature preview
