### ISSUE TITLE
Azure CLI operations are not generating any activity logs

### ISSUE THREAD

**Issue by kaushal40** [Azure/azure-cli#12941]
**Describe the bug**
Trying to list the activity-logs using CLI for the (list - resources, VM) operations but don't see any logs generated for the activities performed. Based on the architecture CLI requests goes through ARM `https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview` and activity log is all the activity performed through ARM. 

**To Reproduce**
1. Connect to azure with CLI (make sure you have enough permissions) `az login`
2. Perform ant list operations  e.g `az list resource`
3. Wait for sync time there can be latency (5 minutes max)
4. Try to fetch activity log, either through UI or CLI `az monitor activity-log list --offset 10m`

**Expected behavior**
Should list the logs of recent activities

**Environment summary**
CLI version 2.0.72

**Comment by yonzhan** [comment]
add to S169

**Comment by yonzhan** [comment]
add to S171

**Comment by jiasli** [comment]
This is not only limited to Azure CLI but to Azure itself. 

According to doc [View activity logs to monitor actions on resources](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/view-activity-logs):

> The activity log contains all write operations (PUT, POST, DELETE) for your resources. It doesn't include read operations (GET).

If you need to retrieve activity logs for `GET` operations, you may create a support request in Azure Portal and a support engineer will gladly help you retrieve the information from back-end. Thanks for understanding.
