### ISSUE TITLE
handle-extended-json-format is both deprecated and in preview.

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#12943]
## Describe the bug
CLI shows the feature is both deprecated, and in preview. Is that right?

  --handle-extended-json-format -j [Deprecated] [Preview] : Support to handle
                                                              extended template content including
                                                              multiline and comments in deployment.
        Option '--handle-extended-json-format/-j' has been deprecated and will be removed in a
        future release. Argument '--handle-extended-json-format' is in preview. It may be
        changed/removed in a future release.

**Command Name**
`az deployment group validate`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az deployment group validate -h`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.3.1

Extensions:
interactive 0.4.3

```

**Comment by yonzhan** [comment]
add to S168

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele Thanks for your feedback, this is a known design. My plan is to remove `is_preview` from this sprint and delete this parameter completely in the next sprint.
If you have any good suggestions for this, please feel free to let me know, thanks~
