### ISSUE TITLE
[SSH] - Update docs to reflect az webapp ssh is in preview and only supported on linux and mac

### ISSUE THREAD

**Issue by cfmayer** [Azure/azure-cli#12940]
It would be good to note in the documentation that the ssh command is in preview and does not work on Windows. When running on Windows, the following message is displayed:

This command is in preview. It may be changed/removed in a future release.
webapp ssh is only supported on linux and mac

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@btardif FYI

**Comment by mloskot** [comment]
I'm running Azure CLI 2.15.0 on Windows 10 from within PowerShell 7:

```
❯ az webapp ssh `
>>   --resource-group $AzResourceGroup `
>>   --name $AzWebApp
This command is in preview. It may be changed/removed in a future release.
webapp ssh is only supported on linux and mac
```

where my `$AzWebApp` points to Linux-based Web App (`az appservice plan create  --sku P1v2  --is-linux ...`).

Now, the error message above can mean two things:
1. `webapp ssh` requires Linux host
2. `webapp ssh` requires Linux-based Web App

Obviously, I the 2. requirement is met in my case. Does the error message actually mean the 1. ?

A clearer error message and documentation clarifying that would be very helpful.

**Comment by btardif** [comment]
This is being tracked here: #16125
