### ISSUE TITLE
On-board SQL Commands

### ISSUE THREAD

**Issue by jsakamoto** [Azure/azure-cli#1294]
@gregjhogan posted new issue for azure-xplat-cli ( https://github.com/Azure/azure-xplat-cli/issues/2204 ), so I have same request for new azure-cli.

> Please add the following commands to ~~ARM mode~~ "az" azure-cli:
>
> **Commands to manage your SQL Server database servers**
>
> ```
> sql server create [options]
> sql server show [options]
> sql server list [options]
> sql server delete [options]
> ```
>
> **Commands to manage your SQL Server firewall rules**
> 
> ```
> sql firewallrule create [options]
> sql firewallrule show [options]
> sql firewallrule list [options]
> sql firewallrule delete [options]
> ```
>
> **Commands to manage your SQL Server databases**
> ```
> sql db create [options]
> sql db list [options]
> sql db show [options]
> sql db delete [options]
> ```

**Comment by jsakamoto** [comment]
Of course, I don't mind command line syntax. I want an ability to control SQL Database from command line tool.

**Comment by tjprescott** [comment]
Hi @jsakamoto we plan on adding SQL support in the coming months. Please check back periodically. Thanks!

**Comment by jsakamoto** [comment]
@tjprescott Thank you for replay. I'm looking forward to release day. 

In my case, I often open/close IP based firewall from my remote working space, that is dynamic changing global IP address, for temporary maintenance job.

I appreciate if this job can finished with one click my script powered by "az" azure-cli. 

Thanks!

**Comment by tjprescott** [comment]
Thanks @jsakamoto! This will help us prioritize the on-boarding of commands. SQL team is working hard behind the scenes to enable us to bring this functionality to the CLI. Right now I've put this on the backlog, but you should get updates when it is scheduled for an upcoming milestone.

**Comment by mayurid** [comment]
Adding it to upcoming Sprint 8. We will have some key things lighting up and will go incrementally from there.

**Comment by jsakamoto** [comment]
> Adding it to upcoming Sprint 8.

Wow, it is good news!
I appreciate for your rapid response.
Thanks!

**Comment by troydai** [comment]
Most of the commands are in. @vishrutshah is helping with validating and adding test cases.

**Comment by vishrutshah** [comment]
All the requested commands have been implemented and validated. Please refer [src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/tests/test_sql_commands.py](https://github.com/Azure/autorest/blame/f355d9da3eac692392bd6254224d33c0fcebeb9b/src/modeler/AutoRest.Swagger/Validation/UniqueResourcePaths.cs) to see the usage examples. Thanks!

**Comment by jsakamoto** [comment]
Thanks everyone.

azure-cli-sql 0.1.1b2 works fine for my use case! 😄 

https://gist.github.com/jsakamoto/827fb9eefc22a1faeae47507a66ab740
