### ISSUE TITLE
az webapp create without starting it

### ISSUE THREAD

**Issue by larsmaes** [Azure/azure-cli#12955]
For deployment purposes i want to create the webapp first without starting it immediatly. Some other az webapp commands need to be run after with a manual start command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by panchagnula** [comment]
@larsmaes can you clarify what you clarify your ask please? Do you need the app to be in stopped state? Once the app is created the app automatically set to running state. Have you tried to explicitly stop the app after az webapp create using command https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-stop

**Comment by panchagnula** [comment]
closing due to lack of response.

**Comment by mloskot** [comment]
@panchagnula I think I'm having similar issue as  @larsmaes had. I'm trying to create a Web App, then configure its settings and then trigger the deployment. Here is the sequence of commands:

```powershell
az appservice plan create `
  --resource-group $AzResourceGroup `
  --name $AzServicePlan `
  --sku P1v2 `
  --is-linux

az webapp create `
  --resource-group $AzResourceGroup `
  --plan $AzServicePlan `
  --name $AzApp `
  --runtime '"NODE|12-lts"' `
  --deployment-source-url "https://example.com/repo.git" `
  --deployment-source-branch "master" `
  --startup-file "/home/site/wwwroot/prepare-and-start.sh"

# Here, the app is created and the deployment starts but the app startup will fail because the settings are not in place yet

# Let's complete the configuration settings:
az webapp config appsettings set `
  --resource-group $AzResourceGroup `
  --name $AzApp `
  --settings `
    WEBSITE_VNET_ROUTE_ALL="1" `
    WEBSITE_DNS_SERVER="168.63.129.16" `
    NODE_ENV="production" `
    DB_HOST="xxx" `
    DB_PORT="1234" `
    DB_DATABASE="xxx" `
    DB_USER="xxx" `
    DB_PASSWORD="xxx"
```

Now, how to force the **re-deployment** of the app so it starts up with the correct and complete settings?

I guess, it may be something along these lines, but that seems not correct, is it?

```powershell
az webapp restart --resource-group $AzResourceGroup --name $AzApp
az webapp deployment source sync --resource-group $AzResourceGroup --name $AzApp
```
