### ISSUE TITLE
AZ CLI Support for Virtual Routing APIs

### ISSUE THREAD

**Issue by dedhar** [Azure/azure-cli#12959]
**Resource Provider**
 
Microsoft.Network

**Description of Feature or Work Requested**

We are adding support for Virtual Routing APIs to Virtual Hub. Route Table (V3) is child resource of Virtual Hub. Routing Configuration would be a new property on all vWAN Connection resources such as ExpressRouteConnection, Vpn Connection, Hub Virtual Network Connection, P2S Connection Configuration.
https://microsoft.sharepoint.com/:w:/r/teams/WAG/AzureNetworking/_layouts/15/Doc.aspx?sourcedoc=%7B6968CBDD-48C8-4CA8-8D40-653E980AF04C%7D&file=VirtualWanRouting.docx&action=default&mobileredirect=true&cid=53650255-c0b6-4d3e-a189-7b9786ea0d12
Advertised Route Tables in above document is referred as Propagated Route Tables in final API.

**Minimum API Version Required**

**Swagger Link**
https://github.com/nagula-ritvika/azure-rest-api-specs/blob/a43c60d9e10c3178f12aa1997d9718d9c97e8d20/specification/network/resource-manager/Microsoft.Network/stable/2020-04-01/virtualWan.json
Postman : https://www.getpostman.com/collections/1dde71062ef8e7d9f1de

**Target Date**
RTv3 is part of vWAN GA. vWAN GA is on June 30.

**Comment by yonzhan** [comment]
add to S169

**Comment by dedhar** [comment]
There are 3 main changes :
1.	Add Create, Update, Delete, Get Cmdlets for new Route Table (V3) resource. Route Table V3 is child of Virtual Hub Resource. It supports PUT/DELETE by directly invoking operations on child resource (similar to vnet peering).
2.	Add support for Routing Configuration property on existing Express Route, Vpn, P2S Connection Configuration and Hub Virtual Network Connection resources.
3.	Add a new POST API Get Effective Routes which would take input parameter as Route Table or Connection (ER,S2S, P2S, Hub Virtual Network Connection) Resource ID.
 
Route Table Commands : 
az network vhub routetable create   
az network vhub routetable update
az network vhub routetable delete
az network vhub routetable show
az network vhub routetable get
az network vhub effective-routes get
 
Connection Commands : Customer can first create Routing Configuration object in memory and then pass it as parameter to the connection cmdlets.
ExpressRouteConnection : https://docs.microsoft.com/en-us/cli/azure/network/express-route/gateway/connection?view=azure-cli-latest
Vpn Connection : https://docs.microsoft.com/en-us/cli/azure/network/vpn-connection?view=azure-cli-latest
Hub Virtual Network Connection : https://docs.microsoft.com/en-us/cli/azure/ext/virtual-wan/network/vhub/connection?view=azure-cli-latest
P2S : I couldn’t find CLI commands for P2S GW. Will update back.
