### ISSUE TITLE
usage-threshold usage and example is unclear

### ISSUE THREAD

**Issue by omzevall** [Azure/azure-cli#12958]
The usage-threshold option says: Min 100 GiB, max 100TiB".

How are the units specified?

The example on this page says: --usage-threshold 100

Does this mean 100 GiB or 100 TiB?

Editorially, there is a space between "100" and "GiB" but no space in "100TiB". Additionally, there is an unnecessary quotation mark at the end of usage-threshold's description (i.e., 100TiB".  -- the quotation mark before the period).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 298ada99-369a-1c65-50ca-617931d26b7a
* Version Independent ID: 5fbd1cdf-e27f-8ffe-1c72-14f5d9e186f1
* Content: [az netappfiles volume](https://docs.microsoft.com/en-us/cli/azure/netappfiles/volume?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/netappfiles/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/netappfiles/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by omzevall** [comment]
Related: https://github.com/Azure/azure-cli-extensions/issues/1526

**Comment by yonzhan** [comment]
netappfiles
