### ISSUE TITLE
[Functions]Add support for Java 11  

### ISSUE THREAD

**Issue by kulkarnisonia16** [Azure/azure-cli#12963]
- Functions runtime V3
- OS (Linux and Windows) all hosting plans

Needs to support create app in Azure and deploy scenario for code and container scenarios
Code scenario:
--runtime java --runtime-version 11
(Needs to set javaVersion "11" and linuxFxVersion "java|11")

**Comment by yonzhan** [comment]
Functions

**Comment by RakeshMohanMSFT** [comment]
Its supported now
![image](https://user-images.githubusercontent.com/49954584/191175207-1937e314-c704-489b-8613-0d40160cc584.png)
https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-java?tabs=bash%2Cconsumption
