### ISSUE TITLE
Error while creating a service fabric cluster using bash

### ISSUE THREAD

**Issue by Tijinm** [Azure/azure-cli#12969]
## Describe the bug

**Command Name**
`az sf cluster create`

**Errors:**
```
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/command_modules/servicefabric/custom.py, ln 1158, in _create_certificate
    cmd, cli_ctx, vault_resource_group_name, vault_name, location, enabled_for_deployment=True).result()
cli/command_modules/servicefabric/custom.py, ln 1667, in _create_keyvault
    permissions = Permissions(keys=[KeyPermissions.get,
AttributeError: 'NoneType' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sf cluster create --resource-group {} --location {} --certificate-output-folder {} --certificate-password {} --certificate-subject-name {} --cluster-name {} --cluster-size {} --os {} --vault-name {} --vault-resource-group {} --vm-password {} --vm-user-name {}`

## Environment Summary
```
Linux-4.15.0-1075-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

```

**Comment by yonzhan** [comment]
sf

**Comment by Tijinm** [comment]
Hi ,
Didnt understand your comment?
First I stored the value in the variables and then i passed using the following commands
az group create --name $ResourceGroupName --location $Location 
az sf cluster create --resource-group $ResourceGroupName --location $Location --certificate-output-folder . --certificate-password $Password --certificate-subject-name $Subject  --cluster-name $ClusterName --cluster-size 3 --os UbuntuServer1604 --vault-name $VaultName  --vault-resource-group $ResourceGroupName --vm-password $VmPassword --vm-user-name $VmUserName

I am getting the error below 

'NoneType' object has no attribute 'get'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/command_modules/servicefabric/custom.py, ln 1158, in _create_certificate
    cmd, cli_ctx, vault_resource_group_name, vault_name, location, enabled_for_deployment=True).result()
cli/command_modules/servicefabric/custom.py, ln 1667, in _create_keyvault
    permissions = Permissions(keys=[KeyPermissions.get,
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by yonzhan** [comment]
Service Fabric service team should take a look at above.

**Comment by navba-MSFT** [comment]
@Tijinm Apologies for the late reply. Could you please use the most recent version of [Python libraries ](https://www.python.org/downloads/)and[ Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and test the behavior again ? Also this github thread has been inactive for quite sometime. Could you please let us know if you still need assistance on this? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Tijinm Please let us know if you are still facing this issue. If no further assistance is required on this, can we proceed with closure of this issue? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Tijinm We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
