### ISSUE TITLE
az login --principal with certificate not working

### ISSUE THREAD

**Issue by N7Overlord** [Azure/azure-cli#12962]
I have created pem file with rsa key

-----BEGIN RSA PRIVATE KEY-----
.....Key content
-----END RSA PRIVATE KEY-----

I have created a x509 certificate using previous key,  and uploaded certificate to my principal configuration using azure portal.

When executing az login command as follows:
 
az login --service-principal --username [application_id] -p azure.pem --tenant [tenanit_id]

I get this annoying error :

[('PEM routines', 'get_name', 'no start line')]

Please advice on what method I need use in order to create a valid key. 

**Command Name**
`az login`

**Errors:**
```
[('PEM routines', 'get_name', 'no start line')]
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 625, in execute
    raise ex
cli/core/commands/__init__.py, ln 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 682, in _run_job
    six.reraise(*sys.exc_info())
...
azure/cli/core/_profile.py, ln 1118, in __init__
    cert = load_certificate(FILETYPE_PEM, self.cert_file_string)
python3.8/site-packages/OpenSSL/crypto.py, ln 1794, in load_certificate
    _raise_current_error()
python3.8/site-packages/OpenSSL/_util.py, ln 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('PEM routines', 'get_name', 'no start line')]
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal --username {} -p {} --tenant {}`

## Environment Summary
```
macOS-10.15.3-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.3.1

```

**Comment by yonzhan** [comment]
add to S169

**Comment by jiasli** [comment]
Duplicate of #9970. Please see the comments at https://github.com/Azure/azure-cli/issues/9970#issuecomment-513478952.

We have updated the document https://github.com/MicrosoftDocs/azure-docs-cli/pull/1889 and will make it live in the next release.

Meanwhile, I will think about how we can polish the error.

**Comment by N7Overlord** [comment]
Resolved, thanks.

Create key and self-signed certificate

% openssl req -x509 -nodes -newkey rsa:2048 -keyout rsa_private.pem \
    -out rsa_cert.pem -subj "/CN=deployment"

Append certificate to key file

% cat rsa_cert.pem >> rsa_private.pem

Upload rsa_cert.pem to Azure Active Directory/App Registrations/[Select registration]/Certificates & Secrets/Certificates

% az login --service-principal --username [applicationId] -p rsa_private.pem --tenant [tenantId]


Result.

[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "[home-tenant-id]",
    "id": "[session-d]",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Subscription Name",
    "state": "Enabled",
    "tenantId": "[tenant-id]",
    "user": {
      "name": "[application-id]",
      "type": "servicePrincipal"
    }
  }
]


Note: In the most updated documentation https://github.com/MicrosoftDocs/azure-docs-cli/pull/1889.  "az login" accepts new arguments --name [ap-registration-name] and --cert [path-to-cert] instead
of --username and -p for authentication with certificates which will apply to future releases.
