### ISSUE TITLE
resource: support tenant bound resources 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#1296]
The work is to let generic resource commands handle such RPs including `intune` and `powerapps`
So far in cli, only graph commands work at tenant level, all others assume at subscriptions level. 

Discussed in PR #1280. Not urgent, but we will need it
```
xplat doesn't, but the generic resource cmdlets in powershell do (New-Resource, Get-Resource, Set-Resource, Remove-Resource). For example, to get a tenant level powerapps resource:

Get-AzureRmResource -ResourceId providers/Microsoft.PowerApps/apps/69fb28f7-9bb3-2766-2b0e-b9449f10fa3c -ApiVersion 2015-02-01-preview
```

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
