### ISSUE TITLE
"az network application-gateway frontend-ip create" command can't accept more than 4 args

### ISSUE THREAD

**Issue by nakamacchi** [Azure/azure-cli#12965]
**Describe the bug**
"az network application-gateway frontend-ip create" command can't accept more than 4 args

**To Reproduce**
nobuyuki@Azure:\~$ az network application-gateway frontend-ip create --gateway-name $AKS_IWF_NAME --resource-group $RG_AKS --name $AKS_IWF_PRIVATE_FRONTEND_IP_NAME
Cannot parse the request.

nobuyuki@Azure:\~$ az network application-gateway frontend-ip create --gateway-name $AKS_IWF_NAME --resource-group $RG_AKS --name MyFrontendIp
Cannot parse the request.

nobuyuki@Azure:\~$ az network application-gateway frontend-ip create --gateway-name $AKS_IWF_NAME --resource-group $RG_AKS
az network application-gateway frontend-ip create: error: the following arguments are required: --name/-n
... (omitted)

nobuyuki@Azure:\~$ az network application-gateway frontend-ip create --name $AKS_IWF_PRIVATE_FRONTEND_IP_NAME
az network application-gateway frontend-ip create: error: the following arguments are required: --resource-group/-g, --gateway-name
... (omitted)

**Additional context**
CLI version 2.2.0, 2.3.1

**Comment by yonzhan** [comment]
add to S169

**Comment by MyronFanQiu** [comment]
@nakamacchi Can you run the first command with --debug? Is the error message `Cannot parse the request.`?

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
@nakamacchi any update for this issue?

**Comment by MyronFanQiu** [comment]
@nakamacchi Hi. Did you still meet this issue?

**Comment by MyronFanQiu** [comment]
close this issue since cannot reproduce.
