### ISSUE TITLE
A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.

### ISSUE THREAD

**Issue by suganthe** [Azure/azure-cli#12966]
A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.

**Comment by yonzhan** [comment]
It is issue related to Azure CLI, could you please input more detailed info for us to triage?

**Comment by myjuda** [comment]
A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration. help me please....

**Comment by yonzhan** [comment]
Still not clear whether it is related to Azure CLI.

**Comment by suganthe** [comment]
Thank you. Now the tagged issue is rectified.

With regards,
Dr.R.C.Suganthe
Professor/CSE
Kongu Engineering College,
Perundurai - 638 052,
Erode District, Tamilnadu, India.
Email:suganthe_rc@kongu.ac.in
Mobile:98423 50051.
________________________________

**Comment by jiasli** [comment]
The error is from [Jupyter Notebook](https://github.com/jupyter/notebook) instead of Azure CLI. Please refer to https://github.com/jupyter/notebook/issues/4630.

**Comment by suganthe** [comment]
thank you. The issue is solved, now  azure notebook is working.

With regards,
Dr.R.C.Suganthe
Professor/CSE
Kongu Engineering College,
Perundurai - 638 052,
Erode District, Tamilnadu, India.
Email:suganthe_rc@kongu.ac.in
Mobile:98423 50051.
________________________________
