### ISSUE TITLE
support uri scheme for parameter files by creating a new parameter --parameter-file

### ISSUE THREAD

**Issue by vairakkumar-vairaperumal** [Azure/azure-cli#12970]
**Is your feature request related to a problem? Please describe.**

Unable to use @ for parameter file reference in Powershell 7. It requires to create scripts for windows batch and linux separate than Powershell 7. Also, Powershell has more features in command line than windows command terminal.

**Describe the solution you'd like**

Instead of modifying the parameters argument to support URI format to reference parameters file, create a new argument to support URI convention to support local files.

**Describe alternatives you've considered**

Update parameters to support URI convention for parameters to refer local files.
like --parameters ./parameters.json that will work in all environments

**Additional context**

**Comment by yonzhan** [comment]
add to S170

**Comment by jiasli** [comment]
The reason why we don't design separate parameters for files is that we don't know which parameter should be read from the file. In other words, users can use a file as input for any parameter. 

`@` is a more general approach which supports all parameters. In PowerShell terminal, `@` is reserved for [splatting](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7). To use it in `az` as a file name indicator, you only need to escape it:

```pwsh
# Escape with backtick
az `@body.json

# Surround with single quotes
az '@body.json'

# Surround with double quotes
az "@body.json"
```

For more info about PowerShell usage, please see [About Quoting Rules](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7) and [About Special Characters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_special_characters?view=powershell-7). 

For Azure CLI usage, please see [Tips for using Azure CLI effectively](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md).
