### ISSUE TITLE
Image builder create doesn't support identity configuration

### ISSUE THREAD

**Issue by feiyushi** [Azure/azure-cli#12976]
The section of "identity" in the image template is ignored. 
Wonder is this a bug or will be supported later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e24b37-83e6-abcb-65f3-8e10aca64fa5
* Version Independent ID: 803fa652-41f2-dcdd-ed5b-2e60b11186af
* Content: [az image builder](https://docs.microsoft.com/en-us/cli/azure/image/builder?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/image/builder.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/image/builder.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by qianwens** [comment]
@qwordy please help take a look.

**Comment by qwordy** [comment]
It is not supported in CLI yet. I am working on it.
One question, is the value of dictionary always "{}"?
```
"identity": {
        "type": "UserAssigned",
        "userAssignedIdentities": {
          "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/rg1/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity_1": {}
        }
      },
```

**Comment by feiyushi** [comment]
When configuring user assigned identity, the value of the key-value pair is empty. Only the key is filled with identity resource id. But when service returns the provisioned resource, the value should not be empty (readonly).
