### ISSUE TITLE
Following Windows install instructions does not allow az to be called from Powershell.

### ISSUE THREAD

**Issue by TheCodeFiend** [Azure/azure-cli#12979]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I am trying to install Azure CLI on Windows 10 1909.  I follow the instructions by using an admin Powershell session, and copying and pasting the command from the documentation. 
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest
When it completes, I re-launch an admin Powershell as stated, and az is not recognized as a program.

**To Reproduce**
Follow the instructions by using an admin Powershell session, and copying and pasting the command from the documentation. 
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest
When it completes, re-launch an admin Powershell as stated, and type az.  It is not recognized as a program.

**Expected behavior**
I should be able to use az at the command line.

**Environment summary**
Windows 10 1909 x64, Chrome v80.

**Additional context**

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
@TheCodeFiend did you see the following message in a popup when Powershell starts to download the package? BTW, when you relaunch Powershell, you don't need to run as administrator, but this should not affect running az.
![image](https://user-images.githubusercontent.com/55177366/79635349-f0a12880-81a2-11ea-8038-9447c2b1705e.png)

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Feel free to reopen this issue if the latest Azure CLI still does not work for you.
