### ISSUE TITLE
Update repository information on https://hub.docker.com/r/azuresdk/azure-cli-python/

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1297]
1. The format is off;
2. Installation instruction of cli 2.0 are out-of-date; (for example, sudo is still promoted.)

**Comment by derekbekoe** [comment]
The information on https://hub.docker.com/r/azuresdk/azure-cli-python/ was taken from our main README automatically.

I've updated the description on Docker Hub to fix the formatting and make it specific to Docker.
