### ISSUE TITLE
Error updating api-server-authorized-ip-ranges for AKS

### ISSUE THREAD

**Issue by cmp66** [Azure/azure-cli#12989]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.3.1

**Describe the bug**
When attempting to update the allowed IP ranges for the AKS api server, I received the following error:
Operation failed with status: 'Bad Request'. Details: UnmarshalEntity encountered error: json: cannot unmarshal bool into Go struct field Properties.properties.autoScalerProfile of type string

**To Reproduce**
AKS is deployed using Terraform with version 2.5 of the Azure Terraform Provider.  The AKS cluster version is 1.16.7

The az aks command used is:
az aks update --name "name" --resource-group "rg" --api-server-authorized-ip-ranges "cidr block list"

**Expected behavior**
The AKS cluster would be updated to have the new IP authorized list.

**Environment summary**
cli versions 2.3.0 and 2.3.1
Azure AKS version 1.16.7
AKS deployed using terraform 0.12.23 with version 2.5 of the azure provider

**Additional context**

**Comment by yonzhan** [comment]
aks

**Comment by marwanad** [comment]
That's a known issue with AZ CLI 2.3.1. 

For now, the fix is to use CLI extensions

az extension add --name aks-preview

The next CLI release on 04/21/2020 will address this issue.

**Comment by jluk** [comment]
Please upgrade to CLI 2.4.0, this should be fixed as a known issue. I will close this as a result, but if you continue to hit this error on the latest version comment and we will revisit.

Thanks for the feedback!
