### ISSUE TITLE
HTTPS Settings?

### ISSUE THREAD

**Issue by nezoic** [Azure/azure-cli#12988]
How do you specify HTTPS? I created a Front End port on 443. I specified a cert that I've already uploaded here. When I create the resources it is successful but stuck on HTTP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dce00db-c8d7-9b93-7ac8-114a500a6a34
* Version Independent ID: 14a03192-a30b-d273-fa11-32413868a5fa
* Content: [az network application-gateway http-listener](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/http-listener?view=azure-cli-latest#az-network-application-gateway-http-listener-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S169

**Comment by MyronFanQiu** [comment]
@nezoic If you provide `--ssl-cert` in `az network application-gateway http-listener create` command, the protocol would be set to `https` accordingly.
