### ISSUE TITLE
The example update command does not work

### ISSUE THREAD

**Issue by jose-lima2011** [Azure/azure-cli#12995]
Hello guys, another thread for you, I tried to follow the example of this document with the error below: 

az monitor log-profiles update --name default --set retentionPolicy.days=365 retentionPolicy.enabled=true
validation error: Parameter 'LogProfileResource.location' can not be None.

According to the example
of the document should be simple:

az monitor log-profiles update --name MyLogProfile --set retentionPolicy.days = 365

What is missing ? Thank you for now

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58a5a5bd-c481-72b8-0cec-05c8795b4469
* Version Independent ID: dba52140-3799-cbc3-4628-c2e77d246eb1
* Content: [az monitor log-profiles](https://docs.microsoft.com/en-us/cli/azure/monitor/log-profiles?view=azure-cli-latest#az-monitor-log-profiles-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @MyronFanQiu could you have a look? thanks

**Comment by MyronFanQiu** [comment]
@jose-lima2011 Hi. I'm sorry for this command. The example is wrong and looks like this command has not been changed for two years. The functionality of this command is not sufficient. To unblock you quickly, please try `az monitor log-profiles update --name default --set retentionPolicy.days=365 retentionPolicy.enabled=true location=westus`. We will fix example and this command later.

**Comment by yonzhan** [comment]
add to S168

**Comment by jose-lima2011** [comment]
> @jose-lima2011 Hi. I'm sorry for this command. The example is wrong and looks like this command has not been changed for two years. The functionality of this command is not sufficient. To unblock you quickly, please try `az monitor log-profiles update --name default --set retentionPolicy.days=365 retentionPolicy.enabled=true location=westus`. We will fix example and this command later.

Ok, but if I need to add all regions including the global one, what would the syntax look like?

**Comment by MyronFanQiu** [comment]
> > @jose-lima2011 Hi. I'm sorry for this command. The example is wrong and looks like this command has not been changed for two years. The functionality of this command is not sufficient. To unblock you quickly, please try `az monitor log-profiles update --name default --set retentionPolicy.days=365 retentionPolicy.enabled=true location=westus`. We will fix example and this command later.
> 
> Ok, but if I need to add all regions including the global one, what would the syntax look like?

Each command can only manipulate one log profile in one region. You may need to write a script to run several commands.

**Comment by jose-lima2011** [comment]
Hi Myron, I understand thanks for your time.
