### ISSUE TITLE
az deployment {sub} create --template-uri... templateLink no longer available. 

### ISSUE THREAD

**Issue by Svessir** [Azure/azure-cli#12990]
## Describe the bug

**Command Name**
`az deployment create`

**Errors:**
```
Deployment failed. Correlation ID: 21bcc642-ce46-4888-848b-300b1ee9634b. {
  "error": {
    "code": "InvalidTemplate",
    "message": "Unable to process template language expressions for resource '/subscriptions/c88c80a7-d849-4bce-8907-ac15d5ca178b/providers/Microsoft.Resources/deployments/innResourceGroup' at line '61' and column '5'. 'The language expression property 'templateLink' doesn't exist, available properties are 'template, templateHash, parameters, mode, provisioningState'.'",
    "additionalInfo": [
      {
        "type": "TemplateViolation",
        "info": {
          "lineNumber": 61,
          "linePosition": 5,
          "path": ""
        }
      }
    ]
  }
}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az deployment create --name {} --location {} --template-uri {} --parameters {} --parameters {} --verbose`

## Expected Behavior
I used the --template-uri to supply the template so I expect deployment().properties.templateLink
to be available to use in the template like in earlier versions of az cli. I'm guessing the az cli is now downloading the template from the source and running it similar to a local template? az deployment sub create has the same behavior. I ran the templates with an earlier version of az cli successfully (version 2.0.69).

## Environment Summary
```
Linux-5.3.0-46-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.3.1

```

**Comment by yonzhan** [comment]
add to S169

**Comment by ckittel** [comment]
I can confirm this is happening as well, it looks like the template is downloaded and then provided to `/validate` as if it was a local file.

**Comment by yonzhan** [comment]
add to S171

**Comment by zhoxing-ms** [comment]
Hi @Svessir, this is the same problem as #13317, and I have submitted a PR #13344 to fix it~ You can track the progress of the problem through this PR.
