### ISSUE TITLE
help text for missing subcommands is not helpful

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#130]
`az vm usage
usage: az vm usage [-h] {list} ...
az vm usage: error: the following arguments are required: subcommand`

This error message is hard to grock: we tell users that they are missing the "subcommand" argument but there is no argument called subcommand, of course.  We should just tell them what subcommands *are available*.  I get that if you know a lot about the CLI you can discern that '{list}' is the subcommand, but there's no real way to figure that out based on the text

**Comment by JasonRShaver** [comment]
dup
