### ISSUE TITLE
HPC Cache - Update command

### ISSUE THREAD

**Issue by rebecca-makar** [Azure/azure-cli#13003]
az hpc-cache update--resource-group "remakar" --name "climakar" --location "eastus"  --cache-size-gb "3072" --subnet "/subscriptions/<SUB_ID>/resourceGroups/remakar/providers/Microsoft.Network/virtualNetworks/vnet_remakar/subnets/default" --sku-name "Standard_2G"

As discussed in meeting, az hpc-cache update only needs to update tags. Params needed would be rg name, cache name, and tags. Do a get before update to make sure cache exists so it does not create a new cache.

**Comment by yonzhan** [comment]
add to S169

**Comment by zhoxing-ms** [comment]
@rebecca-makar In fact, the REST API we used is `PATCH` requests, If the cache to be updated does not exist, an error will be reported:
```pwsh
{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.StorageCache/caches/zhoxing-test' under resource group 'zhoxing-test' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
```
As for the updated parameters, I'll change to support only modified tags

**Comment by rebecca-makar** [comment]
@zhoxing-ms sounds good! thank you
