### ISSUE TITLE
Unable to login using az login --identity

### ISSUE THREAD

**Issue by mrcoder54** [Azure/azure-cli#13008]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05BFC430>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
Traceback (most recent call last):
pip-install-anx9qzc7\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1

```

**Comment by yonzhan** [comment]
add to S169

**Comment by jiasli** [comment]
`az login --identity` is used for managed identity. The command needs to be run in an Azure VM with managed identity configured. Please check [Sign in with a managed identity](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest#sign-in-with-a-managed-identity) for details.

**Comment by seligj95** [comment]
> [!NOTE]
> **[AI-Assisted Triage]** This comment was generated with AI assistance as part of an App Service CLI issue review. Reply to this comment and tag @seligj95 to follow up.

**Summary**: Missing --instance parameter for SSH command
**Status**: Confirmed-bug
**Priority**: P3
**Next Steps**: Fix planned to add missing parameter support
