### ISSUE TITLE
Getting list of Service Fabric applications 

### ISSUE THREAD

**Issue by jajaislanina** [Azure/azure-cli#13007]
## Describe the bug
Trying to fetch list of deployed applications in SFC always returns empty result even though there are applications deployed to a cluster

**Command Name**
`az sf application list --resource-group MyTestRG01 --cluster-name testsfcclust01`

**Errors:**
N/A

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
- Create new SFC (from portal or using CLI)
- Deploy sample voting app (https://github.com/Azure-Samples/service-fabric-dotnet-quickstart)
- `az sf application list --resource-group {} --cluster-name {}`

## Expected Behavior
- Return the list of applications deployed on SF cluster

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1

```

**Comment by yonzhan** [comment]
Service Fabric

**Comment by ColinM9991** [comment]
Any update on this?

**Comment by sicklittlemonkey** [comment]
My suspicion is that you have the same problem as me. In the [docs for az sf application](https://docs.microsoft.com/en-us/cli/azure/sf/application?view=azure-cli-latest) it has an important and tragic note: "**Only support ARM deployed applications.**"

How sad is that!? Azure CLI is Microsoft's "next generation multi-platform command line experience for Azure", but I can't manage SF apps deployed from a DevOps Release Pipeline, and I'm guessing the above limitation is the reason. A possible workaround is to use the (painful) PowerShell [SF command module](https://docs.microsoft.com/en-us/powershell/module/servicefabric/connect-servicefabriccluster?view=azureservicefabricps).

Can anyone confirm the above? I will probably log a new issue anyway.

**Comment by navba-MSFT** [comment]
@jajaislanina Apologies for the late reply. AFAIK there is no indication in SFX for apps that are created via ARM or management endpoint, and indeed you would not see the non ARM application types with ARM get operation. So the CLI commands will show only ARM based applications. see [here](https://docs.microsoft.com/en-us/cli/azure/sf/application?view=azure-cli-latest). 
The PS command[ Get-AzResource](https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azresource?view=azps-7.1.0) will also return applications that are managed as ARM resources. 
Also this github thread has been open for quite sometime now. Please let us know if you need any further assistance on this before we proceed with closure on this thread.

**Comment by navba-MSFT** [comment]
@jajaislanina Please let us know if you had a chance to look at my above comment. Do let us know if you need any further help on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@jajaislanina We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
