### ISSUE TITLE
Keyvault creation without purge protection fails

### ISSUE THREAD

**Issue by mohoff** [Azure/azure-cli#13006]
## Describe the bug

I'm trying to create a keyvault with `az keyvault create ...` that has the purge protection and soft delete disabled. However, the command fails with the error shown below.

The keyvault with the specified name has not been created before.

The command works without the `--enable-purge-protection` being set.

The `--help` of this command states that `false` is an allowed value:

```
--enable-purge-protection: Prevents manual purging of deleted vault, and all contained
                                        entities.  Allowed values: false, true.
```

Furthermore, the help for `--enable-purge-protection` is lacking information about the default value (`--enable-soft-delete` help contains this detail).

**Command Name**
`az keyvault create`

**Errors:**
```
The property "enablePurgeProtection" cannot be set to false. Enabling the purge protection for a vault is an irreversible action.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault create --resource-group {} --name {} --location {} --enable-purge-protection false --enable-soft-delete false`

## Expected Behavior

Create the keyvault with both protection mechanisms disabled

## Environment Summary
```
macOS-10.15.3-x86_64-i386-64bit
Python 3.8.2

azure-cli 2.2.0 *

```

**Comment by yonzhan** [comment]
@bim-msft  please take a look.

**Comment by bim-msft** [comment]
Looking into it, seems to be a service side bug.

**Comment by cdelacruzpinto** [comment]
With the golang api I get the same error, so yes...aparently is not possible to create vaults at all without that protection.

**Comment by jlichwa** [comment]
> With the golang api I get the same error, so yes...aparently is not possible to create vaults at all without that protection.

It is not expected behavior. It is a bug and change is on the way. It will be available in few days.

**Comment by sebansal** [comment]
Is this deployed? @jlichwa

**Comment by jlichwa** [comment]
Yes it is. #please-close

**Comment by jlichwa** [comment]
#please-close @bim-msft

**Comment by jackphillipsjmu** [comment]
This is still an issue in 2025...
