### ISSUE TITLE
Does KeyVault require a callback to clear out the global cache?

### ISSUE THREAD

**Issue by haroldrandom** [Azure/azure-cli#13000]
**Is your feature request related to a problem? Please describe.**
While I am migrating test framework from nose to pytest, I found those 2 tests runing serially would fail.

KeyVault SDK has [a gloal and  process-level variable](https://github.com/Azure/azure-sdk-for-python/blob/94118e48f58563fd22c18f60c1c3c6b885a6a8f3/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/http_challenge_cache.py#L23) `_cache`, whis is a Python dict.

The key of this dict is vault name

Which will cause some problems when running tests tests serially, like [this PR](https://github.com/Azure/azure-cli/pull/13002) mentioned.
1. the first test `test_vm_create_linux_secrets` run and invoke keyvault command, which will write to that cache since it cannot get credential from cache in order to reduce some extral cost, that means it needs to make a series of HTTP requests to KeyVault service, and that order of HTTP requests are recorded in yaml files. And the key for this credential is **vmlinuxkv000002**.
2. the second test `test_vmss_create_linux_secrets` then will find there is already a cache inside that global variable because it use the same key **vmlinuxkv000002**. Consequently, it won't make HTTP requests to query from KeyVault service.

**The problem is every tests during our tests are recorded indenpently, which means, when `test_vmss_create_linux_secrets` is recored, it won't see the `_cache` that is modified by `test_vm_create_linux_secrets`, it's totally clean**. 
So when playback tests, the second test will generate a different sequence of HTTP requests that doesn't like the recording files. So, run those two tests, will fail.

**Describe the solution you'd like**
Currently, I just rename the vault name that the different test used to avoid name conflict in the global variable `_cache`.

But I suggest, we implement a hook/callback to clean out the cache every time a test ends.
Like `doCleanups` or `tearDown` of unittest, and make those tests who are using keyvault command inherits from a Parent class the implements the callback.

Or we could leverage some functionalitu from pytest framework instead.

**Describe alternatives you've considered**
We implement this clean out logic in keyvault comamnds, let keyvault clean it out whenever it needs to. Which requires us to sort out the all the scenario that it should clear.

**Additional context**

**Comment by yonzhan** [comment]
add to S168

**Comment by haroldrandom** [comment]
Another option, implement the cleanup logic in KeyVaultPrepare

**Comment by haroldrandom** [comment]
Added `won't fix` lable sicne it's low priority.
