### ISSUE TITLE
Unable to select a pre-existing app service plan while creating a new web app bot.

### ISSUE THREAD

**Issue by saisharank** [Azure/azure-cli#13016]
**Resource Provider**

azure cli
**Description of Feature or Work Requested**

az bot create --appid "xxxxxxxxxxxxxxxxxxx" --password "xxxxxxxxxxxxxx" --resource-group "test_rg" --name "test-bot-dev" --kind "webapp" --description "bot for testing" --lang javascript --sku S1  **--plan "existing-plan"**

**Minimum API Version Required**

**Swagger Link**

**Target Date**

**Comment by yonzhan** [comment]
web app bot

**Comment by navba-MSFT** [comment]
@saisharank Apologies for the late reply. Could you please let me know if you are still facing this issue ? Awaiting your reply.

Similar issue #11433
