### ISSUE TITLE
Add links

### ISSUE THREAD

**Issue by nrgifford** [Azure/azure-cli#13013]
Make links of 'JsonWebKeyCurveName' and 'JsonWebKeyType'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0f363b-7f21-0ea9-3e27-da7866c94102
* Version Independent ID: 6cc413e4-4f7d-9baa-a365-c9275fc6a7ad
* Content: [az keyvault key](https://docs.microsoft.com/en-us/cli/azure/keyvault/key?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@bim-msft please take a look
