### ISSUE TITLE
"az sf cluster durability update" command fails with error message "'NoneType' object has no attribute 'lower'"no 

### ISSUE THREAD

**Issue by ptsapralis** [Azure/azure-cli#13010]
## Describe the bug

**Command Name**
`az sf cluster durability update`

**Errors:**
```
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 625, in execute
    raise ex
cli/core/commands/__init__.py, ln 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/command_modules/servicefabric/custom.py, ln 582, in <listcomp>
    if ext.type.lower() == SERVICE_FABRIC_WINDOWS_NODE_EXT_NAME or ext.type.lower() == SERVICE_FABRIC_LINUX_NODE_EXT_NAME]
AttributeError: 'NoneType' object has no attribute 'lower'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sf cluster durability update -c {} -g {} --node-type {} --durability-level {} --verbose --subscription {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.3.1

Extensions:
application-insights 0.1.6

```

**Comment by yonzhan** [comment]
Service Fabric

**Comment by navba-MSFT** [comment]
@ptsapralis Apologies for the late reply. Could you please use the most recent version of [Python libraries ](https://www.python.org/downloads/)and[ Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and test the behavior again? Also this github thread has been in active for quite sometime. Could you please let us know if you still need assistance on this? Awaiting your reply.

**Comment by ptsapralis** [comment]
Hello. Thank you for getting back to me on this. You may now close this thread as I have resolved the problem on all my systems since some time ago by updating all components to their latest versions.

Thanks again & Regards,
--
Panos Tsapralis
Head of Networks
(M) 07507477883
(direct) 442082755505
4 Imperial Place, Maxwell Road, Borehamwood, Hertfordshire, WD6 1JN
***@***.******@***.***>

***@***.***   ***@***.*** ***@***.***

From: navba-MSFT ***@***.***>
Date: Thursday, 3 February 2022 at 07:35
To: Azure/azure-cli ***@***.***>
Cc: Panos Tsapralis ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/azure-cli] "az sf cluster durability update" command fails with error message "'NoneType' object has no attribute 'lower'"no (#13010)

CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@ptsapralis<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fptsapralis&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7Cc2fe626f2c2d41854f0408d9e6e7b2f6%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637794705082095419%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qAnl4hmdWGuQa%2Fo9gG1%2Be00LUPCnK23%2F%2FY63ZzUGQnY%3D&reserved=0> Apologies for the late reply. Could you please use the most recent version of Python libraries <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.python.org%2Fdownloads%2F&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7Cc2fe626f2c2d41854f0408d9e6e7b2f6%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637794705082095419%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VOQzDyMeTYt0G8Xp9mqyZvBdgklmHBYCTxyJGkH5u2Y%3D&reserved=0> and Azure CLI<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fcli%2Fazure%2Finstall-azure-cli&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7Cc2fe626f2c2d41854f0408d9e6e7b2f6%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637794705082095419%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cdRjaudmRF5aewB2IQ2FtKWlgb5O9qUyTlxbNOAAeoQ%3D&reserved=0> and test the behavior again? Also this github thread has been in active for quite sometime. Could you please let us know if you still need assistance on this? Awaiting your reply.

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fissues%2F13010%23issuecomment-1028684560&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7Cc2fe626f2c2d41854f0408d9e6e7b2f6%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637794705082095419%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eNK8kuwkDoi0FdW06X2Zk3Rdannj858KTzNud%2Bc%2BdjY%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADLRXZKMYCTYE7SATMQD2JTUZIV2TANCNFSM4MH6X5IA&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7Cc2fe626f2c2d41854f0408d9e6e7b2f6%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637794705082095419%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AKrHmEF3t7SlPShv8LwE2eMlmVAC6%2BRVLDYjXnWsKuE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7Cc2fe626f2c2d41854f0408d9e6e7b2f6%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637794705082095419%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kZ5zMMw%2FzxbuXqJqhKgeX8VLxpX6Oc72md5VJ90ecCI%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpanos.tsapralis%40buyagift.com%7Cc2fe626f2c2d41854f0408d9e6e7b2f6%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637794705082095419%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xRUVhhacL0xbmoOkL352O2D8Vg5iGdFmJdudrQK1QXg%3D&reserved=0>.

**Comment by navba-MSFT** [comment]
Thanks @ptsapralis. Please feel free to get back to us if you need any further assistance in future. We would be happy to help.
