### ISSUE TITLE
Default values should be given

### ISSUE THREAD

**Issue by nrgifford** [Azure/azure-cli#13014]
For optional parameters, the default value should be documented.
Specifically: "Elliptic curve name", "Type of key", "Key size", etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0f363b-7f21-0ea9-3e27-da7866c94102
* Version Independent ID: 6cc413e4-4f7d-9baa-a365-c9275fc6a7ad
* Content: [az keyvault key](https://docs.microsoft.com/en-us/cli/azure/keyvault/key?view=azure-cli-latest#az-keyvault-key-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@bim-msft  please take a look

**Comment by RakeshMohanMSFT** [comment]
@nrgifford for key type the default value is updated for other parameters its actually None by default
--kty
The type of key to import (only for BYOK).

accepted values: EC, RSA, oct
default value: RSA

https://docs.microsoft.com/en-us/cli/azure/keyvault/key?view=azure-cli-latest#az-keyvault-key-import
