### ISSUE TITLE
ModuleNotFoundError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by considerable** [Azure/azure-cli#13017]
## Describe the bug

**Command Name**
`az keyvault secret show`

**Errors:**
```
No module named '_cffi_backend'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 546, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 330, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
site-packages/azure/keyvault/_internal.py, ln 16, in <module>
    from cryptography.hazmat.primitives import hashes, constant_time, padding, hmac
cryptography/hazmat/primitives/constant_time.py, ln 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault secret show --vault-name {} --query {} --name {}`

## Environment Summary
```
Linux-5.5.15-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
Python 3.7.6
Installer: RPM

azure-cli 2.3.1

```

**Comment by yungezz** [comment]
hi @bim-msft could you pls have a look? thanks

**Comment by bim-msft** [comment]
Hi @considerable what is the version of your `cryptography` library? You may use `2.8` to have a try. If anything still blocks you, feel free to let me know, thanks!

**Comment by bim-msft** [comment]
Closing it due to longtime inactivity, feel free to reopen it anytime if you need additional help.
