### ISSUE TITLE
az storage blob delete-batch not running

### ISSUE THREAD

**Issue by andres-ab** [Azure/azure-cli#13029]
## Describe the bug
I tried to "clean" a directory in my blob storage and the command does not finish so I stop it. There are 2 CSV files of around 1 GB, so I would expect a fast response. Previously I list those items and they are shown properly.

I tried different parameters including timeout and debug and nothing changed.

**Command Name**
`az storage blob delete-batch`

**Errors:**
Did not finish.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._

- `az storage blob delete-batch --account-name {} --account-key {} --auth-mode {} --source {} --pattern {} --verbose --dryrun --timeout {} --debug`

## Expected Behavior
Delete blobs in that directory.

## Environment Summary
```
Linux-5.3.0-45-generic-x86_64-with-debian-buster-sid
Python 3.6.5

azure-cli 2.2.0 *

Extensions:
interactive 0.4.3

```

**Comment by yungezz** [comment]
hi @Juliehzl could you pls have a look?

**Comment by yonzhan** [comment]
add to S169

**Comment by andres-ab** [comment]
I tried the command again in dryrun, and it finished in 2180 sec (a lot of time !)

az storage blob delete-batch \
>     --account-name $AZURE_STORAGE_ACCOUNT \
>     --account-key $AZURE_STORAGE_ACCESS_KEY \
>     --auth-mode key \
>     --source $container_name \
>     --pattern "$nuevo_trx*" \
>     --verbose \
>     --dryrun \
>     --timeout 30 \
>     --debug

Thank you.

**Comment by yonzhan** [comment]
@andres-ab Thanks. Was your issue resolved?

**Comment by yonzhan** [comment]
add to S171
