### ISSUE TITLE
CLI for Virtual WAN Point to site feature.

### ISSUE THREAD

**Issue by Nilambari** [Azure/azure-cli#13020]
**Is your feature request related to a problem? Please describe.**
Virtual WAN Point to site feature is already GA but we missed to add the CLI support for the same, and hence the CLI need.
Swagger (Developer to contact is Nilambari Deshpande)
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2020-03-01/virtualWan.json
Swagger PRs:-
1. https://github.com/Azure/azure-rest-api-specs/pull/7238
2. https://github.com/Azure/azure-rest-api-specs/pull/7498
3. https://github.com/Azure/azure-rest-api-specs/pull/7529

**Describe the solution you'd like**
Brief about Virtual WAN : Azure Virtual WAN is a networking service providing optimized and automated branch to branch connectivity through Azure. A point-to-site (P2S) VPN lets you create a secure connection to your virtual WAN from an individual client computer. A P2S connection is established by starting it from the client computer.

**Describe alternatives you've considered**
LI is needed as feature is already GA and we missed to add CLI support.

**Additional context**
Please contact me nilamd@microsoft.com if any questions on Virtual WAN Point to site feature CLI request.

**Comment by qianwens** [comment]
@MyronFanQiu to help take a look.

**Comment by yonzhan** [comment]
add to S169

**Comment by MyronFanQiu** [comment]
@Nilambari Hi. Could you give me the mock commands or the set of Powershell commands?

**Comment by Nilambari** [comment]
Virtual Wan Point to Site feature total 11 command lets:-

Resource: VppnServerConfiguration 4 commands:- 
PS commadlets @https://github.com/Azure/azure-powershell/tree/master/src/Network/Network/Cortex/VpnServerConfiguration
New-AzVpnServerConfiguration
Update-AzVpnServerConfiguration
Get-AzVpnServerConfiguration
Remove-AzVpnServerConfiguration

Resource: P2SVpnGateway 7 commands:- 
PS commadlets @https://github.com/Azure/azure-powershell/tree/master/src/Network/Network/Cortex/P2SVpnGateway
New-AzP2sVpnGateway
Update-AzP2sVpnGateway
Get-AzP2sVpnGateway
Remove-AzP2sVpnGateway
Get-AzP2sVpnGatewayConnectionHealth
Get-AzP2sVpnGatewayDetailedConnectionHealth
Disconnect-AzP2SVpnGatewayVpnConnection

Sample PS command lets test @https://raw.githubusercontent.com/Azure/azure-powershell/master/src/Network/Network.Test/ScenarioTests/CortexTests.ps1
Test-P2SCortexCRUD

Let me know if you have more queries. Thanks!
