### ISSUE TITLE
Question: `az postgres db -g` option

### ISSUE THREAD

**Issue by danielbecroft** [Azure/azure-cli#13034]
The documentation for `az postgres db` indicate that the `--resource-group` is a required parameter to all commands (`create`, `list`, `delete`).

Does this mean that it is expected that a database could be created for a server, but in a different resource group? For example:

```
az postgres server create -g <server-group> -n <server-name>
az postgres db create -g <db-group> -s <server-name> -n <db-name>
```

I've tried this, and it doesn't work. The `az postgres db create` commands fail with the following error:

```
The Resource 'Microsoft.DBforPostgreSQL/servers/<server-name>' under resource group '<db-group>' was not found.
```

If this isn't expected, it's unclear then what the purpose of the `--resource-group` parameter is. The `--server-name` value identifies the server where the database is being created, and if the `--resource-group` parameter needs to match the group the server resides in, that's double entry. (This probably applies to multiple commands on the CLI, I guess).

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by rachel-msft** [comment]
Entering the resource group is a general Azure CLI pattern required to route the command to the correct resource. A resource id is built off of the subscription (using which sub you're logged in to), resource group, and resource name. 

An example of a resource id:
/resource/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myrg/providers/Microsoft.DBforPostgreSQL/servers/myserver

**Comment by danielbecroft** [comment]
Thanks @rachel-msft, I understand that now. I was getting confused, as this is one of the few commands where it's actually something other than the `--name` parameter, combined with the `--resource-group` that builds the ID. In this case it was the `--server-name`. 

I was hoping that it would be possible to create a database in a resource group other than the server, but it's not the case.
