### ISSUE TITLE
unable to login to AZ 

### ISSUE THREAD

**Issue by parasdesaicims** [Azure/azure-cli#13032]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
request failed: Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy. Error detail: Error occurred in request., SSLError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /tenants?api-version=2019-06-01 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
macOS-10.15.4-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.3.1

Extensions:
interactive 0.4.3

```

**Comment by yungezz** [comment]
hi @arrownj  could you pls have a look?thanks

**Comment by arrownj** [comment]
Hi @parasdesaicims , didn't you follow the instructions in the error message to get rid of this problem?

**Comment by parasdesaicims** [comment]
I do not understand, what exactly is the error message is pointing to specifically. Any help would be appreciated.

**Comment by parasdesaicims** [comment]
Tried resolving with the instructions here: 
1. https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy
2. https://blog.jhnr.ch/2018/05/16/working-with-azure-cli-behind-ssl-intercepting-proxy-server/

Still no luck. Can you please help.  
Env. is 
macOS-10.15.4-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.3.1

Extensions:
interactive 0.4.3

**Comment by parasdesaicims** [comment]
The issue is resolved.  It will be handy if there is a section for MAC users in the cli document.

**Comment by ShreyasNBS** [comment]
@parasdesaicims How did you fix this on MAC? Did you download any ca bundle online and trust in locally in system keychain?

**Comment by TeplrGuy** [comment]
@parasdesaicims it would be helpful to know how you resolved this

**Comment by parasdesaicims** [comment]
@TeplrGuy  @ShreyasNBS  Basically, grab the CA cert of the Proxy and update the cert on azure-cli - cacert.pem. Then just update the env. variable with **echo REQUESTS_CA_BUNDLE=*PATH*/CACERT.PEM.**

Note: Perform similar steps when you upgrade the cli version. learned that the hard way.

**Comment by TeplrGuy** [comment]
@parasdesaicims thanks for the response
