### ISSUE TITLE
[ACS] The create command doesn't support auto-completion for its orchestrator-type argument

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1304]
The help text for the `az acs create` command doesn't mention what the allowable values are for the `--orchestrator-type` argument  (other than mentioning that `dcos` is the default value), and that argument also doesn't seem to support auto-completion. It would be great if it was clearer that Swarm, DC/OS and Kubernetes were supported, and if so, the exact values that the command expected in order to use them.

**Comment by mayurid** [comment]
@brendanburns to comment

**Comment by brendandburns** [comment]
@lostintangent thanks for the feature request, definitely worth doing.

**Comment by brendandburns** [comment]
@mayurid I can't seem to assign this to myself, can someone else do it?

**Comment by mayurid** [comment]
@brendandburns : done and labelled it correctly too.

**Comment by yugangw-msft** [comment]
@brendandburns , make sure the swagger (and python sdk) exposes the new enum member, move all acs commands/params from `vm` to `acs` module like we planned, then the auto-completion will work automatically

**Comment by brendanburns** [comment]
Cool, swagger update is merged, in waiting on the pypi update will get to
it early next week.

Thanks
Brendan

**Comment by yugangw-msft** [comment]
fixed through #1326

**Comment by lostintangent** [comment]
@brendandburns Thanks for the really fast turnaround!
