### ISSUE TITLE
Azure China missing API version '2020-03-01' for type 'managedClusters' - API version 2020-03-01 is not supported

### ISSUE THREAD

**Issue by sarndt** [Azure/azure-cli#13047]
## Describe the bug

Trying to get credentials via az aks get-credentials fails because of an unsupported API version.

**Command Name**
`az aks get-credentials`

**Errors:**
```
No registered resource provider found for location 'chinaeast2' and API version '2020-03-01' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31, 2019-02-01, 2019-04-01, 2019-06-01, 2019-08-01, 2019-10-01, 2019-11-01, 2020-01-01, 2020-02-01'. The supported locations are 'chinaeast2, chinanorth2'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Log in to Azure CLI with `az login`
- `az aks get-credentials --resource-group {} --name {}`

## Expected Behavior

Command should succeed and retrieve credentials.

## Environment Summary
```
macOS-10.15.3-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.3.1

Extensions:
azure-devops 0.11.0

```

**Comment by sarndt** [comment]
Sorry, this seems to be an issue on our end (configuration) not an issue with Azure CLI itself, I will investigate this further and re-open in case I come to a different conclusion.

**Comment by sarndt** [comment]
Hello again, having to re-open this, what actually is the type of the resource provider that needs to be registered for this command to work? I don't see any unregistered resource provider that sounds correct, but I do see several registered ones that might be right. None of them have the exact name (managedClusters) though, how can I find out what the correct resource provider is?

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by jluk** [comment]
This is a known issue awaiting an API deployment in Azure China, ETA to be shared in a week

**Comment by sarndt** [comment]
Thanks @jluk for the details, I will wait for the deployment and china and retry afterwards.

**Comment by jluk** [comment]
Hey @sarndt this should now be available, apologies for the delay. Closing as a result.

Please give it a try and let me know if it still repros, and I will revisit.

**Comment by sarndt** [comment]
I can confirm that this has been working in the meantime, didn't retest it today though, but it should be fine. You can close it from my perspective.
