### ISSUE TITLE
appservice plan create

### ISSUE THREAD

**Issue by zyrustawa** [Azure/azure-cli#13057]
## Describe the bug

**Command Name**
`az appservice plan create`

**Errors:**
```
This region has quota of 0 instances for your subscription. Try selecting different region or SKU.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan create --name {} --resource-group {} --location {}`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

```

**Comment by yonzhan** [comment]
appservice

**Comment by panchagnula** [comment]
from the error message looks like your sub is out of quota - either delete some existing ASPs or try a different region or sky like the message suggested. Thanks!
