### ISSUE TITLE
[ACS] Help text for the create command's service principal arguments aren't clear

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1305]
As far as I can tell, when you create a Kubernetes cluster via `az acs create`, it will generate a new service principal for you if you didn't specify the `--client-secret` or `--service-principal` arguments. This behavior is great, however, the help text doesn't make it clear whether this is the default/expected behavior, and therefore, users might expect to need to specify them.

**Comment by mayurid** [comment]
@brendanburns to comment..

**Comment by brendandburns** [comment]
@lostintangent Can you clarify where you want the help text?  On the `acs create` command?  Or on the flags themselves?

Thanks
--brendan

**Comment by lostintangent** [comment]
@brendandburns Ah sorry that I didn't mention this detail! I was thinking it would be nice if this was mentioned in the help text of the ACS create command. Similarly to how the argument for the SSH key mentions that it will use your local id_rsa.pub file if unspecified.

**Comment by lostintangent** [comment]
BTW I love that the Kubernetes cluster creation auto-creates a service principal for you. It's a really great user experience overall :)
