### ISSUE TITLE
AKS disable cluster autoscaling errors with UnmarshalEntity encountered error

### ISSUE THREAD

**Issue by asos-aysefasoulas** [Azure/azure-cli#13050]
**Describe the bug**
When attempting to disable cluster autoscaling on the AKS cluster, I receive the following error:
Operation failed with status: 'Bad Request'. Details: UnmarshalEntity encountered error: json: cannot unmarshal bool into Go struct field Properties.properties.autoScalerProfile of type string.

**To Reproduce**
The az aks command used is:
az aks update --resource-group "rg" --name "name" --disable-cluster-autoscaler

**Expected behavior**
The AKS cluster should be updated with AKS Autoscaling disabled
"enableAutoScaling": false,

**Environment summary**
cli version: 2.3.1 
run on platforms: Windows 10 and Ubuntu 18.04.4 LTS
AKS version 1.16.7

**Additional context**
the same command works with azure cli 2.0.81

the enable autoscaling command works with cli 2.3.1
az aks update --resource-group "rg" --name "name" --enable-cluster-autoscaler --min-count 2 --max-count 5

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
@marwanad this look familiar to you?

**Comment by marwanad** [comment]
That's a known issue with AZ CLI 2.3.1.

Unfortunately, for now, the fix is to use CLI extensions `az extension add --name aks-preview
` or an older CLI version. Disabling through portal works too.

The next CLI release on 04/21/2020 will address this issue.

**Comment by kwaazaar** [comment]
I get the same issue when scaling manually: UnmarshalEntity encountered error: json: cannot unmarshal bool into Go struct field Properties.properties.autoScalerProfile of type string.

I have autoscaler enabled, so probably should have disabled it first. Nevertheless, this is not the error I expected.

Also using 2.3.1.

**Comment by jluk** [comment]
Please upgrade to CLI 2.4.0, this should be fixed as a known issue. I will close this as a result, but if you continue to hit this error on the latest version comment and we will revisit.

Thanks for the feedback!
