### ISSUE TITLE
Webapp:issui while deploying zip

### ISSUE THREAD

**Issue by RaymoEf** [Azure/azure-cli#13058]
## Describe the bug

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
('Connection aborted.', OSError("(10054, 'WSAECONNRESET')",))
Traceback (most recent call last):
urllib3\urllib3\contrib\pyopenssl.py, ln 320, in _send_until_done
pip-install-_1mlo87m\pyOpenSSL\OpenSSL\SSL.py, ln 1757, in send
pip-install-_1mlo87m\pyOpenSSL\OpenSSL\SSL.py, ln 1663, in _raise_ssl_error
OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

...

pip-install-_1mlo87m\requests\requests\sessions.py, ln 643, in send
pip-install-_1mlo87m\requests\requests\adapters.py, ln 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')",))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip --resource-group {} --name {} --src {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
This is a really old version of CLI please get the latest version and re-try or use shell.azure.com
