### ISSUE TITLE
PIM support

### ISSUE THREAD

**Issue by niand** [Azure/azure-cli#13064]
**Is your feature request related to a problem? Please describe.**
We often need to set up resource groups that will require activation through PIM to access them. Currently we need to do this via the portal, which means RG creation cannot be automated fully. In addition, setting this up in PIM requires quite a few clicks today.

**Describe the solution you'd like**
Functionality in az cli to set a user or group as eligible for a role on a specific subscription / resource / resource group. 

**Describe alternatives you've considered**
PowerShell, however this didn't work well with our current pipeline.

**Comment by yonzhan** [comment]
add to S170

**Comment by jiasli** [comment]
Hi @niand, thanks for the feedback. However, Azure CLI currently has no native support for **Privileged Identity Management**. 

You may call the [Microsoft Graph REST API for Privileged Identity Management](https://docs.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta) directly with `az rest`. For examples, you may check https://github.com/Azure/azure-cli/issues/12946. 

You may run `az rest --help` to check out how to use this command.

**Comment by SaschaSchuenemann** [comment]
+1 for the issue. 
In a similar fashin, we would like to automatically set up / delete access reviews via CLI instead of the Portal

**Comment by danijam** [comment]
@jiasli why has this been closed and the feature-request label removed?

**Comment by yonzhan** [comment]
The reason is in https://github.com/Azure/azure-cli/issues/17712

**Comment by danijam** [comment]
@yonzhan OK so I see it reads this is not supported, which is kind of the point of this ticket. But that doesn't explain why this has been closed. My understanding is this is a feature request and so it would remain open until implemented or closed because it has been rejected as an item of feedback. So are we saying that the decision has been taken that this feedback has been rejected? I haven't seen that mentioned anywhere. Would be good to get the clarified so others discovering this in the future know that was the decision

**Comment by jiasli** [comment]
Hi @danijam, apologize for the confusion caused. PIM belongs to AAD's Microsoft Graph API.

Azure CLI is a client-side tool dedicated to manage Azure Resources. [Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview) (even though it belongs to Azure) is a very complicated service that falls out of the scope of Azure CLI.

The current `az ad` command module is only designed for assisting Azure CLI users to manage Azure resources, mainly [Azure Resource Manager](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview) resources.

However, Azure CLI team currently has no bandwidth maintaining the `az ad` command module which still uses the deprecated AD Graph API. For this part, we are working across different teams for a solution. As I pointed out in https://github.com/Azure/azure-cli/issues/12946#issuecomment-737196942, Microsoft Graph is developing their own CLI for a boarder coverage of Microsoft Graph API.

The future of `az ad` has not been decided. We _may_ migrate existing commands to use Microsoft Graph API, but for other features of Microsoft Graph API like Privileged Identity Management, Azure CLI may never support them with native commands. That's why this ticket has been closes.

> why has this been closed and the feature-request label removed?

We have an internal system that tracks the progress of feature-request issues. We wouldn't want this issue to stay open in our queue for years without any promise to implement it. 

Closing it doesn't mean we are not tracking it. We won't lock this issue and you may still vote on it. (In fact, Azure CLI hasn't locked any issue by now.) We will revisit it if the vote count is high enough. 😊

**Comment by danijam** [comment]
@jiasli Thank you for the detailed response! Appreciate it.

**Comment by jwefers** [comment]
@jiasli i would like to challenge this reasoning - PIM exists for both AAD roles and RBAC roles.
The RBAC part of it - Role Eligibility Requests, Instances, Schedules - are clearly subresources of the applicable scope of an Azure resource (https://learn.microsoft.com/en-us/rest/api/authorization/role-eligibility-schedules/list-for-scope?tabs=HTTP):

```
GET https://management.azure.com/{scope}/providers/Microsoft.Authorization/roleEligibilitySchedules?api-version=2020-10-01
```

So i would argue that at least the RBAC part of PIM should be supported by the Azure CLI. They are just fancy RBAC.

**Comment by munntjlx** [comment]
I did find the 'new' way of doing this: https://learn.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignmentschedulerequests?view=graph-rest-1.0&tabs=powershell go to example '2'. It has a PowerShell on how to do it.

**Comment by munntjlx** [comment]
https://learn.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignmentschedulerequests?view=graph-rest-1.0&tabs=powershell shows how to do it in PowerShell, and I suspect 'api' ways....... Go to example 2.

**Comment by archmangler** [comment]
Hi, we have an enterprise use-case for PIM via az cli (at minimum). Where is this feature being tracked?

**Comment by veridicis** [comment]
another enterprise use-case here, especially regarding privilege access groups and member eligibility, native azure rbac support is not enough

**Comment by jiasli** [comment]
@jwefers, thanks for the additional information. We will surely discuss about this with our Product Managers and RBAC service team. However, our TODO list for this semester has been fully occupied, so please expect delay in this feature request.

For now, you may use `az rest` to directly invoke the REST API.

**Comment by iansong1995** [comment]
Hi there, I see I am several years late, but I'm also facing this issue.

specifically, I'm not able to get **az rest** to work at all

I have even manually assigned a role and compared the API call with my code (I had even tried taking the raw body and test it)
![image](https://github.com/Azure/azure-cli/assets/84297052/2120ffae-bfa1-40f6-82c0-d1c9c162ecf1)
![image](https://github.com/Azure/azure-cli/assets/84297052/efc0ef6e-b01e-4816-bc22-2936655d0eaf)

This is what I tried in code
![image](https://github.com/Azure/azure-cli/assets/84297052/d9e5e0d2-be0b-460d-9add-a607faecc113)
![image](https://github.com/Azure/azure-cli/assets/84297052/29415c76-1319-415b-b160-1a125a881c2a)
I've tried many ways to setting up the payload, including doing something like @{ "key"="value" } | ConvertTo-Json etc.
Nothing worked, and I always just get back a generic error "Request Body is invalid"
![image](https://github.com/Azure/azure-cli/assets/84297052/060c018f-0d76-4a97-974d-d3c548a64768)

Any advice (or even better: a working example) would be greatly appreciated 🙏

**Comment by jwefers** [comment]
if you wait till tuesday, i'll let you know the exact request bodies

**Comment by munntjlx** [comment]
Thats wonderful news!

________________________________________

**Comment by jwefers** [comment]
So, my powershell code using the `Az` module looks like this:
```ps
$scope = "some/azure/resource/id/without/first/slash"
$s#cope = "subscriptions/120cffbb-75e1-4e31-b0c3-56ee9e17ed30"
$roleName = "Owner" # or whatever
$roleDefinitionId = "/$scope/providers/Microsoft.Authorization/roleDefinitions/$((Get-AzRoleDefinition -Name $roleName).Id)"
$durationHours = 1

# get the object id of the user logged in
$principalId = (Get-AzAdUser -UserPrincipalName (Get-AzContext).Account.Id).Id

# find the first matching role eligibility for this user, scope and role.
# There might be multiple, but it probably does not matter which one we activate
$eligibilitySchedule = Get-AzRoleEligibilitySchedule `
    -Scope $scope `
    -Filter "assignedTo('$principalId') and atScope() and roleDefinitionId eq '$roleDefinitionId'" |
Select-Object -First 1

# Activate role
New-AzRoleAssignmentScheduleRequest `
    -Name (New-Guid).Guid `
    -RequestType 'SelfActivate' `
    -ExpirationType 'AfterDuration'  `
    -ExpirationDuration "PT$($durationHours)H" `
    -PrincipalId $principalId `
    -Scope $scope `
    -LinkedRoleEligibilityScheduleId $eligibilitySchedule.Id `
    -RoleDefinitionId $roleDefinitionId `
    -Justification "some reason"
```

If we convert this to `az rest`, we should arrive somewhere like

```bash
scope="/subscriptions/120cffbb-75e1-4e31-b0c3-56ee9e17ed30" #/resourceGroups/eon-cmp-eam-data-import-dev/providers/Microsoft.DataFactory/factories/eon-cmp-datafactory-dev"
roleName="Owner"
roleDefinitionId=$(az role definition list --name $roleName --scope $scope --query [0].id -o tsv)
durationHours=2
justification="i need to do stuff"

# get the object id of the user logged in
principalId=$(az ad user show --id $(az account show -o tsv --query user.name) -o tsv --query id)

# https://learn.microsoft.com/en-us/rest/api/authorization/role-eligibility-schedules/list-for-scope?view=rest-authorization-2020-10-01&tabs=HTTP
eligibilityScheduleId=$(az rest \
  --uri "https://management.azure.com$scope/providers/Microsoft.Authorization/roleEligibilitySchedules" \
  --uri-parameters "\$filter=assignedTo('$principalId') and atScope() and roleDefinitionId eq '$roleDefinitionId'" \
                   "api-version=2020-10-01" \
  --query value[0].id \
  -o tsv)

# activate role
az rest \
    --method PUT \
    --uri "https://management.azure.com$scope/providers/Microsoft.Authorization/roleAssignmentScheduleRequests/$(uuid)?api-version=2020-10-01" \
    --body "
        {
            \"properties\": {
                \"principalId\": \"$principalId\",
                \"roleDefinitionId\": \"$roleDefinitionId\",
                \"requestType\": \"SelfActivate\",
                \"linkedRoleEligibilityScheduleId\": \"$eligibilityScheduleId\",
                \"justification\": \"$justification\",
                \"scheduleInfo\": {
                    \"expiration\": {
                        \"type\": \"AfterDuration\",
                        \"duration\": \"PT$(echo $durationHours)H\"
                    }
                }
            }
        }"
```

**Comment by jwefers** [comment]
**EDIT: following up with full fleshed bash function to put in bashrc:**
(mac users please replace `$(uuid)` with `$(uuidgen)`)
```sh
pim() {
    local environment=$1
    local reason=${2:-"work"}
    local hours=${3:-8}
    local passthrough_params=("${@:4}")

    # Validate required inputs
    if [[ -z "$environment" ]]; then
        echo "Error: Environment is required." >&2
        return 1
    fi
    if [[ -z "$reason" ]]; then
        echo "Error: Reason is required." >&2
        return 1
    fi
    if ! [[ "$hours" =~ ^[1-8]$ ]]; then
        echo "Error: Hours must be between 1 and 8." >&2
        return 1
    fi

    # Validate Azure CLI is logged in
    if ! az account show >/dev/null 2>&1; then
        echo "Error: Not logged into Azure CLI. Run 'az login' first." >&2
        return 1
    fi

    # Get principal (user) ID
    local principalId
    principalId=$(az ad signed-in-user show --query id -o tsv $passthrough_params)
    if [[ -z "$principalId" ]]; then
        echo "Error: Could not retrieve principal ID." >&2
        return 1
    fi

    # Helper function to activate a single role
    activate_role() {
        local scope="$1"
        local role_name="$2"

        # Get role definition ID
        local roleDefinitionId
        roleDefinitionId=$(az role definition list --name "$role_name" --scope "$scope" --query "[0].id" -o tsv $passthrough_params)
        if [[ -z "$roleDefinitionId" ]]; then
            echo "Error: Role definition '$role_name' not found in scope '$scope'" >&2
            return 1
        fi

        # Query role eligibility schedule
        local eligibilityScheduleId
        eligibilityScheduleId=$(az rest \
            --uri "https://management.azure.com${scope}/providers/Microsoft.Authorization/roleEligibilitySchedules" \
            --uri-parameters "\$filter=assignedTo('$principalId') and atScope() and roleDefinitionId eq '$roleDefinitionId'" "api-version=2020-10-01" \
            --query "value[0].id" \
            --output tsv $passthrough_params)

        if [[ -z "$eligibilityScheduleId" ]]; then
            echo "Error: No eligibility schedule found for role '$role_name' in scope '$scope'" >&2
            return 1
        fi

        # Activate role assignment
        echo "Activating role '$role_name' in scope '$scope' for $hours hour(s)..." >&2

        az rest \
            --method PUT \
            --uri "https://management.azure.com${scope}/providers/Microsoft.Authorization/roleAssignmentScheduleRequests/$(uuid)?api-version=2020-10-01" \
            --body "{
                \"properties\": {
                    \"principalId\": \"$principalId\",
                    \"roleDefinitionId\": \"$roleDefinitionId\",
                    \"requestType\": \"SelfActivate\",
                    \"linkedRoleEligibilityScheduleId\": \"$eligibilityScheduleId\",
                    \"justification\": \"$reason\",
                    \"scheduleInfo\": {
                        \"expiration\": {
                            \"type\": \"AfterDuration\",
                            \"duration\": \"PT${hours}H\"
                        }
                    }
                }
            }" $passthrough_params
    }

    # === Environment-specific role activation ===
    # Each case defines its own list of {scope, role} pairs
    case "$environment" in
        "myenv1")
            activate_role "/subscriptions/xxx" "Owner"
            ;;
        "myotherenv")
            activate_role "/subscriptions/xxx" "Owner"
            # example: also activate another role in the same environment
            activate_role "/subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.KeyVault/vaults/zzz" "Key Vault Secrets Officer"
            ;;
        *)
            echo "Error: Unknown environment '$environment'. Valid options:" >&2
            echo "  myenv1,myotherenv " >&2
            return 1
            ;;
    esac
}
```
call it with `pim myenv1 "my task" 3` or similar.

**=== ORIGINAL POST ===**

So, my powershell code using the `Az` module (where this is supported) looks like this:
```ps1
$scope = "some/azure/resource/id/without/first/slash"
$roleName = "Owner" # or whatever
$roleDefinitionId = "/$scope/providers/Microsoft.Authorization/roleDefinitions/$((Get-AzRoleDefinition -Name $roleName).Id)"
$durationHours = 1

# get the object id of the user logged in
$principalId = (Get-AzAdUser -SignedIn).Id

# find the first matching role eligibility for this user, scope and role.
# There might be multiple, but it probably does not matter which one we activate
$eligibilitySchedule = Get-AzRoleEligibilitySchedule `
    -Scope $scope `
    -Filter "assignedTo('$principalId') and atScope() and roleDefinitionId eq '$roleDefinitionId'" |
Select-Object -First 1

# Activate role
New-AzRoleAssignmentScheduleRequest `
    -Name (New-Guid).Guid `
    -RequestType 'SelfActivate' `
    -ExpirationType 'AfterDuration'  `
    -ExpirationDuration "PT$($durationHours)H" `
    -PrincipalId $principalId `
    -Scope $scope `
    -LinkedRoleEligibilityScheduleId $eligibilitySchedule.Id `
    -RoleDefinitionId $roleDefinitionId `
    -Justification "some reason"
```

If we convert this to `az rest` and bash, we should arrive somewhere like

```bash
scope="/subscriptions/<sub>"
roleName="Owner"
roleDefinitionId=$(az role definition list --name $roleName --scope $scope --query [0].id -o tsv)
durationHours=2
justification="i need to do stuff"

# get the object id of the user logged in
principalId=$(az ad signed-in-user show -o tsv --query id)

# find the first matching role eligibility for this user, scope and role.
# There might be multiple, but it probably does not matter which one we activate
eligibilityScheduleId=$(az rest \
  --uri "https://management.azure.com$scope/providers/Microsoft.Authorization/roleEligibilitySchedules" \
  --uri-parameters "\$filter=assignedTo('$principalId') and atScope() and roleDefinitionId eq '$roleDefinitionId'" \
                   "api-version=2020-10-01" \
  --query value[0].id \
  -o tsv)

# activate role
az rest \
    --method PUT \
    --uri "https://management.azure.com$scope/providers/Microsoft.Authorization/roleAssignmentScheduleRequests/$(uuid)?api-version=2020-10-01" \
    --body "
        {
            \"properties\": {
                \"principalId\": \"$principalId\",
                \"roleDefinitionId\": \"$roleDefinitionId\",
                \"requestType\": \"SelfActivate\",
                \"linkedRoleEligibilityScheduleId\": \"$eligibilityScheduleId\",
                \"justification\": \"$justification\",
                \"scheduleInfo\": {
                    \"expiration\": {
                        \"type\": \"AfterDuration\",
                        \"duration\": \"PT$(echo $durationHours)H\"
                    }
                }
            }
        }"
```

**Comment by Res260** [comment]
Requiring usage of the browser GUI or a clunky `az rest` command to use PIM truely sucks and is bad developper experience :( I hope this gets reconsidered as the current state of things is very suboptimal.
