### ISSUE TITLE
az login fails

### ISSUE THREAD

**Issue by rmcanall** [Azure/azure-cli#13065]
Received attached error when trying to setup for frontline project. using "az login" 
<img width="429" alt="Screen Shot 2020-04-17 at 7 14 39 AM" src="https://user-images.githubusercontent.com/47162642/79568603-bf7a0880-807b-11ea-8f2b-6c02d5cbb51d.png">

**Comment by yonzhan** [comment]
add to S170

**Comment by jiasli** [comment]
Could you click on **More details** and share the information? Thank you.

**Comment by yonzhan** [comment]
@rmcanall any update?

**Comment by jiasli** [comment]
This issue seems to be caused by your tenant settings. Azure CLI is a first-party app and should have already been allowed in all Azure Clouds. If you have more information, please let us know or you may create a Support Request in Azure Portal for **Azure Active Directory**.
