### ISSUE TITLE
webapp: support connecting privately to a Web App using Azure Private Endpoint 

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#13072]
**Is your feature request related to a problem? Please describe.**
https://docs.microsoft.com/en-us/azure/private-link/create-private-endpoint-webapp-portal

**Describe the solution you'd like**

**Update:** 

Changed to support connecting privately to a Web App using private endpoint connections under `az network private-endpoint-connection`

The following commands:
`az network private-link-service list`,
`az network private-endpoint-connection (approve, delete, list, reject, show)`
Should work with `--type Microsoft.Web/sites`

**Before:**

Command | CLI | PowerShell | Description
-- | -- | -- | --
Get Private Endpoint Connection. Takes: site info + private endpoint connection name. Returns: private endpoint connection info | Az webapp private-endpoint-connection list | Get-AzWebAppPrivateEndpointConnection | Gets the details.  If the optional private endpoint name is specified, will return the details for just that one private endpoint.  If just the app name is specified, will return the details for all of the private endpoints on that app. Arguments: sitename, optional:private endpoint name
Delete Private Endpoint Connection. Takes: site info + private endpoint connection name | Az webapp private-endpoint-connection delete | Delete-AzWebAppPrivateEndpointConnection | Removes a private endpoint from an app. Arguments: sitename private endpoint name
Approve Private Endpoint Connection. Takes: site info + private endpoint connection name. Returns: private endpoint connection info | Az webapp private-endpoint-connection approve | Set-AzWebAppPrivateEndpointConnection | Sets the approve status on  requested private endpoint connection with an app. CLI Arguments: sitename private endpoint name. Powershell Arguments: sitename private endpoint name  "approve"
Reject Private Endpoint Connection. Takes: site info + private endpoint connection name. Returns: private endpoint connection info | Az webapp private-endpoint-connection reject | Set-AzWebAppPrivateEndpointConnection | Sets the reject status on  requested private endpoint connection with an app. CLI Arguments: sitename private endpoint name. Powershell Arguments: sitename private endpoint name  "reject"

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
webapp

**Comment by yonzhan** [comment]
move to S170
