### ISSUE TITLE
az aks create AttributeError: 'NoneType' object has no attribute 'client_id'

### ISSUE THREAD

**Issue by travis-sobeck** [Azure/azure-cli#13074]
I just updated to the latest version of Azure CLI and az aks create is bombing with a less than helpful response (to me).

## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
'NoneType' object has no attribute 'client_id'
Traceback (most recent call last):
pip-install-_1mlo87m\knack\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 625, in execute
cli\core\commands\__init__.py, ln 689, in _run_jobs_serially
cli\core\commands\__init__.py, ln 682, in _run_job
...
cli\command_modules\acs\custom.py, ln 1750, in aks_create
AttributeError: 'NoneType' object has no attribute 'client_id'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --generate-ssh-keys --aad-server-app-id {} --aad-server-app-secret {} --aad-client-app-id {} --aad-tenant-id {} --network-plugin {} --dns-name-prefix {} --vnet-subnet-id {} --docker-bridge-address {} --dns-service-ip {} --service-cidr {} --subscription {} --location {} --kubernetes-version {} --node-count {} --node-vm-size {} --enable-managed-identity --network-policy {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1

```

**Comment by travis-sobeck** [comment]
by the way, if just remove '--enable-managed-identity' and leave everything else,  it kicks off the build.  This would be so bad accept afaik you can NOT go back later and enable managed identity and this seems to very clearly be the recommended path forward as apposed to S.Ps

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by jluk** [comment]
@JunSun17 does this error look familiar in relation to the other nonetype errors we've resolved?

**Comment by JunSun17** [comment]
@jluk I think so, they all just mean something is null, and not as expected.

**Comment by travis-sobeck** [comment]
like I said, removing the flag, it worked as normal so I know there were not any null values :)

**Comment by travis-sobeck** [comment]
After updating vscode (not really sure that's relevant, but ..), I scrapped my cluster a rebuilt, the only change was I set the node/vm type to 'Standard_E2s_v3', everything else is the same and it build the cluster just fine with the '--enable-managed-identity' flag.

**Comment by travis-sobeck** [comment]
I'll open an new issue  if the issue comes up again
