### ISSUE TITLE
az vm create .. --ssh-key ~/.ssh/id_rsa.pub not working on Windows

### ISSUE THREAD

**Issue by chaliy** [Azure/azure-cli#1307]
Trying to use az in crossplat way. I want to use global SSH key in home directory.

`
cat ~/.ssh/id_rsa.pub # works in PowerShell
`
And then try to create VM on Windows with 
`
az vm create -n test -g test --image UbuntuLTS --admin-username ops --ssh-key ~/.ssh/id_rsa.pub
`
Getting error:

```
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"target\": \"linuxConfiguration.ssh.publicKeys.keyData\",\r\n    \"message\": \"The value of parameter linuxConfiguration.ssh.publicKeys.keyData is invalid.\"\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}
```

I understand root cause, and absolute path actually works fine, but most examples uses `~/.ssh/id_rsa.pub` and so it might be beneficial to make such paths support in az tool or at least improve input validation.

**Comment by yugangw-msft** [comment]
@chaliy, so i assume you use `--ssh-key ~/.ssh/id_rsa.pub` is a regular windows command window?

**Comment by chaliy** [comment]
@yugangw-msft yep. Actually I use Makefile that I run both Windows (powershell console) and Linux (bash console). I realize that ~/.ssh/id_rsa.pub is not native for Windows, but for example Powershell already supports this.

**Comment by yugangw-msft** [comment]
/cc:@johanste
We should go ahead to support expanding the `~`, so that the same script can run cross platforms.
