### ISSUE TITLE
AZ CLI support for Security Partner Provider

### ISSUE THREAD

**Issue by ishaniGupta27** [Azure/azure-cli#13075]
**Resource Provider**
NRP (Microsoft.Network)

**Description of Feature or Work Requested**
Security Partner Provider is a new Top Level Resource in NRP which represents the 3rd Party Security Providers in Virtual Hub. 

**Minimum API Version Required**
03-01-2020

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2020-03-01/securityPartnerProvider.json

**Target Date**
May 15th

**Comment by yungezz** [comment]
service team support request

**Comment by yonzhan** [comment]
add to S169

**Comment by MyronFanQiu** [comment]
@ishaniGupta27 Hi. Is the word `Provider` necessary for customers? `security-partner-provider` is quite long and I'm planning to name in `security-partner` in cmdlet. Is that possible?

**Comment by ishaniGupta27** [comment]
I believe to keep consistency having it as security-partner-provider seems to be better choice. I am using the whole name in powershell/portal.
