### ISSUE TITLE
I get this issue when I try to get info from api-management resource via azure-cli

### ISSUE THREAD

**Issue by luis-sandoval-jdas** [Azure/azure-cli#13071]
## Describe the bug

**Command Name**
`az apim show`

**Errors:**
```
No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
Traceback (most recent call last):
Temp\pip-install-umfcm_n2\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 523, in execute
azure-cli-core\azure\cli\core\__init__.py, ln 292, in load_arguments
azure\cli\command_modules\apim\__init__.py, ln 28, in load_arguments
azure\cli\command_modules\apim\_params.py, ln 11, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.apimanagement.models.api_management_client_enums'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim show --name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.76 *

Extensions:
azure-firewall 0.3.1

```

**Comment by yonzhan** [comment]
apim

**Comment by PramodValavala-MSFT** [comment]
@luis-sandoval-jdas Looks like this has since been fixed and I can confirm that there is no error now. Apologies for no updates on this issue sooner. Unless you are still seeing this error on your end, I believe this could be closed.
