### ISSUE TITLE
azure-cli on ubuntu 18.04 does not find  IoT Hub

### ISSUE THREAD

**Issue by dbartz** [Azure/azure-cli#13083]
## Describe the bug

I wanted to run the IoT Edge Tutorial 
https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux
using the azure-cli on my own Ubuntu notebook (the tutorial uses cloud shell).

**Errors:**

After creating the IoT Hub, 
`az iot hub device-identity create --hub-name {correct-hub-name} --device-id myEdgeDevice --edge-enabled`
fails:
`No IoT Hub found with name {correct-hub-name} in current subscription.`

Listing the IoT hubs returns an empty list:
`az iot hub list --subscription {correct-subscription-name}`
`[]`

Strangely, if I run the exact same command
`az iot hub list --subscription {correct-subscription-name}`
 in cloud shell, it returns my IoT Hub

## Environment Summary
```
Linux-5.3.0-46-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.3.1

Extensions:
azure-iot 0.9.1
azure-devops 0.15.0

```

**Comment by qianwens** [comment]
IOT hub issue.

**Comment by jlian** [comment]
@digimaun @iluican any ideas?

**Comment by digimaun** [comment]
I'm currently unable to repro the issue in my ubuntu 18.04 environment with `azure-iot 0.9.1`, but one difference in environment is I installed the latest `2.4.0` base CLI.

I do want to verify one thing - @dbartz , please make sure you have set your default CLI subscription via `az account set -s <your correct subscription guid or name>`. After setting the default sub, please try again and let us know if you are still having problems. For the IoT extension we don't typically use `--subscription` argument in commands rather the explicit setting of default subscription is expected prior to execution.

**Comment by dbartz** [comment]
Hi @digimaun,
setting the default account does not make a difference. 

I actually worked with the correct default account and just posted the command with specified subscription in order to not being asked if I set the default subscription correctly :-)

Meanwhile, I am also on 2.4.0, which does not make a difference.

**Comment by digimaun** [comment]
Please run the commands and append `--debug` in each environment you are using (cloud shell & ubuntu).

Look at the debug logs and take note of `management.azure.com` against `Microsoft.Devices/IotHubs`

You should notice a debug entry that looks like this (API versions will differ - as of this comment, cloud shell is using Azure CLI 2.2.0):

`urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/{your-correct-subscription-id}/providers/Microsoft.Devices/IotHubs?api-version=2019-11-04 HTTP/1.1" 200`

And the related response content:

```
msrest.http_logger : Response content:
msrest.http_logger : {"value":[{"id":"/subscriptions/
```

Please verify the API calls between cloud shell/non-cloud shell are against the same subscription GUID in the request and validate the response content coming back. Please also note the API versions for this exercise - I am wondering if a particular API version is the cause of this issue.

**Comment by dbartz** [comment]
Hi @digimaun,
thanks for looking into this.

I followed your advice and looked into the debug logs. The reason for not finding the IoT Hub was trivial and entirely my fault:
Long time ago, I configured a default resource group on this machine, a fact which I even did not remember anymore.
