### ISSUE TITLE
Unable to create service fabric cluster using azure cli

### ISSUE THREAD

**Issue by sourav-dey** [Azure/azure-cli#13088]
## Describe the bug

**Command Name**
`az sf cluster create`

**Errors:**
```
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 625, in execute
    raise ex
cli/core/commands/__init__.py, ln 689, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/command_modules/servicefabric/custom.py, ln 1158, in _create_certificate
    cmd, cli_ctx, vault_resource_group_name, vault_name, location, enabled_for_deployment=True).result()
cli/command_modules/servicefabric/custom.py, ln 1667, in _create_keyvault
    permissions = Permissions(keys=[KeyPermissions.get,
AttributeError: 'NoneType' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a new azure test group to put the service fabric into_
- `az sf cluster create --resource-group {} --location {} --certificate-output-folder {} --certificate-password {} --certificate-subject-name {} --cluster-name {} --cluster-size {} --os {} --vault-name {} --vault-resource-group {} --vm-password {} --vm-user-name {}`

Put the argument values:
location: "westus"
certificate-output-folder:  .
certificate-subject-name: "sometestsf.westus.cloudapp.azure.com"
cluster-size: 2
os: UbuntuServer1604

## Expected Behavior
Should create proper service fabric cluster

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.3.1

```
## Additional Context

Tried it in the Bash CLI in portal.azure.com. Same error.

**Comment by yonzhan** [comment]
service fabric

**Comment by yungezz** [comment]
@a-santamaria

**Comment by navba-MSFT** [comment]
@sourav-dey Apologies for the late reply. Could you please use the most recent version of [Python libraries ](https://www.python.org/downloads/) and[ Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and test the behavior again ? Also this github thread has been in activity for quite sometime. Could you please let us know if you still need assistance on this? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@sourav-dey Please let us know if you are still facing this issue. If no further assistance is required on this, can we proceed with closure of this issue? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@sourav-dey We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
