### ISSUE TITLE
 issue  with .cer certificate

### ISSUE THREAD

**Issue by djaus2** [Azure/azure-cli#13098]
I have generated a ValidationCertification.cer file.
I now want to upload it and verify the certificate, without going to the Azure Portal.

```az iot dps certificate verify ``` only has and example for a .pem file.
Can I not use this command with the .cer file?

Nb: tried that and got:
```
PS C:\temp> azsphere tenant download-validation-certificate --output ValidationCertification139.cer --verificationcode CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

Saving the validation certificate to 'C:\temp\ValidationCertification139.cer'.
Saved the validation certificate to 'ValidationCertification139.cer'.

PS C:\temps> az iot dps certificate verify --dps-name $DPSName --resource-group $GroupName --name MyCertificate137 --path ValidationCertification139.cer --etag AAAAAALTXUo=

Invalid ETag supplied. If you contact a support representative please include this correlation identifier: 48ab965d-7916-46e9-9856-61745accce7a, timestamp: 2020-04-21 05:39:59Z, errorcode: IH412001.
```

The etag used was from the earlier ``` az iot dps certificate create``` command and used in the ```az iot dps certificate generate-verification-code``` command.

```
{
  "etag": "AAAAAALTXUo=",
  "id": "/s
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f10e44a3-521f-07e1-407d-10656f1cf204
* Version Independent ID: 1ef12d7e-0c22-6127-9aed-46c9c89104b4
* Content: [az iot dps certificate](https://docs.microsoft.com/en-us/cli/azure/iot/dps/certificate?view=azure-cli-latest#az-iot-dps-certificate-list)
* Content Source: [src/azure-cli/azure/cli/command_modules/iot/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/iot/_help.py)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
iot

**Comment by djaus2** [comment]
Issue was that the etag  changes and has to be redetermined from a query to do the Verification. This is now part of my djaus2/az-iothub-ps GitHub repo

**Comment by djaus2** [comment]
Also found I can just use the full local path the 2nd  .cer file. Doesn't have to be .pem
Example documentation should be adjusted for that.

**Comment by cocowalla** [comment]
> Also found I can just use the full local path the Validation .cer file. Doesn't have to be .pem

If your .cer file is in PEM format, the file extension shouldn't matter (as long as the file [only contains the leaf](https://github.com/Azure/azure-cli/issues/11131)).

But I'm also having the same issue as you, and it seems to ot just affect `az iot dps certificate create`. I'm doing:

1. Get the etag with:
```bash
az iot dps certificate show
```

2. Get a verification code:
```bash
az iot dps certificate generate-verification-code
```

3. (create and sign a certificate)

4. Upload the verified cert, using the same etag from (1):
```bash
az iot dps certificate verify
```

This fails with `Invalid ETag supplied`

**Comment by djaus2** [comment]
You need to get the etag again after step 2 or 3.
That what I found and it works.
I have done that in my az-iothub-ps code on GitHub:
https:/github.com.djaus2/az-iothub-ps
I can do all of that Verification from the command line.

Unfortunately the same is not true for IoT Central Verification

**Comment by yiyiguo** [comment]
@Azure/azure-iot-cli-triage

**Comment by djaus2** [comment]
Please don't close this until it is resolved. Seems bots are closing a few of these unresolved issues saying they have been orphaned.

**Comment by c-ryan-k** [comment]
> 1. (create and sign a certificate)
> 2. Upload the verified cert, using the same etag from (1):
> 
> ```shell
> az iot dps certificate verify
> ```
> 
> This fails with `Invalid ETag supplied`

@cocowalla - just ran through this scenario, and @djaus2 is correct, the `generate-verification-code` function (and service call) returns the cert with a new etag along with the verification code. Because the verification code is stored in the properties of the backing certificate object, the etag will have changed since the initial show step, as both the `verificationCode` and `updated` time stamp have changed.

In order to work through closing this - @cocowalla and @djaus2 - are there any outstanding issues here (regarding this specific issue) in the functionality of the CLI itself? Or is the issue pertaining to missing / incomplete / incorrect documentation?

P.S - @cocowalla , I'm digging into #11131 (just reproed this with another example cert while running through this scenario) and will update you on that issue in that thread once I nail down the issue.

**Comment by c-ryan-k** [comment]
To clarify the verification process of commands (assuming all have `--dps-name {dps} -g {resource_group}`):

1.  `az iot dps certificate create  -p "path\to\cert" -n {cert_name}`
         - This uploads the certificate to the DPS instance, and returns `{..."etag": "etag1"}`
2.  [optional] `az iot dps certificate show -n {cert_name}`
         - This returns `{..."etag": "etag1"}`
3. `az iot dps certificate generate-verification-code -n {cert_name} --etag {etag1}`
         - This returns `{..."etag": "etag2"}` and the `verificationCode` for signing the verification certificate
4. Sign another certificate {cert2} using the `verificationCode` from step 3
5. `az iot dps certificate verify -n {cert_name} --etag {etag2} --path {path/to/cert2}`
         - This returns `{..."etag": "etag3"}` and `"isverified": true`

**Comment by djaus2** [comment]
Looking at this again now.

**Comment by vilit1** [comment]
@djaus2 Do you still need help with this issue? Otherwise, I would like to close it.
