### ISSUE TITLE
create --throughput for database with their own throughput 

### ISSUE THREAD

**Issue by chwarr** [Azure/azure-cli#13096]
Please clarify the `create --throughput` parameter, especially concerning how it interacts with database-level throughput and containers that need to not have their own throughput.

The documentation for the `create --throughput` parameter doesn't clearly explain how to create a container with no throughput, like one inside a database with database-level throughput. The documentation says "Default value is 400." I read this as saying that "if `--throughput` is omitted, the default value of 400 will be used".

However, what I've observed is when creating containers in a database with database-level throughput is that:

* omitting `--throughput` creates a container with no throughput,
* `--throughput 0` creates a container with its own 400 RU/s throughput,
* `--throughput 500` creates a container with its own 500 RU/s throughput, and
* specifying `--throughput` without a value fails with the error "argument --throughput: expected one argument".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e20da33-a85d-abf3-88d4-2c9c6d5c1ad9
* Version Independent ID: ac38600c-6df4-5898-4bd7-fe880eb36819
* Content: [az cosmosdb sql container](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/sql/container?view=azure-cli-latest#az-cosmosdb-sql-container-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cosmosdb

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by shurd** [comment]
Hi @chwarr thank you for opening this issue. We can extend the description of the throughput parameter in the help menu. We originally intended to keep this description short, which is why we did not explain every scenario. The throughput parameter is optional, but it behaves differently depending on whether it is contained within a shared database. If the database is shared, it will have no throughput. If the database is not shared, it will  have throughput equal to the default value.

**Comment by chwarr** [comment]
The help content that I see as of 2020-06-19 is the same as when I reported this:

> The throughput of SQL container (RU/s). Default value is 400.

I don't think this has actually been resolved.
