### ISSUE TITLE
Ability to enable threat protection for Postgres

### ISSUE THREAD

**Issue by danielbecroft** [Azure/azure-cli#13091]
**Is your feature request related to a problem? Please describe.**
When running the Azure Database for PostgreSQL server instance, I can enable Advanced Threat Protection (public preview) at the server level. This is only available in the portal, or the REST API, but not the CLI.

**Describe the solution you'd like**
A new option to enable threat protection on a PostgreSQL server instance.

```
e.g.
az postgres threat-protection
```

**Describe alternatives you've considered**
There is already the option for enabling this in the `az sql` grouping, but this requires a specific database to enable the functionality on. There is no requirement ot restrict to a database in the portal, so this could potentially just be extended to allow a server-wide enablement.

**Additional context**

**Comment by yonzhan** [comment]
postgres

**Comment by lfittl-msft** [comment]
@danielbecroft We unfortunately don't have support for enabling Advanced Threat Protection via CLI at this point, as the Advanced Threat Protection functionality is in Preview.

As you describe, this can be automated through the REST API as a workaround.

We are looking to enable this in the future, but don't have an exact ETA we can share at this point. Hope that helps!

**Comment by danielbecroft** [comment]
Okay thanks @lfittl-msft . I understand that the CLI hasn't been updated due to the functionality being in preview. Will the CLI be updated once the feature is GA, or is that still unknown?

**Comment by nachoalonsoportillo** [comment]
@yonzhan Since PostgreSQL Single Server is approaching retirement, this won't be implemented at this point. Please, close this issue.
