### ISSUE TITLE
azure-cli-core 2.4.0 reports error: ImportError: You need to install 'azure-cli-core' to load CLI credentials

### ISSUE THREAD

**Issue by yashodhan10** [Azure/azure-cli#13105]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version The latest 2.4.0 version did not work.

pn az --version I'm getting this output:
 az --version
azure-cli                         2.0.61 *

acr                                2.2.3 *
acs                               2.3.20 *
advisor                            2.0.0 *
ams                                0.4.3 *
appservice                        0.2.16 *
backup                             1.2.2 *
batch                              4.0.0 *
batchai                            0.4.8 *
billing                            0.2.1 *
botservice                         0.1.9 *
cdn                                0.2.1 *
cloud                              2.1.1
cognitiveservices                  0.2.5 *
command-modules-nspkg               2.0.2 *
configure                         2.0.20 *
consumption                        0.4.2 *
container                         0.3.15 *
core                              2.0.61 *
cosmosdb                           0.2.9 *
dla                                0.2.5 *
dls                                0.1.8 *
dms                                0.1.3 *
eventgrid                          0.2.2 *
eventhubs                          0.3.4 *
extension                          0.2.4 *
feedback                           2.1.4 *
find                               0.3.1 *
hdinsight                          0.3.2 *
interactive                        0.4.2 *
iot                                0.3.7 *
iotcentral                         0.1.6 *
keyvault                          2.2.13 *
kusto                              0.2.1 *
lab                                0.1.6 *
maps                               0.3.4 *
monitor                           0.2.11 *
network                            2.3.5 *
nspkg                              3.0.3 *
policyinsights                     0.1.2 *
profile                            2.1.4 *
rdbms                              0.3.9 *
redis                              0.4.2 *
relay                              0.1.4 *
reservations                       0.4.2 *
resource                          2.1.12 *
role                               2.4.3 *
search                             0.1.1 *
security                           0.1.1 *
servicebus                         0.3.4 *
servicefabric                     0.1.15 *
signalr                            1.0.0 *
sql                                2.2.0 *
sqlvm                              0.1.1 *
storage                            2.3.2 *
telemetry                          1.0.2 *
vm                                2.2.17 *

Python location '/usr/lib64/az/bin/python'
Extensions directory '/home/mstr1/.azure/cliextensions'

Python (Linux) 2.7.5 (default, Sep 26 2019, 13:23:47)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

Legal docs and information: aka.ms/AzureCliLegal

Error Message: ImportError: You need to install 'azure-cli-core' to load CLI credentials\

Packages. I'm installing 

msrestazure
azure-mgmt-resource
azure-mgmt-storage
azure-mgmt-network
azure-mgmt-dns
azure-mgmt-rdbms
azure-mgmt-compute
azure-mgmt-netapp==0.3.0
azure-cli-core
azure-core
azure-storage
azure-storage-file

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

OS: RedHat

**Additional context**

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
@yashodhan10 `azure-cli-core` and `azure-cli` versions must match. Please upgrade `azure-cli` to 2.4.0 as well. 

Actually you were using a very old version, all the command modules are now consolidated into a single azure-cli package, you only need to install azure-cli package now. You may need to clean up the old packages before you install the latest azure-cli.

**Comment by yashodhan10** [comment]
Thanks! It did work after upgrading the cli version to 2.4.0. I'm not sure if I missed it, but would be great to have this cli version as a prerequisite in the documentation.

**Comment by fengzhou-msft** [comment]
> Thanks! It did work after upgrading the cli version to 2.4.0. I'm not sure if I missed it, but would be great to have this cli version as a prerequisite in the documentation.

Yes. We will work on a doc to guide on upgrading from older packages.
