### ISSUE TITLE
az keyvault show doesn't work on ubuntu 20.04

### ISSUE THREAD

**Issue by JoranDox** [Azure/azure-cli#13101]
## Describe the bug

**Command Name**
`az keyvault secret show`

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault secret show --name {} --vault-name {} --output {} --query {}`

## Expected Behavior
getting the requested secret instead of an error
## Environment Summary
```
Linux-5.4.0-25-generic-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81 *

Extensions:
azure-devops 0.17.0

```

**Comment by JoranDox** [comment]
I reinstalled azure cli from the script instead of apt, and now it works, probably some issue with the older version still in apt.

az version now gives:
{
  "azure-cli": "2.4.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.4.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}

**Comment by abokov** [comment]
Ubuntu 20.04 - still have this issue with Azure Cli from apt-get - it does install old ones
{
  "azure-cli": "2.0.81",
  "azure-cli-core": "2.0.81",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "azure-devops": "0.17.0"
  }
}

Fix with  curl -L https://aka.ms/InstallAzureCli | bash ( from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest ) does help, after I got:
{
  "azure-cli": "2.5.1",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.5.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}

**Comment by JoranDox** [comment]
Good point, maybe I should keep this issue open until the version in the apt repositories is updated, thanks for the heads-up.

**Comment by yonzhan** [comment]
@bim-msft  please take a look

**Comment by bim-msft** [comment]
@fengzhou-msft Hi, seems `apt-get` will install an old version (2.0.81) of CLI, and this version maybe contains some bugs. Do you know how to push them to upload our latest package? Thanks.

**Comment by bim-msft** [comment]
Waiting for apt repositories to be updated. Move this issue into the backlog.

**Comment by yungezz** [comment]
hi @abokov there's issue in 2.0.81 which is in default repo of Ubuntu Focal release, detail pls see issue https://github.com/Azure/azure-cli/issues/14011. We have to wait for next main distro release to change CLI version in it. To resolve your issue, could  you pls uninstall 2.0.81 and install latest version of Azure CLI? thanks.

**Comment by fengzhou-msft** [comment]
Please follow https://github.com/Azure/azure-cli/issues/14011#issue-640943121 for the fix.

**Comment by jiasli** [comment]
This is bug in the unofficial Azure CLI delivered by Ubuntu's repo. Please see https://github.com/Azure/azure-cli/issues/19640 and install the official Azure CLI from Microsoft Linux Repo.
