### ISSUE TITLE
[ACS] Deleting an ACS instance only deletes the "logical" ACS resource

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1310]
Creating an ACS instance via `az acs create` generates all of the necessary Azure resources in order to support the cluster (e.g. load balancer, master/agent VMs), however, when you delete it via `az acs delete`, it only seems to remove the "logical" ACS resource, and none of its children that were created as a result of its corresponding create command.

Maybe this is expected behavior, but it seems non-ideal since ACS provides such a great higher-level abstraction on top of the underlying infrastructure, kind of like how deleting a k8s `Deployment` object will also delete the "underlying" `ReplicaSets`, `Pods`, etc. Using a resource group to manage this provides a reasonable work-around, so it definitely isn't a blocker, but I'd love to better understand the expected user scenarios that the `az acs delete` command is supporting. Thanks!

**Comment by mayurid** [comment]
@brendanburns to comment

**Comment by brendandburns** [comment]
Yeah, this is the current ACS behavior for all orchestrator types.  Its not ideal.  The trouble is right now you can deploy an ACS cluster into a resource group with other stuff in it, and we don't really track what we created, so it's tricky to know what to delete.  We will be improving the ACS API to do a better job here.

In the mean time, we could add a `--delete-parent-resource-group` flag that would also delete the resource group and help clean this up.

--brendan

**Comment by rjtsdl** [comment]
It should be soon resolved by latest ACS implementation.
logical ACS resource are not sitting together with other resources anymore. And az acs delete should remove the logical one and also the underlying resource. Try regions in this announcement. 

https://github.com/Azure/ACS/blob/master/announcements/2017-08-04_additional_regions.md

**Comment by mboersma** [comment]
This behavior is no longer the case--`az acs delete` removes all the expected resources. @mayurid @tjprescott we can close this issue.
