### ISSUE TITLE
Adding --enable-managed-identity true fails on create

### ISSUE THREAD

**Issue by dearsi-mocha** [Azure/azure-cli#13111]
## Describe the bug

**Command Name**
az apim create --name $name --publisher-email "by@bu.com" --publisher-name "bu" -g $resourceGroup **--enable-managed-identity true**
**Errors:**
```
'ApiManagementServiceResource' object does not support item assignment
Traceback (most recent call last):
Temp\pip-install-9101vebg\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 608, in execute
azure\cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 659, in _run_job
Local\Temp\pip-install-9101vebg\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 636, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 493, in default_command_handler
azure\cli\command_modules\apim\custom.py, ln 31, in create_apim
TypeError: 'ApiManagementServiceResource' object does not support item assignment
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim create --name {} --publisher-email {} --publisher-name {} -g {} --enable-managed-identity {} --no-wait`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6

azure-cli 2.2.0 *

Extensions:
application-insights 0.1.1

```

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look? thanks

**Comment by qwordy** [comment]
@kevinhillinger @jonlester Are you still the code owner of apim?

**Comment by kevinhillinger** [comment]
Looking into this.
