### ISSUE TITLE
copy from one storage to another takes much time

### ISSUE THREAD

**Issue by novaknole** [Azure/azure-cli#13113]
I have two storage accounts(`storage1`) and (`storage2`) and both of them have containers called `data`. 

Now, `storage1`'s `data` contains folder called `database-files` which contains lots of folders recursively. I mean it's kind of huge(so many files, sooo many files). 

What I am trying to do is I want to copy `database-files` and everything that's in it from `storage1`'s `data` container to `storage2`'s data container. **Note:** both storage accounts are in the same resource group and subscription.

Here is what I've tried:

`az storage blob copy start-batch --source-account-name "storage1" --source-container "data" --account-name "storage2" --destination-container "data"`

This worked fine, but The problem is time it takes is ridiculously big and I can't wait this much because I want to do this command for one of my release . Which means that i need this as soon as fast, so that my deployment happens fast.

Is there any way to make it faster? maybe `zip it/copy it/unzip` it? Even If I use `AzCopy` , I have no idea how it's gonna help with timing. All it helps is it doesn't have point of failure and Also I have no idea how to use it via `azure cli` .

What advice could you give me to proceed with? 

**Update:**  I tried using `azcopy` from my local machine's terminal. Looks like it's much, much, much faster. Turns out I have to stick with that. but the problem is I want to execute the command from azure-cli on release pipeline. On the release pipeline, I have `inline script` chosen and i use commands such as `call az storage` and so on. How can I use `azcopy` there? Any idea? 
I read somewhere that `azcopy` has been rewritten as `az storage file` but now I got no idea what `share` means and how do i copy directory from one storage's container to another storage's container where both storage are in the same subscription and resource. 

Thanks in advance.

**Comment by yonzhan** [comment]
add to S170

**Comment by Juliehzl** [comment]
@novaknole We have a new command named `az storage copy`, which has better performance when copy. You can have a try.

**Comment by Juliehzl** [comment]
close the issue given there is no response for several days.
