### ISSUE TITLE
Unable to deploy Logic App resource due to "'$schema' not found in JSON" issue

### ISSUE THREAD

**Issue by hpsan** [Azure/azure-cli#13125]
## Describe the bug
I'm unable to create a Logic App resource even after I literally used the "Export Template" option in the Logic App portal. I can see that there is a '$schema' in the template.json file that I'm trying to use for the deployment
```bash
(azuredev) [master ?] ~/Workspace/DevSentinel/Playbooks/Playbook5  $ head -n 3 template.json
{
"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
```
**Command Name**
`az deployment group create`

**Errors:**
```
Deployment failed. Correlation ID: df10f68f-54e1-438b-bb57-e69f49ca705d. {
  "error": {
    "code": "InvalidRequestContent",
    "message": "The request content is not valid and could not be deserialized: 'Required property '$schema' not found in JSON. Path 'properties.definition', line 1, position 69.'."
  }
}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az deployment group create -g RedactedRG1 --name Playbook5 --template-file template.json`

## Expected Behavior
I expected it to be successfully deployed since I had just literally downloaded the deployment template from the portal
## Environment Summary
```
Darwin-19.4.0-x86_64-i386-64bit
Python 3.7.5

azure-cli 2.2.0 *

```

**Comment by yonzhan** [comment]
add to S170

**Comment by cath123123** [comment]
Is this issue resolved? I am hitting the same "'$schema' not found in JSON" issue.

**Comment by hpsan** [comment]
It hasn't been resolved. I'm guessing it will be as a part of the S170 milestone

**Comment by zhoxing-ms** [comment]
@hpsan Hi, I can't reproduce this problem. Could you please send me the JSON file of template and parameters which you use by email?
My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by hpsan** [comment]
Hi Xing - Thanks for taking a look. Sent you an email with the template and parameters JSON files. Let me know if you need any additional information to debug.

**Comment by zhoxing-ms** [comment]
@hpsan Hi, I still can't reproduce your problem. Could you please add `--debug` to the command you executed and show me the printed information? 
If it involves private information, you can sent it to me by email~

**Comment by hpsan** [comment]
@zhoxing-ms I've sent you the printed information when I ran it with --debug via email. Thank you!

**Comment by zhoxing-ms** [comment]
In fact, this issue may be related to the deployment service of the workflows resource:
1. The template provided by customer can pass the verification with rest API [Deployments - Validate](https://docs.microsoft.com/en-us/rest/api/resources/deployments/validate)
2. When the template is deployed with rest API [Deployments - Create Or Update](https://docs.microsoft.com/en-us/rest/api/resources/deployments/createorupdate), the following error is reported:
> The request content is not valid and could not be deserialized: 'Required property '$schema' not found in JSON. Path 'properties.definition', line 1, position 69.'
3. Replace the resources of `Microsoft.Logic/workflows` in the ARM template with other resources, the template will be normally deployed. This shows that the format of the template is correct.

This issue requires the service team to see if there is a problem with the deployment service of resource `Microsoft.Logic/workflows`.
*Correlation ID: 5af650fb-d96c-49dc-ab9b-b9c25f023648.*

**Comment by hpsan** [comment]
I can no longer repro. Looks like the Azure Sentinel UI has reverted to an older schema that no longer has this issue
