### ISSUE TITLE
Azure UK South missing API version '2020-02-02-preview' for type 'Microsoft.Insights/components' - API version 2020-02-02-preview is not supported error

### ISSUE THREAD

**Issue by rohank-proarch** [Azure/azure-cli#13126]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Trying to get Application Insights Instrumentation Key using following command:

`az monitor app-insights component show --app $applicationInsightsName --resource-group $resourceGroupName --query "instrumentationKey" --output "tsv"`

**Error**
`No registered resource provider found for location 'uksouth' and API version '2020-02-02-preview' for type 'components'. The supported api-versions are '2014-04-01, 2014-08-01, 2014-12-01-preview, 2015-05-01, 2018-05-01-preview'. The supported locations are ', eastus, southcentralus, northeurope, westeurope, southeastasia, westus2, uksouth, canadacentral, centralindia, japaneast, australiaeast, koreacentral, francecentral, centralus, eastus2, eastasia, westus, southafricanorth, northcentralus, brazilsouth, switzerlandnorth, australiasoutheast'.`

**To Reproduce**

Login to Azure CLI using `az login`
`az monitor app-insights component show --app $applicationInsightsName --resource-group $resourceGroupName --query "instrumentationKey" --output "tsv"`

**Expected behavior**

Command should succeed and retrieve instrumentation key.

**Environment summary**

```
azure-cli                          2.3.1 *

command-modules-nspkg              2.0.3
core                               2.3.1 *
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-devops                      0.18.0
```

**Additional context**

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
We have reverted the version back. I will sync with service team and find out a solution for this issue later.
