### ISSUE TITLE
az role on azure-cli-role 2.6.3 and 2.6.4 fails with "NotImplementedError: APIVersion 2018-09-01-preview is not available"

### ISSUE THREAD

**Issue by Slowdive-Aideron** [Azure/azure-cli#13124]
## Describe the bug
so I'm trying to get the value of principalName from the az role assignment list command, which according to ms documentation, should be there .. but it isn't. So i installed latest pycli, because according to commit messages this was fixed with some version of azure-cli-role. But when i manually install azure-cli-role 2.6.3 or 2.6.4, it runs into this error. 

**Command Name**
`az role assignment list`

**Errors:**
```
APIVersion 2018-09-01-preview is not available
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 688, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.6/site-packages/six.py, ln 703, in reraise
    raise value
...
azure/cli/core/__init__.py, ln 574, in default_command_handler
    return op(**command_args)
cli/command_modules/role/custom.py, ln 164, in list_role_assignments
    assignments_client = factory.role_assignments
azure/mgmt/authorization/authorization_management_client.py, ln 183, in role_assignments
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2018-09-01-preview is not available
```

## To Reproduce:
just run az role assignment list --all with the azure-cli-role 2.6.3 or latest 2.6.4 

- _Put any pre-requisite steps here..._
- `az role assignment list`

## Expected Behavior
list of role assignments pertaining to my scope 
## Environment Summary
```
Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
Python 3.6.8
Installer: PIP

azure-cli                                 2.4.0
command-modules-nspkg    2.0.3
core                                        2.4.0
nspkg                                     3.0.4
role                                        2.6.3 *
telemetry                               1.0.4

```

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by arrownj** [comment]
Hi @Slowdive-Aideron , CLI has included all the modules now, we do not need to use `pip install azure-cli-role` separately. Actually both `2.6.3` and `2.6.4` of  `azure-cli-role` are very old version. There will be compatible problem with our latest CLI version (`2.4.0`).

So suggest you use a clean CLI 2.4.0 version, and run `az role assignment` commands again.

**Comment by arrownj** [comment]
Hi @Slowdive-Aideron , if no more problems, I will close this issue first. You can reopen it or submit a new one if you have other concerns. Thanks
