### ISSUE TITLE
Deprecation warning written to stderr using 'deployment group operation list' with az-cli 2.4.0

### ISSUE THREAD

**Issue by russcam** [Azure/azure-cli#13129]
The following deprecation warning is written to stderr when using az-cli 2.4.0 and the command

```sh
az deployment operation group list --name mainTemplate --resource-group "<rg>" --out json
```

> Error: This command is implicitly deprecated because command group 'deployment operation' is deprecated and will be removed in a future release. Use 'deployment operation sub' instead.

How would one list the operations for a resource group using `deployment operation sub`? It looks like it operates at the subscription scope, without an option to specify resource group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 503c72eb-48c4-19d0-d761-942df47ee19f
* Version Independent ID: be942ff9-79d1-8cb0-0046-9f284ad35321
* Content: [az deployment operation group](https://docs.microsoft.com/en-us/cli/azure/deployment/operation/group?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S170

**Comment by zhoxing-ms** [comment]
@russcam This problem is caused by the misuse of deprecate information, and command `az deployment operation group` will not be deprecated.
I have submitted a PR to fix this problem, thanks for your feedback~

**Comment by russcam** [comment]
thanks @zhoxing-ms
