### ISSUE TITLE
How to use when virtual network exists in a different resource group?

### ISSUE THREAD

**Issue by HermanCordes** [Azure/azure-cli#13131]
When using the `az storage account network-rule add` command, it's possible to specify the resource group name using the `--resource-group` argument. This argument however, seems to be used for discovering both the storage account and the virtual network. So both the storage account and the virtual network should exist in the same resource group. But how to use this command when that's not the case?

I've tried to specify the entire resourceId of the virtual network for the `--vnet-name` argument, but that doesn't seem to be valid solution. Maybe there's another way to add a network rule to the storage account? Maybe also good to extend the documentation on this page a bit to mention what the `--resource-group` argument refers to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac52f120-deaa-0a12-3663-8bf51cbbd234
* Version Independent ID: b7e2694c-c7be-8d1f-da00-fdd8b60f327e
* Content: [az storage account network-rule](https://docs.microsoft.com/en-us/cli/azure/storage/account/network-rule?view=azure-cli-latest#az-storage-account-network-rule-add)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S170

**Comment by Juliehzl** [comment]
Hi @HermanCordes, you can specify `--subnet` with resource id, which is in another resource group.

**Comment by HermanCordes** [comment]
Hi @Juliehzl, your suggestion is working!

That also means that the command was working all along right? It at least means that I misunderstood the documentation page. Would it maybe a good idea to provide an additional example specificying the case that the subnet resides in a different resource group?

And aside from that, I'd like to propose another clarification for the documentation page, because of `--subnet` argument cannot be used in conjunction with the `--vnet-name` when using the ID format for the subnet value.

Imagine this sample:
```
az storage account network-rule add \
  --subscription $subscriptionId \
  --resource-group $resourceGroup \
  --account-name $accountName \
  --vnet-name $virtualNetworkName \
  --subnet $subnetId
```

This statement will simply result in an error message:

> incorrect usage: [--subnet ID | --subnet NAME --vnet-name NAME]

While removing the `--vnet-name` proves to be the solution:
```
az storage account network-rule add \
  --subscription $subscriptionId \
  --resource-group $resourceGroup \
  --account-name $accountName \
  --subnet $subnetId
```

This however, isn't mentioned in the documentation page.

**Comment by Juliehzl** [comment]
> Hi @Juliehzl Zunli Hu FTE, your suggestion is working!
> 
> That also means that the command was working all along right? It at least means that I misunderstood the documentation page. Would it maybe a good idea to provide an additional example specificying the case that the subnet resides in a different resource group?
> 
> And aside from that, I'd like to propose another clarification for the documentation page, because of `--subnet` argument cannot be used in conjunction with the `--vnet-name` when using the ID format for the subnet value.
> 
> Imagine this sample:
> 
> ```
> az storage account network-rule add \
>   --subscription $subscriptionId \
>   --resource-group $resourceGroup \
>   --account-name $accountName \
>   --vnet-name $virtualNetworkName \
>   --subnet $subnetId
> ```
> 
> This statement will simply result in an error message:
> 
> > incorrect usage: [--subnet ID | --subnet NAME --vnet-name NAME]
> 
> While removing the `--vnet-name` proves to be the solution:
> 
> ```
> az storage account network-rule add \
>   --subscription $subscriptionId \
>   --resource-group $resourceGroup \
>   --account-name $accountName \
>   --subnet $subnetId
> ```
> 
> This however, isn't mentioned that clearly on the documentation page. Currently the following is mentioned:
> 
> > --subnet
> > Name or ID of subnet. If name is supplied, --vnet-name must be supplied.
> 
> Maybe good to mention here that `--vnet-name` should _only_ supplied in case of ID, but shouldn't be supplied when using the subnet name. Just to be absolutely clear of the usage.

add one example for subnet id usage.
