### ISSUE TITLE
TCP and UDP port exposure

### ISSUE THREAD

**Issue by kmo-dev** [Azure/azure-cli#13143]
Hi there,
I can't see how I can configure TCP and UDP port at the same time. I have two different ports for my single container, but how can I configure both ports at the same time? I'v already found an issue from 2018 at stackoverflow and hopefully it's fixed already. I'm a bit shocked, if this isn't supported yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5d1da7-7c4f-c9e6-e4b9-a30407675acf
* Version Independent ID: ba32e12d-8283-f980-e1d0-1ca2a75a5152
* Content: [az container](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/container/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/container/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
container

**Comment by yungezz** [comment]
question

**Comment by navba-MSFT** [comment]
@kmo-dev Apologies for the late reply. I am able to create an ACI via portal and add both TCP and UDP ports. Also while running the _az container show_ command I am able to see the setting just fine. 
```
"ports": [
      {
        "port": 80,
        "protocol": "TCP"
      },
      {
        "port": 8080,
        "protocol": "UDP"
      }
```
This issue is open for quite sometime now. Please let me know if you need any further assistance on this. Awaiting your reply.

**Comment by kmo-dev** [comment]
hi, I can confirm that. this feature is now available. case closed. thanks to all ♥

**Comment by emepetres** [comment]
Sorry for the late question: THis is still not possible from azure cli right?

**Comment by JoeMarkov** [comment]
I also have this problem! I want to deploy Jaeger tracing that requires 7 TCP and UDP ports using az container create, but it seems I can't specify that.

https://www.jaegertracing.io/docs/1.22/getting-started/
