### ISSUE TITLE
Add `--os-disk-size-gb` in `az vmss create`

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#13148]
**Is your feature request related to a problem? Please describe.**

Please add `--os-disk-size-gb` in `az vmss create`
Example: azure-rest-api-specs\specification\compute\resource-manager\Microsoft.Compute\stable\2019-07-01\examples\CreateAScaleSetWithEmptyDataDisksOnEachVm.json

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yungezz** [comment]
create on behalf of service team

**Comment by basnijholt** [comment]
Anyone looking how to change the OS disk size *after* creation.

Create `patch-disk.json`
```
{
  "properties": {
    "virtualMachineProfile": {
      "storageProfile": {
        "osDisk": {
          "diskSizeGB": 128,
        }
      }
    }
  }
}
```
and run
```
az rest -m patch --header "Accept=application/json" -u "https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.Compute/virtualMachineScaleSets/${VMSS_NAME}?api-version=2019-12-01" --body @patch-disk.json
```

**Comment by qwordy** [comment]
Are you asking how to change the OK disk size after creation? Can your command work?

**Comment by basnijholt** [comment]
I just posted it because it took me a very long time to figure out how to do it. And yes command works 😄

**Comment by qwordy** [comment]
Thank you for sharing. You can also try `az vmss update --set property=value`.
