### ISSUE TITLE
az account list-locations fails

### ISSUE THREAD

**Issue by dkozinn** [Azure/azure-cli#13144]
## Describe the bug

**Command Name**
`az account list-locations`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account list-locations`

## Expected Behavior
Expected valid output

## Environment Summary
```
Linux-4.15.0-1075-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

Extensions:
interactive 0.4.3

```

**Comment by yonzhan** [comment]
@arrownj  please take a look

**Comment by arrownj** [comment]
Similar to [#11749 (comment)](https://github.com/Azure/azure-cli/issues/11749#issuecomment-570975762)

400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token is a known issue of Cloud Shell that it intermittently fails with this error.

To solve it, please use Azure CLI on a local machine or run az login in Cloud Shell and retry the command.

**Comment by dkozinn** [comment]
I can confirm that using **az login** in the cloud shell works. It seems like I only had to do that once, after closing the cloud shell and starting a new one the command worked without another az login.

**Comment by arrownj** [comment]
@dkozinn , yes, glad to here that it works. Let us know if you have other problems. Thanks

**Comment by arrownj** [comment]
Close this issue first. Cloud shell issue will be traced in #11749
