### ISSUE TITLE
Error while assigning policy set definition using cli. 

### ISSUE THREAD

**Issue by divyamoorthyTR** [Azure/azure-cli#13149]
**Resource Provider**

**Description of Feature or Work Requested**

**Minimum API Version Required**

**Swagger Link**

**Target Date**

**Comment by yonzhan** [comment]
add to S170

**Comment by zhoxing-ms** [comment]
@divyamoorthyTR The information of this issue is not complete, it seems to be the issue of #13150. I will close it first, if you have any other questions, please reopen it or open a new issue~
