### ISSUE TITLE
az version --query "azure-cli" should return version number and not throw error

### ISSUE THREAD

**Issue by silentbobbert** [Azure/azure-cli#13152]
## Describe the bug

When I run ```az version --query "azure-cli"``` it should return the version number: ```"2.4.0"```

**Command Name**
`az version`

**Errors:**
```
az version: error: argument --query: invalid jmespath_type value: "azure-cli"'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az version --query "azure-cli"`

## Expected Behavior

According to the tutorial pages you suggest people use to learn about [JMESPath](https://jmespath.org/tutorial.html), it should work like this:

![image](https://user-images.githubusercontent.com/3257988/80186315-b8b43e00-8605-11ea-8950-8e00aaf5aed5.png)

I copied the output from a plain `az version` execution, and selected the field I wanted manually in the online tool.

I would expect `az version --query "azure-cli"` to perform the same logical function and return `2.4.0`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.4.0

```

**Comment by yonzhan** [comment]
add to S170

**Comment by jiasli** [comment]
This is the design of JMESPath that `-` is parsed as minus. See https://github.com/jmespath/jmespath.py/issues/109#issuecomment-240315651. 

So in the query `azure-cli` needs to be quoted as `"azure-cli"` as you did in the screenshot:

![image](https://user-images.githubusercontent.com/3257988/80186315-b8b43e00-8605-11ea-8950-8e00aaf5aed5.png)

**However, since the terminal interprets double quotes, the command needs to be escaped.**

In Windows CMD:

 ```cmd
>az version --query "\"azure-cli\""
"2.4.0"
```

In Windows PowerShell (Actually `\` shouldn't be necessary, but we need them here due to https://github.com/PowerShell/PowerShell/issues/1995): 

```pwsh
> az version --query '\"azure-cli\"'
"2.4.0"
> az version --query "\`"azure-cli\`""
"2.4.0"
```

In Bash:

```sh
$ az version --query "\"azure-cli\""
"2.4.0"
$ az version --query '"azure-cli"'
"2.4.0"
```

**Comment by silentbobbert** [comment]
Thanks for helping me out! I guess there is still a discrepancy between the query parameter you can use in the online tutorial tool - where you dont have to escape anything, and the parameter you must pass to the az version command. One has to be escaped and the other does not. Its not clear from the error messages, or the tutorial page what the user should do to correct their query parameter. Perhaps the help page for --query should not point to that tutorial page, which is generic - it should point to a Microsoft help page which would explain the --query parameter should be escaped, but could also point to the tutorial page for further reading.

**Comment by jiasli** [comment]
Thanks for the suggestion. 

The quoting issue is not only limited to `--query`, but to all parameters, like passing in a JSON string. We do have a doc to describe general quoting issues: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues

We are investigating about how to make it more obvious to the users.

**Comment by jiasli** [comment]
@silentbobbert, I added some new contents in the doc. Maybe you are interested: https://github.com/Azure/azure-cli/pull/13249/files#diff-2f68bb7d55730e192dc93f133467a721R162-R175
