### ISSUE TITLE
Issue when running az cosmosdb mongodb database delete command

### ISSUE THREAD

**Issue by stephenb-kainos** [Azure/azure-cli#13156]
Running command as per 
az cosmosdb mongodb database delete --account-name $COSMOSACCOUNT --resource-group $RG_NAME --name $DB_NAME --subscription $SUBSCRIPTION --yes

Getting error
Operation failed with status: 'Unauthorized'. Details: Required Header authorization is missing. Ensure a valid Authorization token is passed.

az cli is being run with a user that just listed the cosmos databases under that storage account and has permission to delete and default subscription for that user has also been set to the right one of this cosmos isntance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3a7368e-b170-2192-ad7f-2f09f92150d3
* Version Independent ID: 96d3f671-b8ea-bec3-608d-ea1d78ab356c
* Content: [az cosmosdb mongodb database](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/mongodb/database?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cosmosdb

**Comment by shurd** [comment]
Hi @stephenb-kainos it is difficult to debug this problem without any detailed information. Collection and Database names are case sensitive, so please ensure those match the casings they were created with. If the error continues, please open a support ticket via the Azure portal and share subscription id/account name/database name/collection name so that we can help investigate.

**Comment by shurd** [comment]
Closing this issue now. If you still encounter the error, please open a support ticket or open a new issue with more information.
