### ISSUE TITLE
--sa-lifetime and --sa-max-size in example

### ISSUE THREAD

**Issue by mobileha** [Azure/azure-cli#13157]
Please fix the --sa-lifetime and --sa-max-size to larger values in example (default 27000 and 102400000 are good values)
If users just copy these values from example, this will lead to very frequent unneeded rekeys, and this can significantly impact performance.
--sa-max-size 1024
is just a 1 megabyte, which will lead to rekey 10 times a second with 100mbit/s speed.
--sa-lifetime 600
rekeys every 9-10 minutes. Also good to raise the value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bccfe9-5e94-430b-3002-ade01e60afde
* Version Independent ID: a2784876-679c-cd4e-61ae-b793759ceb2b
* Content: [az network vpn-connection ipsec-policy](https://docs.microsoft.com/en-us/cli/azure/network/vpn-connection/ipsec-policy?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
@jsntcy  Could you please take a look?
