### ISSUE TITLE
Error while assigning policy set definition using cli. ResourceIdentityRequired - The policy assignment 'RGTag-v1.1' request is invalid. Policy assignments must include a resource identity when assigning 'Modify' policy definitions.

### ISSUE THREAD

**Issue by divyamoorthyTR** [Azure/azure-cli#13150]
I am getting the following error when I try to perform a policy assignment of policy set definition.
ResourceIdentityRequired - The policy assignment 'RGTag-v1.1' request is invalid. Policy assignments must include a resource identity when assigning 'Modify' policy definitions.

The command is 

az policy assignment create --policy-set-definition "<Policy definitionid>" --display-name RGTag-v1.1 --name RGTag-v1.1 --scope /providers/Microsoft.Management/managementgroups/<mgname>

**Comment by yonzhan** [comment]
add to S170

**Comment by divyamoorthyTR** [comment]
Any updates?

**Comment by zhoxing-ms** [comment]
Hi @divyamoorthyTR, here is a similar issue, maybe we can refer to it:  https://github.com/terraform-providers/terraform-provider-azurerm/issues/4950
Could you please try adding `--assign-identity` append to the command and see if it can solve the problem?

By the way, could you please send me your specific policy information by email? My email address is Zhou.Xing@microsoft.com.

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
