### ISSUE TITLE
az keyvault secret show unrecognized arguments

### ISSUE THREAD

**Issue by josiahlaivins** [Azure/azure-cli#13167]
## Describe the bug

**Command Name**
`az keyvault secret show -–name some-dash-delimited-secret-name –-vault-name somename`

**Errors:**
```
az: error: unrecognized arguments: -–name some-dash-delimited-secret-name –-vault-name somevaultname
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._

## Expected Behavior
I expect this command to return a secret value. 

I have also tried without dashes in the name argument. I logged in with my azure account which has access to the keyvault directly through the portal.

## Environment Summary
```
Linux-5.3.0-26-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0

Extensions:
azure-iot 0.9.1

```

**Comment by yonzhan** [comment]
@bim-msft  please take a look

**Comment by bim-msft** [comment]
@josiahlaivins Hi, seems this is not a familiar case and it should not happened, I was not able to reproduce this:

![image](https://user-images.githubusercontent.com/3250203/82419657-496d2500-9ab1-11ea-9cb5-89b5bdedb5af.png)

I'm using `azure-cli 2.5.1`, maybe you can upgrade your package and retry it again, thanks!
Anyway, feel free to let me know if this workaround cannot resolve the issue.

**Comment by bim-msft** [comment]
Closing it due to longtime inactivity, feel free to reopen it anytime if you need additional help.

**Comment by josiahlaivins** [comment]
I have been using az version 2.9~ and am having these issues again. I downgraded to your version and it still doesnt work.

```bash
cli.azure.cli.core.parser : az: error: unrecognized arguments: -–name pipelines-artifact-token –-vault-name svikv -–query value
az: error: unrecognized arguments: -–name some-token –-vault-name somevault -–query value
usage: az [-h] [--verbose] [--debug] [--only-show-errors]
          [--output {json,jsonc,yaml,yamlc,table,tsv,none}] [--query JMESPATH]
          {keyvault} ...
recommendation_provider: version: 2.5.1, command: keyvault secret show, parameters: ['-–', '-–'], extension: None
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f9d3b84ee18>]
az_command_data_logger : exit code: 2
telemetry.save : Save telemetry record of length 2692 in cache
telemetry.check : Negative: The /home/josiah/.azure/telemetry.txt was modified at 2020-07-22 03:28:03.580166, which in less than 600.000000 s
command ran in 0.254 seconds.

```

**Comment by bim-msft** [comment]
Hi @josiahlaivins this is really weird, could you please paste the result of `az --version`?

**Comment by josiahlaivins** [comment]
```bash
az --version
azure-cli                         2.10.1

command-modules-nspkg              2.0.3
core                              2.10.1
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-iot                          0.9.7

Python location '/opt/az/bin/python3'
Extensions directory '/home/josiah/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Aug  6 2020, 08:50:46) 
[GCC 9.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```
The key-vault is working right now, so it is difficult to know what changed. I basically had to wait for a few hours then the key vault was working.

**Comment by bim-msft** [comment]
@josiahlaivins I think I figured it out: the dash in your command `az keyvault secret show -–name some-token –-vault-name somevault -–query value` is incorrect.

`-–name`: you have 2 different chars.

`-`:
![image](https://user-images.githubusercontent.com/3250203/90003429-a9492580-dcc6-11ea-84e9-4418d2b567e0.png)

`–`:
![image](https://user-images.githubusercontent.com/3250203/90003470-b6661480-dcc6-11ea-82a7-9a507b84c7c8.png)

**Comment by josiahlaivins** [comment]
I think this makes sense. I'm usually copy/paste from a readme. I will verify on my end.
*edit:
I was able to replicate. Thanks! I think this solved the problem. Not sure how this happened on my end. Deleting the dashes and re entering them fixes it

**Comment by bim-msft** [comment]
Great! This is a super rare case and it's difficult to check with human eyes, we will consider refining the error message for such cases.
