### ISSUE TITLE
Unable to grep the filename and password from az back restore file output

### ISSUE THREAD

**Issue by ahamedn** [Azure/azure-cli#13168]
I'm trying to automate Azure backup restore using the Azure CLI. But I'm not able to assign the output as variable and also not able to filter out the file name and password inside the script. 

This is my code 
`az backup restore files mount-rp --resource-group ***-eastus2 --vault-name ***-eastus2 --container-name ***-eastus2-001 --item-name ***-eastus2-001 --rp-name ****`

Let me know if I'm doing anything wrong. 

**Description of Feature or Work Requested**

**Minimum API Version Required**

**Swagger Link**

**Target Date**

**Comment by yonzhan** [comment]
backup

**Comment by pvrk** [comment]
@ahamedn : Sorry for the delay in response. At present, may I know more on how are you planning to automate? Honestly speaking, the way the feature is built is not exactly suited for automation. The command initiates a download of a script into the downloads folder. And the script name varies with VM name and the selected RP and hence may or may not follow a pattern.  And then one needs to provide a password to run the script. So, interested to know how were planning to automate.

**Comment by ahamedn** [comment]
@pvrk thanks for the response. I found a workaround and automated it through bash script. We have prod application in azure and dev application in on-prem server. I created the script to restore the prod data to on prem using this method.

**Comment by maxleonalbrecht** [comment]
I have the same problem.
