### ISSUE TITLE
az network express-route list-route-tables does not output as table or tsv

### ISSUE THREAD

**Issue by nichols-356** [Azure/azure-cli#13162]
## Describe the bug
Output of express-route circuit route-tables fails when formatting as table or tsv

**Command Name**
`az network express-route list-route-tables`

**Errors:**
no errors are returned

## To Reproduce:
- have an express-route circuit with peering to a 3rd party
- `az network express-route list-route-tables -n {} -g {} --path {} --peering-name {} -o {table|tsv}`
* If you format output as a `table`, there is an empty line returned before the command exists successfully.
* If you format output as `tsv`, you get "none" followed by the count of routes in your table (the "none" part may be different based on your setup, more on that below)

## Expected Behavior
the route-tables for the selected express-route circuit path and peering is returned in a human readable format

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.2

azure-cli 2.2.0 *

```
## Additional Context
this is due to the fact that the JSON output is structured slightly different from other az cli commands. for example `az network express-route list` returns JSON in the format of `[{data0},{data1},{data2}]`, where as `az network express-route list-route-tables` returns JSON in the format of `{"nextLink":null,"value":[{data0},{data1},{data2}]}`. For all my express-route circuit peerings, "nextLink" is never anything except for null, so i am not entirely sure of its purpose. i can fathom that it might be if your route table is too large for a single api call, however, i would expect in the event all data can be returned in a single api call, "nextLink" would simply not be included. it is entirely possible that this is intended, not a bug at all, so please enlighten me.

having said all that, there is an easy workaround. add `--query "value[]"` to your command and it'll output as expected.

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
@haroldrandom  Could you please take a look?
