### ISSUE TITLE
Creating cluster

### ISSUE THREAD

**Issue by madhavsandireddi** [Azure/azure-cli#13169]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
Resource group 'myaksrgrg' could not be found.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --enable-addons {} --generate-ssh-keys`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

```

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
The error is reporting the correct response, please validate you are using the correct subscription and the RG exists to be deployed into.

**Comment by Jen7714** [comment]
As Justin mentioned above, please validate, and let us know if you're still running into issues.
