### ISSUE TITLE
az keyvault secret list returns null for contentType since 2.3 & 2.4

### ISSUE THREAD

**Issue by diepes** [Azure/azure-cli#13166]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

for azure-cli 2.20  ,  az keyvault secret list --vault-name $AKVNAME
returns json output where contentType has string values. 
e.g. "contentType": "application/x-pkcs12"
or   "contentType": "application/x-pem-file",

for azure-cli 2.3 and 2.4 az keyvault secret list --vault-name $AKVNAME
returns null for "contentType" for all keys.
"contentType": null,

**To Reproduce**

use azure-cli 2.3 or 2.4 to retrieve secrets from keyvault that contains certificates.

**Expected behavior**

i expect the "contentType" not to be null for 2.3, 2.4 but retrun the same values 2.2 returns.

**Environment summary**

multiple,  laptop(Linux)   docker mcr.microsoft.com/azure-cli,   azure worker node.

**Additional context**

detected after i upgraded from older az to 2.4.0.,   2.3 did not fix it , but 2.2. seem to work fine.

**Comment by yonzhan** [comment]
@bim-msft  please take a look

**Comment by bim-msft** [comment]
@diepes Hi, this is by design, not a bug. We planned to no longer display managed keys and secrets to keep consistent with Azure Portal: https://github.com/Azure/azure-cli/pull/12679
Please feel free to let me know if you have any other concern.

**Comment by diepes** [comment]
@bin-msft thanks for the info/update.

Ok so if i understand correctly if we add a certificate, for consistency it will show under 
$ az keyvault certificate list --vault-name $AKVNAME

but then
$ az keyvault certificate download --name $certName --vault-name $AKVNAME --file test-cert.pem
>> Give's you only the main cert, not full chain or secret.


For other's running into this you can still download all the certificates and secret with 
$ az keyvault secret download --name $certName --vault-name $AKVNAME --file test-cert+ca+pvt.pem

even though the $certName does not show under secret list, you can retrieve it.
$ az keyvault secret list --vault-name $AKVNAME --file $filename
$ cat $filename | grep '\-----'
-----BEGIN PRIVATE KEY-----
-----END PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----

Thanks.

**Comment by bim-msft** [comment]
@diepes Hi, I'd like to show my case to better demo this change, here I have a certificate named `bimcert1111`:
![image](https://user-images.githubusercontent.com/3250203/82418066-175ac380-9aaf-11ea-93c4-b1c58df7ed43.png)

I can use `show` command to see the detail of its auto-generated secret/key with content type `application/x-pkcs12` or `application/x-pem-file` (which we call it `managed secrets/keys`):
![image](https://user-images.githubusercontent.com/3250203/82418153-35c0bf00-9aaf-11ea-83d7-12c5db1c9205.png)
Downloading this secret is also allowed.

But I cannot use `list` command to display it, the result of `list` only includes manually created secrets/keys (generally manually created secrets and keys don't have content type, show as `null`):
![image](https://user-images.githubusercontent.com/3250203/82418248-5852d800-9aaf-11ea-8b2e-aa247dd71d3a.png)
![image](https://user-images.githubusercontent.com/3250203/82419091-7a992580-9ab0-11ea-8c4f-2ced6ac90649.png)

I'm not sure if this clarification can solve your concern. If anything confusing, feel free to reply, thanks!

**Comment by bim-msft** [comment]
Closing it due to longtime inactivity, feel free to reopen it anytime if you need additional help.
