### ISSUE TITLE
Not all log alert rules are being returned

### ISSUE THREAD

**Issue by niswitze** [Azure/azure-cli#13161]
## Describe the bug
When querying for log alert rules using the command below I only receive log alert rules created for Log Analytics resource and not for Application Insights.

**Command Name**
az resource list --namespace Microsoft.Insights -g "groupName" --resource-type scheduledqueryrules

**Errors:**
Only Log Alert rules for log analytics workspaces show. No Application Insights Log Alert rules are returned.

## To Reproduce:
1. Create Log Alert rule for a log analytics workspace
2. Create Log Alert rule for an application insights in the same resource group as step 1
3. Run the command above and only the log alert rule for the log analytics workspace will be returned.

## Expected Behavior
All log alert rules, for both application insights and  log analytics workspaces, should be returned.
## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.4.0

Extensions:
alertsmanagement 0.1.0
azure-devops 0.17.0
interactive 0.4.1

```

**Comment by yonzhan** [comment]
add to S170

**Comment by niswitze** [comment]
Closing issue. Completely missed that I had a default location set for the cli. After removing the default location configuration this query pulled back both Application Insights and Log Analytics based log alerts.
