### ISSUE TITLE
aks issue

### ISSUE THREAD

**Issue by venkat1211** [Azure/azure-cli#13171]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
An RSA key file or key value must be supplied to SSH Key Value. You can use --generate-ssh-keys to let CLI generate one for you
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --kubernetes-version {} --location {} --node-vm-size {} --load-balancer-sku {} --api-server-authorized-ip-ranges {} --node-count {} --node-osdisk-size {}`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

```

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by jluk** [comment]
The error message is accurate, you need an ssh key to exist on create to exist. As mentioned in the error you can pass a flag to have one generated on your behalf.

**Comment by Jen7714** [comment]
Closing this for now as the question was answered above.
