### ISSUE TITLE
Can't create backend pool type url-path-map rule of Application Gateway when url-path-map default target type is redirection and it has some redirect type rules.

### ISSUE THREAD

**Issue by kuniteru** [Azure/azure-cli#13189]
## Describe the bug

**Command Name**
`az network application-gateway url-path-map rule create`

**Errors:**
```
Path Rule /subscriptions/922c51d0-4e66-4056-aa86-5a8d5b1e9412/resourceGroups/test001-rg/providers/Microsoft.Network/applicationGateways/demo-appgw2/urlPathMaps/demo-appgw2-urlpathmap/pathRules/demo-appgw2-web004-urlpathmapRule cannot reference a BackendAddressPool when Redirect Setting is specified.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- pre-requisite steps
    - Create url-path-map it default target type is "redirect" and it has some redirect type rules.
        - `az network application-gateway url-path-map create -g $rgName --gateway-name $appgwName -n $urlPathMapName --default-redirect-config $redirectConfName1 --rule-name $urlpathmapRuleName1 --paths "/dir1*" "/dir2*" --redirect-config $redirectConfName1`
        - `az network application-gateway url-path-map rule create -g $rgName --gateway-name $appgwName -n $urlPathMapRuleName2 --path-map-name $pathMapName --paths "/dir3*" "/dir4*" --redirect-config $redirectConfName2`
- `az network application-gateway url-path-map rule create -g $rgName --gateway-name $appgwName -n $urlPathMapRuleName3 --path-map-name $pathMapName --paths "/dir5*" "/dir6*" --address-pool $addressPoolName --http-settings $httpSettingsName`

I checked --debug output, in one pathRule "backendAddressPool", "backendHttpSettings" and "redirectConfiguration" were included.

## Expected Behavior
Create backend pool type url-path-map rule.

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0

Extensions:
application-insights 0.1.6
interactive 0.4.3

```

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
@kuniteru Sorry for the delay due to low bandwidth. I checked the logic in detail. If you set `--default-redirect-config $redirectConfName1` in url path map, it will be applied to each rule. In your case, I think you can remove `default-redirect-config`.

**Comment by kuniteru** [comment]
@MyronFanQiu Thank you for your suggestion.

As you said, I tried.
I created url-path-map with redirect type rule without --default-redirect-config.
And after that I tried to create path base type rule, then I got same error.

I ran it in the following order.

1. az network application-gateway url-path-map create \
    -g $rg \
    --gateway-name $appgwName \
    -n ${appgwName}-urlpathmap \
    --rule-name ${appgwName}-web001-urlpathmapRule \
    --paths "/web1*" "/web2*" \
    --redirect-config ${appgwName}-web001-redirectConf

1. az network application-gateway url-path-map rule create \
    -g $rg \
    --gateway-name $appgwName \
    -n ${appgwName}-web002-urlpathmapRule \
    --path-map-name ${appgwName}-urlpathmap \
    --paths "/weba*" "/webb*" \
    --redirect-config ${appgwName}-web001-redirectConf

1. az network application-gateway url-path-map rule create \
    -g $rg \
    --gateway-name $appgwName \
    -n ${appgwName}-web003-urlpathmapRule \
    --path-map-name ${appgwName}-urlpathmap \
    --paths "/web3*" \
    --address-pool ${appgwName}-addresspool02 \
    --http-settings ${appgwName}-httpsettings

I got the following error when I executed the aforementioned 3.
"Path Rule /subscriptions/*******-****-****-****-***********/resourceGroups/test001-rg/providers/Microsoft.Network/applicationGateways/demo-appgw2/urlPathMaps/demo-appgw2-urlpathmap/pathRules/demo-appgw2-web003-urlpathmapRule cannot reference a BackendAddressPool when Redirect Setting is specified."

I think the problem is when I try to add a "path base" type rule to a path map that has a "redirect type" rules by Azure CLI.
Incidentally, in Azure Portal, I can add a path base rule to a path map that has a redirect type rules.

**Comment by MyronFanQiu** [comment]
@kuniteru Hi. You're correct. After double checking the code logic, if `--redirect-config` is set for `az network application-gateway url-path-map create`, it would be used to set `--default-redirect-config`. To unblock you quickly, you can create an empty url-path-map and add rules through `az network application-gateway url-path-map rule` commands. But I agree that it's not convenient to use. I would revisit the usage flow and change the command behavior. Thanks for your suggestion.

**Comment by kuniteru** [comment]
@MyronFanQiu Thank you for understanding this issue.
I hope that this issue will improve.
