### ISSUE TITLE
How can I create network profile from Azure CLI other than use "az container create"

### ISSUE THREAD

**Issue by clement128** [Azure/azure-cli#13191]
hey there, I would like to create a network profile with my prefer name and before create any container group. is there any way to do it?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1651f497-06fd-d00c-0b0c-1b4a51f90f9d
* Version Independent ID: 57fa7b63-4563-2ad2-4dc4-621f7295cd20
* Content: [az network profile](https://docs.microsoft.com/en-us/cli/azure/network/profile?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
Hello. Looks like we cannot do it right now. I would invite container instance team to answer this question.
```
    az network profile : Manage network profiles.
        To create a network profile, see the create command for the relevant resource. Currently,
        only Azure Container Instances are supported.
```

**Comment by gtonello** [comment]
Hey @clement128, I just found a **workaround** to deal with it.
In my case, I've creating a new container with a network that doesn't exists yet.
```
az container create \
  --name appcontainer \
  --resource-group myRosourceGroup \
  --image mcr.microsoft.com/azuredocs/aci-helloworld \
  --vnet ny-vnet \
  --vnet-address-prefix 10.0.0.0/16 \
  --subnet my-subnet \
  --subnet-address-prefix 10.0.0.0/24
```
When finished, the output will give you the `networkProfile ID`.
The container instance is not necessary anymore, and you can delete it if you want.

I believe that there's an easy way to do that without the process to create a new virtual network.

**Comment by clement128** [comment]
@gtonello  good solution, thanks !!

**Comment by mloskot** [comment]
@gtonello
> Hey @clement128, I just found a **workaround** to deal with it.
> In my case, I've creating a new container with a network that doesn't exists yet.

Unfortunately, with `azure-cli 2.12.1` this workaround is no longer successful, see https://github.com/Azure/azure-cli/issues/15391

**Comment by mloskot** [comment]
I have found an alternative to `az container create`, using Azure REST based on https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networkprofiles/createorupdate

```powershell
$AsSubId="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXXXX"
$AzRG="my-rg"
$AzVN="my-vnet"
$AzSN="my-snet"

$uri = "https://management.azure.com/subscriptions/$AsSubId/resourceGroups/$AzRG/providers/Microsoft.Network/networkProfiles/networkProfile1?api-version=2020-05-01"

$body = @{
  "location"="uksouth"
  "properties"=@{
    "containerNetworkInterfaceConfigurations"=@(
      @{
        "name"="eth1"
        "properties"=@{
          "ipConfigurations"=@(
            @{
              "name"="ipconfig1"
              "properties"=@{
                "subnet"=@{
                  "id"="/subscriptions/$AsSubId/resourceGroups/$AzRG/providers/Microsoft.Network/virtualNetworks/$AzVN/subnets/$AzSN"
                }
              }
            }
          )
        }
      }
    )
  }
}
$body=$body | ConvertTo-Json -Depth 8

$token=(az account get-access-token | ConvertFrom-Json)
$headers = @{
  "Authorization" = ("{0} {1}" -f $token.tokenType, $token.accessToken)
}

Invoke-RestMethod -Uri $uri -Method Put -Headers $headers -Body $body -ContentType "application/json"
```

Obviously, the same can be achieved using `cURL` or https://httpie.org

**Comment by binn** [comment]
> I have found an alternative to `az container create`, using Azure REST based on https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networkprofiles/createorupdate
> 
> ```powershell
> $AsSubId="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXXXX"
> $AzRG="my-rg"
> $AzVN="my-vnet"
> $AzSN="my-snet"
> 
> $uri = "https://management.azure.com/subscriptions/$AsSubId/resourceGroups/$AzRG/providers/Microsoft.Network/networkProfiles/networkProfile1?api-version=2020-05-01"
> 
> $body = @{
>   "location"="uksouth"
>   "properties"=@{
>     "containerNetworkInterfaceConfigurations"=@(
>       @{
>         "name"="eth1"
>         "properties"=@{
>           "ipConfigurations"=@(
>             @{
>               "name"="ipconfig1"
>               "properties"=@{
>                 "subnet"=@{
>                   "id"="/subscriptions/$AsSubId/resourceGroups/$AzRG/providers/Microsoft.Network/virtualNetworks/$AzVN/subnets/$AzSN"
>                 }
>               }
>             }
>           )
>         }
>       }
>     )
>   }
> }
> $body=$body | ConvertTo-Json -Depth 8
> 
> $token=(az account get-access-token | ConvertFrom-Json)
> $headers = @{
>   "Authorization" = ("{0} {1}" -f $token.tokenType, $token.accessToken)
> }
> 
> $r=Invoke-RestMethod -Uri $uri -Method Put -Headers $headers -Body $body -ContentType "application/json"
> $r | ConvertTo-Json -Depth 8
> ```
> 
> Obviously, the same can be achieved using `cURL` or https://httpie.org

This is the only valid solution for me. I am unable to use az container create to create a network profile, as every time I create a container with an existing or new virtual network, it will not create a network profile (I'm not sure how this works, but it does); and I'm looking to deploy automatically using C#'s Fluent SDK.

I resorted to using this request manually if a network profile didn't already exist in the target VNet, it's not too hard to implement. Azure should allow the automatic creation of network profiles from the Fluent SDK & from the CLI/other SDK tools. 

I also noticed that some users recently have been getting a blank output from `az network profile list` even after using `az container create` like me. Hoping that gets resolved on the Azure end too. There are far too many reasons to have a container in a virtual network, and far too many reasons to have the ability to have a static outbound IP e.g. a worker that batch processes a heavy file and uploads it to a service under a certain IP due to their IP rules.

**Comment by navba-MSFT** [comment]
@clement128 Apologies for the late reply. Could you let us know if you need any further assistance on this issue ? Awaiting your reply.
