### ISSUE TITLE
[Keyvault] MHSM vault backup/restore

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#13194]
**Resource Provider**

Keyvault
**Description of Feature or Work Requested**

Swagger ready at [dev-keyvault-Microsoft.KeyVault-7.2](https://github.com/Azure/azure-rest-api-specs/tree/dev-keyvault-Microsoft.KeyVault-7.2/specification).

**Minimum API Version Required**

**Swagger Link**

**Target Date**

**Comment by yungezz** [comment]
for MHSM private preview

**Comment by bim-msft** [comment]
Holding this due to service is not ready.

**Comment by yungezz** [comment]
private package is provided to service team for testing. Will only release it when service public, ETA now is around Sep.

**Comment by yungezz** [comment]
feature released in 2.12.0, close the issue.
