### ISSUE TITLE
Cloud Shell - Azure CLI: passing headers not working but does with version 2.4.0

### ISSUE THREAD

**Issue by Krumelur** [Azure/azure-cli#13208]
## Describe the bug

I'm trying to use `az rest` to access a CosmosDB's REST API. This works fine locally with Azure CLI 2.4.0 installed on macOS. The problem is caused by the `--headers` parameter.

According to the docs (https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-rest), multiple header values can be specified as a blank-separated string. This does not work. Only the first header is sent. This is why I'm using the JSON format which is optionally supported. This works fine when running locally.

```
headers="{\"x-ms-date\": \"$now\", \"x-ms-version\": \"2018-12-31\", \"x-ms-documentdb-isquery\": \"true\", \"Content-Type\": \"application/query+json\", \"Authorization\": \"$authString\"}"
echo "Headers:" $headers

# Make the API call by combining base URL and resource type.
url="$baseUrl$resourceType"
echo "URL: $url"
az rest --verbose -m get -u $url --headers $headers
```

When running the same command in Cloud Shell in Azure Portal (v 2.2.0), the error below occurs.

**Command Name**
`az rest`

**Errors:**
```
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
azure/cli/core/util.py, ln 280, in shell_safe_json_parse
    return json.loads(json_or_dict_string)
lib/python3.6/json/__init__.py, ln 354, in loads
    return _default_decoder.decode(s)
lib/python3.6/json/decoder.py, ln 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.6/json/decoder.py, ln 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 14 (char 13)

...

azure/cli/core/util.py, ln 552, in send_raw_request
    key, value = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az rest --verbose -m {} -u {} --headers {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}`

## Expected Behavior
1. JSON format for headers should work
2. Space separated headers should work

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

```

**Comment by yonzhan** [comment]
add to S170

**Comment by jiasli** [comment]
Hi @Krumelur, thanks for contacting us. I didn't introduce any change in the header resolving logic during 2.2.0 > 2.4.0. See the [blame](https://github.com/Azure/azure-cli/blame/4e1ed61cb44933fd59e4d44f729b09763c372895/src/azure-cli-core/azure/cli/core/util.py#L564-L571).

I suspect some headers are malformed. Could you run the command in Cloud Shell with `--debug` and share the result of the first line? It will reveal the actual arguments CLI receives. 

```
$ az rest --headers x-ms-date=2020-04-29 x-ms-version=2018-12-31 x-ms-documentdb-isquery=true Content-Type=application/query+json Authorization=somevalue --uri https://management.azure.com --debug
Command arguments: ['rest', '--headers', 'x-ms-date=2020-04-29', 'x-ms-version=2018-12-31', 'x-ms-documentdb-isquery=true', 'Content-Type=application/query+json', 'Authorization=somevalue', '--uri', 'https://management.azure.com', '--debug']
```

**Comment by Krumelur** [comment]
You're right. It was my fault. I didn't realize that my "date" string had blanks in it.

This does (of course) not work:

```
az rest -m get -u https://foo.com --headers x-ms-date=Wed, 29 Apr 2020 13:48:12 GMT
```

The header value must be enclosed in quotes:

```
az rest -m get -u https://foo.com --headers x-ms-date="Wed, 29 Apr 2020 13:48:12 GMT"
```

**Comment by jiasli** [comment]
Glad to know it is solved. 😊

**Comment by jiasli** [comment]
@Krumelur, I added some new contents in the doc. Maybe you are interested: https://github.com/Azure/azure-cli/pull/13249/files#diff-2f68bb7d55730e192dc93f133467a721R176-R194
