### ISSUE TITLE
No az iot central  and no  az iot central commands

### ISSUE THREAD

**Issue by djaus2** [Azure/azure-cli#13203]
When trying to run az iot central app show --name XXXX I got 
az iot: 'central' is not in the 'az iot' command group

Yet they are listed: https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/central?view=azure-cli-latest

Same problem with PNP

-------------------------------------------------------------

PS C:\Users\DavidJones\source\repos\az-iothub-ps\PS> az iot central 

. See 'az iot --help'.
PS C:\Users\DavidJones\source\repos\az-iothub-ps\PS> az iot pnp

az iot: 'pnp' is not in the 'az iot' command group. See 'az iot --help'.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 149e918e-db5e-736c-0d6c-92f985d7ddae
* Version Independent ID: 97344c62-24a6-2047-cd27-8612930b7a9b
* Content: [az iot pnp](https://docs.microsoft.com/en-us/cli/azure/iot/pnp?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/iot/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/iot/_help.py)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by yiyiguo** [comment]
@Azure/azure-iot-cli-triage

**Comment by prbans** [comment]
Have you installed the `az iot` cli extension? It's not part of the base azure cli

https://docs.microsoft.com/en-us/azure/iot-central/core/howto-manage-iot-central-from-cli#install-the-extension

**Comment by digimaun** [comment]
Closed as @prbans stated the resolution of first having the IoT extension installed as a pre-requisite.

**Comment by djaus2** [comment]
Yes I had the extensions installed.

**Comment by djaus2** [comment]
I did have the extensions installed.

David Jones MVP

________________________________

**Comment by digimaun** [comment]
@djaus2 Are you still experiencing this issue? Something to point out (as a double check) is the IoT extension is called `azure-iot`. The legacy IoT extension `azure-cli-iot-ext` has been deprecated for awhile and should no longer be used. It's scheduled for deletion.

**Comment by digimaun** [comment]
These are the docs for the PnP commands (which are entirely in the IoT extension) https://docs.microsoft.com/en-us/cli/azure/ext/azure-iot/iot/central?view=azure-cli-latest and these are the docs for the central commands in the extension https://docs.microsoft.com/en-us/cli/azure/ext/azure-iot/iot/central?view=azure-cli-latest. Note you do not need the IoT extension for the basic central app management commands (create/delete/list/show/update) https://docs.microsoft.com/en-us/cli/azure/iot/central/app?view=azure-cli-latest.

Taking this into account, if you are still running into issues can you provide the version of Azure CLI and IoT extension you are using? Also in general we recommend using the latest packages (if your environment can support it).
