### ISSUE TITLE
az group list issue

### ISSUE THREAD

**Issue by mayank2k** [Azure/azure-cli#13202]
## Describe the bug

**Command Name**
`az group list`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group list -o {} --query {}`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

```

**Comment by yungezz** [comment]
hi @mayank2k could you pls be more specific what's error and what's expected result, thanks

**Comment by mayank2k** [comment]
The problem auto resolved.

the issues came when i was using azure shell by creating default storage account. typing any command throw exception.

Now the problem automatically resolved, so closing the ticket.
