### ISSUE TITLE
Webapp:Set "stack" fore windows containers?

### ISSUE THREAD

**Issue by dazinator** [Azure/azure-cli#13205]
For windows containers (still not GA) there is also a "Stack" setting under configuration tab --&gt; "General Settings" --&gt; Stack Settings header - where you can pick ".NET Core". If I want to set this setting using `az webapp config ` is the argument still `--linux-fx-version` ? If so that seems counterintuitive as this is a windows container and nothing to do with linux. If it's not --linux-fx-version then what is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e50d77a-f2fa-6d6e-0c57-2f434c12766f
* Version Independent ID: f9a98805-6e16-487a-03ce-237cb964f83c
* Content: [az webapp config](https://docs.microsoft.com/en-us/cli/azure/webapp/config?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by dazinator** [comment]
- I just found --windows-fx-version - this can now be closed.. must have missed there before or it has just been added!

**Comment by dazinator** [comment]
I thought `--windows-fx-version` would be the answer for windows containers. However it failed - it seems this argument is not the windows containers parallel of `--linux-fx-version`.

So I am now out of ideas for how to set this for windows containers.

**Comment by yonzhan** [comment]
webapp

**Comment by Japeth** [comment]
Any updates on this?

**Comment by navba-MSFT** [comment]
@dazinator Apologies for the late reply. More Info about this paramater:

>--linux-fx-version
The runtime stack used for your linux-based webapp, e.g., "RUBY|2.5.5", "NODE|10.14", "PHP|7.2", "DOTNETCORE|2.1". See https://aka.ms/linux-stacks for more info.

The similar ask is discussed here Azure/azure-cli#21192. Please let me know if that helps. Awaiting your help.
