### ISSUE TITLE
Webapp:Is it possible to Pipe / STDIN in access key variable to keep more secure?

### ISSUE THREAD

**Issue by dazinator** [Azure/azure-cli#13207]
As per other docs, MS recommends not providing secure / sensitive variables as command line arguments directly as they can show up in various O/S level logs.

With that in mind, how do we provided the storage access key to these commands, securely?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4892bb1c-5cb4-91fa-325b-f5180cd05c3a
* Version Independent ID: 8c9a9a0e-5b36-4039-72c5-b28fd0bb9fd4
* Content: [az webapp config storage-account](https://docs.microsoft.com/en-us/cli/azure/webapp/config/storage-account?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/storage-account.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/storage-account.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
CLI don't have ability to mask passowrd in the secure way today when input from user

**Comment by billspat** [comment]
The question  about avoiding putting the storage key on the command line is not specific to this particular help
topic ( mounting storage account to app service.  ) but can be used anywhere. 

While you are waiting on Microsoft to answer, try this: 

Assuming you are using the CLI on bash, and you have an existing storage account, You could  extract the key into a variable using something like (replace placeholders with your actual storage account values)  

`AZSTORAGEKEY=$(az storage account keys list -g <GroupName> -n <storagename> --query [0].value -o tsv)`

then use that in another command, for example 

`az storage share create --account-name  <storagename> --name <sharename> --account-key $AZSTORAGEKEY --enabled-protocol SMB `

or combine into just one command (if you are feeling lucky ):

```sh
az storage share create --account-name  <storagename> --name <sharename>  \
     --account-key $(az storage account keys list -g <GroupName> -n <storagename> --query [0].value -o tsv) \
     --enabled-protocol SMB 
```

HTH

**Comment by dazinator** [comment]
> The question about avoiding putting the storage key on the command line is not specific to this particular help
> topic ( mounting storage account to app service. ) but can be used anywhere.
> 
> While you are waiting on Microsoft to answer, try this:
> 
> Assuming you are using the CLI on bash, and you have an existing storage account, You could extract the key into a variable using something like (replace placeholders with your actual storage account values)
> 
> `AZSTORAGEKEY=$(az storage account keys list -g <GroupName> -n <storagename> --query [0].value -o tsv)`
> 
> then use that in another command, for example
> 
> `az storage share create --account-name <storagename> --name <sharename> --account-key $AZSTORAGEKEY --enabled-protocol SMB `
> 
> or combine into just one command (if you are feeling lucky ):
> 
> ```shell
> az storage share create --account-name  <storagename> --name <sharename>  \
>      --account-key $(az storage account keys list -g <GroupName> -n <storagename> --query [0].value -o tsv) \
>      --enabled-protocol SMB 
> ```
> 
> HTH

@billspat 
You are calling the az command line within that script and passing the secret value as an argument to that command line. I dont think it matters that you supplied it from a variable - the OS keeps information about commands called and the arguments supplied and the secret variable will be visible there as it is supplied via an argument unencrypted.

**Comment by cephalin** [comment]
#please-close as this issue has been stale and product team declined to add information to what's already provided in the comments.

**Comment by dazinator** [comment]
I'm confused over the outcome. This has been closed with no explaination. Is the outcome what azure cli will continue to leave this as an insecure cli command?
