### ISSUE TITLE
Webapp:App Service web app SSL import command from Keyvault access right issue

### ISSUE THREAD

**Issue by AnandPatel4Git** [Azure/azure-cli#13204]
I have web app is in different resource group and keyvault is in different resource group as my keyvault contain shared secrets like wildcard certificate which can be utilized by all my 50-100 web app across enterprise . I Want to import SSL certificate stored inside keyvault to app service web app using  “az webapp config ssl import" command. I tried to trigger Azure CLI command from Azure devops as part of my app service deployment automation using service principal. I granted Get and List keyvault access to service principal and it has contributor access to app service web app resource group. But "az webapp config ssl import" command throw error and ask for first read access for keyvault and once we grant read access it throw error for write access. Which seems strange as we don't want to give write access to keyvault just for importing ssl certificate from keyvault. Even i tried to grant all in keyvault access policy. But "az webapp config ssl import" command only work once i gave contributor/read-write access to service principal. This is security concern as granting contributor access for keyvault to any service principal is not allowed best practice to avoid any accidental problem for other important secret stored inside respective keyvault. So need solution for this. Also we can't use seperate keyvault for each web app as it will be nightmare to manage and maintain shared secret for each and every keyvault dedicated to respective web app.

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by tsgenge** [comment]
The error seems to appear even if you have provided Read access - as long as it can address your keyvault it should have worked. One thing to note if only the most recent Azure CLI version supports key vaults from other resource groups being used - though specifying the full resource ID of your keyvault would work;

**Comment by panchagnula** [comment]
@AnandPatel4Git checking to see if your issue is resolved?

**Comment by panchagnula** [comment]
closing due to lack of response.
