### ISSUE TITLE
az aks update  --api-server-authorized-ip-ranges "" does not work on PowerShell

### ISSUE THREAD

**Issue by travis-sobeck** [Azure/azure-cli#13213]
## Describe the bug
According to your documentation, https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-update, using empty string for --api-server-authorized-ip-ranges should remove the ip range restrictions, it however just throws an error leaving cluster in undesired state

az aks update -g $resGrp -n $aks --api-server-authorized-ip-ranges ""

**Errors:**
```
az aks update: error: argument --api-server-authorized-ip-ranges: expected one argument
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update -g {} -n {} --api-server-authorized-ip-ranges`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1 *

```

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
@tomgeske @feiskyer could someone investigate this?

**Comment by yungezz** [comment]
bug

**Comment by travis-sobeck** [comment]
> bug

Yes, please fix 😁

**Comment by arrownj** [comment]
Hi @travis-sobeck , did you run this command in power shell ? There is a know issue for power shell to handle empty string. We need to specify an empty string as `'""'` in power shell. Could you try it once more ?

**Comment by travis-sobeck** [comment]
Yes, I do most things in PowerShell, I will try it in the morning in the morning

**Comment by TomGeske** [comment]
It works for me in windows command prompt and azure CLI 2.4.0

Could you try 

> az aks update -g $resGrp -n $aks --api-server-authorized-ip-ranges " "

**Note: ensure you have a space between quotes.**

**Comment by travis-sobeck** [comment]
Ok, wrapping the double quotes in single quotes did work
az aks update -g ${resGrp} -n $aks --api-server-authorized-ip-ranges '""'
did remove clear out the previous values

**Comment by jluk** [comment]
@TomGeske the public docs state no spaces should work, could you please investigate this on the docs as a separate followup?
https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges#disable-authorized-ip-ranges

Closing this issue as resolved.

**Comment by travis-sobeck** [comment]
I would not consider this issue to be "resolved" as nothing was actually fixed.  wrapping the double quotes in single quotes is not a normal thing to do in powershell and i'm sure i'm not the only powershell user.  Azure CLI should be smart enough to take a null/empty value for --api-server-authorized-ip-ranges and not throw an error.

**Comment by jluk** [comment]
Updating to be specifically about powershell if that is the root issue, handing off to Xiaojian/Tom to investigate as this may be a PowerShell syntax issue as opposed to an AKS issue.

**Comment by TomGeske** [comment]
We use the same code for PowerShell and Windows Command Prompt. Most likely related to the way arguments are parsed and escaped. 

We will continue investigate it. Please, use one of the workarounds suggested in the meantime. 

@MikkelHegn can you help to investigate this?

**Comment by travis-sobeck** [comment]
Yeah, I've stash the work around in my code, so I'm fine,  Its more to help the next person.  Also, bigger picture .... how many other cases are there in AzureCLI where this can happen.

**Comment by MikkelHegn** [comment]
Looking around a bit this seems like a common experience in PowerShell: 
https://github.com/Azure/azure-cli/issues/7110 and from this https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7

_To make double-quotation marks appear in a string, enclose the entire string in single quotation marks._

**Comment by arrownj** [comment]
Close this first, as it is not a problem of CLI.
