### ISSUE TITLE
Instructions not clear

### ISSUE THREAD

**Issue by techn0rome0** [Azure/azure-cli#13214]
I am requesting these instructions for enabling diagnostic logs for virtual machine scale sets to be more clear. The protection settings example does not work for most people testing and there are no powershell code examples or Azure portal examples to follow. Please update. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac6e6aef-61a3-3195-70a0-cc68473beeb7
* Version Independent ID: 56ef59d1-8acd-3a21-69cd-a2bac4109e7c
* Content: [az vmss diagnostics](https://docs.microsoft.com/en-us/cli/azure/vmss/diagnostics?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by CarelvanHeerden** [comment]
Please also include Terraform Examples

**Comment by qwordy** [comment]
Please refer to
https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-linux#extension-schema
https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows#extension-schema

**Comment by qwordy** [comment]
> 
> 
> Please also include Terraform Examples

@ArcturusZhang

**Comment by yungezz** [comment]
hi @techn0rome0 does above examples looks good for you? For Terraform example, could you pls help to create issue at Terraform repo? thanks.

**Comment by yungezz** [comment]
hi @techn0rome0 , will close the issue for now since no response. Feel free to create new issue if any other problem met. thanks.
