### ISSUE TITLE
Running 'az network' command for a specific RG when it has just been created (I.e. not updated in Graph database yet)

### ISSUE THREAD

**Issue by Forcebyte** [Azure/azure-cli#13217]
In pipeline cases, there should be a way to directly query when a VNet / Resource group has just been created (for example, if I run an 'az deployment' that creates a VNet and Resource group)

in https://docs.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest, the docs specifically ask to use `--assignee-object-id` to remove errors caused by the Graph DB not being updated, but this doesn't seem to be the case for most other commands. Is this the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1f75594-b95b-a85d-b971-c06e207e3fe2
* Version Independent ID: 16a09479-ff9b-9029-aae4-6ba14ccc8260
* Content: [az network](https://docs.microsoft.com/en-us/cli/azure/network?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @MyronFanQiu could you pls help to have a look

**Comment by MyronFanQiu** [comment]
@Forcebyte Hi. Could you share your questions in detail? You mentioned that `there should be a way to directly query`. What should be queried? `az network` is a command group instead of a command. Which command are we talking about?

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
@Forcebyte Hi. Are you still there?

**Comment by MyronFanQiu** [comment]
Closed this issue since no response. Feel free to open a new one if you meet any issue.
