### ISSUE TITLE
[ACS] Add a browse/dashboard command for Kubernetes

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1321]
The `az acs dcos browse` command allows easily connecting to the admin dashboard for a DC/OS cluster in ACS, however, there isn't currently an equivalent for Kubernetes. It would be great if there was an `az acs kubernetes browse` command that handled starting the local proxy and launching a browser to the k8s admin UI. This would behave similar to the `minikube dashboard` command (which many may use for local development), and would save users a few steps.

**Comment by brendandburns** [comment]
@lostintangent `kubectl proxy` and then going to `http://localhost:8001/ui` does this.

Do you think we need to wrap that up in an `az` command?

**Comment by lostintangent** [comment]
@brendandburns That solution definitely works great, so this suggestion isn't a blocker by any means. I just wondered whether it wouldn't be a nice helper command since the Az CLI already has the equivalent command for DC/OS, as does minikube, so there's a little bit of precedent for the value. But I think it's pretty low-pri since, as you mentioned, the kubectl already provides a simple solution.

**Comment by brendandburns** [comment]
well, at the least we can shell out to kubectl...  easy enough to do, and I think supporting the precedent makes sense.  (though honestly, I want to kill the SSH tunnel in general, it's a bad pattern to encourage)
