### ISSUE TITLE
az aks kollect command fails ...

### ISSUE THREAD

**Issue by i008817** [Azure/azure-cli#13228]
## Describe the bug

**Command Name**
`az aks kollect`

**Errors:**
```
invalid syntax (custom.py, line 1399)
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 523, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 291, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
azure/cli/core/__init__.py, ln 528, in get_op_handler
    op = import_module(mod_to_import)
lib64/python2.7/importlib/__init__.py, ln 37, in import_module
    __import__(name)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 1399
    f'save them to the storage account '
    ^
SyntaxError: invalid syntax
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks kollect -h`

## Environment Summary
```
Linux-4.12.14-lp151.28.20-default-x86_64-with-SuSE-12-x86_64
Python 2.7.14
Shell: bash

azure-cli 2.0.76 *

Extensions:
aks-preview 0.4.43

```

**Comment by yonzhan** [comment]
aks

**Comment by Tatsinnit** [comment]
Hey @i008817 , thanks for sharing the info, it was helpful. So here is the issue: `Python 2.7.14` 

The syntax error you are seeing is because the python version `az-cli-extension` uses and dependency on is `3.0`  

* Details of what's new in `py3`:  https://docs.python.org/3.0/whatsnew/3.0.html   

**Fix:** - Please upgrade your local machine python and you will not see this `syntax` issue.

Thanks.

**Comment by i008817** [comment]
Hello
Thanks for taking cate of the request.
However even after the “Upgrade” of Python the error remains the same

Can you please name me the correct repositories where to upgrade from?

Thanks and best regards
Roland

**Comment by Tatsinnit** [comment]
Hey @i008817 please follow the instruction and link I provided earlier I.e. you need to configure your local machine to correct purging version.

* This link has steps to do So:
https://github.com/Azure/azure-cli/issues/2529#issuecomment-287284321

Beyond that there nothing specific from Aks end which needs fixing.

Thanks

**Comment by yunjchoi** [comment]
Hi @i008817, were you able to resolve the issue after configuring your local machine to the correct python version?

**Comment by i008817** [comment]
Hello, unfortunately not
I there no other way then the solution, described here - [#2529 (comment)](https://github.com/Azure/azure-cli/issues/2529#issuecomment-287284321)

Best Regards Roland

**Comment by yunjchoi** [comment]
Hi @i008817, I'd like to make sure I understand you clearly. Have you configured your local machine to the correct python version and you are still facing issues with az aks kollect? Or are you looking for a different solution from the one described here - #2529 (comment)?

**Comment by i008817** [comment]
Hello,

I’m looking for an easier solution than described in here - #2529<https://github.com/Azure/azure-cli/issues/2529> (comment), or is this the only possibility?

**Comment by i008817** [comment]
Hello
the following commands did the trick, you can close the thread. Thanks for your help

server:~ # zypper refresh
server:~ # zypper update azure-cli
server:~ # az extension add --name aks-preview
server:~ # az --version
azure-cli                          2.5.1
core                               2.5.1
Extensions:
aks-preview                       0.4.44
Python location '/usr/bin/python3'
Extensions directory '/root/.azure/cliextensions'
Python (Linux) 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
server:~ #
