### ISSUE TITLE
cosmosdb mongodb collection update cannot set default TTL to -1

### ISSUE THREAD

**Issue by nohajc** [Azure/azure-cli#13229]
## Describe the bug

When attempting to enable TTL on cosmosdb mongo collection with no default, TTL is disabled instead.

## To Reproduce:
Run the following command on an existing cosmosdb mongodb collection:

`az cosmosdb mongodb collection update --account-name {} --resource-group {} --database-name {} --name {} --idx "[{\"key\": {\"keys\": [\"_ts\"]},\"options\": {\"expireAfterSeconds\": -1}}]"`

When inspecting the result in mongo shell, the result looks like this:

```
        {
                "v" : 1,
                "key" : {
                        "_ts" : 1
                },
                "name" : "_ts_1",
                "ns" : "db.collection"
        }
```

## Expected Behavior

The command should set default TTL to -1

```
        {
                "expireAfterSeconds" : -1,
                "v" : 1,
                "key" : {
                        "_ts" : 1
                },
                "name" : "_ts_1",
                "ns" : "db.collection"
        }
```

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.0

```
## Additional Context

Note that setting default TTL to -1 works fine if I use the deprecated command
`az cosmosdb collection update --name {} --resource-group-name {} --db-name {} --collection-name {} --default-ttl -1`

**Comment by yonzhan** [comment]
cosmosdb

**Comment by shurd** [comment]
Hi @nohajc, I am looking into this issue. I will update once I finish my investigation

**Comment by nohajc** [comment]
> Hi @nohajc, I am looking into this issue. I will update once I finish my investigation

Any update?

**Comment by shurd** [comment]
Hi @nohajc sorry for the delay. We have an active thread with our Mongo DB team investigating if we are missing something in our resource provider (the request goes through ARM for the non-deprecated command). I will be sure to update here as soon as we identify any required fixes.

**Comment by JosXa** [comment]
I am trying to use the mongodb-csharp driver with the following create index command:

```
var options = new CreateIndexOptions {ExpireAfter = TimeSpan.FromSeconds(-1)};
var field = new StringFieldDefinition<TDto>("_ts");
var indexDefinition = new IndexKeysDefinitionBuilder<TDto>().Ascending(field);
Collection.Indexes.CreateOne(indexDefinition, options);
```

And it fails with `----> MongoDB.Driver.MongoCommandException : Command createIndexes failed: TTL index 'expireAfterSeconds' option cannot be less than 0. Index spec: { key: { _ts: 1 }, name: "_ts_1", expireAfterSeconds: -1.0 }.`, which I think is related.

**Comment by shurd** [comment]
Hi, just to provide an update, we are tracking a fix for this problem in our service as work item 553745. We do not yet have a firm timeline for the fix, but I will update once we finalize that.

**Comment by MehaKaushik** [comment]
Since we do not have a timeline for this ask in the near future and we tracking it internally, I am closing this issue from github.
