### ISSUE TITLE
failed to create aks cluster in cloud shell.

### ISSUE THREAD

**Issue by gopik** [Azure/azure-cli#13226]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --enable-addons {} --generate-ssh-keys`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

```

**Comment by yonzhan** [comment]
aks

**Comment by yungezz** [comment]
seems duplicate issue with https://github.com/Azure/azure-cli/issues/13234

**Comment by arrownj** [comment]
Hi @gopik , it's a known issue of Cloud Shell. Similar to #11749 (comment)

To solve it, please use Azure CLI on a local machine or run az login in Cloud Shell and retry the command.

**Comment by yungezz** [comment]
hi @gopik are you running the command inside Cloushell?

**Comment by Benauld** [comment]
Did and az login and that seemed to solve the bad request issue.
Change my region from uksouth to northeurope and got the following error. Tried to request extra cores but told cannot do this on the free year subscription. I am only trying to follow the Microsoft tutorials for deploying Kubernetes with AKS.


Operation failed with status: 'Bad Request'. Details: Provisioning of resource(s) for container service aksworkshop-17779 in resource group aksworkshop failed. Message: Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: northeurope, Current Limit: 4, Current Usage: 0, Additional Required: 6, (Minimum) New Limit Required: 6. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%22cbdaf421-e081-4e10-9650-8db43d2a5287%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests.. Details:

**Comment by jluk** [comment]
@Benauld you will need to raise your cpu quota in order to fulfill the deployment, instructions can be found on that link shared in the error message.

**Comment by arrownj** [comment]
Hi @Benauld , close this first. The cloud shell issue will be traced in #11749
