### ISSUE TITLE
Failure running sample commands

### ISSUE THREAD

**Issue by josiahvinson** [Azure/azure-cli#13233]
I'm trying to run the sample commands in the [az docs](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#code-try-18) using the Cloud Shell and getting failures. I'm logged into my Microsoft corp account.

## Describe the bug

**Command Name**
`az rest`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az rest --method {} --uri {} --body {}`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5

azure-cli 2.2.0 *

```

**Comment by yungezz** [comment]
hi @arrownj could you pls look at why the auth endpoint is localhost? thanks

**Comment by yungezz** [comment]
duplicate with https://github.com/Azure/azure-cli/issues/13226

**Comment by yungezz** [comment]
add @jiasli who works on az rest

**Comment by arrownj** [comment]
Hi @josiahvinson, it's a known issue of Cloud Shell. Similar to #11749 (comment)

To solve it, please use Azure CLI on a local machine or run az login in Cloud Shell and retry the command.

**Comment by yungezz** [comment]
hi @josiahvinson could you pls the resource you're using in `az rest`? thanks.

**Comment by josiahvinson** [comment]
I was trying the examples here: https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-rest-examples and saw this failure on the first two:
```
az rest --method get --uri https://graph.microsoft.com/beta/auditLogs/directoryAudits
```
```
az rest --method patch --uri "https://graph.microsoft.com/v1.0/users/johndoe@azuresdkteam.onmicrosoft.com" --body "{\"displayName\": \"jondoe2\"}"
```

**Comment by jiasli** [comment]
This is not exactly related to `az rest`, but to Cloud Shell's issue where it can't get the token. As @arrownj suggested, please use Azure CLI on a local machine or run `az login` in Cloud Shell and retry the command.

**Comment by josiahvinson** [comment]
Sure - that works. The issue is with running them specifically from the samples page I linked. There's user interface there to sign you in, and then I encountered errors after signing in and selecting a subscription.
