### ISSUE TITLE
Incorrect URL for 'az acs kubernetes install-cli'

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1323]
For 'Darwin', the URL to download `kubectl` from appears incorrect.

It is `'https://storage.googleapis.com/kubernetes-release/release/v{}/darwin/amd64/kubectl'.format(client_version)`

Looks like it should be:
`'https://storage.googleapis.com/kubernetes-release/release/v{}/bin/darwin/amd64/kubectl'.format(client_version)`

**Comment by mayurid** [comment]
@brendanburns and @sauryadas: Guys, Derek has a PR out for this. it would be awesome if you guys can take a quick look.
@yugangw-msft as fyi
