### ISSUE TITLE
XML specified is not syntactically valid

### ISSUE THREAD

**Issue by philspokas** [Azure/azure-cli#13232]
## Describe the bug
az storage logging update command when used to update table storage logging, generates an invalid XML error

**Command Name**
``az storage logging update --connection-string $sa --log rwd --retention 120 --services t --version 2.0 --verbose

**Errors:**
XML specified is not syntactically valid.
``<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>InvalidXmlDocument</m:code><m:message xml:lang="en-US">XML specified is not syntactically valid.
RequestId:17fbe858-f002-0090-4d79-1d4bb3000000
Time:2020-04-28T16:27:45.6607274Z</m:message></m:error>

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Set the storage account connection string variable
`` $sa='<storage account connection string>'

## Expected Behavior
Logging is provisioned as it is for both blog and queue storage

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.4.0 *

Extensions:
application-insights 0.1.1
azure-devops 0.13.0
dev-spaces 1.0.3

```

**Comment by philspokas** [comment]
"--version 2.0" cannot be specified for table storage. Removing this parameter eliminates the error.

**Comment by yungezz** [comment]
@Juliehzl  to  help confirm this is by design behavior

**Comment by yonzhan** [comment]
add to S169

**Comment by yonzhan** [comment]
add to S171

**Comment by Juliehzl** [comment]
@philspokas for table service, the supported version is 1.0 not 2.0.
