### ISSUE TITLE
Base64 of CSR downloaded from KV certificate operations page doesn't match Azure CLI

### ISSUE THREAD

**Issue by TitaniumDave** [Azure/azure-cli#13231]
As described in the title, if you browse to your Key Vault after generating an RSA private key and CSR then browse to **Certificates -> Certificate Operation -> Download CSR** the Base64 and CSR is valid (and can be viewed with `openssl req -in foo.req -text -noout`).

However if you execute `az keyvault certificate pending show --name foo --vault-name bar` the Base64 on screen does not match the Base64 downloaded from the web UI, and does not parse with the above openssl command.

I am using macOS 10.15.4 with the Azure CLI version below.

Is this correct? Should they not be the same?

```
% az --version                         
azure-cli                          2.5.0

command-modules-nspkg              2.0.3
core                               2.5.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
interactive                       1.12.0

Python location '/usr/local/Cellar/azure-cli/2.5.0/libexec/bin/python'
Extensions directory '/Users/daveshaw/.azure/cliextensions'

Python (Darwin) 3.8.2 (default, Mar 11 2020, 00:29:50) 
[Clang 11.0.0 (clang-1100.0.33.17)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

```
% openssl version
OpenSSL 1.1.1g  21 Apr 2020
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4912852-e33b-5d45-4de4-d64ce94693d9
* Version Independent ID: 02098cf1-5e19-59b5-efe5-b31006334dc5
* Content: [az keyvault certificate pending](https://docs.microsoft.com/en-us/cli/azure/keyvault/certificate/pending?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
@bim-msft could you pls help to have a look? thanks

**Comment by bim-msft** [comment]
Hi @TitaniumDave thanks for the feedback!
It's weird that I cannnot reproduce your scenario. I created a self-signed certificate on Azure Portal, this is the content retrieved by Azure CLI:
```
az keyvault certificate pending show -n test-cert-0527 --vault-name bim-kv5

{
  "cancellationRequested": false,
  "csr": "MIICpzCCAY8CAQAwFzEVMBMGA1UEAxMMbXlkb21haW4uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwJqQy1TdZbjXYHtx7XZrU76MEuHdWWksMIt3zP2E8ZDPVXl0sYFJ1SDF8YrEg1QQ0ZKsd8LIND8fCKa+rk7upBEAubDzxJi
bk1uVcMnKZ8yDpYo59idVlsEzF09IXqKZGhhKFKbCv9KDnGSU0V8F49W/X7nrkzGgmRlEcZ5j3LLVtppeqgDkQ6VGvJpPDjcfOmiFhn2qO1CZrRbw3MqU6c9J+oLdIDYjdkze+yBXJ++yE/0VVrNjnpBWatSU+Kxu0BDpF4922BQ0+QnIQyPGDCyleIXVw+BXUpYi
b1HwjIzrc/m6s8TM/JeoRsCEIWr1df5/k2LdH2t06CrjLcmdlQIDAQABoEswSQYJKoZIhvcNAQkOMTwwOjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggEBAFtzSfN6fD68T
ITPL0aXiJloqK92sqiCyl7kUv6TupzoQvvxZCRBoz74Gb5bdqTOTMrW0KLddN5YaMC9iEsH0tOHEERaNxr9gsrKu+ljhTwLJf8eJlrvjKQGJmohETJF8bOWRwIPAEFWB+rUnRYuWActDepFNZVR9gJaNpoCsvHFdn+fucCL8JoWzTI3CYGfv+aDTYxdzMlka8by9v
Wecq0bPO4t9I2YbrK0e7W90Bx8Tsrf/xgnY/3UMi8bFuFFJBKdmGvW1LHVOnG8jfXMR/r5xKRG+usxXgWRF6DDqZ9UfgLdz0DaG+siA4O6sX+CNzmx1gOLmNuRxRInCg7V9Ug=",
  "error": null,
  "id": "https://bim-kv5.vault.azure.net/certificates/test-cert-0527/pending",
  "issuerParameters": {
    "certificateTransparency": null,
    "certificateType": null,
    "name": "Self"
  },
  "name": "test-cert-0527",
  "requestId": "6aa0797ab0d945d3b2eb899405b130df",
  "status": "completed",
  "statusDetails": null,
  "target": "https://bim-kv5.vault.azure.net/certificates/test-cert-0527"
}
```

Also I downloaded the CSR file on Azure Portal (**Certificates -> Certificate Operation -> Download CSR**), then used openssl to display it:
```
openssl req -in /mnt/c/users/bim/downloads/test-cert-0527_6aa0797ab0d945d3b2eb899405b130df.csr

-----BEGIN CERTIFICATE REQUEST-----
MIICpzCCAY8CAQAwFzEVMBMGA1UEAxMMbXlkb21haW4uY29tMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwJqQy1TdZbjXYHtx7XZrU76MEuHdWWksMIt3
zP2E8ZDPVXl0sYFJ1SDF8YrEg1QQ0ZKsd8LIND8fCKa+rk7upBEAubDzxJibk1uV
cMnKZ8yDpYo59idVlsEzF09IXqKZGhhKFKbCv9KDnGSU0V8F49W/X7nrkzGgmRlE
cZ5j3LLVtppeqgDkQ6VGvJpPDjcfOmiFhn2qO1CZrRbw3MqU6c9J+oLdIDYjdkze
+yBXJ++yE/0VVrNjnpBWatSU+Kxu0BDpF4922BQ0+QnIQyPGDCyleIXVw+BXUpYi
b1HwjIzrc/m6s8TM/JeoRsCEIWr1df5/k2LdH2t06CrjLcmdlQIDAQABoEswSQYJ
KoZIhvcNAQkOMTwwOjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH
AwEGCCsGAQUFBwMCMAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggEBAFtzSfN6
fD68TITPL0aXiJloqK92sqiCyl7kUv6TupzoQvvxZCRBoz74Gb5bdqTOTMrW0KLd
dN5YaMC9iEsH0tOHEERaNxr9gsrKu+ljhTwLJf8eJlrvjKQGJmohETJF8bOWRwIP
AEFWB+rUnRYuWActDepFNZVR9gJaNpoCsvHFdn+fucCL8JoWzTI3CYGfv+aDTYxd
zMlka8by9vWecq0bPO4t9I2YbrK0e7W90Bx8Tsrf/xgnY/3UMi8bFuFFJBKdmGvW
1LHVOnG8jfXMR/r5xKRG+usxXgWRF6DDqZ9UfgLdz0DaG+siA4O6sX+CNzmx1gOL
mNuRxRInCg7V9Ug=
-----END CERTIFICATE REQUEST-----
```

As you see, two texts are identical.

Could you please provide me some more information about how to reproduce it? Such as how your certificate was generated. Thanks!

**Comment by bim-msft** [comment]
Closing due to longtime inactivity. Feel free to reopen this and ping me again when you have new information. @TitaniumDave
