### ISSUE TITLE
[AppService] Creating a function app should only set AzureWebJobsDashboard if AppInsights is disabled

### ISSUE THREAD

**Issue by gzuber** [Azure/azure-cli#13236]

**Comment by yungezz** [comment]
hi @gzuber could you pls share info about az cli version you're using, and command to help trouble shooting? thanks

**Comment by gzuber** [comment]
Sorry @yungezz I'm on the AppService/Functions team, this is a tracking issue for a work item we need to fix the `az functionapp create` command. I've linked the related [Function's github issue](https://github.com/Azure/Azure-Functions/issues/1524) and the [PR](https://github.com/Azure/azure-cli/pull/13238) I just finished.

**Comment by yungezz** [comment]
Got it. thanks @gzuber for explanation.
