### ISSUE TITLE
libffi is an undocumented dependency

### ISSUE THREAD

**Issue by jetzerb** [Azure/azure-cli#13235]
On a fresh install of the azure cli on Ubuntu, using the method described on [Install Azure CLI with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest), attempting to install an extension results in an error message.  Adding the debug flag shows that it's due to a missing dependency on libffi (see [comments](https://github.com/Azure/azure-cli-extensions/pull/535#issuecomment-471240107) on azure-cli-extensions issue # 535 on github)
Please update either this page or the page linked above to call it out as a dependency.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ea1a0d9-c0d5-657d-f73b-0e9220bec600
* Version Independent ID: 7138b13a-3381-1aee-346b-5e7f6905c5b3
* Content: [az extension](https://docs.microsoft.com/en-us/cli/azure/extension?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/extension/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/extension/_help.py)
* Service: **azure-cli**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
@fengzhou-msft could you pls have a look?thanks

**Comment by fengzhou-msft** [comment]
@jetzerb which Ubuntu distro are you using? I tested on Bionic and Xenial, and the install of azure-devops can be done successfully.

For the debug log in [comments](https://github.com/Azure/azure-cli-extensions/pull/535#issuecomment-471240107), I noticed there's a mismatch between the package repo and the distro:

> DEBUG: Linux distro check: /etc/apt/sources.list.d/azure-cli.list has 'wheezy', current distro is 'bionic' 

And it could be the reason for the failure according to this [comment](https://github.com/Azure/azure-cli-extensions/issues/65#issuecomment-366270381).

**Comment by jetzerb** [comment]
@fengzhou-msft I am using Focal (20.04).  I just tried it now and it worked fine.

I think you're right about the version mismatch.  At the time, Microsoft didn't have a Ubuntu 20.04 repository, so I was overriding the installation script to pull the 19.10 version of `azure-cli` and creating a symlink of libffi7 to libffi6 to satisfy the older version's requirement. I removed that workaround at the end of May, at which time MS had a 20.04 package repository.

I see that libffi is installed in the base Ubuntu 20.04 container, so while it is _technically_ a requirement, the fact that it's installed by default means that it's not _practically_ a requirement.

**Comment by fengzhou-msft** [comment]
> @fengzhou-msft I am using Focal (20.04). I just tried it now and it worked fine.
> 
> I think you're right about the version mismatch. At the time, Microsoft didn't have a Ubuntu 20.04 repository, so I was overriding the installation script to pull the 19.10 version of `azure-cli` and creating a symlink of libffi7 to libffi6 to satisfy the older version's requirement. I removed that workaround at the end of May, at which time MS had a 20.04 package repository.
> 
> I see that libffi is installed in the base Ubuntu 20.04 container, so while it is _technically_ a requirement, the fact that it's installed by default means that it's not _practically_ a requirement.

Right. And we have a [troubleshooting section](https://github.com/Azure/azure-cli/blob/dev/doc/install_troubleshooting.md#errors-on-install-with-cffi-or-cryptography) in case libffi is missing after installation on some old systems.
