### ISSUE TITLE
az openshift list fails

### ISSUE THREAD

**Issue by jarielpa** [Azure/azure-cli#13242]
## Describe the bug

**Command Name**
`az openshift list`

**Errors:**
```
name
Traceback (most recent call last):
Temp\pip-install-d4ph977u\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 631, in execute
azure\cli\core\commands\__init__.py, ln 695, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 688, in _run_job
Local\Temp\pip-install-d4ph977u\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 665, in _run_job
azure\cli\core\commands\__init__.py, ln 324, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 574, in default_command_handler
azure\cli\command_modules\acs\custom.py, ln 3282, in osa_list
azure\cli\command_modules\acs\custom.py, ln 3242, in _remove_osa_nulls
AttributeError: name
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az openshift list`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.0

Extensions:
aro 3.1.0

```

**Comment by yonzhan** [comment]
openshift

**Comment by navba-MSFT** [comment]
@jarielpa Apologies for the late reply. The az openshift command is deprecated and has been replaced by az aro for ARO 4 clusters. See http://aka.ms/aro/4 for information on switching to ARO 4.

More Info [here](https://docs.microsoft.com/en-us/cli/azure/openshift?view=azure-cli-latest). This github thread is open for quite sometime. Could you please let me know if you still need any assistance on this ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@jarielpa This is a follow-up to check if you had a chance to look at my above comment. This issue is open for quite sometime. Please let us know if you need any further assistance on this.
