### ISSUE TITLE
az ad app update set error

### ISSUE THREAD

**Issue by peterfleck** [Azure/azure-cli#13248]
## Describe the bug

setting knownClientApplications

**Command Name**
`az ad app update`

**Errors:**
```
Refuse str type as a valid iter type.
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 686, in _run_job
    cmd_copy.exception_handler(ex)
...
python3.8/site-packages/msrest/serialization.py, ln 733, in serialize_data
    return self.serialize_type[iter_type](
python3.8/site-packages/msrest/serialization.py, ln 810, in serialize_iter
    raise SerializationError("Refuse str type as a valid iter type.")
msrest.exceptions.SerializationError: Refuse str type as a valid iter type.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad app update --id {} --set knownClientApplications=`

## Environment Summary
```
macOS-10.15.4-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.5.0

Extensions:
azure-devops 2.9

```

**Comment by yonzhan** [comment]
@arrownj  please take a look

**Comment by yungezz** [comment]
s170

**Comment by arrownj** [comment]
Hi @peterfleck , `knownClientApplications` is an array, to add a value to it, you should use below command:

> az ad app update --id {} --add knownClientApplications {}

**Comment by frankiea** [comment]
> Hi [@peterfleck](https://github.com/peterfleck) , `knownClientApplications` is an array, to add a value to it, you should use below command:
> 
> > az ad app update --id {} --add knownClientApplications {}

Hi @arrownj, I tried the format above you recommended but it did not update the knownClientApplications list. I also didn't get an error, interestingly enough - but it didn't seem to work. Any idea why that might be the case? Have you had success with this?
