### ISSUE TITLE
azure-iot fails install with v2.5.0

### ISSUE THREAD

**Issue by DAD713** [Azure/azure-cli#13240]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.5..0

**Describe the bug**
After installing azure-cli the azure-iot causes errors

**To Reproduce**
install azure-cli
az extension add --name azure-iot

**Expected behavior**
No Errors

**Environment summary**
installed using powershell, saw failure and uninstalled azure-cli from the control panel.
Installed azure-cli with MSI
run the extension command listed above failed.
OS: WIndows 10
Powershell 5

**Additional context**
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\azure-cli-core\azure\cli\core\extension\__init__.py", line 148, in get_metadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\wheel.py", line 16, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\distribution.py", line 108, in extractMetadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-d4ph977u\pkginfo\pkginfo\wheel.py", line 43, in read
ValueError: Not a known wheel archive format or installed .dist-info: C:\Users\laxre\.azure\cliextensions\azure-iot\paho_mqtt-1.5.0-py3.6.egg-info

**Comment by haroldrandom** [comment]
Sincerely sorry for the incovenience, we fixed it https://github.com/Azure/azure-cli/pull/13222 
The next release would be tomorrow.

**Comment by yonzhan** [comment]
add to S170

**Comment by haroldrandom** [comment]
As for installing older version of Azure CLI, you could try `pip install azure-cli==2.4.0` if you are in a Python (virtual) env. but this could polute your env if you have other Python depencies in the same Python env.

Another option for windows is to download [2.4.0 in MSI format](https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.4.0.msi) if you are using MSI installation. Better uninstall the previous version before install a new one.

**Comment by haroldrandom** [comment]
New [Azure CLI 2.5.1](https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.5.1.msi) is released the bug should be fixed, please upgrade to the newer version.

Sorry for the trouble. We should be more careful. :(
