### ISSUE TITLE
 az extension add -n aro --index https://az.aroapp.io/stable failed in centos 7

### ISSUE THREAD

**Issue by jarielpa** [Azure/azure-cli#13244]
## Describe the bug

**Command Name**
`az extension add`

**Errors:**
```
An error occurred. Pip failed with status code 1. Use --debug for more information.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension add -n {} --index {}`

## Environment Summary
```
Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
Python 3.6.8
Installer: RPM

azure-cli 2.5.0

```

**Comment by haroldrandom** [comment]
Dup with https://github.com/Azure/azure-cli/issues/13241
