### ISSUE TITLE
Azure Key Vault creation fails when enable soft delete is set to false

### ISSUE THREAD

**Issue by kooditoni** [Azure/azure-cli#13247]
# Describe the bug

Azure Key Vault creation using `az keyvault` gives an error when soft delete is disabled and does not create the key vault.

# To Reproduce

Running the following command
```bash
az keyvault create --resource-group myrg --name mykv \
  --location westeurope --sku standard --enable-soft-delete false
``` 
returns
```bash
The property "enableSoftDelete" must be set to true.
```
# Expected Behavior

Should create the key vault with soft delete disabled.

# Environment summary
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
```bash
az --version
azure-cli                          2.5.0

command-modules-nspkg              2.0.3
core                               2.5.0
nspkg                              3.0.4
telemetry                          1.0.4
```
Same error also in Cloud Shell environment.

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

```bash
$ az --version
azure-cli                          2.4.0 *

command-modules-nspkg              2.0.3
core                               2.4.0 *
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
application-insights               0.1.6
resource-graph                     1.0.0
azure-devops                      0.18.0
```

# Additional Context

The reason seems to be the property *softDeleteRetentionInDays* in the JSON payload the `az keyvault` command sends to the REST API. 

```jsonc
{
    "location": "westeurope",
    "properties": {
        "tenantId": "<removed>",
        "sku": {
            "family": "A",
            "name": "standard"
        },
        "accessPolicies": [],
        "enableSoftDelete": false,
        "softDeleteRetentionInDays": 90

      // rest of the properties removed
    }
}
```

Everything seems to work correctly if the key vault creation is invoked directly using the `az rest` command and without the property *softDeleteRetentionInDays* in the JSON payload.

```json
{
    "location": "westeurope",
    "properties": {
        "tenantId": "<removed>",
        "sku": {
            "family": "A",
            "name": "standard"
        },
        "accessPolicies": [],
        "enableSoftDelete": false,
        "enableRbacAuthorization": false
    }
}
```
```bash
az rest \
    --method PUT \
    --uri "https://management.azure.com/subscriptions/<removed>/resourceGroups/my-resource-group/providers/Microsoft.KeyVault/vaults/my-keyvault?api-version=2019-09-01"
    --header Content-Type=application/json \
    --body <the json playload above>
```

**Comment by yungezz** [comment]
hi @bim-msft could you pls have a look

**Comment by sarthakvijayvergiya** [comment]
we are also facing this same issue.

Is azure CLI updated in the background?

**Comment by vbrinza** [comment]
have the same problem

$ az --version
azure-cli                          2.3.1 *

command-modules-nspkg              2.0.3
core                               2.3.1 *
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-firewall                     0.3.0
aks-preview                       0.4.42
azure-devops                      0.12.0

**Comment by HumanBug** [comment]
Same here.
KeyVault creation without this option is also not possible.

**Comment by rickystream94** [comment]
+1 same issue: running an ARM deployment with the following template fails with the same error, if the value provided to the `enableKeyVaultSoftDelete` parameter is set to `false`:

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "keyVaultName": {
            "type": "String"
        },
        "enableKeyVaultSoftDelete": {
            "defaultValue": true,
            "type": "Bool"
        }
    },
    "variables": {
        "keyVaultApiVersion": "2019-09-01"
    },
    "resources": [
        {
            "type": "Microsoft.KeyVault/vaults",
            "apiVersion": "[variables('keyVaultApiVersion')]",
            "name": "[parameters('keyVaultName')]",
            "location": "[resourceGroup().location]",
            "properties": {
                "tenantId": "[subscription().tenantId]",
                "sku": {
                    "family": "A",
                    "name": "standard"
                },
                "enabledForDeployment": false,
                "enabledForDiskEncryption": false,
                "enabledForTemplateDeployment": false,
                "enableSoftDelete": "[parameters('enableKeyVaultSoftDelete')]",
                "createMode": "default",
                "enablePurgeProtection": true,
                "accessPolicies": []
            }
        }
    ]
}
```

Worth noting that the [latest available Microsoft.KeyVaults/vauls API version (2019-09-01)](https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/2019-09-01/vaults) specifies:

> `enableSoftDelete`: Property to specify whether the 'soft delete' functionality is enabled for this key vault. If it's not set to any value(true or false) when creating new key vault, it will be set to true by default. Once set to true, it cannot be reverted to false.

Whereas if you check the same property definition for an older API version (such as [2018-02-14](https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/2018-02-14/vaults)) you can see:

> `enableSoftDelete`: Property to specify whether the 'soft delete' functionality is enabled for this key vault. **It does not accept false value**.

In both API version definitions, you can also see that:

> `enablePurgeProtection`: Property specifying whether protection against purge is enabled for this vault. Setting this property to true activates protection against purge for this vault and its content - only the Key Vault service may initiate a hard, irrecoverable deletion. **The setting is effective only if soft delete is also enabled**. Enabling this functionality is irreversible - that is, the property does not accept false as its value.

Out of curiosity, from the above ARM template I tried to remove the `"enablePurgeProtection": true,` line and the deployment succeeded: the KV got created with soft delete **disabled**.
Deployment doesn't work if I set `enablePurgeProtection` to `false`:

```
message '{
  "error": {
    "code": "BadRequest",
    "message": "The property \"enablePurgeProtection\" cannot be set to false. Enabling the purge protection for a
vault is an irreversible action."
  }
}'
```

It still looks like there's some clear inconsistency between what the API definitions say and what the actual behavior of the deployment is.

**Comment by the-vampiire** [comment]
i am getting the same error but **without setting the flag** (so the default `true` should be used):

```ps
# the rg is set as a config default (so rg and location are defaulted)
> az keyvault create -n test-key-vault
The property "enableSoftDelete" must be set to true.
```

it fails to create. this was working as of yesterday afternoon but from last night to today is failing.

**Comment by the-vampiire** [comment]
to follow up. the keyvault never gets created but i am getting a "The name 'test-key-vault' is already in use."

nothing appears under `az keyvault list` nor `az keyvault list-deleted`. it also does not exist on the azure console so this is not a CLI-only issue. idk if this is related but something odd is happening with az keyvault.

**Comment by johndoe0920** [comment]
I also got this error when trying to use the set-policy command for a MSI on the keyvault.

`az keyvault set-policy -n mirms-usw-user-kv --object-id <GUID> --subscription <Sub GUID> --key-permissions encrypt decrypt wrapKey unwrapKey sign verify get list create update import delete backup restore recover purge  --output json
The property "enableSoftDelete" must be set to true.`

**Comment by HumanBug** [comment]
> to follow up. the keyvault never gets created but i am getting a "The name 'test-key-vault' is already in use."
> 
> nothing appears under `az keyvault list` nor `az keyvault list-deleted`. it also does not exist on the azure console so this is not a CLI-only issue. idk if this is related but something odd is happening with az keyvault.

The KeyVault name must be global unique, therefore you can assume that the name is already used by other users.

**Comment by mjspeller** [comment]
I am getting the same error 'The property "enableSoftDelete" must be set to true.' with Azure CLI 2.5.1
If i remove --enable-soft-delete from the command I still get the error even tho it is suppose to default to true.
If i specifically set it to true I can continue with my deployment. "--enable-soft-delete true"

**Comment by Abhishek-P** [comment]
> 
> 
> I am getting the same error 'The property "enableSoftDelete" must be set to true.' with Azure CLI 2.5.1
> If i remove --enable-soft-delete from the command I still get the error even tho it is suppose to default to true.
> If i specifically set it to true I can continue with my deployment. "--enable-soft-delete true"

Same for me

**Comment by kooditoni** [comment]
> I am getting the same error 'The property "enableSoftDelete" must be set to true.' with Azure CLI 2.5.1
> If i remove --enable-soft-delete from the command I still get the error even tho it is suppose to default to true.
> If i specifically set it to true I can continue with my deployment. "--enable-soft-delete true"

If you run the `az keyvaylt create` command with `--debug`, you can see that the JSON payload that the command send to the REST API does not contain the property *enableSoftDelete* and it **does** contain the property *softDeleteRetentionInDays*.

It actually might be that the REST API does not respect the contract anymore. According to the the REST API [documentation](https://docs.microsoft.com/en-us/rest/api/keyvault/vaults/createorupdate#vaultproperties), *enableSoftDelete* should be defaulted to true in the API itself. And I would think that *softDeleteRetentionInDays* wouldn't matter at all if the enableSoftDelete is set to false.

**Comment by Pwd9000-ML** [comment]
Same issue here.
Had to change some of my Terraform (local-exec provisioners) that uses this CLI to --enable-soft-delete true because all my pipelines were starting to fail :( because the false value did not allow the CLI to execute with error "The property "enableSoftDelete" must be set to true."

This is an issue for me because I create and destroy lots of keyvaults (sometimes with the same name hence soft delete is not required) now I have to incorporate a purge in addition to my code base to accommodate this value being set to true

**Comment by the-vampiire** [comment]
> > to follow up. the keyvault never gets created but i am getting a "The name 'test-key-vault' is already in use."
> > nothing appears under `az keyvault list` nor `az keyvault list-deleted`. it also does not exist on the azure console so this is not a CLI-only issue. idk if this is related but something odd is happening with az keyvault.
> 
> The KeyVault name must be global unique, therefore you can assume that the name is already used by other users.

ah thank you. i thought it was just unique within a subscription but that makes sense now that i look at it given that it is used as a subdomain.

**Comment by danielbecroft** [comment]
I'm seeing the same failures when running the `azure-cli` docker image (which `az --version` resolves as 2.5.1).

I'm not seeing the errors on older versions of the CLI (specifically 2.0.80 was tested). The vault gets created correctly, and the `enableSoftDelete` flag is set appropriately based on the command line parameter.

**Comment by danielbecroft** [comment]
I've gone back through all the versions of the `az cli` release. The `az keyvault create` command works correctly under the `azure-cli:2.2.0` image, but fails under `azure-cli:2.3.0` and later.

**Comment by gregorybleiker** [comment]
6 days and this bug which essentially stops people from creating keyvaults with the cli is not fixed...

**Comment by flytzen** [comment]
@gregorybleiker You can create a key vault if you include --enable-soft-delete true. That gives the same result as *omitting that* parameter used to do.

**Comment by flytzen** [comment]
This looks suspiciously similar to #13100. Is there something systemic that happened in the latest release?

**Comment by einko** [comment]
> @gregorybleiker You can create a key vault if you include `--enable-soft-delete true`. That gives the same result as _omitting_ that parameter used to do.

but it is not working for `--enable-soft-delete false` so it is not a solution / workaround.

**Comment by gregorybleiker** [comment]
@einko exactly... soft delete is a very intrusive feature (and certainly not wished for in my scenario), that's why I want to create a keyvault without soft delete (which I can't via cli atm).

**Comment by bim-msft** [comment]
Some regions are broken:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/3250203/81146880-bd84d480-8fab-11ea-8c69-f7164eef785f.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/3250203/81146902-ca092d00-8fab-11ea-9644-8cbfbc61352f.png)

@kooditoni This is due to a service side error, all CLI versions/platforms are affected, they are fixing this. No big change on CLI side around soft-delete parameter recently.

**Comment by wolszakp** [comment]
@bim-msft How to workaround this issue? I am working with `westeurope` mainly. Change region for current my deployment is not an option for me.

**Comment by jlichwa** [comment]
> @bim-msft How to workaround this issue? I am working with `westeurope` mainly. Change region for current my deployment is not an option for me.

It should work now. I just tested in this region.

**Comment by nenad1002** [comment]
It works for westeurope, but it doesn't for eastus for example.

**Comment by nenad1002** [comment]
> > @bim-msft How to workaround this issue? I am working with `westeurope` mainly. Change region for current my deployment is not an option for me.
> 
> It should work now. I just tested in this region.

It works for westeurope, but it doesn't for eastus for example.

**Comment by wolszakp** [comment]
Thanks @jlichwa. I've just verified `westeurope` and it works.

**Comment by jlichwa** [comment]
#please-close

**Comment by cdelacruzpinto** [comment]
I still get this error for northeurope.
