### ISSUE TITLE
Insert space after # in block comments of the file headers

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1324]
This is today's copyright header“
```
#---------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#---------------------------------------------------------------------------------------------
```
There isn't a space between the `-` and `#`. It is not recommended in [PEP8](https://www.python.org/dev/peps/pep-0008/#block-comments). Errors are reported in PyCharm and other editors if PEP8 is enabled.

The files can be updated together in one batch automatically.

**Comment by tjprescott** [comment]
There's a script that puts the headers in each file. It might be as simple as updating that and rerunning (or that might just result in appending the new correct header, which would not be good).
