### ISSUE TITLE
`az resource tag`  against a 'microsoft.containerregistry/registries/webhooks' resource failed with `missing property ServiceUri`

### ISSUE THREAD

**Issue by DoPaNik** [Azure/azure-cli#13255]
## Describe the bug

When running `az resource tag` against `microsoft.containerregistry/registries/webhooks` resource, the command fails with 'Missing property ServiceUri ...' message.

**Command Name**
`az resource tag`

**Errors:**
```
Missing property ServiceUri for the operation against the resource with name  vsts982561name
```

## To Reproduce:
Run:
```az resource tag --tags {} {} {} {} {} --id {}```

## Expected Behavior
The resource ('microsoft.containerregistry/registries/webhooks') with the specified id gets attached tags

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.5.0

Extensions:
azure-devops 1.12.0
resource-graph 1.0.0

```

**Comment by yonzhan** [comment]
add to S170
