### ISSUE TITLE
Service Principal cache file not getting generated when using az aks create

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [Azure/azure-cli#13252]
## Describe the bug
I am using azure-cli through Powershell using Terminal. According to docs and other issues, when I trigger `az aks create...`, I expected a `~\.azure\aksServicePrincipal.json` file but none is created. Thus everytime I create a cluster, a new service principle is generated in Azure AD.
**Command Name**
`az aks create`

**Errors:**
None. Except the cache file is not created.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --enable-addons {} --ssh-key-value {} --kubernetes-version {} --node-vm-size {} --node-count {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.0

```
## Additional Context
1. Using Powershell 5
2. Tested with Terminal, Powershell, cmd both with and without admin privileges.

**Comment by yonzhan** [comment]
aks

**Comment by yungezz** [comment]
routing to aks team

**Comment by bpdohall** [comment]
@SayakMukhopadhyay - to mitigate this issue, you can first explicitly create the service principal:
`az ad sp create-for-rbac --skip-assignment --name {}` 
Then pass the app-id and password in to your `az aks create` command via parameters `--service-principal` and `--client-secret`

**Comment by SayakMukhopadhyay** [comment]
Yeah, I am aware of this, In fact I am using a managed identity for now.

**Comment by Jen7714** [comment]
Looks like this answer was addressed above, so closing this issue.

**Comment by SayakMukhopadhyay** [comment]
Hi @Jen7714 
The workaround given above does not solve this issue so I dont think this issue should be closed. The CLI and the docs clearly states that on not supplying a service principle, one is created and is cached locally. This local caching is not happening.
