### ISSUE TITLE
az resource update fails with 'too many 502 error responses'

### ISSUE THREAD

**Issue by DoPaNik** [Azure/azure-cli#13250]
## Describe the bug
When running `az resource update` against `microsoft.insights/scheduledqueryrules` resource, the command fails with 'too many 502 error responses' message.

**Command Name**
`az resource update`
or
`az resource tag`

**Errors:**
For `azure resource update --set tags...`:
```
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/92e6488d-d172-4ec5-b17f-e2a433bd82cd/resourceGroups/testece/providers/microsoft.insights/scheduledqueryrules/mmeum-analytics-workspace-testece%7C1c569eaf-4df3-4ea0-bc66-a94d89ebadba%7Ca8bc2709-2085-40ba-91f3-fb1f09930f52%7C18b38cc9-c2fc-41bd-baf1-c964b55a7549?api-version=2018-04-16 (Caused by ResponseError('too many 502 error responses'))
```

For `azure resource tag --tags...`:
```
The tag names 'hidden-link:/subscriptions/92e6488d-d172-4ec5-b17f-e2a433bd82cd/resourceGroups/testece/providers/Microsoft.OperationalInsights/workspaces/mmeum-analytics-workspace-testece' have reserved characters '<,>,%,&,\,?,/' or control characters. These characters are only allowed for tags that start with the prefix 'hidden, link'.
```

## To Reproduce:
Run 
```
        az resource update --set tags.'key'='owner' --id myResourceId
```

or run
```
       az resource tag --tags $oldTagsFromResource key=value --id myResourceId
```

## Expected Behavior
The tag is added to the resource.
`az resource tag --tags` does not work because the `hidden-link` tag cannot be set over cli due to special characters ... 

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.5.0

Extensions:
azure-devops 1.12.0
resource-graph 1.0.0

```

**Comment by yonzhan** [comment]
add to S170

**Comment by yungezz** [comment]
resource

**Comment by zhoxing-ms** [comment]
@DoPaNik Hi, I can't reproduce your problem. Could you please email me the specific parameters of the command you executed? My email address is Zhou.Xing@microsoft.com

**Comment by DoPaNik** [comment]
@zhoxing-ms Hi, mail just went out to you

**Comment by zhoxing-ms** [comment]
@DoPaNik Thanks for your email. I used the tag parameters in the email and still could not reproduce the problem. Could you please add `--debug` to the original command and send me the printed message?

**Comment by zhoxing-ms** [comment]
@DoPaNik Thanks for the debug log you provided, my investigation of the two problems is as follows:

1. The problem of `az resource tag --tags`
The prefix of parameter `--tags` is `\n  hidden-link:/subscriptions/...`, `\` and `/` is  is a restricted character in the tag resource, so the tag name cannot be used. Doc link: [tag-resources#limitations](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources#limitations)
In addition, according to my test, `/` can be used when the tag starts with `hidden-link:/` or `link:/`, but I haven't found the relevant documents. So we need the service team to confirm to see if it meets the expectation.
@DoPaNik May I ask why do you need the `\n  ` at the beginning of `\n  hidden-link:/subscriptions/...`? Could you delete the `\n  ` from the tag ? If so, then you can use it as the tag name.

2. The problem of `resource update --set`
This is a problem of service. We need to wait for someone from the service team to intervene in the troubleshooting, and then we can send the parameters to him.
@DoPaNik For this problem, Could you find the relevant records from the Activity log on portal and get the corresponding correlationId?

**Comment by DoPaNik** [comment]
Hi @zhoxing-ms 
 
thank you very much for the quick feedback:

First of all, thank you for pointing out that I didn't even notice the character `\n`. Now that I have changed this, I get the same error as described by 2:

`request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/.../resourceGroups/.../providers/microsoft.insights/scheduledqueryrules/...analytics-workspace-...?api-version=2018-04-16 (Caused by ResponseError('too many 502 error responses'))`

to 2.
Yes I was able to find the entries in the activity log. Here the corresponding correlationId: **3a8df5bf-325e-44c4-ae8d-7f5a4741636f**

**Comment by zhoxing-ms** [comment]
> request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/.../resourceGroups/.../providers/microsoft.insights/scheduledqueryrules/...analytics-workspace-...?api-version=2018-04-16 (Caused by ResponseError('too many 502 error responses'))

@DoPaNik Thanks for your feedback, this is a service problem, and I can't reproduce it in my side.

Could you please provide the correlationId when the `too many 502 error responses` error occurs after the `\n hidden-link:/subscriptions/...` is changed to `hidden-link:/subscriptions/...`?

**Comment by zhoxing-ms** [comment]
@ifeoluwaokunoren Could you please help to triage this issue?

**Comment by DoPaNik** [comment]
@zhoxing-ms Here the correlationId: **215c02ae-e56b-4b32-995b-f24b19a89699**

**Comment by zhoxing-ms** [comment]
> 3a8df5bf-325e-44c4-ae8d-7f5a4741636f
> 215c02ae-e56b-4b32-995b-f24b19a89699

@DoPaNik Thanks, the two correlationIds will be provided to the service team for troubleshooting.
