### ISSUE TITLE
Creating NIC in the VNET from different subscription

### ISSUE THREAD

**Issue by kosinsky** [Azure/azure-cli#13258]
This doc says: "If you want to use an **existing subnet in other** resource group or **subscription**, please provide the ID instead of the name of the subnet." That assumes that I can create NIC using VNET from different subscription. 
However, https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-network-interface#create-a-network-interface says: "Before creating a network interface, you must have an existing **virtual network in the same** location and **subscription you create a network interface in.**"

Which one is true? Is it supported scenario? So far I'm getting following error:
"Resource /subscriptions/&lt;subscription id for vnet&gt;/resourceGroups/&lt;rg&gt;&gt;/providers/Microsoft.Network/virtualNetworks/Test1/subnets/default referenced by resource /subscriptions/&lt;subscription id for NIC&gt;/resourceGroups/VNet-Demo/providers/Microsoft.Network/networkInterfaces/Nic1 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region." that just says about region.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29b6bb22-cb91-c7f8-995e-134d0fe5627f
* Version Independent ID: a92f24e8-36a0-808b-a9e7-598f85560b0f
* Content: [az network nic](https://docs.microsoft.com/en-us/cli/azure/network/nic?view=azure-cli-latest#az-network-nic-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @MyronFanQiu could you pls have a look

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
@kosinsky official doc is correct. https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-network-interface#create-a-network-interface. `subnet` is a general resource used in all network commands. Some commands support the cross-subs scenario and some don't.

**Comment by kosinsky** [comment]
To summarize it's possible to assign cross-subs vnet via az command, but not possible via the portal. Am I correct?

If yes, from error above looks like az command still doesn't work even docs say it should.

**Comment by MyronFanQiu** [comment]
@kosinsky No. We cannot assign cross-subs vnet for `az network nic create`. But we can assign cross-subs vnet for part of az commands. It depends on the server side. Since `--subnet` is a common resource across many Azure resources, it share same help message. That's why in `az network nic create` we have a misleading help message. The doc in azure cli is not accurate for `az network nic create`.
