### ISSUE TITLE
az webapp up failing when RG needs to be created

### ISSUE THREAD

**Issue by btardif** [Azure/azure-cli#13257]
![image](https://user-images.githubusercontent.com/4119816/80642230-f86e9180-8a1a-11ea-9127-2ce0204c7c8f.png)

When trying to create an app by passing in minimum parameters resource group creation fails since it's missing location, this should be implied from app service defaults.

This works when I pass in location parameter however location parameter should not be required.

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by panchagnula** [comment]
@Kotasudhakarreddy this seems like a regression from the latest change you made - can you take a look so we can get this in for //BUILD release plus add a test case for this as well? Thank you.

**Comment by Kotasudhakarreddy** [comment]
@panchagnula - I am unable to repro the issue reported. Please find the details below.

**Able to deploy the site with minimal parameters.** 

![image](https://user-images.githubusercontent.com/60102891/80786657-ebc87580-8ba1-11ea-8909-54d49cc952a5.png)

**able to browse the deployed site** 

![image](https://user-images.githubusercontent.com/60102891/80786732-25997c00-8ba2-11ea-8644-13551e4c6c9b.png)

**Able to redeploy the site with minimal parameters as well.**

![image](https://user-images.githubusercontent.com/60102891/80786841-6abdae00-8ba2-11ea-8648-b63bf12f8959.png)

**Comment by Kotasudhakarreddy** [comment]
@panchagnula - can you please get the `--debug` logs from the reported user.

**Comment by panchagnula** [comment]
@Kotasudhakarreddy thanks for the quick debugging here. I will add you to email with Byron on this. one more thing to check on your end is can you see if you have local/global context values set. open the folder Git13257Issue above and check if there is a .azure folder with a file that saves the RG, location & other values set. Just delete this folder and re-try & see if you repro it.

**Comment by btardif** [comment]
@Kotasudhakarreddy please try the repro without having the localcontext set (.azure dir)

I can repro this at will :

![2020-05-01_20h59_49](https://user-images.githubusercontent.com/4119816/80854700-2a385180-8bef-11ea-8de0-33fc8ce4ecc3.gif)

**Comment by Kotasudhakarreddy** [comment]
@btardif - thanks for providing -debug log. Yes I am able to repro the issue after removing local context. I am analysing further to figure out the root cause.

**Comment by panchagnula** [comment]
@Kotasudhakarreddy thanks for debugging this. @btardif  this was not really a regression with Kota's previous but a bug that existed but never surfaced until now because the we always used an existing RG instead of creating a new one and the existing test cases never handled this either.
