### ISSUE TITLE
After create a webapp with container image

### ISSUE THREAD

**Issue by rloreto** [Azure/azure-cli#13254]
## Describe the bug

**Command Name**
`az webapp config container set`

**Errors:**
```
'NoneType' object has no attribute 'reserved'
Traceback (most recent call last):
Temp\pip-install-ygnynjtx\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 560, in execute
azure\cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 611, in _run_job
Local\Temp\pip-install-ygnynjtx\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 588, in _run_job
azure\cli\core\commands\__init__.py, ln 297, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 461, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 871, in update_container_settings
azure\cli\command_modules\appservice\custom.py, ln 628, in _add_fx_version
AttributeError: 'NoneType' object has no attribute 'reserved'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config container set --name {} --resource-group {} --docker-custom-image-name {} --docker-registry-server-url {} --docker-registry-server-user {} --docker-registry-server-password {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.66 *

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@rloreto can you give more details here by running command with --debug,

the error seems like its happening because the app being used here is not a linux app ('reserved' is a property set on Linux apps) or the app name used in the command are incorrect.

**Comment by panchagnula** [comment]
closing this due to lack of response. Please try with the latest CLI version and create new bug if you still see this issue with --debug information.
