### ISSUE TITLE
Update az webapp list-runtimes to use static list until new Available Stacks API is available

### ISSUE THREAD

**Issue by btardif** [Azure/azure-cli#13261]
- `az webapp list-runtimes` depends on the available stacks API
  - Available stacks API is updated with Antares deployments
  - Antares deployments are infrequent and don't line up with stacks EOL schedule.
- There are bugs in existing **Available Stacks API** around **LTS** and **Current** decorations
  - See `"DOTNETCORE|LTS"` and `"DOTNETCORE|Latest"`

### Hide-Windows

- "node|0.6",
- "node|0.8",
- "node|0.10",
- "node|0.12",
- "node|4.8",
- "node|6.5",
- "node|6.9",
- "node|6.12",
- "node|7.10",
- "node|8.1",
- "node|8.4",
- "node|8.5",
- "node|8.9",
- "node|8.10",
- "node|8.11",
- "php|5.6",
- "python|2.7",

### Add-Windows

- "DOTNETCORE|2.1",
- "DOTNETCORE|3.1",

### Expected results

``` bash

az webapp list-runtimes
[
  "aspnet|V4.7",
  "aspnet|V3.5",
  "DOTNETCORE|2.1",
  "DOTNETCORE|3.1",
  "node|10.0",
  "node|10.6",
  "node|10.14",
  "node|10.15",
  "php|7.2",
  "php|7.3",
  "php|7.4",
  "python|3.6",
  "java|1.7|Tomcat|7.0",
  "java|1.7|Tomcat|8.0",
  "java|1.7|Tomcat|8.5",
  "java|1.7|Tomcat|9.0",
  "java|1.7|Jetty|9.1",
  "java|1.7|Jetty|9.3",
  "java|1.7|Java SE|8",
  "java|1.8|Tomcat|7.0",
  "java|1.8|Tomcat|8.0",
  "java|1.8|Tomcat|8.5",
  "java|1.8|Tomcat|9.0",
  "java|1.8|Jetty|9.1",
  "java|1.8|Jetty|9.3",
  "java|1.8|Java SE|8",
  "java|11|Tomcat|7.0",
  "java|11|Tomcat|8.0",
  "java|11|Tomcat|8.5",
  "java|11|Tomcat|9.0",
  "java|11|Jetty|9.1",
  "java|11|Jetty|9.3",
  "java|11|Java SE|8"
]
```

### Hide-Linux

- "RUBY|2.4.5",
- "RUBY|2.3.8",
- "NODE|lts",
- "NODE|8-lts",
- "NODE|6-lts",
- "NODE|4.4",
- "NODE|4.5",
- "NODE|4.8",
- "NODE|6.2",
- "NODE|6.6",
- "NODE|6.9",
- "NODE|6.10",
- "NODE|6.11",
- "NODE|8.0",
- "NODE|8.1",
- "NODE|8.2",
- "NODE|8.8",
- "NODE|8.9",
- "NODE|8.11",
- "NODE|8.12",
- "NODE|9.4",
- "PHP|5.6",
- "DOTNETCORE|1.0",
- "DOTNETCORE|1.1",
- "DOTNETCORE|2.0",
- "DOTNETCORE|2.2",
- "DOTNETCORE|3.0",
- "DOTNETCORE|LTS",
- "DOTNETCORE|Latest",
- "WILDFLY|14-jre8",
- "PYTHON|2.7"

### Add-Linux

- "DOTNETCORE|3.1",

### Expected Results Linux

``` bash
az webapp list-runtimes --linux

[

  "DOTNETCORE|2.1",
  "DOTNETCORE|3.1",
  "NODE|12-lts",
  "NODE|10-lts",
  "NODE|10.1",
  "NODE|10.10",
  "NODE|10.12",
  "NODE|10.14",
  "NODE|10.16",
  "NODE|12.9",
  "JAVA|8-jre8",
  "JAVA|11-java11",
  "TOMCAT|8.5-jre8",
  "TOMCAT|9.0-jre8",
  "TOMCAT|8.5-java11",
  "TOMCAT|9.0-java11",
  "PHP|7.2",
  "PHP|7.3",
  "PYTHON|3.8",
  "PYTHON|3.7",
  "PYTHON|3.6",
  "RUBY|2.5.5",
  "RUBY|2.6.2",
]
```

**Comment by yonzhan** [comment]
webapp

**Comment by ThejaChoudary** [comment]
Unable to repro the Issue.

**Comment by panchagnula** [comment]
@ThejaChoudary we need to temporarily change our support to return a hard coded list of values instead of using the API to return the list of supported runtimes.

**Comment by cgreene87** [comment]
Is this not considered a breaking change? We lost quite a bit of time trying to figure out why our pipelines _randomly_ stopped working. The issue was compounded because the CLI silently updated to 2.9.1. 

Our pipeline was using `"DOTNETCORE|Latest"`; I would have thought the whole point of using something like `Latest` is that it protects you from the removal of hard coded version numbers. `Latest` should just alias to the `"DOTNETCORE|3.1"`

**Comment by calvinsID** [comment]
@cgreene87 Sorry for the inconvenience this caused. @btardif can you chime in on whether `Latest` should alias to `DOTNETCORE|3.1`?

**Comment by btardif** [comment]
"Latest" was a bug in the API and should not be used. It's ambiguous and can cause problems for apps.

**Comment by cgreene87** [comment]
All good, if it's causing bugs. However, should these changes be marked as breaking? Since it will break people builds if they are using values that don't match the available list?
