### ISSUE TITLE
basic az list commands (and others) failing

### ISSUE THREAD

**Issue by briandmaher** [Azure/azure-cli#13264]
## Describe the bug

**Command Name**
`az resource list`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 688, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az resource list -o {}`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by yungezz** [comment]
hi @briandmaher just to confirm, did you run `azure cli` inside CloudShell? thanks

**Comment by briandmaher** [comment]
Hi Yunge – that’s right, though the command was technically from inside a Windows Terminal/Azure Cloud session on my laptop & not via the cloud shell in the browser, technically. No issues running commands that way before.

Thanks,
Brian

________________________________

**Comment by yonzhan** [comment]
add to S170

**Comment by yungezz** [comment]
hi @briandmaher this is not azure cli issue, duplicate https://github.com/Azure/azure-cli/issues/13226. it's a known issue of Cloud Shell. Similar to #11749 (comment)
To solve it, please use Azure CLI on a local machine or run az login in Cloud Shell and retry the command

**Comment by briandmaher** [comment]
Actually, I think this issue is resolved (authentication problem likely related to my Pay-As-You-Go and Learning/Sandbox environments timing out..)

________________________________
