### ISSUE TITLE
Severity explanation incorrect

### ISSUE THREAD

**Issue by ade-nz** [Azure/azure-cli#13262]
The Azure CLI command reference says "Severity of the alert from 0 (low) to 4 (high)" but the Alerts Overview information on https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-overview indicates "...0 (critical) to 4 (verbose)".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d97968df-72c9-e50c-d5b1-54562c1bdef7
* Version Independent ID: 0cde4f15-6464-3106-b787-3ee37c7de0ee
* Content: [az monitor metrics alert](https://docs.microsoft.com/en-us/cli/azure/monitor/metrics/alert?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @MyronFanQiu could you pls have a look? thanks

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
@ade-nz Thanks for reporting this. official doc should be the source of truth. https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-overview We will refine the help message.

**Comment by MyronFanQiu** [comment]
This issue has been fixed by https://github.com/Azure/azure-cli/pull/13512
