### ISSUE TITLE
`az vm list-skus` table format column "restrictions" has ambiguity

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#13271]
**Is your feature request related to a problem? Please describe.**

Table format:
```
ResourceType     Locations    Name            Zones    Restrictions
---------------  -----------  --------------  -------  ---------------------------
virtualMachines  westus2      Standard_M128s  2,3      NotAvailableForSubscription
```
However, it is only not available in zone 1.
```
"restrictions": [
      {
        "reasonCode": "NotAvailableForSubscription",
        "restrictionInfo": {
          "locations": [
            "westus2"
          ],
          "zones": [
            "1"
          ]
        },
        "type": "Zone",
        "values": [
          "westus2"
        ]
      }
    ],
```

**Describe the solution you'd like**

Please make table output accurate.

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Compute

**Comment by qwordy** [comment]
`az vm list-skus` does not have restrictions now. All skus' restriction fields are empty arrays.

**Comment by qwordy** [comment]
Another user's feedback:
The command used is “az vm list-skus” where the restricted SKUs are not listed as designed. Though, this command has the “--all” parameter which will list all the SKUs regardless of any restrictions imposed.
Even with a restriction to a single Zone, without the “--all” parameter, those sizes won’t be listed by simply running “az vm list-skus”.

The customer’s challenge in CLI command is very similar to what observed with the “Get-AzComputeResourceSku”. This when using the “—output table” for a better formatting.
Sample:
az vm list-skus --size Standard_M64ls --location westeurope --all -o table
```
ResourceType     Locations    Name            Zones    Restrictions
---------------  -----------  --------------  -------  ---------------------------
virtualMachines  westeurope   Standard_M64ls  1,2,3    NotAvailableForSubscription
```
