### ISSUE TITLE
How do I set the cache option for OS disks?

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-cli#13278]
Looks like the OS disk is created with read-only cache. Why not read/write and how can a VMSS be created with read/write OS disk cache?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0408c294-207a-2b72-7b93-e09121602b75
* Version Independent ID: 852cb67b-70c6-b811-3b0a-5d5b84b8a911
* Content: [az vmss](https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
HI @qwordy could you pls have a look?

**Comment by qwordy** [comment]
```
--os-disk-caching

Storage caching type for the VM OS disk. Default: ReadWrite.
accepted values: None, ReadOnly, ReadWrite
```
Looks like the default value is ReadWrite.
I create a vmss using the default configuration.
I get 
```
"osDisk": {
          "caching": "ReadWrite",
          "createOption": "FromImage",
          "diskSizeGB": 30,
          "managedDisk": {
            "storageAccountType": "Premium_LRS"
          }
        }
```
Would you share your command?

**Comment by qwordy** [comment]
Hi @letmaik ?

**Comment by qwordy** [comment]
@letmaik

**Comment by letmaik** [comment]
Sorry, I missed this somehow. I think you're right. Thanks for pointing me to the `--os-disk-caching` flag.
