### ISSUE TITLE
Cannot set cors in file service storage

### ISSUE THREAD

**Issue by droplet-tech** [Azure/azure-cli#13288]
## Describe the bug

**Command Name**
`az storage cors clear --services f` or `az storage cors list` 

**Errors:**
```
'NoneType' object has no attribute 'body'
Traceback (most recent call last):
storage/v2018_03_28/common/storageclient.py, ln 252, in _perform_request
    self.authentication.sign_request(request)
storage/v2018_03_28/common/_auth.py, ln 78, in sign_request
    self._add_authorization_header(request, string_to_sign)
storage/v2018_03_28/common/_auth.py, ln 57, in _add_authorization_header
    signature = _sign_string(self.account_key, string_to_sign)
storage/v2018_03_28/common/_common_conversion.py, ln 91, in _sign_string
    key = _decode_base64_to_bytes(key)
...
binascii.Error: Invalid base64-encoded string: number of data characters (77) cannot be 1 more than a multiple of 4


storage/v2018_03_28/common/retry.py, ln 154, in _retry
    if hasattr(context.request.body, 'read'):
AttributeError: 'NoneType' object has no attribute 'body'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage cors clear --services f`

## Environment Summary
```
Darwin-19.4.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.64 *

```

**Comment by yonzhan** [comment]
add to S170

**Comment by Juliehzl** [comment]
Hi @droplet-tech, I am trying to reproduce your issue. But I cannot reproduce it with azure cli 2.6.0 installed. Could you try to upgrade your azure cli version according to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest or provide debug information with`--debug` in your command to help figure out root cause in your scenario?
