### ISSUE TITLE
Webapp:Unable to install the EntityFrameworkCore.InMemory as part of the Create a Web API Tutorial

### ISSUE THREAD

**Issue by thomasdavidneal** [Azure/azure-cli#13281]
## Describe the bug
Unable to install the EntityFrameworkCore.InMemory as part of the Create a Web API Tutorial

**Command Name**
dotnet add package Microsoft.EntityFrameworkCore.InMemory

**Errors:**
  Writing /tmp/tmpTcyjJa.tmp
info : Adding PackageReference for package 'Microsoft.EntityFrameworkCore.InMemory' into project '/home/thomasdavidnealdev/contoso-pets2/src/ContosoPets.Api/ContosoPets.Api.csproj'.
info : Restoring packages for /home/thomasdavidnealdev/contoso-pets2/src/ContosoPets.Api/ContosoPets.Api.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.inmemory/index.json
error: Root element is missing.

## To Reproduce:
I have no idea what is causing this issue so I have no idea how to reproduce it.

- _Put any pre-requisite steps here..._
Take the basic tutorial?
- ``

## Expected Behavior
I am assuming that it should install the package. This is really my first foray into C# API building or Azure, so far not great.

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by yungezz** [comment]
hi @thomasdavidneal could you pls share your repo steps for trouble shooting? Are you using azure cli in cloudshell? Are you trying to setup a .NET webapp?

**Comment by thomasdavidneal** [comment]
I am following the below learning module:
https://docs.microsoft.com/en-us/learn/modules/build-web-api-net-core/
When I get to unit three were it asks to run the following command:
`dotnet add package Microsoft.EntityFrameworkCore.InMemory`
it returns the error listed in the initial issue. I have removed the directory created in the first unit and retried. I have changed the name of the directory. Nothing works. This is performed in the in page Azure Cloud Shell.

**Comment by btardif** [comment]
@panchagnula can this be closed?

**Comment by panchagnula** [comment]
@btardif Kota & Theja are taking care of triage - and they will verify and close accordingly. Thanks for checking

**Comment by panchagnula** [comment]
@btardif this doesn't seem to have anything to do with CLI - the question is on this step dotnet add package Microsoft.EntityFrameworkCore.InMemory 

Please help route this?

**Comment by btardif** [comment]
This is not an issue with App Service CLI
