### ISSUE TITLE
Unable to register custom model when filesize ~>250MB

### ISSUE THREAD

**Issue by krishnakarthi** [Azure/azure-cli#13289]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I have custom trainned model, which file size is ~250 MB. When i try to register the model i'm getting below error.
It would be highly appreciated if you help on this issue

**To Reproduce**

model = Model.register(model_path = "trainedModel.h5",
                       model_name = "mycustomModel",
                       description = "mycustomModel",
                       workspace = ws)
ERROR :
WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError("(10053, 'WSAECONNABORTED')"))': /azureml/LocalUpload/200501T164820-c78f74a7/Covid_Final_Best_model.h5?sv=2019-02-02&sr=b&sig=PUcjiw9F0iNWJSKEsel8cjhaBlMHKCn6ueYefonbH%2Fc%3D&st=2020-05-01T11%3A08%3A25Z&se=2020-05-02T11%3A18%3A25Z&sp=rcw&comp=block&blockid=TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQXdNRFF4T1RRek1EUSUzRA%3D%3D&timeout=30

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
@krishnakarthi  was this related to Azure CLI?

**Comment by lostmygithubaccount** [comment]
hi @krishnakarthi are you still facing this issue?

**Comment by swatig007** [comment]
closing due to no response
