### ISSUE TITLE
webapp:runtime not supported

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-cli#13282]
When running `az webapp create` with `--runtime="node|10.0"` or  `--runtime="node|10.15"` an error occurs on CLI.

```bash 
Linux Runtime 'node|10.0' is not supported.Please invoke 'list-runtimes' to cross check
```
So far I have not found any that work on --is-linux app service plan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by awentzel** [comment]
I resolved this issue by explicitly `list-runtimes` with the `--is-linux` argument.  So by running `az webapp create --is-linux --list-runtimes` the correct list of runtimes is displayed.  Selecting these works on Linux machines.  

I do think that where runtimes for Windows and Linux match, they should be the same casing, same name, and work across platforms.  Currently, when listing runtimes on Windows they are same format but lowercase.  On Linux they are same format `runtime|version` but in all caps.  In this case when creating web app the casing does matter.

**Comment by panchagnula** [comment]
@calvinsID  can you take a look at this -did your changes to runtime not fix this?

**Comment by calvinsID** [comment]
Hi @awentzel, the --runtime parameter in `az webapp create` is not case sensitive, so it should work the same regardless if it is upper or lower case. In your use case, node|10.0 and node|10.15 are not supported for linux, as shown by `az webapp list-runtimes --linux` which is why you're receiving the error. The only node runtime currently supported by both windows and linux is node|10.14

**Comment by calvinsID** [comment]
I can update the error message to clarify that for linux apps, the list-runtimes command should be used with flag --linux: `Linux Runtime 'node|10.0' is not supported. Please invoke 'az webapp list-runtimes --linux' to cross check`
