### ISSUE TITLE
az postgres server create/update - no support "InfrastructureEncryption" REST API parameter

### ISSUE THREAD

**Issue by fabiendelpierre** [Azure/azure-cli#13297]
The Azure Resource Manager provider for Terraform recently (in v2.7.0) added support for an argument called `infrastructure_encryption_enabled`, which I assume corresponds to the `InfrastructureEncryption` parameter of the REST API (reference [here](https://docs.microsoft.com/en-us/rest/api/postgresql/servers/create#infrastructureencryption)).

Unfortunately it does not appear that this particular setting is supported by the Azure CLI, as I do not see it listed in the help for `az postgres server create` or `az postgres server update`.

On a related note, I was unable to find any info whatsoever on what this setting actually does. Azure claims all the storage for their database services is already backed by AES 256 encryption that cannot be disabled, so I would love to get additional clarity on what `InfrastructureEncryption` does on top.

**Comment by bquantump** [comment]
Thank you for your request and question @fabiendelpierre. @yungezz it looks like the swagger supports this, can we add this as a feature?

**Comment by bquantump** [comment]
@shinilm can you provide more information on what the InfrastructureEncryption  does?

**Comment by fabiendelpierre** [comment]
I reached out to Azure support separately regarding the purpose of this new setting. Their response was that it's a new capability for Azure MySQL and Postgres databases, which adds a second layer of encryption using a different algorithm, protecting the data from compromise of the first algorithm.

They added that the feature is in development and will be rolled out in the coming months, and they recommend not using it at this time. 

So, given that, maybe it's not urgent to add it to Azure CLI since it might cause confusion among customers 😅 

(FWIW the feature caused me to waste most of my day trying to figure out what I was doing wrong with my Terraform code, until a process of elimination led me to determine I should leave that setting disabled.)

**Comment by yonzhan** [comment]
az postgres is currently taken care by postgres service team.

**Comment by rachel-msft** [comment]
@fabiendelpierre Our apologies for the inconvenient experience. We initially intended the full rollout to happen shortly after we released the CLI. However, that plan was interrupted causing the large time gap between the presence in the CLI and the functionality.
