### ISSUE TITLE
az ad app list: shows empty list, expected to display adb2c apps linked to the subscription

### ISSUE THREAD

**Issue by the-vampiire** [Azure/azure-cli#13296]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

i have created an adb2c directory and linked it to my subscription as per the docs. when (authed under the account with that subscription) i run `az ad app list` i get an empty list. i expected to see my adb2c app displayed. 

have also tried `az ad app show --id <adb2c app ID>` and told it doesnt exist.

**To Reproduce**

1. create adb2c directory
2. link to main account subscription
3. run `az ad app list` or `az ad app show --id <adb2c app ID>`

**Expected behavior**

view my adb2c (subscription linked) apps using the az cli

**Environment summary**

> powershell 7 core on win10

```ps
>  az --version
azure-cli                          2.3.1 *

command-modules-nspkg              2.0.3
core                               2.3.1 *
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-cli-ml                       1.3.0
```

**Comment by yonzhan** [comment]
@arrownj  please take a look

**Comment by arrownj** [comment]
Hi @the-vampiire , sorry for reply late. Could you please tell which document are your following ? As I know, `az ad app list` can only list applications, not a adb2c account. 

To create a application, you can just run `az ad app create`.

**Comment by the-vampiire** [comment]
@arrownj i have not seen a distinction between an AD app and an ADB2C app. documentation around these discusses them both as if they were the same (a general AD registered application). 

i was not trying to view the adb2c account but instead just interact with the registered applications within it. for example to update the redirect URI or manage scopes from the `az` CLI

**Comment by arrownj** [comment]
Hi @the-vampiire , you mean you create an app in ADB2C but can't list it with azure cli ? Could you please share us the reproduce steps ? How did you create the app ? If it can be list in portal enterprise applications page ?

**Comment by arrownj** [comment]
Hi @the-vampiire , I will close this issue first. If you still have problems, you can reopen it or submit a new one. Thanks
