### ISSUE TITLE
acs: remove dependencies on external command modules

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#1329]
Tracking:
For now, it depends on `azure-cli-vm` and `azure-cli-role` which we should remove as we expect each command module can be updated and published by itself. This involves 2 pieces of works
a.	Move all acs commands from ‘vm’ module to ‘acs’ module
b.	Move ‘create-for-rbac’ to a share utility module. This is under the impression that acs won’t get server side handle it in near future.

**Comment by vishrutshah** [comment]
This task has been completed and should be closed.
