### ISSUE TITLE
Webapp:az webapp deployment slot swap should support preserveVnet

### ISSUE THREAD

**Issue by seushermsft** [Azure/azure-cli#13291]
**Is your feature request related to a problem? Please describe.**

When swapping slots in an App Service via `az webapp deployment slot swap`, you can't specify preserve vnet.

**Describe the solution you'd like**

```bash
az webapp deployment slot swap  -g <rg_name> -n <appsvc_name> --slot staging --target-slot production --preserve-vnet=true
```

**Describe alternatives you've considered**

Alternatively, we can directly call the management API, use an existing language SDK, or use the Azure Devops App Service pipeline task, but would rather use azure-cli.

**Additional context**

**Comment by bquantump** [comment]
Thank you for your suggestion @seushermsft. @yungezz PS does/provides this, can we look into adding it?

**Comment by yonzhan** [comment]
webapp will be taken care by service team

**Comment by panchagnula** [comment]
we need to revamp our swap commands & we will address this as. a part of that work

**Comment by panchagnula** [comment]
@Kotasudhakarreddy / @ThejaChoudary can one of you take this up for the upcoming milestone?

**Comment by Kotasudhakarreddy** [comment]
Fix is given and will be released in next CLI update.
