### ISSUE TITLE
az group show and az group show not returning me resource group id(GUID format)

### ISSUE THREAD

**Issue by csharpdocs** [Azure/azure-cli#13292]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I need newly created resource group id(guid) to set scope of new service principal using cli command to restrict to resource group of subscription.

$newResourceGroup = $(az group create ...) | ConvertFrom-Json
$$newResourceGroupId = $newResourceGroup.ResourceGroupId(here is bug.. i want GUID)
$newServicePrincipal = $(az ad sp create-for-rbac -- name "somename" --scopes "/subscriptions/$SubscriptionId/resourceGroups/$newResourceGroupId"

**To Reproduce**

Create Resource Group using cli command
Create Service principal with scope to resource group created follow below code

$newResourceGroup = $(az group create ...) | ConvertFrom-Json
$$newResourceGroupId = $newResourceGroup.ResourceGroupId(here is bug.. i want **GUID**)
$newServicePrincipal = $(az ad sp create-for-rbac -- name "somename" --scopes "/subscriptions/$SubscriptionId/resourceGroups/$newResourceGroupId"

**id         : /subscriptions/{sub id}/resourceGroups/rg-sampletest-t-weu**
location   : westeurope
managedBy  : 
name       : rg-sampletest-t-weu
properties : @{provisioningState=Succeeded}
tags       : @{Department= My Department; Environment= My Environment; Purpose= My Reason}
type       : Microsoft.Resources/resourceGroups

see in above output resource group guid is not present

**Expected behavior**
It should also return **GUID** of newly created resource group using cli command

**Environment summary**
Latest CLI command. ran on powershell command prompt

**Additional context**
NA

**Comment by bquantump** [comment]
Thank you for your question @csharpdoc. @yungezz can you take a look?

**Comment by yonzhan** [comment]
add to S170

**Comment by zhoxing-ms** [comment]
@csharpdocs Hi, may I ask why do you need GUID?
In fact, the `--scopes` parameter of command `az ad sp create-for-rbac` is passed directly by resource group id, so we can append `--query "id"` to the command `az group create -l westus -n zhoxing-test` to get the resource group id.

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
