### ISSUE TITLE
Submitting an image configuration to the VM Image Builder service in Azure Cloud Shell fails.

### ISSUE THREAD

**Issue by sirredbeard** [Azure/azure-cli#13298]
![image](https://user-images.githubusercontent.com/33820650/80840522-838e8980-8bcb-11ea-9fc3-a98aeeccec1f.png)

## Describe the bug

Submitting an image configuration to the VM Image Builder service in Azure Cloud Shell [per documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/image-builder#create-the-image):

```
az resource create \
    --resource-group $imageResourceGroup \
    --properties @helloImageTemplateWin.json \
    --is-full-object \
    --resource-type Microsoft.VirtualMachineImages/imageTemplates \
    -n helloImageTemplateWin01
```

Fails with a cryptic message:

```
location of the resource is required
```

Even when --location is specified:

```
az resource create \
    --resource-group $imageResourceGroup \
    --properties @helloImageTemplateWin.json \
    --is-full-object \
    --resource-type Microsoft.VirtualMachineImages/imageTemplates \
    -n helloImageTemplateWin01
    --location $location
```

**Command Name**
`az resource create`

**Errors:**
```
location of the resource is required
```

I cannot find reference to this error message anywhere in the documentation or even in the project.

The only reference to location in the template is complete:

![image](https://user-images.githubusercontent.com/33820650/80841711-f862c300-8bcd-11ea-948b-9dd774c5b00b.png)

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- I followed the tutorial here: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/image-builder on Azure Cloud Shell
- Run `az resource create \
    --resource-group $imageResourceGroup \
    --properties @helloImageTemplateWin.json \
    --is-full-object \
    --resource-type Microsoft.VirtualMachineImages/imageTemplates \
    -n helloImageTemplateWin01`

## Expected Behavior

When complete, this will return a success message back to the console, and create an Image Builder Configuration Template in the $imageResourceGroup. 

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by sirredbeard** [comment]
I can reproduce on Azure CLI on WSL:

![Annotation 2020-05-01 165901](https://user-images.githubusercontent.com/33820650/80841361-36abb280-8bcd-11ea-9b7b-5805124c4f0d.png)
![Annotation 2020-05-01 165959](https://user-images.githubusercontent.com/33820650/80841363-38757600-8bcd-11ea-8394-e87df1f734d3.png)

**Comment by sirredbeard** [comment]
![Annotation 2020-05-01 171307](https://user-images.githubusercontent.com/33820650/80842225-0b29c780-8bcf-11ea-991e-da4b7f1802bf.png)
![Annotation 2020-05-01 171515](https://user-images.githubusercontent.com/33820650/80842344-59d76180-8bcf-11ea-89d5-dcefd41464e0.png)

**Comment by bureado** [comment]
@danielsollondon

**Comment by Drewm3** [comment]
@danielsollondon, could you take a look at this issue?

**Comment by danielsollondon** [comment]
Looking now...

**Comment by sirredbeard** [comment]
Thank you @danielsollondon those are very helpful.

**Comment by danielsollondon** [comment]
Quick update, all the Azure docs PRs are in review now, I am hoping the updates will get out today.

**Comment by danielsollondon** [comment]
Sorry for the delay, docs have been updated.

**Comment by sirredbeard** [comment]
Thank you!

**Comment by Drewm3** [comment]
Closing this now that the docs are updated.
