### ISSUE TITLE
File share generation example does not work

### ISSUE THREAD

**Issue by ElYusubov** [Azure/azure-cli#13308]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Getting error when running example of Azure File Share generation below when AZURE_STORAGE_KEY env variable is already set:
az storage share create --account-name MyAccount--name MyFileShare

> One of the request inputs is out of range. ErrorCode: OutOfRangeInput
> <?xml version="1.0" encoding="utf-8"?><Error><Code>OutOfRangeInput</Code><Message>One of the request inputs is out of range.
> RequestId:723ccb79-901a-0071-0b43-21b92e000000
> Time:2020-05-03T12:08:29.9874959Z</Message></Error>

**To Reproduce**

Run sample CLI command of file share creation from:
https://docs.microsoft.com/en-us/cli/azure/storage/share?view=azure-cli-latest#az-storage-share-create

**Expected behavior**
File share generation should not give error.
az storage share create --account-name myaccountname--name myfileshare

**Environment summary**
Run it on Azure portal CLI (Bash) window

**Additional context**

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
Hi @ElYusubov , I cannot reproduce your issue in Cloud Shell. Could you share debug information with me using `--debug` in your command?

**Comment by Juliehzl** [comment]
Hi , because there is no response for several days, I will close the PR now and if you still have the problem, feel free to reopen it.
