### ISSUE TITLE
--enable-managed-identity does not seem to be working

### ISSUE THREAD

**Issue by mattruma** [Azure/azure-cli#13301]
When I use --enable-managed-identity with a value of true, I am getting a `'ApiManagementServiceResource' object does not support item assignment` error message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 197d8382-ee16-6001-4941-768877379c0d
* Version Independent ID: 1423fa76-977f-ad88-8129-0b52a38e68e6
* Content: [az apim](https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest#code-try-6)
* Content Source: [src/azure-cli/azure/cli/command_modules/apim/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/apim/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
apim

**Comment by mattruma** [comment]
Hi @yonzhan, any update on this?

**Comment by yonzhan** [comment]
Api management service team should look into this.

**Comment by navba-MSFT** [comment]
@mattruma Apologies for the late reply. I was able to run the below command in azure cloud shell and it worked fine.

>***@Azure:~$ az apim create --name MyApim -g MyRG -l eastus --publisher-email Myemail@contoso.com --publisher-name Contoso **--enable-managed-identity true**

More Info [here](https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest). Could you please test the same and let me know if you face any issues ? Awaiting your reply.
