### ISSUE TITLE
Import an existing certificate failure: Unable to assign an existing policy

### ISSUE THREAD

**Issue by s-tuli** [Azure/azure-cli#13304]
## Describe the bug

**Command Name**
`az keyvault certificate import`

**Errors:**
```
Unable to build a model: Unable to deserialize response data. Data: 2020-04-30T21:43:42+00:00, unix-time, TypeError: an integer is required (got type str), DeserializationError: Unable to deserialize response data. Data: 2020-04-30T21:43:42+00:00, unix-time, TypeError: an integer is required (got type str)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
You should be able to get the policy with the ‘az keyvault certificate show’ command, download the file as you did below, and import it specifying the -p or --policy parameter to the ‘az keyvault certificate import’ command.
```
CERT_POLICY=$(az keyvault certificate show --vault-name $SOURCE_FIRST_PARTY_KEY_VAULT_NAME  -n azds1sp --query policy)

az keyvault secret download --vault-name $SOURCE_FIRST_PARTY_KEY_VAULT_NAME --file ./azds1SP -n azds1sp  --encoding base64

az keyvault certificate import --vault-name $FIRST_PARTY_KEY_VAULT_NAME --file ./azds1SP -n azds1sp -p “$CERT_POLICY”
```
But the above does not work. I had to explicity remove the date attributes in the policy that I got in $CERT_POLICY and I saved it as policy.json

I tried to run the below command: 
```
az keyvault certificate import --vault-name $FIRST_PARTY_KEY_VAULT_NAME --file ./azds1SP -n azds1sp -p "@policy.json"
```
It worked after I had explicitly deleted the date attributes: "created" and "updated"

## Expected Behavior
These commands should have worked:
```
CERT_POLICY=$(az keyvault certificate show --vault-name $SOURCE_FIRST_PARTY_KEY_VAULT_NAME  -n azds1sp --query policy)

az keyvault secret download --vault-name $SOURCE_FIRST_PARTY_KEY_VAULT_NAME --file ./azds1SP -n azds1sp  --encoding base64

az keyvault certificate import --vault-name $FIRST_PARTY_KEY_VAULT_NAME --file ./azds1SP -n azds1sp -p “$CERT_POLICY”
```
## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1

```

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by bim-msft** [comment]
@s-tuli Thanks for the report, this is a bug on our side. I will make a patch to fix this.
