### ISSUE TITLE
AZ issue on Cloud Shell

### ISSUE THREAD

**Issue by reddyfull** [Azure/azure-cli#13309]
## Describe the bug

**Command Name**
``

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by yonzhan** [comment]
@reddyfull what is the detailed issue on Cloud Shell?

**Comment by yungezz** [comment]
hi @reddyfull could you pls share what az commands you run to help troubleshooting? thanks.

**Comment by maertendMSFT** [comment]
@reddyfull , please provide repro steps.  Otherwise, please close this issue.
