### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory

### ISSUE THREAD

**Issue by ridhabnj** [Azure/azure-cli#13307]
## Describe the bug

**Command Name**
`az storage blob download-batch`

**Errors:**
```
[Errno 21] Is a directory: 'data/boats/1282/2000xauto'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
command_modules/storage/operations/blob.py, ln 204, in _download_blob
    progress_callback=progress_callback)
storage/v2018_11_09/blob/baseblobservice.py, ln 1968, in get_blob_to_path
    with open(file_path, open_mode) as stream:
IsADirectoryError: [Errno 21] Is a directory: 'data/boats/1282/2000xauto'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob download-batch -d {} -s {} --account-name {} --account-key {}`

## Environment Summary
```
Linux-4.9.78-xxxx-std-ipv6-64-x86_64-with-centos-7.7.1908-Core
Python 3.6.8
Installer: RPM

azure-cli 2.5.1

```

**Comment by yonzhan** [comment]
add to S170

**Comment by Juliehzl** [comment]
@ridhabnj soorry for late response. Is it possible to provide us debug information to us with `--debug` in your command? 
In this command, the value for `-d` should be a path. Is it a directory(path) for 'data/boats/1282/2000xauto' in your scenario?

**Comment by yonzhan** [comment]
@ridhabnj  any update?
