### ISSUE TITLE
Respect KUBECONFIG env for get-credentials

### ISSUE THREAD

**Issue by garthkerr** [Azure/azure-cli#13305]
**Describe the solution you'd like**
Currently, to override the system default `~/.kube/config` path there is an optional parameter `--file` for the `az aks get-credentials` command. When the parameter is not provided, the CLI should respect the value of `KUBECONFIG` environment variable in the current shell context.

**Additional context**
This is useful for workflows with direnv, etc. and providing isolated kubectl contexts with az.

**Comment by yonzhan** [comment]
aks

**Comment by navba-MSFT** [comment]
@garthkerr Apologies for the late reply. Use one of the following options to change where kubectl looks for configuration parameters:

Modify the KUBECONFIG environment variable to point to the config file's current location. For more information, see [Set the KUBECONFIG environment variable](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable).

Run the [kubectl config](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#config) command with the --kubeconfig= parameter.

Could you please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the Azure CLI and check if the KUBECONFIG is still getting ignored ? Awaiting your reply.
