### ISSUE TITLE
Login failed because it won't let me switch accounts

### ISSUE THREAD

**Issue by rpstester** [Azure/azure-cli#13310]
## Describe the bug
I just downloaded and install the AZ CLI.  I ran the 'az login' command.  It opened in Chrome, my default browser.  It shows my currently logged-in (o365) account, and my test (Microsoft) account. I want to log in with my test account.  
![Azure login fail 1](https://user-images.githubusercontent.com/32249806/80925028-94b9d080-8d5a-11ea-88b6-1f0d981fb426.PNG)
However, when I click on the second account, which is my test Microsoft account, it acts like I clicked on the first account, my Office 365 account.
![Azure login fail 2](https://user-images.githubusercontent.com/32249806/80925064-e5312e00-8d5a-11ea-90ac-a90ebc040960.PNG)
From here, I could Sign In with my o365 account, which is of course the wrong one.  Or I could click the back arrow, which exits me out with a failure.  
![Azure login fail 3](https://user-images.githubusercontent.com/32249806/80925102-37724f00-8d5b-11ea-834c-92919d00a48f.PNG)
So yeah. I cannot log in with AZ CLI, and since I'm new to it, I don't know what else to try.  But I'm sure you want to know about this bug and forward it to the appropriate party. Thanks!

**Command Name**
`az login`

**Errors:**
```
Login failed
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- I have Chrome 81 as my default browser, and I have the Windows 10 accounts add-in which detects the Office 365 account.  I'm not signed into O365, I'm signed into the domain, but I have linked my O365, and that's what this add-in is picking up. 
- `az login` (with no parameters, so interactive mode)
- I had been using Firefox for my test account to access the Azure Portal, as I'm logged into my O365 account on Chrome all the time. 

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1

```

**Comment by rpstester** [comment]
Hey, I'm the 1001st issue! Cool!

**Comment by rpstester** [comment]
I see if I simply go to portal.azure.com in Chrome, that I have the same problem.

**Comment by rpstester** [comment]
I found a workaround by clicking "another account" and typing in my test/Microsoft email address, and it let me in.

**Comment by yonzhan** [comment]
add to S170

**Comment by jiasli** [comment]
As this issue also happens for you with Azure Portal, it is not specific to Azure CLI. It looks like this [Windows 10 Accounts](https://chrome.google.com/webstore/detail/windows-10-accounts/ppnbnpeolgkicgegkbkbjmhlideopiji) extension is not actively maintained.

![image](https://user-images.githubusercontent.com/4003950/81908945-82625100-95fc-11ea-9cbe-040a026b1bd0.png)

Could you try to remove this extension and clear the Chrome cache and try again?

I tried to install this extension but couldn't repro this issue.

**Comment by yonzhan** [comment]
@rpstester was your issue resolved by above?

**Comment by jiasli** [comment]
Please follow the common flow to login, as [Windows 10 Accounts](https://chrome.google.com/webstore/detail/windows-10-accounts/ppnbnpeolgkicgegkbkbjmhlideopiji) extension is not actively maintained.
