### ISSUE TITLE
creating a cert for authentication generates a world-readable private key

### ISSUE THREAD

**Issue by mohamedhafez** [Azure/azure-cli#13312]
running `az ad sp create-for-rbac --name ServicePrincipalName --create-cert` creates a pem file with a certificate and a private key in it, but the file is world-readable.

cli version 2.5.1, Ubuntu 18.04

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by arrownj** [comment]
Hi @mohamedhafez , thanks for reporting this problem, the default mod will change to `600` in our next release.
