### ISSUE TITLE
Error message should be more specific in case of non-unique dns prefix

### ISSUE THREAD

**Issue by pragyamehta** [Azure/azure-cli#1331]
Error thrown when a non-unique dns prefix is specified is below

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "PreflightValidationCheckFailed",
        "message": "Provisioning of resource(s) for container service 'myacs' in resource group 'myacs-rg' failed with 1 error(s): \\n Resource target: , code: PreflightValidationCheckFailed, message: \\n Preflight validation failed. Please refer to the details for the specific errors.\r\n"
      }
    ]
  }
}

Error message should be more specific

**Comment by derekbekoe** [comment]
@pragyamehta 
Can you provide details on what command produced this error message?
Also what version of the CLI was installed? `az --version`

**Comment by pragyamehta** [comment]
az acs create --resource-group myacs-rg --name myacs --dns-prefix myacs

az --version
azure-cli (0.1.0b9)

acr (0.1.0b9)
acs (0.1.0b9)
appservice (0.1.0b9)
cloud (0.1.0b9)
component (0.1.0b9)
configure (0.1.0b9)
container (0.1.0b9)
context (0.1.0b9)
core (0.1.0b9)
feedback (0.1.0b9)
network (0.1.0b9)
profile (0.1.0b9)
resource (0.1.0b9)
role (0.1.0b9)
storage (0.1.0b9)
vm (0.1.0b9)

Python (Windows) 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]

**Comment by brendandburns** [comment]
Acknowledged.  We should do a better job of validating in the API server before we send the request on...

We can add extra checks in the CLI as well.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
