### ISSUE TITLE
Create Rollout Doesn't exist

### ISSUE THREAD

**Issue by ahmadabdalla** [Azure/azure-cli#13311]
I've noticed that the creation of a roll out resource doesn't exist in CLI nor PowerShell. The only way to provision it is via the the ARM Template. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 530d76b4-5e6e-b66f-fca7-e8739659a6cc
* Version Independent ID: ea1e403c-fa38-b4b0-09bc-9e6482e4c138
* Content: [az deploymentmanager rollout](https://docs.microsoft.com/en-us/cli/azure/deploymentmanager/rollout?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/deploymentmanager/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/deploymentmanager/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
@ahmadabdalla Hi, in fact, the [REST API for creating rollouts](https://docs.microsoft.com/en-us/rest/api/deploymentmanager/rollouts/createorupdate) has many parameters and complicated input logic, so it may be inconvenient to input parameters one by one. Using ARM templates for most scenarios is a simpler and reusable option.
So may I ask what scenario you prefer to use `az deploymentmanager rollout create`?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
