### ISSUE TITLE
Null templateLink returned in deployment().properties in 2.5.1 azure cli

### ISSUE THREAD

**Issue by priyank-b** [Azure/azure-cli#13317]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.5.1

**Describe the bug**

Following az command is brokern:
az deployment group create -g <resource_group> --template-uri "https://devtestzipacc.blob.core.windows.net/test/mainTemplate.json" --name "test"

It used to return templateLink correctly in older version. With latest update, it is sending null.

**To Reproduce**

Use this command in 2.5.1 azure cli. It returns null templateLink property.
az deployment group create -g <resource_group> --template-uri "https://devtestzipacc.blob.core.windows.net/test/mainTemplate.json" --name "test"

**Expected behavior**

Above command should populate templateLink as explained in public documentation:
- https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/linked-templates#using-variables-to-link-templates
- https://docs.microsoft.com/bs-latn-ba/azure/azure-resource-manager/templates/template-functions-deployment#remarks

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
add to S169
