### ISSUE TITLE
VMSS Disk Detach Error

### ISSUE THREAD

**Issue by AErmie** [Azure/azure-cli#13329]
## Describe the bug

**Command Name**
`az vmss disk detach`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 688, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss disk detach --lun {} --vmss-name {} -g {} --instance-id {}`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

Extensions:
resource-graph 0.1.11
aks-preview 0.4.43

```

**Comment by yungezz** [comment]
hi @AErmie Did you met the issue on Cloudshell? If yes, this is a known issue at Cloudshell, similiar to https://github.com/Azure/azure-cli/issues/13233#issuecomment-620938939. To solve it, please use Azure CLI on a local machine or run az login in Cloud Shell and retry the command.

**Comment by maertendMSFT** [comment]
This should be fixed now.  I cannot repro, please close.
