### ISSUE TITLE
az acr helm push hangs when connection is slow

### ISSUE THREAD

**Issue by djyou** [Azure/azure-cli#13323]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

The service team received a case where the `az acr helm push` command hangs for hours when the client connection is slow and the service returned a response after ~4 mins.

This behavior is sporadic (could be caused by transient network connection) but the hanging behavior may be addressed by adding a client timeout.

**To Reproduce**

Can't be reproduced deterministically.

**Expected behavior**

Client should error out if connection times out.

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
acr

**Comment by yungezz** [comment]
It's strange that RestAPI/SDK not timeout limit?

**Comment by yugangw-msft** [comment]
i will add client end timeout this week to mitigate

**Comment by yugangw-msft** [comment]
Fixed
