### ISSUE TITLE
Update endpoint list to include Function Apps

### ISSUE THREAD

**Issue by josiahvinson** [Azure/azure-cli#13324]
According to [this link](https://github.com/Azure/azure-cli/issues/10879#issuecomment-564752435), Function Apps are now a first-class endpoint for Event Grid and can be set as such via the `create` command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e73e1b-aad9-0ce8-be1f-a9b9d02ca6d4
* Version Independent ID: 73525c5f-94f3-1c07-e3b6-3a022aab2a10
* Content: [az eventgrid event-subscription](https://docs.microsoft.com/en-us/cli/azure/eventgrid/event-subscription?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/eventgrid/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/eventgrid/_help.py)
* Service: **event-grid**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
eventgrid

**Comment by yungezz** [comment]
this is a feature request

**Comment by ebrucucen** [comment]
Apparently it is not part of main AzureCli feature, but does require installation of cli extension:
https://github.com/Azure/azure-cli-extensions/issues/1713#issuecomment-629667760

**Comment by ahamad-MS** [comment]
this is dup issue. closing it
