### ISSUE TITLE
failure in az vm create

### ISSUE THREAD

**Issue by anillaghuvarapu** [Azure/azure-cli#13322]
## Describe the bug

**Command Name**
`az vm create`

**Errors:**
```
The password length must be between 12 and 72
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm create --resource-group {} --name {} --vnet-name {} --subnet {} --nsg {} --image {} --size {} --admin-username {} --custom-data {} --no-wait --admin-password {}`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by yungezz** [comment]
let's confirm where the validation error from. If it's from srevice, then by design.

**Comment by qwordy** [comment]
It's by design. The validation comes from CLI. Portal has the same requirement.
Password must have 3 of the following: 1 lower case character, 1 upper case character, 1 number, and 1 special character.
The value must be between 12 and 72 characters long.
