### ISSUE TITLE
Can't find ubuntu 20.04 with azure cli

### ISSUE THREAD

**Issue by GabyCT** [Azure/azure-cli#13320]
I am trying to find ubuntu 20.04 with azure cli and I can't, I tried the following
$az vm image list --offer UbuntuServer --output table --all

**Comment by bquantump** [comment]
Thank you for your question @GabyCT.  We will check in 20.04 is supported.

**Comment by agnutzmann** [comment]
I have the same issue.
I can see the image on Azure web portal as Ubuntu Server 20.04 Pro (need to pay the subscription), but i can't find it via CLI.

**Comment by Drewm3** [comment]
@Vaibhav-Agar, could you look into this?

**Comment by Vaibhav-Agar** [comment]
Investigating.

**Comment by tg123** [comment]
@Vaibhav-Agar 

no `focal` folder for 20.04 at `https://packages.microsoft.com/repos/azure-cli/dists/`

a workaround is to use an older os version, e.g. `bionic`,
```
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main
```

**Comment by Vaibhav-Agar** [comment]
I was able to replicate the issue. Reached out to the marketplace team to seek resolution.

**Comment by GabyCT** [comment]
any feedback? thanks

**Comment by Vaibhav-Agar** [comment]
Marketplace team to provide an update shortly.

**Comment by bureado** [comment]
Hello! We launched both Ubuntu Server 20.04 LTS and Ubuntu Pro 20.04 on 23 April.

While this means that images are tested, built, published and supported in Azure (see below), I want to acknowledge that the `UbuntuLTS` alias that many of you use when creating new VMs still points to the 18.04 LTS release.

This is not an omission, but a way to give users additional time to prepare for the switch particularly given the migration to [Python 3.8 as default](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Python3_by_default).

While I don't have a specific date to share just yet, I want to reiterate that we fully intend to make _focal_ the default release when you look for Ubuntu on Azure, whether that's via `az vm create` (the `UbuntuLTS` shortname) or in the Portal.

In the meantime, you can create a new _focal_ VM either via the Azure Portal (search for 20.04 when creating a new resource, and you'll see both Server and Pro) or via the CLI, for example:

`az vm image list -p canonical -o table --all | grep 20_04-lts | grep -v gen2`

You can deploy any of those images by using the URN directly in place of the alias. For example:

`az vm create -g foo -l southcentralus -n bar --image Canonical:0001-com-ubuntu-server-focal:20_04-lts:20.04.202006100 --no-wait`

(or, for simplicity, you can just use `Canonical:0001-com-ubuntu-server-focal:20_04-lts:latest`)

I hope this is useful for those of you that want to get up and running with either Ubuntu Server or Ubuntu Pro 20.04. And, of course, for those of you that are running earlier Ubuntu releases on Azure and are upgrading to _focal_ in place, you're more than welcome to do so and please let us know your feedback.

I will update this issue when we are closer to switching the defaults. Thank you!

**Comment by maburlik** [comment]
Hi there, Max from Service Fabric team. We are planning a migration path for which we need the image offer to match the previous Ubuntu LTS image releases under offer "UbuntuServer".

Our current main consumed images on Linux are:
**16.04-LTS**:
  {
    "id": "/Subscriptions/13ad2c84-84fa-4798-ad71-e70c07af873f/Providers/Microsoft.Compute/Locations/southcentralus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/**UbuntuServer**/Skus/16.04-LTS",
    "location": "southcentralus",
    "name": "16.04-LTS",
    "properties": {
      "automaticOSUpgradeProperties": {
        "automaticOSUpgradeSupported": true
      }
    },
    "tags": null
  },

**18.04-LTS**:
  {
    "id": "/Subscriptions/13ad2c84-84fa-4798-ad71-e70c07af873f/Providers/Microsoft.Compute/Locations/southcentralus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/**UbuntuServer**/Skus/18.04-LTS",
    "location": "southcentralus",
    "name": "18.04-LTS",
    "properties": {
      "automaticOSUpgradeProperties": {
        "automaticOSUpgradeSupported": true
      }
    },
    "tags": null
  },

and I noticed this query does not return 20.04 LTS as a supported image for the same offer:
az vm image list-skus --publisher Canonical --offer UbuntuServer --location southcentralus 

The latest image version listed under this offer is 19.10 and we can only adopt the LTS releases for our purpose. Is there a reason the offer and SKU format has changed for 20.04, and is this planned to be moved in line with the previous release structure?

I've retrieved this **imageReference** in the template when creating a VMSS resource with target SKU 20.04 LTS through the portal:
                        "imageReference": {
                            "publisher": "canonical",
                            "offer": "0001-com-ubuntu-pro-focal",
                            "sku": "pro-20_04-lts",
                            "version": "20.04.20200525"
                        }

**Comment by bureado** [comment]
Yes, @maburlik, publishers can change the offer name as Canonical has for the 20.04 release. There are currently no plans to move the 20.04 LTS image to the previous offer name.

**Comment by Drewm3** [comment]
@bureado, I believe the original question has been answered. So, can the issue/question be closed?

**Comment by IanBoudreaux** [comment]
@maburlik @bureado I agree and I think it is fairly confusing to have the offer name changed for the 20.04 release.

I was looking into upgrading our VMs from 18.04-LTS to 20.04-LTS and because I expected `Canonical:UbuntuServer:20.04-LTS:latest` but it didn't exist in the `az vm image list`, I wouldn't have known it existed at all if not for the [marketplace link](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/canonical.0001-com-ubuntu-server-focal?tab=Overview). When I saw `Canonical:0001-com-ubuntu-server-focal:20_04-lts:latest` in the [list](https://az-vm-image.info/?cmd=--all+--publisher+Canonical) I wasn't sure it was the correct image until I found this post.

It seems unwise to break the established mold - it is adding unnecessary confusion. If it had the "UbuntuServer" offer with the same SKU format, it would have been clear and obvious.

Since it sounds like Canonical themselves made the change, what is the best way to get this feedback to them?

**Comment by shurick81** [comment]
Just in case it helps to save time to someone.

I have looked what images are promoted in Azure Portal.

One of them was `Ubuntu Server 20.04 LTS - Gen2`. When I convert the configuration from portal to ARM template, it tells this image:

```Json
"imageReference": {
                        "publisher": "canonical",
                        "offer": "0001-com-ubuntu-server-focal",
                        "sku": "20_04-lts-gen2",
                        "version": "latest"
                    }
```

**Comment by Drewm3** [comment]
I am moved this to a "Feature Request" because this is not really a question nor a bug at this point. @bureado, please close this issue once the defaults have been switched.

**Comment by Drewm3** [comment]
Toggling the feature request flag because it looks like the MSFT monitoring tools didn't pickup the change from two weeks ago.

**Comment by immae1** [comment]
As I understand it, there is no SKU for Ubuntu 20.04 LTS in Azure anymore? Then my terraform deployment breaks because by default no URN is offered by the _azurerm_ provider. That's a real pity - does anyone have a workaround?

**Comment by shurick81** [comment]
@immae1, this does not work for you or have I lost you here?

```
"publisher": "canonical",
"offer": "0001-com-ubuntu-server-focal",
"sku": "20_04-lts-gen2",
"version": "latest"
```

**Comment by immae1** [comment]
My fault - i had to change the offer field, too... . Thanks @shurick81

**Comment by Drewm3** [comment]
Closing out this issue because the publisher as decided to not use the existing offer any longer, and this is fully up to Canonical. So this is not anything that can be changed through the Azure platform.

**Comment by 0brym** [comment]
What's up guys. 18.04 is still the default, and 22.04 has been out since April 2022. It's 2023 now.

**Comment by maburlik** [comment]
> What's up guys. 18.04 is still the default, and 22.04 has been out since April 2022. It's 2023 now.

Take a read up above. It answers the question.

**Comment by 0brym** [comment]
so it's a do-release-upgrade until current then. got it.

**Comment by Hooloovoo** [comment]
> so it's a do-release-upgrade until current then. got it.

You can deploy all recent Ubuntu (or Ubuntu Pro) releases. You just need to use the new URN for the release you want rather than the old offer:
https://ubuntu.com/server/docs/find-ubuntu-images-on-azure
