### ISSUE TITLE
az storage container: Name or service not known

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [Azure/azure-cli#13337]
## Describe the bug
I create a resource group and a storage account, when I try to create a storage container I get `name or service not known` error even though in the portal I can see that the storage account with the given name exists.

**Command Name**
`az storage container create`

**Errors:**
```
HTTPSConnectionPool(host='talha2.blob.core.windows.net', port=443): Max retries exceeded with url: /mycontainer?restype=container (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb917b5c9b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
python3.6/site-packages/urllib3/connection.py, ln 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
...
    raise _wrap_exception(ex, AzureException)
azure.common.AzureException: HTTPSConnectionPool(host='talha2.blob.core.windows.net', port=443): Max retries exceeded with url: /mycontainer?restype=container (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb917b5c9b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

## To Reproduce:

- a storage account is created successfully here with the name talha2.
- `az storage container create --account-name talha2 --name talha --auth-mode login`

## Expected Behavior
The storage container should be created.
## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.74 *

```
## Additional Context

This happens in different regions, `westus2`, `eastus2`, `southcentralus`.

**Comment by yonzhan** [comment]
add to S170

**Comment by SaitTalhaNisanci** [comment]
Note that I have been using this command for the last 2 months and didn't have any issue. But now it is constantly failing with the above error. I didn't change my az cli version.

**Comment by rebecca-makar** [comment]
Adding onto this.... Have this automated in azure devops pipelines, have been using same az command for months and this broke from last night to this morning. Microsoft Internal user. 

`2020-05-05T15:40:55.3539676Z The value for one of the HTTP headers is not in the correct format. ErrorCode: InvalidHeaderValue
2020-05-05T15:40:55.3542457Z <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.
2020-05-05T15:40:55.3544065Z RequestId<requstidNum>
2020-05-05T15:40:55.3545698Z Time:2020-05-05T15:40:55.3535810Z</Message><HeaderName>x-ms-blob-public-access</HeaderName><HeaderValue>off</HeaderValue></Error>
2020-05-05T15:40:55.4536092Z ##[error]Blob container (<NAME>) creation failed. See log for details.`

**Comment by SaitTalhaNisanci** [comment]
Yeah We are also Microsoft internal user and we started to see this issue last night.

**Comment by Juliehzl** [comment]
@SaitTalhaNisanci because there is no change for you azure cli version, according to the error message, there may be server error. I will recommend you to create a ICM ticket for quick response.

**Comment by Juliehzl** [comment]
Hi @zhusijia26, do you know which one is the right person for such service attention issue.

**Comment by zhusijia26** [comment]
@kartikshah9 can you help on this issue? Not sure if Storage tag was added correctly.

**Comment by SaitTalhaNisanci** [comment]
I think the issue is resolved now

**Comment by Juliehzl** [comment]
> I think the issue is resolved now

Thanks for you update. In this way I will close the issue and if there is any problem, feel free to create a new one.

**Comment by kethahel99** [comment]
What was the issue? We are experiencing the same problem

**Comment by gauravgurung7** [comment]
How was the issue resolved ?
