### ISSUE TITLE
Does not work on Focal Fossa (Ubuntu 20.04) MicrosoftDocs/azure-docs-cli#1955

### ISSUE THREAD

**Issue by MonikaReddy-MSFT** [Azure/azure-cli#13332]
**Is your feature request related to a problem? Please describe.**
Customer has reported that it does not work on Focal Fossa Ubuntu 20.04 version.

**Describe the solution you'd like**
Customer has provided a solution that worked for him - 
Here is a workaround I used for myself for now (worked for my use-case, can't guarantee it's perfect):
First download the script without running it:
curl -sL https://aka.ms/InstallAzureCLIDeb > install_azcli.sh
chmod +x install_azcli.sh
Now modify the line that starts with CLI_REPO=... to look like this:
CLI_REPO=eoan
Save the file
Run ./install_azcli.sh

**Describe alternatives you've considered**

**Additional context**

https://github.com/MicrosoftDocs/azure-docs-cli/issues/1955

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look?

**Comment by tg123** [comment]
no focal folder for 20.04 at https://packages.microsoft.com/repos/azure-cli/dists/

a workaround is to use an older os version, e.g. bionic,

deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main

**Comment by fengzhou-msft** [comment]
Focal package released for azure-cli 2.6.0. Please try again.
