### ISSUE TITLE
How do I install older versions of the cli?/MicrosoftDocs/azure-docs-cli#1954

### ISSUE THREAD

**Issue by MonikaReddy-MSFT** [Azure/azure-cli#13331]
**Resource Provider**
Customer is requesting to provide older versions of Azure CLI

**Description of Feature or Work Requested**
Customer is looking for older version of CLI.
Working on a project where previous developer used an older version of the cli, but now when I try to run the scripts he created it's not working.
I fully understand the ramifications of running an older cli, but the costs incurred for customer for me to fix all the issues is not acceptable, and I can't really find where the older versions of the installers are?

**Minimum API Version Required**

**Swagger Link**
https://github.com/MicrosoftDocs/azure-docs-cli/issues/1954

**Target Date**

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look? thanks

**Comment by fengzhou-msft** [comment]
Take 2.2.0 as an example, to install azure cli 2.2.0, please check the following:
Package | Install   Specific Version Command
-- | --
RPM | yum --showduplicates list azure-cli; sudo yum install azure-cli-2.2.0-1.el7
DEB | apt-cache policy azure-cli; sudo apt-get install azure-cli=2.2.0-1~bionic
MSI | Invoke-WebRequest -Uri https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.2.0.msi -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait   -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi
HOMEBREW | brew install -s https://raw.githubusercontent.com/azclibot/homebrew-core/azcli2.2.0/Formula/azure-cli.rb
PIP | pip install azure-cli=2.2.0
DOCKER | docker pull mcr.microsoft.com/azure-cli:2.2.0

**Comment by jiasli** [comment]
I think we need to put this information in the implementation of https://github.com/Azure/azure-cli/issues/13653.

**Comment by freedev** [comment]
The HOMEBREW way does not work. For example trying to install an older version returns this:

```
brew install -s https://raw.githubusercontent.com/azclibot/homebrew-core/azcli2.22.0/Formula/azure-cli.rb
Traceback (most recent call last):
brew extract or brew create and brew tap-new to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of azure-cli formula file from an arbitrary URL is unsupported! (UsageError)
brew extract or brew create and brew tap-new to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of azure-cli formula file from an arbitrary URL is unsupported! (UsageError)


```

**Comment by ryanhofdotgov** [comment]
I was able to install an older version of azure-cli (2.21.1) with Homebrew following the approach described here: https://stackoverflow.com/a/64125796

**Comment by freedev** [comment]
I found

> I was able to install an older version of azure-cli (2.21.1) with Homebrew following the approach described here: https://stackoverflow.com/a/64125796

I found much easier install an old version with:

     brew uninstall azure-cli
     pip3 install azure-cli==2.22.0

**Comment by jdthorpe** [comment]
Previous versions of the source code and MSI installers are on the [Azure CLI GitHub Releases page](https://github.com/Azure/azure-cli/releases)

**Comment by smruti2233** [comment]
if you are using mac os then here is a steps to install older version of azure cli
step 1- Install pip by using this command
python3 get-pip.py

step 2 - check the version of pip 
pip --version

step 3- then install the specific version you wat for example 
pip install azure-cli==2.41.0

**Comment by ZhiliangWu** [comment]
Another alternative is to use [pipx](https://github.com/pypa/pipx)

```console
$ pipx install azure-cli==2.56.0
```
