### ISSUE TITLE
Support for RHEL 8 RAW

### ISSUE THREAD

**Issue by GabyCT** [Azure/azure-cli#13339]
Is there going to be an image for RHEL 8 RAW?

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
@GabyCT You can submit feedback here: https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/redhat/redhat-imagelist

CLI Team is not involved in image build and distribution.
