### ISSUE TITLE
az kusto cluster create fails with "Invalid SKU name provided"

### ISSUE THREAD

**Issue by vladris** [Azure/azure-cli#13330]
## Describe the bug

**Command Name**
`az kusto cluster create`

**Errors:**
```
Invalid SKU name provided
```

## To Reproduce:
`az kusto cluster create --location "Central US" --name MyClusterName --resource-group MyRGName --sku D11_v2 --capacity 1`

## Expected Behavior
Provision Kusto cluster.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1

```
## Additional Context

I tried all possible values of SKU allowed by the CLI but none of them seem to work. The error happens server-side, here is the relevant part of running with `--debug` on:

```
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Content-Length': '72'
msrest.http_logger :     'User-Agent': 'python/3.6.6 (Windows-10-10.0.18362-SP0) msrest/0.6.13 msrest_azure/0.6.3 azure-mgmt-kusto/0.3.0 Azure-SDK-For-Python AZURECLI/2.5.1 (MSI)'
msrest.http_logger : Request body:
msrest.http_logger : {"location": "centralus", "sku": {"name": "D11_v2", "tier": "Standard"}}
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Kusto/clusters/<redacted>?api-version=2019-01-21 HTTP/1.1" 400 73
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
...
msrest.http_logger : Response content:
msrest.http_logger : {"error":{"code":"InvalidSkuName","message":"Invalid SKU name provided"}}
msrest.exceptions : Invalid SKU name provided
```
Sounds like the API expects a different specification for the SKU name but CLI restricts this to a small set of values which don't seem to work.

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by radennis** [comment]
These are old SKUs that were recently removed. We are releasing a new nuget so that you can use the new SKUs. Adding @ilayrn for more information

**Comment by vladris** [comment]
Thanks! Azure CLI needs to be updated since it restricts the SKU parameter. User can only pick from these SKUs that don't work.

**Comment by radennis** [comment]
Correct that's why we're working on releasing a new nuget for that to work. AFAIK this was already released, @ilayrn can share the details.

**Comment by ilayrn** [comment]
@vladris, we released a new version for Azure CLI with up-to-date support for all the functionality provided by Kusto. To install it, run the command: "az extension add -n kusto". After it's installed, the command should work.

**Comment by vladris** [comment]
Now I get `usage error: --sku [KEY=VALUE ...]` for the same command. What is the expected format?

**Comment by ilayrn** [comment]
Yes, you should use the same values that appear in the portal, e.g. Dev(No SLA)_Standard_D11_v2. We moved away from enforcing the name on the client-side because SKUs can be added and removed in the backend.

**Comment by vladris** [comment]
Thanks, I managed to provision a cluster! The updated extension requires separate name-value pairs for SKU name, tier, and capacity. It is a bit tricky to figure out the right combination, is this documented somewhere?

After a bunch of trial and errors,I got it working with `name='Dev(No SLA)_Standard_D11_v2' tier='Basic'` but a reference for allowed values would really help.

**Comment by ilayrn** [comment]
@vladris I'm glad to hear it worked for you. We're going to release the documentation in the coming days and we'll add an example to address your feedback. Thanks!

**Comment by SQLDataSide** [comment]
Hi I cant get it working i have 


SubscriptionName='Pay-As-You-Go'
ResourceGroupName='My_RG'
Location='WestUS2'
AzureDataExplorer='myapplicationadx'
SkuName='Dev(No SLA)_Standard_D11_v2'
Capacity=1

az kusto cluster create --name $AzureDataExplorer \
                        --resource-group $ResourceGroupName \
                        --location $Location \
                        --sku SkuName \
                        --capacity $Capacity

not sure what i am missing, please fix the help section of the 
az kusto cluster create --help

i am still getting the same error 

thanks
Nik

**Comment by vladris** [comment]
Try this:

```
az kusto cluster create --cluster-name $AzureDataExplorer
--resource-group $ResourceGroupName
--location $Location
--sku name=SkuName capacity=$Capacity tier=$Tier
```

+1 on getting this documented, it's not easy to figure it out...

**Comment by SQLDataSide** [comment]
still getting an error 
az : ERROR: az kusto cluster create: 'name=Dev(No SLA)_Standard_D11_v2' is not a valid value for '--sku'. See 'az kusto cluster create --help'.

**Comment by SQLDataSide** [comment]
i did run "az extension add -n kusto" got an error

az extension add -n kusto
az : ERROR: No matching extensions for 'kusto'. Use --debug for more information.
At line:1 char:1
+ az extension add -n kusto
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: No match...re information.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by SQLDataSide** [comment]
I even ran the "**az extension add -n kusto --debug**" and i git the error


ERROR: cli.azure.cli.core.util : No matching extensions for 'kusto'. Use --debug for more information.
ERROR: No matching extensions for 'kusto'. Use --debug for more information.

**Comment by SQLDataSide** [comment]
> @vladris, we released a new version for Azure CLI with up-to-date support for all the functionality provided by Kusto. To install it, run the command: "az extension add -n kusto". After it's installed, the command should work.


i did run it and got the error 

z : ERROR: No matching extensions for 'kusto'. Use --debug for more information.
At line:1 char:1
+ az extension add -n kusto
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: No match...re information.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by vladris** [comment]
> still getting an error
> az : ERROR: az kusto cluster create: 'name=Dev(No SLA)_Standard_D11_v2' is not a valid value for '--sku'. See 'az kusto cluster ? create --help'.

Could you please share the full command you ran to create the cluster?

**Comment by SQLDataSide** [comment]
yes i did run ........

az kusto cluster create --name $AzureDataExplorer --resource-group 'IoT_Project_RG' --location westus2 --sku name='Dev(No SLA)_Standard_D11_v2' capacity=1 tier='Basic'


..... and got the error


az : ERROR: az kusto cluster create: 'name=Dev(No SLA)_Standard_D11_v2' is not a valid value for '--sku'. See 'az kusto cluster create --help'.
At line:1 char:1
+ az kusto cluster create --name $AzureDataExplorer --resource-group 'I ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az kusto...create --help'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by vladris** [comment]
Strange, that worked for me. I'll let the product engineers follow up.

**Comment by SQLDataSide** [comment]
can you check this please
....
I even ran the "az extension add -n kusto --debug" and i git the error

ERROR: cli.azure.cli.core.util : No matching extensions for 'kusto'. Use --debug for more information.
ERROR: No matching extensions for 'kusto'. Use --debug for more information.

------ how do you i know that the KUSTO have been installed correctly?????
thanks

**Comment by vladris** [comment]
I just ran that command and it worked fine for me. Maybe try updating Az CLI?

**Comment by SQLDataSide** [comment]
hi i did reinstall AZURE CLI and Kusto and it did work
I gave you  the code 
az kusto cluster create --name $AzureDataExplorer --resource-group ........
and you mentioned it worked , on kkmy side i had to change the code to 
az kusto cluster create --**cluster-**name $AzureDataExplorer --resource-group ........

**Feedback**:
when running anything related to "az kusto ....." the first thing you get is a message in RED that is very very missleading maybe it can be changed, also the information in the --help needs to be updated .

Thank you 
Nik
