### ISSUE TITLE
download-batch OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by rangernet** [Azure/azure-cli#13333]
## Describe the bug

**Command Name**
`az storage blob download-batch`

**Errors:**
```
[Errno 5] Input/output error
Traceback (most recent call last):
storage/v2018_11_09/blob/baseblobservice.py, ln 1984, in get_blob_to_path
    timeout)
storage/v2018_11_09/blob/baseblobservice.py, ln 2200, in get_blob_to_stream
    operation_context
storage/v2018_11_09/blob/_download_chunking.py, ln 42, in _download_blob_chunks
    list(executor.map(downloader.process_chunk, downloader.get_chunk_offsets()))
python3.6/concurrent/futures/_base.py, ln 586, in result_iterator
    yield fs.pop().result()
...
storage/v2018_11_09/blob/_download_chunking.py, ln 164, in _write_to_stream
    self.stream.write(chunk_data)
OSError: [Errno 5] Input/output error


storage/v2018_11_09/blob/baseblobservice.py, ln 1984, in get_blob_to_path
    timeout)
OSError: [Errno 5] Input/output error
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob download-batch --account-name {} --account-key {} -s {} -d {} --pattern {}`

## Environment Summary
```
Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
Python 3.6.8
Installer: RPM

azure-cli 2.3.1 *

```

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
Hi @rangernet , could you share more information about your issue with `--debug` in your command? I cannot reproduce your issue in my machine.

**Comment by Juliehzl** [comment]
Hi @rangernet, because there is no response for several days, I will close the PR now and if you still have the problem, feel free to reopen it.
