### ISSUE TITLE
Error az deployment: 'group' is not in the 'az deployment' command group.

### ISSUE THREAD

**Issue by gregdegruy** [Azure/azure-cli#13346]
What is the reason for this error?

I test using this command
`az deployment group create --name "folding" --resource-group "Folding-COVID19" --template-uri https://raw.githubusercontent.com/likamrat/foldingathome/master/deploy/azure/azuredeploy.json`

I get this error:
```cmd
az deployment: 'group' is not in the 'az deployment' command group. See 'az deployment --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649a07bb-0fa2-6c51-2820-88b1bafa80ba
* Version Independent ID: ace434b7-7549-8e6d-cab0-1612f422a0cf
* Content: [az deployment group](https://docs.microsoft.com/en-us/cli/azure/deployment/group?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S170

**Comment by zhoxing-ms** [comment]
@gregdegruy Hi, may I ask which version of CLI did you use?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Comment by gregdegruy** [comment]
Hi @zhoxing-ms thanks for the replay sorry for the delay.

This is a non-issue I had an older version of the CLI on my system.

> `az deployment group` was added in azure-cli 2.2.0. 
> ensure you If you upgrade to latest az cli and the command will work as expected
