### ISSUE TITLE
Possible regression with az find in 2.5.1

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-cli#13359]
## Describe the bug
Run `az find "group create"` or `az find "vm create"` returns no examples in azure-cli 2.5.1
![image](https://user-images.githubusercontent.com/55177366/81177096-b4f6c300-8fd8-11ea-884c-0af530c950ae.png)

while in 2.4.0, examples are returned for the 2 commands:
![image](https://user-images.githubusercontent.com/55177366/81177330-0b640180-8fd9-11ea-972c-15557d50e9d7.png)

**Command Name**
`az find`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az find {}`

## Environment Summary
```
Linux-5.0.0-1027-azure-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1
azure-cli-ml 1.2.0

Extensions:
azure-cli-ml 1.2.0
peering 0.1.0rc2
datashare 0.1.0
resource-graph 1.0.0
blueprint 0.1.0 (dev) /home/fengzhou/azure-cli-extensions/src/blueprint

```

**Comment by yonzhan** [comment]
az find
