### ISSUE TITLE
az monitor metrics alert create - error with Namespace

### ISSUE THREAD

**Issue by SanjayKishnani** [Azure/azure-cli#13351]
## Describe the bug

**Command Name**
`az monitor metrics alert create`

**Errors:**
```
'namespace'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
command_modules/monitor/operations/metric_alert.py, ln 29, in create_metric_alert
    target_resource_type = _parse_resource_type(scopes)
command_modules/monitor/operations/metric_alert.py, ln 221, in _parse_resource_type
    item_namespace = parse_resource_id(item)['namespace']
KeyError: 'namespace'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor metrics alert create --name {} --resource-group {} --scopes {} {} --condition {} --window-size {} --evaluation-frequency {} --action {} {} --description {}`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

Extensions:
interactive 0.4.4

```

**Comment by yungezz** [comment]
hi @MyronFanQiu could you have a look? thanks

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
@SanjayKishnani The value for `--scopes` should be full ARM Resource ID. Please check the values.

**Comment by SanjayKishnani** [comment]
@MyronFanQiu this is the syntax am trying and it fails with the exact same namespace error.

az monitor metrics alert create -n alert1 -g {ResourceGroup} --scopes {VirtualMachineID} --condition "avg Percentage CPU > 90" --description "High CPU"

scopes is the virtualmachine id and even trying with virtualmachineid gives the exact same error.

**Comment by MyronFanQiu** [comment]
Could you please run it with `--debug` and check the first 10 lines? It should have the actual input values for azure cli.

**Comment by yonzhan** [comment]
@SanjayKishnani  any update for above?

**Comment by MyronFanQiu** [comment]
@SanjayKishnani Hi. I cannot reproduce this issue. Could you please upgrade your Azure CLI to 2.7.0 and have a try?

**Comment by MyronFanQiu** [comment]
closed this issue since no response and cannot reproduce. Feel free to reopen it.
