### ISSUE TITLE
Support for DNS Proxy on Azure Firewall

### ISSUE THREAD

**Issue by tejasshah7** [Azure/azure-cli#13350]
**Resource Provider**

Network (NRP)

**Description of Feature or Work Requested**

Need to add 3 new parameters to the base command of creating the Firewall.
az network firewall create -g MyResourceGroup -n MyFirewall –dns-servers @("1.2.3.4", "4.5.6.7") --dns-proxy-enabled true --dns-require-proxy-for-network-rules false

Here the last 3 parameters are needed:
- dns-servers
   -  Default value is empty
   -  Can have list of IP Address strings
- dns-proxy-enabled
   -  Default value is false
- dns-require-proxy-for-network-rules
   -  Default value is true

For Powershell, I am currently working on these and actually will have something like this:
- DNSServers: Array of strings
- DNSEnableProxy: This can betrue/false with default being false

Allowed:
New-AzFirewall -Name "azFw" -ResourceGroupName $rgName -Location centralus -VirtualNetwork $vnet -PublicIpAddress $pip -DNSEnableProxy true -DNSServers @("10.10.10.1", "20.20.20.2")

Allowed only if no Network Rules have FQDNs:
New-AzFirewall -Name "azFw" -ResourceGroupName $rgName -Location centralus -VirtualNetwork $vnet -PublicIpAddress $pip -DNSRequireProxyForNetworkRules false

Only validation required is
- If DNSRequireProxyForNetworkRules is explicitly set to False with DNSProxy disabled too, then no Network Rules can have FQDNs. Default value is true

**Minimum API Version Required**

There is no NRP change so no API version issue.

**Swagger Link**

There are no swagger changes but here is the Powershell PR for reference.
https://github.com/Azure/azure-powershell/pull/11808

**Target Date**

End of 2020.06.17

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
@haroldrandom  Could you please take a look at this issue?

**Comment by tejasshah7** [comment]
Please do look at the final PR of Powershell as there were some argument type changes done there.
https://github.com/Azure/azure-powershell/pull/11808

**Comment by haroldrandom** [comment]
@tejasshah7 Why does `dnsServers` parameter value need `@()` to quote the servers?

**Comment by haroldrandom** [comment]
@tejasshah7 Also, will those 3 parameters updatable?
