### ISSUE TITLE
ERROR: A hash conflict was encountered for the role Assignment ID. Please use a new Guid

### ISSUE THREAD

**Issue by MaurGi** [Azure/azure-cli#13368]
**Describe the bug**
Running a script from Azure DevOps pipeline, I randomly get the following error, once every 100 calls or so:
```
az role assignment create --subscription <sub_id> --role 'Support Request Contributor' --assignee-object <object_id> --scope /subscriptions/<sub_id>
ERROR: A hash conflict was encountered for the role Assignment ID. Please use a new Guid
```
this is making it impossible to run a long script that has hundreds of these role assignments

**To Reproduce**
call 
```
az role assignment create --subscription <sub_id> --role '<any role>' --assignee-object <object_id> --scope /subscriptions/<sub_id>
```
1,000 times, it will randomly fail with the above.

**Expected behavior**
az role assignment completes

**Environment summary**
no idea how this was installed on the AzDevOps agents.
Here is the output from az --version though:
```
This command group is in preview. It may be changed/removed in a future release.
WARNING: You have 2 updates available. Consider updating your CLI installation. Instructions can be found at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
azure-cli                         2.0.77 *

command-modules-nspkg              2.0.3
core                              2.0.77 *
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/data/vsts-agent/_work/_temp/.azclitask/cliextensions'

Python (Linux) 3.6.5 (default, Nov 22 2019, 05:32:09) 
[GCC 7.4.0]

Legal docs and information: aka.ms/AzureCliLegal

```

**Additional context**

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by arrownj** [comment]
Hi @vladimirjoanovic @rthorn17 , seems the error (ERROR: A hash conflict was encountered for the role Assignment ID. Please use a new Guid) is reported by service side, could you please help check this problem ? Thanks

**Comment by jongio** [comment]
I also encountered this today using terraform

```
resource "azurerm_role_assignment" "cli_queue_msg_storage" {
  scope                = azurerm_storage_account.storage.id
  role_definition_name = "Storage Queue Data Message Processor"
  principal_id         = data.azurerm_client_config.current.object_id
}
```

**Comment by rthorn17** [comment]
@alex-frankel can you see if this is a deployment issue or does it need to be with identity. Thanks

**Comment by MaurGi** [comment]
This keeps happening, I have to rerun a 20 minutes script because this randomly happens

**Comment by alex-frankel** [comment]
I don't know how the `role assignment create` CLI command (or the TF provider Go code) generates the role assignment name, but there is usually some hashing function involved because it requires a GUID for the roleAssignment. It shouldn't happen often, but depending on the hashing seed that is used, this can occur. Do either CLI or TF provider allow you to pass the name of the roleAssignment directly? Then you can generate the GUID yourself and use that instead.

I would reach out to identity team for CLI fix and open an issue in the relevant TF provider repo.

**Comment by jongio** [comment]
Yes, custom name is allowed
https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html#argument-reference

Will try that as a stopgap

**Comment by MaurGi** [comment]
keeps happening with 2.10.1 - here are my versions:

```
azure-cli                         2.10.1 *

command-modules-nspkg              2.0.3
core                              2.10.1 *
nspkg                              3.0.4
telemetry                          1.0.4 *
```

**Comment by karataliu** [comment]
still encountered, is there a fix plan?
What about add an `az role assignment ensure` to check assignment existence before send creating?

**Comment by Kruti-Joshi** [comment]
What is the scope of uniqueness of the roleAssignmentID?
I'm frequently seeing these error messages too, but in the ARM template, I've set role assignment 
`'name' = "[guid(concat(resourceGroup().id, 'some-string-here'))]"`

Since this depends on the resource group in the current deployment, is it possible that there's a hash conflict with the role assignment id of some other resource group which is already present in the subscription?

**Comment by callmewhy** [comment]
Hi team, any update abot this thread? Recently we met the same problem when deploy ARM tempaltes using EV2...
It works in most environments, but just failed in a specify instance. The name is `guid(concat(rg, scope, id, roleId))` which is 100% unique.

**Comment by abhishekjalanvns** [comment]
Please can this issue be updated, we are also getting this but strangely this is only happening in prod environment but not in lower environments.

**Comment by jiasli** [comment]
Superseded by https://github.com/Azure/azure-cli/issues/23770

https://github.com/Azure/azure-cli/pull/24324 worked around this issue by introducing `--name` in `az role assignment create`. You can now provide your own GUID as `--name` to have a predictable role assignment created and bypass this service issue.
