### ISSUE TITLE
Issue with az resource tag -i

### ISSUE THREAD

**Issue by jrachwalski** [Azure/azure-cli#13367]
Incremental parameter does not work
"az: error: unrecognized arguments: -i"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76a8ad2-efd8-9e8a-9b2b-eebeb1e9d1d4
* Version Independent ID: 280b7ea9-eb6c-9601-464b-09bf8e0cff5d
* Content: [az resource](https://docs.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S170

**Comment by zhoxing-ms** [comment]
@jrachwalski Hello, `-i` is work fine on my side, may I ask which version of CLI did you use?

**Comment by jrachwalski** [comment]
azure-cli                         2.0.77 *

command-modules-nspkg              2.0.3
core                              2.0.77 *
nspkg                              3.0.4
telemetry                          1.0.4

**Comment by jrachwalski** [comment]
My Az cli was an old version, due to my brew being out of date
`brew update && brew upgrade azure-cli`

updated the cli to 2.5, and I can now use the --is-incremental option.
You can close this issue,

Thanks.
