### ISSUE TITLE
webapp: az appservice ase create command fails on azure cli version 2.4.0, 2.5.0 or 2.5.1 (last worked on v2.3.1)

### ISSUE THREAD

**Issue by tocorobo** [Azure/azure-cli#13361]
**DESCRIPTION**
The command *az appservice ase create* fails with azure cli version 2.4.0, 2.5.0 or 2.5.1 on CentOS 7.8 [last working version was 2.3.1].

**ERROR**
The request content was invalid and could not be deserialized: 'Could not find member 'template' on object of type 'DeploymentDefinition'. Path 'template', line 1, position 12.'.

**STEPS TO REPRODUCE**
- Procure CentOS 7.8 Linux OS instance
- Patch OS with latest updates; reboot.
*sudo yum update*
*sudo shutdown -r -time 0*
- Follow steps in https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest to setup azure cli repo.

*sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc*

*sudo sh -c 'echo -e "[azure-cli]
name=Azure CLI
baseurl=https://packages.microsoft.com/yumrepos/azure-cli
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'*

- Install azure-cli version 2.4.0, 2.5.0 or 2.5.1 (pick one):
*sudo yum install azure-cli-2.4.0-1.el7.x86_64*
OR
*sudo yum install azure-cli-2.5.0-1.el7.x86_64*
OR
*sudo yum install azure-cli-2.5.1-1.el7.x86_64*

- Login to your azure subscription.
az login

- Create a bash script similar to the following which will try to create the azure appservice environment using the *az appservice ase create* command.

#!/bin/bash
aseRgName="ASE_RESOURCE_GROUP_NAME_HERE"
aseName="ASE_NAME_HERE"
aseVnetName="VNET_NAME_CONTAINING_SUBNET_THAT_ASE_WILL_BE_TIED_TO"
aseVnetRgName="VNET_RESOURCE_GROUP_NAME_HERE"
aseSubnetName="NAME_OF_SUBNET_TO_ASSOCIATE_WITH_ASE_HERE"
aseSubnetId=$(az network vnet subnet list --resource-group $aseVnetRgName --vnet-name $aseVnetName --query "[].id" -o tsv | grep $aseSubnetName)
aseFrontEndScaleFactor="15"
aseFrontEndSku="I1"
aseVirtualIpType="Internal"
aseRegionName="southcentralus"

az appservice ase create -n $aseName -g $aseRgName --subnet $aseSubnetId --ignore-subnet-size-validation --ignore-network-security-group --ignore-route-table --front-end-sku $aseFrontEndSku --front-end-scale-factor $aseFrontEndScaleFactor --virtual-ip-type $aseVirtualIpType --location $aseRegionName --subscription $azSubscription --no-wait

- Run the script; notice that in version 2.4.0, 2.5.0 or 2.5.1the *az appservice ase create* command throws the error mentioned.

**EXPECTED BEHAVIOR**
The *ase appservice ase create* command succeeds and the appservice environment is successfully provisioned.

To see the expected behavior, uninstall 2.4.0, 2.5.0 or 2.5.1; then install 2.3.1 and re-run the steps to reproduce listed above, notice that the command succeeds.

*sudo yum remove azure-cli*
*sudo yum install azure-cli-2.3.1-1.el7.x86_64*
*Repeat the repro steps listed above*

**ENVIRONMENT SUMMARY**
- CentOS 7.8
- Latest OS patches
- Azure cli version 2.4.0, 2.5.0 or 2.5.1

**Comment by panchagnula** [comment]
@tocorobo can you run your script with --debug flag and share the log details if possible? Thanks!

**Comment by yonzhan** [comment]
appservice

**Comment by tocorobo** [comment]
> @tocorobo can you run your script with --debug flag and share the log details if possible? Thanks!

Sure thing; here's some redacted output of that; I hope it is helpful:

------------------------------------------
Create App Service Environment...
Getting management service client client_type=ResourceManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
adal-python : REDACTED - Authority:Performing instance discovery: ...
adal-python : REDACTED - Authority:Performing static instance discovery
adal-python : REDACTED - Authority:Authority validated via static instance discovery
adal-python : REDACTED - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : REDACTED - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : REDACTED - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : REDACTED - CacheDriver:Found 5 potential entries.
adal-python : REDACTED - CacheDriver:Resource specific token found.
adal-python : REDACTED - CacheDriver:Returning token from cache lookup, AccessTokenId: b'REDACTED_AccessTokenId=', RefreshTokenId: b'REDACTED_RefreshTokenId='
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/REDACTED_SUBSCRIPTION_ID/resourcegroups/REDACTED_ASE_RESOURCE_GROUP/providers/Microsoft.Resources/deployments/cli_ase_deploy_F4qhBOl14rlNIQKz?api-version=2019-10-01'
msrest.http_logger : Request method: 'PUT'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Content-Length': '827'
msrest.http_logger :     'User-Agent': 'python/3.6.8 (Linux-3.10.0-1127.el7.x86_64-x86_64-with-centos-7.8.2003-Core) msrest/0.6.9 msrest_azure/0.6.3 azure-mgmt-resource/9.0.0 Azure-SDK-For-Python AZURECLI/2.5.1 (RPM)'
msrest.http_logger : Request body:
msrest.http_logger : {"template": {"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#", "contentVersion": "1.0.0.0", "parameters": {}, "variables": {}, "resources": [{"name": "REDACTED_ASE", "type": "Microsoft.Web/hostingEnvironments", "location": "southcentralus", "apiVersion": "2019-02-01", "kind": "ASEV2", "tags": null, "properties": {"name": "REDACTED_ASE", "location": "southcentralus", "InternalLoadBalancingMode": 3, "virtualNetwork": {"Id": "/subscriptions/REDACTED_SUBSCRIPTION_ID/resourceGroups/REDACTED_RESOURCE_GROUP/providers/Microsoft.Network/virtualNetworks/REDACTED_VNET/subnets/REDACTED_SUBNET"}, "frontEndScaleFactor": 15, "multiSize": "Standard_D1_V2"}}], "outputs": {}}, "parameters": {}, "mode": "Incremental"}
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/REDACTED_SUBSCRIPTION_ID/resourcegroups/REDACTED_ASE_RESOURCE_GROUP/providers/Microsoft.Resources/deployments/cli_ase_deploy_F4qhBOl14rlNIQKz?api-version=2019-10-01 HTTP/1.1" 400 233
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-failure-cause': 'gateway'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger :     'x-ms-request-id': '94da1204-6af0-4dcd-97b4-43453ab60d22'
msrest.http_logger :     'x-ms-correlation-request-id': '94da1204-6af0-4dcd-97b4-43453ab60d22'
msrest.http_logger :     'x-ms-routing-request-id': 'CANADAEAST:20200507T045817Z:94da1204-6af0-4dcd-97b4-43453ab60d22'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Thu, 07 May 2020 04:58:16 GMT'
msrest.http_logger :     'Content-Length': '233'
msrest.http_logger : Response content:
msrest.http_logger : {"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: 'Could not find member 'template' on object of type 'DeploymentDefinition'. Path 'template', line 1, position 12.'."}}
msrest.exceptions : The request content was invalid and could not be deserialized: 'Could not find member 'template' on object of type 'DeploymentDefinition'. Path 'template', line 1, position 12.'.
cli.azure.cli.core.util : The request content was invalid and could not be deserialized: 'Could not find member 'template' on object of type 'DeploymentDefinition'. Path 'template', line 1, position 12.'.
The request content was invalid and could not be deserialized: 'Could not find member 'template' on object of type 'DeploymentDefinition'. Path 'template', line 1, position 12.'.
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f9c0abf0a60>]
command ran in 2.634 seconds
------------------------------------------

**Comment by panchagnula** [comment]
@madsd I am checking with you on this first before I go find someone else to investigate - since we haven't changed anything specific to this command since the time you added support & we don't see the tests added here fail. Thanks!

**Comment by panchagnula** [comment]
Closing this since the fix is merged
