### ISSUE TITLE
AZ CLI equivalent command for powershell command Reset-HubRouter 

### ISSUE THREAD

**Issue by syfarogh** [Azure/azure-cli#13363]
**Resource Provider**

Microsoft.Network

**Description of Feature or Work Requested**

We are adding a new command in powershell for Virtual Hub resource. The command in powershell will be **Reset-HubRouter** and will do a Put on the Virtual hub resource if RoutingState field of hub (Virtualhub.properties.RoutingState) is set to Failed.

Minimum API Version Required

Swagger Link

Target Date

Depends on Nrp Release.

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
@syfarogh Please provide swagger spec PR link and ETA of the release.

**Comment by syfarogh** [comment]
@nagula-ritvika will add link for swagger PR adding RoutingState Field.

Relase ETA is end of May.

**Comment by nagula-ritvika** [comment]
Hi @yonzhan  : This is the swagger link : https://github.com/Azure/azure-rest-api-specs/pull/9385

**Comment by nagula-ritvika** [comment]
This is the PS Design Review : https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/588
