### ISSUE TITLE
az account get-access-token failing for resource 'https://database.windows.net/'

### ISSUE THREAD

**Issue by haymansfield** [Azure/azure-cli#13360]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named 'https://database.windows.net/' was not found in the tenant named ***. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: *****\r\nCorrelation ID: *****\r\nTimestamp: 2020-05-06 13:30:38Z","error_codes":[500011],"timestamp":"2020-05-06 13:30:38Z","trace_id":"*******","correlation_id":"*******","error_uri":"https://login.microsoftonline.com/error?code=500011"}
Traceback (most recent call last):
pip-install-7cl6xofh\knack\knack\cli.py, ln 215, in invoke
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --subscription {} --resource 'https://database.windows.net/'`

## Expected Behavior

An access token is returned I can use for Azure sql authentication

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1

Extensions:
azure-devops 0.16.0

```

**Comment by yonzhan** [comment]
add to S170

**Comment by haymansfield** [comment]
To shed a little light, the following **will** get me a token:

az account get-access-token --subscription {} --resource https://database.windows.net

But this won't:

az account get-access-token --subscription {} --resource 'https://database.windows.net/'

**Comment by jiasli** [comment]
I am not able to reproduce it anymore:

```
> az account get-access-token --resource https://database.windows.net
{
  "accessToken": "...",
  "expiresOn": "2020-07-15 12:16:16.784885",
  "subscription": "0b1f6471-1bf0-4dda-aec3-cb9272f09590",
  "tenant": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
  "tokenType": "Bearer"
}

> az account get-access-token --resource https://database.windows.net/
{
  "accessToken": "...",
  "expiresOn": "2020-07-15 12:16:23.451931",
  "subscription": "0b1f6471-1bf0-4dda-aec3-cb9272f09590",
  "tenant": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
  "tokenType": "Bearer"
}
```

For SQL service, now both resource IDs are supported:

- `https://database.windows.net`
- `https://database.windows.net/`

If I remember correctly, there is a known issue that some resource providers require the trailing slash `/` while some don't: 

https://github.com/Azure/azure-cli/blob/81ff7bfad67383a9d8aba2e2e0bd5a7457b0f8b9/src/azure-cli-core/azure/cli/core/cloud.py#L243-L259

\+ @azureSQLGitHub to help confirm.
