### ISSUE TITLE
Weird behavior with create

### ISSUE THREAD

**Issue by pjboardman** [Azure/azure-cli#13364]
Is create not idempotent (like other az cli resource creation)? When I run subsequent times, I get this error message:
Operation failed with status: 200. Details: Resource state Succeeded

This causes Azure DevOps release pipelines to fail

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84bf7aaa-0925-70d6-63a9-d51debfa403b
* Version Independent ID: 3c5ee9dc-dd0a-480c-556b-e1ae2246f30a
* Content: [az signalr](https://docs.microsoft.com/en-us/cli/azure/signalr?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/signalr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/signalr/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
signalr

**Comment by chenkennt** [comment]
@zackliu please help take a look

**Comment by zackliu** [comment]
@pjboardman Currently we have a bug in checking the response status code for the existing resource using `az signalr create`. That will be fixed once https://github.com/Azure/azure-rest-api-specs/pull/9228 is merged and new SDK is release. Before that, the workaround is using `az signalr update`.

**Comment by zackliu** [comment]
Already fixed in the current azure-cli version 2.9.1.

**Comment by pjboardman** [comment]
What do you mean by ”already"?

**Comment by zackliu** [comment]
The bug should has been fixed. Can not reproduce in 2.9.1. Did you still have the issue?

**Comment by RakeshMohanMSFT** [comment]
If you are still facing this issue, please reopen.
