### ISSUE TITLE
az aks nodepool add: --enable-node-public-ip unrecognized

### ISSUE THREAD

**Issue by marcusjwhelan** [Azure/azure-cli#13378]
In the docs it says this is an available argument but when trying to use it on either `az aks create` or `az aks nodepool add` it fails with

`az: error: unrecognized arguments: --enable-node-public-ip`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
thanks for reporting, routing to appropriate team

**Comment by jluk** [comment]
You must use 0.4.43 or greater to receive the command. Please upgrade your preview extension, closing as a result as I am seeing the correct command with the required version.

https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#assign-a-public-ip-per-node-for-your-node-pools-preview
