### ISSUE TITLE
How to restrict access to Azure Container Registry to a particular subnet in Virtual network

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/azure-cli#13374]
Hi Team,

Could you please tell how we can restrict access to azure container registry to particular network ,previously we where able to do via portal itself

**Comment by yonzhan** [comment]
ACR

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by yugangw-msft** [comment]
Using old service point can be accomplished here through Azure CLI
   https://docs.microsoft.com/en-us/azure/container-registry/container-registry-vnet

But private endpoint is more recommended for better isolation which has support from both Azure CLI and Portal
   https://docs.microsoft.com/en-us/azure/container-registry/container-registry-private-link

**Comment by nidiculageorge** [comment]
Thanks so much for the update .So what you recommend is private endpoint

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-private-link
