### ISSUE TITLE
--only-show-errors should be added to the docs in the global parameter list

### ISSUE THREAD

**Issue by jkewley** [Azure/azure-cli#13384]
Some individual commands include this option, but according to https://github.com/Azure/azure-cli/issues/6341 the option was added globally. It should be added to the 'Global Parameters' section included in every command documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeedb9a7-2aed-6727-4cfb-1515809d676e
* Version Independent ID: 2c83180d-22ad-db42-e2eb-f27f11977963
* Content: [az](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/profile/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/profile/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @jiasli  pls have a look, thanks

**Comment by yonzhan** [comment]
add to S169

**Comment by jiasli** [comment]
This is known issue of doc generation. We are internally working with doc team to fix it. Thanks for your patience.

**Comment by jiasli** [comment]
This issue has been fixed in the doc generation and will go live in next CLI release.
