### ISSUE TITLE
 az image update --tags replaces all tags with new tags

### ISSUE THREAD

**Issue by azilber** [Azure/azure-cli#13380]
Performing 
 az image update .... --tags test=test test2=test2
on an image, removes all existing tags and replaces them with the new tag list.

The examples (from  az image update -h) specifically say:
Examples
    **Add or update tags.**
        az image update -n ImageName -g ResourceGroup --tags tag1=val1 tag2=val2

The help for tags says:
Arguments
    --tags              : Space-separated tags: key[=value] [key[=value] ...]. Use '' to clear
                          existing tags.

So there exists a specific option to clear all tags.  Yet, instead of adding or updating tags, all tags are cleared then replaced with new tags.  This is broken behavior.

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look? thanks

**Comment by qwordy** [comment]
@zhoxing-ms I remember you contributed a commit about tags. What's your idea of this issue?

**Comment by zhoxing-ms** [comment]
Hi, @azilber In fact, the `--tags` parameter in the update command of all resources directly overwrites the original tags, which is by our design.
If you want to add tags incrementally, please try using the command `az resource tag --ids {resource-id} --tags {append-tag} -i`. 
If you still have any other questions, please feel free to let us know~

**Comment by azilber** [comment]
@zhoxing-ms this also does not work.  Same exact effect, all tags are deleted.   Additionally, -i isn't an available option:
"az: error: unrecognized arguments: -i"

For "azure-cli": "2.0.81"

**Comment by azilber** [comment]
@zhoxing-ms ok, using "azure-cli": "2.5.1" with the -i flag I can add tags.

Doing it the original way using -n and -g there's no way to add the -i flag.  It seems to only be doable when using RESOURCE ID.

**Comment by zhoxing-ms** [comment]
@azilber Yes, for now, only command `az resource tag` supports tagging resources incrementally, it already supports most scenarios, you can use `az resource tag -h` to see how it is used~

**Comment by yonzhan** [comment]
@azilber was your issue resolved?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
