### ISSUE TITLE
ACS: Resource group existence validation after creating SP

### ISSUE THREAD

**Issue by sauryadas** [Azure/azure-cli#1338]
Looks like we create the service principal first (which takes a while) and then validate if the resource group exists or not. Should we validate for rg first?
 

 
 
 
![ttt](https://cloud.githubusercontent.com/assets/15387759/20330005/933977dc-ab50-11e6-9d9d-046b900c4e18.png)

**Comment by mayurid** [comment]
@brendanburns to comment.
