### ISSUE TITLE
az login failed

### ISSUE THREAD

**Issue by frankliu20** [Azure/azure-cli#13389]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='api-dogfood.resources.windows-int.net', port=443): Max retries exceeded with url: /subscriptions?api-version=2019-06-01 (Caused by ResponseError('too many 500 error responses',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6

azure-cli 2.2.0 *

Extensions:
aks-preview 0.4.42
interactive 0.4.4
spring-cloud 0.2.2

```

**Comment by yungezz** [comment]
hi @arrownj could  you pls have a look? thanks

**Comment by ybelMekk** [comment]
plus 1 one this
On G.Actions:
Run az login --service-principal -u $AZURE_SP -p $AZURE_SP_PASSWORD --tenant $AZURE_SP_TENANT
  az login --service-principal -u $AZURE_SP -p $AZURE_SP_PASSWORD --tenant $AZURE_SP_TENANT
  shell: sh -e {0}
  env:
    AZURE_SP: ***
    AZURE_SP_PASSWORD: ***
    ARM_CLIENT_SECRET: ***
    AZURE_SP_TENANT: ***
    ARM_TENANT_ID: ***
    SUBSCRIPTION_ID: ***
    ARM_SUBSCRIPTION_ID: ***
    AZURE_STORAGE_ACCOUNT: navtestapimstorage
    AZURE_STORAGE_KEY: ***
    ARM_CLIENT_ID: ***
    ARM_ACCESS_KEY: ***
    APIM_NAME: test-apim-nav
    RESOURCE_GROUP: nav_test_apim
    ACTUAL_SIZE: 12
    GENERATED_SIZE: 17
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/__main__.py", line 33, in <module>
    az_cli = get_default_cli()
  File "/usr/local/lib/python3.7/dist-packages/azure/cli/core/__init__.py", line 628, in get_default_cli

**Comment by arrownj** [comment]
Hi @frankliu20 , why the endpoint in your log is `api-dogfood.resources.windows-int.net` ? Is there any special settings in your case ? Maybe you can share more about your environment to help us investigate the problem. Thanks

**Comment by arrownj** [comment]
Close this first for no feedback for a long time.
