### ISSUE TITLE
az blob exists cmd

### ISSUE THREAD

**Issue by kpard** [Azure/azure-cli#13383]
## Describe the bug

**Command Name**
`az storage blob exists`

**Errors:**
```
/usr/lib64/az/lib/python2.7/site-packages/_cffi_backend.so: undefined symbol: PyUnicodeUCS4_FromUnicode
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 523, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 291, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
storage/v2018_11_09/blob/_encryption.py, ln 13, in <module>
    from cryptography.hazmat.primitives.padding import PKCS7
cryptography/hazmat/primitives/padding.py, ln 13, in <module>
    from cryptography.hazmat.bindings._padding import lib
ImportError: /usr/lib64/az/lib/python2.7/site-packages/_cffi_backend.so: undefined symbol: PyUnicodeUCS4_FromUnicode
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob exists --container-name {} --name {} --timeout {} --only-show-errors`

## Environment Summary
```
Linux-3.10.0-957.43.1.el7.x86_64-x86_64-with-redhat-7.6-Maipo
Python 2.7.16
Shell: bash

azure-cli 2.0.76

```

**Comment by yungezz** [comment]
hi @Juliehzl could you have a look?

**Comment by Juliehzl** [comment]
@kpard  I cannot reproduce your error with python 3 installed in linux. I will recommend you to upgrade the python version because CLI doesn't plan to support python 2 because python 2 is deprecated from 2020/01/01.

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
@kpard any feedback?

**Comment by yonzhan** [comment]
@kpard any feedback?

**Comment by Juliehzl** [comment]
Hi, because there is no response for several days, I will close the PR now and if you still have the problem, feel free to reopen it.
