### ISSUE TITLE
Creating a cname record - how to set the alias

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Azure/azure-cli#13382]
I've executed 
`az network dns record-set cname create --resource-group $dnsResourceGroup --zone-name $zone --name jfl` but the "Alias" value is blank when I view the entry. 

How am I able to create a CNAME record (mycname) that points to example.mydomain.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bf2496b-338d-9d05-7c91-63b9ed576dae
* Version Independent ID: 0ae8e4a4-59ae-c756-9e5b-44239188882f
* Content: [az network dns record-set cname](https://docs.microsoft.com/en-us/cli/azure/network/dns/record-set/cname?view=azure-cli-latest#az-network-dns-record-set-cname-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jeanfrancoislarente** [comment]
For example, the "Value" is not set:

![image](https://user-images.githubusercontent.com/5884676/81339341-01dfa580-907c-11ea-9f58-5e49420ef03c.png)

![image](https://user-images.githubusercontent.com/5884676/81339391-1c198380-907c-11ea-9f21-f4b355d3d996.png)

**Comment by yungezz** [comment]
hi @MyronFanQiu could you have a look

**Comment by MyronFanQiu** [comment]
@jeanfrancoislarente Do you mean this command`az network dns record-set cname set-record -g MyResourceGroup -z www.mysite.com -n MyRecordSet -c www.contoso.com`?

**Comment by jeanfrancoislarente** [comment]
So this was definitely the solution, but I must say it's a bit confusing... Despite the notes of one recordset per, etc.

You create an A record, but you set a cname. Is there _any_ way that this can be (more) clarified in the docs? 

Thanks very much for the prompt response and help!

**Comment by sspott** [comment]
I'm having the same issue and don't seem to be able to get the Alias Record Set flag to set to YES?

I followed the commands above (and it doesn't seem to work), perhaps I'm missing something?

`az network dns record-set cname set-record -g MyResourceGroup -z www.mysite.com -n MyRecordSet -c www.contoso.com`

Any help would be appreciated!

**Comment by MyronFanQiu** [comment]
> I'm having the same issue and don't seem to be able to get the Alias Record Set flag to set to YES?
> 
> I followed the commands above (and it doesn't seem to work), perhaps I'm missing something?
> 
> `az network dns record-set cname set-record -g MyResourceGroup -z www.mysite.com -n MyRecordSet -c www.contoso.com`
> 
> Any help would be appreciated!

**Comment by MyronFanQiu** [comment]
@sspott Hi. Could you share more context? what's your purpose and what's the error?

**Comment by sspott** [comment]
Thanks so much for the fast reply!
 
The CLI command creates the record without issue `az network dns record-set cname set-record -g MyResourceGroup -z www.mysite.com -n MyRecordSet -c www.contoso.com`

The problem seems to be that when the CNAME is created there's no way to set the ALAIS RECORD SET flag to yes?

<img width="830" alt="dns2" src="https://user-images.githubusercontent.com/702888/86424665-25f0e900-bcb1-11ea-97c6-765cd58c3bbc.png">

**Comment by MyronFanQiu** [comment]
@sspott Looks like CLI cannot do it right now. I need check with service team about this one. I cannot find corresponding swagger spec as well.

**Comment by sspott** [comment]
Thanks for the follow-up, I've got a ticket going with Azure support, I'll gladly post any information I receive from them.

**Comment by MyronFanQiu** [comment]
Hi. I open an other issue. #14200. Let's close this one for now.
