### ISSUE TITLE
az login failure on macOS Catalina + Homebrew

### ISSUE THREAD

**Issue by alesniak303** [Azure/azure-cli#13405]
**Command Name**
`az login`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --allow-no-subscriptions`

Trying to:

az login --allow-no-subscriptions

right after initial installation via homebrew.

1.  Browser is launched
2. Entered log information
3. Redirect to localhost:8400 fails

It appears that Safari forces redirect to https, causing the failure.  I can work around this by using chrome.  It took me a while to realize that this due to Safari.  Perhaps it's worth documenting if it cannot be addressed.

## Environment Summary
```
macOS-10.15.4-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.5.1

```

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
@arrownj  please take a look

**Comment by alesniak303** [comment]
FYI. It seems that in Safari, if you have navigated to a hostname using SSL, it records that and subsequently redirects to SSL.  To then be able to use HTTP with that host, one has to go through a rather onerous procedure to remove that mapping.  This applies to localhost as well.

**Comment by yungezz** [comment]
hi @alesniak303 thanks for the updating, is it ok to close the issue now since its envrionment issue instead of Azure CLI? thanks.

**Comment by arrownj** [comment]
Hi @alesniak303 , actually not only Safari has this behavior, always all modern browsers have this behavior. Yes, we need to remove the SSL mapping cache from the browser to overcome the problem.

So can I close this issue first as it is just a browser usage problem? Thanks

**Comment by arrownj** [comment]
Hi @alesniak303 , I will close it first. If you have other concerns, you can reopen it. Thanks
