### ISSUE TITLE
az vm list-skus --zone is not working

### ISSUE THREAD

**Issue by jaepak0320** [Azure/azure-cli#13407]
az vm list-skus --zone is not working for all resourceType as shown below commands. It would be better to mention it on public document mentioning it. It seems like --zone is checking a string instead of an array.
az vm list-skus -l uksouth -o table --query "[].{name:name, resourceType:resourceType, zones:length(locationInfo[].zones[])}" -z false
az vm list-skus -l uksouth -r hostGroups/hosts -o table --zone false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look? thanks

**Comment by jaepak0320** [comment]
Here is more information.

As shown below, hosts are not working for “--zone” parameter
I guess --zone is just checking a string instead of an array. locationInfo[].zone[] is an array.

az vm list-skus -l uksouth -o table --query "[].{name:name, resourceType:resourceType, zones:length(locationInfo[].zones[])}" -z false
[cid:image003.png@01D62557.6760D4F0]

az vm list-skus -l uksouth -r hostGroups/hosts -z true -o table
az vm list-skus -l uksouth -r hostGroups/hosts -z false -o table
[cid:image008.png@01D62557.6760D4F0]

If you have manual query for array zone as below, it works as expected.

az vm list-skus -l uksouth -r hostGroups/hosts --query "[?not_null(locationInfo[].zones[])]" -o table                    //list skus supporting zones
az vm list-skus -l uksouth -r hostGroups/hosts --query "[?!not_null(locationInfo[].zones[])]" -o table                 //list skus not supporting zones
[cid:image009.jpg@01D62557.6760D4F0]

Best regards,
Jae Pak

**Comment by qwordy** [comment]
I have reproduced the issue and found the root cause.
```
--zone -z
Show all vm size supporting availability zones.
```
This parameter limits the resource type to vm. When `-z` is set, only vm skus will be shown. It's not reasonable. I will update it.

**Comment by qwordy** [comment]
I have written a PR to solve this issue.

**Comment by qwordy** [comment]
Would please upgrade to latest Azure CLI and have a try? It fixes this issue.

**Comment by jaepak0320** [comment]
on cloudshell (I guess it is updated to the latest all the times), below command didn't return anything still.
az vm list-skus -l uksouth -r hostGroups/hosts -o table -z

**Comment by qwordy** [comment]
Result in Azure CLI 2.6.0
```
> az vm list-skus -l uksouth -r hostGroups/hosts -o table --zone
ResourceType      Locations    Name        Zones    Restrictions
----------------  -----------  ----------  -------  --------------
hostGroups/hosts  uksouth      DSv3-Type1  1,2,3    None
hostGroups/hosts  uksouth      ESv3-Type1  1,2,3    None
hostGroups/hosts  uksouth      DSv3-Type2  1,2,3    None
hostGroups/hosts  uksouth      ESv3-Type2  1,2,3    None
hostGroups/hosts  uksouth      FSv2-Type2  1,3      None
```
Cloud Shell may need some days to get updated to latest version. It should not be a long time.

**Comment by jaepak0320** [comment]
Thank you. Just confirmed that it works fine on 2.6.0

**Comment by qwordy** [comment]
Glad to know that!

**Comment by qwordy** [comment]
> 
> 
> Result in Azure CLI 2.6.0
> 
> ```
> > az vm list-skus -l uksouth -r hostGroups/hosts -o table --zone
> ResourceType      Locations    Name        Zones    Restrictions
> ----------------  -----------  ----------  -------  --------------
> hostGroups/hosts  uksouth      DSv3-Type1  1,2,3    None
> hostGroups/hosts  uksouth      ESv3-Type1  1,2,3    None
> hostGroups/hosts  uksouth      DSv3-Type2  1,2,3    None
> hostGroups/hosts  uksouth      ESv3-Type2  1,2,3    None
> hostGroups/hosts  uksouth      FSv2-Type2  1,3      None
> ```
> 
> Cloud Shell may need some days to get updated to latest version. It should not be a long time.

@fengzhou-msft Should cloud shell upgrades before we announce a new version of CLI?
