### ISSUE TITLE
az webapp up fails from tutorial

### ISSUE THREAD

**Issue by icfly2** [Azure/azure-cli#13400]
## Describe the bug

Followed along the tutorial: https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-python-postgresql-app?tabs=bash
and ran the comand 

`az webapp up --plan myAppServicePlan --location westus2 --sku B1 --name <my name>`

wher <my name > was a legal, most likely unique app name
**Command Name**
`az webapp up`

**Errors:**
```
'registrationState'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 686, in _run_job
    cmd_copy.exception_handler(ex)
...
python3.6/site-packages/msrestazure/tools.py, ln 57, in register_rp_hook
    if not _register_rp(session, url_prefix, rp_name):
python3.6/site-packages/msrestazure/tools.py, ln 102, in _register_rp
    if rp_info['registrationState'] == 'Registered':
KeyError: 'registrationState'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Follow tutorial https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-python-postgresql-app

on a  fresh azure account from Ubuntu 18.04 box with a fresh az cli install and an otherwise working python3 version Faild at, after successfully creating the DB:
-`az webapp up --plan myAppServicePlan --location westus2 --sku B1 --name <my name>`

## Environment Summary
```
Linux-4.15.0-99-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1

Extensions:
db-up 0.1.13

```

**Comment by icfly2** [comment]
adding   --resource-group myResourceGroup to the webapp up command (the same resource group ans the postgres DB appears to fix it) It would benice to either add this to the docs or tutorial and example, if this really is the fix.

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@icfly2 thanks for reporting, we had an issue with interpreting the RG for an app, which has since been fixed,. is it possible for you to re-try this with the latest version of CLI and let us know if you still see this (i.e not needing to run the command with -g parameter)

**Comment by panchagnula** [comment]
closing this due to lack of response. Please try with the latest CLI version and let us know if you still see this issue
