### ISSUE TITLE
ACR: improve the parameter validation logic of image import command

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#13415]
For tracking: the code in https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/import.py#L50-L85 should be moved to `_validators.py`

This is to follow up comments from PR review of https://github.com/Azure/azure-cli/pull/13392

**Comment by yonzhan** [comment]
ACR

**Comment by yugangw-msft** [comment]
we can live with this and let the next update on this command pick up
