### ISSUE TITLE
[CI] CI on dev branch should use Knack's master branch

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#13417]
CI on `dev` branch should use https://github.com/microsoft/knack `master` branch, instead of the public [Knack on PyPI](https://pypi.org/project/knack/). 

Otherwise, a compatibility issue with Knack can only be discovered **after Knack is released to PyPI**. To fix it, we will have to release Knack again, as shown in https://github.com/microsoft/knack/pull/205 and https://github.com/microsoft/knack/pull/206. This causes PyPI to contain un-usable Knack versions. 

On the other hand, CI on `release` branch should use [Knack on PyPI](https://pypi.org/project/knack/).

**Comment by yonzhan** [comment]
add to S170

**Comment by jiasli** [comment]
I think the same applies to azdev https://github.com/Azure/azure-cli-dev-tools. The CI should use the source code of azdev.

**Comment by yonzhan** [comment]
add to S172

**Comment by jiasli** [comment]
`azdev`'s change was done in https://github.com/Azure/azure-cli/pull/14156.

**Comment by haroldrandom** [comment]
Close as https://github.com/Azure/azure-cli/issues/14301
