### ISSUE TITLE
Error running az  -h from ubuntu-20.04 on wsl2

### ISSUE THREAD

**Issue by pauldotyu** [Azure/azure-cli#13416]
## Describe the bug

**Command Name**
`az appservice`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice --help`

## Environment Summary
```
Linux-4.19.84-microsoft-standard-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
appservice

**Comment by panchagnula** [comment]
@pauldotyu is this occurring with az appservice command group only? what happens if you run say az account ?

**Comment by panchagnula** [comment]
This doesn't seem like App service issue but something with the CLI install. Moving to core.

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by panchagnula** [comment]
Same as  https://github.com/Azure/azure-cli/issues/13644

**Comment by fengzhou-msft** [comment]
Please see instructions [here](https://github.com/Azure/azure-cli/issues/14011#issue-640943121).
