### ISSUE TITLE
What is the point of these commands if you cant tell it what App service to work with?

### ISSUE THREAD

**Issue by StingyJack** [Azure/azure-cli#13428]
The deployment user/pass are different on every app service. Which app service is this command going to show me the credentials for if I dont name one as a parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea54d36-cb69-577c-e114-2c4bd0e33728
* Version Independent ID: 812e7aa5-2e8a-f9ef-d922-df188bd6275a
* Content: [az webapp deployment user](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/user?view=azure-cli-latest#az-webapp-deployment-user-show)
* Content Source: [latest/docs-ref-autogen/webapp/deployment/user.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/deployment/user.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by StingyJack** [comment]
@yonzhan - i dont understand your response.

**Comment by yonzhan** [comment]
webapp CLI commands are owned by service team and they will look into this.

**Comment by panchagnula** [comment]
@StingyJack I don't understand the question here - please elaborate. what do you mean which app service? App service is an Azure service - what are you trying to find?

**Comment by StingyJack** [comment]
This is because the presentation of deployment credentials in Azure is very misleading. Being only visible from an app service, without any highlight to say otherwise, it looks like a per app service setting. This command takes no app service name as a parameter.
