### ISSUE TITLE
az webapp up: How do I get permissions for this ?

### ISSUE THREAD

**Issue by charlvdm101** [Azure/azure-cli#13427]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
[Errno 13] Permission denied: 'C:\\\\python37.zip'
Traceback (most recent call last):
Temp\pip-install-7cl6xofh\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 631, in execute
azure\cli\core\commands\__init__.py, ln 695, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 686, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 55, in _polish_bad_errors
azure\cli\core\commands\__init__.py, ln 665, in _run_job
azure\cli\core\commands\__init__.py, ln 324, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 574, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 3282, in webapp_up
azure\cli\command_modules\appservice\_create_util.py, ln 37, in zip_contents_from_dir
Microsoft SDKs\Azure\CLI2\lib\zipfile.py, ln 1090, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'C:\\\\python37.zip'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up -n {} -g {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@charlvdm101 az webapp up needs to run from the context of the query of the directory where the code to deploy is looks like you are running from DIR where you have Python is installed & since Az CLI uses python we cannot run webapp up in context of this. Can you please try from a different folder & check if you see the same issue? Thanks!

**Comment by panchagnula** [comment]
closing due to lack of response.
