### ISSUE TITLE
Failed to create Keyvault certificate

### ISSUE THREAD

**Issue by ramganesh19** [Azure/azure-cli#13424]
## Describe the bug

**Command Name**
`az keyvault certificate get-default-policy`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault certificate get-default-policy --output {}`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by yungezz** [comment]
duplicate with https://github.com/Azure/azure-cli/issues/13426, close this one
