### ISSUE TITLE
error when trying to delete a resource group

### ISSUE THREAD

**Issue by dsotomstecs** [Azure/azure-cli#13422]
## Describe the bug

**Command Name**
`az group delete`

**Errors:**
```
az: error: unrecognized arguments: --ues
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group delete --name {} --no-wait --ues`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S171

**Comment by zhoxing-ms** [comment]
@dsotomstecs Hi, there is no `--ues` parameter in command `az group delete`. You want to enter the `--yes` parameter, right?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
