### ISSUE TITLE
Failed to create the certificate

### ISSUE THREAD

**Issue by ramganesh19** [Azure/azure-cli#13426]
## Describe the bug

**Command Name**
`az keyvault certificate create`

**Errors:**
```
Error occurred in request., HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault certificate create --vault-name {} --name {} --policy {}`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by ramganesh19** [comment]
Below is command 
keyvault_name=mykeyvault
az keyvault create --resource-group myResourceGroupAutomate --name $keyvault_name --enabled-for-deployment

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by yungezz** [comment]
hi @ramganesh19  did you see the error in Cloudshell? If yes, this is a known Cloudshell issue. Cloudshell team is looking at it. To workaround, pls use local Azure CLI on local machine.

**Comment by yungezz** [comment]
duplicate with https://github.com/Azure/azure-cli/issues/13425

**Comment by bim-msft** [comment]
Hi @ramganesh19 which environment are you in? Are you running this in CloudShell?
Based on my knowledge, one possible reason for this is your keyvault name is too long, I'm not sure if this would be suitable with your case.

**Comment by bim-msft** [comment]
Closing it due to longtime inactivity, feel free to reopen it anytime if you need additional help.

**Comment by bim-msft** [comment]
Closing it due to longtime inactivity, feel free to reopen it anytime if you need additional help.
