### ISSUE TITLE
Allocating IPs?

### ISSUE THREAD

**Issue by howardjones** [Azure/azure-cli#13436]
Is there any method to allocate the next available IP in a prefix? Or at least find the IP address to use when creating an actual Public IP resource?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f494d2d1-07a1-3ac8-fc2f-6aaddd340959
* Version Independent ID: c7e19a80-0c3d-268c-643d-3b2a8dde4027
* Content: [az network public-ip prefix](https://docs.microsoft.com/en-us/cli/azure/network/public-ip/prefix?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S170

**Comment by howardjones** [comment]
I found the answer eventually - it's done from the `az network public-ip create` command, not the prefix, but it would be much clearer if there was some pointer there.

**Comment by MyronFanQiu** [comment]
Hi. I checked the help message of `az network public-ip show` and we do have an example to show the actual ip address of a Azure Public IP.

**Comment by MyronFanQiu** [comment]
closed this issue since they should be solved. Feel free to reopen it.
