### ISSUE TITLE
Docker image is missing ssh-keygen

### ISSUE THREAD

**Issue by brendandburns** [Azure/azure-cli#1343]
Many tools expect to be able to make keys, but the command is missing from the `az-cli` docker image.

**Comment by jdumars** [comment]
Workaround until the image is changed:
```apk update && apk add openssh
ssh-keygen
```
Also handy are dependencies to enable curl against https:
```
apk add ca-certificates && update-ca-certificates && apk add openssl
```

**Comment by derekbekoe** [comment]
I'll address this as part of https://github.com/Azure/azure-cli/pull/1336
