### ISSUE TITLE
Powershell command equivalent to "az keyvault certificate pending merge" cli command

### ISSUE THREAD

**Issue by sanjay1913** [Azure/azure-cli#13438]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
@bim-msft  please take a look

**Comment by yungezz** [comment]
feature request

**Comment by bim-msft** [comment]
@sanjay1913 Hi, I guess you want to use an equivalent command to `az keyvault certificate pending merge` in Azure Powershell? If yes, you should create an issue on Azure Powershell repo: https://github.com/Azure/azure-powershell , thanks!

**Comment by bim-msft** [comment]
@sanjay1913 Hi, I will close the issue due to long time inactivity. If the above solution doesn't work for you or you have something else need us to help with, feel free to reopen it and ping me, thanks!
