### ISSUE TITLE
CI is broken by the latest release of flake8 

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#13448]
CI is broken by the latest release of flake8 3.8.0: https://pypi.org/project/flake8/

https://dev.azure.com/azure-sdk/public/_build/results?buildId=388688&view=logs&j=10884592-6334-52bc-4a58-7b0259fa5909&t=c6210a79-6b8f-5f7c-861b-11eaae91f848&l=366

```
1     E225 missing whitespace around operator
76    E741 ambiguous variable name 'l'
8     F522 '...'.format(...) has unused named argument(s): remote
19    F523 '...'.format(...) has unused arguments at position(s): 0
4     F541 f-string is missing placeholders
```

We need to do any of these:

1. Lock flake8 version to 3.7.9
2. Disable these errors in `.flake8` file
3. Fix the violations in the code

**Comment by yonzhan** [comment]
add to S169
