### ISSUE TITLE
Deployment of ARM template with az deployment group fails during validation with encoding error

### ISSUE THREAD

**Issue by hcrutz** [Azure/azure-cli#13443]
#12648 # **This is autogenerated. Please review and update as needed.**

## Describe the bug
impossible to deploy an arm template because of encoding/converting error, where no special characters exist. I tried different file encodings, but without change.
I have three similar templates for logic apps, but one can't be deployed.

**Command Name**
`az deployment group create`

**Errors:**
```
{'additionalProperties': {}, 'code': 'InvalidRequestContent', 'message': "The request content was invalid and could not be deserialized: 'Unable to translate bytes [FC] at index 303 from specified code page to Unicode.'.", 'target': None, 'details': None, 'additionalInfo': None}
```

## To Reproduce:
Just deploy/validate the attached template and parameter file.
The referenced API connections are not part of the template - don't know if they are needed for debug this error
[FiBu.zip](https://github.com/Azure/azure-cli/files/4612601/FiBu.zip)

- _Put any pre-requisite steps here..._
- `az deployment group create -g {} --template-file {} --parameters {} --verbose`

## Expected Behavior
The template should be deployed, or a better error description should clarify the problem
## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1

Extensions:
eventgrid 0.2.1

```

**Comment by yungezz** [comment]
hi @zhoxing-ms could you pls have a look? thanks

**Comment by yonzhan** [comment]
add to S170

**Comment by hcrutz** [comment]
I forgot to mention, that the deployment with the classic visual studio powershell deployment script works fine with the attached arm template.
Could you reproduce this problem? 
Any info's when this could be fixed?

**Comment by zhoxing-ms** [comment]
Hi @hcrutz, this seems to be the same problem as #13316. 
It has been fixed in the version 2.6.0 of CLI, could you please upgrade the CLI version to have a try?

**Comment by hcrutz** [comment]
Hi @zhoxing-ms , you're right, I could deploy the template with 2.6. 
Do you know how/when new versions are deployed to MS hosted Agents? The agent still runs version 2.5.1.

**Comment by zhoxing-ms** [comment]
@hcrutz The version of CLI is automatically updated periodically in the Azure DevOps Pipeline.

If you are in a hurry to upgrade CLI, you can consider adding a bash task to the Pipeline:
1. Use `pip install azure-cli==2.6.0` in the bash task script to install the latest version of azure-cli
2. You might need to add command `az login` to the script to login for CLI, the account and password can be placed in `Pipelines->Variables->Pipeline variables` for management, and the lock symbol can be clicked for confidentiality management.
