### ISSUE TITLE
az keyvault key download failing on ubuntu

### ISSUE THREAD

**Issue by ashwarn** [Azure/azure-cli#13457]
## Describe the bug

**Command Name**
`az keyvault key show`

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
<frozen importlib._bootstrap>, ln 961, in _find_and_load_unlocked
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault key show`

## Environment Summary
```
Linux-5.4.0-29-generic-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81 *

Extensions:
azure-devops 0.17.0

```

**Comment by yungezz** [comment]
hi @bim-msft could you pls have a look?thanks

**Comment by bim-msft** [comment]
@ashwarn Hi, could you upgrade your CLI to the latest version? I cannot reproduce this issue using https://shell.azure.com/
You may also try `pip install azure-keyvault==1.1.0` to fix it.

**Comment by ashwarn** [comment]
Sure, I will do that and let you know.

**Comment by bim-msft** [comment]
@ashwarn Hi, we are going to close the issue due to long time inactivity. If you have anything unresolved, just feel free to reopen this and I will continue to follow up this.

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/19640#issuecomment-1148202854
