### ISSUE TITLE
Windows nodepool is not supported error with azure-cli version 2.4.0 

### ISSUE THREAD

**Issue by VikasPullagura-MSFT** [Azure/azure-cli#13453]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
In the latest cli version (azure cloudshell `azure-cli    2.4.0 *`) getting error while adding windows node pool to aks cluster the Error is **Windows nodepool is not supported**

**To Reproduce**
Here is the tutorial [link](https://docs.microsoft.com/en-us/azure/aks/windows-container-cli#add-a-windows-server-node-pool)
Below are commands to reproduce the issue:

```
az aks create --resource-group rgname --name AKSCluster --node-count 2 --enable-addons monitoring --kubernetes-version 1.16.7 --generate-ssh-keys --network-plugin azure

az aks nodepool add --resource-group rgname --cluster-name AKSCluster --os-type Windows --name npwin --node-count 1 --kubernetes-version 1.16.7
```
Error screenshot with --debug option:

![image](https://user-images.githubusercontent.com/48944027/81658994-eba85f80-9456-11ea-8d0e-0c7fce6788e3.png)

**Expected behavior**
The Add a Windows Server node pool is working as expected in older cli version which I have on my local machine.

![image](https://user-images.githubusercontent.com/48944027/81659253-2b6f4700-9457-11ea-9ceb-b04b1607c96b.png)

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
aks

**Comment by yungezz** [comment]
hi @VikasPullagura-MSFT have you tried install `aks-preview` extension?

**Comment by VikasPullagura-MSFT** [comment]
Thanks tried installing the preview and issue is resolved.
