### ISSUE TITLE
Add support for listing and restoring deleted log analytics workspaces.

### ISSUE THREAD

**Issue by yoramsinger** [Azure/azure-cli#13456]
**Resource Provider**
Microsoft.OperationalInisghts

**Description of Feature or Work Requested**
We need to enable PS/CLI to recover a deleted workspace. Recovering a workspace is simply calling PUT (create) on a workspace resource, providing the original location. A workspace can be recovered during 14 days after it was deleted.

The UI for this feature will be available this week. The basic UI flow is this:
1.	Going to the Log Analytics Workspaces page in Azure portal.
2.	Clicking ‘Recover’ button.
3.	Listing deleted workspaces in a subscription.
4.	Selecting a workspace to recover.

The flow in API would be this:
1.	Calling GET /deletedWorksapces API to list the deleted workspaces and select the one you need (this is optional if you know your workspace resource id)
2.	Calling PUT /workspaces to re-create the workspace. If you specify just the location and empty properties, the workspace is recovered with the same properties it had when it was deleted. You can optionally provide properties that will override the ones we keep for that workspace. The behavior is PATCH like.

We need simple PS/CLI to do the same. I would  suggest the following syntaxes for PS, but we can apply the same for CLI:

1.	Get-AzOperationalInsightsDeletedWorkspaces -SubscriptionId <subscription-id>
Gets the recently deleted workspaces in a subscription.
2.	Recover-AzOperationalInsightsWorkspace -ResourceId <original-resource-id> -Location <azure-location>
Sends a PUT (Create) workspace with empty properties.

3.	Recover-AzOperationalInsightsWorkspace -SubscriptionId <subscription-id> -WorksapceName <ws-name>
Calls GET /deletedWorkspaces, locates the desired workspace by name, then calls PUT to recover the workspace.

4.	Recover-AzOperationalInsightsWorkspace -SubscriptionId <subscription-id> -WorksapceId <ws-id-guid>
Calls GET /deletedWorkspaces, locates the desired workspace by id, then calls PUT to recover the workspace.

5.	Recover-AzOperationalInsightsWorkspace -Workspace <workspace-object>
Takes a workspace object that was selected from the results in Get-AzOperationalInsightsDeletedWorkspaces, clears some read-only properties and calls PUT to recover the workspace with possibly patched properties.

Of course no need for SubscriptionId parameter if you run Select-AzSubscription. I’m not sure if we need to provide it at all.

Here is our current documentation for delete and recover workspaces:
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/delete-workspace

**Minimum API Version Required**
2020-03-01-preview

**Swagger Link**
Workspaces API is here:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/preview/2020-03-01-preview/Workspaces.json

deletedWorkspaces API is pending merge:
https://github.com/Azure/azure-rest-api-specs/pull/9401

**Target Date**
M3 29-May-2020

**Comment by yungezz** [comment]
feature request at monitor

**Comment by yonzhan** [comment]
add to S170
