### ISSUE TITLE
ssh

### ISSUE THREAD

**Issue by phillipmacon** [Azure/azure-cli#13463]
## Describe the bug

**Command Name**
``

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29
Python 3.8.2
Shell: sudo

azure-cli 2.0.81 *

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
@phillipmacon what is your detailed issue ?

**Comment by jiasli** [comment]
We will reopen this issue once more information is provided.
