### ISSUE TITLE
Using SPN parameter makes a reference to app ID not to Service Principal name 

### ISSUE THREAD

**Issue by Raul150** [Azure/azure-cli#13460]
In documentation is stated SPN attribute makes a reference to Service Principal which is not the case, if you try to add an actual name the command will brake and show the following error 
Unable to find user with spn '47f813e7-5968-4ee1-bad8-2b4dafa9c94c'
Unable to get object id from principal name.
I think is necessary to explain SPN can only be use by application and makes a reference to an application id

**Comment by yonzhan** [comment]
add to S170

**Comment by jiasli** [comment]
@Raul150, thanks for contacting us. Could you share more information?

1. The link to the doc you mentioned
2. The command you ran
3. The output when you run the command with `--debug`

**Comment by yonzhan** [comment]
@Raul150, any update?

**Comment by jiasli** [comment]
Hi @Raul150, if you have more information. Please kindly reply here.

**Comment by mibo32** [comment]
@jiasli  
´´´
$account = az ad signed-in-user show --query objectId --output tsv
az keyvault set-policy --name $kvName --spn $account --secret-permissions set
´´´

i get the same error as above

**Comment by jiasli** [comment]
@bim-msft, could you help take a look at this `keyvault` command?

```
$account = az ad signed-in-user show --query objectId --output tsv
az keyvault set-policy --name $kvName --spn $account --secret-permissions set
```

**Comment by bim-msft** [comment]
I have checked the code and did some tests but still have no idea about this.
Hi @mibo32 once we find the root cause we will notify you. As you said, temporarily you can use `--object-id` to workaround this.
