### ISSUE TITLE
Cannot get consumption after using batch service

### ISSUE THREAD

**Issue by fertinaz** [Azure/azure-cli#13468]
I'm using a shell script which follows these steps:
1- start_time
2- Create pool && job && task && run container && download outputs && delete resources
3- end_time; `az consumption usage list -o yaml --start-date  $start_time --end-date $end_time`

However, it doesn't return any usage. Is there a delay between what `az consumption` can read and the actual usage. I'm trying to provide a cost estimate for the 2nd step above once tasks are completed even if the entire process takes about 5 minutes.

Note that I tried different approaches. timestamps are created on my system (Toronto time), therefore I convert them to UTC but no success. I also tried the last 6 hours which returned an empty string. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e05c0768-9cfc-3b78-4f39-70a8c1f0b6bd
* Version Independent ID: b5e5d8fa-e84c-408a-3f49-19d245563abd
* Content: [az consumption usage](https://docs.microsoft.com/en-us/cli/azure/consumption/usage?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/consumption/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/consumption/_help.py)
* Service: **consumption**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by fertinaz** [comment]
Are there any updates on this?

**Comment by ms-premp** [comment]
This can take from 8 hours to 24 hours for usage to appear.

**Comment by ramaganesan-rg** [comment]
Resolving as per Prem's comments. Please feel free to re-open as needed.
