### ISSUE TITLE
Please explain what the commands do

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-cli#13465]
For example, what does "soft delete" do?  We should assume that many users reading this documentation don't know Azure language and terminology.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226e5769-f6c8-a480-db78-727fb96348ec
* Version Independent ID: 8ee06a2a-6eda-11be-3c8e-6ad948be207e
* Content: [az keyvault](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az-keyvault-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by awentzel** [comment]
I would also like to know more about what and how `--enable-rbac-authorization` works, as another example.

**Comment by yungezz** [comment]
hi @bim-msft could you pls help on this?

**Comment by bim-msft** [comment]
Hi @awentzel , you may refer to: https://docs.microsoft.com/en-us/azure/key-vault/general/overview-soft-delete for more soft-delete detail.
For `RBAC`, I think this is the most comprehensive doc: https://docs.microsoft.com/en-us/azure/role-based-access-control/overview . KeyVault use its `AccessPolicy` mechanism to do authorization as default, if you want to use `RBAC`, then you should specify `--enable-rbac-authorization`

**Comment by bim-msft** [comment]
Hi @awentzel I need to close this issue due to long time inactivity, please feel free to reopen it and let me know if you have anything unresolved, thanks!
