### ISSUE TITLE
Cannot set certificate transparency

### ISSUE THREAD

**Issue by fabicz** [Azure/azure-cli#13475]
## Describe the bug
Trying to create certificate request with policy incl. certificate transparency fails with "Cannot set Certificate Transparency for a manual enrollment."

**Command Name**
`az keyvault certificate create`

**Errors:**
```
Cannot set Certificate Transparency for a manual enrollment.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault certificate create --vault-name {} -n {} -p {}`

Policy JSON:
```
{
  "issuerParameters": {
    "certificateTransparency": true,
    "name": "Unknown"
  },
  "keyProperties": {
    "curve": null,
    "exportable": true,
    "keySize": 2048,
    "keyType": "RSA",
    "reuseKey": false
  },
  "secretProperties": {
    "contentType": "application/x-pkcs12"
  },
  "x509CertificateProperties": {
    "keyUsage": [
      "cRLSign",
      "dataEncipherment",
      "digitalSignature",
      "keyEncipherment",
      "keyAgreement",
      "keyCertSign"
    ],
    "subject": "CN=foobar.net",
    "validityInMonths": 24
  }
}
```

## Expected Behavior
Certificate request is created

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1

```

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by davej** [comment]
Apologies for the +1 but I'm also seeing this issue.

**Comment by yungezz** [comment]
hi @fabicz the error is from Azure Keyvault service

**Comment by sebansal** [comment]
@RandalliLama from key vault service team will be looking into it

**Comment by sebansal** [comment]
ping @RandalliLama

**Comment by sebansal** [comment]
@RandalliLama do we have internal ADO open to track?

**Comment by sebansal** [comment]
@RandalliLama for triaging

**Comment by sebansal** [comment]
This has been fixed and is no longer an issue.
#please-close
