### ISSUE TITLE
unexpected error on 'az aks create'

### ISSUE THREAD

**Issue by Kengo-Araki** [Azure/azure-cli#13477]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
invalid version number '1.16.7
'
Traceback (most recent call last):
pip-install-7cl6xofh\knack\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 631, in execute
cli\core\commands\__init__.py, ln 695, in _run_jobs_serially
cli\core\commands\__init__.py, ln 688, in _run_job
Temp\pip-install-7cl6xofh\six\six.py, ln 703, in reraise
cli\core\commands\__init__.py, ln 665, in _run_job
cli\core\commands\__init__.py, ln 324, in __call__
...
    self.parse(vstring)
CLI2\lib\distutils\version.py, ln 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '1.16.7
'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create \
--resource-group $RESOURCE_GROUP \
--name $AKS_CLUSTER_NAME \
--load-balancer-sku standard \
--location $REGION_NAME \
--kubernetes-version $VERSION \
--network-plugin azure \
--service-cidr 10.2.0.0/24 \
--dns-service-ip 10.2.0.10 \
--docker-bridge-address 172.17.0.1/16 \
--generate-ssh-keys \
--node-vm-size Standard_B2s \
--node-count 2
`

## Expected Behavior
create aks cluster

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Installer: 

azure-cli 2.5.1

```

**Comment by yonzhan** [comment]
aks

**Comment by bpdohall** [comment]
@Kengo-Araki - please verify that the version you are requesting is available in your target region. User the `az aks get-versions` command. For example, in eastus 1.16.7 is no longer a valid option:
```
$ az aks get-versions --location eastus --output table
KubernetesVersion    Upgrades
-------------------  -------------------------------------------------
1.18.2(preview)      None available
1.18.1(preview)      1.18.2(preview)
1.17.5(preview)      1.18.1(preview), 1.18.2(preview)
1.17.4(preview)      1.17.5(preview), 1.18.1(preview), 1.18.2(preview)
1.16.9               1.17.4(preview), 1.17.5(preview)
1.16.8               1.16.9, 1.17.4(preview), 1.17.5(preview)
1.15.11              1.16.8, 1.16.9
1.15.10              1.15.11, 1.16.8, 1.16.9
1.14.8               1.15.10, 1.15.11
1.14.7               1.14.8, 1.15.10, 1.15.11
```

**Comment by seanmck** [comment]
Closing per the comment above from @bpdohall. AKS only supports 2 patch releases per minor version. If the patch release specified is no longer supported, you will get this error.
