### ISSUE TITLE
support multiple cli command sessions run concurrently 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#1347]
The main thing is to protect file asserts under ~./azure 
1. The main files are `accessFile.json`, and `acccessTokens.json` which can be updated by commands automatically
2. For  some other files, which you have to run `az configure` interactively to update it, we don't need to concern. 

The goal is to get things reliably, and also take into considerations of creds sharing with xplat-cli
One option (cheap but not perfect) is to port `Azure_Configure_Dir` over like #1298. But even we take it,  to get things decent (when people forget to set the env var), we still need to protect under concurrent accesses.

Mark it as discussion for inputs

**Comment by tjprescott** [comment]
This is related to #1293.

**Comment by derekbekoe** [comment]
I believe there are two parts to this:

**Scenario 1**
I want to be able to run multiple cli command sessions run concurrently for the same account.

For this scenario, as @yugangw-msft mentioned, we need to protect concurrent access to `accessTokens.json` and `azureProfile.json`.

Concurrent access could occur if the cli sessions all needed to refresh an access token at the same time for example.
Currently, if this happens, one of the files _could_ become corrupt.

Unless xplat CLI does implement some file locking, I believe it has the same issue as described.

We can look at Python file locking to resolve this.
For example, https://docs.python.org/2/library/fcntl.html though this is specific to Unix.


**Scenario 2**
I want to be able to run multiple cli command sessions run concurrently for _multiple_ accounts.
This is the `AZURE_CONFIG_DIR` feature that's supported in xplat CLI and is what https://github.com/Azure/azure-cli/issues/1293 refers to.

Why not port the environment variable AZURE_CONFIG_DIR to Azure CLI 2.0?

- All the config directories that a user may create are not tracked by the CLI so users have to resort to aliases to remember the different configs they have.
- The multiple config directories do not address the concurrent access issues that can occur anyway.
- Azure CLI 2.0 supports multiple clouds, and will support API versions and Azure Stack in the future whilst xplat does not.
- We have introduced the concept of 'contexts' to make it easy for users to switch between clouds, API versions and accounts/subscriptions.

Proposal on how we would support Scenario 2:

```
# Create the contexts you want
az context create --cloud AzureCloud -n foo
az context create --cloud AzureCloud -n bar

# Modify them to set the default subscription to use
az context modify -n foo --default-subscription "XXX-XXX-XXX"
az context modify -n bar --default-subscription "YYY-YYY-YYY"

# In a single session, switch contexts with a command
az context switch -n foo

# Alternatively, switch to a different context using `AZURE_CONTEXT`
export AZURE_CONTEXT=foo
az

# You can still alias the commands if you wish
alias az-foo='AZURE_CONTEXT=foo az'
alias az-bar='AZURE_CONTEXT=bar az'
```

With this solution, we support switching between clouds, API versions and accounts/subscriptions with the single 'context' concept.
We do this whilst still only using the one `~/.azure` directory.

To implement this, in _profile.py, we should load the default subscription that's set for the context.
If there isn't one set, fall back to the current active account as we do right now.

This is of course open to discussion but that's what I'm thinking here! 😄

**Comment by nneul** [comment]
I like the above context capability as described... what's the timeframe for implementation? Note that this doesn't necessarily preclude also supporting the PR in #1293 / #1298 if it's going to be a while before this is supported.

**Comment by nneul** [comment]
Just so it's documented here as well - #1293 / #1298 was merged today.

**Comment by yugangw-msft** [comment]
We can live with this for now with the option of using `AZURE_CONFIG_DIR `. In future migrating to MSAL will eliminate such needs with the new creds-sharing mechanism
