### ISSUE TITLE
(Windows only) "az vm extension set" command is passing public json as string instead of a json map to the VM extension

### ISSUE THREAD

**Issue by canfikret** [Azure/azure-cli#13471]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Linux VM extension is failing to install. Linux Guest Agent expects public settings to be a map; however, from the logs it arrives as string; and it causes "Install failed with error: 'unicode' object has no attribute 'get'"

**To Reproduce**
Run this command in Windows cmd:
az vm extension set --resource-group RG --vm-name VM --name OmsAgentForLinux --publisher Microsoft.EnterpriseCloud.Monitoring --version 1.12 --protected-settings '{
"workspaceKey":"reducted' --settings '{"workspaceId":"587155ae-REDUCTED"}' --no-auto-upgrade

It produces below in the logs. The problem is in bold.
[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "*** REDACTED ***", "publicSettings": **"{workspaceId:587155ae-REDUCTED}"**, "protectedSettingsCertThumbprint": "*** REDACTED ***"}}]}

Run the same command in Linux or WSL and it works. The expected is in bold.
2020/05/11 15:47:09 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "*** REDACTED ***", "publicSettings": **{"workspaceId": "24e61b15-00e6-45fd-8c42-043bff85d6d9"}**, "protectedSettingsCertThumbprint": "*** REDACTED ***"}}]}

**Expected behavior**
The command should succeed in Windows az-cli as well.

**Environment summary**
Installed via MSI on Win 10.

E:\>az --version
azure-cli                          2.5.1

command-modules-nspkg              2.0.3
core                               2.5.1
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
aks-preview                       0.4.24
azure-devops                      0.12.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'

**Additional context**

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look?

**Comment by yungezz** [comment]
hi @qwordy ,could you pls have a look at this issue?

**Comment by qwordy** [comment]
The issue is confirmed. It is tricky to pass quote and double quote in various of shells.

**Comment by qwordy** [comment]
You can try
```
az vm extension set --resource-group RG --vm-name VM --name OmsAgentForLinux --publisher Microsoft.EnterpriseCloud.Monitoring --version 1.12 --protected-settings '{\"workspaceKey\":\"reducted\"}' --settings '{\"workspaceId\":\"587155ae-REDUCTED\"}' --no-auto-upgrade
```
Share a doc: https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md
