### ISSUE TITLE
Listing blobs from secondary endpoint of RAGRS storage account using account key failing with Authorization error

### ISSUE THREAD

**Issue by GaneshMSFT** [Azure/azure-cli#13483]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az storage blob list --account-name **ACCOUNTNAME-secondary** --account-key **ACCOUNTKEY** --container-name **CONTAINERNAME**

The above command failing with Authorization failure. 

**To Reproduce**
Run this command and it's failing with auth error however this should list the blobs.
az storage blob list --account-name **ACCOUNTNAME-secondary** --account-key **ACCOUNTKEY** --container-name **CONTAINERNAME**

ErrorCode: AuthenticationFailed<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.RequestId:6fbc540a-c01e-0047-184f-290c79000000Time:2020-05-13T17:52:04.1072616Z</Message><AuthenticationErrorDetail>**Cannot find the claimed account when trying to GetProperties for the account ACCOUNTNAME-secondary.**</AuthenticationErrorDetail></Error>.
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=63ab68e6-9542-11ea-86f6-ba31b597a0ac Retry policy did not allow for a retry: Server-Timestamp=Wed, 13 May 2020 17:52:03 GMT, Server-Request-ID=6fbc540a-c01e-0047-184f-290c79000000, HTTP status code=403, Exception=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. ErrorCode: AuthenticationFailed<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.RequestId:6fbc540a-c01e-0047-184f-290c79000000Time:2020-05-13T17:52:04.1072616Z</Message><AuthenticationErrorDetail>Cannot find the claimed account when trying to GetProperties for the account ACCOUNTNAME-secondary.</AuthenticationErrorDetail></Error>.

**Expected behavior**
The command should be able to list blobs from secondary endpoint of the storage account.

**Environment summary**

azure-cli                          2.4.0 *

command-modules-nspkg              2.0.3
core                               2.4.0 *
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
interactive                        0.4.3

**Additional context**

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172

**Comment by drebake** [comment]
Is there an alternative way to communication with a _-secondary endpoint of a RAGRS using an accesskey? Right now, it would be impossible to recover data from a storage account using a accesskey if there would be a outage in the main storage account location.... defeating the purpose of RAGRS.

**Comment by Juliehzl** [comment]
Fix in https://github.com/Azure/azure-cli/pull/14605.
You could try with Edge Builds here https://github.com/Azure/azure-cli#edge-builds.
please use xxx-secondary as your --account-name.

Official release will be available after next Tuesday.

**Comment by Juliehzl** [comment]
`az storage blob list --account-name ACCOUNTNAME-secondary --account-key ACCOUNTKEY --container-name CONTAINERNAME` should work in edge build and 2.10.0
