### ISSUE TITLE
Azure Monitor Diagnostics Settings CLI should support logAnalyticsDestinationType

### ISSUE THREAD

**Issue by asheniam** [Azure/azure-cli#13484]
Please add support for logAnalyticsDestinationType property in the Azure Monitor CLI for diagnostic settings.  This property is already supported by the PowerShell equivalent.

**Comment by yonzhan** [comment]
add to S170

**Comment by MyronFanQiu** [comment]
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2017-05-01-preview/diagnosticsSettings_API.json#L320

**Comment by nkiest** [comment]
Instead of "export_to_specific_resource", this should be "export_to_resource_specific"
