### ISSUE TITLE
Resource not found error- Create webapp

### ISSUE THREAD

**Issue by tobystic** [Azure/azure-cli#13488]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

  [0] create a generic issue.
   [1] az webapp create       : FAILURE. Ran: 1 hrs 59 mins ago.
   [2] az webapp create       : FAILURE. Ran: 1 hrs 55 mins ago.
   [3] az webapp create       : FAILURE. Ran: 1 hrs 55 mins ago.
   [4] az webapp create       : FAILURE. Ran: 1 hrs 53 mins ago.
   [5] az webapp create       : SUCCESS. Ran: 1 hrs 51 mins ago.
   [6] az login               : SUCCESS. Ran: 20 mins ago.
   [7] az account set         : SUCCESS. Ran: 20 mins ago.
   [8] Unknown (help version) : SUCCESS. Ran: 15 mins ago.
   [9] az version             : SUCCESS. Ran: 14 mins ago.

**Describe the bug**
"az webapp create " command returned "ResourceNotFound - The Resource 'Microsoft.Web/sites/testapp' under resource group 'mmmmm' was not found."

Here is the command:

`user@Azure:$

user@Azure:$ az webapp create --resource-group mmmmm --plan myAppServicePlan --name testapp --runtime "PHP|7.3" --deployment-local-git
ResourceNotFound - The Resource 'Microsoft.Web/sites/testapp' under resource group 'mmmmm' was not found.

user@Azure:~$`

**To Reproduce**
Configure deployment user
Create Resource group
Create App service plan
Create Webapp with app name <testapp>
(Followed tutorial https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-php)

**Expected behavior**
Expected webapp to be created

**Environment summary**
  "azure-cli": "2.4.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.4.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}

**Additional context**
It appears the name "testapp" is not an available name. I noticed this when I tried the same step in portal as it clearly said "name not available". I changed the name in the CLI and then it worked. The error return was confusing

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
We should add site name validation to create command as well and that should make this experience match portal.

**Comment by panchagnula** [comment]
@calvinsID we currently don't do CheckNameValidation on create - once we make the changes to make show the detailed error message on az webapp up - lets see if we can use the same on create as well.
