### ISSUE TITLE
--tags option missing for "iot hub" and "iot dps"

### ISSUE THREAD

**Issue by cocowalla** [Azure/azure-cli#13497]
The `--tags` option appears to be missing from the `az iot hub create` and `az iot hub update` commands.

It's not [documented](https://docs.microsoft.com/en-us/cli/azure/iot?view=azure-cli-latest), and trying to use it results in an error `az: error: unrecognized arguments: --key=`.

I'd consider this a bug rather than a feature request, as every other create/update command seems to have a `--tags` option; `--tags` is like part of the create/update contract.

**Comment by yonzhan** [comment]
iot

**Comment by yiyiguo** [comment]
@Azure/azure-iot-cli-triage

**Comment by c-ryan-k** [comment]
@cocowalla @yonzhan @yiyiguo `--tags` should be supported in update/create for both Hub and DPS

**Comment by vilit1** [comment]
Closing the issue due to no response. If you still need help with this issue, please re-open.
