### ISSUE TITLE
`az -v` fails.

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#13499]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

`az -v` fails.
```
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'rjust'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\knack\knack\cli.py", line 207, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\__init__.py", line 107, in show_version
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-7cl6xofh\azure-cli-core\azure\cli\core\util.py", line 198, in get_az_version_string
AttributeError: 'NoneType' object has no attribute 'rjust'
```

`az version` works.

**To Reproduce**

I installed a new version of Azure CLI. During the installation, it prompts python is running. When the installation is finished, it asks me restart computer. When I restart, `az -v` crash. The reason is one extension's version is missing.

**Expected behavior**

**Environment summary**

Version: 2.5.1
OS: Windows 10

**Additional context**

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
Added default for ext.version:
https://github.com/Azure/azure-cli/blob/58198af0d650df1433f329f2ab42572836bae62e/src/azure-cli-core/azure/cli/core/util.py#L243  

Please try with the latest dev branch and see which extension has `Unknown` version info.

**Comment by qwordy** [comment]
It is the image-copy-extension

**Comment by fengzhou-msft** [comment]
Does this issue still exist? I cannot reproduce it now. @qwordy

**Comment by qwordy** [comment]
The extension version is still unknown. But I can run `az -v` now.
```
image-copy                       Unknown
```
