### ISSUE TITLE
How to stop the execution of command

### ISSUE THREAD

**Issue by codemaker** [Azure/azure-cli#13498]
I have tried below command

az storage blob copy start-batch --account-key 00000000 --account-name MyAccount --destination-container MyDestinationContainer --source-account-key MySourceKey --source-account-name MySourceAccount --source-container MySourceContainer

Now how do I pause or break it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b4e73a9-187f-ad77-3f22-52e7c3edd149
* Version Independent ID: e58b4f05-7bbc-fcb0-ee55-571ee68bd3e7
* Content: [az storage blob copy](https://docs.microsoft.com/en-us/cli/azure/storage/blob/copy?view=azure-cli-latest#code-try-5)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
In windows, use `Ctrl` + `C`.

**Comment by Juliehzl** [comment]
Hi, because there is no response for several days, I will close the PR now and if you still have the problem, feel free to reopen it.
