### ISSUE TITLE
[Bot Services] Web chat channel creation

### ISSUE THREAD

**Issue by huski1017** [Azure/azure-cli#13502]
Hi,

After running across the documentation of the Azure CLI and more specifically the Bot Services part I noticed that the create and delete commands were not available for the Web Chat channels.

I am looking forward for this feature as this would allow me to automate this part of the process on my side.

Is there any development planned on that? A potential release date approximation?

Thank you for taking into consideration my request.

**Comment by yonzhan** [comment]
Bot Services

**Comment by stevengum** [comment]
@huski1017 thanks for creating this issue, we will investigate this request.

**Comment by stevengum** [comment]
@huski1017 this looks to be doable with the current Swagger-generated Python SDK. I'm going to tentatively mark it for S170 and see if I can get it via https://github.com/Azure/azure-cli/pull/13462.

**Comment by huski1017** [comment]
@stevengum That would be great, thank you for taking care of my request!

**Comment by huski1017** [comment]
@stevengum Any update about my feature request?

**Comment by huski1017** [comment]
Could it be possible to get some updates about my request?

It's been 2 months that someone is supposed to take care of it on the S170 we're now about to reach the end of the S173 and still nothing changed.

**Comment by huski1017** [comment]
Hi,

Is there any update about this request?
I am still looking forward this feature that would allow me to automate a painful process.

Regards,
Huski1017

**Comment by navba-MSFT** [comment]
@huski1017 Apologies for the late reply. For the _webchat_ only **show** command is currently available in CLI. Refer [this](https://docs.microsoft.com/en-us/cli/azure/bot/webchat?view=azure-cli-latest#az-bot-webchat-show). Please let us know if you have any further questions on this. Awaiting your reply.

Refer similar issue here https://github.com/microsoft/BotFramework-WebChat/issues/2913
