### ISSUE TITLE
Upload batch fails if any files contain a colon in their name

### ISSUE THREAD

**Issue by OwainYoung** [Azure/azure-cli#13500]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When batch uploading to a file store, if any of the files contain a colon in their name an error is returned saying "the specified resource name contains invalid characters".
This doesn't happen when the command is run with --dryrun

**To Reproduce**
create a file containing a colon in its name and run
az storage file upload-batch -s . -d <filestore>
from its directory

**Expected behavior**
The file to be uploaded correctly

**Environment summary**
Ubuntu 16

**Additional context**
debug trace:
Command arguments: ['storage', 'file', 'upload-batch', '-d', 'aksshare/documents/000/216/620', '-s', '.', '--pattern', 'Letter of reference (redacted, 23:06:2015).pdf', '--account-name', 'aks1storageaccount', '--account-key', '92wheZQ9crN2grgUT3atBb5TzkQ8Owitj+T9hOYKBzsTrTzUqHDhj5i7xjQLY0ypUfrJt+JtPZK57wpIg8D3vg==', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f8fa7e1fbf8>, <function OutputProducer.on_global_arguments at 0x7f8fa7747e18>, <function CLIQuery.on_global_arguments at 0x7f8fa76edf28>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.007 seconds.
Loaded module 'acs' in 0.007 seconds.
Loaded module 'advisor' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.005 seconds.
Loaded module 'apim' in 0.001 seconds.
Loaded module 'appconfig' in 0.003 seconds.
Loaded module 'appservice' in 0.011 seconds.
Loaded module 'aro' in 0.004 seconds.
Loaded module 'backup' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.031 seconds.
Loaded module 'batchai' in 0.003 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'botservice' in 0.005 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.005 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.002 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.008 seconds.
Loaded module 'deploymentmanager' in 0.003 seconds.
Loaded module 'dla' in 0.005 seconds.
Loaded module 'dls' in 0.004 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.003 seconds.
Loaded module 'eventhubs' in 0.003 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.006 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.006 seconds.
Loaded module 'kusto' in 0.003 seconds.
Loaded module 'lab' in 0.003 seconds.
Loaded module 'managedservices' in 0.001 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.008 seconds.
Loaded module 'natgateway' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.003 seconds.
Loaded module 'network' in 0.036 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.005 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.008 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.002 seconds.
Loaded module 'resource' in 0.011 seconds.
Loaded module 'role' in 0.005 seconds.
Loaded module 'search' in 0.001 seconds.
Loaded module 'security' in 0.003 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'signalr' in 0.001 seconds.
Loaded module 'sql' in 0.011 seconds.
Loaded module 'sqlvm' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.068 seconds.
Loaded module 'vm' in 0.017 seconds.
Loaded all modules in 0.351 seconds. (note: there's always an overhead with the first module loaded)
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f8fa541c730>]
az_command_data_logger : command args: storage file upload-batch -d {} -s {} --pattern {} --account-name {} --account-key {} --debug
metadata file logging enabled - writing logs to '/home/lcdadmin/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f8fa53f3400>]
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f8fa53f3840>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f8fa53f3950>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f8fa4b0e488>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f8fa7747ea0>, <function CLIQuery.handle_query_parameter at 0x7f8fa76e3048>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f8fa53f38c8>, <function handler at 0x7f8fa49e9ea0>]
Getting data service client service_type=FileService
uploading /filestore/documents/000/216/620/Letter of reference (redacted, 23:06:2015).pdf
azure.multiapi.storage.v2018_11_09.common._auth : String_to_sign=PUT

x-ms-client-request-id:0b0fcc08-95c6-11ea-8d26-00155dafff6d
x-ms-content-length:246182
x-ms-content-type:application/pdf
x-ms-date:Thu, 14 May 2020 09:34:01 GMT
x-ms-type:file
x-ms-version:2018-11-09
/aks1storageaccount/aksshare/documents/000/216/620/Letter%20of%20reference%20(Dr%20Jeffery%20Chew,%2023%3A06%3A2015).pdf
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=0b5849ba-95c6-11ea-8d26-00155dafff6d Outgoing request: Method=PUT, Path=/aksshare/documents/000/216/620/Letter%20of%20reference%20(Dr%20Jeffery%20Chew,%2023%3A06%3A2015).pdf, Query={'timeout': None}, Headers={'x-ms-content-length': '246182', 'x-ms-type': 'file', 'x-ms-cache-control': None, 'x-ms-content-type': 'application/pdf', 'x-ms-content-disposition': None, 'x-ms-content-md5': None, 'x-ms-content-encoding': None, 'x-ms-content-language': None, 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.6.8; Linux 3.10.0-1062.12.1.el7.x86_64) AZURECLI/2.5.1 (RPM)', 'x-ms-client-request-id': '0b0fcc08-95c6-11ea-8d26-00155dafff6d', 'x-ms-date': 'Thu, 14 May 2020 09:34:01 GMT', 'Authorization': 'REDACTED'}.
urllib3.connectionpool : Starting new HTTPS connection (1): aks1storageaccount.file.core.windows.net:443
urllib3.connectionpool : https://aks1storageaccount.file.core.windows.net:443 "PUT /aksshare/documents/000/216/620/Letter%20of%20reference%20(redacted,%2023%3A06%3A2015).pdf HTTP/1.1" 400 243
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=0b5849ba-95c6-11ea-8d26-00155dafff6d Receiving Response: Server-Timestamp=Thu, 14 May 2020 09:34:01 GMT, Server-Request-ID=99df7175-c01a-0008-75d2-29925d000000, HTTP Status Code=400, Message=The specifed resource name contains invalid characters., Headers={'content-length': '243', 'content-type': 'application/xml', 'server': 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '99df7175-c01a-0008-75d2-29925d000000', 'x-ms-version': '2018-11-09', 'x-ms-error-code': 'InvalidResourceName', 'date': 'Thu, 14 May 2020 09:34:01 GMT'}.
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=0b5849ba-95c6-11ea-8d26-00155dafff6d Operation failed: checking if the operation should be retried. Current retry count=0, Server-Timestamp=Thu, 14 May 2020 09:34:01 GMT, Server-Request-ID=99df7175-c01a-0008-75d2-29925d000000, HTTP status code=400, Exception=The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.RequestId:99df7175-c01a-0008-75d2-29925d000000Time:2020-05-14T09:34:01.5930270Z</Message></Error>.
azure.multiapi.storage.v2018_11_09.common.storageclient : Client-Request-ID=0b5849ba-95c6-11ea-8d26-00155dafff6d Retry policy did not allow for a retry: Server-Timestamp=Thu, 14 May 2020 09:34:01 GMT, Server-Request-ID=99df7175-c01a-0008-75d2-29925d000000, HTTP status code=400, Exception=The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.RequestId:99df7175-c01a-0008-75d2-29925d000000Time:2020-05-14T09:34:01.5930270Z</Message></Error>.
cli.azure.cli.core.util : The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:99df7175-c01a-0008-75d2-29925d000000
Time:2020-05-14T09:34:01.5930270Z</Message></Error>
The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:99df7175-c01a-0008-75d2-29925d000000
Time:2020-05-14T09:34:01.5930270Z</Message></Error>
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f8fa541c950>]
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2572 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "/usr/bin/python3 /usr/lib64/az/lib/python3.6/site-packages/azure/cli/telemetry/__init__.py /home/lcdadmin/.azure"
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.
command ran in 0.620 seconds.

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
For upload-batch command, cli will use original file name as blob name, and blob name has some requirements as shown here https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#blob-names.

So it is by design for Invalid Naming failure. you need to rename your file names for upload-batch. sorry for inconvenience.
