### ISSUE TITLE
Command fails with auth-mode login, but works when omitted with warning

### ISSUE THREAD

**Issue by iUnknwn** [Azure/azure-cli#13509]
When attempting to add a storage access policy to a container, if I do not specify auth mode, I get a warning: `No connection string, account key or sas token found, we will query account keys for your storage account. Please try to use --auth-mode login or provide one of the following parameters: connection string, account key or sas token for your storage account.`

However, the command executes successfully. 

If I add `--auth-mode login` to the command, the command fails with a resource not found error.

**Command Name**
`az storage container policy create`

**Errors:**
```
The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:bc57d6ff-201e-00ce-2b3b-2a1bd2000000
Time:2020-05-14T22:02:55.5697669Z</Message></Error>
```

## To Reproduce:
- `az storage container policy create --name {} --container-name {} --account-name {} --expiry {} --permissions {} --subscription {} --auth-mode {}`

## Expected Behavior
I assume, when not specified, the command is using --auth-mode login, since I'm accessing resources just though my account, not via any keys or SAS tokens. 

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1

Extensions:
azure-devops 0.12.0

```

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
Hi @iUnknwn, when no `--auth-mode login` specified, cli command will query account key as credential for your operation.

But in general, we will recommend users to provide credentials by themselves according to their own scenarios.

**Comment by iUnknwn** [comment]
@Juliehzl - Ok, so when no auth is specified, it's equivalent to "--auth-mode key"?

**Comment by Juliehzl** [comment]
> @Juliehzl Zunli Hu FTE - Ok, so when no auth is specified, it's equivalent to "--auth-mode key"?

yes

**Comment by Juliehzl** [comment]
Hi @iUnknwn, error message is already refined in PR https://github.com/Azure/azure-cli/pull/13963. Besides --auth-mode, you can consider using `--account-key` or `--connection-string` as credential. for more information, you can refer to [here ](https://github.com/Azure/azure-cli/blob/3113258ba38f0415cae2c30347491030e76c08f4/doc/use_cli_effectively.md#using-storage-commands).

I will close the issue now and if you still have issue, feel free to create a new one.
