### ISSUE TITLE
Every time I run a command, I am getting a 400 error.

### ISSUE THREAD

**Issue by sayd0003** [Azure/azure-cli#13501]
## Describe the bug

**Command Name**
`Unknown`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az -h`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

Extensions:
interactive 0.4.4

```

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
@sayd0003 can you run with `--debug` and paste the log here?

**Comment by fengzhou-msft** [comment]
@sayd0003 are you running on Cloud Shell? There is a [known issue](https://github.com/Azure/azure-cli/issues/11749). Please run `az login` and retry.

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please feel free to reopen the issue if it still exists.
