### ISSUE TITLE
Creation of Azure Container Registry Fails

### ISSUE THREAD

**Issue by tas1272** [Azure/azure-cli#13514]
## Describe the bug

**Command Name**
`az acr create`

**Errors:**
```
'registrationState'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 688, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.6/site-packages/six.py, ln 693, in reraise
    raise value
...
site-packages/msrest/universal_http/requests.py, ln 275, in user_hook_cb
    return user_hook(r, *args, **kwargs)
python3.6/site-packages/msrestazure/tools.py, ln 57, in register_rp_hook
    if not _register_rp(session, url_prefix, rp_name):
python3.6/site-packages/msrestazure/tools.py, ln 102, in _register_rp
    if rp_info['registrationState'] == 'Registered':
KeyError: 'registrationState'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr create --name {} --resource-group {} --sku {} --admin-enabled {}`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by yonzhan** [comment]
acr

**Comment by yugangw-msft** [comment]
This is not container registry issue; rather a msrest-azure bug when tried to auto register the provider, which can happen on any other resource creation. Please investigate from the installtion

**Comment by jiasli** [comment]
+ https://github.com/Azure/msrestazure-for-python owner @lmazuel

**Comment by lmazuel** [comment]
That doesn't make sense, it means we got a 200 from the POST to ARM with url `"{}providers/{}/register?api-version=2016-02-01".format(url_prefix, rp_name)`, but that response body didn't includes the `registrationState` key ([see RestAPI spec](https://docs.microsoft.com/en-us/rest/api/resources/providers/register#provider)).

@yugangw-msft is there a possibility that this format is from done by the service team? I don't see how ARM would start to not returning this (especially since the API version is hard coded). Might be an ARM bug otherwise.

**Comment by navba-MSFT** [comment]
@tas1272 Apologies for the late reply. I tried to run the same command and that worked fine for me. Could you please use the [most recent version ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the CLI and try to run the same command again. More Info [here](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-create).

This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@tas1272 This is a follow-up to check if you had a chance to look at my above comment. This issue is open for quite sometime. Please let us know if you need any further assistance on this.

**Comment by navba-MSFT** [comment]
@tas1272 We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
