### ISSUE TITLE
"az vm create" should do a pre-check for available SKUs

### ISSUE THREAD

**Issue by yangl900** [Azure/azure-cli#1351]
The default az vm create doesn't work for some location and will get error "The requested VM size 'Standard_DS1' is not available in this region". Unfortunately there is no easy way to find out the available region/sku combination from CLI. At this point user has to keep retrying different location, or open portal to figure out what's available.

I suggest we do similar pre-deployment check like portal: fetch the /providers/Microsoft.Compute/skus API and use that in auto-completion and validate/default a SKU to provision.

**Comment by mayurid** [comment]
@yugangw-msft to take a look.

**Comment by derekbekoe** [comment]
We have the `az vm list-sizes -l <location>` command. Does that help?

For example:
```
$ az vm list-sizes -l centralus --query [].name
[
  "Standard_A0",
  "Standard_A1",
  "Standard_A2",
  "Standard_A3",
  "Standard_A4",
  "Basic_A0",
  "Basic_A1",
  "Basic_A2",
  "Basic_A3",
  "Basic_A4",
...
]
```

**Comment by yangl900** [comment]
if this is calling /vmSizes API, it doesn't take account the restrictions due to capacity check. it'll be best if we use the skus API and do client side validation.

**Comment by yugangw-msft** [comment]
@hyonholee, @huangpf, I don't see this specific path of `/providers/Microsoft.Compute/skus` has been modeled in the swagger?

**Comment by yugangw-msft** [comment]
This needs to happen from service side first, which is not finalized yet

**Comment by yugangw-msft** [comment]
Close for now, and will re-open when service and API spec are available
