### ISSUE TITLE
Getting OsType null for vmss 

### ISSUE THREAD

**Issue by mightysood** [Azure/azure-cli#13516]
**Describe the bug**

While using Azure cli to fetch details of vmss , osType is showing null.

In my Azure portal below, I can clearly see that OS is Linux
![image](https://user-images.githubusercontent.com/32262801/82054573-c75db480-96dc-11ea-980c-49887a702b93.png)

Using Azure CLI, it's coming out to be null.

    "storageProfile": {
      "dataDisks": null,
      "imageReference": {
        "id": null,
        "offer": "UbuntuServer",
        "publisher": "Canonical",
        "sku": "18.04-LTS",
        "version": "latest"
      },
      "osDisk": {
        "caching": "ReadWrite",
        "createOption": "FromImage",
        "diffDiskSettings": null,
        "diskSizeGb": 30,
        "image": null,
        "managedDisk": {
          "diskEncryptionSet": null,
          "storageAccountType": "Premium_LRS"
        },
        "name": null,
        "osType": null,   <======= This guy
        "vhdContainers": null,
        "writeAcceleratorEnabled": null
      }
    }

**To Reproduce**

1. Create a default vmss .
2. Use the command below.
3. ` $ az vmss show -g rgrp -n vmss_name 
`
4. Search for osType.

**Expected behavior**

It should describe the type of OS whether it is Linux, Windows, etc.

**Environment summary**

Use azure cli on ubuntu.
az login is required.

**Additional context**

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by qwordy** [comment]
HTTP response is
```
"storageProfile": {
        "osDisk": {
          "createOption": "FromImage",
          "caching": "ReadWrite",
          "managedDisk": {
            "storageAccountType": "Premium_LRS"
          },
          "diskSizeGB": 30
        },
        "imageReference": {
          "publisher": "OpenLogic",
          "offer": "CentOS",
          "sku": "7.5",
          "version": "latest"
        }
      },
```
However, the output is
```
"storageProfile": {
      "dataDisks": null,
      "imageReference": {
        "exactVersion": null,
        "id": null,
        "offer": "CentOS",
        "publisher": "OpenLogic",
        "sku": "7.5",
        "version": "latest"
      },
      "osDisk": {
        "caching": "ReadWrite",
        "createOption": "FromImage",
        "diffDiskSettings": null,
        "diskSizeGb": 30,
        "image": null,
        "managedDisk": {
          "diskEncryptionSet": null,
          "storageAccountType": "Premium_LRS"
        },
        "name": null,
        "osType": null,
        "vhdContainers": null,
        "writeAcceleratorEnabled": null
      }
    }
```

The cause is CLI deserializes string to a model in SDK and then serialize it. `osType` is a field of `osDisk`.
Description of `osType`:
```
This property allows you to specify the type of the OS that is included in the disk if creating a VM from user-image or a specialized VHD. <br><br> Possible values are: <br><br> **Windows** <br><br> **Linux**
```

**Comment by qwordy** [comment]
Hi service team, is it possible to add a field showing operating system type?

**Comment by Drewm3** [comment]
The OS Type is specified on the OS Disk. It is not specified on the VM or VMSS instance. So the behavior that you are seeing is expected.
