### ISSUE TITLE
"az group deployment validate" hangs when parameters are missing

### ISSUE THREAD

**Issue by vllama** [Azure/azure-cli#13526]
When calling "az group deployment validate" as below, if any parameter that is specified in the template.json file is omitted, the call just hangs, and does not return. It also does not seem to time out.
```
az group deployment validate `
  --resource-group $resourceGroup `
  --template-file $deployRoot\deployment-template.json `
   --parameters subscriptionId=$subscriptionId `
   --parameters name=$functionName `
   --parameters location=$location `
   --parameters hostingPlanName=$appServicePlan `
  --parameters connectionString =$connectionString  <------- omit this parameter and it hangs

```
parameter is defined in template as:

```
 "parameters": {
    "connectionString": {
      "type": "string"
    } ....
```

Version used:
```
azure-cli                         2.0.81 *

command-modules-nspkg              2.0.3
core                              2.0.81 *
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
application-insights               0.1.3

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'c:\Users\user\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal




Please let us know how we are doing: https://aka.ms/clihats
```

**Comment by yonzhan** [comment]
add to S170

**Comment by vllama** [comment]
Also discovered that having a typo of  "defaultvalue" instead of "defaultValue" when defining a parameter will also cause it to hang. 

Most likely related.
Example: 
```
      "alwaysOn": {
          "type": "bool",
          "defaultvalue": false
        },
```

**Comment by vllama** [comment]
Actually this only seems to be happening when running in the Windows PowerShell ISE interpreter.
If i run this in straight powershell or cmd I get the followinig prompt:
```
Please provide string value for 'database_connection_string' (? for help):
```

there seems to have been an issue logged here that dissapeared:
https://docs.microsoft.com/en-us/archive/blogs/powershell/console-application-non-support-in-the-ise

**Comment by iteal** [comment]
This also happens when using VSCode on Linux, in the terminal tab.

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness
