### ISSUE TITLE
Command az vm start not working with Azure CLI in Azure Cloud Shell

### ISSUE THREAD

**Issue by RohitY24** [Azure/azure-cli#13528]
## Describe the bug

**Command Name**
`az vm start`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 688, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm start -g {} -n {}`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by yungezz** [comment]
hi @RohitY24 did you see the error in Cloudshell? If yes, this is a known issue in Cloudshell, Cloudshell team is working on resolving it. one workaround is using local installed azure cli.

**Comment by yungezz** [comment]
duplicate with https://github.com/Azure/azure-cli/issues/11749

**Comment by RohitY24** [comment]
Hello @yungezz, thank you for letting me know that the team is working on a fix. Any ETA on when the fix is expected?

**Comment by maertendMSFT** [comment]
This should be fixed now.  I cannot repro, please close.
