### ISSUE TITLE
SAML Identifier missing on Service Principal

### ISSUE THREAD

**Issue by nickadams675** [Azure/azure-cli#13525]
version 2.5.1

**Describe the bug**
Hello, it appears that the UI/possibly Graph API is not honoring the SAML Identifier (Entity ID) when set by the Application Manifest. The UI is showing the following behavior:
![image](https://user-images.githubusercontent.com/49757520/82108828-1adcfc00-96f7-11ea-9d56-86812460fd39.png)

![image](https://user-images.githubusercontent.com/49757520/82108843-44962300-96f7-11ea-9bde-7ef4122e3cd6.png)

**To Reproduce**
Create an App Registration via az-cli, or Graph API, then create a Service Principal and link it to the App Registration.

**Expected behavior**
Since the SAML Identifier is showing in the first (non-edit) view, one would think that it was configured correctly. Although users cannot authenticate until this is filled in the UI.

**Environment summary**
Mac OS, az-cli version 2.5.1

Also, I do not see a way to configure this on the SP side via either az-cli or Graph API.

Thanks!

**Comment by yonzhan** [comment]
add to S170

**Comment by jiasli** [comment]
This issue doesn't seem be to caused by Azure CLI, but by AD Graph API. Could you create a Support Request in Azure Portal for AAD? Thanks for understanding.

**Comment by nickadams675** [comment]
@jiasli 

Thanks! I've opened a support request via the Azure Portal. 

I would like to have the latter part of this issue investigated, is that possible?:
>Also, I do not see a way to configure this on the SP side via either az-cli or Graph API.

**Comment by jiasli** [comment]
If this can't be configured via Graph API, Azure CLI can't do this as well. Azure CLI is still using the old AD Graph API 1.6. 

You may discuss with the support engineer about whether this can be done using Microsoft Graph API. If so, you may use `az rest` to call that API. Examples can be found at https://github.com/Azure/azure-cli/issues/12946.

**Comment by nickadams675** [comment]
Thanks! I'll open an SR for this to have it added to the Graph API.
