### ISSUE TITLE
az redis create - enabling ssl port - incorrect/unclear documentation

### ISSUE THREAD

**Issue by lgmorand** [Azure/azure-cli#13529]
I'm trying to create a Redis cache using `az redis create` command. 
When passing the parameter --enable-non-ssl-port true, the command triggers an error 

> az: error: unrecognized arguments: true

The doc is clear, true can be passed as parameter
```
--enable-non-ssl-port
If the value is true, then the non-ssl redis server port (6379) will be enabled.
```

Note: if I just use the parameter with any value then it works. But then the doc is misguiding, either true should be passed or either just the parameter without any value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb66426-9b0f-be54-5530-0673e6821f39
* Version Independent ID: 3d89a838-9a95-3cfe-ea58-7d7484e94956
* Content: [az redis](https://docs.microsoft.com/en-us/cli/azure/redis?view=azure-cli-latest#az-redis-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/redis/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/redis/_help.py)
* Service: **cache**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
redis
