### ISSUE TITLE
'az provider register' fails with invalid syntax 

### ISSUE THREAD

**Issue by viananth** [Azure/azure-cli#13523]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

az provider register cmd fails with invalid syntax. Please check the debug output below.

**To Reproduce**
az provider register --namespace Microsoft.Storage

**Expected behavior**

**Environment summary**

Edge build

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Windows\system32>az -v
azure-cli                          2.5.1

command-modules-nspkg              2.0.3
core                               2.5.1
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Python35\python.exe'
Extensions directory 'C:\Users\Administrator.S31R0203-DVM\.azure\cliextensions'

Python (Windows) 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/clihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Additional context**

7492 : 2020-05-13 17:46:20,240 : DEBUG : cli.knack.log : File logging enabled - writing logs to 'C:\CloudDeployment\BVTs\Output\AZSDKTOOLSCTQ\CLITestLogs'.
7492 : 2020-05-13 17:46:20,240 : DEBUG : cli.knack.cli : Command arguments: ['provider', 'register', '--namespace', 'Microsoft.Storage']
7492 : 2020-05-13 17:46:20,240 : DEBUG : cli.knack.cli : Event: Cli.PreExecute []
7492 : 2020-05-13 17:46:20,240 : DEBUG : cli.knack.cli : Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x02AFAC00>, <function OutputProducer.on_global_arguments at 0x02B8B978>, <function CLIQuery.on_global_arguments at 0x02BA9D68>]
7492 : 2020-05-13 17:46:20,272 : DEBUG : cli.knack.cli : Event: CommandInvoker.OnPreCommandTableCreate []
7492 : 2020-05-13 17:46:20,287 : DEBUG : cli.azure.cli.core : Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
7492 : 2020-05-13 17:46:20,287 : DEBUG : cli.azure.cli.core : Loaded module 'acr' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,287 : DEBUG : cli.azure.cli.core : Loaded module 'acs' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,287 : DEBUG : cli.azure.cli.core : Loaded module 'advisor' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,287 : DEBUG : cli.azure.cli.core : Loaded module 'ams' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,287 : DEBUG : cli.azure.cli.core : Loaded module 'apim' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,287 : DEBUG : cli.azure.cli.core : Loaded module 'appconfig' in 0.004 seconds.
7492 : 2020-05-13 17:46:20,303 : DEBUG : cli.azure.cli.core : Loaded module 'appservice' in 0.013 seconds.
7492 : 2020-05-13 17:46:20,319 : DEBUG : cli.azure.cli.core : Loaded module 'aro' in 0.007 seconds.
7492 : 2020-05-13 17:46:20,319 : DEBUG : cli.azure.cli.core : Loaded module 'backup' in 0.003 seconds.
7492 : 2020-05-13 17:46:20,350 : DEBUG : cli.azure.cli.core : Loaded module 'batch' in 0.028 seconds.
7492 : 2020-05-13 17:46:20,350 : DEBUG : cli.azure.cli.core : Loaded module 'batchai' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,350 : DEBUG : cli.azure.cli.core : Loaded module 'billing' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,350 : DEBUG : cli.azure.cli.core : Loaded module 'botservice' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,350 : DEBUG : cli.azure.cli.core : Loaded module 'cdn' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,350 : DEBUG : cli.azure.cli.core : Loaded module 'cloud' in 0.002 seconds.
7492 : 2020-05-13 17:46:20,350 : DEBUG : cli.azure.cli.core : Loaded module 'cognitiveservices' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,350 : DEBUG : cli.azure.cli.core : Loaded module 'configure' in 0.002 seconds.
7492 : 2020-05-13 17:46:20,350 : DEBUG : cli.azure.cli.core : Loaded module 'consumption' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,350 : DEBUG : cli.azure.cli.core : Loaded module 'container' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,365 : DEBUG : cli.azure.cli.core : Loaded module 'cosmosdb' in 0.002 seconds.
7492 : 2020-05-13 17:46:20,365 : DEBUG : cli.azure.cli.core : Loaded module 'deploymentmanager' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,365 : DEBUG : cli.azure.cli.core : Loaded module 'dla' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,365 : DEBUG : cli.azure.cli.core : Loaded module 'dls' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,365 : DEBUG : cli.azure.cli.core : Loaded module 'dms' in 0.002 seconds.
7492 : 2020-05-13 17:46:20,365 : DEBUG : cli.azure.cli.core : Loaded module 'eventgrid' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,365 : DEBUG : cli.azure.cli.core : Loaded module 'eventhubs' in 0.005 seconds.
7492 : 2020-05-13 17:46:20,365 : DEBUG : cli.azure.cli.core : Loaded module 'extension' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,365 : DEBUG : cli.azure.cli.core : Loaded module 'feedback' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,381 : DEBUG : cli.azure.cli.core : Loaded module 'find' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,381 : DEBUG : cli.azure.cli.core : Loaded module 'hdinsight' in 0.003 seconds.
7492 : 2020-05-13 17:46:20,381 : DEBUG : cli.azure.cli.core : Loaded module 'interactive' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,381 : DEBUG : cli.azure.cli.core : Loaded module 'iot' in 0.006 seconds.
7492 : 2020-05-13 17:46:20,381 : DEBUG : cli.azure.cli.core : Loaded module 'iotcentral' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,397 : DEBUG : cli.azure.cli.core : Loaded module 'keyvault' in 0.007 seconds.
7492 : 2020-05-13 17:46:20,397 : DEBUG : cli.azure.cli.core : Loaded module 'kusto' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,397 : DEBUG : cli.azure.cli.core : Loaded module 'lab' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,397 : DEBUG : cli.azure.cli.core : Loaded module 'managedservices' in 0.002 seconds.
7492 : 2020-05-13 17:46:20,397 : DEBUG : cli.azure.cli.core : Loaded module 'maps' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,397 : DEBUG : cli.azure.cli.core : Loaded module 'monitor' in 0.002 seconds.
7492 : 2020-05-13 17:46:20,397 : DEBUG : cli.azure.cli.core : Loaded module 'natgateway' in 0.002 seconds.
7492 : 2020-05-13 17:46:20,397 : DEBUG : cli.azure.cli.core : Loaded module 'netappfiles' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,444 : DEBUG : cli.azure.cli.core : Loaded module 'network' in 0.037 seconds.
7492 : 2020-05-13 17:46:20,444 : DEBUG : cli.azure.cli.core : Loaded module 'policyinsights' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,444 : DEBUG : cli.azure.cli.core : Loaded module 'privatedns' in 0.006 seconds.
7492 : 2020-05-13 17:46:20,444 : DEBUG : cli.azure.cli.core : Loaded module 'profile' in 0.002 seconds.
7492 : 2020-05-13 17:46:20,444 : DEBUG : cli.azure.cli.core : Loaded module 'rdbms' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,459 : DEBUG : cli.azure.cli.core : Loaded module 'redis' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,459 : DEBUG : cli.azure.cli.core : Loaded module 'relay' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,459 : DEBUG : cli.azure.cli.core : Loaded module 'reservations' in 0.002 seconds.
7492 : 2020-05-13 17:46:20,459 : DEBUG : cli.azure.cli.core : Loaded module 'resource' in 0.011 seconds.
7492 : 2020-05-13 17:46:20,475 : DEBUG : cli.azure.cli.core : Loaded module 'role' in 0.006 seconds.
7492 : 2020-05-13 17:46:20,475 : DEBUG : cli.azure.cli.core : Loaded module 'search' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,475 : DEBUG : cli.azure.cli.core : Loaded module 'security' in 0.004 seconds.
7492 : 2020-05-13 17:46:20,475 : DEBUG : cli.azure.cli.core : Loaded module 'servicebus' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,475 : DEBUG : cli.azure.cli.core : Loaded module 'servicefabric' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,475 : DEBUG : cli.azure.cli.core : Loaded module 'signalr' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,475 : DEBUG : cli.azure.cli.core : Loaded module 'sql' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,490 : DEBUG : cli.azure.cli.core : Loaded module 'sqlvm' in 0.001 seconds.
7492 : 2020-05-13 17:46:20,490 : DEBUG : cli.knack.cli : Event: CommandLoader.OnLoadCommandTable []
7492 : 2020-05-13 17:46:20,522 : DEBUG : cli.azure.cli.core : Loaded module 'storage' in 0.037 seconds.
7492 : 2020-05-13 17:46:20,537 : DEBUG : cli.azure.cli.core : Loaded module 'vm' in 0.019 seconds.
7492 : 2020-05-13 17:46:20,537 : DEBUG : cli.azure.cli.core : Loaded all modules in 0.249 seconds. (note: there's always an overhead with the first module loaded)
7492 : 2020-05-13 17:46:20,537 : DEBUG : cli.knack.cli : Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x036D4108>]
7492 : 2020-05-13 17:46:20,537 : INFO : az_command_data_logger : command args: provider register --namespace {}
7492 : 2020-05-13 17:46:20,537 : DEBUG : cli.azure.cli.core.azlogging : metadata file logging enabled - writing logs to 'C:\Users\Administrator.S31R0203-DVM\.azure\commands'.
7492 : 2020-05-13 17:46:20,537 : DEBUG : cli.knack.cli : Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03712A98>]
7492 : 2020-05-13 17:46:20,584 : ERROR : cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

7492 : 2020-05-13 17:46:20,584 : ERROR : cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

7492 : 2020-05-13 17:46:20,584 : ERROR : cli.azure.cli.core.util : invalid syntax (_formatters.py, line 132)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35\lib\site-packages\knack\cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 553, in execute
    self.commands_loader.load_arguments(command)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\__init__.py", line 384, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 310, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "C:\Program Files (x86)\Python35\lib\site-packages\knack\commands.py", line 106, in load_arguments
    cmd_args = self.arguments_loader()
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\__init__.py", line 588, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\__init__.py", line 628, in get_op_handler
    op = import_module(mod_to_import)
  File "C:\Program Files (x86)\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\command_modules\resource\custom.py", line 47, in <module>
    from ._formatters import format_what_if_operation_result
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\command_modules\resource\_formatters.py", line 132
    return f"{count} to create"
                              ^
SyntaxError: invalid syntax
7492 : 2020-05-13 17:46:20,584 : ERROR : cli.azure.cli.core.util : invalid syntax (_formatters.py, line 132)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35\lib\site-packages\knack\cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 553, in execute
    self.commands_loader.load_arguments(command)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\__init__.py", line 384, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 310, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "C:\Program Files (x86)\Python35\lib\site-packages\knack\commands.py", line 106, in load_arguments
    cmd_args = self.arguments_loader()
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\__init__.py", line 588, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\__init__.py", line 628, in get_op_handler
    op = import_module(mod_to_import)
  File "C:\Program Files (x86)\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\command_modules\resource\custom.py", line 47, in <module>
    from ._formatters import format_what_if_operation_result
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\command_modules\resource\_formatters.py", line 132
    return f"{count} to create"
                              ^
SyntaxError: invalid syntax

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
@viananth We've dropped support for Python 3.5. Some code is written with the syntax only supported with Python 3.6+. Can you upgrade your Python version to at least 3.6?

**Comment by viananth** [comment]
Thank you @fengzhou-msft . It was a hotfix env and it had Python 3.5. Once updated to 3.6, it went fine.
