### ISSUE TITLE
--query?

### ISSUE THREAD

**Issue by SeaDude** [Azure/azure-cli#13536]
--query seems to be a universal flag for each az command, but its not often listed as a required or optional flag. Maybe linking to how --query works from this root doc would be useful?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeedb9a7-2aed-6727-4cfb-1515809d676e
* Version Independent ID: 2c83180d-22ad-db42-e2eb-f27f11977963
* Content: [az](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/profile/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/profile/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @SeaDude here's doc https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest on --query. Does it helpful?

**Comment by SeaDude** [comment]
Sure this works. Thank you
