### ISSUE TITLE
Pod & Service CIDR must be /18 or larger

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/azure-cli#13531]
Pod & Service CIDR must be /18 or larger, this should be documented in the CLI docs !

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 08eb181a-b377-c854-69cc-3b9307f59f72
* Version Independent ID: 2142cb43-b027-86a1-6d3c-2f77bf86d177
* Content: [az aro](https://docs.microsoft.com/fr-fr/cli/azure/aro?view=azure-cli-latest#az-aro-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/aro/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/aro/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
aro
