### ISSUE TITLE
valid values for apiserver visibility & ingress visibility NOT DOCUMENTED

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/azure-cli#13530]
What are the valid values for apiserver visibility & ingress visibility ??

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 08eb181a-b377-c854-69cc-3b9307f59f72
* Version Independent ID: 2142cb43-b027-86a1-6d3c-2f77bf86d177
* Content: [az aro](https://docs.microsoft.com/fr-fr/cli/azure/aro?view=azure-cli-latest#az-aro-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/aro/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/aro/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
aro

**Comment by mjudeikis** [comment]
Thanks, we will fix this and rollout when we can.
