### ISSUE TITLE
Azure CLI commands are failing 

### ISSUE THREAD

**Issue by mathurneha** [Azure/azure-cli#13533]
## Describe the bug

**Command Name**
`az account show`

**Errors:**
The command failed with an unexpected error. Here is the traceback:

[Errno 5] Input/output error: '/xxx/xxxx/xxxxx/commands/2020-05-17.04-06-29.account_show.136.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 510, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 84, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 106, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 5] Input/output error: '/xxx/xxxx/xxxxx/commands/2020-05-17.04-06-29.account_show.136.log'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account show`

## Expected Behavior
get the list of subscriptions i have access
## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *

```

**Comment by mathurneha** [comment]
I am unable to run any az command in the cloud shell. I

**Comment by yungezz** [comment]
hi @mathurneha did you see the error in Cloudshell?

**Comment by mathurneha** [comment]
Yes, I am unable to run any cli command.

Thanks & Regards
Neha

**Comment by arrownj** [comment]
> Yes, I am unable to run any cli command. Thanks & Regards Neha
> […](#)


> Yes, I am unable to run any cli command. Thanks & Regards Neha
> […](#)
> On May 17, 2020, at 6:22 AM, Yunge Zhu ***@***.***> wrote: ﻿ hi @mathurneha did you see the error in Cloudshell? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi @mathurneha , Could you please help confirm whether you have extra space in your storage account? It seems that you encounter a I/O error while write log to disk. You may confirm it by writing a file to $HOME/.azure/commands. Thanks

**Comment by arrownj** [comment]
Hi @mathurneha , any feedback for this issue ?

**Comment by arrownj** [comment]
Hi @mathurneha , will close this issue first for no more feedback for a long time. You can reopen it if you have other concerns. Thanks
