### ISSUE TITLE
Log Analytics Data cap 

### ISSUE THREAD

**Issue by yossi-y** [Azure/azure-cli#13546]
**Resource Provider**
microsoft.operationalinsights

**Description of Feature or Work Requested**
Add CLI/PowerShell support for setting Daily volume cap (aka data cap) on workspace ingestion.
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/manage-cost-storage#manage-your-maximum-daily-data-volume

**Minimum API Version Required**
2020-03-01-preview

**Swagger Link**
Not available yet.

**Target Date**
2020-06-30

**Comment by yungezz** [comment]
hi @MyronFanQiu could you pls have a look?

**Comment by yonzhan** [comment]
add to S171

**Comment by yoramsinger** [comment]
Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/9505
