### ISSUE TITLE
Add support for tab completion of command

### ISSUE THREAD

**Issue by mvvsubbu** [Azure/azure-cli#13540]
**Is your feature request related to a problem? Please describe.**
There are few tools which support auto completion of command by pressing tab. For example dotnet command does support this, having this feature would make usability lot easier. 

https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete

**Describe the solution you'd like**
az and press tab should show available options. 

**Describe alternatives you've considered**
Looking at help for command line

**Additional context**
Currently if we have to use any feature, need to look at the help having auto completion would simply discovery and figuring out usage very much

**Comment by yonzhan** [comment]
@arrownj  please take a look

**Comment by arrownj** [comment]
Hi @mvvsubbu , which platform are you using ? Windows, Linux or Mac ?

**Comment by mvvsubbu** [comment]
windows

**Comment by arrownj** [comment]
Hi @mvvsubbu , please kindly be noted that CLI do not support tab completion on Windows. You can try it on Linux or Mac.

**Comment by mvvsubbu** [comment]
Yes I know it doesn't support. Ask here is may be you would want to add the support. Given so many options in the tool, it will be easy for anyone to use. Users can't switch OS for tool right!!

**Comment by dtewinkel** [comment]
What about a same approach as the dotnet CLI tool takes? Add a command to get the completion. For instance `az complete --to-complete "vm " --position 3`, returning one option per line.

This would make it more uniform to integrate across different OSses or shells. It at least would help to integrate this into PowerShell where the tab completion could look something like:

```powershell
# PowerShell parameter completion shim for the az CLI
Register-ArgumentCompleter -Native -CommandName az -ScriptBlock {
     param($commandName, $wordToComplete, $cursorPosition)
         az complete --position $cursorPosition --to-complete "$wordToComplete" | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
         }
 }
```

My inspiration came from: [How to enable TAB completion for the .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete)

**Comment by dtewinkel** [comment]
I do like the proposed approach. It would make it really easy to integrate tab completion with PowerShell. Tab completion for az is one of the features that is really lacking on PowerShell.

**Comment by Rashair** [comment]
Is there a way to achieve it on `git bash`?

**Comment by Ileriayo** [comment]
Hi @arrownj, just installed az cli on the latest macbook m1 pro, it doesn't support tab completion. I followed the instruction from here (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos#completion-is-not-working) to configure Homebrew completion, all to no avail.
> Hi @mvvsubbu , please kindly be noted that CLI do not support tab completion on Windows. You can try it on Linux or Mac.

**Comment by mvvsubbu** [comment]
Ok fine, you can close the request
