### ISSUE TITLE
Describe which CLI command to use to import an SSH Key pairs and download private key from KV 

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/azure-cli#13548]
see 
https://github.com/Azure/azure-cli/issues/13547
https://github.com/MicrosoftDocs/azure-docs/issues/55072

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0f363b-7f21-0ea9-3e27-da7866c94102
* Version Independent ID: 6cc413e4-4f7d-9baa-a365-c9275fc6a7ad
* Content: [az keyvault key](https://docs.microsoft.com/en-us/cli/azure/keyvault/key?view=azure-cli-latest#az-keyvault-key-import)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by ezYakaEagle442** [comment]
Once the key is imported in KV, then **az keyvault key download** returns the public key only.
A similar question & explanation regarding certificates is described at https://github.com/Azure/azure-sdk-for-js/issues/7647#issuecomment-594935307


```sh
ssh-keygen -t rsa -b 4096 -N $ssh_passphrase -f ~/.ssh/$ssh_key -C "youremail@groland.grd"

az keyvault key import --name $ssh_key --vault-name $vault_name --pem-file ~/.ssh/$ssh_key --pem-password $ssh_passphrase
az keyvault key list --vault-name $vault_name
az keyvault key show --name $ssh_key --vault-name $vault_name
az keyvault key download --name $ssh_key --vault-name $vault_name --encoding PEM --file key2

```

Does KeyVault store both the public part in a KV Key and the private part of the imported key in a KV secret ?
**what i sthe CLI snippet then to download the private key** ?
```sh
az keyvault secret list --vault-name $vault_name
az keyvault secret show --name $vault_secret_name --vault-name $vault_name --output tsv

az keyvault secret download --file myLostKey.txt --name $vault_secret_name --vault-name $vault_name 
```

**Comment by bim-msft** [comment]
@ezYakaEagle442 Thanks for your feedback, it's a good question. In fact, KV stores both public part and private part of your key. Once you uploaded your key into KV, there is no way to show or download the private part: this is for security concern, you can use public key to do your own encryption, but you can only call KV API to do decryption.

Here is an article talking about this: https://odetocode.com/blogs/scott/archive/2018/03/08/decryption-with-azure-key-vault.aspx

> Secondly, speaking of public keys, only the public key is available to the system. The API call to GetKeyAsync doesn’t return private key data. This is why the DecryptAsync wrapper method does use the Key Vault API for decryption. In other words, private keys never leave the vault, which is one reason to use Key Vault for decryption instead of bringing private keys into the process.

**Comment by ezYakaEagle442** [comment]
So I added this just in case of the private key is lost, as it required to have it to SSH connect to the remote server.

```sh
ssh_prv_key_val=`cat ~/.ssh/$ssh_key`

az keyvault secret set --name ssh-passphrase --value $ssh_passphrase --vault-name $vault_name --description "AKS ${appName} SSH Key Passphrase" 
az keyvault secret set --name ssh-key --value "$ssh_prv_key_val" --vault-name $vault_name --description "AKS ${appName} SSH Private Key value" 

az keyvault secret list --vault-name $vault_name
az keyvault secret show --vault-name $vault_name --name ssh-passphrase -o table
az keyvault secret show --vault-name $vault_name --name ssh-key -o table

az keyvault secret download --file myLostKey.txt --name ssh-key --vault-name $vault_name
az keyvault secret download --file myLostPassPhrase.txt --name ssh-passphrase --vault-name $vault_name
```

**Comment by ezYakaEagle442** [comment]
Could you please update the docs describing this SSH Key pairs use case, expalining that there will be no way to get back the private key from KV runnning : 
az keyvault key download 
az keyvault key show

**Comment by bim-msft** [comment]
@ezYakaEagle442 Yes, saving private keys as secrets is a practical way.

`key show` already has this information:
![image](https://user-images.githubusercontent.com/3250203/82789302-a3e4f780-9e9c-11ea-980b-782ec8e35605.png)

`key download` doesn't have, I will update the doc accordingly. Thanks for the feedback!
