### ISSUE TITLE
Cli support for Encryption of cache & data-in-transit for OS/Data disks and temp disks for VM & VMSS

### ISSUE THREAD

**Issue by ramankumarlive** [Azure/azure-cli#13559]
**Resource Provider**
Compute Resource Provider

**Description of Feature or Work Requested**
We are introducing the encryption of the following:

1.	Encryption at rest for temp disks
2.	Encryption at rest for cache of OS and data disks
3.	Encryption of data-in-transit of OS and data disks

The above encryption features can be enabled by setting a new property EncryptionAtHost under securityProfile of VMs/VMSSs using the API version 2020-06-01 and above.

"securityProfile": { "encryptionAtHost": "true" }

You can find more details here: https://github.com/ramankumarlive/manageddisksendtoendencryptionpreview

**Minimum API Version Required**
2020-06-01 and above

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/9366

**Target Date**
06/30/2020

it will help us prioritize your request against other requests. --->

**Comment by yungezz** [comment]
feature request

**Comment by yungezz** [comment]
Swagger merged https://github.com/Azure/azure-rest-api-specs/pull/9366. pick it up.

**Comment by qwordy** [comment]
Hi Raman, can this field be changed when a VM/VMSS instance is already created?

**Comment by qwordy** [comment]
I noticed that swagger is merged to master branch. I will start my work.
