### ISSUE TITLE
unable to use az cli in cloud shell.

### ISSUE THREAD

**Issue by scottgorlick** [Azure/azure-cli#13556]
## Describe the bug
unsure when/how this started, but every AZ CLI command that I invoke from my cloud shell instance (not just this run command) will result in the same oauth token lookup exception.

**Command Name**
`az vm run-command invoke`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 688, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm run-command invoke --resource-group {} --name {} --command-id {} --scripts {} {} {}`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1

```

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by yungezz** [comment]
duplicate with #11749, #13528 , this is an issue in Cloudshell.

**Comment by Juliehzl** [comment]
@scottgorlick  if you still have the problem, you can try to run `az login` again. Please let me know if it is work with you :)

**Comment by scottgorlick** [comment]
That did work.

**Comment by Drewm3** [comment]
Removing compute label because this does not appear to be a compute specific issue.

**Comment by maertendMSFT** [comment]
This should be fixed now.  I cannot repro, please close.

**Comment by scottgorlick** [comment]
I'm unable to tell if this is working or not with my work account, but both of my "personal" accounts looked acceptable... I do think this issue is closed, but would like to point out another potential problem that is blocking my use of cloud shell with my work account.  If there is another issue open for the "Key Not Found", we're good, but if not, I'll create an issue for that item.

with my work account, it keeps failing with "Key Not Found" error (this happens the first login, using saved connection info, and using a the device auth flow):
```
Please enter the desired tenant number.
> 0
Do you want to save these connection settings for future logins? [y/n]
> y
Your connection settings have been saved for future logins.
Requesting a cloud shell instance...
Succeeded.
Requesting a terminal (this might take a while)...
**Key not found**
[process exited with code 1]
```
