### ISSUE TITLE
Cannot `az acr login` on Pengwin in WSL2

### ISSUE THREAD

**Issue by Pat-Ayres** [Azure/azure-cli#13551]
## Describe the bug

**Command Name**
`az acr login`

**Errors:**
```
cannot import name 'BlockBlobService' from 'azure.storage.blob' (/usr/lib/python3/dist-packages/azure/storage/blob/__init__.py)
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
cli/command_modules/acr/_archive_utils.py, ln 15, in <module>
    from azure.storage.blob import BlockBlobService
ImportError: cannot import name 'BlockBlobService' from 'azure.storage.blob' (/usr/lib/python3/dist-packages/azure/storage/blob/__init__.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr login -n {}`

## Expected Behavior
I am authenticated to my container registry.

## Environment Summary
```
Linux-4.19.84-microsoft-standard-x86_64-with-glibc2.29
Python 3.8.3
Shell: bash

azure-cli 2.0.81 *

Extensions:
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
acr

**Comment by yungezz** [comment]
duplicate with https://github.com/Azure/azure-cli/issues/13336

**Comment by Pat-Ayres** [comment]
Thank you @yungezz! Looking at #13336 helped me resolve my issue.  Pengwin wsl distro has a setup utility that I used to install az cli, but it installs an old version.  There is a PR open to update it: [here](https://github.com/WhitewaterFoundry/pengwin-setup/pull/234/commits/c5b6a381bf24ca30f60e25c9aebf0656c687ca96).  Using the updated commands in that commit installs the current version (2.6.0 at the time of writing) and this error no longer occurs.
