### ISSUE TITLE
az : Command group 'vm monitor metrics' is in preview.

### ISSUE THREAD

**Issue by bablushaikh** [Azure/azure-cli#13553]
az : Command group 'vm monitor metrics' is in preview. It may be changed/removed in a future release.
i have been facing this error while using az vm monitor metrics tail --name
                           --resource-group
                           [--aggregation {Average, Count, Maximum, Minimum, Total}]
                           [--dimension]
                           [--end-time]
                           [--filter]
                           [--interval]
                           [--metadata]
                           [--metrics]
                           [--namespace]
                           [--offset]
                           [--orderby]
                           [--start-time]
                           [--subscription]
                           [--top]

can you help me how can i resolve this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a219001-52f3-3dca-a599-cf366414ad97
* Version Independent ID: 0e3da82a-d806-46ed-bf76-4f594e9debe7
* Content: [az vm monitor metrics](https://docs.microsoft.com/en-us/cli/azure/vm/monitor/metrics?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by MyronFanQiu** [comment]
@bablushaikh looks like you input some wrong arguments or values. The easy way to use it is to input a vm's name and its resource group.

**Comment by yungezz** [comment]
hi @bablushaikh could you share your error? " Command group 'vm monitor metrics' is in preview. I" is a hint message, not error, it doesn't blocking usage of the command.

**Comment by bablushaikh** [comment]
Hi @yungezz i have used it in right manner and it is throwing back an error "az:Command group 'vm monitor metrics' is in preview. It may be changed/removed in a future release." this is in preview and i am not able to use it.

**Comment by bablushaikh** [comment]
@yungezz however i'm using **get-azmetric** cmdlet to pull the data but the " **timegrain**"  parameter is having an issue with "**storage accounts**" metrics type "**Used capacity**". i have taken time grain for 1day but it is throwing me an error for the cmdlet.

**Comment by yungezz** [comment]
hi @bablushaikh could you pls share the error you met to help investigation? Thanks. below message isn't an error
```
az : Command group 'vm monitor metrics' is in preview. It may be changed/removed in a future release.
```

**Comment by qwordy** [comment]
Could you share a screenshot?
"az : Command group 'vm monitor metrics' is in preview. It may be changed/removed in a future release." This is not an error, but a warning.

**Comment by qwordy** [comment]
Any update?

**Comment by bablushaikh** [comment]
@qwordy you can close this issue.
