### ISSUE TITLE
Typo in `az aks update` exception

### ISSUE THREAD

**Issue by SpartyInDetroit** [Azure/azure-cli#13555]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Running command `az aks update -g <resource-group> -n <resource-name>` with no further arguments will yield the following exception:

```
Please specify one or more of "--enable-cluster-autoscaler" or "--disable-cluster-autoscaler" or "--update-cluster-autoscaler" or "--load-balancer-managed-outbound-ip-count" or"--load-balancer-outbound-ips" or "--load-balancer-outbound-ip-prefixes" or"--load-balancer-outbound-ports" or"--load-balancer-idle-timeout" or"--attach-acr" or "--dettach-acr" or"--"api-server-authorized-ip-ranges
```

Note the suggestion for `--dettach-acr`. This is a typo as the actual flag is `--detach-acr` with a single t.

**To Reproduce**

Run the following command with valid resource names:
`az aks update -g <resource-group> -n <resource-name>`

**Expected behavior**

`--detach-acr` instead of `--dettach-acr`

**Environment summary**

azure CLI version: 2.5.1

**Additional context**

**Comment by SpartyInDetroit** [comment]
Created a pull request here: #13554

**Comment by yonzhan** [comment]
aks
