### ISSUE TITLE
AZ command does nothing

### ISSUE THREAD

**Issue by edsonharantes** [Azure/azure-cli#13569]
> ### az command does nothing, CLI version 2.6.0

**Describe the bug**
I just installed the azure cli tool, but when I type az login on the cmd window or use power shell, nothing happens, not even an error message is displayed.

**To Reproduce**
1. install azure CLI tool
2. open a power shell window, type az login (or any other command from the az CLI)
3. nothing happens

**Expected behavior**
It should open a browser windows to type my credentials, or display a code in the power shell window to be used to authenticate.

**Environment summary**
1. windows 10 1909
2. python 3.8 installed
3. azure cli version 2.6.0
4. power shell 5.1.18362.752
5. not using a vpn

**Additional context**

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by mithuns1986** [comment]
I am also facing the same issue in my linux server and az commands hangs indefinitely.


https://github.com/Azure/azure-cli/issues/13505

**Comment by arrownj** [comment]
Hi @edsonharantes , could you please help run command with `--debug` and see whether there is some output ?

**Comment by edsonharantes** [comment]
Hello @arrownj, how are you? 

I tried that, nothing happens, the power shell window just jump to the next line =/

Is there a log file being saved somewhere that could help me solve this issue?

**Comment by edsonharantes** [comment]
I update the version of azure cli to 2.7.0 and the error persists

Also, there's a error message in the windows event viewer (application error).

![image](https://user-images.githubusercontent.com/7422540/83665936-87cf0d80-a5a2-11ea-9a6d-5c66315313fe.png)

**Comment by arrownj** [comment]
Hi @edsonharantes , how did you install CLI ? With `pip install` or from a MSI ?

**Comment by edsonharantes** [comment]
hi @arrownj , I used the MSI

**Comment by arrownj** [comment]
Hi @edsonharantes , sorry for the late to reply. Is this problem still valid ? 

It seems that you use a system python, which is so wired. If you install CLI from a MSI, it has an embedded python in and should not use the system python version.

Could you please help execute `get-command az` in powershell and see what exactly the executing command is ? It should be something like below:
> Application     az.cmd                                             0.0.0.0    C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd

And the content of `az.cmd` is:
>::
:: Microsoft Azure CLI - Windows Installer - Author file components script
:: Copyright (C) Microsoft Corporation. All Rights Reserved.
::
@IF EXIST "%~dp0\..\python.exe" (
  SET AZ_INSTALLER=MSI
  "%~dp0\..\python.exe" -IBm azure.cli %*
) ELSE (
  echo Failed to load python executable.
  exit /b 1
)

**Comment by edsonharantes** [comment]
Hello @arrownj how are you doing? 

I had a problem with my ssd last week and I end up formatting my machine =/ 

Maybe it was something related to my ssd problem, I'm not sure.

Anyway, I did not tried the "az login" after that. I think It's ok to close this issue, for now at least

Thank you for your support!!!

**Comment by ZedTDean** [comment]
I have the same problem on Windows 11 , It seems i have to format the machine as well , I think there is bug somewhere , it should be solved . I uninstalled all the CLI and still it does exists

**Comment by bebound** [comment]
@ZedTDean What's the output of `az login --debug`, are you using the latest version?

**Comment by blueboxes** [comment]
I have the same issue. In my case, I am running in Windows docker container (base image mcr.microsoft.com/dotnet/framework/sdk:4.8.1), installed the MSI and all `az` commands do nothing with other non-existant commands correctly error.

```
RUN powershell -Command \
    Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; \
    Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; \
    Remove-Item AzureCLI.msi -Force
```

![Recording 2023-06-26 at 10 36 31](https://github.com/Azure/azure-cli/assets/985852/44901235-012b-4b77-b550-cbbd7fec59a4)

**Comment by bebound** [comment]
@blueboxes  I can't repro.
What's the output of `cd "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\" ; ./az.cmd`

**Comment by blueboxes** [comment]
It was completely blank. I have rebuilt the docker image and it is all ok now, very odd.

**Comment by ness001** [comment]
me 2
