### ISSUE TITLE
Please add 2 optional properties for OperationalInsights saved searches API

### ISSUE THREAD

**Issue by arolshan** [Azure/azure-cli#13562]
**Resource Provider**

Microsoft.OperationalInsights
**Description of Feature or Work Requested**

Adding 2 new properties for existing CLI, 2020-03-01-preview version, which are defined here:
https://github.com/Azure/azure-rest-api-specs/pull/9498
docs: https://docs.microsoft.com/en-us/azure/azure-monitor/insights/solutions-resources-searches-alerts

**Minimum API Version Required**

2020-03-01-preview

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/9498

**Target Date**

June 1st 2020

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172
