### ISSUE TITLE
Webapp:How do I connect my Web App to App Insights & Workspace?

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-cli#13571]
It's unclear how to turn on application insights using Azure CLI and link to my Azure Monitor Workspace.  Please provide documentation on how to perform this scenario using Azure CLI.

I'm using App Service for WebApp running Linux Node|LTS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-update)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
App insights team is working on this - & they will provide an ETA not webapp specific issue.

**Comment by yutanglin16** [comment]
The CLI used would be CLI for App Insights and not App Service.

To connect AI to Workspace, you can use the commands below with the following parameter "--workspace":
[az monitor app-insights component update](https://learn.microsoft.com/en-us/cli/azure/monitor/app-insights/component?view=azure-cli-latest#az-monitor-app-insights-component-update)
[az monitor app-insights component create](https://learn.microsoft.com/en-us/cli/azure/monitor/app-insights/component?view=azure-cli-latest#az-monitor-app-insights-component-create)

To connect AI to web app use this:
[az monitor app-insights component connect-webapp](https://learn.microsoft.com/en-us/cli/azure/monitor/app-insights/component?view=azure-cli-latest#az-monitor-app-insights-component-connect-webapp)
