### ISSUE TITLE
Error querying resources

### ISSUE THREAD

**Issue by maxleonca** [Azure/azure-cli#13578]
### **This is autogenerated. Please review and update as needed.**
**Environment**
az --version
azure-cli                          2.6.0

command-modules-nspkg              2.0.3
core                               2.6.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
db-up                             0.1.13

Python location '/home/mleon/.lib/azure-cli/bin/python'
Extensions directory '/home/mleon/.azure/cliextensions'

Python (Linux) 3.5.2 (default, Apr 16 2020, 17:47:17)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.

## Describe the bug

**Command Name**
`az resource list`

**Errors:**
```
invalid syntax (custom.py, line 673)
Traceback (most recent call last):
python3.5/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 553, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 344, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
<frozen importlib._bootstrap_external>, ln 727, in source_to_code
<frozen importlib._bootstrap>, ln 222, in _call_with_frames_removed
cli/command_modules/resource/custom.py, ln 673
    err_messages = [f'{what_if_error.code} - {what_if_error.message}']
                                                                    ^
SyntaxError: invalid syntax
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az resource list`

## Environment Summary
```
Linux-4.4.0-178-generic-x86_64-with-Ubuntu-16.04-xenial
Python 3.5.2
Installer: 

azure-cli 2.6.0

Extensions:
db-up 0.1.13

```

**Comment by yungezz** [comment]
hi @houk-ms could you pls have a look? thanks

**Comment by houk-ms** [comment]
@maxleonca Seems to be your python version issue. AzureCLI requires python with version 3.6 or 3.7 or 3.8, see [here](https://github.com/houk-ms/azure-cli).

By the way, is your AzureCLI installed by pip? If so, upgrade you python and then install AzureCLI, it should work.

**Comment by maxleonca** [comment]
Thank you, my bad.

**Comment by houk-ms** [comment]
Great! So I gonna close this issue, you are welcomed to open issues if you have further feedback.
