### ISSUE TITLE
Set group description via 'az ad group create'

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-cli#13574]
**Is your feature request related to a problem? Please describe.**
Not all properties of groups are settable via the CLI.

**Describe the solution you'd like**
I'd like to be able to set the group description property via Azure CLI in `az ad group create`

**Describe alternatives you've considered**
Manually getting a token and doing REST API calls (that defeats the purpose, it's long and arduous)

**Comment by yungezz** [comment]
hi @arrownj could  you have a look? thanks

**Comment by arrownj** [comment]
Hi @stewartadam , we will add `--description` parameter in our next release.
