### ISSUE TITLE
It would be nice to see links to/from azure cli

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-cli#13570]
If a customer enters the doc site from azure cli, there is no explanation on what things are.  It would be useful to include in the entire CLI documentation a link back to what it is, for example, what is an linked-service?  If I'm using App Service for Web Apps is this how I link my apps to log analytics workspace?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ed2f4f2-6622-c151-ef61-1d8f8a708fcf
* Version Independent ID: bc7308a5-8e00-ff74-31be-d7c683b47508
* Content: [az monitor log-analytics workspace linked-service](https://docs.microsoft.com/en-us/cli/azure/monitor/log-analytics/workspace/linked-service?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S171

**Comment by MyronFanQiu** [comment]
@jsntcy Could you please take a look?

**Comment by jsntcy** [comment]
@awentzel, I'm not so clear about your meaning, could you explain more?
Do you mean we need add a document link about what's linked-service in https://docs.microsoft.com/en-us/cli/azure/monitor/log-analytics/workspace/linked-service?view=azure-cli-latest?

@dbradish-microsoft, It seems currently there is no document link about what's linked-service for log analytics workspace, could you help on this?

**Comment by awentzel** [comment]
@jsntcy in generally, when looking at CLI documentation for any service (example you referenced above), you see commands, and what they do, but nothing about what it is.  For example, "Manage linked service for log analytics workspace." What if the customer doesn't know what a "linked service" is.  Where is that detail or a link to that detail?  It would be nice complementary content to provide at the introduction or in the navigation.  I could see links for Best Practices, Architecture, Service, and Platform.  4 associative entry points for those unfamiliar with linked services.  Each of thee 4 speaks to different roles that would be working in that area.  

I think this would be an improvement and I hope this explains it a little better.

**Comment by jsntcy** [comment]
@awentzel, thanks for your explanation and your points make sense to me.
Yes, it seems to be common issue for Azur CLI document and I'll tag it as improvement and will think how we can improve CLI documentation.

**Comment by jsntcy** [comment]
Add the following explanation for linked services in CLI help:
“Linked services is used to defined a relation the workspace to another Azure resource. Log Analytics and Azure resources then leverage this connection in their operations. Example uses of Linked Services in Log Analytics workspace is Automation account and workspace association to CMK.”
