### ISSUE TITLE
Webapp:Azure CLI: Creating a Webapp

### ISSUE THREAD

**Issue by OvalAdmin** [Azure/azure-cli#13581]
## Describe the bug

I was trying to setup a webapp from the command line, any invocation that I tried seems to error out. Weirdly azure seems to be looking for project files in the current directory, or beneath it. I'm not sure why it requires this when firing up a web application.

**Command Name**
`az webapp up`

**Errors:**
```
[Errno 2] No such file or directory: 'C:\\Users\\AB\\DebugBasics.csproj'
Traceback (most recent call last):
pip-install-yf22vmg2\knack\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 654, in execute
cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
cli\core\commands\__init__.py, ln 709, in _run_job
cli\command_modules\appservice\commands.py, ln 55, in _polish_bad_errors
cli\core\commands\__init__.py, ln 688, in _run_job
cli\core\commands\__init__.py, ln 325, in __call__
azure\cli\core\__init__.py, ln 545, in default_command_handler
...
lib\xml\etree\ElementTree.py, ln 1196, in parse
    tree.parse(source, parser)
lib\xml\etree\ElementTree.py, ln 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\AB\\DebugBasics.csproj'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az webapp up --sku {SKU} -n {PROJECT} -l {LOCATION}`

Varying the values for `{SKU}`, `{PROJECT}` and `{LOCATION}` do not seem to affect the out come.

## Expected Behavior

I was expecting a webapp to be created.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.6.0

```

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by panchagnula** [comment]
Please try az webapp create if you want to simply create an app and not deploy local content to the app. Thanks!
