### ISSUE TITLE
Add new "simulate-eviction" command action for az vmss

### ISSUE THREAD

**Issue by sandeepkv93** [Azure/azure-cli#13583]
**Resource Provider**
What is the Azure resource provider your feature is part of?
- **Compute Resource Provider (Microsoft.Compute)**

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
- This API simulates the Eviction of Spot VMScaleSet Virtual Machines. 
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesetvms/simulateeviction

- #### Background
  Azure has announced a new feature Azure Spot. https://azure.microsoft.com/en-us/pricing/spot/ Here, customer gets deep discounts on VMs but in case Azure needs capacity to cater for regular VMs. these Spots VMs will be evicted with a 30 seconds In-VM notification. This In-VM notification will be via Azure Metadata service, so that, before eviction, it send the 30 seconds notification inorder to prepare the workload for the customer.

   Now, customer wanted an API where he/she can call it to simulate the behaviour as if the VM is evicted due to Capacity reasons. In that case customer would get an invm notification and they can parse that and have a logic for backing up some data or any other disaster management.

  This SimulateEviction API does that. It evicts the VMScaleSet VM and then, as mentioned above, if the customer subscribed for In-VM notification via Azure metadata service, they will get the notification before the eviction.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

2019-12-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

https://github.com/Azure/azure-rest-api-specs/pull/9102

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

- The feature/API is already GA. Can this be prioritized in this semester or early IRON semester as this is the highly asked customer requirement

**Comment by yungezz** [comment]
ack on the request.

**Comment by houk-ms** [comment]
PR merged, close the request now.
