### ISSUE TITLE
Storage command failing with auth mode login

### ISSUE THREAD

**Issue by brdly-smith** [Azure/azure-cli#13585]
## Describe the bug

**Command Name**
`az storage container generate-sas`

**Errors:**
```
self.account_key should not be None.
Traceback (most recent call last):
Temp\pip-install-yf22vmg2\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 709, in _run_job
azure\cli\command_modules\storage\__init__.py, ln 257, in new_handler
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
site-packages\azure\cli\core\__init__.py, ln 545, in default_command_handler
cli\command_modules\storage\operations\blob.py, ln 556, in generate_container_shared_access_signature
multiapi\storage\v2018_11_09\blob\baseblobservice.py, ln 421, in generate_container_shared_access_signature
multiapi\storage\v2018_11_09\common\_error.py, ln 130, in _validate_not_none
ValueError: self.account_key should not be None.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container generate-sas --account-name {} --name {} --permissions {} --expiry {} --auth-mode {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.6.0

```

**Comment by yonzhan** [comment]
add to S171

**Comment by Juliehzl** [comment]
@brdly-smith Thanks for your feedback! It is a known issue in azure cli, which is because --auth-mode is not support in generate_sas. We will remove it this sprint and please use account_key or connection_string for your command to unblock your work.

**Comment by brdly-smith** [comment]
Does this mean we can only use account_key and connection_string in the future or will the error when not using auth_mode be removed from genereate-sas?

**Comment by Juliehzl** [comment]
> Does this mean we can only use account_key and connection_string in the future or will the error when not using auth_mode be removed from genereate-sas?

yes
