### ISSUE TITLE
ACS: Subgroup and connect command  for all 3 orchestrators 

### ISSUE THREAD

**Issue by sauryadas** [Azure/azure-cli#1358]
I am seeing only dcos and k8s as of now

<img width="720" alt="screen shot 2016-11-16 at 10 18 44 pm" src="https://cloud.githubusercontent.com/assets/15387759/20378408/bc679dbe-ac4a-11e6-846d-e2a51581f56b.png">

az acs dcos/kubernetes/swarm connect command to ssh into the master node for all orchestrators

there is a browse command for dcos which ssh's in and opens the dcos dashboard in the browser. connect is better than browse. 

For swarm and k8s there is no management dashboard , so we could ssh into the masters and open the bash shell

Thoughts?

**Comment by sauryadas** [comment]
@brendanburns thoughts?

**Comment by brendandburns** [comment]
@sauryadas I don't want to encourage the use of SSH tunnel.  It's an anti-pattern that I'd prefer not to have to commit to via a CLI with a deprecation policy.

**Comment by brendandburns** [comment]
@sauryadas I am ok with subgrouping if we want, and honestly, the cluster type is superflous since it can be derived from the cluster API info.  So:

```console
az acs browse -r resource-group -n cluster-name
```

Would work for both DC/OS and Kubernetes clusters

likewise:

```console
az acs install-cli -r resource-group -n cluster-name
```

Could work for all three.

**Comment by brendandburns** [comment]
@sauryadas I also missed one thing you said: "for swarm and k8s there is no management dashboard"

That is incorrect for k8s, I've already added browse for k8s.

**Comment by lostintangent** [comment]
@brendandburns I really like the idea of making commands orchestrator agnostic if possible and it makes sense. The browse command seems like a good candidate for sure.
