### ISSUE TITLE
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded

### ISSUE THREAD

**Issue by lchave** [Azure/azure-cli#13587]
## Describe the bug

**Command Name**
`az sql db audit-policy update`

**Errors:**
```
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/b526aa26-e5c4-4583-90a3-6d0a4663242a/resourceGroups/test-data-lake-rg/providers/Microsoft.Sql/servers/test-data-lake-sb-server/databases/test-data-lake-db/auditingSettings/default?api-version=2017-03-01-preview (Caused by ResponseError('too many 500 error responses',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sql db audit-policy update --name {} --resource-group {} --server {} --state {} --storage-account {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.6.0

Extensions:
interactive 0.4.4

```

**Comment by yonzhan** [comment]
sql

**Comment by lchave** [comment]
Hello, following up on this, we have not been able to enable the audit and threat policies for this SQL server due to the error we have reported above. Please let us know if there are any updates.

**Comment by chhavikishore** [comment]
@lchave Hi, you might can check the following issue if it helps you : https://github.com/Azure/azure-cli/issues/13518

**Comment by cocowalla** [comment]
Having the same issue (it works with `audit-policy`, but I get this with `threat-policy`)

**Comment by cocowalla** [comment]
I get this with `threat-policy`, regardless of what parameters I use. If I add the `--debug` flag, I can see the call that fails with error 500 is to:

```
https://management.azure.com/subscriptions/MY_SUBSCRIPTION/resourceGroups/MY_GROUP/providersMicrosoft.Sql/servers/MY_SERVER_NAME/databases/MY_DB_NAME/securityAlertPolicies/default?api-version=2014-04-01
```

In the end, I had to use `az rest` to work around it, with 2 notable things:

1. When specifying `storageEndpoint`, it *must* have a trailing forward slash
2. The API version that Azure CLI is using (`2014-04-01`) appears to be broken - I had to use `2020-02-02-preview`

Example of what is working for me (not I use an empty storage key, because I'm using a SQL Server MSI):

```bash
az rest \
  --method put \
  --uri "https://management.azure.com/subscriptions/${subscription_id}/resourceGroups/${group}/providers/Microsoft.Sql/servers/${server_name}/databases/${db_name}/securityAlertPolicies/default?api-version=2020-02-02-preview" \
  --body '{"properties": {"state": "Enabled", "emailAccountAdmins": "Disabled", "storageEndpoint": "https://'"${storage_name}"'.blob.core.windows.net/", "storageAccountAccessKey": ""}}'
```

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed now. Please upgrade to the latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
