### ISSUE TITLE
az resource create --is-full-object --properties fails in powershell

### ISSUE THREAD

**Issue by bquantump** [Azure/azure-cli#13580]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

PLEASE LOOK AT THIS TEXT RAW, GITHUB DOES MARKDOWNS SO IT HIDES THE EXACT CHARACTERS!
**Describe the bug**
When trying to create a full object with the cli via a powershell, the command cannot parse a valid JSON string with both using single quotes around strings in the JSON and using powershell's escape charter "`"". The HSM team also has encountered this issue as well. 

With powershell escape:

az resource create -g stevens-rg-japan -n test --resource-type Microsoft.web/sites --is-full-object --properties "{`"location`": `"japaneast`", `"sku`": {`"name`": `"Lu`"}, `"tags`": {`"Dept`": `"h`"}, `"properties`": {`"stampId`": `"stamp1`", `"networkProfile`": {`"subnet`": {`"id`": `"/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/stevens-rg-japan/providers/Microsoft.Network/virtualNetworks/vm1VNET/subnets/hsm`"}, `"networkInterfaces`": [{`"privateIpAddress`": `"10.0.2.21`"}]}}}"
Error parsing JSON.
{location: japaneast, sku: {name: Lu}, tags: {Dept: h}, properties: {stampId: stamp1, networkProfile: {subnet: {id: /subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/stevens-rg-japan/providers/Microsoft.Network/virtualNetworks/vm1VNET/subnets/hsm}, networkInterfaces: [{privateIpAddress: 10.0.2.21}]}}}
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

With powershell with single quotes around strings:

az resource create -g stevens-rg-japan -n test --resource-type Microsoft.HardwareSecurityModules/dedicatedHSMs --is-full-object --properties "{'location': 'japaneast', 'sku': {'name': 'SafeNet Luna Network HSM A790'}, 'tags': {'Dept': 'h'}, 'properties': {'stampId': 'stamp1', 'networkProfile': {'subnet': {'id': '/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/stevens-rg-japan/providers/Microsoft.Network/virtualNetworks/vm1VNET/subnets/hsm'}, 'networkInterfaces': [{'privateIpAddress': '10.0.2.21'}]}}}"
Error parsing JSON.
{'location': 'japaneast', 'sku': {'name': 'SafeNet Luna Network HSM A790'}, 'tags': {'Dept': 'h'}, 'properties': {'stampId': 'stamp1', 'networkProfile': {'subnet': {'id': '/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/stevens-rg-japan/providers/Microsoft.Network/virtualNetworks/vm1VNET/subnets/hsm'}, 'networkInterfaces': [{'privateIpAddress': '10.0.2.21'}]}}}
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

Of course "\"" will not work in PS:

az resource create -g stevens-rg-japan -n test --resource-type Microsoft.HardwareSecurityModules/dedicatedHSMs --is-full-object --properties "{\"location\": \"japaneast\", \"sku\": {\"name\": \"SafeNet Luna Network HSM A790\"}, \"tags\": {\"Dept\": \"h\"}, \"properties\": {\"stampId\": \"stamp1\", \"networkProfile\": {\"subnet\": {\"id\": \"/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/stevens-rg-japan/providers/Microsoft.Network/virtualNetworks/vm1VNET/subnets/hsm\"}, \"networkInterfaces\": [{\"privateIpAddress\": \"10.0.2.21\"}]}}}"
az: error: unrecognized arguments: location\: \japaneast\, \sku\: {\name\: \SafeNet Luna Network HSM A790\}, \tags\: {\Dept\: \h\}, \properties\: {\stampId\: \stamp1\, \networkProfile\: {\subnet\: {\id\: \/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/stevens-rg-japan/providers/Microsoft.Network/virtualNetworks/vm1VNET/subnets/hsm\}, \networkInterfaces\: [{\privateIpAddress\: \10.0.2.21\}]}}}

**To Reproduce**
Try creating any resource that takes in a JSON string with strings contained in the JSON.

**Expected behavior**
Example from Linux 20.04 via bash:

 az resource create -g stevens-rg-japan -n test --resource-type Microsoft.HardwareSecurityModules/dedicatedHSMs --is-full-object --properties "{\"location\": \"japaneast\", \"sku\": {\"name\": \"SafeNet Luna Network HSM A790\"}, \"tags\": {\"Dept\": \"h\"}, \"properties\": {\"stampId\": \"stamp1\", \"networkProfile\": {\"subnet\": {\"id\": \"/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/stevens-rg-japan/providers/Microsoft.Network/virtualNetworks/vm1VNET/subnets/hsm\"}, \"networkInterfaces\": [{\"privateIpAddress\": \"10.0.2.21\"}]}}}"

{- Finished ..
  "id": "/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/stevens-rg-japan/providers/Microsoft.HardwareSecurityModules/dedicatedHSMs/test",
  "identity": null,
  "kind": null,
  "location": "japaneast",
  "managedBy": null,
  "name": "test",
  "plan": null,
  "properties": {
    "networkProfile": {
      "networkInterfaces": [
        {
          "id": "/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/stevens-rg-japan/providers/Microsoft.Network/networkInterfaces/test_HSMnic",
          "privateIpAddress": "10.0.2.21",
          "resourceGroup": "stevens-rg-japan"
        }
      ],
      "subnet": {
        "id": "/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/stevens-rg-japan/providers/Microsoft.Network/virtualNetworks/vm1VNET/subnets/hsm",
        "resourceGroup": "stevens-rg-japan"
      }
    },
    "provisioningState": "Succeeded",
    "stampId": "stamp1",
    "statusMessage": "The Dedicated HSM device is provisioned successfully and ready to use."
  },
  "resourceGroup": "stevens-rg-japan",
  "sku": {
    "capacity": null,
    "family": null,
    "model": null,
    "name": "SafeNet Luna Network HSM A790",
    "size": null,
    "tier": null
  },
  "tags": {
    "Dept": "h"
  },
  "type": "Microsoft.HardwareSecurityModules/dedicatedHSMs"
}

**Environment summary**
Windows 10, powershell, 6.0 and powershell 7.0

**Comment by yungezz** [comment]
@zhoxing-ms could you pls have a look? thanks

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
@bquantump Hi, This is a typical question of how to pass JSON parameters in PowerShell environment. As for it, I give the following explanations:

Only double quotes are allowed to declare strings in [JSON syntax](https://www.json.org/json-en.html), but if the input parameters contain double quotes, it must be escaped, otherwise they will be treated as string encapsulation symbols.

The double quote escape requires the following work:
1. Add prefix `\` to the double quotes in the input values to interpret double quotes in in the string as literal (this is shown in the examples of `-h`)
2. If you are using PowerShell environment, because the escape character of PowerShell is not `\`, additional parsing logic is required:
```pwsh
> az version --query '\"azure-cli\"'
"2.5.1"

> az version --query "\`"azure-cli\`""
"2.5.1"

> az version --query "\""azure-cli\"""
"2.5.1"

> az --% version --query "\"azure-cli\""
"2.5.1"

> az --% version --query \"azure-cli\"
"2.5.1"
```

If you want more guidance on handling quotes, please refer to the documentation: [doc link](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues)

**Comment by zhoxing-ms** [comment]
@bquantump For your scenario, there are two simple ways to pass parameters as follows:
```pwsh
az resource create -g stevens-rg-japan -n test --resource-type Microsoft.HardwareSecurityModules/dedicatedHSMs --is-full-object --properties '{\"location\": \"japaneast\", \"sku\": {\"name\": \"SafeNet Luna Network HSM A790\"}, \"tags\": {\"Dept\": \"h\"}, \"properties\": {\"stampId\": \"stamp1\", \"networkProfile\": {\"subnet\": {\"id\": \"/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/stevens-rg-japan/providers/Microsoft.Network/virtualNetworks/vm1VNET/subnets/hsm\"}, \"networkInterfaces\": [{\"privateIpAddress\": \"10.0.2.21\"}]}}}'
```
```pwsh
az --% resource create -g stevens-rg-japan -n test --resource-type Microsoft.HardwareSecurityModules/dedicatedHSMs --is-full-object --properties "{\"location\": \"japaneast\", \"sku\": {\"name\": \"SafeNet Luna Network HSM A790\"}, \"tags\": {\"Dept\": \"h\"}, \"properties\": {\"stampId\": \"stamp1\", \"networkProfile\": {\"subnet\": {\"id\": \"/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/stevens-rg-japan/providers/Microsoft.Network/virtualNetworks/vm1VNET/subnets/hsm\"}, \"networkInterfaces\": [{\"privateIpAddress\": \"10.0.2.21\"}]}}}"
```
If you still have any other questions, please feel free to let us know

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
