### ISSUE TITLE
Updating app gateway address pool using --add removes existing hosts

### ISSUE THREAD

**Issue by subhasishdc** [Azure/azure-cli#13599]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I'm trying to update the servers in the app gateway's backend pool via the CLI using the --add command. The goal is to add additional VMs to the pool. However, what is happening is that the new host is getting added but the existing VMs in the pool are getting removed.

**To Reproduce**
schowdhu-mn2:~ schowdhu$ az network application-gateway address-pool list -g scus-ei-k2-network-rg --gateway-name azureei1-aag01-scus --subscription c3b5358d-d824-450c-badc-734462b9bbf1 | jq -r '.[].backendAddresses[] | .ipAddress'
10.3.8.198
10.3.8.197
10.3.8.196
schowdhu-mn2:~ schowdhu$ az network application-gateway address-pool update -g scus-ei-k2-network-rg --gateway-name azureei1-aag01-scus --name appGatewayBackendPool --add backendAddresses "{\"ip_address\":\"10.3.8.199\"}" --subscription c3b5358d-d824-450c-badc-734462b9bbf1
{
  "backendAddresses": [
    {
      "fqdn": null,
      "ipAddress": "10.3.8.199"
    }
  ],
  "backendIpConfigurations": null,
  "etag": "W/\"822e9614-6f0c-4e95-970d-2c94c4c42a80\"",
  "id": "/subscriptions/c3b5358d-d824-450c-badc-734462b9bbf1/resourceGroups/scus-ei-k2-network-rg/providers/Microsoft.Network/applicationGateways/azureei1-aag01-scus/backendAddressPools/appGatewayBackendPool",
  "name": "appGatewayBackendPool",
  "provisioningState": "Succeeded",
  "resourceGroup": "scus-ei-k2-network-rg",
  "type": "Microsoft.Network/applicationGateways/backendAddressPools"
}
schowdhu-mn2:~ schowdhu$ az network application-gateway address-pool list -g scus-ei-k2-network-rg --gateway-name azureei1-aag01-scus --subscription c3b5358d-d824-450c-badc-734462b9bbf1 | jq -r '.[].backendAddresses[] | .ipAddress'
10.3.8.199

**Expected behavior**
The existing hosts should not be removed. Aim is to add the new VM to the existing pool

**Environment summary**
schowdhu-mn2:~ schowdhu$ az --version
azure-cli (2.0.55)

**Additional context**
Is this the correct way to add a new host to the existing backend pool of the application gateway

**Comment by yungezz** [comment]
hi @MyronFanQiu could you have a look?

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172

**Comment by subhasishdc** [comment]
@MyronFanQiu : Thanks for approving my PR https://github.com/Azure/azure-cli/pull/13780.

The example which has been added in the PR has the bug which is raised by this issue ( https://github.com/Azure/azure-cli/issues/13599 ). Will this bug also be fixed in the same release as the PR. I tried looking into the code for this bug but could not find the exact source of the --add parameter. The behavior should be adding to the list of the backend pool addresses, however, seems the list is being overwritten with the new value being provided.

I tried to submit a fix for this and tried looking into the codebase but could not find this part of the code. Thanks for helping.

**Comment by MyronFanQiu** [comment]
@subhasishdc Thanks for your contribution. 😄 This issue is a little bit complicated. `--add` is a generic argument exposed in most `update` command. This issue should be an edge case for original design. If you want and have time, you can take a look at this issue and I'm willing to provide any help you need. I've not figured out the root cause for this issue yet.

**Comment by subhasishdc** [comment]
@MyronFanQiu : I would love to help if I receive some guidance and direction on the correct approach from you. I am available on Microsoft Teams and my id is "schowdhuri@linkedin.com" (Full Name: Subhasish Dutta Chowdhuri). If you are okay, then we can discuss this on Teams.
