### ISSUE TITLE
Error assigning managed identity operator role to AKS Cluster

### ISSUE THREAD

**Issue by roblohmann** [Azure/azure-cli#13591]
I'm trying to access a keyvault from within our Azure Kubernetes Cluster. To do [this](https://samcogan.com/pod-identity-with-kubernetes-in-azure/) I'm following the steps in this blogpost.

When executing the following command i'm getting an error;

`az role assignment create --role "Managed Identity Operator" --assignee <CLIENT ID OF AKS CLUSTER> --scope <FULL RESOURCE ID OF MANAGED IDENTITY>`

## Describe the bug

**Command Name**
`az role assignment create`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 688, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role assignment create --role {} --assignee {} --scope {}`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1 *

Extensions:
application-insights 0.1.1

```

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by yungezz** [comment]
duplicate iwth #11749

**Comment by arrownj** [comment]
Hi @roblohmann , this is a known issue of CloudShell. To workaround, you can run `az login` and rerun your commands. The CloudShell issue will be traced in #11949. Let me know if you have other problems.
