### ISSUE TITLE
[Monitor] Expose `--no-wait` for command `az monitor log-analytics cluster create`

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#13593]
**Resource Provider**
Log-Analytics

**Description of Feature or Work Requested**
Expose `--no-wait` for command `az monitor log-analytics cluster create`

**Minimum API Version Required**
2020-03-01-preview

**Swagger Link**

**Target Date**

**Comment by yonzhan** [comment]
add to S171
