### ISSUE TITLE
Error running the comand "az ad sp create-for-rbac"

### ISSUE THREAD

**Issue by JaviRpo** [Azure/azure-cli#13596]
This was following the [guide](https://docs.microsoft.com/en-us/learn/modules/provision-infrastructure-azure-pipelines/6-run-terraform-remote-storage#create-a-service-principal) in the step 2

```
ARM_CLIENT_SECRET=$(az ad sp create-for-rbac \
  --name http://tf-sp-$UNIQUE_ID \
  --role Contributor \
  --scopes "/subscriptions/$ARM_SUBSCRIPTION_ID" \
  --query password \
  --output tsv)
```

## Describe the bug

**Command Name**
`az ad sp create-for-rbac`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 686, in _run_job
    cmd_copy.exception_handler(ex)
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad sp create-for-rbac --name {} --role {} --scopes {} --query {} --output {}`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1 *

```

**Comment by yungezz** [comment]
hi @JaviRpo just to confirm, did you see the error in Cloudshell?

**Comment by JaviRpo** [comment]
@yungezz yes, it was in Cloudshell.
The error is intermittent. I closed the Cloudshell, open a new one, and the error didn't happen anymore.

**Comment by yungezz** [comment]
hi @JaviRpo sorry for late response, this is an known issue in Cloudshell #11749. As a workaround, pls try run `az login`.

**Comment by arrownj** [comment]
Hi @JaviRpo , do it work after you run `az login`. If no more concern, I will close this first, CloudShell problem will be traced in #11749.
