### ISSUE TITLE
`az storage account list -otable` displays incorrect

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#13602]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

`az storage account list -otable` displays incorrect. I don't have a monitor of 50 inch.

![image](https://user-images.githubusercontent.com/5019528/82528062-80ebd800-9b6a-11ea-8212-be7a8ce8aeda.png)

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
@qwordy reducing display items is fine to you, right?

**Comment by qwordy** [comment]
Sounds good.

**Comment by qwordy** [comment]
I don't think this issue is resolved. And it not only happens in this command.
