### ISSUE TITLE
`az storage account create` response is invalid json

### ISSUE THREAD

**Issue by SeaDude** [Azure/azure-cli#13603]
I believe the "WARNING" message displayed at the top of the `az storage account create` response is creating invalid json. I'm not able to turn the response into a valid json object using `json.loads("\n".join(varName))` like I can with other `az cli` responses. 
Also, the message doesn't need to be displayed to me as I used the `--kind StorageV2` flag anyway.

(first few lines shown below for brevity)...
```
["WARNING: The default kind for created storage account will change to 'StorageV2' from 'Storage' in the future",
 '{',
 '  "accessTier": "Cool",',
 '  "azureFilesIdentityBasedAuthentication": null,',
 '  "creationTime": "2020-05-21T05:28:13.115847+00:00",',
 '  "customDomain": null,',...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92115d19-d7a0-93a8-bf2b-5126d1cddcd0
* Version Independent ID: a657f09b-e1ac-12a2-4b9c-7aaa1f0e3f5c
* Content: [az storage account](https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az-storage-account-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S171

**Comment by SeaDude** [comment]
Same issue with the command: `az functionapp create --consumption-plan-location westus --name $af_name --os-type Linux --resource-group $rg_name --runtime python --storage-account $sa_name --disable-app-insights true`
I opened a StackOverflow issue [here](https://stackoverflow.com/questions/61906062/python-variable-appears-to-be-json-but-with-quotes-throughout) for advice/help.

**Comment by SeaDude** [comment]
Curious if there is any update on this.

**Comment by Juliehzl** [comment]
Hi @SeaDude, the warning information in `az storage account create` is already removed in latest azure cli version. You can have a try with latest azure cli.

To block all warning information, you can add `--only-show-errors` in you commands.
