### ISSUE TITLE
No module named '_cffi_backend'

### ISSUE THREAD

**Issue by praveen-pk** [Azure/azure-cli#13612]
## Describe the bug

**Command Name**
`az storage container create`

**Errors:**
```
No module named '_cffi_backend'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
storage/v2018_11_09/blob/_encryption.py, ln 13, in <module>
    from cryptography.hazmat.primitives.padding import PKCS7
cryptography/hazmat/primitives/padding.py, ln 13, in <module>
    from cryptography.hazmat.bindings._padding import lib
ModuleNotFoundError: No module named '_cffi_backend'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container create --account-name {} --account-key {} --name {}`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-fedora-31-Generic
Python 3.7.6

azure-cli 2.1.0 *

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
@praveen-pk May I know how you install azure cli?
If you are using `pip install`, could you try `python3 -m pip install cffi` to resolve the issue?

**Comment by praveen-pk** [comment]
I ran into this issue while using an older version of fedoraremix WSL Image. I reset my WSL environment recently and cannot reproduce the issue anymore. If this issue is not reproducible, please feel free to resolve it.

**Comment by ElvenSpellmaker** [comment]
> I ran into this issue while using an older version of fedoraremix WSL Image. I reset my WSL environment recently and cannot reproduce the issue anymore. If this issue is not reproducible, please feel free to resolve it.
I have the same issue, but resetting really wasn't an option for me. The problem for me is that the `azure-cli` from `dnf` uses the stripped down python3.6 and installing `pip` manually for this version and then `python3.6 -m pip install cffi` didn't work for me.

The solution for me was to uninstall the `azure-cli` package, and then use the main install of python 3.8 to install azure cli:
```
dnf uninstall azure-cli
pip install azure-cli
hash -r
```

**Comment by leonheess** [comment]
I can reproduce this consistently on fedoraremix WSL2 and could also fix this issue with @ElvenSpellmaker s tip. Please fix the underlying issue tho since this is a workaround at best.
