### ISSUE TITLE
Error running the cool new Azure CLI in the Azure Cloud Shell in the new Terminal

### ISSUE THREAD

**Issue by john-loughlin** [Azure/azure-cli#13615]
## Describe the bug

**Command Name**
`az cosmosdb list`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cosmosdb list`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1 *

```

**Comment by john-loughlin** [comment]
I signed into the Azure Portal, opened an Azure Cloud Shell and ran az cosmosdb list there and got the correct response, if that helps

**Comment by yonzhan** [comment]
cosmosdb

**Comment by shurd** [comment]
@yonzhan I do not think this issue is related to Cosmos DB. The error they are seeing is "400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token", which appears to be a CLI authentication problem.

**Comment by jiasli** [comment]
This is a known issue of Cloud Shell https://github.com/Azure/azure-cli/issues/11749. Please see the workaround at https://github.com/Azure/azure-cli/issues/11749#issuecomment-570975762.
