### ISSUE TITLE
ThreatIntel Whitelist on Firewall Policy

### ISSUE THREAD

**Issue by saisujithreddym** [Azure/azure-cli#13628]
**Is your feature request related to a problem? Please describe.**
This is a new feature request. We are trying to replicate the threatintelwhitelist in firewall(https://github.com/Azure/azure-cli/issues/11647) in the firewall policy.

**Describe the solution you'd like**
We should be able to send a threatintel whitelist object to the policy and this should have a list of ipaddresses and fqdns. This would be a property on the firewall policy like threatintel mode.

**Describe alternatives you've considered**
There are not alternatives as this is a requirement by design

**Additional context**
Swagger changes for reference: https://github.com/Azure/azure-rest-api-specs/pull/9224/files

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172
