### ISSUE TITLE
Problem with creating event subscription using the quickstart guide

### ISSUE THREAD

**Issue by suterma** [Azure/azure-cli#13624]
## Describe the bug

I am working through the "Quickstart: Route custom events to web endpoint with Azure CLI and Event Grid" example at https://docs.microsoft.com/en-us/azure/event-grid/custom-event-quickstart#code-try-5 and got stuck here: 

az eventgrid event-subscription create \
  --source-resource-id "/subscriptions/{subscription-id}/resourceGroups/{resource-group}/providers/Microsoft.EventGrid/topics/$topicname" \
  --name demoViewerSub \
  --endpoint $endpoint

I am really not sure what the issues is, since I am only learning, but maybe one of the engineers might test the quickstart guide through.

**Command Name**
`az eventgrid event-subscription create`

**Errors:**
```
'subscription-id'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 688, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrest/service_client.py, ln 108, in _request
    request = ClientRequest(method, self.format_url(url))
python3.6/site-packages/msrest/service_client.py, ln 151, in format_url
    url = url.format(**kwargs)
KeyError: 'subscription-id'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az eventgrid event-subscription create --source-resource-id {} --name {} --endpoint {}`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1 *

```

**Comment by yonzhan** [comment]
eventgrid

**Comment by suterma** [comment]
Thanks for looking into this. I managed to create the subscription in the Azure Web interface, so this seems to be more of a problem with the guide's CLI commands (or my interpretation of them), not with the the Event Grid itself.

**Comment by ahamad-MS** [comment]
Hello @suterma . Thanks for reporting this issue. If you are using { } as part of the command while they are meant to be placeholders for the values for subscription Id, resource group, etc.

the source-resource-Id represents the ARM Id for the topic on which the event subscription is created. For example, let us assume that you want to create an event subscription on a custom topic that is (already created) in 

- Azure Subscription: 1380c0bd-8cc0-483a-8718-5ebd2affdf87,
- Resource Group: ResourceGroupExample
- Topic Name: TopicExample
- endpoint https://www.example.com/index
The command will look like: 

az eventgrid event-subscription create
--source-resource-id "/subscriptions/1380c0bd-8cc0-483a-8718-5ebd2affdf87/resourceGroups/ResourceGroupExample/providers/Microsoft.EventGrid/topics/TopicExample" --name demoViewerSub --endpoint https://www.example.com/index


Please let us know if this resolve this issue for you and if further help is needed.

We will add work item to investigate if we can improve these help text further

thanks

**Comment by suterma** [comment]
Thanks for your input, and yes, this resolves the issue at hand. 

Unfortunately it was not clear to me that the bracketted terms must be replaced, especially because I was not aware of how to get the azure subscription id. So I assumed they might be meant literally.

Another reason is, in all the previous commands in this guide, the placeholders were expressed with $ variables.

I am closing this issue here, but I suggest for the written guide, that this particular command gets changed to use the $ style variables style too.
