### ISSUE TITLE
New naming/schema for Firewall Policy

### ISSUE THREAD

**Issue by saisujithreddym** [Azure/azure-cli#13629]
**Is your feature request related to a problem? Please describe.**
The backend schema for the firewall policy is going to change from 2020-05-01 api version. If CLI automatically updates the api version to call a new sdk everytime the sdk is updated, we need to make this change ASAP.

**Describe the solution you'd like**
**Current Scenario:**
CLI is consuming the firewall policy schema in the format of RuleGroups, Rules and RuleConditions. However it is shown to the user in the format of RuleCollectionsGroup, RuleCollections and Rule.

**Going Forward:**
The changes made to map the Rulegroups/Rule/RuleConditions -> RuleCollectionsGroup/RuleCollections/Rules on the CLI side will be moved to the backend. So we need not map this on the CLI side as backend sends the right schema of RuleCollectionsGroup/RuleCollections/Rules starting with the api version 2020-05-01. We need changes on the CLI to consume the new schema

**Describe alternatives you've considered**
We do not have an alternative as this change is already rolledout on the backend and this is a requirement 

**Additional context**
Swagger Changes for reference: https://github.com/Azure/azure-rest-api-specs/pull/9356.
Please note that the SDK is not released yet. So we will have to generate a local sdk to test the changes and use the api version 2020-05-01 when making the call to get the new schema

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172
