### ISSUE TITLE
Multiple Public IP support for Azure Firewall deployed in Virtual Hub

### ISSUE THREAD

**Issue by anchalkpr** [Azure/azure-cli#13634]
**Is your feature request related to a problem? Please describe.**
This is a new feature request. We are adding a new field HubIPAddresses through which users can specify the multiple IP addresses they would like to be attached to the firewall.

**Describe the solution you'd like**
HubIPAddresses was earlier a read-only property on Azure Firewall. With this change it will be editable, and users will be able to provide the count of public IP addresses they would like us to deploy and a list of IP addresses which will contain those addresses that were previously deployed and they would like to retain. So HubIPAddresses contains a new field fpublicIPs which has sub fields Addresses and Count through which the user can provide the 2 inputs.

**Describe alternatives you've considered**
There are not alternatives as this is a requirement by design.

**Additional context**
https://github.com/Azure/azure-rest-api-specs/pull/9560

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172

**Comment by tejasshah7** [comment]
What is the update on this?
