### ISSUE TITLE
AZ CLI for DNS Proxy in Firewall Policy

### ISSUE THREAD

**Issue by ishaniGupta27** [Azure/azure-cli#13638]
**Resource Provider**
NFVRP

**Description of Feature or Work Requested**
dnsSettings is added a new property on firewall policy.
Servers, EnableProxy,RequireProxyForNetworkRules are added as subproperties.

**Minimum API Version Required**
05-01-2020

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/9461
https://github.com/Azure/azure-rest-api-specs/pull/9609

**Target Date**
June 5

**Comment by yonzhan** [comment]
add to S171

**Comment by haroldrandom** [comment]
@ishaniGupta27 Is the feature added since API 2020-05-01? The swagger haven't got merged into master branch yet. Could you make sure the Azure:network-may-release be ready?

**Comment by ishaniGupta27** [comment]
There was a small update on above swagger Pr...

https://github.com/Azure/azure-rest-api-specs/pull/9609

In summary, we need to include fqdns to network rule in policy,
