### ISSUE TITLE
Support multiple DNAT rules in dnat rule collection - Firewall Policy

### ISSUE THREAD

**Issue by saisujithreddym** [Azure/azure-cli#13631]
**Is your feature request related to a problem? Please describe.**
We have been supporting a single DNAT rule per dnat rule collection till now. We should be supporting a list going forward

**Describe the solution you'd like**
We should remove the restriction to support a single dnat rule per collection.

Please note that translated port and translated ipaddress are just for dnat rule and not network rule. We have been reusing network rule and used translated address and translated port on top of that to create a dnat rule. This worked because we were supporting a single dnat rule per collection. 

Going forward please create a new type of rule called dnat rule and do not extend the network rule. Please create a dnat rule by copying the fields of network rule. This will facilitate multiple dnat rules per collection. Also you might be getting a future request for ipgroups support and this creation of a seperate dnat rule makes the work simple in the future,

**Describe alternatives you've considered**
No alternatives as this is a requirement for our GA

**Additional context**
This support for multiple dnat rules starts from the api version 2020-05-01. These changes should be made on top of https://github.com/Azure/azure-cli/issues/13629. The multiple dnat rules are supported with the new schema and not the old schema.

Please note that the SDK is not released yet. So we will have to generate a local sdk to test the changes and use the api version 2020-05-01 when making the call to get the new schema

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172
