### ISSUE TITLE
Azure CLI wheels includes __init__.py files that should not be there

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-cli#13635]
A given wheel should only be responsible for one file, and only one. It means no other packages should contain this file too: if two wheels contains the same file, installing them side by side will break the uninstallation scenario.

Concrete example:
- `azure/__init__.py` is owned by `azure-nspkg`, and only this wheel should contain it
- `azure/cli/__init__.py` is owned by `azure-cli-nspkg`, and only this wheel should contain it

This means the current wheel content of a package like `azure-cli` is wrong, since it contains both copy of these files.
![image](https://user-images.githubusercontent.com/1050156/82696225-763d4b80-9c1b-11ea-8c85-d1a0ec7e394b.png)

To make things worse, the copies of these files use a "pkg_resource" format that is a performance killer. See also https://github.com/Azure/azure-cli/issues/13293

CLI packages MUST NOT contains files that are owned by any nspkg (applies to azure-cli-core, etc.)

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by lmazuel** [comment]
@fengzhou-msft if you're unsure what this means in term of `setup.py` magic feel free to ping me ;)

**Comment by fengzhou-msft** [comment]
@lmazuel For `azure/__init__.py`, we should use `import pkgutil;__path__ = pkgutil.extend_path(__path__, __name__)` for development and remove the file in the package. Is that correct? How can we remove it?

**Comment by lmazuel** [comment]
That's correct. You remove those lines from your wheel using this:
https://github.com/Azure/azure-sdk-for-python/blob/7aecf6ffa4f886df25f40cc2cd2ea451dfea7e08/sdk/storage/azure-mgmt-storage/setup.py#L78-L80

See also:
https://github.com/Azure/azure-sdk-for-python/blob/master/doc/dev/packaging.md

**Comment by arrownj** [comment]
Hi @lmazuel , as CLI does not support python 2 anymore. So we think we can remove the __init__.py in both dev and whl environment. Is that right ?

**Comment by lmazuel** [comment]
@arrownj 
- it should not be in the wheel ever, whatever py2 or py3
- sdist is more interesting, I'm not sure it matters anymore that much if you target just py3 (keep it or leave it, same). Most of all the complex easy-install/dev install/etc. scenarios are gone. If you remove it you should be fine.
