### ISSUE TITLE
Missing antlr4, Antlr4 failure whenever running an az vm * command.  Stock install of CLI on WSL 

### ISSUE THREAD

**Issue by caeswor** [Azure/azure-cli#13633]
## Describe the bug

**Command Name**
`az vm create`

**Errors:**
```
No module named 'antlr4'
Traceback (most recent call last):
lib/python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
dist-packages/azure/cli/core/__init__.py, ln 300, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
azure/cli/command_modules/vm/__init__.py, ln 31, in load_arguments
    from azure.cli.command_modules.vm._params import load_arguments
azure/cli/command_modules/vm/_params.py, ln 31, in <module>
    from azure.cli.command_modules.monitor.actions import get_period_type
azure/cli/command_modules/monitor/actions.py, ln 7, in <module>
    import antlr4
ModuleNotFoundError: No module named 'antlr4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm create -n {} -g {} --public-ip-address-dns-name {} --image {} --data-disk-sizes-gb {} {} --size {} --generate-ssh-keys`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by qwordy** [comment]
Could you please upgrade to latest version and try again? 2.0.81 is old.

**Comment by qwordy** [comment]
Or try `sudo pip3 install antlr4-python3-runtime`

**Comment by qwordy** [comment]
Are you using the bundled Azure CLI of Ubuntu? The package is old and has some problems. Could you install the latest version and retry?
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

**Comment by qwordy** [comment]
Any update?
