### ISSUE TITLE
Can both service principle and azure ad both can be set on cluster ?

### ISSUE THREAD

**Issue by mohanrao** [Azure/azure-cli#13636]
Can both service principle and azure ad both can be set on cluster ? If so how the service principle should be logged in with az aks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-update-credentials)
* Content Source: [src/azure-cli/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
aks

**Comment by djsly** [comment]
@mohanrao could you share the exact flags you are interested in using at the same time ?

**Comment by seanmck** [comment]
Yes, if you create an AKS cluster with managed AAD, you can login via either SP or managed identity, using kubelogin:

https://docs.microsoft.com/en-us/azure/aks/managed-aad
https://github.com/Azure/kubelogin
