### ISSUE TITLE
keyvault secret set

### ISSUE THREAD

**Issue by acworkma** [Azure/azure-cli#13648]
## Describe the bug

**Command Name**
`az keyvault secret set`

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
<frozen importlib._bootstrap>, ln 961, in _find_and_load_unlocked
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault secret set --name {} --vault-name {} --value {}`

## Environment Summary
```
Linux-5.4.0-31-generic-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by yungezz** [comment]
hi @bim-msft same issues reported several times, is there anything we could to avoid it?

**Comment by bim-msft** [comment]
@yungezz Hi, the root cause for this has still not been found yet. It seems the data-plane SDK `azure-keyvault` was upgraded from `1.1.0` to `4.x` incorrectly (see another case #13507 ). 
Some clues:
1. Most of afftected version is `2.0.81`
2. Most of afftected OS is `Linux-5.4.0-29-generic-x86_64-with-glibc2.29`

This might be an OS side issue instead of CLI side, anyway, will follow up this.

**Comment by bim-msft** [comment]
Hi @acworkma You can try to upgrade your Azure CLI version to latest to avoid this issue. Another way to resolve it is using `azure-keyvault==1.1.0`. Please let me know if these 2 ways don't workaround you.

**Comment by bim-msft** [comment]
Closing due to longtime inactivity. If anything needs us to help with, feel free to reopen it, thanks.

**Comment by jiasli** [comment]
Duplicate of #13101. To fix it, please see https://github.com/Azure/azure-cli/issues/19640#issuecomment-924578571.
