### ISSUE TITLE
Webapp:Missing details on ` --number-of-workers`

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-cli#13641]
Where can I find documentation on what workers do and recommended workers to use?  Best practices also would be useful?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e50d77a-f2fa-6d6e-0c57-2f434c12766f
* Version Independent ID: f9a98805-6e16-487a-03ce-237cb964f83c
* Content: [az webapp config](https://docs.microsoft.com/en-us/cli/azure/webapp/config?view=azure-cli-latest&source=docs)
* Content Source: [latest/docs-ref-autogen/webapp/config.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by awentzel** [comment]
@yonzhan is this your answer or a triage label?

**Comment by yonzhan** [comment]
webapp service team will take a look at this.

**Comment by panchagnula** [comment]
this is not CLI specific question @btardif  do we have any help documentation we reference in this issue?

**Comment by btardif** [comment]
@awentzel Workers are the unit of scale for an app. you can learn more about scale out here --> https://docs.microsoft.com/en-us/azure/app-service/manage-scale-up

**Comment by pylgrym** [comment]
Interestingly, when following the link mentioned in the "closed-as-completed" comment,
that page references neither number-of-workers neither the word "workers" at all.
  When trying to google what "number-of-workers" is about,
among the top listed but not really helpful search results, this discussion ranks as #9.
