### ISSUE TITLE
Webapp:Where is ARR Affinity

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-cli#13640]
I can't seem to find how to control ARR affinity using the Azure CLI for `az webapp`s .

I'm running Linux and don't see the point of having this at all, certainly, it should be defaulted to false.

So now I have 24 apps across multiple regions behind Front Door with no ability to automate changing this setting. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-update)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
Please use az webapp update -set (see examples) to update any value in the site object https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-update
