### ISSUE TITLE
webapp: Unable to create App Service Plan in a different resource group to App Service Environment

### ISSUE THREAD

**Issue by danbyrne** [Azure/azure-cli#13646]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
As per the documentation, only one resource group can be specified, and it seems that this is expecting to be both the resource group to find the App Service Environment as well as the App Service Plan. However in our implementation they are generally in different groups.

**To Reproduce**
az appservice plan create -g ResourceGroup1 -n ServicePlanName  --app-service-environment AppServiceEnvironmentName --sku I1 
(noting that my expectation is that ResourceGroup1 is where I want the serviceplan to go, not where the AppServiceEnvironment is located)

The result/error is: 
App service environment '/subscriptions/xxx/resourceGroups/ResourceGroup1/providers/Microsoft.Web/hostingEnvironments/AppServiceEnvironmentName' not found in subscription.

**Expected behavior**
I would expect aligned behaviour as per the AzureRM (https://docs.microsoft.com/en-us/powershell/module/azurerm.websites/new-azurermappserviceplan?view=azurermps-6.13.0) with a parameter 'AseResourceGroupName' that defines how to locate the App Service Environment (if specified), and the 'ResourceGroupName' is used only for the App Service in this scenario.

**Environment summary**
Using windows based CLI

**Additional context**

**Comment by yonzhan** [comment]
appservice

**Comment by panchagnula** [comment]
@Kotasudhakarreddy / @ThejaChoudary  can you check if we can pass ResourceGroup ID instead of RG Name here to fix this?

**Comment by SamirBanjanovic** [comment]
Has this issue been addressed? I am currently facing this exact error when attempting to create run `az appservice plan create` where the app service is under a different RG than the ASE

**Comment by Kotasudhakarreddy** [comment]
@SamirBanjanovic - yes it has been addressed and working fine in with latest versions of CLI. Please update your CLI version to `2.19.1`. If you still face the issue please share the `-debug` log for your command.
