### ISSUE TITLE
Failure Attempting to create AppServicePlan

### ISSUE THREAD

**Issue by Rich-Lang** [Azure/azure-cli#13644]
## Describe the bug

**Command Name**
`az appservice plan create`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan create --name {} --resource-group {} --sku {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
appservice

**Comment by Rich-Lang** [comment]
Was able to work around using: https://github.com/Azure/azure-cli/issues/13343#issuecomment-624367680

This was a fresh install of WSL, Ubuntu, AZ CLI, everything

**Comment by yungezz** [comment]
could you pls share your previous install story to help trouble shooting? thanks

**Comment by panchagnula** [comment]
@Rich-Lang only common package I see included b/w the 2 githhub issues is the azdevops extension can you try uninstalling that extension & trying & also question above on how the original install was done?

**Comment by Rich-Lang** [comment]
I just reproduced the issue on a fresh Azure VM.
1) Created Azure VM with Image = "Windows 10 Pro, Version 1809"
2) RDP into box
3) PS Admin Prompt: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
4) Reboot & RDP again
5) Install Ubuntu from store (https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?ocid=9nblggh4msv6_ORSEARCH_Bing&rtc=1&activetab=pivot:overviewtab)
6) From Ubuntu command prompt: sudo apt update
7) sudo apt install azure-cli
8) az appservice plan create --name myAppServicePlan --resource-group SQLAzureDotNetCoreDev --sku FREE

**Comment by fengzhou-msft** [comment]
@Rich-Lang please install azure-cli following the instructions:https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

The azure cli comes with the WSL is an old version and not tested by our team. We publish packages to https://packages.microsoft.com/repos/azure-cli. Please install and update from there.
