### ISSUE TITLE
[Packaging] Create release pipeline for beta versions

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#13654]
We need to come up with a release pipeline/procedure for beta versions. Currently the need is for Azure Identity Adoption.

**Comment by yonzhan** [comment]
release pipeline

**Comment by jiasli** [comment]
The pipeline is created at https://dev.azure.com/azure-sdk/internal/_release?view=mine&_a=releases&definitionId=94

The script used: https://github.com/jiasli/az-publish
