### ISSUE TITLE
Missing Azure CLI package registry on Ubuntu 20.04 LTS 

### ISSUE THREAD

**Issue by sithukyaw007** [Azure/azure-cli#13656]
Hello Azure CLI team,

I install Azure CLI on On Ubuntu 20.04 LTS following this [official link](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#manual-install-instructions). 

After Step 3, when I run `sudo apt-get update`, I found this error

`https://packages.microsoft.com/repos/azure-cli focal Release` 
`404  Not Found [IP: <IP_Address_Here> 443]`

`E: The repository 'https://packages.microsoft.com/repos/azure-cli focal Release' does not have a Release file.`
`N: Updating from such a repository can't be done securely, and is therefore disabled by default.`

Is it because Azure CLI repository has not supported yet for Ubuntu 20.04 LTS? 

Thank you.

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by yungezz** [comment]
we're working on supporting it.

**Comment by sithukyaw007** [comment]
Thank you team.

**Comment by fengzhou-msft** [comment]
Focal package released for azure-cli 2.6.0. Please try again.

**Comment by sithukyaw007** [comment]
It has been fixed now. Thank you.
