### ISSUE TITLE
using azure cli i'm able to create duplicate cdn profiles

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-cli#13652]
when running `az cdn profile create` multiple times with the same values i get a successful completion. however, it's already been created and i still get successful completion.  Usually with other commands I get a red message that it already exists.

This is throwing me off a bit. Could we add clarity or perform consistent messaging with other commands?

When running the following command Azure CLI returns name available true, yet how can the name be available if I just successfully created it in my prior step.

```bash
$ az cdn name-exists --name some-static
{
  "message": null,
  "nameAvailable": true,
  "reason": null
}
```
very confusing. Furthermore, I seem to always get the  same result no matter what I try.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e2b3b2-3e26-a47f-ee80-5bd5c3b065c4
* Version Independent ID: 72ef6ca0-b8f6-4952-732d-34aefa414bb6
* Content: [az cdn endpoint](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint?view=azure-cli-latest#az-cdn-endpoint-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/cdn/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cdn/_help.py)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cdn
