### ISSUE TITLE
what are the requirements to set --origin-path

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-cli#13650]
When attempting to set `--origin-path` using Azure CLI with `az cdn endpoint create` I'm getting the following error.  But, nowhere documentation say what is required for this to succeed.  For example, does it perform a DNS lookup and if nonexistent respond with this error?

```
BadRequest - Property 'Endpoint.OriginPath' cannot be set to 'static.fast.design/assets'. 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e2b3b2-3e26-a47f-ee80-5bd5c3b065c4
* Version Independent ID: 72ef6ca0-b8f6-4952-732d-34aefa414bb6
* Content: [az cdn endpoint](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint?view=azure-cli-latest#az-cdn-endpoint-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/cdn/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cdn/_help.py)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cdn

**Comment by nachakra** [comment]
Origin path should meet the following requirement - should start with / and only contain letters, numbers and following characters: - . / _
