### ISSUE TITLE
az: error: unrecognized arguments: --only-show-errors for "az storage" commands

### ISSUE THREAD

**Issue by vllama** [Azure/azure-cli#13667]
running the following command
-`az storage account list --only-show-errors --resource-group $resourceGroup --query '[0].{name: name}'`

Produces the following error:
>az: error: unrecognized arguments: --only-show-errors
>usage: az [-h] [--verbose] [--debug]
>          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
>          {storage} ...

**Command Name**
`az storage account list`

**Errors:**
```
az: error: unrecognized arguments: --only-show-errors
```

## To Reproduce:
- `az storage account list --only-show-errors --resource-group {} --query {}`

## Expected Behavior
As per the documentation [here](https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az-storage-account-create) on Global Parameters, it should suppress warnings.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.81 *

Extensions:
application-insights 0.1.3

```

**Comment by yonzhan** [comment]
add to S170

**Comment by Juliehzl** [comment]
@vllama  You need to upgrade aszure cli version for the new parameter.

**Comment by vllama** [comment]
Great. That has fixed it.
