### ISSUE TITLE
Support for the `Microsoft.CostManagement/query` API

### ISSUE THREAD

**Issue by florianrusch** [Azure/azure-cli#13664]
**Is your feature request related to a problem? Please describe.**
I would like to query our azure costs via the `az` cli, to bring them in our own on-premise monitoring system. To do this I need to group and filter them, which is not immediately possible with the `az consumption` command.

**Describe the solution you'd like**
The Azure API `.../Microsoft.CostManagement/query` (https://docs.microsoft.com/en-us/rest/api/cost-management/query/usage) allows to send a json object with filters, groups etc. and returns the costs based on this. It would be great if the `az` cli would wrap this endpoint.

**Describe alternatives you've considered**
- Use the REST API directly via any http client.
- Use `az rest` as a wrapper

Both alternatives would mean that I would have to take care of the API Definition (mainly the url/path) and the authentication (just on the first point), which is not so nice.

**Comment by yonzhan** [comment]
add to S171

**Comment by haroldrandom** [comment]
Hi, https://github.com/Azure/azure-cli-extensions/pull/1729, https://github.com/Azure/azure-cli/issues/12912 we are going to onboard it here. 
It will be release before June.

The CLI plan is going to lose weight, which is going to make most of commands an extension. 
So, we are not going to put it on the Azure CLI.

But still thanks for your suggestion!

**Comment by florianrusch** [comment]
@haroldrandom Thanks a lot! Then this issue can be closed, right?

**Comment by haroldrandom** [comment]
costmanagement commands is released. You could install it and have a try via `az extension add -n costmanagement`
