### ISSUE TITLE
az cli fails with ModuleNotFoundError

### ISSUE THREAD

**Issue by cuzzlor** [Azure/azure-cli#13660]
## Describe the bug

**Command Name**
`az webapp create`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Install Ubuntu 20.4 LTS on Windows WSL
- Install az cli following these steps: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#set-release
- `az login`
- `az webapp create --name --resource-group --plan --runtime {}`

## Expected Behavior
`az` commands work

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
No related to app service - see https://github.com/Azure/azure-cli/issues/13644

**Comment by cuzzlor** [comment]
I read all that at the time, I still couldn’t make it work on a fresh install following all the instructions. Care to elaborate? Someone else’s job?

**Comment by yonzhan** [comment]
@fengzhou-msft could you help with this?

**Comment by fengzhou-msft** [comment]
@cuzzlor you need to first remove the packages installed by the old 2.0.81 azure-cli that comes with the Ubuntu 20.4 LTS. Try `sudo apt remove azure-cli` and make sure `/usr/lib/python3/dist-packages/azure` is deleted.

**Comment by cuzzlor** [comment]
Ok. At the time it was a brand new install of WSL and the azure cli install script. I’ll try again maybe something has changed. Thanks.

**Comment by fengzhou-msft** [comment]
You may need to run `sudo apt autoremove` after `sudo apt remove azure-cli` to remove the old azure packages that `azure-cli 2.0.81` depends on.

**Comment by fengzhou-msft** [comment]
Duplicate with #14011
