### ISSUE TITLE
CLI returns success before operation completes

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-cli#13678]
In my CLI I'm running `az cdn endpoint create` immediately after `az cdn profile create` which returns success.  However, the endpoint hasn't completely been setup and so when creating customer domain it fails with:

```
BadRequest - The requested operation cannot be executed on the entity in the current state.
```
I believe the endpoint creation returns too soon and should await for a success response or perform validation that it's been created via show/list before returning success to CLI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e2b3b2-3e26-a47f-ee80-5bd5c3b065c4
* Version Independent ID: 72ef6ca0-b8f6-4952-732d-34aefa414bb6
* Content: [az cdn endpoint](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint?view=azure-cli-latest#az-cdn-endpoint-show)
* Content Source: [src/azure-cli/azure/cli/command_modules/cdn/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cdn/_help.py)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by awentzel** [comment]
Could you provide an update please?

**Comment by yonzhan** [comment]
CDN service team should look into this issue.

**Comment by t-bzhan** [comment]
If the `--no-wait` flag is not used, `az cdn endpoint create` will only return when the underlying endpoint has been created successfully or has failed. The endpoint creation is asynchronous, but CLI will poll the operation status. You can verify this in the debug output of the command. I have tried multiple times to reproduce the issue but have been unsuccessful. Therefore, I will close the issue for now. Please reactivate it with more diagnostic information if it still occurs. We can check our backend log to investigate further.

> PS D:\diag> az cdn endpoint create -g boprivate -n testendpoint01 --profile-name verizon-standard-test --origin ccihteststorage1.blob.core.chinacloudapi.cn --debug
> cli.knack.cli: Command arguments: ['cdn', 'endpoint', 'create', '-g', 'boprivate', '-n', 'testendpoint01', '--profile-name', 'verizon-standard-test', '--origin', 'ccihteststorage1.blob.core.chinacloudapi.cn', '--debug']
> cli.knack.cli: __init__ debug log:
> Enable color in terminal.
> Enable VT mode.
> cli.knack.cli: Event: Cli.PreExecute []
> cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0325B6A0>, <function OutputProducer.on_global_arguments at 0x0345C8E0>, <function CLIQuery.on_global_arguments at 0x03472538>]
> cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
> cli.azure.cli.core: Modules found from index for 'cdn': ['azure.cli.command_modules.cdn']
> cli.azure.cli.core: Loading command modules:
> cli.azure.cli.core: Name                  Load Time    Groups  Commands
> cli.azure.cli.core: cdn                       0.010        39       133
> cli.azure.cli.core: Total (1)                 0.010        39       133
> cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
> cli.azure.cli.core: Loading extensions:
> cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
> cli.azure.cli.core: Total (0)                 0.000         0         0
> cli.azure.cli.core: Loaded 39 groups, 133 commands.
> cli.azure.cli.core: Found a match in the command table.
> cli.azure.cli.core: Raw command  : cdn endpoint create
> cli.azure.cli.core: Command table: cdn endpoint create
> cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03F00658>]
> cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\bzhan\.azure\commands\2023-09-04.11-40-02.cdn_endpoint_create.52796.log'.
> az_command_data_logger: command args: cdn endpoint create -g {} -n {} --profile-name {} --origin {} --debug
> cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03F6AD60>]
> cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
> cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03F6ADF0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03F6AE80>]
> cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
> cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
> cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0345C928>, <function CLIQuery.handle_query_parameter at 0x03472580>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03F6AE38>]
> cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
> cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\bzhan\\.azure\\msal_token_cache.bin', encrypt=True
> cli.azure.cli.core.auth.binary_cache: load: C:\Users\bzhan\.azure\msal_http_cache.bin
> urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
> msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
> msal.application: Broker enabled? False
> cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
> cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
> msal.application: Cache hit an AT
> msal.telemetry: Generate or reuse correlation_id: 9344c2e3-0b88-4d29-8e39-fdf17934a9b2
> cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourcegroups/boprivate?api-version=2022-09-01' cli.azure.cli.core.sdk.policies: Request method: 'GET'
> cli.azure.cli.core.sdk.policies: Request headers:
> cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
> cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'bb1bb927-4ad4-11ee-8c29-c8d9d2133ae1'
> cli.azure.cli.core.sdk.policies:     'CommandName': 'cdn endpoint create'
> cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --profile-name --origin --debug'
> cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.50.0 (MSI) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
> cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
> cli.azure.cli.core.sdk.policies: Request body:
> cli.azure.cli.core.sdk.policies: This request has no body
> urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
> urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourcegroups/boprivate?api-version=2022-09-01 HTTP/1.1" 200 280
> cli.azure.cli.core.sdk.policies: Response status: 200
> cli.azure.cli.core.sdk.policies: Response headers:
> cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
> cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
> cli.azure.cli.core.sdk.policies:     'Expires': '-1'
> cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
> cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
> cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'd75858ad-b1de-4fcc-8067-ec913ff87afa'
> cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'd75858ad-b1de-4fcc-8067-ec913ff87afa'
> cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20230904T034003Z:d75858ad-b1de-4fcc-8067-ec913ff87afa'
> cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
> cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
> cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 04 Sep 2023 03:40:03 GMT'
> cli.azure.cli.core.sdk.policies:     'Content-Length': '280'
> cli.azure.cli.core.sdk.policies: Response content:
> cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourceGroups/boprivate","name":"boprivate","type":"Microsoft.Resources/resourceGroups","location":"eastasia","properties":{"provisioningState":"Succeeded"}}
> cli.azure.cli.core.commands.validators: using location 'eastasia' from resource group 'boprivate'
> cli.azure.cli.core.commands.client_factory: Getting management service client client_type=CdnManagementClient
> urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
> msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
> msal.application: Broker enabled? False
> cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
> cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
> msal.application: Cache hit an AT
> msal.telemetry: Generate or reuse correlation_id: 815be973-288f-49ff-815b-fdc1b1d1684a
> cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourceGroups/boprivate/providers/Microsoft.Cdn/profiles/verizon-standard-test/endpoints/testendpoint01?api-version=2021-06-01'
> cli.azure.cli.core.sdk.policies: Request method: 'PUT'
> cli.azure.cli.core.sdk.policies: Request headers:
> cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
> cli.azure.cli.core.sdk.policies:     'Content-Length': '262'
> cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
> cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'bb1bb927-4ad4-11ee-8c29-c8d9d2133ae1'
> cli.azure.cli.core.sdk.policies:     'CommandName': 'cdn endpoint create'
> cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --profile-name --origin --debug'
> cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.50.0 (MSI) azsdk-python-mgmt-cdn/12.0.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
> cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
> cli.azure.cli.core.sdk.policies: Request body:
> cli.azure.cli.core.sdk.policies: {"location": "eastasia", "properties": {"isCompressionEnabled": false, "isHttpAllowed": true, "isHttpsAllowed": true, "origins": [{"name": "origin-0", "properties": {"hostName": "ccihteststorage1.blob.core.chinacloudapi.cn", "httpPort": 80, "httpsPort": 443}}]}}
> urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
> urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourceGroups/boprivate/providers/Microsoft.Cdn/profiles/verizon-standard-test/endpoints/testendpoint01?api-version=2021-06-01 HTTP/1.1" 201 1119
> cli.azure.cli.core.sdk.policies: Response status: 201
> cli.azure.cli.core.sdk.policies: Response headers:
> cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Content-Length': '1119'
> cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
> cli.azure.cli.core.sdk.policies:     'Expires': '-1'
> cli.azure.cli.core.sdk.policies:     'Retry-After': '10'
> cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
> cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '0eaa0e4d-3b10-4497-8108-45d4185d138b'
> cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'bb1bb927-4ad4-11ee-8c29-c8d9d2133ae1'
> cli.azure.cli.core.sdk.policies:     'Azure-AsyncOperation': 'https://management.azure.com/subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourcegroups/boprivate/providers/Microsoft.Cdn/operationresults/08647a7d-9545-4283-8a87-46cf1b29c477?api-version=2021-06-01'
> cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
> cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-resource-requests': '399'
> cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'a72501ad-aa2d-405c-a82e-84b16d96c072'
> cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20230904T034011Z:a72501ad-aa2d-405c-a82e-84b16d96c072'
> cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
> cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 04 Sep 2023 03:40:10 GMT'
> cli.azure.cli.core.sdk.policies: Response content:
> cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourcegroups/boprivate/providers/Microsoft.Cdn/profiles/verizon-standard-test/endpoints/testendpoint01","type":"Microsoft.Cdn/profiles/endpoints","name":"testendpoint01","location":"EastAsia","tags":{},"properties":{"hostName":"testendpoint01.azureedge.net","originHostHeader":null,"originPath":null,"contentTypesToCompress":[],"isCompressionEnabled":false,"isHttpAllowed":true,"isHttpsAllowed":true,"queryStringCachingBehavior":"IgnoreQueryString","optimizationType":null,"probePath":null,"origins":[{"name":"origin-0","properties":{"hostName":"ccihteststorage1.blob.core.chinacloudapi.cn","httpPort":80,"httpsPort":443,"originHostHeader":null,"priority":null,"weight":null,"enabled":true,"privateLinkAlias":null,"privateLinkResourceId":null,"privateLinkLocation":null,"privateEndpointStatus":null,"privateLinkApprovalMessage":null}}],"originGroups":[],"defaultOriginGroup":null,"customDomains":[],"geoFilters":[],"deliveryPolicy":null,"urlSigningKeys":null,"webApplicationFirewallPolicyLink":null,"resourceState":"Creating","provisioningState":"Creating"}}
> cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourcegroups/boprivate/providers/Microsoft.Cdn/operationresults/08647a7d-9545-4283-8a87-46cf1b29c477?api-version=2021-06-01'
> cli.azure.cli.core.sdk.policies: Request method: 'GET'
> cli.azure.cli.core.sdk.policies: Request headers:
> cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'bb1bb927-4ad4-11ee-8c29-c8d9d2133ae1'
> cli.azure.cli.core.sdk.policies:     'CommandName': 'cdn endpoint create'
> cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --profile-name --origin --debug'
> cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.50.0 (MSI) azsdk-python-mgmt-cdn/12.0.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
> cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
> cli.azure.cli.core.sdk.policies: Request body:
> cli.azure.cli.core.sdk.policies: This request has no body
> urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourcegroups/boprivate/providers/Microsoft.Cdn/operationresults/08647a7d-9545-4283-8a87-46cf1b29c477?api-version=2021-06-01 HTTP/1.1" 200 None
> cli.azure.cli.core.sdk.policies: Response status: 200
> cli.azure.cli.core.sdk.policies: Response headers:
> cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
> cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
> cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
> cli.azure.cli.core.sdk.policies:     'Expires': '-1'
> cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
> cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
> cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '6238f731-d5cc-4234-bb03-5244ac9263a9'
> cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'bb1bb927-4ad4-11ee-8c29-c8d9d2133ae1'
> cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
> cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
> cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '8f86963d-2801-49b9-90fc-6b0326f2737b'
> cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20230904T034011Z:8f86963d-2801-49b9-90fc-6b0326f2737b'
> cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
> cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 04 Sep 2023 03:40:10 GMT'
> cli.azure.cli.core.sdk.policies: Response content:
> cli.azure.cli.core.sdk.policies: {"status":"InProgress","error":{"code":"None","message":null}}
> cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourcegroups/boprivate/providers/Microsoft.Cdn/operationresults/08647a7d-9545-4283-8a87-46cf1b29c477?api-version=2021-06-01'
> cli.azure.cli.core.sdk.policies: Request method: 'GET'
> cli.azure.cli.core.sdk.policies: Request headers:
> cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'bb1bb927-4ad4-11ee-8c29-c8d9d2133ae1'
> cli.azure.cli.core.sdk.policies:     'CommandName': 'cdn endpoint create'
> cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --profile-name --origin --debug'
> cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.50.0 (MSI) azsdk-python-mgmt-cdn/12.0.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
> cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
> cli.azure.cli.core.sdk.policies: Request body:
> cli.azure.cli.core.sdk.policies: This request has no body
> urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourcegroups/boprivate/providers/Microsoft.Cdn/operationresults/08647a7d-9545-4283-8a87-46cf1b29c477?api-version=2021-06-01 HTTP/1.1" 200 None
> cli.azure.cli.core.sdk.policies: Response status: 200
> cli.azure.cli.core.sdk.policies: Response headers:
> cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
> cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
> cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
> cli.azure.cli.core.sdk.policies:     'Expires': '-1'
> cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
> cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
> cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'ddedf16e-c47c-4cf6-9664-b8c100d784b5'
> cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'bb1bb927-4ad4-11ee-8c29-c8d9d2133ae1'
> cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
> cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11998'
> cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '92ac1f94-aa46-45dd-8391-8f5eecf765e2'
> cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20230904T034041Z:92ac1f94-aa46-45dd-8391-8f5eecf765e2'
> cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
> cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 04 Sep 2023 03:40:41 GMT'
> cli.azure.cli.core.sdk.policies: Response content:
> cli.azure.cli.core.sdk.policies: {"status":"Succeeded","error":{"code":"None","message":null}}
> cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourceGroups/boprivate/providers/Microsoft.Cdn/profiles/verizon-standard-test/endpoints/testendpoint01?api-version=2021-06-01'
> cli.azure.cli.core.sdk.policies: Request method: 'GET'
> cli.azure.cli.core.sdk.policies: Request headers:
> cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'bb1bb927-4ad4-11ee-8c29-c8d9d2133ae1'
> cli.azure.cli.core.sdk.policies:     'CommandName': 'cdn endpoint create'
> cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --profile-name --origin --debug'
> cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.50.0 (MSI) azsdk-python-mgmt-cdn/12.0.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
> cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
> cli.azure.cli.core.sdk.policies: Request body:
> cli.azure.cli.core.sdk.policies: This request has no body
> urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourceGroups/boprivate/providers/Microsoft.Cdn/profiles/verizon-standard-test/endpoints/testendpoint01?api-version=2021-06-01 HTTP/1.1" 200 None
> cli.azure.cli.core.sdk.policies: Response status: 200
> cli.azure.cli.core.sdk.policies: Response headers:
> cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
> cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
> cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
> cli.azure.cli.core.sdk.policies:     'Expires': '-1'
> cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
> cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
> cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '9c596993-c5be-414d-96f2-c333adea06e4'
> cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'bb1bb927-4ad4-11ee-8c29-c8d9d2133ae1'
> cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
> cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-resource-requests': '499'
> cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '2796d4af-7320-4e06-8b06-c028471a70d6'
> cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20230904T034042Z:2796d4af-7320-4e06-8b06-c028471a70d6'
> cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
> cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 04 Sep 2023 03:40:42 GMT'
> cli.azure.cli.core.sdk.policies: Response content:
> cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourcegroups/boprivate/providers/Microsoft.Cdn/profiles/verizon-standard-test/endpoints/testendpoint01","type":"Microsoft.Cdn/profiles/endpoints","name":"testendpoint01","location":"EastAsia","tags":{},"properties":{"hostName":"testendpoint01.azureedge.net","originHostHeader":null,"originPath":null,"contentTypesToCompress":[],"isCompressionEnabled":false,"isHttpAllowed":true,"isHttpsAllowed":true,"queryStringCachingBehavior":"IgnoreQueryString","optimizationType":null,"probePath":null,"origins":[{"name":"origin-0","properties":{"hostName":"ccihteststorage1.blob.core.chinacloudapi.cn","httpPort":80,"httpsPort":443,"originHostHeader":null,"priority":null,"weight":null,"enabled":true,"privateLinkAlias":null,"privateLinkResourceId":null,"privateLinkLocation":null,"privateEndpointStatus":null,"privateLinkApprovalMessage":null}}],"originGroups":[],"defaultOriginGroup":null,"customDomains":[],"geoFilters":[],"deliveryPolicy":null,"urlSigningKeys":null,"webApplicationFirewallPolicyLink":null,"resourceState":"Running","provisioningState":"Succeeded"}}
> cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x03F23E80>, <function _x509_from_base64_to_hex_transform at 0x03F23EC8>]
> cli.knack.cli: Event: CommandInvoker.OnFilterResult []
> {
>   "contentTypesToCompress": [],
>   "customDomains": [],
>   "defaultOriginGroup": null,
>   "deliveryPolicy": null,
>   "geoFilters": [],
>   "hostName": "testendpoint01.azureedge.net",
>   "id": "/subscriptions/6d3165c9-640f-4e0c-be76-3ff409fc88df/resourcegroups/boprivate/providers/Microsoft.Cdn/profiles/verizon-standard-test/endpoints/testendpoint01",
>   "isCompressionEnabled": false,
>   "isHttpAllowed": true,
>   "isHttpsAllowed": true,
>   "location": "EastAsia",
>   "name": "testendpoint01",
>   "optimizationType": null,
>   "originGroups": [],
>   "originHostHeader": null,
>   "originPath": null,
>   "origins": [
>     {
>       "enabled": true,
>       "hostName": "ccihteststorage1.blob.core.chinacloudapi.cn",
>       "httpPort": 80,
>       "httpsPort": 443,
>       "name": "origin-0",
>       "originHostHeader": null,
>       "priority": null,
>       "privateEndpointStatus": null,
>       "privateLinkAlias": null,
>       "privateLinkApprovalMessage": null,
>       "privateLinkLocation": null,
>       "privateLinkResourceId": null,
>       "weight": null
>     }
>   ],
>   "probePath": null,
>   "provisioningState": "Succeeded",
>   "queryStringCachingBehavior": "IgnoreQueryString",
>   "resourceGroup": "boprivate",
>   "resourceState": "Running",
>   "systemData": null,
>   "tags": {},
>   "type": "Microsoft.Cdn/profiles/endpoints",
>   "urlSigningKeys": null,
>   "webApplicationFirewallPolicyLink": null
> }
> cli.knack.cli: Event: Cli.SuccessfulExecute []
> cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03F00778>]
> az_command_data_logger: exit code: 0
> cli.__main__: Command ran in 41.327 seconds (init: 1.129, invoke: 40.198)
> telemetry.main: Begin splitting cli events and extra events, total events: 1
> telemetry.client: Accumulated 0 events. Flush the clients.
> telemetry.main: Finish splitting cli events and extra events, cli events: 1
> telemetry.save: Save telemetry record of length 3395 in cache
> telemetry.check: Negative: The C:\Users\bzhan\.azure\telemetry.txt was modified at 2023-09-04 11:34:39.749817, which in less than 600.000000 s
