### ISSUE TITLE
an Azure CLI command to set keyvault networking to selected/private network

### ISSUE THREAD

**Issue by xiaodai7** [Azure/azure-cli#13671]
Hey guys,

I was wondering if there is a way to run a CLI command which sets the Azure Keyvault resource which has the networking option on "Allow access: from all networks" to "Allow access: from private endpoint and selected networks. See screenshot to understand which buttons I'm referring to.

![kv access](https://user-images.githubusercontent.com/21020555/82812707-e3f3ac80-9e93-11ea-85aa-a52fb72af59b.PNG)
  
I'm guessing it's a command which starts with something similar to: az keyvault network-rule add etc...

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by bim-msft** [comment]
Hi @xiaodai7 , you can use `az keyvault update --default_action Deny` to disable the public endpoint.

**Comment by xiaodai7** [comment]
> Hi @xiaodai7 , you can use `az keyvault update --default_action Deny` to disable the public endpoint.

I tried this and it works, thanks!
