### ISSUE TITLE
Webapp:az webapp deployment source config-zip

### ISSUE THREAD

**Issue by bluesapp** [Azure/azure-cli#13676]
## Describe the bug

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
[Errno 2] No such file or directory: 'C:\\Users\\user\\Downloads\\Azure\\Echo Bot v1\\code.zip'
Traceback (most recent call last):
Temp\pip-install-7cl6xofh\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 631, in execute
azure\cli\core\commands\__init__.py, ln 695, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 688, in _run_job
Local\Temp\pip-install-7cl6xofh\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 665, in _run_job
azure\cli\core\commands\__init__.py, ln 324, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 574, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 358, in enable_zip_deploy_webapp
azure\cli\command_modules\appservice\custom.py, ln 384, in enable_zip_deploy
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\Downloads\\Azure\\Echo Bot v1\\code.zip'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip -g {} -n {} --src {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1 *

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@bluesapp 2 reasons this might happen 

1. 'C:\\Users\\user\\Downloads\\Azure\\Echo Bot v1\\code.zip' doesn't exist or
2. The path contains spaces so when you pass the path as an argument make sure to close them in double quotes ""

Please let me know if you are still seeing this & we can try to help you out as much as we can. Thanks!

**Comment by yonzhan** [comment]
move to S171

**Comment by panchagnula** [comment]
Closing due to lack of response
