### ISSUE TITLE
Webapp:Deploy of the .NET Core app failed

### ISSUE THREAD

**Issue by Rinal** [Azure/azure-cli#13672]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
'NoneType' object has no attribute 'reserved'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 709, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/core/commands/__init__.py, ln 325, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 545, in default_command_handler
    return op(**command_args)
cli/command_modules/appservice/custom.py, ln 3237, in webapp_up
    current_os = 'Linux' if plan_info.reserved else 'Windows'
AttributeError: 'NoneType' object has no attribute 'reserved'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up -n {} --resource-group {}`

## Environment Summary
```
macOS-10.15.4-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.6.0

```

**Comment by yonzhan** [comment]
webapp

**Comment by Rinal** [comment]
Hi all! Additional STRs with webapp deployment:
Additional STR:
1. Run *up* command as described in the [documentation](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-up). Example:
`az webapp up -n my-webapp-name`
2. Observe result and logs.

Expected: Deployed webapp with desired .NET Core version (3.1)

Actual Result: WebApp with .NET Core version 2.2
```
"runtime_version": "dotnetcore|2.2",
 "runtime_version_detected": "3.1",
```

**Comment by panchagnula** [comment]
@calvinsID we probably need to change the defaults we use for dotnet core with az webapp up.

**Comment by calvinsID** [comment]
@Rinal can you please try with the latest CLI? I was unable to repro with v2.10.1

**Comment by Rinal** [comment]
We solved with another CLI command. Thank you!
