### ISSUE TITLE
az webapp appsettings set is case sensitive, should be case insensitive 

### ISSUE THREAD

**Issue by subir0071** [Azure/azure-cli#13673]
>  CLI version 2.6.0

**Bug Description**

Azure webapp configuration key is case-insensitive. (https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-key-value)
However, when we execute the below command:
az webapp config appsettings set -n <appService Name> -g <RG Name>  --settings KEY=Value1 we receive an error message --> Operation returned an invalid status code 'Conflict'.
This is because there is already a "key" present in the configuration.

**To Reproduce**

Execute
az webapp config appsettings set -n <appService Name> -g <RG Name>  --settings key=Value1 
az webapp config appsettings set -n <appService Name> -g <RG Name>  --settings KEY=Value2
Expected:
Both "KEY" and "key" should be present in webapp configuration with "Value1" & "Value2" respectively.
Actual:
Receiving error message --> Operation returned an invalid status code 'Conflict'

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
Application settings are basically Key , Value pairs which means the key should be unique in your example 'key' and 'KEY' are not unique. The error is coming from the API and is not CLI specific the behavior is consistent with the portal as well.
