### ISSUE TITLE
Webapp:unable to deploy botService NodeJS

### ISSUE THREAD

**Issue by manikanta-kondeti** [Azure/azure-cli#13674]
## Describe the bug

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
dlopen(/usr/local/Cellar/azure-cli/2.0.71/libexec/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/azure-cli/2.0.71/libexec/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so
  Reason: image not found
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
...
  Reason: image not found
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip --resource-group {} --name {} --src {}`

## Environment Summary
```
Darwin-17.7.0-x86_64-i386-64bit
Python 3.7.7
Shell: bash

azure-cli 2.0.71 *

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@manikanta-kondeti  can you please update to use the latest version of CLI & re-try looking at the stack trace the error is happening even before the method to do zip deployment is invoked.

**Comment by yonzhan** [comment]
move to S171

**Comment by panchagnula** [comment]
closing due to lack of response on this.
