### ISSUE TITLE
Missing information on how to configure using `--custom-domain-https-parameters`

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-cli#13679]
This parameter shown in the title, says it requires custom configuration, yet provides no details in how this is to be supplied.  When using the portal there are at least a few fields that would be created to choose my owner certificate, key vault where it's stored, certificate, and secret.  How do I supply these to the Azure CLI with this optional parameter?

An example would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e2b3b2-3e26-a47f-ee80-5bd5c3b065c4
* Version Independent ID: 72ef6ca0-b8f6-4952-732d-34aefa414bb6
* Content: [az cdn endpoint](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint?view=azure-cli-latest#az-cdn-endpoint-show)
* Content Source: [src/azure-cli/azure/cli/command_modules/cdn/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cdn/_help.py)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by lsmith130** [comment]
These were autogenerated parameters, and have been replaced with simpler, documented parameters in #12648.
