### ISSUE TITLE
[App Service] Manual source control syncing fails with unfriendly error

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1368]
If you run the `az appservice web source-control sync` command against an app that isn't configure to use a remote repo, it fails with the following error, which doesn't really explain the issue:

`Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/227e5d5d-9ecf-4d90-a747-95f50501343e/resourceGroups/demo-app-test/providers/Microsoft.Web/sites/demo-app-test/sync?api-version=2015-08-01`.

It would be ideal if this clearly stated that the `sync` command can't be used and why, as opposed to just outputting the "raw" error.

**Comment by yugangw-msft** [comment]
I have hold on fixing such issues, and hoped webapp service team can make their error payload conform to arm's guideline, but after 4 months, nothing has happened yet. So I am giving up and fall back to client side workaround.
