### ISSUE TITLE
key vault: support importing key from string, not just from file path

### ISSUE THREAD

**Issue by khaliddermoumi** [Azure/azure-cli#13685]
The Problem: In situations where you have generated a key in memory, or read a key from some storage which is not a file, you want to import this key directly from a string, instead of having to write it to a file first. Currently, importing a key is only supported from a file path.

The solution proposal: introduce a param to import key from string, similar to the existing file -params, f. e.:
"az keyvault key import --vault-name {kv} -n import-key-encrypted --pem-string "{key_enc_string}" --pem-password {key_enc_password}"
(likewise with all import key file options, such as ec keys etc.)

As I consider this to be a rather simple feature addition (you will need to omit reading the file, the rest is mostly the same), I am offering to submit a pull request for this feature, if you are interested. Of course, I am happy too if you implement this.

Thanks for your work, and best regards!

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by bim-msft** [comment]
Hi @khaliddermoumi , this is a really good feature, we are glad to hear that you are willing to do this. You can directly open a pull request to implement this, and I will review the code and merge it. Welcome to be a contributor!

Anyway, if you are going to be occupied with other things, our team can continue to do this at anytime. 😄

**Comment by khaliddermoumi** [comment]
Hi @bim-msft , thanks for the warm welcome! :)

I am happy to continue working on this in the next few days. If I manage to get the dev environment running, I expect I will submit a pull request around early next week.

Thx and c u

**Comment by bim-msft** [comment]
@khaliddermoumi Thank you in advance. If you need us to help with, feel free to let me know at anytime.
