### ISSUE TITLE
[CosmosDB] Using the cli command az cosmosdb keys list -n $name -g $group --subscription $sub --type connection-strings, the retrywrites, maxIdleTimeMS, and appName are missing.

### ISSUE THREAD

**Issue by preddy727** [Azure/azure-cli#13686]
**Is your feature request related to a problem? Please describe.**

From the portal, the connection strings for a mongo api cosmos include the params ?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@cdbe-ebond-prod@

Using the cli command az cosmosdb keys list -n $name -g $group --subscription $sub --type connection-strings, the retrywrites, maxIdleTimeMS, and appName are missing.

The recent Mongodb nodejs client throws an exception with the missing retrywrites param. 

**Describe the solution you'd like**

Is there a cli parameter that would get the connection string with the recommended properties added as in the portal connection string?

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
CosmosDB

**Comment by shurd** [comment]
Hi @preddy727 thank you for opening this issue. We are currently working on reconciling the differences between the portal listed connection string and the CLI-listed connection string. I will update once we have a better idea of when this will be resolved

**Comment by shurd** [comment]
To provide an update on this issue, we are going to be moving the portal to use the connection string returned from our resource provider in the near future. With this change, the connection string will be consistent between the two places. We are tracking this internally as work item 822064, and the ETA is early September for this switch. It is possible we will update the connection string returned via RP before then, and I will provide an update once we know that timeline.

**Comment by Krusen** [comment]
I seem to be having the same issue when using ARM templates and `listConnectionStrings(...)`. I'm guessing this is related.

Is this still expected to be fixed soon (early september)? Is there any workaround until it is fixed?

**Comment by shurd** [comment]
Yes, that function uses the resource provider path. The ETA for the service-side work is now early October. As a workaround, you could append these query parameters onto the returned connection string.

**Comment by shurd** [comment]
To provide an update, the updated connection string for Mongo 3.6 accounts has been merged and is awaiting deployment from the service side. Based on current deployment cycles, we expect it to be deployed around mid to late October.

**Comment by shurd** [comment]
The deployment is still pending, and we are still targeting the next few weeks.

**Comment by MehaKaushik** [comment]
Hey all, just to update, we are still waiting for deployments to complete.

**Comment by MehaKaushik** [comment]
Deployment is complete.
