### ISSUE TITLE
'az pack build' fails with Heroku Buildpacks due to incompatible platform API

### ISSUE THREAD

**Issue by ericmichael** [Azure/azure-cli#13694]
## Incompatible Platform API

Heroku example fails due to Platform API being incompatible with builder, source: https://docs.microsoft.com/sv-se/cli/azure/acr/pack?view=azure-cli-latest

**Command Name**
`az acr pack build`

**Errors:**
```
ERROR: pack v0.4.1 (git sha: 90e88e7b1dc02ca65e22548fdfbeabec4c9879a6) (Platform API version 0.1) is incompatible with builder heroku/buildpacks:18 (Platform API version 0.3)
2020/05/27 01:01:59 Container failed during run: acb_step_0. No retries remaining.
failed to run step ID: acb_step_0: exit status 1

Run ID: ca6 failed after 1m9s. Error: failed during run, err: exit status 1
Run failed
```

## To Reproduce:
Fill in `<registryname>` with a valid value.

- `az acr pack build -r <registryname> -t {{.Run.Registry}}/node-app:{{.Run.ID}} --pull --builder heroku/buildpacks:18 https://github.com/Azure-Samples/nodejs-docs-hello-world.git`

## Expected Behavior

Expected buildpack to be produced and deployed to registry.

## Environment Summary
```
macOS-10.15.4-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.6.0

```

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by yugangw-msft** [comment]
@northtyphoon, please investigate

**Comment by rmachielse** [comment]
Is there any update on this? We're running into the same issue.

**Comment by northtyphoon** [comment]
@dorfire is there any known issue with "Heroku Buildpacks"?

**Comment by dorfire** [comment]
Thanks for reporting this @ericmichael!

Seems like it's related to an outdated version of the `pack` CLI tool. I'm working on a new `pack` runner image with pack 0.12.0; I'll let you know if it resolves the issue and post exact instructions.

**Comment by dorfire** [comment]
Hey @ericmichael,
this seems to resolve the issue:
```
az acr pack build -r MyRegistry -t {{.Run.Registry}}/node-app:{{.Run.ID}} --pack-image-tag 20200715.1-patch1 --pull --builder heroku/buildpacks:18 https://github.com/Azure-Samples/nodejs-docs-hello-world.git
```

Can you confirm that it works for you?

**Comment by navba-MSFT** [comment]
@ericmichael Apologies for the late reply. Could you please run the sample command mentioned [here](https://docs.microsoft.com/en-us/cli/azure/acr/pack?view=azure-cli-latest#az-acr-pack-build-examples) using the [most recent CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos) version and check if you are still facing the issue ? This issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.
