### ISSUE TITLE
Subscription Diagnostic Settings for Activity Log Export

### ISSUE THREAD

**Issue by nkiest** [Azure/azure-cli#13692]
**Resource Provider**
Microsoft.Insights

**Description of Feature or Work Requested**
Support Subscription Variant of Diagnostic Settings to export Activity Log, as documented at
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2017-05-01-preview/subscriptionDiagnosticsSettings_API.json
This should look like Diagnostic Settings command, but with Subscription as target, rather than resource ID. Note, retention setting is not supported.
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-settings
This feature will replace Add-AzLogProfile

**Minimum API Version Required**
2017-05-01-preview

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2017-05-01-preview/subscriptionDiagnosticsSettings_API.json

**Target Date**
This was requested via ADO about 6 months ago. We need

**Comment by yonzhan** [comment]
add to S171
