### ISSUE TITLE
az: error: unrecognized arguments: --auth-mode login

### ISSUE THREAD

**Issue by vllama** [Azure/azure-cli#13708]
error when specyfying --auth-mode login

**Command Name**
`az storage cors clear`

**Errors:**
```
az: error: unrecognized arguments: --auth-mode login
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- 
- `az storage cors clear --account-name $storageAccountName --services="b"'
I get message Below:

> No connection string, account key or sas token found, we will query account keys for your storage account. Please try to use --auth-mode login or provide one of the following parameters: connection string, account key or sas token for your storage account.
- then I run:
`PS C:\powershell> az storage cors clear --account-name $storageAccountName --services="b" --auth-mode login`
- and I get:
> az: error: unrecognized arguments: --auth-mode login
> usage: az [-h] [--verbose] [--debug] [--only-show-errors]
>           [--output {json,jsonc,yaml,yamlc,table,tsv,none}] [--query JMESPATH]
>           {storage} ...
> 

## Expected Behavior
No warning or --auth-mode login should user the login I already have
## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.6.0

Extensions:
application-insights 0.1.3

```

**Comment by zhoxing-ms** [comment]
@Juliehzl Could you please help to have a look~

**Comment by yonzhan** [comment]
add to S171

**Comment by Juliehzl** [comment]
error message will be refined soon.
