### ISSUE TITLE
[App Service] Does the "web list" command need to require a resource group?

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1370]
It would be great if the `az appservice web list` command didn't require a resource group, just like the `az appservice plan list` command doesn't, in order to improve its simplicity a little bit. The mandatory nature of the `-g` flag for `list` commands seem a tad inconsistent across the CLI, and in general, allowing it to be an optional filtering mechanism would be ideal if at all possible.

**Comment by tjprescott** [comment]
@yugangw-msft will know best, but it looks like the SDK only supports a call to list sites in a resource group.

**Comment by mayurid** [comment]
normally all the list commands do have RG as optional and list has list vs list-all behavior. Looks like Webapp has the same (https://github.com/Azure/azure-rest-api-specs/blob/master/arm-web/2016-08-01/WebApps.json#L19) @yugangw-msft: bug? did we miss this?
@lostintangent : to be clear this will be list in RG vs list everything in the subscription which is consistent with the CLI

**Comment by lostintangent** [comment]
@mayurid Yep that's the behavior that I'd expect. Thanks!

**Comment by yugangw-msft** [comment]
Yep, it is a bug. The spec pointed out is the latest and we have not got python sdk generated from it. The plan on webapp is we will hold on all commands work till the swagger gets reviewed, corrected, and sdk picks it up and publish.

**Comment by yugangw-msft** [comment]
also, I believe there is an api you can list sites belong to the same plan. When we have new spec finalized, we can look up and incorporate to the same command.

**Comment by yugangw-msft** [comment]
this was fixed in the release 2 weeks ago
