### ISSUE TITLE
[Az-Cli 2.6.0] Missing required positional argument: 'extension_path' when running 'az devops login'

### ISSUE THREAD

**Issue by miketimofeev** [Azure/azure-cli#13706]
**Describe the bug**
Crossposted https://github.com/Azure/azure-devops-cli-extension/issues/1004
When running `az devops login` or `echo ${AZURE_DEVOPS_CLI_PAT} | sudo az devops login` we've got an error on version **2.6.0**, rollback to 2.5.1 resolves the issue
```
Unable to use secure credential store in this environment.
Please refer to alternate methods at https://aka.ms/azure-devops-cli-auth
using Environment variable
or use 'az login'
_run_pip() missing 1 required positional argument: 'extension_path'
```

**To Reproduce**
1. install azure-cli 2.6.0
2. install azure-devops (az extension add -n azure-devops)
3. Try to login to azure devops (az devops login or echo ${AZURE_DEVOPS_CLI_PAT} | sudo az devops login)

**Expected behavior**
`az devops login` works

**Environment summary**
azure-cli (2.6.0)
azure-devops extension (0.18.0)

Both windows\linux environments are affected

**Comment by mboutet** [comment]
Also having this problem on Ubuntu hosted Azure Pipelines pools. This is preventing builds from running. Please fix.

**Comment by yonzhan** [comment]
add to S170
