### ISSUE TITLE
not able to run

### ISSUE THREAD

**Issue by rakeshadusumilli** [Azure/azure-cli#13707]
## Describe the bug

**Command Name**
`az sql db list`

**Errors:**
```
Can not perform requested operation on nested resource. Parent resource '[logistics-prod.database.windows.net]' not found.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sql db list`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1 *

```

**Comment by adeal** [comment]
@rakeshadusumilli the server `logistics-prod` exists in chinaeast1-a. Have you [set your environment](https://docs.microsoft.com/cli/azure/manage-clouds-azure-cli?toc=%2Fcli%2Fazure%2Ftoc.json&bc=%2Fcli%2Fazure%2Fbreadcrumb%2Ftoc.json&view=azure-cli-latest) to AzureChinaCloud before running `az sql db list`?
