### ISSUE TITLE
[Network] network dns zone import output should not be red

### ISSUE THREAD

**Issue by ShaunWilkinson** [Azure/azure-cli#13702]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Output of the command is as follows - 

== BEGINNING ZONE IMPORT: *****.co.uk ==
(1/3) Imported 1 records of type 'soa' and name '@'
(2/3) Imported 1 records of type 'a' and name '@'
(3/3) Imported 1 records of type 'cname' and name 'www'
== 3/3 RECORDS IMPORTED SUCCESSFULLY: '******.co.uk' ==

This output should not be red as it indicates an error, especially frustrating with the current error regarding case-insensitivity. Ideally should be either green for success or neautral white as it's informational.

**To Reproduce**
Run the DNS Import command

**Expected behavior**
Would expect green or white text

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172

**Comment by jiasli** [comment]
@MyronFanQiu, could you try to repro this? I think the color may be controlled by the command itself.

**Comment by jiasli** [comment]
Hi @ShaunWilkinson, I tested on a local machine but couldn't repro.

```
> cd azure-cli\src\azure-cli\azure\cli\command_modules\network\tests\latest\zone_files
> az network dns zone import -n zone1.com -g rg1 --file-name zone1.txt
```

![image](https://user-images.githubusercontent.com/4003950/86723684-b5ecb500-c05a-11ea-8f75-01ea5e5fb9a1.png)

Could you share a screenshot of what you are actually seeing?

**Comment by jiasli** [comment]
Closing. If it still happens, please kindly provide a screenshot.
