### ISSUE TITLE
Next Marker Missing From az storage blob list Response Object

### ISSUE THREAD

**Issue by Alexei-B** [Azure/azure-cli#13704]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.63

**Describe the bug**
The command `az storage blob list` produces the next token in stderr, instead of including it in the response object. The response object is an array, which means it can't have a marker, however, something should be done about this because that makes this a nightmare to write automation against.

**To Reproduce**
1. Create a storage account with a container and two blobs.
2. `az storage blob list --account-name <account> --container-name <container> --num-results 1`

**Expected behavior**
I would like to be able to write automation against any command in the az CLI easily. For example, I would expect either the following PowerShell or similar to return all blobs in a storage account container:
```PowerShell
$next_token = ""

do {
  $response = & az storage blob list --account-name <account> --container-name <container> --num- results 1 | ConvertFrom-Json
  $next_token = $response.next_marker
  $blobs += $response.blobs
} while ($next_token -ne $null)

$blobs
```

**Environment summary**
OS: Windows 10
Shell: PowerShell 7.0.0
Installer: MSI
az --version:
```
azure-cli                          2.6.0

command-modules-nspkg              2.0.3
core                               2.6.0
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\alexei.barnes\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/clihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

**Additional context**
The help docs on this command specifically call out reading "next_marker":
```
    --marker                       : An opaque continuation token. This value can be retrieved from
                                     the next_marker field of a previous generator object if
                                     num_results was specified and that generator has finished
                                     enumerating results. If specified, this generator will begin
                                     returning results from the point where the previous generator
                                     stopped.
```

**Comment by yungezz** [comment]
hi @Juliehzl could you pls have a look?

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
Hi @Alexei-B, thanks for your feedback.

To  not break existing users' scripts, we are thinking that adding one additional argument to represent that users want to include nextMarker in the response. If you still have any concern, feel free to let me know.

**Comment by Alexei-B** [comment]
@Juliehzl that makes sense to me!

**Comment by Juliehzl** [comment]
Hi @Alexei-B , it is supported in https://github.com/Azure/azure-cli/pull/14832.
Please install latest azure cli and try`az storage blob list` with `--show-next-marker`

**Comment by star286** [comment]
@Juliehzl could you please also add this parameter **--show-next-marker** for **ADLS Gen2**, for this command [az storage fs file list](https://docs.microsoft.com/en-us/cli/azure/storage/fs/file?view=azure-cli-latest#az_storage_fs_file_list)?

**Comment by Juliehzl** [comment]
> @Juliehzl Zunli Hu FTE could you please also add this parameter **--show-next-marker** for **ADLS Gen2**, for this command [az storage fs file list](https://docs.microsoft.com/en-us/cli/azure/storage/fs/file?view=azure-cli-latest#az_storage_fs_file_list)?

I see. We will plan for the feature soon.
