### ISSUE TITLE
Adding global action to CDN using az cli fails

### ISSUE THREAD

**Issue by vivekananth** [Azure/azure-cli#13709]
**Describe the bug**
az cdn endpoint rule action add -g group -n name --profile-name profile --rule-name Global --action-name "ModifyResponseHeader" --header-action Overwrite --header-name X-Content-Type-Options --header-value nosniff

Running the above command fails with below error

"validation error: Parameter 'DeliveryRuleAction.name' can not be None."

**To Reproduce**
1. Have a CDN endpoint and profile 
2. Create a global rule to add action using above mentioned command

**Expected behavior**
Expected rules to be created

**Environment summary**
azure-cli                          2.6.0

command-modules-nspkg              2.0.3
core                               2.6.0
nspkg                              3.0.4
telemetry                          1.0.4

**Additional context**

**Comment by yonzhan** [comment]
cdn

**Comment by hytao** [comment]
Currently we are using "RequestHeader" instead of "ModifyResponseHeader" as action name in CLI. We'll probably change this but please use "RequestHeader" as the action name for now.
