### ISSUE TITLE
No updates available for 'azure-cli-ml' - extension not available 

### ISSUE THREAD

**Issue by dedreira** [Azure/azure-cli#13717]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Until yesterday azure-cli-ml extension was available to be installed through command az extension install -n azure-cli-ml

**To Reproduce**

type: "**az extension install -n azure-cli-ml**" or "**az extension update -n azure-cli-ml**"

This error message appear:

**No updates available for 'azure-cli-ml'. Use --debug for more information.**

**Expected behavior**

Azure CLI ML extension should be installed successfully

**Environment summary**

Any platform with Azure CLI

**Additional context**

There's additional information log:

**urllib3.connectionpool : Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool : https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool : Starting new HTTPS connection (1): azurecliextensionsync.blob.core.windows.net:443
urllib3.connectionpool : https://azurecliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 309315
Candidates ['azure_cli_ml-1.6.0-py3-none-any.whl']
Skipping 'azure_cli_ml-1.6.0-py3-none-any.whl' as not universal wheel.We do not currently support platform specific extension detection. They can be installed with the full URL https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.6.0-py3-none-any.whl
Candidates []
Candidates []
No suitable extensions found.
cli.azure.cli.core.util : No updates available for 'azure-cli-ml'. Use --debug for more information.
No updates available for 'azure-cli-ml'. Use --debug for more information.**

**Comment by yonzhan** [comment]
ml

**Comment by hustbill** [comment]
In this [azure-cli-extensions index.json](https://github.com/Azure/azure-cli-extensions/blob/master/src/index.jsonl)
azure-cli-ml requires azure-cli min version should be 2.3.1

```json
 "azure-cli-ml": [
            {
                "downloadUrl": "https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.6.0-py3-none-any.whl",
                "filename": "azure_cli_ml-1.6.0-py3-none-any.whl",
                "metadata": {
                    "azext.minCliCoreVersion": "2.3.1",
```

You can replace your requirements.txt 
```
azure-cli==2.1.0
azure-cli-core==2.1.0
```

to 
```
azure-cli==2.3.1
azure-cli-command-modules-nspkg==2.0.3
azure-cli-core==2.3.1
```
Ref to requirments.txt in the source code.
https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.3.1

**Comment by dedreira** [comment]
Thanks, I have found that this requirement changed [yesterday](https://github.com/Azure/azure-cli-extensions/commit/21252b2131b3e3f2d4c7744226ec690458753db7#diff-175151397c27e434c8016e66047e72f4).  Changed the minimun Az CLI required version from 2.0.28 to 2.3.1 . . . .  (that's a huge version jump....)

**Comment by j-so** [comment]
We have bumped our minCliCoreVersion to 2.3.1 to resolve compatibility issues, and users will need to upgrade az CLI to get our latest extension. Unfortunately, the error message is not clear about that.

If you want to use our older versions that are compatible with older az CLI versions, you can install the whl directly. i.e. `az extension add --source https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.5.0-py2.py3-none-any.whl`

**Comment by dedreira** [comment]
thanks a lot for the workaround @j-so  😄

**Comment by j-so** [comment]
We are now working on providing version 1.5.0 for users with az CLI <2.3.1 automatically with the az extension add command. I’ll update again once that is available.

**Comment by j-so** [comment]
We have published the change. If you have az CLI version < 2.3.1, you should get az ml extension version 1.5.0 when using `az extension add -n azure-cli-ml`.

For updates, you will need to upgrade your az CLI version.

Thanks for the feedback!

**Comment by dedreira** [comment]
@j-so thanks a lot! it's working again :)
