### ISSUE TITLE
VWan:: Hub virtual network connection related changes

### ISSUE THREAD

**Issue by shyamshd** [Azure/azure-cli#13715]
**Resource Provider**

Network resource provider

**Description of Feature or Work Requested**

Virtual Wan service is changing the interface to specify virtual network connections in a Virtual hub to address specific scenarios (and simplify the interface/behavior).

Currently the Virtual Network connections are specified as a part of PUT on the Virtual Hub. This has been changed in 2020-05-01 API version to no longer accept Virtual network connections as a part of the PUT hub call. (The PUT call with virtual network connections would return an error). The virtual network connections can be created/updated or deleted only using direct PUT/DELETE calls on the Virtual Network connection. This is a newly exposed API in swagger.

The swagger change PR for this is still under review. 
https://github.com/Azure/azure-rest-api-specs/pull/9536/

Once this is merged in & the sdk is available, we’d need changes in the az-cli any time before you cut over to 2020-05-01 API version.  The older API versions (e.g. 2020-04-01) will continue to work as before. Corresponding Powershell/Portal changes are being tracked separately-
Powershell request- https://github.com/Azure/azure-powershell/pull/12009

One additional change is to deprecate the allowHubToRemoteVnetTransit and allowRemoteVnetToUseHubVnetGateways flags in the hub virtualnetwork connection. Currently it is marked as deprecated and will be removed in the future. It would be good to follow similar process for azcli too.

**Minimum API Version Required**

2020-05-01

**Swagger Link**

This is a pending PR in  network-may branch 
https://github.com/Azure/azure-rest-api-specs/pull/9536/

**Target Date**

Before AZ cli moves to nrp 2020-05-01 version. Otherwise some aspects of az cli might be broken.

**Comment by yonzhan** [comment]
add to S171
