### ISSUE TITLE
This really needs some color (especially the JSON output)

### ISSUE THREAD

**Issue by snobu** [Azure/azure-cli#1371]
Just a thought - would be nice to have a `--color` parameter (which could be the default or not - or at least be configurable).

Using [underscore-cli](https://github.com/ddopson/underscore-cli) to simulate desired behaviour here:

![image](https://cloud.githubusercontent.com/assets/6472374/20428919/6296943e-ad94-11e6-8bf0-2b236db8d448.png)

**Comment by mayurid** [comment]
@snobu: have you tried -o jsonc as an option to see colorized Json output?

**Comment by snobu** [comment]
A-ha! Cool stuff.
Can i make that the default through something like `.azrc`, you know like `.bashrc` or `.vimrc`?

![image](https://cloud.githubusercontent.com/assets/6472374/20430985/31dc6f74-ada0-11e6-9549-f4a1bad54544.png)

**Comment by tjprescott** [comment]
@snobu you can set your default output format using `az configure` (my default is also JSONC 👍 )
