### ISSUE TITLE
hostnames in --allowed-clients

### ISSUE THREAD

**Issue by hmeiland** [Azure/azure-cli#13722]
From the documentation, it seems hostnames can be used in the allowed clients; on the cli this errors and in the portal it says specificly that on ip and cidr are allowed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4429655-bc7e-37d2-eb90-9a9ad203b62a
* Version Independent ID: 88efa4de-a91b-a217-d236-dc16c62432ca
* Content: [az netappfiles volume export-policy](https://docs.microsoft.com/en-us/cli/azure/netappfiles/volume/export-policy?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/netappfiles/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/netappfiles/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
netappfiles

**Comment by audunn** [comment]
Stale issue fixed
```
--allowed-clients
Client ingress specification as comma separated string with IPv4 CIDRs, IPv4 host addresses and host names. 
```
