### ISSUE TITLE
'***' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by yannick-Lapierre** [Azure/azure-cli#13726]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I am not sure if it's a bug, but I don't know where I can ask for this issue:

I have a PowerShell script using az. this script is a part of an AzureDevops Task written in Powershell.
When I execute the az statement I got this error:
```text
{
   "exists": false
}
##[debug]Leaving D:\a\_tasks\<*****>\1.0.38\<*****>.ps1.
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]'st' is not recognized as an internal or external command,
##[debug]    + CategoryInfo          : NotSpecified: (:) [], RemoteException
##[debug]    + FullyQualifiedErrorId : RuntimeException
```

**To Reproduce**
``` PowerShell
az storage container exists --account-name $StorageAccountName --name $containerName --sas-token '?sv=2019-02-02&st=2020-05-28T14%3A09%3A23Z&se=2020-05-29T14%3A09%3A23Z&sr=c&sp=racwdl&sig=<hided>'
```

**Expected behavior**
Return the message without error.

**Environment summary**
I execute 
```powershell
az --version
```
and get this response:

```text
debug]az client version: azure-cli                          2.5.1 *  command-modules-nspkg              2.0.3 core                               2.5.1 * nspkg                              3.0.4 telemetry                          1.0.4  Extensions: azure-devops                      0.18.0  Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe' Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'  Python (Windows) 3.6.6 
```

**Additional context**
When I execute the query from the **try it** in [az storage](https://docs.microsoft.com/en-us/cli/azure/storage?view=azure-cli-latest)
get the result:
```
{
  "exists": true
}
```

**Comment by yonzhan** [comment]
add to S171

**Comment by Juliehzl** [comment]
Hi @yannick-Lapierre, actually it is a powershell issue because pwershell will always loss `"` for agrguments.

So I will recommend you use `az --% storage container exists --account-name zuhdefault --name test --debug --sas-token "?sv=2019-02-02&st=2020-06-15T06%3A53%3A23Z&se=2020-06-16T06%3A53%3A23Z&sr=c&sp=rl&sig=REDACT"`.  You can see more here https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md#ampersand--is-interpreted-by-command-prompt.
