### ISSUE TITLE
Add support for 'Log Analytics data export'

### ISSUE THREAD

**Issue by yossi-y** [Azure/azure-cli#13721]
**Resource Provider**
microsoft.operationalinsights

**Description of Feature or Work Requested**
Feature document is available [here]( https://microsoft.sharepoint.com/:w:/t/LogAnalyticsTeam/EbhdHdsVLwBKksLCbObyVqkBSBgMZfKTzX1hs1mk2rIKLQ?e=0ytp0m):

Support these operations: 
- Create a data export rule
- Update a data export rule
   - Disable an export rule
   - Update tables for export
   - Update destination
- Get data export rule configuration
- Delete a data export rule
- Get all data export rules in a workspace

**Minimum API Version Required**
2020-03-01-preview

**Swagger Link**
- [Swaggers](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/preview/2020-03-01-preview/DataExports.json)
- [rest doc](https://docs.microsoft.com/en-us/rest/api/loganalytics/dataexports) 

**Target Date**
This is already needed for private preview customers, which are using rest API currently. Once CLI is available, we can make the configuration easier for them with CLI.

**Comment by yonzhan** [comment]
add to S171

**Comment by MyronFanQiu** [comment]
@yossi-y Hi. I have sent out an email to you talking about some issues in the swagger spec.

**Comment by yossi-y** [comment]
Replied the mail.
