### ISSUE TITLE
AZ AKS not working

### ISSUE THREAD

**Issue by rameshthangaraj** [Azure/azure-cli#13725]
## Describe the bug

**Command Name**
`az aks`

**Errors:**
```
invalid syntax (custom.py, line 1399)
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 549, in execute
    parsed_args = self.parser.parse_args(args)
python2.7/site-packages/knack/parser.py, ln 259, in parse_args
    return super(CLICommandParser, self).parse_args(args)
2.7/lib/python2.7/argparse.py, ln 1705, in parse_args
    args, argv = self.parse_known_args(args, namespace)
...
lib/python2.7/importlib/__init__.py, ln 37, in import_module
    __import__(name)
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 1399
    f'save them to the storage account '
    ^
SyntaxError: invalid syntax
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks -h`

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 2.7.16
Shell: bash

azure-cli 2.0.71 *

Extensions:
aks-preview Unknown

```

**Comment by yonzhan** [comment]
aks

**Comment by jluk** [comment]
the preview extension version is suspicious, could you try removing and reinstalling the extension?

az extension remove -n aks-preview
az extension add -n aks-preview

**Comment by rameshthangaraj** [comment]
Tried it but didnt help at all.

**Comment by palma21** [comment]
Please update your core-cli and then install the extension, that CLI version is too old to use the latest extension. 

Current versions


jpalma@aeolus:~$ az --version
azure-cli                          2.6.0

Extensions:
aks-preview                       0.4.49
