### ISSUE TITLE
Can't manually create a service principal - Bad Request - 401

### ISSUE THREAD

**Issue by Ayrica** [Azure/azure-cli#13731]
I just install Azure CLI 2.6.0 (Windows 10) and when I try manually create a service principal like this (from doc):
az ad sp create-for-rbac --skip-assignment --name myAKSClusterServicePrincipal

Using documentation - https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#automatically-create-and-use-a-service-principal

Got:
{
  "appId": "appId",
  "displayName": "displayName",
  "name": "name",
  "password": "9bzD}N{K7j2Wchss,o+fKdk}n8QP+|r:",
  "tenant": "tenantGUID"
}

Password looks like incorrect!

Then I use password to specify a service principal for an AKS cluster:
az aks create --resource-group "resource-group-name" --name "cluster-name" --service-principal "appId" --client-secret "9bzD}N{K7j2Wchss,o+fKdk}n8QP+|r:"

Got error:
Operation failed with status: 'Bad Request'. Details: The credentials in ServicePrincipalProfile were invalid. Please see https://aka.ms/aks-sp-help for more details. (Details: adal: Refresh request failed. Status Code = '401')

OR

Operation failed with status: 'Bad Request'. Details: Service principal client secret has invalid characters:

Thanks for help.

**Comment by yungezz** [comment]
hi @arrownj could you have a look?

**Comment by grexofficial** [comment]
I have the same issue!

**Comment by Michael-Coetzee** [comment]
also have the same issue, please bring back --password switch again

**Comment by yolalayouu** [comment]
Same issue for me, the auto-generated password seems to work half the time.

**Comment by yungezz** [comment]
seems related to password generation, reassign.

**Comment by jiasli** [comment]
Similar as https://github.com/Azure/azure-cli/issues/13761. It is very likely some characters in the password are corrupting AKS, but we don't exactly know how and why.

This password itself doesn't have any issue with Bash and Azure CLI:

```sh
$ echo "9bzD}N{K7j2Wchss,o+fKdk}n8QP+|r:"
9bzD}N{K7j2Wchss,o+fKdk}n8QP+|r:
$ az "9bzD}N{K7j2Wchss,o+fKdk}n8QP+|r:" --debug
Command arguments: ['9bzD}N{K7j2Wchss,o+fKdk}n8QP+|r:', '--debug']
```

The password generation logic has been changed in https://github.com/Azure/azure-cli/pull/13643 only allowing punctuation of `-_.~`. Please update to the latest Azure CLI version 2.7.0 and try creating the service principal again. 

```sh
$ az ad sp create-for-rbac --skip-assignment --name myAKSClusterServicePrincipal
Changing "myAKSClusterServicePrincipal" to a valid URI of "http://myAKSClusterServicePrincipal", which is the required format used for service principal names
{
  "appId": "",
  "displayName": "myAKSClusterServicePrincipal",
  "name": "http://myAKSClusterServicePrincipal",
  "password": "E-GATSTl7fNQsRSt4J~MwZzdv-GsnpZ4pt",
  "tenant": ""
}
```

**Comment by jiasli** [comment]
If the issue persists, please let us know.
