### ISSUE TITLE
App update fails when Role type is included in the resourceAccess list

### ISSUE THREAD

**Issue by pachabelle** [Azure/azure-cli#13739]
I am running

> az ad app update

with the --required-resource-accesses parameter.  When resourceAccess array contains a Role type such as

"resourceAccess": [
	{
		"id": "e2a3a72e-5f79-4c64-b1b1-878b674786c9",
		"type": "Role"
	}
]

 the call fails complaining that the property is invalid.  Scope types are fine.  The array is copied from the manifest file on the Azure Portal so the values are definitely correct.  Is there a work around for adding Role type access?

**Comment by yonzhan** [comment]
@arrownj  please take a look

**Comment by arrownj** [comment]
Hi @pachabelle , what's the content of your json file ? I test from my side and it successfully update the app with a Role type. Could you please provide your CLI version and the full json content to help us reproduce this issue ? Thanks

**Comment by pachabelle** [comment]
Hi Xiaojian,

Thanks for getting back to me.

My json file is attached.  I am using cli version 2.6.0

Regards,
Cheng

**Comment by pachabelle** [comment]
Hi,

Sorry, sent you a json file with a typo.  I just tried v2.10.1 and I still
get the same error.

Regards,
Cheng

**Comment by pachabelle** [comment]
{
    "name": "TestApp",
    "requiredResourceAccess": [
        {
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "resourceAccess": [
                {
                    "id": "e2a3a72e-5f79-4c64-b1b1-878b674786c9",
                    "type": "Role"
                },
                {
                    "id": "b633e1c5-b582-4048-a93e-9f11b44c7e96",
                    "type": "Role"
                }
            ]
        }
    ]
}

**Comment by arrownj** [comment]
Hi @pachabelle , your json format is not right, you can run `az ad app update -h` to see the example, I also paste it here for your reference.
>Examples
    update a native application with delegated permission of "access the AAD directory as the
    signed-in user"
        az ad app update --id e042ec79-34cd-498f-9d9f-123456781234 --required-resource-accesses
        @manifest.json
        ("manifest.json" contains the following content)
        [{
            "resourceAppId": "00000002-0000-0000-c000-000000000000",
            "resourceAccess": [
                {
                    "id": "a42657d6-7f20-40e3-b6f0-cee03008a62a",
                    "type": "Scope"
                }
           ]
        }]

I successfully update the application with below json, you can copy and try that.

>[
        {
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "resourceAccess": [
                {
                    "id": "e2a3a72e-5f79-4c64-b1b1-878b674786c9",
                    "type": "Role"
                },
                {
                    "id": "b633e1c5-b582-4048-a93e-9f11b44c7e96",
                    "type": "Role"
                }
            ]
        }
    ]

**Comment by arrownj** [comment]
Hi @pachabelle , I will close it if no more question. Reach us if you have other concerns. Thanks
