### ISSUE TITLE
az webapp logs needs to support deployment logs

### ISSUE THREAD

**Issue by btardif** [Azure/azure-cli#13734]
We can get list of deployments form: 

`https://<webapp>.scm.azurewebsites.net/api/deployments/`

And you can get deployment logs form a specific deployment through:

`https://<webapp>.scm.azurewebsites.net/api/deployments/<id>`

**Comment by panchagnula** [comment]
@btardif can you share the list of commands we need to add as a part of this? Thanks!

**Comment by btardif** [comment]
@panchagnula 

`az webapp logs deployment`  --> Show the latest deployment log

`az webapp logs deployment list`  --> List of deployment logs available

`az webapp logs deployment --deploymentid <id>` Show specific deployment log
