### ISSUE TITLE
Az.Accounts 1.8.0 having trouble to load - System.Threading.Tasks.Extensions

### ISSUE THREAD

**Issue by etiennehucklemarchand** [Azure/azure-cli#13746]
**Describe the bug**
Since a PowerShell Az module upgrade, the Az.Accounts module has trouble loading. The failure is caught by $ERROR environment variable. The variable gets filled-in when importing the Az.Accounts modules, when opening a PowerShell session or console. It seems to have trouble with one of its dependencies:
`Add-Type : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`
`At C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\1.8.0\Az.Accounts.psm1:68 char:17`
`+ ...                Add-Type -Path $_.FullName -ErrorAction Ignore | Out-N ...`
`+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : NotSpecified: (:) [Add-Type], ReflectionTypeLoadException`
`    + FullyQualifiedErrorId : System.Reflection.ReflectionTypeLoadException,Microsoft.PowerShell.Commands.AddTypeCommand`

Getting more information on the error above by running `$error[0].Exception.GetBaseException().LoaderExceptions`, it outputs the following:
`Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral,
PublicKeyToken=xxxxx' or one of its dependencies. The system cannot find the file specified.`

**To Reproduce**
Open a PowerShell console and type `$ERROR`. 

**Expected behavior**
The $ERROR variable should be empty

**Environment summary**
Installed the module by deleting the older version, then using `Install-Module -Name Az.Accounts` PowerShell command. Currently running Az v.4.1.0 and Az.Accounts v.1.8.0

**Additional context**
(Will add anything in this section if needed)

**Comment by yonzhan** [comment]
This is a powershell issue, right? Please open an issue in powershell repo. Thanks.
