### ISSUE TITLE
Missing antlr4, az vm met missing module antlr4 error

### ISSUE THREAD

**Issue by tinokingstone** [Azure/azure-cli#13747]
## Describe the bug

**Command Name**
`az vm list`

**Errors:**
```
No module named 'antlr4'
Traceback (most recent call last):
lib/python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
dist-packages/azure/cli/core/__init__.py, ln 300, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
azure/cli/command_modules/vm/__init__.py, ln 31, in load_arguments
    from azure.cli.command_modules.vm._params import load_arguments
azure/cli/command_modules/vm/_params.py, ln 31, in <module>
    from azure.cli.command_modules.monitor.actions import get_period_type
azure/cli/command_modules/monitor/actions.py, ln 7, in <module>
    import antlr4
ModuleNotFoundError: No module named 'antlr4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm list`

## Environment Summary
```
Linux-5.4.0-33-generic-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81 *

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by qwordy** [comment]
What OS do you use and how do you install Azure CLI?

**Comment by yonzhan** [comment]
@tinokingstone any update?

**Comment by qwordy** [comment]
Are you using the bundled Azure CLI of Ubuntu? The package is old and has some problems. Could you install the latest version and retry?
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

**Comment by yungezz** [comment]
hi @tinokingstone this is caused by issue https://github.com/Azure/azure-cli/issues/14011, similiar one #14001. Root cause is that old version 2.0.81 which isn't correctly package. Could you pls follow official installation guide here to install latest azure cli https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest? let us know if any other issue met

**Comment by qwordy** [comment]
No response since June 1st.
