### ISSUE TITLE
az storage account create exits bat script

### ISSUE THREAD

**Issue by torres-roberto** [Azure/azure-cli#13749]
I'm writing a Windows batch script with multiple `az storage account create` commands to automate creating the storage accounts. After running one, it exits my script. This script contains other az commands that do not exit my script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92115d19-d7a0-93a8-bf2b-5126d1cddcd0
* Version Independent ID: a657f09b-e1ac-12a2-4b9c-7aaa1f0e3f5c
* Content: [az storage account](https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az-storage-account-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S171

**Comment by Juliehzl** [comment]
@torres-roberto  You need to add `call` in each cli command.
