### ISSUE TITLE
Invalid SKU name provided

### ISSUE THREAD

**Issue by zama202** [Azure/azure-cli#13753]
instruction not valid.
if I insert one of the suggested SKU... it appears this message: 
"Invalid SKU name provided"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a0adf5-f3e3-01a5-59cb-0475cc4506fd
* Version Independent ID: c94cc817-9e89-4904-2865-1f08838ee472
* Content: [az kusto cluster](https://docs.microsoft.com/en-us/cli/azure/kusto/cluster?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/kusto/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/kusto/_help.py)
* Service: **data-explorer**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Kusto

**Comment by astauben** [comment]
Hi @zama202 we have recently update the CLI client and it seems that you are using the old version. Please install the new Kusto CLI extension as explained here: https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-cli  and let us know if the issue has not been resolved.

**Comment by navba-MSFT** [comment]
@zama202 Apologies for the late reply. Did you get a chance to test with the most recent version of the CLI ? Please let us know if you are still facing this issue. Awaiting your reply.

**Comment by zama202** [comment]
ok, It's solved. Thank you, you can close the ticket.
