### ISSUE TITLE
az keyvault create not idempotent with access policies

### ISSUE THREAD

**Issue by mcalnd70** [Azure/azure-cli#13752]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

The "**az keyvault create**" command is not idempotent with **Access Policies**. On re-running the command the Access Policies are deleted/removed.

**To Reproduce**

Create a KeyVault with **az keyvault create**  e.g. "**_az keyvault create --location westus2 --name MyKeyVault --resource-group MyResourceGroup_**"

Assign an access policy to the KeyVault, either manually in the portal, or via another Azure CLI or PowershellAz command.

Run the "**az keyvault create --location westus2 --name MyKeyVault --resource-group MyResourceGroup**" command again

The access policy has been removed/deleted

**Expected behavior**
Leave the Access Policy alone

**Environment summary**

All environments

**Additional context**

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by bim-msft** [comment]
Duplicate with #13212 
Hi @mcalnd70 , thanks for the feedback. Unfortunately, this is the expected behavior on service side. You can refer to the above issue to see more detail.
If you have any question, feel free to ping me again.

**Comment by mcalnd70** [comment]
@bim-msft The other one has been closed? Is this being worked on?

**Comment by bim-msft** [comment]
@mcalnd70 Hi, sorry for the late response. We are working on it.

**Comment by yungezz** [comment]
This one is a feature request because previously az keyvault don't support idempotent at client side, but depends on service to provide idempotency. To support at client side, there's little debate at existing user experience impact. PR is ready, we're working on reviewing and fine design on it.

**Comment by pascalnaber** [comment]
@yungezz Maybe I don't understand what you mean with client side idempotency. Because I would not know why somebody needs that. Idempotency is about server side behavior if you ask me.

If I read about the az cli Standard Command Types, The CREATE command MUST be idempotent according to the documentation.

https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#standard-command-types

Hopefully, the behavior of the Keyvault can be changed soon according to the cli guidelines.

**Comment by puagarwa** [comment]
@bim-msft Is there any ETA for this fix ? I am also facing this issue in my CMK code where i create key vault and then add ACL for CMK to work but once we deploy template again, things break because it altogether remove access policy. I have to everything via ARM here.
