### ISSUE TITLE
Can't get away from a ready-only filesystem error.

### ISSUE THREAD

**Issue by speediefarf** [Azure/azure-cli#13759]
## Describe the bug

**Command Name**
`az group show`

**Errors:**
```
Resource group 'eshop-learn-rg' could not be found.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group show -g {} -o {}`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1 *

```

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
@speediefarf Could you please show the details of the error?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
