### ISSUE TITLE
Remove preview comment for cluster

### ISSUE THREAD

**Issue by yossi-y** [Azure/azure-cli#13754]
**Resource Provider**
microsoft.operationalinsights

**Description of Feature or Work Requested**
Cluster is GA now (no announcement for it) and we need to remove the preview comment: 

- "Command group 'monitor log-analytics cluster' is in preview. It may be changed/removed in a future release."
- Linkservices for: Link/unlink workspace to cluster
- Link storage account to workspace

**Minimum API Version Required**
2020-03-01-preview

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/preview/2020-03-01-preview

**Target Date**
6/5/2020

**Comment by yonzhan** [comment]
add to S171

**Comment by jsntcy** [comment]
@yossi-y, do we also need remove `preview` for the commands that link/unlink cluster with workspace?

**Comment by yossi-y** [comment]
Yes.
We need to remove the preview comment from these commands:

  *   Cluster create/update (all updates)
  *   link/unlink cluster with workspace
  *   Link/unlink storage account to workspace
