### ISSUE TITLE
AKS: cannot use secret generated from credential reset cli

### ISSUE THREAD

**Issue by lostrouter** [Azure/azure-cli#13761]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

following this guide https://docs.microsoft.com/en-us/azure/aks/azure-ad-integration-cli

i run into this error at the step for creating the cluster
`Operation failed with status: 'Bad Request'. Details: Service principal client secret has invalid characters: ` '`

**To Reproduce**

following this guide https://docs.microsoft.com/en-us/azure/aks/azure-ad-integration-cli

**Expected behavior**

any "password" generated by `az ad sp credential reset` should be consumable by `az aks create`

**Environment summary**

MacOS 10.15.4
zsh 5.7.1 
azure-cli                          2.6.0
command-modules-nspkg              2.0.3
core                               2.6.0
nspkg                              3.0.4
telemetry                          1.0.4

**Additional context**

**Comment by yonzhan** [comment]
add to S171

**Comment by qianwens** [comment]
This issue has been fixed in PR https://github.com/Azure/azure-cli/pull/13643 which will be released on 6/3/2020. Please let us know if you still meet the issue with the new version.
