### ISSUE TITLE
`az monitor metrics list` retrieves null for average values

### ISSUE THREAD

**Issue by tingtingq** [Azure/azure-cli#13760]
## Describe the bug

**Command Name**
`az monitor metrics list`

**Errors:**
The cli can be ran successfully, and but returns null for 'average' fields, which should not be.
{
  "cost": 0.0,
  "interval": "0:30:00",
  "namespace": "Microsoft.NetApp/netAppAccounts/capacityPools/volumes",
  "resourceregion": "eastus",
  "timespan": "2020-06-01T02:35:31Z/2020-06-01T03:35:31Z",
  "value": [
    {
      "displayDescription": "Logical size of the volume (used bytes)",
      "errorCode": "Success",
      "id": <my id>,
      "name": {
        "localizedValue": "Volume Consumed Size",
        "value": "VolumeLogicalSize"
      },
      "resourceGroup": <my rg>,
      "timeseries": [
        {
          "data": [
            {
              "average": null,
              "count": null,
              "maximum": null,
              "minimum": null,
              "timeStamp": "2020-06-01T02:35:00+00:00",
              "total": null
            },
            {
              "average": null,
              "count": null,
              "maximum": null,
              "minimum": null,
              "timeStamp": "2020-06-01T03:05:00+00:00",
              "total": null
            }
          ],
          "metadatavalues": []
        }
      ],
      "type": "Microsoft.Insights/metrics",
      "unit": "Bytes"
    }
  ]
}
## To Reproduce:
It's reproducible since May/16th, it was working fine before that. 

- _Put any pre-requisite steps here..._
- `az monitor metrics list --resource {} --metric {} --interval {}`

## Expected Behavior
Get proper average numbers for VolumeLogicalSize.

## Environment Summary
```
Linux-3.10.0-1062.9.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
Python 3.6.8
Installer: RPM

azure-cli 2.6.0

```

**Comment by yonzhan** [comment]
add to S172

**Comment by TuoYe25** [comment]
Any updates @yonzhan ?

**Comment by MyronFanQiu** [comment]
@tingtingq @TuoYe25  If possible, could you run the command with `--debug` to check the raw output? We didn't release any new version in the past week. Meanwhile, `az monitor metrics list` is a simple command and we didn't do much thing for it. It should be a service issue.

**Comment by TuoYe25** [comment]
Thanks @MyronFanQiu , in fact, a SR:120052123000836 had been raised to our Monitor team and with the collab from NetApp team, we can confirm that this is not a issue related to metric resource. One evidence is that @tingtingq was able to get normal result from another server. 

@tingtingq ,could you please try the command with --debug and also provide us the CLI version used in the two servers? Thanks!

**Comment by MyronFanQiu** [comment]
@TuoYe25 Wait for debug information. This is strange. The last potential change for this command is about 2 months ago. We bump the dependency for monitor. But it should not have any impact for this command as well.

**Comment by yonzhan** [comment]
@tingtingq, any update for debug info?

**Comment by navba-MSFT** [comment]
@tingtingq Apologies for the late reply. This issue is open for quite sometime. Could you please let us know if you need assistance on this issue ? If Yes, could you please share the --debug output from the command ? Awaiting your reply.
