### ISSUE TITLE
az deployment sub create add --mode flag (complete\Incremental)

### ISSUE THREAD

**Issue by motim6026** [Azure/azure-cli#13768]
There is any option to create RG using  az deployment sub create (subscription scope)
with mode parameters? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c21eb60-cfe9-0ef7-8d93-71a8af273a04
* Version Independent ID: a97f1562-8602-f55e-df4e-7523f437edcf
* Content: [az deployment sub](https://docs.microsoft.com/en-us/cli/azure/deployment/sub?view=azure-cli-latest#az-deployment-sub-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
@motim6026 May I ask what do you mean by the `mode parameters`?

**Comment by zhoxing-ms** [comment]
@motim6026 Hi, You can declare the deployment mode of resources in the ARM template, for example:
```
"resources": [
  {
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2017-05-10",
      "name": "linkedTemplate",
      "properties": {
          "mode": "Incremental",
          <nested-template-or-external-template>
      }
  }
]
```
Do you have any other questions?

**Comment by yonzhan** [comment]
@motim6026 any update?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Comment by montereyharris** [comment]
Can Incremental Mode be declared in bicep?

**Comment by zhoxing-ms** [comment]
> Can Incremental Mode be declared in bicep?

@Shenglol Could you please help answer this question?

**Comment by johndikeibm** [comment]
Does anyone have an answer to this yet?
Using incremental mode with bicep deployments..
