### ISSUE TITLE
[AKS]: Wrong error message when trying to add a label whose value has more than 63 chars.

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-cli#13767]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.6.0

**Describe the bug**

https://github.com/Azure/azure-cli/blob/cbb7c28fc29d4e92a4908c8d85ea2de30ceb9c25/src/azure-cli/azure/cli/command_modules/acs/_validators.py#L327-L328
Error message is wrong: 
```
Invalid label: kubernetes.azure.com/node-image-version=AKSWindows-2019-datacenter-core-smalldisk-2005-17763.1217.200513. Label must be more than 63 chars.
```

**To Reproduce**

```
az aks nodepool add -g rg --cluster-name k8s -n ap --os-type Windows --node-vm-size Standard_D2s_v3 --node-count 1 --labels kubernetes.azure.com/node-image-version=AKSWindows-2019-datacenter-core-smalldisk-2005-17763.1217.200513
```

**Expected behavior**

```
Invalid label: kubernetes.azure.com/node-image-version=AKSWindows-2019-datacenter-core-smalldisk-2005-17763.1217.200513. Label must not be more than 63 chars.
```

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
AKS

**Comment by jluk** [comment]
Thanks for logging this @AbelHu is this WI one you will own for resolution?

**Comment by AbelHu** [comment]
@jluk It is ok to assign to me.
