### ISSUE TITLE
Az webapp integartion failure with NonType, No attribute location

### ISSUE THREAD

**Issue by pardhasaradhireddy** [Azure/azure-cli#13775]
Az webapp vnet Integration fails with nonType, no attribute location. It looks like a bug.

az webapp vnet-integration add -g myrsg -n mywebapp --vnet myvnet --subnet mysubnet
This command group is in preview. It may be changed/removed in a future release.
usage: az webapp vnet-integration add [-h] [--verbose] [--debug]
                                      [--output {json,jsonc,table,tsv,yaml,yamlc,none}]
                                      [--query JMESPATH]
                                      [--subscription _SUBSCRIPTION] --name
                                      NAME --resource-group
                                      RESOURCE_GROUP_NAME --vnet VNET --subnet
                                      SUBNET [--slot SLOT]
**az webapp vnet-integration add: error: 'NoneType' object has no attribute 'location'**

[](https://docs.microsoft.com/en-us/cli/azure/webapp/vnet-integration?view=azure-cli-latest#az-webapp-vnet-integration-add)

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@pardhasaradhireddy thanks for reporting if you are still seeing this can you run the command with --debug flag at the end of the command & let us know what you see. Thanks!

**Comment by panchagnula** [comment]
closing due to lack of response.
