### ISSUE TITLE
Cross Region Restore az cli

### ISSUE THREAD

**Issue by ggg333** [Azure/azure-cli#13779]
Don't see the option for enabling the "Cross Region Restore" on azure cli. Is that something that will be added? or if its already there can someone point me in the right direction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27d97953-c8f5-32e0-f88b-9714b28b89f2
* Version Independent ID: c33a9ee8-4f89-31ce-799c-b5c437eeca7a
* Content: [az backup job](https://docs.microsoft.com/en-us/cli/azure/backup/job?view=azure-cli-latest#az-backup-job-list)
* Content Source: [src/azure-cli/azure/cli/command_modules/backup/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/backup/_help.py)
* Service: **backup**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
backup

**Comment by pvrk** [comment]
@ggg333 : Since the feature is currently in preview, we don't have options for CLI yet. Current plan is to provide around Sept end.

**Comment by pvrk** [comment]
Closing this issue since this is a planned item.

**Comment by pvrk** [comment]
We have a parameter "--cross-region-restore-flag" as a parameter to ```az backup vault backup-properties set``` command
