### ISSUE TITLE
[Discussion] Would it be valuable to allow configuring a default resource group?

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1377]
I wonder whether it wouldn't be valuable to allow users to configure a default resource group, either per-user, per-shell or per-directory (via some kind of config file), and would take effect for all commands where a resource group wasn't explicitly specified. I've seen this kind of behavior provided by other CLIs, with the goal of reducing the number of repetitive parameters, especially if they don't change frequently or are context-sensitive (e.g. can be derived via a config file in the CWD).

I'm not entirely sure how devs use resource groups in the wild, but it seems like it could be a useful simplification of their workflow by being able to configure a resource group for a session, project, etc. and then omit it from there on out. That way the CLI can strike a balance between flexibility and verbosity.

**Comment by joshgav** [comment]
I've been working with the CLI and have the same feedback - it's not the best experience to have to repeatedly specify `--resource-group` or `-g`, especially interactively. FWIW, the same goes for specifying a name in subgroups, e.g. continually specifying the web app name in the appservice commands.

Perhaps an env var could address this too, like AZURE_CLI_RESOURCE_GROUP, and/or part of the `configure` commands, which could write to local or global dotfiles as @lostintangent suggested.

#1102 is somewhat related.

**Comment by yugangw-msft** [comment]
//CC: @johanste @mayurid
CRP folks also provided the similar feedback. I suggest we should do it. Johan, please feel free to fold under other general issues as long as we communicate whether we will take this feedback or not.
I am moving this issue to sprint 12 so we can at least triage

**Comment by johanste** [comment]
I 100% agree that it would be very beneficial to have a generic mechanism for specifying default values for parameters in general. Resource group, location, web app, SQL server are all things that service teams have asked for. 

Today, we have somewhat ad-hoc mechanisms such as the storage default environment variables that we've inherited from the Azure CLI 1.0/xplat CLI. 

I'll take a stab at writing up a proposal.

**Comment by mayurid** [comment]
Moving out of current sprint to the next. Will work with Johan to make sure we have a proposal out for discussion in upcoming sprint.

**Comment by yugangw-msft** [comment]
Thanks for all the feedback. PR #2414  was merged. 
You can use `az configure --defaults group=<name>` to configure a default group. Later you can clear it up with `''`. There are a few other configurable names available, like `location`, `vm`, `vmss`, `web`. 
You can also use env variable of `AZURE_DEFAULTS_GROUP`, because CLI has integration between env vars and config file through the mapping of `AZURE_<SECTION>_<VAR>`
The PR's main goal was to introduce a general mechanism, so new arguments can be configured easily moving forward. 
(For reference)
 ```bash
C:\SDK\azure-cli>az configure -h
...
    --defaults : Space separated 'name=value' pairs for common arguments defaults, e.g. '--defaults
                 group=myRG web=myweb vm=myvm'. Use '' to clear the defaults, e.g. --defaults vm=''
                 web=''.
```

**Comment by lostintangent** [comment]
@yugangw-msft Thanks! Is there a way from the CLI to view the current defaults? Or do you need to open the underlying config file?

**Comment by yugangw-msft** [comment]
Running `az configure` (w/o any parameters) should list the contents.
