### ISSUE TITLE
[Resources] `az resource create` should use the latest api-version if unspecified

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#13770]
**Is your feature request related to a problem? Please describe.**
 
When `az resource create` is called without `--api-version`, it will query the resource provider and use the **latest GA version**: 

https://github.com/Azure/azure-cli/blob/88480669cdd65e3a715c6fa527c479ed4b4436a0/src/azure-cli/azure/cli/command_modules/resource/custom.py#L2709-L2710

On the other hand, the public documentation only shows the latest `api-version`, including `preview`. For example, [Environments - Create Or Update](https://docs.microsoft.com/en-us/rest/api/time-series-insights/management/environments/createorupdate) only shows `api-version=2018-08-15-preview`.

This causes issue https://github.com/Azure/azure-cli/issues/13503: When `az resource create` is called without `--api-version`, it uses the GA version `2017-11-15` which doesn't comply with `2018-08-15-preview` in the public doc.

**Describe the solution you'd like**

`az resource create` should use the latest api-version if unspecified.

**Describe alternatives you've considered**

Keep this inconsistent behavior.

**Additional context**

FYI, this is the query done by `az resource create`:

```http
GET https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.TimeSeriesInsights?api-version=2019-07-01
{
  "authorizations": [
    {
      "applicationId": "120d688d-1518-4cf7-bd38-182f158850b6",
      "roleDefinitionId": "5a43abdf-bb87-42c4-9e56-1c24bf364150"
    }
  ],
  "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.TimeSeriesInsights",
  "namespace": "Microsoft.TimeSeriesInsights",
  "registrationPolicy": "RegistrationRequired",
  "registrationState": "Registered",
  "resourceTypes": [
    {
      "apiVersions": [
        "2018-08-15-preview",
        "2017-11-15",
        "2017-02-28-preview"
      ],
      "capabilities": "CrossResourceGroupResourceMove, CrossSubscriptionResourceMove, SupportsTags, SupportsLocation",
      "locations": [
        "South Central Us",
        "East US 2",
        "West US",
        "East US",
        "North Europe",
        "West Europe",
        "West US 2",
        "Central US",
        "Southeast Asia",
        "Australia East",
        "Australia Southeast",
        "East Asia",
        "UK West",
        "UK South"
      ],
      "resourceType": "environments"
    },
    ...
```

**Comment by yonzhan** [comment]
add to S172
