### ISSUE TITLE
Grant command not working

### ISSUE THREAD

**Issue by srudin** [Azure/azure-cli#13788]
I'm creating a new app registration:
`az ad app create --display-name $Name --oauth2-allow-implicit-flow $true`

Then I add the User.ReadBasic.All permission:
`az ad app permission add --id $BackendAppId --api "00000003-0000-0000-c000-000000000000" --api-permissions "e1fe6dd8-ba31-4d61-89e7-88639da4683d=Scope"`

It then shows the following message:
`Invoking "az ad app permission grant --id $BackendAppId --api 00000003-0000-0000-c000-000000000000" is needed to make the change effective`

However if I run this command it says:
`Operation failed with status: 'Not Found'. Details: 404 Client Error: Not Found for url: https://graph.windows.net/{GUID}/oauth2PermissionGrants?$filter=clientId%20eq%20%{GUID}%27&api-version=1.6`

1. I can see the permission in the portal ui and can use it in my app. So **what do I need the grant command for**?
2. If I need it what do I have to do to make it work?
3. Only problem I can see is that when rerunning the commands above **I get the same permission listed twice** in the portal api. Is this related to the failing grant command? If not how can I avoid multiplied permission entries?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5b5348-f67e-ef14-0529-4c80fddd4bc6
* Version Independent ID: bfd7e6b1-1fba-3d25-8ee3-5105bcf4157d
* Content: [az ad app permission](https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest#az-ad-app-permission-grant)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@arrownj  please take a look

**Comment by srudin** [comment]
Any news on this?

**Comment by arrownj** [comment]
Hi @srudin , this issue will be fixed in our next release.

**Comment by arrownj** [comment]
Hi @srudin , sorry for late reply. For you case, you need to create a service principal for the application after you create it. The commands should be like this:

>az ad app create --display-name $Name --oauth2-allow-implicit-flow $true

>az ad sp create --id $BackendAppId

>az ad app permission add --id $BackendAppId --api "00000003-0000-0000-c000-000000000000" --api-permissions "e1fe6dd8-ba31-4d61-89e7-88639da4683d=Scope"
> ......

**Comment by arrownj** [comment]
Close this first as it's a usage issue.

**Comment by srudin** [comment]
Didn't see your answer sorry. Seems like I'm not getting notifications from github, need to check.

So I added the az add sp create command and I end up with exactly the same behaviour. The additional command succeeds, but I still get the same messages and failures as described above.
