### ISSUE TITLE
Issue about Listing the Non-compliant Resources for Management group scope

### ISSUE THREAD

**Issue by Mounika-M776** [Azure/azure-cli#13784]
Hi Team,

I'm looking for the AZ-CLI command for the Non-compliant resources list of the Management group scope. I was using the below cmd but it has the no. limit. Is there any possible way to list the huge no. of non-complaint resources for the particular scope?
az policy state list -m "Scope" --query "[?complianceState=='NonCompliant' && policyDefinitionName=='XXXX'].{ResourceID:resourceId,ResourceType:resourceType}" --output table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca46c96d-8c88-7c4a-d75f-1c6c45d0f75c
* Version Independent ID: 9b8bdef9-8f67-7e82-1ae8-9356b62e84b0
* Content: [az policy state](https://docs.microsoft.com/en-us/cli/azure/policy/state?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
@Mounika-M776 Hi, in fact, the `--management-group\-m` parameter can specify the scope of management group
```
--management-group -m      : Name of management group.
```
It seems that your usage is correct:
> az policy state list -m "Scope" --query "[?complianceState=='NonCompliant' && policyDefinitionName=='XXXX']

The problem now is that you use `-m` but it doesn't have the effect of limiting management group?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
