### ISSUE TITLE
az managedapp create --tags not working

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-cli#13786]
## Describe the bug
When attempting to create a managedapp with the `--tags` parameter, we get the following error:
`Parameter 'tags' must be of type '{str}'`

Have tried variations of:
`'a=b'`
`"a=b"`
`'a'='b'`
`"a"="b"`
`{'a':'b'}`

**Command Name**
`az managedapp create`

**Errors:**
```
validation error: Parameter 'tags' must be of type '{str}'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az managedapp create --kind {} --managed-rg-id {} --name {} --resource-group {} --location {} --managedapp-definition-id {} --subscription {} --parameters {} --tags {}`

## Expected Behavior
Command to validate and work

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.6.0 *

```

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
@wahyuen Hi, could you please show me the specific parameters you used? please add `--debug` to the original command and email the printed information to me~
My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by wahyuen** [comment]
@zhoxing-ms I've emailed the output to yourself

**Comment by zhoxing-ms** [comment]
@wahyuen Thank you for your feedback. I have located the problem and will submit a PR to fix it
