### ISSUE TITLE
az cosmosdb check-name-exists too many 500 error responses

### ISSUE THREAD

**Issue by findemor** [Azure/azure-cli#13792]
## Describe the bug

**Command Name**
`az cosmosdb check-name-exists`

**Errors:**
```
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /providers/Microsoft.DocumentDB/databaseAccountNames/dev-db-account-ms-esb?api-version=2020-03-01 (Caused by ResponseError('too many 500 error responses',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
- `az cosmosdb check-name-exists --name dev-db-account-ms-esb`

## Expected Behavior

true or false is returned without error

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.7.0

```
## Additional Context

This issue is happening in our GitLab-ci DevOps pipelines and in my local setup.
I tried login with "az login" manually and with pregenerated service principal credentials.

I noticed it while I was trying to launch my Terraform plan, this error ocurred and then I tried to debug it:

```
2020/06/02 11:37:09 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error checking if CosmosDB Account "ACCOUNTNAME" already exists (Resource Group "RESOURCEGROUPNAME"): documentdb.DatabaseAccountsClient#CheckNameExists: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF

Error: Error checking if CosmosDB Account "ACCOUNTNAME" already exists (Resource Group "RESOURCEGROUPNAME"): documentdb.DatabaseAccountsClient#CheckNameExists: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF

  on main.tf line 40, in resource "azurerm_cosmosdb_account" "db":
  40: resource "azurerm_cosmosdb_account" "db" {
```

In terraform, I am using version 2.12

provider "azurerm" {
  subscription_id = var.SUBSCRIPTION_ID
  tenant_id       = var.SERVICEPRINCIPAL_TENANT_ID
  client_id       = var.SERVICEPRINCIPAL_CLIENT_ID
  client_secret   = var.SERVICEPRINCIPAL_CLIENT_SECRET

  version = "= 2.12"
  features {}
}

**Comment by yonzhan** [comment]
cosmosdb

**Comment by vaughanh1** [comment]
This is occurring in my terraform script with the same issue (only since yesterday morning, using GMT timezone). I did not do any version changes, it just stopped working. I am trying to create a cosmos DB and this check is performed by default before creation is possible. It tries for several minutes and then fails with the error above. A cosmos DB cannot be created using a terraform script, but it can be created using the Azure portal.

**Comment by YKJumper** [comment]
I faced with the similar issue:

provider "azurerm" {
  version = "=2.12.0"

  subscription_id = var.azurerm_subscription_id
  tenant_id       = var.azurerm_tenant_id
  client_id       = var.azurerm_client_id
  client_secret   = var.azurerm_client_secret

  features {}
}

Terraform output:
...
...
module.identity.module.identity_management.azurerm_cosmosdb_account.cosmosdb_account: Still creating... [7m20s elapsed]
module.identity.module.identity_management.azurerm_cosmosdb_account.cosmosdb_account: Still creating... [7m30s elapsed]

Error: Error checking if CosmosDB Account "cosmos-interviews-yk01" already exists (Resource Group "rg-interviews-yk01"): documentdb.DatabaseAccountsClient#CheckNameExists: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF

  on ..\..\service\interviews_service\main.tf line 342, in resource "azurerm_cosmosdb_account" "cosmosdb_account":
 342: resource "azurerm_cosmosdb_account" "cosmosdb_account" {

**Comment by vaughanh1** [comment]
FYI: Using different versions of the Azure CLI makes no difference. Exactly the same error is provided every time, always after 7m30 elapsed.

**Comment by KennethFelber** [comment]
I've had this error for the last three days also.

**Comment by saigutta** [comment]
I am also facing this issue with same error.

**Comment by vaughanh1** [comment]
FYI. It is not related to a proxy server as I have the same problem when not behind a proxy.

**Comment by shurd** [comment]
Hi all thank you for opening this issue. We are tracking a fix with deployment ETA of today.

**Comment by vaughanh1** [comment]
Seems it is being tracked here: [https://github.com/terraform-providers/terraform-provider-azurerm/issues/7173](url)

**Comment by shurd** [comment]
As noted in that issue, the fix was deployed yesterday.
