### ISSUE TITLE
[CosmosDB] MongoDB API doesn't support creation of fixed collections

### ISSUE THREAD

**Issue by MehaKaushik** [Azure/azure-cli#13797]
**Resource Provider**

**Description of Feature or Work Requested**
<Although the CosmosDB RP supports creation of fixed collections, CLI doesn't, which is an inconsistent behavior.>

**Minimum API Version Required**
<Current CLI>

**Swagger Link**

**Target Date**

**Comment by MehaKaushik** [comment]
Targeting [S171](https://github.com/Azure/azure-cli/issues/13797)

**Comment by yungezz** [comment]
set S171 milestone

**Comment by MehaKaushik** [comment]
https://github.com/Azure/azure-cli/pull/13950

Merged and released.
