### ISSUE TITLE
CLI inconsistency -- to specify a parameters file, one must not use equal sign

### ISSUE THREAD

**Issue by jmspring** [Azure/azure-cli#1379]
If you use an equal sign between --parameters and the actual file path, you end up with the following:

```
az resource group deployment create --resource-group=jmsdcosrg --template-file=./output/azuredeploy.json --parameters="@./output/azuredeploy.parameters.json"
No JSON object could be decoded
```

Removing the equal sign works:

```
az resource group deployment create --resource-group=jmsdcosrg --template-file=./output/azuredeploy.json --parameters "@./output/azuredeploy.parameters.json"
```

**Comment by brendandburns** [comment]
The reason for this is that the console sees --flag=<expr> as a single string, and the console is the thing that interprets the '@'

I guess the right answer is to detect the @ at the beginning of a string and then inline the file?

**Comment by jmspring** [comment]
Thanks @brendandburns -- for me it is an issue of consistency.  It took me awhile to figure out what was going on... The az command line help mentions "add an @ for files" (or close to that).  Not sure why for `az resource group deployment create ....` there is --template and --template-file, but only --parameters.
