### ISSUE TITLE
repeat command execution: az appconfig kv set-keyvault 

### ISSUE THREAD

**Issue by motycak** [Azure/azure-cli#13800]
Describe the bug:
I need to rewrite (update) the vault reference from the powershell in the app configuration key.
When I run the command repeatedly:

az appconfig kv set-keyvault --name $appConfigurationName --key $keyAppConfiguration --secret-identifier $secretIdentifier --yes

Azure return:
az : This operation will result in overwriting existing key whose value is: {"uri":"https://xxxxxxxxx.vault.azure.net/secrets/xxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
At C:\MyPathToPowershelScript.ps1:29 char:5
+     az appconfig kv set-keyvault --name $appConfigurationName --key $ ...
+     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (This operation ...73896fd3eba2e"}:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

How can I rewrite in app configuration without exception?

**Comment by yonzhan** [comment]
appconfig

**Comment by shenmuxiaosen** [comment]
Hi, thanks for reporting the bug. We will have a fix to remove the unnecessary warning as we do ask for confirmation before setting the key vault reference (can be turned off by ```--yes```). As of now, if the warning is bothering you, you can try a global argument ```--only-show-errors``` to suppress the log level to error. 

It will be something like 
```az appconfig kv set-keyvault --name $appConfigurationName --key $keyAppConfiguration --secret-identifier $secretIdentifier --yes --only-show-errors```

**Comment by PramodValavala-MSFT** [comment]
@motycak This has since been implemented. We are closing this issue.
