### ISSUE TITLE
[App Service] The list-locations command's table output seems overly verbose

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1380]
If you run `az appservice list-locations -otable`, the output includes three columns, all of which seem to provide the exact same value. Not a blocker by any means, but it seems unnecessarily noisy, as opposed to providing the user with just the unique information needed (e.g. the `Name` column?)

<img width="418" alt="screen shot 2016-11-18 at 11 32 39 am" src="https://cloud.githubusercontent.com/assets/116461/20443702/c5b3baa4-ad82-11e6-8196-19f2ac834694.png">

**Comment by mayurid** [comment]
@derekbekoe: Thoughts? I know we curate the table output for some cases and wonder if we can do better here?
@lostintangent : What fields would you like to see or would make sense?
//cc @yugangw-msft:
