### ISSUE TITLE
can't delete virtual node addon from aks. get error msg --The addon aciConnectorLinux is not installed.

### ISSUE THREAD

**Issue by rbankole** [Azure/azure-cli#13807]
Describe the bug
Can't remove the virtual-node addon. exits with error message "The addon aciConnectorLinux is not installed."

To Reproduce
Steps to reproduce the behavior.

Create an AKS cluster, and enable the virtual-node.

Run az aks disable-addons --resource-group usnc-rg-aks-tools --name usnc-aks-tools --addons virtual-node
It returns "The addon aciConnectorLinux is not installed."

**Expected behavio**r

The addon should be removed.

**Environment summary**
az version
{
  "azure-cli": "2.7.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.7.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.35"
  }
}

**Comment by yonzhan** [comment]
AKS

**Comment by djsly** [comment]
could you share your json of your cluster using resources.azure.com to ensure that the add-on was indeed present ?

Also, which versions of AKS are you targeting ?

**Comment by navba-MSFT** [comment]
@rbankole Apologies for the late reply. Could you please confirm if you are still running into this issue ? This issue is open for quite sometime. Please let us know if you need any further assistance on this.
