### ISSUE TITLE
Unable to set IP Address Type with ACI

### ISSUE THREAD

**Issue by hjfitz** [Azure/azure-cli#13802]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When attempting to deploy an Azure Container Instance to a Virtual Network, I am unable to set the IP Address Type to "Private" with the `--ip-address Private` flag.

**To Reproduce**
Run the following script:
```sh
az container create \
--ip-address Private \
--resource-group modern.sftp.test \
--name hjfmodsftp \
--image atmoz/sftp:latest \
--dns-name-label hjfmodsftp \
--ports 22 \
--vnet sftp-virtual-network \
--subnet default \
--azure-file-volume-account-name dedicatedsftpstorage \
--azure-file-volume-account-key FSyB1JUtqEZA0+8s8b+N4SMjTkrTVPGT84/ejeN5tbNPgtmy6tNfgeuuoso6g4M7JOg4XbrGo9txLnA08yHuhQ== \
--azure-file-volume-share-name persistent-sftp \
--azure-file-volume-mount-path /aci/logs/ 
```

**Expected behavior**
The container should deploy. Instead, I get the error message:
`IP Address type can't be public when network profile is set.`

**Environment summary**
* Shell: ZSH 5.7.1
* OS: MacOs 10.15.3
* CLI Version: 2.0.77 (code)

**Additional context**
none

**Comment by yonzhan** [comment]
container

**Comment by hjfitz** [comment]
This turned out to be a user issue. You can't use `--dns-name-label $name \` as a container can't be on a private network with a public FQDN! Remove that from the original command and it works

**Comment by alexlydiate** [comment]
That's not a user issue - the error message is incorrect.

**Comment by Steiniche** [comment]
I agree with @alexlydiate the error message could definitely be improved.
