### ISSUE TITLE
az login failure

### ISSUE THREAD

**Issue by asranja** [Azure/azure-cli#13801]
## Describe the bug

**Command Name**
`az login`

**Errors:**
While trying to login from the browser, I am getting the below error:

An error occurred
Please close and try again in a new window. Contact helpdesk if the issue persists.
Error details
Activity ID: bacd293e-0bd5-40c2-a954-9f0c9a546689
Error details: MSIS7007: The requested relying party trust 'urn:federation:microsoftonline.us' is unspecified or unsupported. If a relying party trust was specified, it is possible that you do not have permission to access the trust relying party. Contact your administrator for details.
Node name: 45ebeee1-1289-4014-92b3-fb2c6db6da2b
Error time: Wed, 03 Jun 2020 07:16:14 GMT
Cookie: enabled
User agent string: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
- `az login` with @microsoft.com account

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.7.0
```

**Comment by yonzhan** [comment]
add to S171

**Comment by asranja** [comment]
@yonzhan @qianwens Any pointers here will be highly appreciated.

**Comment by yonzhan** [comment]
This issue was planned in this Sprint. @qianwens will help you.

**Comment by qianwens** [comment]
@asranja , is this error only happen in Azure CLI? Can you login in from azure portal?

**Comment by asranja** [comment]
Yes, I can login from Azure portal and Azure PowerShell. 

I tried ```az login``` again and got the same error:

An error occurred
Please close and try again in a new window. Contact helpdesk if the issue persists.
Error details
Activity ID: 3221e202-e5ca-4033-8a22-2667d7a83f72
Error details: MSIS7007: The requested relying party trust 'urn:federation:microsoftonline.us' is unspecified or unsupported. If a relying party trust was specified, it is possible that you do not have permission to access the trust relying party. Contact your administrator for details.
Node name: a0d10289-f14e-424f-9cb7-6bf6e121a1df
Error time: Thu, 18 Jun 2020 09:32:40 GMT
Proxy server name: cy***33
Cookie: enabled
User agent string: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36

**Comment by bishal-pdMSFT** [comment]
I am facing same problem with my @microsoft.com account. Issues happen only when doing `az login`, and portal login works fine.

**Comment by jiasli** [comment]
@asranja @bishal-pdMSFT could you please share me the `--debug` log to my Microsoft email (same as my GitHub user name)?

**Comment by jiasli** [comment]
As this only happens for `microsoft.com` accounts. Please reach me internally on **Microsoft Teams** and we can set up a Teams meeting to troubleshoot together.
