### ISSUE TITLE
error

### ISSUE THREAD

**Issue by satish61** [Azure/azure-cli#13809]
## Describe the bug

**Command Name**
``

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1 *

```

**Comment by yonzhan** [comment]
Please share detailed command and related error info.

**Comment by yungezz** [comment]
hi @satish61 could you pls share error detail for investigation?

**Comment by satish61** [comment]
This ticket can be closed. I opened it in another browser and it worked.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
