### ISSUE TITLE
Unexpected error az webapp up

### ISSUE THREAD

**Issue by mohitmehau** [Azure/azure-cli#13805]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
Expecting ',' delimiter: line 8 column 5 (char 139)
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 686, in _run_job
    cmd_copy.exception_handler(ex)
...
lib/python3.6/json/__init__.py, ln 354, in loads
    return _default_decoder.decode(s)
lib/python3.6/json/decoder.py, ln 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.6/json/decoder.py, ln 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 8 column 5 (char 139)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --name {} --resource-group {} --plan {} --sku {} --location {}`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1 *

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@mohitmehau thanks for reporting. Are you seeing this error with az webapp up command only or with other commands as well - a quick look at the trace makes it look like a problem with the CLI deployment package instead of being specific to the command. Please let us know. Thanks.

**Comment by panchagnula** [comment]
closing due to lack of response.
