### ISSUE TITLE
Retrying role assignment creation: 1/36

### ISSUE THREAD

**Issue by eliassal** [Azure/azure-cli#13803]
**Describe the bug**
I try to create a SP with the following command 
az ad sp create-for-rbac --name TTapp1 --scopes $(az acr show --name $ACR_NAME --query id --output tsv) --role acrpull --query password --output tsv
I always get the following output which really can not be understood what does it mean!!
![RBAC](https://user-images.githubusercontent.com/8447864/83631835-74ba3e80-a59e-11ea-91f2-d964a57716e5.jpg)

I switch to Azure, I see the SP created in the container registory as if there was no error. The 1st problem is that I need to get back the password. The 2nd this command creates a SP and a ssighns a random passwor with caracters that are not allowed to be used in some places such as variables in AzureDevops pipeline

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by eliassal** [comment]
hi yonzhan, take a look at what?

**Comment by yonzhan** [comment]
@eliassal  assigned to look at your issue.

**Comment by eliassal** [comment]
Oh thanks, I misunderstood

**Comment by arrownj** [comment]
Hi @eliassal ,

>+CategoryInfo          : NotSpecified: (:String) [], RemoteException
+FullyQualifiedErrorId : NativeCommandError

is an error reported by powershell, it must have something to do with your local environment. I also tried the same command you give in my environment, it succeed with no errors. Could you please also run the command in cmd or other terminal to see whether it has the same problem? Thanks

**Comment by arrownj** [comment]
Hi @eliassal , close this as it is not CLI command issue. If you have other concerns, you can submit a new one.
