### ISSUE TITLE
az ad sp create-for-rbac : password contains illegal characters

### ISSUE THREAD

**Issue by eliassal** [Azure/azure-cli#13804]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Creating a SP with create-for-rbac  generates a random password, such as 
Mn*N7DAyZBw@6(TN^(xDT/w$zAf_:9EG

In some places, this password does not go through (for example in Azuredevops pipelines or releases)

Even when I try to login from powershell it does not go through (I changed appid and tenantid for security the password is the right one)

az login --service-principal -u 1064d1dc-6b80-47de-8bdf-1899cd81685c --password='Mn*N7DAyZBw@6(TN^(xDT/w$zAf_:9EG' --tenant 8867c70e-3abc-4e99-af13-87bv165fd4a5 
I get

az : Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid 
client secret is provided.\r\nTrace ID: c1f0b5cb-43fd-460f-80d3-c0c7bb19d300\r\nCorrelation ID: 
2000aa90-1d2b-4114-826f-d6972088743f\r\nTimestamp: 2020-06-03 12:07:59Z","error_codes":[7000215],"timestamp":"2020-06-03 12:07:59Z","trace_id":"c
1f0b5cb-43fd-460f-80d3-c0c7bb19d300","correlation_id":"2000aa90-1d2b-4114-826f-d6972088743f","error_uri":"https://login.microsoftonline.com/error
?code=7000215"}
At line:1 char:1
+ az login --service-principal -u 1064d1dc-6b80-47de-8bdf-1899cd81685c  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Get Token reque...?code=7000215"}:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by eliassal** [comment]
Also, can you please tell me what is the az command to change the SP password? is it feasible? I udnerstand that we can do a reset but I am not sure if it is useful? I need to enter a legal password in my AzureDevops pipeline in order to make it go through. Here is the error when running the pipeline


> 2020-06-03T12:04:48.6132863Z [command]/usr/bin/az account set --subscription f151ee3f-......-0........-8e3b0......df......
> 2020-06-03T12:04:49.4430349Z [command]/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/home/vsts/work/_temp/azureclitaskscript1591185869298.ps1'
> 2020-06-03T12:05:00.8017305Z At /home/vsts/work/_temp/azureclitaskscript1591185869296_inlinescript.ps1:1 char:180
> 2020-06-03T12:05:00.8024596Z + … 5d1dc-3b80-40de-8bdf-1899cd81682d -p ***
> 2020-06-03T12:05:00.8025237Z +                                                                        ~
> 2020-06-03T12:05:00.8027981Z Missing closing ')' in expression.
> 2020-06-03T12:05:00.8028576Z + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
> 2020-06-03T12:05:00.8029075Z + FullyQualifiedErrorId : MissingEndParenthesisInExpression
> 2020-06-03T12:05:00.8194283Z ##[error]Script failed with exit code: 1
> 2020-06-03T12:05:00.8263971Z [command]/usr/bin/az account clear

**Comment by eliassal** [comment]
So it indicates "MissingEndParenthesisInExpression" because of the password

> Mn*N7DAyZBw@6(TN^(xDT/w$zAf_:9EG

as it has an opening Parenthesis

**Comment by yonzhan** [comment]
add to S171

**Comment by qianwens** [comment]
This issue has been fixed in https://github.com/Azure/azure-cli/pull/13643 . Please help install the latest version to solve this problem.

**Comment by eliassal** [comment]
Hi qianwens, what latest version and where I can get it? do you mean Azure powershell?

**Comment by yonzhan** [comment]
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

**Comment by eliassal** [comment]
OK I updated my az-cli to 2.7, can I update the passwor for the user in Azure? If yes, how?

**Comment by qianwens** [comment]
@eliassal , you can update the password with `az ad credential reset` https://docs.microsoft.com/en-us/cli/azure/ad/sp/credential?view=azure-cli-latest#az-ad-sp-credential-reset
