### ISSUE TITLE
parameter "ssh-key-value" replacing instead of appendind

### ISSUE THREAD

**Issue by rg54** [Azure/azure-cli#13810]
Hello,

It seems to have an error in this section with parameter "--ssh-key-value" : it is described as appending the SSH public key in user ".ssh/authorized_keys"

But I've tested it today, with this syntax :
az vm user update -u [UserName] --ssh-key-value "[SSH public key]" -n [VM name] -g [RG name]

and in fact, this command have replaced public key value in ".ssh/authorized_keys"

Tested with AZ CLI version 2.1.0

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0474c5a5-4231-0e39-f63f-f7bc05cb7797
* Version Independent ID: 22ea94c8-cc6f-97aa-77b1-4ffca845807e
* Content: [az vm user](https://docs.microsoft.com/en-us/cli/azure/vm/user?view=azure-cli-latest#az-vm-user-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by rg54** [comment]
I've tested and checked again, and I made a mistake the first time (two different accounts with only case differences in login). So the doc is OK, public keys are appended and not replaced.

Sorry for the inconvenience
