### ISSUE TITLE
az storage blob upload fails

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-cli#13814]
## Describe the bug

**Command Name**
`az storage blob upload -f {} --name {} -c {} --auth-mode login` fails, complaining about the authentication.

however `az storage blob list --account-name {} -c runners --prefix {} --auth-mode login` works with no issues. as per documentation upload should also support auth-mode login. 

**Errors:**
```bash
Missing credentials to access storage service. The following variations are accepted:
    (1) account name and key (--account-name and --account-key options or
        set AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY environment variables)
    (2) account name and SAS token (--sas-token option used with either the --account-name
        option or AZURE_STORAGE_ACCOUNT environment variable)
    (3) account name (--account-name option or AZURE_STORAGE_ACCOUNT environment variable;
        this will make calls to query for a storage account key using login credentials)
    (4) connection string (--connection-string option or
        set AZURE_STORAGE_CONNECTION_STRING environment variable); some shells will require
        quoting to preserve literal character interpretation.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload -f {} --name {} -c {} --auth-mode login`

## Expected Behavior
`auth-mode login` should work for blob upload

## Environment Summary
```
macOS-10.15.4-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.7.0

```

**Comment by yonzhan** [comment]
add to S172

**Comment by moderakh** [comment]
any update on this issue? @yonzhan @zhinlu

**Comment by moderakh** [comment]
resolved.
