### ISSUE TITLE
az login doesn't take --only-show-errors

### ISSUE THREAD

**Issue by JimKCode** [Azure/azure-cli#13818]
The page says the global param --only-show-errors works with az login.  It does not.

az login --only-show-errors
az: error: unrecognized arguments: --only-show-errors
usage: az [-h] [--verbose] [--debug]
          [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
          {login} ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeedb9a7-2aed-6727-4cfb-1515809d676e
* Version Independent ID: 2c83180d-22ad-db42-e2eb-f27f11977963
* Content: [az](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/profile/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/profile/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S171

**Comment by jiasli** [comment]
`--only-show-errors` was introduced in [2.3.0](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/HISTORY.rst#230). Please make sure you are using the latest version of Azure CLI.
