### ISSUE TITLE
Application Gateway PrivateLink :  CLI Support

### ISSUE THREAD

**Issue by jaishals** [Azure/azure-cli#13819]
**Resource Provider**

Microsoft.Network

**Description of Feature or Work Requested**

The feature will enable customers to enable private link support on application gateway. 
The feature needs a new child property of application gateway called PrivateLinkConfigurations which customers can configure. 

Also a private link configuration can be associated with FrontendIpConfiguration on application gateway.

CLI support will be needed for enabling this property on application gateway

Further more, since private link is azure wide supported feature , application gateway has onboarded on to it. Common CLI commands which are common to all private link providers need to support application gateway

Link to Design doc
https://microsoft.sharepoint.com/:w:/r/teams/WAG/AzureNetworking/Engineering%20Q%20%20Z/VirtualAppliance/AppGateway/Design/Private%20Link%20on%20Application%20Gateway.docx?d=w9c02265291f74f40857df6ed7eecc274&csf=1&web=1&e=OUVGFd

Please engage me for any questions.

**Minimum API Version Required**

Swagger May release (2020-05-01)

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/9490

**Target Date**

June end would a good goal

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172

**Comment by haroldrandom** [comment]
@jaishals questions:
1. Does AppGw need to set PrivateLinkConfigurations before seting a private endpoint?
2. Is AppGw able to update PrivateLinkConfigurations after an AppGw is created? 
3. Is AppGw able to update PrivateLinkConfigurations after it's associated with a private endpoint？
