### ISSUE TITLE
[App Service] Creating a plan requires a SKU, but its help text indicates it has a default value

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1381]
If you run `az appservice plan create -h`, the `--sku` parameter indicates that it is both required, and has a default value at the same time. Does that make sense? When running the command, it definitely requires the `--sku` flag, so the mandatory nature is currently enforced. I'm just curious whether the default value is a bug that should be removed from the help text, or if there is an actual default value, whether the required nature of the flag should be lifted?

<img width="667" alt="screen shot 2016-11-18 at 11 40 31 am" src="https://cloud.githubusercontent.com/assets/116461/20444011/2f4c8a58-ad84-11e6-8d96-f6bfdcd6cf51.png">

**Comment by mayurid** [comment]
You are right.. created a PR to make this optional https://github.com/Azure/azure-cli/pull/1383

**Comment by lostintangent** [comment]
@mayurid Awesome, thanks!
