### ISSUE TITLE
az vmss create NoneType error

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#13812]
## Describe the bug
Trying to create a VMSS - not sure what the error is here
**Command Name**
`az vmss create`

**Errors:**
az vmss create: error: 'NoneType' object has no attribute 'split'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss create -n {} -g {} --image {} --lb-sku {} --public-ip-per-vm -l {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1 *

Extensions:
interactive 0.4.3

```

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by qwordy** [comment]
Could you please add `--debug` parameter and paste the output here?
Something is unexpectedly None according to the error message.

**Comment by qwordy** [comment]
@fitzgeraldsteele Any update?

**Comment by qwordy** [comment]
Any update?

**Comment by yungezz** [comment]
#14287

**Comment by qwordy** [comment]
Close it for no reply.
