### ISSUE TITLE
Support for IPGroups on Firewall policy

### ISSUE THREAD

**Issue by tejasshah7** [Azure/azure-cli#13811]
**Resource Provider**
Network (NRP)

**Description of Feature or Work Requested**
There are 3 changes needed. Two of them are for following command:
az network firewall policy rule-collection-group collection rule add --collection-name
                                                                     --name
                                                                     --policy-name
                                                                     --resource-group
                                                                     --rule-collection-group-name
                                                                     --rule-type {ApplicationRule, NetworkRule}
                                                                     [--description]
                                                                     [--destination-addresses]
                                                                     [--destination-ports]
                                                                     [--fqdn-tags]
                                                                     [--ip-protocols {Any, ICMP, TCP, UDP}]
                                                                     [--protocols]
                                                                     [--source-addresses]
                                                                     [--target-fqdns]

1. For rule-type ApplicationRule, need to add following new optional field:
[--source-ip-groups]

This field is similar to the one in "az network firewall application-rule create" command.

2. For rule-type NetworkRule, need to add following 2 new optional fields:
[--source-ip-groups]
[--destination-ip-groups]

These fields are similar to the ones in "az network firewall network-rule create" command.

3. There is an outstanding request to create a new command for creating a NAT rule like Network and Application Rule above. Here is the open request:
https://github.com/Azure/azure-cli/issues/13629

In there for NAT Rule too, we will need to support:
[--source-ip-groups]

This field is similar to the one in "az network firewall nat-rule create" command.

**Minimum API Version Required**
2020-05-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/8477

**Target Date**
Jun 23, 2020

**Comment by yonzhan** [comment]
add to S172

**Comment by ssripadham** [comment]
When does S172 release?

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/milestone/90    Build to Cloud Shell: 07/10/2020 Official Release: 07/14/2020

**Comment by tejasshah7** [comment]
Why was this release pushed out? Our GA release was this week. With this being pushed out, it would impact our GA.
