### ISSUE TITLE
Unable to Add Network Rule to CosmosDb

### ISSUE THREAD

**Issue by sireza** [Azure/azure-cli#13820]
## Describe the bug

**Command Name**
`az cosmosdb network-rule add`

**Errors:**
```
'NoneType' object has no attribute 'virtual_network_rules'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 325, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 545, in default_command_handler
    return op(**command_args)
cli/command_modules/cosmosdb/custom.py, ln 955, in cli_cosmosdb_network_rule_add
    for rule in existing.virtual_network_rules:
AttributeError: 'NoneType' object has no attribute 'virtual_network_rules'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
- `az cosmosdb network-rule add --name {} --subnet {} -g {}`

## Expected Behavior

Network rule for the vnet added successfully 

## Environment Summary
```
macOS-10.15.4-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.7.0

Extensions:
image-copy-extension 0.2.1

```

**Comment by yonzhan** [comment]
cosmosdb

**Comment by shurd** [comment]
Hi @sireza thank you for opening this issue. I was able to reproduce this error, but only by targeting a non-existent account. Can you please ensure that the resource group name and the account name are correct?

We are working on providing a more useful error message, and I will provide more information once we have a target timeline.

**Comment by shurd** [comment]
We have updated the swagger so that the SDK will provide an error message when the account does not exist. This change will be in the next SDK release and then can be applied to the CLI. Target is middle of August release.

**Comment by shurd** [comment]
To update this issue, the management SDK has been updated to properly throw the not found exception. The CLI will be updated to use the newer version with the next cosmosdb command module update. This was originally targeted for the middle of August, but has been delayed.

**Comment by MehaKaushik** [comment]
As a part of S175(https://github.com/Azure/azure-powershell/milestone/109), a CosmosDB was updated. @sireza  please verify if your issue is resolved now.
