### ISSUE TITLE
az storage container generate-sas expiry datetime not valid

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/azure-cli#13824]
[https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#az-storage-container-generate-sas](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#az-storage-container-generate-sas)

```sh
az version

end_date=`date --iso-8601=seconds --date "2020-07-01T17:00:00"` # TZ="Europe/Paris +%FT%T%z

az storage container generate-sas \
    --account-name $aro_registry_blob_str_name \
    --name $aro_registry_container_name \
    --account-key $str_acc_access_key1 \
    --permissions acdlrw \
    --expiry $end_date \
    --auth-mode login \
    --https-only
```
The above command returns the error below :
 az storage container generate-sas: error: argument **--expiry: invalid datetime_type value**: '2020-07-01T19:00:00+02:00'

setting a harc coded value with --expiry "2020-06-10T17:00Z does work, what is wrong with the $end_date ? and how to specify TZ="Europe/Paris ?

{
  "azure-cli": "2.7.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.7.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.45",
    "aro": "1.0.0",
    "azure-firewall": "0.3.0",
    "connectedk8s": "0.1.3",
    "k8sconfiguration": "0.1.6"
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcba5ed-e693-6345-2c1b-c17422d7b8f9
* Version Independent ID: 58297400-b777-6868-1687-0af3a512a16f
* Content: [az storage container](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#az-storage-container-generate-sas)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
Hi @ezYakaEagle442,  `--expiry`  only accepts UTC time which is required by SDK side.  you could use end=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'` to get valid datetime.

So I will close the issue now and feel free to create a new one if you still have problems.
