### ISSUE TITLE
[vm] No option to specify custom data while creating a VM

### ISSUE THREAD

**Issue by paulmey** [Azure/azure-cli#1382]
The 'customData' property in the [create vm API](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines?redirectedfrom=MSDN) is required to provide configuration to [cloud-init](https://help.ubuntu.com/community/CloudInit), the provisioning agent on Ubuntu and an increasing number of Linux distro's.

az vm create doesn't allow me to specify custom data (nor is there any mention of customData in this repo)

**Comment by yugangw-msft** [comment]
We will get to it after #1849 is merged, which should get such change much easier

**Comment by OddBloke** [comment]
#1849 has landed, when might we expect to see work on this?

**Comment by yugangw-msft** [comment]
It will be in the upcoming release

**Comment by twitchax** [comment]
@devigned, do you know what the work required / status is for this issue?

**Comment by devigned** [comment]
@twitchax should be in shortly: https://github.com/devigned/azure-cli/tree/feature/custom-data

I spoke with @paulmey a couple days back about this, so I think we are all good.

**Comment by twitchax** [comment]
Awesome: thanks!

**Comment by OddBloke** [comment]
\o/ Thanks for the attention, folks!
