### ISSUE TITLE
Cannot create network-rule for storage account Values for request parameters are invalid: networkAcls.ipRule[*].value

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/azure-cli#13828]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

az storage account network-rule add command fails with error below :
Values for request parameters are invalid: networkAcls.ipRule[*].value. For more information, see - https://aka.ms/storagenetworkruleset

**To Reproduce**

```sh
AUTHORIZED_IP_RANGE="192.168.1.0/24" 
az storage account update --name $blob_str_name --default-action deny
az storage account network-rule list --account-name $blob_str_name 
az storage account network-rule add --action allow --account-name $blob_str_name --subnet $bastion_subnet_id -g $rg_name # --ip-address $AUTHORIZED_IP_RANGE
az storage account network-rule add --action allow --account-name $blob_str_name --ip-address $AUTHORIZED_IP_RANGE -g $rg_name

```

**Expected behavior**

az storage account network-rule add command should run successfully

**Environment summary**

WSL
{
  "azure-cli": "2.5.1",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.5.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}

**Additional context**

See also [https://github.com/Azure/azure-cli/issues/7417](https://github.com/Azure/azure-cli/issues/7417)

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
Hi@ezYakaEagle442, it is because the ip address you provided is not valid. Only public internet IP addresses is allowed here.

**Comment by Juliehzl** [comment]
For more information, please see https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security#grant-access-from-an-internet-ip-range.
