### ISSUE TITLE
az policy definition create fails with "APIVersion 2019-09-01 is not available"

### ISSUE THREAD

**Issue by plzm** [Azure/azure-cli#13835]
## Describe the bug

**Command Name**
`az policy definition create`

**Errors:**
```
APIVersion 2019-09-01 is not available
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/resource/custom.py, ln 1465, in create_policy_definition
    return policy_client.policy_definitions.create_or_update(name, parameters)
mgmt/resource/policy/_policy_client.py, ln 175, in policy_definitions
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-09-01 is not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az policy definition create --name {} --display-name {} --description {} --rules {} --params {} --mode {} --verbose`

## Environment Summary
```
Linux-4.19.84-microsoft-standard-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
@plzm Hi, this problem will not appear in the latest version. Could you please upgrade the version of CLI to the latest version (2.8.0) and have a try?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
