### ISSUE TITLE
Support for Function App

### ISSUE THREAD

**Issue by sebastiaanvandesteeg** [Azure/azure-cli#13833]
**Feature request:**
-Support for Function App in Event Grid Topics, at this point you cannot see nor create subscriptions manually created between Topics  and Function Apps with Azure CLI.  I would like to create these subscriptions from my command line instead of manually creating them and having to redo this for every Event Grid Trigger.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e73e1b-aad9-0ce8-be1f-a9b9d02ca6d4
* Version Independent ID: 73525c5f-94f3-1c07-e3b6-3a022aab2a10
* Content: [az eventgrid event-subscription](https://docs.microsoft.com/en-us/cli/azure/eventgrid/event-subscription?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/eventgrid/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/eventgrid/_help.py)
* Service: **event-grid**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
eventgrid

**Comment by lilyjma** [comment]
Hi @sebastiaanvandesteeg, we're looking to understand usage scenarios and pain points when customers are using Event Grid. Would you be interested in giving us some feedback on your experience with the library?

**Comment by sebastiaanvandesteeg** [comment]
@lilyjma I am happy to give feedback based on my experience, so far I really like Event Grid and the flexibility of it.  The pain point though is the fact I have to configure so much from the Azure Portal, I would like to setup my Event Grid with a Function App using Event Grid Trigger binding. 

Right now it's easy to set it up using the Azure Portal, but I would like to connect my Function App through configuration(just like any other connection, CosmosDB for example) in the Function App or creating a subscription with the Azure-CLI. But manually configuring this is just not good, I can't automate releases with this for example (atleast new functionality).

Within my company we use 3 resource-groups for the different environments, test -> acceptation -> production. With the current way of configuring I can do 95% through Github Actions and the Azure-CLI but it's hard to release new triggers on the Event Grid because you have to configure the subscription through the Azure Portal.

Since we are a forwarding company we use the Event Grid for internal events and notifcations. So we want it to be flexible, which the Event Grid itself is. But configuring is not...

**Comment by ahamad-MS** [comment]
Hello @sebastiaanvandesteeg .. Thanks for reporting this issue and requesting this feature.

Can you please add this request through the Azure feedback (user voice). Link is here: https://feedback.azure.com/forums/909934-azure-event-grid .. This will allow it to be voted on and makes it to our planning list.

Said that, it seems the ask here is to automatically create when function is created? is this correct?

Currently, Azure Event Grid support creating event subscription in our SDK with Azure Function as a destination (as well as a webhook). This requires The Azure function to be set up separately and to be fully functioning and you have full access privileges to it.

If this is not what you are looking, can you please provide us with additional information to understand the request better.

Adding @jfggdl for awareness.

**Comment by sebastiaanvandesteeg** [comment]
@ahamad-MS Thanks for your reply. You are right, it's about creating a subscription automatically. I will submit a ticket in the Azure feedback.

**Comment by ahamad-MS** [comment]
Thanks @sebastiaanvandesteeg .. Can you please use user voice to open the feedback request and close this issue whenever you have a chance. thanks.
