### ISSUE TITLE
az storage account: 'blob-service-properties' is not in the 'az storage account' command group

### ISSUE THREAD

**Issue by Anbukugan** [Azure/azure-cli#13832]
When I run this command it throws the following error

az storage account: 'blob-service-properties' is not in the 'az storage account' command group. See 'az storage account --help'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18ea7d6-e13f-2ce2-3646-8d5fd7108d20
* Version Independent ID: 3af2621e-585c-11f4-d1ae-0cc9d3531c18
* Content: [az storage account blob-service-properties](https://docs.microsoft.com/en-us/cli/azure/storage/account/blob-service-properties?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Juliehzl** [comment]
@Anbukugan To use `blob-service-properties` , you need to make sure the installed azure cli >= 2.0.78. If your azure cli version is out-of-date, please update it according to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest.

**Comment by Anbukugan** [comment]
Yeah, it worked after updating the CLI. Thank you
