### ISSUE TITLE
Webapp:az webapp create - Example for different RSgroups for Plan and WebApp

### ISSUE THREAD

**Issue by iyerusad** [Azure/azure-cli#13837]
`az webapp create` examples should show example for creating a WebApp in a App Service Plan that is in a different resource group. This information is currently buried in a issue board (https://github.com/Azure/azure-cli/issues/12090)

This is achieved by fetching ID of App Service Plan and providing that for the `-p/--plan` var:
```
AppServicePlanID=$(az appservice plan show -n "SharedAppServicePlan" -g "SharedResources" --query "id" --out tsv)
az webapp create -g MyResourceGroup -n MyUniqueAppName -p "$AppServicePlanID"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
hi @iyerusad do you need a more clear doc on this?

**Comment by iyerusad** [comment]
Please add the example shown.

**Comment by panchagnula** [comment]
@Kotasudhakarreddy do we currently fail this because we do some validation on our end that checks for the serverfarm to be in the same RG as webapp to be created? if not we should make changes to support this to use --resourceID for RG and ASP values. Need more investigation.

**Comment by Kotasudhakarreddy** [comment]
looking in to it.
