### ISSUE TITLE
unable to use azure aks command

### ISSUE THREAD

**Issue by manisha10992** [Azure/azure-cli#13836]
## Describe the bug

**Command Name**
``

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.5.1 *

```

**Comment by yonzhan** [comment]
AKS

**Comment by yungezz** [comment]
hi @manisha10992 could you pls share error you met and repro steps? currently the bug description has nothing for investigation.

**Comment by seanmck** [comment]
This is not actionable. Please reopen if there's a real repro.
