### ISSUE TITLE
Adding nic to address pool fails because of unsupported api version on azure api

### ISSUE THREAD

**Issue by tomecho** [Azure/azure-cli#13831]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

`az network nic ip-config address-pool add \
    --resource-group jenkins-azure-vms \
    --nic-name "$(hostname)NIC" \
    --ip-config-name ipconfig1 \
    --address-pool /subscriptions/a3e26f48-3fab-4ced-a75e-2a39196e42ba/resourceGroups/jenkins/providers/Microsoft.Network/loadBalancers/jenkins-agents-alb/backendAddressPools/jenkins-agents \
    --subscription "Teacher Evaluator"` 

Azure cli seems to have updated https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#network to switch network api version to unsupported version.

`No registered resource provider found for location 'eastus' and API version '2020-04-01' for type 'networkInterfaces'. The supported api-versions are '2014-12-01-preview, 2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-06-01, 2016-07-01, 2016-08-01, 2016-09-01, 2016-10-01, 2016-11-01, 2016-12-01, 2017-03-01, 2017-04-01, 2017-06-01, 2017-08-01, 2017-09-01, 2017-10-01, 2017-11-01, 2018-01-01, 2018-02-01, 2018-03-01, 2018-04-01, 2018-05-01, 2018-06-01, 2018-07-01, 2018-08-01, 2018-10-01, 2018-11-01, 2018-12-01, 2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-01-01, 2020-03-01'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth, australiaeast, australiasoutheast, centralindia, southindia, westindia, canadacentral, canadaeast, westcentralus, westus2, ukwest, uksouth, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth'.`

**To Reproduce**

`az network nic ip-config address-pool add \
    --resource-group jenkins-azure-vms \
    --nic-name "$(hostname)NIC" \
    --ip-config-name ipconfig1 \
    --address-pool /subscriptions/a3e26f48-3fab-4ced-a75e-2a39196e42ba/resourceGroups/jenkins/providers/Microsoft.Network/loadBalancers/jenkins-agents-alb/backendAddressPools/jenkins-agents \
    --subscription "Teacher Evaluator"` 

**Expected behavior**

It should work without error like before

**Environment summary**

Installed using `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`, latest 2.7.0, running on ubuntu vm

**Additional context**

**Comment by yonzhan** [comment]
add to S171

**Comment by MyronFanQiu** [comment]
@tomecho service team is fixing it right now. The quickest way to unblock you is to install the old version of Azure CLI. Sorry for the inconvenience.
```
sudo apt remove azure-cli
sudo apt-get install azure-cli=2.5.1-1~bionic
```
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

**Comment by tomecho** [comment]
Thanks!  That’s what we’ll do.





On Thursday, June 4, 2020, 9:03 AM, MyronFanQiu <notifications@github.com> wrote:




@tomecho service team is fixing it right now. The quickest way to unblock you is to install the old version of Azure CLI. Sorry for the inconvenience.
sudo apt remove azure-cli
sudo apt-get install azure-cli=2.5.1-1~bionic

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

**Comment by MyronFanQiu** [comment]
This should be fixed. Please have a try.
