### ISSUE TITLE
`az acr login --expose-token` should throw error if username or password is specified

### ISSUE THREAD

**Issue by Wwwsylvia** [Azure/azure-cli#13847]
**Describe the bug**
When a username or password is specified, the `az acr login --expose-token` returns a invalid result.

**To Reproduce**
`az acr login -n myregistry -u test -p test --expose-token`

![image](https://user-images.githubusercontent.com/8113721/83867653-5a2dc400-a75c-11ea-906a-30000bc35e5b.png)

**Expected behavior**
Throw error and output a warning if username or password is specified, as exposing token for ACR admin users and token users makes no sense.

**Environment summary**

azure-cli 2.3.0

**Additional context**

**Comment by Wwwsylvia** [comment]
I will fix this.

**Comment by yonzhan** [comment]
acr

**Comment by yugangw-msft** [comment]
thanks, and let us fix it
