### ISSUE TITLE
Get List of Available IP for Subnet

### ISSUE THREAD

**Issue by geoarchitect** [Azure/azure-cli#13853]
Azure CLI recently added this command: 

```
az network vnet list-available-ips -g [resource group] -n [vnet name]
```

This works great but only seems to return some ip addresses in the VNet. 

Can we leverage the jmeshquery --query to specify some ip range or a subnet to narrow this down? 

**Is your feature request related to a problem? Please describe.**
Yes, the list-available-ips command doesnt return all available ip's 

For example you may have 192.168.0.0/16 and you may have a bunch of subnets, can we filter to a given subnet, or get all available ip's from the vnet. 

**Describe the solution you'd like**
Option 1 - Possibly use --query to specify the ip range of the subnet or subnet name

Option 2 - Add the same list-available-ips command for az network vnet subnet 

If there is a way to do this, maybe we can document it and update the CLI Docs with an example. 

**Describe alternatives you've considered**
Manually typing random ip's in a range to see if they are consumed. 

**Additional context**
We did this for VNet level but that only returns some of the available ip's.

**Comment by yonzhan** [comment]
add to S172

**Comment by MyronFanQiu** [comment]
@geoarchitect Thanks for your suggestions. I would invite service team to take a look. When I worked for this command, I didn't find a way to list some ips within a subnet. We might need service team's help.

**Comment by jl-ms** [comment]
We are looking into this. Thanks for the feedback, @geoarchitect .

**Comment by thiDucTran** [comment]
Hi @jl-ms , we have a use-case where in our create/upgrade aks cluster playbooks..we need to know the number of available IPs within a given subnet before performing creation or upgrading.

**Comment by 00rellana** [comment]
We have the same need using python SDK where we need to query number of available ( Free ) IPs in a subnet before we allow VM provisioning to continue. I will be watching this post closely to see if anyone comes up with solution or workaround using NetworkManagementClient.   Thanks, OO

**Comment by thiDucTran** [comment]
```bash
#!/usr/bin/bash

vnet_rg="rg-th01-sea-n-nonprodsrv01-network01"
vnet_name="vnet-th01-sea-n-nonprodsrv01"
subnet_name="subnet-u-nonprod-aks01-10.214.151.0-24"

network_prefix=`az network vnet subnet show -g $vnet_rg -n $subnet_name --vnet-name $vnet_name -o json | jq -r .addressPrefix`

regex="\/(.*)"

[[ $network_prefix =~ $regex ]]

subnet_mask=${BASH_REMATCH[1]}

max_ip=$((2 ** (32-$subnet_mask)-5))

used_ip=`az network vnet subnet show -g $vnet_rg -n $subnet_name --vnet-name $vnet_name -o json -o json | jq  ".ipConfigurations[].id" | wc -l`

available_ip=$(($max_ip - $used_ip))

echo "There are $available_ip IPs available for subnet $subnet_name"
```

**Comment by thiDucTran** [comment]
we are using this as a workaround

```bash
#!/usr/bin/bash

vnet_rg=""
vnet_name=""
netmask="24"

max_ip=$((2 ** (32-$netmask)-5))

used_ip=`az network vnet subnet show -g $vnet_rg -n $subnet_name --vnet-name $vnet_name -o json -o json | jq  ".ipConfigurations[].id" | wc -l`

available_ip=$(($max_ip - $used_ip))

echo "There are $available_ip IPs available for subnet $subnet_name"
```

**Comment by necusjz** [comment]
Testing blocked by feature `Microsoft.Network/AllowMultipleAddressPrefixesOnSubnet` registration.
