### ISSUE TITLE
no option to control minimum tls version

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/azure-cli#13857]
## Describe the bug

there appears to be no way to set the minimum TLS version with az cli. it's not in configuration properties.  but it's exposed in portal

![image](https://user-images.githubusercontent.com/31082908/83938183-2fa53080-a787-11ea-8ff4-c932f823dfe3.png)

and it's visible in the resource properties itself when reviewing the json for the mysql db.

**Command Name**
`az mysql server update`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az mysql server update -h`

## Environment Summary
```
macOS-10.15.5-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.7.0

Extensions:
db-up 0.1.14

```

**Comment by yonzhan** [comment]
mysql

**Comment by kummanish** [comment]
We are working on enabling this CLI support in upcoming releases. Currently we only support portal workflow.

**Comment by kummanish** [comment]
#please-close
