### ISSUE TITLE
Azure CLI Throws TypeError: __init__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by alexhhward** [Azure/azure-cli#13858]
I'm attempting to follow this [tutorial](https://github.com/microsoft/recommenders/blob/master/notebooks/05_operationalize/als_movie_o16n.ipynb) and am getting the following error.
![image](https://user-images.githubusercontent.com/66201469/83938211-caa20880-a78f-11ea-838f-7c17ae518c4e.png)

I've tried solutions to roll back my Azure Python SDK using Pip. I run ``pip install --upgrade azureml-sdk`` and all looks good. Thanks very much for any and all help!

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14830

**Comment by rastala** [comment]
@alexhhward  Looks like the underlying issue has been resolved. Could you re-try after updating Azure ML SDK and dependencies, please? I'll proceed to close the issue, if I don't hear otherwise.

**Comment by DmBoiko** [comment]
Hello, 
When publishing a pipeline I get the same error:

TypeError: __init__() takes 2 positional arguments but 3 were given

Could you please help?
