### ISSUE TITLE
Error when running this command : az cosmosdb update --name CosmosDBAccountName --resource-group ResourceGroupName --disable-key-based-metadata-write-access true 

### ISSUE THREAD

**Issue by sharan779** [Azure/azure-cli#13869]
## Describe the bug

**Command Name**
`az cosmosdb update`

**Errors:**
```
'NoneType' object has no attribute 'consistency_policy'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 325, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 545, in default_command_handler
    return op(**command_args)
cli/command_modules/cosmosdb/custom.py, ln 163, in cli_cosmosdb_update
    max_staleness_prefix = existing.consistency_policy.max_staleness_prefix
AttributeError: 'NoneType' object has no attribute 'consistency_policy'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cosmosdb update --name {} --resource-group {} --disable-key-based-metadata-write-access {}`

## Environment Summary
```
Linux-4.15.0-1083-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

```

**Comment by yungezz** [comment]
duplicate with https://github.com/Azure/azure-cli/issues/13808

**Comment by shurd** [comment]
@yungezz is correct. Please ensure the resource group/account exist in the subscription. We are working on a fix to clarify the error in the CLI output.

**Comment by sharan779** [comment]
Yes, the resource group and account does exist

**Comment by shurd** [comment]
Hi @sharan779 sorry for the delay. Could you please share account name either here or by opening on support request via Azure portal? I have not been able to reproduce this error unless the target account does not exist.

We have updated the swagger so that the SDK will provide an error message when the account does not exist. This change will be in the next SDK release and then can be applied to the CLI. Target is middle of August release.

**Comment by shurd** [comment]
To update this issue, the management SDK has been updated to properly throw the not found exception. The CLI will be updated to use the newer version with the next cosmosdb command module update. This was originally targeted for the middle of August, but has been delayed.

**Comment by MehaKaushik** [comment]
As a part  of[ S175](https://github.com/Azure/azure-powershell/milestone/109) a CosmosDB was updated. @sharan779 please verify if your issue is resolved now.
