### ISSUE TITLE
az resource delete doesn't work for privateDnsZones (nested resources)

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/azure-cli#13860]
## Describe the bug

Microsoft.Network/privateDnsZones can't be deleted due to nested resources. az cli doesn't seem to be able to deal with nested resources.

**Command Name**
`az resource delete`

**Errors:**
```
Some resources failed to be deleted (run with `--verbose` for more information):
/subscriptions/00f9d365-3a02-4dfa-9d65-7fdbe445cd16/resourceGroups/swamp
```
msrest.exceptions : Operation failed with status: 'Method Not Allowed'. Details: 405 Client Error: Method Not Allowed for url: https://management.azure.com/subscriptions/00f9d365-3a02-4dfa-9d65-7fdbe445cd16/resourcegroups/swamp/providers/Microsoft.Network/privateDnsZones/privatelink.mysql.database.azure.com%2Fmysqldnslink?api-version=2020-01-01
405 Client Error: Method Not Allowed for url: https://management.azure.com/subscriptions/00f9d365-3a02-4dfa-9d65-7fdbe445cd16/resourcegroups/swamp/providers/Microsoft.Network/privateDnsZones/privatelink.mysql.database.azure.com%2Fmysqldnslink?api-version=2020-01-01

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az resource delete --resource-group {} --name {} --resource-type {} --verbose --debug`

## Environment Summary
```
macOS-10.15.5-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.7.0

Extensions:
db-up 0.1.14

```

**Comment by yungezz** [comment]
hi @zhoxing-ms could you have a look?

**Comment by yonzhan** [comment]
add to S171

**Comment by zhoxing-ms** [comment]
@christiankuhtz Hi, I tried many times and found that this problem was related to the special character `%2F` in the ID of the privateDnsZones. If the ID of privateDnsZones contains `%2F`(`/`), will report an error when created, like:
```pwsh
(env) PS D:\project> az network private-dns zone create -g zhoxing-test -n privatelink.table.core.windows.net/zhoxing
Operation failed with status: 'Method Not Allowed'. Details: 405 Client Error: Method Not Allowed for url: https://management.azure.com/subscriptions/{xxx}/resourceGroups/{xxx}/providers/Microsoft.Network/privateDnsZones/privatelink.table.core.windows.net%2Fzhoxing?api-version=2018-09-01
```
So May I ask why does your resource ID include `%2F`?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
