### ISSUE TITLE
webapp: Quit using the pipe character '|' inside runtime types - makes CLI difficult

### ISSUE THREAD

**Issue by freemansoft** [Azure/azure-cli#13866]
**Describe the bug**
Can't find any way to run the --runtimes  on windows in bash shell.
Quit using the "|" character in values for --runtime  for the CLI.  It causes problems in all shells.
Use "-" or "_" or some non special character. 

**To Reproduce**
Install Azure CLI on windows
Install any bash shell like Git Bash
Alias az=az.cmd
Try and run something like "az webapp create .... -runtime "JAVA|8-jre8"
Try and run something like "az webapp create .... -runtime "JAVA\|8-jre8"

**Expected behavior**
Standard Bash escaping should work but it doesn't

**Environment summary**
Install Azure CLI on windows 10 using the installer

**Additional context**
Our build servers run on linux. Most of our developers have Windows laptops. We run Git BAsh shells in Visual Code and in shell windows

Pretty much everything in the CLI works fine except for these dang runtime names with embedded pipe characters.

Runtimes should be specified with ARNs.  Something like

- runtime:linux/JAVA/8-jre8

**Comment by yonzhan** [comment]
webapp

**Comment by freemansoft** [comment]
The second example that fails actually has a backslash prior to the pipe.  You can only see it if you edit the post.  The backslash is eaten by the formatter.

**Comment by panchagnula** [comment]
Thanks for reporting - the use of pipe | comes from the API that sets the values as language|runtime-version.  Please make sure to use bash or terminal instead of Powershell - to ensure pipe doesn't mess with the usage. Closing this as by design for now.

**Comment by freemansoft** [comment]
The "|" is a bad character to put in the API.  Are you saying this change would have to happen in a different project?

**Comment by panchagnula** [comment]
@freemansoft yes our API team is working on re-writing the API & this is the feedback I already shared with them. If API doesn't make that change - we plan to  obscure this info from CLI command & handle it on the client before passing it to the API, but that will take time unfortunately.

**Comment by piouson** [comment]
Just stumbled on this issue with Git Bash and wondering if anyone found a way to escape pipe or a cli alternative..
Asked on [Stackoverflow](https://stackoverflow.com/questions/64318299/how-do-you-escape-pipes-when-using-azure-cli-from-git-bash)

**Comment by freemansoft** [comment]
Moving to Linux on Windows with WSL2 has become my go-to fix for this type of thing.

**Comment by piouson** [comment]
@freemansoft lucky man, some of us hands tied.. [#6016](https://github.com/microsoft/WSL/issues/6016) [#4285](https://github.com/microsoft/WSL/issues/4285) [#5336](https://github.com/microsoft/WSL/issues/5336)
> Git Bash - fail
> PowerShell - fail
> Command Prompt - works :confounded:

**Comment by panchagnula** [comment]
> @freemansoft lucky man, some of us hands tied.. [#6016](https://github.com/microsoft/WSL/issues/6016) [#4285](https://github.com/microsoft/WSL/issues/4285) [#5336](https://github.com/microsoft/WSL/issues/5336)
> 
> > Git Bash - fail
> > PowerShell - fail
> > Command Prompt - works 😖

Sorry folks - we plan to make this change on the client side since the API continues to use this format in the versioning. In the meantime please check out this link to see if it helps https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively?view=azure-cli-latest#quoting-issues

**Comment by NickFosterEnsono** [comment]
This still sucks six years later.  

I'm using the Azure CLI from PowerShell in Azure Devops deployment pipelines and this has cost me hours of searching to get it working.  Using | as a separator character is a terrible idea for this.
