### ISSUE TITLE
Missing antlr4, az cli nic add --help fails

### ISSUE THREAD

**Issue by doughernand** [Azure/azure-cli#13862]
## Describe the bug

**Command Name**
`az vm nic add`

**Errors:**
```
No module named 'antlr4'
Traceback (most recent call last):
lib/python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
dist-packages/azure/cli/core/__init__.py, ln 300, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
azure/cli/command_modules/vm/__init__.py, ln 31, in load_arguments
    from azure.cli.command_modules.vm._params import load_arguments
azure/cli/command_modules/vm/_params.py, ln 31, in <module>
    from azure.cli.command_modules.monitor.actions import get_period_type
azure/cli/command_modules/monitor/actions.py, ln 7, in <module>
    import antlr4
ModuleNotFoundError: No module named 'antlr4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm nic add --help`

## Environment Summary
```
Linux-5.4.0-33-generic-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by subhasishdc** [comment]
@doughernand: It looks like the package `antlr4` is missing for python. Could you check whether `antlr4-python3-runtime` is installed correctly using `pip list | grep antlr`

If not, can you try running `sudo pip3 install antlr4-python3-runtime` and retry the `az vm nic add` after that to see if it solves the issue.

If it is still happening even after doing the above steps, then it may be something else and I will let someone from the `az cli` team comment on it.

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by doughernand** [comment]
Some additional background - this is a recent install of Ubuntu 20.04 LTS. I don't see an antlr module, and pip is not currently installed.

```bash
pi@copper:~/.ssh$ python3 -m antlr4-python3-runtime;python3 -m antlr4
/usr/bin/python3: No module named antlr4-python3-runtime
/usr/bin/python3: No module named antlr4
pi@copper:~/.ssh$ cat /etc/os-release && uname -a
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
Linux copper 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
pi@copper:~/.ssh$ dpkg -l | grep pip
ii  libpipeline1:amd64                   1.5.2-2build1                         amd64        Unix process pipeline manipulation library
```

I ran into this shortly after running azure cli setup commands. Here is my history:
```console
1735  az login
 1736  sudo apt install azure-cli
 1737  az login
 1738  az nic
 1739  az network
 1740  azn network -h
 1741  az network -h
 1742  az network nsg -h
 1743  az network nsg list
 1744  az vm help
 1745  az vm --help
 1746  az vm nic --help
 1747  az vm nic add --help
 1748  az vm nic add
 1749  az vm nic addaz feedback
 1750  az vm nic add --help
 1751  az feedback
```

**Comment by yungezz** [comment]
hi @qwordy @fengzhou-msft seems there's several instance on missing `antl4r` , could  you pls work together to have a look? thanks

**Comment by qwordy** [comment]
> 
> 
> hi @qwordy @fengzhou-msft seems there's several instance on missing `antl4r` , could you pls work together to have a look? thanks

Yes, it is.

**Comment by qwordy** [comment]
Are you using the bundled Azure CLI of Ubuntu? The package is old and has some problems. Could you install the latest version and retry?
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

**Comment by qwordy** [comment]
Any update?
