### ISSUE TITLE
Example commands and better definitions

### ISSUE THREAD

**Issue by jfrabetti** [Azure/azure-cli#13864]
Hello,

I am trying to [set a policy using Azure CLI](https://docs.microsoft.com/en-us/azure/governance/policy/assign-policy-azurecli):
az policy assignment create --name 'audit-vm-manageddisks' --display-name 'Audit VMs without managed disks Assignment' --scope 'ugh2020' --policy '06a78e20-9358-41c9-923c-fb736d382a4d'
I am getting the error: 
The request did not have a subscription or a valid tenant level resource provider.
I navigated to the page below.  I see things like:
_--scope
Scope to which this policy assignment applies._

Is it possible to elaborate?  Show sample commands? I have set the subscription.

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c6760bb-c278-da56-a95c-4e82e221f1e8
* Version Independent ID: e25cbd2a-b415-214f-7d50-c403992c9361
* Content: [az policy assignment](https://docs.microsoft.com/en-us/cli/azure/policy/assignment?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
Hi, could you please try to use the command `az policy assignment create -h` to view the help information and examples.
The following are the explanations and examples of scope:
```bash
Valid scopes are management group, subscription, resource group, and resource, for example
   management group:  /providers/Microsoft.Management/managementGroups/MyManagementGroup
   subscription:      /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333
   resource group:    /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333/resourceGroups/myGroup
   resource:          /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333/resourceGroups/myGroup/providers/Microsoft.Compute/virtualMachines/myVM
     az policy assignment create --scope \
        "/providers/Microsoft.Management/managementGroups/MyManagementGroup" \
            --policy {PolicyName} -p "{ \"allowedLocations\": \
                { \"value\": [ \"australiaeast\", \"eastus\", \"japaneast\" ] } }"
```
Do you hava any other questions?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
