### ISSUE TITLE
az webapp vnet-integration add fails with api-version '2020-04-01' is invalid

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/azure-cli#13863]
**Describe the bug**
`az webapp vnet-integration add` fails (at least in west europe) with message
```
Command group 'webapp vnet-integration' is in preview. It may be changed/removed in a future release.
The api-version '2020-04-01' is invalid. The supported versions are '2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
```

UPDATE: This happens only if `--vnet` param is passed in form of resourceId not name.

**To Reproduce**
Run `az webapp vnet-integration add` for a web app in west europe.

**Expected behavior**
Should work :-).

**Environment summary**
apt-get/2.7.0/Ubuntu 18.04/Bash on Windows

**Additional context**
west europe

**Comment by mkosieradzki** [comment]
Version 2.6.0 fails with 
```
Command group 'webapp vnet-integration' is in preview. It may be changed/removed in a future release.
The api-version '2020-03-01' is invalid. The supported versions are '2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
Thanks for reporting we will look into this. @calvinsID can you check if you can repro this with the latest version of CLI - as per this issue this happened on 2.6.0. Thanks!

**Comment by calvinsID** [comment]
@mkosieradzki Thanks for reporting this! This behaviour happens whenever an invalid vnet name is used. The command's --vnet parameter expects a vnet name rather than resourceId. I'll fix the error handling/message for invalid vnet name, however please continue using vnet name rather than resourceId

**Comment by mkosieradzki** [comment]
Thanks. How can I connect vnet from a different RG using CLI? Do I need to use ARM template or REST API?

**Comment by calvinsID** [comment]
Using the vnet name of a vnet in a different RG should work. However if there are multiple vnets of the same name, that can be an issue.. I'll put in a fix to allow using the vnet resourceId in place of the name

**Comment by mkosieradzki** [comment]
Thanks! That would be a big improvement in my scenario.
