### ISSUE TITLE
azure-cli 2.8.0 and 2.7.0 compatibility issues with azure-storage-blob since October 2019

### ISSUE THREAD

**Issue by jeroenhabets** [Azure/azure-cli#13876]
## Describe the bug
azure-storage-blob versions after _October 2019_ are not supported. 
**Update: still there in azure-cli 2.8.0 (with Python 3.8.3)**
ERROR: azure-cli 2.7.0 has requirement azure-storage-blob<2.0.0,>=1.3.1, but you'll have azure-storage-blob 12.3.1 which is incompatible.

**Command Name**
`pip install -U -r requirements.txt`

**Errors:**
2.7.0:
ERROR: azure-cli 2.7.0 has requirement azure-storage-blob<2.0.0,>=1.3.1, but you'll have azure-storage-blob 12.3.1 which is incompatible.
2.8.0:
ERROR: azure-cli 2.8.0 has requirement azure-storage-blob<2.0.0,>=1.3.1, but you'll have azure-storage-blob 12.3.2 which is incompatible.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `python -m venv azure_cli_issue`
- `cd azure_cli_issue`
- `pip install -U azure-cli azure-storage-blob`
Then
- `pip install -U azure-storage-blob`

## Expected Behavior
No error. But I get:
ERROR: azure-cli 2.8.0 has requirement azure-storage-blob<2.0.0,>=1.3.1, but you'll have azure-storage-blob 12.3.1 which is incompatible.

## Environment Summary
**Update: still there in azure-cli 2.8.0 (with Python 3.8.3)**
```
Windows-10-10.0.18362-SP0
Python 3.7.7
Installer: PIP

azure-cli 2.7.0

```

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by jeroenhabets** [comment]
Update title/description to reflect issue is still there in 2.8.0.

Why not just remove the azure-storage-blob<2.0.0 and run your regression test? (Note that I haven't encountered any issues but our usage does not offer wide coverage)

**Comment by fengzhou-msft** [comment]
@Juliehzl is working on removing azure-storage-blob and currently blocked by an extension that is still using it.

**Comment by jeroenhabets** [comment]
Also reported by @IRLeif, see https://github.com/Azure/azure-cli/issues/14240#issuecomment-656111287

**Comment by Juliehzl** [comment]
fixed already. please try with latest azure cli.

**Comment by jeroenhabets** [comment]
@Juliehzl Ah! Great! That's why I no longer got the error yesterday afternoon when I pip updated my local installation _nor_ in the new installation for one of the starters within my team :) 

I reran the repro steps (BTW: they miss the venv activation) and got no error so I'm closing this issue. 

Thanks @Juliehzl, @fengzhou-msft
