### ISSUE TITLE
Quoting '&' in PowerShell

### ISSUE THREAD

**Issue by skmkzyk** [Azure/azure-cli#13882]
## Describe the bug

I'm sorry, I think this is a FAQ...
I hit on Azure CLI on Windows (PowerShell, Windows Terminal), but can't figure out how to pass multiple params to the REST URL.
1st parameter (peer=13.76.248.75) is recognized but 2nd (api-version=2020-04-01) is not.
Tried quoting by 'URL' (single quote), "URL" (double quote), and '"URL"' (single and double quote), but neither working..

```
PS C:\Users\kasakemi> az rest --verbose -m post -u 'https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/vnet-peering/providers/Microsoft.Network/virtualNetworkGateways/vpngw-onpsvc01/getAdvertisedRoutes?peer=13.76.248.75&api-version=2020-04-01'
Request URL: 'https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/vnet-peering/providers/Microsoft.Network/virtualNetworkGateways/vpngw-onpsvc01/getAdvertisedRoutes?peer=13.76.248.75'
Request method: 'POST'
...
Response content:
{"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}}
Bad Request({"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}})
command ran in 1.227 seconds.
'api-version' is not recognized as an internal or external command,
operable program or batch file.
```

**Command Name**
`az rest`

**Errors:**
```
Bad Request({"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}})
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az rest --verbose -m {} -u {}`

## Expected Behavior

pass parameters peer and api-version correctly.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.7.0

Extensions:
resource-graph 1.1.0

```

**Comment by yonzhan** [comment]
add to S172

**Comment by jiasli** [comment]
We have a doc about quoting issues on the home page https://github.com/Azure/azure-cli#common-scenarios-and-use-azure-cli-effectively. You may find the link there pointing to [Quoting issues](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues), which again links to [Quoting issues with PowerShell](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md#ampersand--is-interpreted-by-command-prompt).

Kindly let me know if this solves your problem. 😊

**Comment by skmkzyk** [comment]
Thanks, it helps me a lot ;)

**Comment by jiasli** [comment]
Thank you too. I have also improved the doc and make it more visible.
