### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by lexuanquynh** [Azure/azure-cli#13896]
## Describe the bug

**Command Name**
`az deployment create`

**Errors:**
```
Deployment failed. Correlation ID: f098dc2a-4199-42c4-a57e-f07ef3819dd7. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
...
          }
        ]
      }
    ]
  }
}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az deployment create --template-file {} --location {} --parameters {} {} {} {} {} {} {} {} {} --name {}`

## Environment Summary
```
macOS-10.15.5-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.7.0

```

**Comment by yungezz** [comment]
hi @zhoxing-ms could you pls have a look?

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
This is a problem returned by service, which needs to be investigated by the service team.
> Correlation ID: f098dc2a-4199-42c4-a57e-f07ef3819dd7.

**Comment by navba-MSFT** [comment]
@lexuanquynh Apologies for the delayed response. If the issue is still occurring, Could you please share the new `correlation id `, time of the issue and the `region` where the resource is being created ? Awaiting your reply.
