### ISSUE TITLE
Can't query and save az cli output as a variable except when using a "show" command

### ISSUE THREAD

**Issue by Plus3IT-Azure** [Azure/azure-cli#13890]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
 Running command `$appreg = (az ad app create --displayname "xxxxxx").appId` does not make the appId a variable when using Azure CLI. 

**To Reproduce**
1. Create a App Registration using AZ CLI and attempt to specify the appId as the variable as seen above. 

**Expected behavior**
When I run $appreg the output should be the appId of the App Registration that was created. 

**Environment summary**
Install Method (MSI) / CLI version (`2.0.63`) / OS version Windows 10 / Shell Type (powershell) 

**Additional context**

**Comment by yungezz** [comment]
hi @Plus3IT-Azure could you pls try --query output to get the appId?
```
az ad app create --displayname "xxxxxx" | --query "appId"
```

**Comment by Plus3IT-Azure** [comment]
Thank you for responding; that syntax worked without the pipe; when the pip is added it threw errors stating that `Expressions are only allowed as the first element of a pipeline`

In conclusion the syntax that worked is `az ad app create --displayname "xxxx" --query "appId"`

**Comment by fengzhou-msft** [comment]
For more about `--query`: https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest
