### ISSUE TITLE
Keyvault, RBAC role assignements create follows Swagger objects. 

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#13895]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Service previously has a bug to compliance with Swagger file, service will do the fix. Need to update CLI code to compliance with Swagger also.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2/rbac.json#L351

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Keyvault

**Comment by bim-msft** [comment]
Fixed
