### ISSUE TITLE
[network] az network application-gateway frontend-ip update does not work for public ip addresses, please remove from help and doc

### ISSUE THREAD

**Issue by subhasishdc** [Azure/azure-cli#13891]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
As per az cli help and azure docs, the following command can be used to update the public frontend ip address to a new address for the application gateway:

`az network application-gateway frontend-ip update -g MyResourceGroup --gateway-name MyAppGateway -n MyFrontendIp --public-ip-address MyNewPublicIpAddress`

However, on trying to use this for one of our use cases during testing, it looks like it does not work

**To Reproduce**
`schowdhu-mn2:~ schowdhu$ az network application-gateway frontend-ip update --gateway-name test-aag --name testpublicipv4-1 --resource-group wus2-test-network-rg --public-ip-address traffic-aag-pubip-1`
`PublicIPAddress property of FrontendIpConfiguration /subscriptions/2e4c9be9-b9de-41fe-ade9-05b246dfa02b/resourceGroups/wus2-k2-net-rg/providers/Microsoft.Network/applicationGateways/test-aag/frontendIPConfigurations/testpublicipv4-1 cannot be changed.`

**Expected behavior**
From what I understand, updating the public ip address can't be done directly. We would need to first disassociate it from the application gateway (by changing the listener frontend ip configuration to point to the private ip address) and then configure the app gateway frontend ip configuration to point to the new public ip address ID. Considering this, the above command will not work.

**Environment summary**
az --version : azure-cli (2.0.55)

OS Version
schowdhu-mn2:~ schowdhu$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287

**Additional context**
Issue https://github.com/Azure/azure-cli/issues/4133 was created previously for this. It was closed without any action since the service may change in future to permit this behavior. Another user also reported it: https://github.com/Azure/azure-cli/issues/13852

Is there any update on the future roadmap of the service to support this? If not, it would be best to remove it from the --help section as well as from the documentation to avoid confusion.

**Comment by subhasishdc** [comment]
@MyronFanQiu : Here is the issue with output from the `az cli` command to confirm the error which is described. Please review this from your end and confirm if this parameter can be deprecated.

If yes, I can submit a PR for removing it from the `--help` section and the docs.

**Comment by yungezz** [comment]
@MyronFanQiu is on it

**Comment by yonzhan** [comment]
add to S171

**Comment by MyronFanQiu** [comment]
@subhasishdc Hi. You're correct, I think we can deprecate this argument and change help message as well.

**Comment by subhasishdc** [comment]
@MyronFanQiu : Created this PR to deprecate this argument and remove it from the help section: https://github.com/Azure/azure-cli/pull/14098

**Comment by MyronFanQiu** [comment]
Thanks for @subhasishdc's contribution. Closed this issue since it's solved.
