### ISSUE TITLE
Webapp:OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

### ISSUE THREAD

**Issue by kbrajwani** [Azure/azure-cli#13906]
Hey when i am uploading my Flask + Pytorch by following command
az webapp up --sku F1 -n b appname

I am getting following errors

## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
('Connection aborted.', OSError("(10054, 'WSAECONNRESET')",))
Traceback (most recent call last):
urllib3\urllib3\contrib\pyopenssl.py, ln 320, in _send_until_done
pip-install-_kvuguic\pyOpenSSL\OpenSSL\SSL.py, ln 1737, in send
pip-install-_kvuguic\pyOpenSSL\OpenSSL\SSL.py, ln 1639, in _raise_ssl_error
OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

...

pip-install-_kvuguic\requests\requests\sessions.py, ln 646, in send
pip-install-_kvuguic\requests\requests\adapters.py, ln 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')",))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --sku {} -n {} --debug`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.7.0

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
Please try with the latest version of CLI and open a new issue if this still a problem thanks.
