### ISSUE TITLE
az vm capture prints to stdout rather than returning values...

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#1390]
...which breaks output formatters, multiple ids etc. I'm also not sure why we have our own poller etc. (but I'm guessing that is because we are not returning values and letting the rest of the infrastructure do the right thing)

Current implementation:

def capture_vm(resource_group_name, vm_name, vhd_name_prefix,
               storage_container='vhds', overwrite=True):
    '''Captures the VM by copying virtual hard disks of the VM and outputs a
    template that can be used to create similar VMs.
    :param str vhd_name_prefix: the VHD name prefix specify for the VM disks
    :param str storage_container: the storage account container name to save the disks
    :param str overwrite: overwrite the existing disk file
    '''
    client = _compute_client_factory()
    parameter = VirtualMachineCaptureParameters(vhd_name_prefix, storage_container, overwrite)
    poller = client.virtual_machines.capture(resource_group_name, vm_name, parameter)
    result = LongRunningOperation()(poller)
    **print(json.dumps(result.output, indent=2)) # pylint: disable=no-member**

**Comment by tjprescott** [comment]
I believe the reason it prints to STDOUT is because it is outputting the VM template that you would then redirect to a file. For that, only the JSON output format would be appropriate.

**Comment by yugangw-msft** [comment]
I see. We can either live with it (I will add a code comment) or we take the suggestion from #1512, and expose a --template flag. 
I would live with it.
