### ISSUE TITLE
 az monitor diagnostic-setting create --export-to-resource-specific command doesn't work in Azure CLI 2.3.0

### ISSUE THREAD

**Issue by Gitdevnttuser** [Azure/azure-cli#13901]
trying to specify the location of the  --export-to-resource-specific command with $true and I get an 
az: error: unrecognized arguments: --export-to-resource-specific True

Tried "true", same result.

upgrade to 2.7.0 fix it.

Please update doco to include  the "logAnalyticsDestinationType" property and the allowed values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9ae3afa-74ff-12e8-a32c-c01240bd37da
* Version Independent ID: 522b7e55-2510-8e51-021a-2fc134fabfbe
* Content: [az monitor diagnostic-settings](https://docs.microsoft.com/en-us/cli/azure/monitor/diagnostic-settings?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S172

**Comment by haroldrandom** [comment]
@Gitdevnttuser Is your question solved? I don't understand, did you want us to update the doc?

**Comment by haroldrandom** [comment]
Closed as inactive
