### ISSUE TITLE
Failure with az login

### ISSUE THREAD

**Issue by ianchanning** [Azure/azure-cli#13905]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.6/site-packages/six.py, ln 703, in reraise
    raise value
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 600, in set_token
    token_entry = self._vm_msi.get_token(self.resource)
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 649, in get_token
    token_entry = self._retrieve_token_from_imds_with_retry(resource)
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 704, in _retrieve_token_from_imds_with_retry
    raise HTTPError(request=result.request, response=result.raw)
requests.exceptions.HTTPError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity -u {}`

## Environment Summary
```
Linux-5.3.0-1020-azure-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

```

**Comment by yungezz** [comment]
hi @arrownj could you pls have a look?

**Comment by ianchanning** [comment]
I believe this is down to a mix up between system and user assigned managed identities. I believe when I was first assigning identities via `az vm identity assign` I accidentally created a system identity rather than a user identity. I have since turned off the system assigned identity and re-assigned the user identity and the `az login --identity` works correctly now
