### ISSUE TITLE
webapp: Cannot deploy by any means to my WebApp, not using FTP, not using az CLI, not in VS

### ISSUE THREAD

**Issue by nordquist** [Azure/azure-cli#13909]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
'NoneType' object has no attribute 'reserved'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 686, in _run_job
    cmd_copy.exception_handler(ex)
...
cli/core/commands/__init__.py, ln 324, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 574, in default_command_handler
    return op(**command_args)
cli/command_modules/appservice/custom.py, ln 3215, in webapp_up
    current_os = 'Linux' if plan_info.reserved else 'Windows'
AttributeError: 'NoneType' object has no attribute 'reserved'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up -g {} -n {} --html`

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.5.1 *

```

**Comment by yonzhan** [comment]
webapp

**Comment by nordquist** [comment]
So, what is happening with this? Did it go straight to trash can? @AzureAppServiceCLI @antcp

**Comment by panchagnula** [comment]
@nordquist as per the title the deployment issue is not specific to CLI - are you still seeing this issue.
Few things to consider
1. When using CLI please upgrade to the newer version from the current issue - seems like you are using a  very old version
2. App service currently cannot mix windows and linux apps in the same RG, so if you are trying to use the RG that has windows apps you can use it for linux apps & vice versa.

in general az webapp up should take care of #2, if you don't pass a -g in the command but I definitely recommend upgrading to the latest version of azure-cli which has lots of fixes to az webapp up in general.

**Comment by yungezz** [comment]
#14287

**Comment by nordquist** [comment]
It has nothing to do with the version of the CLI as implicated by the fact that there is no way that works. This is the latest message from VS when trying to deploy an Azure Function (..and yes, I have tried setting WEBSITE_RUN_FROM_PACKAGE to 0 (and why this is not default when it never works?)). 

![image](https://user-images.githubusercontent.com/1436622/87141238-1706c980-c2a3-11ea-86ee-52bb334871e8.png)

The "detailed" error is:

```
2020-07-10 11:44:55
System.AggregateException: One or more errors occurred. ---> System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---

System.Exception: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 

===================
```

**Comment by panchagnula** [comment]
@nordquist given this is CLI I am going to focus on getting this working with CLI -> and if using az webapp up, my recommendation would be to use a more recent version, and run the up command from the context of the DIR where you code to be deployed is. and try creating & deploying a new webapp using webapp up. If this is a function app then this command is not supported for it.

If your question is about run as package deployment then please use this repo to https://github.com/projectkudu/kudu. Hope this helps you.

**Comment by panchagnula** [comment]
closing due to lack of response.
