### ISSUE TITLE
SCALE IN/OUT VMSS WITH CUSTOM METRIC IS IMPOSSIBLE USING AZURE CLI

### ISSUE THREAD

**Issue by edkrizo** [Azure/azure-cli#13908]
**Is your feature request related to a problem? Please describe.**

When a scale in/out operation is issued to Azure virtual machine Scale with custom metric, the operation fails. An example command issued is  az monitor autoscale update --count 2 --min-count 2  . This command fails with error message " Exception of type 'Microsoft.WindowsAzure.Management.Monitoring.MonitoringServiceException' was thrown.. [Code: "UnsupportedMetric"]". 

The same command runs successfully when vmss has no custom metrics.

**Describe the solution you'd like**

Be able to run scale in/out command with az-cli to VMSS that has custom metric 
**Describe alternatives you've considered**

These same operations are being carried out today with rest api calls. A get and patch requests are being issued to VMSS to scale in/out.
**Additional context**

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by qwordy** [comment]
I create autoscale rules using “az monitor autoscale rule create” and then run “az monitor autoscale update”. It succeeds. Could you share the commands that you use to create custom metrics and rules? And could you append “--debug” to the failed command and paste the output? I need these logs to locate the problem.
I check the code of Azure CLI. "autoscale update” is written in 2018 and has not been updated for two years.

**Comment by qwordy** [comment]
@MyronFanQiu Is the related PR merged?

**Comment by MyronFanQiu** [comment]
> @MyronFanQiu Is the related PR merged?

Yes. According to our email thread, custom metric should be used with namespace together.  https://github.com/Azure/azure-cli/pull/14255 has been merged.
