### ISSUE TITLE
[webapp]:Import App Service Certificates into a Web App using the Azure CLI

### ISSUE THREAD

**Issue by tsgenge** [Azure/azure-cli#13907]
**Is your feature request related to a problem? Please describe.**
We're using App Service Certificates rather than PFX files imported into Certificates in the Key vault. The problem is the key vault "certificate" created during the enrollment process goes into the Secrets category in the Key Vault. Consequently, the **az webapp config ssl import** command doesn't find the certificate in the key vault. 

**Describe the solution you'd like**
I'd like the ssl import command to also check the secrets category in the keyvault if the certificate by the name provided cannot be found. I know, I know, the actual root cause here is the App Service Certificate creation process using the wrong key vault category! But, we can import App Service Certificates into an App Service via the Web UI, so it's be great to be able to do it in the Azure CLI too.

**Describe alternatives you've considered**
We have to export the app service certificate to PFX, then import it into the key vault again, this time to the Certificate type. *sigh*

**Additional context**
We have to do the PFX import every year. What a BORE.

**Comment by yonzhan** [comment]
webapp

**Comment by Kotasudhakarreddy** [comment]
@ThejaChoudary - try to repro the issue.

**Comment by panchagnula** [comment]
@tsgenge APP service certificates do use KV - however you cannot use the Import app service certificate command for App service certificates - we will have separate commands for those in the future. Thanks!

**Comment by panchagnula** [comment]
We don't have an ETA on supporting this - we will add a milestone when we have a timeline to share.

**Comment by panchagnula** [comment]
@singlessis is working currently on this

**Comment by btardif** [comment]
@panchagnula @singlessis  any updates on this one?

**Comment by panchagnula** [comment]
> @panchagnula @singlessis any updates on this one?

Still in PR @btardif!
