### ISSUE TITLE
CLI Support for private links for exporting/importing managed disks

### ISSUE THREAD

**Issue by ramankumarlive** [Azure/azure-cli#13917]
**Resource Provider**
Microsoft.Compute

**Description of Feature or Work Requested**

Customers can export from or import to Managed Disks without attaching them to a VM. If a user has sufficient permissions, he/she can generate a Shared Access Signature (SAS) URI of the underlying VHD of Managed Disks and then use the SAS URI to download/upload VHD. A SAS URI consists of the FQDN of the underlying hidden storage account where VHD is stored as a page blob and query parameters comprising the SAS token that has all of the information necessary to grant read/write access to the VHD. SAS gives persistent and unaudited access to the disks without any trace. Customers are worried that a malicious employee can download their data from home without any trace.

Networking Resource Provider (NRP) provides a mechanism, named Private Links that allows an onboarded Azure services such as Storage accounts, Azure SQL to associate a resource to a NRP private endpoint resource (associated to a VNET/subnet). Once the private endpoint is associated, network reads from the private endpoint are tagged with the ID of the private link. This lets the service filter out reads/writes from outside the customer's private endpoint.  Moreover, Traffic between customers' virtual network and the service travels the Microsoft backbone network. Customers are not required to expose their services to the public internet. 

Now you can leverage Private Links for restricting the export of VHD from or the import of VHD to Managed Disks from your Azure VNET only. You can create an instance of the new resource called DiskAccess, and link it to your VNET in the same subscription by creating a private endpoint. A DiskAccess object owns a special hidden Storage account (prefixed md-impexp). The FQDN of the Storage account is mapped to a private DNS in your VNET. Any calls to the Storage account from the VNET is routed via the private DNS over the Microsoft backbone network to the Storage account.

Disk users must associate a disk with an instance of DiskAccess to export/import the data via Private Links. Disk RP uses an already existing md-impexp Storage account associated with a private link or provisions new md-impexp storage accounts under the same private link if many disks are exported at the same time. When Disk RP provisions a new md-impexp storage account, it will inform NRP about it which will map the FQDN of the storage account with a private DNS in customers’ VNET.

You can find more details here: https://github.com/ramankumarlive/manageddisksprivatelinks

**Minimum API Version Required**
2020-05-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/9552

**Target Date**
7/10 for "Enterprise" M4 milestone

**Comment by yonzhan** [comment]
Private Link

**Comment by yungezz** [comment]
service not ready, feature isn't ready.

**Comment by houk-ms** [comment]
Supported now.
