### ISSUE TITLE
Support 'Delete' eviction policy for Azure Spot Standalone VMs

### ISSUE THREAD

**Issue by rakeshakkera** [Azure/azure-cli#13918]
**Is your feature request related to a problem? Please describe.**
Currently Azure Spot standalone VMs only support eviction policy of 'Deallocate'. We have made changes in the CRP service for standalone Spot VMs to support 'Delete' eviction policy as well. Changes need to be made in Azure CLI to support this.

**Describe the solution you'd like**
Currently Azure CLI blocks choosing 'Delete' eviction policy for Standalone Spot VMs. Changes need to be made to support this. Here is the link to the swagger PR for this change: Azure/azure-rest-api-specs#9743

**Describe alternatives you've considered**
NA

**Additional context**
Swagger PR: Azure/azure-rest-api-specs#9743

**Comment by qwordy** [comment]
Add to S172.

**Comment by qwordy** [comment]
As we talked in Teams, it is already supported in Azure CLI. 
```
az vm create -h
--eviction-policy              : The eviction policy for the Spot priority virtual machine.
                                     Default eviction policy is Deallocate for a Spot priority
                                     virtual machine.  Allowed values: Deallocate, Delete.
az vmss create -h
--eviction-policy         [Preview] : The eviction policy for virtual machines in a
                                          Spot priority scale set. Default eviction policy is
                                          Deallocate for a Spot priority scale set.  Allowed values:
                                          Deallocate, Delete.
```
Could you test and confirm it?

**Comment by qwordy** [comment]
Hi Rakesh, Do I need to remove the "preview" label of --eviction-policy? Is it in preview?

**Comment by rakeshakkera** [comment]
Hi @Feiyue Yu<mailto:Feiyue.Yu@microsoft.com>,

Please remove the preview label. It should not be in preview?

-Rakesh
