### ISSUE TITLE
AZ VM Run-Command not setting env vars

### ISSUE THREAD

**Issue by abelbarrera15** [Azure/azure-cli#13914]
If I use:
`
 az vm run-command invoke -g myRgGroup -n myVmName -command-id RunShellScript --scripts "export HADOOP_HOME=/usr/local/hadoop" `

It does not set the HADOOP_HOME var. I've confirmed by running 

`
 az vm run-command invoke -g myRgGroup -n myVmName -command-id RunShellScript --scripts "export"  `

after and it still does not return the HADOOP_HOME var. Can RunShellScript not set env vars? Or is this a bug?

**Comment by yonzhan** [comment]
@qwordy please take a look

**Comment by abelbarrera15** [comment]
I was able to resolve this! It seems that the root file system is not appendable and if you want to make edits to files on it-- you need to first cp them to a tmp file, then edit the tmp file with what you want the file to be and then sudo cp on top of the old file (overwrite) so that the root file now contains the things needed in addition. Appenditure like: "_export THING2=usr/local/bin" >> /etc/environment_" won't work. Just an FYI. I'm not sure if this is AZ CLI interating w/ root specific or not. Functionally, my workaround works for my issue, but this is not reflective of that behavior should or should not be this way. This should still be investigated if y'all wish @yonzhan , @qwordy
