### ISSUE TITLE
Need better diagnostic logs

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1392]
I'm trying to add additional info to [this issue,](https://github.com/Azure/azure-cli/issues/1391) but I don't seem to be getting ANY sort of log whatsoever in `~/.azure`...

**Comment by yugangw-msft** [comment]
@derekbekoe can help

**Comment by colemickens** [comment]
Ideally, there would be a log running *all the time* that contains the output of the command with `--debug`.

We have users that experience errors, and then when I go to get support, I need a correlation ID... but it's far too late for that. If we had a continuous, running debug log, it would be trivially to have users send that when they encounter issues.

Though, with that last part, my earlier issue about redacting secret tokens from the logs is again potentially relevant.

**Comment by derekbekoe** [comment]
There is file logging available. Early on, we made the decision to make this opt-in.

Set the environment variable `AZURE_CLI_ENABLE_LOG_FILE`.
e.g. `export AZURE_CLI_ENABLE_LOG_FILE=1`

You can also set the log dir with `AZURE_CLI_LOG_DIR`.

Created https://github.com/Azure/azure-cli/issues/1399 in relation to this.

**Comment by colemickens** [comment]
Cool, didn't know we had that.

Is it documented? Can we get an issue for that if not?

Is there any point in me bringing up the opt-in behavior? It's a bit hard to ask users to spend their time repro-ing flaky issues for us when we could just ask them to send the log from when they experienced a real issue....

Thanks.

**Comment by mayurid** [comment]
I don't believe this is documented. I have added a documentation label to this and will work with @derekbekoe and @jasonrshaver to have this added.

**Comment by derekbekoe** [comment]
@colemickens There were a few reasons for going with opt-in:
1. Logs can contain sensitive info (tokens, subscription IDs, SSH keys, command results, etc.).
2. Whilst we have size limits on the log files (rotating logs of 10MB max. for each log file and 6 log files in total), they take up disk space which may be unexpected for the user.
3. Access to the log files from multiple concurrent `az` executions was a concern, especially if we made it a default.

**Comment by colemickens** [comment]
Okay, thank you for the details, makes sense. The env variables seem to be a good way to deal with this then.

**Comment by derekbekoe** [comment]
Closing.
https://github.com/Azure/azure-cli/issues/1399 tracks a few improvements to this.
