### ISSUE TITLE
az group deployment create

### ISSUE THREAD

**Issue by dijonsmit** [Azure/azure-cli#13926]
## Describe the bug

**Command Name**
`az group deployment create`

**Errors:**
```
Deployment failed. Correlation ID: 7da346cc-4508-446b-b328-2b3d615f3a9c. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
...
          }
        ]
      }
    ]
  }
}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group deployment create --resource-group {} --template-uri {} --parameters {}`

## Environment Summary
```
Linux-4.15.0-1083-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

```

**Comment by zhoxing-ms** [comment]
This is a problem returned by service, which needs to be investigated by the service team.
> Correlation ID: 7da346cc-4508-446b-b328-2b3d615f3a9c.

**Comment by snaheth** [comment]
This could be happening for a variety of reasons so it'd be useful to gain some more understanding around what you're deploying. If you're still experiencing the same problem, feel free to reopen this issue and provide some additional context (e.g. the resource type, operation, HTTP method) and a newer Correlation ID.
