### ISSUE TITLE
cli help text outdate: unsupported kubernetes version on the az aks create

### ISSUE THREAD

**Issue by tzachie** [Azure/azure-cli#13922]
Hello Team,

I have noticed our documentations on page : https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create is not updated.

Please update the below example with a newer version of AKS for successful customer experience

The current state:  will generate a 'Bad Request "
"az aks create -g MyResourceGroup -n MyManagedCluster --kubernetes-version 1.12.6"

Full error detail: 
Operation failed with status: 'Bad Request'. Details: Version 1.12.6 is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list

Recommend to update the example version or refer to an updated version list.

Current Any version 1.14.7. will be working
Default Azure creation will use Kubernetes version 1.15.11

Screenshot:
![aks_create_err](https://user-images.githubusercontent.com/32248613/84255711-a9d50c80-ab1b-11ea-8feb-812d1f6b3975.png)

Thank you,
Tzachi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest&source=docs)
* Content Source: [src/azure-cli/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
aks
