### ISSUE TITLE
Error when executing 'az webapp config access-restriction set'

### ISSUE THREAD

**Issue by sven73a** [Azure/azure-cli#13928]
When I run the command `az webapp config access-restriction set --resource-group <resource group> --name <name appservice> --use-same-restrictions-for-scm-site false`

It will execute the command with the expected result, but it also gives an error/warning

```
az : Command group 'webapp config access-restriction' is in preview. It may be changed/removed in a future release.
At line:1 char:12
+  $output = az webapp config access-restriction set --resource-group " ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Command group '...future release.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

I want to run it in a pipeline, but due the error/warning the pipelines fails.
I see it on Azure CLI versions 2.2.x, 2.7.0 & 2.5.1

How can I prevent the warning/error to occur ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c788e908-cee3-ae46-fac4-956d0606ad76
* Version Independent ID: 2ed69bfd-bb05-3d09-072e-00e505856fba
* Content: [az webapp config access-restriction](https://docs.microsoft.com/en-us/cli/azure/webapp/config/access-restriction?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/access-restriction.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/access-restriction.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@sven73a can you give us more details on the error/warning you are referring to here? CLI shouldn't error out if the command hasn't failed - more details here will help us root cause this better.

**Comment by sven73a** [comment]
All information is in the opening post. There is no much more to tell. Please let me know what more yo want to know.

**Comment by sedvardsen** [comment]
@sven73a adding ` --only-show-errors` to the command seem to make it play ball with pipelines

**Comment by panchagnula** [comment]
@sven73a the command throws an error only something has actually failed on our end - & an error should be reported and not ignored by the pipeline as well. with regards to warning its possible that the in preview message of this command is being interpreted as a warning as a pipeline for that what @sedvardsen recommended above is the best option, to suppress warning messages. Hope this helps. Thanks!

**Comment by sven73a** [comment]
OK. thnx for the work-around I will try it tomorrow. But for mine understanding is the warning/error for this particular command a bug in the command or is it by design?

**Comment by sedvardsen** [comment]
Looks like it is an issue for all preview-methods - i.e all methods that throws a warning no matter what

**Comment by sven73a** [comment]
With the option `--only-show-errors` it works nicely. Thank again.

**Comment by jiasli** [comment]
@sven73a, glad to know it work for you. The `--only-show-errors` option was introduced in https://github.com/Azure/azure-cli/pull/12544, and has been documented at [CLI configuration values and environment variables](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-values-and-environment-variables). There is also a corresponding config option `[core] only_show_errors` controlling this behavior.
