### ISSUE TITLE
install failed on SuSE 11SP4

### ISSUE THREAD

**Issue by Lickkylee** [Azure/azure-cli#1393]
I followed steps to install the latest release on SUSE 11SP4 and failed with below error. Anyone has  clue?  

# zypper --non-interactive install gcc libffi-devel python-devel openssl-devel
 # curl -L https://aka.ms/InstallAzureCli | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
104  1048  104  1048    0     0     51      0  0:00:20  0:00:20 --:--:--  3326
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /tmp/azure_cli_install_tmp_QAMG.
######################################################################## 100.0%
Running install script.
Traceback (most recent call last):
  File "/tmp/azure_cli_install_tmp_QAMG", line 145, in <module>
    main()
  File "/tmp/azure_cli_install_tmp_QAMG", line 127, in main
    install_dir = get_install_dir()
  File "/tmp/azure_cli_install_tmp_QAMG", line 99, in get_install_dir
    prompt_message = 'In what directory would you like to place the install? (leave blank to use {}): '.format(DEFAULT_INSTALL_DIR)
ValueError: zero length field name in format

**Comment by derekbekoe** [comment]
@Lickkylee What version of Python was installed on the machine?
Based of the [SUSE documentation](https://www.suse.com/releasenotes/x86_64/SUSE-SLES/11-SP4/#id349370) SUSE 11SP4 comes with Python 2.6.9 by default.

The CLI supports Python 2.7 and up.

I have created https://github.com/Azure/azure-cli/issues/1400 so we can should a more user-friendly error message.

**Comment by Lickkylee** [comment]
Thanks derekbekoe. I will try if this works on suse 12.
