### ISSUE TITLE
Make it easier to add and update extensions

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli#13930]
**Is your feature request related to a problem? Please describe.**

Our team has a number of automation scripts, which as part of the bootstrapping install necessary az CLI extensions. Unfortunately, over time extensions go stale and it's problematic to get them add or update, depending on the current state of extension.

Example: I have extension front-door installed and blueprint not installed.

Attempt to add an existing extension: warning is printed, no attempt to update.

```
$ az extension add --name front-door
Extension 'front-door' is already installed.
```

Attempt to update an extension w/o new updates: fails with error (why ?!?!).

```
$ az extension update --name front-door
No updates available for 'front-door'. Use --debug for more information.
```

Attempt to update extension that's not installed locally: fails with error.

```
$ az extension update --name blueprint
The extension blueprint is not installed.
```

**Describe the solution you'd like**

I'd like to be able to add-or-update, or update-or-add, or update-all.

Add-or-update: `az extension add --name front-door --update` - will add, if extension is missing, update to latest version otherwise.

Update-or-add: `az extension update --name front-door --add` - will update, if extension is present, add latest version otherwise.

Update-all: `az extension --update-all` - will update all extensions to their latest versions.

**Alternative**

At least make `az extension update` not fail, if there're no updates: it's hard to tell "update failed because problems" from "update failed because no updates" apart.

**Comment by yonzhan** [comment]
add to S172

**Comment by yungezz** [comment]
thanks for the feedback @wasker . We're working on extension upgrading recently.  @fengzhou-msft could share more instruction on this after released. Pls give it a try and let us know if any feedback. :)

**Comment by fengzhou-msft** [comment]
@wasker `az extension update` does not fail for no updates available from `2.11.0`, just prints a warning message.
 
I have submitted #15083 to support `az extension add --upgrade`, it will install or update the extension.

As for updating all extensions, we introduced `az upgrade` in `2.11.0` to update azure-cli and all installed extensions.

**Comment by wasker** [comment]
@fengzhou-msft Thanks for heads up!

With regards to `az upgrade` - does it work in Azure Cloud Shell environment? I.e., is it able to upgrade azure-cli itself there?

**Comment by fengzhou-msft** [comment]
@wasker `az upgrade` is not supported in Cloud Shell as you cannot gain sudo permission. Cloud Shell incorporates new versions of azure-cli when building, usually we're in sync for the 3-week release cadence.
