### ISSUE TITLE
VMSS: confirmation on specify NOT latest as image version of specific Markplace image 

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#13931]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62
**VMSS**

Pinning VMSS to a specific Marketplace image version may cause service outage in future. We have seen several support cases and sev2s because of this. Customers should pick "latest" as the image version whenever possible. This allows VMSS to auto upgrade when a newer version is available.

IaaS Portal automatically puts "latest" as the image version for any VMSS deployment from Marketplace. However, in Powershell and CLI, customers still have the option to specify version. We need to warn customers when they are deploying VMSS pinned to a specific image version from Azure Marketplace, and ask them to consider using "latest" as the image version.

Ask [Powershell and CLI]
Warn customers when they are deploying VMSS pinned to a specific image version from Azure Marketplace, and ask them to consider using "latest" as the image version.

https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/requesting-confirmation-from-cmdlets?view=powershell-7

https://msazure.visualstudio.com/One/_workitems/edit/5730841/

**Comment by qwordy** [comment]
Reasonable ask

**Comment by qwordy** [comment]
I have to warn that this request is a breaking change.
Azure CLI is not an interactive client. Most users use Azure CLI for automation. If we ask “Do you still want to proceed?” and wait for a response from user, it is a breaking change.
We must be careful.

**Comment by yungezz** [comment]
hi @qwordy thanks for raising the good point! per communication with service team, they're ok to a warning message. Could you pls take care of this in this sprint? thanks.

**Comment by DailyTech** [comment]
But PLease, what is the Powershell/CLI command line to specify it musst use the "latest" image ??? please what is it ?

**Comment by DailyTech** [comment]
New-AzVmss `
  -ResourceGroupName "TEstScaleSet" `
  -VMScaleSetName "TestScaleSet" `
  -Location "southafricanorth" `
  -VirtualNetworkName "TestVnet" `
  -SubnetName "TestSubnet" `
  -version "latest" `
  -PublicIpAddressName "TestPubIP" `
  -LoadBalancerName "TestLB" `
  -Credential $cred

**Comment by DailyTech** [comment]
Ive tried -imageversion "latest" ? and a few other, nothing seems to be valid ?

**Comment by zhoxing-ms** [comment]
@DailyTech Hi, the command you give is PowerShell command. If it is a problem related to Azure PowerShell, please submit it to https://github.com/Azure/azure-powershell/issues

In addition, may I ask does CLI also have this issue? If so, please add `--debug` after the executed CLI command, and then send the printed information to me. My email address is Zhou.Xing@microsoft.com
