### ISSUE TITLE
[Telemetry] Client telemetry for command performance

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#13932]
We need to be able to send **command running time** as client telemetry, so that we can analyze the performance of each command using a data-driven model. 

```
> az rest -h --verbose

...
Command ran in 0.147 seconds (init: 0.064, invoke: 0.083)
```

**Comment by yungezz** [comment]
this could be tracked at client telemetry

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls close the issue with PR link? thanks

**Comment by fengzhou-msft** [comment]
Close via #14273
