### ISSUE TITLE
az ad app permission admin-consent --id  $serverApplicationId Error

### ISSUE THREAD

**Issue by yoshuhire** [Azure/azure-cli#13934]
## Describe the bug

**Command Name**
`az ad app permission admin-consent`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 709, in _run_job
    cmd_copy.exception_handler(ex)
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad app permission admin-consent --id {}`

## Environment Summary
```
Linux-4.15.0-1083-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

```

**Comment by yungezz** [comment]
hi @yoshuhire Did you see the error at Cloudshell?

**Comment by yoshuhire** [comment]
@yungezz 

Yup. This error showed up on the cloudshell.
Once I tried the command on the local pc, it succeeded without any issue.

The only difference is the python version. 
Azure CLI installed on my local pc has python 3.6.6.

**Comment by yungezz** [comment]
hi @yoshuhire sorry for late response, this is due to an known issue in Cloudshell #11749. A workaround is to run `az login` again.

**Comment by yonzhan** [comment]
@yoshuhire was your issue resolved by above solution?

**Comment by arrownj** [comment]
Close this issue first, the cloud shell issue will be tracked in #11749 .
