### ISSUE TITLE
--content-types-to-compress format for list[str]

### ISSUE THREAD

**Issue by amanjain** [Azure/azure-cli#13935]
## Describe the bug

**Command Name**
`az cdn endpoint create`

**Errors:**
```
Refuse str type as a valid iter type.
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
python3.8/site-packages/msrest/serialization.py, ln 754, in serialize_data
    return self.serialize_type[iter_type](
python3.8/site-packages/msrest/serialization.py, ln 831, in serialize_iter
    raise SerializationError("Refuse str type as a valid iter type.")
msrest.exceptions.SerializationError: Refuse str type as a valid iter type.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cdn endpoint create -g {} --tags {} --name {} --origin {} --profile-name {} --enable-compression {} --no-http {} --no-https {} --origin-host-header {} --content-types-to-compress {}`

## Environment Summary
```
macOS-10.15.5-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.7.0

```

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by amanjain** [comment]
issue is with ```--content-types-to-compress``` flag.

**Comment by hytao** [comment]
can you share a sample command that reproduce the issue? Ideally you should provide a comma separated string as input.

**Comment by gabriel-kohen-by** [comment]
Example of reproducing this:
```
          az cdn endpoint create --name $AZURE_CDN_ENDPOINT \
            --profile-name $AZURE_CDN_PROFILE \
            --origin $WEB_ENDPOINT \
            --enable-compression \
            --origin-host-header $WEB_ENDPOINT \
            --content-types-to-compress {text/plain,text/html,text/css,text/javascript,application/x-javascript,application/javascript,application/json,application/xml,image/vnd.microsoft.icon,image/svg+xml} \
            --tags "${TAGS_TO_ADD[@]}"

```
Or 
```
          az cdn endpoint create --name $AZURE_CDN_ENDPOINT \
            --profile-name $AZURE_CDN_PROFILE \
            --origin $WEB_ENDPOINT \
            --enable-compression \
            --origin-host-header $WEB_ENDPOINT \
            --content-types-to-compress "text/plain,text/html,text/css,text/javascript,application/x-javascript,application/javascript,application/json,application/xml,image/vnd.microsoft.icon,image/svg+xml" \
            --tags "${TAGS_TO_ADD[@]}"

```

Can anyone show an example (or add to the documentation on how to use `content-types-to-compress` with multiple types?
Thanks!

**Comment by t-bzhan** [comment]
@gabriel-kohen-by , space separated list is widely used in azure CLI for collection like parameters. Azure CLI will parse the multiple values separated  by space following "--content-types-to-compress" into a collection.
In you case, your command would go like

>           az cdn endpoint create --name $AZURE_CDN_ENDPOINT \
>             --profile-name $AZURE_CDN_PROFILE \
>             --origin $WEB_ENDPOINT \
>             --enable-compression \
>             --origin-host-header $WEB_ENDPOINT \
>             --content-types-to-compress text/plain text/html text/css text/javascript application/x-javascript application/javascript application/json application/xml image/vnd.microsoft.icon image/svg+xml \
>             --tags "${TAGS_TO_ADD[@]}"

BTW, quote is needed if you value itself contains spaces.

**Comment by mgressman** [comment]
@t-bzhan , did you actually run this command?

When I run the command I get the error 'UnrecognizedArgumentError: unrecognized arguments: text\html'.

So far, I have found no syntax that will allow me to use the --content-types-to-compress switch and no documentation to give direction.
