### ISSUE TITLE
Typo for VirtualMachineScaleSets

### ISSUE THREAD

**Issue by bowang-666** [Azure/azure-cli#13945]
some `VirtualMachineScaleSets` are `VirtualMachineScaleSet` missing 's'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
aks

**Comment by yungezz** [comment]
hi @bowang-666 could you be specific which doc is missing `s`? in AKS command doc?
