### ISSUE TITLE
CLI support for new storage account properties

### ISSUE THREAD

**Issue by fhryo-msft** [Azure/azure-cli#13942]
**Resource Provider**
Azure Storage (SRP)

**Description of Feature or Work Requested**
We added two properties on storage account (allowBlobPublicAccess, minimumTlsVersion) since SRP API 2019-04. We need the CLI to support these two properties so customers can configure them with CLI.

**Minimum API Version Required**
SRP 2019-04

**Swagger Link**
SRP Swagger is being updated now. It's expected to go live by 6/18. I will provide the link once it's available.

**Target Date**
7/15/2020 or sooner iteration that fits.

**Comment by yonzhan** [comment]
add to S172
