### ISSUE TITLE
azure-multiapi-storage setup.py is not correct

### ISSUE THREAD

**Issue by arrownj** [Azure/azure-cli#13943]
**Describe the bug**

[setup.py](https://github.com/Azure/azure-multiapi-storage-python/blob/726b1b0cf3c61aae52fc410451f968cbc4e675bc/setup.py#L59) of `azure-multiapi-storage` is not correct. It will install `azure-nspkg` no matter it is Python 2 or Python 3 environment.

If it is Python 3, it will add a `__init__.py` file under `azure` folder, which will ruin all the namespace package.

**To Reproduce**
Not avaiable

**Expected behavior**
[setup.py](https://github.com/Azure/azure-sdk-for-python/blob/64cc053e589691da22fed7a47611199818c99b2b/sdk/core/azure-core/setup.py#L73) of `azure-core` can be a reference.

**Environment summary**

**Additional context**

**Comment by arrownj** [comment]
Storage SDK related.

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
done

**Comment by Juliehzl** [comment]
fixed in https://github.com/Azure/azure-multiapi-storage-python/pull/26
