### ISSUE TITLE
AZ CLI support for Network Virtual Appliance

### ISSUE THREAD

**Issue by naveenchekuri** [Azure/azure-cli#13947]
**Resource Provider**
NFVRP (Microsoft.Network)

**Description of Feature or Work Requested**
NetworkVirtualAppliance is a new service that we want to onboard. Each NetworkVirtualAppliance has child resources called virtualApplianceSites and also need to support GetNetworkVirtualApplianceSkus

**Minimum API Version Required**
2020-05-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/9682
https://github.com/Azure/azure-rest-api-specs/pull/8270
https://github.com/Azure/azure-rest-api-specs/pull/8010
https://github.com/Azure/azure-rest-api-specs/pull/9357

**Target Date**
Release Target date 07/15/2020

**Comment by yonzhan** [comment]
add to S172
