### ISSUE TITLE
Azure devops cli

### ISSUE THREAD

**Issue by ankita11194** [Azure/azure-cli#13944]
HI,
az devops user list  -o table --query ["members[].user[].displayName[] , members[].lastAccessedDate[]"] --top 2
Column1                           Column2
--------------------------------  --------------------------------
Aaron                               Abel 
2020-05-20T19:02:53.006463+00:00  2020-03-24T14:42:21.654520+00:00

I want the format to be column1 as "name" and column 2 as "date" and in tabular format.
can you help?

**Comment by yonzhan** [comment]
devops
