### ISSUE TITLE
Az CLI doesn't allow specific special characters 

### ISSUE THREAD

**Issue by cmneubaum** [Azure/azure-cli#13949]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When creating Azure Metric Alerts in the UX, a dimension value can contain a ',' or a '|'. But when creating a Metric Alert using CLI and inserting a dimension value that contains either ',' or '|' you get the following error:
usage error: --condition {avg,min,max,total,count} [NAMESPACE. ]METRIC {=,!=,>,>=,<,<=} THRESHOLD
						 [where DIMENSION {includes,excludes} VALUE [or VALUE ...]
						 [and DIMENSION {includes,excludes} VALUE [or VALUE ...] ...]] 

**To Reproduce**
Generates error:
az monitor metrics alert az monitor metrics alert create --name "Test" --resource-group "Test1" --scopes /subscriptions/SUBID/resourceGroups/RG/providers/microsoft.insights/components/AI_COMPONENT--condition "count dependencies/count > 10 [where dependency/target includes tcp:myapp-sqldbserver.database.windows.net,1433 | SqlDB22 [and dependency/resultCode includes 200]]" --window-size 5m --evaluation-frequency 5m --severity 3

**Expected behavior**
Would expect this to succeed as it does when creating alerts in the UX. 

Only way I can get this to work is by removing the part of the dimension value that contains a ',' and '|'. So the following will work:
az monitor metrics alert az monitor metrics alert create --name "Test" --resource-group "Test1" --scopes /subscriptions/SUBID/resourceGroups/RG/providers/microsoft.insights/components/AI_COMPONENT --condition "count dependencies/count > 10 [where dependency/target includes tcp:datapptho-squibbledbserver.database.windows.net [and dependency/resultCode includes 200]" --window-size 5m --evaluation-frequency 5m --severity 3 --description ""

**Environment summary**
Az CLI v2.7.0

**Additional context**
Alerting PG verified the issue is on the CLI side.

**Comment by yonzhan** [comment]
add to S172

**Comment by MyronFanQiu** [comment]
@cmneubaum Thanks for raising this issue. Will fix this one as the plan.
