### ISSUE TITLE
"az keyvault secret set" failed with error "Max retries exceeded attempting to connect to vault"

### ISSUE THREAD

**Issue by Andriy-dev** [Azure/azure-cli#13952]
## Describe the bug

**Command Name**
`az keyvault secret set`

**Errors:**
```
Max retries exceeded attempting to connect to vault. The vault may not exist or you may need to flush your DNS cache and try again later.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault secret set --vault-name {} --name {} --value {}`

## Environment Summary
```
Linux-5.3.0-1028-azure-x86_64-with-debian-9.11
Python 3.6.5

azure-cli 2.1.0 *

```

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by yungezz** [comment]
hi @Andriy-dev could you pls share more repro steps?

**Comment by jrudley** [comment]
FYI, this error will happen if you try to create a secret to a vault that does not exist

**Comment by yungezz** [comment]
> FYI, this error will happen if you try to create a secret to a vault that does not exist

thanks @jrudley for the info. If this is the case, the error message should be improved. Would you pls mind to create a new issue for track investigation? thanks.

**Comment by bim-msft** [comment]
I think the message is quite clear "The vault may not exist".
If this happened on an existing vault, you can reopen this issue.

**Comment by moirf** [comment]
> I think the message is quite clear "The vault may not exist".
> If this happened on an existing vault, you can reopen this issue.

As per the document it should create if not already there.
https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-cli
Also if this is the case, how to create secret via cli?

**Comment by aayadi-ey** [comment]
From my powershell ISE it is creating the secret if doesn't exist, but in a Azure DevOps pipeline it is failing. any idea?

**Comment by evelyn-ys** [comment]
@moirf @aayadi-ey 
It will create if the secret doesn't exist.
The error message is saying that the vault doesn't exist. You should use `az keyvault create` to create a vault first.

**Comment by opor-thorleifsson** [comment]
same issue here as @aayadi-ey.
If I run: az keyvault key create  --vault-name {} --name {} locally on my terminal it works fine but as soon as the same is ran as part of AzureCLI@2 task in devops it will fail with error "Max retries exceeded attempting to connect to vault

**Comment by bhordupur** [comment]
> From my powershell ISE it is creating the secret if doesn't exist, but in a Azure DevOps pipeline it is failing. any idea?

Same here. It would work from CLI of mac but when we run this from GitLab pipeline it does not work. I can confirm you that secrets exist already.

**Comment by bhordupur** [comment]
> @moirf @aayadi-ey It will create if the secret doesn't exist. The error message is saying that the vault doesn't exist. You should use `az keyvault create` to create a vault first.

And it never does. We have the secret without any value and when we run command from CLI on our work station it works and same exact command would throw that error from GITLAB pipeline.

**Comment by bhordupur** [comment]
> FYI, this error will happen if you try to create a secret to a vault that does not exist

That's is not true as per [this](https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az_keyvault_secret_set) doc

**Comment by evelyn-ys** [comment]
@bhordupur Sounds like something not going well with 'gitlab pipeline'. Could you share more about gitlab pipeline? What's the env difference for local CLI and pipeline CLI? Can you provide the failure debug log?

**Comment by Mullenmaster** [comment]
This will happen when the logged-in account has attempted and failed multiple times to set a secret in a key vault. 

E.g., a member of an organization using Azure CLI logged in as the same service principal as used on a pipeline, attempted to set a secret and failed up to the max retry limit. 

The solution to this issue is to reset the count for the service principal...but how @houk-ms ?

**Comment by evelyn-ys** [comment]
The retry counts is defined in Python SDK which is global for all Azure mgmt. plane SDK, I believe. So it seems not possible for CLI to expose some argument to change that... @Mullenmaster

**Comment by MeaningOfLights** [comment]
To reduce the confusion and narrow down on what the actual bug is please see my experience here. https://stackoverflow.com/a/71580218/495455
