### ISSUE TITLE
Unable to find user with upn 'user@domain.com'

### ISSUE THREAD

**Issue by BassamBallaji** [Azure/azure-cli#13956]
I typed this cmd to grant permission for keyvault to access storage account with upn of my address (as the only user of the subscription) in order to manage storage access keys:

`az keyvault set-policy -n keyvault02 --upn user@domain.com --storage-permissions get list delete set update regeneratekey getsas listsas deletesas setsas recover backup restore purge`

but I faced this error message :

`Unable to find user with upn 'user@domain.com'
Unable to get object id from principal name`

Is there an issue with AD licence (requiring a particular licence) or something else?

Waiting for your help

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by bim-msft** [comment]
Hi @BassamBallaji , you may use command `az ad user list` to make sure your upn is existing. As far as I can see, some upn formats are not email-like, eg: `xxxx_microsoft.com#EXT#@AzureSDKTeam.onmicrosoft.com`

**Comment by BassamBallaji** [comment]
Hello @bim-msft , thnks for answer, this is the reason behind the issue, I had to pass this particular format.
