### ISSUE TITLE
Not able to create image in the container registry

### ISSUE THREAD

**Issue by tmastana** [Azure/azure-cli#13951]
## Describe the bug

**Command Name**
`az acr create`

**Errors:**
```
The registry DNS name myregistry.azurecr.io is already in use. You can check if the name is already claimed using following API: https://docs.microsoft.com/en-us/rest/api/containerregistry/registries/checknameavailability
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr create --name {} --resource-group {} --sku {} --admin-enabled {}`

## Environment Summary
```
Linux-4.15.0-1083-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

```

**Comment by yonzhan** [comment]
acr

**Comment by yugangw-msft** [comment]
@tmastana, did this registry belong to you, and you deleted and tried to recreate? If yes, please let me know; otherwise this is by-design as the name is already taken

**Comment by yugangw-msft** [comment]
please reactivate with more details
