### ISSUE TITLE
az cli failing on webapp deployment

### ISSUE THREAD

**Issue by asnogordo** [Azure/azure-cli#13958]
## Describe the bug

**Command Name**
`az webapp deployment user set`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment user set --user-name {} --password {}`

## Environment Summary
```
Linux-5.4.0-33-generic-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by asnogordo** [comment]
Fresh installation of Ubuntu 20.04 LTS. I ran az login, when azure cli was not installed.

```shell
pi@copper:~/git/azure-mol-samples-2nd-ed/03/prod$ az

Command 'az' not found, but can be installed with:

sudo apt install azure-cli
```
After logging in successfully with 'az login', the az webapp deployment command was run, which is the described in the initial issue.

I was able to resolve my issue by uninstalling the previous az installation, and installing using the [documented azure cli instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest).
```shell
pi@copper:~/git/azure-mol-samples-2nd-ed/03/prod$ sudo apt-get remove azure-cli
```
```shell
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
```

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
duplicate with #13660

**Comment by yungezz** [comment]
hi @asnogordo is your az cli  installed via pypi? If yes, pls see https://github.com/Azure/azure-cli/issues/13343#issuecomment-635811624 for reference.

**Comment by fengzhou-msft** [comment]
@asnogordo yes, following the doc is the right way. The package comes with Ubuntu repo is old and has some issues.

**Comment by yungezz** [comment]
#14011
