### ISSUE TITLE
[ACS] The name argument of the DC/OS browse command doesn't support auto-completion

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1396]
If you type `az acs dcos browse -n <TAB>`, you see the file listings for the CWD, as opposed to the list of current ACS instance names within your subscription. The `-n` flag correctly supports this auto-completion for all other ACS commands, so this appears to be the only one that doesn't support it.

Additionally, auto-completion works for the `-g` parameter for the `az acs dcos browse` command, so it seems like it's just the `-n` flag that needs to be fixed. I'm running macOS Sierra, in case this issue may be platform-specific.

**Comment by thegalah** [comment]
https://github.com/Azure/azure-cli/pull/1460

**Comment by brendandburns** [comment]
I beleive this can be closed...  @derekbekoe

**Comment by lostintangent** [comment]
@brendandburns Yep you definitely fixed this. Thanks!
