### ISSUE TITLE
CLI Nightmare

### ISSUE THREAD

**Issue by techadmin1982** [Azure/azure-cli#13967]
Experiencing same issue while test deploying some ARM templates in Azure. Tested on Local Powershell ISE , Visual Studio Code but no joy. Tested the same ARM templates using old Azure-RM modules from Visual Studio Deployment Project and it worked like charm.
error

This is not good at all. Imagine I was deploying something critical. I was lucky that I have kept AzureRM, new Az Modules and also Azure CLI on my system. But i need someone from MSFT to look into this and let us know. Also, I have checked there are no outages on the regions which could have caused this.

**Comment by techadmin1982** [comment]
![error](https://user-images.githubusercontent.com/42249185/84654536-03c73f00-af2d-11ea-87e3-8b4dbfbd02a0.JPG)

**Comment by yonzhan** [comment]
@techadmin1982  could you please share your detailed CLI command and error info for us to troubleshoot ?

**Comment by techadmin1982** [comment]
@yonzhan - I am trying to deploy a custom RBAC role and assigning that to an existing Group Object.  My ARM template is flawless , it gets deployed fine when run with powershell (Az Modules). However it fails to deploy when i use CLI. I have tested the CLI deployment code both locally (from my laptop) and also from CLI on Azure portal.

Here is the code i am using to deploy the template. Like i said it was working fine this morning , but stopped all of a sudden and started giving me error.
`az deployment sub create `
  --location EastUS `
  --name ExampleDeployment `
  --template-file "$($PSScriptRoot)\azuredeploy.json" `
  --parameters "$($PSScriptRoot)\azuredeploy.parameters.json"`

Error I am getting :
`az : Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: 
/subscriptions/[my subscription id]/providers/Microsoft.Resources/deployments/ExampleDeployment/validate?api-version=2019-07-01 (Caused by 
ResponseError('too many 500 error responses',))
At [location of deploymenyt script on my system]:5 char:1
+ az deployment sub create `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error occurred ...r responses',)):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
`

**Comment by pburkholder** [comment]
I've not worked on Azure in many months so I'm afraid I can't help you here.

**Comment by zhoxing-ms** [comment]
@techadmin1982 Hi, I have two more questions for you
1. May I ask your ARM template works fine in PowerShell, right? If so, what is the corresponding PowerShell command?
2. Please add `--debug` to the original command and email the printed information to me, my email address is Zhou.Xing@microsoft.com, thanks~

**Comment by yungezz** [comment]
if no scripting change but suddenly fail, it's high suspect service issue. While it worth to check why powershell succeeded.

**Comment by techadmin1982** [comment]
> 
> 
> @techadmin1982 Hi, I have two more questions for you
> 
>     1. May I ask your ARM template works fine in PowerShell, right? If so, what is the corresponding PowerShell command?
> 
>     2. Please add `--debug` to the original command and email the printed information to me, my email address is [Zhou.Xing@microsoft.com](mailto:Zhou.Xing@microsoft.com), thanks~

Thank you for your assistance. Ok, corresponding Powershell command would be 

`Param (
[Parameter(Mandatory = $true)]
[String] $location,
[Parameter(Mandatory = $true)]
[String] $SubscriptionId
)
#Logging into Azure Account and selecting working Subscription
#Connect-AzAccount
$context = Get-AzSubscription -SubscriptionId $SubscriptionId
Set-AzContext $context
New-AzDeployment -location $location -TemplateFile "$($PSScriptRoot)\azuredeploy.json" -TemplateParameterFile "$($PSScriptRoot)\azuredeploy.parameters.json"`

I will send you the debug details later today and confirm here.

**Comment by techadmin1982** [comment]
@zhoxing-ms Have sent you the debug logs from my personal outlook email.

**Comment by zhoxing-ms** [comment]
@techadmin1982 Thank you very much for the logs and information you provided. This is a service related problem, and we need the service team to help us to see the cause of the error first.

Could you please view the Activity log on portal after the deployment fails. There is a JSON information corresponding to the failure reason, then please tell me what is the error message and correlationId?

**Comment by techadmin1982** [comment]
> 
> 
> @techadmin1982 Thank you very much for the logs and information you provided. This is a service related problem, and we need the service team to help us to see the cause of the error first.
> 
> Could you please view the Activity log on portal after the deployment fails. There is a JSON information corresponding to the failure reason, then please tell me what is the error message and correlationId?

I checked Activity Logs on my subscription. There is nothing regarding the failures.

**Comment by zhoxing-ms** [comment]
@techadmin1982 May I ask could you find correlationId?

**Comment by snaheth** [comment]
Hi @techadmin1982 - Let me know if you have a newer correlationId for this as @zhoxing-ms also requested.

I was actually able to repro this using an older version of Azure CLI (2.0.76) and a newer version (2.11.1), both of which returned different results. In the former case, Azure CLI returned a parsing error (as it should). In the latter case, I hit the same issue as you (repeated 500s from ARM) since the CLI code didn't automatically parse out the comment for me, leading to an broken template parameter in the request body sent to ARM.

Did you happen to have a comment either before your first curly brace OR after your last (in your JSON file)?....something like the following:
```
// This won't work
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": []
}
// Neither will this
```

If you do - removing the comment/s will fix your issue. If it's something else, please share your --debug logs.

**Comment by techadmin1982** [comment]
unfortunately I am not working on this any longer. I appreciate everyone's help. this issue can be closed.
