### ISSUE TITLE
az ad permission - app_role id??

### ISSUE THREAD

**Issue by edjwhho** [Azure/azure-cli#13969]
Went through this page and found that that there is no mention of getting existing app_role ids from custom app_roles from az ad permission command, its possible to add/delete etc & grant but I have to manually goto the portal/manifest and find out the uuid for the specific app_role ie ( -api-permissions 311a71cc-e848-46a1-bdf8-97ff7156d8e6=Scope ) for custom app_roles and then use the admin consent grant.

`az ad app permission add --id eeba0b46-78e5-4a1a-a1aa-cafe6c123456 --api 00000002-0000-0000-c000-000000000000 --api-permissions  00000006-0000-0000-c000-000000000000=Role`

Is there anyway of getting the uui for custom app_roles?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5b5348-f67e-ef14-0529-4c80fddd4bc6
* Version Independent ID: bfd7e6b1-1fba-3d25-8ee3-5105bcf4157d
* Content: [az ad app permission](https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by yungezz** [comment]
@arrownj is it in output of show command?

**Comment by jiasli** [comment]
`appRoleId` can be retrieved with `az ad sp show`. Please see https://github.com/Azure/azure-cli/issues/12137#issuecomment-596567479 for detailed explanation.
