### ISSUE TITLE
Default value of --force-change-password-next-login

### ISSUE THREAD

**Issue by arnaudjumelet** [Azure/azure-cli#13970]
The AZ CLI online documentation indicates that the --force-change-password-next-login parameter is an optional parameter and does not actually indicate a default value.

First ask will be to make the --force-change-password-next-login or better indicate that the default is false.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57b0bbf2-3dca-90b2-1734-a38e78104b41
* Version Independent ID: 39842113-e499-d863-0f61-795089d844d9
* Content: [az ad user](https://docs.microsoft.com/en-us/cli/azure/ad/user?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by arrownj** [comment]
Will add this message in next release (2.11.0).
