### ISSUE TITLE
Failed to create imageTemplates

### ISSUE THREAD

**Issue by haohaiyu** [Azure/azure-cli#13972]
The command used is
`az resource create --resource-type Microsoft.VirtualMachineImages/imageTemplates --is-full-object -n chemistryImageTemplateMsi --resource-group chemistry-vm-rg --properties @builder.061520113654.json`
The following internal exception is thrown

## Describe the bug

**Command Name**
`az resource create`

**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
pip-install-yf22vmg2\msrest\msrest\serialization.py, ln 1291, in _deserialize
pip-install-yf22vmg2\msrest\msrest\serialization.py, ln 1081, in rest_key_case_insensitive_extractor
pip-install-yf22vmg2\msrest\msrest\serialization.py, ln 1104, in attribute_key_case_insensitive_extractor
...
pip-install-yf22vmg2\msrest\msrest\serialization.py, ln 1104, in attribute_key_case_insensitive_extractor
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az resource create --resource-type {} --is-full-object -n {} --resource-group {} --properties {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.6.0 *

```

**Comment by yonzhan** [comment]
add to S172

**Comment by yungezz** [comment]
hi @haohaiyu Azure CLI has imagebuilder specific commands.  Maybe you can have a try on it. https://docs.microsoft.com/en-us/cli/azure/image/builder?view=azure-cli-latest

**Comment by haohaiyu** [comment]
@yungezz I tried to use 
az image builder create -g chemistry-vm-rg -n chemistryImageTemplateMsi --image-template C:\Users\hay\AppData\Local\Temp\builder.061520113654.json

but get the following error:
Command group 'image builder' is in preview. It may be changed/removed in a future release.
validation error: Parameter 'ImageTemplate.source' can not be None.

and my template does contain:

 "properties": {
        "vmProfile": {
            "vmSize": "Standard_D8s_v3",
            "osDiskSizeGB": 64,
            "vnetConfig": {
                "name": "weckerERsvc-PvtApp-WUS2-VNET-11751",
                "subnetName": "Subnet-1",
                "resourceGroupName": "ERNetwork-PvtApp"
            },
            "source": {
                "type": "ManagedImage",
                "imageId": "/subscriptions/916dfd6d-030c-4bd9-b579-7bb6d1926e97/resourceGroups/chemistry-vm-rg/providers/Microsoft.Compute/images/ChemistryImage20200528162033"
            },

**Comment by qwordy** [comment]
"source" should be at same level as "vmProfile"
This repo has many examples. https://github.com/danielsollondon/azvmimagebuilder

**Comment by zhoxing-ms** [comment]
@haohaiyu May I ask is there any progress?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
