### ISSUE TITLE
ACS Kubernetes fails while listing container services

### ISSUE THREAD

**Issue by UncleTawnos** [Azure/azure-cli#1397]
user@host:~$ az acs list
u'Kubernetes' is not valid value for enum <enum 'ContainerServiceOchestratorTypes'>

user@host:~$ az --version
azure-cli (0.1.0b9)

acr (0.1.0b9)
acs (0.1.0b9)
appservice (0.1.0b9)
cloud (0.1.0b9)
component (0.1.0b9)
configure (0.1.0b9)
container (0.1.0b9)
context (0.1.0b9)
core (0.1.0b9)
feedback (0.1.0b9)
network (0.1.0b9)
profile (0.1.0b9)
resource (0.1.0b9)
role (0.1.0b9)
storage (0.1.0b9)
vm (0.1.0b9)

Python (Linux) 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2]

---- EXTRA INFO ----
Problem seems to occur when ACS was created with either Azure Portal or ARM template. If ASC was created using Azure-CLI, everything works.

**Comment by colemickens** [comment]
cc: @brendandburns

**Comment by brendandburns** [comment]
@UncleTawnos this is fixed here:

https://github.com/Azure/azure-cli/pull/1326

But it's not in the release yet.  Expect it in the next release.

@derekbekoe this can be closed...
