### ISSUE TITLE
[Configure] A more versatile `az configure`

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#13981]
`az configure` currently only supports setting and listing the `default` section:

```
> az configure -h

Command
    az configure : Manage Azure CLI configuration. This command is interactive.

Arguments
    --defaults -d      : Space-separated 'name=value' pairs for common argument defaults.
    --list-defaults -l : List all applicable defaults.  Allowed values: false, true.
    --scope            : Scope of defaults. Using "local" for settings only effective under current
                         folder.  Allowed values: global, local.  Default: global.
```

For other sections described in [Azure CLI configuration](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest), users will have to manually edit the `~/.azure/config` file, like 

```ini
[core]
collect_telemetry = no
no_color = yes

[logging]
enable_log_file = no
```

This is inconvenient. 

To improve the user experience, `az configure` needs to 

1. Support set, get and unset
2. Support sections other than `default`

**Comment by jiasli** [comment]
Did a quick evaluation: https://github.com/jiasli/azure-cli-spec/blob/master/az-configure.md

Hope it brings more ideas.

**Comment by yonzhan** [comment]
add to S171

**Comment by qianwens** [comment]
`az configure` can set the properties in the core/logging section, but it is interactive mode so that it is not script friendly.

**Comment by fengzhou-msft** [comment]
`az configure show` only shows what has been set, right? Then we can add `az configure list-available` command to show all the options that can be configured to increase their publicity.
