### ISSUE TITLE
Missing antlr4, WSL - Ubuntu 20.04 

### ISSUE THREAD

**Issue by adroc** [Azure/azure-cli#13984]
## Describe the bug

**Command Name**
`az vm create --help`

**Errors:**
```
No module named 'antlr4'
Traceback (most recent call last):
lib/python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
dist-packages/azure/cli/core/__init__.py, ln 300, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
azure/cli/command_modules/vm/__init__.py, ln 31, in load_arguments
    from azure.cli.command_modules.vm._params import load_arguments
azure/cli/command_modules/vm/_params.py, ln 31, in <module>
    from azure.cli.command_modules.monitor.actions import get_period_type
azure/cli/command_modules/monitor/actions.py, ln 7, in <module>
    import antlr4
ModuleNotFoundError: No module named 'antlr4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm create -h`

## Expected Behavior
Command
    az vm create : Create an Azure Virtual Machine.
        For an end-to-end tutorial, see https://docs.microsoft.com/azure/virtual-machines/virtual-
        machines-linux-quick-create-cli.
---Truncated----

---Truncated----
For more specific examples, use: az find "az vm create"

Please let us know how we are doing: https://aka.ms/clihats

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
Compute

**Comment by qwordy** [comment]
Hi, how do you install Azure CLI? apt, pip or other ways?

**Comment by yungezz** [comment]
duplicate with https://github.com/Azure/azure-cli/issues/13862

**Comment by qwordy** [comment]
Are you using the bundled Azure CLI of Ubuntu? The package is old and has some problems. Could you install the latest version and retry?
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

**Comment by qwordy** [comment]
Any update?

**Comment by qwordy** [comment]
Close it. If it still occurs in latest version, please open a new issue.
