### ISSUE TITLE
The information for "az consumption budget create" is incomplete

### ISSUE THREAD

**Issue by vabgujral** [Azure/azure-cli#13983]
[Enter feedback here]
Here is the link to the documentation - https://docs.microsoft.com/en-us/cli/azure/consumption/budget?view=azure-cli-latest#az-consumption-budget-create

The documentation for "az consumption budget create" says that it creates a new budget for an Azure subscription. In fact, it creates a new budget if the budget doesn't exist. If the budget exists already, the command actually updates it. I think the document shall be updated to provide the correct information. Under the hood, the command calls the PUT REST API call to create or update the budget. Here is the link to the REST API call - https://docs.microsoft.com/en-us/rest/api/consumption/budgets/createorupdate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d0e4fd3-7458-6d8e-b4ae-aefcdde52409
* Version Independent ID: 9a13720a-356a-6631-f4a0-f9aecd80f92e
* Content: [az consumption budget](https://docs.microsoft.com/en-us/cli/azure/consumption/budget?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/consumption/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/consumption/_help.py)
* Service: **consumption**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
consumption

**Comment by ramaganesan-rg** [comment]
Team is investigating.

**Comment by ramaganesan-rg** [comment]
Thank you for the feedback! Agree, and we will take actions to update documentation.
