### ISSUE TITLE
AttributeError after login through the browser

### ISSUE THREAD

**Issue by Dissonant-Tech** [Azure/azure-cli#13995]
## Describe the bug
AttributeError after login through the browser.

**Command Name**
`az login`

**Errors:**
```
'SubscriptionClient' object has no attribute 'config'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.8/site-packages/six.py, ln 703, in reraise
    raise value
...
azure/cli/core/_profile.py, ln 888, in _find_using_common_tenant
    client = self._arm_client_factory(token_credential)
azure/cli/core/_profile.py, ln 807, in create_arm_client_factory
    configure_common_settings(cli_ctx, client)
cli/core/commands/client_factory.py, ln 79, in configure_common_settings
    client.config.enable_http_logger = True
AttributeError: 'SubscriptionClient' object has no attribute 'config'
```

## Expected Behavior

The azure-cli should login to azure.

## Environment Summary
```
Linux-5.6.15-arch1-1-x86_64-with-glibc2.2.5
Python 3.8.3
Installer: PIP

azure-cli 2.7.0

```
## Additional Context

Currently using SSO through office365 for login.

**Comment by yonzhan** [comment]
add to S172

**Comment by JamieMagee** [comment]
@yonzhan I'm also experiencing the same issue on azure-cli 2.8.0. Happy to provide further debugging information if required.

**Comment by jiasli** [comment]
Looks like you installed Azure CLI with `pip` and then manually installed the Track 2 SDK `azure-mgmt-resource` 15.0.0b1 which changed `config` to `_config`:

```py
self._config = SubscriptionClientConfiguration(credential, **kwargs)
```

You may confirm the installed version of `azure-mgmt-resource` with `pip list`:

```pwsh
> pip list | Select-String azure-mgmt-resource

azure-mgmt-resource                   10.0.0
```

Azure CLI depends on 

https://github.com/Azure/azure-cli/blob/b01fbe373a059aa6c746e6e067aac4ac77323211/src/azure-cli/requirements.py3.windows.txt#L71

Please reinstall Azure CLI with

```
pip install azure-cli --force-reinstall
```

We recommend using the official installation methods: [Install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest). If you have to install with `pip`, please make sure Azure CLI is installed in an isolated virtual environment so that its dependencies are not broken by any other installations.

**Comment by JamieMagee** [comment]
Thanks for digging into this @jiasli. It does indeed look like a mismatch in expected versions. 

It looks like @Dissonant-Tech is using Arch Linux, like myself, and probably is using the [python-azure-cli](https://aur.archlinux.org/packages/python-azure-cli/) which has a dependency on the [python-azure-git](https://aur.archlinux.org/packages/python-azure-git/) package. This is quite unstable, but it looks like the [azure-cli](https://aur.archlinux.org/packages/azure-cli/) package is the best way forward. It uses the official install script, just packaged for Arch Linux.

It works well on my machine, and if you agree @Dissonant-Tech I think we can close this issue?

**Comment by jiasli** [comment]
Hi @JamieMagee, thanks for the analysis. 

However, the package on Arch Linux's repository is not maintained by Azure CLI team and is provided by the community. We only support installation method provided in the official doc [Install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest). See https://github.com/Azure/azure-cli/issues/9326#issuecomment-564364205 for a similar issue. 

Thanks for understanding.
