### ISSUE TITLE
Advisor API recommendations extended properties

### ISSUE THREAD

**Issue by assaf-grth** [Azure/azure-cli#13994]
Hi,
My question is regarding Azure advisor recommendations api (https://docs.microsoft.com/en-us/cli/azure/advisor/recommendation?view=azure-cli-latest, rest API as well - https://docs.microsoft.com/en-us/rest/api/advisor/recommendations)

The list of recommendations contains a recommendation type id and some time there are extended properties with additional details regarding the recommendation

The extended properties do not have a defined structure and change according to recommendation type

Is there a reference to all available possibilities of these extended properties according to recommendation types?

Thanks

Assaf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06faf684-60e4-b8dc-f974-ca6d6018e843
* Version Independent ID: 809dab74-84dc-f7e5-895b-9203f302ff9d
* Content: [az advisor recommendation](https://docs.microsoft.com/en-us/cli/azure/advisor/recommendation?view=azure-cli-latest&source=docs#az-advisor-recommendation-list)
* Content Source: [src/azure-cli/azure/cli/command_modules/advisor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/advisor/_help.py)
* Service: **advisor**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by mojayara** [comment]
Hi @assaf-grth, yes you are correct the extended properties are dynamic for each recommendation type. But unfortunately there are no documentation for all available possibilities of these extended properties.

**Comment by assaf-grth** [comment]
Hi @mojayara,
Is there an API call or a github file containing these details?

**Comment by mojayara** [comment]
@assaf-grth, sorry we do not have such elaborate details in our public recommendation metadata avaialable in either form you asked for.

FYI though, we have a ARM API to fetch basic details for the all [recommendation metadata details](https://docs.microsoft.com/en-us/rest/api/advisor/recommendationmetadata). Unfortunately this does not have the extended properties information.

**Comment by derekscha** [comment]
Is documenting the extendedProperties member for each recommendation category something that is on the road map? There is a discrepancy for cost savings recommendations between what is shown in the portal (savings amount) vs what's returned from the API in extendedProperies (savings amount & annual savings amount), and neither are documented. The portal shows one and the two returned from the API sometimes don't make sense (savings amt X 12mos != annual savings or savings amt X 12mos > annual savings.)
