### ISSUE TITLE
az sql db create: error: the following arguments are required: --server/-s

### ISSUE THREAD

**Issue by iamchamith** [Azure/azure-cli#13990]
While I am creating the SQL server database through azure cli there was a error prompt -s required. But I had append -s to the command. 

### To Reproduce:
az sql db create -n issue1 –s shoppingcartserver -g pow2 -l westus –-service-objective Basic --license-type BasePrice

### Error:
az sql db create: error: the following arguments are required: --server/-s

### Environment
Windows : 10
az cli : 2.0.81 

### Additional Context
![image](https://user-images.githubusercontent.com/10655695/84868162-e368c300-b099-11ea-894d-490d399711f9.png)

**Comment by yonzhan** [comment]
sql

**Comment by RakeshMohanMSFT** [comment]
@iamchamith This issue is fixed.
