### ISSUE TITLE
"'str' object has no attribute 'get'" error using parameter file and --handle-extended-json-format

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-cli#13998]
**Describe the bug

**Command Name**
`az deployment create --location WestUS --template-file ./master1.json --parameters @master1.dev.params.json --handle-extended-json-format`

**Errors:**
```
'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Use these files:
[bug.zip](https://github.com/Azure/azure-cli/files/4794639/bug.zip)
- `az deployment create --location WestUS --template-file ./master1.json --parameters @master1.dev.params.json --handle-extended-json-format`
- !) error

NOTE: If I leave out the parameter file (use a defaultValue for the param) or leave off --handle-extended-json-format (but I need that because I normally hande commets), everything works fine

## Expected Behavior
Should begin deployment

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.1
Shell: bash

azure-cli 2.0.80 *

```

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
@StephenWeatherford Hi, could you please upgrade the version of CLI to the latest version (2.8.0) and have a try?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
