### ISSUE TITLE
Enabling file logging should be supported through 'az configure' and the CLI config system

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1399]
Currently, the user has to set the environment variables `AZURE_CLI_ENABLE_LOG_FILE` and optionally `AZURE_CLI_LOG_DIR`.

We have a config system now should it should be integrated with that now.

**Comment by derekbekoe** [comment]
This would make this configuration available through environment variables but also through the config files.

**Comment by mayurid** [comment]
@derekbekoe : moving this to backlog for now.
