### ISSUE TITLE
az backup vault show duplicated eTag key

### ISSUE THREAD

**Issue by sbugalski** [Azure/azure-cli#13999]
## az backup vault show duplicated eTag key.

**Command Name**
`az backup vault show`

**Errors:**
```
ConvertFrom-Json : Cannot convert the JSON string because a dictionary that was converted from the string contains the
duplicated keys 'eTag' and 'etag'.
At line:1 char:110
+ ... me}" --name "${recoveryServicesVaultName}" -o json | ConvertFrom-Json
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [ConvertFrom-Json], InvalidOperationException
    + FullyQualifiedErrorId : DuplicateKeysInJsonString,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

az backup vault show --resource-group "${resourceGroupName}" --name "${recoveryServicesVaultName}" -o json
Command group 'backup' is in preview. It may be changed/removed in a future release.
{
  "eTag": null,
  "etag": "W/\"datetime'2020-06-03T11%3A50%3A42.8239336Z'\"",
<redacted>
"type": "Microsoft.RecoveryServices/vaults"
}

Value in ARM API:
{
  "location": "westeurope",
  "etag": "W/\"datetime'2020-06-03T11%3A50%3A42.8239336Z'\"",
<redacted>
}
```

## To Reproduce:
```
az backup vault show --resource-group "${resourceGroupName}" --name "${recoveryServicesVaultName}" -o json | ConvertFrom-Json
```

## Expected Behavior
single eTag value returned by az cli

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.7.0

Extensions:
azure-devops 0.18.0
interactive 0.4.4

```

**Comment by yonzhan** [comment]
backup

**Comment by pvrk** [comment]
@sbugalski : Sorry for the delay.  Can you please let me know what is the intent of this command?
```cli
az backup vault show --resource-group "${resourceGroupName}" --name "${recoveryServicesVaultName}" -o json | ConvertFrom-Json
```

**Comment by sbugalski** [comment]
> @sbugalski : Sorry for the delay. Can you please let me know what is the intent of this command?
> 
> ```
> az backup vault show --resource-group "${resourceGroupName}" --name "${recoveryServicesVaultName}" -o json | ConvertFrom-Json
> ```

Sure if it matters.
We assign the comand ouput to variable and then consume it. We run it in the pipeline using Powershell task.
It was easier for use to do it using AZ CLI, but logic is made using Powershell.

**Comment by pvrk** [comment]
@sbugalski : Sincere apologies, I missed updating the thread. We took this up in our investigation and are planning to fix this. Will let you know the plan once this finalized.

**Comment by pvrk** [comment]
Sincere apologies for the delay. Investigation is in progress.

**Comment by mepand** [comment]
Investigation is still in progress.

**Comment by adityabalaji-msft** [comment]
New ETA for the fix is 30 July

**Comment by adityabalaji-msft** [comment]
The fix is now available in 2021-07-01 version. Closing the issue for now, feel free to reopen in case you are facing problems
