### ISSUE TITLE
Syntax for the --fields argument

### ISSUE THREAD

**Issue by ajafry** [Azure/azure-cli#14007]
Hi,

The documentation is unclear on how to provide a list of columns to customize the output fields. The correct syntax requires names of fields with a space (for CLI), e.g.

`az appconfig revision list --name my-app-config-name --top 10 --fields key label last_modified
`
Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e19e40d4-be8f-8018-0145-fb0425a9f423
* Version Independent ID: 3c1e771b-6932-a51b-6989-d5a9f6407cec
* Content: [az appconfig revision](https://docs.microsoft.com/en-us/cli/azure/appconfig/revision?view=azure-cli-latest&source=docs)
* Content Source: [src/azure-cli/azure/cli/command_modules/appconfig/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appconfig/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by shenmuxiaosen** [comment]
Hi ajafry, thanks for reporting this issue. We do have an example for how to use ```--fields``` for other list commands but not for revision. Will have a pull request to add.

**Comment by shenmuxiaosen** [comment]
PR link: https://github.com/Azure/azure-cli/pull/14081

**Comment by RakeshMohanMSFT** [comment]
@ajafry This is fixed.
