### ISSUE TITLE
The commands in documentation are deprecated. Please change the document accordingly.

### ISSUE THREAD

**Issue by sandeepkundala** [Azure/azure-cli#14000]
The commands pointed in the documentation are deprecated. Please update the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da15197a-eca2-19d6-72e3-be853337a759
* Version Independent ID: eb84d467-86df-121e-3b04-66b499342f7f
* Content: [az cosmosdb database](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/database?view=azure-cli-latest#az-cosmosdb-database-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cosmosdb

**Comment by shurd** [comment]
Hi @sandeepkundala thank you for opening this issue. These commands are marked as deprecated (they will not show up in the --help menu). Unfortunately, the documentation is auto-generated from the help file, but it does not hide or mark deprecated commands. Unless we completely remove these commands, they will still appear in the documentation.

**Comment by shurd** [comment]
Closing this issue for now as documentation is auto-generated and the deprecation is noted in the help menu.
