### ISSUE TITLE
No module issue on Ubuntu 20.04(Focal)/WSL

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-cli#14011]
If you just run `apt update && apt install azure-cli` on Ubuntu Focal, you'll install an old `2.0.81` version from `focal/universe` and it's packaged differently than the official deb packages we release and still in testing stage. It's not tested and maintianed by Azure CLI Team and has several issues that need to be fixed.

ℹPlease first uninstall azure-cli 2.0.81 and its dependencies:
`sudo apt remove azure-cli -y && sudo apt autoremove -y`
Then install the latest azure-cli:
`curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`

See more [install documentation](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest). 

Related Issues:
#13519 No module named '__builtin__' in Ubuntu 20.04 (Canonical image)
#13958 az cli failing on webapp deployment (No module named 'decorator')
#14001 Missing antlr4, Error with az vm image list on ubuntu 20.04 (WSL)

**Comment by arrownj** [comment]
Do we know the reason why it link to 2.0.81 instead of latest CLI?

**Comment by fengzhou-msft** [comment]
> Do we know the reason why it link to 2.0.81 instead of latest CLI?

@bluca packaged it initially for testing and is blocked by https://github.com/Azure/azure-cli/pull/13490.

**Comment by haroldrandom** [comment]
Add one issue might related https://github.com/Azure/azure-cli/issues/14777#event-3752926198 (could deleted if it's unnecessary)

**Comment by squillace** [comment]
@fengzhou-msft the "blocking" issue closed in July, but I just had this recur TODAY on a brand new installation of 20.04 in WSL2. Is this issue still open, and if so, why? Likely because of resources, but it's five months later now..... :-)

**Comment by bk2204** [comment]
It would be really great if the Azure CLI team could work with Debian and Ubuntu to produce releases that they can use and package in a normal way so that they work.  The AWS client works just fine out of distro packages, and most users use and expect to use distro packages and won't want to install a custom repository.  I'm certainly in that case, and It's a bit of a problem that the Azure CLI is so brittle that it's broken when packaged by a normal Linux distro.

**Comment by oviliz** [comment]
Why isn't this added to the Ubuntu repo so we can always get the latest with `apt update`?

**Comment by alan-czajkowski** [comment]
How is this not fixed by now? it's the year 2022 and this problem still exists in Ubuntu 20.04 LTS

it is madness to install binaries using this method:
```
$ curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
```
as this is super vulnerable to supply-chain attacks

When can we expect this to be fixed?

**Comment by squillace** [comment]
Um, agree on bash install, but my 20.04 apt does the right thing. Does yours not? `azure-cli is already the newest version (2.34.1-1~focal).`

**Comment by alan-czajkowski** [comment]
@squillace 

Dockerfile:
```
FROM docker.devops.moneris.com/groovy:3.0-jdk11
...
# Install/update OS packages
RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y ca-certificates \
                       locales \
                       wget \
                       curl \
                       zip \
                       python3 \
                       python3-pip \
                       jq \
                       git \
                       docker docker.io \
                       maven \
                       azure-cli \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
           /tmp/* \
           /var/tmp/*
...
```

when I run the container:
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by alan-czajkowski** [comment]
@squillace can you show me how you are doing it?

**Comment by squillace** [comment]
well, not sure this will help, because... it is what it is. Although I followed: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions

and then:
```
 sudo apt-get remove azure-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  python3-crcmod
Use 'sudo apt autoremove' to remove it.
The following packages will be REMOVED:
  azure-cli
0 upgraded, 0 newly installed, 1 to remove and 14 not upgraded.
After this operation, 1083 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 160756 files and directories currently installed.)
Removing azure-cli (2.34.1-1~focal) ...                                                                        /9.5s
 squillace@dellsquill  / 
▶ sudo apt-get install azure-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  python3-crcmod
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  azure-cli
0 upgraded, 1 newly installed, 0 to remove and 14 not upgraded.
Need to get 0 B/75.4 MB of archives.
After this operation, 1083 MB of additional disk space will be used.
Selecting previously unselected package azure-cli.
(Reading database ... 102877 files and directories currently installed.)
Preparing to unpack .../azure-cli_2.34.1-1~focal_all.deb ...
Unpacking azure-cli (2.34.1-1~focal) ...
Setting up azure-cli (2.34.1-1~focal) ...                                                                     /20.3s
 squillace@dellsquill  / 
▶ az --version
azure-cli                         2.34.1
```

**Comment by alan-czajkowski** [comment]
@squillace thanks for this tip, I applied it inside the Dockerfile, and the Azure CLI seems to be working fine now

to anybody who finds this page, I have slightly improved Microsoft's Debian/Ubuntu install commands to the following:

*Dockerfile*:
```
...
```

**Comment by jiasli** [comment]
@alan-czajkowski, this is because you didn't add Microsoft Linux repo. Please see https://github.com/Azure/azure-cli/issues/19640.

**Comment by alan-czajkowski** [comment]
@jiasli you're late to the party, see my solution above

why can't Microsoft add Azure CLI to the official Debian repos?

**Comment by jiasli** [comment]
> @jiasli you're late to the party, see my solution above

I know, since 05/12 is Saturday! 🤣

> why can't Microsoft add Azure CLI to the official Debian repos?

All Microsoft Linux packages are delivered from https://packages.microsoft.com/ due to company policy. Appreciate your understanding.
