### ISSUE TITLE
can't interact with ADLS gen2 from within a container

### ISSUE THREAD

**Issue by dgcaron** [Azure/azure-cli#14019]
## Describe the bug
i am writing some powershell scripts that need to run from a container. i have a powershell script that works locally but fails while i run it in a container. running 
```
az storage account list
```
returns me the list of storage accounts for the subscription but when i want to list the containers, i get an authentication error. running the same script with the same user on my windows machine, is not returning any error. i am thinking it might be related to the fact that i am logged in with service principal credentials. this works fine for the ml extension that is also installed.

**Command Name**
`az storage container list`

**Errors:**
```
Authentication failure. This may be caused by either invalid account key, connection string or sas token value provided for your storage account.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login --service-principal --tenant $env:ARM_TENANT_ID --username $env:ARM_CLIENT_ID --password $env:ARM_CLIENT_SECRET | Out-Null`
-  `az account set -s $env:ARM_SUBSCRIPTION_ID`
- `az storage container list --account-name {..}`

## Expected Behavior
returns list of containers for the account name specified

## Environment Summary
```
Linux-4.19.76-linuxkit-x86_64-with
Python 3.8.2
Installer: 

azure-cli 2.7.0
azure-cli-ml 1.7.0

Extensions:
azure-cli-ml 1.7.0
storage-preview 0.2.10

```

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
@dgcaron could you specify --account-key, --connection-string or --sas-token? if possible, please add `--debug` in your command to provide more debug information.

**Comment by dgcaron** [comment]
i'll take a look, will get back to you asap!

**Comment by Juliehzl** [comment]
any update?

**Comment by dgcaron** [comment]
sorry for the late reply but i am no longer able to reproduce this error and can now talk to the storage account normally
