### ISSUE TITLE
[local context] refine error message

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#14015]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62
Refine messages of local context when saving per PM feedback, below is an example:
"Your preference of: –name AzureFunctionsQuickstart-rg and –location westeurope are now saved to local context. To learn more, type in az local-context –help "

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
local context
