### ISSUE TITLE
az ams account sp is not idempotent

### ISSUE THREAD

**Issue by IUnknownPtr** [Azure/azure-cli#14021]
Consequently executing `az ams account sp create` fails with error `Service principal already exists.`. Same bug has been already [resolved ](https://github.com/Azure/azure-cli/pull/9108) for `az ad app create` but still a case for AMS.

**Comment by yonzhan** [comment]
ams

**Comment by hivyas** [comment]
Hi there, thanks for reporting. We filed this as bug 7540668 with our team and set it to milestone S172. We will be investigating
