### ISSUE TITLE
edit create example

### ISSUE THREAD

**Issue by Mexicoder** [Azure/azure-cli#14025]
create example 
`az network nsg rule create -g MyResourceGroup --nsg-name MyNsg -n MyNsgRuleWithTags \
    --priority 400 --source-address-prefixes VirtualNetwork --destination-address-prefixes Storage \
    --destination-port-ranges * --direction Outbound --access Allow --protocol Tcp --description "Allow VirtualNetwork to Storage."
`

This: `  --destination-port-ranges *`  doesn't work without the single quotes
also if you accidentally use an ide that likes to add the quotes for you and you try and run something with this:   `--destination-port-ranges '*''`

It will hang and not do anything till you tell it to stop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe4941c-7b46-b9fb-1c52-98e68f6354cc
* Version Independent ID: d1bc72fb-ccf9-9645-7b1d-98c91bc75a55
* Content: [az network nsg rule](https://docs.microsoft.com/en-us/cli/azure/network/nsg/rule?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S172

**Comment by MyronFanQiu** [comment]
@Mexicoder I modified the help example. However, I think this issue is not related with quote. Do you still encounter this issue?

**Comment by MyronFanQiu** [comment]
Close this issue first since it should be solved. Feel free to re-open it if you have any more question.
