### ISSUE TITLE
Comments give errors with --handle-extended-json-format in certain locations, and gives bad error location

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-cli#14026]
Might be related to https://github.com/Azure/azure-cli/issues/13998

## Describe the bug

**Command Name**
`az group deployment create`

**Errors:**
```
Expecting ',' delimiter: line 1 column 726 (char 725)
```

## To Reproduce:
[bug2.zip](https://github.com/Azure/azure-cli/files/4801500/bug2.zip)
- `az group deployment create -g deleteme --template-file ./twoLinked-master.json --handle-extended-json-format --parameters @twoLinked-master.dev.params.json`

NOTE: The first comment gives no problems, the second in a different location causes errors

## Expected Behavior
1) Shouldn't give an error for comments
2) Should give a correct error location

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.1
Shell: bash

azure-cli 2.0.80 *

```

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
@StephenWeatherford Hi, this seems to be an problem of the old version, and it has been fixed in the new version. Could you please upgrade the version of CLI to the latest version (2.9.0) and have a try?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
