### ISSUE TITLE
webapp: Have --html default to OS of the app service plan

### ISSUE THREAD

**Issue by RyanHill-MSFT** [Azure/azure-cli#14023]
**Is your feature request related to a problem? Please describe.**

`az webapp up --html` defaults to a Windows OS app service plan. If a customer wants to create a static web app on a Linux OS, this command wouldn't work.

**Describe the solution you'd like**

When using --html, the CLI should use the OS of the app service plan that's being passed in. If --plan is not passed, then simply default to windows.

**Describe alternatives you've considered**

As a workaround, I added a package.json to full the CLI into creating an app which will use nodejs.

**Additional context**

See https://docs.microsoft.com/en-us/answers/questions/37285/index.html for more details.

**Comment by yonzhan** [comment]
webapp

**Comment by daveMitra** [comment]
let me know which command should I choose to create the static HTML web app on Linus OS

**Comment by panchagnula** [comment]
@btardif is this something we plan to consider? Thanks!

**Comment by btardif** [comment]
`az webapp up` is **opinionated** as far as OS goes. so we provide default with no overrides.

For advanced scenarios use `az webapp create` where you have full flexibility

Once we have an official story for static hosting on linux app service we can revisit defaults for `az webapp up`

**Comment by tboerstad** [comment]
@btardif Are there plans for static hosting on Linux App Service?

I face the same challenge as the original poster linked to. I have an existing backend which is running on Linux App Service, and I would like the static frontend to be in the same App Service Plan. This way the backend and frontend can share resources and hopefully improve latency. I suspect there are more of us with this use case.

**Comment by btardif** [comment]
@tboerstad yes static hosting on Linux is something that is in the works.

If you want to do this today, you can target one of the PHP images on linux. We include a web server that can be used for static content in those images.
