### ISSUE TITLE
Sample in the lerningpath will not work

### ISSUE THREAD

**Issue by tofuatjava** [Azure/azure-cli#14033]
I'm working on the storage learningpath
https://docs.microsoft.com/en-us/learn/modules/upload-download-and-manage-data-with-azure-storage-explorer/
I'm able to create a storage accoutn an the sample project in C#. But the verification of the storage account failed for some reason (but i copy&pasted the command and entered a valid name for the storage account)
Creating the sample projekt works, running the HelloWorld works but adding the AzureStorage nuget package fails again with the error: Read-Only filesystem. I tryied to rollback the whole project but still the same issue.
I stucked...

## Describe the bug

**Command Name**
``

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-4.15.0-1083-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

```

**Comment by yonzhan** [comment]
I think this issue is not related to CLI but a PowerShell issue.

**Comment by RakeshMohanMSFT** [comment]
Please reopen if you still need help with this issue, also provide more details like the commands you are having issues with.
