### ISSUE TITLE
Cannot create service principal

### ISSUE THREAD

**Issue by djcornutt** [Azure/azure-cli#14039]
## Describe the bug

**Command Name**
`az ad sp create-for-rbac`

I ran this and got the below error. The 2 variables referenced did indeed have the correct value:
ARM_CLIENT_SECRET=$(az ad sp create-for-rbac \
  --name http://ansible-sp-$UNIQUE_ID \
  --role Contributor \
  --scopes "/subscriptions/$ARM_SUBSCRIPTION_ID" \
  --query password \
  --output tsv)

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 709, in _run_job
    cmd_copy.exception_handler(ex)
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad sp create-for-rbac --name {} --role {} --scopes {} --query {} --output {}`

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

```

**Comment by yonzhan** [comment]
add to S172

**Comment by djcornutt** [comment]
Do I need to upgrade something?

**Comment by yungezz** [comment]
hello @djcornutt where did you meet the error? In Cloudshell or windows terminal?

**Comment by djcornutt** [comment]
Cloudshell

Ask me about migrating your on-premises infrastructure to Azure!

________________________________

**Comment by yungezz** [comment]
Thanks @djcornutt . This is a known issue in Cloudshell due to #11479. Cloudshell team is working on it. A workaround is to run `az login` again.
