### ISSUE TITLE
az login fail on SLES12 SP5

### ISSUE THREAD

**Issue by rukawata** [Azure/azure-cli#14031]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
APIVersion 2019-06-01 is not available
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
azure/cli/core/_profile.py, ln 865, in find_from_service_principal_id
    result = self._find_using_specific_tenant(tenant, token_entry[_ACCESS_TOKEN])
azure/cli/core/_profile.py, ln 960, in _find_using_specific_tenant
    subscriptions = client.subscriptions.list()
mgmt/resource/subscriptions/subscription_client.py, ln 109, in subscriptions
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-06-01 is not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal -u {} -p {} --tenant {}`

## Environment Summary
```
Linux-4.12.14-122.23-default-x86_64-with-SuSE-12-x86_64
Python 3.4.10
Installer: RPM

azure-cli 2.7.0

```

**Comment by yungezz** [comment]
hi @arrownj could you pls have a look? thanks

**Comment by arrownj** [comment]
Hi @rukawata , it seems that you `azure-mgmt-resource` package is not installed correctly. Could you please check whether `2019-06-01` is in your system, it should located in folder like `/usr/lib64/az/lib/python3.6/site-packages/azure/mgmt/resource`. If not, you can reinstalled it by `pip install azure-mgmt-resource==9.0.0 --prefix /usr/lib64/az`.

**Comment by rukawata** [comment]
Hi, it's been some time and the VM has been deleted. We can close this.
