### ISSUE TITLE
trying to upload zip file through azure CLI but it gives "No file to upload"

### ISSUE THREAD

**Issue by ArsalanGul** [Azure/azure-cli#14035]
## Describe the bug

**Command Name**
`az dls fs upload`

**Errors:**
```
az dls fs upload: error: the following arguments are required: --destination-path
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az dls fs upload --bpdata --source-path {}`

## Environment Summary
```
Linux-4.15.0-1083-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

```

**Comment by yonzhan** [comment]
add to S172

**Comment by Juliehzl** [comment]
Hi @ArsalanGul, are you working with ADLS Gen1 account?

According to the error message, it seems you forget to provide `--destination-path` parameter value, could you check your usage again and use `--help` to see more with examples?

**Comment by Juliehzl** [comment]
Hi, because there is no response for several days, I will close the PR now and if you still have the problem, feel free to reopen it.
