### ISSUE TITLE
AKS cluster upgrade with CLI still interactive even when setting --yes option

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/azure-cli#14047]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

AZ CLI not does implement --yes to bypass confirmation when upgrading AKS Clusters

**To Reproduce**

az aks upgrade --control-plane-only --name $cluster_name -g $rg_name --kubernetes-version $version **--yes**

CLI then prompts:
_Since control-plane-only argument is specified, this will upgrade only the control plane to 1.18.6. Node pool will not change. Continue? (y/N)_

**Expected behavior**

Upgrade should run automatically without any prompt

**Environment summary**

AKs 1.16.7

Windows 10 CMD : 
{
  "azure-cli": "2.7.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.7.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "asc": "0.1.0",
    "azure-firewall": "0.3.0"
  }
}

**Additional context**

See [https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-upgrade](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-upgrade)

**Comment by yungezz** [comment]
route to appropriate team

**Comment by atulaggarwal** [comment]
The option --yes was introduced in azure cli version 2.8.0 as mentioned in the [link](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&tabs=azure-cli) . The version which you are using is 2.7.0 which does not contains that option.

**Comment by Jen7714** [comment]
Closing since Atul answered the question!

**Comment by NJura-PartnerAuchan** [comment]
> The option --yes was introduced in azure cli version 2.8.0 as mentioned in the [link](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&tabs=azure-cli) . The version which you are using is 2.7.0 which does not contains that option.

Hello,

I got the same error with the 2.9.0 version of azure cli directly in the cloud shell portal, the option is here but it's don't do the job.

BR

**Comment by ezYakaEagle442** [comment]
I run CLI latestv2.14 

az version
{
  "azure-cli": "2.14.2",
  "azure-cli-core": "2.14.2",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "asc": "0.1.0",
    "azure-firewall": "0.3.0"
  }
}

Please reopen this issue @Jen7714 @atulaggarwal
