### ISSUE TITLE
azure-cli plugin not working after upgrade to jenkins LTS 2.235.1

### ISSUE THREAD

**Issue by erikbotta** [Azure/azure-cli#14049]
Previous version of jenkins LTS works ok with azure-cli.
No I get on master or slave same result : 
`Failure: /bin/sh: 1: az: not found

Build step 'Azure CLI not found' changed build result to FAILURE`

**Comment by yonzhan** [comment]
@erikbotta please provide more details info about CLI command and error message.

**Comment by erikbotta** [comment]
Command was any ... for example **az list**

Answer from build was : Failure: /bin/sh: 1: az: not found

Build step 'Azure CLI not found' changed build result to FAILURE

after downgrade jenkins master back to 2.222.4 is all ok again.
I tried also to reinstall plugin under 2.235.1. Tried to run on master or different jnlp slaves ... same problem with newer LTS master.

**Comment by erikbotta** [comment]
@yonzhan Hello. Anything I can send here more to solve this? I cannot upgrade jenkins for now, because this plugin is crucial for us. Thx.

**Comment by yonzhan** [comment]
I think you should find jenkins team for help. This issue is not related to CLI.

**Comment by erikbotta** [comment]
Oh. Sry for my mistake. Bad repository :( . 
For others they have issue like this opened from 2018 , so maybe it is some regression. https://github.com/jenkinsci/azure-cli-plugin/issues/15
