### ISSUE TITLE
Webapp:az webapp config not able to set "Incoming Client Certificates"

### ISSUE THREAD

**Issue by softveda** [Azure/azure-cli#14040]
I am using the `az webapp config set` command.
Can't find an option to set the "Incoming Client Certificates" settings.
Both to set the options Require/Allow/Ignore and to add Exclusion paths.
See:
![image](https://user-images.githubusercontent.com/1845906/85201647-72990380-b344-11ea-84a2-2ca68f283b1c.png)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e50d77a-f2fa-6d6e-0c57-2f434c12766f
* Version Independent ID: f9a98805-6e16-487a-03ce-237cb964f83c
* Content: [az webapp config](https://docs.microsoft.com/en-us/cli/azure/webapp/config?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@softveda thanks for opening this - this a a new feature that is not available on Python SDK - the feature owner is working on it once we have this we will start supporting this. Thanks!

**Comment by softveda** [comment]
I found out this can be done like below.
az webapp update -g $rgName -n $appName --set clientCertEnabled=true
az webapp update -g $rgName -n $appName --set clientCertExclusionPaths="/Health"

**Comment by navba-MSFT** [comment]
@softveda Apologies for the late reply. We will provide an update on this thread once we have more details.

@Kotasudhakarreddy @panchagnula Could you please provide the latest update on this feature ? Awaiting your reply.

**Comment by seligj95** [comment]
Thank you for the feedback. `az webapp config set` is used for properties that fall under the site's site config. We have defined dedicated parameters for certain site config properties. Any other site config properties can be updated using the `--generic-configurations` parameter. 

The `clientCertEnabled` property doesn't fall under site config so it can't be used with this command. You must use `az webapp update` as you identified. We would need to build a dedicated command for this property to use as you identified but unfortunately that is not on the roadmap at this time. Will keep this in the backlog for now. 

Thank you again for the feedback.
