### ISSUE TITLE
Changes related to dedicated host group automatic placement

### ISSUE THREAD

**Issue by dochung4** [Azure/azure-cli#14056]
**Resource Provider**

Microsoft.Compute

**Description of Feature or Work Requested**

Today customers can place a VM on a dedicated host, by providing the ARM resource id of the dedicated host in the VM input.
The new feature is to support automatic placement of VMs and VMScaleSets on a dedicated host group. This means in the VM/VMScaleSet input, customers can specify the ARM resource id of the dedicated host group, on which they want their VMs/VMScaleSets to be placed, and Azure will select an appropriate dedicated host under the dedicated host group for each VM and allocate the VM.
There are four major changes related to this feature:
1. "supportAutomaticPlacement" is a new property introduced under DedicatedHostGroup.properties. Customers can specify either true or false. It defaults to true, if no input is provided. If a dedicated host group has automatic placement enabled, VMs or VMScaleSets can be placed on the dedicated host group using automatic placement.

2. GET dedicated host group now supports instance view query parameter. Dedicated host group instance view will return instance view of the dedicated hosts under the dedicated host group.

3. "hostGroup" is a new property introduced under VM.properties and VMScaleSet.properties. The input should be the resource id of the dedicated host group, on which the customer wants his VM/VMScaleSet placed using automatic placement.

4. "assignedHost" is a new property introduced under VMInstanceView and VMScaleSetVMInstanceView. It is the resource id of the dedicated host, on which the queried VM/VMScaleSetVM is placed using atuomatic placement.

Design document: https://microsoft.sharepoint.com/:w:/t/ComputeVM/EV1bTk0XSvNLtvDnLn9PSpoBH2NvlfAFQhduoCSJvatreg?e=6AiqWp

**Minimum API Version Required**

2020-06-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/9684

**Target Date**

August 2020

**Comment by yungezz** [comment]
thanks for @dochung4 for detail info. Just to confirm, is service feature deployed to Prod yet? Or pls share us timeline, then we can start testing and python SDK release, then CLI work.

**Comment by dochung4** [comment]
Would testing in Canary work for you? Everything has been deployed to Canary, except for one small bit, which is expected to be deployed to Canary as well this week. The feature requires subscription whitelisting. I can whitelist subscriptions, if you could provide me subscriptionIds.

I am not completely sure about the timeline for prod and in which regions we are planning to enable first. But we are targeting for preview in August.
