### ISSUE TITLE
Support cross tenant sig image version creation from images/snapshots/disks/vms in different tenants

### ISSUE THREAD

**Issue by KshitijAgrawal** [Azure/azure-cli#14057]
**Resource Provider**
Microsoft.compute

**Description of Feature or Work Requested**
az sig image version create/update need to be able to support cross tenant

**Minimum API Version Required**
None

**Swagger Link**

**Target Date**
Some customers are having to do workarunds. As more and more people are using cross tenant work, it becomes absolutely important for azure cx experience.

**Comment by yungezz** [comment]
we had discussion in email. This will be supported via --aux-tenant argument.
