### ISSUE TITLE
Azure CLI az aks create

### ISSUE THREAD

**Issue by AShchepachev** [Azure/azure-cli#14053]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --enable-addons {} --generate-ssh-keys`

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

```

**Comment by AShchepachev** [comment]
I use free account.
Command:
az aks create --resource-group kubernetesgrp --name democluster --node-count 1 --enable-addons monitoring --generate-ssh-keys

**Comment by yonzhan** [comment]
aks

**Comment by atulaggarwal** [comment]
Have you logged into az cli command using `az login` ([link](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login)) ? The error statement looks like it was unable to retrieve oauth token.

**Comment by AShchepachev** [comment]
Yes, I have. A few times

**Comment by AShchepachev** [comment]
It seems like the problem caused by two accounts being signed in
