### ISSUE TITLE
 Monitor the health of your Azure virtual machine by collecting and analyzing diagnostic data  Exercise - Set up a VM with boot diagnostics

### ISSUE THREAD

**Issue by mgoular** [Azure/azure-cli#14058]
## Describe the bug

**Command Name**
`az login`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity`

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0

```

**Comment by yungezz** [comment]
hello @mgoular could you pls share more detail about the ask and repro steps? Do you need a doc on how to monitor health of vm by setup VM with boot diagnostics? Or did you meet any error during the operation? Pls share more detail infoo to help investigate, thanks.

**Comment by houk-ms** [comment]
No response for long time, closed.
