### ISSUE TITLE
Function of --vm-protection

### ISSUE THREAD

**Issue by vivlit** [Azure/azure-cli#14059]
Hi, I was just wondering what the function of the flag --vm-protection exactly is? In the documentation, it simply states that it can be enabled to turn on VM protection, but there is no further detail.

Some references:
https://docs.microsoft.com/en-us/rest/api/virtualnetwork/virtualnetworks/createorupdate
https://docs.microsoft.com/en-us/cli/azure/network/vnet?view=azure-cli-latest

 Thank you!

**Comment by yungezz** [comment]
hi @qwordy , could you pls help on this? thanks.

**Comment by qwordy** [comment]
```
Enable VM protection for all subnets in the VNet.
```
```
Indicates if VM protection is enabled for all the subnets in the virtual network.
```
I don't know exact meaning of it, either.
@MyronFanQiu Do you know what it means?

**Comment by qwordy** [comment]
Hi service team, could you share what VM protection means? Thanks!

**Comment by Drewm3** [comment]
Updated from compute to networking because this is a Network Service API.

**Comment by anharazi** [comment]
This was a legacy flag that has been replaced with enableDdosProtection

**Comment by mark-at-delta-n** [comment]
Documentation on docs.microsoft.com are not updated with remark of @anharazi. Please update.
https://docs.microsoft.com/en-us/rest/api/virtualnetwork/virtualnetworks/createorupdate
https://docs.microsoft.com/en-us/cli/azure/network/vnet?view=azure-cli-latest

**Comment by qwordy** [comment]
@haroldrandom Can you check the CLI network doc? Thanks!
