### ISSUE TITLE
Can't create cache rule for Akamai CDN endpoint

### ISSUE THREAD

**Issue by rnmakino** [Azure/azure-cli#14052]
**Command Name**
`az cdn endpoint rule action add`

**Errors:**
```
'NoneType' object has no attribute 'rules'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 325, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 545, in default_command_handler
    return op(**command_args)
cli/command_modules/cdn/custom.py, ln 396, in add_action
    for i in range(0, len(policy.rules)):
AttributeError: 'NoneType' object has no attribute 'rules'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cdn endpoint rule action add -g {} --profile-name {} -n {} --rule-name {} --action-name {} --cache-behavior {} --cache-duration {}`

## Environment Summary
```
macOS-10.15.5-x86_64-i386-64bit
Python 3.8.3
Installer: HOMEBREW

azure-cli 2.7.0

Extensions:
front-door 1.0.2

```

**Comment by yonzhan** [comment]
CDN

**Comment by yungezz** [comment]
#14287

**Comment by navba-MSFT** [comment]
@rnmakino Apologies for the delayed response. This issue has been fixed now. Please refer #14335
Since this issue has been inactive for quite sometime now, I am proceeding with the closure of this thread. If you need further assistance on this, please feel free to reopen this github thread. We would be happy to assist you.
