### ISSUE TITLE
Azure Login issue from git 

### ISSUE THREAD

**Issue by hirenrpatel1610** [Azure/azure-cli#14067]
HI All,

I have installed git for windows and while trying to login to Azure with az login I get below error.

Azure CLI is installed.

$ az login
Port '8400' is taken with error '[WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted'. Trying with the next one
Authentication Error: "['access_denied']". Description: "None"
Login failed

**Comment by yonzhan** [comment]
add to S172

**Comment by jiasli** [comment]
@hirenrpatel1610, is the browser opened and ask you to log in to https://login.microsoftonline.com/? Could you share the `--debug` log?

**Comment by jiasli** [comment]
If you have more information, please kindly provide here.
