### ISSUE TITLE
az hpc-cache nfs-storage-target --junction needs more information

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#14060]
**Link to reference content:**
https://docs.microsoft.com/en-us/cli/azure/ext/hpc-cache/hpc-cache/nfs-storage-target?view=azure-cli-latest#ext-hpc-cache-az-hpc-cache-nfs-storage-target-add-examples

**Information provided for junction parameter:**
--junction
List of Cache namespace junctions to target for namespace associations.

**Sample provided that uses undocumented "sub parameter" values of namespace-path and nfs-export**
az hpc-cache nfs-storage-target add --resource-group "scgroup" --cache-name "sc1" --name \
"st1" --nfs3-target 10.7.0.24 --nfs3-usage-model WRITE_AROUND \
--junction **namespace-path**="/nt2" **nfs-export**="/export/a" target-path="/1" \
--junction **namespace-path**="/nt3" **nfs-export**="/export/b"

Also, --junction is a required parameter, but what are the **optional and required “sub parameters”**?  
1.	namespace-path
2.	nfs-export
3.	target-path
Is there a fourth option here?

**Link to portal article in case you want to lift some verbiage:**
https://docs.microsoft.com/en-us/azure/hpc-cache/hpc-cache-namespace

**Comments from doc writer, @ErinKelly:**
•	namespace-path – the client-facing virtual path provided by the Azure HPC Cache
•	nfs-export – the storage export
•	target-path – optional, a subdirectory of the NFS export

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
@dbradish-microsoft Hi, thank you very much for your feedback. `--junction` supports only `namespace-path`, `nfs-export` and `target-path` sub parameters.
The detailed description is shown in this document: [link](https://docs.microsoft.com/en-us/rest/api/storagecache/caches/update#namespacejunction)
I will supplement and optimize our examples according to the information you provided~
