### ISSUE TITLE
Add support for adding certificates to Virtual Machines

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#1407]
Add command for the equivalent PS cmdlet: https://docs.microsoft.com/en-us/powershell/resourcemanager/azurerm.compute/v1.3.4/Add-AzureRmVMSecret?redirectedfrom=msdn

**Comment by squillace** [comment]
@johanste not quite: per "The secret must be stored in a Key Vault." is a breaking requirement likely on Linux work. It is a normal operating procedure to already have key management servers already in deployment, so to enable this for KeyVault but not for https://www.hashicorp.com/blog/vault.html, for example, would be viewed as vindictively biased. 

Instead, please amend this to say something like: 
Add command enabling:
1. adding keys to a vm for a preexisting user from the keyvault
2. adding keys to a vm for a preexisting user from passed in key value/location.

**Comment by yugangw-msft** [comment]
Per clarifiaction from CRP team, the PS cmdlet is windows only

**Comment by yugangw-msft** [comment]
I am closing this, as we have flags of `vm/vmss create --secret` for similar kinds of support.
We can reopen this when we have user voices with clearly defined scenario and scope.
