### ISSUE TITLE
Why does the range of --top for 'az consumption usage list' have a maximum of 1000?

### ISSUE THREAD

**Issue by ramayer-fli** [Azure/azure-cli#14079]
[Enter feedback here]

Why this restriction: 

    --top -t
    Maximum number of items to return. Value range: 1-1000.

on: 

https://docs.microsoft.com/en-us/cli/azure/consumption/usage?view=azure-cli-latest#az-consumption-usage-list

It would be very useful to be able to look at all of a month's consumption (or even a day's) in detail, kinda like we could with https://ea.azure.com/report/downloadusage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e05c0768-9cfc-3b78-4f39-70a8c1f0b6bd
* Version Independent ID: b5e5d8fa-e84c-408a-3f49-19d245563abd
* Content: [az consumption usage](https://docs.microsoft.com/en-us/cli/azure/consumption/usage?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/consumption/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/consumption/_help.py)
* Service: **consumption**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
consumption

**Comment by ms-premp** [comment]
We need to ensure the response, does not exceed 30 seconds or 8 MB in size.
This restrictions ensure, that the response is meeting these SLAs.
