### ISSUE TITLE
cannot create any RG through the BASH

### ISSUE THREAD

**Issue by ugrewal** [Azure/azure-cli#14078]
## Describe the bug

**Command Name**
`az ad sp create-for-rbac`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad sp create-for-rbac`

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

```

**Comment by yungezz** [comment]
hi @ugrewal could you pls share the error you met when running the command? It will help investigate and trouble shooting. thanks

**Comment by yonzhan** [comment]
@ugrewal any update?

**Comment by yungezz** [comment]
hi @ugrewal could you pls share specific error here for investigate? Or is this not a problem for you now?

**Comment by yungezz** [comment]
hi @ugrewal will close the issue for now since missing detail error to further trouble shooting. Pls feel free to create a new issue with detail if you met any other error.
