### ISSUE TITLE
"az tag delete" doesn't delete Subscription tags

### ISSUE THREAD

**Issue by logachev** [Azure/azure-cli#14087]
**Describe the bug**

`az tag delete` doesn't delete Subscription tags.

**To Reproduce**
1. Add some tag via the portal to your subscription
2. `az set account -s <subscription>`
3. `az tag list` - verify you see subscription tag
4. `az tag delete --name <your_tag>` -- no error, API returns 204 (checked with Debug)
5. `az tag list` -- your tag is still there (also visible via the portal)

**Expected behavior**
Subscription tag is removed

**Environment summary**
Windows, cmd
azure cli 2.7.0

**Additional context**

**Comment by yonzhan** [comment]
az tag

**Comment by hamidtirmizi** [comment]
`az tag list` behaves differently based on the parameters.

Assuming that you used the parameters you have mentioned above:

- `az tag list` is a computed result. It lists all the tags used on any **resource / resource group under the subscription or the subscription itself**, plus the **predefined tags** on a subscription.
- `az tag delete --name` option deletes **predefined tags** only. If the same tag exists on any other entity listed above, it will continue to be returned by the `az tag list` operation.
