### ISSUE TITLE
No connection string, account key or sas token found,

### ISSUE THREAD

**Issue by PaulCharlton** [Azure/azure-cli#14080]
referencing #12242 

this is nowhere near resolved.
in a pipeline, one can no longer do

1) az storage account create
2) az storage share create

simply put, the contributor role that allows #1 to succeed does not allow #2 to succeed (because it needs the special SA role) and there is no way in a pipeline to assign the IAM permissions for the special SA role without giving the pipeline OWNER access over the subscription.

what did I miss?

are we saying that the creator of the storage account can no longer create resources within it without doing a lot of extra pushups that a logged in user can do, but that a service principal can not do?

re: adding `--auth-mode login` to `az storage share create`.  does not work ==> `az: error: unrecognized arguments: --auth-mode login`

```
az version
{
  "azure-cli": "2.7.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.7.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.51",
    "azure-devops": "0.18.0",
    "mesh": "0.10.6",
    "resource-graph": "1.1.0"
  }
}
```

**Comment by yonzhan** [comment]
add to S172

**Comment by PaulCharlton** [comment]
acceptable workaround for now:
1) az storage account create --name SA
2) CS="$(az storage account show-connection-string --name SA)"
3) az storage share create --connection-string CS --account-name SA --name SHARE_NAME

however, any identity (User, AP, MI) capable of retrieving the connection string should also be able to perform direct action without it

**Comment by Juliehzl** [comment]
Hi @PaulCharlton, it is because file share doesn't support AAD credential as shown [here](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-requests-to-azure-storage) which means you could not use `--auth-mode login`, and you have to use --account-key/--connection-string/--sas-token for file share service.

Another workaround is you could try with `az storage share-rm` to manage file share.
