### ISSUE TITLE
az login fails unexpectedly "NotImplementedError: APIVersion 2019-06-01 is not available"

### ISSUE THREAD

**Issue by Dmitry1987** [Azure/azure-cli#14088]
## Describe the bug
az login fails unexpectedly, in the same environment and docker container where it always was working, very strange.
100% reproducible, fails all the time. 

**Command Name**
`az login`

**Errors:**
```
APIVersion 2019-06-01 is not available
Traceback (most recent call last):
python3.6/dist-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
azure/cli/core/_profile.py, ln 865, in find_from_service_principal_id
    result = self._find_using_specific_tenant(tenant, token_entry[_ACCESS_TOKEN])
azure/cli/core/_profile.py, ln 960, in _find_using_specific_tenant
    subscriptions = client.subscriptions.list()
mgmt/resource/subscriptions/subscription_client.py, ln 132, in subscriptions
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-06-01 is not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal --username {} --password {} --tenant {} --debug`

## Expected Behavior
Login to work, was always working 

## Environment Summary
```
Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9
Installer: PIP

azure-cli 2.7.0 *

```
## Additional Context
Getting error, but it worked just recently, what might cause this?

**Comment by Dmitry1987** [comment]
More detailed debug output is here https://gist.github.com/Dmitry1987/65f00f6bf49242c75d68ec4663456591

**Comment by yonzhan** [comment]
add to S172

**Comment by jiasli** [comment]
Looks like you installed an old version of `azure-mgmt-resource` which doesn't support `2019-06-01`. 

Could you run `pip list` and check the version of `azure-mgmt-resource`?

```
pip list | grep azure-mgmt-resource
```

Also, please check if `/usr/local/lib/python3.6/dist-packages/azure/mgmt/resource/subscriptions/subscription_client.py` contains the same content as the [10.0.0 version of `_subscription_client.py`](https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-resource_10.0.0/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/_subscription_client.py) which is used by Azure CLI:

https://github.com/Azure/azure-cli/blob/b01fbe373a059aa6c746e6e067aac4ac77323211/src/azure-cli/requirements.py3.windows.txt#L71

**Comment by Dmitry1987** [comment]
thanks @jiasli , I think the format of my CLI command doesn't work because new packages are incompatible with the old way of using "username" as ID of the application. The moment I switched from using ID to using "http://url" it started working :)))
I will close the issue. But it's still a backwards incompatibility question, so you might want to put a note somewhere in docs about this transition. An ID of app works in 4.0 azure cli, and doesn't work in 5.

**Comment by jiasli** [comment]
Hi @Dmitry1987, I am glad the issue is solved. 

However, the current Azure CLI version is 2.9.1. We haven't reached 4.0 or 5.0 yet. 😉

https://github.com/Azure/azure-cli/blob/b01fbe373a059aa6c746e6e067aac4ac77323211/src/azure-cli-core/setup.py#L20

I tested with both formats of `--username` and they all work correctly:

```
> az login --service-principal --username http://cliapp --password xxx --tenant 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a
[
  {
    "cloudName": "AzureCloud",
    "id": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
    ...
    
> az login --service-principal --username 45ee948b-9214-4d23-9a52-1a641c7c8009 --password xxx --tenant 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a
[
  {
    "cloudName": "AzureCloud",
    "id": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
    ...
```

Per the debug log, the error is irrelevant to login but to listing subscriptions:

```
  File "/usr/local/lib/python3.6/dist-packages/azure/cli/core/_profile.py", line 960, in _find_using_specific_tenant
    subscriptions = client.subscriptions.list()
  File "/usr/local/lib/python3.6/dist-packages/azure/mgmt/resource/subscriptions/subscription_client.py", line 132, in subscriptions
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-06-01 is not available
```

I would still recommend checking the installation.

**Comment by Dmitry1987** [comment]
got it :)))  I referred to the "azure" python package. because the error appears when I upgrade from 4.x to 5.
but it works now, so it's ok. And thank you for the information, it's appreciated!
