### ISSUE TITLE
az ad app permission list fails with 404 when permission list is not empty

### ISSUE THREAD

**Issue by staff0rd** [Azure/azure-cli#14085]
## Describe the bug

**Command Name**
`az ad app permission list`

**Errors:**

```
Operation failed with status: 'Not Found'. Details: 404 Client Error: Not Found for url: https://graph.windows.net/<myTenantId>/oauth2PermissionGrants?$filter=clientId%20eq%20%27<myAppId>%27&api-version=1.6
```

Items inside `<>` are redacted

## To Reproduce:

Note that prior to adding a permission, `az ad app permission list  --id <myAppId>` correctly returns `[]`.

- Browse to App Registration on portal.azure.com for the given app
- Click API Permissions
- Add Permission > Microsoft Graph > Delegated permissions > Chat.Read
- Execute `az ad app permission list --id <myAppId>`
- 404 Error above is displayed

Removing the permission (via portal) "fixes" the command and it correctly returns `[]` again.

## Expected Behavior
Permission is displayed as result

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

```

**Comment by yonzhan** [comment]
add to S172

**Comment by jiasli** [comment]
Same as https://github.com/Azure/azure-cli/issues/10563#issuecomment-663370704. Could you still reproduce it?

**Comment by jiasli** [comment]
If you are able to reproduce again, please kindly reply here.
