### ISSUE TITLE
Control Panel uninstall fails - azure-cli-2.0.58.msi

### ISSUE THREAD

**Issue by JPPintoDotCom** [Azure/azure-cli#14082]
Its looking for **azure-cli-2.0.58.msi**, it will not uninstall without it. When installing a newer version it tries to uninstall the old one first, resulting in the same error. Install via PowerShell does not work either.

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look? thanks

**Comment by fengzhou-msft** [comment]
@JPPintoDotCom You may need to manually delete `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2` to remove the old `azure-cli-2.0.58`.

**Comment by fengzhou-msft** [comment]
Close due to inactivity. If the issue still persists, please feel free to reopen it.
