### ISSUE TITLE
az vm extension set - doesn't seem working probably 

### ISSUE THREAD

**Issue by mataralhawiti** [Azure/azure-cli#14095]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Running `az vm extension set` 

will enable the extension on the target VM _**but won't**_  create the expected table/s (in my case : **WADWindowsEventLogsTable**) in the give storage account (or write to it if it's already exist).

**To Reproduce**
run the command :
 `az vm extension set --resource-group myrg --vm-name myvm --name IaaSDiagnostics --publisher Microsoft.Azure.Diagnostics --protected-settings protected-settings.json --settings public-settings.json` 

please see my settings below

**Expected behavior**
I expect the extension to be enabled on the target VM, and the subject table will be create in the given storage account according to logs type I'v defined in `public-settings.json`

**Environment summary**

> Windows

> azure-cli                          2.7.0 *

> Powershell 7.0.2

**Additional context**

- what I'm trying to is to enable VM Diagnostic extension to send **Event logs (Application [1,2,3], Security [all], System [1,2,3])** to one unified storage account (let's call logs storage) where **WADWindowsEventLogsTable** is supposed to be created.

- different scenarios I'm trying to implement : 
    1. VM is in the same resource group where logs storage is.
        `The result :` same as explained above
    2. VM in a different resource group where logs storage is.
       `The result :` same as explained above

   3. VM in a different subscription 
      `The result :` the extension will be enabled. However, where I go to Agent tab, I'll get the error message "the value must not be empty" under Storage account section

* **`public-settings.json`**
 `{
  "StorageAccount": "logsstorage",
  "WadCfg": {
    "DiagnosticMonitorConfiguration": {
      "overallQuotaInMB": 5120,
      "WindowsEventLog": {
        "scheduledTransferPeriod": "PT1M",
        "DataSource": [
          {
            "name": "Application!*[System[(Level=1 or Level=2 or Level=3 or Level=4)]]"
          },
          {
            "name": "Security!*"
          },
          {
            "name": "System!*[System[(Level=1 or Level=2 or Level=3)]]"
          }
        ]
      }
    }
  }
}`

* **`protected-settings.json`**
`{
        "storageAccountName": "logsstorage",
        "storageAccountKey": "xxxxxxxx",
        "storageAccountEndPoint": "https://logsstorage.blob.core.windows.net"
}`

* **`cli-command-output.json`**
`{
  "autoUpgradeMinorVersion": true,
  "forceUpdateTag": null,
  "id": "/subscriptions/xxxxxxxxxxx/resourceGroups/myrg/providers/Microsoft.Compute/virtualMachines/tmpvm01/extensions/IaaSDiagnostics",
  "instanceView": null,
  "location": "westeurope",
  "name": "IaaSDiagnostics",
  "protectedSettings": null,
  "provisioningState": "Succeeded",
  "publisher": "Microsoft.Azure.Diagnostics",
  "resourceGroup": "myrg",
  "settings": {
    "StorageAccount": "logsstorage",
    "WadCfg": {
      "DiagnosticMonitorConfiguration": {
        "WindowsEventLog": {
          "DataSource": [
            {
              "name": "Application!*[Application[(Level=1 or Level=2 or Level=3)]]"
            }
          ],
          "scheduledTransferPeriod": "PT1M"
        },
        "overallQuotaInMB": 5120
      }
    }
  },
  "tags": null,
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "typeHandlerVersion": "1.17",
  "virtualMachineExtensionType": "IaaSDiagnostics"
}`

* I suspect the extension version has something to do with the behavior
* I'd like to add that I tried to implement this via powershell (Set-AzVMDiagnosticsExtension) and I was able successfully to get scenarios (1 & 2) to work. However, scenario (3) I encountered same issue using az cli. I've notieced the extension version in powershell is `TypeHandlerVersion      : 1.5`
* I followed instructions on this like [https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostics-extension-windows-install](url)

**Comment by yungezz** [comment]
@qwordy could you pls have a look? thanks

**Comment by mataralhawiti** [comment]
I managed to get this work, thanks for the help from @prernavashistha from Microsoft support 
it turned out there's some inconsistency in the documentations.

According to the documentation here : 
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostics-extension-windows-install
In **protected-settings.json** I should pass the storage URI to  "storageAccountEndPoint" key : 
`{ "storageAccountEndPoint": "https://logsstorage.blob.core.windows.net" }
`
<br>

However, according to another documentation reference : 
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostics-extension-schema-windows#json
I should pass the Azure storage endpoint : 
`{ "storageAccountEndPoint": "https://core.windows.net" }
`

<br>
I can confirm that using Azure storage endpoint resolved the issue, and I can enable the extension across subscriptions, and I can see logs being written to the correct table as expected.
<br><br>

Note:  
I faced the same issue with Powershell, here : 
https://github.com/Azure/azure-powershell/issues/12259

**Comment by yungezz** [comment]
thanks @mataralhawiti . Is it ok to close the issue now?
