### ISSUE TITLE
Error when running command "az vmss update"

### ISSUE THREAD

**Issue by vishal8k** [Azure/azure-cli#14092]
## Describe the bug

**Command Name**
`az vmss update --resource-group myrgname --name myssname --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].ApplicationGatewayBackendAddressPools '{"id": "/subscriptions/mysubid/resourceGroups/myrgname/providers/Microsoft.Network/applicationGateways/Myappgwname/backendAddressPools/mybpnanme"}'`

**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
python3.6/site-packages/msrest/serialization.py, ln 1291, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
python3.6/site-packages/msrest/serialization.py, ln 1081, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
...

python3.6/site-packages/msrest/serialization.py, ln 1104, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss update --resource-group myrgname --name myssname --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].ApplicationGatewayBackendAddressPools '{"id": "/subscriptions/mysubid/resourceGroups/myrgname/providers/Microsoft.Network/applicationGateways/Myappgwname/backendAddressPools/mybpnanme"}'`

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

```

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look

**Comment by Yao725** [comment]
Hi vishal8k , please try this command
`az vmss update --resource-group myrgname --name myssname --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].ApplicationGatewayBackendAddressPools id="/subscriptions/mysubid/resourceGroups/myrgname/providers/Microsoft.Network/applicationGateways/Myappgwname/backendAddressPools/mybpnanme"`

**Comment by Yao725** [comment]
Any update?

**Comment by Yao725** [comment]
Close the issue. Please open a new issue if there is any problem.
