### ISSUE TITLE
 az keyvault list-deleted returns an empty result instead of an AuthorizationError

### ISSUE THREAD

**Issue by bursson** [Azure/azure-cli#14091]
**Describe the bug**
 Command `az keyvault list-deleted` does not return an error even though the user does not have rights to `Microsoft.KeyVault/locations/deletedVaults/read`. Instead it returns an empty result.

**To Reproduce**
1. Soft delete a key vault
2. Run `az keyvault list-deleted` with credentials that do not have `Microsoft.KeyVault/locations/deletedVaults/read`

**Expected behavior**
error: Azure Error: AuthorizationFailed or a similar notification about insufficient permission.

**Environment summary**
Tested with az cli versions 2.5.1 and 2.8.0

**Additional context**

**Comment by yungezz** [comment]
hi @bim-msft could you pls have a look?

**Comment by yungezz** [comment]
hi @bim-msft could you pls share more detail on what's the ask to service team? thanks.

**Comment by bim-msft** [comment]
CLI doesn't know if the user has permission `Microsoft.KeyVault/locations/deletedVaults/read`. So I think this issue should be redirected to ARM side.

`https://management.azure.com/subscriptions/{subs}/providers/Microsoft.KeyVault/deletedVaults?api-version=2019-09-01` didn't raise any exception even if I don't have the permission.

**Comment by solita-burri** [comment]
Hi, as Azure is now by default enabling soft delete on key vaults I feel like this issue needs a higher priority. Developers are almost always working with Contributor level access and therefore this issue causes a lot of frustration and unnecessary debugging (like seen in #14396).
Please consider implementing a mitigation even though I understand that the root cause is a bit complex (and one could argue this works as intended)

**Comment by jlichwa** [comment]
@solita-burri not sure I understand. Contributor level access has '*' which include above permissions. 
The problem occur when user does not have Contributor access.

**Comment by solita-burri** [comment]
@jlichwa Ah sorry, formulated that badly. Developers are often working with rg level Contributor rights (in result of least priviledge and [MS best practises](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/subscriptions/). This leads in situations where developers can create and delete a keyvault succesfully but then it becomes invisible to them.

**Comment by bipul-jha** [comment]
Hey, I'm facing similar problem here.
I deleted a keyvault with soft-delete enabled, but can't really view in the list, to recover/purge it.

Any update on this thread so far? @solita-burri

**Comment by jlichwa** [comment]
It is as designed by service, only highly privileged users with subscription level access can recover the vault.

**Comment by SaurabhSharma-MSFT** [comment]
@bursson Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So, wanted to check if you are still looking for assistance on this query? Please let us know.

**Comment by MetalBeerGeek** [comment]
Dear Microsoft,

Could you please reopen this issue.
As Azure users we would like to see or an error that there are soft-deleted keyvaults we are not allowed to see or just show the list of soft-deleted keyvaults.

Thanks.

**Comment by jlichwa** [comment]
@MetalBeerGeek like mentioned above it ARM issue with REST API it applies to all soft-deleted resources I.e. Storage. There is nothing Key Vault service nor  Key Vault CLI can do.
