### ISSUE TITLE
Cannot update AAD App Registration in B2C Tenant after first user logs in

### ISSUE THREAD

**Issue by silentbobbert** [Azure/azure-cli#14090]
**Command Name**
`az ad app update`

**Errors:**
```
Updates to converged applications are not allowed in this version.
```

## To Reproduce:
Steps to reproduce the behaviour. Note that argument values have been redacted, as they may contain sensitive information.

- Create an Azure B2C Tenant
- Log in to Azure Cli, using a Service Principal or user, with rights over the app registration.
`az login --allow-no-subscriptions --service-principal -t $tenantId -u $clientId -p $clientSecret`
- Create an App Registration or 
- Query App Registrations to find the appIdentifier you want to use to update the App Reg, store value in $appIdentifier variable.
- IMPORTANT - log a user into an application/authenticate using the App Reg within the B2C tenant.
- `az ad app update --id $appIdentifier --add replyUrls "https://<a-valid-dns-zone-record>`

## Expected Behaviour

The reply url is successfully added to the App Reg

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.7.0 *

```
## Additional Context
The `az ad app update` command works absolutely fine on App Registrations within the B2C Tenant, right up until you actually use the App Reg to secure an app and log a user in.

Logging the first user in using the App Reg seems to change the state of the App Reg within a B2C tenant, and makes it "Converged" - no idea what this means in the context of AAD or B2C more specifically.

It is worth pointing out that the update works if you perform the task manually via the Azure Portal. I am building CI/CD pipelines, so this is not an acceptable workaround.

**Comment by yonzhan** [comment]
add to S173

**Comment by jiasli** [comment]
There seems to be some service-side logic with B2C tenants. Unfortunately, we (Azure CLI) currently don't have enough bandwidth on developing and testing with AAD B2C teanants. Sorry about that...

Could you try `az rest` with Microsoft Graph and see if you can get unblocked? See https://github.com/Azure/azure-cli/issues/12946.

**Comment by jiasli** [comment]
Closing as this is more related to the business logic of AAD. 

If you have further questions about AAD, you may [create a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) to AAD and a support engineer will assist you with your concerns or questions.
