### ISSUE TITLE
az webapp log deployment show should show actual logs instead of the log info

### ISSUE THREAD

**Issue by calvinsID** [Azure/azure-cli#14099]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az webapp log deployment show should show actual logs instead of the log info

**To Reproduce**
az webapp log deployment show

**Expected behavior**
Show actual deployment logs instead of info about the deployment logs

Sample output:
[
  {
    "log_time": "2020...",
    "id": "id",
    "message": "log message",
    "type": 0,
    "details_url": null
  },
  {
    "log_time": "2020...",
    "id": "id",
    "message": "log message 2",
    "type": 0,
    "details_url": null
  }
]

**Comment by yonzhan** [comment]
webapp
