### ISSUE TITLE
Azure Arc for Kube GitOps Policy deletion fails silently

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/azure-cli#14105]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I have successfully deployed the Azure Policy "Deploy GitOps to Kubernetes cluster" - in Preview - 
which I can then see with CLI:
az policy assignment list -g $k3s_rg_name

But then when I sue CLI to delete it, there is no output but the polcy is not deleted, I can see it in the portal and also with:
az policy assignment list -g $k3s_rg_name

See:
- [https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/use-azure-policy](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/use-azure-policy)
- [https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/policy-samples](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/policy-samples)
- [https://docs.microsoft.com/en-us/azure/governance/policy/how-to/remediate-resources](https://docs.microsoft.com/en-us/azure/governance/policy/how-to/remediate-resources)
- [https://docs.microsoft.com/fr-fr/cli/azure/policy/definition?view=azure-cli-latest#az-policy-definition-create](https://docs.microsoft.com/fr-fr/cli/azure/policy/definition?view=azure-cli-latest#az-policy-definition-create)
- [https://docs.microsoft.com/fr-fr/cli/azure/policy/remediation?view=azure-cli-latest#az-policy-remediation-create](https://docs.microsoft.com/fr-fr/cli/azure/policy/remediation?view=azure-cli-latest#az-policy-remediation-create)

**To Reproduce**

az policy assignment list -g $k3s_rg_name
az policy definition delete --name "k3s-gitops-enforcement"
az policy assignment list -g $k3s_rg_name

az policy definition delete --name "k3s-gitops-enforcement" --debug
Command arguments: ['policy', 'definition', 'delete', '--name', 'k3s-gitops-enforcement', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fc5e82bc7b8>, <function OutputProducer.on_global_arguments at 0x7fc5e80187b8>, <function CLIQuery.on_global_arguments at 0x7fc5e803f9d8>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.008 seconds.
Loaded module 'acs' in 0.007 seconds.
Loaded module 'advisor' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.006 seconds.
Loaded module 'apim' in 0.002 seconds.
Loaded module 'appconfig' in 0.003 seconds.
Loaded module 'appservice' in 0.012 seconds.
Loaded module 'aro' in 0.005 seconds.
Loaded module 'backup' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.032 seconds.
Loaded module 'batchai' in 0.003 seconds.
Loaded module 'billing' in 0.002 seconds.
Loaded module 'botservice' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.006 seconds.
Loaded module 'cloud' in 0.002 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.002 seconds.
Loaded module 'consumption' in 0.002 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.008 seconds.
Loaded module 'deploymentmanager' in 0.002 seconds.
Loaded module 'dla' in 0.004 seconds.
Loaded module 'dls' in 0.003 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.004 seconds.
Loaded module 'eventhubs' in 0.004 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.006 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.007 seconds.
Loaded module 'kusto' in 0.002 seconds.
Loaded module 'lab' in 0.004 seconds.
Loaded module 'managedservices' in 0.002 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.007 seconds.
Loaded module 'natgateway' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.003 seconds.
Loaded module 'network' in 0.035 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.004 seconds.
Loaded module 'profile' in 0.001 seconds.
Loaded module 'rdbms' in 0.008 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.002 seconds.
Loaded module 'resource' in 0.010 seconds.
Loaded module 'role' in 0.004 seconds.
Loaded module 'search' in 0.001 seconds.
Loaded module 'security' in 0.002 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'signalr' in 0.002 seconds.
Loaded module 'sql' in 0.009 seconds.
Loaded module 'sqlvm' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.065 seconds.
Loaded module 'vm' in 0.018 seconds.
Loaded all modules in 0.350 seconds. (note: there's always an overhead with the first module loaded)
Found 2 extensions: ['k8sconfiguration', 'connectedk8s']
Extension compatibility result: is_compatible=True cli_core_version=2.7.0 min_required=2.3.1 max_required=None
Extensions directory: '/home/azarc-admin/.azure/cliextensions/k8sconfiguration'
Loaded extension 'k8sconfiguration' in 0.003 seconds.
Extension compatibility result: is_compatible=True cli_core_version=2.7.0 min_required=2.0.67 max_required=None
Extensions directory: '/home/azarc-admin/.azure/cliextensions/connectedk8s'
Loaded extension 'connectedk8s' in 0.027 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fc5e5665950>]
az_command_data_logger : command args: policy definition delete --name {} --debug
metadata file logging enabled - writing logs to '/home/azarc-admin/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fc5e567eae8>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fc5e563eae8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fc5e563ec80>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7fc5e4cd4488>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fc5e8018840>, <function CLIQuery.handle_query_parameter at 0x7fc5e803fa60>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fc5e563eb70>, <function handler at 0x7fc5e4bacea0>]
Getting management service client client_type=PolicyClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.service_client : Accept header absent and forced to application/json
attempting to read file /home/azarc-admin/.azure/accessTokens.json as utf-8-sig
adal-python : 20a1662c-6de8-4e10-b11a-cf6d69ba5dea - Authority:Performing instance discovery: ...
adal-python : 20a1662c-6de8-4e10-b11a-cf6d69ba5dea - Authority:Performing static instance discovery
adal-python : 20a1662c-6de8-4e10-b11a-cf6d69ba5dea - Authority:Authority validated via static instance discovery
adal-python : 20a1662c-6de8-4e10-b11a-cf6d69ba5dea - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : 20a1662c-6de8-4e10-b11a-cf6d69ba5dea - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : 20a1662c-6de8-4e10-b11a-cf6d69ba5dea - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : 20a1662c-6de8-4e10-b11a-cf6d69ba5dea - CacheDriver:Found 3 potential entries.
adal-python : 20a1662c-6de8-4e10-b11a-cf6d69ba5dea - CacheDriver:Resource specific token found.
adal-python : 20a1662c-6de8-4e10-b11a-cf6d69ba5dea - CacheDriver:Returning token from cache lookup, AccessTokenId: b'sfKgWlhjt6fUMliMGw0nlvDuyfvpCx2atUIbGjhzPGI=', RefreshTokenId: b'40BoJPoAYexeIjX6ZzH5o0yXnwAJwFeByAdOkypvBNk='
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/7b5f97dc-3c4d-424d-8288-bdde3891f242/providers/Microsoft.Authorization/policyDefinitions/k3s-gitops-enforcement?api-version=2019-09-01'
msrest.http_logger : Request method: 'DELETE'
msrest.http_logger : Request headers:
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'User-Agent': 'python/3.6.10 (Linux-5.3.0-1028-azure-x86_64-with-debian-buster-sid) msrest/0.6.9 msrest_azure/0.6.3 azure-mgmt-resource/9.0.0 Azure-SDK-For-Python AZURECLI/2.7.0 (DEB)'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "DELETE /subscriptions/7b5f97dc-3c4d-424d-8288-bdde3891f242/providers/Microsoft.Authorization/policyDefinitions/k3s-gitops-enforcement?api-version=2019-09-01 HTTP/1.1" 204 0
msrest.http_logger : Response status: 204
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-request-id': 'westeurope:3186f94b-10c5-4ba6-bf24-55681fb7d3c1'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-deletes': '14999'
msrest.http_logger :     'x-ms-correlation-request-id': '10540550-52d8-465e-a7e1-54891eeb1f43'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTEUROPE:20200625T152322Z:10540550-52d8-465e-a7e1-54891eeb1f43'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Thu, 25 Jun 2020 15:23:22 GMT'
msrest.http_logger : Response content:
msrest.http_logger :
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7fc5e5634488>, <function _x509_from_base64_to_hex_transform at 0x7fc5e5634510>]
Event: CommandInvoker.OnFilterResult []
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fc5e5665b70>]

**Expected behavior**

The Policy should be deleted

**Environment summary**

az version
{
  "azure-cli": "2.7.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.7.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "connectedk8s": "0.2.1",
    "k8sconfiguration": "0.1.8"
  }
}

**Additional context**

**Comment by ezYakaEagle442** [comment]
I could successfully delete it from the portal

**Comment by yonzhan** [comment]
add to S172

**Comment by ezYakaEagle442** [comment]
my bad the CLI command was wrong, the correct one is : 
```sh
az policy assignment delete --name xxx -g $rg_name
```

**Comment by yonzhan** [comment]
@ezYakaEagle442  Do you still need this issue or your issue was resolved?

**Comment by ezYakaEagle442** [comment]
@yonzhan issue resolved, cab be closed, Thanks.
