### ISSUE TITLE
CLI Support for enabling double encryption for Managed Disks 

### ISSUE THREAD

**Issue by ramankumarlive** [Azure/azure-cli#14107]
**Resource Provider**
Microsoft.Compute

**Description of Feature or Work Requested**

Double encryption at rest is the continuation of server-side encryption (SSE) at rest with customer managed keys (CMK) that we recently announced in GA for managed disks. SSE with CMK allows customers to encrypt the data stored on managed disks at rest with AES 256 encryption. High security sensitive customers who are concerned of the risk associated with any particular encryption algorithm, implementation , or key being compromised can now opt for additional layer of encryption using a different encryption algorithm/mode using platform managed encryption keys. 

To enable two layers of encryption at rest for Managed Disks attached to VMs/VMSS, you must must create a DiskEncryptionSet with encryptionType set as EncryptionAtRestWithPlatformAndCustomerKeys and then associate the DiskEncryptionSet to managed disks. 

You can find more details and sample ARM templates here: https://github.com/ramankumarlive/manageddisksdoubleencryptionpreview

**Minimum API Version Required**
2020-05-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/9552

**Target Date**
7/10 for "Enterprise" M4 milestone

**Comment by yungezz** [comment]
JEDI feature request. hi @ramankumarlive next Azure CLI official release date will be July 14th. Let's discuss the timeline offline in email.

**Comment by ramankumarlive** [comment]
@yungezz Please use this swagger link: https://github.com/Azure/azure-rest-api-specs/pull/9937

**Comment by yungezz** [comment]
need bump version

**Comment by yungezz** [comment]
hi @qwordy why the issue is re-opened?

**Comment by qwordy** [comment]
> 
> 
> hi @qwordy why the issue is re-opened?

Bug of Github
