### ISSUE TITLE
Add 'az apim restore' command

### ISSUE THREAD

**Issue by subesokun** [Azure/azure-cli#14114]
**Is your feature request related to a problem? Please describe.**

The Azure CLI only supports creating a backup of the APIM but provides no command to restore it from a given backup.

**Describe the solution you'd like**

Add a `az apim restore` command to restore the APIM from a backup

**Additional context**

https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-disaster-recovery-backup-restore#-restore-an-api-management-service

**Comment by yonzhan** [comment]
apim

**Comment by Jeej** [comment]
Please add the restore command. It is possible to backup, but restore is apperently not possible 😢

**Comment by PramodValavala-MSFT** [comment]
@subesokun This has since been implemented. Thanks @Jeej for the PR. We are closing this issue.
