### ISSUE TITLE
Cannot update tag on Azure Cache via 'az resource tag' if the tier is Basic

### ISSUE THREAD

**Issue by tr-hagfjall** [Azure/azure-cli#14111]
## Describe the bug

**Command Name**
`az resource tag`

**Errors:**
```
The setting 'maxmemory-reserved' is not allowed on 'Basic' cache instances.
RequestID=05846e23-e636-4036-ba64-3ad4b058e9a5
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az resource tag -i --ids <ID to a Redis cache with basic tier> --tags Name=Value`

## Expected Behavior
The tag to be updated or set

## Environment Summary
```
Linux-5.4.0-37-generic-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

```

**Comment by yonzhan** [comment]
add to S173

**Comment by zhoxing-ms** [comment]
There are some problems in updating the tags of Redis Cache by using `PUT` request. So we will update the tags of Redis Cache with `PATCH` request instead.
However, there are some problems in the REST API of [`Redis - Update`](https://docs.microsoft.com/en-us/rest/api/redis/redis/update), which needs to be checked by the service team.
The error returned by service is as follows:
```pwsh
{"error":{"code":"Conflict","message":"The resource '/subscriptions/xxx/resourceGroups/zhoxing-test/providers/Microsoft.Cache/Redis/zhoxing3' is busy processing a previous update request or is undergoing system maintenance.  As such, it is currently unable to accept the update request.  Please try again later.\r\nRequestID=3fcd6585-4f74-40fd-8403-fbde075b78a3","target":null}}
```
> RequestID=3fcd6585-4f74-40fd-8403-fbde075b78a3

**Comment by navba-MSFT** [comment]
@tr-hagfjall Apologies for the late reply. I was able to repro this issue and seems like its still not fixed. I have reached out to the Product Owners to check the update on the fix. I will update this thread once I have more details on this. In the meantime you can invoke [this](https://docs.microsoft.com/en-us/rest/api/resources/tags/update-at-scope) REST API and check if that helps.
