### ISSUE TITLE
Enable dimension for Azure Monitor auto-scale rule

### ISSUE THREAD

**Issue by Sneezry** [Azure/azure-cli#14126]
**Resource Provider**

Microsoft.Insights/autoscaleSettings

**Description of Feature or Work Requested**

https://github.com/Azure/azure-rest-api-specs/pull/9945

**Minimum API Version Required**

2015-04-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/9945

**Target Date**

TBD

**Comment by Sneezry** [comment]
Copy @MyronFanQiu for awareness.

**Comment by yonzhan** [comment]
add to S173
