### ISSUE TITLE
Got "unable to parse parameter: xxxx.parameters.json " error when running az deployment group create  command

### ISSUE THREAD

**Issue by Xiaojing123456** [Azure/azure-cli#14122]
Questions: 

1. I try to deploy AKS with ARM template via CLI, but when i run below command
az deployment group create --resource-group test --name test --template-file azuredeploy.json --parameters xxxx.deploy.parameters.json  
it prompts me "unable to parse parameter: xxxx.deploy.parameters.json" error.  
2. My colleague use same commands ，same template, same machine, but different azure account, the creation commands work fine for him.  
3. I try to use different cli version on different machine, it prompts the same error, which looks related with account

Who can help take a look at the issue, thanks!

**Comment by yonzhan** [comment]
add to S172

**Comment by zhoxing-ms** [comment]
@Xiaojing123456 Hi, could you please show me the specific ARM template and parameters you used? And please add `--debug` to the original command and email the printed information to me~
My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
