### ISSUE TITLE
Release to WinGet Simultaneously

### ISSUE THREAD

**Issue by wjvii** [Azure/azure-cli#14120]
**Resource Provider**
Releases

**Description of Feature or Work Requested**
I would like to request that new versions, including beta/preview versions, be available via WinGet at the same time they are available for download on the Install Azure CLI on Windows page. Not sure if it is because WinGet is new but noticed that 2.8.0 has been available for download from the web page for a while but the current version on WinGet as of this post is still 2.7.0 and there is no preview or beta version listed on WinGet that I can see.

Thank you.

**Comment by yungezz** [comment]
thanks for reporting the issue. today Azure cli support in WinGet is contributed by community. We'll evaluate the requirement and see what's next step.

**Comment by rido-min** [comment]
> Azure cli support in WinGet is contributed by community

do you need a new issue to officially support the WinGet distribution?

**Comment by fengzhou-msft** [comment]
Added a task to publish to winget in our release pipeline.
