### ISSUE TITLE
az lab custom-image create __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by rolandas-rimkus** [Azure/azure-cli#14127]
## Describe the bug

**Command Name**
`az lab custom-image create`

**Errors:**
```
__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
Temp\pip-install-363drsgw\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 711, in _run_job
Local\Temp\pip-install-363drsgw\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
site-packages\azure\cli\core\__init__.py, ln 545, in default_command_handler
azure\cli\command_modules\lab\custom.py, ln 20, in create_custom_image
TypeError: __init__() takes 1 positional argument but 2 were given
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az lab custom-image create --lab-name {} --resource-group {} --name {} --author {} --description {} --os-type {} --os-state {} --source-vm-id {} --debug`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.8.0

Extensions:
azure-devops 0.18.0

```
## Additional Context
The same command is working with older Azure CLI version 2.5.1

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by tanmayeekamath** [comment]
@rolandas-rimkus 
Thanks for your feedback. 

We have filed a bug for this issue and working on fixing it. 

I will update once the fix is out.

-Tanmayee

**Comment by pedroneil** [comment]
Is there any update on this bug; or a work around or documentation of which vesion of azure-cli I could use to avoid this bug?

**Comment by tanmayeekamath** [comment]
@pedroneil Apologies for the delay on this one. We are actively working on this and should push the fix in within the next couple of days. It will be fixed once the CLI team incorporates our fix. 
Reverting to the previous version of the cli should temporarily solve this problem. 

Thanks for your patience,
Tanmayee

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14127
