### ISSUE TITLE
azure.core.exceptions.ServiceRequestError: Can't connect to HTTPS URL because the SSL module is not available

### ISSUE THREAD

**Issue by prakashb83** [Azure/azure-cli#14129]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
using Python script to retrieve Azure Key Vault Certificates using client library (azure-keyvault-certificates 4.1.0)

Facing below issue in Linux Ubuntu VM and windows 10
azure.core.exceptions.ServiceRequestError: Can't connect to HTTPS URL because the SSL module is not available.

**To Reproduce**
from azure.identity import DefaultAzureCredential
from azure.keyvault.certificates import CertificateClient
credential = DefaultAzureCredential()
certificate_client = CertificateClient(vault_url="https://my-key-vault.vault.azure.net/", credential=credential)
certificate = certificate_client.get_certificate("cert-name")
print(certificate.name)
print(certificate.properties.version)
print(certificate.policy.issuer_name)

-Please change Azure key vault name and certificate name 
-Save file keyvaultcertificates.py file
-Python keyvaultcertificates.py

**Expected behavior**
to able to  retrieves a certificate previously stored in the Key Vault without having to specify version

**Environment summary**
Linux: ubuntu 18.04
Create virtual environment for Python :pythonenv
Python version : 3.6.9
azure cli : 2.8
Pip3 : 20.1.1
Installed openssl : 1.1.1 

Windows : 10 
**Additional context**
i will download azure key vault ssl certifate to pkcs12 format (.pfx) file.

**Comment by yonzhan** [comment]
Python SDK issue

**Comment by prakashb83** [comment]
Hi Yonzhan,
I have already included "azure-keyvault-certificates 4.1.0" using pip install azure-keyvault-certificates. 
could you please share more details?

**Comment by yonzhan** [comment]
@yungezz can help you with it.

**Comment by prakashb83** [comment]
@bim-msft: could you please update the status of the above issue? it would be helping me.

**Comment by bim-msft** [comment]
Hi @prakashb83 this seems to be an error on Python SDK side, please create an issue here: https://github.com/Azure/azure-sdk-for-python/issues 
Based on my knowledge, this library (`azure-keyvault-certificates==4.1.0`) is a new one with many breaking changes. Azure CLI uses `azure-keyvault==1.1.0` to handle certificates, you may try this one for a quick solution.

**Comment by prakashb83** [comment]
Hi @bim-msft : thanks for your updates. I will create an issue here: https://github.com/Azure/azure-sdk-for-python/issues.
I tried with Azure CLI to use azure-keyvault==1.1.0 but facing the same issue.

**Comment by yungezz** [comment]
hi @prakashb83 could you pls share the azure cli commands you're using? From description, it's a python sdk issue.

**Comment by yungezz** [comment]
hi @prakashb83 could you pls share azure cli commands you're using if you met same issue when using cli? thanks.

**Comment by bim-msft** [comment]
Hi @prakashb83 please try upgrade your CLI to latest (2.11.0 or later). It might work. If it still doesn't work, please let me know, thanks!

**Comment by yungezz** [comment]
hi @prakashb83 will close the issue for now given less information for investigation. and issue is tracked at sdk side. Feel free to create new issue if any other ask. thanks!
