### ISSUE TITLE
az login --identity command failing - "MSI: Failed to acquire tokens after 12 times"

### ISSUE THREAD

**Issue by prchanda** [Azure/azure-cli#14136]
## Describe the bug
**az login --identity** command is failing inside an azure container instance having ubuntu-1804 image with the below error. The error is only happening in Mooncake tenant, in public it works as expected. The below command is a part of a bash script which runs inside the container.

**Command Name**
az login --identity

**Errors:**
The command failed with an unexpected error. Here is the traceback:2020-06-29 11:46:52.763993: 2020-06-29 11:46:52.767047: MSI: Failed to acquire tokens after 12 times2020-06-29 11:46:52.767149: Traceback (most recent call last):2020-06-29 11:46:52.767432: File \"/opt/az/lib/python3.6/site-packages/knack/cli.py\", line 215, in invoke2020-06-29 11:46:52.767571: cmd_result = self.invocation.execute(args)2020-06-29 11:46:52.767746: File \"/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py\", line 654, in execute2020-06-29 11:46:52.767908: raise ex2020-06-29 11:46:52.768021: File \"/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py\", line 718, in _run_jobs_serially2020-06-29 11:46:52.768257: results.append(self._run_job(expanded_arg, cmd_copy))2020-06-29 11:46:52.768389: File \"/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py\", line 711, in _run_job2020-06-29 11:46:52.768654: six.reraise(*sys.exc_info())2020-06-29 11:46:52.768873: File \"/opt/az/lib/python3.6/site-packages/six.py\", line 703, in reraise2020-06-29 11:46:52.768993: raise value2020-06-29 11:46:52.769087: File \"/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py\", line 688, in _run_job2020-06-29 11:46:52.769246: result = cmd_copy(params)2020-06-29 11:46:52.769374: File \"/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py\", line 325, in __call__2020-06-29 11:46:52.769504: return self.handler(*args, **kwargs)2020-06-29 11:46:52.769619: File \"/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py\", line 545, in default_command_handler2020-06-29 11:46:52.769678: return op(**command_args)2020-06-29 11:46:52.769776: File \"/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py\", line 128, in login2020-06-29 11:46:52.769833: return profile.find_subscriptions_in_vm_with_msi(username, allow_no_subscriptions)2020-06-29 11:46:52.769955: File \"/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py\", line 346, in find_subscriptions_in_vm_with_msi2020-06-29 11:46:52.770053: msi_creds = MSIAuthentication(resource=resource)2020-06-29 11:46:52.770111: File \"/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py\", line 592, in __init__2020-06-29 11:46:52.770207: self.set_token()2020-06-29 11:46:52.770267: File \"/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py\", line 600, in set_token2020-06-29 11:46:52.770361: token_entry = self._vm_msi.get_token(self.resource)2020-06-29 11:46:52.770435: File \"/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py\", line 649, in get_token2020-06-29 11:46:52.770525: token_entry = self._retrieve_token_from_imds_with_retry(resource)2020-06-29 11:46:52.770583: File \"/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py\", line 709, in _retrieve_token_from_imds_with_retry2020-06-29 11:46:52.770690: raise MSIAuthenticationTimeoutError('MSI: Failed to acquire tokens after {} times'.format(max_retry))2020-06-29 11:46:52.770758: msrestazure.azure_exceptions.MSIAuthenticationTimeoutError: MSI: Failed to acquire tokens after 12 times

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- Spin an azure container instance with ubuntu 1804 image
- Run **az login --identity** command

## Expected Behavior
az login --identity should be successful so subsequent az cli commands would run under the context of logged-in user managed identity.

## Environment Summary
```
ubuntu-1804-l
Azure Cli 2.6.0
App Service
dotnet core 3.1.*
```

**Comment by yonzhan** [comment]
add to S173

**Comment by yungezz** [comment]
HI @prchanda, if it's mooncake, did you try `az cloud set` to set to AzureChinaClou?

**Comment by prchanda** [comment]
Yeah after setting the cloud, the issue got resolved.
