### ISSUE TITLE
az create db when using compute-model "provisioned" capacity should be > 1 

### ISSUE THREAD

**Issue by tino-reichel** [Azure/azure-cli#14130]
az create db when using compute-model "provisioned" capacity should be > 1 
doucmentation and warning is wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bdd674-b454-e863-c943-9c979b466a92
* Version Independent ID: b15341f9-3f1b-00e0-a1c2-970f25a6ab03
* Content: [az sql db](https://docs.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
sql

**Comment by RakeshMohanMSFT** [comment]
Fixed by https://github.com/Azure/azure-cli/pull/23433
