### ISSUE TITLE
az network application-gateway ssl-cert -- Is there any option to view the expiry of SSL cert 

### ISSUE THREAD

**Issue by subhasishdc** [Azure/azure-cli#14132]
**Is your feature request related to a problem? Please describe.**
`az network application-gateway ssl-cert` is used to manage the SSL certificates of an application gateway. However, I am not able to find any option to view the expiry date of the certificate. Getting to know the expiry date is essential at times and would be a helpful feature to have. Is there any way to view the expiry of the SSL certificate of an application gateway.

**Describe the solution you'd like**
Having an option to view the expiry date of an SSL certificate of an application gateway would be very helpful. If there is already a way to do it, adding an example in the cli and docs would be very helpful.

**Describe alternatives you've considered**
Tried the following command but did not find any good way to extract the SSL certificate expiry

(**Note that argument values have been redacted, as they may contain sensitive information.**)

`az network application-gateway ssl-cert show -g test-rg --gateway-name test-aag --name test.example.com`
`{
  "data": null,
  "etag": "W/\"136379e-3fcca\"",
  "id": "/subscriptions/zbca-fa02b/resourceGroups/test-rg/providers/Microsoft.Network/applicationGateways/test-aag/sslCertificates/test.example.com",
  "keyVaultSecretId": null,
  "name": "test.example.com",
  "password": null,
  "provisioningState": "Succeeded",
  "publicCertData": "QMVPYn209pT/4k2IBDL1AB0z1WJH7Jioqeu72l/XLJpUlTYZ90le68xxM727Cz2GKpXyak1f19+4oK52is7td59BS60sF+O0dUKtaaS8hE26NXeVVY+1pOjyid70irCMeJda5JPrTKjEA",
  "resourceGroup": "test-rg",
  "type": "Microsoft.Network/applicationGateways/sslCertificates"
}`

**Comment by yonzhan** [comment]
add to S173

**Comment by MyronFanQiu** [comment]
@subhasishdc Thanks for raising this issue. Based on my understanding, expiry time is part of SSL cert and we can obtain the data information of the cert. Using some X509 library, should we be able to see the date?

**Comment by subhasishdc** [comment]
@MyronFanQiu : Thank you for the clarification. The `publicCertData` field shown in the example able displays the cert but there is no information anywhere on what format this cert is in. I read somewhere online that the format returned by the command in the example is PKCS7. Is that correct? Can you provide some clarity on the field `publicCertData` which is returned by the `az network application-gateway ssl-cert list|show` commands.

**Comment by MyronFanQiu** [comment]
@subhasishdc Hi. I don't know too much about PKCS7. User need to input a `.pfx` file. so I think it might be PKCS 12? Here is one of our [test file](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/tests/latest/TestCert2.pfx) and hope it can help you.

**Comment by subhasishdc** [comment]
@MyronFanQiu : I did a lot of digging on the `publicCertData` field returned by the `az network application-gateway ssl-cert list|show` commands to find out what format it is in. It looks like it is in PKCS7 format. Example is as follows:

`$ openssl pkcs7 -print_certs -in test_domain_com.p7b | openssl x509 -noout -enddate
notAfter=Jul 30 12:00:00 2020 GMT`

I created a cert file in the example above with the data of the field `publicCertData`. The pkcs7 format got decrypted correctly.

Can you please confirm the above. Also, would it be a good idea to add this information as an example both to the CLI and documentation. If yes, I can do it.

**Comment by MyronFanQiu** [comment]
@subhasishdc We always appreciate any better help message. 😄 Based on your command, looks like you store the data into `.p7b` file. `.p7b` file is PKCS7. According to my understanding, if you use a `.pfx` to store this file, it will need pkcs12? I'm not sure whether we can use `.p7b` file as the cert-file. I can invite service team to double confirm this behavior.

**Comment by subhasishdc** [comment]
@MyronFanQiu : I tried saving it to a `.pfx` file and tried to decode it but it throws an error. Hence, it is not in pkcs12 format. On storing it in `.p7b` format, the decoding is successful. Therefore, I am sure the format is pkcs7. Can you confirm with the service team on this. If they confirm, I will modify the help message.

`$ openssl pkcs12 -in test_domain_com.pfx -out test_domain_com.pem -nodes`
`140550717241232:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1220:
140550717241232:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:386:Type=PKCS12`

**Comment by subhasishdc** [comment]
@MyronFanQiu : Did you get any update from the service team on this

**Comment by subhasishdc** [comment]
@MyronFanQiu : Discussed this with Akshay Gupta from the service team. He has confirmed that the command takes a `pfx` file as input which is `pkcs12` and show/list shows only the public part of the cert which `pkcs7`.

I will create a PR to add a good example to the help section and documentation to demonstrate this behavior so that it is of help for everyone. Will let you know once I do it.
