### ISSUE TITLE
Unable to install Azure CLI on ARM

### ISSUE THREAD

**Issue by Bengkel** [Azure/azure-cli#14135]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I created a custom ARM build agent (Raspberry Pi 4)  for Azure DevOps. The Azure CLI cannot be installed on a ARM device.

**To Reproduce**
Run curl -L https://aka.ms/InstallAzureCli | bash on a ARM OS and following exception is thrown:

`Step 17/20 : RUN curl -L https://aka.ms/InstallAzureCli | bash ---> Running in be258d20be60 % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 1405 100 1405 0 0 1222 0 0:00:01 0:00:01 --:--:-- 5665 Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /tmp/azure_cli_install_tmp_VfdhGm. ######################################################################## 100.0% /tmp/azure_cli_install_tmp_VfdhGm: OK Running install script. bash: line 42: /dev/tty: No such device or address The command '/bin/sh -c curl -L https://aka.ms/InstallAzureCli | bash' returned a non-zero code: 1`

**Expected behavior**
I expect the installation script to install the Azure CLI as described on [docs.microsoft.com](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest)

**Environment summary**
I tried to install the lastest version of Azure CLI on Raspbian/Stretch, Raspbian/Buster and arm32v7/Ubuntu18.04. 

**Additional context**
I installed tried to install the Azure CLI manually with the same result.
Installing the classic Azure CLI works, but is not usable. Azure DevOps requires a newer version of Azure Cli.

**Comment by yonzhan** [comment]
packaging

**Comment by yungezz** [comment]
hi @Bengkel could you pls share detail OS version info?  I don't think azure cli is supported on ARM device officially. we didn't test it before, while would like to see more info.

**Comment by Bengkel** [comment]
Hi, as you can read in [this blog](https://devblogs.microsoft.com/iotdev/setup-azure-iot-edge-ci-cd-pipeline-with-arm-agent/), Azure CLI was supported on ARM devices.

I tried to install the Azure Cli on arm32/v7Ubuntu18.04, raspbian/stretch and raspbian/buster. 

I included [Docker.zip](https://github.com/Azure/azure-cli/files/4847548/Docker.zip). It shows the several attempts to install the Azure CLI and will give you the opportunity to reproduce the exception by uncommenting the different lines.

**Comment by arturoqu77** [comment]
I have a similar ask, I have partners using RASPBERRY PIs in TEST envirs for Azure IoT Edge scenarios, they need to use azure cli in the RASPBERRY PI 4 model (armhf). I saw that there used to be an azure-cli for use in armhf before in the snapd store from canonical, but it was deprecated and never updated since 2018. The partners I have are running kubernetes clusters in the PIs with no issues as kubernetes (microK8S and K3S) is provided to run in armhf and arm64 platforms . It would be fantastic to be able to run azure-cli in the armhf and arm64 platforms, there are many use cases that need to have intelligent edge IoT devices to connect to Azure via the CLI. I know an ask like this means a lot of work, and that requests like this need to be triaged, but it would be a very welcome development if it does pass the triaging phase.

**Comment by fengzhou-msft** [comment]
Can you use `pip install azure-cli`?

**Comment by arturoqu77** [comment]
Thank you, that did the trick, I used pip3 as I need it to work with python3. The install worked, I will now check the commands we require...thank you

**Comment by Bengkel** [comment]
Doesn't work for me 

```
Step 18/22 : RUN        pip install azure-cli
 ---> Running in 88de22789493
Collecting azure-cli
  Downloading https://files.pythonhosted.org/packages/f5/b5/08d5ccada7653998fe40f5c3e2a268d5bbbef2c1e34d1bc88fa8246881e3/azure-cli-2.8.0.tar.gz (1.4MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ZlJkuS/azure-cli/
The command '/bin/sh -c pip install azure-cli' returned a non-zero code: 1
```

**Comment by Czhang0727** [comment]
Hitting the same error here seems the issue is Azure-Cli somehow referred to internal python3 which does not compatible with armhf. Manual switch python3 to os will fix the issue.

**Comment by crixo** [comment]
@Czhang0727 I have the same problem too. The funny thing is that it seems to exist an ARM64 version https://pkgs.org/download/azure-cli.
MS documentation https://docs.microsoft.com/it-it/cli/azure/install-azure-cli-linux?pivots=apt use only amd63 example and says "The apt package manager contains an x86_64 package for the Azure CLI...." 
It seems there's a blurry zone as far as I understand.

**Comment by Zeushn** [comment]
Same here, tried with docker and pip not luck, there is was a previous version working on Pi 2 that seems to worked.

**Comment by asergaz** [comment]
fyi @fengzhou-msft we have another reported issue in docs: https://github.com/MicrosoftDocs/azure-docs/issues/80763 

Do we have any progress on resoving this issue? Thanks

**Comment by jiasli** [comment]
Let's focus on https://github.com/Azure/azure-cli/issues/7368.
