### ISSUE TITLE
[Storage] Enable batch-copy between file service and blob service

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1414]
This issue is used to track the a few follow-up tasks once #1250 is in:
- [x] Enable copying to blob container from file share
- [x] Enable copying to file share from blob container
- [x] Support source and destination in the form of URL

**Comment by troydai** [comment]
In https://github.com/Azure/azure-cli/pull/1510, copy from blob to file share is enabled.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
