### ISSUE TITLE
az resource group deployment show should take --ids parameter

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#1415]

**Comment by brendandburns** [comment]
@johanste what would `--ids` contain?  Would it be a list of deployment names?  Resource IDs?  Do we want `--names` also?

I'm happy to implement but the comment is vague.

Thanks!
--brendan

**Comment by johanste** [comment]
`--ids` would take one or more deployment ids to show. The resource that this is not showing up correctly is that the id_part property of the deployment_name parameter is not set to 'name'.

**Comment by brendandburns** [comment]
@johanste I'm still not sure I follow...

`az resource group deployment show` maps to `#DeploymentsOperations.get` which doesn't have an `id` parameter which I can find:

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-resource/azure/mgmt/resource/resources/operations/deployments_operations.py#L306

There is:

`acs resource group deployment operation show` which does have a `--operation-id` parameter.  Is that the thing you think should be shortened `--id`?

It seems weird in general that `show` would take multiple ids, that seems more like a `list`.

**Comment by tjprescott** [comment]
@brendandburns ultimately the multiple shows are appended to a list, but "a list of shows" can potentially have more information than simply "a list" depending on what is returned from the server.

**Comment by brendandburns** [comment]
Ok, so then is this requesting that:

```console
$ az resource group deployment operation show --ids=foo,bar,baz
```

Should it be `--operation-ids` for consistency with the existing `--operation-id` flag?

Thanks!

**Comment by tjprescott** [comment]
`$ az resource group deployment operation show --ids foo bar baz`

The CLI uses spaces to separate things with `nargs='+'` specified in the parameter alias.

I'll defer to @johanste on the name, but I think we would keeps it --ids.
