### ISSUE TITLE
No subscription ID specified in the URL

### ISSUE THREAD

**Issue by smokedlinq** [Azure/azure-cli#14152]
**Describe the bug**
When using `az rest` command the error _No subscription ID specified in the URL_ is returned in version 2.8.0.

**To Reproduce**
1. Install azcli 2.8.0
2. After login, run the command: `az rest --uri /subscriptions?api-version=2014-04-01`

**Expected behavior**
The API JSON response from the endpoint

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.8.0

Extensions:
application-insights 0.1.6
azure-devops 0.17.0
```

**Additional context**
I verified that this command worked on 2.7.0 prior to upgrading to 2.8.0.

**Comment by yonzhan** [comment]
add to S173

**Comment by lerlacher-haylix** [comment]
Confirming this bug, also noting:

- There does not seem to be a way to downgrade on Ubuntu (I am running 18.04)
- The following commands can be used on Ubuntu 18.04 to install 2.7.0 through pip:

```
python3 -m venv env
. env/bin/activate
pip3 install azure-cli==2.7.0 # if build tolls and dev libraries are not installed, this will show a bunch of wheel build errors, but that is fine to ignore
alias az=env/bin/az
az --version
```

Activating the venv and doing `alias az=env/bin/az` will need to be done in every session.

**Comment by lerlacher-haylix** [comment]
Hi @yonzhan why is this tagged as a feature request? This is a bug.

**Comment by yonzhan** [comment]
@lerlacher-haylix Correct the label and we will take a look.

**Comment by jiasli** [comment]
I can confirm this is a bug introduced by #13782:

https://github.com/Azure/azure-cli/blob/62eb25feac0da927d219321538046faee6882886/src/azure-cli-core/azure/cli/core/util.py#L807-L808

I will fix it as soon as possible.

There is an issue https://github.com/Azure/azure-cli/issues/13653 for allowing installing old versions. Solutions can be found at https://github.com/Azure/azure-cli/issues/13331#issuecomment-635446175.
