### ISSUE TITLE
Many CLI errors when trying to get the consumption os certain subscription...

### ISSUE THREAD

**Issue by eandresr** [Azure/azure-cli#14158]
## Describe the bug

**Command Name**
`az consumption usage list`

**Errors:**
```
'NoneType' object has no attribute 'message'
Traceback (most recent call last):
cli/core/commands/__init__.py, ln 696, in _run_job
    result = transform_op(result)
cli/command_modules/consumption/_transformers.py, ln 20, in transform_usage_list_output
    return [transform_usage_output(item) for item in result]
cli/command_modules/consumption/_transformers.py, ln 20, in <listcomp>
    return [transform_usage_output(item) for item in result]
python3.6/site-packages/msrest/paging.py, ln 143, in __next__
    self.advance_page()
...
azure.mgmt.consumption.models.error_response.ErrorResponseException: Unknown error


cli/command_modules/consumption/_exception_handler.py, ln 12, in consumption_exception_handler
    message = ex.error.error.message
AttributeError: 'NoneType' object has no attribute 'message'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az consumption usage list --start-date {} --end-date {} --subscription {}`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.7.0 *

```

**Comment by yonzhan** [comment]
consumption

**Comment by yungezz** [comment]
#14287

**Comment by absyed** [comment]
This issue was fixed in Pull Request: [14335](https://github.com/Azure/azure-cli/pull/14335)

**Comment by absyed** [comment]
None type errors should be fixed in the Pull Request: 14335

**Comment by absyed** [comment]
@eandresr are you still experiencing this issue?

**Comment by ramaganesan-rg** [comment]
Closing this issue, absyed - please feel free to reopen this issue if you are still experiencing this issue? thank you for the feedback.
