### ISSUE TITLE
[Network] Local-Gateway issues

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#1416]
1. The create commands dont provide the option to set BGP settings. Commands being referenced are
azure network local-gateway create
az network local-gateway create

2. The set command in js has the ability to modify local network address space but the corresponding command in python doesnt.

3. BGP settings should be directly exposed in the modify commands for both js and python, just like what we have in Powershell

**Comment by tjprescott** [comment]
cc/ @aanandr

**Comment by tjprescott** [comment]
Related (but not duplicate) of #818
