### ISSUE TITLE
Webapp:az webapp config container set failed with missing argument

### ISSUE THREAD

**Issue by leehi0418** [Azure/azure-cli#14183]
## Describe the bug

**Command Name**
`az webapp config container set`

**Errors:**
```
az webapp config container set: error: argument --docker-registry-server-password/-p: expected one argument
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config container set --name {} --resource-group {} --docker-custom-image-name {} --docker-registry-server-url {} --docker-registry-server-uaz {} {} {} {} --name {} --resource-group {} --docker-custom-image-name {} --docker-registry-server-url {} --docker-registry-server-user {} --docker-registry-server-password {} {} --docker-registry-server-password`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1 *

```

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by btardif** [comment]
hey @seligj95 can you see if this still repros

**Comment by seligj95** [comment]
unable to reproduce, please upgrade to the latest cli version
