### ISSUE TITLE
Mac: After cli update with Homebrew all az commands fail: Abort trap: 6

### ISSUE THREAD

**Issue by samson-ite** [Azure/azure-cli#14189]
The issue started after I updated the azure-cli via Homebrew. Any 'az' command throws the following error. I know there is a closed issue where there was a suggestion to remove python and azure-cli and re-install. This did not work for me. 

I have tried pointing the /usr/local/Cellar/azure-cli/2.8.0/bin/   python symbolic links to an older version of python (3.7.7) with the azure.cli modules installed, and I received a similar error with just the "Abort trap: 6" and no other information unlike the error below.

$ az feedback
/usr/local/bin/az: line 2: 20120 Abort trap: 6           AZ_INSTALLER=HOMEBREW /usr/local/Cellar/azure-cli/2.8.0/libexec/bin/python -m azure.cli "$@"

**To Reproduce**
run any 'az' command from the command line

**Expected behavior**

**Environment summary**
MacOS Catalina Version 10.15.5
az version 2.8.0
$ python --version  -> 3.7.7
$ python3 --version -> 3.8.3
$ pip --version -> pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
$ pip3 --version -> pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.8)

installed via HomeBrew
$ brew install python
$ brew install azure-cli

**Additional context**
This only started yesterday after updating the azure-cli with brew.

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look? thanks

**Comment by samson-ite** [comment]
I finally got it to work.

I uninstalled python/azure-cli with Homebrew
removed all python packages (3.x & 2.x) from my machine as well as pip/pip3
ran 'brew install azure-cli' and it worked.
It looks like there was some weird linking or PATH conflicts going on and removing python completely fixed the issue.
