### ISSUE TITLE
[Databricks] support double encryption

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#14186]
**Resource Provider**

Databricks 

**Description of Feature or Work Requested**

Support double encryption. [Double Encryption Design Doc ](https://nam06.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Aw%3A%2Ft%2FAzureDataBricks-EnggTeam%2FEQDPA6ikywxOvOUuTK1HzeQBqcVakAg5yOqzYE0Z3_4ntw%3Fe%3Dt9LiHB&data=02%7C01%7Cyungez%40microsoft.com%7C68e8b2f79741434dcd0d08d8180c021d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637285787139213907&sdata=c7ZMJqL4oKELk%2BJZihAy6XC62WERG40MBLMYdTonVA8%3D&reserved=0)

**Minimum API Version Required**

**Swagger Link**

**Target Date**

service release is completed to all regions by 7/24. Expected Azure CLI release date 8/4

**Comment by yungezz** [comment]
put in S174 for now since serivce not ready yet.

**Comment by fengzhou-msft** [comment]
via https://github.com/Azure/azure-cli-extensions/pull/2113
