### ISSUE TITLE
Cosmosdb collection create command should support partition key version field

### ISSUE THREAD

**Issue by andscho-msft** [Azure/azure-cli#14191]
**Is your feature request related to a problem? Please describe.**

Cannot set cosmosdb collection partition key version from CLI

**Describe the solution you'd like**

The Cosmosdb collection partition key settings have a version field detailed here:
https://docs.microsoft.com/en-us/azure/cosmos-db/large-partition-keys?tabs=dotnetv3#supported-sdk-versions

Seems like that field is already in the auto-generated model:
https://azuresdkdocs.blob.core.windows.net/$web/python/azure-mgmt-cosmosdb/0.12.0/azure.mgmt.cosmosdb.models.html#azure.mgmt.cosmosdb.models.ContainerPartitionKey

Would like to have a new optional command parameter to collection create that would populate it here:
https://github.com/Azure/azure-cli/blob/de73fb57e824104bdf18adf443d574e9b4c88fec/src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py#L270

**Describe alternatives you've considered**
Using an ARM template manually via `az group deployment create`
Monkey-patching ContainerPartitionKey

**Additional context**

**Comment by MehaKaushik** [comment]
Made changes in https://github.com/Azure/azure-cli/pull/13985 to address this issue.
