### ISSUE TITLE
connectors to applications 'azureeventgrid' is not compatible with the Gmail

### ISSUE THREAD

**Issue by BassamBallaji** [Azure/azure-cli#14193]
As part of microsoft integration service. I'm using an azure logic app that should send message to my GMAIL address each time an event is happening in a VM under a specified resource group.

Scenario applied is :

create RG + VM

create blank logic app

add event grid trigger

add condition ......

send email notificiations

(as of the link : https://docs.microsoft.com/en-us/azure/event-grid/monitor-virtual-machine-changes-event-grid-logic-app#:%7E:text=Sign%20in%20to%20the%20Azure,%27re%20done%2C%20select%20Create. )

But Logic app designer denied to save as I receive the following message :

`Failedto save logic app XXXXla01. The operation on workflow 'XXXXla01' cannot be completed because it contains connectors to applications 'azureeventgrid' which are not compatible with the Gmail connector.` 

When workraround, I find this https://docs.microsoft.com/en-us/azure/connectors/connectors-google-data-security-privacy-policy that stated some google policies update.

I'm looking now for an alternative to this issue, where I can still use an azure resource that send notifications to my GMAIL address everytime an event is happening to my VM.

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by ahamad-MS** [comment]
Investigating this issue and will update the thread with findings.

**Comment by ahamad-MS** [comment]
This is related to Logic App itself. Trying to find the appropriate owner from Logic App team

**Comment by navba-MSFT** [comment]
@BassamBallaji Apologies for the late reply. The same issue has been discussed [here](https://docs.microsoft.com/en-us/answers/questions/42264/connectors-to-applications-azureeventgrid-is-not-c.html). Please check if the suggestion provided there helps in your scenario. Also this issue is open for quite sometime. Please let me know if you need any further assistance on this. Awaiting your reply.
