### ISSUE TITLE
Global parameters link is inadequate

### ISSUE THREAD

**Issue by BruceHaley** [Azure/azure-cli#14192]
The link to Global parameters on this page simply lists them without giving any details.
This link should go to the Global parameters page that shows full syntax for each. Right now we have to search for that page.

**Comment by yungezz** [comment]
hi @arrownj could you pls see what's in today's doc. and how to align the exprience on global params as command params,  configuration items and local context etc. thanks.

**Comment by arrownj** [comment]
Hi @BruceHaley , could you please also share us what exactly `The link` and `this page` is ?
