### ISSUE TITLE
Error when using JMESPATH with the keyword SELECT

### ISSUE THREAD

**Issue by Nepomuceno** [Azure/azure-cli#14219]
## Describe the bug

**Command Name**
`az policy definition list`

**Errors:**
```
Unknown function: select()
Traceback (most recent call last):
python3.6/site-packages/jmespath/functions.py, ln 74, in call_function
    spec = self.FUNCTION_TABLE[function_name]
KeyError: 'select'

...

python3.6/site-packages/jmespath/functions.py, ln 77, in call_function
    "Unknown function: %s()" % function_name)
jmespath.exceptions.UnknownFunctionError: Unknown function: select()
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az policy definition list --query 'select(policyType == "Custom")'`

## Expected Behavior

List the custom policy definitions

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

```

**Comment by yonzhan** [comment]
add to S173

**Comment by zhoxing-ms** [comment]
@Nepomuceno Sorry, I can't find the usage of `select( ... )` in the official tutorial, tutorial link: https://jmespath.org/tutorial.html
May I ask could you follow the common `JMESPATH` syntax? Such as `az policy definition list --query "[?policyType == 'Custom']"`.

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
