### ISSUE TITLE
az rest - Retrieving Functions keys results in InternalServerError

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-cli#14220]
## Describe the bug
We have a script which currently calls the HTTP endpoint to retrieve the Function Keys from a newly created FunctionApp to place into Key Vault. The HTTP call seems to fail with an InternalServerError. If we wait long enough, this then succeeds. We suspect this might be some timing issue related to how the FunctionApp gets created from ARM templates or if there is a period of time the newly created resource cannot be queried?

**Command Name**
`az rest`

**Errors:**
```
Bad Request({"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (InternalServerError) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime."}}],"Innererror":null})
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az rest --method {} --uri {}`

```
az rest --method post --uri "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Web/sites/{functionAppName}/host/default/listKeys?api-version=2018-11-01"
```

## Expected Behavior
HTTP call to always succeed

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1 *

Extensions:
interactive 0.4.3

```

**Comment by yonzhan** [comment]
add to S173

**Comment by jiasli** [comment]
`az rest` currently doesn't support support polling [asynchronous Azure operations](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/async-operations) (tracked at https://github.com/Azure/azure-cli/issues/14223). The script is responsible for querying the provisioning status of the prerequisite resources. 

An example can be found from the scenario test:

https://github.com/Azure/azure-cli/blob/5dca36acfa2b95e7870f7ab0df77f89887c07407/src/azure-cli/azure/cli/command_modules/util/tests/latest/test_rest.py#L25-L32

**Comment by wahyuen** [comment]
@jiasli What operation are we supposed to inspect for the 'async' scenario? We provision the function app via a previous Azure DevOps task via ARM templates. Would this not imply that the resource already exists at this point?

We are following the recommendation from https://github.com/Azure/azure-cli/issues/4041#issuecomment-603894815

**Comment by jiasli** [comment]
`az rest` simply makes the REST call and doesn't care about the business logic. 

Could you create a **support ticket** to **Function Ap**p team to investigate? You may provide the `--debug` log of `az rest` (containing the raw HTTP request and response). A support engineer can help you identity the issue from service-side. Thanks for understanding.
