### ISSUE TITLE
Adding a CDN profile rule that modifies a response header fails

### ISSUE THREAD

**Issue by alessandromuresan** [Azure/azure-cli#14238]
**Describe the bug**
Trying to add a CDN profile rule that modifies a response header fails with `validation error: Parameter 'DeliveryRuleAction.name' can not be None`

**To Reproduce**
Run the command below. You will need to create a resource group, cdn profile and cdn endpoint beforehand.
```
az cdn endpoint rule add --name cdn-endpoint-name --profile-name cdn-profile-name --resource-group resource-group-name --order 1 --rule-name cors1 --match-variable RequestHeader --selector Origin --match-values https://mydomain.com --operator Equal --transform Lowercase --action-name ModifyResponseHeader --header-action Overwrite --header-name "Access-Control-Allow-Origin" --header-value https://mydomain.com
```

**Expected behavior**
Should create a new rule

**Environment summary**
MSI on Windows (running the command from PowerShell)

**Comment by yonzhan** [comment]
CDN

**Comment by hytao** [comment]
Expected Action name should be "ResponseHeader".

**Comment by hytao** [comment]
Please close the ticket

**Comment by timMSFT** [comment]
Expected Action name should be "ResponseHeader".
