### ISSUE TITLE
expired token. need help.

### ISSUE THREAD

**Issue by pranotipr** [Azure/azure-cli#14244]
Error:  Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2020-02-26T21:52:54.2810613Z and was inactive for 90.00:00:00.\r\nTrace ID: 6e94ade5-10de-4d67-909a-14d845813500\r\nCorrelation ID: 0e87b495-1e24-4882-be85-d012c216f4f6\r\nTimestamp: 2020-07-06 22:31:52Z","error_codes":[700082],"timestamp":"2020-07-06 22:31:52Z","trace_id":"6e94ade5-10de-4d67-909a-14d845813500","correlation_id":"0e87b495-1e24-4882-be85-d012c216f4f6","error_uri":"https://login.microsoftonline.com/error?code=700082"}

**Comment by yonzhan** [comment]
@pranotipr please share more detailed info, such as in which scenario you met with this error.

**Comment by yungezz** [comment]
hi @pranotipr are you met the issue via `az  get-access-token`? could you try `az login`?

**Comment by pranotipr** [comment]
Thanks. This has been resolved.
