### ISSUE TITLE
Failure to install CLI on Linux machines

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#14246]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
New users having trouble installing CLI on Linux

**To Reproduce**
refer to video link

**Expected behavior**
Users being able to install CLI without issues

**Environment summary**

(no info on this, perhaps data could tell us more)

**Additional context**

**Comment by yungezz** [comment]
will try to get detail from the video, so far no permission yet.

**Comment by yungezz** [comment]
hi @chenlomis as synced in email, the installation failed at `apt-get update` due to 3rd party repository. It's not Azure CLI issue. Will close the issue for now. feel free to create new issue if any other issue. thanks.
