### ISSUE TITLE
Could not create a role assignment for ACR within the subscription where I am an Owner

### ISSUE THREAD

**Issue by dimanngo** [Azure/azure-cli#14259]
## Describe the bug

**Command Name**
`az aks update`

**Errors:**
```
Could not create a role assignment for ACR. Are you an Owner on this subscription?
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update -g {} -n {} --attach-acr {}`

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

```

**Comment by yonzhan** [comment]
aks

**Comment by dimanngo** [comment]
I tried today -- there is no error. So, was it a problem with the service or something else I don't know.
