### ISSUE TITLE
az aks update --attach-acr throws python exception

### ISSUE THREAD

**Issue by rouke-broersma** [Azure/azure-cli#14257]
## Describe the bug

**Command Name**
`az aks update --attach-acr <acr-resource-id>`

**Errors:**
```
'name'
Traceback (most recent call last):
Temp\pip-install-_1mlo87m\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 625, in execute
azure\cli\core\commands\__init__.py, ln 689, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 682, in _run_job
Local\Temp\pip-install-_1mlo87m\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 659, in _run_job
azure\cli\core\commands\__init__.py, ln 324, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 531, in default_command_handler
azure\cli\command_modules\acs\custom.py, ln 2159, in aks_update
azure\cli\command_modules\acs\custom.py, ln 2739, in _ensure_aks_acr
KeyError: 'name'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- create acr (in different subscription but same tenant, not sure if relecant)
- `az login --tenant <tenant.onmicrosoft.com>`
- `az account set --subscription <aks subscription>`
- `az aks update -n {} -g {} --attach-acr {}`

## Expected Behavior

ACR is attached OR an error is shown telling me what I did wrong

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.8.0

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
aks

**Comment by navba-MSFT** [comment]
@rouke-broersma Apologies for the late reply. Could you please use the most [recent version ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)of the CLI and let us know if you are still facing this issue ? Awaiting your reply.

**Comment by rouke-broersma** [comment]
Hi @navba-MSFT,

We now simply grant the managed identity the correct permissions on the container registry using Bicep, so we no longer use this az-cli command. I won't be reproducing this again, apologies. You may close this issue if you wish, I no longer have a need for this functionality.

**Comment by navba-MSFT** [comment]
@rouke-broersma Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
