### ISSUE TITLE
Can we enable API version isolation among modules?

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#14252]
**Is your feature request related to a problem? Please describe.**

It is a disaster when upgrading API version, especially Ring 0 service for it is used everywhere. If each module has its own API version configuration, it will be easier to upgrade API version.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
![image](https://user-images.githubusercontent.com/54048360/86741039-ad4fab00-c069-11ea-8074-46729efc7399.png)

**Comment by qwordy** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/54048360/86741039-ad4fab00-c069-11ea-8074-46729efc7399.png)

It's a screenshot..

**Comment by yonzhan** [comment]
similar to #14102
