### ISSUE TITLE
vm create error in docker when --admin-username not provided

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-cli#14265]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When `--admin-username` is not provided in `az vm create`, the default is to get the current user. 
https://github.com/Azure/azure-cli/blob/b361d116a82c725d9a3322e3a8683376ebf6b785/src/azure-cli-core/azure/cli/core/util.py#L597-L601
When running in Docker, the default user is `root` and can not pass the validator check:
https://github.com/Azure/azure-cli/blob/b361d116a82c725d9a3322e3a8683376ebf6b785/src/azure-cli/azure/cli/command_modules/vm/_validators.py#L1009-L1017

**To Reproduce**

```
>docker run -it --rm mcr.microsoft.com/azure-cli
bash-5.0# az login
bash-5.0# az vm create -g feng-cli-rg -n myvm --image UbuntuLTS --generate-ssh-keys
This user name 'root' meets the general requirements, but is specifically disallowed for this image. Please try a different value.
```

**Expected behavior**

Probably add check of `disallowed_user_names` list in `get_default_admin_username`, either make up a valid username to return or throw an error message to tell users the default username is invalid and they need to provide a valid username with `--admin-username`.
**Environment summary**

Docker
**Additional context**

**Comment by yungezz** [comment]
@qwordy could you pls help to look at it

**Comment by qwordy** [comment]
OK. I will take over this issue.
