### ISSUE TITLE
az backup protection disable throwing traceback when no item name is found

### ISSUE THREAD

**Issue by asnogordo** [Azure/azure-cli#14261]
## Describe the bug

**Command Name**
`az backup protection disable`

**Errors:**
```
Item not found. Please provide a valid item_name.
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/command_modules/backup/custom_help.py, ln 104, in validate_item
    validate_object(item, "Item not found. Please provide a valid item_name.")
cli/command_modules/backup/custom_help.py, ln 113, in validate_object
    raise ValueError(error_message)
ValueError: Item not found. Please provide a valid item_name.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup protection disable --container-name {} --delete-backup-data {} --item-name {} --resource-group {} --vault-name {} --yes --backup-management-type {}`

## Environment Summary
```
Linux-4.15.0-108-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

Extensions:
interactive 0.4.3

```
## Additional Context
I am trying to disassociate a VM with a vault.

Before I ran the az backup production disable command that errors out, I ran this list command:

epicadm@vm-dhernand:~/.ssh/config.d$ az backup item show --container-name mock-prd01 --name mock-prd01 -g mock-production -v mock-production-recovery-vault -
-backup-management-type AzureIaasVM
Command group 'backup' is in preview. It may be changed/removed in a future release.
{
  "eTag": null,
  "id": "/Subscriptions/**OMIT**/resourceGroups/mock-production/providers/Microsoft.RecoveryServices/vaults/mock-production-recov
ery-vault/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;mock-production;mock-prd01/protectedItems/VM;iaasvmcontainerv2;mock-prod
uction;mock-prd01",
  "location": null,
  "name": "VM;iaasvmcontainerv2;mock-production;mock-prd01",
  "properties": {
    "backupManagementType": "AzureIaasVM",
    "backupSetName": null,
    "containerName": "iaasvmcontainerv2;mock-production;mock-prd01",
    "createMode": null,
    "deferredDeleteTimeInUtc": "2020-07-06T23:06:25.762182+00:00",
    "deferredDeleteTimeRemaining": "13.00:20:43.7395011",
    "extendedInfo": null,
    "extendedProperties": null,
    "friendlyName": "mock-prd01",
    "healthDetails": [
      {
        "code": 400239,
        "message": "Backup pre-check status of this virtual machine is OK.",
        "recommendations": [],
        "title": "IaasVmHealthGreenDefault"
      }
    ],
    "healthStatus": "Passed",
    "isDeferredDeleteScheduleUpcoming": null,
    "isRehydrate": null,
    "isScheduledForDeferredDelete": true,
    "lastBackupStatus": "Completed",
    "lastBackupTime": "2020-07-06T02:59:01.299992+00:00",
    "lastRecoveryPoint": "2020-07-06T02:59:05.826498+00:00",
    "policyId": "",
    "policyName": "",
    "protectedItemDataId": "932966403515390900",
    "protectedItemType": "Microsoft.Compute/virtualMachines",
    "protectionState": "ProtectionStopped",
    "protectionStatus": "Healthy",
    "sourceResourceId": "/subscriptions/**OMIT**/resourceGroups/mock-production/providers/Microsoft.Compute/virtualMachines/mock-
prd01",
    "virtualMachineId": "/subscriptions/**OMIT**/resourceGroups/mock-production/providers/Microsoft.Compute/virtualMachines/mock-
prd01",
    "workloadType": "VM"
  },
  "resourceGroup": "mock-production",
  "tags": null,
  "type": "Microsoft.RecoveryServices/vaults/backupFabrics/protectionContainers/protectedItems"
}

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by pvrk** [comment]
@asnogordo : Thanks for reaching out. So, if I understand this right, you verified the parameters using az backup item show and provided the same parameter to the disable command and it failed. Is my understanding right?

If yes, I can see that the item current state is already protection stopped and it is scheduled to be purged permanently on (July 6th + 14 days). So, in effect, the item is no longer available for any further deletion. So, IMO, the output is right. May I know your final requirement?

**Comment by asnogordo** [comment]
@pvrk Thank you. I would like to setup a new backup item for this mock-production VM. For simplicity, let's just say I want to associate it with a different vault in the same RG. Do I have to wait for this cool down period to finish before being able to do that? Here's the output I see what I try to do that:

```bash
epicadm@vm-dhernand:~/.ssh/config.d$ az backup protection enable-for-vm --resource-group mock-production --vault-name mock-production-backup-vault --vm mock-prd01 --policy-name Weekly-Backups --disk-list-setting include --diskslist 0 1 2 3
Command group 'backup' is in preview. It may be changed/removed in a future release.

            The specified Azure Virtual Machine Not Found. Possible causes are
               1. VM does not exist
               2. The VM name or the Service name needs to be case sensitive
               3. VM is already Protected with same or other Vault.
                  Please Unprotect VM first and then try to protect it again.

            Please contact Microsoft for further assistance.

```

**Comment by pvrk** [comment]
@asnogordo : Ah yes. You have to wait for the cool down to move VMs from one vault to another. If this is something you want, you can let me know and I will treat this as a feature request (move VMs from one vault to another without waiting for cool down). When you want to move, you want earlier backups to be deleted or retained?

**Comment by asnogordo** [comment]
In my particular case I wanted them hard deleted. I appreciate your input and help @pvrk!

**Comment by pvrk** [comment]
@asnogordo : Thanks for the clarity. If you want them hard-deleted, then it means you don't want those backups to be soft-deleted. So, in this case, you might want to think to switch off soft-delete at a vault level. Further instructions to permanently delete already deleted items are mentioned [here](https://docs.microsoft.com/azure/backup/backup-azure-security-feature-cloud#permanently-deleting-soft-deleted-backup-items). Please look at the relevant powershell section.

Please try this and let us know if this works.

**Comment by asnogordo** [comment]
Hi pvrk,
This is likely what I needed at the beginning. The vault has been deleted I believe, but I really appreciate your help and the provided doc for removing the soft-delete feature.

Thank you!
