### ISSUE TITLE
Backup test

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#14270]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Hi, owner of backup, I upgrated Compute API version recently. Some tests are marked record only and can not pass when I rerun them. So I skip them. Please help rerun them.

https://github.com/Azure/azure-cli/pull/14212
{Compute} Bump version disks 2020-05-01, compute 2020-06-01

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Backup

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by pvrk** [comment]
@sambitratha : Can you please look into this or assign somebody else accordingly?

**Comment by sambitratha** [comment]
hi @qwordy  sure i'll take a look.

**Comment by pvrk** [comment]
@sambitratha : So, is the required work done and can we close this?

**Comment by qwordy** [comment]
Thank you so much!
