### ISSUE TITLE
Failing to enable autoprotect for workload-type MSSQL

### ISSUE THREAD

**Issue by nsantin** [Azure/azure-cli#14279]
## Describe the bug

**Command Name**
`az backup protection auto-enable-for-azurewl`

**Errors:**
```
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/backup/custom_base.py, ln 287, in auto_enable_for_azure_wl
    protectable_item)
cli/command_modules/backup/custom_wl.py, ln 402, in auto_enable_for_azure_wl
    item_id = protectable_item_object.id
AttributeError: 'NoneType' object has no attribute 'id'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- This is the command I'm running:
- az backup protection auto-enable-for-azurewl --policy-name "MyPolicyName" --resource-group "MyResourceGroup" --vault-name "MyRSVName"  --protectable-item-name "sqlinstance;mssqlserver" --protectable-item-type SQLInstance --server-name "MyVMName" --workload-type MSSQL

## Expected Behavior
mssqlserver instance for that VM should have all DBs protected under the defined policy as well as future DBs 
It works fine if I enable autoprotection manually from the portal

## Environment Summary
```
I'm running it from the cloud shell in case it would be an issue with my laptop

Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

```

**Comment by yonzhan** [comment]
backup

**Comment by yungezz** [comment]
#14287

**Comment by pvrk** [comment]
@yungezz : Sorry for the delay. Acknowledging this. Can you please check for the protectable item by running az backup protectable item list or az backup protectable item show command?

**Comment by nsantin** [comment]
Hi, Autoprotect is now working

Followed your recommendation for checking the output of *“az backup
protectable-item list” *to identify the values that any *“az backup”* would
expect.

I found that *“server-name”* used in *“az backup protection
auto-enable-for-azurewl” **needs to have the fqdn when joined to a domain*

In other words:



Auto-protection was failing:

az backup protection auto-enable-for-azurewl --policy-name
"SQLServerDatabaseSTD" --resource-group "UE2DINT093RSG01" --vault-name
"UE2DINT093RSV01"  --protectable-item-name "sqlinstance;mssqlserver"
--protectable-item-type SQLInstance *--server-name " UE2DINT093MVM06"*
--workload-type
MSSQL



Auto-protection is now working:

az backup protection auto-enable-for-azurewl --policy-name
"SQLServerDatabaseSTD" --resource-group "UE2DINT093RSG01" --vault-name
"UE2DINT093RSV01"  --protectable-item-name "sqlinstance;mssqlserver"
--protectable-item-type SQLInstance *--server-name
"ue2dint093mvm06.int093.sbp.local"* --workload-type MSSQL

**Comment by pvrk** [comment]
@nsantin : Thanks for confirming. This can be taken as a generic rule (using az backup list and show commands) to make sure all the parameters are correct. Closing this issue since this is solved.
