### ISSUE TITLE
Error 503 has been constant when performing ‘az login’

### ISSUE THREAD

**Issue by mateustanaka** [Azure/azure-cli#14275]
**Describe the bug**
I’m using the Docker image **mcr.microsoft.com/azure-cli:latest** (2.8.0) as base of my image to perform `az login -u <username> -p <password>` inside a Hosted Agent on Azure DevOps to be able to push Images to ACR and get AKS credentials later, this process is executed a lot of times for each microservices we have because we are using Multipliers. Unfortunately I’m facing a lot of failures response 503 almost every day in the last weeks.

```
2020-07-07T23:14:05.1209826Z WS-Trust RST request returned http error: 503 and server response: <!DOCTYPE HTML PUBLIC “-//W3C//DTD HTML 4.01//EN””http://www.w3.org/TR/html4/strict.dtd”>
2020-07-07T23:14:05.1210839Z <HTML><HEAD><TITLE>Service Unavailable</TITLE>
2020-07-07T23:14:05.1211597Z <META HTTP-EQUIV=“Content-Type” Content=“text/html; charset=us-ascii”></HEAD>
2020-07-07T23:14:05.1212047Z <BODY><h2>Service Unavailable</h2>
2020-07-07T23:14:05.1212296Z <hr><p>HTTP Error 503. The service is unavailable.</p>
2020-07-07T23:14:05.1212495Z </BODY></HTML>
```

**To Reproduce**
Create a Docker Image based on mcr.microsoft.com/azure-cli:latest and execute docker run -it inside a Hosted Agent at Azure DevOps, run `az login -u <username> -p <password>` a lot of times.

**Expected behavior**
Login on Azure executed successfully by command line `az login`

**Environment summary**
- Hosted Agent OS = Ubuntu 18.04.4
- Agent version = 2.171.1
- az —version = 2.8.0
- Shell type = bash

**Additional context**
If you need some more informations please let me know.

**Comment by yungezz** [comment]
hi @arrownj could you pls have a look?

**Comment by mateustanaka** [comment]
Today I’m receiving the following error when try to `az login -u username -p password`


```
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host=‘globalsso.xx-xxxxx.com’, port=443): Max retries exceeded with url: /adfs/services/trust/2005/usernamemixed (Caused by NewConnectionError(‘<urllib3.connection.VerifiedHTTPSConnection object at 0x7f232ec5c2e8>: Failed to establish a new connection: [Errno 110] Connection timed out’,))
```

**Comment by mateustanaka** [comment]
I'm not facing this issue anymore. Also I made a change to use Service Principal instead.

**Comment by yungezz** [comment]
thanks @mateustanaka for the update. Will close the issue for now,  pls feel free to create new issue if any other error. thanks.
