### ISSUE TITLE
az webapp create fails when '-r "DOTNETCORE|3.1"' specified

### ISSUE THREAD

**Issue by fyvekatz** [Azure/azure-cli#14281]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
`az webapp list-runtimes`

...
```
"DOTNETCORE|2.1",
"DOTNETCORE|3.1",
```
...

When I specify `"DOTNETCORE|3.1"` in the -r option of `az webapp` create, it fails with:

`Runtime 'dotnetcore|3.1' is not supported. Please invoke 'list-runtimes' to cross check`

This runtime can be specified when creating the webapp via the web UI

**To Reproduce**

`az webapp create -n <webappname> -g <resource_group_name> -l -p <app_service_plan> -r "DOTNETCORE|3.1"`

**Expected behavior**

**Environment summary**

MacOSX
Installed via brew (I think)

**Additional context**

**Comment by panchagnula** [comment]
@fyvekatz thanks for reporting we will take a look. However, just a quick test, have you tried using all lowercase "donetcore|3.1" in the create command and check if that works - we might have a .lower() bug on our end. Thanks.
