### ISSUE TITLE
503 on get token request during az account get-access-token

### ISSUE THREAD

**Issue by Random-Word** [Azure/azure-cli#14285]
Re-running worked, so I definitely had access.

## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 503
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/adal/token_request.py, ln 112, in _oauth_get_token
    return client.get_token(oauth_parameters)
python3.6/site-packages/adal/oauth2_client.py, ln 289, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 503
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az account get-access-token --subscription {} -o {}`

## Expected Behavior
Expected to get an access token, instead received a 503.

## Environment Summary
```
Linux-4.15.0-96-generic-x86_64-with-debian-stretch-sid
Python 3.6.10
Installer: DEB

azure-cli 2.8.0

Extensions:
application-insights 0.1.1

```

**Comment by yonzhan** [comment]
add to S173

**Comment by jiasli** [comment]
This looks like service-side issue. Could you reproduce and capture `--debug` log?

**Comment by Random-Word** [comment]
If I run into it again I'll add the debug flag and reopen this. In the meantime it looks like it was a random service failure. Who manages the service the CLI hits, and where do I file issues with them?

**Comment by jiasli** [comment]
You may capture `--debug` log and then [create a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) to AAD. A support engineer will help you identify the service-side issue.
