### ISSUE TITLE
webapp:'NoneType' object has no attribute 'location' error when missing app service plan - need better error message

### ISSUE THREAD

**Issue by ssemyan** [Azure/azure-cli#14282]
**Describe the bug**
When creating a web app when the app service plan does not exist, you get the message: 

`az webapp create: error: 'NoneType' object has no attribute 'location'`

However, when running with --debug you can see the error is the app service plan is missing:
`msrest.http_logger : {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Web/serverFarms/myplan' under resource group 'mygroup' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}`

We should report the plan is missing so the user knows what is wrong. 

**To Reproduce**
Try to create a web app with a non-existing app service plan:

`az webapp create --deployment-container-image-name hello-world -g mygroup -p nonexisting-plan -n mywebapp`

**Expected behavior**
The user should be told the app service plan specified in the command does not exist instead of telling them "'NoneType' object has no attribute 'location'" which means nothing. 

**Environment summary**
az cli 

az --version
azure-cli                          2.8.0

command-modules-nspkg              2.0.3
core                               2.8.0
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/scott/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Jun 19 2020, 07:14:24)
[GCC 5.4.0 20160609]

**Additional context**
This is the same bug as [#6545](https://github.com/Azure/azure-cli/issues/6545) which was closed without any action because the issue was not addressed as an un-useful error message

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
need check get resource result. @houk-ms

**Comment by yungezz** [comment]
#14287

**Comment by houk-ms** [comment]
@ssemyan Thanks for reporting the issue. It's valid and I reproduced it, where we tries to get a service plan in the validation function while use it without properly checking the result. It will be fixed soon.

@yungezz  This is the typical error we want to fix in #14287.

**Comment by panchagnula** [comment]
@yungezz are you planning to make a fix for all azure-cli services to handle this?

**Comment by houk-ms** [comment]
Will be fixed in #14335

**Comment by yungezz** [comment]
> @yungezz are you planning to make a fix for all azure-cli services to handle this?

hi @panchagnula we'll fix known issues reported now. While it will be great if new code could do NoneType check when developing. We're working on guideline on this.

**Comment by panchagnula** [comment]
@calvinsID  can you check if we can add some useful validation on the client side here for ASP create command?

**Comment by calvinsID** [comment]
@ssemyan Thanks for reporting the issue. This has been fixed with PR #14431, and will be in the upcoming CLI release v2.10.0
