### ISSUE TITLE
command for listing private link group-ids is wrong

### ISSUE THREAD

**Issue by KaiWalter** [Azure/azure-cli#14293]
In the parameter descriptions of --group-id and --group-ids state, that the command `az network private-link-resource list` can be used to obtain a list of group ids.

When running the command I get

```
> az network private-link-resource list
usage error: --id / -g -n --type
```

When specifying a resource as requested I just get the specification for this particular resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8911e94f-9496-a68d-50c0-b5d536a375a4
* Version Independent ID: cc37b77b-0fa2-991b-e16b-fcdbbf183853
* Content: [az network private-endpoint](https://docs.microsoft.com/en-us/cli/azure/network/private-endpoint?view=azure-cli-latest#az-network-private-endpoint-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S173

**Comment by MyronFanQiu** [comment]
@KaiWalter  Which resource?

**Comment by KaiWalter** [comment]
@MyronFanQiu I was checking for blob / storage - but in general I would like to have a command or way to see the possible `groupdIds`

**Comment by MyronFanQiu** [comment]
@KaiWalter I believe we have several tests to show group id for storage account. Based on my knowledge, it's just used for some SKU. @Juliehzl Could you help?

**Comment by MyronFanQiu** [comment]
@KaiWalter  If you run the following command ` az network private-link-resource list --id /subscriptions/xxxxxxxxxxxx/resourceGroups/MyRG/providers/Microsoft.Storage/storageAccounts/MySA`, you would find `groupId` field.

**Comment by KaiWalter** [comment]
@MyronFanQiu sure - but only for this particular resource. The section in the article says

> ...You can use "az network private-link-resource list" to obtain the list of group ids.

hence I would expect to obtain a list of all available group ids.

So for me either remove this statement or make it unambiguous.

**Comment by MyronFanQiu** [comment]
@KaiWalter Good suggestion. I would make this help message clearer.

**Comment by KaiWalter** [comment]
@MyronFanQiu maybe it is an option to point to the list of Subresources (which are the groupIds in question) : https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview#private-link-resource

**Comment by MyronFanQiu** [comment]
@KaiWalter I think it's indeed the list of subresources, which has enough information we need. This doc is just a short summary.
