### ISSUE TITLE
Refine experimental tag message

### ISSUE THREAD

**Issue by arrownj** [Azure/azure-cli#14290]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently the `experimental` tag message is:

> Command group 'local-context' is experimental and not covered by customer support. Please use with discretion.

which calls out that customer support is limited and might turn people away from trying it.

PM gives some other suggestions, they are as follows:

> This command group is experimental. Customer support is not available for preview features. We recommend that you back up your work frequently

or

> This command group is experimental and we would love for you to try out the experience and share us your feedback here: aka.ms/cli_feedback

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by arrownj** [comment]
Update `experimental` message in Knack.

**Comment by jiasli** [comment]
[Knack](https://github.com/microsoft/knack) is a general CLI framework. I am not sure if **limiting the error message to Azure CLI** is a good idea.

**Comment by jiasli** [comment]
Will be covered by https://github.com/Azure/azure-cli/pull/15730 and https://github.com/microsoft/knack/pull/223. The experimental message will be made configurable.
