### ISSUE TITLE
servicefabric test

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#14297]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Hi, dear owner of servicefabric, Compute API version is upgraded recently. A test case `test_cluster` can not pass when I rerun them. So I added @unittest.skip. Please help look at test issue.  Thanks!

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by mwesigwaguma** [comment]
closing, this test is no longer in repo, removed by ServiceFabric team
