### ISSUE TITLE
More information on --cmd parameter

### ISSUE THREAD

**Issue by Kylemiller995** [Azure/azure-cli#14298]
It would be useful to have more information regarding the --cmd parameter. From: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-quickstart-task-cli
"The cmd parameter in this example runs the container in its default configuration, but cmd supports additional docker run parameters or even other docker commands."
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0e3f3c-5aed-28b6-1e28-22ff32a8521d
* Version Independent ID: 128e5bc6-e518-bd5a-f511-48e0ed185739
* Content: [az acr task](https://docs.microsoft.com/en-us/cli/azure/acr/task?view=azure-cli-latest#az-acr-task-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by yugangw-msft** [comment]
Bin, please investigate

**Comment by navba-MSFT** [comment]
Refer PR https://github.com/Azure/azure-cli/pull/21303
