### ISSUE TITLE
Update description of what this actually does.

### ISSUE THREAD

**Issue by FilBot3** [Azure/azure-cli#14303]
I have no idea what this does and it's not very well explained in the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbda4d31-92b4-a30e-551b-fd950303e36d
* Version Independent ID: e82ef68d-b83f-dd03-eed7-64a946655a5e
* Content: [az repos policy case-enforcement](https://docs.microsoft.com/en-us/cli/azure/repos/policy/case-enforcement?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/repos/policy/case-enforcement.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/repos/policy/case-enforcement.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S173

**Comment by zhoxing-ms** [comment]
@FilBot3 Hi, this is the repo address related to the `azure-devops` extension: https://github.com/Azure/azure-devops-cli-extension/issues
If you have any problems about this extension, you can give feedback on it~
