### ISSUE TITLE
About "redis-configuration"

### ISSUE THREAD

**Issue by msjunzh** [Azure/azure-cli#14307]
Hi Could you give an example how to set "--redis-configuration"?
And we want to setup "maxmemory-policy" when creating. Is that supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb66426-9b0f-be54-5530-0673e6821f39
* Version Independent ID: 3d89a838-9a95-3cfe-ea58-7d7484e94956
* Content: [az redis](https://docs.microsoft.com/en-us/cli/azure/redis?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/redis/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/redis/_help.py)
* Service: **cache**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by RakeshMohanMSFT** [comment]
Here is a sample JSON format you could use? and yes you could setup "maxmemory-policy" when creating.

```
{
  "aof-backup-enabled": "true",
  "aof-storage-connection-string-0": "primarystorageconnectionstring",
  "aof-storage-connection-string-1": "secondarystorageconnectionstring",
  "maxclients": "1000",
  "maxfragmentationmemory-reserved": "125",
  "maxmemory-delta": "50",
  "maxmemory-policy": "allkeys-lru",
  "maxmemory-reserved": "130"
}
```
