### ISSUE TITLE
[App Service] Allow setting container info as part of web app creation

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1430]
It would be cool if the `az appservice web create` command allowed providing the necessary arguments to configure the custom Docker container that it should run. That wouldn't just save an extra step (i.e. running the `az appservice web config container` command), but it (arguably) feels a little more intuitive to think of the creation/provisioning process as being a single step.

Something like the following would be really nice:

`az appservice web create -n <NAME> --plan <PLAN> -g <GROUP> -c <CONTAINER_NAME>`.

**Comment by lostintangent** [comment]
As an additional point of discussion, the Azure portal allows specifying a custom container as part of the process of creating a new Linux web app, so it would be ideal if the CLI provided an equivalent experience.

**Comment by yugangw-msft** [comment]
@lostintangent, I will consider your suggestion, once we migrate cli to use newer webapp sdk which contains quite a lot of breaking changes

**Comment by tjprescott** [comment]
It seems like items #1430 and #1369 should be done together. This makes it even more necessary to move to a template based create for web app.

**Comment by yugangw-msft** [comment]
Talked to webapp team, was suggested to hold on a bit for pending design

**Comment by yugangw-msft** [comment]
Moving to later sprint as Linux support is not yet finalized

**Comment by yugangw-msft** [comment]
We do now

**Comment by lostintangent** [comment]
Awesome! Just saw this change in the latest bits. Thanks!
