### ISSUE TITLE
Revert CI job to use released azdev instead of master branch of azure-cli-dev-tool

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#14301]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Using released package is a common practice. For CI jobs, stabilization of the job is important. This issue is to change CI job to use released azdev, revert change https://github.com/Azure/azure-cli/pull/14156/files#diff-a878a38b96673b29ca3248b6ec653537R17

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yungezz** [comment]
HI @haroldrandom could you pls take care of this? cc @yonzhan

**Comment by yonzhan** [comment]
@haroldrandom please use released azdev right now.
