### ISSUE TITLE
Network Application Gateway priavet link support specifying subnet ID while adding and wait command

### ISSUE THREAD

**Issue by haroldrandom** [Azure/azure-cli#14311]
**Is your feature request related to a problem? Please describe.**
As follow up of #14185 , private link should follow the Azure CLI command guide line to support wait command and --no-wait feature.
Also, as https://github.com/Azure/azure-cli/pull/14185#discussion_r451967842 mentioned, it would be better to support subnet ID while adding a new subnet.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
add to S173
