### ISSUE TITLE
Webapp:`az webapp list` argument of type 'NoneType' is not iterable for only one subscription

### ISSUE THREAD

**Issue by kaletkamk** [Azure/azure-cli#14319]
## Describe the bug
When running against one of our subscriptions below error appears, it was working fine for the last two weeks.
Error was confirmed on multiple workstations.
Subscription contains around 180 webapps.

az account set -s {subscription}
az webapp list

az webapp list --subscription {subscription}

**Command Name**
`az webapp list`

**Errors:**
```
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
Temp\pip-install-7cl6xofh\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 631, in execute
azure\cli\core\commands\__init__.py, ln 695, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 688, in _run_job
Local\Temp\pip-install-7cl6xofh\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 665, in _run_job
azure\cli\core\commands\__init__.py, ln 324, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 574, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 641, in list_webapp
azure\cli\command_modules\appservice\custom.py, ln 641, in <listcomp>
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az account set -s {subscription}`
- `az webapp list`

## Expected Behavior
Get json list of webapps
## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1 *

Extensions:
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@kaletkamk can you try if you see the same error when you run the command as
az webapp list --subscription ?

**Comment by kaletkamk** [comment]
> @kaletkamk can you try if you see the same error when you run the command as
> az webapp list --subscription ?

Yes, as per my original report, the command
`az webapp list --subscription`
returns the same error.

**Comment by panchagnula** [comment]
Got it

> > @kaletkamk can you try if you see the same error when you run the command as
> > az webapp list --subscription ?
> 
> Yes, as per my original report, the command
> `az webapp list --subscription`
> returns the same error.

Got it. could you try one more thing please - what is the default subscription set on CLI when you run az account show , does this subscription match the sub you are trying to query on? Also, if possible can you run the command with --debug flag & share the details - feel free to remove an PII info. Thanks again

**Comment by calvinsID** [comment]
@kaletkamk Can you please try using the latest version of CLI to see if this problem persists? I was unable to repro

**Comment by kaletkamk** [comment]
@calvinsID 
The issue is not persistent. It happens randomly.

**Comment by panchagnula** [comment]
Closing this to be tracked with the uber error handling bug linked above
