### ISSUE TITLE
Deploying Application Insights Template fails on WorkspaceResourceId when trying to update properties

### ISSUE THREAD

**Issue by cathymarkle** [Azure/azure-cli#14320]
**Describe the bug**
I am trying to update the Application Insights template using the Azure portal to include the DisableIpMasking property.  I am following the instructions for updating in the portal that I found here:  https://docs.microsoft.com/en-us/azure/azure-monitor/app/ip-collection.  One of the parameters being requested is the WorkspaceResourceId.  I do not have OMS set up for this Azure web app.  I have tried setting a random value (resource id for my application insights instance) and I have tried removing the parameter from the template.  In each case, I get a failed deployment with a BadRequest saying the WorkspaceResourceId is not in a valid format. 

**To Reproduce**
Follow the Portal instructions found here:  https://docs.microsoft.com/en-us/azure/azure-monitor/app/ip-collection

**Expected behavior**
The template should deploy Application Insights successfully without requiring a WorkspaceResourceId and should start showing client-ip in the request table.

**Comment by yonzhan** [comment]
This issue is not for Azure CLI, please open issue to Azure Portal.
