### ISSUE TITLE
Command "az bot directline show" throws error 

### ISSUE THREAD

**Issue by yashwant** [Azure/azure-cli#14321]
## Describe the bug

**Command Name**
`az bot directline show`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'HTTPError' object has no attribute 'error'
Traceback (most recent call last):
  File "/Users/yash/lib/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/yash/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
AttributeError: 'HTTPError' object has no attribute 'error'
```

## To Reproduce:

Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

-  create new WebApp bot via Azure portal
- `az login`
- `az bot directline show --name {} --resource-group {} --with-secrets --verbose`

Steps to reproduce the behavior(via REST API). Note that argument values have been redacted, as they may contain sensitive information.

```
curl --location --request POST 'https://management.azure.com/subscriptions/{}/resourceGroups/{}/providers/Microsoft.BotService/botServices/{}/channels/DirectLineChannel/listChannelWithKeys?api-version=2018-07-12' \
--header 'Authorization: Bearer <AccessToken>'

```

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 2.7.15
Shell: bash

azure-cli 2.0.65

```

**Comment by yonzhan** [comment]
bot

**Comment by navba-MSFT** [comment]
@yashwant Apologies for the late reply. Could you please use the most recent version of the Azure CLI from [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and let us know if you are still facing this issue ? Awaiting your reply.
