### ISSUE TITLE
projetoAzul

### ISSUE THREAD

**Issue by profedsonbelem** [Azure/azure-cli#14325]
[Projeto Azul]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a9dc8c24-cda6-8672-8017-b66435eadbb7
* Version Independent ID: a0be523a-ff1f-18ed-0fc4-ba0e0befe4d1
* Content: [az appservice](https://docs.microsoft.com/pt-br/cli/azure/appservice?view=azure-cli-latest#az-appservice-list-locations)
* Content Source: [src/azure-cli/azure/cli/command_modules/appservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/_help.py)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
appservice

**Comment by yungezz** [comment]
hello @profedsonbelem could you pls be more specific about the ask? Thanks. Is it same with https://github.com/Azure/azure-cli/issues/14326?

**Comment by panchagnula** [comment]
Please add details and re-open the issue thanks!
