### ISSUE TITLE
Azure Storage Query Acceleration

### ISSUE THREAD

**Issue by jamesbak** [Azure/azure-cli#14323]
**Resource Provider**
Microsoft.Storage

**Description of Feature or Work Requested**
Add data plane support for Query Acceleration feature (https://docs.microsoft.com/azure/storage/blobs/data-lake-storage-query-acceleration) into CLI.

**Minimum API Version Required**

**Swagger Link**

**Target Date**
8/1/2020

**Comment by yonzhan** [comment]
add to S173
