### ISSUE TITLE
Azure cli command to download the latest report 

### ISSUE THREAD

**Issue by cloudengineers** [Azure/azure-cli#14339]
Hi All, 
Can someone please help me on the below query?
I am running a smoke test on my Azure VM, all the generated smoke test results reports will be saved on the Azure blob storage in the following format:
SmokeTest{{ BUILD_NUMBER }}_{{ ENV }}_{{DATE_TIME}}.html
I always need to download the latest file and send it to team? Is there any az command to download the latest report?
Thank you

**Comment by yonzhan** [comment]
add to S174

**Comment by Juliehzl** [comment]
Hi @cloudengineers, you can consider `az storage blob download` to download it.

**Comment by cloudengineers** [comment]
@ Juliehzl --> i am already using that command, but i need to download only latest report only

**Comment by Juliehzl** [comment]
Hi @cloudengineers, currently there is no such command, but I think you could try to get date information and use in az command. 
```
curday=`date +%Y-%m-%d`
az storage blob download -n {{ BUILD_NUMBER }}{{ ENV }}{$curday}}.html -c test  ....
```
