### ISSUE TITLE
az acr import does not support tag and digest

### ISSUE THREAD

**Issue by yene** [Azure/azure-cli#14337]
**Steps:**
```
az acr import -g ... -n ... --source us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.0@sha256:56633bd00dab33d92ba14c6e709126a762d54a75a6e72437adefeaaca0abb069
```

**Result:**
Invalid value k8s-artifacts-prod/ingress-nginx/controller:v0.34.0@sha256:56633bd00dab33d92ba14c6e709126a762d54a75a6e72437adefeaaca0abb069 for property parameters.Source.SourceImage for resource name acrbobdepsmirror. Kindly refer to the docs: https://aka.ms/acr/import

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
acr

**Comment by toddysm** [comment]
Thanks @yene for reporting this. @yugangw-msft Would you mind taking a look?

**Comment by yugangw-msft** [comment]
@yene, we don't support using both tag and digest, and you can only use one of them. Because we don't see obvious benefit of supporting the format with both, we are closing it. Feel free to let us know if you have scenarios locked
