### ISSUE TITLE
--no-wait (1) CLI always returns 0 even HTTP status code is not 200 (2) CLI should return a "polling object"

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#14332]
**Is your feature request related to a problem? Please describe.**

- The CLI should return a "polling object", a json response which has the operation ID that can be queried for the completion status
- The CLI should return non-zero when the http API returns non-200

This issue is reported by Michael Requa

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Core

**Comment by yungezz** [comment]
What's the current behavior? Is this compute specific?

**Comment by qwordy** [comment]
I am looking at it.
```
def sdk_no_wait(no_wait, func, *args, **kwargs):
    if no_wait:
        kwargs.update({'polling': False})
    return func(*args, **kwargs)
```

**Comment by yungezz** [comment]
seems no feedback from customer on this after clarifying the behavior, will close the issue for now.
