### ISSUE TITLE
adding "Storage" as possible option for --destination-address-prefixes

### ISSUE THREAD

**Issue by aki0061** [Azure/azure-cli#14348]
adding "Storage" as possible option for --destination-address-prefixes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe4941c-7b46-b9fb-1c52-98e68f6354cc
* Version Independent ID: d1bc72fb-ccf9-9645-7b1d-98c91bc75a55
* Content: [az network nsg rule](https://docs.microsoft.com/en-us/cli/azure/network/nsg/rule?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S174

**Comment by MyronFanQiu** [comment]
@aki0061 Thanks for raising this issue. I need some time to check it in detail. I'll keep you posted.

**Comment by MyronFanQiu** [comment]
@aki0061 It seems that we don't do any check for this value and it should support Storage type.

**Comment by MyronFanQiu** [comment]
Which kind of error did you meet?

**Comment by yonzhan** [comment]
@aki0061 any update?

**Comment by MyronFanQiu** [comment]
Close it since this issue should be a false alarm.
