### ISSUE TITLE
[Monitor] az monitor metrics alert create: support metric alert for Application Insights Web Test

### ISSUE THREAD

**Issue by mmyyrroonn** [Azure/azure-cli#14352]
RE: Azure Metric Alerts - Proposed CLI Commands. Item 14

**Comment by yonzhan** [comment]
add to S174

**Comment by jsntcy** [comment]
@mmyyrroonn, could you explain more about your request? 
- Do we need add more argument to the command `az monitor metrics alert create`?
- What's the problem when you use `az monitor metrics alert create` to create metric alert for Application Insights Web Test?

CLI command docs: https://docs.microsoft.com/en-us/cli/azure/monitor/metrics/alert?view=azure-cli-latest#az_monitor_metrics_alert_create

**Comment by jsntcy** [comment]
PowerShell cmdlets: https://github.com/Azure/azure-powershell/pull/11787
