### ISSUE TITLE
[Network] Local-Gateway command outputs inconsistent between Xplat and Az

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#1435]
This needs to be looked into. The JSONs look different. I also noticed that in a simple local-gateway config some fields are missing in one of the JSONs. Will be good to run the commands and check.

**Comment by tjprescott** [comment]
As far as I can tell, the JSON output is the same in both CLIs except that Xplat does not alphabetize the resulting keys. Xplat does not display BGP peering settings by default (which makes sense considering their commands don't support it).

However, the table format in Xplat is superior to what is shown in Az so I will update our table format to match.
