### ISSUE TITLE
Classic SKU not available with Container registry.

### ISSUE THREAD

**Issue by ChiefInnovator** [Azure/azure-cli#14357]
The documentation lists the available SKUs for the Azure Container Registry as ..

accepted values: Basic, Classic, Premium, Standard

Classic is not a SKU of Container Registry as seen by ...

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-skus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
acr

**Comment by yugangw-msft** [comment]
Thanks for reporting this. We will address this in the near future when roll out a new api-version.

Since #11487 was opened to track the same thing, hence I am closing this one.
