### ISSUE TITLE
azdev test --max-retry

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#14355]
**Is your feature request related to a problem? Please describe.**

Add a parameter `--max-retry`.
```
--max-retry    Max retry times on test failure. Default value is 0.
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by haroldrandom** [comment]
Could you put it in Azure/azure-cli-dev-tools repo?

**Comment by yonzhan** [comment]
add to S174

**Comment by qwordy** [comment]
> 
> 
> Could you put it in Azure/azure-cli-dev-tools repo?

OK

**Comment by qwordy** [comment]
https://github.com/Azure/azure-cli-dev-tools/issues/230
