### ISSUE TITLE
AKS nodepool add CLI command

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/azure-cli#14361]
Hi Team,

When running the below command

az aks nodepool add `
    --cluster-name aks-idsemuat1 `
    --name vmseabln2 `
    --resource-group rg-idsemuat-aks `
    --enable-cluster-autoscaler `
    --enable-node-public-ip `
    --kubernetes-version 1.16.10 `
    --min-count 3 `
    --max-count 30 `
    --max-pods 100 `
    --mode System `
    --node-vm-size Standard_B2ms `
    --os-type Linux `
    --node-zones {1,2,3} `
    --vnet-subnet-id '/subscriptions/14ba03f5-b114-49ce-b31c-010dcec4a121/resourceGroups/rg-seab-uattest-vnet/providers/Microsoft.Network/virtualNetworks/testvnet/subnets/akssubnet' `
    --verbose

Its not executing ,.

But if we are running the same command in a single line its working. Not sure why ,I am running azure cli latest version.

Can someone please let know what's the issue.I am running the command from Visual Studio Code. I am able to create a cluster with the same format and all

**Comment by nidiculageorge** [comment]
[Nodepooladd.zip](https://github.com/Azure/azure-cli/files/4920090/Nodepooladd.zip)
 The file is attached

**Comment by nidiculageorge** [comment]
![image](https://user-images.githubusercontent.com/43850474/87453809-ba980700-c620-11ea-8704-7246e3869aa6.png)
I am not getting any errors also

**Comment by yonzhan** [comment]
aks

**Comment by yungezz** [comment]
hi @nidiculageorge which terminal you're using? If you're running in bash, you need add `\` at end of each line to split commands over multiple lines.

For the screencut, seems you're using VSCode powershell terminal, you need add ``` at end of each lien to split commands over lines. Could you pls give it a try? thanks.

**Comment by nidiculageorge** [comment]
@yungezz I had already given a try with the ` character .I was trying with that only

![image](https://user-images.githubusercontent.com/43850474/87502375-0aa5b680-c67f-11ea-9a01-53d90fc54e69.png)

**Comment by yungezz** [comment]
Thanks @nidiculageorge for the i nfo. Could you pls try run it in a standalone powershell terminal? instead of vscode? If it works, then issue is in VSCode extension.

**Comment by nidiculageorge** [comment]
@yungezz 

PS C:\Users\nidicula> az aks nodepool add `
    --cluster-name aks-idsemuat1 `
    --name vmseabln2 `
    --resource-group rg-idsemuat-aks `
    --enable-cluster-autoscaler `
    --enable-node-public-ip `
    --kubernetes-version 1.16.10 `
    --min-count 3 `
    --max-count 30 `
    --max-pods 100 `
    --mode System `
    --node-vm-size Standard_B2ms `
    --os-type Linux `
    --node-zones {1,2,3} `
    --vnet-subnet-id '/subscriptions/14ba03f5-b114-49ce-b31c-010dcec4a121/resourceGroups/rg-seab-uattest-vnet/providers/Microsoft.Network/virtualNetworks/testvnet/subnets/akssubnet' `
    --verbose
az : az aks: 'nodepool' is not in the 'az aks' command group. See 'az aks --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit 
https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
At line:1 char:1
+ az aks nodepool add `
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (az aks: 'nodepo...nsions-overview:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Command ran in 6.982 seconds (init: 0.772, invoke: 6.210)

**Comment by nidiculageorge** [comment]
@yungezz When I ran in a single line

PS C:\Users\nidicula> az aks nodepool add --cluster-name aks-idsemuat1 --name vmseabln2 --resource-group rg-idsemuat-aks --enable-cluster-autoscaler --enable-node-public-ip --kubernetes-version 1.16.10 --min-count 3 --max-count 30 --max-pods 100 --mode System --node-vm-size Standard_B2ms --os-type Linux --node-zones {1,2,3} --vnet-subnet-id '/subscriptions/14ba03f5-b114-49ce-b31c-010dcec4a121/resourceGroups/rg-seab-uattest-vnet/providers/Microsoft.Network/virtualNetworks/testvnet/subnets/akssubnet' --verbose
az : az aks: 'nodepool' is not in the 'az aks' command group. See 'az aks --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit 
https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
At line:1 char:1
+ az aks nodepool add --cluster-name aks-idsemuat1 --name vmseabln2 --r ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (az aks: 'nodepo...nsions-overview:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Command ran in 6.527 seconds (init: 0.656, invoke: 5.871)

**Comment by yungezz** [comment]
thanks @nidiculageorge for the info
- Run the command in single line and in multiple line in Powershell directly got same result. So the problem previously you saw: empty output is in vscode. Could you pls open issue at https://github.com/microsoft/vscode/issues to report it
- For the error met in single line execution `az : az aks: 'nodepool' is not in the 'az aks' command group.` . Could you rurn `az --version` and share the output to help investigate?

Thanks.

**Comment by nidiculageorge** [comment]
![image](https://user-images.githubusercontent.com/43850474/87506559-3b8ae900-c689-11ea-8c9b-530ed8389ea7.png)

@yungezz

**Comment by nidiculageorge** [comment]
@yungezz I have updated the cli and checked saame issue

**Comment by nidiculageorge** [comment]
@yungezz I think i have identified ,if we add node zone its just going to the next line if we remove node  zones its running,

I am running it in a single line.

Is it because of --node-zone {1,2,3}.

**Comment by navba-MSFT** [comment]
@nidiculageorge Apologies for the late reply. The parameter is --zone now. Refer [this](https://docs.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest#az-aks-nodepool-add). This issue is open for quite sometime now. Please let us know if you need any further assistance on this. Awaiting your reply.
