### ISSUE TITLE
[Storage] Refine the logic of selecting blob type in batch-upload command

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1436]
pick blob type for each file to upload.

this is a follow up task for PR #1428

**Comment by edevil** [comment]
I'm trying to use the "upload-batch" command to upload the static content of my web application. 

However, I have the problem of every file ending up with the content-type "application/octet-stream", and in some cases (CSS, for example) the files need to have a specific content-type for browsers to interpret them. It would be nice for "upload-batch" to use the correct content-type for well-known extensions, or at least provide a way to specify the mapping in the command line.

At this time the only solution I see is to issue a separate "upload-batch" command for each extension using the available flags ```--content-type "text/css" --pattern "*.css"```, but this is a bit tedious.

Is this issue related to the problem I described?

**Comment by troydai** [comment]
Hi @edevil, thank you for the feedback. This issue is not related to your problem, however, the issue you faced is very valid. I'll open another issue to track your feedback. Thanks.

**Comment by troydai** [comment]
https://github.com/Azure/azure-cli/issues/1949

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
