### ISSUE TITLE
Update VMO VMSS Support

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#14364]
**Resource Provider**

Microsoft.compute

**Description of Feature or Work Requested**

Update support for VMSS VM Orchestration mode

- Should only support SPG=false
- Enable PPG + VMO support
- Currently requires whitelisting AFEC flag; show warning that old version is deprecated, new version must be whitelisted

**Minimum API Version Required**

2019-12-01
**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-12-01/compute.json

**Target Date**

Ignite Sept 2020

**Comment by yungezz** [comment]
thanks for @fitzgeraldsteele . The ask is tracked.

**Comment by qwordy** [comment]
@fitzgeraldsteele Could you clarify the expected changes in Azure CLI with more details?
Add a validation in VMSS Orchestration Mode that SPG must be false?
Enable `az vmss update` to support updating `ppg` and `spg`?
