### ISSUE TITLE
InvalidTemplate - Deployment template language expression evaluation failed

### ISSUE THREAD

**Issue by gthibaud** [Azure/azure-cli#14373]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When I try to deploy ARM resources, using the `az deployment group create`command, I get an error saying that my template is invalid because an expression is badly formed. However my ARM template file is more than 50,000 lines (it is an extract of an API Management resource, extracted with the azure-api-management-devops-resource-kit extractor, and the alert don't gives the lines where the expression evaluation failed.

**To Reproduce**
When I run:
`az deployment group create -g s-DataPlatform-STAG --template-file /Users/gregoirethibaud/master-apis.template.json  --parameters /Users/gregoirethibaud/master-parameters.json`
I get:
`InvalidTemplate - Deployment template language expression evaluation failed: 'Unable to parse language expression ' ': expected token 'Identifier' and actual 'EndOfData'.'. Please see https://aka.ms/arm-template-expressions for usage details.`

**Expected behavior**
I would like to know the line on which the template evaluation failed, my template file is too big for me to debug it entirely. In this situation, `az deployment group create` command is unusable.

**Environment summary**
MacOS 10.15.5, default Terminal app, az-cli 2.8.0.
**Additional context**
Thank you for your help!

**Comment by yonzhan** [comment]
add to S174

**Comment by zhoxing-ms** [comment]
@gthibaud Hi, could you please show me the specific ARM template and parameters you used? And please add --debug to the original command and email the printed information to me~
My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
