### ISSUE TITLE
--slot : command not found in az webapp deployment source config-zip

### ISSUE THREAD

**Issue by rnkhouse** [Azure/azure-cli#14378]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I am trying to run `az webapp deployment source config-zip` with `--slot` param but it's giving me `--slot: command not found error`

**To Reproduce**
Install latest `az cli`. I also have webapp extension installed. Run webapp deployment command with `config-zip` and provide `slot` param.

**Expected behavior**
It should deploy the app in defined slot.

**Environment summary**
    {
       "azure-cli": "2.5.1",
       "azure-cli-command-modules-nspkg": "2.0.3",
       "azure-cli-core": "2.5.1",
       "azure-cli-nspkg": "3.0.4",
       "azure-cli-telemetry": "1.0.4",
       "extensions": {
         "webapp": "0.2.24"
        }
    }

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
cc @fengzhou-msft for awareness
