### ISSUE TITLE
--set needs examples

### ISSUE THREAD

**Issue by pskelley55** [Azure/azure-cli#14377]
In Windows - PowerShell
In Linux - pwsh

Please provide CLI examples using "--set" for both Windows and Linux platforms. They're DIFFERENT!
I spent hours just discovering on the Windows side that you MUST have a SPACE between "k2":  and "v1" !!!
Sheesh!
I NEVER figured out Linux version of CLI !!!
HELP!!!

Windows:
az iot hub device-twin update --hub-name test --device-id 000680015ba1 --set properties.desired={"k1":{"k2": "v1", "k3": "value 2"}}

Linux:
az iot hub device-twin update --hub-name test --device-id 000680015ba1 --set properties.desired={"k1":{"k2": "v1", "k3": "value 2"}}

<<< LINUX snip >>>
PS /home/debuguser/s0-test> az iot hub device-twin update --hub-name sznacaiottest --device-id 000680015ba1 --set properties.desired={"k1":{"k2":"v1"}}
ParserError:
Line |
   1 |  … test --device-id 000680015ba1 --set properties.desired={"k1":{"k2":"v …
     |                                                                ~
     | Unexpected token ':' in expression or statement.

PS /home/debuguser/s0-test> az iot hub device-twin update --hub-name sznacaiottest --device-id 000680015ba1 --set properties.desired={\"k1\":{\"k2\":\"v1\"}}
az iot hub device-twin update: 'utputformat' is not a valid value for '--output'. See 'az iot hub device-twin update --help'.
PS /home/debuguser/s0-test>
<<< snip-end >>>
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9afeaa5c-1af2-8fcc-69b4-15ae81a0d342
* Version Independent ID: dea97474-170e-f678-f812-a1e4cdf56c76
* Content: [az iot hub](https://docs.microsoft.com/en-us/cli/azure/iot/hub?view=azure-cli-latest#az-iot-hub-update)
* Content Source: [src/azure-cli/azure/cli/command_modules/iot/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/iot/_help.py)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
iot hub

**Comment by yiyiguo** [comment]
@Azure/azure-iot-cli-triage

**Comment by digimaun** [comment]
Sorry you've run into issues with the input format using update, we fully acknowledge your feedback.

Actually usage of `--set` for `az iot hub device-twin update` is now deprecated. You will want to use the `--desired` or `--tags` arguments. There are some examples available in the [IoT extension reference](https://docs.microsoft.com/en-us/cli/azure/ext/azure-iot/iot/hub/device-twin?view=azure-cli-latest#ext_azure_iot_az_iot_hub_device_twin_update-examples) but they are bash examples.

For powershell you will want to do something like this (taking one of the existing bash examples):

`az iot hub device-twin update -n {iothub_name} -d {device_id} --desired "{\"conditions\":{\"temperature\":{\"warning\":70, \"critical\":100}}}"`

Here is a guide that explains input differences (particularly when JSON is involved) https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively?view=azure-cli-latest#quoting-issues

In an upcoming release we will add more examples for different environments.
