### ISSUE TITLE
az vm access set-linux-user --password makes insecure changes the SSHD configuration

### ISSUE THREAD

**Issue by vlivech** [Azure/azure-cli#1437]
CLI Version: 0.1.0b9
OS Type: Mac
Installation via:  pip

Environment: AzureCloud

Description:
Using `az access set-linux-user --password`  to reset a Linux users password, makes insecure changes to the SSH servers configuration `/etc/ssh/sshd_config` and allows password logins by changing the value of `PasswordAuthentication` to `yes`.

Steps to reproduce:
1) deploy Linux VM using SSH keys for authentication `--ssh-key-value ~/.ssh/id_rsa.pub \` with a user called `ahmet`
2) login to the Linux VM and verify the setting for `PasswordAuthentication` in `/etc/ssh/sshd_config` is `no`
3) from the `azure-cli` reset user Ahmets password - `az vm access set-linux-user -u ahmet -p bmwbmwbmw`
4) login to the Linux VM and verify the settings for `PasswordAuthentication` in `/etc/ssh/sshd_config` is *now* `yes`

Expected Behavior:

Resetting a users password with vm access-extensions should _only_ change that users password.  

`az vm access` would not make any system wide security changes

Current Behavior:

Using `az vm access set-linux-user` to make changes to a Linux user, makes an insecure change on the entire Linux VM by opening up SSH to password brute forcing attempts by allowing passwords for SSH logins.  All unknown to the admin of the Linux VM.

Error stack trace:
no error logs

node-cli bug filed: https://github.com/Azure/azure-xplat-cli/issues/3335

**Comment by squillace** [comment]
@amarzavery add whomever you see fit. This and it's node counterpart must be investigated promptly. It is not appropriate to make any undocumented changes to a daemon configured by the user in a particular way. If we do make changes for some reason, we must both document them and undo them before we're done with the machine. SSHD must be left in the same state.

**Comment by yugangw-msft** [comment]
I will update cli to use `1.4.6` version which has this fixed

**Comment by yugangw-msft** [comment]
Like we exchanged in the mail, for VM w/o 'VMAccessForLinux' extension, `az vm access` will pick up the latest 1.4.6 which contains the fix. If you have old VM, the extension might be at lower version, which you can use `az vm extension delete & set` to reinstall.
So far, i don't think there is actionable work at cli side. Let me know otherwise

**Comment by amarzavery** [comment]
@yugangw-msft - Do we need to do anything about this in the node based xplat cli?

**Comment by yugangw-msft** [comment]
Double check it installs the version of `1.4`, and doesn't explicitly set `auto_upgrade_minor_version` to false

**Comment by amarzavery** [comment]
Thanks Yugang. @balajikris - since I would be OOF next week, can you please check the above requirement and make changes if necessary in xplat cli.

**Comment by yugangw-msft** [comment]
like I commented, no actionable item in CLI 2.0
