### ISSUE TITLE
need ability to reset Linux SSH config on pycli

### ISSUE THREAD

**Issue by vlivech** [Azure/azure-cli#1438]
CLI Version: 0.1.0b9
OS Type: Mac
Installation via: pip

Environment: AzureCloud

Description:

There is no way to reset the `/etc/ssh/sshd_config` back to the version the Linux VM was deployed with using the pycli.  If a breaking change is made to `/etc/ssh/sshd_config` and the user is locked out from using SSH, the VM extensions need to be used to reset the SSH config.

Expected Behavior:

Azure VM extensions will be able to reset the `/etc/ssh/sshd_config` file back to its state it was originally deployed with.

Actual Behavior:

The pycli does not have this feature.  The user must use the node-cli to reset SSH.

node-cli counterpart:

```azurecli
azure vm reset-access \
--resource-group myResourceGroup \
--name myVM \
--reset-ssh
```

**Comment by yugangw-msft** [comment]
@vlivech, could you elaborate the counterpart command (and related arguments)in node-cli?

**Comment by vlivech** [comment]
@yugangw-msft updated the bug with the node-cli example

**Comment by yugangw-msft** [comment]
@vlivech, thanks. We will add this missing piece.
