### ISSUE TITLE
az configure --list-defaults should not be case sensitive for environment variables 

### ISSUE THREAD

**Issue by richeney** [Azure/azure-cli#14397]
### Background

It appears that the following environment variables are respected by the CLI (and mentioned in closed issue [#7411](https://github.com/Azure/azure-cli/issues/7411)), but they are undocumented:

* AZURE_DEFAULTS_LOCATION
* AZURE_DEFAULTS_GROUP

They correctly override any defaults in ~/.azure/config when running CLI commands. They are not listed as available [environment variables](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-values-and-environment-variables).

I am yet to test if the following also work

* AZURE_DEFAULTS_ACR
* AZURE_DEFAULTS_WEB
* AZURE_DEFAULTS_VM
* AZURE_DEFAULTS_VMSS

> I'll update the documentation once tested. 

### Issue

The `az configure --list-defaults` command doesn't correctly use case insensitivity for these variables. 

### Example

```bash
az configure --defaults location=brazilsouth
export AZURE_DEFAULTS_LOCATION=uksouth
az group create --name right
```

Resource group _right_ correctly created in uksouth. But the `az configure --list-defaults` output is:

```json
[
  {
    "name": "LOCATION",
    "source": "AZURE_DEFAULTS_LOCATION",
    "value": "uksouth"
  },
  {
    "name": "location",
    "source": "/home/richeney/.azure/config",
    "value": "brazilsouth"
  }
]
```

This should show as:

```json
  {
    "name": "location",
    "source": "AZURE_DEFAULTS_LOCATION",
    "value": "uksouth"
  }
]
```

### Example 2

Follow on from example 1.

```bash
az configure --defaults group=wrong
export AZURE_DEFAULTS_group=false_override
export AZURE_DEFAULTS_GROUP=right
az identity create --name myidentity
```

The identity is created correctly in uksouth and in the _right_ resource group. But again the `az configure --list-available` output is misleading and confusing:

```json
[
  {
    "name": "GROUP",
    "source": "AZURE_DEFAULTS_GROUP",
    "value": "right"
  },
  {
    "name": "LOCATION",
    "source": "AZURE_DEFAULTS_LOCATION",
    "value": "uksouth"
  },
  {
    "name": "group",
    "source": "AZURE_DEFAULTS_group",
    "value": "false_override"
  },
  {
    "name": "location",
    "source": "/home/richeney/.azure/config",
    "value": "brazilsouth"
  }
]
```

Now the group default looks like it has been overridden by the AZURE_DEFAULTS_group environment variable, but that is (correctly) ignored. Correct output would be:

```json
[
  {
    "name": "group",
    "source": "AZURE_DEFAULTS_GROUP",
    "value": "right"
  },
  {
    "name": "location",
    "source": "AZURE_DEFAULTS_LOCATION",
    "value": "uksouth"
  }
]
```

**Comment by yonzhan** [comment]
add to S174

**Comment by jiasli** [comment]
Looks like a bug. Will investigate in S174.

**Comment by jiasli** [comment]
I agree that in `az configure --list-defaults`, the overridden value should not be displayed.

However, it is the behavior of Linux Bash to be **case-sensitive** for environment variables:

```sh
$ export AZURE_DEFAULTS_group=false_override
$ export AZURE_DEFAULTS_GROUP=right
$ env | grep AZURE_DEFAULTS
AZURE_DEFAULTS_GROUP=right
AZURE_DEFAULTS_group=false_override
```

Note that `AZURE_DEFAULTS_GROUP` and `AZURE_DEFAULTS_group` exist at the same time.

On the contrary, Windows PowerShell is **case-insensitive** for environment variables:

```powershell
$Env:AZURE_DEFAULTS_group='false_override'
$Env:AZURE_DEFAULTS_GROUP='right'
> Get-ChildItem Env:AZURE_DEFAULTS_*

Name                           Value
----                           -----
AZURE_DEFAULTS_group           right
```

In order for Azure CLI's behavior to be consistent across platforms, I suggest we only honor `AZURE_DEFAULTS_GROUP` and ignore the malformed `AZURE_DEFAULTS_group` which is never said to be supported in the [Azure CLI configuration](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest) document.

To be more specific, even if only `AZURE_DEFAULTS_group` is supplied, it should be ignored. Introducing an overriding logic between `AZURE_DEFAULTS_GROUP` and `AZURE_DEFAULTS_group` will even complicate things more.

**Comment by richeney** [comment]
100% agree with Bash only honoring the all caps AZURE_DEFAULTS_GROUP.

AZURE_DEFAULTS_group isn't honored by the az commnds, as per the text in Example 2.

But if AZURE_DEFAULTS_group is set as an env var then the value was erroneously reported by the `az configure --list-defaults` command. The problem is only with the logic in that specific command.
