### ISSUE TITLE
Deleted keyvault with option --enable-soft-delete true does not appear in list of deleted keyvaults

### ISSUE THREAD

**Issue by magnus-longva-bouvet** [Azure/azure-cli#14396]
**Describe the bug**
I create a keyvault with `--enable-soft-delete true` and then delete this keyvault. The keyvault does not show up in `az keyvault list-deleted` afterwards, the keyvault can't be purged with `az keyvault purge <kv_name>`, and a new keyvault of the same name can *not* be created.

**To Reproduce**
```
$:~/$ az keyvault list
[]

$:~/$ az keyvault create --name test-kv123123123123 --resource-group $RESOURCE_GROUP_NAME --enabled-for-template-deployment true --enable-soft-delete true                                                                                                                                  
{- Finished ..
  "id": "/subscriptions/<some-guid>/resourceGroups/<my-resource-group>/providers/Microsoft.KeyVault/vaults/test-kv123123123123",
  "location": "norwayeast",
  "name": "test-kv123123123123",
  "properties": {
    "accessPolicies": [
      {
        "applicationId": null,
        "objectId": "<some-guid>",
        "permissions": {
          "certificates": [
            "get",
            "list",
            "delete",
            "create",
            "import",
            "update",
            "managecontacts",
            "getissuers",
            "listissuers",
            "setissuers",
            "deleteissuers",
            "manageissuers",
            "recover"
          ],
          "keys": [
            "get",
            "create",
            "delete",
            "list",
            "update",
            "import",
            "backup",
            "restore",
            "recover"
          ],
          "secrets": [
            "get",
            "list",
            "set",
            "delete",
            "backup",
            "restore",
            "recover"
          ],
          "storage": [
            "get",
            "list",
            "delete",
            "set",
            "update",
            "regeneratekey",
            "setsas",
            "listsas",
            "getsas",
            "deletesas"
          ]
        },
        "tenantId": "<some-guid>"
      }
    ],
    "createMode": null,
    "enablePurgeProtection": null,
    "enableRbacAuthorization": null,
    "enableSoftDelete": true,
    "enabledForDeployment": false,
    "enabledForDiskEncryption": null,
    "enabledForTemplateDeployment": true,
    "networkAcls": null,
    "privateEndpointConnections": null,
    "provisioningState": "Succeeded",
    "sku": {
      "name": "standard"
    },
    "softDeleteRetentionInDays": 90,
    "tenantId": "<some-guid>",
    "vaultUri": "https://test-kv123123123123.vault.azure.net/"
  },
  "resourceGroup": "<my-resource-group>",
  "tags": {},
  "type": "Microsoft.KeyVault/vaults"
}                                                                                                                                                            

$:~/$ az keyvault delete --name test-kv123123123123 --resource-group $RESOURCE_GROUP_NAME --verbose                            
Configured default '<my-resource-group>' for arg resource_group_name
Command ran in 3.691 seconds (init: 0.139, invoke: 3.552)                                                                                                    

$:~/$ az keyvault list-deleted                                                                                                 []
[]

$:~/$ az keyvault purge --name test-kv123123123123
No deleted vault was found with name test-kv123123123123

$:~/$ az keyvault create --name test-kv123123123123 --resource-group $RESOURCE_GROUP_NAME --enabled-for-template-deployment true --enable-soft-delete false
The property "enableSoftDelete" can be set to false only for creating new vault. Enabling the 'soft delete' functionality is an irreversible action.
```

**Expected behavior**
After running `az keyvault create --name test-kv123123123123 --resource-group $RESOURCE_GROUP_NAME --enabled-for-template-deployment true --enable-soft-delete true` and `az keyvault delete --name test-kv123123123123 --resource-group $RESOURCE_GROUP_NAME --verbose`, the command `az keyvault list-deleted` should return a list which includes the recently deleted keyvault, and `az keyvault purge --name test-kv123123123123` should purge the deleted keyvault. 

**Environment summary**

Using Azure CLI 2.9.0 on WSL Ubuntu 20.04, Windows 10.

```
az version                                                                                                               
{
  "azure-cli": "2.9.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.9.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}
```

**Additional context**

**Comment by yungezz** [comment]
hi @bim-msft could you pls have a look?

**Comment by bim-msft** [comment]
Thanks for the feedback, this seems to be a bug. Working on this.

**Comment by bim-msft** [comment]
Hi @magnus-longva-bouvet Could you please try the latest CLI 2.11.1 to verify if it works? I cannot reproduce this using the latest version. Thanks.

**Comment by techadmin1982** [comment]
Hey Same Problem .. i mean BIG PROBLEM. I am testing the Azure CAF Landing Zones using Terraform. The workflow would try to create a keyvault during the process and later i will destroy the resources. Yesterday I ran it for the first time and it created a KV by the name of Launchpad in my subscription. Later i destroyed the resources and after some time tried running the deployment script again. BOOM ... there was an error - saying KV with name Launchpad already exists. I went to portal and manually tried to create with same name and got same error. 

Funny thing is if i am searching (and i am using Cloud Shell running latest v 2.11.1) with az keyvault list-deleted 
there is no output. Please can someone help me ????

**Comment by techadmin1982** [comment]
Please fix this problem. I now have a new subscription and tenant however keyvault with the name "launchpad" still can not be created. 
![Capture](https://user-images.githubusercontent.com/42249185/93849440-c14e9480-fcc9-11ea-9cca-271cd0acd9ac.JPG)

**Comment by bim-msft** [comment]
Hi @techadmin1982 , sorry for the late reply. I still cannot reproduce this issue, so it's really hard for me to debug this on my side. Could you please run `az keyvault list-deleted` with `--debug` and paste the log here? Thanks.

**Comment by yungezz** [comment]
hi @techadmin1982 could you pls share the otuput with `--debug` thanks.

**Comment by bim-msft** [comment]
I have reproduced this issue using subs `AzureSDKTeam`: there is a deleted vault named `Launchpad` exists but I cannot purge or list it, and of course I cannot create a vault with the same name.

**Comment by bim-msft** [comment]
This seems to be a service side issue. Adding the service team.

**Comment by sebansal** [comment]
Adding @shanebala-keyvault to help review

**Comment by ShaneBala-keyvault** [comment]
Hi @techadmin1982 when you create a key vault, the name is globally unique. When you cleaned up your resources, your key vaults moved to the soft deleted state. Before you can create new key vaults with the soft deleted state, you must purge your key vaults. 

In extremely rare cases a bug in the purge operation could cause the key vault to enter a locked state where you can no longer view, recover, or purge the key vault. I have reached out to my dev team to resolve the issue with this key vault.

**Comment by sebansal** [comment]
Hi @bim-msft 
I was triaging this list, can you share if it has been resolved and can be closed?
Thanks

**Comment by bim-msft** [comment]
Hi @sebansal , this was identified as a service side issue, no more CLI side investigation needed so far.

**Comment by sebansal** [comment]
Can you help summarize the problem /question service team need to address? Shane from product side answered the question.
Feel to reopen the issue if is not answered yet.

**Comment by tmjnsn** [comment]
This issue still occurs. I deleted a keyvault through the Azure portal. Now when I try to create one with the same name it says:
`The Vault '<name>' not found within subscription.
Azure Key Vault '<name>' has been soft deleted. Operations on this vault can be performed only after recovering it.`

However when I get the list of soft-deleted keyvaults (either through cli or through the portal) that keyvault is not listed.

The command to restore it also does not work:
`Undo-AzKeyVaultRemoval: A soft deleted vault with the given name does not exist.`

**Comment by sebansal** [comment]
Hi @magnus-longva-bouvet i encourage you to open up a support request with Azure Support team. When you'd open the support request, it will collect some metadata and perform diagnostics. For instructions, you can follow the guidance here https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by sebansal** [comment]
https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-recovery?tabs=azure-portal#prerequisites


Permission | Description
-- | --
Microsoft.KeyVault/locations/deletedVaults/read | View the properties of a soft deleted key vault
Microsoft.KeyVault/locations/deletedVaults/purge/action | Purge a soft deleted key vault
