### ISSUE TITLE
.NET SDK support for Management policies in Azure storage account.

### ISSUE THREAD

**Issue by hem-sharma** [Azure/azure-cli#14392]
I am using .NET SDK to create blob containers on the fly and it's not feasible to set policy manually or CLI/PowerShell every time a container is created using SDK. There should be a configuration during creation APIs in SDK to support the same, I didn't find any documentation for the same or is it being developed? Can someone from team help me into this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f84b325-33af-86ab-749e-faec2e01a1f3
* Version Independent ID: 87036460-df59-9239-680d-29c68a0490bb
* Content: [az storage account management-policy](https://docs.microsoft.com/en-us/cli/azure/storage/account/management-policy?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@hem-sharma  this is Azure CLI repo, please create an issue in PowerShell repo. Thanks
