### ISSUE TITLE
az local-context: 'show' is not in the 'az local-context' command group

### ISSUE THREAD

**Issue by dmraymond** [Azure/azure-cli#14406]
## Describe the bug

**Command Name**
`az local-context`

**Errors:**
```
az local-context: 'show' is not in the 'az local-context' command group. See 'az local-context --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az local-context {}`

## Expected Behavior
https://docs.microsoft.com/en-us/cli/azure/local-context?view=azure-cli-latest#az-local-context-show

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.4.0 *

Extensions:
interactive 0.4.3

```

**Comment by yungezz** [comment]
hi @dmraymond  could you pls upgrade to latest Azure CLI version? az local-context show is supported later than 2.4.0. thanks.

**Comment by arrownj** [comment]
Hi @dmraymond , `local-context show` is supported from `2.6.0`, you can upgrade your CLI version and try again.

**Comment by arrownj** [comment]
Close this first, as `az local-context show` is support from `2.6.0`.
