### ISSUE TITLE
Webapp:Support env file style files for @arguments

### ISSUE THREAD

**Issue by forty** [Azure/azure-cli#14405]
To configure the environment of my webapp for containers, I'm running this:
`az webapp config appsettings set -g "$RG" -n "$NAME" --settings WEBSITES_PORT=3000 "@$CONFIG"`

$CONFIG is a file containing several environment variables. It works great when the file is in JSON format, but it works weirdly when the file in in "env file" format (similar to the format that is supported by `docker run --env-file <file>`): it only use the first key, then everything else as the value.
For example
```
KEY1=value1
KEY2=value2
```

is parsed as 

```
KEY1=value1\nKEY2=value2
```
 (and same with windows style end of line)

**Describe the solution you'd like**

I think it would be great to work well with env files, so that environment setup can be made more consistent with the way it's done on docker cli 

**Describe alternatives you've considered**

Converting the config file to JSON works well, but it's not consistent with the way docker cli works (and other docker environments too, for example AWS ECS allows to have an env file on S3), so it adds more step when explaining to a customer how to setup our software on Azure, vs other docker hosting solution.

**Additional context**

N/A

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@btardif this is a feature request so assigning to you to help figure this out. Thanks

**Comment by forty** [comment]
Sorry to ask, but is there any plan to work on this soon? (I saw that it was put in S174, but it's not anymore, I'm not sure what it means?) - I'm just asking to know if I can count on it or not.

Thanks!

**Comment by ndanielsen** [comment]
Adding to this issue. I'm working on deploying a custom django app in docker container app to the Azure web app service. This is migrating it from heroku.

The standard in python (and other languages) is to use `.env` file for ENVs. 

It would be great to have a similar interface such as:

`az webapp config appsettings set -g MyResourceGroup -n MyUniqueApp --settings-file  .env`

Source:
https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az_webapp_config_appsettings_set-examples

Heroku ENV guidance
https://devcenter.heroku.com/articles/heroku-local

**Comment by navba-MSFT** [comment]
@forty Apologies for the late reply. We will update this thread once we have more details on this.

@seligj95 Could you please provide the latest update on this thread ? Awaiting your reply.

**Comment by zboldyga** [comment]
@navba-MSFT 

We have a similar need for .env file support, here's a gist with the [current workaround](https://gist.github.com/zboldyga/8f51868c7b1d7269bb2679fb036d4995) using the python-dotenv package, which has a well-tested, production-hardened implementation of .env file parsing.

I'm happy to implement this as an open source contribution if you'd like?

I see the underlying JSON support [here](https://github.com/Azure/azure-cli/blob/951e42a1e094f157f5a8e222ae11b78302a24218/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L377) and [parsing here](https://github.com/Azure/azure-cli/blob/951e42a1e094f157f5a8e222ae11b78302a24218/src/azure-cli-core/azure/cli/core/util.py#L532). I can stick to that format, with a parser utility that loads the data into list of settings, then use [this logic](https://github.com/Azure/azure-cli/blob/951e42a1e094f157f5a8e222ae11b78302a24218/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L387) to handle the list.

Thoughts?

**Comment by flammable** [comment]
Thanks for the workaround, @zboldyga. As someone who's new to this, the documentation was somewhat confusing - it's mentioned that you can provide a file, and the example uses a json file, but it's not specified that it's your _only_ option. I expected to be able to import a .env file, too, considering I'm running a container.

**Comment by seligj95** [comment]
Thank you for the feedback but we will not be doing this at this time.
