### ISSUE TITLE
az mysql up error on password-too-short isn't descriptive enough

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#14407]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Command error around password isn't descriptive enough, and hence users can't follow up to resolve it 

**To Reproduce**

(have cross linked with the ADO issue)

**Expected behavior**

Error message aligning with portals

**Environment summary**

Across all OS

**Additional context**

**Comment by yonzhan** [comment]
add to S173
