### ISSUE TITLE
Error in the description

### ISSUE THREAD

**Issue by guangying94** [Azure/azure-cli#14400]
[Enter feedback here]
Error is the description:

1. **--endpoint-dest-address**
Error in description, it should be "Address of the destination of connection monitor endpoint"

2. **--endpoint-source-resource-id**
If endpoint is intended to used as source, this option is required. The resource ID should be the source of connection monitor endpoint instead of destination as documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0800fdc3-05ed-9fa8-888a-a8997c6a5a8e
* Version Independent ID: 5d6188b7-5eb4-835d-d63a-32aa1a1f49ca
* Content: [az network watcher connection-monitor](https://docs.microsoft.com/en-us/cli/azure/network/watcher/connection-monitor?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S174
