### ISSUE TITLE
[AppService] Bug: az webapp create --runtime doesn't set specified runtime

### ISSUE THREAD

**Issue by calvinsID** [Azure/azure-cli#14409]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
`az webapp create -g RG -n WebappName --plan Plan -r "php|7.3"` sets the runtiem to "php|5.x" instead of "php|7.3".

**To Reproduce**
Run `az webapp create -g RG -n WebappName --plan Plan -r "php|7.3"`
Run `az webapp config show -g RG -n WebappName`

**Expected behavior**
Verify runtime version from `az webapp config show` command: Should be php 7.3 instead of 5.x

**Comment by yonzhan** [comment]
webapp
