### ISSUE TITLE
az webapp config container set Base64 encoding of multicontainer-config-file is invalid

### ISSUE THREAD

**Issue by Orthaanc** [Azure/azure-cli#14417]
## Describe the bug

**Command Name**
`az webapp config container set`

**Errors:**
Generated compose text results in invalid app service configuration. Specifically the DOCKER_CUSTOM_IMAGE_

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
using the example [dev.test.yml] attached here as dev.test.yml.txt
[dev.test.yml.txt](https://github.com/Azure/azure-cli/files/4944762/dev.test.yml.txt)
rename to dev.test.yml

configure to deploy into an azure app service (any valid app service target is relevant)
- `az webapp config container set --resource-group <your app service resource group name> --name <your app service name> --multicontainer-config-type compose --multicontainer-config-file dev.test.yml`

## Expected Behavior
The expected behavior is to see the content of the dev.test.yml file base64 encoded in the compose config parameter.
`version: '3.5'
services:
  website:
    image: nginx`
should encode to 
`dmVyc2lvbjogJzMuNScKc2VydmljZXM6CiAgd2Vic2l0ZToKICAgIGltYWdlOiBuZ2lueA==`

but is instead encoding as
`dmvyc2lvbjogjzmunsckc2vydmljzxm6ciagd2vic2l0ztokicagigltywdloibuz2luea==`

On close inspection it appears that the base64 encoding is being lowercased.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.8.0 *

```
## Additional Context
In a different environment the casing for the base64 was correct
```azure-cli                         2.0.76 *

command-modules-nspkg              2.0.3
core                              2.0.76 *
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\ortha\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
```

**Comment by yonzhan** [comment]
webapp

**Comment by Orthaanc** [comment]
This appears to be a related or duplicate issue to #14208 where the compose content is lowercased
