### ISSUE TITLE
az storage blob download finished is written to std err

### ISSUE THREAD

**Issue by mleziva** [Azure/azure-cli#14414]
**Describe the bug**
When running the az storage blob download command the finished output is written to std err. Any external callers that look for std err as a sign that the script failed will think that the script has failed even though it succeeded

**To Reproduce**
(az storage blob download --container-name $container_name \
                         --file ./$blob \
                         --name $blob \
                         --account-name $sa_name \
                         --auth-mode login \
                         --only-show-errors ) 2>> err_file

**Expected behavior**
there should be no output to the err_file
Instead:
This is the contents: Finished[#############################################################]  100.0000%

**Additional context**
az -v
azure-cli                          2.8.0 *

command-modules-nspkg              2.0.3
core                               2.8.0 *
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/austin/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Jun 19 2020, 07:14:33)
[GCC 9.3.0]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
add to S174

**Comment by Juliehzl** [comment]
HI @mleziva, it is azure cli core framework design. progress bar is used to let interactive users see download /upload progress.
currently it is hard to change the core framework due to limited bandwidth, but hope it doesn't break your usage and we will recommend to use exit code as error sign for customers.
