### ISSUE TITLE
Webapp:python webapp

### ISSUE THREAD

**Issue by minutice** [Azure/azure-cli#14415]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
HTTPSConnectionPool(host='pools-demo.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x06A4F630>: Failed to establish a new connection: [WinError 10051] Uma operação de socket foi tentada numa rede inacessível',))
Traceback (most recent call last):
pip-install-z9jdo18k\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 80, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --plan {} --location {} --sku {} --name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.9.1

Extensions:
db-up 0.1.14

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@minutice can you please more info here either by running the command by --debug info or share the details of command you are trying to run with the values you are using in the parameter and the  approximate date time in UTC when you ran into this error so that we can check our longs on our end? Thanks!

**Comment by btardif** [comment]
@calvinsID can we close this?

**Comment by panchagnula** [comment]
closing this due to lack of response on
