### ISSUE TITLE
Unable to encode the output with cp1252 encoding. Unsupported characters are discarded.

### ISSUE THREAD

**Issue by demdante** [Azure/azure-cli#14426]
**Describe the bug**

I don't know if this is specific to the command that I am about to reference, but whenever I run the command

```
az ad sp list --all
```

in a powershell console, the console window will return the message "Unable to encode the output with cp1252 encoding. Unsupported characters are discarded" to the console before processing the command.  To be more specific, the message does **NOT** appear if I run the command as displayed about and just output the result to the console.  The error occurs when I attempt to integrate it with powershell in some way.  For example, the error will display if I attempt to assign the output to a variable:

```
$output = az ad sp list --all
```

Another example is if I attempt to pipe the output from the command to the "Convertfrom-Json" cmdlet (since the output is a json string):

```
az ad sp list --all | Convertfrom-json
```

Just so that we are 100% clear here, it does not **appear** that the command is failing in its entirety.  It does return output when I run the above two commands, but, as the error itself states, I don't know if what I am seeing is the entire return.  And if it is, then the error message shouldn't give that impression by being displayed in the first place.

![image](https://user-images.githubusercontent.com/64720591/87964045-2a871100-caa9-11ea-8074-5252c56e1bd5.png)

**To Reproduce**
1. login to azure using az login in a powershell console
2. Run either of these commands

```
$output = az ad sp list --all
```

```
az ad sp list --all | Convertfrom-json
```

**Expected behavior**
The azure cli should not be returning an error indicating that certain characters might have been dropped from the results of a command just because it was run in a powershell console.  And if no characters were dropped, then the azure cli should not display the error in the first place.

**Environment summary**
Running on a windows 10 pro computer and installed using the msi installer downloaded from Microsoft's website

**Comment by yonzhan** [comment]
add to S174

**Comment by kwill-MSFT** [comment]
Workaround until issue is fixed (https://github.com/microsoft/knack/pull/178):
**Control Panel > Region > Administrative > Change system local -> Check the 'Beta: Use Unicode UTF-8 for worldwide language support' option**

**Comment by jiasli** [comment]
The link (https://github.com/microsoft/knack/pull/178) given by @kwill-MSFT is exactly how this warning is introduced.

This is more of a legacy Windows + PowerShell issue where UTF-8 string can't be handled as a variable.

The solution is any of 

1. Remove invalid characters under the current locale from the service principals
2. Use a locale that supports those special characters
3. Check **Beta: Use Unicode UTF-8 for worldwide language support**

The returned content is **complete**. It's only that the string containing invalid characters are discarded. If you are fine with contents being discarded, you may use[`--only-show-errors`](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-values-and-environment-variables) to mute the "Unable to decode ..." warning.

**Comment by marius-klimantavicius** [comment]
@jiasli Could you shed some more light on:
> This is more of a legacy Windows + PowerShell issue where UTF-8 string can't be handled as a variable.

I tried calling az directly from C# without involving powershell (or even cmd, by calling `%AZCLI%\python.exe -IBm azure.cli ad signed-in-user show --output=json` [split into filename and args respectively]) and still getting this warning (and a character in my last name `č` is skipped). Do you know if this windows, python or knack issue?

**Comment by jiasli** [comment]
I think this is a Windows issue, could you try to enable UTC-8 support as shown in https://github.com/microsoft/knack/pull/178 ? This is the reason why this option is introduced in Windows. :)

**Comment by marius-klimantavicius** [comment]
I don't have this option (corporate update policy, but as workaround I `az config set core.only_show_errors=true`). I wonder how Powershell does it - if only for displaying (without doing `| ConvertFrom-Json`) it shows correct name. I was hoping to do the same by creating process myself (will have to check Win32 maybe something's there).

**Comment by cgtheflash** [comment]
This seems to be an issue when doing something as simple as:
$Test = az account list
If you have a subscription with a hyphen in it (like Visual Studio Subscription - MPN), it will replace it with a foreign character.

**Comment by jiasli** [comment]
@cgtheflash, it is very likely that your **hyphen** is not a real [ASCII](https://www.unicode.org/charts/PDF/U0000.pdf) **hyphen-minus** `-`:

![Image](https://github.com/user-attachments/assets/4e05bf3e-9d5e-409b-ac64-195d85656543)

```
002D - HYPHEN-MINUS
= hyphen or minus sign
• used for either hyphen or minus sign
→ 2010 ‐  hyphen
→ 2011   non-breaking hyphen
→ 2012 ‒  figure dash
→ 2013 –  en dash
→ 2043 ⁃  hyphen bullet
→ 2212 −  minus sign
→ 10191 𐆑  roman uncia sign
```

It could be a hyphen `‐`, a minus sign `−`, or an en dash `–` in the the subscription name. 

Please make sure you only use ASCII hyphen-minus `-`. Otherwise, you need to enable UTF-8 support following https://github.com/microsoft/knack/pull/178.

**Comment by cgtheflash** [comment]
Thanks for the information. This is the default name given for a Visual Studio Azure subscription. That's interesting that by default it's not setting a real hyphen. I've also tested by adding additional Visual Studio subscriptions and it happens on all of them. 

You're right though, I renamed a subscription with a hyphen and don't have that problem.

**Comment by jiasli** [comment]
@cgtheflash glad to know it works for you. Using non-ASCII hyphen-minus `-` (`002D`) is definitely a problem for downstream tools running on systems with no UTC-8 support.

It seems you are using [Visual Studio subscriptions offered to partners in the Microsoft Partner Network (MPN)](https://docs.microsoft.com/en-us/visualstudio/subscriptions/program-mpn). I don't have MPN subscription so can't repro this issue or provide further information about my subscription. 

Could you open the above link and click **Feedback** -> **This product** to open the Visual Studio feedback website:

![image](https://user-images.githubusercontent.com/4003950/115171794-73cac680-a0f6-11eb-8a27-9e3ab597a6ff.png)

Then report a problem following [How to report a problem for Visual Studio and Visual Studio Installer](https://developercommunity2.visualstudio.com/report?space=8&entry=problem).

Then you may paste the link here. I will follow up with this issue and provide available information from Azure CLI side. Thanks for your help.
