### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by nkolench** [Azure/azure-cli#14437]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/acs/custom.py, ln 1183, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
cli/command_modules/acs/custom.py, ln 1125, in _handle_merge
    if not i.get('name', False) or not j.get('name', False):
AttributeError: 'NoneType' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {} --subscription {}`

## Environment Summary
```
Linux-4.18.0-80.11.2.el8_0.x86_64-x86_64-with-centos-8.0.1905-Core
Python 3.6.8
Installer: RPM

azure-cli 2.9.1

```

**Comment by nkolench** [comment]
Hello
I've re-installed az cli. But it doesn't help
sudo yum remove azure-cli
sudo rm /etc/yum.repos.d/azure-cli.repo
MSFT_KEY=`rpm -qa gpg-pubkey /* --qf "%{version}-%{release} %{summary}\n" | grep Microsoft | awk '{print $1}'`
sudo rpm -e --allmatches gpg-pubkey-$MSFT_KEY
sudo yum remove -y python3 azure-cli
sudo yum install -y python3 azure-cli
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[azure-cli]
name=Azure CLI
baseurl=https://packages.microsoft.com/yumrepos/azure-cli
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'
sudo yum install azure-cli

**Comment by yungezz** [comment]
#14287

**Comment by navba-MSFT** [comment]
@nkolench Apologies for the late reply. This issue seems to be fixed here #14335 . Could you please use the most [recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the Azure CLI and let us know if you are still facing this issue ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@nkolench I wanted to do quick follow-up to check if you had a chance to look at my above comment. This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by nkolench** [comment]
hi
the issue is resolved
thank you

**Comment by navba-MSFT** [comment]
@nkolench Thanks for your reply. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
