### ISSUE TITLE
`az acs kubernetes get-credentials` should take resource_group/name rather than location/dns-prefix

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1443]
It's generally more common for GET operation in the CLI to happen via `resource_name` and `resource_group_name` rather than via some properties of the resource or resource group (`dns_prefix`/`location`).

Maybe consider changing `get-credentials` to be more in line with other resources? Or maybe there was a reason that dns prefix and location were thought to be better?

**Comment by colemickens** [comment]
cc: @brendandburns especially given your desire to potentially remove `dns-prefix` entirely from the API.

**Comment by colemickens** [comment]
Just saw the TODO, I guess it may not be ready yet...

**Comment by brendandburns** [comment]
Fixed by https://github.com/Azure/azure-cli/pull/1356
