### ISSUE TITLE
Parsing issue with az CLI in DevOps

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#14430]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

"I am creating app registrations in our AAD using DevOps release pipelines and Azure CLI component with Powershell. I am running into an issue when running the commands within an inline script with a parser in az cli that is taking my app role description and breaking up the input into a list of values at the spaces within the description. I've run the same script via command line in local powershell and don't experience the same parsing issue.

 

Is there anyway to escape the spaces such that the parse won't behave this way?

 

Your guidance/suggested will be greatly appreciated."

**To Reproduce**
The az cli command I am building starts with

az ad app create --display-name "myAppReg" --reply-urls "https://myAppName.azurewebsites.net/.auth/login/aad/callback"

(obvious changes). This works fine.

 

When I try to add --app-roles with value (manifest json format)

"[{'allowedMemberTypes':['User'],'description':'Users have the ability to create, modify, and delete workflow items.','displayName':'User','isEnabled':true,'value':'User'}]"
"[{\"allowedMemberTypes\":[\"User\"],\"description\":\"Users have the ability to create, modify, and delete workflow items.\",\"displayName\":\"User\",\"isEnabled\":true,\"value\":\"User\"}]"
'[{\"allowedMemberTypes\":[\"User\"],\"description\":\"Users have the ability to create, modify, and delete workflow items.\",\"displayName\":\"User\",\"isEnabled\":true,\"value\":\"User\"}]'
'[{"allowedMemberTypes":["User"],"description":"Users have the ability to create, modify, and delete workflow items.","displayName":"User","isEnabled":true,"value":"User"}]'
 

I receive "Expecting property name enclosed in double quotes: line 1 column 3 (char 2)".

 

Adding the "--debug" to the end of the az command shows:

 

Command arguments: ['ad', 'app', 'create', '--display-name', 'myAppReg', '--app-roles', '[{\\', 'allowedMemberTypes\\:[\\User\\],\\description\\:\\Users', 'have', 'the', 'ability', 'to', 'create,', 'modify,', 'and', 'delete', 'workflow', 'items.\\,\\displayName\\:\\User\\,\\isEnabled\\:true,\\value\\:\\User\\}]', '--reply-urls', 'https://myAppName.azurewebsites.net/.auth/login/aad/callback', '--debug']

 

My script contains the following function

 

Function New-AppRegistration {

    [CmdletBinding()]

    Param(

        [string] $DisplayName,

        [string] $AppRoles = "",

        [string] $ReplyUrls = ""

    )

 

    $appInfo = (az ad app list --display-name $DisplayName) | ConvertFrom-Json

 

    if (!$appInfo) {

        $cmd = "az ad app create --display-name ""$($DisplayName)"""

 

        if ($AppRoles) {

            $AppRoles = $AppRoles.Replace("'",'\"')

            $cmd += @"

 --app-roles "$($AppRoles)"

"@

        }

        if ($ReplyUrls) { $cmd += " --reply-urls ""$($ReplyUrls)"""}

        $cmd += " --debug"

 

        $sb = [scriptblock]::Create($cmd)

        $appInfo = (Invoke-Command -ScriptBlock $sb | ConvertFrom-Json)

        if (!$appInfo){

            Write-Error "Error creating application registration for '$($DisplayName)'."

        }

    }

    return $appInfo.appId

}

 

I appreciate the response greatly."

**Expected behavior**

**Environment summary**

**Additional context**
"here is the command line version that works:

az ad app create --display-name "myAppReg" --reply-urls "https://myApp.azurewebsites.net/.auth/login/aad/callback" --app-roles "[{'allowedMemberTypes':['User'],'description':'Users have the ability to create, modify, and delete workflow items.','displayName':'User','isEnabled':true,'value':'User'}]".Replace("'",'\"')

 

This has been my target for the script."

**Comment by elafnit** [comment]
The string.Replace command should be .Replace("'",'\"')

**Comment by elafnit** [comment]
After trying different combination of single, double quoting, and escaped double quote, along with formatting within the function calling the 'az ad app create' command, I am able to get to the point where the parsing is mostly complete in CICD powershell/az cli. The spaces are still causing parsing issues.

The debug output shows the following for the parser:
Command arguments: ['ad', 'app', 'create', '--display-name', 'myAppReg', '--app-roles', '[{"allowedMemberTypes":["User"],"description":"Users', 'have', 'the', 'ability', 'to', 'create,', 'modify,', 'and', 'delete', 'workflow', 'items.","displayName":"User","isEnabled":true,"value":"User"}]', '--reply-urls', 'https://myApp.azurewebsites.net/.auth/login/aad/callback', '--debug']

the input --app-role variable in CICD release pipeline is formatted as [{"allowedMemberTypes":["User"],"description":"Users have the ability to create, modify, and delete workflow items.","displayName":"User","isEnabled":true,"value":"User"}]

And my function preformatting includes: 
$AppRoles = $AppRoles.Replace('"','\\"').Replace("'",'\\"')  #char[](92,34)

**Comment by yungezz** [comment]
hi @arrownj could you pls have a look? thanks.

**Comment by arrownj** [comment]
Hi @chenlomis @elafnit , it's not the problem of quote of the whole `--app-roles` value. It's because that there is no quote for `'isEnabled':true`. There are 2 options to do this:

1. add quote for `true`, the command should like this:

> az ad app create --display-name "myAppReg" --reply-urls "https://myAppName.azurewebsites.net/.auth/login/aad/callback" --app-roles "[{'allowedMemberTypes':['User'],'description':'Users have the ability to create, modify, and delete workflow items.','displayName':'User','isEnabled':**'true'**,'value':'User'}]"

2. write json content in a json file, and specify json path to `--app-roles`

> approles.json
[
  {
    "allowedMemberTypes": [
      "User"
    ],
    "description": "Users have the ability to create, modify, and delete workflow items.",
    "displayName": "User",
    "isEnabled": true,
    "value": "User"
  }
]
az ad app create --display-name "myAppReg" --reply-urls "https://myAppName.azurewebsites.net/.auth/login/aad/callback" --app-roles @approles.json

**Comment by elafnit** [comment]
Something else may be occurring here. I quoted the "true" and it is still parsing on the spaces. I've added debugging to the script and found this in the arm logs
2020-07-21T15:00:59.9184690Z Command arguments: ['ad', 'app', 'create', '--display-name', 'myAppReg', '--debug', '--app-roles', '[{"allowedMemberTypes":["User"],"description":"Users', 'have', 'the', 'ability', 'to', 'create,', 'modify,', 'and', 'delete', 'workflow', 'items.","displayName":"User","isEnabled":"true","value":"User"}]', '--reply-urls', 'https://myApp.azurewebsites.net/.auth/login/aad/callback', '--debug']

when I run the same script from powershell locally, I see
Command arguments: ['ad', 'app', 'create', '--display-name', 'myAppReg', '--debug', '--app-roles', '[{"allowedMemberTypes":["User"],"description":"Users have the ability to create, modify, and delete workflow items.","displayName":"User","isEnabled":"true","value":"User"}]', '--reply-urls', 'https://myApp.azurewebsites.net/.auth/login/aad/callback', '--debug']

My values for --app-roles
1. in pipeline variable: [{"allowedMemberTypes":["User"],"description":"Users have the ability to create, modify, and delete workflow items.","displayName":"User","isEnabled":"true","value":"User"}]
[{"allowedMemberTypes":["User"],"description":"Users have the ability to create, modify, and delete workflow items.","displayName":"User","isEnabled":"true","value":"User"}]

2. in local commandline: '[{"allowedMemberTypes":["User"],"description":"Users have the ability to create, modify, and delete workflow items.","displayName":"User","isEnabled":"true","value":"User"}]'

I am very open to working through this problem in person.

**Comment by elafnit** [comment]
[SOLVED]
I was using Azure CLI with "Powershell" as "Script Type". I updated this to "Powershell Core", realizing that azure cli is supported on core only, and this has corrected the issues I was seeing. Thanks for your willingness to support me through this. You can close this issue as resolved.
