### ISSUE TITLE
Virtual Machines Run Commands - 'RunPowerShellScript' Run command is giving incorrect output

### ISSUE THREAD

**Issue by karthikvarmak1** [Azure/azure-cli#14446]
I want the services running in a windows vm and I queried the below script using Run command API.
```
{
  "commandId": "RunPowerShellScript",
  "script": ["get-service | ft Status,Name,DisplayName -auto"]
}
```
Output is returning only less number of data. (34 services out of 211 services)

`{
  "startTime": "2020-07-21T10:11:47.0488466+00:00",
  "endTime": "2020-07-21T10:13:45.147466+00:00",
  "status": "Succeeded",
  "properties": {
    "output": {
      "value": [
        {
          "code": "ComponentStatus/StdOut/succeeded",
          "level": "Info",
          "displayStatus": "Provisioning succeeded",
          "message": "              \n     Running vmicshutdown                             Hyper-V Guest Shutdown Service                                   \n     Running vmictimesync                             Hyper-V Time Synchronization Service                             \n     Stopped vmicvmsession                            Hyper-V PowerShell Direct Service                                \n     Running vmicvss                                  Hyper-V Volume Shadow Copy Requestor                             \n     Running VSS                                      Volume Shadow Copy                                               \n     Running W32Time                                  Windows Time                                                     \n     Stopped WaaSMedicSvc                             Windows Update Medic Service                                     \n     Stopped WalletService                            WalletService                                                    \n     Stopped WarpJITSvc                               WarpJITSvc                                                       \n     Stopped WbioSrvc                                 Windows Biometric Service                                        \n     Running Wcmsvc                                   Windows Connection Manager                                       \n     Stopped WdiServiceHost                           Diagnostic Service Host                                          \n     Running WdiSystemHost                            Diagnostic System Host                                           \n     Running WdNisSvc                                 Windows Defender Antivirus Network Inspection Service            \n     Stopped Wecsvc                                   Windows Event Collector                                          \n     Stopped WEPHOSTSVC                               Windows Encryption Provider Host Service                         \n     Stopped wercplsupport                            Problem Reports and Solutions Control Panel Support              \n     Stopped WerSvc                                   Windows Error Reporting Service                                  \n     Stopped WiaRpc                                   Still Image Acquisition Events                                   \n     Running WinDefend                                Windows Defender Antivirus Service                               \n     Running WindowsAzureGuestAgent                   Windows Azure Guest Agent                                        \n     Running WindowsAzureNetAgentSvc                  Windows Azure Network Agent                                      \n     Running WinHttpAutoProxySvc                      WinHTTP Web Proxy Auto-Discovery Service                         \n     Running Winmgmt                                  Windows Management Instrumentation                               \n     Running WinRM                                    Windows Remote Management (WS-Management)                        \n     Stopped wisvc                                    Windows Insider Service                                          \n     Stopped wlidsvc                                  Microsoft Account Sign-in Assistant                              \n     Running wmiApSrv                                 WMI Performance Adapter                                          \n     Stopped WMPNetworkSvc                            Windows Media Player Network Sharing Service                     \n     Stopped WPDBusEnum                               Portable Device Enumerator Service                               \n     Running WpnService                               Windows Push Notifications System Service                        \n     Running WpnUserService_11b5533                   Windows Push Notifications User Service_11b5533                  \n     Stopped WSearch                                  Windows Search                                                   \n     Running wuauserv                                 Windows Update                                                   \n\n"
        },
        {
          "code": "ComponentStatus/StdErr/succeeded",
          "level": "Info",
          "displayStatus": "Provisioning succeeded",
          "message": ""
        }
      ]
    }
  },
  "name": "5d4d6b5a-1f90-4ea1-95ad-b10e2e776488"
}`

Referred Docs : https://docs.microsoft.com/en-us/rest/api/compute/virtual%20machines%20run%20commands/runcommand

Is this an issue ?

**Comment by yonzhan** [comment]
This is not Azure CLI issue, right? Please open an issue to Service team.

**Comment by karthikvarmak1** [comment]
How to assign it to service team? Can you let me know.

**Comment by qwordy** [comment]
Click "help" in Azure Portal?

**Comment by jiasli** [comment]
The Azure CLI command for **Run Command** is [`az vm run-command`](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest). 

For REST API issue, you may [create a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) and a support engineer will gladly help you with this issue.
