### ISSUE TITLE
Webapp:It can't create a webapp in a app service plan

### ISSUE THREAD

**Issue by rockbass2560** [Azure/azure-cli#14450]
**Describe the bug**
When I tried to create an webapp in a service plan I received a error.

Command used
az webapp create --resource-group myResourceGroup --plan myAppServicePlan --name app --runtime "DOTNETCORE|LTS" --deployment-local-git

Error received
ResourceNotFound - The Resource 'Microsoft.Web/sites/app' under resource group 'myResourceGroup' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

**To Reproduce**
- Create a resource group
- Create a Azure service plan
- Create a web app
Follow instructions on:
https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-dotnetcore

**Expected behavior**
The web app has been created

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@rockbass2560 what is the version on CLI you are using can you make sure you are using 2.9.0 or higher? thanks

**Comment by rockbass2560** [comment]
@panchagnula it happens on Ubuntu 20.4 LTS, az --version returns this:
azure-cli                          2.9.1
command-modules-nspkg              2.0.3
core                               2.9.1
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/rockbass2560/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Jul 16 2020, 08:13:35) 
[GCC 9.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by calvinsID** [comment]
@rockbass2560 Thanks for reporting! It is because the name "app" is already taken, and not in your subscription. I opened a PR to surface a better error for this. Will change error msg to "Unable to retrieve details of the existing app 'app'. Please check that the app is a part of the current subscription" instead of "ResourceNotFound..."

**Comment by rockbass2560** [comment]
Thanks @calvinsID, I created the webapp from webpage and I can see that the ID needs to be new. The error message gave not a clue about the problem. The message can be clearer for new users.

**Comment by calvinsID** [comment]
Fixed in upcoming CLI release by PR #14431
