### ISSUE TITLE
`az acs kubernetes install-cli` needs to mark kubectl as executable if on a *nix

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1447]
Was writing a patch, was using the docker container, noticed that `install-cli` left `kubectl` non-executable.

Will send a PR.

**Comment by mayurid** [comment]
@brendanburns as fyi

**Comment by colemickens** [comment]
Closed, relevant PR was merged: https://github.com/Azure/azure-cli/pull/1449
