### ISSUE TITLE
Cannot switch between OWASP rule sets using add/remove or update in WAF_v2

### ISSUE THREAD

**Issue by alexpilon666** [Azure/azure-cli#14499]
Due to how the WAF_v2 is setup, you need at least one set of OWASP rules enabled, and by default, the CLI creates the WAF using OWASP 3.0 (instead of 2.2.9 or 3.1), and there's no way in `az network application-gateway waf-policy create` to specify the OWASP version.

My first line of thinking was to add OWASP 3.1 using `az network application-gateway waf-policy managed-rule rule-set add`, but it failed silently with no errors. Same when I tried to remove OWASP 3.0 using `az network application-gateway waf-policy managed-rule rule-set remove`. 

My logical thinking was then to use `az network application-gateway waf-policy managed-rule rule-set update`, with `--type OWASP --version 3.1`...but the `update` action requires the `--group-name` argument, even if we're not managing rules but rather rule-sets.

Thus, the current status of Azure CLI makes it impossible to create a new WAF Policy in WAF_v2 and use OWASP 3.1, it has to be done manually in the portal.

Suggested fixes:
- Disable the requirement for the `--group-name` argument, and only make it a requirement if paired with `--rules`. so that we can switch over between OWASP rule set versions
- Make it possible to set the initial OWASP rule set version at creation, to prevent having to rely on a second command to then switch over.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69735220-baba-8209-3360-beafe13138cb
* Version Independent ID: d0cfd033-613d-12e0-4de3-cdea1972fcc0
* Content: [az network application-gateway waf-policy managed-rule rule-set](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/waf-policy/managed-rule/rule-set?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S174

**Comment by MyronFanQiu** [comment]
@alexpilon666 Hi. Could you please have a try before we merge this PR? I don't fully catch your usage scenario and may misunderstand something. I exposed the type and the version in `az network application-gateway waf-policy` command. Could you help us to have a try and verify the functionality? You can download edge build from this [link](https://dev.azure.com/azure-sdk/public/_build/results?buildId=473297&view=artifacts&type=publishedArtifacts).
