### ISSUE TITLE
acr helm group is deprecated, please update documentation

### ISSUE THREAD

**Issue by gregdasney** [Azure/azure-cli#14498]
The most recent version of the cli has deprecated this group.  Please update the documentation to reflect that.

```
$ az acr helm -h 
Group 
    az acr helm : Manage helm charts for Azure Container Registries.
        This command group has been deprecated and will be removed in future release. Use 'helm
        v3' instead. For more information go to https://docs.microsoft.com/en-us/azure/container-
        registry/container-registry-helm-repos
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bed94c3-b7a7-40d4-0102-8c9b1f1145ca
* Version Independent ID: 2d4ac8bd-dc7a-236c-56db-7f0e1ce0fd05
* Content: [az acr helm](https://docs.microsoft.com/en-us/cli/azure/acr/helm?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
acr

**Comment by yugangw-msft** [comment]
Done. https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos

**Comment by kinzleb** [comment]
Seemed like Microsoft was a little too hasty on deprecating this... I know it was a preview feature and all but the alternative to use Helm3's OCI experimental features like "helm chart save" and "helm chart push" are still far from mature... simple things like setting the chart's version and app-version require ugly workarounds... this unexpectedly took my development team out of commission for the whole day while I scrambled to fix our CI/CD pipelines.

**Comment by pbalexlear** [comment]
This seems like a very backwards step, we can currently authenticate using az cli using a service connection on pipelines and looking at the documentation it seems we will now have to resolve back to using an service principal and storing those credentials separately in devops? Given that it seems the helm 3 functionality to do this is only an experimental feature as well i would kindly ask that microsoft reconsider decommissioning these commands.

**Comment by petermicuch** [comment]
Seriously? We will have to export chart to be able to install it? What happened to simple `helm repo add test https://testrepo.azurecr.io/helm/v1/repo" and then installing anything that we had in that repository without the need to do any `helm chart pull` and `helm chart export`?
