### ISSUE TITLE
Az.Network for PrivateLink - Set-AzPrivateEndpointConnection, Dictionary Issue

### ISSUE THREAD

**Issue by cysecops** [Azure/azure-cli#14493]
Set-AzPrivateEndpointConnection -ResourceId <Nameofresourceid> -PrivateLinkServiceConnectionState "Approved"

Set-AzPrivateEndpointConnection: The given key 'Microsoft.Network/privateEndpoints' was not present in the dictionary.

AZ.network version 3.2.0

**Comment by yonzhan** [comment]
Please open this issue to PowerShell repo.
