### ISSUE TITLE
User with contributor permission to a resource group can create through CLI

### ISSUE THREAD

**Issue by kawayiboy** [Azure/azure-cli#14495]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
The user in his domain with only Support Request Contributor per subscription to be able to create custom IoT Central App in a designated resource group, where the user has Contributor role.  The customer cannot assign to his User a Contributor role on the Subscription, they can only do it at Resource Group level. 
 
Customer found that if the User runs AZ CLI command like following:

az iot central app create \
  --resource-group "csaez-iot-rg" \
  --name "csaeziotlab02" --subdomain "csaeziotlab02" \
  --sku ST1 --template "iotc-pnp-preview" \
  --display-name "My IOT LAB 02"

where user has Contributor Role on resource-group "csaez-iot-rg", it works fine and the iotC app is created.
If the same user tries to create the custom App using Azure Portal like following:

he gets a:
"You cannot create resources in this subscription without all of the following permissions:
Microsot.IoTCentral/IoTApps/write"

**To Reproduce**
az iot central app create \
  --resource-group "[resource group with only contributor permission]" \
  --name "csaeziotlab02" --subdomain "csaeziotlab02" \
  --sku ST1 --template "iotc-pnp-preview" \
  --display-name "My IOT LAB 02"

**Expected behavior**
it should throw following error:
"You cannot create resources in this subscription without all of the following permissions:
Microsot.IoTCentral/IoTApps/write"

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
iot

**Comment by jeevaeastpoint** [comment]
Any update on this one. I hit with the same issue but from the Azure portal. I have a couple of users who has Contributor access to a resource group and I expect that they should be able to create IoTCentral resources within this group.

**Comment by jeevaeastpoint** [comment]
> Any update on this one. I hit with the same issue but from the Azure portal. I have a couple of users who has Contributor access to a resource group and I expect that they should be able to create IoTCentral resources within this group.

Ignore this. I was going through the Microsoft documentation and it is explicitly specified that the user needs to have contributor at the subscription level. Refer [this](https://docs.microsoft.com/en-gb/azure/iot-central/core/quick-deploy-iot-central). So we have asked our admin to create it for us and all fine now...

**Comment by yonzhan** [comment]
Can we close this issue?

**Comment by vilit1** [comment]
Closing the issue due to no response. If you still need help with this issue, please re-open.
