### ISSUE TITLE
Azure CLI integration for Global Public load balancer

### ISSUE THREAD

**Issue by irenehua** [Azure/azure-cli#14496]
Is your feature request related to a problem? Please describe.
Global Public load balancer is a Standard SKU Global tier load balancer which has a global anycast IP and backend pool of Standard Regional load balancer.

Swagger:
https://github.com/Azure/azure-rest-api-specs/pull/10529

Describe the solution you'd like
CLI support for create/delete/configure global public load balancer.

**We need create a new command group** `az network cross-region-lb`

Describe alternatives you've considered
Need CLI support for Public Preview

Additional context
Please reach out to irenehua@microsoft.com for more context on the feature.

**Comment by yonzhan** [comment]
add to S174

**Comment by LexBurner97** [comment]
Yep! I just wanna add this issue! Pls tackle this issue as quickly as possible, really wanna to use CLI to manage Global Load Balancer on my Azure!

**Comment by yonzhan** [comment]
pending on service issue rollout
