### ISSUE TITLE
Struggling to assign policy to resource group with parameters. 

### ISSUE THREAD

**Issue by pquinton** [Azure/azure-cli#14501]
## Describe the bug

**Command Name**
`az policy assignment create`

**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
pip-install-yh2ypeu1\msrest\msrest\serialization.py, ln 1291, in _deserialize
pip-install-yh2ypeu1\msrest\msrest\serialization.py, ln 1081, in rest_key_case_insensitive_extractor
pip-install-yh2ypeu1\msrest\msrest\serialization.py, ln 1104, in attribute_key_case_insensitive_extractor
...
pip-install-yh2ypeu1\msrest\msrest\serialization.py, ln 1104, in attribute_key_case_insensitive_extractor
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az policy assignment create --display-name {} --policy {} --scope {} -p {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.9.1

```

**Comment by yonzhan** [comment]
add to S174

**Comment by zhoxing-ms** [comment]
@pquinton Hi, could you please show me the specific parameters you used? Please add `--debug` to the original command and email the printed information to me~
My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.
