### ISSUE TITLE
ssh directory created insecurely

### ISSUE THREAD

**Issue by jwilk** [Azure/azure-cli#14517]
The `generate_ssh_keys()` function does this:

```python
os.makedirs(ssh_dir)
os.chmod(ssh_dir, 0o700)
```

This is racy: between the directory creation and the `chmod()` call, the directory has default permissions.
Please use `os.makedirs(..., mode=0o700)` instead.

**Comment by yonzhan** [comment]
Please provide detailed command and error message if this is CLI related issue.
