### ISSUE TITLE
[App service]:Azure CLI  When creating appservice plan Parameter 'resource_group_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+[^\\.]$'.

### ISSUE THREAD

**Issue by sivakumarss** [Azure/azure-cli#14521]
## Describe the bug

**Command Name**
`az appservice plan create`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan create --name {} --resource-group {} --location {} --sku {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.9.1

```
## Additional Context

Actual issue is in "export".

Examples:
export RESOURCE_GROUP=l*************yuyt
export AZURE_REGION=centralus
export AZURE_APP_PLAN=apptest1-$RANDOM
export AZURE_WEB_APP=webtest-$RANDOM

When using the following command
az appservice plan create --name $AZURE_APP_PLAN --resource-group $RESOURCE_GROUP --location $AZURE_REGION --sku FREE

**Comment by yonzhan** [comment]
appservice

**Comment by panchagnula** [comment]
@sivakumarss can you share the name of he RG you were using here - since this error is from our API validation that says that the RG is not in the expected format. Thanks!

**Comment by sivakumarss** [comment]
I don't remember the Resource Group now.  It is used when developing app using Azure Sandbox environment.  
I resolved it by using Power shell.

**Comment by Kotasudhakarreddy** [comment]
@sivakumarss - closing this issue as we are unable to repro this. please reopen or rise new issue when you face it again.
