### ISSUE TITLE
az network application-gateway auth-cert show : clarification on certificate format

### ISSUE THREAD

**Issue by subhasishdc** [Azure/azure-cli#14522]
**Is your feature request related to a problem? Please describe.**
The authorization certificates of an application gateway can be found as follows:

`az network application-gateway auth-cert show -g test-rg --gateway-name test-aag --name test.com --query data`

Note: Argument values have been redacted to hide sensitive information

However, the certificate data is displayed in raw format. After trying around different options, I found that the certificate shown is base64 encoded CER certificate which was uploaded. To retrieve information from the certificate (like expiry date), the data needs to be base64 decoded first and then queried with openssl to retrieve the expiration date.

Example:

`$ az network application-gateway auth-cert show -g test-rg --gateway-name test-aag --name test.com --query data -o tsv | base64 --decode | openssl x509 -enddate -noout`
`notAfter=Jul 30 12:00:00 2020 GMT`

**Describe the solution you'd like**
It would be a good idea to add this as an example in the help message and documentation. It would be pretty helpful as without this information, it takes some effort to get the correct format and information. Please review this and provide guidance.

**Comment by yonzhan** [comment]
add to S174

**Comment by subhasishdc** [comment]
@haroldrandom : Did you get a chance to check this. Would it be a good idea to add an example to the help and documentation explaining the returning certificate type. If yes, I can help submit a PR for it.

**Comment by haroldrandom** [comment]
> @haroldrandom : Did you get a chance to check this. Would it be a good idea to add an example to the help and documentation explaining the returning certificate type. If yes, I can help submit a PR for it.

Yes. please :) . Appreciated in ahead for helping us to improve this, Thanks!

**Comment by subhasishdc** [comment]
@haroldrandom : Here is the PR to add the example to the help and documentation: https://github.com/Azure/azure-cli/pull/14856
