### ISSUE TITLE
[Interactive] AttributeError: module 'azext_interactive' has no attribute 'start_shell'

### ISSUE THREAD

**Issue by dmarinere** [Azure/azure-cli#14525]
## Describe the bug

**Command Name**
`az interactive`

**Errors:**
```
module 'azext_interactive' has no attribute 'start_shell'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 325, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 545, in default_command_handler
    return op(**command_args)
cli/command_modules/interactive/custom.py, ln 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
AttributeError: module 'azext_interactive' has no attribute 'start_shell'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Environment Summary
```
Linux-5.4.0-42-generic-x86_64-with-glibc2.29
Python 3.8.2
Installer: 

azure-cli 2.8.0 *

Extensions:
interactive Unknown

```

**Comment by yonzhan** [comment]
interactive

**Comment by dmarinere** [comment]
This is not a feature request @yonzhan it has worked before and it stopped working when I updated Python on my system

**Comment by jiasli** [comment]
May I know the result if you run `az version`? It should look like:

```
> az version
{
  "azure-cli": "2.9.10",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.9.10",
  "azure-cli-dev-tools": "0.1.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "azure-cli-testsdk": "0.2.4",
  "extensions": {
    "interactive": "0.4.4",  <<<<<
    "log-analytics": "0.2.1",
    "resource-graph": "1.1.0"
  }
}
```

`start_shell` is defined here, so it shouldn't be missing:

https://github.com/Azure/azure-cli-extensions/blob/a4ad9ba3ac419bed9065c6988a98fbb6b351b01c/src/interactive/azext_interactive/__init__.py#L9-L11

```py
def start_shell(cmd, style=None):
    from .azclishell.app import AzInteractiveShell
    AzInteractiveShell(cmd.cli_ctx, style)()
```

If the installation is somehow corrupted, could you run 

```
az extension remove --name interactive
az interactive
```

**Comment by dmarinere** [comment]
It didn't work still returned the same error

**Comment by jiasli** [comment]
May I know the result if you run `az version`?

**Comment by dmarinere** [comment]
I am using Ubuntu please, 
and here is the details of my Version
`{
  "azure-cli": "2.9.1",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.9.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}
`

**Comment by jiasli** [comment]
Could you check the content of `C:\Users\<username>\.azure\cliextensions\interactive\azext_interactive\__init__.py`? Does the folder or file exist?

**Comment by dmarinere** [comment]
I just said i am using Ubuntu which is a Linux distro 
Here is another error`The installed extension 'interactive' is in preview.
The command failed with an unexpected error. Here is the traceback:

No module named 'prompt_toolkit.interface'
Traceback (most recent call last):
  File "/home/mahveotm/.local/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/mahveotm/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/home/mahveotm/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/mahveotm/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/home/mahveotm/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/home/mahveotm/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/home/mahveotm/.local/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 779, in default_command_handler
    return op(**command_args)
  File "/home/mahveotm/.local/lib/python3.8/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/home/mahveotm/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "/home/mahveotm/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 33, in <module>
    from prompt_toolkit.interface import Application, CommandLineInterface
ModuleNotFoundError: No module named 'prompt_toolkit.interface'
`

**Comment by jiasli** [comment]
Sorry I missed the system, but the path should be similar: `/home/<username>/.azure/cliextensions/interactive/azext_interactive/__init__.py`.

Looks like you have bypassed the `AttributeError: module 'azext_interactive' has no attribute 'start_shell'` error? May I know the steps you used? There may be some installation or packaging issue. 

Let's handle `ModuleNotFoundError: No module named 'prompt_toolkit.interface'` in https://github.com/Azure/azure-cli/issues/14761.

**Comment by RakeshMohanMSFT** [comment]
This is fixed ModuleNotFoundError: No module named 'prompt_toolkit.interface' https://github.com/Azure/azure-cli/issues/24213
