### ISSUE TITLE
az vm boot-diagnostics commands update to support managed boot diagnostics  

### ISSUE THREAD

**Issue by avinashakka** [Azure/azure-cli#14539]
**Resource Provider**
- Compute Resource Provider (Microsoft.Compute)

**Description of Feature or Work Requested**
Starting api-version **2020-06-01**, CRP will support VMs with boot diagnostics using managed storage. Traditionally client was required to provide storageUri at **vm.properties.diagnosticsProfile.bootDiagnostics.storageUri**  while enabling boot diagnostics which was used internally by CRP to place the diagnostics log blobs.

But with new api-version: 2020-06-01, client can now enable boot diagnostics without specifying a storageUri which will be indication to CRP to use managed storage instead.

Sample profile for managed boot diagnostics
`
"diagnosticsProfile":
{
  "bootDiagnostics": {
    "enabled": "true"
  }
}
`
With managed boot diagnostics the change in behavior w.r.t boot diagnostics az-cli commands,
1. az vm boot-diagnostics disable: should be same as exists.
2. az vm boot-diagnostics enable: --storage should be optional
3.  az vm boot-diagnostics get-boot-log: If a VM is enabled with managed boot diagnostics, the blobUris will no longer be returned in instance-view (GetVM response) and instead [RetrieveBootDiagnosticsData POST API](https://github.com/Azure/azure-rest-api-specs/blob/ee068060cb90273a653e3964ffd9c69c6b2dc33b/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json#L3440) should be used to retrieve SAS URIs for the log blobs.

**Minimum API Version Required**
- 2020-06-01

**Swagger Link**
- API Specs: https://github.com/Azure/azure-rest-api-specs/blob/94ce88923f0cf7c7a415cc53db1edc4c500d8bea/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json#L8578
- Example: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/examples/CreateAVmWithManagedBootDiagnostics.json

**Target Date**
- Aug/Sep 2020

**Comment by yonzhan** [comment]
@qwordy  please take a look

**Comment by avinashakka** [comment]
> @qwordy please take a look

@qwordy Can you please close on this design.. the feature is already GA and customers are already exercising and seeing this missing support.

**Comment by qwordy** [comment]
>az vm boot-diagnostics disable: should be same as exists.
az vm boot-diagnostics enable: --storage should be optional

Very clear.

> az vm boot-diagnostics get-boot-log: If a VM is enabled with managed boot diagnostics, the blobUris will no longer be returned in instance-view (GetVM response) and instead RetrieveBootDiagnosticsData POST API should be used to retrieve SAS URIs for the log blobs.

I am reading related CLI code.

**Comment by qwordy** [comment]
Any idea about command name of this API?
`az vm boot-diagnostics retrive-data`?
```
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/retrieveBootDiagnosticsData
```
