### ISSUE TITLE
az network nic ip-config inbound-nat-rule remove failed with unexpected error

### ISSUE THREAD

**Issue by irenehua** [Azure/azure-cli#14536]
## Describe the bug

**Command Name**
`az network nic ip-config inbound-nat-rule remove`

**Errors:**
```
az network nic ip-config inbound-nat-rule remove: error: the following arguments are required: --resource-group/-g, --nic-name, --ip-config-name/-n, --inbound-nat-rule
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network nic ip-config inbound-nat-rule remove`

## Environment Summary
```
Linux-4.15.0-1091-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.9.0 *

```
## Additional Context

![image](https://user-images.githubusercontent.com/59070966/88574741-a3312480-cff7-11ea-9f23-4ec0168493fa.png)

**Comment by yonzhan** [comment]
add to S174

**Comment by MyronFanQiu** [comment]
@irenehua I will refine the error message later. Thanks! The reason for such error should be that you don't have any nat rules at all.

**Comment by brianlehr** [comment]
@MyronFanQiu @irenehua  But what is the solution for removing a nat pool using CLI?   I see there is a way [using Resource Explorer](https://ronaldwildenberg.com/azure/2018/02/09/remove-inbound-nat-rules-from-azure-vmss.html) but that's not what we want.

**Comment by irenehua** [comment]
@MyronFanQiu Thanks for fixing the error message! Problem is I do have NAT rules for the LB. 

![image](https://user-images.githubusercontent.com/59070966/89699045-55f76180-d8d9-11ea-9b34-3ec7a2c9b0d5.png)

And this is the command I used to remove the inbound NAT rule: az network nic ip-config inbound-nat-rule remove -g irenehua_vmssRuleDelete --nic-name vmss0807mjboxnic -n vmss0807mjboxipconfig --lb-name vmss0807mlb --inbound-nat-rule vmss0807mnatpool.1

Can we re-open the issue and find out why?

**Comment by MyronFanQiu** [comment]
> @MyronFanQiu Thanks for fixing the error message! Problem is I do have NAT rules for the LB.
> 
> ![image](https://user-images.githubusercontent.com/59070966/89699045-55f76180-d8d9-11ea-9b34-3ec7a2c9b0d5.png)
> 
> And this is the command I used to remove the inbound NAT rule: az network nic ip-config inbound-nat-rule remove -g irenehua_vmssRuleDelete --nic-name vmss0807mjboxnic -n vmss0807mjboxipconfig --lb-name vmss0807mlb --inbound-nat-rule vmss0807mnatpool.1
> 
> Can we re-open the issue and find out why?

I think `--inbound-nat-rule` should be an id instead of the name. You must provide `--lb-name` as well if you want to provide the name of the `--inbound-nat-rule`.

**Comment by MyronFanQiu** [comment]
> > @MyronFanQiu Thanks for fixing the error message! Problem is I do have NAT rules for the LB.
> > ![image](https://user-images.githubusercontent.com/59070966/89699045-55f76180-d8d9-11ea-9b34-3ec7a2c9b0d5.png)
> > And this is the command I used to remove the inbound NAT rule: az network nic ip-config inbound-nat-rule remove -g irenehua_vmssRuleDelete --nic-name vmss0807mjboxnic -n vmss0807mjboxipconfig --lb-name vmss0807mlb --inbound-nat-rule vmss0807mnatpool.1
> > Can we re-open the issue and find out why?
> 
> I think `--inbound-nat-rule` should be an id instead of the name. You must provide `--lb-name` as well if you want to provide the name of the `--inbound-nat-rule`.

But I saw you provided the lb's name. Is it the same lb used in this nic? What's the error message? Could you run this command with `--debug`

**Comment by MyronFanQiu** [comment]
close this one~
