### ISSUE TITLE
AZ CLI join command doesn't appear to work

### ISSUE THREAD

**Issue by ragnarwessels** [Azure/azure-cli#14545]
## Describe the bug
Trying to concatenate 2 files in ADLS Gen1 using the Azure CLI throws Python exception

**Command Name**
`az dls fs join`

**Errors:**
```
should_retry() takes 1 positional argument but 4 were given
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/datalake/store/core.py, ln 816, in concat
    retry_policy=NoRetryPolicy())
azure/datalake/store/lib.py, ln 429, in call
    if request_successful or not retry_policy.should_retry(response, last_exception, retry_count):
TypeError: should_retry() takes 1 positional argument but 4 were given
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`
- `az dls fs join --destination-path '/user/someuser/test_folder2' --source-paths '/user/someuser/test_folder/*.csv' --ids {REDACTED}`
- `az dls fs join --destination-path '/user/someuser/test_folder2' --source-paths '/user/someuser/test_folder/file1.csv /user/someuser/test_folder/file2.csv' --ids {REDACTED}`
- `az dls fs join --destination-path '/user/someuser/test_folder2/all.csv' --source-paths '/user/someuser/test_folder/file1.csv /user/someuser/test_folder/file2.csv' --ids {REDACTED}`

All versions of the command listed above fail with same error.

## Expected Behavior
Having a single concatenated file in test_folder2
## Environment Summary
Run from a Bastion connection on an Azure GPU machine (also replicates on locally installed AZ CLI)
```
Linux-5.3.0-1022-azure-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.80 *
azure-cli-ml 1.0.85

Extensions:
azure-cli-ml 1.0.85

```

**Comment by yonzhan** [comment]
add to S174

**Comment by Juliehzl** [comment]
SDK issue. Report here https://github.com/Azure/azure-data-lake-store-python/issues/314

**Comment by akharit** [comment]
The error and the fix in sdk was in retry code, which for concat is not supposed to retry anyway.
That code will only get triggered if there was an error in the first attempt itself. @ragnarwessels Can you run this with debug flag and check on what error occurred in the first attempt?

**Comment by Juliehzl** [comment]
Hi @akharit, it seems although there is sdk issue, the root cause should be error occurred during implementation, right?
Anyway I think we should upgrade the package version for sdk issue. Could you help take a look at my #14689?

**Comment by akharit** [comment]
@Juliehzl 
So this code did a concat operation, which failed for some reason. It went into the retry loop with policy NoRetryPolicy, which had a bug. The sdk fix only makes sure that the NoRetryPolicy is correct. I don't know why it failed on the first attempt. Could be anything from user error to server error. 

After sdk update, if this issue still occurs, we will get a better exception message that we can use to debug. So upgrade is good to have. I have approved the pull request.
