### ISSUE TITLE
Request to add new properties to Role Assignment objects and operations

### ISSUE THREAD

**Issue by dagoroz** [Azure/azure-cli#14552]
**Resource Provider**

Microsoft.Authorization

**Description of Feature or Work Requested**

Th properties "Condition", "Condition Version" and "Description" need to be added to the RoleAssignment request and response objects.
Additionally we require that a method to update role assignments is implemented, but limiting it to just those 3 new properties.

**Minimum API Version Required**

2020-04-01-preview

**Links**

Swagger: https://github.com/Azure/azure-rest-api-specs/pull/9971
PowerShell PR: https://github.com/Azure/azure-powershell/pull/12570

**Target Date**

Sep/08/2020 please note that this is a **JEDI requirement**

**Comment by yonzhan** [comment]
add to S174

**Comment by yonzhan** [comment]
this is part of JEDI M5 to help prioritization

**Comment by dagoroz** [comment]
@yonzhan Friendly follow up ping
