### ISSUE TITLE
Triggering only on a change to the contents of a github repo folder

### ISSUE THREAD

**Issue by A30004028** [Azure/azure-cli#14550]
Hi, 

I have my triggers setup to specify on branch and folder in a Github repo, but the ACR tasks are being triggered for changes to files outside of the specified folder.

Is it possible to only trigger on a push for the contents of the folder? Otherwise it looks like we can only have one task per repo.

In the example below I'd expect that a Task run only to occur when the contents of `task_folder` is changed.

```
   "sourceTriggers": [
      {
        "name": "defaultSourceTriggerName",
        "sourceRepository": {
          "branch": "master",
          "repositoryUrl": "https://github.com/A30004028/cloud.container.images.git#master:task_folder",
          "sourceControlAuthProperties": null,
          "sourceControlType": "Github"
        },
        "sourceTriggerEvents": [
          "commit"
        ],
        "status": "Enabled"
      }
    ],
```

Thanks
Mark

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0e3f3c-5aed-28b6-1e28-22ff32a8521d
* Version Independent ID: 128e5bc6-e518-bd5a-f511-48e0ed185739
* Content: [az acr task](https://docs.microsoft.com/en-us/cli/azure/acr/task?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
acr

**Comment by hkuadithya** [comment]
@northtyphoon could you take a look?

**Comment by northtyphoon** [comment]
@A30004028, ACR Tasks don't support folder filter. Please submit your request to http://aka.ms/acr/uservoice. /cc: @SteveLasker

**Comment by A30004028** [comment]
Thanks all - Will do. Cheers
