### ISSUE TITLE
CVE in python package dependency `invoke`

### ISSUE THREAD

**Issue by jtarchie** [Azure/azure-cli#14553]
## Describe the bug

There is a CVE in PyYAML that is vendored in `invoke` which Azure CLI installs.
This is a [cross post](https://github.com/pyinvoke/invoke/issues/747) of the issue on their repo.

**Command Name**
n/a

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-4.19.76-linuxkit-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9
Installer: PIP

azure-cli 2.8.0 *

```

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look

**Comment by fengzhou-msft** [comment]
`invoke` is introduced by `fabric`. The only place that `fabric` is used is [here](https://github.com/Azure/azure-cli/blob/e6e6a6d346f6e812ebe2f3892b56317424f13868/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L27) in `appservice`. Route to service team to see if the `fabric` package can be upraded or replaced.

**Comment by jtarchie** [comment]
Are there remaining action items here? I'm not familiar with the @msftbot actions and labels here.

**Comment by fengzhou-msft** [comment]
The command that uses `fabric` package is owned by App Service team and now we need their action to see if this can be improved.

**Comment by jtarchie** [comment]
Thank you for clarifying.

**Comment by btardif** [comment]
FYI @panchagnula not sure what the repair item is here, can you take a look?

**Comment by btardif** [comment]
@chenlomis can you help here I don't think this should be going to App Service, nothing for us to do here.

**Comment by fengzhou-msft** [comment]
@btardif the `fabric` library used by app service module in CLI introduced a CVE item. Please consider replacing it with `paramiko`.

**Comment by yungezz** [comment]
hi @btardif I'll add `service attention` label back. Detail of the issue is above as @fengzhou-msft mentioned. Feel free to ping us if any other issue.

**Comment by jtarchie** [comment]
I have to say, this is concerning.

We reported this issue in July.
As a security issue, even minor, the turn around time on is concerning.
Is there anything I can do to help expedite this?
Cause based on the github comment history, this is just a game of ping-pong. :-/

**Comment by panchagnula** [comment]
> @btardif the `fabric` library used by app service module in CLI introduced a CVE item. Please consider replacing it with `paramiko`.

@yungezz can you point us to the change or the package you are referring to - so we can take care of this. Thanks!

**Comment by yungezz** [comment]
> > @btardif the `fabric` library used by app service module in CLI introduced a CVE item. Please consider replacing it with `paramiko`.
> 
> @yungezz can you point us to the change or the package you are referring to - so we can take care of this. Thanks!

hi @fengzhou-msft could you pls share the detail?

**Comment by fengzhou-msft** [comment]
@panchagnula `fabric` is only used with `from fabric import Connection` and connection is then used for executing commands remotely. 
https://github.com/Azure/azure-cli/blob/85d96b07e386ffa56da5e96541b5caebee607a82/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L3968-L3993

The code can be replaced with similar code using `paramiko`:
https://github.com/Azure/azure-cli/blob/85d96b07e386ffa56da5e96541b5caebee607a82/src/azure-cli/azure/cli/command_modules/batchai/custom.py#L1068-L1073
