### ISSUE TITLE
Allow users to set `allowBlobPublicAccess` with a flag on `az storage account create`

### ISSUE THREAD

**Issue by bbkane** [Azure/azure-cli#14556]
**Is your feature request related to a problem? Please describe.**

My company recently changed security policy - All storage accounts created must have the `allowBlobPublicAccess` property ( https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=azure-cli ) disabled. However, I think this means it will be impossible for our engineers to use `az storage account create` to create storage accounts - we can't set that field on creation (that I know of, happy to be shown a counter example).

**Describe the solution you'd like**

Allow users to set `allowBlobPublicAccess` with a flag on `az storage account create`

**Describe alternatives you've considered**

Engineers can still:

- use the portal to create storage accounts (not as reproducible as saving a command and its output)
- Use the `az resource create` method to create storage accounts - much harder to find the right combination of flags and such

**Additional context**

This flag is visible in the "Configuration" sidebar when looking at a storage account in the Azure portal.

![image](https://user-images.githubusercontent.com/6081085/88740563-61d16f80-d0f2-11ea-87b5-2a655fb7629e.png)

**Comment by arrownj** [comment]
Hi @Juliehzl , could you please check with this issue ? Thanks

**Comment by yonzhan** [comment]
add to S174

**Comment by Juliehzl** [comment]
Done in https://github.com/Azure/azure-cli/pull/14422
