### ISSUE TITLE
az group command not working

### ISSUE THREAD

**Issue by meghachauhan0392** [Azure/azure-cli#14561]
## Describe the bug

**Command Name**
`az group list`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group list`

## Environment Summary
```
Linux-4.15.0-1091-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.9.0 *

```

**Comment by yonzhan** [comment]
add to S174

**Comment by meghachauhan0392** [comment]
Issue has been solved
