### ISSUE TITLE
Deploy python written functions with the CLI

### ISSUE THREAD

**Issue by nestor-qhr** [Azure/azure-cli#14562]
## Describe the bug
I tried to deploy functions from a zip file into an existing function app  

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.8/site-packages/six.py, ln 703, in reraise
    raise value
...
lib/python3.8/json/__init__.py, ln 357, in loads
    return _default_decoder.decode(s)
lib/python3.8/json/decoder.py, ln 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.8/json/decoder.py, ln 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

I only ran the following command on the terminal:
- `az functionapp deployment source config-zip -g <resource_group> -n \<app_name> --src <zip_file_path>`

## Expected Behavior
I was hoping to see the functions deployed in my function app

## Environment Summary
```
macOS-10.15.5-x86_64-i386-64bit
Python 3.8.5
Installer: HOMEBREW

azure-cli 2.9.1

```

**Comment by yonzhan** [comment]
functionapp

**Comment by nestor-qhr** [comment]
It works now. I fixed my deploy of the App Service, that I did through Terraform: turns out I didn't specify that I wanted Python to be the `FUNCTIONS_WORKER_RUNTIME` in my app service resource. **I just tried to deploy and I had no issues** 👍  thank you for your time!
