### ISSUE TITLE
az image builder create 

### ISSUE THREAD

**Issue by danielsollondon** [Azure/azure-cli#14575]
**Describe the bug**
az image builder create does not contain the vmProfile config properties:
        "vmProfile": 
            {
            "vmSize": "<vmSize>",
            "osDiskSizeGB": <sizeInGB>,
            "vnetConfig": {
                "subnetId": "/subscriptions/<subscriptionID>/resourceGroups/<vnetRgName>/providers/Microsoft.Network/virtualNetworks/<vnetName>/subnets/<subnetName>"
                }

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-json?toc=/azure/virtual-machines/windows/toc.json&bc=/azure/virtual-machines/windows/breadcrumb/toc.json

**To Reproduce**
These are required to support key customer functionality, and customers have asked for this to be made available. 

Please can these configuration properties be added to match AZ PowerShell. thanks!

**Comment by arrownj** [comment]
Hi @qwordy , could you please help with this issue ? Thanks

**Comment by qwordy** [comment]
It is not supported yet. Added to S174. You can use --image-template as a workaround.
