### ISSUE TITLE
Webapp:az webapp deleted restore needs always the slot parameter to succeed, otherwise returns "not found"

### ISSUE THREAD

**Issue by IgnacioAlvarezArenas** [Azure/azure-cli#14573]
az webapp deleted restore command instruction seems to be wrong. If you run it without specifying the slot, it seems to be failed with something like:

az webapp deleted restore --deleted-id "yourdeletedid" -g yourresourcegroup --name yourappname --subscription yoursubscriptionID

The error is:

ResourceNotFound - The Resource 'Microsoft.Web/sites/yourapp' under resource group 'yourresourcegroup' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

Apparently to make it working, even for the main slot (let's call it production) we need to specify the slot:
az webapp deleted restore -g yourresourcegorup -n yourappname -s production -deleted-id "deletedidofyourapp"

Can you please verify it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b299a5-3666-dfe3-a61f-3b367286f781
* Version Independent ID: 9805327e-e088-fa01-7cd9-ad5120e2841a
* Content: [az webapp deleted](https://docs.microsoft.com/en-us/cli/azure/webapp/deleted?view=azure-cli-latest#az-webapp-deleted-restore)
* Content Source: [latest/docs-ref-autogen/webapp/deleted.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/deleted.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by btardif** [comment]
@gsethgit can you help take a look? can we get one of the backup devs to help?

**Comment by ThejaChoudary** [comment]
Able to repro the issue.Will look into this

**Comment by IgnacioAlvarezArenas** [comment]
is there any update on this? It seemed we started to get some progress but it all stopped :).

**Comment by vkarasala** [comment]
Same as https://github.com/Azure/azure-cli/issues/16689
