### ISSUE TITLE
Initiatives Misspelled in Tree

### ISSUE THREAD

**Issue by JohnKeippel** [Azure/azure-cli#14578]
On this [page](https://docs.microsoft.com/en-us/cli/azure/policy/set-definition?view=azure-cli-latest) the parent of this Overview page in the tree structure on the left misspells Initiatives as "Initiatves".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe29c90-ab37-174c-3365-d33044447272
* Version Independent ID: 3118d6a2-bb53-a881-0017-0313a15c9ef1
* Content: [az policy set-definition](https://docs.microsoft.com/en-us/cli/azure/policy/set-definition?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arrownj** [comment]
Hi @zhoxing-ms , could you please help with this issue ? Thanks

**Comment by zhoxing-ms** [comment]
This is a document related problem.
@daxianji007 Could you please help to have a look~

**Comment by Skovvart** [comment]
Think the typo should be fixed by https://github.com/MicrosoftDocs/azure-docs-cli/pull/2450 / https://github.com/MicrosoftDocs/azure-docs-cli/pull/2451

**Comment by navba-MSFT** [comment]
@JohnKeippel Apologies for the late reply. This issue is open for quite sometime. Could you please let us know if you still need any further assistance on this issue ? Awaiting your reply.

**Comment by JohnKeippel** [comment]
Looks like this wording was removed last year so this issue can be closed. Thanks.
