### ISSUE TITLE
incorrect command for http redirect?

### ISSUE THREAD

**Issue by DPatrickBoyd** [Azure/azure-cli#14582]
az cdn endpoint rule add -g group -n ep --profile-name name --order 1 --rule-name "http-redirect" --match-variable RequestScheme --operator Equal --match-values HTTPS --action-name "UrlRedirect" --redirect-protocol Https --redirect-type
 Moved

This appears to be redirecting https to https? I think the match-values should be HTTP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fef54fc4-b4a8-d366-40de-a0ae2586961d
* Version Independent ID: 1231852d-d3b4-9bcf-e9d4-ba12cffb7603
* Content: [az cdn endpoint rule](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint/rule?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/cdn/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cdn/_help.py)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arrownj** [comment]
Hi @DPatrickBoyd , thanks for reporting, we will look at it.
