### ISSUE TITLE
Webapp:Multiple bugs - `az webapp config appsettings set` command

### ISSUE THREAD

**Issue by flyingUnderTheRadar** [Azure/azure-cli#14580]
Facing two problems

- `az webapp config appsettings set -g $ResourceGroupName -n "app-name" --settings SettingKey=$SettingValue SettingKey2=$SettingValue2` does not work even though the settings are space separated, it errors out. If it is set as a string it puts all of it in the one config setting (with the "()" for keyvault reference. This is relevant for the next problem.)
- `az webapp config appsettings set -g $ResourceGroupName -n "app-name" --settings SettingKey=$SettingValue` - Does not work properly if the `$SettingValue` is a keyvault reference. It sets the value in the web app but omits the last ')' causing it to not be a valid keyvault reference string.

I know this is an avenue is for page feed back, but please let me know who I can get in touch with to resolve this issue on the product itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* Content: [az webapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by flyingUnderTheRadar** [comment]
Service attention and for webapp

**Comment by calvinsID** [comment]
@flyingUnderTheRadar Can you try putting quotations around your settings like so: `--settings 'SettingKey=$SettingValue' 'SettingKey2=$SettingValue2'` and let me know if the problem still persists

**Comment by flyingUnderTheRadar** [comment]
Appreciate your response. Ended doing doing something different. Don't have it set up to test anymore.

However just for others I ended up having to use powershell like this to make it work

```
$ConnectionStringKVReference = '"@Microsoft.KeyVault(SecretUri={0})"' -f $StorageSecret
$ApplicationInsightsKeyKVReference = '"@Microsoft.KeyVault(SecretUri={0})"' -f $AppInsightsSecret

az webapp config appsettings set -g $ResourceGroupName -n $WebAppName `
    --settings StorageConnectionString=$ConnectionStringKVReference APPINSIGHTS_INSTRUMENTATIONKEY=$ApplicationInsightsKeyKVReference
```

**Comment by alexdrenea** [comment]
> @flyingUnderTheRadar Can you try putting quotations around your settings like so: `--settings 'SettingKey=$SettingValue' 'SettingKey2=$SettingValue2'` and let me know if the problem still persists

I know this is a pretty old issue, but I can confirm your solution worked for me. 
I feel this is good enough to close this ticket, however, I also believe some extra documentation or example should be added on the main page on how to achieve this. (specifically, I think setting a KeyVault Reference as an app setting is a valid and common scenario)

**Comment by anmalkov** [comment]
> **Correction:** I know this is a pretty old issue, but this solution doesn't work actually... When you single quote, the $settingValue doesn't get resolved any more.

This is what works for me:
```
--settings DB_PASS='"@Microsoft.KeyVault(VaultName='$kv';SecretName=DbPassword)"'
```
