### ISSUE TITLE
azure network vpn-gateway create giving an unclear error

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#1458]
Tried to add a GW using the following command

 aanandr@AANANDR-WORK:/mnt/c/Windows/System32$ az network vpn-gateway create --name VNet2GW --public-ip-address VNet2GWPubIP --resource-group VV2 --subnet-id GatewaySubnet

Getting the following error. Its difficult to understand the cause of the problem. It seems to be about the format used to specify the Gateway Subnet but the msg. doesnt give any useful guidance

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "InvalidJsonReferenceFormat",
        "message": "Reference Id GatewaySubnet is not formatted correctly. The Id is expected to reference resources of type virtualNetworks/subnets. Path properties.ipConfigurations[0].properties.subnet."
      }
    ]
  }
}  Correlation ID: 40dc667e-5ccc-4deb-a51a-8850d9a4f282

**Comment by tjprescott** [comment]
This is the error from the server, but it is correct. 
**Reference Id GatewaySubnet is not formatted correctly**

--subnet-id requires a fully qualified ID. You cannot use a name.
