### ISSUE TITLE
[az webapp up] if --name parameter is not provided we should auto generate one.

### ISSUE THREAD

**Issue by btardif** [Azure/azure-cli#14583]
We should do similar logic to how static webapps auto generates the cname for a SWA

for example: zealous-tree-06c552e1e --> *adjective*-*noun*-shortguid

This is related to Python worklod review issue: [Issue 1457](https://azuretracking.visualstudio.com/Azure%20tracking/_workitems/edit/1457?src=WorkItemMention&src-action=artifact_link): [az webapp up] Make name optional, generate random name if left blank

**Comment by panchagnula** [comment]
@arrownj  yep - we discussed this recently in a scrum. Adding tentative milestone

**Comment by btardif** [comment]
@calvinsID @panchagnula is this happening this sprint? This is a e2e tracked bug and I need to provide an update

**Comment by panchagnula** [comment]
@btardif  not this sprint with high- confidence so I would update the timeline to next sprint. Sorry didn't provide an update earlier.

**Comment by btardif** [comment]
Ok @panchagnula updated ETA for 12/31
