### ISSUE TITLE
Operation failed with status: 'Conflict'. Details: There is an import or export operation in progress on the database 

### ISSUE THREAD

**Issue by yene** [Azure/azure-cli#14590]
We are doing a DB copy `az sql db copy` followed by an export `az sql db export`, which is prevented with the error:

```
Operation failed with status: 'Conflict'. Details: There is an import or export operation in progress on the database XXX
```

It seems the copy operation is still going on in the  background.
Where can we see ongoing copy/export operations? (azcli, portal, api)

**Comment by yonzhan** [comment]
sql
