### ISSUE TITLE
Metadata key-value pairs get set incorrectly on policy definition creation

### ISSUE THREAD

**Issue by zsombor-adn** [Azure/azure-cli#14591]
**Describe the bug**
When providing multiple metadata key=value pairs on policy definition creation, every pair after the first one gets appended to the first pair's key.

**To Reproduce**
```bash
params='{ "listOfAllowedLocations": { "allowedValues": null, "defaultValue": null, "metadata": { "description": "The list of locations that can be specified when deploying resources.", "displayName": "Allowed locations", "strongType": "location" }, "type": "Array" } }'

rules=$(cat << 'HEREDOC'
{ "if": { "allOf": [ { "field": "location", "notIn": "[parameters('listOfAllowedLocations')]" }, { "field": "location", "notEquals": "global" }, { "field": "type", "notEquals": "Microsoft.AzureActisveDirectory/b2cDirectories" } ] }, "then": { "effect": "deny" } }
HEREDOC
)

az policy definition create --name az-bug-report-2020-07-30 --rules "$rules" --params "$params" --metadata 'version=1.0.0 category=location'
```

The created policy has the second key-value pair (`category=location`) added to the first pair's value (`version=1.0.0 category=location`) instead of being under a new key. Here's the created policy:

```json
{
  "description": null,
  "displayName": null,
  "id": "/subscriptions/REDACTED/providers/Microsoft.Authorization/policyDefinitions/az-bug-report-2020-07-30",
  "metadata": {
    "createdBy": "REDACTED",
    "createdOn": "2020-07-30T10:30:41.6720972Z",
    "updatedBy": null,
    "updatedOn": null,
    "version": "1.0.0 category=location"
  },
 ...
```

**Expected behavior**
Metadata pairs created separately, like:

```json
{
  "description": null,
  "displayName": null,
  "id": "/subscriptions/REDACTED/providers/Microsoft.Authorization/policyDefinitions/az-bug-report-2020-07-30",
  "metadata": {
    "createdBy": "REDACTED",
    "createdOn": "2020-07-30T10:30:41.6720972Z",
    "updatedBy": null,
    "updatedOn": null,
    "version": "1.0.0",
    "category": "location"
  },
 ...
```

**Environment summary**

Installed from [official RPM](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest), shell is Bash.

```bash
az --version
azure-cli                          2.9.1

command-modules-nspkg              2.0.3
core                               2.9.1
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/bin/python3'
Extensions directory '/home/REDACTED/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Sep 26 2019, 11:57:09) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Additional context**
According to the [documentation](https://docs.microsoft.com/en-us/cli/azure/policy/definition?view=azure-cli-latest#az-policy-definition-create-optional-parameters), metadata shall be set as `space-separated key=value pairs`

**Comment by yonzhan** [comment]
add to S174

**Comment by zhoxing-ms** [comment]
@zsombor-adn In fact, it is a question of quoting usage:
> If the value contains whitespace, you must wrap it in quotes.

The usage guide for quotes: [link](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively?view=azure-cli-latest#quoting-issues
)


For your question, there is a few specific examples:

1. `--metadata 'version=1.0.0 category=location'` this represents the metadata contain white spaces.
```pwsh
"metadata": {
    "version": "1.0.0 category=location"
}
```


2. `--metadata version=1.0.0 category=location` or `--metadata 'version=1.0.0' 'category=location'` this represents two metadata separated by a white space.
```pwsh
"metadata": {
    "version": "1.0.0",
    "category": "location"
}
```

If you still have any other questions, please feel free to let us know~

**Comment by zsombor-adn** [comment]
Thank you very much for the detailed reply @zhoxing-ms!

I can confirm doing it the way you describe works. Maybe it'd be worth a mention in the command's docs though, as supplying an argument list like this is quite unusual amongst *nix tools.

**Comment by ishangajera-crest** [comment]
It didn't work for me with --metadata 'version=1.0.0' 'category=location' but it works with --metadata version=1.0.0 category=location

**Comment by zhoxing-ms** [comment]
@ishangajera-crest Could you please tell me in what environment(`linux`, `mac`, `windows`) and what terminal(`CMD`, `PowerShell`, `WSL`...) you execute the command?

If it is convenient, please add parameter `--debug` to the original command, and then send the printed information to me by email
My email address is Zhou.Xing@microsoft.com, thanks~
