### ISSUE TITLE
Accessing createdTime info under az resource list

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#14598]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Unable to access info under the createdTime attribute

**To Reproduce**
"So I have been tasked with creating some cleanup scripts for our testing account.  I ran the az resource list and realize there is a createdTime attribute, but they are all null.  Is this something that is being added and just not used?  Is there a flag to get access to that info?  That would be a really great way combine that with createdBy.  You could easily do some automated hey you have these 5 resources over 2 weeks old are they still in use if not please clean them up or they will be cleaned on x day.  Then you could auto delete and use the cli to export to a template and send it to them.  I tried the Get-AzResource and it does not appear to have a created time attribute."

**Expected behavior**
"I have ideas/options that I could do, but I am more intrigued by if the createdTime is something coming out or in preview, or something that goes against the YAGNI Principal (You ain't gonna need it). "

**Environment summary**

**Additional context**

**Comment by tikicoder** [comment]
Since this ticket was created on my behalf please let me know if you have questions.

**Comment by yonzhan** [comment]
add to S174
