### ISSUE TITLE
az network bastion - hangs on powershell

### ISSUE THREAD

**Issue by klemenberti** [Azure/azure-cli#14592]
**Describe the bug**
'az network bastion create' when used with powershell hangs. The bastion was created, but console locks until ctrl+c, then all powershell commands output turns black.

**To Reproduce**
On powershell:
az network bastion create -g group -n bastion --vnet-name AzureBastionSubnet --public-ip-address  bastionIP

**Expected behavior**
Create bastion and exit to prompt.

**Environment summary**
azure-cli 2.9.1
command-modules-nspkg 2.0.3
core 2.9.1
nspkg 3.0.4
telemetry 1.0.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

PSVersion 5.1.19041.1

MSI - Windows 10 Powershell

**Additional context**
Same behaviour with different output, even '-o none'.

**Comment by yonzhan** [comment]
add to S174

**Comment by MyronFanQiu** [comment]
@klemenberti Hey. Usually this issue would be a service issue. To double confirm this one, could you run the command with `--debug` to see whether the response is always `InProgress`?

**Comment by klemenberti** [comment]
@MyronFanQiu Hello. I tried --debug and could not replicate any problem.
I has able to replicate the console black text output with any bastion subset commands, this behaviour occour when running inside parentheses (az network bastion list -g group), not big issue though.
Sorry for misleading bug report, we may close this until i can provide a consistent sample.
