### ISSUE TITLE
Webapp:`az webapp vnet-integration add` fails when the App Service Plan is not in its original resource group

### ISSUE THREAD

**Issue by krispenner** [Azure/azure-cli#14597]
This is a reincarnation of #12629 which I believe was incorrectly closed as a duplicate when it is not. Commenting on the closed issue is not getting any attention so I am re-creating it.

**Describe the bug**
Move an app service and its app service plan to a new resource group and you can no longer use the `az webapp vnet-integration` commands. This seems to be a common and frustrating recurring theme with app services in general - they don't work well if you move them out of their original resource group which their webspace is tied to. I only have the one app service plan and it is already connected to the vnet through other app services, there are no other app services plans connected to the vnet. Using the Azure Portal also does not work.

**Command**
az webapp vnet-integration add --resource-group GroupNEW --name AppService1 --vnet Vnet1 --subnet Subnet1

**Error**
Operation returned an invalid status code 'Conflict'

**Debug details**
Subnet Subnet1 in VNET Vnet1 is already occupied by service /subscriptions/123/resourceGroups/GroupOLD/providers/Microsoft.Web/serverfarms/AppServicePlan1.

**To Reproduce**
1. Move an app service and its app service plan to a new resource group.
1. Try to use the `az webapp vnet-integration add` command on it.
1. Error: Operation returned an invalid status code 'Conflict'

**Expected behavior**
Success

**Workaround**
1. Move the App Service Plan back to a resource group named the same as the original it was created in.
1. Connect the vnet.
1. You can then move it back to the new group if required.

**Comment by yonzhan** [comment]
webapp

**Comment by dkubi** [comment]
If you delete a resourcegroup with an webapp/appserviceplan with vnetintegration you get the same error in case you want to reuse the vnet for a new created webapp

**Comment by ThejaChoudary** [comment]
Thanks for reporting, we'll look at it

**Comment by farflungfish** [comment]
Hello, I have met this issue today, any update on this?

**Comment by harsh-arora-by** [comment]
Any update on this?

**Comment by madsd** [comment]
Issue was fixed a while ago. Sorry for not notifying and closing this issue sooner. I tested variations of moving plan/app to different resource group and connecting to vnet in same and different resource group - all worked as expected. Let us know if there is a scenario that we missed.
