### ISSUE TITLE
az acr network-rule add tries to apply all rules

### ISSUE THREAD

**Issue by sam-cogan** [Azure/azure-cli#14596]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When running "az acr network-rule add " to create a network rule for a subnet , it appears to attempt to re-apply all existing rules as well as the one you are adding. This results in an error if the user running this does not have permissions on the vnets that the existing rules apply to.

**To Reproduce**
Create a subnet based network rule on an ACR repo, using an account that does not have permissions on that vNet try and add another rule

**Expected behavior**
Only the new rule is added, existing rules are left alone

**Environment summary**
Azure CLI running on PowerShell Core

**Additional context**

**Comment by yonzhan** [comment]
acr

**Comment by yugangw-msft** [comment]
@sam-cogan while we investigate this, have you considered Private Endpoint which is in GA, and we are recommend it more over the service endpoint

**Comment by sam-cogan** [comment]
@yugangw-msft ideally I would use Private link, but it has a couple of issues:
1. The limit of 10 connections to ACR, I will have more than this
2. The DNS part is a pain, each environment we are connecting to ACR has a different DNS setup and so trying to automate this is painful, using service endpoints is much simpler

**Comment by yugangw-msft** [comment]
@sam-cogan, sorry for the delay on response
1. On connection limits, will vnet peering an option for you, which you can share the same endpoint across several vnets?
2. Is it feasible for you to share the detail on #2. In the nushell, DNS record for private endpoint is manageable (2 records, unless you have replication), though I would not call it very trivial. 

For context, we don't have plan for more investment on service endpoint, as private endpoint offers better vnet isolation end to end wise including on-premise. But we don't want to leave existing users behind, hence I am asking what more is needed for users to migrate.

**Comment by sam-cogan** [comment]
@yugangw-msft I have started working with Private endpoints, and am mostly there. Are there plans to increase the limit of 10 endpoints any time soon? Most of the vNets I need to talk to ACR are isolated single vNets where peering is not suitable.

I've mostly worked around all the DNS issues except 1, which is dealing with a scenario where you have two peered networks, using BYO DNS (in this case Windows DNS) where you want a private endpoint in both vNets for HA. In this scenario I am struggling because the shared DNS scenario means we can only really have a private endpoint in 1 region.

**Comment by yugangw-msft** [comment]
@sam-cogan, I am reaching out to domain experts on the DNS issue and will get back to you soon

On increasing the limit, it is a feature in our backlog, I suggest you create a voice at https://feedback.azure.com/forums/903958-azure-container-registry and we will prioritize once its get enough votes.

**Comment by yugangw-msft** [comment]
@sam-cogan, there is no need to deploy multiple PE for HA; or it won't help.

**Comment by sam-cogan** [comment]
@yugangw-msft how does that help in a multi region setup? If you have multiple vNets peered you need service endpoints in each region, otherwise if the region with the PE goes down you loose all connectivity.

**Comment by yugangw-msft** [comment]
@sam-cogan, sorry for the delay, yes your point is correct. Since we are at it, does your solution require 10+ region replicates?

**Comment by yugangw-msft** [comment]
The reason I am asking for the replication topology is if a region is down, through PE in other regions (even peered), you can pull from other healthy regions. Of course with limits at 10, you can't have a PE in each region, but 10 regions all simultaneously down is much less likely

**Comment by lissff** [comment]
@yugangw-msft  any update for this issue?
"when running "az acr network-rule add " to create a network rule for a subnet , it appears to attempt to re-apply all existing rules as well as the one you are adding."
we encountered the same issue here, do we plan a fix or workaround?

**Comment by navba-MSFT** [comment]
@sam-cogan Apologies for the late reply. This issue is open for quite sometime now. Please let us know if you are still looking for assistance on this issue ? Awaiting your reply.
