### ISSUE TITLE
the command "az security contact list" not show security contact created on security center azure portal

### ISSUE THREAD

**Issue by jose-lima2011** [Azure/azure-cli#14594]
Hello guys, in my settings I verified that the security email registration page has changed, there is no longer the phone field, in addition to other changes, but what is curious is that the email that I register in the field is not displayed with the command az security contact list even in preview worked, now only if I create the security contact via command az security contact create -n "default1" --email 'john@contoso.com' given as an example on the page, is distorted if the that I register on the portal without the command actually works. the problem path is security center> pricing & settings> email notifications, since the command is not effective nor via rest api which command in az cli can i check if the configuration exists? Thank you !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5e41eed-b0f8-4533-6da2-10411cfd6468
* Version Independent ID: a6c27983-1feb-9c11-c675-6305e1e6c8a4
* Content: [az security contact](https://docs.microsoft.com/en-us/cli/azure/security/contact?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/security/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/security/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
security

**Comment by yonzhan** [comment]
@ariklin @chnachmani to help with.

**Comment by ariklin** [comment]
@eliagrady, please advise.

**Comment by jose-lima2011** [comment]
> Hello guys, in my settings I verified that the security email registration page has changed, there is no longer the phone field, in addition to other changes, but what is curious is that the email that I register in the field is not displayed with the command az security contact list even in preview worked, now only if I create the security contact via command az security contact create -n "default1" --email '[john@contoso.com](mailto:john@contoso.com)' given as an example on the page, is distorted if the that I register on the portal without the command actually works. the problem path is security center> pricing & settings> email notifications, since the command is not effective nor via rest api which command in az cli can i check if the configuration exists? Thank you !
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: b5e41eed-b0f8-4533-6da2-10411cfd6468
> * Version Independent ID: a6c27983-1feb-9c11-c675-6305e1e6c8a4
> * Content: [az security contact](https://docs.microsoft.com/en-us/cli/azure/security/contact?view=azure-cli-latest)
> * Content Source: [src/azure-cli/azure/cli/command_modules/security/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/security/_help.py)
> * GitHub Login: @rloutlaw
> * Microsoft Alias: **routlaw**

Hello guys, any news? As it is something that is not widely used, it may fall by the wayside, but as my job is to audit security compliance, I cannot ignore this item, thank you.
