### ISSUE TITLE
Should be able to create a VMSS-VMO without a PPG; PPG optional

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#14602]
## Describe the bug

**Command Name**
`az vmss create`

**Errors:**
```
Deployment failed. Correlation ID: 29bca5e8-ab6f-4398-af30-408286e13c9e. {
  "error": {
    "code": "InvalidParameter",
    "message": "Required parameter 'proximityPlacementGroup.id' is missing (null).",
    "target": "proximityPlacementGroup.id"
  }
}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss create -n {} -g {} -l {} --orchestration-mode {} --platform-fault-domain-count {}`

## Expected Behavior
Should be able to omit the ppg parameter and create a VMO. PPG is optional, however currently required by CLI

## Environment Summary
```
Linux-5.4.0-1022-azure-x86_64-with-glibc2.29
Python 3.8.2
Installer: PIP

azure-cli 2.9.1

```

**Comment by yungezz** [comment]
issue fixed.
