### ISSUE TITLE
how to export key from key vault?

### ISSUE THREAD

**Issue by LudoNieuw** [Azure/azure-cli#14608]
hi there, 

I'm looking for a way to export my keys from azure key vault tye 'key' but I cannot find how to do it anywhere. Please spcify, as I need my key local to run some commands. To be clear, I need the private key I uploaded to the key vault earlier. 

Regards,

Ludo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0f363b-7f21-0ea9-3e27-da7866c94102
* Version Independent ID: 6cc413e4-4f7d-9baa-a365-c9275fc6a7ad
* Content: [az keyvault key](https://docs.microsoft.com/en-us/cli/azure/keyvault/key?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by yungezz** [comment]
hi @LudoNieuw could you pls try `az keyvault key download` command? doc  here: https://docs.microsoft.com/en-us/cli/azure/keyvault/key?view=azure-cli-latest#az-keyvault-key-download
let us know if any other issue met

**Comment by bim-msft** [comment]
Hi @LudoNieuw Private keys cannot be exported in the current version. If you want to use your private key to encrypt or decrypt data, you may use `az keyvault key encrypt/decrypt`, it will access the private key internally to avoid data exposing.

**Comment by bim-msft** [comment]
`az keyvault key download` can only download the public part.
