### ISSUE TITLE
Private Python packages for remote build

### ISSUE THREAD

**Issue by zuckerruebe** [Azure/azure-cli#14609]
**Is your feature request related to a problem? Please describe.**
We have an internal PyPI index to which we deploy private packages that we'd then like to pip install into our Python Azure function. Because our packaging index is not reachable from the Azure cloud we've so far opted for `--build local`. However, this has turned out to be a bit fragile as a couple of times now after adding new dependencies we get errors like these:

`There was an error restoring dependencies. ERROR: cannot install pyrsistent-0.16.0 dependency: binary dependencies without wheels are not supported when building locally. Use the "--build remote" option to build dependencies on the Azure Functions build server, or "--build-native-deps" option to automatically build and configure the dependencies using a Docker container. More information at https://aka.ms/func-python-publish`

**Describe the solution you'd like**
Hence I was wondering whether it isn't possible to first pip install our couple private packages on our CI runner into a magic folder and have that folder uploaded to Azure to be considered in an otherwise standard remote build - or something along those lines.

**Describe alternatives you've considered**
I'd rather not get into the `--build-native-deps` option if I can avoid it as the CI runners we're using aren't under our control and I don't know how straight-forward it would be to have them configured for `--build-native-deps`.

**Comment by yonzhan** [comment]
@fengzhou-msft  please take a look

**Comment by zuckerruebe** [comment]
I've only just found this:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#install-local-packages

This is pretty much exactly what I need. Sorry for the trouble, I guess the issue can be closed now.
