### ISSUE TITLE
AZ AD query command fails or produces NO results.

### ISSUE THREAD

**Issue by scott-dunt** [Azure/azure-cli#14600]
## Describe the bug

**Command Name**
`az ad user list --query "sort_by([[].mail, [].objectId])"

**Errors:**
```
Expected 2 arguments for function sort_by(), received 1
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 666, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_FILTER_RESULT, event_data=event_data)
python3.6/site-packages/knack/cl96e6i.py, ln 164, in raise_event
    func(self, **kwargs)
...
python3.6/site-packages/jmespath/functions.py, ln 80, in call_function
    self._validate_arguments(resolved_args, signature, function_name)
python3.6/site-packages/jmespath/functions.py, ln 90, in _validate_arguments
    len(signature), len(args), function_name)
jmespath.exceptions.ArityError: Expected 2 arguments for function sort_by(), received 1
```

## To Reproduce:
az ad user list --query "sort_by([[].mail, [].objectId])" -o tsv

## Expected Behavior
az ad user list will NOT return selected values on a single line.
Running: az ad user list --query '[[].mail, [].objectId]' -o tsv

returns a list of user's email addresses followed by a list of object ids:

will.frank@XXXXXXXX.com	wendy.streitmatter@XXXXXXXXX.com	zmiller@XXXXXXXXXX.com
XXXXXXXX-XXXX-XXXX-XXXX-686e3f9dab80	XXXXXXXX-XXXX-XXXX-XXXX-e1ad124ea3e7	XXXXXXXX-XXXX-XXXX-XXXX-a3e69db4d217

and trying to force it to sort that return blows up.

How does one create an AD report of user and object ID for example.
## Environment Summary
```
Linux-5.4.0-42-generic-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.9.1

```

**Comment by yonzhan** [comment]
@arrownj please take a look

**Comment by arrownj** [comment]
Hi @scott-dunt , please reference [JMSPath document](https://jmespath.org/proposals/exptype.html?highlight=sort_by#sort-by) to write the `sort-by` expression. In general, just as the error message shows, the `sort-by` function takes 2 parameters.

**Comment by arrownj** [comment]
Close this first since it's a JSMPath usage problem.
