### ISSUE TITLE
replace API from Azure AD Graph API to Microsoft Graph REST API for `az ad` commands

### ISSUE THREAD

**Issue by skmkzyk** [Azure/azure-cli#14617]
**Is your feature request related to a problem? Please describe.**

Currently, `az ad sp create-for-rbac` seems using Azure AD Graph API.

```
msrest.http_logger : Request URL: 'https://graph.windows.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/servicePrincipals?$filter=servicePrincipalNames%2Fany%28x%3Ax%20eq%20%27http%3A%2F%2FmyAKSClusterServicePrincipal%27%29&api-version=1.6'
```

As the article like [this](https://developer.microsoft.com/en-us/office/blogs/microsoft-graph-or-azure-ad-graph/) recommends migration from Azure AD Graph to Microsoft Graph, `az ad` commands need to be migrated to new.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
add to S174

**Comment by jiasli** [comment]
Thanks for the feedback. This request is being tracked at https://github.com/Azure/azure-cli/issues/12946.
