### ISSUE TITLE
Azure CLI: Typo in az keyvault secret set.

### ISSUE THREAD

**Issue by plooploops** [Azure/azure-cli#14616]
## Describe the bug

**Command Name**
`az keyvault secret set`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault secret set -n {} --value {} --vault-name {}`

## Expected Behavior
"kind" is spelled correctly in json output instead of "kid".
![image](https://user-images.githubusercontent.com/2498998/89089628-18338f80-d353-11ea-9946-6b5537bd846e.png)

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.9.1

```

**Comment by yonzhan** [comment]
@bim-msft please take a look

**Comment by bim-msft** [comment]
@plooploops Thanks for reaching out. Actually it's not a type: here `kid` represents `If this is a secret backing a KV certificate, then this field specifies the corresponding key backing the KV certificate.`.
https://docs.microsoft.com/en-us/rest/api/keyvault/setsecret/setsecret#secretbundle

**Comment by bim-msft** [comment]
For normal (non-certificate related) secrets, this field is useless.

**Comment by plooploops** [comment]
@bim-msft Thank you for the clarification and the link to the docs.  Looks like it's expected behavior then!

**Comment by bim-msft** [comment]
Anyway, thank you for your feedback! :-)
