### ISSUE TITLE
[AppService] Test failure

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#14623]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

```
FAILED src\azure-cli\azure\cli\command_modules\appservice\tests\latest\test_webapp_commands.py::WebappImplictIdentityTest::test_webapp_assign_user_identity
FAILED src\azure-cli\azure\cli\command_modules\appservice\tests\latest\test_webapp_commands.py::WebappImplictIdentityTest::test_webapp_remove_identity
FAILED src\azure-cli\azure\cli\command_modules\appservice\tests\latest\test_webapp_commands.py::WebappWindowsContainerBasicE2ETest::test_webapp_create_with_msi
```
These three test cases cannot pass.
Open this issue to track it.

Error
```
knack.util.CLIError: Name clitest.rg3hdo26ksbqcrbem7cwwqll4z2p5pyv26gwhroglddmnbyz5v4prss6snz4laex5aq is not valid.
```

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yungezz** [comment]
hi @panchagnula could you pls help to look at the issue? Currently Azure CLI CI blocked by the test failure. one example failure: https://dev.azure.com/azure-sdk/public/_build/results?buildId=479772&view=logs&j=771f6cdf-8d98-5d9b-2fb9-d3a6e9554788&t=0a182f1d-9946-580d-467e-4d4ebd6af32d&l=6534

**Comment by panchagnula** [comment]
@cxznmhdcxz looks like the new tests you added are failing in CLI? can you take a look please and fix the test or add a new recording? Thanks!

**Comment by cxznmhdcxz** [comment]
Three test methods that raises:
1. `test_webapp_assign_user_identity` 
2. `test_webapp_remove_identity`
3. `test_webapp_create_with_msi`

For the first and second one, I could reproduce the same error in live mode (different random name though of course), and could pass live/record mode after a small fix.

However for the third one, I could pass either live/record mode.
Still looking into it. But any information or step to reproduce a same error would be appreciated.

**Comment by panchagnula** [comment]
@calvinsID can you check if on the latest Dev you are able to repro these tests failing as well?

**Comment by calvinsID** [comment]
I got the same results as @cxznmhdcxz. Test `test_webapp_assign_user_identity` and `test_webapp_remove_identity` pass live with the change: `@ResourceGroupPreparer(name_prefix="clitest", random_name_length=24)`, while I was unable to repro error on test `test_webapp_create_with_msi` - it passes live without any changes for me

**Comment by colbylwilliams** [comment]
I started seeing this error in [our extension's CI](https://github.com/microsoft/TeamCloud/runs/956782209?check_suite_focus=true#step:13:295) when attempting to deploy an ARM template since the last release (2.10.1).

**Comment by btardif** [comment]
This is fixed
