### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by tikicoder** [Azure/azure-cli#14632]
The link https://docs.microsoft.com/rest/api/keyvault/certificates-and-policies does not appear to be valid when I goto it it redirects to https://docs.microsoft.com/en-us/azure/key-vault/

I tried to find a new doc, but was unsure where it should go.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9c661d7-bf43-5354-015e-3859f30a42a2
* Version Independent ID: fa69e552-5904-ce97-d02c-915c819bdde1
* Content: [az keyvault certificate](https://docs.microsoft.com/en-us/cli/azure/keyvault/certificate?view=azure-cli-latest&source=docs#az-keyvault-certificate-get-default-policy)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
keyvault

**Comment by yungezz** [comment]
hi @bim-msft could  you pls help to update the link? seems service side changed the link. thanks
