### ISSUE TITLE
Mandatory parameters for az keyvault secret set not correct

### ISSUE THREAD

**Issue by uandrei** [Azure/azure-cli#14630]
az keyvault secret set has the value as required parameter and at the moment the documentation page shows it as optional.

![image](https://user-images.githubusercontent.com/11975434/89214937-a01dd180-d5bf-11ea-963d-81b0a1a8a135.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39cfb8ed-c246-2ffb-9dff-070b90c18b21
* Version Independent ID: c09c1597-1b6c-b0a2-b3fc-bdc16764d096
* Content: [az keyvault secret](https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az-keyvault-secret-set)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
keyvault

**Comment by yungezz** [comment]
hi @bim-msft could  you pls help to check if the required property set correctly in help.py? thanks

**Comment by bim-msft** [comment]
Hi @uandrei `--value` is not required since you can use `--file` instead. So we mark both `--value` and `--file` optional and do the check at runtime.

**Comment by bim-msft** [comment]
Closing this one due to long-time inactivity.
