### ISSUE TITLE
Output cannot be formatted to table - when listing objects and using --query

### ISSUE THREAD

**Issue by Shahar-do** [Azure/azure-cli#14634]
Hello, I'm working with webapps, vms, and other objects throguh CLI,
I am able to query those objects, rename columns, etc,
but when I use --query - I am unable to eventually display the output as table.
I have followed this documentation page - https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest step by step.

**Describe the bug**
I am running those commands, for example:
- `az vm list -g {} --query {}`
- `az webapp list -g {} --query {}`

Works just fine - returns the expected json result.

But when I run them with `-o table` at the end, like this:
- `az vm list -g {} --query {} -o table`
- `az webapp list -g {} --query {} -o table`

Error is thrown:
`Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.`

**To Reproduce**
Run commands such as:
- `az vm list -g {} --query {}`
- `az webapp list -g {} --query {}`
Validate that those are working.

Then, run those commands again with `-o table` at the end of the line.

**Environment summary**

Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI
Extensions:
interactive 0.4.4

Update (8/4/20, 10:30) update: Tried on two other windows 10 workstations with differenet cli version and issue is reproduced just the same.

**Additional context**
1. I am using interactive mode.
2. I updated both azure-cli and interactive mode 10 mintues ago, and it didn't help.
3. Issue reproduced and error just the same in azure cloud shell.
4. In addition, I would like to let you know that I googled the issue and saw few github posts in which the issue have already been reported. I did not find any appropriate solution in any of those posts.
5. Update (8/4/20, 10:30):  This issue has been opened 3 days ago - https://github.com/Azure/azure-cli/issues/14615.
In my intuition, according to the similarity of the issues it really seems like the problem is not client-specific, nor version-specific, and not object-specific.

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look?

**Comment by jiasli** [comment]
I am not able to reproduce it. The result is correct. 

```
> az vm list -g ubuntu-rg --query [].name --output table
Result
-------------
my-ubuntu
```

Would you mind sharing the actual commands you used? (Provide the contents of `{}` in the commands.)

**Comment by Shahar-do** [comment]
> I am not able to reproduce it. The result is correct.
> 
> ```
> > az vm list -g ubuntu-rg --query [].name --output table
> Result
> -------------
> my-ubuntu
> ```
> 
> Would you mind sharing the actual commands you used? (Provide the contents of `{}` in the commands.)

Hey, please take a look at these two examples:

![image](https://user-images.githubusercontent.com/38504703/90227661-9d23ac00-de1d-11ea-9c35-bb8f09d95dfa.png)

![image](https://user-images.githubusercontent.com/38504703/90227783-ce03e100-de1d-11ea-9b4f-f374942a126c.png)

**Comment by jiasli** [comment]
I see you are using `interactive`. Unfortunately, currently `interactive` doesn't work with `--output table`. You may use the normal CLI to execute those commands. 

Thanks for your understanding.

**Comment by Shahar-do** [comment]
Thank you for this comment.
I would like to point out that the error "Table output unavailable. Use the --query option to specify..."
Is extremely confusing, and it sure does not say that this feature is simply unavailable in interactive mode.
Should I open another bug about it? or open a feature request?

**Comment by jiasli** [comment]
@Shahar-do, thanks for the feedback. However, `az interactive` is not being actively maintained. We would recommend always using the normal `az` commands.
