### ISSUE TITLE
Webapp:az webapp create - doesn't support using managed identity creds for ACR pulls

### ISSUE THREAD

**Issue by aklopfer** [Azure/azure-cli#14631]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

az webapp create doesn't have arguments to support using managed identity creds for ACR pulls (linux)

**To Reproduce**

n/a: there are not options to specify a managed identity for acr pulls
docs are here (they don't work): https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image#configure-app-service-to-deploy-the-image-from-the-registry

**Expected behavior**

az webapp create -UseMiCredsWithAcr [true/false] -UserMiCredsForAcr [user managed identity client id]
(or something similar)

**Environment summary**

**Additional context**

3 situations: Not using Managed Identity Creds for ACR pulls, Using system MI creds for ACR pulls, Using user MI creds for ACR pulls

Not using Managed Identity Creds for ACR pulls) AcrUseManagedIdentityCreds:False; AcrUserManagedIdentityID:null
 
Using system MI creds for ACR pulls) AcrUseManagedIdentityCreds:True; AcrUserManagedIdentityID:null

Using user MI creds for ACR pulls) AcrUseManagedIdentityCreds:True; AcrUserManagedIdentityID:"{UserManagedIdentity.ClientId}"
*the specific clientID of the Managed Identity the customer wished to be used

*In both cases (system or user MI), a customer use the Identity tab to add a Managed Identity for this to work
*In both cases, a customer must grant this Identity ARCPull permissions to the Azure  Container Repo

**Comment by panchagnula** [comment]
In order to work on this request we need to make sure we have this change in the SDK https://github.com/Azure/azure-rest-api-specs/pull/10215

**Comment by panchagnula** [comment]
@btardif  can you review the command new arguments proposal so based on that we can work on implementation.

**Comment by panchagnula** [comment]
@calvinsID this needs the new SDK for Python, i am working on that but something might need to be done for Ignite release. No action needed right away.

**Comment by jvano** [comment]
Please make sure you test against Windows Containers on App Service as the backend support for pulling with MSI is also ready

**Comment by btardif** [comment]
We don't support setting this up through create, but this can be done after the resource already exists, here is documentation:

- [How to use system-assigned Managed Identities with App Service and Azure Container Registry](https://github.com/Azure/app-service-linux-docs/blob/master/HowTo/use_system-assigned_managed_identities.md)
- [How to use user-assigned Managed Identities with App Service and Azure Container Registry](https://github.com/Azure/app-service-linux-docs/blob/master/HowTo/use_user-assigned_managed_identities.md)

**Comment by peter-bertok** [comment]
This issue shouldn't closed, and App Service shouldn't have ordinary properties that are "runtime writeable only" mixed in with ARM-compatible properties.

**Comment by egoward** [comment]
Is DoesacrUseManagedIdentityCreds actually supported?
