### ISSUE TITLE
[Compute] Support dedicated host group in VMSS

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#14637]
**Resource Provider**

Compute

**Description of Feature or Work Requested**

Support dedicated host group in VMSS

```
"hostGroup": {
          "$ref": "#/definitions/SubResource",
          "description": "Specifies information about the dedicated host group that the virtual machine scale set resides in. <br><br>Minimum api-version: 2020-06-01."
        },
```

**Minimum API Version Required**

2020-06-01

**Swagger Link**

**Target Date**

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14056

**Comment by qwordy** [comment]
It is already supported.
