### ISSUE TITLE
az aks scale fails with "The value of parameter imageReference.version is invalid"

### ISSUE THREAD

**Issue by dineshsharmads** [Azure/azure-cli#14635]
## Describe the bug

Following command fails to scale the windows node pool. However, scaling operation from the portal succeeds.

AKS Version: 1.16.10
Windows Nodepool Version: 1.16.10

**Command**
`az aks scale -g <cluster-rg> -n <clustername> --node-count 2 --nodepool-name <windows node pool> --debug`

**Errors:**
```
Operation failed with status: 'Bad Request'. Details: Provisioning of resource(s) for container service <clustername> in resource group <clustername-rg> failed. Message: Resource 'aksf3aa10e1-0cb9-4505-9b0b-6cf5e8f049ba' has invalid parameters. Details: The value of parameter imageReference.version is invalid.. Details:
```

## To Reproduce:
Deploy an AKS cluster version 1.16.10 using portal 
Add a windows nodepool with one node
Scale with above command

## Expected Behavior
The nodepool should scale to 2 nodes

## Environment Summary
```
AKS Version: 1.16.10
Windows Nodepool Version: 1.16.10

CLI details:
Linux-4.15.0-1092-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.9.0 *

```

**Comment by yonzhan** [comment]
aks

**Comment by TomGeske** [comment]
@dineshsharmads: please, open a support ticket with us.

cc: @keikhara

**Comment by dineshsharmads** [comment]
Thanks @TomGeske 
I have opened a support case.

**Comment by dineshsharmads** [comment]
Turns out this is a known CLI issue and fix is ready and pending deployment.
To work around the issue, you may use az aks nodepool scale, same as the API used by Azure portal.
