### ISSUE TITLE
Cannot import a bacpac into an existing non-empty db. Need to clarify that.

### ISSUE THREAD

**Issue by diego-pomatta** [Azure/azure-cli#14646]
Change "**Imports a bacpac into an existing database**" to  "**Imports a bacpac into a new database, or an existing empty database.**"
**Reason:** You cannot import a bacpac into an existing non-blank database. The above description has confused customers and caused several support incidents to be open.

If you attempt to import a bacpac to an existing -non empty- database you get this error:

**Operation failed with status: 'Bad Request'. Details: There was an error that occurred during this operation : '<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">Error encountered during the service operation. ; Exception Microsoft.SqlServer.Management.Dac.Services.ServiceException:Target database is not empty. The import operation can only be performed on an empty database.; </string>'**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bdd674-b454-e863-c943-9c979b466a92
* Version Independent ID: b15341f9-3f1b-00e0-a1c2-970f25a6ab03
* Content: [az sql db](https://docs.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#az-sql-db-import)
* Content Source: [src/azure-cli/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
sql
