### ISSUE TITLE
functionapp: Remove support to create PowerShell 6.2 function apps

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-cli#14649]
**Description**
Remove support to create PowerShell 6.2 function apps

cc: @gzuber @eamonoreilly @anirudhgarg @anthonychu @stefanushinardi

**Comment by yonzhan** [comment]
functionapp

**Comment by pragnagopa** [comment]
@gzuber - any update on this?

**Comment by kamperiadis** [comment]
Closing as this is no longer relevant since we rely on the stacks API to determine if a runtime is still supported and do not allow customers to create the function app if that is not the case.
