### ISSUE TITLE
Example needed or explain syntax for using multiple (not in the same range) IPs with generate-sas and parameter --IP

### ISSUE THREAD

**Issue by simon-michaud** [Azure/azure-cli#14647]
There is no example or explanation for the syntax when entering mutliple IPs for the generate-sas with --IP option, please provide one or more.

Thanks,

Simon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S174
