### ISSUE TITLE
az aks Ingress Controller add-on(Greenfield) documented "create" command giving error

### ISSUE THREAD

**Issue by bennya1** [Azure/azure-cli#14644]
## Describe the bug
Following the documentation* to create APPGW Greenfield the default command provided below error

* https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-new#deploy-an-aks-cluster-with-the-add-on-enabled

**Command Name**
`az aks create`

**Errors:**
```
unrecognized kwargs: ['is_preview']
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 482, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 276, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
...
cli/core/commands/parameters.py, ln 341, in _merge_kwargs
    return merge_kwargs(kwargs, base, CLI_PARAM_KWARGS)
cli/core/commands/__init__.py, ln 964, in _merge_kwargs
    raise TypeError('unrecognized kwargs: {}'.format(unrecognized_kwargs))
TypeError: unrecognized kwargs: ['is_preview']
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create -n {} -g {} --network-plugin {} --enable-managed-identity -a {} --appgw-name {} --appgw-subnet-prefix {}`

## Environment Summary
```
Linux-4.15.0-112-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.65 *

Extensions:
aks-preview 0.4.58

```

**Comment by yonzhan** [comment]
aks

**Comment by TomGeske** [comment]
This is related to Application Gateway

cc: @mscatyao

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
