### ISSUE TITLE
Include a simple way of getting into a development environment

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1465]
In my projects, I include a `devenv.sh` script that uses a docker container and a shared volume including the source directory that makes it incredibly painless for new users to make contributions.

If the `RUN` commands in the `Dockerfile` were externalized into a `./build.sh` script, then the `Dockerfile` could be used to the build the development container, and can still be used to do point in time builds of source code by running it with `docker build -t az-devenv .; docker run -v $(pwd):/az-cli -it az-devenv bash ./build.sh`.

That will allow the actual enlistment to override the source that was added with `ADD` in the `Dockerfile`.

Doing this would allow me to type `./devenv.sh` and get a fully working development environment, instead of spending a non-trivial amount of time trying to get Python and pythonpath and whatnot to be configured correctly.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
