### ISSUE TITLE
[Keyvault] MHSM control plane support

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#14658]
**Is your feature request related to a problem? Please describe.**

Keyvault

**Describe the solution you'd like**

Support for keyvault MHSM control plane.
Swagger link: https://github.com/Azure/azure-rest-api-specs/pull/8996
service spec: https://nam06.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Aw%3A%2Ft%2FAzureKeyVault-SDKPSHCLICollaboration%2FETixR_Vb365Al7UzP3UVKp0B8IoJweHfwxB5JcbFdTeL7g%3Fe%3DhTN8YC&data=02%7C01%7Cyungez%40microsoft.com%7C44614276ef8644ca097108d828df162d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637304285920269125&sdata=UvVMcHfHtS4ed82GUVNBK5PS2FJQ878O2I%2BkHyxvY6s%3D&reserved=0

**Describe alternatives you've considered**

**Additional context**

Part of MHSM feature. public at Ignite.

**Comment by yungezz** [comment]
@bim-msft has provided private package for service team testing.

**Comment by bim-msft** [comment]
PR merged.
