### ISSUE TITLE
az storage account create command line option

### ISSUE THREAD

**Issue by manojk011** [Azure/azure-cli#14651]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
```az storage account create``` command does not expose any command line option "--allow-blob-public-access" as mentioned in the documentation.
https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az-storage-account-create

**Additional context**
I have been trying to look up for the az cli versions which can support it but even the latest version 2.10.0 does not support it.

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @manojk011, could you check if you installed `storage-preview` extension with `az extension list`?

**Comment by manojk011** [comment]
Yes I did.
```
azure-cli                          2.9.1 *

command-modules-nspkg              2.0.3
core                               2.9.1 *
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
datafactory                        0.1.0
storage-preview                   0.2.10

```

**Comment by Juliehzl** [comment]
Hi @manojk011, currently you could use `az storage fs access`  in main cli and extension related commands will be migrated to main repo. See here for usage https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/docs/ADLS%20Gen2.md, which could also help you manage ADLS Gen2 command.

**Comment by manojk011** [comment]
Thank you @Juliehzl.
