### ISSUE TITLE
detaching NSG from subnet does not work

### ISSUE THREAD

**Issue by soulcoolzz** [Azure/azure-cli#14665]
[Enter feedback here]

Doc under "az network vnet subnet update" says that: 

"--network-security-group --nsg
Name or ID of a network security group (NSG). Use empty string "" to detach it."

But when I use empty string, it does not work and output ERROR like below: 

"
PS /home/lub> az network vnet subnet update -n frontendSubnet --vnet-name MyVirtualNetwork -g TestResourceGroup --nsg $myNSG
az network vnet subnet update: error: argument --network-security-group/--nsg: expected one argument
"

Could you please to correct this and let us know the right cmd to detach NSG from subnet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 385e420c-4bd0-3ddd-d9cd-a9a411ec1f7b
* Version Independent ID: 65172372-f485-3d2b-64aa-57c38ac11538
* Content: [az network vnet subnet](https://docs.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S174

**Comment by MyronFanQiu** [comment]
@soulcoolzz Are you using PS? Please try `--network-security-group "''"`.

**Comment by soulcoolzz** [comment]
> @soulcoolzz Are you using PS? Please try `--network-security-group "''"`.

I tried but still not work. It recognize '' as nsg name.

"
PS /home/lub> az network vnet subnet update -n frontendSubnet --vnet-name MyVirtualNetwork -g TestResourceGroup --network-security-group "''"
Resource /subscriptions/915860b1-5ad3-49a1-954a-488b33e60dde/resourceGroups/TESTRESOURCEGROUP/providers/Microsoft.Network/networkSecurityGroups/'' referenced by resource /subscriptions/915860b1-5ad3-49a1-954a-488b33e60dde/resourceGroups/TestResourceGroup/providers/Microsoft.Network/virtualNetworks/MyVirtualNetwork/subnets/frontendSubnet was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.
"

**Comment by MyronFanQiu** [comment]
@soulcoolzz Yes. it will be treated as a name and we have code path to detach it. The error message told us that the subnet's name is not correct. Subnet `frontendSubnet` doesn't exist.

**Comment by MyronFanQiu** [comment]
@soulcoolzz Hi. Any updates about this issue?

**Comment by soulcoolzz** [comment]
@MyronFanQiu 

The error message should be a mistake, because the subnet frontendSubnet does really exist.

You can refer to below log which I just tested:

PS /home/lub> az network vnet subnet show -n frontendSubnet --vnet-name MyVirtualNetwork -g TestResourceGroup
{
  "addressPrefix": "10.0.1.0/24",
  "addressPrefixes": null,
  "delegations": [],
  "etag": "W/\"5a748212-4f6c-45ec-b206-cd98be194e34\"",
  "id": "/subscriptions/915860b1-5ad3-49a1-954a-488b33e60dde/resourceGroups/TestResourceGroup/providers/Microsoft.Network/virtualNetworks/MyVirtualNetwork/subnets/frontendSubnet",
  "ipAllocations": null,
  "ipConfigurationProfiles": null,
  "ipConfigurations": null,
  "name": "frontendSubnet",
  "natGateway": null,
  "networkSecurityGroup": {
    "defaultSecurityRules": null,
    "etag": null,
    "flowLogs": null,
    "id": "/subscriptions/915860b1-5ad3-49a1-954a-488b33e60dde/resourceGroups/TestResourceGroup/providers/Microsoft.Network/networkSecurityGroups/MyVirtualNetwork-NSG-CASG",
    "location": null,
    "name": null,
    "networkInterfaces": null,
    "provisioningState": null,
    "resourceGroup": "TestResourceGroup",
    "resourceGuid": null,
    "securityRules": null,
    "subnets": null,
    "tags": null,
    "type": null
  },
  "privateEndpointNetworkPolicies": "Enabled",
  "privateEndpoints": null,
  "privateLinkServiceNetworkPolicies": "Enabled",
  "provisioningState": "Succeeded",
  "purpose": null,
  "resourceGroup": "TestResourceGroup",
  "resourceNavigationLinks": null,
  "routeTable": null,
  "serviceAssociationLinks": null,
  "serviceEndpointPolicies": null,
  "serviceEndpoints": [],
  "type": "Microsoft.Network/virtualNetworks/subnets"
}
PS /home/lub>
PS /home/lub>
PS /home/lub> az network vnet subnet update -n frontendSubnet --vnet-name MyVirtualNetwork -g TestResourceGroup  --network-security-group "''"
Resource /subscriptions/915860b1-5ad3-49a1-954a-488b33e60dde/resourceGroups/TESTRESOURCEGROUP/providers/Microsoft.Network/networkSecurityGroups/'' referenced by resource /subscriptions/915860b1-5ad3-49a1-954a-488b33e60dde/resourceGroups/TestResourceGroup/providers/Microsoft.Network/virtualNetworks/MyVirtualNetwork/subnets/frontendSubnet was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.
PS /home/lub>

**Comment by MyronFanQiu** [comment]
Well. Looks like powershell is doing something magically. Please use `az network vnet subnet update -g cli2020 --vnet-name dsfsd -n sdfsdfsdf --nsg '""'` to detach it. Sorry about the inconvenience.

**Comment by MyronFanQiu** [comment]
@soulcoolzz Please let me know whether it works for you and is there any more issue.
