### ISSUE TITLE
--host-names  not working with FQDN list.

### ISSUE THREAD

**Issue by johnmeister** [Azure/azure-cli#14674]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
running preview command --host-names is not allowing multiple FQDN's to be uploaded

**To Reproduce**

command ran is 
`az network application-gateway http-listener update -g MyGroup--gateway-name MyGateway -n myListenerSecure --host-names www.mywebsite.com,mywebsite.com --verbose --debug `

error message returned:
"HostName www.mywebsite.com,mywebsite.com is not a FQDN for Http Listener..."

**Expected behavior**

I would expect the the http-listener be updated with the two host names

**Environment summary**

 az version
{
  "azure-cli": "2.10.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.10.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "interactive": "0.4.3"
  }
}
windows 10

**Additional context**

Running 
`az network application-gateway http-listener update -g MyGroup--gateway-name MyGateway -n myListenerSecure --host-names www.mywebsite.com --verbose --debug `

works and properly adds the single host name to the host-names list and running

`az network application-gateway http-listener update -g MyGroup--gateway-name MyGateway -n myListenerSecure --host-names mywebsite.com --verbose --debug `

updates properly but still wont add multiple hosts

changed resource group , gateway name and URLS for business privacy

**Comment by yonzhan** [comment]
add to S174

**Comment by BenMitchell1979** [comment]
Is this a bug? Following the documentation on **https://docs.microsoft.com/en-us/powershell/module/az.network/add-azapplicationgatewayhttplistener?view=azps-4.6.1** and getting the same issue using Powershell.

**Comment by haroldrandom** [comment]
I believe the correct usage format is 
`az network application-gateway http-listener update -g harold --gateway appgw1 -n appGatewayHttpListener --host-names www.example.com www.example2.com`

It's supposed to be `Space-separated list of host names that allows special wildcard characters as well `. We will update it for clearness.
