### ISSUE TITLE
Kubectl installation fails in WSL due to Python 3.6 SSL certificate error

### ISSUE THREAD

**Issue by hirezeli** [Azure/azure-cli#14670]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
Traceback (most recent call last):
lib/python3.6/urllib/request.py, ln 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
lib/python3.6/http/client.py, ln 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
lib/python3.6/http/client.py, ln 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
...
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)


lib/python3.6/urllib/request.py, ln 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Update Windows 10 to version 2004
- Install WSL and reboot
- Update WSL to version 2 and reboot
- Install Windows Terminal from Windows Store
- Install WSL Ubuntu 20.04 LTS from Windows store
- Using Windows Terminal to access WSL Ubuntu, use az login and authenticate successfully
- run `az aks install-cli`

## Expected Behavior
kubectl is installed correctly

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.10.0

```

**Comment by yonzhan** [comment]
aks

**Comment by navba-MSFT** [comment]
@hirezeli Apologies for the late reply. Could you please check if there is a proxy in your environment ? Would you be able to test this on another environment which is in a different network and let us know if you are still facing the issue ? This issue is open for quite sometime. Please let us know if you still need any assistance on this. Awaiting your reply.
