### ISSUE TITLE
Mixed resource group and account name in command "az ams streaming-endpoint show"

### ISSUE THREAD

**Issue by meteor688** [Azure/azure-cli#14687]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.9.1

**Describe the bug**
Mixed resource group and account name in "az ams streaming-endpoint show"

**To Reproduce**
Run command _az ams streaming-endpoint show -g MediaServicesQuickTest -a testmediaaccount8 -n 'default'_ , but the resource group and account name was mixed in the ourput as below shown.
_The Resource 'Microsoft.Media/mediaServices/**MediaServicesQuickTest**/streamingEndpoints/default' under resource group '**testmediaaccount8**' was not found._

**Expected behavior**
show the right output. 

**Environment summary**
az version                                                                                                                                                                  {
  **"azure-cli": "2.9.1",**
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.9.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}

**Additional context**

**Comment by yonzhan** [comment]
ams

**Comment by hivyas** [comment]
Hi there, thanks for reporting this. I have opened bug 8272644 on our team and we will be fixing this very shortly. Thank you!
