### ISSUE TITLE
[Appservice]: access-restriction remove by ip address does not work since the ip address check

### ISSUE THREAD

**Issue by cboudereau** [Azure/azure-cli#14684]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Before this version it was possible to remove an access-restriction by ip address. After the version checking duplicates over ip address the remove by ip address is not working anymore. And I think the problem is related to that pull request : https://github.com/Azure/azure-cli/commit/2b78c06b2d32cd9461e1b1545e065c7430365674#diff-5091ef8c5edecc1ae2c3ffd1896ff7d2R195. Maybe @Kotasudhakarreddy can help on this

**To Reproduce**
Repro Step:

```
> az functionapp config access-restriction add -g XXX -n XXX --ip-address 40.114.193.214/32 --priority 200 --rule-name "Azure 1"

> az functionapp config access-restriction remove -g XXX -n XXX --ip-address 40.114.193.214/32

Command group 'functionapp config access-restriction' is in preview. It may be changed/removed in a future release.

IP address 40.114.193.214/32 already exists.Cannot add duplicate IP address values.
```

The error message : "IP address 40.114.193.214/32 already exists.Cannot add duplicate IP address values" is not relevant in case of deletion. I have this problem since the last docker pull and I know that it was possible to have duplicate in previous version. 

**Expected behavior**
Same output when deleting by name : 

```
> az functionapp config access-restriction remove -g XXX -n XXX --rule-name "Azure 1"
Command group 'functionapp config access-restriction' is in preview. It may be changed/removed in a future release.

[
  {
    "action": "Allow",
    "description": null,
    "ipAddress": "104.40.254.139/32",
    "name": "Azure 6",
    "priority": 200,
    "subnetMask": null,
    "subnetTrafficTag": null,
    "tag": "Default",
    "vnetSubnetResourceId": null,
    "vnetTrafficTag": null
  },
  {
    "action": "Deny",
    "description": "Deny all access",
    "ipAddress": "Any",
    "name": "Deny all",
    "priority": 2147483647,
    "subnetMask": null,
    "subnetTrafficTag": null,
    "tag": null,
    "vnetSubnetResourceId": null,
    "vnetTrafficTag": null
  }
]
```

**Environment summary**
Env:
docker linux container on windows :
```
REPOSITORY                                                   TAG                 IMAGE ID            CREATED             SIZE
mcr.microsoft.com/azure-cli                                  latest              55a65eee1172        5 days ago          681MB
```

```
 az version
{
  "azure-cli": "2.10.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.10.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}```

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by Kotasudhakarreddy** [comment]
Looking in to it.

**Comment by Kotasudhakarreddy** [comment]
able to repro the issue. sorry for inconvenience. Will give the fix in next release.

**Comment by cboudereau** [comment]
Hi, don't worry, at least the add command will not add duplicates anymore.

Having idempotent commands could help a little bit more instead of detecting duplicates but that could be another feature request..

Thanks in advance for the work done 🥇
