### ISSUE TITLE
az eventhubs eventhub create fails with Event Hub names longer than 50 characters

### ISSUE THREAD

**Issue by ianblitz** [Azure/azure-cli#14698]
## Describe the bug
Event Hub creation fails when creating with a name longer than 50 characters. This conflicts with the 256 character limit quoted in the [quotas and limits](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-quotas) documentation. I was also able to create Event Hubs with up to 256 character names as recently as 2.0.77.

**Command Name**
`az eventhubs eventhub create`

**Errors:**
```
validation error: Parameter 'event_hub_name' must have length less than 50.
```

## To Reproduce:

- Run the Event Hub Create command `az eventhubs eventhub create -g rg-name --namespace-name ns-name -n {name longer than 50 characters}`

## Expected Behavior
I would expect that the command should create the desired Event Hub as long as the name is less than 257 characters.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.10.1

```

**Comment by yonzhan** [comment]
eventhubs

**Comment by ianblitz** [comment]
Hi, any word on this?

**Comment by yonzhan** [comment]
eventhubs service team should look into this issue.

**Comment by serkantkaraca** [comment]
This limitation is from CLI client. @v-Ajnava can you help or pull in a dev who can?

**Comment by MyronFanQiu** [comment]
@serkantkaraca This limitation is defined in swagger spec. It seems like you just changed it 21 days ago. Please send sdk request and change the dependency for Azure CLI. https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventhub/resource-manager/Microsoft.EventHub/common/v1/definitions.json#L129

**Comment by samuelkoppes** [comment]
We are investigating this issue and will respond with an update by 11/4/2020.

**Comment by samuelkoppes** [comment]
This issue should be resolved, please upgrade to the latest version of the SDK and retest.

**Comment by ianblitz** [comment]
I have validated it is working on version 2.14.0. Thank you!
