### ISSUE TITLE
Webapp:Can't set a setting that contains a | char

### ISSUE THREAD

**Issue by dazinator** [Azure/azure-cli#14693]
I am using powershell, and trying to use the `az webapp config appsettings set` command to set an appsetting, and am following this document.

My setting value, contains a `|` character. I tried this:

```
 az webapp config appsettings set --name uniun-prod --resource-group production --slot-settings Foo=foo|bar
```

I get:

> bar : The term 'bar' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.

I tried to escape the pipe character. Powershell rules say backtick is used to escape special chars:

```
 az webapp config appsettings set --name uniun-prod --resource-group production --slot-settings Foo=foo`|bar
```

Same error:

> 'bar' is not recognized as an internal or external command,
operable program or batch file.

I try to quote the string:

```
 az webapp config appsettings set --name uniun-prod --resource-group production --slot-settings Foo='foo|bar'
```

Same error:

> 'bar' is not recognized as an internal or external command,
operable program or batch file.

I try to declare the variable first, then use it:

```
$fooValue = 'foo|bar'
az webapp config appsettings set --name uniun-prod --resource-group production --slot-settings Foo=$fooValue 
```

Same error.

Absolutely pulling my hair out now. How do I set this value?

Lastly I tried using a double `||`

```
 az webapp config appsettings set --name uniun-prod --resource-group production --slot-settings 'Foo=1||2'
```

That set the variable to `1` so it seemed to evaluate the `||` as an "or else" even though I am passing it as a literal string arguement:

```
 {
    "name": "Foo",
    "slotSetting": true,
    "value": "1"
  }

```
So to me, this is seeming like its a limitation of the command itself and that it seems to interpret pipe characters. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* Content: [az webapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by ThejaChoudary** [comment]
Assigning it to myself to repro

**Comment by calvinsID** [comment]
@dazinator Please try `--slot-settings Foo='"foo|bar"'` as per this guide on escaping: https://octopus.com/blog/powershell-pipe-escaping
