### ISSUE TITLE
Command for notifications

### ISSUE THREAD

**Issue by DonPetry-EY** [Azure/azure-cli#14697]
This feature supports/requires the use of Notifications.  The REST API covers a "notifications" section which is not reflected here.  The portal requires creation of a notification but I don't see how to do that via CLI.

https://docs.microsoft.com/en-us/rest/api/consumption/budgets/createorupdate

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d0e4fd3-7458-6d8e-b4ae-aefcdde52409
* Version Independent ID: 9a13720a-356a-6631-f4a0-f9aecd80f92e
* Content: [az consumption budget](https://docs.microsoft.com/en-us/cli/azure/consumption/budget?view=azure-cli-latest#az-consumption-budget-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/consumption/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/consumption/_help.py)
* Service: **consumption**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
consumption

**Comment by ramaganesan-rg** [comment]
We are working on upgrading the SDK to a newer version that will fix this. thank you for your feedback!

**Comment by TiloGit** [comment]
would that be the same as **Alert recipients (email)** I can create via GUI? 
List in JSON under  **ContactEmail**

**Comment by dan-dimitrov** [comment]
Is there an update on this and enabling budget alerts?
