### ISSUE TITLE
Webapp:What is the json file meant to look like?

### ISSUE THREAD

**Issue by dazinator** [Azure/azure-cli#14694]
The docs says you can supply the settings from a json file, but it doesn't give an example for what thay JSON file should look like.

I tried to guess the following, but it didn't work:

```
[
  {
  "name": "foo",
  "slotSetting": true,
  "value": "1|2"
  }
]

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* Content: [az webapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by dazinator** [comment]
Apologies the format I guessed does work, still, I am leaving this open because it would be good to add an example file to the doc.

```
[
  {
  "name": "foo",
  "slotSetting": true,
  "value": "1|2"
  }
]

```

**Comment by yonzhan** [comment]
webapp

**Comment by ThejaChoudary** [comment]
Assigning it to myself to repro

**Comment by ibidani** [comment]
my suggestion is to refer on this page https://docs.microsoft.com/en-us/azure/app-service/configure-common#edit-in-bulk
where appsettings syntax is explained 
https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az_webapp_config_appsettings_set
