### ISSUE TITLE
Support Azure CLI for schedule query rules new API version.

### ISSUE THREAD

**Issue by yanivlavi** [Azure/azure-cli#14691]
**Is your feature request related to a problem? Please describe.**
This is a new feature of schedule query rules not related to an issue other than usbility. 

**Describe the solution you'd like**
CLI support for this new API that is as similar as possible to Azure Monitor metric alert CLI.

**Additional context**
Approved swagger:
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2020-05-01-preview

SDK is not ready.

**Comment by yonzhan** [comment]
For Ignite.
