### ISSUE TITLE
[Output Format] List format breaks up all caps strings

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#147]
Create a VM.  It returns an object with the propert OsSKU.  This is broken up by the output format into words.

Expected output: Os SKU
Actual output: Os S K U (spaces between abbreviation chars)

**Comment by JasonRShaver** [comment]
@BurtBiel Is this still happening?

**Comment by BurtBiel** [comment]
@JasonRShaver We haven't made any changes to the list output that I know of, so I assume it still happens.  However, the outputs for VM have changed and I didn't see any other properties in vm nic and storage account show that had continuous capital letters.

**Comment by derekbekoe** [comment]
Yes this is not specific to compute.
It's a bug in the List output format in general.

e.g.
`$ az vm list --out list --query "[].{ALLCAPS: name, someCAPS: name}"`

```
A L L C A P S : vm1
Some C A P S  : vm1

A L L C A P S : vm2
Some C A P S  : vm2

A L L C A P S : vm3
Some C A P S  : vm3
```

**Comment by tjprescott** [comment]
PR #747 merged.
