### ISSUE TITLE
Synapses Creating Big Data Pool validation error: Parameter 'BigDataPoolResourceInfo.node_count' failed to meet validation requirement.

### ISSUE THREAD

**Issue by jayendranarumugam** [Azure/azure-cli#14708]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Running the command of [creating bigdata pools for azure synapses](https://docs.microsoft.com/en-us/cli/azure/ext/synapse/synapse/spark/pool?view=azure-cli-latest#ext-synapse-az-synapse-spark-pool-create) getting the below error 
validation error: Parameter 'BigDataPoolResourceInfo.node_count' failed to meet validation requirement.

**To Reproduce**
Download latest az cli and running the below command which was the example given at [here](https://docs.microsoft.com/en-us/cli/azure/ext/synapse/synapse/spark/pool?view=azure-cli-latest#ext-synapse-az-synapse-spark-pool-create)
```
az synapse spark pool create --name testpool --workspace-name testsynapseworkspace --resource-group rg \
--spark-version 2.4 --node-count 3 --node-size Medium

```
**Expected behavior**

It should create a Big data pool

**Environment summary**

Windows 10

**Additional context**

**Comment by yonzhan** [comment]
synapse

**Comment by idear1203** [comment]
Thanks for the notification. This is a bug. We will fix it soon.

**Comment by idear1203** [comment]
```bash
az synapse spark pool create --name testpool--workspace-name testsynapseworkspace --resource-group rg --spark-version 2.4 --node-count 4 --node-size Medium
Command group 'synapse' is in preview. It may be changed/removed in a future release.
validation error: Parameter 'BigDataPoolResourceInfo.node_count' failed to meet validation requirement.
```

**Comment by fengzhou-msft** [comment]
@idear1203 you may need to add `type=int` in `_params.py` for `node_count` to pass the validation in SDK model.

**Comment by jayendranarumugam** [comment]
Thanks you all for fixing the bug. I just came across another one https://github.com/MicrosoftDocs/azure-docs/issues/60927. Not sure really it is a bug in the code or docs issue. Just putting it here FYI.

Cc: @idear1203  @fengzhou-msft

**Comment by idear1203** [comment]
Hi @jayendranarumugam , for the issue described on this page, we have already fixed it in the PR: https://github.com/Azure/azure-cli/pull/14755 . The fix will be available in the next Azure CLI release.

For https://github.com/MicrosoftDocs/azure-docs/issues/60927 , this is a docs issue indeed. I have notified our PM for a fix. Thanks a lot for your feedback!
