### ISSUE TITLE
functionapp create --assign-identity not implemented

### ISSUE THREAD

**Issue by cxznmhdcxz** [Azure/azure-cli#14701]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Missed implementation of "az functionapp create **--assign-identity**"  in PR https://github.com/Azure/azure-cli/pull/14233

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
functionapp

**Comment by cxznmhdcxz** [comment]
PR merged. Close this issue.
