### ISSUE TITLE
Az login in WSL runs powershell with profile

### ISSUE THREAD

**Issue by dhmoto17** [Azure/azure-cli#14711]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When I run "az login" in WSL console it starts powershell and runs the profile from the default location in my Windows host:
env:USERPROFILE\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1

This is unexpected, inefficient and a little confusing.  E.g. my profile creates a long set of aliases and functions.

I think it may be related to a request to switch from CMD to powershell in this request https://github.com/Azure/azure-cli/issues/11927

**To Reproduce**
Open WSL console
Run "az login"

**Expected behavior**
Powershell runs without profile e.g. by using -noprofile switch

**Environment summary**
Windows 10 build 18363

az --version
azure-cli                         2.10.0 *

command-modules-nspkg              2.0.3
core                              2.10.0 *
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/dhunix01/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Jul 31 2020, 08:33:11)
[GCC 7.5.0]

**Additional context**

**Comment by yonzhan** [comment]
add to S175

**Comment by jiasli** [comment]
`az upgrade` already uses `-NoProfile` to invoke `powershell.exe` (#15361, #15455). I will migrate the same to `az login`.
