### ISSUE TITLE
Don't overwrite kubectl on macOS during aks install-cli

### ISSUE THREAD

**Issue by LukeCarrier** [Azure/azure-cli#14713]
**Describe the bug**

`aks install-cli` should not install to `/usr/local` on macOS, because Homebrew probably manages that. It should also not overwrite the kubectl binary or link that already exists at that location, because that's just bad behaviour.

**To Reproduce**

1. Install Homebrew, as I'd imagine most developers do.
2. Install kubectl via Homebrew or Docker Desktop.
3. Run `az aks install-cli` and observe that Az has dutifully overwritten your existing binary with its own.

**Expected behavior**

Either:
* Raise a warning, telling me that a binary already exists there and that I have to remove it to continue.
* Install it to `~/` somewhere, which is what the docs tell us will happen!

**Environment summary**

N/A

**Additional context**

N/A

**Comment by yonzhan** [comment]
aks

**Comment by navba-MSFT** [comment]
@LukeCarrier Apologies for the late reply. We are looking into this and we will update this thread once we have more details.

@azure/aks-pm Could you please look into this ask and update this thread once you get a chance ? Awaiting your reply.

**Comment by olsenme** [comment]
@qpetraroia

**Comment by LukeCarrier** [comment]
Tired of seeing this open and unloved issue.

**Comment by marrem** [comment]
Is it so difficult for Microsoft to solve this trivial problem.
