### ISSUE TITLE
az role assignment list from Windows Terminal 1.1 resolves in 400 client error

### ISSUE THREAD

**Issue by EelcoLos** [Azure/azure-cli#14723]
## Describe the bug

When using windows terminal (Version: 1.1.2021.0) with azure cli, and requesting role assignement, subsequent error showed up. *note*: after I ran the command, it said I had 2 updates waiting, which would update on the next shell request. I updated and ran the command again. The same error occured.

**Command Name**
`az role assignment list`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role assignment list`

## Expected Behavior
To see the role assignements of my account.

## Environment Summary
```
Linux-4.15.0-1092-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB
Windows Terminal (Version: 1.1.2021.0)

azure-cli 2.9.1 *

```

**Comment by yonzhan** [comment]
add to S175

**Comment by yungezz** [comment]
#11478

**Comment by EelcoLos** [comment]
Updated to Version: 1.1.2233.0. Either that, rbac, az remote updates resolved the issue
