### ISSUE TITLE
CLI error message is not relevant to improper use

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#1472]
```
az acr check-name ahmet
usage: az [-h] [--output {json,tsv,list,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {storage,keyvault,vm,network,resource,redis,iot,appservice,role,vmss,component,ad,container,tag,provider,login,acr,acs,account,feedback,taskhelp,context,logout,cloud,configure}
          ...
```

This error I got when I forgot to specify `--name` is far too generic. The `az acr check-name` part is true, but the error is treating me like I typed `az asdfajsdfhhjkhasd`.

I'm running 0.1.0b10.

cc: @djyou is this acr-specific do you think or is there a more common issue here?

**Comment by derekbekoe** [comment]
@ahmetalpbalkan Right after the usage statement, I see a more specific error message.
```
# az acr check-name ahmet
usage: az [-h] [--output {json,tsv,list,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {storage,network,account,vm,appservice,vmss,resource,cloud,logout,acr,role,acs,tag,ad,provider,context,container,component,feedback,login,configure}
          ...
az: error: unrecognized arguments: ahmet
```

**Comment by ahmetalpbalkan** [comment]
@derekbekoe oops I missed that totally. I think I was confused by the other 4 lines of top-level help message that totally doesn't help me at all. :-) I think a better designs in terms of UX here would be

0. move the actual error to the top, along with how to get help (not USAGE string)
0. just print the error, I'm already deep in your command, so top level help doesn't really help me.
0. print all the help for that specific subcommand and the error _clearly_ at the end.

Here are examples for each of them:

```
➜  curl -Y http://asdf
curl: option -Y: expected a proper numerical parameter
curl: try 'curl --help' or 'curl --manual' for more information
```

```
➜  azure vm create -X

  error: unknown option `-X'
```

```
➜ ./azure-extensions-cli replication-status -x
Incorrect Usage.

NAME:
   azure-extensions-cli replication-status - Retrieves replication status for an uploaded extension package

USAGE:
   azure-extensions-cli replication-status [command options] [arguments...]

OPTIONS:
   --management-url "https://management.core.windows.net"	Azure Management URL for a non-public Azure cloud [$MANAGEMENT_URL]
   --subscription-id 						Subscription ID for the publisher subscription [$SUBSCRIPTION_ID]
   --subscription-cert 						Path of subscription management certificate (.pem) file [$SUBSCRIPTION_CERT]
   --namespace 							Publisher namespace e.g. Microsoft.Azure.Extensions [$EXTENSION_NAMESPACE]
   --name 							Name of the extension e.g. FooExtension [$EXTENSION_NAME]
   --version 							Version of the extension package e.g. 1.0.0

flag provided but not defined: -x
```

**Comment by squillace** [comment]
upvote. the usage, in addition, is quite difficult to parse, and it therefore becomes difficult especially when harried to figure out what the hell went wrong, really. It's a readability thing. Seeing the usage first means that you KNOW something went wrong (or you would have gotten the expected result) but you must parse _forward_ to know what it is and then parse _backward_ to discover what it should be. 

This ordering should be systematically reversed.

**Comment by squillace** [comment]
@derekbekoe to bring it into your queue. :-)
