### ISSUE TITLE
AZ Command to retrieve no of running containers in a container group

### ISSUE THREAD

**Issue by lowrencekurera** [Azure/azure-cli#14720]
**Resource Provider**
AZURE

**Description of Feature or Work Requested**
Is there any Azure CLI command to get the value of running containers of any container group?
Something like "az container count -n my_cnt_grp -g MyResourceGroup"?
I need to pass the value of running containers to an "If" condition to send alerts.

**Target Date**
14/08/2020

**Comment by yonzhan** [comment]
container

**Comment by yungezz** [comment]
hi does `az contianer list` meet the requirement?https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-list

**Comment by lowrencekurera** [comment]
Hi,

Thanks for the reply. No, list will only give me a list of containers. But
my requirement is to get a number, instead of list of running containers.

Kind regards

Lowrence

**Comment by PramodValavala-MSFT** [comment]
@lowrencekurera You can leverage the [query parameter](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest) to get the number of containers with a command like so

```sh
az container show -g myrg -n mycontainer --query 'length(containers)'
```
