### ISSUE TITLE
Provide documentation about the data structure of the consumption usage list command

### ISSUE THREAD

**Issue by florianrusch** [Azure/azure-cli#14725]
It would be cool to have a documentation about the data structure of the provided data behind the `az consumption usage list` command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e05c0768-9cfc-3b78-4f39-70a8c1f0b6bd
* Version Independent ID: b5e5d8fa-e84c-408a-3f49-19d245563abd
* Content: [az consumption usage](https://docs.microsoft.com/en-us/cli/azure/consumption/usage?view=azure-cli-latest#az-consumption-usage-list)
* Content Source: [src/azure-cli/azure/cli/command_modules/consumption/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/consumption/_help.py)
* Service: **consumption**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
consumption

**Comment by ramaganesan-rg** [comment]
Hello, 
The documentation you are asking for is available at
https://docs.microsoft.com/en-us/rest/api/consumption/usagedetails/list#legacyusagedetail
Please check it out, and reopen if you have any further questions. Thank you for your feedback!
