### ISSUE TITLE
[Compute] add new license_type in vm create/update: RHEL_BYOS, SLES_BYOS

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#14735]
**Resource Provider**

Compute

**Description of Feature or Work Requested**

FEATURE 4014 created and assigned to you, Arun.
 
Timeline: by Ignite (week of 9/21)
 
The ask:
Make sure new values are accepted by:
az vm update
az vm create
 
Background: Azure Hybrid Benefit already exists for Windows. Instead of charging for HW and SW fees. Just charging for the HW fee. For this update, two new values will be added to licenseType.
 
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate
“Windows Server” is already a possible value for Properties.licenceType 
 
For Linux - adding two new values.
- RHEL_BYOS
- SLES_BYOS
 
API - no revision; no increment needed. Not breaking anything.
Can use:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json
 
- We’ll need capability to do a bulk update of VMs’ AHB statuses, using the --ids parameter
   -  E.g. az vm update --license-type RHEL_BYOS --ids <path to id file>
   - Messages for success and failure conditions will need to be added

**Minimum API Version Required**

**Swagger Link**

**Target Date**

**Ignite**

**Comment by yungezz** [comment]
https://nam06.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Aw%3A%2Fr%2Fteams%2FAzureIDC%2FAzureIDC_CRP%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257BDAEEE1BA-1D9C-455C-A889-2ED26DFE2A5A%257D%26file%3DAHUB%2520support%2520for%2520Linux%2520VMs-CRP.docx%26wdLOR%3Dc26DC10B6-BB90-47CD-9A45-C2D5593DA9E8%26nav%3DeyJjIjo1ODQ1MDkwNTB9%26action%3Ddefault%26mobileredirect%3Dtrue&data=02%7C01%7Cyungez%40microsoft.com%7C12b55c3a49f049cb387e08d83d5769b0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637326793176219273&sdata=c6XadsdvDIaocz4eFgTl8G5R0MiYcJ3G5cO5n3Clw74%3D&reserved=0

**Comment by qwordy** [comment]
I don't think it's a good practice to open PR for service team. They are the entity that requests this feature. I sent a email of instructions on creating service feature request feature to them on May 19 about this feature.
