### ISSUE TITLE
"consumption usage list --subscription" is pulling billing information from a random incorrect subscription.

### ISSUE THREAD

**Issue by GarrettGeorge** [Azure/azure-cli#14747]
## Describe the bug

**Command Name**
`az consumption usage list --subscription`

**Errors:**

No formal errors, but gives unexpected output.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az consumption usage list --subscription [UUID] --start-date "$( date +'%Y-%m-%d' -d '-2 days')" --end-date "$( date +'%Y-%m-%d' -d '-2 days')" --output json`

## Expected Behavior

List of billing information based on specified subscription.

## Actual Output

List of billing information based on a _**random**_ subscription. I truly mean random, it's different every time. This happens no matter if I use `--subscription` or I use the default subscription from doing `az account set -s`.

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.10.1

```

**Comment by GarrettGeorge** [comment]
After looking at the tests, it doesn't look like there is one for verifying the output contains the correct subscription, specifically https://github.com/Azure/azure-cli/blob/8adf97355a605d147afc26f6c1b6f6afb6651c2f/src/azure-cli/azure/cli/command_modules/consumption/tests/latest/test_consumption_commands.py#L140 which seems to indicate based on the name it has something to do with the subscription.

**Comment by GarrettGeorge** [comment]
After using `--debug` to see the content of the HTTP request being made to the server. It looks like it doesn't have anything to do with the azure CLI and instead to do with the `/Microsoft.Consumption/usageDetails` microservice. If you can provide me a person/place to contact about this, I can close this ticket.

**Comment by yonzhan** [comment]
consumption

**Comment by tujamg** [comment]
During the first week of Aug as part of engineering perf improvements, we made changes to our caching strategy which caused a regression for calls made at subscription scope within the same enrollment. The feature is reverted back to mitigate the issue. Let reopen the issue if you see this happening recently.
