### ISSUE TITLE
az network application-gateway create: the --private-ip-address parameter does nothing

### ISSUE THREAD

**Issue by subhasishdc** [Azure/azure-cli#14748]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When creating an application gateway using `az network application-gateway create`, adding the `--private-ip-address` parameter does nothing.  The CLI gives no errors but the parameter does nothing and does not associate a private ip address to the application gateway. To associate a private ip address, I need to run a second command `az network application-gateway frontend-ip create` which will create the private frontend IP configuration.

Is this something by design or a bug in the `az network application-gateway create` command.

**Expected behavior**
If this is something by design, then the `--private-ip-address` parameter should be deprecated. If not, it is a bug and needs to be fixed.

**Environment summary**
CLI Version:  2.8.0
OS Type: Mac

**Additional context**

**Comment by yonzhan** [comment]
add to S175

**Comment by haroldrandom** [comment]
Duplicate with https://github.com/Azure/azure-cli/issues/14494
