### ISSUE TITLE
Add more character options for autoscale rule metric-namespace

### ISSUE THREAD

**Issue by GhostInThePotato** [Azure/azure-cli#14745]
**Is your feature request related to a problem? Please describe.**
When creating a new autoscale rule using ` az monitor autoscale rule create`, the metric namespace is limited to `(WORD | '/' | '.')`. This is rather limiting and prevents using metric namespaces that contain whitespace and hyphens, for example.

**Describe the solution you'd like**
Ability to set autoscaling rules using metrics in namespaces that contain whitespace, i.e. "kubernetes custom metrics"

**Additional context**
[AutoscaleCondition.g4](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/grammar/autoscale/AutoscaleCondition.g4#L11)

**Comment by yonzhan** [comment]
add to S175

**Comment by MyronFanQiu** [comment]
@GhostInThePotato Thanks for the suggestion. Will work on it later.
