### ISSUE TITLE
az storage container create fails and returns incorrect error message

### ISSUE THREAD

**Issue by brooke-hamilton** [Azure/azure-cli#14743]
## Describe the bug
`az storage container create` fails after creating a storage account.

**Command Name**
`az storage container create`

**Errors:**
```
The request may be blocked by network rules of storage account. Please check network rule set using 'az storage account show -n accountname --query networkRuleSet'.
If you want to change the default action to apply when no rule matches, please use 'az storage account update'.
```

If I run the command suggested in the error message, ```az storage account show -n accountname --query networkRuleSet```, I get the output below, showing that there are no network rules blocking the creation of a storage container:
```
{
  "bypass": "AzureServices",
  "defaultAction": "Allow",
  "ipRules": [],
  "virtualNetworkRules": []
}
```

## To Reproduce:
The BASH script below reproduces the issue:

``` BASH
#!/bin/bash

location="eastus"
resourceGroupName="rg-repro"
storageAccountName="sarepro"
storageContainerName="ctrepro"

az group create --location $location --name $resourceGroupName

az storage account create \
    --name $storageAccountName \
    --resource-group $resourceGroupName \
    --location $location 

az storage container create \
    --name $storageContainerName \
    --account-name $storageAccountName \
    --resource-group $resourceGroupName \
    --auth-mode login 
```

## Expected Behavior
The `az storage container create` command should succeed, or there should be an error message describing why the command failed.

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.10.1

```

**Comment by brooke-hamilton** [comment]
I encountered the same issue in PowerShell on Windows.

**Comment by brooke-hamilton** [comment]
From a BASH cloud shell, I get this error when I run `az storage container create`
``` BASH
usage: az storage container create [-h] [--verbose] [--debug]
                                   [--only-show-errors]
                                   [--output {json,jsonc,yaml,yamlc,table,tsv,none}]
                                   [--query JMESPATH]
                                   [--account-name ACCOUNT_NAME]
                                   [--account-key ACCOUNT_KEY]
                                   [--connection-string CONNECTION_STRING]
                                   [--sas-token SAS_TOKEN]
                                   [--subscription _SUBSCRIPTION] --name
                                   CONTAINER_NAME
                                   [--resource-group RESOURCE_GROUP_NAME]
                                   [--metadata METADATA [METADATA ...]]
                                   [--public-access {off,blob,container}]
                                   [--fail-on-exist] [--timeout TIMEOUT]
                                   [--default-encryption-scope DEFAULT_ENCRYPTION_SCOPE]
                                   [--prevent-encryption-scope-override [{true,false}]]
                                   [--auth-mode {login,key}]
az storage container create: error: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

**Comment by brooke-hamilton** [comment]
I do not get this error on another subscription in which I am in the Owner role on the sub.
I get this error on my MSDN subscription in which I am in the Owner role on the sub.
I get this error on my company-sponsored subscription in which I'm in the Account Admin role on the sub.

**Comment by yonzhan** [comment]
add to S175

**Comment by brooke-hamilton** [comment]
I used this python script to work around the issue:

```python
import os

from azure.common.client_factory import get_client_from_cli_profile
from azure.mgmt.storage import StorageManagementClient

RESOURCE_GROUP_NAME = os.environ["rgName"]
STORAGE_ACCOUNT_NAME = os.environ["saName"]
CONTAINER_NAME = os.environ["containerName"]

storage_client = get_client_from_cli_profile(StorageManagementClient)
container = storage_client.blob_containers.create(RESOURCE_GROUP_NAME, STORAGE_ACCOUNT_NAME, CONTAINER_NAME, "None")

print(f"Provisioned container {container.name}")
```

**Comment by Juliehzl** [comment]
Hi @brooke-hamilton, it should be caused by lacking of RBAC permission for storage blob as shown here https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-portal#azure-roles-for-blobs-and-queues.
We will refine the error message.
IN addition, we will recommend you to use account key as credential if you can. `--auth-mode login` will  require specific RBAC roles assigned.

**Comment by brooke-hamilton** [comment]
Thank you for following up on this. 

I wonder why the Python SDK and the Azure Portal do not require any RBAC permissions for creating a storage container.

Ideally, the AZ CLI would not require any additional permissions or require using an account key, which would be consistent with other methods of creating a storage container.

**Comment by Juliehzl** [comment]
`az storage container-rm` is supported now without additional data related roles. It will use login AD credential directly to ARM.
