### ISSUE TITLE
Query on vm list-sizes fails

### ISSUE THREAD

**Issue by devhl-labs** [Azure/azure-cli#14744]
`az vm list-sizes --query "[? maxDataDiskCount == '4']"` returns empty
```az vm list-sizes --query "[?maxDataDiskCount == `4`]"``` throws an invalid jmespath_type error

Am I doing something wrong in this query?  I had someone else test it and get the same result.

**Comment by subhasishdc** [comment]
@devhl-labs: You would need to escape the backtick character ``` using which you enclose the value. I tested it on my system and it works. Without the escaping, it throws an invalid jmespath_type error. The following works for me and returns the correct values.

`az vm list-sizes --location westus --query "[?maxDataDiskCount==\`4\`]"`

**Comment by devhl-labs** [comment]
`az vm list-sizes --location westus --query "[?maxDataDiskCount==``4``]"`

Perfect, thanks!
