### ISSUE TITLE
Unknown error occurring on az aks create when specifying --load-balancer-outbound-ips

### ISSUE THREAD

**Issue by QTom01** [Azure/azure-cli#14742]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I am creating an aks instance using `az aks create`. Everything works fine until I add `--load-balancer-outbound-ips` at which point I get an error with no information, and the deployment still continues:

![image](https://user-images.githubusercontent.com/5354942/89918989-a250e300-dbf2-11ea-968c-c78b2fde7fea.png)

This error appears but the cluster seems to deploy normally and successfully anyway. The output looks correct and the outbound IP's etc are correctly set to the one I specified.

**To Reproduce**

```
az aks create `
--resource-group=dummy-rg `
--name=dummy-aks`
--node-vm-size=Standard_B2s `
--generate-ssh-keys `
--load-balancer-outbound-ips $staticIpId
```

Where $staticIpId is a fully qualified id such as:
`/subscriptions/<subId>/resourceGroups/other-dummy-rg/providers/Microsoft.Network/publicIPAddresses/<ipName>`

Unsure if it's related but the IP I am using is in a different resource group.

**Expected behavior**

Deploy without errors, or show an error explaining what is wrong.

**Environment summary**

```
az version
{
  "azure-cli": "2.9.1",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.9.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}
```
Microsoft Windows 10 Pro 10.0.18362 N/A Build 18362
Powershell 5.1
CLI installed from the MSI.

**Comment by yonzhan** [comment]
aks

**Comment by TomGeske** [comment]
It is a known issue caused by SP replication. To work around you may want to create your service principle ahead of cluster creation. See also: https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal

**Comment by navba-MSFT** [comment]
@QTom01 Apologies for the late reply. Could you please let us know if you had a chance to look at the above comment ? Please let me know if you need any further assistance on this issue. Awaiting your reply.
