### ISSUE TITLE
Live test pipline support all the tests in azure-cli-extensions repo

### ISSUE THREAD

**Issue by zhoxing-ms** [Azure/azure-cli#14756]
**Is your feature request related to a problem? Please describe.**

When CLI is in bumping version, if there are some breaking changes may affect extensions ( such as: https://github.com/Azure/azure-cli-extensions/pull/2129 ) , we need a test system to test all extension tests in azure-cli-extensions repo.

**Describe the solution you'd like**

* Supports manual trigger to run all tests in azure-cli-extensions repo
* We can select branch of azure-cli repo that is dependent, because the upgrade of CLI has not been released during the test.

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Live test pipline enhancement

**Comment by qwordy** [comment]
Received the feature request

**Comment by qwordy** [comment]
Finished. Please read user manual carefully.
