### ISSUE TITLE
[Keyvault] Security domain

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#14753]
**Resource Provider**

Keyvault

**Description of Feature or Work Requested**

Support Keyvault security domain feature

**Minimum API Version Required**

https://msazure.visualstudio.com/One/_workitems/edit/7634479
**Swagger Link**

**Target Date**

part of MHSM public preview

**Comment by yungezz** [comment]
security domain is part of MHSM public preview

**Comment by yungezz** [comment]
feedback from Amit after testing.
---
Public preview blockers - must be fixed for 9/22 release
No public preview blocking issues so far.
remove --restore-blob option. --restore-blob is not very useful after SD is uploaded. Becaused SD-exchange-key(private key in HSM) will be deleted after the SD has been successfuly uploaded)
For commands with --hsm-name, error message contains "vault", it's confusing.
Open issues to be fixed AFTER public preview

1. "Unknown error" - message when using the 'az keyvault security-domain upload'. The upload actually succeeds. 
 
Bin Ma - We have consistently seen this "Unknown Error" when doing a "az keyvault security-domain upload". Even though it shows Error, we have observed that the upload was actually successful. This error message appears consistently but the upload never failed.
 
 
deverett@deMHSM:/mnt/c/temp/MHSM/mhsmprod-data$ oid1='fc59e4db-7bbc-47e3-a33c-428097ff279a'

deverett@deMHSM:/mnt/c/temp/MHSM/mhsmprod-data$ oid2='7bfa9d09-1e11-4546-9d6a-d097b48b8cd4'

deverett@deMHSM:/mnt/c/temp/MHSM/mhsmprod-data$ az keyvault create --hsm-name mhsmprod2 --location eastus2euap --resource-group deMHSM --administrators $oid1 $oid2 --subscription 43e19234-6e95-42f6-b559-77d6eafe5004

 

 

deverett@deMHSM:/mnt/c/temp/MHSM/mhsmprod-data$ az keyvault security-domain init-recovery --hsm-name mhsmprod2 --sd-exchange-key mhsmprod2-SDE.cer

Argument '--hsm-name' is in preview. It may be changed/removed in a future release.

Command group 'keyvault security-domain' is in preview. It may be changed/removed in a future release.

deverett@deMHSM:/mnt/c/temp/MHSM/mhsmprod-data$ ls

certs  deKEK-backup  mhsmprod-SD.json  mhsmprod2-SDE.cer

 

deverett@deMHSM:/mnt/c/temp/MHSM/mhsmprod-data$ az keyvault security-domain upload --hsm-name mhsmprod2 --sd-exchange-key mhsmprod2-SDE.cer --sd-file mhsmprod-SD.json --sd-wrapping-keys ./certs/cert_0.key ./certs/cert_1.key

Argument '--hsm-name' is in preview. It may be changed/removed in a future release.

Command group 'keyvault security-domain' is in preview. It may be changed/removed in a future release.

Unknown error


 
2. Selective key restore (See spec ) is not implemented in the CLI.
This is not a public preview blocker. But needs to be added soon after the public preview.
 
3. InitialAdmins gets a newline character
When 'az keyvault create' is invoked like this, initial admin gets a new line character.
az keyvault create --hsm-name mhsmdemo --location eastus2euap --resource-group ambapathsmrg --administrators $(az ad signed-in-user show --query objectId -o tsv)
 
I get a "\r" appended to the first admin - did the CLI not remove white space around the received values?
 {
  "id": "/subscriptions/4b2eb912-ac5b-4348-bc12-dd149b4aeb56/resourceGroups/ambapathsmrg/providers/Microsoft.KeyVault/managedHSMs/mhsmdemo",
  "location": "eastus2euap",
  "name": "mhsmdemo",
  "properties": {
    "createMode": null,
    "enablePurgeProtection": false,
    "enableSoftDelete": true,
    "hsmPoolUri": null,
    "hsmUri": "https://mhsmdemo.managedhsm.azure.net/",
    "initialAdminObjectIds": [
      "50be469a-d7eb-4b26-a2d4-b092cebf0c80\r"
    ],
    "provisioningState": "Succeeded",
    "securityDomainId": null,
    "softDeleteRetentionInDays": 90,
    "statusMessage": "The Managed HSM is provisioned and ready to use.",
    "tenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47"
  },
  "resourceGroup": "ambapathsmrg",
  "sku": {
    "name": "Standard_B1"
  },
  "tags": {},
  "type": "Microsoft.KeyVault/managedHSMs"
}
 
4. Confusing warning/error messages using the terms like 'vault' when it was invoked with --hsm-name parameter.
for any command that is invoked with --hsm-name, it is confusing to read the error messages referring to "vault". For example: in the below example, I had entered a non-existent mhsm name. So of course the command is going to fail. But the error message is confusing because though I used --hsm-name, it says, 'vault' may not exist.
 
(CLI0903) amit@RAIDER10:/mnt/c/Users/amitb/certs$ az keyvault security-domain init-recovery --hsm-name ambapathsm3 --sd-exchange-key ambapatmhsm3-SDE.pem
Argument '--hsm-name' is in preview. It may be changed/removed in a future release.
Command group 'keyvault security-domain' is in preview. It may be changed/removed in a future release.
Max retries exceeded attempting to connect to vault. The vault may not exist or you may need to flush your DNS cache and try again later.
 
for 'az keyvault delete' this message is not applicable as it should only appear for resource type key vault.
 
(CLI0903) amit@RAIDER10:/mnt/c/Users/amitb/certs$ az keyvault delete --hsm-name ambapatmhsm2
Warning! If you have soft-delete protection enabled on this key vault, you will not be able to reuse this key vault name until the key vault has been purged from the soft deleted state. Please see the following documentation for additional guidance.
https://docs.microsoft.com/en-us/azure/key-vault/general/soft-delete-overview
Argument '--hsm-name' is in preview. It may be changed/removed in a future release.
 
 
5. Mutual exclusive error message when using "--hsm-name" only, without "--vault-name".
az keyvault key restore --hsm-name ambapatmhsm3 -f mykey.backup
Argument '--hsm-name' is in preview. It may be changed/removed in a future release.
--vault-name and --hsm-name are mutually exclusive.
 
6. Make sure Azure CLI ignores the expiry dates for the certificates used for SD download.
 
 
---

**Comment by yungezz** [comment]
feedback is tracked at https://github.com/Azure/azure-cli-pr/issues/100

**Comment by bim-msft** [comment]
PR merged.
