### ISSUE TITLE
[Storage] Improve parsing of source/dest URLs for storage batch operations

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1475]
- [ ] Parse blob URL into account name, container name, and blob name or pattern
- [ ] Parse file URL into account name, share name, directory sub-path, and filename or pattern

With this we would not need the individual parameters for each component, although we may keep them since some people might prefer them.

**Comment by williexu** [comment]
Closing this as our storage batch operations look into containers/fileshares and use globbing patterns to gather the right targets. There is no need to accept urls.
