### ISSUE TITLE
ACR login does not work with podman

### ISSUE THREAD

**Issue by mjudeikis** [Azure/azure-cli#14768]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
 az acr login --name registry
You may want to use 'az acr login -n registry --expose-token' to get an access token, which does not require Docker to be installed.
An error occurred: DOCKER_COMMAND_ERROR
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg

**To Reproduce**
install: `podman`, `podman-docker` emulator for CLI

**Expected behavior**
az acr login to work

**Environment summary**
RHEL8. Rhel8 does not have docker anymore. 
If you do `dnf install docker` it will install `podman` and `podman-docker` for CLI backwards compatibility. 

**Additional context**
With growing podman addition would be good for this to work out of the box. With or without `podman-docker` package.

**Comment by yonzhan** [comment]
acr

**Comment by yugangw-msft** [comment]
We will prioritize based on user voice on https://feedback.azure.com/forums/903958-azure-container-registry

**Comment by mangalorereshmi** [comment]
Hi @mjudeikis - Thank you for your feedback. We are tracking this feature request using [UserVoice](https://aka.ms/acr/uservoice) item:   https://feedback.azure.com/forums/903958-azure-container-registry/suggestions/41179153-acr-login-with-podman. We will prioritize this in our backlog based on customer feedback/votes.

Regards,
Reshmi Mangalore

**Comment by serprex** [comment]
@yugangw-msft with [Docker Desktop 4.0's change of terms](https://www.docker.com/blog/updating-product-subscriptions) the story for using docker with WSL becomes less ergonomic & raises the value of podman compatibility in aks. Unfortunately the feedback links in this thread are dead, redirecting to https://azure.microsoft.com/en-us/feedback

**Comment by dsanchor** [comment]
+1 @serprex. Please, @yugangw-msft @mangalorereshmi @toddysm, could you provide a valid link so we can provide our feedback/votes?

**Comment by jdelgadillo** [comment]
+1 We are currently using Azure Container Registry and would like to explore using podman as well.

**Comment by serprex** [comment]
I was able to get it working with `--expose-token` in `az acr login`, followed by `--creds=00000000-0000-0000-0000-000000000000:{shellescape(accessToken)}` when invoking `podman push`

**Comment by djds** [comment]
```sh
#!/bin/bash

set -euo pipefail

readonly USERNAME='00000000-0000-0000-0000-000000000000'


acr_password() {
    local -r registry="${1}"

    set +x
    az acr login \
        --name "${registry}" \
        --expose-token  \
        2>/dev/null \
        | jq -r '.accessToken'
}


login() {
    local -r registries=("${@}")

    for registry in "${registries[@]}"; do
        printf "%s: %s\n" "${registry}" "$(
            podman login \
                --username "${USERNAME}" \
                --password "$(acr_password "${registry}")" \
                "${registry}.azurecr.io"
        )"
    done
}


login "${@}"
```

```sh
./podman-login.sh ${registry}
```

**Comment by murphy85** [comment]
I found some information on this blog: [https://www.danielstechblog.io/running-podman-on-macos-with-multipass/](https://www.danielstechblog.io/running-podman-on-macos-with-multipass/)
I just set the link, executed `podman machine init `and `podman machine start` and it worked :-)

Mac Homebrew M1
`ln -s /opt/homebrew/bin/podman /usr/local/bin/docker || true`

Mac Homebrew Intel
`ln -s /usr/local/bin/podman /usr/local/bin/docker || true`

**Comment by Korijn** [comment]
For any readers hoping to do this in powershell and with WSL2, I've translated the workaround to something you can put in your powershell profile (`code $profile` to edit your profile with vscode):

```ps
function Invoke-AcrLogin {
    param (
        [string]$repository
    )
    $json = az acr login -n $repository --expose-token | ConvertFrom-Json
    $registryUrl = "{0}.azurecr.io" –f $repository
    echo $json.accessToken | wsl podman login --username "00000000-0000-0000-0000-000000000000" --password-stdin "$registryUrl"
}
Set-Alias acrlogin Invoke-AcrLogin
```

Usage: `acrlogin <your-registry>`

**Comment by l3ender** [comment]
@murphy85's approach worked for me but required just a minor tweak for using on WSL:
```bash
sudo ln -s /usr/bin/podman /usr/bin/docker || true
```

After this, `az acr login` worked as expected.

**Comment by zomarg** [comment]
This is suboptimal, beacuse of security reasons "Disabling admin account" in ACR is a must and for the provided solutions to work it needs to be enabled.

**Comment by kalkin** [comment]
`DOCKER_HOST=unix:///run/user/1000/podman/podman.sock az acr login --name acrrss`

**Comment by pakochiu** [comment]
Workaround: 
1. Adding a Access keys for the azure container registry
2. Login Podman with the below script (YourRegistry changing to your registry name) with the account and password created above
3. Podman login YourRegistry.azurecr.io

**Comment by tgolly** [comment]
This worked for me on MacOS:

~~~
TOKEN=$(az acr login -n myacrrepo --expose-token -o tsv --query accessToken)
podman pull myacrrepo.azurecr.io/myapp:latest --creds 00000000-0000-0000-0000-000000000000:$TOKEN
~~~

**Comment by bencat-sixense** [comment]
> 

Work on Manjaro (Arch) too :) 
Thanks @tgolly !

**Comment by bencat-sixense** [comment]
> This worked for me on MacOS:
> 
> ```
> TOKEN=$(az acr login -n myacrrepo --expose-token -o tsv --query accessToken)
> podman pull myacrrepo.azurecr.io/myapp:latest --creds 00000000-0000-0000-0000-000000000000:$TOKEN
> ```

Work on Manjaro (Arch) too :)
Thanks @tgolly !

**Comment by Divya1388** [comment]
Any update on this?

**Comment by kalkin** [comment]
> Any update on this? And do we have a workarounf for RHEL other than exposing token?
Yes this https://github.com/Azure/azure-cli/issues/14768#issuecomment-1222191302

**Comment by Divya1388** [comment]
@kalkin Thanks for looking in to this. i will give it a try and keep posted here

**Comment by maciejduk** [comment]
Not sure how helpful this is, but I was running into similar issues trying to provide login creds for the `podman push` command and my solution was to login beforehand.

```shell
az login
podman login --username $cr_user --password $cr_pass $cr_host
podman push "localhost/$cr_image:latest" "$cr_host.azurecr.io/$cr_image"
```

**Comment by onitake** [comment]
> ```
> TOKEN=$(az acr login -n myacrrepo --expose-token -o tsv --query accessToken)
> podman pull myacrrepo.azurecr.io/myapp:latest --creds 00000000-0000-0000-0000-000000000000:$TOKEN
> ```

These can also be combined into one command:
```
podman login myregistry.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p "$(az acr login --name myregistry --expose-token -o tsv --query accessToken)"
```

The socket approach will only work with systemd, because Podman is daemonless and the socket is activated by a systemd unit.

**Comment by crussell52** [comment]
> [@murphy85](https://github.com/murphy85)'s approach worked for me but required just a minor tweak for using on WSL. After this, `az acr login` worked as expected.
> 
> sudo ln -s /usr/bin/podman /usr/bin/docker || true
> Note: an alias in `~/.bashrc` was not sufficient.

For me (running on wsl2), `/usr/bin/podman` already exists and is just a wrapper to podman with a stderr echo notifying you that docker is being emulated. I just touched the file that suppresses that notification and `az acr login` worked as expected. Maybe it is detected stderr output as an error condition?

Note, I also already had the podman socket enabled, so that may have played a role. 
```
sudo systemctl enable --now podman.socket
````
