### ISSUE TITLE
 az kusto cluster create: 'Standard_D14_v2' is not a valid value for '--sku'

### ISSUE THREAD

**Issue by digeler** [Azure/azure-cli#14769]
## Describe the bug

**Command Name**
`az kusto cluster create`

**Errors:**
```
Invalid SKU name provided
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az kusto cluster create -l {} -n {} -g {} --sku {} --capacity {} --debug`
full command :
  az kusto cluster create -l australiaeast  -n testsku -g kusto --sku "D14_v2" --capacity 1 --debug
also tried : 
 az kusto cluster create -l australiaeast  -n testsku -g kusto --sku "Standard_D14_v2" --capacity 1 --debug

list of available skus : 

"skuName": {
            "allowedValues": [
                "Dev(No SLA)_Standard_D11_v2",
                "Standard_D11_v2",
                "Standard_D12_v2",
                "Standard_D13_v2",
                "Standard_D14_v2",
                "Standard_L4s",
                "Standard_L8s",
                "Standard_L16s",
                "Standard_L8s_v2",
                "Standard_L16s_v2",
                "Standard_DS13_v2+1TB_PS",
                "Standard_DS13_v2+2TB_PS",
                "Standard_DS14_v2+3TB_PS",
                "Standard_DS14_v2+4TB_PS",
                "Standard_E2a_v4",
                "Standard_E4a_v4",
                "Standard_E8a_v4",
                "Standard_E16a_v4",
                "Standard_E8as_v4+1TB_PS",
                "Standard_E8as_v4+2TB_PS",
                "Standard_E16as_v4+3TB_PS",
                "Standard_E16as_v4+4TB_PS",
                "Dev(No SLA)_Standard_E2a_v4"

using the portal its working : 
tags": {
    "primaryResourceId": "/subscriptions/928f4e7e-2c28-4063-a56e-6f1e6f2bb73c/resourcegroups/dcos-ci/providers/Microsoft.Kusto/Clusters/testdinkusto",
    "marketplaceItemId": "Microsoft.AzureKusto"
  },
  "properties": {
    "templateHash": "8145598177547138071",
    "parameters": {
      "name": {
        "type": "String",
        "value": "testdinkusto"
      },
      "location": {
        "type": "String",
        "value": "australiaeast"
      },
      "properties": {
        "type": "Object",
        "value": {
          "enableStreamingIngest": false,
          "enablePurge": false
        }
      },
      "tags": {
        "type": "Object",
        "value": {}
      },
      "skuName": {
        "type": "String",
        "value": "Standard_D14_v2"
      },
      "tier": {
        "type": "String",
        "value": "Standard"
      },
      "capacity": {
        "type": "Int",
        "value": 2
      }

seems related : https://github.com/Azure/azure-cli/issues/13330

also if there is a nugget update for c# let me know.

## Expected Behavior
to create the kusto cluster 
## Environment Summary
```
Linux-4.15.0-1092-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.9.1 *

```

**Comment by yonzhan** [comment]
kusto

**Comment by orhasban** [comment]
Hi @digeler can you run 'az extension add -n kusto' and try again please? You are using old version of kusto cli

**Comment by digeler** [comment]
PS C:\Users\digeler> az extension add -n kusto
Extension 'kusto' is already installed.

same result: 
az_command_data_logger : command args: kusto cluster create -l {} -n {} -g {} --sku {} --capacity {} --debug
metadata file logging enabled - writing logs to 'C:\Users\digeler\.azure\commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0406B228>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0406B270>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0406B8E8>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x045E67C8>]
cli.azure.cli.core.util : usage error: --sku [KEY=VALUE ...]
usage error: --sku [KEY=VALUE ...]
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x040EF810>]
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2485 in cache
telemetry.check : Negative: The C:\Users\digeler\.azure\telemetry.txt was modified at 2020-08-15 17:17:42.586373, which in less than 600.000000 s
command ran in 0.469 seconds.

**Comment by digeler** [comment]
any updates on this please ?

**Comment by astauben** [comment]
Hi @digeler, Sorry for the late response. 
We have changed the command's syntax a bit. Can you please follow this: https://docs.microsoft.com/en-us/cli/azure/ext/kusto/kusto/cluster?view=azure-cli-latest#ext-kusto-az-kusto-cluster-create doc and try again?

**Comment by NullMDR** [comment]
Hi @astauben it's because you introduced a breaking change in swagger in api version 2019-01-20 which updates the enum but SDK and cli didn't get update and release. I suggest sending SDK release request for this change or maybe request cli update on kusto.

**Comment by NullMDR** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/6197/files#diff-8cd41463a9cc7c1a75a89c3aec008e2dR1532-R1543 FYI

**Comment by RakeshMohanMSFT** [comment]
This is working. `az kusto cluster create -l australiaeast -n Issue14769kustocluster -g Issue14769 --sku "Standard_D14_v2" --capacity 2`

Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
