### ISSUE TITLE
Update Verbiage for az policy definition command

### ISSUE THREAD

**Issue by RDukes425** [Azure/azure-cli#14760]
I received feedback from a customer regarding the verbiage of reunning the az policy definition update command. Currently the verbiage defines the --management-group parameter as the name of the management group, however the command is not successful unless you use the Management Group ID. 

Can you please update this section to have the Parameter Definition updates from Management Group Name (or Display Name) to Management Group ID

Reference: https://docs.microsoft.com/en-us/cli/azure/policy/definition?view=azure-cli-latest#az-policy-definition-create-optional-parameters
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 436bf02d-dfe3-ef6e-2be8-1bd7b1f39623
* Version Independent ID: e8b92df3-9e3d-c4c7-1965-0b6b3f7d00ea
* Content: [az policy definition](https://docs.microsoft.com/en-us/cli/azure/policy/definition?view=azure-cli-latest#az-policy-definition-create-optional-parameters)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S175

**Comment by zhoxing-ms** [comment]
@RDukes425 Hi, in fact, command `policy definition create` supports the parameter `--management-group` to pass in the name of the management group.

> I received feedback from a customer regarding the verbiage of reunning the az policy definition update command. Currently the verbiage defines the --management-group parameter as the name of the management group, however the command is not successful unless you use the Management Group ID.

What is the error when the customer passed in the name of management group? This may be due to some other problems, which need to be investigated

**Comment by yonzhan** [comment]
@RDukes425  any feedback?
