### ISSUE TITLE
Unable to force delete backupvault

### ISSUE THREAD

**Issue by Bobchev** [Azure/azure-cli#14776]
## Describe the bug

**Command Name**
`az backup vault delete`

**Errors:**
```
Container not found. Please provide a valid container_name.
Traceback (most recent call last):
cli/command_modules/backup/custom.py, ln 79, in delete_vault
    client.delete(resource_group_name, vault_name)
mgmt/recoveryservices/operations/vaults_operations.py, ln 353, in delete
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: ServiceResourceNotEmptyWithBackendMessage
Message: Vault cannot be deleted as there are existing resources within the vault. : Server2
Please ensure all containers have been unregistered from the vault and all private endpoints associated with the vault have been deleted, and retry operation. For more details, see https://aka.ms/AB-AA4ecq5

...

cli/command_modules/backup/custom.py, ln 848, in _validate_object
    raise ValueError(error_message)
ValueError: Container not found. Please provide a valid container_name.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup vault delete --resource-group {} --name {} --force`

## Environment Summary
```
Linux-4.15.0-1092-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.9.1 *

```

**Comment by yonzhan** [comment]
backup

**Comment by mepand** [comment]
@Bobchev If you don't want to be prompted for the confirmation of deletion, please execute the command with --yes. However, there would still be a check to identify if there are existing protected items or registered containers with the vault. There is some issue with --force parameter, we will fix it at our end . Also, please ensure that the vault name you are passing in the command is correct.

**Comment by mepand** [comment]
@Bobchev could you please confirm if the issue has been resolved for you?

**Comment by mepand** [comment]
Suggested the workaround. Closing the issue since there is no further action pending at our end. We will triage the permanent fix internally.
