### ISSUE TITLE
Issues with the `az vm wait --custom` flag

### ISSUE THREAD

**Issue by yeroc-sebrof** [Azure/azure-cli#14775]
## Describe the bug

The `az vm wait` command when using `--custom` crashes when I am attempting to use it. Using the example provided by [the documentation](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-wait) this crash will persist. I am trying to wait for either a stopped or deallocated state but it appears I am unable to wait for one of the two at this time.

**Command Name**
`az vm wait`

**Errors:**
```
Bad jmespath expression: Unknown token /:
instanceView.statuses[?code==PowerState/running]
                                       ^
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/jmespath/parser.py, ln 109, in _parse
    self._tokens = list(self.tokenizer)
python3.6/site-packages/jmespath/lexer.py, ln 109, in tokenize
    message="Unknown token %s" % self._current)
jmespath.exceptions.LexerError: Bad jmespath expression: Unknown token /:
instanceView.statuses[?code==PowerState/running]
                                       ^
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az vm wait --resource-group $RESOURCE_GROUP --name $VM_NAME --custom instanceView.statuses[?code==PowerState/running]`
  - Or instanceView.statuses[?code==PowerState/deallocated] or instanceView.statuses[?code==PowerState/stopped]

## Environment Summary
```
Linux-5.3.0-64-generic-x86_64-with
Python 3.6.9

azure-cli 2.2.0 *

```

**Comment by Juliehzl** [comment]
@qwordy  could you help with this issue?

**Comment by qwordy** [comment]
This issue is confirmed. I get the same result as you. I am locating the fault.

**Comment by qwordy** [comment]
Try this command. It works in PowerShell.
```
az vm wait -g fy3 -n vm --custom "instanceView.statuses[?code=='PowerState/running']"
```

**Comment by yeroc-sebrof** [comment]
Ah, thank you that command works for me also
