### ISSUE TITLE
az : AllowVnetToVnetTraffic flag in VirtualWan is not supported

### ISSUE THREAD

**Issue by AshwinSarimin** [Azure/azure-cli#14772]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When creating an virtual wan with the azure cli virtual-wan extension with the parameter --vnet-to-vnet-traffic on $true , i get the error: az : AllowVnetToVnetTraffic flag in VirtualWan is not supported.

**To Reproduce**
 az network vwan create --name $vwanname `
        --resource-group $rg `
        --branch-to-branch-traffic $true `
        --disable-vpn-encryption $false `
        --location $vwanlocation `
        --type $vwantype `
        --vnet-to-vnet-traffic $true `

**Expected behavior**
Create an Azure Virtual WAN with the vnet-to-vnet setting on true

**Environment summary**
azure-cli                         2.10.1

**Additional context**

**Comment by yonzhan** [comment]
add to S175

**Comment by jsntcy** [comment]
@dedhar, could you help take a look this issue?

It seems it's a regression issue (allowVnetToVnetTraffic is missing in http response from service side) in service side on 2020-05--01 as there is no such issue in previous version before 2020-05-01.

Below are http logs for calling 2020-05-01 and 2018-08-01:

- **Use 2020-05-01**:

> msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/azure-cli-test-rg/providers/Microsoft.Network/virtualWans/myvwan5?api-version=2020-05-01
> msrest.http_logger : Request method: 'PUT''
> 
> msrest.http_logger : Request body:
> msrest.http_logger : {"location": "westus", "properties": {"allowVnetToVnetTraffic": true}}`
> 
> msrest.http_logger : Response content:
> msrest.http_logger : {
>   "name": "myvwan5",
>   "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/azure-cli-test-rg/providers/Microsoft.Network/virtualWans/myvwan5",
>   "etag": "W/\"624a2deb-09b1-4d78-864e-0e2058bf276b\"",
>   "type": "Microsoft.Network/virtualWans",
>   "location": "westus",
>   "properties": {
>     "disableVpnEncryption": false,
>     "allowBranchToBranchTraffic": true,
>     "office365LocalBreakoutCategory": "None",
>     "type": "Standard"
>   }
> }
> 

- **Use 2018-08-01**

> msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/azure-cli-test-rg/providers/Microsoft.Network/virtualWans/myvwan-old?api-version=2018-08-01'
> msrest.http_logger : Request method: 'PUT'
> 
> msrest.http_logger : Request body:
> msrest.http_logger : {"location": "westus", "properties": {"allowVnetToVnetTraffic": true}}
> 
> msrest.http_logger : Response content:
> msrest.http_logger : {
>   "name": "myvwan-old",
>   "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/azure-cli-test-rg/providers/Microsoft.Network/virtualWans/myvwan-old",
>   "etag": "W/\"76b3c6d0-cffb-4894-8c89-994604e191f3\"",
>   "type": "Microsoft.Network/virtualWans",
>   "location": "westus",
>   "properties": {
>     "provisioningState": "Succeeded",
>     "disableVpnEncryption": false,
>     "allowBranchToBranchTraffic": true,
>     "allowVnetToVnetTraffic": true,
>     "office365LocalBreakoutCategory": "None"
>   }
> }
>

**Comment by jsntcy** [comment]
@AshwinSarimin, Confirmed from service team, --vnet-to-vnet-traffic is deprecated in 2020-05-01 which azure cli 2.10.1 uses. CLI will remove this argument from the command `az network vwan create`.
