### ISSUE TITLE
acs: kubernetes browse command could be confusing

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1477]
From looking at #1476, it seems like `acs browse ...` could be rather confusing with kubernetes.

It won't give the correct results in the user hasn't executed `acs kubernetes get-credentials`, or if their current kubeconfig context is set to a different cluster.

Maybe it should use `get-credentials` to pull it down to a temp dir, then call `kubectl proxy` with the right kubeconfig path or set KUBECONFIG before invoking it.

Does the merge logic change the current context? I didn't look at it that closely.

CC: @brendandburns

**Comment by brendandburns** [comment]
merge logic does change the context.

but you're right we should prob. download the existing context to a temp file and feed that into the kubectl proxy...
