### ISSUE TITLE
Prompt consent for APM migration from 2.0 to 2.1

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#14787]
**Resource Provider**
Microsoft.Insights

**Description of Feature or Work Requested**
In the following two scenarios, Azure CLI need prompt consent to users:
- If it’s a classic AI (no workspace linked) and the users want it to link to a workspace with workspace-context permissions (enableLogAccessUsingOnlyResourcePermissions = false).
- If the AI links with a workspace with resource-context permissions (enableLogAccessUsingOnlyResourcePermissions = true), and the users want it to link to another workspace with workspace-context permissions (enableLogAccessUsingOnlyResourcePermissions = false).

Advisory text to use for consent prompt: 

“Specified workspace is configured with workspace-based access mode. Some APM features may be impacted. Please refer to https://aka.ms/apm-workspace-access-mode for details.”

Terms:
- APM 2.0 – classic AI (no AI/LA integration)
- APM 2.1 – workspace-based AI (WS-centric RBAC required)
- APM 3.0 – resource-centric AI (resource-centric only RBAC acceptable)

**Minimum API Version Required**

**Swagger Link**

**Target Date**
2020-09-14

**Comment by yonzhan** [comment]
This is for Ignite
