### ISSUE TITLE
`az role assignment list` breaks with trailing slash

### ISSUE THREAD

**Issue by ehashman** [Azure/azure-cli#14782]
**Describe the bug**

When providing a `--scope` argument to `az role assignment list`, if a trailing slash is accidentally included, the CLI gives a non-descriptive error "Invalid scope. Please use --help to view the valid format."

**To Reproduce**

Using a valid subscription, run e.g.

```
$ az role assignment list --scope /subscriptions/<subscription_id>/resourceGroups/<resource_group>/
Invalid scope. Please use --help to view the valid format.
```

**Expected behavior**

Our customer expected either a clear error or this to remove the trailing slash and work as intended.

When you run the help command, it isn't entirely obvious that a trailing slash is not supported:

```
$ az role assignment list -h
...
    --scope                          : Scope at which the role assignment or definition applies to,
                                       e.g., /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333,
                                       /subscriptions/0b1f6471-1bf0-4dda-
                                       aec3-111122223333/resourceGroups/myGroup, or
                                       /subscriptions/0b1f6471-1bf0-4dda-aec3-111122223333/resourceG
                                       roups/myGroup/providers/Microsoft.Compute/virtualMachines/myV
                                       M.
```

**Environment summary**

```
$ az --version
azure-cli                         2.10.1

command-modules-nspkg              2.0.3
core                              2.10.1
nspkg                              3.0.4
telemetry                          1.0.4

...

Your CLI is up-to-date.
```

**Additional context**

An Azure Red Hat OpenShift customer encountered this issue when they needed to update role assignments on a VNet and a trailing slash was accidentally included in the commands run. The error provided was not helpful and they were not able to determine the cause of the error without support.

**Comment by yonzhan** [comment]
add to S175

**Comment by RakeshMohanMSFT** [comment]
This is as designed. There are many possible errors that could a user commit, it would be difficult to address them all.

**Comment by ehashman** [comment]
I don't really agree as the URL is valid both with and without trailing slash.
