### ISSUE TITLE
Webapp:az webapp create fails because Azure CLI reports app service exists in a different resource group then specified (which is not the case)

### ISSUE THREAD

**Issue by sanderaernouts** [Azure/azure-cli#14788]
## Describe the bug
We can no longer run out deployment scripts against out PROD environment since Azure CLI has been updated to `2.10.1`
**Command Name**
`az webapp create`

**Errors:**
```
The webapp '<app-service>' exists in resource group '<group>_devtest' and does not match the value entered '<group>'. Please re-run command with the correct parameters.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create --resource-group {} --name {} --plan {} --only-show-errors`

## Expected Behavior
The command should pass without making any changes since the web app already exists

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.10.1

```
## Additional Context
The app service we create here already exists in the resource group `<group>` and not in `<group>_devtest`.  `<group>_devtest` is a resource group we use for DEV purposes and there is and there is an app service named  '<app-service>-dev' in there. As of this version of the Azure CLI some check seems to indicate that the app service is in a different resource group then it really is
`az webapp show --resource-group {} --name {}` with the same name an resource group returns the app service object as well

**Comment by yonzhan** [comment]
webapp

**Comment by sanderaernouts** [comment]
Thanks @qwordy for fixing this 👍

**Comment by sanderaernouts** [comment]
Thanks @calvinsID for fixing this 👍
