### ISSUE TITLE
Webapp:Enable AI on web app

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#14789]
**Resource Provider**
Microsoft.Insights

**Description of Feature or Work Requested**
We add all functionalities in AI commands instead of in web app commands for APM 2.1.

`az monitor app-insights component connect-webapp –ids resource-id-for-webapp --enable-profiler false --enable-snapshot-debugger`
`az monitor app-insights component connect-webapp -g rg -n myApp --enable-profiler false --enable-snapshot-debugger`

We’ll tell users that –enable-profiler/debugger are currently only supported for .NET/.NET Core Web Apps in help document.

**Minimum API Version Required**

**Swagger Link**

**Target Date**

**Comment by yonzhan** [comment]
for ignite
