### ISSUE TITLE
Self signed certificate error

### ISSUE THREAD

**Issue by amchaney** [Azure/azure-cli#14793]
## Describe the bug

**Command Name**
`az dls fs list`

**Errors:**
```
HTTP error: SSLError(MaxRetryError("HTTPSConnectionPool(host='lcadlproddatalake.azuredatalakestore.net', port=443): Max retries exceeded with url: /webhdfs/v1/data/lcc/raw/PartitionDateKey%3D2020-08-11/PartitionTypeKey%3DAnalyticThermostatMessage?OP=LISTSTATUS&api-version=2018-09-01&listSize=4000 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))"))
Traceback (most recent call last):
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az dls fs list --account {} --path {}`

## Environment Summary
```
macOS-10.15.6-x86_64-i386-64bit
Python 3.8.5
Installer: HOMEBREW

azure-cli 2.10.1

```
## Additional Context
I've run the command s_client -showcerts -connect microsoft.com:443 in openssl and didn't see any self signed certs.  I also get this when i run the GUI file explorer, but then i can run with the ignore flag and it will succeed.

**Comment by amchaney** [comment]
due to corporate VPN

**Comment by JohnKeippel** [comment]
> due to corporate VPN

What do you mean? I modified my CA bundle but I can only properly execute Az commands when not connected to our corp VPN. Did you add a particular certs to your CA bundle to resolve the issue? Thanks for any help.
