### ISSUE TITLE
Enable AI for Functions

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#14790]
**Resource Provider**
Microsoft.Insights

**Description of Feature or Work Requested**
We add all functionalities in AI commands instead of in functions commands for APM 2.1.

**Add a new command**
`az monitor app-insights component connect-function –g rg -app myAI --function resource-id-for-function`  (using function resource id)
`az monitor app-insights component connect-function –g rg -app myAI --function name-of-function` (using function name)

**Minimum API Version Required**

**Swagger Link**

**Target Date**

**Comment by yonzhan** [comment]
feature request
