### ISSUE TITLE
unable to install in mac

### ISSUE THREAD

**Issue by quantrpeter** [Azure/azure-cli#14794]
Hi
    latest mac os, installed python and az by homebrew. Bug:

```
/Users/peter>which az
/usr/local/bin/az
/Users/peter>az
/usr/local/opt/python@3.8/bin/python3.8: Error while finding module specification for 'azure.cli' (ModuleNotFoundError: No module named 'azure')
/Users/peter>/usr/local/bin/az

     /\
    /  \    _____   _ _  ___ _
   / /\ \  |_  / | | | \'__/ _\
  / ____ \  / /| |_| | | |  __/
 /_/    \_\/___|\__,_|_|  \___|


Welcome to the cool new Azure CLI!
```

thanks
Peter

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to have a look?

**Comment by fengzhou-msft** [comment]
@quantrpeter please check your `$PATH` environment variable and add `/usr/local/bin` if not in there.

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please feel free to open new issues if the latest version of Azure CLI still does not work for you.
