### ISSUE TITLE
[Storage] Retrieve credentials for batch-copy operations when possible

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1479]
When copying between two storage accounts within the same subscription, we can attempt to retrieve the storage account keys as needed to perform the operation. This would require you to be logged in and have permission to access the storage account keys.

**Comment by valencik** [comment]
This would be very nice, as currently we have to generate a SAS separately.
e.g. https://github.com/Azure/azure-cli/issues/1527#issuecomment-272280141
