### ISSUE TITLE
Cannot create a mongodb collection using azure cli with an index policy

### ISSUE THREAD

**Issue by nadworny** [Azure/azure-cli#14792]
## Describe the bug

**Command Name**
`az cosmosdb mongodb collection create`

**Errors:**
```
Unable to build a model: Cannot deserialize as [MongoIndex] an object of type <class 'dict'>, DeserializationError: Cannot deserialize as [MongoIndex] an object of type <class 'dict'>
Traceback (most recent call last):
Temp\pip-unpacked-wheel-ib_p0vwa\msrest\serialization.py, ln 571, in body
Temp\pip-unpacked-wheel-ib_p0vwa\msrest\serialization.py, ln 1261, in _deserialize
Temp\pip-unpacked-wheel-ib_p0vwa\msrest\serialization.py, ln 1261, in _deserialize
...
msrest.exceptions.SerializationError: Unable to build a model: Cannot deserialize as [MongoIndex] an object of type <class 'dict'>, DeserializationError: Cannot deserialize as [MongoIndex] an object of type <class 'dict'>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cosmosdb mongodb collection create -a {} -g {} -d {} -n {} --shard {} --throughput {} --idx {}`

index.json
```
{
  "indexingMode": "consistent",
  "includedPaths": [
    {
      "path": "/*",
      "indexes": [
        {
          "kind": "Range",
          "dataType": "Number",
          "precision": -1
        },
        {
          "kind": "Range",
          "dataType": "String",
          "precision": -1
        }
      ]
    }
  ],
  "excludedPaths": [
    {
      "path": "/path/to/single/excluded/property/?"
    },
    {
      "path": "/path/to/root/of/multiple/excluded/properties/*"
    }
  ]
}
```

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.10.1

Extensions:
azure-devops 0.17.0

```

**Comment by nadworny** [comment]
I'm one step further - the index.json has to be an array. So adding "[" and "]" fixed the first issue (btw please update your documentation as everywhere it's in a dict format --> https://docs.microsoft.com/en-us/azure/cosmos-db/manage-with-cli#create-a-container-with-a-custom-index-policy)

Now when I execute the command I get:
```
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxx/collections/processingMetadata?api-version=2020-04-01 (Caused by ResponseError('too many 500 error responses',))
```

**Comment by yonzhan** [comment]
cosmosdb

**Comment by MehaKaushik** [comment]
Thanks @nadworny for bringing this to our notice. Is there any other issue you are facing ?

**Comment by markjbrown** [comment]
You can't use an index policy for SQL API for a MongoDB collection.

Please refer to the example here for how to create indexes for MongoDB API collection.
https://docs.microsoft.com/en-us/azure/cosmos-db/scripts/cli/mongodb/create

Thanks.

**Comment by nadworny** [comment]
@markjbrown my bad! Thanks for a tip!

I've just tried with the following index file:
```
[
  {
    "key": {
      "keys": [
        "_id",
        "modifiedDate"
      ]
    }
  }
]
```

But now I get this error: `Index definition does not contains '_id' index specification.`

1. Any idea what am I doing wrong? 

1. Also, for the _modifiedDate_ field I would like to define an index with sorting DESC, in mongodb this would be { "modifiedDate" : -1 }

**Comment by MehaKaushik** [comment]
Hey @nadworny 

1. For Mongo 3.6 with apiVersion >=2020-04-01 _id is a required index. An index with a single key, equal to _id should be present.
 "key": {"keys": ["_id"]}

2. When creating indexes using Rest-API for Azure resource manager, there is no way to provide the sorting. By default, the sort order is set to 1. This is a known system limitation and we hope to fix it in the future. But no tentative timeline exists.

**Comment by nadworny** [comment]
Thanks @MehaKaushik 

I've just splitted and created both indices and it works:
```
[
  {
    "key": {
      "keys": [
        "_id"
      ]
    }
  },
  {
    "key": {
      "keys": [
        "modifiedDate"
      ]
    }
  }
]
```

**Comment by MehaKaushik** [comment]
@nadworny glad to hear.
