### ISSUE TITLE
CONTRIBUTING.rst has a broken link

### ISSUE THREAD

**Issue by mgrandi** [Azure/azure-cli#14796]
**Describe the bug**
https://github.com/Azure/azure-cli/blob/dev/CONTRIBUTING.rst at revision  5173fd1 has a broken link, the `Microsoft Azure Projects Contribution Guidelines` link goes to `http://azure.github.io/guidelines.html` which is a HTTP 404

**To Reproduce**
click on the link in CONTRIBUTING.rst

**Expected behavior**
that it should link to a page where it shows the azure project contribution guidelines

**Environment summary**
N/A

**Additional context**
N/A

**Comment by yonzhan** [comment]
add to S175

**Comment by Juliehzl** [comment]
Hi @mgrandi, I think the right cod you want should be https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules.

**Comment by Juliehzl** [comment]
please also sync with the latest dev branch

**Comment by Juliehzl** [comment]
I think we lose it now.
To contribute the code, you could just build your developer environment and write code according to https://github.com/Azure/azure-cli#developer-setup
