### ISSUE TITLE
Set access policy for app configuration

### ISSUE THREAD

**Issue by ashinzekene** [Azure/azure-cli#14809]
Please is there a script for setting access policies using managed identities for app configuration. I can't seem to find it on this page
Something like [az keyvault set-policy](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az-keyvault-set-policy)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 141619ee-fd83-7493-88a3-afd818d6c56e
* Version Independent ID: 25e4c840-d438-02ef-2363-77b9616f006b
* Content: [az appconfig](https://docs.microsoft.com/en-us/cli/azure/appconfig?view=azure-cli-latest#az-appconfig-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/appconfig/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appconfig/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
appconfig

**Comment by avanigupta** [comment]
Hello @ashinzekene , the command group [az appconfig identity](https://docs.microsoft.com/en-us/cli/azure/appconfig/identity?view=azure-cli-latest) can be used to assign/remove/show managed identities. You can also assign managed identity during store creation by specifying `--assign-identity` argument with the command [az appconfig create](https://docs.microsoft.com/en-us/cli/azure/appconfig?view=azure-cli-latest#az-appconfig-create).

**Comment by ashinzekene** [comment]
The first use case was what I was looking for. Thank you @avanigupta 

Might be useful to have it here
https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-integrate-azure-managed-service-identity?tabs=core2x

**Comment by avanigupta** [comment]
Thanks for the feedback @ashinzekene. We have created a work item to add this to our documentation.

**Comment by ashinzekene** [comment]
I have an issue with this @avanigupta 

After running this and verifying that a resource has been assigned the given role
```
az role assignment create \
    --role "App Configuration Data Reader" \
    --assignee $functionPrincipalId \
    --scope $appConfigId
```


This return an empty object
```
az role assignment list \
    --role "App Configuration Data Reader" \
    --assignee $functionPrincipalId
```

**Comment by avanigupta** [comment]
Hi @ashinzekene, I was able to list the role assignment by using `--scope` filter instead of `--assignee`. Will that work for you?

`az role assignment list --role "App Configuration Data Reader" --scope $appConfigId`

I'm not sure why we can't filter based on `--assignee`. Feel free to create an issue for [az role assignment list](https://docs.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest#az-role-assignment-list) documentation to reach out to the right team who can help debug this further.

**Comment by ashinzekene** [comment]
Thanks. This works

**Comment by ashinzekene** [comment]
Sorry if it feels like I'm bothering, but when I run this on `ev2`
```
az role assignment create \
    --role "App Configuration Data Reader" \
    --assignee $functionPrincipalId \
    --scope $appConfigId
```
I get

` Operation failed with status: 'Forbidden'. Details: 403 Client Error: Forbidden for url: https://graph.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/getObjectsByObjectIds?api-version=1.6`


I don't know if you're familiar with this type of error

**Comment by avanigupta** [comment]
Hi @ashinzekene, it looks like the user or service principal logged in to Azure CLI does not have permission to create this role assignment. Please make sure you are using the same credentials on EV2 which were working for you on non-EV2. 
Could you please run `az account show` to make sure you are logged in with the right credentials?

**Comment by ashinzekene** [comment]
Thanks

**Comment by navba-MSFT** [comment]
@ashinzekene Apologies for the late reply. This issue is open for quite sometime. Could you please let us know if you need any further assistance on this ? Awaiting your reply.
