### ISSUE TITLE
[Breadth Coverage] Onboard Azure Stack HCI Commands

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#14804]
**Spec Link**
https://microsoft.sharepoint.com/:w:/t/AzureManagementExperience/ESUpnBLbm3xEvFpNLxn25kYB3X7hHr10LNZlpDcT9OFJ3Q?e=XYCASy

**ADO Work Item Link**
https://dev.azure.com/azure-mgmt-ex/Onboarding/_workitems/edit/2757

**Resource Provider**
What is the Azure resource provider your feature is part of?
Microsoft.AzureStackHCI

**Description of Feature or Work Requested**
Support Azure CLI commands for AzureStackHCI

**Minimum API Version Required**
2020-03-01-preview

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/azurestackhci/resource-manager

**Python SDK Link**
Not necessary, CodeGen will generate it automatically when generating CLI code.

**Target Date**
09/21/2020

CodeGen Validation Contact:
Xiao Chen

**Addtional context**
We'll use [autorest.az](https://github.com/Azure/autorest.az/blob/master/doc/how-to-generate.md) from code gen team to auto-generate the code first and may need update some code manually if the generated code doesn't meet your requirements.

**Comment by yonzhan** [comment]
for Ignite
