### ISSUE TITLE
dockerfile: add dockerignore override support

### ISSUE THREAD

**Issue by luigibk** [Azure/azure-cli#14811]
**Is your feature request related to a problem? Please describe.**

There is currently no way to specify (or override) the `.dockerignore` file in the `acr build` command. This prevents multiple Dockerfile(s) to share the same context effectively.

**Describe the solution you'd like**

I suggest that different Dockerfiles define different subsets of the context files.
The frontend (e.g. `acr build`) first checks for <path/to/Dockerfile>.dockerignore and if it is found it will be used instead of the root .dockerignore. 

This would be consistent with the docker behaviour implemented in:
https://github.com/moby/buildkit/pull/901

**Describe alternatives you've considered**

The alternative is to overwrite the .dockerignore file(s) at build time, only this prevents concurrent builds as there is no control over which .dockerignore file is used by which build thread.  Not that I can see at least

**Additional context**

It seems to me it would be fairly simple to modify:

https://github.com/Azure/azure-cli/blob/438cc0a9fb7f4ca2c99cadbfbc96cd7ea27fadaa/src/azure-cli/azure/cli/command_modules/acr/_archive_utils.py#L147

to introduce this change. 

Would you accept a PR?

**Comment by yonzhan** [comment]
acr

**Comment by yugangw-msft** [comment]
+ @northtyphoon to comment
