### ISSUE TITLE
az image builder list returns duplicate results

### ISSUE THREAD

**Issue by feiyushi** [Azure/azure-cli#14813]
## Describe the bug

**Command Name**
`az image builder list`

**Errors:**
Duplicate results showed:
BuildTimeoutInMinutes    Location       Name                 ProvisioningState    ResourceGroup

0                        eastus         eus                  Succeeded            prod
0                        eastus         identity-test        Succeeded           prod
0                        westcentralus  wcu                  Succeeded            prod
0                        eastus         eus                  Succeeded            prod
0                        eastus         identity-test        Succeeded            prod
0                        westcentralus  wcu                  Succeeded            prod
0                        northeurope    neu                  Succeeded            prod
8                        northeurope    northeurope_timeout  Succeeded           prod
0                        westeurope     weu                  Succeeded            prod
0                        northeurope    neu                  Succeeded            prod
8                        northeurope    northeurope_timeout  Succeeded            prod
0                        westeurope     weu                  Succeeded           prod

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image builder list -g {} --subscription {} -o {}`

## Environment Summary
```
Linux-5.4.0-42-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.10.1

Extensions:
azure-devops 0.18.0
aks-preview 0.4.57

```

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look? thanks

**Comment by qwordy** [comment]
Hi Feiyu, what's the result of calling Azure REST API to list templates?

**Comment by feiyushi** [comment]
it's filed in the bug under `Errors`

**Comment by qwordy** [comment]
Sorry. I don't understand. More details?
CLI doesn't add custom logic for show and list command. It's a wired problem. Let's first check if calling RESP API directly works.

**Comment by feiyushi** [comment]
I'm sorry that I misunderstood the question.
I added `--debug` to `az image builder list` and it contains duplicate results.
I then used `az resource list --resource-type Microsoft.VirtualMachineImages/imageTemplates` to list the templates, it doesn't contain the duplicates.
By invoking REST API directly `http GET https://management.azure.com/subscriptions/{sub-id}/resourceGroups/{rg-name}/providers/Microsoft.VirtualMachineImages/imageTemplates?api-version=2020-02-14` it gives me duplicates, which is the same API that's used by the `az image builder list`.
I'll check ARM and RP logs later and report back

**Comment by feiyushi** [comment]
Confirmed that this is a service bug. I've logged a bug and am closing this bug.
Thanks for taking a look!

**Comment by qwordy** [comment]
You are welcome!

**Comment by feiyushi** [comment]
Reporting back. This is now fixed.
