### ISSUE TITLE
Webapp:I tried to use --xml option in az webapp deployment list-publishing-profiles but I can't

### ISSUE THREAD

**Issue by richardlm57** [Azure/azure-cli#14820]
I tried to use --xml option in az webapp deployment list-publishing-profiles but I can't. Those are the option I have available from Azure CLI

![AzureCLIIssue](https://user-images.githubusercontent.com/10284438/90476307-81066000-e0e6-11ea-8baf-e2e7dfdff600.png)

With this, I can assume there is an issue with the documentation, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26f21f9c-7323-9caa-deeb-00e714a8d0ca
* Version Independent ID: c6d509be-937f-e228-17a7-570d275b6fa4
* Content: [az webapp deployment](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/deployment.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/deployment.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@richardlm57 I can't tell the version of CLI you are currently using --xml option is a newly added support so you need to be on the latest version of CLI which is 2.10.1. Please update if needed & let us know if you still see this. Thanks!

**Comment by richardlm57** [comment]
My apologies, indeed the Azure CLI version was the issue from my side. Thanks!

**Comment by panchagnula** [comment]
Thanks for the confirmation will close this

**Comment by kclubbresideo** [comment]
I am running az 2.48.1 but the --xml does not work.
PS C:\Users\275527\repo\Super-Aggregator> az --version
azure-cli                         2.48.1

core                              2.48.1
telemetry                          1.0.8

Extensions:
azure-iot                         0.14.1

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\275527\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
