### ISSUE TITLE
webapp : Migrate vsts dependency to azure-devops

### ISSUE THREAD

**Issue by arrownj** [Azure/azure-cli#14821]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Currently `appservice` depends on `vsts` which is not maintained anymore. There will be no further support for this package if there are bugs for feature requests. The `vsts` package is migrated to [`azure-devops`](https://github.com/microsoft/azure-devops-python-api).

This is a request to migrate `vsts` to `azure-devops` in CLI side.

**Describe alternatives you've considered**

**Additional context**

**Comment by arrownj** [comment]
Hi @panchagnula , could you please help check this ? Thanks

**Comment by panchagnula** [comment]
ACK @arrownj will take a look just to be sure is this the one you are referring to https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/vsts_cd_provider.py 

Can you point me to the new vets package on devops so I can update the references & test on our end? Thanks!

**Comment by btardif** [comment]
@panchagnula is this still relevant?

**Comment by Kotasudhakarreddy** [comment]
> ACK @arrownj will take a look just to be sure is this the one you are referring to https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/vsts_cd_provider.py
> 
> Can you point me to the new vets package on devops so I can update the references & test on our end? Thanks!

@arrownj - could you respond here.

**Comment by qwordy** [comment]
Hi Kota, 

I read the issue, read the code and searched information.
We advise to deprecate vsts-cd-manager and use azure-devops instead. vsts-cd-manager is not maintained now.

Please search
from .vsts_cd_provider import VstsContinuousDeliveryProvider
from vsts_cd_manager.continuous_delivery_manager import ContinuousDeliveryManager
in code.

https://pypi.org/project/vsts-cd-manager/
https://github.com/microsoft/vsts-cd-manager
https://pypi.org/project/azure-devops/
https://github.com/microsoft/azure-devops-python-api

**Comment by Kotasudhakarreddy** [comment]
@qwordy - thanks. Will check and get back to you for any clarifications.

**Comment by qwordy** [comment]
Hi @Kotasudhakarreddy , is there any update?

**Comment by Kotasudhakarreddy** [comment]
@qwordy I am on it. Targeted for S183.

**Comment by panchagnula** [comment]
@calvinsID assigning this to you to help identify the right functions with the new library for parity 
this file needs to be updated
from vsts_cd_manager.continuous_delivery_manager import ContinuousDeliveryManager
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/vsts_cd_provider.py 

Old: https://github.com/microsoft/vsts-cd-manager
New: https://github.com/microsoft/azure-devops-python-api

**Comment by calvinsID** [comment]
Created this item to track moving `az functionapp devops-pipeline create` command, which pulls in vsts package, to an extension to reduce weight: #18228

**Comment by seligj95** [comment]
this is complete
