### ISSUE TITLE
Can't use 'az component' as-is

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1482]

**Comment by colemickens** [comment]
```
$ az component update --add keyvault                                                                       21:53:55
    100% |████████████████████████████████| 102kB 1.5MB/s
    100% |████████████████████████████████| 583kB 1.6MB/s
Permission denied. Run command with --debug for more information.
If executing az with sudo, you may want sudo's -E and -H flags.
```

**Comment by colemickens** [comment]
I install `az` via `pip --upgrade --user install azure-cli`. I have no intention of running `az` as root.

How do I use `keyvault` module then?

**Comment by derekbekoe** [comment]
Can you run `which az`? There may be multiple instances of az on the machine.
'Permission Denied' usually means the instance is installed in a global location and so pip requires sudo for this.

**Comment by colemickens** [comment]
```
$ which az
/home/cole/.local/bin/az

$ ls -a $(which az)
/home/cole/.local/bin/az

$ ls -al /usr/lib/python2.7/site-packages | grep azure                                                                                              

$ ls -al /usr/lib/python3.5/site-packages | grep azure
drwxr-xr-x   8 root root   4096 Nov 15 23:57 azurelinuxagent
```

**Comment by colemickens** [comment]
(I don't know what `az component` is doing, but if it's doing `pip install blah` then I'm not surprised it doesn't work. It would need to know, somehow, to do `pip install --user ...`.)

**Comment by colemickens** [comment]
Alternatively, if it just spit out the `pip` command that I need to run, that'd be more than fine.

**Comment by derekbekoe** [comment]
@colemickens thanks for pointing it out.
I'll look into determining if the --user flag is needed when `az component update` runs.
Until this is resolved, you can do `pip install --user azure-cli-keyvault`
