### ISSUE TITLE
Can't create VMSS in South Africa West

### ISSUE THREAD

**Issue by biltongza** [Azure/azure-cli#14837]
## Describe the bug
VMSS and VNets are indicated as generally available:

![image](https://user-images.githubusercontent.com/2845704/90615161-046da180-e20c-11ea-8583-71f33b2b375b.png)

https://azure.microsoft.com/en-us/global-infrastructure/services/?products=virtual-machine-scale-sets,virtual-network

However any attempt to create a vnet or VMSS with location = southafricawest fails. I am also not able to select South Africa West in the azure portal.

**Command Name**
`az vmss create`

**Errors:**
```
Azure Error: LocationNotAvailableForResourceType
Message: The provided location 'southafricawest' is not available for resource type 'Microsoft.Network/virtualNetworks'. List of available regions for the resource type is 'westus,eastus,northeurope,westeurope,eastasia,southeastasia,northcentralus,southcentralus,centralus,eastus2,japaneast,japanwest,brazilsouth,australiaeast,australiasoutheast,centralindia,southindia,westindia,canadacentral,canadaeast,westcentralus,westus2,ukwest,uksouth,koreacentral,koreasouth,francecentral,australiacentral,southafricanorth,uaenorth,switzerlandnorth,germanywestcentral,norwayeast'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss create --resource-group {} --name {} --public-ip-per-vm --image {} --instance-count {} --vm-sku {} --lb {} --nsg {} --computer-name-prefix {} --admin-username {} --location southafricawest --vnet-name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: 

azure-cli 2.7.0 *

```

**Comment by yungezz** [comment]
hi @biltongza from the description, service doesn't support VMSS in region South Africa West. Since you cannot do it either in azure cli or Potal. Involve service team to help on this. thanks.

**Comment by avirishuv** [comment]
Let me follow up on the availability of VMSS in this region.

**Comment by avirishuv** [comment]
@biltongza For region access related issues and requests, you can open a support request with our Support team. This document has helpful instructions for this: https://docs.microsoft.com/en-us/troubleshoot/azure/general/region-access-request-process

**Comment by avirishuv** [comment]
@biltongza I hope the document was helpful for your region access question. I'll close this issue, but please feel free to reopen if you need any further information on this topic here.
