### ISSUE TITLE
Error: az acr login- APIVersion 2019-12-01-preview is not available

### ISSUE THREAD

**Issue by harshbangad** [Azure/azure-cli#14844]
## Describe the bug

**Command Name**
`az acr login`

**Errors:**
```
APIVersion 2019-12-01-preview is not available
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/acr/_client_factory.py, ln 19, in cf_acr_registries
    return get_acr_service_client(cli_ctx).registries
azure/mgmt/containerregistry/container_registry_management_client.py, ln 208, in registries
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-12-01-preview is not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr login --name {}`

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-stretch-sid
Python 3.6.9
Installer: PIP

azure-cli 2.8.0 *
azure-cli-ml 1.9.0

Extensions:
azure-cli-ml 1.9.0

```

**Comment by yonzhan** [comment]
acr

**Comment by yugangw-msft** [comment]
This is installation issue

**Comment by fengzhou-msft** [comment]
@harshbangad are you using a VM? What is the sku? We would like to reproduce the issue.

**Comment by harshbangad** [comment]
@fengzhou-msft  So, i am trying to build my docker image in azure container registry as per this document
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-custom-docker-image#build-a-custom-base-image

I am using the terminal in Jupyterlab from a compute instance in Azure machine learning. Any new machine we spin up in azure fails with this error in the terminal. It fails at acr login with the error posted.

When i try to do this locally in my windows machine using powershell as admin, i am able to successfully login into acr but i get an error of access denied while trying to build my docker file, which is also a potential known windows issue.

Open to other suggestions on how to build the docker image on the container registry.

**Comment by hermandr** [comment]
I am experiencing this also when using the az commands in compute instance.
So I am running the az commands in local instance only.
Any response on how to fix this issue?

**Comment by fengzhou-msft** [comment]
If you used `pip install azure-cli` to install the package, please check `pip show azure-mgmt-containerregistry`. The latest `azure-cli` package uses `3.0.0rc15` of `azure-mgmt-containerregistry` which has APIVersion 2019-12-01-preview.

**Comment by fengzhou-msft** [comment]
The issue is caused by incompatibility versions of `azure-mgmt-containerregistry` on the Azure machine learning compute instance.
Can you try the following workaround by using a virtual environment?
https://github.com/Azure/azure-cli/issues/15627#issuecomment-716129300

**Comment by fengzhou-msft** [comment]
Close as this issue is caused by VM environment and workaround provided.
