### ISSUE TITLE
Azure CLI failing to finish/return from `az vm start ...` command

### ISSUE THREAD

**Issue by hobothulhu** [Azure/azure-cli#14841]
## Describe the bug
I have an Azure DevOps Release Pipeline with the Azure CLI task wherein I have this command run:
az vm start --resource-group GROUP --name NAME
Last week (the second week of August) the command had been running fine. As of around August 17th, the command began being stuck in the `in progress` state for up to >90 minutes before I manually canceled it. I repeated it several times, and noticed that the VM was indeed being started, just that the command never finished. I am able to reproduce this locally on my laptop with Azure CLI 2.10.1 as well. I have also tried this command on the Azure Portal cloud shell, where it works fine and finishes quickly. The similar `az vm stop` works fine on all locations, too.

**Command Name**
`az vm start`

**Errors:**
Command never finishes, seems stuck as `in progress`, although the VM is started.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm start --resource-group {} --name {} --debug`

## Expected Behavior
The command completes after VM is started, allowing either the Azure CLI release pipeline task to continue or the CLI command prompt to return to user.

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.10.1

```
## Additional Context
[azurecli1.txt](https://github.com/Azure/azure-cli/files/5097458/azurecli1.txt)
Including output of --debug command after letting it run for several minutes.
[azurecliPipeline.txt](https://github.com/Azure/azure-cli/files/5097472/azurecliPipeline.txt)
Including output of release pipeline task with debug setting.
Release pipeline is on Azure DevOps online, a la https://dev.azure.com/COMPANY

**Comment by yonzhan** [comment]
@yungezz will help you with this issue.

**Comment by yungezz** [comment]
hi @qwordy could you pls help to look at the issue? thanks.

**Comment by qwordy** [comment]
Azure CLI doesn't add custom logic to start operation. I suspect it's a service problem.
https://management.azure.com:443 "GET /subscriptions/6106db48-494a-4767-a0ca-689bb7c63c07/providers/Microsoft.Compute/locations/southcentralus/operations/fe776d73-a214-4ea9-8149-da276d98231a?api-version=2019-07-01 HTTP/1.1" always return inProgress even if the VM has started already.

**Comment by avirishuv** [comment]
I'll look into this issue

**Comment by hobothulhu** [comment]
@avirishuv Thank you for any aid. I can attest to the issue still occurring. I am happy to help if able.

**Comment by hobothulhu** [comment]
@avirishuv Have there been any findings?

**Comment by avirishuv** [comment]
Marking this as a bug. The CLI cmdlet az vm start --resource-group {} --name {} does not complete even though the VM finishes starting and reaches 'Running' state (this is reflected in portal as well as through get instance view API call).

**Comment by qwordy** [comment]
> 
> 
> Marking this as a bug. The CLI cmdlet az vm start --resource-group {} --name {} does not complete even though the VM finishes starting and reaches 'Running' state (this is reflected in portal as well as through get instance view API call).

Should we use https://management.azure.com:443 "GET /subscriptions/6106db48-494a-4767-a0ca-689bb7c63c07/providers/Microsoft.Compute/locations/southcentralus/operations/fe776d73-a214-4ea9-8149-da276d98231a?api-version=2019-07-01 HTTP/1.1 to check state?

**Comment by hobothulhu** [comment]
@qwordy To update the case, I am still experiencing this issue today. If I can do anything to help, please let me know.

**Comment by avirishuv** [comment]
hi @hobothulhu are there any additional steps after VM reaches Running state, for example extension provisioning? Such additional steps after Starting of the VM can take more time. And the Start operation will wait for these additional steps to complete.

**Comment by hobothulhu** [comment]
I'm not aware of any extensions like that. And this process had been functioning for 3-4 months before this began. My VM has two extensions: 1)TeamServicesAgentExtension and 2)SqlIaasExtension. I am not using the SqllaasExtension one, nor have I used it. The TeamServicesAgentExtension works fine to my eyes as well.

**Comment by avirishuv** [comment]
@hobothulhu thanks for the info, this helps. 
The extensions that you are using may be taking longer time to finish after the VM has started. This additional time is why the operation does not complete even though VM shows as Running, as the operation waits for the extensions to complete.

**Comment by avirishuv** [comment]
@hobothulhu hope that answers your question, or any other follow up needed?

**Comment by hobothulhu** [comment]
The issue no longer appears present after removing the `SqlIaasExtension`. I will create a new issue and reference this one if I re-encounter this issue. I appreciate your help, @avirishuv . I wish you a pleasant weekend!

**Comment by feacluster** [comment]
I am running into the same issue . az vm start hangs. Sometimes for 5 minutes. Sometimes forever until I kill it. But the machine starts ok. I am using 'az vm start' in an automated workflow. This hanging causes my workflow to take much longer than it should or hang also.

**Comment by Drewm3** [comment]
@feacluster, could you open a new issue with the details that you are seeing? It looks like the original problem described in this issue was with the SqlIaasExtension. If you are using that extension, then please see if the issue goes away if you remove that extension. If your issue is separate from the previous one, then please open a new issue for the CLI team to investigate.

**Comment by feacluster** [comment]
> @feacluster, could you open a new issue with the details that you are seeing? It looks like the original problem described in this issue was with the SqlIaasExtension. If you are using that extension, then please see if the issue goes away if you remove that extension. If your issue is separate from the previous one, then please open a new issue for the CLI team to investigate.

Sure, will do. I've opened a ticket through the support portal. So if still unresolved then will open a new issue here. I am not using SqlIaasExtension as far as I know..
