### ISSUE TITLE
example for the --plan option

### ISSUE THREAD

**Issue by hpourreza** [Azure/azure-cli#14852]
[Enter feedback here]
Is it possible to provide an example using the --plan option? All the examples use --urn. When I run az vm image show --urn <urn> it print json with plan section which has three subsections. how can I use this plan section to call az vm image terms with the --plan option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77a1361f-355d-9d60-4733-cd2d0d429985
* Version Independent ID: 5d85cdce-c9f0-c36a-486f-a8e3dda6c94f
* Content: [az vm image terms](https://docs.microsoft.com/en-us/cli/azure/vm/image/terms?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look?

**Comment by qwordy** [comment]
`--plan` represents for image billing plan. Can you show the plan section of `az vm image show --urn`?

**Comment by qwordy** [comment]
Close due to no reply.
