### ISSUE TITLE
Azure Cli-generated access token can not access Cloud Shell API's

### ISSUE THREAD

**Issue by maartenba** [Azure/azure-cli#14859]
Cross-post of https://github.com/microsoft/azure-tools-for-java/issues/4529, as I'm not sure which channel works best...

In the Azure Toolkit, I'm trying to integrate with Azure Clou Shell, setting up a console socket etc. This all works when using device login flow with another application id.

Now, I want to use the Azure CLI to manage authentication. This works for other features, but unfortunately the Azure CLI's client id (`04b07795-8ddb-461a-bbee-02f9e1bf7b46`) is not permitted to access the cloud shell APIs.

A request to Azure Cloud Shell:

```
GET https://management.azure.com/providers/Microsoft.Portal/userSettings/cloudconsole?api-version=2017-12-01-preview
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer xxxxxxxxx
```

Getting the following error response:

```
{
  "error": {
    "code": "ClientNotAllowed",
    "message": "The client with application Id '04b07795-8ddb-461a-bbee-02f9e1bf7b46' is not permitted to access this API."
  }
}
```

This is not an Azure CLI bug per-se, but a missing bit of configuration I believe only Microsoft can update.

So the question becomes: can access to the Cloud Shell API's be provided for client id/application id `04b07795-8ddb-461a-bbee-02f9e1bf7b46` (Azure CLI)?

**Comment by yonzhan** [comment]
Cloud Shell

**Comment by jiasli** [comment]
I think the [portal extension](https://github.com/Azure/azure-cli-extensions/tree/master/src/portal) may be responsible for this operation (in the future).

`https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Portal/dashboards` works well with Azure CLI's client ID and token.

```powershell
> az extension add --name portal

> az portal dashboard list --debug
...
azure.core.pipeline.policies.http_logging_policy : Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Portal/dashboards?api-version=REDACTED'
azure.core.pipeline.policies.http_logging_policy : Request method: 'GET'
...
azure.core.pipeline.policies.http_logging_policy : Response status: 200
```

But I got the same error with

```powershell
> az rest -u https://management.azure.com/providers/Microsoft.Portal/userSettings/cloudconsole?api-version=2017-12-01-preview
Bad Request({
  "error": {
    "code": "ClientNotAllowed",
    "message": "The client with application Id '04b07795-8ddb-461a-bbee-02f9e1bf7b46' is not permitted to access this API."
  }
})
```

\+ owner of portal extension @YalinLi0312 to help take a look.

**Comment by maartenba** [comment]
This seems to have been fixed now on the portal side.
