### ISSUE TITLE
Errors with dynamic extension install ?

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#14868]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Testing out new dynamic extension install feature

**To Reproduce**
1) az config set extension.run_after_dynamic_install=yes_without_prompt -- succeeded
![image](https://user-images.githubusercontent.com/30876406/90849966-6a9a1780-e325-11ea-9e15-398af23581c9.png)

2) run az mysql up -- failed
![image](https://user-images.githubusercontent.com/30876406/90849987-7685d980-e325-11ea-9451-e0b3eddaaaeb.png)

3)az databricks workspace create -- also failed
![image](https://user-images.githubusercontent.com/30876406/90850022-843b5f00-e325-11ea-8c47-93e03686448f.png)

**Expected behavior**
no fail

**Environment summary**
Windows
![image](https://user-images.githubusercontent.com/30876406/90850043-8ef5f400-e325-11ea-8d72-47a0c78cb61b.png)

**Additional context**
![image](https://user-images.githubusercontent.com/30876406/90850061-987f5c00-e325-11ea-8b97-785b2dff6fd8.png)

**Comment by chenlomis** [comment]
yes_prompt also failed:
![image](https://user-images.githubusercontent.com/30876406/90850355-4ee34100-e326-11ea-80bd-fc3a37a7e7f1.png)


but no and yes did not fail:
![image](https://user-images.githubusercontent.com/30876406/90850452-87831a80-e326-11ea-9f06-71f92b5a71be.png)

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help a look? thanks.

**Comment by fengzhou-msft** [comment]
`run_after_dynamic_install` is currently a boolean, only supports `yes` or `no` while `use_dynamic_install` is a string and supports `yes_prompt`, `yes_without_prompt`, `no`.

**Comment by chenlomis** [comment]
Oh okay. Thanks!
I see what happened here. Conflated the _use dynamic install_ with _run after dynamic install_

Awesome! Fixed the command and they worked
![image](https://user-images.githubusercontent.com/30876406/91001539-d5935a80-e580-11ea-9cb9-05511653fc3d.png)
