### ISSUE TITLE
Webapp:Cannot add access restriction for scm part of the Webapp if the same adress is already used for the regular site

### ISSUE THREAD

**Issue by JacobStruiksma** [Azure/azure-cli#14862]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
If the access restriction has been added for the regular website, and if an extra access restriction is set for the scm-site part is added with the same ip cidr, then an error is thrown back: 

cli.azure.cli.core.util : IP address 4.3.2.1/32 already exists.Cannot add duplicate IP address values.

Where 4.3.2.1/32 is the given ip address

**To Reproduce**
az webapp config access-restriction add --resource-group 'Resource-group' --name 'webapp-name' --action Allow --priority 20 --ip-address '4.3.2.1/32' --rule-name 'Test1' --description 'Test1' 

az webapp config access-restriction add --resource-group 'Resource-group' --name 'webapp-name' --action Allow --priority 20 --ip-address '4.3.2.1/32' --rule-name 'Test2' --description 'Test2' --scm-site $true

**Expected behavior**

Adding to the whitelist for the SCM part of the site with the given ip-address

**Environment summary**
Works on azure-cli 2.2.0
Does not work on azure-cli 2.10.1

**Additional context**
Also does not currently work on the azure devops hosted agents and on my machine

**Comment by yonzhan** [comment]
webapp

**Comment by ThejaChoudary** [comment]
Assigning it to myself to do repro

**Comment by JacobStruiksma** [comment]
just a quick look 
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/_validators.py
line 201, it only checks the regular site not the scm

**Comment by toddplu** [comment]
Getting the same issue. this is a pretty major blocker as far as streamlining AzureDevops (AZDO)  pipelines is concerned.

**Comment by JacobStruiksma** [comment]
I have also posted this on [stackoverflow](https://stackoverflow.com/questions/63935457/whitelist-hosted-agent-for-azure-app-service-with-azure-cli/63936048#63936048) and got as a workaround to first add the scm part of the whitelist and then to the regular site (reverse order). I have not tested this yet but if look at the code, this should be able to work.

**Comment by kmadof** [comment]
What is worth to add is that we can add first rule to scm site and then to main site.

**Comment by btardif** [comment]
This is fixed by #15784
