### ISSUE TITLE
[Functions] Update stacks to new schema 

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-cli#14866]
cc @gzuber   @anthonychu @ammanifold

Repo: https://github.com/pragnagopa/azure-functions-supported-runtime-stacks is a temporary location and will be deprecated soon.

Please move to updated schema: https://github.com/Azure/azure-functions-ux/tree/dev/server/src/stacks/functionapp/2020-06-01/stacks

NOTE: This info will be available on ARM API. No ETA yet for this.

**Comment by yungezz** [comment]
hi @pragnagopa is it ok to assign the issue to you?

**Comment by gzuber** [comment]
@yungezz you can assign it to me, thanks!

**Comment by kamperiadis** [comment]
Closing as this is no longer relevant.
