### ISSUE TITLE
Policy link doesn't work

### ISSUE THREAD

**Issue by maperr** [Azure/azure-cli#14867]
[Enter feedback here]
For more details, see: https://docs.microsoft.com/rest/api/keyvault/certificates-and-policies.
 link doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9c661d7-bf43-5354-015e-3859f30a42a2
* Version Independent ID: fa69e552-5904-ce97-d02c-915c819bdde1
* Content: [az keyvault certificate](https://docs.microsoft.com/en-us/cli/azure/keyvault/certificate?view=azure-cli-latest#az-keyvault-certificate-get-default-policy)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @bim-msft could you pls have a look? thanks.

**Comment by bim-msft** [comment]
This has been fixed in #14757 . The doc will be updated soon.

**Comment by bim-msft** [comment]
Doc updated
