### ISSUE TITLE
Error in Examples

### ISSUE THREAD

**Issue by seanvelir** [Azure/azure-cli#14879]
In the examples for deleting the .py script for files older than 10 days there are a few errors

the first line should use date as a varible so it should be $date
also there are 2 quotation marks in it that do not seem correct.

here is a modified line that should work..

 $date=date -d "10 days ago" '+%Y-%m-%dT%H:%MZ 

az storage blob delete-batch -s mycontainer --account-name mystorageaccount --pattern *.py --if-unmodified-since $date --auth-mode login 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Juliehzl** [comment]
Hi @seanvelir, thanks a lot for your feedback!
The date command in example is for bash and it could works well. Anyway thanks for you feedback :)
