### ISSUE TITLE
Webapp:az webapp create fails to create an app with java runtime

### ISSUE THREAD

**Issue by KonstantinTr** [Azure/azure-cli#14883]
## Describe the bug
Cloud shell fails to create a webapp if I choose java as a runtime.
Same command works perfectly well with the "python" runtime

**Command Name**
`az webapp create`

**Errors:**
```
Linux Runtime 'java|11|Java SE|8' is not supported.Please invoke 'list-runtimes' to cross check
Linux Runtime 'java|1.8|Java SE|8' is not supported.Please invoke 'list-runtimes' to cross check
Linux Runtime 'java|1.8|Tomcat|9.0' is not supported.Please invoke 'list-runtimes' to cross check
```

## To Reproduce:
- `az appservice plan create --name $APP_PLAN_NAME --is-linux`
- `az webapp create --name $WEB_APP_NAME --plan $APP_PLAN_NAME --runtime "java|11|Java SE|8"`
- `az webapp create --name $WEB_APP_NAME --plan $APP_PLAN_NAME --runtime "java|1.8|Tomcat|9.0"`
- `az webapp create --name $WEB_APP_NAME --plan $APP_PLAN_NAME --runtime "java|1.8|Tomcat|9.0"`

## Environment Summary
```
Linux-4.15.0-1092-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.9.1 *

```

**Comment by ThejaChoudary** [comment]
Assigning it ti myself to do repro

**Comment by calvinsID** [comment]
@KonstantinTr Please use the list-runtimes command with --linux flag to get the list of available linux runtimes. Using the list-runtimes command without this flag will show you runtimes available for windows
`az webapp list-runtimes --linux`

**Comment by KonstantinTr** [comment]
@calvinsID Thanks for clarification!
