### ISSUE TITLE
[Breadth Coverage] Onboard Network Watcher Connection Manager Commands

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#14889]
**Spec Link**
Not ready

**ADO Work Item Link**
https://dev.azure.com/azure-mgmt-ex/Onboarding/_workitems/edit/3685

**Resource Provider**
What is the Azure resource provider your feature is part of?
MICROSOFT.NETWORK

**Description of Feature or Work Requested**
Support Azure CLI commands for Network Watcher Connection Manager

**Minimum API Version Required**
2020-05-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/4b2aa12fe415caa4ea0148372466fc15d006d37e/specification/network/resource-manager/Microsoft.Network/stable/2020-05-01

**Python SDK Link**
Not necessary, CodeGen will generate it automatically when generating CLI code.

**Target Date**
09/30/2020

CodeGen Validation Contact:
Qiaoqiao Zhang

**Addtional context**
We'll use [autorest.az](https://github.com/Azure/autorest.az/blob/master/doc/how-to-generate.md) from code gen team to auto-generate the code first and may need update some code manually if the generated code doesn't meet your requirements.

**Comment by yonzhan** [comment]
Network Watcher Connection Manager Commands

**Comment by haroldrandom** [comment]
Closed as no one is tracing.
