### ISSUE TITLE
az network vnet peering delete fail to delete network peering using --ids

### ISSUE THREAD

**Issue by mobindaraie** [Azure/azure-cli#14886]
## Describe the bug

**Command Name**
`az network vnet peering delete`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


string indices must be integers
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 580, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_POST_PARSE_ARGS, command=parsed_args.command, args=parsed_args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 300, in parse_ids_arguments
    full_id_list += [json_val['id']]
TypeError: string indices must be integers
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
(Tested successfully in Powershell using az 2.0.81)

1 - create network peering for two vnet
2- get peering ids using 
peedingid1=$(az network vnet show -g 'rg' --name 'vnet-1' --query virtualNetworkPeerings[0].id)
peedingid2=$(az network vnet show -g 'rg' --name 'vnet-2' --query virtualNetworkPeerings[0].id)
3- pass the peering ids to the vnet peering delter:
az network vnet peering  delete -ids $peedingid1 $peedingid2
## Expected Behavior
-deleting network peerings

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.10.1

```

**Comment by haroldrandom** [comment]
@mobindaraie Please refer to this https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively?view=azure-cli-latest#output-formatting-json-table-or-tsv

It's by design, the JEMSPath output is json by default should re-format them via `-o tsv` to remove the double quote

**Comment by houk-ms** [comment]
#14830
