### ISSUE TITLE
Invalid resource ID error when deleting firewall rule

### ISSUE THREAD

**Issue by douglaswaugh** [Azure/azure-cli#14895]
One of the IDs returned by `az sql server firewall-rule list -g [myResourceGroup] -s [myServer]` returns an 'Invalid resource ID' error when used with `az sql server firewall-rule delete --ids [idForResource]`

The ID returned does have a different format to the other IDs.  It has hypens instead of colons in the date: /subscriptions/[mySubscription]/resourceGroups/[myResourceGroup]/providers/Microsoft.Sql/servers/[myServer]/firewallRules/ClientIPAddress_2020-8-13_12-49-41

**To Reproduce**
Create some firewall rules on an Azure SQL Server
Run `az sql server firewall-rule list -g [myResourceGroup] -s [myServer]` to get a list of firewall rules
If IDs for any of them include hypens in the rule ID, try and delete using `az sql server firewall-rule delete --ids [idForResource]`

**Expected behavior**
The IDs return by `az sql server firewall-rule list` should be usable by `az sql server firewall-rule delete`

**Environment summary**
Installed via MSI: azure-cli-2.10.1.msi
```
azure-cli                         2.10.1

command-modules-nspkg              2.0.3
core                              2.10.1
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
application-insights               0.1.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.
```
Windows:  Version	10.0.17763 Build 17763
Shell: gitbash

**Comment by yonzhan** [comment]
sql

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed. Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)

`az sql server firewall-rule delete --ids` /subscriptions/<subscriptionid>/resourceGroups/issue13587/providers/Microsoft.Sql/servers/issue13587server/firewallRules/ClientIPAddress_2020-8-13_12-49-41
