### ISSUE TITLE
DiskRP 2020-06-30 CLI changes

### ISSUE THREAD

**Issue by laurawu19** [Azure/azure-cli#14899]
**Resource Provider**
Microsoft.Azure.Management.Compute (specifically DiskRP)

**Description of Feature or Work Requested**
Customers can create ultra disks with specific logicalSectorSize. The support values are 4096 and 512. And 4096 is the default value.

Customers can set performance tier of the disks when creating premium disks.

Customers can list associated resources which are using a specific disk encryption set.

We also exposed some fields for shared disks to customers and allow customers to update those properties.

Powershell Design doc: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/725

**Minimum API Version Required**
2020-06-30

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/10208

**Target Date**
Next CLI release

**Comment by yonzhan** [comment]
DiskRP

**Comment by yungezz** [comment]
hi @laurawu19 will sync with you on timeline via email.

**Comment by qwordy** [comment]
4k alignment? What's the benefit of 512?

**Comment by laurawu19** [comment]
> 4k alignment? What's the benefit of 512?

Hi @qwordy , 
Ultra disk is a 4k native disk. There are some customers, for example, Blackrock using legacy apps or applications that allow < 4K IOs sector size (512E). So, diskRP introduces this property to support customers to create disks with 512E logicalSectorSize.

**Comment by qwordy** [comment]
512 doesn't work for me. 4096 works.
```
Deployment failed. Correlation ID: b398e722-ad7a-4544-93c7-f5e43a332fac. Exception creating storage object https://md-dd-a98de607f8a0431b9d47deb1b486fc3a.disk.core.windows.net/disks/a98de607-f8a0-431b-9d47-deb1b486fc3a
```

**Comment by qwordy** [comment]
Hi Lu. Some questions
1.What is tier? What's the corresponding swagger definition?
I find a "tier". It is read only.
```
class DiskSku(Model):
    """The disks sku name. Can be Standard_LRS, Premium_LRS, StandardSSD_LRS, or
    UltraSSD_LRS.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param name: The sku name. Possible values include: 'Standard_LRS',
     'Premium_LRS', 'StandardSSD_LRS', 'UltraSSD_LRS'
    :type name: str or
     ~azure.mgmt.compute.v2020_06_30.models.DiskStorageAccountTypes
    :ivar tier: The sku tier.
    :vartype tier: str
    """

    _validation = {
        'tier': {'readonly': True},
    }
```
2.List associated resources which are using a specific disk encryption set
Is there a REST API for it? How do you implement it in PowerShell?

Thanks,

**Comment by laurawu19** [comment]
Hi Feiyue,

1. The "tier" refers to performance tier of the disk (e.g, P4, S10)  and  is different from the DiskTier in DiskSku model.
Here is the description: https://azure.microsoft.com/en-us/pricing/details/managed-disks/

2. Yes. There is an API for it.
Powershell command:
Get-DiskManagerDiskEncryptionSetAssociatedResources -SubscriptionId sub -ResourceGroup rg --DiskEncryptionSetName desName -Region region

RestAPI:
Get 
subscriptions/{subId}/resourceGroups/{rg}/providers/Microsoft.Compute/{diskEncryptionSets}/{name}/associatedResources

**Comment by qwordy** [comment]
Thanks Lu

**Comment by rahul602** [comment]
@qwordy , 

It's probably clear to you from Lu's comment, but I would still like to mention this for your reference. The sku tier is difference from the performance tier.
This is the swagger for it: 
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-30/disk.json

        "tier": {
          "type": "string",
          "description": "Performance tier of the disk (e.g, P4, S10) as described here: https://azure.microsoft.com/en-us/pricing/details/managed-disks/. Does not apply to Ultra disks."
        }
