### ISSUE TITLE
Display all PWD requirements in error messages?

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#14897]
**Is your feature request related to a problem? Please describe.**

Yes, frustrated when the error guidance/output only check one condition at a time rather than providing complete holistic guidance
See following example. Is there a way to inform the user both PWD requirements at once?
![image](https://user-images.githubusercontent.com/30876406/91096611-26ec2a00-e613-11ea-8e11-0d1eeaf9859c.png)

**Describe the solution you'd like**
Combining both error messages so people don't hit the same error twice because of the lack of clear requirements the in first error output

**Describe alternatives you've considered**
No alternatives

**Additional context**
In midst of designing lab study with VM resource
Believe we've had similar frustration in PWD settings in the storage/db space

**Comment by yonzhan** [comment]
VM

**Comment by yungezz** [comment]
thanks @chenlomis for the feedback. This is valid point. hi @houk-ms let's confirm is this message from service or from CLI, If service, let's feedback to service team. If CLI, let's fix it in next iteration. and check if there any other similar case.

**Comment by houk-ms** [comment]
This is a client-side validation, will open a pr to improve the behavior
