### ISSUE TITLE
Webapp:FTPS endpoint is not returned with 'az webapp deployment list-publishing-profiles' after enforcing FTPS

### ISSUE THREAD

**Issue by richardlm57** [Azure/azure-cli#14909]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
If I use 'az webapp deployment list-publishing-profiles' from Azure CLI to list the publish methods, enforcing FTPS in the Web App, it is not returning any FTPS endpoint

**To Reproduce**
- Enforcing FTPS in the Web App
- Retrieve Web App Publish Profile with 'az webapp deployment list-publishing-profiles' (as here https://docs.microsoft.com/en-us/azure/app-service/scripts/cli-deploy-ftp?toc=/cli/azure/toc.json) the exact used command was creds=($(az webapp deployment list-publishing-profiles --name $webappname --resource-group myResourceGroup \
--query "[?contains(publishMethod, 'FTP')].[publishUrl,userName,userPWD]" --output tsv))

**Expected behavior**
With the previous command, in ${creds[0]} there should be stored 'ftps://waws-prod-XXX.ftp.azurewebsites.windows.net/site/wwwroot' instead of 'ftp://waws-prod-XXX.ftp.azurewebsites.windows.net/site/wwwroot'

**Environment summary**
Azure CLI 2.10.1

**Additional context**

**Comment by yonzhan** [comment]
webapp

**Comment by ThejaChoudary** [comment]
Assigning it to myself to do repro

**Comment by panchagnula** [comment]
@ThejaChoudary were you able to repro this? Any updates?

**Comment by richardlm57** [comment]
Hello, is there any update about this?

**Comment by richardlm57** [comment]
Hello, is there any update about this?

**Comment by panchagnula** [comment]
@ThejaChoudary & @Kotasudhakarreddy like we discussed today please update this  after talking to the core CLI folks if needed. @richardlm57 we were able to repro this issue & are investigating a potential fix. Thanks!

**Comment by richardlm57** [comment]
Hello, is there any update about this?

**Comment by Kotasudhakarreddy** [comment]
@richardlm57 i am unable to repro this issue. could you please try with latest version of CLI `2.19.0 *`. Below is FYI

![image](https://user-images.githubusercontent.com/60102891/109642424-f57f8880-7b78-11eb-9ff9-d75b0665c978.png)

**Comment by Kotasudhakarreddy** [comment]
Closing this issue as unable to repro and no response from the user. @richardlm57 please reopen if you still face this issue.
