### ISSUE TITLE
Installation on CentOS 7.2 failed

### ISSUE THREAD

**Issue by xpillons** [Azure/azure-cli#1490]
you need to run these 2 commands 
sudo yum install -y gcc openssl-devel libffi-devel python-devel
curl https://bootstrap.pypa.io/get-pip.py | sudo python

and then
curl -L https://aka.ms/InstallAzureCli | sudo bash

otherwise the installation of the CLI will failed with the following error
    build/temp.linux-x86_64-2.7/_openssl.c:12:24: fatal error: pyconfig.h: No such file or directory
     #  include <pyconfig.h>
                            ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

**Comment by derekbekoe** [comment]
@xpillons Yes the CLI has some native dependencies and for CentOS 7, some prerequisites are required.

Whilst it is documented in our [Preview Install Guide](https://github.com/Azure/azure-cli/blob/master/doc/preview_install_guide.md#centos-71--72), we have a work item for the curl script to be more user friendly and detect missing native dependencies and [show an appropriate message](https://github.com/Azure/azure-cli/issues/1341#issuecomment-262662441) with the commands needed.

Closing this issue as it's tracked by https://github.com/Azure/azure-cli/issues/1341#issuecomment-262662441.
