### ISSUE TITLE
AKS create fails (not specifying --node-osdisk-diskencryptionset-id)

### ISSUE THREAD

**Issue by vinisoto** [Azure/azure-cli#14915]
## Describe the bug

AKS create fails. Seems similar to [this](https://github.com/Azure/azure-cli-extensions/issues/1187)

**Command Name**
`az aks create`

**Errors:**
```
Property id '' at path 'properties.diskEncryptionSetID' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create -g {} -n {} --enable-aad --aad-admin-group-object-id {}`

## Expected Behavior
To succesfully create an AKS resource

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.11.0

Extensions:
azure-devops 0.11.0

```
## Additional Context

Seems to have been introduced by [this](https://github.com/Azure/azure-cli/pull/14688/files#r476665073)

**Comment by CamSoper** [comment]
I can also repro this. 

This is a regression that has broken Microsoft Learn content that relies on Az CLI. See: https://aka.ms/learn-microservices

![image](https://user-images.githubusercontent.com/137648/91221089-c6c4b900-e6e2-11ea-8133-e64e158b01cc.png)

cc: @scottaddie @nishanil

**Comment by vinisoto** [comment]
@MyronFanQiu This issue seems to have been introduced by [this change](https://github.com/Azure/azure-cli/pull/14688/files#r476665073)

**Comment by yonzhan** [comment]
aks

**Comment by yungezz** [comment]
add @andyzhangx for this

**Comment by andyzhangx** [comment]
fixed by https://github.com/Azure/azure-cli/pull/14920, is `azure-cli 2.11.0` released? I could only find `2.10.1` release in this project now.

**Comment by TomGeske** [comment]
@please-close

**Comment by yungezz** [comment]
> fixed by #14920, is `azure-cli 2.11.0` released? I could only find `2.10.1` release in this project now.

hi @andyzhangx your PR merged after build cut at last Friday, so it will be released at next release: 2.12.0 released at Sep 22th.

**Comment by andyzhangx** [comment]
> > fixed by #14920, is `azure-cli 2.11.0` released? I could only find `2.10.1` release in this project now.
> 
> hi @andyzhangx your PR merged after build cut at last Friday, so it will be released at next release: 2.12.0 released at Sep 22th.

@yungezz this is a broken change for creating AKS cluster, is it possible to merge this PR into `2.10.1` release? thanks.

**Comment by yungezz** [comment]
> > > fixed by #14920, is `azure-cli 2.11.0` released? I could only find `2.10.1` release in this project now.
> > 
> > 
> > hi @andyzhangx your PR merged after build cut at last Friday, so it will be released at next release: 2.12.0 released at Sep 22th.
> 
> @yungezz this is a broken change for creating AKS cluster, is it possible to merge this PR into `2.10.1` release? thanks.

will sync with you on teams

**Comment by nishanil** [comment]
Thanks for the fix. I hope you're able to prioritize the release to Cloud Shell sooner than Sep 22. Something as basic as this walkthrough https://docs.microsoft.com/en-in/azure/aks/kubernetes-walkthrough  is broken.

**Comment by andyzhangx** [comment]
maybe cut a new `2.11.1` release earlier than 9/22?

**Comment by HackerBaloo** [comment]
It's fixed in aks-preview so a work around is to install that: `az extension add --name aks-preview`

**Comment by FHPIENAAR** [comment]
Any update on the issue?  I'm trying to create a private cluster and cannot set the property --outbound-type userDefinedRouting without using Azure CLI, but when I do, I get the error Property id '' at path 'properties.diskEncryptionSetID' is invalid.

**Comment by FHPIENAAR** [comment]
> It's fixed in aks-preview so a work around is to install that: `az extension add --name aks-preview`

I will attempt this now.

**Comment by FHPIENAAR** [comment]
> > It's fixed in aks-preview so a work around is to install that: `az extension add --name aks-preview`
> 
> I will attempt this now.

100% working and fine after I added the ask-preview extension.  Thank you all!

**Comment by ghosh9691** [comment]
> It's fixed in aks-preview so a work around is to install that: `az extension add --name aks-preview`

Thanks! Worked for me, but such a key fix needs to be pushed through quicker. This breaks the AKS lessons.

**Comment by AaronHsiao** [comment]
It works for me
`az extension add --name aks-preview`

But when I try to create aks 
`az aks create -g {} -n {} --enable-managed-identity`

There is another problem 
`Directory permission is needed for the current user to register the application. For how to configure, please refer 'https://docs.microsoft.com/azure/azure-resource-manager/resource-group-create-service-principal-portal'. Original error: Insufficient privileges to complete the operation.`

az version in my environment
```
{
  "azure-cli": "2.11.0",
  "azure-cli-core": "2.11.0",
  "azure-cli-telemetry": "1.0.5",
  "extensions": {
    "aks-preview": "0.4.61"
  }
}
```

**Comment by ernani** [comment]
@AaronHsiao In your case you may not have the permissions to create service principals in your tenant, please refer to the given link to check if or your tenant admin can create them for you here: https://docs.microsoft.com/azure/azure-resource-manager/resource-group-create-service-principal-portal

And, then specify the params by referring to the az aks create command, more details here:

https://docs.microsoft.com/en-us/azure/aks/managed-aad

and here:

https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create

**Comment by Houlberg-Nielsen** [comment]
It fails in preview as well
az aks create -g $resourceGroup -n $clusterName --node-count 1 --generate-ssh-keys

Operation failed with status: 'Bad Request'. Details: Service principal clientID: d8fb2cad-59b1-4f9d-8cfb-5fe38b2f0e16 not found in Active Directory tenant 0cbd4674-a427-493e-834f-e014c4a8cd25, Please see https://aka.ms/aks-sp-help for more details.

Gives no sense, is it possible to download a compiled version 2.19.X ?

**Comment by antrikshdev** [comment]
It works for me
az extension add --name aks-preview

**Comment by TomGeske** [comment]
@AaronHsiao: you issue looks different. It seems like you don't have permissions on your AAD to create app registrations. Are you able to create managed identity in your subscription?

**Comment by MortlMcCrisis** [comment]
I am facing the same issue. Also az _extension add --name aks-preview_ did not work for me an I get the same permission error. The problem raised without any changes to the cluster or the AAD.

**Comment by andyzhangx** [comment]
another workaround is remove `2.11.0` cli and install `2.10.1`

**Comment by TomGeske** [comment]
Windows download is availble here: https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.10.1.msi

**Comment by andyzhangx** [comment]
already fixed by latest version: https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.11.1
