### ISSUE TITLE
Webapp:Cannot set "additionalLoginParams" with `az webapp auth update`

### ISSUE THREAD

**Issue by tormodfj** [Azure/azure-cli#14912]
**Is your feature request related to a problem? Please describe.**
Occasionally, one has to specify `additionalLoginParams` for a web app. One such scenario is described at [https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-how-to#refresh-identity-provider-tokens](https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-how-to#refresh-identity-provider-tokens). While I am able to _view_ an existing `additionalLoginParams` value using `az webapp auth show`, I am unable to _edit_ the value using `az webapp auth update`, since none of its parameters correspond to `additionalLoginParams`.

**Describe the solution you'd like**
I wish `az webapp auth update` had a parameter that would allow me to set `additionalLoginParams` for a web app.

**Describe alternatives you've considered**
I have been able to set `additionalLoginParams` in an ARM template by adding the following sub-resource to the web app:
```json
{
    "type":"config",
    "apiVersion": "2018-11-01",
    "name":"authsettings",
    "properties": { 
        "additionalLoginParams": [
            "response_type=code id_token",
            "[concat('resource=', variables('appId'))]"
        ]
    }
}
```
However, I'd rather be able to accomplish the same using Azure CLI directly, e.g. with the  `az webapp auth update`  sommand.

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@hamster-huey tagging you here to track the issues regarding EasyAuth

**Comment by Hamster-Huey** [comment]
Regarding this issue, with the authV2 extension, we don't have the ability to set login parameters directly, but you can do a full JSON put of a site's authsettingsv2 using `az webapp auth set -g myResourceGroup --name MyWebApp --body @auth.json` 

In authV2, you configure each provider individually, so an example of a Microsoft provider with login parameters would look like: 
```
    "identityProviders": {
      "azureActiveDirectory": {
        "login": {
          "loginParameters": [
            "response_type=code id_token"
          ],
          "disableWWWAuthenticate": false
        }
```

**Comment by seligj95** [comment]
closing because of confirmation from service team. please reopen if there are still issues.
