### ISSUE TITLE
az identity show without resource name does not have exit code.

### ISSUE THREAD

**Issue by NillsF** [Azure/azure-cli#14913]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When running `az identity show` with a wrong name (making the command return `The Resource XXX under resource group YYY was not found`), does not exit with a exit code. When running this in a pipeline (e.g. GitHub actions) this doesn't stop the pipeline, which is not expected behavior after a failed command.
**To Reproduce**

Run `az identity show -g $RGNAME -n _doesnotexist_` in a pipeline
See green checkmark.
Example below:
![image](https://user-images.githubusercontent.com/6205923/91210621-60c83980-e6c2-11ea-9130-b5a7fb204890.png)

**Expected behavior**

I would expect a non-zero exit code.
**Environment summary**

GitHub actions.
**Additional context**

**Comment by yonzhan** [comment]
identity

**Comment by jiasli** [comment]
The command `az identity show` does return [exit code](https://github.com/Azure/azure-cli#exit-codes) `3` for a non-existing identity resource (the REST response is `404`).

```sh
# id2 is a non-existing resource
$ az identity show -g rg1 -n id2 --query clientId --output tsv
The Resource 'Microsoft.ManagedIdentity/userAssignedIdentities/id2' under resource group 'rg1' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

# The exit code is as expected
$ echo $?
3

# Export the output to an environment variable
$ export IDENTITY_CLIENT_ID=$(az identity show -g rg1 -n id2 --query clientId --output tsv)
The Resource 'Microsoft.ManagedIdentity/userAssignedIdentities/id2' under resource group 'rg1' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

# The exit code is now 0
$ echo $?
0

# IDENTITY_CLIENT_ID is empty
$ echo $IDENTITY_CLIENT_ID 

```

It is the behavior of `export` to return `0` even if the inner command fails. In other words, `export` ignores the exit code of the inner command. 

For `export`, [the POSIX specification](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#export) says,

>***EXIT STATUS***<ul>
0<ul>All name operands were successfully exported.</ul>
&gt;0<ul>At least one name could not be exported, or the `-p` option was specified and an error occurred.</ul></ul>

So,

```sh
export foo="$(mycmd)"
```

should be changed to

```sh
foo=$(mycmd)
export foo
```

More info, please see https://unix.stackexchange.com/a/270831/145565

I am not an expert of GitHub Actions so can't give a solid fix. You may try

1. Run the command and save the result in a variable
2. Export the variable as an environment variable

If this is not possible, you may report this issue to GitHub Actions instead.
