### ISSUE TITLE
 az keyvault create with --enable-soft-delete=true -> confusing logs

### ISSUE THREAD

**Issue by abrignola** [Azure/azure-cli#14927]
**Describe the bug**
az keyvault create --location "xxx" --name "xxx" --resource-group "xxx" --enable-soft-delete=true

When using cli 2.10.1 to create a KeyVault with the soft delete flag on, it will log that this has been deprecated and will be removed in 2.11.0.
The release notes for 2.11.0 don't mention anything about that. 
When updating cli to 2.11.0 and running the same command, the message says that it will be removed in a future release.

**Expected behavior**
Be given the right information so we know how to deal with this since it's a breaking change.

**Additional context**
In addition, we are using the Cli task in AzureDevOps which has no way of setting it to an exact version so all our deployments will break when this release goes out to all the hosted agents. Since we have no control over how and when the version gets updated on the Azure-Hosted agents, it would be good to have the ability to specify which version of the cli to use to avoid breaking changes like this one affect our prod deployments.

**Comment by yonzhan** [comment]
keyvault

**Comment by abrignola** [comment]
UPDATE: 
The task is failing even when I disable failOnStandardError, it returns exit code 1. 

**Current scenario is:** 
Azure CLI @2 loads cli version 2.10.1. 
failOnStandardError is set to false

Outcome: 
![image](https://user-images.githubusercontent.com/52066880/91302832-f76a2880-e79e-11ea-8942-1bfd4a96a2c4.png)

How do we get around this?

**Comment by yungezz** [comment]
hi @bim-msft, could you pls check the message there? thanks

**Comment by bim-msft** [comment]
@abrignola Hi, to let you quickly unblocked: do not specify `--enable-soft-delete=true`, the default value is `true`.

**Comment by yungezz** [comment]
hi @abrignola thanks for the great feedback. For --enable-soft-delete exact timeline, we'll communicate with service team to get a concrete timeline. For now, pls not specify `--enable-soft-delete`. thanks
