### ISSUE TITLE
Should exclude storageProfile on VMSS update command request

### ISSUE THREAD

**Issue by yangl900** [Azure/azure-cli#14924]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When a VMSS is created using Shared Image Gallery image from a different tenant, any VMSS update operation like `az vmss update` or `az vmss extension add` will fail at ARM linked access check. This is because the client CLI use won't have permission in the SIG tenant.

The error message you see will be:
```
The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '{VMSS or VM resource ID}', 
however the current tenant '{customer tenant ID}' is not authorized to access linked subscription '109a5e88-712a-48ae-9078-9ca8b3c81345'.
```

AKS recently rolled out a change to subset of customers to pilot using SIG image and discovered this issue.

**To Reproduce**

Create an AKS cluster in Australia / Canada region, in the node resource group (named MC_xxx) there will be a VMSS using SIG image. Try do any `az vmss update` operation on it, or on the VM instance.

**Expected behavior**

VMSS update should succeed.

In order to make this scenario work, the update request body should only contain the relevant property changes (not the full VMSS properties body), or at least remove property "properties.virtualMachineProfile.storageProfile".

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
VMSS

**Comment by yungezz** [comment]
cc @arrownj , could be done via support of aux-tenant-id in header?

**Comment by qwordy** [comment]
This piece of code is copied from `vmss update`. It was added in July. It checks existence of image reference and sets auxiliary subscription so that it won't trigger the permission error. Which version of Azure CLI do you use? Maybe you can try the latest version of Azure CLI, 2.11.0 and see if it still fails.
```
    aux_subscriptions = None
    # pylint: disable=too-many-boolean-expressions
    if vmss and hasattr(vmss, 'virtual_machine_profile') and vmss.virtual_machine_profile and \
            vmss.virtual_machine_profile.storage_profile and \
            vmss.virtual_machine_profile.storage_profile.image_reference and \
            vmss.virtual_machine_profile.storage_profile.image_reference.id:
        aux_subscriptions = _parse_aux_subscriptions(vmss.virtual_machine_profile.storage_profile.image_reference.id)
    client = _compute_client_factory(cmd.cli_ctx, aux_subscriptions=aux_subscriptions)
```

**Comment by xuto2** [comment]
@qwordy  setting aux_subscription won't help here  - the SP that invokes the CLI command doesn't have permission to access the image under the aux_subscription so it will still fail (the aux_subscription is an AKS owned prod subscription and the images resources under that subscription is not accessible to anyone other than AKS 1st party SP).

**Comment by qwordy** [comment]
Discuss in internal email. I will give a summary here.

**Comment by andyzhangx** [comment]
any progress about fix on `az vmss extension` command?

**Comment by qwordy** [comment]
https://github.com/Azure/azure-cli/pull/14992
PR is ready

**Comment by andyzhangx** [comment]
found a similar issue on `az vmss disk attach/detach` command: https://github.com/Azure/azure-cli/issues/15058

**Comment by qwordy** [comment]
Thank you for reporting it.

**Comment by yungezz** [comment]
currently PR in CLI side, while blocked by a VMSS service issue. When service deployment done, will merge CLI side change.
