### ISSUE TITLE
[Errno 30] Read-only file system: '/home/NAME/.azure/commands/2020-08-26.20-06-21.login.452.log'

### ISSUE THREAD

**Issue by cerrakoth** [Azure/azure-cli#14931]
## Describe the bug
Deleted my cloud shell resource group via ACS, since then I'm unable to run any command due to the error message below. The first command I tried after deleting the group via 'az group delete -n GROUPNAME was az group list.

I have seen this posted in other threads with no answer from MS.

**Command Name**
az group list

**Errors:**

The command failed with an unexpected error. Here is the traceback:

[Errno 30] Read-only file system: '/home/NAME/.azure/commands/2020-08-26.20-06-21.login.452.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 511, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 86, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 108, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/NAME/.azure/commands/2020-08-26.20-06-21.login.452.log'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Any command entry into ACS other than az feedback seems to reproduce the error above. The file name referenced in the 'Read-only file system' section, does change.

## Expected Behavior

list resource groups.

## Environment Summary
```
Linux-4.15.0-1092-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.11.0

```
## Additional Context

I had originally been trying to troubleshoot an AKS error whereby I could no longer execute **az aks create** without the below error being generated:

"Property id '' at path 'properties.diskEncryptionSetID' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' "

I had thought that this might be related to the ACS and as this is just my personal subscription, thought I'd start from scratch and delete all resource groups.

**Comment by yonzhan** [comment]
add to S175

**Comment by zhoxing-ms** [comment]
It seems duplicated with #13855, so I close it first
