### ISSUE TITLE
acs create... ssh key path instead of ssh key data

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1494]
This is the other bug @yangl900 reported.

It seems there's an edge case where the ssh key path is inserted into the template rather than the ssh key data.

**Comment by brendandburns** [comment]
Ok, I got another repro on this. It looks like if you don't have a key and --generate-ssh-key (or somesuch) is set to false, then you'll get this. I will add a check.

**Comment by brendandburns** [comment]
I believe this is now fixed. (it will errror out)
