### ISSUE TITLE
az cli adding a system node pool

### ISSUE THREAD

**Issue by naioja** [Azure/azure-cli#14943]
## Describe the bug

I'm trying to add a system node pool using the az-cli command following the options here :
https://docs.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest#az-aks-nodepool-add

The command fails as the option `--mode` is reported to be unrecognized.

**Command Name**
`az aks nodepool add`

**Errors:**
```
az: error: unrecognized arguments: --mode System
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- run the command below
- `az aks nodepool add \
    --resource-group rg \
    --cluster-name aks \
    --name npool \
    --node-count 3 \
    --node-taints CriticalAddonsOnly=true:NoSchedule --mode System`
- if the `--mode` is removed adding the pool works as expected

## Expected Behavior
- the az cli should obey the option `--mode` as per documentation : https://docs.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest#az-aks-nodepool-add

## Environment Summary
```
macOS-10.15.6-x86_64-i386-64bit
Python 3.8.5
Installer: HOMEBREW

azure-cli 2.11.0

Extensions:
azure-firewall 0.5.0
aro 1.0.0
aks-preview 0.4.38
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
aks

**Comment by naioja** [comment]
The command works if I update the aks-preview to latest version :     "aks-preview": "0.4.61",
