### ISSUE TITLE
Unable to get the public IP info through Python CLI commands

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#1495]
Used command az network public-ip show -n GatewaySubnet -g VV2. Also tried with another subnet present in the same VNet but both times i got the following error
The Resource 'Microsoft.Network/publicIPAddresses/GatewaySubnet' under resource group 'VV2' was not found.
The Resource 'Microsoft.Network/publicIPAddresses/Sub2' under resource group 'VV2' was not found.

Also tried giving the VNet name instead of the subnet name but that didnt work either. The same command works in Node.js

**Comment by tjprescott** [comment]
If you do `az resource list -g VV2 -otable` does it list a public IP address?

**Comment by tjprescott** [comment]
In the `az network public-ip show` command, `-n` refers to a public-ip name, not a VNet or a subnet name. I would not expect that to work.

**Comment by tjprescott** [comment]
Xplat (Node) also does not accept a subnet or vnet name for their public-ip show command.

**Comment by tjprescott** [comment]
@aanandr can you provide clarification on this issue?
