### ISSUE TITLE
az login --identity: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url

### ISSUE THREAD

**Issue by AbdulWas1** [Azure/azure-cli#14961]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04911470>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
Traceback (most recent call last):
Temp\pip-unpacked-wheel-nmdz9lpd\urllib3\connection.py, ln 160, in _new_conn
pip-unpacked-wheel-nmdz9lpd\urllib3\util\connection.py, ln 80, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.10.1 *

```

**Comment by yonzhan** [comment]
add to S175

**Comment by jiasli** [comment]
The timeout error indicates **the managed identity endpoint on the VM is not responding**, so Azure CLI fails to retrieve an access token.

Please [open a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) and check why the endpoint is not working on the VM instead.

**Comment by sakitA** [comment]
I got this issue recently. Can you please explain what should I do to solve this issue?
