### ISSUE TITLE
How to pass an argument parameter without defining a value?

### ISSUE THREAD

**Issue by arde0708** [Azure/azure-cli#14968]
I am trying to achieve three scenarios for a command. Is there a way to do this ?
1. az postgres server create                                        **(no argument parameter passed)**
2. az postgres server create --public-access               **(no value passed for argument parameter _--public-access_)**
3. az postgres server create --public access <value> **( a valid value is passed to argument parameter _--public-access_).**

Is there a way to do (2) that is pass a parameter without a value ? I am running into the below error :
az postgres server create: **error: argument **--public-access: expected one argument**.**

If this is do-able, how should I differentiate between (1) and (2) that is whether the parameter is completely missing or is present with a missing value ?

**Comment by yonzhan** [comment]
postgres

**Comment by fengzhou-msft** [comment]
@arde0708 what are the sample values of `--public-access`? What is the behavior for 2?
We have [get_three_state_flag](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/commands/parameters.py#L161) arg_type that can achieve 2 and 3, but it only support boolean values.

**Comment by arde0708** [comment]
We would want to define three kind of values for --public-access

1. **No value.** Just the parameter is passed. _Ex : 'az postgres flexible-server create --public-access'_ ( Adds neither a Vnet, nor a firewall rule)
2. **Single IP**. _Ex :  'az postgres flexible-server create --public-access 10.23.202.44'_ (Behavior : Adds single firewall rule)
3. **Multiple IP**. _Ex :  'az postgres flexible-server create --public-access 10.23.202.44-10.23.202.48'_ (Behavior : Adds range of firewall rules)
4. Don't pass the parameter itself _'Ex : az postgres flexible-server create'_ (Behavior : Adds Vnet, Subnet)

**Comment by nachoalonsoportillo** [comment]
@yonzhan Single Server is being retired. We won't be fixing this at this point in time. Please, close this issue. Thanks!
