### ISSUE TITLE
Running "az synapse workspace delete " with contributor SPN access giving Error "Can not perform requested operation on nested resource. Parent resource '<workspacename>' not found." 

### ISSUE THREAD

**Issue by jayendranarumugam** [Azure/azure-cli#14960]
I ran `az synapses workspace delete` command with SPN , the SPN having contributor access to the sub, getting the error like 
> Can not perform requested operation on nested resource. Parent resource '<workspacename>' not found.

Even though i get the above error the workspace getting deleted successfully.

running this with `--debug` I get the below

> GET /subscriptions/<>/resourceGroups/<>/providers/Microsoft.Synapse/workspaces/<>/operationStatuses/560a9de7-3526-4141-971a-965c081eb35a?api-version=2019-06-01-preview HTTP/1.1\" 404 156", "msrest.http_logger : Response status: 404", "msrest.http_logger : Response headers:", "msrest.http_logger :     'Cache-Control': 'no-cache'", "msrest.http_logger :     'Pragma': 'no-cache'", "msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'", "msrest.http_logger :     'Expires': '-1'", "msrest.http_logger :     'x-ms-failure-cause': 'gateway'", "msrest.http_logger :     'x-ms-request-id': '5ea2c78d-1024-451a-af06-ce1d911dda5c'", "msrest.http_logger :     'x-ms-correlation-request-id': '5ea2c78d-1024-451a-af06-ce1d911dda5c'", "msrest.http_logger :     'x-ms-routing-request-id': 'CANADACENTRAL:20200828T075102Z:5ea2c78d-1024-451a-af06-ce1d911dda5c'", "msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'", "msrest.http_logger :     'X-Content-Type-Options': 'nosniff'", "msrest.http_logger :     'Date': 'Fri, 28 Aug 2020 07:51:02 GMT'", "msrest.http_logger :     'Content-Length': '156'", "msrest.http_logger : Response content:", "msrest.http_logger : {\"error\":{\"code\":\"ParentResourceNotFound\",\"message\":\"Can not perform requested operation on nested resource. Parent resource '<>' not found.\"}}", "msrest.exceptions : Can not perform requested operation on nested resource. Parent resource '<>' not found.", "cli.azure.cli.core.util : Deployment failed. Correlation ID: 5ea2c78d-1024-451a-af06-ce1d911dda5c. Can not perform requested operation on nested resource. Parent resource '<>' not found.", "Deployment failed. Correlation ID: 5ea2c78d-1024-451a-af06-ce1d911dda5c. Can not perform requested operation on nested resource. Parent resource '<>' not found.", "Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f24bde09488>]", "az_command_data_logger : exit code: 1", "Command ran in 205.401 seconds (init: 0.531, invoke: 204.869)", "telemetry.save : Save telemetry record of length 6549 in cache", "telemetry.check : Negative: The /home/jayendran/.azure/telemetry.txt was modified at 2020-08-28 13:17:28.196572, which in less than 600.000000 s"]}

*Note: This error is not coming if I run it with owner access*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a8ce4bb-b234-dc91-cd2c-e5587caf6169
* Version Independent ID: 9f08c3b1-5ac8-81d3-02e4-f7111cfe0781
* Content: [az synapse workspace](https://docs.microsoft.com/en-us/cli/azure/ext/synapse/synapse/workspace?view=azure-cli-latest#ext-synapse-az-synapse-workspace-delete)
* Content Source: [latest/docs-ref-autogen/ext/synapse/synapse/workspace.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/synapse/synapse/workspace.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by idear1203** [comment]
Thanks for the notification. We will add some logic at CLI side to handle this. Meanwhile, we will check if there is a server issue or not.

**Comment by idear1203** [comment]
@jayendranarumugam we did some investigation from backend, it seems this is not a server side issue. Since the issue was reported 2 weeks ago, some logs cannot be found any more. Could you please help trigger the issue again and share the related logs (command output)? Especially the `x-ms-correlation-request-id`

**Comment by jayendranarumugam** [comment]
@idear1203  here is the logs which I just ran now

> "GET /subscriptions/<removed>/resourceGroups/<removed>/providers/Microsoft.Synapse/workspaces/test1432/operationStatuses/c09c54de-11e4-44a2-8b13-3b1de2734147?api-version=2019-06-01-preview HTTP/1.1\" 404 149", "msrest.http_logger : Response status: 404", "msrest.http_logger : Response headers:", "msrest.http_logger :     'Cache-Control': 'no-cache'", "msrest.http_logger :     'Pragma': 'no-cache'", "msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'", "msrest.http_logger :     'Expires': '-1'", "msrest.http_logger :     'x-ms-failure-cause': 'gateway'", "msrest.http_logger :     'x-ms-request-id': 'cd860788-cee1-470a-8763-5e4b1860a1e5'", "msrest.http_logger :     'x-ms-correlation-request-id': 'cd860788-cee1-470a-8763-5e4b1860a1e5'", "msrest.http_logger :     'x-ms-routing-request-id': 'CANADACENTRAL:20200911T070827Z:cd860788-cee1-470a-8763-5e4b1860a1e5'", "msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'", "msrest.http_logger :     'X-Content-Type-Options': 'nosniff'", "msrest.http_logger :     'Date': 'Fri, 11 Sep 2020 07:08:26 GMT'", "msrest.http_logger :     'Content-Length': '149'", "msrest.http_logger : Response content:", "msrest.http_logger : {\"error\":{\"code\":\"ParentResourceNotFound\",\"message\":\"Can not perform requested operation on nested resource. Parent resource 'test1432' not found.\"}}", "msrest.exceptions : Can not perform requested operation on nested resource. Parent resource 'test1432' not found.", "cli.azure.cli.core.util : Deployment failed. Correlation ID: cd860788-cee1-470a-8763-5e4b1860a1e5. Can not perform requested operation on nested resource. Parent resource 'test1432' not found.", "Deployment failed. Correlation ID: cd860788-cee1-470a-8763-5e4b1860a1e5. Can not perform requested operation on nested resource. Parent resource 'test1432' not found.", "Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f4a6f249488>]", "az_command_data_logger : exit code: 1", "Command ran in 242.228 seconds (init: 0.644, invoke: 241.584)", "telemetry.save : Save telemetry record of length 6542 in cache", "telemetry.check : Negative: The /home/jayendran/.azure/telemetry.txt was modified > at 2020-09-11 12:30:44.678760, which in less than 600.000000 s"]}

**Comment by jayendranarumugam** [comment]
Hi @idear1203  is there any update ? We are blocking with this issue on our production

**Comment by Sai-Kumar-1901** [comment]
HI @jayendranarumugam , are you still facing this issue?
