### ISSUE TITLE
az vm assess-patches fails with "Subscription is not registered." error

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-cli#14964]
## Describe the bug
`az vm assess-patches` fails with "Subscription is not registered." error.
What does that mean? How to fix it?

**Command Name**
`az vm assess-patches`

**Errors:**
```
Subscription is not registered.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm assess-patches -g {} -n {} --debug`

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.11.1

Extensions:
interactive 0.4.4

```

**Comment by yonzhan** [comment]
vm

**Comment by alexandair** [comment]
@yonzhan vm?

**Comment by yonzhan** [comment]
@yungezz will help you with this issue

**Comment by yungezz** [comment]
hi @alexandair that means the feature need to be registered firstly before using. @qwordy could you pls help with instruction?

**Comment by qwordy** [comment]
Run these two commands.
https://docs.microsoft.com/en-us/cli/azure/feature?view=azure-cli-latest#az-feature-register
https://docs.microsoft.com/en-us/cli/azure/provider?view=azure-cli-latest#az-provider-register
If it still does not work, it requires service's manual intervention to whitelist it.

**Comment by qwordy** [comment]
Message from service team:
The public preview feature documentation will be shipping next week. That will include instructions for onboarding subscription to the feature.

**Comment by alexandair** [comment]
@qwordy Any news about this?

**Comment by qwordy** [comment]
> The service update is scheduled for 9/9. The customer can use the feature after that date.

**Comment by yungezz** [comment]
official doc: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/automatic-vm-guest-patching#azure-cli-20

**Comment by alexandair** [comment]
@yungezz Thanks.
