### ISSUE TITLE
az cli incorrect parsing of query "--query "[0].keys(@)"

### ISSUE THREAD

**Issue by ralfkret** [Azure/azure-cli#14972]
## Describe the bug
I get an error message (see below) when I issue the following command. The command should output the structure of the json data.

**Command Name**
` az vm list -d --query "[0].keys(@)"`

**Errors:**
```
az vm list: error: argument --query: invalid jmespath_type value: '[0].keys(@'
usage: az vm list [-h] [--verbose] [--debug] [--only-show-errors]
                  [--output {json,jsonc,yaml,yamlc,table,tsv,none}]
                  [--query JMESPATH] [--subscription _SUBSCRIPTION]
                  [--resource-group RESOURCE_GROUP_NAME] [--show-details]
To learn more about [--query JMESPATH] usage in AzureCLI, visit https://aka.ms/CLIQuery

C:\>echo Failed to load python executable.
Failed to load python executable.

C:\>exit /b 1
```

As you may notice in the error message the closing parenthesis of the query is missing.
So I reissued the slightly modified command with an extra space after the closing parenthesis:

` az vm list -d --query "[0].keys(@) "`

Et Voilà:
```
[
  "location",
  "tags",
 ... skipped for prevety
 "privateIps",
  "macAddresses",
  "resourceGroup"
]
```
## To Reproduce:
See above.

## Expected Behavior
The command should output the keys of the json describing the vm.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.11.0 *

Extensions:
interactive 0.4.4

```

**Comment by yungezz** [comment]
thanks for reporting the issue! hi @qwordy could you pls help to have a look? Is this a general issue in query? thanks

**Comment by qwordy** [comment]
Remove the compute label.

**Comment by jiasli** [comment]
I can't run this command and got error https://github.com/Azure/azure-cli/issues/15064. @qwordy

**Comment by jiasli** [comment]
It looks like you are running this command in Command Prompt, but I can't reproduce it

```powershell
D:\cli>az vm list --query "[0].keys(@)"
[
  "location",
  "tags",
  "plan",
  ...
]
```

May I know what terminal you are using?

By the way, there are some [known quoting issues with PowerShell](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md). 

But when I ran this command, it is weird that the command is actually invoked twice, one without the `)` and one with `)`.

```powershell
> az vm list --debug --query "[0].keys(@)"
Command arguments: ['vm', 'list', '--debug', '--query', '[0].keys(@']
...
az vm list: error: argument --query: invalid jmespath_type value: '[0].keys(@'
...
Command arguments: ['vm', 'list', '--debug', '--query', '[0].keys(@)']
...
[
  "id",
  "name",
  "type",
  "location",
...
```

I am not sure why this happens, but anyway in PowerShell the correct way to run this command is to quote `@` twice, one for Command Prompt, one for PowerShell:

```powershell
az vm list --query '"[0].keys(@)"'
# or
az --% vm list --query "[0].keys(@)"
```

**Comment by ralfkret** [comment]
Indeed I am using Powershell (version 5.1.19041.1 running in Windows Terminal 1.2.2381.0).
When I switch to Command.exe the original command `az vm list --query "[0].keys(@)"` works as expected.
I wasn't aware of the quoting issues you have mentioned

**Comment by ralfkret** [comment]
At least now I have an idea why the variant with the extra space `az vm list --query "[0].keys(@) "` worked. 

I assumed any character would do, but the real difference seems to be that the whitespace prevents prevents PowerShell from stripping the quotes as mentioned in [Quoting issues with PowerShell](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md#ampersand--is-interpreted-by-command-prompt).

This is confirmed by the fact that the following variants of the command work as expected (in PowerShell):
```
az vm list --query " [0].keys(@)"
```

```
az vm list --query "[0].keys( @ )"
```

Well - live and learn.

**Comment by jiasli** [comment]
Glad to know the issue is solved. 😊

@houk-ms, maybe we can improve the error message for `--query` to inform the user that they may be hitting [Quoting issues with PowerShell](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md)?

**Comment by houk-ms** [comment]
sure, that make sense. while if it only happens on powershell, maybe better if we can show the hints only to powershell users

**Comment by qwordy** [comment]
> 
> 
> I can't run this command and got error #15064. @qwordy
It is a service issue after my investigation.

**Comment by jiasli** [comment]
Tracked by #15529
