### ISSUE TITLE
[Install] `dev_setup.py` no longer works in Python 3.5

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1498]
When I run the `dev_setup.py` script in a brand new Python 3.5 virtual environment (Windows), upon completion, running `az` results in:

```

     /\
    /  \    _____   _ _ __ ___
   / /\ \  |_  / | | | \'__/ _ \
  / ____ \  / /| |_| | | |  __/
 /_/    \_\/___|\__,_|_|  \___|


Welcome to the cool new Azure CLI!

Here are the base commands:

```
However, if I repeat this process in Python 2.7, I have all of the command packages per usual.

**Comment by derekbekoe** [comment]
Looked into this and it looks like pip is caching the old modules as I could repro on my local machine but not on any new VMs.

Can you clear the pip cache and try again?

On Windows, it should be at `%USERPROFILE%\AppData\Local\pip\cache`.

**Comment by derekbekoe** [comment]
I'm not able to repro on my Windows machine.
@tjprescott What was the pip version in your environment? I had 9.0.1.

@troydai, @yugangw-msft have you run into this issue on Windows with a Python 3.5 env?

**Comment by tjprescott** [comment]
@derekbekoe 9.0.1

**Comment by tjprescott** [comment]
Deleting the pyc files fixed this issue for me.

`del *.pyc /S`
