### ISSUE TITLE
Fix non-actionable code bugs: VM

### ISSUE THREAD

**Issue by houk-ms** [Azure/azure-cli#14986]
These issues are from Telemetry records, and most of them are caused by obvious code bugs. The detail error messages and the corresponding command and CLI version info can be viewed in the [CLI error dashboard](https://msit.powerbi.com/groups/de995b1a-16c1-4cc7-a49b-bc9f90bc6acd/reports/b657544c-ab0a-4306-bc7b-5bedab1bb5a9/ReportSection01812df080cad06afcb4?noSignUpCheck=1power).

As the info of these issues are limited and may be more difficult to identify and solve, we opened a [Teams channel](https://teams.microsoft.com/l/team/19%3a0e3d8b3a0c40468884a92709305d5898%40thread.tacv2/conversations?groupId=863077aa-7638-4956-a60e-43b88698fb04&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) for command groups owners to sync up the common error types and fixing methods. Feel free to share your experience and ask for help (if any) there.

A brief summary of the code bug errors of VM here:

FailureType | EventCount
-- | --
TypeError | 3012
AttributeError | 2192
JMESPathTypeError | 435
ModuleNotFoundError | 400
ValueError | 160
KeyError | 48
UnknownFunctionError | 42
ArityError | 41
ImportError | 14
IndexError | 6
NameError | 5
UnboundLocalError | 4
IndentationError | 1
SyntaxError | 1

**Comment by yungezz** [comment]
Non-actionable error messages are helpless to end users when Azure CLI error out. One of Fe OKR is to improve Azure CLI command pass rate for better user experience. We've identified non-actionable errors of top used command groups. Pls help to fix non-actionable errors. More detail in email. Feel free to ping us at [teams](https://teams.microsoft.com/l/team/19%3a0e3d8b3a0c40468884a92709305d5898%40thread.tacv2/conversations?groupId=863077aa-7638-4956-a60e-43b88698fb04&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47),  or ping @houk-ms @yungezz  if any issue.
