### ISSUE TITLE
az vmss update-instances not working

### ISSUE THREAD

**Issue by sysadmin-exe** [Azure/azure-cli#14998]
I am having an issue. 

az vmss update-instances --instance-ids * --name server_scaleset --resource-group web_rg

the error I get is this: The provided instanceId data.tf is invalid. It must be a non-negative integer or the character "*". 

data.tf is actually the first file in the PWD where the command was run from on the terminal.

Tried same on Portal CLI and the error was: The provided instanceId clouddrive is invalid. It must be a non-negative integer or the character "*".

AZ CLI version: 2.11.1

All I can do is run the command for all instances one at a time like so
az vmss update-instances --instance-ids 2 --name server_scaleset --resource-group web_rg
az vmss update-instances --instance-ids 3 --name server_scaleset --resource-group web_rg

And i dont think this makes sense

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0408c294-207a-2b72-7b93-e09121602b75
* Version Independent ID: 852cb67b-70c6-b811-3b0a-5d5b84b8a911
* Content: [az vmss](https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look?

**Comment by qwordy** [comment]
I think `*` is translated by your terminal. Please add `"` around `*`. `--instance-ids "*"`

**Comment by qwordy** [comment]
@sysadmin-exe Do I solve your problem?

**Comment by sysadmin-exe** [comment]
Oh yea please @qwordy thanks.

**Comment by qwordy** [comment]
> 
> 
> Oh yea please @qwordy thanks.

Cool! I will close this issue.
