### ISSUE TITLE
update from command line?

### ISSUE THREAD

**Issue by lovettchris** [Azure/azure-cli#14999]
**Is your feature request related to a problem? Please describe.**
Hunting down and installing the .msi is a pain.

**Describe the solution you'd like**
can you please provide a "az update" command that updates az in place?

**Describe alternatives you've considered**
Lots of other command line tools do this.

**Additional context**
The screenshot should be a terminal window, I never have to leave it even to install updates :-)

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls share the instruction of az upgrade? hi @lovettchris thanks for the feedback, we'd also love to hear your feedback after trying the new az upgrade command, feel free to comment here if found any issue with it.

**Comment by fengzhou-msft** [comment]
@lovettchris we have added the `az upgrade` command in version `2.11.0` to update azure cli and all installed extensions. You can find more information in this [PR](https://github.com/Azure/azure-cli/pull/14803).

**Comment by lovettchris** [comment]
Sweet, thanks!
