### ISSUE TITLE
Command index broke dev_sources workflow

### ISSUE THREAD

**Issue by jim-minter** [Azure/azure-cli#14997]
ARO has the following CI workflow:

* install latest released `az`
* update [extension] dev_sources in .azure/config in order to override the core 'aro' module with a local 'aro' extension
* run `az aro ...` to test it

As far as 2.10.1, this worked fine (when we did this, the local 'aro' extension would run, not the core 'aro' module).

In 2.11.1, we find that the above behaviour does not work any more.  A workaround we found is to delete .azure/commandIndex.json to force it to be refreshed.

When we do that, we can see that the following diff happens to commandIndex.json:

```
--- old	2020-08-31 16:02:23.397858250 +0000
+++ new	2020-08-31 16:02:28.322865042 +0000
@@ -39,6 +39,7 @@
       "azure.cli.command_modules.appservice"
     ],
     "aro": [
+      "azext_aro",
       "azure.cli.command_modules.aro"
     ],
     "backup": [
```

Is this a regression that needs to be fixed in `az`, or do we need to permanently change our behaviour?  Is there a better workaround than to delete commandIndex.json?

## Environment Summary
```
Linux-5.7.11-100.fc31.x86_64-x86_64-with-glibc2.2.5
Python 3.8.5
Installer: RPM

azure-cli 2.11.1

Extensions:
aro 1.0.0 (dev) /root/go/src/github.com/Azure/ARO-RP/python/az/aro

```

**Comment by jim-minter** [comment]
@jiasli please could you take a look at this question?

**Comment by yonzhan** [comment]
Command index

**Comment by jiasli** [comment]
This is a known issue of **command index** that when underlying extensions are manually updated, either by running `azdev extension add` or editing related files or configs like `[extension] dev_sources` in `~/.azure/config`, command index will not detect the change and use the old index. This is not something command index can detect and handle.

There are 2 ways to fix it:

1. Manually deleting `~/.azure/commandIndex.json` to force it to be refreshed.
2. Use `[core] use_command_index` to disable command index:
    https://github.com/Azure/azure-cli/blob/814598f5e8fe3d0e418f0be392a0f2984b6bd215/src/azure-cli-core/azure/cli/core/__init__.py#L385

Please let me know if these approaches can fix your issue.

BTW, this known issue won't affect real users as `CommandIndex` has a `invalidate` method which is called when adding extensions via `az extension add`.

https://github.com/Azure/azure-cli/blob/814598f5e8fe3d0e418f0be392a0f2984b6bd215/src/azure-cli-core/azure/cli/core/__init__.py#L571-L585
