### ISSUE TITLE
Upgrade kubectl by using `aks install-cli` on Cloud Shell

### ISSUE THREAD

**Issue by iamalexmang** [Azure/azure-cli#14995]
Hi,

I'm trying to leverage AKS-managed AAD integration in a brand new AKS cluster and by using exclusively Cloud Shell (which is, in my opinion, the preferred way everyone should work with).
Seems though that there are prerequisites on the Azure CLI and on kubectl, specifically versions 2.11 and 1.18.1 respectively.

Hence Cloud Shell comes installed with kubectl 1.16.0, this is a blocker which by default prevents the utilization of the non-preview feature.

Using `az aks install-cli`, the command fails with a Permission denied error.
Alternatively, one could specificy a different install location, which would end up with the user having two kubectl versions installed, which again is something I believe is less than ideal and somewhat cumbersome.

What I would appreciate is to:
- either have kubectl installed in a location where the default user has privileges to write to
- have a way to upgrade kubectl (or other CLIs for that matter)

**Comment by yonzhan** [comment]
aks

**Comment by TomGeske** [comment]
Thank you for your feedback. We are currently working on getting cloud shell updated. 

PR: https://github.com/Azure/CloudShell/pull/28

@maertendMSFT, @edyoung do you have an ETA?

cc: @palma21

**Comment by TomGeske** [comment]
PR has been merged. Target is Ignite.

**Comment by navba-MSFT** [comment]
@iamalexmang Apologies for the late reply. This issue is open for quite sometime. Please let us know if you need any further assistance on this issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@iamalexmang Thanks for getting back. [This](https://docs.microsoft.com/en-us/azure/aks/managed-aad#prerequisites) article talks about the AKS with managed AAD integration and under the prerequisites section it has mentioned the kubectl version:

>Kubectl with a _minimum version_ of [1.18.1](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#v1181) or [kubelogin](https://github.com/Azure/kubelogin)

The cloud shell has the kubectl already installed with a higher version. So it should be good for you to use this.

>****@Azure$ **kubectl version**
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"f2fbef752f852512e05e85ebba94d05c90ee0354", GitTreeState:"clean", BuildDate:"2021-11-16T17:13:07Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

Please let me know if you have any questions on this.

**Comment by iamalexmang** [comment]
I'm not sure that the niche use case related to AAD integration from two years ago helps highlight the issue related to the inability to update Azure CLI on Cloud Shell.

I believe it should be possible to update the Azure CLI to support advancements in CLI (preview extensions or not, that should be irrelevant) in Cloud Shell.

**Comment by navba-MSFT** [comment]
@iamalexmang This is documented [here](https://docs.microsoft.com/en-gb/azure/cloud-shell/troubleshooting#user-permissions) as you do not have full access to the cloud shell environment. So you can follow the below steps:

To install individual versions download to a specified path in the home folder, for example:

>*****@Azure:~$ az aks install-cli --install-location mykubetools/kubectl1.19.1 --client-version 1.19.1 --kubelogin-install-location mykubetools/kubelogin

>Downloading client to "mykubetools/kubectl1.19.1" from [[https://storage.googleapis.com/kubernetes-release/release/v1.19.1/bin/linux/amd64/kubectl](https://storage.googleapis.com/kubernetes-release/release/v1.19.1/bin/linux/amd64/kubectl)]
Please ensure that mykubetools is in your search PATH, so the `kubectl1.19.1` command can be found.
Downloading client to "/tmp/tmps1qp6p1e/kubelogin.zip" from [[https://github.com/Azure/kubelogin/releases/download/v0.0.11/kubelogin.zip](https://github.com/Azure/kubelogin/releases/download/v0.0.11/kubelogin.zip)]
Please ensure that mykubetools is in your search PATH, so the `kubelogin` command can be found.

>*****@Azure:~$ ./mykubetools/kubectl1.19.1 version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)

Hope this helps. Please let me know if you have any further questions on this.

**Comment by iamalexmang** [comment]
Excellent answer, @navba-MSFT. This definitely helps a lot.
I believe it's safe to close down the issue now.

**Comment by navba-MSFT** [comment]
@iamalexmang Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
