### ISSUE TITLE
Unable to import function api into apim

### ISSUE THREAD

**Issue by tonyalanschleich** [Azure/azure-cli#15000]
## Unable to import function api into apim

**Command Name**
`az apim api import`

**Errors:**
```
must be str, not NoneType
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-kl_cpqvn\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 711, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-imoq0319\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
pip-unpacked-wheel-d55550gx\azure\cli\core\__init__.py, ln 779, in default_command_handler
azure\cli\command_modules\apim\custom.py, ln 263, in import_apim_api
TypeError: must be str, not NoneType
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim api import --path {} --resource-group {} --service-name {}`

## Expected Behavior
Import function app into apim

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.10.1 *

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
apim

**Comment by miaojiang** [comment]
It is not supported at the moment. 

cc @RupengLiu

**Comment by dslot** [comment]
@miaojiang Any updates on this issue?

**Comment by navba-MSFT** [comment]
@tonyalanschleich Apologies for the late reply. We are looking into this issue. We will provide an update once we have more details on this.

@adrianhall Could you please provide an update on this ? Awaiting your reply.

**Comment by celluj34** [comment]
I would really like to have this functionality too. Is there any workaround?

**Comment by adrianhall** [comment]
The ability to import a function app is not available in the API as yet.  It is in our current plan, however, and we have backlog items to add it.  Once the capability is in the API, we can (and will) revisit adding it to the CLI and PWSH capabilities.  Sorry I don't have better news for you, but this is a long-term item (moving import functionality from the Portal into API).

#please-close

**Comment by navba-MSFT** [comment]
Thanks @adrianhall
