### ISSUE TITLE
Webapp:"az webapp create" call fails - claiming ressource is in another resource group

### ISSUE THREAD

**Issue by perkops** [Azure/azure-cli#15009]
**Describe the bug**
We have 2 resource groups.

Resource Group A and Resource Group B.

A webapp is created in Resource Group **A**.
A FunctionApp is created in Resource Group **B**.

The naming of the webapp is: xxx
The naming of the FunctionApp is: xxxsource

Whenever we try to run our az cli deployment step from Azure DevOps, we get this error when trying to deploy webapp (after FunctionApp has been deployed).

The webapp 'xxx' exists in resource group '**B**' and does not match the value entered '**A**'. Please re-run command with the correct parameters.

The webapp clearly does not exist in resource group B, but in A. But somehow the az cli command picks up the ressource from the wrong resource group. The only reason we can think of, is that the az cli does some sort of "StartsWith" matching to find the webapp name and checks if it exists.

Sometimes the pipeline runs fine and sometimes it fails - so it looks like a list is retrieved inside the az cli, where ordering is not guaranteed.

**To Reproduce**
Create two resource groups. Create a webapp in the first ResourceGroup and a FunctionApp in the second resource group.
The try to re-provision the webapp again from azure devops pipeline.

**Expected behavior**
The az cli script should not return an error stating that the resources exists in a wrong resource group when running "az webapp create" again.

**Environment summary**
Information from pipeline in Azure DevOps.

Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/Powershell Core/Batch script when running on Windows agent.
Version      : 2.0.16
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
azure-cli                         2.10.1 *

command-modules-nspkg              2.0.3
core                              2.10.1 *
nspkg                              3.0.4
telemetry                          1.0.4 *

Extensions:
azure-devops                      0.18.0

**Comment by yonzhan** [comment]
webapp

**Comment by ThejaChoudary** [comment]
@perkops Can you please let us know exactly what cli command you are using and also are you facing the same with the cli command itself without the azure Devops Cli ?

**Comment by perkops** [comment]
> @perkops Can you please let us know exactly what cli command you are using and also are you facing the same with the cli command itself without the azure Devops Cli ?

Hi @ThejaChoudary,

We managed to work around this issue, by simply making the names not match that much, so I do not have the current error setup at hand atm. From my memory this was only an issue on Azure DevOps, and only sometimes, as I wrote in the initial text.

For the webapp part, the code looks like the following in one project:

Write-Host "  Create web app" -ForegroundColor DarkYellow
$output = az webapp create `
  --name $apiName `
  --resource-group $resourceGroupName `
  --plan $appServicePlanId `
  --tags $resourceTags

For the Function app part, the code looks like the following in another project:

Write-Host "  Creating function app" -ForegroundColor DarkYellow
$output = az functionapp create `
--name $functionAppName `
--resource-group $resourceGroupName `
--storage-account $storageAccountId `
--app-insights-key $instrumentationKey `
--plan $appServicePlanId `
--runtime dotnet `
--functions-version 3 `
--tags $resourceTags

And then when we tried to provision webapp once again from CI/CD pipeline, it would sometimes fail, saying that the webapp was in another resource-group (than it was).

**Comment by panchagnula** [comment]
thanks for the update @perkops - have you tried to add a wait b/w the two create calls when calling via DevOps? Also if you repro this again can you run both CLI commands in AzureDevops with --debug at the end so we can get a stack trace & see if we can capture more info? Please feel free to re-activate when you have more info.

**Comment by perkops** [comment]
So - the two steps are actually from each of their own pipeline - so a wait would not work.

It cant give you more information than I have already provided - it should be enough to fix the error.

**Comment by perkops** [comment]
@panchagnula I cant find any button to re-activate the issue.

**Comment by panchagnula** [comment]
@perkops is there a reason you believe this is a CLI error? if you run the CLI commands without devops pipeline would it work?

**Comment by perkops** [comment]
> @perkops is there a reason you believe this is a CLI error? if you run the CLI commands without devops pipeline would it work?

Yes - it works if we run the commands from local azure cli.

**Comment by panchagnula** [comment]
> > @perkops is there a reason you believe this is a CLI error? if you run the CLI commands without devops pipeline would it work?
> 
> Yes - it works if we run the commands from local azure cli.

That makes me believe its something to do with Devops pipeline & this is repo is for CLI only. @yonzhan this issue is specific to using CLI commands to devops pipeline any pointers on how to help @perkops ? Thanks!

**Comment by yonzhan** [comment]
devops pipeline service team should look into this.
