### ISSUE TITLE
[Enhancement Proposal] Support hint message after output is printed

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#15003]
## Issue

Related to #14933. Sometimes, the user's account has access to many subscriptions (for example, over 300).

## Proposal

Azure CLI should support a **hinting mechanism** that can print some hint message to `stderr` after the output is sent to knack, in order to provide a better user experience. 

For example, after `az login` prints all available subscriptions, CLI can show:

```
WARNING: The current subscription is 0b1f6471-1bf0-4dda-aec3-cb9272f09590 AzureSDKTest.
WARNING: To list all available subscriptions, run `az account list`.
WARNING: To switch to another subscription, run `az account set --subscription <subscription_id>`.
```

Hinting can be turned on/off with

```
az config set hint=true
az config set hint=false
```

**Comment by yonzhan** [comment]
Support hint message
