### ISSUE TITLE
Export template of a deployed resource

### ISSUE THREAD

**Issue by yene** [Azure/azure-cli#15006]
Hi, currently I manually open the application gateway in Azure portal and export its template (via the "Export template" page) to my local PC. As a backup and for configuration review.
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/export-template-portal#export-template-from-a-resource

Is it possible to get the Template of the current deployed Application Gateway from command line?
If not can this be added?

**Comment by yonzhan** [comment]
Export template

**Comment by zhoxing-ms** [comment]
@yene Hi, could you please try command `az deployment group/mg/sub/tenant export` to see if it meets your needs?

**Comment by yene** [comment]
no success with these commands

**Comment by zhoxing-ms** [comment]
@yene May I ask which scope the resource you want to export is deployed, and which export command you used?
