### ISSUE TITLE
[AppService] add `web start` command

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-cli#1501]
Currently only these are available for `az appservice web`: `{browse, create, delete, list, restart, show, stop}`. Could a `start` command be added?

The reason I need this is that a web app created for Linux doesn't work until the site is stopped and started, and `web restart` doesn't help from the CLI or the portal. I'd like to add the `stop` and `start` commands to the end of my deploy script.

**Comment by yugangw-msft** [comment]
We will add `start`, though odd, but for now would `stop` and `restart` will do it?

**Comment by joshgav** [comment]
@yugangw-msft 

> but for now would `stop` and `restart` will do it

Actually no, `restart` doesn't seem to work after `stop` (same in CLI and portal), and `restart` alone (without `stop` first) doesn't cause the app to start working.

I agree it's odd, and I think the best thing would be for restart to yield the exact same results as stop/start.

Thanks!

**Comment by yugangw-msft** [comment]
@naziml, please clarify

**Comment by joshgav** [comment]
FWIW you should be able to test with [this script](https://github.com/joshgav/azure-scripts/blob/master/appsvc/webapp-deploy.sh), just set the env vars at the top with your own names.
