### ISSUE TITLE
How to create az aks,Operation failed with status: 'Bad Request

### ISSUE THREAD

**Issue by gympohnpimol** [Azure/azure-cli#15013]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
Operation failed with status: 'Bad Request'. Details: Provisioning of resource(s) for container service mssql-20200831192302 in resource group mssql-20200831192302 failed. Message: Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus, Current Limit: 4, Current Usage: 1, Additional Required: 40, (Minimum) New Limit Required: 41. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%22e1b13ebd-105a-42d5-a869-655a1ea0baef%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests.. Details:
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --name {} --resource-group {} --generate-ssh-keys --node-vm-size {} --node-count {}`

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.5
Installer: HOMEBREW

azure-cli 2.11.1

Extensions:
interactive 0.4.4

```

**Comment by yonzhan** [comment]
aks

**Comment by TomGeske** [comment]
Did you verify you have enough core quota?

`Message: Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus, Current Limit: 4, Current Usage: 1, Additional Required: 40, (Minimum) New Limit Required: 41.`

**Comment by gympohnpimol** [comment]
> Did you verify you have enough core quota?
> 
> `Message: Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus, Current Limit: 4, Current Usage: 1, Additional Required: 40, (Minimum) New Limit Required: 41.`
