### ISSUE TITLE
Incorrect error message when adding ssl-cert to the application gateway from the keyvault

### ISSUE THREAD

**Issue by timvanderweijde** [Azure/azure-cli#15011]
## Describe the bug

**Command Name**
`az network application-gateway ssl-cert create`

**Errors:**
```
Deployment failed. Correlation ID: 6fe6685c-2344-45ea-8872-1916cd637848. Access denied for KeyVault Secret 'https://portals-nonprod-keyvault.vault.azure.net/secrets/www-x-a1-t-mobile-nl-chain/531974e9bcf0487ea6f2f5aee6248f19' for Application Gateway '/subscriptions/b7ec6ddd-f866-4ad9-86b1-a0acc527a254/resourceGroups/tmobile-portals-nonprod-public/providers/Microsoft.Network/applicationGateways/ag-nonprod-public'. Make sure that Identity assigned to Application Gateway has access to the KeyVault associated with secret.

_However, the certificate is installed from the keyvault. The errors is wrong and not needed._
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- az identity create -g {}-n {}
- $principalId = $(`az identity show -g {} -n {} --query 'principalId' -o tsv)
   az keyvault set-policy --name {} -g {} --certificate-permissions get list --secret-permissions get list --object-id $principalId
- `az network application-gateway ssl-cert create -g {} --gateway-name {} -n {} --key-vault-secret-id {}`

## Expected Behavior
No error message.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.10.1 *

```

**Comment by yonzhan** [comment]
network

**Comment by timvanderweijde** [comment]
Why is this  a "Feature Request" and not a "Issue/Bug"?

**Comment by yonzhan** [comment]
@timvanderweijde mark this as bug

**Comment by haroldrandom** [comment]
Could you try to assign the managed identity to your application gateway as well, `az network application-gateway identity assign` before associate the secret with the application gateway?

**Comment by timvanderweijde** [comment]
I believe I did, but forget to mentioned in the description. However, to be sure I will retest it again. I will come back to you on that.

**Comment by timvanderweijde** [comment]
I retested it again, but still the same result. The identity was added to the Application Gateway with the flag -identity already.

Same error: 
Deployment failed. Correlation ID: f1f49a96-8873-4317-b099-bd5f0c6fef71. Access denied for KeyVault Secret '<Secret Identifier url>' for Application Gateway '<gateway url>'. Make sure that Identity assigned to Application Gateway has access to the KeyVault associated with secret.

**Comment by timvanderweijde** [comment]
Any update on this?

**Comment by haroldrandom** [comment]
@timvanderweijde Sorry for the late reply. I asked round my teammates, we considering it might be a bug the service or some potential permission problem.

I will mark this as "Service Attention", add @bim-msft might help.

Also, you could contact Azure Support to check detail about your operation.

**Comment by bim-msft** [comment]
Hi @timvanderweijde I saw your steps:
```
$principalId = $(`az identity show -g {} -n {} --query 'principalId' -o tsv)
az keyvault set-policy --name {} -g {} --certificate-permissions get list --secret-permissions get list --object-id $principalId
```

Could you try directly paste the value of the principal id and do not use the shell variable? It might work, but not sure. Anyway, it worth a try. :-)

**Comment by bim-msft** [comment]
@timvanderweijde 
Also please provide the result of your `az keyvault show`, I'd like to know what `accessPolicies` part looks like. Thanks!

**Comment by timvanderweijde** [comment]
Hi @bim-msft, is there a way to share this information on a secure way?

**Comment by bim-msft** [comment]
Hi @timvanderweijde send it to me via email (bim@microsoft.com), thanks!

BTW, did this way work?

> Could you try directly paste the value of the principal id and do not use the shell variable? It might work, but not sure. Anyway, it worth a try. :-)

**Comment by timvanderweijde** [comment]
Goodmorning. I tried to paste the value directly, but it did not work.

I will send you the log/json of the az keyvault show.

**Comment by timvanderweijde** [comment]
@bim-msft Goodmorning. Do you have any update on this issue?

**Comment by yonzhan** [comment]
@yungezz for awareness.

**Comment by yungezz** [comment]
hi @timvanderweijde ,when you run below command, are the logged in user identity same as identity created by `az identity`?
```
az identity create -g {}-n {}
$principalId = $(`az identity show -g {} -n {} --query 'principalId' -o tsv)
az keyvault set-policy --name {} -g {} --certificate-permissions get list --secret-permissions get list --object-id $principalId
az network application-gateway ssl-cert create -g {} --gateway-name {} -n {} --key-vault-secret-id {}
```

Unfortunately, @bim-msft is on long vacation now.

**Comment by timvanderweijde** [comment]
@yungezz 
No, I'm logged in under my own account (with the highest privileges) and run above commands. 
And as a I mentioned before, the created user identity was added to the Application Gateway with the flag -identity already.

**Comment by timvanderweijde** [comment]
Goodmorning, any update on this?

**Comment by bim-msft** [comment]
Hi @timvanderweijde sorry, I just came back from vacation and I will continue to investigate this issue. No updates so far.

**Comment by timvanderweijde** [comment]
H @bim-msft how was your vacation?

And any update on this issue?

**Comment by sebansal** [comment]
@haroldrandom We'd like to understand the issue from the key vault service perspective

**Comment by timvanderweijde** [comment]
@sebansal  @haroldrandom If there is anything I can do let me know.

**Comment by haroldrandom** [comment]
Might be related to this one https://github.com/Azure/azure-cli/issues/8244

**Comment by msfcolombo** [comment]
Agree with @sebansal. For assistance from the KV team, we need to understand what the key vault service is returning.

The error message from the bug description is not from Key Vault. I'm speculating that App Gateway is translating any 403 received from Key Vault into a permission issue. However, Key Vault may return 403 also when the firewall blocks access, or when the certificate is disabled.

In order to find the root cause, I recommend enabling KV logs as described [in this article](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/key-vault-insights-overview). Search for "operations workbook" and check for accesses made to Key Vault while the command `az network application-gateway ssl-cert create` is execute (it might take about 10 minutes until the logs appear).

Then you will see exactly what Key Vault is returning to App Gateway and we can resume assistance from there.
