### ISSUE TITLE
Add az vmss extension-upgrade start API to CLI

### ISSUE THREAD

**Issue by chjaress** [Azure/azure-cli#15017]
**Resource Provider**
Compute Resource Provider

**Description of Feature or Work Requested**
To add az vmss extension-upgrade start command to CLI to invoke extension upgrades on VMSS resources. This should invoke the extensionRollingUpgrade API in CRP to upgrade all extensions to their latest version on a VMSS.

Sample command: az vmss extension-upgrade start --name "VMScaleSetName" --resource-group "ResourceGroupName" --subscription "SubscriptionId"

**Minimum API Version Required**
2017-12-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/23a83bfbab7f956695e0e0082b24ae08c99bf80f/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json#L4912

**Target Date**
09/20/2020

**Comment by yungezz** [comment]
hi @chjaress is this Ignite ask?

**Comment by chjaress** [comment]
hi @yungezz if possible yes :)

**Comment by houk-ms** [comment]
Supported in #15238, repoen the issue if there are any questions here.
