### ISSUE TITLE
Add an example for az keyvault set-policy

### ISSUE THREAD

**Issue by samsmithnz** [Azure/azure-cli#15016]
There is example for some of the other commands, but not az keyvault set-policy, and it's not clear what the format should be, and I had to go to another page to find an example.

for example: 

az keyvault set-policy --name MyKeyVault --object-id $MyPrincipalId --secret-permissions list get
               
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226e5769-f6c8-a480-db78-727fb96348ec
* Version Independent ID: 8ee06a2a-6eda-11be-3c8e-6ad948be207e
* Content: [az keyvault](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @bim-msft could you pls add the example? thanks.
