### ISSUE TITLE
Update az vm get-instance-view command with VMHealth field

### ISSUE THREAD

**Issue by chjaress** [Azure/azure-cli#15018]
**Resource Provider**
Compute Resource Provider

**Description of Feature or Work Requested**
There is a new property being returned by the get instance view API called VMHealth. This VMHealth has the following json structure: "vmHealth": {
"status": {
"code": "HealthState/unhealthy",
"level": "Error",
"displayStatus": "The VM is reporting itself as unhealthy or is unreachable",
"time": "2020-06-25T14:04:48-07:00"
}
}

The request is to add this new field to the output of the az vm get-instance-view CLI command

**Minimum API Version Required**
2020-06-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/23a83bfbab7f956695e0e0082b24ae08c99bf80f/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json#L8875

**Target Date**
09/20/2020

**Comment by yungezz** [comment]
hi @chjaress is this Ignite ask?

**Comment by chjaress** [comment]
hi @yungezz if possible yes :)

**Comment by chjaress** [comment]
> @chjaress
> When I call the service API (2020-06-01) to get the instance view of vm, the vmHealth property is not in the response. What might be the problem？Here is my test.
> 
> **GET**
> 
> ```
> https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/houk-test/providers/Microsoft.Compute/virtualMachines/houk-vm/instanceView?api-version=2020-06-01
> ```
> 
> **Response**
> 
> ```
> {
>   "computerName": "houk-vm",
>   "osName": "ubuntu",
>   "osVersion": "18.04",
>   "vmAgent": {
>     "vmAgentVersion": "2.2.49.2",
>     "statuses": [
>       {
>         "code": "ProvisioningState/succeeded",
>         "level": "Info",
>         "displayStatus": "Ready",
>         "message": "Guest Agent is running",
>         "time": "2020-09-07T07:47:42+00:00"
>       }
>     ],
>     "extensionHandlers": []
>   },
>   "disks": [
>     {
>       "name": "houk-vm_disk1_ce7f7033ba904fa8aa38bb06dcf7277a",
>       "statuses": [
>         {
>           "code": "ProvisioningState/succeeded",
>           "level": "Info",
>           "displayStatus": "Provisioning succeeded",
>           "time": "2020-09-07T07:28:07.4483639+00:00"
>         }
>       ]
>     }
>   ],
>   "bootDiagnostics": {
>     "consoleScreenshotBlobUri": "https://houktestdiag.blob.core.windows.net/bootdiagnostics-houkvm-adb86a11-0c66-4f68-89a4-6357a8105a9f/houk-vm.adb86a11-0c66-4f68-89a4-6357a8105a9f.screenshot.bmp",
>     "serialConsoleLogBlobUri": "https://houktestdiag.blob.core.windows.net/bootdiagnostics-houkvm-adb86a11-0c66-4f68-89a4-6357a8105a9f/houk-vm.adb86a11-0c66-4f68-89a4-6357a8105a9f.serialconsole.log"
>   },
>   "hyperVGeneration": "V1",
>   "statuses": [
>     {
>       "code": "ProvisioningState/succeeded",
>       "level": "Info",
>       "displayStatus": "Provisioning succeeded",
>       "time": "2020-09-07T07:28:23.9334785+00:00"
>     },
>     {
>       "code": "PowerState/running",
>       "level": "Info",
>       "displayStatus": "VM running"
>     }
>   ]
> }
> ```

@houk-ms  For Windows VMs you have to add the health extension for it to show in the instance view:

{
  "properties": {
    "forceUpdateTag": "RerunExtension",
    "publisher": "Microsoft.ManagedServices",
    "type": "ApplicationHealthWindows",
    "typeHandlerVersion": "1.0",
    "autoUpgradeMinorVersion": true,
    "settings": {
        "port": 3389,
        "protocol": "tcp"
    },
    "protectedSettings": "{}"
    }
}

The output of the get instance view should then have something like this:

      "vmHealth": {
        "status": {
          "code": "HealthState/unhealthy",
          "level": "Error",
          "displayStatus": "The VM is reporting itself as unhealthy or is unreachable",
          "time": "2020-06-25T14:04:48-07:00"
        }
      }

**Comment by houk-ms** [comment]
@chjaress Thanks for the clarification.

**Comment by houk-ms** [comment]
I checked it, it seems our latest version (2.11.1) already supported it. @chjaress Can you help confirm it?

**Comment by houk-ms** [comment]
Already supported, repoen the issue if there are any questions here.
