### ISSUE TITLE
cannot change app gw waf owasp version via cli

### ISSUE THREAD

**Issue by steveaustin0101** [Azure/azure-cli#15019]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az network application-gateway waf-policy managed-rule rule-set add
issue was included in milestone
-  https://user-images.githubusercontent.com/70607958/91909283-88934080-ec72-11ea-883f-13011c493ae4.png

milestone released
downloaded / install cli 2.11.1
issue persists

**To Reproduce**
az login
az account set --subscription "subid"
az network application-gateway waf-policy managed-rule rule-set add -g <resourceGroup> --policy-name <wafPolicyName> --version 3.1 --type owasp 
az network application-gateway waf-policy managed-rule rule-set list --policy-name <wafPolicyName> -g <resourceGroup>
...  last command confirms current version number

**Expected behavior**
for version number to change = 3.1
portal seems to be only pathway at the moment ... do we have a publishable timeline for the release ?

**Environment summary**
cli 2.11.1

**Additional context**
none

**Comment by fengzhou-msft** [comment]
@MyronFanQiu can you take a look?

**Comment by yonzhan** [comment]
add to S176

**Comment by haroldrandom** [comment]
@steveaustin0101 What do you mean `for version number to change = 3.1` ?

**Comment by steveaustin0101** [comment]
the default owasp version is 3.0 , and trying to change to another version , like 3.1

Sent from Yahoo Mail on Android 
 
  On Tue, Sep 22, 2020 at 11:25 PM, Jianhui Harold<notifications@github.com> wrote:   


@steveaustin0101 What do you mean for version number to change = 3.1 ?

**Comment by haroldrandom** [comment]
@steveaustin0101 I get your point. An RP is under reviewing and this will be fixed in the upcoming release

**Comment by steveaustin0101** [comment]
super , thank you

Sent from Yahoo Mail on Android 
 
  On Wed, Sep 23, 2020 at 8:49 PM, Jianhui Harold<notifications@github.com> wrote:   


@steveaustin0101 I get your point. An RP is under reviewing and this will be fixed in the upcoming release

**Comment by haroldrandom** [comment]
@steveaustin0101 The patch is merged, and the next version available for this fix is 2.13.0

**Comment by steveaustin0101** [comment]
thanks for update Jianhui .  is release timeline set yet

Sent from Yahoo Mail on Android 
 
  On Fri, Oct 9, 2020 at 2:12 AM, Jianhui Harold<notifications@github.com> wrote:   


@steveaustin0101 The patch is merged, and the next version available for this fix is 2.13.0
