### ISSUE TITLE
 Utilize new API for Public IPs

### ISSUE THREAD

**Issue by brianlehr** [Azure/azure-cli#15015]
**Resource Provider**
Az.Network

**Description of Feature or Work Requested**
Please begin to use API 2020-08-01, which has a breaking change for public IP creation as described here: https://github.com/brianlehr/azure-docs-pr/blob/brianlehrbranch/articles/virtual-network/create-public-ip-cli.md

That is, to create a standard zone-redundant public ip, you must now use --zone 1,2,3 in the parameter as opposed to not adding a zone parameter.

  az network public-ip create \
    --resource-group myResourceGroup \
    --name myStandardZRPublicIP \
    --sku Standard
    --zone 1,2,3 

If you do not add a zone parameter, the resource is created as non-zonal by default.  This is different from how the current API and CLI operate!

**Minimum API Version Required**
2020-08-01

**Target Date**
This cannot be applied until NRP 151 rolls out, which should complete over the month of September.  But it should be applied to coincide with this rollout.

Also need to know which CLI version will end up having this so we can update docs accordingly.

**Comment by yonzhan** [comment]
add to S176

**Comment by jsntcy** [comment]
Check if #12197 covers the same feature.

**Comment by brianlehr** [comment]
@yonzhan @haroldrandom  Hi team - which version of the CLI will the new API be included in?  Need to include for our documentation.

**Comment by haroldrandom** [comment]
@brianlehr As far as I know, the SDK for 2020-07-01 is till waiting for release and it might take 1~1.5 month to ship. And we are still at 2020-06-01. And the 2020-08-01 is sound to be ready at November. Based on the duration between releases is 3 weeks, I think the version might be between 2.15-2.17

**Comment by dennis-benzinger-hybris** [comment]
Early October is over :-). Is there a more precise ETA now?

**Comment by haroldrandom** [comment]
> Early October is over :-). Is there a more precise ETA now?

Not yet. We are still waiting for the swagger merged.

**Comment by brianlehr** [comment]
Checking again on this.

> > Early October is over :-). Is there a more precise ETA now?
> 
> Not yet. We are still waiting for the swagger merged.

**Comment by haroldrandom** [comment]
@brianlehr Could you post your swagger PR in this PR body as well

**Comment by msyyc** [comment]
@brianlehr The minimum version "2020-08-01" for network is not prepared. Please inform us when it prepared.

**Comment by brianlehr** [comment]
> @brianlehr The minimum version "2020-08-01" for network is not prepared. Please inform us when it prepared.

That is fine.  This unfortunately was not created earlier and is coming by around late Jan/early Feb.  I'll let you know.

**Comment by brianlehr** [comment]
@yonzhan @haroldrandom  Hello again - here's the version you need: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/network/resource-manager/Microsoft.Network/stable/2020-08-01

Apologies for the delay!

**Comment by msyyc** [comment]
@brianlehr Got it and we plan to finish the feature after 2021/02/09. FYI

**Comment by brianlehr** [comment]
Both these commands need to also have the exact same zone behavior as **az network public-ip create**

**az network public-ip prefix create**
**az network lb frontend-ip create** (for a Standard load balancer only)

In other words, when you create these resources, you need to explicitly specify --zone 1 2 3 to create a zone-redundant resource.  If no --zone parameter is provided, then the resource is created with no zone.
