### ISSUE TITLE
az storage blob list - crash

### ISSUE THREAD

**Issue by KevinBuchs** [Azure/azure-cli#15025]
## Describe the bug

**Command Name**
`az storage blob list`

**Errors:**
```
get_token() takes 1 positional argument but 2 were given
Traceback (most recent call last):
Temp\pip-unpacked-wheel-mtleih48\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 654, in execute
cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
cli\core\commands\__init__.py, ln 709, in _run_job
cli\command_modules\storage\__init__.py, ln 334, in new_handler
cli\core\commands\__init__.py, ln 688, in _run_job
cli\core\commands\__init__.py, ln 325, in __call__
azure\cli\core\__init__.py, ln 782, in default_command_handler
...
azure\core\pipeline\_base.py, ln 71, in send
  [Previous line repeated 3 more times]
azure\core\pipeline\_base.py, ln 69, in send
azure\core\pipeline\_tools.py, ln 29, in await_result
core\pipeline\policies\_authentication.py, ln 93, in on_request
TypeError: get_token() takes 1 positional argument but 2 were given
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- From Azure Windows VM with a managed identity allowing access to the storage account.
- This worked:
  - az storage container list --account-name <my-account> --auth-mode login
- This failed:
  - az storage blob list --account-name <my-account> -c <my-container> --auth-mode login

## Versions
az version
{
  "azure-cli": "2.11.1",
  "azure-cli-core": "2.11.1",
  "azure-cli-telemetry": "1.0.5",
  "extensions": {}
}

get-computerinfo
WindowsBuildLabEx                                       : 14393.2312.amd64fre.rs1_release.180607-1919
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : ServerDatacenter
WindowsInstallationType                                 : Server
WindowsInstallDateFromRegistry                          : 8/6/2018 5:18:49 PM
WindowsProductId                                        : 00376-40000-00000-AA947
WindowsProductName                                      : Windows Server 2016 Datacenter

$PSVersionTable
Name                           Value
PSVersion                      5.1.14393.2312
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2312
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

# Installation of Azure CLI
# previously installed Python3.8 from https://python.org for single user.
Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi
# Installed 9/2/2020

**Comment by yonzhan** [comment]
add to S175

**Comment by dougan001** [comment]
Seeing the same behaviour on Linux - Ubuntu

**Comment by Juliehzl** [comment]
Hi @KevinBuchs and @dougan001, sorry for inconvenience. Could you remove `--auth-mode login` if you are in terminal usage or add `--account-key`/`--sas-token`/'--connection-string` ad credential?

**Comment by KevinBuchs** [comment]
@Juliehzl are you asking us to do this as a test or a work-around?

**Comment by Juliehzl** [comment]
Hi the provided solution for `--account-key`... is work-around.
And the fix is already merged. You could try with edge build installed now.
See here for more information https://github.com/Azure/azure-cli#edge-builds.
