### ISSUE TITLE
"No module named 'antlr4'" exception when issuing azure-cli command ''az vm list-sizes southafricanorth"

### ISSUE THREAD

**Issue by mornemaritz** [Azure/azure-cli#15023]
## Describe the bug

**Command Name**
`az vm list-sizes southafricanorth`

**Errors:**
```
No module named 'antlr4'
Traceback (most recent call last):
lib/python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
dist-packages/azure/cli/core/__init__.py, ln 300, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
azure/cli/command_modules/vm/__init__.py, ln 31, in load_arguments
    from azure.cli.command_modules.vm._params import load_arguments
azure/cli/command_modules/vm/_params.py, ln 31, in <module>
    from azure.cli.command_modules.monitor.actions import get_period_type
azure/cli/command_modules/monitor/actions.py, ln 7, in <module>
    import antlr4
ModuleNotFoundError: No module named 'antlr4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- was following this terraform tutorial https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_secret.html
- `az login --service-principal -u xxxxx -p xxxxx --tenant xxxx`
- `az vm list-sizes southafricanorth`

## Expected Behavior
Sizes of vms to be displayed?

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yungezz** [comment]
duplicate with #14011 . hi @mornemaritz does workaround mentioned in #14011: uninstall then install azure cli?

Please first uninstall azure-cli 2.0.81 and its dependencies:
sudo apt remove azure-cli -y && sudo apt autoremove -y
Then install the latest azure-cli:
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

**Comment by mornemaritz** [comment]
Hi @yungezz, issue resolved. Thank you very much for your prompt response.
