### ISSUE TITLE
az firewall create is passing "Network.DNS.EnableProxy": "True" instead of lower case true

### ISSUE THREAD

**Issue by tejasshah7** [Azure/azure-cli#15028]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
It seems when configuration EnableProxy field on Azure Firewall via Az CLI, the value being passed is True instead of true and this causes failure in the backend.

**To Reproduce**
https://portal.microsofticm.com/imp/v3/incidents/details/203146390/home

**Expected behavior**
This field needs to be set as "true" like it is set by Powershell and portal.

**Environment summary**

**Additional context**
Customer reported this issue. Corresponding CRI is pasted above for reference.

**Comment by yonzhan** [comment]
add to S176

**Comment by tejasshah7** [comment]
Please make sure similar change is made for other fields while pass true/false under Network.DNS.
