### ISSUE TITLE
[AppService] automatically start first git repo sync

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-cli#1502]
When an external git repo is set for a Node on Linux web app with `az appservice web source-control config ...` it doesn't do the initial sync until I call `az appservice web source-control sync ...` or click the Sync button in the portal. I'm not using the `--manual-integration` flag.

IMO it would be more expected that the initial sync would start automatically.

**Comment by yugangw-msft** [comment]
Let me clarify with the webapp team. My observations are, though not a proof, the sync always auto-started when the source control configuration got updated

**Comment by yugangw-msft** [comment]
We will trigger a sync in the command

**Comment by LukaszStem** [comment]
The change is being made here https://github.com/Azure/azure-cli/pull/2326

**Comment by yugangw-msft** [comment]
PR#2326 was merged
