### ISSUE TITLE
Add notice on future depracated command group

### ISSUE THREAD

**Issue by lincolnpires** [Azure/azure-cli#15024]
The command group `cosmosdb database` will be deprecated soon - maybe add a notice on the docs :)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da15197a-eca2-19d6-72e3-be853337a759
* Version Independent ID: eb84d467-86df-121e-3b04-66b499342f7f
* Content: [az cosmosdb database](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/database?view=azure-cli-latest#az-cosmosdb-database-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cosmosdb

**Comment by shurd** [comment]
Hi @lincolnpires thank you for opening this issue. Right now, I believe all the documentation is auto-generated, and the generator does not include information about deprecation warning. I am not sure if the CLI team is planning on adding support for including deprecation info in the documentation.

**Comment by lincolnpires** [comment]
@shurd no problem. I didn't really know how that's generated. In that case, probably when they actually deprecate the feature the docs will be re-generated and everything will be fine. So, maybe not an issue.
I'm ok with closing this ;)
Thanks.

**Comment by MehaKaushik** [comment]
Closing, since no action is required from CosmosDB end.
