### ISSUE TITLE
az vm create tutorial link broken

### ISSUE THREAD

**Issue by elliotpeele** [Azure/azure-cli#15026]
The end-to-end tutorial link in the az vm create section returns a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
@qwordy , could you pls have a look?

**Comment by qwordy** [comment]
Thanks for finding this problem. I can't open it, either.
https://docs.microsoft.com/azure/virtual-machines/virtual-machines-linux-quick-create-cli
I search the internet. This is new link: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/quick-create-cli
I don't think docs team should change the link. Anyway, I will fix it.
