### ISSUE TITLE
Update vpn connection do put on connection instead of in s2s gateway

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#15036]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
Currently the s2s gateway connections are specified as a part of PUT on the s2s gateway. Now the connections can be created/updated or deleted only using direct PUT/DELETE calls on the s2s gateway connections.

- Only implementation change, no command interface change.
- Need update the following commands in `virtual-wan` extension.
  - `az network vpn-gateway connection create/delete/show/list`

**Minimum API Version Required**
2020-05-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2020-05-01/virtualWan.json#L2034

**Target Date**

**Comment by yonzhan** [comment]
add to S176
