### ISSUE TITLE
az vnet create - provide info on default subnet

### ISSUE THREAD

**Issue by cynthn** [Azure/azure-cli#1503]
When you use **az vnet create** it is awesome that it now creates a default subnet, but it doesn't say that anywhere in **-help**. 

Can you add in something like: "If **--subnetName** is not specified, a subnet named Subnet1 with the address prefix 10.0.0.1/24 is created automatically."

It would also be helpful if the default address prefix for **vnet create** was different from the one that **subnet create** uses. I didn't realize **vnet create** would create a default subnet, so when I went to create a subnet, it had a conflict with the address prefix of the auto-created subnet. The error message was just **"Subnet 'mySubnet' is not valid in virtual network 'myVnet'."** if they used different default address prefixes, I would have just ended up with 2 subnets instead of getting a vague error message.

**Comment by tjprescott** [comment]
@cynthn great points!

How is this for the new --help text for `vnet create`:
```
Command
    az network vnet create: Create a virtual network.
        By default, the created network will have a prefix of '10.0.0.0/16' and a single subnet
        named 'default' with a prefix of '10.0.0.0/24', unless otherwise specified.

Arguments
    --name -n           [Required]: The virtual network (VNET) name.
    --resource-group -g [Required]: Name of resource group.
    --address-prefix              : IP address prefix for the virtual network.  Default:
                                    10.0.0.0/16.
    --dns-servers                 : List of DNS server IP addresses.
    --location -l                 : Location.
    --subnet-name                 : The subnet name.  Default: Subnet1.
    --subnet-prefix               : IP address for the subnet.  Default: 10.0.0.0/24.
    --tags                        : Space separated tags in 'key[=value]' format. Use "" to clear
                                    existing tags.
```
