### ISSUE TITLE
az account list-locations

### ISSUE THREAD

**Issue by santoshpandey11** [Azure/azure-cli#15038]
## Describe the bug

**Command Name**
`az account list-locations`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account list-locations --query {} --output {}`

## Environment Summary
```
Linux-4.15.0-1092-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.11.1

Extensions:
ai-examples 0.2.3

```

**Comment by yonzhan** [comment]
add to S176

**Comment by jiasli** [comment]
Could you elaborate what the issue is? Thanks for the information.

**Comment by yonzhan** [comment]
@santoshpandey11 any update?

**Comment by santoshpandey11** [comment]
pl close this tkt
