### ISSUE TITLE
[AppService] linux web app must be stopped and started to work

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-cli#1504]
When I deploy a Linux web app using `az appservice web create ...`, `az appservice web config update ...` and `az appservice web source-control config ...` as in [this script](https://github.com/joshgav/azure-scripts/blob/ee5196a29a3107f350a56203ac39938046a119e6/appsvc/no-arm-deploy.sh), the web app doesn't work till I go into the portal and click the "Stop" and then "Start" button.

See also #1501, where one can't send a start command from the CLI, which makes this particularly troublesome. The `web restart` command doesn't seem to address the issue either.

The expected behavior would be that no stop/start is required.

**Comment by yugangw-msft** [comment]
@naziml, could you verify?
For non linux webapp, this definitely works as we have end to end tests verifying that
@joshgav , could you go to your git repository, and see whether there is a web hook created?

**Comment by joshgav** [comment]
@yugangw-msft Yes, a web hook is there in the repo for App Service. Next time I spin it up again I'll take note of when it gets created.

**Comment by yugangw-msft** [comment]
I tried and it works now. Of course you should upload a git token beforehand so CLI can wire up the auto-sync. Please reactivate if you still see a repro
