### ISSUE TITLE
Value 'Standard_B2s' specified for parameter 'RoleSize' is invalid

### ISSUE THREAD

**Issue by NoelAbrahams** [Azure/azure-cli#15042]
**Describe the bug**

I'm using Visual Studio Community 2019 version 16.7.2 to deploy a cloud service. The cloud service has been deployed successfully on numerous occasions using the `Standard_A1_v2` `vmsize`.

Trying to specify 'Standard_B2s' for `vmsize` results in the following error:

```
 Value 'Standard_B2s' specified for parameter 'RoleSize' is invalid. 
Allowed values are 'Standard_E20_v3,Standard_D48_v3,Standard_E48_v3,ExtraSmall,Small,Medium,Large,ExtraLarge,A5,A6,A7,A8,A9,A10,A11,Standard_D1,Standard_D2,Standard_D3,Standard_D4,Standard_D11,Standard_D12,Standard_D13,Standard_D14,Standard_D1_v2,Standard_D2_v2,Standard_D3_v2,Standard_D4_v2,Standard_D5_v2,Standard_D11_v2,Standard_D12_v2,Standard_D13_v2,Standard_D14_v2,Standard_D15_v2,Standard_G1,Standard_G2,Standard_G3,Standard_G4,Standard_G5,Standard_H8,Standard_H16,Standard_H8m,Standard_H16m,Standard_H16r,Standard_H16mr,Standard_A1_v2,Standard_A2_v2,Standard_A4_v2,Standard_A8_v2,Standard_A2m_v2,Standard_A4m_v2,Standard_A8m_v2,Standard_D2_v3,Standard_D4_v3,Standard_D8_v3,Standard_D16_v3,Standard_D32_v3,Standard_D64_v3,Standard_E2_v3,Standard_E4_v3,Standard_E8_v3,Standard_E16_v3,Standard_E32_v3,Standard_E64_v3'.
```

My Service definition looks a bit like this:

```xml
<ServiceDefinition name="azure" xmlns="http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition" schemaVersion="2015-04.2.6">
  <WebRole name="foo-bar" vmsize="Standard_B2s">
    <Sites>
      </Site>
    </Sites>
    <Endpoints>
    </Endpoints>
    <ConfigurationSettings>
    </ConfigurationSettings>
  </WebRole>
</ServiceDefinition>

```

**Expected behaviour**
This is a [valid VM size](https://docs.microsoft.com/en-us/azure/virtual-machines/sizes-b-series-burstable), so this error doesn't seem right.

**Environment summary**
I'm using Visual Studio. I have the latest version of the Azure CLI installed: `2.11.1`.

I'm assuming that Visual Studio uses the CLI under the covers.

Sorry if this is the wrong place, but any help will be much appreciated.

Thanks

**Comment by fengzhou-msft** [comment]
@qwordy can you help to take a look?

**Comment by qwordy** [comment]
I need to verify your assertion "Visual Studio uses the CLI under the covers" first.

**Comment by qwordy** [comment]
I find no evidence that visual studio relies on Azure CLI. Please ask for help via https://visualstudio.microsoft.com/support/. Thanks.
