### ISSUE TITLE
Creating a function App With Powershell Version 7.0 runtime fails

### ISSUE THREAD

**Issue by LLautt** [Azure/azure-cli#15041]
## Describe the bug

**Command Name**
`az functionapp create`

**Errors:**
```
'powershell'
Traceback (most recent call last):
Temp\pip-install-0u_uiwkq\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 608, in execute
azure\cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 657, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 55, in _polish_bad_errors
azure\cli\core\commands\__init__.py, ln 636, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 493, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 2333, in create_function
KeyError: 'powershell'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Runtime is powershell, version is 7.0

- _Put any pre-requisite steps here..._
- `az functionapp create --resource-group {} --name {} --storage-account {} --runtime {} --runtime-version {} --consumption-plan-location {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.80 *

```

**Comment by yonzhan** [comment]
functionapp

**Comment by apawast** [comment]
@gzuber could you please take a look at this?

**Comment by gzuber** [comment]
Hi @LLautt! Are you still experiencing this issue on more recent versions of the cli? It says here you're using 2.0.80, but I don't believe support was added for Powershell 7.0 until ~2.7.0

**Comment by gzuber** [comment]
@yonzhan I believe this issue can be closed. It hasn't been updated in a while and it looks like it was due to an out of date version of the cli.
