### ISSUE TITLE
Azure CLI support for Rule priority in Application Gateway

### ISSUE THREAD

**Issue by surajmb** [Azure/azure-cli#15050]
**Resource Provider**

NRP

**Description of Feature or Work Requested**

CLI support is needed for the release of rule priority feature for Application Gateway. This will add an additional property called "priority" in the *az network application-gateway rule* command. https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/rule?view=azure-cli-latest. 
The parameter takes an 'integer' value. Validations are added to NRP.

        "priority": {
          "type": "integer",
          "format": "int32",
          "minimum": 1,
          "exclusiveMinimum": false,
          "maximum": 20000,
          "exclusiveMaximum": false,
          "description": "Priority of the request routing rule."
        },

**Minimum API Version Required**

2019-09-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/applicationGateway.json

**Target Date**

End of September. The API is already out and we are working on PS and Portal, once done, we'll be targeting release in October.

**Comment by yonzhan** [comment]
@surajmb does this feature target for Ignite?

**Comment by surajmb** [comment]
Hi @yonzhan , it's not targeted for Ignite per se. But we are announcing another feature called wildcard listener in Ignite and this will unlock a key scenario which could be a blocker otherwise.

**Comment by yonzhan** [comment]
@surajmb We are pretty busy and fully occupied with Ignite features this month. Could we ship this feature in Mid of October?
