### ISSUE TITLE
'az storage table create' doesn't have an '--auth-mode' parameter, but mentions it in a warning

### ISSUE THREAD

**Issue by AleksandarTomicMs2** [Azure/azure-cli#15052]
## Describe the bug
When running `az storage table create` without an account key, connection string or sas token, the warning message you get is:
```
There is no credential provided in your command and environment, we will query account key for your storage account.
Please provide --connection-string, --account-key or --sas-token as credential, or use `--auth-mode login` if you have required RBAC roles in your command. For more information about RBAC roles in storage, you can see https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-cli.
Setting corresponding environment variable can avoid inputting credential in your command. Please use --help to get more information.
```
This command succeeds, as it uses the user's credentials. Unfortunately this command doesn't take have an `--auth-mode` parameter, so if you're using that authentication method you are stuck with this warning.

**Command Name**
`az storage queue create`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage queue create --name {} --account-name {}`

## Expected Behavior
Either the command should have an `--auth-mode` parameter, or there should be no warning for using RBAC.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.10.1 *

```

**Comment by yonzhan** [comment]
add to S176

**Comment by AleksandarTomicMs2** [comment]
The same seems to be true for `az storage account generate-sas` - you get a warning that you need to use `--auth-mode login` for RBAC, but it's not a parameter that `az storage account generate-sas` takes. Not sure if I should open a new issue for this or whether it can be addressed with this issue?
