### ISSUE TITLE
Dependency on non-existing version 0.4.1 of azure-multiapi-storage

### ISSUE THREAD

**Issue by bluca** [Azure/azure-cli#15051]
The following PR https://github.com/Azure/azure-cli/pull/14785 set a requirements on azure-multiapi-storage version 0.4.1, but no such tag exists - the newest available tag on https://github.com/Azure/azure-multiapi-storage-python/releases is 0.4.0

**Comment by yonzhan** [comment]
add to S176

**Comment by bluca** [comment]
@Juliehzl ping - I cannot upload the most recent version of azure-cli until azure-multiapi-storage is updated, or the dependency bump is reverted.

**Comment by Juliehzl** [comment]
Hi @bluca , 0.4.1 is already available now

**Comment by bluca** [comment]
Great, thank you!
