### ISSUE TITLE
host group creation FD Count 5 is not supported 

### ISSUE THREAD

**Issue by zivraf** [Azure/azure-cli#15054]
Host group creation with FDCount =5 is a supported scenario for zonla host group (created within an availability zone).

Note that for regional host groups, we do limit by the regional FD Count (either 2 or 3), but for zonal host groups (where the user has provided one or more AZ, we relax this limitation and support up to 5 FDs. It seems that the cli validation treats both scenarios the same block 5 FDs.

Please support our release by fixing this bug so that we will be able to test 5 FDs
 

PS C:\Users\zivr\OneDrive - Microsoft\LocalGit\AzureDedicatedHostsSamples\cli> az vm host group create -l $location --name zonalHGwith5FD -g $rg --platform-fault-domain-count 5 -z 1 --automatic-placement true

 

validation error: Parameter 'DedicatedHostGroup.platform_fault_domain_count' must be less than 3.

**Comment by fengzhou-msft** [comment]
@qwordy please take a look.

**Comment by qwordy** [comment]
The range is defined in swagger file. CLI relies on Python SDK. Python SDK verifies it.
azure-rest-api-specs\specification\compute\resource-manager\Microsoft.Compute\stable\2020-06-01\compute.json
```
    "DedicatedHostGroupProperties": {
      "properties": {
        "platformFaultDomainCount": {
          "type": "integer",
          "format": "int32",
          "minimum": 1,
          "maximum": 3,
          "description": "Number of fault domains that the host group can span."
        },
```
We need to relax the limitation in swagger.

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by amjads1** [comment]
Assigned to Ziv.

**Comment by yungezz** [comment]
[Swagger bug](https://github.com/Azure/azure-rest-api-specs/pull/10813) fixed, SDK released https://pypi.org/project/azure-mgmt-compute/13.1.1/ hi @qwordy could you pls pick up this work again? thanks.

**Comment by qwordy** [comment]
OK
