### ISSUE TITLE
[Network] Vnet-gateway update issues

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#1506]
1. The arguments for the two are very different. Python provides a generic way to specify objects but JS doesnt have this capability. As a result, in JS, there is no way to set BGP settings
2. Python doesnt have settings for SKU
3. Why does Python have address-prefixes param? It is not there in powershell. It is not needed
4. Both versions should have params for BGP and other settings. Just specifying an object is not enough

**Comment by tjprescott** [comment]
Issues with Xplat (Node) should be filed separately here: https://github.com/Azure/azure-xplat-cli

**Comment by tjprescott** [comment]
@aanandr 
By #2 do you mean that capacity is not exposed? Is there ever an instance where name and tier would not be the same?

IRT #3 address-prefixes is present, according to the help, because it is a prerequisite for uploading certificates. Is this not the case?

**Comment by tjprescott** [comment]
Our action items:
- [ ] Add BGP peering settings to create and update (just like with local-gateway)
- [ ] Add SKU capacity
- [ ] Add missing UltraPerformance SKU type
