### ISSUE TITLE
Better installation documentation for Linux

### ISSUE THREAD

**Issue by scott-doyland-burrows** [Azure/azure-cli#15069]
**Is your feature request related to a problem? Please describe.**
Installation documentation does not work for Linux Mint.

**Describe the solution you'd like**
Correct documentation to install on Linux Mint, or on all Debian versions of Linux.

**Describe alternatives you've considered**
Manually downloading the latest az .deb file from the MS website and installing.

**Additional context**
There are the following two commands in the documentation

AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
sudo tee /etc/apt/sources.list.d/azure-cli.list

The first command sets AZ_REPO to be "ulyana" which is the version of Linux Mint I am running.
In turn a file is created called /etc/apt/sources.list.d/azure-cli.list and it's contents are:

deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ ulyana main

This file is used by "apt" to know which distro to download the az cli for, however the distro is set (correctly) to "ulyana", but on the MS website, only Ubuntu distros are listed:

https://packages.microsoft.com/repos/azure-cli/dists/

Can you please add the Linux Mint distros (or all debian distros) or potentially make a "stable" folder and use "stable" in place of the distro name in the azure-cli/list file.

Or something else if you prefer - but either way, can proper installation and documentation be implemented for other debian linux versions.  It isn't really acceptable to just support Ubuntu especially when other debian versions will run the az cli without any issues.

Thank you .
Scott

**Comment by yungezz** [comment]
thanks for reporting. @fengzhou-msft could you pls have a look? thanks

**Comment by fengzhou-msft** [comment]
@scott-doyland-burrows the install script is updated to use the upstream distro package for Linux Mint. Please try again with `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`.

**Comment by scott-doyland-burrows** [comment]
@fengzhou-msft 

Thanks - that worked, it upgraded my "az cli" to the latest version.

Is there any reason that the azure cli cannot just be put into the normal Linux Mint repos.

It would be a far better customer experience for a customer to install Linux Mint (or any Debain distro) and then just do
```apt install azure-cli```
or whatever the customers preferred command is to install software, rather than having to use the curl command or add additional repos.

I am not sure why MS does not do this?

But thanks for making it a bit easier for the time being.

**Comment by fengzhou-msft** [comment]
We cannot control the release cycle if the package is put into the official distro repo, which is usually very long while Azure CLI updates frequently.

**Comment by scott-doyland-burrows** [comment]
Hi,

I probably misunderstand how it works, but whenever I check for updates and upgrade on Linux Mint
```
apt update
apt list upgradable
apt upgrade
```
There always seems to be new updates almost every day for different packages.
Why can't the az cli just be managed in this way?

**Comment by fengzhou-msft** [comment]
Some colleague is actually working on putting an azure-cli package in the Ubuntu Focal repository but the package was buggy (https://github.com/Azure/azure-cli/issues/14011) and according to him we cannot fix or take away the buggy package from Ubuntu Focal repository: 

> The way Linux distributions work is, especially LTS, that any issues are logged in the distribution issue tracker, together with any known workaround.
> If an issue does not have a security impact, or does not impede the correct functioning of the distribution as a whole, it is unlikely to be allowed to be fixed before the next release.

**Comment by scott-doyland-burrows** [comment]
OK - thanks for the infs.
