### ISSUE TITLE
Trying to publish functionapp via zip file fails with connection error

### ISSUE THREAD

**Issue by lrbuermann** [Azure/azure-cli#15066]
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
('Connection aborted.', OSError("(104, 'ECONNRESET')",))
Traceback (most recent call last):
site-packages/urllib3/contrib/pyopenssl.py, ln 331, in _send_until_done
    return self.connection.send(data)
python3.6/site-packages/OpenSSL/SSL.py, ln 1737, in send
    self._raise_ssl_error(self._ssl, result)
python3.6/site-packages/OpenSSL/SSL.py, ln 1639, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

...

python3.6/site-packages/requests/adapters.py, ln 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')",))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip -g {} -n {} --src {}`

## Environment Summary
```
Linux-5.4.0-45-generic-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.11.1

```

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by apawast** [comment]
@lrbuermann are you still experiencing this issue?

**Comment by navba-MSFT** [comment]
@lrbuermann Apologies for the late reply. Could you please let us know if you are still facing the issue ? This issue is open for quite sometime. Please let us know if you still need any assistance on this. Awaiting you reply.
