### ISSUE TITLE
azure-cli 2.11.1 - Cannot create keyvault

### ISSUE THREAD

**Issue by davidpoltorak** [Azure/azure-cli#15060]
## Describe the bug

az keyvault create command fails when executed and no keyvault is created

**Command Name**
`az keyvault create`

**Errors:**
```
'KeyVaultManagementClientConfiguration' object has no attribute 'http_logging_policy'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/mgmt/core/_pipeline_client.py, ln 50, in __init__
    kwargs["policies"] = self._default_policies(**kwargs)
azure/mgmt/core/_pipeline_client.py, ln 68, in _default_policies
    config.http_logging_policy or ARMHttpLoggingPolicy(**kwargs),
AttributeError: 'KeyVaultManagementClientConfiguration' object has no attribute 'http_logging_policy'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az keyvault create -g example_resourcegroup --name example_keyvault`

## Expected Behavior

Keyvault should be created without error

## Environment Summary
```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.7
Installer: PIP

azure-cli 2.11.1

Extensions:
azure-firewall 0.6.0

```

**Comment by fengzhou-msft** [comment]
@bim-msft please take a look.

**Comment by bim-msft** [comment]
@davidpoltorak Hi, please try `pip install azure-mgmt-keyvault==7.0.0b2`

**Comment by davidpoltorak** [comment]
Many thanks, and apologies for the delay in responding. I'm running a deployment later and will try this version. Thanks
