### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable 

### ISSUE THREAD

**Issue by aneee22** [Azure/azure-cli#15073]
## Describe the bug

**Command Name**
``

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yungezz** [comment]
hi @aneee22 could you pls share more detail about the command and error? thanks. cc @houk-ms .

**Comment by yungezz** [comment]
#14287

**Comment by aneee22** [comment]
Here is the complete errror!
$ az aks enable-addons -g terraform-rg -n terraform-ask -a kube-dashboard    
                                                                                                                                                                       
The command failed with an unexpected error. Here is the traceback:                                                                                                                                                                                                                                                                                     argument of type 'NoneType' is not iterable                                                                                                                                 Traceback (most recent call last):                                                                                                                                            File "/usr/lib/python3/dist-packages/knack/cli.py", line 206, in invoke                                                                                                       cmd_result = self.invocation.execute(args)                                                                                                                                File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 608, in execute                                                                               raise ex                                                                                                                                                                  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially                                                                    results.append(self._run_job(expanded_arg, cmd_copy))                                                                                                                     File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job                                                                              six.reraise(*sys.exc_info())                                                                                                                                              File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise                                                                                                            raise value                                                                                                                                                               File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job                                                                              result = cmd_copy(params)                                                                                                                                                 File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 306, in __call__                                                                              return self.handler(*args, **kwargs)                                                                                                                                      File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 493, in default_command_handler                                                                        return op(**command_args)                                                                                                                                                 File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acs/custom.py", line 1846, in aks_enable_addons                                                                _ensure_container_insights_for_monitoring(cmd, instance.addon_profiles['omsagent'])                                                                                       File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acs/custom.py", line 2496, in _ensure_container_insights_for_monitoring                                        if 'loganalyticsworkspaceresourceid' in addon.config:                                                                                                                   TypeError: argument of type 'NoneType' is not iterable

**Comment by navba-MSFT** [comment]
@aneee22 Apologies for the late reply. This issue seems to be addressed #14335. Could you please let us know if you are still facing this issue ? Also note Kubernetes Dashboard addon is deprecated for Kubernetes version >= 1.19.0. This github issue is open for quite sometime now. Please let me know if you need any further assistance on this issue.

**Comment by navba-MSFT** [comment]
@aneee22 This is a follow-up to check if you had a chance to look at my above comment. This issue is open for quite sometime. Please let us know if you need any further assistance on this.

**Comment by navba-MSFT** [comment]
@aneee22 We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
