### ISSUE TITLE
Incorrect description of 'apply-network-updates'

### ISSUE THREAD

**Issue by LukasNespor** [Azure/azure-cli#15078]
Command **apply-network-updates** has incorrect description. It says that it is used for backing up the API Management service to storage account. There is no switch used for specifying storage account. And according to the name this command do something else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 197d8382-ee16-6001-4941-768877379c0d
* Version Independent ID: 1423fa76-977f-ad88-8129-0b52a38e68e6
* Content: [az apim](https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest#az-apim-apply-network-updates)
* Content Source: [src/azure-cli/azure/cli/command_modules/apim/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/apim/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
apim

**Comment by RakeshMohanMSFT** [comment]
@LukasNespor This is fixed
