### ISSUE TITLE
Webapp:SSH to app service is not supported in Windows

### ISSUE THREAD

**Issue by Flanker32** [Azure/azure-cli#15072]
**Describe the bug**

`az webapp ssh` didn't work in Windows, will report `webapp ssh is only supported on linux and mac`, but this feature could work with VSCode App Service Extension, only Linux App Service is not supported

**To Reproduce**

run `az webapp ssh` to an Linux web app in terminal

**Expected behavior**

Connect to app service ssh endpoint

**Environment summary**

- Install Method: MSI
- CLI version:
    ```
    azure-cli                         2.11.1
    core                              2.11.1
    telemetry                          1.0.5 *

    Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
    Extensions directory 'C:\Users\hanli\.azure\cliextensions'

    Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

    Legal docs and information: aka.ms/AzureCliLegal
    ```
- OS : Windows 10 2004
- Shell: Powershell

**Comment by yonzhan** [comment]
webapp

**Comment by mloskot** [comment]
IMHO, the error message is unclear, see https://github.com/Azure/azure-cli/issues/12940#issuecomment-737152145

**Comment by btardif** [comment]
This is being tracked here: #16125
