### ISSUE TITLE
Cannot enable identity for a web app

### ISSUE THREAD

**Issue by gsscoder** [Azure/azure-cli#15087]
## Describe the bug

**Command Name**
`az functionapp identity assign`

**Errors:**
```
'NoneType' object has no attribute 'identity'
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-mtleih48\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 711, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-qqxn1krb\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
pip-unpacked-wheel-a_t_wugh\azure\cli\core\__init__.py, ln 782, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 768, in assign_identity
azure\cli\core\commands\arm.py, ln 1057, in assign_identity
azure\cli\command_modules\appservice\custom.py, ln 741, in setter
AttributeError: 'NoneType' object has no attribute 'identity'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp identity assign --subscription {} --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.11.1

```

**Comment by yonzhan** [comment]
functionapp

**Comment by apawast** [comment]
@panchagnula could you please take a look at this?

**Comment by panchagnula** [comment]
@apawast is this specific to functionapp? I also recommend to update to the latest update since functionapp identity was recently updated during this release https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#appservice

**Comment by RakeshMohanMSFT** [comment]
This is working. Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
