### ISSUE TITLE
Can't call cli admin-consent

### ISSUE THREAD

**Issue by AdamWhite** [Azure/azure-cli#15085]
## Describe the bug

following the guide: https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest#code-try-3 
I get the following errors, I am signed in as the admin and can click in the portal to provide admin consent however via the CLI :(

**Command Name**
`az ad app permission admin-consent`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 709, in _run_job
    cmd_copy.exception_handler(ex)
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad app permission admin-consent --id {}`

## Environment Summary
```
Linux-4.15.0-1093-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.11.1

Extensions:
ai-examples 0.2.3

```

**Comment by yonzhan** [comment]
add to S176

**Comment by jiasli** [comment]
`az ad app permission admin-consent` doesn't work in Cloud Shell, because `main.iam.ad.ext.azure.com` is an not an endpoint supported by Cloud Shell. 

Please see https://github.com/Azure/azure-cli/issues/12137#issuecomment-596567479 for detailed explanation and workarounds.
