### ISSUE TITLE
Az CLI shell

### ISSUE THREAD

**Issue by samuel-velazquez** [Azure/azure-cli#15093]
## Describe the bug

**Command Name**
`Unknown`

**Errors:**
```
az: '&&[smd]' is not in the 'az' command group. See 'az --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview

'NoneType' object has no attribute 'in_tree'
Traceback (most recent call last):
pip-install-363drsgw\knack\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 654, in execute
cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
cli\core\commands\__init__.py, ln 711, in _run_job
Temp\pip-install-363drsgw\six\six.py, ln 703, in reraise
...
interactive\azext_interactive\azclishell\app.py, ln 600, in handle_scoping_input
    if self.completer.command_tree.in_tree(tree_path):
AttributeError: 'NoneType' object has no attribute 'in_tree'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az &&[smd]`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.8.0 *

Extensions:
deploy-to-azure 0.2.0
dev-spaces 1.0.5
interactive 0.4.4

```

**Comment by samuel-velazquez** [comment]
Shell is account language so graph if version lastest someone process and extension

**Comment by jiasli** [comment]
Sorry I don't understand your statement:

> Shell is account language so graph if version lastest someone process and extension

Could you let us know 
1. What you are trying to do?
2. How you are doing that, with what commands?

Thanks for the information.

**Comment by samuel-velazquez** [comment]
firsts not single to download async

**Comment by jiasli** [comment]
> firsts not single to download async

Sorry I can't understand your comment. Could you provide some more details?

**Comment by samuel-velazquez** [comment]
Resource to get (|pragna) alone is status function or project asset [have to remote; draft]

**Comment by jiasli** [comment]
The author seems to be a bot and also created https://github.com/git-lfs/git-lfs/issues/4212 before. Closing.
