### ISSUE TITLE
--vnet-to-vnet-traffic unrecognized argument (azure cli extension virtual-wan 0.2.1)

### ISSUE THREAD

**Issue by stephgou** [Azure/azure-cli#15094]
**Describe the bug**

I am using virtual-wan 0.2.1 az-cli extension on Windows with the following command:
az network vwan create --name $wanName1 --resource-group $resourceGroupName --type Standard `
                    --location $location1 --branch-to-branch-traffic **--vnet-to-vnet-traffic** 

**--vnet-to-vnet-traffic** [documented here: https://docs.microsoft.com/en-us/cli/azure/ext/virtual-wan/network/vwan?view=azure-cli-latest#ext-virtual-wan-az-network-vwan-create] appears as an unrecognized argument.

**To Reproduce**

az network vwan create --name $wanName1 --resource-group $resourceGroupName --type Standard `
                    --location $location1 --branch-to-branch-traffic **--vnet-to-vnet-traffic** 
**Expected behavior**

**Environment summary**
  "azure-cli": "2.5.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.5.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4"
  
**Extension summary**
    "aks-preview": "0.4.45",
    "azure-devops": "1.25.8",
    "azure-firewall": "0.6.0",
    "dev-spaces": "1.0.5",
    "virtual-wan": "0.2.1"

**Comment by yonzhan** [comment]
add to S176

**Comment by jsntcy** [comment]
@stephgou, --vnet-to-vnet-traffic is deprecated in 0.2.1 https://github.com/Azure/azure-cli-extensions/pull/2237 which is a breaking change from service side.
See release note: https://github.com/Azure/azure-cli-extensions/blob/master/src/virtual-wan/HISTORY.rst#021
