### ISSUE TITLE
Rerun failed test in new disks API version 2020-06-30

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#15097]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I am updating API version of disks. https://github.com/Azure/azure-cli/pull/15031
I can't pass these tests. Can you help run them after this PR is merged? Thank you!

network:
test_network_virtual_appliance

servicefabric:
test_cluster_certs

acs:
test_k8s_install_kubelogin_emit_warnings
test_k8s_install_kubelogin_create_installation_dir

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by qwordy** [comment]
@andyzhangx

**Comment by mwesigwaguma** [comment]
test has been removed, related to command `az sf cluster certificate add` which was removed by team
