### ISSUE TITLE
[Attestation] GA Support

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#15100]
**Resource Provider**

MMA(Attestation)

**Description of Feature or Work Requested**

MAA GA date is moved to Oct  30, 2020. We are expected to provide consistent experience across PowerShell, Portal, CLI and Terraform for GA. 

Swagger completeness is expected by 9/15. 
**Minimum API Version Required**

**Swagger Link**

TBD.

**Target Date**

**Comment by yungezz** [comment]
To track Attestation GA work

**Comment by bim-msft** [comment]
Message from the service team: "Our GA changes of swagger are expected to be checked in by Oct 2nd"

**Comment by yungezz** [comment]
Service team postponed GA date again, move later
