### ISSUE TITLE
'az functionapp list' errors out

### ISSUE THREAD

**Issue by zkatsavelis** [Azure/azure-cli#15105]
## Describe the bug

**Command Name**
`az functionapp list` or `az functionapp show --name xxx`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp list`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
functionapp

**Comment by yungezz** [comment]
duplicate with https://github.com/Azure/azure-cli/issues/14800.
did you install azure-cli via pip? If yes, it might caused by situation in #13343 (comment). Could you pls install decorator? Recommended way to install azure cli is there: #14011

**Comment by zkatsavelis** [comment]
Originally was installed by apt but looks like that this version is unsupported?

anyway I have reinstall it from https://aka.ms/InstallAzureCLIDeb and looks ok now
