### ISSUE TITLE
`az storage logging update` fails without optional argument

### ISSUE THREAD

**Issue by ChandlerSwift** [Azure/azure-cli#15111]
## Describe the bug

**Command Name**
`az storage logging update`

**Errors:**
```
incorrect usage: for table service, the supported version for logging is `1.0`. For more information, please refer to https://docs.microsoft.com/en-us/rest/api/storageservices/storage-analytics-log-format.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage logging update --retention 30 --services t --log r --connection-string [...]`

## Expected Behavior
According to the docs, the version argument is optional:
```
$ az storage logging update --help
[...]
Arguments
[...]
    --version              : Version of the logging schema.
```

However, https://github.com/Azure/azure-cli/pull/13962 introduced a check that fails if the version is not explicitly set to 1.0. This isn't necessary, as the version defaults to 1.0. For debugging, I've simply been commenting out the `raise` statement, which works fine---the version defaults to 1.0, the check doesn't stop us, and it succeeds. (At the time of check, namespace.version is `None`.) Also, if I explicitly add `--version 1.0`, the command succeeds. 

Two potential fixes:
```
1322c1322
<     if validate_service_type(namespace.services, 'table') and namespace.version != 1.0:
---
>     if validate_service_type(namespace.services, 'table') and namespace.version and namespace.version != 1.0:
```
or explicitly require `--version` to be set when `--services=table` (affecting both docs and validation).

I'd be happy to open a PR for either of these, if you think one is the right fix.

## Environment Summary
```
Linux-5.8.7-arch1-1-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9
Installer: PIP

azure-cli 2.11.1

Extensions:
azure-devops 0.18.0
interactive 0.4.3

```

**Comment by yonzhan** [comment]
add to S176

**Comment by Juliehzl** [comment]
Hi @ChandlerSwift, thanks for your feedback. It is fixed in https://github.com/Azure/azure-cli/pull/15474 and official release will be available on 10/27.
To avoid the issue, you could specify `--version 1.0` in your command as workaround.
