### ISSUE TITLE
Az cli fails with pod identities

### ISSUE THREAD

**Issue by Maqsoodp** [Azure/azure-cli#15113]
## Describe the bug
Az cli is installed and pod identity is set on a container. Getting below error.

**Command Name**
`az storage blob list`

**Errors:**
```
get_token() takes 1 positional argument but 2 were given
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 709, in _run_job
    cmd_copy.exception_handler(ex)
...
    _await_result(self._policy.on_request, request)
azure/core/pipeline/_tools.py, ln 29, in await_result
    result = func(*args, **kwargs)
core/pipeline/policies/_authentication.py, ln 93, in on_request
    self._token = self._credential.get_token(*self._scopes)
TypeError: get_token() takes 1 positional argument but 2 were given
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login --identity --allow-no-subscriptions`
- `az storage blob list --account-name xxxxxxxx --auth-mode login --container yyyyyyyy`

## Environment Summary
```
Linux-4.15.0-1089-azure-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.11.1

```

**Comment by fengzhou-msft** [comment]
@Juliehzl please take a look.

**Comment by code-to-joy** [comment]
I'm getting an identical stack and error when running "query" in the "costmanagement" extension. (Yes I know it's not supported)

**Comment by Juliehzl** [comment]
fixed on https://github.com/Azure/azure-cli/pull/15118
please try with edge build https://github.com/Azure/azure-cli#edge-builds now and official release will be available on 9/22
