### ISSUE TITLE
CLI and app

### ISSUE THREAD

**Issue by samuel-velazquez** [Azure/azure-cli#15116]
## Describe the bug

**Command Name**
`az find`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az find {}`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.8.0 *

Extensions:
deploy-to-azure 0.2.0
dev-spaces 1.0.5
interactive 0.4.4

```

**Comment by yungezz** [comment]
hi @samuel-velazquez could you pls share detail of the issue you met to  help trouble shooting?

**Comment by samuel-velazquez** [comment]
be trouble ad in shold  attribute lastst call disk top remote asset check

**Comment by yonzhan** [comment]
This issue was trigger by a bot.
