### ISSUE TITLE
az vm capture - needs option for downloading template

### ISSUE THREAD

**Issue by cynthn** [Azure/azure-cli#1512]
The old version of the CLI had a -t switch for downloading the template locally. This is really useful when you are quickly trying to capture and redeploy VMs. Without it, you need to query on the files in storage to get the URI for the template to use it to create a new VM.

**Comment by yugangw-msft** [comment]
@cynthn, CLI 2.0 usually doesn't provide the option to save file, rather we encourage users to use OS built-in piping. So for the capture, you can use `>` to write to any file you like. `az vm capture -g mygroup -n myvm >deployTemplate.json`

**Comment by cynthn** [comment]
The thing is that the .json that gets outputted isn't as easy to use as it was in CLI 1.0. I could take the .json output and turn around and create a VM. You have to edit the .json output from 2.0 to include all of the required information for creating a new VM. You don't get prompts for VM name etc.

**Comment by yugangw-msft** [comment]
@cynthn, so you mean the template generated by 2.0 is difference from 1.0? 
Regarding prompt for parameters, that is a known thing,  which we can track separately

**Comment by cynthn** [comment]
The difference is the prompt for parameters. So, if that needs to be tracked separately, that works.

**Comment by yugangw-msft** [comment]
Opened #1778
