### ISSUE TITLE
Add GalleryImageDefinitionFeature to the SIG image definition object

### ISSUE THREAD

**Issue by grace-liang** [Azure/azure-cli#15138]
**Resource Provider**

Azure.Compute

**Description of Feature or Work Requested**

Add an array of GalleryImageFeature objects named "features" under the image definition object in Shared Image Gallery. The array is not updatable after creation. 

Image definition CLI docs: https://docs.microsoft.com/en-us/cli/azure/sig/image-definition?view=azure-cli-latest

Example usage: 
`az sig image-definition create --features IsSecureBootSupported=true IsMeasuredBootSupported=false`

The implementation should be able to handle arbitrary feature names and values as input on the create call- we have validation on the service side to allow/disallow specific feature names and feature values.

Please note- to begin with, this is meant to be a limited release to specific customers and we are not yet in public preview. The feature names are not locked and are subject to change. We want to allow specific customers to use it, but with known feature names and values provided by the service. CLI docs should not provide info as to what acceptable feature names are. 

**Minimum API Version Required**

2020-09-30

**Swagger Link**

Search for "features"
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/preview/2020-09-30/gallery.json

**Target Date**

October 15

**Comment by fengzhou-msft** [comment]
@qwordy please take a look.

**Comment by qwordy** [comment]
Asking SDK team for SDK release.

**Comment by qwordy** [comment]
@grace-liang There is an error. Can you help? Does the subscription need to be added to allowed list? Thanks.
Request body:
```
{"location": "westus", "tags": {}, "properties": {"osType": "Linux", "osState": "Generalized", "hyperVGeneration": "V1", "features": [{"name": "IsSecureBootSupported", "value": "true"}, {"name": "IsMeasuredBootSupported", "value": "false"}], "identifier": {"publisher": "publisher1", "offer": "offer1", "sku": "sku1"}, "disallowed": {}}}
```
Error:
```
{
  "error": {
    "code": "BadRequest",
    "message": "Could not find member 'features' on object of type 'GalleryImageProperties'. Path 'properties.features', line 1, position 132.",
    "target": "galleryImage.properties.features"
  }
}
```

**Comment by grace-liang** [comment]
Added that subscription, please retry. Thanks @qwordy!

**Comment by qwordy** [comment]
> 
> 
> Added that subscription, please retry. Thanks @qwordy!

Thanks. I tried last Friday and it didn't work. It works this Monday. It seems there is a notable delay between it takes effect.
