### ISSUE TITLE
To create AppGW v1 without Public IP is failed by Azure CLI 2.11.1.

### ISSUE THREAD

**Issue by hisasima** [Azure/azure-cli#15130]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Issue: Behavior of Azure CLI was changed from version 2.11.1.  I can not create AppGW v1 without Public IP when I used Azure CLI 2.11.1.

**To Reproduce**
command (To repro)

```Shell
~$ az -v
azure-cli                         2.11.1

$ az network application-gateway create --resource-group Newinternal --name test2 --location japaneast --sku Standard_Medium  --private-ip-address 10.0.0.100 --http2 Disabled --vnet-name AG-VNet1 --subnet AG-Sub

Azure Error: InvalidTemplateDeployment
Message: The template deployment 'ag_deploy_r6dBx2lSWKesOzTbbkR2BJTkZE5wv2SP' is not valid according to the validation procedure. The tracking id is 'c51ffc21-0df3-4cf0-88d6-2d02eedf698f'. See inner errors for details.
Exception Details:
        Error Code: InvalidResourceReference
        Message: Resource /subscriptions/66bef1e6-a2cb-4f94-a009-eaacf5ae1be3/resourceGroups/NewInternal/providers/Microsoft.Network/applicationGateways/test1/frontendIPConfigurations/appGatewayFrontendIP referenced by resource /subscriptions/66bef1e6-a2cb-4f94-a009-eaacf5ae1be3/resourceGroups/Newinternal/providers/Microsoft.Network/applicationGateways/test1/httpListeners/appGatewayHttpListener was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.
Azure Error: InvalidResourceReference
Message: Resource /subscriptions/66bef1e6-a2cb-4f94-a009-eaacf5ae1be3/resourceGroups/NewInternal/providers/Microsoft.Network/applicationGateways/test1/frontendIPConfigurations/appGatewayFrontendIP referenced by resource /subscriptions/66bef1e6-a2cb-4f94-a009-eaacf5ae1be3/resourceGroups/Newinternal/providers/Microsoft.Network/applicationGateways/test1/httpListeners/appGatewayHttpListener was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.
```

**Expected behavior**
When I used 2.10.1, the issue was not reproduced. I also confirmed that I created AppGW with Public IP using version 2.10.1.
 
az network application-gateway create --resource-group Newinternal --name test2 --location japaneast --sku Standard_Medium  --private-ip-address 10.0.0.100 **--public-ip-address pupapgw2**  --http2 Disabled --vnet-name AG-VNet1 --subnet AG-Sub
 
I think this behavior is related to below change.
 

https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&tabs=azure-cli#network

Network
	
[BREAKING CHANGE] Allow to create both public and private IP while creating an Application Gateway

 
We can create AppGW v1 without publicip by portal so we should create AppGW v1 without public ip by Azure CLI. 

**Environment summary**
Application Gateway V1 SKU Medium
Japan East
**Additional context**

**Comment by yonzhan** [comment]
add to S176

**Comment by haroldrandom** [comment]
@hisasima The issue is awared, we will fix it ASAP
