### ISSUE TITLE
`az network private-link-resource list` - arguments documented as optional are not optional

### ISSUE THREAD

**Issue by glennmusa** [Azure/azure-cli#15135]
**Describe the bug**

All of the arguments on the `az network private-link-resource list` command are documented as optional. But the command requires a certain combination of arguments.

**To Reproduce**

When you run:

`az network private-link-resource list --type Microsoft.CognitiveServices/accounts`

You get: 

`usage error: --id / -g -n --type`

**Expected behavior**

An accurate description of the required arguments in documentation and `--help`.

**Environment summary**
azure-cli version 2.11.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae400cf1-3b18-08af-d8c5-ed2b23184ed2
* Version Independent ID: 9803d7a9-cf98-be6d-4b10-a228d0fa2fc2
* Content: [az network private-link-resource](https://docs.microsoft.com/en-us/cli/azure/network/private-link-resource?view=azure-cli-latest#az-network-private-link-resource-list)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S176
