### ISSUE TITLE
'az servicebus queue update' updates some properties not included in the command, leaves others unchanged

### ISSUE THREAD

**Issue by cscoon** [Azure/azure-cli#15132]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
'az servicebus queue update' includes several optional parameters that will update a property on a service bus queue.  When a parameter is not included in the command, the behavior is inconsistent.  Some properties will remain unchanged, and others will be changed to a default or non-default value.

So if you only want to update the lock duration, for example, executing 'az servicebus queue update' with the --lock-duration parameter will result in some other properties being changed, making it difficult to be prescriptive about which properties you want to change.

**To Reproduce**

1. Create a service bus queue in the Azure portal.  Accept the defaults with the exception of 'Enable partitioning' which should be enabled.
2. Execute '& az servicebus queue update --subscription <yourSubscriptionId> --resource-group <yourResourceGroup> --namespace-name <yourNamespace> --name <yourQueue> --lock-duration 0:05:00'
3. Examine the queue in the portal.  Some properties that were not involved in the update are unchanged, which seems logical and the expected behavior.  Examples include 'Enable partitioning' which is left at it's original value of enabled.  Other properties, however, are changed even though they weren't involved in the update.  An example is Max Size, which is changed to 5 GB, and Message Time to Live which is changed as well.

**Expected behavior**
The expected behavior is that only the properties involved in the update are changed, and the rest of the properties remain at the value they had before the update.

**Environment summary**
Azure CLI 2.11.1
PowerShell Core 7.0.3
Windows 10

**Additional context**

**Comment by yonzhan** [comment]
servicebus

**Comment by Saglodha** [comment]
Hi @cscoon, thank you for bringing this to our attention.

We would triage internally and keep you posted.

**Comment by Saglodha** [comment]
@cscoon , this behavior is fixed in our latest release. Please review and let us know. Thanks!
