### ISSUE TITLE
`az network private-endpoint create` - "group Id" is not an optional argument

### ISSUE THREAD

**Issue by glennmusa** [Azure/azure-cli#15136]
**Describe the bug**

When creating a private endpoint, the target resource's group Id is listed as optional, but it is required.

**To Reproduce**

When you run:

```
az network private-endpoint create --name {peName} --resource-group {rgName} --vnet-name {vnetName} --subnet {subnetName} --private-connection-resource-id {peResourceId} --connection-name {peConnectionName}
```

You get back:

```
MissingParameterOnPrivateLinkServiceConnection - Private link service connection /subscriptions/{subId}/resourceGroups/{rgName}/providers/Microsoft.Network/privateEndpoints/{resourceName}/privateLinkServiceConnections/{peName} is missing required parameter 'group Id'.
```

**Expected behavior**

An accurate description of the required arguments in documentation and `--help`.

**Environment summary**
azure-cli version 2.11.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8911e94f-9496-a68d-50c0-b5d536a375a4
* Version Independent ID: cc37b77b-0fa2-991b-e16b-fcdbbf183853
* Content: [az network private-endpoint](https://docs.microsoft.com/en-us/cli/azure/network/private-endpoint?view=azure-cli-latest#az-network-private-endpoint-create)
* Content Source: [src/azure-cli/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S176

**Comment by haroldrandom** [comment]
It is optional. One of the supported resources, PrivateLinkResource is required not to provide this, so we leave it optional. But the other resources are required
