### ISSUE TITLE
[Keyvault] using absolute path instead of relative path when importing

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#15144]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Keyvault.

Today in code it's relative path instead of absolute path when importing, this will cause issue when pacakge changes to Pyinstaller. 

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yungezz** [comment]
cc @arrownj , this will be a cross-commands effort not only for keyvault. @arrownj  pls help to define a plan to drive it. thanks.

**Comment by jiasli** [comment]
FYI, [PEP 8](https://www.python.org/dev/peps/pep-0008/#imports) states:

> Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured (such as when a directory inside a package ends up on sys.path)
