### ISSUE TITLE
Provide simple instructions for getting development started

### ISSUE THREAD

**Issue by brettcannon** [Azure/azure-cli#1514]
Could be as simple as:
1. Create a venv
2. Activate the venv
3. `python scripts/dev_setup.py`
4. `testall`/`testall.bat`

**Comment by tjprescott** [comment]
That's what this is: https://github.com/Azure/azure-cli/blob/master/doc/configuring_your_machine.md

**Comment by brettcannon** [comment]
Oh, great! Didn't find that while I was poking around. Is it linked to in a more prominent location in the project that I overlooked?

**Comment by tjprescott** [comment]
I don't think so because we assume most people will install it to use rather than develop for it. But we can add it to the main README

**Comment by brettcannon** [comment]
Or maybe CONTRIBUTING.md? That way it's still in a top-level file that people who want to contribute can find but it doesn't muck with the README for most users who will just want to use the CLI?

**Comment by tjprescott** [comment]
Actually we have an issue for this #889.

**Comment by brettcannon** [comment]
Darn, my search didn't find it (sorry about that). I'll close this in favour of the other issue.
