### ISSUE TITLE
Azure CLI error updating servicebus queue seems wrong

### ISSUE THREAD

**Issue by andreacassioli** [Azure/azure-cli#15142]
## Describe the bug

**Command Name**
`az servicebus queue update`

**Errors:**
```
BadRequest - SubCode=40000. The property value for 'DefaultMessageTimeToLive' must be between 00:00:01 and 14.00:00:00 when the namespace '{}' is using 'Basic' tier.
Parameter name: DefaultMessageTimeToLive. TrackingId:191e9094-003d-4682-8778-de5fd74e5ea9_M3CH3_M3CH3_G5, SystemTracker:{}.servicebus.windows.net:{}, Timestamp:2020-09-13T18:45:04 CorrelationId: 911bec62-cdd2-47c0-90fe-d4504a4d6b6c
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az servicebus queue update --namespace-name {} -n {} -g {} --lock-duration {}`

## Expected Behavior
The lock duration is set to a new value

## Environment Summary
```
macOS-10.15.6-x86_64-i386-64bit
Python 3.8.5
Installer: HOMEBREW

azure-cli 2.11.1 (same behaviour with 2.10.1)

```
## Additional Context

* This issue might relate to https://github.com/Azure/azure-cli/issues/15132
* According to https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-resource-manager-exceptions the lock duration is a property that I should be able to change

**Comment by yonzhan** [comment]
servicebus

**Comment by yungezz** [comment]
cc @houk-ms

**Comment by v-Ajnava** [comment]
fixed, please use the latest CLI release
