### ISSUE TITLE
Creating PoshBot Powershell-Based Azure function.

### ISSUE THREAD

**Issue by Phenix51** [Azure/azure-cli#15141]
I'm following the guide from LAzy Admin "SETTING UP POSHBOT FOR MICROSOFT TEAMS"
https://www.thelazyadministrator.com/2019/08/19/chatops-setting-up-poshbot-for-microsoft-teams/

The guide does state that we may no longer need to worry about using v1 functions in the future, but I am not certain if this is the reason for this error. 

## Describe the bug

**Command Name**
`az functionapp config appsettings set`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp config appsettings set --resource-group {} --name {} --settings {}`

## Environment Summary
```
Linux-4.15.0-1095-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.11.1

Extensions:
ai-examples 0.2.3

```

**Comment by yonzhan** [comment]
functionapp

**Comment by yungezz** [comment]
hi @Phenix51 could you pls run `az login` to workaround the issue? This is a known cloud shell issue #11749 .  Add Cloud Shell label to route to appropriate team.

**Comment by Phenix51** [comment]
Thanks for your responses, I found updated information from another source that showed that I needed to be in function v3. I was abole to push forward with this project.
