### ISSUE TITLE
Azure CLI from Azure functions

### ISSUE THREAD

**Issue by librucha** [Azure/azure-cli#15154]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I need use `az` commands from azure function because some Powershell comamnds doesn't work.

**To Reproduce**
Create azure function with `az -h` command or else az command

**Expected behavior**
show help for az cli
**Environment summary**
Azure functions on runtime 2.0.14248.0

**Comment by yonzhan** [comment]
functionapp

**Comment by apawast** [comment]
@librucha when you say some Powershell commands don't work, are you using the az module in the Powershell function?

**Comment by juloora** [comment]
I created a Azure powershell function by using terraform but I facing problem run azure cli from my function please explain detailed information about this

**Comment by librucha** [comment]
It is too old bug.
