### ISSUE TITLE
`az acs create --orchestrator=kubernetes ...` should implicitly perform `get-credentials` afterward

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1517]
This can be assigned to me.

**Comment by brendandburns** [comment]
@colemickens are you working on this? if not I'll take it...

**Comment by colemickens** [comment]
I had meant to send it over the weekend but it fell by the wayside, feel free to take it from me.

**Comment by mboersma** [comment]
We don't plan to implement this change for `az acs`. @tjprescott this issue can be closed.
