### ISSUE TITLE
--diskId deprecated

### ISSUE THREAD

**Issue by nkorojoseph** [Azure/azure-cli#15178]
[Enter feedback shere]
--disk deprecated error while trying to attach a disk. 
--name worked fine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbc06453-93e1-e616-9649-c1487c605a65
* Version Independent ID: 76d52328-613f-bd5f-7daf-f62841300e2b
* Content: [az vm disk](https://docs.microsoft.com/en-us/cli/azure/vm/disk?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm/disk.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/vm/disk.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy could you pls help to check if the deprecation from service side or from client side? thanks.

**Comment by qwordy** [comment]
Can you describe it with more details? The information is not complete.

**Comment by qwordy** [comment]
@nkorojoseph hello, any update?

**Comment by qwordy** [comment]
Close it since the description is not clear.
