### ISSUE TITLE
{Core} AdalAuthentication doesn't honor `scopes` for Track 2 SDK

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#15179]
**Describe the bug**

In Track 2 SDK, `scopes` (`resource`) is managed by SDK, instead of Azure CLI. For example, in [`AzureAppConfigurationClient`](https://github.com/Azure/azure-sdk-for-python/blob/022bc80f2bc645d8d82d647620376fcea2229522/sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py#L128):

```py
if aad_mode:
    scope = base_url.strip("/") + "/.default"
```

But in `get_token`, `scopes` is not honored (discarded), resulting in getting a token for a wrong `scopes` (ARM `https://management.core.windows.net/` by default):

https://github.com/Azure/azure-cli/blob/c2b9a2c5cfe34b108b52b49ac50c6802ac4d729f/src/azure-cli-core/azure/cli/core/adal_authentication.py#L61-L67

**Comment by yonzhan** [comment]
Core
