### ISSUE TITLE
Unable to deploy Linux Function App

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-cli#15172]
Cannot deploy a function app using the az CLI (command: az functionapp deployment source config-zip  -g test  -n mahoeger-linux --src ./helloworld.zip).

The deployment fails with 2.7.0 and 2.11.1, but is ok with 2.0.77. I am running on a Mac, using az CLI 2.11.1 and deploying to Linux Consumption function apps that are already deployed (both v2 and v3 sites).

```
mariehoeger$az functionapp deployment source config-zip  -g test  -n mahoeger-linux --src ./helloworld.zip
Unknown error============================== 100.0% ..
```

**Comment by yonzhan** [comment]
functionapp
