### ISSUE TITLE
Option to use managed storage account with boot diagnostics

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-cli#15189]
It seems it is possible to use managed storage account with boot diagnostics from the portal now:

![image](https://user-images.githubusercontent.com/106444/93409420-d1cdcc00-f8d1-11ea-8257-8ce559e44547.png)

However I cannot find the corresponding option with the latest version of azure-cli (version 2.11.1).

Please let us know when this option will be available.

**Comment by yungezz** [comment]
hi @qwordy could you pls share release plan and how to do it in new release? thanks.

**Comment by qwordy** [comment]
This feature will be released on 9/22.
Omit `--storage` to use managed storage.
```
vm boot-diagnostics enable -g rg -n vm
```
PR: https://github.com/Azure/azure-cli/pull/15145
