### ISSUE TITLE
Hang forever in Powershell ISE

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#15183]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

A customer runs `az vm create -g rg -n vm1 --image Win2016DataCenter --admin-username azurename` in Powershell ISE and he can never get a prompt to input password. It hangs forever. I reproduce this bug in my machine.

Correct result:
![image](https://user-images.githubusercontent.com/5019528/93304388-882ca500-f82f-11ea-9702-5ebbdaa040c0.png)

I read the code. It calls `prompt_pass` in knack.

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Hang forever

**Comment by jiasli** [comment]
This is an issue with [`msvcrt`](https://docs.python.org/3.8/library/msvcrt.html) and Windows PowerShell ISE. 

Knack uses `getpass.getpass`:

https://github.com/microsoft/knack/blob/cf628bf3930c622f16d6eb31b275f0ec81ca4174/knack/prompting.py#L60

```py
password = getpass.getpass(msg)
```

And `getpass.getpass` uses `msvcrt.getwch`:

https://github.com/python/cpython/blob/929112ef81ccef20d3aef25c8a1142059ee941da/Lib/getpass.py#L103

```
c = msvcrt.getwch()
```

This issue can be reproduced with a simple demo:

```py
import getpass

password = getpass.getpass("Input password:")
print(password)
```

or 

```py
import msvcrt

pw = ""
while 1:
    c = msvcrt.getwch()
    if c == '\r' or c == '\n':
        break
    if c == '\003':
        raise KeyboardInterrupt
    if c == '\b':
        pw = pw[:-1]
    else:
        pw = pw + c

print(pw)
```

Run the script with

```
python D:\py\testproj\hello.py
```

Windows PowerShell ISE will hang:

![image](https://user-images.githubusercontent.com/4003950/93308860-68987b00-f835-11ea-8248-917d776a2a53.png)

Windows PowerShell ISE is now [deprecated](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/ise/introducing-the-windows-powershell-ise?view=powershell-7#support), please use [VSCode PowerShell extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell) instead, which works fine with `msvcrt`.

**Comment by jiasli** [comment]
Reproduced directly by calling [`_getwch`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getch-getwch?view=vs-2019):

```cpp
// crt_getch.c
// compile with: /c
// This program reads characters from
// the keyboard until it receives a 'Y' or 'y'.

#include <conio.h>
#include <ctype.h>

int main(void)
{
    int ch;

    _cputs("Type 'Y' when finished typing keys: ");
    do
    {
        ch = _getch();
        ch = toupper(ch);
    } while (ch != 'Y');

    _putch(ch);
    _putch('\r');    // Carriage return
    _putch('\n');    // Line feed
}
```

![image](https://user-images.githubusercontent.com/4003950/93313680-5c172100-f83b-11ea-8eba-9c9d213856d3.png)

**Comment by qwordy** [comment]
Open an issue in PowerShell repository.
