### ISSUE TITLE
Az APIM backup fails

### ISSUE THREAD

**Issue by enema17484** [Azure/azure-cli#15186]
## Describe the bug

**Command Name**
`az apim backup`

**Errors:**
```
AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.

Trace ID: ba111091-1440-4668-a349-e618fea24f00

Correlation ID: 5718ed4c-5055-4ae2-a739-8b56300aac9d

Timestamp: 2020-09-16 09:39:46Z
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim backup --backup-name {} --name {} --resource-group {} --storage-account-container {} --storage-account-key {} --storage-account-name {} --subscription {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.11.1

Extensions:
interactive 0.4.3
powerbidedicated 0.1.1

```

**Comment by yonzhan** [comment]
apim

**Comment by RakeshMohanMSFT** [comment]
@enema17484 This issue is resolved
