### ISSUE TITLE
Webapp:Improve the error message for az webapp up runtime auto detection

### ISSUE THREAD

**Issue by btardif** [Azure/azure-cli#15202]
There are 2 things to fix in this bug:

## Improve formating:

Notice the difference between az webapp up error message formatting and the formating for az --versions command.

1) Multiple lines instead of runoff text make it more readable.
2) links are color coded to stand out

![image](https://user-images.githubusercontent.com/4119816/93531042-73194a00-f8f3-11ea-89f7-73912b1a0f01.png)

Here is my proposal:

![image](https://user-images.githubusercontent.com/4119816/93531282-cdb2a600-f8f3-11ea-92fd-4cab3de28203.png)

- break the error message into multiple sentences with line breaks
- apply link formatting to learn more link

## improve the message body

The most common mistake is running this command from he wrong folder, this is covered in the learn more doc, however we should try and surface it a bit more, the suggestion here is to add a hint:

**Hint:** are you in the right folder?

**Comment by yonzhan** [comment]
webapp
