### ISSUE TITLE
az backup policy create --workload-type {} KeyError: 'AzureFileShare'

### ISSUE THREAD

**Issue by DoppoM** [Azure/azure-cli#15206]
## Describe the bug

**Command Name**
`az backup policy create`

**Errors:**
```
'AzureFileShare'
Traceback (most recent call last):
Temp\pip-install-7cl6xofh\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 631, in execute
azure\cli\core\commands\__init__.py, ln 695, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 688, in _run_job
Local\Temp\pip-install-7cl6xofh\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 665, in _run_job
azure\cli\core\commands\__init__.py, ln 324, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 574, in default_command_handler
azure\cli\command_modules\backup\custom_base.py, ln 42, in create_policy
azure\cli\command_modules\backup\custom_wl.py, ln 206, in create_policy
KeyError: 'AzureFileShare'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup policy create --backup-management-type {} --name {} --policy {} --resource-group {} --vault-name {} --workload-type {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1 *

```
## Additional Context
If i try to use 'az backup policy create' without '--workload-type', i get output "Please provide workload type."

**Comment by yonzhan** [comment]
backup

**Comment by pvrk** [comment]
@DoppoM : Just wanted to confirm: Are you passing the policy definition as a JSON encoded object?

**Comment by DoppoM** [comment]
@pvrk,  of course, I use .json file in cmdlet
```
az backup policy create `
--backup-management-type AzureIaasVM `
--name $policyName `
--policy ./vm-backup-policy.json `
--resource-group $newRecoveryServicesVault.resourceGroup `
--vault-name $newRecoveryServicesVault.name

```

**Comment by pvrk** [comment]
@DoppoM : Thanks for the clarity. Will come back on this. @hiaga : Let's take a look and respond.

**Comment by mepand** [comment]
@DoppoM Currently az backup policy create command doesn't support creation of IAAS VM policy. We have an action item at our end and working actively for supporting this.

**Comment by DoppoM** [comment]
@mepand  thx for feedback

**Comment by mepand** [comment]
@DoppoM  az backup policy create command now supports creation of IAAS VM policy. Since there is no further action pending from our side, closing this issue. Please feel free to reach out incase of any query.
