### ISSUE TITLE
Webapp:deploying a .net app to a linux webapp with az-webapp-up fails

### ISSUE THREAD

**Issue by btardif** [Azure/azure-cli#15201]
Our defaults when creating a new .net core app should continue to target windows.

However deploying to a linux app should be supported for .net core.

![2020-09-17_12h02_27](https://user-images.githubusercontent.com/4119816/93515810-09db0c00-f8de-11ea-9afc-8ace0011876f.gif)

## command output

Webapp 'bk-linux-dotnet' already exists. The command will deploy contents to the existing app.
The webapp 'bk-linux-dotnet' is a Linux app. The code detected at 'C:\Demo\core' will default to '<module 'os' from 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\lib\\os.pyc'>'. Please create a new app to continue this operation.

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@btardif as per our discussion az webapp up has restrictions and follows the same rules it follows for create + deploy with az webapp up i.e .netcore defaults to windows. happy to have discussion to change design - but keep it consistent and avoid causing more confusion. for deployments we have az webapp config deployment - zip deploy commands & that should be used.
