### ISSUE TITLE
[Storage] Recursive download and uploads for ADLS Gen2 folders

### ISSUE THREAD

**Issue by caksoylar** [Azure/azure-cli#15200]
**Is your feature request related to a problem? Please describe.**

There is currently no way to download or upload a directory with the `az storage fs` interface. Since ADLS Gen2 is a hierarchical system, it needs to have a way to interact with directories as a first-class citizen. [This was possible](https://github.com/Azure/azure-cli-extensions/tree/master/src/storage-preview#mapping-from-adls-gen1-to-adls-gen2) before with the `az storage blob directory download` command in the `storage-preview` extension.

**Describe the solution you'd like**

Add a new `--recursive` flag to `az storage fs file download` and `az storage fs file upload` commands. Or create new `az storage fs directory download` and `az storage fs directory upload` commands that work with directories recursively.

**Describe alternatives you've considered**

Enumerate the folder contents with `az storage fs directory list`, then parse it and call `az storage fs file download` separately (and recurse for subdirectories). This is infeasible because of the startup cost of starting a new `az` process for each file.

**Additional context**

While the new `az storage fs` interface is a clear improvement over `az storage blob directory` (for example directory listing doesn't take ages to run), this case is an obvious regression that has to be addressed for it to be usable at all.

**Comment by yonzhan** [comment]
add to S176

**Comment by Juliehzl** [comment]
Hi @caksoylar, thanks for your feedback.
For the reason we don't migrate `directory upload`/`donwload`, it is because we have similar command in main CLI, which is `az storage copy`.
Could you try with `az storage copy` fisrt? And if you still think `az storage fs directory upload/donwload` are useful, we could consider add such support.

**Comment by caksoylar** [comment]
Hi @Juliehzl, I wasn't aware of `az storage copy`. At first glance the interface looks like `azcopy` which I used before, so I assume I can pass the blob URL (`https://<account-name>.blob.core.windows.net/<container-name>/path`) for ADLS Gen2, however I couldn't get it to work because it couldn't find my storage account. It also seems to be using a different authentication setup than Azure CLI, where other functions currently work fine for me.

While my particular issue above can likely be resolved, I'd **strongly prefer** to have a directory download/upload option in `az storage fs` to keep the interface consistent with `file download/upload`. `az storage copy` has a different interface and consistency would be very good to have. In fact, I'd prefer if I didn't have to know in advance whether I am downloading a `file` or `directory` and instead specify a `--recursive` flag for `file`, which is how most `cp` implementations work.

If you decide not to go with this direction, I'd suggest that at least documentation for `az storage fs` be updated to direct users to `az storage copy`. In fact, in that case, `az storage fs file download/upload` operations can also be removed, since I believe they are covered by `az storage copy`. However I'd strongly prefer the first option like I noted above.

**Comment by Juliehzl** [comment]
@evelyn-ys could you help support the issue?
