### ISSUE TITLE
Creating a volume with az cli only works when subnet field is set with full resource id 

### ISSUE THREAD

**Issue by netapp-juliec** [Azure/azure-cli#15209]
Received the following doc change request from NetApp team member (Stefan.Smarason@netapp.com) -- 

Microsoft documentation has to be corrected: https://docs.microsoft.com/en-us/cli/azure/netappfiles/volume?view=azure-cli-latest#az_netappfiles_volume_create
i.e.
--subnet
The ARM Id **or name** of the subnet for the vnet. If omitted 'default' will be used.
default value: default
 
Please remove "or name".  
When providing only the name of the subnet, volume creation fails with VNET not found.
Creating a volume with az cli only works when subnet field is set with full resource id 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 298ada99-369a-1c65-50ca-617931d26b7a
* Version Independent ID: 5fbd1cdf-e27f-8ffe-1c72-14f5d9e186f1
* Content: [az netappfiles volume](https://docs.microsoft.com/en-us/cli/azure/netappfiles/volume?view=azure-cli-latest#az_netappfiles_volume_create)
* Content Source: [latest/docs-ref-autogen/netappfiles/volume.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/netappfiles/volume.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
netappfiles

**Comment by netapp-juliec** [comment]
Can we please get an update on this PR?  Thanks.

**Comment by yonzhan** [comment]
netappfiles service team should look into this issue.
