### ISSUE TITLE
'az apim api import' doesn't take api version argument

### ISSUE THREAD

**Issue by finesse-fingers** [Azure/azure-cli#15205]
Really liking the az apim api, however, is there a way to set the API version?

I notice the option to specify --api-revision. Would be nice to have --api-version option as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f27e34-66e0-1d08-f734-26ce29c56c36
* Version Independent ID: d1a421eb-807c-c0bd-cee3-a5aed7335625
* Content: [az apim api](https://docs.microsoft.com/en-us/cli/azure/apim/api?view=azure-cli-latest#az_apim_api_import)
* Content Source: [latest/docs-ref-autogen/apim/api.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/apim/api.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
apim

**Comment by petenorth** [comment]
Any update on this?

The CLI command seems to match the Powershell API all except for API versions

https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/import-azapimanagementapi?view=azps-5.9.0

Example 5 is the use case that the CLI doesn't support

https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/import-azapimanagementapi?view=azps-5.9.0#example-5---import-an-api-from-a-open-api-link-into-a-apiversion-set

**Comment by DreamlessA** [comment]
Issue is now resolved with PR https://github.com/Azure/azure-cli/pull/18604. Please ping me if there is any other issue. Thanks!

**Comment by RakeshMohanMSFT** [comment]
@finesse-fingers This is resolved
