### ISSUE TITLE
Cannot remove extension in development mode?

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#15215]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Attempting to remove an experimental extension that can't be loaded but no luck

**To Reproduce**
![image](https://user-images.githubusercontent.com/30876406/93723808-bb847200-fb56-11ea-902e-b4d47339ae53.png)

**Expected behavior**
Being able to remove the extension...

**Environment summary**
![image](https://user-images.githubusercontent.com/30876406/93723845-07371b80-fb57-11ea-8b4c-8f0789280af0.png)

**Additional context**

**Comment by yonzhan** [comment]
extension

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls look at the error about the removing command? thanks.

**Comment by fengzhou-msft** [comment]
@chenlomis azdev can only be used in a Python venv. You need to activate your venv then use azdev to remvoe the extension.

**Comment by chenlomis** [comment]
Sounds good
Thanks for the resolution!
