### ISSUE TITLE
Use Azure CLI create subnet issue

### ISSUE THREAD

**Issue by aaaaasam** [Azure/azure-cli#15213]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
The IPv6 subnet can be successfully created using the CLI, but it cannot be viewed and referenced by azure portal

**To Reproduce**
Can Work Code：
az network vnet subnet create \
	--address-prefixes  '10.1.2.0/24' 'ace:cab:decb:deed::/64' \
	--name TestIPv6Subnet \
	--resource-group sam-test-resource-group \
	--vnet-name samtestresourcegroupvnet150

Can't work code:
az network vnet subnet create \
	--address-prefixes 'ace:cab:decb:deed::/64'  '10.1.2.0/24'  \
	--name TestIPv6Subnet \
	--resource-group sam-test-resource-group \
	--vnet-name samtestresourcegroupvnet150

**Comment by yonzhan** [comment]
add to S176

**Comment by haroldrandom** [comment]
@aaaaasam Sorry. I can't reproduce. 
![image](https://user-images.githubusercontent.com/14357159/97832861-d4b03f00-1d0e-11eb-8745-33d961f548b7.png)

Are this scenario happening again now?

**Comment by haroldrandom** [comment]
Closed as inactive. If happening again, feel free to reopen it.
