### ISSUE TITLE
`Az rest` messes up with `$` in the URL on windows

### ISSUE THREAD

**Issue by geordle** [Azure/azure-cli#15214]
## Describe the bug

**Command Name**
`az rest`

**Errors:**

Some html is outputted. Followed by `'$expand' is not recognized as an internal or external command,
operable program or batch file.`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az rest --url 'https://dev.azure.com/{}/{}/_apis/wit/workitemtypes/Bug/fields/{}?api-version=6.1-preview.3&$expand=All' --resource  "499b84ac-1321-427f-aa17-267ca6975798"`

## Expected Behavior
Output resource as json. 

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.11.1

Extensions:
azure-devops 0.18.0

```
## Additional Context

Same command but without `&$expand=All` in the URL executes correctly... but does not contain the fields I'm after.  I think it's an escaping issue, adding the `--debug` flag shows that after the initial steps the URL is already split. 

```
az rest --debug --url 'https://dev.azure.com/{}/{}/_apis/wit/workitemtypes/Bug/fields/{}?api-version=6.1-preview.3&$expand=All' --resource  "499b84ac-1321-427f-aa17-267ca6975798"

>>>debug output

Command arguments: ['rest', '--debug', '--url', 'https://dev.azure.com/{}/{}/_apis/wit/workitemtypes/Bug/fields/{}?api-version=6.1-preview.3']
````

Navigating to the exact URL in a browser works. Same command in `bash` in wsl2 works. I've tried replacing the `$` with urlencoded version, using "" and explicitly escaping, all to no avail. If you could help me out that would be awesome (did I ever tell you you build great stuff?).

**Comment by yonzhan** [comment]
add to S176

**Comment by evelyn-ys** [comment]
linked with #15529

**Comment by evelyn-ys** [comment]
Hi @geordle, this is a known issue in Powershell. We have a doc about quoting issues on the home page https://github.com/Azure/azure-cli#common-scenarios-and-use-azure-cli-effectively. You may find the link there pointing to [Quoting issues](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues), which again links to [Quoting issues with PowerShell](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md#ampersand--is-interpreted-by-command-prompt).
Here's the solution to your scenario:
In Windows Powershell:
```
> $expand="myexpand"
> az rest --url "`"https://dev.azure.com/{}/{}/_apis/wit/workitemtypes/Bug/fields/{}?api-version=6.1-preview.3&$expand=All`"" --resource "499b84ac-1321-427f-aa17-267ca6975798"
```
In Windows CMD:
```
> set expand=myexpand
> az rest --url "https://dev.azure.com/{}/{}/_apis/wit/workitemtypes/Bug/fields/{}?api-version=6.1-preview.3&%expand%=All" --resource "499b84ac-1321-427f-aa17-267ca6975798"
```
In Bash:
```
$ expand=myexpand
$ az rest --url "https://dev.azure.com/{}/{}/_apis/wit/workitemtypes/Bug/fields/{}?api-version=6.1-preview.3&$expand=All" --resource "499b84ac-1321-427f-aa17-267ca6975798"
```

**Comment by geordle** [comment]
Ha, found it. Thanks! It was solved by wrapping it with single quotes, like listed quoting issues. So: az rest --url '"https://dev.azure.com/{}/{}/_apis/wit/workitemtypes/Bug/fields/{}?api-version=6.1-preview.3&$expand=All"' --resource "499b84ac-1321-427f-aa17-267ca6975798"
