### ISSUE TITLE
Installing CLI 2.0 Preview onto macOS 10.12 fails, with OpenSSL-related C compilation error

### ISSUE THREAD

**Issue by DavidLudwig** [Azure/azure-cli#1522]
Attempting to install the CLI 2.0 Preview onto a macOS 10.12 (aka, "macOS Sierra") machine fails.  Specifically, it fails when attempting to build a file, "build/temp.macosx-10.12-intel-2.7/_openssl.c".

The command run to attempt installation was as follows:

`pip install --user azure-cli`

The error generated was as follows:

```
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c build/temp.macosx-10.12-intel-2.7/_openssl.c -o build/temp.macosx-10.12-intel-2.7/build/temp.macosx-10.12-intel-2.7/_openssl.o

build/temp.macosx-10.12-intel-2.7/_openssl.c:434:10: fatal error: 'openssl/opensslv.h' file not found

#include <openssl/opensslv.h>

         ^

1 error generated.

error: command 'cc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/private/var/folders/x0/nmqpprms1ss69gt8yppnxgl40000gn/T/pip-build-davidl/cryptography/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/x0/nmqpprms1ss69gt8yppnxgl40000gn/T/pip-tMqwwB-record/install-record.txt --single-version-externally-managed --user failed with error code 1 in /private/var/folders/x0/nmqpprms1ss69gt8yppnxgl40000gn/T/pip-build-davidl/cryptography
Storing complete log in /Users/davidl/Library/Logs/pip.log
```

A full copy of the pip log is attached.

Xcode 7.3 is installed on the machine, along with its command-line tools, and is set (via 'xcode-select') to be the primary Xcode.

If I remember correctly, macOS 10.12 changed if or how it installed OpenSSL, in some manner, but I might be mistaken.  I do recall other, open-source libraries running into trouble with macOS 10.12, and OpenSSL.

If need be, I could try installing OpenSSL via brew, or MacPorts.

[pip.log.zip](https://github.com/Azure/azure-cli/files/642654/pip.log.zip)

**Comment by DavidLudwig** [comment]
If it helps, I could try installation via a different version of Xcode.  I have both 7.3.1 and 8.1 installed on my machine, and could get other version(s), if needed.

**Comment by derekbekoe** [comment]
@DavidLudwig Did upgrading Xcode or installing an update to openssl resolve your issue?

**Comment by DavidLudwig** [comment]
Hmmm, switching my system from MacPorts, to Brew, seemed to fix the issue.

Installing the CLI without pip (via the InstallAzureCli shell script) also seemed to work.

**Comment by derekbekoe** [comment]
Following up with a solution:
```
xcode-select --install
```

http://stackoverflow.com/a/19604913
