### ISSUE TITLE
Webapp:Webapp deployment: Unable to target folders other than wwwroot 

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-cli#15226]
**Resource Provider**
Microsoft.Web

**Description of Feature or Work Requested**

- Am using Azure CLI to deploy two projects from a single solution.

- There are two zip packages out of the build and i wanted to deploy both. Ex: firstproject.zip and secondproject.zip

- I used the below Azure CLI command: az webapp deployment source config-zip --resource-group "dummy" --name "sample" --src "firstproject.zip" -- this gets deployed to wwwroot by default

- I want to use the same command for the secondproject.zip, and want to deploy to apiroot, instead of wwwroot.

Please let me know how to achieve this and change the target folder from wwwroot to something else?

The same applies to AzureDevOps Webapp Deployment task, where there is no option to deploy to other custome folders other than wwwroot.

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
This is currently by design and not supported.

**Comment by rajaprad** [comment]
@panchagnula  - What is the alternative for this design ? when will it be supported ?

**Comment by krish-gh** [comment]
It is recommended to use separate WebApps. If cost is the concern, you can use same 'app service plan' for multiple web apps.
