### ISSUE TITLE
Getting PIP install to work...

### ISSUE THREAD

**Issue by grecoe** [Azure/azure-cli#15231]
Hi,

I *thought* I had this working last week....using 

az functionapp deployment source config-zip

To push a zip file to an app service containing python function app code. Codes all there but the problem is the requirements.txt file is having no effect...that is the needed azure libraries listed are not getting installed to the environment. If I then publish with VS code I see the pip install happen and all is right with the world. 

When I use the command it sets WEBSITE_RUN_FROM_PACKAGE and SCM_DO_BUILD_DURING_DEPLOYMENT did nothing to help. 

I'm pretty sure when I used the powershell command, Publish-AzWebapp , it worked but then the problem was another downstream issue I had to try and serialize in an ARM deployment. 

Any help would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebc5cbbe-2cb1-8430-3843-638fa3fd3f1b
* Version Independent ID: eb60de03-08d0-141f-9fb2-5970e3a2bd7f
* Content: [az functionapp deployment source](https://docs.microsoft.com/en-us/cli/azure/functionapp/deployment/source?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/functionapp/deployment/source.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/functionapp/deployment/source.yml)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
functionapp

**Comment by grecoe** [comment]
Sorry, this can be closed. I completely missed the flag --build-remote which solved the problem.
