### ISSUE TITLE
Webapp:az webapp does not support installing extensions

### ISSUE THREAD

**Issue by FlourishS** [Azure/azure-cli#15235]
### Expected

On the azure portal new extensions can be installed as shown below. It is expected that the same action can be taken via the "az webapp" command.

![image](https://user-images.githubusercontent.com/40595784/93852679-c18f6580-fcb2-11ea-9492-f56b79b2e883.png)

### Actual

The az webapp command does not support installing extensions such as Pythong 2.7.

**Comment by yungezz** [comment]
route to appropriate team

**Comment by panchagnula** [comment]
Thanks for reporting we will add support to this in upcoming milestones.

**Comment by ThejaChoudary** [comment]
Considering this for feature request.
FYI @panchagnula

**Comment by seligj95** [comment]
Thank you for the feedback but we will not be doing this at this time.
