### ISSUE TITLE
Webapp:az webapp does not support deployment source of Azure Pipeline

### ISSUE THREAD

**Issue by FlourishS** [Azure/azure-cli#15236]
### Expected

In the azure portal a webapp can be configured to be deployed from azure pipeline. "Az webapp" is expected to support this configuration as well.

### Actual

"Az webapp" does not support configuring a webapp to be deployed from azure pipeline.

**Comment by yungezz** [comment]
route to appropriate team

**Comment by panchagnula** [comment]
@FlourishS I am not sure I understand the issue here - what exact deployment are you referring? GitHub deployment/ git hub actions? can you share the screenshot from azure portal you are referring to? Thanks!

**Comment by FlourishS** [comment]
Thank you very much for your reply.

Please see below the screenshots from azure portal:

![image](https://user-images.githubusercontent.com/40595784/94235772-5d67de00-ff0c-11ea-9ffd-a0e5b8de2e62.png)

![image](https://user-images.githubusercontent.com/40595784/94235871-8e481300-ff0c-11ea-8237-e65927cce76a.png)

**Comment by btardif** [comment]
This is by-design, there are no plans to support Azure Pipelines configuration through WebApps CLI

CC: @panchagnula
