### ISSUE TITLE
table output for `az account` should show id instead of tenantId

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-cli#1523]
As in the title. The "id" property is what can be used with `az account set` et al. I'm not sure what "tenantId" represents, but it's shared across subs.

Thanks!

**Comment by squillace** [comment]
yeah, a tenantID is a critical concept. That can't be just id. It's an AAD concept that is part of docs everywhere.... you can call it "id", but then you'll be explaining everywhere to find the "id" of the account and use that as the "tenant" id.

**Comment by yugangw-msft** [comment]
Agree with @squillace, also the current table output no longer includes the `tenantId`, so no confusions
