### ISSUE TITLE
az vm create with scope argument gives an error

### ISSUE THREAD

**Issue by cnadgonde** [Azure/azure-cli#15243]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Creating a VM with scope argument where the scope is granting a role to a storage account in a different resource group than the VM resource group throws following error

Deployment failed. Correlation ID: 08673f9b-d369-4f65-95aa-ab8e24115e7d. {
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.Storage/storageAccounts/mystorage' under resource group 'MyRG' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
  }
}

**To Reproduce**
az vm create --resource-group MyRG --name MyVM --image UbuntuLTS \
 --nics $vnic \
 --admin-username attcloud \
 --admin-password $xword \
 --size "Standard_D16_v3" \
 --assign-identity "[system]" \
 --scope "/subscriptions/fbd*****-a76d-****-****-f1d9610****/resourceGroups/MyStorageResourceGroup/providers/Microsoft.Storage/storageAccounts/mystorage/blobServices/default/containers/keysContainer" \
 --role "Storage Blob Data Reader"

**Expected behavior**
A VM should be created with system assigned managed identity. The identity should have Storage Blob Data Reader role assigned to access container keysContainer in storage account mystorage

**Environment summary**
<!--- Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Bash CLI used with
azure-cli                         2.0.80 *

**Additional context**

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look? thanks.

**Comment by qwordy** [comment]
Hi @cnadgonde, can you confirm if Storage Blob Data Reader is an existing role name?
