### ISSUE TITLE
Update network vrouter Help Text

### ISSUE THREAD

**Issue by nerddtvg** [Azure/azure-cli#15249]
## Describe the bug

The help text is confusing.

**Command Name**
`az network vrouter`

**Errors:**

https://github.com/Azure/azure-cli/blob/1fcfa989e9545348e287296b2b52bb0214e4812a/src/azure-cli/azure/cli/command_modules/network/_params.py#L1835

The redirect value should have a dash (hosted-subnet) and not underscore (hosted_subnet).

https://github.com/Azure/azure-cli/blob/2b0e639001248204ba26394238d02492783c13b1/src/azure-cli/azure/cli/command_modules/network/_help.py#L5374

`Considering VirtualRouter is depcated, we recommand to create VirtualRouter instead`

Once of these VirtualRouter statements is wrong.

## To Reproduce:
- `az network vrouter --help`

## Environment Summary
```
Linux-4.19.128-microsoft-standard-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.12.0

```

**Comment by yonzhan** [comment]
add to S176
