### ISSUE TITLE
--policy-assignment parameter is incorrectly defined.

### ISSUE THREAD

**Issue by julesman101** [Azure/azure-cli#15242]
With reference the the following AZ CLI docs page: https://docs.microsoft.com/en-us/cli/azure/policy/state?view=azure-cli-latest

There are 2 references on this page to the definition of the "--policy-assignment" parameter. Both are incorrect.
The 2 references currently show:
![image](https://user-images.githubusercontent.com/7341236/93889546-39748480-fce1-11ea-9f11-e298e5a33c7c.png)

The correct definition is not the NAME of the Policy Assignment, it is the last alpahnumeric pattern of the assignment ID.

Looking at a policy assignment in the Azure Portal, it is the highlighted string below:
![image](https://user-images.githubusercontent.com/7341236/93890027-ce777d80-fce1-11ea-9120-d3ae90d2ecdf.png)

Kind Regards.... Jukius Davies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca46c96d-8c88-7c4a-d75f-1c6c45d0f75c
* Version Independent ID: 9b8bdef9-8f67-7e82-1ae8-9356b62e84b0
* Content: [az policy state](https://docs.microsoft.com/en-us/cli/azure/policy/state?view=azure-cli-latest#az_policy_state_summarize)
* Content Source: [src/azure-cli/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S176

**Comment by zhoxing-ms** [comment]
In fact, the policy assignment name is the suffix of policy assignment ID in CLI:
![Screenshot 2021-01-11 151836](https://user-images.githubusercontent.com/16612065/104155623-90ce6a00-5422-11eb-9573-2f35e9cc1f59.png)
![Screenshot 2021-01-11 152501](https://user-images.githubusercontent.com/16612065/104155631-93c95a80-5422-11eb-8eaf-8d4fab5888a0.png)

So this should be a issue of Portal: the original `Assignment name` should make it clear that it is `Assignment display name` and show the real `Assignment name` to avoid misleading users.
![Web capture_11-1-2021_153341_portal azure com](https://user-images.githubusercontent.com/16612065/104155730-c07d7200-5422-11eb-96db-eff45daa4efc.jpeg)

**Comment by kenieva** [comment]
To the best of knowledge, the standard across Azure Portal is to have Name = display. However, I see how the CLI documentation stating Name of policy assignment, but actually meaning ID of policy assignment can be confusing. I have submitted a request to update. Thank you.
