### ISSUE TITLE
Can't seem to revert back to previous CLI version

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#15253]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
(not sure if it's a bug) but attempted to revert back to 2.11.0 version using pip install but didn't work

**To Reproduce**

![image](https://user-images.githubusercontent.com/30876406/93945892-ab060000-fcec-11ea-826b-3c542ee33325.png)

**Expected behavior**
being able to revert back to version 2.11.0

**Environment summary**

![image](https://user-images.githubusercontent.com/30876406/93945869-9f1a3e00-fcec-11ea-91ca-bc2a5069703a.png)

**Additional context**

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls to have a look?

**Comment by fengzhou-msft** [comment]
@chenlomis based on the Python information, it looks like you're using the MSI-installed azure-cli. Please install
https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.11.0.msi to revert to 2.11.0
