### ISSUE TITLE
Azure Cli Command Not Working 

### ISSUE THREAD

**Issue by RedTeamOperations** [Azure/azure-cli#15268]
## Describe the bug

**Command Name**
`az ad user list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:



Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-64vfp5fb\knack\knack\cli.py", line 212, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-64vfp5fb\knack\knack\output.py", line 134, in out
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-64vfp5fb\colorama\colorama\ansitowin32.py", line 41, in write
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-64vfp5fb\colorama\colorama\ansitowin32.py", line 162, in write
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-64vfp5fb\colorama\colorama\ansitowin32.py", line 190, in write_and_convert
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-64vfp5fb\colorama\colorama\ansitowin32.py", line 195, in write_plain_text
MemoryError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad user list`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.79 *

```

**Comment by yonzhan** [comment]
add to S176

**Comment by jiasli** [comment]
`MemoryError` indicates `az` is running out of memory, because the user list is too long. Please consider using `--filter` to limit the result size.

**Comment by b-dasass** [comment]
Hi @jiasli 

Is there an artificial memory limit what we're hitting here?

Are you suggesting to write our own "recursion" to get all users? Is there any already existing best practice how should we do that?

Thank you!

**Comment by jiasli** [comment]
> Is there an artificial memory limit what we're hitting here?

No. Azure CLI doesn't impose any memory limit by itself.

Current `az ad user list` still calls the deprecated AD Graph API [Get users](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/users-operations#get-users--) internally, which has [Paging support](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/howto/azure-ad-graph-api-supported-queries-filters-and-paging-options#paging-support-), but this ability is not exposed by `az ad user list`:

```
$ az ad user list --help
...
Arguments
    --display-name                  : Object's display name or its prefix.
    --filter                        : OData filter, e.g. --filter "displayname eq 'test' and
                                      servicePrincipalType eq 'Application'".
    --upn                           : User principal name, e.g. john.doe@contoso.com.
```

> Are you suggesting to write our own "recursion" to get all users? Is there any already existing best practice how should we do that?

Yes. In such case, calling the new Microsoft Graph API [List users](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http) with `az rest` will be the best choice for the time being (#12946):

```sh
$ az rest --method GET --url 'https://graph.microsoft.com/v1.0/users?$top=2'
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users",
  "@odata.nextLink": "https://graph.microsoft.com/v1.0/users?$top=2&$skiptoken=X%27445370...",
  "value": [
    {      
      "displayName": "Admin",
      "givenName": null,
      ...
    },
    {
      ...
    }
  ] 
```
