### ISSUE TITLE
Incorrect statement on documentation

### ISSUE THREAD

**Issue by pfsantosaad** [Azure/azure-cli#15260]
Azure CLI groups doc (https://docs.microsoft.com/en-us/cli/azure/ad/group/member?view=azure-cli-latest#az_ad_group_member_add) states that you need to use the Object ID of Service Principals to add them to a group, however this is incorrect as in order to CLI to resolve the Service Principal it uses the Application ID.

Current:
--member-id
The object ID of the contact, group, user, or service principal.

Should be:
--member-id
The object ID of the contact, group, user, or **Application ID** of service principal.

Best regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c659a298-8897-6d50-c1d9-c14a3b0e6364
* Version Independent ID: 2d2bec5b-ef92-f65f-bfd0-ccdabda52a41
* Content: [az ad group member](https://docs.microsoft.com/en-us/cli/azure/ad/group/member?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by fengzhou-msft** [comment]
@jiasli can you take a look?

**Comment by yonzhan** [comment]
add to S176

**Comment by jiasli** [comment]
The document is correct: `--member-id` should be the object ID of the Service Principal.

![image](https://user-images.githubusercontent.com/4003950/118105603-2b5daa80-b40f-11eb-9b5c-6ed37d2491cb.png)

```
> az ad group member add --group group0513 --member-id adce3999-674f-4d46-b0d3-fe7675117b36
```

Using application ID causes failure:

```
> az ad group member add --group group0513 --member-id 4e3ee70e-6eeb-4ee3-acc9-344131610713
Resource '4e3ee70e-6eeb-4ee3-acc9-344131610713' does not exist or one of its queried reference-property objects are not present.
```
