### ISSUE TITLE
Issue - az backup vault create 

### ISSUE THREAD

**Issue by narendraugh** [Azure/azure-cli#15266]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I am creating recovery service vault using the below command 
$ResourceGroup = "Test-RG"
$Location = "westeurope"
$RecoveryServiceVaultName = "Test-RSV"
az backup vault create -g $ResourceGroup -n $RecoveryServiceVaultName -l $Location

Error:
az : Command group 'backup' is in preview. It may be changed/removed in a future release.
At line:5 char:1
+ az backup vault create -g $ResourceGroup -n $RecoveryServiceVaultName ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Command group '...future release.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Resource group 'Test-RG' could not be found.

**To Reproduce**
$ResourceGroup = "Test-RG"
$Location = "westeurope"
$RecoveryServiceVaultName = "Test-RSV"
az backup vault create -g $ResourceGroup -n $RecoveryServiceVaultName -l $Location

**Expected behavior**
It should create service vault

**Environment summary**
<!--- Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell 

OS Name	Microsoft Windows 10 Enterprise

PSversion:
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  752 

PS C:\WINDOWS\system32> az --version
azure-cli                         2.11.1 *
core                              2.11.1 *
telemetry                          1.0.5

**Comment by yonzhan** [comment]
backup

**Comment by narendraugh** [comment]
> backup

@yonzhan: I do not understand your reply?

**Comment by yonzhan** [comment]
backup service team should look into this issue.

**Comment by pvrk** [comment]
@narendraugh : Sorry for the delay in responding. Could you please check if the RG exists by using the ['az group exists'](https://docs.microsoft.com/cli/azure/group?view=azure-cli-latest#az_group_exists) command? Also, or location, please make sure that the value is as listed here ( ```az account list-locations --query "sort_by([].{DisplayName:displayName, Name:name}, &DisplayName)" --output table```).

**Comment by narendraugh** [comment]
> @narendraugh : Sorry for the delay in responding. Could you please check if the RG exists by using the ['az group exists'](https://docs.microsoft.com/cli/azure/group?view=azure-cli-latest#az_group_exists) command? Also, or location, please make sure that the value is as listed here ( `az account list-locations --query "sort_by([].{DisplayName:displayName, Name:name}, &DisplayName)" --output table`).

@pvrk - It is resolved now. Thankyou :-)

**Comment by narendraugh** [comment]
It is resolve now hence closing the issue.
