### ISSUE TITLE
Issue trying to update subnet of a VMSS using set command

### ISSUE THREAD

**Issue by enigmae** [Azure/azure-cli#15264]
## Describe the bug

**Command Name**
`az vmss update`

**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
python3.6/site-packages/msrest/serialization.py, ln 1416, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
...
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss update --name {} --resource-group {} --set {}`

## Environment Summary
```
Linux-4.15.0-1095-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.12.0

Extensions:
ai-examples 0.2.3

```

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look? thanks

**Comment by qwordy** [comment]
@enigmae Can you add --debug to your command and post output here?

**Comment by qwordy** [comment]
Similar issue: https://github.com/Azure/azure-cli/issues/15119

**Comment by qwordy** [comment]
@enigmae Can you add --debug to your command and post output here? And I need complete command to reproduce and debug the issue. Thanks.
