### ISSUE TITLE
Webapp: VBXCBXC

### ISSUE THREAD

**Issue by bacmodung** [Azure/azure-cli#15279]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56fc532d-8c75-3681-3c26-c6276df401a2
* Version Independent ID: 1e51db86-6ad9-d6ea-cdb5-ced1b86fc65d
* Content: [az webapp scan](https://docs.microsoft.com/en-us/cli/azure/ext/webapp/webapp/scan?view=azure-cli-latest#ext_webapp_az_webapp_scan_start)
* Content Source: [latest/docs-ref-autogen/ext/webapp/webapp/scan.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/webapp/webapp/scan.yml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bacmodung** [comment]
> [Enter feedback here]
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 56fc532d-8c75-3681-3c26-c6276df401a2
> * Version Independent ID: 1e51db86-6ad9-d6ea-cdb5-ced1b86fc65d
> * Content: [az webapp scan](https://docs.microsoft.com/en-us/cli/azure/ext/webapp/webapp/scan?view=azure-cli-latest#ext_webapp_az_webapp_scan_start)
> * Content Source: [latest/docs-ref-autogen/ext/webapp/webapp/scan.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/webapp/webapp/scan.yml)
> * Service: **app-service**
> * GitHub Login: @rloutlaw
> * Microsoft Alias: **routlaw**

**Comment by bacmodung** [comment]
vhgfh

**Comment by btardif** [comment]
@Kotasudhakarreddy closing this as **no-repro**
