### ISSUE TITLE
blob copy between account - there is no way to specify source and destination accounts

### ISSUE THREAD

**Issue by xpillons** [Azure/azure-cli#1527]
In the "azure storage blob copy start" CLI you can provide two storage accounts, one for the source, and one for the dest. This is not possible in this release, only URI with SAS is permit

**Comment by tjprescott** [comment]
@xpillons the implementation of `az storage blob copy start` is very much tied to the SDK implementation of the copy operation. We are working on a more customized upload/download/copy experience that you can try:  `az storage blob copy start-batch`. This does accept a source storage account and allows you to copy more than one blob at a time via globbing patterns.

After we have collected feedback and refined the "batch" versions of copy/upload/download, they will be the commands we promote over the old "one-at-a-time" verisons.

**Comment by valencik** [comment]
We'd like to copy a captured VHD from one resource group to another. I'm trying to use `az storage blob copy start-batch` as you've suggested but not getting any luck.

```bash
az storage blob copy start-batch \
--source-account capturetest \
--destination-container system \
--source-container system \
--prefix Microsoft.Compute/Images/vhds/capture-1234-osDisk.hexcodestuffvhd \
--account-name capturedisks
```

This outputs nothing normally, and with the `--verbose` flag we get the following as the bottom output:
```
Application event 'Application.TransformResults' with event data {'event_data': {'result': []}}
Application event 'Application.FilterResults' with event data {'event_data': {'result': []}}
```
We have also tried adding the `--account-key` which changes nothings.

**Comment by troydai** [comment]
I'll take a look.

**Comment by valencik** [comment]
Turns out you need a `--source-sas` param. I managed to get things working with the following:

```bash
az storage blob copy start-batch \
    --source-account "$source_account" \
    --destination-container system \
    --source-container system \
    --prefix "$source_blob" \
    --account-name "$destination_account" \
    --source-sas "$source_sas"
```

Where the `source_sas` is generated with the following:

```bash
az storage blob generate-sas \
    --account-name "$source_account" \
    --name "$source_blob" \
    --container-name system \
    --permissions r \
    --expiry "$expirary_date" \
    --output tsv
```

Attached is an example bash script:
[example-blob-copy.sh](https://github.com/Azure/azure-cli/files/702854/example-blob-copy.txt)

**Comment by troydai** [comment]
@valencik @xpillons does this solve your problem? I'll close this issue. Please reopen or file a new issue and there are further issues.

Thanks.

**Comment by Calvin-Yuhui-Liu** [comment]
FYI. I'm working with azure-cli (2.0.45) and it works for me. In my case, I tried to copy bunch of zip files from file share in on storage account to a blob container in another storage account. the trick is that you just need to pass the --source-share parameter with the share name -- not the full uri, and pass --pattern parameter with <path/*.zip>. Everything will be fine.
