### ISSUE TITLE
[UX lab] Password policy is not clear for az postgres up

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#15274]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
PWD validation failed but no concrete explanations
![image](https://user-images.githubusercontent.com/30876406/94086841-fbe72880-fdc0-11ea-9daa-fe616288fd67.png)

**To Reproduce**

![image](https://user-images.githubusercontent.com/30876406/94085771-d7d61800-fdbd-11ea-9376-e8ad15ca0625.png)
![image](https://user-images.githubusercontent.com/30876406/94085778-defd2600-fdbd-11ea-8790-f87f09346e92.png)
![image](https://user-images.githubusercontent.com/30876406/94085786-e290ad00-fdbd-11ea-9810-427ac9a5866e.png)

**Expected behavior**
1) When PWD validation fails, the tool should provide explicit requirements, context, and instructions around mitigation
2) This particular error probably should align with all the other PWD validation mechanism and output messages. Or better yet align with the portal's
3) Request to have all validations done at the client side instead of also failing it at the server side
![image](https://user-images.githubusercontent.com/30876406/94085962-6c407a80-fdbe-11ea-82ea-42863d8118c7.png)

*) Not really an expected behavior but am wondering whether there is something we could document ...

**Environment summary**
@shizn to help provide more context on the VM set up

**Additional context**
follow up issue from az connect UX lab

**Comment by yonzhan** [comment]
add to S177

**Comment by shizn** [comment]
Adding one more screenshot on the error message: password too short
![image](https://user-images.githubusercontent.com/3619378/96307184-06f33a00-0fb6-11eb-82e9-47577d1cd472.png)

They have exactly the same characters but the order is different ($).

**Comment by nachoalonsoportillo** [comment]
@yonzhan Please close. Thanks!
