### ISSUE TITLE
[UX lab] Git bash auto replacing user input?

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#15275]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
![image](https://user-images.githubusercontent.com/30876406/94086725-9d21af00-fdc0-11ea-82c3-dbd8a6f87fc3.png)

**To Reproduce**
Users attempting to pass in admin password for postgres db but apparently the password got auto-translated to something else

**Expected behavior**
(not sure if this is as expected)

**Environment summary**
@shizn to provide additional context on VM environment

**Additional context**
follow up issue from az connect UX lab

**Comment by yonzhan** [comment]
add to S177

**Comment by nachoalonsoportillo** [comment]
@yonzhan Please close. Thanks!
