### ISSUE TITLE
[Error Handling] "usage error" is prefixed with ValidationError

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#15280]
**Describe the bug**
The code has many checks which include `usage error` in the error message.

https://github.com/Azure/azure-cli/blob/419bf8b4a7988d853b9ab5a4b75b1be6c0dace5f/src/azure-cli/azure/cli/command_modules/storage/_validators.py#L1324

https://github.com/Azure/azure-cli/blob/c763c5bbd7c0a79ede49b540341347a48231beb4/src/azure-cli/azure/cli/command_modules/network/_validators.py#L191-L192

When the error is triggered, it will be printed as

```
ValidationError: usage error: xxx
```

The duplicated `ValidationError` and `usage error` may cause some confusion.

**Comment by yonzhan** [comment]
Error Handling

**Comment by houk-ms** [comment]
Resolved in #15319
