### ISSUE TITLE
Azure-cli version 2.12 not availible in brew as formula on mac

### ISSUE THREAD

**Issue by stefje-nd** [Azure/azure-cli#15285]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

> brew upgrade azure-cli
Warning: azure-cli 2.11.1 already installed

Eventhough current version is 2.12 

We work with apim and needs to use cli to import functions api to apim but it fails in version 2.11 so hopefully it will work in 2.12

**To Reproduce**
Brew formula for 2.12 not availible 

**Expected behavior**
When updating azure-cli please add version to brew

**Environment summary**
Mac OSX

**Comment by yungezz** [comment]
we're blocked by merging of PR https://github.com/Homebrew/homebrew-core/pull/61520 at homebrew side, it's closed now. Hopefully it will available soon. @fengzhou-msft  to share latest update.

**Comment by fengzhou-msft** [comment]
@stefje-nd 2.12.0 is available now for homebrew. You can run `az upgrade` to update.
