### ISSUE TITLE
Unable to install kubectl

### ISSUE THREAD

**Issue by kingadit** [Azure/azure-cli#15300]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
[Errno 13] Permission denied: '/usr/local/bin/kubelogin'
Traceback (most recent call last):
az/lib/python3.6/shutil.py, ln 550, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/tmp/tmpsf3zj9wf/bin/linux_amd64/kubelogin' -> '/usr/local/bin/kubelogin'

...

az/lib/python3.6/shutil.py, ln 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/kubelogin'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli --install-location={}`

## Environment Summary
```
Linux-4.15.0-1096-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.12.0

Extensions:
ai-examples 0.2.3

```

**Comment by yonzhan** [comment]
aks

**Comment by yungezz** [comment]
This should due to Cloudshell permission issue, no way to change system files in cloudshell

**Comment by ruchinmunjal** [comment]
Tried the same command as sudo and it worked. Dont know if this is correct way or not, but it worked and I was able to use it after that

**Comment by miwithro** [comment]
https://github.com/Azure/azure-cli/issues/2558

Either run sudo az aks install-cli or install it to a different directory that you have permission over.
