### ISSUE TITLE
urllib3.exceptions.LocationParseError when proxy setting has un-safe characters

### ISSUE THREAD

**Issue by HMatsumura** [Azure/azure-cli#15305]
**Describe the bug**
If proxy username/password has un-safe characters (like "\"), az login is failed due to URL parsing error by urllib3.

```
UnexpectedError: The command failed with an unexpected error. Here is the traceback:
Failed to parse: http://testdomain\user01:12345@proxy.co.jp:8080
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-nzvsnu6j\requests\adapters.py", line 412, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-nzvsnu6j\requests\adapters.py", line 305, in get_connection
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-yitcvwac\urllib3\util\url.py", line 234, in parse_url
urllib3.exceptions.LocationParseError: Failed to parse: http://testdomain\user01:12345@proxy.co.jp:8080
```

**To Reproduce**
In Windows OS and using PowerShell.
1. set the following variables (with un-safe character.)
e.g.)
```
$env:HTTPS_PROXY = "testdomain\user01:12345@proxy.co.jp:8080"
$env:HTTP_PROXY = "testdomain\user01:12345@proxy.co.jp:8080"
```

2. run `az login` and sign-in operation

**Expected behavior**
Doesn't happen this error. Users can use un-safe characters.
(If we use 2.0.77 MSI build from [official here](https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.0.77.msi), this issue is not happened.)

**Environment summary**
MSI install / At least after CLI 2.10.1 / Windows 10 / PowerShell

**Additional context**
Probably, this is related to urllib3 version using by azure-cli. In Non-issued version (2.0.77 MSI official build package) uses urllib3 1.24.2.
![image](https://user-images.githubusercontent.com/60459728/94239404-b7889380-ff4c-11ea-9192-4123cb08d89c.png)

On the other hands, recently issued version uses urllib3 1.25.3. This version is same issue (https://github.com/psf/requests/issues/5097) is reported other environment.

Moreover, in urllib3, it looks fixed from next version 1.25.4.
https://pypi.org/project/urllib3/
> Remove dependency on rfc3986 for URL parsing.

**Approach**
- modifying "urllib3==1.25.4" in src/azure-cli/requirements.py3.windows.txt
- then, building the MSI according here.
- install azure-cli using this MSI.

I tried this approach was successes, the issue has resolved.

**Question**
Could you fix it?

Kind Regards.

**Comment by yonzhan** [comment]
add to S176

**Comment by TakafumiSakai** [comment]
Can you please increase the priority for the customer's request?

**Comment by jiasli** [comment]
https://github.com/Azure/azure-cli/pull/16663 already fixed this issue:

https://github.com/Azure/azure-cli/blob/c9d47420c4c644099d18c4879bf203be23fd579b/src/azure-cli/requirements.py3.windows.txt#L131

Please upgrade to the latest version of Azure CLI: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
