### ISSUE TITLE
Don't use naïve datetime objects in CLI telemetry

### ISSUE THREAD

**Issue by christopher-o-toole** [Azure/azure-cli#15336]
**Describe the bug**

[`datatime.utcnow()`](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) returns a [naive datetime object](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects) instead of an aware current UTC datetime.    [`datetime.now(timezone.utc)`](https://docs.python.org/3.8/library/datetime.html#datetime.datetime.utcnow) should be used instead.

https://github.com/Azure/azure-cli/blob/9ee8122885d46818962d0dbcb47c2c1bbd5aacf2/src/azure-cli-core/azure/cli/core/telemetry.py#L181-L182

https://github.com/Azure/azure-cli/blob/9ee8122885d46818962d0dbcb47c2c1bbd5aacf2/src/azure-cli-core/azure/cli/core/telemetry.py#L245-L249

https://github.com/Azure/azure-cli/blob/9ee8122885d46818962d0dbcb47c2c1bbd5aacf2/src/azure-cli-core/azure/cli/core/telemetry.py#L276-L283

**To Reproduce**

Perform any action that creates a telemetry record.

**Expected behavior**

For times in CLI telemetry to be UTC aware.

**Environment summary**

Happens in all environments.

**Additional context**

For a discussion on why `datetime.datetime.utcnow()` does not contain timezone information, see this [StackOverflow question](https://stackoverflow.com/questions/2331592/why-does-datetime-datetime-utcnow-not-contain-timezone-information).

**Comment by yungezz** [comment]
hi @houk-ms could you pls take a look? thanks.

**Comment by houk-ms** [comment]
Yes, already sync it with @christopher-o-toole, will open a pr to fix it.

@fengzhou-msft Are there any considerations we didn't use aware datetime before?

**Comment by houk-ms** [comment]
Closed since pr is opened to fix it.
