### ISSUE TITLE
AZ webapp list --> error

### ISSUE THREAD

**Issue by PtrKllr** [Azure/azure-cli#15332]
## Describe the bug

**Command Name**
`az webapp list`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp list`

## Environment Summary
```
Linux-5.4.0-48-generic-x86_64-with-glibc2.29
Python 3.8.2
Shell: zsh

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
hi @PtrKllr could you pls try uninstall firstly, then install latest Azure CLI? This is an known issue in #14011

**Comment by PtrKllr** [comment]
Just reinstalled Azure CLI as it is mentioned above #14011 

Thanks!
