### ISSUE TITLE
Test Failing despite raising a CLI error

### ISSUE THREAD

**Issue by arde0708** [Azure/azure-cli#15338]
Context for the test : Create a db server. Attempt to recreate another server with the same name and it should throw a CLI error. I am trying to test the above behavior.

In the test, I am using the instructions here for validating the message returned in the CLI error : 
https://github.com/Azure/azure-cli/blob/dev/doc/authoring_tests.md#sample-9-assert-specific-error-occurs

I do see the CLI error message in the test output that I am raising in the code, but the test fails stating that CLI Error was not raised. Can someone help understand what is the issue here ?

Screenshot 1: Code that raises the error (which is also a part of the test output in Screenshot 2):
![image](https://user-images.githubusercontent.com/63367896/94498327-b5257400-01ae-11eb-8f15-5400629fd753.png)

Screenshot 2 : 
![image](https://user-images.githubusercontent.com/63367896/94498505-34b34300-01af-11eb-8aea-84854704e933.png)

Screenshot 3: Assertion in test.
![image](https://user-images.githubusercontent.com/63367896/94499156-cd968e00-01b0-11eb-9a45-0b304b37afe4.png)

Also, is there a way to debug tests ?

**Comment by yonzhan** [comment]
add to S177

**Comment by Juliehzl** [comment]
Hi @arde0708 , debugging test is similar with command. please add config as below and set break point at the position you want.
![image](https://user-images.githubusercontent.com/49508232/100328738-d4eae400-3007-11eb-9f89-d19773b28170.png)
 
If the exception is raised in validation, consider raising SystemExit.

If you still have the problem, feel free to find me for help.
