### ISSUE TITLE
--lb "" not working in az cli for Powershell

### ISSUE THREAD

**Issue by Kraftwerx** [Azure/azure-cli#15352]
While using either cloudshell or the CLI in any other bash session works, when running in Powershell, the command returns this:
az vmss create --name ... --lb ""
az vmss create: error: argument --load-balancer/--lb: expected one argument

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0408c294-207a-2b72-7b93-e09121602b75
* Version Independent ID: 852cb67b-70c6-b811-3b0a-5d5b84b8a911
* Content: [az vmss](https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az_vmss_create)
* Content Source: [latest/docs-ref-autogen/vmss.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/vmss.yml)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy could you pls share how to pass empty string?

**Comment by qwordy** [comment]
You can use `--lb '""'` in PowerShell.
https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md

**Comment by qwordy** [comment]
@kagbakpem Is your problem solved?

**Comment by qwordy** [comment]
If any problem, please open a new issue. Thanks.
