### ISSUE TITLE
az cosmosdb mongodb database throughput show/update does not work

### ISSUE THREAD

**Issue by MdeRhoter** [Azure/azure-cli#15365]
`az cosmosdb mongodb database throughput --resource-group rg --account-name accountname --name databasename --debug`

```
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/guid/resourceGroups/rg/providers/Microsoft.DocumentDB/databaseAccounts/accountname/mongodbDatabases/databasename/throughputSettings/default?api-version=2020-04-01 HTTP/1.1" 404 232
msrest.http_logger : Response status: 404
```
According to https://docs.microsoft.com/en-us/cli/azure/cosmosdb/mongodb/database/throughput?view=azure-cli-latest, it should work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33348034-21db-964e-935c-fd132af48a2b
* Version Independent ID: 29d8024d-3553-d381-e94f-fb1e7d0cfc9e
* Content: [az cosmosdb mongodb database throughput](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/mongodb/database/throughput?view=azure-cli-latest#az-cosmosdb-mongodb-database-throughput-update)
* Content Source: [latest/docs-ref-autogen/cosmosdb/mongodb/database/throughput.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cosmosdb/mongodb/database/throughput.yml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cosmosdb

**Comment by shurd** [comment]
The provided response error code or 404 indicates that one of the resources was not found. Please ensure the account exists in the provided subscription/resource group. Additionally ensure that database exists (and the casing is all correct) and ensure that the database is a shared throughput database. If the database is not shared throughput, there is no associated offer, so it is expected for a 404 error to return.

If you are still seeing errors after confirming, please share an activity id here or open a support request via the Azure portal with all details so we can look into your account and requests.
