### ISSUE TITLE
Webapp:az webapp config ssl import - not working 

### ISSUE THREAD

**Issue by amitpuri** [Azure/azure-cli#15368]
this command is not working, though I am able import certificate from Key vault manually and run next command az webapp config ssl bind to thumbprint.

It errors out as below error message 

This command is in preview. It may be changed/removed in a future release.
Unable to verify Key Vault permissions.
You may need to grant Microsoft.Azure.WebSites service principal the Secret:Get permission
Find more details here: https://azure.github.io/AppService/2016/05/24/Deploying-Azure-Web-App-Certificate-through-Key-Vault.html

Version Info
az --version azure-cli 2.12.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3f984d-0d48-e075-7e2f-2da5667b15cf
* Version Independent ID: 98e06d47-0ed4-4d8e-ccf5-d3a78e510539
* Content: [az webapp config ssl](https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/ssl.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config/ssl.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
cc @bim-msft for awareness

**Comment by panchagnula** [comment]
@amitpuri - for import from AKV to work the RP needs GET permissions on the AKV - which is what the error message is conveying.

**Comment by amitpuri** [comment]
@panchagnula What do you mean to say? Please read carefully my initial comment. So if it is a permission issue, it should not work manually. Can you list exact steps for az webapp config ssl import including prerequisite, Thanks

**Comment by mossywell** [comment]
@amitpuri Couple of things (assuming you are using Vault access policy, not RBAC):
1. I found that when using the CLI, the permissions need to be granted to "Microsoft Azure App Service", not yourself.
2. I think this is a bug in the CLI: you need to make sure that Microsoft Azure App Service has "get" on _Secret_ Permissions even if you are only using Certificates in the KV.

**Comment by panchagnula** [comment]
> @amitpuri Couple of things (assuming you are using Vault access policy, not RBAC):
> 
> 1. I found that when using the CLI, the permissions need to be granted to "Microsoft Azure App Service", not yourself.
> 2. I think this is a bug in the CLI: you need to make sure that Microsoft Azure App Service has "get" on _Secret_ Permissions even if you are only using Certificates in the KV.

CLI does not set any permissions on the customers AKV & hence throws the warning with the info on what access permissions are needed & set it themselves. the following CLI command can be used to set the right permissions az keyvault set-policy -n sisirap-KV-2 --secret-permissions get --spn SPAppId
