### ISSUE TITLE
azure-cli installation on SLES12SP4 fails - once again

### ISSUE THREAD

**Issue by tp199314** [Azure/azure-cli#15366]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Cannot install azure-cli on SLES 12 SP 4

**To Reproduce**
Do Steps 1 to 4 from https://docs.microsoft.com/de-de/cli/azure/install-azure-cli-zypper#install

sudo zypper install -y curl
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo zypper addrepo --name 'Azure CLI' --check https://packages.microsoft.com/yumrepos/azure-cli azure-cli
sudo zypper install --from azure-cli azure-cli

**Expected behavior**
azure-cli is installed.

**Environment summary**
SUSE Linux Enterprise Server 12 SP4 x86_64 (64-bit)
bash

**Additional context**
azmvbmt1ci:~ # sudo zypper install --from azure-cli azure-cli                                                     Refreshing service 'Advanced_Systems_Management_Module_x86_64'.
Refreshing service 'Containers_Module_x86_64'.
Refreshing service 'HPC_Module_x86_64'.
Refreshing service 'Legacy_Module_x86_64'.
Refreshing service 'Public_Cloud_Module_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Server_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Software_Development_Kit_x86_64'.
Refreshing service 'Toolchain_Module_x86_64'.
Refreshing service 'Web_and_Scripting_Module_x86_64'.
Loading repository data...
Warning: Repository 'Backports SLE-15-SP2 (standard)' appears to be outdated. Consider using a different mirror or server.
Reading installed packages...
Resolving package dependencies...

Problem: azure-cli-2.12.1-1.el7.x86_64 requires libpython3.6m.so.1.0()(64bit), but this requirement cannot be provided
  uninstallable providers: libpython3_6m1_0-3.6.10-lp152.4.3.1.x86_64[openSUSE_Leap_15.2_Update]
                   libpython3_6m1_0-3.6.10-lp152.4.6.2.x86_64[openSUSE_Leap_15.2_Update]
 Solution 1: Following actions will be done:
  install glibc-2.26-lp152.26.3.1.x86_64 (with vendor change)
    SUSE LLC <https://www.suse.com/>  -->  openSUSE
  install glibc-locale-2.26-lp152.26.3.1.x86_64 (with vendor change)
    SUSE LLC <https://www.suse.com/>  -->  openSUSE
  install nscd-2.26-lp152.26.3.1.x86_64 (with vendor change)
    SUSE LLC <https://www.suse.com/>  -->  openSUSE
 Solution 2: do not install azure-cli-2.12.1-1.el7.x86_64
 Solution 3: break azure-cli-2.12.1-1.el7.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/3/c] (c):

Solution 2 as mentioned on https://docs.microsoft.com/de-de/cli/azure/install-azure-cli-zypper#install Step 4 is no solution -> azure-cli will not be installed. Why should i install openSUSE packages, when using SLES?

I had these type of errors month ago. It is really frustrating, that azure-cli is not working on SLES. We need the for the Enhanced Monitoring Extension for SAP. 
Link to older issue: https://github.com/Azure/azure-cli/issues/9665

**Comment by tp199314** [comment]
Solution https://docs.microsoft.com/de-de/cli/azure/install-azure-cli-zypper#install-on-sles-12-or-other-systems-without-python-36 is not working too.

**Comment by yungezz** [comment]
thanks for reporting. @fengzhou-msft could you pls have a look? thanks

**Comment by fengzhou-msft** [comment]
We have a script to build python 3.6 from source, then download azure-cli and install without dependency. Please try:
`curl -sL https://azurecliprod.blob.core.windows.net/sles12_install.sh | sudo bash`

**Comment by fengzhou-msft** [comment]
@tp199314 are you able to give the above script a try?

**Comment by tp199314** [comment]
Script is working. Needed to remove azure-cli package before. It is possible to add a check for this?
Is this script a long-term solution or will it be replaced in the near future? maybe we will integrate this in some scripts.

**Comment by fengzhou-msft** [comment]
I have added a removal step in the script.

It is a long-term workaround as the default Python 3.4 on SLES12SP4 reached end-of-life and Azure CLI dropped support for it.
