### ISSUE TITLE
Command "az sf cluster node-type add" fails with unexpected error "list index out of range"

### ISSUE THREAD

**Issue by ptsapralis** [Azure/azure-cli#15378]
## Describe the bug

**Command Name**
`az sf cluster node-type add`

**Errors:**
```
list index out of range
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/servicefabric/custom.py, ln 765, in add_cluster_node_type
    _create_vmss(cmd, resource_group_name, cluster_name, cluster, node_type, durability_level, vm_password, vm_user_name, vm_sku, vm_tier, capacity)
cli/command_modules/servicefabric/custom.py, ln 793, in _create_vmss
    virtual_network = list(
IndexError: list index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sf cluster node-type add --capacity {} -c {} -g {} --node-type {} --vm-sku {} --vm-tier {} --verbose --subscription {} --vm-password {} --vm-user-name {} --durability-level {}`

## Expected Behavior

Add a new node type to an existing Azure Service Fabric Cluster.

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.5
Installer: HOMEBREW

azure-cli 2.12.1

```

**Comment by ptsapralis** [comment]
Same error occurs when using "az" on Ubuntu Linux 16.04 & Windows Subsystem for Linux (WSL) with Ubuntu 16.04 on Windows 10.

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
