### ISSUE TITLE
Improve the default help message

### ISSUE THREAD

**Issue by davenicoll** [Azure/azure-cli#15375]
**Is your feature request related to a problem? Please describe.**
Typing `az monitor` (or any incomplete command without `--help`) results in an unintuitive help message -
```
ArgumentParseError: the following arguments are required: _subcommand
Try this: 'az extension add --name anextension'
Still stuck? Run 'az monitor --help' to view all commands or go to 'https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest' to learn more
```

**Describe the solution you'd like**
Rather than showing "Still stuck? tack on --help", why not automatically tack on "--help" and show the useful help documentation (so that `az monitor` would should show `az monitor --help`). If there's a strong preference not to implement this, at least consider making it an az cli configuration option?

**Comment by yonzhan** [comment]
add to S177

**Comment by stewartadam** [comment]
+1, unless you've memorized the exact command invocation needed this necessitates you to re-run the same command and tack `--help` onto it, and likely more times if you're using nested subcommands like `az iot hub device-identity`. Adds so much more friction there it needs to be.

**Comment by jongio** [comment]
We should fix this.

I had a customer type in 

`az policy _subcommand`

because they thought that was missing.

**Comment by jiasli** [comment]
Tracked by #19592
