### ISSUE TITLE
[Docs] Improve formatting of 'pip install' README instructions

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-cli#1537]
Under the "Windows" section:
`Enable tab completion with source az.completion.sh.` - the "source" command is not available on Windows. 

The documentation should be updated with the correct steps to activate tab completion on windows.

**Comment by derekbekoe** [comment]
Tab completion is not available on Windows CMD.
In the README, the text that reads "Enable tab completion with source az.completion.sh" is not actually under the 'On Windows:' heading.

We can update the formatting to make this more clear.

**Comment by trondhindenes** [comment]
If you look at the structure of the proceeding sections, there's no way to tell that that's not part of the windows section.

**Comment by derekbekoe** [comment]
Agreed, it's not clear in the README.

**Comment by derekbekoe** [comment]
Changed the issue name to reflect this.
