### ISSUE TITLE
Firewall policy premium properties addition + Firewall sku tier addition

### ISSUE THREAD

**Issue by adgrieve** [Azure/azure-cli#15377]
**Resource Provider**
Azure Networking (Firewall)

**Description of Feature or Work Requested**
Add firewall policy premium properties
Add firewall option to chose tier (Standard/Premium)

**Minimum API Version Required**
2020-07-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/10780/
https://github.com/Azure/azure-rest-api-specs/pull/10929/

**Powershell Link**
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/746

**Target Date**
01/21/2021

**Comment by yonzhan** [comment]
Firewall policy

**Comment by haroldrandom** [comment]
Postpone by service team
