### ISSUE TITLE
az storage copy crashes: ValidationError: local variable 'service' referenced before assignment

### ISSUE THREAD

**Issue by Timost** [Azure/azure-cli#15379]
**Describe the bug**
When using the `az storage copy` command to move data from aws s3 to azure blob storage it crashes with:
`ValidationError: local variable 'service' referenced before assignment`. 
This happens only on the `2.12.1` release of azure cli, the same command works with azure-cli `2.11.1`
 ```
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f3007e8b730>, <function CLIQuery.handle_query_parameter at 0x7f3007e1f9d8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f3007abf9d8>, <function
 register_ids_argument.<locals>.parse_ids_arguments at 0x7f3007abfb70>]
This command is in preview. It may be changed/removed in a future release.
cli.azure.cli.core.azclierror : ValidationError: local variable 'service' referenced before assignment
ValidationError: local variable 'service' referenced before assignment 
```

**To Reproduce**
The command I run looks like this:
```
az storage copy -s 'https://<redacted>.s3.<redacted>.amazonaws.com/<redacted>/<redacted>' -d 'https://<redacted>.blob.core.windows.net/<redacted>/<redacted>/<redacted>/' --recursive
```

**Expected behavior**
The command does not crash and the data transfer proceeds.

**Environment summary**

Install Method: apt-get
CLI version: 2.12.1
OS version: Debian buster
Shell: zsh

**Additional context**
The command works properly using azure-cli `2.11.1` but fails with azure-cli `2.12.1`

**Comment by yonzhan** [comment]
add to S177

**Comment by tengl** [comment]
We have the same issue in Azure DevOps. This is quite serious, need a fix immediately if I can't find a different way to do what we want to do. 

Is there a way to specify version 2.11.1 in a release task?

**Comment by yonzhan** [comment]
Add @Juliehzl to help with

**Comment by Juliehzl** [comment]
Hi @Timost could you try with the artifact for the fix https://dev.azure.com/azure-sdk/public/_build/results?buildId=568322&view=artifacts&type=publishedArtifacts?

**Comment by Juliehzl** [comment]
Hi @tengl, we will try to fix it in next release, which will happen on next Tuesday. But for DevOps CLI, we will need to contact with DevOPs people for help.

**Comment by Timost** [comment]
Hi @Juliehzl I've managed to install the pypi artefact after some fiddling, but I still get the same error. I suspect the way I installed it might be the reason. What's the proper way install this new version of az-cli ?

What I've done:
1. Download the pypi artefact
2. create a venv somewhere
3. install the artefact in the venv using `pip install --find-links=~/Downloads/pypi azure-cli`
4. when I run `az --version` i get :
```
(.venv) ➜  test-az-cli .venv/bin/az --version
azure-cli                         2.13.0

core                              2.13.0
telemetry                          1.0.6

Extensions:
aks-preview                       0.4.62

Python location '/home/<redacted>/<redacted>/test-az-cli/.venv/bin/python3.6'
Extensions directory '/home/<redacted>/.azure/cliextensions'

Python (Linux) 3.6.12 (default, Sep  1 2020, 16:32:53)
[GCC 10.2.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

**Comment by tengl** [comment]
Thanks @Juliehzl 
I filed a bug report for Azure DevOps asking them to downgrade until it is fixed. 
https://developercommunity.visualstudio.com/content/problem/1214135/az-storage-copy-crashes-validationerror-local-vari.html

**Comment by Juliehzl** [comment]
Hi @Timost, could you try with edge builds here https://github.com/Azure/azure-cli#edge-builds? I am not sure if you install the new package.

**Comment by Timost** [comment]
Hi @Juliehzl I just tested the edge-build and it seems the issue is fixed. Everything worked as expected.

**Comment by tengl** [comment]
Hi @Juliehzl 
There seems to be a regression here. Got the error again on Azure DevOps with Azure CLI 2.19.1.

```log
2021-02-17T08:28:26.6299733Z [command]"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\azureclitaskscript1613550411195.ps1'"
2021-02-17T08:28:40.7148788Z WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
2021-02-17T08:28:40.7151745Z ERROR: local variable 'service' referenced before assignment
```

**Comment by tengl** [comment]
I created a new issue.
