### ISSUE TITLE
Failure creating AKS with Windows Nodes

### ISSUE THREAD

**Issue by WAftring** [Azure/azure-cli#15371]
## Describe the bug

**Command Name**
`az aks create`

Creating AKS with Windows nodes per [Creating AKS with Windows nodes per https://docs.microsoft.com/en-us/azure/aks/windows-container-cli](https://docs.microsoft.com/en-us/azure/aks/windows-container-cli).

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --enable-addons {} --generate-ssh-keys --windows-admin-password {} --windows-admin-username {} --vm-set-type {} --network-plugin {}`

## Environment Summary
```
Linux-4.15.0-1095-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.12.0 *

Extensions:
ai-examples 0.2.3

```

**Comment by yonzhan** [comment]
AKS

**Comment by jluk** [comment]
@yonzhan this is a specific error to cloudshell trying to access the managed identity

**Comment by yungezz** [comment]
hi @WAftring could you pls try `az login` to workaround? this is a known cloudshell issue #11749

**Comment by WAftring** [comment]
@yungezz The az login workaround no longer reproduces the issue

**Comment by maertendMSFT** [comment]
@WAftring , are you still seeing this issue?  If no, please close :)
