### ISSUE TITLE
Add the az login --scope parameter

### ISSUE THREAD

**Issue by oliviercastonguay** [Azure/azure-cli#15389]
**Is your feature request related to a problem? Please describe.**
We are using the Windows Task Scheduled to automate the execution of some powershell scripts that use the az login command.  Sometimes, we only require read-only access so we login using a read-only account.  Sometimes, write access are necessary.  The issue is that since the session scope is the same on any powershell sessions, if the two tasks run one after the other, it makes the first script crash.  

**Describe the solution you'd like**
Having the possibility to specify the scope of the az login command similar to the [Connect-AzAccount -Scope](https://docs.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-4.7.0) command.  It would then be able to run the two Powershell sessions with two different user context at the same time without having any impact on each of the scripts.

**Describe alternatives you've considered**
At the moment, we plan our scheduled tasks in order for them to never be executed at the same time if the context of the two scripts are different are might impact one another.

**Comment by yonzhan** [comment]
login

**Comment by jiasli** [comment]
Azure CLI is only a native `python.exe` application, so `Connect-AzAccount -Scope` which is backed by PowerShell is not a possible solution in Azure CLI.

There is a similar environment variable `AZURE_CONFIG_DIR` you can use for [concurrent builds](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#concurrent-builds). You may set it for different Azure CLI scripts and these scripts will  run with their own "context".
