### ISSUE TITLE
for `az keyvault certificate list`, `--maxresults` can't be set higher than 25 results

### ISSUE THREAD

**Issue by bbkane** [Azure/azure-cli#15382]
**Describe the bug**

I need to be able to enumerate all of my certificates in a keyvault. There exists a parameter, `--maxresults`,  that shows an error if set higher than 25. This severely reduces the usefulness of this command - I need to be able to see the certs I have.

**To Reproduce**

```
$ az keyvault certificate list --maxresults 30 --vault-name test
Parameter 'maxresults' must be equal to or less than 25.
```

**Expected behavior**

I should be able to set `--maxresults` larger than 25 to be able to enumerate all of my certificates. 

Or, similar to [the REST API](https://docs.microsoft.com/en-us/rest/api/keyvault/getcertificates/getcertificates), maybe add a `nextLink` or `token` result so I can get the next set of results ( something like `az keyvault certificate list --nextLink aAcxe...`

**Environment summary**

Mac OS, but this is a cross-version limitation.

**Additional context**

It looks like this behaviour was created almost a year ago in https://github.com/Azure/azure-cli/pull/11531 .

**Comment by yonzhan** [comment]
keyvault

**Comment by bim-msft** [comment]
`25` is a limitation from api definition. If you want to list all certificates, just use `az keyvault certificate list` without `--maxresults`.

**Comment by bim-msft** [comment]
> Or, similar to the REST API, maybe add a nextLink or token result so I can get the next set of results ( something like az keyvault certificate list --nextLink aAcxe...

This is quite a good suggestion, we will consider this, thanks!

**Comment by bbkane** [comment]
> For now, the CLI can only return the first page

Only returning the first page of results means I can't count on this command to give me the information I need. If I want to list all the certificates and their tags and such, I'll need to write a script with the REST API or some language library directly.

Thank you for considering this!
Ben

**Comment by bbkane** [comment]
I've created https://github.com/bbkane/kvcrutch to give me this functionality. Feel free to take from my implementation

**Comment by jaceks2106** [comment]
> @bbkane `25` is a limitation from api definition. If you want to list all certificates, just use `az keyvault certificate list` without `--maxresults`.

Are you sure? According to the MSDN, maximum is 25. 
https://docs.microsoft.com/en-us/cli/azure/keyvault/certificate?view=azure-cli-latest#az_keyvault_certificate_list
![image](https://user-images.githubusercontent.com/17142439/104592801-0af32e80-566f-11eb-89ed-6c1448fb2fe6.png)

**Comment by bbkane** [comment]
@jaceks2106 , there can be multiple pages of results in a Key Vault. This command only lists the first page (with or without `--maxresults` with no indication that there might be pages of certificates.

**Comment by evelyn-ys** [comment]
@schaabs Can KeyVault Data Plane Python SDK support `pageNumber` or `nextLink` parameter for `get_keys`, `get_secrets` and `get_certificates` so that CX can get more than the first page?

**Comment by bbkane** [comment]
Was this fixed recently? I'm listing more than 25 certs now in my test KV!!

```bash
$ az keyvault certificate list --vault-name kvcreate-01-kv-dev-bbk --query '[*].name' --output tsv
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
```

**Comment by evelyn-ys** [comment]
Hi @bbkane, it's always supported to list all when no `--maxresults` given.

I thought you were blocked by listing by page and getting the next page😆
