### ISSUE TITLE
List available IPs inside a subnet

### ISSUE THREAD

**Issue by jkewley** [Azure/azure-cli#15380]
**Is your feature request related to a problem? Please describe.**
The CLI currently has a way to check for free IPs in a vnet by using `az network vnet list-available-ips`. This is very useful, but some enterprises have network architectures which would benefit from being able to specify a subnet qualifier. This was touched upon in #6876, but was closed after implementation of the vnet scope.

**Describe the solution you'd like**
I would like to see list-available-ips under `az network vnet subnet:`
```
az network vnet subnet list-available-ips 
                                   [--ids] #not sure if this is relevant
                                   [--name]
                                   [--vnet-name]
                                   [--resource-group]
                                   [--subscription]
```

This would behave as  `az network vnet list-available-ips` does, but the IPs would be in the address space of the given subnet.

**Describe alternatives you've considered**
Compare ips returned from the `az network vnet list-available-ips` command against the subnet's address space, but I don't think the command supports paging so this may not be an option.

**Comment by yonzhan** [comment]
feature request

**Comment by haroldrandom** [comment]
Dup with https://github.com/Azure/azure-cli/issues/6876

**Comment by jmorcar** [comment]
Any update? 

the command az network vnet list-available-ips only display 4 or 5 available ips but if you check in azure portal there is more than 500 ips available... Is there some command to list available ips in a array json or similar in a subnet?

**Comment by a-nldisr** [comment]
`az network vnet list |jq ".[].subnets[].addressPrefix"`

**Comment by yonzhan** [comment]
@necusjz  for awareness

**Comment by jsntcy** [comment]
Duplicated with #13853
