### ISSUE TITLE
'postgres flexible-server' can't create 'Burstable' instances

### ISSUE THREAD

**Issue by matticala** [Azure/azure-cli#15387]
## Describe the bug

**Command Name**
`az postgres flexible-server create`

**Errors:**
```
ValidationError: Incorrect value for --sku-name. Follow the convention Standard_{VM name}. Examples: Standard_D4s_v3
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az postgres flexible-server list-skus -l westeurope -o table`

| SKU | Tier | VCore | Memory | Max Disk | IOPS 
| --- | --- | --- | --- | --- | ---
| Standard_B1ms | Burstable | 1 | 2 | GiB | 640 
| Standard_B2s | Burstable | 2 | 4 | GiB | 1280 
| Standard_D2s_v3 | GeneralPurpose | 2 | 8 | GiB | 3200 
| Standard_D4s_v3 | GeneralPurpose | 4 | 16 | GiB | 6400 
| Standard_D8s_v3 | GeneralPurpose | 8 | 32 | GiB | 12800 
| Standard_D16s_v3 | GeneralPurpose | 16 | 64 | GiB | 18000 
| Standard_D32s_v3 | GeneralPurpose | 32 | 128 | GiB | 18000 
| Standard_D48s_v3 | GeneralPurpose | 48 | 192 | GiB | 18000 
| Standard_D64s_v3 | GeneralPurpose | 64 | 256 | GiB | 18000 
| Standard_E2s_v3 | MemoryOptimized | 2 | 16 | GiB | 3200 
| Standard_E4s_v3 | MemoryOptimized | 4 | 32 | GiB | 6400 
| Standard_E8s_v3 | MemoryOptimized | 8 | 64 | GiB | 12800 
| Standard_E16s_v3 | MemoryOptimized | 16 | 128 | GiB | 18000 
| Standard_E32s_v3 | MemoryOptimized | 32 | 256 | GiB | 18000 
| Standard_E48s_v3 | MemoryOptimized | 48 | 384 | GiB | 18000 
| Standard_E64s_v3 | MemoryOptimized | 64 | 432 | GiB | 18000 
- `az postgres flexible-server create --location westeurope --name {} --resource-group {} --admin-user {} --admin-password {} --tags {} --tier Burstable --sku-name Standard_B2s --storage-size {} --version {}`

## Expected Behavior

It should create a _PostgreSQL Burstable_ instance with the specified SKU name. If the `Burstable` tier is not available, it shouldn't even be mentioned or there should be a specific warning.

## Environment Summary
```
macOS-10.15.6-x86_64-i386-64bit
Python 3.8.5
Installer: HOMEBREW

azure-cli 2.12.1

```
## Additional Context

The validator

https://github.com/Azure/azure-cli/blob/d4930e4ba3bb2f74db29c58f74890f909c31d851/src/azure-cli/azure/cli/command_modules/rdbms/validators.py#L153

```python
        if len(ns.sku_name.split('_')) != 3:
            raise CLIError('Incorrect value for --sku-name. Follow the convention Standard_{VM name}. '
                           'Examples: Standard_D4s_v3')
        server_type, cpu, server_v3 = ns.sku_name.split('_')
        if server_type != 'Standard' or server_v3 != 'v3':
            raise CLIError('Incorrect value for --sku-name. Follow the convention Standard_{VM name}. '
                           'Examples: Standard_D4s_v3')
        if not re.match(r"^(D|E)\d+s$", cpu) or \
           (re.match(r"^(D|E)\d+s$", cpu) and int(cpu[1:-1]) not in [2, 4, 8, 16, 32, 48, 64]):
            raise CLIError('Incorrect value for --sku-name.  Follow the convention Standard_{VM name}. '
                           'Examples: Standard_D4s_v3. \nAllowed number of vCores: 2, 4, 8, 16, 32, 48, 64')
```

considers `Standard_B` SKUs **never** valid.

**Comment by yonzhan** [comment]
postgres

**Comment by rachel-msft** [comment]
Thanks for reaching out. We'll investigate this and get back to you.

**Comment by lfittl-msft** [comment]
@matteocalabro-tomtom Thanks for reporting this - we can reproduce this, and confirm this is a bug.

We'll work on fixing this & will update you here when its done.

**Comment by lfittl-msft** [comment]
@matteocalabro-tomtom FYI: The fix for this is scheduled to go out at the end of October - we will update the issue once a new CLI release is out that has the bugfix.

In the meantime, you should be able to workaround by using an ARM template for automation: https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/quickstart-create-server-arm-template?tabs=portal%2Cazure-portal

**Comment by RakeshMohanMSFT** [comment]
This is working now. Please upgrade to latest version of azure cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
