### ISSUE TITLE
Remove DNSProxyRequiredForNetworkRule in Azure Firewall and Azure Firewall Policy

### ISSUE THREAD

**Issue by b564518128** [Azure/azure-cli#15383]
**Resource Provider**
NRP (Azure Firewall)
NVFRP (Azure Firewall Policy)

**Description of Feature or Work Requested**

Remove a flag introduced with below requests
  - Remove `RequireProxyForNetworkRules` introduced in #13638
  - Remove `dns-require-proxy-for-network-rules` introduced in #13350

**Minimum API Version Required**

05-01-2020 (NFVRP)
No API requirement for NRP

**Swagger Link**

**Target Date**

10/21/2020

**Comment by yonzhan** [comment]
feature request

**Comment by haroldrandom** [comment]
@b564518128  Could you explain why remove those recently added arguments?

**Comment by b564518128** [comment]
@haroldrandom Sorry for the delayed response. I was oncall last week and did not have time to look at it. These recently added arguments are parts of a private review feature. After some internal discussion and customer feedback, we decide to make these arguments not configurable.

This is aligned with #15481 . But for Azure Firewall, I am not aware of new arguments to be added. I need to double check and will update the issue description if needed.
