### ISSUE TITLE
How to create rule with a very long list of match-value args?

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli#15384]
I'm attempting to create a custom WAF rule to block users outside of certain ranges of IP addresses. I have 300+ IP address blocks on that list. If I put all these as `match-value=xxx` into the list of arguments, cmd.exe fails to launch the command due to a very long command line (the length is limited to 2K, IIRC).

Is there a way to pass all arguments from the file? Or pass list of values from the file? Or somehow "append" to an existing custom rule? I can see in the Portal that conditions in WAF can use "AND" operator - is it available in CLI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec529414-05f9-fc44-5e4e-2614dea48da5
* Version Independent ID: 039649c2-3e28-5bd2-981a-aad808209ff5
* Content: [az cdn waf policy custom-rule](https://docs.microsoft.com/en-us/cli/azure/cdn/waf/policy/custom-rule?view=azure-cli-latest#az_cdn_waf_policy_custom_rule_set)
* Content Source: [latest/docs-ref-autogen/cdn/waf/policy/custom-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cdn/waf/policy/custom-rule.yml)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cdn

**Comment by wasker** [comment]
I'm pretty sure it's going to be the same problem with WAF for Azure Front Door as well.

**Comment by t-bzhan** [comment]
For the time being, a potential way to bypass the limitation is to use Bicep or ARM template: https://docs.microsoft.com/en-us/azure/templates/microsoft.cdn/cdnwebapplicationfirewallpolicies?tabs=json
