### ISSUE TITLE
CDN WAF IPRange validation is too strict

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli#15393]
**Describe the bug**

When overlapping IP ranges provided in WAF rule configuration, rule cannot be created.

**To Reproduce**

`az cdn waf policy custom-rule set --resource-group rg-name --policy-name somepolicyname --name rulename --action Block --priority 100 --match-condition match-variable=RemoteAddr operator=IPMatch negate=true match-value=123:45:6:7::8/64 match-value=123:45:6:7::9/64`

**Expected behavior**

Just create the rule. Yes, IP address ranges can overlap, but it's more expensive for users to figure out how to clean up this sort of data than for WAF to deal with that. Figuring out overlapping IP address ranges for both IPv4 and IPv6 in bulk data is not an easy task.

**Environment summary**

Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.12.1

Extensions:
aks-preview 0.4.63
front-door 1.0.9
resource-graph 1.1.0

**Additional context**

**Comment by yonzhan** [comment]
cdn

**Comment by t-bzhan** [comment]
The CLI for `az cdn waf ` has been deprecated:
![image](https://github.com/Azure/azure-cli/assets/61817681/8d0cd16e-5afd-4360-8861-d040786222e0)
