### ISSUE TITLE
Webapp:Setting deployment slot connection string from file doesn't work

### ISSUE THREAD

**Issue by kmadof** [Azure/azure-cli#15394]
**Describe the bug**
As it is mentioned [here](https://docs.microsoft.com/en-us/cli/azure/webapp/config/connection-string?view=azure-cli-latest#az_webapp_config_connection_string_set) for `az webapp config connection-string set ` I'm trying to set `slot-settings` from file
>

Space-separated slot connection-string in a format of either <name>=<value> or @<json_file>.

But without any effect. For more than a 15 minutes I haven't got any response from CLI. I had to break execution. After that I also checked connection string on the portal, but they haven't been updated.

**To Reproduce**
Run this command:
`az webapp config connection-string set --name hadar --resource-group TheCodeManual --slot-settings "@con.json"`
or this
`az webapp config connection-string set --name hadar --resource-group TheCodeManual --slot Slot-test --slot-settings "@con.json"`

with this file

```json
[
  {
    "name": "Deault",
    "slotSetting": false,
    "type": "SQLAzure",
    "value": "<RealConnectionString>"
  }
]

```

**Expected behavior**
I expect to be able to set slot connection string from file.

**Environment summary**
az --version
```
azure-cli                         2.12.0 *

core                              2.12.0 *
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\krzys\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal
```
$PSVersionTable.PSVersion
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  752
```
`[System.Environment]::OSVersion.Version`
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18363  0
```

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by btardif** [comment]
I think this is a dup of #15395
