### ISSUE TITLE
[az container create] ModuleNotFoundError: No module named azure.mgmt.network.v2018_08_01

### ISSUE THREAD

**Issue by mloskot** [Azure/azure-cli#15391]
## Describe the bug
**Command Name**

`az container create`

The problem happens in both cases
- creating a container in a new virtual network
- creating a container in an existing virtual network

**Errors:**
```
No module named 'azure.mgmt.network.v2018_08_01'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-tuw8_17y\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 654, in execute
cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
cli\core\commands\__init__.py, ln 711, in _run_job
Local\Temp\pip-unpacked-wheel-cpn0gwyu\six.py, ln 703, in reraise
cli\core\commands\__init__.py, ln 688, in _run_job
cli\core\commands\__init__.py, ln 325, in __call__
azure\cli\core\__init__.py, ln 784, in default_command_handler
cli\command_modules\container\custom.py, ln 190, in create_container
cli\command_modules\container\custom.py, ln 286, in _get_vnet_network_profile
azure\mgmt\network\_network_management_client.py, ln 5336, in subnets
ModuleNotFoundError: No module named 'azure.mgmt.network.v2018_08_01'
```

## To Reproduce:

```
az group create -n myResourceGroup -l uksouth
```

```
az container create  `
  --name appcontainer  `
  --resource-group myResourceGroup  `
  --image mcr.microsoft.com/azuredocs/aci-helloworld  `
  --vnet my-vnet  `
  --vnet-address-prefix 10.0.0.0/16  `
  --subnet my-subnet  `
  --subnet-address-prefix 10.0.0.0/24
```

## Environment Summary

```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI
azure-cli 2.12.1
PowerShell 7.1.0-preview.7
```
## Additional Context

This issue seems to be affecting Azure CLI only, as @duschmidt explained in https://github.com/Azure/azure-cli/issues/15372#issuecomment-701586346, as workaround, a network profile can be successfully created from portal.azure.com

This issue may be a duplicate of #15372 and #15334 

Interestingly, in June, user @gtonello confirmed in https://github.com/Azure/azure-cli/issues/13191#issuecomment-638388717 that the `az  container create` was successful, creating new virtual network and network profile.

Unfortunately, Azure PowerShell command `New-AzContainerGroup` can not be used as a workaround here as it does not offer options to specify VNET and subnet, see https://github.com/Azure/azure-powershell/issues/12218#issuecomment-702693058

**Comment by yonzhan** [comment]
container

**Comment by AKlaus** [comment]
Does it implicitly require a `Network Profile`?

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed. Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
