### ISSUE TITLE
az deployment group create issue

### ISSUE THREAD

**Issue by bengodeloson** [Azure/azure-cli#15396]
## Describe the bug

**Command Name**
`az deployment group create`

**Errors:**
```
ValidationError: Deployment failed. Correlation ID: 7d035b9b-3fd7-4432-9003-3377d6f51eb5. {
  "error": {
    "code": "DomainNameLabelMissing",
    "message": "The domain name label in the dnsSettings section of the public IP address simpleLinuxVMPublicIP is null or empty. If a dnsSettings section exists, its domain name label must not be null or empty.",
    "details": []
  }
}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az deployment group create --name {} --resource-group {} --template-file {} --parameters {} --parameters {} --parameters {} --parameters {}`

## Environment Summary
```
Linux-4.15.0-1095-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.12.0 *

Extensions:
ai-examples 0.2.3

```

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
@bengodeloson Hi, this issue seems to be because your ARM template does not set a domain name label for dnsSettings of public IP address `simpleLinuxVMPublicIP`. Do you have any questions about this?
