### ISSUE TITLE
az webapp deployment source config-zip  fails with decotator error

### ISSUE THREAD

**Issue by nmishr** [Azure/azure-cli#15390]
## Describe the bug

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip --src {} --name {} --resource-group {}`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
known issue in https://github.com/Azure/azure-cli/issues/14011. HI @nmishr this is due to package issue in Focal. Could you pls remove existing Azure CLI and install latest one via instruction in https://github.com/Azure/azure-cli/issues/14011? thanks.

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14011

**Comment by nmishr** [comment]
I'm using ubuntu on windows and the directions I followed to install are here:

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

Maybe an update to the docs for install should be a part of this as some users follow these directions for every machine they setup.

**Comment by fengzhou-msft** [comment]
Updated in the troubleshooting part: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#no-module-issue-on-ubuntu-2004-focalwsl
