### ISSUE TITLE
command: 'vm list' should show power state of VM (running, stopped, etc)

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#154]
This is the field people cares a lot, and trigger different actions based on it
xplat's list command retrieves it using "get" with "instanceView" option enabled. I highly recommend cli's list should do the same, also it makes script easier to write.
I would imagine script to start a fleet vm would be like following 

``` bash
az vm list-all --query "[?contains(powerState,'stopped')==`true`].name" -o tsv | xargs -I {} -P 10 az vm start --vm-name "{}" -g mygroup
```

**Comment by raags** [comment]
This is something that we need as well to be able to migrate from xplat to azure-cli. We can't generate inventory without the power status for a VM.

**Comment by yugangw-msft** [comment]
we probably can expose `--show-power-state`, so user can opt-in with the perf penalty

**Comment by iankesh** [comment]
Can anyone tell me what are all the power states for Azure VM.?

**Comment by yugangw-msft** [comment]
Here is the list, might not be very up to date: 
https://azure.github.io/azure-sdk-for-java/com/microsoft/azure/management/compute/PowerState.html
