### ISSUE TITLE
On Python 2, upgrading from 0.1.0b10 to 0.1.0b11 may cause 'KeyError: Azure' error

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1540]
On Python 2, it's recommended to upgrade with the `--ignore-installed` flag:
`pip install --upgrade --ignore-installed azure-cli`.

If the above isn't followed, KeyError may appear as pip fails to install 2 required files.
Add these manually with:
```
touch <path_to_site_packages>/azure/cli/__init__.py
touch <path_to_site_packages>/azure/cli/command_modules/__init__.py
```

<path_to_site_packages> is the path to the environment the CLI was installed into.
For example /usr/local/lib/python2.7/site-packages.

This is a one-time change.

Fresh installs are not affected.

---
More info:

Upgrading from the previous version of the CLI to this version breaks on Python 2.
It breaks because pip attempts to uninstall the old version first so https://github.com/Azure/azure-cli/issues/1406 occurs again.
Python 3 works because of implicit namespace package support.

**Comment by dtzar** [comment]
I believe I'm also experiencing this now after the upgrade.  I get this when I type az:
`Traceback (most recent call last):
  File "/usr/local/az/lib/python2.7/site.py", line 703, in <module>
    main()
  File "/usr/local/az/lib/python2.7/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/usr/local/az/lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/local/az/lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/local/az/lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyError: 'azure'`

Going through the install again also does not fix the problem.

**Comment by nzthiago** [comment]
If you have python3 and pip3 installed you might need to do this before it works:
sudo pip3 install --upgrade --no-deps --force-reinstall azure-cli

**Comment by derekbekoe** [comment]
@dtzar Running the following commands should resolve the issue.
```
touch /usr/local/lib/python2.7/site-packages/azure/cli/__init__.py
touch /usr/local/lib/python2.7/site-packages/azure/cli/command_modules/__init__.py
```

**Comment by dtzar** [comment]
@nzthiago pip3 wasn't installed, but I installed it and gave your command a try (with and without --upgrade).  Could not find a version that satisfies the requirement azure-cli (from versions: 0.1.0b4, 0.1.0b10, 0.1.0b9, 0.1.0b7, 0.1.0b8, 0.1.0b11, 0.1.0b11, 0.1.0b9, 0.1.0b10)

@derekbekoe touch does "touch: cannot touch ‘/usr/local/lib/python2.7/site-packages/azure/cli/__init__.py’: No such file or directory".
I initially installed Azure-Cli using `curl -L https://aka.ms/InstallAzureCli | bash` and installed into default directory option provided (/home/myusername/lib/azure-cli).  I tried this again to no avail.  When I try to run az from /home/myusername/lib/azure-cli/bin, I get `/usr/bin/python: No module named azure`

**Comment by derekbekoe** [comment]
@dtzar The error "Could not find a version that satisfies the requirement azure-cli" from pip usually means an old version of pip is installed. Run `pip --version` to confirm. The latest version is 9.0.1.

In https://github.com/Azure/azure-cli/issues/1540#issuecomment-267193426, the commands I provided were based off https://github.com/Azure/azure-cli/issues/1540#issuecomment-266916877 but it looks like those directories were deleted at some point so that's why that doesn't work.

Finally, the curl script is a good install option.
The correct `az` executable should be in `/home/myusername/bin` not `/home/myusername/lib/azure-cli/bin`.
So you can run it with `/home/myusername/bin/az` of if `/home/myusername/bin` is in your PATH, just `az`.

**Comment by dtzar** [comment]
I had the latest version as you mentioned of pip.  Why are the default installation directories not what is recommended? I installed via curl again to the directory you mentioned and still to no avail.  I'm going to just keep using the docker image.  If you want to live troubleshoot, feel free to reach out to me inside MSFT.

**Comment by derekbekoe** [comment]
Will do.

**Comment by derekbekoe** [comment]
Closed as the issue is marked as FAQ and it's documented in our install troubleshooting doc - https://github.com/Azure/azure-cli/blob/master/doc/install_troubleshooting.md#upgrade-from-010b10-causes-keyerror-azure-error.

**Comment by dtzar** [comment]
thanks to @brusmx I got this working via these commands:
touch /usr/local/az/lib/python2.7/site-packages/azure/cli/command_modules/__init__.py
touch /usr/local/az/lib/python2.7/site-packages/azure/cli/__init__.py

**Comment by brusMX** [comment]
Also, just to point out that the error @dtzar is running into is by installing the Az Cli in Windows 10 with Ubuntu bash through this command:

```
curl -L https://aka.ms/InstallAzureCli | bash
```
That command is actually setting the contents of the `python2.7/site-packages` within the `az` folder inside the `/usr/local` folder. Instead of using `/usr/local/lib/python2.7`

**Comment by derekbekoe** [comment]
@brusMX This is intended.
With the curl script, the CLI gets installed into its own virtual environment. This is so that our dependencies do not conflict with any other Python dependencies that are currently installed on the system.

In your case, the root of this virtualenv is `/usr/local/az`.

**Comment by derekbekoe** [comment]
Also, previously the default location of this virtualenv was `/usr/local/az` and now it is `~/lib/azure-cli`.

**Comment by brusMX** [comment]
I supposed so @derekbekoe 
What I intended to communicate is that it was unclear to determine the root of the virtualenv. Especially from what you just communicated, the last version of the code says `DEFAULT_INSTALL_DIR = os.path.expanduser(os.path.join('~', 'lib', 'azure-cli'))` and not really `/usr/local/az`

So if anybody else runs into this issue, they could realize that their virtualenv could be different.
