### ISSUE TITLE
`az login --identity` max retries exceeded. Connection timed out

### ISSUE THREAD

**Issue by joruales** [Azure/azure-cli#15401]
I have been seeing the following error since Oct 3rd as part of our deployment pipeline:

```
az login --identity
ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 110] Connection timed out',))

[...]
```

The same pipeline was working Oct 2nd. Has anyone seen a similar issue?

**Comment by yonzhan** [comment]
add to S177

**Comment by francoran** [comment]
we're totally blocked for 2 days now because of this

**Comment by tshaiman** [comment]
we are blocked 2 days as well

**Comment by shubham90** [comment]
Our deployments are also failing with the same error since last couple of days. Both az cli and azcopy cli are failing with the same error.

**Comment by joruales** [comment]
This is working again now (at least for our team)

**Comment by yonzhan** [comment]
The timeout error indicates the managed identity endpoint on the VM is not responding, so Azure CLI fails to retrieve an access token.
Please open a support ticket and check why the endpoint is not working.
