### ISSUE TITLE
public-network-enabled no longer supported

### ISSUE THREAD

**Issue by bsherwin** [Azure/azure-cli#15406]
The argument `--public-network-enabled` is not supported, but still listed in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az_acr_create)
* Content Source: [latest/docs-ref-autogen/acr.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/acr.yml)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by yugangw-msft** [comment]
@bsherwin 
It is supported and we don't have any plans of removing it.  Please try newer version of CLI or share how you installed the CLI

**Comment by bsherwin** [comment]
You are correct. I had updated my cli on windows but not on WSL2. I was out of sync.
