### ISSUE TITLE
Modify Azure Policy Scope

### ISSUE THREAD

**Issue by ROC38983** [Azure/azure-cli#15403]
[Enter feedback here]
I was looking at the _az policy assignment create_ and couldnt find a modify function to allow modification of existing
policy Scope definition.  This would be useful for allowing existing Azure policies that have a defined Scope, to modify the Scope to allow for gradual testing and deployment versus creating a new policy for each Scope.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c6760bb-c278-da56-a95c-4e82e221f1e8
* Version Independent ID: e25cbd2a-b415-214f-7d50-c403992c9361
* Content: [az policy assignment](https://docs.microsoft.com/en-us/cli/azure/policy/assignment?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/policy/assignment.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/policy/assignment.yml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S177

**Comment by zhoxing-ms** [comment]
@ROC38983 May I ask do you mean that you want CLI to support modifying the scope of policy assignment?
