### ISSUE TITLE
Issue with blob set-tier if closed parenthesis is in the blob name

### ISSUE THREAD

**Issue by 500InternalServerError** [Azure/azure-cli#15418]
**Describe the bug**
Attempted to set the tier on a blob and received the error listed below.  This appears to only occur with a closed parenthesis is in the name of the blob.  Interestingly, open parenthesis is fine.  Confirmed this command works for all of my other data.

On a separate note, files with this name uploaded and downloaded fine using upload-batch and download-batch.

PS C:\> az storage blob set-tier --container-name "$containerName" --name "(File).zip" --tier "Cool" --connection-string $azConnStr
.zip was unexpected at this time.
C:\>  "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\\..\python.exe" -IBm azure.cli storage blob set-tier --container-name CONTAINERNAME --name (File).zip --tier Cool --connection-string DefaultEndpointsProtocol=https;AccountName=MYACCTNAME;A
ccountKey=ACCOUNTKEY==;EndpointSuffix=ENDPOINT

**To Reproduce**

Running the set-tier command with the following name should reproduce this error easily.

az storage blob set-tier --container-name "$containerName" --name "(file).zip" --tier "Cool" --connection-string $azConnStr

**Expected behavior**

I would expect this command to set the tier appropriately without erroring.

**Environment summary**

Windows server 2012 R2 Standard

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\> az version
{
  "azure-cli": "2.12.0",
  "azure-cli-core": "2.12.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Additional context**

**Comment by 500InternalServerError** [comment]
Just to add, if I run the python command myself and qualify the file name with quotes it works.  I actually needed to add quotes for my connection string as well.

For example:
C:> "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\..\python.exe" -IBm azure.cli storage blob set-tier --container-name CONTAINERNAME --name "(File).zip" --tier Cool --connection-string "DefaultEndpointsProtocol=https;AccountName=MYACCTNAME;AccountKey=ACCOUNTKEY==;EndpointSuffix=ENDPOINT"

**Comment by yonzhan** [comment]
add to S177

**Comment by Juliehzl** [comment]
Hi @500InternalServerError , it is PowerShell issue. In Powershell, please try  `az storage blob set-tier --container-name "$containerName" --name """(File).zip""" --tier "Cool" --connection-string $azConnStr`.

Precious command should work in cmd.
