### ISSUE TITLE
webapp:az webapp config ssl upload should support app service plan in different resource group.

### ISSUE THREAD

**Issue by jayaakshayan** [Azure/azure-cli#15415]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**
Create app service plan and web app in different resourcegroup. Use the az webapp config ssl upload command to upload the ssl certificate. The command executes with out any error but the certificate will not be visible in the webapp --->

**Expected behavior**

**Comment by yonzhan** [comment]
webapp

**Comment by btardif** [comment]
@panchagnula is this something for @singlessis ?

**Comment by panchagnula** [comment]
For now @ThejaChoudary is doing the initial investigation not for Sofi.

**Comment by ThejaChoudary** [comment]
@jayaakshayan Unable to repro the issue. Can you please share more details to investigate further with using --debug with the command.
Thanks You!

**Comment by btardif** [comment]
@panchagnula this issue looks stale, we should close cc: @ThejaChoudary
