### ISSUE TITLE
az login error: Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443)

### ISSUE THREAD

**Issue by giri-teja** [Azure/azure-cli#15410]
Hi all,

i have azure sandbox which i got from my company, am trying to deploy simple spring boot application in azure so i have done configuration in my POM and installed CLI when i try to deploy my application from cmd i see one challenge on the command az login

C:\Users\C53101>az login
ValidationError: Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x046361B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

![Capture](https://user-images.githubusercontent.com/48361727/95196876-03eb9300-07d9-11eb-9b84-b70e4b3f0e8f.PNG)

Please help me to solve this

**Comment by yonzhan** [comment]
add to S177

**Comment by giri-teja** [comment]
@jiasli: any idea on this issue

**Comment by jiasli** [comment]
It is very likely that you are working in a private network which doesn't have access to https://login.microsoftonline.com/.

You may verify this by connecting to https://login.microsoftonline.com/ directly with Python.

```
>"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
...
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-j_stz1v3\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03EFA890>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

Please contact your administrator to make sure the Azure sandbox you are using has access to Azure endpoints like https://login.microsoftonline.com/. 

All endpoints Azure CLI uses for public cloud are listed at https://github.com/Azure/azure-cli/blob/bade99898a9ce6b321c53ef5be3633b1eedc508c/src/azure-cli-core/azure/cli/core/cloud.py#L367-L402

**Comment by yonzhan** [comment]
@giri-teja  any feedback for the above solution?

**Comment by mankuuuuu** [comment]
I removed auto generated values by WSL in /etc/resolv.conf and added google NS now it is able to resolve it.
```
# [network]
# generateResolvConf = false
nameserver 8.8.8.8
```

**Comment by dpotapovich** [comment]
> I removed auto generated values by WSL in /etc/resolv.conf and added google NS now it is able to resolve it.
> 
> ```
> # [network]
> # generateResolvConf = false
> nameserver 8.8.8.8
> ```

Hello, 

It is working for my WSL, great!!
