### ISSUE TITLE
webapp:az webapp up should use the free asp if it already exists instead of throwing error

### ISSUE THREAD

**Issue by nigarfin** [Azure/azure-cli#15413]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When I ran az webapp up, instead of using the free ASP already existing it tries to create a new one and that causes the command to fail and I’m suggested to use a different region/sku. Note- I didn’t even specific a region so customers at this point wouldn’t know what the command is or what to input.

![image](https://user-images.githubusercontent.com/37638436/95239231-810a0e80-07bf-11eb-874d-8ef27c1028c5.png)

**To Reproduce**
1. Create a free ASP with a hello world site
2. in a fresh folder, clone another hello world app and try to run 'az webapp up --sku F1 --name SomeUniqueName

**Expected behavior**
I expect 'az webapp up' to recognize that a free ASP already exists and deploy to that ASP instead of trying to create a new one and fail when no parameters about rg or asp are given. If the ASP already has >= 10 sites, it should fail, recommend I create a new ASP or suggest I include a ignore-limit flag to allow me to deploy to that same ASP.

**Environment summary**

Run on Windows through CMD. Python 3.

az --version:
azure-cli                          2.9.1 *

command-modules-nspkg              2.0.3
core                               2.9.1 *
nspkg                              3.0.4
telemetry                          1.0.4 *

Extensions:
db-up                             0.1.15

**Additional context**

**Comment by yonzhan** [comment]
webapp

**Comment by calvinsID** [comment]
Hey @nigarfin, was the first Free app you created (repro step 1) using CLI, specifically `az webapp up` with no resource group specified?

**Comment by nigarfin** [comment]
Correct.

**Comment by nigarfin** [comment]
Whoops - failed to tag you. @calvinsID . Correct :)

**Comment by calvinsID** [comment]
@nigarfin do you mind sharing the resource group name and appservice plan name of the first free app created, as well as the resource group name and appservice plan name you get when running the command the second time, with `--dryrun` param? I was unable to repro this using `az webapp up --name {name} --sku F1` twice on two different clones of the same codebase. However if I create the first free app with a custom resource group name, I can repro the error msg. This is expected, since I should pass the custom resource group name for the second run

**Comment by nigarfin** [comment]
It happened so long ago I'm just not sure which of the apps it relates to so I can't provide asp or rg name sadly. 

When you say it's not reproing. Just to confirm, you're working out of two different project folders right? Can you try using these python projects (https://docs.microsoft.com/en-us/samples/azure-samples/python-docs-hello-world/python-flask-sample-for-azure-app-service-linux/). I DOUBT it makes a different which runtime you're using but only thing I can thing of...

1. Clone python flask project. cd into folder, run az webapp up -n MyWebApp1 --sku F1
2. Go to a new folder. Clone python flask project. cd into folder, run az webapp up -n MyWebApp1 --sku F1

If so, not sure what other details I can provide. If it's working now that's great. Maybe a regression shipped that was later fixed.

**Comment by calvinsID** [comment]
Yup same repro steps, except for step 2 used a new webapp name. Must have been fixed in a later version
Thanks!

**Comment by nigarfin** [comment]
No problem! Thank you for investigating!
