### ISSUE TITLE
webapp: Change name assigned to app service managed certificates 

### ISSUE THREAD

**Issue by singlessis** [Azure/azure-cli#15421]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Free Certificates are named after their custom domain. This is causing issues with traffic manager domains, as multiple free certs cannot be issued to to the same domain. 

**To Reproduce**
Trying to create a two free certificates for the same domain will result in a naming conflict ARM error. 

**Expected behavior**
We need to change the name assigned to free certs, so that more than one can be issued to traffic manager domains in the same resource group. Maybe appending a number, or the site name, 

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
app service

**Comment by Kotasudhakarreddy** [comment]
@ThejaChoudary - please check
