### ISSUE TITLE
Unable to get the -d

### ISSUE THREAD

**Issue by SuperTonic09** [Azure/azure-cli#15422]
[Enter feedback here]
The following command: `az policy state list --policy-definition "$name"` returns null; while `az policy state list --query "[?policyDefinitionName=='$name']"` using the _same_ id value works, is it a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca46c96d-8c88-7c4a-d75f-1c6c45d0f75c
* Version Independent ID: 9b8bdef9-8f67-7e82-1ae8-9356b62e84b0
* Content: [az policy state](https://docs.microsoft.com/en-us/cli/azure/policy/state?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/policy/state.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/policy/state.yml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S177

**Comment by zhoxing-ms** [comment]
This is an issue related to the REST API : [listqueryresultsforpolicydefinition](https://docs.microsoft.com/en-us/rest/api/policy-insights/policystates/listqueryresultsforpolicydefinition)

When the request URL is `https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.PolicyInsights/policyStates/latest/queryResults?api-version=2019-10-01`, relevant data can be found

But no data was found when `https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/policyDefinitions/{policyDefinitionName}/providers/Microsoft.PolicyInsights/policyStates/latest/queryResults?api-version=2019-10-01` was requested

This needs to be investigated by the service team
**correlation-request-id: 677947d4-758c-431b-876a-7b7eea0a2680**

**Comment by kenieva** [comment]
Hi @SuperTonic09, I was not able to reproduce this issue on my side. Is the definition custom or built-in?
