### ISSUE TITLE
webapp:az webapp deployment error

### ISSUE THREAD

**Issue by keziashirazi98** [Azure/azure-cli#15427]
Hi All,

I am having trouble deploying new code to my web app in Azure. My app is up and running in azure, but when I make changes to the app's code and deploy it to Azure using the command `az webapp deployment source config-zip --name appname --resource-group resourcegroup --src .\out\out.zip`, it fails the first time I run the command with the output:

![image](https://user-images.githubusercontent.com/63583873/95311306-56828900-0885-11eb-92ee-fcbf3cdb7933.png)

Then if I run this exact command again, changing nothing, it passes.

What is very odd about this is that there are no logs or even any evidence at all that the first (failed) deployment happened in Azure - nothing in the Log Stream or the Deployment centre. They only shows the second (successful) deployment. Additionally, if I run the command  `az webapp log deployment show -n appname -g resourcegroup --deployment-id e482068e3bc049c59faf03c9c59da9f0 ` where the deployment Id is the Id of the deployment that failed, it returns this:

![image](https://user-images.githubusercontent.com/63583873/95310773-b462a100-0884-11eb-9297-796d3dcfecf6.png)

which suggests that the deployment cannot be found as if it didn't happen.

My code is setup so that when I push to GitLab, it uses this command to deploy the code to Azure. I would like to diagnose this problem to avoid constantly rerunning my pipelines in GitLab each time I make a change to deploy the code to Azure.

Please could anyone help me solve this issue?

**Comment by yonzhan** [comment]
webapp

**Comment by Kotasudhakarreddy** [comment]
@keziashirazi98 - could you execute the command with `--debug` and give the log here to look further.

**Comment by calvinsID** [comment]
@keziashirazi98 what is the runtime & os of the app you are deploying to?

**Comment by keziashirazi98** [comment]
@calvinsID .NETCore 3.1 and Linux 
@Kotasudhakarreddy sorry it only breaks intermittently, not every other time, so I haven't been able to make it error again yet

**Comment by calvinsID** [comment]
@keziashirazi98 thanks for the update. If webapp configs are updated right before the deployment, it could be possible that the configs haven't propagated yet and cause this issue

**Comment by keziashirazi98** [comment]
@calvinsID is this something I can do to mitigate this or should I leave this with you?

**Comment by btardif** [comment]
Looks like we have no-repro for this issue so closing the issue

**Comment by keziashirazi98** [comment]
We are still hitting this intermittently. Today I pushed a pipeline and hit the error again. Could this please stay open as a ticket? I would really like to find a solution

**Comment by keziashirazi98** [comment]
@calvinsID unfortunately the problem you proposed cannot be the issue as the latest deployment was done as the first time the web app was touched in ~10days and it failed first and then passed again like the first time the issue occurred.
