### ISSUE TITLE
aks install-cli command failed with permission denied error

### ISSUE THREAD

**Issue by manuvrat** [Azure/azure-cli#15432]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
[Errno 13] Permission denied: '/usr/local/bin/kubelogin'
Traceback (most recent call last):
az/lib/python3.6/shutil.py, ln 550, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/tmp/tmp5gc68lwg/bin/linux_amd64/kubelogin' -> '/usr/local/bin/kubelogin'

...

az/lib/python3.6/shutil.py, ln 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/kubelogin'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli --install-location={}`

## Environment Summary
```
Linux-4.15.0-1096-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.12.0 *

Extensions:
ai-examples 0.2.3

```

**Comment by bquantump** [comment]
@manuvrat If you do not have permission on that directory, unless you are running az as root, this is expected to fail. Can you give us more information on what is expected behavior here? Do you believe this directory does have correct permissions on it?

**Comment by yonzhan** [comment]
aks

**Comment by manuvrat** [comment]
i am not able to change permission on PermissionError: [Errno 13]
Permission denied: '/usr/local/bin/kubelogin'

**Comment by xuyae573** [comment]
I have use the below command to install kubectl, I think the official document is outdated
` az extension add --name aks-preview`

**Comment by navba-MSFT** [comment]
@manuvrat Apologies for the late reply. This is documented [here](https://docs.microsoft.com/en-gb/azure/cloud-shell/troubleshooting#user-permissions) if you do not have full access to the /usr/local/bin path.

You can try with the sudo az aks install-cli and check if that helps. Alternatively, You can follow the below to install in a different location (download to a specified path) in the home folder, for example:

**:~$ az aks install-cli --install-location mykubetools/kubectl1.19.1 --client-version 1.19.1 --kubelogin-install-location mykubetools/kubelogin

Downloading client to "mykubetools/kubectl1.19.1" from https://storage.googleapis.com/kubernetes-release/release/v1.19.1/bin/linux/amd64/kubectl
Please ensure that mykubetools is in your search PATH, so the kubectl1.19.1 command can be found.
Downloading client to "/tmp/tmps1qp6p1e/kubelogin.zip" from https://github.com/Azure/kubelogin/releases/download/v0.0.11/kubelogin.zip

Please ensure that mykubetools is in your search PATH, so the kubelogin command can be found.

**https://github.com/Azure:~$ ./mykubetools/kubectl1.19.1 version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Hope this helps.

**Comment by manuvrat** [comment]
Thank you.

**Comment by navba-MSFT** [comment]
@manuvrat Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
