### ISSUE TITLE
enable-bgp param in az network vpn-gateway update doesnt seem to be working

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#1543]
Setting this param to false doesnt disable BGP. The capability to disable BGP is not present in Powershell so i dont have something equivalent to compare.

I also learnt that BGP enable/disable is not configurable at the Gateway level. So, if possible, we should remove this parameter from the CLI command

**Comment by tjprescott** [comment]
enableBgp is a property on the VirtualNetworkGateway object. In PR #1539 I verified that setting to "false" didn't produce a change and corrected it. The `create` command will automatically assume you want to enable BGP if you supply BGP parameters. If you later want to disable it, you can do an update with `--enable-bgp false` and the object updates appropriately.
