### ISSUE TITLE
Azure NSG should accept a comma-separated list of single ports and/or port ranges

### ISSUE THREAD

**Issue by bikoboshi** [Azure/azure-cli#15439]
**Az Version**

**Describe the bug**
```
ValidationError: Security rule has invalid Port range. Value provided: 25,587,25028. Value should be an integer OR integer range with '-' delimiter. Valid range 0-65535.
```

**To Reproduce**
```
az network nsg rule create --resource-group RG --nsg-name NSG --name NAME --priority 123 --direction Outbound --access Allow --protocol TCP --source-address-prefixes VirtualNetwork --destination-address-prefixes Internet --destination-port-ranges 25,587,25028 --description 'xxx'
```

**Expected behavior**
From Azure Portal tooltip
> Provide a single port, such as 80; a port range, such as 1024-65535; or a comma-separated list of single ports and/or port ranges, such as 80,1024-65535. This specifies on which ports traffic will be allowed or denied by this rule. Provide an asterisk (*) to allow traffic on any port.

Azure Network Security Groups accepts a comma delimited list of integers or integer ranges.

**Environment summary**
Windows Subsystem for Linux; Bash
```
{
  "azure-cli": "2.12.1",
  "azure-cli-core": "2.12.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

**Comment by yonzhan** [comment]
add to S177

**Comment by Totorman** [comment]
Still not working in April 2022 ...

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
@Totorman, please try to use "space-separated", like: *--destination-port-range 500-1000 2000 3000*.

**Comment by Totorman** [comment]
OK, Thx. Trying this format tomorrow. I'll keep you informed here.

**Comment by ChrisJBurns** [comment]
This doesn't work for me.

```terminal
> az network nsg rule create --name whitelisted-ips \
--nsg-name [REDACTED] \
--priority 490 \
--resource-group [REDACTED] \
--access Allow \
--description "Only allows Whitelisted IPs" \
--destination-address-prefixes [REDACTED] \
--destination-port-ranges 80 443 \
--direction Inbound \
--protocol Tcp \
--source-address-prefixes [REDACTED] \
--source-port-ranges *

(SecurityRuleInvalidPortRange) Security rule has invalid Port range. Value provided: README.md. Value should be an integer OR integer range with '-' delimiter. Valid range 0-65535.
Code: SecurityRuleInvalidPortRange
Message: Security rule has invalid Port range. Value provided: README.md. Value should be an integer OR integer range with '-' delimiter. Valid range 0-65535.
```

## Az CLI Version
```terminal
> az version
{
  "azure-cli": "2.39.0",
  "azure-cli-core": "2.39.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

**Comment by ChrisJBurns** [comment]
Apologies, ignore me, turns out it's not an issue with `--destination-port-ranges`, it was because I was not wrapping the `--source-port-ranges` value in quotes. Doing this `--source-port-ranges "*"` instead of `--source-port-ranges *` stopped the error from happening.
