### ISSUE TITLE
az cosmosdb keys list --type connection-strings extracted string does not contain all the parameters one can get via the portal

### ISSUE THREAD

**Issue by vbrinza** [Azure/azure-cli#15430]
[Enter feedback here]

az cosmosdb keys list --type connection-strings extracted string does not contain all the parameters one can get via the portal
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37c3520b-e1ab-8090-9bdb-2506c18cf1aa
* Version Independent ID: d711595b-6162-6b8f-402b-257a7e6dda87
* Content: [az cosmosdb keys](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/keys?view=azure-cli-latest#az_cosmosdb_keys_list)
* Content Source: [latest/docs-ref-autogen/cosmosdb/keys.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cosmosdb/keys.yml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cosmosdb

**Comment by shurd** [comment]
Hi, can you confirm that you account is a Mongo DB version 3.6 account? If so, we have an update coming in the next month that will change this connection string to match what is in the portal.

**Comment by vbrinza** [comment]
Confirm

**Comment by MehaKaushik** [comment]
Just to update, the fix for this was checked in sometime back, unfortunately, we are still waiting for the deployments to take place. I am guessing, in the next couple of weeks, it should be live.

**Comment by shurd** [comment]
Hi, the new connection string should be returned now.
