### ISSUE TITLE
Update Azure Cli for subscription RP 

### ISSUE THREAD

**Issue by navysingla** [Azure/azure-cli#15436]
**Resource Provider**
Microsoft.Subscription

**Description of Feature or Work Requested**
We added new optional parameter - "ResellerId" in our alias PUT API, we want support for same in the Azure cli extension.

**Minimum API Version Required**
NA

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/subscription/resource-manager/Microsoft.Subscription/stable/2020-09-01/subscriptions.json

**Target Date**
As soon as possible, Ideally by 20th October

**Comment by yonzhan** [comment]
subscription

**Comment by yungezz** [comment]
hi @navysingla is this property available on Prod now for testing?

**Comment by navysingla** [comment]
@yungezz  Yes it is available in Prod for testing
