### ISSUE TITLE
webapp:az webapp traffic-routing set to slot that doesn't exist breaks webapp

### ISSUE THREAD

**Issue by LiquoriChris** [Azure/azure-cli#15448]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Experiencing an issue where using `az webapp traffic-routing set` to a slot that does not exist breaks the app service. The app service displays a "404 Website Not Found" until clearing the routing rules and routing back to production.

**To Reproduce**
Run: `az webapp traffic-routing set -g rgTest -n webapp --distribution tseting=100`. (tseting is spelled incorrectly. Should be testing).

```
[
  {
    "actionHostName": "<hostName>",
    "changeDecisionCallbackUrl": null,
    "changeIntervalInMinutes": null,
    "changeStep": null,
    "maxReroutePercentage": null,
    "minReroutePercentage": null,
    "name": "tseting ",
    "reroutePercentage": 100.0
  }
]
```

**Expected behavior**
When trying to route traffic to a different slot, if you specify a slot that does not exist, the behavior should be to throw an error. However, the command executes successfully on the non-existent slot and the app service throws a 404.

**Additional context**
Is this the expected behavior? The traffic will try to route to a slot that does not exist? 

Thanks for your help.

**Comment by yonzhan** [comment]
webapp

**Comment by btardif** [comment]
This is by-design.

Traffic routing rules belong to the production app. 

If there is a bug here, it should go to API to block creating a TIP rule against a slot that does not exist.

CLI will not do this validations on the client side.

**Comment by btardif** [comment]
We are tracking the API validation here: Bug 8579682: az webapp traffic-routing set to slot that doesn't exist breaks webapp
