### ISSUE TITLE
az cdn endpoint rule add is very particular with input validation and documentation is lacking

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli#15447]
I've spent 20 minutes trying to figure out that the *only* way to create cache bypass rule is to write the command like this:

`az cdn endpoint rule add --resource-group myrg --name mycdnendpoint --profile-name mycdnprofile --order 1 --rule-name "rulename" --match-variable "UrlPath" --match-values "/somevalue/" --operator BeginsWith --transform Lowercase --action-name "CacheExpiration" --cache-behavior Override --cache-duration 00:15:00`

If I use "URLPath" in match-variable, it doesn't work.

`az cdn endpoint rule add --resource-group myrg --name mycdnendpoint --profile-name mycdnprofile --order 1 --rule-name "rulename" --match-variable "URLPath" --match-values "/somevalue/" --operator BeginsWith --transform Lowercase --action-name "CacheExpiration" --cache-behavior Override --cache-duration 00:15:00`

If I use custom name in action-name, it doesn't work. If action-name must match specific set of names, these names should be enumerated in the documentation.

`az cdn endpoint rule add --resource-group myrg --name mycdnendpoint --profile-name mycdnprofile --order 1 --rule-name "rulename" --match-variable "UrlPath" --match-values "/somevalue/" --operator BeginsWith --transform Lowercase --action-name "myactionname" --cache-behavior Override --cache-duration 00:15:00`

If I omit leading zeros in cache-duration, validation also fails. Ironically, Azure Portal displays cache rules w/o leading zeros.

`az cdn endpoint rule add --resource-group myrg --name mycdnendpoint --profile-name mycdnprofile --order 1 --rule-name "rulename" --match-variable "UrlPath" --match-values "/somevalue/" --operator BeginsWith --transform Lowercase --action-name "CacheExpiration" --cache-behavior Override --cache-duration 0:15:0`

Why is "order" a required field, if you don't let me specify order out of sequence? Just figure out what is the next order going to be, when you're adding the rule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fef54fc4-b4a8-d366-40de-a0ae2586961d
* Version Independent ID: 1231852d-d3b4-9bcf-e9d4-ba12cffb7603
* Content: [az cdn endpoint rule](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint/rule?view=azure-cli-latest#az_cdn_endpoint_rule_add)
* Content Source: [latest/docs-ref-autogen/cdn/endpoint/rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cdn/endpoint/rule.yml)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cdn

**Comment by t-bzhan** [comment]
Hi @wasker , apologize for the inconvenience caused by some design flaws in the service model and the insufficient documentation. We have improved the command’s help output and added a relevant link to help customer to use it more easily. Hope this will reduce some of the confusion.

For your specific questions:
> If I use "URLPath" in match-variable, it doesn't work.
> 
> az cdn endpoint rule add --resource-group myrg --name mycdnendpoint --profile-name mycdnprofile --order 1 --rule-name "rulename" --match-variable "URLPath" --match-values "/somevalue/" --operator BeginsWith --transform Lowercase --action-name "CacheExpiration" --cache-behavior Override --cache-duration 00:15:00

That works now, at least in Az CLI 2.50.0 .

> If I use custom name in action-name, it doesn't work. If action-name must match specific set of names, these names should be enumerated in the documentation.
> 
> az cdn endpoint rule add --resource-group myrg --name mycdnendpoint --profile-name mycdnprofile --order 1 --rule-name "rulename" --match-variable "UrlPath" --match-values "/somevalue/" --operator BeginsWith --transform Lowercase --action-name "myactionname" --cache-behavior Override --cache-duration 00:15:00

We have called out this in the help text:
![image](https://github.com/Azure/azure-cli/assets/61817681/81fa4cbc-561c-49f4-a1f6-f2b6ca870fbe)

> If I omit leading zeros in cache-duration, validation also fails. Ironically, Azure Portal displays cache rules w/o leading zeros.
> 
> az cdn endpoint rule add --resource-group myrg --name mycdnendpoint --profile-name mycdnprofile --order 1 --rule-name "rulename" --match-variable "UrlPath" --match-values "/somevalue/" --operator BeginsWith --transform Lowercase --action-name "CacheExpiration" --cache-behavior Override --cache-duration 0:15:0

That is a restriction from the service side, service side use TimeSpan as the data type and it only allows the "[d.]hh:mm:ss" format, we've called this out in the help doc.

> Why is "order" a required field, if you don't let me specify order out of sequence? Just figure out what is the next order going to be, when you're adding the rule.

I think you are right on that, the order parameter is pointless, we will evaluate to see whether that could be improved in future releases
