### ISSUE TITLE
The enabe "--all" for all tables is not support.

### ISSUE THREAD

**Issue by xuegao0112** [Azure/azure-cli#15452]
Hi Team,
After using the second example"az monitor log-analytics workspace data-export create -g MyRG --workspace-name MyWS -n MyDataExport --destination {sa_id_1} --enable --all" I met this error:

ValidationError: You must provide a table or tables array 'TableNames' : ['SecurityEvent'] or ['Heartbeat', 'SecurityEvent'].

It looks like the "--all" parameter is not support for now. Can you please help update the document to let customers know it's not support?

In the meanwhile, even the name is export as "table", I can find tables in my storage account but instead "container". Will you change it as export to "container"?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01a69262-72bb-fef5-c77d-83846b77c38e
* Version Independent ID: d7d19c3d-7e73-7f64-31b3-331e7cf77216
* Content: [az monitor log-analytics workspace data-export](https://docs.microsoft.com/en-us/cli/azure/monitor/log-analytics/workspace/data-export?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/monitor/log-analytics/workspace/data-export.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/monitor/log-analytics/workspace/data-export.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S177

**Comment by xuegao0112** [comment]
Hi @yonzhan ,
Thanks for the help.
Actually I found it's only support for the 3 tables export.Seems like need to clarify in the document.

**Comment by etiennetremel** [comment]
It seems that the flag has been deprecated, see the [limitations section](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/logs-data-export?tabs=azure-cli#limitations):
> The --export-all-tables option in CLI and REST isn't supported and will be removed. You should provide the list of tables in export rules explicitly.

**Comment by jsntcy** [comment]
@kairu-ms, let's update the help for the command to make it clear.
![image](https://user-images.githubusercontent.com/16348853/107452555-60dec780-6b84-11eb-8e21-26e6a90e9dcc.png)

**Comment by kairu-ms** [comment]
> @kairu-ms, let's update the help for the command to make it clear.
> ![image](https://user-images.githubusercontent.com/16348853/107452555-60dec780-6b84-11eb-8e21-26e6a90e9dcc.png)

OK
