### ISSUE TITLE
ACR Build errors with python 3.9

### ISSUE THREAD

**Issue by accu-joeykarns** [Azure/azure-cli#15465]
## Describe the bug

**Command Name**
`az acr build`

**Errors:**
```
list index out of range
Traceback (most recent call last):
python3.9/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 579, in execute
    parsed_args = self.parser.parse_args(args)
python3.9/site-packages/knack/parser.py, ln 262, in parse_args
    return super(CLICommandParser, self).parse_args(args)
3.9/lib/python3.9/argparse.py, ln 1818, in parse_args
    args, argv = self.parse_known_args(args, namespace)
...
azure/cli/core/command_recommender.py, ln 162, in recommend_a_command
    normalized_parameters = self._normalize_parameters(parameters)
azure/cli/core/command_recommender.py, ln 244, in _normalize_parameters
    standard_form = sorted_options[0]
IndexError: list index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr build`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.9.0
Installer: HOMEBREW

azure-cli 2.12.1

Extensions:
aks-preview 0.4.61

```

**Comment by yonzhan** [comment]
acr

**Comment by yugangw-msft** [comment]
@accu-joeykarns, the stack provided doesn't contain the any frames coming from `acr`. Could you please cross check by running other command like `az group list`? This way we can first exclude installation related issues

**Comment by accu-joeykarns** [comment]
@yugangw-msft I noticed I was missing the directory param at the very end of the command I was running. Once added the functionality worked. However I was expecting a cleaner error message about missing the directory param.

Thanks

**Comment by fdiiallo** [comment]
@accu-joeykarns  , Could you provide your command, i am still facing the issue, 
here is my commnd 
`az acr build --image <image_name> --registry <registry_name> --subscription <subscription_name> --resourcegroup  <resourcegroup_name> --file <path_to_docker_file> .`

Thanks

**Comment by yugangw-msft** [comment]
@northtyphoon, this is regarding error message improvement,

> I noticed I was missing the directory param at the very end of the command I was running

**Comment by northtyphoon** [comment]
@yonzhan the above log shows cli argument parser throw error when parsing required positional parameter. Before if positional parameter is missing, CLI would point out the missing parameter. Is there any change in CLI argument parser? /cc: @yugangw-msft 

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/_params.py#L188

**Comment by yonzhan** [comment]
@jiasli to comment.

**Comment by jiasli** [comment]
I am able to repro with a pseudo command:

```
> az acr build --image test . --debug
Command arguments: ['acr', 'build', '--image', 'test', '.', '--debug']
...
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-c8n8j8wo\azure\cli\core\command_recommender.py", line 257, in _normalize_parameters
IndexError: list index out of range
```

The argument are received by Azure CLI correctly, and the failure happened in `azure/cli/core/command_recommender.py`. + @houk-ms to take a look.

**Comment by houk-ms** [comment]
This should be a problem in failure recommedation. The reason is the positional arguments are not properly dealt when parsing arguments for failure recommendation. I will open a pr to fix the issue.

**Comment by houk-ms** [comment]
Thanks everyone for the discussions. PR has been merged to fix the issue, I think we can close it now. @accu-joeykarns @northtyphoon

**Comment by northtyphoon** [comment]
Thank you @houk-ms
