### ISSUE TITLE
Add example to clarify --workspace-resource-id value for az aks enable-addons

### ISSUE THREAD

**Issue by elygre** [Azure/azure-cli#15475]
The `--workspace-resource-id` option is confusing, as is requires a full URL, and not a guid. https://github.com/Azure/azure-cli/issues/6949 discusses this issue in a different context.

Here, it would be useful to add an example that uses this parameter, along the lines of 

```
az aks enable-addons --addons monitoring \
--name AKS-CLUSTER \
--resource-group AKS-RESOURCEGROUP \
--workspace-resource-id /subscriptions/11112222-3333-4444-5555-666677778888/resourcegroups/WORKSPACE-RESOURCEGROUP/providers/microsoft.operationalinsights/workspaces/WORKSPACE-NAME
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_enable_addons)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/aks.yml)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
aks

**Comment by elygre** [comment]
This suggestion was to add an *example*, in the very useful "Examples" chapter at <https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-enable-addons-examples>. This has very specifically *not happened*. I can't see any reason for not doing this, but I guess you guys decide the quality of your own documentation.
