### ISSUE TITLE
'azure storage account show' vs 'azure storage account usage show'

### ISSUE THREAD

**Issue by seguler** [Azure/azure-cli#1548]
Hey Folks,

I was just discussing this with Johan in the bug bash. As a user, I would prefer that we always append after 'show' command with the properties/resources we want to show rather than having different usages such as 'azure storage account usage show'. It is not intuitive in my opinion. Can we simplify this to have 'show' right after 'azure storage account' for each command ?

Sercan

**Comment by tjprescott** [comment]
In the current version of the CLI, the command you are referring to is `az storage account show-usage`. When putting something in a subcategory would result in a category of 1 (as would be the case with `az storage account usage show`) we opt to move the command "up" one level with a hyphen.

Is that in line with your thinking?

**Comment by tjprescott** [comment]
No movement on this since it was created. Closing.
