### ISSUE TITLE
What query is `--custom` operating on? 

### ISSUE THREAD

**Issue by kingces95** [Azure/azure-cli#15484]
What query is `--custom` operating on? The `resource show` result?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76a8ad2-efd8-9e8a-9b2b-eebeb1e9d1d4
* Version Independent ID: 280b7ea9-eb6c-9601-464b-09bf8e0cff5d
* Content: [az resource](https://docs.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/resource.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/resource.yml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S178

**Comment by zhoxing-ms** [comment]
Hi @kingces95, many commands have `--custom` parameter, which command do you refer to?
If you are referring to `az resource wait`, then it's judgment condition is based on the attributes of resources, which can be viewed through the `az resource show` command

**Comment by zhoxing-ms** [comment]
It is repeated with #15489, so close this issue
