### ISSUE TITLE
Deprecate an existing parameter and add a new parameter for Firewall policy

### ISSUE THREAD

**Issue by tejasshah7** [Azure/azure-cli#15481]
**Resource Provider**
Network (NRP)

**Description of Feature or Work Requested**

Two things are needed.
1. Deprecate the optional parameter "--require-dns-proxy-for-network-rules" in the command "az network firewall policy create and update".

This was a preview feature and we are about to GA this end of this month and we would like to streamline the experience before that.

2. Add a new parameter named "translated-fqdn" to the command "az network firewall policy rule-collection-group collection add-nat-collection".
User should be able to provide EITHER "translated-address" or "translated-fqdn".

**Minimum API Version Required**
2020-07-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/11012

**Target Date**
End of October 2020

**Comment by yonzhan** [comment]
add to S178

**Comment by haroldrandom** [comment]
Align with https://github.com/Azure/azure-cli/issues/15383 ?

**Comment by b564518128** [comment]
@haroldrandom The first request is aligned with #15383 .

**Comment by tejasshah7** [comment]
@haroldrandom I didn't realize first part was already filed. As mentioned in comment above, yes that request is aligned.

**Comment by tejasshah7** [comment]
@yonzhan @haroldrandom what is the expected release for this?

**Comment by tejasshah7** [comment]
Here is Powershell PR for reference: https://github.com/Azure/azure-powershell/pull/13238

**Comment by yonzhan** [comment]
S178  https://github.com/Azure/azure-cli/milestone/96

**Comment by kairu-ms** [comment]
@tejasshah7 There's no Network API of version 2020-07-01 available in Python SDK.

**Comment by jsntcy** [comment]
@tejasshah7 , please help check when 07-01 can be merged into master branch in https://github.com/Azure/azure-rest-api-specs/tree/master/specification/network/resource-manager/Microsoft.Network/stable which is the prerequisite of SDK release.

**Comment by tejasshah7** [comment]
> @tejasshah7 , please help check when 07-01 can be merged into master branch in https://github.com/Azure/azure-rest-api-specs/tree/master/specification/network/resource-manager/Microsoft.Network/stable which is the prerequisite of SDK release.

@kairu-ms the SDK for 07-01 is now released.
