### ISSUE TITLE
azure-cli-core has hard dependency on previous version of azure-mgmt-resource

### ISSUE THREAD

**Issue by fhoy** [Azure/azure-cli#15496]
**Describe the bug**
We use the `azure-cli-core` package to utilize CLI auth-mechanisms in some infrastructure deployment scripts, and some of that infrastructure is deployed using the `azure-mgmt-resource` package. After having upgraded the latter to its newest version, 15.0.0, we discovered that `azure-cli-core` has a hard dependency on `azure-mgmt-resource` 10.2.0. Since it does not seem like `azure-cli-core` actually uses much of `azure-mgmt-resource`, this version mismatch has not actually caused any problems for us yet, but with the [new dependency resolver](https://discuss.python.org/t/announcement-pip-20-2-release/4863) coming in `pip`, this conflict can not be ignored as easily. Does `azure-cli-core` _really_ need to depend on `azure-mgmt-resource`? A cursory examination turned up use of an enum from the latter, which I would assume could easily be copied, but I may certainly have missed something.

**To Reproduce**
Include latest versions of `azure-cli-core` (2.12.1) and `azure-mgmt-resource` (15.0.0) in a `setup.py` and run `pip install . --use-feature=2020-resolver`.

**Expected behavior**
No dependency conflict.

**Environment summary**
Tested with `pip` on Ubuntu 18.04.1.

**Additional context**
n/a

**Comment by jiasli** [comment]
`azure-cli-core` Azure CLI does rely on `azure-mgmt-resource` to do tenant and subscription discovery:

https://github.com/Azure/azure-cli/blob/6f0deecfa44ade0318e01dce45f97b1c8d768a6b/src/azure-cli-core/azure/cli/core/_profile.py#L808-L811

I am also able to repro 

```
> pip install azure-cli-core==2.12.1 azure-mgmt-resource==15.0.0 --use-feature=2020-resolver
...
ERROR: Cannot install azure-mgmt-resource==15.0.0 and azure-cli-core 2.12.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested azure-mgmt-resource==15.0.0
    azure-cli-core 2.12.1 depends on azure-mgmt-resource==10.2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

Let's keep an eye on how `pip` will do in the future for `2020-resolver`. We will consider bumping the version of `azure-mgmt-resource` to the latest version if that is necessary. + @zhoxing-ms

**Comment by jsntcy** [comment]
We'll plan to bump the version `azure-mgmt-resource` to the latest version next sprint (11/17).

**Comment by glaubitz** [comment]
This bug also causes issues for Linux distribution packagers which are now stuck with an old version of ```azure-mgmt-resource``` as Linux distributions usually don't allow shipping multiple versions of the same package in one repository.

This should definitely get fixed for the next release.

**Comment by mike-edmonds** [comment]
As of pip 20.3.0+ this is an error that can't be avoided when trying to explicitly install azure-mgmt-resource==15.0.0 w/ the latest azure-cli-core.
downgrading azure-mgmt-resource 2 releases is not ideal.
downgrading pip 2 releases is not ideal.

**Comment by jiasli** [comment]
The latest Azure CLI has removed hard dependency on `azure-cli-core` by vendoring `azure-cli-core` (https://github.com/Azure/azure-cli/pull/15711). Please let us know if it works for you. Thanks.

**Comment by glaubitz** [comment]
Not sure how this resolves the issue. This is just papering the issue over, the problem still remains.

Also, we can't use vendoring in distributions for security reasons.

**Comment by jiasli** [comment]
There are some outstanding breaking changes between `azure-mgmt-resource` 10.2.0 and 15.0.0. While we are actively working on migrating from `azure-mgmt-resource` 10.2.0 to15.0.0, given the amount of dependency on `azure-mgmt-resource`, it is a really huge task to accomplish.

That's why we only vendored `subscriptions` module from `azure-mgmt-resource` as a temporary workaround to satisfy the needs from `azure-cli-core`. Once other command modules have been migrated to use Track 2 SDK, `azure-cli-core` will depend on `azure-mgmt-resource` again.

Thanks for understanding.

**Comment by glaubitz** [comment]
I understand the huge work involved and I don't mean to put any pressure here. I just think that closing this bug report is misleading as the underlying problem still remains.

I think I will use the vendored version for the time being so we can unbreak ```azure-cli``` in our rolling release distribution Tumbleweed, so thanks for the workaround.

But i think you should keep the bug open as long ```azure-cli``` hasn't been ported to the new version of ```azure-mgmt-resource```.

**Comment by glaubitz** [comment]
I think that was fixed here: https://github.com/Azure/azure-cli/commit/4a5d74215d5d1566f839c2d11fd360d300f56b62

`azure-cli` depends on `azure-mgmt-resource` 18.0.0 now. So this issue can be closed.
