### ISSUE TITLE
az storage blob list gives `TypeError: 'NoneType' object is not iterable`

### ISSUE THREAD

**Issue by timtylin** [Azure/azure-cli#15495]
## Describe the bug

**Command Name**
`az storage blob list`

**Errors:**
```
'NoneType' object is not iterable
Traceback (most recent call last):
lib/python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 553, in execute
    self.commands_loader.load_arguments(command)
site-packages/azure/cli/core/__init__.py, ln 479, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
azure/cli/command_modules/storage/__init__.py, ln 36, in load_arguments
    load_arguments(self, command)
azure/cli/command_modules/storage/_params.py, ln 567, in load_arguments
    "Options include: {}. Can be combined.".format(get_include_help_string(t_blob_include)),
azure/cli/command_modules/storage/_validators.py, ln 589, in get_include_help_string
    for include in include_list:
TypeError: 'NoneType' object is not iterable
```

## To Reproduce:

1. (do `az login` via service principal: `az login --service-principal -u [REDACTED] --tenant [REDACTED] -p [REDACTED]`)
2. `az storage blob list --account-name [REDACTED] --auth-mode login --container-name [REDACTED]`

## Expected Behavior

Prints out list of objects inside the blob storage container

**EDIT**: the container is actually empty, but I expected the azure cli to tell me it's empty instead of throwing an exception

## Environment Summary
```
(Amazon Linux 2, x86, latest as of 2020-10-12)
Linux-4.14.193-149.317.amzn2.x86_64-x86_64-with-glibc2.2.5
Python 3.7.9
Installer: RPM

azure-cli 2.12.1
```
## Additional Context

Azure CLI installed via the circumvented method under Amazon Linux 2:

1. Setup Microsoft RPM repo and keys
2. `sudo yum install python3-libs yum-utils`
3. `sudo yumdownloader azure-cli`
4. `sudo rpm -ivh --nodeps azure-cli-*.rpm`

**Comment by yonzhan** [comment]
add to S178

**Comment by timtylin** [comment]
I've since found out that the container is actually empty, but I still expected the cli to tell me it's empty instead of throwing an exception.

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14287

**Comment by Juliehzl** [comment]
Hi @timtylin , could you try again? The None Type error should already be fixed. But could you show me your `azure-multiapi-storage` package version?
