### ISSUE TITLE
Get Effective Routes CLI not sending resource type and resource URI in request

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#15499]
In ICM https://portal.microsofticm.com/imp/v3/incidents/details/206126962/home, customer is using CLI for Get Effective Routes but the request being sent to Nrp is incorrect.
 
PS /home/vladimir> az network vhub get-effective-routes --resource-type RouteTable --resource-id /subscriptions/b2ae6fcd-b251-454e-af82-7ef05907a3dc/resourceGroups/VirtualWAN-RG/providers/Microsoft.Network/virtualHubs/NorthCentral-VHub/hubRouteTables/default  -n NorthCentral-VHub --resource-group virtualwan-rg
 
Request Received :
POST https://northcentralus.network.azure.com:30036/ef1ef5e3-b77b-41c7-8084-625fa097d749/132439549398969306/subscriptions/b2ae6fcd-b251-454e-af82-7ef05907a3dc/resourceGroups/VirtualWAN-RG/providers/Microsoft.Network/virtualHubs/NorthCentral-VHub/effectiveRoutes?api-version=2020-04-01
…
Referer: https://management.azure.com/subscriptions/b2ae6fcd-b251-454e-af82-7ef05907a3dc/resourceGroups/VirtualWAN-RG/providers/Microsoft.Network/virtualHubs/NorthCentral-VHub/effectiveRoutes?api-version=2020-04-01 User-Agent: Mozilla/5.0,(Windows NT 10.0; Win64; x64),AppleWebKit/537.36,(KHTML, like Gecko),Chrome/85.0.4183.121,Safari/537.36 Content-Length: 2 Content-Type: application/json {} --> Empty
 
Logs : https://jarvis-west.dc.ad.msft.net/F29AC501

**Comment by yonzhan** [comment]
add to S177

**Comment by 00Kai0** [comment]
Fix at https://github.com/Azure/azure-cli-extensions/pull/3555

**Comment by 00Kai0** [comment]
PR merged
