### ISSUE TITLE
Error running `az network public-ip` commands

### ISSUE THREAD

**Issue by sveinung-r** [Azure/azure-cli#15492]
## Describe the bug

**Command Name**
`az network public-ip list`

**Errors:**
```
ipv4
Traceback (most recent call last):
network/v2020_05_01/models/_network_management_client_enums.py, ln 24, in __getattr__
    return cls._member_map_[name.upper()]
KeyError: 'IPV4'

...

network/v2020_05_01/models/_network_management_client_enums.py, ln 26, in __getattr__
    raise AttributeError(name)
AttributeError: ipv4
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network public-ip list`

## Environment Summary
```
Linux-5.8.0-2-amd64-x86_64-with-glibc2.29
Python 3.8.6
Installer: PIP

azure-cli 2.11.1 *

Extensions:
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
add to S178

**Comment by haroldrandom** [comment]
@sveinung-r Do you run it with additional arguments? I ran it without any arguments and it works as expected.

**Comment by haroldrandom** [comment]
Closed as inactive
