### ISSUE TITLE
not able to delete group (az group delete --name) after deleting first storage

### ISSUE THREAD

**Issue by bellens99** [Azure/azure-cli#15491]
I was deleting all my groups and deleted the storage before the webservice. Afterwards I tried to delete the webservice (group) and it generates an error.
## Describe the bug

**Command Name**
`az group delete`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group delete --name {}`

## Environment Summary
```
Linux-4.15.0-1096-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.12.0 *

Extensions:
ai-examples 0.2.3

```

**Comment by yonzhan** [comment]
add to S178

**Comment by zhoxing-ms** [comment]
Hi @bellens99  Sorry, I can't reproduce this issue. May I ask what is the specific error message?

**Comment by bellens99** [comment]
Hi XZ,

It’s already a long time ago and I already found a workaround so it can be considered solved.
It had to do with the order of deleting of things as the title indicates.

Please close the issue.

Thx. Boris
