### ISSUE TITLE
`az login -u <username> -p <password>` does not work if <password> starts with a hyphen

### ISSUE THREAD

**Issue by jpbufe3** [Azure/azure-cli#15493]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When attempting to log in and specifying the `-p` parameter, the CLI is unable to parse the password argument if it starts with a hyphen character.

**To Reproduce**
```
az login -u user -p "-VerySecret"
>ArgumentParseError: argument --password/-p: expected one argument
Try this: 'az login --service-principal -u http://azure-cli-2016-08-05-14-31-15 -p VerySecret --tenant contoso.onmicrosoft.com'
Still stuck? Run 'az login --help' to view all commands or go to 'https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest' to learn more
```

Note - this fails with or without quotes around the argument (tried both single and double quotes as well)

**Expected behavior**
The parser should accept the argument.

**Environment summary**
azure-cli                         2.12.1
core                              2.12.1
telemetry                          1.0.6
Extensions:
azure-devops                      0.18.0
xsignextension                     0.0.1
Python location '/usr/local/Cellar/azure-cli/2.12.1_1/libexec/bin/python'
Python (Darwin) 3.9.0 (default, Oct  6 2020, 04:17:54) 
[Clang 12.0.0 (clang-1200.0.32.2)]

MacOS 10.15.6
zsh 5.7.1 (x86_64-apple-darwin19.0)

**Additional context**

**Comment by yonzhan** [comment]
add to S178

**Comment by zawachte-msft** [comment]
Hit this today. 

Did 
```
ad sp create-for-rbac
```

And got a client secret which started with a hyphen.

Caused
```
az login --service-principal -u <CLIENT_ID> -p <CLIENT_SECRET_WITH_HYPHEN> --tenant <TENANT_ID>
```

To fail.

**Comment by jiasli** [comment]
This is the same issue as #7054, #10692. `--password="-VerySecret"` should work.

I will change the password generating behavior so that no password with leading dash will be generated.

**Comment by jiasli** [comment]
This is the same issue as #7054, #10692. `--password="-VerySecret"` should work.

**Comment by jiasli** [comment]
@zawachte-msft, which version of Azure CLI you are using (`az --version`)? 

We have explicitly made the first character to be alphanumeric to avoid argument parsing issues. 

https://github.com/Azure/azure-cli/blob/11347b73999dc9b9d1c6f924fb42e3d20b34a767/src/azure-cli/azure/cli/command_modules/role/custom.py#L1847-L1848

https://github.com/Azure/azure-cli/blob/11347b73999dc9b9d1c6f924fb42e3d20b34a767/src/azure-cli/azure/cli/command_modules/role/custom.py#L1864

**Comment by zawachte-msft** [comment]
ah now that you mention it, I realize that the spn was generated from either az powershell or the azure sdk for dotnet, not azcli. 

Will need to get more details on that. @mattatmsft let's sync about this.

thanks for the tip. I will try to change some documentation to use `--password="-VerySecret'` instead.
