### ISSUE TITLE
Cannot change the signInAudience using the Microsoft Graph API

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#15512]
Can you clarify how to do this using the REST API? 
I can not change the signInAudience using the azure ad graph api. The calls always fails with `ValidationError: Bad Request`

I created a question [here](https://stackoverflow.com/questions/64335377/setting-signinaudience-using-azure-graph-api-invalid-json). Basically the API tells me that the JSON is invalid. Is there a working example anywhere how to set the signInAudience?

_Originally posted by @Console32 in https://github.com/Azure/azure-cli/issues/14086#issuecomment-707712158_

**Comment by jiasli** [comment]
@Console32, judging from [the content you posted on Stackoverflow](https://stackoverflow.com/questions/64335377/setting-signinaudience-using-azure-graph-api-invalid-json):

```powershell
$body='{"signInAudience":"AzureADAndMicrosoftAccounts"}'
echo $body
Test-Json -Json $body
az rest --method PATCH --uri https://graph.microsoft.com/v1.0/applications/$application_object_id --body $body --headers "Content-Type=application/json"

ValidationError: Bad Request({
  "error": {
     "code": "BadRequest",
     "message": "Unable to read JSON request payload. Please ensure Content-Type header is set and payload is of valid JSON format.",
     "innerError": {
     "date": "2020-10-13T10:48:48",
      "request-id": "f29fd020-33aa-4cda-b98e-130d1434cd85",
      "client-request-id": "f29fd020-33aa-4cda-b98e-130d1434cd85"
     }
   }
 })
```

It looks like you are using PowerShell and hitting the [quoting issue of PowerShell](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md). Double quotes in the JSON string should be escaped as `\"`.

Also you are not specifying the correct value for `signInAudience`. According to [application resource type](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0#properties), it can only be:

- `AzureADMyOrg`
- `AzureADMultipleOrgs`
- `AzureADandPersonalMicrosoftAccount`
- `PersonalMicrosoftAccount`

So these lines should be 

```pwsh
$body='{\"signInAudience\":\"AzureADandPersonalMicrosoftAccount\"}'
$application_object_id='f71973eb-8d62-40ef-bf27-324f9ee5c115'
az rest --method PATCH --uri https://graph.microsoft.com/v1.0/applications/$application_object_id --body $body
```

FYI, 

- `--headers "Content-Type=application/json"` is not necessary if the body is a valid JSON
- This post regarding `identifierUris` may be helpful: https://stackoverflow.com/questions/41580865/why-switch-to-azure-web-app-api-to-multi-tenanted-is-not-working/41595708#41595708

**Comment by Console32** [comment]
Hi @jiasli 

You are correct this was just a quoting issue on my side. After fixing the JSON, the updates work. Strange that the other Update in my SO Posts worked without a valid JSON 🙈 .

Thanks

**Comment by jiasli** [comment]
Perhaps because you are using Cloud Shell or Bash? This issue only happens in PowerShell. You may use `--debug` to check 
- the actual JSON argument Azure CLI receives 
- the REST request and response on the wire

For example:
```powershell
> az rest --method PATCH --uri https://graph.microsoft.com/v1.0/applications/$application_object_id --body $body --debug
Command arguments: ['rest', '--method', 'PATCH', '--uri', 'https://graph.microsoft.com/v1.0/applications/f71973eb-8d62-40ef-bf27-324f9ee5c115', '--body', '{"signInAudience":"AzureADandPersonalMicrosoftAccount"}', '--debug']
...
Request URL: 'https://graph.microsoft.com/v1.0/applications/f71973eb-8d62-40ef-bf27-324f9ee5c115'
Request method: 'PATCH'
Request headers:
    'User-Agent': 'AZURECLI/2.13.0 (PIP)'
    'Accept-Encoding': 'gzip, deflate'
    'Accept': '*/*'
    'Connection': 'keep-alive'
    'x-ms-client-request-id': '2c56b1a3-8f99-419d-a677-161a414d9a7d'
    'Content-Type': 'application/json'
    'CommandName': 'rest'
    'ParameterSetName': '--method --uri --body --debug'
    'Authorization': 'Bearer eyJ0eXAiOiJKV...'
    'Content-Length': '55'
Request body:
{"signInAudience":"AzureADandPersonalMicrosoftAccount"}
urllib3.connectionpool : Starting new HTTPS connection (1): graph.microsoft.com:443
urllib3.connectionpool : https://graph.microsoft.com:443 "PATCH /v1.0/applications/f71973eb-8d62-40ef-bf27-324f9ee5c115 HTTP/1.1" 204 0
Response status: 204
Response headers:
    'Cache-Control': 'private'
    'Content-Type': 'text/plain'
    'request-id': 'f97cf129-2768-4628-988c-5320a03e659c'
    'client-request-id': 'f97cf129-2768-4628-988c-5320a03e659c'
    'x-ms-ags-diagnostic': '{"ServerInfo":{"DataCenter":"Southeast Asia","Slice":"SliceC","Ring":"5","ScaleUnit":"001","RoleInstance":"AGSFE_IN_6"}}'
    'Strict-Transport-Security': 'max-age=31536000'
    'Date': 'Wed, 14 Oct 2020 09:01:39 GMT'
Response content:
```

**Comment by worldspawn** [comment]
`$body = '{\"accessTokenAcceptedVersion\": 2, \"signInAudience\": \"AzureADandPersonalMicrosoftAccount\"}'`

@jiasli  ☝️ I can't send that payload. Documentation states that in order to set the sign in audience to AzureADandPersonalMicrosoftAccount the token version must be set to 2. If I try the above payload I get
> One or more property values specified are invalid.

If I try to set either individually I get the same result.

If I edit my manifest in the portal and set accessTokenAcceptedVersion to 2 there, I am then able to set the signInAudience to AzureADandPersonalMicrosoftAccount  via REST. So currently it seems to be impossible to use the cli exclusively to set AzureADandPersonalMicrosoftAccount sign in audience.

**Comment by worldspawn** [comment]
@jiasli just read https://github.com/Azure/azure-cli/issues/11168 and seem to be unblocked. Tried on a fresh application and was able to do it one single rest operation.

For anyone arriving here the solution is for the payload to look like this:
`$body = '{\"api\":{\"requestedAccessTokenVersion\": 2},\"signInAudience\": \"AzureADandPersonalMicrosoftAccount\"}'`

For some reason `accessTokenAcceptedVersion` has a different name and is under `api`. 🤷‍♂️ 

As an aside, the user xp is just bad. Its too hard to find this stuff out.

**Comment by jiasli** [comment]
@worldspawn, glad to know it is working for you. Yes, I have previously provided the information in https://github.com/Azure/azure-cli/issues/11168#issuecomment-593385804.

In **Microsoft Graph**, `signInAudience` is defined in [application resource type](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0) and `api.requestedAccessTokenVersion` is defined in [apiApplication resource type](https://docs.microsoft.com/en-us/graph/api/resources/apiapplication?view=graph-rest-1.0).

> As an aside, the user xp is just bad. Its too hard to find this stuff out.

The breaking change is caused by the **Active Directory Graph** -> **Microsoft Graph** migration on the service side. As a client application, Azure CLI should not be the culprit for this user experience. 😆
