### ISSUE TITLE
Error loading command modules 

### ISSUE THREAD

**Issue by AshTappin** [Azure/azure-cli#15517]
I have installed azure-cli (v 2.13.0) manually on Ubuntu (I followed these instructions https://docs.microsoft.com/en-gb/cli/azure/install-azure-cli-linux). I have Python 3.8.5 installed.

However, everytime I use `az` I get the following errors:

```
Error loading command module 'acr'
Error loading command module 'ams'
Error loading command module 'apim'
Error loading command module 'appconfig'
Error loading command module 'appservice'
Error loading command module 'backup'
Error loading command module 'botservice'
Error loading command module 'cdn'
Error loading command module 'configure'
Error loading command module 'consumption'
Error loading command module 'cosmosdb'
Error loading command module 'deploymentmanager'
Error loading command module 'dla'
Error loading command module 'dls'
Error loading command module 'iot'
Error loading command module 'lab'
Error loading command module 'monitor'
Error loading command module 'netappfiles'
Error loading command module 'network'
Error loading command module 'reservations'
Error loading command module 'search'
Error loading command module 'security'
Error loading command module 'servicefabric'
Error loading command module 'sqlvm'
Error loading command module 'storage'
Error loading command module 'vm'
```
Running with `--debug` I see

`TypeError: __init__() missing 1 required positional argument: 'cli_ctx'`

Any ideas on what is going wrong and what I can do to fix it?

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look? thanks

**Comment by AshTappin** [comment]
Is there any movement on this?

**Comment by fengzhou-msft** [comment]
@AshTappin we recommend to use the apt package: https://docs.microsoft.com/en-gb/cli/azure/install-azure-cli-apt

In your case, the issue is likely to be caused by having some other incompatible python packages or legacy dependencies of old azure-cli installed in the same environment with the latest azure-cli.

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please feel free to open new issues if the latest Azure CLI still does not work for you.

**Comment by 211217613** [comment]
I'm getting the same or similar issue on mac. When invoking `az interactive` I immediately get 

![image](https://user-images.githubusercontent.com/7006850/131405062-4d1107c3-aff8-4990-9628-0d8979177327.png)

**Comment by jiasli** [comment]
@211217613, this issue has been fixed by https://github.com/Azure/azure-cli-extensions/pull/3636. Please update `interactive` extension to the latest:

```
az extension update --name interactive
```
