### ISSUE TITLE
Is there any way to return the exit code from a PowerShell script to Jenkins?

### ISSUE THREAD

**Issue by VladMoc** [Azure/azure-cli#15519]
**Describe the bug**
I'm trying to run a PowerShell script from Jenkins using Azure CLI that is installed in a docker container. The problem is that when the script fails the Jenkins pipeline passes.

This is the response from the Azure CLI

`[Pipeline] sh
+ az vm run-command invoke --command-id RunPowerShellScript --n AZR -g AM --scripts '& C:\clean_up.ps1'
{
  "value": [
    {
      "code": "ComponentStatus/StdOut/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Uninstalling the previous version \n\nCheck that the previous installer was uninstalled\n\n'App ' NOT is installed.\n\nDelete the previous unistaller\n\nVerify if the folder is empty\n\n\nThe Folder is not empty",
      "time": null
    },
    {
      "code": "ComponentStatus/StdErr/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "",
      "time": null
    }
  ]
}`

here is an example of the Powershell script

Write-Host "" 
Write-Host "Uninstalling the previous version of the app"
Write-Host ""
msiexec.exe /x $PATH_TO_MSI /passive

Write-Host "Check that the previous installer was uninstalled"
Write-Host ""
$installed = (Get-ItemProperty  HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Where { $_.DisplayName -match $software }) -ne $null

If(-Not $installed) {
	Write-Host "'$software' NOT is installed.";
    Write-Host ""
} else {
	Write-Host "'$software' is installed."
    Write-Host ""
    exit 1
}

I'm expecting if the PowerShell scripts fail that that error can be marked as a failure in  Jenkins. 

Can you help me with how to do this?

**Comment by yungezz** [comment]
hi @qwordy could you pls help to have a look? thanks

**Comment by VladMoc** [comment]
@yungezz @qwordy  Any Solution for the question above? 
Thanks

**Comment by qwordy** [comment]
Use `$?` or `$LASTEXITCODE` to get exit code of last command in PowerShell.
Sorry I have little experience of Jenkins. Here is doc of Jenkins. https://www.jenkins.io/doc/
