### ISSUE TITLE
WebApp:unable to upload new django project to web app

### ISSUE THREAD

**Issue by dvdtho** [Azure/azure-cli#15525]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
'NoneType' object has no attribute 'reserved'
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-lhx4371t\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 709, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 55, in _polish_bad_errors
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
pip-unpacked-wheel-c8n8j8wo\azure\cli\core\__init__.py, ln 784, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 3587, in webapp_up
AttributeError: 'NoneType' object has no attribute 'reserved'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.13.0

```

**Comment by panchagnula** [comment]
@dvdtho is this Django app a Github repo app you can point us to also. Can you  check defaults subscription & local config set on this & if they look correct?

az account show -> using the right subscription

check no local config set from the folder you are running the app from look for .azure folder & see if you have any default values set for  app service plan or resource group. Thanks!

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14287

**Comment by seligj95** [comment]
please upgrade to the latest cli version and let us know if there is still an issue

**Comment by seligj95** [comment]
closing due to no response, please reopen if still an issue
