### ISSUE TITLE
Shared Image Gallery: Updating a share image version returns internal error

### ISSUE THREAD

**Issue by mainred** [Azure/azure-cli#15539]
[Enter feedback here]
After create a image version under my SIG, and I update the image version with more replicas in several regions with ` az sig image-version update`, after 2 hours and 17 minutes, it throws the following error
```
ValidationError: Gallery replication jobs failed in one or more regions. The failing regions' details are as follows: '{region:northeurope, detail:Failed with internal server error.}'. If retry does not work, then please do an update by removing the failed regions and update again by adding them back.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99108d44-6c69-d481-7c5e-891905799635
* Version Independent ID: 142e71ef-a7cd-2acb-786b-7ac359863e91
* Content: [az sig image-version](https://docs.microsoft.com/en-us/cli/azure/sig/image-version?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/sig/image-version.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/sig/image-version.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy could you pls help on this? thanks

**Comment by qwordy** [comment]
Service issue. You can first follow the error message: "If retry does not work, then please do an update by removing the failed regions and update again by adding them back."

**Comment by qwordy** [comment]
Hi @mainred, does the error still occur?

**Comment by mainred** [comment]
@qwordy , I did not hit this problem after several tries.

**Comment by qwordy** [comment]
Great! Close this issue.
