### ISSUE TITLE
Can't update vm or image-version if reference to a cross tenant image

### ISSUE THREAD

**Issue by arrownj** [Azure/azure-cli#15536]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Here’s a scenario that an internal customer, Lab Services, is having. They have a HOBO scenario.

1. Lab Services has a snapshot sitting in their own subscription.
2. Lab Services uses a service principal that has access to the Lab Services subscription and customers’ subscriptions.
3. The service principal creates a gallery, image definition and image version in the customer’s subscription. The image version is based on the snapshot in Lab Services’ subscription, so it is a cross-tenant scenario.
4. The customer then tries to update the replication details of the image version (az sig image-version update), but because the customer does not have access to Lab Services’ subscription, it fails.

Image version based on a resource in another tenant
- Customer tries to update the replica count
- Customer tries to add / remove a region on the image version

VM based on a SIG image in another tenant
- Customer tries to add a data disk
- I would argue that since it’s not allowed to change the imageReference.id of any VM, then, maybe all az vm update can omit the imageReference.id parameter.

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Compute

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/15536
