### ISSUE TITLE
azure-cli fails to install on SUSE 12 SP5

### ISSUE THREAD

**Issue by matt-richardson** [Azure/azure-cli#15545]
**Describe the bug**

Following the install instructions [Install on SLES 12 or other systems without Python 3.6](https://docs.microsoft.com/de-de/cli/azure/install-azure-cli-zypper#install-on-sles-12-or-other-systems-without-python-36) fails with

```
~> az --version
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 38, in <module>
    az_cli = get_default_cli()
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 840, in get_default_cli
    from azure.cli.core.parser import AzCliCommandParser
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 171
    recommender = CommandRecommender(*command_arguments, message, cli_ctx)
                                                                ^
SyntaxError: only named arguments may follow *expression
```

**To Reproduce**
1. spin up a new instance of SUSE12. I used `ami-0676bd358c66c9150` on AWS in ap-southest-2.
2. install python 3.6 from source:
```
sudo zypper install -y gcc gcc-c++ make ncurses patch wget tar zlib-devel zlib openssl-devel
PYTHON_VERSION="3.6.9"
PYTHON_SRC_DIR=$(mktemp -d)
wget -qO- https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz | tar -xz -C "$PYTHON_SRC_DIR"

$PYTHON_SRC_DIR/*/configure
make
sudo make install
```
3. confirm that python is there and running:
```
~> python3 --version
Python 3.6.9
```
4. install azure-cli:
```
sudo zypper install -y curl
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo zypper addrepo --name 'Azure CLI' --check https://packages.microsoft.com/yumrepos/azure-cli azure-cli
sudo zypper refresh azure-cli
AZ_VERSION=$(zypper --no-refresh info azure-cli | grep Version | awk -F': ' '{print $2}' | awk '{$1=$1;print}')
wget https://packages.microsoft.com/yumrepos/azure-cli/azure-cli-$AZ_VERSION.x86_64.rpm
sudo rpm -ivh --nodeps azure-cli-$AZ_VERSION.x86_64.rpm
```
5. check the version that's installed -> crash:
```
~> az --version
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 38, in <module>
    az_cli = get_default_cli()
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 840, in get_default_cli
    from azure.cli.core.parser import AzCliCommandParser
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/parser.py", line 171
    recommender = CommandRecommender(*command_arguments, message, cli_ctx)
                                                                ^
SyntaxError: only named arguments may follow *expression
```

**Expected behavior**
It should show the version number.

**Environment summary**
Install method: interactive script(see above)
CLI version: 2.13.0
OS version: SUSE LES 12, SP 5
Shell: bash

**Additional context**

https://github.com/Azure/azure-cli/issues/15366 looks related, but different.
https://github.com/Azure/azure-cli/issues/9665 looks related again, but different

It's odd that its referring to python3.4 in that stack trace. I tried uninstalling python3.4, and it didn't help (got errors around installing module _ssl (or something like that)).

I've worked around this by changing my scripts to use version 2.11.1 instead, but this will bite me in the future when new features aren't available / bug fixes are made in the newer versions etc

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look? thanks

**Comment by fengzhou-msft** [comment]
@matt-richardson if you run `/usr/bin/python3 -V`, does it still refer to python 3.4?

In the configure step when building python 3, you can try to add the following options:
`$PYTHON_SRC_DIR/*/configure --with-ssl --prefix=/usr`
It will build with the support of ssl and install python 3.6 in `/usr/bin/`. It will override the existing python 3.4.

**Comment by matt-richardson** [comment]
Before running any of the steps, running `/usr/bin/python3 -V` gave me:
 ```
Python 3.4.10
```

after running:
```
sudo zypper install -y gcc gcc-c++ make ncurses patch wget tar zlib-devel zlib openssl-devel
PYTHON_VERSION="3.6.9"
PYTHON_SRC_DIR=$(mktemp -d)
wget -qO- https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz | tar -xz -C "$PYTHON_SRC_DIR"

$PYTHON_SRC_DIR/*/configure
make
sudo make install
```
running `/usr/bin/python3 -V` gives me:
```
Python 3.4.10
```

Running with the new configure options :
```
$PYTHON_SRC_DIR/*/configure --with-ssl --prefix=/usr
```

showed this warning:
![image](https://user-images.githubusercontent.com/373389/96217451-56ddfb00-0fce-11eb-96c2-633592e588e8.png)

but still appeared to work. I'm just setting things up to try installing after that (having repo issues). will report back soon.

**Comment by fengzhou-msft** [comment]
I have updated the [installation doc](https://docs.microsoft.com/de-de/cli/azure/install-azure-cli-zypper#install-on-sles-12-or-other-systems-without-python-36) accordingly and provided a script for installation on SLES 12: 
`curl -sL https://azurecliprod.blob.core.windows.net/sles12_install.sh | sudo bash`
