### ISSUE TITLE
Bug in apim apply-network-updates location data paylod

### ISSUE THREAD

**Issue by PgInsight** [Azure/azure-cli#15546]
`> az apim apply-network-updates --name testapim --resource-group test00 --location westus --debug`

Throws an error:
```
azure.mgmt.apimanagement.models._models.ErrorResponseException: Invalid parameter: Invalid location found : '{'location': 'westus'}'.
Parameter name: Location

cli.azure.cli.core.azclierror : AzureResponseError: code: InvalidParameters - , Invalid parameter: Invalid location found : '{'location': 'westus'}'.
Parameter name: Location
AzureResponseError: code: InvalidParameters - , Invalid parameter: Invalid location found : '{'location': 'westus'}'.

```

Debug logging shows the JSON data payload sending as:

```
msrest.http_logger : Request body:
msrest.http_logger : {"location": "{'location': 'westus'}"}

```

This location payload being sent should be  {'location': 'westus'}

Per the apim documentation for this API:
https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/apimanagementservice/applynetworkconfigurationupdates#examples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 197d8382-ee16-6001-4941-768877379c0d
* Version Independent ID: 1423fa76-977f-ad88-8129-0b52a38e68e6
* Content: [az apim](https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest#az_apim_apply_network_updates)
* Content Source: [latest/docs-ref-autogen/apim.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/apim.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed.
