### ISSUE TITLE
Documentation issues and optimization of the API call

### ISSUE THREAD

**Issue by CesarSolis** [Azure/azure-cli#15544]
Documentation does not provide the complete help, problem I see is that it does not even include the spec options used in the examples provided (-l -s for instance).
az vm list-skus -h

--zone option does not provide what is the default value if not included.

The optimization I'm talking about is : while running with --Debug --Verbose I found that the API call to Request URL: 'https://management.azure.com/subscriptions/c575b3f9-a87d-44a5-b536-f683ba941bf6/providers/Microsoft.Compute/skus?api-version=2019-04-01' is done whit out any filter so CLI client gets all the bulk response and filters. The api supports filtering so this can be made more efficient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az_vm_list_skus)
* Content Source: [latest/docs-ref-autogen/vm.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/vm.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy , could you pls take a  look? thanks

**Comment by qwordy** [comment]
Hi @CesarSolis , Could you provide more details?
Default is all sizes no matter it support zone or not.
https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az_vm_list_skus

**Comment by qwordy** [comment]
@CesarSolis
