### ISSUE TITLE
[Monitor] Onboarding Azure Monitor Control Service (AMCS)

### ISSUE THREAD

**Issue by herreraj-ms** [Azure/azure-cli#15543]
**Resource Provider**
Azure Monitor

**Description of Feature or Work Requested**
Onboarding AMCS data collection rules (DCR) and data collection rule associations (DCRA) APIs to monitor module.

**Minimum API Version Required**
2019-11-01-preview

**Swagger Link**
DCR: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2019-11-01-preview/dataCollectionRules_API.json
DCRA: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2019-11-01-preview/dataCollectionRuleAssociations_API.json

**Target Date**
20-November-2020

**Comment by yonzhan** [comment]
add to S178

**Comment by herreraj-ms** [comment]
Hi @yonzhan, 

I just saw that the milestone change to S179.
I think there was a meeting on Nov 2nd for reviewing the onboarding process.

Do you need anything from my side?

**Comment by yonzhan** [comment]
Please let us know when swagger is merged in public repo and Python SDK request is sent out.

**Comment by herreraj-ms** [comment]
> Please let us know when swagger is merged in public repo and Python SDK request is sent out.

Swagger specs are already merged:

- DCR: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2019-11-01-preview/dataCollectionRules_API.json
- DCRA: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2019-11-01-preview/dataCollectionRuleAssociations_API.json

Regarding Python SDK, I need to request it via OpenAPI Hub, right?

**Comment by yonzhan** [comment]
@jsntcy @kairu-ms for awareness. We have planned this in S179. Firstly, codeGen should validate this.

**Comment by jsntcy** [comment]
@herreraj-ms, yes I saw the SDK release request.
