### ISSUE TITLE
az vm extension set requires a publisher, but there is no way (command) to get the publishers

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#1554]
In order to set the vm extension, you need to specify a publisher
`usage: az vm extension set [-h] [--output {json,tsv,list,table,jsonc}]
                           [--verbose] [--debug] [--query JMESPATH]
                           [--vm-name NAME]
                           [--resource-group RESOURCE_GROUP_NAME] --publisher
                           PUBLISHER [--settings SETTINGS]
                           [--ids RESOURCE_ID [RESOURCE_ID ...]] [--name NAME]
                           [--no-auto-upgrade] [--version VERSION]
                           [--protected-settings PROTECTED_SETTINGS]
az vm extension set: error: argument --publisher is required`

But there is no way to determine the available publishers or the extension images they publish.

**Comment by yugangw-msft** [comment]
use `az vm extension image list`
