### ISSUE TITLE
Unable to upload to blob

### ISSUE THREAD

**Issue by vipulsmishra** [Azure/azure-cli#15557]
## Describe the bug

**Command Name**
`az storage blob upload`

**Errors:**
```
cannot import name timezone
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
azure/cli/core/__init__.py, ln 536, in get_op_handler
    op = import_module(mod_to_import)
lib64/python2.7/importlib/__init__.py, ln 37, in import_module
    __import__(name)
command_modules/storage/operations/blob.py, ln 9, in <module>
    from datetime import datetime, timezone
ImportError: cannot import name timezone
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload --container-name {} -n {} -f {}`

## Environment Summary
```
Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 2.7.5

azure-cli 2.2.0 *

```

**Comment by yonzhan** [comment]
add to S178

**Comment by Juliehzl** [comment]
Hi @vipulsmishra, the issue is caused because you are using python 2. Please use python 3 instead. Python 2 is deprecated and we do not support it ay more.
If you don't want to change your python version, consider installing azure cli using the install instruction here https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt
