### ISSUE TITLE
Documentation for vm extension set lacks important details

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#1555]
az vm extension set supports:
`    --protected-settings  : Protected settings or a file path with such contents.
    --settings            : Public settings or a file path with such contents.`

This is a really unhelpful comment.  We need to denote what the format for settings is and (ideally), and users need a way to determine what settings are available for a given extension.  (This probably can't be via the docs, but I see no way to get that information via commands.)

**Comment by yugangw-msft** [comment]
I will improve the argument description. Note, this command does provide an example in the help 
```bash
Examples
    Add a new linux user
        az vm extension set -n VMAccessForLinux --publisher Microsoft.OSTCExtensions --version 1.4
        --vm-name myvm --resource-group mygroup --protected-settings '{"username":"user1",
        "ssh_key":"ssh_rsa ..."}'
```
