### ISSUE TITLE
Error when running az login on my kali linux

### ISSUE THREAD

**Issue by kamransb** [Azure/azure-cli#15566]
## Describe the bug
Kali version is 
_Linux kali 5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux_

After installation, when I run az login, it takes me to the browser where I enter required credentials that are accepted, and the browser then shows following message.
**You have logged into Microsoft Azure!**
However after that I get this error.
**Command Name**
`az login`

**Errors:**
```
'SubscriptionClient' object has no attribute 'config'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
azure/cli/core/_profile.py, ln 812, in create_arm_client_factory
    configure_common_settings(cli_ctx, client)
cli/core/commands/client_factory.py, ln 79, in configure_common_settings
    client.config.enable_http_logger = True
AttributeError: 'SubscriptionClient' object has no attribute 'config'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.5.0-kali2-amd64-x86_64-with-glibc2.29
Python 3.8.2
Installer: PIP

azure-cli 2.11.1 *

Extensions:
azure-devops 0.18.0

```

**Comment by jiasli** [comment]
This is a known issue if you install Azure CLI will `azure-mgmt-resource==15.0.0` under the same Python virtual environment, please see https://github.com/Azure/azure-cli/issues/13995#issuecomment-663353202 for more details.

**Comment by yonzhan** [comment]
dup with #13995 (comment)
