### ISSUE TITLE
Failure with az login command

### ISSUE THREAD

**Issue by xeronix** [Azure/azure-cli#15579]
## Describe the bug
az login command is not working. Get's stuck while retrieving subscriptions and then fails.

**Command Name**
az login

**Errors:**
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions?api-version=2016-06-01 (Caused by ResponseError('too many 503 error responses',))

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.77 *

```

**Comment by yonzhan** [comment]
add to S178

**Comment by danashviro** [comment]
I had the same temp problem as well on 10/20 UTC 8:40 PM - UTC 9:00 PM.

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/18617#issuecomment-868275965 for an explanation.
