### ISSUE TITLE
Add a new parameter named web-categories to FirewallPolicy Application Rule

### ISSUE THREAD

**Issue by tejasshah7** [Azure/azure-cli#15578]
**Resource Provider**
Network (NRP)

**Description of Feature or Work Requested**
Need to add a new parameter named "web-categories" to the commands:
az network firewall application-rule create/update.

This will be a list of strings.

Also, user can specify either TargetFQDNs, FqdnTag or WebCategories.
There is another issue open to add "TargetURLs" as another parameter to same command. With that too, it will be only 1 of the 4 fields allowed. Here is the issue for reference: https://github.com/Azure/azure-cli/issues/15377

**Minimum API Version Required**
2020-07-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/11049

**Target Date**
11/15/2020

**Comment by yonzhan** [comment]
add to S178

**Comment by tejasshah7** [comment]
@yonzhan 
What is the timeline for S178 to be released?

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/milestone/96  Build to Cloud Shell: 11/13/2020 Official Release: 11/17/2020

**Comment by tejasshah7** [comment]
This feature is postponed from backend so closing this request for now. Will create a new one based on the feature release timeline.
