### ISSUE TITLE
CLI does not support way to create managed identity for Logic App

### ISSUE THREAD

**Issue by spatialman** [Azure/azure-cli#15586]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Could not find any way to create "Managed Identity" for Azure Logic App using Azure CLI.

**To Reproduce**
az logic workflow create --location eastus2 --name la-001 --resource-group rg-test

**Expected behavior**
Should have option to specify whether managed identity needs to be created or separate command to do the same.

**Environment summary**
OS Version - Win 10
Shell Type - Bash on Windows
CLI Version - latest - 2.11.0

**Additional context**
Please provide the sample, to create managed identity for Azure Logic App using Azure CLI

**Comment by yonzhan** [comment]
logic

**Comment by ecfan** [comment]
@Azure/azure-logicapps-team

**Comment by chvndb** [comment]
Anyone working on this, I need this feature.

**Comment by jsntcy** [comment]
We'll plan it in next sprint (12-05).
