### ISSUE TITLE
is there any way to attach multiple disk which ids i have in my variable in tsv format or i have to execute command for every disk i have to attach?

### ISSUE THREAD

**Issue by jdsapariya18** [Azure/azure-cli#15583]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbc06453-93e1-e616-9649-c1487c605a65
* Version Independent ID: 76d52328-613f-bd5f-7daf-f62841300e2b
* Content: [az vm disk](https://docs.microsoft.com/en-us/cli/azure/vm/disk?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm/disk.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/vm/disk.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy could you pls help on this ask? thanks

**Comment by qwordy** [comment]
The help message of `az vm disk attach` says
```
Attach a managed persistent disk to a VM. Please note that --ids only supports one disk.
```
You need to run command for every disk. I think you can write a Bash or PowerShell script to run them.

**Comment by qwordy** [comment]
There is a same issue. Let's only keep one issue open.
https://github.com/Azure/azure-cli/issues/15765
