### ISSUE TITLE
az login --allow-no-subscription does no longer create tenant level account

### ISSUE THREAD

**Issue by Console32** [Azure/azure-cli#15585]
## Describe the bug

Starting of today I can no longer interact with the azure active directory of my tenant using the command line because `az login ...` does no longer create the account required.

**Command Name**
az login

**Errors:**
The missing Account in the `az account list` causes the following error in terraform when using azuread ressources that want to interact with the tenant:

```
 building AzureAD Client: obtain subscription(d2846bb0-0b6e-4c52-a8cb-45f42233fd29) from Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1
```

## To Reproduce:

* Run az login --tenant {} --allow-no-subscription
* View the created account list:

```
az login --tenant {} --allow-no-subscription
You have logged in. Now let us find all the subscriptions to which you have access...
[
  {
    "name": "shared-management-001",
...
  },
  {
    "name": "shared-staging-001",
...
    }
  },
  {
    "name": "shared-testing-001",
...
  },
  {
    "name": "shared-production-001",
...
    }
  }
]
```

## Expected Behavior

The accounts should contain a Account for tenant level access looking like this:
```
{
    "name": "N/A(tenant level account)",
  }
```

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.6
Installer: HOMEBREW

azure-cli 2.13.0

Extensions:
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
add to S178

**Comment by jiasli** [comment]
I believe your tenant now has accessible subscriptions, so the subscription account replaces the tenant account. You have to use the subscription ID in to access the responding tenant.

I have to admin the behavior of `--allow-no-subscription` is unpredictable from CLI perspective, and we are planning to refine it in

- https://github.com/Azure/azure-cli/issues/13285
- https://github.com/Azure/azure-cli/issues/15005

**Comment by jiasli** [comment]
## Explanation on `--allow-no-subscriptions`

`--allow-no-subscriptions` behaves differently under the below 2 scenarios:

### Scenario 1: The identity has no accessible subscriptions

In such case, `az login --allow-no-subscriptions` creates a **placeholder** subscription representing the tenant:

```
> az login --service-principal --username 92375e31-0eae-4019-8207-0698ce16d144 --password xxx --tenant 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a --allow-no-subscriptions
[
  {
    "cloudName": "AzureCloud",
    "id": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
    "isDefault": true,
    "name": "N/A(tenant level account)",
    "state": "Enabled",
    "tenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
    "user": {
      "name": "92375e31-0eae-4019-8207-0698ce16d144",
      "type": "servicePrincipal"
    }
  }
]
```

Notice `name` is `N/A(tenant level account)` and `id` is the same as `tenantId`.

### Scenario 2: The identity has accessible subscriptions

In such case, `--allow-no-subscriptions` degenerates into a no-op. `az login --allow-no-subscriptions` is equivalent to `az login` and returns real subscriptions.

```
> az login --service-principal --username 92375e31-0eae-4019-8207-0698ce16d144 --password xxx --tenant 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a --allow-no-subscriptions
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
    "id": "0b1f6471-1bf0-4dda-aec3-cb9272f09590",
    "isDefault": true,
    "managedByTenants": [],
    "name": "AzureSDKTest",
    "state": "Enabled",
    "tenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
    "user": {
      "name": "92375e31-0eae-4019-8207-0698ce16d144",
      "type": "servicePrincipal"
    }
  }
]
```

Now `name` is the real subscription name `AzureSDKTest` and `id` is the subscription ID. `tenantId` is the tenant of the token used to access this subscription (for Azure Lighthouse). `homeTenantId` is the tenant where the subscription belongs to.
