### ISSUE TITLE
Az cli authorization failed, when user has owner permissions

### ISSUE THREAD

**Issue by donets420** [Azure/azure-cli#15589]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
My user has owner permissions on tenant level.
when I tried to run command "az account management-group show "name_mgmt" -e" I received error:
_AzureResponseError: code: AuthorizationFailed - , The client 'user_name' with object id 'xxx' does not have authorization to perform action 'Microsoft.Management/managementGroups/read' over scope '/providers/Microsoft.Management/managementGroups/name_mgmt' or the scope is invalid. If access was recently granted, please refresh your credentials._

**To Reproduce**
az login
az account management-group show "name_mgmt" -e

**Expected behavior**
output of mgmt and nested objects

**Environment summary**
azure-cli 2.13.0
core 2.13.0

extensions:
account 0.2.1
ai-examples 0.2.4

**Comment by yonzhan** [comment]
add to S178

**Comment by donets420** [comment]
I have found reason of my problem. 
If look to help (az account management-group show --help):
_Arguments
    --name -n            [Required] : Name of the management group._

But it doesn't work with name, it works with management group id in general.

**Comment by ausfestivus** [comment]
Yea, have just lost half my day due to this issue.

From the azure-cli help:
```
Arguments
    --name -n            [Required] : Name of the management group.

...

Examples
    Get a management group.
        az account management-group show --name GroupName
```

`az account management-group show -n remediationMgmtGrp`
```
  "displayName": "Remediation",
  "id": "/providers/Microsoft.Management/managementGroups/remediationMgmtGrp",
  "name": "remediationMgmtGrp",
```

So a human will see the instructions as saying use required arg `--name` and think that refers to the `displayName` when it actually refers to the `name` key.

**Comment by jiasli** [comment]
There are 2 issues we are facing here:

## Issue 1: `displayName` can't be used to show the management group

This can be reproduced with:

```sh
> az account management-group create --name mg20201111 --display-name mg20201111-display
{
  "id": "/providers/Microsoft.Management/managementGroups/mg20201111",
  "name": "mg20201111",
  "properties": {
    ...
    "displayName": "mg20201111-display",
    "tenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a"
  },
  "status": "Succeeded",
  "type": "/providers/Microsoft.Management/managementGroups"
}


> az account management-group show --name mg20201111
{
  ...
  "displayName": "mg20201111-display",
  "id": "/providers/Microsoft.Management/managementGroups/mg20201111",
  "name": "mg20201111",
  "roles": null,
  "tenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
  "type": "/providers/Microsoft.Management/managementGroups"
}

> az account management-group show --name mg20201111-display
code: AuthorizationFailed - , The client 'test@azuresdkteam.onmicrosoft.com' with object id '6d97229a-391f-473a-893f-f0608b592d7b' does not have authorization to perform action 'Microsoft.Management/managementGroups/read' over scope '/providers/Microsoft.Management/managementGroups/mg20201111-display' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

For the terms we use in Azure:

- `id`: the resource ID, like `/providers/Microsoft.Management/managementGroups/mg20201111`
- `name`: the resource name. It is also the last part of the resource ID, like `mg20201111`

`displayName` is one of the `properties` and is not an Azure resource common property. In other words, it is specific to `/providers/Microsoft.Management/managementGroups` resource type.


## Issue 2: the command raises `AuthorizationFailed` instead of `ResourceNotFoundError`

If the user doesn't have tenant-level permission, it is expected that CLI shows `AuthorizationFailed` because the user shouldn't have the permission to know whether the specified management group exists or not.

```sh
# Login with an account that doesn't have tenant-level permission
> az account management-group show --name mg20201111-display
code: AuthorizationFailed - , The client 'test@azuresdkteam.onmicrosoft.com' with object id '6d97229a-391f-473a-893f-f0608b592d7b' does not have authorization to perform action 'Microsoft.Management/managementGroups/read' over scope '/providers/Microsoft.Management/managementGroups/mg20201111-display' or the scope is invalid. If access was recently granted, please refresh your credentials.

# Grant tenant level permission using another tenant-level Owner
> az role assignment create --assignee test@azuresdkteam.onmicrosoft.com --scope / --role Reader

# Now it shows ResourceNotFoundError
> az account management-group show --name mg20201111-display
ResourceNotFoundError: (NotFound) '/providers/Microsoft.Management/managementGroups/mg20201111-display' not found
```

**Comment by jiasli** [comment]
I will update the help message of `--name` (#15871). Thank you for the feedback.

**Comment by worldsayshi** [comment]
For others who end up here: Make sure that you specify which subscription azure-cli should look at.

You can run this command:
```
az account set --subscription <subscription id>
```
