### ISSUE TITLE
az commands for or-policy not working

### ISSUE THREAD

**Issue by wenjuweng37** [Azure/azure-cli#15587]
Hi, it seems that the BLOB storage object replication works from portal, but it doesn't work using aure CLI either via VM or via cloud shell. For example, from VM, I'm getting this message -

$ az storage account or-policy list -n xxxxxx
az storage account: 'or-policy' is not in the 'az storage account' command group. See 'az storage account --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2be315ac-95dc-9465-006c-29ca910996d6
* Version Independent ID: c82c8430-4981-bf90-548f-3e975d7f8878
* Content: [az storage account or-policy](https://docs.microsoft.com/en-us/cli/azure/storage/account/or-policy?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/account/or-policy.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/account/or-policy.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S178

**Comment by Juliehzl** [comment]
Hi @wenjuweng37, may I know you azure cli version?

**Comment by wenjuweng37** [comment]
I upgraded the azure CLI later on to 2.13.0, the corresponding (I replaced storage account name below):
 az storage account or-policy list -n xxxxxx
Command group 'storage account or-policy' is in preview. It may be changed/removed in a future release.
ValidationError: Storage account 'xxxxxx' not found.
This is the case with using azure cloud shell as well.
I entered the storage account name without the URL. I hope that is how you use it. 
Meanwhile, I know I have access to the storage account and I have contributor privilege

**Comment by Juliehzl** [comment]
Hi @wenjuweng37, could help confirm if your storage account is failovered before.  Currently there is an issue in SRP to list failovered storage account and somebody is working on the fix.
Currenly, please add resource group name in your command with `-g` and you could list as expected.
