### ISSUE TITLE
Support Python 3.9 for Azure Functions create

### ISSUE THREAD

**Issue by stefanushinardi** [Azure/azure-cli#15580]
Python 3.9 support in Azure Functions is expected to be available for public preview in mid-November 2020

**Comment by yonzhan** [comment]
Azure Functions

**Comment by nexxai** [comment]
Any update on this?

**Comment by yonzhan** [comment]
Azure Functions service team should look into this issue

**Comment by yonzhan** [comment]
https://github.com/Homebrew/homebrew-core/pull/67930

**Comment by stefanushinardi** [comment]
Update: we are tracking mid-late January

**Comment by pawepaw** [comment]
I see that it's available as preview. Is there anything missing or is it marked as preview for now because it's not fully tested and it's kind of in public test stage?

**Comment by kamperiadis** [comment]
Marking as resolved since this is already supported.
