### ISSUE TITLE
Undocumented alias container option for az storage blob download

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/azure-cli#15595]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When using the `az storage blob download` command, the [documentation](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az_storage_blob_download) states that container names can only be used as `--container-name/-c`.

However, it seems you can also use `--container` argument, which seems to be undocumented. 

**To Reproduce**

Command

```bash
az storage blob download \
    --container test \
    --file somefile \
    --name somefile \
    --account-key my-account-key \
    --account-name my-account-name
```

Running Help

```bash
armaan@Azure:~$ az storage blob download -h
Command
    az storage blob download : Downloads a blob to a file path, with automatic chunking and progress
    notifications.
        Returns an instance of :class:`~azure.storage.blob.models.Blob` with properties and
        metadata.

Arguments
    --container-name -c [Required] : The container name.
    ...
```

**Expected behavior**

This seems to be a leftover option that is supposed to be omitted, or the documentation has forgotten to include it as an option.

Looking at the code: https://github.com/Azure/azure-cli/blob/da3422d7f02625b587c8c4eed00dd061c7cee775/src/azure-cli/azure/cli/command_modules/storage/_params.py#L940

It seems to be an extra undocumented option. 

If this needs to be documented, then it probably needs to be included for the other commands as well, since I see no trace of `--container` option in documentation. 

**Environment summary**

AZ CLI version: 2.13.0
Environment: bash & powershell on Cloud Shell

**Additional context**

**Comment by yonzhan** [comment]
add to S178

**Comment by Juliehzl** [comment]
Hi @ArmaanMcleod, actually the parameter options are `--container-name` and `-c` in our code, but CLI support prefix match. In this way `--container` even `--con` works for `az storage blob download`.

Thanks a lot for you feedback!
