### ISSUE TITLE
Custom ARM endpoint?

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1559]
How do I go about specifying a custom ARM endpoint to target?

**Comment by colemickens** [comment]
For that matter, I'm not even seeing how I would utilize a sovereign cloud.

**Comment by derekbekoe** [comment]
> How do I go about specifying a custom ARM endpoint to target?

To specify a custom ARM endpoint, you can register a new cloud:
```
$ az cloud register -n CloudWithCustomEndpoint --endpoint-active-directory https://login.microsoftonline.com --endpoint-active-directory-graph-resource-id https://graph.windows.net/ --endpoint-active-directory-resource-id https://management.core.windows.net/ --endpoint-gallery https://gallery.azure.com/ --endpoint-management https://management.core.windows.net/ --endpoint-resource-manager <YOUR_CUSTOM_ENDPOINT> --suffix-storage-endpoint core.windows.net
```

Afterwards, switch to that:
```
$ az context create --cloud CloudWithCustomEndpoint -n CustomCloud
```

---

> For that matter, I'm not even seeing how I would utilize a sovereign cloud.
List the registered clouds with `az cloud list`:
```
$ az cloud list -otable
Name
-----------------------
AzureCloud
AzureChinaCloud
AzureUSGovernment
AzureGermanCloud
CloudWithCustomEndpoint
```

Switch to AzureChinaCloud for example:
```
$ az context create --cloud AzureChinaCloud -n MyChina
```
The endpoints will have changed so then you can log in if needed.
```
$ az login
To sign in, use a web browser to open the page https://aka.ms/deviceloginchina ...
```

**Comment by colemickens** [comment]
@derekbekoe Fantastic. Thanks for the very comprehensive answer!
