### ISSUE TITLE
Color on console is broken AzCli + PowerShell

### ISSUE THREAD

**Issue by EwertonJordao** [Azure/azure-cli#15609]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Output after run az cli with cmdlet Convertfrom-json

![image](https://user-images.githubusercontent.com/12378570/96830986-a2e7d000-1412-11eb-9732-a584eaa762f8.png)

**To Reproduce**

- `az lab vm list --lab-name {} -g {} --query {} | convertfrom-json`
Using az cli  + powershell to work with output 

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.13.0

```

**Comment by jiasli** [comment]
This is because `az lab vm list` is a preview command. Is the warning blocking your script? If you really don't like it, you may use [`--only-show-errors`](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-values-and-environment-variables) to turn it off.

**Comment by jiasli** [comment]
This is because `az lab vm list` is a preview command, and the output redirection is causing the terminal color to be corrupted. Please see https://github.com/Azure/azure-cli/pull/12601 for more details.
