### ISSUE TITLE
Fixing monitor test

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#15619]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

There are 7 failed test cases in monitor in a recent test run. Can you have a look? Thanks!
https://clitestresultstac.blob.core.windows.net/latest/index.html
https://clitestresultstac.blob.core.windows.net/20201113-054322-540793/monitor.report.parallel.html

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
monitor

**Comment by haroldrandom** [comment]
close as all failed tests fixed
