### ISSUE TITLE
Fixing storage test

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#15626]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

There are 9 failed test cases in storage in a recent test run. Can you have a look? Thanks!
Latest link: https://clitestresultstac.blob.core.windows.net/latest/index.html

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
storage

**Comment by qwordy** [comment]
![image](https://user-images.githubusercontent.com/5019528/103122040-a66d3100-46b9-11eb-8629-1a6d0a903e9a.png)
I don't think it is time to close it. Feature-request label can avoid SLA check.

**Comment by yonzhan** [comment]
@Juliehzl please take a look.

**Comment by Juliehzl** [comment]
According test results in https://github.com/Azure/azure-cli/issues/16656, it could be closed now.
