### ISSUE TITLE
[Storage] az storage container metadata update cannot accept space-separated metadata key=value pairs

### ISSUE THREAD

**Issue by hasonmsft** [Azure/azure-cli#1562]
From the help, it said that the metadata option accepts space-separated format. But the result looks incorrect. 

```
az storage container metadata update -c hasontestsetacl -h
--metadata          : Metadata in space-separated key=value pairs. This overwrites any existing
                          metadata.
az storage container metadata update -n hasontestsetacl --metadata "a=1 b=2 c=3"
C:\tmp>az storage container metadata show -n hasontestsetacl
{
  "a": "1 b=2 c=3"
}
```

**Comment by tjprescott** [comment]
az storage container metadata update -n hasontestsetacl **--metadata "a=1 b=2 c=3"**

You should not put quotes around your space separated list.

**Comment by tjprescott** [comment]
I verified that this works correctly without quotes and that it works correctly if you surround a value with quotes to include spaces. 
```
--metadata a="1 and 2" b=3 c="4 and 5"

{
  "a": "1 and 2",
  "b": "3",
  "c": "4 and 5"
}
```

**Comment by hasonmsft** [comment]
Could you add more sample in the help? I think for most people, they will follow the way I input as above.
