### ISSUE TITLE
Document condition syntax

### ISSUE THREAD

**Issue by aelij** [Azure/azure-cli#15628]
I could not find a documentation for the `--condition` parameter: exact syntax and which properties can be used

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dacfad8-cb2f-2534-3b29-89b0930a2252
* Version Independent ID: 17325cd4-44c5-4069-d9f6-940a55f0f7c9
* Content: [az role assignment](https://docs.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/role/assignment.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/role/assignment.yml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S178

**Comment by jiasli** [comment]
Let me work with RBAC service team to put more information in the doc.

**Comment by jiasli** [comment]
We have marked `--condition`, `--condition-version` and `--description` as preview for now (https://github.com/Azure/azure-cli/pull/15690). The corresponding document will be updated by RBAC service team later.

**Comment by RakeshMohanMSFT** [comment]
@aelij Sample is updated for --condition parameter https://docs.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest

**Comment by aelij** [comment]
@RakeshMohanMSFT thanks. It could be helpful to add a link to the syntax [documentation](https://docs.microsoft.com/en-us/azure/role-based-access-control/conditions-format) in addition to a sample.

**Comment by mumoryan** [comment]
@aelij the documentation associated with abac conditions in role assignments will be released soon. We are launching public preview for the feature in the next few weeks. Please expect official docs to be updated with new info under the concepts category. Thank you for your patience
