### ISSUE TITLE
"az group list" inconsistent results

### ISSUE THREAD

**Issue by anders-kiaer** [Azure/azure-cli#15629]
## Describe the bug

**Command Name**
`az group list`

**Errors:**
Not an error, but incorrect output. Sometimes `az group list` returns correctly a list of my resource groups. However, sometimes the list is empty. The issue is observed over some time now when rerunning `az group list` multiple times immediately after each other (sometimes returns empty list, sometimes one item, sometimes five items, without any apparent pattern, e.g. 5, 5, 5, 1, 0, 5, 0, 0, 1, 5...).

## To Reproduce:

- `az group list`
- `az group list`
- `az group list`
- `az group list`
- `az group list`

## Expected Behavior
Consistent correct output.

## Environment Summary
```
Linux-5.4.0-48-generic-x86_64-with-glibc2.29
Python 3.8.5
Installer: PIP

azure-cli 2.13.0

```
## Additional Context

---

From a user perspective it is `az group list` that is inconsistent, but I guess there is a medium+ probability that the issue does not rely within the CLI, but rather the API used by the CLI? If this is likely, feel free to transfer/close this issue.

**Comment by yonzhan** [comment]
add to S178

**Comment by zhoxing-ms** [comment]
Hi @anders-kiaer Sorry, I can't reproduce this issue. When this problem occurs, those resources under this resource group are not deleted or added, right?
If so, please execute `az group list --debug` and email the printed information to me~
My email address is Zhou.Xing@microsoft.com, thanks~
