### ISSUE TITLE
Fixing network test

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#15621]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

There are 9 failed test cases in network in a recent test run. Can you have a look? Thanks!
https://clitestresultstac.blob.core.windows.net/latest/index.html
https://clitestresultstac.blob.core.windows.net/20201113-054322-540793/network.report.parallel.html

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
add to S178

**Comment by fengzhou-msft** [comment]
@aznetsuppgithub please advise on how to fix the error returned by service with `az network application-gateway create`: 

> Application Gateway with SKU tier WAF_v2 can only use PrivateIPAddress with IpAllocationMethod as Static.

Which SKU should we use? Standard_v2 does not work either.

**Comment by surajmb** [comment]
Hi @fengzhou-msft , I see you have used self.check('frontendIpConfigurations[0].privateIpAllocationMethod', '_Dynamic_') in one of the creates, is it for testing the scenario?

Application Gateway Standard_v2 and WAF_v2 SKUs only support private IP allocation method as Static as mentioned in the error message.

**Comment by fengzhou-msft** [comment]
> Hi @fengzhou-msft , I see you have used self.check('frontendIpConfigurations[0].privateIpAllocationMethod', '_Dynamic_') in one of the creates, is it for testing the scenario?
> 
> Application Gateway Standard_v2 and WAF_v2 SKUs only support private IP allocation method as Static as mentioned in the error message.

@haroldrandom is the owner of network module and please check if we can use static private IP allocation method for the tests scenario.

**Comment by haroldrandom** [comment]
@surajmb What you said is https://github.com/Azure/azure-cli/issues/15712. 
And it's quite wired, the test is passed when I submit this [PR](https://github.com/Azure/azure-cli/pull/15255/files/8c1cbdf50b50ecd8dda7c577c54e7d54f6ac8b62). 

I will make a patch to this ASAP
