### ISSUE TITLE
Fix security test

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#15624]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

There are 6 failed test cases in security in a recent test run. Can you have a look? Thanks!
https://clitestresultstac.blob.core.windows.net/20201018-203235-041446/index.html
https://clitestresultstac.blob.core.windows.net/20201018-203235-041446/security.report.parallel.html

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
security
