### ISSUE TITLE
Error in az cloud register example

### ISSUE THREAD

**Issue by hattan** [Azure/azure-cli#15634]
There is an error in the az cloud register example, specifically when using a cloud config file. The example states that the cloud config file should contain the following json properties

```json 
{
  "endpoint":{
    "activeDirectory": "https://login.microsoftonline.us"
  },
  "suffix":{
    "acrLoginServerEndpoint": ".azurecr.us"
  }
```

However that is invalid, when testing with az cli 2.12.1 the file should look like this (note the plural property names):

```json
{
    "endpoints": {

    },
    "suffixes": {
    }
}
```

Note the same issue appears in the cli help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8655f313-0a82-5fcc-e8f9-87199bbddcad
* Version Independent ID: ec2ef23a-6e82-937d-b8e0-02bca39bf603
* Content: [az cloud](https://docs.microsoft.com/en-us/cli/azure/cloud?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/cloud.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cloud.yml)
* Service: **cloud-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @fengzhou-msft ,could you pls help to check and update example if necessary? thanks

**Comment by fengzhou-msft** [comment]
Fixed code in Azure CLI. It will be released on 11/27 and doc will also be in sync then.
