### ISSUE TITLE
Cannot list or delete soft-deleted Managed HSMs

### ISSUE THREAD

**Issue by heaths** [Azure/azure-cli#15632]
## Describe the bug

Despite being documented that you can purge or list deleted MHSMs, it appears that is not the case given the error output:

```
$ az keyvault list-deleted --resource-type hsm
'ManagedHsmsOperations' object has no attribute 'list_deleted'
```

/cc @Lusitanian 

**Command Name**
`az keyvault list-deleted`

**Errors:**
```
'ManagedHsmsOperations' object has no attribute 'list_deleted'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 325, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 784, in default_command_handler
    return op(**command_args)
cli/command_modules/keyvault/custom.py, ln 250, in list_deleted_vault_or_hsm
    return hsm_client.list_deleted()
AttributeError: 'ManagedHsmsOperations' object has no attribute 'list_deleted'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a resource group
- Provision a Managed HSM (no need to activate for this repro) in that resource group
- Delete the resource group with the Managed HSM
- `az keyvault list-deleted --resource-type hsm` or `az keyvault purge --hsm-name <name>`

## Expected Behavior

I can list and purge deleted MHSMs like I can KVs.

## Environment Summary
```
Linux-4.19.128-microsoft-standard-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.13.0

```

**Comment by yungezz** [comment]
hi @bim-msft could you pls take a look?

**Comment by bim-msft** [comment]
Hi @heaths , the service has not supported `list-deleted` and `purge` for MHSM yet.

**Comment by heaths** [comment]
If it's not planned, should we make sure those MHSM resources aren't enumerated or swallow errors?

**Comment by yungezz** [comment]
> If it's not planned, should we make sure those MHSM resources aren't enumerated or swallow errors?

make sense. @bim-msft let's make a graceful error message with userFault here to show that list-deleted isn't supported for hsm yet, and doc change.

**Comment by bim-msft** [comment]
@heaths @yungezz  Sure, sounds good.
