### ISSUE TITLE
Where is documentation for Kusto extension?

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-cli#15630]
The Note at the top directs users to use the kusto extension instead of the built-in functionality, but I'm having a hard time trying to find documentation for the extension. It would be great to link users to this documentation or - better yet - include it instead of the default docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41f71b1e-7a13-664a-9382-a69931e566c1
* Version Independent ID: 7f44a1c2-c6a1-ead6-f286-cdf54bc6ec5c
* Content: [az kusto](https://docs.microsoft.com/en-us/cli/azure/kusto?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/kusto.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/kusto.yml)
* Service: **data-explorer**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Kusto

**Comment by ilayrn** [comment]
@astauben, can you please check it out?

**Comment by astauben** [comment]
Hi @brandonh-msft you can find the docs here: https://docs.microsoft.com/en-us/cli/azure/ext/kusto/kusto?view=azure-cli-latest

**Comment by brandonh-msft** [comment]
> Hi @brandonh-msft you can find the docs here: https://docs.microsoft.com/en-us/cli/azure/ext/kusto/kusto?view=azure-cli-latest

@astauben thanks, any reason why we don't link there from the `az kusto` page?

**Comment by cicorias** [comment]
can we clarify where the documentation is as the link above from @brandonh-msft states deprecation of the module.

But where is the docs/source for the "kusto extension" mentioned?

```
Manage Azure Kusto resources.

This module will not be supported starting January 1, 2021. Please execute "az extension add -n kusto" to install the supported Kusto extension.
```

**Comment by zoharHenMicrosoft** [comment]
https://docs.microsoft.com/cli/azure/kusto?view=azure-cli-latest

**Comment by zoharHenMicrosoft** [comment]
> can we clarify where the documentation is as the link above from @brandonh-msft states deprecation of the module.
> 
> But where is the docs/source for the "kusto extension" mentioned?
> 
> ```
> Manage Azure Kusto resources.
> 
> This module will not be supported starting January 1, 2021. Please execute "az extension add -n kusto" to install the supported Kusto extension.
> ```
> 
> Best in public doc I found is: https://github.com/Azure/azure-cli-extensions/blob/main/src/kusto/report.md

this one is OK https://github.com/Azure/azure-cli-extensions/blob/main/src/kusto/report.md

**Comment by ohads-MSFT** [comment]
@zoharHenMicrosoft are those docs hosted under https://learn.microsoft.com/ somewhere?

**Comment by zoharHenMicrosoft** [comment]
> @zoharHenMicrosoft are those docs hosted under https://learn.microsoft.com/ somewhere?

The most updated docs are in here https://learn.microsoft.com/en-us/cli/azure/kusto?view=azure-cli-latest
but we strongly recommend on using PS instead, as CLI is no longer under support.

**Comment by ohads-MSFT** [comment]
> > @zoharHenMicrosoft are those docs hosted under https://learn.microsoft.com/ somewhere?
> 
> The most updated docs are in here https://learn.microsoft.com/en-us/cli/azure/kusto?view=azure-cli-latest but we strongly recommend on using PS instead, as CLI is no longer under support.

Thank you @zoharHenMicrosoft.
1. These docs seem to be for the built-in command, not the extension. Perhaps you could update them and point to the PS module instead?
> This module will not be supported starting January 1, 2021. Please execute "az extension add -n kusto" to install the supported Kusto extension.
2. AFAIK the current practice in Azure is to prioritize `az` CLI over PS (I assume for best xplat experiece), any reason you deviated from this norm?

**Comment by zoharHenMicrosoft** [comment]
> > > @zoharHenMicrosoft are those docs hosted under https://learn.microsoft.com/ somewhere?
> > 
> > 
> > The most updated docs are in here https://learn.microsoft.com/en-us/cli/azure/kusto?view=azure-cli-latest but we strongly recommend on using PS instead, as CLI is no longer under support.
> 
> Thank you @zoharHenMicrosoft.
> 
> 1. These docs seem to be for the built-in command, not the extension. Perhaps you could update them and point to the PS module instead?
> 
> > This module will not be supported starting January 1, 2021. Please execute "az extension add -n kusto" to install the supported Kusto extension.
> 
> 2. AFAIK the current practice in Azure is to prioritize `az` CLI over PS (I assume for best xplat experiece), any reason you deviated from this norm?

Please contact oren.hasbani@microsoft.com, I'm not working on it for more than 2y.

**Comment by ohads-MSFT** [comment]
@orhasban?

**Comment by sw47** [comment]
Any updates? I was under same impressions as @ohads-MSFT that CLI support would be prioritized over PS.

**Comment by danielkimuipath** [comment]
Are there any updates to CLI support?
