### ISSUE TITLE
[Storage] --fail-on-exist looks not very useful

### ISSUE THREAD

**Issue by hasonmsft** [Azure/azure-cli#1564]
When I don't pass the --fail-on-exist option, I can still get the result - fail. Besides that, some commands like this one (without --fail-on-exist), I can only get the result (failure) but not the reason (why it failed). 

```
Looks like --fail-on-exist is not very useful. 

C:\tmp>az storage container create -n hasontestsetacl
{
  "success": false
}

C:\tmp>az storage container create -n hasontestsetacl --fail-on-exist

The specified container already exists.
C:\tmp>

```

**Comment by tjprescott** [comment]
This is a limitation of the SDK and/or service. Since the SDK makes "fail-on-exist" an opt-in behavior, we do the same since whatever reason the SDK (and service for that matter) has for exposing that choice would presumably apply to a CLI user as well.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
