### ISSUE TITLE
[Storage] Cannot get the detailed reason for command failure

### ISSUE THREAD

**Issue by hasonmsft** [Azure/azure-cli#1565]
```
C:\tmp>az storage container create -n hasonclibugbash
{
  "success": false
}
It's very hard to understand why it failed…
```

**Comment by tjprescott** [comment]
true/false is the extent of the response coming from the Python storage SDK. As you mention in #1564, using the --fail-on-exist flag will give you an actual error message. If there were some other error, presumably there would be no way to get it and you would just get "false" as the return value.

While we could always make these calls such that they fail if the resource exists, whatever design reason the SDK has for making this an opt-in behavior would apply to the CLI as well.

**Comment by hasonmsft** [comment]
This issue is not only for this command, it's a generic issue for all commands. Please take a consideration for failure troubleshooting.

**Comment by troydai** [comment]
@hasonmsft thanks for filing the issue. Just as @tjprescott said, it is difficult for CLI to give any reason if the SDK itself doesn't provide sufficient information.
