### ISSUE TITLE
--ssh-key-values along with [az vm create] parameter is not taking the public key 

### ISSUE THREAD

**Issue by subhendu-de** [Azure/azure-cli#15652]
**Describe the bug**
The  ```--ssh-key-values``` along with ```az vm create``` parameter is not taking the public key while creating a vm. Please note I've created the key-pair using ```ssh-keygen``` utility

**To Reproduce**
Use the following scripts to create a keypair
```
ssh-keygen -f .ssh\ubuntu
```
It creates private and public key named ubuntu and ubuntu.pub. Try to use the public key to create the vm by running the following az cli command
```
az vm create \
	--resource-group myResourceGroups \
	--name ubuntu-vm-20102020 \
	--image UbuntuLTS \
	--admin-username azureuser \
	--ssh-key-values .ssh\ubuntu.pub
```
**Expected behavior**
The vm should be created using the public key provider in the az cli command

**Environment summary**
I'm using windows 10 and az vm cli version is 2.2.20. The azure cli version is 2.0.64

**Additional context**
As per the documentation, the ```--ssh-key-values``` parameter takes the path of the public file (Space-separated list of SSH public keys or public key file paths.)

**Comment by yungezz** [comment]
hi @qwordy , could you pls help to take a look?

**Comment by qwordy** [comment]
@subhendu-de Thank you for reporting it. Can you paste the error message here?

**Comment by subhendu-de** [comment]
@qwordy please find the attached snapshot

![image](https://user-images.githubusercontent.com/13384157/97256222-77148200-1838-11eb-9904-749a3e866206.png)

**Comment by qwordy** [comment]
I haven't reproduced your problem. What happens if you pass the key value in command line? The version of Azure CLI you use is kind of old. Can you download the latest version of Azure CLI and have a try?

**Comment by subhendu-de** [comment]
@qwordy Installing az cli 2.14.0 resolves the issue. Thanks!
