### ISSUE TITLE
Can't configure Log Analytics data export to specific event hub

### ISSUE THREAD

**Issue by yossi-y** [Azure/azure-cli#15650]
**Resource Provider**
operationalinsights

**Description of Feature or Work Requested**
CLI configuration to EH allows configuration to event hub namespaces like:
    $eventHubNamespacesId = '/subscriptions/b1550e13-52b0-4ed1-8a7a-8929cee47022/resourceGroups/yossiy/providers/Microsoft.EventHub/namespaces/yossiy-dataexport'
    az monitor log-analytics workspace data-export create -g $resourcegroup --workspace-name $workspace -n yossiyexport2 --tables SecurityEvent Heartbeat --destination $eventHubNamespacesId

The outcome in this configuration is that each table is exported to separate EH, one for SecurityEvent and one for Heartbeat.
In REST, I can also specify EH name and allow all exported data to be sent to same EH, like:
PUT https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourcegroup}}/providers/Microsoft.OperationalInsights/workspaces/{{workspace}}/dataexports/yossiyexport2?api-version=2020-08-01
Authorization: {{credential}}
Content-type: application/json

{
    "properties": {
      "destination": {
            "resourceId": "{{eventHubId}}",
            "metaData": {
                  **"EventHubName": "{{eventHubName}}"**
            }
      },
      "tablenames": [
            "Usage",
            "Heartbeat"
      ],
      "enable": true
    }
}

**Minimum API Version Required**
2020-08-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2020-08-01

**Target Date**
2020-11-12

**Comment by yonzhan** [comment]
add to S178

**Comment by kairu-ms** [comment]
@yossi-y should I add a new parameter for EventHubName or retrieve it from eventHubId?

**Comment by yossi-y** [comment]
Please give me your perspective here -
Originally, we didn't ask to add EventHubName parameter since it can lead to unintended result - users may see the EventHubName  parameter and set name and this will result in all tables being exported to the same event hub while each different schema. 
After trying CLI, I realized that when EH resourceId includes event hub name, like: 
$eventHubId = '/subscriptions/b1550e13-52b0-4ed1-8a7a-8929cee47022/resourceGroups/yossiy/providers/Microsoft.EventHub/namespaces/yossiy-dataexport/eventHubName/exportcentralized-CLI'
az monitor log-analytics workspace data-export create -g $resourcegroup --workspace-name $workspace -n yossiyexport2 --tables Heartbeat InsightsMetrics VMBoundPort --destination $eventHubId 

The operation creates the EH name and export all tables to it fine.

Now I'm reluctant to add  EventHubName parameter for the reason I mentioned above.
If users desire to export to a single EH, they can define it in $eventHubId and that will work.

Make sense?

**Comment by kairu-ms** [comment]
@yossi-y That make sense. However python SDK for api version 2020-08-01 is not available, I will work on when it's ready.
