### ISSUE TITLE
webapp: Container Apps Quick Start Image Change

### ISSUE THREAD

**Issue by calvinsID** [Azure/azure-cli#15660]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
- Change container apps quick start image from nginx:latest to mcr.microsoft.com/appsvc/staticsite:latest
- Add registry url

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by btardif** [comment]
Lets talk about this one during sync. This might not apply to current solution.

**Comment by yonzhan** [comment]
Appservice

**Comment by btardif** [comment]
We don't use quickstart images for CLI
