### ISSUE TITLE
`az storage blob exists` Fails

### ISSUE THREAD

**Issue by poita66** [Azure/azure-cli#15668]
## Describe the bug

**Command Name**
`az storage blob exists`

**Errors:**
```
No module named '_cffi_backend'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 553, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 478, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 310, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
storage/v2018_11_09/blob/_encryption.py, ln 13, in <module>
    from cryptography.hazmat.primitives.padding import PKCS7
cryptography/hazmat/primitives/padding.py, ln 13, in <module>
    from cryptography.hazmat.bindings._padding import lib
ModuleNotFoundError: No module named '_cffi_backend'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Enter registry.fedoraproject.org/f32/fedora-toolbox:32 container with podman (docker may also work)
- Install Azure CLI by following https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum
- `az login`
- `az storage blob exists --container-name {} --name {} --account-name {}`

## Expected Behavior

A valid response describing if the blob exists

## Environment Summary
```
Linux-5.8.16-200.fc32.x86_64-x86_64-with-glibc2.2.5
Python 3.8.6
Installer: RPM

azure-cli 2.13.0

```
## Additional Context

- This is running in fedora-toolbox:32 container (registry.fedoraproject.org/f32/fedora-toolbox:32)
- Azure CLI installed by following https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum
- Other commands (e.g. `az group create`) work as expected

**Comment by yonzhan** [comment]
add to S178

**Comment by Juliehzl** [comment]
See here https://github.com/Azure/azure-cli/blob/dev/doc/install_troubleshooting.md#errors-on-install-with-cffi-or-cryptography.
`sudo yum install -y python3-cffi`
