### ISSUE TITLE
information Mismatch

### ISSUE THREAD

**Issue by johnmeister** [Azure/azure-cli#15666]
On page :
https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-multiple-sites-cli#create-a-cname-record-in-your-domain

it states
"With host-names, you can mention up to 5 host names as __comma-separated values__ . For example, --host-names "*.contoso.com,*.fabrikam.com" ".

while on this page:
https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/http-listener?view=azure-cli-latest#az-network-application-gateway-http-listener-create

it's stated as
"--host-names
__Space-separated list __ of host names that allows special wildcard characters as well."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dce00db-c8d7-9b93-7ac8-114a500a6a34
* Version Independent ID: 14a03192-a30b-d273-fa11-32413868a5fa
* Content: [az network application-gateway http-listener](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/http-listener?view=azure-cli-latest#az-network-application-gateway-http-listener-create)
* Content Source: [latest/docs-ref-autogen/network/application-gateway/http-listener.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/application-gateway/http-listener.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S178

**Comment by haroldrandom** [comment]
Closed as PR merged
