### ISSUE TITLE
az backup protectable-item list error

### ISSUE THREAD

**Issue by kunjals** [Azure/azure-cli#15677]
## Describe the bug
az backup protectable-item list failes with an error when used with workload-type AzureFileshare

**Command Name**
`az backup protectable-item list`

**Errors:**
```
'AzureFileShare'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/backup/custom_base.py, ln 199, in list_protectable_items
    return custom_wl.list_protectable_items(client, resource_group_name, vault_name, workload_type, container_uri)
cli/command_modules/backup/custom_wl.py, ln 271, in list_protectable_items
    workload_type = workload_type_map[workload_type]
KeyError: 'AzureFileShare'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup protectable-item list --resource-group {} --vault-name {} --workload-type {}`

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.13.0 *

Extensions:
ai-examples 0.2.4

```

**Comment by yonzhan** [comment]
backup

**Comment by pvrk** [comment]
@kunjals : This command is only for AzureWorkload backup management type i.e., for databases such as HANA. This is not meant for Azure file shares. Can you please let me understand what is the scenario and how you were planning to use this command?

taggin @mepand for information

**Comment by pvrk** [comment]
@kunjals : A gentle reminder to comment.

**Comment by pvrk** [comment]
@kunjals :Another gentle reminder

**Comment by pvrk** [comment]
Closing this issue since we didn't get any response. Currently, this command doesn't support Azure File shares.
