### ISSUE TITLE
Add a Note about the plan property

### ISSUE THREAD

**Issue by damienbod** [Azure/azure-cli#15670]
If creating a functionsapp using a plan from a different resource group, the Resource ID must be used and not the plan name for the plan property.

I think it would be good to add this to the docs where the plan property is explained. I could create a PR for this if you want.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f254bb-7dfd-417b-b08d-f2ac34247d99
* Version Independent ID: 9d22f523-579b-ea66-04ed-20f09c72bcbb
* Content: [az functionapp](https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest#az_functionapp_create)
* Content Source: [latest/docs-ref-autogen/functionapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/functionapp.yml)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
functionsapp

**Comment by damienbod** [comment]
Created a PR in the docs which fixes this.
