### ISSUE TITLE
azure --version still reports old version after upgrade using apt-get

### ISSUE THREAD

**Issue by mpowrie** [Azure/azure-cli#15675]
## Describe the bug
I upgraded to the latest version of azure-cli in Ubuntu, but typing in az --version still shows an older version installed.

I then realized that running az from WSL is actually executing az for Windows.

running this command:
```
sudo apt-get install azure-cli
```
I see:
Reading package lists... Done
Building dependency tree
Reading state information... Done
azure-cli is already the newest version (2.14.0-1~focal).
0 upgraded, 0 newly installed, 0 to remove and 31 not upgraded.

but when I type:
```
az --version
```
I see:
azure-cli                         2.13.0 *

core                              2.13.0 *
telemetry                          1.0.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\MarcusPowrie\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: 

azure-cli 2.13.0 *

```

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look?

**Comment by fengzhou-msft** [comment]
If you run `/usr/bin/az --version`, does it give you the expected result?

If yes, please check your `PATH` env variable and make sure `/usr/bin/` is in front of `/mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin`.

**Comment by fengzhou-msft** [comment]
@mpowrie Did you get a chance to check the above comment?

**Comment by mpowrie** [comment]
Hi Feng Zhou,

Sorry for the delay in my response. I figured out the problem: I have the
Azure CLI installed in both my WSL instance and my Windows 10 host.
when typing in az --version into WSL, the Windows version which was
slightly different was responding.

Workaround: Uninstall the Azure CLI from Windows and only have it installed
in my WSL (Ubuntu 20.04).

I'd like to be able to have the azure cli installed on both WSL and Windows
however, with WSL choosing the Azure native executable over the Windows
executable.

**Comment by fengzhou-msft** [comment]
@mpowrie normally after you installed `azure-cli` in WSL and run `which az`, you should see `/usr/bin/az` no matter whether you installed `azure-cli` with MSI in windows. If not, then you need to fix your `PATH` variable.

**Comment by mpowrie** [comment]
Hi Feng Zhou,

Thanks. I was surprised to see my Windows host OS path entries mixed
into my WSL bash paths - I'll remove the redundant Windows paths from WSL.
