### ISSUE TITLE
WebApp:az webapp config appsettings : slotSettings auto change

### ISSUE THREAD

**Issue by geremy42** [Azure/azure-cli#15680]
### Describe the bug
**Command line**
`az webapp config appsettings set --name APP1 --resource-group RG1 --slot staging --settings "Key1=Value1"`

**Output**
`
[
  {
    "name": "Key1",
    "slotSetting": false,
    "value": "Value1"
  }
]
`

**Error**
Even the output is correct, by running `az webapp config appsettings list`, the slotSetting has been automatically changed to True
`
[
  {
    "name": "Key1",
    "slotSetting": true,
    "value": "Value1"
  }
]
`

**Expected behavior**
Keep slotSetting value unchanged

### Additional context
The idea is to edit an app settings value on app service slot. The concerned app settings has to be swapped to production slot, as the native behavior.

**Comment by yonzhan** [comment]
webapp

**Comment by btardif** [comment]
@ThejaChoudary and @Kotasudhakarreddy can you try and repro this?

**Comment by Kotasudhakarreddy** [comment]
@geremy42 - I am unable to repro the issue in the latest CLI version (2.16.0) . Please try with latest version and reopen this issue if you are still facing the same.

**Comment by akshaychopra5207** [comment]
I am facing the same issue with az cli  2.16 version. Tried to upgrade it to 2.18 and still getting the same issue
az webapp config appsettings set -g dp-yamlcont-master -n dp-yamlcont-cont-test --slot staging  --settings @appSettings.json
The command above. always make the slot setting to true even if we define false in JSON

[

    {
        "name": "testNewApp" ,
        "value": "time",
        "slotsetting": "false"
    }
    ,
    {
        "name": "testNewApp1" ,
        "value": "time1",
        "slotsetting": "false"
    }
    ,
    {
        "name": "testNewApp2" ,
        "value": "time2",
        "slotsetting": "false"
    }
    ,
    {
        "name": "testNewApp3" ,
        "value": "time3",
        "slotsetting": "false"
    }
    ,
    {
        "name": "testNewApp2" ,
        "value": "@Microsoft.KeyVault(SecretUri=https://dpyamlcont.vault.azure.net/secrets/test1/f6d4d4f4dff74a689c29dfd180bc0740)",
        "slotsetting": "false"
    }
    ,
    {
        "name": "testNewApp3" ,
        "value": "@Microsoft.KeyVault(SecretUri=https://dpyamlcont.vault.azure.net/secrets/test2/2416121e38d74e7495f0d0fc2e3d9be6)",
        "slotsetting": "false"
    }
    ]

**Comment by giovannifl** [comment]
Any updates on this issue ?
