### ISSUE TITLE
Azure Batch CLI command --os-family parameter should support the string name of the os family rather than magic strings

### ISSUE THREAD

**Issue by cbellee** [Azure/azure-cli#15689]
**Is your feature request related to a problem? Please describe.**
Azure Batch CLI command --os-family parameter only supports 'magic strings' identifying the os family

https://docs.microsoft.com/en-us/cli/azure/batch/pool?view=azure-cli-latest#az_batch_pool_create

$az batch pool create --os-family {2, 3, 4, 5, 6}

**Describe the solution you'd like**
Azure Batch CLI command --os-family parameter should support the 'magic number' and string name of the os family, or probably more easily, by adding a new parameter, such as '--os-family-name' to avoid breaking backwards compatibility.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by yungezz** [comment]
route to appropriate team

**Comment by bgklein** [comment]
The osFamily refers to the --os-family number for cloud services as referenced https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-guestos-update-matrix. For a VMSS Image you should make use of --image
