### ISSUE TITLE
WebApp:[customer interview request]  Updating config values of app service with newly created container instance

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#15685]
**Is your feature request related to a problem? Please describe.**
Yes, unable to update config values of app service with container instance via the CLI

**Describe the solution you'd like**
Being able to update the webapp config file with the newly created container instance in the via commands such as 

_az webapp config update key_ or something

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by chenlomis** [comment]
@devlife for awareness and additional context

**Comment by yonzhan** [comment]
webapp

**Comment by devlife** [comment]
I just found this: https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az_webapp_config_appsettings_set. I didn't know that this even existed and definitely suites my needs.
