### ISSUE TITLE
[AzureFunctions][CustomHandler]Remove preview flag 

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-cli#15688]
cc @gzuber  @anthonychu

Stacks updates here:  https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/pull/21

**Comment by pragnagopa** [comment]
@gzuber - if this issue requires just updating the stacks content, please assign it to me

**Comment by yonzhan** [comment]
AzureFunctions
