### ISSUE TITLE
Error Output Improvement: Requests to be confirmed

### ISSUE THREAD

**Issue by houk-ms** [Azure/azure-cli#15693]
These requests are for error output improvements, which are to be confirmed or have dependencies.

**1. Print ClientError & ServiceError to users in the error message**

To be Confirmed
- Print only ClientError and ServiceError?
- The terms we use, will the terms 'ClientError' and 'ServiceError' confuse users?

**2. Provide description for recommendations**

Depends on Aladdin
- Aladdin need provide recommendations with descriptions

**3. Provide at most 3 recommendations**

To be Confirmed
- The orders of CLI exmaples and Aladdin recommendations
- Depends on 2

**4. Remove optional parameters in recommended commands**

Partly Depends on Aladdin
- Aladdin need provide commands without unnecessary arguments.

**5. Colorization**

Depends on Framework Support

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/15692

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness.
