### ISSUE TITLE
Equivalent command to Get-AzureRmLog for formal auditing?

### ISSUE THREAD

**Issue by rcarmo** [Azure/azure-cli#1569]
I'd like to access the audit logs for a specific resource group in the same way as `Get-AzureRmLog`. I can try to rummage inside every deployment, but that doesn't give me the same info.

**Comment by tjprescott** [comment]
This might be part of insights, which is currently still being worked on.

**Comment by rcarmo** [comment]
Thanks, is it scheduled/on roadmap so that I can assess if I need to develop a workaround?

**Comment by SychevIgor** [comment]
@tjprescott agree with @rcarmo this is really important! I don't know why we are releasing 2.0 sdk that not giving the same features as 1.0...

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.

**Comment by rcarmo** [comment]
Yeah, this is still active - on a cleanly installed az, there is still no equivalent command that I can fathom. Why close this without verification?

**Comment by derekbekoe** [comment]
I'm going to reopen this so we don't lose track of this.

**Comment by neilshannon** [comment]
This is a really important feature for us...

**Comment by tjprescott** [comment]
I believe the command you are looking for is `az monitor activity-log list`
