### ISSUE TITLE
"az monitor metrics alert list" not showing custom alert rules

### ISSUE THREAD

**Issue by philthynz** [Azure/azure-cli#15704]
If I define a custom alert rule, where the signal is "Custom log search". These alerts are not showing when I do a `az monitor metrics alert list --resource-group groupname --subscription subscriptionid -o table`

Only alerts that have the signal set as metric show up.

Is this expected?

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
You should try

```
az monitor alert list
```
