### ISSUE TITLE
WebApp:`az webapp create --runtime` not idempotent

### ISSUE THREAD

**Issue by Strepto** [Azure/azure-cli#15701]
## Describe the bug

**Command Name**
`az webapp create`

**Errors:**
```
Parameter with name WEBSITE_NODE_DEFAULT_VERSION already exists.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az webapp create --name {} --resource-group {} --plan {} --runtime "node|12-lts"`
- `az webapp create --name {} --resource-group {} --plan {} --runtime "node|12-lts"`

## Expected Behavior

Running the same command twice should produce same result.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.13.0 *

Extensions:
application-insights 0.1.11

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@calvinsID seems like the test test_webapp_up_change_runtime_version is also failing due to the same reason - can you take a look?
