### ISSUE TITLE
The examples for storage container create are incorrect.

### ISSUE THREAD

**Issue by christopher-o-toole** [Azure/azure-cli#15706]
**Describe the bug**

According to the [rules for naming Azure resources](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftstorage), only lowercase letters, numbers, and hyphens are allowed in a storage container name, yet the examples for `az storage container create` provide the sample name `MyStorageContainer`.

**To Reproduce**

Run `az storage container create --help`  and scroll down to the examples section. All of the provided examples use the invalid storage container name `MyStorageContainer`.

```
Examples
    Create a storage container in a storage account.
        az storage container create -n MyStorageContainer

    Create a storage container in a storage account and return an error if the container already
    exists.
        az storage container create -n MyStorageContainer --fail-on-exist

    Create a storage container in a storage account and allow public read access for blobs.
        az storage container create -n MyStorageContainer --public-access blob
```

**Expected behavior**

For  `MyStorageContainer` to be replaced with `mystoragecontainer`.

```
Examples
    Create a storage container in a storage account.
        az storage container create -n mystoragecontainer

    Create a storage container in a storage account and return an error if the container already
    exists.
        az storage container create -n mystoragecontainer --fail-on-exist

    Create a storage container in a storage account and allow public read access for blobs.
        az storage container create -n mystoragecontainer --public-access blob
```

**Environment summary**

This issue will occur no matter the installation method.

**Comment by yonzhan** [comment]
storage
