### ISSUE TITLE
WebApp:Unable to delete / disable deployment user via CLI

### ISSUE THREAD

**Issue by heniu75** [Azure/azure-cli#15705]
The documentation shows how to show and how to set the user. How on earth may I remove or disable these credentials? Unfortunately I can find no information on this topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea54d36-cb69-577c-e114-2c4bd0e33728
* Version Independent ID: 812e7aa5-2e8a-f9ef-d922-df188bd6275a
* Content: [az webapp deployment user](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/user?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/deployment/user.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/deployment/user.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by panchagnula** [comment]
@heniu75 are you suggesting that this is available via portal but not via CLI?

**Comment by avanigupta** [comment]
@panchagnula I ran into the same issue today. I updated deployment credentials using `az webapp deployment user set` command, but I can't find any documentation on how to reset deployment credentials for all the webapps in my subscription. Not sure if it's even possible to do this.

**Comment by panchagnula** [comment]
@avanigupta this not a CLI specific question ; @btardif do you know of any documentation about reset creds?

**Comment by petebytes** [comment]
Same question, I can set and show user - how do I delete the user?

**Comment by carlosrenemendoza** [comment]
el mismo problema como desabilitar el usuario de deployment
