### ISSUE TITLE
Can not create AppGW v2 without private ip.

### ISSUE THREAD

**Issue by hisasima** [Azure/azure-cli#15712]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I used below command to create AppGW v2 but it was failed.

$ az network application-gateway create -n myApplicationGateway -l canadacentral -g 3myResourceGroup --sku Standard_v2 --public-ip-address myPublicIp --vnet-name myVnet --subnet mySubnet

Deployment failed. Correlation ID: 12855b3e-7235-4b30-8527-993023968170. {
  "error": {
    "code": "ApplicationGatewayFrontendIpPrivateIpAddressInvalidAllocationType",
    "message": "FrontendIpConfiguration /subscriptions/66bef1e6-a2cb-4f94-a009-eaacf5ae1be3/resourceGroups/3myResourceGroup/providers/Microsoft.Network/applicationGateways/myApplicationGateway/frontendIPConfigurations/appGatewayPrivateFrontendIP of Application Gateway with SKU tier Standard_v2 can only use PrivateIPAddress with IpAllocationMethod as Static.",
    "details": []
  }
}

When I used below command, it was successful.

$ az network application-gateway create -n myApplicationGateway -l canadacentral -g 3myResourceGroup --sku Standard_v2 --public-ip-address myPublicIp **--private-ip-address 11.1.0.4** --vnet-name myVnet --subnet mySubnet

I know we can create AppGW v2 without private ip so this is bug of Azure CLI.

**Comment by tnotheis** [comment]
Same issue here. Yesterday the same command worked without specifying a private IP.

**Comment by yonzhan** [comment]
network

**Comment by giatule** [comment]
I got the same issue

**Comment by giatule** [comment]
I passed the issue by add the specified IP with the defined subnet created for APPGW.
az network application-gateway create \
  --name "$appgw_name" \
  --location japaneast \
  --resource-group "$myResourceGroup" \
  --vnet-name "$vnet_vnetname" \
  --subnet "$appgw_sn_name" \
  --capacity 2 \
  --sku Standard_v2 \
  --http-settings-cookie-based-affinity Disabled \
  --frontend-port 80 \
  --http-settings-port 80 \
  --http-settings-protocol Http \
  --public-ip-address myAGPublicIPAddress \
  **--private-ip-address 11.1.0.200**

**Comment by haroldrandom** [comment]
If `--private-ip-address` is not provided, Azure CLI would create a default private IP inside the default private subnet and it's IP address is dynamically created. And if `--private-ip-address` is provided, the allocation method is static.

I think it's a feature or restriction added from the service side. If you about to create an AppGw with default sku, it would succeed. But if with Standard_v2 SKU, it wouldn't allow.

**Comment by hisasima** [comment]
I think below fix is related to this issue. After this fix, we fail to create AppGW without private ip.

https://github.com/Azure/azure-cli/pull/15255/files/8c1cbdf50b50ecd8dda7c577c54e7d54f6ac8b62

**Comment by haroldrandom** [comment]
> I think below fix is related to this issue. After this fix, we fail to create AppGW without private ip.
> 
> https://github.com/Azure/azure-cli/pull/15255/files/8c1cbdf50b50ecd8dda7c577c54e7d54f6ac8b62

Are you using the latest Azure CLI?

**Comment by haroldrandom** [comment]
@hisasima It is a regression introduced last time, the original goal is to able to create an application gateway with both public IP and private IP. 
We will plan a way to think about how to fix it.
