### ISSUE TITLE
--subscription parameter not mentioned in the page

### ISSUE THREAD

**Issue by sachiney** [Azure/azure-cli#15716]
I tried to run/test the commands and got error message 'Resource group not found'. In the previous steps I was logging into the subscription so I thought It would just use the subscription from context. But that was not the case and I had to provide --subscription <subs> and the error was resolved. Although --subscription tag is not found in the page, it can be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ad2a0dd-d117-e9d6-6539-ea299df7c1b5
* Version Independent ID: 6b1b933d-d4fc-57a7-e372-43e6c4fb3ebe
* Content: [az synapse workspace firewall-rule](https://docs.microsoft.com/en-us/cli/azure/ext/synapse/synapse/workspace/firewall-rule?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/synapse/synapse/workspace/firewall-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/synapse/synapse/workspace/firewall-rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by idear1203** [comment]
@sachiney could you please provide the issued command?

**Comment by sachiney** [comment]
Below command with my firewall name/subscription/workspace/resourcegroup details was successful.
az synapse workspace firewall-rule create --name "MYIP001" --resource-group "USERRSG001" --workspace-name "USEDASW001" --subscription "<my_subs>" --start-ip-address "255.255.255.1" --end-ip-address "255.255.255.2"

It failed without the --subscription "<my_subs>" part .

**Comment by idear1203** [comment]
I cannot reproduce the issue on my machine. The command can be successful without --subscription. @yonzhan do you have any suggestions to debug the issue? I suppose this is a general CLI issue. By the way, @sachiney , are you able to run other commands? For example, `az synapse workspace list` or `az storage account list`?

**Comment by sachiney** [comment]
Ohh okay. I think now I understood it. I was running the CLI command through ansible task and I think in Ansible the context is not getting set the way it gets set in Powershell. So, I need to provide the subscription each time.
Same was the case for workspace list - in CLI it runs fine as context is set but not through ansible without --subscription.

**Comment by yonzhan** [comment]
Add @jsntcy in case any help is needed from CLI team.
