### ISSUE TITLE
WebApp:Issue relating creating appservice plan

### ISSUE THREAD

**Issue by link78** [Azure/azure-cli#15728]
## Describe the bug

**Command Name**
`az appservice plan create`

**Errors:**
```
Requested feature is not available in resource group fasolab-rg. Please try using a different resource group or create a new one.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan create -g {} -n {} --sku {} --is-linux`

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0

Extensions:
ai-examples 0.2.4

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by panchagnula** [comment]
@link78 I see that you are creating a Linux ASP on this RG - does this RG already host ASPs that have windows applications. Currently we can't mix Linux & windows resources under the same RG. Can you try with a new empty RG & let us know if you see the same error? Thanks!

@sanchitmehta can you help here - creating a Linux ASP is giving the following error "Requested feature is not available in resource group fasolab-rg. Please try using a different resource group or create a new one."
Under what conditions do we limit this creation? Can the error message be clearer on what needs to be done?

**Comment by MarkAtAgilliance** [comment]
Chiming in here.  Happy to start a new thread if this you feel this is not related.

I have a similar problem.  the Resource Group I am using has only ever had one App Service Plan and it was Windows hosted.  I deleted all the webapps then the app service plan then tried to recreate exactly the same App Service plan.  It fails with this error.  

I have waited for an hour just in case it was a sync issue on the delete.  no luck.  

I checked Resource Explorer and could not find anything that looks like a linux service in that RG.

Are there other service types that will cause a lock out like this?  Thanks.

**Comment by ThejaChoudary** [comment]
@link78  Please use different resource group to deploy linux ASP  if the resouce group you are using currently has a windows based ASP. 
Please let us know if you need any further or else we will proceed to close the issue.
Thanks!

**Comment by ThejaChoudary** [comment]
FYI @panchagnula When we are creating a linux asp while having a windows based ASP we are getting the error as 
error:"You cannot change the OS hosting your app at this time. Please recreate your app with the desired OS" when we already have a windows"

**Comment by ThejaChoudary** [comment]
@MarkAtAgilliance Apps running on Windows Containers are available only in Hyper-V Container enabled SKU and same with the linux also .Please feel free to log a new issue if you still have any queries.

**Comment by ThejaChoudary** [comment]
Proceeding to close the issue ,please feel free to reopen if the issue persists. Thank you!
