### ISSUE TITLE
Incorrect error message for max length of resource group

### ISSUE THREAD

**Issue by codingoutloud** [Azure/azure-cli#15727]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

The `az group create` command returns a ValidateError inconsistent with behavior.

Attempting to create a resource group with a 91 character name complains: `"ValidationError: Parameter 'resource_group_name' must have length less than 90."`

However, creating a 90 char name works (and 90 is not "less than 90"). So the message should read something like: `"ValidationError: Parameter 'resource_group_name' must have length no more than 90."`

**To Reproduce**

# 90 char length SUCCEEDS
`az group create -l eastus -n "123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"` # 90 chars

# 91 char length FAILS
`az group create -l eastus -n "123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890x"` # 91 chars
# RETURNS ERROR: "ValidationError: Parameter 'resource_group_name' must have length less than 90."

**Expected behavior**

`az group create -l eastus -n "123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890x"` # 91 chars

Should RETURN ERROR: "ValidationError: Parameter 'resource_group_name' must have length no more than 90."

**Environment summary**

Azure Shell

**Additional context**

Azure CLI version 2.14.0

https://github.com/azure/azure-cli/issues/new?body=%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.+Please+review+and+update+as+needed.%2A%2A%0A%0A%23%23+Describe+the+bug%0A%0A%2A%2ACommand+Name%2A%2A%0A%60az+group+create%60%0A%0A%2A%2AErrors%3A%2A%2A%0A%60%60%60%0AValidationError%3A+Parameter+%27resource_group_name%27+must+have+length+less+than+90.%0A%60%60%60%0A%0A%23%23+To+Reproduce%3A%0ASteps+to+reproduce+the+behavior.+Note+that+argument+values+have+been+redacted%2C+as+they+may+contain+sensitive+information.%0A%0A-+_Put+any+pre-requisite+steps+here..._%0A-+%60az+group+create+-l+%7B%7D+-n+%7B%7D%60%0A%0A%23%23+Expected+Behavior%0A%0A%23%23+Environment+Summary%0A%60%60%60%0ALinux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid+%28Cloud+Shell%29%0APython+3.6.10%0AInstaller%3A+DEB%0A%0Aazure-cli+2.14.0%0A%0AExtensions%3A%0Aai-examples+0.2.4%0A%0A%60%60%60%0A%23%23+Additional+Context%0A%0A%3C%21--Please+don%27t+remove+this%3A--%3E%0A%3C%21--auto-generated--%3E%0A%0A&template=Bug_report.md

**Comment by yungezz** [comment]
cc @houk-ms for awareness

**Comment by yonzhan** [comment]
add to S178

**Comment by zhoxing-ms** [comment]
This is a issue related to msrest, I have opend a issue on their repo: Azure/msrest-for-python#219

**Comment by RakeshMohanMSFT** [comment]
@codingoutloud Error message updated 
az group create -l eastus -n "123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890x"
(InvalidResourceGroup) The provided resource group name '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890x' has a length of '91' which exceeds the maximum length of '90'.
Code: InvalidResourceGroup
Message: The provided resource group name '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890x' has a length of '91' which exceeds the maximum length of '90'.
