### ISSUE TITLE
How to troubleshoot with Fiddler/mitmproxy (aka, how to use HTTPS_PROXY)

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1572]
If I `export HTTPS_PROXY=http://localhost:8080` with `mitmproxy` running, I get this from the CLI:

```
Please ensure you have network connection. Error detail: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
```

For the other CLIs, there is an env var that can be exported to disable the strict checking and allow this for debug scenarios. Is that an equivalent for `az`?

**Comment by colemickens** [comment]
(I'm looking for the equivalent of `NODE_TLS_REJECT_UNAUTHORIZED` in xplat-cli.)

**Comment by colemickens** [comment]
(The CA is trusted by my machine as well, I can curl/wget https://www.google.com with traffic appearing in `mitmproxy` without any insecure flags)

**Comment by tjprescott** [comment]
@colemickens try setting the following environment variables: ADAL_PYTHON_SSL_NO_VERIFY and AZURE_CLI_DISABLE_CONNECTION_VERIFICATION.

**Comment by tjprescott** [comment]
@colemickens did this unblock your scenario?

**Comment by colemickens** [comment]
Yes. Thank you!

**Comment by jiasli** [comment]
[Working behind a proxy](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#work-behind-a-proxy) provides detailed instructions on how to trust a custom root certificate.

**Comment by jiasli** [comment]
See https://github.com/Azure/azure-cli/issues/11436
