### ISSUE TITLE
WebApp:'az webapp ssh' not work for both Linux and windows webapps.

### ISSUE THREAD

**Issue by shenqianjin** [Azure/azure-cli#15729]
**Describe the bug**
C:\Users\qianjinshen>az webapp ssh --subscription 685ba005-af8d-4b04-8f16-a7bf38b2eb5a -n qianjinshen-wl-01 -g qianjinshen
This command is in preview. It may be changed/removed in a future release.
webapp ssh is only supported on linux and mac

C:\Users\qianjinshen>

**** Note that "qianjinshen-wl-01" is a Linux web app. ****

**To Reproduce**
Just execute the command.

**Expected behavior**
works like expected, better to support windows as well.

**Environment summary**
C:\Users\qianjinshen>az -v
azure-cli                         2.14.0

core                              2.14.0
telemetry                          1.0.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\qianjinshen\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

C:\Users\qianjinshen>

**Additional context**

![image](https://user-images.githubusercontent.com/19339116/97654004-fefac600-1a9c-11eb-9a0b-2d9a3a18105d.png)

**Comment by yungezz** [comment]
route to webapp team

**Comment by mloskot** [comment]
IMHO, the error message is unclear, see https://github.com/Azure/azure-cli/issues/12940#issuecomment-737152145

**Comment by btardif** [comment]
This is being tracked here:  #16125
