### ISSUE TITLE
WebApp:Make setting of complex appsettings easier by just allowing to upload regular JSON

### ISSUE THREAD

**Issue by ModernRonin** [Azure/azure-cli#15723]
# Problem
Say you have a complex settings structure like:
```javascript
{
    "Logging": 
    {
        "LogLevel": 
        {
            "Default": "Error"
        }
    },
    "Gateways": 
    {
        "Apple": "x",
        "Banana": "y"
    }
}
```
that you want to set via the az cli. Currently, you have to transform this into a format like
```javascript
[
    { "name": "Logging:LogLevel:Default", "value": "Error", "slotSetting": false },
    { "name": "Gateways:Apple", "value": "x", "slotSetting": false},
    { "name": "Gateways:Banana"value": "y", "slotSetting": false}
]
```
in order to then be able to set it for a webapp or a function app with either of
```shell
az functionapp config appsettings set --name <myFunctionName> --settings "@<temporaryFile>.json"
az webapp config appsettings set --name <myWebAppName> --settings "@<temporaryFile>.json"
```

This is really quite tedious because usually one has either some ready JSON files in the regular, nested format or one works with a combination of in-memory arrays and dictionaries that nicely map to regular JSON.

# Proposed Solution
Allow specifying regular json-files via new command-line option
```shell
az functionapp config appsettings set --name <myFunctionName> --json-settings <pathToJsonFile>[--is-slot-settings true|false]
```
Notes:
* by adding a new option `--json-settings` existing scripts are not broken
* pathToJsonFile would point to a file with regular nested JSON
* `--is-slot-settings` would be optional and specify for the whole file whether the entries count as slot settings or not, with a default of false (if the option is not given); `--is-slot-settings` would only be allowed in conjunction with `--json-settings`; if someone as a nested appsettings structure where only some properties are slot-settings, they would have to split the settings into two JSON files and perform two calls, one for each JSON file, each with the corresponding value for `--is-slot-settings`

In essence, you'd really implement for us what otherwise we have to do ourselves, ie, the transformation from regular JSON to that specific flattened structure.

What do you think?
Cheers,
MR

**Comment by yungezz** [comment]
route to appropriate team

**Comment by panchagnula** [comment]
@ModernRonin CLI command lets you add a JSON file by using --settings which takes JSON file as an input
az webapp config appsettings set -g MyResourceGroup -n MyUniqueApp --settings  @moreSettings.json

The complex structure you are requesting is not supported by the backend or API at this time & so not a CLI specific issue

**Comment by ModernRonin** [comment]
There is no need to change the backend API. 

The CLI would just need to convert from regular JSON settings to the very specific nested format the backend API expects. (Which is what currently we users of the CLI have to do.)
