### ISSUE TITLE
Defaults not accepted for all commands

### ISSUE THREAD

**Issue by BhargaviAnnadevara-MSFT** [Azure/azure-cli#15724]
## Describe the bug

**Command Name**
`az group create`

**Errors:**
```
RequiredArgumentMissingError: the following arguments are required: --name/--resource-group/-n/-g
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Configured defaults as follows:
```
az configure -d group=tstgrp001-rg
az configure -d location=westeurope
```
- Run `az group create`

## Expected Behavior
The expectation is that the command should pick the configured defaults from the Azure CLI config file located at `$AZURE_CONFIG_DIR/config` but it does not, and returns the error mentioned above.

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.14.0
azure-cli-iot-ext 0.8.10

Extensions:
alertsmanagement 0.1.0
azure-cli-iot-ext 0.8.10
azure-devops 0.18.0
dev-spaces 1.0.5
managementpartner 0.1.3
mesh 0.10.6
resource-graph 1.1.0

```

**Comment by BhargaviAnnadevara-MSFT** [comment]
@Makovec FYI.

**Comment by yonzhan** [comment]
add to S178

**Comment by zhoxing-ms** [comment]
Hi @BhargaviAnnadevara-MSFT  this is by design. `az configure` and `az config` are not used to set the default value for all commands
Commands that can set default values will be prompted in help, such as `az webapp up -h`

```pwsh
PS > az webapp up -h
...
Resource Id Arguments
    ...
    --resource-group -g : Name of resource group. You can configure the default group using `az
                          configure --defaults group=<name>`.
```
However `az group create` does not indicate support for default values
```pwsh
PS C:\Users\zhoxing.FAREAST\Desktop> az group create -h
...
Arguments
...
    --name --resource-group -g -n [Required] : Name of the new resource group.
```
