### ISSUE TITLE
Missing required python version in various setup.py files

### ISSUE THREAD

**Issue by con-f-use** [Azure/azure-cli#15720]
Currently, pip assumes 2.14.0 is the latest version for all python interpreters and installs that version. This causes errors like this on older python versions:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/confus/.local/share/virtualenvs/specter-yzp-I12c/lib/python3.2/site-packages/azure/cli/core/commands/__init__.py", line 425
    def cached_put(cmd_obj, operation, parameters, *args, setter_arg_name='parameters', **kwargs):
                                                                        ^
SyntaxError: invalid syntax
```

This probably a systemic problem in more than one of the azure libraries and because older packages with this error are already on pypi.org, it is hard to solve in retrospect. See https://github.com/Azure/azure-cli/pull/15719

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls take a look? thanks

**Comment by con-f-use** [comment]
Sorry, but I have to point out that this issue is **NOT** in fact fixed, because the older azure packages on e.g. pypi.org are still missing properly declared python_versions. I.e. they pretend to support Python 2, when they are Python-3-only.

**Comment by jiasli** [comment]
Do you mean old versions of Azure CLI or other Azure packages? On PyPI, once a version is released, it becomes a snapshot and can't be updated (https://github.com/pypa/packaging-problems/issues/74), so it is not possible for us to backport the change to older versions of Azure CLI.

**Comment by con-f-use** [comment]
I mean both actually. However, I didn't realize that old package cannot simply be deleted completely and then just re-uploaded as below. Thanks for the issue link. Also I'm aware that even if it was possible, it would change the file hashes that tools like Pipenv and Poetry use for version pinning. Guess there's nothing that can be done about it, then. Luckily, it will become less of an issue with time.


![PyPI delete release](https://user-images.githubusercontent.com/11145016/120324093-82f08700-c2e6-11eb-931b-4568ed68915c.png)

**Comment by jiasli** [comment]
If you see other Azure packages (excluding Azure CLI `azure-cli`) has the same issue, feel free to create an issue to their corresponding GitHub repo. 

> Guess there's nothing that can be done about it, then. Luckily, it will become less of an issue with time.

Exactly, without specifying a version, `pip` automatically installs the latest version, so this has already been solved for most users.
