### ISSUE TITLE
Steaming uploads to Azure storage

### ISSUE THREAD

**Issue by onpaws** [Azure/azure-cli#15732]
**Is your feature request related to a problem? Please describe.**
Sometimes it's useful to upload data that's a raw byte steam, aka not a file. This appears to not be possible. 

**Describe the solution you'd like**
Standard Unix tools support piping data across commands, would be helpful if users could pipe STDIN into some appropriate Azure storage option. 

**Describe alternatives you've considered**

**Additional context**
@Juliehzl 
https://github.com/Azure/azure-cli/issues/10090

**Comment by yonzhan** [comment]
add to S178

**Comment by Juliehzl** [comment]
Hi @onpaws, we may support the feature but may be in extension repo first and then moving to main cli.

**Comment by onpaws** [comment]
Thanks for the update. What is the extension repo, is that where new `azure-cli` features begin life?

**Comment by Juliehzl** [comment]
https://github.com/Azure/azure-cli-extensions
It works like a patch for main cli to give customer preview feature experience but will not influence existing cli commands, because it only take effect when you install it.

**Comment by Juliehzl** [comment]
dupe with #3447

**Comment by onpaws** [comment]
If anyone else doesn't want to wait on this, I recently learned the JavaScript SDK already supports streaming uploads. 

Following [this](https://docs.microsoft.com/en-us/samples/azure-samples/azure-sdk-for-js-storage-blob-stream-nodejs/stream-blobs-nodejs/) using the so-called [blockBlobClient](https://github.com/Azure-Samples/azure-sdk-for-js-storage-blob-stream-nodejs/blob/f31f649a470d51cf4c2ee0ebffe6ae4e0ff657f7/v12/routes/index.js#L82) ended up serving my needs satisfactorily. 

Would still prefer to use the CLI to avoid maintaining yet another app -- fortunately, if I understand right, it seems there may be some positive development [on this front](https://github.com/Azure/azure-sdk-for-python/blob/0659533bdced45f72a8b3e62e2d44e3ce2b58ff7/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L352) and hopeful it might land in the CLI one day

**Comment by Juliehzl** [comment]
Hi @onpaws, you are right that there is sdk support for uploading stream and CLI would support it by 12/29 due to limited bandwidth.

**Comment by baelter** [comment]
Seems it still has not made it into the CLI?

**Comment by onpaws** [comment]
I haven't checked, but a bit disappointing if true. 
Could you please share an example of the command you're trying? With that, perhaps someone can point us in the right direction.

**Comment by baelter** [comment]
I want to stream blob upload from stdin, but can't find any command for that.

**Comment by evelyn-ys** [comment]
Hi @baelter @onpaws, it's already supported in cli extension. See https://github.com/Azure/azure-cli-extensions/pull/2799

You can first install the extension with
```
az extension add storage-blob-preview
```
And then try
```
# Upload a string to a blob.
az storage blob upload --data "teststring" -c mycontainer -n myblob --account-name mystorageaccount --account-key 0000-0000

# Upload through pipe.
echo $data | az storage blob upload --data @- -c mycontainer -n myblob --account-name mystorageaccount --account-key 0000-0000
```

**Comment by onpaws** [comment]
> Hi @baelter @onpaws, it's already supported in cli extension. See https://github.com/Azure/azure-cli-extensions/pull/2799
> 
> 
> 
> You can first install the extension with
> 
> ```
> 
> az extension add storage-blob-preview
> 
> ```
> 
> And then try
> 
> ```
> 
> # Upload a string to a blob.
> 
> az storage blob upload --data "teststring" -c mycontainer -n myblob --account-name mystorageaccount --account-key 0000-0000
> 
> 
> 
> # Upload through pipe.
> 
> echo $data | az storage blob upload --data @- -c mycontainer -n myblob --account-name mystorageaccount --account-key 0000-0000
> 
> ```

Thanks! Will give this a try. 

By the way do you know of eg a Docker image with the extension already installed? I use it in a CI env and would be preferable to have the extension ready to go. Thank you!
