### ISSUE TITLE
Bug with New-AzFunctionApp with Azure Gov

### ISSUE THREAD

**Issue by DiscoveringWorld** [Azure/azure-cli#15738]
Hello,
I logged with Connect-AzAccount  -Environment AzureUSGovernment
I created a storage on USGov Virginia. 
After I tried to create an new function app with New-AzFunctionApp.  
This command failed with The server responded with a Request Error, Status: BadRequest.

When I check the debug details its show that on the server side it try to use the public endpoint of the storage and not the azure gov endpoint storage123455622.file.core.usgovcloudapi.net/

This is the error:
  "ErrorEntity": {
        "ExtendedCode": "01020",
        "MessageTemplate": "There was a conflict. {0}",
        "Parameters": [
          "The remote name could not be resolved: 'storage123455622.file.core.windows.net'"
        ],
        "Code": "BadRequest",
        "Message": "There was a conflict. The remote name could not be resolved: 'storage123455622.file.core.windows.net'"

**Comment by yonzhan** [comment]
Please open this issue in azure-powershell repo.

**Comment by DiscoveringWorld** [comment]
ok
