### ISSUE TITLE
az group show in sandbox environment returns error

### ISSUE THREAD

**Issue by rmariboe** [Azure/azure-cli#15744]
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/rune_mariboe/.azure/commands/2020-11-01.14-47-34.group_show.283.log'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 511, in execute
    load_cmd_tbl_func=self.commands_loader.load_command_table, args=args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 164, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 86, in init_command_file_logging
    self._init_command_logfile_handlers(cmd_logger, args)  # pylint: disable=protected-access
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/azlogging.py", line 108, in _init_command_logfile_handlers
    logfile_handler = logging.FileHandler(log_file_path)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/az/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/rune_mariboe/.azure/commands/2020-11-01.14-47-34.group_show.283.log'

And:

## Describe the bug

**Command Name**
`az group show`

**Errors:**
```
ForbiddenError: The client 'live.com#[**REDACTED**]' with object id 'ed08d33f-cf72-4dc7-9329-e169982d8b8a' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/66d3dea9-da3f-4284-8bb4-eb7b757334a3/resourcegroups/learn-d45a2a68-74b8-4dad-8003-07930dde6ee3' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group show --name {}`

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0

Extensions:
ai-examples 0.2.4

```

**Comment by rmariboe** [comment]
Also, the newly created sandbox has only 52 minutes left. Maybe I got someone else's sandbox?

**Comment by rmariboe** [comment]
Manually recreating storage account helped...

**Comment by yonzhan** [comment]
@zhoxing-ms
