### ISSUE TITLE
Carriage return being added to output?

### ISSUE THREAD

**Issue by Teodelas** [Azure/azure-cli#15745]
**Describe the bug**
I'm seeing carriage returns being added it outputs.  As an example, I'm unable to create eventgrid subscription by passing bash variables that are populated by other az cli commands.

**To Reproduce**
iothub=$(az iot hub list -g adtdemo --query [].id -o tsv)
function=$(az functionapp function show -n teotwinfunction -g adtdemo --function-name twinsfunction --query id -o tsv)
az eventgrid event-subscription create --name IoTHubEvents --source-resource-id $iothub --endpoint $function -
-endpoint-type azurefunction --included-event-types Microsoft.Devices.DeviceTelemetry

If I pass the values in the bash variables everything works as expected.

I can see \r in the values passed when I run the commands with the --debug --verbose commands

**Comment by yonzhan** [comment]
Core

**Comment by KaiWalter** [comment]
same here

```
az resource delete --ids $(az sf cluster show --cluster-name my-cluster --query id -o tsv) --verbose
```

ends up with a 

```
400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/.../resourcegroups/.../providers/Microsoft.ServiceFabric/clusters/my-cluster%0D?api-version=2020-03-01
```

**Comment by KaiWalter** [comment]
@Teodelas I had to upgrade from `2.9.1` to `2.20.0` to get rid of this error.

**Comment by jiasli** [comment]
Please see the explanation at https://github.com/Azure/azure-cli/issues/13573#issuecomment-6506865310
