### ISSUE TITLE
Fix Log Analytics data export CLIs

### ISSUE THREAD

**Issue by yossi-y** [Azure/azure-cli#15742]
**Resource Provider**
operationalinsights

**Description of Feature or Work Requested**
Log Analytics data export CLI includes '--all' and '--export-all-tables' which were removed in swaggers.
1. Removed these in CLI.
2. The example in CLI doesn't include Tables as required parameter. Tables should be added to required parameters:
az monitor log-analytics workspace data-export create **--tables** --destination
                                                      --name
                                                      --resource-group
                                                      --workspace-name
                                                      [--all {false, true}]
                                                      [--enable {false, true}]
                                                      [--subscription]

**Minimum API Version Required**
2020-08-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2020-08-01

**Target Date**
We get support cases for it, please do at the first update iteration you can.

**Comment by yonzhan** [comment]
add to S179

**Comment by yossi-y** [comment]
Could you add the date, since I'm not familiar with sprint count?

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/milestones
