### ISSUE TITLE
WebApp:az webapp up --runtime option should either be implemented or removed

### ISSUE THREAD

**Issue by roalexan** [Azure/azure-cli#15747]
Here's the doc for az webapp up. It says there is a --runtime option
https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_up

However, if I do:

call az webapp up --plan %app_plan% --name %app_name% --subscription %subscription_id% --resource-group %resource_group_name% --runtime "abc"

I get the error:

az: error: unrecognized arguments: --runtime abc

plus, az webapp up --help doesn't show a --runtime option.

If there is no --runtime option, it needs to be removed from the documentation. Or better yet, it should be implemented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by btardif** [comment]
@calvinsID this looks like a bug since we always want to *auto-detect* runtime for UP scenarios. `--runtime` parameter should be removed

FYI @panchagnula

**Comment by btardif** [comment]
@roalexan the --runtime option is new. To use it you will need to update your CLI to latest release.
