### ISSUE TITLE
az vm host group create, --platform-fault-domain-count required

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#15749]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

A user reported
```
PS C:\Users\zivr\OneDrive - Microsoft\LocalGit\AzureDedicatedHostsSamples> az vm host group create -l $location --name myHostGroup -g $rg  --automatic-placement true 
ValidationError: Parameter 'DedicatedHostGroup.platform_fault_domain_count' can not be None.
```
He said platform_fault_domain_count was not required before.

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
vm
