### ISSUE TITLE
Support cross tenant image/disk in vm/vmss/image-version related commands

### ISSUE THREAD

**Issue by arrownj** [Azure/azure-cli#15753]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Currently if some resource reference a cross tenant image/disk, the create/update command for it would fail if the executor has no permission to access the source tenant.

Commands list as following:

- `az vm create` [DONE]
- `az vmss create` [DONE]
- `az sig image-version create` [DONE]
- `az vmss update` [DONE]
- `az vm update` (image done, disk still not support)
- `az sig image-version update` (image done, disk still not support)
- `az vm disk attach`
- `az vm resize`
- `az vm boot-diagnostics get-boot-log / enable / disable`
- `az vm nic add / set`
-` az sig image-version update.` In fact, we have an additional question. When I do a request to update the list of regions in the image-version, is it a PATCH call or a combined GET & PUT call. Please see the attached thread for a scenario that AKS is experiencing. They send multiple az sig image-version update calls to incrementally publish their images to new regions 1 by 1, and some of these calls fails. In our service we see the various calls.

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
vm

**Comment by yungezz** [comment]
hi @arrownj could this issue be closed now since PR merge? could  you pls link PR? thanks.

**Comment by arrownj** [comment]
All the commands listed are supported in 2.15.0.
