### ISSUE TITLE
[Compute] Simplifying SSH access to Linux VMs

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#15769]
**Is your feature request related to a problem? Please describe.**

Support SSHPublicKey resource in CLI, and support VM creation using SSHKey resource.

**Describe the solution you'd like**

A new `sshkey` verb will be required in CLI.  

Upload a new key 

`az sshkey upload --ssh-key-value VALUE --ssh-key-name NAME` 

Create new Key Pair 

`az sshkey create --ssh-key-name NAME` 

  

If a key with the given name already exists fail with an error. 

  

The private key is stored in the client ~/.ssh directory 

List all keys 

`az sshkey list` 

Get the details of a Key 

`az sshkey show --ssh-key-name` 

Deleting a Key  

`az sshkey delete --ssh-key-name NAME` 

 

The user must confirm the operation or provide a `--yes` switch. 

Changes to `az vm create`  

VM keys can be used or created as part of the normal `az vm create` command. There are three options: 

Use an existing key stored in Azure 

Upload an existing public key 

Create a new SSH Key (providing one time download of the key pair while storing the public key in Azure) 

In order to achieve this it seems that all we need to do is add `--ssh-key-names` to existing commands. The question is whether we make this a required parameter or not. If it is not required then we will default to a default key name. 

Use Existing Key(s)  

` az vm create … --ssh-key-name NAME` 

  

The keys must exist or an error will be thrown. If they key does not exist an error is returned advising the user to add either `--ssh-key-value` or `--generate-ssh-keys` - see below.  

Upload and Use New Key(s) 

`az vm create --ssh-key-names NAMES --ssh-key-values VALUES'  

Create New Key Pair(s)  

`az vm create --ssh-key-names NAMES –generate-ssh-keys` 

  

In addition to the current behavior for `--generate-ssh-keys` this call will upload the key(s) to Azure. 

**Describe alternatives you've considered**

spec: https://microsoft-my.sharepoint.com/:w:/p/rogardle/ESNq5mqG3zhJkvIPfkDBY80B9baP4OqsVeMu58lzXumD-A?e=oWJ7DC&CID=0FE5A762-BCF1-40DE-8FEA-76D4599C0A85&wdLOR=c5B565221-F44A-484B-B48B-FC587A3CDAB7

Swagger link:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json#L1186-L1448
**Additional context**

**Comment by yungezz** [comment]
put into S179 now.

**Comment by qwordy** [comment]
It has released.
