### ISSUE TITLE
az login --identity fails from Azure VMs

### ISSUE THREAD

**Issue by shivabommakanti03** [Azure/azure-cli#15764]
When I install az cli on Azure VM and run `az login --identity` it gives me an error as below.  What should I do to fix this issue.
`AzureResponseError: Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned http error: 400, reason: Bad Request`

**Comment by yungezz** [comment]
hi @shivabommakanti03 from the error, has you enabled MSI of the VM?

**Comment by carlosporter** [comment]
I have seen this same error while trying to use az login and a user managed identity.

Originally the UMI was pointing to a resource group.

```
  # Get the source Id for the resource group where the UMI should have access
  AZ_RESOURCE_GROUP_ID="$( az group show --name $AZ_RESOURCE_GROUP --query 'id' -o tsv )"

  # Grant the "Owner" role to the UMI using the resource group as the scope
  az role assignment create --assignee $AZ_USER_ASSIGNED_IDENTITY_PRINCIPAL_ID --scope $AZ_RESOURCE_GROUP_ID --role "Owner"
```

Then I created a virtual machine on the same resource group and ran the command below:
```

[root@vm2900i21md1004 ~]# az login --identity --username /subscriptions/<secret>/resourcegroups/week30rg2480/providers/Microsoft.ManagedIdentity/userAssignedIdentities/UserAssignedIdentity_lnxadmin1627357711
Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned http error: 400, reason: Bad Request
[root@vm2900i21md1004 ~]# 
```

I solved the problem back assigning the UMI to the new virtual machine ( despite of it being on the same resource group ).

```
# Apply the UMI to the target virtual machine 
az vm identity assign --resource-group $AZ_RESOURCE_GROUP --name $AZ_VM_NAME --identities $AZ_USER_ASSIGNED_IDENTITY_NAME | sj userAssignedIdentities_${AZ_VM_NAME}
```

So, it seems attach the UMI to the resource group is not enough, I still have to attach it to the virtual machine from where I need to run "az login" ?

Regards,

**Comment by jiasli** [comment]
@shivabommakanti03, please make sure managed identity is configured correctly on the VM. 

See https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-portal-windows-vm
