### ISSUE TITLE
Upgrade the azure-mgmt-core in cli core

### ISSUE THREAD

**Issue by qiaozha** [Azure/azure-cli#15766]
The latest autorest.python 5.4.0 has resolved an important issue of duplicate base class properties in multi-layer inheritance. But it has upgraded the dependency of azure-mgmt-core to 1.2.1 at the same time and azure-cli-core is still using 1.2.0

And autorest.az has already upgraded to the latest autorest.python 5.4.0.

To make it work azure-cli-core need to release a new version with latest azure-mgmt-core 1.2.1.

**Comment by yonzhan** [comment]
core
