### ISSUE TITLE
az aks update: "unrecognized arguments: -—load-balancer-outbound-ips"

### ISSUE THREAD

**Issue by michaelschmit** [Azure/azure-cli#15770]
Trying to update the public IP for my aks cluster via the az aks update command I'm receiving the error:
`unrecognized arguments: -—load-balancer-outbound-ips`

The command I am replicating from documentation is:
`az aks update \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --load-balancer-outbound-ips <publicIpId1>,<publicIpId2>
`

Originally I was on az cli version 2.12 and aks preview 0.4.33.  I upgraded to az cli version 2.14 and aks preview 0.4.65, but that didn't help.  I tried to remove az extension aks-preview but that didn't work either.  Is the documentation wrong or is there a bug here?

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/aks.yml)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to service team

**Comment by michaelschmit** [comment]
I should note that I am running on MacOS.

**Comment by michaelschmit** [comment]
Any chance this could get assigned for someone to look at?  I've gone into github and looked at the azure aks extension.  I followed the code but was unable to figure out what might be causing this issue.
