### ISSUE TITLE
using az component update ends in a "10525 Segmentation fault"

### ISSUE THREAD

**Issue by pms1969** [Azure/azure-cli#1578]
I'm running arch linux, have installed python, and done a pip install azure-cli.  That all worked fine.

When I run `az component update` I get the following
```
[paul@arch-sb tools]$ az component update
  Running setup.py install for pycparser ... done
  Running setup.py install for cryptography ... done
  Running setup.py install for secretstorage ... done
  Running setup.py install for isodate ... done
  Running setup.py install for oauthlib ... done
  Running setup.py install for chardet ... done
  Running setup.py install for applicationinsights ... done
  Running setup.py install for pyyaml ... done
  Running setup.py install for sshtunnel ... done
/home/paul/.local/bin/az: line 13: 10525 Segmentation fault      (core dumped) python -m azure.cli "$@"
[paul@arch-sb tools]$ 

```

Any help would be appreciated.

It's worth noting that this is a VirtualBox VM running on a SurfaceBook.

**Comment by derekbekoe** [comment]
@pms1969 Can you provide a few details:
1. What Python version is installed?
2. What pip version is installed?
3. What's the output from `az --version`?
4. What's the output from `az component update --debug`?

**Comment by pms1969** [comment]
damn, started writing this yesterday, and obviously didn't hit the button. :-(

1. 
```
[paul@arch-sb dotcom]$ python --version
Python 3.5.2
```
2.
```
[paul@arch-sb dotcom]$ pip --version
pip 9.0.1 from /home/paul/.local/lib/python3.5/site-packages (python 3.5)
```
3. 
```
[paul@arch-sb dotcom]$ az --version
azure-cli (0.1.0b11)

acr (0.1.0b11)
acs (0.1.0b11)
appservice (0.1.0b11)
cloud (0.1.0b11)
component (0.1.0b11)
configure (0.1.0b11)
container (0.1.0b11)
context (0.1.0b11)
core (0.1.0b11)
feedback (0.1.0b11)
network (0.1.0b11)
nspkg (0.1.0b11)
profile (0.1.0b11)
resource (0.1.0b11)
role (0.1.0b11)
storage (0.1.0b11)
vm (0.1.0b11)

Python (Linux) 3.5.2 (default, Nov  7 2016, 11:31:36)
[GCC 6.2.1 20160830]
```
4. see attached file.

[debug.txt](https://github.com/Azure/azure-cli/files/656709/debug.txt)

**Comment by derekbekoe** [comment]
@pms1969 thanks for the version information.
In the debug.txt file attached, it looks like the 'Content' from `az component update --debug` has been truncated.

**Comment by pms1969** [comment]
damn.  it was completely wrong.  :-s  Hopefully this one is better.

[debug.txt](https://github.com/Azure/azure-cli/files/657887/debug.txt)

**Comment by derekbekoe** [comment]
Thanks.
Can you also provide output from `$ uname -a`?

**Comment by pms1969** [comment]
```
[paul@arch-sb azure-templates]$ uname -a
Linux arch-sb 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
```

**Comment by derekbekoe** [comment]
Thanks @pms1969 for all the information.
Investigating...

**Comment by pms1969** [comment]
Cheers.

**Comment by derekbekoe** [comment]
I can repro using a Docker image of python with:
```
$ sudo docker run -it python:3.5 bash
$ pip install azure-cli
$ az component update
```

The exact cause is yet to be determined and the only error message is ``Segmentation fault      (core dumped) python -m azure.cli "$@"`` which doesn't provide much insight.

**Comment by pms1969** [comment]
yeah, it's a bit baffling

**Comment by derekbekoe** [comment]
Update to azure-cli-component published that includes this fix.
https://pypi.python.org/pypi/azure-cli-component/0.1.0b12

**Comment by derekbekoe** [comment]
Install the CLI again and this issue will be resolved.

**Comment by pms1969** [comment]
confirmed.  thanks.
