### ISSUE TITLE
[Network] add "az network express-route port generate-loa" for generating Letter of Authorization

### ISSUE THREAD

**Issue by amwate** [Azure/azure-cli#15790]
Resource Provider

Network

Description of Feature or Work Requested

We have updated the Azure-Powershell with a new Cmdlet.

Changes:

Added New-AzExpressRoutePortLOA cmdlet. This cmdlet fetches a pdf document as base64 encoded string in the JSON response from Nfv-RP and saves the pdf on the local machine.
Minimum API Version Required

2020-06-01

Swagger Link

https://github.com/Azure/azure-rest-api-specs/blob/network-june-release/specification/network/resource-manager/Microsoft.Network/stable/2020-06-01/expressRoutePort.json

See the new added endpoint: generateLOA

Target Date:
Feature is already released from Powershell.

Need the parity with az-cli in the next suitable release.

**Comment by neelbhavsar97** [comment]
Below is the PR with the powershell changes for the same.
>> https://github.com/Azure/azure-powershell/pull/12465

**Comment by yonzhan** [comment]
Network
