### ISSUE TITLE
[Network] "az network network watcher configure" - NetworkWatcherCountLimitReached

### ISSUE THREAD

**Issue by HappyTobi** [Azure/azure-cli#15796]
## Describe the bug

**Command Name**
`az network watcher configure`

**Errors:**
```
code: NetworkWatcherCountLimitReached - , Cannot create more than 1 network watchers for this subscription in this region.
```

## To Reproduce:
- Deploy a network watcher to a specified region like "eastus"
`az network watcher configure --subscription {} --locations eastus --resource-group {} --enabled {} --debug`
- Verify that the command was succeed
- Rerun the same command but with an Uppercase-letter at the beginning of the `--locations` argument
`az network watcher configure --subscription {} --locations Eastus --resource-group {} --enabled {} --debug`

Now you will receive the the exception / error:
```
cli.azure.cli.core.azclierror : code: NetworkWatcherCountLimitReached - , Cannot create more than 1 network watchers for this subscription in this region.
code: NetworkWatcherCountLimitReached - , Cannot create more than 1 network watchers for this subscription in this region.
```

If you look into the debug log you see the the `PUT` command will generate a new Network Watcher name that it different than the other.

1.
```
 https://management.azure.com:443 "PUT /subscriptions/XXXXXXX/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_eastus?api-version=2020-06-01 HTTP/1.1" 200 None
```
2. 
```
https://management.azure.com:443 "PUT /subscriptions/XXXXXXX/resourceGroups/NetworkWatcherRG//providers/Microsoft.Network/networkWatchers/Eastus-watcher?api-version=2020-06-01 HTTP/1.1" 400 190
```

## Expected Behavior

No error should be thrown because it's an idempotent operation.
Location should be case-insensitive

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.6
Installer: HOMEBREW

azure-cli 2.14.0
```

also tested on
```
Ubuntu 18.04
Python 3.8.6

azure-cli 2.10.0
```

**Comment by yonzhan** [comment]
Network
