### ISSUE TITLE
Missing deployment slot support for az functionapp update

### ISSUE THREAD

**Issue by kevin-secrist** [Azure/azure-cli#15800]
###  Describe the bug

Hi there!

When attempting to update one of the properties on my function app, I found that `az functionapp update` does not have slot support. To attempt to work around this I tried using `az webapp` (which does have slot support) but it gave me an error telling me to use `az functionapp` instead.

Other commands that may/may not need slot support:

```
az functionapp config hostname get-external-ip
az functionapp deployment user set
az functionapp deployment user show
az functionapp devops-pipeline create
az functionapp function *
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```
az functionapp update --resource-group <rg> --name <app> --slot staging --set siteConfig.healthCheckPath=/api/HealthCheck
```

**Errors:**

```
az: error: unrecognized arguments: --slot staging
```

To reiterate, `az webapp update` _does_ have slot support.

A separate issue that I don't _need_ addressed is that passing in the resourceId of the slot gets ignored, e.g. 

```
az functionapp update --ids /subscriptions/{SubscriptionId}/resourceGroups/{ResourceGroup}/providers/Microsoft.Web/sites/{FunctionApp}/slots/staging --set siteConfig.healthCheckPath=/api/HealthCheck
```

Ends up silently updating the `production` slot instead of the `staging` slot. I imagine this is probably the behavior across all commands though. This is undesired behavior because it will cause an app restart on the production slot when an out-of-rotation slot should have been updated+restarted instead.

## Expected Behavior

Update the config on the slot as expected in the same way that it does on the `production` slot.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.11.0 *

Extensions:
front-door 1.0.9

```
## Additional Context

Thanks for your help!

**Comment by yonzhan** [comment]
functionapp

**Comment by apawast** [comment]
@gzuber could you please take a look at this?

**Comment by bhopkinson** [comment]
Hi,

I have just come across this problem. I too need to update the staging slot.

```
        az functionapp update `
            --name <name> `
            --resource-group <resource group> `
            --set dailyMemoryTimeQuota=<quota> `
            --slot staging
```

Omitting `--slot` correctly updates the production slot, but ideally we need a way to update the staging slot.

Are there any alternative ways until the support is added?

Thanks.

**Comment by hejingkan2005** [comment]
Hi team, 

I'm having the same issue that az functionapp update does not support updating httpsonly for slot. Any update on this? 

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.0.0                Az.Functions                        PSGallery            Microsoft Azure PowerShell - Azure Functions service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....

**Comment by mjazwiecki** [comment]
do we have any updates / ways to make this work? 
updating staging slot is something we would love to use in our environment.

**Comment by navba-MSFT** [comment]
@kevin-secrist Apologies for the late reply. The similar issue has been discussed here and I see the PR has been merged now https://github.com/Azure/azure-cli/pull/21698. Please let me know if you are still facing the same issue using [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the AzCLI. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@kevin-secrist Thanks for getting back. Just checked the details about the PR https://github.com/Azure/azure-cli/pull/21698 and got a confirmation that the fix is yet to be released. Sending you the next release milestone details: https://github.com/Azure/azure-cli/milestone/116 which is planned for April 6th. Hope this helps. In the meantime, if you have any questions on this, please let me know.

**Comment by kevin-secrist** [comment]
May be fixed by https://github.com/Azure/azure-cli/pull/22745, will retest upon the next release

**Comment by kevin-secrist** [comment]
Tried to reproduce again, created a new test app using instructions from above:

```bash
$ az --version
azure-cli                         2.38.0

core                              2.38.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/kevin/.azure/cliextensions'

Python (Linux) 3.10.5 (main, Jul  1 2022, 04:14:52) [GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

## Before Updating Config

```bash
$ az functionapp show --resource-group azclitest070622 --name azclitest070622 | jq .siteConfig.healthCheckPath
null
$ az functionapp show --resource-group azclitest070622 --name azclitest070622 --slot staging | jq .siteConfig.healthCheckPath
null
```

## Update Config

```bash
az functionapp update --resource-group azclitest070622 --name azclitest070622 --slot staging --set siteConfig.healthCheckPath=/api/HealthCheck
```

## After Update

```bash
$ az functionapp show --resource-group azclitest070622 --name azclitest070622 | jq .siteConfig.healthCheckPath
null
$ az functionapp show --resource-group azclitest070622 --name azclitest070622 --slot staging | jq .siteConfig.healthCheckPath
"/api/HealthCheck"
```

✔️ Looks like the staging slot took the setting instead of the production slot

Newest version (2.38.0) fixes the issue, fixed by https://github.com/Azure/azure-cli/pull/22745, thanks @haroonf
