### ISSUE TITLE
WebApp:Cannot list publishing profiles using resource IDs

### ISSUE THREAD

**Issue by elliotchaim** [Azure/azure-cli#15811]
## Describe the bug

Publishing profiles are not returned when using the `--ids` parameter to specify the web app. Instead, an empty array is returned. Using `--name` and `--resource-group` instead works correctly.

**Command Name**
`az webapp deployment list-publishing-profiles`

**Errors:**

## To Reproduce:

```
$ ResourceId="/subscriptions/***/resourceGroups/***/providers/Microsoft.Web/sites/***"
$ az webapp deployment list-publishing-profiles --ids $ResourceId 
[] # incorrect response
```

## Expected Behavior

Correct publish profile is returned

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.6
Installer: HOMEBREW

azure-cli 2.14.0

```

## Additional Context

First spotted this issue in our CI, which uses GitHub Actions with [ubuntu-latest](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md).  I have since recreated this issue locally on MacOS Catalina (10.15.7).

Did not occur on azure-cli 2.11.1. Environment summary is my local environment. Note the GH Action mentioned above uses azure-cli 2.13.0.

**Comment by yonzhan** [comment]
webapp

**Comment by btardif** [comment]
@Kotasudhakarreddy can you look into this once you get a chance?

**Comment by Kotasudhakarreddy** [comment]
@btardif - sure will take care of this.

**Comment by Kotasudhakarreddy** [comment]
please use the latest version of cli `2.34.1` to unblock from the issue.
