### ISSUE TITLE
What are the SKU options?

### ISSUE THREAD

**Issue by johnsen9000** [Azure/azure-cli#15813]
I am trying to google and looking at the options, but can't find the SKU options. Would it might be an idea to put the options in the creation description?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f43f74b5-856c-3b6a-1a75-f1c7e1dd1c81
* Version Independent ID: 63e76088-2537-b337-c130-20dcad6d772c
* Content: [az search service](https://docs.microsoft.com/en-us/cli/azure/search/service?view=azure-cli-latest#az_search_service_create)
* Content Source: [latest/docs-ref-autogen/search/service.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/search/service.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
search

**Comment by johnsen9000** [comment]
How about you write it in the documentations on the page instead of making me google like the other services on Microsoft? I found something through google, and used the single letter code, as you use on functions, but that did not work and I needed to use the whole name. Why you write the shorthand code is a mystery then because it is useless. 

Either way, if the documentation could have a hint of what the answer is, it would reduce time used on such stupid things.

**Comment by brjohnstmsft** [comment]
@johnsen9000 Apologies for the misunderstanding -- I believe @yonzhan was indicating which Azure service team should handle this issue (my team, Azure Cognitive Search).

I'll find the right person to update this documentation. In the meantime, try one of the Azure Cognitive Search SKUs listed in [the PowerShell reference](https://docs.microsoft.com/powershell/module/az.search/new-azsearchservice?view=azps-5.0.0). I'm assuming they'll be the same for Azure CLI, but I'll find the engineer who owns this to confirm. Sorry for the inconvenience.

**Comment by brjohnstmsft** [comment]
Assigned @timothyta12 to fix the issue with our documentation.

@johnsen9000 Please let us know if the SKUs listed in the PowerShell reference worked for you.
