### ISSUE TITLE
az network application-gateway root-cert create not working (TLS termination)

### ISSUE THREAD

**Issue by ptoluganti** [Azure/azure-cli#15810]
$gatewayCertCerPath = "D:\certificates\apim.cer"
$gatewayName = 'gw001'
$certName = 'apim_cert'
$resourceGroup = 'dmz-gw-rg'

az network application-gateway root-cert create --cert-file $gatewayCertCerPath --gateway-name $gatewayName --name $certName --resource-group $resourceGroup

This command fails after sometime. 

This behaviour is same even in portal. if i try to upload/change CA certificate http settings for port 443. application gateway fails to update.

az cli version 2.14
OS : windows 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35fc947b-5973-cded-3660-02b52370b02a
* Version Independent ID: 1bd4fcd3-788d-3df9-fd3a-3dd528d89846
* Content: [az network application-gateway root-cert](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/root-cert?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/application-gateway/root-cert.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/application-gateway/root-cert.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by haroldrandom** [comment]
Could you post the error message with sensitive info redacted?

**Comment by haroldrandom** [comment]
I cannot produce your scenario 
![image](https://user-images.githubusercontent.com/14357159/100062259-4725c200-2e6a-11eb-8c06-87486479bfd3.png)

**Comment by haroldrandom** [comment]
Closed as inactive
