### ISSUE TITLE
Generic Update Needs Better Documentation

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1582]
Feedback from numerous individuals indicate that people find generic update poorly documented and difficult to use. We need clear documentation (within the CLI or external) that shows how to use this feature, complete with common examples.

**Comment by cedwards-reisys** [comment]
Documentation still lacking.

**Comment by yugangw-msft** [comment]
@tjprescott, the document now is in https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md.
Shall we close it, or wait till we move it to Azure CLI Hub in docs.microsoft.com?

**Comment by tjprescott** [comment]
I would close it for now. Once the hub is up, we might migrate the material into its own article. https://github.com/MicrosoftDocs/azure-docs-cli/tree/master/docs-ref-conceptual seems like a logic place since it has articles on using query and such.
