### ISSUE TITLE
Azure CLI for Ubuntu Groovy Gorilla

### ISSUE THREAD

**Issue by pilif42** [Azure/azure-cli#15828]
At https://packages.microsoft.com/repos/azure-cli/dists/ , I cannot see a distribution for Ubuntu Groovy Gorilla. Is there a plan to create one? If yes, when can I expect it to be available?

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls share principal of supporting Ubuntu release? thanks

**Comment by heytjr** [comment]
+1 it would be great if the az cli team could validate Ubuntu releases as they come out as it seems to take a bit for this tooling to catch up..
BUT fyi as a work around I just take - https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt
and use AZ_REPO=focal in Step 3

**Comment by pilif42** [comment]
Thanks @heytjr for the tip. I can confirm it works on my Ubuntu Groovy Gorilla.

**Comment by fengzhou-msft** [comment]
The install script is updated to use the focal package for groovy before the groovy package is ready:
`curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`

**Comment by fengzhou-msft** [comment]
Groovy package is added in release pipeline.
