### ISSUE TITLE
Error accessing WAF certificates

### ISSUE THREAD

**Issue by Dicolla** [Azure/azure-cli#15822]
## Describe the bug

**Command Name**
`az network application-gateway auth-cert show`

**Errors:**
```
'NoneType' object is not iterable
Traceback (most recent call last):
Temp\pip-install-7cl6xofh\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 631, in execute
azure\cli\core\commands\__init__.py, ln 695, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 688, in _run_job
Local\Temp\pip-install-7cl6xofh\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 665, in _run_job
azure\cli\core\commands\__init__.py, ln 324, in __call__
azure\cli\core\commands\arm.py, ln 752, in handler
azure\cli\core\commands\arm.py, ln 764, in show_exception_handler
azure\cli\core\commands\arm.py, ln 750, in handler
azure\cli\command_modules\network\_util.py, ln 31, in get_func
TypeError: 'NoneType' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network application-gateway auth-cert show -g {} --gateway-name {} -n {}`

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1 *

Extensions:
log-analytics 0.1.4

```

**Comment by yonzhan** [comment]
add to S179

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14287

**Comment by haroldrandom** [comment]
Hi, @Dicolla. I guess your issue has been fixed since https://github.com/Azure/azure-cli/pull/14529. 
Your issue is duplicated with https://github.com/Azure/azure-cli/issues/14487.

Please have a shot to the Azure CLI with 2.10.0 or later.
