### ISSUE TITLE
WebApp:can't recognize "|" character correctly in “az webapp create” command in powershell

### ISSUE THREAD

**Issue by hanhsia** [Azure/azure-cli#15832]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

following command works well in cmd window but fails in powershell
az login
az configure --defaults group="<xxxxx>" location="<xxxxx>"
az webapp create --name "<xxxxx>" --plan "<xxxxxx>" -r "DOTNETCORE|3.1"
it reports following error
'3.1' is not recognized as an internal or external command,
operable program or batch file.
**To Reproduce**

run following command in powershell:
az login
az configure --defaults group="<xxxxx>" location="<xxxxx>"
az webapp create --name "<xxxxx>" --plan "<xxxxxx>" -r "DOTNETCORE|3.1"

**Expected behavior**

a webapp hosted .net core app should be created successfully.
**Environment summary**

 az --version

azure-cli                         2.14.1

core                              2.14.1
telemetry                          1.0.6

Extensions:
application-insights              0.1.11
azure-iot                         0.10.3
**Additional context**

it looks like a powershell issue but my suggestion is not using "|" character in the string.

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
hi @hanhsia could you pls does this https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md#workaround-the-stop-parsing-symbol work for you?

**Comment by Strepto** [comment]
You can solve this by "double escaping" in powershell. 

`--runtime '"node|12-lts"'`

Working example:
```
az webapp create  --name "$FrontendAppName" --resource-group "$ResourceGroup" --plan $Plan --runtime '"node|12-lts"'
```

**Comment by hanhsia** [comment]
yes, i use this way to workaround it. The doc is great.

**Comment by yungezz** [comment]
happy to see if works for you. :) is it ok to close the issue?

**Comment by hanhsia** [comment]
sure, please close it.
