### ISSUE TITLE
Typo in `az storage remove` command example

### ISSUE THREAD

**Issue by Zhaph** [Azure/azure-cli#15842]
https://github.com/Azure/azure-cli/blob/dc4b934d4399b8d10fbe9b0676e00e2ef1ddf534/src/azure-cli/azure/cli/command_modules/storage/_help.py#L662

Should read:

> You can also try "az storage remove" command

**Comment by yonzhan** [comment]
@Zhaph  thanks for your contribution. This issue can be closed after the PR is merged.

**Comment by savelinomediagroup** [comment]
As storage remove
