### ISSUE TITLE
'az container exec' does NOT run /bin/bash

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#15856]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I've created the Docker image and I can launch container from it using 'docker' tool:
docker build --compress --tag $image_id:$tag_id --file Dockerfile-$image_id .

I can successfully run /bin/bash inside a container:
'docker exec --interactive --tty PostgresProStandard12 bash'

I've put the image into ACR and I can launch container from it using 'az' tool:
az container create \
--resource-group dockers \
--name debiandocker \
--image $loginServer_id/$image_id:$tag_id \
--cpu 2 \
--memory 2 \
--registry-login-server $loginServer_id \
--registry-username pgprostdacr \
--registry-password $password_id \
--dns-name-label $image_id \
--ports 5433 \
--no-wait

I used to run /bin/bash inside a container some time ago
az container exec \
--resource-group dockers \
--name debiandocker \
--exec-command "/bin/bash" \
--container-name debiandocker

but I cannot do it now - when I run previous command, nothing happens - I simply stay in my OS CLI environment

I can verify the container is up & running by:

az container list \
--resource-group dockers

az container show \
--resource-group dockers \
--name debiandocker

az container logs \
--resource-group dockers \
--name debiandocker \
--container-name debiandocker

az container attach \
--resource-group dockers \
--name debiandocker \
--container-name debiandocker

It looks to me something has been broken with 'az' tool, since it all worked before and have not changed anything in my Dockerfile.

**To Reproduce**

Create container and try to run /bin/bash inside of it

**Expected behavior**

By running 

az container exec \
--resource-group dockers \
--name debiandocker \
--exec-command "/bin/bash" \
--container-name debiandocker

I expect, like before, to get inside of container

**Environment summary**

root@ubuntu16:~# az --version
azure-cli                         2.14.2

core                              2.14.2
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Nov  9 2020, 06:00:25)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Additional context**

It used to work without any issues, probably several months ago, but does not work any longer.
Since I have not changed anything with my Dockerfile and it still works with 'docker' tool, I suspect something wrong with 'az' tool.

**Comment by alexeyshishkin01** [comment]
some more info - I've tried to use container in the documentation
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-quickstart
it does not work as well:

az container create --resource-group dockers --name mycontainer --image mcr.microsoft.com/azuredocs/aci-helloworld --dns-name-label aci-demo2 --ports 80
az container list --resource-group dockers
az container exec --resource-group dockers --name mycontainer --exec-command "/bin/bash" --container-name mycontainer
az container delete --resource-group dockers --name mycontainer --yes
az container list --resource-group dockers

it's easily reproduced - so, hopefully you'll fix this bug soon

**Comment by yonzhan** [comment]
container

**Comment by alexeyshishkin01** [comment]
I've also tested my Docker image in GCP - no such issue exists

**Comment by alexeyshishkin01** [comment]
one more hint for your troubleshooting

when I create container in the AKS pod from the same Docker image mentioned above I can successfully get into container via:

kubectl exec --stdin --tty $POD_NAME -- /bin/bash

**Comment by juicyarts** [comment]
I'm experiencing the same behaviour on MacOS Catalina(10.15.5 (19F101))

```bash
➜  azure git:(master) ✗ az --version
azure-cli                         2.15.0 *

core                              2.15.0 *
telemetry                          1.0.6

Python location '/usr/local/Cellar/azure-cli/2.15.0/libexec/bin/python'
Extensions directory '/Users/[user]/.azure/cliextensions'

Python (Darwin) 3.8.6 (default, Oct 27 2020, 08:57:44)
[Clang 12.0.0 (clang-1200.0.32.21)]

Legal docs and information: aka.ms/AzureCliLegal

```

```bash
➜  azure git:(master) ✗ az container exec --resource-group [resource-group] --name [resource-name] --container-name [container-name] --exec-command "/bin/bash"
➜  azure git:(master) ✗
```

nothing happens even though it used to work some time ago (~august)  :/

**Comment by bitcloud** [comment]
The issue got introduced by the backend.

The problem lies here:
https://github.com/Azure/azure-cli/blob/879396f3c9ec4dd090b595eeabb36b8dde2007ec/src/azure-cli/azure/cli/command_modules/container/custom.py#L684

This function loops over the websocket output and if the socket emits an empty string it is considered end of session. But currently the backend seems to start with an empty string before emitting the real output.

by just commenting out this and the next line, it works again, but the eol detection is gone then. which is kind of okay, because if the terminal ends, the socket closes anyway from the server side.

**Comment by alexeyshishkin01** [comment]
ok, thanks for that, when the fix is going to be available in 'az' tool ?

**Comment by bitcloud** [comment]
I don't know as I don't work for MS ;-)
But if you need it right away, you can easily patch you local version.

On the mac the file is located `/usr/local/Cellar/azure-cli/2.14.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/container/custom.py`

check for the function `_cycle_exec_pipe` and just remove the two lines 4 and 5 in the function (`if not data: return False`)

This should get you working until they release a new version.

**Comment by alexeyshishkin01** [comment]
any news from vendor side ?

**Comment by benjaminSponagel** [comment]
please fix soon 🥇

**Comment by alexeyshishkin01** [comment]
hello, guys ?

any news regarding the issue ?

I tried to use simple possible container image:

'echo FROM mcr.microsoft.com/hello-world > Dockerfile'

and the issue is reproduced.

I also tried to use web-interface to run this container - https://portal.azure.com/#home - the container first starts, than terminates.

On the other hand, if I use ready container image 'mcr.microsoft.com/azuredocs/aci-helloworld', I can connect to its '/bin/sh' interface.

How is it possible ?

**Comment by alexeyshishkin01** [comment]
upon creating my container I see the following:

root@Alexey-HP:~# az container attach --resource-group dockers --name debiandocker --container-name debiandocker
Container 'debiandocker' is in state 'Waiting'...
(count: 1) (last timestamp: 2020-12-26 09:09:31+00:00) pulling image "pgprostdacr.azurecr.io/pgpro-std96-debian-x64:96.201.20201205"
(count: 1) (last timestamp: 2020-12-26 09:09:56+00:00) Successfully pulled image "pgprostdacr.azurecr.io/pgpro-std96-debian-x64:96.201.20201205"
(count: 1) (last timestamp: 2020-12-26 09:10:05+00:00) Started container
(count: 1) (last timestamp: 2020-12-26 09:10:08+00:00) Killing container with id 4e8b4a2b2da19ac571cf01ce8202d48ba44f121e2059379df1b2c7293a96c31d.

it's really strange to see my container is killed after being started

**Comment by alexeyshishkin01** [comment]
hello, all !

it still does not work for me

pls. see below:

root@Alexey-HP:~# az --version
azure-cli                         2.17.1

core                              2.17.1
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Dec 31 2020, 08:28:47)
[GCC 9.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy



root@Alexey-HP:~# az container create \
> --resource-group dockers \
> --name debiandocker \
> --image $loginServer_id/$image_id:$tag_id \
> --cpu 2 \
> --memory 2 \
> --registry-login-server $loginServer_id \
> --registry-username pgprostdacr \
> --registry-password $password_id \
> --dns-name-label $image_id \
> --ports 5433 \
> --no-wait

root@Alexey-HP:~# az container list \
> --resource-group dockers
Name          ResourceGroup    Status    Image                                                         IP:ports            Network    CPU/Memory       OsType    Location
------------  ---------------  --------  ------------------------------------------------------------  ------------------  ---------  ---------------  --------  -----------
debiandocker  dockers          Creating  pgprostdacr.azurecr.io/pgpro-std13-debian-x64:13.11.20201218  52.155.179.82:5433  Public     2.0 core/2.0 gb  Linux     northeurope

root@Alexey-HP:~# az container list --resource-group dockers
Name          ResourceGroup    Status    Image                                                         IP:ports            Network    CPU/Memory       OsType    Location
------------  ---------------  --------  ------------------------------------------------------------  ------------------  ---------  ---------------  --------  -----------
debiandocker  dockers          Creating  pgprostdacr.azurecr.io/pgpro-std13-debian-x64:13.11.20201218  52.155.179.82:5433  Public     2.0 core/2.0 gb  Linux     northeurope

root@Alexey-HP:~# az container list --resource-group dockers
Name          ResourceGroup    Status     Image                                                         IP:ports            Network    CPU/Memory       OsType    Location
------------  ---------------  ---------  ------------------------------------------------------------  ------------------  ---------  ---------------  --------  -----------
debiandocker  dockers          Succeeded  pgprostdacr.azurecr.io/pgpro-std13-debian-x64:13.11.20201218  52.155.179.82:5433  Public     2.0 core/2.0 gb  Linux     northeurope

root@Alexey-HP:~# az container show \
> --resource-group dockers \
> --name debiandocker
Name          ResourceGroup    Status    Image                                                         IP:ports            Network    CPU/Memory       OsType    Location
------------  ---------------  --------  ------------------------------------------------------------  ------------------  ---------  ---------------  --------  -----------
debiandocker  dockers          Running   pgprostdacr.azurecr.io/pgpro-std13-debian-x64:13.11.20201218  52.155.179.82:5433  Public     2.0 core/2.0 gb  Linux     northeurope

root@Alexey-HP:~# az container show --resource-group dockers --name debiandocker
Name          ResourceGroup    Status    Image                                                         IP:ports            Network    CPU/Memory       OsType    Location
------------  ---------------  --------  ------------------------------------------------------------  ------------------  ---------  ---------------  --------  -----------
debiandocker  dockers          Running   pgprostdacr.azurecr.io/pgpro-std13-debian-x64:13.11.20201218  52.155.179.82:5433  Public     2.0 core/2.0 gb  Linux     northeurope

root@Alexey-HP:~# az container logs \
> --resource-group dockers \
> --name debiandocker \
> --container-name debiandocker
None

root@Alexey-HP:~# az container attach \
> --resource-group dockers \
> --name debiandocker \
> --container-name debiandocker
Container 'debiandocker' is in state 'Waiting'...
(count: 5) (last timestamp: 2021-01-12 08:34:19+00:00) pulling image "pgprostdacr.azurecr.io/pgpro-std13-debian-x64:13.11.20201218"
(count: 5) (last timestamp: 2021-01-12 08:34:20+00:00) Successfully pulled image "pgprostdacr.azurecr.io/pgpro-std13-debian-x64:13.11.20201218"
(count: 1) (last timestamp: 2021-01-12 08:34:39+00:00) pulling image "pgprostdacr.azurecr.io/pgpro-std13-debian-x64:13.11.20201218"
(count: 1) (last timestamp: 2021-01-12 08:35:14+00:00) Successfully pulled image "pgprostdacr.azurecr.io/pgpro-std13-debian-x64:13.11.20201218"
(count: 1) (last timestamp: 2021-01-12 08:35:23+00:00) Started container
(count: 1) (last timestamp: 2021-01-12 08:35:24+00:00) Killing container with id 3ca042e2787fd18cd4f07c43303dad9fe382e6e8a7d4add6273145200f638cdc.
^C

root@Alexey-HP:~# az container exec \
> --resource-group dockers \
> --name debiandocker \
> --exec-command "/bin/bash" \
> --container-name debiandocker
root@Alexey-HP:~#
root@Alexey-HP:~#

**Comment by bitcloud** [comment]
@alexeyshishkin01 it has landed in the 2.18.0 version. (see https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#container) please try that one.

**Comment by alexeyshishkin01** [comment]
still does NOT work for me - it works before - what have you changed ?


root@Alexey-HP:~# image_id=pgpro-std13-debian-x64
root@Alexey-HP:~# echo $image_id
pgpro-std13-debian-x64
root@Alexey-HP:~#
root@Alexey-HP:~# tag_id=13.11.20201218
root@Alexey-HP:~# echo $tag_id
13.11.20201218
root@Alexey-HP:~# az container list \
> --resource-group dockers
root@Alexey-HP:~#
root@Alexey-HP:~# az container create \
> --resource-group dockers \
> --name debiandocker \
> --image $loginServer_id/$image_id:$tag_id \
> --cpu 2 \
> --memory 2 \
> --registry-login-server $loginServer_id \
> --registry-username pgprostdacr \
> --registry-password $password_id \
> --dns-name-label $image_id \
> --ports 5433 \
> --no-wait
root@Alexey-HP:~# az container list \
> --resource-group dockers
Name          ResourceGroup    Status     Image                                                         IP:ports             Network    CPU/Memory       OsType    Location
------------  ---------------  ---------  ------------------------------------------------------------  -------------------  ---------  ---------------  --------  -----------
debiandocker  dockers          Succeeded  pgprostdacr.azurecr.io/pgpro-std13-debian-x64:13.11.20201218  52.155.163.246:5433  Public     2.0 core/2.0 gb  Linux     northeurope
root@Alexey-HP:~# az container show \
> --resource-group dockers \
> --name debiandocker
Name          ResourceGroup    Status    Image                                                         IP:ports             Network    CPU/Memory       OsType    Location
------------  ---------------  --------  ------------------------------------------------------------  -------------------  ---------  ---------------  --------  -----------
debiandocker  dockers          Running   pgprostdacr.azurecr.io/pgpro-std13-debian-x64:13.11.20201218  52.155.163.246:5433  Public     2.0 core/2.0 gb  Linux     northeurope
root@Alexey-HP:~# az container logs \
> --resource-group dockers \
> --name debiandocker \
> --container-name debiandocker
None
root@Alexey-HP:~# az container attach \
> --resource-group dockers \
> --name debiandocker \
> --container-name debiandocker
Container 'debiandocker' is in state 'Waiting'...
(count: 1) (last timestamp: 2021-01-20 07:25:56+00:00) pulling image "pgprostdacr.azurecr.io/pgpro-std13-debian-x64:13.11.20201218"
(count: 1) (last timestamp: 2021-01-20 07:26:23+00:00) Successfully pulled image "pgprostdacr.azurecr.io/pgpro-std13-debian-x64:13.11.20201218"
(count: 1) (last timestamp: 2021-01-20 07:26:34+00:00) Started container
^Croot@Alexey-HP:~# az container exec \
> --resource-group dockers \
> --name debiandocker \
> --exec-command "/bin/bash" \
> --container-name debiandocker
root@Alexey-HP:~#
root@Alexey-HP:~# az --version
azure-cli                         2.18.0

core                              2.18.0
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Jan 15 2021, 09:54:30)
[GCC 9.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
root@Alexey-HP:~#

**Comment by bitcloud** [comment]
I just hat also a look at it and it doesn't work for me as well, but now it is also not working on the portal. So there seems to be another issue now...

**Comment by alexeyshishkin01** [comment]
it worked 100%, at least in summer 2020

**Comment by bitcloud** [comment]
I just tested it again and it it works here on my machine:
```
> az container create --resource-group testing --name debiandocker --image debian:jessie --cpu 2 --memory 2 --command-line 'bash -c "sleep 30000"'
## wait until the container started
> az container exec --resource-group testing --name debiandocker --exec-command "/bin/bash" --container-name debiandocker
root@wk-caas-22b5128d43814c5aad05834f1fc7382f-8485266ad827c62f5b926d:/#
```

It seems to have some issues with refreshing the output, but I can interact with the shell. So it seems that it works for me now.

**Comment by alexeyshishkin01** [comment]
I use the same terminals, I've tested on two different terminals - WSL and Putty - will try to test again
but it works on the same terminals if I use 'docker ...' or run container in K8S

**Comment by alexeyshishkin01** [comment]
now I've got the following issue - it did not happen before:

compare the output of connecting to container via 'bash' in case of 'docker' and 'az'
they used to be the same, but now 'az' out put is wrong - it should connect to 'postgres' user instead of 'root' user

1) 'docker' output

root@ubuntu20:~# image_id=pgpro-std10-debian-x64
root@ubuntu20:~# echo $image_id
pgpro-std10-debian-x64
root@ubuntu20:~#
root@ubuntu20:~# tag_id=10.151.20210122
root@ubuntu20:~# echo $tag_id
10.151.20210122
root@ubuntu20:~# docker run --rm --detach --publish 5533:5433 --name $image_id $image_id:$tag_id
a3b2f79098b2234b85dbf4431fc2e54d576b24a2aca47a4c84087b0805d78ac7
root@ubuntu20:~# docker exec --interactive --tty $image_id bash
#
# Welcome to Postgres Pro Standard Database 10 (docker)
#
# Product documentation is available at https://postgrespro.com/products/postgrespro/azure/standard
#
# Use the following command to set up Postgres Pro Database 'postgres' user password:
#
# psql -c "alter user postgres with encrypted password 'YOUR_POSTGRES_USER_PASSWORD'"
#
[postgres@ ~]$



2) 'az' output

root@ubuntu20:~# az container create \
> --resource-group dockers \
> --name debiandocker \
> --image $loginServer_id/$image_id:$tag_id \
> --cpu 1 \
> --memory 1 \
> --registry-login-server $loginServer_id \
> --registry-username pgprostdacr \
> --registry-password $password_id \
> --dns-name-label $image_id \
> --ports 5433 \
> --no-wait
root@ubuntu20:~# az container exec \
> --resource-group dockers \
> --name debiandocker \
> --exec-command "/bin/bash" \
> --container-name debiandocker
root@SandboxHost-637469396088046907:/#

one more thing is that terminal connected to container started via 'az' freezes after some time and the only way to unfreeze it is to delete the container

**Comment by alexeyshishkin01** [comment]
I have also tested the image with K8S - it works fine as well as Docker:

root@Alexey-HP:~# kubectl get pods
NAME                                                READY   STATUS    RESTARTS   AGE
pgpro-std10-debian-x64-deployment-c86bcb8dc-fnk65   1/1     Running   0          26s
root@Alexey-HP:~# kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.0.0.1     <none>        443/TCP   10m
root@Alexey-HP:~# kubectl get deployments
NAME                                READY   UP-TO-DATE   AVAILABLE   AGE
pgpro-std10-debian-x64-deployment   1/1     1            1           36s
root@Alexey-HP:~# kubectl get replicasets
NAME                                          DESIRED   CURRENT   READY   AGE
pgpro-std10-debian-x64-deployment-c86bcb8dc   1         1         1       39s
root@Alexey-HP:~# kubectl expose deployment $image_id-deployment --type=LoadBalancer --port 5433 --target-port 5433
service/pgpro-std10-debian-x64-deployment exposed
root@Alexey-HP:~# kubectl get services
NAME                                TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
kubernetes                          ClusterIP      10.0.0.1       <none>        443/TCP          10m
pgpro-std10-debian-x64-deployment   LoadBalancer   10.0.195.231   <pending>     5433:31662/TCP   3s
root@Alexey-HP:~# kubectl get service $image_id-deployment --watch
NAME                                TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)          AGE
pgpro-std10-debian-x64-deployment   LoadBalancer   10.0.195.231   20.54.90.163   5433:31662/TCP   7s
^Croot@Alexey-HP:~# EXTERNAL_IP=$(kubectl get services $image_id-deployment --no-headers | awk '{print $4}')
root@Alexey-HP:~# echo $EXTERNAL_IP
20.54.90.163
root@Alexey-HP:~# POD_NAME=$(kubectl get pods --no-headers | grep $image_id | awk '{print $1}')
root@Alexey-HP:~# echo $POD_NAME
pgpro-std10-debian-x64-deployment-c86bcb8dc-fnk65
root@Alexey-HP:~# kubectl exec --stdin --tty $POD_NAME -- /bin/bash
#
# Welcome to Postgres Pro Standard Database 10 (docker)
#
# Product documentation is available at https://postgrespro.com/products/postgrespro/azure/standard
#
# Use the following command to set up Postgres Pro Database 'postgres' user password:
#
# psql -c "alter user postgres with encrypted password 'YOUR_POSTGRES_USER_PASSWORD'"
#
[postgres@ ~]$
[postgres@ ~]$ id
uid=999(postgres) gid=1000(postgres) groups=1000(postgres)
[postgres@ ~]$

so, you see logging to container brings you to 'postgres' user env

for 'az container exec' it somehow switches you to 'root' env - that's not correct

could you pls. fix it ?

**Comment by alexeyshishkin01** [comment]
it looks like the issue can be with terminals - it works in Putty and does NOT work in WSL - both have Ubuntu 20.04

**Comment by alexeyshishkin01** [comment]
oh, no - the issue is unpredictable - sometime it works in either terminal, sometime it does not

but one thing is for sure - it ALWAYS works in Docker and in K8S - so 'az container ...' looks like a buggy stuff

**Comment by bitcloud** [comment]
I just tested what you said with the `memcachd` container from docker hub as I don't have access to your container and it works for me.
```bash
# az container create --resource-group testing --name debiandocker --image memcached --cpu 2 --memory 2

# az container exec --resource-group testing --name debiandocker --exec-command "/bin/bash"
memcache@wk-caas-a495427f09b4405faae750ab2a320c97-cef15a559878e1d13af51e:/$ exit

# az container delete --resource-group testing --name debiandocker
```

created the container twice and connected to each twice. Always the same result. This is certainly not a cli issue as it only forwards the terminal from the azure container service. So I guess it is either an issue in the azure container service or an issue with the container itself. But that is certainly out of scope for the issue here.

**Comment by alexeyshishkin01** [comment]
ok, let me check with other types/versions of containers
it worked really great till summer 2020 - no issues at all

**Comment by sunileman** [comment]
Why is this issue closed? Like others said in this post, this worked very well before.  Nothing in our containers changed.  Something on the CLI or service changed. 

And the example provided by @bitcloud ..well that doesn't work either

`sunilmanjee:~ » az container exec --resource-group efmassets --name debiandocker --exec-command "/bin/bash"
The command failed with an unexpected error. Here is the traceback:
write() argument must be str, not bytes
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/command_modules/container/custom.py", line 623, in container_exec
    _start_exec_pipe(execContainerResponse.web_socket_uri, execContainerResponse.password)
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/command_modules/container/custom.py", line 666, in _start_exec_pipe
    if not _cycle_exec_pipe(ws):
  File "/usr/local/Cellar/azure-cli/2.24.2/libexec/lib/python3.8/site-packages/azure/cli/command_modules/container/custom.py", line 684, in _cycle_exec_pipe
    sys.stdout.write(data)
TypeError: write() argument must be str, not bytes
To open an issue, please run: 'az feedback'`

Azure CLI seems to be lacking maturity.

**Comment by alexeyshishkin01** [comment]
+1

https://github.com/Azure/azure-cli/issues/18251

**Comment by bitcloud** [comment]
This seems to be a new or at least another issue. The new PR should address that issue as well.

**Comment by alexeyshishkin01** [comment]
many thanks !

**Comment by yonzhan** [comment]
@bitcloud for awareness

**Comment by jhwj9617** [comment]
@bitcloud 
I think I also had this issue. From a windows machine, I get
```
websocket: error from callback <function _on_ws_msg at 0x044F4618>: cannot use a string pattern on a bytes-like object
File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ampcm833\websocket\_app.py", line 345, in _callback
File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-o9w9ubks\azure\cli\command_modules\container\custom.py", line 643, in _on_ws_msg
File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-tdu1i9ff\colorama\ansitowin32.py", line 41, in write
File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-tdu1i9ff\colorama\ansitowin32.py", line 162, in write
File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-tdu1i9ff\colorama\ansitowin32.py", line 184, in write_and_convert
File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-tdu1i9ff\colorama\ansitowin32.py", line 246, in convert_osc
```
I am on az version 2.18.0. Will I have to upgrade to see this fix?

**Comment by dil-rmishra** [comment]
I was struggling with this issue.  Since my docker did not had bash installed as I was using a alpine image I tried `sh`i nstead. Then realized that the command is running fine in my windows command prompt or power shell. Only in gitbash it is not working.
`az container exec --resource-group <resource_group_name> --name <container_group_name> --exec-command "/bin/sh"`
