### ISSUE TITLE
az vmss extension set FAILURE

### ISSUE THREAD

**Issue by JDface** [Azure/azure-cli#15851]
## Describe the bug

**Command Name**
`az vmss extension set`

**Errors:**
```
'Response' object has no attribute 'status'
Traceback (most recent call last):
azure/cli/core/adal_authentication.py, ln 103, in set_token
    super(MSIAuthenticationWrapper, self).set_token()
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
...

azure/cli/core/adal_authentication.py, ln 114, in set_token
    .format(err.response.status, err.response.reason))
AttributeError: 'Response' object has no attribute 'status'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss extension set --resource-group {} --vmss-name {} --publisher {} --version {} --name {} --settings {}`

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *

Extensions:
ai-examples 0.2.4

```

**Comment by yungezz** [comment]
hi @qwordy the error is from adal auth, while could you pls help to double check e2e scenario? thanks.

**Comment by qwordy** [comment]
@JDface Does it still happen?

**Comment by yungezz** [comment]
hi @JDface are you still seeing the error? @qwordy fixed several NoneType errors.

**Comment by qwordy** [comment]
@yungezz Not clear
