### ISSUE TITLE
Subroutine functionapp function keys missing correct documentation

### ISSUE THREAD

**Issue by nimbusparis** [Azure/azure-cli#15857]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a function using Azure CLI. As I know, the subroutine is `az functionapp function keys set` but the documentation (inline or web) lack details how to proceed. 
When I try to type  `az functionapp function keys set --function-name CronTrigger1 --key-name TimerTrigger1 --name myFuncApp -g myResourceGroup` I got an error:
`code: NotFound - , Error creating or updating function key.` 
But the documentation doesn't tell anything about the parameter code.

**Describe the solution you'd like**
A clear documentation and error message. It is **impossible** to use Azure CLI to add function to a function app.

**Describe alternatives you've considered**
Default code could be set, as the portal do

**Comment by yonzhan** [comment]
functionapp

**Comment by apawast** [comment]
@gzuber could please take a look at this?

**Comment by hedglenrm** [comment]
Any status on this issue?

**Comment by panchagnula** [comment]
@nimbusparis for creating functions using CLI - the functions team supports funccli https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cmacos%2Ccsharp%2Cportal%2Cbash

the message you see here is 404 : NotFound since there is no existing functions for this to run.
