### ISSUE TITLE
Postgres server create fails using azure cli

### ISSUE THREAD

**Issue by wdesplas** [Azure/azure-cli#15855]
**Describe the bug**
Fails : 
```
az account set -s ${SUBSCRIPTION}
az postgres server create --location westeurope --resource-group auto-broker --name absdb \
--admin-user absadmin --admin-password LfbSm6nGAX2t     --sku-name B_Gen5_1 --ssl-enforcement Enabled \
--minimal-tls-version TLS1_0 --public-network-access Disabled     --backup-retention 20 --geo-redundant-backup Enabled \
--storage-size 51200 --version 11
```

ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/e9f981ec-1386-4419-89e4-67a9994ba6ea/resourceGroups/auto-broker/providers/Microsoft.DBForPostgreSQL/servers/absdb?api-version=2017-12-01 (Caused by ResponseError('too many 502 error responses',))

**To Reproduce**
```
az account set -s ${SUBSCRIPTION}
az postgres server create --location westeurope --resource-group auto-broker --name absdb \
--admin-user absadmin --admin-password LfbSm6nGAX2t     --sku-name B_Gen5_1 --ssl-enforcement Enabled \
--minimal-tls-version TLS1_0 --public-network-access Disabled     --backup-retention 20 --geo-redundant-backup Enabled \
--storage-size 51200 --version 11
```

**Expected behavior**
A postgres database must be created

**Environment summary**
Azure bash with the following cli : 
```
willy@Azure:~/repos/ingress-aks$ az version
{
  "azure-cli": "2.14.0",
  "azure-cli-core": "2.14.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.4"
  }
}
```

**Additional context**

**Comment by yonzhan** [comment]
postgres

**Comment by wdesplas** [comment]
Hi, 
Any news abiut this issues? In fact, istill reproducible currently.

Regards,

**Comment by DaeunYim** [comment]
Hi @wdesplas
We are very sorry for late reply. 
Postgres server doesn't support geo redundancy for basic tier . Please use General Purpose or Burstable tier to enable geo redundancy. 
We will work on improving guidance in CLI when features are not supported. We are very sorry for your inconvenience.
