### ISSUE TITLE
Capture VM

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-cli#15869]
**Resource Provider**
COMPUTE

**Description of Feature or Work Requested**
Customers can capture a VM to a shared image gallery

**Minimum API Version Required**

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/preview/2020-09-30/gallery.json
1.	In SIG, it would automate a PUT Gallery, PUT GalleryImage and then PUT GalleryImageVersion

**Target Date**
Early Co

**Comment by yungezz** [comment]
put in backlog firstly for Cobalt

**Comment by qwordy** [comment]
@puicchan I want confirm that this issue introduces no new REST API and a new CLI command like `az sig capture` will be added. It simplifies steps to capture a VM into an image version.

**Comment by qwordy** [comment]
This feature is canceled according to Yemi.
