### ISSUE TITLE
Import VHD

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-cli#15868]
**Resource Provider**
COMPUTE

**Description of Feature or Work Requested**
Customers can now create a Shared Image Gallery version from a VHD source in a storage account

**Minimum API Version Required**

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/preview/2020-09-30/gallery.json

Also refer to https://dev.azure.com/azure-mgmt-ex/Compute/_workitems/edit/4672

**Target Date**
Code has rolled out to Canary and we expect completion by end of November

**Comment by yungezz** [comment]
put in S179 tentatively.

**Comment by qwordy** [comment]
@puicchan @zunli hu Can you share how to prepare a VHD?

**Comment by Juliehzl** [comment]
To use storage account uri, you need to upload vhd file to storage account with `az storage blob upload` and then you could get the url with `az storage blob url`.

**Comment by qwordy** [comment]
@puicchan 
I got an error
```
(BadRequest) Could not find member 'uri' on object of type 'GalleryArtifactVersionSource'. Path 'properties.storageProfile.source.uri', line 1, position 388
```
Is it required to add subscription to allowed list?
