### ISSUE TITLE
WebApp: Can't set 64bit using "az webapp" cmd

### ISSUE THREAD

**Issue by hanhsia** [Azure/azure-cli#15879]
I didn't find any doc about how to set platform "64bit" using cli. The only way is to change it in azure portal. But i want to autmate it using az command. By default, it sets to 32bit platform in configuration. But my .net core app is compiled to win-64. if i deploy this .net core app, web app service will report error.
So is there any way to set it using az command?

**Comment by yungezz** [comment]
route to appropriate team to help look at it.

**Comment by gpictonmg** [comment]
I am wondering how to do this as well.

**Comment by gpictonmg** [comment]
This is working for me:
az webapp config set --name $WEBAPP_NAME --resource-group $RESOURCEGROUP_NAME --use-32bit-worker-process false

**Comment by hanhsia** [comment]
that's it. thanks.
