### ISSUE TITLE
Azure failed Login when connect to AML workspace in Linux VM

### ISSUE THREAD

**Issue by irishun** [Azure/azure-cli#15877]
**Describe the bug**
Hi MSFT Team,
we have faced an issue when using Linux VM to run python code and cannot login successfully with interactive Authentication. 
The error message is as follow:

![image](https://user-images.githubusercontent.com/47106812/98835856-3d9b6380-2441-11eb-8b26-460aaf348730.png)

**To Reproduce**
The process is:
Use Macbook to connect to Linux VM -> run python code to connect AML workspace -> interactive authentication

**Expected behavior**
successful interactive authentication

**Environment summary**
Linux VM created from Azure

**Additional context**
This issue might be related to the previous issue:
https://github.com/Azure/azure-cli/issues/11567

**Comment by yungezz** [comment]
hi @irishun did you meet the issue when running `az login`? Little confusing about `connect to AML workspace` , thanks.

**Comment by irishun** [comment]
Hi @yungezz, thank you for your reply.
az login was also not successful.

connect to AML workspace be running the following code will trigger interactive authentication as described in the following link:
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-setup-authentication

**Comment by singankit** [comment]
@irishun  Can you please share the output you get when you run **az login** ?

**Comment by sauryadas** [comment]
@irishun Will it be possible to file a support ticket with details so we can look at the logs?

**Comment by v-strudm-msft** [comment]
Since there hasn't been a response to our last comment, we are closing this issue. Should there still be a question, please open a new issue. Thank you.
