### ISSUE TITLE
get action groups on list

### ISSUE THREAD

**Issue by Mexicoder** [Azure/azure-cli#15889]
Is there any way to get the linked action groups in this list command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c78b494-edd2-74b4-fce6-1573cb9c242a
* Version Independent ID: 49b15a27-f990-bb88-eca8-d3f615210012
* Content: [az monitor activity-log alert](https://docs.microsoft.com/en-us/cli/azure/monitor/activity-log/alert?view=azure-cli-latest#az_monitor_activity_log_alert_list)
* Content Source: [latest/docs-ref-autogen/monitor/activity-log/alert.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/monitor/activity-log/alert.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
Could you try this command?

```
az monitor activity-log alert list --query [*].actions.actionGroups
```
