### ISSUE TITLE
Statement completion for values is inconsistent, slow, and unpredictable

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#1588]
Statement completion of parameter values can be helpful when it works, but it is really slow and works for some parameter values and not others, making it impossible to predict when to use it and when not to.  As a result, users end up waiting several seconds to get parameter values that may never be shown.

If we're going to do this, we need to make sure the behavior is intuitable and consistent.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
