### ISSUE TITLE
Can not update firewall rules via CLI

### ISSUE THREAD

**Issue by csullivannet** [Azure/azure-cli#15890]
## Describe the bug

**Command Name**
`az postgres server update`

**Errors:**
```
BadRequestError: Invalid Public Network Access Value
```

## To Reproduce:
- `az postgres server update --resource-group my-rg --name my-psql --public 10.20.30.40`

## Expected Behavior

The documentation from `az postgres server update --help` clearly states that a `<SingleIP>` is valid, however the command does not accept it:

```
    --public --public-network-access : Enable or disable public network access to server. When
                                       disabled, only connections made through Private Links can
                                       reach this server. Allowed values are : Enabled, Disabled,
                                       all, 0.0.0.0, <SingleIP>, <StartIP-DestinationIP>. Default is
                                       Enabled.
```

It is expected that running the command would add a new firewall rule, such as below when using the portal:

![Screenshot_2020-11-12_11-14-14](https://user-images.githubusercontent.com/11093135/98965619-40956300-24d8-11eb-9e2b-403299843eff.png)

## Environment Summary
```
Linux-5.4.75-1-MANJARO-x86_64-with-glibc2.2.5
Python 3.8.6
Installer: 

azure-cli 2.14.2

```
## Additional Context

The expected behaviour is contradicted by the [official azure-cli documentation](https://docs.microsoft.com/en-us/cli/azure/postgres/server?view=azure-cli-latest#az_postgres_server_update-optional-parameters), which does not say that `<SingleIP>` is an accepted value, although there are two extraneous commas that suggest perhaps these values are intended to be there, but missing:
> `--public --public-network-access`
> Enable or disable public network access to server. When disabled, only connections made through Private Links can reach this server. Allowed values are : Enabled, Disabled, all, 0.0.0.0, , . Default is Enabled.

**Comment by yonzhan** [comment]
postgres

**Comment by sr-msft** [comment]
Hello, Thanks for pointing that issue. We will look into updating it. For creating/updating firewall rules, please refer to https://docs.microsoft.com/azure/postgresql/howto-manage-firewall-using-cli.

**Comment by nachoalonsoportillo** [comment]
This confussion was created by PR #15538, which overloaded the `--public-network-access ` parameter to also create firewall rules under the covers, but it was only implemented for the create subcommand.

Unfortunately, help text for that parameter is common for create and update subcommands, hence the confussion.

To create or delete firewall rules for existing servers, don't use the update subcommand of the server command, but use the firewall-rule create/delete/update subcommands instead.

@yonzhan Please, close this issue.
