### ISSUE TITLE
No way to get CIFS URI for storage shares

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#1589]
Mounting a storage share is a core scenario for using shares via the CLI, yet there is no way that I can see to retrieve the CIFS url for a given share, which is required to mount it.  I think is important not only for convenience, but to ensure that the share URI is retrieved in a reliable fashion that will work in all Azure clouds.

**Comment by tjprescott** [comment]
We had a prototype "mount" command for file shares, but it was never merged due to security concerns and the fact that OSX didn't support SMB 3.0.

**Comment by binderjoe** [comment]
Thx @tjprescott.  I don't actually want the CLI to mount the share.  I just need the URI needed so I can mount it via standard *nix commands.

**Comment by tjprescott** [comment]
I'll dig into that branch and see about exposing just that. The security implication was around the mounting process itself, so simply providing the URI shouldn't be  a problem!

**Comment by troydai** [comment]
Reassign to Willie. I do think it is a valid feature.
