### ISSUE TITLE
WebApp:"az webapp log deployment list" returns [].

### ISSUE THREAD

**Issue by ShugoYoko** [Azure/azure-cli#15900]
[Enter feedback here]
I run the "az webapp log deployment list --name <Web App name> --resource-group <MyResourceGroup>" command in Azure Cloud shell. And the value [] was output. When I add the "--debug  flag" , implement it , and response contains a value. I'd like to confirm it. I want to make sure this works correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dfa0326-ea7b-e586-09eb-e4be66189e41
* Version Independent ID: 9057db94-f0a3-9534-0bdb-a1ff2d20fa93
* Content: [az webapp log deployment](https://docs.microsoft.com/en-us/cli/azure/webapp/log/deployment?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/log/deployment.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/log/deployment.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by calvinsID** [comment]
Hi @ShugoYoko, do you mind sharing the details of the output using `--debug` flag?

**Comment by calvinsID** [comment]
Unable to repro, @ShugoYoko please share details using `--debug` flag and tag me to re open investigation
