### ISSUE TITLE
Exporting Template

### ISSUE THREAD

**Issue by yene** [Azure/azure-cli#15908]
**Describe the solution you'd like**
Possibility to get the JSON Template for a resource, the same JSON you can get in the portal under "Export template"

**Additional context Example**
Create a VM. Open the VM resource in Azure Portal. In the UI navigate to automation Template > Export Template.
I would like to access that JSON from azcli

<img width="1373" alt="shot 2020-11-13 at 14 15 16" src="https://user-images.githubusercontent.com/63942/99076019-c12c9000-25ba-11eb-9c71-9baa24f4a8a7.png">

**Comment by yonzhan** [comment]
@yene Was this a portal issue or CLI issue?
