### ISSUE TITLE
No way to list all directories

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#1590]
There appears to be no way to list all directories for storage.  It's possible to list files, accounts, and shares but not directories.

**Comment by tjprescott** [comment]
`storage file list - List files and directories in the specified share.`

This is what Xplat does and is more akin to what you would get with `ls/dir`. In the SDK the actual method is `list_directories_and_files`.

**Comment by binderjoe** [comment]
Yeah, but the ls command doesn't imply it is specific to files--it "lists directory contents".  Where as a command called "list" under a group called "files" by definition implies it will list files.  Similarly, commands like ls make it easy to get just directories via -d or grepping the output.

I think there is a larger consistency issue:
- All other list commands in the CLI enumerate all resources of the parent command group type.  For example, vm list only enumerates vms; it doesn't enumerate scale sets.  
- A common pattern in the CLI is to create an item, then subsequently retrieve it via the show/list command.  It's weird to use a command from one part of the CLI to create something then grovel through the commands elsewhere in the CLI to retrieve it.

If nothing else, I'd consider adding a parameter to files list that only returns directories and adding help to the directory commands to tell users to use the file commands to get directory info.

**Comment by tjprescott** [comment]
I think the command was original called `az storage share contents` to more accurately convey what it does, but Storage didn't like that it wasn't named the same as Xplat and it got changed.

You can grep directories or file with:
`az storage file list -s {share} -otable | grep dir/file`

**Comment by tjprescott** [comment]
A few options:
1. go back to `az storage share contents`
2. make `file list` show only files and create a `directory list` command that shows only directories

Or, technically, I guess you could have all three. Thoughts?

**Comment by binderjoe** [comment]
My $0.02 is that option 2 would be the most intuitable behavior.  Thanks Travis.
