### ISSUE TITLE
`az servicebus namespace delete` may return 404 in some cases when the resource exists and is deleted during the operation

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-cli#15906]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

In our live test pipeline, we are seeing failures with `az servicebus namespace delete` caused by resource not found during the delete long running operation. The resource **does** exist (otherwise an error will be returned by service directly, the polling of long running operation result will not happen) and is deleted after the operation. 
Some failure examples in [test_sb_network](https://clitestresultstac.blob.core.windows.net/20200926-214150-475111/servicebus.report.parallel.html), [test_sb_alias](https://clitestresultstac.blob.core.windows.net/20201106-033418-010544/servicebus.report.parallel.html).

I cannot reproduce the issue easily by simply creating and then deleting a namespace. So it may only happen in some cases.

**To Reproduce**

`azdev test test_sb_alias --live`, the deletion of the primary namespace often succeeds while the deletion of the secondary namespace often fails.

**Expected behavior**

`az servicebus namespace delete` should delete the namespace with a 200 status code.

**Environment summary**

**Additional context**

**Comment by yungezz** [comment]
route to appriopriate team

**Comment by Saglodha** [comment]
@fengzhou-msft , Looks like the fix had been done for core CLI. Please feel free to reach out if you have additional concerns from service bus side.
