### ISSUE TITLE
Permissions are the wrong case

### ISSUE THREAD

**Issue by robs** [Azure/azure-cli#15907]
Hiya,

When I tried this with all lowercase permissions (get list) it didn't seem to work.
I updated through the portal and noticed that the casing changed to Get List.
Adding another policy I used Get and List and that worked fine so I guess the docs might need changing to reflect that.

`az keyvault set-policy --name
                       [--certificate-permissions {backup, create, delete, deleteissuers, get, getissuers, import, list, listissuers, managecontacts, manageissuers, purge, recover, restore, setissuers, update}]
                       [--key-permissions {backup, create, decrypt, delete, encrypt, get, import, list, purge, recover, restore, sign, unwrapKey, update, verify, wrapKey}]
                       [--no-wait]
                       [--object-id]
                       [--resource-group]
                       [--secret-permissions {backup, delete, get, list, purge, recover, restore, set}]
                       [--spn]
                       [--storage-permissions {backup, delete, deletesas, get, getsas, list, listsas, purge, recover, regeneratekey, restore, set, setsas, update}]
                       [--subscription]
                       [--upn]`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226e5769-f6c8-a480-db78-727fb96348ec
* Version Independent ID: 8ee06a2a-6eda-11be-3c8e-6ad948be207e
* Content: [az keyvault](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az_keyvault_set_policy)
* Content Source: [latest/docs-ref-autogen/keyvault.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/keyvault.yml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @bim-msft could you pls help to have a look?

**Comment by yungezz** [comment]
hi @robs which CLI version you're using? With latest 2.19.1, the lowercase permissions works fine, I cannot repo the issue
```
catherine@Azure:~$ az keyvault set-policy -n testmyvault21 --key-permissions get list import --object-id xxxxxxxxxxxxxxxxxxxxxxxxxxxx
{- Finished ..
  "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/yungez-test1/providers/Microsoft.KeyVault/vaults/testmyvault21",
  "location": "eastus",
  "name": "testmyvault21",
  "properties": {
    "accessPolicies": [
.....
```

**Comment by robs** [comment]
Hiya,

Hmm, I was on 2.11.1 so I guess that may have been it.
I rather stupidly upgraded before checking to see if I could repro it.

Can you see Get, List and Import as selected in the portal UI for that access policy?

**Comment by yungezz** [comment]
yes. Portal can show the access policy based on their convention.

**Comment by robs** [comment]
Thanks for looking, sorry I didn't check which version of the CLI tools I had.
I guess it's either fixed now or was something else, no idea what though.
I don't think I'll be changing our deployments to all lowercase though, just in case :)
