### ISSUE TITLE
webapp: az command-line: Error 500 "too many 500 error responses" while swapping slots

### ISSUE THREAD

**Issue by ensa-DMS** [Azure/azure-cli#15909]
**Describe the bug**
While deploying to azure using "az" command line, we obtain the following error: 

ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxxx/resourceGroups/...../slots/staging/slotsswap?api-version=2019-08-01 (Caused by ResponseError('too many 500 error responses',))

**To Reproduce**
This is our command:

az webapp deployment slot swap --action swap --resource-group 'resourceGroup' --name 'appService' --slot staging --target-slot production

**Expected behavior**
The slots are swapped correctly.

**Environment summary**
az version 2.14.2 under indows.

**Additional context**
I see other issues with the same error, "too many 500 error responses" but with different command lines. It might have to do with them, but I am not sure.

**Comment by yonzhan** [comment]
webapp

**Comment by Kotasudhakarreddy** [comment]
@ensa-DMS - I tried in `az version 2.15.0 *` but unable to repro the issue. slots were swapped successfully. Try update your `az` pack and run the command. still if you face any issue please share the `debug` log for your execution.

**Comment by btardif** [comment]
@Kotasudhakarreddy please close this as no-repro if we don't hear back by the end of the milestone

**Comment by Kotasudhakarreddy** [comment]
@btardif sure will do.

**Comment by panchagnula** [comment]
Closing since no response - please use the latest CLI version & re-activate if this still repros.
