### ISSUE TITLE
[Storage] File list does not work with -o tsv

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1591]
When I run `az storage file list -s my_share -o table` I get:

```
Name         Content Length    Type    Last Modified
-----------  ----------------  ------  ---------------
dir1/                          dir
license.txt  1122              file
```

However, when I run this with `-o tsv` I get:
```
2       None
```

This is likely the result of this command using a customized table output format.

**Comment by derekbekoe** [comment]
Related to https://github.com/Azure/azure-cli/issues/1553.
With tsv, often an appropriate query is required.

**Comment by tjprescott** [comment]
Should a query be required?

**Comment by derekbekoe** [comment]
I expect the output from `az storage file list -s my_share -ojson` contains complex objects so tsv can't pull out the fields that a user would expect.
Looks also related to https://github.com/Azure/azure-cli/issues/1062#issuecomment-252983746
