### ISSUE TITLE
az keyvault role assignment list issues

### ISSUE THREAD

**Issue by gbr746** [Azure/azure-cli#15914]
az keyvault role assignment list has a mandatory parameter (--hsm-name or --id)  as opposed to the page saying optional.
A parameter with --vault-name would be consistent, --hsm-name is not as also Standard key-vaults can have the new RBAC roles assigned. It does not seem to list roles for a specific key vault thought.

az keyvault role assignment list --hsm-name {vault name} does not seem to work.

The overall question is: how to list RBAC roles for a key-vault?
(  Access policies can be listed with az keyvault show --name {vault name}  )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c8df8ff-f34b-aff2-ece7-cb5aa2ddf493
* Version Independent ID: 576cb752-7b70-ea17-f66d-91af0e516553
* Content: [az keyvault role assignment](https://docs.microsoft.com/en-us/cli/azure/keyvault/role/assignment?view=azure-cli-latest#az_keyvault_role_assignment_list)
* Content Source: [latest/docs-ref-autogen/keyvault/role/assignment.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/keyvault/role/assignment.yml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
keyvault

**Comment by yungezz** [comment]
hi @bim-msft could you pls have a look? thanks

**Comment by bim-msft** [comment]
Hi @gbr746 , RBAC can be only used on HSM. For ordinary key vaults, the only way to control access is by using access policies.

**Comment by gbr746** [comment]
HI @bim-msft actually the contrary, the documentation says it only applies to key-vaults!
https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide
" Note
Key Vault resource provider supports two resource types: vaults and managed HSMs. Access control described in this article only [RBAC] applies to vaults. To learn more about access control for managed HSM, see Managed HSM access control."

**Comment by bim-msft** [comment]
@gbr746 Hi, you can try Azure RBAC using `az role` not `az keyvault role`, and I think it can be applied on normal vaults, `az keyvault role` is only for HSMs. Sorry, I misunderstood your scenario.

**Comment by yungezz** [comment]
hi @gbr746 as shared above, if you'd like vault level RBAC, pls use `az role` as in the doc https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide. `az keyvault role` is for HSM only.
