### ISSUE TITLE
az cosmosdb collection - commands deprecated 

### ISSUE THREAD

**Issue by pk422** [Azure/azure-cli#15921]
"az cosmosdb collection" commands are deprecated.
 Warning when these commands are used in cli
"This command has been deprecated and will be removed in a future release. Use 'cosmosdb sql container, cosmosdb mongodb collection, cosmosdb cassandra table, cosmosdb gremlin graph or cosmosdb table' instead." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d791e10-4181-cf15-1398-499eb0918c9c
* Version Independent ID: 2e5f864d-29bd-da4f-b964-a87a39f988c0
* Content: [az cosmosdb collection](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/collection?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/cosmosdb/collection.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cosmosdb/collection.yml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cosmosdb

**Comment by MehaKaushik** [comment]
Hi @pk422 yes this is correct. These commands are deprecated. Please use the API specific commands. Do you have any specific question for us ?

**Comment by MehaKaushik** [comment]
I don't understand the ask in this issue. Please open it again if you have any questions for us. @pk422

**Comment by JackSinclairT** [comment]
This 'az cosmosdb collection' is marked as deprecated, however where is the non-deprecated sql equivalent of this command? 

I don't see a "az cosmosdb sql collection" command available to carry out queries/deletes on SQL API documents?

@MehaKaushik

**Comment by MehaKaushik** [comment]
The commands available in CLI module are intended to perform database and container level operations. 

The data plane operations can not be done using these commands. You can use the cosmo v3 sdk for it (https://github.com/Azure/azure-cosmos-dotnet-v3)

**Comment by JackSinclairT** [comment]
Thanks @MehaKaushik, appreciate it!
