### ISSUE TITLE
[Network] Deprecate RTv1 and RTv2

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#15927]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
Deprecate Route table v1 and Route table v2
- RTv1: `az network route-table` in main repo
- RTv2: `az network vhub route-table` for vHub in CLI extension `virtual-wan`

Deprecation policy:
- For GA – 3 years
- For preview – 90 days

RTv3 is in #12959

**Minimum API Version Required**

**Swagger Link**

**Target Date**

**Comment by yonzhan** [comment]
Network

**Comment by yonzhan** [comment]
Feature finished.
