### ISSUE TITLE
Can not create RG with CLI 2.14.2  : The specified location 'france-central' is invalid. ("francecentral" is OK)

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/azure-cli#15935]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**

az account list-locations | grep "france"
    "id": "/subscriptions/7b5f97dc-3c4d-424d-8288-bdde3891f242/locations/**francecentral**",
    "name": "francecentral",
    "id": "/subscriptions/7b5f97dc-3c4d-424d-8288-bdde3891f242/locations/**francesouth**",
    "name": "francesouth",

az group create --name rg-cloudshell --location "france-central" --debug

Command arguments: ['group', 'create', '--name', 'rg-cloudshell', '--location', 'france-central', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0320B930>, <function OutputProducer.on_global_arguments at 0x0339ADB0>, <function CLIQuery.on_global_arguments at 0x033BFDB0>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'group': ['azure.cli.command_modules.resource']
Loading command modules:
Name                  Load Time    Groups  Commands
resource                  0.025        35       164
Total (1)                 0.025        35       164
These extensions are not installed and will be skipped: ['azext_ai_examples']
Loading extensions:
Name                  Load Time    Groups  Commands  Directory
Total (0)                 0.000         0         0
Loaded 35 groups, 164 commands.
Found a match in the command table.
Raw command  : group create
Command table: group create
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03568C90>]
az_command_data_logger : command args: group create --name {} --location {} --debug
metadata file logging enabled - writing logs to 'C:\Users\xxx\.azure\commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0367C738>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x0367C540>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0367C588>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0367C8A0>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0339ADF8>, <function CLIQuery.handle_query_parameter at 0x033BFDF8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x0367C4F8>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0367C4B0>]
Getting management service client client_type=ResourceManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
attempting to read file C:\Users\xxx\.azure\accessTokens.json as utf-8-sig
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - Authority:Performing instance discovery: ...
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - Authority:Performing static instance discovery
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - Authority:Authority validated via static instance discovery
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - CacheDriver:Found 4 potential entries.
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - CacheDriver:Resource specific token found.
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - CacheDriver:Returning token from cache lookup, AccessTokenId: b't6aLOqUKO+hLa3p9VWTtxH2u11lUaKFQydgqdBQ2JDk=', RefreshTokenId: b'7QNcIgQ7e4pnY5fkIEaTlQX6tcnuS30WAq1mpmZkrtY='
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - CacheDriver:Cached token is expired at 2020-11-11 13:57:30.062825.  Refreshing
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - TokenRequest:called to refresh a token from the cache
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - TokenRequest:Getting a new token from a refresh token
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token HTTP/1.1" 200 7367
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - OAuth2Client:Get Token Server returned this correlation_id: c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - CacheDriver:Created new cache entry from refresh response.
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - CacheDriver:Removing entry.
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - CacheDriver:Adding entry AccessTokenId: b'J/XfgVhE1EYHKFnpABytBmUxhB/dZ8cHnv/3gvRmJOU=', RefreshTokenId: b'dK/Ctjj/Kc5t9DlhfiwrIq/dWuRxc35JlUkM13Udr64='
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - CacheDriver:Updating 3 cached refresh tokens
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - CacheDriver:Remove many: 3
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - CacheDriver:Add many: 3
adal-python : c7629be1-f6f0-4fa8-95d6-e61d6cbf6dc1 - CacheDriver:Returning token refreshed after expiry.
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/7b5f97dc-3c4d-424d-8288-bdde3891f242/resourcegroups/rg-cloudshell?api-version=2020-06-01'
msrest.http_logger : Request method: 'PUT'
msrest.http_logger : Request headers:
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Content-Length': '30'
msrest.http_logger :     'User-Agent': 'python/3.6.8 (Windows-10-10.0.19041-SP0) msrest/0.6.18 msrest_azure/0.6.3 azure-mgmt-resource/10.2.0 Azure-SDK-For-Python AZURECLI/2.14.2 (MSI)'
msrest.http_logger : Request body:
msrest.http_logger : {"location": "france-central"}
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/7b5f97dc-3c4d-424d-8288-bdde3891f242/resourcegroups/rg-cloudshell?api-version=2020-06-01 HTTP/1.1" 400 194
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Length': '194'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-failure-cause': 'gateway'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger :     'x-ms-request-id': '91579478-acd0-44e8-95ae-c7d96cf1977d'
msrest.http_logger :     'x-ms-correlation-request-id': '91579478-acd0-44e8-95ae-c7d96cf1977d'
msrest.http_logger :     'x-ms-routing-request-id': 'FRANCECENTRAL:20201116T132303Z:91579478-acd0-44e8-95ae-c7d96cf1977d'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Mon, 16 Nov 2020 13:23:03 GMT'
msrest.http_logger : Response content:
msrest.http_logger : {"error":{"code":"InvalidResourceLocation","message":"The specified location 'france-central' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
msrest.exceptions : The specified location 'france-central' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'.
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-o2uit6zy\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-mdyrq85s\azure\cli\core\commands\__init__.py", line 654, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-mdyrq85s\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-mdyrq85s\azure\cli\core\commands\__init__.py", line 711, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-3fdrh26k\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-mdyrq85s\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-mdyrq85s\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-mdyrq85s\azure\cli\core\__init__.py", line 784, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-o3wjowf7\azure\cli\command_modules\resource\custom.py", line 1154, in create_resource_group
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-tba5qr_y\azure\mgmt\resource\resources\v2020_06_01\operations\_resource_groups_operations.py", line 154, in create_or_update
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidResourceLocation
**Message: The specified location 'france-central' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'.

cli.azure.cli.core.azclierror : BadRequestError: The specified location 'france-central' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'.
BadRequestError: The specified location 'france-central' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'.**
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03568DB0>]
az_command_data_logger : exit code: 1
Command ran in 2.987 seconds (init: 0.682, invoke: 2.305)
telemetry.save : Save telemetry record of length 3076 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\xxx\.azure"
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.

whereas az group create --name rg-cloudshell --location "francecentral" runs fine (no "-" between France and Central)

az aks get-versions -o table --location france-central runs fine as well

**Expected behavior**

**Environment summary**

az version
{
  "azure-cli": "2.14.2",
  "azure-cli-core": "2.14.2",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "asc": "0.1.0",
    "azure-firewall": "0.3.0"
  }
}

**Additional context**

--location "france-central" did run fine in the past, have you change the locations references ??

**Comment by yonzhan** [comment]
aks

**Comment by RakeshMohanMSFT** [comment]
az group create --name rg-cloudshell --location "francecentral". Please use a location with no special characters.

Please upgrade to latest version of az cli 2.40.0
