### ISSUE TITLE
list functions should allow inverse filtering on tags

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1593]
`az group list --tag key=value` is nice, but I'd like to filter inversely.

Specifically, I want to write a script that allows me to cleanup all resources in a resource group that contain `colemick` **and** lack a `colemick-permanent=true` tag.

I wasn't sure if there's a way to do this today...

**Comment by tjprescott** [comment]
@colemickens you should be able to use the `--query` functionality to accomplish this.

**Comment by colemickens** [comment]
(Let me know if you'd prefer a different issue for this, but) I can't get it to work like I might've expected. 

This has no output:

```az group list -o json --query '[?tags.colemickpermanent == `true`].name'```

Yet, if I feed it the same input data on the JMESPath website, I get output.

```
az group list -o json

[
  {
    "id": "/subscriptions/[redacted]/resourceGroups/colemick-acs-linuxdev",
    "location": "westus2",
    "managedBy": null,
    "name": "colemick-acs-linuxdev",
    "properties": {
      "provisioningState": "Succeeded"
    },
    "tags": {
      "colemickpermanent": "true"
    }
  }
]
```

Result from http://jmespath.org/ with ```[?tags.colemickpermanent == 'true'].name``` in the path box:

```
[
  "colemick-acs-linuxdev"
]
```

**Comment by colemickens** [comment]
As always, minutes after posting... this works: ```az group list -o json --query "[?tags.colemickpermanent == 'true'].name```

**Comment by colemickens** [comment]
In case anyone is curious, this is what I came up with for a cleanup function using `az` and tags: https://github.com/colemickens/dotfiles/commit/d8146e950c1bf39fbc54be40fae98c5ede300b26
