### ISSUE TITLE
create alert needs a description 

### ISSUE THREAD

**Issue by Mexicoder** [Azure/azure-cli#15947]
az monitor alert create
--description is not optional. the command will fail as say so.

need to update the documentation to show this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f601495-154d-5e5c-3692-02f8f41516f7
* Version Independent ID: 2968e230-b7a0-b433-333a-af3bba69fd0e
* Content: [az monitor alert](https://docs.microsoft.com/en-us/cli/azure/monitor/alert?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/monitor/alert.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/monitor/alert.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Mexicoder** [comment]
you can't even do this `--description ""`
it won't accept an empty string

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
The command `az monitor alert create` is deprecated.
