### ISSUE TITLE
2 corrections to the documentation

### ISSUE THREAD

**Issue by mossywell** [Azure/azure-cli#15944]
2 corrections (both in the "create" section. The first is a typo correction. The second is to add clarification.

1. "The resource id of which private enpoint connect to." --> "The resource id of the private endpoint to connect to."

2. "Name or ID of an existing subnet. If name specified, also specify --vnet-name. If you want to use an existing subnet in other resource group or subscription, please provide the ID instead of the name of the subnet." --> "Name or ID of an existing subnet. If the name is specified, also specify --vnet-name. If you want to use an existing subnet in other resource group or subscription, please provide the ID instead of the name of the subnet and do not specify the --vnet-name."

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8911e94f-9496-a68d-50c0-b5d536a375a4
* Version Independent ID: cc37b77b-0fa2-991b-e16b-fcdbbf183853
* Content: [az network private-endpoint](https://docs.microsoft.com/en-us/cli/azure/network/private-endpoint?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/private-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/private-endpoint.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network
