### ISSUE TITLE
Table output without headers

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1594]
How do I get `--output=table` but without the header and `-----` line(s).

For now I'm using `tail -n+3`.

**Comment by tjprescott** [comment]
Currently table format always shows headers. Does `-o tsv` not work for your scenario? The default table format does not apply to TSV, so you may need to specify an appropriate query.

**Comment by johanste** [comment]
We tried to make tsv the choice for line based output for automated consumption by other tools (grep etc.) and --table for human consumption in the terminal/console window. 

@colemickens, do you have a specific use case in mind where this does not work?

**Comment by colemickens** [comment]
`tsv` works for this. thanks!

**Comment by gjustice** [comment]
It might seem hokey, but one use case that came up for me, is in writing a script that did multiple consecutive NSG rule additions, suppressing the header on all but the first rule would have led to an almost user-friendly output without much effort.  Yes, the output does not line up but it still would look decent enough, way better than with all those extra headers and line-spacers.
