### ISSUE TITLE
Upgrade failed for 2.0 to 2.14

### ISSUE THREAD

**Issue by saikongara** [Azure/azure-cli#15956]
Upgrade failed for 2.0 to 2.14 for azure CLI, followed the documentation but it didn't work. Please find below the error

az upgrade
az: 'upgrade' is not in the 'az' command group. See 'az --help'.

**Comment by yungezz** [comment]
hi @saikongara `az upgrade` is released in 2.11.0. You need to manual upgrade to version >=2.11.0, then run az upgrade.

**Comment by saikongara** [comment]
how to manually upgrade to version >=2.11.0 ?

**Comment by saikongara** [comment]
Installed the latest version using `homebrew` on my Mac, it worked and I could use 2.15.x now.
