### ISSUE TITLE
WebApp:az webapp create-remote-connection doesn’t work for Windows App Service Plan

### ISSUE THREAD

**Issue by ecc256** [Azure/azure-cli#15968]
Unable to open console with
_az webapp create-remote-connection_
It show message:
_"Only Linux App Service Plans supported, Found a Windows App Service Plan"_
I can open console for the same App Service in web GUI and both Kudu Remote Execution Consoles "CMD and PowerShell", meaning there is no problem on server side.
create-remote-connection works properly linux apps, so I assume az cli configuration is correct.

Could somebody share the proper **az cli** command to open console for windows apps, please?
Thanks

**Comment by ecc256** [comment]
Guys,
I see, this issue is **removed this from the S181 milestone # days ago.**
Could you tell, when it'll be fixed approximately, please?
Or provide a workaround...

**Comment by btardif** [comment]
Windows webapps don't have ssh-server, the Kudu PS and CMD terminal are not SSH

**Comment by ecc256** [comment]
Byron,
Could you clarify how to connect to "Kudu PS or CMD terminal" via **az cli** command, please?
Thanks!
