### ISSUE TITLE
Clarify how to remove multiple legal hold tags with `az storage container legal-hold [clear|set]`

### ISSUE THREAD

**Issue by alexwlchan** [Azure/azure-cli#15965]
I'm using `az storage container legal-hold clear` to remove legal hold tags on a Blob Storage container. Quoting part of the help text:

```
$ az storage container legal-hold clear --help

Command
    ...

Arguments
    --tags          [Required] : Each tag should be 3 to 23 alphanumeric characters and is
                                 normalized to lower case.
    …
```

The name "tags" implies that this argument can be used to delete multiple tags in one go – rather than running multiple commands, running one tag at a time – but it wasn't clear to me how you're meant to do this.

I found out by searching the repo and discovering a test that deletes multiple tags, but it could be clearer from the help text/documentation:

https://github.com/Azure/azure-cli/blob/a2f2ec07c93e46103d703f98710e5756acfab085/src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_container_legal_hold.py#L29-L31

The same seems to be true of the `set` command.

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.5
Installer: HOMEBREW

azure-cli 2.10.1 *

```

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @alexwlchan , I have tested the feature and it works as expected:
```
❯ az storage container legal-hold set --account-name xxxxx -c test --tags aaa bbb cccc -g zuh
{
  "hasLegalHold": true,
  "tags": [
    "aaa",
    "bbb",
    "cccc"
  ]
}
```

```
❯ az storage container legal-hold clear --account-name xxxxx -c test --tags aaa bbb cccc -g zuh
{
  "hasLegalHold": false,
  "tags": []
}
```

If you still have the issue, could you show me the debug info with `--debug` in the command.

**Comment by alexwlchan** [comment]
The problem isn’t *“setting/clearing multiple tags is broken”*, more *”I couldn’t work out how to set/clear multiple tags from the documentation”*.
