### ISSUE TITLE
"az ad app permission admin-consent" returns "service unavailable" when logged with a service principal

### ISSUE THREAD

**Issue by SplashA** [Azure/azure-cli#15967]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
"az ad app permission admin-consent" returns "service unavailable" when logged in with a service principal but works fine with a regular user. 

**To Reproduce**
I guess just launch the following command line while logged in with a service principal : 

`az ad app permission admin-consent --id {}`

**Expected behavior**
To actually validate the grants in the api permissions section of the app in the active directory 

**Environment summary**

```
Ubuntu Bullseye - bash for windows
azure-cli versions : {                                 
  "azure-cli": "2.14.0",          
  "azure-cli-core": "2.14.0",     
  "azure-cli-telemetry": "1.0.6", 
  "extensions": {}                
}   
```                              

**Additional context**
* Both the user used to test and the service principal are global administrator on the Active Directory. 
* it's an active directory B2C
* the whole app and its apis were created by the same service principal using the graph api

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/12137#issuecomment-596567479 for the explanation and workaround.
