### ISSUE TITLE
Add new commands for Storage Mgmt 2016-05-01 

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1597]
After https://github.com/Azure/azure-sdk-for-python/pull/913 is merged, add new storage mgmt API list operations for account and service SAS.

**Comment by troydai** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/1833
Per discussion with storage team the two new API introduced in the 2016-12-01 release do not need CLI command representation.
