### ISSUE TITLE
[Azure Monitor] Onboarding Azure Monitor Control Service - Data Collection Rules

### ISSUE THREAD

**Issue by herreraj-ms** [Azure/azure-cli#15970]
**Resource Provider**

   - AMCS RP (Data Collection Rules) is a feature of Azure Monitor 

**Description of Feature or Work Requested**

   - [Description] Azure Monitor Control Service (AMCS) is responsible for storing and distributing users' monitoring configuration exposed through ARM API. The configuration is expressed in two types of resources: 
      1) Data collection rule (DCR) - defines: Data Sources (WHAT data should be collected), Destinations (WHERE it should be sent) and Data flows (HOW to route data streams) 
      2) Association (DCRA) - defines to which monitorable resources given collection rule should be applied.
   - [Work requested] Onboard AMCS RP into Azure CLI (Implementation of CLI's commands)
   - Documentation Links:
      1) [Overview] https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-collection-rule-overview
      2) [Rest API docs] https://docs.microsoft.com/en-us/rest/api/monitor/datacollectionrules
      3) [Schema detail] https://docs.microsoft.com/en-us/rest/api/monitor/datacollectionrules/create
      4) Python SDK operations are present in this version: https://pypi.org/project/azure-mgmt-monitor/0.12.0/

**Minimum API Version Required**

   - 2019-11-01-preview

**Swagger Link**

   - [DCR] https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2019-11-01-preview/dataCollectionRules_API.json
   - [DCRA] https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2019-11-01-preview/dataCollectionRuleAssociations_API.json

**Target Date**

   - Nov/Dec 2020

**Comment by yonzhan** [comment]
perceiving

**Comment by kairu-ms** [comment]
@herreraj-ms  I will add two command groups:
```bash
az monitor data-collection rule
az monitor data-collection rule association
```

**Comment by kairu-ms** [comment]
@herreraj-ms the patch method of dataCollectionRules_API only support tags property. Should I need to call put method for other property updating?

**Comment by herreraj-ms** [comment]
> will add two command grou

**Comment by herreraj-ms** [comment]
> @herreraj-ms I will add two command groups:
> 
> ```shell
> az monitor data-collection rule
> az monitor data-collection rule association
> ```

LGTM

**Comment by herreraj-ms** [comment]
> @herreraj-ms the patch method of dataCollectionRules_API only support tags property. Should I need to call put method for other properties updating?

Yes. Patch operation only receives tag property. To update any other property, the complete schema must be sent in a PUT operation.
