### ISSUE TITLE
Azure CLI application list command

### ISSUE THREAD

**Issue by VigneshKiru** [Azure/azure-cli#15973]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I am not able to show the application list or application type using below command.
It's producing the empty result.
PS C:\windows\system32> az sf application list -g rg_testmaxdiskviki -c testmaxdiskviki
{
  "nextLink": null,
  "value": []
}

CX experiencing this issue from their side.
I just did repro and confirmed from my end as well.

**To Reproduce**
1. Deploy the sample voting app to your sample cluster.
2. Install the Azure CLI using the below link
   https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli
3. Run the below commands in your Powershell.
   az login
   az account set --subscription subID
   az sf application list -g rg_testmaxdiskviki -c testmaxdiskviki (showing empty result)

**Expected behavior**
I believe it should show the application list.

**Environment summary**

**Additional context**

**Comment by PaulCharlton** [comment]
in debug mode, the AZ command reports:
`urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/1b907cdd-2fcf-40e0-b8c9-6f18fce5d955/resourceGroups/PlatformFabric-ATRProd02US/providers/Microsoft.ServiceFabric/clusters/SrvFabC01WSFCautqmslrdo/applications?api-version=2020-03-01 HTTP/1.1" 200 None
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Transfer-Encoding': 'chunked'
msrest.http_logger :     'Content-Type': 'application/json'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-reads': '11999'
msrest.http_logger :     'x-ms-request-id': 'f7aaeb53-74e3-4751-82e2-b6da07eacbc5'
msrest.http_logger :     'x-ms-correlation-request-id': 'f7aaeb53-74e3-4751-82e2-b6da07eacbc5'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTUS:20201119T011024Z:f7aaeb53-74e3-4751-82e2-b6da07eacbc5'
msrest.http_logger :     'Date': 'Thu, 19 Nov 2020 01:10:23 GMT'
msrest.http_logger : Response content:
msrest.http_logger : {
  "value": []
}
`

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to check is this caused by storage account connection again?

**Comment by fengzhou-msft** [comment]
> hi @fengzhou-msft could you pls help to check is this caused by storage account connection again?

The response status is 200, route to service team to check.

**Comment by VigneshKiru** [comment]
Thank you everyone. We got an update from Product team that, application related commands(Azure CLI) will work only for the applications which deployed over ARM template. Hence closing this.

**Comment by PaulCharlton** [comment]
@VigneshKiru -- our SF apps are deployed by ARM templates and we still have this issue!!  please reopen the ticket

**Comment by sicklittlemonkey** [comment]
> Thank you everyone. We got an update from Product team that, application related commands(Azure CLI) will work only for the applications which deployed over ARM template. Hence closing this.

The docs note this, but can we have an explanation for this terrible limitation? I deploy SF apps from a DevOps release pipeline, so not being able to use Microsoft's "next generation multi-platform command line experience for Azure" to manage these is pretty disappointing.
