### ISSUE TITLE
"az network application-gateway ssl-cert create" command requires --cert-password flag, even if SSL certificate does not have a password

### ISSUE THREAD

**Issue by loganballard** [Azure/azure-cli#15976]
**Describe the bug**

Addition of an existing SSL certificate to an application gateway using `az network application-gateway ssl-cert create` requires a password.  SSL certificates that are not encrypted (for instance, many self-signed certificates) often do not have passwords, so it is not necessarily reasonable to require an SSL certificate that is used by an application gateway to have a password in the CLI.

**To Reproduce**

Have a self-signed SSL certificate that does not require a password.  For example, generate via [openssl](https://www.openssl.org/):

`$> openssl req -newkey rsa:2048 -new -nodes -x509 -keyout key.pem -out cert.pem`

Attempt to use in your app gateway:

```
$>az network application-gateway ssl-cert create -g {} --gateway-name {} -n key --cert-file key.pem --cert-password ''
None
To use SSL certificate, you must specify both the filename and password
```

**Expected behavior**

`--cert-password` should be optional.

**Environment summary**

```$> $ az --version
azure-cli                         2.10.1 *

command-modules-nspkg              2.0.3
core                              2.10.1 *
nspkg                              3.0.4
telemetry                          1.0.4 *

Extensions:
azure-devops                      0.18.0

Python location '{}/python'
Extensions directory '{}/.azure/cliextensions'

Python (Darwin) 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Additional info**

[It looks like the bug occurs here.](https://github.com/Azure/azure-cli/blob/ca102c14a48019dba4b305a4dcafb55647ade1a1/src/azure-cli/azure/cli/command_modules/network/_validators.py#L249)

```
def validate_ssl_cert(namespace):
    params = [namespace.cert_data, namespace.cert_password]
    if all([not x for x in params]) and not namespace.key_vault_secret_id:
        # no cert supplied -- use HTTP
        if not namespace.frontend_port:
            namespace.frontend_port = 80
    else:
        if namespace.key_vault_secret_id:
            return
        # cert supplied -- use HTTPS
        if not all(params):
            raise CLIError(
                None, 'To use SSL certificate, you must specify both the filename and password')
```

The validator should check that `namespace.cert_data` exists, but `namespace.cert_password` need not exist.

**Comment by yonzhan** [comment]
network

**Comment by Zeka13** [comment]
can you provide workaround please?

**Comment by msyyc** [comment]
Because of the validator check, both of ssl-file and password is necessary. So if hurried to use the function, please use ssl file with password. And we will release a new CLI version at around 2020/12/31.
