### ISSUE TITLE
az aks list ResourceNotFoundError error

### ISSUE THREAD

**Issue by deathgaze** [Azure/azure-cli#15987]
## Describe the bug
Azure CLI seems to be retaining some kind of state from a previous cluster I created and removed. Now this command is failing and I don't know how to get it working again.

**Command Name**
`az aks list`

**Errors:**
```
ResourceNotFoundError: Resource group 'pod-iot-demo' could not be found.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a resource group and cluster 
- Delete the resource group and cluster
- Add a new resource group and cluster
- `az aks list`

## Expected Behavior
Command lists my aks clusters.

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.6
Installer: HOMEBREW

azure-cli 2.15.0

Extensions:
azure-iot 0.9.4
aks-preview 0.4.66

```

**Comment by yonzhan** [comment]
aks

**Comment by RakeshMohanMSFT** [comment]
[az config set](https://docs.microsoft.com/en-us/cli/azure/config?view=azure-cli-latest#az-config-set) is used to set default values, youu can use unset to remove. Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
