### ISSUE TITLE
[Compute] Add optional parameter --EdgeZone to support extended locations

### ISSUE THREAD

**Issue by viananth** [Azure/azure-cli#15988]
**Resource Provider**

Compute

**Description of Feature or Work Requested**

Add an “--EdgeZone” parameter for below cmds
Note: the underlying ARM property is called “extended locations”, and is intended to cover several types of extended locations including EdgeZone, among others. We do not want to directly reflect this into the cmdlets (by say, having --ExtendedLocationType and --ExtendedLocationName parameters). Instead, for cmdlets reflecting resources that can be created in edge zones, we prefer to offer a simple --EdgeZone parameter (this infers the extended location type, and the value is the extended location name).

Add optional parameter --EdgeZone to the following Az.Compute cmdlets:
```cli
az vm image 
az vm image list-offers  
az vm image list-skus 
az disk 
az image create        
az snapshot create 
az vm create   
az vmss create    


Add optional parameters "--ResourceType" & "--EdgeZone":
az vm list-skus 
```
Autocomplete support:
When --EdgeZone is used, tab completion should pull edgezones supported for the main region.

**Minimum API Version Required**

2020-06-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/compute-2020-12/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json
Powershell FR: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/776

**Target Date**

December 2020

**Comment by yonzhan** [comment]
Compute

**Comment by qwordy** [comment]
@viananth I noticed that the swagger change has not been merged to master branch? When will it be merged? Azure CLI can't release this until swagger change is merged to master branch.

**Comment by qwordy** [comment]
@viananth

**Comment by viananth** [comment]
> @viananth I noticed that the swagger change has not been merged to master branch? When will it be merged? Azure CLI can't release this feature until swagger change is merged to master branch.

@qwordy The feature branch for the swagger change is scheduled to be merged on 12th of Jan. 
https://github.com/Azure/azure-rest-api-specs/tree/compute-2020-12

**Comment by qwordy** [comment]
`az vm list-skus `, swagger is not ready. Others are finished.
