### ISSUE TITLE
WebApp:Error while running 'az appservice' on arm64 Ubuntu 20.04

### ISSUE THREAD

**Issue by joelbyford** [Azure/azure-cli#15985]
## Describe the bug
Simply running `az appservice` after logging in successfully errors out with ModuleNotFound.  Running 'az sql db list` works fine. 

**Command Name**
`az appservice`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
- `az appservice -h`

## Expected Behavior
Provide a list of commands 

## Environment Summary
```
Linux-4.19.128-microsoft-standard-aarch64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```
## Additional Context
Running in WSL on Windows on Arm (ARM64) Samsung Galaxy Book S

**Comment by joelbyford** [comment]
May be related to #15957 ?

**Comment by yonzhan** [comment]
appservice

**Comment by yungezz** [comment]
hi @joelbyford could you pls try uninstall 2.0.81 and  install latest Azure CLI? The issue is caused by a problematic package in Focal release 2.0.81, detail in issue https://github.com/Azure/azure-cli/issues/14011. Let us know if any other question.

**Comment by joelbyford** [comment]
Did not work, but `pip3 install decorator` fixed it.  Assume the install scripts are missing this command.

**Comment by joelbyford** [comment]
Confirmed earlier today that the packages at `packges.microsoft.com` do not currently work on arm64.  In the mean time. . .here is the workaround to get the AZ CLI working on any arm64 Ubuntu 20.04 [Focus] (WSL or otherwise):
- Follow all the **MANUAL** install instructions on the [docs](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt#manual-install-instructions) website.
- **Important**: Skip Step 3 which is meant to redirect you to the `packages.microsoft.com`.  Yes, even omitting the `[arch=amd64]` will still break as the package distributed there is currently x64 only. Just skip the step so it uses Debian's own package repo (housing an older but more portable version of the CLI) for now.
- Add the `decorator` Python package that this older install of az-cli is missing by running `pip3 install decorator`
- Run `az login` and ensure everything works.

I'm in conversations with the team to try and fix the packages distributed at packages.microsoft.com and will update this issue once resolved.

**Comment by joelbyford** [comment]
@fengzhou-msft, believe this is related to the [install instructions](https://github.com/joelbyford/azure-docs-cli/blob/jobyford/docs-ref-conceptual/install-azure-cli-apt.md) you help maintain.

**Comment by joelbyford** [comment]
[Debian apt Docs](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#overview) have been updated correctly to reflect they will not work with ARM64.  [Install Script](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script) is silent on the topic, but it will install correctly on ARM64 either natively or as a WSL2 Ubuntu install.
