### ISSUE TITLE
AZ Tool Caching Service Principals

### ISSUE THREAD

**Issue by JargoonPard** [Azure/azure-cli#1599]
While trying to provision a new kubernetes cluster using acs I ran into an issue with a service principal from a different account was assigned to the cluster.

The SP that my kubernetes installation is using is in a different subscription that is in a different account.  I use two different accounts, a corporate account tied to my corporate credentials, and an MSDN account tied to my personal credentials. I have noticed occasionally that when I list the accounts using `az account list` that I will sometimes see accounts from both login credentials.

Yesterday when I created my new kubernetes cluster the first time I ran the command `az acs ...` it failed because it couldn't find the resource group but not until after it had done some SP provisioning. I fixed that and reran the command. My guess is that it somehow created another new SP in a different account/subscription than the one in which it created the actual cluster and associated the kubernetes config with the wrong SP.

**Comment by yugangw-msft** [comment]
>I will sometimes see accounts from both login credentials.
This is correct behavior. If you use cli to login to 2 accounts, it will remember/cache all subscriptions from 2 accounts

   > created my new kubernetes cluster the first time I ran the command `az acs ...`

I assume to use ` --service-principal` argument to create service principal on the fly? Or you have logged in as a service principal and create acs? 

  >it failed because it couldn't find the resource group but not until after it had done some SP provisioning.

You might have to ensure you are under right active subscription by using `az account set`

  > My guess is that it somehow created another new SP in a different account/subscription than the one in which it created the actual cluster and associated the kubernetes 
SP is a tenant specific entity which is not tied to a subscription. A single tenant can managed multiple subscriptions. For you situation, your multiple subscriptions will belong to one of the 2 tenants, one from your corporate account, and the other from you MSDN one.  When you you use `az account set` to ensure you are in right subscription and tenant, the SP will be created under that (tenant, subscription) pair. As long as you create `acs` under subscriptions belonging to the same tenant, it should work.

**Comment by JargoonPard** [comment]
I did not use --service-principal in the command at all. I was following the instructions here: https://docs.microsoft.com/en-us/azure/container-service/container-service-kubernetes-walkthrough

The SP was created in a subscription in a different tenant than where the cluster was created.

There does seem to be an issue with the initial subscription that is preventing me from successfully running ACS at all once that gets sorted out I will try and repro this again and provide additional information.

**Comment by yugangw-msft** [comment]
@brendandburns, I think this is a SP working with ACS, not used in general login

**Comment by brendandburns** [comment]
I believe that this is now fixed, there was a bug where SPs were not per subscription. They are now...

If this re-occurs please re-open.

Thanks!
