### ISSUE TITLE
Cookie-based affinity setting not working when using same cookie-name on http/https Httpsettings for same host

### ISSUE THREAD

**Issue by timvanderweijde** [Azure/azure-cli#15995]
**Describe the bug**
The browser-client is not being routed to the same server of the same backend pool when arriving at http port 80 and being redirected to the http port 443 of the same host.

**To Reproduce**
`All statements below are created by az network application-gateway .. `

- create 1 backend pool "backendPool-1" with say 8 machines
- create HttpSetting for protocol http port 80. **Enable Cookie-based affinity and use cookie name "afck-somehost"**
- create HttpSetting for protocol https port 443. **Enable Cookie-based affinity and use the same cookie name "afck-somehost"**
- create HttpListener for port 80 and host name "www.somehost.com" (Listener type = Multi site)
- create HttpListener for port 443 and host name "www.somehost.com" (Listener type = Multi site)
- create Rule 1 for HttpSetting port 80, HttpListener port 80 and for the backend pool "backendPool-1"
- create Rule 2 for HttpSetting port 443, HttpListener port 443 and for the same backend pool "backendPool-1"
- Request the host with http://www.somehost.com (http 80) with a redirect page
- User redirects to https://www.somehost.com (http 443), but with a different value in the **cookie "afck-somehost"**

**Expected behavior**
The value of the cookie "afck-somehost" is the same and the client is being routed to the same server from the backend pool.

**Environment summary**
Azure Portal - Application Gateway

**Additional context**
None

**Comment by yonzhan** [comment]
Not CLI related issue
