### ISSUE TITLE
Update for RHEL 6.x ELS

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-cli#16004]
**Resource Provider**
COMPUTE

**Description of Feature or Work Requested**
RHEL 6.10 enters end of lifecycle phase and RHEL 6.10 extended-lifecycle-support (ELS) offer starts. GA is Dec 1 2020. Customers need to update billing meter capability so that they will continue to get update for RHEL 6.10 till 2024. 

`az vm update --license-type`

Specifies that the Windows image or disk was licensed on-premises. To enable Azure Hybrid Benefit for Windows Server, use 'Windows_Server'. To enable Multitenant Hosting Rights for Windows 10, use 'Windows_Client'. For more information see the Azure Windows VM online docs.

**Specifies that the Linux image or disk was licensed in Azure. To enable RHEL 6 Extended-Lifecycle-Support (ELS). For more information see the Azure Red Hat Enterprise (RHEL) Extended Lifecycle Support online docs.**

accepted values: None, RHEL_BYOS, SLES_BYOS, Windows_Client, Windows_Server, **RHEL_ELS_6**

**Minimum API Version Required**
2020-06-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json

**Target Date**
As soon as possible. GA is Dec 1 2020

**Comment by yungezz** [comment]
hi @qwordy , this is a easy  fix, can we make it into this release? thanks.

**Comment by qwordy** [comment]
> 
> 
> hi @qwordy , this is a easy fix, can we make it into this release? thanks.

OK.
