### ISSUE TITLE
lacking details of set argument

### ISSUE THREAD

**Issue by donfouts** [Azure/azure-cli#16009]
if you do a show of a record you get back a json record and the following set argument here 
Update an object by specifying a property path and value to set. Example: --set property1.property2=.

would imply you use --set arecords.ipv4address=##.##.##.##  but that is not so simple is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8ef1e49-3042-7815-3273-ee5debe4dcb5
* Version Independent ID: a3ab4167-f0b8-a3a2-f8d4-7c0dec53a425
* Content: [az network dns record-set a](https://docs.microsoft.com/en-us/cli/azure/network/dns/record-set/a?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/dns/record-set/a.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/dns/record-set/a.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by haroldrandom** [comment]
`--set` is the fallback way for updating an Azure Resource if there is no explicit option to update the corresponding property.

What properties do you want to you update though? We could plan to add arguments for them.
