### ISSUE TITLE
WebApp:Mounting storage to webapp with invalid key returns success

### ISSUE THREAD

**Issue by freastro** [Azure/azure-cli#16002]
## Describe the bug

**Command Name**
`az webapp config storage-account update`

**Errors:**
Returns a success response when provided with an invalid `access-key`. The response is the same regardless of whether the `access-key` is correct or not. This falsely led me to believe that the storage account was added to the webapp when it actually had failed.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

The issue seems to happen both for the `add` and `update` commands:
- `az webapp config storage-account add --resource-group {} --name {} --custom-id {} --storage-type {} --share-name {} --account-name {} --mount-path {} --access-key {}`
- `az webapp config storage-account update --resource-group {} --name {} --custom-id {} --storage-type {} --share-name {} --account-name {} --mount-path {} --access-key {}`

## Expected Behavior
I expect the command to return an error if the `access-key` is invalid.

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *

Extensions:
ai-examples 0.2.4

```
## Additional Context
I ran into this issue when on a call with an Azure support engineer where they pasted in their access key, received a success message after running the command, and were surprised when the storage account was not available to the webapp. We were only able to solve it after guessing that the access key needed to be in quotes. So I don't think I'm the only one that has an issue.

If this is the wrong place to report the issue please let me know where I should report it instead.

**Comment by yonzhan** [comment]
webapp

**Comment by btardif** [comment]
@freastro in general we don't validate access to other resources. the same is true for connection strings.

This is by-design
