### ISSUE TITLE
Caution should be noted about using --pull-secret

### ISSUE THREAD

**Issue by josephtingiris** [Azure/azure-cli#16001]
Using --pull-secret will overwrite the arosvc.azureecr.io pull secret, which contradicts (or doesn't properly explain) that doing so (improperly) will void the support policy for ARO, per https://docs.microsoft.com/en-us/azure/openshift/support-policies-v4

Additionally, this page cautions, https://docs.microsoft.com/en-us/azure/openshift/howto-add-update-pull-secret

```Do not remove or alter your the arosvc.azurecr.io entry from your pull secret. This section is needed for your cluster to function properly.```

The documentation for az aro create with --pull-secret should mimic those cautions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08eb181a-b377-c854-69cc-3b9307f59f72
* Version Independent ID: 2142cb43-b027-86a1-6d3c-2f77bf86d177
* Content: [az aro](https://docs.microsoft.com/en-us/cli/azure/aro?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/aro.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/aro.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
aro

**Comment by mjudeikis** [comment]
@josephtingiris  I think this should be fixed by ARO operator now?

**Comment by josephtingiris** [comment]
Yes, it appears so.

**Comment by bennerv** [comment]
@yonzhan  this can be closed as it was addressed.
