### ISSUE TITLE
Documentation - Broken link in CONTRIBUTING.rst - http://azure.github.io/guidelines.html

### ISSUE THREAD

**Issue by surenderssm** [Azure/azure-cli#16015]
**Describe the bug**

Broken link in `Microsoft Azure Projects Contribution Guidelines <http://azure.github.io/guidelines.html>`

**To Reproduce**

Navigate to https://github.com/Azure/azure-cli/blob/dev/CONTRIBUTING.rst and click on `Microsoft Azure Projects Contribution Guidelines`

**Expected behavior**

Should be redirecting to correct page.
**Additional context**

Links takes you to generic 404 page.
Looks like this is broken in other projects as well.

![image](https://user-images.githubusercontent.com/12485087/99964269-0b7eef80-2db9-11eb-8c2b-a87419176dba.png)

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to fix? thanks
