### ISSUE TITLE
Missing RBAC CLI example in documentation

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-cli#1601]
Here:
https://docs.microsoft.com/en-us/azure/active-directory/role-based-access-control-manage-access-azure-cli

I miss A LOT the Python CLI sample. It's (for some AD reason....) the sample I need the most. Today it's the third times I need it, and I have to send people to the old CLI one :(

Sending people to the generated documentation is not precise enough.

**Comment by lmazuel** [comment]
Fourth: https://github.com/Azure-Samples/virtual-machines-python-manage/issues/4

**Comment by squillace** [comment]
@lmazuel noted. I'm working on updating that topic at the moment.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
