### ISSUE TITLE
webapp:az appservice plan create fails on use of ASE resource id with --app-service-environment

### ISSUE THREAD

**Issue by dtewinkel** [Azure/azure-cli#16026]
## Describe the bug

**Command Name**
`az appservice plan create`

**Errors:**
```
App service environment '/subscriptions/***/resourceGroups/***/providers/Microsoft.Web/hostingEnvironments/***' not found in subscription.
```

## To Reproduce:
Run:
- `az appservice plan create --name {} --resource-group {} --app-service-environment {} --is-linux --sku {} --number-of-workers {} --location {} --tags {} {} {} --output {} --verbose`
with a resource ID of an ASE provided to the --app-service-environment.

## Expected Behavior

`az appservice plan create` with a resource ID for `--app-service-environment` works. It used to do up to version 2.14.2.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.15.1

Extensions:
alertsmanagement 0.1.0
application-insights 0.1.12
azure-devops 0.18.0
azure-iot 0.10.7
kusto 0.2.0
log-analytics 0.2.1
logic 0.1.1
portal 0.1.1
subscription 0.1.4

```

**Comment by yungezz** [comment]
route to appropriate service team.

**Comment by Kotasudhakarreddy** [comment]
@dtewinkel - can you try passing **ASE** `name` instead of `id`. it should work if you pass `name`. will get back to you on `id` part.

**Comment by dtewinkel** [comment]
@Kotasudhakarreddy, passing in the name for the ASE works as long as the ASE is in the same resource group as where the ASP is created in. In our case the ASE ans the ASP are in different resource groups, as the ASE is share between a number of ASP for different applications.

**Comment by dtewinkel** [comment]
@Kotasudhakarreddy, my bad, it works with 2.15.1. Initially I retested with 2.14.2. 
But unfortunately this still is a breaking change. Old scripts won't run on 2.15.0 or newer. We have quite a few of them. Newer scripts won't run on older versions, because they require the resource ID.

**Comment by Kotasudhakarreddy** [comment]
@dtewinkel - thanks for your update. we will look in to it further and update you.
@panchagnula - can you please suggest on backward compatibility and vice versa .

**Comment by dtewinkel** [comment]
@panchagnula, @Kotasudhakarreddy 
I would like to add that the help for `az appservice plan create -h` on az CLI 2.15.1 states "name or **ID**":
`   --app-service-environment -e   : Name or ID of the app service environment.`

**Comment by panchagnula** [comment]
@madsd since you own these commands please take a look. Thanks!
