### ISSUE TITLE
az keyvault secret show crashes

### ISSUE THREAD

**Issue by vigneshmsft** [Azure/azure-cli#16022]
## Describe the bug

**Command Name**
`az keyvault secret show`

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
<frozen importlib._bootstrap>, ln 961, in _find_and_load_unlocked
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Just run the below command, expect to see the help menu or invalid arguments prompt, but the cli just crashes.

- `az keyvault secret show`

## Expected Behavior
Should prompt that a required module is missing and the instructions to install it without crashing.
## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.29
Python 3.8.2
Shell: zsh

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yungezz** [comment]
hi @bim-msft could  you pls help to look at the issue, is it same with https://github.com/Azure/azure-cli/issues/16013? cc @houk-ms for awareness

**Comment by yungezz** [comment]
hi @vigneshmsft could you pls uninstall 2.0.81 and install latest Azure CLI? there's some issue in 2.0.81 version detail pls see https://github.com/Azure/azure-cli/issues/14011.

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/19640#issuecomment-1148202854
