### ISSUE TITLE
az network public-ip list gives error

### ISSUE THREAD

**Issue by lmcthbe** [Azure/azure-cli#16028]
## Describe the bug

**Command Name**
`az network public-ip list`

**Errors:**
```
ipv4
Traceback (most recent call last):
network/v2020_06_01/models/_network_management_client_enums.py, ln 24, in __getattr__
    return cls._member_map_[name.upper()]
KeyError: 'IPV4'

...

network/v2020_06_01/models/_network_management_client_enums.py, ln 26, in __getattr__
    raise AttributeError(name)
AttributeError: ipv4
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network public-ip list --subscription {}`

## Environment Summary
```
Linux-5.9.0-kali2-amd64-x86_64-with-glibc2.29
Python 3.8.6
Installer: PIP

azure-cli 2.14.2 *

Extensions:
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
network

**Comment by haroldrandom** [comment]
thanks for providing this for us. It's also related to one of our fix in the long term and had long been pending no demo to reproduce :)

**Comment by haroldrandom** [comment]
It's similar to https://github.com/Azure/azure-cli/issues/15984

**Comment by haroldrandom** [comment]
@lmcthbe We found some similar scenarios the cannot find properties of IPVersion. But cannot reproduce successfully. No idea what's going on. Could you provide what environment are you in and what steps had you done?

**Comment by lmcthbe** [comment]
I was running it from Kali and noticed that the az version is 2.14.2 (package by kali) and it was not the latest version. I removed it and install it via pip instead and now I got 2.15.1 which does not give me any more errors when listing public-ip from my subscription. 

Ticket can be closed.

**Comment by haroldrandom** [comment]
@lmcthbe how do you install Azure CLI in kaili ?

**Comment by lmcthbe** [comment]
It is a Kali package installed with apt install azure-cli but not really up to date as it is version 2.14.2 so I removed it and install azure-cli via pip instead and get the latest version
