### ISSUE TITLE
Setting AD-Admin via AZ CLI/Powershell for Synapse

### ISSUE THREAD

**Issue by CharlesAbetz** [Azure/azure-cli#16025]
Hi 

Looking at the either powershell or az cli I can't find what I am after for setting the AD Admin for the synapse workspace/sql pool.

az synapse workspace create or New-AzSynapseWorkspace 

OR 

az synapse sql pool create or New-AzSynapseSqlPool 

WIthout setting this I am finding I am getting inaccessible sql pools (something is not working with the Grant) when creating them through Automation (Azure DevOps).

If I set it manually everything is ok, but that isn't the point, I should be able to set it through a script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a8ce4bb-b234-dc91-cd2c-e5587caf6169
* Version Independent ID: 9f08c3b1-5ac8-81d3-02e4-f7111cfe0781
* Content: [az synapse workspace](https://docs.microsoft.com/en-us/cli/azure/ext/synapse/synapse/workspace?view=azure-cli-latest#ext_synapse_az_synapse_workspace_create)
* Content Source: [latest/docs-ref-autogen/ext/synapse/synapse/workspace.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/synapse/synapse/workspace.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
synapse

**Comment by idear1203** [comment]
@CharlesAbetz , sorry for the inconvenience. we are working on supporting this on both PowerShell and CLI side. 

For PowerShell side, the PR link is here: https://github.com/Azure/azure-powershell/pull/13489 . The command Set-AzSynapseSqlActiveDirectoryAdministrator will be available on 12/08.

For CLI side, this is still under development. This is supposed to be supported by the end of December. We plan to catch S180 that will be released by 12/29/2020.

**Comment by fengzhou-msft** [comment]
@idear1203 any update?

**Comment by idear1203** [comment]
Yes, the CLI support for this has been done in this PR: https://github.com/Azure/azure-cli/pull/16224
