### ISSUE TITLE
GrantSqlControlToManagedIdentity parameter not available

### ISSUE THREAD

**Issue by CharlesAbetz** [Azure/azure-cli#16033]
Please add GrantSqlControlToManagedIdentity to az synapse workspace module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a8ce4bb-b234-dc91-cd2c-e5587caf6169
* Version Independent ID: 9f08c3b1-5ac8-81d3-02e4-f7111cfe0781
* Content: [az synapse workspace](https://docs.microsoft.com/en-us/cli/azure/ext/synapse/synapse/workspace?view=azure-cli-latest#ext_synapse_az_synapse_workspace_create)
* Content Source: [latest/docs-ref-autogen/ext/synapse/synapse/workspace.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ext/synapse/synapse/workspace.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
synapse

**Comment by idear1203** [comment]
Thanks, we are working on this. Please expect January 2021.

**Comment by Sai-Kumar-1901** [comment]
@yonzhan: Is this issue resolved ??

**Comment by yonzhan** [comment]
@idear1203 any update for this issue?

**Comment by idear1203** [comment]
Try command group: `az synapse sql ad-admin`.

cc: @wonner @zesluo
