### ISSUE TITLE
VMSS Rolling Upgrade opt in flags 

### ISSUE THREAD

**Issue by ajjha-az** [Azure/azure-cli#16038]
**Resource Provider**

Compute Resource Provider (CRP) - > Virtual Machine Scale Sets (VMSS)

**Description of Feature or Work Requested**

VMSS Rolling Upgrade provides an upgrade facility that automatically applies VMSS model changes to the individual instances through a health-based orchestration. 
There are some additional opt-in flags we are introducing for Upgrade policy for VMSS. At the moment we expose these four properties that our customers configure  - 

1.	maxBatchInstancePercent - The maximum percent of total virtual machine instances that will be upgraded simultaneously by the rolling upgrade in one batch. Default: 20% 
2.	maxUnhealthyInstancePercent - The maximum percentage of the total virtual machine instances in the scale set that can be simultaneously unhealthy. Default: 20% 
3.	maxUnhealthyUpgradedInstancePercent - The maximum percentage of upgraded virtual machine instances that can be found to be in an unhealthy state. Default: 20% 
4.	pauseTimeBetweenBatches - The wait time between completing the update for all virtual machines in one batch and starting the next batch. Default: 0 seconds 

In addition to these four, we are introducing two new properties. Note that these are opt-in properties. 

1.	enableCrossZoneUpgrade - Setting this Boolean property will allow VMSS to ignore AZ boundaries when constructing upgrade batches, and only consider Update Domain and maxBatchInstancePercent to determine the batch size. 
2.	prioritizeUnhealthyInstances - Setting this Boolean property will lead to all unhealthy instances in a scale set getting upgraded before any healthy instances. 

**Minimum API Version Required**

2020-12-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/11184
[Rolling upgrade - Prioritize Unhealthy VMs.docx](https://github.com/Azure/azure-cli/files/5594864/Rolling.upgrade.-.Prioritize.Unhealthy.VMs.docx)

**Target Date**

2020-12-20

**Comment by yungezz** [comment]
HI @ajjha-az will sync with you in email for more detail

**Comment by qwordy** [comment]
New API version 2020-12-01

**Comment by qwordy** [comment]
I check the latest code and 2020-12-01 is not in master branch.

**Comment by ajjha-az** [comment]
@qwordy -  Any update?

**Comment by qwordy** [comment]
> 
> 
> @qwordy - Any update?

@ajjha, put into S185
