### ISSUE TITLE
The js version of azure network vpn-connection create doesnt seem to be working 

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#1603]
Ran the following command
C:\WINDOWS\system32>azure network vpn-connection create -g VV2 -l "East US" -n GW2ToGW1 -i "/subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV2/providers/Microsoft.Network/virtualNetworkGateways/VNet2GW" -r VV2 -e "/subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV1/providers/Microsoft.Network/virtualNetworkGateways/VNet1GW" -m VV1 -y Vnet2Vnet -k Aanand

Got the following error -
- Looking up virtual network gateway "/subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV2/providers/M+crosoft.Network/virtualNetworkGateways/VNet2GW"
error:   A virtual network gateway with name "/subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV2/providers/Microsoft.Network/virtualNetworkGateways/VNet2GW" not found in the resource group "VV2"

But the GW is actually present
C:\WINDOWS\system32>azure network vpn-gateway list -g VV2
info:    Executing command network vpn-gateway list
+ Looking up virtual network gateways
data:    Name     Location  Provisioning state  Gateway type  VPN type    SKU       Enable BGP  Private IP allocation  Private IP address
data:    -------  --------  ------------------  ------------  ----------  --------  ----------  ---------------------  ------------------
data:    VNet2GW  eastus    Succeeded           Vpn           RouteBased  Standard  false       Dynamic
info:    network vpn-gateway list command OK

Another Issue
---------------
There are multiple versions of resource group param. There is a RG1 and RG2 that go with VNET GW1 and VNET GW2. But there is also a separate resource grp param. Is that for GW to local network gateway connections?

**Comment by tjprescott** [comment]
This issue should be posted here: https://github.com/Azure/azure-xplat-cli

**Comment by tjprescott** [comment]
cc/ @amarzavery
