### ISSUE TITLE
JMESPath not working with AZ VM SHOW

### ISSUE THREAD

**Issue by phyoungmsft** [Azure/azure-cli#16032]
I'm try to use AZ VM SHOW to query the powerState of a VM. 

Using _az vm list -g "myRG" -d --query '[].{VMName:name, powerState:powerState}' --output table_, I'm able to get a list of VM's and their corresponding powerstate.

However, if I move the query over to Az VM Show, I'm not seeing any output come out.

Repro the issue: _az vm show -g myRG -n myVM -d --query '[].{VMName:name, powerState:powerState}' --output table_

Is this an issue with AZ VM SHOW jmespath?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/vm.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy could you pls help on this?

**Comment by qwordy** [comment]
@phyoungmsft  Please try
```
az vm show -g myRG -n myVM -d --query '{VMName:name, powerState:powerState}' --output table
```
`list` returns a list, so we use `[]`. `show` returns a single VM. No `[]` required.

**Comment by phyoungmsft** [comment]
Thanks @qwordy . Closing this.
