### ISSUE TITLE
az storage container create --public-access uses confusing labels creating security risks

### ISSUE THREAD

**Issue by e30chris** [Azure/azure-cli#1604]
CLI Version: 0.10.6
OS Type: Mac
Installation via:  pip

node-cli bug: [#3403](https://github.com/Azure/azure-xplat-cli/issues/3403)

Environment: AzureCloud

Description:
`az storage container create --public-access` uses confusing labels for each type of permission that can be granted, opening up the container to potential security issues with mistaken permissions granting public, wide open read access to the blob when the end user _thinks_ they are assigning the container a _storage role_.

If an Azure infrastructure is being engineered to use Azure Blob storage for Application and Linux OS logging, mistakenly setting a _Blob_ *ACL* on the container while creating it on the `azure-cli`, could open up the sensitive data inside the logs to internet wide read access.  Renaming the *ACL* options to be something more logically aligned to a permissions naming structure instead of a storage type naming structure, would avoid this potentially easy to make mistake.

Steps to reproduce:

Run `-h` for --public-access cli flag

```
az storage container create --public-access -h
                                              [--public-access {container,off,blob}]
```

Expected behavior:

```
az storage container create --public-access -h
                                              [--public-access {Private,ReadOnly,Public}]
```

The permission ACLs would be appropriately named in a logical fashion.  This would ensure the end user gives the storage container the correct permissions.

_Private = Private - no public access_
_ReadOnly = Read Only Access to everyone on the Internet_
_Public = Read & List Access to everyone on the internet_

Actual behavior:

```
az storage container create --public-access -h
                                              [--public-access {container,off,blob}]
```

The end user could very easily mistakenly apply the `blob` ACL to the container thinking they are wanting to create a `blob` type of container.    The permissions flag is the only flag that mentions what type of container you are creating, easily making the *permissions* flag appear to be the *type* flag, which there isnt one.

_Off = Private - no public access_
_Blob = Read Only Access to everyone on the Internet_
_Container = Read & Write Access to everyone on the internet_

**Comment by johanste** [comment]
We would prefer to use the same terminology as the portal. But it is a good suggestion. If we get to the point that we can convince the other CLIs and portal to use the proposed terminology, we will revisit this issue and consider providing the more clear aliases.

**Comment by williexu** [comment]
The help for the command gives a clear explanation on the behavior for each enum. 
Since we cannot rename them without breaking many users, I am closing this issue.
