### ISSUE TITLE
`az keyvault secret set` with `--value` fails when the secret starts with a dash

### ISSUE THREAD

**Issue by christianfosli** [Azure/azure-cli#16044]
**Describe the bug**

Running `az keyvault secret set`, passing the secret with `--value` fails when the secret starts with a dash (`-`).
It gives the error `ArgumentUsageError: argument --value: expected one argument`

Running with the `--debug` option shows that the secret value is interpreted as another argument. For example, passing `--value '-secretvalue'` shows a few interesting pointers:

```console
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fe759214620>]
az_command_data_logger : command args: keyvault secret set -n {} --value -s{} --vault-name {} --debug
# <a few lines omitted>
Event: CommandInvoker.OnPreParseArgs []
"-s" is an invalid parameter for command "keyvault secret set".
# < a few lines omitted>
cli.azure.cli.core.azclierror : ArgumentParseError: argument --value: expected one argument
ArgumentParseError: argument --value: expected one argument
```

**To Reproduce**

Given that I have a keyvault named "mykeyvault":

```console
az keyvault secret set -n mysecret --value '-secret' --vault-name mykeyvault
```

**Expected behavior**

A secret will be set/created with the value "-secret"

**Environment summary**

azure-cli 2.14.2 run with `docker run -it mcr.microsoft.com/azure-cli`

**Additional context**

I experimented with wrapping the secret in single and double quotes, but that makes no difference.
I also tried to escape the `-` with a `\`, but that causes the backslash to be a part of the secret itself, so it doesn't work.

**Comment by christianfosli** [comment]
After a bit of searching, I see that I may have created a duplicate of #2588 and that this behavior is caused by the argparse module in the python standard library.

I found a satisfactory work-around by using adding an equals sign to supply the argument value. i.e.

```console
az keyvault secret set -n mysecret --vault-name mykeyvault --value='-secret'
```

instead of

```console
az keyvault secret set -n mysecret --vault-name mykeyvault --value '-secret'
```

---

I wasn't aware that it was possible to use `--argument=value` syntax for azure-cli before I read the [related bug report for argparse](https://bugs.python.org/issue9334). Maybe it would be a good idea to add info about that to the help page for this command?

**Comment by yungezz** [comment]
hi @bim-msft could you pls help to have a look? thanks

**Comment by christianfosli** [comment]
Closing due to dupe with #2588
