### ISSUE TITLE
VM creation fails using --ssh-key-values with multiple values

### ISSUE THREAD

**Issue by devcovato** [Azure/azure-cli#16048]
## Describe the bug

**Command Name**
`az vm create`

**Errors:**
```
Deployment failed. Correlation ID: 838d8ded-8f75-4cda-8368-2581ac2d8d45. {
  "error": {
    "code": "InvalidParameter",
    "message": "The value of parameter linuxConfiguration.ssh.publicKeys.keyData is invalid.",
    "target": "linuxConfiguration.ssh.publicKeys.keyData"
  }
}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm create -g {} -l {} --name {} --image {} --size {} --public-ip-address {} --public-ip-sku {} --subnet {} --nsg {} --nsg-rule {} --admin-username {} --authentication-type {} --ssh-key-values {} {}` 

## Expected Behavior

Reading multiple public key files and create the VM successfully

## Environment Summary
```
Linux-5.4.0-54-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.15.1

Extensions:
aks-preview 0.4.66
azure-firewall 0.7.0

```
## Additional Context

I tried to set `--ssh-key-values` in multiple ways:

- `export SSH_KEY_VALUES=(~/.ssh/id_rsa.pub ~/.ssh/id_ed25519.pub)` and then `--ssh-key-values ${SSH_KEY_VALUES[@]}`. Failed
- `--ssh-key-values ~/.ssh/id_rsa.pub ~/.ssh/id_ed25519.pub`. Failed
- `--ssh-key-values "$(cat ~/.ssh/id_rsa.pub)" "$(cat ~/.ssh/id_ed25519.pub)"`. Failed
- `--ssh-key-values /home/REDACTED/.ssh/id_rsa.pub /home/REDACTED/.ssh/id_ed25519.pub`. Failed

I end up using only one file.

**Comment by yungezz** [comment]
hi @qwordy could you pls help to have a look? thanks

**Comment by sycured** [comment]
Any ETA or idea/workaround?

**Comment by zhoxing-ms** [comment]
@sycured This should be a service issue. Could you add the parameter `--debug` after the executed command, and then send the printed debug log to me?

**Comment by Drewm3** [comment]
@amjads1, please have a look at this to see if there is a service issue here.

**Comment by amjads1** [comment]
@srijang Per our chat, can you please look into this issue?

**Comment by srijang** [comment]
1/13/22: Currently under investigation. We haven't been able to reproduce this issue. Looking into this further. Maybe this issue could be solved using the custom data in CloudInit. I'll provide update once we have more information. ETA - 1/24/22.

**Comment by mries** [comment]
I have tested this myself.  It does look like the --ssh-key-values doesn't work as expected in the az cli.

**Comment by anhvoms** [comment]
This worked fine for me:
--ssh-key-values @/home/xyz/.ssh/key1.pub @/home/xyz/.ssh/key2.pub

**Comment by srijang** [comment]
This is working correctly. This ticket can be resolved.

**Comment by jaylabell** [comment]
Closing
