### ISSUE TITLE
Usage needs more details for alerts conditions

### ISSUE THREAD

**Issue by dmellonielet** [Azure/azure-cli#16051]
Comparing to the other popular public cloud provider's documentation, this documentation can improve with more details for users. For ex. when working to configure an alert, one has to figure out the format for creating a condition. This is no where listed on the page and requires using the  **az monitor alert create --help** to really understand the correct usage.

How does a user know what the --condition is supposed to look like? Until they use the cli and find this:
```

 --condition [Required] : The condition which triggers the rule.
        The form of a condition is "METRIC {>,>=,<,<=} THRESHOLD {avg,min,max,total,last} PERIOD".
        Values for METRIC and appropriate THRESHOLD values can be obtained from `az monitor metric`
        commands, and PERIOD is of the form "##h##m##s".
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f601495-154d-5e5c-3692-02f8f41516f7
* Version Independent ID: 2968e230-b7a0-b433-333a-af3bba69fd0e
* Content: [az monitor alert](https://docs.microsoft.com/en-us/cli/azure/monitor/alert?view=azure-cli-latest#az_monitor_alert_create)
* Content Source: [latest/docs-ref-autogen/monitor/alert.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/monitor/alert.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Monitor

**Comment by kairu-ms** [comment]
`az monitor alert` is deprecated. Please use `az monitor metrics alert` instead.
