### ISSUE TITLE
webapp:Unable to select a runtime version if it includes "space" in its name such as "Java SE"

### ISSUE THREAD

**Issue by v-yuwak** [Azure/azure-cli#16066]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
As following github, it seems "space" inside runtime version name is considered as delimiter as coded.
https://github.com/Azure/azure-cli/blob/ed1fe586d24b5d78127c0b616cd7e32b765d0bfc/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L2572
As a result, CLI outputs an error as follow which suggests "Java SE" is processed as "Java|SE".
"Windows runtime 'java\|1.8\|Java\|SE\|8' is not supported. Please invoke 'az webapp list-runtimes' to cross check"

**To Reproduce**
Execute the command with a runtime version that includes "space" in the name, such as "az webapp create ~ omitted ~ --runtime 'java | 1.8 | Java SE | 8'.

**Expected behavior**
"Space" inside their runtime version name should be treated as just space so that you can select "Java SE".

**Environment summary**
It occurs on both CloudShell or local Azure CLI, so it looks no matter what OS you use.
My Azure CLI version is "azure-cli": "2.11.0".

**Additional context**
N/A

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
Able to reproduce the reported issue. Will look in to it further.

**Comment by panchagnula** [comment]
@calvinsID this is due to the change we allow space to be a delimiter for runtime language & version. Can you take a look. Thanks!
