### ISSUE TITLE
Creating new Infrastructure Encrypted Storage Account creates following Error.

### ISSUE THREAD

**Issue by Herbaltea-GG** [Azure/azure-cli#16064]
When creating a new _infra. encrypted storage account_ the account creates successfully but throws the following error.  Full disclosure, I'm new to Azure so I have no idea what it means but I wanted to report the error 😅

## Describe the bug

**Command Name**
`az storage account create`

**Errors:**
```
'Response' object has no attribute 'status'
Traceback (most recent call last):
azure/cli/core/adal_authentication.py, ln 103, in set_token
    super(MSIAuthenticationWrapper, self).set_token()
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
...

azure/cli/core/adal_authentication.py, ln 114, in set_token
    .format(err.response.status, err.response.reason))
AttributeError: 'Response' object has no attribute 'status'
```

## To Reproduce:
Run the following command after registering for Infra. Encryption (I did confirm it changed from 'Registering' to 'Registered')
- `az storage account create --name {} --resource-group {} --location canadaeast --sku Standard_RAGRS --kind StorageV2 --require-infrastructure-encryption`

## Expected Behavior
- Create Infra. Encryption storage account and provide success message

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *

Extensions:
ai-examples 0.2.4

```

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @Herbaltea-GG, could you add `--debug` in your command and share the debug info with us?
I have tried in cloud shell and it works as expected. Could you try again and report to us if there is error occured?

**Comment by Herbaltea-GG** [comment]
Hi @Juliehzl, I was able to try this again a few times since reporting this issue and haven't encountered it since. I can still try to make it again, but it may have just been a one-off hiccup?

**Comment by yonzhan** [comment]
Hi @Herbaltea-GG, do you mind we close this issue for now and create a new issue if it happens again?

**Comment by Herbaltea-GG** [comment]
That sounds good to me!
