### ISSUE TITLE
Azure container registry charging unfairly

### ISSUE THREAD

**Issue by techfreakworm** [Azure/azure-cli#16060]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I have a basic SKU plan in Azure container registry. Having 4 images, the total size on local is 5.7 GB. But on ACR portal, it shows 11.1 GB used. I only have one tag per image.

On Local machine:
![image](https://user-images.githubusercontent.com/16111115/100348376-d66adb00-300c-11eb-872c-dd06eb627416.png)

On ACR portal:
![image](https://user-images.githubusercontent.com/16111115/100347687-c1da1300-300b-11eb-9481-c95727b61b67.png)

**To Reproduce**

**Expected behavior**
ACR portal must also show 5.7 GB instead of 11.1 GB

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
acr

**Comment by yonzhan** [comment]
Was this issue related to Azure CLI?

**Comment by yugangw-msft** [comment]
@techfreakworm, thanks for the feedbacks. You can submit a support ticket since this is not Azure CLI related. 
Since we are at it, if you run `az acr repository show-manifests`, are you seeing extra manifests? Also did you purge any images recently, if yes how did you do it?

**Comment by techfreakworm** [comment]
@yugangw-msft Yes, I am indeed seeing extra manifests. I purged 2 images (not shown in the screenshot) from the UI itself. Just delete the image (repository) using delete option.

**Comment by toddysm** [comment]
@techfreakworm Is this still an issue or can we close it? As @yugangw-msft mentioned - this is not a CLI issue. If you experience it again, please submit a support request.

**Comment by yugangw-msft** [comment]
Closing per context above
