### ISSUE TITLE
Unable to create a Cosmos DB account using Azure Cloud Shell command

### ISSUE THREAD

**Issue by jfsom** [Azure/azure-cli#16067]
## Describe the bug
Unable to create a Cosmos DB account using Azure Cloud Shell command
**Command Name**
``
Unable to create a Cosmos DB account using Azure Cloud Shell command
**Errors:**
<img width="958" alt="Cosmodbcreationissue" src="https://user-images.githubusercontent.com/26001084/100401760-672ece80-3080-11eb-8d67-b542868a586e.PNG">

## To Reproduce:
Steps to reproduce the behavior. 

*******************************************
By Running the below mentioned commend in the cloud shell:
export NAME=cosmos$RANDOM
az cosmosdb create \
    --name $NAME \
    --kind GlobalDocumentDB \
    --resource-group storagerg
*****************************************************

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *

Extensions:
ai-examples 0.2.4

```

**Comment by yonzhan** [comment]
cosmosdb

**Comment by MehaKaushik** [comment]
Two comments here:
1. Location is a nonoptional field which needs to be present. 
2. Please refer these docs https://docs.microsoft.com/en-us/azure/cosmos-db/scripts/cli/sql/create?toc=/cli/azure/toc.json

Let me know if you still face issues.

**Comment by MehaKaushik** [comment]
Hey @jfsom were you able to resolve your issue?

**Comment by jfsom** [comment]
Yes @MehaKaushik Thanks
