### ISSUE TITLE
WebApp: Azure error

### ISSUE THREAD

**Issue by Kallebysantos2k** [Azure/azure-cli#16076]
## Describe the bug

**Command Name**
`az appservice plan create`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan create --name {} -g {} --sku {} --is-linux`

## Environment Summary
```
Linux-5.4.0-54-generic-x86_64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
appservice

**Comment by Kotasudhakarreddy** [comment]
@kallebysantos - I am unable to repro the issue in version 2.15.0. could you try in the latest version or please share us the debug log for the same.

**Comment by panchagnula** [comment]
@yonzhan this error seems to be due to incomplete install of azure-cli see the error is about missing packages. Thanks!

**Comment by yonzhan** [comment]
@yungezz @fengzhou-msft to help with.

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
