### ISSUE TITLE
public blob gives error

### ISSUE THREAD

**Issue by tooptoop4** [Azure/azure-cli#16079]
https://azuremlexamples.blob.core.windows.net/datasets/iris.csv is a public dataset (no auth required)

./az storage blob list --account-name azuremlexamples --container-name datasets

give below error:

There are no credentials provided in your command and environment, we will query for the account key inside your storage account. 
Please provide --connection-string, --account-key or --sas-token as credentials, or use `--auth-mode login` if you have required RBAC roles in your command. For more information about RBAC roles in storage, visit https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-cli. 
Setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information.
Please run 'az login' to setup account.

**Comment by yonzhan** [comment]
storage
