### ISSUE TITLE
Make DedicatedHostGroup.properties.supportAutomaticPlacement default to false

### ISSUE THREAD

**Issue by dochung4** [Azure/azure-cli#16077]
**Resource Provider**

Microsoft.Compute

**Description of Feature or Work Requested**

 The initial plan was to default DedicatedHostGroup.properties.supportAutomaticPlacement to true, but recently we have agreed to default the value to false as we GA. The change to default to false has already been made on the service side.

**Minimum API Version Required**

2020-06-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/11697

**Target Date**

The feature is expected to GA on December 10. While having a wrong description is not the biggest issue, it would be good to have this change reflected in the next release.

**Comment by yungezz** [comment]
hi @qwordy could you pls take care of the change? thanks

**Comment by qwordy** [comment]
OK

**Comment by dochung4** [comment]
> OK

@qwordy , can you please review?

**Comment by qwordy** [comment]
The change will be released on 12/29/2020. Sorry it is a bit late than your GA date.

**Comment by dochung4** [comment]
> The change will be released on 12/29/2020. Sorry it is a bit late than your GA date.

Thank you Feiyue. This is only for updating the description, so a slight delay should be fine. Can you please approve the PR and merge it, if the change looks fine?

**Comment by qwordy** [comment]
OK.

A review comment:
> this will be a behavior breaking change to users, although no CLI interface breaking. What's service side communication plan?

**Comment by dochung4** [comment]
> OK.
> 
> A review comment:
> 
> > this will be a behavior breaking change to users, although no CLI interface breaking. What's service side communication plan?

This feature has been in preview with limited subscriptions, so the impact of this change should be minimal. Also, there will be a blog post about this as we GA.
