### ISSUE TITLE
Install Ansible on the virtual machine

### ISSUE THREAD

**Issue by darhasubrahmanyam** [Azure/azure-cli#16075]
## Describe the bug

**Command Name**
`az vm extension set`

**Errors:**
```
'Response' object has no attribute 'status'
Traceback (most recent call last):
azure/cli/core/adal_authentication.py, ln 103, in set_token
    super(MSIAuthenticationWrapper, self).set_token()
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
...

azure/cli/core/adal_authentication.py, ln 114, in set_token
    .format(err.response.status, err.response.reason))
AttributeError: 'Response' object has no attribute 'status'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm extension set --resource-group {} --vm-name {} --name {} --publisher {} --version {} --settings {} --protected-settings {}`

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *

Extensions:
ai-examples 0.2.4

```

**Comment by yungezz** [comment]
hi @qwordy could you pls  help to have a look? thanks

**Comment by qwordy** [comment]
An error in core ADAL code. @darhasubrahmanyam Can you help add `--debug` and paste the output here? Thanks.
@houk-ms @jiasli for awareness.

**Comment by jiasli** [comment]
This issue has been fixed by #15776. Please update to the latest version and see if the error can be shown correctly. @evelyn-ys

**Comment by evelyn-ys** [comment]
Hi @darhasubrahmanyam, this occurs when authentication encounters a `HTTPError`. After updating to the latest version, you may see the error message from auth service.
Could you kindly try `--debug` and paste the output here? We will work with service team to fix this if there do exist some problem.

**Comment by qwordy** [comment]
@darhasubrahmanyam Can you try what jiasli said?

**Comment by yungezz** [comment]
hi @darhasubrahmanyam close the issue for now, feel free to create new one if any other error met.
