### ISSUE TITLE
Onboard Resource Provider as a Service Commands

### ISSUE THREAD

**Issue by wwendyc** [Azure/azure-cli#16088]
**Resource Provider**

Resource Provider as a Service (Microsoft.ProviderHub)

**Description of Feature or Work Requested**

Support Azure CLI commands for select APIs such as Resource Provider Registration and Resource Type Registration. https://armwiki.azurewebsites.net/rpaas/onboardprod.html

**Minimum API Version Required**

2020-11-20

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/providerhub/resource-manager/Microsoft.ProviderHub/stable/2020-11-20/providerhub.json

**Target Date**

Dec 2020

**Comment by yungezz** [comment]
hi @wwendyc will sync with in email.

**Comment by fengzhou-msft** [comment]
The `providerhub` extension is released.
