### ISSUE TITLE
ExpressRoute AZCLI Function Appears Incorrectly Named 

### ISSUE THREAD

**Issue by da5is** [Azure/azure-cli#16089]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

ExpressRoute does not have a space in the name, however the AZCLI puts a dash between the two words "Express" and "Route".  The proper name is "ExpressRoute" as listed in the service documentation here:  https://azure.microsoft.com/en-us/services/expressroute/.  Per the AZCLI documentation for ExpressRoute here: https://docs.microsoft.com/en-us/azure/expressroute/howto-circuit-cli#get-the-list-of-supported-providers-locations-and-bandwidths - a dash is required.

**To Reproduce**

- Attempt to use a command such as `az network expressroute` and realize that there needs to be a dash there for some reason.

**Expected behavior**

- `az network expressroute` should be available for azcli - this improves discoverability and aligns with the technical name and branding of ExpressRoute.  Since it's currently express-route - that should be maintained for backwards compatiblity.

**Environment summary**

All environments.

**Additional context**

**Comment by yonzhan** [comment]
network

**Comment by haroldrandom** [comment]
It's a style of Azure CLI. CamelCase would turn into a dash to connect two lowercase-letter leading words
