### ISSUE TITLE
syntax error for basic use of "az group create"

### ISSUE THREAD

**Issue by genegc** [Azure/azure-cli#16085]
## Describe the bug

**Command Name**
`az group create`

**Errors:**
```
invalid syntax (custom.py, line 838)
Traceback (most recent call last):
python3.5/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 553, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 478, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
<frozen importlib._bootstrap_external>, ln 727, in source_to_code
<frozen importlib._bootstrap>, ln 222, in _call_with_frames_removed
cli/command_modules/resource/custom.py, ln 838
    err_messages = [f'{preflight_error.code} - {preflight_error.message}']
                                                                        ^
SyntaxError: invalid syntax
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group create --location {} --name {}`

## Expected Behavior
It should create the group

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-Ubuntu-16.04-xenial (Cloud Shell)
Python 3.5.2
Installer: PIP

azure-cli 2.15.1

Extensions:
interactive 0.4.4

```

**Comment by genegc** [comment]
I've verified that the same command works from my laptop. Here are the env details for my laptop:

Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.15.1

**Comment by genegc** [comment]
I've also found that the same command works from another azure account. Here are the env details for that account:

Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *

Extensions:
ai-examples 0.2.4

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness
