### ISSUE TITLE
webapp: --name does not defaulting

### ISSUE THREAD

**Issue by dev-playbook** [Azure/azure-cli#16087]
This should work if the default for `web` is configured

```shell
az webapp config ssl create --hostname $fqdn --verbose
```
But i get this error: 
```
RequiredArgumentMissingError: the following arguments are required: --name/-n
```
So I am forced to use this 
```shell
az webapp config ssl create --hostname $fqdn --name $appname --verbose
```

Page does say on Required Parameters,
```
--name -n
Name of the web app. You can configure the default using az configure --defaults web=<name>.
```
az cli version info:
```
azure-cli                         2.15.1
core                              2.15.1
telemetry                          1.0.6
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3f984d-0d48-e075-7e2f-2da5667b15cf
* Version Independent ID: 98e06d47-0ed4-4d8e-ccf5-d3a78e510539
* Content: [az webapp config ssl](https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/ssl.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config/ssl.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by btardif** [comment]
@panchagnula --name should be marked as a required parameter
