### ISSUE TITLE
Azure SQL VMs - How do I configure the storage via Az CLI? 

### ISSUE THREAD

**Issue by JohnDelisle** [Azure/azure-cli#16096]
I'm unable to find anything in the Az CLI documentation regarding the storage configuration of Azure SQL VMs created via `az sql vm create`.  

I'm specifically looking for how one should add more disks.  The functionality seems to be in ARM (I can export a template in the portal that creates an Azure SQL VM with disks configured as I require), however I cannot find it in the Az CLI documentation.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a502befd-c5a3-8aa4-3f03-a65133e73583
* Version Independent ID: 33f1db2e-73f1-e786-c1d1-6a9bb570de7b
* Content: [az sql vm](https://docs.microsoft.com/en-us/cli/azure/sql/vm?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/sql/vm.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/sql/vm.yml)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
sql

**Comment by JohnDelisle** [comment]
Hello, just looking for an update please.  

Is this possible via "az sql vm create"?  I see all the other functionality like SQL backups, enabling R Services, and so on are present... but disk layout is missing.

Am I just looking in the wrong place?

**Comment by bluefooted** [comment]
Unfortunately disk configuration is not currently supported through az cli.
