### ISSUE TITLE
Need a central place to record the Azure cli api-version change 

### ISSUE THREAD

**Issue by t-bzhan** [Azure/azure-cli#16094]
**Is your feature request related to a problem? Please describe.**

My problem is very similar to: https://github.com/Azure/azure-cli/issues/9834, https://github.com/Azure/azure-cli/issues/12881, https://github.com/Azure/azure-cli/issues/12895, https://github.com/Azure/azure-cli/issues/13047

The azure cli complains that:
```
cli.azure.cli.core.util : NoRegisteredProviderFound - No registered resource provider found for location 'chinanorth' and API version '2019-06-15-preview' for type 'profiles/endpoints'. The supported api-versions are '2015-06-01, 2016-04-02, 2016-10-02, 2017-04-02, 2017-10-12, 2018-04-02, 2019-04-15'. The supported locations are 'chinanorth, chinanorth2, chinaeast, chinaeast2'.
NoRegisteredProviderFound - No registered resource provider found for location 'chinanorth' and API version '2019-06-15-preview' for type 'profiles/endpoints'. The supported api-versions are '2015-06-01, 2016-04-02, 2016-10-02, 2017-04-02, 2017-10-12, 2018-04-02, 2019-04-15'. The supported locations are 'chinanorth, chinanorth2, chinaeast, chinaeast2'.
```
It looks like Azure Cli use an api-version which is not supported by the backend resource provider. And the mitigation is often to downgrade the azure cli version. But we do not have a central place to record the api-version change and it is not easy to know which cli version should we use. 

**Describe the solution you'd like**

The ideal solution is that we could specify the api-version in the command. 

**Describe alternatives you've considered**

If the above solution is not acceptable, it would be great if we could have a central place to keep the api-version change history to help customer to choose the correct version to use.

**Additional context**

**Comment by yonzhan** [comment]
Core

**Comment by jiasli** [comment]
We do have a centralized location to define `api-version`s for each resource provider:

https://github.com/Azure/azure-cli/blob/0952571c2214693a79850f67d33b3fa6ab0354c0/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L135-L139

I searched for `2019-06-15-preview` in this file, but it is not defined, which means AKS hasn't onboard Azure CLI's multi-API mechanism yet. 

Also, all 4 public clouds 

- AzureCloud
- AzureChinaCloud
- AzureUSGovernment
- AzureGermanCloud

use the same `latest` profile.

We need to determine whether we need another mechanism to use different cloud profiles for different clouds.

At the same time, @jluk, please help take a look and see if AKS can utilize the multi-API mechanism to pin the API version until the service is available in all 4 public Azure clouds.

**Comment by t-bzhan** [comment]
Hi @jiasli , this issue is for CDN, the resource type is "profiles/endpoints" in my case. But I believe  other resources might has the same issue in China Cloud.
