### ISSUE TITLE
webapp: ssl bind fails due to \r in thumbprint

### ISSUE THREAD

**Issue by dev-playbook** [Azure/azure-cli#16090]
When I did this....

```shell
wwwSslThumbprint=$(az webapp config ssl list --query "[?name=='www.$customRootDomain'].thumbprint" --output tsv)

echo $wwwSslThumbprint

az webapp config ssl bind --certificate-thumbprint $wwwSslThumbprint --ssl-type SNI --verbose
```

I get this error. `'not found. for thumbprint'{thumbprint}`

But if when I did this...

```shell
wwwSslThumbprint=$(az webapp config ssl list --query "[?name=='www.$customRootDomain'].thumbprint" --output tsv | sed "s/\r//g")

echo $wwwSslThumbprint

az webapp config ssl bind --certificate-thumbprint $wwwSslThumbprint --ssl-type SNI --verbose
```

**It works!**

Note that I've had to **remove the carriage return in the extracted thumbprint** by using `sed "s/\r//g"`.

az version info
```json
{
  "azure-cli": "2.15.1",
  "azure-cli-core": "2.15.1",    
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```
Microsoft Windows [Version 10.0.18363.1198]

Ubuntu wsl version: 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3f984d-0d48-e075-7e2f-2da5667b15cf
* Version Independent ID: 98e06d47-0ed4-4d8e-ccf5-d3a78e510539
* Content: [az webapp config ssl](https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/ssl.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config/ssl.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by btardif** [comment]
@panchagnula looks like we need to trim trailing carriage return on the thumbprint

**Comment by jiasli** [comment]
Please see the explanation at https://github.com/Azure/azure-cli/issues/13573#issuecomment-888791313.
