### ISSUE TITLE
Article incorrect

### ISSUE THREAD

**Issue by pvanroos** [Azure/azure-cli#16106]
Required parameters for create is not correct.  When I run my script with minimum parameters, it returns:

ValidationError: Parameter 'MetricAlertResource.description' can not be None.

Is this page updated to latest?  

When I added description, it now returns:

The following metric name(s) were not found: Percentage CPU. Please note that for custom metrics, the relevant metric namespace must be specified. Activity ID: aa4a6469-da70-4410-80bd-1f245b836263.. [Code: "BadRequest"]

Here is my script command text:

az monitor metrics alert create -g "[redacted]" -n "Test" \
        --scopes "[redacted]" \
        --action "[redacted]" \
        --description "Paul is testing the az cli script creation" \
        --condition "avg Percentage CPU > 90"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d97968df-72c9-e50c-d5b1-54562c1bdef7
* Version Independent ID: 0cde4f15-6464-3106-b787-3ee37c7de0ee
* Content: [az monitor metrics alert](https://docs.microsoft.com/en-us/cli/azure/monitor/metrics/alert?view=azure-cli-latest#az_monitor_metrics_alert_create)
* Content Source: [latest/docs-ref-autogen/monitor/metrics/alert.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/monitor/metrics/alert.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
monitor

**Comment by pvanroos** [comment]
So here's the thing.  The condition must be constructed using a string that is based on the available metrics for that target resource.  If the docs say this, then I apologize for raising this issue.   The provided examples don't work but I was able to figure out the logic.
