### ISSUE TITLE
WebApp:Need description of the  "customID" parameter for the "az webapp config storage-account" commands

### ISSUE THREAD

**Issue by billspat** [Azure/azure-cli#16105]
[Enter feedback here]
The documentation for CLI "az webapp config storage-account" commands does not describe, or link to a description, of the  "customID" parameter.    The tutorial/overview page https://docs.microsoft.com/en-us/azure/app-service/configure-connect-to-azure-storage?pivots=container-linux for this command does not describe it either.   

What is "customID" and what is it used for in the context of this feature (mounting storage onto app service containers)?   thank you!  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4892bb1c-5cb4-91fa-325b-f5180cd05c3a
* Version Independent ID: 8c9a9a0e-5b36-4039-72c5-b28fd0bb9fd4
* Content: [az webapp config storage-account](https://docs.microsoft.com/en-us/cli/azure/webapp/config/storage-account?view=azure-cli-latest#az_webapp_config_storage_account_delete)
* Content Source: [latest/docs-ref-autogen/webapp/config/storage-account.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config/storage-account.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Calvin-Yuhui-Liu** [comment]
Can't get the point why M$ wants to hide such information? Come on...

**Comment by btardif** [comment]
@seligj95 please follow up with Gaurav on this to get a description.

**Comment by Calvin-Yuhui-Liu** [comment]
A quick update. Appreciate help from Azure support team this parameter is just a text string, a name. In my case I tried to attach a file share **to a Windows web app**. And my issue was actually about another parameter --mount-path (which is also not clear either). After trying it for several times, both side agreed to give up as it's a preview feature for the moment.

This is the link we were following: https://docs.microsoft.com/en-us/cli/azure/webapp/config/storage-account?view=azure-cli-latest#az_webapp_config_storage_account_add.

**Comment by seligj95** [comment]
•	Custom id is name of the share configured within the web app  
•	Mount path is the path which the web app uses to read-write data ex: /share1 or /share2
•	Share name is name of the file share as given  in the storage account

Example:

az webapp config storage-account add -g <<resource group name>> -n <<web app name>> --custom-id <<name of BYOS share used by the web app>>  --storage-type AzureFiles --account-name <<storage account name>> --share-name <<name of file share in the storage account >> --access-key <<storage account access key>>  --mount-path <<mount path used by the web app to read\write content>>

We will be updating the docs to reflect this. Thank you for the feedback.

**Comment by Calvin-Yuhui-Liu** [comment]
Hi Jordan,

Thanks for the information. It's really helpful.

BTW, not sure if this "custom-id" equals "a name" pattern applies anywhere else but if I may, I'd suggest changing "custom-id" to "mount-name" as it would be more straightforward and self-descriptive. Thanks.

Best regards,
Calvin Liu

________________________________
