### ISSUE TITLE
`az storage blob list`

### ISSUE THREAD

**Issue by shahmanthan1209** [Azure/azure-cli#16100]
## Describe the bug

**Command Name**
`az storage blob list`

**Errors:**
```
Connection string missing required connection details.
Traceback (most recent call last):
blob/v2019_12_12/_shared/base_client.py, ln 385, in parse_connection_str
    conn_settings["AccountName"], service, conn_settings.get("EndpointSuffix", SERVICE_HOST_BASE)
KeyError: 'AccountName'

...

blob/v2019_12_12/_shared/base_client.py, ln 388, in parse_connection_str
    raise ValueError("Connection string missing required connection details.")
ValueError: Connection string missing required connection details.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob list --account-name {} --container-name {} --connection-string {}`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.6
Installer: HOMEBREW

azure-cli 2.14.0 *

```

**Comment by yonzhan** [comment]
storage

**Comment by nikonov91-dev** [comment]
I've solved that issue with the same environment and VS-Code. The problem that we havent set:
-  correct **Connection Key string** 
- nor **shell (environment) variable** .

![connection key location image](https://user-images.githubusercontent.com/31586394/103098075-2cce3800-4612-11eb-8d31-0dd19f9f83d9.png)

To set correctly environment variable we need to use debugger in VSCode and add it in **launch.json**

![bash environment variable image](https://user-images.githubusercontent.com/31586394/103098077-2dff6500-4612-11eb-8dd9-239c61e18931.png)

follow this solution [runtime variable question](https://stackoverflow.com/a/48609350/9277453)

My launch.json to run an opened file
```{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "env": {
                "AZURE_STORAGE_CONNECTION_STRING": "DefaultEndpointsProtocol=https;AccountName=mediastorealexnikonov;AccountKey=pSWYOvxWVJINthORcmX2Yp9hPiU3TarugY9Ipd2f/+4r08pbkTiWTIHVA1SWOYT86+0qMwlesdeBGwar/0ZOvg==;EndpointSuffix=core.windows.net"
            }
        }
    ]
}
```

**Comment by yonzhan** [comment]
issue resolved by above solution
