### ISSUE TITLE
unable to use: az synapse notebook create

### ISSUE THREAD

**Issue by genegc** [Azure/azure-cli#16104]
## Describe the bug
I'm unable to get this az cli command to work in any env.

**Command Name**
`az synapse notebook create`

**Errors:**
```
BadRequestError: Operation returned an invalid status 'Bad Request'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az synapse notebook create --workspace-name {} --name {} --file {} --debug`

## Expected Behavior
It should create the notebook in the specified synapse workspace

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.15.1

```
## Additional Context
I've also found it to fail when attempted in azure cloudshell.
Here are the env details:
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *

Extensions:
ai-examples 0.2.4

**Comment by yonzhan** [comment]
synapse

**Comment by idear1203** [comment]
BadRequest indicates there is something wrong in the request payload. Please check your request. or provide content of the definition file.

**Comment by genegc** [comment]
Here is the result of the command:
[log.txt](https://github.com/Azure/azure-cli/files/5636242/log.txt)

Here is the notebook I'm attempting to import (though I have tried with several different notebooks):
(note: this attachment should end in .ipynb - it was only changed .txt to be able to upload to this comment)
[Notebook1.txt](https://github.com/Azure/azure-cli/files/5636223/Notebook1.txt)

Could you provide details of an example that works? I have tried numerous different approaches and haven't been able to get any notebooks created or imported from az cli.

**Comment by perber** [comment]
Hey, 
If someone is getting the error. It helped to upgrade az cli to the latest version.
Version 2.25.0 it worked.

**Comment by genegc** [comment]
Thank you. It's working for me now.
I used the following command:
`az synapse notebook create --workspace-name syn-mytest1 --name testnotebook --file @./mytest.ipynb --debug`

But I also realized that this only works if you don't have your workspace configured to use a git repo (ie, you have to be in "live mode" to see the notebook that gets created).

If you have your workspace configured to use a git repo, you can just commit your notebook json into the "notebook" folder in your repo and it will show up in your workspace after you do a refresh.
