### ISSUE TITLE
WebApp:[webapp ssh] - does not work on WSL

### ISSUE THREAD

**Issue by mloskot** [Azure/azure-cli#16119]
## Describe the bug

**Command Name**
`az webapp ssh`

**Errors:**
```
webapp ssh is only supported on linux and mac
```

Here is the Ubuntu 20.04 (WSL) using the [Azure CLI installed on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt):

![image](https://user-images.githubusercontent.com/80741/100863889-83be7280-3495-11eb-9f22-44ddaa3c2d7a.png)

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp ssh --resource-group {} --name {}`

## Environment Summary

```
Ubuntu 20.04 (WSL on Windows-10-10.0.19041-SP0)
Python 3.6.8
Installer: `apt` package azure-cli 2.15.0 *
```

## Additional Context

These are issues reporting the `webapp ssh` does not work on Windows:

- https://github.com/Azure/azure-cli/issues/15729
- https://github.com/Azure/azure-cli/issues/15072
- https://github.com/Azure/azure-cli/issues/12940
- https://github.com/Azure/azure-cli/issues/12844

but apparently it does not work on Linux either, so there must be something broken in general.

**Comment by yonzhan** [comment]
webapp

**Comment by btardif** [comment]
This is a valid bug, looks like our detection logic is buggy, we need to account for WSL scenarios and ideally make them work.

**Comment by RobinZergiebel** [comment]
Is this actually solved? I still get the same error using WSL on Windows.

**Comment by calvinsID** [comment]
@RobinZergiebel what version of CLI are you using?

**Comment by RobinZergiebel** [comment]
> @RobinZergiebel what version of CLI are you using?

@calvinsID My mistake, I was using an outdated version. Works perfectly fine.
