### ISSUE TITLE
WebApp:Support az webapp ssh for windows clients

### ISSUE THREAD

**Issue by btardif** [Azure/azure-cli#16125]
We currently don't support SSH from a windows client:

![image](https://user-images.githubusercontent.com/4119816/100918772-c54b1f80-348d-11eb-9132-af9c02137d00.png)

As an initial mitigation, we should open a browser to the web-ssh console that is part of every Linux app:

![image](https://user-images.githubusercontent.com/4119816/100919045-2115a880-348e-11eb-8e61-caf0e5dcc346.png)

This is accessible under: https://<site-name>.scm.azurewebsites.net/webssh/host

**Comment by yonzhan** [comment]
webapp
