### ISSUE TITLE
[ACS] Orchestrator-agnostic browse command fails for k8s cluster

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1612]
When I try running `az acs browse` on a newly provisioned k8s cluster, I get the following error: `Unsupported orchestrator type ContainerServiceOchestratorTypes.kubernetes for browse`. Running `az acs kubernetes browse`, however, works perfectly, so it seems like there's an issue (at least for me) with the general `browse` command and k8s clusters.

**Comment by PeterJausovec** [comment]
Same error occurs when running ```az acs browse``` against DCOS.

**Comment by brendandburns** [comment]
Ugh, I'll try to reproduce...

**Comment by brendandburns** [comment]
This is fixed in https://github.com/Azure/azure-cli/issues/1612
