### ISSUE TITLE
Feature request for supporting update Virtual Router and get virtual router peer learned routes and advertised routes

### ISSUE THREAD

**Issue by naveenchekuri** [Azure/azure-cli#16139]
**Resource Provider**

Microsoft.Network

**Description of Feature or Work Requested**
AZ CLI currently support create and delete virtual router and virtual router peer. We need to add support for following

1. Support update virtual router to add boolean flag AllowBranchToBranchTraffic. Example powershell is below

"Update-AzVirtualRouter -ResourceGroupName VirtualRouterRG -RouterName virtualrouterhub1 -AllowBranchToBranchTraffic"

When this flag as true by customer, please set allowBranchToBranchTraffic flag under virtualhub. By default this flag is false

2. Support virtualrouterpeer getlearnedroutes and virtualrouterpeer getadvertisedroutes for az cli. Powershell example below

"Get-AzVirtualRouterPeerAdvertisedRoute -ResourceGroupName VirtualRouterRG -VirtualRouterName virtualrouterhub1  -PeerName peer1"

"Get-AzVirtualRouterPeerLearnedRoute -ResourceGroupName VirtualRouterRG -VirtualRouterName virtualrouterhub1  -PeerName peer1"

Minimum API Version Required**
2020-06-01

**Swagger Link**
AllowBranchToBranchTraffic flag - https://github.com/Azure/azure-rest-api-specs/pull/11015
Advertised and LearnedRoutes - https://github.com/Azure/azure-rest-api-specs/pull/10434

**Target Date**
12/25/2020

**Comment by yonzhan** [comment]
Network

**Comment by kairu-ms** [comment]
Hi @naveenchekuri. 'az network vrouter' has been renamed by 'az network virtualhub-router', so those features will be added in ' az network virtualhub-router'. Is that make sense?

**Comment by naveenchekuri** [comment]
Yes. Thank you. please add these features under ' az network virtualhub-router'

**Comment by naveenchekuri** [comment]
@kairu-ms routeserver is the final name change we agreed upon with marketing. please add these features under "az network routeserver"

**Comment by kairu-ms** [comment]
> @kairu-ms routeserver is the final name change we agreed upon with marketing. please add these features under "az network routeserver"

Done
