### ISSUE TITLE
Setting BGP ASN at the gateway level fails

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#1613]
Following are the steps to enable BGP for VNet-VNet and they have to be executed in the following order
1. Set the ASN at the Gateway level so that it is different from the other VNet's GW
2. Enable BGP explicitly at the connection level

When i run the following command to set the BGP ASN i get an error
aanandr@AANANDR-WORK:/mnt/c/Windows/System32$ az network vpn-gateway update -n VNet1GW -g VV1 --set bgpSettings.asn=7000
Resource /subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV1/providers/Microsoft.Network/virtualNetworks/NONE referenced by resource /subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV1/providers/Microsoft.Network/virtualNetworkGateways/VNet1GW was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.

But the GW is already associated with the right VNet
aanandr@AANANDR-WORK:/mnt/c/Windows/System32$ az network vnet list -g VV1
[
  {
    "addressSpace": {
      "addressPrefixes": [
        "192.168.0.0/16"
      ]
    },
    "dhcpOptions": null,
    "etag": "W/\"dacfc6f3-46cd-48e9-b8ed-8ae15c672fcc\"",
    "id": "/subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV1/providers/Microsoft.Network/virtualNetworks/VNet1",
    "location": "westus",
    "name": "VNet1",
    "provisioningState": "Succeeded",
    "resourceGroup": "VV1",
    "resourceGuid": "b713371f-4112-40df-ac76-7d155c365a61",
    "subnets": [
      {
        "addressPrefix": "192.168.1.0/24",
        "etag": "W/\"dacfc6f3-46cd-48e9-b8ed-8ae15c672fcc\"",
        "id": "/subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV1/providers/Microsoft.Network/virtualNetworks/VNet1/subnets/Sub1",
        "ipConfigurations": null,
        "name": "Sub1",
        "networkSecurityGroup": null,
        "provisioningState": "Succeeded",
        "resourceGroup": "VV1",
        "resourceNavigationLinks": null,
        "routeTable": null
      },
      {
        "addressPrefix": "192.168.255.0/24",
        "etag": "W/\"dacfc6f3-46cd-48e9-b8ed-8ae15c672fcc\"",
        "id": "/subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV1/providers/Microsoft.Network/virtualNetworks/VNet1/subnets/GatewaySubnet",
        "ipConfigurations": [
          {
            "etag": null,
            "id": "/subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV1/providers/Microsoft.Network/virtualNetworkGateways/VNet1GW/ipConfigurations/vnetGatewayConfig",
            "name": null,
            "privateIpAddress": null,
            "privateIpAllocationMethod": null,
            "provisioningState": null,
            "publicIpAddress": null,
            "resourceGroup": "VV1",
            "subnet": null
          }
        ],
        "name": "GatewaySubnet",
        "networkSecurityGroup": null,
        "provisioningState": "Succeeded",
        "resourceGroup": "VV1",
        "resourceNavigationLinks": null,
        "routeTable": null
      }
    ],
    "tags": null,
    "type": "Microsoft.Network/virtualNetworks",
    "virtualNetworkPeerings": null
  }
]

**Comment by aanandr** [comment]
I tried the update command to change the SKU and VPN type of the Gateway and got the same error

**Comment by tjprescott** [comment]
> az network **vpn-gateway** update ...

From your command, it seems you are using an out of date version of the network package. Numerous fixes have been applied in PR #1539.

**Comment by tjprescott** [comment]
I confirmed that this works correctly on the latest master.
