### ISSUE TITLE
Az namespace exists returns inconsistent error message

### ISSUE THREAD

**Issue by ashinzekene** [Azure/azure-cli#16137]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I'm trying to verify if a namespace is currently in use. I think it is still available, though I can't create a resource with that name.
The error message is different

![image](https://user-images.githubusercontent.com/20991583/101026143-d2900900-3576-11eb-9299-ba2027c161ba.png)

**To Reproduce**
```
az servicebus namespace exists --name usl-osupd-servicebus-fus-test
az servicebus namespace exists --name service-bus-namespace // or any other sb namespace that exists
```
**Expected behavior**
Expected result for both cases
```json
{
  "message": "The specified name is not available. For more information visit https://aka.ms/eventhubsarmexceptions.",
  "nameAvailable": false,
  "reason": "NameInUse"
}
```

 Also, is there a way to find out which subscription has used a resource name?

**Comment by Saglodha** [comment]
@ashinzekene - Can you confirm if the same issue is happening in latest CLI module? I tried with CLI version 2.34.1 and am unable to reproduce the behavior.

**Comment by ashinzekene** [comment]
We can close this
