### ISSUE TITLE
Explenations differ a bit

### ISSUE THREAD

**Issue by B4Art** [Azure/azure-cli#16136]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

To links same command but different

**To Reproduce**

https://docs.microsoft.com/en-us/cli/azure/pipelines/build/tag?view=azure-cli-latest
https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines/build/tag?view=azure-cli-latest
--subscription is missing in the first link AND present in the second one?

**Expected behavior**

**Environment summary**

**Additional context**

Also reported via the other link #2747

**Comment by yonzhan** [comment]
devops

**Comment by RakeshMohanMSFT** [comment]
Fixed.
