### ISSUE TITLE
Application Gateway Mutual Authentication Support

### ISSUE THREAD

**Issue by HemantErappa** [Azure/azure-cli#16144]
**Resource Provider**

Network

**Description of Feature or Work Requested**

Application Gateway Mutual Authentication Support

**Minimum API Version Required**

2020-06-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/9965

**Target Date**

02/01/2021

**Comment by yonzhan** [comment]
Application Gateway

**Comment by yonzhan** [comment]
planned in S182

**Comment by msyyc** [comment]
@HemantErappa It's a little hard to finish the feature in S181. Is it ok to finish it in S182?(about 2021-02-09)
![image](https://user-images.githubusercontent.com/70930885/103602099-2317cf00-4f46-11eb-8764-f144e989e4d3.png)

**Comment by 3quanfeng** [comment]
Hi @msyyc and @yonzhan , is  it affirmative that S183 targets on 2021-02-09?
Could you please help share the estimation for the date of S183 as well? we have some changes needs to be included in S183, and the estimation date will help us determine our public review date, Thanks!

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/milestone/101   Code complete: 02/24/2021 Build to Cloud Shell: 02/26/2021 Official Release: 03/02/2021

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/milestone/100  Code complete: 02/03/2021 Build to Cloud Shell: 02/05/2021 Official Release: 02/09/2021  This feature is targeted for S182, right?

**Comment by yonzhan** [comment]
Yes, S182 is target for 02/09.

**Comment by msyyc** [comment]
@3quanfeng @HemantErappa How to create a valid "data" for test before "application-gateway create"? I do not find any reference docs.
![Uploading image.png…]()

**Comment by 3quanfeng** [comment]
@msyyc , az cli support for mtls is only available after 02/09 as said above
