### ISSUE TITLE
az synapse notebook list fails in cloudshell

### ISSUE THREAD

**Issue by genegc** [Azure/azure-cli#16145]
## Describe the bug
I'm not able to get any of the az synapse notebook commands to work from the cloud shell.
When trying to call az synapse notebook list, I get the following error:
`msrestazure.azure_active_directory : MSI: Failed to retrieve a token from 'http://localhost:50342/oauth2/token' with an error of '400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token'. This could be caused by the MSI extension not yet fully provisioned.`

Here is the debug log...
[log.txt](https://github.com/Azure/azure-cli/files/5640478/log.txt)

**Command Name**
`az synapse notebook list`

**Errors:**
```
'Response' object has no attribute 'status'
Traceback (most recent call last):
azure/cli/core/adal_authentication.py, ln 103, in set_token
    super(MSIAuthenticationWrapper, self).set_token()
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token

...

azure/cli/core/adal_authentication.py, ln 114, in set_token
    .format(err.response.status, err.response.reason))
AttributeError: 'Response' object has no attribute 'status'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az synapse notebook list --workspace-name {} --debug`

## Environment Summary
```
Linux-4.15.0-1100-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *

Extensions:
ai-examples 0.2.4

```

**Comment by yungezz** [comment]
route to appropriate team to have a look

**Comment by idear1203** [comment]
Current the service doesn't support MSI login. Could you please try login with ` az login  --use-device-code`
