### ISSUE TITLE
Documentation for az vm run-command is out of date and incomplete

### ISSUE THREAD

**Issue by Bob-RH** [Azure/azure-cli#16157]
I'm attempting the most basic of using the run-command invocation on a linux VM from powershell and it's failing with needs --command-id.  This isn't documented.

This VM works for run command from the console.  

PS C:\Users\robbro04\.ssh> az vm run-command invoke --resource-group vpn-test --name z110-r-3ess-linux --scripts 'echo $1 $2' --parameters hello world
az vm run-command invoke: error: the following arguments are required: --command-id
usage: az vm run-command invoke [-h] [--verbose] [--debug]
                                [--only-show-errors]
                                [--output {json,jsonc,yaml,yamlc,table,tsv,none}]
                                [--query JMESPATH]
                                [--subscription _SUBSCRIPTION]
                                [--resource-group RESOURCE_GROUP_NAME]
                                [--name NAME] --command-id COMMAND_ID
                                [--scripts SCRIPTS [SCRIPTS ...]]
                                [--parameters PARAMETERS [PARAMETERS ...]]
                                [--ids ID [ID ...]]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f04b196d-7d11-7213-f037-f12b85b19c52
* Version Independent ID: adc05d8e-b13b-134b-5f61-42aaf23666df
* Content: [az vm run-command](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm/run-command.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/vm/run-command.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy, could you pls have a look? thanks

**Comment by qwordy** [comment]
@Bob-RH `--command-id` is a required parameter. Where did you find the help?
```
$ az vm run-command invoke -h

Command
    az vm run-command invoke : Execute a specific run command on a vm.
        `az vm run-command show` returns helpful information on each run-command. Discover Run
        command-id's via `az vmss run-command list`.

Arguments
    --command-id [Required] : The command id.  Values from: az vm run-command list.
    --parameters            : Space-separated parameters in the format of '[name=]value'.
    --scripts               : Space-separated script lines. Use @{file} to load script from a file.

Resource Id Arguments
    --ids                   : One or more resource IDs (space-delimited). It should be a complete
                              resource ID containing all information of 'Resource Id' arguments. You
                              should provide either --ids or other 'Resource Id' arguments.
    --name -n               : The name of the Virtual Machine. You can configure the default using
                              `az configure --defaults vm=<name>`.
    --resource-group -g     : Name of resource group. You can configure the default group using `az
                              configure --defaults group=<name>`.
    --subscription          : Name or ID of subscription. You can configure the default subscription
                              using `az account set -s NAME_OR_ID`.

Global Arguments
    --debug                 : Increase logging verbosity to show all debug logs.
    --help -h               : Show this help message and exit.
    --only-show-errors      : Only show errors, suppressing warnings.
    --output -o             : Output format.  Allowed values: json, jsonc, none, table, tsv, yaml,
                              yamlc.  Default: json.
    --query                 : JMESPath query string. See http://jmespath.org/ for more information
                              and examples.
    --verbose               : Increase logging verbosity. Use --debug for full debug logs.

Examples
    Install nginx on a linux VM.
        az vm run-command invoke -g MyResourceGroup -n MyVm --command-id RunShellScript --scripts
        "sudo apt-get update && sudo apt-get install -y nginx"

    Run shell command on a linux VM with parameters.
        az vm run-command invoke -g MyResourceGroup -n MyVm --command-id RunShellScript --scripts
        'echo $1 $2' --parameters hello world

    Run powershell script on a windows VM with parameters. Script supplied inline. Be wary of
    single-quoting in CMD.exe.
        az vm run-command invoke  --command-id RunPowerShellScript --name win-vm -g my-resource-
        group  \
            --scripts 'param([string]$arg1,[string]$arg2)' \
            'Write-Host This is a sample script with parameters $arg1 and $arg2' \
            --parameters 'arg1=somefoo' 'arg2=somebar'

    Run powershell script on a windows VM with parameters. Script supplied from file.
        # script.ps1
        #   param(
        #       [string]$arg1,
        #       [string]$arg2
        #   )
        #   Write-Host This is a sample script with parameters $arg1 and $arg2

        az vm run-command invoke  --command-id RunPowerShellScript --name win-vm -g my-resource-
        group \
            --scripts @script.ps1 --parameters "arg1=somefoo" "arg2=somebar"
```

**Comment by Bob-RH** [comment]
Hi,

I'm not sure now, but I was looking via search in google for "az vm run-command"

I'm getting this page now:  https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest

I think the problem I ran into is that I didn't have the correct command-id which should have been "RunShellScript" but I was confused and didn't know that related to the functions listed in the UI.
The learn more links for Linux were a  bit  incomprehensible at the time.  I thought

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/run-command
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/run-command

I now know that the command-id can only be RunShellScript or iconfig.

Bob

**Comment by yungezz** [comment]
thanks @Bob-RH , is it ok to close the issue now?

**Comment by Bob-RH** [comment]
Yes, it does.  Thanks!!
