### ISSUE TITLE
Bug to execute az apim

### ISSUE THREAD

**Issue by econezza** [Azure/azure-cli#16155]
## Describe the bug

**Command Name**
`az apim`

**Errors:**
```
az apim: error: the following arguments are required: _subcommand
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6

azure-cli 2.1.0 *

Extensions:
interactive 0.4.3
webapp 0.2.24

```

**Comment by yonzhan** [comment]
apim

**Comment by miaojiang** [comment]
Please update to the latest CLI version and see if the issue persists.
