### ISSUE TITLE
[Compute] Automatic In-Guest Patching for Linux VMs

### ISSUE THREAD

**Issue by rane-rajasi** [Azure/azure-cli#16159]
**Resource Provider**
Compute

**Description of Feature or Work Requested**
Automatic in-guest patching provides customers an easy-to-onboard solution to maintain security compliance for their virtual machines. This feature provides:
1.	Simple onboarding – Enrolling a VM requires configuring one property on the VM model (process detailed below) with no further onboarding actions needed.
2.	Automatic compliance – Most VMs (including dev/test) have compliance requirements for security/critical vulnerabilities and using automatic in-guest patching keeps the virtual machine compliant without additional overhead.
3.	Availability-first patching – Automatic in-guest patching is orchestrated through an availability-first process (detailed below) which ensures maximum uptime for the customer’s application.
 
To onboard a new VM to automatic in-guest patching, the following property settings must be included in the VM model/template:
"linuxConfiguration": {
       "provisionVMAgent": true,
       "patchSettings": {
            "patchMode": "AutomaticByPlatform"
       }
}
 
CLI support is requested to set the above flag on the VM model when creating the VM or modifying it.

**Minimum API Version Required**
2020-12-01

**Swagger Link**
Link for swagger: https://github.com/Azure/azure-rest-api-specs/blob/compute-2020-12/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json

**Target Date**
January public preview

**Comment by yungezz** [comment]
service public date Jan.

**Comment by qwordy** [comment]
@rane-rajasi  I noticed that the swagger change has not been merged to master branch? When will it be merged? Azure CLI can't release this until swagger change is merged to master branch.

**Comment by rane-rajasi** [comment]
@qwordy The swagger release has been delayed for sometime now. Current ETA we have for swagger release is the 1st week of Feb.

**Comment by qwordy** [comment]
In compute 2020-12-01, InGuestPatchMode becomes WindowsVMGuestPatchMode, LinuxVMGuestPatchMode. It is a breaking change.
