### ISSUE TITLE
Output of vpn-connection list command doesnt provide any information, all values are NULL

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#1615]
Created a routebased VPN connection . Here is the output that i got. Most values are NULL which is incorrect.

aanandr@AANANDR-WORK:/mnt/c/Windows/System32$ az network vpn-connection list -g VV1
[
  {
    "authorizationKey": null,
    "connectionStatus": null,
    "connectionType": "IPsec",
    "egressBytesTransferred": 0,
    "enableBgp": false,
    "etag": "W/\"78f93a73-770e-4841-9dd1-8f1eb0ee6b89\"",
    "id": "/subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV1/providers/Microsoft.Network/connections/GWtoLNG",
    "ingressBytesTransferred": 0,
    "localNetworkGateway2": {
      "bgpSettings": null,
      "etag": null,
      "gatewayIpAddress": null,
      "id": "/subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV1/providers/Microsoft.Network/localNetworkGateways/VNet1LNG",
      "localNetworkAddressSpace": null,
      "location": null,
      "name": null,
      "provisioningState": null,
      "resourceGroup": "VV1",
      "resourceGuid": null,
      "tags": null,
      "type": null
    },
    "location": "westus",
    "name": "GWtoLNG",
    "peer": null,
    "provisioningState": "Succeeded",
    "resourceGroup": "VV1",
    "resourceGuid": "5efa8ff9-e5d2-4d57-8ee5-66b011dbacc1",
    "routingWeight": 10,
    "sharedKey": null,
    "tags": null,
    "type": "Microsoft.Network/connections",
    "virtualNetworkGateway1": {
      "activeActive": null,
      "bgpSettings": null,
      "enableBgp": null,
      "etag": null,
      "gatewayDefaultSite": null,
      "gatewayType": null,
      "id": "/subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV1/providers/Microsoft.Network/virtualNetworkGateways/VNet1GW",
      "ipConfigurations": null,
      "location": null,
      "name": null,
      "provisioningState": null,
      "resourceGroup": "VV1",
      "resourceGuid": null,
      "sku": null,
      "tags": null,
      "type": null,
      "vpnClientConfiguration": null,
      "vpnType": null
    },
    "virtualNetworkGateway2": null
  }
]

**Comment by tjprescott** [comment]
This is the data as returned from the server.

**Comment by aanandr** [comment]
Travis – I see a proper output when I check in powershell.

**Comment by tjprescott** [comment]
This was closed by mistake. I'll suppress the null values on the two sides of the connection and only display the IDs.
