### ISSUE TITLE
[CI] Tests in CI will return immediately when encountering the first failure

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#16151]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Tests in CI will return immediately when encountering the first failure, for example, if there are two recording files missing, it will only report one each time.

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
CI
