### ISSUE TITLE
[Compute] Request to Add "enableAutomaticUpgrade" flag for VMExtensions in CLI

### ISSUE THREAD

**Issue by chjaress** [Azure/azure-cli#16160]
**Resource Provider**
Microsoft.Compute (CRP)

**Description of Feature or Work Requested**
Need to add support for "enableAutomaticUpgrade" flag as part of VMExtension model. This bool flag will indicate if the extension should be automatically upgraded by Compute Platform.

**Minimum API Version Required**
2020-06-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/10134

**Target Date**
Jan 31, 2021

**Comment by yungezz** [comment]
ETA end of Jan 31st

**Comment by yungezz** [comment]
spec https://nam06.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fmicrosoft-my.sharepoint-df.com%2F%3Aw%3A%2Fp%2Fmanayar%2FEYTyarAcsjRKkLm2jXL5hHoBjfDeLhONxARBbRmCGrlcWw%3Fe%3Dvqqhxg&data=04%7C01%7Cyungez%40microsoft.com%7C3663e6f8d3bc4062cac108d898b29ca7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C1%7C637427240217333366%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AaHFZt47ukoPIXvaZeyWcTS3qeeQTRMUTFksaN%2BuwyA%3D&reserved=0
