### ISSUE TITLE
Error on using az ad app update

### ISSUE THREAD

**Issue by elafnit** [Azure/azure-cli#16166]
I tried your example for updating the app roles and received the following error
Property  value cannot be deleted or updated unless it is disabled first.
I failed to find the az cli command that would allow me to disable the app role to allow me to perform this app role update successfully.
Your assistance in addressing this pre-requisite would be greatly appreciated because this is the update I need to perform on my environment.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ad/app.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ad/app.yml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
az ad

**Comment by MartinWickman** [comment]
This is still an issue. To recap:

`az ad app update --id $app.appId --app-roles `@rolesManifest.json`

Fails if roles exist: `ERROR: Permission (scope or role) cannot be deleted or updated unless disabled first.`

I tried setting `isEnabled: false`, in the rolesManifest.json file, but no luck.

**Comment by elafnitzegger** [comment]
I've run into this as well. You need to set the flag in a separate transaction prior to deleting or updating the role/scope.

**Comment by MartinWickman** [comment]
> You need to set the flag in a separate transaction prior to deleting or updating the role/scope.

Cool, so there’s is actually a workaround that doesn’t involve manual fix in Azure portal? Can you please elaborate a bit, cause I can’t get it to work.

**Comment by elafnitzegger** [comment]
interesting enough, my earlier solution leveraged Powershell AZ not AZ CLI. When I used the example code for the command against one of my app registrations that contained an app role, I had no issues. I did have to reference the "manifest.json" file without using the '@' character. My command was 
`az ad app update --id "{myAppIdGuid}" --app-roles manifest.json`

**Comment by MartinWickman** [comment]
Yes thanks, but that's what I'm doing it and I get the error `Permission (scope or role) cannot be deleted or updated unless disabled first.` 

> You need to set the flag in a separate transaction prior to deleting

I'm looking for a (script) way to disable them so I can remove/update then.  I'm trying different permutations of the roles.json file to no avail.

**Comment by jiasli** [comment]
@MartinWickman, thank you for sharing the solution. I am sure it will help other users.

As for the behavior of AD Graph API, you may contact AAD support by creating a support ticket at https://azure.microsoft.com/en-us/support/create-ticket/. The "**Removing roles requires the existing role to be 'disabled'**" behavior is not related to Azure CLI command itself.

**Comment by franpb90** [comment]
> Eventually, I figured it out. My powershell skillz are horrible, but it works.
> 
> ```
> az ad app update --id $appId --app-roles `@roles.json
> 
> if (!$?) {
>     # Note: Roles are quirky. Updates and adds work fine if the role contains the "id" in the json file.
>     # Removing roles requires the existing role to be "disabled". We try to handle that here.
> 
>     Write-Output "* Roles failed: trying to fix by deleting all roles and creating again..."
>     # Fetch existing roles
>     $roles = (az ad app show --id $appId | ConvertFrom-Json ).appRoles
>     $roles | ForEach-Object { $_.isEnabled = $false }
>     $roles = ConvertTo-Json $roles
>     $roles | Out-File "disabled_roles.json"
>     # Disable them
>     az ad app update --id $appId --app-roles `@disabled_roles.json
>     # Add all roles. It should replace all existing roles
>     az ad app update --id $appId --app-roles `@roles.json
>     Write-Output "- Roles replaced"
> }
> else {
>     Write-Output "- Roles created"
> }
> ```

It has a side effect, users lose their role assignment. 
I am testing updating the ids in roles.json for the existing roles and using  `az rest --method PATCH --uri "https://graph.microsoft.com/v1.0/applications/$($app.objectId)" --headers 'Content-Type=application/json' --body "@$PSScriptRoot\roles.json"`
