### ISSUE TITLE
Regarding to the Public IP prefix length 

### ISSUE THREAD

**Issue by setunol** [Azure/azure-cli#16162]
Hello team, 

Not sure if this is the best place to reach out or not.  But we run into some issues where the customer has increased the quota limit to /26 for the prefix for the subscription (we can confirm that via the portal reflecting the increase.)  But attempting with CLI, it still fails. 

With regarding to the following parameter 

--length
Length of the prefix (i.e. XX.XX.XX.XX/<Length>).

Minimum PrefixLength 28 Maximum PrefixLength 31.  < -------------- this is the message that we are getting.  Is it possible to confirm if this is hard limit configured for the command itself regardless of the quota on the subscription level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f494d2d1-07a1-3ac8-fc2f-6aaddd340959
* Version Independent ID: c7e19a80-0c3d-268c-643d-3b2a8dde4027
* Content: [az network public-ip prefix](https://docs.microsoft.com/en-us/cli/azure/network/public-ip/prefix?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/public-ip/prefix.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/public-ip/prefix.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by haroldrandom** [comment]
![image](https://user-images.githubusercontent.com/14357159/101321174-e782da00-389f-11eb-94ca-989f6ddeba10.png)

I tested on Portal it is required a length between 28 to 31. Can't reproduce your situation. Could you please more detail?

**Comment by setunol** [comment]
Hello Jianhui,

Sorry about the delayed in getting back to you on this.  Please give me a little bit more time to follow up with the customer and the subscription team and get back to you on this.

What you saw via the portal is expected for a subscription with <default> limit.  The request that we got from the subscription team stating that they customer has already performed the increase, and the portal also reflects the change, but they are still failing with CLI.  But from the last request I just received, this might have something to do with the quota increase only applied to a specific region.  I will verify with the customer, and update this thread as soon as possible.


[cid:image001.png@01D6CE14.48DB55D0]


The original ask on this is:  customer increased the quota to allowing /26 for the public IP prefix, but they are still failing with CLI deployment.

Thank you,

Michael Li
Support Eng, Azure Networking
Office: +1 (425) 538-3864
micli@microsoft.com<mailto:micli@microsoft.com>
8:30 a.m. - 7:30 p.m. PST Wed-Fri
7:00 a.m. – 6:00 p.m. PST Sat

Locating an Engineer: azurebu@microsoft.com<mailto:azurebu@microsoft.com>
[Microsoft]
If you have any feedback about my work, please let either me or my manager Jeffrey Gumke at jefgu@microsoft.com<mailto:jefgu@microsoft.com>

**Comment by setunol** [comment]
Hello all,

Sorry about the delay in providing an update here.  I think we can disregard this, as the issue was due to subscription team didn't complete the request to the region that customer has requested.

From technical side, they have confirmed that everything is working now after the quota increase is completed.

Sorry for the inconveniences.

Thank you,

Michael Li
Support Eng, Azure Networking
Office: +1 (425) 538-3864
micli@microsoft.com<mailto:micli@microsoft.com>
8:30 a.m. - 7:30 p.m. PST Wed-Fri
7:00 a.m. - 6:00 p.m. PST Sat

Locating an Engineer: azurebu@microsoft.com<mailto:azurebu@microsoft.com>
[Microsoft]
If you have any feedback about my work, please let either me or my manager Jeffrey Gumke at jefgu@microsoft.com<mailto:jefgu@microsoft.com>



From: Michael Li <micli@microsoft.com>
Sent: Wednesday, December 9, 2020 10:16 AM
To: Azure/azure-cli <reply@reply.github.com>; Azure/azure-cli <azure-cli@noreply.github.com>
Cc: Author <author@noreply.github.com>; Michael Li <micli@microsoft.com>
Subject: RE: [Azure/azure-cli] Regarding to the Public IP prefix length (#16162)

Hello Jianhui,

Sorry about the delayed in getting back to you on this.  Please give me a little bit more time to follow up with the customer and the subscription team and get back to you on this.

What you saw via the portal is expected for a subscription with <default> limit.  The request that we got from the subscription team stating that they customer has already performed the increase, and the portal also reflects the change, but they are still failing with CLI.  But from the last request I just received, this might have something to do with the quota increase only applied to a specific region.  I will verify with the customer, and update this thread as soon as possible.


[cid:image001.png@01D6D47F.A93D72C0]


The original ask on this is:  customer increased the quota to allowing /26 for the public IP prefix, but they are still failing with CLI deployment.

Thank you,

Michael Li
Support Eng, Azure Networking
Office: +1 (425) 538-3864
micli@microsoft.com<mailto:micli@microsoft.com>
8:30 a.m. - 7:30 p.m. PST Wed-Fri
7:00 a.m. - 6:00 p.m. PST Sat

Locating an Engineer: azurebu@microsoft.com<mailto:azurebu@microsoft.com>
[Microsoft]
If you have any feedback about my work, please let either me or my manager Jeffrey Gumke at jefgu@microsoft.com<mailto:jefgu@microsoft.com>
