### ISSUE TITLE
Missing semicolon (;) in PowerShell help for az aks install-cli

### ISSUE THREAD

**Issue by glenncarr** [Azure/azure-cli#16170]
**Describe the bug**

The help displayed after executing `az aks install-cli` displays:

_Run "set PATH=%PATH%;C:\Users\<user>\.azure-kubectl" or **"$env:path += 'C:\Users\<user>\.azure-kubectl'"** for PowerShell. This is good for the current command session._

A semicolon is required before the appended path.  It should be:
**_$env:path += ';C:\Users\<user>\.azure-kubectl'"_**

**To Reproduce**

Install kubectl with `az aks install-cli`

**Expected behavior**

Displays the correct PowerShell command

**Environment summary**

Installing locally with PowerShell Core 7.1.0

**Comment by yonzhan** [comment]
aks
