### ISSUE TITLE
WebApp:Error when trying to enable client certificates for app service.

### ISSUE THREAD

**Issue by indrehus** [Azure/azure-cli#16178]
## Describe the bug

**Command Name**
`az webapp update`

**Errors:**
```
'NoneType' object has no attribute 'kind'
Traceback (most recent call last):
Temp\pip-install-363drsgw\knack\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 711, in _run_job
Local\Temp\pip-install-363drsgw\six\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
azure\cli\core\commands\arm.py, ln 527, in handler
azure\cli\command_modules\appservice\custom.py, ln 599, in update_webapp
AttributeError: 'NoneType' object has no attribute 'kind'
```

## To Reproduce:

- `az webapp update --set clientCertEnabled=true --name {} --resource-group {}`

## Expected Behavior

I expected to enable client certificates for my app service. I was following the guide at:

https://docs.microsoft.com/en-us/azure/app-service/app-service-web-configure-tls-mutual-auth

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.8.0 *

Extensions:
azure-devops 0.18.0
front-door 1.0.9

```
## Additional Context

I was able to perform the action from https://portal.azure.com/

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14287

**Comment by panchagnula** [comment]
@indrehus please try the command as
az webapp update --set clientCertEnabled=true --name <app-name> --resource-group <group-name> --subscription <SubId> & let us know if you still see the same issue. Thanks!

**Comment by seligj95** [comment]
@indrehus Please let us know if the above solved your issue. Thanks!

**Comment by seligj95** [comment]
closing due to lack of response and answer provided by service team
