### ISSUE TITLE
Azure CLI on Apple Silicon

### ISSUE THREAD

**Issue by moredhel** [Azure/azure-cli#16197]
## Describe the bug

The following error occurs when running on Apple Silicon from the home-brew install.

**Command Name**
`az aks get-credentials`

**Errors:**
```
dlopen(/opt/homebrew/Cellar/azure-cli/2.15.1/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 2): Symbol not found: _ffi_prep_closure
  Referenced from: /opt/homebrew/Cellar/azure-cli/2.15.1/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so
  Expected in: flat namespace
 in /opt/homebrew/Cellar/azure-cli/2.15.1/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so
Traceback (most recent call last):
...
  Expected in: flat namespace
 in /opt/homebrew/Cellar/azure-cli/2.15.1/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {} --admin`

## Environment Summary
```
macOS-11.0.1-arm64-arm-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.15.1

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by maxburke** [comment]
Seeing this issue as well with Homebrew + Apple Silicon.

**Comment by iFlameing** [comment]
> Seeing this issue as well with Homebrew + Apple Silicon.

@maxburke can you tell me what do you mean by above line. Does the above problem related to homered?

**Comment by moredhel** [comment]
This issue has been resolved 👍
