### ISSUE TITLE
az storage blob upload-batch: report percentage correctly

### ISSUE THREAD

**Issue by nkaretnikov** [Azure/azure-cli#16199]
azure-cli 2.16.0

Happens during `az storage blob upload-batch`:

<img width="90" alt="Screen Shot 2020-12-08 at 20 53 08" src="https://user-images.githubusercontent.com/10469885/101522038-bab1ee00-3997-11eb-8e9e-180c57595c08.png">
<img width="93" alt="Screen Shot 2020-12-08 at 20 50 34" src="https://user-images.githubusercontent.com/10469885/101522045-bd144800-3997-11eb-9740-269af03d3dc7.png">

**Comment by nkaretnikov** [comment]
Just to clarify: the issue here is the way this is formatted.

I would expect to see:
```
30%
2%
```

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @nkaretnikov, to get more accurate calculation, CLI will presents the percent  which is rounded to 4 decimals.
Do you think the integer number is enough to display the percentage?
