### ISSUE TITLE
az vm list-sizes shows incorrect vcpu counts for constrained machines re-open

### ISSUE THREAD

**Issue by sbonds** [Azure/azure-cli#16196]
## Describe the bug

Constrained vCPU VMs show incorrect CPU count info in `az vm list-sizes` (and also in PowerShell `Get-AzVMSize`)

This is identical to the closed-for-inactivity issue #5243.

**Command Name**
`az vm list-sizes`

## To Reproduce:

- `az vm list-sizes --location eastus --query "[?name=='Standard_M128-32ms']"`

Actual output (note numberOfCores):

```json
[
  {
    "maxDataDiskCount": 64,
    "memoryInMb": 3891200,
    "name": "Standard_M128-32ms",
    "numberOfCores": 128,
    "osDiskSizeInMb": 1047552,
    "resourceDiskSizeInMb": 4096000
  }
]
```

## Expected Behavior

The constrained vCPU VMs would report the number of cores available to the VM. In the above case of `Standard_M128-32ms` I would expect numberOfCores to be 32 instead of 128.

## Environment Summary
```
Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 3.6.8
Installer: RPM

azure-cli 2.15.1 *

```
## Additional Context

Since this incorrect info is also reported by the PowerShell `Get-AzVMSize` command this is likely the CLI correctly reporting info that was incorrect in the upstream API. For example, this PowerShell command:

```powershell
Get-AzVMSize -Location eastus | Where-Object {$_.Name -eq "Standard_M128-32ms"}
```
Reports this identical info as the `az` CLI:

```text
Name               NumberOfCores MemoryInMB MaxDataDiskCount OSDiskSizeInMB ResourceDiskSizeInMB
----               ------------- ---------- ---------------- -------------- --------------------
Standard_M128-32ms           128    3891200               64        1047552              4096000
```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by sbonds** [comment]
A possible non-breaking fix would be to add a new field along the lines of `ConstrainedNumberOfCores` which would equal `NumberOfCores` for non-CPU-constrained VMs

**Comment by sbonds** [comment]
A clever workaround in the meantime would be to parse out the constrained cores count from the size description, e,g, parsing out `32` from the text `Standard_M128-32ms`. This is a non-ideal solution since text fields can change more easily over time than defined attribute values.

**Comment by rafamarrara** [comment]
I am not sure, but this command could be using a deprecated API
Virtual Machine Sizes - List
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinesizes/list

> _This API is deprecated. Use Resources Skus
https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list_

**Comment by Drewm3** [comment]
The list of "cores" shown in the properties of the VM aligns with the cores required for quota purposes. In the case of suppressed core VMs the quota required is based on the parent VM size. For the details on suppressed cores you need to use the SKUs API.

In general, all new property/spec additions for SKUs are being described in the SKU API instead of properties of the resource directly.

**Comment by sbonds** [comment]
The "az vm list-skus" command does not show any info for constrained core VMs so the above might be true from an API standpoint, but does not resolve this issue.

**Comment by brokedba** [comment]
@sbonds  I totally agree . I created a shell script that lists the vm size based on number of cores and the same happens when I select   Standard_E32-8s_v5 . 
```
az vm list-sizes -l eastus --query "sort_by(@,&memoryInMb)[?numberOfCores == \`8\` && (contains(name,\`E32\`) )]" -o table
0 result
```
It's been years now . How hard is it to add a new attribute to the json construct
```
$ az vm list-sizes -l eastus --query "sort_by(@,&memoryInMb)[?numberOfCores == \`32\` && (contains(name,\`Standard_E32-8ads\`) )]" -o table

Name                  NumberOfCores    ConstrainedNumberOfCores OsDiskSizeInMb    ResourceDiskSizeInMb    MemoryInMb    MaxDataDiskCount       
--------------------  --------------- ------------------------- ----------------  ----------------------  ------------  ------------------  
Standard_E32-8ads_v5  32                    8                   1047552           1228800                 262144        32                  
```

**Comment by brokedba** [comment]
@sbonds , after some digging few weeks ago I found a way to display the actual CPU core number for constrained VMs from `az vm list-skus` .
The missing info was hidden under the VM size capabilities section in the json construct.
-  After checking the JSON construct of the source, I picked the info through
                    `capabilities[vCPUsAvailable].Value`
- **example** : Here is the final query based on the same query filter (E32, 8 Constrained vCPU)
```
$ az vm list-skus -z --resource-type  virtualMachines --size "E32" -l eastus \
--query "[?capabilities[?name==\`vCPUsAvailable\`].value|[0] == '8'].{name:name, \ 
VCPU:capabilities[?name==\`vCPUs\`].value|[0], \
ActualVCPU:capabilities[?name==\`vCPUsAvailable\`].value|[0], \
MemoryGB:capabilities[?name==\`MemoryGB\`].value|[0]} \
 | reverse(sort_by(@,&name))" -o table
 
Name                  VCPU    ActualVCPU    MemoryGB
--------------------  ------  ------------  ----------
Standard_E32-8s_v5    32      8             256
Standard_E32-8s_v4    32      8             256
Standard_E32-8s_v3    32      8             256
Standard_E32-8ds_v5   32      8             256
Standard_E32-8ds_v4   32      8             256
Standard_E32-8as_v5   32      8             256
Standard_E32-8as_v4   32      8             256
Standard_E32-8ads_v5  32      8             256

```

* Bonus : I also built a Bundle Script  **"Azure Constrained CPU VM Selector"**
- You can download the script here >> [az-cli-examples/check_az_vmsize.sh](https://github.com/brokedba/az-cli-examples/blob/main/check_az_vmsize.sh) 
   - Read more in my [blog post (Azure VM Selection Made Easy)](http://www.brokedba.blogspot.com/2023/04/azure-vm-selection-made-easy-script-for.html)
   - See demo below
   
![image](https://user-images.githubusercontent.com/29458929/232410502-ac6aa64d-8bd4-47e8-86bf-42af90fa5ab4.gif)

HTH 
cheers
