### ISSUE TITLE
az monitor log-analytics workspace table show returns retention as null

### ISSUE THREAD

**Issue by tofriedl** [Azure/azure-cli#16207]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

using az cli to update a table seems to work and to return the correct payload. but when using get table the retention returns as null. in addition when using REST request directly to ARM the correct payload is received.

Rest request sent:
GET https://management.azure.com/subscriptions/a8732c41-c4a7-4fa1-a180-f3efb7843f6f/resourcegroups/testworkspaces/providers/Microsoft.OperationalInsights/workspaces/TestWorkspaceWestUS/tables/Heartbeat?api-version=2015-11-01-preview HTTP/1.1

Rest response:
{"properties":{"RetentionInDays":40,"IsTroubleshootingAllowed":false},"id":"/subscriptions/a8732c41-c4a7-4fa1-a180-f3efb7843f6f/resourcegroups/testworkspaces/providers/microsoft.operationalinsights/workspaces/testworkspacewestus/tables/heartbeat","name":"Heartbeat"}

Example using cli:

PS /home/tom> az monitor log-analytics workspace table show --resource-group testworkspaces --workspace-name TestWorkspaceWestUS --name Heartbeat
{
  "id": "/subscriptions/a8732c41-c4a7-4fa1-a180-f3efb7843f6f/resourcegroups/testworkspaces/providers/microsoft.operationalinsights/workspaces/testworkspacewestus/tables/heartbeat",
  "name": "Heartbeat",
  "resourceGroup": "testworkspaces",
  "retentionInDays": null,
  "type": null
}
PS /home/tom> az monitor log-analytics workspace table update --resource-group testworkspaces --workspace-name TestWorkspaceWestUS --name Heartbeat --retention-time 40
{
  "id": "/subscriptions/a8732c41-c4a7-4fa1-a180-f3efb7843f6f/resourcegroups/testworkspaces/providers/microsoft.operationalinsights/workspaces/testworkspacewestus/tables/heartbeat",
  "name": "Heartbeat",
  "resourceGroup": "testworkspaces",
  "retentionInDays": 40,
  "type": null
}
PS /home/tom> az monitor log-analytics workspace table show --resource-group testworkspaces --workspace-name TestWorkspaceWestUS --name Heartbeat
{
  "id": "/subscriptions/a8732c41-c4a7-4fa1-a180-f3efb7843f6f/resourcegroups/testworkspaces/providers/microsoft.operationalinsights/workspaces/testworkspacewestus/tables/heartbeat",
  "name": "Heartbeat",
  "resourceGroup": "testworkspaces",
  "retentionInDays": null,
  "type": null
}

**To Reproduce**
in order to reproduce just run 
az monitor log-analytics workspace table update
and then 
az monitor log-analytics workspace table show

and you will see the retention returns as null

**Expected behavior**
the expected behavior is that the retention will return when running the "show" command

**Environment summary**
i tried to run from CLI in azure portal, but i guess it is the same for all environments

**Additional context**
the type is also null - i am not sure what it supposed to contains, but maybe worth fixing it as well

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
The property 'retentionInDays' is not capitalize in [swagger](https://github.com/Azure/azure-rest-api-specs/blob/fef61739185a1501cdccdafa40ada903120e8ba3/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/preview/2020-03-01-preview/Tables.json#L183). But in response body it names 'RetentionInDays'.

**Comment by Hiroaki-Tsutsumi** [comment]
Please let me know the current status of this article.

**Comment by kairu-ms** [comment]
@sameergMS @dadunl Please help with this issue. Thanks!

**Comment by Hiroaki-Tsutsumi** [comment]
Can you please tell me the current status of this event?

**Comment by yonzhan** [comment]
Monitor service team should look into this issue.

**Comment by Hiroaki-Tsutsumi** [comment]
CX is required for an urgent resolving this issue.
When are you planning to resolve this issue?
