### ISSUE TITLE
WebApp:az webapp log tail and insufficient information about linux

### ISSUE THREAD

**Issue by TPIvan** [Azure/azure-cli#16203]
az webapp log tail and download says:
_This command may not work with web apps running on Linux._
However there is no other explanation.
There are issues with containeres like this: https://github.com/Azure/azure-cli/issues/1803, but it is almost 4 years old.  It would be very useful to have some explanation about when the commands work and when not or how to obtain log for linux.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bee2e287-5fb7-a849-9d3b-87013b783f16
* Version Independent ID: 97f9e1c4-1573-b776-0fce-53c65839d713
* Content: [az webapp log](https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#az_webapp_log_tail)
* Content Source: [latest/docs-ref-autogen/webapp/log.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/log.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
routing to service team to have a look

**Comment by ThejaChoudary** [comment]
Working on this.Thanks!

**Comment by gkaleta** [comment]
Any progress on this?

**Comment by ryansan** [comment]
Any update?

**Comment by tulikac** [comment]
az webapp log tail works for a Linux Bring your own code app. It does not work for a Bring your own container app. Will file a doc bug to call out this scenario.

**Comment by tulikac** [comment]
Determine why it would not show for Bring Your Own Container scenarios

**Comment by sarsharma** [comment]
Tested log tail command for bring your own container scenario. It is working fine. 
@tulikac @btardif

**Comment by btardif** [comment]
#please-close
