### ISSUE TITLE
Internal Error: az network application-gateway private-link add

### ISSUE THREAD

**Issue by jmeadowcroft** [Azure/azure-cli#16215]
**Describe the bug**
I get an internal error when executing the command:
az network application-gateway private-link add --frontend-ip {my-existing-frontend-ip} --name {new-private-link-name} --subnet {subnet-name} --gateway-name {app-gateway-name} --resource-group {resource-group-name} 
Error:
Command group 'network application-gateway private-link' is in preview. It may be changed/removed in a future release.
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-2huwp6jm\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 654, in execute       
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 717, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 710, in _run_job      
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-in8b2jw5\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 688, in _run_job      
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 325, in __call__      
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\__init__.py", line 784, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-_skkczbr\azure\cli\command_modules\network\custom.py", line 511, in add_ag_private_link
TypeError: 'NoneType' object is not iterable

**To Reproduce**
Execute the command above

**Expected behavior**
Add a private link

**Environment summary**
az cli version: 2.16.0

**Comment by yonzhan** [comment]
apim

**Comment by jmeadowcroft** [comment]
I deployed a different different application gateway and I no longer receive the internal error. I thought it might be helpful to provide the configuration of the app gateway that produced the error. Here is the deployment arm template.
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "applicationGateways_test_name": {
            "defaultValue": "test",
            "type": "String"
        },
        "virtualNetworks_vnet_dev_vmtest_externalid": {
            "defaultValue": "/subscriptions/{subscription}/resourceGroups/{rg}/providers/Microsoft.Network/virtualNetworks/vnet-dev-vmtest",
            "type": "String"
        },
        "publicIPAddresses_test_externalid": {
            "defaultValue": "/subscriptions/{subscription}/resourceGroups/{rg}/providers/Microsoft.Network/publicIPAddresses/test",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.Network/applicationGateways",
            "apiVersion": "2020-05-01",
            "name": "[parameters('applicationGateways_test_name')]",
            "location": "westus2",
            "tags": {
            },
            "properties": {
                "sku": {
                    "name": "Standard_Medium",
                    "tier": "Standard",
                    "capacity": 2
                },
                "gatewayIPConfigurations": [
                    {
                        "name": "appGatewayIpConfig",
                        "properties": {
                            "subnet": {
                                "id": "[concat(parameters('virtualNetworks_vnet_dev_vmtest_externalid'), '/subnets/{subnet name}')]"
                            }
                        }
                    }
                ],
                "sslCertificates": [],
                "authenticationCertificates": [],
                "frontendIPConfigurations": [
                    {
                        "name": "appGwPublicFrontendIp",
                        "properties": {
                            "privateIPAllocationMethod": "Dynamic",
                            "publicIPAddress": {
                                "id": "[parameters('publicIPAddresses_test_externalid')]"
                            }
                        }
                    }
                ],
                "frontendPorts": [
                    {
                        "name": "port_80",
                        "properties": {
                            "port": 80
                        }
                    }
                ],
                "backendAddressPools": [
                    {
                        "name": "[parameters('applicationGateways_test_name')]",
                        "properties": {
                            "backendAddresses": []
                        }
                    }
                ],
                "backendHttpSettingsCollection": [
                    {
                        "name": "[parameters('applicationGateways_test_name')]",
                        "properties": {
                            "port": 80,
                            "protocol": "Http",
                            "cookieBasedAffinity": "Disabled",
                            "pickHostNameFromBackendAddress": false,
                            "requestTimeout": 20
                        }
                    }
                ],
                "httpListeners": [
                    {
                        "name": "listener",
                        "properties": {
                            "frontendIPConfiguration": {
                                "id": "[concat(resourceId('Microsoft.Network/applicationGateways', parameters('applicationGateways_test_name')), '/frontendIPConfigurations/appGwPublicFrontendIp')]"
                            },
                            "frontendPort": {
                                "id": "[concat(resourceId('Microsoft.Network/applicationGateways', parameters('applicationGateways_test_name')), '/frontendPorts/port_80')]"
                            },
                            "protocol": "Http",
                            "hostNames": [],
                            "requireServerNameIndication": false
                        }
                    }
                ],
                "urlPathMaps": [],
                "requestRoutingRules": [
                    {
                        "name": "rule",
                        "properties": {
                            "ruleType": "Basic",
                            "httpListener": {
                                "id": "[concat(resourceId('Microsoft.Network/applicationGateways', parameters('applicationGateways_test_name')), '/httpListeners/listener')]"
                            },
                            "backendAddressPool": {
                                "id": "[concat(resourceId('Microsoft.Network/applicationGateways', parameters('applicationGateways_test_name')), concat('/backendAddressPools/', parameters('applicationGateways_test_name')))]"
                            },
                            "backendHttpSettings": {
                                "id": "[concat(resourceId('Microsoft.Network/applicationGateways', parameters('applicationGateways_test_name')), concat('/backendHttpSettingsCollection/', parameters('applicationGateways_test_name')))]"
                            }
                        }
                    }
                ],
                "probes": [],
                "rewriteRuleSets": [],
                "redirectConfigurations": [],
                "enableHttp2": false
            }
        }
    ]
}

**Comment by msyyc** [comment]
similar issue : https://github.com/Azure/azure-cli/issues/17272
