### ISSUE TITLE
Failed to import MS sample json file into Azure API management interface

### ISSUE THREAD

**Issue by aphlai** [Azure/azure-cli#16214]
## Describe the bug

**Command Name**
`az apim api import`

**Errors:**
```
must be str, not NoneType
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-2huwp6jm\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 717, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 710, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-in8b2jw5\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
pip-unpacked-wheel-0ydpnxq9\azure\cli\core\__init__.py, ln 784, in default_command_handler
azure\cli\command_modules\apim\custom.py, ln 275, in import_apim_api
TypeError: must be str, not NoneType
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim api import -g {} -n {} --path {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.16.0

```
## Python exception throws once executing the import command line
![image](https://user-images.githubusercontent.com/37915758/101696594-35cfed00-3adb-11eb-8e2c-714d22fec496.png)

**Comment by aphlai** [comment]
Attaching also the sample json used in zip format.  The file was downloaded from [MS tutorial page](https://docs.microsoft.com/en-us/azure/api-management/import-and-publish)



[azureAPI.zip](https://github.com/Azure/azure-cli/files/5669127/azureAPI.zip)

**Comment by yonzhan** [comment]
apim

**Comment by miaojiang** [comment]
@RupengLiu please take a look.

**Comment by eyesis** [comment]
I got the same error, with the same sample API. My full command was:

`az apim api import --path https://conferenceapi.azurewebsites.net?format=json --resource-group ApiResourceGroup --service-name AndrewApiM --protocols https`
