### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iter'

### ISSUE THREAD

**Issue by ghost** [Azure/azure-cli#16217]
## Describe the bug

**Command Name**
`az storage fs file list`

**Errors:**
```
'dict' object has no attribute 'iter'
Traceback (most recent call last):
storagev2/filedatalake/v2020_02_10/_list_paths_helper.py, ln 56, in _get_next_cb
    cls=return_headers_and_deserialized_path_list)
v2020_02_10/_generated/operations/_file_system_operations.py, ln 442, in list_paths
    raise models.StorageErrorException(response, self._deserialize)
azure.multiapi.storagev2.filedatalake.v2020_02_10._generated.models._models_py3.StorageErrorException: (EndpointUnsupportedAccountFeatures) This endpoint does not support BlobStorageEvents or SoftDelete. Please disable these account features if you would like to use this endpoint.
RequestId:b74e382b-701f-0004-5e8e-ce25f0000000
Time:2020-12-10T00:49:15.5364417Z

...

filedatalake/v2020_02_10/_shared/response_handlers.py, ln 94, in process_storage_error
    for info in error_body.iter():
AttributeError: 'dict' object has no attribute 'iter'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage fs file list -f {} --account-name {} --account-key {}`

## Environment Summary
```
Linux-4.18.0-193.14.3.el8_2.x86_64-x86_64-with-redhat-8.2-Ootpa
Python 3.6.8
Installer: RPM

azure-cli 2.16.0

Extensions:
storage-preview 0.6.0

```

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
hi @ghost, the error is EndpointUnsupportedAccountFeatures. Could you share more info with `--debug` in your command?
Could you also share your storage account info? Have you enabled hierarchical namespace for your storage account?

**Comment by Juliehzl** [comment]
Given there is no response for long time, I will close the PR and please create a new one if there is still the issue.

**Comment by cbare** [comment]
I also see this error in line 97 of `_shared/response_handlers.py` in the function process_storage_error. The relevant lines are:

``` python
[95]       error_body = ContentDecodePolicy.deserialize_from_http_generics(storage_error.response)
[96]        if error_body:
[97]            for info in error_body.iter():
```

Stepping in with pdb, I see the following:

`
[...]/venv/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py(97)process_storage_error()
-> if error_body:
(Pdb) type(error_body)
<class 'dict'>
(Pdb) print(error_body)
{'error': {'code': 'InvalidQueryParameterValue', 'message': 'Value for one of the query parameters specified in the request URI is invalid.\nRequestId:82bff81c-501f-0053-39b5-344d92000000\nTime:2021-04-19T00:44:42.6291960Z'}}
`

So, it looks like under at least some circumstances, `ContentDecodePolicy.deserialize_from_http_generics` returns a dict rather than whatever type is expected.

**Comment by Juliehzl** [comment]
> Hi, I'm seeing this same error.
> 
> Using `azure-storage-blob==12.8.0`, it happens in line 97 of `_shared/response_handlers.py` in the function process_storage_error. The relevant lines are:
> 
> ```python
> [95]       error_body = ContentDecodePolicy.deserialize_from_http_generics(storage_error.response)
> [96]        if error_body:
> [97]            for info in error_body.iter():
> ```
> 
> Stepping in with pdb, I see the following:
> 
> ```
> [...]/venv/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py(97)process_storage_error()
> -> if error_body:
> (Pdb) type(error_body)
> <class 'dict'>
> (Pdb) print(error_body)
> {'error': {'code': 'InvalidQueryParameterValue', 'message': 'Value for one of the query parameters specified in the request URI is invalid.\nRequestId:82bff81c-501f-0053-39b5-344d92000000\nTime:2021-04-19T00:44:42.6291960Z'}}
> ```
> 
> So, it looks like under at least some circumstances, `ContentDecodePolicy.deserialize_from_http_generics` returns a dict rather than whatever type is expected.

Thanks a lot for your feedback! It seems the response doesn't has SDK expected type. azure-storage-blob source code is in https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob. could you create an issue in https://github.com/Azure/azure-sdk-for-python/issues?

**Comment by cbare** [comment]
Related issue filed on azure-sdk-python here: https://github.com/Azure/azure-sdk-for-python/issues/18129
