### ISSUE TITLE
Error when peering two Virtual Networks  on Linux OS

### ISSUE THREAD

**Issue by djr29578** [Azure/azure-cli#16235]
**az network vnet peering create**  command fails on ubuntu 18.04 when trying to peer two Vnets.  

Az cli verison = 2.16

Have tried multiple ways of writing the script from passing resource ID's as variables, hardcoding the VNet names/id's but always receive **cli.azure.cli.core.azclierror : BadRequestError: Cannot parse the request.
BadRequestError: Cannot parse the request.**

error occurs when peering VNets in same RG or separate.

Error message when run with --debug:
  **"error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "InvalidJson",
        "message": "Could not find member 'syncRemoteAddressSpace' on object of type 'VirtualNetworkPeeringProperties'. Path 'properties.syncRemoteAddressSpace', line 1, position 489."
      }
    ]
  }
}**

**Comment by yonzhan** [comment]
network

**Comment by runemy** [comment]
Hi. I do get the same  message in CloudShell.

**Comment by msyyc** [comment]
same with https://github.com/Azure/azure-cli/issues/16211

**Comment by akshaysngupta** [comment]
+1 seeing same error when creating a peering.

**Comment by nboeckmann** [comment]
+1 - And now it's getting really annoying as the hosted Agents in Azure DevOps have just been switched to 2.16 - So no one using Azure DevOps can create any network peerings using the Azure CLI task anylonger.

**Comment by yonzhan** [comment]
We are proactively following up with service team about this and will update later.

**Comment by nboeckmann** [comment]
any update on this one?

**Comment by alepauly** [comment]
@nboeckmann, @djr29578, @runemy , @akshaysngupta, @msyyc - the following commands can be use to downgrade the version and unblock your builds on the Hosted Azure DevOps agents:

Windows:
```
choco uninstall azure-cli
choco install azure-cli --version 2.15.1
az version
```

Ubuntu:
```
sudo apt-get remove azure-cli
sudo apt-get install azure-cli=2.15.1-1~focal
az version
```

Please keep us posted on any issues with them. Thanks!

**Comment by nboeckmann** [comment]
Hey @alepauly,

that works! Thank you!

Nils

**Comment by alepauly** [comment]
Also, for MacOS:

```
brew uninstall azure-cli
brew tap-new $USER/old-azure-cli
brew extract --version=2.15.1 azure-cli $USER/old-azure-cli
brew install azure-cli@2.15.1
az version
```

**Comment by msyyc** [comment]
Thanks for comment. We have found the problem and it will be fixed in new version(will be released at about 2020/12/31). The problem could be avoided temporarily through downgrading version to 2.15.1.

![Uploading image.png…]()

**Comment by haroldrandom** [comment]
One of live test failed due to the same issue https://clitestresultstac.blob.core.windows.net/20201211-043721-979918/network.report.parallel.html

**Comment by msyyc** [comment]
the problem has been fixed.
