### ISSUE TITLE
Need more details on properties to update

### ISSUE THREAD

**Issue by fsureau** [Azure/azure-cli#16230]
Documentation does not show how to update data. 
update command with Id to select the service connection ok. But how to pass parameters to update?

Regards,
Florian.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd63c4b-37f7-3641-8f15-0f5713ab71b4
* Version Independent ID: 39006efa-983d-d605-ca4f-95ffd91fbec4
* Content: [az devops service-endpoint](https://docs.microsoft.com/en-us/cli/azure/devops/service-endpoint?view=azure-cli-latest#az_devops_service_endpoint_list)
* Content Source: [latest/docs-ref-autogen/devops/service-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/devops/service-endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
devops

**Comment by RakeshMohanMSFT** [comment]
If you are still looking for solution, please reopen an issue in [azure cli extension ](https://github.com/Azure/azure-cli-extensions/issues)
