### ISSUE TITLE
`az policy` `auditIfNotExists` `vnetRouteAllEnabled`. Compliance scan fails when `WEBSITE_VNET_ROUTE_ALL=1`

### ISSUE THREAD

**Issue by DanielLarsenNZ** [Azure/azure-cli#16269]
**Resource Provider**

`Microsoft.Web/sites`

**Description of Feature or Work Requested**

An ARM Policy deployed with `az policy definition create` and `az policy assignment create` with an effect of `auditIfNotExists` that tests for the presence of `Microsoft.Web/sites/config/vnetRouteAllEnabled = true` will report failed when App Services App Setting `WEBSITE_VNET_ROUTE_ALL=1`.

## Background

In Azure App Services, you can force a Web App to route its outbound traffic through a VNet (as opposed to Internet) by setting an App Setting (environment variable) `WEBSITE_VNET_ROUTE_ALL`: [Regional VNet Integration](https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet#regional-vnet-integration#:~:text=WEBSITE_VNET_ROUTE_ALL).

App Services team have submitted a PR to expose this property via ARM: [Add vnetRouteAllEnabled and vnetPrivatePortsCount to Microsoft.Web/sites/config swagger #11152](https://github.com/Azure/azure-rest-api-specs/pull/11152).

We now need this property to be effective for ARM Policy compliance scans.

**Minimum API Version Required**

Not sure.

**Swagger Link**

[Add vnetRouteAllEnabled and vnetPrivatePortsCount to Microsoft.Web/sites/config swagger #11152](https://github.com/Azure/azure-rest-api-specs/pull/11152)

**Target Date**

ASAP.

**Comment by yonzhan** [comment]
policy

**Comment by kenieva** [comment]
Investigating..

**Comment by kenieva** [comment]
Hi @DanielLarsenNZ, it seems that this is a known issue by that RP: https://github.com/Azure/azure-policy#resource-type-query-results-incomplete-missing-or-non-standard-format

**Comment by DanielLarsenNZ** [comment]
Yes that is right :D And on that page is a link to open a support ticket with the Web team, which is how we started with this case in the first place. This scenario is very important to this customer.
![image](https://user-images.githubusercontent.com/2294760/104237197-95dff780-54bc-11eb-892c-980a331ee808.png)

**Comment by kenieva** [comment]
If they have added the change into swagger, the only action on the policy side would be to create aliases. But per our discussion, it seems that the aliases are exposed.

**Comment by DanielLarsenNZ** [comment]
Here is where the property was added to rest-api-specs by the Web team. Apparently it's available as of version `2020-09-01`.

https://github.com/Azure/azure-rest-api-specs/commit/7c3af69837d5f90812c1c7052b5e1c2ab750ca71

**Comment by kenieva** [comment]
Policy operates on the latest version so the property should have been added. So the alias has been updated and exposed, but is it still not working as required?

**Comment by DanielLarsenNZ** [comment]
Hi @kenieva, I have just tested this again and it is still not working from my perspective. Here are my steps to reproduce:

1. Run [deploy-vnet-route-all.ps1](https://github.com/DanielLarsenNZ/examples/blob/main/private-paas/deploy-vnet-route-all.ps1)

This will deploy a test App Service with the `WEBSITE_VNET_ROUTE_ALL=1` App Setting configured. The app attempts to create a connection to <https://www.dropbox.com/> but is prevented from connecting because traffic is being forced into the VNet and is being blocked by an NSG.

![image](https://user-images.githubusercontent.com/2294760/108811553-599ecb80-7612-11eb-9003-22e420a5a2c6.png)

1. Run [deploy-policy-azcli.ps1](https://github.com/DanielLarsenNZ/azure-policy/blob/master/samples/WebApp/web-app-vnet-route-all-enabled/deploy-policy-azcli.ps1)

This will deploy the policy to the resource group that the App Service is deployed into. When the scan completes* you will see that the audit policy is non compliant. My expectation is that the policy would report the resource as compliant.

![image](https://user-images.githubusercontent.com/2294760/108813528-0f1f4e00-7616-11eb-84df-c0cbbb8d0584.png)

\*You can trigger the scan on the Resource Group with this command: `az policy state trigger-scan -g 'hellovnetrouteall-rg'`

**Comment by kenieva** [comment]
Hi Daniel, from this policy: https://github.com/DanielLarsenNZ/azure-policy/blob/master/samples/WebApp/web-app-vnet-route-all-enabled/azurepolicy.json the existence condition reads if the Microsoft.Web/sites/config/vnetRouteAllEnabled equals true then audit as non-compliant. I believe the logic you are looking for is if  Microsoft.Web/sites/config/vnetRouteAllEnabled equals false.

**Comment by DanielLarsenNZ** [comment]
Hi @kenieva, this is the rule I am using (the logic is identical): [azurepolicy.rules.json](https://github.com/DanielLarsenNZ/azure-policy/blob/master/samples/WebApp/web-app-vnet-route-all-enabled/azurepolicy.rules.json).

The effect is `auditIfNotExists`: [If any matching related resource evaluates to true, the effect is satisfied and doesn't trigger the audit](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/effects#audit#:~:text=If%20any%20matching%20related%20resource%20evaluates%20to%20true%2C%20the%20effect%20is%20satisfied%20and%20doesn't%20trigger%20the%20audit.).

Never the less, I tried your suggestion and the policy does go compliant, but it is also compliant when the `WEBSITE_VNET_ROUTE_ALL=1` setting is missing, so it is still not working - note in my screen shot above, the **Current value** is `false` which is not correct.

**Comment by DanielLarsenNZ** [comment]
Thanks to @kahawai-sre I finally got this to work. The `vnetRouteAllEnabled` property must be set using ARM. Policy will not be effected by the App Setting (WEBSITE_VNET_ROUTE_ALL).

For this policy to take effect:

1. App Service must be deployed using an ARM API Version >= `2019-04-01`
1. App Service (`Microsoft.Web/sites`) property `siteConfig` > `vnetRouteAllEnabled` must be set to `true` using an ARM template, e.g.

```json
"resources": [
    {
      "type": "Microsoft.Web/sites",
      "apiVersion": "2020-09-01",
      "name": "[parameters('appName')]",
      "location": "[parameters('location')]",
      "kind": "app",
      "dependsOn": [
        
      ],
      "properties": {
        "serverFarmId": "[resourceId('Microsoft.Web/serverFarms', parameters('appServicePlanName'))]",
        "siteConfig": {
          "vnetRouteAllEnabled": true
        }
      }
    }
  ]
```
