### ISSUE TITLE
WebApp:az webapp up gives "too many 502 error responses"

### ISSUE THREAD

**Issue by JasonFreeberg** [Azure/azure-cli#16266]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

The `az webapp up` command fails to deploy my site content.

**To Reproduce**

Follow the Python tutorials for Django or Flask (both reproduce the issue). The first usage of `az webapp up` works, but I get the following exception when I try to re-deploy after making a code change. The error occurred on Free and Basic tiers.

![image](https://user-images.githubusercontent.com/18747768/102136020-b4939580-3e0d-11eb-8416-973b4062506c.png)

Here are the quickstarts:

- https://docs.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=bash&pivots=python-framework-flask
- https://docs.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=bash&pivots=python-framework-django

**Expected behavior**

The site content should be deployed.

**Environment summary**

I'm using PowerShell

```powershell
PS C:\Users\jafreebe> az --version
azure-cli                         2.16.0

core                              2.16.0
telemetry                          1.0.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\jafreebe\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Additional context**

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@JasonFreeberg do you still repro this with the latest CLI version?

**Comment by StrawnSC** [comment]
@JasonFreeberg I'm unable to repro this when I try it -- both the initial deploy and the update work for me for the flask & Django examples. Are you still running into this issue?

**Comment by seligj95** [comment]
closing
