### ISSUE TITLE
az apim backup Invalid parameter: The specifed resource name contains invalid characters.  Parameter name: backupContainerName

### ISSUE THREAD

**Issue by alpersilistre** [Azure/azure-cli#16262]
## Describe the bug

We have been using `az apim backup` for a long time but suddenly we started to get this error. The error message does not make any sense, there is no parameter called backupContainerName, I have checked this GitHub repo and couldn't find anything either. We first saw this in Azure DevOps agent and then I tried to run this command in my local machine, but the same error exists.

We have an automation to run this script every day but since December 08, we are getting this error. I attached an image to show it was running successfully for a long time.

![image](https://user-images.githubusercontent.com/6996763/102089695-a2295400-3e2d-11eb-867b-a72d00b776c1.png)

**Command Name**
`az apim backup`

**Errors:**
```
InvalidParameters: Invalid parameter: The specifed resource name contains invalid characters.

Parameter name: backupContainerName
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az apim backup --backup-name {} -n {} -g {} --storage-account-container {} --storage-account-key {} --storage-account-name {} --subscription {}`

## Expected Behavior

_az apim backup_ runs successfully as it used to be.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.16.0

Extensions:
azure-devops 0.17.0
blueprint 0.1.1

```

**Comment by yonzhan** [comment]
apim

**Comment by alpersilistre** [comment]
This error occurs in the azure-cli wta-dev version, I switched back to **2.15.1** and didn't get the error.

**Comment by adamstruck** [comment]
Any updates on this?

**Comment by miaojiang** [comment]
@RupengLiu please take a look.

**Comment by Radamonas** [comment]
Was this issue resolved on v 2.18.0?

**Comment by pebarrer** [comment]
I am seeing this issue in Azure CLI via Cloudshell .

az version
{
  "azure-cli": "2.19.0",
  "azure-cli-core": "2.19.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5"
  }
}

**Comment by VirtualFox0** [comment]
I am seeing this issue in Azure CLI (on Mac) version **2.17.1**, **2.19.1** and Azure Cloud Shell Azure CLI version **2.19.0**.

**Comment by ericfran** [comment]
any update ?

**Comment by yonzhan** [comment]
API Management service team should look into this issue.

**Comment by RupengLiu** [comment]
checking....

**Comment by RupengLiu** [comment]
pr submitted, fix expected to be next release
