### ISSUE TITLE
Response doesn't help/make sense: az network application-gateway private-link add

### ISSUE THREAD

**Issue by jmeadowcroft** [Azure/azure-cli#16279]
**Describe the bug**
I get the message "Subnet duplicates" when running the below command. This message does not make sense to me, as the subnet I am specifying is in the vnet that the app gateway is connected to, and the private link subnet has no other attached resources.
az network application-gateway private-link add --frontend-ip {my-existing-frontend-ip} --name {new-private-link-name} --subnet {subnet-name} --gateway-name {app-gateway-name} --resource-group {resource-group-name}

**To Reproduce**
Execute the command above

**Expected behavior**
Add a private link

**Environment summary**
az cli version: 2.16.0

**Comment by yonzhan** [comment]
network

**Comment by taherkhan30** [comment]
hello, i have the same issue, is there any update to this?

**Comment by kairu-ms** [comment]
That's because the subnet should not belong to the subnets of  app-gateway's vnet.

**Comment by haraldfianbakken** [comment]
> That's because the subnet should not belong to the subnets of app-gateway's vnet.

The docs specifies that it should here: 
https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/private-link?view=azure-cli-latest

If you specify a different subnet in the same Vnet - you will get a different error (as there's no way currently to give it a prefix for creating a new subnet) -  and there's no obvious option for referring to a subnet outside the AppGW VNet.

**Comment by kairu-ms** [comment]
This is an example. https://github.com/Azure/azure-cli/blob/aad1e1801262eaf13615f7170f89a485627ed0f8/src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py#L1342-L1356
