### ISSUE TITLE
Add new exception type to carry HTTP status code 

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1627]
In the pull request #1617 there is a try-catch structure relies on checking if the error message contains a specific string to determine the source of the exception. The process can be more deterministic if the exception, which triggered by an error coded HTTP response, carries the HTTP response status code.

The current `CLIError` exception is too simple to carry any information when the error is triggered by an errored response.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
