### ISSUE TITLE
WebApp:Error while using az webapp command

### ISSUE THREAD

**Issue by oshz** [Azure/azure-cli#16277]
## Describe the bug

**Command Name**
`az webapp list`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp list`

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
webapp

**Comment by calvinsID** [comment]
Hi @oshz, can you please try using the latest CLI? I could not repro using CLI 2.16.0

**Comment by ThejaChoudary** [comment]
@oshz Can you please let us if your still facing the issue with the latest CLI?

**Comment by oshz** [comment]
@calvinsID  @ThejaChoudary  working fine now on version 2.19.1 , Thanks
