### ISSUE TITLE
Add a new parameter named web-categories to FirewallPolicy Application Rule

### ISSUE THREAD

**Issue by girishmotwani** [Azure/azure-cli#16282]
Resource Provider
Network (NRP)

Description of Feature or Work Requested
Need to add a new parameter named "web-categories" to the commands:
az network firewall application-rule create/update.

This will be a list of strings.

Also, user can specify either TargetFQDNs, FqdnTag or WebCategories.
There is another issue open to add "TargetURLs" as another parameter to same command. With that too, it will be only 1 of the 4 fields allowed. Here is the issue for reference: #15377

Minimum API Version Required
2020-07-01

Swagger Link
Azure/azure-rest-api-specs#11049

Powershell Link
https://github.com/Azure/azure-powershell/pull/13695

Target Date
1/21/2021

**Comment by yonzhan** [comment]
network

**Comment by girishmotwani** [comment]
Wondering if you could share ETA for this issue?

**Comment by msyyc** [comment]
We'll try to finish it before 2021/2/1. Is it OK?
