### ISSUE TITLE
az ad app create cannot set SAML token optional claims

### ISSUE THREAD

**Issue by matteocalabro-tomtom** [Azure/azure-cli#16288]
## Describe the bug

**Command Name**
`az ad app create`

**Errors:**
`saml2token` is discarded from optional claims

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a `manifest.json` with a `saml2Token` entry:
  ```
  {
    "idToken": [
      {
        "name": "email",
        "source": null,
        "essential": true
      }
    ],
    "accessToken": [
      {
        "name": "email",
        "source": null,
        "essential": true
      }
    ],
    "saml2Token": [
      {
        "name": "email",
        "source": null,
        "essential": true
      }
    ]
  }
  ```
- `az ad app create --display-name {} --identifier-uris {} --available-to-other-tenants={} --homepage {} --reply-urls {} {} --optional-claims {}`

## Expected Behavior
The output should be something like:

```
"optionalClaims": {
    "accessToken": [
        {
          "additionalProperties": [],
          "essential": false,
          "name": "email",
          "source": null
        }
      ],
      "idToken": [
        {
          "additionalProperties": [],
          "essential": false,
          "name": "email",
          "source": null
        }
      ],
      "saml2Token": [
        {
          "additionalProperties": [],
          "essential": false,
          "name": "email",
          "source": null
        }
      ]
  },
```

instead, we have `"saml2Token": []`

## Environment Summary
```
macOS-11.1-x86_64-i386-64bit
Python 3.8.6
Installer: HOMEBREW

azure-cli 2.16.0

```
## Additional Context
The function [_build_optional_claims](https://github.com/Azure/azure-cli/blob/4bed6cca3ebb746d0f8bc2b44c75f0d0d2f7ed15/src/azure-cli/azure/cli/command_modules/role/custom.py#L1140) only considers `idToken` and `accessToken`, completely ignoring `saml2Token` settings?

**Comment by fengzhou-msft** [comment]
@jiasli please take a look.

**Comment by jiasli** [comment]
As we currently don't have bandwidth maintaining `az ad` which still uses the deprecated Azure Active Directory Graph, please consider using `az rest` to call Microsoft Graph directly. (#12946)
