### ISSUE TITLE
Interesting behavior of az upgrade...

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#16283]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Not entirely sure what the error is...

![image](https://user-images.githubusercontent.com/30876406/102285582-6f459580-3eeb-11eb-9678-aae8e876fbc0.png)

**To Reproduce**
See above

**Expected behavior**
Not sure what to expect either.. but wasn't able to act on the error really

but interesting the version was upgraded..?
![image](https://user-images.githubusercontent.com/30876406/102285590-74a2e000-3eeb-11eb-9d6e-c5eda9778968.png)

**Environment summary**

**Additional context**
Tried to run az upgrade again but have no feedback on the operation... 
![image](https://user-images.githubusercontent.com/30876406/102285605-7c628480-3eeb-11eb-9c2a-d240c65cbe0b.png)

Not too sure what my takeaway should be with the operation.....
that the operation succeeded but no confirmation..(?)

**Comment by yungezz** [comment]
good finding. @fengzhou-msft could you pls help to have a look? thanks

**Comment by fengzhou-msft** [comment]
The issue is caused when updating the extensions. The storage account hosting the extension index is not so stable recently, we're migrating it to AME subscription. A message of `Upgrading extensions` is added now in `az upgrade` before checking extensions.

**Comment by fengzhou-msft** [comment]
Added retry when fetching extension index to reduce this error caused by unstable network.
