### ISSUE TITLE
Filtering in query using the '||' (OR) operator causes errors 

### ISSUE THREAD

**Issue by bstlaurentnz** [Azure/azure-cli#16284]
## Describe the bug
A query using the || fails causing error AADSTS50076 where a the same query with && works as expected. 

**Command Name**
`az storage account list --query "[?type=='Microsoft.Storage/storageAccounts'||name=='zprodsqllog'].{Name:name}"`

**Errors:**
```
AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.
Trace ID: 4b132462-06d0-49f1-b5f4-82d91c483b00
Correlation ID: 210fb6bd-1d11-4d65-9e37-1011b9441b41
Timestamp: 2020-12-16 02:03:14Z

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage account list --query "[?type=='Microsoft.Storage/storageAccounts'&&name=='zprodsqllog'].{Name:name}"`

this outputs the following:

```
[
  {
    "Name": "zprodsqllog"
  }
]
```
- az storage account list --query "[?type=='Microsoft.Storage/storageAccounts'||name=='zprodsqllog'].{Name:name}"

this outputs the error mentioned above. 
## Expected Behavior
A JSON list of all the names of the storage accounts of which there are 100 or so

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.6
Installer: PIP

azure-cli 2.16.0

Extensions:
interactive 0.4.4

```

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @bstlaurentnz, you get the error because when `||` takes effect, you will get more storage account to list. But it seems you cannot access some of them due to AAD requirement.
Please check your AAD role with admin and try to use multi-factor authentication to access.

**Comment by Juliehzl** [comment]
@jiasli  for AAD issue.

**Comment by jiasli** [comment]
`--query` has nothing to do with the REST API call and only works on the **response** of the REST API call. So the issue is not related to `&&` or `||`.

> AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.

The error means there is some configuration change on the tenant. You may simply run `az login` to re-authenticate and the command will work as expected.
