### ISSUE TITLE
Disable _update_latest_from_github in tests

### ISSUE THREAD

**Issue by stan-sz** [Azure/azure-cli#16307]
## Describe the bug

When calling az cli in tests and asserting on each outbound call, we see that `_update_latest_from_github` gets called and there is now way to disable that behavior. 

**Errors:**
There's an outbound connection to https://example.org from `check_connectivity`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

In a simple pytest have:
```python
from azure.cli.core import cloud, get_default_cli
az_cli = get_default_cli()
```

this will call `_update_latest_from_github`.

## Expected Behavior
Have a way (env variable?) to disable reaching out to internet.
There is a way to disable telemetry:
```python
os.environ['AZURE_CORE_COLLECT_TELEMETRY'] = 'false'
```
but neither of the two below works:
```python
os.environ['AZURE_AUTO-UPGRADE_ENABLE'] = 'false'
os.environ['AZURE_AUTO_UPGRADE_ENABLE'] = 'false'
```

## Environment Summary
```
Windows-10
Python 3.6.8
Installer: MSI

azure-cli 2.12.1 *

Extensions:
application-insights 0.1.11
azure-devops 0.18.0
blueprint 0.2.1
interactive 0.4.4

```

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to have a look? thanks

**Comment by stan-sz** [comment]
Using https://github.com/Azure/azure-cli/blob/b5cc60ab5a00591bc0441ad348f8e7e9df26b2f3/src/azure-cli-core/azure/cli/core/mock.py#L9 the unit tests can now pass without reaching out to github. However, the uncaught exception message still uncovered a bug in an unclosed requests.Session: https://github.com/Azure/azure-cli/blob/625ccad030a7583ba9a1d2633ff812ece70e924c/src/azure-cli-core/azure/cli/core/util.py#L784. The fix would be to wrap this into a `with` block.
