### ISSUE TITLE
unmanaged error message when upload resource to blob container

### ISSUE THREAD

**Issue by alperc92** [Azure/azure-cli#16303]
az storage blob upload -f "<path>" -c <container> --name <name>" --connection-string <connection string>

**Command Name**
`az storage blob upload`

**Errors:**
```
[Errno 13] Permission denied: '.'
Traceback (most recent call last):
Temp\pip-install-wl9gly17\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 566, in execute
azure\cli\core\commands\__init__.py, ln 624, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 615, in _run_job
azure\cli\command_modules\storage\__init__.py, ln 240, in new_handler
azure\cli\command_modules\storage\__init__.py, ln 183, in handler
azure\cli\core\commands\__init__.py, ln 594, in _run_job
azure\cli\core\commands\__init__.py, ln 303, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 470, in default_command_handler
cli\command_modules\storage\operations\blob.py, ln 352, in upload_blob
cli\command_modules\storage\operations\blob.py, ln 345, in upload_block_blob
multiapi\storage\v2018_03_28\blob\blockblobservice.py, ln 447, in create_blob_from_path
PermissionError: [Errno 13] Permission denied: '.'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload -f {} -c {} --name {} --connection-string {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.67

```

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @alperc92, could you make sure you could read for the target file? And what is your value for `-f`? is it a valid file?

https://stackoverflow.com/questions/36434764/permissionerror-errno-13-permission-denied/36469464

**Comment by yonzhan** [comment]
Hi @alperc92, any update?
