### ISSUE TITLE
“az network vnet peering create” results in “BadRequestError: Cannot parse the request.” 

### ISSUE THREAD

**Issue by Qq20180503** [Azure/azure-cli#16316]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.16.0

**Describe the bug**
"az network vnet peering create” results in “BadRequestError: Cannot parse the request.”  with CLI version 2.16.0 

**To Reproduce**

```
az group create --name myResourceGroup --location eastus
az network vnet create \
  --name myVirtualNetwork1 \
  --resource-group myResourceGroup \
  --address-prefixes 10.0.0.0/16 \
  --subnet-name Subnet1 \
  --subnet-prefix 10.0.0.0/24
az network vnet create \
  --name myVirtualNetwork2 \
  --resource-group myResourceGroup \
  --address-prefixes 10.1.0.0/16 \
  --subnet-name Subnet1 \
  --subnet-prefix 10.1.0.0/24
# Get the id for myVirtualNetwork1.
vNet1Id=$(az network vnet show \
  --resource-group myResourceGroup \
  --name myVirtualNetwork1 \
  --query id --out tsv)

# Get the id for myVirtualNetwork2.
vNet2Id=$(az network vnet show \
  --resource-group myResourceGroup \
  --name myVirtualNetwork2 \
  --query id \
  --out tsv)
az network vnet peering create \
  --name myVirtualNetwork1-myVirtualNetwork2 \
  --resource-group myResourceGroup \
  --vnet-name myVirtualNetwork1 \
  --remote-vnet $vNet2Id \
  --allow-vnet-access \
  --out tsv
```

![image](https://user-images.githubusercontent.com/38937369/102579622-c9d33180-4137-11eb-88d6-3547137a5de9.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/38937369/102579838-48c86a00-4138-11eb-944f-56205f965826.png)

**Environment summary**

It does not work with Azure cloud shell or local shell with azure-CLI 2.16.0 but it can work well with local CLI version 2.11.1

**Additional context**

 Is there any bug in the Azure cli version 2.16.0  ?

For more details, refer to the StackOverflow link. https://stackoverflow.com/questions/65330470/az-network-vnet-peering-create-results-in-badrequesterror-cannot-parse-the-r/65333529#65333529

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
same question with https://github.com/Azure/azure-cli/issues/16211, https://github.com/Azure/azure-cli/issues/16235.
The bug will be fixed in new CLI version (about 2020/12/31)

**Comment by yonzhan** [comment]
duplicated
