### ISSUE TITLE
"az synapse notebook create" fails on simple example

### ISSUE THREAD

**Issue by genegc** [Azure/azure-cli#16311]
## Describe the bug

**Command Name**
`az synapse notebook create`

**Errors:**
```
BadRequestError: Operation returned an invalid status 'Bad Request'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az synapse notebook create --workspace-name {} --name {} --file {} --debug`

## Expected Behavior
It should create the notebook in the specified synapse workspace

## Environment Summary
```
Linux-4.15.0-1102-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.16.0

Extensions:
ai-examples 0.2.5

```
## Additional Context
Here is the output:
[log.txt](https://github.com/Azure/azure-cli/files/5711187/log.txt)

Here is the json for the notebook:
[testnotebook.txt](https://github.com/Azure/azure-cli/files/5711189/testnotebook.txt)

**Comment by yonzhan** [comment]
synapse

**Comment by idear1203** [comment]
BadRequest usually means there are errors in the payload. Could you please provide the definition file?

**Comment by genegc** [comment]
The definition file is provided above - within the "Additional Context" section

**Comment by genegc** [comment]
I'm still unable to create a notebook through az cli.
I've included the info you have asked for - is there any update on this?
Can you provide an example that works so that I can see what I'm doing wrong?

**Comment by genegc** [comment]
I have also verified that I can do an export of a notebook successfully, but when I try to then do an import with the json that was just exported, I still get the 'Bad Request' error.

**Comment by edyoung** [comment]
This may be an issue with the authentication endpoint that Cloud Shell uses. Can you try running `az login` then rerun your command?

**Comment by genegc** [comment]
Using az login did not work - I get the same result.
I also tried to use the json from the [rest api example](https://docs.microsoft.com/en-us/rest/api/synapse/data-plane/notebook/createorupdatenotebook), but I get the same result.

Then I tried just using the rest api directly like this (where $body was set to valid json):
`az rest --method PUT --uri https://syn-oea-cisd3west9.dev.azuresynapse.net/notebooks/exampleNotebook?api-version=2019-06-01-preview --body $body --debug`
and I got this error:
`cli.azure.cli.core.azclierror: Unauthorized({"code":"BearerTokenNotFound","message":"BearerToken not found in request"})`

Then I noticed [this note from the docs:](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az_rest)
`This command automatically authenticates using the logged-in credential: If Authorization header is not set, it attaches header Authorization: Bearer <token>, where <token> is retrieved from AAD. The target resource of the token is derived from --url if --url starts with an endpoint from az cloud show --query endpoints. You may also use --resource for a custom resource.`

I tried specifying the resource and got another error.

Can you provide details of how this can be made to work with the rest api?

**Comment by perber** [comment]
I also had a similar issue. It helped me to upgrade az cli to version 2.25.0.

**Comment by genegc** [comment]
This is working now.
I've verified by first doing an export of a notebook and then performing a create (and it also works with import).
Here are the commands I used:
`az synapse notebook export --workspace-name syn-ggtest1 --name mynotebook --output-folder ./`
`az synapse notebook import --workspace-name syn-ggtest1 --name mynotebook --file @./mynotebook.ipynb`

A few things to be aware of (this needs to be added to the docs):

1. The notebook will only be visible in synapse studio if you're in "live mode". If your workspace is connected to a git repo, you need to import a notebook by adding the json file to the "notebook" folder in your repo.
2. You have to use the .ipynb format (this is the format you get when you do an export via cli) to do the import/create, not the .json (this is the format you get when you commit to git)
3. The notebook will created at the root level in Synapse studio (the "folder" property in the .ipynb is ignored)

**Comment by prapanw** [comment]
I am still seeing the `400 Bad Request` issue where I am not able to import the notebook using the same content I got when I exported it.
