### ISSUE TITLE
Erroneous "Check your internet connection" message

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-cli#16310]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When running `az --version` returns "Unable to check if your CLI is up-to-date. Check your internet connection." while connected to the internet.

**To Reproduce**
1. Go to speedtest.net
2. Start a speedtest
3. Run `az --version`
4. Receive following response:
```
azure-cli                         2.8.10

command-modules-nspkg              2.0.3
core                              2.8.10
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\charris\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Unable to check if your CLI is up-to-date. Check your internet connection.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

**Expected behavior**
I expected to find out that my version was up-to-date or that I needed to upgrade.

**Environment summary**
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI
azure-cli 2.8.10
Shell Type: PowerShell

**Additional context**

**Comment by yungezz** [comment]
hi @fengzhou-msft we may need consider more concern case on this. could you pls have a look? thanks

**Comment by fengzhou-msft** [comment]
@charris-msft does the `Unable to check if your CLI is up-to-date. Check your internet connection.`  message always show up for you? Can you run `az --version --debug` to check the error trace before the output of the version information?

**Comment by charris-msft** [comment]
@fengzhou-msft 
After manually upgrading to a later version the problem no longer occurs. However, I have included the debug info below that you requested.

❯(.venv)  az --version
azure-cli                         2.17.1 *

core                              2.17.1 *
telemetry                          1.0.6

Extensions:
db-up                              0.2.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\charris\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 2 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
charris@CHARRISSL1   .venv  ~\source\FlaskMSAL                                                             [09:27]
❯(.venv)  az --version --debug
Command arguments: ['--version', '--debug']
Event: Cli.PreExecute []
urllib3.connectionpool : Starting new HTTPS connection (1): example.org:443
urllib3.connectionpool : https://example.org:443 "HEAD / HTTP/1.1" 200 0
Connectivity check: 0.212642 sec
urllib3.connectionpool : Starting new HTTPS connection (1): raw.githubusercontent.com:443
urllib3.connectionpool : https://raw.githubusercontent.com:443 "GET /Azure/azure-cli/master/src/azure-cli-core/setup.py HTTP/1.1" 200 1403
urllib3.connectionpool : Starting new HTTPS connection (1): raw.githubusercontent.com:443
urllib3.connectionpool : https://raw.githubusercontent.com:443 "GET /Azure/azure-cli/master/src/azure-cli-telemetry/setup.py HTTP/1.1" 200 682
azure-cli                         2.17.1 *

core                              2.17.1 *
telemetry                          1.0.6

Extensions:
db-up                              0.2.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\charris\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 2 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03423D68>]
Command ran in 1.732 seconds (init: 1.090, invoke: 0.642)
Suppress exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-wcxsakwf\azure\cli\__main__.py", line 60, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-wcxsakwf\azure\cli\__main__.py", line 53, in <module>
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\decorators.py", line 74, in _wrapped_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\telemetry.py", line 292, in set_custom_properties
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\telemetry.py", line 169, in <lambda>
KeyError: 'x-ms-client-request-id'

telemetry.save : Save telemetry record of length 2684 in cache
telemetry.check : Negative: The C:\Users\charris\.azure\telemetry.txt was modified at 2021-01-28 09:27:43.597880, which in less than 600.000000 s

**Comment by derekantrican** [comment]
I'm also getting the "internet connection" message every time I run `az --version` on one of my machines. Here is the output of `az --version --debug`:

```
F:\o\Git\src>az --version --debug
Command arguments: ['--version', '--debug']
Event: Cli.PreExecute []
urllib3.connectionpool : Starting new HTTPS connection (1): example.org:443
urllib3.connectionpool : https://example.org:443 "HEAD / HTTP/1.1" 200 0
Connectivity check: 0.11478029999999995 sec
Running: ['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'pip', 'search', 'azure-cli', '-vv', '--disable-pip-version-check', '--no-cache-dir', '--retries', '0']
Extensions directory: 'C:\Users\deantric\.azure\cliextensions'
Extensions directory: 'C:\Users\deantric\.azure\cliextensions'
azure-cli                         2.0.70

command-modules-nspkg               2.0.3
core                              2.0.70
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
azure-devops                      0.17.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\deantric\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Unable to check if your CLI is up-to-date. Check your internet connection.
Event: Cli.PostExecute []
Suppress exception 'x-ms-client-request-id'
telemetry.save : Save telemetry record of length 2302 in cache
telemetry.check : Negative: The C:\Users\deantric\.azure\telemetry.txt was modified at 2023-12-15 11:26:26.941571, which in less than 600.000000 s
command ran in 2.025 seconds.
```
