### ISSUE TITLE
`az keyvault certificate download` crashes on Python 3.9

### ISSUE THREAD

**Issue by christianfosli** [Azure/azure-cli#16318]
**Describe the bug**
Trying to download a certificate with the `az certificate download` command, on azure cli 2.16 and python 3.9, crashes with the error **module 'base64' has no attribute 'encodestring'**

**To Reproduce**

* Have python 3.9 and azure cli 2.16

* Have a keyvault _mykeyvault_ with a certificate _mycert_

* `az keyvault certificate download -n mycert --vault-name mykeyvault --file mycert.crt`

**Expected behavior**

The certificate should be downloaded and stored as `mycert.txt`

**Environment summary**

* Install Method: dnf package manager with the https://packages.microsoft.com/yumrepos/azure-cli yum repo

* CLI Version:

  ```console
  $ az --version
  azure-cli                         2.16.0

  core                              2.16.0
  telemetry                          1.0.6

  Extensions:
  azure-devops                      0.18.0

  Python location '/usr/bin/python3'
  Extensions directory '/home/cfosli/.azure/cliextensions'

  Python (Linux) 3.9.0 (default, Oct  6 2020, 00:00:00) 
  [GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]

  Legal docs and information: aka.ms/AzureCliLegal

  Your CLI is up-to-date.
  ```

* OS version: Fedora Linux 33  (which comes with Python 3.9 preinstalled)

* Shell type: Bash

**Additional context**

The [Python 3.9 release notes](https://docs.python.org/3/whatsnew/3.9.html#removed) seem to describe the reason and fix quite well:

> base64.encodestring() and base64.decodestring(), aliases deprecated since Python 3.1, have been removed: use 
 base64.encodebytes() and base64.decodebytes() instead. (Contributed by Victor Stinner in bpo-39351.)

**Comment by yungezz** [comment]
hi @houk-ms could you pls have a look? thanks

**Comment by christianfosli** [comment]
So this is a customer facing bug affecting those using Python 3.9+ (default in Fedora Linux and other distros). And it has a simple one-line fix which I opened a PR for more than a month ago.

Any ETA on reviewing this?
