### ISSUE TITLE
[Storage] File copy source convenience parameters don't work

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1631]
When copying a file, if you specify the `--source-share` and `--source-path` parameters, the constructed URI is incorrect and the copy operation eventually fails with the error "Could not verify the copy source within the specified time."

You can obtain the correct URI using the `az storage file url ...` command and use the `--source-uri` parameter until this issue is fixed.

The problem is that in the constructed URI, the pattern is:
{protocol}://{account}.**share**.core.windows.net/{share}/{path}

But it __should__ be:
{protocol}://{account}.**file**.core.windows.net/{share}/{path}

**Comment by troydai** [comment]
We need a reverse version of this: https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/storage_url_helpers.py

**Comment by tjprescott** [comment]
Since the "old" copy commands will likely be deprecated, I created a PR that fixes the issue and expanded the test to guard against the regression.
