### ISSUE TITLE
Typo "Azure function app"→"Azure Function App"

### ISSUE THREAD

**Issue by hyoshioka0128** [Azure/azure-cli#16323]
Typo "Azure function app"→"Azure Function App"

https://docs.microsoft.com/en-us/cli/azure/functionapp/devops-pipeline?view=azure-cli-latest

![devops-pipeline](https://user-images.githubusercontent.com/40815708/102701229-20578180-4298-11eb-9ed6-1f5be3c1485a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3162209-04eb-aafb-a830-9edd55b584b3
* Version Independent ID: d1aad587-01b8-16c5-49f6-78cc85ab23cc
* Content: [az functionapp devops-pipeline](https://docs.microsoft.com/en-us/cli/azure/functionapp/devops-pipeline?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/functionapp/devops-pipeline.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/functionapp/devops-pipeline.yml)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
functionapp

**Comment by apawast** [comment]
@ggailey777 what is our guidance on the Functions naming convention?
