### ISSUE TITLE
Errors during update VMSS with AGW backend pool

### ISSUE THREAD

**Issue by tonytangau** [Azure/azure-cli#16324]
## Error during update VMSS
Try to use `az vmss update` to attach VMSS to an existing application gateway backend pool, as suggested [here](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-upgrade-scale-set#update-the-load-balancer-for-your-scale-set).

`az vmss update --resource-group myResourceGroup --name myScaleSet --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].ApplicationGatewayBackendAddressPools '{"id": "/subscriptions/{subscriptionId}/resourceGroups/myResourceGroup/providers/Microsoft.Network/applicationGateways/{applicationGatewayName}/backendAddressPools/{applicationGatewayBackendPoolName}"}'`

The command failed with errors below.

**Command Name**
`az vmss update`

**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-laos76cl\msrest\serialization.py, ln 1416, in _deserialize
Temp\pip-unpacked-wheel-laos76cl\msrest\serialization.py, ln 1181, in rest_key_case_insensitive_extractor
Temp\pip-unpacked-wheel-laos76cl\msrest\serialization.py, ln 1210, in attribute_key_case_insensitive_extractor
...
Temp\pip-unpacked-wheel-laos76cl\msrest\serialization.py, ln 1210, in attribute_key_case_insensitive_extractor
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss update --resource-group {} --name {} --add {} {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.13.0 *

Extensions:
interactive 0.4.3
spring-cloud 0.2.4

```

**Comment by yungezz** [comment]
hi @qwordy , could you pls help to have a look? thanks.

**Comment by qwordy** [comment]
I have two similar issues. I'll prioritize it.

**Comment by yungezz** [comment]
close this one since it's tracked in https://github.com/Azure/azure-cli/issues/16324
