### ISSUE TITLE
WebApp: No module named 'decorator'

### ISSUE THREAD

**Issue by Luck547** [Azure/azure-cli#16325]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --sku {} --name {}`

## Environment Summary
```
Linux-5.8.0-33-generic-x86_64-with-glibc2.32
Python 3.8.6
Installer: PIP

azure-cli 2.10.1

Extensions:
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/16277. hi @Luck547 could you pls try uninstall and install latest Azure CLI to see if it resolves the issue?
