### ISSUE TITLE
Improvements to context/account/clouds

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1633]
This feature is not well documented and is not necessarily straightforward to use.
This is due to wanting to maintain compatibility with xplat CLI whilst also exposing new functionality.

Related to this question - https://github.com/Azure/azure-cli/issues/1559#issuecomment-267110057.

**Comment by johanste** [comment]
My suggestion is to:

- Remove the context commands for now
- Ensure that we have an environment variable I can set to indicate which cloud I'm currently using

When we add profile support:

- Add a default profile attribute to the cloud configuration
- Ensure that we have an environment variable I can set to override the currently selected profile
