### ISSUE TITLE
allow to run shell commands in "az interactive"

### ISSUE THREAD

**Issue by ozbillwang** [Azure/azure-cli#16347]
**Is your feature request related to a problem? Please describe.**

no
**Describe the solution you'd like**

when run command in `az interactive`, it only allows az commands. This would be an inconvenience. 

For example, I'd like to set a variable and using in az commands, it gives me error messages as below

```
az>> ADMIN_USER=adminuser
CommandNotFoundError: 'ADMIN_USER=adminuser' is misspelled or not recognized by the system.
Still stuck? Run 'az --help' to view all commands or go to 'https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest' to learn more
az>> exit
```

Could we treat any commands if not start with `az `, as shell commands?

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
interactive

**Comment by ozbillwang** [comment]
Seems this feature is ready. 

You can run shell commands without leaving interactive mode using #[cmd].
```
az>> #dir
```
https://docs.microsoft.com/en-us/cli/azure/interactive-azure-cli#bash-commands
