### ISSUE TITLE
M Series SKUs not being returned in "az vm list-skus"

### ISSUE THREAD

**Issue by grtn316** [Azure/azure-cli#16344]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I am trying to return all available SKUs and their zones and noticed the M series is missing.

**To Reproduce**
`az vm list-skus --location eastus2 --subscription "<SubName>" --query "[?contains(name,'M')]" -o table`

**Expected behavior**
Return a list of M series SKUs like: Standard_M16-8ms.

**Environment summary**
Ubuntu 18.04
azure-cli                         2.16.0
core                              2.16.0
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/home/david/.azure/cliextensions'
Python (Linux) 3.6.10 (default, Dec  4 2020, 12:36:15) 
[GCC 7.5.0]
Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.

**Additional context**
This command works:
`az vm list-skus --location eastus2 --query "[?family=='standardEDSv4Family' && resourceType=='virtualMachines'].{Name:name, Zones:locationInfo[].zones[]}"`

This command does not:
`az vm list-skus --location eastus2 --query "[?family=='standardMSFamily' && resourceType=='virtualMachines'].{Name:name, Zones:locationInfo[].zones[]}"`

**Comment by yungezz** [comment]
HI @grtn316 Is M series skus returned in eastus2 by rest API? @qwordy could you pls have a look is this service response?

**Comment by qwordy** [comment]
@grtn316  My results. Could you remove `--query` and see if the expected size exists?
```
$ az vm list-skus --location eastus2 --query "[?contains(name,'M')]" -o table
ResourceType      Name                    Family              Tier      Size
----------------  ----------------------  ------------------  --------  -------------
hostGroups/hosts  MSm-Type1               standardMSFamily
hostGroups/hosts  MS-Type1                standardMSFamily
hostGroups/hosts  MSv2-Type1              standardMSv2Family
hostGroups/hosts  MSmv2-Type1             standardMSv2Family
virtualMachines   Standard_M64            standardMSFamily    Standard  M64
virtualMachines   Standard_M64m           standardMSFamily    Standard  M64m
virtualMachines   Standard_M128           standardMSFamily    Standard  M128
virtualMachines   Standard_M128m          standardMSFamily    Standard  M128m
virtualMachines   Standard_M8-2ms         standardMSFamily    Standard  M8-2ms
virtualMachines   Standard_M8-4ms         standardMSFamily    Standard  M8-4ms
virtualMachines   Standard_M8ms           standardMSFamily    Standard  M8ms
virtualMachines   Standard_M16-4ms        standardMSFamily    Standard  M16-4ms
virtualMachines   Standard_M16-8ms        standardMSFamily    Standard  M16-8ms
virtualMachines   Standard_M16ms          standardMSFamily    Standard  M16ms
virtualMachines   Standard_M32-8ms        standardMSFamily    Standard  M32-8ms
virtualMachines   Standard_M32-16ms       standardMSFamily    Standard  M32-16ms
virtualMachines   Standard_M32ls          standardMSFamily    Standard  M32ls
virtualMachines   Standard_M32ms          standardMSFamily    Standard  M32ms
virtualMachines   Standard_M32ts          standardMSFamily    Standard  M32ts
virtualMachines   Standard_M64-16ms       standardMSFamily    Standard  M64-16ms
virtualMachines   Standard_M64-32ms       standardMSFamily    Standard  M64-32ms
virtualMachines   Standard_M64ls          standardMSFamily    Standard  M64ls
virtualMachines   Standard_M64ms          standardMSFamily    Standard  M64ms
virtualMachines   Standard_M64s           standardMSFamily    Standard  M64s
virtualMachines   Standard_M128-32ms      standardMSFamily    Standard  M128-32ms
virtualMachines   Standard_M128-64ms      standardMSFamily    Standard  M128-64ms
virtualMachines   Standard_M128ms         standardMSFamily    Standard  M128ms
virtualMachines   Standard_M128s          standardMSFamily    Standard  M128s
virtualMachines   Standard_M208ms_v2      standardMSv2Family  Standard  M208ms_v2
virtualMachines   Standard_M208s_v2       standardMSv2Family  Standard  M208s_v2
virtualMachines   Standard_M416s_v2       standardMSv2Family  Standard  M416s_v2
virtualMachines   Standard_M416ms_v2      standardMSv2Family  Standard  M416ms_v2
virtualMachines   Standard_M416-208s_v2   standardMSv2Family  Standard  M416-208s_v2
virtualMachines   Standard_M416-208ms_v2  standardMSv2Family  Standard  M416-208ms_v2
```

**Comment by grtn316** [comment]
@qwordy When removing the filter, I still do not see the SKUs.

- I can see them when I run az vm list-sizes -l eastus2
- I can select them from the portal when configuring a VM

When I run: 

`$ az vm list-usage -l eastus2 --query "[?contains(localName,'M')]" -o table

<pre>CurrentValue    Limit    LocalName
--------------  -------  ------------------------------
4               25000    Virtual Machines
0               2500     Virtual Machine Scale Sets
0               128      Standard MS Family vCPUs
0               0        Standard MSv2 Family vCPUs
0               50000    Standard Storage Managed Disks
22              50000    Premium Storage Managed Disks</pre>
`

I see available cores under the MS Family.

**Comment by grtn316** [comment]
@qwordy Any additional thoughts?

**Comment by qwordy** [comment]
It indicates that the REST API `GET subscriptions//providers/Microsoft.Compute/skus` does not return the SKU you expect. Can you add `--debug` to the command and see the specific REST API invoked.

**Comment by grtn316** [comment]
Looks like the family name got updated and is now showing up.

`$ az vm list-skus --location eastus2 --query "[?contains(name,'M')]" -o table
ResourceType      Name                  Family                    Tier      Size
----------------  --------------------  ------------------------  --------  -----------
hostGroups/hosts  MSm-Type1             standardMSFamily
hostGroups/hosts  MS-Type1              standardMSFamily
hostGroups/hosts  MSv2-Type1            standardMSv2Family
hostGroups/hosts  MSmv2-Type1           standardMSv2Family
virtualMachines   Standard_M32ms_v2     standardMSmallv2Family    Standard  M32ms_v2
virtualMachines   Standard_M64ms_v2     standardMSmallv2Family    Standard  M64ms_v2
virtualMachines   Standard_M64s_v2      standardMSmallv2Family    Standard  M64s_v2
virtualMachines   Standard_M128ms_v2    standardMSmallv2Family    Standard  M128ms_v2
virtualMachines   Standard_M128s_v2     standardMSmallv2Family    Standard  M128s_v2
virtualMachines   Standard_M192ims_v2   standardMISmallv2Family   Standard  M192ims_v2
virtualMachines   Standard_M192is_v2    standardMISmallv2Family   Standard  M192is_v2
virtualMachines   Standard_M32dms_v2    standardMDSmallv2Family   Standard  M32dms_v2
virtualMachines   Standard_M64dms_v2    standardMDSmallv2Family   Standard  M64dms_v2
virtualMachines   Standard_M64ds_v2     standardMDSmallv2Family   Standard  M64ds_v2
virtualMachines   Standard_M128dms_v2   standardMDSmallv2Family   Standard  M128dms_v2
virtualMachines   Standard_M128ds_v2    standardMDSmallv2Family   Standard  M128ds_v2
virtualMachines   Standard_M192idms_v2  standardMIDSmallv2Family  Standard  M192idms_v2
virtualMachines   Standard_M192ids_v2   standardMIDSmallv2Family  Standard  M192ids_v2`
