### ISSUE TITLE
Assign Fault Domain during VM Create

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#16346]
**Resource Provider**

Compute RP

**Description of Feature or Work Requested**

When creating a virtual machine that is added to a VMSS flex, customer can now specific the fault domain where they would like the VM to land 

VMSS Maximum FD count per region available via SKUs API 

/skus 

Type = availabilitySet 

Name = Aligned 

Capabilities[0].name=MaximumPlatformDomainCount.value 

 
 
 

VM must be in a VMSS flex with FDCount > 1 

FD is 0-indexed, based on FD Count of the VMSS Flex 

If VMSS FDCount = 3, V can have FD of 0,1,2 

Api-version 2020-12-01 

This property cannot be updated after VM create 

https://microsoft.sharepoint.com/:w:/t/vmssvmorchestrationmode/Edo-u2Trix1DgPrk2DLl3ncBFLTjUMs04p8PM4lBTFP4mw?e=DgZfNc

**Minimum API Version Required**

2020-12-01
**Swagger Link**

**Target Date**

1/13

**Comment by yungezz** [comment]
hi @qwordy could you pls take care of this? thanks.

**Comment by qwordy** [comment]
Hi Jerry, what's the current status of 2020-12-01. It is not in master branch yet.
