### ISSUE TITLE
Azure CLI unable to create portal dashboards from templates

### ISSUE THREAD

**Issue by lujinlou** [Azure/azure-cli#16356]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.16.0

**Describe the bug**
When I run the  `az portal dashboard create` command to create an Azure Portal Dashboard, it reports the error message >>> 
><_io.TextIOWrapper name='C:\\Users\\kevinliu2\\Downloads\\TestDash.json' mode='r' encoding='cp1252'> does not contain the property 'lenses'

**To Reproduce**
1. Create a Json file or Export the Dashboards Template json in Azure Portal.
The sample Json code url: https://docs.microsoft.com/en-us/azure/azure-portal/azure-portal-dashboards-create-programmatically#json-representation-of-our-example-dashboard-before-templating

2. Execute the command: `az portal dashboard create --input-path patt\TestDash.json  --name TestDash1  --resource-group xx`

**Json Code sample**

```
{
  "properties": {
    "lenses": {
      "0": {
        "order": 0,
        "parts": {}
      }
    },
    "metadata": {
      "model": {
        "timeRange": {
          "value": {
            "relative": {
              "duration": 24,
              "timeUnit": 1
            }
          },
          "type": "MsPortalFx.Composition.Configuration.ValueTypes.TimeRange"
        }
      }
    }
  },
  "name": "My Dashboard",
  "type": "Microsoft.Portal/dashboards",
  "location": "INSERT LOCATION",
  "tags": {
    "hidden-title": "My Dashboard"
  },
  "apiVersion": "2015-08-01-preview"
}

```

**Tool Info**

![image](https://user-images.githubusercontent.com/52313100/103068057-49a94200-45f7-11eb-8c05-03922ee4205d.png)

**Additional context**

Obviously this parameter: lenses exists, but the Azure CLI can't read this value.

**Comment by yonzhan** [comment]
portal

**Comment by yungezz** [comment]
hi @qwordy , could you pls help to have a look?

**Comment by qwordy** [comment]
@YalinLi0312 I remember portal is written by you. Could you have a look?

**Comment by YalinLi0312** [comment]
@lujinlou In `az portal dashboard create`, the --input-path is the path to properties json file instead of full template.  If you want to create a dashboard with full template, should use the command `az portal dashboard import`. Also, you need to update the `location` value in your sample Json.

**Comment by lujinlou** [comment]
@YalinLi0312 Thank you ! Get it.   It could work now.

Here is the sample:

```
{
    "lenses": {
      "0": {
        "order": 0,
        "parts": {}
      }
    },
    "metadata": {
      "model": {
        "timeRange": {
          "value": {
            "relative": {
              "duration": 24,
              "timeUnit": 1
            }
          },
          "type": "MsPortalFx.Composition.Configuration.ValueTypes.TimeRange"
        }
      }
    }
 
}
```

**Comment by hde-spyro** [comment]
The exported file should be a valid backup of the dashboard, without any modification
