### ISSUE TITLE
Azure - Error: az login

### ISSUE THREAD

**Issue by ShaohuaJoseph** [Azure/azure-cli#16354]
## Describe the bug

**Command Name**
`az login`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-4.15.0-1102-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.16.0

Extensions:
ai-examples 0.2.5

```

**Comment by yonzhan** [comment]
az login

**Comment by jiasli** [comment]
Please provide more information about the failure.
