### ISSUE TITLE
login and use of Graph API directly

### ISSUE THREAD

**Issue by AndriiOmelianenko** [Azure/azure-cli#16357]
Hello, this issue is more educational that actual issue with cli.

I have a need to access Graph API directly (via curl, for example).

Using this cli, I was able to login:
```bash
az login -u some-service-account --allow-no-subscriptions
```

and perform rest operations like this:
```bash
az rest --method POST --uri 'https://graph.microsoft.com/v1.0/groups/<object-id of the group>/appRoleAssignments' --headers 'Content-Type=application/json' --body '{"principalId": "principalId-value","resourceId": "resourceId-value","appRoleId": "appRoleId-value"}'
```

So I want to do the same using curl only. 

- I've tried to login (get accessToken) using this doc https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc but it doesn't gets me through with same credentials I use in az-cli.
- I've tried to use access token generated by cli, but it has different audience (https://management.core.windows.net/) so my curl requests to graph.microsoft.com are not allowed.

How do I do same things that CLI does to access graph-api? or what magic does the cli to able to reach graph-api with my username/password? 

Any suggestions are appreciated :)

**Comment by yonzhan** [comment]
login

**Comment by jiasli** [comment]
Hi @AndriiOmelianenko, sorry for the delay.

### Get access token from AAD directly

If you want to directly get an access token from AAD but your organization requires MFA, [username + password flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc) will fail. In that case, you will have to use [auth code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) (like `az login`) or [device code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code) (like `az login --use-device-code`). However, both flows require you to make several REST API calls or use MSAL library, like [Microsoft Authentication Library (MSAL) for Python](https://github.com/AzureAD/microsoft-authentication-library-for-python).

### Get access token using `az account get-access-token`

A simpler way is to get an access token with Azure CLI using [`az account get-access-token`](https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest#az_account_get_access_token). If you need to use MS Graph as the audience, simply specify it as an argument, just as the document provides:

```
az account get-access-token --resource-type ms-graph
```

This is how `az rest` does under the hood, so no fancy magic:

https://github.com/Azure/azure-cli/blob/3d14ca21e648f4fc0124132a43156a85a50251cd/src/azure-cli-core/azure/cli/core/util.py#L912

Feel free to let me know if there are any further questions.
