### ISSUE TITLE
'az storage directory exists' returns error when checking directory with brackets

### ISSUE THREAD

**Issue by TheStephLab** [Azure/azure-cli#16358]
**Describe the bug**
When performing an `az storage directory exists` targeting a directory with brackets '()', anything in the name that has characters after the brackets is returned as "unexpected".

**To Reproduce**

1. Standard login procedure
2. `az storage directory exists --name "SQL/SQLServer2014(Std)SP3" --share-name "share" --account-name *** --account-key ***`
3. Returns `SP3 was unexpected at this time.`

**Expected behavior**
Command should complete and do a verification as to the existence of the specified directory.

**Environment summary**
az cli version: 2.12.1
OS: Windows 10

**Additional context**
N/A

**Comment by yonzhan** [comment]
storage

**Comment by TheStephLab** [comment]
Thanks for the triaging @yonzhan 

I forgot to mention that this also affects other commands such as `az storage directory show`

**Comment by Juliehzl** [comment]
Hi @TheStephLab, is your terminal PowerShell? It is not CLI issue, but it is terminal issue.
You could try to use `cmd`, and your commands could work.
Or if you still want to use current terminal , please use the following command `az storage directory exists --name """SQL/SQLServer2014(Std)SP3""" --share-name "share" --account-name *** --account-key ***`.
For more information, please find quoting rules for your client.
