### ISSUE TITLE
Bad Error Message on creating a vpn gateway that already exists

### ISSUE THREAD

**Issue by bridgetcdavis** [Azure/azure-cli#1636]
The first time I ran the 'az network vpn-gateway create' command, the public-ip that I assigned to it was not in the same location as the vnet and vpn-gateway so it produced an error message that it could not find the public-ip resource.

This was helpful, but what I did not realize is that the Gateway had been created, but with a failed state. So I tried to create it again, this time with the correct public-ip, and it gave me an "Internal Server Error" with message "An error has occurred." It wasn't until I used a different Name with all the other parameters the same that it informed me the public-ip was already in use, which is what alerted me to the existence of the gateway.

I have created a separate issue for displaying output upon creating a Gateway, which would have helped me realize the gateway had been created in a failed state. Still, if a user tries to create a vpn-gateway using the same name, there should be a message that the gateway already exists instead of an internal server error.

**Comment by MyronFanQiu** [comment]
@Nilambari  Any update about this issue?

**Comment by yonzhan** [comment]
add to S165.

**Comment by MyronFanQiu** [comment]
@Nilambari Hello. Any update about this issue?

**Comment by yonzhan** [comment]
@Nilambari any update? Can we close this issue?

**Comment by Nilambari** [comment]
I will take a look.

**Comment by yonzhan** [comment]
@Nilambari any update?

**Comment by yonzhan** [comment]
@Nilambari any update?

**Comment by Nilambari** [comment]
For Powershell command let:- https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayCommand.cs (New-AzureRmVirtualNetworkGateway), we do validate if the same named gateway already exists in this resource group in same region, and throw proper error. But, seems this issue is for CLI, and we(VPN team) don't own that codebase. So adding @tjprescott who can help finding out if we have any similar validation in CLI command let or not.

**Comment by tjprescott** [comment]
I'm no longer on the CLI team, but generally the pattern is that CLI create commands do not do an existence check for resources.

**Comment by MyronFanQiu** [comment]
> For Powershell command let:- https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/VirtualNetworkGateway/NewAzureVirtualNetworkGatewayCommand.cs (New-AzureRmVirtualNetworkGateway), we do validate if the same named gateway already exists in this resource group in same region, and throw proper error. But, seems this issue is for CLI, and we(VPN team) don't own that codebase. So adding @tjprescott who can help finding out if we have any similar validation in CLI command let or not.

In my opinion, CLI can do such validation. But I think server should not return the "Internal Server Error". For a PUT method, I think it should have idempotency。

**Comment by Nilambari** [comment]
@MyronFanQiu  Is it possible to add similar validation at start in CLI as well to see if the same named gateway already exists in this resource group in same region, and if exists, throw proper error?

**Comment by yonzhan** [comment]
add to S172
