### ISSUE TITLE
az account set fail

### ISSUE THREAD

**Issue by ShaohuaJoseph** [Azure/azure-cli#16367]
## Describe the bug

**Command Name**
`az account set`

**Errors:**
```
The subscription of 'fy6kf4qan' doesn't exist in cloud 'AzureCloud'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account set --subscription {}`

## Environment Summary
```
Linux-4.15.0-1102-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.16.0

Extensions:
ai-examples 0.2.5

```

**Comment by yonzhan** [comment]
account

**Comment by jiasli** [comment]
Could you use `az account list` to list all subscriptions you have access to and check if `fy6kf4qan` is a valid subscription name?
