### ISSUE TITLE
Webapp:az webapp up failed to deploy with errors

### ISSUE THREAD

**Issue by sky-lynx** [Azure/azure-cli#16369]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
'NoneType' object has no attribute 'reserved'
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-2huwp6jm\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 717, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 709, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 37, in _ex_handler
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
pip-unpacked-wheel-0ydpnxq9\azure\cli\core\__init__.py, ln 784, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 3692, in webapp_up
AttributeError: 'NoneType' object has no attribute 'reserved'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
- `az webapp up --subscription {} --location {} --name {} --plan {} --resource-group {} --html --os-type {}`

## Expected Behavior
It should deploy the project to app service.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.16.0

```

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
#14287

**Comment by sky-lynx** [comment]
Is this a known issue? Is this really an issue or just happening on my machine?
It is blocking my deployment but I haven't gotten responses yet.

**Comment by ThejaChoudary** [comment]
Thanks for reporting .Will take a look.

**Comment by panchagnula** [comment]
Please try with the latest CLI version & let us know if this still repros. Thanks!
