### ISSUE TITLE
Deployment failed. Correlation ID: 140afdfe-8b92-4c4d-a9a9-521d8bf3a497. Cannot change network spine of shared disk sharedDisk while it is attached to running VM(s). Although max-shares is 2.

### ISSUE THREAD

**Issue by jawadSajid** [Azure/azure-cli#16375]
My disk is created as follows:

**az disk create -g ML-Resource-Group -n sharedDisk --size-gb 256 --location eastus --max-shares 2 --sku Premium_LRS**

My disk gets attached to the one of the VMs which i created as follows:

**az vm create --resource-group ML-Resource-Group --name PVM --image microsoft-dsvm:ubuntu-1804:1804-gen2:20.11.04 --generate-ssh-keys --location eastus**

But when I try to attach it to another VM created as follows:

**az vm create \
    --resource-group ML-Resource-Group \
    --name CVM \
    --image microsoft-dsvm:ubuntu-1804:1804-gen2:20.11.04  \
    --generate-ssh-keys \
    --priority Spot \
    --max-price -1 \
    --location eastus \
    --eviction-policy Deallocate \
    --output json \
    --verbose \
    --size "Standard_ND12s"**

I get this error:

**Deployment failed. Correlation ID: 140afdfe-8b92-4c4d-a9a9-521d8bf3a497. Cannot change network spine of shared disk sharedDisk while it is attached to running VM(s) /subscriptions/39472272-11a1-4c87-9de5-92aaeac6f7cf/resourceGroups/ML-Resource-Group/providers/Microsoft.Compute/virtualMachines/PVM.  Target: 'VM: '/subscriptions/39472272-11a1-4c87-9de5-92aaeac6f7cf/resourceGroups/ML-Resource-Group/providers/Microsoft.Compute/virtualMachines/VMTest', disk: '/subscriptions/39472272-11a1-4c87-9de5-92aaeac6f7cf/resourceGroups/ML-Resource-Group/providers/Microsoft.Compute/disks/sharedDisk''.**

**Comment by yungezz** [comment]
hi @qwordy could you pls have a look? thanks

**Comment by jawadSajid** [comment]
Figured out the solution! A Proximity Placement Group is to be made as follows:

    az ppg create -n myPPG -g ML-Resource-Group -l eastus -t standard

And then passed as a parameter in --ppg while creating VMs as:

    az vm create -n PVM -g ML-Resource-Group --image microsoft-dsvm:ubuntu-1804:1804-gen2:20.11.04 --generate-ssh-keys --ppg myPPG --location eastus --verbose
