### ISSUE TITLE
MSI for 2.17 "does not appear to have an app id"

### ISSUE THREAD

**Issue by MatthewSteeples** [Azure/azure-cli#16387]
**Describe the bug**
We use [Microsoft Endpoint Manager](https://endpoint.microsoft.com/) to deploy Azure CLI to our dev machines. Each release has been fine to do an in-place upgrade apart from 2.17. When trying to upload 2.17 to the portal an error is displayed

`The selected app package does not appear to have an app id.`

![image](https://user-images.githubusercontent.com/255971/103285937-4affb380-49d7-11eb-858c-cbc213647234.png)

**To Reproduce**
* Create a new Line of Business application in Endpoint Manager
* Attempt to upload the 2.17 MSI
* Error message appears

**Expected behavior**
Application is uploaded and available to deploy

**Environment summary**
MSI install

**Comment by jiasli** [comment]
I tested https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.17.0.msi on a local machine and it installs correctly.

I found the the same issue has been mentioned multiple times:

- https://docs.microsoft.com/en-us/answers/questions/177461/msi-to-intune-34the-selected-app-package-does-not.html
- https://social.technet.microsoft.com/Forums/ie/en-US/8aa5b36c-9bf2-4558-8c39-e48741ed3d52/cant-use-custom-msi-in-intune-but-can-be-used-in-sccm?forum=microsoftintuneprod
- https://techcommunity.microsoft.com/t5/msix-packaging-and-tools/o365-msix-package-upload-to-intune-the-selected-app-package-does/m-p/1430089

We didn't make any changes to the MSI packaging pipeline recently. 

While we are doing more research from CLI side, do you mind reaching out to the customer support of Microsoft Endpoint Manager as well? Thanks a lot.

**Comment by MatthewSteeples** [comment]
Hi @jiasli,

Thanks for the response. I'll raise a ticket and see what happens. I tried uploading the 2.16 version into the portal and that still works fine, so there's definitely something unusual going on

**Comment by MatthewSteeples** [comment]
Support ticket opened - # 23514049

**Comment by MatthewSteeples** [comment]
This problem still exists with 2.18. I'm still jumping through the various hoops with the service request

**Comment by MatthewSteeples** [comment]
Sadly the best I could get out of support was "Yes we can reproduce the problem, let us know if you fix it"

**Comment by StephaneLeleu** [comment]
Same here with 2.18. confirmed.

**Comment by jiasli** [comment]
Hi @MatthewSteeples, I am not sure what `app id` means in the error message. Could you provide this issue to the support team or add me to the email communication? My email address is <my_github_alias>@microsoft.com.

**Comment by MatthewSteeples** [comment]
Hi @jiasli I'm not sure what it means either, but it's all the portal reveals. Support closed my case (as I didn't have time to go through the steps that the should have been doing).

I'll forward you the emails I have from them.

**Comment by MatthewSteeples** [comment]
Problem still exists for 2.20

**Comment by MatthewSteeples** [comment]
Just noticed that the Azure Portal gives me this error:

>_1rRA0vmyWGo.js:10 [fx]  11:00:07 PM MsPortalImpl/Services/Services.IntuneAppParse Services.IntuneAppParse: [IntuneAppParse] Error parsing .msi file with code: 6

@jiasli is that something you can pass on to the right team?

**Comment by jiasli** [comment]
@MatthewSteeples, thanks for the information. We are internally working with Intune team on this. We will let you once there is any updates.

**Comment by MatthewSteeples** [comment]
Early indications suggest that this is fixed in 2.21

**Comment by MatthewSteeples** [comment]
This has been working fine for us for a while now
