### ISSUE TITLE
az cli 2.17.0 broke "az sig image-version create --no-wait --resource-group ..."

### ISSUE THREAD

**Issue by RadhakrishnaHariMSFT** [Azure/azure-cli#16391]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
On 12/29/2020 a new version of az cli was released for xenial and bionic  as listed here https://packages.microsoft.com/repos/azure-cli/dists/ and that broke the very last step of os image creation which is `az sig image-version create --no-wait --resource-group ...`

**To Reproduce**
The command that was run was 
az sig image-version create --no-wait --resource-group merusigv2 --gallery-name merusigv2 --gallery-image-definition ubuntu1604sbicustom --gallery-image-version 0.2020.12291921 --managed-image /subscriptions/7fec3109-5b78-4a24-b834-5d47d63e2596/resourceGroups/merusigv2/providers/Microsoft.Compute/images/ubuntu1604sbicustom_0.2020.12291921_mi --replica-count 3 --target-regions 'East US2' 'West US2' 'West Central US' 

**Expected behavior**
It should go off and start creating the image versions but instead we get this error
CLIInternalError: The command failed with an unexpected error. Here is the traceback:\n\'NoneType\' object is not subscriptable\nTraceback (most recent call last):\n  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke\n    cmd_result = self.invocation.execute(args)\n  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in execute\n    raise ex\n  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially\n    results.append(self._run_job(expanded_arg, cmd_copy))\n  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job\n    six.reraise(*sys.exc_info())\n  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise\n    raise value\n  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job\n    result = cmd_copy(params)\n  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 330, in __call__\n    return self.handler(*args, **kwargs)\n  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler\n    return op(**command_args)\n  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 3276, in create_image_version\n    external_bearer_token = external_tokens[0][0] + \' \' + external_tokens[0][1]\nTypeError: \'NoneType\' object is not subscriptable\nTo open an issue, please run: \'az feedback\'\n]'

**Environment summary**
apt-get

**Additional context**

**Comment by fengzhou-msft** [comment]
@qwordy can you take a look?

**Comment by qwordy** [comment]
@RadhakrishnaHariMSFT , I will have a look.

**Comment by qwordy** [comment]
I wrote a PR to address this issue. I am still investigating why it is None.

**Comment by dkegel-sigsci** [comment]
I get that very repeatable error with a slightly different command:
```
$ apt-cache version azure-cli
azure-cli:
  Installed: 2.17.0-1~buster
...
$ az sig image-version create --resource-group azjig_dkegel_1 --gallery-name azjig_dkegel_1_gal --gallery-image-definition http-test-server-a --gallery-image-version 1.0.0 --target-regions westus --replica-count 1 --managed-image /subscriptions/ec057915-e0d9-47de-a2ea-a713c9a986c3/resourceGroups/azjig_dkegel_1/providers/Microsoft.Compute/virtualMachines/http-test-server
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/vm/custom.py", line 3276, in create_image_version
    external_bearer_token = external_tokens[0][0] + ' ' + external_tokens[0][1]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by qwordy** [comment]
@dkegel-sigsci Is 7fec3109-5b78-4a24-b834-5d47d63e2596 the same as subscription where the image version will be created?

**Comment by qwordy** [comment]
Root cause found. Line 1 retrieves auxiliary subscriptions. But it does not take into consider if the subscription is same as the subscription where the image version is going to be created. We adopted Track 2 Python SDK recently. It does not return this subscription's token as external token.
```
1    aux_subscriptions = _get_image_version_aux_subscription(managed_image, os_snapshot, data_snapshots)
2    client = _compute_client_factory(cmd.cli_ctx, aux_subscriptions=aux_subscriptions)

3    # Auxiliary tokens, pass it to init or operation
4    external_bearer_token = None
5    if aux_subscriptions:
6        profile = Profile(cli_ctx=cmd.cli_ctx)
7        resource = cmd.cli_ctx.cloud.endpoints.active_directory_resource_id
8        cred, _, _ = profile.get_login_credentials(resource=resource,
9                                                   aux_subscriptions=aux_subscriptions)
10       _, _, _, external_tokens = cred.get_all_tokens('https://management.azure.com/.default')
```

**Comment by dkegel-sigsci** [comment]
Yes, I only have one subscription.  )I am an azure newbie and am just learning how to automate stuff with the cli.)

**Comment by qwordy** [comment]
Got it. No problem. This issue is not your mistake. It is a bug.
