### ISSUE TITLE
command show: support to take a resource id as parameter

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#164]
/CC: @johanste. For tracking.
So far we take a name which is not convenient on piping as the upstream command usually has the "id"  available, and i repeatedly had to use extra script to extract out the base name.

**Comment by tjprescott** [comment]
@johanste can this be closed?

**Comment by BurtBiel** [comment]
yep, this is taken care of.  Any specific issues with --ids can be re-opened seperately
