### ISSUE TITLE
az login fails from Linux box

### ISSUE THREAD

**Issue by marcopiuma** [Azure/azure-cli#16401]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I'm trying to login into az cli from my Ubuntu 18.04 box, it worked until a few days ago. Now I get the following error:

Authentication Error: "['access_denied']". Description: "["AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.\r\nTrace ID: 07982e8e-4109-4dcf-b6d1-f83475c18900\r\nCorrelation ID: 271fd4e6-6f77-4114-ae2d-6ddb723ccd77\r\nTimestamp: 2020-12-31 00:41:54Z"]" 
Login failed

**To Reproduce**

> sudo az login
**Expected behavior**

the command open a browser where I should be able to complete the authentication.

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
az login

**Comment by GatoonJin** [comment]
Hi Azure Team and marcopiuma,

I met the issue on Linux SUSE/CentOS/RedHat/Debian too. And I didn't reproduce on Windows and Mac. Azure CLI version didn't work with 2.14.2, 2.16.0 and 2.17.0. And the error message is the same: Authentication Error: "['access_denied']". Description: "["AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.

**Comment by jiasli** [comment]
`AADSTS50005` comes from AAD service and is displayed by Azure CLI.

I discussed with my colleague @ChenTanyi and we are also seeing the same issue while logging in with `@microsoft.com` accounts in [Microsoft Teams](https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/group-chat-software/) on Ubuntu. 

It looks the organization/directory/tenant administrator has enabled Conditional Access policy which will banned login on devices running unsupported operating systems like Linux. 

While we are solving this issue with Microsoft IT internally, could you contact your IT department as well? Thanks.

**Comment by jiasli** [comment]
### Temporary workaround

You may create a service principal on a supported system - Windows or Mac, with either Azure Portal or
```
az ad sp create-for-rbac --role xxx
```

Then you can log in with the service principal on Linux with 

```
az login --service-principal
```

**Comment by serprex** [comment]
Also seeing this with WSL

**Comment by marcopiuma** [comment]
thank you for the workaround!
