### ISSUE TITLE
Azure CLI 2.17.0_1 fails to launch on M1 Mac

### ISSUE THREAD

**Issue by maxburke** [Azure/azure-cli#16417]
**Describe the bug**

Running `az` generates this error message:

```
$ az
/opt/homebrew/Cellar/azure-cli/2.17.0_1/libexec/bin/python: No module named azure.cli.__main__; 'azure.cli' is a package and cannot be directly executed
```

**To Reproduce**
After upgrading to 2.17.0_1, type `az`, with or without additional options.

**Expected behavior**
I expected it to give me the help screen, or run the commands I specified.

**Environment summary**
Mac OS Big Sur (11.1), Apple M1 MacBook Pro, installed via HomeBrew.

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to look at this issue? thanks

**Comment by maxburke** [comment]
I just upgraded to 2.17.1 via homebrew and this still happens.

**Comment by fengzhou-msft** [comment]
Not sure if it's caused by the arm bottle package. I tested on my Intel chip Mac and it works fines. If anyone else meets the same issue on Apple M1 MacBook Pro, please comment.

**Comment by maxburke** [comment]
Ahh, yeah, I think I see the issue. It seems to be an interaction with a virtualenv I've got setup which re-sets the python path. Closing.

**Comment by joaocc** [comment]
Pls find log of 2.20 failing on M1
https://github.com/Azure/azure-cli/issues/16697#issuecomment-804919401
Can reproduce easily.

**Comment by pritom007** [comment]
> Not sure if it's caused by the arm bottle package. I tested on my Intel chip Mac and it works fines. If anyone else meets the same issue on Apple M1 MacBook Pro, please comment.

Have been facing the issue for quite a long. Mine is also mac m1. And I tried python 3.8 and 3.9 both failed.

**Comment by pritom007** [comment]
> Ahh, yeah, I think I see the issue. It seems to be an interaction with a virtualenv I've got setup which re-sets the python path. Closing.

can you please share the setup?
