### ISSUE TITLE
az login --identity fails: load_pem_private_key() missing 1 required positional argument: 'backend'

### ISSUE THREAD

**Issue by rajdhandus** [Azure/azure-cli#16416]
**Describe the bug**
**Command Name**
`az login`

**Errors:**
```
load_pem_private_key() missing 1 required positional argument: 'backend'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise+ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
...
python3.8/site-packages/jwt/api_jws.py, ln 149, in decode_complete
    self._verify_signature(signing_input, header, signature, key, algorithms)
python3.8/site-packages/jwt/api_jws.py, ln 233, in _verify_signature
    key = alg_obj.prepare_key(key)
python3.8/site-packages/jwt/algorithms.py, ln 242, in prepare_key
    key = load_pem_private_key(key, password=None)
TypeError: load_pem_private_key() missing 1 required positional argument: 'backend'
```

**To Reproduce**
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity`

**Expected behavior**

**Environment summary**
```
Linux-4.15.0-1089-azure-x86_64-with
Python 3.8.5
Installer: PIP

azure-cli 2.17.0

```

**Additional context**

This was working until a few days ago. Something with 2.17.0 release broke it. Was able to fix it by freezing the sub-dependency PyJWT to version 1.7.1 instead of 2.0.0 after noticing the following error in the build logs.

```
[INFO] [416] ERROR: pyopenssl 20.0.1 has requirement cryptography>=3.2, but you'll have cryptography 2.9.2 which is incompatible.
[INFO] [417] ERROR: msal 1.0.0 has requirement PyJWT[crypto]<2,>=1.0.0, but you'll have pyjwt 2.0.0 which is incompatible.
[INFO] [418] ERROR: azure-cli-core 2.16.0 has requirement azure-mgmt-core==1.2.1, but you'll have azure-mgmt-core 1.2.2 which is incompatible.

```

**Comment by divgo** [comment]
I am also experiencing this same issue. Installing AZ CLI via PIP into an Alpine Image.

**Comment by yonzhan** [comment]
az login

**Comment by divgo** [comment]
az login by itself doesn't seem to work either. Downgrading the PyJWT package does solve the problem though, so that is what I currently have in place. 

```
FROM alpine:latest

RUN apk update && apk upgrade && \
    apk add bash curl make py-pip jq openssl && \
    apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python3-dev && \
    pip install PyJWT==1.7.1 azure-cli==2.16.0 && \
    apk del --purge build
```

**Comment by jiasli** [comment]
This is caused by a conflicting dependency on `cryptography` from PyJWT 

https://github.com/jpadilla/pyjwt/blob/3993ce1d3503b58cf74699a89ba9e5c18ef9b556/setup.cfg#L55

```py
cryptography>=3.3.1,<4.0.0
```

and Azure CLI

https://github.com/Azure/azure-cli/blob/6f255051203445da73c99687e64f15d58c4006a7/src/azure-cli/setup.py#L134

There is an ongoing PR https://github.com/Azure/azure-cli/pull/15687 to bump `cryptography` to the latest version.
