### ISSUE TITLE
az login failed on my Linux machine

### ISSUE THREAD

**Issue by lianglin74** [Azure/azure-cli#16411]
**Resource Provider**
<cognition service>

**Description of Feature or Work Requested**
<'az login' failed on my Linux machine. I got the following message: 'Some failures occurred during the authentication
You can log an issue at Azure CLI GitHub Repository and we will assist you in resolving it.'>

**Comment by yonzhan** [comment]
az login

**Comment by lianglin74** [comment]
Any update for this problem? Thanks.

**Comment by lianglin74** [comment]
Is it related to ubuntu version? I am using ubuntu 16.04.5. Should I upgrade ubuntu to higher version? Thanks.

**Comment by yonzhan** [comment]
Similar to #16401

**Comment by jiasli** [comment]
> <'az login' failed on my Linux machine. I got the following message: 'Some failures occurred during the authentication
You can log an issue at Azure CLI GitHub Repository and we will assist you in resolving it.'>

This message is shown in the web browser. Could you share the error message in the terminal as well?
