### ISSUE TITLE
--remove option

### ISSUE THREAD

**Issue by 1spgardiner** [Azure/azure-cli#16426]
[Enter feedback here]
Can you confirm the syntax of the command to remove an IP address from the backend pool and addition.
The examples give this format 
az network application-gateway address-pool update -g MyResourceGroup --gateway-name MyAppGateway -n MyAddressPool \
    --add backendAddresses "{ "ip_address": "{10.0.0.13}" }"
But I have also seen
backendAddresses "{\"ip_address\":\"{10.0.0.13}\"}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb7977f-f67a-b7f1-9c55-5fe3ceef1148
* Version Independent ID: 855b66dc-6a1b-a182-8670-2a8b8ca8b10a
* Content: [az network application-gateway address-pool](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/address-pool?view=azure-cli-latest#az_network_application_gateway_address_pool_update)
* Content Source: [latest/docs-ref-autogen/network/application-gateway/address-pool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/application-gateway/address-pool.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Please use the following argument format to add and remove backendAddresses
```
--add backendAddresses ipAddress="10.0.0.13"
```
```
--remove  backendAddresses {index number}
```
