### ISSUE TITLE
i was trying to add enable virtual node add on on existing aks cluster and failed

### ISSUE THREAD

**Issue by doronmak** [Azure/azure-cli#16427]
## Describe the bug

**Command Name**
`az aks enable-addons`

**Errors:**
```
'NoneType' object has no attribute 'rpartition'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 717, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 710, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/acs/custom.py, ln 2244, in aks_enable_addons
    _add_virtual_node_role_assignment(cmd, result, random_agent_pool.vnet_subnet_id)
cli/command_modules/acs/custom.py, ln 1698, in _add_virtual_node_role_assignment
    vnet_id = vnet_subnet_id.rpartition('/')[0]
AttributeError: 'NoneType' object has no attribute 'rpartition'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks enable-addons --resource-group {} --name {} --addons {} --subnet-name {}`

## Environment Summary
```
Linux-5.8.0-7630-generic-x86_64-with-debian-bullseye-sid
Python 3.6.12
Installer: PIP

azure-cli 2.16.0 *

```

**Comment by yonzhan** [comment]
aks

**Comment by istarbuxs** [comment]
do we have any updates on this?

**Comment by navba-MSFT** [comment]
@doronmak @istarbuxs Apologies for the late reply. Could you please follow the below action plan ?

1. Update your python libraries
2. Update your Azure CLI and then test the command again.

Once this is done, please test your AKS CLi command again and let me know if you see the same issue. Awaiting your reply.
