### ISSUE TITLE
az ad app permission admin-consent --id  $appid Forbidden Message

### ISSUE THREAD

**Issue by brunoterkaly** [Azure/azure-cli#16422]
# Describe the bug

az ad app permission admin-consent --id  $appid

is giving me a Forbidden error.

Forbidden({"ClassName":"Microsoft.Portal.Framework.Exceptions.ClientException","Message":"Graph call failed with httpCode=Forbidden, errorCode=Authorization_RequestDenied, errorMessage=This operation can only be performed by an administrator. 

# To Reproduce

I am following in Azure sample:

https://github.com/Azure-Samples/azure-cli-samples/blob/master/aks/azure-ad-integration/azure-ad-integration.sh

The failure occurs on line 59.

# Expected behavior

I expect to be able to consent to permissions for my application ID have registered in active directory.

# Environment summary

Run WSL / Ubuntu on Windows. Following the example here:

https://github.com/Azure-Samples/azure-cli-samples/blob/master/aks/azure-ad-integration/azure-ad-integration.sh

# Additional context

Here is an image of the error:

![image](https://user-images.githubusercontent.com/1461866/103587040-37eb5880-4e9b-11eb-985b-f5c50da4e877.png)

I may also be locked down as I am using the MS Tenant:

![image](https://user-images.githubusercontent.com/1461866/103587446-1fc80900-4e9c-11eb-803c-eb474943f41b.png)

**Comment by yonzhan** [comment]
az ad

**Comment by brunoterkaly** [comment]
Ok, it worked from another subscription that I owned, not MS. Makes more sense.

az ad app permission grant --id 6efcb928-a0ac-49f7-90e4-211377cd1234 --api 00000003-0000-0000-c000-000000000000
{
  "clientId": "aaaaa1-cc95-4600-b8f9-cf979ab2369e",
  "consentType": "AllPrincipals",
  "expiryTime": "2022-01-05T00:11:44.372243",
  "objectId": "cfsadfsadfAEa4-c-XmrI2nsJ5wvaAC05OnOnzUdX1TXc",
  "odata.metadata": "https://graph.windows.net/ade82855-7143-4a84-950e-c9007506f8bb/$metadata#oauth2PermissionGrants/@Element",
  "odatatype": null,
  "principalId": null,
  "resourceId": "f6c279c2dsaffd9ce9-f351d5f54d77",
  "scope": "user_impersonation",
  "startTime": "2021-01-05T00:11:44.372243"
}
