### ISSUE TITLE
az deployment group create parameter --no-prompt is not working

### ISSUE THREAD

**Issue by Paqi** [Azure/azure-cli#16444]
**Describe the bug**
When I run `az deployment group create` to deploy an ARM template (for an APIM API resource), I am not prompted for parameters, and get a `Missing input parameters` error. 

Attempt 1
```
$ az deployment group create --mode Incremental --resource-group {resource group} --template-file sample.template.json
Missing input parameters: ApimServiceName, PolicyXMLBaseUrl, PolicyXMLSasToken
```

[The documentation](https://docs.microsoft.com/en-us/cli/azure/deployment/group?view=azure-cli-latest#az_deployment_group_create) says the `--no-prompt` parameter should default to false. That doesn't seem to be the case. 

Explicitly setting that parameter doesn't seem to work either:

```
$ az deployment group create --mode Incremental --resource-group {resource group} --no-prompt false --template-file sample.template.json
Missing input parameters: ApimServiceName, PolicyXMLBaseUrl, PolicyXMLSasToken
```

**To Reproduce**
See above.

**Expected behavior**
I should be prompted to supply the missing parameters for the ARM template I'm deploying, and the deployment should succeed.

**Environment summary**

OS: Windows Server 2019 Datacenter
Install Method: MSI
Shell Type: Bash via [git for windows](https://gitforwindows.org/)
Azure CLI Version:
```
$ az --version
azure-cli                         2.17.1

core                              2.17.1
telemetry                          1.0.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\SSH\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
ARM

**Comment by jkantamneni** [comment]
Hi, any update on this I have similar issue?

**Comment by zhoxing-ms** [comment]
> Missing input parameters: ApimServiceName, PolicyXMLBaseUrl, PolicyXMLSasToken

In fact, this message is just a warning log to remind you that this command lacks parameters, it is not an error message *(please note that its color is yellow instead of red)*. It will not affect the final execution result of this command.
