### ISSUE TITLE
display help text for 'az monitor app-insights component create --help' throws an error  

### ISSUE THREAD

**Issue by SREbuilt** [Azure/azure-cli#16442]
## Describe the bug

**Command Name**
`az monitor app-insights component create`

**Errors:**
```
No module named 'azure.mgmt.core'
Traceback (most recent call last):
Temp\pip-install-9101vebg\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 528, in execute
azure-cli-core\azure\cli\core\__init__.py, ln 300, in load_arguments
.azure\cliextensions\application-insights\azext_applicationinsights\__init__.py, ln 32, in load_arguments
    from azext_applicationinsights._params import load_arguments
.azure\cliextensions\application-insights\azext_applicationinsights\_params.py, ln 9, in <module>
    from ._validators import validate_applications, validate_storage_account_name_or_id, validate_log_analytic_workspace_name_or_id, validate_dest_account
.azure\cliextensions\application-insights\azext_applicationinsights\_validators.py, ln 8, in <module>
    from azure.mgmt.core.tools import is_valid_resource_id
ModuleNotFoundError: No module named 'azure.mgmt.core'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- az login
- az account set --subscription ... create prerequisites like resource-group, storage, etc.
- `az monitor app-insights component create --help`

## Expected Behavior
description of possible commands and arguments is displayed 

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6

azure-cli 2.2.0

Extensions:
application-insights 0.1.13

```

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
Hi @SREbuilt, how did you install azure-cli?
Please update it to the latest version by following the [Doc link](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli).

**Comment by SREbuilt** [comment]
My bad: my Version has been ways behind (2.2.0)
Now I’ve updated to 2.17.0 and also enabled the experimental Auto-update.

Many thanks and sorry for the noise I’ve generated – wish you a very nice weekend,
Bernhard

[cid:image003.png@01D6E5D0.1B3143A0]



Von: kai ru<mailto:notifications@github.com>
Gesendet: Freitag, 8. Januar 2021 04:29
An: Azure/azure-cli<mailto:azure-cli@noreply.github.com>
Cc: SREbuilt<mailto:bernhard.vogel@live.de>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [Azure/azure-cli] display help text for 'az monitor app-insights component create --help' throws an error (#16442)


Hi @SREbuilt<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSREbuilt&data=04%7C01%7C%7Cbe440baee6e4444809cf08d8b3859985%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637456733666587674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vw%2BLHc2eWf7zULZE6zdLQjAdUAv9ohQUrdcb%2ByQAC1o%3D&reserved=0>, how did you install azure-cli?
Please update it to the latest version by following the Doc link<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fcli%2Fazure%2Finstall-azure-cli&data=04%7C01%7C%7Cbe440baee6e4444809cf08d8b3859985%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637456733666597628%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=m7sc%2BIGrUkFWUXVqQQUISOGzitpi283MTZLQz8JRclI%3D&reserved=0>.

**Comment by yonzhan** [comment]
Could this issue be closed?

**Comment by SREbuilt** [comment]
Yes the issue can be closed, absolutely.

Thanks again,
Bernhard
