### ISSUE TITLE
az role assignment list unexpected error

### ISSUE THREAD

**Issue by dmraymond** [Azure/azure-cli#16449]
## Describe the bug
When running the az role assignment list an error is thrown but conitnues.

**Command Name**
`az role assignment list`

**Errors:**
```
'id=/subscriptions/cdd8dcb4-1f9b-4d0a-af79-170583e49d3a/resourceGroups/rg-vm-operations-westus2-001; location=westus2; managedBy=; name=rg-vm-operations-westus2-001; properties=; tags=; type=Microsoft'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 659, in execute
cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
cli\core\commands\__init__.py, ln 715, in _run_job
...
Temp\pip-unpacked-wheel-qa9gi9_9\msrest\service_client.py, ln 151, in format_url
KeyError: 'id=/subscriptions/cdd8dcb4-1f9b-4d0a-af79-170583e49d3a/resourceGroups/rg-vm-operations-westus2-001; location=westus2; managedBy=; name=rg-vm-operations-westus2-001; properties=; tags=; type=Microsoft'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- az cloud set
- az login
- az ad signed-in-user show
- az account list
- `az role assignment list --include-inherited --include-groups --subscription {}`

## Expected Behavior
A list of roles is returned.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1

Extensions:
interactive 0.4.4

```

**Comment by yonzhan** [comment]
az role

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed. Please upgrade to latest version of azure cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
