### ISSUE TITLE
command failed with keyerror

### ISSUE THREAD

**Issue by tlfmcooper** [Azure/azure-cli#16453]
## Describe the bug

**Command Name**
`az ad sp create-for-rbac`

**Errors:**
```
'281e3ece-67bd-457f-8328-81a12db8427a'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 714, in _run_job
    return cmd_copy.exception_handler(ex)
...
python3.6/site-packages/msrest/service_client.py, ln 108, in _request
    request = ClientRequest(method, self.format_url(url))
python3.6/site-packages/msrest/service_client.py, ln 151, in format_url
    url = url.format(**kwargs)
KeyError: '281e3ece-67bd-457f-8328-81a12db8427a'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad sp create-for-rbac --name {} --role {} --scopes {} --sdk-auth`

## Environment Summary
```
Linux-4.19.128-microsoft-standard-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.17.1

```

**Comment by tlfmcooper** [comment]
Expected output should be like this:

{
  "clientId": "<GUID>",
  "clientSecret": "<GUID>",
  "subscriptionId": "<GUID>",
  "tenantId": "<GUID>",
  (...)
}

**Comment by yonzhan** [comment]
az ad

**Comment by jiasli** [comment]
Could you share the `--debug` log for us to troubleshoot? You may share it here or send it to <my_github_id>@microsoft.com. Thank you.
