### ISSUE TITLE
"ValidationError: time data" When trying to create a vm with az cli

### ISSUE THREAD

**Issue by marcelo321** [Azure/azure-cli#16457]
**Describe the bug**

Running a command like:

`az vm create -n name -g group --public-ip-address-dns-name vwevsdfsdfwfl --image ubuntults --size Standard_B1ls --generate-ssh-keys -l eastus2`

Gives a time error:

`ValidationError: time data '2021-01-08T03:49:36.773Z' does not match format '%Y-%m-%d %H:%M:%S.%f'`

I have no idea why I am getting this with this command, as other az cli commands work.

**Comment by yungezz** [comment]
hi @qwordy could you pls help to have a look? thanks

**Comment by marcelo321** [comment]
@yungezz, Just solved it by doing the following command:

`apt-get install ntp`.

which updated the timezone of my server and then the command worked. Having a wrong time-zone was causing az-cli to crash.

All good now, close it if you like.

**Comment by qwordy** [comment]
I have not seen this error before. A mysterious issue.

**Comment by marcelo321** [comment]
Hi, this keeps happening over and over again and it gets pretty annoying. I fix it but the error comes back after a few weeks or so @qwordy @[CarolineNB](https://github.com/CarolineNB)

**Comment by marcelo321** [comment]
This keeps happening because a `Z` is added to the time of the machine.

`time data '2023-02-10T13:00:32.277Z' does not match format '%Y-%m-%d %H:%M:%S.%f'`

Might be possible to somehow ignore the time of the machine when running az cli commands? I don't understand why the times matter and fails the command from executing.

@yonzhan @zhoxing-ms

**Comment by zhoxing-ms** [comment]
@marcelo321 In fact, CLI determines whether the token has expired through the machine time in the authorization process, so CLI needs to obtain the time of the machine
