### ISSUE TITLE
Error message for incompatible extensions should suggest next steps

### ISSUE THREAD

**Issue by dkmiller** [Azure/azure-cli#16452]
**Is your feature request related to a problem? Please describe.**

If a user attempts to add a private preview extension to the Azure CLI, and the extension requires a base version greater than what they have currently installed, the resulting error message isn't very helpful. It doesn't tell them the extension name or how to install a compatible CLI core version.

![image](https://user-images.githubusercontent.com/5003801/103958346-a4679100-5101-11eb-9558-73770a856169.png)

**Describe the solution you'd like**

The error message should say which extension is attempting to be installed, and should point users to a link showing up to upgrade their installation of the Azure CLI.

**Describe alternatives you've considered**

I can't think of any alternativs.

**Additional context**

Motivated by: https://github.com/Azure/azureml-v2-preview/issues/130

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to look at is this related with package unsync in index.json?
