### ISSUE TITLE
Can't create storage account neither in GUI or az cli

### ISSUE THREAD

**Issue by marcelo321** [Azure/azure-cli#16456]
## Describe the bug

**Command Name**
`az storage account create`

**Errors:**
```
time data '2021-01-08T03:49:36.773Z' does not match format '%Y-%m-%d %H:%M:%S.%f'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
    datetime.datetime.strptime(full_token['expiresOn'], '%Y-%m-%d %H:%M:%S.%f')))
az/lib/python3.6/_strptime.py, ln 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
az/lib/python3.6/_strptime.py, ln 362, in _strptime
    (data_string, format))
ValueError: time data '2021-01-08T03:49:36.773Z' does not match format '%Y-%m-%d %H:%M:%S.%f'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account create --name {} -g {}`

## Environment Summary
```
Linux-5.8.0-25-generic-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.17.1

```

**Comment by yonzhan** [comment]
storage

**Comment by marcelo321** [comment]
@yonzhan Just solved it by doing the following command:

`apt-get install ntp`

which updated the timezone of my server and then the command worked. All good now

**Comment by marcelo321** [comment]
I think it is the same root cause of #16457 because of the first line:

`time data '2021-01-08T03:49:36.773Z' does not match format '%Y-%m-%d %H:%M:%S.%f'`

Closing this. If it happens again then I will just make a new issue.
