### ISSUE TITLE
Allow customers to specify a blob and its storage account to use as a source for creating a SIG image

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-cli#16451]
**Resource Provider**
COMPUTE

**Description of Feature or Work Requested**
Allow customers to specify a blob and its storage account to use as a source for creating a SIG image

**Minimum API Version Required**

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/42c0390a0df39676a731b6a45a5bc52522e99d5d/specification/compute/resource-manager/Microsoft.Compute/preview/2020-09-30/gallery.json

**Target Date**
GA in Feb 2021

**Comment by yungezz** [comment]
ack on the request

**Comment by qwordy** [comment]
Is this issue https://github.com/Azure/azure-cli/issues/15868 same one?

**Comment by qwordy** [comment]
Duplicate
