### ISSUE TITLE
az role assignment list BadRequestError

### ISSUE THREAD

**Issue by dmraymond** [Azure/azure-cli#16450]
## Describe the bug

**Command Name**
`az role assignment list`

**Errors:**
```
BadRequestError: The api-version query parameter (?api-version=) is required for all requests.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az resource list --resource-group {} --subscription {}`
- Loop through each resource and run the following command:
- `az role assignment list --scope {} --include-groups`

## Expected Behavior
A list of roles is returned, including groups.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1

Extensions:
interactive 0.4.4

```

**Comment by dmraymond** [comment]
Error consistently happens querying an expired certificate attached to a app service. Identifying information removed.
`/subscriptions/mySub/resourceGroups/myRG/providers/Microsoft.Web/certificates/myThumbprint#{}`

**Comment by yonzhan** [comment]
az role

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed. Please upgrade to latest version of azure cli [ 2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
