### ISSUE TITLE
WebApp:az webapp config ssl import allow naming of imported ssl resource

### ISSUE THREAD

**Issue by gavinbarron** [Azure/azure-cli#16464]
**Is your feature request related to a problem? Please describe.**
At present it is not possible to re-use an SSL cert imported from a key vault across multiple web apps in a single resource group.
Running az webapp config ssl import for a second webapp in a single resource group results in an error:
```InvalidResourceLocation - The resource '{resource-group}-{key-vault}-{cert-name}' already exists in location 'other location' in resource group '{resource-group}'. A resource with the same name cannot be created in location 'target location'. Please select a new resource name.```

**Describe the solution you'd like**
I'd like an optional parameter to give a different name to the imported ssl cert resource to avoid the name collision. e.g. --resource-name or --target-certificate-name

**Describe alternatives you've considered**
The only viable work around is to download the cert from the keyvault, set a password on it, and then use the upload and bind commands which is a lot to do and requires that you put the cert onto disk outside of the keyvault

**Comment by yonzhan** [comment]
webapp

**Comment by ThejaChoudary** [comment]
Able to repro the issue.Will look into this.

**Comment by seligj95** [comment]
Closing as associated PR was merged. Please update to the latest CLI and reopen if this is still an issue.
