### ISSUE TITLE
az-cli stops working if python project called "azure" in cwd

### ISSUE THREAD

**Issue by AddisonG** [Azure/azure-cli#16463]
### Summary
The `az` command (with any args or params) fails with an error when there exists a directory in the CWD called "azure" with another file in it called `__init__.py`.

### To Reproduce:
1. Navigate to any directory on the commandline.
    E.g: `cd /tmp`
2. Create a folder called azure, and a file under it called `__init__.py`.  
    E.g: `mkdir azure; touch azure/__init__.py`
3. Attempt to run any `az` command.
    E.g: `az version`
4. Observe the command fail, with the following error:
    `/usr/bin/python3: No module named azure.cli`

### Expected behavior
The command should work, regardless of folders.

### Environment summary
Installed with: `apt install azure-cli`

```
azure-cli                         2.0.81
core                              2.0.81
telemetry                          1.0.4
Extensions:
azure-devops                      0.17.0
```

Using `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)` on `Ubuntu 20.04.1 LTS`, `5.4.0-58-generic`.

---

This is an issue because many people may have python projects that contain a folder called `azure` somewhere within them.

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls have a look? thanks

**Comment by fengzhou-msft** [comment]
@AddisonG Please follow the [instruction](https://github.com/Azure/azure-cli/issues/14011#issue-640943121) to install the latest `azure-cli`. In the `azure-cli` package from microsoft repository, we use `-I` option of python to invoke `azure.cli`, it will not prepend the current directory to `sys.path` and it should fix this issue.
