### ISSUE TITLE
WebApp:staticwebapp - [P1] "browse" command should be "show"

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-cli#16472]
Currently, to view the details of a staticwebapp, the command is `az staticwebapp browse`. In `az webapp`, the verb is `show`. `browse` opens the browser to the site.

I think `az staticwebapp browse` should be renamed to `az staticwebapp show`. Should add a `browse` command at a later date to open the site in a browser. #16473

**Comment by yonzhan** [comment]
staticwebapp

**Comment by ThejaChoudary** [comment]
Considering this as feature request. Will look into this.
Thanks!

**Comment by ThejaChoudary** [comment]
FYI @panchagnula

**Comment by anthonychu** [comment]
Looks like this is done. Closing.
