### ISSUE TITLE
WebApp:staticwebapp - [P1] add commands to manage deployment secrets

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-cli#16470]
Add the following commands to get/reset deployment tokens
- get deployment token `az staticwebapp secrets list -g group -n site`
    `az rest --method post --url /subscriptions/[subscriptionId]/resourcegroups/[resourceGroupName]/providers/Microsoft.Web/staticSites/[staticSiteName]/listsecrets?api-version=2020-06-01`
- reset deployment token `az staticwebapp secrets reset-api-key -g group -n site`
    `az rest --method post --url /subscriptions/[subscriptionId]/resourcegroups/[resourceGroupName]/providers/Microsoft.Web/staticSites/[staticSiteName]/resetapikey?api-version=2020-06-01 --body "{\"location\": \"centralus\", \"properties\": {}}"`

@miwebst Any thoughts on the suggested commands?

**Comment by yonzhan** [comment]
staticwebapp

**Comment by ThejaChoudary** [comment]
Thanks for reporting. Considering this as feature request,we will work on this based on priority.

**Comment by ThejaChoudary** [comment]
FYI @panchagnula
