### ISSUE TITLE
Note needed about Enabling Access-Control-Allow-Credentials from CLI

### ISSUE THREAD

**Issue by bertwagner** [Azure/azure-cli#16478]
Since the `az functionapp cors` command allows adding/removing/showing origin URLs, I was expecting this same command to allow enabling Access-Control-Allow-Credentials as well.  I based this logic on the fact that these operations are shown on the same screen in the Azure Portal (numbers 2 and 3 in the screenshot):

![image](https://user-images.githubusercontent.com/4317083/104132114-49c07600-5349-11eb-8969-dffa0a49e81b.png)

Turns out while you can use `az functionapp cors` to modify the Origin URLs, you have to use a completely different command to programmatically enable the Access-Control-Allow-Credentials checkbox:

`az resource update --name web --resource-group <resource group name> --namespace Microsoft.Web --resource-type config --parent sites/<function app name> --set properties.cors.supportCredentials=true`

This is confusing.  Best case, I'd like to see a `az functionapp cors --enable` command added.  At the very least, a note should be added to the [az functionapp cors](https://docs.microsoft.com/en-us/cli/azure/functionapp/cors?view=azure-cli-latest) documentation saying that `az resource` needs to be used to enable CORS, with the above command as an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a3961a2-da0c-5697-b52d-35c8e676537d
* Version Independent ID: 3111fdd6-55ed-c1c8-7ac6-c4806a16945c
* Content: [az functionapp cors](https://docs.microsoft.com/en-us/cli/azure/functionapp/cors?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/functionapp/cors.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/functionapp/cors.yml)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
functionapp

**Comment by apawast** [comment]
@bertwagner thank you for this request. This is reasonable, we will have to review and prioritize this.

**Comment by arambazamba** [comment]
Just to prevent other from wasting time. I am using:

funcappid=$(az functionapp create -n $app -g $grp -s $storage --consumption-plan-location $loc --runtime dotnet --functions-version 3 --app-insights $app --query id -o tsv)
az resource update --ids $funcappid/config/web --set properties.cors.supportCredentials="true"

**Comment by kamperiadis** [comment]
Marking as resolved since this is now supported.
