### ISSUE TITLE
WebApp:staticwebapp - [P3] add command for zip deploy

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-cli#16471]
Add a command to deploy to a site by providing a URL to a zip file.

@miwebst to provide API details and sample zip file.

**Comment by yonzhan** [comment]
staticwebapp

**Comment by ThejaChoudary** [comment]
Thanks for reporting. Considering this as feature request,we will work on this based on priority.

**Comment by ThejaChoudary** [comment]
FYI @panchagnula
