### ISSUE TITLE
Error while login using Azure CLI

### ISSUE THREAD

**Issue by bembalkp** [Azure/azure-cli#16476]
getting an error while login using azure CLI.

http://localhost:8400/?error=invalid_request&error_description=AADSTS50139%3a+Session+is+invalid+due+to+missing+an+external+refresh+token.%0d%0aTrace+ID%3a+47ad116e-1a0f-42e2-9758-f411768b5500%0d%0aCorrelation+ID%3a+1f97f37c-d254-4852-8139-90b4090cb030%0d%0aTimestamp%3a+2021-01-10+11%3a04%3a34Z&state=t7swwkg5ei86w4axv2ps#

![image](https://user-images.githubusercontent.com/76433847/104121264-e8a59c00-5362-11eb-9a4b-89078fdbc5c8.png)

PS C:\Users\Prathmesh Bembalkar> az login
The default web browser has been opened at https://login.microsoftonline.com/common/oauth2/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
Authentication Error: "['invalid_request']". Description: "['AADSTS50139: Session is invalid due to missing an external refresh token.\r\nTrace ID: 47ad116e-1a0f-42e2-9758-f411768b5500\r\nCorrelation ID: 1f97f37c-d254-4852-8139-90b4090cb030\r\nTimestamp: 2021-01-10 11:04:34Z']"
Login failed

**Comment by yonzhan** [comment]
az login

**Comment by bembalkp** [comment]
any update?

**Comment by jiasli** [comment]
@bembalkp could you run `az login --debug` and share the output?

**Comment by dmitriyteteruk** [comment]
I have same issue with login after authorization in Azure Stack via az login.

**Comment by bembalkp** [comment]
Authentication Error: "['invalid_request']". Description: "['AADSTS50139: Session is invalid due to missing an external refresh token.\r\nTrace ID: 517dcfab-91f7-49b4-b1b5-6d87e9c11900\r\nCorrelation ID: 1858ffc3-8e16-4b82-97c8-9e4948344f12\r\nTimestamp: 2021-01-15 11:53:05Z']"
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 659, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 722, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 715, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-igh1xymj\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 693, in _run_jobAuthentication Error: "['invalid_request']". Description: "['AADSTS50139: Session is invalid due to missing an external refresh token.\r\nTrace ID: 517dcfab-91f7-49b4-b1b5-6d87e9c11900\r\nCorrelation ID: 1858ffc3-8e16-4b82-97c8-9e4948344f12\r\nTimestamp: 2021-01-15 11:53:05Z']"
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 659, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 722, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 715, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-igh1xymj\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 693, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 330, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\__init__.py", line 784, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-wcxsakwf\azure\cli\command_modules\profile\custom.py", line 162, in login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\_profile.py", line 197, in find_subscriptions_on_login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\_profile.py", line 871, in find_through_authorization_code_flow
knack.util.CLIError: Login failed
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\commands\__init__.py", line 330, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\__init__.py", line 784, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-wcxsakwf\azure\cli\command_modules\profile\custom.py", line 162, in login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\_profile.py", line 197, in find_subscriptions_on_login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-34tyr6f2\azure\cli\core\_profile.py", line 871, in find_through_authorization_code_flow
knack.util.CLIError: Login failed

**Comment by dmitriyteteruk** [comment]
What helped me:
1) Delete all clouds information except main subscription from file C:\Users\username\.azure\**clouds.config**
2) Delete cache file from this folder C:\Users\username\.azure\

**Comment by jiasli** [comment]
@dmitriyteteruk, this is weird. If the cloud is not activated via `az cloud set`, it won't be used in any way. CLI should authenticate against `https://login.microsoftonline.com/` as usual.

@bembalkp, are you using the public `AzureCloud` or any Azure Stack cloud? Have you changed anything under `C:\Users\username\.azure`?

**Comment by dmitriyteteruk** [comment]
> @dmitriyteteruk, this is weird. If the cloud is not activated via `az cloud set`, it won't be used in any way. CLI should authenticate against `https://login.microsoftonline.com/` as usual. In your case, are you using an ADFS account on `https://login.microsoftonline.com/`?
Yes, authentication always goes through `https://login.microsoftonline.com/`. 
I am authenticated in browser in both accounts (Stack and Cloud). 
In CLI I have added both clouds (AzureCloud and Stack).
I faced with this issue second time this week when need to switch in CLI from Stack to AzureCloud. If I not change Stack to AzureCloud using `az cloud set -n Name` then I get error after `az login`

**Comment by jiasli** [comment]
@dmitriyteteruk, 

The Azure Resource Management' resource ID will be sent in the initial 

```py
https://login.microsoftonline.com/common/oauth2/authorize
?response_type=code
&client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46
&redirect_uri=http://localhost:8400
&state=h4s32833xo1ve962o1ql
&resource=https://management.core.windows.net/  # Make sure this is from the correct target cloud
&prompt=select_account
&sso_reload=true
```

Authentication Error: "['access_denied']". Description: "["AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46(Microsoft Azure CLI). Resource value from request: https://management.masselfhost.onmicrosoft.com/0f237931-e2a3-402d-a489-686a4cb547c1. Resource app ID: 84d205b6-b275-47cb-9270-94e861521c99. List of valid resources from app registration: .\r\nTrace ID: 452c6599-c799-47fd-814c-aca31cb00600\r\nCorrelation ID: 26e603d1-f6ae-4e5c-b042-ac810c17f0ea\r\nTimestamp: 2021-01-18 02:05:47Z"]"
Just want to double confirm: is your Azure Stack use AAD auth or ADFS auth. In other words, in `cloud.config`, what is the value of the `endpoint_active_directory` property of the Azure Stack:

- AAD: `https://login.microsoftonline.com/`
- ADFS: something like `https://adfs.redmond.azurestack.corp.microsoft.com/adfs/`

**Comment by jiasli** [comment]
@dmitriyteteruk, I think the root cause for the failure is that you are using unmatched **AAD account** for **Azure Stack cloud**.

In the initial `/authorize` request, `resource` field contains the ARM ID for the selected cloud.

```sh
https://login.microsoftonline.com/common/oauth2/authorize
?response_type=code
&client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46
&redirect_uri=http://localhost:8400
&state=dinlzewoozmv1djziynk
&resource=https://management.core.windows.net/  # ARM resource ID
&prompt=select_account
```

When an unmatched account is used, error like this may occur. @bembalkp, could you kindly check the same?

### Too long; Don't read

However, when I tested with my account which doesn't have access to Azure Stack:

```sh
https://login.microsoftonline.com/common/oauth2/authorize
?response_type=code
&client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46
&redirect_uri=http://localhost:8400
&state=dyxifurdy7tn681qw50u
&resource=https://management.masselfhost.onmicrosoft.com/0f237931-e2a3-402d-a489-686a4cb547c1  # ARM resource ID of Azure Stack
&prompt=select_account
&sso_reload=true
```

I got:

```
Authentication Error: "['access_denied']". 
Description: "["AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in 
  the requested permissions in the client's application registration. 
Client app ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46(Microsoft Azure CLI). 
Resource value from request: https://management.masselfhost.onmicrosoft.com/0f237931-e2a3-402d-a489-686a4cb547c1. 
Resource app ID: 84d205b6-b275-47cb-9270-94e861521c99. List of valid resources from app registration: .\r\n
...
```

It seems the actual error message depends on AAD tenant/Azure Stack settings. Anyway, selecting the correct cloud is always a necessary task before logging in.

**Comment by dmitriyteteruk** [comment]
> @dmitriyteteruk, I think the root cause for the failure is that you are using unmatched **AAD account** for **Azure Stack cloud**.
> 
> In the initial `/authorize` request, `resource` field contains the ARM ID for the selected cloud.
> 
> ```shell
> https://login.microsoftonline.com/common/oauth2/authorize
> ?response_type=code
> &client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46
> &redirect_uri=http://localhost:8400
> &state=dinlzewoozmv1djziynk
> &resource=https://management.core.windows.net/  # ARM resource ID
> &prompt=select_account
> ```
> 
> When an unmatched account is used, error like this may occur. @bembalkp, could you kindly check the same?
> 
> ### Too long; Don't read
> However, when I tested with my account which doesn't have access to Azure Stack:
> 
> ```shell
> https://login.microsoftonline.com/common/oauth2/authorize
> ?response_type=code
> &client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46
> &redirect_uri=http://localhost:8400
> &state=dyxifurdy7tn681qw50u
> &resource=https://management.masselfhost.onmicrosoft.com/0f237931-e2a3-402d-a489-686a4cb547c1  # ARM resource ID of Azure Stack
> &prompt=select_account
> &sso_reload=true
> ```
> 
> I got:
> 
> ```
> Authentication Error: "['access_denied']". 
> Description: "["AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in 
>   the requested permissions in the client's application registration. 
> Client app ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46(Microsoft Azure CLI). 
> Resource value from request: https://management.masselfhost.onmicrosoft.com/0f237931-e2a3-402d-a489-686a4cb547c1. 
> Resource app ID: 84d205b6-b275-47cb-9270-94e861521c99. List of valid resources from app registration: .\r\n
> ...
> ```
> 
> It seems the actual error message depends on AAD tenant/Azure Stack settings. Anyway, selecting the correct cloud is always a necessary task before logging in.

I am choosing right account in pop login browser window. Until I change cloud that I want to `az login` with command `az cloud set --name Azure` I am getting error.
Looks below on screenshots.

- I am logged in to Stack account 
![image](https://user-images.githubusercontent.com/34028526/104880540-cb7b5980-5970-11eb-862c-73f484765ff0.png)
- I want to switch to Azure account using `az login` 
![image](https://user-images.githubusercontent.com/34028526/104880999-a3d8c100-5971-11eb-81b3-5b0839eac81a.png)
- Getting error: `Authentication Error: "['access_denied']". Description: "["AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46(Microsoft Azure CLI). Resource value from request: https://management.iurnvgru.onmicrosoft.com/97a61497-2338-4b3d-9a11-cbaaae5191da. Resource app ID: faf7681b-619f-4d59-8655-43a40b5ad363. List of valid resources from app registration: .\r\nTrace ID: 81dd37b0-50f9-48bb-85f2-e23032d30000\r\nCorrelation ID: 9e095169-20cd-461b-b431-5ae733640e63\r\nTimestamp: 2021-01-18 06:42:47Z"]"
Login failed`
![image](https://user-images.githubusercontent.com/34028526/104881092-c4a11680-5971-11eb-8cbf-1ff7b93328e0.png)

- to avoid this error I need to change cloud using `az cloud set --name Name` and change Azure to Stack and back before use `az login`. Not sure if this behavior is correct.

**Comment by jiasli** [comment]
Selecting the account in the browser won't automatically switch the cloud. The account that is selected in the browser must match the cloud that is set via `az cloud set`.
