### ISSUE TITLE
WebApp:az webapp up DefaultErrorResponseException import error

### ISSUE THREAD

**Issue by panzergame** [Azure/azure-cli#16488]
I followed tutorial from https://docs.microsoft.com/fr-fr/azure/app-service/quickstart-python?tabs=bash&pivots=python-framework-flask but command `az webapp up --sku F1 --name test-hello-world` is raising an import error.

**Command Name**
`az webapp up`

**Errors:**
```
cannot import name 'DefaultErrorResponseException' from 'azure.mgmt.web.models' (/usr/lib/python3/dist-packages/azure/mgmt/web/models.py)
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 558, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 478, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
cli/command_modules/appservice/custom.py, ln 39, in <module>
    from azure.mgmt.web.models import KeyInfo, DefaultErrorResponseException
ImportError: cannot import name 'DefaultErrorResponseException' from 'azure.mgmt.web.models' (/usr/lib/python3/dist-packages/azure/mgmt/web/models.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --sku {} --name {}`

## Environment Summary
```
Linux-5.10.0-1-amd64-x86_64-with-glibc2.31
Python 3.9.1
Installer: PIP

azure-cli 2.17.1

Extensions:
azure-devops 0.19.0

```

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@calvinsID this is concerning can you take a look.

**Comment by calvinsID** [comment]
Hi @panzergame, I was unable to repro this. Can you please try reinstalling Azure CLI and letting me know if issue still persists?

**Comment by panzergame** [comment]
Hi @calvinsID, I reinstalled Azure CLI and now it seems to work nicely, thanks for testing. Should I let you close the issue ?
