### ISSUE TITLE
Exception when running az network vnet list 

### ISSUE THREAD

**Issue by Kamran-Bilgrami** [Azure/azure-cli#16481]
## Describe the bug

**Command Name**
`az network vnet list`

**Errors:**
```
ipv4
Traceback (most recent call last):
network/v2020_07_01/models/_network_management_client_enums.py, ln 24, in __getattr__
    return cls._member_map_[name.upper()]
KeyError: 'IPV4'

...

network/v2020_07_01/models/_network_management_client_enums.py, ln 26, in __getattr__
    raise AttributeError(name)
AttributeError: ipv4
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network vnet list`

## Environment Summary
```
Linux-5.9.0-kali1-amd64-x86_64-with-glibc2.31
Python 3.9.1
Installer: PIP

azure-cli 2.16.0

Extensions:
interactive 0.4.4
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
@Kamran-Bilgrami I could not reproduce it. Could you have a try to upgrade azure-cli?

**Comment by kairu-ms** [comment]
Please upgrade CLI by command

```
az upgrade
```
