### ISSUE TITLE
Upgrade azcopy version at least to 10.6.1

### ISSUE THREAD

**Issue by terezbw** [Azure/azure-cli#16489]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Command "az storage copy"  copy files with wrong content-type. It appended  ";" at the end.
Example:
"Content-type: text/html;"

It's azcopy bug and it fixed in 10.6.1:
https://github.com/Azure/azure-storage-azcopy/issues/1139

 **To Reproduce**

az storage copy
**Expected behavior**

"Content-type: text/html"
or
"Content-type: text/html;  charset=utf-8"

**Environment summary**

Centos-7, add azure repo https://packages.microsoft.com/yumrepos/azure-cli, then  yum install azure-cli
**Additional context**

**Comment by terezbw** [comment]
--- /usr/lib64/az/lib64/python3.6/site-packages/azure/cli/command_modules/storage/azcopy/util.py.ORIG   2021-01-11 16:21:04.772407020 +0300
+++ /usr/lib64/az/lib64/python3.6/site-packages/azure/cli/command_modules/storage/azcopy/util.py        2021-01-11 16:21:48.298409125 +0300
@@ -23,7 +23,7 @@
 
 STORAGE_RESOURCE_ENDPOINT = "https://storage.azure.com"
 SERVICES = {'blob', 'file'}
-AZCOPY_VERSION = '10.5.0'
+AZCOPY_VERSION = '10.6.1'

**Comment by vgrebenschikov** [comment]
Same on macOS, 

For me, problem raised in https://github.com/Azure/azure-storage-azcopy/issues/1139 was not solved
- because 'az storage copy ...' still use old version of azcopy

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Thanks for the feedback. We will upgrade it in next release
