### ISSUE TITLE
WebApp:I can't start or update my webapp

### ISSUE THREAD

**Issue by ojnas** [Azure/azure-cli#16487]
When I run "az webapp up" I get the following error:

Deployment status endpoint ... returns malformed data. Retrying...

## Describe the bug

**Command Name**
`az webapp up`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.5.1

```

**Comment by ojnas** [comment]
I tried to deploy from local git instead but that results in another error:

error: RPC failed; HTTP 409 curl 22 The requested URL returned error: 409 Conflict

I don't know what more to try. Please assist.

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@calvinsID second case with the error.

**Comment by seligj95** [comment]
please upgrade to the latest cli version and let us know if the issue persists.

**Comment by seligj95** [comment]
closing due to no response, please reopen if still an issue after updating to the latest CLI version
