### ISSUE TITLE
az acs dcos browse navigates to localhost as well as the proxy

### ISSUE THREAD

**Issue by PeterJausovec** [Azure/azure-cli#1649]
Running ```az acs dcos browse -n [] --resource-group []``` opens two browsers. One goes to the DCOS portal (which is expected), but the other navigates to the proxy that was set and fails with this error:

```dial tcp 127.0.0.1:63037: getsockopt: connection refused```

**Comment by brendandburns** [comment]
weird, let me look at the code, it shouldn't do that ...

**Comment by brendandburns** [comment]
Ah, I see the problem, filed:

https://github.com/Azure/azure-cli/pull/1702
