### ISSUE TITLE
The 'az ad sp credential reset' resets the password on application but not sp itself?

### ISSUE THREAD

**Issue by Shuanglu** [Azure/azure-cli#16496]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

1. Run 'az ad spcredential reset' it calls ' /<tenantID>/applications/<applicationID>?api-version=1.6' instead of  '/<tenantID>/servicePrincipals?api-version=1.6' to reset the password. 
2. When my app object doesn't hv the secret and sp has the secret, the 'az ad sp credential list' returns empty. Firstly it checked the credential of sp but finally it returned the result of app object. This is confusing.

**To Reproduce**

az ad spcredential reset --id xxx --debug
**Expected behavior**

The 'az ad sp' and 'az ad app' can return the corresponding results
**Environment summary**

WSL

{
  "azure-cli": "2.16.0",
  "azure-cli-core": "2.16.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.4.71"
  }
}

ubuntu 18.04

bash
**Additional context**

**Comment by yonzhan** [comment]
az ad
