### ISSUE TITLE
Always getting the remote exception after executing the az storage blob upload

### ISSUE THREAD

**Issue by MoueenShaik** [Azure/azure-cli#16504]
Hello Team,

I am trying to upload the files to the Azure blob storage by using the following command.

 **az storage blob upload --only-show-errors   --auth-mode login --account-name "BlobName" -c "folder\testing" -f "D:\localfile.txt" -n "localfile.txt"**

file is uploading successfully, but I am getting the below exception in the PowerShell output window. 

Output after executing the commad: 
az : 
At line:2 char:2
+  az storage blob upload --only-show-errors  --auth-mode login --accou ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Alive[################################################################]  100.0000%
Finished[#############################################################]  100.0000%
{
  "etag": "\"0x8D8B71E5AA7EEB3\"",
  "lastModified": "2021-01-12T17:20:27+00:00"
}

Query : How to fix the remote exception error with any command params or how to get rid of the remote exception in output window

Azure CLI Version: 2.17.1
PowerShell version : PSVersion-  5.1.19041.610  
Thanks In Advance 
Moueen Shaik

**Comment by yonzhan** [comment]
storage

**Comment by MoueenShaik** [comment]
Hello Team,

Any update on the above query?

Thanks & Regards,
Moueen Shaik

**Comment by Juliehzl** [comment]
Hi @MoueenShaik, could you show me your debug info with `--debug` in your command?

**Comment by MoueenShaik** [comment]
@Juliehzl , Please find below screen shot for your reference.

![image](https://user-images.githubusercontent.com/47388795/104786029-c932b880-5740-11eb-8434-e9e14611afd6.png)

**Comment by Juliehzl** [comment]
@MoueenShaik Thanks for your information!
From the debug information you shared, your command is executed successfully. For `RemoteException` you get in your client, I think it is the terminal you use cannot handle the information which is written to `stderr`. Are you using `Powershell ISE`?

If you still want to use the terminal, you could redirect stderr info to a file or add `2>$null` in your command.
And you could change to `cmd` or other terminal and the issue will not happen any  more.

**Comment by yonzhan** [comment]
@MoueenShaik any update or feedback?

**Comment by taimish** [comment]
Perhaps this issue should be reopened.
Today morning I was successfully running some commands that create resources using Azure CLI version 2.12. Later I installed the Azure CLI version 2.24 and ran the same commands but got the error:
```
az :
At line:1 char:1
+ az network nsg rule create `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (               ...               :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
Among them are:
az network nsg rule create ...
az keyvault create ...
az acr create ...
Usually I ran them inside a script but I specially tried them in Powershell and saw that beside success message, sent to the stdout, there is also this message sent to the stderr.
PS info:
```
Name             : ConsoleHost
Version          : 5.1.19041.906
InstanceId       : 1670521c-b3b3-4398-85c3-d11312b42755
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```
Azure CLI info:
```
azure-cli: 2.24.0
azure-cli-core: 2.24.0
azure-cli-telemetry: 1.0.6
extensions:
  account: 0.2.1
  aks-preview: 0.4.63
```
I suppose that since the error appears for different commands the problem is not caused by the PS.
Also redirecting the stderr to the $null is not an option - how should we work without error messages at all?

P.S.
Please inform your team that some commands output warnings to the stderr (for example, `az network vnet subnet create` for a subnet that already exists). That can be avoided via `--only-show-errors` option, but again - we loose all warnings then.

**Comment by melborp** [comment]
@taimish  @yonzhan 
I am experiencing same issue with az webapp slot swap that worked fine before and now suddenly fails.

Command: `az webapp deployment slot swap -n $AppName -g $ResourceGroupName --slot $SlotName`

`Error: NotSpecified: (:) [], RemoteException`

In my case i am using PowerShell Core and Jobs to run multiple commands in paralleel. It has worked fine for 12+ months but broke with 2.24, works with 2.23. 

The command succeeds and swaps nicely, but the script exists with failure and breaks the deployment.
`--only-show-errors` didnt help

In case of Jobs, this `the terminal you use cannot handle the information which is written to stderr` is applicable but using jobs is desired and the main way for paralleel execution in powershell.

**Comment by melborp** [comment]
powershell 7 has a new capability to run `ForEach-Object -Parallel` but even though no error is shown now, the second write to host doesnt happen. 

```
    $Apps | ForEach-Object -Parallel { 
        Write-Host "Swapping asynchronously for site: $_"
        $appName = $_

        $measure = Measure-Command {
            az webapp deployment slot swap -n $appName -g $using:ResourceGroupName --slot $using:SlotName 
        }
        
        Write-Host "Slot swap for $($appName) took $($measure.TotalSeconds) seconds" 
    }
```

Running in a job causes the RemoteException.

**Comment by Erw1nT** [comment]
If anyone else stumbles onto this problem.
When using powershell, add the parameter "--no-progress"
