### ISSUE TITLE
Rename az cli cmdlets

### ISSUE THREAD

**Issue by naveenchekuri** [Azure/azure-cli#16508]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
We would need to rename following cli commands to match marketing team's requirement.

az network vrouter create -> az network routeserver create

az network vrouter delete -> az network routeserver delete

az network vrouter list -> az network routeserver list

az network vrouter peering -> az network routeserver peering

az network vrouter peering create -> az network routeserver peering create

az network vrouter peering delete -> az network routeserver peering delete

az network vrouter peering list -> az network routeserver peering list

az network vrouter peering show -> az network routeserver peering show

az network vrouter peering update -> az network routeserver peering update

az network vrouter show -> az network routeserver show

az network vrouter update -> az network routeserver update

**Minimum API Version Required**
2020-08-01

**Swagger Link**

**Target Date**
02/07

**Comment by yonzhan** [comment]
app service
