### ISSUE TITLE
azcopy is given more powerful SAS than needed (has write, only needs read)

### ISSUE THREAD

**Issue by MaxTranced** [Azure/azure-cli#16519]
**Is your feature request related to a problem? Please describe.**
Using `azure-cli` ` 2.17.1`, when copying a blob from a blob storage account to a local file using `azcopy` (via `az storage copy`), even though I am logged in, a SAS is generated. The SAS is displayed as a part of the console output with no censoring whatsoever (which makes it more likely to accidentally leak) and it includes more permissions than needed. I think read permission for the blob service would suffice, but apparently all of them are granted (`sp=rwdlacup`). The generated command line is:

```
'C:\\Users\\<usr>\\.azcopy\\azcopy.exe', 'copy', 'https://<account>.blob.core.windows.net/<blobpath>?se=2021-01-14T13%3A53%3A27Z&sp=rwdlacup&sv=2018-03-28&ss=b&srt=sco&sig=redacted', 'D:\\<destinationpath>'
```

**Describe the solution you'd like**
The SAS would ideally not be generated, the `az login` credentials would ideally be used for `azcopy` too.
Alternatively, if the SAS is used, it should not be displayed uncensored. Also, it should only include the minimum permissions necessary to do the job.

**Describe alternatives you've considered**
I've considered using `az storage blob copy` but in some scenarios it's much, much slower than `az storage copy`, in some cases more than 10x slower.

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Thanks @MaxTranced  for your feedback. We need to integrate with Azcopy to use `az login` credentials. @zezha-msft we could set up a meeting for the usage.

**Comment by zezha-msft** [comment]
@Juliehzl sounds good!

The combination of sp=rwdlacup and srt=sco is indeed too powerful.
