### ISSUE TITLE
Az aks get-credentials crash

### ISSUE THREAD

**Issue by dhaugli** [Azure/azure-cli#16515]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
/home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-x86_64-linux-gnu.so: undefined symbol: ffi_prep_closure, version LIBFFI_CLOSURE_7.0
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 558, in execute
    self.commands_loader.load_arguments(command)
...
python3.8/site-packages/bcrypt/__init__.py, ln 25, in <module>
    from . import _bcrypt
ImportError: /home/linuxbrew/.linuxbrew/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/_cffi_backend.cpython-38-x86_64-linux-gnu.so: undefined symbol: ffi_prep_closure, version LIBFFI_CLOSURE_7.0
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials -n {} -g {} -f {} -f`

## Expected Behavior
A successfull grab of the kubernetes credentials to access the cluster. 

## Environment Summary
```
Linux-5.8.0-34-generic-x86_64-with-glibc2.2.5
Python 3.8.7
Installer: HOMEBREW

azure-cli 2.17.1

```

**Comment by yonzhan** [comment]
aks

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to look is this caused by cffi dependency? thanks

**Comment by dhaugli** [comment]
Hi, this issue can be closed. It got solved once I updated python :)
