### ISSUE TITLE
Az Login

### ISSUE THREAD

**Issue by Xenomorfo** [Azure/azure-cli#16517]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
invalid syntax (parser.py, line 158)
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
lib/python3/dist-packages/six.py, ln 703, in reraise
    raise value
...
python3/dist-packages/adal/token_request.py, ln 38, in <module>
    from .cache_driver import CacheDriver
python3/dist-packages/adal/cache_driver.py, ln 32, in <module>
    from dateutil import parser
python3.8/site-packages/dateutil/parser.py, ln 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.7.0-15-generic-x86_64-with-glibc2.32
Python 3.8.6
Installer: PIP

azure-cli 2.10.1

Extensions:
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
az login

**Comment by jiasli** [comment]
``l.append("%s=%s" % (attr, `value`))`` was changed to `l.append("%s=%s" % (attr, repr(value)))` 10 years ago (https://github.com/dateutil/dateutil/commit/ac37a80ce677025e03951091284feab1eadc0404).

It looks like you used `pip` to install a very old version of [python-dateutil](https://pypi.org/project/python-dateutil/) which doesn't work in Python 3.

To revert it, please install the specified version:

https://github.com/Azure/azure-cli/blob/7ef9f617f9f54a5ea3537b824a1ef43eaa6401cd/src/azure-cli/requirements.py3.Linux.txt#L121

```
pip install python-dateutil==2.8.0
```
