### ISSUE TITLE
az keyvault create returns "Unable to find user with spn 'systemAssignedIdentity'" when logged in with MSI

### ISSUE THREAD

**Issue by MarkAtAgilliance** [Azure/azure-cli#16514]
## Describe the bug
When using a desktop with a user signed into the browser (az login), the command succeeds (same tenant, same resource, etc)
When signed into a VM with an MSI enabled and using az login --identity, it fails as below.
When adding the --no-self-perms flag, it succeeds.

It is not clear why the no-self-perms flag is required (is an MSI not able to be added to the permissions by default?).

BTW - the documentation says --no-self-perms is required but it is in the "optional" list...yet it isn't always required.  somethings up here with the doc too.

Hope this helps.
M.

**Command Name**
`az keyvault create`

**Errors:**
```
Unable to find user with spn 'systemAssignedIdentity'
Cannot create vault.
Unable to query active directory for information about the current user.
You may try the --no-self-perms flag to create a vault without permissions.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- az login --identity 
- `az keyvault create -l "North Europe" -n {} -g {} --network-acls-vnets "vnet/default" --enabled-for-deployment true --bypass AzureServices --default-action Deny

Using --no-self-perms succeeds.
- `az keyvault create -l "North Europe" -n {} -g {} --network-acls-vnets "vnet/default" --enabled-for-deployment true --bypass AzureServices --default-action Deny --no-self-perms
## Expected Behavior
Creates the keyvault.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1

```

**Comment by yungezz** [comment]
hi @houk-ms could you pls help on this?

**Comment by houk-ms** [comment]
Hi @MarkAtAgilliance, thanks for reporting this.

The reason is we try to retrive the `object_id` from the signed-in user/service principal and then set default access policy for the `object_id` when creating a keyvault. While i am afraid we can not retrive the `object_id` when you login with managed identity.

For your case, my suggestion is
1. Create the keyvault with `--no-self-perms` parameter
2. Use `az keyvault set-policy` to grant access policy for the keyvault

**Comment by houk-ms** [comment]
@MarkAtAgilliance I'll close the issue now, we will open a feature request for this if this behavior can be improved.
