### ISSUE TITLE
Unable to login to azure using 'az login' from linux (ubuntu on windows 10)

### ISSUE THREAD

**Issue by ShayYannay** [Azure/azure-cli#16524]
Hi,
I'm unable to login to azure using 'az login' running on Linux 4.4.0-18362-Microsoft x86_64 (uses Ubuntu application from windows 10)

Got the following error:
_Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd21e6da080>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))_

Tried using different network but failed all the time from the linux emulator but able to connect via Windows CMD on the same machine.

Note that i'm running under the latest azure cli 2.17.1.

Please assist, thanks!

**Comment by yonzhan** [comment]
az login

**Comment by ShayYannay** [comment]
Note that i'm using WSL (https://docs.microsoft.com/en-us/windows/wsl/install-win10) installed via Ubuntu app from Windows Store.

Tried 'nslookup login.microsoftonline.com' but keeping getting blocked, i'm able to nslookup for example to google.com

**Comment by jiasli** [comment]
Azure CLI relies on https://login.microsoftonline.com/ for authentication. If DNS lookup fails, CLI will simply not work. 

Could you share the result of `nslookup login.microsoftonline.com` when you run it from WSL? 

This issue has been reported before at https://github.com/microsoft/WSL/issues/5991. Could you try changing `/etc/resolv.conf` to Google's `8.8.8.8` and `8.8.8.4` and see if that works?

**Comment by ShayYannay** [comment]
Thanks @jiasli it appear that this issue is a communication problem with WSL as you mentioned above. 
I've asked 2 of my colleges to assist and they recommended one of the following solutions:
1) Modify /etc/hosts and add entry for login.microsoftonline.com
2) A more general solution follow the steps in here - https://github.com/microsoft/WSL/issues/5256#issuecomment-666545999

**Comment by jiasli** [comment]
I am glad to know the issue of Azure CLI is fixed, and many thanks for the helpful link. For anything else regarding Azure CLI, please feel free to let us know.
