### ISSUE TITLE
error when running `az vmss reimage` from azure cloud shell

### ISSUE THREAD

**Issue by gietal** [Azure/azure-cli#16522]
## Describe the bug

**Command Name**
`az vmss reimage`

**Errors:**
```
'VirtualMachineScaleSetsOperations' object has no attribute 'reimage'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/cli/core/__init__.py, ln 784, in default_command_handler
    return op(**command_args)
cli/command_modules/vm/custom.py, ln 2787, in reimage_vmss
    return sdk_no_wait(no_wait, client.virtual_machine_scale_sets.reimage, resource_group_name, vm_scale_set_name)
AttributeError: 'VirtualMachineScaleSetsOperations' object has no attribute 'reimage'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss reimage --resource-group {} --name {}`

## Expected Behavior
according to `az vmss reimage --help`, running the above command should reimage all the VMs in the VMSS

## Environment Summary
```
Linux-4.15.0-1103-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.17.1
azure-cli-ml 1.19.0

Extensions:
ai-examples 0.2.5
azure-cli-ml 1.19.0

```

**Comment by yungezz** [comment]
hi @qwordy could you pls confirm if this issue fixed.

**Comment by qwordy** [comment]
Hi @gietal, thank you for reporting this issue. It is fixed by https://github.com/Azure/azure-cli/commit/3269d06a0ab0ad235a1ad1a04b944e3f19b746ef.
Release date is 1/19/2021.
