### ISSUE TITLE
VM automation randomly fails

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1652]
https://travis-ci.org/Azure/azure-cli/builds/189282184

It claimed that one dynamically created configuration file is missing.

**Comment by derekbekoe** [comment]
FYI: I saw this and restarted the build to see if it will fix itself.

**Comment by derekbekoe** [comment]
As I don't see how the PR that was merged would cause such a failure.

**Comment by troydai** [comment]
I suspect the parallel test run has something to do with it.

**Comment by troydai** [comment]
both `VMExtensionInstallTest` and `VMSSExtensionInstallTest` create a `private_config.json` and delete during clean up. this is the conflict.

**Comment by tjprescott** [comment]
I am working on a VM PR, so I'll update the filename in that.

**Comment by troydai** [comment]
https://github.com/Azure/azure-cli/issues/1652

**Comment by troydai** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/1653
