### ISSUE TITLE
webapp:Reference clarification request for az webapp up

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#16523]
**Resource Provider**
az webapp up [examples](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_up-examples)

**Description of Work Requested**
I was asked to clarify this statement: "Deploy new code to an app that was originally created using the same command".  If the following statement is correct, can the auto-gen reference content be updated?  Interpretation: _"Deploy new code to a webapp running the Azure CLI command from the folder where the code to be deployed exists.  If deploying to an existing webapp with the same name and location, you will be over-writing the existing code.  If you want to change a portion of your webapp, use az webapp update."_

**Minimum API Version Required**
not applicable

**Swagger Link**
not applicable

**Target Date**
Auto-gen reference content update schedule

**Comment by yonzhan** [comment]
webapp

**Comment by calvinsID** [comment]
Hi @dbradish-microsoft, wondering if you can clarify the ask - is it to update this 
![image](https://user-images.githubusercontent.com/14339314/105221402-e931f580-5b0d-11eb-9b56-2619a85a5647.png) to 
_"Deploy new code to a webapp running the Azure CLI command from the folder where the code to be deployed exists. If deploying to an existing webapp with the same name and location, you will be over-writing the existing code. If you want to change a portion of your webapp, use az webapp update."_?

**Comment by dbradish-microsoft** [comment]
@calvinsID , love your GitHub name, btw.  :-)

"yes" to your question assuming my statement is correct.  I had a support call on this sentence, and I feel I made assumptions in my response.

**Comment by calvinsID** [comment]
@dbradish-microsoft haha thanks, not the most original name in the world 

hmm I'm actually more in favour of removing the `az webapp up -n MyUniqueAppName -l locationName` example, since there are already examples for `az webapp up -n MyUniqueAppName` and `a webapp up -l locationName` individually. thoughts?
