### ISSUE TITLE
az redis create fails

### ISSUE THREAD

**Issue by serprex** [Azure/azure-cli#16527]
## Describe the bug

**Command Name**
`az redis create`

**Errors:**
```
'RedisOperations' object has no attribute 'create'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 330, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 784, in default_command_handler
    return op(**command_args)
cli/command_modules/redis/custom.py, ln 98, in cli_redis_create
    return client.create(resource_group_name, name, params)
AttributeError: 'RedisOperations' object has no attribute 'create'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az redis create --resource-group {} --name {} --sku Basic --vm-size C0 --minimum-tls-version 1.2`

## Environment Summary
```
Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.31
Python 3.9.1
Installer: PIP

azure-cli 2.17.1

Extensions:
front-door Unknown
azure-devops 0.19.0

```
## Additional Context
I'm using Debian Bullseye (AZREPO buster) with WSL2. Creating a resource group worked fine. This worked fine a few months ago

**Comment by yonzhan** [comment]
redis

**Comment by serprex** [comment]
I've checked that there's no create method in /usr/lib/python3/dist-packages/azure/mgmt/redis/operations/_redis_operations.py for me

Meanwhile my colleague verified that there was a create method on their system. Not sure how to figure out what version of azure.mgmt I have

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to the latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
