### ISSUE TITLE
issue with Azure CLI command

### ISSUE THREAD

**Issue by nameier** [Azure/azure-cli#16525]
## Describe the bug

**Command Name**
`az vmss update`

**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
python3.6/site-packages/msrest/serialization.py, ln 1416, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
...
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss update -g {} -n {} --set {}`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.17.1

Extensions:
image-copy-extension 0.2.8
maintenance 1.1.0
vm-repair 0.3.4

```

**Comment by yungezz** [comment]
hi @qwordy could you pls help to have a look?

**Comment by qwordy** [comment]
@nameier I have seen this issue multiple times. I will prioritize it.

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/16324

**Comment by BigCat20196** [comment]
hi @nameier I didn't have this problem in my test environment. My azure cli version is 2.20.0. Could you try to upgrade the version first to see if this problem is solved?

**Comment by nameier** [comment]
Hi @BigCat20196 I haven't seen this in a while either.  Assuming it was either a one-time thing, or it has since been fixed in the newer releases of CLI.  Thanks for checking back in!
