### ISSUE TITLE
bug in mslearn-improve-app-scalability-resiliency-with-load-balancer -  fails to execute command - az network nic ip-config update

### ISSUE THREAD

**Issue by abdullah1133** [Azure/azure-cli#16539]
## Describe the bug

**Command Name**
`az network nic ip-config update`

**Errors:**
```
ResourceNotFoundError: (ResourceNotFound) The Resource 'Microsoft.Network/networkInterfaces/webNic2' under resource group 'learn-a4e2818d-e048-42b9-8c46-747a4651f2fb' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network nic ip-config update --resource-group {} --nic-name {} --name {} --lb-name {} --lb-address-pools {}`

## Environment Summary
```
Linux-4.15.0-1103-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.17.1
azure-cli-ml 1.19.0

Extensions:
ai-examples 0.2.5
azure-cli-ml 1.19.0

```

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Cannot reproduce you issue. Please upgrade cli by command
```
az upgrade
```
