### ISSUE TITLE
WebApp:Incorrect Optional Parameters listed for appsettings set

### ISSUE THREAD

**Issue by JFolberth** [Azure/azure-cli#16535]
For appsettings set it lists all parameters as optional.  This is not accurate.  I am not 100% sure on this and this why I am not submitting a PR.  

From my playing around I beleve it should be either --ids required or --name AND --resource-group required like it is in the list command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* Content: [az webapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az_webapp_config_appsettings_set)
* Content Source: [latest/docs-ref-autogen/webapp/config/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
@JFolberth - Thanks for for your support! We will update our documentation to list out the Required parameters . But still you can use the command as it wont allow the command execution without required parameters.

**Comment by JFolberth** [comment]
Thanks, yes I've been able to use the command as noted above. Just wanted to provide feedback on the documentation.

**Comment by Kotasudhakarreddy** [comment]
Here the help command `-h` is showing the required parameters correctly. 
![image](https://user-images.githubusercontent.com/60102891/158010441-41f612c5-4c2f-482b-858a-3708d385c3d1.png)

@panchagnula documentation is generated automatically based on the `_help.py`. Can you please confirm if we need to check this issue with the `core-cli` team.

**Comment by seligj95** [comment]
Thanks for the feedback. Closing this and will address doc updates.
