### ISSUE TITLE
WebApp: az webapp config ssl create has inconsistent output between Linux and Windows

### ISSUE THREAD

**Issue by jlienSage** [Azure/azure-cli#16538]
## Describe the bug

The command `az webapp config ssl create` outputs the following on Windows:
```json
{
  "canonicalName": "something.com",
  "cerBlob": null,
  "expirationDate": "2021-07-13T23:59:59+00:00",
  "friendlyName": "",
  "hostNames": [
    "something.com"
  ],
  "hostingEnvironmentProfile": null,
  "id": "",
  "issueDate": "2021-01-14T00:00:00+00:00",
  "issuer": "GeoTrust TLS DV RSA Mixed SHA256 2020 CA-1",
  "keyVaultId": "",
  "keyVaultSecretName": "",
  "keyVaultSecretStatus": "Initialized",
  "kind": null,
  "location": "West US",
  "name": "something.com",
  "password": null,
  "publicKeyHash": null,
  "resourceGroup": "my-rg",
  "selfLink": null,
  "serverFarmId": null,
  "siteName": null,
  "subjectName": "something.com",
  "tags": null,
  "thumbprint": "",
  "type": "Microsoft.Web/certificates",
  "valid": null
}
```
Linux:
```json
{
  "id": "",
  "location": "West US",
  "name": "something.com",
  "properties": {
    "canonicalName": "something.com",
    "cerBlob": null,
    "expirationDate": "2021-07-13T23:59:59+00:00",
    "friendlyName": "",
    "hostNames": [
      "something.com"
    ],
    "hostingEnvironment": null,
    "hostingEnvironmentProfile": null,
    "issueDate": "2021-01-14T00:00:00+00:00",
    "issuer": "GeoTrust TLS DV RSA Mixed SHA256 2020 CA-1",
    "keyVaultId": "",
    "keyVaultSecretName": "",
    "keyVaultSecretStatus": "Initialized",
    "password": null,
    "pfxBlob": null,
    "publicKeyHash": null,
    "resourceGroup": "my-rg",
    "selfLink": null,
    "serverFarmId": null,
    "siteName": null,
    "subjectName": "something.com",
    "tags": null,
    "thumbprint": "",
    "toDelete": null,
    "valid": null,
    "webSpace": "my-rg-WestUSwebspace"
  },
  "resourceGroup": "my-rg",
  "type": "Microsoft.Web/certificates"
}
```

**Command Name**
`az webapp config ssl create`

## To Reproduce:
Run `az webapp config ssl create`.

## Expected Behavior
Output is the same on both platforms.

## Environment Summary
WSL (Ubuntu)
```
Linux-4.19.104-microsoft-standard-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.17.1

```
Windows
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1

```

## Additional Notes

`az webapp config ssl show` has the same output as `az webapp config ssl create` does Windows on both platforms.

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
@panchagnula - CLI command receives this response in different formats for Linux and Windows Apps  from API.  Could you please check and respond if this is not an expected behavior.

**Comment by panchagnula** [comment]
@jlienSage is this the diff b/w Linux & windows or re-creating an existing certificate with the same canonical name? I am guessing the "properties" section is the difference you are referring to here?

**Comment by jlienSage** [comment]
> @jlienSage is this the diff b/w Linux & windows or re-creating an existing certificate with the same canonical name? I am guessing the "properties" section is the difference you are referring to here?

@panchagnula Yes, the difference is between the Linux and Windows versions of Az CLI. On Windows, creating a certificate only has the `properties` section as output while Linux has more information. However, the command `az webapp config ssl show` has the same behavior on both platforms, only returning the `properties` section.

**Comment by Kotasudhakarreddy** [comment]
@panchagnula Just sending you a gentle reminder on this issue.

**Comment by StrawnSC** [comment]
Unable to repro. I tested today with the latest version of the CLI (2.45.0) on both WSL and windows. `az webapp config ssl create` always seems to return a message saying "Managed Certificate creation in progress..." and nothing else (no JSON)
