### ISSUE TITLE
az group delete : RUNNING (Unable to delete resource group

### ISSUE THREAD

**Issue by suaknab** [Azure/azure-cli#16545]
## Describe the bug

**Command Name**
`az group delete`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group delete --name {}`

## Environment Summary
```
Linux-4.15.0-1103-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.17.1
azure-cli-ml 1.19.0

Extensions:
ai-examples 0.2.5
azure-cli-ml 1.19.0

```

**Comment by yonzhan** [comment]
ARM

**Comment by RakeshMohanMSFT** [comment]
@suaknab We sincerely apologies for the delay. Please update az cli to latest version [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and reopen this issue if you still face the issue
