### ISSUE TITLE
Unable to run az aks get-credentials

### ISSUE THREAD

**Issue by rajbiswal** [Azure/azure-cli#16546]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
'str' object has no attribute 'get'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/acs/custom.py, ln 1163, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
cli/command_modules/acs/custom.py, ln 1099, in _handle_merge
    if not existing.get(key):
AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --name {} --resource-group {}`

## Environment Summary
```
macOS-10.14.3-x86_64-i386-64bit
Python 3.8.7
Installer: HOMEBREW

azure-cli 2.17.1

```

**Comment by yonzhan** [comment]
aks

**Comment by rajbiswal** [comment]
I am able to resolve the issue by the following steps:

Created ~/.kube/config with the following contents:
apiVersion: v1
clusters: []
kind: Config

$ az aks get-credentials --name IDE_Che_Cluster_Dev --resource-group IDE_Che
/Users/RajendraBiswal/.kube/config has permissions "644".
It should be readable and writable only by its owner.
Merged "IDE_Che_Cluster_Dev" as current context in /Users/RajendraBiswal/.kube/config
