### ISSUE TITLE
Wording for --license-type is vague

### ISSUE THREAD

**Issue by JiandongRuan** [Azure/azure-cli#16541]
I ran into an issue with enabling Azure Hybrid Benefit on VMSS. It took Azure support 2+ weeks to figure out what's going on. Eventually, the issue was resolved with the help from Azure dev team.

If the documentation of "--license-type" were clear, the Azure support ticket could have been avoided.

Current wording:

"To enable Azure Hybrid Benefit for Windows Server, use 'Windows_Server'"

This give people incorrect impression that Azure Hybrid Benefit will be enabled on the existing VMs in the VMSS after the license type is set on the VMSS. But this is not the case. Users are still required to run the following commands in order for the changes to be applied on the existing VMs.

```
az vmss update-instances -g "__replaced_with_rg_name__" -n "__replace_with_vmss_name" --instance-ids "*"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0408c294-207a-2b72-7b93-e09121602b75
* Version Independent ID: 852cb67b-70c6-b811-3b0a-5d5b84b8a911
* Content: [az vmss](https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vmss.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/vmss.yml)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
add @qwordy to help with.

**Comment by qwordy** [comment]
@JiandongRuan 
We are going to add an instruction in `vmss update` help message.
Bye the way, VMSS has an "upgrade policy" that determine how VMs are brought up-to-date with the latest scale set model. 
https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-upgrade-scale-set#how-to-bring-vms-up-to-date-with-the-latest-scale-set-model
