### ISSUE TITLE
WebApp:Serialization issue with az webapp config access-restriction add

### ISSUE THREAD

**Issue by designerfh** [Azure/azure-cli#16559]
## Describe the bug

**Command Name**
`az webapp config access-restriction add`

**Errors:**
```
'ServiceTag' is not valid value for enum <enum 'IpFilterTag'>
Traceback (most recent call last):
Temp\pip-unpacked-wheel-qa9gi9_9\msrest\serialization.py, ln 987, in serialize_enum
enum.py, ln 293, in __call__
enum.py, ln 535, in __new__
enum.py, ln 548, in _missing_
ValueError: 'ServiceTag' is not a valid IpFilterTag

...

Temp\pip-unpacked-wheel-qa9gi9_9\msrest\serialization.py, ln 771, in serialize_data
Temp\pip-unpacked-wheel-qa9gi9_9\msrest\serialization.py, ln 994, in serialize_enum
msrest.exceptions.SerializationError: 'ServiceTag' is not valid value for enum <enum 'IpFilterTag'>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config access-restriction add --resource-group {} --name {} --action {} --rule-name {} --ip-address {} --priority {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1

Extensions:
aks-preview 0.4.72
front-door 1.0.9
storage-preview 0.7.0
webapp 0.3.1

```

**Comment by yonzhan** [comment]
webapp

**Comment by Kotasudhakarreddy** [comment]
@designerfh - Unable to repro this issue in Version `azure-cli 2.17.1` and latest version `azure-cli 2.18.0`. Please reopen this issue with `debug` details if you still repro it.

**Comment by rodney-almeida** [comment]
We having this same issue. If the webapp already has an access-restriction rule that is of the type ServiceTag, this command fails to add any more.

ERROR: CLIInternalError: The command failed with an unexpected error. Here is the traceback:
ERROR: 'ServiceTag' is not valid value for enum <enum 'IpFilterTag'>
