### ISSUE TITLE
Unable to create image definition with V2 Hyper-V Genration

### ISSUE THREAD

**Issue by tleepa** [Azure/azure-cli#16564]
## Describe the bug:
Since azure-cli 2.17.0 I cannot create image definition with Hyper-V Generation 2.
When "V2" is provided as hvgen parameter value, V1 is created instead.
Was working fine in 2.16.0.

**Command Name**
`az sig image-definition create`

**Errors:**
No errors, V1 image definition is created, instead of V2.

```json
{
  "description": null,
  "disallowed": null,
  "endOfLifeDate": null,
  "eula": null,
  "features": null,
  "hyperVGeneration": "V1",
  "id": "/subscriptions/{redacted}/resourceGroups/rg/providers/Microsoft.Compute/galleries/sig/images/imgdef",
  "identifier": {
    "offer": "off",
    "publisher": "pub",
    "sku": "sku"
  },
  "location": "brazilsouth",
  "name": "imgdef",
  "osState": "Generalized",
  "osType": "Windows",
  "privacyStatementUri": null,
  "provisioningState": "Succeeded",
  "purchasePlan": null,
  "recommended": null,
  "releaseNoteUri": null,
  "resourceGroup": "rg",
  "tags": {},
  "type": "Microsoft.Compute/galleries/images"
}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az group create --location westeurope --name rg`
- `az sig create --resource-group rg --gallery-name sig`
- `az sig image-definition create --resource-group rg --gallery-name sig --gallery-image-definition imgdef --os-type Windows --hyper-v-generation V2 --publisher pub --offer off --sku sku`

## Expected Behavior
Image definition with Hyper-V Generation V2 is created.

## Environment Summary
```
Linux-3.10.0-1160.6.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Python 3.6.8
Installer: RPM

azure-cli 2.17.1
```

**Comment by yonzhan** [comment]
Compute

**Comment by yungezz** [comment]
hi @qwordy could you pls help to check is there service behavior change? thanks

**Comment by qwordy** [comment]
Hi @tleepa , thank you for reporting this issue. It is fixed by https://github.com/Azure/azure-cli/commit/4191edbe7fbef2997a02eacc53596da0c5a937f4.
Release date is 1/19/2021. Have a try after the new version is released.

**Comment by tleepa** [comment]
Confirm, that it works fine again with 2.18.0.
Thank you :)

**Comment by qwordy** [comment]
> 
> 
> Confirm, that it works fine again with 2.18.0.
> Thank you :)

Glad to know that!
