### ISSUE TITLE
az webapp create fails

### ISSUE THREAD

**Issue by kaubuchon** [Azure/azure-cli#16565]
**Command Name**
`az webapp create`

**Errors:**
```
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 659, in execute
azure\cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 714, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 37, in _ex_handler
azure\cli\core\commands\__init__.py, ln 693, in _run_job
azure\cli\core\commands\__init__.py, ln 330, in __call__
pip-unpacked-wheel-34tyr6f2\azure\cli\core\__init__.py, ln 784, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 156, in create_webapp
azure\cli\command_modules\appservice\custom.py, ln 1060, in _format_fx_version
AttributeError: 'NoneType' object has no attribute 'lower'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Trying to deploy Windows .NET core web app.  Resource group already exists...
az appservice plan create -n myplan -g myresource --hyper-v --sku P1V3 // this was successful

az webapp create -g myresource -p myplan -n myname --debug -r "DOTNETCORE|3.1"  //this failed
- `az webapp create -g {} -p {} -n {} --debug -r {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1

```

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14287
