### ISSUE TITLE
az acr login API version 2020-11-01-preview does not have operation group 'registries'

### ISSUE THREAD

**Issue by phlbrz** [Azure/azure-cli#16566]
## Describe the bug

**Command Name**
`az acr login`

**Errors:**
```
API version 2020-11-01-preview does not have operation group 'registries'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/acr/_client_factory.py, ln 20, in cf_acr_registries
    return get_acr_service_client(cli_ctx).registries
azure/mgmt/containerregistry/_container_registry_management_client.py, ln 304, in registries
    raise ValueError("API version {} does not have operation group 'registries'".format(api_version))
ValueError: API version 2020-11-01-preview does not have operation group 'registries'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az acr login --name myregistry`

## Environment Summary
```
Linux-5.10.0-1-amd64-x86_64-with-glibc2.31
Python 3.9.1
Installer: PIP
Linux MYMACHINE 5.10.0-1-amd64 #1 SMP Debian 5.10.4-1 (2020-12-31) x86_64 GNU/Linux

azure-cli 2.17.1

Extensions:
azure-devops 0.19.0

docker version
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:34 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
## Additional Context

```
pip --version
pip 20.1.1 from /usr/lib/python3/dist-packages/pip (python 3.9)

pip show azure-mgmt-containerregistry
Name: azure-mgmt-containerregistry
Version: 8.0.0b1
Summary: Microsoft Azure Container Registry Client Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by:
```

**Comment by phlbrz** [comment]
- Same problem with `az acr list --resource-group myresource`

```
az acr list --resource-group myresource
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
API version 2020-11-01-preview does not have operation group 'registries'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/home/t319806/.local/lib/python3.9/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 775, in default_command_handler
    client = client_factory(cmd.cli_ctx, command_args) if client_factory else None
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acr/_client_factory.py", line 20, in cf_acr_registries
    return get_acr_service_client(cli_ctx).registries
  File "/usr/lib/python3/dist-packages/azure/mgmt/containerregistry/_container_registry_management_client.py", line 304, in registries
    raise ValueError("API version {} does not have operation group 'registries'".format(api_version))
ValueError: API version 2020-11-01-preview does not have operation group 'registries'
To open an issue, please run: 'az feedback'
```

**Comment by phlbrz** [comment]
- Took a look at `docker run -it mcr.microsoft.com/azure-cli:2.17.1` and `azure-mgmt-containerregistry==3.0.0rc16`
- So I downgraded with pip:
pip install 'azure-mgmt-containerregistry==3.0.0rc16'
- Same problem.

**Comment by phlbrz** [comment]
I did the first option in the workaround https://github.com/Azure/azure-cli/issues/15627#issuecomment-716129300

```
alias az='docker run --rm -it -v ~/.azure:/root/.azure mcr.microsoft.com/azure-cli az '
az acr login --name myregistry 
You may want to use 'az acr login -n alurasportsfeliperegistry --expose-token' to get an access token, which does not require Docker to be installed.
An error occurred: DOCKER_COMMAND_ERROR
Please verify if Docker client is installed and running.
```

**Comment by yonzhan** [comment]
acr

**Comment by phlbrz** [comment]
- As my last workaround and using docker login command, I have successfully logged in and pushed my image.

```
docker login -u myuserregistry myregistry.azurecr.io
Password: 
WARNING! Your password will be stored unencrypted in /home/myuser/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

- But I filled this issue to help others to find some workaround while it doesn't have a solution.

Thank's!

**Comment by yugangw-msft** [comment]
@fengzhou-msft, this is Azure CLI package issue

**Comment by adewaleo** [comment]
summary: I think uninstalling 8.0.0b1 and installing 3.0.0rc16 should solve the problem because 3.0.0rc16 is more up to date. see [azure-mgmt-containerregistry's release history](https://pypi.org/project/azure-mgmt-containerregistry/3.0.0rc16/#history)

@phlbrz how exactly did you install the CLI. It seems you are using PIP. When CLI is packaged, it includes the py packages and versions defined in one of the requirements.txt [files found here](https://github.com/Azure/azure-cli/tree/dev/src/azure-cli). I can see your pip installed CLI is using the **highest** version azure-mgmt-containerregistry package and not the **latest** version. 

Unfortunately (and I don't know why) our highest version which you have installed is  [azure-mgmt-containerregistry 8.0.0b1](https://pypi.org/project/azure-mgmt-containerregistry/8.0.0b1/), however the latest version which should have support for the latest ARM API version (2020-11-01-preview) is the following [azure-mgmt-containerregistry 3.0.0rc16](https://pypi.org/project/azure-mgmt-containerregistry/3.0.0rc16/). 


cc: @yugangw-msft @yonzhan @fengzhou-msft

**Comment by phlbrz** [comment]
> summary: I think uninstalling azure-mgmt-containerregistry 8.0.0b1 and installing 3.0.0rc16 should solve the problem because 3.0.0rc16 is more up to date. see [azure-mgmt-containerregistry's release history](https://pypi.org/project/azure-mgmt-containerregistry/3.0.0rc16/#history)
> 
> @phlbrz how exactly did you install the CLI. It seems you are using PIP. When CLI is packaged, it includes the py packages and versions defined in one of the requirements.txt [files found here](https://github.com/Azure/azure-cli/tree/dev/src/azure-cli). I can see your pip installed CLI is using the **highest** version azure-mgmt-containerregistry package and not the **latest** version.
> 
> Unfortunately (and I don't know why) our highest version which you have installed is [azure-mgmt-containerregistry 8.0.0b1](https://pypi.org/project/azure-mgmt-containerregistry/8.0.0b1/), however the latest version which should have support for the latest ARM API version (2020-11-01-preview) is the following [azure-mgmt-containerregistry 3.0.0rc16](https://pypi.org/project/azure-mgmt-containerregistry/3.0.0rc16/).
> 
> cc: @yugangw-msft @yonzhan @fengzhou-msft
Hi @adewaleo ,
I did a debian install and then a pip install.
I really don't know who installed version `azure-mgmt-containerregistry 8.0.0b1`.
But I downgraded with pip in https://github.com/Azure/azure-cli/issues/16566#issuecomment-761701057 and had the same problem, I don't know others py packages are required to downgrade together to address better what was my mistake.
I cannot reproduce anymore 'cause I finished my training course and my free trial too, sorry.
Thank's.

**Comment by fengzhou-msft** [comment]
@phlbrz please follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt&view=azure-cli-latest to install the `azure-cli` package in microsoft repository.

**Comment by fengzhou-msft** [comment]
@phlbrz did you mean `apt install azure-cli` with debian install? Did you add the `microsoft` respository first? If not, please run `sudo apt remove azure-cli -y && sudo apt autoremove -y` to remove the `azure-cli` apt package first then follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt&view=azure-cli-latest to install the `azure-cli` package from `microsoft` repository.

**Comment by dod38fr** [comment]
Note that on Debian testing and unstable, the instructions mentioned above install Debian's version of `azure-cli` because Debian's version (`2.18.0-1`) is greater than Microsoft's version (`2.18.0-1~buster`).

To make sure that Microsoft's `azure-cli` is installed, you should run `sudo apt install azure-cli-2.18.0-1~buster` after Microsoft installation instructions.

HTH

**Comment by fengzhou-msft** [comment]
Close as it's caused by an incompatible version of `azure-mgmt-containerregistry` installed together with `azure-cli`.
