### ISSUE TITLE
Command "az network application-gateway http-listener create" does not work.

### ISSUE THREAD

**Issue by mytuanZ** [Azure/azure-cli#16567]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I have an application gateway and I want to create a http-listener on port 8099.
Command: `az network application-gateway http-listener create `does not work.
**To Reproduce**

Run below command from Azure Cloud Shell Bash.

`az network application-gateway http-listener create -g infra-validation --gateway-name overlap-test-appgw --name appGatewayHttpListener8099 --frontend-port 8099 --subscription xxx-DEV-01`
**Expected behavior**

Http-listener named appGatewayHttpListener8099 on port 8099 should be created.
**Environment summary**

Error logs: 
`BadRequestError: (InvalidResourceReference) Resource /subscriptions/ef9xxx1c9/resourceGroups/infra-validation/providers/Microsoft.Network/applicationGateways/overlap-test-appgw/frontendPorts/8099 referenced by resource /subscriptions/ef9xxxx1c9/resourceGroups/infra-validation/providers/Microsoft.Network/applicationGateways/overlap-test-appgw/httpListeners/appGatewayHttpListener8099 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.`

I use Azure Cloud Shell Bash to run this command. I'm able to create this http-listener on Azure Portal. If I run this command after creating it on Azure portal , I got this `Item 'appGatewayHttpListener8099' already exists. Replacing with new values.`
**Additional context**

**Comment by yonzhan** [comment]
network

**Comment by mytuanZ** [comment]
I figured it out, to create **http-listener on port 8099**, I need to create **front-end port 8099** first, with this command `az network application-gateway frontend-port create `. I couldn't find out the docs that mentions this action.
