### ISSUE TITLE
Cant change function app plan tier.

### ISSUE THREAD

**Issue by gregix008** [Azure/azure-cli#16563]
## Describe the bug

**Command Name**
`az functionapp update`

**Errors:**
```
'NoneType' object has no attribute 'resource_group'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/core/commands/arm.py, ln 527, in handler
    instance = custom_function(instance=instance, **custom_func_args)
cli/command_modules/appservice/custom.py, ln 648, in update_functionapp
    dest_plan_info = client.app_service_plans.get(instance.resource_group, plan)
AttributeError: 'NoneType' object has no attribute 'resource_group'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp update --name {} --resource-group {} --plan {}`

## Environment Summary
```
Linux-4.15.0-1103-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.17.1
azure-cli-ml 1.19.0

Extensions:
ai-examples 0.2.5
azure-cli-ml 1.19.0

```

**Comment by gregix008** [comment]
this is the full command i run : az functionapp update --name $functionAppName --resource-group $resourceGroup --plan $consumptionplan

**Comment by yonzhan** [comment]
functionapp

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/14287

**Comment by RakeshMohanMSFT** [comment]
@gregix008 This issue is fixed. Please upgrade to latest version of Az CLI [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli). And reopen this if you are still facing issue
