### ISSUE TITLE
Telemetry reports issue when there is no valid account login 

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-cli#16579]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When there is no account login, although my command succeed. It will print the following exception to me when using `--debug`. Please catch the exception and not report to customer.

![image](https://user-images.githubusercontent.com/49508232/104982934-a8bb7480-5a46-11eb-94b1-e18da496f24d.png)

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Telemetry
