### ISSUE TITLE
 login hangs for both az login and az login --use-device-code

### ISSUE THREAD

**Issue by brucezlata** [Azure/azure-cli#16571]
azure-cli  2.17.1, PowerShell 5.1
(1) az login
Still hangs on "https://localhost:8400/?code=0" even I upgrade to 2.17.1.

(2) az login --use-device-code
Will block with below message.
Help us keep your device secure
Your sign-in was successful but your admin requires the device requesting access to be managed by Microsoft to access this resource.

Request Id: 14900afa-c3ea-4525-b746-caddc6470700
Correlation Id: 2fa8f17f-f5c2-4f95-8cd4-efa24e9cf54c
Timestamp: 2021-01-18T04:58:47.295Z
App name: Microsoft Azure CLI
App id: 04b07795-8ddb-461a-bbee-02f9e1bf7b46
IP address: 167.220.233.202
Device identifier: 30990e80-64c9-483e-93f0-03ece298970c
Device platform: Windows 10
Device state: Compliant

VPN: yes, I connect to MSFTVPN
Intune: yes, my device has enrolled and it can be found in Company portal.

**Comment by yonzhan** [comment]
az login

**Comment by brucezlata** [comment]
az login screeshot
![image](https://user-images.githubusercontent.com/21032579/104879194-5459bb80-5998-11eb-99ef-57f18d4767ec.png)

**Comment by jiasli** [comment]
The redirection to `localhost` should happen on `http`, instead of `https`. Please see https://github.com/Azure/azure-cli/issues/10426#issuecomment-528308713 for the solution.

**Comment by brucezlata** [comment]
Thanks @jiasli. I can use az login now. But still --use-device-code not work.

**Comment by craftzneko** [comment]
I get this exact issue, i dont see any solution but its closed?
