### ISSUE TITLE
Wrong sample command for configuring the HTTP->HTTPS redirect

### ISSUE THREAD

**Issue by marxxxx** [Azure/azure-cli#16574]
The sample command for configuring the HTTP->HTTPS redirect is wrong imho.

az cdn endpoint rule add -g RG_PerformancePlattform_Europe_West_QA -n dev-eremabluport --profile-name dev-erema-cdn --order 1 --rule-name "redirect" --match-variable RequestScheme --operator Equal --match-values **HTTPS** --action-name "UrlRedirect" --redirect-protocol Https --redirect-type Moved

should be

az cdn endpoint rule add -g RG_PerformancePlattform_Europe_West_QA -n dev-eremabluport --profile-name dev-erema-cdn --order 1 --rule-name "redirect" --match-variable RequestScheme --operator Equal --match-values **HTTP** --action-name "UrlRedirect" --redirect-protocol Https --redirect-type Moved

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fef54fc4-b4a8-d366-40de-a0ae2586961d
* Version Independent ID: 1231852d-d3b4-9bcf-e9d4-ba12cffb7603
* Content: [az cdn endpoint rule](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint/rule?view=azure-cli-latest#az_cdn_endpoint_rule_add)
* Content Source: [latest/docs-ref-autogen/cdn/endpoint/rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cdn/endpoint/rule.yml)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cdn

**Comment by marxxxx** [comment]
Apparently this has already been reported (https://github.com/Azure/azure-cli/issues/14582)
