### ISSUE TITLE
az webapp up failed with 502 in eastus2euap

### ISSUE THREAD

**Issue by najian** [Azure/azure-cli#16572]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I am following https://docs.microsoft.com/en-us/azure/app-service/tutorial-python-postgresql-app?tabs=bash%2Cclone#41-create-the-app-service-app to create a web app in Eastus2euap(this region is specific for my business requirement) and I already registed feature Microsoft.Resouces/EUAPParticipation and Microsoft.Web/EastUS2EUAPRegionEnabled

request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/937bc588-a144-4083-8612-5f9ffbbddb14/resourceGroups/DjangoPostgres-tutorial-rg/providers/Microsoft.Web/serverfarms/DjangoPostgres-tutorial-plan?api-version=2019-08-01 (Caused by ResponseError('too many 502 error responses',))

**To Reproduce**

az webapp up --resource-group DjangoPostgres-tutorial-rg --location eastus2euap --plan DjangoPostgres-tutorial-plan --sku B1 --name najitest
using my subscription 937bc588-a144-4083-8612-5f9ffbbddb14
**Expected behavior**

A web app in eastus2 euap created

**Environment summary**

azure-cli                         2.11.1

core                              2.11.1
telemetry                          1.0.5

Extensions:
connect                            0.0.1
db-up                              0.2.0
dev-spaces                         1.0.5

**Additional context**

**Comment by yonzhan** [comment]
webapp

**Comment by najian** [comment]
fixed by other channel
