### ISSUE TITLE
Unable to create a Postgres db from command line for my app service

### ISSUE THREAD

**Issue by kalyankrishna1** [Azure/azure-cli#16576]
## Describe the bug

**Command Name**
`az postgres server create`

**Errors:**
```
'registrationState'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 659, in execute
cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
cli\core\commands\__init__.py, ln 715, in _run_job
Local\Temp\pip-unpacked-wheel-igh1xymj\six.py, ln 703, in reraise
cli\core\commands\__init__.py, ln 693, in _run_job
cli\core\commands\__init__.py, ln 330, in __call__
...
pip-unpacked-wheel-qa9gi9_9\msrest\universal_http\requests.py, ln 275, in user_hook_cb
Temp\pip-unpacked-wheel-0i0aug_8\msrestazure\tools.py, ln 57, in register_rp_hook
Temp\pip-unpacked-wheel-0i0aug_8\msrestazure\tools.py, ln 102, in _register_rp
KeyError: 'registrationState'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres server create --resource-group {} --location {} --name {} --admin-user {} --admin-password {} --sku-name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1

```

**Comment by kalyankrishna1** [comment]
the command was

`
az postgres server create --resource-group appsvc_linux_centralus --location centralus --name mydjangodb --admin-user sa --admin-password XXXX! --sku-name GP_Gen5_2`

**Comment by yungezz** [comment]
route to appropriate team

**Comment by nachoalonsoportillo** [comment]
Not reproduceable.

#please-close
