### ISSUE TITLE
Need document on how to turn off event hub capture. set enable-capture to false won't work

### ISSUE THREAD

**Issue by rachelxj-ms** [Azure/azure-cli#16577]
--enable-capture
A boolean value that indicates whether capture description is enabled.
accepted values: false, true

But it doesn't turn off capture by setting --enable-capture to false. 

Need document on how to turn off capture.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa949ea-86b1-125e-e7d3-f0f88a2661ab
* Version Independent ID: c8351dbc-7358-ba5b-6757-3929a4a2b42b
* Content: [az eventhubs eventhub](https://docs.microsoft.com/en-us/cli/azure/eventhubs/eventhub?view=azure-cli-latest#az_eventhubs_eventhub_update)
* Content Source: [latest/docs-ref-autogen/eventhubs/eventhub.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/eventhubs/eventhub.yml)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Saglodha** [comment]
Hi @rachelxj-ms , Thanks for flagging this. We would investigate internally and would keep you posted.

**Comment by Saglodha** [comment]
Hi @rachelxj-ms, we have fixed this in our latest release: https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#event-hubs. 

Please retry the operation with false flag and let us know in case you observe any discrepancy. Thanks
