### ISSUE TITLE
Ordinal Issue with AZ CLI Forcing ASCII

### ISSUE THREAD

**Issue by mxrss2** [Azure/azure-cli#16589]
## Describe the bug

**Command Name**
`az acr run`

**Errors:**
```
'ascii' codec can't encode character '\u2714' in position 180: ordinal not in range(128)
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/command_modules/acr/_stream_utils.py, ln 64, in stream_logs
    raise_error_on_failure)
cli/command_modules/acr/_stream_utils.py, ln 131, in _stream_logs
    print(flush.decode('utf-8', errors='ignore'))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2714' in position 180: ordinal not in range(128)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr run -r {} {} -f {}`

## Environment Summary
```
Linux-5.4.0-1032-azure-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.18.0

```

**Comment by yonzhan** [comment]
acr

**Comment by yugangw-msft** [comment]
@northtyphoon this might be a known issue

**Comment by mxrss2** [comment]
Went to go look at the container that is published.. Found this variable 

`LANG=C.UTF-8
`
I set this in my existing container and it did not error at the issue it was.. So this might be a viable work around.

**Comment by mxrss2** [comment]
Yea that does indeed fix it. 

Work around till remided in CLI Tooling is to export ENVIRONMENT LANG=C.UTF-8
