### ISSUE TITLE
server georestore fails even when server is available

### ISSUE THREAD

**Issue by KalyanChanumolu-MSFT** [Azure/azure-cli#16582]
## Describe the bug

Creating a new server fails with source server not found error even when the server is available in the subscription.

**Command Name**
`
az postgres server georestore --resource-group kachanum-databases --name mydemoserver-georestored --source-server kachanumtester --location eastus --sku-name GP_Gen4_8
`

**Errors:**

Deployment failed. Correlation ID: 44430fab-201a-4508-a9e6-9180b63a64b6. Subscription 'b83c1ed3-c5b6-44fb-b5ba-2b83a074c23f' does not have the server 'kachanumtester'. Please make sure that the subscription and server name are entered correctly. Please contact Microsoft support if further assistance is needed.

## Environment Summary
```
Linux-4.15.0-1103-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.17.1 *
azure-cli-ml 1.19.0

Extensions:
ai-examples 0.2.5
azure-cli-ml 1.19.0

```

**Comment by yungezz** [comment]
routing to appropriate team

**Comment by kabharati** [comment]
@KalyanChanumolu-MSFT  - I tried this and it is working , I do understand that this issue was raised few years ago and I stumbled upon this while going through old PR's. 

Please try and let me know if you need any help.

**Comment by kabharati** [comment]
#please-close
