### ISSUE TITLE
az vmss deallocate --instance-ids failed

### ISSUE THREAD

**Issue by rick-lb** [Azure/azure-cli#16585]
azure-cli                         2.18.0

core                              2.18.0
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/usr/local/airflow/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Jan 15 2021, 09:54:35) 
[GCC 8.3.0]

**it won't work if i put multiple ids like --instance-ids 6 19 but works fine if only one id provided like --instance-ids 6, here is the error**

cli.knack.cli: Command arguments: ['vmss', 'deallocate', '--resource-group', 'mygroup, '--name', 'myresource', '--subscription', 'mysubscription', '--instance-ids', '6', '19', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f55ba9638c8>, <function OutputProducer.on_global_arguments at 0x7f55ba8b16a8>, <function CLIQuery.on_global_arguments at 0x7f55ba844950>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'vmss': ['azure.cli.command_modules.vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: vm                        0.338        43       219
cli.azure.cli.core: Total (1)                 0.338        43       219
cli.azure.cli.core: Loaded 43 groups, 219 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : vmss deallocate
cli.azure.cli.core: Command table: vmss deallocate
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f55ba562e18>]
az_command_data_logger: command args: vmss deallocate --resource-group {} --name {} --subscription {} --instance-ids {} {} --debug
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/usr/local/airflow/.azure/commands'.
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f55ba515048>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f55ba46f730>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f55ba46f7b8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f55ba46f8c8>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f55ba8b1730>, <function CLIQuery.handle_query_parameter at 0x7f55ba8449d8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f55ba46f6a8>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f55ba46f840>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ComputeManagementClient
msrest.exceptions: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'
msrest.exceptions: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'

**Comment by yungezz** [comment]
hi @qwordy could you pls help to have a look?

**Comment by qwordy** [comment]
I will open an investigation into this issue.

**Comment by rick-lb** [comment]
I am wondering if there is any finding and fix.

**Comment by qwordy** [comment]
Not yet..

**Comment by qwordy** [comment]
It is caused by a recent upgrade of Azure Python SDK. A pull request has been opened to fix it.

**Comment by rick-lb** [comment]
Is this fix released? Can i ask which version includes this fix?

**Comment by qwordy** [comment]
> 
> 
> Is this fix released? Can i ask which version includes this fix?

Yes. Just download latest version.
