### ISSUE TITLE
Create metric alerts for SQL Server databases throw an error 

### ISSUE THREAD

**Issue by ovidiu10** [Azure/azure-cli#16590]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.17.1

**Describe the bug**

az monitor metrics alert create throw an error "You can't define a scope that is different from the selected target resource type"

**To Reproduce**

az monitor metrics alert create -n "CPU Critical Alert Above 90 Percent SQL Server" -g rg --scopes "/subscriptions/subid/resourceGroups/rg/providers/Microsoft.Sql/servers/sqlserver1/databases/testdb1" --condition "avg Microsoft.Sql/servers/databases/cpu_percent > 90" --description "Action will be triggered when average Azure SQL Databse CPU percentage is greater than 90%." --action /subscriptions/subid/resourceGroups/rg/providers/microsoft.insights/actionGroups/mg1 --severity 1 --subscription subid

**Expected behavior**

need to create the alert 

**Environment summary**

all envirments 

**Additional context**

az monitor metrics alert create scope SQL Server Database 

here's the debug http request 

      "description": "Action will be triggered when average Azure SQL Database CPU  percentage is greater than 90%.",
      "severity": 1,
      "enabled": true,
      "scopes": [
        "/subscriptions/subid/resourceGroups/rg/providers/Microsoft.Sql/servers/sqlserver1/databases/testdb1"
      ],
      "evaluationFrequency": "PT1M",
      "windowSize": "PT5 M",
      "targetResourceType": "Microsoft.Sql/databases",
      "targetResourceRegion": "global",

**should be "targetResourceType": "Microsoft.Sql/**servers**/databases",**
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftsqlserversdatabases 

Python code 
File "..\AppData\Local\Temp\pip-unpacked-wheel-9w5uvfh5\azure\mgmt\monitor\v2018_03_01\operations\_metric_alerts_oper
ations.py", line 289, in create_or_update
azure.mgmt.monitor.v2018_03_01.models._models.ErrorResponseException: You can't define a scope that is different from the selected target resource type.
@kairu-ms

**Comment by yonzhan** [comment]
monitor
