### ISSUE TITLE
Bug when create a app with password in aad

### ISSUE THREAD

**Issue by lihantao3** [Azure/azure-cli#16591]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When create a app with password in aad， it will return nothing in property passwordCredential. Need run the command once again to set the password

**To Reproduce**
az ad app create --display-name the-spn1111 --native-app --key-type Password --password 'QcdJY6V~--8SA1OS1o0NKV26G1OujTvQ-z'

**Expected behavior**
The output should be like as bellowd:
"passwordCredentials": [
    {
      "additionalProperties": null,
      "customKeyIdentifier": null,
      "endDate": "2022-01-20T01:59:36.534508+00:00",
      "keyId": "3f7e532c-2d98-4f07-8078-949fd2828400",
      "startDate": "2021-01-20T01:59:36.534508+00:00",
      "value": null
    }
  ],

**Environment summary**
Have tried different versions of az cli

**Additional context**
When executing the command for the first time, the passwordCredential property would be null
$ az ad app create --display-name the-spn1111 --native-app --key-type Password --password 'QcdJY6V~--8SA1OS1o0NKV26G1OujTvQ-z’
> 
> 
> 
> 
> 
> ^C
[lihantao@cen76 ~]$ az ad app create --display-name the-spn1111 --native-app --key-type Password --password 'QcdJY6V~--8SA1OS1o0NKV26G1OujTvQ-z'
{
  "acceptMappedClaims": null,
  "addIns": [],
  "allowGuestsSignIn": null,
  "allowPassthroughUsers": null,
  "appId": "f5d65f75-b8f3-4fd7-9ddd-9d7bee494134",
  "appLogoUrl": null,
  "appPermissions": null,
  "appRoles": [],
  "applicationTemplateId": null,
  "availableToOtherTenants": false,
  "deletionTimestamp": null,
  "displayName": "the-spn1111",
  "errorUrl": null,
  "groupMembershipClaims": null,
  "homepage": null,
  "identifierUris": [],
  "informationalUrls": {
    "marketing": null,
    "privacy": null,
    "support": null,
    "termsOfService": null
  },
  "isDeviceOnlyAuthSupported": null,
  "keyCredentials": [],
  "knownClientApplications": [],
  "logo@odata.mediaEditLink": "directoryObjects/c417424c-d428-4317-810e-bf9b1a53edbc/Microsoft.DirectoryServices.Application/logo",
  "logoUrl": null,
  "logoutUrl": null,
  "mainLogo@odata.mediaEditLink": "directoryObjects/c417424c-d428-4317-810e-bf9b1a53edbc/Microsoft.DirectoryServices.Application/mainLogo",
  "oauth2AllowIdTokenImplicitFlow": true,
  "oauth2AllowImplicitFlow": false,
  "oauth2AllowUrlPathMatching": false,
  "oauth2Permissions": [
    {
      "adminConsentDescription": "Allow the application to access the-spn1111 on behalf of the signed-in user.",
      "adminConsentDisplayName": "Access the-spn1111",
      "id": "0dfda669-08e5-45a6-b2cb-8d9a86aea8f3",
      "isEnabled": true,
      "type": "User",
      "userConsentDescription": "Allow the application to access the-spn1111 on your behalf.",
      "userConsentDisplayName": "Access the-spn1111",
      "value": "user_impersonation"
    }
  ],
  "oauth2RequirePostResponse": false,
  "objectId": "c417424c-d428-4317-810e-bf9b1a53edbc",
  "objectType": "Application",
  "odata.metadata": "https://graph.chinacloudapi.cn/b388b808-0ec9-4a09-a414-a7cbbd8b7e9b/$metadata#directoryObjects/@Element",
  "odata.type": "Microsoft.DirectoryServices.Application",
  "optionalClaims": null,
  "orgRestrictions": [],
  "parentalControlSettings": {
    "countriesBlockedForMinors": [],
    "legalAgeGroupRule": "Allow"
  },
  "passwordCredentials": [],
  "preAuthorizedApplications": null,
  "publicClient": true,
  "publisherDomain": "MicrosoftInternal.partner.onmschina.cn",
  "recordConsentConditions": null,
  "replyUrls": [],
  "requiredResourceAccess": [],
  "samlMetadataUrl": null,
  "signInAudience": "AzureADMyOrg",
  "tokenEncryptionKeyId": null,
  "wwwHomepage": null
}

The password will be set successfully after run the command again:

$ az ad app create --display-name the-spn1111 --native-app --key-type Password --password 'QcdJY6V~--8SA1OS1o0NKV26G1OujTvQ-z'
Found an existing application instance of "f5d65f75-b8f3-4fd7-9ddd-9d7bee494134". We will patch it
{
  "acceptMappedClaims": null,
  "addIns": [],
  "allowGuestsSignIn": null,
  "allowPassthroughUsers": null,
  "appId": "f5d65f75-b8f3-4fd7-9ddd-9d7bee494134",
  "appLogoUrl": null,
  "appPermissions": null,
  "appRoles": [],
  "applicationTemplateId": null,
  "availableToOtherTenants": false,
  "deletionTimestamp": null,
  "displayName": "the-spn1111",
  "errorUrl": null,
  "groupMembershipClaims": null,
  "homepage": null,
  "identifierUris": [],
  "informationalUrls": {
    "marketing": null,
    "privacy": null,
    "support": null,
    "termsOfService": null
  },
  "isDeviceOnlyAuthSupported": null,
  "keyCredentials": [],
  "knownClientApplications": [],
  "logo@odata.mediaEditLink": "directoryObjects/c417424c-d428-4317-810e-bf9b1a53edbc/Microsoft.DirectoryServices.Application/logo",
  "logoUrl": null,
  "logoutUrl": null,
  "mainLogo@odata.mediaEditLink": "directoryObjects/c417424c-d428-4317-810e-bf9b1a53edbc/Microsoft.DirectoryServices.Application/mainLogo",
  "oauth2AllowIdTokenImplicitFlow": true,
  "oauth2AllowImplicitFlow": false,
  "oauth2AllowUrlPathMatching": false,
  "oauth2Permissions": [
    {
      "adminConsentDescription": "Allow the application to access the-spn1111 on behalf of the signed-in user.",
      "adminConsentDisplayName": "Access the-spn1111",
      "id": "0dfda669-08e5-45a6-b2cb-8d9a86aea8f3",
      "isEnabled": true,
      "type": "User",
      "userConsentDescription": "Allow the application to access the-spn1111 on your behalf.",
      "userConsentDisplayName": "Access the-spn1111",
      "value": "user_impersonation"
    }
  ],
  "oauth2RequirePostResponse": false,
  "objectId": "c417424c-d428-4317-810e-bf9b1a53edbc",
  "objectType": "Application",
  "odata.metadata": "https://graph.chinacloudapi.cn/b388b808-0ec9-4a09-a414-a7cbbd8b7e9b/$metadata#directoryObjects/@Element",
  "odata.type": "Microsoft.DirectoryServices.Application",
  "optionalClaims": null,
  "orgRestrictions": [],
  "parentalControlSettings": {
    "countriesBlockedForMinors": [],
    "legalAgeGroupRule": "Allow"
  },
  "passwordCredentials": [
    {
      "additionalProperties": null,
      "customKeyIdentifier": null,
      "endDate": "2022-01-19T02:09:46.136407+00:00",
      "keyId": "ee2c284d-c841-4c84-9aea-837d5b4e0dd7",
      "startDate": "2021-01-20T02:09:46.136407+00:00",
      "value": null
    }
  ],
  "preAuthorizedApplications": null,
  "publicClient": true,
  "publisherDomain": "MicrosoftInternal.partner.onmschina.cn",
  "recordConsentConditions": null,
  "replyUrls": [],
  "requiredResourceAccess": [],
  "samlMetadataUrl": null,
  "signInAudience": "AzureADMyOrg",
  "tokenEncryptionKeyId": null,
  "wwwHomepage": null
}

**Comment by jarrekk** [comment]
Additional information: this happened on Mac/Linux platform, Windows `az` command doesn't have this problem.

**Comment by yonzhan** [comment]
az ad

**Comment by lihantao3** [comment]
Hi team, any update?

**Comment by chicago7** [comment]
Hi Team, we also encounter this issue. Could you let us know whether you consider solving the problem?

**Comment by jiasli** [comment]
We are currently running out of bandwidth maintaining `az ad` which uses the deprecated AD Graph. Could you follow https://github.com/Azure/azure-cli/issues/12946 and try calling MS Graph directly with `az rest`?

Thanks for understanding.

**Comment by lihantao3** [comment]
@ jiasli How can I create an app with specified password by using az rest？

**Comment by jiasli** [comment]
According to [passwordCredential resource type](https://docs.microsoft.com/en-us/graph/api/resources/passwordcredential?view=graph-rest-1.0), MS Graph doesn't support creating an app with specified password. You will need to call [application: addPassword](https://docs.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-1.0&tabs=http) to let MS Graph generate one for you.

**Comment by chicago7** [comment]
@jiasli  thanks for your reply. I tried to use the MS Graph to call API. but we encounter the below error messages. FYI.

az rest --method post --url "https://microsoftgraph.chinacloudapi.cn/v1.0/applications/63488455-a508-4a02-abe2-f4786a4f602c/addPassword" --body @C:\body.json
Not Found({
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource '63488455-a508-4a02-abe2-f4786a4f602c' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "date": "2021-03-15T08:06:09",
      "request-id": "65f1d330-43f7-4c20-a485-63914c6e6318",
      "client-request-id": "65f1d330-43f7-4c20-a485-63914c6e6318"
    }
  }
})

body.json as follows:
{
  "passwordCredential": {
    "displayName": "azresttest01"
  }
}


In the meanwhile, we want your team can fix the issue. A new key can be created when we create a new application by Azure CLI on Mac/Linux platform. thank you so much.

**Comment by jiasli** [comment]
> I tried to use the MS Graph to call API. but we encounter the below error messages.

Is `63488455-a508-4a02-abe2-f4786a4f602c` in the URL object ID?

```
https://microsoftgraph.chinacloudapi.cn/v1.0/applications/63488455-a508-4a02-abe2-f4786a4f602c/addPassword
```

Please make sure to use object ID, instead of application ID.

> In the meanwhile, we want your team can fix the issue. A new key can be created when we create a new application by Azure CLI on Mac/Linux platform. thank you so much.

Sure. I will certainly look into this issue when time permits.

**Comment by chicago7** [comment]
hi jiasli  thanks for your quick response. I try to use object id instead of application id. it works.

{
  "@odata.context": "https://microsoftgraph.chinacloudapi.cn/v1.0/$metadata#microsoft.graph.passwordCredential",
  "customKeyIdentifier": null,
  "displayName": "azresttest01",
  "endDateTime": "2023-03-15T09:21:54.1438256Z",
  "hint": "c_E",
  "keyId": "a0ad2857-6a4e-44fa-b634-ba22610e48ce",
  "secretText": "c_E2_O7E94*********4t6W55Y~-D6_a",
  "startDateTime": "2021-03-15T09:21:54.1438256Z"
}

Meanwhile, We are anxious to resolve this issue on Mac/Linux platform ASAP. thanks for your support.

**Comment by jiasli** [comment]
We currently don't have enough bandwidth maintaining `az ad` module which still uses AD Graph, please see https://github.com/Azure/azure-cli/issues/12946 for calling MS Graph with `az rest`. Thanks for your understanding.
