### ISSUE TITLE
Output none still prints stuff

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cli#16606]
**Describe the bug**

I'm using az login -o none - but I still get output on the screen.

```
memealyzer2$ az login -o none
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code to authenticate.
The following tenants don't contain accessible subscriptions. Use 'az login --allow-no-subscriptions' to have tenant level access.
The following tenants require Multi-Factor Authentication (MFA). Use 'az login --tenant TENANT_ID' to explicitly login to a tenant.
```

**To Reproduce**

az login -o none

**Expected behavior**

No output

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
az login

**Comment by jiasli** [comment]
`-o/--output none` only controls the content of `stdout`.

To fully disable warnings in `stderr`, you may use

- `core.only_show_errors` config option via `az config set core.only_show_errors=true`
- `AZURE_CORE_ONLY_SHOW_ERRORS=1` environment variable
-  `--only-show-errors` argument

More information can be found at [CLI configuration values and environment variables](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-values-and-environment-variables).
