### ISSUE TITLE
az next continuous error...

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#16601]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
![image](https://user-images.githubusercontent.com/30876406/105226337-b8a18a00-5b14-11eb-9bfc-bcead1cbc45f.png)

Have actually encountered similar errors like this numerous times in the last weeks but never created a bug to track it until now

**To Reproduce**
1) tried az next after upgrading to v2.18.0 but didn't work
2) tried uninstalling and reinstalling the feature ...also didn't work...

**Expected behavior**
 I expect anyone using the feature not to encounter error every time they use the feature after version upgrade or for any other reason
 
**Environment summary**
![image](https://user-images.githubusercontent.com/30876406/105226561-fd2d2580-5b14-11eb-9c80-c35da5a66902.png)

**Additional context**

**Comment by yonzhan** [comment]
az next

**Comment by zhoxing-ms** [comment]
Hi @chenlomis this is an installation issue of `az next`, can you submit it to the corresponding repo of `az next`? [repo link](https://github.com/hackathon-cli-recommendation/cli-recommendation/issues)

**Comment by zhoxing-ms** [comment]
I've created a new issue to replace this issue. You can follow it up through [new issue](https://github.com/hackathon-cli-recommendation/cli-recommendation/issues/5)
So I close this issue first

**Comment by chenlomis** [comment]
Thank you! Please let me know if there'd a quick fix avail some time tomorrow. There's a PM sync where I'd like to provide a brief live walkthrough to explain how it works! @zhoxing-ms

**Comment by zhoxing-ms** [comment]
@chenlomis If you previously installed it in the way of `MSI`, please just rerun the installation script.
Because `MSI` package can't cover higher version with lower version, I just updated the installation package of `MS`I for `az next`

By the way, if you have anything else I can help you with when you are preparing for the demo, please feel free to let me know 😊

**Comment by chenlomis** [comment]
@zhoxing-ms  Thank you! That's very kind of you
I was able to get it working for a small scenario... we did receive additional feedback on the walkthrough where the leads were asking us to tweak part of the walkthrough before we share it out in the MVP meet up next week though... would love your help on the feasibility... let me follow up with you over email!
