### ISSUE TITLE
 az cosmosdb cassandra table create command is in preview

### ISSUE THREAD

**Issue by RajTechcafe** [Azure/azure-cli#16614]
This command group az cosmosdb cassandra is under preview. When we can expect GA version of this? May be it will helpuful if it is mentioned in doc what is current version of command group either Preview or GA. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f15e72-f5d8-b270-66a6-ad75a6766ff8
* Version Independent ID: d4736bea-3a9c-b9f4-defe-e9dfc3696167
* Content: [az cosmosdb cassandra](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/cassandra?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/cosmosdb/cassandra.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cosmosdb/cassandra.yml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by MehaKaushik** [comment]
Hey @RajTechcafe I believe your cli module is not updated. The latest module doesn't have this command in preview mode. I believe it has been out of preview for months. Please update your cli client. Please reopen this issue if you still have any further questions.
