### ISSUE TITLE
Incorrect PKCS7 format in az network application-gateway ssl-cert show example

### ISSUE THREAD

**Issue by dae3** [Azure/azure-cli#16610]
A PKCS7 format cert should be delimited with `-----BEGIN PKCS7-----` and `-----END PKCS7-----`, not `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67b074ef-2732-8002-ba0e-47534e238c0c
* Version Independent ID: 3b48511d-b007-f938-985f-cc6765d37d45
* Content: [az network application-gateway ssl-cert](https://docs.microsoft.com/en-au/cli/azure/network/application-gateway/ssl-cert?view=azure-cli-latest#az_network_application_gateway_ssl_cert_list)
* Content Source: [latest/docs-ref-autogen/network/application-gateway/ssl-cert.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/application-gateway/ssl-cert.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network
