### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#16611]
**Is your feature request related to a problem? Please describe.**

Currently Azure CLI can't be installed on [Python 3.9](https://www.python.org/downloads/release/python-391/), causing different errors on different platforms. 

For example, on Windows

```
Building wheels for collected packages: bcrypt, cryptography, PyNaCl
...
  Building wheel for cryptography (PEP 517) ... error
  building '_openssl' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
```

This is because older versions of **bcrypt**, **cryptography**, **PyNaCl** don't distribute wheels for Python 3.9. For example, [cryptography 2.9.2](https://pypi.org/project/cryptography/2.9.2/#files) only distributes `cryptography-2.9.2-cp38-cp38-win_amd64.whl`.

Users will have to either

- install **gcc** or **Microsoft Visual C++** to build these dependencies from source, or
- use an older version of Python (https://github.com/MicrosoftDocs/azure-docs-cli/issues/2407).

**Describe the solution you'd like**

The latest versions of [bcrypt](https://pypi.org/project/bcrypt/#files), [cryptography](https://pypi.org/project/cryptography/#files), [PyNaCl](https://pypi.org/project/PyNaCl/#files) all use [Stable Application Binary Interface](https://docs.python.org/3/c-api/stable.html) (`*-cp36-abi3-win_amd64.whl`) to build wheels so that they can be installed on Python 3.9 without building source code.

Azure CLI should support Python 3.9 by bumping these dependencies:

- [ ] [bcrypt 3.2](https://pypi.org/project/bcrypt/3.2.0/): #17369
- [ ] [cryptography 3.3.1](https://pypi.org/project/cryptography/3.3.1/): #15687
- [ ] [PyNaCl 1.4](https://pypi.org/project/PyNaCl/1.4.0/): #17369

**Comment by yonzhan** [comment]
Python 3.9 support

**Comment by ericsnowcurrently** [comment]
Also, the first beta release of Python 3.10 is coming at the beginning of May.

**Comment by Umamahesh888** [comment]
in azure cli pip --version is 3.9 but finction app version is 3.10 getting the http 500 error , and will check in the logs request module not found already we called latest version request module in requirements.txt, is it related to python version issue?
