### ISSUE TITLE
Error json CLI

### ISSUE THREAD

**Issue by guemuno** [Azure/azure-cli#16626]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

the azure cli in windows powershell is not working with json strings
**To Reproduce**

Create an self sign certificate in a key vault in windows 
az keyvault certificate create --vault-name KVName -n cert1 -p "$(az keyvault certificate get-default-policy)"
Expecting property name enclosed in double quotes: line 1 column 5 (char 4)

Run the same sentence in bash and works

**Expected behavior**

Create the certificate 
**Environment summary**

Cloud Shell
az --version
azure-cli                         2.18.0

core                              2.18.0
telemetry                          1.0.6

Extensions:
ai-examples                        0.2.5
azure-cli-ml                      1.20.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/omar/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.6/site-packages/azure-cli-extensions'

Python (Linux) 3.6.10 (default, Jan 15 2021, 09:54:35)
[GCC 8.3.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
**Additional context**

**Comment by yungezz** [comment]
hi @houk-ms could you pls have a look? thanks

**Comment by qwordy** [comment]
@guemuno I think it is a problem of `"` character. It has special meaning in terminal. It should be escaped so that it can be treated as a normal character.
https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#quoting-issues

**Comment by yungezz** [comment]
hi @guemuno  could you pls try the above solution from @qwordy : escape the `"`? thanks.

**Comment by yungezz** [comment]
close for now. Feel free to open new issue if any other error met.
