### ISSUE TITLE
'postgres server ad-admin create' fails if --object-id is surrounded with quotes (")

### ISSUE THREAD

**Issue by mikkelhegn** [Azure/azure-cli#16620]
## Describe the bug
'postgres server ad-admin create' fails if --object-id is surrounded with quotes ("). This makes scripting with the command more difficult to have to keep track of "cleaning" outputs form other commands for quotes.
E.g.
```
USER=me@mytenant.com

ADMIN_USER_ID=$(az ad user show --id $USER | jq .objectId)

# This is to remove quotes (") from the above output
ADMIN_USER_ID=$(sed -e 's/^"//;s/"$//' <<<"$ADMIN_USER_ID")

az postgres server ad-admin create --server-name $SERVER \
    --resource-group $RG --object-id $ADMIN_USER_ID --display-name $USER
```

**Command Name**
`az postgres server ad-admin create`

**Errors:**
```
BadRequestError: The 'parameters.properties.sid' segment in the url is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres server ad-admin create --server-name {} --resource-group {} --object-id {} --display-name {}`

## Environment Summary
```
Linux-4.19.121-linuxkit-x86_64-with-debian-10.7
Python 3.6.10
Installer: DEB

azure-cli 2.17.1 *

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by MikkelHegn** [comment]
FYI - jq takes a flag to provide the raw output `jq -r`. That makes it easier in the example above, but I still think it should be possible to parse the object id with quotes.

**Comment by SeaDude** [comment]
I'm getting the same error from `az sql server ad-admin create`. Its actually addressed in the official docs [here](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli#get-a-single-value). Use the flag `--output tsv` to return a value with no double quotes. 

Testing now

**Comment by guestdj** [comment]
I'm also getting the same error when running:
`az sql server ad-admin create --resource-group --server --subscription --object-id --output tsv --debug`

`cli.azure.cli.core.azclierror: (InvalidResourceIdSegment) The 'parameters.properties' segment in the url is invalid.`

What is the point of having an api if it does not work - or MS please give us an example on your docs:
[](https://docs.microsoft.com/en-us/cli/azure/sql/server/ad-admin?view=azure-cli-latest#az_sql_server_ad_admin_create)

**Comment by RakeshMohanMSFT** [comment]
@mikkelhegn This issue is fixed. Please update to Az CLI latest version [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)

**Comment by dan-dekel** [comment]
+1
