### ISSUE TITLE
az storage account list - Parameter 'resource_group_name' must have length less than 90.

### ISSUE THREAD

**Issue by dmraymond** [Azure/azure-cli#16625]
## Describe the bug
When you run the command with the subscription parameter and  without the resource-group parameter it results in an error. The same error occurs if you run the command without any parameters.

**Command Name**
`az storage account list`

**Errors:**
```
ValidationError: Parameter 'resource_group_name' must have length less than 90.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account list --subscription {}`

## Expected Behavior
List all storage accounts in a subscription.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1 *

Extensions:
interactive 0.4.4

```

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @dmraymond, have you ever configure `group` with `az configure` or local context?

Could you also add `--debug` in your command and share debug info?

**Comment by dmraymond** [comment]
Just prior to running the command I do run "az account set --subscription {}" but I do not set the resource group or set any persistent parameters. I ran the command again today and it is not throwing an error. I am attaching the debug log just in case.

[debug.log](https://github.com/Azure/azure-cli/files/5946978/debug.log)

**Comment by Juliehzl** [comment]
Thanks for your feedback. There is no special issue in your log. But if you still get the issue, you could create a new issue with debug log.
