### ISSUE TITLE
Add support for Logic Apps

### ISSUE THREAD

**Issue by cmatskas** [Azure/azure-cli#1662]
Hi team, could you please add support for Azure LogicApps? Is it in the roadmap? if not, what do we need to do to move this forward?

**Comment by tjprescott** [comment]
@yugangw-msft you've had the most interaction with the appservice team. Do you know where this fits in?

**Comment by yugangw-msft** [comment]
Logic App will be considered at post February. It is not webapp, though both are app types supported  by azure appservice

**Comment by yugangw-msft** [comment]
@cmatskas, for now, unless logic team makes contribution, the only option is to use `azure-powershell`

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.

**Comment by dgard1981** [comment]
2.5 year on there is still no CLI support for Logic Apps. Is this ever coming, or does the lack of support mean that we can assume Logic Apps were a fad and are going to die?

**Comment by tjprescott** [comment]
@dgard1981 I believe that a team is working on a separate CLI for Logic App connectors. @mamurshe can you comment?

**Comment by mamurshe** [comment]
@dgard1981 We have a standalone CLI for flow and powerapps at this moment. However, the CLI doesn't support LogicApps yet. @schabungbam may have more information.

The repo is located here: https://github.com/Microsoft/PowerPlatformConnectors

**Comment by dgard1981** [comment]
@mamurshe, @tjprescott, thanks for the replies - the sooner the better, as Logic Apps are not the easiest to work with at present!

**Comment by yugangw-msft** [comment]
@dgard1981, before the gap gets filled, you can either use generic [resource commands](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#generic-resource-commands)  or `az rest` by referencing [rest api](https://docs.microsoft.com/en-us/rest/api/logic/)

**Comment by dgard1981** [comment]
@yugangw-msft, thanks for your reply. I have taken a look at `invoke-action`, but the documentation is context-less, and I was unable to figure out how to do things like update the Logic App definition, or add/update parameters.
