### ISSUE TITLE
create vm from image windows10 is not as same as portal 

### ISSUE THREAD

**Issue by phoenixkill** [Azure/azure-cli#16633]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
when create vm from image windows 10  license-type is a request parameter ,but when use az cli to create vm from image windows 10  ,license type is not a request parameter 

**To Reproduce**

**Expected behavior**
az cli create vm is as same as portal 

**Environment summary**
msi az cli latest version 

**Additional context**

**Comment by yungezz** [comment]
hi @qwordy could yo upls have a look? thanks

**Comment by qwordy** [comment]
Azure CLI is a command line tool while Azure Portal is a website. They don't guarantee identical usage.
