### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by Tribeni-Gupta** [Azure/azure-cli#16639]
**Resource Provider**
 IOT hub

**Description of Feature or Work Requested**

This is great. I have started using it for managing azure resources . I on this below version. 
PS C:\windows\system32> az --version
azure-cli                         2.18.0
core                              2.18.0
telemetry                          1.0.6
Extensions:
interactive                        0.4.4

I am running one command and it seems it is not working. am i missing anything here. 
az iot hub device-identity list --ee --hub-name d365csintwestus2-iothub

No response and its hanging . i had to kill the poweshell session. 

please assist. 

**Minimum API Version Required**

**Swagger Link**

**Target Date**

**Comment by yonzhan** [comment]
iot

**Comment by vilit1** [comment]
Closing the issue due to no response. If you still need help with this issue, please re-open.
