### ISSUE TITLE
az iot hub device-identity list

### ISSUE THREAD

**Issue by Tribeni-Gupta** [Azure/azure-cli#16637]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
iot

**Comment by vilit1** [comment]
Closing the issue due to no response. If you still need help with this issue, please re-open.
