### ISSUE TITLE
`az sig image-version update` is still updating after one day

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-cli#16632]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

```
{
  "azure-cli": "2.7.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.7.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}
```

**Describe the bug**

`az sig image-version update` is still updating after one day. We are been blocking so we need your help ASAP.

**To Reproduce**

```
RG_NAME="AKS-Windows"
GALLERY_NAME="AKSWindows"
IMAGEDEFINITION_NAME="windows-2019"
IMAGE_VERSION="17763.1697.210113"
TARGET_REGIONS="westus2=50 westeurope=50 eastus=50 northeurope=50 westus=50 eastus2=50 centralus=40 uksouth=40 southeastasia=40 australiaeast=40 japaneast=40 northcentralus=50 canadacentral=30 eastasia=30 southcentralus=30 francecentral=30 brazilsouth=20 australiasoutheast=20 canadaeast=20 koreacentral=20 ukwest=20 centralindia=20 southafricanorth=20 japanwest=20 southindia=20 koreasouth=20 westcentralus=20 germanywestcentral=20 switzerlandnorth=20 norwayeast=20 uaenorth=10 eastus2euap=20 centraluseuap=20 westindia=20"

TARGET_CREATE_REGIONS="westus2 westeurope eastus northeurope westus eastus2 centralus uksouth southeastasia australiaeast japaneast northcentralus canadacentral eastasia southcentralus francecentral brazilsouth australiasoutheast canadaeast koreacentral ukwest centralindia southafricanorth japanwest southindia koreasouth westcentralus germanywestcentral switzerlandnorth norwayeast uaenorth eastus2euap centraluseuap westindia"

 az sig image-version create \
   --resource-group ${RG_NAME} \
   --gallery-name ${GALLERY_NAME} \
   --gallery-image-definition ${IMAGEDEFINITION_NAME} \
   --gallery-image-version ${IMAGE_VERSION} \
   --managed-image "${MANAGED_IMAGE_URI}" \
   --target-regions ${TARGET_CREATE_REGIONS} \
   --storage-account-type Premium_LRS \
   --replica-count 5

az sig image-version update \
   --resource-group ${RG_NAME} \
   --gallery-name ${GALLERY_NAME} \
   --gallery-image-definition ${IMAGEDEFINITION_NAME} \
   --gallery-image-version ${IMAGE_VERSION} \
   --target-regions ${TARGET_REGIONS} \
   --no-wait
```

**Expected behavior**

`az sig image-version update` succeeds.

**Environment summary**

Linux-5.3.0-1035-azure-x86_64-with-debian-buster-sidPython 3.6.10Installer: DEBazure-cli 2.7.0

**Additional context**

**Comment by yungezz** [comment]
hi @qwordy could you pls take a look

**Comment by qwordy** [comment]
@AbelHu Could you add `--debug` and paste output here?

**Comment by AbelHu** [comment]
@qwordy After removing `eastus2euap` from the target regions, it succeeded. But later when I added `eastus2euap` back, it is still stuck in `updating`

**Comment by AbelHu** [comment]
@qwordy it seems like to be an issue of the region `eastus2euap`. Now it is finished. Is there any idea to increase the replica count for a specified region instead of updating all regions?
I set the replica count to 10 (Max count in Azure portal) for the region `eastus2euap`. But we want to increase it to 20. How can we use az command to do it? We have 40 regions so we do not want to do a full update.

**Comment by qwordy** [comment]
@AbelHu, glad to know that.
Use this parameter `--target-regions`
https://docs.microsoft.com/en-us/cli/azure/sig/image-version?view=azure-cli-latest#az_sig_image_version_create
