### ISSUE TITLE
`az functionapp create` doesn't support https-only true

### ISSUE THREAD

**Issue by ElvenSpellmaker** [Azure/azure-cli#16636]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is that I'm trying to use `az functionapp create` to create a new function instead of using ARM as ARM removes all appsettings on update.

The problem I have is that subscription policy for this client denies creating a function without https-only true but I can't set this at function creation time using `az`...

**Describe the solution you'd like**
I'd like to be able to specify more settings on function creation, such as https-only true, or have the functionapp automatically enable https-only true as this is 2021 after all...

**Describe alternatives you've considered**
Crying 😢 

ARM/TF don't work properly.
Can't use `az` and write PowerShell scripts either.

**Additional context**
https://github.com/Azure/azure-cli/issues/11718

If issues like the above were fixed it'd be a lot easier to use ARM/TF for this.

Function apps should _not_ be using `appsettings` for _infrastructure_ values such as Storage Account and Function Version... These aren't app settings but intrinsic to the function, much like the OS type of a resource or Size of a VM is.

**Comment by yonzhan** [comment]
functionapp

**Comment by apawast** [comment]
@gzuber can you please take a look at this?

**Comment by ElvenSpellmaker** [comment]
I've had to wrok around this by creating my own JSON and using `az resource create`:
```pwsh
az functionapp create `
	--name $FunctionName `
	--resource-group $ResourceGroup `
	--storage-account $StorageAccount `
	--assign-identity '[system]' `
	--functions-version $FunctionVersion `
	--os-type Linux `
	--plan $ServicePlan `
	--runtime dotnet `
	--tags @tagsArray
```
has become:
```pwsh
		# `az functionapp create` doesn't support https only currently...
		# Therefore I need to mimic what `az functionapp create` does
		# and call `az resource create` myself...
		$appServicePlan = (
			az appservice plan show `
				--name $ServicePlan `
				--resource-group $ResourceGroup `
			| ConvertFrom-Json
		)

		$servicePlanResourceLocation = $appServicePlan.location

		$jsonDocument = @{
			name = $FunctionName
			tags = $Tags
			location = $servicePlanResourceLocation
			kind = 'functionapp,linux'
			properties = @{
				serverFarmId = $ServicePlan
				reserved = $true
				clientAffinityEnabled = $false
				siteConfig = @{
					alwaysOn = $true
					appSettings = @(
						@{
							name = $ENV_FUNCTION_VERSION_KEY
							value = "~$FunctionVersion"
						},
						@{
							name = 'FUNCTIONS_WORKER_RUNTIME'
							value = 'dotnet'
						},
						@{
							name = $ENV_STORAGE_ACCOUNT_KEY
							value = $StorageAccountConnectionString
						}
					)
				}
				httpsOnly = $true
				http20Enabled = $true
			}
			identity = @{
				type = 'SystemAssigned'
			}
		} | ConvertTo-Json -Compress -Depth 100

		az resource create `
			--api-version 2020-06-01 `
			--name $FunctionName `
			--resource-group $ResourceGroup `
			--resource-type Microsoft.Web/Sites `
			--is-full-object `
			--properties ("$jsonDocument" -replace'(\\*)"','$1$1\"')
```

**Comment by BAAdeosun** [comment]
@ElvenSpellmaker 
Hi ElvenSpellmaker, i tired to use your fix but i keep getting "NotSpecified: (UnrecognizedArg...ments: Europe"}:String) []," whenever the script get to "az resource create"
Could the "--properties ("$jsonDocument" -replace'(\\*)"','$1$1\"')" be missing something ?

**Comment by ElvenSpellmaker** [comment]
Hey, it's working fine for me, I've just checked master and re-copied and pasted it in above, please double check.

**Comment by ElvenSpellmaker** [comment]
You'll also need these:
```pwsh
Set-Variable `
	ENV_FUNCTION_VERSION_KEY `
	-Option Constant `
	-Scope Script `
	-Value FUNCTIONS_EXTENSION_VERSION

Set-Variable `
	ENV_STORAGE_ACCOUNT_KEY `
	-Option Constant `
	-Scope Script `
	-Value AzureWebJobsStorage
```

**Comment by BAAdeosun** [comment]
@ElvenSpellmaker 
below is exact code, after changing the variables to be pre-set variables:

$appServicePlan = (
			az appservice plan show `
				--name $planName `
				--resource-group $rgName `
			| ConvertFrom-Json
		)

		$servicePlanResourceLocation = $appServicePlan.location

		$jsonDocument = @{
			name = $functionAppName
			tags = $Tags
			location = $servicePlanResourceLocation
			kind = 'functionapp,linux'
			properties = @{
				serverFarmId = $planName
				reserved = $true
				clientAffinityEnabled = $false
				siteConfig = @{
					alwaysOn = $true
					appSettings = @(
						@{
							name = $ENV_FUNCTION_VERSION_KEY
							value = "$FunctionVersion"
						},
						@{
							name = 'FUNCTIONS_WORKER_RUNTIME'
							value = 'dotnet'
						},
						@{
							name = $ENV_STORAGE_ACCOUNT_KEY
							value = $StorageAccountConnectionString
						}
					)
				}
				httpsOnly = $true
				http20Enabled = $true
			}
			identity = @{
				type = 'SystemAssigned'
			}
		} | ConvertTo-Json -Compress -Depth 100

		az resource create `
			--api-version 2020-06-01 `
			--name $functionAppName `
			--resource-group $RgName `
			--resource-type Microsoft.Web/Sites `
			--is-full-object `
            --properties ("$jsonDocument" -replace'(\\*)"','$1$1\"')

Error line was from:
az resource create `

**Comment by ElvenSpellmaker** [comment]
```
					@{
						name = $ENV_FUNCTION_VERSION_KEY
						value = "$FunctionVersion"
					},
					@{
						name = 'FUNCTIONS_WORKER_RUNTIME'
						value = 'dotnet'
					},
					@{
						name = $ENV_STORAGE_ACCOUNT_KEY
						value = $StorageAccountConnectionString
					}
```
Did you set the variables I showed above?

**Comment by BAAdeosun** [comment]
No i didn't, not sure where to retrieve the exact values, as this is a new function app creation

**Comment by ElvenSpellmaker** [comment]
Right, this script assumes you have an App Service Plan, as that can be done in ARM/Terraform without much difficulty. 🙂 

Are you planning on running the function in an App Service Plan or Consumption?

**Comment by BAAdeosun** [comment]
It is from App Service Plan.
App Service Plan will be created by Az Cli, "az functionapp plan create"

**Comment by ElvenSpellmaker** [comment]
OK the plan has to be created first such that the plan can be retrieved by my script. 🙂

**Comment by BAAdeosun** [comment]
Yeah, plan was created and function app created in the plan 
The steps to create includes:
az group create - creates resource group
az storage account create - create storage account
az functionapp plan create  - create webapp plan
 


 

My initial script was to add the httpOnly after creation, that is wait 2 minutes before the below, but still didnt work, until i ran the below separately.  

if ($functionAppNameExists)
{   az functionapp update `
        --name $functionAppName `
        --resource-group $rgName `
        --set httpsOnly=true `
}

**Comment by ElvenSpellmaker** [comment]
If the plan exists and you have the right variables set it should work, hrm.

**Comment by kamperiadis** [comment]
Hi @ElvenSpellmaker We apologize for not getting back to you sooner. `https-only` is now a supported param for the `az functionapp create` command. As such, I will mark this as resolved. Thank you!

**Comment by ElvenSpellmaker** [comment]
@kamperiadis Better late than never thanks! 🙂
