### ISSUE TITLE
az login fails to connect to Azure china 

### ISSUE THREAD

**Issue by ajay15283** [Azure/azure-cli#16638]
## Describe the bug
az login command using service principal fails to login Azure china subscription .There is no specific option to mention the environment as well

**Command Name**
`az login`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'XXXXXXXX-XXXX-XXXX' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: 8ae8e1bc-777d-43f9-bc14-d032ad7f5900\r\nCorrelation ID: 2239d0dd-552c-4a0f-b101-2f4f9c7db3e3\r\nTimestamp: 2021-01-22 18:48:30Z","error_codes":[90002],"timestamp":"2021-01-22 18:48:30Z","trace_id":"8ae8e1bc-777d-43f9-bc14-d032ad7f5900","correlation_id":"2239d0dd-552c-4a0f-b101-2f4f9c7db3e3","error_uri":"https://login.microsoftonline.com/error?code=90002"}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal --username {} --tenant {}`

## Environment Summary
```
Linux-4.12.14-16.38-azure-x86_64-with-SuSE-12-x86_64
Python 3.4.10
Installer: RPM

azure-cli 2.9.1

```

**Comment by yonzhan** [comment]
az login

**Comment by ajay15283** [comment]
I switch to Azure china cloud and the az login returns a different due to firewall block so closing the thread
