### ISSUE TITLE
Error message is not helpful when a validation fails on `az vm create`

### ISSUE THREAD

**Issue by asilverman** [Azure/azure-cli#16640]
## Describe the bug

I am following the  [kubernetes-the-hard-way-on-azure](https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure/blob/master/docs/03-compute-resources.md#kubernetes-controllers) tutorial, in the section to create the VMs my command to create a VM had a problem, I was specifying the wrong value for the `--image` option.

This is a legitimate mistake, however the result of the resulting error from the invocation of `az vm create`  command was not very helpful, the resulting message was: `ERROR: ValidationError: Operation returned an invalid status 'Bad Request'`

Indeed my invocation was a bad request but given that I am specifying multiple options, this is not really a helpful error message, instead I would have wanted to see something to the effects of: `ERROR: ValidationError: the value specified for the option --image is invalid`

**Command Name**
`az vm create`

**Errors:**
```
ValidationError: Operation returned an invalid status 'Bad Request'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
- Follow the [instructions to setup VMs of the tutorial](https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure/blob/master/docs/03-compute-resources.md#virtual-machines)
- Set `UBUNTULTS` to any invalid string (i.e. something that is not a valid value for --image)
- Run : ` az vm create -g kubernetes \               
        -n controller-${i} \
        --image ${UBUNTULTS} \
        --nics controller-${i}-nic \
        --availability-set controller-as \
        --nsg '' \
        --admin-username 'kuberoot' \
        --generate-ssh-keys > /dev/null`

## Expected Behavior
 I expect the error message to help me understand what about the command is invalid so I can fix it instead of sending me on a wild goose chase for the problem.
## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: 

azure-cli 2.18.0

```

**Comment by yungezz** [comment]
hi @qwordy @houk-ms could you pls help to have a look? thanks

**Comment by qwordy** [comment]
@asilverman Could you add `--debug` and paste logs here?

**Comment by qwordy** [comment]
@asilverman

**Comment by qwordy** [comment]
Close since no reply.
