### ISSUE TITLE
Webapp: az webapp config ssl bind giving "certificate not found" 

### ISSUE THREAD

**Issue by calvinsID** [Azure/azure-cli#16642]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
`az webapp config ssl bind` giving "certificate not found error"

**To Reproduce**
- `az webapp config ssl import` command to import SSL cert to webapp that has an appservice plan in diff resource group
- `az webapp config ssl bind` - this command will fail with "certificate not found" error if webapp and appservice plan in diff resource groups

**Expected behavior**
- it should find certificate and bind

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
webapp
