### ISSUE TITLE
az login need to re-login multiple times a day

### ISSUE THREAD

**Issue by velvia** [Azure/azure-cli#16641]
## Describe the bug

**Command Name**
`az login`

I have heard from many that `az login` is supposed to keep you logged in for many days or weeks.  However, myself and another colleague, we have to login at the start of each day we are doing things using az CLI or scripts that use it, and sometimes multiple times a day.   Do you know why that is?

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

Repeat other az commands and see that az login is required at beginning of every day, at minimum.

## Expected Behavior

`az login` has keep alive token and keeps you logged in for a long time, at least a week

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.6
Installer: HOMEBREW

azure-cli 2.14.0 *

```

**Comment by yonzhan** [comment]
az login

**Comment by velvia** [comment]
@yonzhan sorry?  Yes I know how to use `az login` the problem is that I get logged out too often.  Any hints?

**Comment by jiasli** [comment]
Hi @velvia, apologize for the confusion. @yonzhan is only triaging this issue indicating we have received your request.

Could you share the error you got if you don't re-login? Is it something similar to https://github.com/Azure/azure-cli/issues/16209?

Thanks for the information.

**Comment by matthai** [comment]
I have the same problem.

It's different from #16209 in that it occurs during az login, not during az aks get-credentials.

It's similar in the sense that it seems to happen due to a token timeout. I get the following error message:
AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-01-22T00:44:26.3870000Z and the maximum allowed lifetime for this request is 43200.
Trace ID: 6a8b15e9-6f31-4152-9ba9-734539395000
Correlation ID: 64ac554e-63ae-49a0-b580-a23c77b35ac6
Timestamp: 2021-01-26 07:47:14Z

I've been using az login for a while now, and this problem started in the last two weeks or so.

**Comment by jiasli** [comment]
@matthai, did the error occur in the browser or in the terminal? Could you share a screenshot? Thanks.

**Comment by velvia** [comment]
@jiasli there is no error from `az login` for me.  It is when using other az commands, such as aks, etc that the error occurs, and then I would need to login again.  (or for example using kubectl, which interacts with AKS)
The problem for me is not az login error, it is that I am asked to login too frequently.

```
E0125 20:14:59.503595   36876 azure.go:154] Failed to acquire a token: failed acquiring new token: waiting for device code authentication to complete: autorest/adal/devicetoken: Error occurred while sending request with device code for a token: Post "https://login.microsoftonline.com/8ec745c3-f5c9-433a-9ca4-8702b7059c2c/oauth2/token": net/http: TLS handshake timeout
```

**Comment by matthai** [comment]
> @matthai, did the error occur in the browser or in the terminal? Could you share a screenshot? Thanks.

Sorry, my bad, the error is not from az login. It is triggered by other az commands due to not being logged in, similar to @velvia.

I guess it's possible that possible that our systems administrators have changed login policies to require very frequent (every 12 hrs) re-login?

**Comment by velvia** [comment]
Where in Azure would login policies be set?

Thanks,
Evan

**Comment by jiasli** [comment]
@velvia, `TLS handshake timeout` is another issue. Please check your network connection and make sure `az account get-access-token` works as expected.

As for the original issue, it is very likely that your tenant administrator has enabled Conditional Access policy that makes the refresh token only valid for certain period of time (say 12h). You may refer to [Configurable token lifetimes in the Microsoft identity platform (preview)](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes) or contact your tenant administrator. 

Meanwhile, I will also do some investigation and testing on my tenant.

**Comment by jiasli** [comment]
@matthai, to better help us identity the original error, could you share a screenshot of these lines? Thanks a lot.

```
AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. 
The token was issued on 2021-01-22T00:44:26.3870000Z and the maximum allowed lifetime for this request is 43200.
Trace ID: 6a8b15e9-6f31-4152-9ba9-734539395000
Correlation ID: 64ac554e-63ae-49a0-b580-a23c77b35ac6
Timestamp: 2021-01-26 07:47:14Z
```

**Comment by velvia** [comment]
@jiasli the error I get back from `az account get-access-token` is as follows:

```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-01-25T17:51:10.1022630Z and was inactive for 12:00:00.\r\nTrace ID: df22e591-3c03-4ed9-857f-a97e7eb90100\r\nCorrelation ID: d29923fb-f57f-4ca9-98ec-20a390254421\r\nTimestamp: 2021-01-26 17:38:18Z","error_codes":[700082],"timestamp":"2021-01-26 17:38:18Z","trace_id":"df22e591-3c03-4ed9-857f-a97e7eb90100","correlation_id":"d29923fb-f57f-4ca9-98ec-20a390254421","error_uri":"https://login.microsoftonline.com/error?code=700082"}
```

It looks like indeed there is a 12-hour policy of some kind.

**Comment by velvia** [comment]
By the way, I followed the instructions in the Configurable Lifetimes article above, installed PowerShell and the AzureAD module, but it doesn't work:

```
PS /Users/evan/data> Connect-AzureAD -Confirm
Connect-AzureAD: The term 'Connect-AzureAD' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by jiasli** [comment]
@velvia, it looks like you don't have `AzureAD` module installed. Could you check [Install Azure Active Directory PowerShell for Graph](https://docs.microsoft.com/en-us/powershell/azure/active-directory/install-adv2?view=azureadps-2.0) to install `AzureAD` module accordingly? 

BTW, I think `New-AzureADPolicy` from [Configure token lifetime policies (preview)](https://docs.microsoft.com/en-us/azure/active-directory/develop/configure-token-lifetimes) can only by executed by the tenant/directory admin.

I will also take some time to investigate it with my test tenant as well .

**Comment by velvia** [comment]
@jiasli I installed AzureAD in addition to AzureADPreview, but no difference, it still can't find the command.  :(

**Comment by jiasli** [comment]
@velvia, could you reach AAD customer support for the usage of AAD-related Cmdlet?

To create a ticket: https://azure.microsoft.com/en-us/support/create-ticket/
 
Thanks for understanding.

**Comment by jiasli** [comment]
@velvia, could you try configuring Sign-in frequency control in Azure Portal and see if that works for you?

See: https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime#policy-1-sign-in-frequency-control

**Comment by velvia** [comment]
@jiasli can you tell me which tool in Azure that is?  I can't tell from the section you pointed me to.... it looks like something called "Contuoso"?  I've never seen that....

**Comment by jiasli** [comment]
Ah, it should be under **Azure Active Directory**:

![image](https://user-images.githubusercontent.com/4003950/109616243-e5af7680-7b6f-11eb-8c5d-4f5209690ab8.png)

**Comment by jiasli** [comment]
Provided a more detailed explanation at https://github.com/Azure/azure-cli/issues/16209#issuecomment-787593844.
