### ISSUE TITLE
Upload Page Blob from piped data or standard in (stdin, /dev/stdin) while skipping empty ranges

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#16652]
**Is your feature request related to a problem? Please describe.**

In an ideal world, users would be able to:
* provision large disk images
* compress them using `zstd`
* decompress them on-the-fly and pipe them into a tool to upload them
* that tool would read from standard in, **and** would skip empty blob ranges

It seems Microsoft has attempted to remedy this multiple times but has abandoned each:

* [`microsoft/azure-vhd-utils-for-go`](https://github.com/microsoft/azure-vhd-utils) had this functionality, but the code is rather complex and it's been abandonded
* [`Azure/blobxfer`](https://github.com/Azure/blobxfer) had this functionality, but the python deps have rotted and it's been abandonded

Moreover, this issue  (https://github.com/Azure/azure-cli/issues/3447#event-4159019969) **was opened four years ago**, and was recently was closed, but:
* I can't tell if that's coming to the CLI proper, or if I have to go out of my way to ensure that the CLI extensions are built appropriately by my distro packaging
* I can't tell if that uses the Storage SDK in a way that skips empty byte ranges in the page blob

**Describe the solution you'd like**

Microsoft to commit to supporting this basic scenario in their primary CLI tool, or, in a standalone, statically compiled, actively-maintained tool.

**It is important that the tool support both features**:
* reading from standard in
* skipping empty byte ranges when uploading

I remember `azure-vhd-utils-for-go` working well, as well. I had better experiences with it than I have had with the new `azcopy`...

**Describe alternatives you've considered**

* Forking and maintaining `azure-vhd-utils-for-go`
* Pinning `nixpkgs` to a specific revision (and thus the python ecosystem to a snapshot), patching `blobxfer`, and just using it since it works fairly well

**Comment by yonzhan** [comment]
storage

**Comment by colemickens** [comment]
A correction, despite the last commit moving the project ot Go modules, `azure-vhd-utils` doesn't even build, leaving a patched, pinnged `blobxfer` as the best remaining option I'm aware of.

```
[nix-shell:~/code/nixpkgs/cmpkgs]$ go get github.com/microsoft/azure-vhd-utils
# github.com/Microsoft/azure-vhd-utils/upload/metadata
../../../go/src/github.com/Microsoft/azure-vhd-utils/upload/metadata/metaData.go:95:32: blobClient.GetBlobMetadata undefined (type storage.BlobStorageClient has no field or method GetBlobMetadata)
# github.com/Microsoft/azure-vhd-utils/upload
../../../go/src/github.com/Microsoft/azure-vhd-utils/upload/upload.go:89:34: cxt.BlobServiceClient.PutPage undefined (type storage.BlobStorageClient has no field or method PutPage)
../../../go/src/github.com/Microsoft/azure-vhd-utils/upload/upload.go:93:7: undefined: storage.PageWriteTypeUpdate
```

**Comment by Juliehzl** [comment]
Hi @colemickens, for your feature request to reading from standard in, we have similar support in `storage-blob-preview` extension with Python SDK. You could have a try according to the example here https://github.com/Azure/azure-cli-extensions/blob/master/src/storage-blob-preview/azext_storage_blob_preview/_help.py#L170-L172.
For  `azure-vhd-utils-for-go` integration, we cannot achieve it because azure cli is in Python, and we cannot integrate go library.

**Comment by colemickens** [comment]
@Juliehzl thanks for the update, however here are my thoughts:

(regarding standard in) I've spent a gargantuan amount of time making this scenario work, and have it working with a pinned version of `azblobxfer` that should work for forever, basically. Additionally, nodejs packaging is hard in nixpkgs, and I'm not inclined to try to package preview cli extensions for such core, basic functionality. So, I'm unlikely to test this.

(regarding uploading to a SAS URL) The polling done in the no-storage-account scenario (aka, create the MD, acquire write-lease, upload-direct-to-MD-storage, break the write-lease) is so slow that, so far, it has seemed just as easy to suffer the pain of naming an Azure storage account, do a direct upload (again with blobxfer for the zstd piping functionality) and then create an MD from the storage link.

All of this is to say, I'm unlikely to try the storage preview, but I appreciate following up with me. Feel free to close this or whatever, I feel like I've left enough breadcrumbs for someone else to make blobxfer work and/or they can try the preview.

**Comment by Juliehzl** [comment]
Thanks for your feedback anyway!
