### ISSUE TITLE
Adding sync peering operation after the address space is updated after peerings are created

### ISSUE THREAD

**Issue by harics24** [Azure/azure-cli#16654]
**Is your feature request related to a problem? Please describe.**
This new feature enhancement enables user to update the address space after the peerings are created. Current behavior will throw an exception

**Describe the solution you'd like**
We had implemented the feature in two steps so that we don't have many failures in the backend. The second step is to update the address space on the remote peering. 

Please refer: https://microsoft-my.sharepoint.com/:w:/p/haperaba/EQTudFR2E21Cr-KL4qQcey8BpwFHfJlIe1seIF7BRYaAwA?e=t3bciq

**Describe alternatives you've considered**

**Additional context**
The REST call to do the same operation looks like this:
`curl --location --request PUT 'https://brazilus.management.azure.com/subscriptions/47ff8d6e-e419-464f-8940-dfa750f2115d/resourceGroups/HUB1-RG/providers/Microsoft.Network/virtualNetworks/spoke1/virtualNetworkPeerings/spoke1-hub1?api-version=2021-01-01&syncRemoteAddressSpace=true' \
--header 'Authorization: Bearer <TOKEN>' \
--header 'Content-Type: application/json' \
--data-raw '
{
  "location": "eastus2euap",
  "properties": {
    "remoteVirtualNetwork": {
      "id": "/subscriptions/47ff8d6e-e419-464f-8940-dfa750f2115d/resourceGroups/HUB1-RG/providers/Microsoft.Network/virtualNetworks/hub1"
    },
    "allowVirtualNetworkAccess": true,
    "allowForwardedTraffic": false,
    "allowGatewayTransit": false,
    "useRemoteGateways": false
  }
}'`

PS Commandlet(to be implemented):

`PS C:\> Sync-AzVirtualNetworkPeering
   -VirtualNetworkName <String>
   -ResourceGroupName <String>
   [-Name <String>]
   [-DefaultProfile <IAzureContextContainer>]
   [<CommonParameters>]`

Please note that we need to supply a **_query param_** (syncRemoteAddressSpace=true) in the request. Please help us to create a similar command in the azure cli.

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
Is it OK to release the new feature in the end of S184 (03/23/2021) ?

**Comment by msyyc** [comment]
What is the api-version of network needed? 2021-01-01?

**Comment by harics24** [comment]
> What is the api-version of network needed? 2021-01-01?

Correct. It's 2021-01-01

**Comment by harics24** [comment]
> network

Can we please target for 183? Would be too late for 184.

**Comment by msyyc** [comment]
2021-01-01 for network has not been merged into public repo(https://github.com/Azure/azure-rest-api-specs). After merge, it also takes some time to release python SDK. What's more ,2021/2/11~2021/2/18 is Chinese Spring Festival. So it is very hard to release in S183

**Comment by msyyc** [comment]
@harics24 when will '2021-01-01' be merged into 'master' of main repo?

**Comment by yonzhan** [comment]
@harics24 any update?

**Comment by msyyc** [comment]
@harics24 Hari Prasad Perabattula FTE when will '2021-01-01' be merged into 'master' of main repo?

**Comment by yonzhan** [comment]
@harics24 any feedback/update?

**Comment by kairu-ms** [comment]
Hi @harics24, I think the best implement is to support an new argument in `az network vnet peering update` command instead of add a new command `az network vnet peering sync`.
