### ISSUE TITLE
VMSS Flex support

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#16658]
**Resource Provider**

Compute, VMSS

**Description of Feature or Work Requested**

spec link:

- https://microsoft.sharepoint.com/:w:/t/vmssvmorchestrationmode/EemJzvPV2pdAgri8iFfTI_YB6V7CIIIWWpNXoPO__n1kFw?CID=A5C6140D-724B-43F9-830E-F49C5E297946&wdLOR=c5F5CB902-CA83-404A-A52C-95DEF3832AA5
- https://nam06.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Aw%3A%2Fr%2Fteams%2FComputeVM%2FShared%2520Documents%2FVM%2520Scale%2520Sets%2FVMSS%25202.0%2FVMSS%2520Flex%2520API.docx%3Fd%3Dw1b18260df7a54ac0aba000826af5229e%26csf%3D1%26web%3D1%26e%3DJneG4S&data=04%7C01%7Cyungez%40microsoft.com%7C8dcbf31d8e224d65ed3c08d8c0fb93f8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637471534056000184%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=12bXkMk7L3UzMyjOiBBlX17HqZbrBeULnciBCDdMVuc%3D&reserved=0
- https://nam06.safelinks.protection.outlook.com/ap/p-59584e83/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2F%3Ap%3A%2Ft%2Fvmssvmorchestrationmode%2FEXI6LDyIrmpOv1bIx4XathYBF978Yud-Ac3PM8UgJCJHTA%3Fe%3Drk1UUx&data=04%7C01%7Cyungez%40microsoft.com%7C8dcbf31d8e224d65ed3c08d8c0fb93f8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637471534056010172%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zO4RViY%2FvPJ7adIZBAyyIHdhe3YVPhb3UsTcvEj%2BMSs%3D&reserved=0

**Minimum API Version Required**

**Swagger Link**

API version: 2020-12-01. Not merged yet.

**Target Date**

•	APIs should be ready for integration testing in canary 2/15
•	Targeting Public preview 3/30
•	Targeting GA 5/30

**Comment by yungezz** [comment]
Current status: Swagger not merged yet, pending on it.

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/16747

**Comment by qwordy** [comment]
According to Jerry's latest email, Azure CLI has supported all available features now. Next is Public Preview 5/3.
