### ISSUE TITLE
Some parameters do not respect * if the running folder has got directories/files

### ISSUE THREAD

**Issue by antonlcy32** [Azure/azure-cli#16660]
When running Azure Storage CLI for CORS in a folder with sub-directories / files, it does not respect "--origins * --allowed-headers * --exposed-headers *" parameters. The CORS rule applied to the storage account will have "Allowed origins = <list of concatenated folder / file names>". 

Steps to reproduce: 

1. Run "cd" to a directory with some files / directories in there
![Screenshot 2021-01-25 at 7 17 29 PM](https://user-images.githubusercontent.com/15645184/105699254-0584c680-5f42-11eb-81c8-712a6b3b27b0.png)

2. Run "az storage cors add --methods GET --origins * --services b --account-name <name> --allowed-headers * --exposed-headers *"
3. Go to Azure console, the allowed origin, allowed headers, exposed headers will become list of concatenated folder/file names
![Screenshot 2021-01-25 at 7 15 18 PM](https://user-images.githubusercontent.com/15645184/105699270-09b0e400-5f42-11eb-99b0-78a65fb0dcc3.png)

Azure CLI version: 2.16.0
OS: MacOS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e3dfa7-e7ba-d8b9-9c8b-7a716016b7c0
* Version Independent ID: 249776f7-0d81-361b-822e-b87c2ca7fb23
* Content: [az storage cors](https://docs.microsoft.com/en-us/cli/azure/storage/cors?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/cors.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/cors.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @evelyn-ys , could you help take a look?

**Comment by evelyn-ys** [comment]
Hi @antonlcy32, this is because unix shell will fetch the values of what is associated with the "*" automatically. You can see the real arguments you passed in by adding `--debug` just like this:
```sh
$ az storage cors add --methods GET --origins * --services b --allowed-headers * --account-name yssa --debug
cli.knack.cli: Command arguments: ['storage', 'cors', 'add', '--methods', 'GET', '--origins', 'docs', 'one.jpg', 'three.jpg', 'two.jpg', '--services', 'b', '--allowed-headers', 'docs', 'one.jpg', 'three.jpg', 'two.jpg', '--account-name', 'yssa', '--debug']
......
```
As you can see in my example, `*` is parsed to all the files and directories and passed to CLI.

**To solve this, you can use `\*` instead of `*`.** See the results after:
```sh
$ az storage cors add --methods GET --origins \* --services b --allowed-headers \* --account-name yssa --debug
cli.knack.cli: Command arguments: ['storage', 'cors', 'add', '--methods', 'GET', '--origins', '*', '--services', 'b', '--allowed-headers', '*', '--account-name', 'yssa', '--debug']
......
```
