### ISSUE TITLE
`vm create` example has a bug

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#16669]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

`vm create` example has a bug.

Create a CentOS VM with a system assigned identity. The VM will have a 'Contributor' role with access to a storage account.
Azure CLI
```
az vm create -n MyVm -g rg1 --image centos --assign-identity --scope /subscriptions/99999999-1bf0-4dda-aec3-cb9272f09590/MyResourceGroup/myRG/providers/Microsoft.Storage/storageAccounts/storage1
```

It should be
```
az vm create -n MyVm -g rg1 --image centos --assign-identity [system] --scope /subscriptions/99999999-1bf0-4dda-aec3-cb9272f09590/MyResourceGroup/myRG/providers/Microsoft.Storage/storageAccounts/storage1
```

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yungezz** [comment]
PR ready
