### ISSUE TITLE
Error Updating BackendPool with AZ Cli [az network application-gateway address-pool update

### ISSUE THREAD

**Issue by m13biker** [Azure/azure-cli#16664]
## Describe the bug

**Command Name**
`az network application-gateway address-pool update`

**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
python3.6/site-packages/msrest/serialization.py, ln 1416, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
...
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network application-gateway address-pool update -g {} --gateway-name {} --name {} --add {} {}`

## Environment Summary
```
Linux-4.15.0-1103-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.18.0
azure-cli-ml 1.20.0

Extensions:
ai-examples 0.2.5
azure-cli-ml 1.20.0

```
## Additional Context

The Command executed is the following: 

az network application-gateway address-pool update -g RGName --gateway-name AAGName --name "appGatewayBackendPool-UI" --add backendAddresses "{ "ip_address": "10.39.93.11" }"

We were following the instructions on the AZ Cli Docs webpage [https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/address-pool?view=azure-cli-latest#code-try-10]

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Please use `--add backendAddresses ipAddress="10.39.93.11"`
