### ISSUE TITLE
FunctionApp Add Access Restrictions throws error if Service Tag is present 

### ISSUE THREAD

**Issue by kolendomichal** [Azure/azure-cli#16661]
## Describe the bug

Adding additional **Access Restrictions** (for example IPv4 restriction) to existing FunctionApp with **ServiceTag** restriction throws error.
Command works if a **ServiceTag** restriction is **not present** in **Access Restrictions**

**Command Name**
`az functionapp config access-restriction add`

**Errors:**
```
'ServiceTag' is not valid value for enum <enum 'IpFilterTag'>
Traceback (most recent call last):
python3.6/site-packages/msrest/serialization.py, ln 987, in serialize_enum
    enum_obj(result)
az/lib/python3.6/enum.py, ln 293, in __call__
    return cls.__new__(cls, value)
az/lib/python3.6/enum.py, ln 535, in __new__
    return cls._missing_(value)
az/lib/python3.6/enum.py, ln 548, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'ServiceTag' is not a valid IpFilterTag

...

python3.6/site-packages/msrest/serialization.py, ln 994, in serialize_enum
    raise SerializationError(error.format(attr, enum_obj))
msrest.exceptions.SerializationError: 'ServiceTag' is not valid value for enum <enum 'IpFilterTag'>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a FunctionApp
- Add Access Restriction of type **ServiceTag** for example "AzureEventGrid"
- Try to add any sort of IPv4 restriction
- `az functionapp config access-restriction add --resource-group {} --name {} --action {} --ip-address {} --priority {}`

## Expected Behavior

Adding additional IP restrictions appends new restrictions to a FunctionApp without errors.

## Environment Summary
```
Linux-4.15.0-1103-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.18.0
azure-cli-ml 1.20.0

Extensions:
ai-examples 0.2.5
azure-cli-ml 1.20.0

```
## Additional Context

We would like to secure our Azure Functions and adding IP restrictions to each one of them.
We would like to be able to add IP restrictions to an Azure Function with ServiceTag restriction.

Is there a feature request for adding ServiceTag restriction with az cli?

**Comment by yonzhan** [comment]
functionapp

**Comment by carltonu3sq** [comment]
I have the exact same issue with `az webapp config access-restriction add`.

**Comment by kolendomichal** [comment]
> I have the same issue with `az webapp config access-restriction add`, but I'm not even specifying a ServiceTag as far as I'm aware. I'm using the azure cli task in Azure pipelines and running the following:
> 
> ```
> az webapp config access-restriction add --resource-group <resource-group> --name <name> --rule-name <rule-name> --action Allow --ip-address <ip> --priority 100
> ```
I presume you have a 'ServiceTag' access restriction added to your web app?
If yes, then the issue is the same, although I suggest verifying the same command but with Azure Powershell.
It might work

**Comment by carltonu3sq** [comment]
> > I have the same issue with `az webapp config access-restriction add`, but I'm not even specifying a ServiceTag as far as I'm aware. I'm using the azure cli task in Azure pipelines and running the following:
> > ```
> > az webapp config access-restriction add --resource-group <resource-group> --name <name> --rule-name <rule-name> --action Allow --ip-address <ip> --priority 100
> > ```
> 
> I presume you have a 'ServiceTag' access restriction added to your web app?
> If yes, then the issue is the same, although I suggest verifying the same command but with Azure Powershell.
> It might work

I just checked and there is in fact a restriction on the web app. I'll give Azure Powershell a try!

**Comment by kolendomichal** [comment]
@yonzhan  Any update on this?

**Comment by yonzhan** [comment]
functionapp related commands are owned by service team.

**Comment by apawast** [comment]
@gzuber could you please investigate this?

**Comment by kolendomichal** [comment]
@apawast  @gzuber  any update on this?

**Comment by kolendomichal** [comment]
@apawast  @gzuber bump

**Comment by makokui** [comment]
Hello @kolendomichal @apawast @gzuber 
This issue seems to be resolved with latest version. I am not sure whether it was fixed explicitly or if it was fixed by another fix.  was able to reproduce the same error in Azure CLI 2.22, which may have been improved in a recent update.
Can you confirm it?

az version
{
  "azure-cli": "2.23.0",
  "azure-cli-core": "2.23.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

az functionapp config access-restriction add --resource-group "my-resouce-group" --name "my-function" --priority 300 --action "Allow" --description "Allow from GitHub Actions only duaring deploying" --ip-address "xx.xx.xx.xx" --rule-name "test" --scm-site "true"
[
  {
    "action": "Allow",
    "description": null,
    "headers": null,
    "ipAddress": "ActionGroup",
    "name": "ServiceTag",
    "priority": 100,
    "subnetMask": null,
    "subnetTrafficTag": null,
    "tag": "ServiceTag",
    "vnetSubnetResourceId": null,
    "vnetTrafficTag": null
  },
…

**Comment by kolendomichal** [comment]
Yes, you are right. Thank you for that.
The issue seems to be resolved, I am closing it.
