### ISSUE TITLE
Update VMSS Orchestration Mode Parameter to 'flexible' instead of 'VM'

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#16666]
**Resource Provider**

Microsoft.Compute

**Description of Feature or Work Requested**
Update parameter for VMSS Orchestration mode. We have deprecated the parameters 'ScaleSetVM, VM' Allowed values should now be 'uniform, flexible' with default Uniform.

    --orchestration-mode      [Preview] : Choose how virtual machines are managed by the
                                          scale set. In VM mode, you manually create and add a
                                          virtual machine of any configuration to the scale set. In
                                          ScaleSetVM mode, you define a virtual machine model and
                                          Azure will generate identical instances based on that
                                          model.  Allowed values: ScaleSetVM, VM.  Default:
                                          ScaleSetVM.

As documented in the swagger
https://github.com/Azure/azure-rest-api-specs/blob/082a554784b6f6658998b7fbcc8c030390e7d0d3/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json#L10098

    "OrchestrationMode": {
      "type": "string",
      "description": "Specifies the orchestration mode for the virtual machine scale set.",
      "enum": [
        "Uniform",
        "Flexible"
      ],
      "x-ms-enum": {
        "name": "OrchestrationMode",
        "modelAsString": false
      }
    },

**Minimum API Version Required**

2019-12-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/082a554784b6f6658998b7fbcc8c030390e7d0d3/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json

**Target Date**

2/15/2021

**Comment by yungezz** [comment]
hi @qwordy could you pls evaluate impact of the breaking change? thanks.

**Comment by qwordy** [comment]
NumInvocations=58. It is not widely used.
```
HttpIncomingRequests
| where TIMESTAMP > ago(30d)
| where userAgent contains 'AzureCLI/2.'
| where commandName startswith 'vmss create' and parameterSetName contains '--orchestration-mode '
| summarize NumInvocations=dcount(clientRequestId)
```

**Comment by fitzgeraldsteele** [comment]
If you want to check my subid, I bet most of them are from me. partial subid 576f5...cc4



Jerry
Steele
Microsoft
senior program manager
425.421.2566


________________________________
