### ISSUE TITLE
az aks update --enable-managed-identity --assign-identity fails with UnrecognizedArgumentError

### ISSUE THREAD

**Issue by velvia** [Azure/azure-cli#16678]
## Describe the bug

**Command Name**
`az aks update`

**Errors:**
```
UnrecognizedArgumentError: unrecognized arguments: --enable-managed-identity --assign-identity <REDACTED>
```

According to this article: https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

We can update an existing AKS cluster to enable a user managed identity.  What I'm trying to do is to allow a Python app running in our AKS cluster to authenticate using user managed identities via the `ManagedIdentityCredential` Python SDK API.  However the az aks update command fails.

If there is a different way to enable our user managed identity for AKS please let us know, thanks.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update -g {} -n {} --enable-managed-identity --assign-identity {}`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.7
Installer: HOMEBREW

azure-cli 2.18.0

```

**Comment by yonzhan** [comment]
aks

**Comment by RakeshMohanMSFT** [comment]
The command is working. Please upgrade to latest azure cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
`az aks update -g Issue16678 -n Issue16678cluster --enable-managed-identity --assign-identity /subscriptions/<subid>/resourcegroups/Issue16678/providers/Microsoft.ManagedIdentity/userAssignedIdentities/Issue16678i
dentity`
The behavior of this command has been altered by the following extension: aks-preview
Your cluster is already using systemassigned managed identity, and you are going to update the cluster to use userassigned managed identity.
Are you sure you want to perform this operation? (y/N): y
