### ISSUE TITLE
"az storage blob download" fails with "Permission denied" if the destination file is a directory

### ISSUE THREAD

**Issue by roander-msft** [Azure/azure-cli#16679]
**Describe the bug**
"az storage blob download" fails with "Permission denied" if the destination file is a directory. It makes sense that it fails. The bug is that the error message is non-specific and confusing for the user.

**To Reproduce**
From powershell:
```powershell
# C:\test is a directory
mkdir C:\test;

$containerName = "anyContainerName";
$storageAccountConnectionString = "anyStorageAccount";
$blobName = "anyBlobName";

# We pass the destination file path as the directory we created above
az storage blob download --container-name $containerName --connection-string $storageAccountConnectionString --name $blobName --file C:\test
```

Fails like so:
```powershell
FileOperationError: [Errno 13] Permission denied: 'C:\\test'
```

**Expected behavior**

Would be more helpful for the user if the command failed with a more specific error message like `Error: Destination file "C:\test" is a directory`

**Environment summary**

- Windows 10
- Powershell 5.1.19041.610
- az --version: 
    azure-cli 2.16.0
    core 2.16.0
    telemetry 1.0.6
    Python (Windows) 3.6.8 ... MSC v.1916 32 bit (Intel)

**Additional context**

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @evelyn-ys, could you help take a look?
