### ISSUE TITLE
'[Errno 22] Invalid argument' for az keyvault secret list/show

### ISSUE THREAD

**Issue by houk-ms** [Azure/azure-cli#16683]
**Describe the bug**

If a secret's **Activation Date** or **Expiration Date** is set out of range year 1970 – 2038 (need to confirm, for windows10 & python 3.8.2, the range is around 1970-3000), the `az keyvault secret list/show` commands will fail.

This is due to [Python crash on Windows with a datetime close to the epoch](https://stackoverflow.com/questions/56931738/python-crash-on-windows-with-a-datetime-close-to-the-epoch), and only on windows.

This is actually an issue in CLI dependency (datetime), so the issue may appear beyond KeyVault.

**To Reproduce**

- Add a new secret in your vault with **Expiration Date** 3000-01-01
- Run `az keyvault secret show` to show the secret on windows

**Expected behavior**

Yo will get the error message `[Errno 22] Invalid argument` on windows, while linux OSes will succeed.

**Environment summary**

Only on windows

**Additional context**

**Comment by houk-ms** [comment]
Keyvault

**Comment by RakeshMohanMSFT** [comment]
@houk-ms This issue is fixed
