### ISSUE TITLE
Unable to login to ACR

### ISSUE THREAD

**Issue by akashpandey111** [Azure/azure-cli#16684]
## Describe the bug

**Command Name**
`az acr login`

**Errors:**
```
APIVersion 2019-12-01-preview is not available
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/acr/_client_factory.py, ln 19, in cf_acr_registries
    return get_acr_service_client(cli_ctx).registries
azure/mgmt/containerregistry/container_registry_management_client.py, ln 208, in registries
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-12-01-preview is not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr login -n {}`

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid
Python 3.6.9
Installer: PIP

azure-cli 2.14.2 *
azure-cli-ml 1.18.0

Extensions:
azure-cli-ml 1.18.0

```

**Comment by yonzhan** [comment]
acr

**Comment by yugangw-msft** [comment]
setup bugs

**Comment by fengzhou-msft** [comment]
@akashpandey111 we recommend to use debian packages as instructed in [install doc](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt&view=azure-cli-latest).

In your case, you may have installed a different version of `azure-mgmt-containerregistry` in your python environment than the version CLI requires (probably related to some steps in azure machine learning setup). Please run `pip show azure-mgmt-containerregistry` to check the version and run `pip install azure-mgmt-containerregistry==3.0.0rc15` if you're seeing a different version.

**Comment by fengzhou-msft** [comment]
@akashpandey111 can you tell us how you installed `azure-cli`? Did you follow some other doc?
