### ISSUE TITLE
WebApp:az webapp deleted restore should create destination site if does not exist. 

### ISSUE THREAD

**Issue by rmarr2** [Azure/azure-cli#16689]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When trying to restore deleted site and the site used in the --Name parameter does not exist this results in  404 .
This is inconsistent with the Powershell experience which will create the site if the does not exust

[Restore-AzDeletedWebApp (Az.Websites) | Microsoft Docs](https://docs.microsoft.com/en-us/powershell/module/az.websites/restore-azdeletedwebapp?view=azps-5.3.0)
-- Example 1

Failure  Example where destSitename  does not exist.
az webapp deleted restore --deleted-id "/subscriptions/<sub>/providers/Microsoft.Web/locations/Central US/deletedSites/1997322" --name destSitename --resource-group rgName --subscription <subid>
Result.  
ResourceNotFound: The Resource 'Microsoft.Web/sites/<DestinationSiteName> under resource group ‘<RG>' was not found.

**To Reproduce**

1. Create and Delete and  Azure App Service app ( Cannot be Functions consumption or EP, not currently supported)
2. Get the Deleted Site Id using "az webapp deleted list":
3. Execute the restore command targeting where the site in  --Name does not exist

**Expected behavior**
Can this be changed to be consistent with Powershell where the destination site is created ?
Otherwise update the documentation to reflect that the destination site in the --name parament must be created first

**Environment summary**
Azure Cloud Shell
az --version
azure-cli                         2.18.0

core                              2.18.0
telemetry                          1.0.6

Extensions:
ai-examples                        0.2.5
azure-cli-ml                      1.20.0

**Additional context**

**Comment by yonzhan** [comment]
webapp

**Comment by ThejaChoudary** [comment]
@rmarr2 able to repro the issue.Will look into this 
Thanks!

**Comment by sulabh-msft** [comment]
Ashok merged the PR for this.

https://github.com/Azure/azure-cli/pull/25374/files

@gsethdev  Can we close this issue now?
