### ISSUE TITLE
az group exists appends \r to the output

### ISSUE THREAD

**Issue by shaunm-msft** [Azure/azure-cli#16695]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az group exists appends \r to the output. It should return "true" or "false" but instead it returns something like "false\r".

So my bash script looks like this:
if [ $(az group exists --name doesnt_exist) == $'false\r' ]

This is what I expected it to look like, but this doesn't work.
if [ $(az group exists --name doesnt_exist) == $'false' ]

You can see the result of the carriage return if you do this:
echo "group_exists=$(az group exists --name doesnt_exist). If this is false, then it's wrong"
The "group_exists=" is overwritten by the end of the echo text.

**Environment summary**
Using WSL 1.0 with Ubuntu 18.04
az cli version 2.18.0
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

**Comment by yonzhan** [comment]
ARM

**Comment by panaut0lordv** [comment]
It happens on AMD64 as well and actually it returns `$'true\r\n'` (hex: 7472 7565 0d0a) but your subshell call `$()` truncates all trailing newlines. If output would be only `$'true\n' (hex: 7472 7565 0a) subshell would behave as expected.

Therefore I agree that having CLI tool on Linux output MS line ending is not only unsettling but qualifies as a bug as this extraneous CR (0d aka carriage return) makes what should have been an easy "throw me together" type of development into "weird behaviour hunt".

BTW You could go as well with `[[ $(az exists…) == "true"* ]]` (not sure which is faster) but mind you it's not POSIX.

**Comment by ptcalex** [comment]
Other CLI commands I stumble upon with this bug are:
```
az group show
az network vnet show
az network vnet subnet show

```

**Comment by shaunm-msft** [comment]
I hit it in this one as well:
`az ad sp create-for-rbac`

**Comment by jiasli** [comment]
Please see the explanation at https://github.com/Azure/azure-cli/issues/13573#issuecomment-888791313.
