### ISSUE TITLE
Reset custom DNS Servers on vNet back to default (Azure-provided)

### ISSUE THREAD

**Issue by wordlessitguy** [Azure/azure-cli#16699]
When creating or updating a vnet using Azure CLI you can set DNS servers (using --dns-servers command) - however there does not appear to be a way to reset this back to the Azure-provided DNS using the Azure CLI (other than using a generic update argument to remove dhcpOptions?).

This is possible on a network interface -

`
Command
    az network nic update : Update a network interface.

Arguments
    --accelerated-networking : Enable accelerated networking.  Allowed values: false, true.
    --ip-forwarding          : Enable IP forwarding.  Allowed values: false, true.
    --network-security-group : Name or ID of the associated network security group.
    --no-wait                : Do not wait for the long-running operation to finish.

DNS Arguments
    _--dns-servers            : Space-separated list of DNS server IP addresses. Use ""('""' in
                               PowerShell) to revert to default Azure servers._
`

Solution - 

Use same solution as above for a vnet  (--dns-servers ""('""') or add flag (--az-provideddns) to reset DNS back to Azure provided DNS.

Additional note - update the DNS arguments note or documentation on how to revert when using bash?

**Comment by wordlessitguy** [comment]
Found workaround - can instead pass '' and this has the impact of nulling the DNS server list and Azure provided being used instead.

i.e -

`az network vnet update --name <name> --resource-group <rgroup> --dns-servers  ''`

{
  "addressSpace": {
    "addressPrefixes": [
      "10.0.0.0/8"
    ]
  },
  "bgpCommunities": null,
  "ddosProtectionPlan": null,
  "dhcpOptions": {
    "dnsServers": []
  },

Suggest documentation gets updated to reflect this behaviour and\or help comment on command instead?

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
@wordlessitguy Thank you for your feedback and we will add it to 'help' message.

**Comment by heavenlyren** [comment]
Adding just a quick comment if anyone struggle with this.
On python I had to use this instead :   --set dhcpOptions={'dnsServers':[]}
to reset to Azure Provided DNS. Otherwise it would keep saying '''' is not a valid IP Address.

**Comment by stuart23** [comment]
Thanks for the tip @benjamin-rousseau-shift.

For me, the json had to be quoted: `az network vnet update -g clp1h3s4g002x01madmnp206r --name clp1h3s4g002x01madmnp206r --set dhcpOptions="{'dnsServers':[]}"` (CLI version 2.55.0)
