### ISSUE TITLE
Trusted Launch - CLI

### ISSUE THREAD

**Issue by khyewei** [Azure/azure-cli#16692]
**Resource Provider**
 Microsoft.compute\virtualmachines & Microsoft.compute\disk

**Description of Feature or Work Requested**

Release CLI for Trusted Launch public preview. 

(1) Create a virtual machine with Trusted Launch.
	az group create -n myGroup -l eastus
az vm create \
--resource-group myResourceGroup \
--name myVM \
--image XXX \
--admin-username azureuser \
--generate-ssh-keys \
[--SecurityType trustedLaunch] \
[--EnableSecureBoot true] \ 
[--EnableVtpm true] 
	--SecurityType: specify if the VM is Trusted Launch enabled. Accepted value: trustedLaunch.
--EnableSecureBoot: turn on secure boot. Accepted values: false, true.
	--EnableVtpm: turn on vTPM. Accepted values: false, true.

(2) After creating virtual machines, you can optionally enable/disable secure boot and vTPM settings. To enable/disable secure boot and vTPM settings on exiting virtual machines:
az vm update \ 
--resource-group myResourceGroup \
--name myVM \
--EnableSecureBoot \ 
--EnableVtpm
	
[Note: Updating the virtual machine with secure boot and vTPM settings will trigger auto-reboot]
--EnableSecureBoot: turn on secure boot. Accepted values: false, true.
	--EnableVtpm: turn on vTPM. Accepted values: false, true.

**Minimum API Version Required**

2020-12

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/compute-2020-12/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json

**Target Date**

First week of March 2021.

**Comment by yungezz** [comment]
2020-12-01 Swagger ETA beginning of Feb.
