### ISSUE TITLE
Knack hasn't been republished to make status_tag_messages available to az cli

### ISSUE THREAD

**Issue by scseely** [Azure/azure-cli#16703]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
After forking and cloning the repo, I tried to do some development. I cannot start the app because of an import of this line: https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/__init__.py#L45.

Investigating, the functionality which defines knack.util.status_tag_messages was introduced on Dec 16, 2020 but the knack package on PyPi.org has not been updated since July 28, 2020 (https://pypi.org/project/knack/).

**To Reproduce**
Follow setup instructions, try to run. If you do not have the latest knack, you cannot proceed. Author who introduced the issue is also the maintainer of knack.

**Expected behavior**
The import should work and code should proceed.

**Environment summary**
Running on Windows using VS Code and a clean virtual environment (never installing packages into the global libraries for python).

**Additional context**
Also submitted details to author of the changes (discovered using BLAME).

**Comment by jiasli** [comment]
The current Azure CLI has a hard dependency on 

https://github.com/Azure/azure-cli/blob/c7155bbc4009e1665c3ef8a65d4163493b6434b6/src/azure-cli-core/setup.py#L52

[Knack 0.8.0rc2](https://pypi.org/project/knack/0.8.0rc2/) does have the `knack.util.status_tag_messages` defined:

https://github.com/microsoft/knack/blob/v0.8.0rc2/knack/util.py#L17-L20

```py
status_tag_messages = {
    'preview': "{} is in preview. It may be changed/removed in a future release.",
    'experimental': "{} is experimental and under development."
}
```

I believe `pip` will automatically install [Knack 0.8.0rc2](https://pypi.org/project/knack/0.8.0rc2/) for you whether you are installing the dev Azure CLI using 

- [`azdev setup`](https://github.com/Azure/azure-cli-dev-tools), or
- `pip install -e azure-cli azure-cli-core`

BTW, we are going to release 0.8.0 very soon (https://github.com/microsoft/knack/pull/231).

**Comment by scseely** [comment]
Verified that project is able to be debugged in VS Code now. Looks like this isn't a bug. Thank you!
