### ISSUE TITLE
Unexpected error messages in az acr run output

### ISSUE THREAD

**Issue by northtyphoon** [Azure/azure-cli#16700]
**Describe the bug**
I upgraded to latest 2.18.0 and noticed `az acr build/run` commands included the error messages like the below

Client-Request-ID=9bf92238-6111-11eb-b54a-ecb1d74de943 Retry policy did not allow for a retry: Server-Timestamp=Thu, 28 Jan 2021 02:36:22 GMT, Server-Request-ID=24848dbe-901e-00aa-4f1e-f52672000000, HTTP status code=404, Exception=The specified blob does not exist. ErrorCode: BlobNotFound.

**To Reproduce**
az acr run -r myregistry --cmd "docker images" /dev/null

**Expected behavior**
The error itself was legitimate and the code was just polling the log until it's available. It should not output the above message as error. Is there any framework or storage library change in azure cli?

**Comment by yungezz** [comment]
I don't think there's change at CLI error related with this. hi @houk-ms could you pls help to double check? thanks.

**Comment by northtyphoon** [comment]
@houk-ms do you have any insight of the issue?
