### ISSUE TITLE
Webapp:az cli does not show the same (correct) information as Azure PowerShell for the same resource

### ISSUE THREAD

**Issue by nexxai** [Azure/azure-cli#16719]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When looking for the fileChangeAuditEnabled property on a WebApp, az cli says the setting is "null" (incorrect), whereas Azure PowerShell shows it as being "true" (correct).  This also manifests itself when looking at the "JSON View" of the WebApp in the Azure portal.

**To Reproduce**
Have a site that has fileChangeAuditEnabled set to true.

In PowerShell:
```powershell
$config = Get-AzResource -ResourceGroupName $webApp.ResourceGroup `
   -ResourceType "Microsoft.Web/sites/config" `
   -ResourceName "$($webApp.Name)/web" `
   -apiVersion 2016-08-01
$config.Properties
```

In Azure CLI:
```
az webapp show --resource-group $webApp.ResourceGroup --name $webApp.Name
```

**Expected behavior**
The values to match

**Environment summary**
Currently macOS but since the issue also appears in the portal, I doubt it's architecture based.

```sh
⚡️•100% ➜ uname -a
Darwin nexxai.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

 2:58pm in ~
⚡️•100% ➜ az --version
azure-cli                         2.18.0

core                              2.18.0
telemetry                          1.0.6

Extensions:
front-door                         1.0.9

Python location '/usr/local/Cellar/azure-cli/2.18.0/libexec/bin/python'
Extensions directory '/Users/nexxai/.azure/cliextensions'

Python (Darwin) 3.8.7 (default, Dec 30 2020, 10:14:55)
[Clang 12.0.0 (clang-1200.0.32.28)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Additional context**
n/a

**Comment by yonzhan** [comment]
webapp

**Comment by calvinsID** [comment]
This property has not yet been swaggered/added to azure-rest-api-specs https://github.com/calvinsID/azure-rest-api-specs/blob/3db9067827c9e9d65d19b0dbf3c5c5d1ea51c067/specification/web/resource-manager/Microsoft.Web/stable/2020-09-01/CommonDefinitions.json

**Comment by nexxai** [comment]
Is there any plans to update the spec to do so?  I ask because we have a use case that this is blocking: if you take a WebApp, scale it up to a PremiumV2 SKU, and then execute an action that enables this flag, if you then want to scale it back down to a Basic SKU, you are permanently prevented from doing that because this flag can't be modified.

**Comment by kjohann** [comment]
This applies to other properties as well. It seems that most of, if not all of, the `siteConfig`-object under `properties` displays only default values when using as. Works fine with Az-Powershell.

**Comment by panchagnula** [comment]
@calvinsID it seems like the all properties under SiteConfig show as null on CLI . Can you or @Kotasudhakarreddy  take a quick look?

**Comment by Kotasudhakarreddy** [comment]
@panchagnula - API itself is returning null values for all the properties under `SiteConfig`

**Comment by Kotasudhakarreddy** [comment]
> @calvinsID it seems like the all properties under SiteConfig show as null on CLI . Can you or @Kotasudhakarreddy take a quick look?

created a bug #17053 for fixing the null properties under `SiteConfig`.

**Comment by Kotasudhakarreddy** [comment]
@nexxai - To fix this issue we required a Swagger update.  We will consider this under release scope once we get the next swagger update.

**Comment by nexxai** [comment]
@Kotasudhakarreddy Do you have an ETA on that?  Like is that happening in the next release or should we be expecting multiple releases before this is solved?

**Comment by Kotasudhakarreddy** [comment]
@nexxai right now i don't have an ETA for this as it required a swagger update. Will take it on priority once we get the latest swagger update.

**Comment by calvinsID** [comment]
@nexxai apologies for the delayed response. What CLI action enables this flag?

**Comment by btardif** [comment]
@seligj95 I think this is a general CLI issue and not specific to logs, might be something that @yutanglin16 needs to chime in for if there is some weirdness on how this is configured.

**Comment by seligj95** [comment]
This seems to be addressed in the latest CLI version and API version. Unable to repro. Please update to the latest CLI version. Closing for now. Please reopen if you're still experiencing the issue.
