### ISSUE TITLE
AttributeError: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update', VM password fails

### ISSUE THREAD

**Issue by SimonWrightTW** [Azure/azure-cli#16712]
I ran a script to update VM local admin passwords. This works fine running on my own PC using my account, but I get the error below when running it on a Hybrid Worker using a Managed Identity. The authentication step works and I have given the Managed Identity the same RBAC role as my own account. Any ideas?

## Describe the bug

**Command Name**
`az vm user update`

**Errors:**
```
'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-pwfpui04\knack\cli.py, ln 233, in invoke
azure\cli\core\commands\__init__.py, ln 659, in execute
azure\cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 715, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-s5x_2dzp\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 693, in _run_job
azure\cli\core\commands\__init__.py, ln 330, in __call__
pip-unpacked-wheel-c2pcumlb\azure\cli\core\__init__.py, ln 786, in default_command_handler
azure\cli\command_modules\vm\custom.py, ln 2224, in set_user
azure\cli\command_modules\vm\custom.py, ln 2211, in _reset_windows_admin
AttributeError: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm user update --name {} --resource-group {} --username {} --password {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.18.0

```

**Comment by yungezz** [comment]
hi @qwordy could you pls help to confirm?

**Comment by qwordy** [comment]
Similar issue https://github.com/Azure/azure-cli/issues/16392

**Comment by SimonWrightTW** [comment]
Thanks for this, but I don’t think the suggested solution is relevant as the Hybrid Worker VM is already running Azure CLI 2.18.0.

**Comment by qwordy** [comment]
It has been fixed in next release on 3/23.
