### ISSUE TITLE
Is $fqdn a powershell variable? Is this the most common use case example? 

### ISSUE THREAD

**Issue by diberry** [Azure/azure-cli#16721]
![image](https://user-images.githubusercontent.com/41597107/106208328-0a32c000-6178-11eb-8e3b-1341818444b3.png)

Seems like an actual string name may be more representative of a good example? Or is powershell the top use case? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e390289-90cc-30e2-de78-33b080f9c27d
* Version Independent ID: df152c25-2434-0831-46b7-e9d0e3015f06
* Content: [az webapp config hostname](https://docs.microsoft.com/en-us/cli/azure/webapp/config/hostname?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/hostname.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config/hostname.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by ThejaChoudary** [comment]
@diberry $fqdn is just an example given like 'Myresourcegroup' . Hostname is the costum domain which your willing to add to the appservice .
Hence proceeding to close the issue.Thanks!

**Comment by diberry** [comment]
@dbradish-microsoft @ThejaChoudary  $fqdn seems to be the most important param in the code snippet since it is about binding a host name but no where in the text is there any explanation of what it means. Why use a named variable a customer is supposed to pass in if it is never explained?
