### ISSUE TITLE
az upgrade should only upgrade az,  "brew cleanup" should be skipped 

### ISSUE THREAD

**Issue by edrandall** [Azure/azure-cli#16727]
## Describe the bug
I ran "az upgrade" expecting that the az cli command would be upgraded.
The whole of homebrew was upgraded including python 3.8 _and_ python 3.9.

From the output, only python 3.8 is a dependency of az, not python 3.9.   This may have been the result of an automatic  'brew cleanup' following on from the az update:

```
==> Summary
🍺  /usr/local/Cellar/python@3.8/3.8.7: 4,498 files, 72.6MB
==> Installing azure-cli
==> Pouring azure-cli-2.18.0.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/azure-cli/2.18.0: 18,244 files, 295.2MB
==> `brew cleanup` has not been run in 30 days, running now...
...
runed 1 symbolic links and 2 directories from /usr/local
==> Upgrading 1 dependent:
python@3.9 3.9.0 -> 3.9.1_6
==> Upgrading python@3.9 3.9.0 -> 3.9.1_6
==> Downloading https://homebrew.bintray.com/bottles/tcl-tk-8.6.11.catalina.bottle.tar.gz

curl: (22) The requested URL returned error: 407
Error: Failed to download resource "tcl-tk"
Download failed: https://homebrew.bintray.com/bottles/tcl-tk-8.6.11.catalina.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/andreas-kupries/critcl/archive/3.1.18.1.tar.gz

curl: (22) The requested URL returned error: 407
Error: Failed to download resource "tcl-tk--critcl"
Download failed: https://github.com/andreas-kupries/critcl/archive/3.1.18.1.tar.gz
==> Checking for dependents of upgraded formulae...
==> No broken dependents found!
```

(Yes I am using a proxy, and it had worked for downloading the updates to az;  I'm unsure why the 407's started at this point)

Following on from the python 3.9, the failures around the tcl package left me highly confused and not confident in the state of my system.
 
Suggest that 'az upgrade' pass an option to brew to skip that cleanup, if possible.   
Just upgrade do the minimum which concerns az.
Apparently this might be done by az setting `HOMEBREW_NO_INSTALL_CLEANUP=1` before az calls into brew..

**Command Name**
`az upgrade`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az upgrade`

## Expected Behavior

Minimum upgrade to perform az upgrade takes place.   Do not upgrade my entire homebrew system.

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.7
Installer: HOMEBREW

azure-cli 2.18.0

```

**Comment by yungezz** [comment]
thanks for sharing the finding! @fengzhou-msft could you pls help to have a look? thanks

**Comment by yungezz** [comment]
use #17150 to track az upgrade via brew.
