### ISSUE TITLE
[Compute] Hotpatching for Windows VMs

### ISSUE THREAD

**Issue by kjohn-msft** [Azure/azure-cli#16720]
**Resource Provider**
Compute

**Description of Feature or Work Requested**
Hotpatching is a new feature for VMs created from a specific image (to be announced at Ignite). It will function as part of Automatic VM guest patching for eligible VMs.

Automatic VM guest patching provides customers an easy-to-onboard solution to maintain security compliance for their virtual machines. This feature provides:

1. Simple onboarding – Enrolling a VM requires configuring one property on the VM model (process detailed below) with no further onboarding actions needed.
2. Automatic compliance – Most VMs (including dev/test) have compliance requirements for security/critical vulnerabilities and using automatic in-guest patching keeps the virtual machine compliant without additional overhead.
3. Availability-first patching – Automatic in-guest patching is orchestrated through an availability-first process (detailed below) which ensures maximum uptime for the customer’s application.

To onboard a new VM to automatic in-guest patching, the following property settings must be included in the VM model/template:
"windowsConfiguration": {
"provisionVMAgent": true,
"patchSettings": {
"patchMode": "AutomaticByPlatform",
**"enableHotpatching": true**
}
}

CLI support is requested to set the above flag on the VM model when creating the VM or modifying it.

**Minimum API Version Required**
2020-12-01

**Swagger Link**
Link for swagger: https://github.com/Azure/azure-rest-api-specs/blob/compute-2020-12/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json

**Target Date**
March 1st Public Preview (Ignite)

**Comment by qwordy** [comment]
Will plan it.

**Comment by qwordy** [comment]
It is already released.
az vm create --enable-hotpatching
