### ISSUE TITLE
az container create error

### ISSUE THREAD

**Issue by czmirek** [Azure/azure-cli#16735]
## Describe the bug
Got this error when trying to create a new container attached to existing VNET subnet. VNET is in a different resource group, everything is in West Europe. 

The command created a new VNET with same name in myresourcegroup

**Command Name**
`az container create`

**Errors:**
```
'NetworkProfile' object has no attribute 'result'
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-pwfpui04\knack\cli.py, ln 233, in invoke
azure\cli\core\commands\__init__.py, ln 659, in execute
azure\cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 715, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-s5x_2dzp\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 693, in _run_job
azure\cli\core\commands\__init__.py, ln 330, in __call__
pip-unpacked-wheel-c2pcumlb\azure\cli\core\__init__.py, ln 786, in default_command_handler
azure\cli\command_modules\container\custom.py, ln 190, in create_container
azure\cli\command_modules\container\custom.py, ln 348, in _get_vnet_network_profile
AttributeError: 'NetworkProfile' object has no attribute 'result'
```

## To Reproduce:
- Create or have existing VNET and subnet with container group delegation
- `az container create -g myresourcegroup --name testcontainer --image Ubuntu  --command-line "tail -f /dev/null" --vnet myazurevnet --subnet mycontainersubnet`

## Expected Behavior
Container is successfully created and attached to existing subnet in existing virtual network.
No new virtual network is created. According to the documentation I should be able to reference existing virtual network and existing subnet.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.18.0

Extensions:
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
container

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and retry again.
