### ISSUE TITLE
az cli docker images uses outdated python image

### ISSUE THREAD

**Issue by StefanSchoof** [Azure/azure-cli#16748]
## Describe the bug
The azure cli docker image uses the image version 3.6.10, see
https://github.com/Azure/azure-cli/blob/dev/Dockerfile#L6
but the offical python docker image no longer supports 3.6.10 only 3.6.12 has a supported image, see https://hub.docker.com/_/python

With this old base image, the image may contain insecure libs.

## To Reproduce:
n/a

## Expected Behavior
The azure cli docker image always uses a supported base image.

## Environment Summary
```
Linux-4.19.128-microsoft-standard-x86_64-with
Python 3.6.10
Installer: DOCKER

azure-cli 2.18.0

```

**Comment by yungezz** [comment]
hi @fengzhou-msft let's plan it accordingly.

**Comment by StefanSchoof** [comment]
@fengzhou-msft @yungezz Do you have now a process to keep the python version up to date with a supported version or will this happen in few months again?

**Comment by fengzhou-msft** [comment]
We don't have a process to automatically update the python version yet.

**Comment by StefanSchoof** [comment]
Okay, thanks for the info. Then I will create a issue of I spot this again
