### ISSUE TITLE
doc for az storage account management-policy update need example(s)

### ISSUE THREAD

**Issue by dennisseah** [Azure/azure-cli#16743]
there are no examples of how to update lifecycle policy using `az storage account management-policy update` command cli.
the policy is in JSON format. how do we set it in command line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f84b325-33af-86ab-749e-faec2e01a1f3
* Version Independent ID: 87036460-df59-9239-680d-29c68a0490bb
* Content: [az storage account management-policy](https://docs.microsoft.com/en-us/cli/azure/storage/account/management-policy?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/account/management-policy.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/account/management-policy.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
@zhangyan133  could you help add it?
