### ISSUE TITLE
No CLI command to update managed app definition

### ISSUE THREAD

**Issue by benjamincburns** [Azure/azure-cli#16740]
**Is your feature request related to a problem? Please describe.**
Based on the [Azure Management API reference documentation](https://docs.microsoft.com/en-us/rest/api/managedapplications/applicationdefinitions/createorupdate) it would appear that it's possible to update an existing managed application definition. Unfortunately, there's no update command in the CLI to do this.

**Describe the solution you'd like**
Ideally `az managedapp definition update ...` would be a valid command, and it'd accept all of the same flags as `az managedapp definition create ...`

It turns out that running the `create` command when the managed app definition already exists appears to work, as behind the scenes it's using the same `PUT` request. If that's the case, probably all that's necessary is to create an `update` command that's essentially an alias of the `create` command, but likely with slightly modified help text.

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
@benjamincburns  Hi, if we design the update command as an alias for the create command, the required parameters will be the same. May I ask if this is in line with your expectations?

**Comment by benjamincburns** [comment]
@zhoxing-ms - sounds good to me.
