### ISSUE TITLE
Got ResourceNotFoundError:  The Resource 'Microsoft.Network/routeTables/WinRouteTable' under resource group 'WindowsDevRG' wasnot found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

### ISSUE THREAD

**Issue by pandeyvaibhav** [Azure/azure-cli#16744]
Hi, 

I tried executing this command from Azure shell:
az network route-table route create -g $RGName --route-table-name $RouteTable -n MyRoute --next-hop-type VirtualAppliance --address-prefix 10.0.0.0/16 --next-hop-ip-address 10.0.100.4

And got this error:
This command is implicitly deprecated because command group 'network route-table' is deprecated and will be removed in a future release. Use'network vhub route-table' instead.
ResourceNotFoundError: (ResourceNotFound) The Resource 'Microsoft.Network/routeTables/WinRouteTable' under resource group 'WindowsDevRG' wasnot found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

Azure documentation page for: ~az network route-table route create" did not showed any mention of future deprication. Should'nt this get mentioned on the page?

Please suggest or update documentation.

Thanks,
Vaibhav 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebc636f9-e84c-eee0-dcb3-2d35cd4f8190
* Version Independent ID: 652b69dc-33c6-3579-603d-43c6c2fffd1a
* Content: [az network route-table route](https://docs.microsoft.com/en-us/cli/azure/network/route-table/route?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/route-table/route.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/route-table/route.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
Thank you for your feedback and we will check it soon.

**Comment by msyyc** [comment]
@pandeyvaibhav It seems that I couldn't reproduce it.
![image](https://user-images.githubusercontent.com/70930885/112113781-3c015980-8bf2-11eb-8dc5-bc94ed02e19e.png)

**Comment by kairu-ms** [comment]
I couldn't reproduce it.
