### ISSUE TITLE
Azure CLI Update for VMSS Orchestration Mode 

### ISSUE THREAD

**Issue by ajjha-az** [Azure/azure-cli#16747]
**Resource Provider**
Microsoft.Compute/virtualMachineScaleSets

**Description of Feature or Work Requested**
Virtual machines scale sets provide a logical grouping of platform-managed virtual machines. With scale sets, you create a virtual machine configuration model, automatically add or remove additional instances based on CPU or memory load, and automatically upgrade to the latest OS version. Traditionally, scale sets allow you to create virtual machines using a VM configuration model provided at time of scale set creation, and the scale set can only manage virtual machines that are implicitly created based on the configuration model.

With the scale set orchestration mode (preview), you can now choose whether the scale set should orchestrate virtual machines which are created explicitly outside of a scale set configuration model, or virtual machine instances created implicitly based on the configuration model. Scale set orchestration mode also helps you design your VM infrastructure for high availability by deploying these VMs in fault domains and Availability Zones.

Virtual machine scale sets will support 2 distinct orchestration modes: Uniform and Flexible. 

Flexible – Virtual machines created outside of the scale set can be explicitly added to the scaleset. This is the new mode to be added. Virtual Machines created by VMSS scale out will be ARM tracked VM resources similar to Single VMs. 
Uniform - Existing ScaleSet with implicit VM resources. 

In this release, if customer specifies orchestrationMode=Flexible, the scale set is set to VMO mode. 

Piping scenarios / how these cmdlets are used with existing cmdlets

Create a scale set in Flexible Orchestration mode. Create N VMs and add to scale set or Scale out with the Virtual Machine Profile defined at the ScaleSet model. 

Sample of end-to-end usage

Sample templates here - https://microsoft.sharepoint.com/teams/vmssvmorchestrationmode/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2Fvmssvmorchestrationmode%2FShared%20Documents%2Fsample%20templates&p=true&originalPath=aHR0cHM6Ly9taWNyb3NvZnQuc2hhcmVwb2ludC5jb20vOmY6L3Qvdm1zc3Ztb3JjaGVzdHJhdGlvbm1vZGUvRW92NnF2YkJESlJJdFAyNHU3WWp5Tk1CaWdtOWFuWldNNmY1UHlSbFlKTUhKQT9ydGltZT1fX28wa1QzRzJFZw
**Minimum API Version Required**

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/12062/files

**Target Date**
02/26/2021

**Comment by yungezz** [comment]
hi @qwordy , could you pls help to confirm is this same ask from Jerry on https://github.com/Azure/azure-cli/issues/16666? thanks

**Comment by qwordy** [comment]
https://github.com/Azure/azure-cli/issues/16666 focuses on renaming orchestration mode values. Let's just keep both issues.

**Comment by qwordy** [comment]
@ajjha-az According to Jerry's latest email, Azure CLI has supported all available features now. Next is Public Preview 5/3.
