### ISSUE TITLE
Not able to authenticate throw the application from visual studio 2019

### ISSUE THREAD

**Issue by khaldelshiekh** [Azure/azure-cli#16745]
Not able to open my application from visual studio it was working as expected before now. I'm getting the below error
**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2021-01-05T05:09:31.5970000Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2021-01-14T06:26:06.0000000Z'.\r\nTrace ID: 0aaa7d90-73c6-46cc-9c9d-fc161b282000\r\nCorrelation ID: eb217b32-36ad-410b-9b1e-f71cd6947581\r\nTimestamp: 2021-01-31 05:56:19Z","error_codes":[50173],"timestamp":"2021-01-31 05:56:19Z","trace_id":"0aaa7d90-73c6-46cc-9c9d-fc161b282000","correlation_id":"eb217b32-36ad-410b-9b1e-f71cd6947581","error_uri":"https://login.microsoftonline.com/error?code=50173"}
Traceback (most recent call last):
Temp\pip-unpacked-wheel-uf4h10vu\knack\cli.py, ln 215, in invoke
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --output {} --resource {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.14.1 *

Extensions:
interactive 0.4.4

**Comment by yonzhan** [comment]
Account

**Comment by jiasli** [comment]
As the error suggested:

> AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. 

Your AAD tenant has revoked the refresh token. Could you run `az login` again and see if the issue is solved?

**Comment by khaldelshiekh** [comment]
It is solved by refreshing my login on visual studio 2019 I just logged out and logged-in seems my old password was cached. Thank you everyone who tried to help

**Comment by jiasli** [comment]
@khaldelshiekh, glad to know the issue is solved. If there are any further questions, feel free to let us know.
