### ISSUE TITLE
`az account get-access-token` crashed in china

### ISSUE THREAD

**Issue by woodymoo** [Azure/azure-cli#16758]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: db1bea1a-fb52-4233-a625-e778034b7d00\r\nCorrelation ID: 4c3d230a-4b4e-41c9-9a6e-c0bc11f2c545\r\nTimestamp: 2021-02-02 06:30:32Z","error_codes":[9002313],"timestamp":"2021-02-02 06:30:32Z","trace_id":"db1bea1a-fb52-4233-a625-e778034b7d00","correlation_id":"4c3d230a-4b4e-41c9-9a6e-c0bc11f2c545","error_uri":"https://login.microsoftonline.com/error?code=9002313"}
Traceback (most recent call last):
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --output {} -t {} --resource {}`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.6
Installer: HOMEBREW

azure-cli 2.14.2

```

**Comment by yonzhan** [comment]
account

**Comment by jiasli** [comment]
The error message is from AAD service, not CLI itself.

Have you switched the cloud before running `az account get-access-token`?
```
az cloud set --name AzureChinaCloud
```

To better help us identify the issue, could you share the original command with actual argument values?
