### ISSUE TITLE
az network nic list query example not working?

### ISSUE THREAD

**Issue by jeffbearer** [Azure/azure-cli#16754]
I'm in cloud shell with az cli installed.   trying exactly the query example from the docs:
 az network nic list --query "[?dnsSettings.internalDomainNameSuffix=`{dnsSuffix}`]"

and it fails saying:

InvalidArgumentValueError: argument --query: invalid jmespath_type value: '[?dnsSettings.internalDomainNameSuffix=]'
To learn more about --query, please visit: 'https://docs.microsoft.com/cli/azure/query-azure-cli'

I'm not an expert in adding query to az cli commands but maybe there is some other bug with az network nic, I can't even get simple queries to work like "[name, location]" which I think should work? idk.

interestingly that url also gives a 404 error.  need to file that bug too.

$ az version
{
  "azure-cli": "2.18.0",
  "azure-cli-core": "2.18.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "image-copy-extension": "0.2.8"
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29b6bb22-cb91-c7f8-995e-134d0fe5627f
* Version Independent ID: a92f24e8-36a0-808b-a9e7-598f85560b0f
* Content: [az network nic](https://docs.microsoft.com/en-us/cli/azure/network/nic?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/nic.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/nic.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by joedborg** [comment]
It needs to be `==`, I've just hit this bug too.

**Comment by yonzhan** [comment]
@msyyc will take a look

**Comment by msyyc** [comment]
same with https://github.com/Azure/azure-cli/issues/16754
