### ISSUE TITLE
Need way to enable diagnostics from cli for app gateways (and likely other entities)

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#1675]
This is supported in the web portal, but not seeing any way to do it from the CLI. If it is, a pointer would be appreciated.

**Comment by tjprescott** [comment]
This is likely part of Insights, which is being worked on for the CLI. For now, I would recommend enabling it via the portal or PS/Xplat.

**Comment by nneul** [comment]
Is there any news on this request?

**Comment by tjprescott** [comment]
@vishrutshah developed our current monitor commands, so he might be able to give an update on this. I can confirm that this is not a part of the Application Gateway API surface area.

**Comment by nneul** [comment]
In case it helps, this is what I have with assistance of MS support to be able to do it with powershell - which works, but - well - it's powershell. :(

```
Login-AzureRMAccount

$rgname = "resourcegroupname"
$omsname = "workspacename"
$gwname = "gwname"
$saname = "storageacct"

$sub = Get-AzureRmSubscription
$ws = Get-AzureRmOperationalInsightsWorkspace -Name $omsname -ResourceGroupName $rgname
$sa = Get-AzureRmStorageAccount -Name $saname -ResourceGroupName $rgname
$gateway = Get-AzureRmApplicationGateway -Name $gwname -ResourceGroupName $rgname

Get-AzureRmSubscription -SubscriptionName $sub.Name | Select-AzureRmSubscription

Set-AzureRmDiagnosticSetting -ResourceId $gateway.Id -StorageAccountId $sa.Id -WorkspaceId $ws.ResourceId -Enabled $true
```

**Comment by vishrutshah** [comment]
@nneul Did you get change to look at the command https://docs.microsoft.com/en-us/cli/azure/monitor/diagnostic-settings#create ?

**Comment by nneul** [comment]
Nope, but I have now, and that looks like an exact match to me. Going to try that out now.

**Comment by nneul** [comment]
This worked great. I'm not seeing any way to look up workspaces, but since it can be passed in by name, that's not an issue.

**Comment by nneul** [comment]
Thank you!

**Comment by prafulbusa** [comment]
Bottom line, we don't I don't see any CLI way to enable diagnostics for Azure VM.

**Comment by Parik10** [comment]
Do we have AZ CLI for Diagnostic logs enablement for Application Gateway/WAF ?? Or Can we use it in JSON directly ? Could you please suggest ?
