### ISSUE TITLE
WebApp:Cannot use "az webapp up" and get failure result

### ISSUE THREAD

**Issue by yasenstar** [Azure/azure-cli#16757]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
cannot import name 'DefaultErrorResponseException' from 'azure.mgmt.web.models' (/usr/lib/python3/dist-packages/azure/mgmt/web/models.py)
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 558, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 480, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
cli/command_modules/appservice/custom.py, ln 39, in <module>
    from azure.mgmt.web.models import KeyInfo, DefaultErrorResponseException
ImportError: cannot import name 'DefaultErrorResponseException' from 'azure.mgmt.web.models' (/usr/lib/python3/dist-packages/azure/mgmt/web/models.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --sku {} --name {}`

## Environment Summary
```
Linux-5.8.0-40-generic-x86_64-with-glibc2.32
Python 3.9.1+
Installer: DEB

azure-cli 2.18.0

```

**Comment by yonzhan** [comment]
webapp

**Comment by calvinsID** [comment]
Hi @yasenstar, can you pls try reinstalling CLI?

**Comment by yasenstar** [comment]
Already reinstalled but not help

Regards,
Xiaoqi

在 2021年2月2日，上午10:39，Calvin <notifications@github.com> 写道：

﻿

Hi @yasenstar<https://github.com/yasenstar>, can you pls try reinstalling CLI?

**Comment by ThejaChoudary** [comment]
Able to repro the issue.

**Comment by ThejaChoudary** [comment]
@Kotasudhakarreddy please look into this

**Comment by Kotasudhakarreddy** [comment]
@yasenstar - We are Unable to repro this at our end. Can you run the command with `--debug` and share the details that would be helpful to investigate further

**Comment by Kotasudhakarreddy** [comment]
@yasenstar - closing this issue as no response from you. Please try with latest `azure-cli  version - 2.20.0`. If you still face the issue please reopen with `--debug` details
