### ISSUE TITLE
az cli query error suggests users check out help url which returns a 404 error.

### ISSUE THREAD

**Issue by jeffbearer** [Azure/azure-cli#16755]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When you try to --query and it errors the error suggests users visit a help url.  that link goes to a 404.

**To Reproduce**
$ az network nic list --query "[?dnsSettings.internalDomainNameSuffix='{dnsSuffix}']"
InvalidArgumentValueError: argument --query: invalid jmespath_type value: "[?dnsSettings.internalDomainNameSuffix='{dnsSuffix}']"
To learn more about --query, please visit: 'https://docs.microsoft.com/cli/azure/query-azure-cli'

**Expected behavior**
HTTP 200 ok ;)   
either change the link.  or restore the help at that url.

**Environment summary**
latest az cli in azure cloud shell.

Azure:~$ az version
{
  "azure-cli": "2.18.0",
  "azure-cli-core": "2.18.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "image-copy-extension": "0.2.8"
  }
}

**Additional context**

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
@jeffbearer It is the problem in the use of JMESPath. You could reference https://jmespath.org/.
'''--query "[?dnsSettings.internalDomainNameSuffix='{dnsSuffix}']"
may should be 
'''--query "[?dnsSettings.internalDomainNameSuffix=='{dnsSuffix}']"
