### ISSUE TITLE
Az Backup Restore File - Provide valid item_name / --item-name

### ISSUE THREAD

**Issue by maxleonalbrecht** [Azure/azure-cli#16769]
## Describe the bug

**Command Name**
`az backup restore files mount-rp`

**Errors:**
```
Item not found. Please provide a valid item_name.
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 659, in execute
azure\cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 715, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-igh1xymj\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 693, in _run_job
azure\cli\core\commands\__init__.py, ln 330, in __call__
pip-unpacked-wheel-34tyr6f2\azure\cli\core\__init__.py, ln 784, in default_command_handler
azure\cli\command_modules\backup\custom.py, ln 532, in restore_files_mount_rp
azure\cli\command_modules\backup\custom.py, ln 852, in _validate_item
azure\cli\command_modules\backup\custom.py, ln 861, in _validate_object
ValueError: Item not found. Please provide a valid item_name.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az backup restore files mount-rp --container-name {} --item-name {} --rp-name {} --resource-group {} --vault-name {}`

## Expected Behavior

When I try to execute this Azure CLI Command I get the above shown error.

In the parameter --item-name I pass the name of the virtual machine.
This name is completely correct, because I use the same variable for --item-name in az backup recoverypoint list and az backup recoverypoint show.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1 *

```

**Comment by yonzhan** [comment]
backup

**Comment by pvrk** [comment]
@maxleonalbrecht : So, the parameters work fine when you run az recovery point show command but the same set of parameters don't work with az backup restore files mount-rp command?

**Comment by maxleonalbrecht** [comment]
Exactly.

**Comment by maxleonalbrecht** [comment]
So I found out the following. The item-name wasn't the problem.
The problem was the --container-name, which needs to be the name of the item too.
(https://docs.microsoft.com/en-us/cli/azure/backup/restore/files?view=azure-cli-latest)

Example:

$virtualMachineName = "vmxyz"

az backup restore files mount-rp --container-name $virtualMachineName --item-name $virtualMachineName --rp-name $recoveryPoints[$selectedRecoveryPoint].name --resource-group $recoveryPoints[$selectedRecoveryPoint].resourceGroup --vault-name  $vaultNameOfSelectedBackup

In this way it works.

**Comment by pvrk** [comment]
@maxleonalbrecht : In case of VM backup, the container name and item name are same since the Azure VM being backed up is the container as well as the item. Having said that, may I know what were you passing as the container name before giving it the VM name?

**Comment by pvrk** [comment]
@maxleonalbrecht : A gentle reminder.

**Comment by maxleonalbrecht** [comment]
Thanks, I got it working.
You can close this issue.
