### ISSUE TITLE
[VM] Add aliases to the parameter names of the image commands

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1676]
The `az vm image` commands are great, but the parameter names can feel a little verbose after using them regularly. For example, instead of needing to do something like this:

```shell
az vm image list --all -l westus --publisher meanio --offer meanio-050-vm --sku meanio-050-vm
```

It would be awesome to be able to do:

```shell
az vm image list --all -l westus -p meanio -o meanio-050-vm -s meanio-050-vm
```

**Comment by yugangw-msft** [comment]
for `--offer`, I will go with `-f`, as `-o` is taken for general output format

**Comment by lostintangent** [comment]
@yugangw-msft Ah good point! That sounds good.
