### ISSUE TITLE
error when running'az feedback'

### ISSUE THREAD

**Issue by khaledabdelfatah** [Azure/azure-cli#16767]
## Describe the bug

**Command Name**
``

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-4.15.0-1106-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.18.0
azure-cli-ml 1.20.0

Extensions:
ai-examples 0.2.5
azure-cli-ml 1.20.0

```

**Comment by yonzhan** [comment]
feedback

**Comment by yungezz** [comment]
hi @khaledabdelfatah could you pls share repro step to help trouble shooting? thanks
