### ISSUE TITLE
UnrecognizedArgumentError: unrecognized arguments: --auto-upgrade-channel stable

### ISSUE THREAD

**Issue by actini** [Azure/azure-cli#16764]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I am following this docs to enable auto-upgrade for AKS cluster https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel, but I am failed because  of "UnrecognizedArgumentError: unrecognized arguments: --auto-upgrade-channel stable" error

**To Reproduce**
Login in with az
az account set --subscription SUBSCRIPTION_ID
az feature register --namespace Microsoft.ContainerService -n AutoUpgradePreview --subscription SUBSCRIPTION_ID
az provider register --namespace Microsoft.ContainerService --subscription SUBSCRIPTION_ID --wait
az aks update --resource-group RESOURCE_GROUP --name AKS_NAME --auto-upgrade-channel stable --subscription SUBSCRIPTION_ID

**Expected behavior**
Should have auto-upgrade enabled for the AKS

**Environment summary**
**Ubuntu**
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
**Azure Cli**
{
  "azure-cli": "2.18.0",
  "azure-cli-core": "2.18.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Additional context**
Tried on Windows 10 with Azure Cli but also failed
{
  "azure-cli": "2.10.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.10.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "application-insights": "0.1.9"
  }
}

**Comment by yonzhan** [comment]
aks

**Comment by g3gurung** [comment]
I am also having a same error. Az cli 2.18.0
![Screenshot 2021-02-03 at 16 18 18](https://user-images.githubusercontent.com/6603227/106759811-d6eea600-663b-11eb-819b-70b1830dad9e.png)

**Comment by MateusAmin** [comment]
```
az version
{
  "azure-cli": "2.18.0",
  "azure-cli-core": "2.18.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

az aks update  --name $AKS_CLUSTER_NAME  --resource-group $RESOURCE_GROUP --auto-upgrade-channel stable
UnrecognizedArgumentError: unrecognized arguments: --auto-upgrade-channel stable
```

**Comment by actini** [comment]
Hi all, I got the solution, try to run `az extension add --name aks-preview` before `az aks update  --name $AKS_CLUSTER_NAME  --resource-group $RESOURCE_GROUP --auto-upgrade-channel stable`
@MateusAmin @g3gurung 

@yonzhan Maybe the Microsoft should address this in the documentation.

**Comment by yonzhan** [comment]
aks service team should look into above issue.

**Comment by g3gurung** [comment]
> Hi all, I got the solution, try to run `az extension add --name aks-preview` before `az aks update --name $AKS_CLUSTER_NAME --resource-group $RESOURCE_GROUP --auto-upgrade-channel stable`
> @MateusAmin @g3gurung
> 
> @yonzhan Maybe the Microsoft should address this in the documentation.

@actini yes this is the solution. I contacted the azure support and they said documentation needs to be updated with the extension.

**Comment by hoangelos** [comment]
I still get this error.  Even though I have aks-preview installed

`bash$ az version
{
  "azure-cli": "2.21.0",
  "azure-cli-core": "2.21.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.6",
    "azure-devops": "0.18.0",
    "databricks": "0.5.0",
    "interactive": "0.4.4"
  }
}`

Then when I try to use the -auto-upgrade-channel it fails in the same way despite the fact I've followed the rest of the documentation and have the preview installed:

`bash$ az aks upgrade --resource-group <resource-group> --name <aks-name> --auto-upgrade-channel stable
unrecognized arguments: --auto-upgrade-channel stable

TRY THIS:
az aks upgrade --kubernetes-version 1.12.6 --name MyManagedCluster --resource-group MyResourceGroup
Upgrade a managed Kubernetes cluster to a newer version. (autogenerated)

az aks upgrade --control-plane-only --kubernetes-version 1.12.6 --name MyManagedCluster --resource-group MyResourceGroup
Upgrade a managed Kubernetes cluster to a newer version. (autogenerated)

https://docs.microsoft.com/en-US/cli/azure/aks#az_aks_upgrade
Read more about the command in reference docs
`

**Comment by AshWilliams** [comment]
> I still get this error. Even though I have aks-preview installed
> 
> `bash$ az version { "azure-cli": "2.21.0", "azure-cli-core": "2.21.0", "azure-cli-telemetry": "1.0.6", "extensions": { "aks-preview": "0.5.6", "azure-devops": "0.18.0", "databricks": "0.5.0", "interactive": "0.4.4" } }`
> 
> Then when I try to use the -auto-upgrade-channel it fails in the same way despite the fact I've followed the rest of the documentation and have the preview installed:
> 
> `bash$ az aks upgrade --resource-group --name --auto-upgrade-channel stable
> unrecognized arguments: --auto-upgrade-channel stable
> 
> TRY THIS:
> az aks upgrade --kubernetes-version 1.12.6 --name MyManagedCluster --resource-group MyResourceGroup
> Upgrade a managed Kubernetes cluster to a newer version. (autogenerated)
> 
> az aks upgrade --control-plane-only --kubernetes-version 1.12.6 --name MyManagedCluster --resource-group MyResourceGroup
> Upgrade a managed Kubernetes cluster to a newer version. (autogenerated)
> 
> https://docs.microsoft.com/en-US/cli/azure/aks#az_aks_upgrade
> Read more about the command in reference docs
> `

Remember to also run this command before:

`az feature register --namespace Microsoft.ContainerService -n AutoUpgradePreview`

**Comment by hoangelos** [comment]
As I stated, I have long since run the acs-preview.  I've verified the output below.  I also ran the above, and have verified it below.  However, even so, it can't find the flag to enable the feature

`bash> az extension add --name aks-preview
Extension 'aks-preview' is already installed.

bash> az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/AutoUpgradePreview')].{Name:name,State:properties.state}"
Name                                           State
---------------------------------------------  ----------
Microsoft.ContainerService/AutoUpgradePreview  Registered

bash> az aks upgrade  --resource-group <resorce-group> --name <aks-name> --auto-upgrade-channel stable
unrecognized arguments: --auto-upgrade-channel stable

TRY THIS:
az aks upgrade --kubernetes-version 1.12.6 --name MyManagedCluster --resource-group MyResourceGroup
Upgrade a managed Kubernetes cluster to a newer version. (autogenerated)

az aks upgrade --control-plane-only --kubernetes-version 1.12.6 --name MyManagedCluster --resource-group MyResourceGroup
Upgrade a managed Kubernetes cluster to a newer version. (autogenerated)

https://docs.microsoft.com/en-US/cli/azure/aks#az_aks_upgrade
Read more about the command in reference docs`

**Comment by hoangelos** [comment]
@AshWilliams @g3gurung  read above.  Incorporated the suggestions, but this still is a bug.

**Comment by Malleich** [comment]
Any news on this? I have a policy in place which doesn't allow my company to use VMSS if automatic OS upgrade isn't active. Without this preview I can't activate auto OS upgrade and thus can't create any cluster.  
I'm using ansible to create an azure shell and get the error: 
"stderr": "ERROR: unrecognized arguments: --auto-upgrade-channel node-image

**Comment by rogelioamancisidor** [comment]
a bit off topic, but can you add spot nodes after you enabled `auto-upgrade`?
