### ISSUE TITLE
[Network] Default table output for public IPs doesn't display their IP address

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1677]
Simply running the `az network public-ip list` command doesn't display the actual IP addresses. It would be great to get this information without needing to resort to a custom query/format type.

**Comment by tjprescott** [comment]
The address is listed in the table as 'IpAddress'. It might be that when you tried to list the public IPs that the IP address had not been determined, but it is shown by default.

**Comment by lostintangent** [comment]
@tjprescott Ah that's a good point. The issue was probably that my PIPs were dynamic, and hadn't been reserved an IP at the time I queried them. I'll close this for now since I'm sure you're right, and I'll re-open if needed. Thanks!
