### ISSUE TITLE
Decouple the code of `next` in `azure-cli-core`

### ISSUE THREAD

**Issue by zhoxing-ms** [Azure/azure-cli#16770]
In order to decouple the code of `az next` in `azure-cli-core` and reduce the impact on the performance and stability of CLI，I set up this issue to track some items that need to be improved:
- [x] Migrate those methods (`log_cmd_history()`, `clean_exception_history()`) in utils into `next` extension
- [x] Use environment variables `AZURE_CORE_USE_COMMAND_INDEX` and reload command table to skip command index.
- [x] Delete method `log_latest_error_info()` and get exception information from the cache of Telemetry

Related PR: #15964

**Comment by jiasli** [comment]
Checkbox syntax can be a very good helper 😉:

```
- [ ] Register those methods (`log_cmd_history`,`log_latest_error_info`,`clean_exception_history`) in utils as events to move them into `next` extension
```

**Comment by yonzhan** [comment]
Core
