### ISSUE TITLE
az vm & az resource move failed deployment

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#16772]
CLI Team,

This bug was reported to me via email and I am copying the communication here for your review.

*****************************************
Tl;dr: looks like there is a bug and CLI lies about a failed deployment :D

I found a few issues with the script, which I fixed (variables had spaces between the variable = value, but it needs to be variable=value) and I move where you set subscription for the original VM.

When it got to creating the VM, I got the following:

xxxxx@yyyyy-t480:/mnt/c/Users/xxxxx$ az vm create --resource-group $destinationResourceGroup --name $vmName \
>     --attach-os-disk "/subscriptions/$destinationSubscription/resourceGroups/$destinationResourceGroup/providers/Microsoft.Compute/disks/DestinationDisk" \
>     --os-type $osType
Deployment failed. Correlation ID: 6f03828b-f17c-4071-9f5a-d87c571a6525. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMMarketplaceInvalidInput",
        "message": "Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request. VM: '/subscriptions/0f401833-78ff-4ebe-a797-67791c5fbdaa/resourceGroups/generalized/providers/Microsoft.Compute/virtualMachines/planlinux'."
      }
    ]
  }
}

Which is expected, because it needs the plan info. Note that is says “Deployment failed” – this is the interesting part.

So, I added that and got the same message you got – notice that it says “an update”:

xxxxx@yyyyy-t480:/mnt/c/Users/xxxxx$ az vm create --resource-group $destinationResourceGroup --name $vmName     --attach-os-disk "/subscriptions/$destinationSubscription/resourceGroups/$destinationResourceGroup/providers/Microsoft.Compute/disks/DestinationDisk"     --os-type $osType --plan-product $offer --plan-publisher $publisher --plan-name $plan
Azure Error: CannotSetPlanOnUpdate
Message: This resource was created without a plan. A new plan cannot be associated with an update.

On a hunch, I went to check to see what was in the destination resource group. Guess what? There was a new VM there with the right name. I suspect it was created during the first pass, even though it said it failed. 

I deleted the new VM and re-ran the create command, with the plan parameters, and it worked:

xxxxx@yyyyy-t480:/mnt/c/Users/xxxxx$ az vm create --resource-group $destinationResourceGroup --name $vmName     --attach-os-disk "/subscriptions/$destinationSubscription/resourceGroups/$destinationResourceGroup/providers/Microsoft.Compute/disks/DestinationDisk"     --os-type $osType --plan-product $offer --plan-publisher $publisher --plan-name $plan
{- Finished ..
  "fqdns": "",
  "id": "/subscriptions/0f401833-78ff-4ebe-a797-67791c5fbdaa/resourceGroups/generalized/providers/Microsoft.Compute/virtualMachines/planlinux",
  "location": "westcentralus",
  "macAddress": "00-0D-3A-D7-88-F0",
  "powerState": "VM running",
  "privateIpAddress": "10.1.1.8",
  "publicIpAddress": "13.78.131.35",
  "resourceGroup": "generalized",
  "zones": ""
}

Sooooo. It really shouldn’t have created the VM the first time, and it reported that the deployment failed – but it created a VM (and vNet, IP address etc). That is why it says “an update”. The VM is there and it thinks you are trying to update it with plan info.
********************************

**Here are the content of the attached file:**

******************************
#!/bin/bash
# Set variable values before proceeding. 

# Variables
sourceResourceGroup=myresourcegroup
sourceSubscription=7891b050-2d44-4a2c-8b96-xxxxxxxx
vmName=planlinux

destinationResourceGroup=generalized
destinationSubscription=0f401833-78ff-4ebe-a797-xxxxxxxx

# Set your current subscription for the source virtual machine
az account set --subscription $sourceSubscription

# Load variables about your virtual machine
# osType = windows or linux
osType=$(az vm get-instance-view --resource-group $sourceResourceGroup \
    --name $vmName --query 'storageProfile.osDisk.osType' --output tsv)

# offer = Your offer in Marketplace
offer=$(az vm get-instance-view --resource-group $sourceResourceGroup \
    --name $vmName --query 'storageProfile.imageReference.offer' --output tsv)

# plan = Your plan in Marketplace
plan=$(az vm get-instance-view --resource-group $sourceResourceGroup \
    --name $vmName --query 'plan.name' --output tsv)

# publisher = Your publisher in Marketplace
publisher=$(az vm get-instance-view --resource-group $sourceResourceGroup \
    --name $vmName --query 'plan.publisher' --output tsv)

# Get the name of the OS disk
osDiskName=$(az vm show --resource-group $sourceResourceGroup --name $vmName \
    --query 'storageProfile.osDisk.name' --output tsv)

# Verify the terms for your market virtual machine
az vm image terms show --offer $offer --plan $plan --publisher $publisher \
    --subscription $sourceSubscription

# Deallocate the virtual machine
az vm deallocate --resource-group $sourceResourceGroup --name $vmName

# Create a snapshot of the OS disk.
az snapshot create --resource-group $sourceResourceGroup --name MigrationSnapshot \
    --source "/subscriptions/$sourceSubscription/resourceGroups/$sourceResourceGroup/providers/Microsoft.Compute/disks/$osDiskName"

# Move the snapshot to your destination resource group
az resource move --destination-group $destinationResourceGroup \
    --destination-subscription-id $destinationSubscription \
    --ids "/subscriptions/$sourceSubscription/resourceGroups/$sourceResourceGroup/providers/Microsoft.Compute/snapshots/MigrationSnapshot"

# Set your subscription to the destination value
az account set --subscription $destinationSubscription

# Accept the terms from the Marketplace
az vm image terms accept --offer $offer --plan $plan --publisher $publisher \
    --subscription $destinationSubscription

# create disk from the snapshot 
az disk create --resource-group $destinationResourceGroup --name DestinationDisk \
    --source "/subscriptions/$destinationSubscription/resourceGroups/$destinationResourceGroup/providers/Microsoft.Compute/snapshots/MigrationSnapshot" \
    --os-type $osType

# create virtual machine from disk
az vm create --resource-group $destinationResourceGroup --name $vmName  --attach-os-disk "/subscriptions/$destinationSubscription/resourceGroups/$destinationResourceGroup/providers/Microsoft.Compute/disks/DestinationDisk" --os-type $osType --plan-product $offer --plan-publisher $publisher --plan-name $plan
******************************

CCing @cynthn  and @TimShererWithAquent

**Comment by yungezz** [comment]
hi @qwordy could you pls help? thanks

**Comment by qwordy** [comment]
I will open an investigation into this issue.

**Comment by qwordy** [comment]
@dbradish-microsoft You created a VM and then created it again, so it is treated as update operation. Please delete the VM and run correct command at the first time.
