### ISSUE TITLE
Install AZ CLI on Windows without Administrator permissions

### ISSUE THREAD

**Issue by golaat** [Azure/azure-cli#16787]
Currently the AZ CLI Windows MSI installation requires local administrator permissions to install the product, update it or to add extensions. The default installation directory is to Program Files and does not seem to be over-ridable.

Can the MSI installation be adjusted so that the product is installable into %LOCALAPPDATA%\Programs, which would eliminate the need for administrative permissions and allow the end user to update the product as well as install extensions. Many other products such as Visual Studio Code, GIT, Storage Explorer etc support installation into the user program folder.

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to look at it? thanks

**Comment by BaibhavVishal123** [comment]
Not sure, this will help you or not. Did not help me though. ```https://github.com/Azure/azure-cli/issues/15381```. Works by installing python, pip -> az-cli. However, I still  had the same issue of admin access in employer provided system.

**Comment by nrdev88** [comment]
Same as #15381
