### ISSUE TITLE
WebApp:Azure Webapp Authentication / Authorization for Azure active directory management mode parameter are missing 

### ISSUE THREAD

**Issue by saswatmohanty01** [Azure/azure-cli#16789]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Azure Webapp Authentication / Authorization for Azure active directory management mode parameter are missing . There is no parameter from az cli or powershell to configure Azure App services Authentication providers with Azure active directory and then choose management mode to Express or Advanced.  **

az webapp auth update is missing parameter to change /set  Active directory authentication ----Management mode---Off/Express/Advanced . From Azure portal it is possible but there is no way to configure it using az cli or PowerShell, which is big problem during automation.  
**To Reproduce**

Create new App service 
Configure Authentication / Authorization 
Select App service Authentication to ON
Select Log in with Azure Active Directory from Action to take when request is not authenticated 
Select Azure Active Directory 
Select Management mode to Express 

from azure cli : **az webapp auth update**    https://docs.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest

reference issue : https://github.com/Azure/azure-cli/issues/14912

**Expected behavior**

az cli / powershell should have parameter to configure management mode to Express / Advanced / Off for Web app 
**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
webapp

**Comment by Kotasudhakarreddy** [comment]
Thanks for your feedback. Will check and consider for future release based on priority.

**Comment by panchagnula** [comment]
@Hamster-Huey FYI.

**Comment by Hamster-Huey** [comment]
@saswatmohanty01 Management Mode is/was a portal experience feature related to deciding how you would set up your app registration. The auth CLI command group does not set up your AAD app registration for you. That being said, one could consider the entire set of auth CLI to be "Advanced". 

If I'm misunderstanding, could you please share the specific auth configuration from the authsettings json schema that you wish to modify via cli?

**Comment by seligj95** [comment]
@saswatmohanty01 - please review the above response and asks

**Comment by seligj95** [comment]
Closing due to no response. Please re-open if there is any additional feedback.
