### ISSUE TITLE
routing condtion parameter with trailing ) is removed

### ISSUE THREAD

**Issue by JardarM** [Azure/azure-cli#16786]
**Describe the bug**
When running the az iot hub route create command with the condition option with a trailing ')' the last parenthesis is removed.

**To Reproduce**
`az iot hub route create --hub-name $az_hub --endpoint-name $az_sb_t_state --route Test --source twinchangeevents -c 'IS_OBJECT($twin.properties.reported.state)'`
Fails with this error:
```
BadRequestError: Invalid Routing Condition, RouteName:Test, ErrorMessage:Message:Syntax error., Location <start>:1:42, <end>:1:43, Severity:Error 
. If you contact a support representative please include this correlation identifier: baf6e38e-7c5d-4556-9e69-24547f63bc4d, timestamp: 2021-02-03 14:38:00Z, errorcode: IH400104.

```
This works however (not added space in condition statement):
`az iot hub route create --hub-name $az_hub --endpoint-name $az_sb_t_state --route Test --source twinchangeevents -c 'IS_OBJECT($twin.properties.reported.state) '`

**Expected behavior**
Should create a routing with this condition string:
IS_OBJECT($twin.properties.reported.state)

**CLI Version**
azure-cli                         2.18.0
core                              2.18.0
telemetry                          1.0.6
Extensions:
application-insights              0.1.11
azure-cli-iot-ext                 0.8.10
interactive                        0.4.4

**Comment by yonzhan** [comment]
iot

**Comment by vilit1** [comment]
Closing the issue due to no response. If you still need help with this issue, please re-open.
