### ISSUE TITLE
Azure CLI output is corrupted!

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#16798]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

It is not a valid JSON string. `Finished` appears in final output.

```
~$ az vm run-command invoke -g fy -n vm1 --command-id RunShellScript --scripts 'echo $1 $2' --parameters hello world
{- Finished ..
  "value": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Enable succeeded: \n[stdout]\nhello world\n\n[stderr]\n",
      "time": null
    }
  ]
}
```

**To Reproduce**

**Expected behavior**

**Environment summary**

WSL Ubuntu 20.04 LTS

**Additional context**

**Comment by yonzhan** [comment]
Compute

**Comment by yonzhan** [comment]
@Juliehzl was this issue related to Storage or Compute?

**Comment by qwordy** [comment]
> 
> 
> @Juliehzl was this issue related to Storage or Compute?

It is related to progress bar

**Comment by Juliehzl** [comment]
@qwordy I haven't checked in progress bar related code, so I am not sure how you get such output.
In addition, in my progress bar test, I cannot see your issue, either.

Could you provide more information to help figure out why you get the issue?

**Comment by jongio** [comment]
I ran into this issue today as well with this command:

`dotnetcore-sqldb-tutorial$ az sql server create --name dotnetcore-sqldb-tutorial-sql1 --resource-group dotnetcore-sqldb-tutorial-rg --location "westus2" --admin-user jonbgallant --admin-password asdfasdf`

```json
{/ Finished ..
  "administratorLogin": "jonbgallant",
  "administratorLoginPassword": null,
  "fullyQualifiedDomainName": "dotnetcore-sqldb-tutorial-sql1.database.windows.net",
  "id": "/subscriptions//resourceGroups/dotnetcore-sqldb-tutorial-rg/providers/Microsoft.Sql/servers/dotnetcore-sqldb-tutorial-sql1",
  "identity": null,
  "kind": "v12.0",
  "location": "westus2",
  "minimalTlsVersion": null,
  "name": "dotnetcore-sqldb-tutorial-sql1",
  "privateEndpointConnections": [],
  "publicNetworkAccess": "Enabled",
  "resourceGroup": "dotnetcore-sqldb-tutorial-rg",
  "state": "Ready",
  "tags": null,
  "type": "Microsoft.Sql/servers",
  "version": "12.0"
}
```


```json
dotnetcore-sqldb-tutorial$ az version
{
  "azure-cli": "2.22.1",
  "azure-cli-core": "2.22.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.18.0",
    "fzf": "1.0.2",
    "imds": "0.1.0",
    "noelbundick": "0.0.17"
  }
}
```

WSL2/Ubuntu 20

ddcc1

**Comment by Juliehzl** [comment]
Thanks for feedback. I will investigate the issue soon and plan in S187.
