### ISSUE TITLE
[VM] Allow enabling IP forwarding upon VM creation

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1679]
This is potentially a somewhat advanced scenario, but it would be cool if the `az vm create` command allowed enabling IP forwarding on the NIC that it creates (if it creates one). That way, you didn't need to create the VM, find the ID of the auto-created NIC, and then run `az network nic update` to enable IP forwarding.

**Comment by johanste** [comment]
One alternative for advanced scenarios is to create the NIC first and then reference that in your VM create. Would that be less of a hassle?

**Comment by lostintangent** [comment]
@johanste That's actually what I'm doing now. It's a totally fine solution, but it would "feel" a little nicer to just be able to take advantage of the `az vm create` command, instead of needing to drop down to manual NIC provisioning for this.

I also ran into #1659 when going the NIC + VM route, so it would be cool to address that, but ideally, I would much prefer to not need to manually create the NIC.

**Comment by johanste** [comment]
We'll take a look and see how one could fold this functionality into the `az vm create`. My meta concern is that the number of parameters that the command accepts end up making the simpler/more common create patterns hidden in the noise.

**Comment by lostintangent** [comment]
Totally understood! Thanks for the consideration.

**Comment by lostintangent** [comment]
Now that the parameters for the `vm create` command are categorized, I wonder whether it would be less disruptive to add this option, since it could be placed in the context of the `Network arguments` section. That group of flags is already effectively an face over the underlying NIC resource, so it would be great to not need to manually manage the NIC in order to enable IP forwarding.

**Comment by yugangw-msft** [comment]
We can revisit when we have more user voices on this
