### ISSUE TITLE
New CLI command for install patches API

### ISSUE THREAD

**Issue by rane-rajasi** [Azure/azure-cli#16790]
**Resource Provider**
Compute

**Description of Feature or Work Requested**
We need a new command for installPatches API, which is used to maintain security compliance on azure VMs

Command: az vm install-patches -g rg -n vm

Other input parameters as mentioned below:
NOTE: some parameters vary depending on the VM OS Type (i.e. Windows or Linux)

- maximumDuration (Required for both Windows and Linux VMs)
    Specifies the maximum amount of time that the operation will run. It must be an ISO 8601-compliant duration string such as PT4H (4 hours)

- rebootSetting (Required for both Windows and Linux VMs)
    Defines when it is acceptable to reboot a VM during a software update operation.
    Possible values are:
    
      - IfRequired
      - Never
      - Always

- classificationsToInclude (Optional for both Windows and Linux VMs however the possible values vary)
    The update classifications to select when installing patches. Possible values differ for Windows and Linux.

    Possible values for Windows VM:
      - Critical
      - Security
      - UpdateRollUp
      - FeaturePack
      - ServicePack
      - Definition
      - Tools
      - Updates
    
    Possible values for Linux VM:
      - Critical
      - Security
      - Other

- kbNumbersToInclude (Applicable to Windows VM only and is an **optional** parameter)
  KBs to include in the patch operation.

- kbNumbersToExclude (Applicable to Windows VM only and is an **optional** parameter)
  KBs to exclude in the patch operation.

- excludeKBsRequiringReboot (Applicable to Windows VM only and is an **optional** parameter)
  Filters out KBs that don't have a reboot behavior of 'NeverReboots' when this is set.

- packageNameMasksToInclude (Applicable to Linux VM only and is an **optional** parameter)
  Packages to include in the patch operation. Format: packageName_packageVersion.

- packageNameMasksToExclude (Applicable to Linux VM only and is an **optional** parameter)
  Packages to exclude in the patch operation. Format: packageName_packageVersion.

**Minimum API Version Required**
2020-12-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/compute-2020-12/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json#L4038

**Target Date**
March 1st Public Preview (Ignite)

**Comment by qwordy** [comment]
2020-12-01 is not released yet. We have accumulated so many features that depend on it. March 1st, not a realistic time.

**Comment by rane-rajasi** [comment]
@qwordy Any updates on when this will be picked up?

**Comment by qwordy** [comment]
@rane-rajasi Added to S185
