### ISSUE TITLE
passing json to --policy does not work. Azure documentation on this is very poor.

### ISSUE THREAD

**Issue by pmaslej** [Azure/azure-cli#16802]
## Describe the bug

**Command Name**
`az backup policy create`

**Errors:**
```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
Temp\pip-unpacked-wheel-pwfpui04\knack\cli.py, ln 233, in invoke
cli\core\commands\__init__.py, ln 659, in execute
cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
cli\core\commands\__init__.py, ln 715, in _run_job
Local\Temp\pip-unpacked-wheel-s5x_2dzp\six.py, ln 703, in reraise
cli\core\commands\__init__.py, ln 693, in _run_job
cli\core\commands\__init__.py, ln 330, in __call__
azure\cli\core\__init__.py, ln 786, in default_command_handler
...
cli\command_modules\backup\custom_help.py, ln 298, in get_or_read_json
json\__init__.py, ln 299, in load
json\__init__.py, ln 354, in loads
json\decoder.py, ln 339, in decode
json\decoder.py, ln 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup policy create --policy {} --resource-group {} --vault-name {} --name {} --backup-management-type {}`

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.18.0

```

**Comment by yonzhan** [comment]
backup

**Comment by pmaslej** [comment]
Seems to work using CLI Shell via portal. I was using WIN10 Powershell CLI and most probably environment was missing some python modules or so. 


{
  "azure-cli": "2.18.0",
  "azure-cli-core": "2.18.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
