### ISSUE TITLE
WebApp:'az webapp config access-restriction add' fails when webapp has a pre-existing ServiceTag rule

### ISSUE THREAD

**Issue by rodney-almeida** [Azure/azure-cli#16809]
## Describe the bug
When using `az webapp config access-restriction add` to add additional rules to a webapp that already have a rule with a ServiceTag, the command fails

**Command Name**
`az webapp config access-restriction add`

**Errors:**
```
'ServiceTag' is not valid value for enum <enum 'IpFilterTag'>
Traceback (most recent call last):
Temp\pip-unpacked-wheel-tv8yhkg2\msrest\serialization.py, ln 987, in serialize_enum
enum.py, ln 293, in __call__
enum.py, ln 535, in __new__
enum.py, ln 548, in _missing_
ValueError: 'ServiceTag' is not a valid IpFilterTag

...

Temp\pip-unpacked-wheel-tv8yhkg2\msrest\serialization.py, ln 771, in serialize_data
Temp\pip-unpacked-wheel-tv8yhkg2\msrest\serialization.py, ln 994, in serialize_enum
msrest.exceptions.SerializationError: 'ServiceTag' is not valid value for enum <enum 'IpFilterTag'>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a WebApp and add an access restriction rule with a Service Tag. Im my case, we have an "allow frontdoor" rule using the service tag of AzureFrontDoor.Backend
- Then try and create any additional rules with `az webapp config access-restriction add -g {} -n {} --rule-name {} --priority {} --action {} --ip-address {} --subscription {}`

## Expected Behavior
Add the additional rule

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.18.0

Extensions:
azure-devops 0.18.0
front-door 1.0.11

```

**Comment by yonzhan** [comment]
webapp

**Comment by Kotasudhakarreddy** [comment]
Looking in to this issue.

**Comment by andre-r-magalhaes** [comment]
Hi, we're having the same error but with another command. 

az webapp traffic-routing set --distribution StageName=100 --name WebApp --resource-group ResourceGroup

The issue is related?

**Comment by Kotasudhakarreddy** [comment]
@andre-r-magalhaes - Issue is logged for `ServiceTag` rule. you too using this rule?

**Comment by Kotasudhakarreddy** [comment]
@rodney-almeida - could you please share the `--debug` log for further investigation.

**Comment by panchagnula** [comment]
@madsd might probably be fixed when we have the new SDK in CLI?

**Comment by madsd** [comment]
@panchagnula yes, this cannot be fixed before we have the new SDK. Until then - if you use service tag rules, you will have to manage from ARM/REST, portal or PowerShell...

**Comment by Pangamma** [comment]
I am also having this same issue.

**Comment by madsd** [comment]
@Pangamma Official release of the next CLI version containing the fix is 6. May (2.23)
