### ISSUE TITLE
keyvault "SET" to  include contentType

### ISSUE THREAD

**Issue by SenseiJoe** [Azure/azure-cli#16804]
Since I can't rename a keyvault I was transferring one to another and found that I could not set the contentType, I can get it but not set it in the new vault.

**Comment by yungezz** [comment]
hi @houk-ms could you pls help to check?

**Comment by SenseiJoe** [comment]
Yes, id there a new version?

**Comment by BigCat20196** [comment]
Hi @SenseiJoe,  is this still bothering you? If so, please let us know the version of Azure-CLI you are currently using, and we will verify and fix this issue as soon as possible.

**Comment by yungezz** [comment]
will close the issue for now since no response. Feel free to create new issue if any other queries. thanks.

**Comment by SenseiJoe** [comment]
Sorry, this shouldn't be closed.  Using v2.22.1, there is no ability to set contentType of a new key.

This is the help for the command, no "contentType"
Examples
    Create a secret (if one doesn't exist) or update a secret in a KeyVault.
        az keyvault secret set --name MySecretName --vault-name MyKeyVault --value MyVault

Why isn't there an option for the property?
maybe:
        az keyvault secret set --name MySecretName --vault-name MyKeyVault --value MyVault -contentType MyType
