### ISSUE TITLE
SAS token generation on Linux CLI

### ISSUE THREAD

**Issue by YankoSolanoS** [Azure/azure-cli#16806]
It takes more than a second(s) and we expect it to take less than a second. We are passing in the key so we specifically believe the method itself to be slow. This has become an issue for us because we create hundreds of SaS on files at a time and it is taking too long.  I have two questions:

1)	Is our expectations on duration correct or do we need to manage it?

2)	What steps would we do to troubleshoot this issue?

The code passes in the necessary parameters for SaS. The parameters then goes through some conditional statements to check what parameters were passed (example if an IP address is given or not). The appropriate SaS is generated based off these parameters. In terms of troubleshooting, we already has timers around the code that generates the results. Results below:

root@qiti-StdLab-VM:~/python# time python3  test.py -a vnew -s experimental -p "thisisatest/testfile.txt" -r cdrw  -t file 1> /dev/null 2>> /tmp/times.txt

real    0m1.465s
user    0m1.354s
sys     0m0.105s
root@qiti-StdLab-VM:~/python# time python3  test_sdk.py  1> /dev/null

real    0m0.532s
user    0m0.476s
sys     0m0.054s

The only thing I could think of was to do the timers specifically around the sub process that actually does the the az command.

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Replied in e-mail and close it here.
To see CLI command execution time, you could add `--debug` in your command and you could see the time as below:
![image](https://user-images.githubusercontent.com/49508232/107169540-15e47900-69f9-11eb-951c-880c1dff6917.png)
