### ISSUE TITLE
[Service Team Request] Adding subnet ID and IP address as eligible input for load balancer backend pool commands

### ISSUE THREAD

**Issue by erichrt** [Azure/azure-cli#16808]
**Resource Provider**

Networking

**Description of Feature or Work Requested**
We have added subnet ID and IP address as a way to specify backend address when creating or updating an IP-based backend pool of a load balancer. This is related to this feature: https://github.com/Azure/azure-cli/issues/12937 however, we will start allowing customers to specify by subnet ID in place of vnet ID. 

**Minimum API Version Required**

2020-11-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/tree/network-november-release/specification/network/resource-manager/Microsoft.Network/stable/2020-11-01

**Target Date**

3/15

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
@erichrt When will '2020-11-01' be merged into 'master' of main repo?
