### ISSUE TITLE
webapp:Missing GenerateRandomAppNames.json from installation needed by az webapp

### ISSUE THREAD

**Issue by vivaladan** [Azure/azure-cli#16803]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
[Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\lib\\site-packages\\azure\\cli\\command_modules\\appservice\\resources\\GenerateRandomAppNames.json'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-pwfpui04\knack\cli.py, ln 233, in invoke
cli\core\commands\__init__.py, ln 659, in execute
cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
cli\core\commands\__init__.py, ln 714, in _run_job
cli\command_modules\appservice\commands.py, ln 37, in _ex_handler
cli\core\commands\__init__.py, ln 693, in _run_job
cli\core\commands\__init__.py, ln 330, in __call__
...
azure\cli\core\util.py, ln 474, in get_file_json
azure\cli\core\util.py, ln 488, in read_file_content
codecs.py, ln 897, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\lib\\site-packages\\azure\\cli\\command_modules\\appservice\\resources\\GenerateRandomAppNames.json'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Running this command on local terminal.
- `az webapp up`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.18.0

```
## Additional Context

Installed directory exists and contains files, just not the one it's looking for.
Have rerun the CLI installer and clicked repair, but the mystery file hasn't appeared.

![image](https://user-images.githubusercontent.com/1514212/106920318-e1c03e00-6702-11eb-827b-8ebc7aacf3b6.png)

**Comment by yonzhan** [comment]
webapp

**Comment by calvinsID** [comment]
Unable to repro on a fresh MSI installation, but I see this on cloudshell..

**Comment by vivaladan** [comment]
I tried an uninstall and fresh install of MSI. But the file didn't turn up

**Comment by calvinsID** [comment]
Hi @qwordy, @Juliehzl wondering if you can provide any guidance, I can't repro on my machine but can repro on cloudshell. The file seems to exist in v2.18 source code here https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.18.0

**Comment by geekyarthurs** [comment]
Temporary Fix:

`wget https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/resources/GenerateRandomAppNames.json`

in the mentioned directory.

**Comment by panchagnula** [comment]
@calvinsID do we know if this is still an issue - did we get any help from core-cli here?

**Comment by qwordy** [comment]
I confirm this file is in git repository. Cloud shell is using deb file we provide to install Azure CLI. @fengzhou-msft Do you know how json files are packaged?
