### ISSUE TITLE
[Question] Recommended way to get a raw string value from a custom query

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1681]
Since the JSON output type will return quoted value strings (e.g. `"foo"` instead of `foo`), what is the recommended solution for getting the raw/unquoted value of a string that is returned from using a custom `--query` flag? Using `-otsv` seems to work, but feels kind of "hacky" (?), and obviously piping JSON output to `jq -r` would work, but seems strange to need to use JQ strictly to remove the quotes from a string. 

Maybe `-otsv` is the right solution, and I'm just hung up on the name. Is the `tsv` output expected to be the "raw" format for scalar values? Is there a way to achieve this behavior via JMESPath? I looked at the spec but couldn't find anything. Either way, I'd love to hear what the recommended solution is for this, since I'm probably missing something.

<img width="906" alt="screen shot 2017-01-07 at 7 51 28 pm" src="https://cloud.githubusercontent.com/assets/116461/21747149/bba3b3a4-d512-11e6-8b2b-001b0ffb17ee.png">

**Comment by valencik** [comment]
I ran into exactly this issue last night and ended up replacing the whole query with `jq` (thankfully they're the same syntax):

```bash
vm_ip_json=$(az vm list-ip-addresses \
    --name "$name" \
    --resource-group capturetest)

vm_ip=$(jq --raw-output \
    '.[0].virtualMachine.network.publicIpAddresses[0].ipAddress' \
    <<<"$vm_ip_json")
```

Nice to know you can combine the `--query` and `-otsv` though.

**Comment by lostintangent** [comment]
@valencik Yeah that's definitely another solution, but I was curious how to achieve this without needing to rely on `jq` at all, since the `--query` option (and `-ojsonc`) for the AZ CLI provides most of what I typically need.

**Comment by johanste** [comment]
@lostintangent, using `--out tsv` is indeed intended way to get "raw" string data. If the collective community can come up with a better name, I'd be more than happy to make the change to support it. 

The argument against "raw" was the possible confusion between "don't touch the data that I received from Azure" (which would imply json since that is what is on the wire) and the "don't quote strings" that you are expecting here...

**Comment by lostintangent** [comment]
@johanste Sounds good. I'm cool with `-otsv`, I just wanted the confirmation that this was the correct solution here. Thanks so much!
