### ISSUE TITLE
az backup protection backup-now does not work for NFS volumes

### ISSUE THREAD

**Issue by pmaslej** [Azure/azure-cli#16817]
## Describe the bug
Triggering ondemand backup for NFS File shares always end up with an internal Microsoft error. Reoccurring for weeks.

![image](https://user-images.githubusercontent.com/46818397/107039977-e3e7d280-67be-11eb-9aae-8637413eed74.png)

Same is valid for portal way

![image](https://user-images.githubusercontent.com/46818397/107040236-3c1ed480-67bf-11eb-8aeb-873cd97a20b3.png)

**Command Name**
`az backup protection backup-now`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup protection backup-now --vault-name {} --resource-group {} --container-name {} --item-name {} --backup-management-type {} --retain-until {} --output {}`

## Environment Summary
```
Linux-4.15.0-1106-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.18.0
azure-cli-ml 1.20.0

Extensions:
ai-examples 0.2.5
azure-cli-ml 1.20.0

```

**Comment by yonzhan** [comment]
backup

**Comment by pvrk** [comment]
@mepand to comment on NFS based file-shares. I think we don't have support for that yet but I will let @mepand  have the final word.

**Comment by mepand** [comment]
@pmaslej Apologies for the inconvenience . NFS shares are currently not supported by Azure Backup. Yes we do have plans of supporting it in the future but in the interim, we are working on service side fix that would ensure that error message is more clear and apt.  I will also update support matrix to call out clearly that NFS shares are not supported.

**Comment by mepand** [comment]
Support matrix has been updated. Service side fix would be rolled out by end of March . Since there is no further action pending on the PG side, closing this issue. Please feel free to reach out incase of any other issue or concern.
