### ISSUE TITLE
Bug: Please  allow for setting up email for az vm auto-shutdown.

### ISSUE THREAD

**Issue by sanjaydatasciencedojo** [Azure/azure-cli#16824]
This does not create an email for foo@bar.com.

az vm auto-shutdown -g MyResourceGroup -n MyVm --time 1730 --email "foo@bar.com" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/vm.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @qwordy could you pls help to  have a look? thanks

**Comment by qwordy** [comment]
@sanjaydatasciencedojo Can you add `--debug`?

**Comment by sanjaydatasciencedojo** [comment]
This is  my log.
```
{
  "createdDate": "2021-02-08T22:19:11.098288+00:00",
  "dailyRecurrence": {
    "time": "1630"
  },
  "hourlyRecurrence": null,
  "id": "/subscriptions/daa06d72-2245-4e5c-b0fb-3294990933a9/resourcegroups/rg-jitsi/providers/microsoft.devtestlab/schedules/shutdown-computevm-vmsouthcentralusjitsiinstance001",
  "location": "southcentralus",
  "name": "shutdown-computevm-vmsouthcentralusjitsiinstance001",
  "notificationSettings": {
    "emailRecipient": null,
    "notificationLocale": null,
    "status": "Disabled",
    "timeInMinutes": 0,
    "webhookUrl": null
  },
  "provisioningState": "Succeeded",
  "resourceGroup": "rg-jitsi",
  "status": "Enabled",
  "tags": null,
  "targetResourceId": "/subscriptions/daa06d72-2245-4e5c-b0fb-3294990933a9/resourceGroups/rg-jitsi/providers/Microsoft.Compute/virtualMachines/vmsouthcentralusjitsiinstance001",
  "taskType": "ComputeVmShutdownTask",
  "timeZoneId": "UTC",
  "type": "microsoft.devtestlab/schedules",
  "uniqueIdentifier": "d5f41124-97d8-416c-8c65-9913f795a753",
  "weeklyRecurrence": null
}

```

**Comment by BigCat20196** [comment]
Hi @sanjaydatasciencedojo ,I found the "-- webhook" parameter missing in your input command. After my test, this is the main reason for your issue. Please add this parameter according to the example and try again.

eg:
az vm auto-shutdown -g MyResourceGroup -n MyVm --time 1730 --email "foo@bar.com" --webhook "https://example.com/"

**Comment by sanjaydatasciencedojo** [comment]
@BigCat20196 What value should I use for webhook? Should not email and webhook be decoupled?
