### ISSUE TITLE
az login sends me to localhost url

### ISSUE THREAD

**Issue by williamohara** [Azure/azure-cli#16823]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When I log in using az login - it opens a browser to select my account then it leads to a a link that is trying to open on localhost:8400. 

**To Reproduce**
1. Download the most recent version of az cli on a fully up to date windows 10 machine (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli - choosing the "non-beta") 
2. After install, start PowerShell in admin mode 
3. enter az login
4. Pick the Microsoft account you wish to use to log into MS azure (i have three accounts to choose from)
5. browser then redirects to a page with the following url structure 

``
https://localhost:8400/?code=...&state=...&session_state=...
``
I have a feeling that the localhost:8400 is supposed to really be a login.microsoft.com url
![localhostlogin](https://user-images.githubusercontent.com/17223014/107125054-59ee4700-685c-11eb-8e42-8761843e86e6.jpg)

**Expected behavior**
I expect to be put into a flow where I can enter my password and 2fa

**Environment summary**
Install method - downloaded azure-cli-2.18.0.msi and installed

**Additional context**
I tried logging in by using the -u and -p parameters az login -u <redacted> -p <redacted> and i was able to log in

**Comment by yonzhan** [comment]
Account

**Comment by jiasli** [comment]
Redirecting to `http://localhost` is the standard process of [OAuth 2.0 authorization code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow).

If your browser forces `https` on `localhost`, please see #10426.

**Comment by daniel-l-higgs** [comment]
This happens to me when I'm using vscode on a remotely connected compute instance on AzureML. I try to run some python code which connects to the AzureML workspace and my local browser pops up asking to authenticate, even though the python is executing on the remote machine.

**Comment by jan-molemans** [comment]
@daniel-l-higgs I have the same issue, also in Azure ML, did you manage to find a solution for it?
