### ISSUE TITLE
azure-cli-ml: AttributeError("'NoneType' object has no attribute 'lower'") when trying to deploying 

### ISSUE THREAD

**Issue by IndianBoy42** [Azure/azure-cli#16821]
(Cross-posting from azure-cli-extensions https://github.com/Azure/azure-cli-extensions/issues/2979)

## Describe the bug

When trying to deploy a model locally with azure-ml I get this error (`"'NoneType' object has no attribute 'lower'"`) no matter what.

Some time ago it worked for a few minutes but has since gone back to not working

I have tried to reinstall azure-cli and azure-cli-ml.

**Command Name**
`az ml model deploy
Extension Name: azure-cli-ml. Version: 1.21.0.`

**Errors:**
```
{'Azure-cli-ml Version': '1.21.0', 'Error': AttributeError("'NoneType' object has no attribute 'lower'")}
```

Full output:
```
Found the config file in: [redacted]/.azureml/config.json
{'Azure-cli-ml Version': '1.21.0', 'Error': AttributeError("'NoneType' object has no attribute 'lower'")}
Command ran in 0.816 seconds (init: 0.046, invoke: 0.770)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ml model deploy -m {} --ic {} --dc {} -n {} --verbose --overwrite`

My inference config:
```
{
    "entryScript": "dummy.py",
    "sourceDirectory": "yolov5"
}
```

My deployment config
```
{
    "computeType": "local",
    "port": 32267
}
```

dummy.py
```
def init():
    pass
def run(data):
    print(data)
```

## Expected Behavior

It deploys the model locally

## Environment Summary
```
Linux-5.8.0-7630-generic-x86_64-with-glibc2.10
Python 3.8.5
Installer: 

azure-cli 2.18.0
azure-cli-ml 1.21.0

Extensions:
azure-cli-ml 1.21.0

```

**Comment by yonzhan** [comment]
ml

**Comment by frcai** [comment]
You can try specify runtime or environment in inference config.

1) "runtime": "python"
2) refer to sample "environment" at
https://docs.microsoft.com/en-us/azure/machine-learning/reference-azure-machine-learning-cli#inference-configuration-schema

**Comment by shivanissambare** [comment]
Hi, please let us know if above comment solved your issue.

**Comment by shivanissambare** [comment]
#please-close
