### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by VidithAgarwal** [Azure/azure-cli#16822]
After installing azure CLI on Azure IOT Edge terminal
Using az command leads to the following error:

/usr/bin/az: line 2: /opt/az/bin/python3: cannot execute binary file: Exec format error

**Comment by yungezz** [comment]
should be caused by arch. @VidithAgarwal could you pls share more aobut the `Azure IOT Edge Terminal`? @fengzhou-msft to help confirm.

**Comment by fengzhou-msft** [comment]
Our installer packages do not support ARM64 yet. Please try `az` installed with `pip install azure-cli` and let us know if it works.

**Comment by OrrinEdenfield** [comment]
Thank you for the guidance @fengzhou-msft. Looks like `pip3 install azure-cli` is working for me.

**Comment by marianpetruk** [comment]
@fengzhou-msft is it already supported or not yet?

**Comment by jiasli** [comment]
> @fengzhou-msft Feng Zhou FTE is it already supported or not yet?

This is tracked by https://github.com/Azure/azure-cli/issues/7368.

**Comment by dustindortch** [comment]
> 

Maybe this should be added to the installation documentation.

**Comment by bebound** [comment]
@dustindortch  ARM64 support is added in #24180, we'll release official package later.
