### ISSUE TITLE
[Discussion] Allow creating/referencing an NSG as part of VNet creation

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1683]
I like that the `az network vnet create` command allows creating a default subnet, and I was curious whether it would be reasonable/valuable to also support creating (or referencing) an NSG as part of this command? That way, you could do something like this:

```shell
az network vnet create -g foo \
  -n foo-vnet \
  --subnet-name foo-subnet \
  --nsg-name foo-nsg
```

As opposed to:

```shell
az network vnet create -g foo \
  -n foo-vnet \
  --subnet-name foo-subnet

az network nsg create -g foo -n foo-nsg

az network vnet subnet update -g foo \
  -n foo-subnet \
  --vnet-name foo-vnet \
  --network-security-group foo-nsg
```

The addition of the new `--nsg-name` parameter of the `az network vnet create` command would effectively automate the last two commands in the second example. However, if the specified NSG already exists, it would simply automated the third command, since it wouldn't need to create the NSG.  If the flag was omitted, than the existing behavior should continue (don't create or associate an NSG with the generated subnet).

The `az network vnet subnet create` command already allows referencing an existing NSG, so there's at least precedent for that behavior when creating new subnets. Even if the proposed `--nsg-name` parameter only allowed referencing an existing NSG, that would still be valuable.

**Comment by tjprescott** [comment]
We have not gotten additional customer asks for this feature and do not want to change vnet creation into an ARM-templated backed command, so I will close this.
