### ISSUE TITLE
WebApp:az cli update app setting command always making slotsetting to true

### ISSUE THREAD

**Issue by akshaychopra5207** [Azure/azure-cli#16838]
I am facing the same issue with az cli  2.16 version. Tried to upgrade it to 2.18 and still getting the same issue
az webapp config appsettings set -g dp-yamlcont-master -n dp-yamlcont-cont-test --slot staging  --settings @appSettings.json
The command above. always make the slot setting to true even if we define false in JSON

[

    {
        "name": "testNewApp" ,
        "value": "time",
        "slotsetting": "false"
    }
    ,
    {
        "name": "testNewApp1" ,
        "value": "time1",
        "slotsetting": "false"
    }
    ,
    {
        "name": "testNewApp2" ,
        "value": "time2",
        "slotsetting": "false"
    }
    ,
    {
        "name": "testNewApp3" ,
        "value": "time3",
        "slotsetting": "false"
    }
    ,
    {
        "name": "testNewApp2" ,
        "value": "@Microsoft.KeyVault(SecretUri=https://dpyamlcont.vault.azure.net/secrets/test1/f6d4d4f4dff74a689c29dfd180bc0740)",
        "slotsetting": "false"
    }
    ,
    {
        "name": "testNewApp3" ,
        "value": "@Microsoft.KeyVault(SecretUri=https://dpyamlcont.vault.azure.net/secrets/test2/2416121e38d74e7495f0d0fc2e3d9be6)",
        "slotsetting": "false"
    }
    ]

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@Kotasudhakarreddy can you take a look at this?

**Comment by Kotasudhakarreddy** [comment]
@akshaychopra5207 unable to repro this issue. I am able to see the given value(true/false) for `slot setting `. I could see the same in your output given above. All the values for `slot setting ` shows as `false`

**Comment by Kotasudhakarreddy** [comment]
closing this issue as unable to repro. Please reopen with `--debug` details if you still face it.

**Comment by Kotasudhakarreddy** [comment]
Issue is able to repro only when trying to override the existing settings. Will check further on this.

**Comment by Ahmad-Al-Ali** [comment]
Hey Guys, I was looking into this issue and would like to add my perspective on this.  as I understood from the command documentation, we should be specifying the "stickiness" of each app settings using the --slot-settings so the CLI command would become: 

`az webapp config appsettings set -g rgname-RG  -n appservicename --settings  @appSettings.json --slot-settings @StickySettings.json`

where the content of appSettings.json is a key value similar to:

`[
  {
    "name": "AppSetting1",
	"value": "test",
  },
  {
    "name": "AppSetting2",
	"value": "investigating issue",
  },
  {
    "name": "AppSetting3",
	"value": "Hey ! I need a solution"
  }
]`

and the content of StickySettings.json is a key value where the value is a Boolean that indicates wither the app setting is sticky or not. 
`[
  {
    "name": "AppSetting1",
	"value": true,
  },
  {
    "name": "AppSetting2",
	"value": false,
  },
  {
    "name": "AppSetting3",
	"value": true	
  }
]`

Unfortunately this didn't work as well.

**Comment by Ahmad-Al-Ali** [comment]
@Kotasudhakarreddy any update on this issue, is there an active investigation that is in progress?

**Comment by Kotasudhakarreddy** [comment]
@Ahmad-Al-Ali - yes we are working on it. Milestone has been set for this.
