### ISSUE TITLE
[Discussion] Could the help text for the VNet create command be a little clearer?

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1684]
Could the behavior of the `az network vnet create` command's `--subnet-prefix` parameter be clarified any further? It's help text states that it will reserve a portion of the vnet's address space, but in my experience, it seems to use the following specific heuristic: `<vnet-prefix>/max(24, <vnet-cidr-block>)`.

Maybe the behavior isn't this simple, but if it is, it would be cool if the help text stated this, that way a user would know exactly when they do or don't need to explicitly set it (e.g. `If omitted, automatically reserves a `/24` (or as large as available) block within the VNet address space, .`).

This isn't that high-pri, and maybe I'm just being nit-picky, but I had to try the `az network vnet create` command with and without the `--subnet-prefix` parameter in order to see how it worked.

**Comment by tjprescott** [comment]
You are absolutely correct--that's what it does. I'll update the help with your recommended wording. Thanks for the feedback!
