### ISSUE TITLE
[Network] Support Ipv6 address in ExpressRoute private peering 

### ISSUE THREAD

**Issue by amwate** [Azure/azure-cli#16848]
**Is your feature request related to a problem? Please describe.**

Support for Ipv6 Ip address(es) for Azure ExpressRoute Private Peering. 
The powershell support has been added in https://github.com/Azure/azure-powershell/pull/12324. 

swagger definition is here. 
https://github.com/Azure/azure-rest-api-specs/blob/3227f9795b09642afb975f40d45ed481192b43a2/specification/network/resource-manager/Microsoft.Network/stable/2020-08-01/expressRouteCircuit.json#L1855

**Describe the solution you'd like**

Similar to the powershell, az-cli should also allow the primary and secondary address prefixes to be of address family type Ipv6. 
Currently powershell relaxes the requirements of them to be Ipv4 or Ipv6, while an added parameter AddressPrefixType <Ipv4|Ipv6> is added. 

A similar structure from the az cli would also be consistent. Please evaluate if that fits with the remaining az cli functionality. 

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Network

**Comment by yonzhan** [comment]
This feature will be shipped today.
