### ISSUE TITLE
WebApp:CLI: Documentation and behaviour for "--slot-setting" in "storage-account" for webapp is unclear

### ISSUE THREAD

**Issue by haslo** [Azure/azure-cli#16854]
The documentation for the CLI for adding or updating `storage-account` just states that there is a parameter `--slot-setting` for a command like this:

```bash
az webapp config storage-account [...]
```

The full documentation for the parameter is as follows:

> `--slot-setting`
> 
> Slot setting.

It looks like **providing this parameter enables the "slot setting"** (of which I'm not certain what it does),  
while **omitting the parameter does _not_ disable the "slot setting"**.

So the documentation should provide the following pieces of information:

* How exactly do I use the parameter `--slot-setting`? It doesn't appear to take additional values like all the other parameters.
* What does "slot setting" do exactly in this context?
* Once enabled, how do I disable the "slot setting" again?

Also of interest would be:

* Is there a corresponding setting in the portal? (This is less relevant here since *the issue is with the CLI* - but this setting *doesn't* seem to be in the portal.)

Since in the case I tested it in, it looks to break slot swaps, I'd be particularly interested in how I disable this setting again now that I've enabled it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4892bb1c-5cb4-91fa-325b-f5180cd05c3a
* Version Independent ID: 8c9a9a0e-5b36-4039-72c5-b28fd0bb9fd4
* Content: [az webapp config storage-account](https://docs.microsoft.com/en-us/cli/azure/webapp/config/storage-account?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/storage-account.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config/storage-account.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by Kotasudhakarreddy** [comment]
@haslo - thanks for your feedback. We will update the documentation

**Comment by StrawnSC** [comment]
@haslo, I looked into this issue, and there appears to be a bug in the azure backend with how storage account slot settings are handled. Creating a storage account as a slot setting is supposed to make it "sticky" relative to that slot, meaning that when that slot is swapped, the storage account stays with that slot. The CLI should behave correctly when the backend issue is resolved

**Comment by haslo** [comment]
Thanks @StrawnSC for the explanation. That will solve how to remove the setting once it's set.

I do believe that the documentation should have some content similar to your explanation about what slot settings actually are as well though. It still only says "Slot setting." now, which doesn't explain anything.

**Comment by btardif** [comment]
Hey @gsethdev I think this is more of a BYOS issue than deployment. If I remember correctly this behavior changed recently so it might already be fix, can you take a look?

cc: @seligj95, @tulikac

**Comment by gsethdev** [comment]
We do support declaring BYOS custom storage as a slot-setting. With slot setting you can decide to make BYOS configuration sticky to a slot.
The document here explains the same https://learn.microsoft.com/en-us/azure/app-service/configure-connect-to-azure-storage?tabs=portal&pivots=container-linux#mount-storage-to-linux-container
