### ISSUE TITLE
IMPORTANT- VMSS CLI license-type not working for Linux VMSS (RHEL_BYOS, SLES_BYOS) - IMPORTANT

### ISSUE THREAD

**Issue by mathapli** [Azure/azure-cli#16859]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
while using license-type in create VMSS, we are getting error
az : ValidationError: usage error: --license-type is only applicable on Windows VM scaleset

**To Reproduce**
create a Linux RedHat vmss with license type RHEL_BYOS which should be allowed. It gives failure

**Expected behavior**
VMSS created with RHEL_BYOS licensetype

**Environment summary**
Production

**Additional context**
in documentation it mentions it is allowed so it is a bug
https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/62987682/107267784-5bdb2480-6a6d-11eb-9428-5b1a2cd86d00.png)

**Comment by yungezz** [comment]
hi @qwordy could you pls have alook?

**Comment by qwordy** [comment]
Will open an investigation.
