### ISSUE TITLE
Add PlatformImageFeatures to VMImage object in PIR Consumption GET API

### ISSUE THREAD

**Issue by grace-liang** [Azure/azure-cli#16863]
**Resource Provider**
Azure.Compute

**Description of Feature or Work Requested**

GET Consumption API docs: https://docs.microsoft.com/en-us/cli/azure/vm/image?view=azure-cli-latest#az_vm_image_show

Sample command:
`grace@Azure:~$ az vm image show --location EastUS2EUAP --publisher RedHat --offer RHEL --sku 8_3 --version 8.3.2020111905`

Sample current payload:
`{
  "automaticOsUpgradeProperties": {
    "automaticOsUpgradeSupported": false
  },
  "dataDiskImages": [],
  "disallowed": {
    "vmDiskType": "None"
  },
  "hyperVGeneration": "V1",
  "id": "/Subscriptions/97f78232-382b-46a7-8a72-964d692c4f3f/Providers/Microsoft.Compute/Locations/EastUS2EUAP/Publishers/RedHat/ArtifactTypes/VMImage/Offers/RHEL/Skus/8_3/Versions/8.3.2020111905",
  "location": "EastUS2EUAP",
  "name": "8.3.2020111905",
  "osDiskImage": {
    "operatingSystem": "Linux",
    "sizeInBytes": 68719477248,
    "sizeInGb": 64
  },
  "plan": null,
  "tags": null
}`

Work requested:
An optional list of objects named `features` can be returned, but can also be null or empty. The `features` array contains an arbitrary number of PlatformImageFeature objects with fields `name` and `value` which contains arbitrary string values. 

`public class PlatformImageFeature
    {
        public String name;
        public String value;
    }`

Example:
`"features": [
        {
          "name": "SecurityType",
          "value": "TrustedLaunchSupported"
        },
        {
          "name": "IsHibernateSupported",
          "value": "True"
        }
      ],`

Note: please do testing in canary regions- this array will not be returned in public regions until post public preview announcement.

**Minimum API Version Required**
Any. Work is not versioned.

**Swagger Link**
Swagger: https://github.com/Azure/azure-rest-api-specs/pull/12085
- currently checked in to compute-2020-12 branch, which will be merged with master shortly, if it hasn't already.

**Target Date**
Feb 26, 2021

**Comment by yungezz** [comment]
Swagger not in master yet.

**Comment by grace-liang** [comment]
Closing this request for now, please disregard. Will revisit soon.

**Comment by grace-liang** [comment]
Reopening. Swagger was merged to master in this PR: https://github.com/Azure/azure-rest-api-specs/pull/12334
@qwordy please have a look when you get a chance.

**Comment by qwordy** [comment]
OK

**Comment by qwordy** [comment]
@grace-liang It is supported now.
When I run 
```
az vm image show --location EastUS2EUAP --publisher RedHat --offer RHEL --sku 8_3 --version 8.3.2020111905
```
I get
```
"features": null
```
Can you give a image that has features?

**Comment by grace-liang** [comment]
Sorry about that @qwordy.

Please use 
`az vm image show --location EastUS2EUAP --publisher RedHat --offer RHEL --sku 83-gen2 --version 8.3.2020111907`

which should return 
`"features": [
            {
                "name": "SecurityType",
                "value": "TrustedLaunchSupported"
            }
        ],`

**Comment by qwordy** [comment]
Thanks, @grace-liang. I test it in Azure CLI 2.20.0. It works as expected. Close this issue now.
