### ISSUE TITLE
az monitor metrics alert create command breaks in latest cli release 2.18.0

### ISSUE THREAD

**Issue by spatialman** [Azure/azure-cli#16867]
Describe the bug
"az monitor metrics alert create" CLI command breaks in the latest cli release of 2.18.0
when we execute the command by passing a scope as resource ID, the command is throwing an exception as "BadRequestError: The following resources were not found under the region global" which was working fine until last cli release.

To Reproduce
Create a Alert using Azure CLI
az monitor metrics alert create -g "rg-xyz" -n alert1 --subscription "sub-xyz" --scopes /subscriptions/sub-xyz/resourceGroups/rg-xyz/providers/Microsoft.Storage/storageAccounts/sta001xyz --condition "total transactions > 5 where ResponseType includes Success" --description "Storage Slow Transactions"
It fails with error message "BadRequestError: The following resources were not found under the region global"

Expected behavior
Should have created an alert with out any error message.

Environment summary
Shell Type - bash
Bash on windows 10
CLI Version - latest (2.18.0)

Additional context
Could you provide sample alert cli command to achieve this..in latest release version (cli 2.18.0)

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
It's fixed in version 2.19.0 which will be released today.

**Comment by spatialman** [comment]
Good to know, looking forward on the release.

**Comment by kairu-ms** [comment]
> Good to know, looking forward on the release.

It’s ready now. Please try following command to update CLI: az upgrade

**Comment by spatialman** [comment]
Cool, that made the day.. Thanks a lot for fix.
