### ISSUE TITLE
Improve dev-machine build document.

### ISSUE THREAD

**Issue by Tatsinnit** [Azure/azure-cli#16882]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

This is just a placeholder from the struggle I had with the dev-machine set-up, I am really hoping to get clearer docs and happy to contribute to this repository that way, intent is to just open an issue but to possibly unblock myself with dev machine set-up at least in mac-OSX 

**Describe the bug**

Following steps here: https://github.com/Azure/azure-cli/blob/dev/doc/configuring_your_machine.md  or possibly outdated information: https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#heading_author_command_mod 

currently after updating bunch of the `pip` I am getting this error:

![image](https://user-images.githubusercontent.com/6233295/107446073-8da1d780-6ba2-11eb-9782-43ffe3bde09c.png)

**To Reproduce**

* follow the instructions here: https://github.com/Azure/azure-cli/blob/dev/doc/configuring_your_machine.md 

**Expected behavior**

* I was hoping `az` will get me started.

**Environment summary**

![image](https://user-images.githubusercontent.com/6233295/107446675-c9896c80-6ba3-11eb-9f1d-c26ce69324e2.png)

**Additional context**

I am fairly chill to jump on a call and possibly get guidance.  

Thank you so much in advance.

**Comment by yonzhan** [comment]
packaging

**Comment by Tatsinnit** [comment]
💡 Further to add:

* Setup instruction here say `azdev setup -c` is a valid command but seems like it is not as from screenshot below: https://github.com/Azure/azure-cli/blob/dev/doc/configuring_your_machine.md 

<img width="963" alt="Screen Shot 2021-02-11 at 3 25 45 PM" src="https://user-images.githubusercontent.com/6233295/107596761-8996b800-6c7d-11eb-9d54-a8d9c0039e0d.png">

**Comment by yonzhan** [comment]
Add @jiasli for awareness.

**Comment by fengzhou-msft** [comment]
@Tatsinnit we've updated https://github.com/Azure/azure-cli-dev-tools#setting-up-your-development-environment, please follow it and let us know if you still meet issues.

For the `azdev` issue, you're using the one in https://github.com/azure/azure-cli/blob/dev/tools/automation/__main__.py which is deprecated. There is also a PR to update doc: https://github.com/Azure/azure-cli/pull/17236

**Comment by yonzhan** [comment]
@Juliehzl for awareness
