### ISSUE TITLE
'az devops login' fails with pip error

### ISSUE THREAD

**Issue by PushkarVaity** [Azure/azure-cli#16884]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
- az-cli version 2.18.0 fails with pip error trying to install python keyring module. (ex: **`cat ~/.ssh/ado.pat | az devops login`**)
- Following are the messages I see on command line:
        WARNING: Unable to use secure credential store in this environment.
        WARNING: Please refer to alternate methods at https://aka.ms/azure-devops-cli-auth
        WARNING: using Environment variable
        WARNING: or use 'az login'
        **ERROR: An error occurred. Pip failed with status code 1 for package keyring~=17.1.1. Use --debug for more information.**

**To Reproduce**
 `cat ~/.ssh/ado.pat | az devops login` 

**Expected behavior**
Expecting to log user into ADO like in previous versions 

**Environment summary**
CentOS 7, zsh
% az --version
azure-cli 2.18.0 *

**Additional context**
I do not see this issue in 2.17.1 version. Flows started failing when using version 2.18.0
UPDATE: Users reported seeing this in version 2.17.1 as well.

**Comment by yonzhan** [comment]
devops

**Comment by PushkarVaity** [comment]
Hi, more and more users are reporting this breaking our flow now. Is there an update/workaround for this issue since many people seem to be facing the problem?

**Comment by PushkarVaity** [comment]
I can confirm that updating pip to latest version in this target location **/usr/lib64/az/lib/python3.6/site-packages/** helped solve the following error:

_Unable to use secure credential store in this environment.
Please refer to alternate methods at https://aka.ms/azure-devops-cli-auth
using Environment variable
or use ‘az login’
An error occurred. Pip failed with status code 1 for package keyring~=17.1.1. Use --debug for more information._

This still leaves me with the following keyring related issue while executing (**cat ~/.ssh/ado.pat | az devops login --org https://dev.azure.com/my_org/**):

_Failed to store PAT using keyring; falling back to file storage.
You can clear the stored credential by running az devops logout.
Refer https://aka.ms/azure-devops-cli-auth to know more on sign in with PAT._

This does not always translate to loss of functionality. Can someone help with this message?

**Comment by RakeshMohanMSFT** [comment]
This is fixed. Please reopen if you are still facing this issue.
