### ISSUE TITLE
WebApp:az staticwebapp create results in bad request

### ISSUE THREAD

**Issue by RyanHill-MSFT** [Azure/azure-cli#16886]
## Describe the bug
When running the following command, it results in BadRequestError

**Command Name**
`az staticwebapp create`

**Errors:**
```
BadRequestError: Operation returned an invalid status code 'Bad Request'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az staticwebapp create --name {mystaticwebapp} --source https://github.com/RyanHill-MSFT/staticwebapp-vanilla --branch master --token {PAT} --verbose`

## Expected Behavior
Create the static web app
## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.18.0 *

Extensions:
azure-devops 0.18.0
db-up 0.2.0
interactive 0.4.4

```

**Comment by yonzhan** [comment]
staticwebapp

**Comment by Kotasudhakarreddy** [comment]
@RyanHill-MSFT - could you please share the `--dubug` log.

**Comment by RyanHill-MSFT** [comment]
Thanks for the `--debug` hint @Kotasudhakarreddy. I found that my token didn't have the necessary scopes. I'll update the doc to instruct users on the appropriate scopes to add. It would be nice though to bubble these errors higher up the stack.
