### ISSUE TITLE
[ACS] Validate service principal before kubernetes deployment

### ISSUE THREAD

**Issue by dtzar** [Azure/azure-cli#1689]
Creating a new ACS kubernetes cluster requires a valid service principal (sp) and the cluster will deploy even if the sp does not have the appropriate permissions and no warning or error messages are provided.  Sp validation should occur _before_ the deployment and provide a useful message to let people know this is a problem.

**Comment by brendandburns** [comment]
Closing this as a I believe it was fixed by #1704 please re-open if you still see problems.

Thanks!
