### ISSUE TITLE
Return next_marker with results from "az storage fs file list" command

### ISSUE THREAD

**Issue by AlehP** [Azure/azure-cli#16893]
**Is your feature request related to a problem? Please describe.**
If I want to get info about all files in ADLS Gen2 I have to use continuation token, called here as Next Marker (next_marker). 
This marker is not returning with result, but putted into logger as a warning, thus I can't build my logic to get all files in iterative way.  
https://github.com/Azure/azure-cli/blob/8aedd2d631699b422a1a525fb3101284c37ad942/src/azure-cli/azure/cli/command_modules/storage/operations/fs_file.py#L78

**Describe the solution you'd like**
I want to have ability to get nex_marker with response, not as warning message in stdout

**Describe alternatives you've considered**
Alternative is continue using `az storage blob list`, but cli  claim  it will be deprecated.

**Additional context**
https://stackoverflow.com/questions/66125910/how-to-grab-next-marker-next-marker-in-azure-cli-command-az-storage-fs-file-li/66131754#66131754

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
@evelyn-ys  will work on the support in `az storage fs file list`.
