### ISSUE TITLE
Command group 'vm' marked as experimental and under development

### ISSUE THREAD

**Issue by usrme** [Azure/azure-cli#16891]
## Describe the bug

**Command Name**
`az vm <cmd>`

**Errors:**

```text
Command group 'vm' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
```

## To Reproduce:

Just run any `vm` command.

```console
$ az vm show --resource-group rg-name --name vm-name
Command group 'vm' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
{
  "additionalCapabilities": null,
  "availabilitySet": null,
  "billingProfile": null,
  "diagnosticsProfile": null,
  "evictionPolicy": null,
  "extensionsTimeBudget": null,
...
```

```console
$ az vm list
Command group 'vm' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
...
```

## Expected Behavior

Not to see a warning for a command group whose status has **not** been changed to be experimental and **not** documented in the CLI reference types and status documentation page [here](https://docs.microsoft.com/en-us/cli/azure/reference-types-and-status).

## Environment Summary

```
Linux-5.10.13-200.fc33.x86_64-x86_64-with-glibc2.32
Python 3.9.1
Installer: RPM

azure-cli 2.19.0
```

## Additional Context

This was message was not present in 2.18.0 and persists for **any** `vm` command.

**Comment by yungezz** [comment]
hi @usrme sorry for the confusing. THe issue will be fixed in next release. There's nothing changed in vm command group, pls continue use it as normal.

**Comment by gt3M** [comment]
This bug has just started to have a large blast radius for those of us with Azure DevOps pipelines containing Azure CLI steps that are configured with "Fail on standard error". As DevOps agents with this new version of Azure CLI are deployed, such pipelines are now failing. I implore the developers to get a fix out quickly and for this to be communicated to those at Microsoft maintaining DevOps agents.

**Comment by qwordy** [comment]
It will be fixed on 3/2/2021.

**Comment by eprokudin** [comment]
Thanks @qwordy.

My team is experiencing exactly the same problem as @gt3M described with Azure DevOps pipelines failing on standard error.

**Comment by qwordy** [comment]
@eprokudin Sorry to know that.

**Comment by j-hudgins** [comment]
Same- we are experiencing this and looking forward to the resolution @qwordy

**Comment by qwordy** [comment]
@j-hudgins The fix will be available in the release on 3/2/2021.

**Comment by Satak** [comment]
Is this fixed?

**Comment by usrme** [comment]
@Satak, yes. The [latest release](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.20.0) includes a [fix](https://github.com/Azure/azure-cli/commit/fbedfec2e8ca7dd6cdd6ae55b15b7fd1ed0ce642) for this. Considering this closed.

**Comment by j-hudgins** [comment]
@qwordy @usrme  how would I update my azure CLI version if my pipeline runs off of a Microsoft hosted agent? Does the CLI get auto updated or are there some steps I need to take?

**Comment by usrme** [comment]
> @qwordy @usrme how would I update my azure CLI version if my pipeline runs off of a Microsoft hosted agent? Does the CLI get auto updated or are there some steps I need to take?

Unfortunately I'm not using Azure Pipelines, so hopefully @qwordy can help you out.

**Comment by qwordy** [comment]
@j-hudgins @usrme It is not auto updated. See https://docs.microsoft.com/en-us/cli/azure/install-azure-cli. Azure CLI also provide `az upgrade` command to upgrade version.

**Comment by j-hudgins** [comment]
@qwordy i am pretty sure I am running Azure CLI off azure cloud- which the documentation says does not support `az upgrade` ... if that is the case how do I get access to the latest release of Azure CLI? I tried running `az upgrade`  in my powershell script where anyhow and I was unsuccessful.

**Comment by qwordy** [comment]
@j-hudgins If you can't use `az upgrade`, you need to reinstall it. Just use the method of how you install the current Azure CLI. We provide multiple ways to install Azure CLI including `.msi`, `.deb`, `apt install`, `pip install`, etc.
