### ISSUE TITLE
"The system cannot find the file specified" - when installing on Windows with curl

### ISSUE THREAD

**Issue by jonbgallant** [Azure/azure-cli#1690]
C:\Users\jong
λ curl -L https://aka.ms/InstallAzureCli | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   167  100   167    0     0    574      0 --:--:-- --:--:-- --:--:--   618
100   788  100   788    0     0   1476      0 --:--:-- --:--:-- --:--:--  1476
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /tmp/azure_cli_install_tmp_rBjY.
######################################################################## 100.0%
Running install script.
-- Verifying Python version.
-- Python version 2.7.12 okay.

===> In what directory would you like to place the install? (leave blank to use 'C:\Users\jong\lib\azure-cli'):
-- Creating directory 'C:\Users\jong\lib\azure-cli'.
-- We will install at 'C:\Users\jong\lib\azure-cli'.

===> In what directory would you like to place the 'az' executable? (leave blank to use 'C:\Users\jong\bin'):
-- Creating directory 'C:\Users\jong\bin'.
-- The executable will be in 'C:\Users\jong\bin'.
-- Executing: ['C:\\Python27\\python.exe', 'virtualenv.py', '--python', 'C:\\Python27\\python.exe', 'C:\\Users\\jong\\lib\\azure-cli']
Already using interpreter C:\Python27\python.exe
New python executable in C:\Users\jong\lib\azure-cli\Scripts\python.exe
Installing setuptools, pip, wheel...done.
-- Executing: ['C:\\Users\\jong\\lib\\azure-cli\\bin\\pip', 'install', '--cache-dir', 'c:\\users\\jong\\appdata\\local\\temp\\tmphpi5_l', 'azure-cli', '--upgrade']
Traceback (most recent call last):
  File "C:/Users/jong/AppData/Local/Temp/azure_cli_install_tmp_rBjY", line 325, in <module>
    main()
  File "C:/Users/jong/AppData/Local/Temp/azure_cli_install_tmp_rBjY", line 311, in main
    install_cli(install_dir, tmp_dir)
  File "C:/Users/jong/AppData/Local/Temp/azure_cli_install_tmp_rBjY", line 122, in install_cli
    exec_command(cmd)
  File "C:/Users/jong/AppData/Local/Temp/azure_cli_install_tmp_rBjY", line 95, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "C:\Python27\lib\subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

C:\Users\jong
λ

**Comment by derekbekoe** [comment]
@jonbgallant The curl script does not support Windows.
To install the CLI on Windows, please use pip.
https://github.com/Azure/azure-cli#pip

**Comment by jonbgallant** [comment]
Thx. Can you add that to the docs? (That curl isn't support on Windows) and a note to install via pip if using Windows.

**Comment by derekbekoe** [comment]
Yes thanks for the feedback
