### ISSUE TITLE
help pip3 install

### ISSUE THREAD

**Issue by missa112** [Azure/azure-cli#16918]
Help please, I can not install "pip3 install pgpy" on Centos 7, an error occurs.

Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-build-_lndkep4/cryptography/setup.py", line 14, in
from setuptools_rust import RustExtension
ModuleNotFoundError: No module named 'setuptools_rust'

What to do?

**Comment by yungezz** [comment]
hi @missa112 could you pls share more repo steps on how this related with azure cli? thanks.

**Comment by fengzhou-msft** [comment]
@missa112 try to update your pip with: `python3 -m pip install -U pip`
