### ISSUE TITLE
error: list register

### ISSUE THREAD

**Issue by rzlrogerio** [Azure/azure-cli#16919]
## Describe the bug

**Command Name**
`az acr repository list`

**Errors:**
```
RequiredArgumentMissingError: the following arguments are required: --name/-n
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr repository list`

## Environment Summary
```
Linux-5.10.0-3-amd64-x86_64-with-glibc2.31
Python 3.9.1+
Installer: DEB

azure-cli 2.18.0 *

Extensions:
aks-preview Unknown
azure-devops 0.19.0

```

**Comment by yonzhan** [comment]
acr

**Comment by yugangw-msft** [comment]
@rzlrogerio, this error is legit that `-n` is needed for the name of the container registry.
