### ISSUE TITLE
Unclear how to upload file for cool storage

### ISSUE THREAD

**Issue by hasselmm** [Azure/azure-cli#16916]
How do the tiers P10, P20, P30, P4, P40, P50, P6, P60 related to hot, cool and archive tier?

## Describe the bug

**Command Name**
`az storage blob upload`

**Errors:**
```
az storage blob upload: 'cool' is not a valid value for '--tier'. See 'az storage blob upload --help'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload -c {} -f {} -n {} --tier cool`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.75

```

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Currently uploading with `--tier` is already supported in `storage-blob-preview` extension. You could install the extension with `az extension add -n storage-blob-preview`, but please make sure installing azure cli >= 2.16.0. We will migrate the feature in `storage-blob-preview` to azure cli asap.

Besides,  with your current azure cli version, you could upload first and set tier with `az storage blob set-tier`.

**Comment by orloffm** [comment]
> Besides, with your current azure cli version, you could upload first and set tier with az storage blob set-tier.

That means additional costs, no?

> When a blob is moved to a cooler tier (hot->cool, hot->archive, or cool->archive), the operation is billed as a write operation to the destination tier, where the write operation (per 10,000) and data write (per GB) charges of the destination tier apply.
> https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-storage-tiers
