### ISSUE TITLE
az storage account generate-sas fails if a connection string is provided

### ISSUE THREAD

**Issue by mmuffins** [Azure/azure-cli#16917]
## Describe the bug
`az storage account generate-sas` returns error `Argument --account-name should be specified` used with the connection-string parameter. It can be resolved by also providing the account-name parameter in addition to the  connection-string parameter, but that shouldn't be necessary since all needed information is already contained in the connection string.

Downgrading to 2.16 also resolves this issue, we only noticed it in 2.18 and later (haven't tested 2.17).

**Command Name**
`az storage account generate-sas`

**Errors:**
```
Argument --account-name should be specified
```

## To Reproduce:
- `az storage account generate-sas --expiry {} --services {} --resource-types {} --permissions {} --connection-string {}`

## Expected Behavior
The account name should be parsed from the connection string.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1

Extensions:
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
@evelyn-ys I could reproduce the issue and it seems it is caused by https://github.com/Azure/azure-cli/pull/16034. Could you help take a look?
