### ISSUE TITLE
az not in path after install via pip

### ISSUE THREAD

**Issue by jonbgallant** [Azure/azure-cli#1691]
C:\Users\jong
λ pip install --user azure-cli
Collecting azure-cli
  Downloading azure_cli-0.1.0b11-py2.py3-none-any.whl
Collecting azure-cli-acr (from azure-cli)
  Downloading azure_cli_acr-0.1.0b11-py2.py3-none-any.whl
Collecting azure-cli-resource (from azure-cli)
  Downloading azure_cli_resource-0.1.0b11-py2.py3-none-any.whl
Collecting azure-cli-feedback (from azure-cli)
  Downloading azure_cli_feedback-0.1.0b11-py2.py3-none-any.whl
Collecting azure-cli-storage (from azure-cli)
  Downloading azure_cli_storage-0.1.0b11-py2.py3-none-any.whl
Collecting azure-cli-cloud (from azure-cli)
  Downloading azure_cli_cloud-0.1.0b11-py2.py3-none-any.whl
Collecting azure-cli-configure (from azure-cli)
  Downloading azure_cli_configure-0.1.0b11-py2.py3-none-any.whl
Collecting azure-cli-core (from azure-cli)
  Downloading azure_cli_core-0.1.0b11-py2.py3-none-any.whl (61kB)
    100% |################################| 71kB 1.0MB/s
Collecting azure-cli-profile (from azure-cli)
  Downloading azure_cli_profile-0.1.0b11-py2.py3-none-any.whl
Collecting azure-cli-context (from azure-cli)
  Downloading azure_cli_context-0.1.0b11-py2.py3-none-any.whl
Collecting azure-cli-component (from azure-cli)
  Downloading azure_cli_component-0.1.0b12-py2.py3-none-any.whl
Collecting azure-cli-appservice (from azure-cli)
  Downloading azure_cli_appservice-0.1.0b11-py2.py3-none-any.whl
Collecting azure-cli-vm (from azure-cli)
  Downloading azure_cli_vm-0.1.0b11-py2.py3-none-any.whl (124kB)
    100% |################################| 133kB 578kB/s
Collecting azure-cli-nspkg (from azure-cli)
  Downloading azure_cli_nspkg-0.1.0b11-py2.py3-none-any.whl
Collecting azure-cli-network (from azure-cli)
  Downloading azure_cli_network-0.1.0b11-py2.py3-none-any.whl (263kB)
    100% |################################| 266kB 764kB/s
Collecting azure-cli-role (from azure-cli)
  Downloading azure_cli_role-0.1.0b11-py2.py3-none-any.whl
Collecting azure-cli-acs (from azure-cli)
  Downloading azure_cli_acs-0.1.0b11-py2.py3-none-any.whl
Collecting azure-cli-container (from azure-cli)
  Downloading azure_cli_container-0.1.0b11-py2.py3-none-any.whl
Collecting azure-mgmt-storage==0.30.0rc6 (from azure-cli-acr->azure-cli)
  Downloading azure_mgmt_storage-0.30.0rc6-py2.py3-none-any.whl
Collecting azure-mgmt-containerregistry==0.1.0 (from azure-cli-acr->azure-cli)
  Downloading azure_mgmt_containerregistry-0.1.0-py2.py3-none-any.whl
Collecting azure-mgmt-resource==0.30.2 (from azure-cli-acr->azure-cli)
  Downloading azure_mgmt_resource-0.30.2-py2.py3-none-any.whl (110kB)
    100% |################################| 112kB 939kB/s
Collecting applicationinsights (from azure-cli-feedback->azure-cli)
  Downloading applicationinsights-0.10.0.tar.gz
Collecting azure-storage==0.33.0 (from azure-cli-storage->azure-cli)
  Downloading azure_storage-0.33.0-py2-none-any.whl (182kB)
    100% |################################| 184kB 489kB/s
Collecting msrest>=0.4.0 (from azure-cli-core->azure-cli)
  Downloading msrest-0.4.4-py2-none-any.whl (109kB)
    100% |################################| 112kB 825kB/s
Collecting colorama (from azure-cli-core->azure-cli)
  Downloading colorama-0.3.7-py2.py3-none-any.whl
Collecting pygments (from azure-cli-core->azure-cli)
  Downloading Pygments-2.1.3-py2.py3-none-any.whl (755kB)
    100% |################################| 757kB 559kB/s
Collecting argcomplete>=1.3.0 (from azure-cli-core->azure-cli)
  Downloading argcomplete-1.7.0-py2.py3-none-any.whl
Collecting six (from azure-cli-core->azure-cli)
  Downloading six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied: pip in c:\python27\lib\site-packages (from azure-cli-core->azure-cli)
Collecting requests (from azure-cli-core->azure-cli)
  Downloading requests-2.12.4-py2.py3-none-any.whl (576kB)
    100% |################################| 583kB 568kB/s
Collecting tabulate (from azure-cli-core->azure-cli)
  Downloading tabulate-0.7.7-py2.py3-none-any.whl
Collecting msrestazure>=0.4.0 (from azure-cli-core->azure-cli)
  Downloading msrestazure-0.4.6-py2.py3-none-any.whl
Collecting jmespath (from azure-cli-core->azure-cli)
  Downloading jmespath-0.9.0-py2.py3-none-any.whl
Collecting azure-mgmt-dns==0.30.0rc6 (from azure-cli-core->azure-cli)
  Downloading azure_mgmt_dns-0.30.0rc6-py2.py3-none-any.whl
Collecting azure-mgmt-trafficmanager==0.30.0rc6 (from azure-cli-core->azure-cli)
  Downloading azure_mgmt_trafficmanager-0.30.0rc6-py2.py3-none-any.whl
Collecting adal>=0.4.3 (from azure-cli-core->azure-cli)
  Downloading adal-0.4.3-py2.py3-none-any.whl (49kB)
    100% |################################| 51kB 966kB/s
Collecting pyyaml (from azure-cli-core->azure-cli)
  Downloading PyYAML-3.12-cp27-cp27m-win_amd64.whl (197kB)
    100% |################################| 204kB 664kB/s
Collecting azure-mgmt-web==0.30.1 (from azure-cli-appservice->azure-cli)
  Downloading azure_mgmt_web-0.30.1-py2.py3-none-any.whl (209kB)
    100% |################################| 215kB 691kB/s
Collecting urllib3[secure]==1.16 (from azure-cli-appservice->azure-cli)
  Downloading urllib3-1.16-py2.py3-none-any.whl (98kB)
    100% |################################| 102kB 682kB/s
Collecting azure-mgmt-network==0.30.0rc6 (from azure-cli-vm->azure-cli)
  Downloading azure_mgmt_network-0.30.0rc6-py2.py3-none-any.whl (162kB)
    100% |################################| 163kB 609kB/s
Collecting azure-mgmt-compute==0.32.1 (from azure-cli-vm->azure-cli)
  Downloading azure_mgmt_compute-0.32.1-py2.py3-none-any.whl (117kB)
    100% |################################| 122kB 581kB/s
Collecting paramiko (from azure-cli-vm->azure-cli)
  Downloading paramiko-2.1.1-py2.py3-none-any.whl (172kB)
    100% |################################| 174kB 747kB/s
Collecting azure-mgmt-authorization==0.30.0rc6 (from azure-cli-role->azure-cli)
  Downloading azure_mgmt_authorization-0.30.0rc6-py2.py3-none-any.whl
Collecting azure-graphrbac==0.30.0rc6 (from azure-cli-role->azure-cli)
  Downloading azure_graphrbac-0.30.0rc6-py2.py3-none-any.whl (43kB)
    100% |################################| 51kB 664kB/s
Collecting scp (from azure-cli-acs->azure-cli)
  Downloading scp-0.10.2-py2.py3-none-any.whl
Collecting sshtunnel (from azure-cli-acs->azure-cli)
  Downloading sshtunnel-0.1.2.tar.gz
Collecting azure-common[autorest]==1.1.4 (from azure-mgmt-storage==0.30.0rc6->azure-cli-acr->azure-cli)
  Downloading azure_common-1.1.4-py2.py3-none-any.whl
Collecting azure-mgmt-nspkg (from azure-mgmt-storage==0.30.0rc6->azure-cli-acr->azure-cli)
  Downloading azure_mgmt_nspkg-1.0.0-py2.py3-none-any.whl
Collecting futures (from azure-storage==0.33.0->azure-cli-storage->azure-cli)
  Downloading futures-3.0.5-py2-none-any.whl
Collecting cryptography (from azure-storage==0.33.0->azure-cli-storage->azure-cli)
  Downloading cryptography-1.7.1-cp27-cp27m-win_amd64.whl (1.3MB)
    100% |################################| 1.3MB 519kB/s
Collecting python-dateutil (from azure-storage==0.33.0->azure-cli-storage->azure-cli)
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
    100% |################################| 194kB 966kB/s
Collecting azure-nspkg (from azure-storage==0.33.0->azure-cli-storage->azure-cli)
  Downloading azure_nspkg-1.0.0-py2.py3-none-any.whl
Collecting keyring>=5.6 (from msrest>=0.4.0->azure-cli-core->azure-cli)
  Downloading keyring-10.1-py2.py3-none-any.whl
Collecting enum34>=1.0.4 (from msrest>=0.4.0->azure-cli-core->azure-cli)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting certifi>=2015.9.6.2 (from msrest>=0.4.0->azure-cli-core->azure-cli)
  Downloading certifi-2016.9.26-py2.py3-none-any.whl (377kB)
    100% |################################| 378kB 522kB/s
Collecting chardet>=2.3.0 (from msrest>=0.4.0->azure-cli-core->azure-cli)
  Downloading chardet-2.3.0.tar.gz (164kB)
    100% |################################| 174kB 624kB/s
Collecting requests-oauthlib>=0.5.0 (from msrest>=0.4.0->azure-cli-core->azure-cli)
  Downloading requests_oauthlib-0.7.0-py2.py3-none-any.whl
Collecting isodate>=0.5.4 (from msrest>=0.4.0->azure-cli-core->azure-cli)
  Downloading isodate-0.5.4.tar.gz
Collecting PyJWT>=1.0.0 (from adal>=0.4.3->azure-cli-core->azure-cli)
  Downloading PyJWT-1.4.2-py2.py3-none-any.whl
Collecting ndg-httpsclient; python_version <= "2.7" and extra == "secure" (from urllib3[secure]==1.16->azure-cli-appservice->azure-cli)
  Downloading ndg_httpsclient-0.4.2.tar.gz
Collecting pyOpenSSL>=0.13; python_version <= "2.7" and extra == "secure" (from urllib3[secure]==1.16->azure-cli-appservice->azure-cli)
  Downloading pyOpenSSL-16.2.0-py2.py3-none-any.whl (43kB)
    100% |################################| 51kB 930kB/s
Collecting pyasn1; python_version <= "2.7" and extra == "secure" (from urllib3[secure]==1.16->azure-cli-appservice->azure-cli)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from cryptography->azure-storage==0.33.0->azure-cli-storage->azure-cli)
  Downloading cffi-1.9.1-cp27-cp27m-win_amd64.whl (154kB)
    100% |################################| 163kB 648kB/s
Requirement already satisfied: setuptools>=11.3 in c:\python27\lib\site-packages (from cryptography->azure-storage==0.33.0->azure-cli-storage->azure-cli)
Collecting idna>=2.0 (from cryptography->azure-storage==0.33.0->azure-cli-storage->azure-cli)
  Downloading idna-2.2-py2.py3-none-any.whl (55kB)
    100% |################################| 61kB 777kB/s
Collecting ipaddress (from cryptography->azure-storage==0.33.0->azure-cli-storage->azure-cli)
  Downloading ipaddress-1.0.17-py2-none-any.whl
Collecting pywin32-ctypes; sys_platform == "win32" (from keyring>=5.6->msrest>=0.4.0->azure-cli-core->azure-cli)
  Downloading pywin32-ctypes-0.0.1.tar.gz
Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.5.0->msrest>=0.4.0->azure-cli-core->azure-cli)
  Downloading oauthlib-2.0.1.tar.gz (122kB)
    100% |################################| 133kB 1.1MB/s
Collecting pycparser (from cffi>=1.4.1->cryptography->azure-storage==0.33.0->azure-cli-storage->azure-cli)
  Downloading pycparser-2.17.tar.gz (231kB)
    100% |################################| 235kB 819kB/s
Installing collected packages: pywin32-ctypes, keyring, enum34, certifi, chardet, requests, oauthlib, requests-oauthlib, isodate, msrest, colorama, pygments, argcomplete, six, applicationinsights, tabulate, python-dateutil, pycparser, cffi, pyasn1, idna, ipaddress, cryptography, PyJWT, adal, msrestazure, azure-cli-nspkg, jmespath, azure-nspkg, azure-common, azure-mgmt-nspkg, azure-mgmt-dns, azure-mgmt-trafficmanager, pyyaml, azure-cli-core, azure-mgmt-storage, azure-mgmt-containerregistry, azure-mgmt-resource, azure-cli-acr, azure-cli-resource, azure-cli-feedback, futures, azure-storage, azure-cli-storage, azure-cli-cloud, azure-cli-configure, azure-cli-profile, azure-cli-context, azure-cli-component, azure-mgmt-web, pyOpenSSL, ndg-httpsclient, urllib3, azure-cli-appservice, azure-mgmt-network, azure-mgmt-compute, paramiko, azure-cli-vm, azure-cli-network, azure-mgmt-authorization, azure-graphrbac, azure-cli-role, scp, sshtunnel, azure-cli-acs, azure-cli-container, azure-cli
  Running setup.py install for pywin32-ctypes ... done
  Running setup.py install for chardet ... done
  Running setup.py install for oauthlib ... done
  Running setup.py install for isodate ... done
  Running setup.py install for applicationinsights ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for ndg-httpsclient ... done
  Running setup.py install for sshtunnel ... done
Successfully installed PyJWT-1.4.2 adal-0.4.3 applicationinsights-0.10.0 argcomplete-1.7.0 azure-cli-0.1.0b11 azure-cli-acr-0.1.0b11 azure-cli-acs-0.1.0b11 azure-cli-appservice-0.1.0b11 azure-cli-cloud-0.1.0b11 azure-cli-component-0.1.0b12 azure-cli-configure-0.1.0b11 azure-cli-container-0.1.0b11 azure-cli-context-0.1.0b11 azure-cli-core-0.1.0b11 azure-cli-feedback-0.1.0b11 azure-cli-network-0.1.0b11 azure-cli-nspkg-0.1.0b11 azure-cli-profile-0.1.0b11 azure-cli-resource-0.1.0b11 azure-cli-role-0.1.0b11 azure-cli-storage-0.1.0b11 azure-cli-vm-0.1.0b11 azure-common-1.1.4 azure-graphrbac-0.30.0rc6 azure-mgmt-authorization-0.30.0rc6 azure-mgmt-compute-0.32.1 azure-mgmt-containerregistry-0.1.0 azure-mgmt-dns-0.30.0rc6 azure-mgmt-network-0.30.0rc6 azure-mgmt-nspkg-1.0.0 azure-mgmt-resource-0.30.2 azure-mgmt-storage-0.30.0rc6 azure-mgmt-trafficmanager-0.30.0rc6 azure-mgmt-web-0.30.1 azure-nspkg-1.0.0 azure-storage-0.33.0 certifi-2016.9.26 cffi-1.9.1 chardet-2.3.0 colorama-0.3.7 cryptography-1.7.1 enum34-1.1.6 futures-3.0.5 idna-2.2 ipaddress-1.0.17 isodate-0.5.4 jmespath-0.9.0 keyring-10.1 msrest-0.4.4 msrestazure-0.4.6 ndg-httpsclient-0.4.2 oauthlib-2.0.1 paramiko-2.1.1 pyOpenSSL-16.2.0 pyasn1-0.1.9 pycparser-2.17 pygments-2.1.3 python-dateutil-2.6.0 pywin32-ctypes-0.0.1 pyyaml-3.12 requests-2.12.4 requests-oauthlib-0.7.0 scp-0.10.2 six-1.10.0 sshtunnel-0.1.2 tabulate-0.7.7 urllib3-1.16

**C:\Users\jong
λ az
'az' is not recognized as an internal or external command,
operable program or batch file.**

**Comment by derekbekoe** [comment]
Is `%APPDATA%\Python\PythonXY\Scripts` in the PATH?

**Comment by jonbgallant** [comment]
Found it here: C:\Users\jong\AppData\Roaming\Python\Scripts

**Comment by jonbgallant** [comment]
Can you add that info to docs?  That you can find scripts folder somewhere in APPDATA and to search for it.

**Comment by rubengr** [comment]
I add to the PATH but don't works..

**Comment by rubengr** [comment]
Can you help me??

**Comment by derekbekoe** [comment]
Instead of using %APPDATA% as in the documentation, I can suggest using %USERPROFILE% as follows:
```
%USERPROFILE%\AppData\Roaming\Python\Scripts
%USERPROFILE%\AppData\Roaming\Python\PythonXY\Scripts
```

**Comment by shrutir25** [comment]
I am facing a similar issue. I have '%USERPROFILE%\AppData\Roaming\Python\PythonXY\Scripts' added in my path variable but I still receive this error
**'az' is not recognized as an internal or external command,
operable program or batch file.**

**Comment by derekbekoe** [comment]
What that the exact path added? XY was a placeholder for your actual Python version.

**Comment by shrutir25** [comment]
It worked. I mistook the Roaming directory for Local.
