### ISSUE TITLE
az vm disk detach to support force-detach

### ISSUE THREAD

**Issue by avinashakka** [Azure/azure-cli#16912]
**Resource Provider**
- Compute Resource Provider (Microsoft.Compute)

**Description of Feature or Work Requested**

Azure will now support force-detaching managed data disks from a VM. This feature is supported as part of VM recovery scenarios, when a VM is unresponsive due to unexpected failure in underlying stack, Client can choose to just forcibly detach a data disk to mount it and use with another healthy VM. **This feature is supported exclusively only for managed disks [Azure Managed Disks] and on Single instance/ Availability set VMs**

The existing Az-CLI cmd [az vm disk detach](https://docs.microsoft.com/en-us/cli/azure/vm/disk?view=azure-cli-latest#az_vm_disk_detach) should be updated to support a optional --forceDetach param which internally should set tobeDetached and detachOption property of the disk. Force-detaching a data disk is currently supported only by setting [toBeDetached == true](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/update#datadisk) and [detachOption == 'ForceDetach'](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/update#diskdetachoptiontypes) on the [DataDisk](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/update#datadisk)

Additional References:
- PowerShell cmdlet update design request: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/851

**Minimum API Version Required**
 `2020-12-01`

**Swagger Link**
- https://github.com/Azure/azure-rest-api-specs/pull/11554
- [New optional detachOption property introduced for data disk.](https://github.com/Azure/azure-rest-api-specs/blob/e6a4cb677ad0d3b5567ae98024b7c7d360469393/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json#L8929)
- [Sample update (Put/Patch) VM request to force-detach a disk](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/examples/UpdateVMForceDetachDataDisk.json)

**Target Date**
March/April 2021 or the next Az-Cli release which ever is the earliest

**Comment by yungezz** [comment]
will put it in 3/25 release for now.

**Comment by avinashakka** [comment]
> will put it in 3/25 release for now.

If that is the earliest possible release then that sounds good.

**Comment by avinashakka** [comment]
@yungezz Any update on this? This was supposed to go in 3/25/2021 but looks like it still hasn't been completed: https://docs.microsoft.com/en-us/cli/azure/vm/disk?view=azure-cli-latest#az-vm-disk-detach. Is there an ETA on this?

**Comment by zhoxing-ms** [comment]
@avinashakka Sorry, due to re-org, our team is currently responsible for the feature requests related to VM. I'm sorry we didn't realize this request before.
We will plan to develop and release it in the next sprint (**09-06**), this is the fastest time we can release. May I ask is this time acceptable?

**Comment by avinashakka** [comment]
We need this ASAP as we discovered that this is still not supported when a customer tried it directly and saw it wasn't working. 
@zhoxing-ms Please try to get this in as soon as possible. [Tagging @ramankumarlive, @smotwani also for visibility]

**Comment by zhoxing-ms** [comment]
@avinashakka Before the official release of next sprint (09-06), we will generate the private packages through [edge build](https://github.com/Azure/azure-cli/blob/dev/doc/try_new_features_before_release.md) and then you can provide it to customer. 
He can use the private package in advance, so he should not be blocked. Does this meet your expectations?

**Comment by yanzhudd** [comment]
Hello @avinashakka, could you please help to confirm below two questions?

- Since multi-word parameter should be hyphenated in our cli's naming convention, we recommend that the parameter should be changed to `--force-detach` format.
- Is this paramater **only** supported in `az vm disk detach`? Or also supported in `az vmss disk detach` or other groups?

**Comment by zhoxing-ms** [comment]
@avinashakka `az vm disk detach` has supported `--force-detach` in PR #23346, we will release it in this sprint (**08-02**). If you also need `az vmss disk detach` to support `--force-detach`, please create a new feature request, thanks~
