### ISSUE TITLE
az ad app list is missing createdTime

### ISSUE THREAD

**Issue by yene** [Azure/azure-cli#16922]
**Is your feature request related to a problem? Please describe.**
`az ad app list` is missing createdTime

**Describe the solution you'd like**
The resulting list has property `createdTime`
similar to `az resource list` -> `"createdTime": "2019-10-01T13:11:19.635924+00:00",`

If possible `changedTime` would be nice too.

**Additional context**
We use the command to review app registrations, without creationTime it is hard.

**Comment by yonzhan** [comment]
Graph

**Comment by RakeshMohanMSFT** [comment]
This command now returns "createdDateTime": "2022-04-27T06:23:55Z",

`az ad app list --filter "displayname eq 'test'" --app-id "appid-guid"`
[
  {
    "addIns": [],
    "api": {
      "acceptMappedClaims": null,
      "knownClientApplications": [],
      "oauth2PermissionScopes": [],
      "preAuthorizedApplications": [],
      "requestedAccessTokenVersion": null
    },
    "appId": "appid",
    "appRoles": [],
    "applicationTemplateId": null,
    "certification": null,
    **"createdDateTime": "2022-04-27T06:23:55Z",**
