### ISSUE TITLE
az network private-endpoint list-types fails due to invalid resource type error

### ISSUE THREAD

**Issue by adewaleo** [Azure/azure-cli#16929]
az network private-endpoint list-types fails due to invalid resource type error

## Describe the bug

**Command Name**
`az network private-endpoint list-types`

**Errors:**
```
(InvalidResourceType) The resource type 'locations' could not be found in the namespace 'Microsoft.Network' for api version '2020-07-01'. The supported api-versions are '2014-12-01-preview,2015-05-01-preview,2015-06-15,2016-03-30,2016-06-01,2016-07-01,2016-08-01,2016-09-01,2016-10-01,2016-11-01,2016-12-01,2017-03-01,2017-04-01,2017-06-01,2017-08-01,2017-09-01,2017-10-01,2017-11-01,2018-01-01,2018-02-01,2018-03-01,2018-04-01,2018-05-01,2018-06-01,2018-07-01,2018-08-01,2018-10-01,2018-11-01,2018-12-01,2019-02-01'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network private-endpoint list-types --location westus2`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1

Extensions:
alias 0.5.2
interactive 0.4.4

```

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
I have a try and it could work. My azure-cli version is 2.20.0

**Comment by kairu-ms** [comment]
Please upgrade you cli version by command

```
az upgrade
```
