### ISSUE TITLE
How to programmatically extract the encryptionkey from keyvault to add in cosmosdb creation

### ISSUE THREAD

**Issue by V4A001** [Azure/azure-cli#16926]
I want to create a cosmosdb with azli and encryptionkey. However, extraction of key also takes the token 3fxxxx7f22a08 and not will the / forward slash which is required in the cosmos db creation:
https://xxx.vault.azure.net/keys/CosmosDb--EncryptionKey/3fxxxxec7f22a08

But this is required:
https://xxx.vault.azure.net/keys/CosmosDb--EncryptionKey
`
CosmosDbEncryptionKey="$(az keyvault key show --vault-name $KEYVAULT_NAME --name "CosmosDb--EncryptionKey" --query key.kid -otsv)" 
echo $CosmosDbEncryptionKey
==> includes 3f...08
https://xxx.vault.azure.net/keys/CosmosDb--EncryptionKey/3fxxxxec7f22a08

###https://xxx.vault.azure.net/keys/CosmosDb--EncryptionKey

az cosmosdb create \
  --resource-group $RESOURCE_GROUP \
  --name $COSMOSDB_ACCOUNTNAME \
  --kind GlobalDocumentDB \
  --locations regionName=$LOCATION failoverPriority=0 \
  #--locations regionName=$LOCATION_FAILOVER failoverPriority=1 \
  --default-consistency-level "Session" \
  --enable-multiple-write-locations true \
  --key-uri $CosmosDbEncryptionKey \
  --enable-automatic-failover true \
  --enable-public-network false \
  --ip-range-filter $ALLOWED_IP_RANGE \
  --backup-policy-type Continuous \
  --capacity-mode "Serverless (preview)"
`
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc8d652-2eda-296f-28ea-8d5f1ea855b3
* Version Independent ID: 80b87995-d339-61e9-1cac-b5c9ad6efe5e
* Content: [az cosmosdb](https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/cosmosdb.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cosmosdb.yml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cosmosdb

**Comment by MehaKaushik** [comment]
Azure Keyvault team to help the customer figure out a way to get the encryption key directly, instead of extracting from the string.

**Comment by jlichwa** [comment]
It is not token, but actual version of the key. The key id returned from get key command returns id of specific key (and its version), using uri without version is a command to get latest version of the key. 

More info about retrieval of the key can be found here:
https://docs.microsoft.com/en-us/rest/api/keyvault/getkey/getkey

Encryption configuration for cosmosdb as a parameter is taking uri for latest key to support automatic refresh of the key when is rotated.

Once you know key vault name and key name why not use that to construct latest key uri:
`az cosmosdb create ..... --key-uri "https://$KEYVAULT_NAME.vault.azure.net/keys/$KEY_NAME"`

**Comment by V4A001** [comment]
Good suggestion to construct it. Did not think about it as I retrieved principals on existence.\ with az show etc.
