### ISSUE TITLE
az storage with --auth-mode=login incorrectly determines principal permissions

### ISSUE THREAD

**Issue by tkent** [Azure/azure-cli#16928]
My Azure AD user account has access to a blob storage account/container. If I sign into the azure portal, I can navigate to it and perform read, write, and listing actions against it.

However, when I try to use the `az` command to list the container like so...

```
az storage blob list --account-name <the-account-name> \
  --container=<the-container-name> \
  --subscription=<the-subscription-id-of-the-container> \
  --auth-mode=login
```

I get an error that I do not have the required privileges to perform the operation. If I omit the `--auth-mode=login` option, then it works because it looks up account keys (as described in the warning output and #13509). However, my goal is to actually use my Azure AD principal for access.

I've been unable to find any documentation about this and there are a slew of open issues here related to this auth mode (e.g. #16853, #15232, #16899, etc). I'm concerned that `--auth-mode=login` can only be expected to work in some narrow configuration scenario (e.g. all resources under a single subscription)

### (Possibly) Relevant Details

* The storage account is under a different subscription than my Azure AD user account.
* I'm using `azure-cli` version `2.19.1`

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @tkent, if they are in the same tenant, there should be no issue.

**Comment by tkent** [comment]
@Juliehzl 

I don't know if you mean something specific when you say 

> If you have the specific permission to target resource

But I can say that it's working now for. I assume something was fixed in the months since I originally filed this issue.
