### ISSUE TITLE
az storage blob download should allow output to stdout for pipe support

### ISSUE THREAD

**Issue by djgilcrease** [Azure/azure-cli#16925]
**Is your feature request related to a problem? Please describe.**
My company is switching from artifactory to az storage which means I can no longer download bash scripts and pipe them to bash for auto execution. eg `curl -nsfL https://artifactory.company.com/path/to/file | sh -s`

**Describe the solution you'd like**
I would like to be able to do `az storage blob download -c bla -n path/to/file | sh -s`

**Describe alternatives you've considered**
`az storage blob download -c bla -n path/to/file -f /dev/stdout --max-connections 1 --no-progress --output none | sh -s` - This works, but I should not need to add `-f /dev/stdout --max-connections 1 --no-progress --output none` it should be such that is -f is not specified it assumes you want to output to stdout.

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
@evelyn-ys could you take a look for this issue? We already support read form stdin for upload, and I think we could also add stdout support for download scenario with track2 sdk.
Let's add the feature first in `storage-blob-preview` extension.

**Comment by dhduvall** [comment]
Why did this get closed? The PR hasn't been merged.
