### ISSUE TITLE
az backup vault create - No --Tags option

### ISSUE THREAD

**Issue by Pwd9000-ML** [Azure/azure-cli#16924]
Please can the --Tags option be added to allow creation of tags when "Az Backup Vault Create" is made to create a new Recovery Services Vault.

```
az backup vault create --location uksouth --name test --resource-group Test-RG --tags $Tags

az : ERROR: UnrecognizedArgumentError: unrecognized arguments: --tags System.Collections.Hashtable
At line:9 char:1
+ az backup vault create --location uksouth --name test --resource-grou ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Unrecogn...tions.Hashtable:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Try this: 'az backup vault create --location <westus2> --name <MyRecoveryServicesVault> --resource-group <MyResourceGroup>'
Still stuck? Run 'az --help' to view all commands or go to 'https://aka.ms/cli_ref' to learn more
```
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dab6757-9dab-9267-c3ae-073e9db200c1
* Version Independent ID: f5d969a6-e8ef-90eb-5679-b6734612be76
* Content: [az backup vault](https://docs.microsoft.com/en-us/cli/azure/backup/vault?view=azure-cli-latest#az_backup_vault_create)
* Content Source: [latest/docs-ref-autogen/backup/vault.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/backup/vault.yml)
* Service: **backup**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
backup

**Comment by pvrk** [comment]
Taggin @mepand for information. We are treating this as feature request and will respond back with some tentative timelines

**Comment by mepand** [comment]
We have added this item to the backlog. Will update ETA shortly.

**Comment by Flodu31** [comment]
Hello,
Any news on that?
Thanks.
Florent

**Comment by mepand** [comment]
We have completed the changes for this feature . I need to check the next release date when the changes would go live. Will update by tomorrow.

**Comment by zubairabid** [comment]
@yonzhan can the issue be closed. The changes were completed, as can be seen in public facing documentation: https://learn.microsoft.com/en-us/cli/azure/backup/vault?view=azure-cli-latest#az-backup-vault-create.
