### ISSUE TITLE
Missing the responses for the VNet integration commmands? 

### ISSUE THREAD

**Issue by owingruters** [Azure/azure-cli#16938]
I am missing the responses of these commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cf5a035-926f-1cef-8335-963b497cbed8
* Version Independent ID: 296a49f5-bc7a-d56a-6fe2-914d276b2a9e
* Content: [az webapp vnet-integration](https://docs.microsoft.com/en-us/cli/azure/webapp/vnet-integration?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/vnet-integration.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/vnet-integration.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
webapp

**Comment by seligj95** [comment]
please share more info about the issue here so we can further investigate

**Comment by seligj95** [comment]
closing due to no response. please reopen if needed.
