### ISSUE TITLE
Webapp vnet-integration complains it is missing a delegation that exists

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#16939]
## Describe the bug

**Command Name**
`az webapp vnet-integration add`

**Errors:**
```
(SubnetMissingRequiredDelegation) Subnet /subscriptions/XXXX/resourceGroups/myrg/providers/Microsoft.Network/virtualNetworks/VNET858634624/subnets/Subnet858634624 requires any of the following delegation(s) [Microsoft.DBforPostgreSQL/flexibleServers] to reference service association link /subscriptions/XXXX/resourceGroups/myrg/providers/Microsoft.Network/virtualNetworks/VNET858634624/subnets/Subnet858634624/serviceAssociationLinks/Subnet858634624-service-association-link.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Was trying to follow this tutorial:
https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/tutorial-django-app-service-postgres?tabs=clone

Once I got to the `vnet-integration add` step, I got this error. I ran `vnet subnet update` to add the delegation, though I thought the `webapp up` command did this for me. The subnet does in fact show the flexibleServers delegation on the subnet, yet this command always fails. 

When I try to set the vnet integration via portal, the VNET doesn't even show up, so I'm not sure if there is a bug or the service has changed or I'm just doing something wrong.

## Expected Behavior
This should work?

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1

```

**Comment by tjprescott** [comment]
And I recreated my RG and simply ran `postgres flexible-server create`. This did indeed create the VNET and subnet with the delegation set to `Microsoft.DBforPostgreSQL/flexibleServers`, so I don't know why the webapp commands are upset.

**Comment by yonzhan** [comment]
webapp

**Comment by panchagnula** [comment]
@madsd can you take a look?

**Comment by tjprescott** [comment]
@panchagnula and @madsd I also opened an issue against the article since it isn't clear that whether the issue is with either service or the article itself. According to the portal, the VNET integration requires a subnet that is empty and NOT delegated, which is directly contrary to the article which says you have to use the same subnet as the postGRES flexible server is delegated to.

**Comment by madsd** [comment]
@tjprescott @panchagnula thank you Travis. It is the tutorial that is wrong. Both for using B1 SKU, which does not support vnet integration and for not using an empty subnet (with a delegation for Microsoft.Web/serverFarms). A subnet cannot be delegated to multiple services. Basically, the tutorial never worked and should be updated asap - fix would be to add use at least S1 as SKU and add a subnet to the vnet.

The command will take care of setting the right delegation - but in this case, because an existing delegation is in use, this delegation will complain when you try to override it with the serverFarms delegation.

**Comment by mksuni** [comment]
Thanks for pointing this out. I shall get the documentation updated .

**Comment by madsd** [comment]
@mksuni did you update the docs? @tjprescott can we close this issue?

**Comment by smedegaard** [comment]
As far as I can gather the tutorial is still not corrected:
https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/tutorial-django-app-service-postgres

**Comment by madsd** [comment]
#reassign:mksuni @mksuni, looks like this article we not updated.

**Comment by madsd** [comment]
#please-open

**Comment by ahmeds63** [comment]
The tutorial article still isn't updated. @madsd can you please share the command to make the flexible postgresql server with correct params?

**Comment by madsd** [comment]
@ahmeds63 I spoke to the writer and reopened the issue.

**Comment by paul-goodall** [comment]
It appears that the Tutorial still hasn't been corrected :(

In the meantime, can someone please give me an idea at what stage the subject should be left empty?
I changed the SKU from B1 to S1 as the comments above suggest.
Below give you an idea of what I've tried so far:

`
# Create Flexible server in a private virtual network (VNET) 

az postgres flexible-server create \
    --resource-group ${my_rg}  \
    --vnet ${my_vnet} \
    --location ${my_loc} \
    --subnet ${my_subnet} \
    --name ${my_pg_servername} \
    --admin-user ${my_admin_user} \
    --admin-password ${my_admin_passwd} \
    --database-name ${my_pg_dbname} \
    --yes
`

`
az webapp up \
    --resource-group ${my_rg} \
    --location ${my_loc} \
    --plan DjangoPostgres-tutorial-plan \
    --sku S1 \
    --name ${my_app_name}
`

`
az webapp vnet-integration add \
    --resource-group ${my_rg} \
    --name ${my_app_name} \
    --vnet ${my_vnet} \
    --subnet ${my_subnet}
`

The last stage above gives the same reported error c.f. (SubnetMissingRequiredDelegation).
If I remove the subnet specification as per:


`
az webapp vnet-integration add \
    --resource-group ${my_rg} \
    --name ${my_app_name} \
    --vnet ${my_vnet} 
`

The following is received:  `the following arguments are required: --subnet`

Any tips hugely appreciated.

**Comment by paul-goodall** [comment]
#please-open

**Comment by ahmeds63** [comment]
Anyone still facing the issue, I came accross this very helpful video tutorial by Microsoft on Youtube:

Setting up server for django/python: https://www.youtube.com/watch?v=D6Wyk9q2JM0
Setting up database server and its connectivity with your django app: https://www.youtube.com/watch?v=Z4gLolNTM5I&t=293s

I found the above more easy to follow and was able to get the app running in like half hour.

Thanks

**Comment by paul-goodall** [comment]
Thanks @ahmeds63 - I will check it out

**Comment by sugruedes** [comment]
Its now 2024 and this is still an issue. 
At the very least, is it possible to have a clear workaround in these comments? `az network vnet subnet create` requires a different approach from that of the tutorial, so is less than useful.
