### ISSUE TITLE
Documentation for parameters is incomplete, inadequate

### ISSUE THREAD

**Issue by cpdohert** [Azure/azure-cli#16934]
The parameters
```
--hostname
The host name of the custom domain. Must be a domain name.

--name -n
Name of the custom domain.
```

and the example:
```
az cdn custom-domain create -g group --endpoint-name endpoint --profile-name profile -n domain-name --hostname www.example.com
```

do not provide enough information to use this command. `--hostname` and `--name` appear to describe the same thing, conceptually.  The example is useless, as values like `--endpoint-name endpoint`, `--profile-name profile`, and `--name domain-name` do not provide any information about the intended format or nature of the parameter.

As an example, 
```
az cdn custom-domain create --profile-name cdnp-myproject-b4d55 --endpoint-name cdne-myproject-b4d55 --hostname cdn.myproject.com --name myproject.com --resource-group rg-myproject --location eastus
```
returns the error
```
BadRequest: Property 'CustomDomainEntityKey.CustomDomainName' cannot be set to 'myproject.com'.
```
so `--name` _clearly_ is not expecting a domain name despite the description being "Name of the custom domain" and the property's internal label being `CustomDomainName`.

To make things more confusing, the Az.Cdn PowerShell cmdlet New-AzCdnCustomDomain defines
```
-HostName
Specifies the host name of the custom domain.

-CustomDomainName
Specifies the resource name of the custom domain.
```
Is `--name` in the az cli supposed to refer to an internal Azure resource identifier?  If so, where is a user supposed to find that information?

In the Azure Portal, only two tokens are required to create a custom domain: "Endpoint hostname" (pre-filled, and fixed by context) and "Custom hostname".

As it stands, neither the az cli nor the New-AzCdnCustomDomain cmdlet are usable without proper documentation of what the parameters mean and how they used in the instantiation of a custom domain.

[Aside: this is a consistent problem in the documentation for all az cli commands and Az cmdlets: terse, inadequate descriptions of parameters and examples that do not represent real-world usage.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed8c61db-b294-77fb-0e92-eae01d07b776
* Version Independent ID: 958b6e8d-609b-2a58-dbe1-240d3fd894bb
* Content: [az cdn custom-domain](https://docs.microsoft.com/en-us/cli/azure/cdn/custom-domain?view=azure-cli-latest#az_cdn_custom_domain_create)
* Content Source: [latest/docs-ref-autogen/cdn/custom-domain.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cdn/custom-domain.yml)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
CDN

**Comment by slbentley** [comment]
I was just struggling with this same issue. I exported the ARM template and I see my custom domain being used as a name within the template, where my domain dots are replaced with dashes.
www-mydomain-com. I replaced www.mydomain.com in my command line with www-mydomain-com and it worked. But I see that name nowhere within the portal. So, docs need to be updated. Portal needs to be updated. And maybe the az command needs to be updated.

**Comment by cpdohert** [comment]
@slbentley I've done some research in the interim and you may find this helpful.

A "custom domain name" in Azure isn't an attribute of a CDN endpoint; it's actually an independent Azure resource all on its own.  The `--name` parameter for `az cdn custom-domain create` and the `-CustomDomainName` parameter for `New-AzCdnCustomDomain` refers to the Azure resource name for the custom domain name resource.  Since the resource name for an Azure resource is part of the path in the URL to the Azure ARM APIs, it can't have periods in it.  That's why ARM is silently replacing them with dashes in your exported template.

The portal isn't showing the name because the portal displays the custom domain name as if it's an attribute of a CDN endpoint, even though it isn't.

Hope that helps.  The user experience between the az cli, the Az PowerShell module, the Portal, and ARM templates/Bicep keeps fragmenting.  It's like Microsoft doesn't want people using IaC tools.

**Comment by slbentley** [comment]
Interesting. I grew curious and went and checked my QA region which was created from an ARM template  just a few days ago, and has yet to be  reviewed or tested. I was curious to see what the custom domain ended up being set to as my input parameter included dots. Looks like for that input the dots worked. So I guess its just on the cli...maybe.... Its like I'm feeling around in the dark.  But I do continue to move forward. Albeit more slowly that I would like.
