### ISSUE TITLE
aks failed

### ISSUE THREAD

**Issue by nisargam** [Azure/azure-cli#16932]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
'registrationState'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 664, in execute
    raise ex
cli/core/commands/__init__.py, ln 727, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 720, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/tools.py, ln 57, in register_rp_hook
    if not _register_rp(session, url_prefix, rp_name):
python3.6/site-packages/msrestazure/tools.py, ln 102, in _register_rp
    if rp_info['registrationState'] == 'Registered':
KeyError: 'registrationState'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --enable-addons {} --generate-ssh-keys --enable-rbac --service-principal {} --client-secret {}`

## Environment Summary
```
Linux-4.15.0-1106-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.19.0 *

Extensions:
ai-examples 0.2.5

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by RakeshMohanMSFT** [comment]
This is working. Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
`az aks create -g Issue16932 -n Issue16932cluster --service-principal c78a1333-e383-4274-****-******044d --client-secret "secret"
`The behavior of this command has been altered by the following extension: aks-preview
{
  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
    {
      "availabilityZones": null,
