### ISSUE TITLE
'az login' messages suppressed when 'only_show_errors' set to 'yes'

### ISSUE THREAD

**Issue by usrme** [Azure/azure-cli#16949]
## Describe the bug

**Command Name**
`az login`

## To Reproduce:

Either set the `core.only_show_errors` configuration option to `yes` in a configuration file or set the relevant environment variable.

```console
$ export AZURE_CORE_ONLY_SHOW_ERRORS=yes
$ az login
<no output beyond this point>
```

## Expected Behavior

That the configuration options does exactly as described in the [documentation](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration):

> Only show errors during command invocation. In other words, only errors will be written to stderr. It suppresses warnings from preview, deprecated and experimental commands.

---

The message when using just `az login`:

> The default web browser has been opened at https://login.microsoftonline.com/common/oauth2/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.

And the message when using `az login --use-device-code`:

> To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CDUSATQHU to authenticate.

Should **not** be sent to `stderr`.

## Environment Summary

```
Linux-5.10.15-200.fc33.x86_64-x86_64-with-glibc2.32
Python 3.9.1
Installer: RPM

azure-cli 2.19.1
```

## Additional Context

With just `az login` the browser still opens when possible, but when one isn't available and `--use-device-code` is used, then no output means that the user does not know what they are supposed to do next.

**Comment by yonzhan** [comment]
Account

**Comment by svdHero** [comment]
I have a similar problem here. When I execute
```
export AZURE_CORE_ONLY_SHOW_ERRORS=true
az --version
```
in bash, the following text, according to Azure Pipelines, is written to Std Error:
```
Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```
This makes my pipeline job fail then. Also see https://github.com/microsoft/azure-pipelines-tasks/issues/16840.

**Comment by jiasli** [comment]
@usrme, your original issue was addressed by https://github.com/Azure/azure-cli/pull/23647
