### ISSUE TITLE
az role definition create command is part of a script that is delivering a syntax error

### ISSUE THREAD

**Issue by clfilipe** [Azure/azure-cli#16940]
While running the below script, I am getting this error:

**Script:**
az login

$roledefinitions = Get-Content -Path C:\Users\XX\Downloads\test.json | ConvertFrom-Json

foreach ($roledef in $roledefinitions){
    Write-Output "Role Definition to be added is:"
    $role_json = $roledef | ConvertTo-Json
    $rc = "'"+$role_json+"'"
    
    Write-Output "az role definition create --role-definition"
    Write-Output $rc
    az role definition create --role-definition "$rc"
}

**Outcome:**
![image](https://user-images.githubusercontent.com/44497350/107982889-c1269c80-6fbc-11eb-8b00-f085c9650ca1.png)

**Isolated variables/commands**
![image](https://user-images.githubusercontent.com/44497350/107982977-ef0be100-6fbc-11eb-99e0-437162685b46.png)
![image](https://user-images.githubusercontent.com/44497350/107983010-01861a80-6fbd-11eb-9a46-7f96594814e0.png)
![image](https://user-images.githubusercontent.com/44497350/107983501-cdf7c000-6fbd-11eb-9c89-baefa5d0e1a9.png)

**Json file user:**
[
{
  "Name": "rbac_test_1",
  "Id": null,
  "IsCustom": true,
  "Description": "abc",
  "Actions": [
     "*"
  ],
  "NotActions": [
    "Microsoft.Authorization/*/Delete",
    "Microsoft.Authorization/*/Write",
    "Microsoft.Authorization/elevateAccess/Action",
    "Microsoft.Blueprint/blueprintAssignments/write",
    "Microsoft.Blueprint/blueprintAssignments/delete"
  ],
  "AssignableScopes": [
   "/subscriptions/d6fe94b3-749e-456b-bb2d-d89434aa8ec5/resourceGroups/ResourceGroup2"
  ]
},
{
  "Name": "rbac_test_2",
  "Id": null,
  "IsCustom": true,
  "Description": "123",
  "Actions": [
    "Microsoft.Compute/*/read",
    "Microsoft.Storage/*/read",
    "Microsoft.Support/*"
  ],
  "NotActions": [],
  "AssignableScopes": [
   "/subscriptions/d6fe94b3-749e-456b-bb2d-d89434aa8ec5/resourceGroups/ResourceGroup2"
  ]
}
]

**Aditional Context on the use case:**
1) We are working on the backup of custom role definitions and role assignments for each resource type.
2) This backup would later be used to restore the role definitions and role assignments in case of any disaster in systems or change.
3) Our backup script is completed but when we are developing the restore script using the AZ CLI commands shared in the documentation, somehow it’s not working.

I believe this failing because of the "line break". As per the docs, the role definition needs to come right after the command and here it is coming only below. However, I am not being able to update the script to get a successful outcome. 

Can you possibly help?

**Comment by yonzhan** [comment]
RBAC

**Comment by clfilipe** [comment]
Hello Team,

Do we have any updates on this issue? https://github.com/Azure/azure-cli/issues/16940

Thanks,

Cláudia Filipe
Support Engineer - Customer Service and Support
EMEA Cloud Identity POD Support
Office: +351 (21) 0602345 | 9:00 - 18:00 (UTC)
[cid:image001.gif@01D705F4.0E8427A0]

**Comment by jiasli** [comment]
### Line breaks can't be parsed

`az` on Windows is a cmd script that doesn't support line breaks.

```powershell
> Get-Command az

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     az.cmd                                             0.0.0.0    C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
```

To repro:

```powershell
> az --debug '{
>> "a": "b"
>> }'
cli.knack.cli: Command arguments: ['--debug', '{']
```

When calling it from PowerShell, line breaks should by removed first. 

### Double quotes are lost

You may also hit [quoting issues with PowerShell](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md).

```powershell
> $testjson = '{"a":"b"}'
> echo $testjson
{"a":"b"}
> az --debug "$testjson"
cli.knack.cli: Command arguments: ['--debug', '{a:b}']
```

Notice that double quotes (`"`) are lost.

The only way to make it work is to escape double quotes again:

```powershell
> $testjson = '{\"a\":\"b\"}'
> az --debug "$testjson"
cli.knack.cli: Command arguments: ['--debug', '{"a":"b"}']
```

### Best practice

To avoid hitting these unnecessary complications, we recommend using [file input](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md#workaround-use-file-input) `@` for JSON contents: 

```powershell
az role definition create --role-definition "@roledefinition.json"
```

Or in your case, you may also read from `stdin`:

```
Write-Output $rc | az role definition create --role-definition "@-"
```
