### ISSUE TITLE
az storage blob sync not working with 2.19.0

### ISSUE THREAD

**Issue by yixuanhouphl** [Azure/azure-cli#16944]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
On Circle CI
`az storage blob sync --source "./build/" --container \$web --connection-string STRING` is returning error "MSI is not supported yet." 

**To Reproduce**
Set up circle CI pipeline
Using Orb circleci/azure-cli@1.1.0
Install the latest Azure CLI
Log in with service principle 
`az storage blob sync --source "./build/" --container \$web --connection-string STRING`

**Expected behavior**
There shouldn't be an error as this works with 2.18.0

**Environment summary**

**Additional context**
While I downgrade the azure cli version to 2.18.0, there's no issue.

**Comment by yonzhan** [comment]
storage

**Comment by poveilleux** [comment]
We also have noticed the same problem using Azure Pipelines `AzureCLI@1` and `AzureCLI@2` tasks. This prevents us from updating our CDN from our pipelines.

**Comment by yonzhan** [comment]
@Juliehzl will take a look

**Comment by poveilleux** [comment]
Hello @Juliehzl,
Have you been able to look at it?

**Comment by Juliehzl** [comment]
Could you upgrade azure cli to 2.20.0 with `az upgrade` and try again？

**Comment by poveilleux** [comment]
@Juliehzl It works now, thank you 😁
