### ISSUE TITLE
az storage copy crashes: ValidationError: local variable 'service' referenced before assignment

### ISSUE THREAD

**Issue by tengl** [Azure/azure-cli#16959]
## Describe the bug

Same issue as #15379 (regression). When copying from Azure Blob Storage to local machine I get the error. I get the same error in Azure DevOps (same CLI version) which stops our workflow.

**Command Name**
`az storage copy`

**Errors:**
```
local variable 'service' referenced before assignment
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage copy -s {path on storage} -d {local path} --recursive`

## Expected Behavior

I expected it to copy the files to my local disk

## Environment Summary
```
Linux-5.8.0-7642-generic-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.19.1

```

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @tengl, thanks for your feedback. I will take a look soon.

**Comment by Juliehzl** [comment]
There are edge builds with fix available now. Could you try to install edge builds according to https://github.com/Azure/azure-cli#edge-builds and try again?

**Comment by dav009** [comment]
is there getting release any time soon?

**Comment by yonzhan** [comment]
Yes, in this Sprint, within these 2 days.
