### ISSUE TITLE
Command "az storage remove" doesn't work with servicePrincipal

### ISSUE THREAD

**Issue by wild123** [Azure/azure-cli#16967]
**Describe the bug**

Command : az storage remove
az version: 2.19.0
Exception: MSI auth not yet supported.

**To Reproduce**

Login Azure CLI with service principal: 
az login --service-principal -u "***" -p "***" --tenant ***
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "***",
    "id": "***",
    "isDefault": true,
    "managedByTenants": [],
    "name": "***",
    "state": "Enabled",
    "tenantId": "***",
    "user": {
      "name": "***",
      "type": "servicePrincipal"
    }
  }
]

Run Azure CLI Command:

az storage remove --account-name *** --container-name ***

**Expected behavior**

Clean up Azure blob storage

**Environment summary**

Windows latest
azure-cli 2.19..0

**Additional context**

Seems like az cli 2.19.0 use azcopy to implements all storage command, but the service principal login can't work with azcopy creds.

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @wild123, through investigation, service principal is not supported now for `az storage remove` command due to security issue.
Please use `az storage blob delete` or `az storage blob delete-batch`.
