### ISSUE TITLE
AttributeError: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update', Can not create new user with az vm user update

### ISSUE THREAD

**Issue by rjmccallumbigl** [Azure/azure-cli#16962]
## Describe the bug
I have tried several times to create a new user on a Windows (Windows Server 2016 Datacenter) VM per the instructions here:https://docs.microsoft.com/en-us/cli/azure/vm/user?view=azure-cli-latest. Each time I get the below error. This is after deallocation and starting again. Also cannot change the pw of the working local username. Tried AZ CLI, Az PowerShell and local admin PowerShell.

**Command Name**
`az vm user update`

**Errors:**
```
'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 664, in execute
    raise ex
cli/core/commands/__init__.py, ln 727, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 720, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/vm/custom.py, ln 2243, in set_user
    return _reset_windows_admin(cmd, vm, resource_group_name, username, password, no_wait)
cli/command_modules/vm/custom.py, ln 2230, in _reset_windows_admin
    poller = client.virtual_machine_extensions.create_or_update(resource_group_name,
AttributeError: 'VirtualMachineExtensionsOperations' object has no attribute 'create_or_update'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az vm user update -u {} -p {} -g {} -n {} --verbose`
- Particularly I tried the following: az vm user update -u ryan -n repair-sql2_ -p <redacted> -g repair-sql2-20210204173616.296338 --verbose

## Expected Behavior
New user to be created similar to the following functionality: https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/reset-rdp

## Environment Summary
```
Linux-4.15.0-1106-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.19.0 *

Extensions:
vm-repair 0.3.4
ai-examples 0.2.5

```

**Comment by yungezz** [comment]
hi @qwordy could you pls take a look? thanks

**Comment by qwordy** [comment]
Combine with this issue: https://github.com/Azure/azure-cli/issues/16392

**Comment by qwordy** [comment]
It has been fixed in next release on 3/23.
