### ISSUE TITLE
az aks create fails with 'The requested size is currently not available in location'. Works from Portal

### ISSUE THREAD

**Issue by vinisoto** [Azure/azure-cli#16961]
**Describe the bug**

Creating from CLI fails. Works from Portal with the same SKU, region and subscription:

`az aks create -g maxtest1infra -n MyManagedCluster --node-vm-size Standard_DS2_v2 --location eastus`

**BadRequestError**: Operation failed with status: 'Bad Request'. Details: Provisioning of resource(s) for container service MyManagedCluster in resource group maxtest1infra failed. Message: The template deployment failed with error: 'The resource with id: '/subscriptions/d54b42d6-ff6b-4916-996b-0797188ebf52/resourceGroups/maxtest1infra/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-42484858-vmss' failed validation with message: '**The requested size for resource** '/subscriptions/<ommited>/resourceGroups/maxtest1infra/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-42484858-vmss' **is currently not available in location 'eastus' zones '' for subscription '<ommited>'.** Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.

**To Reproduce**

this was working as recently as 2/16/2021 morning PST

`az aks create -g maxtest1infra -n MyManagedCluster --node-vm-size Standard_DS2_v2 --location eastus`

**Expected behavior**

**Environment summary**
Windows
Installed via MSI

```
az --version
azure-cli                         2.19.1

core                              2.19.1
telemetry                          1.0.6

```
**Additional context**
Same VM size, subscription and region combination works from Portal:
![image](https://user-images.githubusercontent.com/18271663/108243476-ff2dd880-7102-11eb-8dde-f6d135fe2720.png)
![image](https://user-images.githubusercontent.com/18271663/108243501-0523b980-7103-11eb-9644-c6ccce028bbe.png)
![image](https://user-images.githubusercontent.com/18271663/108243522-09e86d80-7103-11eb-86c5-73cde2dfa06d.png)
![image](https://user-images.githubusercontent.com/18271663/108243528-0c4ac780-7103-11eb-972e-0cc71edcba6e.png)
![image](https://user-images.githubusercontent.com/18271663/108243551-15d42f80-7103-11eb-89a5-d9ca75b1d775.png)

**Comment by danielkon96** [comment]
Same thing is happening to me.

I tried to deploy in westus which does not contain availability zones and I get the same error from CLI and the PORTAL. I tried in eastus and same problem. This began happening yesterday around 6:30 pm (PT), it was working earlier around 5:00 pm.

**Comment by yonzhan** [comment]
aks

**Comment by mdaslamansari** [comment]
any solution?

**Comment by RakeshMohanMSFT** [comment]
@vinisoto This is working now. Please upgrade to the latest version of azure cli [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
