### ISSUE TITLE
az network application-gateway ssl-cert create using KeyVault cert fails

### ISSUE THREAD

**Issue by ChrisKlug** [Azure/azure-cli#16972]
## Describe the bug

Trying to create an SSL certificate in Application Gateway using a KeyVault cert fails

**Command Name**
`az network application-gateway ssl-cert create`

**Errors:**
```
'Namespace' object has no attribute 'frontend_port'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network application-gateway ssl-cert create -g {} --gateway-name {} --name {} --key-vault-secret-id {}`

## Expected Behavior

A cert is created in the gateway. It seems to work as the Listener using the cert is set up properly. But the actual command fails...

## Environment Summary
```
Linux-4.19.128-microsoft-standard-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.19.1

```

**Comment by yonzhan** [comment]
network

**Comment by ChrisKlug** [comment]
It seems like this started working again for some reason. We had 2 different problems end of last week. This, and one with Application Insight, that just "magically" started working again without any changes... Not sure why it was happening

**Comment by yonzhan** [comment]
@msyyc could verify whether it is service issue before.

**Comment by msyyc** [comment]
I could not reproduce it. Does it ever happen after that?

**Comment by ChrisKlug** [comment]
Nope, it seems like it just started working for some reason...
