### ISSUE TITLE
issue in executing az cli commands after az cli upgrade

### ISSUE THREAD

**Issue by ashishkarnad** [Azure/azure-cli#16973]
## Describe the bug

**Command Name**
`az storage blob sync`

**Errors:**
```
MSI auth not yet supported.
Traceback (most recent call last):
command_modules/storage/azcopy/util.py, ln 122, in client_auth_for_azcopy
    token_info = _unserialize_non_msi_token_payload(token_info)
command_modules/storage/azcopy/util.py, ln 144, in _unserialize_non_msi_token_payload
    'refresh_token': token_info['refreshToken'],
KeyError: 'refreshToken'

...

command_modules/storage/azcopy/util.py, ln 124, in client_auth_for_azcopy
    raise Exception('MSI auth not yet supported.')
Exception: MSI auth not yet supported.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob sync -c {} --verbose --account-name {} --account-key {} -s {}`

## Environment Summary
```
Linux-5.4.0-1039-azure-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.19.1

```

**Comment by yonzhan** [comment]
storage

**Comment by ashishkarnad** [comment]
this is  a production VM and i followed https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt to install az cli but i encountered above issues. i tried to downgrade the az cli to 1.8 referring to https://github.com/Azure/azure-cli/issues/16908

but am not able to downgrade either

**Comment by Juliehzl** [comment]
There are edge builds with fix available now. Could you try to install edge builds according to https://github.com/Azure/azure-cli#edge-builds and try again?

**Comment by Juliehzl** [comment]
> this is a production VM and i followed https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt to install az cli but i encountered above issues. i tried to downgrade the az cli to 1.8 referring to #16908
> 
> but am not able to downgrade either

The fix is in dev branch now and will be officially available on 3/2. If you cannot try edge builds or downgrade the version, could you run `az login` with username and password?

**Comment by JavierPalaciosNexplore** [comment]
Might the be the same than https://developercommunity.visualstudio.com/t/az-cli-blob-storage-sync-fails-in-azure-pipelines/1345576?
We also suffer of same problem, running az-cli by mean of [azure-cli pipeline task](https://github.com/Microsoft/azure-pipelines-tasks), that has been working for a few months with no issue.

**Comment by Juliehzl** [comment]
Fixed on https://github.com/Azure/azure-cli/pull/16885
