### ISSUE TITLE
`az ad sp create-for-rbac` doesn't treat `--name` the way I'd expect

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1698]
`az ad sp create-for-rbac --name colemick-acs-kube-sp2`

results in:

![2017-01-09 1](https://cloud.githubusercontent.com/assets/327028/21794474/7461b916-d6af-11e6-8991-2470d161bb8f.png)

I'm actually amazed this was even possible. The App ID URI is not valid. And the display name doesn't match the name I supplied.

I'd expected to see the following instead:

   Name: `colemick-acs-kube-sp2`
   App ID URI: `http://colemick-acs-kube-sp2`

CC: @yugangw-msft

**Comment by derekbekoe** [comment]
Related to https://github.com/Azure/azure-cli/issues/1596?

**Comment by colemickens** [comment]
Wow that was fast. Yes, this is a dupe. Thanks!
