### ISSUE TITLE
Azure Firewall DNAT rule is not created

### ISSUE THREAD

**Issue by djr1991** [Azure/azure-cli#16986]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Command Name
az network firewall nat-rule create Extension Name: azure-firewall. Version: 0.9.0.

Errors:

BadRequestError: AzureFirewallRule SpringCloudIngressDNAT: Invalid IP address value or range or Service Tag clouddrive.

**To Reproduce**
az network firewall nat-rule create --collection-name {} --destination-ports {} --firewall-name {} --name {} --protocols {} --translated-port {} --action {} --resource-group {} --destination-addresses {} --source-addresses {} --priority {} --translated-address {} --debug

**Expected behavior**
DNAT collection and rule created on the Azure Firewall

**Environment summary**
Linux-4.15.0-1106-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.18.0
azure-cli-ml 1.20.0

Extensions:
azure-firewall 0.9.0
ai-examples 0.2.5
azure-cli-ml 1.20.0

**Additional context**

**Comment by yonzhan** [comment]
network

**Comment by djr1991** [comment]
I have resolved the issue. It wouldn’t complete until I put “” around text and up adresses
