### ISSUE TITLE
Console clearing on command input.

### ISSUE THREAD

**Issue by benlavender** [Azure/azure-cli#16987]
I cannot see a way to stop the terminal from clearing once a command is entered in the documentation or the `az configure` command.

Is this possible right now?

Thanks

**Comment by yonzhan** [comment]
Config

**Comment by benlavender** [comment]
@yonzhan config? 🤔

_Sent from my Pixel 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jiasli** [comment]
@benlavender, the above comment is only for issue triage purpose and you may ignore it. 

Could you give more information about

1. entered in the documentation 
2. the `az configure` command

What is the current behavior you see and what do you expect? Thanks.

**Comment by yonzhan** [comment]
@benlavender any update？
