### ISSUE TITLE
Outputs of some 'exists' sub-commands are different

### ISSUE THREAD

**Issue by usrme** [Azure/azure-cli#16999]
## Describe the bug

**Command Name**
`az storage container exists`
`az group exists`

## To Reproduce:

Call both `az storage container exists` and `az group exists`:

```console
$ az storage container exists --name <existing container name> --account-name <existing storage account>
{
  "exists": true
}
$ az group exists --name <resource group name>
true
```

## Expected Behavior

For the outputs to conform to a single style to avoid writing additional code to deal with discrepancies.

## Environment Summary
```
Linux-5.10.15-200.fc33.x86_64-x86_64-with-glibc2.32
Python 3.9.1
Installer: RPM

azure-cli 2.19.1
```

## Additional Context

When I add `--output tsv` to `az storage container exists` then the output is more similar to `az group exists`, but still not quite right as capitalization is being performed:

```console
$ az storage container exists --name <existing container name> --account-name <existing storage account> --output tsv
True
```

Adding `--output json` to `az group exists` does nothing:

```console
$ az group exists --name <resource group name> --output json
true
```

I have **not** tested other commands where the `exists` sub-command is also present, but those should be verified as well!

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @usrme, thanks for your feedback! The commands have such difference because different SDK design and service team. But you could consider adding `--query` to get similar output for the command, e.g.
```
 az storage container exists -n xxx --account-name xxx --query exists
```

**Comment by usrme** [comment]
I'm sorry, but I don't agree with this. I do understand that there are probably _way_ more important issues to resolve, but for me this is the same as if I were to create a resource with `create`, for example, and in one case the response includes:

```json
{
    "id": "<resource ID>"
}
```

And in another case the response includes:

```json
{
    "resourceId": "<resource ID>"
}
```

Do you see how I would have to have explicit knowledge of how each and every command responds in order to know this? That does not make sense and it requires adding additional pieces of code to account for this.

Now, I don't know how much the developers working on Azure CLI have to follow this, but Microsoft has [REST API guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md) that dictates in the [Response format section](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#710-response-formats) that:

> For organizations to have a successful platform, they must serve data in formats developers are accustomed to using, and in consistent ways that allow developers to handle responses with common code.

If this is **not** true for Azure CLI, then I would like to know why and if it is true, then I would really prefer if you kept this issue open and worked towards unifying responses for, at least, the `exists` sub-command across all of your various SDKs and service teams.
