### ISSUE TITLE
Cannot stop postgres flexible server, says it does not exist but it appears with 'show' and is visible in the portal

### ISSUE THREAD

**Issue by rivardjm** [Azure/azure-cli#17019]
## Describe the bug

**Command Name**
`az postgres flexible-server stop`

**Errors:**
```
Deployment failed. Correlation ID: a44c44a8-eb11-4ec4-8aa8-1af4483a10be. Operation Stop failed, because server db-pgsql-test-centralus-001 does not exist.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres flexible-server stop --resource-group {} --name {}`

## Expected Behavior
server stops
## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1

```

**Comment by yonzhan** [comment]
postgres

**Comment by sr-msft** [comment]
Hello @rivardjm, Sorry about you are running into an issue. Please file a support request for this issue so that we can properly triage what is going on with the server. thanks.

**Comment by nachoalonsoportillo** [comment]
@yonzhan Please proceed with the closure of this issue.
