### ISSUE TITLE
deployment from local git repo to linux app service plan web app fails

### ISSUE THREAD

**Issue by Monte-Christo** [Azure/azure-cli#17014]
### **This is autogenerated. Please review and update as needed.**

**Command Name**
`git push azure master`

**Errors:**

"Oops, an error occurred"

```
D:\src\Playground\udemy\corelx [master]> git remote add azure https://ek-demo@ek-linux-31.scm.azurewebsites.net:443/ek-linux-31.git
D:\src\Playground\udemy\corelx [master]> git push azure master
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 12 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (11/11), 4.98 KiB | 2.49 MiB/s, done.
Total 11 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Deploy Async
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id 'a479c06a9d'.
remote: Repository path is /home/site/repository
remote: Running oryx build...
remote: .
remote: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
remote: You can report issues at https://github.com/Microsoft/Oryx/issues
remote:
remote: Oryx Version: 0.2.20201105.1, Commit: 127d6a3c61a6c0eb67bcfeee0600c3fe71251839, ReleaseTagName: 20201105.1
remote:
remote: Build Operation ID: |NXn+s2f/b/8=.da9ae958_
remote: Repository Commit : a479c06a9d7ac18c3406b666fc17b728213d733a
remote:
remote: Detecting platforms...
remote: Detected following platforms:
remote:   dotnet: 3.1.10
remote: Error: Oops... An unexpected error has occurred.
remote: Deployment Logs : 'https://ek-linux-31.scm.azurewebsites.net/newui/jsonviewer?view_url=/api/deployments/a479c06a9d7ac18c3406b666fc17b728213d733a/log'
To https://ek-linux-31.scm.azurewebsites.net:443/ek-linux-31.git
 * [new branch]      master -> master
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Set up linux-based App Service Plan P1V2.

Set up web app with

`--runtime "DOTNETCORE|3.1" --deployment-local-git`

Created a .NET Core 3.1 web app with 

`dotnet new web`

Committed, added remote, and pushed

Also tried with .NET 2.1, 2.2, and 5.0, with different and matching web app, global.json, and app service plan, of course.. None works. With 5.0, got the same "oops". With the others, deploy worked by website was inoperative (docker was unable to start app inside container).

## Expected Behavior

Web app deploys

## Environment Summary
```
Linux-4.15.0-1106-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.19.0 *

Extensions:
ai-examples 0.2.5

```

**Comment by yonzhan** [comment]
webapp

**Comment by yungezz** [comment]
hi @Monte-Christo seems the issue isn't Azure CLI related, could you pls close this one and track issues at webapp related channel to make sure it's triaged by correct team? thanks

**Comment by Monte-Christo** [comment]
Would love to do this. Tried but failed. Do you have a link? Is the WebApp channel here on GitHub or somewhere else?
