### ISSUE TITLE
az cosmosdb create --name $COSMOSNAME --resource-group $RGNAME --kind MongoDB The command failed with an unexpected error. Here is the traceback: 'registrationState' Traceback (most recent call last):

### ISSUE THREAD

**Issue by andresmmujica** [Azure/azure-cli#17016]
## Describe the bug

**Command Name**
`az cosmosdb create`

**Errors:**
```
'registrationState'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 664, in execute
    raise ex
cli/core/commands/__init__.py, ln 727, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 720, in _run_job
    six.reraise(*sys.exc_info())
...
python3.6/site-packages/msrestazure/tools.py, ln 57, in register_rp_hook
    if not _register_rp(session, url_prefix, rp_name):
python3.6/site-packages/msrestazure/tools.py, ln 102, in _register_rp
    if rp_info['registrationState'] == 'Registered':
KeyError: 'registrationState'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cosmosdb create --name {} --resource-group {} --kind {}`

## Environment Summary
```
Linux-4.15.0-1106-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.19.0 *

Extensions:
ai-examples 0.2.5

```

**Comment by yonzhan** [comment]
cosmosdb

**Comment by MehaKaushik** [comment]
Hi, thanks for creating this issue. Are these the only params you are providing ? Locations is a mandatory param required to create cosmosdb account. Please provide the same. Please find the docs here https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest#az_cosmosdb_create

**Comment by MehaKaushik** [comment]
@andresmmujica please reopen this issue if you still face any issues. Closing it due to inactivity.
