### ISSUE TITLE
`az pipelines release definition show` produces invalid JSON (newlines not escaped)

### ISSUE THREAD

**Issue by tkent** [Azure/azure-cli#17018]
**The issue**
The `az pipelines release definition show` command produces unusable JSON output because newlines are not properly escaped on  _at least_ the `environments[].deployPhases[].workflowTasks[].inputs.script` field.

**To Reproduce**

This is extremely straightforward to reproduce.

1. Define a release pipeline where a stage a script has a newline.
2. Use `az pipelines release definition show` to view it.
3. Attempt to parse the JSON using any standard utility (e.g. `jq`)

Putting it all together, here's how to see the issue in one go

```shell
RELEASE_DEF_JSON="$(az pipelines release definition show \
  --project=YOUR_PROJECT \
  --organization=YOUR_ORGANIZATION \
  --name=YOUR_RELEASE_DEFINITION_NAME \
  --output json)"

# This will fail
echo "$RELEASE_DEF_JSON"  | jq 

# This will show you the invalid JSON
echo "$RELEASE_DEF_JSON"
```

**Expected behavior**
That valid `json` would be produced when the output type is `json`

**Environment summary**
AZ CLI version: `2.19.1`

**Impact note**

This is blocking us from scripting certain operational activities.

**Comment by yonzhan** [comment]
pipelines

**Comment by RakeshMohanMSFT** [comment]
Please reopen if you still need assistance with this, also open the issue in [azure cli extension](https://github.com/Azure/azure-cli-extensions/issues)
