### ISSUE TITLE
AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access

### ISSUE THREAD

**Issue by V4A001** [Azure/azure-cli#17013]
## Describe the bug
For some reason my integration tests start failing as of yesterday. I run from my dev box. I am working with AzureB2C integration with MSAL 3.0 to test if bearer tokens are received. I use my complete startup file including managed identities for my key vaults.
I find it hard to find out was is generating this bug.

The error is thrown upon test server creation.

`
public class TestServerScenarioInitialize
    {
        static string GetKeyVaultEndpoint() => Environment.GetEnvironmentVariable("KEYVAULT_NAME");

        public static TestServer CreateServer()
        {
           ///code ommitted for explaining where error is thrown

            var testServer = new TestServer(hostBuilder);
           ///error thrown above
           
            return testServer;
        }
    }`

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access 'cxxx3'.\r\nTrace ID: fc001aee-6ebe-487c-a226-ad3e9d300b00\r\nCorrelation ID: 00fedcf6-2ceb-4c35-a196-0fb6dc958758\r\nTimestamp: 2021-02-20 10:16:51Z","error_codes":[50078],"timestamp":"2021-02-20 10:16:51Z","trace_id":"fc001aee-6ebe-487c-a226-ad3e9d300b00","correlation_id":"00fedcf6-2ceb-4c35-a196-0fb6dc958758","suberror":"basic_action"}
Traceback (most recent call last):
Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py, ln 233, in invoke
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --output {} --resource {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1

```

**Comment by yonzhan** [comment]
Account

**Comment by V4A001** [comment]
I fixed this by first running F5 before integration tests on my VS2019. The issue is away for now. You can close if you want. With Azure Feedback I got this reporting option.
