### ISSUE TITLE
webapp: MS document link for restoring web App with Azure CLI 

### ISSUE THREAD

**Issue by SajalMS** [Azure/azure-cli#17025]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Customer has raised concern with below MS document link for restoring web App with Azure CLI . 
https://docs.microsoft.com/en-us/cli/azure/webapp/config/backup?view=azure-cli-latest#az_webapp_config_backup_restore

customer gets confuse with required parameter --webapp-name and optional parameter [--target-name] 

**To Reproduce**

We tried to reproduce scenario restoring web App using above CLI script. Below are our findings:

•	Az command does not work as per description in document the below parameter mentioned as optional however script always fails with below error if it we don’t mentions parameter --overwrite

--overwrite
Overwrite the source web app, if --target-name is not specified.

Parameter 'RestoreRequest.overwrite' can not be None.

•	When using below parameter error related to Resource Group or "... WebApp name required" or "...command not found errors "

--target-name
The name to use for the restored web app. If unspecified, will default to the name that was used when the backup was created.

Restore is successful using below Azure CLI:

utkarsha@Azure:~$ az webapp config backup restore --backup-name "Mrutest_202102150747" --container-url "https://testakhilesh.blob.core.windows.net/testbackupcontainer?sp=rwdl&st=2021-02-15T07:47:14Z&se=2294-11-30T07:47:14Z&sv=2020-02-10&sr=c&sig=KvrT0ceKuiIimzFPfNcyTtkgnS7JsNTUN%2FhbHy6l1RI%3D" --resource-group "mrutest123" --webapp-name "mrutest" --target-name "qaaphp" --overwrite
utkarsha@Azure:~$

**Expected behavior**
Requesting you to look into above findings as customer wants update in backup config document : https://docs.microsoft.com/en-us/cli/azure/webapp/config/backup?view=azure-cli-latest#az_webapp_config_backup_restore

**Environment summary**
Using Azure CLI from Azure Portal

**Additional context**
Please update this MS Documentation and make it more convenient for user to understand. 

![A](https://user-images.githubusercontent.com/57890116/108675630-13ac0f80-750d-11eb-9670-1e0b74fb851d.jpg)
![B](https://user-images.githubusercontent.com/57890116/108675636-160e6980-750d-11eb-985e-eea9d78c2d98.png)
![C](https://user-images.githubusercontent.com/57890116/108675639-16a70000-750d-11eb-9cdf-d4e5f24c5251.png)
![D](https://user-images.githubusercontent.com/57890116/108675644-17d82d00-750d-11eb-80a5-21c4cf8bd9fc.png)

**Comment by yonzhan** [comment]
web App

**Comment by panchagnula** [comment]
@ThejaChoudary can you check if we repro this behavior - we haven't changed this command on CLI for a while but maybe the API has been changed that might cause this behavior change. If so we can get the API folks involved. Thanks!

**Comment by ThejaChoudary** [comment]
@panchagnula Able to repro the issue Sisira.

**Comment by panchagnula** [comment]
> @panchagnula Able to repro the issue Sisira.

Going to start an internal thread with the feature owners to help resolve this.

**Comment by vkarasala** [comment]
The issue is with `&` char in the container-url. The CLI parsing breaks as & is- a reserved character.

Wrapping the container-url around two sets of quotes is the current working mitigation. Ex : '"<ContainerUrl>"'.

Thanks & Regards,
Ashok K.
