### ISSUE TITLE
az apim api import: `api-id` and `name` are confusing

### ISSUE THREAD

**Issue by kenchon** [Azure/azure-cli#17026]
### Is your feature request related to a problem? Please describe.

-> Yes

##### Target command

`az apim api import`
docs: https://docs.microsoft.com/en-us/cli/azure/apim/api?view=azure-cli-latest#az_apim_api_import

##### Problem Overview

One apim resource property has two names; `api-id` and `name`.

Here's the example:

```bash
# What I did
$ az apim api import 
    --api-id MyTestAPI \ # <- here I specify api-id as "MyTestAPI"
    --specification-path ./MyTestAPI.yaml \
    --subscription ${my-subscription-name} \
    --service-name ${apim-service-name} \
    --resource-group ${my-resource-group} \
    --specification-format OpenApi \
    --path my-test-api

# What I get (Generated API information)
Command group 'apim api' is in preview. It may be changed/removed in a future release.
{
  ...
  "name": "MyTestAPI", # <- The value I specified as `api-id` is recognized as `name` in backend. 
  "path": "my-test-api",
  ...
}
```

### Describe the solution you'd like

To improve the clarity of the behavior of the API, I prefer property name `api-id` and `name` become same name.

**Comment by yonzhan** [comment]
apim

**Comment by RupengLiu** [comment]
sorry, we can't make api-id and name the same name, api-id is the resource ID, name is the Resource name, they are used in different scenarios in the backend

**Comment by owingruters** [comment]
Really, from the documentation is is not clear what is what. Please describe this more elaborate in the documentation
