### ISSUE TITLE
getting this error after running az apim api import

### ISSUE THREAD

**Issue by malikouadfel** [Azure/azure-cli#17029]
## Describe the bug

**Command Name**
`az apim api import`

**Errors:**
```
'charmap' codec can't decode byte 0x9d in position 59039: character maps to <undefined>
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py, ln 233, in invoke
azure\cli\core\commands\__init__.py, ln 664, in execute
azure\cli\core\commands\__init__.py, ln 727, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 720, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-rg200gj8\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 698, in _run_job
azure\cli\core\commands\__init__.py, ln 331, in __call__
pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py, ln 816, in default_command_handler
azure\cli\command_modules\apim\custom.py, ln 289, in import_apim_api
encodings\cp1252.py, ln 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 59039: character maps to <undefined>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim api import --service-name {} -g {} --api-id {} --path {} --specification-format {} --specification-path {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1

```

**Comment by yonzhan** [comment]
apim

**Comment by malikouadfel** [comment]
@yonzhan  thanks for response.
but 'apim' what?

**Comment by yonzhan** [comment]
API Management service team should look into this issue.

**Comment by RupengLiu** [comment]
looks like not cli issue, can you forward your commands and files to my email: rupliu@microsoft.com, I will take a look

**Comment by DSpirit** [comment]
@malikouadfel have you tried adding the --specification-format parameter?
E.g. `--specification-format OpenApi`
I get the same error when not passing it.

**Comment by miaojiang** [comment]
Doesn't seem to be CLI issue. Please reopen if more assistance is needed.
