### ISSUE TITLE
"az postgres server create" documentation issue (typo?)

### ISSUE THREAD

**Issue by jakesmolka** [Azure/azure-cli#17032]
The second example under `az postgres server create` has a `--version 11.0` parameter, which is not supported.

Running it throws the following error.

``` bash
➜ az postgres server create \
    --resource-group $AZ_RESOURCE_GROUP \
    --name $AZ_DATABASE_NAME \
    --location $AZ_LOCATION \
    --sku-name B_Gen5_1 \
    --storage-size 5120 \
    --admin-user $AZ_PSQL_USERNAME \
    --admin-password $AZ_PSQL_PASSWORD \
        --version 11.0 \
    | jq
WARNING: Checking the existence of the resource group 'xyz-test'...
WARNING: Resource group 'xyz-test' exists ? : False 
WARNING: Creating Resource Group 'xyz-test'...
WARNING: Creating postgres Server 'xyz' in group 'xyz-test'...
WARNING: Your server 'xyz' is using sku 'B_Gen5_1' (Paid Tier). Please refer to https://aka.ms/postgres-pricing  for pricing details
ERROR: Version '11.0' is not supported.
```

However, `--version 11` works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d11bd3f4-efbf-691d-76a4-293ab97ad845
* Version Independent ID: a553d088-d838-f90f-d601-12fa312fe0cf
* Content: [az postgres server](https://docs.microsoft.com/en-us/cli/azure/postgres/server?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/postgres/server.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/postgres/server.yml)
* Service: **postgresql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
postgres

**Comment by sr-msft** [comment]
Thank you @jakesmolka for pointing that out. We will address the doc issue shortly.

**Comment by RakeshMohanMSFT** [comment]
@jakesmolka This is fixed now
