### ISSUE TITLE
az storage blob sync not working with 2.19.1 (authentication error)

### ISSUE THREAD

**Issue by fgrmt** [Azure/azure-cli#17031]
## Describe the bug

Running `az storage blob sync` using `--account-name` and `--account-key` does not work with version 2.19.1 of Azure-CLI.
The command fails with an error asking to login using `az login`.

**Command Name**
`az storage blob sync`

**Errors:**
```
Please run 'az login' to setup account.
```

## To Reproduce:

- `az storage blob sync --container '$web' --source www/ --account-name myaccountname --account-key myaccountkey`

## Expected Behavior

Azure CLI should sync using the credentials provided with `account-name` and `account-key` instead of asking for login.

## Environment Summary
```
macOS-11.2.1-x86_64-i386-64bit
Python 3.8.8
Installer: HOMEBREW

azure-cli 2.19.1

```
## Additional Context

The Azure `account-name` and `account-key` used for this test are valid since they are working when used for other Azure-CLI commands (example : `az storage blob upload-batch`).

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/16885

**Comment by SaulLoachamin** [comment]
What is the solution because in this moment the microsoft agents are not working as expected, we need to change the commands? Or what we need to fix the problem?

**Comment by yonzhan** [comment]
The fix should be released within 2 days.
