### ISSUE TITLE
Manual approval of a SQL Server Private Endpoint connection using the azure-cli command is not possible

### ISSUE THREAD

**Issue by mbetley** [Azure/azure-cli#17050]
**Is your feature request related to a problem? Please describe.**
Manual approval of a (cross-subscription) SQL Server Private Endpoint connection using the az-cli command is not possible:

az network private-endpoint-connection approve -g <resource_group> -n <private_endpoint_conn> --type Microsoft.SQL/servers CMD Output:

```
az network private-endpoint-connection approve: 'Microsoft.SQL/servers' is not a valid value for '--type'. See 'az network private-endpoint-connection approve --help'.
The most similar choices to 'Microsoft.SQL/servers' are:
Microsoft.DBforMySQL/servers
Microsoft.DBforPostgreSQL/servers
Microsoft.DBforMariaDB/servers
```

**Describe the solution you'd like**
PEP approval using Azure CLI is possible

**Describe alternatives you've considered**
Is it possible to find out if the SQL server pep approval feature will be enabled for the Azure cli and is there an ETA?

**Additional context**
Currently, PEP approval is only possible via Powershell command and REST API

PowerShell instead for approval.
`Set-AzPrivateEndpointConnection -ResourceId /subscriptions/xxxxxxxxx-xxxxx-xxxxxx-xxxxxxxxxxx-xxxxxxxxxxxxx/resourceGroups/121020225001164/providers/Microsoft.Sql/servers/xxxxxxxxxxxxxxxx/privateEndpointConnections/PE1-279b4257-717e-4b67-b89f-9693ec28844e -PrivateLinkServiceConnectionState Approved`
 
 
Or REST API
 
`GET https://management.azure.com/subscriptions/xxxxx-xxxxxx-xxxxxxx-xxxxxxxx/resourceGroups/121020225001164/providers/Microsoft.Sql/servers/xxxxxxxxxxxxx/PrivateEndpointConnections/PE1-279b4257-717e-4b67-b89f-9693ec28844e?api-version=2018-06-01-preview`
 
Response:
```
{
  "properties": {
    "privateEndpoint": {
      "id": "/subscriptions/xxxxxxxx-xxxxxxxxx-xxxxx-xxxxx-xxxxxxxxxxxx/resourceGroups/121020225001164/providers/Microsoft.Network/privateEndpoints/PE1"
    },
    "privateLinkServiceConnectionState": {
      "status": "Approved",
      "description": "Please Accept",
      "actionsRequired": "None"
    },
    "provisioningState": "Ready"
  },
  "id": "/subscriptions/6343c102-da59-42ce-a292-3f85d1316201/resourceGroups/121020225001164/providers/Microsoft.Sql/servers/mysqlserver9876543210/privateEndpointConnections/PE1-279b4257-717e-4b67-b89f-9693ec28844e",
  "name": "PE1-279b4257-717e-4b67-b89f-9693ec28844e",
  "type": "Microsoft.Sql/servers/privateEndpointConnections"
}
```
 
 
 
 
```
PUT https://management.azure.com/subscriptions/xxxxx-xxxxxx-xxxxxxx-xxxxxxxx/resourceGroups/121020225001164/providers/Microsoft.Sql/servers/xxxxxxxxxxxxx/privateEndpointConnections/PE1-279b4257-717e-4b67-b89f-9693ec28844e?api-version=2018-06-01-preview
{
  "properties": {
    "privateEndpoint": {
      "id": "/subscriptions/xxxxx-xxxxxx-xxxxxxx-xxxxxxxx/resourceGroups/121020225001164/providers/Microsoft.Network/privateEndpoints/PE1"
    },
    "privateLinkServiceConnectionState": {
      "status": "Approved",
      "description": "Please Accept"
    }
  }
}
```

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
Thank you for your feedback. we will check it soon.

**Comment by kairu-ms** [comment]
Supported in PR https://github.com/Azure/azure-cli/pull/18268
