### ISSUE TITLE
WebApp: `az webapp show` returning null values for SiteConfig properties

### ISSUE THREAD

**Issue by Kotasudhakarreddy** [Azure/azure-cli#17053]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

WebApp: `az webapp show` returning null values for SiteConfig properties

**To Reproduce**

`az webapp show --name <name> --resource-group <RGName>`

**Expected behavior**

It should have a site config properties

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
229008131
