### ISSUE TITLE
WebApp:Still can't delete an appservice plan when it contains a web app

### ISSUE THREAD

**Issue by RyanHill-MSFT** [Azure/azure-cli#17058]
## Describe the bug
When running the command below, I get prompted that the plan contains an app and ask if I want to remove that resource. I select 'y' and command still ends in "error" reporting a conflict. 

In checking the -debug output, it appears the app service is still deleted first even after saying yes. The associated webapps should be deleted first before deleting plan.

**Command Name**
`az appservice plan delete`

**Errors:**
```
Operation returned an invalid status code 'Conflict'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan create --name myplan`
- `az webapp create --plan myplan --name my app`
- `az appservice plan delete --name myplan --debug`

## Expected Behavior
The app service plan and webapp are both removed.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.18.0 *

Extensions:
azure-devops 0.18.0
db-up 0.2.0
interactive 0.4.4

```

**Comment by yonzhan** [comment]
appservice

**Comment by Kotasudhakarreddy** [comment]
@RyanHill-MSFT could you please recheck the prompt you have received during `az appservice plan delete --name myplan --debug` execution. You must have received as below and not to delete `AppService`

![image](https://user-images.githubusercontent.com/60102891/109029187-96d58d00-76e8-11eb-9c17-6c8db5e0e093.png)

**Comment by RyanHill-MSFT** [comment]
I did receive the prompt as you did @Kotasudhakarreddy. My app service plan had a web app associated with it. What I'm saying is that if I confirm I want to delete the app service plan, it should also delete app services associated with the plan, like how it's done inside the portal.

**Comment by Kotasudhakarreddy** [comment]
@RyanHill-MSFT - It is not possible to delete an `AppService plan` when it is associated with a `WebApp` . This is not possible in portal as well. 
if you want to delete both the last  `webapp` and `appservice plan` together you can use ` webapp delete` command.

**Comment by RyanHill-MSFT** [comment]
> @RyanHill-MSFT - It is not possible to delete an `AppService plan` when it is associated with a `WebApp` . This is not possible in portal as well.
> if you want to delete both the last `webapp` and `appservice plan` together you can use ` webapp delete` command.

You're right @Kotasudhakarreddy. I confused the order of operation steps when I reported the bug. When I reported it, I had in my mind deleting the web app and subsequently deleting the app service plan like you can in the portal.

![image](https://user-images.githubusercontent.com/47189704/111642825-cdc52d00-87d4-11eb-8f52-b27224252e94.png)

I know that you can't delete an app service plan when it contains an application. But when you delete a web app, and you're confirming it's okay to delete the app service plan it's associated with, the app service plan isn't deleted.

**Comment by Kotasudhakarreddy** [comment]
@RyanHill-MSFT - I hope you are referring to the `webapp` DELETE action in portal.  If yes, I can able to see my `AppService plan` is deleted along with `webapp` when I confirm to delete. Please cross check one more time if issue is still persist open a ticket with azure support team or you can you can respond here so that I can transfer it to the appropriate team.

**Comment by RyanHill-MSFT** [comment]
I am. I sent you `--debug` entries. I don't see where the app service plan is being deleted. I also don't see a switch to delete the plan when the web app is deleted.

```
Command
    az webapp delete : Delete a web app.

Arguments
    --keep-dns-registration : Keep DNS registration.
    --keep-empty-plan       : Keep empty app service plan.
    --keep-metrics          : Keep app metrics.
    --slot -s               : The name of the slot. Default to the productions slot if not
                              specified.
```

**Comment by Kotasudhakarreddy** [comment]
@RyanHill-MSFT - Thanks for sharing `--debug` entries. You don't see any separate call to delete `appservice plan`. It handles by the  `webapp delete` API internally. Yes, Switch is not present in the current command. I think it could be a `feature request` .

When comes to the reported issue I am unable to repro it in the latest version of `az cli 2.20.0`. To validate you can use below commands after `webapp delete`. You should get either error or no response for both the commands.
`az webapp show --name myname --resource-group myrg`
`az appservice plan show --name myname --resource-group myrg`

**Comment by Kotasudhakarreddy** [comment]
@RyanHill-MSFT - Did you try with the information given. Can you please update your findings. If no issue is persists we will close this issue.

**Comment by RyanHill-MSFT** [comment]
@Kotasudhakarreddy, knowing that `webapp delete` doesn't delete the app service plan by default is a feature request, I'm good with closing this issue. But could be used as a basis for the feature request.
