### ISSUE TITLE
CLI update for changing performance tiers for disks without downtime

### ISSUE THREAD

**Issue by ramankumarlive** [Azure/azure-cli#17063]
**Resource Provider**
Microsoft.Compute/DiskRP

**Description of Feature or Work Requested**

You can now change the performance tiers for Premium SSDs without any downtime to your application. You can change the performance tier of a disk even when it is attached to running virtual machines. With performance tiers on Premium SSDs, customers have the flexibility to scale the disk performance without increasing the disk size by selecting a higher performance tier. They can also change tiers to bring it back to your baseline performance tier, enabling you to achieve higher performance and cost savings.  

The asks are the following:

1. Update the CLI SDK to use the new API version for disk
2. Update the az disk show command to return the new property propertyUpdatesInProgress to inform the customers that tier update is still in progress. 

Read the Performance Tiers Documentation to learn more: https://docs.microsoft.com/en-us/azure/virtual-machines/disks-performance-tiers?tabs=azure-cli

**Minimum API Version Required**
2020-12-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/12796/commits/6a61af0be4e4d5fde162988cc5082542a588b105

**Target Date**
April 16th 2021

**Comment by yungezz** [comment]
disk feature request

**Comment by qwordy** [comment]
I evaluated the 3 features.
1. CLI update for changing performance tiers for disks without downtime
2. Support for zone-redundant storage (ZRS) managed disks
3. Support auto-key rotation of keys for encrypting managed disks

1st and 3rd are easy. 2nd is more complex.
