### ISSUE TITLE
Support for zone-redundant storage (ZRS) managed disks 

### ISSUE THREAD

**Issue by ramankumarlive** [Azure/azure-cli#17065]
**Resource Provider**
Microsoft.Compute/DiskRP
Microsoft.Compute/CRP

**Description of Feature or Work Requested**
ZRS managed disks provides synchronous replication of data across the Zones in a region, enabling disks to tolerate Zonal failures which may occur due to natural disasters or hardware issues. ZRS disks maintain three consistent copies of the data in distinct Availability Zones in a region, making them tolerant to outages. ZRS disks enable customers to maximize their virtual machine availability without the need for application-level replication of data across zones, which is not supported by many legacy applications such as old versions of SQL or industry-specific proprietary software. This means that, if a virtual machine becomes unavailable in an affected Zone, you can continue to work with the ZRS disk by mounting it to a virtual machine in a different zone. You can also use the ZRS option with shared disks to provide improved availability for clustered or distributed applications like SQL FCI, SAP ASCS/SCS or GFS2. ZRS disks is now supported on Premium SSDs and Standard SSDs. 

We need the following changes:
1. Update Azure CLI to use the API version 2020-12-01 for virtual machines, virtual machine scale sets and managed disks 
2. Update the VM, VMSS and disk commands to accept the two new types of disks: Premium_ZRS and StandardSSD_ZRS 
3. Update the VM and disk commands to ensure that ZRS disks cannot be pinned with a zone. 
3. Update the VM commands to ensure that a ZRS disk can be attached to a zonal VM.
4. Update the disk commands to ensure that customers can change the sku (StorageType) of a ZRS disk to other types such as Premium_LRS, StandardSSD_LRS and vice versa.
5. Update the disk commands to ensure that Premium_ZRS and StandardSSD_ZRS works for shared disks.

**Minimum API Version Required**
2020-12-01

**Swagger Link**
DiskRP: https://github.com/Azure/azure-rest-api-specs/pull/12796/commits/d4242d0bdf598d837c3ebf7cfa1676b03b03e8b8
CRP: https://github.com/Azure/azure-rest-api-specs/pull/12958#pullrequestreview-591591543

**Target Date**
April 16th 2021

**Comment by yungezz** [comment]
put in S185 for now

**Comment by qwordy** [comment]
@ramankumarlive 
1, 2, 5 are finished.
4, 6, I need to test.
3, do you expect me to add a validation rule in Azure CLI?

**Comment by ramankumarlive** [comment]
@qwordy 
#3 - good to add validation to fail fast but not a P0 requirement 
You can use ZRS disks in East US EUAP region. Let me tell you how to enable the feature for your subscription.
