### ISSUE TITLE
invalid error "azclierror: argument --public-access: expected one argument" for "mysql flexible-server create"

### ISSUE THREAD

**Issue by bughit** [Azure/azure-cli#17062]
**Describe the bug**

the [docs](https://docs.microsoft.com/en-us/cli/azure/mysql/flexible-server?view=azure-cli-latest#az_mysql_flexible_server_create) say the IP arg is optional

>  Specifying no IP address sets the server in public access mode but does not create a firewall rule.

**To Reproduce**

`az mysql flexible-server create --public-access --name server1 <<other required args>>`

**Expected behavior**

no error

**Environment summary**

azure-cli 2.19.1 on ubuntu 20.04

**Comment by yonzhan** [comment]
mysql

**Comment by savjani** [comment]
@yonzhan - You need to specify in the IP range in --public access values would be  either none, all, <SingleIP>, <StartIP-DestinationIP>

**Comment by savjani** [comment]
We will updatye the documentation as well to reflect this

**Comment by yonzhan** [comment]
@bughit does above solution resolve your issue?

**Comment by bughit** [comment]
I am not clear on the solution. Will `--public-access` accept no args as the docs say? That seems the right way of specifying an empty list.

**Comment by savjani** [comment]
@bughit - --public-access accepts anyone of the following arguments none, all, <Single-IP>, <Start-Destination IP>. You can find an example here - https://docs.microsoft.com/en-us/azure/mysql/flexible-server/how-to-manage-firewall-cli

**Comment by bughit** [comment]
The first place anyone goes to for usage is the command reference, that's it purpose.

https://docs.microsoft.com/en-us/cli/azure/mysql/flexible-server?view=azure-cli-latest#az_mysql_flexible_server_create

So it should be exhaustively complete and correct. If that's the fix, that's fine.

**Comment by savjani** [comment]
@bughit - Ack on the feedback. We will fix the docs.

**Comment by savjani** [comment]
@yonzhan - Can you please close this issue. We have an internal repair item and the command reference doc update will be performed in next release which is expected in 30 days so we can close this issue.
