### ISSUE TITLE
Support auto-key rotation of keys for encrypting managed disks 

### ISSUE THREAD

**Issue by ramankumarlive** [Azure/azure-cli#17064]
**Resource Provider**
Microsoft.Compute/DiskRP

**Description of Feature or Work Requested**
Azure managed disks provide end to end encryption of data with customer-managed keys stored in Azure Key Vault. Now, they can choose to enable automatic rotation of their keys. A disk references a key via its disk encryption set. When you enable automatic rotation for a disk encryption set, the system will automatically update all managed disks, snapshots, and images referencing the disk encryption set to use the new version of the key within one hour. 

We need the following changes:
1. Update Azure CLI to use the Compute API version 2020-12-01
2. Update the az disk-encryption-set create and update commands to support the new boolean property rotationToLatestKeyVersionEnabled

**Minimum API Version Required**
2020-12-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/12796/files#diff-3d7d14cad991b6300999753a4440e8cff0438b2d9b7d7da3948b06d7357115be

**Target Date**
April 16th 2021

**Comment by yungezz** [comment]
put in S185

**Comment by qwordy** [comment]
@ramankumarlive Do you have a recommended parameter name for rotationToLatestKeyVersionEnabled? It is very long.

**Comment by ramankumarlive** [comment]
@qwordy you can use enableAutoKeyRotation
