### ISSUE TITLE
[Network] Loadbalancer behavior change when network bump from '2020-07-01' to '2020-08-01'

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-cli#17071]
**Describe the bug**

==cmd begin=======
az group create -n yyc -l eastus2
az network lb create -g yyc -n lb-yyc --sku Standard  
az network lb show -g yyc -n lb-yyc 
az network public-ip prefix create -g yyc -n prefix-yyc --length 30
az network lb frontend-ip create -g yyc --lb-name lb-yyc -n frontend2-yyc --public-ip-prefix prefix-yyc (failed cmd)
==cmd end=======
When Microsoft.Network version is 2020-07-01, the up cmd succeed; when Microsoft.Network version is 2020-08-01, it failed.
The reason is the difference when exec 'az network lb show -g yyc -n lb-yyc'.

========az network lb show -g yyc -n lb-yyc (2020-07-01)======
{
  "etag": "W/\"d67f1643-943a-4b4d-9711-8a02eb4567db\"",
  "id": "/subscriptions/000000000000000000000000000/resourceGroups/yyc/providers/Microsoft.Network/loadBalancers/lb-yyc/frontendIPConfigurations/frontend2-yyc",
  "inboundNatPools": null,
  "inboundNatRules": null,
  "loadBalancingRules": null,
  "name": "frontend2-yyc",
  "outboundRules": null,
  "privateIpAddress": null,
  "privateIpAddressVersion": "IPv4",
  "privateIpAllocationMethod": "Dynamic",
  "provisioningState": "Succeeded",
  "publicIpAddress": null,
  "publicIpPrefix": {
    "id": "/subscriptions/000000000000000000000000000000000000/resourceGroups/yyc/providers/Microsoft.Network/publicIPPrefixes/prefix-yyc",
    "resourceGroup": "yyc"
  },
  "resourceGroup": "yyc",
  "subnet": null,
  "type": "Microsoft.Network/loadBalancers/frontendIPConfigurations",
  "zones": null
}
=====az network lb show -g yyc -n lb-yyc (2020-07-01) ====

========az network lb show -g yyc -n lb-yyc (2020-08-01)======
{
  "name": "frontend2-yyc",
  "id": "/subscriptions/000000000000000000000000000000/resourceGroups/yyc/providers/Microsoft.Network/loadBalancers/lb-yyc/frontendIPConfigurations/frontend2-yyc",
  "etag": "W/\"7bf54ec2-97b8-4c55-8ad9-531f151919c9\"",
  "type": "Microsoft.Network/loadBalancers/frontendIPConfigurations",
  "properties": {
    "provisioningState": "Succeeded",
    "privateIPAllocationMethod": "Dynamic",
    "publicIPPrefix": {
      "id": "/subscriptions/0000000000000000000000000000/resourceGroups/yyc/providers/Microsoft.Network/publicIPPrefixes/prefix-yyc"
    },
    "privateIPAddressVersion": "IPv4"
  },
  "zones": [
    "1",
    "2",
    "3"
  ]
}
=====az network lb show -g yyc -n lb-yyc (2020-08-01) ====
The up content showed difference for 'zones'. It causes the 'az network lb frontend-ip create -g yyc --lb-name lb-yyc -n frontend2-yyc --public-ip-prefix prefix-yyc' failure. the error message is :

==error message begin===
cli.azure.cli.core.azclierror: (ResourceAvailabilityZonesCannotBeModified) Resource /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/yyc/providers/Microsoft.Network/loadBalancers/lb-yyc/frontendIPConfigurations/LoadBalancerFrontEnd has an existing availability zone constraint  and the request has availability zone constraint 1, 2, 3, which do not match. Zones cannot be added/updated/removed once the resource is created. The resource cannot be updated from regional to zonal or vice-versa.
==error message end===

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Network

**Comment by msyyc** [comment]
linked powershell issue: https://supportability.visualstudio.com/AzureNetworking/_workitems/edit/12686/
