### ISSUE TITLE
Correct syntax for parameters not described or linked to

### ISSUE THREAD

**Issue by cpdohert** [Azure/azure-cli#17078]
For `az cdn endpoint rule add`, the following parameters exist:

```
--match-variable
Name of the match condition.

--operator
Operator of the match condition.

--action-name
Name of the action.
```

The examples given show the following format for these parameters:

```
--action-name CacheExpiration

--match-variable RequestScheme --operator Equal --match-values HTTPS --action-name "UrlRedirect"
```

The syntax of these examples does not match the actions listed here: https://docs.microsoft.com/en-us/azure/cdn/cdn-standard-rules-engine-actions
or the match conditions listed here: https://docs.microsoft.com/en-us/azure/cdn/cdn-standard-rules-engine-match-conditions
and there is no link to the correct format for whatever values these parameters expect.

I consider the documentation for the az CLI to be inadequate and the tool unusable as a result.  This is a consistent problem with many subcommands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fef54fc4-b4a8-d366-40de-a0ae2586961d
* Version Independent ID: 1231852d-d3b4-9bcf-e9d4-ba12cffb7603
* Content: [az cdn endpoint rule](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint/rule?view=azure-cli-latest#az_cdn_endpoint_rule_add)
* Content Source: [latest/docs-ref-autogen/cdn/endpoint/rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cdn/endpoint/rule.yml)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cdn

**Comment by t-bzhan** [comment]
@cpdohert , could you try upgrade to version 2.35.0 or after. We've added more context in the help output.
