### ISSUE TITLE
argument --resource-group/-g: expected one argument azure devops

### ISSUE THREAD

**Issue by Bryankarlsson** [Azure/azure-cli#17077]
Hi,

Im trying to create and run a release pipeline where i try to to create a Azure Container instance.

Here is my task in devops:

![image](https://user-images.githubusercontent.com/28007067/109004646-4e4aaf00-76a9-11eb-87bc-0cd8908673f0.png)

When i run this, i get the following error:
`ERROR: ArgumentUsageError: argument --resource-group/-g: expected one argument`

Here is the complete log:
![image](https://user-images.githubusercontent.com/28007067/109004716-6ae6e700-76a9-11eb-92d5-7960819721e4.png)

I have no idea what this is. Can't it read from the environment variables?

**Comment by yonzhan** [comment]
container instance

**Comment by Bryankarlsson** [comment]
I solved the issue. I put the variable values inside the Variable-tab in the pipeline. This fixed the issue.

**Comment by VolodymyrMolodets** [comment]
I ran into same issue with container instance creation using _az container create_ command in yaml pipelines and fixed that by ensuring env variables were capitalized. 

E.g. ${env:RESOURCEGROUPNAME}.
