### ISSUE TITLE
Why Azure cli 2.19.1 version uses Python 3.6 as a default in pipeline

### ISSUE THREAD

**Issue by LauraRocks** [Azure/azure-cli#17076]
> ### Why Azure cli 2.19.1 version uses Python 3.6 as a default in pipeline

**Describe the bug**
We are using the azure pipelines to create a function app with `az functionapp create` and giving these as a flag (among others):
```
                  --functions-version 3 \
                  --runtime python \
                  --runtime-version 3.8 \
```
But the azure cli gives an error when it tries to create the function app, because it is still trying to use the 3.6. version of the python

The `az --version` in the pipeline gives us this information:

![image](https://user-images.githubusercontent.com/19936722/108998783-12641980-76aa-11eb-9770-571d1aadd285.png)

Can anyone help me with telling where does this default Python version come from and how can we change this?

**Environment summary**
We are using a pipeline in azure devops (cloud), image is ubuntu-20.04 and the agent is Microsoft-hosted.

The AzureCli task is 2.1.0

**Additional context**
We are using templates for this pipeline and it seems that pulling this stage from the template and putting it to the actual pipeline yaml fixes the issue, but even then the default python seems to be wrong when printing out the version details for azurecli with az --version. So it seems that there are two issues, the default python and then also the fact that when using a template, it is impossible to use 3.8 even when explicitly stating that use 3.8.

**Comment by yonzhan** [comment]
functionapp

**Comment by derekllaw** [comment]
Using the CLI command
`az webapp create --name <name> --plan <plan> --resource-group <group> --runtime "Python|3.8" --deployment-local-git`
Gives error:
`'3.8' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by kamperiadis** [comment]
Hi @laurarocks The Python version listed when running `az --version` is the version of Python used by the Azure CLI, but that is different from the Python version passed in `--runtime-version` which dictates what Python version your function app will be using. If you do not pass `--runtime-version`, then we pick the Python version for your function app. You can view the list of supported runtimes for your function app with the `az functionapp list-runtimes` command. Please let me know if you still have questions on the above.

**Comment by kamperiadis** [comment]
Closing as we have not heard back from the customer.
