### ISSUE TITLE
webapp:`az webapp browse` should offer a flag for HTTPS if not default to it

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-cli#17082]
**Is your feature request related to a problem? Please describe.**
Running `az webapp browse` navigates using the http:// scheme, which prompts the "not secure" warning in most modern browsers. The site can be configured to auto-redirect to https:// but http:// strikes me as a strange default, especially when considering network-restricted environments where I may not allow http traffic ingress.

**Describe the solution you'd like**
I would like to have `az webapp browse` commands navigate to the site using the https:// scheme. To me, it feels like the proper default, but I could also see the argument for just adding a flag.

**Describe alternatives you've considered**
Auto-redirect, but this does not work in network-restricted setups where you need https:// to even get that far.

**Additional context**
N/A

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
looking in to it.

**Comment by panchagnula** [comment]
@mattchenderson in CLI the URL to browse will have https if httpsOnly property is true on the site object - currently this is not true/on  by default.
