### ISSUE TITLE
az cli for learning gives subscription errors

### ISSUE THREAD

**Issue by platypus0** [Azure/azure-cli#17085]
I just started to use the az cli as part of an education/certification effort. Kinda dove right in.
After I installed it, I got the following, so I'm looking to correct it somehow. I suspect I did not get the correct learning resources found for: 'https://docs.microsoft.com/en-us/learn/modules/control-azure-services-with-cli/4-work-with-the-cli'. TIA.
* * * Begin * * *
platypus0:~$ az login
The default web browser has been opened at https://login.microsoftonline.com/common/oauth2/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
/app/bin/firefox: line 194: getenforce: command not found
/app/bin/firefox: line 194: [: !=: unary operator expected
You have logged in. Now let us find all the subscriptions to which you have access...
The following tenants don't contain accessible subscriptions. Use 'az login --allow-no-subscriptions' to have tenant level access.
fcf67057-50c9-4ad4-98f3-ffca64add9e9 'IBM'
No subscriptions found.
platypus0:~$ az login --allow-no-subscriptions
The default web browser has been opened at https://login.microsoftonline.com/common/oauth2/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
/app/bin/firefox: line 194: getenforce: command not found
/app/bin/firefox: line 194: [: !=: unary operator expected
You have logged in. Now let us find all the subscriptions to which you have access...
The following tenants don't contain accessible subscriptions. Use 'az login --allow-no-subscriptions' to have tenant level access.
fcf67057-50c9-4ad4-98f3-ffca64add9e9 'IBM'
[
  {
    "cloudName": "AzureCloud",
    "id": "fcf67057-50c9-4ad4-98f3-ffca64add9e9",
    "isDefault": true,
    "name": "N/A(tenant level account)",
    "state": "Enabled",
    "tenantId": "fcf67057-50c9-4ad4-98f3-ffca64add9e9",
    "user": {
      "name": "platypus0@us.ibm.com",
      "type": "user"
    }
  }
]
* * * End * * *

**Comment by yonzhan** [comment]
Account

**Comment by jiasli** [comment]
@platypus0, https://docs.microsoft.com/en-us/learn/modules/control-azure-services-with-cli/4-work-with-the-cli is a correct tutorial for Azure CLI. You may also refer to https://docs.microsoft.com/en-us/cli/azure/ for more detailed documentation.

The error `No subscriptions found.` you received is expected as you don't have accessible Azure subscriptions. You may double check that from Azure Portal https://portal.azure.com/. You may create a free account following https://azure.microsoft.com/en-us/free/.

If you encounter any issue, feel free to create an Azure support ticket: https://azure.microsoft.com/en-us/support/create-ticket/.
