### ISSUE TITLE
rootmert256

### ISSUE THREAD

**Issue by rootmert26** [Azure/azure-cli#17084]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-US/cli/azure/vm?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/vm.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
hi @rootmert26 could you pls share what's the problem with repo steps? thanks.

**Comment by yungezz** [comment]
close this for now since need more info for investigation. feel free to create new issue when any error met.
