### ISSUE TITLE
Please fix test cases

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#17094]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I upgraded compute API version. The below test cases can't run lively. I added comment in `unittest.skip()` to give clues. Code owners, please spend some time to fix them. Appreciate!

```
acs:
test_k8s_install_kubelogin_with_custom_source_url

backup:
test_backup_restore

deploymentmanager:
test_deploymentmanager_scenario

dms:
test_service_commands

eventgrid:
test_create_domain

keyvault:
test_keyvault_hsm_selective_key_restore
test_keyvault_hsm_full_backup_restore
test_keyvault_hsm_role
test_keyvault_hsm_key_using_hsm_name
test_keyvault_hsm_key_using_hsm_url
test_keyvault_hsm_key_download

monitor:
test_monitor_private_link_scope_scenario

netappfiles:
test_perform_replication

network:
test_network_express_route_connection_routing_configuration
test_network_express_route_port_generate_loa
test_vrouter_with_virtual_hub_support
test_network_virtual_hub_router_scenario
test_nw_connection_monitor_v2_test_configuration
test_connection_monitor_v2_test_group
test_private_endpoint_connection_keyvault
test_private_endpoint_connection_private_link_scope
test_private_endpoint_connection_webapp

storage:
test_storage_account_sku
test_adls_access_recursive_scenarios

synapse:
test_data_flow
```

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
@kairu-ms @Juliehzl @msyyc @jsntcy for awareness.

**Comment by kairu-ms** [comment]
There are service issues for test_monitor_private_link_scope_scenario.

**Comment by akshayneema** [comment]
For test_backup_restore it was taking more than 3 hours because some more test cases were added. I've created a separate test suite for the additional test cases. PR link - [](https://github.com/Azure/azure-cli/pull/17183)

**Comment by zubairabid** [comment]
@yonzhan can we close this issue as it was fixed in 2021.
