### ISSUE TITLE
azure-cli storage copy error

### ISSUE THREAD

**Issue by umrogge** [Azure/azure-cli#17101]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
 
After upgrading from azure-cli 2.18.0 to 2.19.1 an error has occurred running the same az storage copy command:
az storage copy -s file -d https://storage.blob.core.windows.net/directory
Error: See expected behavoir
**To Reproduce**

Running the following az storage copy command using azure-cli 2.18.0 and 2.19.1:
az storage copy -s file -d https://storage.blob.core.windows.net/directory

**Expected behavior**

With 2.18.0 no error occurs
With 2.19.1 an error occurs:
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
There are no credentials provided in your command and environment, we will query for the account key inside your storage account. 
Please provide --connection-string, --account-key or --sas-token as credentials, or use `--auth-mode login` if you have required RBAC roles in your command. For more information about RBAC roles in storage, visit https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-cli. 
Setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information.
local variable 'service' referenced before assignment

**Environment summary**

Bug occurs running azure-cli 2.19.1 from local Ubuntu18 terminal and also when running azure DevOps pipelines when calling AzureCLI@2

**Additional context**

A similar error occurred when upgrading from azure-cli 2.11.0 to 2.13.0

**Comment by Juliehzl** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/16971
