### ISSUE TITLE
[Account] The show command's expanded view doesn't provide a superset of the non-expanded view

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1711]
The help text for the `--expanded-view` flag of the `az account show` command indicates that it provides **more** details about the account. However, I noticed that while it does provide some additional data, it also omits some properties, which was pretty unexpected. For example, simply running running `az account show` will return an `isDefault` and `state` property for the account, however, adding `--expanded-view` seems to remove these properties from the returned data.

<img width="666" alt="screen shot 2017-01-11 at 10 37 09 am" src="https://cloud.githubusercontent.com/assets/116461/21861551/2b7c4e6e-d7ea-11e6-9acc-9c11a12740bf.png">

Additionally, the expanded view seems to rename some properties that were already included in the non-expanded view:

1. `name` and `id` become `subscriptionName` and `subscriptionId`
2. The `user` object becomes `userName`

These changes seem somewhat strange, and could potentially impact the ability to write custom scripts/queries that want to access certain properties of an account, regardless if its an "expanded view" or not.

Ideally, adding `--expanded-view` would simply introduce **new** properties to the data that is returned, as opposed to renaming/removing/adding properties.

**Comment by lostintangent** [comment]
From what I can tell, the primary thing that the `--expanded-view` adds is providing the "endpoints" of the cloud environment associated with the subscription. You can already get this info via `az cloud show` (which seems like a more appropriate place for it anyways?), so I'm somewhat confused about the value of the `az account show --expanded-view` flag. Is it even really needed?

<img width="488" alt="screen shot 2017-01-11 at 10 57 08 am" src="https://cloud.githubusercontent.com/assets/116461/21862158/d431836a-d7ec-11e6-9fa1-93bcd17daff8.png">

**Comment by yugangw-msft** [comment]
@lostintangent. this was added per ask from Java SDK. /cc: @jianghaolu

**Comment by jianghaolu** [comment]
@lostintangent  Yes this format was requested by Java team so that authentication in Java SDK can be simplified. Maybe we should use a different name than "expanded view"?

**Comment by yugangw-msft** [comment]
Also /cc: @selvasingh, this issue is the fallout which I have concerned, but unfortunately it is coming true now, that, exposing something for a team's special purpose will inevitably confuse regular users.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
