### ISSUE TITLE
az aks install-cli Failed

### ISSUE THREAD

**Issue by ZosionLee** [Azure/azure-cli#17125]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
IncompleteRead(12095791 bytes read, 35337975 more expected)
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py, ln 233, in invoke
azure\cli\core\commands\__init__.py, ln 664, in execute
azure\cli\core\commands\__init__.py, ln 727, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 720, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-rg200gj8\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 698, in _run_job
azure\cli\core\commands\__init__.py, ln 331, in __call__
pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py, ln 816, in default_command_handler
azure\cli\command_modules\acs\custom.py, ln 351, in k8s_install_cli
azure\cli\command_modules\acs\custom.py, ln 460, in k8s_install_kubelogin
azure\cli\command_modules\acs\custom.py, ln 303, in _urlretrieve
http\client.py, ln 462, in read
http\client.py, ln 614, in _safe_read
http.client.IncompleteRead: IncompleteRead(12095791 bytes read, 35337975 more expected)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1

```

**Comment by yungezz** [comment]
hi @ZosionLee this seems network issue, could you pls try rerun? route to appropriate team

**Comment by ZosionLee** [comment]
> hi @ZosionLee this seems network issue, could you pls try rerun? route to appropriate team

Hi. It is indeed caused by network problems. Perhaps it is relatively slow to access the services corresponding to Azure in my area, and the download speed is very low. Already processed, thank you
