### ISSUE TITLE
webapp:No such file or directory az webapp up

### ISSUE THREAD

**Issue by lamboktulus1379** [Azure/azure-cli#17145]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
[Errno 2] No such file or directory: 'C:\\Users\\lambo\\source\\repos\\AkuSuka\\TokenService.csproj'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py, ln 233, in invoke
cli\core\commands\__init__.py, ln 664, in execute
cli\core\commands\__init__.py, ln 727, in _run_jobs_serially
cli\core\commands\__init__.py, ln 719, in _run_job
cli\command_modules\appservice\commands.py, ln 37, in _ex_handler
cli\core\commands\__init__.py, ln 698, in _run_job
...
cli\command_modules\appservice\_create_util.py, ln 193, in detect_dotnet_lang
xml\etree\ElementTree.py, ln 1196, in parse
xml\etree\ElementTree.py, ln 586, in parse
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lambo\\source\\repos\\AkuSuka\\TokenService.csproj'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --sku {} --name {} --os-type {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1

```

**Comment by yungezz** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
@lamboktulus1379 - `az webapp up` this command is required to run from the folder where the code is present. in your case you should run from the folder where the `.csproj` is exists.

**Comment by lamboktulus1379** [comment]
![image](https://user-images.githubusercontent.com/42629000/109524815-81df6c00-7ae3-11eb-8471-de2a5628bab9.png)
This is my directory structure...

The TokenService.csproje exist in project TokenService

**Comment by calvinsID** [comment]
Looks like code is looking for `C:\Users\lambo\source\repos\AkuSuka\TokenService.csproj` instead of \AkuSuka\TokenService\TokenService.csproj - can you pls try to run command inside the \AkuSuka\TokenService directory rather than \AkuSuka directory?

**Comment by lamboktulus1379** [comment]
Oke Thanks.. I will try...

I think I have been wrong directory...

Thanks for the help

**Comment by Kotasudhakarreddy** [comment]
yes please try from the `\AkuSuka\TokenService\TokenService.csproj` .
