### ISSUE TITLE
Getting the below error while trying to authenticate to azure subscription

### ISSUE THREAD

**Issue by shalin231** [Azure/azure-cli#17142]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-01-19T08:57:18.3420000Z and the maximum allowed lifetime for this request is 28800.\r\nTrace ID: 7f71aec4-7ca4-457f-8346-4a6935741300\r\nCorrelation ID: aa01de5a-0067-4c86-a31a-1f3632d1feaa\r\nTimestamp: 2021-02-27 09:01:41Z","error_codes":[70043],"timestamp":"2021-02-27 09:01:41Z","trace_id":"7f71aec4-7ca4-457f-8346-4a6935741300","correlation_id":"aa01de5a-0067-4c86-a31a-1f3632d1feaa","suberror":"token_expired"}
Traceback (most recent call last):
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --resource {} --subscription {} -o={}`

## Environment Summary
```
macOS-10.15.4-x86_64-i386-64bit
Python 3.8.5
Installer: HOMEBREW

azure-cli 2.9.1

```

**Comment by yonzhan** [comment]
account

**Comment by shalin231** [comment]
Yonzhan, account ?

**Comment by jiasli** [comment]
@shalin231, the above comment is only for issue triage purpose and you may ignore it. 

Your issue is the same as https://github.com/Azure/azure-cli/issues/16209#issuecomment-787593844. Please check my comments and let me know if you are unblocked.
