### ISSUE TITLE
webapp:Unable to run `az webapp up --sku B1 --name <app-name>` following the Python Quickstart guide

### ISSUE THREAD

**Issue by frederickjjoubert** [Azure/azure-cli#17143]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I am following the Quickstart: Create a Python app using Azure App Service on Linux guide at [https://docs.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=bash&pivots=python-framework-flask](https://docs.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=bash&pivots=python-framework-flask)

But I get stuck in a loop on the command below and cannot deploy the application.

**To Reproduce**

Complete the steps of the guide up to the following point, then:

Run `az webapp up --sku B1 --name <app-name>`

PS I am using a unique app-name.

Get the following prompt:

```
The command requires the extension webapp. Do you want to install it now? The command will continue to run after the extension is installed. (Y/n):
```

Y:

```
Run 'az config set extension.use_dynamic_install=yes_without_prompt' to allow installing extensions without prompt.
Extension 'webapp' 0.3.1 is already installed.
It will be updated if available.
No updates available for 'webapp'. Use --debug for more information.
```

and the prompt reappears throwing me in a loop: 

```
The command requires the extension webapp. Do you want to install it now? The command will continue to run after the extension is installed. (Y/n):
```

n:

```
The command requires the latest version of extension webapp. To install, run 'az extension add --upgrade -n webapp'.
```

So I run `az extension add --upgrade -n webapp`

and once again

```
Extension 'webapp' 0.3.1 is already installed.
It will be updated if available.
No updates available for 'webapp'. Use --debug for more information.
```

**Expected behavior**

Per the guide I expect the deployment process to begin

**Environment summary**

Installed azure-cli with brew on macOS Big Sur v11.2.1

`brew install azure-cli`

**Additional context**

This is my first time working with azure, I've never used it before or installed the CLI before.

**Comment by frederickjjoubert** [comment]
Update: I ran `brew reinstall azure-cli` a few more times out of frustration and now it's working.

**Comment by panchagnula** [comment]
@frederickjjoubert looks like you have an older version of azure-cli extension installed ; that is causing this behavior. Looks like a clean/new install of core helped? Otherwise I would recommend you deleting the extension version

az extension remove --name webapp ; so that can use just the core-cli webapp package. Thanks!

**Comment by Kotasudhakarreddy** [comment]
@frederickjjoubert hope you are unblocked with the issue now. please confirm so that we will close this issue.

**Comment by frederickjjoubert** [comment]
All good here, thank you!
