### ISSUE TITLE
CLI for Virtual WAN : p2s multiple authentication 

### ISSUE THREAD

**Issue by neethirshetty** [Azure/azure-cli#17158]
**Is your feature request related to a problem? Please describe.**
P2S multiple authentication feature has been released. Hence we will need to add CLI support to it.
previously we were allowed to set only single authentication for P2S vpnServerConfiguration. Support for multiple authentication has to be added.

**Describe the solution you'd like**

Brief about multi auth: . A point-to-site (P2S) VPN lets you create a secure connection to your virtual WAN from an individual client computer. there are 3 auth types allowed: radius/AAD/Certificate. Previously we used to support setting only one of these auth types. But with multi auth we need to allow setting multiple auth parameters at a time.

**Describe alternatives you've considered**

CLI is needed for this as this feature is already released.

**Additional context**

Please contact me neethir@microsoft.com if there is any questions on Point to site multi- auth feature CLI request.

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
@neethirshetty Which cli-cmd do you want to add? Which swagger file is related with the issue? Please give more detailed description.

**Comment by neethirshetty** [comment]
there is no swagger for this as we were allowing only 1 entry for -vpnAuthenticationType property in New-AzVpnServerConfiguration and Update-AzVpnServerConfiguration. With multi auth we would like to allow multiple vales to be passed. eg: -vpnAuthenticationType AAD,Certificate,Radius(allowed now). (Before this change only 1 value was allowed to be set. -vpnAuthenticationType )

**Comment by msyyc** [comment]
@neethirshetty Which cli-cmd do you want to add the new parameters? Is the issue same with https://github.com/Azure/azure-cli/issues/17260?

**Comment by yonzhan** [comment]
@neethirshetty any feedback or update?

**Comment by neethirshetty** [comment]
This is for virtual wan and  #17260 is for VNG. 
In this VWan scenario:
The PS command **New-AzVpnServerConfiguration**  
[-VpnClientRootCertificateFilesList <String[]>] [-VpnClientRevokedCertificateFilesList <String[]>] 
[-RadiusServerAddress <String>] [-RadiusServerSecret <SecureString>] [-RadiusServerList <PSRadiusServer[]>] 
 [-RadiusServerRootCertificateFilesList <String[]>] [-RadiusClientRootCertificateFilesList <String[]>]
 [-AadTenant <String>] [-AadAudience <String>] [-AadIssuer <String>] 

from the above command: previously we were allowing only 1 auth type related param. ie either radius or add or cert. But now we need to allow setting multiple auths params . ie: cert and radius and aad
