### ISSUE TITLE
Error while installing edge build

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#17151]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Encountered the following error while installing the edge build
![image](https://user-images.githubusercontent.com/30876406/109541093-3cd22000-7a78-11eb-8dc6-cfec0f1b1756.png)

**To Reproduce**
Installation steps as per shared over email

**Expected behavior**
That the installation would have gone through :)

**Environment summary**

![image](https://user-images.githubusercontent.com/30876406/109541149-55423a80-7a78-11eb-9db3-b13e965a15e4.png)

**Additional context**

Tried following recommendations here but still encountered the same error:
https://stackoverflow.com/questions/63509419/error-could-not-build-wheels-for-bcrypt-which-use-pep-517-and-cannot-be-install

**Comment by yonzhan** [comment]
edge build

**Comment by jiasli** [comment]
Installing **bcrypt** shouldn’t require building from source:

```
> pip install bcrypt
Collecting bcrypt
  Using cached bcrypt-3.2.0-cp36-abi3-win_amd64.whl (28 kB)
Collecting cffi>=1.1
  Using cached cffi-1.14.5-cp38-cp38-win_amd64.whl (179 kB)
Collecting six>=1.4.1
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: pycparser, cffi, six, bcrypt
Successfully installed bcrypt-3.2.0 cffi-1.14.5 pycparser-2.20 six-1.15.0
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'd:\cli-test\testenv0302\scripts\python.exe -m pip install --upgrade pip' command.
```

May I know which python and pip version you are using?

```
python --version
pip --version
```

If you are using an old pip, could you follow the instruction in the terminal to update to the latest pip?
