### ISSUE TITLE
az aks get-versions leaves a \r character in the output

### ISSUE THREAD

**Issue by clambert** [Azure/azure-cli#17155]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
running the az aks get-versions command leaves a \r in the output when running it on unbuntu using the windows subsystem for linux

**To Reproduce**
1) run 
```
VERSION=$(az aks get-versions \
> --location $REGION_NAME \
> --query 'orchestrators[?!isPreview] | [-1].orchestratorVersion' \
> --output tsv)
```
at the command prompt in Ubuntu using Windows Terminal
2) set `REGION_NAME=eastus`, `RESOURCE_GROUP=akscostsaving`, and `AKS_CLUSTER_NAME=akscostsaving-$RANDOM` so the next command will work (These were the values being used in the tutorial)
3) run 
```
az aks create \
> --resource-group $RESOURCE_GROUP \
> --name $AKS_CLUSTER_NAME \
> --location $REGION_NAME \
> --kubernetes-version $VERSION \
> --node-count 2 \
> --load-balancer-sku standard \
> --vm-set-type VirtualMachineScaleSets \
> --generate-ssh-keys
```
**Actual Behavior**
output of:
```
The behavior of this command has been altered by the following extension: aks-preview
SSH key files 'C:\Users\charl\.ssh\id_rsa' and 'C:\Users\charl\.ssh\id_rsa.pub' have been generated un
der ~/.ssh to allow SSH access to the VM. If using machines without permanent storage like Azure Cloud
 Shell without an attached file share, back up your keys to a safe location
Operation failed with status: 'Bad Request'. Details: Error to parse agent pool version "1.19.7\r": In
valid character(s) found in patch number "7\r"
```

**Expected behavior**
output of:
```
The behavior of this command has been altered by the following extension: aks-preview
SSH key files 'C:\Users\charl\.ssh\id_rsa' and 'C:\Users\charl\.ssh\id_rsa.pub' have been generated un
der ~/.ssh to allow SSH access to the VM. If using machines without permanent storage like Azure Cloud
 Shell without an attached file share, back up your keys to a safe location
```
followed by lots of json

**Environment summary**

installed via MSI
version:
 ```
{
  "azure-cli": "2.19.1",
  "azure-cli-core": "2.19.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.0"
  }
}
```
Windows 10 Home ver 2004 os build 19041.804
shell bash running inside of Ubuntu Linux installed via Windows Subsystem for Linux. All of that was running inside of Windows Terminal 

**Additional context**

I installed the Azure CLI onto windows before I installed the Windows Subsystem for Linux, it was visible inside of my Ubuntu install without any additional steps.
I have run these command together about a week ago on macos using the bash shell and this problem does not occur.

**Comment by jiasli** [comment]
Please see the explanation at https://github.com/Azure/azure-cli/issues/13573#issuecomment-888791313.
