### ISSUE TITLE
az storage blob download-batch creating file instead of folder for parent and failing with [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by abhi-msft** [Azure/azure-cli#17179]
I am trying to download files recursively from Azure storage to local folder using the command:
az storage blob download-batch -d $targetFilePath --pattern $searchPattern -s $projectName  --account-name $storageAccount --auth-mode login -o tsv

During the process, it started downloading the file: **XXX/1.0.0/FileName.psd1**
The expected behavior is to create a folder "1.0.0" and then copy the file with "FileName.psd1"
What it did was creating a file with the name "1.0.0" first and then when trying to copy the file it gave the error [Errno 2] No such file or directory.

![image](https://user-images.githubusercontent.com/52011872/109716599-ee954d80-7b59-11eb-8176-ee863bc39b47.png)

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @abhi-msft, may I know your azure cli version used? could you provide debug information with `--debug` in your command?
I cannot reproduce your issue. As you can see, I could download with a new folder `1.0.0` created:
![image](https://user-images.githubusercontent.com/49508232/109749558-dd117b80-7c15-11eb-9613-cc728f0a7689.png)

**Comment by abhi-msft** [comment]
To clarify, it is not working when a dot is present in subfolder name.
Try with 1.0.0 as a subfolder but not parent.
So, you could try either
- adding a folder under 1.0.0 like "1.1.1" with test.txt.
- Adding a parent folder to 1.0.0 and try downloading that. ex: test/1.0.0

**Comment by Juliehzl** [comment]
discussed with @abhi-msft online. His account is ADLS Gen2 account. 1.0.0 is a folder with empty size and `blob download-batch` cannot download such resource correctly.

**Comment by kaburkett** [comment]
I too faced this problem when using ADLS Gen2 storage. I got around the problem by downloading only files (not folders) by matching *.* .... here is an example of how I fixed this issue:

```
az storage blob download-batch --source CONTAINERNAME --destination C:/FILEPATH/DIR/ --pattern subdirectory1/subdirectory2/2021.08.01.1/*.* --account-name ACCOUNTNAME --account-key XXXXXXXXXXX
```

For me, this retrieved every file and folder inside of the directory 2021.08.01.1 and placed them in subdirectories matching the container exactly.

**Comment by Juliehzl** [comment]
> I too faced this problem when using ADLS Gen2 storage. I got around the problem by downloading only files (not folders, as I found it will make those automatically by path) by matching `*.*` .... here is an example of how I fixed this issue:
> 
> `az storage blob download-batch --source CONTAINERNAME --destination C:/FILEPATH/DIR/ --pattern subdirectory1/subdirectory2/2021.08.01.1/*.* --account-name ACCOUNTNAME --account-key XXXXXXXXXXX`
> 
> For me, this retrieved every file and folder inside of the directory 2021.08.01.1 and placed them in subdirectories matching the container exactly.
For ADLS Gen2 account, you could use `az storage fs directory download` to download folders, which could process empty sub-folder as expected. If you don't find the command, please upgrade to latest azure cli.

**Comment by kaburkett** [comment]
Thanks @Juliehzl for linking this. As a user I am struggling to find any documentation on --file-system parameter. I see 'File Shares' and 'File Service' in storage account config but I am only working with Blob Storage... similar to the poster of this bug. I am wondering if 'File System' parameter is requiring either a File Service or File Share- or maybe all three are the same thing with different names. It's a little confusing and I havent found anything on the topic yet.

**Comment by kaburkett** [comment]
To me, this does still seem like a bug for even non-gpv2 users though, because, the folder/directory does not need to be empty to fail.. mine is full of great things but still fails when using as directed in usage guide.
