### ISSUE TITLE
distutils.version.LooseVersion should be replaced by packaging.version.Version

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#17170]
**Is your feature request related to a problem? Please describe.**

As pointed out by https://github.com/Azure/azure-cli-extensions/pull/2987#discussion_r572827296,  `distutils.version.LooseVersion` is legacy and conformant only to the superseded [PEP 386](https://www.python.org/dev/peps/pep-0386/) (by [PEP 440](https://www.python.org/dev/peps/pep-0440/)).

In edge build, the version is `2.20.0.post20210302071300`, which causes a failure at 

https://github.com/Azure/azure-cli/blob/b2c8e710170fe9141f81246edc4ffa5e84bdc3ef/src/azure-cli-core/azure/cli/core/util.py#L1179

```
'<' not supported between instances of 'int' and 'str'
```

because `post` is not a supported versioning convention of `distutils.version.LooseVersion`.

**Describe the solution you'd like**

We should migrate to [`packaging.version.Version`](https://packaging.pypa.io/en/latest/version.html#packaging.version.Version).

**Comment by yonzhan** [comment]
distutils related issue

**Comment by PARADISSEEKR** [comment]
How to reproduce this error.
