### ISSUE TITLE
Can't disable error recommendations

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#17175]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az config set error_recommendations=off does not disable recommendations

**To Reproduce**

![image](https://user-images.githubusercontent.com/30876406/109690183-eed22080-7b3a-11eb-8cdc-68e88ce13f9c.png)

Also tried the previous config but also didn't work
![image](https://user-images.githubusercontent.com/30876406/109690791-8fc0db80-7b3b-11eb-86ab-e6072d6d3d4d.png)

**Expected behavior**
Recommendations could be turned off

**Environment summary**

![image](https://user-images.githubusercontent.com/30876406/109690219-fc87a600-7b3a-11eb-911a-ef8b519ff4b4.png)

**Additional context**
Timeline --- this feature will be part of LEARN TV demo on the 9th 

On a similar note, configuring things shouldn't be this difficult....
For instance, the following should be accepted even though there's a space between the name & value...
![image](https://user-images.githubusercontent.com/30876406/109690568-55efd500-7b3b-11eb-857d-02903cf508a7.png)

Another example... when command is misspelled, there should be indication that it hasn't gone through
Else people will hit the same error over and over again...
![image](https://user-images.githubusercontent.com/30876406/109690703-7ae44800-7b3b-11eb-89d4-f87210560930.png)

**Comment by yungezz** [comment]
hi @houk-ms , could you pls have a look? thakns

**Comment by houk-ms** [comment]
Hi @chenlomis , we should use `az config set error_recommendation=off` not  `az config set error_recommendations=off`.

Just close the issue now.
