### ISSUE TITLE
az aks get-credentials --resource-group xxx --name xxx throwing  an unexpected error

### ISSUE THREAD

**Issue by nareshkhatiwada** [Azure/azure-cli#17174]
## Describe the bug
**Command Name**
`az aks get-credentials --resource-group xxx --name xxx`

**Errors:**
```
The version of cryptography does not match the loaded shared object. This can happen if you have multiple copies of cryptography installed in your Python path. Please try creating a new virtual environment to resolve this issue. Loaded python version: 3.3.2, shared object version: b'2.8'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py, ln 233, in invoke
cli\core\commands\__init__.py, ln 559, in execute
azure\cli\core\__init__.py, ln 502, in load_arguments
cli\core\commands\__init__.py, ln 316, in load_arguments
...
hazmat\bindings\openssl\binding.py, ln 165, in _verify_package_version
ImportError: The version of cryptography does not match the loaded shared object. This can happen if you have multiple copies of cryptography installed in your Python path. Please try creating a new virtual environment to resolve this issue. Loaded python version: 3.3.2, shared object version: b'2.8'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.20.0

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by RakeshMohanMSFT** [comment]
This is working. Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)

`az aks get-credentials -g Issue16932 -n Issue16932cluster`
The behavior of this command has been altered by the following extension: aks-preview
Merged "Issue16932cluster" as current context in C:\Users\user\.kube\config
