### ISSUE TITLE
az storage endpoint not available for AzureCLI 2.20.0 in Azure Goverment

### ISSUE THREAD

**Issue by Quintinon** [Azure/azure-cli#17189]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Attempting to use the `az storage` command with location usgovvirginia fails with the following error:
```ERROR: (NoRegisteredProviderFound) No registered resource provider found for location 'usgovvirginia' and API version '2021-01-01' for type 'storageAccounts'. The supported api-versions are '2020-08-01-preview, 2019-06-01, 2019-04-01, 2018-11-01, 2018-07-01, 2018-03-01-preview, 2018-02-01, 2017-10-01, 2017-06-01, 2016-12-01, 2016-07-01, 2016-05-01, 2016-01-01, 2015-06-15, 2015-05-01-preview'. The supported locations are 'usgoviowa, usgovvirginia, usgovtexas, usgovarizona, usdodeast, usdodcentral'.```

**To Reproduce**
Install AzureCLI 2.20.0 (currently the latest)
Run command `az storage account create -g <Resource> -n <Name> -l usgovvirginia --sku Standard_LRS`

**Expected behavior**
The azure storage account to be created and no error produced.

**Environment summary**
AzureCLI was installed manually through MSI file downloaded from https://aka.ms/installazurecliwindows
`az storage` command was run through Azure DevOps Release using Azure CLI task version 2.1.0

**Additional context**
Uninstalling AzureCLI 2.20.0 and installing 2.19.1 allows my command to function with no changes.

**Comment by yonzhan** [comment]
storage

**Comment by ps23** [comment]
Confirmed, have the same issue in all our Azure Devops pipelines using the public agents, ADO have just updated to 2.20.0. Workaround in the pipeline:

pool:
  vmImage: ubuntu-18.04
  
```
sudo apt install -y --allow-downgrades azure-cli=2.19.1-1~bionic
```

**Comment by Juliehzl** [comment]
There is an issue in service side with api 2021-01-01. The same as https://github.com/Azure/azure-powershell/issues/14395.
Currently please downgrade to previous version as a workaround.

**Comment by sachinjoseph** [comment]
We ran into the same issue last day. We had to pin our Az CLI to 2.19.1 to get it working again:

```yaml
pool:
  vmImage: ubuntu-20.04
strategy:
  runOnce:
    deploy:
      steps:
        - bash: |
            sudo apt install -y --allow-downgrades azure-cli=2.19.1-1~focal
```

cc @D4N14L

**Comment by RKSelvi** [comment]
Same here, we had to downgrade Cli to make it work in GitHub actions,

uses: azure/CLI@v1
      with:
        azcliversion: 2.19.1
        inlineScript: |

**Comment by johnnyyuelee008** [comment]
we have the same issue in Azure china cloud.

**Comment by Juliehzl** [comment]
As mentioned in https://github.com/Azure/azure-powershell/issues/14395#issuecomment-804596969, the issue is resolved now.
