### ISSUE TITLE
[DNS] Record set list doesn't display type name by default

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1718]
It would be useful if the default table output of the `az network dns record-set list` command displayed the type (e.g. `CNAME`). As it stands now, there isn't a way to easily differentiate between two record sets that share the same name but different type.

Additionally, since the type is a required parameter for the update/delete/show commands for a record set instance, it seemingly represents a key part of the record set's identity, and would useful to be able to easily retrieve without requiring the use of a custom format/query.

**Comment by tjprescott** [comment]
Since the type is a required parameter, why would you want it returned in the output since you know what the type must be for all the output records?

**Comment by jtuliani** [comment]
When listing record sets, the type should be optional.  I.e. you can list record sets of a specific type, or you can omit the type and list all record sets regardless of type.

The latter is the most common mode of operation.  And it makes total sense that the record set list therefore contains the record set type.

**Comment by lostintangent** [comment]
@tjprescott The record set type isn't a required parameter of the `az network dns record-set list`command. However, it is a required parameter of the other record set CRUD commands, which is why I was proposing that it would be valuable to display by default in via the `list` command, in addition to the disambiguation value it would provide.
