### ISSUE TITLE
Zones availability --node-zones 1 2 3

### ISSUE THREAD

**Issue by NirajCricket** [Azure/azure-cli#17184]
the command az aks nodepool add --cluster-name

                    **[--node-zones {1, 2, 3}]** is not correct, it throws errror, it should be 

                    [--zones 1 2 3 ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fce7ab-ab56-44c6-b9a8-405444247a0b
* Version Independent ID: dabbb6c6-c616-a6ec-61f6-1b9d3bb069e8
* Content: [az aks nodepool](https://docs.microsoft.com/en-US/cli/azure/aks/nodepool?view=azure-cli-latest#az_aks_nodepool_update)
* Content Source: [latest/docs-ref-autogen/aks/nodepool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/aks/nodepool.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by RakeshMohanMSFT** [comment]
@NirajCricket This is fixed 
`az aks nodepool add --cluster-name issue16961cluster -g issue16961 -n issue16961pool -z 5`
az aks nodepool add: '5' is not a valid value for '--zones'. Allowed values: 1, 2, 3.
