### ISSUE TITLE
Incorrect param for recommendations

### ISSUE THREAD

**Issue by chenlomis** [Azure/azure-cli#17188]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

![image](https://user-images.githubusercontent.com/30876406/109861294-03361c00-7c14-11eb-9239-684a8783cdc2.png)

I believe --resource-group param should be --name 

**To Reproduce**
see above

**Expected behavior**
see above

**Environment summary**

**Additional context**
n/a

**Comment by yonzhan** [comment]
ARM

**Comment by RakeshMohanMSFT** [comment]
@chenlomis The command `az group delete` expects the -n param to delete a group.
