### ISSUE TITLE
[DNS] Could record sets be implicitly created when adding new records?

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1719]
I may be missing something, but it doesn't seem like the `az network dns record <TYPE> add` commands allow implicitly creating a record set if it doesn't already exist. [This behavior](https://docs.microsoft.com/en-us/azure/dns/dns-operations-recordsets-cli#create-a-dns-record) existed in the previous xplat CLI, and would help simplify the experience for common cases where there aren't multiple records in a zone with the same type and name.

Right now, you'd have to run `az network dns record-set create`, and then go create your actual record, which feels a little heavy weight for simple scenarios.

**Comment by tjprescott** [comment]
Great suggestion @lostintangent!

**Comment by jtuliani** [comment]
Yes.  The Azure CLI1.0 supports this--using azure network dns record-set add-record will create the record-set for you if it doesn't exist.

We have made recent improvements in CLI1.0 relating to how add-record can be used to overwrite existing CNAMEs, and how delete-record either does or doesn't delete empty record sets (these changes will ship later in Jan).  We should do the same in CLI2.0
