### ISSUE TITLE
can't create service principle at Dogfood with AADSTS500011 error

### ISSUE THREAD

**Issue by azurepeterli** [Azure/azure-cli#17209]
Hi, I'm trying to create a service principle at Dogfood, but got AADSTS500011 error. Please help taking a look, is there any step or settings missing? Thanks!

MacBook-Pro:arcplatform peterl$ az ad sp create-for-rbac --skip-assignment
AADSTS500011: The resource principal named https://graph.windows-ppe.net/ was not found in the tenant named f686d426-8d16-42db-81b7-ab578e110ccd. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 224c5acb-47c7-47e3-bb7e-173bf4770100
Correlation ID: 1f4a2938-8aa5-4669-85f5-24ba1896eec1
Timestamp: 2021-03-04 17:14:32Z
MacBook-Pro:arcplatform peterl$ az account show
{
  "environmentName": "Dogfood",
  "homeTenantId": "f686d426-8d16-42db-81b7-ab578e110ccd",
  "id": "a9485996-20ca-4e84-8f8c-decb5087323e",
  "isDefault": true,
  "managedByTenants": [],
  "name": "Arc Platform/Custom Location- Dogfood",
  "state": "Enabled",
  "tenantId": "f686d426-8d16-42db-81b7-ab578e110ccd",
  "user": {
    "name": "PETLI@microsoft.com",
    "type": "user"
  }
}
MacBook-Pro:arcplatform peterl$ az cloud show
{
  "endpoints": {
    "activeDirectory": "https://login.windows-ppe.net/",
    "activeDirectoryDataLakeResourceId": null,
    "activeDirectoryGraphResourceId": "https://graph.windows-ppe.net/",
    "activeDirectoryResourceId": "https://management.core.windows.net/",
    "appInsightsResourceId": null,
    "appInsightsTelemetryChannelResourceId": null,
    "attestationResourceId": null,
    "batchResourceId": null,
    "gallery": "https://df.gallery.azure-test.net/",
    "logAnalyticsResourceId": null,
    "management": "https://api-dogfood.resources.windows-int.net/",
    "mediaResourceId": null,
    "microsoftGraphResourceId": null,
    "ossrdbmsResourceId": null,
    "portal": null,
    "resourceManager": "https://api-dogfood.resources.windows-int.net/",
    "sqlManagement": null,
    "synapseAnalyticsResourceId": null,
    "vmImageAliasDoc": null
  },
  "isActive": true,
  "name": "Dogfood",
  "profile": "latest",
  "suffixes": {
    "acrLoginServerEndpoint": null,
    "attestationEndpoint": null,
    "azureDatalakeAnalyticsCatalogAndJobEndpoint": null,
    "azureDatalakeStoreFileSystemEndpoint": null,
    "keyvaultDns": null,
    "mariadbServerEndpoint": null,
    "mhsmDns": null,
    "mysqlServerEndpoint": null,
    "postgresqlServerEndpoint": null,
    "sqlServerHostname": null,
    "storageEndpoint": null,
    "storageSyncEndpoint": null,
    "synapseAnalyticsEndpoint": null
  }
}

**Resource Provider**

Custom Location
Microsoft.ExtendedLocation

**Description of Feature or Work Requested**

I'm following this document to create a custom location resource, 
https://msazure.visualstudio.com/AzureArcPlatform/_wiki/wikis/AzureArcAppliance.wiki/76580/Create-CustomLocation-in-Dogfood

**Minimum API Version Required**

N/A

**Swagger Link**

N/A

**Target Date**

N/A

**Comment by azurepeterli** [comment]
Leis-MacBook-Pro:arcplatform peterl$ az ad sp create-for-rbac --skip-assignment --debug
Command arguments: ['ad', 'sp', 'create-for-rbac', '--skip-assignment', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x108be9550>, <function OutputProducer.on_global_arguments at 0x108c535e0>, <function CLIQuery.on_global_arguments at 0x108c98dc0>]
Event: CommandInvoker.OnPreCommandTableCreate []
Modules found from index for 'ad': ['azure.cli.command_modules.role']
Loading command modules:
Name                  Load Time    Groups  Commands
role                      0.009        17        61
Total (1)                 0.009        17        61
These extensions are not installed and will be skipped: ['azext_ai_examples']
Loading extensions:
Name                  Load Time    Groups  Commands  Directory
Total (0)                 0.000         0         0
Loaded 17 groups, 61 commands.
Found a match in the command table.
Raw command  : ad sp create-for-rbac
Command table: ad sp create
remaining    :              for-rbac
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x1091c7790>]
az_command_data_logger : command args: ad sp create-for-rbac --skip-assignment --debug
metadata file logging enabled - writing logs to '/Users/peterl/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x1091f6f70>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x109252c10>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x109252ca0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x109252dc0>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x108c53670>, <function CLIQuery.handle_query_parameter at 0x108c98e50>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x109252310>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x109252d30>]
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
Adding custom headers to the client:
    'x-ms-client-request-id': '2e1725ae-7d0e-11eb-b3de-acde48001122'
    'CommandName': 'ad sp create-for-rbac'
    'ParameterSetName': '--skip-assignment --debug'
Getting management service client client_type=AuthorizationManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
Adding custom headers to the client:
    'x-ms-client-request-id': '2e1725ae-7d0e-11eb-b3de-acde48001122'
    'CommandName': 'ad sp create-for-rbac'
    'ParameterSetName': '--skip-assignment --debug'
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
Adding custom headers to the client:
    'x-ms-client-request-id': '2e1725ae-7d0e-11eb-b3de-acde48001122'
    'CommandName': 'ad sp create-for-rbac'
    'ParameterSetName': '--skip-assignment --debug'
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
Adding custom headers to the client:
    'x-ms-client-request-id': '2e1725ae-7d0e-11eb-b3de-acde48001122'
    'CommandName': 'ad sp create-for-rbac'
    'ParameterSetName': '--skip-assignment --debug'
msrest.async_paging : Paging async iterator protocol is not available for ApplicationPaged
AdalAuthentication.signed_session invoked by Track 1 SDK
Retrieving token from ADAL for resource 'https://graph.windows-ppe.net/'
attempting to read file /Users/peterl/.azure/accessTokens.json as utf-8-sig
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - Authority:Performing instance discovery: ...
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - Authority:Performing static instance discovery
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - Authority:Attempting instance discover at: https://login.microsoftonline.com/common/discovery/instance?authorization_endpoint=https%3A%2F%2Flogin.windows-ppe.net%2Ff686d426-8d16-42db-81b7-ab578e110ccd%2Foauth2%2Fauthorize&api-version=1.0
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool : https://login.microsoftonline.com:443 "GET /common/discovery/instance?authorization_endpoint=https%3A%2F%2Flogin.windows-ppe.net%2Ff686d426-8d16-42db-81b7-ab578e110ccd%2Foauth2%2Fauthorize&api-version=1.0 HTTP/1.1" 200 131
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - Authority:Instance Discovery Server returned this correlation_id: 4fded3c9-8da2-4d0f-989f-ac0fff15040a
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - CacheDriver:Found 2 potential entries.
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - CacheDriver:No resource specific cache entries found.
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - CacheDriver:Found an MRRT token.
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - CacheDriver:Returning token from cache lookup, AccessTokenId: b'utXCs76f7Vk8AdG/Cq2ILa9YlhxJUL+SVUXo0EWF3k4=', RefreshTokenId: b'yz/hFXH5x8qhJbSLMwFT66P91+/kwCU+yuoEI+kM0i8='
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - CacheDriver:Acquiring new access token from MRRT token.
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - TokenRequest:called to refresh a token from the cache
adal-python : 4fded3c9-8da2-4d0f-989f-ac0fff15040a - TokenRequest:Getting a new token from a refresh token
urllib3.connectionpool : Starting new HTTPS connection (1): login.windows-ppe.net:443
urllib3.connectionpool : https://login.windows-ppe.net:443 "POST /f686d426-8d16-42db-81b7-ab578e110ccd/oauth2/token HTTP/1.1" 400 768
azure.cli.core.util.handle_exception is called with an exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/adal_authentication.py", line 38, in _get_token
    scheme, token, full_token = self._token_retriever(sdk_resource)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 587, in _retrieve_token
    return self._creds_cache.retrieve_token_for_user(username_or_sp_id,
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 1065, in retrieve_token_for_user
    token_entry = context.acquire_token(resource, username, _CLIENT_ID)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/adal/authentication_context.py", line 145, in acquire_token
    return self._acquire_token(token_func)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/adal/authentication_context.py", line 143, in token_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/adal/token_request.py", line 347, in get_token_from_cache_with_refresh
    return self._find_token_from_cache()
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/adal/token_request.py", line 127, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/adal/cache_driver.py", line 198, in find
    return self._refresh_entry_if_necessary(entry,
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/adal/cache_driver.py", line 184, in _refresh_entry_if_necessary
    return self._acquire_new_token_from_mrrt(entry)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/adal/cache_driver.py", line 160, in _acquire_new_token_from_mrrt
    token_response = self._refresh_function(entry, self._resource)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/adal/token_request.py", line 137, in _get_token_with_token_response
    return self._get_token_with_refresh_token(refresh_token, resource, None)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/adal/token_request.py", line 339, in _get_token_with_refresh_token
    return self._oauth_get_token(oauth_parameters)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/adal/token_request.py", line 112, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/adal/oauth2_client.py", line 289, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://graph.windows-ppe.net/ was not found in the tenant named f686d426-8d16-42db-81b7-ab578e110ccd. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 77db15f3-d05a-49a5-bad5-4e08277f0000\r\nCorrelation ID: 4fded3c9-8da2-4d0f-989f-ac0fff15040a\r\nTimestamp: 2021-03-04 17:22:23Z","error_codes":[500011],"timestamp":"2021-03-04 17:22:23Z","trace_id":"77db15f3-d05a-49a5-bad5-4e08277f0000","correlation_id":"4fded3c9-8da2-4d0f-989f-ac0fff15040a","error_uri":"https://login.windows-ppe.net/error?code=500011"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 714, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/role/commands.py", line 69, in graph_err_handler
    raise ex
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/role/custom.py", line 1456, in create_service_principal_for_rbac
    aad_application = create_application(cmd,
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/role/custom.py", line 808, in create_application
    existing_apps = [x for x in existing_apps if set(identifier_uris).issubset(set(x.identifier_uris))]
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/role/custom.py", line 808, in <listcomp>
    existing_apps = [x for x in existing_apps if set(identifier_uris).issubset(set(x.identifier_uris))]
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/graphrbac/operations/applications_operations.py", line 155, in internal_paging
    response = self._client.send(request, stream=False, **operation_config)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 65, in send
    self._creds.signed_session(session)
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/adal_authentication.py", line 137, in signed_session
    scheme, token, _, external_tenant_tokens = self._get_token()
  File "/usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/core/adal_authentication.py", line 63, in _get_token
    raise CLIError(err)
knack.util.CLIError: AADSTS500011: The resource principal named https://graph.windows-ppe.net/ was not found in the tenant named f686d426-8d16-42db-81b7-ab578e110ccd. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 77db15f3-d05a-49a5-bad5-4e08277f0000
Correlation ID: 4fded3c9-8da2-4d0f-989f-ac0fff15040a
Timestamp: 2021-03-04 17:22:23Z

cli.azure.cli.core.azclierror : AADSTS500011: The resource principal named https://graph.windows-ppe.net/ was not found in the tenant named f686d426-8d16-42db-81b7-ab578e110ccd. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 77db15f3-d05a-49a5-bad5-4e08277f0000
Correlation ID: 4fded3c9-8da2-4d0f-989f-ac0fff15040a
Timestamp: 2021-03-04 17:22:23Z
AADSTS500011: The resource principal named https://graph.windows-ppe.net/ was not found in the tenant named f686d426-8d16-42db-81b7-ab578e110ccd. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 77db15f3-d05a-49a5-bad5-4e08277f0000
Correlation ID: 4fded3c9-8da2-4d0f-989f-ac0fff15040a
Timestamp: 2021-03-04 17:22:23Z
Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x1091c79d0>]
az_command_data_logger : exit code: 1
Command ran in 1.405 seconds (init: 0.154, invoke: 1.251)
telemetry.save : Save telemetry record of length 3498 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "/usr/local/Cellar/azure-cli/2.17.1/libexec/bin/python /usr/local/Cellar/azure-cli/2.17.1/libexec/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py /Users/peterl/.azure"
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.

**Comment by yonzhan** [comment]
Graph

**Comment by jiasli** [comment]
The error message has shown the root cause:

```
AADSTS500011: The resource principal named https://graph.windows-ppe.net/ was not found in the tenant named 
f686d426-8d16-42db-81b7-ab578e110ccd. This can happen if the application has not been installed by the 
administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication 
request to the wrong tenant.
```

This is because `https://graph.windows-ppe.net/` is not the valid Active Directory Graph resource ID (URL) in Dogfood environment. I tried to visit it in a browser and also got `DNS_PROBE_STARTED`.

### TODO

Please follow with your team to get the correct Active Directory Graph resource ID in Dogfood environment.

### Additional context

The substitution of Active Directory Graph `https://graph.windows-ppe.net/` is Microsoft Graph `https://graph.microsoft-ppe.com/`, but Azure CLI `az ad` command group only works on Active Directory Graph.

If Active Directory Graph `https://graph.windows-ppe.net/` has really been deprecated, using `az rest` to call [Microsoft Graph API](https://docs.microsoft.com/en-us/graph/use-the-api) `https://graph.microsoft-ppe.com/` is currently the only working approach. 

More detail on calling Microsoft Graph API with `az rest` and examples: https://github.com/Azure/azure-cli/issues/12946

**Comment by azurepeterli** [comment]
Thanks Jiashuo for the response and meeting. I will figure out the correct Active Directory Graph resource ID. And, after the meeting with you, I realized in our e2e test, we actually use an existing SP, that can be a workaround for me (reuse that SP for my work).  Thanks again!

**Comment by azurepeterli** [comment]
Hi Jiashuo, you're right, I switched to the correct one, https://graph.ppe.windows.net/, the error is gone. (There is another one though, I may open a separate support ticket if necessary).

Thanks for the help!
