### ISSUE TITLE
WebApp:Python Error when creating webapp with az

### ISSUE THREAD

**Issue by TonyWu3027** [Azure/azure-cli#17204]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
[Errno 2] No such file or directory: '/Users/tonywu/ChromeDebugAdapter.csproj'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 660, in execute
    raise ex
cli/core/commands/__init__.py, ln 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 715, in _run_job
    return cmd_copy.exception_handler(ex)
cli/command_modules/appservice/commands.py, ln 37, in _ex_handler
    raise ex
...
cli/command_modules/appservice/_create_util.py, ln 193, in detect_dotnet_lang
    parsed_file = ET.parse(csproj_path)
python3.8/xml/etree/ElementTree.py, ln 1202, in parse
    tree.parse(source, parser)
python3.8/xml/etree/ElementTree.py, ln 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tonywu/ChromeDebugAdapter.csproj'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --sku {} --name {}`

## Environment Summary
```
macOS-11.2.1-x86_64-i386-64bit
Python 3.8.8
Installer: HOMEBREW

azure-cli 2.20.0

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by calvinsID** [comment]
Hi @TonyWu3027 , are you running the command in your project directory, and can confirm that ChromeDebugAdapter.csproj exists in there?

**Comment by TonyWu3027** [comment]
Hi @calvinsID, sorry for the late reply. I was following an Azure tutorial to deploy a Flask app and I forgot to `cd` into project directory. Thanks for the help. I wonder if there can be any prompt or warning implemented to handle such errors? The error report seems confusing. But thanks!
