### ISSUE TITLE
webapp:az webapp log config level always defaults to verbose

### ISSUE THREAD

**Issue by juanfergc** [Azure/azure-cli#17207]
When I enter this command:

az webapp log config -n myapp --resource-group myrg --application-logging filesystem --level **information**

I get this:

{
  "applicationLogs": {
    "azureBlobStorage": {
      "level": "Off",
      "retentionInDays": 3,
      "sasUrl": null
    },
    "azureTableStorage": {
      "level": "Off",
      "sasUrl": null
    },
    "fileSystem": {
      "level": "**Verbose**"
    }
  },
[see screenshot](https://imgur.com/a/nPtjiJa)

How can I set the level to a different value for application logging (filesystem)? No matter what, it is always defaulting to Verbose

By using the UI, we can set the level for "Application Logging (Filesystem)" and "Application Logging (Blob)" independently, but the cli, has just one parameter fot both, maybe it needs to be update to reflect this new feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bee2e287-5fb7-a849-9d3b-87013b783f16
* Version Independent ID: 97f9e1c4-1573-b776-0fce-53c65839d713
* Content: [az webapp log](https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#az_webapp_log_config)
* Content Source: [latest/docs-ref-autogen/webapp/log.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/log.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
Able to repro this issue. working on fix.
