### ISSUE TITLE
webapp: Hostname does not exist error on ssl bind

### ISSUE THREAD

**Issue by pjboardman** [Azure/azure-cli#17219]
## Describe the bug
Starting in 2.20.0, this started throwing errors. (was working in <=2.19). Note that this is for a situation where the app service & app service plan are in different resource groups. 

What is happening is that we are trying to bind an ssl cert to app service with cname of ABC, but instead we get an error that an unrelated hostname (XYZ) does not exist (It actually does exist, making this a doubly-fun error).

It looks like something in `az webapp config ssl bind` is using the *last* ssl cert in the list rather than the one that corresponds to the given app service / cert thumprint. (If I run `az webapp config ssl list`, the hostname XYZ that appears in the error is the last in the list.)

**Command Name**
`az webapp config ssl bind`

**Errors:**
```
Hostname 'XYZ.domain.com' does not exist.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Here is how the certificate thumprint is selected:

APP_FQDN=ABC.domain.com

`THUMBPRINT=$(az webapp config ssl list -g $PLAN_RESOURCE_GROUP --query "[?name=='$APP_FQDN'].thumbprint | [0]")`

and here is the command that errors:
`az webapp config ssl bind --resource-group $RESOURCE_GROUP --name $APP_SERVICE --certificate-thumbprint $THUMBPRINT --ssl-type SNI`

Same results if the `--ids` arg is used instead.

## Expected Behavior
Was working in 2.19

## Environment Summary

Note, this is also occurring in multiple Azure DevOps pipelines (just started recently)

```
macOS-10.13.6-x86_64-i386-64bit
Python 3.8.8
Installer: HOMEBREW

azure-cli 2.20.0

Extensions:
front-door 1.0.11
aks-preview 0.5.4
webapp 0.3.1
application-insights 0.1.13

```

**Comment by yonzhan** [comment]
webapp

**Comment by YohanSciubukgian** [comment]
2.20.0 return success but it doesn't bind the certificate on the webapp.
I have downgraded to 2.19.1 and it's working properly.

**Comment by devsh4** [comment]
This issue also happens if both the app service plan & app service are in the **same resource group**. This seems to be happening due to a recent change in 2.20.0 version.

Tried with version 2.19.0 and it worked perfectly fine.

**Comment by devsh4** [comment]
Please escalate this issue accordingly as there is no workaround to bypass this error, using --name or --ids doesn't work.

If working locally, one can downgrade to 2.19.1 and resolve it but there is no workaround for Azure DevOps as we can't specify a version for the `AzureCLI` task.

**Comment by coelho5br** [comment]
@panchagnula 
We got some cases related to this

**Comment by panchagnula** [comment]
@calvinsID can you take a look at this especially since this states that this is a regression from this change https://github.com/Azure/azure-cli/pull/16778

**Comment by mpowrie** [comment]
> @calvinsID can you take a look at this especially since this states that this is a regression from this change #16778

I got this same error with az cli version 2.21, suggesting that the issue is not fixed.
![image](https://user-images.githubusercontent.com/323814/114059186-74ce4d80-98d7-11eb-8bfc-20b95753116d.png)

**Comment by calvinsID** [comment]
@mpowrie the fix should be in the next version, which will be on cloud shell 04/09 and officially released 04/13. Can you please try again with the updated version once its out? sorry for the inconvenience

**Comment by mpowrie** [comment]
Thanks @calvinsID will do.
