### ISSUE TITLE
Improve error handling for az --upgrade

### ISSUE THREAD

**Issue by nigarfin** [Azure/azure-cli#17213]
**Is your feature request related to a problem? Please describe.**

When I used `az --upgrade`, I got an error that I was missing an arg "_command_package"

![image](https://user-images.githubusercontent.com/37638436/110066592-af682780-7d26-11eb-891d-74188fc4092e.png)

**Describe the solution you'd like**

I would have expected a error message telling me to not use the dashes.

**Describe alternatives you've considered**

It maybe can just work, we are probably pretty confident that if someone types az --upgrade they probably mean az upgrade. Can we set an alias for az --upgrade to mirror the functionality of az upgrade?

**Additional context**

**Comment by yungezz** [comment]
thanks for reporting the issue, we'll look at it

**Comment by RakeshMohanMSFT** [comment]
@nigarfin `az upgrade` should do the work. Let me know if its not what you are looking for.

**Comment by jiasli** [comment]
Tracked by #19592
