### ISSUE TITLE
How can I update my Azure CLI for my pipeline?

### ISSUE THREAD

**Issue by j-hudgins** [Azure/azure-cli#17218]
**Resource Provider**

Azure Cloud

**Description of Feature or Work Requested**

There was a bug introduced in Azure CLI v 2.19.1 * but I run off of the Azure Cloud so I in the documentation  az upgrade` isn't supported. How can I get access to Azure CLI v 2.20.0?

**Minimum API Version Required**

**Swagger Link**

**Target Date**

ASAP- my pipelines have been broken all week as a result.

**Comment by yungezz** [comment]
hi @fengzhou-msft, could  you pls help on this?

**Comment by fengzhou-msft** [comment]
@j-hudgins what agent do you use, Ubuntu or windows?

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please feel free to open new issues if the latest Azure CLI still does not work for you.
