### ISSUE TITLE
az storage blob upload-batch --destination-path website documentation seems incorrect

### ISSUE THREAD

**Issue by dsherret** [Azure/azure-cli#17220]
The help text in the app says:

> The directory where the source data is copied to. If omitted, data is copied to the root directory.

https://github.com/Azure/azure-cli/blob/aa0155ea7bfa8aa4c9a372e022621a7247003c41/src/azure-cli/azure/cli/command_modules/storage/_help.py#L1661

However, the website says "appended":

> The destination path that will be appended to the blob name.

It should probably say "prepended".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/blob.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/blob.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage
