### ISSUE TITLE
linux installation doesn't allow `azure-cli` to be installed at a specified directory. 

### ISSUE THREAD

**Issue by jade2k11598** [Azure/azure-cli#17221]
**Describe the bug**
I downloaded azure-cli_bionic_all.deb and installed it on a specific directory (e.g. `dpkg-deb --extract azure-cli_bionic_all.deb <specific-directory>` since I didn't want to install it on default directory `/usr`.  So looking at the specified directory, I see it installed the following directories:
```
~/bin/azure$ ls
etc  opt  usr
```
But when triggering the `az` script in the `usr/bin` I get this error: 
```
~/bin/azure/usr/bin$ ./az --version
./az: line 2: /opt/az/bin/python3: No such file or directory
```

Looking at the script`az`:
```
#!/usr/bin/env bash
AZ_INSTALLER=DEB /opt/az/bin/python3 -Im azure.cli "$@"
```
This assumes that the azure-cli will be always installed at the top directory (e.g. `/`).  That's not ideal.  The script should work such that one can install azure-cli to whatever desired directory the user decides.  Looking at the layout of the installation, it might be ideal to update the `az` script to:
```
#!/usr/bin/env bash
AZ_INSTALLER=DEB ${PWD}/../../opt/az/bin/python3 -Im azure.cli "$@"
```
This should work regardless of where azure-cli is installed at.

**To Reproduce**
Install the  azure.cli to a specific directory (e.g. `dpkg-deb --extract azure-cli_bionic_all.deb <specific-directory>`) then run the `az` script

**Expected behavior**
Should not get error `./az: line 2: /opt/az/bin/python3: No such file or directory` when trigger the `az` script in `usr/bin`

**Environment summary**
This was installed on Ubuntu 18.04, using `dpkg-deb` (see above) and shell is BASH.

az version is:
```
azure-cli                         2.19.1 *

core                              2.19.1 *
telemetry                          1.0.6
```

**Comment by yungezz** [comment]
hi @fengzhou-msft could you have a look? thanks
