### ISSUE TITLE
UserData for VM and VM ScaleSets (high priority) 

### ISSUE THREAD

**Issue by roipmsft** [Azure/azure-cli#17223]
**Resource Provider**

Compute Resource Provider
**Description of Feature or Work Requested**

https://microsoft.sharepoint.com/:w:/r/teams/ComputeVM/_layouts/15/Doc.aspx?sourcedoc=%7B13AE3881-1B63-4D2E-9334-71E687A4A61D%7D&file=UserDataRequirementsForCLI.docx&action=default&mobileredirect=true
This new UserData feature is essentially a new and improved version of the existing CustomData(https://docs.microsoft.com/en-us/azure/virtual-machines/custom-data). We are trying to catch up with AWS, which already has this feature.
**Minimum API Version Required**

2021-03-01
**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/13220
**Target Date**

We would like to GA on April 30.
This new feature is for Gartner and we are on a tight deadline.

**Comment by yungezz** [comment]
hi @qwordy,  let's check the availability of 2021-03-01 API version and SDK release ETA, then communicate back on CLI plan.

**Comment by qwordy** [comment]
@roipmsft When will the 2021-03-01 API be merged into master branch?

**Comment by roipmsft** [comment]
Api version for 2021-03-01 is already available for CRP in all regions.

UserData for regular VMs is currently rolling out.
UserData for VMSS is not done yet and may not being rolling out until week of April 5.

Swagger PR for UserData (for both VM and VMSS) may not finish until week of April 12, unfortunately.

**Comment by yungezz** [comment]
hi @roipmsft , Swagger change https://github.com/Azure/azure-rest-api-specs/pull/13220#pullrequestreview-633218158 need to be checked in firstly as prerequisite for Azure CLI work. The workflow is: Swagger merged into master -> Python SDK released -> Azure CLI development and release(Azure CLI depends on Python SDK)

**Comment by zhoxing-ms** [comment]
@roipmsft Hi, I would like to ask what is the expected help for `UserData` as a new parameter?
Could I use the description from Swagger
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/compute.json#L11047-L11050

**Comment by yonzhan** [comment]
@roipmsft any feedback?

**Comment by zhoxing-ms** [comment]
> There is a max limit to the size of the userData (the same size limit as for existing customData)

@roipmsft Hi, may I ask the verification of max limit for `UserData` should be the logic of the server side, right? I didn't see any max limit checks for `customData` on the client side.

**Comment by roipmsft** [comment]
Yes, CRP does server-side validation.
If customData doesn't have client-side validation, we can follow the same pattern for userData.

**Comment by zhoxing-ms** [comment]
> We allow customers to retrieve value of userData (this behavior does not exist for customData today). For that, CLI must make GET request using $expand=userData

@roipmsft Hi, in this regard, I would like to confirm with you two questions:

1. Which query commands need to support querying `UserData` property?
From the perspective of REST API, only GET requests *([virtualmachines_get](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get) and [virtualmachinescalesets_get](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/get))* support parameter `expand`, while LIST requests *([virtualmachines_list](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/list) and [virtualmachinescalesets_list](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/list))* do not. So we just need commands `az vm show` and `az vmss show` to support querying `UserData`, right?

2. Should querying `UserData` property be the default behavior, or should it be triggered by user input parameters? If it needs a parameter, what is the name of this parameter?

**Comment by roipmsft** [comment]
Answers inline, thank you.

**Comment by zhoxing-ms** [comment]
@roipmsft Hi, I still have some questions:
1. May I ask is `instanceview` and `userData` mutually exclusive in the parameter `expand` for REST service?

2. How to name the parameter `--include-user-data`? It follows the naming convention for parameters
> I don't know if CLI has a naming convention for parameters, so I am happy to defer to your suggestion on a suitable name for the param.

3. What is the expected help information of parameter `--userdata`? Could I use the description from Swagger: UserData for the VM.

**Comment by roipmsft** [comment]
Answers inline, thank you.

**Comment by zhoxing-ms** [comment]
> We should allow customer to delete UserData. For the CRP/VMSS REST api endpoint, if the PUT VM request contains userData equal to empty string, CRP will interpret that as a signal to delete the UserData. CLI can allow customer to pass an empty string as input, or perhaps have a separate option? (such as --deleteUserData)

@roipmsft Hi, I want to confirm that this requirement means that `az vm update/az vmss update` also needs to support updating parameter `--user-data`, right? And when `--user-data` passed in is an empty string, it will clear the existing value, right?

**Comment by roipmsft** [comment]
> > We should allow customer to delete UserData. For the CRP/VMSS REST api endpoint, if the PUT VM request contains userData equal to empty string, CRP will interpret that as a signal to delete the UserData. CLI can allow customer to pass an empty string as input, or perhaps have a separate option? (such as --deleteUserData)
> 
> @roipmsft Hi, I want to confirm that this requirement means that `az vm update/az vmss update` also needs to support updating parameter `--user-data`, right? And when `--user-data` passed in is an empty string, it will clear the existing value, right?

Yes, that is exactly right.
