### ISSUE TITLE
zsh autocompletion on OSX/macOS

### ISSUE THREAD

**Issue by niemyjski** [Azure/azure-cli#1722]
Every time I launch my terminal I get the following error: `/Users/blake/lib/azure-cli/az.completion:10: command not found: complete` I followed the `curl -L https://aka.ms/InstallAzureCli | bash` docs exactly and the file is there although in a weird location (the default). Is anyone else running into this?

**Comment by derekbekoe** [comment]
In ZSH your default shell?

Through bash compatibility mode, ZSH tab completion support was added for the pip installed packages but not the other install methods. (https://github.com/Azure/azure-cli/pull/1558)

Will investigate adding support for the other install methods also.

Until then, does running `autoload bashcompinit && bashcompinit` resolve this?

**Comment by niemyjski** [comment]
Yes, I'm using zsh and hyper.is :).

**Comment by derekbekoe** [comment]
Is `$SHELL` set to zsh?

**Comment by niemyjski** [comment]
Yes,

$ echo $SHELL
/bin/zsh

**Comment by berndverst** [comment]
I also just encountered this.

```
$ sw_vers -productVersion
10.12.3
$ zsh --version
zsh 5.2 (x86_64-apple-darwin16.0)
$ echo $SHELL
/bin/zsh
```

Installed via 
`$ curl -L https://aka.ms/InstallAzureCli | bash`

If I update my .zshrc and add
`autoload bashcompinit && bashcompinit`

in the line before sourcing `azure-cli/az.completion` it works fine.

**Comment by berndverst** [comment]
I just noticed that `zsh` version `5.2` is not the latest. For some reason I wasn't managing it via homebrew, so I updated my install with `brew install zsh`. Now running `zsh 5.3.1 (x86_64-apple-darwin16.3.0)` I no longer get this error.

@niemyjski perhaps upgrading your zsh will fix this for you too? 🤷‍♂️

**Comment by niemyjski** [comment]
Awesome, it works after I updated zsh and added that line before the auto completion. Wonder what can be done to make this just work.

**Comment by berndverst** [comment]
@niemyjski I don't think you even need that line anymore after updating zsh. I removed it entirely and it works fine. That line was only necessary for me to make it work with zsh 5.2.

**Comment by niemyjski** [comment]
I was getting an error when I tried without it

**Comment by berndverst** [comment]
@niemyjski you are right -
turns out it only worked because I am loading the Google Cloud Platform bash completion script before this.

So it seems that independent of zsh version you must have `autoload bashcompinit && bashcompinit` in your bashrc before sourcing the Azure bash completion script.

**Comment by benstegink** [comment]
Thanks guys! The fix from @berndverst of adding the line before sourcing azure-cli/az.completion worked to fix it for me as well.

**Comment by frankfuu** [comment]
Running zsh shell on Windows Subsystem for LInux (WSL) I also had to have `autoload bashcompinit && bashcompinit` before sourcing `azure-cli/az.completion`

**Comment by qqzylx** [comment]
The fix from @berndverst works for me as well. Thanks guys.

**Comment by maticko** [comment]
If someone is getting the ```bashcompinit:134: parse error near `|' error``` even after adding autoload line before sourcing change command to `autoload -U bashcompinit && bashcompinit`. Should work after that.

**Comment by Raidus** [comment]
I've followed the installation guidance and the suggestion from @berndverst but I still get the error:
`zsh: command not found: az`

P.S. homebrew and zsh is up to date

**Comment by matxx** [comment]
Same as @Raidus here, I had the `command not found: complete` error 

I've followed the installation guidance and the suggestion from @berndverst and got the error : `zsh: command not found: az`

I wanted to try out Azure but I won't come back (cause of this and the fact that homebrew's formula is not up-to-date either)

**Comment by Jaysojitra13** [comment]
ZSH shell doesn't support pip command. 
Now what?

**Comment by jldeen** [comment]
@Jaysojitra13 Can you elaborate on what you mean "zsh shell doesn't support pip command?" I'm using pip just fine.

**Comment by Jaysojitra13** [comment]
Herewith i am sending you a screenshot. I hope you will understand what is
the error....

**Comment by jldeen** [comment]
@Jaysojitra13 I didn't see a screenshot attached to your previous reply. Can you try again?

**Comment by Jaysojitra13** [comment]
I hope this will work.

**Comment by cicorias** [comment]
when installing from Brew, now the `.zshrc` file requires

```
autoload bashcompinit && bashcompinit
source /usr/local/etc/bash_completion.d/az
```

paths have changed

**Comment by Jaysojitra13** [comment]
Hello,

Currently i'm working on Django framework of python. When virtual
environment is activated and When i write python, python3.5 shell is
opened. And virtual environment is not activated and i write python then
python2.7 shell is opened. I don't know what the hack is going on in my
system.

Here i'm sending screenshots. You will understand my problem clearly by
seeing this screenshots.

In first.png, If i write python3  though python2.7 shell is opened.
In second.png,Django environment is activated. And i tried to open python2
shell though python3.5 shell is opened.

I hope you will give me favour.

**Comment by derekbekoe** [comment]
@Jaysojitra13 This seems unrelated to this GitHub issue.

**Comment by derekbekoe** [comment]
Closing issue as the following comments resolve this:
https://github.com/Azure/azure-cli/issues/1722#issuecomment-277565158
https://github.com/Azure/azure-cli/issues/1722#issuecomment-370205593
