### ISSUE TITLE
How to specify "Latest" in --user-cert-secret-version argument?

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli#17234]
When viewed in Azure Portal, custom domain functionality of CDN recommends using latest version of certificate to avoid service interruption:

![image](https://user-images.githubusercontent.com/1999365/110395501-1d606780-8023-11eb-9453-759f62a96b54.png)

However, it's impossible to specify "Latest" as --user-cert-secret-version argument value - if done so, CDN will fail to retrieve the certificate from the KeyVault.

It's impossible to *not* specify the version argument:

```
('--user-cert-group-name, --user-cert-vault-name, --user-cert-secret-version, ', '--user-cert-secret-version, and --user-cert-protocol-type are all required for user managed certificates.')
```

Nor is it possible to specify "" as a value:

```
code: BadRequest - , Property 'CustomHttpsParameters.CertificateSourceParameters.SecretVersion' cannot be set to ''
```

How to specify the latest version of the secret in Az CLI?

Here's the baseline command for enable-https:

```
az cdn custom-domain enable-https --name custom-domain-name --resource-group resource-group-name --min-tls-version 1.2 --profile-name cdn-profile-name --endpoint-name endpoint-name --user-cert-subscription-id kv-subscription-id --user-cert-group-name kv-resource-group --user-cert-vault-name kv-name --user-cert-secret-name cert-name --user-cert-secret-version cert-version --user-cert-protocol-type sni
```

Currently I'm using actual version of the cert, but tried to replace it with "Latest" or "", or completely remove it for this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed8c61db-b294-77fb-0e92-eae01d07b776
* Version Independent ID: 958b6e8d-609b-2a58-dbe1-240d3fd894bb
* Content: [az cdn custom-domain](https://docs.microsoft.com/en-us/cli/azure/cdn/custom-domain?view=azure-cli-latest#az_cdn_custom_domain_show)
* Content Source: [latest/docs-ref-autogen/cdn/custom-domain.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cdn/custom-domain.yml)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cdn

**Comment by t-bzhan** [comment]
@wasker , you could just omit the "--user-cert-secret-version" parameter. The "Latest" version will be used by default and CDN will pick up the renewed certificate once your certificate is auto rotated.

The command goes like:
`az cdn custom-domain enable-https -g huaiyiz --profile-name huaiyiz-msft --endpoint-name huaiyiz-rpv2-test1 -n byomsft-localdev-cdn-azure-cn --user-cert-group-name bzhanafdtest --user-cert-protocol-type sni --user-cert-secret-name certmy --user-cert-vault-name bzhanbyostest`

By the way, the latest portal already support that now  and it is only supported by Azure CDN Microsoft SKU.
![image](https://user-images.githubusercontent.com/61817681/110609078-d2338980-81c7-11eb-9617-3905c964416c.png)

**Comment by wasker** [comment]
Ah, it's the good old "I'm using the old version of az CLI" bug. I was on 2.14, but it seems that the auto-rotation support was added in at least 2.16. The problem is not reproducing with the latest version (2.20) - I'm able to remove the version arg and CDN endpoint reports that it uses "Latest" version.

Thanks for looking into this!

**Comment by woozar** [comment]
2.15 does not yet support it
