### ISSUE TITLE
[Automation] Enhance run_tests command

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1723]
1. Enable it to run individual test
2. Enable it to make VCR based tests run live

**Comment by tjprescott** [comment]
Also, I would recommend adding:
3. Quickly run only tests that need to be re-recorded.

Technically, there's a 'run_live' flag on existing tests that will make them always run live so 2 is supported (unless you mean to override it across the board)

**Comment by troydai** [comment]
Retire this issue.
