### ISSUE TITLE
Need a way to specify the access tier

### ISSUE THREAD

**Issue by altwohill** [Azure/azure-cli#17233]
Running the following command 

```bash
az storage share create --name $user --account-name $azurestoragename --account-key $azurestoragekey --quota 1024
````

creates the share as desired, however it is set to "Transaction optimized" tier, which is twice the price of "Hot".

We should be able to specify the tier when creating the share. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae881ef-ad75-32e6-6e64-6b526a2d9a5d
* Version Independent ID: 99971e2e-9ff6-f865-07f7-61efbcb16021
* Content: [az storage share](https://docs.microsoft.com/en-US/cli/azure/storage/share?view=azure-cli-latest#az_storage_share_create)
* Content Source: [latest/docs-ref-autogen/storage/share.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/share.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
@altwohill please try with `az storage share-rm create`, which has access tier support.
