### ISSUE TITLE
Azure CLI creates storage account in a region different from that of resource group

### ISSUE THREAD

**Issue by septst** [Azure/azure-cli#17238]
Hello,

First of all, this may not be an issue. I would like to understand why Azure CLI creates a storage account in a region different from that of resource group when location is not specified while creating as below.

1. Create a new resource group
`> az group create -n "ch4-rg" -l "westus"`
2. Create a new storage account
`> az storage account create -n "cdnstorage03082020" -g "ch4-rg" `

Since I didn't specify the location in the second step, I thought that it would take the region of the resource group i.e. westus but the  new storage account was created in westeurope. That said, I do understand that the location of group is independent of that of resources it contains. But, it may be worthwhile to consider the same region from group while creating a new resource when a location is not specified.

Any leads on how this works would be greatly appreciated.

**Comment by yonzhan** [comment]
Storage

**Comment by Juliehzl** [comment]
@septst, we do read location from resource group if there is no location input.
But have you ever set location with `az configure`? You could check with `az configure -l`.

**Comment by septst** [comment]
> @septst, we do read location from resource group if there is no location input.
> But have you ever set location with `az configure`? You could check with `az configure -l`.

No, I haven't set location for the configuration. But, it didn't use the location from resource group when I didn't give location for the above resource.

**Comment by Juliehzl** [comment]
Could you provide debug info with `--debug` in your command?

**Comment by septst** [comment]
I don't have it. You can use the above two commands to reproduce the steps but ensure that the location is not set in config to check if the resource group location is used when a location is not given for a new resource like storage accout.

**Comment by Juliehzl** [comment]
Please see
![image](https://user-images.githubusercontent.com/49508232/113077607-0963ec00-9204-11eb-9e8f-7f12b06871a6.png)

As location is required when creating storage account, if there is no location specified in parameter list, we have to read from resource group. If you still have the issue, please send me debug log as I cannot reproduce your issue.

**Comment by septst** [comment]
Sure, thanks for your time and help.
