### ISSUE TITLE
az cli modifying values in custom rules in WAF-Policies produces error

### ISSUE THREAD

**Issue by lnxnut** [Azure/azure-cli#17249]
## Describe the bug

**Command Name**
`az network application-gateway waf-policy custom-rule match-condition remove`

**Errors:**
```
pop from empty list
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 325, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 784, in default_command_handler
    return op(**command_args)
cli/command_modules/network/custom.py, ln 1571, in remove_waf_custom_rule_match_cond
    rule.match_conditions.pop(index)
IndexError: pop from empty list
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network application-gateway waf-policy custom-rule match-condition remove -g {} --policy-name {} -n {} --index {}`

## Environment Summary
```
Linux-4.15.0-106-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.12.1 *

```

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
Please make sure it exists before removing the resource.('az network application-gateway waf-policy custom-rule match-condition list ' may help to check it before)
