### ISSUE TITLE
[DNS] Could record set name default to "@"?

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1724]
In the spirit of the CLI providing sensible defaults when possible, I'm curious whether it would make sense for the `-n` parameter of the `az network dns record-set create` command to default to "@", as an alias to the zone name itself. This appears to be the behavior when creating a record set via the Azure portal, so there would also be a potential consistency benefit.

**Comment by tjprescott** [comment]
It's certainly possible. @jtuliani thoughts?

**Comment by jtuliani** [comment]
I think I'd prefer to not have a default, rather make the user think about the record name and provide it explicitly.

In the portal, the UI provides context in that the zone name suffix is presented with the record name text input box, so if you type 'foo' you can see that the FQDN will be 'foo.contoso.com'.  Hence it makes sense that if the box is blank, the FQDN will be 'contoso.com' and hence the Portal should use the '@' default.  This argument doesn't translate to CLI or PowerShell.

Also the Portal is used by DNS novice users who often aren't familiar with the convention of using '@' for record names at the zone apex.  CLI/PowerShell users are generally a bit more technical/aware.

**Comment by lostintangent** [comment]
@jtuliani Sounds good to me. I didn't feel too strongly about this, but I was curious what you thought. Thanks!
