### ISSUE TITLE
az backup item list returns invalid resource ID

### ISSUE THREAD

**Issue by lovelinuxalot** [Azure/azure-cli#17244]
Hi,

I understand `az backup item` is in preview mode. While I was testing i came across a bug. The list of items returned had the resource IDs starting like this:

```
"/Subscriptions/xxx-xxx-xxxxx/resourceGroups/xxxxxx"
```
which has problems when integrating with Terraform in importing resources to State file. The import works if the resource ID is 
changed to small letter. Like this:

```
"/subscriptions/xxx-xxx-xxxxx/resourceGroups/xxxxxx"
````

It would be great if this could be fixed before releasing :)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60a9656d-adaf-b33e-a5a9-985e6245c970
* Version Independent ID: 98f0d6b5-5005-38a3-0f0d-a10d138062a7
* Content: [az backup item](https://docs.microsoft.com/en-us/cli/azure/backup/item?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/backup/item.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/backup/item.yml)
* Service: **backup**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by pvrk** [comment]
@lovelinuxalot : Thanks for the feedback and sorry for the delay in response. Acknowledged as a bug. Will come back and update the thread on the ETA for fixing it.

**Comment by pvrk** [comment]
We are fixing this in the upcoming API release. This change will be reflected from that API version onwards.

**Comment by pvrk** [comment]
Please check in the latest CLI version: 2.28. The URL will have lower case 's' for 'subscription'.
Please re-open if that is not the case.

**Comment by pvrk** [comment]
#please-close
