### ISSUE TITLE
WebApp:az webapp list-runtimes does not list all current python versions

### ISSUE THREAD

**Issue by tonybaloney** [Azure/azure-cli#17256]
The `az webapp list-runtimes` command gave the following options for Python:

```default
python|2.7
python|3.6
```

Python 3.7 and 3.8 are both available runtimes on Azure Web Apps and I can deploy using `--runtime "python|3.8"`

The printout is missing the current list of runtimes for Python

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
looking in to it.

**Comment by panchagnula** [comment]
@calvinsID do we need to update our static runtimes list?

**Comment by calvinsID** [comment]
Hi @tonybaloney wondering what CLI version you're using? On the latest CLI I'm seeing 3.6, 3.7 and 3.8 using `az webapp list-runtimes --linux` and 3.6 without `--linux` flag

**Comment by tonybaloney** [comment]
```
azure-cli                          2.3.1

command-modules-nspkg              2.0.3
core                               2.3.1
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/usr/local/Cellar/azure-cli/2.3.1/libexec/bin/python'
Extensions directory '/Users/anthonyshaw/.azure/cliextensions'

Python (Darwin) 3.8.6 (default, Oct 27 2020, 08:57:44)
[Clang 12.0.0 (clang-1200.0.32.21)]

Legal docs and information: aka.ms/AzureCliLegal



Unable to check if your CLI is up-to-date. Check your internet connection.

Please let us know how we are doing: https://aka.ms/clihats
```

In the UI I can select between Python versions 3.8-3.6. If I select 3.7 or 3.8 it will then grey out Windows as the option.

It never crossed my mind to specify `--linux` to get the full list of what is available on Linux. So by default it only lists what is available on Windows?

**Comment by calvinsID** [comment]
@tonybaloney yeah by default `az webapp list-runtimes` shows windows stacks, and adding --linux flag shows linux stacks. I can update the `-h` help text to make it more clear

**Comment by tonybaloney** [comment]
Thanks Calvin,

An update to the help text would be useful, but this default behaviour is contrary to the portal, which will select Linux as the default running environment for Python and show the available runtimes for Linux once you select Python.

Whereas if the user were to query the command by default, its not obvious that this is _only_ Windows and that is why they can't see Python3.7+, unless they read the help text.
As the runtimes for Python on Windows are frozen at 3.6 (which is really old) and linux will continue to be updated, I think this problem will only get worse. 

This is also the same for node 12 runtime, which will only appear if you add `--linux` 

```
$ az webapp list-runtimes                                                                                                                                                                                                                                                       
Result
-------------------
aspnet|V4.7
aspnet|V3.5
node|0.6
node|0.8
node|0.10
node|0.12
node|4.8
node|6.5
node|6.9
node|6.12
node|7.10
node|8.1
node|8.4
node|8.5
node|8.9
node|8.10
node|8.11
node|10.0
node|10.6
node|10.14
node|10.15
php|5.6
php|7.2
php|7.3
php|7.4
python|2.7
python|3.6
java|1.7|Tomcat|7.0
java|1.7|Tomcat|8.0
java|1.7|Tomcat|8.5
java|1.7|Tomcat|9.0
java|1.7|Jetty|9.1
java|1.7|Jetty|9.3
java|1.7|Java SE|8
java|1.8|Tomcat|7.0
java|1.8|Tomcat|8.0
java|1.8|Tomcat|8.5
java|1.8|Tomcat|9.0
java|1.8|Jetty|9.1
java|1.8|Jetty|9.3
java|1.8|Java SE|8
java|11|Tomcat|7.0
java|11|Tomcat|8.0
java|11|Tomcat|8.5
java|11|Tomcat|9.0
java|11|Jetty|9.1
java|11|Jetty|9.3
java|11|Java SE|8
```

Would it be possible for this command to show both Linux and Windows with an additional column specifying which platforms are supported? Then for a `--windows` flag to be added to compliment the `--linux` flag.

Cc @bnb

**Comment by charris-msft** [comment]
I would like to +1 @tonybaloney's recommendation.
Given that Python on Linux is the path forward, we should make the command line reflect that reality. Ideally, the default command would show which versions are available for Linux (rather than Windows) so the long-term experience requires the least amount of typing.

Short of that, it seems that we could do something similar to the java approach of which would look like this for python:

Python | 3.6 | Linux
python | 3.6 | Windows
Python | 3.7 | Linux
Python | 3.8 | Linux
Python | 3.9 | Linux

That seems pretty easy to understand.

**Comment by tonybaloney** [comment]
<img width="912" alt="Screen Shot 2021-04-23 at 10 36 40 am" src="https://user-images.githubusercontent.com/1532417/115801351-e05c0300-a41f-11eb-9856-39d55666ea8a.png">

This is the behaviour of the Azure extension for vs code. It'll show the correct stacks for Linux, you don't need to tell it that you want linux first

**Comment by bnb** [comment]
+1 to what @tonybaloney said. As an extension of this discussion, it may also be useful to consider a "supported" column into such a table to more clearly communicate which versions of each runtime are and are not supported rather than having a parenthetical at the very end of the list which will theoretically grow infinitely.

**Comment by panchagnula** [comment]
Noted all feedback on this - we have work item to rewrite runtimes stack with the API support while doing that we will make updates to the command to be clear - however, since this would be a breaking change - we need to sign off on design,Thanks.
