### ISSUE TITLE
SSL Certificate validation error even though AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1

### ISSUE THREAD

**Issue by JBerny** [Azure/azure-cli#17252]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

i'm trying to give list and get permissions for secrets to users and i get two different behaviours.
Users have owner role on the resource group and contributor on the subscription.

The following command gives an error:
```
az keyvault set-policy --upn user@somemail.com --resource-group TeamRG_3-Team_3 --name kv-openhack-team3 --secret-permissions list get

Error occurred in request., SSLError: HTTPSConnectionPool(host='graph.windows.net', port=443): Max retries exceeded with url: /587b6ea1-3db9-4fe1-a9d7-85d4c64ce5cc/users?$filter=userPrincipalName%20eq%20%27***********%27&api-version=1.6 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

While the following command works fine:
```
objid=$(az ad user show --id ${email} --query objectId )
az keyvault set-policy --only-show-errors --resource-group TeamRG_3-Team_3 \
            --object-id ${objid}\
            --name kv-openhack-team3 --secret-permissions list get
```

**To Reproduce**

see above

**Expected behavior**

I would expect that both commands give the same result.

**Environment summary**

az --version
azure-cli                         2.20.0

core                              2.20.0
telemetry                          1.0.6

Extensions:
azure-firewall                     0.6.1
subscription                       0.1.4
account                            0.2.1

Python location '/usr/local/Cellar/azure-cli/2.20.0/libexec/bin/python'
Extensions directory '/Users/jberny/.azure/cliextensions'

Python (Darwin) 3.8.8 (default, Feb 26 2021, 23:59:43)
[Clang 12.0.0 (clang-1200.0.32.29)]

**Additional context**

a proxy is involved and the following vars are set
http_proxy=http://localhost:3129
https_proxy=http://localhost:3129

**Comment by yungezz** [comment]
add @houk-ms to help

**Comment by jiasli** [comment]
`AZURE_CLI_DISABLE_CONNECTION_VERIFICATION` doesn't work in many cases and has been nearly deprecated. [Working behind a proxy](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#work-behind-a-proxy) provides detailed instructions on how to trust a custom root certificate. (#1572, #11436)
