### ISSUE TITLE
Add az login option to NOT fetch the list of subscriptions. 

### ISSUE THREAD

**Issue by serbrech** [Azure/azure-cli#17254]
**Is your feature request related to a problem? Please describe.**

When we run az login, there is no way to tell it to not fetch the list of subscription we have access to.
This significantly slow down the time it takes to login, for example in CI runs

**Describe the solution you'd like**

`az login --dont-get-the-subscription-list-please`

**Describe alternatives you've considered**

pull appart the az login code and write my own login routine to save the toke only

**Additional context**

in our environment, az login takes 10+ second in our CI because of the GET following the login.

**Comment by yonzhan** [comment]
Account

**Comment by jiasli** [comment]
Good suggestion. It is being tracked at https://github.com/Azure/azure-cli/issues/13285.

**Comment by kewalaka** [comment]
for people coming along afterwards & using the ADO DevOps `AzureCLI@2` task - you can achieve this by setting `visibleAzLogin: false` parameter.

ref; https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines
