### ISSUE TITLE
az network front-door backend-pool backend add doesn't allow to specify empty value for backend host header value

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli#17269]
**Describe the bug**

Empty value of a backend host header parameter has a special meaning in AFD: if value is empty, the Host header will be populated with what came as part of the request. This is important when same backend pool is used by multiple frontends and needs to be able to know which domain had made the request.

It is possible to make the value blank in Azure Portal, but impossible to do so with az CLI.

**To Reproduce**

Explicitly specified empty value:

`az network front-door backend-pool backend add --resource-group myrg --front-door-name myfd --pool-name DefaultBackendPool --address www.bing.com --backend-host-header "" --disabled true --http-port 80 --https-port 443 --priority 2 --weight 1`

results in

```
{
  "address": "www.bing.com",
  "backendHostHeader": "www.bing.com",
  "enabledState": "Disabled",
  "httpPort": 80,
  "httpsPort": 443,
  "priority": 2,
  "privateEndpointStatus": null,
  "privateLinkAlias": null,
  "privateLinkApprovalMessage": null,
  "privateLinkLocation": null,
  "privateLinkResourceId": null,
  "weight": 1
}
```

No backend-host-header arg specified:

`az network front-door backend-pool backend add --resource-group myrg --front-door-name myfd --pool-name DefaultBackendPool --address www.bing.com --disabled true --http-port 80 --https-port 443 --priority 2 --weight 1`

results in 

```
{
  "address": "www.bing.com",
  "backendHostHeader": "www.bing.com",
  "enabledState": "Disabled",
  "httpPort": 80,
  "httpsPort": 443,
  "priority": 2,
  "privateEndpointStatus": null,
  "privateLinkAlias": null,
  "privateLinkApprovalMessage": null,
  "privateLinkLocation": null,
  "privateLinkResourceId": null,
  "weight": 1
}
```

**Expected behavior**

If empty value is explicitly specified for the backend-host-header arg, it should be used instead of defaulting to the backend address.

**Environment summary**

```
{
  "azure-cli": "2.20.0",
  "azure-cli-core": "2.20.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.5",
    "front-door": "1.0.11",
    "log-analytics": "0.2.1",
    "resource-graph": "1.1.0"
  }
}
```

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
Thank you for feedback and we may do it in the future. https://github.com/Azure/azure-cli-extensions/blob/94b491f5565f504cc046ed66924fbd381998213c/src/front-door/azext_front_door/custom.py#L395

**Comment by msyyc** [comment]
the issue could be fixed together with https://github.com/Azure/azure-cli/issues/17270
