### ISSUE TITLE
CLI for VNG : p2s multiple authentication

### ISSUE THREAD

**Issue by neethirshetty** [Azure/azure-cli#17260]
**Is your feature request related to a problem? Please describe.**
P2S multiple authentication feature has been released. Hence we will need to add CLI support to it.
previously we were allowed to set only single authentication for P2S VNG. Support for multiple authentication has to be added.

**Describe the solution you'd like**

Brief about multi auth: . A point-to-site (P2S) VPN lets you create a secure connection to your VNG from an individual client computer. there are 3 auth types allowed: radius/AAD/Certificate. Previously we used to support setting only one of these auth types. But with multi auth we need to allow setting multiple auth parameters at a time.

**Describe alternatives you've considered**

CLI is needed for this as this feature is already released.

**Additional context**

Please contact me neethir@microsoft.com if there is any questions on Point to site multi- auth feature CLI request.
SWAGGER PR: https://github.com/Azure/azure-rest-api-specs/pull/13183
Powershell PR: https://github.com/Azure/azure-powershell/pull/14441#issuecomment-794959932

Commands eg:
(newly added property is highlighted)
New-AzVirtualNetworkGateway -ResourceGroupName $rgname -name $rname -location $location -IpConfigurations $vnetIpConfig -GatewayType Vpn -VpnType RouteBased -EnableBgp $false -GatewaySku VpnGw2 -VpnClientAddressPool 201.169.0.0/16 **_-VpnAuthenticationType Certificate,Radius,AAD_** -RadiusServerAddress "1.2.3.4" -RadiusServerSecret $Secure_String_Pwd -VpnClientRootCertificates $rootCert -AadTenantUri $aadTenant -AadAudienceId $aadAudience -AadIssuerUri $aadIssuer -VpnClientProtocol OpenVPN
     

OR
Set-AzVirtualNetworkGateway -VirtualNetworkGateway $gate **-VpnAuthenticationType Certificate,Radius,AAD** -RadiusServerAddress "1.2.3.4" -RadiusServerSecret $Secure_String_Pwd -VpnClientRootCertificates $rootCert -AadTenantUri $aadTenant -AadAudienceId $aadAudience -AadIssuerUri $aadIssuer

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
PR has been merged, new version 2.22.0 of azure-cli will be released soon.
