### ISSUE TITLE
Exception in an attempt to remove and add action group for a metric alert rule

### ISSUE THREAD

**Issue by ivan-sam** [Azure/azure-cli#17268]
## Describe the bug

**Command Name**
`az monitor metrics alert update`

**Errors:**
```
'MetricAlertAction' object has no attribute 'webhook_properties'
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py, ln 233, in invoke
azure\cli\core\commands\__init__.py, ln 660, in execute
azure\cli\core\commands\__init__.py, ln 723, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 715, in _run_job
azure\cli\command_modules\monitor\_exception_handler.py, ln 23, in exception_handler
azure\cli\core\commands\__init__.py, ln 694, in _run_job
azure\cli\core\commands\__init__.py, ln 331, in __call__
azure\cli\core\commands\arm.py, ln 527, in handler
cli\command_modules\monitor\operations\metric_alert.py, ln 96, in update_metric_alert
AttributeError: 'MetricAlertAction' object has no attribute 'webhook_properties'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor metrics alert update --ids {} --remove-action {} --add-action {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.20.0

```
## Additional Context

The `az monitor metrics alert list` command returns the json in the following format:
```
[
  {
    "actions": [
      {
        "actionGroupId": "/subscriptions/<guid>/resourceGroups/<resource-group>/providers/microsoft.insights/actiongroups/<action-group-name>",
        "webHookProperties": {}
      }
    ],

]
```

so the property name in response is `webHookProperties`, not the `webhook_properties` that is mentioned in exception.

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
Please reinstall Azure-CLI and make sure its requirements are updated as well.

**Comment by ivan-sam** [comment]
Thanks, @kairu-ms!
I've tried to uninstall/install the Azure CLI msi. The issue is still reproducible.
I'm not sure about updating requirements though. I haven't found any info about that. Could you provide the details, please?

**Comment by kairu-ms** [comment]
Thanks for your feedback. There's an issue in CLI and I will fix it in next version. Currently it can be workaround by removing that existing action and then adding id again. For example

```
az monitor metrics alert update --ids {...} --remove-action {action-to-update} --add-action {action-to-update} {properties}
```

**Comment by ivan-sam** [comment]
Thank you, @kairu-ms!
I did some more testing.
It looks like the issue that I experience is a bit different.

So, first remark - my scenario was about replacing one action with the other, so actionGroupIds are different.
And second - I've tried to execute just `--add-action` and got the same issue:

```
az monitor metrics alert update --ids "<metric-alert-id>" --add-action "/subscriptions/<subs>/resourceGroups/<rg>/providers/microsoft.insights/actiongroups/<action-group>" webHookProperties={"test":"test"}
```
It failed with the same error: ERROR: `'MetricAlertAction' object has no attribute 'webhook_properties'`

**Comment by kairu-ms** [comment]
> d second - I've tried to execute just `--add-action` and got the same issue:

That's because `/subscriptions/<subs>/resourceGroups/<rg>/providers/microsoft.insights/actiongroups/<action-group>` already exists. I think the following command can work for your scenario.

```
az monitor metrics alert update --ids "<metric-alert-id>" --remove-action "/subscriptions/<subs>/resourceGroups/<rg>/providers/microsoft.insights/actiongroups/<action-group>" --add-action "/subscriptions/<subs>/resourceGroups/<rg>/providers/microsoft.insights/actiongroups/<action-group>" test=test
```

**Comment by kairu-ms** [comment]
In order to workaround the bug, you should add the actionGroupId behand `--remove-action` first and then use it in `--add-action` again.

**Comment by ivan-sam** [comment]
> > d second - I've tried to execute just `--add-action` and got the same issue:
> 
> That's because `/subscriptions/<subs>/resourceGroups/<rg>/providers/microsoft.insights/actiongroups/<action-group>` already exists. I think the following command can work for your scenario.
> 
> ```
> az monitor metrics alert update --ids "<metric-alert-id>" --remove-action "/subscriptions/<subs>/resourceGroups/<rg>/providers/microsoft.insights/actiongroups/<action-group>" --add-action "/subscriptions/<subs>/resourceGroups/<rg>/providers/microsoft.insights/actiongroups/<action-group>" test=test
> ```

Yes, that works! Thank you! I got documentation incorrectly. Now I know that **properties** stands for webHookProperties.
