### ISSUE TITLE
'az storage container policy' commands don't support auth-mode login

### ISSUE THREAD

**Issue by ishepherd** [Azure/azure-cli#17278]
## Describe the bug

**Command Name**
`az storage container policy list`

**Errors:**
```
The specified resource does not exist. ErrorCode: ResourceNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:bdb8235d-701e-0024-5635-167282000000
Time:2021-03-11T05:17:47.5356430Z</Message></Error>
```

## To Reproduce:

- `az storage container policy list --account-name <Account> -c <BlobContainer> --auth-mode login`
- `az storage container policy create` also reproduces it.

## Expected Behavior

* A list of storage policies on the container or `{}` if none.
* (The command works if you use `--auth-mode key`.)

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.20.0

```
## Additional Context

* Other storage commands, like `az storage container list --account-name <Account> --auth-mode login`, are working.
    * So there is no problem with my login.

**Comment by ishepherd** [comment]
I presume this is a limitation of Azure Storage REST API but I couldn't find any documentation or bug report about it.

It would be nice if the Azure CLI can help out the next wanderer by printing a special warning if this scenario is attempted.

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @ishepherd, you need to assign `Storage Blob Data Owner` rule if you want to see access policy info. For details about RBA role, see https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-owner.

**Comment by ishepherd** [comment]
Thanks @Juliehzl

After checking, yes I only had Contributor on this storage account.

It's a shame the Storage API implemented this as a 404.
403 Forbidden would have given me the clue what was wrong. (I am authorized to know the account exists).
