### ISSUE TITLE
https://docs.microsoft.com/en-us/learn/modules/manage-iot-central-apps-with-rest-api/5-exercise-manage-devices

### ISSUE THREAD

**Issue by llwang8** [Azure/azure-cli#17276]
## Describe the bug

**Command Name**
`az login`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity`

## Environment Summary
```
Linux-4.15.0-1108-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.20.0

Extensions:
azure-iot 0.10.10
ai-examples 0.2.5

```

**Comment by yonzhan** [comment]
account
