### ISSUE TITLE
az network front-door backend-pool backend family of commands should provide an easy way to enable/disable backends

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli#17270]
**Is your feature request related to a problem? Please describe.**

It's impossible to enable or disable an existing backend in the backend pool of the AFD resource. The only way to do that from the command line is to get an existing backend, create a new backend with the same parameters but desired value for the "disable" arg of the CLI, then delete the original backend.

This approach is bad for a few reasons:

* It doesn't scale as backends might have new parameters which are not recognized by e.g. the script that implements the algorithm described above.
* Apparently, even in the current implementation of az CLI it's impossible to correctly clone an existing backend. For example, it's impossible to create a new backend with an empty value for backend host header parameter - see #17269 for more details.

**Describe the solution you'd like**

I'd like to have a pair of new commands ("enable", "disable") under the "az network front-door backend-pool backend" family of commands, and let az CLI (or AFD service) handle enabling or disabling of existing backends correctly.

**Describe alternatives you've considered**

The clone-then-delete-the-original algorithm described above is what I'm using today.

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
thank you for your feedback and we will think about it seriously.

**Comment by msyyc** [comment]
FYI. Customer wants ''az network front-door backend-pool backend update" to update parameters of an existing backend in a backend-pool. (front-door is in 'extension' repo)
