### ISSUE TITLE
network route-table is deprecated use network vhub route-table

### ISSUE THREAD

**Issue by Keithsc** [Azure/azure-cli#17286]
az cli = v2.19.1

I noticed today that the "az network route-table create" command outputs a prompt stating that it is going to be deprecated and replaced with "az network vhub route-table create".  I tried using the new command but it failed as it seems I need to create a vhub. 

Are we being forced down the vhub route or is there another way to create a route table ?

**Comment by yonzhan** [comment]
network

**Comment by Keithsc** [comment]
I should have said it was the "az network route-table create" command that I was querying. I have edited my original post.

**Comment by msyyc** [comment]
what is the detailed prompt, I don't find it : 
![image](https://user-images.githubusercontent.com/70930885/111099588-ce658580-8580-11eb-8b4d-ac18550c41a4.png)

**Comment by msyyc** [comment]
@Keithsc I could not find the prompt. Could you show the detailed prompt?
![image](https://user-images.githubusercontent.com/70930885/111948746-9b8c3600-8b1a-11eb-8581-7b0f1c3389ec.png)

**Comment by msyyc** [comment]
similar issue : https://github.com/Azure/azure-cli/issues/16744

**Comment by kairu-ms** [comment]
I could not find the prompt
