### ISSUE TITLE
Front door: enable HTTPS using Latest secret

### ISSUE THREAD

**Issue by mossywell** [Azure/azure-cli#17284]
**Is your feature request related to a problem? Please describe.**

Inability to enable front door HTTPS using a custom certificate without specifying the exact secret version. However, the GUI allows selection of "Latest". Moreover, if you don't select "Latest" the GUI generates a warning and recommends using Latest to avoid downtime during certificate rotation! This is the warning:
"The domain 'my-fd.contoso.com' has enabled HTTPS with your own certificate and specific secret version. To avoid potential downtime, we suggest to set the Secret Version to 'Latest' to always use the latest version from Azure Key Vault."

**Describe the solution you'd like**

Allow the option '--secret-version "Latest"' when using "az network front-door frontend-endpoint enable-https".

**Describe alternatives you've considered**

The workaround is to parse out the secret version from the key vault. But as stated above, that then causes the GUI to recommend against this. And, it will indeed cause downtime during certificate rotation.

**Additional context**

**Comment by yonzhan** [comment]
front-door

**Comment by t-bzhan** [comment]
@mossywell , the issue is fixed for front-door extension after 1.0.13, you could just omit the secret-version parameter and the "Latest" version will be used:
![image](https://user-images.githubusercontent.com/61817681/123224650-987f5800-d504-11eb-964e-a4b753e354d4.png)

**Comment by mossywell** [comment]
Thank you very much for fixing this.
