### ISSUE TITLE
Error when attempting to deallocate multiple vm scaleset instances at once

### ISSUE THREAD

**Issue by rryanq** [Azure/azure-cli#17285]
## Describe the bug
An unexpected error occurs when attempting to deallocate multiple vm scaleset instances at once. When running the same command and only specifying a single instance to deallocate, the command runs as expected.

**Command Name**
`az vmss deallocate`

**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'
Traceback (most recent call last):
python3.6/site-packages/msrest/serialization.py, ln 1416, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
...
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss deallocate --no-wait --name {} --resource-group {} --instance-ids {} {}`

## Environment Summary
```
Linux-3.10.0-1127.el7.x86_64-x86_64-with-centos-7.7.1908-Core
Python 3.6.8
Installer: RPM

azure-cli 2.19.1

```

**Comment by yungezz** [comment]
hi @qwordy, can this be fixed with Neil's PR together?

**Comment by qwordy** [comment]
@rryanq @yungezz This issue will be fixed by https://github.com/Azure/azure-cli/pull/17274. Release date is 3/23/201.
