### ISSUE TITLE
`az iot edge deployment create` leaks the server stacktrace

### ISSUE THREAD

**Issue by gukoff** [Azure/azure-cli#17295]
## Describe the bug

**Command Name**
`az iot edge deployment create`

Extension Name: azure-iot. 
Version: 0.10.9.

**Errors:**

See the stacktrace [here](https://microsoft-my.sharepoint.com/:w:/p/kgukov/EfsOsNQuV2JDhLmy_wgTkY0BxLxwptQ2BhgKhEfdFRvnfQ?e=Pine3B).

## To Reproduce:

Try to create a deployment with the name that already exists:
- `az iot edge deployment create --content {} --deployment-id {} --hub-name {} --target-condition {}`

## Expected Behavior

Error w/o stacktrace

## Environment Summary
```
macOS-11.2-x86_64-i386-64bit
Python 3.8.8
Installer: HOMEBREW

azure-cli 2.20.0

Extensions:
kusto 0.2.0
azure-iot 0.10.9
interactive 0.4.4

```

**Comment by yonzhan** [comment]
iot

**Comment by vilit1** [comment]
Hi @gukoff,

I cannot reproduce the stack trace leak. Can you update your version of azure-iot and check if you still see the stack trace leak?

**Comment by vilit1** [comment]
Closing the issue due to no response. If you still need help with this issue, please re-open.
