### ISSUE TITLE
[Network] Allow auto-creating a public IP as part of creating a NIC

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1730]
The `az vm create` and `az network lb create` commands both allow auto-creating a referenced public IP if it doesn't already exist. This behavior is great, and it would be nice if the `az network nic create` command supported this as well, since it is the other resource type that can be logically associated with a public IP.

**Comment by tjprescott** [comment]
We'll look into adding support for this. Thanks for the feedback!

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
