### ISSUE TITLE
Blob Directory Exists replacement?

### ISSUE THREAD

**Issue by Tbohunek** [Azure/azure-cli#17306]
Hi,

The command `az storage blob directory exists` does not return folders that are not represented by an empty file. For blob `folder/file.txt` the `directory exists -d folder` is `false`.

I see that the command is on deprecation path, however `az storage fs directory exists` does not work for blobs. What is the right replacement then?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/blob.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/blob.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi ＠Tbohunek, thanks for your feedback. `az storage blob directory exists` is deprecated and it is for ADLS Gen2 account, which do have folder in such account. 
But for blobs in standard storage account, the folder is virtual path not real resource. It is impossible to check virtual path with REST. If you do want to see if the virtual path exists or not, you could consider using `az storage blob list` with `--prefix` and `--prefix` is the virtual path e.g. `folder/`.

**Comment by Tbohunek** [comment]
Thanks @Juliehzl for suggesting `blob list --prefix` - I did not notice that one exists!
I agree that blob directories are virtual, however some abstraction would help: `blob list --prefix` returns a list of blobs, so user needs to handle if empty or not. This could have been virtualized by `blob directory exists` returning `true/false`.
Is that something that could be done?
