### ISSUE TITLE
[Keyvault] MHSM softdelete

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#17304]
**Resource Provider**

**Description of Feature or Work Requested**

**Minimum API Version Required**

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/13282

spec
https://microsoft.sharepoint.com/:w:/t/AzureKeyVault-SDKPSHCLICollaboration/ETixR_Vb365Al7UzP3UVKp0B8IoJweHfwxB5JcbFdTeL7g?e=DkeZrP&CID=A29F108D-CC5B-4C14-B562-5649A476D17F

**Target Date**

MHSM GA 5/10

**Comment by yungezz** [comment]
only need to cover 2 more endpoints:
a.	/subscriptions/{subscriptionId}/providers/Microsoft.KeyVault/locations/{location}/deletedManagedHSMs/{name}
b.	/subscriptions/{subscriptionId}/providers/Microsoft.KeyVault/locations/{location}/deletedManagedHSMs/{name}/purge

**Comment by evelyn-ys** [comment]
Supported by https://github.com/Azure/azure-cli/pull/17834
