### ISSUE TITLE
New feature for Azure Load Balancer

### ISSUE THREAD

**Issue by anavinahar** [Azure/azure-cli#17311]
Due to the nature of the feature, I am not able to put information into a public repo. I will email the details. Once it is more public, I can update this comment. However, I want to make sure CLI team is able to plan for this.

**Comment by yonzhan** [comment]
@msyyc for awareness

**Comment by msyyc** [comment]
@anavinahar Have you sent the e-mail?

**Comment by yonzhan** [comment]
@anavinahar any feedback or update?

**Comment by yonzhan** [comment]
@anavinahar did you send out the email?

**Comment by msyyc** [comment]
@anavinahar  Any update about e-mail: 'RE: CLI for Gateway LB'?
