### ISSUE TITLE
Error "Authentication failed." during az Login

### ISSUE THREAD

**Issue by kumarsen26** [Azure/azure-cli#17310]
I am getting Authenctication Failed as below when trying login into Azure (az login)

![image](https://user-images.githubusercontent.com/3154296/111213563-29bf6400-85d1-11eb-846f-b5ccb6fdc7c1.png)

I am not sure what is the reason. 

Kindly check.

**Comment by andrewlehmann-whs** [comment]
I'm getting the same issue. There's currently an issue with Azure AD that you can read more about on the status site, which is likely the reason for this. https://status.azure.com/en-us/status

**Comment by WongyuChoi** [comment]
Same issue here. We are experiencing enterprise-wide issues, not only with Azure CLI but also with many MS products with AD. Thanks for the status update.

**Comment by yonzhan** [comment]
Azure AD server-side issue.

**Comment by andrewlehmann-whs** [comment]
This issue has been resolved for me since a couple hours after the original question was posted. Can this be closed?

**Comment by kumarsen26** [comment]
@andrewlehmann-whs Yes this can be closed.
