### ISSUE TITLE
terminal colour settings

### ISSUE THREAD

**Issue by Skmonkay** [Azure/azure-cli#17325]
**Resource Provider**

**Description of Feature or Work Requested**

**Minimum API Version Required**

**Swagger Link**

**Target Date**

**Comment by Skmonkay** [comment]
Hi,

I can't find out how to either reset or change the Azure CLI Cloud Shell terminal settings.  I have larger scripts now and find the black background I changed it to difficult to use.

Thanks.

**Comment by yonzhan** [comment]
color

**Comment by Skmonkay** [comment]
Tried it. 

Can you give me more?

Alan

**Comment by Skmonkay** [comment]
az config set core.no_color=true  # no change
reset # no change

az config --help # nothing

Microsoft Docs for "color" in AZ CLI # nothing

**Comment by jiasli** [comment]
Hi @Skmonkay, apologize for the confusion. @yonzhan is only triaging this issue indicating we have received your request.

Could you share a screenshot of what you are seeing, so that I can better understand your requirement?

**Comment by Skmonkay** [comment]
![image](https://user-images.githubusercontent.com/78912796/111481570-01e41380-872b-11eb-9316-d2e0552f5148.png)

**Comment by Skmonkay** [comment]
This is Bash.  Only a black background for now.  Very hard to see coding.

![image](https://user-images.githubusercontent.com/78912796/111481734-2a6c0d80-872b-11eb-8ae4-b1fb0cb74188.png)

**Comment by Skmonkay** [comment]
And in PowerShell it's really nice with the blue default backgroud:

![image](https://user-images.githubusercontent.com/78912796/111482092-7b7c0180-872b-11eb-97b5-d232c11098f9.png)

**Comment by jiasli** [comment]
@Skmonkay, I see what you are talking about. 

Azure CLI `az` is simply a command line executable running on Cloud Shell. It has nothing to do with the black background of Cloud Shell. In other words, the black background of Cloud Shell is out of the control of Azure CLI.

[This screenshot](https://github.com/Azure/azure-cli/issues/17325#issuecomment-801116114) you shared is coming from `vi`, right?

### My repo

I can see the same result while running `vi .bashrc`:

![image](https://user-images.githubusercontent.com/4003950/111565178-ea159980-87d5-11eb-9d57-2e1178789244.png)

PowerShell terminal doesn't look better for `vi`:

![image](https://user-images.githubusercontent.com/4003950/111564763-40360d00-87d5-11eb-9c24-5c3708e98f42.png)

### Solution 1: Change font to Monospace

You may change the font to **Monospace** which is bolder than **Courier New**.

![image](https://user-images.githubusercontent.com/4003950/111564297-7626c180-87d4-11eb-9bd8-a7edb13b9026.png)

### Solution 2: Use VS Code editor

The [VS Code editor](https://docs.microsoft.com/en-us/azure/cloud-shell/using-cloud-shell-editor) (GUI) are available for both Bash and PowerShell:

![image](https://user-images.githubusercontent.com/4003950/111564597-f0efdc80-87d4-11eb-9b31-bab1b101b063.png)

Note that the file extension `.sh` must be included in the file name to get syntax highlighting.

**Comment by jiasli** [comment]
The colors in Cloud Shell (including the background) are not configurable, and that's why Azure CLI hardcodes RGB colors to get better visual effect in Cloud Shell (#17283).

I have also created https://github.com/Azure/CloudShell/issues/84 to track this readability issue.

**Comment by Skmonkay** [comment]
Hi,

Yeah, I came to the same conclusions as you.  I'll have to live with it and stick with the VS Code Editor.

Thanks.

Alan

**Comment by jiasli** [comment]
@Skmonkay, I am glad to know the workaround works for you. You may also vote on these issues:

- https://github.com/Azure/CloudShell/issues/84
- https://feedback.azure.com/forums/598699-azure-cloud-shell/suggestions/34656385-font-background-color
- https://feedback.azure.com/forums/598699-azure-cloud-shell/suggestions/35185162-the-red-on-blue-can-be-hard-to-read-for-color-cha
