### ISSUE TITLE
Unable to Set HeathCheck Path

### ISSUE THREAD

**Issue by kmkelly2015** [Azure/azure-cli#17328]
$HealthPath = @{ "healthCheckPath" = "/HealthApi" } | ConvertTo-Json
az webapp config set --subscription $SUB --resource-group $RG --name $Name --generic-configurations $HealthPath

## Describe the bug

**Command Name**
`az webapp config set`

**Errors:**
```
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
azure/cli/core/util.py, ln 510, in shell_safe_json_parse
    return json.loads(json_or_dict_string, strict=strict)
lib/python3.6/json/__init__.py, ln 367, in loads
    return cls(**kw).decode(s)
lib/python3.6/json/decoder.py, ln 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.6/json/decoder.py, ln 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

...

cli/command_modules/appservice/custom.py, ln 1184, in update_site_configs
    config_name, value = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config set --subscription {} --resource-group {} --name {} --generic-configurations {} {}`

## Environment Summary
```
Linux-4.15.0-1108-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.20.0

Extensions:
virtual-wan 0.2.4
ip-group 0.1.2
azure-firewall 0.9.0
ai-examples 0.2.5

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by panchagnula** [comment]
Please check quoting issues https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#quoting-issues based on the terminal being used. Hope this helps.
