### ISSUE TITLE
Container exec -  ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by Friedrg** [Azure/azure-cli#17326]
## Describe the bug

We are trying to connect to a running container. We see a blocked access by the firewall on 152.199.19.160. The container is running in a private section and cannot be accessed via the internet.

**Command Name**
`az container exec`

**Errors:**
```
[Errno 104] Connection reset by peer
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 660, in execute
    raise ex
cli/core/commands/__init__.py, ln 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 716, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.6/site-packages/six.py, ln 703, in reraise
    raise value
...
az/lib/python3.6/ssl.py, ln 407, in wrap_socket
    _context=self, _session=session)
az/lib/python3.6/ssl.py, ln 817, in __init__
    self.do_handshake()
az/lib/python3.6/ssl.py, ln 1077, in do_handshake
    self._sslobj.do_handshake()
az/lib/python3.6/ssl.py, ln 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container exec --resource-group {} --name {} --container-name {} --exec-command {} --debug`

## Expected Behavior
Command is '/bin/bash' - expected is executed bash in container

## Environment Summary
```
Linux-5.4.0-65-generic-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.20.0

```

**Comment by yonzhan** [comment]
container

**Comment by Friedrg** [comment]
We found it - it was a wrong config on the NGINX running in the container
Thanks
