### ISSUE TITLE
[Network] Default user-defined routes to "VirtualAppliance" if a next hop IP is specified

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1733]
Would it be reasonable for the `--next-hop-type` parameter of the `az network route-table route create` command to have a default value? Perhaps either always defaulting to 'VirtualAppliance` (is this the most common type?), or defaulting to `VirtualAppliance` if a `--next-hop-ip-address` is specified (since only virtual appliances can have a next hop IP) or `None` otherwise (or whatever other heuristic made sense).

Needing to specify `--next-hop-type VirtualAppliance` in order to creates route between VMs in a subnet seems a tad verbose (as compared to other similar CLIs), and I was just curious if a sensible default could be applied here for common scenarios.

**Comment by tjprescott** [comment]
It's a good suggestion. Right now we simply take the defaults from Xplat, but we can work with the RouteTable team to potentially come up with something better.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
