### ISSUE TITLE
"az functionapp function delete" Returns success but did not delete function

### ISSUE THREAD

**Issue by jonathan-shapiro-msf** [Azure/azure-cli#17331]
I ran the cli command below:
```
az functionapp function delete -g <resource_group> -n <function_app_name> --function-name <function_name>
```

Then, I got the return statement 
```
"Successfully deleted function '<function_name>' from app '<fucntion_app_name>'"
```

However, when I go on to the UI, the function is still present and can be enabled/disabled as normal. The command doesn't appear to have deleted the function at all.

My function ID is: `Id=d6620d81-4e34-47aa-896b-d969340a3e07`

**Comment by jonathan-shapiro-msf** [comment]
Was this ever resolved?

**Comment by yonzhan** [comment]
cc @ahmedelnably, @fabiocav to take a look

**Comment by balag0** [comment]
Unfortunately I dont think we have the logs from the original incident anymore. Could some one please share a more recent instance?

**Comment by jonathan-shapiro-msf** [comment]
I tested again yesterday and had the same output as my first post. I did notice the functions left the UI when I pushed new ones up from VSCode, however.
