### ISSUE TITLE
When using --protocols parameter in apim api update I encounter a list object has no attribute 'split'

### ISSUE THREAD

**Issue by limelobo** [Azure/azure-cli#17330]
## Describe the bug

**Command Name**
`az apim api update`

**Errors:**
```
'list' object has no attribute 'split'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 660, in execute
    raise ex
cli/core/commands/__init__.py, ln 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/core/commands/arm.py, ln 527, in handler
    instance = custom_function(instance=instance, **custom_func_args)
cli/command_modules/apim/custom.py, ln 235, in update_apim_api
    instance.protocols = protocols.split(',')
AttributeError: 'list' object has no attribute 'split'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim api update --service-name {} --resource-group {} --api-id {} --display-name {} --path {} --protocols {} --service-url {} --subscription-key-header-name {} --subscription-key-query-param-name {} --subscription-required {}`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.8
Installer: HOMEBREW

azure-cli 2.20.0

Extensions:
logic 0.1.2
azure-devops 0.18.0
application-insights 0.1.9

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by DreamlessA** [comment]
Issue resolved with https://github.com/Azure/azure-cli/pull/18605
