### ISSUE TITLE
Web App created with local git defaults to "main" branch when "master" branch is the default for deployment

### ISSUE THREAD

**Issue by mrsquish** [Azure/azure-cli#17335]
**Design Fault - Description**
When creating a Web App with the option for local-git deployment. The branch that gets created is "main". Whereas the branch used for deployment (by default) is master. This causes some confusion and is only fixed by another call to change the default deployment branch to "main"

**To Reproduce**
[Azure Cli]
az group create -n "FooyFooDevTest" -l australiaeast
az appservice plan create -n FooyFooDevTestAppPlan -l australiaeast -g FooyFooDevTest --sku F1 -l australiaeast
az webapp create -g FooyFooDevTest -p FooyFooDevTestAppPlan -n FooyFooDevTestUiApp --runtime "node|10.14" --deployment-local-git

[Powershell] - (Requires a $deploy variable pointing at a temp path, and a $sourcePath variable pointing at an Angular Cli production build with dist folder)
mkdir $deploy
cd $deploy
git clone 'https://deploy.fooyfoo.com.au:<redacted>@FooyFoodevtestuiapp.scm.azurewebsites.net/FooyFooDevTestUiApp.git' .
if (Test-Path (Join-Path $deploy 'dist')) { Remove-Item (Join-Path $deploy 'dist') -Recurse -Force -Confirm:$false }
Copy-Item -Path $sourcePath -Destination $deploy -Recurse -Force
git add .
git commit -m "On Prem Test release"
git push 

**Expected behavior**
The above should work without having to use the below additional step to configure the app.
az webapp config appsettings set -g FooyFooDevTest -n FooyFooDevTestUiApp --settings deployment_branch=main

**Environment summary**
azure-cli                         2.20.0
core                              2.20.0
telemetry                          1.0.6
Azure Cli on Windows

**Comment by yungezz** [comment]
route to appropriate team

**Comment by mrsquish** [comment]
This seems to be resolved, the branch that get's created by default is now back to "master"
