### ISSUE TITLE
Missing Python modules azure-storage-blob and azure-eventhub

### ISSUE THREAD

**Issue by trevors20** [Azure/azure-cli#17347]
Azure-cli version: 2.20.0

I have an azure-cli extension that requires the python modules azure-storage-blob and azure-eventhub.
It looks like the azure-cli uses a private version of python and those modules are not installed in that version of python.

What is the best and recommended way to install these python modules into the private version of python that the azure-cli is using?

In my "setup.py" I have specified that I have a dependency on the modules like this:
DEPENDENCIES = ['azure-eventhub>=5.2.0', 'azure-storage-blob>=12.4.0']

But, these dependencies do not get installed when I install the extension.
Is there something that I'm missing?  That is what I was expecting to happen.

Any recommendations would be great.  Thank you.

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @trevors20, for `azure-storage-blob`, we will recommend to use `azure-multiple-storage`, which already has storage blob support. 
But if you want to add dependency for your extension, your method is right and you can see here 
https://github.com/Azure/azure-cli-extensions/blob/97f2afc5a0f707505a650d4f92cbd874688b09cc/src/db-up/setup.py#L25-L29. For such dependencies, it will be installed in extension folder, typically in `.Azure/cliextensions/<extension name>`, which may be why you don't see the package.

**Comment by yonzhan** [comment]
Hi @trevors20, any feedback or update?
