### ISSUE TITLE
cannot upload and unzip large zip

### ISSUE THREAD

**Issue by NON2057** [Azure/azure-cli#17341]
## Describe the bug

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py, ln 233, in invoke
azure\cli\core\commands\__init__.py, ln 660, in execute
azure\cli\core\commands\__init__.py, ln 723, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 716, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-l7ikczg1\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 694, in _run_job
azure\cli\core\commands\__init__.py, ln 331, in __call__
pip-unpacked-wheel-sc_lkrar\azure\cli\core\__init__.py, ln 808, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 395, in enable_zip_deploy_webapp
azure\cli\command_modules\appservice\custom.py, ln 422, in enable_zip_deploy
MemoryError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip -g {} -n {} --src {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.20.0

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by RakeshMohanMSFT** [comment]
@NON2057 We sincerely apologies for the delay. Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and retry.
