### ISSUE TITLE
Document need to be updated

### ISSUE THREAD

**Issue by anweshs-ms** [Azure/azure-cli#17345]
[Enter feedback here]
Hi Team, 

When we use the "az sql server tde-key set" command from CLI, it is failing with "ServerKeyNotFound" error and this is because there is a prerequisite step before using the "az sql server tde-key set" command which is to use "az sql server key create" command. 

Following is the sequence of commands that need to be used in order to set a CMK TDE encryption Key for Azure SQL Server. 

1. az sql server key create --resource-group <resource group> --server <SQL Server> --kid  <Key ID>
2. az sql server tde-key set --debug --server <sql server name> --resource-group <resource group name> --server-key-type AzureKeyVault --kid <https://<keyvaultname>.vault.azure.net/keys/<key name>/<KeyId>

This has not been mentioned in the document and CSS received a case when customer is failing to set the TDE encryption key using CLI command listed in document https://docs.microsoft.com/en-us/cli/azure/sql/server/tde-key?view=azure-cli-latest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea369391-5bd1-845a-83c8-f544d30728db
* Version Independent ID: 251e46ee-9f7a-2e64-8ae0-30837b23897b
* Content: [az sql server tde-key](https://docs.microsoft.com/en-us/cli/azure/sql/server/tde-key?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/sql/server/tde-key.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/sql/server/tde-key.yml)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
sql
