### ISSUE TITLE
Unable to create a log analytics data export rule, either python exception or "table doesn't exist"

### ISSUE THREAD

**Issue by airwalk-neilashbysenior** [Azure/azure-cli#17342]
## Describe the bug
Command doesn't create rule as it says no table (UpdateRunProgress) in database or I get a python exception. The table does exist and I did try creating the rule while data was going into the table. I have also tried the command with parameters as well as environment variables. It is going to a preexisting eventhub.

I had the same behaviour with the same command but on the table Update but managed to get the command to go through. I don't know why this was, it was just random and a result of rerunning the command lots of times through frustration.

**Command Name**
`az monitor log-analytics workspace data-export create`

**Errors:**
```
(InvalidOperationArgument) Table UpdateRunProgress does not exist in the workspace.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor log-analytics workspace data-export create --resource-group {} --workspace-name {} --name {} --tables {} --destination {}`

### Error

```
The command failed with an unexpected error. Here is the traceback:
Cannot deserialize content-type: text/plain
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 660, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/monitor/_exception_handler.py", line 23, in exception_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 694, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 808, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/monitor/operations/log_analytics_workspace.py", line 131, in create_log_analytics_workspace_data_exports
    return client.create_or_update(resource_group_name, workspace_name, data_export_name, data_export)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/loganalytics/operations/_data_exports_operations.py", line 185, in create_or_update
    error = self._deserialize(_models.DataExportErrorResponse, response)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1367, in __call__
    data = self._unpack_content(response_data, content_type)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1541, in _unpack_content
    raw_data.headers
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/universal.py", line 226, in deserialize_from_http_generics
    return cls.deserialize_from_text(body_bytes, content_type)
  File "/opt/az/lib/python3.6/site-packages/msrest/pipeline/universal.py", line 203, in deserialize_from_text
    raise DeserializationError("Cannot deserialize content-type: {}".format(content_type))
msrest.exceptions.DeserializationError: Cannot deserialize content-type: text/plain
```

OR

```
(InvalidOperationArgument) Table UpdateRunProgress does not exist in the workspace.
```

## Environment Summary
```
Linux-4.15.0-1108-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.20.0

Extensions:
ai-examples 0.2.5

```

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
Same as https://github.com/Azure/azure-cli/issues/17231

**Comment by airwalk-neilashbysenior** [comment]
> Same as #17231

Currently I only have one rule. This would be a second rule. I have had two rules before in testing so I don't think this is due to exceeding a limit?

**Comment by airwalk-neilashbysenior** [comment]
> Same as #17231

I have one rule from the workspace going into the same event hub namespace already. That is for the Update table. The command that fails is for the UpdateRunProgress table and wants to go into the same namespace but a different event hub.

I had previously a rule for this, which I deleted. The rule listing command shows only one rule, the one for Update.

``` 
az monitor log-analytics workspace data-export list --resource-group xxx --workspace-name xxx

[
  {
    "createdDate": "Wed, 17 Mar 2021 08:57:48 GMT",
    "dataExportId": xxx",
    "enable": true,
    "eventHubName": "law-update",
    "id": "/subscriptions/xxx/resourcegroups/xxx/providers/microsoft.operationalinsights/workspaces/xxx/dataexports/rl-data-export-update",
    "lastModifiedDate": "Wed, 17 Mar 2021 08:57:48 GMT",
    "name": "rl-data-export-update",
    "resourceGroup": "xxx",
    "resourceId": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.EventHub/namespaces/xxx",
    "tableNames": [
      "Update"
    ],
    "type": "Microsoft.OperationalInsights/workspaces/export",
    "typePropertiesDestinationType": "EventHub"
  }
]
```

However, --debug reveals this:

```
You are adding a desiccation that is already defined in rule: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.EventHub/namespaces/xxx. A destination can be included in a single rule – you can create 10 export rules to 10 different destinations.
```

Is there a way to check that the old rule been fully deleted?

**Comment by kairu-ms** [comment]
That's a good question. I think the limitation is on workspaces level. You can only add a single rule for your workspace. Because when you create a data-export rule, the command never needs a event hub name. And prefix of the rule ID is workspace ID.

**Comment by kairu-ms** [comment]
> Thanks for the information. My current setup of precreating the event hubs and creating two rules through Terraform will not work then.

Yes, the limitation is on service side. If they are on different workspaces, I think it can work.

**Comment by airwalk-neilashbysenior** [comment]
Thanks for clarification.
I did find that you can precreate the event hubs with the name tablename and "am-" prefix (e.g. am-updates), so that at least you can control the event hub settings. This is better for me than letting Azure Monitor create the event hubs.
I'll close this issue.
