### ISSUE TITLE
How to query postgresql?

### ISSUE THREAD

**Issue by cveld** [Azure/azure-cli#17365]
Is it possible to execute a query on a postgresql instance with the az cli?
To enable the Timescaledb extension this query must be executed:

`CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a0d6be8-0e95-0994-ace2-235d909d4714
* Version Independent ID: 0920947d-a29b-9536-9101-503685479d94
* Content: [az postgres](https://docs.microsoft.com/en-us/cli/azure/postgres?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/postgres.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/postgres.yml)
* Service: **postgresql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
postgresql

**Comment by sr-msft** [comment]
Hello @cveld, AZ CLI is not a full-fledged PostgreSQL client. You have to invoke Postgres clients like psql or pgAdmin to connect to the server and you can execute the create extension command.   

For example: 
$ psql "host=myTargetServer port=5432 dbname=postgres user=myUser password=###### sslmode=mySSLmode"
