### ISSUE TITLE
az aks create says only -g and -n are required, but command doesn't succeed with only those two options

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-cli#17375]
**Describe the bug**
According to [the documentation](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_create), only `-rg` and `-n` are required paramters to `az aks create`. Running `az aks create -g $RESOURCE_GROUP -n $KUBERNETES_CLUSTER_NAME` fails with the following error:

> An RSA key file or key value must be supplied to SSH Key Value. You can use --generate-ssh-keys to let CLI generate one for you

**To Reproduce**
Run `az aks create -g $RESOURCE_GROUP -n $KUBERNETES_CLUSTER_NAME`

**Expected behavior**
It succeeds.

**Environment summary**
Ubuntu 20.04, Bash

az cli details:
```
{
  "azure-cli": "2.20.0",
  "azure-cli-core": "2.20.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

**Additional details**
Alternatively update the documentation to remove the example `az aks create -g MyResourceGroup -n MyManagedCluster`, which suggests that this should work.

**Comment by matthchr** [comment]
This looks like #13171, except that issue doesn't address the: "but the docs say this should work" part of it

**Comment by yungezz** [comment]
route to appropriate team

**Comment by RakeshMohanMSFT** [comment]
This is fixed. Please update to the latest version of az cli [2.43.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)
![image](https://user-images.githubusercontent.com/49954584/210749714-931bb3af-fa11-4e8a-ad03-c2642d2c7d73.png)
