### ISSUE TITLE
Cannot delete postgres database with CLI

### ISSUE THREAD

**Issue by piersfinlayson** [Azure/azure-cli#17384]
Trying to delete a postgres database I get the error listed below.

**Command Name**
`az postgres db delete`

**Errors:**
```
Deployment failed. Correlation ID: 3239bb20-1e35-43b9-8dfb-bc4fed78a5aa. Cannot drop system database 'postgres'.
```

## To Reproduce:

Have been running django webapp connected to this postgres database, but created a new database and switched over to that - so now want to delete this old database.  I've tried repeatedly to delete the database with this command but always get the same error.

- `az postgres db delete -n {} -s {} -g {}`

## Expected Behavior

Database is deleted.

## Environment Summary
```
Linux-4.19.104-microsoft-standard-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.20.0

Extensions:
db-up 0.2.1

```

**Comment by piersfinlayson** [comment]
I also tried creating a database with the same name (and server-name and resource-group) in case the CLI's view of the database had got into a duff state per this comment, but no success then deleting:

https://github.com/Azure/azure-cli/issues/7285#issuecomment-420717903

**Comment by yonzhan** [comment]
postgres

**Comment by nachoalonsoportillo** [comment]
Not reproduceable. It was most probably caused by the database being accessed by other users while trying to drop it.

@yonzhan, please close as not reproduceable.
