### ISSUE TITLE
If resource group of Vault and VM are different

### ISSUE THREAD

**Issue by sanghoon-damien-yang** [Azure/azure-cli#17382]
[Enter feedback here]

I've tested az backup protection enable-for-vm  when RG from Vault and VM are different,
I front the error like below.

sanghoon@Azure:~$ az backup protection enable-for-vm --resource-group SanghoonYang_KoreaAzureLab --vault-name KorCen-Vault --vm DiskTest-01 --policy-name DefaultPolicy --disk-list-setting exclude --diskslist 0
Command group 'backup' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
_**The Resource 'Microsoft.RecoveryServices/vaults/KorCen-Vault' under resource group 'SanghoonYang_KoreaAzureLab' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix**_
sanghoon@Azure:~$
sanghoon@Azure:~$
sanghoon@Azure:~$ az backup protection enable-for-vm --resource-group Readiness01 --vault-name KorCen-Vault --vm DiskTest-01 --policy-name DefaultPolicy --disk-list-setting exclude --diskslist 0
Command group 'backup' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
**_(ResourceNotFound) The Resource 'Microsoft.Compute/virtualMachines/DiskTest-01' under resource group 'Readiness01' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix_**

Any other parameter for specifying each resource's resource group?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48754d22-3349-4e45-a315-126569fe9047
* Version Independent ID: 72e517fa-8000-0ec4-1b33-853901d75cb2
* Content: [az backup protection](https://docs.microsoft.com/en-us/cli/azure/backup/protection?view=azure-cli-latest#az_backup_protection_enable_for_vm)
* Content Source: [latest/docs-ref-autogen/backup/protection.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/backup/protection.yml)
* Service: **backup**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by pvrk** [comment]
@sanghoon-damien-yang : Please pass the complete VM ID as VM as mentioned in this [document](https://docs.microsoft.com/azure/backup/quick-backup-vm-cli#enable-backup-for-an-azure-vm) in the 'Note' section

**Comment by pvrk** [comment]
Closing this since the solution is given. Can re-open if that doesn't help.
