### ISSUE TITLE
Error while running azure cli check-acr command

### ISSUE THREAD

**Issue by gbakthavatchalam** [Azure/azure-cli#17397]
## Describe the bug

**Command Name**
`az aks check-acr`

**Errors:**
```
the following arguments are required: --resource-group/-g, --name/-n, --acr
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks check-acr`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.8
Installer: HOMEBREW

azure-cli 2.20.0

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by RakeshMohanMSFT** [comment]
Its as designed, these are required parameter of the command https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-check-acr.

Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
