### ISSUE TITLE
Bicep related live test issue

### ISSUE THREAD

**Issue by zhoxing-ms** [Azure/azure-cli#17390]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

For both tests `test_subscription_level_deployment_with_bicep` and `test_management_group_level_deployment_with_bicep`, the following errors occurred:

> cli.azure.cli.core.azclierror:azclierror.py:67 /home/vsts/work/1/azure-cli/src/azure-cli/azure/cli/command_modules/resource/tests/latest/policy_definition_deploy.bicep(1,77) : Error BCP135: Scope "resourceGroup" is not valid for this resource type. Permitted scopes: "managementGroup", "subscription".

@shenglol Because this is bicep related issues, please help to investigate it.

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Bicep
