### ISSUE TITLE
"For more specific examples, use: az find" doesn't really give more examples

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#17398]
**Describe the bug**

All commands' help (like `az feedback --help`) shows

```
> az feedback -h

For more specific examples, use: az find "az feedback"
```

However, if a user really runs `az find "az feedback"`, the output can sometimes give no helpful information:

```
> az find "az feedback"
Finding examples...

Sorry I am not able to help with [az feedback].
Try typing the beginning of a command e.g. az vm.
Please let us know how we are doing: https://aka.ms/azureclihats
```

This causes frustration and distrust.

**Expected behavior**

Possible solutions:

1. `For more specific examples, use: az find` should be hidden if no more examples can be given, but this will cause performance problem as network request is necessary.
2. Refine the wording to make the description more accurate, like:
    ```diff
    - For more specific examples, use: az find "az feedback"
    + To search the AI knowledge base for examples, run `az find "az feedback"`
    ```

_Originally posted by by @dkreeft in https://github.com/Azure/azure-cli/issues/17393#issue-837586433_

**Comment by yonzhan** [comment]
route to Aladdin team to investigate.
