### ISSUE TITLE
Add 'az feedback' examples

### ISSUE THREAD

**Issue by dkreeft** [Azure/azure-cli#17393]
**Is your feature request related to a problem? Please describe.**
I came across the `az feedback` command that allows you to send feedback to the Azure CLI team. Unfortunately, the documentation of the feature is not so clear to me. Am I supposed to send a string with my feedback? Executing `az feedback --help` suggest the following:

> For more specific examples, use: az find "az feedback"

However, executing `az find "az feedback"` does not return any examples of how to use the feedback command. Is this by design? If so, maybe omit the above suggestion of finding specific examples.

**Describe the solution you'd like**
I would like to see examples of how to use `az feedback` in the documentation, when I run `az find "az feedback"` or at least have some more information on how to send my feedback when I run `az feedback --help`.

**Comment by jiasli** [comment]
Hi @dkreeft, `az feedback` is an interactive command. It creates the GitHub issue body automatically for you. 

Simply run `az feedback` and see what you get! 😀

**Comment by dkreeft** [comment]
Great, thanks for your swift reply and action!

**Comment by jiasli** [comment]
Let me refine the help message in #17396 and track the `az find` problem in #17398.
