### ISSUE TITLE
az keyvault certificate list --id

### ISSUE THREAD

**Issue by kaletkamk** [Azure/azure-cli#17399]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
According to the documentation az keyvault certificate list --id (kv_id) should list all of the certificates. Other parameters should not be required when using --id 
But when you run  az keyvault certificate list --id (kv_id) you get response 'vaultBaseUrl'

```
Marcin@XPS  D:                                                                                               [15:00]
❯ az keyvault certificate list --id /subscriptions/7a77d45b-dbdc-4831-b3d9-e5a9c23fc1af/resourceGroups/AZ-RG-CS-APGv2-NA-Prod-01/providers/Microsoft.KeyVault/vaults/AZ-KV-CS-Cloud-EASTUS-2
'vaultBaseUrl'
Marcin@XPS  D:                                                                                               [15:01]
❯
```
**To Reproduce**
az keyvault certificate list --id (kv_id) 
**Expected behavior**
List of certificates
**Environment summary**
azure-cli                         2.20.0

core                              2.20.0
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0
azure-firewall                     0.9.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Marcin\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Additional context**

**Comment by yungezz** [comment]
hi @houk-ms,  could you pls have a look?

**Comment by chwarr** [comment]
I'm seeing the same behavior in 2.30.0 on Windows.

```text
PS> az keyvault certificate list --id /subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.KeyVault/vaults/redacted  --output json
'vaultBaseUrl'
PS> $LASTEXITCODE
1
```

Here's my  environment summary:

```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0

Extensions:
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
@evelyn-ys to help with

**Comment by evelyn-ys** [comment]
Hi @chwarr and @kaletkamk, sorry for the ambiguous param `--id`. In fact, it should be `Vault URI` instead of `Resource ID`
![image](https://user-images.githubusercontent.com/10227683/141926374-9d2de41e-3073-4441-b963-822016c2d3f8.png)
See my results:
![image](https://user-images.githubusercontent.com/10227683/141926435-16c37068-66e8-41a5-90b2-c0e684321c55.png)

**Comment by chwarr** [comment]
Yup. Passing the vault's URI for `--id` works. Thanks!

I've created [a PR to revise the help text for the `--id` parameter](https://github.com/Azure/azure-cli/pull/20369/files).
