### ISSUE TITLE
CosmosDB Delete Command Fails But Still Appears to Delete the Database

### ISSUE THREAD

**Issue by CMihalcik** [Azure/azure-cli#17418]
Running the following command as an inline script in an `AzureCLI@2` task in an Azure DevOps Pipeline leads to the error below. It appears that the database is actually deleted though.

Repro Command
```
az cosmosdb sql database delete -y `
  -n db-name `
  -g resource-group `
  -a db-account
```

Observed Error
```
2021-03-23T14:00:17.5435278Z ERROR: Deployment failed. Correlation ID: addc0632-1b37-468b-a3b2-cd04d21f2b42. The client 'uuid' with object id 'uuid' does not have authorization to perform action 'Microsoft.DocumentDB/operationsStatus/read' over scope '/subscriptions/uuid' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

Expected Behavior

The database is deleted and the command completes successfully.

**Comment by yonzhan** [comment]
CosmosDB

**Comment by MehaKaushik** [comment]
Hi @CMihalcik from the message it looks like the command failed on polling on the operation status. Since the initial Put request to cosmos-db went through the database was deleted. It is only on polling on the operation that the request failed.

**Comment by MehaKaushik** [comment]
AAD team to recommed solution for: 

> The client 'uuid' with object id 'uuid' does not have authorization to perform action 'Microsoft.DocumentDB/operationsStatus/read' over scope '/subscriptions/uuid' or the scope is invalid.

**Comment by CMihalcik** [comment]
The task ran without error yesterday. Seems to be resolved. Thanks.
