### ISSUE TITLE
WebApp:Unhelpful error on `az webapp up`

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-cli#17419]
## Describe the bug
When trying to use `az webapp up` I was met with an 'Unauthorized' error message and that let me on a wild chase of permission issues with my account, RBAC rules, etc. as it led me to believe that my user account didn't have access to create the resource.

Turns out that was an unhelpful message and the actual underlying exception message would have saved me endless time:
```
msrest.http_logger: {"Code":"Unauthorized","Message":"This subscription has reached the limit of 1 Free Linux app service plan(s) it can create in this region. Please choose a different sku or region.","Target":null,"Details":[{"Message":"This subscription has reached the limit of 1 Free Linux app service plan(s) it can create in this region. Please choose a different sku or region."},{"Code":"Unauthorized"},{"ErrorEntity":{"ExtendedCode":"52041","MessageTemplate":"This subscription has reached the limit of {0} Free Linux app service plan(s) it can create in this region. Please choose a different sku or region.","Parameters":["1"],"Code":"Unauthorized","Message":"This subscription has reached the limit of 1 Free Linux app service plan(s) it can create in this region. Please choose a different sku or region."}}],"Innererror":null}
msrest.exceptions: Operation returned an invalid status code 'Unauthorized'
```

The specific portion: `This subscription has reached the limit of 1 Free Linux app service plan(s) it can create in this region. Please choose a different sku or region` would have alerted me immediately to the issue and I could have resolved it in 5 minutes rather than hours.  Alternatively the default error message of `Operation returned an invalid status code 'Unauthorized'` could have told me to turn on `--debug` option for more details and that would have equally saved me time.  As it stands today, the message is not helpful to the user in directing them to resolution.

**Command Name**
`az webapp up`

**Errors:**
```
Operation returned an invalid status code 'Unauthorized'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --os-type {} --debug`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.21.0

```

**Comment by Kotasudhakarreddy** [comment]
@panchagnula - seems this error has been returned by the API. could you please check this one.

**Comment by panchagnula** [comment]
@timheuer apologize but the detailed error message currently is not displayed by default in CLI commands & --debug is usually the recommended approach for CLI commands - you do have a good point about adding the info about using --debug to all error/warning messages. Will check with core-cli folks on 
1. displaying detailed error messages as default
2. exposing the use of --debug.
@yonzhan -- will start an email thread on this discussion internally -FYI.

**Comment by timheuer** [comment]
Thank you @panchagnula -- just looking for a little more hinting as the current state was unhelpful and didn't direct me to how it could be more helpful.
