### ISSUE TITLE
Fix `az ad app permission grant` in the docs

### ISSUE THREAD

**Issue by dgroh** [Azure/azure-cli#17416]
**Describe the bug**
The docs for [az ad app permission add](https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest#az_ad_app_permission_add) says to invoke `az ad app permission grant`, but when invoking it a **404 error** is shown. Workaround is to use `az ad app permission admin-consent` instead.

![image](https://user-images.githubusercontent.com/16785357/112183633-bc2dbc00-8bfe-11eb-8323-890334767a23.png)

**To Reproduce**

  Run the follwoing commands with powershell:
   ```powershell
    $appRegistration = az ad app create `
        --display-name "AppName" `
        --reply-urls "http://localhost/auth" `
        --oauth2-allow-implicit-flow true `
        --available-to-other-tenants false `
        -o json | 
    ConvertFrom-Json

    az ad app permission add --id $appRegistration.appId `
        --api '00000003-0000-0000-c000-000000000000' `
        --api-permissions @("c5366453-9fb0-48a5-a156-24f0c49a4b84=Scope", "1ca167d5-1655-44a1-8adf-1414072e1ef9=Scope")

    az ad app permission grant --api 00000003-0000-0000-c000-000000000000 --id $appRegistration.appId
   ```

This error is showing:

![image](https://user-images.githubusercontent.com/16785357/112186457-70304680-8c01-11eb-8006-99c7fba89d77.png)

There is a related issue on StackOverflow about it from a months ago: https://stackoverflow.com/questions/62883453/add-graph-api-via-az-ad-app-permission-fails

**Expected behavior**
The doc should specify when to exactly use it. In case the issue is with the cli, this should be fixed.

**Environment summary**
Powershell and Azure CLI 2.21.0

**Additional context**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The error was refined in https://github.com/Azure/azure-cli/pull/17051. Please see https://github.com/Azure/azure-cli/issues/16862#issuecomment-783922013 for the solution.
