### ISSUE TITLE
Service objective update example is wrong

### ISSUE THREAD

**Issue by dbamaster** [Azure/azure-cli#17420]
[Enter feedback here]

The service objetive in the <code>az sql dw update</code> example is wrong. It has "S1" instead of something like "DW1000c".

Suggested example:

```bash
az sql dw update --name <MyDW> --resource-group <MyRG> --server <MyServer> --service-objective DW1000c
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6c6ca27-08d8-9c51-d68e-dad749bf8402
* Version Independent ID: a4e3d208-2717-9761-3968-59bd94308576
* Content: [az sql dw](https://docs.microsoft.com/en-us/cli/azure/sql/dw?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/sql/dw.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/sql/dw.yml)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
sql
