### ISSUE TITLE
webapp:az appservice plan show does not provide correct exit status

### ISSUE THREAD

**Issue by undervillain** [Azure/azure-cli#17424]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
`az appservice plan show` does not provide correct exit status

**To Reproduce**
1. execute `az appservice plan show` with arguments describing a non-existent resource, for instance:

`az appservice plan show --resource-group nonesuch-rg-doesntexist --name nonesuch-app-doesntexist`

**Expected behavior**
non-zero exit status, similar to as provided by other `az <resource> show` commands

**Environment summary**
ubunut 18.04 installed from package

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
Able to repro the issue. Will work on this in future releases.
