### ISSUE TITLE
JSON requires escaped double quotes

### ISSUE THREAD

**Issue by mattsmall1972** [Azure/azure-cli#17436]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When passing JSON to CLI, an error occurs:
az : Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**To Reproduce**
PS C:\Users\msmall.NORTHAMERICA> az monitor diagnostic-settings create `
-n "msmall-01" `
--resource "/subscriptions/<subscriptionid>/resourceGroups/SME/providers/Microsoft.DocumentDB/databaseAccounts/msmall" `
--event-hub "msmall" `
--event-hub-rule "/subscriptions/<subscriptionid>/resourceGroups/Main/providers/Microsoft.EventHub/namespaces/msmall/AuthorizationRules/RootManageSharedAccessKey" `
--storage-account "/subscriptions<subscriptionid>/resourceGroups/Main/providers/Microsoft.Storage/storageAccounts/dbvulnerability" `
--logs '{"category":"QueryRuntimeStatistics","enabled":"true","retentionPolicy":{"days":"6","enabled":"true"}}' 

**Expected behavior**
Command returns as expected

**Environment summary**
 az --version
azure-cli                         2.21.0
core                              2.21.0
telemetry                          1.0.6
Extensions:
resource-graph                     1.0.0
Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.

**Additional context**
Issue is resolved by escaping the double quotes in the JSON:
--logs '[{"category":\"QueryRuntimeStatistics\",\"enabled\":\"true\",\"retentionPolicy\":{\"days\":\"6\",\"enabled\":\"true\"}}]'

**Comment by yonzhan** [comment]
monitor

**Comment by jiasli** [comment]
@mattsmall1972, I believe you are hitting [Quoting issues with PowerShell](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md). That's why double quotes need to be escaped again as `\"` with CMD syntax.

**Comment by jiasli** [comment]
BTW, your string provided in **Additional context** is not rendered correctly. Even though you do escaped double quotes:

![image](https://user-images.githubusercontent.com/4003950/112407396-fd35e580-8d50-11eb-848a-c6871cb0c22e.png)

Markdown removes the backward slash in normal text, so it should be marked as code block to get the raw string displayed:

```
--logs '[{\"category\":\"QueryRuntimeStatistics\",\"enabled\":\"true\",\"retentionPolicy\":{\"days\":\"6\",\"enabled\":\"true\"}}]'
```

**Comment by mattsmall1972** [comment]
@jiasli It appears you are correct that I am running into the known problem. However, is this expected to be fixed or is it by-design?

**Comment by jiasli** [comment]
@mattsmall1972, I am glad to know it works! 

This is a has been a known issue of PowerShell for a long time, but fixing it will actually cause huge breaking changes. It is being traced at https://github.com/PowerShell/PowerShell/issues/1995.

**Comment by lcfrancoi** [comment]
Hi everyone!!

In my case, I ´ve replaced all double quotes by single quote before call the parameter, and set double quote just in the beggining and in the end. Worked like a charm in Powershell Script.

In my scenario, I was calling Powershell from groovy.

changeorderParam is where I have my Json string.

changeorderParam = changeorderParam.replaceAll("\"", "'")
bat "powershell.exe -Executionpolicy bypass -file C:\\Jenkins\\scripts\\engine.ps1 \"${template}\" \"${script}\" \"${branch}\" \"${changeorderParam}\""  

I hope this help someone!
