### ISSUE TITLE
Is there way to set up an Az Cli session with only an access token?

### ISSUE THREAD

**Issue by cveld** [Azure/azure-cli#17452]
In the PowerShell Az modules ecosystem you have the `Connect-AzAccount -AccessToken` option. Is something comparable available for Az CLI?
We have use cases where ideally only an access token is shared instead of a principal id and principal secret.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abfaa54-0895-29f7-f3bb-ff604912b2ac
* Version Independent ID: d1ff3478-8a86-59e4-62ef-449900132a67
* Content: [az account](https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/account.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/account.yml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This feature request is being tracked at https://github.com/Azure/azure-cli/issues/16459. You may vote on that.
