### ISSUE TITLE
I can not az login

### ISSUE THREAD

**Issue by georgeAccnt-GH** [Azure/azure-cli#17458]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I am using a freshly pulled mcr.microsoft.com/azure-cli (as described in https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-dockers)
	run: az login, get the regular:
	To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code A73PMXDXN to authenticate.
	 
	I follow the regular signin process in browser, and in stead of being pointed to phone authentication I get this message:
Help us keep your device secure
Your sign-in was successful but your admin requires the device requesting access to be managed by Microsoft to access this resource.

, and the sign in process in azcli does not resolve.

**To Reproduce**

**Expected behavior**

I should be asked to authenticate via phone, and then az login in azcli should resolve

**Environment summary**

docker run -it --rm --name azcliicon -v $(pwd):/workspace:rw -v /var/run/docker.sock:/var/run/docker.sock mcr.microsoft.com/azure-cli /bin/bash

**Additional context**

**Comment by jiasli** [comment]
This is a known issue of Microsoft tenant. Please see https://github.com/Azure/azure-cli/issues/17273#issuecomment-796384345for for solutions.

**Comment by jiasli** [comment]
For this error message happening in `Microsoft` tenant, it is tracked by https://github.com/Azure/azure-cli/issues/17273.
