### ISSUE TITLE
az cosmosdb : Collection exists and Gremlin graph exists command show different results

### ISSUE THREAD

**Issue by Divyansh00** [Azure/azure-cli#17457]
Repo:

Enable firewall for the cosmos db account
Run the following commands from the test machine, whose IP is not whitelisted in the cosmos db
az cosmosdb collection exists --collection-name $collectionName --db-name $dbName -n $accountName -g $resourceGroupName
az cosmosdb gremlin graph exists -n $collectionName -d $dbName -a $accountName -g $resourceGroupName
Expected result :
Both the command fail to connect to cosmos db ,as the test machine is not whitelisted

Actual :
The Gremlin Graph command is able to access the account and returns whether the graph exists or not, while the first command (az cosmosdb collection exists) fails with Forbidden error.

![image](https://user-images.githubusercontent.com/22240474/112474672-eebded00-8d95-11eb-90ff-80fcbf6d2103.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc8d652-2eda-296f-28ea-8d5f1ea855b3
* Version Independent ID: 80b87995-d339-61e9-1cac-b5c9ad6efe5e
* Content: [az cosmosdb](https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/cosmosdb.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cosmosdb.yml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cosmosdb

**Comment by MehaKaushik** [comment]
Hi @Divyansh00, thanks for opening this issue. az cosmosdb collection  commands are deprecated, we no longer maintain them. That is also the reason we would not want customers to use it. 

I would recommend to rely on az cosmosdb graph commands for your usage. They are maintained actively, if you face any issue in those commands please let us know.

**Comment by MehaKaushik** [comment]
yes this behavior was designed to be like this. The internal implementation of the two commands is different. The deprecated ones use our Data plane which is guarded by firewall properties. The Graph commands use control plane and do not require firewall whitelisting.
