### ISSUE TITLE
az login fails

### ISSUE THREAD

**Issue by ishanic** [Azure/azure-cli#17465]
## Describe the bug

**Command Name**
`az login`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.4.0-70-generic-x86_64-with-debian-buster-sid
Python 3.7.3
Installer: PIP

azure-cli 2.3.1
azure-cli-ml 1.10.0

Extensions:
azure-cli-ml 1.10.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Please provide the error message you see when `az login` fails.

Also, I noticed you are using a very old version `2.3.1`. Please [install the latest Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and see if the issue is gone.
