### ISSUE TITLE
Generate Communication 1.0.0 CLI extension

### ISSUE THREAD

**Issue by memontic-ms** [Azure/azure-cli#17481]
**Resource Provider**

Azure Communication Services (short name: Communication)

**Description of Feature or Work Requested**

Generation of CLI extension
Release 1.0.0 version for GA

Currently the service has a public preview version, 0.1.0, available:
https://github.com/Azure/azure-cli-extensions/tree/master/src/communication

**Minimum API Version Required**

2020-08-20

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/communication/resource-manager/Microsoft.Communication/stable/2020-08-20/CommunicationService.json

**Target Date**

ASAP. Let me know how we can help expedite the process

**Comment by yonzhan** [comment]
Communication

**Comment by jsntcy** [comment]
Close this issue as it's supported by https://github.com/Azure/azure-cli-extensions/pull/3216
