### ISSUE TITLE
<az network public-ip update> Parameter SKU is deprecated

### ISSUE THREAD

**Issue by irenehua** [Azure/azure-cli#17482]
![image](https://user-images.githubusercontent.com/59070966/112699089-546ab180-8e48-11eb-97ef-f751d7b7f978.png)
Why are we deprecating SKU? This is the only CLI command customers can use the upgrade their IP from Basic to Standard

**Comment by yonzhan** [comment]
@msyyc please take a look

**Comment by msyyc** [comment]
The deprecation is to fix https://github.com/Azure/azure-cli/issues/12570. In the future, sku can not be updated after creation for public ip.

**Comment by jsntcy** [comment]
@msyyc, please double check if sku can be upgraded from `Basic` to `Standard`. I guess it cannot be downgraded from `Standard` to `Basic`, but it can be upgraded from `Basic` to `Standard`.

**Comment by msyyc** [comment]
for service, it cannot be downgraded from Standard to Basic, but it can be upgraded from Basic to Standard. So azure-cli keep correspondence with service. We will remove the 'deprecation' message.
