### ISSUE TITLE
az aks get-credentials  does not completed due to The command requires the extension aks-preview

### ISSUE THREAD

**Issue by itsforbrijesh** [Azure/azure-cli#17497]
## Describe the bug

**Command Name**
az aks get-credentials 

**Errors:**
Issue while getting AKS credentials using az cli 

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --name {} -g {}`

az --version 
azure-cli                         2.20.0 *

core                              2.20.0 *
telemetry                          1.0.6

Extensions:
aks-preview                        0.5.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\bdhobale\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

## Expected Behavior
The command should complete with credentials stored in kube config

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: 

azure-cli 2.20.0 *

Extensions:
aks-preview 0.5.6

```

**Comment by itsforbrijesh** [comment]
The command requires the extension aks-preview. Do you want to install it now? The command will continue to run after the extension is installed. (Y/n): Y
Run 'az config set extension.use_dynamic_install=yes_without_prompt' to allow installing extensions without prompt.
Extension 'aks-preview' 0.5.6 is already installed.
It will be updated if available.
No updates available for 'aks-preview'. Use --debug for more information.
The command requires the extension aks-preview. Do you want to install it now? The command will continue to run after the extension is installed. (Y/n): N
The command requires the latest version of extension aks-preview. To install, run 'az extension add --upgrade -n aks-preview'.

**Comment by d0ctajones** [comment]
I am also experiencing this behavior, in multiple versions of the azure-cli docker container and in my local environment. When it goes to install the `aks-preview` extension, it loops forever trying to find updates, ask permission to update, find none, ask permission to update, etc.

Versions I've tried (azure-cli container tags):
- latest
- 2.20.0
- 2.19.0

Here's some output:
```
bash-5.0# az aks get-credentials -n $CLUSTER_NAME -g $RESOURCE_GROUP --subscription $SUBSCRIPTION --admin

The command requires the extension aks-preview. Do you want to install it now? The command will continue to run after the extension is installed. (Y/n): Y
Run 'az config set extension.use_dynamic_install=yes_without_prompt' to allow installing extensions without prompt.
The installed extension 'aks-preview' is in preview.
The command requires the extension aks-preview. Do you want to install it now? The command will continue to run after the extension is installed. (Y/n): Y
Run 'az config set extension.use_dynamic_install=yes_without_prompt' to allow installing extensions without prompt.
Extension 'aks-preview' 0.5.6 is already installed.
It will be updated if available.
No updates available for 'aks-preview'. Use --debug for more information.
The command requires the extension aks-preview. Do you want to install it now? The command will continue to run after the extension is installed. (Y/n): n
The command requires the latest version of extension aks-preview. To install, run 'az extension add --upgrade -n aks-preview'.
```

This area of the `--debug` logs was interesting
```
cli.azure.cli.core.extension.operations: Saved the whl to /root/.azure/cliextensions/aks-preview/aks_preview-0.5.6-py2.py3-none-any.whl
cli.azure.cli.core.extension.operations: The installed extension 'aks-preview' is in preview.
cli.azure.cli.core: Command index has been invalidated.
cli.knack.cli: Command arguments: ['aks', 'get-credentials', '-n', '*****', '-g', '*****', '--subscription', '*****', '--admin', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fae6aec0950>, <function OutputProducer.on_global_arguments at 0x7fae6ade5488>, <function CLIQuery.on_global_arguments at 0x7fae6ae04730>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Command index version or cloud profile is invalid or doesn't match the current command.
cli.azure.cli.core: Command index has been invalidated.
cli.azure.cli.core: No module found from index for '['aks', 'get-credentials', '-n', '*****', '-g', '*****', '--subscription', '*****', '--admin', '--debug']'
cli.azure.cli.core: Loading all modules and extensions
cli.azure.cli.core: Discovered command modules: ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'config', 'configure', 'consumption', 'container', 'cosmosdb', 'databoxedge', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'synapse', 'util', 'vm']
```
Note that it claims that the `aks-preview` extension is installed, but the "Discovered command modules" doesn't seem to include `aks` after that point. However, the extension is indeed installed:
```
bash-5.0# az extension list -o table
Experimental    ExtensionType    Name         Path                                    Preview    Version
--------------  ---------------  -----------  --------------------------------------  ---------  ---------
False           whl              aks-preview  /root/.azure/cliextensions/aks-preview  True       0.5.6
```

I do see something about the cloud profile in there. Here's how I set it:
```
az cloud set --name AzureCloud --profile 2020-09-01-hybrid
az login
```

**Comment by sunkararp** [comment]
I am also experiencing this behavior
Surface Book3
azure-cli version 2.21.0

**Comment by fengzhou-msft** [comment]
Please run `az config set extension.use_dynamic_install=no` to disable the infinite extension install bug. Then rerun the aks command with `--debug` to check the real error.

**Comment by fengzhou-msft** [comment]
aks commands are only supported in `latest` profile.

This issue may be related to https://github.com/Azure/azure-cli/pull/17509, please revert to the latest profile `az cloud set --name AzureCloud --profile latest` and apply the quick patch in the PR.
