### ISSUE TITLE
az backup protection disable does not accept id of AzureIaasVM backup container

### ISSUE THREAD

**Issue by Klaas-** [Azure/azure-cli#17494]
Hi,
I used to delete backup like this:
`az backup protection disable --ids {{ backup_vault_id }} --container-name {{ virtualMachineName }} --item-name {{ virtualMachineName }} --delete-backup-data true --backup-management-type AzureIaasVM --yes`

This no longer works after one of the last upgrades. So I had a look at the error and I may have been using the id switch wrong because it expects an id that includes name of the container.

I looked at what you may be looking for now, I think you want the id listed in
`az backup container list [...] --backup-management-type AzureIaasVM --query '[].id'`
side note: you do not accept the -q shortcut that is being used in a lot of other subcommands

But using that ID does not work. It returns the error below.

Another side note: I think you should return the id you need to disabling the backup container if you run the command:
`az backup protection check-vm [...]` which currently returns the vault_id (which is why I used that id in --ids)

Greetings
Klaas

## Describe the bug

**Command Name**
`az backup protection disable`

**Errors:**
```
Argument --item-name cannot be derived from ID [...]/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;[reg];[vmname]. Please provide a complete resource ID containing all information of 'Resource Id' arguments.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az backup protection disable --ids {} --delete-backup-data true --backup-management-type AzureIaasVM --yes`

## Expected Behavior
Succeed with disabling/deletion.

## Environment Summary
```
Linux-3.10.0-1160.2.2.el7.x86_64-x86_64-with-redhat-7.9-Maipo
Python 3.6.8
Installer: RPM

azure-cli 2.21.0

Extensions:
resource-graph 1.1.0
ssh 0.1.4

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Klaas-** [comment]
This is not really a question, the bug is `The ID does not work for deleting AzureIaasVM container`. This could be a different bug  though, `az backup container list [...] --backup-management-type AzureIaasVM --query '[].id'` does not show the correct ID :)

**Comment by mepand** [comment]
@Klaas- We have recently corrected the behaviour of --ids parameters for various CLI commands. The id parameter should be the id of resource in whose context the command is executed. Disabling protection is a backup item level operation and not the container level.  Hence, please get the id of VM by executing az backup item list command and pass that id to --ids parameter of az backup protection disable command. Please let me know if this works for you

**Comment by Klaas-** [comment]
Hi,
yes that id works.
correct ID is for usage with --ids is made up like this:
[...]/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;[reg];[vmname]/protectedItems/VM;iaasvmcontainerv2;[reg];[vmname]

I still would argue you should show this as a return value for the `az backup protection check-vm [...]` command but I can work with what I know now. You should most likely improve the documentation on the --ids switch though - an example on how to use --ids or where to get the proper ID should be sufficient.

Greetings
Klaas
