### ISSUE TITLE
ACR Build doesn't honor included directories in dockeringore

### ISSUE THREAD

**Issue by joelnotified** [Azure/azure-cli#17493]
**Describe the bug**
A directory is excluded by a `.dockerignore` file, and a single directory within that directory is included. `az acr build` doesn't seem to understand this.

**To Reproduce**
Have a Dockerfile that exludes a directory called `database/`, but includes the directory within that `database/directory-to-include`

Like this:
```
# Exclude the entire directory
**/database

# Include this (override the exclusions)
!/database/directory-to-include
```

`az acr build` will throw an error because the contents of `/database/directory-to-include` won't be included in the build context.

**Expected behavior**
That it works. It works fine with `docker build` for the same Dockerfile.

**Comment by joelnotified** [comment]
Minimal repro:

Create a file under:
`/ignoredfolder/includedsubfolder/file.txt`

`Dockerfile`:
```
 FROM node:12-alpine
 WORKDIR /app
 COPY ["ignoredfolder/includedsubfolder/file.txt", "src"]
 COPY . .
 ENTRYPOINT ["sh"]
```

`.dockerignore`:
```
**/ignoredfolder
!/ignoredfolder/includedsubfolder
```

Then run:
`az acr build --image some-name  --registry myregistry.azurecr.io --file .\Dockerfile .`

**Comment by yungezz** [comment]
route to appropriate team

**Comment by arnaud-tincelin** [comment]
I am having a similar issue but without directories. It seems `az acr build` and `docker build` don't interpret the .dockerignore file the same way.

.dockerignore file:
```
# Ignore everything
**

# Allow files and directories
!/start.sh
```

run `az acr build` ends with an error:
```
Step 9/28 : COPY ./start.sh .
COPY failed: stat /var/lib/docker/tmp/docker-builder021336173/start.sh: no such file or directory
```

Whereas `docker build` runs successfully.

**Comment by yugangw-msft** [comment]
+@northtyphoon to investigate

**Comment by guilhem** [comment]
Problem is here: https://github.com/Azure/azure-cli/blob/29767d75d850ddc1c24cc85bd46d861b61d77a47/src/azure-cli/azure/cli/command_modules/acr/_archive_utils.py#L87

It only do matching to `ignore_items`.

**Comment by iamjasonp** [comment]
To @CarolineNB for investigation. Thanks!

**Comment by dracan** [comment]
This still doesn't seem to work...

Example dockerignore...

https://github.com/dracan/danclarkeblog/blob/7fa215bb19f15358492c4d725d0aa513a42b0465/.dockerignore

And failing build...

https://github.com/dracan/danclarkeblog/runs/8072733424?check_suite_focus=true

**Comment by CarolineNB** [comment]
Hi @dracan, thank you for reaching out. We are looking into it.

**Comment by CarolineNB** [comment]
Hi @dracan, try removing the trailing '/'s in your .dockerignore file and let me know if that works.

This will be fixed in the next CLI release, but I don't want you to have to wait until then.

Thanks!

**Comment by sebastus** [comment]
I cloned a repo to a windows environment - the dockerignore functionality doesn't work correctly. 

I cloned the same repo to a WSL environment - it worked fine.

https://github.com/akitana-airtanker/mcp-python-streamable-e2e-test-template.git
