### ISSUE TITLE
WebApp:staticwebapp - [P2] enable and remove managed identity

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-cli#17506]
**Describe the solution you'd like**

Enable managed identity. See [`az functionapp identity assign`](https://docs.microsoft.com/en-us/cli/azure/functionapp/identity?view=azure-cli-latest#az_functionapp_identity_assign) for optional params.

```bash
az staticwebapp identity assign -g $group -n $name
```

Remove managed identity. See [`az functionapp identity remove`](https://docs.microsoft.com/en-us/cli/azure/functionapp/identity?view=azure-cli-latest#az_functionapp_identity_remove) for optional params.

```bash
az staticwebapp identity remove -g $group -n $name
```

**Additional context**

Needed for Static Web Apps GA

**Comment by Kotasudhakarreddy** [comment]
Thanks for your feedback. We will check and consider for future milestones .
@panchagnula FYI.

**Comment by parth21999** [comment]
Managing identity via CLI would require updating azure-mgmt-web sdk. Blocked on this for now

**Comment by StrawnSC** [comment]
Closing since this feature was added to the latest release
