### ISSUE TITLE
WebApp:staticwebapp - [P2] add support for linking existing function app (bring your own functions)

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-cli#17507]
**Is your feature request related to a problem? Please describe.**

Azure Static Web Apps is adding the ability to link a Static Web App to an existing Azure Functions app. This requires gestures in Az CLI to add and remove the link.

**Describe the solution you'd like**

Link:

```bash
az staticwebapp functions link -g $StaticWebAppGroup -n $StaticWebAppName --function-resource-id $FunctionsResourceId
```

Unlink:

```bash
az staticwebapp functions unlink -g $StaticWebAppGroup -n $StaticWebAppName
```

**Additional context**

Needed for Static Web Apps GA

**Comment by Kotasudhakarreddy** [comment]
Thanks for your feedback. We will check and consider for future milestones .

@panchagnula FYI
