### ISSUE TITLE
WebApp:staticwebapp - [P1] support adding hostname via TXT record validation

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-cli#17508]
**Is your feature request related to a problem? Please describe.**

Azure Static Web Apps is adding the ability to add hostnames using TXT record validation method. This is a two-step process:

1. Initiate the process, which kicks off a background process to genreate a validation code
2. Client calls a command to poll for status. When code is generated, the status includes a code.

**Describe the solution you'd like**

This initiates the domain creation process. Valid validation methods are `cname` (default) and `txt`.

```bash
az staticwebapp hostname set -g $group -n name --hostname $hostname --validation-method txt
```

This is the command for polling for status:

```bash
az staticwebapp hostname get -g $group -n $name --hostname $hostname
```

**Additional context**

Needed for Static Web Apps GA

**Comment by Kotasudhakarreddy** [comment]
Thanks for your feedback. We will check and consider for future milestones .

**Comment by Kotasudhakarreddy** [comment]
@panchagnula FYI.

**Comment by StrawnSC** [comment]
This feature was added by https://github.com/Azure/azure-cli/pull/20074 in the latest release
