### ISSUE TITLE
az login: Invalid profile error for non-AzureStack cloud

### ISSUE THREAD

**Issue by egodigitus** [Azure/azure-cli#17513]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Invalid profile is used for cloud 'AzureCloud'. To configure the cloud profile, run `az cloud set --name AzureCloud --profile <profile>(e.g. 2019-03-01-hybrid)`. For more information about using Azure CLI with Azure Stack, see https://docs.microsoft.com/azure-stack/user/azure-stack-version-profiles-azurecli2
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal -u {} -p {} -t {}`

## Expected Behavior

login as a service-principal works

## Environment Summary
```
Linux-4.4.0-17763-Microsoft-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.21.0

```
## Additional Context

The fix from https://github.com/Azure/azure-cli/pull/15550 works:
If I set `az cloud set --name AzureCloud --profile 2020-09-01-hybrid` the login works as expected.
The response body of both (the failed and the successful one) calls contain `"managedByTenants":[],`

**I do not connect to an Azure Stack instance**

**Comment by jiasli** [comment]
This is caused by an ongoing ARM service incident. Please see #17509.

**Comment by egodigitus** [comment]
Thanks for the quick response.
A workaround without the patch #17509 is to use the hybrid profile:
`az cloud set --name AzureCloud --profile 2020-09-01-hybrid`
`az login`

**Comment by jiasli** [comment]
@egodigitus, setting `--profile 2020-09-01-hybrid` will cause other failures (like for `az aks`) because `2020-09-01-hybrid` has a reduced command set compared to `latest`.

**Comment by Forcebyte** [comment]
shouldn't there be an incident communication from Microsoft in situations like this?

Not trying to be needy or anything; but it appears to be affecting three orgs I communicate with regularly

**Comment by J0F3** [comment]
@jiasli I wondering the same as @Forcebyte. Why is there no official communication in the service health dashboard or somewhere that there is a problem with the ARM service. So that it is clear that we not to have to search on our side which the "az login" suddenly does not work anymore resp. that we, customers, can actually not do much to fix it.

**Comment by jiasli** [comment]
Thanks to everyone for the feedbacks. We have internally forwarded your feedbacks to program manager team and ARM service. 

The rollback of ARM has completed at 2021-03-31 08:00 UTC, so this issue should have been resolved.

Apologize for the inconvenience caused.
