### ISSUE TITLE
Error using az login to Azure Portal

### ISSUE THREAD

**Issue by dhmoto17** [Azure/azure-cli#17514]
## Describe the bug

Cannot login to Azure Portal with az login

**Command Name**
`az login`

**Errors:**
```
'NoneType' object is not iterable
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/profile/custom.py, ln 158, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
azure/cli/core/_profile.py, ln 240, in find_subscriptions_on_login
    is_service_principal, bool(use_cert_sn_issuer))
azure/cli/core/_profile.py, ln 276, in _normalize_properties
    subscription_dict[_MANAGED_BY_TENANTS] = [{_TENANT_ID: t.tenant_id} for t in s.managed_by_tenants]
TypeError: 'NoneType' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --query "sort_by([].{name:name, state:state, isDefault:isDefault, subscriptionId:id, tenantId:tenantId},&name)" --output table --only-show-errors`

## Expected Behavior

Login to Azure Portal and return list of subscriptions

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.14.2 *

Extensions:
azure-devops 0.18.0
resource-graph 1.1.0

```

**Comment by dhmoto17** [comment]
I'm comparing this to ticket https://github.com/Azure/azure-cli/pull/15550 but 15550 seems to be referring to a customer Azure Stack as opposed to the Azure portal.

**Comment by jiasli** [comment]
This is caused by an ongoing ARM service incident. Please see #17509.

**Comment by dhmoto17** [comment]
Ah, thank you for the update.  Happy for this bug to be closed.

I've updated to az 2.21 and get this error now, for reference if anyone else has the same issue and stumbles across my issue first..

Invalid profile is used for cloud 'AzureCloud'. To configure the cloud profile, run `az cloud set --name AzureCloud --profile <profile>(e.g. 2019-03-01-hybrid)`. For more information about using Azure CLI with Azure Stack, see https://docs.microsoft.com/azure-stack/user/azure-stack-version-profiles-azurecli2

**Comment by egodigitus** [comment]
A workaround without the patch #17509 is to use the hybrid profile:
az cloud set --name AzureCloud --profile 2020-09-01-hybrid
az login

**Comment by dhmoto17** [comment]
Thanks @jiasli and @egodigitus , I'm up and running with the fix in https://github.com/Azure/azure-cli/pull/17509

**Comment by dvdvorle** [comment]
To add further to the ugly workaround @egodigitus, I was able to set the profile to `2020-09-01-hybrid`, then `az login`, then set the profile back to `latest` to continue using `az aks` and other features
