### ISSUE TITLE
The command az webapp list-runtimes --linux fails on PopOS 20.10

### ISSUE THREAD

**Issue by a13marquez** [Azure/azure-cli#17525]
## Describe the bug

**Command Name**
`az webapp list-runtimes`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp list-runtimes --linux`

## Environment Summary
```
Linux-5.8.0-7642-generic-x86_64-with-glibc2.32
Python 3.8.6
Installer: PIP

azure-cli 2.10.1

Extensions:
azure-devops 0.18.0

```

**Comment by yungezz** [comment]
hi @a13marquez could you pls upgrade to latest CLI to resolve the issue? there's a pinned issue related to this

**Comment by a13marquez** [comment]
Hi @yungezz this solution fixes the problem, thank you, I was using the npm package
