### ISSUE TITLE
Helpful WAF policy custom rule match condition example

### ISSUE THREAD

**Issue by skotz** [Azure/azure-cli#17536]
It would be helpful to note in the `az network application-gateway waf-policy custom-rule match-condition` documentation that each match variable specified in the space-separated `--match-variables` list is further period-separated in the form `name.selector`. After a lot of searching for a way to create a specific rule using the CLI, I eventually found the solution by looking at the CLI's source [here](https://github.com/Azure/azure-cli/blob/5b95a87f0294ee95feae1a43a14aa8e0656dea3a/src/azure-cli/azure/cli/command_modules/network/_params.py#L538) and [here](https://github.com/Azure/azure-cli/blob/5b95a87f0294ee95feae1a43a14aa8e0656dea3a/src/azure-cli/azure/cli/command_modules/network/_validators.py#L507) to discover it was possible using periods.

An example with `--match-variables RequestHeaders.Content-Type --operator Equal --values application/csp-report` might help someone else down the road.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eae3c03c-db11-6d8e-a701-ef1a95e588db
* Version Independent ID: 5be6d86e-5ed1-fd02-eaaa-6e54bd2d7b44
* Content: [az network application-gateway waf-policy custom-rule match-condition](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/waf-policy/custom-rule/match-condition?view=azure-cli-latest#az_network_application_gateway_waf_policy_custom_rule_match_condition_add)
* Content Source: [latest/docs-ref-autogen/network/application-gateway/waf-policy/custom-rule/match-condition.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/application-gateway/waf-policy/custom-rule/match-condition.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@msyyc for awareness

**Comment by msyyc** [comment]
@skotz Thank you for your feedback!
