### ISSUE TITLE
az login issues

### ISSUE THREAD

**Issue by ambarishg** [Azure/azure-cli#17548]
## Describe the bug

**Command Name**
`az login`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-4.15.0-1111-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.21.0

Extensions:
ai-examples 0.2.5
ssh 0.1.4

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by ambarishg** [comment]
@yonzhan @jiasli Issue solved.

1. Created a New Resource group for this subscription. This subscription was brand new.
2. Opened Cloud Shell
3. Problem solved
4. I had also cleared cookies , deleted Temp , restarted the machine

Thank you

**Comment by yonzhan** [comment]
Please let me know if you have further questions.

**Comment by ambarishg** [comment]
Thank you. No questions.
