### ISSUE TITLE
How to use the key "sign" operation

### ISSUE THREAD

**Issue by jakraft** [Azure/azure-cli#17542]
Version 7.1 of the Azure REST API allows users to generate a signature using a key stored in key vault: 
https://docs.microsoft.com/en-us/rest/api/keyvault/keys/sign/sign?tabs=HTTP

Is there an equivalent `az keyvault key sign` command for Azure CLI?

**Comment by yungezz** [comment]
hi @houk-ms could you have a look is this a feature request or bug? thanks

**Comment by evelyn-ys** [comment]
Need `azure-keyvault-keys` Python SDK support first.

**Comment by achamayou** [comment]
@evelyn-ys support does seem to be available now: https://azuresdkdocs.blob.core.windows.net/$web/python/azure-keyvault-keys/latest/azure.keyvault.keys.crypto.html#azure.keyvault.keys.crypto.CryptographyClient.sign

**Comment by AliakseiT** [comment]
@evelyn-ys, @yonzhan, could you please look at this request? Python SDK has it already.

**Comment by evelyn-ys** [comment]
We will plan this feature in next sprint

**Comment by evelyn-ys** [comment]
Supported in https://github.com/Azure/azure-cli/pull/26922

**Comment by evelyn-ys** [comment]
This feature will be included in Azure CLI 2.51.0 (release on 2023/08/01)

**Comment by evelyn-ys** [comment]
This feature will be included in Azure CLI 2.51.0 (release on 2023/08/01)
