### ISSUE TITLE
`azcopy --cap-mbps` option unavailable from `az storage copy`

### ISSUE THREAD

**Issue by mwilensky768** [Azure/azure-cli#17544]
**Is your feature request related to a problem? Please describe.**

I cannot tell `azure storage copy` to limit the transfer rate, which is causing an overload on my compute resource's 1Gb external link, causing symptoms not unlike a DDOS attack.

**Describe the solution you'd like**

Somehow make `--cap-mbps` option available from `azure storage copy` call.

**Describe alternatives you've considered**

 I have spent a while trying to install and successfully log into `azcopy` so that I can make use of its `--cap-mbps` option, which has itself required its own troubleshooting on this system and I have so far been unsuccessful with. I've tried several of the options on this wiki: https://github.com/Azure/azure-storage-azcopy/wiki/Improved-login-support-for-AzCopy-commands-(with-in-memory-secret-store) to help with my login troubles. I was linked there by issue #193, which is closed, but mentions the same error message that I repeatedly get.

**Additional context**

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
@zhangyan133 could you evaluate if we could add this feature in azure cli?
