### ISSUE TITLE
[Feature Request] Support `--scope` in `az login`

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#17551]
**Is your feature request related to a problem? Please describe.**

The current Azure CLI unconditionally uses ARM resource ID (e.g.

https://github.com/Azure/azure-cli/blob/3feea02888ea67f033f407174a3a7a340158b81a/src/azure-cli-core/azure/cli/core/cloud.py#L306

) to call `/authorize` API of [authorization code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow).

There are increasing asks for Conditional Access support from multiple service teams (#15220):

- Storage
- App Configuration
- VM SSH

**Describe the solution you'd like**

We should reconsider supporting Conditional Access on `dev` branch. 

In order to do so, `az login` must take `--scope` and use it in `/authorize`.

ℹ ADAL only takes `resource`, so `scope` must be converted back to `resource` using 

https://github.com/Azure/azure-cli/blob/ad30d5595a4e49ff4fa5b2be887b8fac3a1bce79/src/azure-cli-core/azure/cli/core/util.py#L1214-L1228

**Comment by yonzhan** [comment]
support scope
