### ISSUE TITLE
[Function app] Use ARM API to get stacks information for functions 

### ISSUE THREAD

**Issue by stefanushinardi** [Azure/azure-cli#17558]
Hello, 

Current implementation uses static list to get stacks information(e.g.[LinuxFunctionsStacks.json](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/resources/LinuxFunctionsStacks.json)). We recently launched ARM api endpoints so that clients could get latest stacks information(i.e. https://management.azure.com/providers/Microsoft.Web/functionappstacks?api-version=2020-10-01)

The ask is to onboard to this API.

**Additional context**

cc: @gzuber  @pragnagopa  for the details

**Comment by pragnagopa** [comment]
cc @AnatoliB

**Comment by panchagnula** [comment]
@stefanushinardi & @pragnagopa is this API updated on swagger, SDK released with this API - if so then CLI can be updated accordingly. Thanks!

**Comment by pragnagopa** [comment]
Tagging @ehamai and @andimarc - to confirm if API updated on swagger and SDK released.

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
this is done. Please use the latest version of CLI.
