### ISSUE TITLE
InvalidApiVersionParameter: Azure CLI fails to create SSL certificate in App Gateway

### ISSUE THREAD

**Issue by patrickheinzelmann** [Azure/azure-cli#17559]
## Describe the bug

I tried to create a new certificate in the App Gateway using the latest Azure CLI from Home Brew.

**Command Name**
`az network application-gateway ssl-cert create`

**Errors:**
```
(InvalidApiVersionParameter) The api-version '2020-11-01' is invalid. The supported versions are '2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network application-gateway ssl-cert create --gateway-name {} --resource-group {} --subscription {} --name {} --key-vault-secret-id {} --output {} --only-show-errors`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.8
Installer: HOMEBREW

azure-cli 2.21.0

Extensions:
aks-preview 0.5.5

```

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
@patrickheinzelmann  I run the following cmd successfully. It seems that '2020-11-01' is supported. Could you run again with ' --debug' to get more info?

---------------------cmd begin---------------

az group create -n yyc -l westus
az identity create -g yyc -n access_identity （*1）

az keyvault create -g yyc -n kv-yyc --sku premium

az keyvault set-policy -g yyc -n kv-yyc  --object-id 00000000000000000000000000  --secret-permissions get list set ('--object-id' is 'principalId' of *1)

az keyvault update -n kv-yyc  --enable-soft-delete -g yyc

az keyvault certificate create  --vault-name kv-yyc --name cert  --policy "$(az keyvault certificate get-default-policy)"        (run in Linux or cloud shell bash)

az network public-ip create -g yyc -n ip --sku Standard

az network application-gateway create  -g yyc -n gw --sku Standard_v2 --public-ip-address ip  --identity access_identity

az keyvault certificate show --vault-name kv-yyc --name cert (*2)

az network application-gateway ssl-cert create -g yyc --gateway-name gw  --name MySSLCert  --key-vault-secret-id https://kv-yyc.vault.azure.net/secrets/cert/00000000000000000000000000 ('--key-vault-secret-id': get from 'sid' of *2)

---------------------cmd end---------------

**Comment by kairu-ms** [comment]
It works on the latest version of azure cli.
