### ISSUE TITLE
"az sf application list" not listing application

### ISSUE THREAD

**Issue by sandeepdk** [Azure/azure-cli#17561]
[Enter feedback here]
`az sf application list --subscription XXX --resource-group xxxx -c xxxx` returns an empty list.
Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9164372b-4c1a-ae4b-f7df-3d8934b429f0
* Version Independent ID: 03c82f3c-f2a4-1c75-3c1e-2367c8a5776d
* Content: [az sf application](https://docs.microsoft.com/en-us/cli/azure/sf/application?view=azure-cli-latest#az_sf_application_show)
* Content Source: [latest/docs-ref-autogen/sf/application.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/sf/application.yml)
* Service: **service-fabric**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to the latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and retry and also ensure you have list permission for the applications.
