### ISSUE TITLE
webapp:az webapp u not working - ConnectionResetError(10054

### ISSUE THREAD

**Issue by TiborGalambos** [Azure/azure-cli#17563]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Traceback (most recent call last):
lib\site-packages\urllib3\connectionpool.py, ln 699, in urlopen
    httplib_response = self._make_request(
lib\site-packages\urllib3\connectionpool.py, ln 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
lib\site-packages\urllib3\connection.py, ln 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
...

lib\site-packages\requests\adapters.py, ln 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.6
Installer: PIP

azure-cli 2.19.1 *

Extensions:
db-up 0.2.1

```

**Comment by Kotasudhakarreddy** [comment]
unable to repro this issue. please try with latest version `2.21.0` . If still issue comes please share `--debug` log.

**Comment by panchagnula** [comment]
@TiborGalambos I see you have the following extension installed db-up 0.2.1 - please try uninstalling this extension & re-try - & update here. Thanks!

**Comment by Kotasudhakarreddy** [comment]
closing due to lack of response. Please file a new issue if this is still a problem.

**Comment by TiborGalambos** [comment]
> @TiborGalambos I see you have the following extension installed db-up 0.2.1 - please try uninstalling this extension & re-try - & update here. Thanks!

reinstall helped, thanks
