### ISSUE TITLE
az webapp identity assign => The api-version '2018-01-01-preview' is invalid

### ISSUE THREAD

**Issue by subhendu-de** [Azure/azure-cli#17562]
## Describe the bug

**Command Name**
`az webapp identity assign`

**Errors:**
```
The api-version '2018-01-01-preview' is invalid. The supported versions are '2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
```

## To Reproduce:
```bat
set subscriptionid={subscription-id}
set webapp=mywebapp%RANDOM%
set resourcegroup={resource-group-name}

az webapp identity assign --resource-group %resourcegroup% --name %webapp% --role reader --scope /subscriptions/%subscriptionid%/%resourcegroup%
```

## Expected Behavior
The MSI should be assigned to the resource.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.21.0

Extensions:
azure-devops 0.12.0

```

**Comment by subhendu-de** [comment]
I found the issue. It was due to the incorrect --scope. It should be ```/subscriptions/{subscription-id}/resourceGroups/{resource-group-name}```

The error message is not helpful though. Keeping this open to hear back if error message can be fixed.

**Comment by Kotasudhakarreddy** [comment]
This message is being returned by the API. This cannot be handled/fixed at command level. 

@panchagnula - can you please transfer it to API team if this is an appropriate issue to be handle at API side.

**Comment by panchagnula** [comment]
> This message is being returned by the API. This cannot be handled/fixed at command level.
> 
> @panchagnula - can you please transfer it to API team if this is an appropriate issue to be handle at API side.

@Kotasudhakarreddy / @subhendu-de which API are we referring to here? The command calls identity APIs as well as AppService - if this is from identity API then this should be updated & move to the right team.

@subhendu-de as a general rule running any CLI command with --debug flag should give you detailed error message.

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
> > This message is being returned by the API. This cannot be handled/fixed at command level.
> > @panchagnula - can you please transfer it to API team if this is an appropriate issue to be handle at API side.
> 
> @Kotasudhakarreddy / @subhendu-de which API are we referring to here? The command calls identity APIs as well as AppService - if this is from identity API then this should be updated & move to the right team.
> 
> @subhendu-de as a general rule running any CLI command with --debug flag should give you detailed error message.

@panchagnula - It is referring to [Roledefinitions.List API](https://docs.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2018_01_01_preview.operations.roledefinitionsoperations?view=azure-python#list-scope--filter-none----kwargs-). Below is the debug log response.
![image](https://user-images.githubusercontent.com/60102891/113656380-66a2e600-96b9-11eb-8e6d-ae008affb95d.png)

**Comment by RakeshMohanMSFT** [comment]
This is working. Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
`az webapp identity assign -g Issue17562 -n issue17562webapp --role reader --scope /subscriptions/<subid>/resourcegroups/Issue17562`
Retrying role assignment creation: 1/36
Retrying role assignment creation: 2/36
Retrying role assignment creation: 3/36
Retrying role assignment creation: 4/36
Retrying role assignment creation: 5/36
Retrying role assignment creation: 6/36
{
  "principalId": "<Pid>",
  "tenantId": "<tid>",
  "type": "SystemAssigned",
  "userAssignedIdentities": null
}
