### ISSUE TITLE
Direct Sharing support for Azure Shared Image Gallery

### ISSUE THREAD

**Issue by axayjo** [Azure/azure-cli#17574]
**Resource Provider**
CAPS, PIR, CRP

**Description of Feature or Work Requested**
We now support direct sharing in Azure Shared Image Gallery. The feature allows you to share galleries with other subscriptions and tenants, without having to use Azure RBAC. 

Since it's a new way of sharing, we need to make changes in 'az sig', 'az vm create' and 'az vmss create' commands. These are what we had in mind, but we can discuss the design in detail:
Share 
Az sig update --permissions "private/groups/community"
Az sig share --subscription-ids "subscription-id" --tenant-ids "tenant-id" --mgmtgrp-ids "managementgroup-ids"
**changes:**
`Az sig share add --subscription-ids "subscription-id" --tenant-ids "tenant-id"` #mgmtgrp will not be supported in this version
Az sig share --reset - going from groups to private
**changes**
`Az sig share reset`

List galleries:
Az sig group-list --scope "subscription/tenant/mgmtgrp" --location
**changes**
`Az sig shared-gallery list --scope "subscription/tenant" --location `

List image definition and version:

Az sig image-definition list --scope "subscription/tenant/mgmtgrp/community" --location
**changes**
`Az sig shared-image-definition list --scope "subscription/tenant" --location `
Az sig share image-version list --scope "subscription/tenant/mgmtgrp/community" --location
**changes**
`Az sig shared-image-version list --scope "subscription/tenant" --location ` #mgmtgrp/community will not be supported in this version
Get:
Az sig share image-definition show --name "is it gallery name or gallery unique name?"
**changes**
`az sig shared-image-definition show --gallery-image-name "myGalleryImageName" --gallery-unique-name "galleryUniqueName" --location "myLocation"`
Or
`az sig shared-image-definition show –ids “resource id”`

**Minimum API Version Required**

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-12-01/gallery.json
updated:
 https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30/gallery.json and https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30/sharedGallery.json

**Target Date**
First week of May

### Updated commands according to discussion
see #17978

**Comment by qwordy** [comment]
Add it to S186.

**Comment by xfz11** [comment]
Could you provide the REST API to the command `az sig share` ? I don't see the corresponding API and arguments in the swagger file

**Comment by xfz11** [comment]
From @kang in SIG team, swagger file for direct sharing are https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30/gallery.json and https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30/sharedGallery.json
Arguments are in SharingProfile and SharingUpdate.

**Comment by xfz11** [comment]
Updating `Shared Image Gallery` commands example

**Share**
- command: gallery update
`az sig update --permissions "private/groups "`
- command: Add sharing id to the sharing profile of a gallery.
`  az sig share update --gallery-name "myGalleryName" -g "myResourceGroup" --groups type="Subscriptions" ids="34a4ab42-0d72-47d9-bd1a-aed207386dac" ids="380fd389-260b-41aa-bad9-0a83108c370b" --groups type="AADTenants" ids="c24c76aa-8897-4027-9b03-8f7928b54ff6" --operation-type "Add"`
- command: reset sharing profile of a gallery.
  `az sig share update --gallery-name "myGalleryName" -g "myResourceGroup" --operation-type "Reset"`

**List galleries:**
- command: List shared galleries by subscription id or tenant id.
`az sig group-list --scope " tenant“  --location "myLocation"      `

**List image definition and version:**
`az sig share image-definition list --gallery-unique-name "galleryUniqueName" --location  "myLocation" –scope "subscription/tenant "`
`az sig share image-version list --gallery-image-name "myGalleryImageName" --gallery-unique-name "galleryUniqueName" --location "myLocation" --scope "subscription/tenant" –scope "subscription/tenant "`


**Get**:
- command: Get a shared gallery by subscription id or tenant id
`az sig share image-definition show --gallery-image-name "myGalleryImageName" --gallery-unique-name "galleryUniqueName" --location "myLocation"`
Or
`az sig share image-definition show –ids “resource id”`

**Changes**
Word 'share' is added in the middle of commands `sig image-definition` and `sig image-definition` to avoid influencing existing commands behavior.

**Comment by xfz11** [comment]
**Question**:
Swagger defined the list API parameter `sharedTo` to be a single value enum, so` --scope` can only be set as `tenant` or None. The designed commands require the option can be set as `subscription/tenant`

**Response** from service developer @kangsun-ctrl :

> `az sig group-list --scope " subscription|tenant“  --location "myLocation"      `
For list call, in scope, we have subscription and tenant. And the subscription is the default scope, so in backend and swagger, user do not need to specify ‘sharedTo=tenant’ when they just want to list by subscriptionId. And if they want to list by tenant, then they need to specify ‘sharedTo=tenant’.
Just in CLI, we want users to specify subscription or tenant.
For get call, user do not need to specify scope and both subscriptionId and tenantid will be passed in. So we return the result as long as it is shared to user’s tenant or user’s subscription.


**Solution**:
CLI allows users to set the  `--scope` option to be `subscription/tenant`, but if user doesn't set the option or set it to be `subscription`, cli request the API with `sharedTo` parameters to be None.

**Potential Problem**
CLI commands behavior doesn't align with Swagger. So it can not be auto-generated and has to be manually maintained

**Comment by xfz11** [comment]
@kangsun-ctrl 
`az sig group-list --scope tenant` will cause a error:
```
# Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Compute/locations/eastus/sharedGalleries?api-version=2020-09-30&sharedTo=tenant'

"error": {
  "code": "InternalOperationError",
  "message": "Getting dht entry '54826b22-38d6-4fb2-bad9-b7b93a3e9c5a' from dht table 'TenantSharingDHT' failed using CrpPir Client"
}
```
This error message will be really confusing for customers, user-friendlier notes would be much better

**Comment by kangsun-ctrl** [comment]
> @kangsun-ctrl
> `az sig group-list --scope tenant` will cause a error:
> 
> ```
> # Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Compute/locations/eastus/sharedGalleries?api-version=2020-09-30&sharedTo=tenant'
> 
> "error": {
>   "code": "InternalOperationError",
>   "message": "Getting dht entry '54826b22-38d6-4fb2-bad9-b7b93a3e9c5a' from dht table 'TenantSharingDHT' failed using CrpPir Client"
> }
> ```
> 
> This error message will be really confusing for customers. To tell users the cause of error will be much user-friendlier

I already have a pull request out for this. https://msazure.visualstudio.com/One/_git/Compute-CPlat-PIR/pullrequest/4406008

**Comment by xfz11** [comment]
> @xfz11 if we restrict `az sig group-list --scope tenant` to only 'tenant', will there still be an issue? How difficult is it to manually maintain?

It seems that `mgmtgrp/community` scope will be supported in the future, then CLI developers should add them manually. But if we align with Swagger, setting --scope to be only tenant as Swagger defined, then we can use codegen tool to automatically generate code. 
For this feature, manual maintaining will not cost much efforts. But it a trend to embrace codegen since maintaining all tremendous commands manually will be not realistic with the growing number of feature requests.

**Comment by kangsun-ctrl** [comment]
> > @xfz11 if we restrict `az sig group-list --scope tenant` to only 'tenant', will there still be an issue? How difficult is it to manually maintain?
> 
> It seems that `mgmtgrp/community` scope will be supported in the future, then CLI developers should add them manually. But if we align with Swagger, setting --scope to be only tenant as Swagger defined, then we can use codegen tool to automatically generate code.
> For this feature, manual maintaining will not cost much efforts. But it a trend to embrace codegen since maintaining all tremendous commands manually will be not realistic with the growing number of feature requests.

@xfz11  Actually I think if you will do it manually, then it is better to map scope=subscription to swagger with no sharedTo option, and map scope=tenant to swagger with sharedTo=tenant. It will be more clear for customer. Codegen is cool, we will keep it in mind and try to align our future development with CLI Codegen.

**Comment by xfz11** [comment]
@kangsun-ctrl Of course we can manually add the commands if you persist, I just raise the potential problem for discussion. 
Actually the key point is that present Swagger may be not clear enough to let users know what will happen calling the API. `sharedTo` is just described as  `The query parameter to decide what shared galleries to fetch when doing listing operations.` and defined as a single value enum. Users will be not sure how to request by 'subscription' or what will happen if `sharedTo` is set to be `None`. 
I still think it is necessary to update Swagger now or later. Add `subscription` as the enum value as it is.  And you can use `default` data field to specify the default value. That would make more sense.

**Comment by xfz11** [comment]
For awareness, we change the commands
```
az sig share update --operation-type "Add" --groups type="Subscriptions" ids="34a4ab42" ids="380fd389" 
az sig share update --operation-type "Reset"
```
to
```
az sig share add  --subscription-ids "subscription-id" --tenant-ids "tenant-id" --groups type="AADTenants" ids="c24c76a"
az sig share reset
```
for better user experience, which also corresponds with initial commands design

**Comment by olayemio** [comment]
@xfz11 if customers want to specify multiple ids is this correct
`az sig share add  --subscription-ids "subscription-id1" "subscription-id2" --tenant-ids "tenant-id1" "tenant-id2" --groups type="AADTenants" ids="c24c76a"`

also can you explain what the `--groups-type="AADTenants" ids="c24c76a"` part means. Sorry if I'm asking a question you already answered before.

**Comment by xfz11** [comment]
@olayemio  Sorry for the typos, I update the command without `--groups-type="AADTenants" ids="c24c76a"`

**Comment by xfz11** [comment]
@kangsun-ctrl I'm not sure what you mean by design the command to be 'share list --scope'. It seems that the command will share a list within the scope. But in fact, you just want to list the galleries instead of sharing.
Your advice is still helpful, maybe we should reconsider the commands design to make it more consistent and approachable. But it would be risky to catch next CLI release.

**Comment by xfz11** [comment]
Since it may confuse customers that list command contains a verb 'share', I'd like to change command
`az sig share image-definition list/show`, `az sig share image-version list/show`
to
`az sig shared-image-definition list/show`, `az sig shared-image-version list/show`
Then the commands would be more approachable.
@kangsun-ctrl @olayemio  What do you think of the changes?

**Comment by kangsun-ctrl** [comment]
> Since it may confuse customers that list command contains a verb 'share', I'd like to change command
> `az sig share image-definition list/show`, `az sig share image-version list/show`
> to
> `az sig shared-image-definition list/show`, `az sig shared-image-version list/show`
> Then the commands would be more approachable.
> @kangsun-ctrl @olayemio What do you think of the changes?

This is a good point. I like this idea since our backend resource is 'Gallery'/'SharedGallery'

**Comment by olayemio** [comment]
Hi @xfz11 and @kangsun-ctrl , my proposal would be 
`az sig image-definition --scope "subscription" --region "eastus list/show"`

I don't want customers to look at the API and think shared-image-definition and image-definition are different resources.

**Comment by kangsun-ctrl** [comment]
> Hi @xfz11 and @kangsun-ctrl , my proposal would be
> `az sig image-definition --scope "subscription" --region "eastus list/show"`
> 
> I don't want customers to look at the API and think shared-image-definition and image-definition are different resources.

Hi @olayemio , if we use image-definition, then parameters are not the same actually. To use normal gallery, user needs to pass '- galleryName', and to use sharedGallery, user needs to pass '- galleryUniqueName'. GalleryUniqueName = subscriptionId + galleryName. So that would be 

az sig image-definition 
   [--gallery-unique-name string]
   [--gallery-name string]
   [--gallery-image-name]
   [--location ]

And that might get user confused. Because they do not know when to pass in galleryName and galleryUniqueName.

**Comment by olayemio** [comment]
@kangsun-ctrl 
here's my thought process:
1. The resources are actually the same. `shared-image-definition` and `image-definition` raises confusion that they are two completely separate resources
2. Whether we use `shared-image-definition` or only use `image-definition`, a customer will always have to know which one to use.

**Comment by kangsun-ctrl** [comment]
> @kangsun-ctrl
> here's my thought process:
> 
> 1. The resources are actually the same. `shared-image-definition` and `image-definition` raises confusion that they are two completely separate resources
> 2. Whether we use `shared-image-definition` or only use `image-definition`, a customer will always have to know which one to use.

Hi @olayemio , actually the resources are not the same. normall gallery comes from Caps, and sharedGallery comes from CrpPir, which means that their api models are different too. For example, normal gallery image version contains "publishingProfile - publishedData" while shared gallery image version contains "properties -publishedDate". Given user will actually have different experience using those two, spliting them might be a good idea.

Another concern from me is that galleryName looks confusing when we have another option called 'galleryUniqueName'

**Comment by olayemio** [comment]
Hi @xfz11, after internal discussions, we are making changes to the list galleries, image definitions and image versions calls

List galleries:
`az sig list-in-group  --group "subscription" --region "eastus"`

List image definition and version:
`az sig image-definition list-in-group/show-in-group --group "subscription" --region "eastus" --gallery-unique-name ...`
`az sig image-version list-in-group/show-in-group --group "subscription" --region "eastus" --gallery-unique-name ...`

we have an additional question:
- if I log into two tenants, is there a way for CLI to pass the current tenant to our API. Also if a customer wants to switch their current tenant, how would they do that?

**Comment by xfz11** [comment]
Hi @olayemio, why is the option `--location "eastus"` changed to  `--region "eastus"`
In CLI command, it is all defined as `location`.

**Comment by xfz11** [comment]
Hi @olayemio @kangsun-ctrl , we discussed the changes in CLI team, and we think the verb `list-in-group/show-in-group` doesn't conform to CLI convention. If you insist on changing the commands, we can discuss it later. But tomorrow CLI will stop merge PR for next release. Please contact @Juliehzl for following discussion about the feature.
Thanks

**Comment by olayemio** [comment]
@xfz11 sorry for the confusion, I meant "location", not "region". Can you explain why `list-in-group/show-in-group` does not conform to CLI convention.

New changes
List galleries:
`az sig list-in-group  --group "subscription" --location "eastus"`

List image definition and version:
`az sig image-definition list-in-group/show-in-group --group "subscription" --location "eastus" --gallery-unique-name ...`
`az sig image-version list-in-group/show-in-group --group "subscription" --location "eastus" --gallery-unique-name ...`

**Comment by xfz11** [comment]
Hi @olayemio, CLI Command is composed of `az [resource name] [operation] [option]`, generally the common operation is named `create/update/list/show` and we can use `option` to restrict the operation type or scope.
So the command should either be `az sig image-definition list --type gallery/sharedGallery` or  `az sig shared-image-definition list  ` 

As @kangsun-ctrl mentioned above, the former command will confuse users. Because the command `az sig image-definition list` require users to pass different options, such as `galleryUniqueName` and `galleryName`. 
So we think the latter will conform to CLI convention better.

Based on Swagger and context provided by service developer, we think shared-image-definition and image-definition are not absolutely the same resource . @kangsun-ctrl says that the image shared by direct sharing doesn't belong to the shared user. But if users use original way to share gallery/image, then image will belong to shared user.
So we use the qualifier `shared-` to separate 2 kinds of resource.

If you don't agree with current command design, we will not merge the PR to catch CLI 5/25 release. @Juliehzl will support you later.

**Comment by olayemio** [comment]
@xfz11 our preference is to stick with `list-in-group` / `show-in-group`. I see that `az vm assess-patches`, `az vm availability-set list-sizes`, `az vm boot-diagnostics get-boot-log-uris` break the CLI convention as well. For a great customer experience, we need to break the convention as well for this feature. 

and to clarify, the resources are the same. It's just the mode of sharing that is different. There is RBAC (user, group, service principal) and now direct sharing (subscription or tenant) for the same resource. 

We'll work with @Juliehzl
