### ISSUE TITLE
no versions mentioned, old deprecated version installed if omitted

### ISSUE THREAD

**Issue by Morriz** [Azure/azure-cli#17579]
No examples are given for `--version`, and when omitted an old deprecated version is installed: 0.9.6

Please upgrade the default version and mention in the docs what is the default, and what versions are available.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d11bd3f4-efbf-691d-76a4-293ab97ad845
* Version Independent ID: a553d088-d838-f90f-d601-12fa312fe0cf
* Content: [az postgres server](https://docs.microsoft.com/en-us/cli/azure/postgres/server?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/postgres/server.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/postgres/server.yml)
* Service: **postgresql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team
