### ISSUE TITLE
Trusted Launch - DiskRP CLI

### ISSUE THREAD

**Issue by khyewei** [Azure/azure-cli#17599]
**Resource Provider**
Microsoft.compute\disk

**Description of Feature or Work Requested**
Release DiskRP CLI for Trusted Launch public preview.

// more details on SecurityType

**Minimum API Version Required**
2020-12

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/12796

**Target Date**
ASAP

**Comment by yungezz** [comment]
https://github.com/Azure/azure-cli/issues/16692

**Comment by qwordy** [comment]
@khyewei I provide two solutions.
(1) `--security-type`, enum type, value is `TrustedLaunch`
(2) `--enable-trusted-launch`, bool type, value is `true` or `false`
Which one do you prefer? If there are more security types in the future, (1) is better.

**Comment by khyewei** [comment]
(1) --security-type, enum, value: TrustedLaunch 

cc: @anshulsolanki21

**Comment by qwordy** [comment]
@khyewei I got an error. Could you have a look? Thanks!

```
azure.core.pipeline.policies._universal: Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/fy/providers/Microsoft.Compute/disks/d5?api-version=2020-12-01'
azure.core.pipeline.policies._universal: Request method: 'PUT'
azure.core.pipeline.policies._universal: Request body:
azure.core.pipeline.policies._universal: {"location": "westus", "tags": {}, "sku": {"name": "Premium_LRS"}, "properties": {"creationData": {"createOption": "FromImage", "imageReference": {"id": "/Subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/Providers/Microsoft.Compute/Locations/westus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/18.04-LTS/Versions/18.04.202002180"}}, "securityProfile": {"securityType": "TrustedLaunch"}}}
azure.core.pipeline.policies._universal: Response content:
azure.core.pipeline.policies._universal: {
  "error": {
    "code": "InvalidParameter",
    "message": "The value of parameter securityType is invalid.",
    "target": "securityType"
  }
}
```

**Comment by khyewei** [comment]
+ @***@***.***>, @***@***.***>

Anshul, could you pls take a look?

Khye

**Comment by khyewei** [comment]
SecurityType can be specified only with TVM capable image (Gen2 image with TVM tags) . The image used is Gen1 and validation fails indicating SecurityType as invalid.

Retrieved VM image: {
  "properties": {
    "osDiskImage": {
      "operatingSystem": "Linux",
      "sizeInBytes": 32213303808,
      "sizeinGB": 31
    },
    "dataDiskImages": [],
    "replicaType": "Unmanaged",
    "hyperVGeneration": "V1",
    "disallowed": {
      "vmDiskType": "None"
    }
  },
  "location": "westus",
  "name": "18.04.202002180",
  "id": "/Subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/Providers/Microsoft.Compute/Locations/westus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/18.04-LTS/Versions/18.04.202002180"
}


From: Khye Wei ***@***.***>
Sent: Wednesday, April 21, 2021 1:45 AM
To: Azure/azure-cli ***@***.***>; Azure/azure-cli ***@***.***>; Anshul Solanki ***@***.***>; Abhishek Verma (AZURE) ***@***.***>
Subject: RE: [Azure/azure-cli] Trusted Launch - DiskRP CLI (#17599)

+ @***@***.***>, @***@***.***>

Anshul, could you pls take a look?

Khye

**Comment by khyewei** [comment]
Here's the list of Trusted Launch supported images:

Preview: Trusted launch for Azure VMs - Azure Virtual Machines | Microsoft Docs<https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch#public-preview-limitations>

Khye

From: Anshul Solanki ***@***.***>
Sent: Tuesday, April 20, 2021 1:48 PM
To: Khye Wei ***@***.***>; Azure/azure-cli ***@***.***>; Azure/azure-cli ***@***.***>; Abhishek Verma (AZURE) ***@***.***>
Subject: RE: [Azure/azure-cli] Trusted Launch - DiskRP CLI (#17599)

SecurityType can be specified only with TVM capable image (Gen2 image with TVM tags) . The image used is Gen1 and validation fails indicating SecurityType as invalid.

Retrieved VM image: {
  "properties": {
    "osDiskImage": {
      "operatingSystem": "Linux",
      "sizeInBytes": 32213303808,
      "sizeinGB": 31
    },
    "dataDiskImages": [],
    "replicaType": "Unmanaged",
    "hyperVGeneration": "V1",
    "disallowed": {
      "vmDiskType": "None"
    }
  },
  "location": "westus",
  "name": "18.04.202002180",
  "id": "/Subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/Providers/Microsoft.Compute/Locations/westus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/18.04-LTS/Versions/18.04.202002180"
}


From: Khye Wei ***@***.******@***.***>>
Sent: Wednesday, April 21, 2021 1:45 AM
To: Azure/azure-cli ***@***.******@***.***>>; Azure/azure-cli ***@***.******@***.***>>; Anshul Solanki ***@***.******@***.***>>; Abhishek Verma (AZURE) ***@***.******@***.***>>
Subject: RE: [Azure/azure-cli] Trusted Launch - DiskRP CLI (#17599)

+ @***@***.***>, @***@***.***>

Anshul, could you pls take a look?

Khye

**Comment by qwordy** [comment]
Thank you @khyewei. I got same error. I used Ubuntu 18.04 latest version and set Hyper V generation to V2.
```
azure.core.pipeline.policies._universal: Request body:
azure.core.pipeline.policies._universal: {"location": "westus", "tags": {}, "sku": {"name": "Premium_LRS"}, "properties": {"hyperVGeneration": "V2", "creationData": {"createOption": "FromImage", "imageReference": {"id": "/Subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/Providers/Microsoft.Compute/Locations/westus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/18.04-LTS/Versions/18.04.202104150"}}, "securityProfile": {"securityType": "TrustedLaunch"}}}
```

**Comment by khyewei** [comment]
+ @***@***.***>

**Comment by khyewei** [comment]
Hi, The new image again seems incompatible for TVM disk creation. It is Gen1 image and does not contain TVM tags.

Also I think TVM is not enabled in WestUS region, can we try creating disk in SouthCentralUS?

Retrieved VM image: {
  "properties": {
    "osDiskImage": {
      "operatingSystem": "Linux",
      "sizeInBytes": 32213303808,
      "sizeinGB": 31
    },
    "dataDiskImages": [],
    "replicaType": "Unmanaged",
    "hyperVGeneration": "V1",
    "disallowed": {
      "vmDiskType": "None"
    }
  },
  "location": "westus",
  "name": "18.04.202104150",
  "id": "/Subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/Providers/Microsoft.Compute/Locations/westus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/18.04-LTS/Versions/18.04.202104150"
}

Thanks,
Anshul

From: Khye Wei ***@***.***>
Sent: Wednesday, April 21, 2021 9:06 AM
To: Azure/azure-cli ***@***.***>; Azure/azure-cli ***@***.***>; Anshul Solanki ***@***.***>
Subject: RE: [Azure/azure-cli] Trusted Launch - DiskRP CLI (#17599)

+ @***@***.***>

**Comment by khyewei** [comment]
@***@***.***>, could you pls try:

https://management.azure.com/subscriptions/{{subscriptionId}}/providers/Microsoft.Compute/locations/westus/publishers/Canonical/artifacttypes/vmimage/offers/UbuntuServer/skus/18_04-lts-gen2/versions/18.04.202004290?api-version=2020-12-01<https://management.azure.com/subscriptions/%7b%7bsubscriptionId%7d%7d/providers/Microsoft.Compute/locations/westus/publishers/Canonical/artifacttypes/vmimage/offers/UbuntuServer/skus/18_04-lts-gen2/versions/18.04.202004290?api-version=2020-12-01>

Khye

From: Anshul Solanki ***@***.***>
Sent: Tuesday, April 20, 2021 10:42 PM
To: Khye Wei ***@***.***>; Azure/azure-cli ***@***.***>; Azure/azure-cli ***@***.***>
Subject: RE: [Azure/azure-cli] Trusted Launch - DiskRP CLI (#17599)

Hi, The new image again seems incompatible for TVM disk creation. It is Gen1 image and does not contain TVM tags.

Also I think TVM is not enabled in WestUS region, can we try creating disk in SouthCentralUS?

Retrieved VM image: {
  "properties": {
    "osDiskImage": {
      "operatingSystem": "Linux",
      "sizeInBytes": 32213303808,
      "sizeinGB": 31
    },
    "dataDiskImages": [],
    "replicaType": "Unmanaged",
    "hyperVGeneration": "V1",
    "disallowed": {
      "vmDiskType": "None"
    }
  },
  "location": "westus",
  "name": "18.04.202104150",
  "id": "/Subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/Providers/Microsoft.Compute/Locations/westus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/18.04-LTS/Versions/18.04.202104150"
}

Thanks,
Anshul

From: Khye Wei ***@***.******@***.***>>
Sent: Wednesday, April 21, 2021 9:06 AM
To: Azure/azure-cli ***@***.******@***.***>>; Azure/azure-cli ***@***.******@***.***>>; Anshul Solanki ***@***.******@***.***>>
Subject: RE: [Azure/azure-cli] Trusted Launch - DiskRP CLI (#17599)

+ @***@***.***>

**Comment by khyewei** [comment]
@***@***.***>, did it work for you?

Khye

From: Khye Wei
Sent: Tuesday, April 20, 2021 10:46 PM
To: Anshul Solanki ***@***.***>; Azure/azure-cli ***@***.***>; Azure/azure-cli ***@***.***>; Feiyue Yu ***@***.***>
Subject: RE: [Azure/azure-cli] Trusted Launch - DiskRP CLI (#17599)

@***@***.***>, could you pls try:

https://management.azure.com/subscriptions/{{subscriptionId}}/providers/Microsoft.Compute/locations/westus/publishers/Canonical/artifacttypes/vmimage/offers/UbuntuServer/skus/18_04-lts-gen2/versions/18.04.202004290?api-version=2020-12-01<https://management.azure.com/subscriptions/%7b%7bsubscriptionId%7d%7d/providers/Microsoft.Compute/locations/westus/publishers/Canonical/artifacttypes/vmimage/offers/UbuntuServer/skus/18_04-lts-gen2/versions/18.04.202004290?api-version=2020-12-01>

Khye

From: Anshul Solanki ***@***.******@***.***>>
Sent: Tuesday, April 20, 2021 10:42 PM
To: Khye Wei ***@***.******@***.***>>; Azure/azure-cli ***@***.******@***.***>>; Azure/azure-cli ***@***.******@***.***>>
Subject: RE: [Azure/azure-cli] Trusted Launch - DiskRP CLI (#17599)

Hi, The new image again seems incompatible for TVM disk creation. It is Gen1 image and does not contain TVM tags.

Also I think TVM is not enabled in WestUS region, can we try creating disk in SouthCentralUS?

Retrieved VM image: {
  "properties": {
    "osDiskImage": {
      "operatingSystem": "Linux",
      "sizeInBytes": 32213303808,
      "sizeinGB": 31
    },
    "dataDiskImages": [],
    "replicaType": "Unmanaged",
    "hyperVGeneration": "V1",
    "disallowed": {
      "vmDiskType": "None"
    }
  },
  "location": "westus",
  "name": "18.04.202104150",
  "id": "/Subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/Providers/Microsoft.Compute/Locations/westus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/18.04-LTS/Versions/18.04.202104150"
}

Thanks,
Anshul

From: Khye Wei ***@***.******@***.***>>
Sent: Wednesday, April 21, 2021 9:06 AM
To: Azure/azure-cli ***@***.******@***.***>>; Azure/azure-cli ***@***.******@***.***>>; Anshul Solanki ***@***.******@***.***>>
Subject: RE: [Azure/azure-cli] Trusted Launch - DiskRP CLI (#17599)

+ @***@***.***>

**Comment by khyewei** [comment]
@Khye ***@***.***> Yes, thank you very much!

________________________________
From: Khye Wei ***@***.***>
Sent: Thursday, April 22, 2021 12:06 PM
To: Anshul Solanki ***@***.***>; Azure/azure-cli ***@***.***>; Azure/azure-cli ***@***.***>; Feiyue Yu ***@***.***>
Subject: RE: [Azure/azure-cli] Trusted Launch - DiskRP CLI (#17599)


@***@***.***>, did it work for you?



Khye



From: Khye Wei
Sent: Tuesday, April 20, 2021 10:46 PM
To: Anshul Solanki ***@***.***>; Azure/azure-cli ***@***.***>; Azure/azure-cli ***@***.***>; Feiyue Yu ***@***.***>
Subject: RE: [Azure/azure-cli] Trusted Launch - DiskRP CLI (#17599)



@***@***.***>, could you pls try:



https://management.azure.com/subscriptions/{{subscriptionId}}/providers/Microsoft.Compute/locations/westus/publishers/Canonical/artifacttypes/vmimage/offers/UbuntuServer/skus/18_04-lts-gen2/versions/18.04.202004290?api-version=2020-12-01<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmanagement.azure.com%2Fsubscriptions%2F%257b%257bsubscriptionId%257d%257d%2Fproviders%2FMicrosoft.Compute%2Flocations%2Fwestus%2Fpublishers%2FCanonical%2Fartifacttypes%2Fvmimage%2Foffers%2FUbuntuServer%2Fskus%2F18_04-lts-gen2%2Fversions%2F18.04.202004290%3Fapi-version%3D2020-12-01&data=04%7C01%7CFeiyue.Yu%40microsoft.com%7Ca7df2fb83c6e4c7f734d08d90543fa10%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637546611796345371%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6GXjd6HOHzCOw5F2LH0ISN13zYZcBxDanaRdE50e2i8%3D&reserved=0>



Khye



From: Anshul Solanki ***@***.******@***.***>>
Sent: Tuesday, April 20, 2021 10:42 PM
To: Khye Wei ***@***.******@***.***>>; Azure/azure-cli ***@***.******@***.***>>; Azure/azure-cli ***@***.******@***.***>>
Subject: RE: [Azure/azure-cli] Trusted Launch - DiskRP CLI (#17599)



Hi, The new image again seems incompatible for TVM disk creation. It is Gen1 image and does not contain TVM tags.



Also I think TVM is not enabled in WestUS region, can we try creating disk in SouthCentralUS?



Retrieved VM image: {

  "properties": {

    "osDiskImage": {

      "operatingSystem": "Linux",

      "sizeInBytes": 32213303808,

      "sizeinGB": 31

    },

    "dataDiskImages": [],

    "replicaType": "Unmanaged",

    "hyperVGeneration": "V1",

    "disallowed": {

      "vmDiskType": "None"

    }

  },

  "location": "westus",

  "name": "18.04.202104150",

  "id": "/Subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/Providers/Microsoft.Compute/Locations/westus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/18.04-LTS/Versions/18.04.202104150"

}



Thanks,

Anshul



From: Khye Wei ***@***.******@***.***>>
Sent: Wednesday, April 21, 2021 9:06 AM
To: Azure/azure-cli ***@***.******@***.***>>; Azure/azure-cli ***@***.******@***.***>>; Anshul Solanki ***@***.******@***.***>>
Subject: RE: [Azure/azure-cli] Trusted Launch - DiskRP CLI (#17599)



+ @***@***.***>
