### ISSUE TITLE
az extension add -s is stuck at installing step

### ISSUE THREAD

**Issue by dikhakha** [Azure/azure-cli#17592]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
For our Azure pipelines and GitHub actions, 'az extension add -s' command is stuck at installing step. This started happening for Windows System using Azure CLI version 2.21. It was working fine for Azure CLI 2.20.

**To Reproduce**
Create GitHub action which installs an extension using wheel file, like 'az extension add -s .\aidls.whl'

**Expected behavior**
Extension should get installed correctly.

**Environment summary**
OS: Microsoft Windows Server 2019
az cli version used:
2021-04-06T07:32:13.2759914Z ##[debug]azure-cli                         2.21.0
2021-04-06T07:32:13.2759914Z ##[debug]azure-cli                         2.21.0
2021-04-06T07:32:13.2760402Z ##[debug]
2021-04-06T07:32:13.2760820Z ##[debug]core                              2.21.0
2021-04-06T07:32:13.2761500Z ##[debug]telemetry                          1.0.6
2021-04-06T07:32:13.2761962Z ##[debug]
2021-04-06T07:32:13.2762395Z ##[debug]Extensions:
2021-04-06T07:32:13.2762900Z ##[debug]azure-devops                      0.18.0

**Additional context**
We have added PR gates in our Azure CLI extension repo. This PR gate, builds and installs the extension, and only upon successful installation, PR is allowed to merge. Due to this issue, the install extension step is stuck forever and eventually GitHub action times out after 1.5 hrs. This is blocking our development activity.

**Comment by yungezz** [comment]
hi @fengzhou-msft could you check is this related with packaging? thanks

**Comment by fengzhou-msft** [comment]
@dikhakha can you add `--debug` to the `az extension add` command in the pipeline and check the error message?

**Comment by dikhakha** [comment]
Please find the attached logs.
[installextensionlogs.txt](https://github.com/Azure/azure-cli/files/6284555/installextensionlogs.txt)

**Comment by fengzhou-msft** [comment]
@dikhakha it looks like the extension has an invalid version:

> 2021-04-07T06:59:08.3571470Z D:\a\azure-aidls-cli-extension\azure-aidls-cli-extension\env\lib\site-packages\setuptools\dist.py:472: UserWarning: The version specified ('0.1.master.0') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
> 2021-04-07T06:59:08.3573399Z   "details." % version
> 2021-04-07T06:59:08.4900303Z Found the wheel file at: aidls-0.1.master.0-py2.py3-none-any.whl

We bumped the version for setuptools and pip recently. Please use an extension version that is compliant with [PEP 440](https://www.python.org/dev/peps/pep-0440/).

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please feel free to open new issues if the latest Azure CLI still does not work for you.
