### ISSUE TITLE
webapp:Add ability to import ssl cert from keyvault to webapp slots.

### ISSUE THREAD

**Issue by MikeBecatti** [Azure/azure-cli#17595]
**Is your feature request related to a problem? Please describe.**

The az cli will allow a user to import an ssl cert for a webapp, but not for a specific slot even though slot configurations for ssl are independent of one another.

**Describe the solution you'd like**

Add the "--slot" argument to "az webapp config ssl import" to allow configuration of the slot.  This slot argument should function just like it does for the "az webapp config set" command.  

**Describe alternatives you've considered**

I have been unable to find one other than manually importing the cert via the azure portal.

**Additional context**

We are trying to import a key vault certificate that is then read by the startup logic in our application.  If I configure the certificate manually in the portal everything works fine, but because I cannot configure slots via the import ssl cert command I cannot find a way to automate this portion of our deployment.

**Comment by yungezz** [comment]
route to appropriate team

**Comment by MikeBecatti** [comment]
My initial analysis of the import results may not be correct.  I've noticed that after importing the certificate in the web app it does not show the certificate in the slot through the azure portal.  However, after a certain amount of time (or possibly after my code is deployed) it will eventually show the certificate in the portal for the slot.  I'm not quite certain what is going on here.

**Comment by Kotasudhakarreddy** [comment]
@MikeBecatti - The certificate imported at `webapp` level would be available at `slot` level too. So `--slot` parameter is not required. 
Closing this issue as the the command is working as expected .
