### ISSUE TITLE
az functionapp plan update  --max-burst can't be set bigger than 20

### ISSUE THREAD

**Issue by nixGirl** [Azure/azure-cli#17596]
az functionapp plan update --max-burst can't be set higher than 20. 
20 is limit for Linux function app, not for Windows. As result it's not possible to set higher max-burst for Windows function app, which is allowed to be 100.

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
@v-anvari - please look in to this.

**Comment by fabiocav** [comment]
@apawast can we please make sure this issue is in the triage list so we can discuss? Thanks!

**Comment by apawast** [comment]
@gzuber could you please help investigate?

**Comment by panchagnula** [comment]
this is fixed please try with the latest cli version
