### ISSUE TITLE
add backendpool addresses do not work

### ISSUE THREAD

**Issue by mgexm** [Azure/azure-cli#17602]
[Enter feedback here]
The example provided for : 

c:\> az network application-gateway address-pool update -g MyResourceGroup --gateway-name MyAppGateway -n MyAddressPool --add backendAddresses "{ "ip_address": "{10.0.0.13}" }"

AND

C:\> az network application-gateway address-pool update -g MyResourceGroup --gateway-name MyAppGateway -n MyAddressPool --add backendAddresses "{ \"ip_address\": \"{10.0.0.13}\" }"

DO NOT WORK !!!!! You get the following error :

```
az network application-gateway address-pool update: 'utputformat' is not a valid value for '--output'.

TRY THIS:
az network application-gateway address-pool update --resource-group MyResourceGroup --gateway-name MyAppGateway --name MyAddressPool --servers 10.0.0.4 10.0.0.5 10.0.0.6
--output json
Update backend address pool.

https://docs.microsoft.com/en-US/cli/azure/network/application-gateway/address-pool#az_network_application_gateway_address_pool_update
Read more about the command in reference docs
```

Please provide a working example.

----- AND if you try to pass "--servers" a string which is a list of the address ----

and trying to pass --servers $(list) ... where list is something like this 

echo $list
172.16.192.26 1.1.1.1

fails as well.

C:\> az network application-gateway address-pool update -g MyResourceGroup --gateway-name MyAppGateway -n MyAddressPool --servers $ipl

```
The address must contain only digits, letters, hyphens and dots for separation. Moreover, it cannot have hyphens at the start, end or next to a dot.
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb7977f-f67a-b7f1-9c55-5fe3ceef1148
* Version Independent ID: 855b66dc-6a1b-a182-8670-2a8b8ca8b10a
* Content: [az network application-gateway address-pool](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/address-pool?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/network/application-gateway/address-pool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/application-gateway/address-pool.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by mgexm** [comment]
actually I realized I shouldbe passing an array ... still this is pretty bad that I can't jsut add an ip address but rather have to always collect all the known address and then set them again into the pool using --servers.

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
'az network application-gateway address-pool update -g yyc --gateway-name ag-yyc -n appGatewayBackendPool --add backendAddresses ipAddress=10.0.0.5' could work and we will update '--help' message. Thank you for your feedback.
