### ISSUE TITLE
az ml connecting to new URL

### ISSUE THREAD

**Issue by TLaborde** [Azure/azure-cli#17604]
**Describe the bug**
After updating the az ml extension to the latest version (1.25.0) running a command like `az ml datastore attach-sqldb` tries to connect to the domain `experiments.azureml.net` (to get the information in /discovery).

The domain name was not used before, and I can't find any documentation about its use and necessity

**To Reproduce**

- block access to *.experiments.azureml.net
- run  `az ml datastore attach-sqldb`
- get error: `ERROR: HTTPSConnectionPool(host='[redacted].experiments.azureml.net', port=443): Max retries exceeded with url: /discovery (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))`

**Expected behavior**
Either:
- a way to skip this discovery step
- clear documentation of the need for it

**Environment summary**
using agent built using virtual-environment (latest release) and azure ml (latest release)

**Comment by yonzhan** [comment]
route to service team

**Comment by harneetvirk** [comment]
To work with resources within a workspace, we need to switch from the general management.azure.com server to a REST API server specific to the location of the workspace which can be located from discoveryUrl key.
More details about the discoveryURL can be found here: https://docs.microsoft.com/azure/machine-learning/how-to-manage-rest

You can use service tags to define network access controls on network security groups or Azure Firewall: https://docs.microsoft.com/en-us/azure/virtual-network/service-tags-overview
These service tags can be resolved to IP addresses: https://www.microsoft.com/en-us/download/details.aspx?id=56519
