### ISSUE TITLE
https://docs.microsoft.com/en-us/cli/azure/ext/datafactory/datafactory 404

### ISSUE THREAD

**Issue by ClaytonWork** [Azure/azure-cli#17600]
All links leading to the Azure CLI documentation for the datafactory extension results in a 404.

Following this tutorial https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-azure-cli. Clicking the link for the 'az datafactory factory create' command about a 1/4 of the way down the page results in a 404 error.

**Comment by yungezz** [comment]
hi @ClaytonWork thanks for reporting the issue, we're working on finding right doc owner for this.

**Comment by daxianji007** [comment]
@ClaytonWork I have make a fix. Please check if the issue resolved.

**Comment by ClaytonWork** [comment]
@daxianji007 The issue looks to be resolved! Thank you for looking into it.
