### ISSUE TITLE
az acr task credential add crashes

### ISSUE THREAD

**Issue by guidola** [Azure/azure-cli#17618]
## Describe the bug

**Command Name**
`az acr task credential add`

**Errors:**
```
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py, ln 233, in invoke
azure\cli\core\commands\__init__.py, ln 664, in execute
azure\cli\core\commands\__init__.py, ln 727, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 720, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-rg200gj8\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 698, in _run_job
azure\cli\core\commands\__init__.py, ln 331, in __call__
pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py, ln 816, in default_command_handler
azure\cli\command_modules\acr\task.py, ln 598, in acr_task_credential_add
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr task credential add -r {} -n {} --login-server {} --use-identity [system]`

## Expected Behavior
The command would succeed without error
## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1 *

Extensions:
account 0.2.1
subscription 0.1.4

```

**Comment by yungezz** [comment]
#14287

**Comment by guidola** [comment]
As a note, this happens when the task has been created with the `--auth-mode None` flag. If the task is recreated without the flag, it no longer crashes.
