### ISSUE TITLE
assign UMI on VM 

### ISSUE THREAD

**Issue by leug85** [Azure/azure-cli#17619]
## Describe the bug

**Command Name**
`az vm identity assign`

**Errors:**
```
'NoneType' object is not callable
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/vm/custom.py, ln 648, in assign_vm_identity
    assign_identity_helper(cmd.cli_ctx, getter, setter, identity_role=identity_role_id, identity_scope=identity_scope)
cli/core/commands/arm.py, ln 1057, in assign_identity
    resource = setter(resource)
cli/command_modules/vm/custom.py, ln 642, in setter
    vm.identity.user_assigned_identities[identity] = VirtualMachineIdentityUserAssignedIdentitiesValue()
TypeError: 'NoneType' object is not callable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

-az cloud update --profile 2019-03-01-hybrid
- az login
- `az vm identity assign -g {} -n {} --identities {} --debug`

## Expected Behavior
The command will not failed.

## Environment Summary
```
macOS-10.16-x86_64-i386-64bit
Python 3.8.7
Installer: HOMEBREW

azure-cli 2.11.1

```
## Additional Context
After an upgrade of az cli, both on macOs and ubuntu, i have a new error, that i haven't before. I can't assign an UserManagedIdentity on a VM. 

I inspect the code, and i saw that the cmd.get_models" in the same method of the exception return None value.

**Comment by yungezz** [comment]
#14287

**Comment by xfz11** [comment]
You'd better upgrade the Azure CLI by `az upgrade` and rerun the commands. According to my test, this problem has been resolved   in the latest version

**Comment by leug85** [comment]
I am sorry, i put the feedback with an olded version. Here is the same with the last version :


### **This is autogenerated. Please review and update as needed.**

## Describe the bug

**Command Name**
`az vm identity assign`

**Errors:**
```
'NoneType' object is not callable
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 660, in execute
    raise ex
cli/core/commands/__init__.py, ln 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 811, in default_command_handler
    return op(**command_args)
cli/command_modules/vm/custom.py, ln 683, in assign_vm_identity
    assign_identity_helper(cmd.cli_ctx, getter, setter, identity_role=identity_role_id, identity_scope=identity_scope)
cli/core/commands/arm.py, ln 1061, in assign_identity
    resource = setter(resource)
cli/command_modules/vm/custom.py, ln 677, in setter
    vm.identity.user_assigned_identities[identity] = UserAssignedIdentitiesValue()
TypeError: 'NoneType' object is not callable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm identity assign -g {} -n {} --identities {} --debug`

## Expected Behavior

## Environment Summary
```
macOS-11.1-x86_64-i386-64bit
Python 3.8.9
Installer: HOMEBREW

azure-cli 2.21.0

```
## Additional Context

**Comment by yungezz** [comment]
#14287

**Comment by xfz11** [comment]
your errors omit several logs in the middle, could you please provide the complete error message

**Comment by xfz11** [comment]
> I am sorry, i put the feedback with an olded version. Here is the same with the last version :
> 
> ### **This is autogenerated. Please review and update as needed.**
> ## Describe the bug
> **Command Name**
> `az vm identity assign`
> 
> **Errors:**
> 
> ```
> 'NoneType' object is not callable
> Traceback (most recent call last):
> python3.8/site-packages/knack/cli.py, ln 233, in invoke
>     cmd_result = self.invocation.execute(args)
> cli/core/commands/__init__.py, ln 660, in execute
>     raise ex
> cli/core/commands/__init__.py, ln 723, in _run_jobs_serially
>     results.append(self._run_job(expanded_arg, cmd_copy))
> ...
>     return self.handler(*args, **kwargs)
> azure/cli/core/__init__.py, ln 811, in default_command_handler
>     return op(**command_args)
> cli/command_modules/vm/custom.py, ln 683, in assign_vm_identity
>     assign_identity_helper(cmd.cli_ctx, getter, setter, identity_role=identity_role_id, identity_scope=identity_scope)
> cli/core/commands/arm.py, ln 1061, in assign_identity
>     resource = setter(resource)
> cli/command_modules/vm/custom.py, ln 677, in setter
>     vm.identity.user_assigned_identities[identity] = UserAssignedIdentitiesValue()
> TypeError: 'NoneType' object is not callable
> ```
> 
> ## To Reproduce:
> Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
> 
> * _Put any pre-requisite steps here..._
> * `az vm identity assign -g {} -n {} --identities {} --debug`
> 
> ## Expected Behavior
> ## Environment Summary
> ```
> macOS-11.1-x86_64-i386-64bit
> Python 3.8.9
> Installer: HOMEBREW
> 
> azure-cli 2.21.0
> ```
> 
> ## Additional Context

your errors omit several logs in the middle, could you please provide the complete error message

**Comment by leug85** [comment]
here is the full logs. I remove sensitive data with 'XXXX' :

cli.knack.cli: Command arguments: ['vm', 'identity', 'assign', '-g', 'XXXX', '-n', 'XXXX', '--identities', 'XXXX', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x108561160>, <function OutputProducer.on_global_arguments at 0x1085f6310>, <function CLIQuery.on_global_arguments at 0x10861caf0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'vm': ['azure.cli.command_modules.vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: vm                        0.260        44       167
cli.azure.cli.core: Total (1)                 0.260        44       167
cli.azure.cli.core: Loaded 44 groups, 167 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : vm identity assign
cli.azure.cli.core: Command table: vm identity assign
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x108b88ee0>]
az_command_data_logger: command args: vm identity assign -g {} -n {} --identities {} --debug
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/XXXX/.azure/commands'.
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x108c0fd30>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x108c2f550>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x108c2f5e0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x108c2f700>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x1085f63a0>, <function CLIQuery.handle_query_parameter at 0x10861cb80>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x108c0fe50>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x108c2f670>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ComputeManagementClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
cli.azure.cli.core.util: attempting to read file /Users/XXXX/.azure/accessTokens.json as utf-8-sig
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - Authority:Performing instance discovery: ...
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - Authority:Performing static instance discovery
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - Authority:Authority validated via static instance discovery
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - TokenRequest:Getting token from cache with refresh if necessary.
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - CacheDriver:Found 6 potential entries.
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - CacheDriver:Resource specific token found.
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - CacheDriver:Returning token from cache lookup, AccessTokenId: b'UVjQiNbbHOzwM0FQA0ki8RfY/v1BbBq6NnCPdvzSNJI=', RefreshTokenId: b'PIiMcCTyMZNV89T/EHZ8zdJQUcNq3kC3VeR4b78PhTc='
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - CacheDriver:Cached token is expired at 2021-04-12 18:16:52.828840.  Refreshing
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - TokenRequest:called to refresh a token from the cache
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - TokenRequest:Getting a new token from a refresh token
urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /ee6c3728-6c25-4201-b1fb-79cbe99342ab/oauth2/token HTTP/1.1" 200 6265
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - OAuth2Client:Get Token Server returned this correlation_id: d2c66671-2e30-40b6-8e9c-a99cdf78943b
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - CacheDriver:Created new cache entry from refresh response.
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - CacheDriver:Removing entry.
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - CacheDriver:Adding entry AccessTokenId: b'WVnRubmQ7dkXSaBZpZBZ6tFflIyLeukbKPuGpI+aFkA=', RefreshTokenId: b'PxMVZq36G6hba+NCQhwFY9HadGEMITC4mINJ82m61Sk='
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - CacheDriver:Updating 5 cached refresh tokens
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - CacheDriver:Remove many: 5
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - CacheDriver:Add many: 5
adal-python: d2c66671-2e30-40b6-8e9c-a99cdf78943b - CacheDriver:Returning token refreshed after expiry.
azure.core.pipeline.policies._universal: Request URL: 'https://management.azure.com/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Compute/virtualMachines/XXXX?$expand=instanceView&api-version=2017-12-01'
azure.core.pipeline.policies._universal: Request method: 'GET'
azure.core.pipeline.policies._universal: Request headers:
azure.core.pipeline.policies._universal:     'Accept': 'application/json'
azure.core.pipeline.policies._universal:     'x-ms-client-request-id': 'd49f46d2-9c25-11eb-a4e7-acde48001122'
azure.core.pipeline.policies._universal:     'CommandName': 'vm identity assign'
azure.core.pipeline.policies._universal:     'ParameterSetName': '-g -n --identities --debug'
azure.core.pipeline.policies._universal:     'User-Agent': 'AZURECLI/2.21.0 (HOMEBREW) azsdk-python-azure-mgmt-compute/19.0.0 Python/3.8.9 (macOS-11.1-x86_64-i386-64bit)'
azure.core.pipeline.policies._universal:     'Authorization': '*****'
azure.core.pipeline.policies._universal: Request body:
azure.core.pipeline.policies._universal: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Compute/virtualMachines/XXXX?$expand=instanceView&api-version=2017-12-01 HTTP/1.1" 200 None
azure.core.pipeline.policies._universal: Response status: 200
azure.core.pipeline.policies._universal: Response headers:
azure.core.pipeline.policies._universal:     'Cache-Control': 'no-cache'
azure.core.pipeline.policies._universal:     'Pragma': 'no-cache'
azure.core.pipeline.policies._universal:     'Transfer-Encoding': 'chunked'
azure.core.pipeline.policies._universal:     'Content-Type': 'application/json; charset=utf-8'
azure.core.pipeline.policies._universal:     'Content-Encoding': 'gzip'
azure.core.pipeline.policies._universal:     'Expires': '-1'
azure.core.pipeline.policies._universal:     'Vary': 'Accept-Encoding'
azure.core.pipeline.policies._universal:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/LowCostGet3Min;3993,Microsoft.Compute/LowCostGet30Min;31978'
azure.core.pipeline.policies._universal:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
azure.core.pipeline.policies._universal:     'x-ms-request-id': '2e401f7a-7a8e-4ff7-a41c-c5ff9ac6dd59'
azure.core.pipeline.policies._universal:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
azure.core.pipeline.policies._universal:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
azure.core.pipeline.policies._universal:     'x-ms-correlation-request-id': '6e21ab48-9bbc-4ebb-a555-30524914055f'
azure.core.pipeline.policies._universal:     'x-ms-routing-request-id': 'FRANCECENTRAL:20210413T065947Z:6e21ab48-9bbc-4ebb-a555-30524914055f'
azure.core.pipeline.policies._universal:     'X-Content-Type-Options': 'nosniff'
azure.core.pipeline.policies._universal:     'Date': 'Tue, 13 Apr 2021 06:59:46 GMT'
azure.core.pipeline.policies._universal: Response content:
azure.core.pipeline.policies._universal: {
  "name": "XXXX",
  "id": "/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Compute/virtualMachines/XXXX",
  "type": "Microsoft.Compute/virtualMachines",
  "location": "westeurope",
  "tags": {
    "app_asset": "IT",
    "app_code": "XXXX",
    "app_criticity": "utile",
    "app_label": "XXXX",
    "app_owner": "XXXX",
    "app_security_level": "tobedefined",
    "auto_shutdown_schedule": "19:00 -> 8:00, Saturday, Sunday",
    "date_creation": "31/08/2020",
    "environment": "rec",
    "monitoring": "gitlabrunner_process",
    "technical_contact": "XXXX"
  },
  "properties": {
    "vmId": "d90d20a5-b4a9-4ef6-8dc1-a4f266fdf2eb",
    "hardwareProfile": {
      "vmSize": "Standard_B1ms"
    },
    "storageProfile": {
      "imageReference": {
        "publisher": "Canonical",
        "offer": "UbuntuServer",
        "sku": "16.04-LTS",
        "version": "latest"
      },
      "osDisk": {
        "osType": "Linux",
        "name": "XXXXdskos",
        "createOption": "FromImage",
        "caching": "ReadWrite",
        "writeAcceleratorEnabled": false,
        "managedDisk": {
          "storageAccountType": "Standard_LRS",
          "id": "/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Compute/disks/XXXXdskos"
        },
        "diskSizeGB": 30
      },
      "dataDisks": []
    },
    "osProfile": {
      "computerName": "XXXX",
      "adminUsername": "terraform",
      "linuxConfiguration": {
        "disablePasswordAuthentication": true,
        "ssh": {
          "publicKeys": [
            {
              "path": "/home/terraform/.ssh/authorized_keys",
              "keyData": "ssh-rsa XXXX"
            },
            {
              "path": "/home/terraform/.ssh/authorized_keys",
              "keyData": "ssh-rsa XXXX"
            }
          ]
        }
      },
      "secrets": []
    },
    "networkProfile": {"networkInterfaces":[{"id":"/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Network/networkInterfaces/XXXXnic001","properties":{"primary":false}}]},
    "provisioningState": "Succeeded",
    "instanceView": {
      "computerName": "XXXX",
      "osName": "ubuntu",
      "osVersion": "16.04",
      "vmAgent": {
        "vmAgentVersion": "2.2.53.1",
        "statuses": [
          {
            "code": "ProvisioningState/succeeded",
            "level": "Info",
            "displayStatus": "Ready",
            "message": "Guest Agent is running",
            "time": "2021-04-13T06:59:45+00:00"
          }
        ],
        "extensionHandlers": []
      },
      "disks": [
        {
          "name": "XXXXdskos",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "time": "2021-04-13T02:28:21.8409212+00:00"
            }
          ]
        }
      ],
      "statuses": [
        {
          "code": "ProvisioningState/succeeded",
          "level": "Info",
          "displayStatus": "Provisioning succeeded",
          "time": "2021-04-13T02:28:48.7785732+00:00"
        },
        {
          "code": "PowerState/running",
          "level": "Info",
          "displayStatus": "VM running"
        }
      ]
    }
  }
}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 660, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 716, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 694, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 811, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/vm/custom.py", line 683, in assign_vm_identity
    assign_identity_helper(cmd.cli_ctx, getter, setter, identity_role=identity_role_id, identity_scope=identity_scope)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/arm.py", line 1061, in assign_identity
    resource = setter(resource)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/vm/custom.py", line 677, in setter
    vm.identity.user_assigned_identities[identity] = UserAssignedIdentitiesValue()
TypeError: 'NoneType' object is not callable

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 660, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 716, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 694, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 811, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/vm/custom.py", line 683, in assign_vm_identity
    assign_identity_helper(cmd.cli_ctx, getter, setter, identity_role=identity_role_id, identity_scope=identity_scope)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/arm.py", line 1061, in assign_identity
    resource = setter(resource)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/vm/custom.py", line 677, in setter
    vm.identity.user_assigned_identities[identity] = UserAssignedIdentitiesValue()
TypeError: 'NoneType' object is not callable
cli.azure.cli.core.azclierror: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 660, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 716, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 694, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 811, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/vm/custom.py", line 683, in assign_vm_identity
    assign_identity_helper(cmd.cli_ctx, getter, setter, identity_role=identity_role_id, identity_scope=identity_scope)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/arm.py", line 1061, in assign_identity
    resource = setter(resource)
  File "/usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/vm/custom.py", line 677, in setter
    vm.identity.user_assigned_identities[identity] = UserAssignedIdentitiesValue()
TypeError: 'NoneType' object is not callable
To open an issue, please run: 'az feedback'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x108b89160>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.608 seconds (init: 0.116, invoke: 1.492)
telemetry.save: Save telemetry record of length 6387 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/local/Cellar/azure-cli/2.21.0/libexec/bin/python /usr/local/Cellar/azure-cli/2.21.0/libexec/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py /Users/XXXX/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

**Comment by xfz11** [comment]
Could you run `az cloud show --query profile` to check your profile?
Your request's api version is '2017-12-01'  and you could use `az cloud set -n <cloud name> --profile latest` to update your cloud profile first.
Then try `az vm identity assign` again

**Comment by leug85** [comment]
Great it's working on my computer (Mac OSX). I will check for my other VM (ubuntu 18) if i could fix it also with this method.

**Comment by leug85** [comment]
I have change the profil on my ubuntu VM, and it is also ok.
