### ISSUE TITLE
Redact tokens from `--debug` log

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#17625]
## Context

1. Starting from `azure-core` 1.13.0, `Authorization` header is now exposed in DEBUG log (https://github.com/Azure/azure-sdk-for-python/pull/17424).
2. Python SDK decided not to redact `x-ms-authorization-auxiliary` header (https://github.com/Azure/azure-sdk-for-python/issues/17271).

Before bumping `azure-core` to 1.13.0, Azure CLI must adapt to `azure-core`'s new behavior.

## Proposed solutions

For tokens in `Authorization` and `x-ms-authorization-auxiliary`:

1. Keep the current behavior and redact tokens.
2. Expose tokens in `--debug` mode like the new `NetworkTraceLoggingPolicy`.
   1. Unconditionally do so, but redact tokens in `--verbose`.
   2. Make a config like `az config set logging.show_tokens=True`.

**Comment by yonzhan** [comment]
Core
