### ISSUE TITLE
parameters supply for type "SecureString"

### ISSUE THREAD

**Issue by minnieshi** [Azure/azure-cli#17637]
[do we need to do anything special for parameter which types are **SecureString**?

e.g. in CLI, i successfully retrieved the value from a KV by running, and want to provided it to the json file which has parameter 'administratorLoginPassword' defined.

```
_secret=`az keyvault secret show --name "my-secret-name" --vault-name "my-KV-NAME" --query "value" | tr -d '"'`

az deployment group create \
--name ${_deployment_name} \
--resource-group "${AZ_RESOURCE_GROUP}" \
--template-file $ARM_TEMPLATE_PATH/my_template_file.json \
--parameters airflow_psql_name="psql-${_resource_suffix}" \
 airflow_psql_env=$ENV_FULL_NAME \
 administratorLogin=blahblahblah \
 administratorLoginPassword="${_secret}"
```
it does not seem to take effect for the password
]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649a07bb-0fa2-6c51-2820-88b1bafa80ba
* Version Independent ID: ace434b7-7549-8e6d-cab0-1612f422a0cf
* Content: [az deployment group](https://docs.microsoft.com/en-us/cli/azure/deployment/group?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/deployment/group.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/deployment/group.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ARM

**Comment by minnieshi** [comment]
Please close the ticket as I made a mistake during my test. The retrieved value can be used directly.
