### ISSUE TITLE
az login fails behind proxy

### ISSUE THREAD

**Issue by hgeorges** [Azure/azure-cli#17634]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Running a session on a W2k16 VM behind firewalls/on corporate LAN.
Unable to sign into azure with az login. Used all resources found on the internet (including MS install documentation). Ran out of ideas.

Proxy set at the system level, including proxy authentication cert.
Browsers are able to open internet sites, including MS.

az login is able to open a browser, the signing in takes place successfully in the browser
(You have logged into Microsoft Azure!
You can close this window, or we will redirect you to the Azure CLI documents in 10 seconds.)

Returning to the command window, Az login eventually fails:
(Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04906AF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))))

Proxy information set in the command window
proxy cert (base64 cer) copied in cacert.pem
Microsoft sites are all whitelisted at the proxy, and reachable from any browser. 

**To Reproduce**

included above.

**Expected behavior**

login successfully.
**Environment summary**

Windows 2016 command and powershell
>az --version
azure-cli                         2.21.0
core                              2.21.0
telemetry                          1.0.6
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\hgeorges\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal
Unable to check if your CLI is up-to-date. Check your internet connection.

**Additional context**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by hgeorges** [comment]
Hello, I've been able to resolve the issue, going back and forth through a few changes/iterations.

**Comment by yonzhan** [comment]
@hgeorges glad to know your issue was resolved by yourself. Could this issue be closed?

**Comment by hgeorges** [comment]
problem resolved
