### ISSUE TITLE
No module named 'azure.keyvault.v7_0'

### ISSUE THREAD

**Issue by emagers** [Azure/azure-cli#17639]
## Describe the bug

**Command Name**
`az keyvault secret set`

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault secret set --vault-name {} --name {} --file {} --encoding {}`

## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yungezz** [comment]
hi @emagers could you pls help to upgrade to latest Azure CLI? there's packaging issue in 2.0.81, detail see https://github.com/Azure/azure-cli/issues/14011

**Comment by emagers** [comment]
@yungezz Hey, I had to completely uninstall the old version and then reinstall following those steps. It did fix the problem. Thanks!

**Comment by jiasli** [comment]
Duplicate of #13101. To fix it, please see https://github.com/Azure/azure-cli/issues/19640#issuecomment-924578571.
