### ISSUE TITLE
WebApp:Cannot use az webapp up to upload my app

### ISSUE THREAD

**Issue by SudoCory** [Azure/azure-cli#17641]
## Describe the bug
Was attempting to upload the new version of the Web app I am making, due to a bug that has appeared that is only present when it is being hosted live. I have a need to continually upload a new version to set my solution.

But now it won't let me upload the app saying I am out of retries but won't tell me when I can try again.

**Command Name**
`az webapp up`

**Errors:**
```
HTTPSConnectionPool(host='fixaleak.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef619f37b8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
python3.6/site-packages/urllib3/connection.py, ln 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
...

...

python3.6/site-packages/requests/adapters.py, ln 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='fixaleak.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/deployments/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef619f37b8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --sku {} --name {}`

## Expected Behavior
To allow me to upload the web app.

## Environment Summary
```
Linux-5.11.0-7612-generic-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.21.0

```

**Comment by Kotasudhakarreddy** [comment]
@SudoCory - Could you please retry and share me the `--debug` log if you still face the issue.
