### ISSUE TITLE
Cannot list or create role assignments without a subscription

### ISSUE THREAD

**Issue by djbb7** [Azure/azure-cli#17648]
## Describe the bug

On the Azure portal it is possible to assign application roles to AD groups without using a subscription. However, when trying to perform the same action with the az cli tool a subscription is mandatory. 

**Command Name**

`az role assignment list`

**Errors:**
```
The subscription 'XXXXX XXXXX XXXXX XXXXX' could not be found.
```
(the command uses my tenant id as value for the subscription)

## To Reproduce:
- I am using Azure just for AD purposes, so there is no subscription:
`az login --allow-no-subscriptions`
- `az role assignment list --subscription ''`

## Expected Behavior

 The expected behavior is that the role assignment should be able to be listed or created without requiring a subscription.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.21.0

```
## Additional Context

Here are the steps that I am following to assign an application role to a group, which I am able to do without a subscription: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/add-application-portal-assign-users

The assignment of app roles to enterprise applications without a subscription is also possible through the microsoft graph API and the powershell modules:
https://docs.microsoft.com/en-us/graph/api/group-post-approleassignments?view=graph-rest-1.0&tabs=http
https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/assign-user-or-group-access-portal#assign-users-and-groups-to-an-app-using-powershell

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
`az role` is for [Azure role-based access control (Azure RBAC)](https://docs.microsoft.com/en-us/azure/role-based-access-control/overview) permissions. What you want is `appRoleAssignment` from Microsoft Graph API which is a totally different topic. 

For now, you may follow https://github.com/Azure/azure-cli/issues/12946 to use `az rest` to call the Microsoft Graph API.

**Comment by jiasli** [comment]
I provided extremely detailed instructions in https://github.com/Azure/azure-cli/issues/12137. Hopefully it can unblock you. 

(I am not from AAD team, so don't take my comments seriously. 🤣)
