### ISSUE TITLE
WebApp:az webapp config ssl list is not consistently listing all certificates imported on resource group

### ISSUE THREAD

**Issue by mkunze8187** [Azure/azure-cli#17659]
Did something change with the 'az webapp config ssl list' command, as it is nolonger working for me.

 On Saturday I ran a deployment process from Azure DevOps that included getting the list of all SSL certificates for a webapp and it successfully ran and returned the list of certificates.   Today, running the same script against the same appservice it returns no certificates.   I double checked the Azure portal and the certificates exist.   I ran the exact az command from the Cloud Shell in the portal and I was also not able to retrieve the list of certificates. Using Get-AzWebAppCertificate command successfully returns the list of certificates.   

To verify it wasn't an issue with just that one appservice  I then ran the 'az webapp config ssl list' against other services that we have run the same deployment process against and found that some returned all certificates, one returned a subset of the certificates and others did not return any certificates.     

Running 'az webapp config ssl show' and specifying one of the certificates that was not showing using the list command successfully returned the certificate details.

The exact syntax of the command I used was 'az webapp config ssl list --resource-group <name of my resourcegroup>.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3f984d-0d48-e075-7e2f-2da5667b15cf
* Version Independent ID: 98e06d47-0ed4-4d8e-ccf5-d3a78e510539
* Content: [az webapp config ssl](https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/ssl.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config/ssl.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
@mkunze8187 - I am unable to repro the issue. Please try with latest `CLI` version `2.22.0`. If you still face the issue check with `--debug` logs and share with us.

**Comment by Kotasudhakarreddy** [comment]
closing due to lack of response. Please file a new issue if this is still a problem.
