### ISSUE TITLE
Support for DiskRP 2020-12-01 changes

### ISSUE THREAD

**Issue by meet1993shah** [Azure/azure-cli#17656]
**Resource Provider**
Microsoft.Compute/DiskRP

**Description of Feature or Work Requested**
Feature - Support for Hibernating VMs (Persist supportsHibernation flag on managed disks)

IAAS VMs in Azure will support a new state: hibernation. From the fabric/CRP point of view, a hibernating VM is deallocated; however, before deallocation, the VM saves the memory state to the disk, thus allowing a fast restore to the initial state when the VM is restarted. To support this managed disks will persist a new boolean property called supportsHibernation which CRP can use to determine if the underlying disk has capability to support hibernation. This flag can be turned on / off by the customer.

We need the following changes:
1. Update the disk and snapshot commands to accept a new optional property called supportsHibernation which is a boolean and ensure that customers can modify it.

**Minimum API Version Required**
2020-12-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/12796

**Target Date**
asap

**Comment by qwordy** [comment]
We are planning it.

**Comment by meet1993shah** [comment]
this feature is not yet enabled for preview, so will need to remove this issue. Will create the issue again when the preview is announced.
Thanks and sorry for this.

**Comment by meet1993shah** [comment]
please disregard the above comment

**Comment by qwordy** [comment]
@meet1993shah 
It is already in 2020-12-01 disk.json.
```
        "supportsHibernation": {
          "type": "boolean",
          "description": "Indicates the OS on a disk supports hibernation."
        },
```
Is this feature available now?

**Comment by meet1993shah** [comment]
yes, it's available.
