### ISSUE TITLE
[Function App] Update in stacks API to include PowerShell on Linux support

### ISSUE THREAD

**Issue by stefanushinardi** [Azure/azure-cli#17657]
as titled.

cc: @pragnagopa , @AnatoliB , @Francisco-Gamino , @gzuber

**Comment by Francisco-Gamino** [comment]
Adding Stack API PR link: https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/pull/29.

**Comment by yonzhan** [comment]
route to service team
