### ISSUE TITLE
Parameters in documentation are not recognized

### ISSUE THREAD

**Issue by supereddie** [Azure/azure-cli#17652]
`az network vnet-gateway create` has a couple parameters in the documentation that are not recognized by the cli:
* `--aad-tenant`
* `--aad-issuer`
* `--aad-audience`
* `--vpn-auth-type`

azure-cli version 2.21.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e274d7-9619-d96b-4389-8de0883b98e6
* Version Independent ID: 0c402156-30a9-6963-c8d1-64455536c541
* Content: [az network vnet-gateway](https://docs.microsoft.com/en-us/cli/azure/network/vnet-gateway?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/vnet-gateway.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/vnet-gateway.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
@supereddie There may be some time delay for docs. Now the docs have been updated : https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/vnet-gateway.yml
