### ISSUE TITLE
az sql db update fails  {"error":{"code":"InvalidDatabaseCreateOrUpdateRequest","message":"The request body for the create or update database operation is invalid."}}

### ISSUE THREAD

**Issue by jauwecbwq** [Azure/azure-cli#17651]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Scaling DB from S2 to P1 fails.
Current size:   -g myrg -s mysrv -n mydbname --edition Standard --service-objective S2 --max-size 250GB
New size: 
az sql db update -g myrg -s mysrv -n mydbname --edition Premium --service-objective P2 --max-size 250GB

Fails if db is part of failover group and outside of failover group, same happens without --max-size.
Oddly some databases scales up/down without issues within or outside of failover groups, might be something to do with API versions ?
Works using portal or Az powershell.

**To Reproduce**

az sql db update -g myrg -s mysrv -n mydbname --edition Premium --service-objective P2 --max-size 250GB

**Expected behavior**
Expected behavior is that database scales up from S2 to P2
 
**Environment summary**
Latest az cli executed in powershell. 

**Additional context**
--debug info
msrest.http_logger: Request URL: 'https://management.azure.com/subscriptions/xxxx/xxxx/xxxx/providers/Microsoft.Sql/servers/xxxx/databases/xxxx?api-version=2020-08-01-preview'
msrest.http_logger: Request method: 'PUT'
msrest.http_logger: Request headers:
msrest.http_logger:     'Accept': 'application/json'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'accept-language': 'en-US'
msrest.http_logger:     'Content-Length': '284'
msrest.http_logger:     'User-Agent': 'python/3.6.8 (Windows-10-10.0.19041-SP0) msrest/0.6.21 msrest_azure/0.6.3 azure-mgmt-sql/0.26.0 Azure-SDK-For-Python AZURECLI/2.21.0 (MSI)'
msrest.http_logger: Request body:
msrest.http_logger: {"location": "westeurope", "sku": {"name": "P1", "tier": "Premium"}, "properties": {"collation": "SQL_Latin1_General_CP1_CI_AS", "maxSizeBytes": 268435456000, "catalogCollation": "SQL_Latin1_General_CP1_CI_AS", "zoneRedundant": false, "readScale": "Disabled", "secondaryType": "Geo"}}
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Sql/servers/xxxx/databases/xxxx?api-version=2020-08-01-preview HTTP/1.1" 400 142
msrest.http_logger: Response status: 400
msrest.http_logger: Response headers:
msrest.http_logger:     'Cache-Control': 'no-cache'
msrest.http_logger:     'Pragma': 'no-cache'
msrest.http_logger:     'Content-Length': '142'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'Expires': '-1'
msrest.http_logger:     'x-ms-request-id': 'b5b22d0b-f672-40bf-91d5-xxxx'
msrest.http_logger:     'Server': 'Microsoft-HTTPAPI/2.0'
msrest.http_logger:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger:     'x-ms-correlation-request-id': '81bcaacc-c9de-4c17-8329-xxxx'
msrest.http_logger:     'x-ms-routing-request-id': 'WESTEUROPE:20210412T102817Z:81bcaacc-c9de-4c17-8329-xxxx'
msrest.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger:     'X-Content-Type-Options': 'nosniff'
msrest.http_logger:     'Date': 'Mon, 12 Apr 2021 10:28:17 GMT'
msrest.http_logger: Response content:
msrest.http_logger: {"error":{"code":"InvalidDatabaseCreateOrUpdateRequest","message":"The request body for the create or update database operation is invalid."}}
msrest.exceptions: The request body for the create or update database operation is invalid.
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 660, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 716, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\six.py", line 703, in reraise
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 694, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 331, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 567, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 450, in cached_put
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 444, in _put_operation
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/sql/operations/_databases_operations.py", line 437, in create_or_update
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/sql/operations/_databases_operations.py", line 388, in _create_or_update_initial
msrestazure.azure_exceptions.CloudError: Azure Error: InvalidDatabaseCreateOrUpdateRequest
Message: The request body for the create or update database operation is invalid.

cli.azure.cli.core.azclierror: The request body for the create or update database operation is invalid.
cli.azure.cli.core.azclierror: The request body for the create or update database operation is invalid.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x040486A8>]
cli.__main__: Command ran in 2.555 seconds (init: 0.180, invoke: 2.376)

**Comment by yonzhan** [comment]
route to service team

**Comment by jauwecbwq** [comment]
Just a note, command was working fine for more than 6 months, at some point started to throw error.

**Comment by jauwecbwq** [comment]
An update -  **stopping geo replication** solves the issue, however I assume this is a bug as it should clearly handle or describe why it cannot change sku, similar when we try to scale primary db first it gives warning about geo replicated db size incompatibilities on secondaries.
------------
Here is latest log
az sql db update -g myrg -s mysrv -n mydbname --tier Premium --service-objective P1 --max-size 250GB --debug
cli.knack.cli: Command arguments: ['sql', 'db', 'update', '-g', 'myrg', '-s', 'mysrv', '-n', 'mydbname', '--tier', 'Premium', '--service-objective', 'P1', '--max-size', '250GB', '--debug']


msrest.http_logger: Request URL: 'https://management.azure.com/subscriptions/xxxxx/resourceGroups/xxxx/providers/Microsoft.Sql/servers/xxxx/databases/xxxx?api-version=2020-08-01-preview'
msrest.http_logger: Request method: 'PUT'
msrest.http_logger: Request headers:
msrest.http_logger:     'Accept': 'application/json'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'accept-language': 'en-US'
msrest.http_logger:     'Content-Length': '260'
msrest.http_logger:     'User-Agent': 'python/3.6.8 (Windows-10-10.0.19041-SP0) msrest/0.6.21 msrest_azure/0.6.3 azure-mgmt-sql/0.26.0 Azure-SDK-For-Python AZURECLI/2.21.0 (MSI)'
msrest.http_logger: Request body:
msrest.http_logger: {"location": "westeurope", "sku": {"name": "P1", "tier": "Premium"}, "properties": {"collation": "SQL_Latin1_General_CP1_CI_AS", "maxSizeBytes": 268435456000, "catalogCollation": "SQL_Latin1_General_CP1_CI_AS", "zoneRedundant": false, "readScale": "Disabled"}}
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Sql/servers/xxxx/databases/xxxx?api-version=2020-08-01-preview HTTP/1.1" 202 75
msrest.http_logger: Response status: 202
msrest.http_logger: Response headers:
msrest.http_logger:     'Cache-Control': 'no-cache'
msrest.http_logger:     'Pragma': 'no-cache'
msrest.http_logger:     'Content-Length': '75'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'Expires': '-1'
msrest.http_logger:     'Location': 'https://management.azure.com/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Sql/locations/westeurope/databaseOperationResults/88250bb3-c756-442a-ac97-xx?api-version=2020-08-01-preview'
msrest.http_logger:     'Retry-After': '15'
msrest.http_logger:     'Azure-AsyncOperation': 'https://management.azure.com/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Sql/locations/westeurope/databaseAzureAsyncOperation/88250bb3-c756-442a-ac97-xx?api-version=2020-08-01-preview'
msrest.http_logger:     'x-ms-request-id': '88250bb3-c756-442a-ac97-xx'
msrest.http_logger:     'Server': 'Microsoft-HTTPAPI/2.0'
msrest.http_logger:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger:     'x-ms-correlation-request-id': '1cd758dd-69d3-4b51-xx'
msrest.http_logger:     'x-ms-routing-request-id': 'WESTEUROPE:20210412T124124Z:1cd758dd-69d3-4b51-b39a-xxx'
msrest.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger:     'X-Content-Type-Options': 'nosniff'
msrest.http_logger:     'Date': 'Mon, 12 Apr 2021 12:41:23 GMT'
msrest.http_logger: Response content:
msrest.http_logger: {"operation":"UpdateLogicalDatabase","startTime":"2021-04-12T12:41:23.98Z"}
msrest.service_client: Accept header absent and forced to application/json
msrest.universal_http.requests: Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90

**Comment by RakeshMohanMSFT** [comment]
These two commands are working without any issues, please upgrade Azure CLI to 2.40.0 and retry.

```
az sql db create -g Issue17651 -s Issue17651 -n Issue17651db --edition Standard --service-objective S2 --max-size 250GB

az sql db update -g Issue17651 -s Issue17651 -n Issue17651db --edition Premium --service-objective P2 --max-size 250GB
```
