### ISSUE TITLE
WebApp:az webapp config access-restriction add -g <gr_name> -n <app_name> --rule-name test4 --action Allow --ip-address <ip_address> --priority 40 failing

### ISSUE THREAD

**Issue by itahirov** [Azure/azure-cli#17676]
**Describe the bug**
The command failed with an unexpected error. Here is the traceback:
**'ServiceTag' is not valid value for enum <enum 'IpFilterTag'>**
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/**serialization.py", line 999, in serialize_enum**

**To Reproduce**

run the command in description, added service tag to my network access config

**Expected behavior**
I have expected successful run of command

**Environment summary**
C:\Users\v-istahi>az --version
azure-cli                         2.22.0

core                              2.22.0
telemetry                          1.0.6

Extensions:
azure-iot                         0.10.8
spring-cloud                       0.2.5

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\v-istahi\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Additional context**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
@itahirov  I am unable to repro the issue. If you still face the issue please retry and share  `--debug` logs with us.

**Comment by itahirov** [comment]
[repro.txt](https://github.com/Azure/azure-cli/files/6310736/repro.txt)
@Kotasudhakarreddy  thank you for looking into the issue, i have uploaded debug file

**Comment by Kotasudhakarreddy** [comment]
@itahirov - This is because `Service Tag` support is currently not available on SDK version of Python used on CLI. [Pull Request](https://github.com/Azure/azure-cli/pull/17687) has been raised for the same. Will be fixed in the next release. See [here](https://github.com/Azure/azure-cli/issues/17135) for the same issue with other command.

**Comment by Kotasudhakarreddy** [comment]
Official release of the next CLI version containing the fix is 6. May (2.23)

**Comment by itahirov** [comment]
@Kotasudhakarreddy  thank you for update and for providing the estimates.

**Comment by Kotasudhakarreddy** [comment]
Closing as the fix is released in the latest version `2.23.0`. Please file a new issue if this is still a problem.
