### ISSUE TITLE
Support for Traffic Manager target resources for DNS zone export

### ISSUE THREAD

**Issue by simnyc** [Azure/azure-cli#17677]
**Is your feature request related to a problem? Please describe.**
The `dns zone export` command does not export "alias recordsets", which results in incomplete zone files. In this case I'm specifically interested in supporting Traffic Manager Profile targets.

**Describe the solution you'd like**

The `export` command should create one A record for each Traffic Manager Profile target that has status `Enabled`.

For example given the Profile:

```
az network traffic-manager endpoint list -g myrg --profile-name myprofile| jq '.[]|select(."endpointStatus" == "Enabled").target'
Tue Apr 13 18:40:34 MDT 2021
"1.1.1.1"
"2.2.2.2"
"3.3.3.3"
```

and given the DNS record:

```
az network dns record-set a show -g myrg -z myzone -n 'myrecord'
{
  "targetResource": {
    "id": "/subscriptions/<subscritionId>/resourceGroups/myrg/providers/Microsoft.Network/trafficManagerProfiles/myprofile",
    "resourceGroup": "myrg"
  },
}
```

The `export` command should return:

```
myrecord 300 IN A 1.1.1.1
                300 IN A 2.2.2.2
                300 IN A 3.3.3.3
```

**Describe alternatives you've considered**

**Additional context**

As far as I can tell, the code [here](https://github.com/Azure/azure-cli/blob/master/src/azure-cli/azure/cli/command_modules/network/custom.py#L2047) ignores records that do not have a `record_data` field, i.e `arecords` for A records.

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
@simnyc I could not reproduce the scene. Could you describe the question with more details? For example : 
--------- example begin----------
(1) create necessary resource with the following steps:
az group create -n yyc-westus -l westus
az network traffic-manager profile check-dns -n myfoobar1
az network traffic-manager profile create -n tm -g yyc-westus --routing-method priority --unique-dns-name dns000 
......
(2) execute the cmd 'az ...' but get unexpected result: ...
(3) my expected result : ...
---------example end----------

**Comment by yonzhan** [comment]
@simnyc any update or feedback?

**Comment by yonzhan** [comment]
@simnyc any update or feedback?

**Comment by jonbeck7** [comment]
Repro steps:
1) Create a ATM profile
2) add endpoint to the profile (Ipv4 or Ipv6)
3) create a DNS Zone
4) add recordset to zone selecting "alias" and then selecting your newly created ATM profile as your azure resource
5)export the newly created zone file

When you do this you should see the alias, but instead you don't get anything.  Here is a screenshot from the portal UI:

![image](https://user-images.githubusercontent.com/17036965/158443387-2d05b5b9-102c-408c-a95d-a4b46923e479.png)

You will see I have 2 A records, one is an alias and one is not.  Here is what the export shows:

__________________

on@DESKTOP-N3HJVU8:/mnt/c/Users/jonbeck$ az network dns zone export -g accsystem -n demofordana.contoso.comply -f aliasexporttest.txt

; Exported zone file from Azure DNS
;      Zone name: demofordana.contoso.comply
;      Resource Group Name: accsystem
;      Date and time (UTC): Tue, 15 Mar 2022 11:00:54 -0700

$TTL 300
$ORIGIN demofordana.contoso.comply.

@ 3600 IN SOA ns1-06.azure-dns.com. azuredns-hostmaster.microsoft.com. (
              1 ; serial
              3600 ; refresh
              300 ; retry
              2419200 ; expire
              300 ; minimum
              )

  172800 IN NS ns1-06.azure-dns.com.
  172800 IN NS ns2-06.azure-dns.net.
  172800 IN NS ns3-06.azure-dns.org.
  172800 IN NS ns4-06.azure-dns.info.

testingrecord 3600 IN A 8.8.4.4

__________________

Missing the testingagainexportalias record.
