### ISSUE TITLE
'az aks create' error if name contains character underscore(_)

### ISSUE THREAD

**Issue by wcc8088** [Azure/azure-cli#17681]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

$> az aks create --resource-group wooccdocker -n "aks_woocccluster" --node-count 1 
_--name cannot exceed 63 characters and can only contain letters, numbers, or dashes (-)._

**Expected behavior**

According to the document, underscore can be used for names.
Entity | Scope | Length | Valid Characters
-- | -- | -- | --
managedClusters | resource group | 1-63 | Alphanumerics, underscores, and hyphens.Start and end with alphanumeric.
openShiftManagedClusters | resource group | 1-30 | Alphanumerics.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftcontainerservice

**Environment summary**
$ az --version
azure-cli                         2.22.0

core                              2.22.0
telemetry                          1.0.6

Extensions:
subscription                       0.1.4
blueprint                          0.1.1
account                            0.2.1

**Comment by C4RTON** [comment]
We got the same problem, can you investigate on it ?

**Comment by yonzhan** [comment]
AKS service team should look into this

**Comment by vcariven** [comment]
In my case, it happens when using the `aks-preview` extension which might be the effective root cause :
```
cli.azure.cli.core.commands: The behavior of this command has been altered by the following extension: aks-preview
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 645, in execute
    self._validation(expanded_arg)
  File "/opt/az/lib/python3.6/site-packages/knack/invocation.py", line 113, in _validation
    self._validate_arg_level(parsed_ns)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 853, in _validate_arg_level
    validator(**self._build_kwargs(validator, ns))
  File "/home/vagrant/.azure/cliextensions/aks-preview/azext_aks_preview/_validators.py", line 91, in validate_linux_host_name
    raise CLIError('--name cannot exceed 63 characters and can only contain '
knack.util.CLIError: --name cannot exceed 63 characters and can only contain letters, numbers, or dashes (-).

cli.azure.cli.core.azclierror: --name cannot exceed 63 characters and can only contain letters, numbers, or dashes (-).
az_command_data_logger: --name cannot exceed 63 characters and can only contain letters, numbers, or dashes (-).
```
Where the function `validate_linux_host_name` is called to validate the AKS cluster name and does not allow the underscore `_` character.
- https://github.com/Azure/azure-cli-extensions/blob/main/src/aks-preview/azext_aks_preview/_validators.py#L79
Maybe the issue should be moved to the https://github.com/Azure/azure-cli-extensions project ?
