### ISSUE TITLE
Confusing wording

### ISSUE THREAD

**Issue by bmedlin** [Azure/azure-cli#17692]
"Manage Azure Resource Manager template deployment at resource group."

This is a poorly formed sentence. What is being implied here but not stated? "At resource group *scope*" ? *Level*?

Does 'subgroup' == 'scope'? If so - why are both terms used?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649a07bb-0fa2-6c51-2820-88b1bafa80ba
* Version Independent ID: ace434b7-7549-8e6d-cab0-1612f422a0cf
* Content: [az deployment group](https://docs.microsoft.com/en-us/cli/azure/deployment/group?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/deployment/group.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/deployment/group.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
@bmedlin In fact, they are two different concepts:
Scope means different resource levels. The common levels are: tenant, subscription, resource group and management group
Subgroup means subcommand group of a specific command group. Just like `az storage account` is the subgroup of `az storage`
