### ISSUE TITLE
[AKS] Microsoft docs should not contain employee's alias

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-cli#17699]
[Enter feedback here]
Microsoft docs should not contain employee's alias `xiazhan`
```
az aks maintenanceconfiguration add -g xiazhan-mtc-stg --cluster-name test1 -n default --weekday Monday  --start-hour 1
  The maintenance is allowed on Monday 1:00am to 2:00am
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 560b49aa-3fcc-51a1-5b72-d126712d462c
* Version Independent ID: 990a716e-67c1-585a-831c-1ef5d6a5d979
* Content: [az aks maintenanceconfiguration](https://docs.microsoft.com/en-us/cli/azure/aks/maintenanceconfiguration?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/aks/maintenanceconfiguration.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/aks/maintenanceconfiguration.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team
