### ISSUE TITLE
Add "FlowTimeout" property under Virtual Networks

### ISSUE THREAD

**Issue by Satya-anshu** [Azure/azure-cli#17702]
**Resource Provider**

Microsoft.Network

**Description of Feature or Work Requested**

Need addition of FlowTimeout property under Virtual Networks.

FlowTimeout enables connection tracking for intra-VM flows. The value should be between 4 and 30 minutes (inclusive) to enable tracking, or null to disable tracking.

It is similar to the 'idleTimeoutInMinutes' property of public IP address.

**In SDK, the property name is 'FlowTimeoutInMinutes'.**

Under Powershell, it has been implemented as FlowTimeout in the request, but in the response, we get 'FlowTimeoutInMinutes'.
https://github.com/Azure/azure-powershell/pull/14665

```
az network vnet create \
  --name myVNet \
  --resource-group CreateVNetQS-rg \
  --subnet-name default \
  --flowtimeout 10
```

**Minimum API Version Required**

2020-11-01 (In Swagger /  PS, it is 2021-02-01 API version)

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/13519

**Target Date**

_NRP 155 Manifest update release (Target May 2021)_

**Comment by yonzhan** [comment]
network

**Comment by msyyc** [comment]
waiting for 'network-february-release' merge into 'master'
