### ISSUE TITLE
change settings for multiple Azure resources roles in PIM without manual clicks in portal

### ISSUE THREAD

**Issue by butcheroo** [Azure/azure-cli#17712]
My config requires a setting like "approver" or "activation period" on a large amount of builit-in and custom roles for Azure Resources in PIM.  

1) Can I change the default settings for all roles?
2) Can I via cli or PS change some settings for a group of roles to avoid a lot of clicks in portal for multiple subscritions

**Comment by jiasli** [comment]
As explained in https://github.com/Azure/azure-cli/issues/13064, Azure CLI currently has no native support for **Privileged Identity Management**. 

You may call the [Microsoft Graph REST API for Privileged Identity Management](https://docs.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta) directly with `az rest`. For examples, you may check https://github.com/Azure/azure-cli/issues/12946.
