### ISSUE TITLE
Create resource group if not found

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#1771]
Contexts:
1. Almost every create command needs to provide a resource group and a few people have expressed the desire that CLI should create it if not existing 
2. But to create a group, we need `location` which is an optional argument

Propose:
1. We can let CLI handle it at base layer, and expose a configuration point like `auto-create-group`. A user can set it to `true`, or maybe we default to `true`
2. For the `location` parameter needed to create the group, we can handle it:
    a. If the `location` is supplied at command, use it
    b. Again, we can expose a configuration point of `default location` and CLI will use that.

/cc: @johanste, @colemickens , @squillace

**Comment by johanste** [comment]
Minor addition; the location would have to be per cloud (different clouds have different locations).

**Comment by derekbekoe** [comment]
Related to https://github.com/Azure/azure-cli/issues/623?

**Comment by tjprescott** [comment]
I would close out #623 as this has more thought put into the technical implementation.

**Comment by lostintangent** [comment]
I couldn't possibly +1 this proposal enough! I'd love to also toss out #1377 into the general conversation, since together, I think they would help simplify the CLI experience quite a bit.

**Comment by yugangw-msft** [comment]
@johanste, please triage

**Comment by johanste** [comment]
@lostintangent, given that resource group create is now goal seeking (i.e. doing a create for an existing resource group will not fail unless you are trying to change its location), do you still feel the need for this check? 

The downside is that we have to make extra calls for each create command (to check for existence), which will slow down the command execution.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
