### ISSUE TITLE
Create Apple - AD Identity Providers via the command line (AZ CLI / GraphAPI)

### ISSUE THREAD

**Issue by fabienso** [Azure/azure-cli#17728]
Good day everyone,

can i create "Identity Providers" for an Azure Active Direcotry (especially Azure AD B2C) via the "az cli" --> etc. "az rest", "az app" fully automated via "Python" ? --> **For the Apple Identity Provider**

I want to roll out B2C tenant structures fully automated for multi-tenant applications:

This requires the following steps:
- First I create a B2C tenant fully automated.
- Automatically log in to the new B2C tenant via VS code.
- Create all necessary application registrations via "az rest" through my personal JWT token (login on new tenant). These apps have different GRAPH-API scopes with which I create e. g. user flows. 
- In the new Application Registration I create the Secrets via "az rest"
- With the App-Secret and the App-Id from the automatic creation, I request an authentication token for the Graph-API Scopes in order to create the user flows in the next step.
- Once I have the token for the scopes, I pass the body of a user flow via "az rest" to create it

**Challange** 
- Now I have the following challenge: I would like to automatically store the identity providers for a tenant (Apple, Google, email, etc.). Which "az rest", "az cli" command is suitable for this? Is there any Mircosoft documentation for the creation of **apple** identity provider in the context of Azure AD for the **Apple Provider?**
a.) Create new identity provider (Apple)
b.) Store Secrets (certificates) Ids for the Identity-Provider etc. to be considered.
c.) Consider the new Identity-Provider for the User-Flows

https://docs.microsoft.com/de-de/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0

`--> But not for Apple. `

--> **Info**: The Apple-Identity-Provider is already in **_Preview_** for AD B2C
https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-apple-id?pivots=b2c-user-flow

Thank you for your help!

Best regards
Fabien

**Comment by fabienso** [comment]
@jiasli do u have any ideas?

**Comment by jiasli** [comment]
1. There is no `az app` command module.
2. If you mean `az ad app`, it is only used for creating [AAD application](https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals) (with limited functionality).
3. [Create identityProvider](https://docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0) is from Microsoft Graph API, so yes, `az rest` is the only way to call it with Azure CLI. You may find some useful examples from https://github.com/Azure/azure-cli/issues/12946.
4. As for questions regarding detailed business logic, you may [create a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) to AAD team and our support engineers will help you with them.

Thanks for your understanding.

**Comment by fabienso** [comment]
Thank @jiasli! This works wonderfully with the Google IDP. Apple doesn't seem to be considered for automation yet. 

However, when automating the IDP for Microsoft, there was an "Internal Server Error". I have opened the following thread about this.  #17741

**Comment by jiasli** [comment]
@fabienso, I am glad to know `az rest` works for you for Google IDP. As this issue falls out of the scope of Azure CLI, I will close it. 

Please feel free to raise a new issue if you have any concern with Azure CLI itself.
