### ISSUE TITLE
Add az functionapp function list command

### ISSUE THREAD

**Issue by sschlesier** [Azure/azure-cli#17720]
**Is your feature request related to a problem? Please describe.**
I would like to be able to enumerate all the functions deployed in a function app.

My immediate needs are to inventory all our HTTP triggered functions, but it seems generally useful to be able to list all the functions in a functionapp.

**Describe the solution you'd like**
Implement a `functionapp function list` command which enumerates all the functions with a specified functionapp.

**Describe alternatives you've considered**
AFAIK azure-cli has no alternative, I beleive I can find this info via the Resource Manager API but haven't actually done so yet.

**Additional context**
I'd like to be able to collect info on the functions deployed within my subscriptions without needing to know all the function names ahead of time.

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
@fabiocav is this something we still want to consider for azure-cli or funccli still supposed to be alternate?

**Comment by kamperiadis** [comment]
Marking as resolved since this is already supported
