### ISSUE TITLE
az postgres flexible-server create InternalServerError

### ISSUE THREAD

**Issue by groogiam** [Azure/azure-cli#17721]
## Describe the bug

**Command Name**
`az postgres flexible-server create`

**Errors:**
```
(InternalServerError) An unexpected error occured while processing the request. Tracking ID: '1ee513e2-8ba7-40d3-909c-409e7deb4551'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres flexible-server create --resource-group {} --name {} --location {} --admin-user {} --admin-password {} --sku-name {} --tier {} --public-access {} --storage-size {} --backup-retention {} --version {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.22.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by DaeunYim** [comment]
Hi, thanks for submitting the issue. Have you had the same problem after reporting this? If that's the case, could you provide the parameter value you used ?

**Comment by groogiam** [comment]
I was able to eventually get the resource created but my recollection was that I did get the error a couple more times in the process. There might have been a previous postgres server with the same name I deleted a few minutes prior to running to the command. Parameters I used are below. 

--sku-name Standard_B1ms --tier Burstable --public-access none --storage-size 32 --backup-retention 35 --version 12

**Comment by DaeunYim** [comment]
@groogiam 
Thanks a lot for providing the information and I'm glad that at least it worked eventually. The error might have been transient issue in the region but I'm sorry you had to try creating it multiple times. Let me investigate the issue and work on improving the experience. 

Thanks.

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to latest version of az cli 2.40.0. Also if you face this issue again, reopen the issue
