### ISSUE TITLE
az bicep throws python error on execution

### ISSUE THREAD

**Issue by akvernberg** [Azure/azure-cli#17739]
## Describe the bug

**Command Name**
`az bicep build`

**Errors:**
```
type object 'datetime.datetime' has no attribute 'fromisoformat'
Traceback (most recent call last):
cli\Lib\site-packages\knack\cli.py, ln 231, in invoke
azure\cli\core\commands\__init__.py, ln 657, in execute
azure\cli\core\commands\__init__.py, ln 720, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 691, in _run_job
azure\cli\core\commands\__init__.py, ln 328, in __call__
site-packages\azure\cli\core\__init__.py, ln 807, in default_command_handler
azure\cli\command_modules\resource\custom.py, ln 3294, in build_bicep_file
azure\cli\command_modules\resource\_bicep.py, ln 63, in run_bicep_command
azure\cli\command_modules\resource\_bicep.py, ln 152, in _load_bicep_version_check_result_from_cache
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bicep build -f {}`

## Expected Behavior
bicep file is compiled to ARM-template.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.22.0

```

**Comment by akvernberg** [comment]
The environment summary states that I have Python 3.6.8 installed on my system, but I can't find any trace of it.
The only version I have installed is 3.9.2.
```
python --version
Python 3.9.2
```

**Comment by yonzhan** [comment]
route to service team

**Comment by smokedlinq** [comment]
I just installed 2.22.1 and this fixes this issue, at least for me. 👍

**Comment by akvernberg** [comment]
> 
> 
> I just installed 2.22.1 and this fixes this issue, at least for me. 👍

That seems to have solved the issue for me as well.
Thank you, @smokedlinq!
