### ISSUE TITLE
Application Insights page doesn't have content or a redirect to the right content

### ISSUE THREAD

**Issue by samsmithnz** [Azure/azure-cli#17736]
This page appears to be a stub. 

I believe it should either contain the Application Insights information, or redirect to the Azure Monitor app insights page that does (https://docs.microsoft.com/en-us/cli/azure/monitor/app-insights?view=azure-cli-latest).

Or possibly be deleted. What is the purpose of this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03a894ba-1cb1-8c67-d3bf-903f002b4bc5
* Version Independent ID: 7f086018-c68e-3d26-2227-d8591f41631f
* Content: [Azure Application Insights](https://docs.microsoft.com/en-us/cli/azure/service-page/azure%20application%20insights?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/service-page/Azure Application Insights.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/service-page/Azure Application Insights.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
It has content now.
