### ISSUE TITLE
InternalError when creating AD DS using CLI

### ISSUE THREAD

**Issue by jonasthehobbit** [Azure/azure-cli#17734]
Seems to be an issue whenever this is run from command prompt, creating the service through gui works with same account but creating on CLI i get an error suggesting i do not have sufficient rights to create this service.

(InternalError) The service principal with appId 'REDACTED' could not be found in the Azure Active Directory tenant. Please retry the operation.

```shell
az ad ds create --domain "redacted" \
                --replica-sets location="northeurope" subnet-id="redacted" \
                --name "test" \
                --resource-group "hp_test" \
                --sku "Standard" \
                --notify-dc-admins "Enabled" --notify-global-admins "Enabled"
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19e61616-7711-b57c-29b2-4b1df5b9e09a
* Version Independent ID: 0dd3cc06-fa31-f137-f6b3-35cb8f45a400
* Content: [az ad ds](https://docs.microsoft.com/en-us/cli/azure/ad/ds?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ad/ds.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ad/ds.yml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by evelyn-ys** [comment]
@jonasthehobbit   Thanks for reaching out. Could you provide more info by add `--debug`?
