### ISSUE TITLE
az deployment sub create ends with error Table output unavailable.

### ISSUE THREAD

**Issue by roviracarlos** [Azure/azure-cli#17744]
Hi,
When I run the deployment of resource groups at the subscription level have this error, but the deployment apply correctly.

az deployment sub create --name "$deploymentName" --location "$resourceGroupLocation" --template-file "$templateFilePath" --parameters "@${parametersFilePath}"

Error
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.

The same behaviour is run interactive or with the values instead of variables.
The same behaviour is run in cloud shell or wsl, with the latest cli version. 

WSL2
$lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

$az --version
azure-cli                         2.22.0
core                              2.22.0
telemetry                          1.0.6

Python location '/usr/local/bin/python3.9'
Extensions directory '/home/user/.azure/cliextensions'

Python (Linux) 3.9.4 (default, Apr 16 2021, 14:48:13) 
[GCC 9.3.0]

CloudSHell Bash created from scratch.
$lsb_release -a
Distributor ID: Cbld
Description:    Common Base Linux Delridge (quinault)
Release:        10
Codename:       quinault

$ az --version
azure-cli                         2.22.0
core                              2.22.0
telemetry                          1.0.6

Extensions:
ai-examples                        0.2.5
ssh                                0.1.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/user/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.6/site-packages/azure-cli-extensions'

Python (Linux) 3.6.10 (default, Apr  9 2021, 09:40:07)
[GCC 8.3.0]

With debugger enabled:

cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7f825a6649d8>, <function _x509_from_base64_to_hex_transform at 0x7f825a664a60>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
cli.knack.output: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 72, in format_table
    result = obj.table_transformer(result)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/commands.py", line 50, in transform_deployment
    ('ResourceGroup', r['resourceGroup']),
KeyError: 'resourceGroup'

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 72, in format_table
    result = obj.table_transformer(result)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/commands.py", line 50, in transform_deployment
    ('ResourceGroup', r['resourceGroup']),
KeyError: 'resourceGroup'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 237, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 146, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 81, in format_table
    "Use --debug for more info.") from ex
knack.util.CLIError: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.

cli.azure.cli.core.azclierror: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
az_command_data_logger: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f825a68ac80>]

Thanks in advance!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c21eb60-cfe9-0ef7-8d93-71a8af273a04
* Version Independent ID: a97f1562-8602-f55e-df4e-7523f437edcf
* Content: [az deployment sub](https://docs.microsoft.com/en-us/cli/azure/deployment/sub?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/deployment/sub.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/deployment/sub.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ARM

**Comment by juarezr** [comment]
I have hit the same issue after upgrading to azure-cli v2.30.

Diagnostics:

``` sh
$$ uname -a
Darwin MACBOOK_PRO 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
$$ az account list -o table --debug
cli.knack.cli: Command arguments: ['account', 'list', '-o', 'table', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x107cdb910>, <function OutputProducer.on_global_arguments at 0x107d16170>, <function CLIQuery.on_global_arguments at 0x107d33760>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'account': ['azure.cli.command_modules.profile', 'azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: profile                   0.023         2         9
cli.azure.cli.core: resource                  0.031        40       187
cli.azure.cli.core: Total (2)                 0.054        42       196
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 41 groups, 196 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : account list
cli.azure.cli.core: Command table: account list
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x108283010>]
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x108396200>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x1083e3d00>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x1083e3d90>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x1083e3eb0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x107d16200>, <function CLIQuery.handle_query_parameter at 0x107d337f0>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x1083e3c70>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x1083e3e20>]
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x1083c2d40>, <function _x509_from_base64_to_hex_transform at 0x1083c2dd0>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
cli.knack.output: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 76, in format_table
    return to.dump(result_list)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 207, in dump
    from tabulate import tabulate
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 76, in format_table
    return to.dump(result_list)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 207, in dump
    from tabulate import tabulate
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 237, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 146, in out
    output = formatter(obj)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/output.py", line 79, in format_table
    raise CLIError("Table output unavailable. "
knack.util.CLIError: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.

cli.azure.cli.core.azclierror: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
az_command_data_logger: Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x108283250>]
cli.__main__: Command ran in 0.543 seconds (init: 0.182, invoke: 0.361)
telemetry.save: Save telemetry record of length 3182 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/bin/python /usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py /Users/juarez.rudsatz.br/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.
$$ az --version
azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Extensions:
datafactory                        0.5.0
databricks                         0.7.3
resource-graph                     2.1.0
storage-preview                    0.7.4

Python location '/usr/local/Cellar/azure-cli/2.30.0_1/libexec/bin/python'
Extensions directory '/Users/juarez.rudsatz.br/.azure/cliextensions'
Python (Darwin) 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
$$ brew list az
/usr/local/Cellar/azure-cli/2.30.0_1/bin/az
/usr/local/Cellar/azure-cli/2.30.0_1/etc/bash_completion.d/az
/usr/local/Cellar/azure-cli/2.30.0_1/libexec/bin/ (32 files)
/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/ (21261 files)
/usr/local/Cellar/azure-cli/2.30.0_1/libexec/pyvenv.cfg
```

**Comment by juarezr** [comment]
Some workarounds whenever acceptable:

## Set default output to `tsv`

In your `$HOME/.azure/config` file:

``` ini
[core]
# output = table
output = tsv
```

Or issue command:

```  sh
$$ az config set core.output=tsv
...
```

## Use command line switch -o tsv

```  sh
$$ az account list -o tsv
...
```

**Comment by jiasli** [comment]
@juarezr, you problem is not the same as the original one. You issue is now tracked by #20348.

The original issue is related to `transform_deployment`. @zhoxing-ms, please help take a look.

**Comment by zhoxing-ms** [comment]
Here is a PR to solve the original `transform_deployment` issue: #20455
