### ISSUE TITLE
Copy files between containers of different storage accounts?

### ISSUE THREAD

**Issue by sriharshakappala** [Azure/azure-cli#1774]
I have half a million files to copy from one storage account to another. None of your libraries are working and if they work they aren't reliable.

I tried..

**Azure Storage Explorer:** Whenever I start copy operation it copies some 10000 to 15000 files and closes the application saying "A problem caused Storage Explorer to stop working correctly. Storage Explorer can check for a solution and try to restart the program."

**azure-cli:** I don't see an option to copy from one storage account to another. All I see is copy between containers of same storage account.

**AzCopy:** I have read in the documentation that there is an option for copying between different storage accounts but it's only available for windows and I am not using one.

Point me in right direction if I am missing something or suggest me a sure shot option!

**Comment by tjprescott** [comment]
cc/ @troydai

@sriharshakappala we have replicated much of the AzCopy functionality in our Azure CLI 2.0 Preview (this repo). The command you would want to use is:

`az storage file copy start-batch --source-account {source} --source-share {scont} --destination-share {dest} --account-name {dest account}`

You may need additional parameters (i.e. credentials). If this doesn't work for you, that is valuable feedback!

**Comment by troydai** [comment]
@sriharshakappala could you give `az storage file start-batch` a try? Should you hit any issue, please leave comments to this issue?

I'll assign this issue to me for now and I'll close it in about a week. Thanks.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.

**Comment by schokkarapu-rms** [comment]
I'd like copy files from one share to another share but in different storage accounts. I used this 
`az storage file copy start-batch` displays file with `--dryrun` but when i remove `--dryrun`, it gives me the following error:
```Failed to copy file 0x0409.ini from share dlmrisklink18/DLM_Data_06142018 to file share dlmrisklink18. Please check if you have right permission to read source or set a correct sas token.```
