### ISSUE TITLE
Error:  az login -i

### ISSUE THREAD

**Issue by Andrey-Kozhanov** [Azure/azure-cli#17756]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:



Traceback (most recent call last):
  File "/opt/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
HTTPError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login -i`

## Environment Summary
```
Linux-4.12.14-95.65-default-x86_64-with-SuSE-12-x86_64
Python 2.7.17
Shell: csh

azure-cli 2.0.81

```

**Comment by Andrey-Kozhanov** [comment]
Hello Colleagues,
we are suffering from this "az login -i" error in our productive environment.
Please, could you help here.
Thank you and best regards,
Andrey Kozhanov

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by Andrey-Kozhanov** [comment]
Hello Colleagues,
in this particular case the managed identity for this VM was disabled.

But, I think in such a case something meaningful should be the output, not just a trace...
Thank  you,
Andrey Kozhanov

**Comment by jiasli** [comment]
The error means the Managed Identity endpoint is not set up correctly. We have improved the error message in https://github.com/Azure/azure-cli/pull/15574. 

You are running a very old Azure CLI 2.0.81. Please follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=zypper to install the latest version.
