### ISSUE TITLE
Redis missing from available commands

### ISSUE THREAD

**Issue by bigjimnolan** [Azure/azure-cli#17765]
## Describe the bug

**Command Name**
`Unknown`

**Errors:**
```
'redis' is misspelled or not recognized by the system.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az redis`

## Expected Behavior
I get access to redis commands
## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.22.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed. Please upgrade to latest version of azure cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
