### ISSUE TITLE
The list of IP addresses is inconsistent between the calls

### ISSUE THREAD

**Issue by 180254** [Azure/azure-cli#17760]
**Describe the bug**
The list of IP addresses is inconsistent between the calls

We are doing Azure Kubernetes Service deployment, with 5 outbound IP addresses configured. After the deployment is completed, we are trying to obtain a list of outbound IP addresses in subscription and in AKS resource groups. The list of returned IPs sometimes is inconsistent and occasionally does not include all IP addresses.

In the case described below, we deployed two AKS clusters. The first one was in East US, the second one in West US2, each in a different resource group. We waited until cluster were created successfully. After that, we used AZ CLI to get a list of outbound IP addresses in the whole subscription, and the result was proper. Later, we used AZ CLI to get a list of outbound IP addresses in concrete resource groups, and the result was empty (but should return values - multiple IP addresses). The same call, for the list of IP addresses in the resource group, after some time, returned proper values.

Timeline:
2021-04-19T11:46:44+00:00 - Deployment on EastUS finished.
2021-04-19T11:47:03+00:00 - Deployment on WestUS2 finished.

2021-04-19T11:47:03+00:00 - Getting IPs, in the whole subscription, with tag type=aks-slb-managed-outbound-ip returned correct list of IP adresses. 'x-ms-request-id' was 'e18857b4-4eab-49e1-bb89-b8db5fe1e774'. Used command: az network public-ip list --subscription "REDACTED" --query "[?tags.type=='aks-slb-managed-outbound-ip'].ipAddress"  --verbose

2021-04-19T11:48:54+00:00 - Getting IPs, in the whole subscription, with tag type=aks-slb-managed-outbound-ip returned correct list of IP adresses. 'x-ms-request-id' was 'fee85513-d78f-4015-8f42-28fa21422958'. Used command: az network public-ip list --subscription "REDACTED" --query "[?tags.type=='aks-slb-managed-outbound-ip'].ipAddress"  --verbose

2021-04-19T11:50:42+00:00 -  Getting IPs, in the whole subscription, with tag type=aks-slb-managed-outbound-ip returned correct list of IP adresses. 'x-ms-request-id' was '783c31cd-18e3-478d-ba8d-7c479701cd06'. Used command: az network public-ip list --subscription "REDACTED" --query "[?tags.type=='aks-slb-managed-outbound-ip'].ipAddress"  --verbose

2021-04-19T11:50:50+00:00 - Getting IPs, in the resource group "MC_ticket2-dev-eastus_ticket2-dev-eastus_eastus", with tag type=aks-slb-managed-outbound-ip returned empty list of IP adressed. Expected list of 5 IP adresses. Used AZ CLI command: az network public-ip list --resource-group "MC_ticket2-dev-eastus_ticket2-dev-eastus_eastus" --subscription "REDACTED" --query "[?tags.type=='aks-slb-managed-outbound-ip'].ipAddress" --verbose
Verbose info returned by AZ CLI:
INFO: Request URL: 'https://management.azure.com/subscriptions/REDACTED/resourceGroups/MC_ticket2-dev-eastus_ticket2-dev-eastus_eastus/providers/Microsoft.Network/publicIPAddresses?api-version=REDACTED'
INFO: Request method: 'GET'
INFO: Request headers:
INFO:     'Accept': 'application/json'
INFO:     'x-ms-client-request-id': '7d97c777-a105-11eb-8ce0-02ba7c23eb6d'
INFO:     'CommandName': 'REDACTED'
INFO:     'ParameterSetName': 'REDACTED'
INFO:     'User-Agent': 'AZURECLI/2.20.0 (DEB) azsdk-python-azure-mgmt-network/17.1.0 Python/3.6.10 (Linux-5.4.0-1045-aws-x86_64-with-debian-buster-sid)'
INFO:     'Authorization': 'REDACTED'
INFO: No body was attached to the request
INFO: Response status: 200
INFO: Response headers:
INFO:     'Cache-Control': 'no-cache'
INFO:     'Pragma': 'no-cache'
INFO:     'Content-Type': 'application/json; charset=utf-8'
INFO:     'Content-Encoding': 'REDACTED'
INFO:     'Expires': '-1'
INFO:     'Vary': 'REDACTED'
INFO:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
INFO:     'x-ms-request-id': 'b77014cc-949a-4c7d-b0ea-55757ff4e69c'
INFO:     'x-ms-correlation-request-id': 'REDACTED'
INFO:     'x-ms-routing-request-id': 'REDACTED'
INFO:     'Strict-Transport-Security': 'REDACTED'
INFO:     'X-Content-Type-Options': 'REDACTED'
INFO:     'Date': 'Mon, 19 Apr 2021 11:50:52 GMT'
INFO:     'Content-Length': '133'
INFO: Command ran in 0.774 seconds (init: 0.097, invoke: 0.677)

2021-04-19T11:50:52+00:00 - Getting IPs, in the resource group "MC_ticket2-dev-westus2_ticket2-dev-westus2_westus2", with tag type=aks-slb-managed-outbound-ip returned empty list of IP adressed. Expected list of 5 IP adresses. Used az cli command: az network public-ip list --resource-group "MC_ticket2-dev-westus2_ticket2-dev-westus2_westus2" --subscription "REDACTED" --query "[?tags.type=='aks-slb-managed-outbound-ip'].ipAddress" --verbose
Verbose info returned by AZ CLI:
INFO: Request URL: 'https://management.azure.com/subscriptions/REDACTED/resourceGroups/MC_ticket2-dev-westus2_ticket2-dev-westus2_westus2/providers/Microsoft.Network/publicIPAddresses?api-version=REDACTED'
INFO: Request method: 'GET'
INFO: Request headers:
INFO:     'Accept': 'application/json'
INFO:     'x-ms-client-request-id': '7e216b21-a105-11eb-8ce0-02ba7c23eb6d'
INFO:     'CommandName': 'REDACTED'
INFO:     'ParameterSetName': 'REDACTED'
INFO:     'User-Agent': 'AZURECLI/2.20.0 (DEB) azsdk-python-azure-mgmt-network/17.1.0 Python/3.6.10 (Linux-5.4.0-1045-aws-x86_64-with-debian-buster-sid)'
INFO:     'Authorization': 'REDACTED'
INFO: No body was attached to the request
INFO: Response status: 200
INFO: Response headers:
INFO:     'Cache-Control': 'no-cache'
INFO:     'Pragma': 'no-cache'
INFO:     'Content-Type': 'application/json; charset=utf-8'
INFO:     'Content-Encoding': 'REDACTED'
INFO:     'Expires': '-1'
INFO:     'Vary': 'REDACTED'
INFO:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
INFO:     'x-ms-request-id': 'f5bdff22-16bc-4fcd-a680-aa30c9f40983'
INFO:     'x-ms-correlation-request-id': 'REDACTED'
INFO:     'x-ms-routing-request-id': 'REDACTED'
INFO:     'Strict-Transport-Security': 'REDACTED'
INFO:     'X-Content-Type-Options': 'REDACTED'
INFO:     'Date': 'Mon, 19 Apr 2021 11:50:53 GMT'
INFO:     'Content-Length': '133'
INFO: Command ran in 0.813 seconds (init: 0.097, invoke: 0.717)

2021-04-19T13:55:17+02:00 - Getting IPs in resource group "MC_ticket2-dev-eastus_ticket2-dev-eastus_eastus" returned list of 5 IP adressed. Result is as expected. Used az cli command: az network public-ip list --resource-group "MC_ticket2-dev-eastus_ticket2-dev-eastus_eastus" --subscription "REDACTED" --verbose
Verbose info returned by AZ CLI:
Request URL: 'https://management.azure.com/subscriptions/REDACTED/resourceGroups/MC_ticket2-dev-eastus_ticket2-dev-eastus_eastus/providers/Microsoft.Network/publicIPAddresses?api-version=REDACTED'
Request method: 'GET'
Request headers:
    'Accept': 'application/json'
    'x-ms-client-request-id': '1bc0571b-a106-11eb-b3dd-2f03ad5837dd'
    'CommandName': 'REDACTED'
    'ParameterSetName': 'REDACTED'
    'User-Agent': 'AZURECLI/2.21.0 (DEB) azsdk-python-azure-mgmt-network/18.0.0 Python/3.6.10 (Linux-5.8.0-48-generic-x86_64-with-debian-bullseye-sid)'
    'Authorization': 'REDACTED'
No body was attached to the request
Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json; charset=utf-8'
    'Content-Encoding': 'REDACTED'
    'Expires': '-1'
    'Vary': 'REDACTED'
    'x-ms-request-id': '6ae02938-320d-41b1-911e-53a39f009b33'
    'x-ms-correlation-request-id': 'REDACTED'
    'x-ms-arm-service-request-id': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
    'x-ms-ratelimit-remaining-subscription-reads': '11962'
    'x-ms-routing-request-id': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Mon, 19 Apr 2021 11:55:18 GMT'

**Expected behavior**
The list of IP addresses is available immediately after the deployment is completed and is always consistent between calls.

**Environment summary**
'AZURECLI/2.20.0 (DEB) azsdk-python-azure-mgmt-network/17.1.0 Python/3.6.10 (Linux-5.4.0-1045-aws-x86_64-with-debian-buster-sid)
Installed from deb package.

**Additional context**

**Comment by yonzhan** [comment]
route to network service team to take a look

**Comment by 180254** [comment]
A have got a response from Azure Support Engineer.

> Azure is a multi-regional product, where relative information of resources and their state needs to be replicated across multiple regions. Our investigation discovered that the issue that you encountered on 20-4-21 was caused by a transient delay in replication flow between Azure’s regions. This issue is restricted to resources which are simultaneously managed by clients spread across multiple geographies. The resources for which writes are restricted to a client from single region shouldn’t face this issue. We recognize that this as a problem, and we are continuously working on improving the platform.

> We are currently in process of rolling out a new design to address these type of delays in replication. This functionality has not yet been rolled out to general release, across all subscriptions. If you would like to be included in the upcoming preview, please let us know and we can work on including your subscription when the preview becomes available. 

>We apologize for any inconvenience that this may have caused.

> Workaround that could help until the new version is available. It is changing the ARM endpoint to ask directly where the resource was deployed, in the next example eastus2, please change accordingly and don’t forget to put the management.azure.com after gathering the information.
```
az cloud update --endpoint-resource-manager https://eastus2.management.azure.com
az network nsg list --resource # ... or the commands you need.
az cloud update --endpoint-resource-manager https://management.azure.com
```
