### ISSUE TITLE
Cannot delete resource group named with leading dashes

### ISSUE THREAD

**Issue by mladedav** [Azure/azure-cli#17762]
**Describe the bug**
Running `az group delete -y --no-wait -n "-bad-resource-group-name"` outputs
```
argument --name/-n/--resource-group/-g: expected one argument

TRY THIS:
az group delete --resource-group MyResourceGroup
Delete a resource group.

https://docs.microsoft.com/en-US/cli/azure/group#az_group_delete
Read more about the command in reference docs`
```

**To Reproduce**
Create a resoruce group with a leading dash and then try to delete it. I have not tried to create it with az tool, we accidentally made them with ARM templates and now I am trying to get rid of them.

`az group delete -y --no-wait -n "-bad-resource-group-name"`

**Expected behavior**
Resource group gets deleted with no errors in CLI.

**Environment summary**
```
Microsoft Windows 10.0.18363,
PS Core 7.0.1
Python 3.8.2
{
  "azure-cli": "2.19.1",
  "azure-cli-core": "2.19.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.6",
    "application-insights": "0.1.1",
    "dev-spaces": "1.0.3"
  }
}
```

**Comment by yonzhan** [comment]
ARM

**Comment by mladedav** [comment]
I just want to clarify because based on the tags I believe there is some kind of misunderstanding.

This has nothing to do with ARM but with how arguments are parsed in Azure CLI. It incorrectly assumes that anything that starts with a hyphen is a new option. Also I believe this is a bug report and not a feature request, the feature (deleting resource groups) is present, it just does not work for some edge cases because of argument parsing.

Also based on [naming restrictions](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules), this concrete case should not happen as resource groups must start in a lowercase letter (which ARM seems to ignore and even creates `NetworkWatcherRG` which also violates this rule). But there are other resources (e.g. AppConfiguration) that do not have similar restrictions and therefore can start in a hyphen so this should be probably fixed.

**Comment by jiasli** [comment]
Duplicate of #2588 and #16044, please see the workaround at https://github.com/Azure/azure-cli/issues/16044#issuecomment-733955065.

**Comment by mladedav** [comment]
For further reference, the linked workaround is to use an equal sign before the value.
```az group delete -y --no-wait --name="-bad-resource-group-name"```
