### ISSUE TITLE
az appservice plan: Optional parameters for plan show

### ISSUE THREAD

**Issue by Sachid26** [Azure/azure-cli#17786]
the optional parameters(resourcer groups, ids etc) mentioned on the doc page come as required when trying to run on  az appservice plan show. I was wondering if an update was required on the documentation.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f99cdf3a-4fd3-e949-aabe-1b26fe828444
* Version Independent ID: 1c2e7517-1275-9e30-db67-393c0451055f
* Content: [az appservice plan](https://docs.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest#az_appservice_plan_update)
* Content Source: [latest/docs-ref-autogen/appservice/plan.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/appservice/plan.yml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Sachid26** [comment]
docs need similar updation for the "**az appservice plan update**" command too

**Comment by yungezz** [comment]
route to appropriate team
