### ISSUE TITLE
WebApp:not wokring: az webapp config storage-account add 

### ISSUE THREAD

**Issue by Band-Aid** [Azure/azure-cli#17788]
> ### `az feedback` auto-generates most of the information requested below, Azure-cli    Azure-cli-core    Azure-cli-telemetry
-----------  ----------------  ---------------------
2.20.0       2.20.0            1.0.6

**Describe the bug**
az webapp config storage-account add returns a bad request

**To Reproduce**
The following command returns a bad request error
az webapp config storage-account add -g BeerSearchRSG -n beerproject \
>   --custom-id appwww\
>   --storage-type AzureFiles \
>   --account-name appstorage\
>   --share-name app\
>   --access-key xxxxxxxx\
>   --mount-path /var/www/

This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Operation returned an invalid status code 'Bad Request'

**Expected behavior**
Should be able to add storage to my webapp
**Environment summary**
Windows 10 x64 - WSL ubuntu 20.04 LTS

**Additional context**
Referenced documents:
https://docs.microsoft.com/en-us/cli/azure/reference-types-and-status
https://docs.microsoft.com/en-us/azure/app-service/configure-connect-to-azure-storage?pivots=container-linux

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
@Band-Aid It must be because of some incorrect input value. Please share the `--debug` log for your command to analyze further.

**Comment by Band-Aid** [comment]
I just tried the exact same command but it is working now. Strange but at least it's working :)

**Comment by besmiralia** [comment]
@Band-Aid  
It throws bad request when the mount already exists. I just tried it myself and once I deleted the existing mount, it worked fine.
Not sure if there is a way to overwrite it by force if it exists and not throw the error.
