### ISSUE TITLE
What-If deployment: print report and exit

### ISSUE THREAD

**Issue by mauve** [Azure/azure-cli#17789]
**Is your feature request related to a problem? Please describe.**

I would like to use `az sub deployment create --confirm-with-what-if` as part of a pipeline step and just print the report for example to use as input to a manual verification step.

**Describe the solution you'd like**

`az sub deployment create --confirm-with-what-if --dry-run`: Perform the what-if analysis, prints the report and then exit, preferably with an exit code which also means something (0 on success, != 0 if something is wrong).

**Describe alternatives you've considered**

`echo "n" | az deployment sub create --confirm-with-what-if`, that however always exits with `1` indicating failure.

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
@shenglol Could you please take a look at this feature request?

**Comment by shenglol** [comment]
Hi @mauve , there's a command called `what-if` which does exactly what you want:
```
az sub deployment what-if ...
```

**Comment by mauve** [comment]
cool thanks
