### ISSUE TITLE
AKS/AZ CLI

### ISSUE THREAD

**Issue by Shaybs** [Azure/azure-cli#17785]
az login --identity

Returns:

request failed: Error occurred in request., ConnectionError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions?api-version=2019-06-01 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7feddcbae470>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Within a pod when previously it was working fine.

**Comment by jiasli** [comment]
The error message `Name or service not known` means the server is unable to do DNS lookup for `management.azure.com`.

Could you try resolving the DNS name using:

```sh
dig management.azure.com

# or
nslookup management.azure.com
```

Also, could you let us know in what environment you are running `az login`?

**Comment by Shaybs** [comment]
We've fixed this issue with Microsoft support. A client may have changed their network rules and we ended up using another method for AKS/pods to look up certain websites.

**Comment by Shaybs** [comment]
Thanks, you may close this issue.
