### ISSUE TITLE
deployment: prompt if parameters are not provided 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#1778]
For now, it is by design, but if we have more user voices, we can reconsider.
Mark it as discussion.

**Comment by brendandburns** [comment]
I'd vote in favor of at least making it available as a flag... (`--prompt`)?

If you don't specify values it's going to fail anyway, is that really the desirable behavior?

**Comment by lostintangent** [comment]
I'm with @brendandburns on this. The current experience isn't particularly inspiring for the first impression/getting started experience, and I think it would go along way to have a prompt for parameters. 

In fact, it would be even more awesome if the CLI allowed you to write out the parameters file with the values you specified to the prompt. That way it would work just like `npm init` and other similar experiences. Then you could take a template URI and combine it with the CLI to have a slightly more guided deployment experience.

**Comment by brendandburns** [comment]
@yugangw-msft what do you think? I'm happy to implement this...

Thanks
--brendan

**Comment by johanste** [comment]
@lostintangent, agreed on template file generation - it would be a very valuable command.

@brendandburns, if you can create a pull request for prompting on --prompt, we'd love to have it :). 

A couple of notes: we want to (at a minimum) support keyvault references in the parameters file (and thus avoid issues like https://github.com/Azure/azure-xplat-cli/issues/3444). I don't believe that we'd have to support providing keyvault references in the prompting logic, but if someone comes up with a reasonable way to do so, it would be awesome.

**Comment by brendandburns** [comment]
Ok, I will start in on implementing this.
