### ISSUE TITLE
webapp:"az staticwebapp appsettings set": values with equal sign (=) are truncated

### ISSUE THREAD

**Issue by gastonmuijtjens** [Azure/azure-cli#17792]
## Describe the bug
Setting App Settings that contain an equal sign (=) for an Azure Static Web App using the CLI truncates the setting after the first equal sign.

**Command Name**
`az staticwebapp appsettings set`

**Errors:**
The setting value is truncated. Only the part before the first equal sign (`=`) is set.

## To Reproduce:
- `az staticwebapp appsettings set --name {name} --setting-names StorageAccount="DefaultEndpointsProtocol=https;AccountName={account_name};EndpointSuffix=core.windows.net;AccountKey={account_key}"`

## Expected Behavior
- `az staticwebapp appsettings list --name {name}` outputs the following:
```json
{
  "id": "{id}",
  "kind": null,
  "location": "West Europe",
  "name": "appsettings",
  "properties": {
    "StorageAccount": "DefaultEndpointsProtocol=https;AccountName={account_name};EndpointSuffix=core.windows.net;AccountKey={account_key}"
  },
  "resourceGroup": "{resource_group}",
  "type": "Microsoft.Web/staticSites/config/functionappsettings"
}
```

## Actual Behavior
- `az staticwebapp appsettings list --name {name}` outputs the following:
```json
{
  "id": "{id}",
  "kind": null,
  "location": "West Europe",
  "name": "appsettings",
  "properties": {
    "StorageAccount": "DefaultEndpointsProtocol="
  },
  "resourceGroup": "{resource_group}",
  "type": "Microsoft.Web/staticSites/config/functionappsettings"
}
```

The `StorageAccount` property is missing the part after the first equal sign (`=`).

## Environment Summary
```
macOS-11.2.3-x86_64-i386-64bit
Python 3.8.9
Installer: HOMEBREW

azure-cli 2.22.1

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by gastonmuijtjens** [comment]
When running the command with the `--debug` parameter, it produces the following output:
```
msrest.http_logger: Request URL: 'https://management.azure.com/subscriptions/{subscription_id}/resourceGroups/{resource_group}/providers/Microsoft.Web/staticSites/{name}/config/functionappsettings?api-version=2019-08-01'
msrest.http_logger: Request method: 'PUT'
msrest.http_logger: Request headers:
msrest.http_logger:     'Accept': 'application/json'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'accept-language': 'en-US'
msrest.http_logger:     'Content-Length': '68'
msrest.http_logger:     'User-Agent': 'python/3.8.9 (macOS-11.2.3-x86_64-i386-64bit) msrest/0.6.21 msrest_azure/0.6.3 azure-mgmt-web/0.48.0 Azure-SDK-For-Python AZURECLI/2.22.1 (HOMEBREW)'
msrest.http_logger: Request body:
msrest.http_logger: {"properties": {"StorageAccount": "DefaultEndpointsProtocol="}}
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
```

The request property `StorageAccount` is sent in a wrong way to the API, so it seems to be a problem with the CLI rather than the API itself.

**Comment by Kotasudhakarreddy** [comment]
@gastonmuijtjens able to repro this issue. Will consider this for future releases.

**Comment by aressler38** [comment]
@Kotasudhakarreddy,  what other options do we have for setting the app settings? Is there another way of doing it that works? I meanwhile I have been replacing = with a different token and doing a string replacement in app code 🤮

**Comment by Kotasudhakarreddy** [comment]
> @Kotasudhakarreddy, what other options do we have for setting the app settings? Is there another way of doing it that works? I meanwhile I have been replacing = with a different token and doing a string replacement in app code 🤮

@panchagnula do we have any alternative way for this.

**Comment by benc-uk** [comment]
I'm hitting this, it's a real pain

Any signs of a fix?

**Comment by panchagnula** [comment]
> I'm hitting this, it's a real pain
> 
> Any signs of a fix?

Sorry no ETA at this time. Will reach out to StaticWebApp folks to check if they can fix it.

**Comment by aressler38** [comment]
The issue in this function `def _parse_pair(pair, delimiter):` seen [here](https://github.com/Azure/azure-cli/blob/2f75074f6961162d1136f8b509468946f28c4f3f/src/azure-cli/azure/cli/command_modules/appservice/static_sites.py#L264). This is super easy to fix.

**Comment by anthonychu** [comment]
@miwebst

**Comment by aressler38** [comment]
In the meanwhile the [az rest](https://docs.microsoft.com/en-us/azure/static-web-apps/application-settings) utility works, and it doesn't have a problem with equal signs. You have to create a json file and invoke the command like this.

    az rest --method put --headers "Content-Type=application/json" \
        --uri "/subscriptions/<YOUR_SUBSCRIPTION_ID>/resourceGroups/<YOUR_RESOURCE_GROUP_NAME>/providers/Microsoft.Web/staticSites/<YOUR_STATIC_SITE_NAME>/config/functionappsettings?api-version=2019-12-01-preview" \
        --body @local.settings.properties.json

The the moment `az staticwebapp appsettings set` seems broken in az-cli version 2.23.0, so I will be switching to the `az rest` method for the time being.

**Comment by panchagnula** [comment]
This is fixed by static apps team, so closing this.
