### ISSUE TITLE
WebApp:az webapp up

### ISSUE THREAD

**Issue by MansiLad** [Azure/azure-cli#17790]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
('Connection aborted.', OSError("(10054, 'WSAECONNRESET')",))
Traceback (most recent call last):
pip-unpacked-wheel-ce49rpvu\urllib3\contrib\pyopenssl.py, ln 331, in _send_until_done
Temp\pip-unpacked-wheel-o9ys4f_j\OpenSSL\SSL.py, ln 1737, in send
Temp\pip-unpacked-wheel-o9ys4f_j\OpenSSL\SSL.py, ln 1639, in _raise_ssl_error
OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

...

Temp\pip-unpacked-wheel-kwr6xmq7\requests\sessions.py, ln 646, in send
Temp\pip-unpacked-wheel-kwr6xmq7\requests\adapters.py, ln 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')",))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --name {} --sku {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.18.0 *

Extensions:
hack 0.4.3

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
@MansiLad I am unable to repro this issue. Please retry this with `CLI version 2.22.0` . If you still face the issue  share `-debug` logs

**Comment by Kotasudhakarreddy** [comment]
closing due to lack of response. Please file a new issue if this is still a problem.
