### ISSUE TITLE
Missing az keyvault set-policy with compound identity

### ISSUE THREAD

**Issue by tshaiman** [Azure/azure-cli#17806]
[Enter feedback here]
looking at az keyvault set-policy docs comparing to Set-AzKeyVaultAccessPolicy PowerShell atlernative
since the two calls should be identical I could not find in the docs the option to run the following : 

```PowerShell
Set-AzKeyVaultAccessPolicy -VaultName $KVNAM -ObjectId $OID -ApplicationId $APP_ID -PermissionsToSecrets Get 
```
the above command adds a permission to COMPOUND IDENTITY on the KV

PS docs : 
https://docs.microsoft.com/en-us/powershell/module/az.keyvault/set-azkeyvaultaccesspolicy

Key Vault Security Overview  ( look for the term 'compound identity' ) 
https://docs.microsoft.com/en-us/azure/key-vault/general/security-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226e5769-f6c8-a480-db78-727fb96348ec
* Version Independent ID: 8ee06a2a-6eda-11be-3c8e-6ad948be207e
* Content: [az keyvault](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/keyvault.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/keyvault.yml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
add @houk-ms to have a look

**Comment by MaurGi** [comment]
+1, we need this @yungezz,  @houk-ms - we would be really appreciate it.
