### ISSUE TITLE
No output format provided for any of the cli commands

### ISSUE THREAD

**Issue by Morriz** [Azure/azure-cli#17808]
No output format provided for any of the cli calls.

Example: `az network public-ip create`

Does it give back an ip address? What is the shape of the result?

Please provide reference documentation that is generated from api specs, and stop asking humans to produce this. 

We are in 2021 and devs expect to find reference docs that are complete. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c12e07f8-d82f-a9ac-895a-b6d980c8c4c2
* Version Independent ID: 43924bb5-20bd-6a0e-9cdc-90b1db46e599
* Content: [az network public-ip](https://docs.microsoft.com/en-us/cli/azure/network/public-ip?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/public-ip.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/public-ip.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Same issue as #17332. @msyyc to provide the REST API link.
