### ISSUE TITLE
[SSHKEY] Generated private key is not shown to users

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#17801]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When a user doesn't pass public key to "az sshkey create", it will invoke 
```
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/sshPublicKeys/{sshPublicKeyName}/generateKeyPair
```
to generate a key pair. But the private key is not shown to user. Sshkey resource only stores public key. The user can never know the private key.

2 Solutions:

(1) Do not add extra logic for users. Do not generate key pair for users automatically. Expose generateKeyPair command.

(2) Add a field "privateKey" in response.

I prefer (1).

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yungezz** [comment]
sshkey issue

**Comment by SorraTheOrc** [comment]
My original spec said that when a key was generated it should provide the same behavior as the --generate-ssh-key. I'm still unclear why this has not been implemented. Why would the behavior be different from the behavior of --generate-ssh-key? In that scenario the key is automatically saved in the users ~/.ssh directory. 

Option 2, return the key, requires the user to know they must save the key, along with the public key. They therefore need to copy and paste to save. If they fail to do so then the key is gone forever. Not to mention you are talking about displaying the private key on the monitor, possibly without the user even realizing it. 

If we can't make the behaviour the same for some reason then Option 1 is the lesser of two evils.

**Comment by qwordy** [comment]
@SorraTheOrc --generate-ssh-keys only generates and saves keys if there is no key in ~/.ssh
az sshkey create​ will keep same behavior when generating new SSH key pairs. Save keys to ~/.ssh if it is empty. Do not create new SSH key resource when no public key provided and there is key in ~/.ssh. Will print warning and error to tell users what happened.
How about this solution?

**Comment by SorraTheOrc** [comment]
This is not the intended behaviour.

`az sshkey create` should always create a key. It does not mean "create if we don't have one" it means "store the provided ket or create a new one if I don't provide it". Therefore, when generating, it can always save the key in "~/.ssh".
