### ISSUE TITLE
postgres server list-skus throws "subscription does not exist" in empty subscription

### ISSUE THREAD

**Issue by jorenvs** [Azure/azure-cli#17807]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When there are no databases in the subscription yet, trying to list the skus in westeurope region (same for other regions) for postgres sql, the command always complains about the subscription:
```
 Subscription '*redacted*' does not exist
```

Creating a database works however and after that the list-skus command works as well, which seems like a bug. You need the list before creating a database, not after.

**To Reproduce**

Authenticated to a fresh subscription
```
az postgres server list-skus -l westeurope           
```

**Expected behavior**

list of skus for postgres in region westeurope
**Environment summary**

installed through `brew install azure-cli` on OS X

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by nachoalonsoportillo** [comment]
@jorenvs Thanks for reporting this issue! Unfortunately, this is a limitation in Azure Database for MariaDB, MySQL Single Server, and PostgreSQL Single Server. Only when you have created the first server in a subscription, the `/performanceTiers` REST API endpoint responded with the expected payload. Once you create that first server, even if you drop it, the `/performanceTiers`endpoint will continue working as expected.

That is not the case with Azure Database for MySQL Flexible Server or PostgreSQL Flexible Server. In those two services, the equivalent endpoint, `/capabilities`, returns the payload even if you invoke it against subscriptions on which you've never deployed any instance.

**Comment by nachoalonsoportillo** [comment]
@yonzhan Please, close this one. Thanks!
