### ISSUE TITLE
az signalr upstream update does not support KeyVault reference syntax

### ISSUE THREAD

**Issue by fgheysels** [Azure/azure-cli#17804]
**Describe the bug**

I have deployed Azure Signalr and I want to set the upstream settings via `az signalr upstream update` using a KeyVault reference, like this:

```
az signalr upstream update  --name mysignalr --resource-group myresourcegroup --template url-template="http://.../runtime/webhooks/signalr?code={@Microsoft.KeyVault(SecretUri='mysecreturi')}"
```
This gives me the error: 
> } was unexpected at this time.

When I remove the @ symbol from the url template, I do not get this error.
Unfortunately, the @ symbol is required in this syntax.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.22.1

Extensions:
alertsmanagement 0.1.0
application-insights 0.1.13
azure-iot 0.10.7
interactive 0.4.4
timeseriesinsights 0.1.3

**Comment by yonzhan** [comment]
route to service team

**Comment by chenkennt** [comment]
@zackliu please help take a look

**Comment by zackliu** [comment]
I think it's the problem of powershell. I tried on CMD or Linux Bash, and both are work fine

**Comment by fgheysels** [comment]
> I think it's the problem of powershell. I tried on CMD or Linux Bash, and both are work fine

Is it then something that can be fixed ?  And where should it be fixed ?

**Comment by fgheysels** [comment]
@zackliu  is this something for the Powershell team then ?

**Comment by fgheysels** [comment]
Any news on this ?

**Comment by zackliu** [comment]
Seems it's the issue in azure cli core. Run command in cmd or bash to mitigate the issue. Or using this mitigation: https://github.com/Azure/azure-cli/issues/10066#issuecomment-1271747789

**Comment by fgheysels** [comment]
So, I understand this won't be fixed as you can 'mitigate' it by working around the issue ?
