### ISSUE TITLE
Unable to run functionapp update

### ISSUE THREAD

**Issue by VIPHercules** [Azure/azure-cli#17818]
## Describe the bug

**Command Name**
`az functionapp update`

**Errors:**
```
'NoneType' object has no attribute 'resource_group'
Traceback (most recent call last):
cli\Lib\site-packages\knack\cli.py, ln 231, in invoke
azure\cli\core\commands\__init__.py, ln 657, in execute
azure\cli\core\commands\__init__.py, ln 720, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 712, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 61, in _ex_handler
azure\cli\core\commands\__init__.py, ln 691, in _run_job
azure\cli\core\commands\__init__.py, ln 328, in __call__
azure\cli\core\commands\arm.py, ln 526, in handler
azure\cli\command_modules\appservice\custom.py, ln 650, in update_functionapp
AttributeError: 'NoneType' object has no attribute 'resource_group'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp update --resource-group {} --subscription {} --name {} --plan {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.22.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by apawast** [comment]
@VIPHercules has this issue persisted for you? 

cc @gzuber

**Comment by VIPHercules** [comment]
Hi. The issue did persist, but I think it was due to the fact the function app plan was set to always on as I also couldn't perform the action in the azure and that was the feedback I was given by the UI. Once I disabled the always on action I was able to perform the update in the portal, I did not retry vie the azure cli however. Thanks for responding.
