### ISSUE TITLE
Example of blob move command fails

### ISSUE THREAD

**Issue by realrubberduckdev** [Azure/azure-cli#17819]
```
az storage blob move -c MyContainer -d DestinationBlobPath -s SourceBlobPath --account-name MyStorageAccount
```

Fails with
```
'move' is misspelled or not recognized by the system
```

My az cli is up to date
```
az --version
azure-cli                         2.22.1

core                              2.22.1
telemetry                          1.0.6

Extensions:
account                            0.2.1
application-insights              0.1.13
subscription                       0.1.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\N16263\.azure\cliextensions'

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

Is the example incorrect or am I doing something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/blob.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/blob.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Storage

**Comment by evelyn-ys** [comment]
Hi @realrubberduckdev, `az storage blob move` is in `storage-preview` extension. You need to install extension first. In addition, this command has been deprecated, you can use `az storage fs file move` instead.
![image](https://user-images.githubusercontent.com/10227683/125412686-b6e4bf00-e3f1-11eb-9c04-804ec9adcef0.png)
