### ISSUE TITLE
Team Chaos Azurecli

### ISSUE THREAD

**Issue by chaos-ui** [Azure/azure-cli#17820]
## Describe the bug

**Command Name**
`az version`

**Errors:**
```
unrecognized arguments: [--subscription]
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az version {}`

## Environment Summary
```
Linux-4.15.0-1113-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.22.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.4

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
A spambot, also spamming .NET Core (https://github.com/dotnet/core/pull/6181).
