### ISSUE TITLE
az aks commands not recognized

### ISSUE THREAD

**Issue by Alfredo-77** [Azure/azure-cli#17824]
## Describe the bug

Hello team, I have installed extension az-preview, but when I try to execute a command like **az aks list**, the following error is displayed: **'aks' is misspelled or not recognized by the system.**

az version output with the evidence of the extension installed:
{
  "azure-cli": "2.22.1",
  "azure-cli-core": "2.22.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.10"
  }
}

Thank you very much for your help

**Command Name**
az aks list

**Errors:**
'aks' is misspelled or not recognized by the system.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Expected Behavior
Getting the list of kubernetes clusters of the linked subcription

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.22.1

Extensions:
aks-preview 0.5.10

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Alfredo-77** [comment]
Hello, I have managed to solved the issue. 

My AzureCloud profile was not the latest. It was "2019-03-01-hybrid"

az cloud list -o table
IsActive    Name               Profile
----------  -----------------  -----------------
True        AzureCloud         2019-03-01-hybrid
False       AzureChinaCloud    latest
False       AzureUSGovernment  latest
False       AzureGermanCloud   latest

Profile changed to latest with: az cloud set --name AzureCloud --profile "latest"

az cloud list -o table
IsActive    Name               Profile
----------  -----------------  ---------
True        AzureCloud         latest
False       AzureChinaCloud    latest
False       AzureUSGovernment  latest
False       AzureGermanCloud   latest

now az aks commands work file :)

Please, close this issue and thank you very much
