### ISSUE TITLE
no defaults mentioned

### ISSUE THREAD

**Issue by Morriz** [Azure/azure-cli#17827]
No default is mentioned for `--public-access`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcba5ed-e693-6345-2c1b-c17422d7b8f9
* Version Independent ID: 58297400-b777-6868-1687-0af3a512a16f
* Content: [az storage container](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/container.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/container.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Hi @Morriz, when not metioned, the default value is `None`.

**Comment by Morriz** [comment]
@evelyn-ys did you add this to the docs? Otherwise I advise to keep this open...

**Comment by evelyn-ys** [comment]
> @evelyn-ys did you add this to the docs? Otherwise I advise to keep this open...

Actually, for all the arguments in CLI, the default value is `None` if not mentioned. Only if when it has different default, we will hint in help.
![image](https://user-images.githubusercontent.com/10227683/126418594-93920910-966e-4cc4-875d-03e75c737eba.png)

**Comment by Morriz** [comment]
It seems my best takeaway from your response is the fact that we can use hinting to see defaults and format of input parameters. Is that assumption correct? Can I see hinting for every input param consistently and rely on that? If so is that reflected in the docs?

**Comment by evelyn-ys** [comment]
> It seems my best takeaway from your response is the fact that we can use hinting to see defaults and format of input parameters. Is that assumption correct? 

Yes. Each argument which has set default value explicitly will auto-generate the hint in help msg.

> Can I see hinting for every input param consistently and rely on that?

I can't ensure every param because some command might have implicit transformer in Python SDK or CLI customization. But most of them are reliable.

> If so is that reflected in the docs?

Which CLI docs are you referring? I'll discuss this internally about the doc.

**Comment by Morriz** [comment]
https://docs.microsoft.com/en-us/cli/azure/
