### ISSUE TITLE
WebApp:az webapp auth update not compatible with Auth settings 2.0 

### ISSUE THREAD

**Issue by lopezleandro03** [Azure/azure-cli#17837]
**Is your feature request related to a problem? Please describe.**
Using the Azure CLI, it is not possible to script authentication settings on either App Service or Azure Function that were configured using authentication settings 2.0 using.

With Authentication(Classic), it is possible using `az webapp auth update` but when trying with a Function App that was  configured using the Azure Portal new Authentication UI it fails with `Bad Request`.

Running `az webapp auth update` on `debug` mode it shows the following:

```json
{
  "Code": "BadRequest",
  "Message": "Cannot execute the request for site func-edl-storage-service-qa because the site is running on auth version v2.",
  "Target": null,
  "Details": [
    {
      "Message": "Cannot execute the requestfor site func-edl-storage-service-qa because the site is running on auth version v2."
    },
    {
      "Code": "BadRequest"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "04534",
        "MessageTemplate": "Cannot execute the request for site {0} because the site is running on auth version {1}.",
        "Parameters": [
          "func-edl-storage-service-qa",
          "v2"
        ],
        "Code": "BadRequest",
        "Message": "Cannot execute the request for site func-edl-storage-service-qa because the site is running on auth version v2."
      }
    }
  ],
  "Innererror": null
}
```

Clearly, the CLI commands is not compatible with Authentication 2.0

**Describe the solution you'd like**
`az webapp auth update` should work with App Services and Function Apps configured using the new Portal Authentication UI.

**Describe alternatives you've considered**
- PowerShell: there isn't a documented method to set Authentication on sites.

**Additional context**
- [Authentication and authorization in Azure App Service and Azure Functions](https://docs.microsoft.com/en-gb/azure/app-service/overview-authentication-authorization#identity-providers)

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
Taking a look in to this.

**Comment by watsonb** [comment]
Any updates on this?  I, too, would like `az webapp auth` to create Auth settings 2.0 instead of classic.

**Comment by lopezleandro03** [comment]
Any updates about this feature?

**Comment by agravity-philipp** [comment]
Would be great to have this supported. More urge because Classic Auth was discontinued from portal (upgrade needed).

**Comment by DrReedo** [comment]
We're also having the same issue as we deploy our App Services with Infrastructure as Code and have noticed that we cannot set our required parameters once the Authentication has been upgraded from classic.  I see this has been open since 23 April 2021, are there any plans to fix it?

**Comment by panchagnula** [comment]
Hi folks - new Easy Auth (non classic) was added to CLI as an extension, while keeping the classic experience available as well.  

"To use v2 auth commands, run "az extension add --name authV2" to add the authV2 CLI extension." See: https://docs.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest

We will work with the feature crew to ensure we can fully deprecate/ remove the classic experience in core-cli & only support the new version. Tentative ETA: April release. Thank you & sorry for the confusion.

**Comment by DrReedo** [comment]
> Hi folks - new Easy Auth (non classic) was added to CLI as an extension, while keeping the classic experience available as well.
> 
> "To use v2 auth commands, run "az extension add --name authV2" to add the authV2 CLI extension." See: https://docs.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest
> 
> We will work with the feature crew to ensure we can fully deprecate/ remove the classic experience in core-cli & only support the new version. Tentative ETA: April release. Thank you & sorry for the confusion.

Hi @panchagnula, is this fully compatible with V2?  We have tried upgrading our Authentication in the Portal and then found that we cannot run the command
`az extension add --name authV2
az webapp auth update -n "$(AppService)" -g "$(ResourceGroupName)" --action AllowAnonymous --enabled false `
against it as it gives 'BadRequest' as detailed above.  How can we set Anonymous access with the V2 version?  Will this be possible?  Please don't deprecate before this has been proved.  thank you

**Comment by panchagnula** [comment]
> > Hi folks - new Easy Auth (non classic) was added to CLI as an extension, while keeping the classic experience available as well.
> > "To use v2 auth commands, run "az extension add --name authV2" to add the authV2 CLI extension." See: https://docs.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest
> > We will work with the feature crew to ensure we can fully deprecate/ remove the classic experience in core-cli & only support the new version. Tentative ETA: April release. Thank you & sorry for the confusion.
> 
> Hi @panchagnula, is this fully compatible with V2? We have tried upgrading our Authentication in the Portal and then found that we cannot run the command `az extension add --name authV2 az webapp auth update -n "$(AppService)" -g "$(ResourceGroupName)" --action AllowAnonymous --enabled false ` against it as it gives 'BadRequest' as detailed above. How can we set Anonymous access with the V2 version? Will this be possible? Please don't deprecate before this has been proved. thank you

@DrReedo AFAIK once you have updated to V2 you cannot use the classic / v1 anymore hence the need to install the v2 extension & run the v2 specific commands, ex. https://docs.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest#az-webapp-auth-set 
@mkarmark the owner of v2 commands & feature to help assist with any questions as well.

**Comment by panchagnula** [comment]
@Hamster-Huey FYI

**Comment by seligj95** [comment]
closing due to lack of response and confirmation of functionality by service team. please reopen if needed.
