### ISSUE TITLE
Support NetworkApiVersion for Vmss with OrchestraionMode == Flexible

### ISSUE THREAD

**Issue by szimmerMicrosoft** [Azure/azure-cli#17830]
**Resource Provider**
CRP 

**Description of Feature or Work Requested**

If VMSS Orchestration mode is Flexible allow users to specify network-api-verision which will populate the networkApiVersion in the networkProfile of the VMSS

sample commands:

![image](https://user-images.githubusercontent.com/11670642/115800715-0c2fa800-a390-11eb-8ef6-0a6fd043679f.png)

Background:
[User Experience Doc](https://microsoft.sharepoint.com/:w:/t/ComputeVM/EVXca8iMvx9PpGMs5euyn3MB4_maG5q7UZ-Mn4yM0dxwqQ?e=zuy1NS)

When a VMSS has orchestration mode set to Flexible, specifying the virtual machine profile is now possible, and will create VMs that are registered with ARM as top level VMs (rather than special VMScaleSetVMs).
When specifying the networkProfile for VMSS Flexible VMSSes we require that the networkApiVersion is populated, networkApiVersion cannot be populated if VMSS Orchestration mode is not flexible.

Additionally if a networkProfile for a VMSS is being added, and OrcehstrationMode == Flexbile, if the user does not provide a networkApiVersion automatically populate version = "2020-11-01"

**Minimum API Version Required**
2021-03-01

**Swagger Link**
Swagger pull request: https://github.com/Azure/azure-rest-api-specs/pull/13449

We are concerned specifically with the vmscaleset.properties.virtualmachineprofile.properties.networkProfile.networkApVersion property being set.

**Target Date**
6/15/2021

**Comment by yungezz** [comment]
2021-03-01 API version not available yet.

**Comment by szimmerMicrosoft** [comment]
I was told to make the design request now, so that we can get the design approved, and then when 2021-03-01 is published we will have an approved design.

Is this not the correct appoach?

**Comment by yungezz** [comment]
you're right @szimmerMicrosoft. We need to track status of Swagger, then make sure there's enough time buffer for Python SDK and CLI to catch 5/25 target.
