### ISSUE TITLE
az cosmosdb sql requires an api version (Microsoft.DocumentDB/databaseAccounts 2021-03-15) not available in US Gov Clouds

### ISSUE THREAD

**Issue by zweim1** [Azure/azure-cli#17844]
## Describe the bug
Fail to run az cosmosdb sql commands for database accounts in US Gov Cloud. 
Example: az cosmosdb sql database list --account-name MyAccount --resource-group MyResourceGroup.
The cosmosdb cli requires "providers/Microsoft.DocumentDB/databaseAccounts, api-version=2021-03-15", but US Gov Clouds do not have this specific api version. 

**Command Name**
`az cosmosdb sql database list`

**Errors:**
```
No registered resource provider found for location 'usgovvirginia' and API version '2021-03-15' for type 'databaseAccounts'. The supported api-versions are '2014-04-01, 2015-04-08, 2015-11-06, 2016-03-19, 2016-03-31, 2019-08-01-preview, 2019-08-01, 2019-12-12, 2020-03-01, 2020-04-01, 2020-06-01-preview, 2020-09-01, 2021-01-15, 2021-03-01-preview, 2021-04-01-preview, 2021-04-15'. The supported locations are 'usgovarizona, usgovtexas, usdodcentral, usdodeast, usgovvirginia'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cosmosdb sql database list --account-name {} --resource-group {}`

## Environment Summary
```
Linux-4.15.0-1113-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.22.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.4

```

**Comment by zweim1** [comment]
In Azure DevOps, all the Microsoft-hosted agents (https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml) are using Azure CLI (azure-cli) 2.22.0

**Comment by yonzhan** [comment]
route to service team

**Comment by MehaKaushik** [comment]
Thanks for pointing this out. Looking into this.

**Comment by MehaKaushik** [comment]
Somehow we missed rolling this apiVersion in this region. We working on this now. I will update here once done. Thanks again for bringing this to our attention.

**Comment by MehaKaushik** [comment]
Hey, I realized you can unblock yourself by using the apiVersion 2021-04-15. We have not publicly announced it yet, but it is rolled out in all regions and contains everything that exists in 2021-03-15.

**Comment by zweim1** [comment]
We use Microsoft-hosted agents
(https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml) in Azure DevOps, which  all have pre-installed Azure CLI (azure-cli) 2.22.1. 
I don't know how you can instruct the az cli to use the apiVersion 2021-04-15. 
But our workaround is to downgrade the az cli to an earlier (and working) version.

**Comment by zweim1** [comment]
Microsoft.DocumentDB/databaseAccounts API version '2021-03-15'" was added to our US Gov Subscriptions this morning. So the issue can be closed.
