### ISSUE TITLE
"Triage" is spelled "Tirage" on App Service Project board

### ISSUE THREAD

**Issue by bgrainger** [Azure/azure-cli#17843]
At https://github.com/Azure/azure-cli/projects/19#column-6357476 there is a column labelled "Tirage". I'm assuming this should be "Triage".

![image](https://user-images.githubusercontent.com/188129/115909349-40eb4000-a420-11eb-9c19-875f64a1de9f.png)

**Comment by yonzhan** [comment]
Updated, thanks
