### ISSUE TITLE
API Management support for KeyVault Named Values

### ISSUE THREAD

**Issue by smokedlinq** [Azure/azure-cli#17845]
## Describe the bug

**Command Name**
`az apim nv list`

**Errors:**
No keyvault named values are returned

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az apim nv list -g {} -n {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.22.1

Extensions:
azure-devops 0.18.0
log-analytics 0.2.2
resource-graph 1.1.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
@smokedlinq This is fixed
