### ISSUE TITLE
Support delete option for NICs and Disks for VMs in Azure CLI

### ISSUE THREAD

**Issue by szimmerMicrosoft** [Azure/azure-cli#17846]
**Resource Provider**
CRP 

**Description of Feature or Work Requested**
User experience:

![image](https://user-images.githubusercontent.com/11670642/115929839-4b680280-a43d-11eb-9e8a-93c74966fa9b.png)

In text:

az vm create
-n MyVm
-g MyResourceGroup
--public-ip-address-dns-name MyUniqueDnsName
--image ubuntults
--size Standard_DS2_v2
--generate-ssh-keys
--data-disk-sizes-gb 10 20
--data-disk-delete-option 0=Detach 1=Delete /*Use a singular value to apply on all data disks, or use <Name>=<Value> to configure the delete behavior for individual disks
--os-disk-delete-option Delete
--nic-delete-option <Name>=<Value> /*Use a singular value to apply on all nics, or use <Name>=<Value> to configure the delete behavior for individual NICs

The new switches do the following
--nic-delete-behavior configures the deleteOption field for the NIC created for the VM
vm.properties.networkProfile.networkInterfaces[0].properties.deleteOption = "Delete"

--os-disk-delete-option Delete configures delete option for the OS Disk
cstorageProfile.dataDisks[*].osDisk= "Delete"

--data-disk-delete-option configures the delete option for data disks as specified
vm.properties.storageProfile.dataDisks[*].deleteOption = "Delete"

Swagger PR containing the deleteOption for VM NICs: https://github.com/Azure/azure-rest-api-specs/pull/13449

Swagger PR for disk deleteOption: https://github.com/Azure/azure-rest-api-specs/pull/13657

**Minimum API Version Required**
2021-03-01

**Swagger Link**

**Target Date**
5/25

**Comment by yungezz** [comment]
hi @szimmerMicrosoft there's no concrete ETA on when 2021-03-01 Swagger will be avaiable, there's high risk to catch 5/25 timeline. Based on info I got from Adam, Swagger will be ready for review at week of 4/26. With it, I dont' think features in 2021-03-01 could catch 5/25 release.

**Comment by Juliehzl** [comment]
Hi @szimmerMicrosoft, it is only supported for `vm create` not including `vmss create`, right?

**Comment by szimmerMicrosoft** [comment]
disk deleteOption is currently only supported for vm, not for VMSS.

We do have the ability to configure it for VMSS on NICs. We could support that now, or we could wait for deleteOption support for both disks and NICs to be possible on VMSS.

Setting deleteOption on VMSS flex for NICs is probably a small minority choice so not a hard requirement now.

**Comment by Juliehzl** [comment]
Hi @szimmerMicrosoft  One more thing to clarify is that for key=value format, the key is name or resource ID to use?

**Comment by szimmerMicrosoft** [comment]
The only option for NICs parameter looking here https://github.com/Azure/azure-cli/blob/1ca212af5ec9e41847a628d1df27e87e411b7345/src/azure-cli/azure/cli/command_modules/vm/custom.py#L873

Appears to be resourceIds.

vmName is used as the singular NIC name if nic_type == new.

Using the name as resourceId if the user provides resource id makes sense.

If the NIC being created is implicit I don't see any value in letting the user specify the VM name for the deleteOption, there is only one NIC, so let it just be deleteOption = X

**Comment by Juliehzl** [comment]
> The only option for NICs parameter looking here
> 
> https://github.com/Azure/azure-cli/blob/1ca212af5ec9e41847a628d1df27e87e411b7345/src/azure-cli/azure/cli/command_modules/vm/custom.py#L873
> 
> Appears to be resourceIds.
> 
> vmName is used as the singular NIC name if nic_type == new.
> 
> Using the name as resourceId if the user provides resource id makes sense.
> 
> If the NIC being created is implicit I don't see any value in letting the user specify the VM name for the deleteOption, there is only one NIC, so let it just be deleteOption = X
> 
> Let me know if I am misunderstanding how the create command works.

We also could use existing nics and set deleteOption for them. Both name and resource id format are allowed for existing nics. If users provide name, we will format it to resource id:
https://github.com/Azure/azure-cli/blob/bc8fca8df0b9087e44381def0afc8fee7768083e/src/azure-cli/azure/cli/command_modules/vm/_validators.py#L960-L964

**Comment by szimmerMicrosoft** [comment]
Oh great,so identifying those via name makes sense.

However the user specifies the NICs, using that as the key I think is sensible.
