### ISSUE TITLE
az acr import needs --no-wait option

### ISSUE THREAD

**Issue by rajsell** [Azure/azure-cli#17851]
az acr import being an async operation, the behavior of the az acr import command is working mimicking it to be a sync operation, it would be great if you can provide the --no-wait option so that if required customers can use that option to wait until the import operation completes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/acr.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/acr.yml)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by yugangw-msft** [comment]
will consider for v-next

**Comment by iamjasonp** [comment]
To @CarolineNB. Thanks!

**Comment by stan-sz** [comment]
Seems to be related to #1528
