### ISSUE TITLE
az storage blob upload: make --name optional

### ISSUE THREAD

**Issue by orloffm** [Azure/azure-cli#17858]
**Describe the bug**
`az storage blob upload` requires an explicit `--name` and cannot infer it from the file name (`-f`) by default.
https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az_storage_blob_upload

**To Reproduce**
Use `az storage blob upload -f {} -c {}`, it requires `-n {}` to be specified.

**Expected behavior**
Work without `-n {}` specified.

**Environment summary**
N/A

**Additional context**
"Upload blob" dialog on the Azure Portal doesn't require an explicit name. You only pick the file, and that's it.

**Comment by yonzhan** [comment]
storage
