### ISSUE TITLE
Webapp:az webapp config access-restriction add is not idempotent when working with Vnet restrictions

### ISSUE THREAD

**Issue by kabukimurder** [Azure/azure-cli#17850]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
The fixes for webapp config access-restriction implemented in issue #13035 only works when specifying --ip-address. When working with Vnet access-restriction this parameter is not used and duplicate entries will occur since the command is not idempotent.

Specifying subnet Id does not help.

**To Reproduce**
az webapp config access-restriction add --resource-group $ResourceGroupName  `
    --name $AppName  `
    --rule-name "My rule" `
    --action Allow  `
    --vnet-resource-group $VnetRg `
    --vnet-name $VnetName `
    --subnet $SubnetName `
    --priority 1 `
    --description "My description" `

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
Looking in to it.

**Comment by Kotasudhakarreddy** [comment]
Hey @madsd could you please take a look in to this.

**Comment by madsd** [comment]
Thanks @Kotasudhakarreddy, I added PR to fix that: https://github.com/Azure/azure-cli/pull/18024

**Comment by Kotasudhakarreddy** [comment]
Thanks @madsd
