### ISSUE TITLE
Query parameter does not support dash in resource name

### ISSUE THREAD

**Issue by michaelelleby** [Azure/azure-cli#17866]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Filtering by Key Vault with a dash in the name results in the error `argument --query: invalid jmespath_type value: '[?name==my-vault]'` whereas filtering by values without a dash work as expected.

**To Reproduce**

`az keyvault list --query [?name=='my-vault']`

**Expected behavior**

A list containing 1 key vault named "my-vault".

**Environment summary**

```
az --version
azure-cli                         2.22.1

core                              2.22.1
telemetry                          1.0.6

Extensions:
log-analytics-solution               0.1.1
azure-devops                      0.18.0
front-door                        1.0.13
aks-preview                        0.5.4
resource-graph                     1.1.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/y3sy/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Apr 19 2021, 07:28:54) 
[GCC 9.3.0]

Legal docs and information: aka.ms/AzureCliLegal

`
Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy```

**Additional context**
<!--- Add any other context about the problem here. --->

**Comment by yungezz** [comment]
add @houk-ms to have a look

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed. Please update your Az CLI [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
az keyvault list --query [?name=='issue-17866']
[
  {
    "id": "<resourceid>",
    "location": "eastus",
    "name": "issue-17866",
    "resourceGroup": "Issue17866",
    "tags": {},
    "type": "Microsoft.KeyVault/vaults"
  }
]
