### ISSUE TITLE
"az functionapp config ssl show" filter on function app

### ISSUE THREAD

**Issue by wonderplayer** [Azure/azure-cli#17875]
I have a question about [this](https://docs.microsoft.com/en-us/cli/azure/functionapp/config/ssl?view=azure-cli-latest#az_functionapp_config_ssl_show) cmdlet. It states, that I can show function app certificates.
How do I filter on specific function app? I have executed [import](https://docs.microsoft.com/en-us/cli/azure/functionapp/config/ssl?view=azure-cli-latest#az_functionapp_config_ssl_import) on one function app and next time I try to import the same certificate I get the error that certificate already is imported, which is fine.
For that reason, I'd like to check, before importing the certificate, if the function app already has it.
Can I achieve that with Azure CLI?
Thank you!

**Comment by yonzhan** [comment]
functionapp

**Comment by wonderplayer** [comment]
Have an update regarding error. Seems that I had an unexpected error, as now whenever I try to import an already existing certificate CLI doesn't throw any errors. Maybe I had a different certificate there? Don't know, but anyway, problem solved, but still answer to this question could be useful in the future :)

**Comment by apawast** [comment]
@panchagnula would you be able to help with this?

**Comment by panchagnula** [comment]
@wonderplayer certificates in general are never associated with a functioapp / webapp they are attached to a webspace or ASP+RG. hence there is no way to achieve this.
