### ISSUE TITLE
WebApp:az webapp config access-restriction add does not work correctly with subnets from a different subscription 

### ISSUE THREAD

**Issue by kabukimurder** [Azure/azure-cli#17876]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When using 'az webapp config access-restriction add' and providing a subnet resource id from different subscription, the CLI tries to retrieve the provided subnet resource from the same subscription as the webapp is located in and obviously fails to locate it. Restricting access to a resource in another subscription is a very important feature that works correctly when using ARM templates.

Specifying Vnet resource id and Vnet name does not help.

**To Reproduce**
$crossSubscriptionResource = "/subscriptions/[subscription1]/resourceGroups/myresourcegroup/providers/Microsoft.Network/virtualNetworks/myVnet/subnets/mySubnet"

 az webapp config access-restriction add --resource-group $ResourceGroupName  `
     --name $AppName  `
    --rule-name $ruleName `
     --action Allow  `
     --subnet $crossSubscriptionResource  `
     --priority 1

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
Will take a look in to it.

**Comment by Kotasudhakarreddy** [comment]
Hey @madsd could you please take a look in to this.

**Comment by madsd** [comment]
@kabukimurder can you try this again with the just released version (2.23). I added an improvement to this. It is actually not the access restriction that is the problem, but by default we will verify that the service endpoint is correctly configured on the subnet. That is not possible cross subscriptions, and thus the error. With the -i switch you can ignore the check. In 2.23 you should get a proper error message describing this. @Kotasudhakarreddy  fyi

**Comment by panchagnula** [comment]
Thanks @madsd , @kabukimurder please follow the suggestion provided. Thanks!
