### ISSUE TITLE
WebApp:The Java example of "az webapp create" is wrong

### ISSUE THREAD

**Issue by ciufudean** [Azure/azure-cli#17885]
The Java examples are confusing with respect to the runtime version, 8 and 11.
While indeed the string `java|11|Java SE|8` is returned by `az webapp list-runtimes`, I expect the text to describe what this means ... is it java 8 or 11?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_create)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to appropriate team

**Comment by Kotasudhakarreddy** [comment]
@calvinsID can you please respond here.

**Comment by calvinsID** [comment]
Hi @ciufudean, it is java 11, using java se 8 application server. I'll update the help doc

**Comment by panchagnula** [comment]
@calvinsID is this already updated?

**Comment by calvinsID** [comment]
now it is :)
