### ISSUE TITLE
[VM] Listing availability sets requires a resource group

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1788]
I noticed that the `az vm availability-set list` command requires a resource group, but I thought that all `list` commands supported doing subscription-wide queries. Could this param requirement be lifted, and treated as a way to filter the data if desired?

**Comment by yugangw-msft** [comment]
Not all services expose list-all, though some do 
@sauryadas, who can comment for how to proceed on this?

**Comment by sauryadas** [comment]
@yugangw-msft looks like list-all api is not available for availability-set?

**Comment by yugangw-msft** [comment]
@sauryadas, please ask CRP and update the issue with rough timeline.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
