### ISSUE TITLE
📦 Make RPM packaging easier for Azure CLI + SDK

### ISSUE THREAD

**Issue by major** [Azure/azure-cli#17909]
👋🏻 Hello there,

I work for Red Hat and I am researching how to package the Azure CLI and SDK components in RPMs for Red Hat Enterprise Linux (RHEL). The current RPM for Azure CLI depends on allowing pip to resolve dependencies during the build process. Unfortunately, packaging requirements for RHEL specify that all source must be downloaded before the RPM is built and no network access is allowed during the build itself.

I would like to package the Azure CLI and required SDK components for RHEL (and update the [Fedora SDK package](https://src.fedoraproject.org/rpms/python-azure-sdk) which still uses the older SDK bundle style), but I am running into several problems:

1. The CLI has strict python dependency mapping (using `==`) and this forces me to update the SDK and CLI packages in parallel.
2. Strict dependency mapping also causes challenges where the CLI may require `python-foo==1.2.3` but RHEL may have `python-foo-1.2.4`.
3. The SDK component dependencies release independently from the same repository, which means if I use sources from GitHub, I need to clone the SDK repo, checkout a tag, install from a subdirectory, checkout another tag, install from another subdirectory, and so on.
4. Using the source code from PyPi does make packaging a little easier, but the tests aren't included with PyPi tarballs and that prevents me from using the `%check` phase of the RPM build.

It's entirely possible that I've missed an easier method for packaging all of these components into RPMs. If you have suggestions for how to work around some of the issues noted above, I'd be grateful! 🤗

**Comment by yungezz** [comment]
thanks for reporting the issue. add @fengzhou-msft to help have a look

**Comment by major** [comment]
For what it's worth, I'm making progress on this in Fedora. I may have some feedback around a few things as I get the remainder of these packages done.

* https://copr.fedorainfracloud.org/coprs/mhayden/azure-cli/monitor/
* https://github.com/major/rpm-azure-cli
