### ISSUE TITLE
deb package releases are including __pycache__ dirs and substantially large

### ISSUE THREAD

**Issue by tmoschou** [Azure/azure-cli#17900]
**Describe the bug**
The `.deb` packages at https://packages.microsoft.com/repos/azure-cli/ are not pruned of `__pycache__` directories, contributing 350MB of the package size or 41%.

This makes container image layers which install `az` significantly larger than it needs to be. 

**To Reproduce**
Download and extract `.deb` package
```bash
wget 'https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.22.1-1~buster_all.deb'
ar -x azure-cli_2.22.1-1~buster_all.deb
mkdir root
tar -xJf data.tar.xz -C root/
```

Calculate size contributed by `__pycache__/` directories:
```
$ du -csh $(find root/ -name '__pycache__') | grep total
350M    total
```

Total size:
```
$ du -sh root/
859M    root
```

**Expected behavior**
```
$ find root/ -name '__pycache__' | wc -l
0
```

**Comment by tmoschou** [comment]
Relates to https://github.com/Azure/azure-cli/issues/7387, however that task looks like more broadly removing the included Python 3.6, where this is about removing the `__pycache__` and associated `*.pyc` files, which should be relatively simple to do. Also note that since #7387 was raised, the installer has grown from 347 MB to 859M. The bundled `__pycache__/` data is now bigger than the cli package was back in Sep 2018.

**Comment by tmoschou** [comment]
Just an update, looks like that though it not common to include `__pycache__/` in the `.deb` packages, it is common to generate these files in the post-install time, using `py3compile` - this is probably important as this needs to be done as root as the normal user would not have write access when running the CLI the first time. So may not help with reducing docker image sizes, but would help with the download of the package

**Comment by yonzhan** [comment]
@jiasli for awareness
