### ISSUE TITLE
Why is sql servers not supported? Can you add sql servers to the list please?

### ISSUE THREAD

**Issue by travelbug2020** [Azure/azure-cli#17911]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae400cf1-3b18-08af-d8c5-ed2b23184ed2
* Version Independent ID: 9803d7a9-cf98-be6d-4b10-a228d0fa2fc2
* Content: [az network private-link-resource](https://docs.microsoft.com/en-us/cli/azure/network/private-link-resource?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/network/private-link-resource.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/private-link-resource.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
I've create a PR for this. It will be released in next version.

**Comment by kairu-ms** [comment]
CLI is stilling missing following private links. @00Kai0, can you add tests for following providers.
- "Microsoft.Batch/batchAccounts"
- "Microsoft.Cache/redisEnterprise"
- "Microsoft.Media/mediaservices"
- "Microsoft.Migrate/assessmentProjects"
- "Microsoft.Migrate/migrateProjects"
- "Microsoft.OffAzure/masterSites"
- "Microsoft.Purview/accounts"
- "Microsoft.ServiceBus/namespaces"
- "Microsoft.StorageSync/storageSyncServices"
- "Microsoft.Web/hostingEnvironments"
