### ISSUE TITLE
az cosmosdb create does NOT support serverless

### ISSUE THREAD

**Issue by Farzad-Jalali** [Azure/azure-cli#17917]
I created a few serverless cosmos DB (MongoDB ) via the portal.
but now I'm trying to do them by  AZ CLI  ,  noticed it doesn't support it.

https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest

**Comment by yonzhan** [comment]
route to service team

**Comment by MehaKaushik** [comment]
Please use this command https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest#az_cosmosdb_create

In the --capabilities param provide the value EnableServerless. Please let me know if you face any issues.

**Comment by MehaKaushik** [comment]
Please re-open if you have any more questions.
