### ISSUE TITLE
az rest can't support Chinese body in body

### ISSUE THREAD

**Issue by hanhsia** [Azure/azure-cli#17922]
## Describe the bug
I use az rest to send a http request to LUIS service. It works fine if the body don't exist any Chinese character. But it fails when the body includes Chinese character.
**Command Name**
$url=https://chinaeast2.api.cognitive.azure.cn/luis/authoring/v3.0-preview/apps/{app id}/versions/{version}/closedlists
$headers="{\""Ocp-Apim-Subscription-Key\"": \""{luis Authoring Key}\"", \""Content-Type\"": \""application/json\""}"
az rest --method post --url $url --headers $headers --body "`@body.json" --resource "https://login.chinacloudapi.cn/" --debug

**Errors:**
```
'latin-1' codec can't encode characters in position 19-22: Body ('服务渠道') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
Traceback (most recent call last):
Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 659, in execute
cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
cli\core\commands\__init__.py, ln 715, in _run_job
...
http\client.py, ln 161, in _encode
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 19-22: Body ('服务渠道') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
Crate a LUIS application. Follow the doc https://westeurope.dev.cognitive.microsoft.com/docs/services/luis-programmatic-apis-v3-0-preview/operations/5890b47c39e2bb052c5b9c14 to genearate a http request

$url=https://chinaeast2.api.cognitive.azure.cn/luis/authoring/v3.0-preview/apps/{app id}/versions/{version}/closedlists
$headers="{\""Ocp-Apim-Subscription-Key\"": \""{luis Authoring Key}\"", \""Content-Type\"": \""application/json\""}"
az rest --method post --url $url --headers $headers --body "`@body.json" --resource "https://login.chinacloudapi.cn/" --debug

## Expected Behavior
the command succeed 

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1 *

Extensions:
application-insights 0.1.13
azure-iot 0.10.8

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Azure CLI does support Unicode. The error is caused by **PowerShell on non-UTF-8-enabled Windows**, as you are saving the result to a PowerShell variable. See https://github.com/microsoft/knack/pull/178 for details.

The latest Azure CLI 2.37.0 doesn't fail anymore. Instead, it discards the Unicode character and shows a warning:

```
> az rest -u https://graph.microsoft.com/v1.0/groups/b2b90a08-60d7-419e-bd06-7af6867d5c27
...
  "displayName": "测试组",

$name=az rest -u https://graph.microsoft.com/v1.0/groups/b2b90a08-60d7-419e-bd06-7af6867d5c27
WARNING: Unable to encode the output with cp1252 encoding. Unsupported characters are discarded.
```

**Comment by jiasli** [comment]
@bmaupin, if you have any question related to JSON body encoding, please create a new issue with required information, like what command you run, what is the expected output, etc.
