### ISSUE TITLE
Not able to use managed identities in a custom app service container

### ISSUE THREAD

**Issue by MallRoy** [Azure/azure-cli#17921]
I am running a web app with ubuntu docker images. I am trying to access the key vault using the system assigned identities in a container which is throwing the below error when I am trying to list web app or key vault
![image](https://user-images.githubusercontent.com/54269166/116511795-9d4cd480-a8e4-11eb-9ee1-2251ee7a0f7e.png)
I have added the permissions for the key vault, web app, and container registry.

**Comment by yungezz** [comment]
route to appropriate team
