### ISSUE TITLE
TypeError: __init__() got multiple values for keyword argument 'default_completer'

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1792]
On a new install, run `az` and you may see the above error.
This is due to an update today to argcomplet that wasn't backwards compatible - https://pypi.python.org/pypi/argcomplete.

**Comment by tbolsh** [comment]
Still see this error on Ubuntu 17.10 - what I suppose to do to get rid of it.

**Comment by derekbekoe** [comment]
What version of the CLI do you have installed and how?
I would suggest creating a new issue.
