### ISSUE TITLE
Azure-ci-core has a strict dependency on an very old PyJWT

### ISSUE THREAD

**Issue by sodul** [Azure/azure-cli#17939]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
The setup.py for azure-cli-core explicitly requires `PyJWT==1.7.1` while all the other azure packages are more relaxed with `>=1.0.0,<3`.

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/setup.py#L61

**To Reproduce**
`pip install azure-cli` alongside more recent packages that need `PyJWT>= 2.0`.

```
pip install azure-cli==2.22.1 PyJWT==2.1.0
... 
ERROR: Cannot install PyJWT==2.1.0 and azure-cli-core==2.22.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested PyJWT==2.1.0
    azure-cli-core 2.22.1 depends on PyJWT==1.7.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
```

**Expected behavior**
We should not have a version conflict with newer versions of PyJWT when installing the latest azure cli.

**Environment summary**
Installed with python 3.9.4 on linux and macOS. Pip 21.0.1.

**Additional context**
PyJWT 1.7.1  was released on 2018. This bug relates to #17598.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by fshabashev** [comment]
affects me as well
