### ISSUE TITLE
az storage fs list throws exception

### ISSUE THREAD

**Issue by zenfish** [Azure/azure-cli#17937]
Ran with these params -

az storage fs directory list --file-system tstdata --subscription 7f57be07-49f8-4202-bbc9-489304f26a1f --account-name sdpstorageacctgen2 --auth-mode login

I don't know if I really don't have permissions or if there's some other issue.  It'd be really helpful to have a way to just test if your permissions are valid with your CLI.  It'd be even more helpful if your storage commands all used the same authentication method and the dox were up to date ;(

## Describe the bug

**Command Name**
`az storage fs directory list`

**Errors:**
```
'dict' object has no attribute 'iter'
Traceback (most recent call last):
storagev2/filedatalake/v2020_02_10/_list_paths_helper.py, ln 50, in _get_next_cb
    return self._command(
v2020_02_10/_generated/operations/_file_system_operations.py, ln 442, in list_paths
    raise models.StorageErrorException(response, self._deserialize)
azure.multiapi.storagev2.filedatalake.v2020_02_10._generated.models._models_py3.StorageErrorException: (AuthorizationPermissionMismatch) This request is not authorized to perform this operation using this permission.
RequestId:aedb3177-801f-0088-180f-3eadde000000
Time:2021-04-30T22:25:33.5042228Z

...

filedatalake/v2020_02_10/_shared/response_handlers.py, ln 94, in process_storage_error
    for info in error_body.iter():
AttributeError: 'dict' object has no attribute 'iter'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage fs directory list --file-system {} --subscription {} --account-name {} --auth-mode {}`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.6
Installer: HOMEBREW

azure-cli 2.16.0 *

Extensions:
log-analytics-solution 0.1.1
datafactory 0.2.1
footprint 1.0.0
logic 0.1.3
azure-devops 0.18.0
resource-graph 1.1.0
storage-preview 0.7.1

```

**Comment by yonzhan** [comment]
Storage

**Comment by Juliehzl** [comment]
this is an issue for python SDK. Add @xiafu-msft  for help.

**Comment by RakeshMohanMSFT** [comment]
This issue is fixed. Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)

`az storage fs directory list --file-system myfilesystem --subscription b83c1ed3-c5b6-44fb-b5ba-2b83a074c23f --account-name issue3949storage --auth-mode login`
[]
