### ISSUE TITLE
az sql db list errors out

### ISSUE THREAD

**Issue by Karthik-BR21** [Azure/azure-cli#17942]
## Describe the bug

**Command Name**
`az sql db list`

**Errors:**
```
Can not perform requested operation on nested resource. Parent resource '[sql-karthik-dev]' not found.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sql db list`

## Environment Summary
```
Linux-4.15.0-1113-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.22.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.4

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Karthik-BR21** [comment]
Hi All, I was able to figure out the issue. Parent resource '[sql-karthik-dev]' not found.
I had to remove the square brackets during configuration and set server as 'sql-karthik-dev' which fixed the issue.
