### ISSUE TITLE
Webapp:.NET 6 support for Runtime Versions

### ISSUE THREAD

**Issue by calvinsID** [Azure/azure-cli#17950]
- Add support for .NET 6 in appservice
- Also update the hardcoded list of supported runtimes if needed, until we can consume the Runtime Stacks API (it is in 2020-12-01 SDK)

**Comment by calvinsID** [comment]
@btardif for tracking

**Comment by btardif** [comment]
@calvinsID see https://github.com/Azure/azure-functions-ux/pull/5909#event-4640366208 for reference
