### ISSUE TITLE
Is there a specification for interacting with the local CosmosDB emulator instance via the CLI?

### ISSUE THREAD

**Issue by CharlieDigital** [Azure/azure-cli#17957]
The documentation for the `az cosmosdb sql` commands does not seem to include any ability to interact with the local emulator instance.

The earlier command `az cosmosdb database` command permitted the use of the `--key` and `--url-connection` parameter to interact with the local emulator instance.  

Is there an equivalent set of parameters/configuration for interacting with local resources?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e20da33-a85d-abf3-88d4-2c9c6d5c1ad9
* Version Independent ID: ac38600c-6df4-5898-4bd7-fe880eb36819
* Content: [az cosmosdb sql container](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/sql/container?view=azure-cli-latest#az_cosmosdb_sql_container_create)
* Content Source: [latest/docs-ref-autogen/cosmosdb/sql/container.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cosmosdb/sql/container.yml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
cosmosdb

**Comment by CharlieDigital** [comment]
@MehaKaushik I understand your point, but consider that the `az storage queue create` operation still retains the `--connection-string` parameter which allows the usage of `"UseDevelopmentStorage=true"` to connect to the local emulator instance.

While I understand the desire for architectural purity, the CLI loses functionality by disconnecting it from emulator.

Is there no compromise available to the CLI team to support usage for local development?

**Comment by MehaKaushik** [comment]
I understand your point, this is very valuable feedback. I will work with my team to see how and when can we can support this. 
Unfortunately, I do not have any temporary workaround. 

For scripting against local emulator you can use our data plane sdk. You can use the sdk here: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-dotnet-standard

or the REST APIs defined here: https://docs.microsoft.com/en-us/rest/api/cosmos-db/
