### ISSUE TITLE
--service-tag argument is not available actually available in the cli

### ISSUE THREAD

**Issue by wdunn001** [Azure/azure-cli#17955]
as of 2.22.1 this argument does not exist in the latest cli 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c788e908-cee3-ae46-fac4-956d0606ad76
* Version Independent ID: 2ed69bfd-bb05-3d09-072e-00e505856fba
* Content: [az webapp config access-restriction](https://docs.microsoft.com/en-US/cli/azure/webapp/config/access-restriction?view=azure-cli-latest#az_webapp_config_access_restriction_add)
* Content Source: [latest/docs-ref-autogen/webapp/config/access-restriction.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config/access-restriction.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yungezz** [comment]
route to service team

**Comment by panchagnula** [comment]
This is available with the future release please upgrade & re-try. Thanks!
