### ISSUE TITLE
Add path accesses the "Rule Collection Group" and not the "Rule"

### ISSUE THREAD

**Issue by logbaseaofn** [Azure/azure-cli#17953]
I expect `az network firewall policy rule-collection-group collection rule add sourceAddresses <ip>` to add a source address to the rule, but I get a response:

```
Couldn't find 'sourceAddresses' in ''. Available options: ['etag', 'id', 'location', 'name', 'priority', 'provisioningState', 'ruleCollections', 'type']
``` 

I would expect this response from `az network firewall policy rule-collection-group update`

This is unexpected because these are the properties of the "Rule Collection Group", not the "Rule". How would I go about updating the singular rule?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51bc8847-2744-bb66-7b83-0518aa47536c
* Version Independent ID: c1c31748-e899-dd98-e418-e01ed781a14a
* Content: [az network firewall policy rule-collection-group collection rule](https://docs.microsoft.com/en-us/cli/azure/network/firewall/policy/rule-collection-group/collection/rule?view=azure-cli-latest#az_network_firewall_policy_rule_collection_group_collection_rule_update)
* Content Source: [latest/docs-ref-autogen/network/firewall/policy/rule-collection-group/collection/rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/firewall/policy/rule-collection-group/collection/rule.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by logbaseaofn** [comment]
I found out how to do it, still is confusing..

Solution right now: `az network firewall policy rule-collection-group collection rule add **"ruleCollections[name=rule-collection-name].rules[name=rule-name].sourceAddresses"** <ip>`

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
SourceAddresses modification is not supported by command level. CLI provide the support to update nested property by [JMESPath](http://jmespath.org/) query string. And "ruleCollections[name=rule-collection-name].rules[name=rule-name].sourceAddresses" is the property query string.
