### ISSUE TITLE
Support generating JWT tokens using cli

### ISSUE THREAD

**Issue by NissesSenap** [Azure/azure-cli#17964]
**Is your feature request related to a problem? Please describe.**

Trying to talk to Azure EventHub and due to reasons I need to have a JWT token. Today I can generate it by using the oauth2 endpoint as described in: https://docs.microsoft.com/en-us/rest/api/eventhub/get-azure-active-directory-token#use-postman-to-get-the-azure-ad-token.

I need to generate this JWT token from kubernetes and I would like to use aadpodidentity to be able to get this token.

**Describe the solution you'd like**

Through the CLI be able to get a JWT token even if `az login -i` is used.

Another option could be to have `azure eventhub` sub command to be able to give a JWT token.

**Describe alternatives you've considered**

Thought I could perform a `az login -i` but it doesn't create the accessTokens.json file, so I can't steel the JWT token from there.

I have also tried to use az rest.

```shell
az rest --headers 'Content-Type=application/x-www-form-urlencoded' --body '{"grant_type":"client_credentials","client_id":"my-client-id","client_secret":"so-much-secret","resource":"https://eventhubs.azure.net"}' -u https://login.microsoftonline.com/<tenant-id>/oauth2/token
```

But this gives me the following error:

`Get Token request returned http error: 400 and server response: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://login.microsoftonline.com was not found in the tenant named`

Even if it would have worked I still would have needed to get the client_secret from a azure key vault and it's nothing that I would like to do.

**Additional context**

I'm trying to build a fluxcd notification-controller integration with Azure EventHub that supports both SAS and JWT token.
Sadly I won't be able to add any other input variables than a JWT token, eventhub name and eventhub namespace.
And that is why I need to use a pure JWT token.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by NissesSenap** [comment]
There is a command for this and it works with `az login -i`

```
az account get-access-token
```

My bad, I will close this issue.
