### ISSUE TITLE
argument --name/-n: expected one argument

### ISSUE THREAD

**Issue by saumyasanghvi03** [Azure/azure-cli#17965]
argument --name/-n: expected one argument
me too getting this error - while creating web app plz help

_Originally posted by @saumyasanghvi03 in https://github.com/Azure/azure-cli/issues/10532#issuecomment-832720997_

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
az webapp create needs -n . please run az webapp create -h to check the basic arguments needed.
