### ISSUE TITLE
The directory is not empty when using az extension add --upgrade -n application-insights

### ISSUE THREAD

**Issue by MarkAtAgilliance** [Azure/azure-cli#17961]
## Describe the bug
The az extension add --upgrade -n application-insights (either using --system or not) does not complete.  It fails with directory not empty error

**Command Name**
`az extension add`

**Errors:**
```
[WinError 145] The directory is not empty: 'C:\\Users\\ASFALIS-SECADM\\AppData\\Local\\Temp\\2\\tmp_49n5szk\\azext_applicationinsights\\vendored_sdks\\applicationinsights'
Traceback (most recent call last):
Lib\site-packages\knack\cli.py, ln 231, in invoke
cli\core\commands\__init__.py, ln 657, in execute
cli\core\commands\__init__.py, ln 720, in _run_jobs_serially
cli\core\commands\__init__.py, ln 691, in _run_job
cli\core\commands\__init__.py, ln 328, in __call__
...
cli\core\extension\operations.py, ln 84, in _validate_whl_extension
shutil.py, ln 500, in rmtree
shutil.py, ln 390, in _rmtree_unsafe
shutil.py, ln 390, in _rmtree_unsafe
shutil.py, ln 390, in _rmtree_unsafe
shutil.py, ln 399, in _rmtree_unsafe
shutil.py, ln 397, in _rmtree_unsafe
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\ASFALIS-SECADM\\AppData\\Local\\Temp\\2\\tmp_49n5szk\\azext_applicationinsights\\vendored_sdks\\applicationinsights'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension add --upgrade -n application-insights --system`

## Expected Behavior
Adds or updates extension.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.22.1

```

**Comment by yungezz** [comment]
hi @MarkAtAgilliance could you pls run `az extension remove -n application-insights` to remove previously installed extension, then install it?

**Comment by MarkAtAgilliance** [comment]
Will do.  Then will run script twice.  Is there any enhanced debug you need turning on?
________________________________

**Comment by MarkAtAgilliance** [comment]
Hi, This is odd.  It sometimes works and sometimes does not.

Here is a trace of me adding/removing the extension.  I am running as admin.  

PS C:\Users\COMP-SECADM> $extensionAdded = az extension add --upgrade -n application-insights  --system
WARNING: Extension 'application-insights' 0.1.13 is already installed.
WARNING: It will be updated if available.
WARNING: No updates available for 'application-insights'. Use --debug for more information.
PS C:\Users\COMP-SECADM> $extensionAdded = az extension add --upgrade -n application-insights  --system
WARNING: Extension 'application-insights' 0.1.13 is already installed.
WARNING: It will be updated if available.
WARNING: No updates available for 'application-insights'. Use --debug for more information.
PS C:\Users\COMP-SECADM> az extension remove -n application-insights
PS C:\Users\COMP-SECADM> $extensionAdded = az extension add --upgrade -n application-insights
WARNING: The installed extension 'application-insights' is in preview.
PS C:\Users\COMP-SECADM> az extension remove -n application-insights
PS C:\Users\COMP-SECADM> $extensionAdded = az extension add --upgrade -n application-insights
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: [WinError 145] The directory is not empty: 'C:\\Users\\COMP-SECADM\\AppData\\Local\\Temp\\2\\tmppk38yybl\\azext_applicationinsights\\vendored_sdks\\applicationinsights'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 807, in default_command_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/extension/custom.py", line 18, in add_extension_cmd
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 340, in add_extension
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 147, in _add_whl_ext
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 84, in _validate_whl_extension
  File "shutil.py", line 500, in rmtree
  File "shutil.py", line 390, in _rmtree_unsafe
  File "shutil.py", line 390, in _rmtree_unsafe
  File "shutil.py", line 390, in _rmtree_unsafe
  File "shutil.py", line 399, in _rmtree_unsafe
  File "shutil.py", line 397, in _rmtree_unsafe
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\COMP-SECADM\\AppData\\Local\\Temp\\2\\tmppk38yybl\\azext_applicationinsights\\vendored_sdks\\applicationinsights'
To open an issue, please run: 'az feedback'

**Comment by MarkAtAgilliance** [comment]
So, a successful script run occurs.  Then another run is run and the error occurs.

It is this directory that is being highlighted in the error as not being empty.:

**C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\applicationinsights**


The full list of directories right after the error is as follows.


 Volume in drive C is Windows
 Volume Serial Number is 0856-6EF2

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5

05/11/2021  03:12 AM    <DIR>          .
05/11/2021  03:12 AM    <DIR>          ..
05/11/2021  01:27 AM    <DIR>          azext_applicationinsights
05/11/2021  03:12 AM                 0 tmp.txt
               1 File(s)              0 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM    <DIR>          vendored_sdks
05/11/2021  01:27 AM             2,178 _client_factory.py
05/11/2021  01:27 AM            15,376 _help.py
05/11/2021  01:27 AM            11,192 _params.py
05/11/2021  01:27 AM             2,527 _validators.py
05/11/2021  01:27 AM             1,484 __init__.py
               5 File(s)         32,757 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM    <DIR>          applicationinsights
05/11/2021  01:27 AM    <DIR>          mgmt_applicationinsights
05/11/2021  01:27 AM               410 __init__.py
               1 File(s)            410 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\applicationinsights

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
               0 File(s)              0 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM               646 models.py
05/11/2021  01:27 AM    <DIR>          v2015_05_01
05/11/2021  01:27 AM    <DIR>          v2017_10_01
05/11/2021  01:27 AM    <DIR>          v2018_05_01_preview
05/11/2021  01:27 AM    <DIR>          v2018_06_17_preview
05/11/2021  01:27 AM    <DIR>          v2019_09_01_preview
05/11/2021  01:27 AM    <DIR>          v2019_10_17_preview
05/11/2021  01:27 AM    <DIR>          v2020_02_02_preview
05/11/2021  01:27 AM    <DIR>          v2020_03_01_preview
05/11/2021  01:27 AM               493 version.py
05/11/2021  01:27 AM            25,130 _application_insights_management_client.py
05/11/2021  01:27 AM             1,915 _configuration.py
05/11/2021  01:27 AM               796 __init__.py
               5 File(s)         28,980 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2015_05_01

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM    <DIR>          models
05/11/2021  01:27 AM    <DIR>          operations
05/11/2021  01:27 AM               498 version.py
05/11/2021  01:27 AM             7,573 _application_insights_management_client.py
05/11/2021  01:27 AM             1,915 _configuration.py
05/11/2021  01:27 AM               796 __init__.py
               4 File(s)         10,782 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2015_05_01\models

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM             2,073 _application_insights_management_client_enums.py
05/11/2021  01:27 AM            78,070 _models.py
05/11/2021  01:27 AM            78,992 _models_py3.py
05/11/2021  01:27 AM             4,476 _paged_models.py
05/11/2021  01:27 AM             8,526 __init__.py
               5 File(s)        172,137 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2015_05_01\operations

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM            18,986 _analytics_items_operations.py
05/11/2021  01:27 AM            15,511 _annotations_operations.py
05/11/2021  01:27 AM            15,578 _api_keys_operations.py
05/11/2021  01:27 AM            28,899 _components_operations.py
05/11/2021  01:27 AM             4,708 _component_available_features_operations.py
05/11/2021  01:27 AM             8,930 _component_current_billing_features_operations.py
05/11/2021  01:27 AM             4,708 _component_feature_capabilities_operations.py
05/11/2021  01:27 AM             4,684 _component_quota_status_operations.py
05/11/2021  01:27 AM            19,603 _export_configurations_operations.py
05/11/2021  01:27 AM            20,879 _favorites_operations.py
05/11/2021  01:27 AM             3,935 _operations.py
05/11/2021  01:27 AM            12,582 _proactive_detection_configurations_operations.py
05/11/2021  01:27 AM            24,290 _web_tests_operations.py
05/11/2021  01:27 AM             5,165 _web_test_locations_operations.py
05/11/2021  01:27 AM            18,785 _workbooks_operations.py
05/11/2021  01:27 AM            23,007 _work_item_configurations_operations.py
05/11/2021  01:27 AM             2,176 __init__.py
              17 File(s)        232,426 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2017_10_01

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM    <DIR>          models
05/11/2021  01:27 AM    <DIR>          operations
05/11/2021  01:27 AM               498 version.py
05/11/2021  01:27 AM             3,754 _application_insights_management_client.py
05/11/2021  01:27 AM             1,915 _configuration.py
05/11/2021  01:27 AM               796 __init__.py
               4 File(s)          6,963 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2017_10_01\models

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM             6,933 _models.py
05/11/2021  01:27 AM             7,058 _models_py3.py
05/11/2021  01:27 AM               943 __init__.py
               3 File(s)         14,934 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2017_10_01\operations

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM            12,351 _component_current_pricing_plan_operations.py
05/11/2021  01:27 AM             4,000 _ea_subscription_list_migration_date_operations.py
05/11/2021  01:27 AM             3,676 _ea_subscription_migrate_to_new_pricing_model_operations.py
05/11/2021  01:27 AM             3,695 _ea_subscription_rollback_to_legacy_pricing_model_operations.py
05/11/2021  01:27 AM             1,142 __init__.py
               5 File(s)         24,864 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2018_05_01_preview

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM    <DIR>          models
05/11/2021  01:27 AM    <DIR>          operations
05/11/2021  01:27 AM               506 version.py
05/11/2021  01:27 AM             2,571 _application_insights_management_client.py
05/11/2021  01:27 AM             1,915 _configuration.py
05/11/2021  01:27 AM               796 __init__.py
               4 File(s)          5,788 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2018_05_01_preview\models

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM             1,005 _application_insights_management_client_enums.py
05/11/2021  01:27 AM            20,713 _models.py
05/11/2021  01:27 AM            20,976 _models_py3.py
05/11/2021  01:27 AM             1,052 _paged_models.py
05/11/2021  01:27 AM             2,499 __init__.py
               5 File(s)         46,245 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2018_05_01_preview\operations

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM            29,267 _components_operations.py
05/11/2021  01:27 AM            12,630 _proactive_detection_configurations_operations.py
05/11/2021  01:27 AM               727 __init__.py
               3 File(s)         42,624 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2018_06_17_preview

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM    <DIR>          models
05/11/2021  01:27 AM    <DIR>          operations
05/11/2021  01:27 AM               506 version.py
05/11/2021  01:27 AM             2,084 _application_insights_management_client.py
05/11/2021  01:27 AM             1,915 _configuration.py
05/11/2021  01:27 AM               796 __init__.py
               4 File(s)          5,301 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2018_06_17_preview\models

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM               708 _application_insights_management_client_enums.py
05/11/2021  01:27 AM             9,557 _models.py
05/11/2021  01:27 AM             9,623 _models_py3.py
05/11/2021  01:27 AM               952 _paged_models.py
05/11/2021  01:27 AM             1,341 __init__.py
               5 File(s)         22,181 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2018_06_17_preview\operations

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM            19,778 _workbooks_operations.py
05/11/2021  01:27 AM               571 __init__.py
               2 File(s)         20,349 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2019_09_01_preview

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM    <DIR>          models
05/11/2021  01:27 AM    <DIR>          operations
05/11/2021  01:27 AM               506 version.py
05/11/2021  01:27 AM             2,393 _application_insights_management_client.py
05/11/2021  01:27 AM             1,915 _configuration.py
05/11/2021  01:27 AM               796 __init__.py
               4 File(s)          5,610 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2019_09_01_preview\models

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM            11,097 _models.py
05/11/2021  01:27 AM            11,184 _models_py3.py
05/11/2021  01:27 AM             1,551 _paged_models.py
05/11/2021  01:27 AM             1,702 __init__.py
               4 File(s)         25,534 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2019_09_01_preview\operations

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM            21,487 _queries_operations.py
05/11/2021  01:27 AM            21,129 _query_packs_operations.py
05/11/2021  01:27 AM               651 __init__.py
               3 File(s)         43,267 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2019_10_17_preview

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM    <DIR>          models
05/11/2021  01:27 AM    <DIR>          operations
05/11/2021  01:27 AM               506 version.py
05/11/2021  01:27 AM             2,143 _application_insights_management_client.py
05/11/2021  01:27 AM             1,915 _configuration.py
05/11/2021  01:27 AM               796 __init__.py
               4 File(s)          5,360 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2019_10_17_preview\models

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM            10,906 _models.py
05/11/2021  01:27 AM            10,948 _models_py3.py
05/11/2021  01:27 AM               992 _paged_models.py
05/11/2021  01:27 AM             1,603 __init__.py
               4 File(s)         24,449 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2019_10_17_preview\operations

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM            18,376 _workbook_templates_operations.py
05/11/2021  01:27 AM               596 __init__.py
               2 File(s)         18,972 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2020_02_02_preview

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM    <DIR>          models
05/11/2021  01:27 AM    <DIR>          operations
05/11/2021  01:27 AM               506 version.py
05/11/2021  01:27 AM             2,091 _application_insights_management_client.py
05/11/2021  01:27 AM             1,915 _configuration.py
05/11/2021  01:27 AM               796 __init__.py
               4 File(s)          5,308 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2020_02_02_preview\models

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM             1,005 _application_insights_management_client_enums.py
05/11/2021  01:27 AM            15,828 _models.py
05/11/2021  01:27 AM            15,996 _models_py3.py
05/11/2021  01:27 AM             1,052 _paged_models.py
05/11/2021  01:27 AM             1,942 __init__.py
               5 File(s)         35,823 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2020_02_02_preview\operations

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM            29,003 _components_operations.py
05/11/2021  01:27 AM               574 __init__.py
               2 File(s)         29,577 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2020_03_01_preview

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM    <DIR>          models
05/11/2021  01:27 AM    <DIR>          operations
05/11/2021  01:27 AM               506 version.py
05/11/2021  01:27 AM             2,240 _application_insights_management_client.py
05/11/2021  01:27 AM             1,915 _configuration.py
05/11/2021  01:27 AM               796 __init__.py
               4 File(s)          5,457 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2020_03_01_preview\models

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM             8,381 _models.py
05/11/2021  01:27 AM             8,458 _models_py3.py
05/11/2021  01:27 AM             1,450 __init__.py
               3 File(s)         18,289 bytes

 Directory of C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\tmpluwug4v5\azext_applicationinsights\vendored_sdks\mgmt_applicationinsights\v2020_03_01_preview\operations

05/11/2021  01:27 AM    <DIR>          .
05/11/2021  01:27 AM    <DIR>          ..
05/11/2021  01:27 AM            15,744 _component_linked_storage_accounts_operations.py
05/11/2021  01:27 AM               637 __init__.py
               2 File(s)         16,381 bytes

     Total Files Listed:
             114 File(s)        900,768 bytes
              86 Dir(s)  64,496,128,000 bytes free

**Comment by MarkAtAgilliance** [comment]
this is getting tedious.  I think it will be quicker to move off CLI and back to azure powershell cmdlets until it can stabilize this extension.

**Comment by jiasli** [comment]
According to the callstack, CLI fails at:

https://github.com/Azure/azure-cli/blob/3d14ca21e648f4fc0124132a43156a85a50251cd/src/azure-cli-core/azure/cli/core/extension/operations.py#L84

Per the document of [`shutil.rmtree`](https://docs.python.org/3/library/shutil.html#shutil.rmtree), it is designed to delete non-empty folders. 

The error `OSError: [WinError 145] The directory is not empty` is raised by `os.rmdir` which is internally called by `shutil.rmtree`.

I found similar issues reported to Python:

- https://bugs.python.org/issue33240
- https://bugs.python.org/issue40143

Things to check:

1. It is possible `C:\\Users\\ASFALIS-SECADM\\AppData\\Local\\Temp\\2\\tmp_49n5szk\\azext_applicationinsights\\vendored_sdks\\applicationinsights` becomes non-empty when `shutil.rmtree` calls  `os.rmdir`. Are multiple CLI commands like `az extension add --upgrade -n application-insights` run in parallels?
2. Do you have File Explorer opened at `C:\\Users\\ASFALIS-SECADM\\AppData\\Local\\Temp\\2\\tmp_49n5szk\\azext_applicationinsights\\vendored_sdks\\applicationinsights`?
2. Is any antivirus software installed?

I am also thinking perhaps we can specify `ignore_errors=False` so that the deletion will not fail for race condition like this.

**Comment by MarkAtAgilliance** [comment]
Hi, Thanks for the update.  
The scernario is that the this is a standard windows server VM in Azure being used as a self-hosted build server for Azure DevOps.  It has the devops agent, visual studio, AZ CLI and Powershell 7 installed.  The commands listed are those issued by the build script on Devops which are using a powershell task to call az CLI commands.

So in answer to your questions:

- standard Windows Server AV (windows defender)
- no explorer opened on this directory.  There are rarely anyone logging into the VM - only to do occasional software updates to VS, Az CLI, Powershell.
- no multiple commands - the agent is set up to process single jobs at a time.

Sometimes jobs are run one after the other, sometimes there are gaps of minutes or hours.  I wonder if there is an async process that is being cancelled with the end of the script and closure of the session?  Just a wild guess. 

I noticed that the temporary folder has many of those  ...\Local\Temp\tmpluwug4v5\... type folders but when the failure occurs (in the picture below, tmp_9h6urcg is an example), sub-folders are left as [above folder listing](https://github.com/Azure/azure-cli/issues/17961#issuecomment-837652508).    When it is successful, the folder remains with only one file - application_insights-0.1.13-py2.py3-none-any.whl.

![image](https://user-images.githubusercontent.com/35114634/118176398-36e8ab80-b3e6-11eb-841f-3baa4ac1154a.png)

**Comment by jiasli** [comment]
> I wonder if there is an async process that is being cancelled with the end of the script and closure of the session? Just a wild guess.

As far as I know, there is no such async process being called that interferes with `az`. `az` is simply a `python.exe` invocation on Windows.

`az extension add` not deleting the `application_insights-0.1.13-py2.py3-none-any.whl` temporary directory is a known issue (#18103). 

`az extension add` only deletes another temporary directory for extracted data:

https://github.com/Azure/azure-cli/blob/9fdde41d1cc0760cdd4e64c8be85c10a579e16bc/src/azure-cli-core/azure/cli/core/extension/operations.py#L78-L85

This is where the `rmtree` invocation is located and causes the problem. Let's retry the `rmtree` call and see how it goes (https://github.com/Azure/azure-cli/pull/18061).

**Comment by MarkAtAgilliance** [comment]
@jiasli  great - I will await M/S 189 can report back.  
Thanks, Mark.
