### ISSUE TITLE
intermittently ERROR: Failed to load token files

### ISSUE THREAD

**Issue by prohand** [Azure/azure-cli#17962]
Hello,

Randomly, I have my account which can no longer log in.
Here is the error:

`UNKNOWN: Command error: ERROR: Failed to load token files. If you have a repro, please log an issue at https://github.com/Azure/azure-cli/issues. At the same time, you can clean up by running 'az account clear' and then 'az login'. (Inner Error: Failed to parse /var/lib/centreon-engine/.azure/accessTokens.json with exception: -     Failed to parse JSON: [{"tokenType": "Bearer", "expiresIn": 3599, "expiresOn": "2021-05-03 13:29:34.371930", "resource": "https://management.core.windows.net/", "accessToken": "mytoken", "refreshToken": "mytoken", "oid": "myoid", "userId": "svc-centreon@elcia.com", "isMRRT": true, "_clientId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46", "_authority": "https://login.microsoftonline.com/common"}, {"tokenType": "Bearer", "expiresIn": 3599, "expiresOn": "2021-05-05 05:55:22.034319", "resource": "https://management.core.windows.net/", "accessToken": "mytoken", "refreshToken": "mytoken", "oid": "myoid", "userId": "svc-centreon@mydomaine.com", "isMRRT": true, "_clientId": "myclientid", "_authority": "https://login.microsoftonline.com/xxxxxx-d007-xxxx-a865-xxxx"}]08"}] - Error detail: Extra data: line 1 column 6613 (char 6612))
`

To correct it, I have to create an az account clear and az login.

Can you correct this bug ?

Thank you

**Comment by jiasli** [comment]
This is because Azure CLI doesn't support concurrent execution. Please see https://github.com/Azure/azure-cli/issues/9427#issuecomment-605786475 for a workaround.
