### ISSUE TITLE
Wrong sku-name

### ISSUE THREAD

**Issue by felipeafeltes** [Azure/azure-cli#17960]
Update the sku-name from **Standard-B1ms** to **Standard_B1ms** on sample:

Create a MySQL flexible server with parameters set.
az mysql flexible-server create --location northeurope --resource-group testGroup \
  --name testServer --admin-user username --admin-password password \
  --sku-name Standard-B1ms --tier Burstable --public-access 0.0.0.0 --storage-size 32 \
  --tags "key=value" --version 5.7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab572d66-e131-dcf9-8754-d8f8eea01cd5
* Version Independent ID: 75e64b41-cd3e-7bc1-a391-fad2b9a956da
* Content: [az mysql flexible-server](https://docs.microsoft.com/en-us/cli/azure/mysql/flexible-server?view=azure-cli-latest#az_mysql_flexible_server_create)
* Content Source: [latest/docs-ref-autogen/mysql/flexible-server.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/mysql/flexible-server.yml)
* Service: **mysql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by savjani** [comment]
Thanks @felipeafeltes for catching that. I have added the PR for the fix

**Comment by RakeshMohanMSFT** [comment]
@felipeafeltes This is resolved
