### ISSUE TITLE
az netappfiles volume create options need more information

### ISSUE THREAD

**Issue by omzevall** [Azure/azure-cli#17972]
The `az netappfiles volume create` options need some more information. Some examples:
* "--security-style : The security style of volume."
   * What are the valid options? (Applies to other args)
* For all arguments with "accepted values" listed, what value is the default if the arg is not specified?
* For all arguments without accepted and default values, are they just "true" when specified and "false" when not specified? For example, `--has-root-access`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 298ada99-369a-1c65-50ca-617931d26b7a
* Version Independent ID: 5fbd1cdf-e27f-8ffe-1c72-14f5d9e186f1
* Content: [az netappfiles volume](https://docs.microsoft.com/en-us/cli/azure/netappfiles/volume?view=azure-cli-latest#az_netappfiles_volume_create)
* Content Source: [latest/docs-ref-autogen/netappfiles/volume.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/netappfiles/volume.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by audunn** [comment]
Old issue was fixed a while ago
```
--security-style
The security style of volume, default unix, defaults to ntfs for dual protocol or CIFS protocol.

Accepted values: ntfs, unix
Default value: unix
```
