### ISSUE TITLE
Some required Parameters for az functionapp create are missing

### ISSUE THREAD

**Issue by jimbobbennett** [Azure/azure-cli#17995]
For the section on `az functionapp create`, the only required parameters listed are:

* `--name`
* `--resource-group`
* `--storage-account`

When you run this command with only these values set you get this error:

``` output
No functions version specified so defaulting to 2. In the future, specifying a version will be required. To create a 2.x function you would pass in the flag `--functions-version 2`
usage error: --plan NAME_OR_ID | --consumption-plan-location LOCATION
```

There should be a note on the default value of `--functions-version`, along with a note saying it will soon be required.

`--consumption-plan-location` should be added to the required parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f254bb-7dfd-417b-b08d-f2ac34247d99
* Version Independent ID: 9d22f523-579b-ea66-04ed-20f09c72bcbb
* Content: [az functionapp](https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest#az_functionapp_create)
* Content Source: [latest/docs-ref-autogen/functionapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/functionapp.yml)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by apawast** [comment]
@gzuber could you please take a look at this?

**Comment by panchagnula** [comment]
@jimbobbennett this is expected since the create command can be used for normal plan or consumption plan. i.e one of them is needed & not both, so in CLI we need to keep them optional & add a message on the right usage like you have seen.

"--plan NAME_OR_ID | --consumption-plan-location LOCATION"
