### ISSUE TITLE
VM Creation - SkuNotAvailable when creating VM in region

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#1800]
In the CLI, I tried creating a VM in 'West US' in my subscription but kept on getting a `ResourceDeploymentFailure` with code `SkuNotAvailable`.

```
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"SkuNotAvailable\",\r\n    \"message\": \"The requested tier for resource '/subscriptions/.../resourceGroups/commute-dev/providers/Microsoft.Compute/virtualMachines/commutedev1' is currently not available in location 'westus' for subscription '...'. Please try another tier or deploy to a different location.\"\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}
```

I tried many VM sizes and kept getting the same result.

I then tried in the portal and get the error message "Your subscription doesn't support virtual machine creation in West US."

<img width="573" alt="screen shot 2017-01-19 at 11 26 43 am" src="https://cloud.githubusercontent.com/assets/16448634/22123812/09b5ff10-de42-11e6-8bbe-e917340773cd.png">

The CLI doesn't show a list of supported regions and there doesn't appear to be a way to get this.

Can we use the same logic/API calls as the portal?

**Comment by yugangw-msft** [comment]
ARM team is working to give us a new API to query the regions

**Comment by yugangw-msft** [comment]
Will move to a particular sprint once we get more details from Compute RP team

**Comment by yugangw-msft** [comment]
CRP will provide API in mid-late Feb.

**Comment by berlic** [comment]
@yugangw-msft any news on new API? we struggle with this issue using python SDK with Ansible

**Comment by Santinell** [comment]
Hey guys, whats up? we are waiting for this feature

**Comment by yugangw-msft** [comment]
@sauryadas, this has to be done at compute RP first. I have forwarded an internal mail to you, could you please coordinate to get the API surface to the SDK?

**Comment by mastappl** [comment]
@yugangw-msft is there any information about new API?

**Comment by v-iam** [comment]
I encountered this as well and it took a while to figure out that the actual problem was not having permissions in the given location rather than specifying an unavailable VM size. The message in the portal is much clearer.

**Comment by yugangw-msft** [comment]
FYI, the `/skus` api is being finalized by Azure Compute team which will return the permission and restrictions information which CLI can leverage for better errors/suggestions.

**Comment by yugangw-msft** [comment]
Essentially each subscription has its own restrictions due to capacity or offer type, CLI will try to surface actionable messages with the assistance of the new API

**Comment by lmazuel** [comment]
@yugangw-msft this RestAPI will be in Swagger right? So update to the compute package?

**Comment by yugangw-msft** [comment]
@lmazuel , correct

**Comment by yugangw-msft** [comment]
`az vm list-skus` is in so people can cross check themselves. For more integrated experience, 2 things should be done:
1. on `vm create`, use the new api to cross check vm size and emit out a good message
2. on `vm availability-set create`, use the same api to default FD to the maximum number

**Comment by prashanthyv** [comment]
This is still a problem... I cannot specify which SKU and this is very frustrating. 

![image](https://user-images.githubusercontent.com/38299801/44543288-fc81d200-a6c3-11e8-8312-b735d3c209f6.png)

**Comment by prashanthyv** [comment]
When will this be fixed?

**Comment by prashanthyv** [comment]
Hi @tjprescott - Thanks. Yes I did. But the documentation doesn't tell the user after using the vm list-skus command what should be the next command to create a VM?

**Comment by tjprescott** [comment]
@yugangw-msft can you take this one after Ignite?

**Comment by yugangw-msft** [comment]
The flow, which we can emphasize in document, is you run “az vm list-skus -r virtualMachines -l <location>-otable” and ensure the size you are using in the “az vm create” command is in the list. If you don’t want to pick a different size, your other option is to make a phone call to the support team so to lift the restriction.

**Comment by tjprescott** [comment]
Per our discussion offline, this is a service issue with the list SKUs operation, which shows a size as being available in the chosen region but then rejecting it.

**Comment by yugangw-msft** [comment]
This issue has been largely mitigated with enhanced `az vm list-skus`, particularly in the help
```
    List all available vm sizes in the East US2 region which support availability zone with name
    like "standard_ds1...".
        az vm list-skus -l eastus2 --zone --size standard_ds1
```
And yes, once you find the available the sizes, you can use this size for `vm/vmss create`.
We have talked to compute team, and there are nothing else planned on this area. Hence i am closing this.
