### ISSUE TITLE
az keyvault -- vaults operations fail in AzureUSGovernment

### ISSUE THREAD

**Issue by glennmusa** [Azure/azure-cli#18006]
## Describe the bug

Unable to run `az keyvault create` or `az keyvault show` in AzureUSGovernment because the preview API `2021-04-01-preview` is not available.

Here's the output from `az provider show --namespace Microsoft.KeyVault --query "resourceTypes[?resourceType=='vaults']"`:

```json
[
  {
    "aliases": null,
    "apiProfiles": [
      {
        "apiVersion": "2016-10-01",
        "profileVersion": "2019-03-01-hybrid"
      }
    ],
    "apiVersions": [
      "2019-09-01",
      "2018-02-14-preview",
      "2018-02-14",
      "2016-10-01",
      "2015-06-01"
    ],
    "capabilities": "CrossResourceGroupResourceMove, CrossSubscriptionResourceMove, SupportsTags, SupportsLocation",
    "defaultApiVersion": "2019-09-01",
    "locationMappings": null,
    "locations": [
      "USGov Virginia",
      "USGov Iowa",
      "USDoD Central",
      "USDoD East",
      "USGov Texas",
      "USGov Arizona"
    ],
    "properties": null,
    "resourceType": "vaults"
  }
]
```

**Command Name**
`az keyvault create`

**Errors:**
```
(NoRegisteredProviderFound) No registered resource provider found for location 'usgovvirginia' and API version '2021-04-01-preview' for type 'vaults'. The supported api-versions are '2015-06-01, 2016-10-01, 2018-02-14-preview, 2018-02-14, 2019-09-01'. The supported locations are 'usgovvirginia, usgoviowa, usdodcentral, usdodeast, usgovtexas, usgovarizona'.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az cloud set -n AzureUSGovernment`
- `az keyvault create -n {} -g {} -l {}`

## Expected Behavior

Vault operations succeed.

## Environment Summary
```
Linux-4.15.0-1113-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.23.0

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yungezz** [comment]
Checking with Keyvault service team on feature parity support among different clouds. cc @fengzhou-msft  @houk-ms for awareness.

**Comment by glennmusa** [comment]
For others who stumble upon this issue, a workaround specific to these commands is setting the profile version:

```plaintext
az cloud set --name AzureUSGovernment --profile 2020-09-01-hybrid
```

**Comment by glennmusa** [comment]
Any updates @yungezz ?

**Comment by evelyn-ys** [comment]
CLI can hardly help with this until service ready in AzureUSGovernment😟 @amitbapat Could you help update the status here if service ready?

**Comment by amitbapat** [comment]
Key Vault resource type 'vault' has been available in Azure US Gov for several years now.

**Comment by evelyn-ys** [comment]
> Key Vault resource type 'vault' has been available in Azure US Gov for several years now.

Thanks for confirmation. According to the error response:
```
No registered resource provider found for location 'usgovvirginia' and API version '2021-04-01-preview' for type 'vaults'.
```
Does that mean 'vaults' has been available but not for API version '2021-04-01-preview'? Since the response also says that:
```
The supported api-versions are '2015-06-01, 2016-10-01, 2018-02-14-preview, 2018-02-14, 2019-09-01'.
```
Gentle ask for further confirmation and updates 😃 @amitbapat

**Comment by amitbapat** [comment]
Adding @Ashok ***@***.***> and @Chandan ***@***.***>

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amitbapat** [comment]
See incident Incident-241704977 Details - IcM (microsofticm.com)<https://portal.microsofticm.com/imp/v3/incidents/details/241704977/home>

The workaround is to override the default profile in latest CLI

az cloud set --name AzureUSGovernment--profile 2020-09-01-hybrid

**Comment by glennmusa** [comment]
Yes, that works as a workaround. The behavior is still broken out of the box and references a Preview API that is not available in any of the other clouds.

**Comment by glennmusa** [comment]
> ```
> The supported api-versions are '2015-06-01, 2016-10-01, 2018-02-14-preview, 2018-02-14, 2019-09-01'.
> ```
> 
> Gentle ask for further confirmation and updates 😃 @amitbapat

This is correct @evelyn-ys -- the API version the keyvault commands use out of the box is in Preview and is not supported in AzureUsGovernment.

**Comment by evelyn-ys** [comment]
According to the email thread, @adarce is working on adding 2021-04-01-preview to arm manifest and deploying to Fairfax!
If any updates, pls sync here🌺

**Comment by glennmusa** [comment]
`az keyvault` working in AzureUsGovernment on az v2.25 -- thanks for the help @adarce @amitbapat @yungeez @evelyn-ys
