### ISSUE TITLE
Could not set user.

### ISSUE THREAD

**Issue by eyesea69** [Azure/azure-cli#18010]
## Describe the bug

**Command Name**
`az webapp deployment user set`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment user set --user-name {}`

## Environment Summary
```
Linux-5.8.0-50-generic-x86_64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by panchagnula** [comment]
Please re-install using latest package & re-try, doesn't seem like an issue with the command.

**Comment by jiasli** [comment]
You probably have a built-in `azure-cli` 2.0.81 installed, which is a very old version. Please see the **Warning** section on page [Install the Azure CLI on Linux](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt).
