### ISSUE TITLE
[webapp] Simplifying the local Git deployment configuration

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1801]
After running the `az appservice web source-control config-local-git` command, I was expecting it to have created a new Git remote for my project, as opposed to requiring me to add it manually. Is this behavior available somewhere in the CLI? It's a simple gesture, but I feel like it would help simplify the getting started process for new users.  Could this command possibly have a new flag that enables/disables auto-adding the Git remote?

Additionally, is it obvious to users that they need to set a deployment password in order to actually push to the newly provisioned Git repository? After running `az appservice web source-control config-local-git`, it prints out the URL for the repo, which includes the user name, but if you immediately tried to push to it, you would be prompted for a password.

I wonder whether this command should either provide a hint to go run `az appservice web deployment user set`, or better yet, if it prompted you for the password automatically as part of the config step. 

The steps needed to setup a custom Git or Docker deployment seem simpler than using the local Git solution, and I wonder whether the CLI couldn't help smooth that over a little bit.

**Comment by lostintangent** [comment]
Actually, it would be cool if the `az appservice web source-control config-local-git` command effectively ran the following command behind the scenes after updating the web app back-end:

```shell
git remote add azure $(az appservice web deployment list-site-credentials --query scmUri -otsv -n <name> -g <group>)
```

That way, you could immediately run `git push azure master` without needing to configure a deployment user. If the dev wanted to use his user credentials, instead of the site credentials, it would be simple to update the generated git remote.

**Comment by panchagnula** [comment]
Thanks for the suggestion - not something we plan , but we will re-activate if we do consider it in the near future.
