### ISSUE TITLE
More parameters are required than just --id

### ISSUE THREAD

**Issue by petender** [Azure/azure-cli#18018]
Hi, I'm trying to run the below command, using the --id parameter only (mentioned as required). However, when running the task, it complains I also needed to provide the --organization as well as --project parameters.

Thanks, Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd63c4b-37f7-3641-8f15-0f5713ab71b4
* Version Independent ID: 39006efa-983d-d605-ca4f-95ffd91fbec4
* Content: [az devops service-endpoint](https://docs.microsoft.com/en-us/cli/azure/devops/service-endpoint?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/devops/service-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/devops/service-endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
@petender its updated

--org --organization
Azure DevOps organization URL. You can configure the default organization using az devops configure -d organization=ORG_URL. **Required if not configured as default or picked up via git config. Example: https://dev.azure.com/MyOrganizationName/.**

--project -p
Name or ID of the project. You can configure the default project using az devops configure -d project=NAME_OR_ID. **Required if not configured as default or picked up via git config.**
