### ISSUE TITLE
MemoryError while trying to deploy as zip file

### ISSUE THREAD

**Issue by AlesMicin** [Azure/azure-cli#18021]
## Describe the bug

When I'm trying to run following command, I receive MemoryError (traceback listed bellow). My guess is that the reason is file size - it's 1.06 GB.

Zip file which I'm trying to upload contains several webjobs. When I try to remove some of them and get file size below 1 GB, command run without errors. In one case I was even able to run the command with original file size, but now I'm not able to reproduce it.

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
Traceback (most recent call last):
cli\Lib\site-packages\knack\cli.py, ln 233, in invoke
azure\cli\core\commands\__init__.py, ln 660, in execute
azure\cli\core\commands\__init__.py, ln 723, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 716, in _run_job
artifacts\cli\Lib\site-packages\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 694, in _run_job
azure\cli\core\commands\__init__.py, ln 331, in __call__
site-packages\azure\cli\core\__init__.py, ln 811, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 395, in enable_zip_deploy_webapp
azure\cli\command_modules\appservice\custom.py, ln 422, in enable_zip_deploy
MemoryError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip --name {} --resource-group {} --src {}`

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.21.0

```

**Comment by yungezz** [comment]
route to appropriate team

**Comment by RakeshMohanMSFT** [comment]
@AlesMicin We sincerely apologies for the delay. Can you please upgrade to the latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and retry?
