### ISSUE TITLE
az graph query has changed format of the output

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli#18027]
**Describe the bug**

Scripts that rely on `az graph query` functionality are broken. Debugging the problem led us to an issue with result object of a query changing from `[ { record }, { record }...]` to `{ data: [ { record }, { record } ]}`.

This is a breaking change from resource-graph v1.x.

**To Reproduce**

Run the same query using resource-graph v1.x and resource-graph v2.x.

**Expected behavior**

There could've been a path to changing behavior that would make it obvious for consumers that the change was coming.

Our scripts use `extension add --upgrade` to keep up with extensions versions. Probably this feature should not upgrade between major versions.

Older (or new) version of resource-graph could've been updated to print a warning if # of resources fetched exceed the page size while using an "old" format, and could require new behavior to be "opt-in" by passing a flag as part of a query command line.

**Environment summary**

Azure Cloud Shell

```
{
  "azure-cli": "2.23.0",
  "azure-cli-core": "2.23.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5",
    "aks-preview": "0.5.10",
    "front-door": "1.0.14",
    "resource-graph": "2.0.0",
    "ssh": "0.1.5"
  }
}
```

**Comment by snaheth** [comment]
Hey @wasker I'm from the Azure Resource Graph team and wanted to apologize for this change in behavior that affected your scripts.

We'll be mindful of things like this moving forward and also hope the CLI team can work on adding the option to limit upgrades within the major versions.
