### ISSUE TITLE
az graph query --query "data.[0].subscriptionId" doesn't return subscription ID

### ISSUE THREAD

**Issue by lambohamp** [Azure/azure-cli#18038]
**Describe the bug**
`az graph query -q "where type =~ 'Microsoft.ContainerService/managedClusters' and name == '$aks_name'" --query "data.[0].subscriptionId"` returns the error:
```
argument --query: invalid jmespath_type value: 'data.[0].subscriptionId'
```

**To Reproduce**
Run `az graph query -q "where type =~ 'Microsoft.ContainerService/managedClusters' and name == '$aks_name'" --query "data.[0].subscriptionId"` replacing `$aks_name` with an existing AKS name.

**Expected behavior**
I tried copying `az graph query -q "where type =~ 'Microsoft.ContainerService/managedClusters' and name == '$aks_name'"` output to [JMESPath Tutorial](https://jmespath.org/tutorial.html) and performing the query - it works as expected.

<img width="850" alt="image" src="https://user-images.githubusercontent.com/36923213/117806633-4095d600-b263-11eb-9dda-66373c8d439d.png">

I did the same using [JMESPath-terminal](https://github.com/jmespath/jmespath.terminal) as suggested [here](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli#experiment-with-queries-interactively) - it works as well.

I expect `az graph query -q "where type =~ 'Microsoft.ContainerService/managedClusters' and name == '$aks_name'" --query "data.[0].subscriptionId"` to produce the same result.

Thanks.

**Comment by yonzhan** [comment]
route to service team

**Comment by fenwickt** [comment]
Please try removing the dot after 'data': --query "data[0].subscriptionId". Let us know whether it helps!

**Comment by lambohamp** [comment]
@fenwickt Thank you for your help, it works.
