### ISSUE TITLE
If resource group of application gateway and nic is not same then this cli command does not work. any other solution to handle case when resource group is different?

### ISSUE THREAD

**Issue by rajanchaubey** [Azure/azure-cli#18039]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14aebf6f-e419-ed83-e60e-00cd511d5eb8
* Version Independent ID: d75451d9-e39a-d239-b864-b0fab210e61a
* Content: [az network nic ip-config address-pool](https://docs.microsoft.com/en-us/cli/azure/network/nic/ip-config/address-pool?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/nic/ip-config/address-pool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/nic/ip-config/address-pool.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Please use the following commands

```
az network nic ip-config address-pool add -g {resource group name} -n {ipconfig name} --nic-name {nic name} --address-pool {address pool id of application gateway}
```
