### ISSUE TITLE
[App Service] Log tailing doesn't seem supported on Linux-based web apps

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1803]
The `az appservice web log tail` command is extremely valuable for viewing diagnostic logs for a web app (e.g. why did my app just give a 500 error?). However, it doesn't appear to work for web apps that are part of Linux-based plans. Am I missing something? Will this support be added soon and/or should the command provide a helpful error indicating that it doesn't support Linux VMs yet?

**Comment by yugangw-msft** [comment]
@lostintangent, last time i checked (last Nov) `log tail` works for non container based Linux web app. For container based web app, it is known not working 
//cc: @naziml who should have more update on this.

**Comment by lostintangent** [comment]
Interesting. I was trying it with a local git deployment setup and I wasn't seeing any of my app logs. The same setup works perfectly with a Windows plan, so maybe I'm doing something wrong.

**Comment by lostintangent** [comment]
I just tried deleting and re-creating my Linux web app and I'm either missing something or this doesn't work :) 

The following is what I did to test this out:

```shell
# Create the web app/plan, ensuring the specify you want a Linux worker
az appservice plan create -n <plan> -g <group> --is-linux
az appservice web create -n <app> -p <plan> -g <group>

# Setup the local Git deployment settings
az appservice web deployment user set --username <name> --password <password>
az appservice web source-control config-local-git -n <app> -g <group>
az appservice web config update -n <app> -g <group> --startup-file <file-name> --node-version 6.6.0

# Configure the local Git repo and push
git remote add azure <git-url>
git push azure master

az appservice web browse -n <app> -g <group>

az appservice web log tail -m <app> -g <group>
```

With the terminal window displaying the output of the `tail` command, I start to interact with the app (launched via the `browse` command) in order to generate logs, and I unfortunately don't see any. Am I doing anything wrong in the above?

**Comment by yugangw-msft** [comment]
It did work [last Nov](https://github.com/Azure/azure-cli/pull/1117#issuecomment-255502851) when we introduced linux webapp support. We are contacting webapp service team for more details

**Comment by yugangw-msft** [comment]
Not CLI issue.

**Comment by GuyHarwood** [comment]
is there a timeframe on this issue?  unable to debug errors from a NodeJS web application due to `az webapp log tail` outputting nothing

**Comment by derekbekoe** [comment]
It looks like this works for my container based Linux web app now.

**Comment by derekbekoe** [comment]
https://github.com/Azure/azure-cli/issues/4149

**Comment by yugangw-msft** [comment]
this works now
