### ISSUE TITLE
Managed HSM Recover

### ISSUE THREAD

**Issue by kim-soohwan** [Azure/azure-cli#18030]
**Resource Provider**
Key Vault
**Description of Feature or Work Requested**
The Recover command as described here: https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az_keyvault_recover needs to support managed HSM as well. Like in KeyVault CLI needs to send a put request to the RP with the CreateMode property set to Recover. 

**Minimum API Version Required**

2021-04-01-preview
**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/keyvault/resource-manager/Microsoft.KeyVault/preview/2021-04-01-preview
**Target Date**

As soon as reasonably possible as this is a missing feature that is a part of support for Managed HSM soft delete

**Comment by yonzhan** [comment]
KeyVault
