### ISSUE TITLE
[Style] Use double quote instead of single quote in docstring

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1804]
According to [PEP 257](https://www.python.org/dev/peps/pep-0257/)

>For consistency, always use """triple double quotes""" around docstrings. Use r"""raw triple double quotes""" if you use any backslashes in your docstrings. For Unicode docstrings, use u"""Unicode triple 
quoted strings""" .

We use single quote for docstring everywhere.

**Comment by yugangw-msft** [comment]
I don't believe we will ever update across, but i will remember this guideline :)

**Comment by troydai** [comment]
I guess I was the only one complained about it ...
