### ISSUE TITLE
az storage blob generate-sas Permission Errors

### ISSUE THREAD

**Issue by danielsollondon** [Azure/azure-cli#18041]
## Describe the bug
I keep receiving permissions errors when I have contributor rights at the sub level.

**Command Name**
`az storage blob generate-sas`

**Errors:**
```

You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.
                    

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob generate-sas --account-name {} --container-name {} --name {} --permissions {} --expiry {} --auth-mode {} --as-user --https-only --full-uri`

## Expected Behavior
There should not be perms errors.

## Environment Summary
```
macOS-10.14.6-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.23.0

Extensions:
dev-spaces 1.0.6
k8s-configuration 1.0.0
connectedk8s 1.1.3
k8s-extension 0.2.1
deploy-to-azure 0.2.0
resource-graph 1.1.0
customlocation 0.1.2
vm-repair 0.3.5
image-copy-extension 0.2.8

```

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
resolved with guidance in https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas#assign-permissions-with-rbac.

**Comment by danielsollondon** [comment]
This was resolved by granting the explicit permissions in that article to me, although I have contributor at a sub level, this should be referenced in the CLI and PS docs.
