### ISSUE TITLE
[App Service] Linux web apps don't appear to be configured correctly when using local git

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1806]
Using the CLI, I created a new Linux App Service plan, and a web app that is configured to use local git for deployments. After doing a Git push and setting the start file (which hopefully won't be necessary soon), I launched the site and got the following error:

<img width="346" alt="screen shot 2017-01-19 at 4 36 17 pm" src="https://cloud.githubusercontent.com/assets/116461/22131069/71bd7ea8-de65-11e6-9c29-614e4c9745b4.png">

After not being able to figure out what the issue was, I opened up the portal and noticed that there wasn't a runtime stack selected on the `Docker Container` tab (see image below). I explicitly set it to `Node.js 6.6.0`, at which point, everything worked great.

<img width="332" alt="screen shot 2017-01-19 at 4 36 03 pm" src="https://cloud.githubusercontent.com/assets/116461/22131094/8c5ca022-de65-11e6-8868-aab679a2f6ef.png">

That makes me wonder whether the `az appservice web create` command configures the app correctly when relying on a default runtime stack. I've not had any issues when deploying a custom Docker container, so maybe the `az appservice web config container update` command doesn't the necessary work to configure the app correctly? Oddly enough, when I ran the `az appservice web config appsettings show` command, I noticed that following output, so it seemed like it detected the use of Node after the Git push, but it didn't setup the runtime stack container right?

```
WEBSITE_NODE_DEFAULT_VERSION
------------------------------
6.9.1
```

**Comment by lostintangent** [comment]
As an update, I noticed that I can mitigate this issue from the CLI by running the following command: `az appservice web config update --node-version 6.6.0`. I suppose this is somewhat analogous to needing to run `az appservice web config container update` to set a custom container. However, the problem is that you can setup an app and push a Git deployment without realizing the app wasn't configured correctly. Whereas with the custom Docker container, you wouldn't expect it to know which image you want it to use.

Ideally, the web app would be able to auto-detect your runtime stack by inspecting the code upon deployment (doesn't Kudu do this already?).

**Comment by yugangw-msft** [comment]
Clarify, the node related appsettings doesn't impact container based linux web, they are 2 different flows, you either go with container, which you have coupe of appsetings to tweak for the image source; or we go with non-container model where you need to specify the the entry file and node/python/php versions
So check out the [sample flow](https://github.com/Azure/azure-cli/pull/1117#issuecomment-255502851)
Either way, we need to update the commands to get flow more clearer and less error-prone for users.

**Comment by lostintangent** [comment]
@yugangw-msft I fully understand the difference here, although the portal makes it clear that you're always using a container, it's just a matter if its a custom container or not. That said, my primary point here was that the experience of creating a web app and deploying via local git doesn't feel very optimized, since you can easily get into a position where you're deployed app doesn't work.

The portal doesn't allow you to create a Linux web app without specifying your runtime stack/custom container, whereas the CLI does.

**Comment by yugangw-msft** [comment]
>The portal doesn't allow you to create a Linux web app without specifying your runtime stack/custom container, whereas the CLI does.

Agreed.

**Comment by yugangw-msft** [comment]
delay a bit for the the same reason of #1337

**Comment by yugangw-msft** [comment]
The stack runtime version for a linux web is controlled by the site configuration `linux_fx_version`. CLI has done 2 improvement to help set up:
    1. On `webapp create`, you can set through `--runtime`
    2. On `webapp config container set`, when the arg of `--docker-custom-image-name` is used, CLI will also patch it.
With those, the original confusion will be greatly mitigated.
Note, the `--node-version` is irrelevant. It was added at service side but abandoned shortly, hence I am going to rewire it to `WEBSITE_NODE_DEFAULT_VERSION`

**Comment by yugangw-msft** [comment]
Submitted https://github.com/Azure/azure-cli/pull/3375 to remove the --node-version.
Closing this issue as we don't have other things to handle.
