### ISSUE TITLE
webapp: New Az CLI Version "2.23.0" is failing to create "az appservice domain" 

### ISSUE THREAD

**Issue by abdulrm** [Azure/azure-cli#18074]
> ###CLI version:

{   
**"azure-cli": "2.23.0",** 
"azure-cli-core": "2.23.0",   
"azure-cli-telemetry": "1.0.6",   
"extensions": 
{     
"ai-examples": "0.2.5",    
"ssh": "0.1.5"  
 }
 }

**Describe the bug**

The new CLI version "2.23.0" is failing to create new app service domain using the CLI command as described in this article: https://docs.microsoft.com/en-us/cli/azure/appservice/domain?view=azure-cli-latest#az_appservice_domain_create

**To Reproduce**

**Command:** 
    
az appservice domain create -g ResourceGroup --hostname mydomain.com --contact-info=@'/home/baldeep/contact_info.json' --accept-terms --subscription 703c19d3-******-*******-584ba7b4d31d

**Error:**
Command group 'appservice domain' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus The command failed with an unexpected error. Here is the traceback: check_availability() missing 1 required positional argument: 'identifier' Traceback (most recent call last):   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke     cmd_result = self.invocation.execute(args)   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute     raise ex   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially     results.append(self._run_job(expanded_arg, cmd_copy))   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job     result = cmd_copy(params)   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__     return self.handler(*args, **kwargs)   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler     return op(**command_args)   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/appservice_domains.py", line 50, in create_domain     hostname_availability = web_client.domains.check_availability(name=hostname) TypeError: check_availability() missing 1 required positional argument: 'identifier' To open an issue, please run: 'az feedback'
Azure CLI reference types
An explanation of reference types and status
aka.ms

**Expected behavior**

Suppose to create a new domain. I think the problem is only with the new  CLI Version "2.23.0". If we downgrade it to "2.22.0" the command works fine and we are able to create the new domain with the old version.

**Additional context**

on local machine we can downgrade to old version but on Azure portal, we cannot downgrade to old version. Please fix this bug with "2.23.0" version on portal and make it more user friendly.

**Comment by yonzhan** [comment]
route to service team
