### ISSUE TITLE
"az functionapp keys list" command does not accept --query parameter

### ISSUE THREAD

**Issue by real-oneill** [Azure/azure-cli#18070]
'--query-example' and '--query' parameters are being ignored when executing the 'az functionapp keys list' command. I tried wrapping in double quotes and using several JMESPath expressions but the output is always the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4246edfd-394e-4d61-360b-b95173159995
* Version Independent ID: e5365558-9b77-c72f-7b6d-f42e36a0a52c
* Content: [az functionapp keys](https://docs.microsoft.com/en-us/cli/azure/functionapp/keys?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/functionapp/keys.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/functionapp/keys.yml)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by gzuber** [comment]
Thanks for reporting this! I'll look into what we need to do to support query params

**Comment by kamperiadis** [comment]
Hi @real-oneill! Just wanted to check in and see if you are still experiencing this issue.
