### ISSUE TITLE
[LOC]Back-Translation "[実行]"→"run" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [Azure/azure-cli#18086]
ja-jp:"https://docs.microsoft.com/ja-jp/cli/azure/ml/datastore?view=azure-cli-latest"
![ml_run_j](https://user-images.githubusercontent.com/40815708/118215849-58609a80-b4ad-11eb-89a1-66025d0e82a5.png)

en-us:"https://docs.microsoft.com/en-us/cli/azure/ml/datastore?view=azure-cli-latest"
![ml_run_e](https://user-images.githubusercontent.com/40815708/118215843-55fe4080-b4ad-11eb-9ebb-02673bae5879.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27bfd14b-bddd-771f-1364-c52a991b75f0
* Version Independent ID: e0750d23-f2a0-7364-e6dc-34ffa51503d4
* Content: [az ml datastore](https://docs.microsoft.com/en-us/cli/azure/ml/datastore?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/datastore.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/datastore.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by ynpandey** [comment]
@hyoshioka0128 If I understand correctly, the translation of "run" heading on the page needs to be changed. Please respond if you want to address something else in this issue. Thank you.

**Comment by hyoshioka0128** [comment]
@ynpandey - Please correct the translation other than the "Run" heading (TOC.yml side) .
　データ ストア →　datastore
　環境 →　environment
　期待 →　experiment
Thanks.

**Comment by luigiw** [comment]
Azure CLI v2 is GAed and the active version AzureML supports. Please consider switching to v2. https://learn.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli?tabs=public
