### ISSUE TITLE
[Functions][Stacks] Support hidden stacks

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-cli#18099]
Related https://github.com/Azure/azure-cli/issues/17558

Please note that currently Powershell stack on Linux is marked as Hidden - https://github.com/Azure/azure-functions-ux/blob/42fba774382c6f72b76e65f428a36189f46abbdc/server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts#L40

This is a feature request to allow creating stacks marked as Hidden only if user requests by passing an explicit flag. We intend to mark stacks as Hidden while the backend changes are rolling out. Having support for hidden flag gives ability for the product team to test E2E while backend changes are rolling out.

cc: @gzuber @anatolib @stefanushinardi

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
@pragnagopa unfortunately there is no way to support this without exposing this to external customers as well.

**Comment by pragnagopa** [comment]
@panchagnula  - It is OK to expose this option to Customers who are willing flight features as they are rolling out. Please reactivate this issue.
