### ISSUE TITLE
Argument's short summary is cut short because specific string.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#1809]
Source: https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/_help.py#L104

The string `Possibile values include` will cause the short summary of an argument to be cut short. This is not a reliable mechanism:
1. Service SDK documentation does not guarantee to use the exact same string.
2. In some cases the following string is needed to be included.

**Comment by tjprescott** [comment]
The reason for this is because these parameters are often enums, and you will get help text like: "Possible values include: a, b, c. Possible values: a, b, c. Default: a." The first is from the help string. The second is because of the choice list (from the enum).

**Comment by troydai** [comment]
Yes. I do see that. My temporarily solution so far to to replace the first occurrence the string. However the search and replace strategy hard-coded in core is not a reliable mechanism.

**Comment by yugangw-msft** [comment]
@tjprescott, is this still an issue?

**Comment by tjprescott** [comment]
Well, if it is an issue, it is in Knack now, not the CLI. I'm inclined to feel it is fine as is so I will close this.
