### ISSUE TITLE
Bug with vm deployment 

### ISSUE THREAD

**Issue by MudassarAbdul** [Azure/azure-cli#18097]
## Describe the bug

**Command Name**
`az vm create`

**Errors:**
```
error retrieving default location: Resource group 'myResourceGroup' could not be found.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm create --resource-group {} --name {} --image {} --admin-username {} --ssh-key-values {}`

## Environment Summary
```
Linux-5.4.0-1046-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.23.0

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by james-flynn-ie** [comment]
Hi @MudassarAbdul , you may need to create the resource group first if it doesn't already exist.

**Comment by MudassarAbdul** [comment]
Thanks , I created it and was able to resolve the problem .

Thanks for your response ,please close the case as resolved.
