### ISSUE TITLE
Where is the source code for azure-cli-ml?

### ISSUE THREAD

**Issue by ashic** [Azure/azure-cli#18108]
**Resource Provider**
Azure Machine Learning

I'm trying to find the source code for the azure-cli-ml extension. I couldn't find the source code in either this repository, or azure-cli-extensions. I'm essentially looking for implementation logic for the following two commands:

```
az ml datastore attach-blob ...
az ml dataset register ...
```

Is there somewhere I can look for this?

**Comment by yonzhan** [comment]
route to service team

**Comment by lostmygithubaccount** [comment]
it is not open source and may not be publicly available. I believe you could probably find the source code in the Python package here: https://pypi.org/project/azureml-cli-common/

we are in the next week releasing the 2.0 CLI, which I'd recommend using instead - instructions can be found at https://github.com/Azure/azureml-previews if interested

**Comment by rajeshnair** [comment]
Any update on this if az ml cli sourcecode would be made open source.
I am trying to look for it and cannot find in the azure-cli or azure-cli-extensions repo.
It would be helpful for a lot of people to understand and (perhaps add functionality) if you open source it

**Comment by paulshealy1** [comment]
@rajeshnair we are planning to open source the v2 CLI, but we do not yet have a timeline to share.

**Comment by rajeshnair** [comment]
Can you at least point me to the REST/gRPC API which the CLI uses so that we can try to use that to automate our env creation and pipeline triggering . I am hoping the REST/gRPC API would have the way to detect the status in az ml environment

**Comment by luigiw** [comment]
Azure CLI v2 is GAed and the active version AzureML supports. Please consider switching to v2. https://learn.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli?tabs=public

**Comment by rajeshnair** [comment]
@luigiw 

This question is not about installing and setup of Azure CLI v2
The question is about source code of Azure CLI v2 and you are closing with the documentation on installing azure cli v2.

Please close only when you can provide the link to where we can find the source code of azure cli v2

@ashic , Please try reopening this issue

**Comment by BzSpi** [comment]
Please reopen since no response has been provided and the only link provided is now a 404. https://github.com/Azure/azureml-previews

**Comment by jikuja** [comment]
You can read the source code from `.azure/cliextensions/ml` although lot of code is being auto-generated. 

I checked for subcommands and looks like the extension has logic to convert yaml -> management API JSON and vice-versa. I'm not sure if there is any public documentation for schema conversions. To get full mapping from CLIv2 schema to ARM schema you need to consult extension directory's source code or HTTP request payloads.

Running CLI with --debug flag should display management.azure.com APIs calls. Few links:
* https://learn.microsoft.com/en-us/azure/machine-learning/how-to-manage-rest
* https://learn.microsoft.com/en-us/rest/api/azureml/2022-10-01/jobs
