### ISSUE TITLE
az network vhub get-effective-routes --resource-type RouteTable   to support "-o table" output

### ISSUE THREAD

**Issue by tiarnaigh** [Azure/azure-cli#18105]
**Is your feature request related to a problem? Please describe.**

When running below, json output only is returned by default, yet the "-o table" switch is still accepted as valid input and then returns no routes at all, which is quite misleading:

# Below returns expected effective routes in route table:
az network vhub get-effective-routes --resource-type RouteTable  --resource-id /sub......../defaultRouteTable -g test-rg  -n test-vhub

# Below on the other hand (-o table) returns a false list, showing nothing. This is misleading & incorrect:
az network vhub get-effective-routes --resource-type RouteTable --resource-id /sub...../defaultRouteTable -g test-rg -n test-vhub -o table
{- Finished ..
  "nextLink": null,
  "value": []
}

**Describe the solution you'd like**

When specifying "--output table" or "-o table" which is a common option for other az resource, a formatted table output should be presented showing the addressPrefixes & nextHop details.

**Describe alternatives you've considered**

Running same command, but accepting json output only............ Also running via Azure portal under vHub, which is very slow to return/render Difficult to read/interpret instantly

**Additional context**

**Comment by yonzhan** [comment]
network
