### ISSUE TITLE
Downgrade python version on Azure Agent Pool

### ISSUE THREAD

**Issue by cllyldrm** [Azure/azure-cli#18115]
**Resource Provider**
Azure CLI, Agent Pool

**Description of Feature or Work Requested**
With the latest Azure CLI release, looks like python version is upgraded from 3.6.8 to 3.8.9. The agent specification we use is vs2017-win2016. On the deployment pipeline, the agent was working properly and picking 3.6.8. Now It gets 3.8.9 which breaks our pipeline. We have been getting an error when we execute that command `az webapp config access-restriction `
We tried to downgrade Python version by `Use Python Version` task. It still gets the latest version. How can we downgrade it? 

![image](https://user-images.githubusercontent.com/5938044/118607257-a8df3d00-b7b8-11eb-91f0-ec647511eb23.png)

**Comment by yonzhan** [comment]
route to service team

**Comment by cllyldrm** [comment]
We figured out the problem, the ticket can be closed.
