### ISSUE TITLE
az storage account network-rule add throw error message: azure.core.exceptions.HttpResponseError: (InvalidValuesForRequestParameters) Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id. For more information, see - https://aka.ms/storagenetworkruleset

### ISSUE THREAD

**Issue by DavidChenLiang** [Azure/azure-cli#18112]
[Enter feedback here]
Hi team,
I tried to run the following **az storage account** command from cloud shell it throws errors:

david@Azure:~$ **az storage account network-rule add --resource-group linuxfoundation  --account-name linuxfoundationdiag  --vnet-name /subscriptions/c9a1c7ee-1044-4570-a441-b46b091a8c34/resourceGroups/PerfInsights/providers/Microsoft.Network/virtualNetworks/PerfInsights-vnet --subnet default --subscription c9a1c7ee-1044-4570-a441-b46b091a8c34
(InvalidValuesForRequestParameters) Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id. For more information, see - https://aka.ms/storagenetworkruleset**

I don't see virtualNetworkRules being required by the command itself, following are the detailed message running with --debug. Please advise is there any workaround to bypass the issue.

david@Azure:~$ **az storage account network-rule add --resource-group linuxfoundation  --account-name linuxfoundationdiag  --vnet-name /subscriptions/c9a1c7ee-1044-4570-a441-b46b091a8c34/resourceGroups/PerfInsights/providers/Microsoft.Network/virtualNetworks/PerfInsights-vnet --subnet default --subscription c9a1c7ee-1044-4570-a441-b46b091a8c34 --debug**
cli.knack.cli: Command arguments: ['storage', 'account', 'network-rule', 'add', '--resource-group', 'linuxfoundation', '--account-name', 'linuxfoundationdiag', '--vnet-name', '/subscriptions/c9a1c7ee-1044-4570-a441-b46b091a8c34/resourceGroups/PerfInsights/providers/Microsoft.Network/virtualNetworks/PerfInsights-vnet', '--subnet', 'default', '--subscription', 'c9a1c7ee-1044-4570-a441-b46b091a8c34', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fcc39581bf8>, <function OutputProducer.on_global_arguments at 0x7fcc394b6730>, <function CLIQuery.on_global_arguments at 0x7fcc394ce840>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.061        52       242
cli.azure.cli.core: Total (1)                 0.061        52       242
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.249         1         1  /opt/az/lib/python3.6/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.249         1         1
cli.azure.cli.core: Loaded 53 groups, 243 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage account network-rule add
cli.azure.cli.core: Command table: storage account network-rule add
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fcc38ff5ea0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/david/.azure/commands/2021-05-17.05-59-37.storage_account_network-rule_add.191.log'.
az_command_data_logger: command args: storage account network-rule add --resource-group {} --account-name {} --vnet-name {} --subnet {} --subscription {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fcc3901de18>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7fcc38f86ea0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fcc38f86f28>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fcc38f900d0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fcc394b67b8>, <function CLIQuery.handle_query_parameter at 0x7fcc394ce8c8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7fcc38f86e18>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fcc38f90048>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=StorageManagementClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 12113
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 12113
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/c9a1c7ee-1044-4570-a441-b46b091a8c34/resourceGroups/linuxfoundation/providers/Microsoft.Storage/storageAccounts/linuxfoundationdiag?api-version=2021-02-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '0f80881e-b6d5-11eb-898a-0a580af4172c'
cli.azure.cli.core.sdk.policies:     'CommandName': 'storage account network-rule add'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --account-name --vnet-name --subnet --subscription --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.23.0 (DEB) azsdk-python-azure-mgmt-storage/17.1.0 Python/3.6.10 (Linux-4.15.0-1113-azure-x86_64-with-debian-10.2) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/c9a1c7ee-1044-4570-a441-b46b091a8c34/resourceGroups/linuxfoundation/providers/Microsoft.Storage/storageAccounts/linuxfoundationdiag?api-version=2021-02-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '2dcc4993-0af1-4140-b684-c136e2639142'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11998'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'bd191207-a65d-42dd-97ba-2ba574e87ea0'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTUS:20210517T055937Z:bd191207-a65d-42dd-97ba-2ba574e87ea0'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 17 May 2021 05:59:37 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"sku":{"name":"Standard_LRS","tier":"Standard"},"kind":"Storage","id":"/subscriptions/c9a1c7ee-1044-4570-a441-b46b091a8c34/resourceGroups/linuxfoundation/providers/Microsoft.Storage/storageAccounts/linuxfoundationdiag","name":"linuxfoundationdiag","type":"Microsoft.Storage/storageAccounts","location":"eastus","tags":{},"properties":{"keyCreationTime":{"key1":"2021-04-09T02:21:08.3423443Z","key2":"2021-04-09T02:21:08.3423443Z"},"privateEndpointConnections":[],"networkAcls":{"bypass":"AzureServices","virtualNetworkRules":[],"ipRules":[],"defaultAction":"Allow"},"supportsHttpsTrafficOnly":true,"encryption":{"services":{"file":{"keyType":"Account","enabled":true,"lastEnabledTime":"2021-04-09T02:21:08.3423443Z"},"blob":{"keyType":"Account","enabled":true,"lastEnabledTime":"2021-04-09T02:21:08.3423443Z"}},"keySource":"Microsoft.Storage"},"provisioningState":"Succeeded","creationTime":"2021-04-09T02:21:08.2329509Z","primaryEndpoints":{"blob":"https://linuxfoundationdiag.blob.core.windows.net/","queue":"https://linuxfoundationdiag.queue.core.windows.net/","table":"https://linuxfoundationdiag.table.core.windows.net/","file":"https://linuxfoundationdiag.file.core.windows.net/"},"primaryLocation":"eastus","statusOfPrimary":"available"}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/c9a1c7ee-1044-4570-a441-b46b091a8c34/resourceGroups/linuxfoundation/providers/Microsoft.Storage/storageAccounts/linuxfoundationdiag?api-version=2021-02-01'
cli.azure.cli.core.sdk.policies: Request method: 'PATCH'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '441'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '0f80881e-b6d5-11eb-898a-0a580af4172c'
cli.azure.cli.core.sdk.policies:     'CommandName': 'storage account network-rule add'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --account-name --vnet-name --subnet --subscription --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.23.0 (DEB) azsdk-python-azure-mgmt-storage/17.1.0 Python/3.6.10 (Linux-4.15.0-1113-azure-x86_64-with-debian-10.2) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: **{"properties": {"networkAcls": {"bypass": "AzureServices", "virtualNetworkRules": [{"id": "/subscriptions/c9a1c7ee-1044-4570-a441-b46b091a8c34/resourceGroups/linuxfoundation/providers/Microsoft.Network/virtualNetworks//subscriptions/c9a1c7ee-1044-4570-a441-b46b091a8c34/resourceGroups/PerfInsights/providers/Microsoft.Network/virtualNetworks/PerfInsights-vnet/subnets/default", "action": "Allow"}], "ipRules": [], "defaultAction": "Allow"}}}**
urllib3.connectionpool: https://management.azure.com:443 "PATCH /subscriptions/c9a1c7ee-1044-4570-a441-b46b091a8c34/resourceGroups/linuxfoundation/providers/Microsoft.Storage/storageAccounts/linuxfoundationdiag?api-version=2021-02-01 HTTP/1.1" 400 213
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '213'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '2a0e79d2-f252-4399-9351-5277a0ca2855'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '32fc2f0f-d7d9-4215-acd6-d5bcebbc91be'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTUS:20210517T055937Z:32fc2f0f-d7d9-4215-acd6-d5bcebbc91be'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 17 May 2021 05:59:37 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: **{"error":{"code":"InvalidValuesForRequestParameters","message":"Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id. For more information, see - https://aka.ms/storagenetworkruleset"}}**
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/account.py", line 488, in add_network_rule
    return client.update(resource_group_name, account_name, params)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/storage/v2021_02_01/operations/_storage_accounts_operations.py", line 440, in update
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InvalidValuesForRequestParameters) Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id. For more information, see - https://aka.ms/storagenetworkruleset

cli.azure.cli.core.azclierror: (InvalidValuesForRequestParameters) Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id. For more information, see - https://aka.ms/storagenetworkruleset
az_command_data_logger: (InvalidValuesForRequestParameters) Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id. For more information, see - https://aka.ms/storagenetworkruleset
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fcc38ff4158>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.136 seconds (init: 0.168, invoke: 0.968)
telemetry.save: Save telemetry record of length 3328 in cache
telemetry.check: Negative: The /home/david/.azure/telemetry.txt was modified at 2021-05-17 05:57:37.593724, which in less than 600.000000 s

david@Azure:~$ az --version
azure-cli                         2.23.0

core                              2.23.0
telemetry                          1.0.6

Extensions:
ai-examples                        0.2.5
ssh                                0.1.5

Python location '/opt/az/bin/python3'
Extensions directory '/home/david/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.6/site-packages/azure-cli-extensions'

Python (Linux) 3.6.10 (default, Apr 29 2021, 12:09:29)
[GCC 8.3.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac52f120-deaa-0a12-3663-8bf51cbbd234
* Version Independent ID: b7e2694c-c7be-8d1f-da00-fdd8b60f327e
* Content: [az storage account network-rule](https://docs.microsoft.com/en-us/cli/azure/storage/account/network-rule?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/account/network-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/account/network-rule.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Juliehzl** [comment]
Hi @DavidChenLiang, if you want to use resource id, please change your command to ` az storage account network-rule add --resource-group linuxfoundation --account-name linuxfoundationdiag --subnet /subscriptions/c9a1c7ee-1044-4570-a441-b46b091a8c34/resourceGroups/PerfInsights/providers/Microsoft.Network/virtualNetworks/PerfInsights-vnet/subnets/default --subscription c9a1c7ee-1044-4570-a441-b46b091a8c34`.
If you want to use vnet name as input, please change your command to ` az storage account network-rule add --resource-group linuxfoundation --account-name linuxfoundationdiag --vnet-name PerfInsights-vnet --subnet default --subscription c9a1c7ee-1044-4570-a441-b46b091a8c34`.

**Comment by DavidChenLiang** [comment]
@Juliehzl, thank you, the command with --subnet only works, the command with --subnet and --vnet-name still failed with following error:
david@Azure:~$ az storage account network-rule add --resource-group linuxfoundation --account-name linuxfoundationdiag --vnet-name PerfInsights-vnet --subnet default --subscription c9a1c7ee-1044-4570-a441-b46b091a8c34
(NetworkAclsValidationFailure) Validation of network acls failure: ParentResourceNotFound:Can not perform requested operation on nested resource. Parent resource 'perfinsights-vnet' not found.

**Comment by Juliehzl** [comment]
> @Juliehzl, thank you, the command with --subnet only works, the command with --subnet and --vnet-name still failed with following error:
> david@Azure:~$ az storage account network-rule add --resource-group linuxfoundation --account-name linuxfoundationdiag --vnet-name PerfInsights-vnet --subnet default --subscription c9a1c7ee-1044-4570-a441-b46b091a8c34
> (NetworkAclsValidationFailure) Validation of network acls failure: ParentResourceNotFound:Can not perform requested operation on nested resource. Parent resource 'perfinsights-vnet' not found.

Oh. I just saw that your subnet and storage account are in different resource group. In this way, you only can use resource id in command.

**Comment by jklaus** [comment]
> subnet

I am trying this on the keyvault network-rule add with the subnet ID passed in for --subnet and it is acting as if it doesn't see it as a valid ID.  It throws the usage error.  If I then also provide the vnet name it throws a similar error to what they're seeing.
