### ISSUE TITLE
network rule section requires link to allow access from Selected Networks

### ISSUE THREAD

**Issue by dejan-shuki** [Azure/azure-cli#18128]
[Enter feedback here]
This section looks like it ti automaticcally generated.
When I just added network rule to the storage, it was added, but when I looked at it from the portal it was still not visible, becouse Allow Access from All Networks was still set. I had to change that manually. Only then my network rules were visible.
I am trying to figure out for more then half an hour how to set Allow Access from Selected Networks. You should add link to that to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac52f120-deaa-0a12-3663-8bf51cbbd234
* Version Independent ID: b7e2694c-c7be-8d1f-da00-fdd8b60f327e
* Content: [az storage account network-rule](https://docs.microsoft.com/en-us/cli/azure/storage/account/network-rule?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/account/network-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/account/network-rule.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi  @dejan-shuki, you could set default action for all networks using `az storage account update` with `--default-action` and `--bypass`. If you just want to allow selected networks, please use `az storage account network-ruls add`.
