### ISSUE TITLE
Add access-restriction fails for subnet under different subscription to web app

### ISSUE THREAD

**Issue by cowinr** [Azure/azure-cli#18122]
**Describe the bug**
When adding an access restriction to allow a subnet that resides under a different subscription than the web app, the command fails to find the subnet's resource group.

**To Reproduce**
Command that fails:
```bash
az webapp config access-restriction add `
  -g rg-webapps -n webapp-xfileupload `
  --priority 100 --rule-name 'devopsvnet2' `
  --vnet-resource-group rg-networking --subnet devops --vnet-name vn-shared
```
Fails with "(ResourceGroupNotFound) Resource group 'rg-networking' could not be found." when the VNet and it's resource group are in a different subscription to the web app.

**Expected behavior**
The access-restriction should be added to allow access to the `webapp-xfileupload` web app from the `sub-devops` subnet.

**Environment summary**
PowerShell on Windows with azure-cli 2.22.0.

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
@madsd this is already supported right if the resourceId is used instead of name?

**Comment by madsd** [comment]
@cowinr If the subnet is in a different subscription, you will need to use the resource id of the subnet. the --subnet parameter accepts the full resource id. Also when vNet is in a different subscription you will need to use the -i switch to ignore subnet check. In 2.23 version of cli, this is explicitly called out in an error message if forgotten.
@panchagnula fyi

**Comment by cowinr** [comment]
@madsd Thanks for the info. This works for me if I use the full subnet resource id and add the -i switch.
