### ISSUE TITLE
Command Syntax error with --generic-configurations

### ISSUE THREAD

**Issue by pranavkevadiya7** [Azure/azure-cli#18121]
The example syntax for generic-configurations is wrong in the documentation.

**Current:**
`az webapp config set -g MyResourceGroup -n MyUniqueApp --generic-configurations "{"alwaysOn": true}"
`
**Proposed:**
`az webapp config set -g MyResourceGroup -n MyUniqueApp --generic-configurations "{\"alwaysOn\": true}"
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e50d77a-f2fa-6d6e-0c57-2f434c12766f
* Version Independent ID: f9a98805-6e16-487a-03ce-237cb964f83c
* Content: [az webapp config](https://docs.microsoft.com/en-us/cli/azure/webapp/config?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
The example syntax is not correct the syntax depends based on the terminal you are using see this https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#using-quotation-marks-in-values
