### ISSUE TITLE
VMSS Flex Autoscale Public Preview

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#18129]
Resource Provider
Microsoft.Compute/virtualMachineScaleSets

Description of Feature or Work Requested
Virtual machines scale sets provide a logical grouping of platform-managed virtual machines. With scale sets, you create a virtual machine configuration model, automatically add or remove additional instances based on CPU or memory load, and automatically upgrade to the latest OS version. Traditionally, scale sets allow you to create virtual machines using a VM configuration model provided at time of scale set creation, and the scale set can only manage virtual machines that are implicitly created based on the configuration model.

With the scale set orchestration mode (preview), you can now choose whether the scale set should orchestrate virtual machines which are created explicitly outside of a scale set configuration model, or virtual machine instances created implicitly based on the configuration model. Scale set orchestration mode also helps you design your VM infrastructure for high availability by deploying these VMs in fault domains and Availability Zones.

Virtual machine scale sets will support 2 distinct orchestration modes: Uniform and Flexible.

Flexible – Virtual machines created outside of the scale set can be explicitly added to the scaleset. This is the new mode to be added. Virtual Machines created by VMSS scale out will be ARM tracked VM resources similar to Single VMs.
Uniform - Existing ScaleSet with implicit VM resources.

In this release, if customer specifies orchestrationMode=Flexible, the scale set is set to VMO mode.

Piping scenarios / how these cmdlets are used with existing cmdlets

Create a scale set in Flexible Orchestration mode. Create N VMs and add to scale set or Scale out with the Virtual Machine Profile defined at the ScaleSet model.

Sample of end-to-end usage
https://microsoft.sharepoint.com/:w:/t/vmssvmorchestrationmode/EUP571LsothBjgfM0mBbldUBgI2ZoZ9kNuRxXeM_NShZmA?e=3bUqZ5

Sample templates here - 
https://microsoft.sharepoint.com/teams/vmssvmorchestrationmode/_layouts/15/Doc.aspx?sourcedoc={1bd40af1-d2dd-45cd-8875-4cd6e28897f3}&action=edit&wd=target%28VMSS-Flex.one%7C4a204002-49fa-4c69-b4f9-9ab9736007ee%2FVMSS-Flex%20Dev-Test%7Cdca1da7e-643a-453b-b012-be8131ea0ff9%2F%29&wdorigin=703

Swagger Link
Compute 2021-03-01

**Comment by yonzhan** [comment]
@Juliehzl for awareness

**Comment by Juliehzl** [comment]
According to description in e-mail, the main update for public preview is as below:
Create VMO with VM Profile
- osProfile
- networkProfile
   Attach to lb
   Attach to appgw
- storageProfile
- extensionsProfile
- securityProfile
- ManagedIdentities
- ultradisks

**Comment by fitzgeraldsteele** [comment]
A few updates:

- VM sku
- instance count
- generate-ssh-key
- osProfile
- networkProfile
- public-ip-per-vm //should default to true for VMSS Flex
- lb sku MUST be standard
- Attach to lb
-- Can specify backend pool, but template should not generate InboundNatPools - does not apply to Flex
- Attach to appgw
- storageProfile
- extensionsProfile
- securityProfile
- Spot instance fields
-- billingProfile, eviction-policy, maxprice, priority
- licenseType
- ManagedIdentities
-- UserAssignedOnly
- ultradisks
- terminate-notificaton-time

These are not (yet) valid for VMSS Flex
upgradePolicy - omit this section in the template, or set to []
scaleInPolicy - omit or set to []
-overprovisioning //must be set to false
- health probe
- host group
- lb-nat-pool-name

**Comment by Juliehzl** [comment]
Hi  @fitzgeraldsteele , could you help me understand `[--computer-name-prefix] //vmss flex has different validation rules`? What is the difference?

**Comment by fitzgeraldsteele** [comment]
Opened a Teams chat with the dev team
