### ISSUE TITLE
Option to create origin Name is not available in CLI but is if you use Powershell

### ISSUE THREAD

**Issue by plynch66** [Azure/azure-cli#18138]
Hi,

I am using Azure CLI to create a CDN endpoint and I have noticed that there is no way to specify the origin name. However, the equivalent Powershell cmdlet 'New-AzCdnEndpoint' does offer the option to create the origin name.

It would be good if the CLI command mirrored the functionality offered in Powershell.

Thanks.

## Describe the bug

**Command Name**
`az cdn endpoint create`

**Errors:**
```
the following arguments are required: --resource-group/-g, --profile-name, --name/-n, --origin

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cdn endpoint create`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.23.0

Extensions:
aks-preview 0.5.11
application-insights 0.1.13
databricks 0.7.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by t-bzhan** [comment]
Ack and will fix it in future releases.

**Comment by Ptnan7** [comment]
@plynch66 Hi, for now if you want to set origin name, you can add the origin name at the end of parameter origin.
