### ISSUE TITLE
webapp:az webapp list-runtimes - Results in error. Ubuntu

### ISSUE THREAD

**Issue by SiebeDev** [Azure/azure-cli#18135]
## Describe the bug

**Command Name**
`az webapp list-runtimes`

**Errors:**
```
'bool' object has no attribute 'provider'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/appservice/custom.py, ln 704, in list_runtimes
    return [s['displayName'] for s in runtime_helper.stacks]
cli/command_modules/appservice/custom.py, ln 2159, in stacks
    self._load_stacks()
cli/command_modules/appservice/custom.py, ln 2180, in _load_stacks
    raw_stacks = self._client.provider.get_available_stacks(os_type_selected=os_type, raw=True)
AttributeError: 'bool' object has no attribute 'provider'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp list-runtimes`

## Environment Summary
```
Linux-5.8.0-53-generic-x86_64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
@calvinsID - Since you already make some work around it in the recent past, I am assigning it to you. Please take a look in to this.

**Comment by calvinsID** [comment]
hey @SiebeDev it seems like an old version of CLI - can you please try using a newer version?

**Comment by Kotasudhakarreddy** [comment]
@SiebeDev can you try with newer version of `CLI- 2.23.0` and confirm back.

**Comment by SiebeDev** [comment]
Hi, yes my bad indeed. I used the ubuntu native version.
`apt install ` instead of following the instructions on the docs website.
