### ISSUE TITLE
[ARM] template validation commands show unexpected error messages for invalid templates

### ISSUE THREAD

**Issue by shenglol** [Azure/azure-cli#18134]
## Describe the bug
ARM template validation commands shows unexpected error messages for invalid templates. This only happens on the dev branch db6c634faac95af7d3ebbeaf97d5245305e9dd91.

**Command Name**
`az deployment group/sub/mg/tenant validate`

**Errors:**
If a template contains any validation errors, the following error will be shown:

```
<bound method _RequestsTransportResponseBase.text of <RequestsTransportResponse: 400 Bad Request, Content-Type: application/json; charset=utf-8>>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Run `az deployment group validate` with any invalid ARM template. For example:

```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  },
  "functions": [],
  "resources": [
    {
      "type": "Microsoft.Storage/storageAccounts",
      "apiVersion": "2021-02-01",
      // reference not allowed here.
      "name": "[reference('abcede').something]",
      "location": "[resourceGroup().location]",
      "kind": "StorageV2",
      "sku": {
        "name": "Premium_LRS",
        "tier": "Premium"
      }
    }
  ]
}
```

## Expected Behavior
Print the template validation error message.

## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.8.10
Installer: PIP

azure-cli 2.23.0

```

**Comment by yonzhan** [comment]
ARM
