### ISSUE TITLE
Deprecitated, claims there is a CLI command to disable softdelete for keyvault which is no longer true

### ISSUE THREAD

**Issue by hjekman** [Azure/azure-cli#18149]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226e5769-f6c8-a480-db78-727fb96348ec
* Version Independent ID: 8ee06a2a-6eda-11be-3c8e-6ad948be207e
* Content: [az keyvault](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/keyvault.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/keyvault.yml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
key vault

**Comment by evelyn-ys** [comment]
Hi @hjekman, We has showed in the help message that once the soft delete is enabled, it can't be disabled anymore😊
```
> az keyvault update -h

Command
    az keyvault update : Update the properties of a Vault.

Arguments

    --enable-soft-delete [Deprecated] : [Vault Only] Property to specify whether the 'soft
                                        delete' functionality is enabled for this key vault. If it's
                                        not set to any value (true or false) when creating new key
                                        vault, it will be set to true by default. Once set to true,
                                        it cannot be reverted to false.  Allowed values: false,
                                        true.
```
