### ISSUE TITLE
How do we create a Service Bus Client Scoped topic subscription in Azure CLI?

### ISSUE THREAD

**Issue by samsmithnz** [Azure/azure-cli#18145]
It appears this option is only available in the Azure Portal. Is there missing documentation that describes how to set it in Azure CLI?

![image](https://user-images.githubusercontent.com/8389039/118886281-b97dd900-b8c6-11eb-812d-c0445de3ad37.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52b7d039-d543-895c-3056-2616b21ac86e
* Version Independent ID: 84875b23-e2ef-997a-c819-dafbae87f4e1
* Content: [az servicebus topic subscription](https://docs.microsoft.com/en-us/cli/azure/servicebus/topic/subscription?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/servicebus/topic/subscription.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/servicebus/topic/subscription.yml)
* Service: **service-bus**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by Saglodha** [comment]
Hi @samsmithnz , This option is available to be set via REST API/ ARM template. We would triage internally and get it supported with CLI. I would keep you posted for future updates. 

https://docs.microsoft.com/en-us/azure/templates/microsoft.servicebus/namespaces/topics/subscriptions?tabs=bicep
https://docs.microsoft.com/en-us/rest/api/servicebus/stable/subscriptions/create-or-update?msclkid=5d214cdebf0b11ecbbb981ab81e4d58a#sbclientaffineproperties

**Comment by Saglodha** [comment]
Hi @samsmithnz, this has been supported in our latest release. Kindly try to create the subscription and let us know in case of additional concerns.
