### ISSUE TITLE
Unable to use colon in tag name for Azure Front Door

### ISSUE THREAD

**Issue by davidjward30** [Azure/azure-cli#18166]
**Describe the bug**
When adding a tag to a Azure Front Door resource, if the tag name contains a colon, the following error is displayed:

Could not save the tags for the resource *****: Failed to save the tag, please correct any errors and try again. More information on tags and compatible resource types can be found here.

**To Reproduce**
In the Azure Portal add a tag name with a colon. Apply changes

**Expected behavior**
Since colon is not in the list of disallowed characters: https://docs.microsoft.com/en-gb/azure/azure-resource-manager/management/tag-resources?tabs=json#limitations I would expect it to succeed.

**Environment summary**
N/A

**Additional context**
N/A

**Comment by yonzhan** [comment]
route to service team

**Comment by t-bzhan** [comment]
The issue has been fixed now
