### ISSUE TITLE
az image copy - fails on "Creating snapshot in target region from the copied blob"

### ISSUE THREAD

**Issue by mikeassel** [Azure/azure-cli#18174]
## Describe the bug

**Command Name**
`az snapshot create`

**Errors:**
```
BadRequestError: (InvalidParameter) The value of parameter snapshot.name is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az snapshot create --resource-group {} --name {} --location {} --source {} --source-storage-account-id {} --output {} --tags {}`

## Environment Summary
```
macOS-10.16-x86_64-i386-64bit
Python 3.8.7
Installer: HOMEBREW

azure-cli 2.18.0 *

Extensions:
image-copy-extension 0.2.8

```

**Comment by mikeassel** [comment]
Looks like the issue was that the image name was too long.

**Comment by yonzhan** [comment]
image copy

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to latest version of azure cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
