### ISSUE TITLE
az keyvault set-policy do not work

### ISSUE THREAD

**Issue by zesluo** [Azure/azure-cli#18173]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Get bad request when using ''az keyvault set-policy --name keyvaultname --object-id 'xxxx-xxx-xx' --key-permissions get unwrapKey wrapKey"
![image](https://user-images.githubusercontent.com/46309533/119128496-51ff8f00-ba68-11eb-9b02-60082c39bd84.png)

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
Hi @zesluo, could you share more debug log containing the request not only the response?
I tested with my CLI(version 2.24.0) and it works well.
