### ISSUE TITLE
DLL Load failed winn32file

### ISSUE THREAD

**Issue by SomnathMore** [Azure/azure-cli#18172]
## Describe the bug

**Command Name**
``az --version or downloading any artifact

**Errors:**
DLL load failed while importing win32file: The specified module could not be found

## To Reproduce:
1. Install azure-cli 2.23.0
2. Try az --version or try to download any azure artifact 
3. Immediately gives the error '**DLL load failed while importing win32file: The specified module could not be found**.'

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.23.0 *

Extensions:
azure-devops 0.17.0

```

**Comment by SomnathMore** [comment]
![Issue](https://user-images.githubusercontent.com/24741589/119127795-60db4700-ba52-11eb-85f6-fee00429b539.JPG)

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Please try the solution provided at https://github.com/Azure/azure-cli/issues/17986#issuecomment-834607007 and let us know if the issue remains. Thanks.
