### ISSUE TITLE
`az iot dps *` commands uses an old api-version which fails on `az iot dps update --set properties.publicNetworkAccess`

### ISSUE THREAD

**Issue by nelsonmorais** [Azure/azure-cli#18184]
## Describe the bug

**Command Name**
`az iot dps update --resource-group <resource_group> --name <dps_name> --set properties.publicNetworkAccess="Disabled"`

**Errors:**
```
Setting Ip Filter is not supported on this api-version. Use 2020-01-01 api-version or higher. If you contact a support representative please include this correlation identifier: 3387f895-46ba-431d-88a8-763d527f6652, timestamp: 2021-05-22 19:40:17Z, errorcode: IH400024.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Make  sure there's a DPS service created
- `az iot dps update --resource-group <resource_group> --name <dps_name> --set properties.publicNetworkAccess="Disabled" --debug`

Verify that the api-version used on the PUT REST call uses an older version *2018-01-22* instead of the latest *2020-01-01* which is also indicated on the error message as being the required one.

## Expected Behavior
`az iot dps update --resource-group <resource_group> --name <dps_name> --set properties.publicNetworkAccess="Disabled"`
 should use the REST api-version *2020-01-01* instead of *2018-01-22*.

*Note:* All `az iot dps *` commands seem to be using the old version

## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.23.0

Extensions:
timeseriesinsights 0.2.1
azure-iot 0.10.11

```

**Comment by yonzhan** [comment]
route to service team

**Comment by nelsonmorais** [comment]
Hi @yonzhan, is there an ETA to get the issue fixed?

**Comment by yonzhan** [comment]
iot service team could provide the ETA.

**Comment by nelsonmorais** [comment]
Any update?

**Comment by c-ryan-k** [comment]
@nelsonmorais apologies for the delay - the DPS control plane SDK in the CLI has been updated as of the latest release (`2.28`) and uses api-version `2020-03-01` - so this should unblock your current scenario. One note to add, if you're still using the same environment as listed above, you'll need to update your cli extension to `0.10.14` or above in order to avoid a breaking change in newer versions of CLI core (`2.24.0` and newer).

@yonzhan fyi

**Comment by nelsonmorais** [comment]
@c-ryan-k thanks for the update.
I did a `az upgrade` but I only get 2.27.1 as the latest, is the fix already applied on this version, or how can I go to 2.28?
![image](https://user-images.githubusercontent.com/4737667/133824901-837f4048-d41b-4bea-94c3-a5f839224ae0.png)

**Comment by nelsonmorais** [comment]
I confirm that version 2020-03-01 is now used, so this issue can be closed.
