### ISSUE TITLE
Many 'az' commands die and produce a stack trace, include 'az self-test'.

### ISSUE THREAD

**Issue by daveman1010221** [Azure/azure-cli#18180]
## Describe the bug

**Command Name**
`az self-test`

**Errors:**
```
The operation 'azure.mgmt.netapp.operations._accounts_operations#AccountsOperations.delete' is invalid.
Traceback (most recent call last):
azure/cli/core/__init__.py, ln 831, in get_op_handler
    op = getattr(op, part)
AttributeError: type object 'AccountsOperations' has no attribute 'delete'

...

azure/cli/core/__init__.py, ln 836, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.mgmt.netapp.operations._accounts_operations#AccountsOperations.delete' is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az self-test`

## Expected Behavior

Runs a self-test.

## Environment Summary
```
Linux-5.11.0-7614-generic-x86_64-with-glibc2.33
Python 3.9.4
Installer: DEB

azure-cli 2.18.0 *

Extensions:
interactive Unknown <--- also stack traces
azure-devops 0.19.0

```
## Additional Context

Other commands that produce a stack trace:

az acs --help
az ad --help
az aks --help
az apim --help
az appservice --help
az batchai --help
az container --help
az cosmosdb --help
az dms --help
az functionapp --help
az group --help
az hdinsight --help
az lab --help
az managedapp --help
az openshift --help
az provider --help
az redis --help
az tag --help
az webapp --help

Happy to do more testing, if needed.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
According to the issue description, your installer is `deb` but Python version is 3.9.4.

If you install from our official repository following [Install the Azure CLI on Linux](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt), Azure CLI will run with the bundled Python 3.6.10 instead:

```
$ az -v
azure-cli                         2.23.0

core                              2.23.0
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/home/user1/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Apr 29 2021, 12:10:04)
[GCC 9.3.0]
```

Please remove the old installation with 


```
sudo apt remove azure-cli -y && sudo apt autoremove -y
``` 

Then follow the doc [Install the Azure CLI on Linux](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) to install from the official repository.
