### ISSUE TITLE
az ad app permission add with Microsoft Graph

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-cli#18185]
## Describe the bug

**Command Name**
`az ad app permission add --id $appRegistration.appId --api $graphSpId --api-permissions $graphPermissionId`

**Errors:**
```
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-pwfpui04\knack\cli.py, ln 233, in invoke
azure\cli\core\commands\__init__.py, ln 659, in execute
azure\cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 714, in _run_job
azure\cli\command_modules\role\commands.py, ln 69, in graph_err_handler
azure\cli\core\commands\__init__.py, ln 693, in _run_job
azure\cli\core\commands\__init__.py, ln 330, in __call__
pip-unpacked-wheel-c2pcumlb\azure\cli\core\__init__.py, ln 786, in default_command_handler
azure\cli\command_modules\role\custom.py, ln 935, in add_permission
ValueError: not enough values to unpack (expected 2, got 1)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad app permission add --id {} --api {} --api-permissions {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.18.0 *

Extensions:
azure-devops 0.18.0

```
## Additional Context
Trying to add Microsoft Graph User.Read Permission into app registration using az cli executed from PowerShell

**Comment by yonzhan** [comment]
@jiasli for awareness
