### ISSUE TITLE
Does az ml model deploy send a snapshot?

### ISSUE THREAD

**Issue by anirbansaha96** [Azure/azure-cli#18193]
Like `az ml run submit-script` sends a snapshot of the working directory which enables us to use these files in our code does `az ml model deploy` also send a snapshot of the working directory? I need to use some files in my scoring script. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 110fd5df-299e-f288-867f-c307a2f2ba9f
* Version Independent ID: ac8d15ce-b17b-8da8-8d60-cf98d448c9bd
* Content: [az ml model](https://docs.microsoft.com/en-us/cli/azure/ml/model?view=azure-cli-latest#az_ml_model_deploy)
* Content Source: [latest/docs-ref-autogen/ml/model.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/model.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by anirbansaha96** [comment]
@needuv Great thanks, this is what I wanted. Thanks for the doc.
