### ISSUE TITLE
Web App Creation issue

### ISSUE THREAD

**Issue by ashishsme14** [Azure/azure-cli#18191]
We have given task as -

Create the App service plan where pricing tier is strictly recommended for a Production environment but takes the minimum cost.

for this we used code as but not sure how we add prod environment strickly. 

`az appservice plan create -g user-jeyhyrrhkgrc -n MyPlan --sku F1`

Create two Web Apps using the app service plan created in the last step.

For this trying as -

`az webapp config set -g user-jeyhyrrhkgrc -n myweb --always-on true --subscription 23c7f465-e27b-418b-b8a7-21616582f9bb`

it showing my web not exit, so we did as-

`az configure --defaults web=myweb`

Still not working. Hence please suggest us.

**Comment by yonzhan** [comment]
route to service team

**Comment by ashishsme14** [comment]
we resolved the issue with help of https://github.com/Azure-Samples/azure-cli-samples/blob/master/app-service/deploy-deployment-slot/deploy-deployment-slot.sh 

thanks
