### ISSUE TITLE
Add `--user-data` option to `az vm create` and `az vmss create`

### ISSUE THREAD

**Issue by schnerring** [Azure/azure-cli#18201]
## Description of the new feature

> [User data through Azure Instance Metadata Service now generally available](https://azure.microsoft.com/en-us/updates/user-data-through-azure-instance-metadata-service-now-generally-available/):
> 
> Today, we are announcing the general availability of user data, enabling you to insert your own metadata into a Microsoft Azure virtual machine at **provisioning time**, with the ability to retrieve it using the Azure Instance Metadata Service (IMDS).

Azure Portal supports that feature:

![image](https://user-images.githubusercontent.com/3743342/119405744-482c9480-bcd1-11eb-8a64-d42af27dd7db.png)

[And so do ARM templates](https://docs.microsoft.com/en-us/azure/virtual-machines/user-data#create-user-data-for-azure-vmvmss)

I couldn't find an issue regarding that feature for the Azure CLI, though.

## Proposed implementation details

Add the `--user-data` option to `az vm create` and `az vmss create` to be able to provide user data at provisioning time.

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
This issue is implemented by PR #18432
