### ISSUE TITLE
Repair script fails to find Resource Group even though the name is an exact match

### ISSUE THREAD

**Issue by rjmccallumbigl** [Azure/azure-cli#18226]
### Extension name (the extension in question)
az vm repair

### Description of issue (in as much detail as possible)
A colleague reached out and let me know when he ran az vm repair, it was unable to locate the Resource Group even though the name was accurate. The exact error was `(ResourceGroupNotFound) Resource group 'APP_SHARED_STAGE' could not be found.`

- Confirmed the context was correct with Set-AzContext
- Tried copying the RG name
- Tried typing it manually
- Also tried to pass in the RG name via the following script:
```PowerShell
$rg = Get-AzResourceGroup "APP_SHARED_STAGE" #confirmed $rg returned Resource Group in question
az vm repair create -g $rg.ResourceGroupName -n NAMEOFVM --enabled-nested --verbose
```

The RG name was "APP_SHARED_STAGE". Another colleague and I had the script fail on an RG with underscores in it months ago but I saved no information thinking it was a one-off issue. Could it be a string parsing issue when it comes to RG names with underscores?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 355a594a-22ef-fd15-0b58-07701dd1815c
* Version Independent ID: d8356a0a-9aaf-900b-ce7a-021c9a0af509
* Content: [az vm repair](https://docs.microsoft.com/en-us/cli/azure/vm/repair?view=azure-cli-latest#ext-vm-repair-az-vm-repair-create)
* Content Source: [latest/docs-ref-autogen/vm/repair.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/vm/repair.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
compute

**Comment by qwordy** [comment]
@swbae31 Could you have a look? Thanks.

**Comment by SagnikLahiri** [comment]
Hello @rjmccallumbigl, I had faced a similar issue a while back and I wanted to know if you could also confirm the context using **"az account show"** instead of set-azcontext

**Comment by swbae31** [comment]
acked. Looking into it .

**Comment by amjads1** [comment]
Looking into the issue

**Comment by amjads1** [comment]
Working with internal teams to confirm on the issue.

**Comment by amjads1** [comment]
@jaylabell - Can you please look into this issue? This could be related to another repair issue that we talked about earlier.

**Comment by amjads1** [comment]
@grizzlytheodore - Tagging for your attention per our last triage discussion on repair issues.

**Comment by jaylabell** [comment]
These are repair script issues that are being handled via a CPlat SDK/PS engineer

**Comment by jaylabell** [comment]
This item is still being investigated

**Comment by microsoftsup** [comment]
Same issue - what to do? Cx is waiting. Getting Resource Group error although everything is correct.

**Comment by jaylabell** [comment]
@microsoftsup Thank you for the feedback, I will follow up with updates.

**Comment by jaylabell** [comment]
@rjmccallumbigl - @haagha is looking into this!

**Comment by andreabisiach** [comment]
If it can be of any help, note that "az disk create"  gives exactly the same error "ResourceGroupNotFound" in version 2.41.0.
It works well in version 2.40.0
In this case, there resource group not being found is the one specified in the parameter "--gallery-image-reference"

**Comment by jaylabell** [comment]
@haagha Can you please provide an update here.

**Comment by Drewm3** [comment]
Moving Jayla's issues over to me.

**Comment by Drewm3** [comment]
@rjmccallumbigl, do you know if this issue still reproduces? This issue is from 2021 and it seems like it bounced around through many people over the years. It is not clear if the issue was consistently reproducible at the time either. So, could you please reconfirm that you are able to reproduce this issue with the current CLI before we spend more time on this?
