### ISSUE TITLE
[AppService] Functionapp: move az functionapp devops-pipeline create to extension

### ISSUE THREAD

**Issue by calvinsID** [Azure/azure-cli#18228]
**Is your feature request related to a problem? Please describe.**
`az functionapp devops-pipeline create` command uses azure-functions-devops-build package, which pulls in vsts package and vsts package is very heavyweight

From email:
![image](https://user-images.githubusercontent.com/14339314/119573362-fb949800-bd68-11eb-9626-417cfbe497af.png)

It is suggested to move this command to an extension, since it isn't heavily used, to reduce size of core cli

**Describe the solution you'd like**
Move command to extension to reduce size of core cli

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by gzuber** [comment]
I'll take a look into this ASAP, thanks!

**Comment by panchagnula** [comment]
@gzuber is there any update on this? is there a milestone we tracking for this?

**Comment by panchagnula** [comment]
@gzuber ping any updates/ETA on this one?

**Comment by gzuber** [comment]
Hi @panchagnula I'm working on this now and am aiming for the [110 milestone](https://github.com/Azure/azure-cli/milestone/110). @calvinsID if I had some specific questions about this item and developing an extension, is there someone you can recommend I reach out to? Thanks!

**Comment by panchagnula** [comment]
> Hi @panchagnula I'm working on this now and am aiming for the [110 milestone](https://github.com/Azure/azure-cli/milestone/110). @calvinsID if I had some specific questions about this item and developing an extension, is there someone you can recommend I reach out to? Thanks!

Thanks for the response @gzuber . for this item talking to core folks @yonzhan would be recommended as well.
