### ISSUE TITLE
AzureStack Could Not Find Member 'enableCrossZoneUpgrade' and 'prioritizeUnhealthyInstances' 

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-cli#18229]
**Describe the bug**
We are getting bad request error running Azure CLI version 2019-03-01-hybrid in an Azure Stack environment. The following is the error:

```
az : ERROR: Deployment failed. Correlation ID: e436a4a0-c388-4834-aecf-ada3f8cf5c56. {
At C:\test\Workloads\DeveloperExperience\CLI\Workloads.Tests.CLI.ps1:759 char:23
+ ...   $result = az vmss create -g $vmssRgName -n $vmssName --admin-userna ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Deployme...ada3f8cf5c56. {:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

  "error": {
    "details": [
      {
        "message": "Could not find member 'enableCrossZoneUpgrade' on object of type 'RollingUpgradePolicy'. Path 
'properties.upgradePolicy.rollingUpgradePolicy.enableCrossZoneUpgrade', line 1, position 338.",
        "target": "vmss.properties.upgradePolicy.rollingUpgradePolicy.enableCrossZoneUpgrade"
      },
      {
        "message": "Could not find member 'prioritizeUnhealthyInstances' on object of type 'RollingUpgradePolicy'. Path 
'properties.upgradePolicy.rollingUpgradePolicy.prioritizeUnhealthyInstances', line 1, position 374.",
        "target": "vmss.properties.upgradePolicy.rollingUpgradePolicy.prioritizeUnhealthyInstances"
      }
    ],
    "code": "BadRequest",
    "message": "The request message is invalid."
  }
} 
```

**To Reproduce**
1. Install Azure CLI.
2. Register:
```
            az cloud register --name $TntAdminEnvironmentName `
                 --endpoint-resource-manager $asEndpoints.ResourceManagerEndpoint `
                 --suffix-storage-endpoint $asEndpoints.StorageEndpointSuffix `
                 --suffix-keyvault-dns ("." + $asEndpoints.AzureKeyVaultDnsSuffix) `
                 --endpoint-vm-image-alias-doc https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json `
                 --profile 2019-03-01-hybrid
```
3. Run the following command:
```
az vmss create -g $vmssRgName -n $vmssName --admin-username $vmssAdminUserName --admin-password $vmssAdminPassword --image $imageName --authentication-type password --upgrade-policy-mode $upgradeMode
```
**Expected behavior**
Should not throw bad request error.

**Environment summary**
We are using the nightly builds:

https://aka.ms/InstallAzureCliWindowsEdge

**Additional Context**
I have an internal email open with @qwordy. We can provide additional information in the email or here if requested.

**Comment by yonzhan** [comment]
compute

**Comment by qwordy** [comment]
This issue was introduced in this [PR](https://github.com/Azure/azure-cli/pull/17580/files). I raised my [concern](https://github.com/Azure/azure-cli/pull/17580/files#r609362130) of this issue during PR review.

**Comment by xfz11** [comment]
Hi @TheOnlyWei, This error happened because your request's api version is old.
If you feel it urgent to fix the problem, the workaround is to use `az cloud set -n <cloud name> --profile latest `to update your CLI cloud profile.
Otherwise you have to wait for it be fix in next CLI release.

**Comment by qwordy** [comment]
@zhoxing-ms  We need to update following code. Add `if` statement of each parameter to check whether it is `None`.
https://github.com/Azure/azure-cli/blob/716b10f107c2e410967d7e09e21a0225c78e3cc8/src/azure-cli/azure/cli/command_modules/vm/_template_builder.py#L932-L939

**Comment by zhoxing-ms** [comment]
> @zhoxing-ms We need to update following code. Add `if` statement of each parameter to check whether it is `None`.
> https://github.com/Azure/azure-cli/blob/716b10f107c2e410967d7e09e21a0225c78e3cc8/src/azure-cli/azure/cli/command_modules/vm/_template_builder.py#L932-L939

@qwordy Yes, that's what I thought~
