### ISSUE TITLE
az image copy to multiple locations not working

### ISSUE THREAD

**Issue by mikeassel** [Azure/azure-cli#18230]
I'm trying to copy an image to multiple locations using the following command:

### Command
```
az image copy --source-resource-group infinity-images \
  --source-object-name infinity-25-3-0-59550-0-0-cnf  \
  --target-location eastus2 southeastasia australiaeast westus \ 
  --target-resource-group infinity-images
```

I don't get any errors, but I do get the following output:
```
Getting OS disk ID of the source VM/image
Creating source snapshot
Getting sas url for the source snapshot with timeout: 3600 seconds
Creating resource group: image-copy-rg
Target location count: 4
Starting async process for all locations
Deleting transient resources
```
However, the resource group `image-copy-rg` is created, but it is empty and no new images are created. 

### Expected Behavior
I was expecting to see the newly created images in the target resource group.

### Environment Summary
```
macOS-10.16-x86_64-i386-64bit
Python 3.8.7
Installer: HOMEBREW

azure-cli 2.24.0

Extensions:
image-copy-extension 0.2.8

```

**Comment by yonzhan** [comment]
compute

**Comment by mikeassel** [comment]
@yonzhan isn't this feature supposed to already exist? I'm wondering why it has the `feature-request` label.

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
