### ISSUE TITLE
Clarification regarding the parameter "--ids"

### ISSUE THREAD

**Issue by carlosporter** [Azure/azure-cli#18239]
Hello,

The way the parameter "--ids" is documented, it's not clear if it refers to the resource id of a Network Security Group or the resource id for a NSG rule.

```
One or more resource IDs (space-delimited). It should be a complete resource ID containing all information of 'Resource Id' arguments.
You should provide either --ids or other 'Resource Id' arguments.

```

Also, the documentation indicates that "one or more" resource id values are allowed, does it mean that several NSG can be updated with a single command ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe4941c-7b46-b9fb-1c52-98e68f6354cc
* Version Independent ID: d1bc72fb-ccf9-9645-7b1d-98c91bc75a55
* Content: [az network nsg rule](https://docs.microsoft.com/en-us/cli/azure/network/nsg/rule?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/nsg/rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/nsg/rule.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by carlosporter** [comment]
@yonzhan,

So you mean that the --ids parameter refers to the resource Id of a network security group ?

**Comment by yonzhan** [comment]
@kairu-ms will help with and I only triage this issue.

**Comment by kairu-ms** [comment]
Hi @carlosporter,

> The way the parameter "--ids" is documented, it's not clear if it refers to the resource id of a Network Security Group or the resource id for a NSG rule.

`--ids` is a convenient way to assign `Resource Id Arguments` in CLI.
Let me use `az network nsg rule show` command as an example. In its help message attached below, the arguments in `Resource Id Arguments` except `--ids` are `--name`, `--nsg-name`, `--resource-group`, `--subscription`. So a valid value of `--ids` should contain all of the values, and only the id of `NSG rule` meets the requirements.

![image](https://user-images.githubusercontent.com/69238381/119754067-7af1ab00-bed2-11eb-948e-921b366c5179.png)

> Also, the documentation indicates that "one or more" resource id values are allowed, does it mean that several NSG can be updated with a single command ?

Yes. You can have a try.
