### ISSUE TITLE
Error executing: az vmss extension upgrade 

### ISSUE THREAD

**Issue by ohl-nemeses** [Azure/azure-cli#18257]
execution of `az vmss extension upgrade` fails completely and has no effect at all.

**Command Name**
`az vmss extension upgrade`

**Errors:**
```
'VirtualMachineScaleSetRollingUpgradesOperations' object has no attribute 'start_extension_upgrade'
Traceback (most recent call last):
cli\Lib\site-packages\knack\cli.py, ln 233, in invoke
azure\cli\core\commands\__init__.py, ln 660, in execute
azure\cli\core\commands\__init__.py, ln 723, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 716, in _run_job
artifacts\cli\Lib\site-packages\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 694, in _run_job
azure\cli\core\commands\__init__.py, ln 331, in __call__
site-packages\azure\cli\core\__init__.py, ln 811, in default_command_handler
azure\cli\command_modules\vm\custom.py, ln 3218, in upgrade_vmss_extension
AttributeError: 'VirtualMachineScaleSetRollingUpgradesOperations' object has no attribute 'start_extension_upgrade'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- No known prerequisites. 
- `az vmss extension upgrade --name {} --subscription {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.21.0 *

Extensions:
eventgrid 0.4.9

```

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@ohl-nemeses Hi, please upgrade CLI to the latest version *(you can upgrade it by running `az upgrade`)* and try again.
If this issue still can be reproduced, please feel free to let me know~
