### ISSUE TITLE
Function app creation -- add two additional app settings (WEBSITE_CONTENTSHARE and WEBSITE_CONTENTAZUREFILECONNECTIONSTRING) for Linux Consumption apps

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-cli#18252]
During function app creation, please add the following two add settings before sending the request to the backend  for Linux Consumption apps:

"WEBSITE_CONTENTSHARE" - This is the share name. For more information, see 
https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-shares--directories--files--and-metadata#share-names

"WEBSITE_CONTENTAZUREFILECONNECTIONSTRING" - This is the connection string to the function app's storage account

**Comment by Francisco-Gamino** [comment]
Hello, could you please assign this issue to @gzuber? Thanks! 

cc: @pragnagopa @AnatoliB @stefanushinardi @gzuber

**Comment by gzuber** [comment]
> Hello, could you please assign this issue to @gzuber? Thanks!
> 
> cc: @pragnagopa @AnatoliB @stefanushinardi @gzuber

Thanks @Francisco-Gamino, I'll take a look!

**Comment by Francisco-Gamino** [comment]
> Thanks @Francisco-Gamino, I'll take a look!

Thanks @gzuber!
