### ISSUE TITLE
add private-subnet example

### ISSUE THREAD

**Issue by dejan-shuki** [Azure/azure-cli#18250]
[Enter feedback here]
Can you add example how to specify both name of private-subnet and range of IPs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e3ccf76-e4ff-16db-01c5-25a19798a58e
* Version Independent ID: d2ef04fc-c838-576e-9d40-729e30e2b3f4
* Content: [az databricks workspace](https://docs.microsoft.com/en-us/cli/azure/databricks/workspace?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/databricks/workspace.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/databricks/workspace.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by 00Kai0** [comment]
Hi @dejan-shuki , can you describe it more clearly, what kind of example do you need ?
