### ISSUE TITLE
Az-cli command "az storage fs file move"  not working with SAS token

### ISSUE THREAD

**Issue by suvarna-03** [Azure/azure-cli#18256]
Issue Description:

Az-cli command "az storage fs file move"  not working with SAS token however same commands works with Access keys.

Doc for reference: https://docs.microsoft.com/en-us/cli/azure/storage/fs/file?view=azure-cli-latest 

Steps to reproduce:

1.SAS generated from Portal

Command: az storage fs file move --new-path "fs1/fs11/vtestone.txt" -p "vtestone.txt" -f fs1 --account-name “accname” --sas-token '"?sv=2020-02-10&ss=b&srt=sco&sp=rwdlacx&se=2021-05-27T18:04:05Z&st=2021-05-27T10:04:05Z&spr=https&sig= "' 

2. SAS generated from Powershell command.

$resourceGroupName="Rgrp"  
$storageAccName=" accname"  

	## Function to get all the blobs  
	Function CreateSASToken  
	{  
	    Write-Host -ForegroundColor Green "Creating an account level SAS Token.."    
	    ## Get the storage account   
	    $storageAcc=Get-AzStorageAccount -ResourceGroupName $resourceGroupName -Name $storageAccName     
	    ## Get the storage account context  
	    $ctx=$storageAcc.Context  
	    ## Creates an account-level SAS token.  
	    New-AzStorageAccountSASToken -Context $ctx -Service Blob -ResourceType Service,Container,Object -Permission "racwdlup"  
	}  CreateSASToken    

Command: az storage fs file move --new-path "fs1/fs11/vtestone.txt" -p "vtestone.txt" -f fs1 --account-name "accname" --sas-token '"?sv=2019-07-07&sig=&se=2021-05-27T11%3A54%3A29Z&srt=sco&ss=b&sp=racupwdl"' 

3. SAS generated from az-cli.

az storage account generate-sas --account-key “###” --account-name “accname” --expiry 2020-01-01 --https-only --permissions acuw --resource-types co --services bf 

command: az storage fs file move --new-path "fs1/fs11/vtestone.txt" -p "vtestone.txt" -f fs1 --account-name "accname" --sas-token '"?se=2020-01-01&sp=wacu&spr=https&sv=2018-03-28&ss=bf&srt=co&sig= "' 

4. SAS generated from explorer: When we generated SAS from MS explorer it works.

az storage fs file move --new-path "fs1/fs11/vtesthree.txt" -p "vtesthree.txt" -f fs1 --account-name “accname” --sas-token '"?sv=2020-02-10&st=2021-05-sr=c&sp=racwdlmeop&sig="' 

Ask: : Why this behavior is observed when storage explorer is able to move the files. And same operations when we tried from portal/cli/powershell it is not working.

Please find attached document for the screen shots of above testing.
[SAS scenarios for az fs file move command.docx](https://github.com/Azure/azure-cli/files/6553724/SAS.scenarios.for.az.fs.file.move.command.docx)

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @suvarna-03, you need to specify move permission for sas token. As `az storage blob generate-sas` is for blob service and there is no move operation for blob, it is not able to generate valid sas for files in ADLS Gen2 account.
The right command to use is `az storage fs generate-sas` and we will add it in PR #18768.
