### ISSUE TITLE
'az storage account network-rule add' does not support secure transfer policy

### ISSUE THREAD

**Issue by jonathancisneros** [Azure/azure-cli#18264]
My Azure Storage account has "Secure transfer required" enabled and also the Firewall is. I need to access the storage from a build agent, and for this, I need to add the current agent IP in the storage Firewall, so I am running the following command:
`az storage account network-rule add -g myRG --account-name myStorage --ip-address 123.123.123`

But it is failing with the following error:
```
ERROR: (RequestDisallowedByPolicy) Resource 'myRG' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"CUSTOM:Enforce Secure transfer storage account to accept requests only from secure connections (HTTPS)",...
Additional Information:Type: PolicyViolation
Info: {
    "policyDefinitionDisplayName": "CUSTOM:Enforce Secure transfer storage account to accept requests only from secure connections (HTTPS)",
    "evaluationDetails": {
        "evaluatedExpressions": [
            {
                "result": "True",
                "expressionKind": "Field",
                "expression": "type",
                "path": "type",
                "expressionValue": "Microsoft.Storage/storageAccounts",
                "targetValue": "Microsoft.Storage/storageAccounts",
                "operator": "Equals"
            },
            {
                "result": "False",
                "expressionKind": "Field",
                "expression": "Microsoft.Storage/storageAccounts/minimumTlsVersion",
                "path": "properties.minimumTlsVersion",
                "expressionValue": "TLS1_0",
                "targetValue": "TLS1_2",
                "operator": "Equals"
            }
        ]
    }

```
With "Secure transfer required" disabled, it works. But the company policies no longer allows me to disable secure transfer and I need to find a way to add the agent IP in the Storage Firewall using code (Az CLI/Az PS Cmdlets/REST API).

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Hi @jonathancisneros, you need to enable secure transfer with `az storage account update -n xxxx --https-only`.
I have tested the network rule add scenario and it works to me.
