### ISSUE TITLE
Does a AzureML webservice overwrite reset the Data Collection Dataset?

### ISSUE THREAD

**Issue by anirbansaha96** [Azure/azure-cli#18271]
If we have an AzureML web service endpoint that is collecting data (for Data Drift Monitoring), does overwriting the web service endpoint with a new version of the model break links with the Dataset registered for collecting data. 

The relative path to this dataset is:
`<Subscription-ID>/<Resource-Group>/<Workspace>/<Webservice-Name>/<model-name>/<version>/inputs/**/inputs*.csv`

If we redeploy a new version using `az ml model deploy ..... --overwrite`, will we need a new reference to a new Dataset for detecting Data Drift? 

If we use `az ml service update ..`, will the Dataset reference be kept intact?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 110fd5df-299e-f288-867f-c307a2f2ba9f
* Version Independent ID: ac8d15ce-b17b-8da8-8d60-cf98d448c9bd
* Content: [az ml model](https://docs.microsoft.com/en-us/cli/azure/ml/model?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/model.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/model.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by QianqianNie** [comment]
Hi Anirban

Thanks for reaching out to us. 

Dataset is a reference to the relative path, and data loading is up to what files or file content is there when dataset loading is triggered.

So for your case, please help us to understand these questions regarding to data collection with new endpoint version, 
1. is the new version of endpoint going to collect the data to the same relative path? which is 
<Subscription-ID>/<Resource-Group>/<Workspace>/<Webservice-Name>/<model-name>/<version>/inputs/**/inputs*.csv
**=> if relative path still stays the same, then dataset reference wont change**
2. if its yes, is the file going to be overwritten? or a new file for each day is collected?  => **this will impact what data will be loaded when dataset loading is triggered**

Hope this helps!

**Comment by anirbansaha96** [comment]
> 1. is the new version of endpoint going to collect the data to the same relative path? which is
>    //////inputs/**/inputs*.csv
>    **=> if relative path still stays the same, then dataset reference wont change**

The model version will change, hence a new Dataset reference needs to be created. Or, we can input that subfolder as a * instead of version_number (int).

Thanks, yes. This answers my question.
