### ISSUE TITLE
Does az ml model deploy --overwrite or az ml service update temporarily put the service into transitioning/ unhealthy state?

### ISSUE THREAD

**Issue by anirbansaha96** [Azure/azure-cli#18272]
When we update a webservice endpoint, using `az ml model deploy .... --overwrite` or `az ml service update ...`, does it temporarily go out of service?
Since AKS is managed Kubernetes cluster, does Azure ensure zero down-time by managing pods by updating them to ensure it is always up and running?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 110fd5df-299e-f288-867f-c307a2f2ba9f
* Version Independent ID: ac8d15ce-b17b-8da8-8d60-cf98d448c9bd
* Content: [az ml model](https://docs.microsoft.com/en-us/cli/azure/ml/model?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/model.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/model.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by KeliGui** [comment]
For webservice update, AML use rolling update strategy and set the maxUnavailable and maxSurge to 1.  So if the replica number of your webservice is larger than 1, there will be no downtime.
