### ISSUE TITLE
Cannot delete roleAssignment because of invalid api-version

### ISSUE THREAD

**Issue by mauve** [Azure/azure-cli#18289]
## Describe the bug

**Command Name**
`az role assignment delete`

**Errors:**
```
The resource type 'roleDefinitions' could not be found in the namespace 'Microsoft.Authorization' for api version '2020-04-01-preview'. The supported api-versions are '2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01,2015-07-01,2016-07-01,2017-05-01,2017-09-01,2018-01-01-preview,2018-07-01'.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role assignment delete --subscription {} --ids {}`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.24.0

Extensions:
azure-devops 0.18.0
azure-iot 0.10.13

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by mauve** [comment]
I think this might because I mixed the roleDef ID with the roleAss ID.

**Comment by jiasli** [comment]
Azure CLI uses `2020-04-01-preview` for `RoleAssignment` and `2018-01-01-preview` for `RoleDefinition`:

https://github.com/Azure/azure-cli/blob/2771efa236aa7ebecf6e63f587bd694d1f121545/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L162-L164

Please use the correct role assignment ID in `az role assignment delete`, like `/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Authorization/roleAssignments/254a30cf-3bdd-4e6c-aa9e-9d96397bf63a`.
