### ISSUE TITLE
When in specific Azure subscription, resource filter result list displays resources from other subscriptions too.

### ISSUE THREAD

**Issue by surendrakongurootu** [Azure/azure-cli#18282]
When in specific Azure subscription, resource filter result list displays resources from other subscriptions too. It will be helpful if it display resource specific to selected subscription.

In Azure Portal, when multiple subscriptions are present. You can reproduce this by selection of one subscription and filter for specific resource.

**Expected behavior**
It will be helpful if it display resource specific to selected subscription.

**Environment summary**
Azure Portal

**Additional context**
Though bread Crum displays one subscription, in result we can see list of all available subscriptions.

**Comment by yonzhan** [comment]
Since not Azure CLI issue.
