### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by buingochieudb** [Azure/azure-cli#18293]
## Describe the bug

**Command Name**
`az vm create`

**Errors:**
```
the following arguments are required: --name/-n, --resource-group/-g

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm create`

## Environment Summary
```
Linux-5.4.0-1047-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.24.0

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
Compute
