### ISSUE TITLE
Given Az logic workflow list command is working only after adding subscription parameter

### ISSUE THREAD

**Issue by rajaduraisamy28** [Azure/azure-cli#18302]
[Enter feedback here]
Hi,
The az logic workflow list command (az logic workflow list --resource-group "test_resource_group") is throwing error when try to execute with only advised resource group parameter. It is working only if we provide subscription as an additional parameter. So, please update list command (az logic workflow list --resource-group "test_resource_group" **--subscription "test_subscription"**) in az logic workflow page.

Regards,
Raja

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa2d288d-9ff4-a51c-3f30-1d79ea6564ab
* Version Independent ID: 4483e7d2-49f0-c2f4-afa2-3d7137ea70be
* Content: [az logic workflow](https://docs.microsoft.com/en-us/cli/azure/logic/workflow?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/logic/workflow.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/logic/workflow.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by jsntcy** [comment]
The fix is available in logic 0.1.5 (latest version), and you can upgrade extension to latest version using command “az extension update –name logic” to try the fix.
