### ISSUE TITLE
Description for api-id param for az apim api import is incorrect

### ISSUE THREAD

**Issue by plzm** [Azure/azure-cli#18306]
The description for the --api-id param for the 'az apim api import' command is incorrect. It references a version, but it should actually reference the API ID.

This is particularly important when using this command to update an already-existing API with a Swagger file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f27e34-66e0-1d08-f734-26ce29c56c36
* Version Independent ID: d1a421eb-807c-c0bd-cee3-a5aed7335625
* Content: [az apim api](https://docs.microsoft.com/en-us/cli/azure/apim/api?view=azure-cli-latest#az_apim_api_import)
* Content Source: [latest/docs-ref-autogen/apim/api.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/apim/api.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by miaojiang** [comment]
cc @DreamlessA

**Comment by RakeshMohanMSFT** [comment]
This is fixed
