### ISSUE TITLE
`cognitiveservices account update` does not take effect

### ISSUE THREAD

**Issue by BigCat20196** [Azure/azure-cli#18311]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When I use the 'az cognitiveservices account update' command to modify 'encryption', I encounter the problem that the modification does not take effect. But when I only modify a tag, it is executed successfully.

I guess it's because 'Update' doesn't support 'encryption'.

**To Reproduce**

`az cognitiveservices account create -n {sname}-g {MyRG} --kind Face --sku S0 -l westeurope --assign-identity --yes`

`az cognitiveservices account show -n {sname}-g {MyRG} `

`az cognitiveservices account update -n {sname}-g {MyRG} --encryption '{\"keySource\": \"Microsoft.CognitiveServices\"}'`

`az cognitiveservices account show -n {sname}-g {MyRG} `

**Expected behavior**

`Encryption ' was successfully updated.

**Environment summary**

python
Windows-10-10.0.19041
Python 3.8.8
Installer: pip

azure-cli 2.23.0

**Additional context**

Doc: [https://docs.microsoft.com/en-us/cli/azure/cognitiveservices/account?view=azure-cli-latest#az_cognitiveservices_account_update](url)

**Comment by yonzhan** [comment]
route to service team

**Comment by BigCat20196** [comment]
It seems to be resolved, temporarily close the issue
