### ISSUE TITLE
incorrect documentation for `az keyvault list-deleted --resource-type`

### ISSUE THREAD

**Issue by aandyl** [Azure/azure-cli#18319]
**Describe the bug**
The documentation for the `--resource-type` option to the `az keyvault list-deleted` command states that: "When --resource-type is not present the command will list all deleted Vaults and HSMs. Possible values for --resource-type are vault and hsm."

However, this does not appear to be correct. With a deleted HSM in my account, when I ran `az keyvault list-deleted`, it did not print anything. Only when I ran `az keyvault list-deleted --resource-type hsm` did it list the deleted HSM.

For reference: https://github.com/Azure/azure-cli/blob/aad1e1801262eaf13615f7170f89a485627ed0f8/src/azure-cli/azure/cli/command_modules/keyvault/custom.py#L249

**To Reproduce**

1. Create a managed HSM.
2. Delete the managed HSM.
3. Run `az keyvault list-deleted`

**Expected behavior**
Either the `az keyvault list-deleted` command should list everything, or the documentation should be changed to reflect the actual behavior.

**Environment summary**

Linux, Ubuntu 20.04, CLI version 2.24.0

**Comment by yonzhan** [comment]
keyvault
