### ISSUE TITLE
Issue Regarding HDInsight registeration

### ISSUE THREAD

**Issue by revanthkumar1999** [Azure/azure-cli#18325]
I'm facing issue regarding Microsoft.HDInsight registeration. From nearly 15 hour it is in registering state. Kindly please resolve the issue.

**Comment by yonzhan** [comment]
route to service team

**Comment by deshriva** [comment]
@revanthkumar1999 : Do you have a rough timeframe on when this happened? Also can you share subscriptionId.

**Comment by deshriva** [comment]
This was a product bug and the fix has already been rolled out.
