### ISSUE TITLE
Create VM flow broken for "EdgeZone" 

### ISSUE THREAD

**Issue by viananth** [Azure/azure-cli#18327]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Creating a VM in EdgeZone using "--edge-zone" parameter creates the vm in edge zone, but creates other resources (like VNet, Nic, Public Ip, etc)  in main region.

**To Reproduce**

1. Install latest Az CLI
2. Run "az vm create -g testcli -n testclivm --image UbuntuLTS --edge-zone microsoftlosangeles1 --public-ip-sku Standard --location westus --debug --generate-ssh-keys"
3. Creates the VM successfully in edge zone. But other resources are created in main region.
4. For example, NIC's Json view from portal should show "ExtendedLocation" as "microsoftlosangeles1", but it doesn't have edgezone information here (with the latest API version from drop down list):

> {
>   "name": "testclivmVMNic",
>   "id": "/subscriptions/baffff89-2c76-424a-af4c-43b7518a3cb8/resourceGroups/viananth-testcli/providers/Microsoft.Network/networkInterfaces/testclivmVMNic",
>   "etag": "W/\"1867f590-9435-4c55-80c9-5d7273c39d3d\"",
>   "location": "westus",
>   "tags": {},
>   "properties": {
>     "provisioningState": "Succeeded",
>     "resourceGuid": "59b8cbe5-8f0e-4d10-8b0b-05345e0070f6",
>     "ipConfigurations": [
>       {
>         "name": "ipconfigtestclivm",
>         "id": "/subscriptions/baffff89-2c76-424a-af4c-43b7518a3cb8/resourceGroups/viananth-testcli/providers/Microsoft.Network/networkInterfaces/testclivmVMNic/ipConfigurations/ipconfigtestclivm",
>         "etag": "W/\"1867f590-9435-4c55-80c9-5d7273c39d3d\"",
>         "type": "Microsoft.Network/networkInterfaces/ipConfigurations",
>         "properties": {
>           "provisioningState": "Succeeded",
>           "privateIPAddress": "10.0.0.4",
>           "privateIPAllocationMethod": "Dynamic",
>           "publicIPAddress": {
>             "id": "/subscriptions/baffff89-2c76-424a-af4c-43b7518a3cb8/resourceGroups/viananth-testcli/providers/Microsoft.Network/publicIPAddresses/testclivmPublicIP"
>           },
>           "subnet": {
>             "id": "/subscriptions/baffff89-2c76-424a-af4c-43b7518a3cb8/resourceGroups/viananth-testcli/providers/Microsoft.Network/virtualNetworks/testclivmVNET/subnets/testclivmSubnet"
>           },
>           "primary": true,
>           "privateIPAddressVersion": "IPv4"
>         }
>       }
>     ],
>     "dnsSettings": {
>       "dnsServers": [],
>       "appliedDnsServers": [],
>       "internalDomainNameSuffix": "4en3ku5oe4me1f4qb4rp5jioag.dx.internal.cloudapp.net"
>     },
>     "macAddress": "00-22-48-06-A4-67",
>     "enableAcceleratedNetworking": false,
>     "enableIPForwarding": false,
>     "networkSecurityGroup": {
>       "id": "/subscriptions/baffff89-2c76-424a-af4c-43b7518a3cb8/resourceGroups/viananth-testcli/providers/Microsoft.Network/networkSecurityGroups/testclivmNSG"
>     },
>     "primary": true,
>     "virtualMachine": {
>       "id": "/subscriptions/baffff89-2c76-424a-af4c-43b7518a3cb8/resourceGroups/viananth-testcli/providers/Microsoft.Compute/virtualMachines/testclivm"
>     },
>     "hostedWorkloads": [],
>     "tapConfigurations": [],
>     "nicType": "Standard"
>   },
>   "type": "Microsoft.Network/networkInterfaces"
> }

**Expected behavior**

It should deploy dependent resources like Nic, VNet, Public Ip, etc in edge zone, not main region.
"extendedLocation": {
        "type": "EdgeZone",
        "name": "microsoftlosangeles1"
    },

**Environment summary**

az upgrade
Windows 10 enterprise
cmd.exe
azure-cli                         2.24.0 *

**Additional context**

**Comment by qwordy** [comment]
I confirm that dependent resources of "vm create" are not created in edge zone yet. We will support it.

**Comment by zhoxing-ms** [comment]
@viananth Hi, at present, when creating VM dependent resources by CLI, the api-version of those resources are fixed. Because the previous fixed version is too old, it does not support edge zone. Therefore, we need to upgrade the api-version used to create dependent resources when users pass in `--edge-zone` parameter, right?  Moreover, If more than one api-version supports edge zone, do we prefer the earliest version (most stable) or the latest version?

For example, the original api-version of `Microsoft.Network/virtualNetworks` is `2015-06-15` [code link](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_template_builder.py#L221) , it should be upgraded to `2020-07-01` or `2021-02-01` when the user passes in parameter `--edge-zone`?

**Comment by viananth** [comment]
@zhoxing-ms  Let's use the latest one 2021-02-01. Thanks for the update!

**Comment by zhoxing-ms** [comment]
@viananth By the way, I would like to ask if `az vmss create` also needs to build those dependent resources on edge zone?

**Comment by viananth** [comment]
> @viananth By the way, I would like to ask if `az vmss create` also needs to build those dependent resources on edge zone?

@zhoxing-ms Yes, VMSS dependent resources also need to be in edgezone. Thanks for checking.
