### ISSUE TITLE
How to execute a startup commands during the deployment of my app

### ISSUE THREAD

**Issue by yviouswilliamous** [Azure/azure-cli#18330]
## Describe the bug
Hi, 

**What can I do to make sure some commands are executed at app container startup ?**

I deployed a custom python package in an azure artifact feed. Unlike the other packages in the requirements.txt, this one need to be downloaded from my azure artifact feed, not from PyPi. When I launch the app deployment I get the following error :

`_Zip deployment failed. {'id': 'abeede44-d648-4891-961b-9e1983f4931b', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2021-06-02T08:55:03.4480845Z', 'start_time': '2021-06-02T08:55:04.6274605Z', 'end_time': '2021-06-02T08:56:02.3265668Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://test-cntrl-permanent-api-2.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://test-cntrl-permanent-api-2.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'test-cntrl-permanent-api-2'}. Please run the command az webapp log deployment show -n test-cntrl-permanent-api-2 -g azr-rg-bpceit-bpcesa-d2i2_`

To make sure that package is installed correctly with the other packages of the requirements.txt I need to modify the **pip.conf** file of the app container. Thus, the following commands must be executed at the app startup: 
```
_mkdir $HOME/.config/pip/
cp pip.conf $HOME/.config/pip/_
```

I've put them in a startup file startup.sh and executed the following command in the cli : `az webapp config set -g <resource-group> -n <app-name> --startup-file <startup-file url>`

But I still get the error.

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az webapp up -g {} -n {}`
- `az webapp config set -g {} -n {} --startup-file={}`

## Expected Behavior
Everything should work fine and the error should not appear.

## Environment Summary
```
Linux-5.4.0-1031-azure-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *

```

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
@btardif this issue is not specific to CLI - do you know who can help with this question?

**Comment by btardif** [comment]
@tulikac see if we can confirm if the startup.sh is part of the app payload (it should be) 

If there is startup.sh command in the root folder the service should pick this up by default.

The `az webapp config set -g {} -n {} --startup-file={}` commnad is only needed if the startup script has a custom name other than startup.sh
