### ISSUE TITLE
Error when creating remote connection 

### ISSUE THREAD

**Issue by bolbo** [Azure/azure-cli#18334]
## Describe the bug

**Command Name**
`az webapp create-remote-connection`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

https://docs.microsoft.com/fr-fr/azure/app-service/configure-linux-open-ssh-session#open-ssh-session-from-remote-shell

- `az webapp create-remote-connection --subscription {} --resource-group {} -n {}`

## Environment Summary
```
Linux-5.4.0-67-generic-x86_64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by CarstenHS** [comment]
any news on this one? This has gathered dust for more than ½ year now.

**Comment by seligj95** [comment]
Unable to repro. Closing as this may be stale. Please re-open if this is still an issue.
