### ISSUE TITLE
--application-id mentioned in documentation not supported on practice

### ISSUE THREAD

**Issue by vitali-kviatkouski** [Azure/azure-cli#18342]
--application-id mentioned in documentation not supported on practice. EastUS region

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226e5769-f6c8-a480-db78-727fb96348ec
* Version Independent ID: 8ee06a2a-6eda-11be-3c8e-6ad948be207e
* Content: [az keyvault](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/keyvault.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/keyvault.yml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
Hi @vitali-kviatkouski, May I know which command do you mean?

**Comment by vitali-kviatkouski** [comment]
az keyvault set-policy - trying to create compound policy with both object id and application id
