### ISSUE TITLE
az network dns record-set a update failure

### ISSUE THREAD

**Issue by scootercop** [Azure/azure-cli#18356]
## Describe the bug

**Command Name**
`az network dns record-set a update`

**Errors:**
```
cannot import name 'BatchManagementClient' from 'azure.mgmt.batch' (/usr/lib/python3/dist-packages/azure/mgmt/batch/__init__.py)
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 558, in execute
    self.commands_loader.load_arguments(command)
...
network/private_link_resource_and_endpoint_connections/resource_providers/batch_provider.py, ln 6, in <module>
    from azure.mgmt.batch import BatchManagementClient
ImportError: cannot import name 'BatchManagementClient' from 'azure.mgmt.batch' (/usr/lib/python3/dist-packages/azure/mgmt/batch/__init__.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network dns record-set a update --help`

## Environment Summary
```
Linux-5.11.0-1009-raspi-aarch64-with-glibc2.33
Python 3.9.5
Installer: DEB

azure-cli 2.18.0 *

Extensions:
azure-devops 0.19.0

```

**Comment by yonzhan** [comment]
network

**Comment by scootercop** [comment]
This was on a Ubuntu 21.04 system. I think there isn't official support for 21.04 yet so i downgraded to Ubuntu Server 20.04 LTS.
The official release still didn't work with 64bit ARM so i installed the package following commands here -
https://ubuntu.pkgs.org/20.04/azure-cli-amd64/azure-cli_2.24.2-1~focal_all.deb.html 
And it's worked fine since.
Installing the build source (by just running apt install azure-cli) on the pi doesn't work as mentioned on the install page so that's expected and is fine.
If its expected behaviour feel free to close this.

**Comment by devigned** [comment]
Similar: https://github.com/Azure/azure-cli/issues/19313
