### ISSUE TITLE
WebApp:Resource state Failed for az webapp deployment source config

### ISSUE THREAD

**Issue by kelvinduan2020** [Azure/azure-cli#18357]
## Describe the bug

**Command Name**
`az webapp deployment source config`

**Errors:**
```
Deployment failed. Correlation ID: 353e2da1-d040-4e3b-b640-fae47ee2923d. Operation failed with status: 200. Details: Resource state Failed
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config --name {} --resource-group {} --repo-url {} --branch {} --manual-integration`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.14.0 *

```

**Comment by yonzhan** [comment]
route to service team

**Comment by kelvinduan2020** [comment]
> route to service team

hi, is there any update for this issue?

**Comment by yonzhan** [comment]
webapp service team should look into this

**Comment by Kotasudhakarreddy** [comment]
@kelvinduan2020 I see that operation is failed with the status 200. Could you please share the `-debug` log for further analysis.

**Comment by kelvinduan2020** [comment]
Hi Kota,

I have attached the screenshot, as you can see from it, the deployment is fine when I removed the branch but it is not ok when I added the branch with master.
However, it is not the biggest issue, the one is this https://github.com/Azure/azure-cli-extensions/issues/3468
Could you please ask the team to investigate is asap, as it is blocked our CICD pipeline.
Thank you in advance.

Best Regards,

Kelvin DUan
Environments Support Engineer

Cell: +86 177 2754 2929
Shen Zhen, China   epam.com<http://www.epam.com/>

**Comment by Kotasudhakarreddy** [comment]
Thanks for sharing. Will look in to it.

**Comment by panchagnula** [comment]
@kelvinduan2020 have you tried to run this command by deleting the extension you have installed? @calvinsID please check the extension issue https://github.com/Azure/azure-cli-extensions/issues/3468

**Comment by seligj95** [comment]
closing due to no response. please reopen if there is still an issue.
