### ISSUE TITLE
Wrong information on the page 

### ISSUE THREAD

**Issue by durayakar** [Azure/azure-cli#18355]
az disk update 

--disk-encryption-set
Name or ID of disk encryption set that is used to encrypt the disk.

This is wrong information. The encryption set CANNOT be located with an ID and it throws an exception like:
(BadRequest) DiskEncryptionSet '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Compute/diskEncryptionSets/{diskEncryptionId}' was not found.

The instructions should read: 

--disk-encryption-set
Name of disk encryption set that is used to encrypt the disk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74997eeb-6fa3-4318-79da-8cf4dce59cfe
* Version Independent ID: c8cea09f-196e-7269-dc42-b6b8933dbaf1
* Content: [az disk](https://docs.microsoft.com/en-us/cli/azure/disk?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/disk.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/disk.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@durayakar In fact, the parameter `--disk-encryption-set` can support passing in ID type. The reason for this error may be that the resource you passed in does not exist, could you confirm if the resource exists? 
If this resource exists, please add parameter `--debug` to this command and rerun it, and then send the printed information to me by email. My email address is Zhou.Xing@microsoft.com, thanks~
