### ISSUE TITLE
Azure CLI command "sig" broken

### ISSUE THREAD

**Issue by rsuds** [Azure/azure-cli#18350]
O/S:  openSUSE Leap 15.3
Kernel: Linux OpenSUSE02 5.3.18-57-default #1 SMP Wed Apr 28 10:54:41 UTC 2021 (ba3c2e9) x86_64 x86_64 x86_64 GNU/Linux
Azure RPM version: azure-cli-2.14.2-6.4.1.noarch

## Describe the bug

**Command Name**
`az sig`

**Errors:**
```
The operation 'azure.mgmt.compute.v2019_12_01.operations#GalleriesOperations.delete' is invalid.
Traceback (most recent call last):
azure/cli/core/__init__.py, ln 829, in get_op_handler
    op = getattr(op, part)
AttributeError: type object 'GalleriesOperations' has no attribute 'delete'

...

azure/cli/core/__init__.py, ln 834, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.mgmt.compute.v2019_12_01.operations#GalleriesOperations.delete' is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sig`

## Environment Summary
```
Linux-5.3.18-57-default-x86_64-with-glibc2.3.4
Python 3.6.13
Installer: PIP

azure-cli 2.14.2 *

```

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@rsuds Hi, please upgrade CLI to the latest version *(you can upgrade it by running `az upgrade`)* and try again.
If this issue still can be reproduced, please feel free to let me know~
