### ISSUE TITLE
[App Service] Rename hostname group to domain

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1835]
This is fairly subjective, but I wonder whether it would be clearer to rename the `az appservice web config hostname` command group to `az appservice web config domain`. The portal calls the respective blade `Custom domains`, the pricing tier breakdowns refer to it as `Custom domains`, and even the help text for the commands within the `az appservice web config hostname` group currently clarifies the term `hostname` with `(custom domain)`, so that term is already heavily used, and I feel like it more accurately represents what you're managing, and feels a little more familiar/friendly.

Maybe it's just me, but I wouldn't imagine users would commonly ask themselves "How do I add a hostname to my web app?", as opposed to, "How can I add a custom domain to my web app?".

**Comment by yugangw-msft** [comment]
We disucssed and decided to keep the `hostname`. Portal is not consistent by itself and the `Custom Domain` blade mentions both
