### ISSUE TITLE
WebApp:Provide more explanation about how to use a JSON file to import appsettings values

### ISSUE THREAD

**Issue by giovannifl** [Azure/azure-cli#18367]
Executing below command fails
az webapp config appsettings set -g az1xxxx-xxx-xxx-xxx-xx -n wexxx-xxx-xxx-xx --settings @appSettings.json 

with the following error

The command failed with an unexpected error. Here is the traceback:
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 506, in shell_safe_json_parse
    return json.loads(json_or_dict_string, strict=strict)
  File "/opt/az/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/opt/az/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

As it also has been reported here:
https://stackoverflow.com/questions/57302327/azure-appsettings-with-json-file-in-azure-cli

so the filename must be enclosed between ""

I've also tried to import a JSON file with the following format 
[
    {
      "name": "Value_1",
      "slotSetting": false,
      "value": "test"
    },
    {
      "name": "Value_2",
      "slotSetting": false,
      "value": "water"
    }
]

but what happens is that all values are loaded as below

{
    "name": "Value_1",
    "slotSetting": false,
    "value": "False"
  }

Please can you confirm the JSON file format ?

This issue has been encountered with az cli 2.24.2 version

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* Content: [az webapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by giovannifl** [comment]
It seems other people reported issues related to how import appsettings using a JSON file:
https://github.com/Azure/azure-cli/issues/15680
https://github.com/Azure/azure-cli/issues/8985
https://github.com/Azure/azure-cli/issues/7245

**Comment by Kotasudhakarreddy** [comment]
@giovannifl This is because the actual path of your Json file is incomplete. Please try the same command by passing complete path where you Json file is present.

**Comment by Kotasudhakarreddy** [comment]
@giovannifl did you try with the full path as suggested.

**Comment by Kotasudhakarreddy** [comment]
closing due to lack of response. Please file a new issue if this is still a problem.
