### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by oakeyc** [Azure/azure-cli#1837]
az storage container metadata update -n vhds --metadata "a=1" --if-modified-since 2018-01-01T00Z 

The condition specified using HTTP conditional header

**Comment by derekbekoe** [comment]
@tjprescott thoughts?

I guess this is related to this https://github.com/Azure/azure-cli/issues/868.

**Comment by derekbekoe** [comment]
In the storage SDK for `if-modified-since` it says:

> Specify this header to perform the operation only
            if the resource has been modified since the specified time.

https://github.com/Azure/azure-storage-python/blob/master/azure/storage/blob/baseblobservice.py#L677

**Comment by tjprescott** [comment]
Yes, this is the error returned by the service.

**Comment by zhusijia26** [comment]
Close the issue due to the idle time. Please reopen if there is still questions.
