### ISSUE TITLE
az devops project create --name throws a false error after creating the project 

### ISSUE THREAD

**Issue by manu-kanwarpal** [Azure/azure-cli#18376]
When running az devops project create --name via an Azure DevOps CLI, it creates the project, but returns the following error, even though the account used for creating the project is added as a project administrator on creation:

https://dev.azure.com/ai-factory-azure/ai-factory-bootstrap/_build/results?buildId=35&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=96d51190-c773-5e24-6d77-f5dbb8477180&l=14

This is making the pipeline step fail, even though it has not actually failed. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce3c1e46-6a16-19f1-ee37-0ac9e783e64a
* Version Independent ID: 0172eade-f91a-d284-51b0-804cf9d4c327
* Content: [az devops project](https://docs.microsoft.com/en-us/cli/azure/devops/project?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/devops/project.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/devops/project.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
Please reopen if you still need assistance, also please add details of the error, others will not have access to your project
