### ISSUE TITLE
Data model not complete due to version is too low for azure-mgmt-applicationinsights

### ISSUE THREAD

**Issue by ECNUJason** [Azure/azure-cli#18378]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Since azure-cli is depends on azure-mgmt-applicationinsights with version 0.1.1 as of 2021-06-07, and ```connection_string``` is not available from the data model.

**To Reproduce**
```
from azure.mgmt.applicationinsights import ApplicationInsightsManagementClient
// .... omit some codes
appinsights_client = get_mgmt_service_client(cli_ctx, ApplicationInsightsManagementClient)
appinsights = appinsights_client.components.get(resource_group, name)
// then connection_string is not available from appinsights
```

**Expected behavior**
```connection_string``` is an attribute of ```appinsights```

**Environment summary**

1. Win10
2. python 3.9 with virutal env
    - install python
    - install pip
    - pip install virtualenv
    - pip install virtualenvwrapper-win
    - python -m venv '/path/to/env/folder'
    - .\Scripts\Activate.ps1
    - Git clone : https://github.com/Azure/azure-cli-extensions
    - pip install azure-cli
    - pip install azdev
    - azdev setup -r .\azure-cli-extensions\
    - azdev extension add spring-cloud
3. Then refer to "To Reproduce" section above

**Additional context**

**Comment by yonzhan** [comment]
monitor
