### ISSUE TITLE
Allow specifying the SSL certificate name in `az network application-gateway create`

### ISSUE THREAD

**Issue by aelij** [Azure/azure-cli#18375]
**Is your feature request related to a problem? Please describe.**
When using `az network application-gateway create` with the `--key-vault-secret-id` parameter (and perhaps with other cert parameters), the deployment creates an SSL certificate (under `sslCertificates`) with the name `<app-gateway-name>SslCert`, which is inconvenient for repeatable deployments.

**Describe the solution you'd like**
Allow specifying the name, e.g. using `--ssl-certificate-name`.

**Comment by yonzhan** [comment]
network
