### ISSUE TITLE
Please provide realistic examples 

### ISSUE THREAD

**Issue by durayakar** [Azure/azure-cli#18385]
Would you be kind enough to provide an example for adding and updating an HTTPS listener? 

The existing example is practically useless for any production use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dce00db-c8d7-9b93-7ac8-114a500a6a34
* Version Independent ID: 14a03192-a30b-d273-fa11-32413868a5fa
* Content: [az network application-gateway http-listener](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/http-listener?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/application-gateway/http-listener.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/application-gateway/http-listener.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Please follow the tests as examples. Thanks.
https://github.com/Azure/azure-cli/blob/d614fdd77ab5df5739f40a2411cae0924fee1b9b/src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py#L1033-L1123
