### ISSUE TITLE
Get AZ Route server should do get for all ipconfigurations and return the first return one

### ISSUE THREAD

**Issue by naveenchekuri** [Azure/azure-cli#18386]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Get/Delete Az Route Server should do a GET on all ipconfigurations and use the first one instead of using hardcoded 'Default' ipconfigurations.

In this file src/azure-cli/azure/cli/command_modules/network/custom.py, we are hardcoding 'Default'

**To Reproduce**
Create Route Server using powershell. It will create hub with ipconfiguration with name "ipconfig1". 
Delete Route Server using az cli. It will delete hub with ipconfiguration with name "Default1". This will return 404 and delete success. But ip configuration "ipconfig1" is still present

**Expected behavior**
Create Route Server using powershell. It will create hub with ipconfiguration with name "ipconfig1". 
Delete Route Server using az cli. We should fetch all ipconfigurations and delete first ipconfiguration (There will always be only 1)

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
network
