### ISSUE TITLE
Package description is too long

### ISSUE THREAD

**Issue by jjaguirre394** [Azure/azure-cli#18383]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Version release notes were all included in the package description. This is causing issues with our dev pipeline in Azure DevOps as they have a limit on how long a package description can be. We have to use Azure DevOps to pull the azure-cli as it is company policy. A tracker was opened with the Azure DevOps team and they stated that this issue must be resolved by your team. The package description must not be longer than 324608 bytes. 
**To Reproduce**

Add pypi as an upstream to Azure DevOps Artifacts feed. Attempt to install the azure-cli package referencing the DevOps Artifact feed. Notice that a failure message is returned, and the package is not installed.
**Expected behavior**

The package should be downloaded and installed when referencing the DevOps artifacts feed.
**Environment summary**

**Additional context**

The issue opened with Azure DevOps can be found here: https://developercommunity.visualstudio.com/t/python-package-cannot-be-installed-from-azure-arti/1434932?from=email&viewtype=all#T-ND1442840

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by djpugh** [comment]
Yep, seeing the same thing as well - I think there are two things here (and MS support seem to be bouncing this upstream to azure-cli, which I don't think fixes the underlying problem) - https://packaging.python.org/specifications/core-metadata/#description says that software that deals with metadata *shouldn't* assume any maximum size, so technically this isn't an issue with the package itself, but with Azure DevOps Artifacts not being compliant to the spec, however, I'd suggest having the full changelog in the description is probably overkill.

**Comment by raspe88** [comment]
Is there any assumption when a release with a shortened description can be released? Will there be a quick solution by e.g. putting the changelog-part into a separate file?

This is really painful because the only solution is to pin to an older version. While it is true that software should not assume any maximum size according to the specification quoted above, software must limit the maximum size allowed to handle metadata in a secure manner - else anyone would complain about somebody not limiting it once the first attack based on that is launched.

**Comment by jjaguirre394** [comment]
We've also had to pin to the previous version, which is unfortunate as our work depends on this being the latest version. This will work for the time being, but I really hope a solution is found soon :/ Any way to escalate this?

**Comment by yonzhan** [comment]
@jiasli to take a look at this

**Comment by adityahcl1** [comment]
> @jiasli to take a look at this
pip install for azure-cli  with Azure DevOps python feeds is still failing with Azure-CLI  version 2.24.0 and above . The package description must not be longer than 324608 bytes.

Seems the merge has removed the release history however the package description is still longer than 324608 bytes .

**Comment by jiasli** [comment]
The change will take effect in the [next release on 07/06/2021](https://github.com/Azure/azure-cli/milestone/107).

**Comment by adityahcl1** [comment]
@jiasli  : - Thanks for the update.

**Comment by jiasli** [comment]
We have released `azure-cli` 2.26.0: https://pypi.org/project/azure-cli/. The history notes are now moved to a hyperlink to https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli instead. Please let us know if the problem is solved.
