### ISSUE TITLE
cli output case varies between resource types

### ISSUE THREAD

**Issue by ausfestivus** [Azure/azure-cli#18391]
**Describe the bug**
The return value displayed by the CLI has varying case formatting, depending on which resource is being queried.

**To Reproduce**
* deploy a vNet and Subnet with a Key Vault and Storage Account endpoint in the subnet
* deploy a Storage Account, set network access to deny by default
* deploy a Key Vault, set network access to deny by default
* Configure the network access for the SA and the KV to allow access from the Subnet in the vNet you created above

Run the following two azure-cli commands:

`az storage account network-rule list --account-name mysaname --resource-group myRgName --query 'virtualNetworkRules[].virtualNetworkResourceId' -o tsv`

`az keyvault network-rule list --name myKvName --resource-group myRgName --query 'virtualNetworkRules[].id' -o tsv`

Inspect the different casing on the output values.

Output from the storage account `network-rule list` command:
`/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/myRgName/providers/Microsoft.Network/virtualNetworks/myVnetName/subnets/mySubnetName`

Output from the key vault `network-rule list` command:
`/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourcegroups/myrgname/providers/microsoft.network/virtualnetworks/myvnetname/subnets/mysubnetname`

**Expected behavior**
The displayed case of the resource should match what is actually configured by the user. The CLI must not modify the casing of any output that contains user entered values.

**Environment summary**
```
macOS-11.4-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.24.2

Extensions:
azure-devops 0.18.0
resource-graph 1.1.0
subscription 0.1.4
account 0.2.1
db-up 0.1.13
```

**Additional context**

The commands being run are part of a bash script. I am running a match on the cli output against the vNet name (myVnetName). This is to determine if the network rule is configured or not.

My bash script confirms the rule is in place on the Storage Account because the casing of the vNet name (myVnetName), matches what is configured on the Storage Account. The same command on the Key Vault, outputs the vNet name as `myvnetname` and my script indicates that the vNet access rule is *NOT* configured on the Key Vault. This occurs because the bash script is comparing `myVnetName` to `myvnetname` and because the case is different it says the names dont match.

Sure, I could run my match using lowercase or case-insensitive but this would be incorrect. The vNet name is actually `myVnetName`. The Azure cli has changed the casing on the output for an unknown reason. Please dont change user data/values. Case matters.

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by ausfestivus** [comment]
@yonzhan can I suggest this get tagged as a Key Vault issue? It's clear that the it is the code related to Key Vault that is mangling the case on the output.

It also raises the question of how many other azure cli commands are mangling the casing on outputs.

**Comment by yonzhan** [comment]
@evelyn-ys will check whether the casing is from server side.

**Comment by evelyn-ys** [comment]
The converting is from server side, CLI doesn't make any change😥

**Comment by jlichwa** [comment]
@ausfestivus our service is case insensitive and it will accept any value. It is by design

**Comment by ausfestivus** [comment]
Im going to have to dispute the closure here with "working as designed".

The AKV service is case insensitive.
The SA service is case sensitive.

The issue here is not that AKV is case insensitive and *SHOULD* be made to be case sensitive. The issue here is that the Azure platform is inconsistent with its case sensitivity wrt to its services.

The fact that I, as an operator/coder of the platform, need to be aware which service is or isn't case sensitive or case insensitive is a terrible customer/developer experience. Why does MS want to make my life harder? Why does MS think its okay to force developers to have to code around the inconsistent casing decisions between services?

At the risk of sounding like Im MS bashing here, I want to point out that MS has a long history of making poor decisions regarding case sensitivity in it's products. It's disappointing to see that the Azure product teams don't seem to care that this is a problem for their customers.
