### ISSUE TITLE
az ml should be "preview" not "experimental"

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azure-cli#18390]
## Describe the bug

`az ml` should be "preview" not  "experimental" 

**Command Name**
`az ml -h`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ml -h`

## Environment Summary
```
macOS-11.2.3-x86_64-i386-64bit
Python 3.8.9
Installer: HOMEBREW

azure-cli 2.22.1 *

Extensions:
ml 2.0.0a1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by paulshealy1** [comment]
Thanks for the feedback! We'll change the CLI to preview in an upcoming release.
