### ISSUE TITLE
Unable to set secret = "$$" through azure cli command

### ISSUE THREAD

**Issue by tamathew** [Azure/azure-cli#18409]
The below command returns following output with a value=64144 instead of "$$"

az keyvault secret set --name "SECRET-NAME" --vault-name "KV-NAME" --value "$$"

{
  "attributes": {
    "created": "2021-06-09T03:00:21+00:00",
    "enabled": true,
    "expires": null,
    "notBefore": null,
    "recoveryLevel": "Purgeable",
    "updated": "2021-06-09T03:00:21+00:00"
  },
  "contentType": null,
  "id": "https://XXXXXX.vault.azure.net/secrets/SECRET-NAME/db6887278202471583c40e43ab78670b",
  "kid": null,
  "managed": null,
  "name": "SECRET-NAME",
  "tags": {
    "file-encoding": "utf-8"
  },
  "value": "64144"
}

**Comment by tamathew** [comment]
Found a work around . Escape the $ value with \$

**Comment by yonzhan** [comment]
@tamathew shall we close this since you have already fixed by yourself?

**Comment by evelyn-ys** [comment]
@tamathew `\` is needed before `$` if you want to pass the original `$` or else it will be parsed before passing to Azure CLI.
