### ISSUE TITLE
Unable to use Microsoft.Sql/servers as type for az network private-endpoint-connection list

### ISSUE THREAD

**Issue by liamejdunphy** [Azure/azure-cli#18403]
Documentation on listing private endpoints suggests that Microsoft.Sql/servers can be used as a valid type argument, but when used with the cli I get the following back:

![image](https://user-images.githubusercontent.com/17970132/121223717-b9e31180-c87f-11eb-92ba-e4593cfc900a.png)

Using az version 2.24.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e4446d-f721-eb1f-2d78-c8e6da619051
* Version Independent ID: e53bdc70-7750-b452-56b8-1caa2d938f0a
* Content: [az network private-endpoint-connection](https://docs.microsoft.com/en-US/cli/azure/network/private-endpoint-connection?view=azure-cli-latest#az_network_private_endpoint_connection_list)
* Content Source: [latest/docs-ref-autogen/network/private-endpoint-connection.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/private-endpoint-connection.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Already supported in this PR https://github.com/Azure/azure-cli/pull/18268. It will be available in version 2.25.0
