### ISSUE TITLE
The keyname of `az cognitiveservices account keys regenerate`cannot be used

### ISSUE THREAD

**Issue by BigCat20196** [Azure/azure-cli#18407]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When I execute this command, I get the following error.
`az cognitiveservices account keys regenerate -n {sname} -g {rg} --key-name key1`

> E           azure.core.exceptions.HttpResponseError: (BadRequest) The key name 'key1' is invalid. Valid values are 'Key1' and 'Key2'.

However, when I use `Key1` as the parameter value, it still reports an error.

> Did you mean 'key1' ?
> TRY THIS:
> az cognitiveservices account keys regenerate --name myresource -g cognitive-services-resource-group --key-name key1 Get new keys for resource.

So, please tell me what value should be used as the parameter of the key name?

**To Reproduce**

`az cognitiveservices account create -n {sname} -g {rg} --kind {kind} --sku {sku} -l {location} --yes`

`az cognitiveservices account keys regenerate -n {sname} -g {rg} --key-name key1`

**Expected behavior**

Command is executed successfully.

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by BigCat20196** [comment]
May have been resolved, temporarily closed.
