### ISSUE TITLE
ADF cli fails updating repository

### ISSUE THREAD

**Issue by simondmorias** [Azure/azure-cli#18402]
Command:
```
az datafactory configure-factory-repo --factory-vsts-configuration xxx
```

The above fails when you run as a service principal with the error:
```
 (AuthorizationFailed) The client 'xxx' with object id 'xxx does not have authorization to perform action 'Microsoft.DataFactory/locations/configureFactoryRepo/action' over scope '/subscriptions/xxx' or the scope is invalid. If access was recently granted, please refresh your credentials
```

This appears to be because the service principal does not have permission to access the azure devops repo. According to https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/authentication-guidance?view=azure-devops Azure DevOps does not support Service principals using the REST API.

However, if I deploy a similar request via an ARM template it works. So the underlying REST API for ADF must be able to support validating these details later? It would be good for the CLI to have a similar feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da110bf9-e979-a0fd-65b0-55ac6cae2077
* Version Independent ID: d2a9d97c-07f7-108c-06cd-8913c89bd041
* Content: [az datafactory](https://docs.microsoft.com/en-us/cli/azure/datafactory?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/datafactory.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/datafactory.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
data factory

**Comment by shawnxzq** [comment]
@Juliehzl Please let us know what service team can do with this, thanks!

**Comment by shawnxzq** [comment]
@Juliehzl Any update on this?

**Comment by JP-Ellis-KPMG** [comment]
I have run into this issue myself recently.

We have some users who have privileges restricted to specific resource groups and do not have access to the subscription as a whole. These users are able to configure their Data Factory in their resource group perfectly fine if done through the web interface, but the corresponding configuration through the `az datafactory configure-factory-repo` fails with the error:

```text
ERROR: (AuthorizationFailed) The client 'email@example.com' with object id '[redacted]' does not have authorization to perform action 'Microsoft.DataFactory/locations/configureFactoryRepo/action' over scope '/subscriptions/[redacted]' or the scope is invalid.
```

**Comment by navba-MSFT** [comment]
@yonzhan This is an old thread (2021), so removing the CXP attention label and adding Service attention label.

**Comment by navba-MSFT** [comment]
@Jingshu923, @zhangyd2015, @Frey-Wang Could you please look into this and provide an update ? Thanks in advance.

**Comment by Frey-Wang** [comment]
@navba-MSFT , Is the package updated to the latest version? Could you please help with the repro and provide the debug logs with `--debug` tag?

**Comment by navba-MSFT** [comment]
@simondmorias Could you please follow the suggestion and next action plan in the above comment and provide us an update ? Thanks.

**Comment by JP-Ellis-KPMG** [comment]
While the original author did not provide the necessary information, I did provide the information above. The "no-recent-activity" tag should be removed.

**Comment by JP-Ellis-KPMG** [comment]
> While the original author did not provide the necessary information, I did provide the information above. The "no-recent-activity" tag should be removed.

**Comment by navba-MSFT** [comment]
@JP-Ellis-KPMG Could you please see the suggestion provided [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/6484#issuecomment-886626279) and check if that helps ?

Also did you try to create a custom role for your above service principle with action `'Microsoft.DataFactory/locations/configureFactoryRepo/action' ` and try ? Awaiting your reply.

**Comment by JP-Ellis-KPMG** [comment]
> @JP-Ellis-KPMG Could you please see the suggestion provided [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/6484#issuecomment-886626279) and check if that helps ?
> 
> Also did you try to create a custom role for your above service principle with action `'Microsoft.DataFactory/locations/configureFactoryRepo/action' ` and try ? Awaiting your reply.

Thanks @navba-MSFT  for pointing out the suggestion from the Terraform repository.

One question does remain: Why is it the case that users can configure the Data Factory through the web interface, but not through the CLI then?
