### ISSUE TITLE
Add "port" support via az ssh vm

### ISSUE THREAD

**Issue by tiarnaigh** [Azure/azure-cli#18410]
[Enter feedback here]
Would it be possible to add support to "az ssh vm" whereby the user can specify a custom port of the remote ssh VM? Currently, this seems to be limited to TCP:22 only by default and I have not found a way to set anything other than TCP:22.

i.e. I have a requirement to do something like the below:
az ssh vm --ip hostname.domainname.int --port 666

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29a90500-fe23-5ae5-caad-9b897ed5ac6c
* Version Independent ID: 588d5bec-fcbe-75f9-5206-616746e61d5f
* Content: [az ssh](https://docs.microsoft.com/en-us/cli/azure/ssh?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ssh.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ssh.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ssh

**Comment by jiasli** [comment]
The port support is added by https://github.com/Azure/azure-cli-extensions/pull/3698.

**Comment by Stateofminf** [comment]
8080
