### ISSUE TITLE
Incorrect examples

### ISSUE THREAD

**Issue by andyr8939** [Azure/azure-cli#18426]
The examples have 
```
--https-redirect False
```

But you have to use Enabled or Disabled for it to work, False is not a valid value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccf1bf82-30bc-e14b-f06e-7af010c876a7
* Version Independent ID: d2de028a-6ae4-0bc3-9ee9-5cf75d95f7db
* Content: [az afd route](https://docs.microsoft.com/en-us/cli/azure/afd/route?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/afd/route.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/afd/route.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by t-bzhan** [comment]
The content is correct now.
