### ISSUE TITLE
[Network] Network commands which add child resources are not goal seeking

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#1843]
If you issue an load balancer rule create twice, the second time it will fail:

`az network lb rule create -g lamp-sample-stack -n http-rule --backend-pool-name lampScaleSetbepool --backend-port 80 --frontend-ip-name LoadBalancerFrontEnd --frontend-port 80 --lb-name lampScaleSetlb --protocol Tcp`

The second time you will receive:
`Cannot parse the request.`

**Comment by tjprescott** [comment]
This behavior is not limited to load balancer rule. You'll get this many network commands that add child resources because the SDK will fail to serialize them.
