### ISSUE TITLE
Azure Database for MySQL flexible server - server not shown in CLI

### ISSUE THREAD

**Issue by dg-tgsw** [Azure/azure-cli#18434]
## Describe the bug

**Command Name**
`az mysql server list`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az mysql server list`

## Expected Behavior
List one server named "flexdisk"

## Environment Summary
```
Linux-5.4.0-1048-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.24.2

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```
## Additional Context
The server "flexdisk" is shown in the azure portal under the resource-group thindiskWebL, but not via CLI.
???

**Comment by yonzhan** [comment]
route to service team

**Comment by dg-tgsw** [comment]
... I noticed that the correct syntax is "az mysql flexible-server list"
This shows my servers....
