### ISSUE TITLE
`az bicep build` doesn't generate any output with the `--stdout` flag

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-cli#18437]
## Describe the bug

**Command Name**
`az bicep build`

When using the `--stdout` flag, warning diagnostics are displayed, but there is no JSON output. There is also no JSON file generated as would be the case without this flag.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az bicep build --file {} --stdout`

## Environment Summary
```
macOS-11.2.3-x86_64-i386-64bit
Python 3.8.9
Installer: HOMEBREW

azure-cli 2.22.0 *

```

**Comment by shenglol** [comment]
@zhoxing-ms mind assigning this to me? I'm looking into this now.

**Comment by yonzhan** [comment]
@shenglol assigned
