### ISSUE TITLE
Error when creating VM

### ISSUE THREAD

**Issue by EinsteinUnicorn** [Azure/azure-cli#18444]
## Describe the bug

**Command Name**
`az vm create`

**Errors:**
```
The password length must be between 12 and 72. Password must have the 3 of the following: 1 lower case character, 1 upper case character, 1 number and 1 special character.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm create --resource-group {} --name {} --location {} --image {} --tags {} --authentication-type {} --admin-user {}`

## Environment Summary
```
Linux-5.4.0-1048-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.24.2

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
Compute

**Comment by Juliehzl** [comment]
Hi @EinsteinUnicorn, you need to specify admin password as required:
- The password length must be between 12 and 72. 
- Password must have the 3 of the following: 1 lower case character, 1 upper case character, 1 number and 1 special character.
