### ISSUE TITLE
Can No Longer Delete FW Rule Collection

### ISSUE THREAD

**Issue by michaelschmit** [Azure/azure-cli#18442]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
This command successfully shows the details of a collection:
az network firewall application-rule collection show --resource-group [resource_group] --firewall-name [firewall_name] --collection-name [collection_name]

However if you try to run the same command but swapping show for delete, you now get a stack trace:
az network firewall application-rule collection delete --resource-group [resource_group] --firewall-name [firewall_name] --collection-name [collection_name]

The command failed with an unexpected error. Here is the traceback:
'AzureFirewallsOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/root/.azure/cliextensions/azure-firewall/azext_firewall/_util.py", line 71, in delete_func
    result = sdk_no_wait(no_wait, client.create_or_update, resource_group_name, resource_name, item).result()
AttributeError: 'AzureFirewallsOperations' object has no attribute 'create_or_update'

**To Reproduce**
az network firewall application-rule collection delete --resource-group [resource_group] --firewall-name [firewall_name] --collection-name [collection_name]

**Expected behavior**
The rule collection should be deleted and no stack trace presented.

**Environment summary**
yum install azure-cli
az --version output:
azure-cli                         2.24.2

core                              2.24.2
telemetry                          1.0.6

Extensions:
azure-firewall                    0.10.0

Python location '/usr/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

**Additional context**

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
This bug is introduced in version 0.9.1 by [PR](https://github.com/Azure/azure-cli-extensions/pull/3284). We will fix it in next firewall version. Please install previous version to workaround.

```
az extension add --name azure-firewall--version 0.9.0
```

**Comment by kairu-ms** [comment]
@00Kai0 Please have a look. Thanks.

**Comment by michaelschmit** [comment]
I was out-of-office this weekend.  I will try to down rev my extension version. This isn't a big enough deal to patch?  Seems like a pretty glaring issue.

**Comment by michaelschmit** [comment]
I down rev'ed my extension and was able to delete the FW rule collection.

**Comment by yonzhan** [comment]
@00Kai0 will help with this.

**Comment by 00Kai0** [comment]
I have created a PR: https://github.com/Azure/azure-cli-extensions/pull/3505
