### ISSUE TITLE
Show commands return zero rather than an error code

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#1845]
If show commands return zero rather than an error code when an entity does not exist, they can be used as "exists" in scripts.

This is also useful in scripts which use `set -e`, since returning non-zero in this case would cause the whole script to exit.

This also enables the following flow, which is very helpful since some of the idempotent creates take a _long_ time even when everything has already been created.
```bash
NAME=$(az vmss show -g ${RESOURCE_GROUP} -n ${NAME} --query "name" -o tsv)
if [ -z ${NAME} ]; then
    # do something with the name
else
    # do something if the entity does not exist
fi
```

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
