### ISSUE TITLE
WebApp:az staticwebapp appsettings set example needs nested example

### ISSUE THREAD

**Issue by whoiskevinrich** [Azure/azure-cli#18468]
Given the following example:
```
$ az staticwebapp appsettings list -n mySite

{
  "id": "/subscriptions/<my-subscription>/resourceGroups/my-site-rg/providers/Microsoft.Web/staticSites/mySite/config/functionappsettings",
  "kind": null,
  "location": "West US 2",
  "name": "appsettings",
  "properties": {
    "TestSetting": "TestValue"
  },
  "resourceGroup": "my-site-rg",
  "type": "Microsoft.Web/staticSites/config/functionappsettings"
}
```

How can I updated the nested property "TestSetting"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57306327-4c21-d60b-758f-e7c2a23a6b5c
* Version Independent ID: 58b831b8-dcdb-d9b3-d3df-2793ef1b2a05
* Content: [az staticwebapp appsettings](https://docs.microsoft.com/en-us/cli/azure/staticwebapp/appsettings?view=azure-cli-latest#az_staticwebapp_appsettings_set)
* Content Source: [latest/docs-ref-autogen/staticwebapp/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/staticwebapp/appsettings.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by parth21999** [comment]
Waiting for azure-mgmt-web sdk update. Blocked until update.
