### ISSUE TITLE
Need to preserve old  zip files after deployment

### ISSUE THREAD

**Issue by Obaid1991** [Azure/azure-cli#18465]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I want to preserve the old zip files after a new deployment using Azure CLI Config-Zip command, as I want 2-4 different zip files to be present under site/wwwroot/webapps.

What's happening is that after deploying 2nd zip file, I cannot see the first zip file under webapps folder.

Any help would be appreciated

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
This is not specific to CLI - since CLI doesn't control what zipfiles are stored on the Kudu site,, please open issue on Kudu project.
