### ISSUE TITLE
Consider making sample JSON in command agree with samples DTDL

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-cli#18461]
This is very much a for consideration only, because there's pros/cons to what we have today and what I'm suggesting.

In the page we have this blurb.  
```script
az iot hub digital-twin invoke-command --command-name reboot -n {iothub_name} -d {device_id} --payload '{"delay":5}'
```

This does indeed successfully send over JSON.  But assuming we're trying to have that JSON map to what's in the [sample](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/samples/TemperatureController.json) we use all over teh pace, this actually isn't what we want.  We'd only want the 5 to be sent across.

Now the pro of leaving as-is is that the JSON as in the document is much more clearly JSON.  5 is of course perfectly reasonable JSON, but it doesn't scream out as JSON.  The pro of changing to just be 5 is that the line here maps to the tempController that lives everewhere else with how device / IoT Explorer send it, which is NOT including the "delay" part from DTDL.

A third approach could be to change the JSON we're sending to be like '{"SomethingElse": 5}.  So it still pops out as JSON, but someone coming to this from the TempController sample won't think they can copy/paste and be done.

I don't have strong opinions on this.  It caused me to trip up momentarily when running sample, though someone new to DTDL might take them longer so I want tocall out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ccfa91-20a2-5812-3d58-119f75c271de
* Version Independent ID: f7d0bbc4-2cd7-c4ed-0d63-b1014afb344c
* Content: [az iot hub digital-twin](https://docs.microsoft.com/en-us/cli/azure/iot/hub/digital-twin?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/iot/hub/digital-twin.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/iot/hub/digital-twin.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by Elsie4ever** [comment]
update help text in [pr](https://github.com/Azure/azure-iot-cli-extension/pull/605), will be available in next release
