### ISSUE TITLE
Exists should return 'true' or 'false'

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#1846]
If an exists command is available for a resource (might not be needed if one were to use show), the only two valid returns should be 'true' or 'false'.

Currently, `az group exists` returns 'true' when exists and empty when it doesn't exist. By doing this, one can't say `if [ $(az group exists -n group-that-doesnt-exit) == 'true' ]` since that would cause a `-bash: [: ==: unary operator expected` to be thrown when null is returned.

**Comment by johanste** [comment]
Related to #1952.

**Comment by derekbekoe** [comment]
For `az group exists`, it looks like it behaves as expected now?

```
$ sudo docker run -it azuresdk/azure-cli-python:0.1.9
bash-4.3# az login -u <USER> -p <PASS>
bash-4.3# az group exists -n thisexists
true
bash-4.3# az group exists -n notthere
false
```

This command directly calls a method in the SDK. The SDK handles this as it checks for a 204 or 404 from the service - https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-resource/azure/mgmt/resource/resources/operations/resource_groups_operations.py#L160.

Looking into the other exists commands now.

**Comment by derekbekoe** [comment]
The other `exists` commands are in storage module and they also have true/false results.

I suspect the `az group exists` issue was fixed by these two PRs.
https://github.com/Azure/azure-cli/pull/1854
https://github.com/Azure/azure-cli/pull/1913
