### ISSUE TITLE
az login fails with "find_subscriptions_on_login() got an unexpected keyword argument 'scopes'"

### ISSUE THREAD

**Issue by qetza** [Azure/azure-cli#18477]
## Describe the bug
On a fresh installation of az cli 2.24.1 when running the `az login` command i get an error.

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
find_subscriptions_on_login() got an unexpected keyword argument 'scopes'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 152, in login
TypeError: find_subscriptions_on_login() got an unexpected keyword argument 'scopes'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.24.1 *

```

**Comment by galewis2** [comment]
Ditto, having the same problem on 2.24.2, on a CentOS Docker container

**Comment by qetza** [comment]
I've uninstall 2.24.1 and reinstall 2.22.1 and i have no issues.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
`find_subscriptions_on_login` does take `scopes` which is added in https://github.com/Azure/azure-cli/pull/17778:

https://github.com/Azure/azure-cli/blob/d1bcf34a3cff63c32a045024ca2cc3a842fd1283/src/azure-cli-core/azure/cli/core/_profile.py#L169-L175

I installed the latest 2.24.2 but can't repro this issue. 

Could you follow these steps and try to install again? (copied from https://github.com/Azure/azure-cli/issues/17986#issuecomment-834607007)

1. Go to **Control Panel > Uninstall a program** , uninstall **Microsoft Azure CLI** 
2. Delete `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2`
3. [Install the latest Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) from scratch

**Comment by jiasli** [comment]
@galewis2, we haven't received other users reporting this issue. Could you share the commands you used to run the docker image and install Azure CLI?

**Comment by qetza** [comment]
Hi @jiasli,
Manually deleting the folder `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2` after uninstalling did the trick.
Thanks

**Comment by CharbelHanna** [comment]
hello, apparently the issue is being resolved by deleting the CLI2 folder as stayed above.

however, i still did not quit understand the core reason of the problem especially since i have tried to reproduce the issue by upgrading the CLI on another machine however the problem did not occur

Thank you for support

Regards;
Charbel HANNA

**Comment by jiasli** [comment]
> however, i still did not quit understand the core reason of the problem especially since i have tried to reproduce the issue by upgrading the CLI on another machine however the problem did not occur

Me neither. This seems to be some problem with the Windows MSI installer where it fails to update the `pyc` files correctly.
