### ISSUE TITLE
Keyvault - add network-rule can be added for the same CIDR (without suffix)

### ISSUE THREAD

**Issue by LotteVoorhorst** [Azure/azure-cli#18479]
**Describe the bug**
When calling the following cli command: 

`az keyvault network-rule add --name {keyvaultname} --resource-group {resource-group} --ip-address {cidr} `

it seems that you can keep adding the same ip-address over and over again when not specifiying the cidr suffix, e.g. **123.123.2.1** instead of **123.123.2.1/32**.

**To Reproduce**
Call the CLI command with CIDR without a suffix multiple times.

**Expected behavior**
Expected behaviour is that the CIDR should not be added multiple times if it's the same cidr (with or without a suffix). 

**Environment summary**
azure-cli                         2.24.1 *

**Comment by yonzhan** [comment]
keyvault
