### ISSUE TITLE
@ramirezalfredo the customer can add this step for Ubuntu to stick to azure-cli 2.23.0 no matter what version is on the image. The installation takes about 40 seconds.

### ISSUE THREAD

**Issue by Deliriousafflictionz5150** [Azure/azure-cli#18472]
@ramirezalfredo the customer can add this step for Ubuntu to stick to azure-cli 2.23.0 no matter what version is on the image. The installation takes about 40 seconds.
```
sudo apt-get remove azure-cli
curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
sudo apt-get update
sudo apt-get install azure-cli=2.23.0-1~$(lsb_release -cs)
```

_Originally posted by @miketimofeev in https://github.com/actions/virtual-environments/issues/3508#issuecomment-852807274_

**Comment by yonzhan** [comment]
Installation

**Comment by ramirezalfredo** [comment]
Correct @Deliriousafflictionz5150, it is a good workaround but not ideal. It is what customer applied while the updated image is released. Thanks!

**Comment by jiasli** [comment]
Original issue has been fixed by https://github.com/Azure/azure-cli/pull/18326
