### ISSUE TITLE
az deployment * create --confirm-with-what-if asks for confirmation when nothing is changed

### ISSUE THREAD

**Issue by alexpilon666** [Azure/azure-cli#18481]
**Describe the bug**
When using any `az deployment * create` command with `--confirm-with-what-if`, if there are no changes (excluded using `--what-if-exclude-change-types NoChange Ignore`), Azure CLI still asks to confirm the execution of the deployment.

**To Reproduce**
Deploy any template with `az deployment * create --confirm-with-what-if --what-if-exclude-change-types NoChange Ignore`, then deploy it again without changing anything.

**Expected behavior**
One of two things:
- Either the deployment does not ask for confirmation when "Resource changes: no change." is the what-if output
- A parameter is made available that if there is no change as the what-if output, then do not ask for confirmation and simply proceed

**Environment summary**
Azure CLI v2.24.2 running in CentOS7 & Ubuntu 20.04LTS via WSL2, and in CentOS7 via Docker container on WSL2
OS: Windows 10 Enterprise 20H2

**Additional context**
This is mostly a problem because we have a lot of templates, and a good chunk of them are multistage templates, i.e.: We will run `az deployment * create` with a parameter `-p stage=X` via a custom Bash script that will trigger different sections of our templates based on the stage number. 
This is needed because let's say Stage 2 might create Resource A, which we then need to get some information in Bash to do some manipulations outside of the ARM template OR to pass as additional parameters for later stages (i.e.: Deploy a storage account, use Azure CLI to fetch the Connection String, sanitise it, and pass it as a deployment parameter for a later stage). If those manipulations are not done, then Stage 3 resources will fail or not work properly.

We have up to 4 stages in our templates currently, and sometimes only one of the stages might have changes. Needing to confirm that nothing is being changed every single time is not really ideal in terms of user experience for the rest of our team.

And because of the above requirements, switching to using `az deployment * what-if` is not an option, because resources that would've been created by Stage X won't be available for a later stage, thus failing it.

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
@shenglol Could you please take a look at this issue~

**Comment by shenglol** [comment]
My concern is that there are people who would expect it to ask for confirmation as a guard regardless whether there are changes or not. Adding a new parameter to allow a deployment to process if there's no change seems reasonable, but I'd like to hear @alex-frankel 's thoughts on this before committing to implementing it.

**Comment by alex-frankel** [comment]
>people who would expect it to ask for confirmation as a guard regardless whether there are changes or not

+1

>A parameter is made available that if there is no change as the what-if output, then do not ask for confirmation and simply proceed

I can see us potentially doing this one. At that point it would be an opt-in capability:

```azcli
az deployment * create -f main.bicep -c --proceed-if-no-changes
```

**Comment by alexpilon666** [comment]
@alex-frankel , @shenglol , adding that kind of `--proceed-if-no-changes` opt-in capability would be perfect for our needs, and most likely the needs of others as well.

**Comment by shenglol** [comment]
Sounds good. I've added a task to our backlog to track this and will be working on it later.

**Comment by alex-frankel** [comment]
@shenglol - should we try to do this one at the same time? https://github.com/Azure/bicep/issues/2923#issuecomment-855191455

**Comment by shenglol** [comment]
Yeah we should.
