### ISSUE TITLE
Update from CoreOS to Flatcar linux for `az vm images list`

### ISSUE THREAD

**Issue by jamesc** [Azure/azure-cli#18484]
As CoreOS is deprecated and there is no Image in the marketplace any more, update to use Flatcar linux instead in the list of available images.

There is already a PR (https://github.com/Azure/azure-rest-api-specs/pull/14796) in the API Specs repo which holds the master list.  We need to update our local fallback copy (https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_alias.py) so that this work in environments where `endpoint_vm_image_alias_doc` is not set.

**Comment by jamesc** [comment]
Once this is merged we should also update the example in https://docs.microsoft.com/en-us/azure/virtual-machines/linux/cli-ps-findimage

**Comment by yonzhan** [comment]
Add @dbradish-microsoft to help with updating the example in example in https://docs.microsoft.com/en-us/azure/virtual-machines/linux/cli-ps-findimage once this is merged.
