### ISSUE TITLE
Some parameters don't work. 

### ISSUE THREAD

**Issue by bigkangji** [Azure/azure-cli#18488]
Hi All,

I run the command and got the error like this - I masked my information : 

$ az storage blob copy start --account-key ***** --account-name **** --destination-blob test.zip --destination-container testtarget --rehydrate-priority --source-uri **** --tier Cool

**unrecognized arguments: --rehydrate-priority --tier Cool**

"--rehydrate-priority" & "--tier" are listed in this page as optional parameters.
The source blob is a block blob in a general purpose v2, standard storage account. 

Regards
Jisun
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b4e73a9-187f-ad77-3f22-52e7c3edd149
* Version Independent ID: e58b4f05-7bbc-fcb0-ee55-571ee68bd3e7
* Content: [az storage blob copy](https://docs.microsoft.com/en-us/cli/azure/storage/blob/copy?view=azure-cli-latest#az_storage_blob_copy_start)
* Content Source: [latest/docs-ref-autogen/storage/blob/copy.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/blob/copy.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by Juliehzl** [comment]
Supported in https://github.com/Azure/azure-cli/pull/18170. Please check your azure cli version and make sure it >=2.25.0. To upgrade azure cli,  you could download manually according to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli or use `az upgrade` for automatically upgrade.
