### ISSUE TITLE
az netappfiles account ad add -> ERROR: (BadRequest) An invalid value '' was received for KeySource"

### ISSUE THREAD

**Issue by allanmo79** [Azure/azure-cli#18480]
when running "az netappfiles account ad add" i have suddenly started to get "ERROR: (BadRequest) An invalid value '' was received for KeySource"

Update: if i use rest API it works fine if i add the encryption property: https://docs.microsoft.com/en-us/rest/api/netapp/accounts/create-or-update 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5545ff44-382e-bd41-4b15-b37e7a7196b7
* Version Independent ID: 750bdcdf-1c28-db49-96aa-e09f5498ca34
* Content: [az netappfiles account ad](https://docs.microsoft.com/en-us/cli/azure/netappfiles/account/ad?view=azure-cli-latest#az_netappfiles_account_ad_add)
* Content Source: [latest/docs-ref-autogen/netappfiles/account/ad.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/netappfiles/account/ad.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by allanmo79** [comment]
Fixed with new az cli version:
 
- azure-cli                         2.25.0

Just update Cli to new version and problem has been resolve, version before upgrade 2.24.0
