### ISSUE TITLE
inconsistent version metadata in python package azure-cli==2.25.0

### ISSUE THREAD

**Issue by dserdyuk** [Azure/azure-cli#18499]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
It looks like inconsistent python package metadata causes pip to download all available versions of multiple dependencies which timeouts in CI tracks.  

**To Reproduce**
pip install -U azure-cli==2.25.0

**Expected behavior**

**Environment summary**

**Additional context**
Workaround is to install previous release 
pip install -U azure-cli==2.24.2

**Comment by dserdyuk** [comment]
part of bash script

> 
> pip3 install --disable-pip-version-check virtualenv -q
> echo "Installing python virtual environment for deployment scripts..."
> virtualenv -p python3 ~/.gdc-env -q
> source ~/.gdc-env/bin/activate
> ~/.gdc-env/bin/python -m pip install --no-input --upgrade pip
> ~/.gdc-env/bin/pip install -r $WORKDIR/scripts/requirements.txt --no-input




 Logs:

Installing python virtual environment for deployment scripts...
Collecting pip
  Using cached pip-21.1.2-py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.4
    Uninstalling pip-20.2.4:
      Successfully uninstalled pip-20.2.4
Successfully installed pip-21.1.2
Collecting requests~=2.24.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting azure-storage-blob
  Using cached azure_storage_blob-12.8.1-py2.py3-none-any.whl (345 kB)
Collecting azure-cli
  Using cached azure_cli-2.25.0-py3-none-any.whl (2.2 MB)
Collecting databricks-api~=0.5.1
  Using cached databricks_api-0.5.1-py2.py3-none-any.whl (6.1 kB)
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting retry
  Using cached retry-0.9.2-py2.py3-none-any.whl (8.0 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting databricks-cli<0.13.0,>=0.12.0
  Using cached databricks_cli-0.12.2-py3-none-any.whl
Collecting tabulate>=0.7.7
  Using cached tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting six>=1.10.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting tenacity>=6.2.0
  Using cached tenacity-7.0.0-py2.py3-none-any.whl (23 kB)
Collecting click>=6.7
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Collecting msrest>=0.6.18
  Using cached msrest-0.6.21-py2.py3-none-any.whl (85 kB)
Collecting azure-core<2.0.0,>=1.10.0
  Using cached azure_core-1.15.0-py2.py3-none-any.whl (138 kB)
Collecting cryptography>=2.1.4
  Using cached cryptography-3.4.7-cp36-abi3-macosx_10_10_x86_64.whl (2.0 MB)
Collecting cffi>=1.12
  Using cached cffi-1.14.5-cp39-cp39-macosx_10_9_x86_64.whl (177 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting requests-oauthlib>=0.5.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting isodate>=0.6.0
  Using cached isodate-0.6.0-py2.py3-none-any.whl (45 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.1-py2.py3-none-any.whl (146 kB)
Collecting azure-mgmt-redhatopenshift==0.1.0
  Using cached azure_mgmt_redhatopenshift-0.1.0-py2.py3-none-any.whl (23 kB)
Collecting azure-mgmt-privatedns~=1.0.0
  Using cached azure_mgmt_privatedns-1.0.0-py2.py3-none-any.whl (43 kB)
Collecting azure-mgmt-extendedlocation~=1.0.0b2
  Using cached azure_mgmt_extendedlocation-1.0.0b2-py2.py3-none-any.whl (37 kB)
Collecting azure-mgmt-dns~=8.0.0
  Using cached azure_mgmt_dns-8.0.0-py2.py3-none-any.whl (118 kB)
Collecting azure-mgmt-iotcentral~=4.1.0
  Using cached azure_mgmt_iotcentral-4.1.0-py2.py3-none-any.whl (18 kB)
Collecting azure-mgmt-media~=3.0
  Using cached azure_mgmt_media-3.1.0-py2.py3-none-any.whl (154 kB)
Collecting websocket-client~=0.56.0
  Using cached websocket_client-0.56.0-py2.py3-none-any.whl (200 kB)
Collecting jsondiff==1.2.0
  Using cached jsondiff-1.2.0-py3-none-any.whl
Collecting azure-mgmt-devtestlabs~=4.0
  Using cached azure_mgmt_devtestlabs-4.0.0-py2.py3-none-any.whl (137 kB)
Collecting azure-mgmt-signalr~=1.0.0b2
  Using cached azure_mgmt_signalr-1.0.0b2-py2.py3-none-any.whl (71 kB)
Collecting azure-cosmos>=3.0.2,~=3.0
  Using cached azure_cosmos-3.2.0-py2.py3-none-any.whl (106 kB)
Collecting jsmin~=2.2.2
  Using cached jsmin-2.2.2-py3-none-any.whl
Collecting semver==2.13.0
  Using cached semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting azure-mgmt-kusto~=0.3.0
  Using cached azure_mgmt_kusto-0.3.0-py2.py3-none-any.whl (73 kB)
Collecting azure-mgmt-recoveryservices~=1.0.0
  Using cached azure_mgmt_recoveryservices-1.0.0-py2.py3-none-any.whl (70 kB)
Collecting javaproperties==0.5.1
  Using cached javaproperties-0.5.1-py2.py3-none-any.whl (19 kB)
Collecting packaging~=20.9
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting azure-mgmt-web~=2.0.0
  Using cached azure_mgmt_web-2.0.0-py2.py3-none-any.whl (2.3 MB)
Collecting azure-cli-core==2.25.0
  Using cached azure_cli_core-2.25.0-py3-none-any.whl (184 kB)
Collecting azure-mgmt-billing==1.0.0
  Using cached azure_mgmt_billing-1.0.0-py2.py3-none-any.whl (89 kB)
Collecting azure-mgmt-keyvault==9.0.0
  Using cached azure_mgmt_keyvault-9.0.0-py2.py3-none-any.whl (312 kB)
Collecting azure-mgmt-search~=8.0
  Using cached azure_mgmt_search-8.0.0-py2.py3-none-any.whl (71 kB)
Collecting antlr4-python3-runtime~=4.7.2
  Using cached antlr4_python3_runtime-4.7.2-py3-none-any.whl
Collecting azure-mgmt-eventgrid==9.0.0
  Using cached azure_mgmt_eventgrid-9.0.0-py2.py3-none-any.whl (178 kB)
Collecting azure-mgmt-cognitiveservices~=6.3.0
  Using cached azure_mgmt_cognitiveservices-6.3.0-py2.py3-none-any.whl (40 kB)
Collecting azure-mgmt-loganalytics~=8.0.0
  Using cached azure_mgmt_loganalytics-8.0.0-py2.py3-none-any.whl (140 kB)
Collecting azure-identity
  Using cached azure_identity-1.6.0-py2.py3-none-any.whl (108 kB)
Collecting azure-graphrbac~=0.60.0
  Using cached azure_graphrbac-0.60.0-py2.py3-none-any.whl (139 kB)
Collecting azure-mgmt-datalake-store~=0.5.0
  Using cached azure_mgmt_datalake_store-0.5.0-py2.py3-none-any.whl (88 kB)
Collecting azure-mgmt-network~=19.0.0
  Using cached azure_mgmt_network-19.0.0-py2.py3-none-any.whl (20.9 MB)
Collecting azure-mgmt-security~=0.6.0
  Using cached azure_mgmt_security-0.6.0-py2.py3-none-any.whl (229 kB)
Collecting azure-mgmt-managedservices~=1.0
  Using cached azure_mgmt_managedservices-1.0.0-py2.py3-none-any.whl (38 kB)
Collecting azure-mgmt-apimanagement~=0.2.0
  Using cached azure_mgmt_apimanagement-0.2.0-py2.py3-none-any.whl (275 kB)
Collecting azure-mgmt-servicefabricmanagedclusters~=1.0.0
  Using cached azure_mgmt_servicefabricmanagedclusters-1.0.0-py2.py3-none-any.whl (112 kB)
Collecting azure-mgmt-cosmosdb~=6.3.0
  Using cached azure_mgmt_cosmosdb-6.3.0-py2.py3-none-any.whl (281 kB)
Collecting pytz==2019.1
  Using cached pytz-2019.1-py2.py3-none-any.whl (510 kB)
Collecting azure-mgmt-rdbms~=8.1.0b4
  Using cached azure_mgmt_rdbms-8.1.0-py2.py3-none-any.whl (636 kB)
Collecting azure-datalake-store~=0.0.49
  Using cached azure_datalake_store-0.0.52-py2.py3-none-any.whl (61 kB)
Collecting azure-loganalytics~=0.1.0
  Using cached azure_loganalytics-0.1.0-py2.py3-none-any.whl (16 kB)
Collecting PyGithub==1.38
  Using cached PyGithub-1.38-py3-none-any.whl
Collecting azure-mgmt-sqlvirtualmachine~=0.5.0
  Using cached azure_mgmt_sqlvirtualmachine-0.5.0-py2.py3-none-any.whl (34 kB)
Collecting azure-mgmt-managementgroups~=0.1
  Using cached azure_mgmt_managementgroups-0.2.0-py2.py3-none-any.whl (59 kB)
Collecting azure-mgmt-maps~=0.1.0
  Using cached azure_mgmt_maps-0.1.0-py2.py3-none-any.whl (31 kB)
Collecting azure-mgmt-applicationinsights~=1.0.0
  Using cached azure_mgmt_applicationinsights-1.0.0-py2.py3-none-any.whl (302 kB)
Collecting azure-mgmt-compute~=21.0.0
  Using cached azure_mgmt_compute-21.0.0-py2.py3-none-any.whl (3.9 MB)
Collecting azure-multiapi-storage~=0.6.2
  Using cached azure_multiapi_storage-0.6.2-py2.py3-none-any.whl (4.3 MB)
Collecting azure-mgmt-containerservice~=11.2.0
  Using cached azure_mgmt_containerservice-11.2.0-py2.py3-none-any.whl (998 kB)
Collecting azure-mgmt-imagebuilder~=0.4.0
  Using cached azure_mgmt_imagebuilder-0.4.0-py2.py3-none-any.whl (29 kB)
Collecting fabric~=2.4
  Using cached fabric-2.6.0-py2.py3-none-any.whl (53 kB)
Collecting vsts-cd-manager>=1.0.2,~=1.0.0
  Using cached vsts_cd_manager-1.0.2-py3-none-any.whl
Collecting azure-mgmt-eventhub~=4.1.0
  Using cached azure_mgmt_eventhub-4.1.0-py2.py3-none-any.whl (116 kB)
Collecting azure-mgmt-appconfiguration~=1.0.1
  Using cached azure_mgmt_appconfiguration-1.0.1-py2.py3-none-any.whl (48 kB)
Collecting azure-functions-devops-build~=0.0.22
  Using cached azure_functions_devops_build-0.0.22-py3-none-any.whl (47 kB)
Collecting azure-synapse-artifacts~=0.6.0
  Using cached azure_synapse_artifacts-0.6.0-py2.py3-none-any.whl (471 kB)
Collecting azure-mgmt-iothub==2.0.0
  Using cached azure_mgmt_iothub-2.0.0-py2.py3-none-any.whl (742 kB)
Collecting azure-mgmt-databoxedge~=0.2.0
  Using cached azure_mgmt_databoxedge-0.2.0-py2.py3-none-any.whl (330 kB)
Collecting azure-mgmt-authorization~=0.61.0
  Using cached azure_mgmt_authorization-0.61.0-py2.py3-none-any.whl (94 kB)
Collecting azure-mgmt-advisor<3.0.0,>=2.0.1
  Using cached azure_mgmt_advisor-2.0.1-py2.py3-none-any.whl (34 kB)
Collecting azure-mgmt-botservice~=0.3.0
  Using cached azure_mgmt_botservice-0.3.0-py2.py3-none-any.whl (37 kB)
Collecting azure-mgmt-monitor~=2.0.0
  Using cached azure_mgmt_monitor-2.0.0-py2.py3-none-any.whl (607 kB)
Collecting azure-mgmt-trafficmanager~=0.51.0
  Using cached azure_mgmt_trafficmanager-0.51.0-py2.py3-none-any.whl (58 kB)
Collecting azure-synapse-spark~=0.2.0
  Using cached azure_synapse_spark-0.2.0-py2.py3-none-any.whl (29 kB)
Collecting azure-mgmt-containerinstance~=1.4
  Using cached azure_mgmt_containerinstance-1.5.0-py2.py3-none-any.whl (96 kB)
Collecting azure-mgmt-reservations==0.6.0
  Using cached azure_mgmt_reservations-0.6.0-py2.py3-none-any.whl (33 kB)
Collecting azure-mgmt-redis~=7.0.0rc1
  Using cached azure_mgmt_redis-7.0.0rc2-py2.py3-none-any.whl (35 kB)
Collecting azure-mgmt-batchai~=2.0
  Using cached azure_mgmt_batchai-2.0.0-py2.py3-none-any.whl (174 kB)
Collecting azure-keyvault-administration==4.0.0b3
  Using cached azure_keyvault_administration-4.0.0b3-py2.py3-none-any.whl (77 kB)
Collecting scp~=0.13.2
  Using cached scp-0.13.4-py2.py3-none-any.whl (8.2 kB)
Collecting azure-mgmt-iothubprovisioningservices~=0.2.0
  Using cached azure_mgmt_iothubprovisioningservices-0.2.0-py2.py3-none-any.whl (60 kB)
Collecting azure-mgmt-synapse~=2.0.0
  Using cached azure_mgmt_synapse-2.0.0-py2.py3-none-any.whl (442 kB)
Collecting azure-keyvault~=1.1.0
  Using cached azure_keyvault-1.1.0-py2.py3-none-any.whl (352 kB)
Collecting azure-mgmt-netapp~=3.0.0
  Using cached azure_mgmt_netapp-3.0.0-py2.py3-none-any.whl (115 kB)
Collecting azure-batch~=10.0.0
  Using cached azure_batch-10.0.0-py2.py3-none-any.whl (230 kB)
Collecting azure-mgmt-datalake-analytics~=0.2.1
  Using cached azure_mgmt_datalake_analytics-0.2.1-py2.py3-none-any.whl (146 kB)
Collecting azure-mgmt-datamigration~=4.1.0
  Using cached azure_mgmt_datamigration-4.1.0-py2.py3-none-any.whl (132 kB)
Collecting azure-mgmt-policyinsights~=0.5.0
  Using cached azure_mgmt_policyinsights-0.5.0-py2.py3-none-any.whl (42 kB)
Collecting azure-mgmt-hdinsight~=7.0.0
  Using cached azure_mgmt_hdinsight-7.0.0-py2.py3-none-any.whl (94 kB)
Collecting azure-mgmt-storage~=18.0.0
  Using cached azure_mgmt_storage-18.0.0-py2.py3-none-any.whl (1.6 MB)
Collecting azure-storage-common~=1.4
  Using cached azure_storage_common-1.4.2-py2.py3-none-any.whl (47 kB)
Collecting azure-mgmt-sql~=0.26.0
  Using cached azure_mgmt_sql-0.26.0-py2.py3-none-any.whl (412 kB)
Collecting azure-mgmt-relay~=0.1.0
  Using cached azure_mgmt_relay-0.1.0-py2.py3-none-any.whl (36 kB)
Collecting azure-appconfiguration~=1.1.1
  Using cached azure_appconfiguration-1.1.1-py2.py3-none-any.whl (37 kB)
Collecting azure-mgmt-containerregistry==3.0.0rc17
  Using cached azure_mgmt_containerregistry-3.0.0rc17-py2.py3-none-any.whl (660 kB)
Collecting azure-mgmt-servicefabric~=0.5.0
  Using cached azure_mgmt_servicefabric-0.5.0-py2.py3-none-any.whl (85 kB)
Collecting azure-mgmt-servicebus~=6.0.0
  Using cached azure_mgmt_servicebus-6.0.0-py2.py3-none-any.whl (120 kB)
Collecting azure-mgmt-msi~=0.2
  Using cached azure_mgmt_msi-0.2.0-py2.py3-none-any.whl (17 kB)
Collecting azure-mgmt-recoveryservicesbackup~=0.11.0
  Using cached azure_mgmt_recoveryservicesbackup-0.11.0-py2.py3-none-any.whl (239 kB)
Collecting azure-synapse-accesscontrol~=0.5.0
  Using cached azure_synapse_accesscontrol-0.5.0-py2.py3-none-any.whl (30 kB)
Collecting azure-mgmt-cdn==11.0.0
  Using cached azure_mgmt_cdn-11.0.0-py2.py3-none-any.whl (252 kB)
Collecting azure-mgmt-resource==18.0.0
  Using cached azure_mgmt_resource-18.0.0-py2.py3-none-any.whl (2.2 MB)
Collecting azure-mgmt-deploymentmanager~=0.2.0
  Using cached azure_mgmt_deploymentmanager-0.2.0-py2.py3-none-any.whl (41 kB)
Collecting azure-mgmt-batch~=15.0.0
  Using cached azure_mgmt_batch-15.0.0-py2.py3-none-any.whl (131 kB)
Collecting xmltodict~=0.12
  Using cached xmltodict-0.12.0-py2.py3-none-any.whl (9.2 kB)
Collecting azure-mgmt-consumption~=2.0
  Using cached azure_mgmt_consumption-2.0.0-py2.py3-none-any.whl (46 kB)
Collecting azure-mgmt-marketplaceordering==1.1.0
  Using cached azure_mgmt_marketplaceordering-1.1.0-py2.py3-none-any.whl (26 kB)
Collecting sshtunnel~=0.1.4
  Using cached sshtunnel-0.1.5-py2.py3-none-any.whl (23 kB)
Collecting argcomplete~=1.8
  Using cached argcomplete-1.12.3-py2.py3-none-any.whl (38 kB)
Collecting msal<2.0.0,>=1.10.0
  Using cached msal-1.12.0-py2.py3-none-any.whl (66 kB)
Collecting pyopenssl>=17.1.0
  Using cached pyOpenSSL-20.0.1-py2.py3-none-any.whl (54 kB)
Collecting humanfriendly<10.0,>=4.7
  Using cached humanfriendly-9.2-py2.py3-none-any.whl (86 kB)
Collecting PyJWT==1.7.1
  Using cached PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting psutil~=5.8
  Using cached psutil-5.8.0-cp39-cp39-macosx_10_9_x86_64.whl (236 kB)
Collecting adal~=1.2.7
  Using cached adal-1.2.7-py2.py3-none-any.whl (55 kB)
Collecting azure-common~=1.1
  Using cached azure_common-1.1.27-py2.py3-none-any.whl (12 kB)
Collecting jmespath
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting azure-mgmt-core<1.3.0,>=1.2.0
  Using cached azure_mgmt_core-1.2.2-py2.py3-none-any.whl (21 kB)
Collecting pkginfo>=1.5.0.1
  Using cached pkginfo-1.7.0-py2.py3-none-any.whl (25 kB)
Collecting urllib3[secure]>=1.26.5
  Using cached urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
Collecting cryptography>=2.1.4
  Using cached cryptography-3.3.2-cp36-abi3-macosx_10_10_x86_64.whl (1.8 MB)
Collecting paramiko<3.0.0,>=2.0.8
  Using cached paramiko-2.7.2-py2.py3-none-any.whl (206 kB)
Collecting azure-cli-telemetry==1.0.6.*
  Using cached azure_cli_telemetry-1.0.6-py3-none-any.whl (10 kB)
Collecting knack~=0.8.2
  Using cached knack-0.8.2-py3-none-any.whl (59 kB)
Collecting portalocker~=1.2
  Using cached portalocker-1.7.1-py2.py3-none-any.whl (10 kB)
Collecting applicationinsights<0.12,>=0.11.1
  Using cached applicationinsights-0.11.10-py2.py3-none-any.whl (55 kB)
Collecting msrestazure<2.0.0,>=0.4.32
  Using cached msrestazure-0.6.4-py2.py3-none-any.whl (40 kB)
Collecting python-dateutil<3,>=2.1.0
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting vsts
  Using cached vsts-0.1.25-py3-none-any.whl (2.3 MB)
Collecting jinja2
  Using cached Jinja2-3.0.1-py3-none-any.whl (133 kB)
Collecting azure-nspkg>=2.0.0
  Using cached azure_nspkg-3.0.2-py3-none-any.whl (1.5 kB)
Collecting azure-mgmt-nspkg>=2.0.0
  Using cached azure_mgmt_nspkg-3.0.2-py3-none-any.whl (1.6 kB)
Collecting azure-mgmt-datalake-nspkg>=2.0.0
  Using cached azure_mgmt_datalake_nspkg-3.0.1-py3-none-any.whl (1.7 kB)
Collecting pathlib2
  Using cached pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
Collecting invoke<2.0,>=1.3
  Using cached invoke-1.5.0-py3-none-any.whl (211 kB)
Collecting pyyaml
  Using cached PyYAML-5.4.1-cp39-cp39-macosx_10_9_x86_64.whl (259 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting pygments
  Using cached Pygments-2.9.0-py3-none-any.whl (1.0 MB)
Collecting PyJWT[crypto]<3,>=1.0.0
  Using cached PyJWT-2.1.0-py3-none-any.whl (16 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting bcrypt>=3.1.3
  Using cached bcrypt-3.2.0-cp36-abi3-macosx_10_9_x86_64.whl (31 kB)
Collecting pynacl>=1.0.1
  Using cached PyNaCl-1.4.0-cp35-abi3-macosx_10_10_x86_64.whl (380 kB)
Collecting PyJWT[crypto]<3,>=1.0.0
  Using cached PyJWT-2.0.1-py3-none-any.whl (15 kB)
  Using cached PyJWT-2.0.0-py3-none-any.whl (15 kB)
INFO: pip is looking at multiple versions of sshtunnel to determine which version is compatible with other requirements. This could take a while.
Collecting sshtunnel~=0.1.4
  Using cached sshtunnel-0.1.4.tar.gz (48 kB)
INFO: pip is looking at multiple versions of scp to determine which version is compatible with other requirements. This could take a while.
Collecting scp~=0.13.2
  Using cached scp-0.13.3-py2.py3-none-any.whl (8.2 kB)
  Using cached scp-0.13.2-py2.py3-none-any.whl (9.5 kB)
INFO: pip is looking at multiple versions of python-dateutil to determine which version is compatible with other requirements. This could take a while.
Collecting python-dateutil<3,>=2.1.0
  Using cached python_dateutil-2.8.0-py2.py3-none-any.whl (226 kB)
INFO: pip is looking at multiple versions of sshtunnel to determine which version is compatible with other requirements. This could take a while.
  Using cached python_dateutil-2.7.5-py2.py3-none-any.whl (225 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of scp to determine which version is compatible with other requirements. This could take a while.
  Using cached python_dateutil-2.7.4-py2.py3-none-any.whl (211 kB)
  Using cached python_dateutil-2.7.3-py2.py3-none-any.whl (211 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached python_dateutil-2.7.2-py2.py3-none-any.whl (212 kB)
  Using cached python_dateutil-2.7.1-py2.py3-none-any.whl (212 kB)
  Using cached python_dateutil-2.7.0-py2.py3-none-any.whl (207 kB)
INFO: pip is looking at multiple versions of python-dateutil to determine which version is compatible with other requirements. This could take a while.
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl (194 kB)
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl (194 kB)
  Using cached python_dateutil-2.5.3-py2.py3-none-any.whl (201 kB)
  Using cached python_dateutil-2.5.2-py2.py3-none-any.whl (201 kB)
  Using cached python_dateutil-2.5.1-py2.py3-none-any.whl (200 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached python_dateutil-2.5.0-py2.py3-none-any.whl (199 kB)
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl (188 kB)
  Using cached python-dateutil-2.4.1.post1.zip (212 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/73/c4/d9e410b1641e210262123f49619070e46da2a7ede334cf6b6fb3db5ee985/python-dateutil-2.4.1.post1.zip#sha256=71357959bd98cbf425a6f5c5632826b548cb09d0ff3272a3565322f8aba58088 (from https://pypi.org/simple/python-dateutil/). Requested python-dateutil<3,>=2.1.0 from https://files.pythonhosted.org/packages/73/c4/d9e410b1641e210262123f49619070e46da2a7ede334cf6b6fb3db5ee985/python-dateutil-2.4.1.post1.zip#sha256=71357959bd98cbf425a6f5c5632826b548cb09d0ff3272a3565322f8aba58088 (from adal~=1.2.7->azure-cli-core==2.25.0->azure-cli->-r /tmp/gdc/scripts/requirements.txt (line 3)) has inconsistent version: filename has '2.4.1.post1', but metadata has '2.4.1'
  Using cached python-dateutil-2.4.1.post1.tar.gz (207 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/9c/b0/5948496efa852dfa78751c3f494f57fa01bfc453b4a7b7b47b0c2e0b6a80/python-dateutil-2.4.1.post1.tar.gz#sha256=aa9bdbd60c395db90204609f1fb5aeb3797870f65c09f04f243476d22f8f4615 (from https://pypi.org/simple/python-dateutil/). Requested python-dateutil<3,>=2.1.0 from https://files.pythonhosted.org/packages/9c/b0/5948496efa852dfa78751c3f494f57fa01bfc453b4a7b7b47b0c2e0b6a80/python-dateutil-2.4.1.post1.tar.gz#sha256=aa9bdbd60c395db90204609f1fb5aeb3797870f65c09f04f243476d22f8f4615 (from adal~=1.2.7->azure-cli-core==2.25.0->azure-cli->-r /tmp/gdc/scripts/requirements.txt (line 3)) has inconsistent version: filename has '2.4.1.post1', but metadata has '2.4.1'
  Using cached python_dateutil-2.4.1-py2.py3-none-any.whl (188 kB)
  Using cached python_dateutil-2.4.0-py2.py3-none-any.whl (175 kB)
  Using cached python_dateutil-2.3-py2.py3-none-any.whl (173 kB)
  Using cached python-dateutil-2.2.tar.gz (259 kB)
  Using cached python-dateutil-2.1.tar.gz (152 kB)
INFO: pip is looking at multiple versions of pyparsing to determine which version is compatible with other requirements. This could take a while.
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.6-py2.py3-none-any.whl (67 kB)
  Using cached pyparsing-2.4.5-py2.py3-none-any.whl (67 kB)
  Using cached pyparsing-2.4.4-py2.py3-none-any.whl (67 kB)
  Using cached pyparsing-2.4.3-py2.py3-none-any.whl (67 kB)
  Using cached pyparsing-2.4.2-py2.py3-none-any.whl (65 kB)
  Using cached pyparsing-2.4.1.1-py2.py3-none-any.whl (64 kB)
^CERROR: Operation cancelled by user

`

**Comment by dserdyuk** [comment]
requirements.txt:

> requests~=2.24.0
> azure-storage-blob
> azure-cli
> databricks-api~=0.5.1
> argparse
> retry

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The `inconsistent version metadata` error is not triggered by Azure CLI, but `python-dateutil`:

```
  Using cached python-dateutil-2.4.1.post1.zip (212 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/73/c4/d9e410b1641e210262123f49619070e46da2a7ede334cf6b6fb3db5ee985/python-dateutil-2.4.1.post1.zip#sha256=71357959bd98cbf425a6f5c5632826b548cb09d0ff3272a3565322f8aba58088 (from https://pypi.org/simple/python-dateutil/). Requested python-dateutil<3,>=2.1.0 from https://files.pythonhosted.org/packages/73/c4/d9e410b1641e210262123f49619070e46da2a7ede334cf6b6fb3db5ee985/python-dateutil-2.4.1.post1.zip#sha256=71357959bd98cbf425a6f5c5632826b548cb09d0ff3272a3565322f8aba58088 (from adal~=1.2.7->azure-cli-core==2.25.0->azure-cli->-r /tmp/gdc/scripts/requirements.txt (line 3)) has inconsistent version: filename has '2.4.1.post1', but metadata has '2.4.1'
  Using cached python-dateutil-2.4.1.post1.tar.gz (207 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/9c/b0/5948496efa852dfa78751c3f494f57fa01bfc453b4a7b7b47b0c2e0b6a80/python-dateutil-2.4.1.post1.tar.gz#sha256=aa9bdbd60c395db90204609f1fb5aeb3797870f65c09f04f243476d22f8f4615 (from https://pypi.org/simple/python-dateutil/). Requested python-dateutil<3,>=2.1.0 from https://files.pythonhosted.org/packages/9c/b0/5948496efa852dfa78751c3f494f57fa01bfc453b4a7b7b47b0c2e0b6a80/python-dateutil-2.4.1.post1.tar.gz#sha256=aa9bdbd60c395db90204609f1fb5aeb3797870f65c09f04f243476d22f8f4615 (from adal~=1.2.7->azure-cli-core==2.25.0->azure-cli->-r /tmp/gdc/scripts/requirements.txt (line 3)) has inconsistent version: filename has '2.4.1.post1', but metadata has '2.4.1'
```

Installing `azure-cli` alone works fine:

```
pip install azure-cli
```

The conflict comes from `requests~=2.24.0` 

https://github.com/psf/requests/blob/v2.24.0/setup.py#L47

```py
    'urllib3>=1.21.1,<1.26,!=1.25.0,!=1.25.1',
```

and `azure-cli-core`

https://github.com/Azure/azure-cli/blob/162be08eefaa1d64974a07b6179babe4c5b2830a/src/azure-cli-core/setup.py#L62

`azure-cli-core` requires the latest `urllib3` due to https://github.com/Azure/azure-cli/pull/18324.

```
> pip install requests~=2.24.0 azure-cli --use-deprecated=legacy-resolver

ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
azure-cli-core 2.25.0 requires urllib3[secure]>=1.26.5, but you'll have urllib3 1.25.11 which is incompatible.
```

Please consider using the latest `requests` to solve this issue.

**Comment by dserdyuk** [comment]
ok. Thanks for update. It works now with latest requests.
