### ISSUE TITLE
VMSS-Uniform Capacity Reservation Properties

### ISSUE THREAD

**Issue by micahjo** [Azure/azure-cli#18495]
**Resource Provider**
Compute Resource Provider (CRP) - > Virtual Machine Scale Sets (VMSS)

**Description of Feature or Work Requested**
Two new resources are being introduced, separate from these changes: Capacity Reservation Group (CRG) and Capacity Reservation (CR). Associations are made between these resources and VMSS resources.

Specifically, in the VMScaleSet -> Properties -> VirtualMachineProfile, the new property "CapacityReservationProfile" has been added as "capacityReservation". This is a class that contains the "capacityReservationGroup" as an ApiEntityRef. This is then used in operations to retrieve the CRG object and assign it in the data model. This is present to see if and which CRG a VMSS is associated with.

Similarly, in the VMScaleSetVM -> Properties (inherited from the single "VM"), the CapacityReservationProfile object is present, called "capacityReservation" storing the ApiEntityRef of the CRG. This is done because the CapacityReservationGroup resource contains a list of all the VMs associated, whether they are standalone VMs or the instances from a VMSS association.

Commands needed:

`az vmss create [--capacity-reservation-group]`
`az vmss update [--capacity-reservation-group]`

**Minimum API Version Required**
2021-04-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/15070

**Target Date**
July 1, 2021

**Comment by yonzhan** [comment]
Compute

**Comment by Juliehzl** [comment]
Hi @micahjo, as the swagger is still not merged and it is impossible to support it in 7/1 because Azure CLI code complete date is 6/30 and we need swagger and python SDK is ready before at least one week, could we support it in next release (8/3)?

And may I know the feature is for GA or public preview?

**Comment by micahjo** [comment]
Yes, that is okay. The feature is for public preview and there are also changes for Capacity Reservation and single-VM supporting Capacity Reservation pending.

**Comment by Juliehzl** [comment]
Hi @micahjo, checked swagger and it seems there is no support for 2021-07-01 https://github.com/Azure/azure-rest-api-specs/tree/master/specification/compute/resource-manager/Microsoft.Compute/stable

**Comment by micahjo** [comment]
Sorry, I have updated. This should be for 2021-04-01 now.

**Comment by Juliehzl** [comment]
> Sorry, I have updated. This should be for 2021-04-01 now.

2021-04-01 is still in preparing. We will add the support when 2021-04-01 features are merged to master as Azure CLI requires python SDK public first.

**Comment by zhoxing-ms** [comment]
@micahjo  Could you provide the design of specific commands and parameters for CI interface?

**Comment by micahjo** [comment]
Hi @zhoxing-ms , I've added the commands we need in the description. I was also wondering about the list calls (list vmss, list instances); crg should show on the vmss and vm instances for these (GET calls contain the crg ids in the response); is any change necessary to support that?

@hari-bodicherla could you verify this is the format we want for cli specifying capacity reservation?

`az vmss create [--capacity-reservation-group]
az vmss update [--capacity-reservation-group]`

**Comment by zhoxing-ms** [comment]
@micahjo Are you asking what changes need to be added to Swagger if the list operation supports capacity reservation? If so, may I ask do the parameters passed in for these list operations need to be changed?

**Comment by micahjo** [comment]
That was what I wanted to ask- the CR should show as it should in the GET for VMSS and VMSS VM- if that would mean it will show up in the list operation by default, then no change should be necessary.

**Comment by hari-bodicherla** [comment]
@micahjo , @zhoxing-ms  Can one of you please explain what is the issue here that is blocking this PR. we have a CLI request that supposed to be covering all CR, VM and VMSS changes. Can we close this and track all the changes in the below CLI issue for the CR changes
https://github.com/Azure/azure-cli/issues/18943

**Comment by micahjo** [comment]
I will close this issue. I don't think they're anything blocking this PR. Just making clarifications.
