### ISSUE TITLE
SSL binding is done on hostname level, but that is not a paremeter

### ISSUE THREAD

**Issue by owingruters** [Azure/azure-cli#18490]
[Enter feedback here]
Hi,

When adding TLS/SSL binding you do that on the fdnq of the hostname. And 1 webapp can have meny hostnames. 
in the BIND funtion I only see parameters "name" for the name of the webapp, but not the "hostname" of the hostname to which the binding should be applied.
In the portal, the first field to selct when adding a binding is select the hostname from a list of yet-unbound hostnames.
So how is this selected using the BIND function? (Same off course applies also to the Unbind)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3f984d-0d48-e075-7e2f-2da5667b15cf
* Version Independent ID: 98e06d47-0ed4-4d8e-ccf5-d3a78e510539
* Content: [az webapp config ssl](https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/ssl.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config/ssl.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team
