### ISSUE TITLE
Ubuntu 20.04 (WSL 2) fails to download azure-cli package

### ISSUE THREAD

**Issue by AzureMarker** [Azure/azure-cli#18514]
**Describe the bug**
When running the automated installer on Ubuntu 20.04 via WSL 2 (`curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`), the `azure-cli` package fails to download.

**To Reproduce**
Run `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash` in WSL 2 Ubuntu 20.04.

**Expected behavior**
The package should be downloaded and installed.

**Environment summary**
WSL 2, Ubuntu 20.04

**Additional context**
<details>
<summary>Output of running installer</summary>
<pre>
$ curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:6 https://baltocdn.com/helm/stable/debian all InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
lsb-release is already the newest version (11.1.0ubuntu2).
lsb-release set to manually installed.
curl is already the newest version (7.68.0-1ubuntu2.5).
curl set to manually installed.
gnupg is already the newest version (2.2.19-3ubuntu2.1).
gnupg set to manually installed.
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 1704 B of archives.
After this operation, 161 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 apt-transport-https all 2.0.5 [1704 B]
Fetched 1704 B in 0s (8730 B/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 48515 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_2.0.5_all.deb ...
Unpacking apt-transport-https (2.0.5) ...
Setting up apt-transport-https (2.0.5) ...
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 https://baltocdn.com/helm/stable/debian all InRelease
Hit:3 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
Get:5 https://packages.microsoft.com/repos/azure-cli focal InRelease [10.4 kB]
Hit:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:8 https://packages.microsoft.com/repos/azure-cli focal/main amd64 Packages [5871 B]
Fetched 16.3 kB in 1s (15.8 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  azure-cli
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 64.3 MB of archives.
After this operation, 937 MB of additional disk space will be used.
Err:1 https://packages.microsoft.com/repos/azure-cli focal/main amd64 azure-cli all 2.25.0-1~focal
  404  Not Found [IP: 13.66.21.183 443]
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.25.0-1~focal_all.deb  404  Not Found [IP: 13.66.21.183 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
</pre>
</details>

**Comment by adrianord** [comment]
I am getting the same issue on the same environment, WSL2, Ubuntu 20.04

Errors out as 
```
Err:1 https://packages.microsoft.com/repos/azure-cli focal/main amd64 azure-cli all 2.25.0-1~focal
  404  Not Found [IP: 13.93.224.173 443]
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.25.0-1~focal_all.deb  404  Not Found [IP: 13.93.224.173 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
Navigating to that address indeed does give a 404 and it seems the entire structure is different.

**Comment by izaac** [comment]
Our `python:3.7.0` docker image is also failing which I think is a Debian Stretch based

```
Err:1 https://packages.microsoft.com/repos/azure-cli stretch/main amd64 azure-cli all 2.25.0-1~stretch
   404  Not Found
 E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.25.0-1~stretch_all.deb  404  Not Found
 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by ericxw** [comment]
Not specific to WSL2. I'm on bare metal Ubuntu 20.04. Same issue.

`Err:1 https://packages.microsoft.com/repos/azure-cli focal/main amd64 azure-cli all 2.25.0-1~focal
  404  Not Found [IP: 40.118.250.56 443]
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.25.0-1~focal_all.deb  404  Not Found [IP: 40.118.250.56 443]
E: Unable to fetch some archives, try running apt-get update or apt-get --fix-missing.`

**Comment by ericxw** [comment]
Looks like it's working now. Was broken for last hour or so

**Comment by AzureMarker** [comment]
It still fails for me.

**Comment by adrianord** [comment]
Yeah, it's still failing for me as well

**Comment by izaac** [comment]
Still fails here too

**Comment by mutazn** [comment]
It is still failing for me, I tried on Ubuntu 20.04 and Ubuntu 18.04

**Comment by gregjhogan** [comment]
filenames in the package index are just completely wrong for some reason:

https://packages.microsoft.com/repos/azure-cli/dists/focal/main/binary-amd64/Packages
```
Package: azure-cli
Priority: extra
Section: python
Installed-Size: 614280
Maintainer: Azure Python CLI Team <azpycli@microsoft.com>
Architecture: all
Version: 2.16.0-1~focal
Depends: libc6 (>= 2.29), libssl1.1 (>= 1.1.1)
Filename: pool/main/a/azure-cli/azure-cli_2.16.0-1~focal_all.deb
Size: 51727956
MD5sum: f50af9a7f02f0b9a513dd9e4ba59ad55
SHA1: bd8214850c41c20e4f71dd63801010dd60207550
SHA256: 9929754791951a64ac4518ec18de88668d93ca8863e34544f7f46fc57f2b0da1
SHA512: 3afaad24744c8f8bc26428a53985d2fab6cba65a59dd3bbeaa412abc663a17f535058a51390aead25cb8f9046139886fa41873db91b6097002e48c90a8ea2b67
Description: Azure CLI
 A great cloud needs great tools; we're excited to introduce Azure CLI,
 our next generation multi-platform command line experience for Azure.
Homepage: https://github.com/azure/azure-cli
```

`Filename` specifications all start with `pool/...` which does not exist, across all distributions it seems

**Comment by AzureMarker** [comment]
It now works for me, feel free to close if others also see it fixed.

**Comment by gregjhogan** [comment]
I see the directory is slowly filling back up with all the releases, so depending on what version you need it may not be there yet.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
## Root Cause

There was a regression in Microsoft APT Linux repos (https://packages.microsoft.com/) during some feature migration work that resulted in the APT repo packages becoming unavailable on our mirrors. During this time, there may be intermittent download errors. 

## Status

We’ve recovered these repos by using a backup from 2021-06-16 06:00 UTC.

## Solution

Please retry the installation and it should recover now.

**Comment by sgametrio** [comment]
It still happens to me.
```
Err:4 https://packages.microsoft.com/repos/azure-cli buster InRelease
  Could not connect to packages.microsoft.com:443 (13.66.3.153), connection timed out
Reading package lists...
W: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/buster/InRelease  Could not connect to packages.microsoft.com:443 (13.66.3.153), connection timed out
```

Do I need to wait some more time for recovery? Or is it supposed to be fixed?

**Comment by adrianord** [comment]
@sgametrio That appears to be a separate issue than the original ticket. You're not even able to reach `package.microsoft.com`. I would check if your network is blocking traffic to that site. Otherwise open a new ticket.

**Comment by gregjhogan** [comment]
It is essentially down again.  Even in a VM from azure you will find these timeouts.  The package repo is up, but so slow that you constantly get timeouts.
