### ISSUE TITLE
Add parameter to add api to versionset with az apim api import

### ISSUE THREAD

**Issue by edgarkiechle** [Azure/azure-cli#18513]
**Is your feature request related to a problem? Please describe.**
In Powershell when importing an API using cmdlet Import-AzApiManagementApi  you can add it to a version set by passing ApiVersionSetId. 

For azcli, az apim api import is missing this parameter

**Describe the solution you'd like**
Add parameter --api-version-set-id

**Describe alternatives you've considered**
Using the Python SDK. However documentation for Python SDK is outdated and not straightforward. 

**Additional context**
https://docs.microsoft.com/en-us/cli/azure/apim/api?view=azure-cli-latest#az_apim_api_import

**Comment by yonzhan** [comment]
route to service team

**Comment by miaojiang** [comment]
cc @DreamlessA

**Comment by RakeshMohanMSFT** [comment]
az apim api import --path
                   --resource-group
                   --service-name
                   --specification-format {OpenApi, OpenApiJson, Swagger, Wadl, Wsdl}
                   [--api-id]
                   [--api-revision]
                   [--api-type {graphql, http, soap, websocket}]
                   [--api-version]
                   **[--api-version-set-id]**

This is fixed
