### ISSUE TITLE
az eventgrid event-subscription list fails to list all deadLetterDestinations

### ISSUE THREAD

**Issue by MerveilleBarbu** [Azure/azure-cli#18544]
## Describe the bug
az eventgrid event-subscription list fails to list all deadLetterDestinations

**Command Name**
`az eventgrid event-subscription list`

**Errors:**
No errors per se; some of the subscriptions that have dead letter destinations show the deadLetterDestination value as null and should not be.  Note that not all of the subscriptions in the list have dead letter destinations.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az eventgrid event-subscription list --source-resource-id {} --subscription {}`

## Expected Behavior

When displaying the event-subscriptions from the Azure Portal, those event-subscriptions that have dead letter destinations show the dead letter destinations.  Expected the az command to produce the same.

## Environment Summary
Running in Azure Cloud Shell (PowerShell)
```
Linux-5.4.0-1048-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.25.0

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by MerveilleBarbu** [comment]
Stupid mistake.

deadLetterDestination _is_ null; deadLetterWithResourceIdentity.deadLetterDestination is not.
