### ISSUE TITLE
On Linux vm, Import-AzApiManagementApi parameter SpecificationPath value returns "Import-AzApiManagementApi: File 'xyz.json' does not exist".

### ISSUE THREAD

**Issue by shariq-alee** [Azure/azure-cli#18552]
**Description**

**Description of Feature or Work Requested**

I am using dpcli on linux machine to use the Import-AzApiManagementApi cmdlet for importing OAS document to Azure Api Management portal. on providing the SpecificationPath parameter, which is similar to following:
/home/user/folder1/xyz.json
I am getting the following error message:
Import-AzApiManagementApi: File '/home/user/folder1/xyz.json' does not exist.

I have tried all possibilities such as, changing file name, file path, using only file name etc.

Kindly let me know if there is a known fix to this issue.

**Comment by yonzhan** [comment]
please open this issue in Azure PowerShell repo
