### ISSUE TITLE
Add SpotRestorePolicy to VMScaleset

### ISSUE THREAD

**Issue by sandeepkv93** [Azure/azure-cli#18555]
**Resource Provider**
CRP (Microsoft.Compute)

**Description of Feature or Work Requested**
Add support in Azure CLI to be able to set SpotRestore Policy to VMScaleSets.

e.g az vmss create --name myScaleSet --resource-group myResourceGroup -spot-restore-policy
e.g az vmss update --name myScaleSet --resource-group myResourceGroup -spot-restore-policy

**Minimum API Version Required**
2021-04-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/14692

**Target Date**
ASAP

**Comment by yonzhan** [comment]
Compute

**Comment by Juliehzl** [comment]
Hi @sandeepkv93, when will API 2021-04-01 be public in swagger master branch?

**Comment by rakeshakkera** [comment]
Hi @Juliehzl, looks like it just got merged. Would you be able to start work on this task?

**Comment by rakeshakkera** [comment]
@yonzhan , can this be made part of the Jul 2021 (2021-08-03) milestone as this is not released yet and the code complete date is 07/28/2021?

**Comment by yonzhan** [comment]
@rakeshakkera Since there are many high priority features in this sprint, we will kick off implementation from next sprint.

**Comment by PARADISSEEKR** [comment]
@sandeepkv93 Does ‘-spot-restore-policy’ need a default value,and how to set the default value if necessary?
