### ISSUE TITLE
webapp:az webapp config backup create - can't correctly parse the container-url

### ISSUE THREAD

**Issue by Timo-Weike** [Azure/azure-cli#18559]
## Describe the bug

If I run the command `az webapp config backup create --resource-group some-res-group --webapp-name some-web-app --debug --container-url 'https://some-storage-acc.blob.core.windows.net/some-blob-storage?se=2021-06-22&sp=rwdl&sv=2018-11-09&sr=c&sig=some-signature'` in a windows powershell I get some strange behavior.
The output is
~~~
{
  "backupId": 35461,
  "backupItemName": "some-web-app_202106210815",
  "blobName": null,
  "correlationId": "cc0d6774-035a-4fe6-8a60-1126be2e3956",
  "created": "2021-06-21T08:15:07.261403+00:00",
  "databases": [],
  "finishedTimeStamp": null,
  "id": "/subscriptions/subscription-id
[azure_backup_error.txt](https://github.com/Azure/azure-cli/files/6685265/azure_backup_error.txt)
/resourceGroups/some-res-group/providers/Microsoft.Web/sites/some-web-app",
  "kind": null,
  "lastRestoreTimeStamp": null,
  "location": "West Europe",
  "log": null,
  "name": "some-web-app",
  "resourceGroup": "some-res-group",
  "scheduled": false,
  "sizeInBytes": 0,
  "status": "Created",
  "storageAccountUrl": "https://some-storage-acc.blob.core.windows.net/some-blob-storage?se=2021-06-22",
  "type": "Microsoft.Web/sites",
  "websiteSizeInBytes": null
}
Der Befehl "sp" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "sv" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "sr" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "sig" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
~~~

`Der Befehl "sp" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.` translates to `The command "sp" is either spelled wrong or could not be found`

Also notice that the `storageAccountUrl` value is `https://some-storage-acc.blob.core.windows.net/some-blob-storage?se=2021-06-22` which misses the exact query parameter reported as errors later.
So I assume that there is some error in parsing the arguments.

If I run the command with `--debug` I see 
~~~
cli.knack.cli: Command arguments: ['webapp', 'config', 'backup', 'create', '--resource-group', 'some-res-group', '--webapp-name', 'some-web-app', '--debug', '--container-url', 'https://some-storage-acc.blob.core.windows.net/some-blob-storage?se=2021-06-22']
~~~
which provides more evidence that the argument parsing is not working properly.

See the attached file for the run with the `--debug` flag
[azure_backup_error.txt](https://github.com/Azure/azure-cli/files/6685272/azure_backup_error.txt)

**Command Name**
`az webapp config backup create`

**Errors:**

Creates an backup with an incomplete container url.

## To Reproduce:

- Create a webapp with an backup strorage container
- Get a container-url with a valid sas token
- run in a powershell `az webapp config backup create --resource-group {} --webapp-name {} --debug --container-url {}`

## Expected Behavior

Create successfully a backup of the webapp

## Actual Behavior

Creates a backup that fails due to missing sas token query parameters.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.22.0 *

```

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
Most likely issue with using CLI commands in Powershell - note if you are a powershell user you can use equivalent PS commands (if available) https://docs.microsoft.com/en-us/cli/azure/choose-the-right-azure-command-line-tool

Also check out this about using CLI commands on PS & recommended practices. https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively

**Comment by Timo-Weike** [comment]
Thanks to your links I found [this](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md) documentation about quoting issues in az with powershell. 

PS:
As to the possibility to use the powershell cmdlets: I know that I could use them, but I like the az cli more because the sub-command syntax lets you better explore the things that you can do with the tool. You simply start with `az --help` and go from there. With the powershell cmdlets I wouldn't even know where to start besides to use google.

**Comment by panchagnula** [comment]
Please re-open if issue is not resolved post updating command with quoting fixes or using BASH terminal. Thanks!
