### ISSUE TITLE
Alter `az network nsg delete` to error if no NSG is found

### ISSUE THREAD

**Issue by lazarillo** [Azure/azure-cli#18558]
**Is your feature request related to a problem? Please describe.**

I noticed weeks after it would have been helpful that `az network nsg delete` returns silently *whether or not an NSG is found*.  The only way to get a true error from the command is if the NSG cannot be deleted, for instance due to RBAC rights.

**Describe the solution you'd like**

I would like for `az network nsg delete` to error if there is no NSG with that name.  This is *likely* because of a typo in either the resource group name or the NSG name, and the user (or pipeline) should be aware that a mistake was made.

I am not sure if there is a hierarchy of errors that the AZ CLI allows for.  I think it is fine if there is a  warning instead of an outright error, as long as the warning can be captured.

**Describe alternatives you've considered**

The alternative that I implemented in our pipeline is to first perform an `az network nsg list` filtering for the NSG of interest, then either raise an error if the returned list is empty or perform `az network nsg delete` on the NSG if found.

This works perfectly fine, but it does require an extra, unnecessary call to ARM each time it is run.  We are creating and destroying resources quite frequently.

**Additional context**

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
@lazarillo, it's by design for all of the delete commands of AzureCLI. I think you can use `az network nsg show` command to detect the resource is exist or not. BTW for command group you could also use `az group show` to check command group.
