### ISSUE TITLE
Token for postman

### ISSUE THREAD

**Issue by adrian-street** [Azure/azure-cli#18560]
Please see below for the autogenerated error message.

I'm looking to use Postman to check what my APIs return during development. The command below had previous returned an access token. Now it returns the error below.

Please notify me as to the correct resource to gain an access token.

az account get-access-token --resource 0b07f429-9f4b-4714-9392-cc5e8e80c8b0sdxz

Thanks

## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named ![image](https://user-images.githubusercontent.com/86230380/122739276-bc2f6d80-d27a-11eb-9a5c-f66732448535.png)429-9f4b-4714-9392-cc5e8e80c8b0sdxz was not found in the tenant named 87d70b0f-5efc-4991-a065-e205bc3db308. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 8398f091-1a03-440a-b484-b9c1bf954f00\r\nCorrelation ID: 3687d6e4-b061-477b-b3a7-056781e8ac36\r\nTimestamp: 2021-06-21 09:18:34Z","error_codes":[500011],"timestamp":"2021-06-21 09:18:34Z","trace_id":"8398f091-1a03-440a-b484-b9c1bf954f00","correlation_id":"3687d6e4-b061-477b-b3a7-056781e8ac36","error_uri":"https://login.microsoftonline.com/error?code=500011"}
Traceback (most recent call last):
Temp\pip-unpacked-wheel-taryuzhh\knack\cli.py, ln 233, in invoke
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --resource {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.20.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Per the error message:

```
Get Token request returned http error: 400 and server response: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named ![image](https://user-images.githubusercontent.com/86230380/122739276-bc2f6d80-d27a-11eb-9a5c-f66732448535.png)429-9f4b-4714-9392-cc5e8e80c8b0sdxz was not found in the tenant named 87d70b0f-5efc-4991-a065-e205bc3db308.
```

You are using `![image](https://user-images.githubusercontent.com/86230380/122739276-bc2f6d80-d27a-11eb-9a5c-f66732448535.png)429-9f4b-4714-9392-cc5e8e80c8b0sdxz` as the `--resource` which a picture:

![image](https://user-images.githubusercontent.com/86230380/122739276-bc2f6d80-d27a-11eb-9a5c-f66732448535.png)

Running the command with text (not picture) should work:

```
az account get-access-token --resource 0b07f429-9f4b-4714-9392-cc5e8e80c8b0sdxz
```
