### ISSUE TITLE
az upgrade is blocked by policy

### ISSUE THREAD

**Issue by chriskuech** [Azure/azure-cli#18566]
When I run `az upgrade`, I get a prompt saying "The system administrator has set policies to prevent this installation".

Does your installer use unsigned powershell scripts?

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by chriskuech** [comment]
Looks like this is only a bug in `az upgrade`.  The msi works fine for upgrading versions with the given group policy.

**Comment by jiasli** [comment]
> Does your installer use unsigned powershell scripts?

No. No script is involved. The lines for installing MSI in `az upgrade` are

https://github.com/Azure/azure-cli/blob/3d14ca21e648f4fc0124132a43156a85a50251cd/src/azure-cli/azure/cli/command_modules/util/custom.py#L133-L135

Does it work if you directly call this command from Command Prompt?

```
powershell.exe -NoProfile Start-Process msiexec.exe -Wait -ArgumentList '/i https://aka.ms/installazurecliwindows'
```

Also, could you open `regedit.exe`, go to `HKLM\Software\Policies\Microsoft\Windows\Installer` and see if `DisableMSI` is configured? If so, is it possible to delete it? 

You may do the same thing in Group Policy Editor: open `gpedit.msc` and check **Local Computer Policy > Computer Configuration > Administrative Templates > Windows Components > Windows Installer > Disable Windows Installer**. If it is enabled, disable it if possible.

### References

- https://docs.microsoft.com/en-us/windows/win32/msi/disablemsi
- https://answers.microsoft.com/en-us/windows/forum/all/this-installation-is-forbidden-by-system-policy/ac1986be-a063-4b7b-834f-8fa56a8c0d04?page=1
- https://kb.vmware.com/s/article/1016563
- https://admx.help/?Category=Windows_8.1_2012R2&Policy=Microsoft.Policies.MSI::DisableMSI

**Comment by vermegi** [comment]
I ended up installing/upgrading by running: 
Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi
As described here: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-powershell (Microsoft MSI with command). 
I ran this from an administrative PowerShell prompt. I used the same prompt for the az upgrade, which failed with the above policy blocker.
The MSI install was successful.

**Comment by vermegi** [comment]
The above "powershell.exe -NoProfile Start-Process msiexec.exe -Wait -ArgumentList '/i https://aka.ms/installazurecliwindows'"
Fails with: 
Start-Process : A positional parameter cannot be found that accepts argument 'https://aka.ms/installazurecliwindows'.
At line:1 char:1
+ Start-Process msiexec.exe -Wait -ArgumentList /i https://aka.ms/insta ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Start-Process], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.StartProcessCommand

**Comment by jiasli** [comment]
@vermegi, you will need to try the command in **Command Prompt**, not PowerShell:

```
powershell.exe -NoProfile Start-Process msiexec.exe -Wait -ArgumentList '/i https://aka.ms/installazurecliwindows'
```

The caller PowerShell will interpret single quotes `'` and strip them when calling `powershell.exe`.

**Comment by vermegi** [comment]
Running that from cmd is successful, it did not show that same policy pop-up, it did fail however during the actual upgrade process with an error code (I choose the repair process). I am already on version 2.26.1 and no longer on 2.23.

**Comment by vermegi** [comment]
And as an FYI: I checked `registry` for `DisableMSI`, it was not there. Also checked group policy for `Disable Windows Installer` and it was also not present.

**Comment by jiasli** [comment]
Sorry it seems the config name has been changed, it should be **Turn off Windows Installer**:

![image](https://user-images.githubusercontent.com/4003950/127091675-636940b8-8a59-49fd-b6f6-d5a435cc62a6.png)

What if you use `python.exe` to initiate the installation in Command Prompt?

```
"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import subprocess; subprocess.call(['powershell.exe', '-NoProfile', \"Start-Process msiexec.exe -Wait -ArgumentList '/i https://aka.ms/installazurecliwindows'\"])"
```
