### ISSUE TITLE
Add public ip as manadatory parameter to az network routeserver create

### ISSUE THREAD

**Issue by naveenchekuri** [Azure/azure-cli#18571]
**Resource Provider**

Microsoft.Network

**Description of Feature or Work Requested**

Please add public ip address as mandatory field to create Azure Route Server server command. Pass the public ip resource id under ipconfiguration -> properties -> PublicIpAddress field

**Minimum API Version Required**

2021-03-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/virtualWan.json -> "HubIpConfiguration"

**Target Date**

07/15

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
@naveenchekuri Its a breaking change for CLI command. And this property in swagger is not marked as required.

**Comment by kairu-ms** [comment]
I can add `--public-ip-address` argument as optional in next release.

**Comment by naveenchekuri** [comment]
@kairu-ms Sure please proceed with this as optional parameter. We would want this change in next release as our GA timelines are dependent on this
