### ISSUE TITLE
can't find az storagesync in cli. replaced by other command?

### ISSUE THREAD

**Issue by AubreyHan** [Azure/azure-cli#18583]
Can't find az storagesync in cli. Replaced by other command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d2be52-3c69-23fc-2499-e371442ed324
* Version Independent ID: 6735ba5d-eff8-9b72-8dae-a3cf2e77e137
* Content: [az storagesync](https://docs.microsoft.com/en-us/cli/azure/storagesync?view=azure-cli-latest#az_storagesync_list)
* Content Source: [latest/docs-ref-autogen/storagesync.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storagesync.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storagesync

**Comment by Juliehzl** [comment]
Hi @AubreyHan, `az storagesync` is a cli extension, if you don't install the extension storagesync, you cannot see it. But when you type `az storagesync -h`, although there is no extension installed, we will ask you to install it with latest azure cli.

**Comment by AubreyHan** [comment]
> Hi @AubreyHan, `az storagesync` is a cli extension, if you don't install the extension storagesync, you cannot see it. But when you type `az storagesync -h`, although there is no extension installed, we will ask you to install it with latest azure cli.

Hi Julie, thanks for your help. I added this extension and it works.

**Comment by yonzhan** [comment]
Share we close this issue?

**Comment by AubreyHan** [comment]
Yes.
Thanks.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年6月22日 11:29
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Azure/azure-cli] can't find az storagesync in cli. replaced by other command? (#18583)


Share we close this issue?

―
