### ISSUE TITLE
(PublicNetworkAccessRestricted) when running az login

### ISSUE THREAD

**Issue by mebrenne** [Azure/azure-cli#18595]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Hi, I'm trying to login to azure cli using "az login"/"az login --use-device-code".
after inserting my credential, I'm getting the following error:

(PublicNetworkAccessRestricted) Request originated from public network for resource '/subscriptions', but public network access to this resource is disabled. To connect to this resource, please use the Private Endpoint from inside your virtual network. To learn more http://aka.ms/PrivateEndpointTroubleshooting.
![image](https://user-images.githubusercontent.com/86288445/122893598-244f8380-d34f-11eb-9ad7-7d5e5ae81e94.png)
(the link is broken).

I believe it's related to Arm private endpoint change but I'm not really sure.

**To Reproduce**
just log in with microsoft user.

**Expected behavior**
I need to get a way (maybe a work around) to login to my user, as it's essential in our team developing process.

**Environment summary**
I downloaded Azure cli using https://docs.microsoft.com/en-us/cli/azure/install-azure-cli.
azure-cli version - 2.25.0
os - windows 10.
shell type - powershell/azure cli.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
I will check this issue with Azure Resource Manager service team and get back to you.

**Comment by jiasli** [comment]
ARM PM replied with:

> This is a result of the customer testing in the **ARM Private Link Testing environment**. While outside of the configured private network, their calls were still trying to use the private testing environment (tenant 24f15700-370c-45bc-86a7-aee1b0c4eb8a), and by design, their calls were blocked.
> 
> The way to mitigate this for future reference is to specify a different tenant when making the call or signing into your SDK client. In this case, the customer should no longer be seeing this issue because their role assignments and credentials for the private, locked environment have been removed, and the test tenant should no longer show up as an option in their list of tenants.
