### ISSUE TITLE
[DNS] az network dns zone create can overwrite existing zones

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1859]
Currently, 'az network dns zone create' has an option --if-none-match.

WITH the option, overwrite of existing zones is prevented (via If-None-Match * etag check header)
WITHOUT the option, the command can overwrite an existing zone (but does not override existing records in that zone).

This matches the REST API behaviour, but I don't think it's very intuitive. I don't see a scenario for being able to create a zone when one already exists. I suggest removing the parameter and simply *always* including the If-None-Match * check. I.e. the command can only create a new zone and always fails if the zone already exists.

**Comment by tjprescott** [comment]
@johanste do you have an opinion on this? You made `resource group create` and PR  #1976 makes several network child resource creates goal seeking.

**Comment by johanste** [comment]
We do not have a good generic way of ensuring that resources are not overwritten. Only some resources support this functionality. We are trying very hard to avoid different semantics for the same verb in the CLI. 

The scenario for "recreating the zone" is to write resilient scripts. If your script creates a zone in step 1 and then something else in step 2, but step 2 fails, you want to be able to re-run your script. The proposed change makes that harder. 

In my opinion, we should open a generic issue for create commands in general to track the overwrite on create semantics and either make sure it works across the board, or we keep the behavior as-is.

**Comment by jtuliani** [comment]
Sounds reasonable
