### ISSUE TITLE
Cross-tenant subscription support for Gateway LB

### ISSUE THREAD

**Issue by anavinahar** [Azure/azure-cli#18600]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
If the Standard Load Balancer is in one subscription and th Gateway LB in another subscription (both in different tenants), it doesn't work in CLI

**To Reproduce**
Create a Standard LB in sub 1 and try to reference a Gateway LB in sub 2 (cross-tenant)

**Expected behavior**
It should work

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
@anavinahar  Cross tenant is supported CLI.
Could you tell me which commands are not work and the error message?
BTW which version of cli are you using?
