### ISSUE TITLE
failed to generate sas-token for iot-hub (IoT Central)

### ISSUE THREAD

**Issue by gaeguu** [Azure/azure-cli#18609]
## Describe the bug

**Command Name**
`az iot hub generate-sas-token`

**Errors:**
```
unrecognized arguments: --auth-type key

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub generate-sas-token --device-id {} --login {}`

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit
Python 3.8.10
Installer: HOMEBREW

azure-cli 2.23.0 *

Extensions:
azure-iot 0.10.6
storage-preview 0.7.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by vilit1** [comment]
Closing the issue due to no response. If you still need help with this issue, please re-open.
