### ISSUE TITLE
[Resource] Bump version 2021-04-01

### ISSUE THREAD

**Issue by 00Kai0** [Azure/azure-cli#18606]
**Is your feature request related to a problem? Please describe.**

We need bump version 2021-04-01, due to problems in this PR: https://github.com/Azure/azure-cli/pull/18433

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Resource

**Comment by shenglol** [comment]
The deployments team also has some CLI work pending on this. Since it is going to cause conflicts and we've already missed the current release milestone, I abandoned my version bump [PR](#18510 ), but It would be great if we can still catch the S190 milestone.

**Comment by 00Kai0** [comment]
Bump version PR: https://github.com/Azure/azure-cli/pull/18923
