### ISSUE TITLE
--assignee-principal-type does not allow ForeignGroup

### ISSUE THREAD

**Issue by flytzen** [Azure/azure-cli#18616]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
`az role assignment create --assignee-principal-type` does not allow `ForeignGroup` for the assignee-principal-type.
This seems to have been removed as part of https://github.com/Azure/azure-cli/issues/11594.

It is, however, required because of: https://docs.microsoft.com/en-us/partner-center/revoke-reinstate-csp

**To Reproduce**
Follow the steps in https://docs.microsoft.com/en-us/partner-center/revoke-reinstate-csp.
Using the az cli, when the client gets to  
`az role assignment create --role "Owner" --assignee-object-id <Object Id of the Admin Agents group provided by partner> --scope "/subscriptions/<CSP Subscription Id>"` 
they will get an error:
> The PrincipalId 'xxx' has type 'ForeignGroup' , which is different from specified PrinciaplType (sic) 'Group'

If you try to 
`az role assignment create --role "Owner" --assignee-object-id <Object Id of the Admin Agents group provided by partner> --scope "/subscriptions/<CSP Subscription Id>" --assignee-principal-type ForeignGroup`
you get this error:
> az role assignment create: 'ForeignGroup' is not a valid value for '--assignee-principal-type'. Allowed values: User, Group, ServicePrincipal.

**Expected behavior**
`--assignee-principal-type ForeignGroup` should be supported to allow for the scenario described by Microsoft here: https://docs.microsoft.com/en-us/partner-center/revoke-reinstate-csp

**Environment summary**
Cloud shell, Powershell

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
I will contact RBAC service team and change Azure CLI accordingly.

**Comment by ctolkien** [comment]
Seems for CSPs, MS are no longer setting AOBO by default, so we require this to be able to manage their subs....
