### ISSUE TITLE
Unable to deploy a python application from az cli

### ISSUE THREAD

**Issue by yviouswilliamous** [Azure/azure-cli#18613]
Hi, 

We have a problem deploying a python application to App service using the Az CLI.

Here is the command we use. We execute it on an ubuntu VM.
`az webapp up -n $WEB_APP_NAME -l "westeurope" -g $RESOURCE_GROUP_NAME --sku B1`
 
Here is the error we have. We don't get it :
```
Zip deployment failed. {'id': '200a84e1e024461ca2ef18edd8c3f607', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2021-06-22T15:49:57.8395052Z', 'start_time': '2021-06-22T15:49:59.5399261Z', 'end_time': '2021-06-22T15:50:13.4118115Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://test-surveillance-api-2.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://test-surveillance-api-2.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'test-surveillance-api-2'}. Please run the command az webapp log deployment show -n test-surveillance-api-2 -g azr-rg-bpceit-bpcesa-d2i2`
```
Here is a link to the [full deployment log](https://github.com/yviouswilliamous/myissues/blob/main/python_app_azcli_deployment_error.txt). In those logs, I saw the following errors. They are not clear haha.
```
knack.util.CLIError: Zip deployment failed. {'id': '273909f740bd44de93111b0576d235f9', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2021-06-22T16:11:12.3912894Z', 'start_time': '2021-06-22T16:11:13.5603203Z', 'end_time': '2021-06-22T16:11:23.3248561Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://test-surveillance-api-2.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://test-surveillance-api-2.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'test-surveillance-api-2'}. Please run the command az webapp log deployment show -n test-surveillance-api-2 -g azr-rg-bpceit-bpcesa-d2i2
```

```
cli.azure.cli.core.azclierror : Zip deployment failed. {'id': '273909f740bd44de93111b0576d235f9', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2021-06-22T16:11:12.3912894Z', 'start_time': '2021-06-22T16:11:13.5603203Z', 'end_time': '2021-06-22T16:11:23.3248561Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://test-surveillance-api-2.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://test-surveillance-api-2.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'test-surveillance-api-2'}. Please run the command az webapp log deployment show -n test-surveillance-api-2 -g azr-rg-bpceit-bpcesa-d2i2
Zip deployment failed. {'id': '273909f740bd44de93111b0576d235f9', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2021-06-22T16:11:12.3912894Z', 'start_time': '2021-06-22T16:11:13.5603203Z', 'end_time': '2021-06-22T16:11:23.3248561Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://test-surveillance-api-2.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://test-surveillance-api-2.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'test-surveillance-api-2'}. Please run the command az webapp log deployment show -n test-surveillance-api-2 -g azr-rg-bpceit-bpcesa-d2i2
```

**More details about the environment:**
OS : Ubuntu 18.04.5 LTS
Python version : 3.8.7

**Comment by yonzhan** [comment]
route to service team

**Comment by yviouswilliamous** [comment]
Hi, 
I solved my problem !!

After doing some researches, I noticed the problem was with the requirements.txt and the repository containing my files.

So, I copied the files in another repository. And I generated the requirements.txt with the python of my python virtual env (./env/bin/python3), not with the one installed in the OS.

I don't understand why this was the problem. If someone knows, please tell me.

Have a good day.

**Comment by RajagopalAswin1994** [comment]
I am getting this error, I can't find the solution, can someone help to this, 

Error: local-exec provisioner error
│ 
│   with module.functionsapp.azurerm_linux_function_app.funcappbbsi,
│   on modules/functionsapp/main.tf line 144, in resource "azurerm_linux_function_app" "funcappbbsi":
│  144:   provisioner "local-exec" {
│ 
│ Error running command 'az account show ; az webapp deployment source
│ config-zip --resource-group rg-app-sndbx --name
│ funcapp-sndbx-ver20230830122951 --src ./api-functions20230830122951
│ --debug': exit status 1. Output: https://management.azure.com:443 "PUT
│ /subscriptions/su-----------------------------f73/resourceGroups/rg-app-sndbx/providers/Microsoft.Web/sites/funcapp-sndbx-ver20230830122951/config/logs?api-version=2022-03-01
│ HTTP/1.1" 200 None
│ DEBUG: cli.azure.cli.core.sdk.policies: Response status: 200
│ DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
│ DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type':
│ 'application/json'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'ETag': '"1D9DB3DECBE7615"'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security':
│ 'max-age=31536000; includeSubDomains'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id':
│ '81e2db06-cbf3-4773-a564-aa4aed5f7ffb'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
│ DEBUG: cli.azure.cli.core.sdk.policies:
│ 'x-ms-ratelimit-remaining-subscription-writes': '1199'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id':
│ 'ff7c1658-2b47-4d89-bfc4-442ccd392f54'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id':
│ 'EASTUS:20230830T123140Z:ff7c1658-2b47-4d89-bfc4-442ccd392f54'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options':
│ 'nosniff'
│ DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 30 Aug 2023
│ 12:31:39 GMT'
│ DEBUG: cli.azure.cli.core.sdk.policies: Response content:
│ DEBUG: cli.azure.cli.core.sdk.policies:
│ {"id":"/subscriptions/su-----------------------------3ba64f73/resourceGroups/rg-app-sndbx/providers/Microsoft.Web/sites/funcapp-sndbx-ver20230830122951/config/logs","name":"logs","type":"Microsoft.Web/sites/config","location":"West
│ US","tags":{"app":"app","env":"sndbx","monitor":"false"},"properties":{"applicationLogs":{"fileSystem":{"level":"Off"},"azureTableStorage":{"level":"Off","sasUrl":null},"azureBlobStorage":{"level":"Off","sasUrl":null,"retentionInDays":null}},"httpLogs":{"fileSystem":{"retentionInMb":100,"retentionInDays":3,"enabled":true},"azureBlobStorage":{"sasUrl":null,"retentionInDays":3,"enabled":false}},"failedRequestsTracing":{"enabled":false},"detailedErrorMessages":{"enabled":false}}}
│ DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
│   File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
│     cmd_result = self.invocation.execute(args)
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
│     raise ex
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
│     results.append(self._run_job(expanded_arg, cmd_copy))
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
│     return cmd_copy.exception_handler(ex)
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/commands.py", line 46, in _ex_handler
│     raise ex
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
│     result = cmd_copy(params)
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
│     return self.handler(*args, **kwargs)
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
│     return op(**command_args)
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 584, in enable_zip_deploy_webapp
│     return enable_zip_deploy(cmd, resource_group_name, name, src, timeout=timeout, slot=slot)
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 615, in enable_zip_deploy
│     response = _check_zip_deployment_status(cmd, resource_group_name, name, deployment_status_url,
│   File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 4121, in _check_zip_deployment_status
│     raise CLIError("Zip deployment failed. {}. Please run the command az webapp log deployment show "
│ knack.util.CLIError: Zip deployment failed. {'id':
│ '1a606704-f9d8-4c20-acf6-ef992c46b30d', 'status': 3, 'status_text': '',
│ 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer',
│ 'message': 'Created via a push deployment', 'progress': '',
│ 'received_time': '2023-08-30T12:31:25.2725488Z', 'start_time':
│ '2023-08-30T12:31:26.489662Z', 'end_time': '2023-08-30T12:31:35.5681384Z',
│ 'last_success_end_time': None, 'complete': True, 'active': False,
│ 'is_temp': False, 'is_readonly': True, 'url':
│ 'https://funcapp-sndbx-ver20230830122951.scm.azurewebsites.net/api/deployments/1a606704-f9d8-4c20-acf6-ef992c46b30d',
│ 'log_url':
│ 'https://funcapp-sndbx-ver20230830122951.scm.azurewebsites.net/api/deployments/1a606704-f9d8-4c20-acf6-ef992c46b30d/log',
│ 'site_name': 'funcapp-sndbx-ver20230830122951'}. Please run the command az
│ webapp log deployment show -n funcapp-sndbx-ver20230830122951 -g
│ rg-app-sndbx
│ 
│ ERROR: cli.azure.cli.core.azclierror: Zip deployment failed. {'id':
│ '1a606704-f9d8-4c20-acf6-ef992c46b30d', 'status': 3, 'status_text': '',
│ 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer',
│ 'message': 'Created via a push deployment', 'progress': '',
│ 'received_time': '2023-08-30T12:31:25.2725488Z', 'start_time':
│ '2023-08-30T12:31:26.489662Z', 'end_time': '2023-08-30T12:31:35.5681384Z',
│ 'last_success_end_time': None, 'complete': True, 'active': False,
│ 'is_temp': False, 'is_readonly': True, 'url':
│ 'https://funcapp-sndbx-ver20230830122951.scm.azurewebsites.net/api/deployments/1a606704-f9d8-4c20-acf6-ef992c46b30d',
│ 'log_url':
│ 'https://funcapp-sndbx-ver20230830122951.scm.azurewebsites.net/api/deployments/1a606704-f9d8-4c20-acf6-ef992c46b30d/log',
│ 'site_name': 'funcapp-sndbx-ver20230830122951'}. Please run the command az
│ webapp log deployment show -n funcapp-sndbx-ver20230830122951 -g
│ rg-app-sndbx
│ ERROR: az_command_data_logger: Zip deployment failed. {'id':
│ '1a606704-f9d8-4c20-acf6-ef992c46b30d', 'status': 3, 'status_text': '',
│ 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer',
│ 'message': 'Created via a push deployment', 'progress': '',
│ 'received_time': '2023-08-30T12:31:25.2725488Z', 'start_time':
│ '2023-08-30T12:31:26.489662Z', 'end_time': '2023-08-30T12:31:35.5681384Z',
│ 'last_success_end_time': None, 'complete': True, 'active': False,
│ 'is_temp': False, 'is_readonly': True, 'url':
│ 'https://funcapp-sndbx-ver20230830122951.scm.azurewebsites.net/api/deployments/1a606704-f9d8-4c20-acf6-ef992c46b30d',
│ 'log_url':
│ 'https://funcapp-sndbx-ver20230830122951.scm.azurewebsites.net/api/deployments/1a606704-f9d8-4c20-acf6-ef992c46b30d/log',
│ 'site_name': 'funcapp-sndbx-ver20230830122951'}. Please run the command az
│ webapp log deployment show -n funcapp-sndbx-ver20230830122951 -g
│ rg-app-sndbx
│ DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function
│ AzCliLogging.deinit_cmd_metadata_logging at 0x7f619b3fef80>]
│ INFO: az_command_data_logger: exit code: 1
│ INFO: cli.__main__: Command ran in 26.859 seconds (init: 0.183, invoke:
│ 26.676)
│ INFO: telemetry.main: Begin splitting cli events and extra events, total
│ events: 1
│ INFO: telemetry.client: Accumulated 0 events. Flush the clients.
│ INFO: telemetry.main: Finish splitting cli events and extra events, cli
│ events: 1
│ INFO: telemetry.save: Save telemetry record of length 4366 in cache
│ INFO: telemetry.main: Begin creating telemetry upload process.
│ INFO: telemetry.process: Creating upload process:
│ "/usr/bin/../../opt/az/bin/python3
│ /opt/az/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py
│ /home/vsts/.azure"
│ INFO: telemetry.process: Return from creating process
│ INFO: telemetry.main: Finish creating telemetry upload process.
│ 
╵
##[error]Bash exited with code '1'.
Finishing: 🏗️ terraform apply
