### ISSUE TITLE
Postgres Flexible Server Variables Are Not Part of Local Context

### ISSUE THREAD

**Issue by raahmed** [Azure/azure-cli#18618]
**Resource Provider**
Azure CLI

**Description of Feature or Work Requested**

Currently, users attempting to connect a webapp to a postgres database need to manually copy-paste the server, hostname, username, password and db-name from the JSON output. 

![image](https://user-images.githubusercontent.com/25991359/123152544-8ffe2300-d419-11eb-9766-61bb54e45e02.png)

This is challenging and adds many step to the process (including scrolling up the terminal, finding this information, copying it over, adding it to the CLI command etc). 

Would it be possible to keep this information as part of the local context so that the users will not have to take so many steps to succeed?

**Minimum API Version Required**
N/A
**Swagger Link**
N/A

**Target Date**
I would love to see this rolled out before Ignite. The Azure Resource Connector goes into preview by that time and having this feature will likely expedite the utility of the changes coming in through the connector.

**Comment by yonzhan** [comment]
route to service team

**Comment by nachoalonsoportillo** [comment]
@raahmed It seems that all this `az local-context`, which was later renamed to `az config params-persist` is being dropped. Therefore, I don't think this request makes sense at this point in time. Please, refer to [Tips for using the Azure CLI successfully](https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully-tips?tabs=bash%2Cbash2) to learn how to retrieve the output of a command and process it further or store it in a variable.

**Comment by nachoalonsoportillo** [comment]
@yonzhan Please, proceed to close. Thanks!
