### ISSUE TITLE
az acs scale fails with error, secret can not be none

### ISSUE THREAD

**Issue by SteveLasker** [Azure/azure-cli#1862]
Following docs here: https://docs.microsoft.com/en-us/azure/container-service/container-service-create-acs-cluster-cli
Created a Kubernetes Cluster
Repro Steps
```
az acs scale -g stevelas-kube -n kube1 --new-agent-count 2
Parameter 'secret' can not be None.
```

**Comment by lostintangent** [comment]
This issue is tracked via #1303
