### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'user_agent' in CI pipeline command-az extension add -n azure-cli-ml

### ISSUE THREAD

**Issue by Smrithi10** [Azure/azure-cli#18626]
File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\azure\cli\core\commands\__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\azure\cli\core\commands\command_operation.py", line 121, in handler
    return op(**command_args)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\azure\cli\command_modules\profile\custom.py", line 152, in login
    subscriptions = profile.find_subscriptions_on_login(
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\azure\cli\core\_profile.py", line 215, in find_subscriptions_on_login
    subscriptions = subscription_finder.find_from_service_principal_id(
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\azure\cli\core\_profile.py", line 939, in find_from_service_principal_id
    result = self._find_using_specific_tenant(tenant, token_entry[_ACCESS_TOKEN])
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\azure\cli\core\_profile.py", line 1033, in _find_using_specific_tenant
    client = self._arm_client_factory(token_credential)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\azure\cli\core\_profile.py", line 880, in create_arm_client_factory
    client = client_type(credentials, api_version=api_version,
TypeError: __init__() got an unexpected keyword argument 'user_agent'

**Comment by yonzhan** [comment]
route to service team

**Comment by singankit** [comment]
@Smrithi10 Can you please share more information on the azure cli version being used. Are you using azureml pipeline or is it a different pipeline ? We have seen this issue when azure-cli is installed using pip (not a recommended way). Recommended way to install azure cli can here found [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli).

**Comment by Smrithi10** [comment]
I am setting up Azure ML ci pipeline in Azure Devops Studio

**Comment by singankit** [comment]
@Smrithi10 Please share the info on how azure-cli is being installed.

**Comment by jiasli** [comment]
Copied from https://github.com/Azure/azure-cli/issues/18532#issuecomment-863725311:

The error 

```
2021-06-15T18:01:17.7121089Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\azure\cli\core\_profile.py", line 881, in create_arm_client_factory
2021-06-15T18:01:17.7121619Z     base_url=self.cli_ctx.cloud.endpoints.resource_manager, **client_kwargs)
2021-06-15T18:01:17.7122847Z TypeError: __init__() got an unexpected keyword argument 'user_agent'
```

happens at

https://github.com/Azure/azure-cli/blob/3b17a5fb2fd9eb3c35c83cc94245c11d268e7323/src/azure-cli-core/azure/cli/core/_profile.py#L880-L881

`user_agent` is added to `client_kwargs` for Track 2 SDK by

https://github.com/Azure/azure-cli/blob/672837983df7e6f4cb55fadd30ed375bfd53df21/src/azure-cli-core/azure/cli/core/commands/client_factory.py#L127

It looks like the `azure-mgmt-resource` SDK on the agent is not updated to Track 2.

Azure CLI does require Track 2 `azure-mgmt-resource` SDK:

https://github.com/Azure/azure-cli/blob/5cbb798ac28c07ef3453be4f960fce8d17c81f4e/src/azure-cli/setup.py#L118

Could you run 

```
C:\hostedtoolcache\windows\Python\3.8.10\x64\python.exe -m pip list
```

and share the result?

You may install Azure CLI again

```
C:\hostedtoolcache\windows\Python\3.8.10\x64\python.exe -m pip install --upgrade azure-cli 
```

so that the responding SDKs are installed.

Though I have little knowledge about how Azure CLI is installed on the agent. Perhaps Machine Learning pipeline team should take a look?

**Comment by rmourya1** [comment]
Hi, I am setting same error while setting up the pipeline in Azure DevOps with the following libraries:

      pip install --upgrade azureml-sdk pandas
      pip install --upgrade azure-cli
      pip install azureml-train-automl-runtime==1.31.0

The error occurs when I try to install azureml-train-automl-runtime and then authenticate using azure cli. It used to work a couple of months ago, precisely in May, but it fails with user_agent error.  If I remove that line, authentication works but then in the pipeline, I get a warning "WARNING:root:The model you attempted to retrieve requires 'azureml-train-automl-runtime' to be installed at '==1.31.0'. Please install 'azureml-train-automl-runtime==1.31.0' (e.g. `pip install azureml-train-automl-runtime==1.31.0`) and then rerun the previous command."

**Comment by jiasli** [comment]
As [`azureml-train-automl-runtime`](https://pypi.org/project/azureml-train-automl-runtime/) requires `Python >=3.6, <3.8`, I tried to install `azureml-train-automl-runtime` in a Python 3.7 virtual env. Then I run [`pipdeptree`](https://pypi.org/project/pipdeptree/) to find the dependency on `azure-mgmt-resource`:

```
> pipdeptree --revers --packages azure-mgmt-resource
azure-mgmt-resource==13.0.0
  - azureml-core==1.31.0 [requires: azure-mgmt-resource>=1.2.1,<15.0.0]
    - azureml-defaults==1.31.0 [requires: azureml-core~=1.31.0]
      - azureml-train-automl-runtime==1.31.0 [requires: azureml-defaults~=1.31.0]
    - azureml-interpret==1.31.0 [requires: azureml-core~=1.31.0]
      - azureml-train-automl-runtime==1.31.0 [requires: azureml-interpret~=1.31.0]
    - azureml-telemetry==1.31.0 [requires: azureml-core~=1.31.0]
      - azureml-automl-core==1.31.0 [requires: azureml-telemetry~=1.31.0]
        - azureml-automl-runtime==1.31.0 [requires: azureml-automl-core~=1.31.0]
          - azureml-train-automl-runtime==1.31.0 [requires: azureml-automl-runtime~=1.31.0]
        - azureml-train-automl-client==1.31.0 [requires: azureml-automl-core~=1.31.0]
          - azureml-train-automl-runtime==1.31.0 [requires: azureml-train-automl-client~=1.31.0]
        - azureml-train-automl-runtime==1.31.0 [requires: azureml-automl-core~=1.31.0]
      - azureml-train-automl-client==1.31.0 [requires: azureml-telemetry~=1.31.0]
        - azureml-train-automl-runtime==1.31.0 [requires: azureml-train-automl-client~=1.31.0]
      - azureml-train-automl-runtime==1.31.0 [requires: azureml-telemetry~=1.31.0]
    - azureml-train-automl-client==1.31.0 [requires: azureml-core~=1.31.0]
      - azureml-train-automl-runtime==1.31.0 [requires: azureml-train-automl-client~=1.31.0]
    - azureml-train-automl-runtime==1.31.0 [requires: azureml-core~=1.31.0]
```

This indicates a conflicting dependency:

- `azureml-core==1.31.0` requires Track 1 SDK `azure-mgmt-resource>=1.2.1,<15.0.0`
- `azure-cli` requires Track 2 SDK `azure-mgmt-resource`: https://github.com/Azure/azure-cli/blob/5cbb798ac28c07ef3453be4f960fce8d17c81f4e/src/azure-cli/setup.py#L118

There are 2 possible solutions:

- Machine Learning team should bump the dependency on `azure-mgmt-resource` to Track 2 in `azureml-core`
- The user can install `azure-cli` in a different virtual environment to avoid such conflicting dependency

**Comment by fatmelon** [comment]
Run into the same error when run `az login` with jupyter notebook in Azure Machine Learning:
![image](https://user-images.githubusercontent.com/9691826/126745804-b567c002-d892-4a2f-8a9c-b56e672c0005.png)

But when I run  `az login` with terminal in the same  Azure Machine Learning, everthing is OK.

**Comment by yonzhan** [comment]
@fatmelon does above solutions proposed by @jiasli resolve your issue?

**Comment by fatmelon** [comment]
@yonzhan I tried solution2&3 but that didn't work for me. I think the error may not be caused by CLI, after all, I can use it normally in terminal, at least for `az login`.

**Comment by yonzhan** [comment]
@fatmelon thanks for clarification. Could this issue be closed?

**Comment by fatmelon** [comment]
@yonzhan just tried again in jupyter notebook with aml and still got the error, so I think we'd better keep it open.

**Comment by jsntcy** [comment]
@singankit, could you please help take a look at this issue?

**Comment by singankit** [comment]
I would suggest not installed azure-cli as a pip package rather than installing azure cli using [official methods ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli).

**Comment by jiasli** [comment]
@fatmelon, you may be running different Azure CLI. To see which Azure CLI you are calling, you may check the full path of `az` with

- `where az` in Command Prompt
- `Get-Command az` in PowerShell
- `which az` in Bash

**Comment by fatmelon** [comment]
@jiasli , you are right. The jupyter calls `/anaconda/envs/azureml_py36/bin//az`, but in terminals we call `/usr/bin/az`. The error is caused by running different Azure CLI in aml. Thanks for your help~

**Comment by rmourya1** [comment]
@jiasli How will this work in Azure DevOps? In DevOps, I am installing CLI using pip install on the runtime system to use it in different modules. Please clarify if I am missing anything.

**Comment by jiasli** [comment]
@rmourya1, `azureml-sdk` depends on `azureml-core` which has a dependency conflict with `azure-cli` on `azure-mgmt-resource` as shown in https://github.com/Azure/azure-cli/issues/18626#issuecomment-879609185:

```
> pipdeptree --revers --packages azure-mgmt-resource
azure-mgmt-resource==13.0.0
  - azureml-core==1.32.0 [requires: azure-mgmt-resource>=1.2.1,<15.0.0]
    - azureml-train-core==1.32.0 [requires: azureml-core~=1.32.0]
      - azureml-pipeline-steps==1.32.0 [requires: azureml-train-core~=1.32.0]
        - azureml-pipeline==1.32.0 [requires: azureml-pipeline-steps~=1.32.0]
          - azureml-sdk==1.32.0 [requires: azureml-pipeline~=1.32.0]
      - azureml-train==1.32.0 [requires: azureml-train-core~=1.32.0]
        - azureml-sdk==1.32.0 [requires: azureml-train~=1.32.0]
```

You may install Azure CLI in a virtual environment and run it from there:

```sh
#Linux
python -m venv <env_name>
<env_name>/bin/python -m pip install azure-cli
<env_name>/bin/python -m azure.cli ...

#PowerShell
python -m venv <env_name>
.\<env_name>\Scripts\python.exe -m pip install azure-cli
.\<env_name>\Scripts\python.exe -m azure.cli ...
```

**Comment by matthid** [comment]
@jiasli I'm a bit confused by this issue. Apparently, you urge people to use a different installation route.
However in [the docs](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-setup-authentication#use-service-principal-authentication) it is mentioned to use `AzureCliAuthentication`:
```python
from azureml.core.authentication import AzureCliAuthentication
cli_auth = AzureCliAuthentication()
ws = Workspace(subscription_id="your-sub-id",
               resource_group="your-resource-group-id",
               workspace_name="your-workspace-name",
               auth=cli_auth
               )
```

Which is ideal for my use case (ie combining that with the `AzureCLI@2`-task in Azure Pipelines), however as I have to install both  `azureml-core` and `azure-cli` I run into this issue.

So is this not a supported scenario? What would be the supported way to re-use an existing Azure Pipelines service connection (if I don't want to manage another set of credentials for authenticating against the workspace in the build)?

**Comment by jiasli** [comment]
@matthid, `azureml.core` is not maintained by our (Azure CLI) team. Migrating to Track 2 SDKs and MSAL are something Azure CLI must do. `azureml.core` should be updated to adapt to the latest Azure CLI.

Also, for downgrading Azure CLI, please see https://github.com/Azure/azure-cli/issues/20297#issuecomment-971256739 for additional things to consider.

**Comment by matthid** [comment]
@jiasli Understood (thanks for the link/node). Maybe a bit naive on my side but can't both teams work together and help each other to ensure this scenario is working? Even if they upgrade now it will break again next time azure-cli is upgraded, right?

**Comment by jiasli** [comment]
I fully understand your concerns.

> but can't both teams work together and help each other to ensure this scenario is working?

We have already informed ML team [on 2021-06-25](https://github.com/Azure/azure-cli/issues/18626#issuecomment-868072055) and I believe they are actively working on it.

> Even if they upgrade now it will break again next time azure-cli is upgraded, right?

Not really. Migrating to Track 2 SDKs and MSAL are the only migrations we need to do recently. No further breaking changes need to done in the foreseeable future.

**Comment by luigiw** [comment]
Azure CLI v2 is GAed and the active version AzureML supports. Please consider switching to v2. https://learn.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli?tabs=public
