### ISSUE TITLE
az sig image-version create does not support mixing disks, snapshots, and vhd

### ISSUE THREAD

**Issue by olayemio** [Azure/azure-cli#18633]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I specify a data disk image using a mix of disk and VHD, but only the VHD is kept. It seems that having the VHD causes the command to ignore the data disk image flags. First, Customers should be able to put data-snapshot-* and data-vhd-* in the same call. Second, data-snapshot-luns and data-vhd-luns should not overlap

**To Reproduce**
`az sig image-version create --gallery-image-definition $galleryDefinitionName --gallery-image-version $galleryImageVersionName --gallery-name $galleryName --resource-group $rg  --location $region--os-snapshot $source_os_snapshot --data-snapshot-luns 0 --data-snapshots $source_dd1_disk --data-vhds-luns 1 --data-vhds-sa $source_dd2_vhd_storage_account --data-vhds-uris $source_dd2_vhd_uri`

**Expected behavior**
The REST API, if using debug, should show that there are two data disk images in the create call (one at LUN 0 and the other at LUN 1). 

**Environment summary**
Using Windows Subsystem for Linux version 2 on Windows 10 and azure-cli 2.24.2

**Additional context**

**Comment by yonzhan** [comment]
Compute

**Comment by jsntcy** [comment]
Close this issue as code is ready and will be released on 8/3 with Azure CLI 2.27.0
