### ISSUE TITLE
[DNS] How do I add tags with a space in the value?

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1863]
'az network dns zone create -h' shows:

    --tags                        : Space separated tags in 'key[=value]' format. Use "" to clear
                                    existing tags.

Tags cannot contain a space in the key. However, they can contain a space in the value.  (I just tried it via the Portal, it works).

Given that the list of tags is space-separated, how does this work? How do I create a tag with a space in the value?

If it's not supported, then it needs to be.  If it is supported, then the help text needs to be improved.

I found this in the context of creating a DNS zone.  However, I expect it is widespread, and hence the fix should be applied broadly across the CLI surface.

**Comment by tjprescott** [comment]
Use quotes. --tags key="my long value"

**Comment by jtuliani** [comment]
In that case, how do I specify multiple tags?

As I said...even if this is supported, the help text needs to explain it better.

**Comment by tjprescott** [comment]
--tags key="long value" key2=shortvalue

**Comment by MassimoSporchia** [comment]
@tjprescott any way to create/modify tags with a spaced-key?
e.g.
{
  "Spaced Key": "Spaced value"
}

**Comment by andythsu** [comment]
I have multiple tags like
key_1 = "foo"
key_2 = "boo"
val_1="foo 1"
val_2="boo 2"
tags=$key_1=$val_1 $key_2=$val_2
--tags $tags <- this command will give me error as it will parse the space in val_1 and val_2
please help. Thanks

**Comment by arjenbloemsma** [comment]
I'm facing the same issue, when i'm scripting the provisioning of Azure resources.

My goal is to store multiple tags in a variable and provide that variable to the --tags option. The problem is, as mentioned in the posts above, that a space in the value will be interpreted as a new key.

Example:

```sh
tag='owner="FirstName LastName" application=coolapp'
```
echo $tag will give:

```sh
owner="FirstName LastName" application=coolapp
```

If I provide the tag variable to the tags option of the command like so:

```sh
az group update --tags $tag --name name-of-my-resource-group
```

The result will be 3 tags instead of the expected 2:

```sh
{
  "id": "/subscriptions/1e42c44c-bc55-4b8a-b35e-de1dfbcfe481/resourceGroups/name-of-my-resource-group",
  "location": "westeurope",
  "managedBy": null,
  "name": "name-of-my-resource-group",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": {
    "LastName\"": "",
    "application": "coolapp",
    "owner": "\"FirstName"
  }
}
```

However, if I provide the value of the tag variable without using the variable the outcome will be as expected as shown in the example below.

```sh
az group update --tags owner="FirstName LastName" application=coolapp --name name-of-my-resource-group
````
Result:
```sh
{
  "id": "/subscriptions/1e42c44c-bc55-4b8a-b35e-de1dfbcfe495/resourceGroups/modern-site-provisioning-dev-rg",
  "location": "westeurope",
  "managedBy": null,
  "name": "modern-site-provisioning-dev-rg",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": {
    "application": "coolapp",
    "owner": "FirstName LastName"
  }
}
```

Does anybody know how to solve this?

**Comment by tbertenshaw** [comment]
Also having this problem. I want to pass a variable to a cli vmss update to set the tags and ive tried numerous variations of quotes escaped quotes with backticks, backslashes. It seems ok for one value but more than one keyvalue pair seems impossible. Is there an example of running the cli via powershell and passing more than one tag in a variable to the command?

**Comment by mtrcn** [comment]
A bit more complex example;

```
--tags Description="A Function app for web scrapping" Created' 'by="Mete Pakdil" Product="Mete SaaS Solutions"
```
