### ISSUE TITLE
Use RootManageSharedAccessKey in example

### ISSUE THREAD

**Issue by algattik** [Azure/azure-cli#18645]
`RootManageSharedAccessKey` would be a better key name in the example than `PrimaryKey`, since it is created by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3352c15-c7ef-2871-2f5e-f51e78044764
* Version Independent ID: 510eef77-4736-7a37-83c4-ad84125dca77
* Content: [az eventhubs namespace authorization-rule keys](https://docs.microsoft.com/en-us/cli/azure/eventhubs/namespace/authorization-rule/keys?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/eventhubs/namespace/authorization-rule/keys.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/eventhubs/namespace/authorization-rule/keys.yml)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by Saglodha** [comment]
Hi @algattik, thanks for reaching out to us. 

Under default RootManageSharedAccessKey , we have two keys: primary and secondary, the renewal operation can work independently on either of primary or secondary key. 

Thus, we have defined the key names explicitly in the examples based on the allowed values. I hope this helps.
