### ISSUE TITLE
Debian 11

### ISSUE THREAD

**Issue by Jonas-Lara** [Azure/azure-cli#18654]
## Describe el bug

**sudo apt update**
``

**Errors:**

## Que produce el error:
Despues de hacer apt update

 -apt update
Obj:10 http://packages.microsoft.com/repos/code stable InRelease
Leyendo lista de paquetes... Hecho  
E: El repositorio «https://packages.microsoft.com/repos/azure-cli bullseye Release» no tiene un fichero de Publicación.
N: No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.
N: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.

## Environment Summary
```
Linux-5.10.0-7-amd64-x86_64-with-glibc2.31
Python 3.9.2
Installer: DEB

azure-cli 2.18.0 *

Extensions:
azure-devops 0.19.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Bing translator gives me:

```
After doing apt update

-apt update
Obj:10 http://packages.microsoft.com/repos/code stable InRelease
Reading package list... fact
E: The "https://packages.microsoft.com/repos/azure-cli bullseye Release" repository does not have a Publish file.
N: You cannot update from a repository like this safely and therefore it is disabled by default.
N: See the apt-secure(8) man page for details on creating repositories and configuring users.
```

This is because we are not releasing for `bullseye` currently. Could you check [No package for your distribution](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#no-package-for-your-distribution) and see if you can be unblocked?

**Comment by jiasli** [comment]
### Install on `bullseye` with automatic fallback

Checked with a [Debian bullseye docker image](https://hub.docker.com/_/ubuntu?tab=tags&page=1&ordering=last_updated&name=21.04) and I was able to install Azure CLI correctly:

```
docker run -it ubuntu:bullseye
```

```
apt update
apt install curl
curl -sL https://aka.ms/InstallAzureCLIDeb | bash
az --version
```

The document [Install the Azure CLI on Linux - Option 1: Install with one command](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) provides a command:

```
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
```

https://aka.ms/InstallAzureCLIDeb is a script which automatically falls back to `buster` for unsupported `Debian` distributions:

https://github.com/Azure/azure-cli/blob/1fec5c4e721d2313e91c15a5ba542025759131d6/scripts/release/debian/deb_install.sh#L64-L65

Please run that command and see if it works.

### Manually choose the fallback repository

If you have to manually add the repository to `/etc/apt/sources.list.d/azure-cli.list`, please follow [No package for your distribution](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#no-package-for-your-distribution) to manually choose the fallback repository. 

### Install with `pip`

You may also instead with `pip` as shown in https://github.com/Azure/azure-cli/issues/18703#issuecomment-875367573.
