### ISSUE TITLE
az webapp up: If csproj not in root directory, exception returned

### ISSUE THREAD

**Issue by calvinsID** [Azure/azure-cli#18652]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
 Exception:

![image](https://user-images.githubusercontent.com/14339314/123477377-d0dd6f80-d5b2-11eb-9924-909399c5d142.png)

**To Reproduce**
Run `az webapp up` with a dotnet app where the csproj is not in the root directory

**Expected behavior**
Expected to not have exception

**Comment by yonzhan** [comment]
route to service team

**Comment by calvinsID** [comment]
I haven't worked on this yet, I can knock it off though
