### ISSUE TITLE
WebApp:az appservice domain create: incorrect domain agreements

### ISSUE THREAD

**Issue by calvinsID** [Azure/azure-cli#18651]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Incorrect domain agreements used in `az appservice domain create`. This causes domain preflight to fail on the API side

**To Reproduce**
Run `az appservice domain create` without privacy flag. The domain agreement returns privacy & transfer agreements

**Expected behavior**
privacy agreeement should only be shown when privacy is specified, and transfer agreement shouldn't be shown (since we don't support transfer)

**Comment by yonzhan** [comment]
route to service team
