### ISSUE TITLE
Dependency not found for Az CLI 2.25

### ISSUE THREAD

**Issue by Sbou** [Azure/azure-cli#18668]
**Describe the bug**
When I try to install the Az CLI with this command:
```bash
sudo dnf install -y azure-cli 
```

I receive this error:
Errors during downloading metadata for repository 'mariadb':
  - Status code: 404 for http://yum.mariadb.org/10.2.36/centos7-amd64/repodata/repomd.xml (IP: 142.4.217.28)
Error: Failed to download metadata for repo 'mariadb': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**To Reproduce**

**Expected behavior**
All dependencies are available.

**Environment summary**
OS: Centos

**Additional context**

**Comment by yonzhan** [comment]
installation

**Comment by Volatus** [comment]
@Sbou MariaDB is unrelated to the `Azure CLI`, but checking `http://yum.mariadb.org` reveals that version `10.2.36` is indeed not available there.

**Comment by jiasli** [comment]
We distribute Azure CLI at Microsoft Linux repo https://packages.microsoft.com/yumrepos/azure-cli. Before calling `sudo dnf install -y azure-cli`, please make sure you have added Microsoft Linux repo correct following [Install the Azure CLI on Linux(https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf).

**Comment by Sbou** [comment]
Ok thank you.

After verification, mariadb was already in the machine's yum repo and is not a dependency of Az CLI.
Sorry and thank you.
