### ISSUE TITLE
Doc for --enable-capture

### ISSUE THREAD

**Issue by algattik** [Azure/azure-cli#18664]
In "A boolean value that indicates whether capture description is enabled.", the word "description" should be removed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa949ea-86b1-125e-e7d3-f0f88a2661ab
* Version Independent ID: c8351dbc-7358-ba5b-6757-3929a4a2b42b
* Content: [az eventhubs eventhub](https://docs.microsoft.com/en-us/cli/azure/eventhubs/eventhub?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/eventhubs/eventhub.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/eventhubs/eventhub.yml)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by Saglodha** [comment]
Hi @algattik, Thanks for flagging this. We would triage internally and keep you posted.

**Comment by Saglodha** [comment]
@algattik , this has been fixed in our latest release. Please review the updated help and let us know in case of any concerns. Thanks
