### ISSUE TITLE
[DNS] Default output mode for 'az network dns zone show' should be '-o list'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1866]
By default 'az network dns zone show' uses the table output format.  This is fine for a summary list of zones. However, it's not useful for showing the zone details, since it misses critical data such as the name servers.

The 'list' output format is much better. Can we make this the default for this command?

**Comment by tjprescott** [comment]
The default output is not set per command. The user sets his/her default output method using `az configure`. The default output format for the CLI is actually JSON. It sounds like you have set yours to table though. :)

**Comment by jtuliani** [comment]
I see. I tried `az configure` and I see that yes, I do have 'table' as my default.

However, there is no option to change that default to 'list'. This is all I am offered:

```
What default output format would you like?
 [1] json - JSON formatted output that most closely matches API responses
 [2] jsonc - Colored JSON formatted output that most closely matches API responses
 [3] table - Human-readable output format
 [4] tsv - Tab and Newline delimited, great for GREP, AWK, etc.
```

**Comment by tjprescott** [comment]
You are correct. See #1883.
