### ISSUE TITLE
az image builder output: how to specify SIG version in distribute

### ISSUE THREAD

**Issue by garimakhulbe02** [Azure/azure-cli#18674]
My question is related to [`az image builder output`](https://docs.microsoft.com/en-us/cli/azure/image/builder/output?view=azure-cli-latest#az_image_builder_output_add-examples) command which related to [Azure Image builder](https://github.com/danielsollondon/azvmimagebuilder/tree/master/quickquickstarts) RP.
```
az image builder output add -n mytemplate -g my-group --gallery-name my_shared_gallery \
    --gallery-replication-regions westus brazilsouth \
    --gallery-image-definition linux_image_def --defer
```
Our customers want to add image version with image definition for Shared image gallery. They create image builder template using ```az builder output add ``` commands. It seems this command does not have option to add gallery image definition version. 

They can still add it if they supply whole template in command like this..
```az image builder create -g gaagar-testing -n gaagartest1 --image-template <template name>```

**Comment by yonzhan** [comment]
Compute

**Comment by Juliehzl** [comment]
Hi @garimakhulbe02, please see `az sig image-version create`
