### ISSUE TITLE
vm image accept terms does not allow for programmatic deployment

### ISSUE THREAD

**Issue by drewmullen** [Azure/azure-cli#18685]
**Describe the bug**
Accepting terms for an image via CLI does not allow for programmatic deployment. After accepting the terms the portal screen for "programmatic deployment" is still marked as `disable` for this image (see pic). Also if I try to create an instance i get the error below:

ERROR:
```
 'You have not accepted the legal terms on this subscription: '<>' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='bitnami' offer = 'tom-cat', sku = '7-0'
```

I have several subscriptions that will need marketplace images to be deployed programmatically so i was hoping the `vm image terms accept` would allow for this. 

Based on [this discussion](https://github.com/Azure/azure-cli/issues/3411) this may _actually_ be a feature request. I dont fully understand how the back end API works for terms vs programmatic deployment options. 

 
**To Reproduce**
```
 az vm image terms accept --offer tom-cat --publisher bitnami --plan hourly
{
  "accepted": true,
...
```
![image](https://user-images.githubusercontent.com/3812162/123425250-e2f9e680-d58f-11eb-909a-47f14ae0665f.png)

**Expected behavior**
programmatic deployment should be `enable`

**Environment summary**

macos

```
$ az --version
azure-cli                         2.25.0

core                              2.25.0
telemetry                          1.0.6
```

**Comment by yonzhan** [comment]
Compute

**Comment by drewmullen** [comment]
@yonzhan could you clarify whats happening here? is it expected that accepting image terms should also enable programmatic access?

im asking because im actually trying to use terraform to build these resources (and accept the terms) and some understanding to the above Qs may help eventually [resolve](https://github.com/terraform-providers/terraform-provider-azurerm/issues/12327)

**Comment by Juliehzl** [comment]
@drewmullen As there is re-org in our team. I am new for the work item. Could you share more information about how you get the error including the commands you use and the document link for subscription status?
Here is a link I found https://docs.microsoft.com/en-us/azure/virtual-machines/linux/cli-ps-findimage.
