### ISSUE TITLE
The -public-ip-address in this CLI does not work. Please remove it.

### ISSUE THREAD

**Issue by ChaiSwaddipong** [Azure/azure-cli#18686]
The -public-ip-address in this CLI does not work. Please remove it.

az network application-gateway frontend-ip update [--add]
                                                  [--force-string]
                                                  [--gateway-name]
                                                  [--ids]
                                                  [--name]
                                                  [--no-wait]
                                                  [--private-ip-address]
                                                  [**--public-ip-address]**
                                                  [--remove]
                                                  [--resource-group]
                                                  [--set]
                                                  [--subnet]
                                                  [--subscription]
                                                  [--vnet-name]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22983291-ef1b-2d38-a378-a87533f9167f
* Version Independent ID: ed056af3-1e62-b953-39ea-6e968f47ce14
* Content: [az network application-gateway frontend-ip](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/frontend-ip?view=azure-cli-latest#az_network_application_gateway_frontend_ip_update)
* Content Source: [latest/docs-ref-autogen/network/application-gateway/frontend-ip.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/network/application-gateway/frontend-ip.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
It's already hidden in latest CLI
