### ISSUE TITLE
Importing a public image from docker.io requires authentication

### ISSUE THREAD

**Issue by fgheysels** [Azure/azure-cli#18699]
I want to import a public image from docker.io into our Azure Container Registry, and I want to use `az acr import` for this.

When I execute this command:

```azcli
az acr import -n myregistry --source docker.io/influxdb:1.8 -t onboard/influxdb:1.8
```
I get an error that I need to authenticate (against the source repository: docker.io):

> Unauthorized Unauthorized {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"influxdb","Action":"pull"}]}]}

Why do I need to authenticate against the source repository for importing a public image ?

I've managed to work around this by using:

```
docker pull
docker tag 
docker push
```
And this just works without having to authenticate against docker.io (I had to login to the target ACR however, which is logical).

(everything is executed from within a DevOps pipeline)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/acr.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/acr.yml)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by hkuadithya** [comment]
@fgheysels The source repository used is incorrect. With dockerhub, you must provide `docker.io/library/influxdb:1.8`.

Please try this instead:-
```
az acr import -n <registry> --source docker.io/library/influxdb:1.8 -t onboard/influxdb:1.8
```

**Comment by fgheysels** [comment]
Thanks, this was indeed the reason.

It's not clear to me however, how we can 'find out' the namespace of the image (of influxdb in this case), as you always see that you can just do `docker pull influxdb` for instance.
