### ISSUE TITLE
[Test] Cannot record any VCR tests

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1869]
After rebasing off master, I can no longer record any VCR tests. I get the following error:

`azure.cli.core._util.CLIError: Authentication failed. The 'Authorization' header is missing.`

The version of vcrpy is 1.10.3 after running dev_setup.py.

**Comment by tjprescott** [comment]
PR #1821 inadvertently caused this. If I comment out the stubs I can record successfully.

**Comment by troydai** [comment]
Can you record under python 2.7 or 3.5?

**Comment by derekbekoe** [comment]
PR will be out soon.
Just testing the tests...
