### ISSUE TITLE
Retain azure-cli support for connecting to cosmosdb emulator

### ISSUE THREAD

**Issue by vishcious** [Azure/azure-cli#18705]
**Describe the bug**
Currently, when connecting to the cosmosdb emulator using azcli, there is deprecation notice for the "az cosmosdb database" command. The new alternatives (az cosmosdb SQL Database) doesn't seem to have support for connecting to the cosmosdb emulator since it is lacking the --key argument and always expects the --account-name argument

**To Reproduce**
Run the cosmosdb emulator using the docker container on Mac OS X or linux
Run the following command to list databases on cosmosdb emulator
`az cosmosdb database list --key "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==" --url-connection "https://localhost:8081"`
The following deprecation is displayed
> This command has been deprecated and will be removed in a future release. Use 'cosmosdb sql database, cosmosdb mongodb database, cosmosdb cassandra keyspace or cosmosdb gremlin database' instead.
This command is implicitly deprecated because command group 'cosmosdb database' is deprecated and will be removed in a future release. Use 'cosmosdb sql database, cosmosdb mongodb database, cosmosdb cassandra keyspace or cosmosdb gremlin database' instead.

**Expected behavior**
The newer commands like "az cosmosdb SQL Database" should support the --key argument and thus provide a way to connect to cosmosdb emulator running locally instead of depending on cloud resources

**Environment summary**
OS: Mac OS X

azure-cli                         2.24.2

core                              2.24.2
telemetry                          1.0.6

Python location '/usr/local/Cellar/azure-cli/2.24.2/libexec/bin/python'
Extensions directory '/Users/vishuma/.azure/cliextensions'

Python (Darwin) 3.8.10 (default, May  4 2021, 03:06:52)
[Clang 12.0.0 (clang-1200.0.32.29)]

**Additional context**
As a developer I want a way to work completely isolated from cloud resources during development thus reducing cloud costs and being isolated from other developer's changes

**Comment by yonzhan** [comment]
route to service team

**Comment by MehaKaushik** [comment]
Thanks for raising the issue, we are discussing on the next steps.

**Comment by MehaKaushik** [comment]
ConnectionKey based access to the resources is not supported using [Azure Resource Manager](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview) based operations. CLI intended to expose the ARM operations.

Ideally, there should be some other tool to access your resources using Connection Key based access. Unfortunately, there is none I am aware of. 
CLI is not intended to be used for this purpose, hence we do not intend to support it.

**Comment by MehaKaushik** [comment]
ConnectionKey based access to the resources is not supported using Azure Resource Manager based operations. CLI intended to expose the ARM operations.

Ideally, there should be some other tool to access your resources using Connection Key based access. Unfortunately, there is none I am aware of.
CLI is not intended to be used for this purpose, hence we do not intend to support it.

**Comment by markjbrown** [comment]
The cli module you are using predates our current resource provider and has been deprecated.

In either case, all management clients in Azure such as Azure CLI, Azure PowerShell, ARM Templates, Terraform, etc. are designed to talk to the Azure Resource Management (ARM) endpoint management.azure.com. As such we would not look to provide key-based access to Cosmos DB resources using any current Azure Management clients.

The Cosmos DB emulator supports the dev/test for our data plane SDKs. If you are looking to do dev/test on your DevOps or management operations you can provision a serverless Cosmos DB account. This will have zero cost as long as you are not doing any data plane operations.
