### ISSUE TITLE
No examples for workspace.yml file in `az ml workspace create' command

### ISSUE THREAD

**Issue by prapanw** [Azure/azure-cli#18702]
It is quite painful to not able to find any documentation or example for the YAML file which can be passed into `az ml workspace create` command to create workspace with existing resources. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63446f78-d3ac-0cc3-a102-a1612c54d90e
* Version Independent ID: a20a657c-aeaa-d122-0714-1aa2cfecd966
* Content: [az ml workspace](https://docs.microsoft.com/en-us/cli/azure/ml/workspace?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/workspace.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/workspace.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by banibrata** [comment]
I know it is little frustrating to figure out the full YAML, good news is we  are working on the documentation. In the meantime here is a sample which has all the fields that and **workspace create** can take from file input (-f option), hope it helps:


name: full_workspace_name
location: EastUS
friendly_name: for_fun
description: some desc
storage_account: /subscriptions/SUBID/resourceGroups/RG_NAME/providers/Microsoft.Storage/storageAccounts/name
container_registry: /subscriptions/SUBID/resourceGroups/RG_NAME/providers/Microsoft.ContainerRegistry/registries/name
key_vault: /subscriptions/SUBID/resourceGroups/RG_NAME/providers/Microsoft.KeyVault/vaults/name
application_insights: /subscriptions/SUBID/resourceGroups/RG_NAME/providers/microsoft.insights/components/name

hbi_workspace: true
customer_managed_key:
  key_vault: /subscriptions/SUBID/resourceGroups/RG_NAME/providers/Microsoft.KeyVault/vaults/name
  key_uri: https://kv_name.vault.azure.net/keys/testvm/key_id

private_endpoints:
  approval_type: AutoApproval
  connections:
    my-endpt1:
      subscription_id: SUBID
      resource_group: RG_NAME
      location: EastUS
      vnet_name: vntest
      subnet_name: default

tags:
  purpose: testing
  team: management
