### ISSUE TITLE
[Network] Support new ciphers and SciState Express Route link

### ISSUE THREAD

**Issue by Niteesh** [Azure/azure-cli#18707]
Is your feature request related to a problem? Please describe.

Support for new ciphers ( "GcmAesXpn128",  "GcmAesXpn256") and SciState  for ExpressRouteLink (ExpressRoute Direct)

The powershell support has been added in https://github.com/Azure/azure-powershell/pull/13928

swagger definition is here.
https://github.com/Azure/azure-rest-api-specs/blob/8a09ea0b84aa36cb0e56bab4f4c8efd83a6fdcf6/specification/network/resource-manager/Microsoft.Network/stable/2020-08-01/expressRoutePort.json#L696

Describe the solution you'd like

Similar to the powershell, az-cli should also allow  these 2 ciphers and  SciState to be toggled for ExpressRouteLink in ExpressRouteLinkMacSecConfig.

Describe alternatives you've considered

Additional context

**Comment by yonzhan** [comment]
network

**Comment by Niteesh** [comment]
In the above PR I do not see changes for new ciphers ( "GcmAesXpn128", "GcmAesXpn256"), will these be automatically picked up from the swagger?

**Comment by kairu-ms** [comment]
> In the above PR I do not see changes for new ciphers ( "GcmAesXpn128", "GcmAesXpn256"), will these be automatically picked up from the swagger?

Yes. They are automatically picked from the end value in python SDK.
