### ISSUE TITLE
AKS Get-credentials does not respect KUBECONFIG env var

### ISSUE THREAD

**Issue by Volatus** [Azure/azure-cli#18700]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
`az aks get-credentials` runs fine but writes only to `/Users/xs/.kube/config` despite `export KUBECONFIG=$HOME/.config/kube/config`. Yes, the specified KUBECONFIG file does exist and even has 4 contexts in it.

**To Reproduce**
`az aks get-credentials -n <cluster name> -g <resource group>`. I currently have 4 other contexts in my KUBECONFIG.

**Expected behavior**
The new config for the cluster should be added to the existing kubeconfig file.

**Environment summary**
Installed with brew on M1 MacBook. (darwin/arm64, BigSur)
az version:
```json
{
  "azure-cli": "2.25.0",
  "azure-cli-core": "2.25.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```
`kubectl version --client`:
```
Client Version: version.Info{
Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"
}
```

**Comment by yonzhan** [comment]
route to service team
