### ISSUE TITLE
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by UnexpectedGrit-3853** [Azure/azure-cli#18703]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

On Linux Ubuntu 21.04, I need the command, "az extension add --name azure-iot" to work in "pwsh", but it seems I am blocked by the check that says, "... Could not find a version that satisfies the requirement paho-mqtt==1.5.0 (from azure-iot)" Followed by the statement, "... No matching distribution found for paho-mqtt==1.5.0"

It appears the latest version of "paho-mqtt" is 1.5.1, NOT 1.5.0, and perhaps this is the cause of the error.

The version of Linux I'm using is:
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 21.04
Release: 21.04
Codename: hirsute

It is my understanding that Azure CLI is NOT tested on Ubuntu version 21.04, and yet needs to be tested on 21.04

A more detailed description of the bug I encountered can be found recorded on the Microsoft Q&A Forum link here: https://docs.microsoft.com/en-us/answers/questions/452610/what-to-do-if-linux-34pwsh34-az-extension-add-name.html#answer-454757 

**To Reproduce**

/*** Although I did not setup this machine, I believe the Lab guys followed the given steps below.
       NOTE: This is a Linux Ubuntu 21.04 Lab machine.  We use BOTH Azure CLI AND Azure via "pwsh" (Power Shell) to perform
       various types of Azure testing on SubZero products.
 ***/
1) Download Ubuntu 21.04 ( https://ubuntu.com/download/desktop )
2) Install Python 3.9 on Linux
      sudo apt update
      sudo apt install software-properties-common
      sudo add-apt-repository ppa:deadsnakes/ppa
      sudo apt install python3.9
      sudo apt-get install python-pip

3) Linux Azure CLI Install (with one command)
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

4) pip3 install azure-eventhub
    pip3 install azure-iot-hub
    pip3 freeze   /* To show installed python packages */

5) pwsh
   > az extension add --name azure-devops
   > az extension list
   > az extension add --name azure-iot --debug

ERROR: Could not find a version that satisfies the requirement paho-mqtt==1.5.0 (from azure-iot)
ERROR: No matching distribution found for paho-mqtt==1.5.0
Exception information:
Traceback (most recent call last):
File "/opt/az/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
requirements, max_rounds=try_to_avoid_resolution_too_deep,
File "/opt/az/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
state = resolution.resolve(requirements, max_rounds=max_rounds)
File "/opt/az/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 357, in resolve
raise ResolutionImpossible(causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('paho-mqtt==1.5.0'), parent=LinkCandidate('file:///tmp/tmplxtmlhhr/azure_iot-0.10.13-py3-none-any.whl'))]

**Expected behavior**

5) pwsh
   > az extension add --name azure-iot --debug
/*** Linux Ubuntu 21.04 Power Shell extension "azure-iot" added Successfully! ***/

**Environment summary**

The installation method was not automated (i.e. via Lab operator interacting with Linux 21.04 terminal)

**Additional context**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
A [quick search](https://github.com/search?q=paho-mqtt%3D%3D1.5.0&type=issues) on the error `paho-mqtt==1.5.0` indicates this issue also happens in Windows agents: https://github.com/Azure/azure-devops-cli-extension/issues/1115, https://github.com/actions/virtual-environments/issues/3143, https://github.com/Azure/azure-cli/issues/17555.

Could you share the Azure CLI version you are using and the full output of 

```
az --version
/opt/az/bin/python3 -m pip list
az extension add --name azure-iot --debug
```

Meanwhile, we will investigate in #17555.

**Comment by UnexpectedGrit-3853** [comment]
@jiasli Here is the Azure CLI version information (full output), you requested:
[terminal-capture-20210706.txt](https://github.com/Azure/azure-cli/files/6771065/terminal-capture-20210706.txt)
Hope this is helpful.

**Comment by jiasli** [comment]
Checked the log and the installation failure is caused by 

```
Collecting paho-mqtt==1.5.0
...
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```

Found a stackoverflow post (https://stackoverflow.com/a/61876234/2199657) about this issue.

Checked with a [Ubuntu 21.04 docker image](https://hub.docker.com/_/ubuntu?tab=tags&page=1&ordering=last_updated&name=21.04) and reproduced this issue:

```
docker run -it ubuntu:21.04
```

```
apt update
apt install curl
curl -sL https://aka.ms/InstallAzureCLIDeb | bash
az extension add --name azure-iot
```

Ubuntu 21.04 now only has `libffi.so.8`:

```
# find /usr/lib -name "libffi.so*"
/usr/lib/x86_64-linux-gnu/libffi.so.8.1.0
/usr/lib/x86_64-linux-gnu/libffi.so.8
```

so the bundled python failed to find `libffi.so.7`.

I will work on the build pipeline to add Ubuntu 21.04 support.

**Comment by jiasli** [comment]
As a workaround, could you use `pip install azure-cli` to install from [PyPI](https://pypi.org/project/azure-cli/)? This way, Azure CLI will run with the system python which uses `libffi.so.8`.

Verified with the [Ubuntu 21.04 docker image](https://hub.docker.com/_/ubuntu?tab=tags&page=1&ordering=last_updated&name=21.04):

```
docker run -it ubuntu:21.04
```

```
apt update
apt install python3
apt install python3-pip
pip install azure-cli
az extension add --name azure-iot
```

**Comment by UnexpectedGrit-3853** [comment]
@jiasli Thank you for the suggested workaround!
I tried the following and I'm now able to move forward:
`
sudo apt update
sudo apt install python3
sudo apt install python3-pip
suod pip install azure-cli
pwsh
az extension add --name azure-iot     /* Successful !!! */
`
Here's what I saw in "pwsh":
`
debuguser@debuguser:~/s0-test$ pwsh
PowerShell 7.1.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /home/debuguser/s0-test> az extension add --name azure-iot
PS /home/debuguser/s0-test> az extension list
[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "azure-devops",
    "path": "/home/debuguser/.azure/cliextensions/azure-devops",
    "preview": false,
    "version": "0.18.0"
  },
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "azure-iot",
    "path": "/home/debuguser/.azure/cliextensions/azure-iot",
    "preview": false,
    "version": "0.10.14"
  }
]
PS /home/debuguser/s0-test> exit
debuguser@debuguser:~/s0-test$
`

**Comment by jiasli** [comment]
@UnexpectedGrit-3853, thank you for the confirmation. I am glad the workaround unblocks you. 😊
