### ISSUE TITLE
Application Gateway url-path-map rule create expands /* to files and directories

### ISSUE THREAD

**Issue by craigminihan** [Azure/azure-cli#18736]
**Describe the bug**
On Linux _only_ `url-path-map rule create --paths` will expand `/*` if passed from a *PowerShell* variable to az.

**To Reproduce**
```pwsh
$paths = @('/*')
az network application-gateway url-path-map rule create -g $resourceGroupName --gateway-name $gatewayName --path-map-name $name -n $ruleName --address-pool $pool --http-settings $settings --paths $paths
```

**Expected behavior**
The rule should be created mapping the path /* to the target/settings. Instead on Linux I end up with a rule mapping paths `/bin,/boot,/dev,/etc,/home,/lib,/lib32,/lib64,/libx32,/media,/mnt,/opt,/proc,/root,/run,/sbin,/snap,/srv,/sys,/tmp,/usr,/var,/init`.

**Environment summary**
```
{
  "azure-cli": "2.25.0",
  "azure-cli-core": "2.25.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "front-door": "1.0.14"
  }
}
```
```
$ uname -a
Linux DESKTOP-KBOT7AU 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
```
```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Additional context**
The same code on Windows does not expand the /*.

**Comment by yonzhan** [comment]
network

**Comment by craigminihan** [comment]
FWIW I am also seeing this problem with `az network front-door routing-rule create`, specifically on the `--patterns` argument. If I pass `/*` I end up with `/bin, /boot, /dev` etc.

**Comment by kairu-ms** [comment]
Please use  $paths = @('"/*"')

**Comment by craigminihan** [comment]
@kairu-ms this devivates from the behaviour on Windows - plus it is not documented.

Just to be clear: I am invoking `az` from a *Powershell* session *not* from bash so this is clearly a bug in either the az code or documentation.

My hunch is that PS passes the variable correctly to `az` but the * is expanded in either a bash sub-process or in Python.

**Comment by kairu-ms** [comment]
> @kairu-ms this devivates from the behaviour on Windows - plus it is not documented.
> 
> Just to be clear: I am invoking `az` from a _Powershell_ session **not** from bash so this is clearly a bug in either the `az` code or documentation.
> 
> My hunch is that PS passes the variable correctly to `az` but the * is expanded in either a bash sub-process or in Python.

This is not cli bug. /* will automatically be expanded as arguments before az parse them. I’ve tried that both in bash and powershell.

**Comment by craigminihan** [comment]
@kairu-ms Powershell does not expand `*`!

```
craig@debian:~$ pwsh
PowerShell 7.1.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /home/craig> Write-Host *
*
```
Ergo az is expanding the `*`, or am I missing something here?

**Comment by craigminihan** [comment]
@kairu-ms ok, so I see the problem:
```
$ file $(whereis az)
az::                         cannot open `az:' (No such file or directory)
/usr/bin/az:                 Bourne-Again shell script, ASCII text executable
```
Calling a bash script (see above) from PS causes bash to expand the args before the script gets invoked. IMHO this breaks the contract since in PS land I should not have to care about how az is implemented. 

For example if I'm running a Azure DevOps pipeline on a Windows agent and switch to a Linux agent I'll see totally unexpected behaviour even tho I'm using the same Powershell and az on both. I could even mistakenly add security vulns by adding paths I don't want to expose, ouch.

TBH I'd rather just invoke python directly rather than going via this:
```bash
#!/usr/bin/env bash
bin_dir=`cd "$(dirname "$BASH_SOURCE[0]")"; pwd`
AZ_INSTALLER=DEB "$bin_dir"/../../opt/az/bin/python3 -Im azure.cli "$@"
```

**Comment by kairu-ms** [comment]
Hi @jiasli, could you help to check this issue?

**Comment by jiasli** [comment]
This issue is _not_ relevant to the fact that `az` is actually a Bash script at `/usr/bin/az`. It is a behavior of Bash and PowerShell on Linux.

You will see the `/*` expansion behavior in Bash even without `az` and the `/usr/bin/az` Bash script:

```sh
$ python3 -c "import sys; print(sys.argv)" /*
['-c', '/bin', '/boot', '/dev', '/etc', '/home', '/init', '/lib', '/lib32', '/lib64', '/libx32', '/lost+found', '/media', '/mnt', '/opt', '/proc', '/root', '/run', '/sbin', '/snap', '/srv', '/sys', '/tmp', '/usr', '/var']

$ python3 -c "import sys; print(sys.argv)" "/*"
['-c', '/*']
```

When running the same command from PowerShell on Linux:

```powershell
> python3 -c "import sys; print(sys.argv)" /*
['-c', '/bin', '/boot', '/dev', '/etc', '/home', '/lib', '/lib32', '/lib64', '/libx32', '/lost+found', '/media', '/mnt', '/opt', '/proc', '/root', '/run', '/sbin', '/snap', '/srv', '/sys', '/tmp', '/usr', '/var', '/init']

> python3 -c "import sys; print(sys.argv)" "/*"
['-c', '/*']

> $paths = @('/*')

> python3 -c "import sys; print(sys.argv)" $paths
['-c', '/bin', '/boot', '/dev', '/etc', '/home', '/lib', '/lib32', '/lib64', '/libx32', '/lost+found', '/media', '/mnt', '/opt', '/proc', '/root', '/run', '/sbin', '/snap', '/srv', '/sys', '/tmp', '/usr', '/var', '/init']

> python3 -c "import sys; print(sys.argv)" "$paths"
['-c', '/*']
```

As shown above, if you want a consistent behavior between **PowerShell on Windows** and **PowerShell on Linux**, use double quotes around `$paths` as `"$paths"`.

**Comment by jiasli** [comment]
In PowerShell on Linux:

```powershell
> Write-Host *
*
> Write-Host /*
/*
```

These commands doesn't expand `*` and `/*` because `Write-Host` is PowerShell cmdlet and `*` and `/*` don't go out of PowerShell to the underlying Linux system, so the expansion doesn't take place.

Meanwhile, `az` is a Bash script and `python3` is an executable, so `*` and `/*` goes out of PowerShell to the underlying Linux system, where the expansion occurs.
