### ISSUE TITLE
i can't create virtual machine

### ISSUE THREAD

**Issue by syntax-err0rr** [Azure/azure-cli#18743]
## Describe the bug

**Command Name**
``

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-5.4.0-1051-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.25.0

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
Please provide more detailed info related to which command in Azure CLI, your environment and log info.

**Comment by Vaibhav-Agar** [comment]
This is an auto generated Issue with not enough information to debug. Closing.
