### ISSUE TITLE
az ad user has no update functionality

### ISSUE THREAD

**Issue by KubaO** [Azure/azure-cli#1874]
`ad az user` has no update functionality at the moment. I envision adding the following:

    az ad user update --upn-or-object-id user@example.com

The following parameters would be supported (same as for `az ad update)`:

    --display-name
    --immutable-id
    --password
    --force-change-password-next-login
    
Addition of other parameters in the [`User` entity](https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/entity-and-complex-type-reference#user-entity) would be a separate issue.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
