### ISSUE TITLE
az upgrade failed

### ISSUE THREAD

**Issue by sebastus** [Azure/azure-cli#18746]
## Describe the bug

**Command Name**
`az upgrade`

**Errors:**

New Azure CLI version available. Running 'az upgrade' to update automatically.
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.19.1. Latest version available is 2.25.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): Y
Hit:1 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease
Hit:2 http://ppa.launchpad.net/rmescandon/yq/ubuntu focal InRelease
Hit:3 https://packages.microsoft.com/repos/azure-cli focal InRelease
Hit:4 https://packages.microsoft.com/repos/microsoft-ubuntu-focal-prod focal InRelease
Hit:5 https://deb.nodesource.com/node_14.x focal InRelease
Hit:6 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Hit:7 http://archive.ubuntu.com/ubuntu focal InRelease
Err:8 https://dl.bintray.com/loadimpact/deb stable InRelease
  403  Forbidden [IP: 3.124.176.138 443]
Hit:9 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:10 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:11 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:12 https://download.docker.com/linux/ubuntu focal InRelease [52.1 kB]
Reading package lists... Done
E: Failed to fetch https://dl.bintray.com/loadimpact/deb/dists/stable/InRelease  403  Forbidden [IP: 3.124.176.138 443]
E: The repository 'https://dl.bintray.com/loadimpact/deb stable InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
CLI upgrade failed.
Auto upgrade failed with exit code 0

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az upgrade --all {}`

## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.19.1 *

Extensions:
deploy-to-azure 0.2.0
dev-spaces 1.0.6
azure-devops 0.18.0
aks-preview 0.5.0

```

**Comment by yonzhan** [comment]
upgrade

**Comment by jiasli** [comment]
Similar to https://github.com/Azure/azure-cli/issues/17666

As the error message indicates:

```
Err:8 https://dl.bintray.com/loadimpact/deb stable InRelease
403 Forbidden [IP: 3.124.176.138 443]
...
E: Failed to fetch https://dl.bintray.com/loadimpact/deb/dists/stable/InRelease 403 Forbidden [IP: 3.124.176.138 443]
E: The repository 'https://dl.bintray.com/loadimpact/deb stable InRelease' is no longer signed.
```

this issue doesn't seem to be caused by Azure CLI. It's highly possible you will face the same issue following https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

Could you check if you have other Linux repos added which could cause the 403 failure?

```
ls /etc/apt/sources.list.d/
```

Then you may delete the problematic `https://dl.bintray.com/loadimpact/deb` and try again.

**Comment by sebastus** [comment]
did that. all's well. thanks!
