### ISSUE TITLE
az role definition supports less scopes than REST API

### ISSUE THREAD

**Issue by DSakura207** [Azure/azure-cli#18752]
It appears that create operation does not allow specifying a scope, but other operations allows it.

Besides, Azure REST API allows more scopes, see [here](https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles-rest#list-custom-roles-at-a-scope).

Is the document out of date, or az cli has not implemented it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e649cf-40e3-1b9e-141a-c62d244eda61
* Version Independent ID: 78ea89c1-7c56-e33b-d10a-dae05642aa34
* Content: [az role definition](https://docs.microsoft.com/en-us/cli/azure/role/definition?view=azure-cli-latest#az_role_definition_create)
* Content Source: [latest/docs-ref-autogen/role/definition.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/role/definition.yml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Currently `az role definition create` doesn't support `--scope`. If this is mandatory, could you try to use `az rest` to [invoke the REST API directly](https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles-rest)?

(If you use Windows and PowerShell, please be aware of PowerShell quoting issue: https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md )

**Comment by DSakura207** [comment]
Thank you @jiasli , I'll give it a try.
