### ISSUE TITLE
WebApp:Don't include "ipSecurityRestrictions" when updating settings

### ISSUE THREAD

**Issue by mahatabur** [Azure/azure-cli#18763]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When a user did an config update - we roundtrip the full config (event those unchanged config back). The issue is ARM cannot tell whether the config settings are new or changed - and enforce RBAC policy across.

Sample error:

"code": "LinkedAuthorizationFailed",

"message": "The client 'xyz' with object id 'xyz-xyz-xyz-xyz-xyz' has permission to perform action 'Microsoft.Web/sites/config/write' on scope '/subscriptions/xxx-xxx-xxx-xxx-xxx/resourceGroups/xxx/providers/Microsoft.Web/sites/xxx/config/web'; however, it does not have permission to perform action 'joinViaServiceEndpoint/action' on the linked scope(s) '/subscriptions/xxx-xxx-xxx-xxx-xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xxx/subnets/xxx_x.z.x.xxx_zz' or the linked scope(s) are invalid." }

**Comment by mahatabur** [comment]
@panchagnula FYI.

**Comment by yonzhan** [comment]
route to service team

**Comment by calvinsID** [comment]
Closing since seems like duplicate of https://github.com/Azure/azure-cli/issues/14857. Please update your CLI to get the fix
