### ISSUE TITLE
azure cli is not opening

### ISSUE THREAD

**Issue by vennela1001** [Azure/azure-cli#18760]
hi sir/madam,
           this is vennela. while using az login command in powershell then it shows some problem in azure cli in github repository.
plz kindly help for this senario.
         thankyou,
regards,
vennela

**Comment by yonzhan** [comment]
Please let us know your detailed info related to which CLI command and error log.

**Comment by vennela1001** [comment]
Hi sir,
        My issue got resolved.


Thanks &regards,
Vennela
