### ISSUE TITLE
The `az databoxedge device create` command failed

### ISSUE THREAD

**Issue by PARADISSEEKR** [Azure/azure-cli#18767]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When create a device with `--sku Edge`, I get the following error:`(GatewayUserErrorSkuDisabledRegion) Sku 'Edge' is not enabled in this region.`.
According to the the information:`(LocationNotAvailableForResourceType) The provided location 'abc' is not available for resource type 'Microsoft.DataBoxEdge/DataBoxEdgeDevices'. List of available regions for the resource type is 'eastus,westeurope,southeastasia,eastus2euap,centraluseuap'.`
I tried the following commands:
`az databoxedge device create -l eastus --sku "Edge" --name testdev1 -g testrg`
`az databoxedge device create -l westeurope --sku "Edge" --name testdev1 -g testrg`
`az databoxedge device create -l southeastasia --sku "Edge" --name testdev1 -g testrg`
`az databoxedge device create -l eastus2euap --sku "Edge" --name testdev1 -g testrg`
`az databoxedge device create -l centraluseuap --sku "Edge" --name testdev1 -g testrg`
All output errors:`(GatewayUserErrorSkuDisabledRegion) Sku 'Edge' is not enabled in this region.`

**To Reproduce**

Examples:
    Create a Data Box Edge resource.
        `az databoxedge device create --location "eastus" --sku "Edge" --name "testedgedevice" --resource-group "GroupForEdgeAutomation"`

**Expected behavior**

**Environment summary**

python
Windows-10-10.0.19041
Python 3.8.9
Installer: pip
azure-mgmt-databoxedge==1.0.0 min_api='2019-08-01'
azure-cli 2.23.0

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by anponnet** [comment]
Sku "Edge" is being retired and we are not allowing new subscriptions to create it.  https://azure.microsoft.com/en-in/updates/azure-stack-edge-pro-fpga-is-retiring-on-28-february-2024/

you can consider creating a GPU device https://docs.microsoft.com/en-us/azure/databox-online/azure-stack-edge-gpu-overview

Sku: 1GPU = EdgeP_Base
         2GPU = EdgeP_High
