### ISSUE TITLE
The `az databoxedge bandwidth-schedule create` command failed

### ISSUE THREAD

**Issue by PARADISSEEKR** [Azure/azure-cli#18765]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When create a bandwidth schedule, I get the following error.
command:
`az databoxedge bandwidth-schedule create --days Sunday -d testdev -n bd1 --rate-in-mbps 2 -g myrg --start 0:0:0 --stop 12:00:00`
error:
`(RestApiInternalError) The REST API call encountered an internal error.
Wait for a few minutes and then try the operation again. If the issue persists, contact Microsoft Support.`
debuginfo:
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/dtest/providers/Microsoft.DataBoxEdge/dataBoxEdgeDevices/dev1/bandwidthSchedules/bd1?api-version=2019-08-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '91'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '2e5a33f4-e08d-11eb-b852-b07b250bf939'
cli.azure.cli.core.sdk.policies:     'CommandName': 'databoxedge bandwidth-schedule create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--days -d -n --rate-in-mbps -g --start --stop --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.26.0 (PIP) azsdk-python-azure-mgmt-databoxedge/1.0.0 Python/3.8.9 (Windows-10-10.0.19041-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"start": "0:0:0", "stop": "12:00:00", "rateInMbps": 2, "days": ["Sunday"]}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/dtest/providers/Microsoft.DataBoxEdge/dataBoxEdgeDevices/dev1/bandwidthSchedules/bd1?api-version=2019-08-01 HTTP/1.1" 500 237
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '237'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'f02abc5d-1178-46f1-917e-d6ab061d2c6c'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '2e5a33f4-e08d-11eb-b852-b07b250bf939'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'f02abc5d-1178-46f1-917e-d6ab061d2c6c'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20210709T081054Z:f02abc5d-1178-46f1-917e-d6ab061d2c6c'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 09 Jul 2021 08:10:54 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "error": {
    "code": "RestApiInternalError",
    "message": "The REST API call encountered an internal error.\r\nWait for a few minutes and then try the operation again. If the issue persists, contact Microsoft Support."
  }
}

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\code\benv\lib\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "d:\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 657, in execute
    raise ex
  File "d:\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "d:\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "d:\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "d:\azure-cli\src\azure-cli-core\azure\cli\core\commands\command_operation.py", line 121, in handler
    return op(**command_args)
  File "d:\azure-cli\src\azure-cli\azure\cli\command_modules\databoxedge\manual\custom.py", line 173, in databoxedge_bandwidth_schedule_create
    return sdk_no_wait(no_wait,
  File "d:\azure-cli\src\azure-cli-core\azure\cli\core\util.py", line 648, in sdk_no_wait
    return func(*args, **kwargs)
  File "D:\benv\lib\site-packages\azure\mgmt\databoxedge\v2019_08_01\operations\_bandwidth_schedules_operations.py", line 283, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "D:\code\benv\lib\site-packages\azure\mgmt\databoxedge\v2019_08_01\operations\_bandwidth_schedules_operations.py", line 234, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (RestApiInternalError) The REST API call encountered an internal error.
Wait for a few minutes and then try the operation again. If the issue persists, contact Microsoft Support.

cli.azure.cli.core.azclierror: (RestApiInternalError) The REST API call encountered an internal error.
Wait for a few minutes and then try the operation again. If the issue persists, contact Microsoft Support.
az_command_data_logger: (RestApiInternalError) The REST API call encountered an internal error.
Wait for a few minutes and then try the operation again. If the issue persists, contact Microsoft Support.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000001F564B958B0>]

**To Reproduce**

Examples:
    Create a bandwidth schedule.
        az databoxedge bandwidth-schedule create --name "bandwidth-1" --device-name "testedgedevice"
        --days "Sunday" "Monday" --rate-in-mbps 100 --start "0:0:0" --stop "13:59:0" --resource-
        group "GroupForEdgeAutomation"

**Expected behavior**

**Environment summary**

python
Windows-10-10.0.19041
Python 3.8.9
Installer: pip
azure-mgmt-databoxedge==1.0.0
azure-cli 2.23.0

**Additional context**

**Comment by yonzhan** [comment]
databoxedge

**Comment by PARADISSEEKR** [comment]
Failed because the device is not activated, refer to these document to activate the device.
https://docs.microsoft.com/en-us/azure/databox-gateway/data-box-gateway-deploy-connect-setup-activate
https://docs.microsoft.com/en-us/azure/databox-online/azure-stack-edge-gpu-deploy-activate
