### ISSUE TITLE
Missing datastore YAML schema

### ISSUE THREAD

**Issue by Bunzab** [Azure/azure-cli#18776]
The example for `az ml datastore create` creates a datastore from a YAML file but there is no indication as to how that file should be formatted. Searching only returns this page. Can you please link to the YAML schema.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27bfd14b-bddd-771f-1364-c52a991b75f0
* Version Independent ID: e0750d23-f2a0-7364-e6dc-34ffa51503d4
* Content: [az ml datastore](https://docs.microsoft.com/en-us/cli/azure/ml/datastore?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/datastore.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/datastore.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by Mossaka** [comment]
Thanks @Bunzab , we have an internal tracking item to add docs for YAML schemas for V2 CLI resources. In the meantime, you can use the Azure Machine Learning extension in VSCode to help writing the YAML schema.

Once you installed that extension, you can create a datastore yaml by typing the following command:
![image](https://user-images.githubusercontent.com/5447827/126374429-689369f7-c24d-42f6-b39f-b70930d16551.png)
