### ISSUE TITLE
Link icon missing when hovering the mouse over headings

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#18771]
**Describe the bug**
The little link icon 🔗 on https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux doesn't show up when hovering the mouse over headings:

![image](https://user-images.githubusercontent.com/4003950/124901854-f76cc300-e014-11eb-8a1a-26ff75fd4e37.png)

It works on other pages like https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli

![image](https://user-images.githubusercontent.com/4003950/124901826-f176e200-e014-11eb-80cd-6b7b8d880e2c.png)

**Comment by yonzhan** [comment]
Link icon missing

**Comment by jiasli** [comment]
Fixed by docs team.
