### ISSUE TITLE
Azure Active Directory Graph would be deprecated soon. When do you plan to upgrade az ad to use Microsoft Graph endpoint?

### ISSUE THREAD

**Issue by jiaojiaoxia** [Azure/azure-cli#18775]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa048db2-b924-889c-c105-2a676714b0ee
* Version Independent ID: 5774d883-1b16-d4b9-8d61-4694af8d9341
* Content: [az ad](https://docs.microsoft.com/en-us/cli/azure/ad?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ad.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ad.yml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiaojiaoxia** [comment]
Azure Active Directory Graph would be deprecated soon. When do you plan to upgrade az ad to use Microsoft Graph endpoint

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The migration to Microsoft Graph is being tracked at https://github.com/Azure/azure-cli/issues/12946.
