### ISSUE TITLE
az storage blob service-properties set?

### ISSUE THREAD

**Issue by valencik** [Azure/azure-cli#1880]
The `az storage blob service-properties show` command let's you *get* various properties like Azure Storage Analytics, is there a way to *set* such properties?
In particular I would like to enable Azure Storage Analytics on Blob of a storage account from the `az` cli.

Relevant Docs:
https://docs.microsoft.com/en-us/cli/azure/storage/blob/service-properties
https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/enabling-and-configuring-storage-analytics

**Comment by tjprescott** [comment]
Do the `az storage logging` and/or `az storage metrics` commands accomplish what you are looking for?

**Comment by troydai** [comment]
@valencik I will close this issue for now since we have commands accomplish the equivalent operations. Feel free to reopen if you have any specific scenario in mind.

**Comment by derekbekoe** [comment]
Can we re-open this? I'm trying to set the default API version for blobs and `az storage logging/metrics` does not let me do this.

https://stackoverflow.com/questions/11503776/serving-video-content-from-azure-blob-storage

**Comment by codestothestars** [comment]
Additional capabilities for updating storage blob service properties appear to have been made available recently.

Per [Static website hosting in Azure Storage](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website), I was able to enable the static website service after installing the storage preview extension.

```shell
az extension add --name storage-preview

az storage blob service-properties update --account-name <ACCOUNT_NAME> --static-website --404-document <ERROR_DOCUMENT_NAME> --index-document <INDEX_DOCUMENT_NAME>
```

Thanks, Azure CLI team!
