### ISSUE TITLE
Web App - Multiple issues.

### ISSUE THREAD

**Issue by sjwaight** [Azure/azure-cli#18807]
1. Cannot navigate intra-page to command "az webapp create" from the main list of commands. "In this article" link works fine though.

2. The Java samples for 'az webapp create' is incorrectly formatted

az webapp create -g MyResourceGroup -p MyPlan -n MyUniqueAppName --runtime "java|11|Java SE|8"

az webapp create -g MyResourceGroup -p MyPlan -n MyUniqueAppName --runtime "java:11:Java SE:8"

has an incorrectly formatted "runtime" argument.

The correct format is:

az webapp create -g MyResourceGroup -p MyPlan -n MyUniqueAppName --runtime "JAVA|8-java11"

az webapp create -g MyResourceGroup -p MyPlan -n MyUniqueAppName --runtime "JAVA:8-java11"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by sjwaight** [comment]
Looks like (1) has been fixed. If (2) is due to platform differences that's fine - as you suggested the Docs maybe need to be clearer on that front. Moving to closed.
