### ISSUE TITLE
Error while enabling HTTPS on front-door frontend-endpoint

### ISSUE THREAD

**Issue by simedbn** [Azure/azure-cli#18805]
Hello, 

when i run this command (V 2.14.0) : 

**az network front-door frontend-endpoint enable-https `
            --front-door-name 'simed' `
            --name 'frontendEndpoint2' `
            --resource-group 'simed-api' `
            --certificate-source AzureKeyVault `
            --minimum-tls-version '1.2' `
            --secret-name 'wildcard-simed' `
            --vault-id '/subscriptions/mysubscriptionguid/resourceGroups/dev-certificate- management/providers/Microsoft.KeyVault/vaults/mykey'**

I get this error : 

![image](https://user-images.githubusercontent.com/15849678/125173281-66355200-e1b6-11eb-89ea-4f67b0f7c7ba.png)

Any idea please ? 
Thank you in advance

**Comment by yonzhan** [comment]
route to service team

**Comment by t-bzhan** [comment]
Hi @simedbn , I could repro the error. It seems that some old versions of Az CLI (2.14.0 is rather old now) are not compatible with recent front-door extensions. Could you try to update you CLI version to the latest. The command works with no error with the latest CLI and front-door extension.
