### ISSUE TITLE
[DNS] Tag keys are capitalized when creating a zone

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1881]
Suppose I create a zone:

`az network dns zone create -g rg1 -n test.cli --tags a="b c" d="ef" -o list`

The output looks like this:

```
Etag                      : 00000003-0000-0000-6ac4-15cad777d201
Id                        : /subscriptions/.../resourceGroups/rg1/providers/Microsoft.Network/dnszones/test.cli
Location                  : global
Max Number Of Record Sets : 5000
Name                      : test.cli
Number Of Record Sets     : 2
Resource Group            : rg1
Type                      : Microsoft.Network/dnszones
Name Servers              :
   ns1-06.azure-dns.com.
   ns2-06.azure-dns.net.
   ns3-06.azure-dns.org.
   ns4-06.azure-dns.info.
Tags                      :
   A : b c
   D : ef
```

Somehow, the key of each tag has been capitalized (a -> A, d -> D).  That shouldn't happen.

I saw the on DNS zone create. Obviously, when fixing, you need to look more broadly (DNS zone updates, DNS record set create/updates, other resources types, etc.

**Comment by jtuliani** [comment]
On further investigation, this _may_ be an issue with the -o list output. The tag key shows as lower case if I use JSON output. Still needs to be fixed though.

**Comment by tjprescott** [comment]
See #1883. If the list output survives, we will fix this.
