### ISSUE TITLE
az acr run failing with 'NoneType' object is not callable

### ISSUE THREAD

**Issue by bartsmykla** [Azure/azure-cli#18832]
## Describe the bug

Our CICD pipeline is failing in a step to clean ACR repositories:

```sh
#!/bin/bash -eo pipefail
PURGE_CMD="acr purge \
  --filter 'kumactl:.*' \
  --filter 'kuma-cp:.*' \
  --filter 'kuma-dp:.*' \
  --filter 'kuma-init:.*' \
  --filter 'kuma-universal:.*' \
  --untagged \
  --ago 1s"

az acr run \
   --cmd "${PURGE_CMD}" \
   --registry "${AZURE_ACR_REGISTRY}" \
   /dev/null
```

**Command Name**
`az acr run`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/run.py", line 93, in acr_run
    variant=platform_variant
TypeError: 'NoneType' object is not callable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr run --cmd {} --registry {} {}`

## Environment Summary
```
Linux-4.15.0-1106-aws-x86_64-with-debian-9.12
Python 3.6.10
Installer: DEB

azure-cli 2.26.0
```

**Comment by yonzhan** [comment]
route to service team

**Comment by daniel347x** [comment]
Same issue as https://github.com/Azure/azure-cli/issues/18857 and https://github.com/Azure/azure-cli/issues/18841...
I too am experiencing this ...

**Comment by daniel347x** [comment]
Solution for anyone reading this: just don't use the Azure Portal cloud shell for the time being to perform the ACR builds. Install the Azure CLI into some other Linux system, log in, and issue the ACR commands from there.

**Comment by johnynfulleffect** [comment]
@daniel347x really?  I'm not using cloud shell but on a private agent running in docker/aks.

**Comment by luisdlp** [comment]
A hotfix for the cli has been released.  Please use Version 2.26.1 for the cli:
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#july-14-2021

**Comment by andygjp** [comment]
Instructions to update azure-cli can be found here: https://github.com/actions/virtual-environments/issues/3735#issuecomment-880623386

These instruction got my hosted Ubuntu agent working again.
