### ISSUE TITLE
ssl-profile --trusted-client-cert not working as expected

### ISSUE THREAD

**Issue by brentmcconnell** [Azure/azure-cli#18838]
I am trying to use az network application-gateway ssl-profile with --trusted-client-cert but only get "(InvalidRequestFormat) Cannot parse the request" whenever I include this option.  I have tried using cert names that have already been uploaded.  I also tried using the ids of those certs.  I have tried it using [] array syntax and I have tried without separated by commas.  I am using MacOS 11.4 with az version 2.26.0 with zsh.  Install method was via brew.  If I don't include the --trusted-client-cert I can create a profile that has the certs available but not selected.  I have to use the portal to assign certs to the profile.  The --trusted-client-cert option looks like the correct option to use to perform this action but better documentation needs to be provided to understand how this can be done via the cli.

**Comment by yonzhan** [comment]
network

**Comment by brentmcconnell** [comment]
I was able to figure out that it takes cert ids in double quotes separated by spaces.  FYI, in my case each id had to have quotes around it.
