### ISSUE TITLE
CLI Extension support - add new features to SIG Gallery and Gallery Image

### ISSUE THREAD

**Issue by hjkumar** [Azure/azure-cli#18848]
**Resource Provider**
Azure.Compute

**Description of Feature or Work Requested**
1) Add a feature named "architecture" under the image-definition object in Shared Image Gallery.
Image definition CLI docs: https://docs.microsoft.com/en-us/cli/azure/sig/image-definition?view=azure-cli-latest
**CLI change:**
az sig image-definition create --gallery-image-definition
                               --gallery-name
                               --offer
                               --os-type {Linux, Windows}
                               --publisher
                               --resource-group
                               --sku
                               [--description]
                               [--disallowed-disk-types]
                               [--end-of-life-date]
                               [--eula]
                               [--features]
                               [--hyper-v-generation {V1, V2}]
                               **[--architecture {x64, Arm64}]**
                               [--location]
                               [--maximum-cpu-core]
                               [--maximum-memory]
                               [--minimum-cpu-core]
                               [--minimum-memory]
                               [--os-state {Generalized, Specialized}]
                               [--plan-name]
                               [--plan-product]
                               [--plan-publisher]
                               [--privacy-statement-uri]
                               [--release-note-uri]
                               [--subscription]
                               [--tags]

This is non-updatable. It should show up in show gallery image-definition/list gallery image-definition /show-shared gallery image-definition /list-shared gallery image-definition

2) Add a feature "softdelete-enabled" to the gallery object in SIG.

Gallery CLI docs: https://docs.microsoft.com/en-us/cli/azure/sig?view=azure-cli-latest#az_sig_create

**CLI change:**
az sig create --gallery-name
              --resource-group
              [--description]
              [--location]
              [--permissions {Groups, Private}]
              **[--softdelete-enabled {False, True}]**
              [--subscription]
              [--tags]

This can be updated
It should show up in show gallery/list gallery

**Minimum API Version Required**
2021-03-01

**Swagger Link**
Swagger PR link: https://github.com/Azure/azure-rest-api-specs/pull/15039

The diff can be seen from here: https://github.com/Azure/azure-rest-api-specs/pull/15039/files/f0fa61f80d2b3eb149e65350ac7cc2dfcc7d3e37..6b8acf666dab90146b4f14ee955a27c84555638b

**Target Date**
(for private preview)
Architecture - 2022-01-01
Soft Delete - 2021-08-23

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@hjkumar  Hi, since we have too many urgent requirements recently, we need to plan the soft deleting feature to be completed in 2021-10-05. May I ask can this date meet your expectations?

**Comment by PARADISSEEKR** [comment]
Hi @hjkumar ,when I use the softdelete parameter of sig create, the service returns my subscription is not registered with the feature Microsoft.Compute/SIGSoftDelete, how do I register it?

**Comment by zhoxing-ms** [comment]
> when I use the softdelete parameter of sig create, the service returns my subscription is not registered with the feature Microsoft.Compute/SIGSoftDelete, how do I register it?

@kangsun-ctrl Could you please take a look at this question and help our subscription register `Microsoft.Compute/SIGSoftDelete`

**Comment by zhoxing-ms** [comment]
@kangsun-ctrl By the way, it may be because this PR Azure/azure-rest-api-specs#15039 is not merged, at present, there is no parameter `architecture` in the model `GalleryImage(Resource)`  [code link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2020_09_30/models/_models.py#L1840)  of Python SDK. Could you update the Swagger and release a new Python SDK version for this parameter?
