### ISSUE TITLE
YAML file details about creating a new AML workspace

### ISSUE THREAD

**Issue by sunnyhay** [Azure/azure-cli#18847]
Hello,

  Please share more details about how to create a new AML workspace using YAML configuration. Samples will be highly appreciated. Current AML documentation does not have such sample/YAML configuration details.
  Thanks,

Harry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63446f78-d3ac-0cc3-a102-a1612c54d90e
* Version Independent ID: a20a657c-aeaa-d122-0714-1aa2cfecd966
* Content: [az ml workspace](https://docs.microsoft.com/en-us/cli/azure/ml/workspace?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/workspace.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/workspace.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by sunnyhay** [comment]
Any update? Thanks.

**Comment by harneetvirk** [comment]
A sample for creating a workspace is posted on a similar request is on another issue: https://github.com/Azure/azure-cli/issues/18702

**Comment by sunnyhay** [comment]
Thank you for the sample. It works.

**Comment by deeikele** [comment]
Please also see https://github.com/Azure/azureml-examples/tree/cli-preview/cli/resources/workspace
