### ISSUE TITLE
RestorePoints

### ISSUE THREAD

**Issue by roipmsft** [Azure/azure-cli#18844]
Compute Resource Provider
Description of Feature or Work Requested
Restore Points api was recently released in 2021-03-1 Compute Swagger

https://docs.microsoft.com/en-us/rest/api/compute/restore-points

https://docs.microsoft.com/en-us/rest/api/compute/restore-point-collections

2021-03-01 Swagger
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2021-03-01/compute.json

**Comment by yonzhan** [comment]
RestorePoints

**Comment by zhoxing-ms** [comment]
@roipmsft Hi, since we have too many urgent requirements recently, we need to plan it to be completed in 2021-10-05. May I ask can this date meet your expectations?

**Comment by zhoxing-ms** [comment]
@roipmsft Since there are too many contents in the Swagger of Compute, could you please provide a PR that shows the changes related to this requirement?
In addition, it would be better if you could provide specific commands and parameter related designs that need to be supported?

**Comment by PARADISSEEKR** [comment]
Hi, @roipmsft  only `restore-point-collections` and no `restore-points` are found in this swagger, do `restore-points` need to be added to CLI

**Comment by roipmsft** [comment]
> Hi, @roipmsft only `restore-point-collections` and no `restore-points` are found in this swagger, do `restore-points` need to be added to CLI
The Swagger does not have restore points.
 "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/restorePointCollections/{restorePointCollectionName}/restorePoints/{restorePointName}": {
      "put": {
        "operationId": "RestorePoints_Create",
        "description": "The operation to create the restore point. Updating properties of an existing restore point is not allowed",
Yes, restore-points does need to be added to CLI.
