### ISSUE TITLE
`az acr credential show` should also display login server

### ISSUE THREAD

**Issue by iainfoulds** [Azure/azure-cli#1884]
When working with Azure Container Registry and you enabled the admin user, the portal will then display the login server and the admin credentials on the one blade.

From CLI, `az acr show` will return the loginServer, but not credentials. Cool. `az acr credential show` for a given registry will then show the credentials you need. But, it would be helpful if `az acr credential show` would also display the loginServer. 

You have to specify a resource group and registry, so that login server should be valid for all the accounts that would potentially be granted access, unless I'm missing something? Having to do both `az acr show` and `az acr credential show` to be able to then `docker login` seem likes one more step than it should be.

**Comment by lostintangent** [comment]
+1

**Comment by lostintangent** [comment]
Additionally, I'd almost be interested to see `az acr create` command return the admin username and password when you specify the `--admin-enabled` flag. That way, you don't need to create the instance, and then immediately turn around to grab the generated credentials.

**Comment by djyou** [comment]
We are actually planning to even remove username from get credential result and be consistent with `az storage account show` and `az storage account keys list`. This is worth discussing though as it can potentially improve usability. @SajayAntony

**Comment by sajayantony** [comment]
Given the current work of enabling repo based tokens going forward, we will first class credentials in that scenario. Might be worth considering closing this since there is not planned action on this.
