### ISSUE TITLE
Potential conflict in `generating_ssh_keys` provided by azure-cli-core

### ISSUE THREAD

**Issue by FumingZhang** [Azure/azure-cli#18854]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When performing concurrent tests recently, we found that the [`generate_ssh_keys`](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/keys.py#L37) function provided by the cli core has potential concurrency conflicts. 

In the existing implementation, when multiple processes try to create an ssh key, process *A* may have created a file but has not yet written key data, while process *B* reads an empty file at this time and obtains illegal empty key data.

In our module(acs/aks-preview), the example of calling this function is located in the [validator](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_validators.py#L27).

For end users, this problem may also occur when users create multiple clusters (`az aks create`) at the same time and there is no ssh key that has been generated.

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

A simple solution is to add a global lock to the `generate_ssh_keys` function.

**Comment by yonzhan** [comment]
@jiasli for awareness
