### ISSUE TITLE
CLI extension support - add ReplicationMode to SIG gallery image version

### ISSUE THREAD

**Issue by hjkumar** [Azure/azure-cli#18851]
**Resource Provider**
Azure.Compute

**Description of Feature or Work Requested**

Add a feature named "replication mode" under the image-definition object in Shared Image Gallery.

The backend changes and ARM manifest changes for this feature are currently being rolled out.

Image version CLI docs: https://docs.microsoft.com/en-us/cli/azure/sig/image-version?view=azure-cli-latest

CLI change:
az sig image-version create --gallery-image-definition
                            --gallery-image-version
                            --gallery-name
                            --resource-group
                            [--data-snapshot-luns]
                            [--data-snapshots]
                            [--data-vhds-luns]
                            [--data-vhds-sa]
                            [--data-vhds-uris]
                            [--end-of-life-date]
                            [--exclude-from-latest {false, true}]
                            [--location]
                            [--managed-image]
                            [--no-wait]
                            [--os-snapshot]
                            [--os-vhd-storage-account]
                            [--os-vhd-uri]
                            [--replica-count]
                           **[--replication-mode {Full, Shallow}]**
                            [--storage-account-type {Premium_LRS, Standard_LRS, Standard_ZRS}]
                            [--subscription]
                            [--tags]
                            [--target-region-encryption]
                            [--target-regions]
              
This replicationMode parameter is non-updatable. 
It should show up in show gallery image-version/list gallery image-version

**Minimum API Version Required**
2021-07-01

**Swagger Link**

Swagger PR link: Azure/azure-rest-api-specs#15039

The diff can be seen from here: https://github.com/Azure/azure-rest-api-specs/pull/15039/files/f0fa61f80d2b3eb149e65350ac7cc2dfcc7d3e37..6b8acf666dab90146b4f14ee955a27c84555638b

**Target Date**
(for private preview)
2021-09-01

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@hjkumar Hi, since we have too many urgent requirements recently, we need to plan it to be completed in 2021-10-05. May I ask can this date meet your expectations?
