### ISSUE TITLE
`az ad sp create-for-rbac` returning null for password if the SP already exists

### ISSUE THREAD

**Issue by jmspring** [Azure/azure-cli#1886]
When creating a service principal using the command `az ad sp create-for-rbac`, the resulting JSON contains a value of "null" for the password.

```bash
jims@azcat:~$ export SUBSCRIPTION_ID="04f7ec88-8e28-41ed-8537-5e17766001f5"
jims@azcat:~$ az account set --subscription="${SUBSCRIPTION_ID}"
jims@azcat:~$ export SP_JSON=`az ad sp create-for-rbac -n="http://jmsacsdcos" --role="Contributor" --scopes="/subscriptions/${SUBSCRIPTION_ID}"`
jims@achat:~$ echo $SP_JSON
{ "appId": "d465c320-20dc-4502-9f68-1d82e7690d48", "displayName": null, "name": "http://jmsacsdcos", "password": null, "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47" }
```

@colemickens

**Comment by colemickens** [comment]
cc: @yugangw-msft

**Comment by colemickens** [comment]
What version @jmspring?

**Comment by jmspring** [comment]
jims@azcat:~$ az --version
azure-cli (0.1.1b2)

acr (0.1.1b1)
acs (0.1.1b1)
appservice (0.1.1b1)
cloud (0.1.1b1)
component (0.1.0rc1)
configure (0.1.1b2)
container (0.1.1b1)
context (0.1.1b1)
core (0.1.1b2)
feedback (0.1.1b1)
network (0.1.1b1)
nspkg (0.1.1)
profile (0.1.1b1)
resource (0.1.1b1)
role (0.1.1b1)
storage (0.1.1b1)
vm (0.1.1b1)

Python (Linux) 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]

**Comment by jmspring** [comment]
Just updated to 0.1.1b2 (using az component update) and things work correctly now.

Note, 0.1.1b1 was installed yesterday evening using `pip install --user azure-cli`

**Comment by jmspring** [comment]
An additional note - I did an `az component update`, but there was no output, and then a subsequent run provided a password for the service principal.

Seems like it is an inconsistency as it is working now.  Will run a trial of creating a number of SPs and see...

**Comment by jpoon** [comment]
Hit the same error just now with `azure-cli (0.1.1b3)`

```
» az ad sp create-for-rbac --name "http://japoon-kubernetes" --role="Contributor" --scopes="/subscriptions/04f7ec88-8e28-41ed-8537-5e17766001f5"
{
  "appId": "841de03e-fba4-408c-ab64-3b0d798ad8d0",
  "displayName": null,
  "name": "http://japoon-kubernetes",
  "password": null,
  "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47"
}
```

Through the portal, deleted the app registration for the above and retried the same command.

```
» az ad sp create-for-rbac --name "http://japoon-kubernetes" --role="Contributor" --scopes="/subscriptions/04f7ec88-8e28-41ed-8537-5e17766001f5"
Retrying role assignment creation: 1/24
Retrying role assignment creation: 2/24
{
  "appId": "512d197f-2abe-4e7e-ae6e-7dd448769ed5",
  "displayName": "azure-cli-2017-02-17-02-19-49",
  "name": "http://japoon-kubernetes",
  "password": "[A VALID PASSWORD]",
  "tenant": "72f988bf-86f1-41af-91ab-2d7cd011db47"
}

**Comment by yugangw-msft** [comment]
The cause is the SP already exists, and under this context, you should use `role assignment create` to configure access or `reset-credentials` to get new creds.
I can throw to get it explicit, but hope the comment here clarifies for this moment

**Comment by jpoon** [comment]
Running that same command again gives me this:

```
» az ad sp create-for-rbac --name "http://japoon-kubernetes" --role="Contributor" --scopes="/subscriptions/04f7ec88-8e28-41ed-8537-5e17766001f5"
The role assignment already exists.
```

This seems different from returning a `null` password?

**Comment by yugangw-msft** [comment]
>This seems different from returning a null password?

Correct. It is different. The previous error occurred when you have a SP, but have not been associated it with a role assignment. 

And, agreed, let us throw.
