### ISSUE TITLE
Cannot create VMSS in an Edge Zone using the --edge-zone argument.

### ISSUE THREAD

**Issue by adhgupta** [Azure/azure-cli#18880]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Creating a Virtual Machine Scale Set using the Azure CLI fails with "unrecognized arguments: --edge-zone". 

**To Reproduce**

Azure CLI version: 2.26.1
Run the following command:
az vmss create --name myVMss --resource-group myResourceGroup --public-ip-address-dns-name my-globally-dns-name --load-balancer MyLoadBalancer --vnet-name testVnet --subnet default --image UbuntuLTS --admin-password password --admin-username test --egde-zone microsoftlosangeles1

Output: unrecognized arguments: --egde-zone microsoftlosangeles1

**Expected behavior**

The command should succeed without an error

**Environment summary**

PS C:\Users\adhipgupta> az version
{
"azure-cli": "2.26.1",
"azure-cli-core": "2.26.1",
"azure-cli-telemetry": "1.0.6",
"extensions": {}
}
**Additional context**

**Comment by yonzhan** [comment]
Compute

**Comment by adhgupta** [comment]
The unrecognized argument error goes away if I add the --location and --lb-sku argument to the CLI, and I am able to deploy the VMSS. The error message isn't correct, and should be changed.

**Comment by zhoxing-ms** [comment]
> unrecognized arguments: --egde-zone microsoftlosangeles1

In fact, this problem is caused by a spelling mistake~  The `--egde-zone` should be `--edge-zone`
