### ISSUE TITLE
aks

### ISSUE THREAD

**Issue by maxvandl** [Azure/azure-cli#18883]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
the following arguments are required: --resource-group/-g, --name/-n

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials`

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit
Python 3.9.6
Installer: PIP

azure-cli 2.26.0 *

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Volatus** [comment]
@maxvandl See: https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_get_credentials
