### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by lexp-paulo** [Azure/azure-cli#18889]
## Describe the bug

**Command Name**
`az ad sp create-for-rbac`

**Errors:**
```
API version 2020-04-01-preview does not have operation group 'role_assignments'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/mgmt/authorization/_authorization_management_client.py, ln 196, in role_assignments
    raise ValueError("API version {} does not have operation group 'role_assignments'".format(api_version))
ValueError: API version 2020-04-01-preview does not have operation group 'role_assignments'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad sp create-for-rbac --sdk-auth`

## Environment Summary
```
Linux-5.11.0-7620-generic-x86_64-with-glibc2.33
Python 3.9.5
Installer: DEB

azure-cli 2.18.0 *

Extensions:
azure-devops 0.19.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
A similar error was previously reported in #16498.

Per the environment summary:

```
Python 3.9.5
Installer: DEB

azure-cli 2.18.0 *
```

this is not an Azure CLI released by Microsoft, as we don't release Azure CLI with Python 3.9.5. The bundled Python in our official package is 3.6.10.

```
$ az -v
azure-cli                         2.26.1
...
Python (Linux) 3.6.10 (default, Jul 14 2021, 08:09:30)
[GCC 9.3.0]
```

Please make sure you [install Azure CLI from official Linux repo](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt).

**Comment by jiasli** [comment]
Tracked in #19640
