### ISSUE TITLE
az --version check for updates

### ISSUE THREAD

**Issue by HenrikSommer-Energinet** [Azure/azure-cli#18891]
> ### `az --version` checks for update

**Describe the bug**
We have a deploy agent with limit internet access and we are using a yml task: AzureCLI@2
When it start it call `az --version` to to print what version is installed on the deploy agent.
But the command is also check if there are any update and since the deploy agent dont have internet access for that, it taking about 20 sec. to do the check.

**To Reproduce**
1. remove internet access
2. call `az --version`

**Expected behavior**
print what version is installed.

**Environment summary**
Type Windows

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by HenrikSommer-Energinet** [comment]
This can be closed.
base on this PR: https://github.com/microsoft/azure-pipelines-tasks/pull/19039
it can the task can be update to call `az version`
