### ISSUE TITLE
EdgeZone: If --lb-sku is not specified, "az vmss create" creates public ip in main region

### ISSUE THREAD

**Issue by viananth** [Azure/azure-cli#18905]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

During VMSS creation in edge zones, if "--lb-sku standard" is not specified, public ip for lb is created in main region instead of edge zone.

**To Reproduce**

az vmss create -n testVmss2 -g test-vmssrg --image UbuntuLTS --edge-zone microsoftlosangeles1 --location westus 

**Expected behavior**

Public IP - Basic SKU is not supported in edge zones. Edge Zones are built out using Standard SKU. VMSS creates Basic SKU by default. So, if --lb-sku is not specified by the customer, CLI should throw exception informing "Basic SKU" is not supported in edge zones. It should not create a Public IP in main region without any information.

**Environment summary**

MSI
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise>az -v
azure-cli                         2.26.1

core                              2.26.1
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\viananth\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
cmd.exe
Windows 10

**Additional context**

**Comment by yonzhan** [comment]
Compute

**Comment by viananth** [comment]
@yonzhan @jsntcy Can you please give an update on when this will be fixed?

**Comment by viananth** [comment]
Verified that this issue is fixed with the latest release.
