### ISSUE TITLE
WebApp:az webapp config set  -g Test-WestUS -n azvnet --generic-configurations  fails with "not enough values to unpack (expected 2, got 1)"

### ISSUE THREAD

**Issue by anilpras** [Azure/azure-cli#18901]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

az webapp config set -g MyResourceGroup -n MyUniqueApp --generic-configurations "{"alwaysOn": true}" 

The above command is failing with below, I could reproduce the issue for the windows and Linux app services.  

**az webapp config set  -g Test-WestUS -n azvnet --generic-configurations "{"alwaysOn": true}"**
The command failed with an unexpected error. Here is the traceback:
**not enough values to unpack (expected 2, got 1)**
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 506, in shell_safe_json_parse
    return json.loads(json_or_dict_string, strict=strict)
  File "/opt/az/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/opt/az/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1172, in update_site_configs
    json_object = get_json_object(s)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 466, in get_json_object
    return _convert_to_snake_case(shell_safe_json_parse(json_string))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 531, in shell_safe_json_parse
    raise InvalidArgumentValueError(msg, recommendation=recommendation) from json_ex
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse JSON: {alwaysOn: true}
Error detail: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1178, in update_site_configs
    config_name, value = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
To open an issue, please run: 'az feedback'

**To Reproduce**
 The issue is reproducible all the time. 
 Create the windows or Linux app services and run the command from the CLI

**Expected behavior**
It should update the configuration or should show the warning if the configuration or value is not expected.

**Environment summary**
Tried with below two CLI version
-----------------------------------------------
C:\WINDOWS\system32>az --version
azure-cli                         2.23.0 *

core                              2.23.0 *
telemetry                          1.0.6

Extensions:
application-insights              0.1.13

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\anilpras\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

-----------------------------------------------
anil@Azure:~$ az --version
azure-cli                         2.26.0 *

core                              2.26.0 *
telemetry                          1.0.6

Extensions:
ai-examples                        0.2.5
ssh                                0.1.5

Python location '/opt/az/bin/python3'
Extensions directory '/home/anil/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.6/site-packages/azure-cli-extensions'

Python (Linux) 3.6.10 (default, Jul  2 2021, 06:40:17)
[GCC 8.3.0]

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
Looking in to the issue.

**Comment by Kotasudhakarreddy** [comment]
As an alternative you can use `az webapp config set -g MyResourceGroup -n MyUniqueApp --always-on true`

**Comment by anilpras** [comment]
Got it working, CLI/BASH use the below, essentially I just used the escape sequence as discussed here - https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#using-quotation-marks-in-values
I found both the commands to be working fine, 
CLI - az webapp config set  -g privateendpoint -n app-with-pe --generic-configurations "{\"vnetRouteAllEnabled\": true}"
Bash - az webapp config set --subscription "5cf15133-052c-466b-8dbb-7b558f88590b" -g "PrivateEndPoint" -n "app-with-pe" --generic-configurations '{"vnetRouteAllEnabled": "true"}'

Troubleshooting tip – if you use the --debug it produces a useful log.

**Comment by anilpras** [comment]
Got it working, CLI/BASH use the below, essentially I just used the escape sequence as discussed here - https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#using-quotation-marks-in-values
I found both the commands to be working fine,
CLI - az webapp config set -g privateendpoint -n app-with-pe --generic-configurations "{"vnetRouteAllEnabled": true}"
Bash - az webapp config set --subscription "5cf15133-052c-466b-8dbb-7b558f88590b" -g "PrivateEndPoint" -n "app-with-pe" --generic-configurations '{"vnetRouteAllEnabled": "true"}'

Troubleshooting tip – if you use the --debug it produces a useful log.
