### ISSUE TITLE
az acr build error

### ISSUE THREAD

**Issue by arshiyaabdullatheef** [Azure/azure-cli#18926]
## Describe the bug

**Command Name**
`az acr build`

**Errors:**
```
argument --registry/-r: expected one argument

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr build --image {} --registry --file {} {}`

## Environment Summary
```
Linux-5.4.0-1051-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.26.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by northtyphoon** [comment]
It's by design. The command requires passing registry name to -r/--registry parameter.
