### ISSUE TITLE
az acr build error in azure devops pipeline in version 20210711.1

### ISSUE THREAD

**Issue by AiHaibara** [Azure/azure-cli#18938]
## Describe the bug
error suddenly in azure devops pipeline after 2021/7/15.
**Command Name**
``
az acr
build
--verbose
--registry
‘xxxxx'
--resource-group
'xxxxx'
--platform
linux/amd64
--file
D:\a\1\s\modules\src\FileDownload\bin\publish\Release\linux-x64\Dockerfile.linux-amd64
--image
'xxxxx'
'D:\a\1\s\xxxxxx'
 for ...

**Errors:**
WARNING: Packing source code into tar to upload...
WARNING: Uploading archived source code from 'C:\Users\VSSADM~1\AppData\Local\Temp\build_archive_950ccb9389684b2e97290a77ba231c47.tar.gz'...
INFO: Client-Request-ID=0975e18b-e936-11eb-811b-000d3ab3c179 Outgoing request: Method=PUT, Path=/d85a9f98874a4c50ae0763370e889c97-2f40ahilti/source/202107200000/4432206c-d7f2-4631-ae7a-e22a0348a189.tar.gz, Query={'timeout': None, 'sv': '2018-03-28', 'sr': 'b', 'sig': 'REDACTED', 'se': '2021-07-20T09:39:45Z', 'sp': 'cw'}, Headers={'x-ms-blob-type': 'BlockBlob', 'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'Content-Length': '34099655', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.8.9; Windows 10)', 'x-ms-client-request-id': '0975e18b-e936-11eb-811b-000d3ab3c179', 'x-ms-date': 'Tue, 20 Jul 2021 08:39:46 GMT'}.
INFO: Client-Request-ID=0975e18b-e936-11eb-811b-000d3ab3c179 Receiving Response: Server-Timestamp=Tue, 20 Jul 2021 08:39:48 GMT, Server-Request-ID=9e8b6fbe-501e-0057-3142-7d1d6e000000, HTTP Status Code=201, Message=Created, Headers={'content-length': '0', 'content-md5': 'PELsvInBgI4GiAG5YPRUYA==', 'last-modified': 'Tue, 20 Jul 2021 08:39:49 GMT', 'etag': '"0x8D94B59EFB8778C"', 'server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '9e8b6fbe-501e-0057-3142-7d1d6e000000', 'x-ms-version': '2018-11-09', 'x-ms-request-server-encrypted': 'true', 'date': 'Tue, 20 Jul 2021 08:39:48 GMT'}.
WARNING: Sending context (32.520 MiB) to registry: alaniotacr...
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 106, in acr_build
TypeError: 'NoneType' object is not callable
To open an issue, please run: 'az feedback'
INFO: Command ran in 25.739 seconds (init: 0.199, invoke: 25.539)
WARNING: az acr

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Expected Behavior
build success.
## Environment Summary

Installer: MSI

azure-cli 1.164.0

```
success env:
Starting: Initialize job
Agent name: 'Azure Pipelines 3'
Agent machine name: 'WIN-J4L756MPM8H'
Current agent version: '2.188.4'
Operating System
Microsoft Windows Server 2019
10.0.17763
Datacenter
Virtual Environment
Environment: windows-2019
Version: 20210628.1
Included Software: https://github.com/actions/virtual-environments/blob/win19/20210628.1/images/win/Windows2019-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20210628.1
Current image version: '20210628.1'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: PowerShell (2.186.0)
Downloading task: UseDotNet (2.184.0)
Downloading task: AzureCLI (1.164.0)
Checking job knob settings.
   Knob: AgentToolsDirectory = C:\hostedtoolcache\windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = C:\agents\perflog Source: ${VSTS_AGENT_PERFLOG} 
   Knob: TaskRestrictionsEnforcementMode = Enabled Source: $(agent.taskRestrictionsEnforcementMode) 
   Knob: EnableTaskRestrictionsTelemetry = true Source: $(agent.enableTaskRestrictionsTelemetry) 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job
```
error env:
```
Starting: Initialize job
Agent name: 'Azure Pipelines 3'
Agent machine name: 'fv-az239-394'
Current agent version: '2.188.4'
Operating System
Microsoft Windows Server 2019
10.0.17763
Datacenter
Virtual Environment
Environment: windows-2019
Version: 20210711.1
Included Software: https://github.com/actions/virtual-environments/blob/win19/20210711.1/images/win/Windows2019-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20210711.1
Current image version: '20210711.1'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: PowerShell (2.186.0)
Downloading task: UseDotNet (2.184.0)
Downloading task: AzureCLI (1.164.0)
Checking job knob settings.
   Knob: AgentToolsDirectory = C:\hostedtoolcache\windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = c:\vsts\perflog Source: ${VSTS_AGENT_PERFLOG} 
   Knob: TaskRestrictionsEnforcementMode = Enabled Source: $(agent.taskRestrictionsEnforcementMode) 
   Knob: EnableTaskRestrictionsTelemetry = true Source: $(agent.enableTaskRestrictionsTelemetry) 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

```

**Comment by yonzhan** [comment]
route to service team

**Comment by zevanreg** [comment]
I have the same issue running az acr build from Azure CloudShell

**Comment by AiHaibara** [comment]
@yonzhan  with the image version auto update to 20210719.0, the build command run successfully.

**Comment by yonzhan** [comment]
@AiHaibara share we close this issue?
