### ISSUE TITLE
Not sure why az login does not work. But i was logged in through browser but still see this error

### ISSUE THREAD

**Issue by priyanka-raghavan-maersk** [Azure/azure-cli#18936]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Darwin-20.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.68

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by priyanka-raghavan-maersk** [comment]
I have gone ahead and also done the following
brew reinstall openssl@1.1
brew link --force openssl
brew reinstall azure-cli
az login

as per this blog https://github.com/Azure/azure-cli/issues/6409. No luck

**Comment by jiasli** [comment]
`azure-cli` 2.0.68 is a very old version. Could you follow [Install Azure CLI on macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos) and install the latest version with 

```
brew update && brew install azure-cli
```

**Comment by priyanka-raghavan-maersk** [comment]
Please close this. It really helped. Thank you

**Comment by jiasli** [comment]
Glad to know the it works for you. 😀

**Comment by jiasli** [comment]
Glad to know it works for you. 😀
