### ISSUE TITLE
az account get-access-token got exception

### ISSUE THREAD

**Issue by woodymoo** [Azure/azure-cli#18945]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50057: The user account is disabled.\r\nTrace ID: b10c3263-8613-4979-ad46-63b2d4ac1501\r\nCorrelation ID: 262255b4-6d20-45e1-b3d6-a5a12a21b980\r\nTimestamp: 2021-07-21 07:56:39Z","error_codes":[50057],"timestamp":"2021-07-21 07:56:39Z","trace_id":"b10c3263-8613-4979-ad46-63b2d4ac1501","correlation_id":"262255b4-6d20-45e1-b3d6-a5a12a21b980","error_uri":"https://login.chinacloudapi.cn/error?code=50057"}
Traceback (most recent call last):
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.6
Installer: HOMEBREW

azure-cli 2.14.2

Extensions:
front-door 1.0.14

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
As the error suggested:

> AADSTS50057: The user account is disabled.

Please contact your tenant/directory administrator to re-enable the user account.
