### ISSUE TITLE
When run in Cloud-Shell, `az account get-access-token` can't retrieve token for Power Platform

### ISSUE THREAD

**Issue by tomavokal** [Azure/azure-cli#18946]
**Describe the bug**
Fetching token for Power Platform (Dataverse) environment is not possible form Azure Cloud-Shell (Bash). This seems to be by design since `crm.dynamics.com` is not valid resource registered for Cloud Shell MSI. Behavior between execution from client and Cloud shell is different (Cloud shell seems to be calling to some MSI proxy: https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_active_directory.py#L597).  This proxy does not register `crm.dynamics.com`  as valid audience. 

**To Reproduce**
Run: `az account get-access-token --resource="https://{environment}.crm.dynamics.com"` 
From: `dev machine`, this is able to get a token
From: `cloud shell`, this fails with 400

**Expected behavior**
I am able to get token for Power Platform environment from Cloud-Shell since it is Microsoft product and behavior is consistent between client and Cloud-Shell execution. 
E.I. `crm.dynamics.com` is registered as valid resource in Cloud-Shell MSI proxy.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This is a known issue of Cloud Shell. Please see https://github.com/Azure/azure-cli/issues/11386#issuecomment-588176743 for explanation and workarounds.
