### ISSUE TITLE
`az sql server create` adds `None` to output

### ISSUE THREAD

**Issue by sanderaernouts** [Azure/azure-cli#18948]
## Describe the bug
Running `az sql server create` and capturing the output in a variable (in Powershell in my case) adds `None` to the output. The command `az sql server create .... --query id --output tsv` returns `None <id>` instead of  `<id>` which breaks places in the my where the output if this command is used.

**Command Name**
`az sql server create`

**Errors:**
```
Output starts with `None `
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az sql server create --name {} --resource-group {} --admin-user {} --admin-password {} --location {} --query id --output tsv`

## Expected Behavior
Should return `<id>` instead of  `None <id>`
## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.0 *

Extensions:
aks-preview 0.5.19
azure-devops 0.18.0
subscription 0.1.4

```
## Additional Context
*None*

**Comment by yonzhan** [comment]
route to service team

**Comment by biltongza** [comment]
This is still an issue:

```
 az --version
azure-cli                         2.32.0 *

core                              2.32.0 *
telemetry                          1.0.6

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\ldam\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal
```
