### ISSUE TITLE
Capacity Reservation, VM and VM ScaleSets (high priority) 

### ISSUE THREAD

**Issue by hari-bodicherla** [Azure/azure-cli#18943]
**Is your feature request related to a problem? Please describe.**
   This feature request is for introducing a new resource called Capacity Reservation. Today Azure provides capacity for the virtual machines in most scenarios and provides availability SLA for virtual machines once deployed in that capacity. But we currently lack features to provide SLA for the capacity availability prior to VM/VMSS deployment. In recent days, we saw the need for this capacity Reservation more due to the increasing capacity needs due to Covid-19 like scenarios and it will be useful if we can provide a feature for Customers to be able to reserve the capacities for critical workloads that couldn’t handle the delayed downtime.  
Full Problem statement and design information is here: 
[https://microsoft.sharepoint.com/:w:/t/ComputeVM/EaUwaQbU3NJGq4U38tiJjHUBqwAhWov9SUSa8rR6RSGQkw?e=HzTeQ3 ](Design documentation)

**Describe the solution you'd like**
This resource will be used by customers to create and reserve the on-demand capacity slots for future deployments to avoid allocation failures due to out-of-capacity issues for any critical deployments. 

**Describe alternatives you've considered**
Customers can always try to reserve clusters ( which is expensive and can be overwhelming for small-scale customers). Also, they can use the spot VMS which is low priority VMs and can be evicted at any time due to other deployments.

**Additional context**

Complete Swagger changes for this feature request are below

Capacity Reservation, Single VM: 
1. [https://github.com/Azure/azure-rest-api-specs/pull/15058](Main)
2. [https://github.com/Azure/azure-rest-api-specs/pull/15158](Patch changes)

VMSS : 
[https://github.com/Azure/azure-rest-api-specs/pull/15070](main)

**Resource Provider**
Compute Resource Provider

**Minimum API Version Required**

2021-04-01

**Target Date**

We would like to for Public Preview in Early August and planning for the GA in September.
 we are on a tight deadline.

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@hari-bodicherla Hi, may I ask why https://github.com/Azure/azure-rest-api-specs/pull/15158 has been closed? Is it because it was replaced by https://github.com/Azure/azure-rest-api-specs/pull/15058?
By the way, since this requirement seems to be a big workload, we can't catch up with the sprint to complete it. Will the next sprint release this requirement in **09-03** meet your expectations?

**Comment by hari-bodicherla** [comment]
> @hari-bodicherla Hi, may I ask why [Azure/azure-rest-api-specs#15158](https://github.com/Azure/azure-rest-api-specs/pull/15158) has been closed? Is it because it was replaced by [Azure/azure-rest-api-specs#15058](https://github.com/Azure/azure-rest-api-specs/pull/15058)?
> By the way, since this requirement seems to be a big workload, we can't catch up with the sprint to complete it. Will the next sprint release this requirement in **09-03** meet your expectations?

Hi @zhoxing-ms , The 15058 is main PR and then we had to make a minor change which is accomplished in another PR from Theodore, so the 15158 is closed. 
Regarding the release date on 09-03, if we can make it sooner than that that would be great since we are planning GA by end of august. But if this is next sooner date, then we can try to get the exception on CLI. thanks

**Comment by zhoxing-ms** [comment]
@hari-bodicherla Sorry, our latest next official release time is **09-07** (I made a mistake before). If some customers need it urgently, maybe we can provide a private package to let users try it first

**Comment by zhoxing-ms** [comment]
@hari-bodicherla Since the Swagger changes too much in the PR https://github.com/Azure/azure-rest-api-specs/pull/15058 , could you provide the specific commands and parameter related designs that need to be supported?

**Comment by hari-bodicherla** [comment]
@zhoxing-ms  we need to support the PUT, Patch, Delete, Get and List operations for the Capacity Reservation while we need to support the Put and Get operations for VM , VMSS and VMSS VM resources to expose this new CR profile. 
Please refer the below powershell PRs covering the commands 
1. https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/967 - Cmdlets for CR, single vm
2. https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/987 -  added missing cmdlets design in the above PR
3. https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/957 - VMSS Changes.
Please let me know if you need more information.

**Comment by zhoxing-ms** [comment]
@hari-bodicherla Hi, I see that `PowerShell` commands also support capacity reservation in the following commands:
> New-AzVMConfig  [-CapacityReservationGroupId <String>]
 New-AzVmssConfig [-CapacityReservationGroupId <String>]

Because there is no corresponding commands in CLI, so we don't need to implement this case, right?

**Comment by zhoxing-ms** [comment]
@hari-bodicherla By the way, the command design in PowerShell does not include VM signature, so how should the CLI commands be designed?
`az vm capacity reservation create/udpate/list/show` or `az capacity reservation create/udpate/list/show`, which command design is better?
Or do you have more suggestions on command design?

**Comment by hari-bodicherla** [comment]
> @hari-bodicherla By the way, the command design in PowerShell does not include VM signature, so how should the CLI commands be designed?
> `az vm capacity reservation create/udpate/list/show` or `az capacity reservation create/udpate/list/show`, which command design is better?
> Or do you have more suggestions on command design?

@zhoxing-ms the capacity reservation is an independent resource and can be created/deleted/updated/list/show with out any relation to VM. Capacity reservation also can be associated with vmss. So if you are asking for the capacity reservation crud operation cli cmd, I think the `az capacity reservation create/udpate/list/show`, is better one.

Thanks

**Comment by hari-bodicherla** [comment]
> @hari-bodicherla Hi, I see that `PowerShell` commands also support capacity reservation in the following commands:
> 
> > New-AzVMConfig  [-CapacityReservationGroupId ]
> > New-AzVmssConfig [-CapacityReservationGroupId ]
> 
> Because there is no corresponding commands in CLI, so we don't need to implement this case, right?

@zhoxing-ms  yes we don't need to implement this in cli if there are no corresponding cmdlets for VM and vmss config . this is used normally to reuse the VM/vmss config by creating it once and then reusing  in multiple update and create cmdlets for powershell.

**Comment by zhoxing-ms** [comment]
https://github.com/hari-bodicherla/azure-rest-api-specs/blob/606074d0c2248882599854f9e8bed38fa9fc00e1/specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json#L9163-L9168
@hari-bodicherla Hi, I would like to confirm that it means that the parameters `zones` can only pass in one value? If so, why is it defined as an array type?

**Comment by zhoxing-ms** [comment]
I see the command `New-AzCapacityReservation` of `PowerShell` has designed these two parameters:
1. `[-CapacityToReserve] <Int32>`: I haven't seen it's definition in Swagger or SDK. What is it's function? Do we need it in CLI?
2. `[-WhatIf]`: our team is not responsible for the support of `what-if` related features at present. Does this parameter also need to be supported at present?

**Comment by zhoxing-ms** [comment]
https://github.com/hari-bodicherla/azure-rest-api-specs/blob/606074d0c2248882599854f9e8bed38fa9fc00e1/specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json#L4323-L4327
I'd like to ask whether the parameter `$expand` can be passed into `virtualMachineScaleSetVMs/$ref` and `virtualMachines/$ref` at the same time? Or are they mutually exclusive?

**Comment by hari-bodicherla** [comment]
> https://github.com/hari-bodicherla/azure-rest-api-specs/blob/606074d0c2248882599854f9e8bed38fa9fc00e1/specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json#L9163-L9168
> @hari-bodicherla Hi, I would like to confirm that it means that the parameters `zones` can only pass in one value? If so, why is it defined as an array type?

we need to mention it as array type since this is the restriction from ARM side that zones should be always array even we allow single zone.

**Comment by hari-bodicherla** [comment]
> https://github.com/hari-bodicherla/azure-rest-api-specs/blob/606074d0c2248882599854f9e8bed38fa9fc00e1/specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/compute.json#L4323-L4327
> I'd like to ask whether the parameter `$expand` can be passed into `virtualMachineScaleSetVMs/$ref` and `virtualMachines/$ref` at the same time? Or are they mutually exclusive?

They are not mutually exclusive, customer can add both to get the VM references as well as vmss VM references in the response.

**Comment by hari-bodicherla** [comment]
> @hari-bodicherla I see the command `New-AzCapacityReservation` of `PowerShell` has designed this parameter:
> `[-WhatIf]`: our team is not responsible for the support of `what-if` related features at present. Does this parameter also need to be supported at present?

This is present default in almost of all the existing cmdlets for resources, if the cli is not supporting this param, then that is fine since it is not supported for existing ones, so customer should not be expecting this param

**Comment by zhoxing-ms** [comment]
@hari-bodicherla Hi, at present, the URL of CLI request for REST is `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/capacityReservationGroups/{capacityReservationGroupName}`
Why does the current service return this error?
> {"error":{"code":"InvalidResourceType","message":"The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2021-04-01'."}}

**'x-ms-correlation-request-id': '9c432ac6-78d0-4c7f-9762-1bc476fa57a2'**

**Comment by hari-bodicherla** [comment]
> @hari-bodicherla Hi, at present, the URL of CLI request for REST is `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/capacityReservationGroups/{capacityReservationGroupName}`
> Why does the current service return this error?
> 
> > {"error":{"code":"InvalidResourceType","message":"The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2021-04-01'."}}
> 
> **'x-ms-correlation-request-id': '9c432ac6-78d0-4c7f-9762-1bc476fa57a2'**
Sorry for the delay, I was oof for some time.
Which Region are you trying to reach when you are trying to trigger the operation on Capacity Reservation @zhoxing-ms . Few validations regions need additional AFEC flags that needs to be whitelisted for subscription to get CR resource support in that region. I just checked the operation details for above correlation id and it was found that operation is triggered at South east asia region. we currently support Capacity reservation in Canary ( central us euap, east us2 euap), west central us and south central us regions only. also subscription need to register to the AFEC flag "Microsoft.Compute/CapacityReservationPreview" to be able to access this CR resource.

**Comment by zhoxing-ms** [comment]
@hari-bodicherla  So at present, only some regions on the white list support capacity reservation, right? Will this restriction affect users in other regions after the release of CLI? Can service provide more friendly and specific error information?

> also subscription need to register to the AFEC flag "Microsoft.Compute/CapacityReservationPreview" to be able to access this CR resource.
What do we need to do for this?

**Comment by hari-bodicherla** [comment]
@zhoxing-ms , Currently we have PR in review to remove the afec flag dependency for prod regions and this will enable customers in all prod users to be able to access the Capacity reservation with out whitelisting to afec. Also we provide specific detailed error information mentioning that subscription is not whitelisted to specific AFEC flag to access the CR resource.

**Comment by zhoxing-ms** [comment]
> we currently support Capacity reservation in Canary ( central us euap, east us2 euap), west central us and south central us regions only.

Hi, @hari-bodicherla I still have this problem after using the above regions.

Such as: **'x-ms-correlation-request-id': 'e2a31220-c6ca-4250-9e46-a7c0af912833'**

What else do I need to do?

**Comment by hari-bodicherla** [comment]
> e2a31220-c6ca-4250-9e46-a7c0af912833

Yes @zhoxing-ms  Currently the AFEC removal changes are still in PR so you need to whitelist the sub t AFEC to access the CR resource. Please share your subscription, I can help in whitelisting the sub with AFEC

**Comment by zhoxing-ms** [comment]
@hari-bodicherla  I'll tell you offline~

**Comment by zhoxing-ms** [comment]
@hari-bodicherla This problem has been solved, but there are new problems when creating capacity reservation. please help to have a look~

Request URL:
```
https://management.azure.com/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Compute/capacityReservationGroups/{capacity_reservation_group}/capacityReservations/{capacity_reservation}?api-version=2021-04-01
```

Requst body
```json
{
    "location": "centraluseuap", 
    "tags": {
        "key": "val"
    }, 
    "sku": {
        "name": "Standard_A0", 
        "tier": "Basic", 
        "capacity": 5
    }, 
    "zones": [
        "1"
    ]
}
```
Response body
```json
{
  "error": {
    "code": "NotSupported",
    "message": "Capacity Reservation is not supported for VM size Standard_A0."
  }
}
```

**'x-ms-correlation-request-id': '26a15da4-d3ed-4007-b764-b7baf76aedcb'**

**Comment by hari-bodicherla** [comment]
> @hari-bodicherla This problem has been solved, but there are new problems when creating capacity reservation. please help to have a look~
> 
> Request URL:
> 
> ```
> https://management.azure.com/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Compute/capacityReservationGroups/{capacity_reservation_group}/capacityReservations/{capacity_reservation}?api-version=2021-04-01
> ```
> 
> Requst body
> 
> ```json
> {
>     "location": "centraluseuap", 
>     "tags": {
>         "key": "val"
>     }, 
>     "sku": {
>         "name": "Standard_A0", 
>         "tier": "Basic", 
>         "capacity": 5
>     }, 
>     "zones": [
>         "1"
>     ]
> }
> ```
> 
> Response body
> 
> ```json
> {
>   "error": {
>     "code": "NotSupported",
>     "message": "Capacity Reservation is not supported for VM size Standard_A0."
>   }
> }
> ```
> 
> **'x-ms-correlation-request-id': '26a15da4-d3ed-4007-b764-b7baf76aedcb'**

@zhoxing-ms  Currently VMAL VM sizes are only supported for using Capacity Reservation. You can know that by looking at the Get sku response for the VM size and finding the Capacity Reservation Suppported property set to true. you can use for eg AV2  sizes which support the CR

**Comment by zhoxing-ms** [comment]
@hari-bodicherla There is a problem when deleting capacity reservations. please help to take a look~


Reuqest URL: 
Delete reuqest: https://management.azure.com/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Compute/capacityReservationGroups/{capacity_reservation_groups}/capacityReservations/{capacity_reservations}?api-version=2021-04-01
Polling request: https://management.azure.com/subscriptions/{subscription}providers/Microsoft.Compute/locations/CentralUSEUAP/operations/4e836e90-0d00-460f-9d1b-7cc5b04e37dc?p=2745cc42-2cf3-41b7-830c-129b79fbec46&api-version=2021-04-01

Response body:
```json
{
    "startTime": "2021-08-30T15:00:03.6667668+00:00", 
    "endTime": "2021-08-30T15:00:03.7292753+00:00", 
    "status": "Failed", 
    "error": {
        "code": "InternalExecutionError", 
        "message": "An internal execution error occurred. Please retry later."
    }
}
```

**Comment by hari-bodicherla** [comment]
> @hari-bodicherla In fact, it will affect our tests, because the check of our tests is case sensitive to the resource ID and resource group name. Moreover, some users may use the returned resource group name to do case sensitive operations, such as using the the parameter `--query` to accurately search the contents from returned results.
> So I think it's better to return the original name than to capitalize it all.

I will triage this scenario with in team and let u know if we need to create a repair item and will share with you. Currently this is how we are returning for other resources like Dedicated host. for some API responses for VM too.

**Comment by hari-bodicherla** [comment]
> @hari-bodicherla There is a problem when deleting capacity reservations. please help to take a look~
> 
> Reuqest URL:
> Delete reuqest: [https://management.azure.com/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.Compute/capacityReservationGroups/{capacity_reservation_groups}/capacityReservations/{capacity_reservations}?api-version=2021-04-01](https://management.azure.com/subscriptions/%7Bsubscription%7D/resourceGroups/%7Bresource_group%7D/providers/Microsoft.Compute/capacityReservationGroups/%7Bcapacity_reservation_groups%7D/capacityReservations/%7Bcapacity_reservations%7D?api-version=2021-04-01)
> Polling request: [https://management.azure.com/subscriptions/{subscription}providers/Microsoft.Compute/locations/CentralUSEUAP/operations/4e836e90-0d00-460f-9d1b-7cc5b04e37dc?p=2745cc42-2cf3-41b7-830c-129b79fbec46&api-version=2021-04-01](https://management.azure.com/subscriptions/%7Bsubscription%7Dproviders/Microsoft.Compute/locations/CentralUSEUAP/operations/4e836e90-0d00-460f-9d1b-7cc5b04e37dc?p=2745cc42-2cf3-41b7-830c-129b79fbec46&api-version=2021-04-01)
> 
> Response body:
> 
> ```json
> {
>     "startTime": "2021-08-30T15:00:03.6667668+00:00", 
>     "endTime": "2021-08-30T15:00:03.7292753+00:00", 
>     "status": "Failed", 
>     "error": {
>         "code": "InternalExecutionError", 
>         "message": "An internal execution error occurred. Please retry later."
>     }
> }
> ```
@zhoxing-ms This issue is being fixed in the PR: https://dev.azure.com/msazure/One/_git/Compute-CPlat-Core/pullrequest/5007620 . Thanks for notifying the bug.

**Comment by zhoxing-ms** [comment]
@hari-bodicherla May I ask when can this problem be solved?  If it cannot be solved before we release the new version of CLI, does the CLI need to expose the features that VM and VMSs can associate with capactiy reservation group?
At present, this problem will also lead to the problem of circular dependency deletion of resources, which makes users unable to delete all resources under this resource group. I will transfer a related ICM to you. Please help to have a look~
