### ISSUE TITLE
WebApp:az webapp config show is missing acr managed identity creds

### ISSUE THREAD

**Issue by SorenMaagaard** [Azure/azure-cli#18956]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Since version 2.23.0 the command `az webapp config show ` do not return the values `acrUserManagedIdentityId` and  `acrUseManagedIdentityCreds`. It is also not possible to set those anymore using `az webapp config set --generic-configurations`.

**To Reproduce**

use azure cli version >= 2.23.0
run 
`az webapp config show -g <resource group> -n <web-app-name>`

**Expected behavior**

`az webapp config show -g <resource group> -n <web-app-name>`
should return 
```json
{
  "acrUseManagedIdentityCreds": true,
  "acrUserManagedIdentityId": "<identity>",
...
}
```

**Environment summary**

Tested on pwsh in windows:
version 2.20.0 --> working
version 2.26.1 --> NOT working
and on linux using azure-cli docker image running in wsl:
version 2.20.0 --> working
version 2.22.1 --> working
version 2.23.0 --> NOT working
version 2.26.1 --> NOT working
**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
Mentioned properties were removed from the current Python SDK. please find the Breaking changes section [here](https://pypi.org/project/azure-mgmt-web/2.0.0/) . Properties were added back to latest SDK (3.0.0) . This issue will be fixed in the next CLI update with latest SDK. As a work around please rollback your CLI to the working version. Sorry for inconvenience.

**Comment by Kotasudhakarreddy** [comment]
@panchagnula can you please check if these properties are added back in the latest SDK.

**Comment by seligj95** [comment]
closing as these properties are now visible. please upgrade to the latest cli version and reopen if any issues.
