### ISSUE TITLE
Support for CustomIpPrefix (BYOIP)

### ISSUE THREAD

**Issue by brianlehr** [Azure/azure-cli#18953]
**Resource Provider**
NRP

**Description of Feature or Work Requested**
Need to have CLI support a new feature for customers to bring their own IP ranges to Azure, coming to Public Preview by 9/30.  This is all done using the CustomIpPrefix object - a new type of NRP resource.  Full PowerShell support is[ in progress](https://github.com/Azure/azure-powershell/pulls?q=gitlwh); note there is already [partial support ](https://docs.microsoft.com/en-us/powershell/module/az.network/new-azcustomipprefix?view=azps-6.2.1).
There are also some modifications to the PublicIpPrefix and PublicIp classes as well.

So for CLI, we will need a new family of commands
**az network custom-ip prefix**
and updates to
**az network public-ip prefix** and **az network public ip**

**Minimum API Version Required**
2021-02-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/customIpPrefix.json
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/publicIpPrefix.json
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/publicIpAddress.json

**Target Date**
The Public Preview date is 9/30.  Updated PowerShell will roll out by 9/7, so we'd like this to be around the same time (early September).

Please contact blehr@microsoft.com for more details.

**Comment by yonzhan** [comment]
network

**Comment by brianlehr** [comment]
@yonzhan Could you help us understand the general timeframe when this can be executed?  The release date for the feature is 9/30, apologies for the late notification.  The good news is that the required pieces are already in the latest API.

**Comment by yonzhan** [comment]
This feature is planned in next sprint https://github.com/Azure/azure-cli/milestone/109

**Comment by brianlehr** [comment]
This issue was closed prematurely.  @kairu-ms please re-open or create a new issue for tracking
