### ISSUE TITLE
[App Service] No way to specify that an appsetting shouldn't participate in a swap

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1895]
The `az appservice web config appsettings update` command doesn't seem to provide a way to indicate that a specific setting is a "Slot setting", and therefore, shouldn't be copied between slots as part of a swap. Am I missing it?

The portal allows you to specify this (see below), and it would be ideal if this could also be set via the CLI.

![image](https://cloud.githubusercontent.com/assets/116461/22356846/1dfaa55a-e3e9-11e6-8e48-66fd29d74de5.png)

**Comment by yugangw-msft** [comment]
Please use `--slot-settings`. Sort of painful to get all work, as appservice maintains the slot setting names in a separate endpoint.
