### ISSUE TITLE
'NoneType' object is not callable when building container with az acr build

### ISSUE THREAD

**Issue by Piotr1215** [Azure/azure-cli#18963]
## Describe the bug

**Command Name**
`az acr build`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/build.py", line 109, in acr_build
    variant=platform_variant
TypeError: 'NoneType' object is not callable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr build --image {} --registry {} --resource-group {} --file {} {}`

## Environment Summary
```
Linux-5.4.0-1055-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.26.0 *

Extensions:
interactive 0.4.5
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by northtyphoon** [comment]
Thanks for reporting it and sorry for the inconvenience.
2.26.1 has been released to address the issue.
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli

**Comment by Piotr1215** [comment]
Thank you @northtyphoon , I will try and see if it's fixed once new az cli version will be upgraded on the cloud shell. Looks like I cannot upgrade manually:

![image](https://user-images.githubusercontent.com/8086638/127068981-72587ffa-2bc9-4eeb-9b41-8c8f9a4f366a.png)

**Comment by zhoxing-ms** [comment]
@Piotr1215 Hi, the CLI latest version will be updated at **08-03** on Cloud Shell, can this date meet your expectations?

**Comment by Piotr1215** [comment]
Hi @zhoxing-ms , absolutely, thank you for a very quick patch. I will close the issue now and if the problem happens after the patch, I will open a new one.

**Comment by mabrahamdevops** [comment]
Please update the AZURE CLOUD SHELL before 8-03.  This has stopped the entire lab here for the past 2 weeks.

**Comment by zhoxing-ms** [comment]
@mabrahamdevops Since Cloud Shell is deployed according to a certain period, and the next release time happens to be **08-03**, we will pull the latest version **2.27.0** (including the fixes in version **2.26.1**), so we generally do not continuously release new versions at such a short interval

For this, I provide a workaround for your reference. Maybe you can use the reference this document [doc link](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script) to install the latest CLI in Cloud Shell.

**Comment by jesusnunezpro** [comment]
The only workaround I found to make this work for me, was though a virtual environment in python
```bash
python -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install azure-cli
```
The Instructions [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script) just reinstalled 2.26.0

**Comment by Piotr1215** [comment]
I can confirm that the bug was resolved with the latest version

![image](https://user-images.githubusercontent.com/8086638/129227359-2943c198-3972-4905-8cbe-6f96e0d5f35d.png)

The image can be built successfully.
