### ISSUE TITLE
Command to list SKUs Codes

### ISSUE THREAD

**Issue by bjosafa** [Azure/azure-cli#18964]
I would like to get a list of the current SKUs codes, not only the name, for my subscription. Is that already possible or it should be added as a feature? E.g.: I am using the Get-AzComputeResourceSku command but I need the SKUs codes.

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@bjosafa Please use `az vm list-skus` to have a try, add parameter `-h` then you can see the usage of this command

**Comment by bjosafa** [comment]
I already did it, but it did show the sku id as it is shown in the calculator. E.g.:

Virtual Machines (West US - VM 1 D2 v3) = AAA-44930 (Sku code) <- that information that I want to get via cli

**Comment by zhoxing-ms** [comment]
In fact, CLI only directly output the results returned by REST service [list-skus](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-images/list-skus) , while REST does not return the data of SKU codes. Therefore, it needs the support of REST from the server team.

As for PowerShell related requirements, please submit them on https://github.com/Azure/azure-powershell

**Comment by amjads1** [comment]
@jaylabell Could you please look into this issue?

**Comment by jaylabell** [comment]
Redirecting updates to https://github.com/Azure/azure-powershell/issues/15526

**Comment by jaylabell** [comment]
@bjosafa was the answer provided by @zhoxing-ms sufficient for you: 

> In fact, CLI only directly output the results returned by REST service [list-skus](https://docs.microsoft.com/en-us/rest/api/compute/resource-skus/list) , while REST does not return the data of SKU codes. Therefore, it needs the support of REST from the server team.

**Comment by bjosafa** [comment]
@jaylabell, as I understood, the SKU codes were supposed to be provided by the Rest service, but nowadays it is not providing this information. So I can assume this will be added or at least taken into account.

**Comment by jaylabell** [comment]
Looking into this issue

**Comment by jaylabell** [comment]
@bjosafa Can you please describe what you are referencing when you say SKU Codes? What do you intend on using the list for? 

For now this item is not able to be implemented because it is not available through the REST and in order to implement in PS we would need it to be implemented through the REST. The Swagger team is interested in your answer to the question above. 
Please re-open if you can provide more details.

Thank you
