### ISSUE TITLE
[ACR] The --admin-enabled boolean parameter requires a value when creating a registry

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1897]
If I try running `az acr create --admin-enabled`, it complains about the `--admin-enabled` parameter needing a value. For boolean flags, which default to `false`, it would be nice if simply specifying them, without a value, was enough to indicate a `true` value. 

Numerous other commands in the CLI provide this behavior (e.g. the `--is-linux` parameter of the `az appservice plan create` command), and so, consistency would be helpful for ease-of-use. Maybe this ACR behavior is the preferred way, and we should just correct other commands to be congruent. I'm cool either way, though I'd vote to not require explicitly adding `true`.

**Comment by djyou** [comment]
We used to have a flag for enabling admin when creating a registry but changed to the current pattern here https://github.com/Azure/azure-cli/pull/1276 following recommendations. The major concern was the consistency with `acr update` command. /cc @SajayAntony

**Comment by shhsu** [comment]
Two concerns:

The --admin-enabled argument would push the parameter into ACR and persist the flag of the service to allow/disallow admin operations. Would it be desirable to allow user to omit the parameters? I would think this would confuse the user and lead them to think --admin-enabled is just a simple modifier of the operation. Moreover, “--admin-enabled” actually has 3 valid values, “true/false” meaning change to “ture/false”; not having the flag means keep the current value. Making this flag a switch and allow user to provide no input to my view would confuse the user and have them think it’s a boolean switch.

After reading the code, it seems like if we want to go ahead and implement this, it would be a pretty big change. The framework automatically use (extract_args_from_signature)[https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/commands/_introspection.py#L62] to scan the method signature and determine what type of parameter is needed from command line. (required/optional, default value, etc) It looks like there's no simple way of doing what is asked for here. @tjprescott, please correct me if I am wrong.

**Comment by shhsu** [comment]
Talked to @tjprescott. this change would be consistent with other places on the cli. We should proceed with the changes then.

**Comment by SajayAntony** [comment]
Will this be a breaking change?
We don't want customer script to break.

**Comment by djyou** [comment]
I agreed that `--is-linux` in `az appservice plan create` is a good example in using Boolean values. They however don't have the confusion we had in `acr update` command.

If we revert to what we had, for `acr create`, we use a flag to enable admin (default is admin disabled), but for `acr update`, we would still need a true/false value.

It is confusing either way. Using the same `--admin-enabled` confuses the user on whether an argument is needed (no in `acr create` but yes in `acr update`). Using a different parameter for `acr create` (e.g., `--enable-admin`) confuses the user on whether it means the same thing as `--admin-enabled` in `acr update`.

We used to have another pattern where we had two flag values (i.e., `--enable-admin` and `--disable-admin`) for `acr update`. It may be less confusing than the above, but was not a recommended solution either.

**Comment by tjprescott** [comment]
I definitely don't recommend two flags.  However, you can have a three state solution that works. @shhsu and I discussed the following:
**create**
```
--admin-enabled  (True is implied)
--admin-enabled True (explicit)
--admin-enabled False (explicit)
(omitting is implicitly false)
```

**update**
```
--admin-enabled True (explicit)
--admin-enabled False (explicit)
(omitting means don't change)
```

In this way, you have consistency between create and update for those who value that, you have the ease of simply specifying a flag on create for those who value that, and you don't have a breaking change.

**Comment by shhsu** [comment]
I agree. This is not a breaking change. However, at this point I am not sure if there's a good way of implementing this change though. In the case of "--admin-enabled" no value and omitted flag case, argparse would fill the field with default/None. @tjprescott do you know of a way for argparse to differentiate the two?

**Comment by tjprescott** [comment]
nargs='?', action='store_true'

That should store true as the value if the flag is specified. It may (or may not) cause issues if an actual value is used.  Let me know if that works.

**Comment by shhsu** [comment]
store_true action does not allow nargs as it doesn't allow input. Same for store_const

**Comment by shhsu** [comment]
This seems promising

action='store', nargs='?', const=True, default=None
