### ISSUE TITLE
Add --edge-zone to the "az vm image" commands

### ISSUE THREAD

**Issue by DwayneNeed** [Azure/azure-cli#18971]
**Resource Provider**
Compute

**Description of Feature or Work Requested**
Add optional parameter --edge-zone to the following Az.Compute cmdlets:

az vm image list
az vm image list-offers 
az vm image list-skus
az vm image list-publishers
az vm image show
 
Note: this was inadvertently not done as part of the previous issue:
https://github.com/Azure/azure-cli/issues/15988

**MS Docs:**
https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-images-edge-zone

**Minimum API Version Required**
2020-12-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/compute-2020-12/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json

**Powershell PR**
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/776

**Comment by yonzhan** [comment]
Compute
