### ISSUE TITLE
Tests still import mock

### ISSUE THREAD

**Issue by major** [Azure/azure-cli#18976]
**Describe the bug**
The `azure-cli-telemetry` tests still contain `import mock` and mock is deprecated in recent python versions.

**To Reproduce**
Run tests for `azure-cli-telemetry` on Python 3.10.

**Expected behavior**
I expect tests to pass.

**Environment summary**
Installed `azure-cli-telemetry` 1.0.6 via `pip`.

**Additional context**
I'm preparing a PR to fix this.

**Comment by yonzhan** [comment]
telemetry

**Comment by jiasli** [comment]
Per https://pypi.org/project/mock/:

> mock is now part of the Python standard library, available as `unittest.mock` in Python 3.3 onwards.

As Azure CLI requires Python >= 3.6, we can drop `mock`. 

Actually, this is not the only place where `mock` is used. It should be dropped everywhere!

**Comment by major** [comment]
@jiasli That would be really helpful for me as I try to package Azure CLI (and the SDK) in Fedora!

**Comment by jiasli** [comment]
By the way, did you encounter any error in Python 3.10?

**Comment by major** [comment]
> By the way, did you encounter any error in Python 3.10?

Not much in the code itself, but I do notice some testing failures there (using `azdev test`).

**Comment by jiasli** [comment]
@major, I am not aware of that. Could you share some example failures caused by `mock` if convenient?

**Comment by major** [comment]
> @major, I am not aware of that. Could you share some example failures caused by `mock` if convenient?

I'll try to take a look later today.
