### ISSUE TITLE
Compute create type incorrect.

### ISSUE THREAD

**Issue by andrew-twigg** [Azure/azure-cli#18984]
Hi, I found the --type parameter on az ml compute create needed to be lower case else I got an error.

So either amlcompute or computeinstance. Using the case in the docs fails. Took a bit of hunting around to try and understand why it was failing.

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71c25404-a256-62b2-3ac8-dd699fc677ba
* Version Independent ID: 5f3dccba-b2ee-224b-9e84-80ba2bbde641
* Content: [az ml compute](https://docs.microsoft.com/en-us/cli/azure/ml/compute?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/compute.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/compute.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by andrew-twigg** [comment]
Examples, so this works...

az ml compute create -g $rg -w $ws -n devhost -t computeinstance --size Standard_DS3_v2
az ml compute create -g $rg -w $ws -n cpu-cluster -t amlcompute --min-instances 0 --max-instance 4 -s 2400

This fails...

az ml compute create -g $rg -w $ws -n devhost -t ComputeInstance --size Standard_DS3_v2
az ml compute create -g $rg -w $ws -n cpu-cluster -t AmlCompute --min-instances 0 --max-instance 4 -s 2400

**Comment by yonzhan** [comment]
route to service team

**Comment by diondrapeck** [comment]
Hi @andrew-twigg - thanks for finding this bug and bringing it to our attention! I'm working on a fix now.

**Comment by diondrapeck** [comment]
Fix has been merged. @yonzhan please close
