### ISSUE TITLE
AZ CLI Query broken for filtering Edgezone related info

### ISSUE THREAD

**Issue by vsmsft** [Azure/azure-cli#18992]
## Describe the bug
When resources like Storage account are created at EdgeZones and we use --query to filter the output. 

It seems the AZ CLI is broken when we use the query functionality to filter on things related to the EdgeZone. To be specific it interprets “!=” as “==” and vice versa. This is specifically happening for parameters which you specify when you want to land something to Edge Zone like Extended location, storage account SKU. 

**Command Name**
PS C:\Users\vivekshah\OneDrive - Microsoft\Documents 1\SDK_Validation> az storage account show -g myResourceGroupvs -n vivtst5678
{
  "accessTier": "Hot",
  "allowBlobPublicAccess": null,
  "allowCrossTenantReplication": null,
  "allowSharedKeyAccess": null,
  "azureFilesIdentityBasedAuthentication": null,
  "blobRestoreStatus": null,
  "creationTime": "2021-07-23T20:46:16.642454+00:00",
  "customDomain": null,
  "enableHttpsTrafficOnly": true,
  "enableNfsV3": null,
  "encryption": {
    "encryptionIdentity": null,
    "keySource": "Microsoft.Storage",
    "keyVaultProperties": null,
    "requireInfrastructureEncryption": null,
    "services": {
      "blob": {
        "enabled": true,
        "keyType": "Account",
        "lastEnabledTime": "2021-07-23T20:46:16.736107+00:00"
      },
      "file": {
        "enabled": true,
        "keyType": "Account",
        "lastEnabledTime": "2021-07-23T20:46:16.736107+00:00"
      },
      "queue": null,
      "table": null
    }
  },
  "extendedLocation": {
    "name": "microsoftlosangeles1",
    "type": "EdgeZone"
  },
  "failoverInProgress": null,
  "geoReplicationStats": null,
  "id": "/subscriptions/a27d4bf1-a787-487f-8c45-0e549e4bfa31/resourceGroups/myResourceGroupvs/providers/Microsoft.Storage/storageAccounts/vivtst5678",
  "identity": null,
  "isHnsEnabled": null,
  "keyCreationTime": {
    "key1": "2021-07-23T20:46:16.736107+00:00",
    "key2": "2021-07-23T20:46:16.736107+00:00"
  },
  "keyPolicy": null,
  "kind": "StorageV2",
  "largeFileSharesState": null,
  "lastGeoFailoverTime": null,
  "location": "westus",
  "minimumTlsVersion": null,
  "name": "vivtst5678",
  "networkRuleSet": {
    "bypass": "AzureServices",
    "defaultAction": "Allow",
    "ipRules": [],
    "resourceAccessRules": null,
    "virtualNetworkRules": []
  },
  "primaryEndpoints": {
    "blob": https://vivtst5678.blob.microsoftlosangeles1.edgestorage.azure.net/,
    "dfs": null,
    "file": null,
    "internetEndpoints": null,
    "microsoftEndpoints": null,
    "queue": null,
    "table": null,
    "web": https://vivtst5678.web.microsoftlosangeles1.edgestorage.azure.net/
  },
  "primaryLocation": "westus",
  "privateEndpointConnections": [],
  "provisioningState": "Succeeded",
  "resourceGroup": "myResourceGroupvs",
  "routingPreference": null,
  "sasPolicy": null,
  "secondaryEndpoints": null,
  "secondaryLocation": null,
  "sku": {
    "name": "Premium_LRS",
    "tier": "Premium"
  },
  "statusOfPrimary": "available",
  "statusOfSecondary": null,
  "tags": {},
  "type": "Microsoft.Storage/storageAccounts"
}
PS C:\Users\vivekshah\OneDrive - Microsoft\Documents 1\SDK_Validation>
################################################################################################################################################################
az storage account list -o table -g myResourceGroupvs
AccessTier    CreationTime                      EnableHttpsTrafficOnly    Kind       Location    Name        PrimaryLocation    ProvisioningState    ResourceGroup      StatusOfPrimary
------------  --------------------------------  ------------------------  ---------  ----------  ----------  -----------------  -------------------  -----------------  -----------------
Hot           2021-07-23T20:46:16.642454+00:00  True                      StorageV2  westus      vivtst5678  westus             Succeeded            myResourceGroupvs  available
################################################################################################################################################################

PS C:\Users\vivekshah\OneDrive - Microsoft\Documents 1\SDK_Validation> az storage account list -o table --query [?extendedLocation.name!='microsoftlosangeles1']  -g myResourceGroupvs   Wrong output for !=
Location    EnableHttpsTrafficOnly    Name        Kind       ProvisioningState    PrimaryLocation    StatusOfPrimary    CreationTime                      AccessTier    ResourceGroup
----------  ------------------------  ----------  ---------  -------------------  -----------------  -----------------  --------------------------------  ------------  -----------------
westus      True                      vivtst5678  StorageV2  Succeeded            westus             available          2021-07-23T20:46:16.642454+00:00  Hot           myResourceGroupvs
################################################################################################################################################################

az storage account list -o table --query [?extendedLocation.name=='microsoftlosangeles1']  -g myResourceGroupvs  - Empty, Wrong output
################################################################################################################################################################

az storage account list -o table --query [?sku.tier=="Premium"] -g myResourceGroupvs – Empty, Wrong output
################################################################################################################################################################

az storage account list -o table --query [?sku.tier!="Premium"] -g myResourceGroupvs Wrong output for !=
Name        Location    Kind       ProvisioningState    PrimaryLocation    StatusOfPrimary    CreationTime                      AccessTier    EnableHttpsTrafficOnly    ResourceGroup
----------  ----------  ---------  -------------------  -----------------  -----------------  --------------------------------  ------------  ------------------------  -----------------
vivtst5678  westus      StorageV2  Succeeded            westus             available          2021-07-23T20:46:16.642454+00:00  Hot           True                      myResourceGroupvs
################################################################################################################################################################

az storage account list -o table --query [?Location=="westus"] -g myResourceGroupvs Works as expected, but this is not changed for EZ deployment. 
Name        Location    Kind       ProvisioningState    PrimaryLocation    StatusOfPrimary    CreationTime                      AccessTier    EnableHttpsTrafficOnly    ResourceGroup
----------  ----------  ---------  -------------------  -----------------  -----------------  --------------------------------  ------------  ------------------------  -----------------
vivtst5678  westus      StorageV2  Succeeded            westus             available          2021-07-23T20:46:16.642454+00:00  Hot           True                      myResourceGroupvs

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Create resource in EdgeZone, like storage account either via CLI or portal. Use the list command with query flag to do filter on Edgezone related parameter and it doesnt list output as expected. 

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1

Extensions:
interactive 0.4.5
next 0.1.2

```

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Please quota query with `""`
![image](https://user-images.githubusercontent.com/10227683/127122046-b62ea33c-7315-4127-a080-5770d3cecd31.png)

**Comment by vsmsft** [comment]
Thanks, this helped. The root cause was query works differently across bash, cmd prompt and PS without quotes around; causing this confusion. With quotes it worked consistently across all.
