### ISSUE TITLE
Parameter completion should juxtapose long and short form arguments

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#190]
If you type `az vm list -[tab]` you see:
`--debug            --output           --resource-group   -g                 -o 
--help             --query            --verbose          -h`

Which is useful, but also kind of confusing because it isn't clear what the short form arguments actually mean.  It would be preferable if the format was --[longform]|-[shortform] or something along those lines.

Low pri.

**Comment by JasonRShaver** [comment]
Example from a recent build:
```
az vm list -
--debug           --output          --resource-group  -g                -o                
--help            --query           --verbose         -h 
```

**Comment by JasonRShaver** [comment]
Clean
