### ISSUE TITLE
az acr build

### ISSUE THREAD

**Issue by challasatish** [Azure/azure-cli#19009]
## Describe the bug

**Command Name**
`az acr build`

**Errors:**
```
the following arguments are required: <SOURCE_LOCATION>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr build --registry {} --image {}`

## Environment Summary
```
Linux-5.4.0-1055-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.26.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by northtyphoon** [comment]
Thanks for reporting it and sorry for the inconvenience.
2.26.1 has been released to address the issue.
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli

On cloud shell, you can upgrade to 2.26.1 by running

curl -L https://aka.ms/InstallAzureCli | bash
