### ISSUE TITLE
WebApp:az appservice plan create - fails when running from WSL2 Ubuntu

### ISSUE THREAD

**Issue by Minnbrit** [Azure/azure-cli#19028]
## Created a resource group with the cli just fine, but attempting to create an appservice plan inside it gives the error below

**Command Name**
`az appservice plan create`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az appservice plan create --name {} --resource-group {} --sku {} --is-linux`

## Expected Behavior
That the appservice plan is created

## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```
## Additional Context
I am using an up to date Ubuntu under WSL2 on an up to date Win10 machine. 
Installed the Azure CLI yesterday using: `sudo apt install azure-cli`
If I copy the exact same command over to the Azure Cloud Shell everything works as expected.

**Comment by yonzhan** [comment]
route to service team

**Comment by ramya894** [comment]
Looking in to the issue

**Comment by ramya894** [comment]
I am unable to repro the issue in latest CLI version 2.26.0. Please use the latest version

**Comment by Minnbrit** [comment]
Seeing as I was using a new installation I thought had the latest version, I should have double checked.

Found on this page [Install the Azure CLI on Linux](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) that the version on Ubuntu 20.04 coming from the universe repository was out of date.

Removed it as the page suggests, followed the instructions to get the latest version and everything worked.

Sorry to waste you time, thanks for the help!
