### ISSUE TITLE
netappfile create volume from snapshotid failed 

### ISSUE THREAD

**Issue by soodkvishal** [Azure/azure-cli#19029]
## Describe the bug

**Command Name**
`az netappfiles volume create`

**Errors:**
```
(InternalServerError) Host is unavailable
ERROR: 'NoneType' object has no attribute 'rules'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az netappfiles volume create -g {} --account-name {} --pool-name {} --name {} -l {} --vnet {} --subnet {} --service-level {} --usage-threshold {} --file-path {} --protocol-types {} --snapshot-id {}`

## Environment Summary
```
Linux-5.4.17-2102.202.5.el7uek.x86_64-x86_64-with-oracle-7.9
Python 3.6.8
Installer: RPM

azure-cli 2.26.0 *

```

**Comment by yonzhan** [comment]
route to service team

**Comment by audunn** [comment]
Stale fixed issue
