### ISSUE TITLE
[Network] az network application-gateway : Add missing commands for  'client-cert' and 'ssl-profile'

### ISSUE THREAD

**Issue by HemantErappa** [Azure/azure-cli#19036]
**Resource Provider**
Network

**Description of Feature or Work Requested**
Application Gateway Mutual Authentication Support
Overview: https://docs.microsoft.com/en-us/azure/application-gateway/mutual-authentication-overview

**Issue**
https://github.com/Azure/azure-cli/pull/16762 missed adding the following commands:
1. az network application-gateway client-cert show
2. az network application-gateway client-cert update
3. az network application-gateway ssl-profile show
4. az network application-gateway ssl-profile update
5. az network application-gateway http-listener create/update/show: Add parameter --ssl-profile

More information about the feature -
1. Configure mutual authentication with Application Gateway through PowerShell: https://docs.microsoft.com/en-us/azure/application-gateway/mutual-authentication-powershell

2. Powershell PR - https://github.com/Azure/azure-powershell/pull/13277

**Minimum API Version Required**
2020-06-01

**Swagger Link**
Azure/azure-rest-api-specs#9965

**Target Date**
09/30/2021

**Comment by yonzhan** [comment]
network
