### ISSUE TITLE
AAD login window should say Azure CLI, not XPlat

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#1903]
![login](https://cloud.githubusercontent.com/assets/386473/22390214/99fec2d4-e49e-11e6-87ab-9c65bc8da68e.png)

See the image above ☝️

**Comment by tjprescott** [comment]
I believe this is because the app ID used is Xplat's. @yugangw-msft correct me if I'm wrong.

**Comment by devigned** [comment]
I'm 90% sure you are right. I just wanted to make sure we had an issue to track this.

**Comment by yugangw-msft** [comment]
This is indeed right. Closing it as we have internal tracking issue for this
