### ISSUE TITLE
Review link instead of docs link

### ISSUE THREAD

**Issue by idjohnson** [Azure/azure-cli#19059]
This page uses the url ("review"):
https://review.docs.microsoft.com/en-us/azure/storage/blobs/blob-inventory#inventory-policy.

instead of the public
https://docs.microsoft.com/en-us/azure/storage/blobs/blob-inventory#inventory-policy.

Most outside org users cannot access 'review' app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9d4e24-cd52-851d-b0c7-bdf81b906b4c
* Version Independent ID: f5508f3b-df8b-5919-3587-d68cdc88c986
* Content: [az storage account blob-inventory-policy](https://docs.microsoft.com/en-us/cli/azure/storage/account/blob-inventory-policy?view=azure-cli-latest#az_storage_account_blob_inventory_policy_create)
* Content Source: [latest/docs-ref-autogen/storage/account/blob-inventory-policy.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/account/blob-inventory-policy.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage
