### ISSUE TITLE
az webapp deployment source config-zip: Deployment endpoint responded with status code 202. But fail to run?

### ISSUE THREAD

**Issue by gagarine** [Azure/azure-cli#19055]
I'm running `az webapp deployment source config-zip --resource-group XX --name XX --src XX-package.zip` on a Linux Web Service instance.

It's a node project. My zip contain a package.json with a npm start command that I expect Azure to run.

```
...
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
{
  "active": true,
  "author": "N/A",
  "author_email": "N/A",
  "complete": true,
  "deployer": "Push-Deployer",
  "end_time": "2021-07-30T09:41:17.9438556Z",
  "id": "a8063d7cc33943e9b852cd5a12a1184d",
  "is_readonly": true,
  "is_temp": false,
  "last_success_end_time": "2021-07-30T09:41:17.9438556Z",
  "log_url": "https:/xx.scm.azurewebsites.net/api/deployments/latest/log",
  "message": "Created via a push deployment",
  "progress": "",
  "received_time": "2021-07-30T09:41:13.0359297Z",
  "site_name": "xx",
  "start_time": "2021-07-30T09:41:14.2349318Z",
  "status": 4,
  "status_text": "",
  "url": "https://xx.scm.azurewebsites.net/api/deployments/latest"
}
```

But then? The app do not seem to run.

**Comment by gagarine** [comment]
Before trying the az CLI  I did used the VS code app service plugin to deploy and it worked. But I do not like VS code and want to deploy using the CLI for test project.
In production I'm using github to build.

**Comment by yonzhan** [comment]
route to service team

**Comment by gagarine** [comment]
I understand the problem now. The project was not running without some devDependencies.

I reported also that when NODE_ENV=production deployment fail because devDependencies is not used during npm install.: https://github.com/microsoft/Oryx/issues/1068
