### ISSUE TITLE
az appservice domain create errors

### ISSUE THREAD

**Issue by Qay-Tekkie** [Azure/azure-cli#19054]
Adding the --privacy parameter throws an argument error with values of 1 or 0. But adding a value of -p makes the domain purchase operation successful.
Please any ideas of what the -p value means?

**Comment by Qay-Tekkie** [comment]
Please any update on this question?

**Comment by panchagnula** [comment]
@calvinsID can you take a look?

**Comment by calvinsID** [comment]
Hi @Qay-Tekkie, what CLI version are you using and what is the error you are seeing? `--privacy` and `-p` should be the same thing 
![image](https://user-images.githubusercontent.com/14339314/127905577-d29350e1-de10-4f97-ab4c-7e6dd088db65.png)

**Comment by Qay-Tekkie** [comment]
Ok..Thanks
