### ISSUE TITLE
Booleans should be case consistent

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#1906]
```bash
$ az group exists -n blah
false
$ az group exists -n custom-image-vm
true
$ az storage account check-name --name storage123231 --query "nameAvailable" -o tsv
True
$ az storage account check-name --name storage123231
{
  "message": null,
  "nameAvailable": true,
  "reason": null
}
```

It appears that the JSON parsed boolean is returned in upper case rather than lower case.

**Comment by derekbekoe** [comment]
Looks like JSON output is correct according to https://docs.python.org/3/library/json.html#json.JSONEncoder.

Would you expect tsv to have capitalized or all lowercase?

**Comment by devigned** [comment]
I'd expect the same as JSON, I suppose.
