### ISSUE TITLE
Unable to build container registry in Microsoft Training module

### ISSUE THREAD

**Issue by Ren-999** [Azure/azure-cli#19068]
## Describe the bug

**Command Name**
`az acr build`

**Errors:**
```
The resource with name 'rmreg999' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription 'Azure subscription 1 (caa6680a-39af-4664-96e0-27b3c58b7715)'.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr build --registry {} --image {} {}`

## Environment Summary
```
Linux-5.4.0-1055-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.26.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by shizhMSFT** [comment]
Thanks for reporting it and sorry for the inconvenience.
2.26.1 has been released to address the issue.
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli

Please upgrade to the latest version of Azure CLI to resolve this issue.

**Comment by CornerstoneII** [comment]
This issues still persists

```
azure-cli                         2.58.0

core                              2.58.0
telemetry                          1.1.0


```

<img width="683" alt="image" src="https://github.com/Azure/azure-cli/assets/42003510/7ccb0db6-7558-4f82-ba11-c3bad594d40a">

Subscription set to the correct id

<img width="871" alt="image" src="https://github.com/Azure/azure-cli/assets/42003510/f05f18f3-43d1-4bc8-aa13-7b399717a4bb">

Container registry was also created successfully without any errors

<img width="704" alt="image" src="https://github.com/Azure/azure-cli/assets/42003510/0ce35344-825e-4531-9b34-975b43887f32">

az acr login cmd logs into the registry despite the fact it cant be found

<img width="622" alt="image" src="https://github.com/Azure/azure-cli/assets/42003510/7e568473-7110-4684-9ab7-d8ef2a69d11f">

Cant create a container app either

<img width="317" alt="image" src="https://github.com/Azure/azure-cli/assets/42003510/c7b5978f-3879-46f7-a3c5-064a654e675c">

Task for arm service connection and service principal login

**Comment by CornerstoneII** [comment]
After creation it is visible in the portal but some weird reasons the credentials cant be found.
