### ISSUE TITLE
Cannot find user or service principal in graph database for 'msi'. If the assignee is an appId, make sure the corresponding service principal is created with 'az ad sp create --id msi'.

### ISSUE THREAD

**Issue by hernansr** [Azure/azure-cli#19062]
## Describe the bug

**Command Name**
`az role assignment create`

**Errors:**
```
Cannot find user or service principal in graph database for 'msi'. If the assignee is an appId, make sure the corresponding service principal is created with 'az ad sp create --id msi'.

```

## To Reproduce:
Follow https://docs.microsoft.com/en-us/learn/modules/deploy-kubernetes/3-set-up-environment

- _Put any pre-requisite steps here..._
`az configure --defaults location=westus2`
`resourceSuffix=$RANDOM`
`registryName="tailspinspacegame${resourceSuffix}"`
`aksName="tailspinspacegame-${resourceSuffix}"`
`rgName='tailspin-space-game-rg'`
`aksVersion=$(az aks get-versions \
  --query 'orchestrators[-1].orchestratorVersion' \
  --output tsv)`
`az group create --name $rgName`
`az acr create \
  --name $registryName \
  --resource-group $rgName \
  --sku Standard`
`az aks create \
  --name $aksName \
  --resource-group $rgName \
  --enable-addons monitoring \
  --kubernetes-version $aksVersion \
  --generate-ssh-keys`
`clientId=$(az aks show \
  --name $aksName \
  --resource-group $rgName \
  --query "servicePrincipalProfile.clientId" \
  --output tsv)`
`acrId=$(az acr show \
  --name $registryName \
  --resource-group $rgName \
  --query "id" \
  --output tsv)`
`az acr list \
 --resource-group $rgName \
 --query "[].{loginServer: loginServer}" \
 --output table`
`az role assignment create \
  --assignee $clientId \
  --role acrpull \
  --scope $acrId`

## Expected Behavior
It should work according to the course

## Environment Summary
```
Linux-5.4.0-1055-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.26.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by hernansr** [comment]
ugh, I just realized this is the azure-cli project, got this error while trying to complete an Azure course and used `az feedback` to report the problem but I don't think it should be solved in here :( my apologies.
