### ISSUE TITLE
Argument to `--settings` flag in `az functionapp config appsettings set` is not space separated

### ISSUE THREAD

**Issue by j0057** [Azure/azure-cli#19097]
The documentation text for the `--settings` parameter misleadingly states that it takes a space-separated argument in the form of `key=value`:

> Space-separated app settings in a format of \<name\>=\<value\>.

Like this, to set three variables, A, B, and C:

    az functionapp config appsettings -g groupname -n funcname --settings 'A=1 B=2 C=3'

Notice the quoting. However this sets only the first variable, A, to the value `1 B=2 C=3`. In reality the `--settings` flag takes _one or more_ arguments in the form of `key=value`:

    az functionapp config appsettings -g groupname -n funcname --settings A=1 B=2 C=3

I think the text should be made more clear to increase the chance that somebody will get it right on the first attempt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e69fb3-f10c-98ac-0506-35d02f2a7481
* Version Independent ID: ad86610e-e20d-2c96-80fd-61c3d6e7f9ff
* Content: [az functionapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest#az_functionapp_config_appsettings_set)
* Content Source: [latest/docs-ref-autogen/functionapp/config/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/functionapp/config/appsettings.yml)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by gzuber** [comment]
Thanks @j0057, I'll think about a better way to describe this. My first thought is 

> Space-separated __list of__ app settings in a format of \<name>=\<value>.

**Comment by j0057** [comment]
That still sounds wrong to me @gzuber, for three reasons: "a list" is one thing so I would interpret that as one argument, i.e. the same as the current wording; a "list" is not a thing in sh/bash whereas 'arguments' are -- one or more arguments in this instance; the arguments are not necessarily space-separated but could normally be separated by any whitespace as defined by the IFS shell setting. So I would suggest a wording along the lines of _"one or more app settings in the form of `key=value`"_.
