### ISSUE TITLE
az network application-gateway -h doesn't list "show-backend-health" as one of the subgroups.

### ISSUE THREAD

**Issue by miniGweek** [Azure/azure-cli#19099]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Executing `az network application-gateway -h` doesn't list `show-backend-health` as one of the sub groups.

**To Reproduce**
Just run `az network application-gateway -h`
You will notice that `show-backend-health`  is missing from the list of the sub groups
**Expected behavior**
Expected to see `show-backend-health` show up as one of the subgroups.

**Environment summary**
On Windows 10 - version 10.0.19043.0

```
azure-cli                         2.26.1

core                              2.26.1
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0
desktopvirtualization               0.1.0
interactive                        0.4.4
next                               0.1.2
```

**Additional context**

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
It's in Commands.

![image](https://user-images.githubusercontent.com/69238381/128112136-4d5e8362-1139-448e-86bf-051ea3d55c9c.png)
