### ISSUE TITLE
Error: MS Learn Deploy and run a containerized web app with Azure App Service / Exercise - Build and store an image by using Azure Container Registry

### ISSUE THREAD

**Issue by AlekseyNIvanov** [Azure/azure-cli#19096]
### **This is autogenerated. Please review and update as needed.**
MS Learn
Deploy and run a containerized web app with Azure App Service / Exercise - Build and store an image by using Azure Container Registry
## Describe the bug
Run the following command. This command sends the folder's contents to Azure Container Registry, which uses the instructions in the Docker file to build the image and store it. Replace <container_registry_name> with the name of the registry you created earlier.

az acr build --registry <container_registry_name> --image webimage .
**Command Name**
``
![error](https://user-images.githubusercontent.com/86664807/127860431-d7c17ceb-038f-4c16-b6eb-fcbc99fc8c86.PNG)

**Errors:**
```
Packing source code into tar to upload...
Excluding '.gitignore' based on default ignore rules
Uploading archived source code from '/tmp/build_archive_e0cce916ee804d5da9c202e33cdd5f25.tar.gz'...
Sending context (2.141 KiB) to registry: <container_registry_name>...
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/build.py", line 109, in acr_build
    variant=platform_variant
TypeError: 'NoneType' object is not callable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-5.4.0-1055-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.26.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by shizhMSFT** [comment]
Thanks for reporting it and sorry for the inconvenience.
2.26.1 has been released to address the issue.
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli

Please upgrade to the latest version of Azure CLI to resolve this issue.
