### ISSUE TITLE
az provider register should provide wait / no-wait

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#1910]
```bash
$ az provider register --namespace "Microsoft.Storage"
Registering is still on-going. You can monitor using 'az provider show -n Microsoft.Storage'
null
```

"You can monitor using `az provider show...`" doesn't seem like a reasonable way to handle a request for registration. If the rest of the script requires that resource provider to be registered, the consumer of this command will need to loop poling `az provider show` to determine the request result.

There should be wait / no-wait on this command. Wait should wait for the registration to complete and return either an error or the body of the provider.

**Comment by tjprescott** [comment]
Great point. I've added this to our omnibus issue of commands to which we should add this functionality and linked this issue to refer back to the discussion.
