### ISSUE TITLE
Azure CLI Python Dependency Issue

### ISSUE THREAD

**Issue by theoaks** [Azure/azure-cli#19106]
This error keeps coming up. I have python installed. I've tried uninstalling and reinstalling several times, but this doesn't go away. Even googling has brought up no solution.

Command
`$ az -v`
Output
`/usr/local/bin/az: line 2: /usr/local/Cellar/azure-cli/2.27.0/libexec/bin/python: No such file or directory`

Please help

OS: Mac OS Big Sur (Version 11.4 (20F71))

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by Volatus** [comment]
@theoaks Can you try clearing brew cache and maybe reinstalling Python as well? (through brew) I'm on MacOS Big Sur 11.5.1 (M1) and I don't have this problem with `azcli 2.27.0`.

**Comment by theoaks** [comment]
Maybe I should run the latest update pending on my Mac and see if it fixes the issue

**Comment by theoaks** [comment]
Done it... Same error on the new version

**Comment by Volatus** [comment]
> Done it... Same error on the new version

What Python version are you using?

**Comment by theoaks** [comment]
> > Done it... Same error on the new version
> 
> What Python version are you using?

Version 3.9

**Comment by Volatus** [comment]
> > > Done it... Same error on the new version
> > 
> > 
> > What Python version are you using?
> 
> Version 3.9

Can you paste the output of `which az` ?

**Comment by theoaks** [comment]
> > > > Done it... Same error on the new version
> > > 
> > > 
> > > What Python version are you using?
> > 
> > 
> > Version 3.9
> 
> Can you paste the output of `which az` ?


/usr/local/bin/az

**Comment by Volatus** [comment]
> > > > > Done it... Same error on the new version
> > > > 
> > > > 
> > > > What Python version are you using?
> > > 
> > > 
> > > Version 3.9
> > 
> > 
> > Can you paste the output of `which az` ?
> 
> /usr/local/bin/az

yeah that's concerning, can you try `$(brew --prefix)/bin/az -v`?

**Comment by jiasli** [comment]
@Volatus, thanks for the investigation. 😊

I tested on Big Sur 11.5.1 with Intel chip but couldn't repro this issue either. @theoaks, are you on M1 chip?

Azure CLI uses Python 3.8 installed by Homebrew:

```
$ which az
/usr/local/bin/az

$ cat /usr/local/bin/az
#!/usr/bin/env bash
AZ_INSTALLER=HOMEBREW /usr/local/Cellar/azure-cli/2.27.0/libexec/bin/python -m azure.cli "$@"

$ ls -l /usr/local/Cellar/azure-cli/2.27.0/libexec/bin/python
lrwxr-xr-x  1 user1  admin  84 Jul 30 19:10 /usr/local/Cellar/azure-cli/2.27.0/libexec/bin/python -> ../../../../../opt/python@3.8/Frameworks/Python.framework/Versions/3.8/bin/python3.8
```

Could you share the result of 

```
ls -l /usr/local/Cellar/azure-cli/2.27.0/libexec/bin/
```

**Comment by theoaks** [comment]
I'm on an Intel chip

`ls -l /usr/local/Cellar/azure-cli/2.27.0/libexec/bin/python`
==============================================
`lrwxr-xr-x  1 user  admin  84 Jul 30 12:10 /usr/local/Cellar/azure-cli/2.27.0/libexec/bin/python -> ../../../../../opt/python@3.8/Frameworks/Python.framework/Versions/3.8/bin/python3.8`

**Comment by jiasli** [comment]
We recently bumped the underlying Python to 3.9 in Azure CLI 2.27.1. Some users report it is working as expected (https://github.com/Azure/azure-cli/issues/19027#issuecomment-898939377), could you upgrade to the latest version?

**Comment by theoaks** [comment]
> We recently bumped the underlying Python to 3.9 in Azure CLI 2.27.1. Some users report it is working as expected ([#19027 (comment)](https://github.com/Azure/azure-cli/issues/19027#issuecomment-898939377)), could you upgrade to the latest version?

The issue is now resolved. Thanks
