### ISSUE TITLE
"az keyvault secret show" fails missing azure.keyvault.v7_0 dependency

### ISSUE THREAD

**Issue by jrcumming** [Azure/azure-cli#19108]
## Describe the bug

**Command Name**
`az keyvault secret show`

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az keyvault secret show --vault-name {} --name {} --query value -o tsv`

## Environment Summary
```
Linux-5.10.43.3-microsoft-standard-WSL2-x86_64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
keyvault

**Comment by jrcumming** [comment]
Installing the latest version of "az cli" fixed the issue.  This was not initially obvious, as apt reported that the latest version was being used (known issue according to Azure website)

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/19640#issuecomment-1148202854
