### ISSUE TITLE
Running "az keyvault secret list" fails with a missing dependancy error

### ISSUE THREAD

**Issue by grahamhayes** [Azure/azure-cli#19121]
## Describe the bug

**Command Name**
`az keyvault secret list`

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
<frozen importlib._bootstrap>, ln 961, in _find_and_load_unlocked
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault secret list --name {}`

## Expected Behavior

List of secrets

## Environment Summary
```
Linux-5.8.0-1039-azure-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

Clean Ubuntu 20.04.2 LTS VM in azure that had `sudo apt install azure-cli` ran on it

```

**Comment by yonzhan** [comment]
keyvault

**Comment by mitchdenny** [comment]
I'm hitting this at the moment, when will a fix be out?

**Comment by evelyn-ys** [comment]
The built-in azure cli is too old to run. Pls upgrade to latest version which is `2.27.0` for now.

**Comment by evelyn-ys** [comment]
@jiasli Can you help take a look that `sudo apt install azure-cli` will install version `2.0.81` by default?

**Comment by jiasli** [comment]
The `2.0.81` version of Azure CLI distributed by official Ubuntu repo is not maintained by Microsoft. 

Please follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt to install Azure CLI. It will add Microsoft Linux repo https://packages.microsoft.com/repos/azure-cli/ to `apt`'s source list.

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/19640#issuecomment-1148202854
