### ISSUE TITLE
Ability to enable SMB Multichannel for Azure File Shares

### ISSUE THREAD

**Issue by aravindyeduvaka** [Azure/azure-cli#19128]
**Is your feature request related to a problem? Please describe.**
It's not possible to currently enable SMB Multichannel from the Azure CLI even though it is available through portal and Powershell. https://docs.microsoft.com/en-us/azure/storage/files/storage-files-enable-smb-multichannel?tabs=azure-portal 

**Describe the solution you'd like**
I would like to enable SMB Multichannel feature on file share during create. i.e. you can specify this as part of the create payload or something. 

**Describe alternatives you've considered**
We currently do this from portal but this is not scalable for deployments.

**Comment by yonzhan** [comment]
Storage

**Comment by evelyn-ys** [comment]
Hi @aravindyeduvaka, Currently CLI support SMB Multichannel in `storage-preview` extension.
Pls try:
```
# install storage-preview extension
az extension add --name storage-preview

# enable SMB Mutichannel
az storage account file-service-properties update --enable-smb-multichannel -n mystorageaccount -g myresourcegroup
```
