### ISSUE TITLE
yes | az storage account delete ...

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#1912]
With the prompt for yes / no by `az storage account delete`, it seems like I should be able to pipe `yes`, but was unable to with the following output:

```bash
$ yes | az storage account delete -g .... -n ....
Unable to prompt for confirmation as no tty available. Use --force.
Operation cancelled.
```

**Comment by johanste** [comment]
@devigned, is there a specific reason you'd prefer to pipe yes instead of using --force?

**Comment by devigned** [comment]
I don't prefer if there is always a way to bypass the confirmation and that --force doesn't cause an behavioral change in the command.

@johanste I think we can close this since we decided that --force will always be the same behavior based on our discussion at stand up.
