### ISSUE TITLE
Announcement: Renaming "master" to "main" in this repository

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#19130]
On the 18th of June, 2021 (PST) we will be renaming the ```master``` branch in this repository to ```main```. When this occurs there will be some disruption to the engineering system as we address any issues that earlier preparations did not address. Please read the following centralized issue for more background on what to expect:

> https://github.com/Azure/azure-sdk/issues/2745

Localized issues in this repository can be discussed here.

# Engineering System Checklist
The following checklist will be executed by a member of the Azure SDK Engineering System team when the branch rename occurs. If errors occur they'll need to be addressed:

- [x] Ensure repo mirroring is stopped (coordination across repos required).
- [x] Rename the master branch to main on this repository.
- [x] Rename the master branch on the ```-pr``` repository.
- [x] Rename the master branch on the ```azure-sdk``` user's clone of this repository.
- [x] Rename the master branch on the ```azure-sdk``` user's clone of the ```-pr``` repository.
- [x] Ensure repo mirroring is started (coordination across repos required).
- [x] Ensure pipeline generation has been run and pipelines have been updated to correct branch.
- [x] Submit a PR to ensure that PR validation is executing correctly.
- [x] Merge PR to ensure that CI triggers are executing correctly.
- [x] Trigger template release pipeline to ensure end-to-end release process is working correctly.

**Comment by yonzhan** [comment]
Renaming "master" to "main"

**Comment by praenubilus** [comment]
python pip module on pypl is broken, when executing `azdev setup`, the following error will happen because the pip module is still pointing to `master` branch
```
~/env/bin/python -m pip install git+https://github.com/Azure/azure-cli@master#subdirectory=src/azure-cli-testsdk` failed with exit code 1:
Collecting git+https://github.com/Azure/azure-cli@master#subdirectory=src/azure-cli-testsdk
  Cloning https://github.com/Azure/azure-cli (to revision master) to /tmp/pip-req-build-k8x_5z_1
  Running command git clone -q https://github.com/Azure/azure-cli /tmp/pip-req-build-k8x_5z_1
  WARNING: Did not find branch or tag 'master', assuming revision or ref.
  Running command git checkout -q master
  error: pathspec 'master' did not match any file(s) known to git.
WARNING: Discarding git+https://github.com/Azure/azure-cli@master#subdirectory=src/azure-cli-testsdk. Command errored out with exit status 1: git checkout -q master Check the logs for full command output.
ERROR: Command errored out with exit status 1: git checkout -q master Check the logs for full command output.
```

**Comment by kairu-ms** [comment]
> python `azdev` module on pypl is broken, when executing `azdev setup`, the following error will happen because the pip module is still pointing to `master` branch
> 
> ```
> ~/env/bin/python -m pip install git+https://github.com/Azure/azure-cli@master#subdirectory=src/azure-cli-testsdk` failed with exit code 1:
> Collecting git+https://github.com/Azure/azure-cli@master#subdirectory=src/azure-cli-testsdk
>   Cloning https://github.com/Azure/azure-cli (to revision master) to /tmp/pip-req-build-k8x_5z_1
>   Running command git clone -q https://github.com/Azure/azure-cli /tmp/pip-req-build-k8x_5z_1
>   WARNING: Did not find branch or tag 'master', assuming revision or ref.
>   Running command git checkout -q master
>   error: pathspec 'master' did not match any file(s) known to git.
> WARNING: Discarding git+https://github.com/Azure/azure-cli@master#subdirectory=src/azure-cli-testsdk. Command errored out with exit status 1: git checkout -q master Check the logs for full command output.
> ERROR: Command errored out with exit status 1: git checkout -q master Check the logs for full command output.
> ```

Thanks for your feedback, It's already fixed in this [PR](https://github.com/Azure/azure-cli-dev-tools/pull/315), which will be contained in next release.
