### ISSUE TITLE
az ad app credential delete fails with more than 1 credential

### ISSUE THREAD

**Issue by rouke-broersma** [Azure/azure-cli#19136]
## Describe the bug

When an app has more than 1 credential the `az ad app credential delete` command fails with the below error. I believe this error has previously been reported for the powershell commandlet as well and has been fixed there. This bug was first reported at https://github.com/Azure/azure-cli/issues/5750 in 2018 but was marked as a feature.

**Command Name**
`az ad app credential delete`

**Errors:**
```
Update to existing credential with KeyId '<key-id>' is not allowed.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `$appId = <app-id>`
- `$credential = az ad app credential reset --id $appId --append | ConvertFrom-Json`
- `$credential2 = az ad app credential reset --id $appId --append | ConvertFrom-Json`
- `az ad app credential delete --id $appId --key-id $credential.keyId`

## Expected Behavior

Credential is deleted

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.25.0 *

Extensions:
alias 0.5.2
account 0.2.1

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
It is very likely the error `Update to existing credential with KeyId '<key-id>' is not allowed.` is causes by an old Azure PowerShell / Azure Portal issue. The explanation and solution are provided at https://github.com/Azure/azure-cli/issues/12561#issuecomment-604991103

**Comment by rouke-broersma** [comment]
We are using az cli.

**Comment by jiasli** [comment]
I am able to repro this issue using `AzureAD` PowerShell module: https://github.com/Azure/azure-cli/issues/14551#issuecomment-893971661

**Comment by rouke-broersma** [comment]
@jiasli I checked the start and end dates of the credentials and they look like this: `"startDate": "2021-08-06T07:42:51.592775Z", "endDate": "2023-08-06T07:42:51.592775Z"`

This looks to me like nanosecond precision instead of millisecond, is that correct?

These credentials were created with the azure graph api by using `az rest` and providing a custom start and end date which we modified to not have nanosecond precision. However due to a bug in our scripting we ended up sending a malformed request that did not contain the start and end date in the correct json format so our custom start and end date was ignored by the graph api. Instead the default was used. **This default sets the validity to 2 years and seems to include nanosecond precision for some reason.**

We did not choose this as far as I can tell, because the maximum validity for a credential in our scripting is 90 days. So 2 years would have been impossible if our start and end date was used.

**Comment by jiasli** [comment]
Please refrain from using `az ad` on credential operations, due to the deprecation of underlying AD Graph API, and we no longer actively maintain it. 

You may see our plan to migrate to Microsoft Graph at https://github.com/Azure/azure-cli/issues/12946 and stick to `az rest`.

**Comment by rouke-broersma** [comment]
@jiasli I rewrote the script to use az rest for both creation and deletion. The same issue persists. If no start and end date is given with the creation request, microsoft graph api seems to pick 2 years as a default, **and it appears that this default is in nano seconds** and not milliseconds. That's what I explained in my last comment.

So while the azure portal and powershell modules have been fixed to not create passwords with nanosecond precision, the microsoft graph api both still accept nanoseconds and also actually has a default start and end date in nanosecond precision. I will provide a reproduction scenario soon but to me it seems clear that it does not make sense to keep changing other clients because of az cli/python... Either python needs to support what the API supports OR better yet the API should be changed to no longer accept AND no longer generate nanosecond precision.

Other wise this issue is doing to keep coming back... The Bicep team is going to create integration with microsoft graph soon. They will probably build against the api spec and Bicep is made in dotnet. They are very likely to actually run into this issue...

**Comment by jiasli** [comment]
`az rest` doesn't parse the response anyway and the `startDateTime` and `endDateTime` (even with nanosecond) are treated as string.

Therefore, if you use `az rest` all the time, it is impossible to hit this nanosecond issue:

```
$ az rest --method GET --url https://graph.microsoft.com/v1.0/applications/ab2a396e-b4d4-4055-86ef-ef8917b04246
...
  "passwordCredentials": [
    {
      "customKeyIdentifier": null,
      "displayName": null,
      "endDateTime": "2022-12-06T03:09:45.2705195Z",
                                                ^
      "hint": null,
      "keyId": "4b54b20a-e540-4cca-a20a-e8851ba7ee7f",
      "secretText": null,
      "startDateTime": "2021-08-06T03:11:09.845617Z"
    }
  ],
```

**Comment by jiasli** [comment]
> The point still stands though, the API is the one generating the nanosecond start and end time here, which az cli cannot deal with. It would be much better if either az-cli could conform to the api spec, or the api spec is changed to conform to the lowest common denominator (milliseconds). This disconnect is painful.

We fully understand. In the future, Azure CLI may perhaps not even support Microsoft Graph at all, since Microsoft Graph team is building on their own CLI: https://github.com/microsoftgraph/msgraph-cli

Even if Azure CLI supports Microsoft Graph, it's very likely we won't rely on Python SDK and build the `Application` object, thus won't hit the `datatime` precision issue.

Anyway, we haven't decided which way to go and `az rest` with Microsoft Graph is by far the best solution.

**Comment by rouke-broersma** [comment]
@jiasli on that point I would like to say that please support microsoft graph in the az cli... The microsoft graph is very much necessary for azure deployments. It would be very annoying have to use two cli's with their own distinct cli syntaxes (I checked, msgraph-cli looks nothing like the az-cli standard command syntax..) imo. Couldn't the msgraph-cli team just adopt this part of the az-cli instead of building their own fork specific to msgraph..

**Comment by jiasli** [comment]
This is indeed a complex topic and we heard your voice! Thanks for letting us know.

Due to drastic changes in Microsoft Graph API, even if Azure CLI migrates its underlying API to Microsoft Graph API, it is nearly impossible to keep backward compatibility, making the migration less meaningful. It will also introduce duplications between Azure CLI and Microsoft Graph CLI.

Anyway, we are still in planning phase and discussing about all possible solutions with Product Managers from both Azure CLI and Microsoft Graph teams. Stay tuned!
