### ISSUE TITLE
az appconfig kv export usage error when using AD login auth

### ISSUE THREAD

**Issue by aadje** [Azure/azure-cli#19139]
**Describe the bug**
`az appconfig kv export` to another appconfig instance always fails on a `usage error` when specifying the endpoint + auth-mode login params for both app config instances.

**Command Name**
`az appconfig kv export`

**Errors:**
```
usage error: --config-name NAME | --connection-string STR
```

**To Reproduce**
```
az appconfig kv export -d appconfig --endpoint https://myappconfiguration.azconfig.io --auth-mode login --dest-endpoint https://anotherappconfiguration.azconfig.io --dest-auth-mode login --key * --label * --preserve-labels
```

**Expected behavior**
This is a valid parameter set. App Config export should start 

**Environment summary**
azure-cli 2.27.0
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
Both in CMD and PsCore7 consoles.
Windows-10-10.0.19041-SP0
Installer: MSI

**Additional context**
This is documented as an example at 
https://docs.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest#az_appconfig_kv_export-examples

Both Key Vaults have the `App Configuration Data Owner` Rbac role assigned for the authenticated azure-cli user.
The export does work when using access key authentication.

**Comment by yonzhan** [comment]
route to service team

**Comment by avanigupta** [comment]
Hello @aadje, thank you for reporting this. We are working on fixing this issue and it should be available in the next CLI release.
