### ISSUE TITLE
Storage command arguments consistency

### ISSUE THREAD

**Issue by seguler** [Azure/azure-cli#1914]
Please align all the arguments in storage commands so they are consistent. For instance when I want to download a blob; destination folder argument is **"-f"**; however in the file case it is **"--dest"**

```
az storage blob download -c $container_name -f $destination_folder/$blob_name -n $blob_name
az storage file download -s $share_name -p $source_path --dest $destination_path
```

Another example is that in the upload case, it is totally different:

```
az storage file upload --source $full_path_to_file -s $share_name -p $directory_name
az storage blob upload -f $file_to_upload -c $container_name -n $blob_name
```

Can we please simplify these to be **-d** for destination, **-s** for source ?

**Comment by twitchax** [comment]
@troydai, we are getting a full list...keep an eye out on this one.

**Comment by troydai** [comment]
roger.

**Comment by seguler** [comment]
@troydai , @twitchax 

After a second look at this, I think the current design is good. In the blob upload, download case, if we change the option to --source and --dest, then we will break the CLI overall design pattern, which is requiring -n/--name for the storage object. I am afraid otherwise users may have hard time understanding.

As for the file upload, download case, the file object could include a path/directory, hence calling it with --name option doesn't make sense, hence the current design.
 
I think we can close the issue. Sorry for bringing this up in first place without thinking thorough.

**Comment by twitchax** [comment]
No problem: thanks for the update.
