### ISSUE TITLE
API Endpoint Does Not Work As Expected: waf-policy managed-rule exclusion remove

### ISSUE THREAD

**Issue by ErezEyal** [Azure/azure-cli#19155]
## Describe the bug

The below *remove* operation is actually doing a *list* operation. So currently it is not possible to remove a waf-policy exclusion via the CLI.

**Command Name**
`az network application-gateway waf-policy managed-rule exclusion remove`

**Errors:**
There is no error, the command simply lists the waf policy, instead of running a Remove action.

## To Reproduce:

Simply run a Remove operation, as mentioned here:
https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/waf-policy/managed-rule/exclusion?view=azure-cli-latest#az_network_application_gateway_waf_policy_managed_rule_exclusion_remove 

You can also see that the documentation is having the same problem, where the explanation for Remove is actually the same of the one for List.

## Expected Behavior
The Remove API call should remove existing exclusions, rather than listing the waf-policy.

## Environment Summary
```
Linux-5.4.0-1055-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.27.0

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
network

**Comment by 00Kai0** [comment]
It's not an issue. Remove Exclusion just cleans the [parameter exclusions of policy](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/custom.py#L1855).
We don't have a delete api for this option.

Why you got a policy as result. It's just a result we got from updating policy which deleted the exclusion.

**Comment by 00Kai0** [comment]
Hi @ErezEyal , this operation works well at our testcase. But It's true that the description has some mistakes. Thanks for your report :)
