### ISSUE TITLE
Unable to run 'az login' in Azure ML compute instance terminal

### ISSUE THREAD

**Issue by sdonohoo** [Azure/azure-cli#19169]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'user_agent'
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 152, in login
    subscriptions = profile.find_subscriptions_on_login(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 208, in find_subscriptions_on_login
    subscriptions = subscription_finder.find_through_interactive_flow(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 930, in find_through_interactive_flow
    result = self._find_using_common_tenant(token_entry[_ACCESS_TOKEN], resource)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 962, in _find_using_common_tenant
    client = self._arm_client_factory(token_credential)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 880, in create_arm_client_factory
    client = client_type(credentials, api_version=api_version,
TypeError: __init__() got an unexpected keyword argument 'user_agent'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.4.0-1047-azure-x86_64-with-glibc2.10
Python 3.8.1
Installer: PIP

azure-cli 2.27.0
azure-cli-ml 1.33.0

Extensions:
azure-cli-ml 1.33.0

```
## Additional Context

Have tried from VSCode remote sessions, and from integrated terminal on AzureML compute instance. Tried both existing compute instance with az cli upgraded and brand new default compute instance. In both cases, versions were:
{
  "azure-cli": "2.27.0",
  "azure-cli-core": "2.27.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-cli-ml": "1.33.0"
  }
}

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Could be related to https://github.com/Azure/azure-cli/issues/18626.

@sdonohoo, have you manually installed Azure CLI with `pip` on the Azure ML compute instance?

**Comment by sdonohoo** [comment]
Hi, @jiasli. The Azure CLI and azure-cli-ml extension are preinstalled on an Azure ML compute instance. I believe the cli is installed via pip but I am not certain. I have manually upgrade the cli in the past using 'az upgrade'.

**Comment by jiasli** [comment]
@sdonohoo, I see. `az upgrade` won't help because the latest Azure CLI doesn't work with `azureml-core`. We are working internally with ML team to fix `azureml-core`.

**Comment by bandsina** [comment]
@jiasli , @sdonohoo Actually, az upgrade command worked for me and got rid of this error on az login.

**Comment by jiasli** [comment]
@bandsina, if you upgrade Azure CLI, the ML SDK `azureml-core` on the instance will be broken. We would still recommend installing Azure CLI in a virtual environment for the time being until `azureml-core` bumps the dependency on `azure-mgmt-resource` to track 2. See https://github.com/Azure/azure-cli/issues/18626#issuecomment-887411446.

**Comment by sdonohoo** [comment]
Thank you, @jiasli. 

I did try updating both the az cli and azureml extension this morning. The az cli updated from 2.27.0 to 2.27.2 and at least the 'az login' error has gone away on the compute instance. I am able to login. It's not clear to me what other breakage might exist. It's worth noting that, at this time, I am working with the AzureML cli 2.0 preview extension (v2.0.1a5) which did not update along with the Azure cli. Prior to the az cli update, both the GA AMLv1 cli extension and the cli 2.0 preview extension exhibited the same login error. I don't yet know if the login issue goes away with az cli 2.27.2 + AML cliV1.

The open issue you mention that still has breakage refers to a conflict with azureml-train-automl-runtime which the ML cli 2.0 preview does not yet fully support so I wouldn't expect any issues at this time. Is this conflict likely to cause any other breakages?

Thanks

**Comment by jiasli** [comment]
> both the GA AMLv1 cli extension and the cli 2.0 preview extension exhibited the same login error

I checked the wheel file of `azure-cli-ml`:

https://github.com/Azure/azure-cli-extensions/blob/ff20effe1c4aca1dc71bf57251685e43a3f0a646/src/index.json#L4276-L4279

```
        "azure-cli-ml": [
            {
                "downloadUrl": "https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.29.0-py3-none-any.whl",
                "filename": "azure_cli_ml-1.29.0-py3-none-any.whl",
```

In `azure_cli_ml-1.29.0.dist-info/METADATA`, it requires 

```
Requires-Dist: azureml-cli-common (~=1.29.0)
```

From the wheel of `azureml-cli-common` (https://pypi.org/project/azureml-cli-common/#files), in `azureml_cli_common-1.33.0.dist-info/METADATA`, it still requires 

```
Requires-Dist: azureml-core (~=1.33.0)
```

> The open issue you mention that still has breakage refers to a conflict with azureml-train-automl-runtime which the ML cli 2.0 preview does not yet fully support

The conflict doesn’t directly occur on `azureml-train-automl-runtime`, but on `azureml-core` which is an underlying dependency of `azureml-train-automl-runtime`. (https://github.com/Azure/azure-cli/issues/18626#issuecomment-879609185)

**Comment by jiasli** [comment]
This should be fixed by Machine Learning team.
