### ISSUE TITLE
Adding a DNS Name to a public IP results in an error

### ISSUE THREAD

**Issue by bweissman** [Azure/azure-cli#19176]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Adding a DNS Name to a public IP results in an error:
unrecognized arguments: ​--dns-name bwtestrepo

**To Reproduce**
az network public-ip create --name PIP-Test --resource-group $RG ​--dns-name bwtestrepo

**Expected behavior**
This should create a public IP with the DNS Name bwtestrepo

**Environment summary**
{
  "azure-cli": "2.27.0",
  "azure-cli-core": "2.27.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "account": "0.2.1",
    "arcdata": "1.0.0",
    "connectedk8s": "1.1.6",
    "customlocation": "0.1.2",
    "k8s-configuration": "1.1.0",
    "k8s-extension": "0.6.1"
  }
}

**Additional context**

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Hi @bweissman, It can work for me.
![image](https://user-images.githubusercontent.com/69238381/128961407-ea4812a9-5995-4fb9-9bb7-006adf63b898.png)
Could you show me the `command arguments` in log by adding `--debug` at the end of your command?
![image](https://user-images.githubusercontent.com/69238381/128961623-8779ee34-f6e8-4e19-89fc-e1bcdc7a1e2d.png)

**Comment by bweissman** [comment]
found the issue... before my --dns-name is a zero width space... however it got there...

sorry!
