### ISSUE TITLE
Add new properties to Log Analytics SDK

### ISSUE THREAD

**Issue by dhaiman** [Azure/azure-cli#19180]
Please add Log Analytics Workspace missing properties to SDK.
Attaching last PR: https://github.com/Azure/azure-rest-api-specs/blob/56cd4784756e65c303ed7aba007ffa8c7540a587/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2020-10-01/Workspaces.json#L593

Thanks!

**Comment by yonzhan** [comment]
Please open this issue to SDK repo https://github.com/Azure/azure-sdk-for-python
