### ISSUE TITLE
Purview GA Azure CLI request, api-version "2021-07-01"

### ISSUE THREAD

**Issue by annoakes** [Azure/azure-cli#19186]
/**Resource Provider**
Microsoft.Purview

**Description of Feature or Work Requested**
Onboard Azure CLI for Microsoft.Purview Resource Provider to preform CRUD operations on resources.
Scope of onboarding is for management plane APIs, resource types are: Accounts, DefaultAccounts, PrivateEndpoints and PrivateLinks

**Minimum API Version Required**
2021-07-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/purview/resource-manager/Microsoft.Purview/stable/2021-07-01/purview.json

**Target Date**
We GA on 9/27, target for testing and final GA sign off is first week of September. Can we target 9/3?

**Comment by yonzhan** [comment]
PLR

**Comment by kairu-ms** [comment]
Hi @annoakes, we have limited bandwidth to do it right now. Because this PLR will be onboarded as an extension which is flexible to release, could we release it in the middle of September?

**Comment by kairu-ms** [comment]
@00Kai0 Could add the new PrivateEndpoints and PrivateLinks of Microsoft.Purview in main repo this sprint?

**Comment by annoakes** [comment]
> Hi @annoakes, we have limited bandwidth to do it right now. Because this PLR will be onboarded as an extension which is flexible to release, could we release it in the middle of September?

Hello, is it possible to get Sept 1st week? That is the current timeline for the other PLR sign offs, apologies for this coming in late, but there are only a few resources to track here

**Comment by yonzhan** [comment]
@annoakes Due to recent re-org, we have attrition in my team and our developers are occupied with knowledge transition. I think it is very hard to commit the Sept 1st week.

**Comment by annoakes** [comment]
> @annoakes Due to recent re-org, we have attrition in my team and our developers are occupied with knowledge transition. I think it is very hard to commit the Sept 1st week.

Understood, does that put the commitment at 9/10?

**Comment by PARADISSEEKR** [comment]
Hi @annoakes ,when I create purview account ,service returned an error `Internal Server Error`, when it is executed for the second time, it prompts that `the resource already exists`, but when using `accout show`, it returns `The resource 'xxx' already exists in location 'westeurope' in resource group 'xxx'. A resource with the same name cannot be created in location 'southeastasia'. Please select a new resource name.`. What should I do?
This is some debuginfo:
`Request body:
cli.azure.cli.core.sdk.policies: {"identity": {"type": "SystemAssigned"}, "location": "eastus2", "properties": {"publicNetworkAccess": "Enabled"}}`
`Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"500","message":"Unknown error","target":null,"details":null}}`

**Comment by PARADISSEEKR** [comment]
Hi @annoakes ,how to correctly create a private endpoint connection, when I pass in the `private_endpoint_connection_name` parameter, it always prompts that it does not exist, even if I create a "private endpoint resource“ on the portal, it is the same.
Request body:
{"properties": {"privateEndpoint": {"id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/pvtest/providers/Microsoft.Network/privateEndpoints/point1"}, "privateLinkServiceConnectionState": {"status": "Approved"}}}

Response content:
 {"error":{"code":"10006","message":"The private endpoint connection point1 does not exist.","target":null,"details":[]}}
