### ISSUE TITLE
Mistake in docs for --workspaces option

### ISSUE THREAD

**Issue by omziv** [Azure/azure-cli#19181]
[Enter feedback here]

Adding workspaces cannot be done by separating them with spaces, this causes an error for Bad Argument. Docs should be updated to state that workspaces must be added in this format:
--workspaces $("ws1","ws2")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56af75a3-3b2f-711b-21b3-57375fbe124d
* Version Independent ID: 93d7d728-534e-3e1e-e138-bcaf040ebd2d
* Content: [az monitor log-analytics](https://docs.microsoft.com/en-us/cli/azure/monitor/log-analytics?view=azure-cli-latest#az_monitor_log_analytics_query)
* Content Source: [latest/docs-ref-autogen/monitor/log-analytics.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/monitor/log-analytics.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
@PARADISSEEKR, could you please test and update `log-analytics` extension?

**Comment by umarelx** [comment]
@omziv , after my double check, "--workspaces" works with space-separated workspace IDs. Maybe "BadArgumentError" caused by mistaken input of other arguments. Thanks.
