### ISSUE TITLE
docker run mcr.microsoft.com/azure-cli az takes a long time

### ISSUE THREAD

**Issue by arykov** [Azure/azure-cli#19183]
**Describe the bug**
az takes a very long time(over a minute and a quarter when tested) when executed the first time in the environment with no connection to raw.githubusercontent.com when invoked in docker container 2.26.1

If one were to enter shell:
`docker run mcr.microsoft.com/azure-cli:2.26.1` and run az twice in a row, only the first invocation is slow. Assume contents of /root/.azure/versionsCheck.json does the trick.

**To Reproduce**
in the environment where  raw.githubusercontent.com is not accessible(no response when trying to establish connection)
`docker run mcr.microsoft.com/azure-cli:2.26.1 az`
takes a long time
**Expected behavior**
Expect to timeout within a few seconds. Also it would be useful to have a way to disable check for update

**Environment summary**
Initially reproduce on Windows 10 enterprise host with no direct access to raw.githubusercontent.com

**Workaround**
I am sure there are other options, but adding
`127.0.0.1 raw.githubusercontent.com` to /etc/hosts predictably addresses the issue. Kills ability to update as well.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The timeout for connecting to `https://raw.githubusercontent.com/` is 10 seconds:

https://github.com/Azure/azure-cli/blob/3e62f39aea845e68f5f944c3c9d14e6d74f1737f/src/azure-cli-core/azure/cli/core/util.py#L275

The switch for version check is at

https://github.com/Azure/azure-cli/blob/a12f5762e02d6d41927280557046eb76241194f2/src/azure-cli/azure/cli/__main__.py#L75

You may turn it off with

```
az config set auto-upgrade.enable=False
```

or setting environment variable

```
AZURE_AUTO-UPGRADE_ENABLE=False
```

We will document this usage in https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration

**Comment by arykov** [comment]
1) You clearly have not tried to reproduce
Simple way to do so is this:
- docker run -it mcr.microsoft.com/azure-cli 
- `echo "192.168.1.200 raw.githubusercontents.com" >> /etc/hosts`. Put some ip there that is inaccessible. This works in my home network to simulate inaccessible raw.githubusercontents.com. With this setup I get 20 seconds wait time. At work it is ~1minute 20 seconds. Assume TCP connection scenario is slightly different, but this will do.
- `time az`
- if you want to run again without exiting and reentering, simply run `rm -rf /root/.azure`
2) Your suggested workarounds don't work
- az config set auto-upgrade.enable=False does not help on the first execution, since prior to calling config az tries to upgrade first. 
- AZURE_AUTO-UPGRADE_ENABLE is not a valid variable name in Linux. 
- setting AZURE_AUTO_UPGRADE_ENABLE=False or AZURE_AUTO_UPGRADE_ENABLE=false yields nothing
- Searching for [AZURE_AUTO-UPGRADE_ENABLE](https://github.com/Azure/azure-cli/search?q=AZURE_AUTO-UPGRADE_ENABLE) or [AZURE_AUTO_UPGRADE_ENABLE](https://github.com/Azure/azure-cli/search?q=AZURE_AUTO_UPGRADE_ENABLE) in azure-cli yields nothing

**Comment by jiasli** [comment]
@arykov, thanks for the suggestion. The developer of `az upgrade` has left the team recently, so I need some time to get familiar with it.

I can produce this issue per your steps:

```
> docker run -it mcr.microsoft.com/azure-cli
```

```
# echo "192.168.1.200 raw.githubusercontents.com" >> /etc/hosts
# time az
real    0m22.090s
user    0m1.369s
sys     0m0.162s
```

`get_latest_from_github` is called twice for both `azure-cli-core` and `azure-cli-telemetry`, so the 20 seconds wait time should be excepted:

https://github.com/Azure/azure-cli/blob/c100b8026cdb4261b773c44cb0551285734aac84/src/azure-cli-core/azure/cli/core/util.py#L295-L296

The ~1minute 20 seconds wait time should be due to some other unknown reasons. But still, this 20 seconds wait time is too long. (⚠ Issue 1) 

I also checked the code path and found there is no way to disable this check. `auto-upgrade.enable` won't work! (⚠ Issue 2)

This exposes an internal problem that all `logger` invocations are not printed even if `--debug` is specified. This is because `get_latest_from_github` is called in `AzCli.__init__`, long before the `logger` is initialized. (⚠ Issue 3)

> `az config set auto-upgrade.enable=False` does not help on the first execution, since prior to calling config az tries to upgrade first.

Sorry my fault, I forget about this...

> `AZURE_AUTO-UPGRADE_ENABLE` is not a valid variable name in Linux. (⚠ Issue 4)

True. The previous developer doesn't take this into consideration:

```
$ export AZURE_AUTO-UPGRADE_ENABLE=False
-bash: export: `AZURE_AUTO-UPGRADE_ENABLE=False': not a valid identifier
```

I will fix it later. 

> setting `AZURE_AUTO_UPGRADE_ENABLE=False` or `AZURE_AUTO_UPGRADE_ENABLE=false` yields nothing

This is because only `AZURE_AUTO-UPGRADE_ENABLE` is recognized by `az`.

> Searching for `AZURE_AUTO-UPGRADE_ENABLE` or `AZURE_AUTO_UPGRADE_ENABLE` in azure-cli yields nothing

This is because these env vars are dynamically generated by Knack from the config option section and name: https://github.com/microsoft/knack/blob/676477eb34e6deb106c296adf0ae5b2ea0e4a6c0/knack/config.py#L75-L77

**Comment by arykov** [comment]
A "nice to have" would be adding parameter to az that would induce the same type of behaviour. It would make one liner slightly less awkward
`(export AZURE_AUTO_UPGRADE_ENABLE=false && az)`
vs
`az -disableUpgrade` or something along these lines

**Comment by jiasli** [comment]
Thanks for the suggestion. 

**Disabling version check** is more of a global configuration. `--disable-upgrade` in such case is a per-command configuration. You will need it for every commands. If any command doesn't have it, the version check will kick in. We just want to make configurations more concentrated to `az config` and env vars.

In addition, `--disable-upgrade` will be a global argument. This will further bloat AzCLI's global arguments.

**Comment by jkroepke** [comment]
> This is because only AZURE_AUTO-UPGRADE_ENABLE is recognized by az.

A potential workaround cloud be the tool `env`, since env is able to set non posix compatible environment variables

```
% env AZURE_AUTO-UPGRADE_ENABLE=False env | grep UPG
AZURE_AUTO-UPGRADE_ENABLE=False
```

in my case, it setup an shell alias for solve this issue (currently untested, if it really solve it):

```
% alias az
az='env AZURE_AUTO-UPGRADE_ENABLE=False az'
```

**Comment by Styxxy** [comment]
The same issue (still) exists for Windows (non-docker). Any updates on this?

![image](https://user-images.githubusercontent.com/1635825/225586244-f522c112-98dd-4728-a47d-a718fab854f5.png)

**Comment by diguardiag** [comment]
Any news about this? this is becoming annoying with tools and automations running az cli commands..

Also, "AZURE_AUTO-UPGRADE_ENABLE" not working on me (as it is not a valid ENV variable on MacOS/Linux, because it contains a hyphen)

**Comment by bebound** [comment]
You can always disable auto upgrade with `az config set auto-upgrade.enable=False`.
Hyphen is annoying in variable name. `env 'AZURE_AUTO-UPGRADE_ENABLE=False'` may works.
