### ISSUE TITLE
SourceFlow Solutions

### ISSUE THREAD

**Issue by Peggysus** [Azure/azure-cli#19198]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37c3520b-e1ab-8090-9bdb-2506c18cf1aa
* Version Independent ID: d711595b-6162-6b8f-402b-257a7e6dda87
* Content: [az cosmosdb keys](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/keys?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/cosmosdb/keys.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/cosmosdb/keys.yml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by AverageDesigner** [comment]
@Peggysus, Can you please provide the actual question that you are trying to ask.
