### ISSUE TITLE
Program 'az.cmd' failed to run: The system cannot find the file specifiedAt line:1 char:1

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#19202]
Program 'az.cmd' failed to run: The system cannot find the file specifiedAt line:1 char:1

```
+ az --version
+ ~~~~~~~~~~~~.
At line:1 char:1
+ az --version
+ ~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

i am facing this error , not getting how to fix it , as i am using windows 10 machine ,powershell 3.10 is installed

_Originally posted by @gyalamanch in https://github.com/Azure/azure-cli/issues/9562#issuecomment-897265333_

**Comment by jiasli** [comment]
@gyalamanch, could you share 

1. How did you install Azure CLI? We recommend [installing with MSI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli).
2. Which version of Azure CLI you are using? 
3. PowerShell 3.10 is very old. Could you try the latest [PowerShell 7.1](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1)?
4. What is the output of 
    ```
    Get-Command az | Format-List
    ```
5. Does it work if you directly invoke: 
    ```
    & "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -IBm azure.cli
    ```

**Comment by gyalamanch** [comment]
PS C:\Users\gyalamanch001> Get-Command az | Format-List

Name            : az.cmd
CommandType     : Application
Definition      : C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
Extension       : .cmd
Path            : C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
FileVersionInfo : File:             C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
                  InternalName:
                  OriginalFilename:
                  FileVersion:
                  FileDescription:
                  Product:
                  ProductVersion:
                  Debug:            False
                  Patched:          False
                  PreRelease:       False
                  PrivateBuild:     False
                  SpecialBuild:     False
                  Language:

**Comment by gyalamanch** [comment]
Point 1 : yes its with MSI
Point 2 : running with 2.7.1 
point 3 : installed powershell 7.1 
point 5 : yes

**Comment by jiasli** [comment]
This is weird. If you check the content of `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd`, it is simply a cmd script which launches Python with Azure CLI:

```
> Get-Content "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd"
::
:: Microsoft Azure CLI - Windows Installer - Author file components script
:: Copyright (C) Microsoft Corporation. All Rights Reserved.
::

@IF EXIST "%~dp0\..\python.exe" (
  SET AZ_INSTALLER=MSI
  "%~dp0\..\python.exe" -IBm azure.cli %*
) ELSE (
  echo Failed to load python executable.
  exit /b 1
)
```

1. Does `az` work in Command Prompt?
2. Could you check the content of `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd`?

**Comment by jiasli** [comment]
I found these posts on internet:

- https://stackoverflow.com/questions/15485632/node-js-npm-error-message-system-cannot-find-the-path-specified
- https://devblogs.microsoft.com/oldnewthing/20071121-00/?p=24433
- https://github.com/cmderdev/cmder/issues/121#issuecomment-48052882

The error doesn't seem to come from `az.cmd`, but from some misconfiguration of CMD itself. Could you open Registry Editor by running `regedit` and check the value of

```
HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun
```

If there is any command, please remove it to see if the issue is solved.

**Comment by gyalamanch** [comment]
i do not see that in the path 
![image](https://user-images.githubusercontent.com/88805737/129382936-0094e035-2ec3-49bd-90a9-7275a72d241f.png)

**Comment by jiasli** [comment]
You are checking `HKEY_LOCAL_MACHINE`. How about `HKEY_CURRENT_USER`?

**Comment by gyalamanch** [comment]
both

**Comment by jiasli** [comment]
I don't really know what is going wrong with the CMD on you system. 😥 Does it happen on another computer? Or could you create another Windows user to isolate the problem?

**Comment by gyalamanch** [comment]
reimaged the laptop to fix the issue

**Comment by jiasli** [comment]
@gyalamanch, I am glad to know the issue is fixed. It is very likely to be caused by some other installed software or anti-virus software that corrupts the PowerShell or CMD environment.
