### ISSUE TITLE
az sql server update publicnetworkaccess

### ISSUE THREAD

**Issue by tommyle225** [Azure/azure-cli#19227]
Executing both from DevOps and locally are giving this error.

+ az sql server update --admin-password XXXXXXXXXX --name d ...--enable-public-network true
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: Argume...s/CLI_refstatus:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
ERROR: (ExternalAdministratorPrincipalType) Invalid or missing external administrator principal type. Please select from User, 
Application or Group.
None

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
This is fixed. Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
