### ISSUE TITLE
Elastic GA Cli

### ISSUE THREAD

**Issue by vakuncha** [Azure/azure-cli#19226]
**Resource Provider**

Microsoft.Elastic

**Description of Feature or Work Requested**

https://www.elastic.co/blog/getting-started-with-the-azure-integration-enhancement

**Minimum API Version Required**

2020-07-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/elastic/resource-manager/Microsoft.Elastic/stable/2020-07-01/elastic.json

**Target Date**

27-08-2021

**Comment by yonzhan** [comment]
@jsntcy for awareness
