### ISSUE TITLE
`az sql server update --set` fails when ad-admin principalType is null

### ISSUE THREAD

**Issue by christianfosli** [Azure/azure-cli#19228]
**Describe the bug**

I first add an AzureAD administrator to my SQL server using `az sql server ad-admin create`, or by performing a similar action in the Azure portal. This appears to work fine.

If I then try to update an unrelated field on my SQL server using `az sql server update --set`, then the command will fail with an error that the AzureAD admnistrator is missing principal type.

**Command Name**
`az sql server update`

**Errors:**
```
(ExternalAdministratorPrincipalType) Invalid or missing external administrator principal type.
Please select from User, Application or Group.
```

**To Reproduce**
```bash
# Create a group in azure ad
az ad group create --display-name MyTestGroup1 --mail-nickname MyTestGroup1
adminGroupId=$(az ad group show --group MyTestGroup1 --query 'objectId' -o tsv)

# Create a SQL Server without an ad-admin
az group create -n rg-reproduce-error --location norwayeast

az sql server create \
  -g rg-reproduce-error \
  -n sql-reproduce-error \
  -u sqladmin \
  -p superduperstr0ngpassword1!

# Add an ad-admin
az sql server ad-admin create \
  -g rg-reproduce-error \
  -s sql-reproduce-error \
  -u MyTestGroup1 \
  -i $adminGroupId

# Try to update a field
az sql server update \
  -g rg-reproduce-error \
  -n sql-reproduce-error \
  --set tags.Role=Something
```

**Expected behavior**
A tag "Role=Something" should be added to my SQL Server resource

**Environment summary**
```
Linux-5.13.8-200.fc34.x86_64-x86_64-with-glibc2.33
Python 3.9.6
Installer: RPM

azure-cli 2.27.1

Extensions:
azure-devops 0.18.0
```

**Additional context**

The environment summary is for my local machine. However, the same error appears in an Azure-DevOps hosted agent release pipeline running Ubuntu-20.04. We use the `az sql server update --set PublicNetworkAccess={Enabled/Disabled}` at the start and end of a pipeline to apply database migrations to a SQL Server which is normally only accessible from our VNET.
This pipeline started failing yesterday, 12 august.

I reproduce it with changing tags above because it's simpler not having to set up VNET and private endpoints...

If I look at my sql server I can see that indeed the principal type is missing.
This may indicate that the bug is in the `az sql server ad-admin create` command, or the API it talks to.

```bash
$ az sql server show -n sql-reproduce-error -g rg-reproduce-error --query administrators
{
  "administratorType": "ActiveDirectory",
  "azureAdOnlyAuthentication": null,
  "login": "MyTestGroup1",
  "principalType": null,
  "sid": "{revoked}",
  "tenantId": "{revoked}"
}
```

**Comment by christianfosli** [comment]
I see we were two people reporting the same issue at the same time :sweat_smile: 
Duplicate with #19227
I'll leave this open for now since I think I describe it more thoroughly

**Comment by yonzhan** [comment]
route to service team

**Comment by peddibindu82** [comment]
Hi, I am facing the same issue when using the Azure CLI Task with azure pipelines. Any resolution for this issue ?

**Comment by yonzhan** [comment]
sql service team should look into this

**Comment by YoupHulsebos** [comment]
Hi, I am facing the same issue when using the Azure CLI Task with azure pipelines. Any resolution for this issue ?

**Comment by christianfosli** [comment]
A work-around is to remove the AD-Admin from the SQL server. But then that group/app/person looses access.

**Comment by christianfosli** [comment]
Another work-around is to use an old version of Azure CLI. Version 2.16.0 is known not to have this bug.

Something like this works for me in bash, and could be put into a Bash task in Azure Pipelines

```bash
ARM_CLIENT_ID=<your-client-id>
ARM_SUBSCRIPTION_ID=<your-subscription-id>
ARM_TENANT_ID=<your-tenant-id>
ARM_CLIENT_SECRET=<your-client-secret>
docker run --rm -it mcr.microsoft.com/azure-cli:2.16.0 /bin/bash -c "az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID && az account set -s $ARM_SUBSCRIPTION_ID && az sql server update -n sdir-d-sqlvsrv-core01 -g sdir-d-rg-common --set publicNetworkAccess=Enabled"
```

**Comment by timvandenhof** [comment]
Well there was a massive commit with breaking change in it:
https://github.com/Azure/azure-cli/commit/588910d98f07a885c3d840a548c72fc599a44df1

The SDK is updated and it contains a few changes related to managed identity, and aad admin. Didn't dive into it further, but that would be the commit that might have caused it.

Is there a way we can assist the service team?

**Comment by christianfosli** [comment]
I am no longer able to reproduce this error, so it looks like it has been fixed.
`az sql server show -n sql-reproduce-error -g rg-reproduce-error --query administrators` now correctly shows `"principalType": "Group"` instead of `"principalType": null` for my reproduce steps in the issue description.

Closing.
