### ISSUE TITLE
CLI for VPN Mulit-Link feature

### ISSUE THREAD

**Issue by gsumit10** [Azure/azure-cli#19233]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
Need CLI changes to support Multi-Link feature in VPN Site and VPN Connection resources.
VPN Site resource is for the VPN on premise configuration and VPN Configuration is for connection to the VPN Site from Azure for Hybrid connectivity. We are introducing a new feature to add Multiple Link capabilities to VPN Site. Here user can create multiple Links within the VPN Site and then associate them to VPNConnection with multiple LinkConnections.
In Multilink feature, VPN Site/Connection properties are moved to the Link level so customers can create multiple of them within the same resource. Hence this CLI will need to create 2 parameter sets. One existing resource without link for backward compatibility and the other with Links where all properties except a few will be moved at link level.

**Minimum API Version Required**
2019-06-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/6528
This has been checked in for some time and now we are looking at CLI as well for the same feature as customers are requesting this.

**Target Date**
9/15/2021

Please contact me (sumigup@microsoft.com) for any questions on the swagger PR or Multi Link feature.

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by gsumit10** [comment]
The rest api doc is very old. There have been some additional updates to the link object. Please check the latest VPN Site link and Vpn link connection resources in swagger to incorporate all parameters
