### ISSUE TITLE
Failded to approve key Vault private endpoint  in data factory managed VNet with Azure CLI

### ISSUE THREAD

**Issue by jacktong** [Azure/azure-cli#19246]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Cx got a '_NoneType' object is not subscriptable_' error, when approve key vault endpoint in managed network with the following command. 
id = (az keyvault show -n mykv --query "privateEndpointConnections[0].id")
az keyvault private-endpoint-connection approve --id $id

This problem only happens to _bash for windows_. We confirmed that we _can approve with prompt command and cloudshell_.

I download gitforwindows on the following website and can reproduce this problem.
-----
https://gitforwindows.org/
-----

We followed the document on CLI Command.
----
https://docs.microsoft.com/ja-jp/cli/azure/keyvault/private-endpoint-connection?view=azure-cli-latest#az_keyvault_private_endpoint_connection_approve
----

**To Reproduce**

This problem is reported by my customer. 
I can reproduce it by two steps.
1. installing gib bash (https://gitforwindows.org/)
2. run the approve command above

**Expected behavior**
![none type error](https://user-images.githubusercontent.com/84124861/129686787-2d5b0531-caf1-43ef-97df-451b7583aae2.png)

Key Vault endpoint should be approved by using git bash exactly the same as prompt command.

**Environment summary**

I download gitforwindows on the following website and can reproduce this problem.
version should be 2.32.0.2.
-----
https://gitforwindows.org/
-----

**Additional context**

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
It's because in git bash all string beginning with `/` will be taken as a file path and git bash will auto-complete 'full path' with where git bash locates.

That's to say, `/subscriptions/00000000-XXXX-XXXX-XXXX-000000000000/resourceGroups/...` will be replaced with `C:/Program Files/Git/subscriptions/00000000-XXXX-XXXX-XXXX-000000000000/resourceGroups/...`. So Azure CLI can't identify such `private endpoint id`.

Better to use powershell or windows terminal in Windows😊

**Comment by jacktong** [comment]
Thank you for your investigation. for sure it is not a problem on Azure CLI, but kind of a problem on bashforwindow, will issue a new ticket on bashforwindow.
