### ISSUE TITLE
az aks get-credentials writes success message as a warning to stderr

### ISSUE THREAD

**Issue by blackbaud-james-williams** [Azure/azure-cli#19248]
**Describe the bug**
`az aks get-credentials` writes a message ("Merged "{}" as current context in {}") when it has succeeded. In the past, this message was written to stdout. 

A [recent change to src/azure-cli/azure/cli/command_modules/acs/custom.py](https://github.com/Azure/azure-cli/pull/18031/files#diff-f1fc443c5eb2ddee110be5f06110930285573e1debf2640ab83dead88943a9a5) changed this message from a print command to a logger.warning command. 

This has the effect of moving the message from stdout to stderr. 

Many CI/CD pipelines are configured to fail the pipeline if there is output on stderr, so this breaks any steps attempting to configure AKS credentials in a pipeline step. 

**To Reproduce**
Run 
```
az aks get-credentials -g $RESOURCEGROUP -n $CLUSTER --admin --sub $SUB
```

and note output. 

To validate that this output is on stderr, run 

```
az aks get-credentials -g $RESOURCEGROUP -n $CLUSTER --admin --sub $SUB 2>\dev\null
```

And observe that no output was written since stderr was redirected to /dev/null

**Expected behavior**
Any non-error output is written to stdout

**Environment summary**

It looks like the latest version of the azure-cli is being rolled out in Azure DevOps Hosted Agents. But I was also able to reproduced locally. 

```
macOS-11.5.2-x86_64-i386-64bit
Python 3.9.6
Installer: HOMEBREW

azure-cli 2.27.1

Extensions:
front-door 1.0.14
resource-graph 2.1.0
log-analytics 0.2.2

```

**Additional context**
It looks like that was introduced in f7e088f474d18c10d1ed6b116c49a34b12ba2a7c

This change is present in 2.27.1 but not in 2.27.0

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@blackbaud-james-williams Apologies for the late reply. Could you please let me know if you are still facing the issue ? Awaiting your reply.

**Comment by blackbaud-james-williams** [comment]
@navba-MSFT Yes, I can still reproduce this on 2.33.1 via the steps in the issue. Non-error messages are being written to stderr. 

We worked around this problem in August (by updating our release pipeline to not treat stderr output as an error when running this command) so it's not really a problem for us any longer, though the behavior still seems wrong to me.

**Comment by navba-MSFT** [comment]
@blackbaud-james-williams Thanks for getting back. Please refer these threads for the similar issue and for the workaround Azure/azure-cli#19314 and Azure/azure-cli#19315. Hope this helps.
