### ISSUE TITLE
Wrong output for az vm run-command invoke command

### ISSUE THREAD

**Issue by VikasPullagura-MSFT** [Azure/azure-cli#19251]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Wrong output for `az vm run-command` invoke command 

**To Reproduce**
Below telnet ip and port is wrong but out shows as provisioning succeeded. Ideally it should fail.

VM : Windows

MYID@Azure:~$ az vm run-command invoke -g MYRG -n MYVM --command-id 'RunPowerShellScript' --scripts 'telnet 10.0.4.9 8080'
{
"value": [
{
"code": "ComponentStatus/StdOut/succeeded",
"displayStatus": "Provisioning succeeded",
"level": "Info",
"message": "",
"time": null
},
{
"code": "ComponentStatus/StdErr/succeeded",
"displayStatus": "Provisioning succeeded",
"level": "Info",
"message": "",
"time": null
}
]

**Expected behavior**
Output of the command should be failed not succeeded.

**Environment summary**
Based on this [document](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/run-command), one of the CX reported the issue.

**Additional context**
https://github.com/MicrosoftDocs/azure-docs/issues/79781

Opening issue on behalf of @praveenambati1233 as this is not a document bug as reported above.

**Comment by yonzhan** [comment]
Compute

**Comment by praveenambati1233** [comment]
Is there any update?

**Comment by PARADISSEEKR** [comment]
Hi @VikasPullagura-MSFT, could you provide some debug information with `--debug`?

**Comment by VikasPullagura-MSFT** [comment]
@praveenambati1233 Can you please share the requested debug info for further investigation.

**Comment by yonzhan** [comment]
@praveenambati1233 any update?

**Comment by zhoxing-ms** [comment]
Since this issue hasn't been replied for a long time, I'll close it first. If this issue needs us to continue troubleshooting, we will reopen it
