### ISSUE TITLE
"'NoneType' object is not iterable" on several commands from "az storage account "

### ISSUE THREAD

**Issue by Remi-Faydide** [Azure/azure-cli#19253]
## Describe the bug

**Command Name**

- `az storage account list`
- `az storage account list --help`
- `az storage account management-policy show --resource-group {resource-group-name} --account-name {storage-account-name}`
- `az storage account management-policy show --help`

**Errors:**

```shell
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\core\commands\__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\core\__init__.py", line 518, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\command_modules\storage\__init__.py", line 30, in load_arguments
    load_arguments(self, command)
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\command_modules\storage\_params.py", line 603, in load_arguments
    get_permission_help_string(t_account_permissions)),
  File "C:\Users\{username}\AppData\Roaming\Python\Python39\site-packages\azure\cli\command_modules\storage\_validators.py", line 765, in get_permission_help_string
    return ' '.join(['({}){}'.format(x[0], x[1:]) for x in allowed_values])
TypeError: 'NoneType' object is not iterable

```

## To Reproduce:
Steps to reproduce the behavior.

here are the commands where I've faced this issue

- `az storage account list -g {} -o {}`
- `az storage account management-policy show --resource-group {resource-group-name} --account-name {storage-account-name}`

even with some help commands:

- `az storage account list --help`
- `az storage account management-policy show  --help`

however, these commands works

- `az storage account --help`
- `az storage account management-policy --help`

## Expected Behavior

either:

- give the help for the commands
- give the output of the commands

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.9.5
Installer: PIP

azure-cli 2.27.1

Extensions:
account 0.2.1
ad 0.1.0
aks-preview 0.5.9
azure-devops 0.18.0
portal 0.1.1
ssh 0.1.4
subscription 0.1.4
```

## Additional Context

- pwsh `7.1.4`

**Comment by yonzhan** [comment]
Storage

**Comment by jmcshane** [comment]
I'm experiencing the same issue here trying to copy on linux with 2.27.1, but i don't get this on my local Mac OS machine. I have a matching stack trace to the issue here.

**Comment by jmcshane** [comment]
it looks like this comes back to this line not returning an SDK version:
```
        t_file_system_permissions = self.get_sdk('_models#FileSystemSasPermissions',
                                                 resource_type=ResourceType.DATA_STORAGE_FILEDATALAKE)
```

https://github.com/Azure/azure-cli/blob/7b8920fa3e2caa5dbe867a82dcc8b263492777b2/src/azure-cli/azure/cli/command_modules/storage/_params.py#L1701

**Comment by evelyn-ys** [comment]
That should be env problems. Please make sure you have `azure-multiapi-storage~=0.6.2` installed in your dependency which is used by CLI 2.27.1.
