### ISSUE TITLE
Question - Missing 'Key-value' argument support in servicebus namespace keys renew command

### ISSUE THREAD

**Issue by prongcs** [Azure/azure-cli#19252]
Hi All,

Was there a recent change to remove 'key-value' argument support in ServiceBus Namespace Keys rotation? However, the ServiceBus Topic and Queue keys rotation does support 'key-value' argument.

I noticed this behavior as some of our automations to renew ServicBus Namespace keys started failing. 

Here are the azure docs for reference:
https://docs.microsoft.com/en-us/cli/azure/servicebus/namespace/authorization-rule/keys?view=azure-cli-latest#az_servicebus_namespace_authorization_rule_keys_renew

https://docs.microsoft.com/en-us/cli/azure/servicebus/queue/authorization-rule/keys?view=azure-cli-latest#az_servicebus_queue_authorization_rule_keys_renew

https://docs.microsoft.com/en-us/cli/azure/servicebus/topic/authorization-rule/keys?view=azure-cli-latest#az_servicebus_topic_authorization_rule_keys_renew

Thank you.

**Comment by yonzhan** [comment]
route to service team

**Comment by Saglodha** [comment]
Hi @prongcs , thank you for reaching out to us. 

I was reviewing the API structure for regeneration for namespace authorization rule and could understand that the key value (if not provided) would be autogenerated based on key Type that you specify. 

Link: https://docs.microsoft.com/en-us/rest/api/servicebus/stable/namespaces-authorization-rules/regenerate-keys

I would like to understand if there is any additional functionality that explicit declaration of --key-value is serving for you with this setup. This would help us in understanding if there were additional use cases that we can look at.
