### ISSUE TITLE
Changes in swagger description leads to failing az apim api import command

### ISSUE THREAD

**Issue by abragsta** [Azure/azure-cli#19277]
**Describe the bug**

I'm trying to import an API Definition into API Management using the following command:

`az apim api import --resource-group $(ApimResourceGroup) --service-name $(ApimName) --specification-format OpenApiJson --api-revision $(Revision) --api-version v1 --api-id $(ApimApiId) --api-version-set-id $(ApimApiId) --specification-url $(ApiSpecificationUrl) --service-url $(ApiUrl) --path $(ApimPath) --subscription-required false --description '$(ApiDisplayName)'`

This works great the first time, but on subsequent attempts we get the error:

`Can't change property Description for non-current revision`

The reason for this error seems to be that this commands uses the Swagger description field.
Which in our case changes for every release, and using this command does not let us do that.
It is also not possible to override the Description field using the --description parameter.

**Expected behavior**

You should be able to override Description when given as an argument in order not to generate this error. 
Imho. you should also be able to change description between imports without generating an error.

As it stands we are unable to deploy new versions of the API when we have changed description of the API in swagger.

**Environment summary**

The script is run as part of an Azure CLI task in Azure DevOps release pipeline, using Azure CLI version 2.27.1.

**Comment by yonzhan** [comment]
route to service team

**Comment by owingruters** [comment]
Same issue. Is there a workapround (except deleting / recreating)

**Comment by navba-MSFT** [comment]
@abragsta @owingruters Apologies for the late reply. We are looking into this issue. We will provide an update once we have more details on this.

@adrianhall Could you please look into this ask once you get a chance ? Awaiting your reply.

**Comment by adrianhall** [comment]
This is "by design".  There are several fields in the OpenAPI specification that cannot be updated unless you are changing the current API revision.  For details, please see https://docs.microsoft.com/en-us/azure/api-management/edit-api#update-the-swagger

#please-close
