### ISSUE TITLE
Add to each 'File system name' Reference in the page a note that says use your container name

### ISSUE THREAD

**Issue by AndresPad** [Azure/azure-cli#19279]
Could we please add a note everywhere we see _'File system name.'_ that says the following:

File system name (i.e. container name).

I see that a number of customers have had issues getting back ACLs and they are confused about what the File System Name is.

It would be great to add some clarification as to what the File System Name is.

Thanks
-Andres

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d802bfb-9b2e-23b5-6d29-ef5265bca892
* Version Independent ID: 05ca9f9f-7473-0ed4-7867-cf6ae5703a25
* Content: [az storage fs access](https://docs.microsoft.com/en-us/cli/azure/storage/fs/access?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/fs/access.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/fs/access.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Storage
