### ISSUE TITLE
Azure kubernetes service in "show more" returns 404.

### ISSUE THREAD

**Issue by carsv** [Azure/azure-cli#19299]
[Enter feedback here]

title selfexplanatory.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90848717-3ba9-0895-98ad-95b8a8a48a2f
* Version Independent ID: 2226b763-42c7-5c6b-7d32-ad76b1b43dc8
* Content: [az acr token](https://docs.microsoft.com/en-us/cli/azure/acr/token?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/acr/token.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/acr/token.yml)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by Wwwsylvia** [comment]
Hi @carsv, Thanks for the feedback! But we are not sure where this issue came from. Could you elaborate a bit? Could you share a screenshot?
Thank you!

**Comment by carsv** [comment]
go to https://docs.microsoft.com/en-us/cli/azure/acr/token?view=azure-cli-latest
Search "show more"
Press "show more"
press "Azure Kubernetes Service"
result: 404

**Comment by Wwwsylvia** [comment]
This is auto-generated. @yonzhan Could you suggest on how can we fix the link in "Recommended Content"?

**Comment by zhoxing-ms** [comment]
This should be a issue related to the document team.  @dbradish-microsoft Please help to take a look

**Comment by navba-MSFT** [comment]
@carsv Apologies for the late reply. I wasn't able to reproduce the issue related to 404. Could you please let me know if you need any assistance on this ? Awaiting your reply.
