### ISSUE TITLE
DesktopVirtualization hostPool  Name max length wrong value

### ISSUE THREAD

**Issue by agm83** [Azure/azure-cli#19298]
If a host pool name exceeds 24 characters I will not be able to use it in any command that specifies this name. This was working in the previous version of the CLI, at  minimum the one available a month ago. 

**To Reproduce**
1. create a host pool with a name longer than 24 characters using the Portal or Azure Powershell (obviously not cli at this point)
2. try to perform any operation in that hostPool from az cli, such as:
_az DesktopVirtualization hostPool show -g $resourceGroupName -n $over24CharactersHostPoolName_
3. you will receive the ERROR: Parameter 'host_pool_name' must have length less than 24

![image](https://user-images.githubusercontent.com/83845280/130294681-7ecaec93-b4a9-482e-b5fa-1e15df892ea5.png)
![image](https://user-images.githubusercontent.com/83845280/130294704-d3a0934b-52db-4a7e-bbed-58d28ff280bc.png)

**Expected behavior**
when using Portal, ARM, azure PowerShell you can create a host Pool with a name as long as 64 characters long, I would expect consistency. I have host Pools that are 27 characters long. Here you can see the maximum length for the name in the portal:
![image](https://user-images.githubusercontent.com/83845280/130294622-13998e4e-aa8a-463c-a093-9518c2444fb0.png)

**Environment summary**
PS C:\> az -v
azure-cli                         2.27.1
core                              2.27.1
telemetry                          1.0.6

Extensions:
desktopvirtualization               0.1.1

**Comment by yonzhan** [comment]
route to service team

**Comment by jsntcy** [comment]
CLI need upgrade API version from [2019-12-10-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/preview/2019-12-10-preview/desktopvirtualization.json#L2957) (max_length: 24) to [2021-07-12](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/stable/2021-07-12/desktopvirtualization.json#L4757) (max_length: 64).

**Comment by agm83** [comment]
Hello, this is still not fixed... any ETA?

**Comment by jsntcy** [comment]
Will fix and release on 4/5.
