### ISSUE TITLE
az upgrade

### ISSUE THREAD

**Issue by robmaynardjr** [Azure/azure-cli#19300]
## Describe the bug

**Command Name**
`az network`

**Errors:**
```
'create' is misspelled or not recognized by the system.

psutil.AccessDenied (pid=3408)
Traceback (most recent call last):
Lib\site-packages\psutil\_common.py, ln 447, in wrapper
AttributeError: _cache

...

Lib\site-packages\psutil\_pswindows.py, ln 750, in name
Lib\site-packages\psutil\_pswindows.py, ln 681, in wrapper
psutil.AccessDenied: psutil.AccessDenied (pid=3408)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network {} --name {} -g {} --address-prefix {} --subnet-name {} --subnet-prefix {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: 

azure-cli 2.22.0 *

Extensions:
aks-preview 0.5.14
quantum 0.3.0

```

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
@robmaynardjr If you mean to create the `vnet`, you should use `az network vnet create` command.

BTW You can always add `--help` to see the help message of any commands. For example `az network vnet --help`

**Comment by jiasli** [comment]
You are using a very old version 2.22.0 of Azure CLI that doesn't include the full call stack in `az feedback` result (https://github.com/Azure/azure-cli/pull/17353). Could you share the full call stack?

For `psutil.AccessDenied`, it is very likely to be caused by https://github.com/Azure/azure-cli/issues/19193. We will workaround it with https://github.com/Azure/azure-cli/pull/19244.

**Comment by jiasli** [comment]
@kot0dama, I fail to understand the relationship between your problem and the `psutil.AccessDenied` error. If you have any problem with extension dynamic install, please create a new issue with detailed description. Thanks.

**Comment by kot0dama** [comment]
It has the exact same error message, complaining about a command that the user did not run themselves (so I suppose it's an internal step) and this page is the most relevant result when looking for it. I figured it was not a problem to let other users quick check if that was not a limited internet access issue.

I did not open an issue as I couldn't reliably reproduce.
