### ISSUE TITLE
Please enable VM disk export via the az CLI

### ISSUE THREAD

**Issue by blochl** [Azure/azure-cli#19306]
**Is your feature request related to a problem? Please describe.**
I want to automate the image generation process, in order to include it in a CI pipeline. The only link which is missing for a fully automated process, is VM disk export - basically, the process which is described [here](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/download-vhd#generate-sas-url). I found no way to do it _via_ the `az` CLI, nor _via_ a simple REST API.

**Describe the solution you'd like**
Ideally, I would be able to do the following _via_ the `az` CLI:
1. Set a duration for OS image export for a deallocated VM.
2. Get the SAS URL for this image.
3. Cancel the export once the download is done, to be able to delete the VM.

**Describe alternatives you've considered**
It would also be okay if there was a REST API way to perform the steps above.

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@blochl  Since we have several important requirements to do in the near future, so we plan to make the development of this requirement to the sprint in October (it will be released in **11-02**). Do you think the release time is acceptable?

**Comment by blochl** [comment]
@zhoxing-ms , Thanks for your response!
Yes, **11-02** release is certainly acceptable.
But in the meantime, can you suggest a workaround for this functionality?

**Comment by zhoxing-ms** [comment]
@blochl Hi, we can have two work arounds:
1. Use the command `az rest` to request the REST API directly.
2. After the code development is basically completed, we can provide you with private packages for testing in advance through edge build. The doc for edge build: [try_new_features_before_release](https://github.com/Azure/azure-cli/blob/dev/doc/try_new_features_before_release.md)

**Comment by blochl** [comment]
@zhoxing-ms ,

> Use the command `az rest` to request the REST API directly.

Do you know where the REST API commands for this functionality are documented?

> After the code development is basically completed, we can provide you with private packages for testing in advance through edge build.

Thanks very much, I'd like that.

**Comment by blochl** [comment]
Sorry, I have found a way to do it.

For future reference:
1. Get the OSDisk name:
    ```sh
    az disk list |
        jq -r '.[] | select(.diskState == "Reserved") | .name' |
        grep "<VM name>_OsDisk_1"
    ```
    * Several names may appear. If unsure, to find the correct one go to the web UI (**Virtual Machines** → **[VM name]** → **Disks** → **OS Disk**) and check the correct name.
1. Get the export URL:
    ```sh
    az disk grant-access --duration-in-seconds <number of seconds to export> \
        -g "<resource group>" -n "<OSDisk name>" |
        jq -r '.accessSas'
    ```
1. Download the image.
1. Revoke access, to enable VM / disk deletion:
    ```sh
    az disk revoke-access -g "<resource group>" -n "<OSDisk name>"
    ```

Closing this issue.
