### ISSUE TITLE
Az CLI support for BgpConnection in VirtualHub

### ISSUE THREAD

**Issue by AndriiKalinichenko** [Azure/azure-cli#19316]
**Resource Provider**

NRP (Microsoft.Network)

**Description of Feature or Work Requested**

We are adding support for a new child resource HubBgpConnection of parent VirtualHub. HubBgpConnection (or just BgpConnection) has following properties:
- PeerIp (IP address of the BGP peer)
- PeerAsn (ASN of the BGP peer)
- VirtualHubVnetConnection (VirtualHubVnetConnection references by the BgpConnection)

For this resource we would need following CLI commands:
- az network vhub bgpconnection create
- az network vhub bgpconnection update
- az network vhub bgpconnection delete
- az network vhub bgpconnection get/show
- az network vhub bgpconnection list

Design doc: [BGP Endpoint in Virtual Hub](https://microsoft.sharepoint.com/:w:/r/teams/Aznet/_layouts/15/Doc.aspx?sourcedoc=%7BE49FBF0C-A70D-4EE0-B9B0-FA88EE6D9A6B%7D&file=BGP%20endpoint%20in%20managed%20VHub.docx&action=default&mobileredirect=true&share=IQEMv5_kDafgTrmw-ojubZprAQITAD3vZTMX86-Bgl1YQY8), most useful section is "JSON resource samples".

There are CLI commands for Route Server which are very similar (except for VirtualHubVnetConnection reference): https://docs.microsoft.com/en-us/cli/azure/network/routeserver/peering?view=azure-cli-latest

**Minimum API Version Required**

02-01-2021

**Swagger Link**

Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/14800

VirtualWan resource: https://github.com/Azure/azure-rest-api-specs/blob/network-march-branch/specification/network/resource-manager/Microsoft.Network/stable/2021-03-01/virtualWan.json#L5877

**Target Date**

9/30/2021

**Comment by yonzhan** [comment]
network
