### ISSUE TITLE
As of 2.27.1 `az aks get-credentials` emits output to stderr

### ISSUE THREAD

**Issue by craigktreasure** [Azure/azure-cli#19315]
### `az aks get-credentials` emits output to stderr, as of CLI version 2.27.1. This was not the case in 2.27.0.

**Describe the bug**

We run `az aks get-credentials` in our build pipeline. In 2.27.0, it emitted `Merged "<omitted>" as current context in /home/cloudtest/.kube/config` to stdout. As of 2.27.1, it emits `WARNING: Merged "<omitted>" as current context in /home/cloudtest/.kube/config` to stderr and the build pipeline began failing when the image was updated due to the command writing to the error stream.

**To Reproduce**

Run the following in 2.27.0:
`az aks get-credentials --resource-group '$(ResourceGroupName)' --name '$(ClusterName)'`

which will result in the following being written to stdout:
```
Merged "<omitted>" as current context in /home/cloudtest/.kube/config
```

Run the following in 2.27.1:
`az aks get-credentials --resource-group '$(ResourceGroupName)' --name '$(ClusterName)'`

which will result in the following being written to stderr:
```
WARNING: Merged "<omitted>" as current context in /home/cloudtest/.kube/config
```

**Expected behavior**

I don't know if there's any commitment to making breaking changes in major or minor versions, but this wasn't mentioned in the [release notes](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#august-17-2021).

**Environment summary**

Behavior reproduced on both Linux and Windows.

**Comment by yonzhan** [comment]
route to service team

**Comment by Dirc** [comment]
I'm experiencing the same issue

**Comment by Woody88** [comment]
We are experiencing the same issue here.

**Comment by miwithro** [comment]
@weinong can you address this one?

**Comment by 304NotModified** [comment]
Quick work arround:

> 
> You may disable all WARNING messages with 
> 
> ```sh
> # This command itself shows a warning which should be disabled
> az config set core.only_show_errors=true --only-show-errors
> ```
> 
 _Originally posted by @jiasli in https://github.com/Azure/azure-cli/issues/19314#issuecomment-919670087_

**Comment by jiasli** [comment]
The topic of using `failOnStdErr` is tracked by https://github.com/Azure/azure-cli/issues/18372.
