### ISSUE TITLE
`az aks get-credentials` writes to stderr on successful acquisition starting in 2.27.1

### ISSUE THREAD

**Issue by jander-msft** [Azure/azure-cli#19314]
**Describe the bug**
`az aks get-credentials` writes to stderr when merging kubernetes context into file starting in Azure CLI version 2.27.1

**To Reproduce**
```
az aks get-credentials --subscription ***** --resource-group ***** --name ***** --file 'test.kubeconfig' --admin 1> 'test.kubeconfig.stdout' 2> 'test.kubeconfig.stderr'
```

The test.kubeconfig.stdout file is empty but the test.kubeconfig.stderr file contains `WARNING: Merged "*****" as current context in *****\test.kubeconfig`. The test.kubeconfig file did not exist before executing the `get-credentials` command.

**Expected behavior**
The command should not write to stderr when no issue occurs. This message used to be written to stdout (`Merged "*****" as current context in *****\test.kubeconfig`) instead of stderr in 2.27.0 and prior.

**Environment summary**
Install method: MSI
CLI Version: 2.27.2
OS Version: Windows 10
Shell Type: pwsh.exe on Windows

**Additional context**
This started to cause Azure DevOps deployments to fail on August 18th because our tasks by default fail when stderr lines are detected. Tested that this issue reproduces in both Azure DevOps Azure CLI Task 2.1.1 as well as on a local machine.

**Comment by yonzhan** [comment]
route to service team

**Comment by jiasli** [comment]
According to https://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html

> Variable: FILE * stderr
> The standard error stream, which is used for error messages and diagnostics issued by the program.

Therefore, `stderr` is the right place for Azure CLI to write WARNING messages.

If the pipeline has `failOnStderr` set to true and the WARNING message is causing failure, you may either

1. In the pipeline, set `failOnStderr` to false 
2. Disable WARNING messages in Azure CLI commands using the [`only_show_errors`](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-values-and-environment-variables ) configuration.

**Comment by jander-msft** [comment]
I would contend that:
1. This is a breaking change. A behavioral change was made (writing out additional messages that were not written in prior same major release) that caused this issue to occur. Without any changes to our pipeline, it started to fail because of the change between 2.27.0 and 2.27.1
2. The usage of the command as described does not request to write out diagnostic information, thus it should not write diagnostic information. Thus, the `diagnostics issued by the program` portion of the explanation is not acceptable. What remains is `which is used for error messages`; the message is not not an error. Since it does not meet either explanation, it should not be written to stderr under these conditions.
3. The CLI should not be writing this warning message under the explained conditions. `Merged "*****" as current context in *****\test.kubeconfig` should only reasonably be a written when credentials were actually merged into an existing file, not when writing into a new file. This warning is being written out when the file doesn't exist in the first place.

I've already mitigated this issue by using `--only-show-errors`. I will not set `failOnStderr: false` so that we can catch other actual errors when they occur.

**Comment by jiasli** [comment]
@jander-msft, as for whether `az aks get-credentials` should print a WARNING message, I will leave it to @andyliuliming to decide. 

I still would like mention that there are other CLI commands that will print WARNING messages to `stderr`, such as `az ad sp create-for-rbac` which even prints several WARNING messages:

```
> az ad sp create-for-rbac > out.txt
WARNING: In a future release, this command will NOT create a 'Contributor' role assignment by default. If needed, use the --role argument to explicitly create a role assignment.
WARNING: Creating 'Contributor' role assignment under scope '/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590'
WARNING: The output includes credentials that you must protect. Be sure that you do not include these credentials in your code or check the credentials into your source control. For more information, see https://aka.ms/azadsp-cli
WARNING: 'name' property in the output is deprecated and will be removed in the future. Use 'appId' instead.
```

With `failOnStderr: true` but no `--only-show-errors`, `az ad sp create-for-rbac` will cause the pipeline to fail for sure. Correct way is to determine whether a command successful is to check the exit code (https://github.com/Azure/azure-cli/issues/18372#issuecomment-918741485).

You may disable all WARNING messages with 

```sh
# This command itself shows a warning which should be disabled
az config set core.only_show_errors=true --only-show-errors
```

**Comment by navba-MSFT** [comment]
@jander-msft I hope you had a chance to look at the pointers suggested by @jiasli. I see that this github issue has been open for quite sometime now. I just wanted to do a follow-up to check if you still require assistance on this. Awaiting your reply.

**Comment by jander-msft** [comment]
I've already mitigated this as stated in https://github.com/Azure/azure-cli/issues/19314#issuecomment-919558448

```
I've already mitigated this issue by using --only-show-errors. I will not set failOnStderr: false so that we can catch other actual errors when they occur.
```

**Comment by navba-MSFT** [comment]
@jander-msft Thanks for your reply. If you need any further assistance on this, please reopen this thread. We would be happy to help you.
