### ISSUE TITLE
az storage remove ignores (BlobEndpoint part of) connection string

### ISSUE THREAD

**Issue by roelarents** [Azure/azure-cli#19311]
**Describe the bug**
`az storage remove` ignores (part of) connection string

**To Reproduce**
* run Azurite with default settings. maybe add `--debug /dev/stdout`
* `export AZURE_STORAGE_CONNECTION_STRING='AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1;DefaultEndpointsProtocol=http;'`  
  ^^ which is the default connection string for azurite
* run `az storage remove --name myblob --container-name mycontainer`
* try again with `az storage remove --name myblob --container-name mycontainer --connection-string="$AZURE_STORAGE_CONNECTION_STRING"`
* endure the error message:
```
failed to perform remove command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20201022074806-8d8fc11be726/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:c640c83d-001e-006c-3e34-989d05000000
Time:2021-08-23T15:36:41.6376634Z, Details:
   AuthenticationErrorDetail: Signature did not match. String to sign used was devstoreaccount1
rdl
b
co

2021-08-24T15:36:41Z


2018-03-28

   Code: AuthenticationFailed
   GET https://devstoreaccount1.blob.core.windows.net/mycontainer?comp=list&delimiter=%2F&include=metadata&prefix=myblob%2F&restype=container&se=2021-08-24t15%3A36%3A41z&sig=-REDACTED-&sp=rdl&srt=co&ss=b&sv=2018-03-28&timeout=901
   User-Agent: [AzCopy/10.8.0 Azure-Storage/0.10 (go1.13; linux)]
   X-Ms-Client-Request-Id: [83e8c3df-a103-4dbd-6fbb-a8732b3f21a0]
   X-Ms-Version: [2019-12-12]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [485]
   Content-Type: [application/xml]
   Date: [Mon, 23 Aug 2021 15:36:40 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [c640c83d-001e-006c-3e34-989d05000000]


.
```
* see in the error message that an attempt was made to authorize with `devstoreaccount1.blob.core.windows.net` instead of localhost. With accountname `devstoreaccount1` though. But `BlobEndpoint` seems ignored.

**Expected behavior**
* The specified blob is removed from the local azurite blob storage.

**Environment summary**
Ubuntu 20.04 in WSL2
Azurite 3.14
az-cli 2.27.1

**Additional context**
Even if it worked, probably the bug in `azcopy` with removing from local storage (azurite) would be encountered:
https://github.com/Azure/azure-storage-azcopy/issues/713

**Comment by yonzhan** [comment]
storage

**Comment by roelarents** [comment]
Support for a connection-string (which apparently is optional) has been added for a similar command, `az storage blob sync` in #13135. It looks like the connection string should be passed [here](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_validators.py#L1665). Plus the `--from-to BlobTrash` arg probably has to be added to the `azcopy rm` command, as read in the solution for [#713](https://github.com/Azure/azure-storage-azcopy/issues/713#issuecomment-911258979)
