### ISSUE TITLE
"Failed to connect to MSI. Please make sure MSI is configured correctly."

### ISSUE THREAD

**Issue by yooakim** [Azure/azure-cli#19328]
## Describe the bug

**Command Name**
`az ad group list`

**Errors:**
```
A Cloud Shell credential problem occurred. When you report the issue with the error below, please mention the hostname 'cc-7c0a29b3-688979ccdc-8h8hk'

Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned: <Response [400]>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Open Azure Shell from Windows terminal
- `az ad group list`

## Expected Behavior

I expect to get a list of groups in our Azure AD

## Environment Summary
```
Linux-5.4.0-1056-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.27.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This is a known issue of Azure Cloud Shell (https://github.com/Azure/azure-cli/issues/11749). Please see the workaround at https://github.com/Azure/azure-cli/issues/11749#issuecomment-570975762.
