### ISSUE TITLE
Support PrivateEndpoint for NSG and ASG

### ISSUE THREAD

**Issue by jamesc** [Azure/azure-cli#19330]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
NSG - network sec groups and app sec groups - create policies on subnet and resource level to deny traffic coming to private link - adding support for this - leveraging property PrivateEndpointNetworkPolicies

**Minimum API Version Required**
2021-03-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/14620
https://github.com/Azure/azure-rest-api-specs/pull/14662

**Target Date**
Pub Preview: End August, GA: End Sept/Start Oct.

**Comment by yonzhan** [comment]
@kairu-ms for awareness
