### ISSUE TITLE
az acr task logs failed since 2.26.0

### ISSUE THREAD

**Issue by huanwu** [Azure/azure-cli#19332]
It is a regression issue from 2.26.0. 

repro step:
az acr task logs --registry $registryname

Expected:  Got the log of the latest run

Actual: Got the following error 
Could not find the latest created run. 

With -debug, we can see the error
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/task.py", line 994, in acr_task_logs
    run_id = paged_runs.get(0)[0].run_id
AttributeError: 'ItemPaged' object has no attribute 'get'

**Comment by yonzhan** [comment]
route to service team
