### ISSUE TITLE
--service-endpoint-configuration is a required parameter, but there is no description given on how to create the json file

### ISSUE THREAD

**Issue by cvdabbeele** [Azure/azure-cli#19340]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd63c4b-37f7-3641-8f15-0f5713ab71b4
* Version Independent ID: 39006efa-983d-d605-ca4f-95ffd91fbec4
* Content: [az devops service-endpoint](https://docs.microsoft.com/en-us/cli/azure/devops/service-endpoint?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/devops/service-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/devops/service-endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
@cvdabbeele Apologies for the delayed response. Let us know if this helps in addressing the concern. https://docs.microsoft.com/en-us/azure/devops/cli/service-endpoint?view=azure-devops#create-service-endpoint-using-a-configuration-file and this is also updated in the document https://docs.microsoft.com/en-us/cli/azure/devops/service-endpoint?view=azure-cli-latest#az-devops-service-endpoint-create

**Comment by cvdabbeele** [comment]
Thank you for your efforts, 
I'm sure it will be beneficial to other Azure customers
Thank you for your deadline of 7 days.  You realize this question was asked 7 months ago, right?
anyway, I appreciate the efforts
chris
