### ISSUE TITLE
Please provide the JSON examples for --service-endpoint-configuration for deploying to KUBERNETES

### ISSUE THREAD

**Issue by cvdabbeele** [Azure/azure-cli#19341]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd63c4b-37f7-3641-8f15-0f5713ab71b4
* Version Independent ID: 39006efa-983d-d605-ca4f-95ffd91fbec4
* Content: [az devops service-endpoint](https://docs.microsoft.com/en-us/cli/azure/devops/service-endpoint?view=azure-cli-latest#az_devops_service_endpoint_update)
* Content Source: [latest/docs-ref-autogen/devops/service-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/devops/service-endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by cvdabbeele** [comment]
we are a few months later
any info on this @narula0781, @ashishonce, @romil07  ?

**Comment by cvdabbeele** [comment]
any info on this @narula0781, @ashishonce, @romil07 please ?

**Comment by cvdabbeele** [comment]
Please provide the JSON examples for --service-endpoint-configuration for deploying to KUBERNETES

**Comment by cvdabbeele** [comment]
It is my understanding that to allow a pipeline to deploy an image to an AKS cluster, it requires a ServiceConnection of type "kubernetes"
It is my understanding that such a serviceconnection can be created using the following command:
`az devops service-endpoint create --service-endpoint-configuration service-endpoint-kubernetes.json --organization "https://dev.azure.com/${AZURE_ORGANIZATION}" --project "${C1PROJECT}" `
I have been unsuccessful to find a template for this: service-endpoint-kubernetes.json
Can you please provide an example?
thank you

**Comment by survivant** [comment]
There is a way to create kubernetes service connection from CLI ?  Really hard to find Azure CLI documentation about that.

**Comment by survivant** [comment]
I added a new issue with a payload example here https://github.com/Azure/azure-cli-extensions/issues/5385

**Comment by RakeshMohanMSFT** [comment]
Hope the example provided above helped. If not, please reopen this issue
