### ISSUE TITLE
Typo Kuberntes

### ISSUE THREAD

**Issue by madiepev** [Azure/azure-cli#19343]
In the details for the --type when creating a compute it says: The type of compute target. Required if --file/-f is not provided. Allowed values: AmlCompute, ComputeInstance, Kuberntes.
**Kuberntes** seems to be a typo. Should be **Kubernetes**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71c25404-a256-62b2-3ac8-dd699fc677ba
* Version Independent ID: 5f3dccba-b2ee-224b-9e84-80ba2bbde641
* Content: [az ml compute](https://docs.microsoft.com/en-us/cli/azure/ml/compute?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/compute.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/compute.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by paulshealy1** [comment]
Thank you for the feedback! We're addressing this now, and it will be fixed in the next release.

**Comment by nishankgu** [comment]
thanks Paul!

**Comment by RakeshMohanMSFT** [comment]
@nishankgu This issue is fixed
