### ISSUE TITLE
missing space between **--resource-group "SampleResourceGroup"**   and  **--vault-name "swaggerExample"** in  sample cli command for az dataprotection backup-vault create

### ISSUE THREAD

**Issue by kumarisarita5** [Azure/azure-cli#19359]
Hi,
In the "try this" cli command for az dataprotection backup-vault create, the space between **--resource-group "SampleResourceGroup"**   and  **--vault-name "swaggerExample"** is missing.
I tried the sample command given, which kept throwing "the following arguments are required: --vault-name". Could you please fix this.
![CLI-bvCreate](https://user-images.githubusercontent.com/37065221/130956939-16c2633e-98ec-4d3e-8a1a-5df0bab7a8eb.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 957b2603-1c71-e6ec-83e2-19c1e553a47b
* Version Independent ID: 3745d12b-b5cf-5ad2-2c6d-b949d343e2e9
* Content: [az dataprotection backup-vault](https://docs.microsoft.com/en-us/cli/azure/dataprotection/backup-vault?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/dataprotection/backup-vault.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/dataprotection/backup-vault.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@kumarisarita5 This seems to have been fixed. Can you please confirm the same?
