### ISSUE TITLE
Auto Delete on Idle

### ISSUE THREAD

**Issue by monojit18** [Azure/azure-cli#19354]
[Enter feedback here]
Documentation says --auto-delete-on-idle as:
_ISO 8601 timeSpan or duration time format for idle interval after which the **topic** is automatically deleted. The minimum duration is 5 minutes_

Shouldn't this be **_subscription_** instead of topic here (_highlighted above_)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52b7d039-d543-895c-3056-2616b21ac86e
* Version Independent ID: 84875b23-e2ef-997a-c819-dafbae87f4e1
* Content: [az servicebus topic subscription](https://docs.microsoft.com/en-us/cli/azure/servicebus/topic/subscription?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/servicebus/topic/subscription.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/servicebus/topic/subscription.yml)
* Service: **service-bus**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by monojit18** [comment]
Any update on this please?

**Comment by yonzhan** [comment]
service bus team should take a look

**Comment by Saglodha** [comment]
Hi @monojit18, thanks for bringing this to our attention. 

We would triage internally on expected behavior and would keep you posted.

**Comment by Saglodha** [comment]
@monojit18 , this has been fixed in our latest release. Please review the updated help and let us know in case of additional concerns. Thanks!
