### ISSUE TITLE
az aks update ignoring core.only_show_errors

### ISSUE THREAD

**Issue by gerhardatball** [Azure/azure-cli#19362]
**Describe the bug**

When `az aks update --attach-acr` is run and completes it seems that the command outputs (see below) to stderr even with `core.only_show_errors=true` set to true.

```
AAD role propagation done[############################################]  100.0000%
```

I think when `_add_role_assignment` in [custom.py](https://github.com/Azure/azure-cli/blob/main/src/azure-cli/azure/cli/command_modules/acs/custom.py) is called from `az aks update --attach-acr` I think a check `cmd.cli_ctx.only_show_errors` is needed to before calling `get_progress_controller(True)`. 

**To Reproduce**

In myResourceGroup create an ACR call myRegistry then create a AKS called myKubernetesService and run the following command.

```
> az config set core.only_show_errors=true --only-show-errors
> az aks update --resource-group myResourceGroup --name myKubernetesService --attach-acr myRegistry
```

stderr
```
AAD role propagation done[############################################]  100.0000%
```

stdout
```
{
  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
    {
```

**Expected behavior**

No spinners or progress bars.

```
> az config set core.only_show_errors=true --only-show-errors
> az aks update --resource-group myResourceGroup --name myKubernetesService --attach-acr myRegistry
{
  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
    {
```

**Environment summary**

```
> az --version
azure-cli                         2.26.0 *

core                              2.26.0 *
telemetry                          1.0.6
...
Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56)
...
```

**Additional context**
I was looking at how to do this in a ARM template but I have yet to find how to do that. So if you know how that can be done would love that!

**Comment by navba-MSFT** [comment]
@gerhardatball Apologies for the late reply. Could you please refer [this](https://github.com/Azure/azure-cli/issues/19365#issuecomment-906909821) comment ? Also do let me know if you need any further assistance on this. Awaiting your reply.
