### ISSUE TITLE
CLI changes for adding new fields (sku and scaleunits) in Azure Bastion creation/update.

### ISSUE THREAD

**Issue by aavalang** [Azure/azure-cli#19375]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
Need CLI changes to support ScaleUnits and Sku selection in Azure Bastion Creation/Update workflow.

**Minimum API Version Required**
2021-03-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/b020247789ba2ab0065ebbcfa69050ce729493b8/specification/network/resource-manager/Microsoft.Network/stable/2021-03-01/bastionHost.json#L671

https://github.com/Azure/azure-rest-api-specs/blob/b020247789ba2ab0065ebbcfa69050ce729493b8/specification/network/resource-manager/Microsoft.Network/stable/2021-03-01/bastionHost.json#L718

**Target Date**
9/30/2021

Please contact Aakash(aavlang@microsoft.com) or Sandeep(sabansal@microsoft.com) for questions on the swagger specs or the new fields addition.

**Comment by kairu-ms** [comment]
Hi @aavalang, we have limited bandwidth to finish your feature request this month. We can work on it next month. Is that OK for you?

**Comment by aavalang** [comment]
@kairu-ms we need this for ignite, will it be on time for that?
