### ISSUE TITLE
"az aks update" commands fail when aks-preview extension is installed and sub does not have AutoUpgradePreview feature registered

### ISSUE THREAD

**Issue by jotavar** [Azure/azure-cli#19385]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
"az aks update" commands fail when aks-preview extension is installed and sub does not have AutoUpgradePreview feature registered, even when update operation is not related with AutoUpgradePreview feature (eg: enabling pod identity addon). Error is the following:

(BadRequest) Feature Microsoft.ContainerService/AutoUpgradePreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features.

**To Reproduce**
1 - Install aks-preview extension
2 - login to a subscription which is not registered to use the AKS AutoUpgradePreview feature 
3 - try to update an AKS cluster with "az aks update...", eg:

az aks update -g $MY_RESOURCE_GROUP -n $MY_CLUSTER --enable-pod-identity

**Expected behavior**
update command should work because this particular update operation is not related with AutoUpgradePreview feature

**Environment summary**
az with aks-preview extension and subscription which is not registered to use the AKS AutoUpgradePreview feature

**Comment by ppraka** [comment]
Same issue reported where no az aks update command is working if aks-preview extension is enabled.

![image](https://user-images.githubusercontent.com/89774551/131314722-c6d63071-0514-424d-a825-4c7750107f8e.png)

**Comment by yonzhan** [comment]
route to service team

**Comment by xhl873** [comment]
should be the same issue as here: https://github.com/Azure/AKS/issues/2515
The "aks-preview" extension version 0.5.29 will have the fix, please try to update cli extension version.

**Comment by ppraka** [comment]
@xhl873 , Updated both Azure CLI to 2.27.2 and aks-preview extension to 0.5.29. It is not working. Same error is reported. Both az aks update command failed. Please see the attached screenshot.

![image](https://user-images.githubusercontent.com/89774551/131459579-75593fca-2779-49fc-806d-f37bff52ed25.png)

**Comment by navba-MSFT** [comment]
@jotavar I was able to run the az aks update command with aks-preview extension installed. I am sending the az cli version details if that helps. Could you please test the behavior and get back to us ? Awaiting you reply.

>PS D:> az version
{
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.51",
    "application-insights": "0.1.14",
    "blueprint": "0.3.1",
    "storage-blob-preview": "0.6.1"
  }
}

**Comment by jotavar** [comment]
@navba-MSFT  unfortunately I no longer have a subscription available where AutoUpgradePreview feature is not registered so I am unable to test this. In any case AutoUpgrade feature is now GA so I believe this registration is no longer required...

**Comment by navba-MSFT** [comment]
@jotavar Thanks for getting back. Since this github thread is open for quite sometime, we will proceed with archival. If you face the same issue in future please do get back to us. We would be happy to reopen this thread and work with you further.
