### ISSUE TITLE
No registered resource provider found for location 'EastUS2' and API version '2021-04-01-preview' for type 'vaults'

### ISSUE THREAD

**Issue by haquemd** [Azure/azure-cli#19389]
**Describe the bug**

When trying to create an Azure Key Vault in the Dogfood environment the request is failing with 
`(NoRegisteredProviderFound) No registered resource provider found for location 'EastUS2' and API version '2021-04-01-preview' for type 'vaults'. The supported api-versions are '2014-12-19-preview, 2015-06-01, 2016-10-01, 2018-02-14-preview, 2018-02-14, 2019-09-01'. The supported locations are 'eastus2, centralus, northcentralus, southcentralus, canadaeast, canadacentral'.`

**To Reproduce**

* Make sure that latest version of az-cli is installed(2.27 in my case)
* Try to execute an az-cli command to create a Key Vault in Dogfood subscription

**Expected behavior**

The expected behavior is that the Key Vault should get created.

**Environment summary**

**OS details**
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
**az-cli version**
➜  ~ az --version
azure-cli                         2.27.2

core                              2.27.2
telemetry                          1.0.6

Extensions:
account                            0.2.1
vmware                             3.1.0

**Additional context**

The create Key Vault request got successful when downgraded the az-cli version following
➜  ~ az --version
azure-cli                         2.22.0 *

core                              2.22.0 *
telemetry                          1.0.6

Extensions:
account                            0.2.1
vmware                             3.1.0

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
For service info: '2021-04-01-preview' not supported in dogfood environment

**Comment by sebansal** [comment]
Please reach out to the AKV dev internally to further investigate.
