### ISSUE TITLE
Adding secondary certificate to Sf cluster

### ISSUE THREAD

**Issue by adrianvellamlt** [Azure/azure-cli#19398]
## Describe the bug

**Command Name**
`az sf application certificate add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
add_app_cert() missing 1 required positional argument: 'client'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
TypeError: add_app_cert() missing 1 required positional argument: 'client'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sf application certificate add --cluster-name {} --resource-group {} --secret-identifier {}`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-debian-bullseye-sid
Python 3.6.10
Installer: DEB

azure-cli 2.27.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@adrianvellamlt Apologies for the late reply. Please see the reply from the product owner [here](https://github.com/Azure/azure-cli/issues/9187). You can use Add-AzVmssSecret command instead to add certificates to the clusters. This command works for both Windows and Linux clusters). More Info [here](https://docs.microsoft.com/en-us/powershell/module/az.compute/add-azvmsssecret?view=azps-2.6.0).

**Sample script:**

```
$cert = Get-AzKeyVaultCertificate -VaultName '<Key Vault Name>' -Name '<Certificate Name>'

$Vault = Get-AzKeyVault -VaultName '<Key Vault Name>'

$CertConfig = New-AzVmssVaultCertificateConfig -CertificateUrl $cert.SecretId 

$VMSS = Get-AzVmss -ResourceGroupName '<Resource Group Name>'  -VMScaleSetName '<VMSS Name>'

Add-AzVmssSecret -VirtualMachineScaleSet $VMSS -SourceVaultId $Vault.ResourceId -VaultCertificate $CertConfig | Update-AzVmss 
```


Please note that if you use the above script, then it’ll add a new sourceVault section to the VMSS. Hence, you need to create a new key vault in the same location as of the previous key vault and then create a new certificate inside it. You can’t add a new vaultCertificates entry to sourceVault using this command. This has been documented [here](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#when-i-run--update-azvmss--after-adding-more-than-one-certificate-from-the-same-key-vault--why-do-i-get-an-error-message-).

Please feel free to reopen this thread if you have any further queries on this.
