### ISSUE TITLE
Unable to delete BYOS which is configured via Azure portal.

### ISSUE THREAD

**Issue by YusukeTobo** [Azure/azure-cli#19399]
**Describe the bug**
`az webapp config storage-account delete` requires `--custom-id/-i`, but we cannot retrieve it when the BYOS is configured on Azure Portal.

**To Reproduce**
1. Configured BYOS via Azure portal.
2. az webapp config storage-account list --resource-group <rg> --name <app name> to get BYOS info. The result doesn't have CustomId so that we cannot unmount the BYOS via az cli.
```
  {
    "name": "asp",
    "slotSetting": false,
    "value": {
      "accessKey": "****",
      "accountName": "***",
      "mountPath": "/mnt/asp",
      "shareName": "asp",
      "state": "NotValidated",
      "type": "AzureFiles"
    }
  },
```

**Expected behavior**
`az webapp config storage-account list` will tell us CustomId.

**Environment summary**
```
% az version
{
  "azure-cli": "2.27.2",
  "azure-cli-core": "2.27.2",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "appservice-kube": "0.1.21",
    "connectedk8s": "Unknown"
  }
}

%uname -a
Linux *** 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
Sharing this over with the portal team @btardif FYI

**Comment by panchagnula** [comment]
@YusukeTobo heard back from the feature owner to use the name value (i.e "name": "asp",) for --custom-id when trying to delete the BYOS created from portal. Thanks!

**Comment by YusukeTobo** [comment]
@panchagnula Thank you for updating me. I understand --custom-id is name when I mount BYOS via portal.
Build on that point, can I get --custom-id via AzureCLI? just in case I mount BYOS via the cli and forget the custom id.

**Comment by seligj95** [comment]
@YusukeTobo - Executing `az webapp config storage-account list --resource-group --name` with the cli will give you this value. The "name" value in the output is equivalent to "custom-id". We are aware of this confusion and are in the process of changing the name for the "custom-id" parameter to align with the portal. Please let me know if you are still experiencing issues, otherwise we can close this out. Thanks!

**Comment by YusukeTobo** [comment]
@seligj95 - Thank you for updating me. It's clear for now so that I'm gonna close the issue.
