### ISSUE TITLE
Create service principal for access to team resource

### ISSUE THREAD

**Issue by bharadwajy** [Azure/azure-cli#19395]
I would like to create a service principal to provide non-interactive login to access to resources of my default subscription for build and test scripts. I do not have access to add roles to my default subscription. Relevant rows of the output of a`z role assignment list --all --output table` shows something like

| Principal    | Role | Scope|
|----------------|--------|------------
|     ...           |   ...   |    ...    |
| My Group  | Reader | /subscription/<subscription-id>|
|     ...           |   ...   |    ...    |
------------------------------------

My attempt to create a service principal using `az ad sp create-for-rbac` with `--role Reader --scope /subscription/<subscription-id>` fails since I do not have `authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscription/<subscription-id>'`

Is there a way for me to create a service principal for non-interactive access to my default subscription `<subscription-id>` in this situation?

Thanks.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
> Is there a way for me to create a service principal for non-interactive access to my default subscription <subscription-id> in this situation?

No. You have to be an any of

- [Owner](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#owner)
- [User Access Administrator](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#user-access-administrator)
- [Custom role](https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles) with `Microsoft.Authorization/*/Write` permission

of the subscription to create role assignment for the created service principal.

Please refer the the RBAC document for further details: https://docs.microsoft.com/en-us/azure/role-based-access-control/
