### ISSUE TITLE
Character ```^``` missed in input parsing for az appconfig 

### ISSUE THREAD

**Issue by shenmuxiaosen** [Azure/azure-cli#19394]
**Describe the bug**
When we run CLI command in powershell, ```^``` is missed in input argument. For example, if --input is "**a^b**", then it becomes "**ab**". This issue only happens in powershell. After some verifications, character is drop in CLI input pipeline before service team's code can reach it. 

**To Reproduce**

$mypass = 'hello^test'
az appconfig kv set -n 'resource-name' --key 'myKey' --value $mypass --yes -y

**Expected behavior**
All characters should be preserved as input. 

**Environment summary**
CLI version: 2.26.0
Env: Powershell

**Additional context**

**Comment by shenmuxiaosen** [comment]
Issue cut by service team on behalf of a customer reported issue. Looks like it is a generic problem for running CLI in powershell.

**Comment by yonzhan** [comment]
route to service team

**Comment by shenmuxiaosen** [comment]
@yonzhan Can you help to redirect to CLI framework folks who work on cli in powershell? This issue is not limit to az appconfig but all other commands.

**Comment by jiasli** [comment]
In Command Prompt, `^` in such case is interpreted as the the Escape Character which as no meaning before `t`:

```
C:\>echo hello^test
hellotest
```

See https://ss64.com/nt/syntax-esc.html

When calling `az.cmd` from PowerShell, please pay attention to PowerShell's quoting rules: https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md. 

You may surround the value with double quotes:

```
PS > az --debug '"hello^test"'
cli.knack.cli: Command arguments: ['--debug', 'hello^test']
```

Or prevent PowerShell from parsing quotes:

```
PS > az --% --debug "hello^test"
cli.knack.cli: Command arguments: ['--debug', 'hello^test']
```

Or repeat `^` 4 times:

```
PS > az --debug 'hello^^^^test'
cli.knack.cli: Command arguments: ['--debug', 'hello^test']
```

This causes the `az.cmd` script to receive `hello^^test`, and it passes `hello^test` to `python.exe`.
