### ISSUE TITLE
functionapp: Add support for .NET 6 stacks

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-cli#19407]
**Is your feature request related to a problem? Please describe.**
Add support for .NET 6 stacks. https://github.com/Azure/azure-functions-ux/blob/dev/server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts

Needed for end of October.

/cc @apawast @gzuber @panchagnula

**Comment by yonzhan** [comment]
route to service team

**Comment by AnatoliB** [comment]
Please make sure non-.NET languages (Java, Node.js, PowerShell, Python) are also covered.
