### ISSUE TITLE
webapp:`az webapp config container set` is overwriting `acrUseManagedIdentityCreds`

### ISSUE THREAD

**Issue by vachillo** [Azure/azure-cli#19406]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

After setting `acrUseManagedIdentityCreds` and successfully pulling an image from a private repo, calling `az webapp config container set` is overwriting this setting and the docker host then gets a `403` trying to pull the same image

**To Reproduce**

- Set the flag `acrUseManagedIdentityCreds` to true (in my case its done via terraform)
- see the image being pulled in the app container logs
- update image using `az webapp config container set ...`
- see the docker cli throw a `403` in the app container logs
- rerunning terraform shows that setting is toggled back to `false`

**Expected behavior**

- the image is updated and still able to pull from the private registry

**Environment summary**

```
macOS-10.15.7-x86_64-i386-64bit
Python 3.9.6
Installer: HOMEBREW

azure-cli 2.27.2

```

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by vachillo** [comment]
any updates on this?

**Comment by aaavang** [comment]
related issue: https://github.com/MicrosoftDocs/azure-docs/issues/64660

**Comment by seligj95** [comment]
I believe this is closed via https://github.com/Azure/azure-cli/issues/20817. please reopen if this is still an issue.
