### ISSUE TITLE
az aks create: unrecognized arguments: --enable-public-fqdn

### ISSUE THREAD

**Issue by derhoppe** [Azure/azure-cli#19419]
We're trying to use the public dns preview feature of aks but can't deploy using azure cli because of the mentioned error.

We tried using guidance in this documentation

https://docs.microsoft.com/en-us/azure/aks/private-clusters#create-a-private-aks-cluster-with-a-public-dns-address 

Command is:

az aks create -n aks-azeuw-1000-prd -g RG-AZEUW-PAAS-CONTAINER-1000-PRD --load-balancer-sku standard --vnet-subnet-id /subscriptions/.../resourceGroups/RG-AZEUW-NETWORK-1000-PRD/providers/Microsoft.Network/virtualNetworks/VNET-AZEUW-SPOKE-1000-PRD/subnets/SN-AZEUW-INT-1000-PRD --enable-private-cluster --enable-managed-identity --assign-kubelet-identity /subscriptions/.../resourceGroups/RG-AZEUW-SECUTILS-1000-PRD/providers/Microsoft.ManagedIdentity/userAssignedIdentities/MI-AZEUW-1001-PRD --assign-identity /subscriptions/.../resourceGroups/RG-AZEUW-SECUTILS-1000-PRD/providers/Microsoft.ManagedIdentity/userAssignedIdentities/MI-AZEUW-1001-PRD --private-dns-zone none --network-plugin kubenet --enable-azure-rbac --enable-public-fqdn

Error is:

unrecognized arguments: --enable-public-fqdn

TRY THIS:
az aks create --resource-group MyResourceGroup --name MyManagedCluster
Create a kubernetes cluster with default kubernetes version, default SKU load balancer (Standard) and default vm set type (VirtualMachineScaleSets).

az aks create --resource-group MyResourceGroup --name MyManagedCluster --enable-managed-identity
Create a kubernetes cluster which enables managed identity.

az extension add --name anextension
Add extension by name

https://docs.microsoft.com/en-US/cli/azure/aks#az_aks_create
Read more about the command in reference docs

Any ideas on how to solve? Preview extension is installed.

{
  "azure-cli": "2.27.2",
  "azure-cli-core": "2.27.2",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.29"
  }
}

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@derhoppe Apologies for the late reply. The similar issue was discussed [here](https://github.com/Azure/azure-cli/issues/19476) and refer the comment https://github.com/Azure/azure-cli/issues/19476#issuecomment-918187237. Please let me know if you have any queries or concerns. Awaiting your reply.
