### ISSUE TITLE
WebApp:az webapp create does not support --https-only flag

### ISSUE THREAD

**Issue by kevinharing** [Azure/azure-cli#19415]
**Is your feature request related to a problem? Please describe.**
Due to Azure Policy we need to enable https by default on the webapp (who wouldn't want that?) and not via az webapp update.

**Describe the solution you'd like**
`az webapp create -g MyResourceGroup -p MyPlan -n MyUniqueAppName **--https-only**`

**Describe alternatives you've considered**
`az webapp update` has been tried, but the original create command will be blocked by policy.

**Additional context**
https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_create
https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_update

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
Thanks for your feedback. We will verify and consider this for future releases. No ETA as of now.

**Comment by Kotasudhakarreddy** [comment]
@panchagnula FYI

**Comment by yvaillancourt** [comment]
We have exactly the same problem, the only way we can create a new web app is with "az deployment group create".  But it's not an easy way.

Maybe if az webapp create can support --properties @{httpsOnly=$true} (and other properties) can be nice.
