### ISSUE TITLE
WebApp:az webapp create does not support --generic-configurations (i.e. siteConfig)

### ISSUE THREAD

**Issue by kevinharing** [Azure/azure-cli#19418]
**Is your feature request related to a problem? Please describe.**
Due to Azure Policy we need to set siteConfig on webapp create and not via az webapp config set.

**Describe the solution you'd like**
`az webapp create -g MyResourceGroup -p MyPlan -n MyUniqueAppName --generic-configurations "@app_config.json"`

**Describe alternatives you've considered**
`az webapp config set --generic-configurations "@app_config.json" -n MyUniqueAppName -g MyResourceGroup `

app_config.json contents:
```
{
    "ftpsState": "Disabled",
    "scmIpSecurityRestrictions": [
        {
            "action": "Allow",
            "description": "Allow AzDo agents access to SCM endpoint",
            "name": "Allow_AzDoAgent",
            "priority": 100,
            "vnetSubnetResourceId": "<resourceId>"
        }
    ]
}
```

The above works, but the original create command will be blocked by policy, hence this feature request.

**Additional context**
https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_create
https://docs.microsoft.com/en-us/cli/azure/webapp/config?view=azure-cli-latest#az_webapp_config_set

**Comment by panchagnula** [comment]
Not something planned to support at this time for create. Thank you for the feedback.
