### ISSUE TITLE
Valid SAS token for a blob container works in ASE but not in Azure CLI

### ISSUE THREAD

**Issue by ivarec** [Azure/azure-cli#19424]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
If I use the SAS token (full URL) provided by a third party so that I can access their blob storage container, it works without any issues. If I use the same token via azure CLI, I get an authentication error. My SAS token (full URL) looks like this:

`https://{some_account}.blob.core.windows.net/{some_container}?sr=c&sig=ADDS3YoX%2BfN2xy4%2B50uuFRnhrWuEtPe13ur6TjdhjjQ%3D&se=2021-12-24T13%3A01%3A00Z&sp=rl`

And my `az` invocation looks like this:

`az storage blob list --container-name {some_container} --account-name {some_account} --auth-mode key --sas-token 'sr=c&sig=ADDS3YoX%2BfN2xy4%2B50uuFRnhrWuEtPe13ur6TjdhjjQ%3D&se=2021-12-24T13%3A01%3A00Z&sp=rl'`

When using `az`, I get the following error:

`Authentication failure. This may be caused by either invalid account key, connection string or sas token value provided for your storage account.`

**To Reproduce**
I can provide the full token in private, if needed.

**Expected behavior**
The same SAS token should work in Azure Storage Explorer (ASE) and Azure CLI without issues.

**Environment summary**
Install method: pip

azure-cli                         2.27.2
core                              2.27.2
telemetry                          1.0.6
Python (Linux) 3.8.11 (default, Aug 10 2021, 20:31:31) 
[GCC 9.3.0]

**Additional context**
None.

**Comment by yonzhan** [comment]
Storage

**Comment by evelyn-ys** [comment]
Hi @ivarec 
When specifying `--auth-mode key`, CLI is expecting an `--account-key` instead of `--sas-token`. For `--sas-token` usage, you just need to provide `--accout-name`~

So just update your command: `az storage blob list --container-name {some_container} --account-name {some_account} --sas-token` and see if it can work.

**Comment by ivarec** [comment]
It worked. Thanks
