### ISSUE TITLE
Can't Create Registry

### ISSUE THREAD

**Issue by Olusoladeboy** [Azure/azure-cli#19426]
## Describe the bug

**Command Name**
`az acr create`

**Errors:**
```
API version 2020-11-01-preview does not have operation group 'registries'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/acr/_client_factory.py, ln 20, in cf_acr_registries
    return get_acr_service_client(cli_ctx).registries
azure/mgmt/containerregistry/_container_registry_management_client.py, ln 304, in registries
    raise ValueError("API version {} does not have operation group 'registries'".format(api_version))
ValueError: API version 2020-11-01-preview does not have operation group 'registries'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr create -n {} -g {} --sku {}`

## Environment Summary
```
Linux-5.11.0-22-generic-x86_64-with-glibc2.33
Python 3.9.5
Installer: DEB

azure-cli 2.18.0

Extensions:
azure-devops 0.19.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Lybecker** [comment]
I have the same issue:

{
  "azure-cli": "2.18.0",
  "azure-cli-core": "2.18.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.19.0"
  }
}

**Comment by Olusoladeboy** [comment]
I had to create the registry from the Portal itself, I'd advise you do that too

**Comment by Lybecker** [comment]
I'm using a devcontainer to deploy a new environment. The devcontainer uses the latest version of AZ CLI, so I'm currently stuck

**Comment by Wwwsylvia** [comment]
Hi @Olusoladeboy @Lybecker,  does the issue still exist? If so, could you re-run with `--debug` option and share the logs? Thanks!
To unblock, can you upgrade to the latest CLI version 2.27.2 and try again?

**Comment by navba-MSFT** [comment]
@Olusoladeboy Apologies for the late reply. I couldn't reproduce this issue using most recent version of AzCLI. Could you please use the [most recent version of the AzCLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and then test again ? Awaiting your reply.
