### ISSUE TITLE
Implement `az staticwebapp environment delete`

### ISSUE THREAD

**Issue by tkhadimullin** [Azure/azure-cli#19433]
**Is your feature request related to a problem? Please describe.**
At the moment there seems to be no way to clean up Staging Environments via the CLI. 

**Describe the solution you'd like**
Running something like
`az staticwebapp environment delete --name swa-name --env environment-name`

**Describe alternatives you've considered**
Deleting from the Portal seems to be supported. But this is much harder to automate. In some cases (see context below) even this may not work and will likely require redeploying the whole resource.

**Additional context**
1. I created an SWA resource with `Other` source of deployment.
2. Performed a manual deployment using `mcr.microsoft.com/appsvc/staticappsclient` directly:
```
docker run -it --rm \
   -e INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN=<my_deployment_token> 
   -e DEPLOYMENT_PROVIDER=DevOps \
   -e GITHUB_WORKSPACE="/working_dir"
   -e IS_PULL_REQUEST=true \
   -e BRANCH="TEST_BRANCH" \
   -e ENVIRONMENT_NAME="TESTENV" \
   -e PULL_REQUEST_TITLE="PR-TITLE" \
   -e INPUT_APP_LOCATION="." \
   -e INPUT_API_LOCATION="./api" \
   -v ${pwd}:/working_dir \
   mcr.microsoft.com/appsvc/staticappsclient:stable \
   ./bin/staticsites/StaticSitesClient upload
```
3. Ended up with two environments and no way to delete them except for dropping the whole resource

![image-3](https://user-images.githubusercontent.com/741601/131860890-2f40e133-9702-4a0b-9982-96223e1e5faf.png)
![image-2](https://user-images.githubusercontent.com/741601/131860896-8460243a-3202-4144-85fb-20824df26437.png)

**Comment by yonzhan** [comment]
route to service team

**Comment by bmiddha** [comment]
related pr: #19514

**Comment by RakeshMohanMSFT** [comment]
This is implemented. Closing the issue.
