### ISSUE TITLE
functionapp: support always ready and prewarmed instances for premium plan

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-cli#19435]
See related issue: https://github.com/Azure/azure-functions-core-tools/issues/2059

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
this command uses & depends on SDK to be updated with new properties in swagger. Once the feature team takes care of updating swagger & new SDK is generated , CLI can use the new SDK. Once this is done, the command has a --set parameter that can be used to update any parameter. Is the ask for these properties to be add as first class parameters? Is this still needed?

**Comment by panchagnula** [comment]
CLI has been updated with new SDK a while back & hence --settings can now be used to support the new porperties.
