### ISSUE TITLE
az servicebus namespace authorization-rule keys list returns "Not found" in tutorial

### ISSUE THREAD

**Issue by docktermj** [Azure/azure-cli#19436]
**Describe the bug**
`az servicebus namespace authorization-rule keys list` as demonstrated in https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quickstart-cli returns this output (when `--verbose` option is used):

```console
Configured default 'learn-a98d812e-02ca-4e78-9dda-b0ff2e0c3351' for arg resource_group_name
Operation returned an invalid status 'Not Found'
Command ran in 1.524 seconds (init: 0.170, invoke: 1.353)
```

**To Reproduce**

Follow steps on https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quickstart-cli.  Here's what was actually performed:

```console
$ az group create --name ContosoRG777 --location eastus

$ az servicebus namespace create --resource-group ContosoRG777 --name ContosoSBusNS777 --location eastus

$ az servicebus queue create --resource-group ContosoRG777 --namespace-name ContosoSBusNS777 --name ContosoOrdersQueue777

$ az servicebus namespace authorization-rule keys list --resource-group ContosoRG777 --namespace-name ContosoSBusNS777 --name RootManageSharedAccessKey777 --query primaryConnectionString --output tsv  --verbose
```

**Expected behavior**
A tutorial that does not produce errors.

**Environment summary**

```console
$ az --version
azure-cli                         2.27.2

core                              2.27.2
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/home/senzing/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Aug 23 2021, 03:36:14) 
[GCC 7.5.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

**Comment by docktermj** [comment]
Ok,  turns out this variation works:

```console
$ az servicebus namespace authorization-rule keys list --resource-group ContosoRG777 --namespace-name ContosoSBusNS777 --name RootManageSharedAccessKey --query primaryConnectionString --output tsv  --verbose
```

Would be nice if the error message:

```
Operation returned an invalid status 'Not Found'
```
would be a little more specific as to what is not found.

**Comment by yonzhan** [comment]
route to service team

**Comment by Saglodha** [comment]
Hi @docktermj, looking at the above tutorial this is an expected behavior. 

Whenever we create a namespace, the default rule that gets created has a name: RootManagedSharedAccessKey. Can you please confirm if you have created an additional rule with the name RootManagedSharedAccessKey777 when we tried the list call?  

If not, then the call would indeed fail with 'Not found' since there would be no rule that matches all the defined inputs in the cmdlet. Hope this helps.
