### ISSUE TITLE
`az resource list --namespace` does not filter

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#1945]
The output of `az resource list --namespace 'Microsoft.Compute'` contains resource from namespaces other than Microsoft.Compute.

The expected result is that only resources from the specified namespace should be returned.

**Comment by johanste** [comment]
The current implementation only applies the namespace if you also specify the type. I cannot find the documentation that describes exactly which filter combinations are valid, but we should at least warn about the namespace requiring the type if that is the combination that is needed from the service's perspective.
