### ISSUE TITLE
Unexplained az command failures 

### ISSUE THREAD

**Issue by jsane-vp** [Azure/azure-cli#19450]
## Describe the bug
I was in process of enabling pod identity in my AKS cluster using the reference https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity. 

After I executed the "az extension add --name aks-preview" I believe things have started failing.

Prior to it I wanted to configure my cluster to attach to an Azure CR using the below command: 
az aks update -n <cluster-name> -g <resource-group> --attach-acr <ACR-name>

The aks update command started failing as seen in the attached file.
[Az command failure error.txt](https://github.com/Azure/azure-cli/files/7108413/Az.command.failure.error.txt)

Taking cue from the error I re-attempted doing the following:
az login
az aks get-credentials --name <cluster-name> --resource-group <resource-group>

But now even the aks get-credentials command fails with same error as that in the attached file. I suspect this started happening after installing aks-preview extension. 

I am executing these commands from within Windows Powershell. 

Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.13.0 *

Extensions:
aks-preview 0.5.31

**Comment by yonzhan** [comment]
route to service team

**Comment by jsane-vp** [comment]
Actually my bad :-( as I had failed to upgrade the CLI to the supported version. After upgrading there are no errors with what I was attempting to do. 

This can be closed for now. regret the false alarm
