### ISSUE TITLE
az functionapp vnet-integration add, allow adding a VNET for a function app running in a consumption plan

### ISSUE THREAD

**Issue by v-bbalaiagar** [Azure/azure-cli#19469]
az functionapp vnet-integration add -g -n --vnet --subnet

The above command allows binding a VNET with the function app running in a Consumption Plan.

I am able to reproduce this for the function app "Powershell-func"
"name": "Powershell-func",
"management_state": "",

"sku": "Dynamic",

"vnet_name": "f4a54_default",

Essentially the command should not allow the VNET integration for the function app running in a consumption plan.

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
@StrawnSC is this already fixed with the new api-version by the API team if not lets add a validation check.

**Comment by kamperiadis** [comment]
Marking as resolved since this has already been addressed.
