### ISSUE TITLE
No matching extensions for 'authV2'

### ISSUE THREAD

**Issue by Chibuzor27** [Azure/azure-cli#19460]
In attempting to run this command locally, it tries to install extension authV2. However it appears that the extension doesn't exist.
az webapp auth microsoft update `
        --resource-group $rgName `
        --name $name `
        --client-id $appId `
        --issuer $tokenIssuerUrl `
        --allowed-audiences $aadTokenAudiences `
        --yes
    ProcessLastExitCode $operation 

I also attempted to run `az extension list-available --output table` but in the list of extensions available, authV2 isn't part of the list.

I then attempted to run the classic version, but it also attempted to install authV2. `No matching extensions for 'authV2'. Use --debug for more information.`
az webapp auth-classic update `
        --resource-group $rgName `
        --name $name `
        --enabled true `
        --action LoginWithAzureActiveDirectory `
        --aad-allowed-token-audiences $aadTokenAudiences `
        --aad-client-id $appId `
        --aad-token-issuer-url $tokenIssuerUrl `
        --output none 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5323dc0-8973-d579-328f-5608a8e667f7
* Version Independent ID: 93c445df-3a56-4674-691e-030be4187368
* Content: [az webapp auth-classic](https://docs.microsoft.com/en-us/cli/azure/webapp/auth-classic?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/auth-classic.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/auth-classic.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by Chibuzor27** [comment]
any update on this?

**Comment by panchagnula** [comment]
@mkarmark FYI.

**Comment by Chibuzor27** [comment]
Just wanna follow up on this and find out if there's an update

**Comment by panchagnula** [comment]
@Chibuzor27 are you still seeing this issue?

**Comment by panchagnula** [comment]
@Hamster-Huey FYI

**Comment by seligj95** [comment]
closing as the service team has confirmed functionality. please reopen if you're still experiencing the issue.
