### ISSUE TITLE
unrecognized arguments: --enable-public-fqdn when creating private AKS cluster with public DNS address

### ISSUE THREAD

**Issue by nguyenlamlll** [Azure/azure-cli#19476]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
unrecognized arguments: --enable-public-fqdn

```

## To Reproduce:
Steps to reproduce the behavior.

- `az extension add --name aks-preview`
- `az aks create -n {} -g {} --load-balancer-sku standard --enable-private-cluster --enable-public-fqdn`

## Expected Behavior
I can create a private AKS cluster with a public DNS address so that I can directly use Azure Pipeline tasks to deploy there (without more advanced networking setups). Doc [here.](https://docs.microsoft.com/en-us/azure/aks/private-clusters#create-a-private-aks-cluster-with-a-public-dns-address)

## Environment Summary
```
Linux-5.4.0-1056-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.27.0 *

Extensions:
aks-preview 0.5.31
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by phealy** [comment]
When the public FQDN feature went GA, public FQDN became on by default. [As of the AKS preview extension version 0.5.27](https://github.com/Azure/azure-cli-extensions/blob/main/src/aks-preview/HISTORY.md#:~:text=ga%20private%20cluster%20public%20fqdn%20feature%2C%20breaking%20change%20to%20replace%20create%20parameter%20--enable-public-fqdn%20with%20--disable-public-fqdn%20since%20now%20it's%20enabled%20by%20default%20for%20private%20cluster%20during%20cluster%20creation.), the argument changed from `--enable-public-fqdn` to `--disable-public-fqdn`. Please remove this argument from your command/script as it (correctly) is no longer valid.

**Comment by phealy** [comment]
@yonzhan Could you please close this out? I don't have permissions.

**Comment by nguyenlamlll** [comment]
I see. I se that the doc is updated as well. Thank you.
