### ISSUE TITLE
CLI asks for v4 public ip from a public ipv6 prefix

### ISSUE THREAD

**Issue by brianlehr** [Azure/azure-cli#19473]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When attempting to create a public IP from a public IP prefix that is IPv6, the command fails if the version parameter is not included.

**To Reproduce**
Create public IPv6 prefix, then request an IP from the prefix without specifying version parameter.  The request will eventually timeout and fail, because NRP is requesting a v4 IP.

```
PS C:\Users\blehr> az network public-ip prefix create --name IPv6prefix --resource-group willdeletethis --location eastus --version IPv6 --length 126
{
"customIpPrefix": null,
"etag": "W/\"3ad152a3-6aa2-43c4-93f9-c821ca3b5928\"",
"extendedLocation": null,
"id": "/subscriptions/6bb4a28a-db84-4e8a-b1dc-fabf7bd9f0b2/resourceGroups/willdeletethis/providers/Microsoft.Network/publicIPPrefixes/IPv6prefix",
"ipPrefix": "2a01:111:f100:2002::8975:2d90/126",
"ipTags": [],
"loadBalancerFrontendIpConfiguration": null,
"location": "eastus",
"name": "IPv6prefix",
"prefixLength": 126,
"provisioningState": "Succeeded",
"publicIpAddressVersion": "IPv6",
"publicIpAddresses": null,
"resourceGroup": "willdeletethis",
"resourceGuid": "6779f972-4a2b-47ae-b74e-839c625fe70d",
"sku": {
"name": "Standard",
"tier": "Regional"
},
"tags": null,
"type": "Microsoft.Network/publicIPPrefixes",
"zones": null
}
C:\Users\blehr> az network public-ip create --name IPv6testing --resource-group willdeletethis --location eastus --sku Standard --public-ip-prefix /subscriptions/6bb4a28a-db84-4e8a-b1dc-fabf7bd9f0b2/resourceGroups/willdeletethis/providers/Microsoft.Network/publicIPPrefixes/IPv6prefix
```
This second command will fail after approximately 30 minutes with an Internal Server Error.
_In general, with an existing public ip prefix, you should not need to call out: **Version, Allocation Method, SKU, Tier, or Zonal properties** – these all should be assumed to match the prefix.  This should be fixed for all cases._

**Expected behavior**
The Public IPv6 address should be allocated as requested.

**Environment summary**
azure-cli 2.20.0 on local Powershell 7.

**Comment by yonzhan** [comment]
network

**Comment by brianlehr** [comment]
@00Kai0 Let me know any questions you have re: this ask

**Comment by brianlehr** [comment]
@yonzhan This has been opened since September of last year.  When will it be actioned?
