### ISSUE TITLE
Update az diskpool  to stable swagger

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-cli#19470]
**Resource Provider**

Microsoft.StoragePool

**Description of Feature or Work Requested**

Update az diskpool to stable swagger

**Minimum API Version Required**

2021-08-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/storagepool/resource-manager/Microsoft.StoragePool/stable/2021-08-01/storagepool.json

**Target Date**

11/4

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Hi @dcaro 
Do you want a new CLI module support for Microsoft.StoragePool? As far as I know, there's no command module called `az dispool`.

**Comment by dcaro** [comment]
`az disk-pool` is available as an experiment extension (https://docs.microsoft.com/en-us/cli/azure/disk-pool?view=azure-cli-latest) and is currently using API version `2021-04-01-preview`. 
It should be upgraded to API version `2021-08-01`
