### ISSUE TITLE
Support `--no-wait` on az resource delete

### ISSUE THREAD

**Issue by ishepherd** [Azure/azure-cli#19487]
### Is your feature request related to a problem? Please describe.
* My script deploys a SQL Managed Instance using `az deployment group create ... --no-wait`
* Once finished using it, the script destroys it with `az resource delete`

[SQL MI create and delete are lengthy operations](https://docs.microsoft.com/en-gb/azure/azure-sql/managed-instance/management-operations-overview#duration) and this causes a problem as the script runs in Azure Pipelines which has a 1 hour job limit.

The create bit is ok because `az deployment group create` returns quickly (due to --no-wait) and Azure Pipelines can just rerun the script each hour, it will check the deployment status each time.

But for resource delete the --no-wait option is missing. This causes a long wait and Azure Pipelines kills the job.

### Describe the solution you'd like
A `--no-wait` option on `az resource delete`

### Describe alternatives you've considered
* We can let Azure Pipelines go ahead and kill the job while it's still waiting on `az resource delete`. But this spams our monitoring channels with a failure notification.
* :white_check_mark: We can put the resource in its own Resource Group and delete that whole RG, instead of deleting just the resource (RG delete _does_ support --no-wait)

**Comment by yonzhan** [comment]
ARM

**Comment by jbpaux** [comment]
Hi, I have the same request. I'm trying to delete resources from a RG so I have my query that returns the objects I want to delete and then use az resource delete commands but it would be great to have a no-wait option as it can take a lot of time. @yonzhan any update on the backlog ?
