### ISSUE TITLE
"az container delete" fails due to 'ContainerGroupsOperations' object has no attribute 'delete'

### ISSUE THREAD

**Issue by mkowa42** [Azure/azure-cli#19489]
## Describe the bug

Since docker image `azure-cli:2.28.0` I get the following error when executing

`az container delete --resource-group any-rg --name any-name`

The same command works fine if it's running with `azure-cli:2.27.2`.

**Command Name**
`az container delete`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'ContainerGroupsOperations' object has no attribute 'delete'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/container/custom.py", line 66, in delete_container
    return client.delete(resource_group_name, name)
AttributeError: 'ContainerGroupsOperations' object has no attribute 'delete'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container delete --resource-group {} --name {}`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with, Alpine Linux v3.14
Python 3.9.6
Installer: DOCKER

azure-cli 2.28.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by jhwj9617** [comment]
Yes. There is a serious issue w/ az cli for deleting container groups. Started happening since yesterday. This needs a hotfix asap. 
```
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'ContainerGroupsOperations' object has no attribute 'delete'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 66, in delete_container
```

**Comment by jhwj9617** [comment]
[ADO AzureCLI](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops) task is locked into this latest version and causing issues elsewhere.

**Comment by mikeminutillo** [comment]
This appears to have been updated over the weekend in the [GitHub Actions Windows 2019 image](https://github.com/actions/virtual-environments/commit/d1d592805b90fc0f382706a6ce2caa9b98ff77f3#diff-816219d3c9f30fcc1c40f88ca826c1662bf99eded781c1b419dd2dfb577ae227R92). Until this is fixed, all of our CI builds will fail and leave dangling docker images.

**Comment by ddelapasse2** [comment]
Just to chime in. Ours broke about a week ago as well.  This is our Azure az-cli deploy script:

![image](https://user-images.githubusercontent.com/18335575/133643576-36049cfb-7896-401b-9a72-95ca46077429.png)

Any work around or hotfix?  We can't find a way to force Azure to use a prior version of the cli.  This is a big problem.  All deployments being run off dev laptops for now.

**Comment by kf6kjg** [comment]
I see nothing in the [release notes](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#september-07-2021) to indicate that there was any intention to change the behavior of this command.

**Comment by StefanVo** [comment]
Where possible we replaced the cli command `az container delete` with PowerShell `Remove-AzContainerGroup` as a temporary workaround.

Ref. https://docs.microsoft.com/en-us/powershell/module/az.containerinstance/remove-azcontainergroup?view=azps-6.4.0

**Comment by kf6kjg** [comment]
Workaround for GitHub Actions:
```
      - name: Destroy container
        uses: azure/CLI@v1.0.4
        with:
          azcliversion: 2.27.2 # v2.28.0 introduces regression https://github.com/Azure/azure-cli/issues/19489
          inlineScript: |
            az container delete ....
```

**Comment by kf6kjg** [comment]
Digging through the issue reports I found an older report of the same basic symptoms: #19475

**Comment by ddelapasse2** [comment]
For us 2.27.2 worked and then it failed with 2.28.0.

**Comment by snapfisher** [comment]
With 2.28.0 I get the failures with both AZ CONTAINER DELETE and AZ CONTAINER ATTACH.

I was able to perform the deletion through the Azure Portal, though.

**Comment by davetapley** [comment]
If you installed with `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash` per [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-1-install-with-one-command), then workaround with:

```bash
sudo apt-get remove azure-cli
```

Then find your `2.72.2` version with:

```bash
apt-cache show azure-cli | grep 'Version: 2.27.2'
```

Then install with, e.g:
```
sudo apt-get install azure-cli=2.27.2-1~focal
```

Worked for me ✅

**Comment by berndverst** [comment]
Workaround on Mac (especially M1 ARM64):

`brew uninstall azure-cli`
`brew install openssl`

`bash
env CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS="1" \
LDFLAGS="-L$(brew --prefix openssl@1.1)/lib" \
CFLAGS="-I$(brew --prefix openssl@1.1)/include" \
pip3 install azure-cli==2.27.2
`

Those flags were necessary for me because the cryptography couldn't be compiled otherwise.

**Comment by berndverst** [comment]
Better workaround (relies on Docker) that is cross-platform:

Use the 2.27.2 Azure CLI Docker container

```bash
docker run --rm -it mcr.microsoft.com/azure-cli:2.27.2 /bin/bash
az login
```

Now proceed to run whatever you wanted to run
```
az container logs ....
az container exec ....
```
