### ISSUE TITLE
Table output with multiple tables

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#1948]
When using table format on things like "show" commands, there is interest in having the resulting output print multiple tables:

Examples:
#1131: Output the record set details, followed by the individual records formatted as a table.
#1291: Output an NSG, followed by it's security rules, all in table format.

Essentially, show the resource details as a table, and then show the contents of its collections as individual tables. Our current table output does not support this.

**Comment by yugangw-msft** [comment]
let us live with it till we have more user voices
