### ISSUE TITLE
`az functionapp show` should not show webapps

### ISSUE THREAD

**Issue by parth21999** [Azure/azure-cli#19491]
## Describe the bug
 `az functionapp show` can be used to show webapps. There should be a type check to prevent this.

**Command Name**
`az functionapp show`

**Errors:**
```
Shows webapp
```

## To Reproduce:

- `az functionapp show -n {webapp_name}`

## Expected Behavior
Should give an error that functionapp could not be found.

## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.8.10
Installer: PIP

azure-cli 2.27.2

```

**Comment by yonzhan** [comment]
route to service team
