### ISSUE TITLE
[PLR] Microsoft.TestBase 

### ISSUE THREAD

**Issue by jamesc** [Azure/azure-cli#19494]
**Resource Provider**
Microsoft.TestBase

**Description of Feature or Work Requested**
New RP through PLR

**Minimum API Version Required**
2021-09-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/15959

Docs: https://docs.microsoft.com/en-us/microsoft-365/test-base/?view=o365-worldwide

**Target Date**
11/1/2021

**Comment by yonzhan** [comment]
new PLR

**Comment by kairu-ms** [comment]
Service team has already created a PR for TestBase:

https://github.com/Azure/azure-cli-extensions/pull/3854

**Comment by jujiang-msft** [comment]
@kairu-ms just clarity that the issue https://github.com/Azure/azure-cli-extensions/pull/3854 created by @v-zhifufeng intended for experiment to explore any effort from service team complete the work. Sorry for any confusion introduced by this.

**Comment by jamesc** [comment]
No longer in PLR scope.  @jujiang-msft - should we review and merge your PR  Azure/azure-cli-extensions#3854 ?

**Comment by jujiang-msft** [comment]
@jamesc no need to review this PR Azure/azure-cli-extensions#3854. Thanks.

**Comment by yonzhan** [comment]
@jujiang-msft Thanks to confirm. Share we close this issue?
