### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by karthikgouni** [Azure/azure-cli#19496]
## Describe the bug

**Command Name**
`az aks list`

**Errors:**
```
unrecognized arguments: --option=table

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks list --option={}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by jiasli** [comment]
The correct argument name should be `--output`, instead of `--option`:

```
> az aks list --help

Global Arguments
    ...
    --output -o                     : Output format.  Allowed values: json, jsonc, none, table, tsv,
                                      yaml, yamlc.  Default: json.
```

Where did you see the incorrect usage of `--option`? It should be fixed of course.
