### ISSUE TITLE
WebApp:az webapp config backup restore fails

### ISSUE THREAD

**Issue by rsenk** [Azure/azure-cli#19492]
## Describe the bug

**Command Name**
`az webapp config backup restore`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'WebAppsOperations' object has no attribute 'restore'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 37, in _ex_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1840, in restore_backup
    return client.web_apps.restore(resource_group_name, webapp_name, 0, restore_request)
AttributeError: 'WebAppsOperations' object has no attribute 'restore'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- First you need to create a web app backup
- `az webapp config backup restore --backup-name {} --container-url {} --resource-group {} --webapp-name {}`

## Expected Behavior
Backup should be restored.

## Environment Summary
```
Linux-5.4.0-1058-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
@parth21999 can you check if this repros & is a regression with the latest cli version? thanks

**Comment by rsenk** [comment]
Could you confirm if it is a bug? Or I did something wrong?

**Comment by panchagnula** [comment]
@Kotasudhakarreddy can you check if you an repro this?

**Comment by Kotasudhakarreddy** [comment]
I am able to repro the issue. It requires a code fix.

**Comment by nik0811** [comment]
The above bug is closed or not, I got the above error for below version
`nikhil@Azure:~/workosoft$ az --version
azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Python location '/usr/bin/python3'
Extensions directory '/home/nikhil/.azure/cliextensions'

Python (Linux) 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]`

Error:
`nikhil@Azure:~/workosoft$ ./app_services.sh
"2021-11-29T14:10:44.9019508"
The command failed with an unexpected error. Here is the traceback:
'WebAppsOperations' object has no attribute 'restore_snapshot'
Traceback (most recent call last):
  File "/home/nikhil/.local/lib/python3.7/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/nikhil/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/home/nikhil/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/nikhil/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/home/nikhil/.local/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/nikhil/.local/lib/python3.7/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/nikhil/.local/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 1894, in restore_snapshot
    return client.web_apps.restore_snapshot(resource_group_name, name, request)
AttributeError: 'WebAppsOperations' object has no attribute 'restore_snapshot'
To open an issue, please run: 'az feedback'`

**Comment by panchagnula** [comment]
This has been fixed please try with the latest version of CLI

**Comment by carlrab** [comment]
I am trying this with CloudShell and it is failing with this same error message

**Comment by panchagnula** [comment]
This in fact is no fixed - the restore backUp apis have changed completely so this needs to be re-visited.

The Python SDK api to use is begin_restore_from_backup_blob

**Comment by haroonf** [comment]
This has been fixed: https://github.com/Azure/azure-cli/pull/22365

**Comment by carlrab** [comment]
Still fails for me.

**Comment by panchagnula** [comment]
> Still fails for me. From: Haroon Feisal ***@***.***> Sent: Monday, May 16, 2022 1:51 PM To: Azure/azure-cli ***@***.***> Cc: Carl Rabeler (AQUENT LLC) ***@***.***>; Comment ***@***.***> Subject: Re: [Azure/azure-cli] WebApp:az webapp config backup restore fails (#19492) This has been fixed: #22365<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fpull%2F22365&data=05%7C01%7Cv-crabeler%40microsoft.com%7C9cb1448d323d466b306b08da377dd629%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637883310862237788%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TJMvnE1tEImjqhPKwu22wU7YoN4I3oLfpMYNinX48Uw%3D&reserved=0> - Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fissues%2F19492%23issuecomment-1128122677&data=05%7C01%7Cv-crabeler%40microsoft.com%7C9cb1448d323d466b306b08da377dd629%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637883310862237788%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Wiv2VbdVBgyZxYG9m%2FSXJJozbO%2BKpWxj3yvawO0KXsg%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWOWDRQTEOSNQCEYU5OLXGTVKKYMVANCNFSM5DVYTXGA&data=05%7C01%7Cv-crabeler%40microsoft.com%7C9cb1448d323d466b306b08da377dd629%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637883310862237788%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XzanRBxG8F2Jc3HkLri11wW1fKBEzH4lrnuUdZb8JGI%3D&reserved=0>. You are receiving this because you commented.Message ID: ***@***.******@***.***>>

@carlrab did you try this with the latest cli release 2.37.0?

**Comment by carlrab** [comment]
I tried it in Cloud Shell.

**Comment by panchagnula** [comment]
@carlrab it could b possible that cloud shell was not updated with the new version yet. Please run az--version & check if the core-cli version used.
