### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by karthikgouni** [Azure/azure-cli#19497]
## Describe the bug

**Command Name**
`az vm list`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm list --output={}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.27.2

```

**Comment by yonzhan** [comment]
Compute

**Comment by jiasli** [comment]
Please describe the problem you have.
