### ISSUE TITLE
[Enhancement Proposal] Add option `plaintext` to disable token cache encryption

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#19506]
## Azure PowerShell's token encryption issues

Various issues have been reported regarding Azure PowerShell's token encryption functionality:

Windows:

- https://github.com/Azure/azure-powershell/issues/14925
- https://github.com/Azure/azure-powershell/issues/13691

MacOS:

- https://github.com/Azure/azure-powershell/issues/14478
- https://github.com/Azure/azure-powershell/issues/15423

The workaround is to disable persistent token cache between sessions:

- https://github.com/MicrosoftDocs/azure-docs-powershell/pull/1872

However, this approach is not feasible for Azure CLI, as there is no concept of session - Azure CLI is a `python` application and there is no connection between commands.

## Python SDK status

In current Python SDKs, a fallback mechanism is used:

- Azure Identity (Python) provides [`allow_unencrypted`](https://github.com/Azure/azure-sdk-for-python/blob/7373db2a493e23bb03a4d8d2f74fff9767f0cb94/sdk/identity/azure-identity/azure/identity/_persistent_cache.py#L64)
- MSAL Extension (Python)'s sample code uses [`fallback_to_plaintext`](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/26240cbc092e0fd28badf52753888051db3a4cec/sample/persistence_sample.py#L8)

But this fallback mechanism _only_ takes effect when initializing `LibsecretPersistence` on Linux fails - it is possible that failures can also occur when

- `FilePersistenceWithDataProtection` on Windows, `KeychainPersistence` on MacOS are initialized or actually used. (Token encryption is enforced on Windows and MacOS)
- `LibsecretPersistence` on Linux is actually used

When failures happen on various platforms, forcing token encryption will render Azure CLI totally unusable.

## Proposed solution

Instead of using `allow_unencrypted` or `fallback_to_plaintext` and let Azure CLI try its best to encrypt, we should introduce a definitive option like `plaintext` to force unencrypted token cache, so that complex platform-dependent problems can be bypassed.

Reference email: _Workaround for DPAPI/KeyChain Errors_

**Comment by yonzhan** [comment]
Enhancement

**Comment by rayluo** [comment]
Regarding to this:

> Windows:
> 
> * https://github.com/Azure/azure-powershell/issues/14925

[One of its comment](https://github.com/Azure/azure-powershell/issues/14925#issuecomment-835810510) linked to [this MSAL Ex .Net PR which adds WithUnprotectedFile() option](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/pull/152).

So, if that kind of "opt-in to unprotected token cache" behavior is what you want, you can use [the `FilePersistence` in MSAL EX Python](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/0.3.0/sample/persistence_sample.py#L31). The choice is yours.

**Comment by jiasli** [comment]
Totally understand. That's why this issue is opened in Azure CLI repo.

**Comment by jiasli** [comment]
Implemented in https://github.com/Azure/azure-cli/pull/19853.
