### ISSUE TITLE
[Storage] Could the create command be simplified?

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1950]
It would be great if the `az storage account create` command didn't require a location parameter, and instead defaulted it from the specified resource group. Additionally, could the `--sku` parameter have a default value? Other services have default values for their SKU (e.g. `az appservice plan create`) and it definitely helps the getting started experience a bit when you're just looking to explore/evaluate something.

**Comment by lostintangent** [comment]
I also just noticed that the `az vm create` command also defaults the SKU for the storage account it (optionally) auto-creates. If we added the same behavior to `az storage account create`, that would be awesome!

**Comment by williexu** [comment]
This issue has been resolved, location is inferred from the resource-group.

**Comment by troydai** [comment]
I will reopen this issue since the `sku` parameter is still required. We can consult with storage team to see if there is any solution to this.

**Comment by troydai** [comment]
The default sku on portal is Standard RAGS.
