### ISSUE TITLE
Unable to create child management group as of version 2.27.1

### ISSUE THREAD

**Issue by mdtro** [Azure/azure-cli#19511]
**Describe the bug**
```
$ az account management-group create --name "test123" --parent "MyTestMG"
```

In version 2.27.0, creating a child management group. As of 2.27.1, the same command is failing with the error message:

> (AuthorizationFailed) The client '\<spn id\>' with object id '\<spn id\>' does not have authorization to perform action 'Microsoft.Management/register/action' over scope '/subscriptions/\<subscription id\>' or the scope is invalid. If access was recently granted, please refresh your credentials.

**To Reproduce**

To recreate this issue, you'll need the following:

- A management group, for example named "MyTestMG".
- A subscription (does not need to be a member of the above management group).
- A SPN with the following roles assigned:
  - _Reader_ at the subscription scope.
  - _Management Group Contributor_ at the "MyTestMG" management group scope.
- An AzureCLI (version >=2.27.1) shell logged in as your SPN.
- An Azure PowerShell instance logged in as your SPN.

Running the following will fail with an error message.
```
$ az account management-group create --name "test123" --parent "MyTestMG"

(AuthorizationFailed) The client '<spn id>' with object id '<spn id>' does not have authorization to perform action 'Microsoft.Management/register/action' over scope '/subscriptions/<subscription id>' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

In Azure PowerShell (I tested with version 6.4.0.34709), the equivalent command with the same SPN and assigned roles will complete successfully and create the child management group.

```
$parentGroup = Get-AzManagementGroup -GroupName MyTestMG
New-AzManagementGroup -GroupName 'test123' -ParentId $parentGroup.id
```

**Expected behavior**
With both AzureCLI and Azure PowerShell, I would expect them to behave the same way and create the child management group with the same roles/permissions assigned to the SPN.

**Environment summary**
AzureCLI >=2.27.1
Azure PowerShell 6.4.0.34709

Azure environment:
- A management group, for example named "MyTestMG".
- A subscription (does not need to be a member of the above management group).
- A SPN with the following roles assigned:
  - _Reader_ at the subscription scope.
  - _Management Group Contributor_ at the "MyTestMG" management group scope.

**Comment by yonzhan** [comment]
management group

**Comment by zhoxing-ms** [comment]
This is a known issue, the addition of `_register_rp()` operation is caused by the history issue of service: tenant-level resources and subscription-level resources cannot support automatic RP registration on server side
Historical discussions: https://github.com/Azure/azure-cli-extensions/pull/62#discussion_r168619781

@wwendyc Could you help to look at the following questions? Or do you know who can look it?
May I ask has the service solved the problem of automatic RP registration? If so, CLI can remove the `_register_rp()` operation, right?

**Comment by azsec** [comment]
@zhoxing-ms I'm seeing the fix is merged to `dev` branch. When does this fix go GA so I could update Az CLI?

**Comment by zhoxing-ms** [comment]
@azsec Hi, please use `az upgrade --yes` to update CLI to the latest version, and then have a try
