### ISSUE TITLE
`az --version` in WSL2 call Windows Azure CLI instead of Linux Azure CLI

### ISSUE THREAD

**Issue by Cuda-Chen** [Azure/azure-cli#19517]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Hi there! I am the new comer of Azure CLI.
I have install Azure CLI on Windows and WSL2(Ubuntu).
However, when I use `az --version` to verify the installation of Azure CLI in WSL2(Ubuntu). `az --version` display the Windows information.

**To Reproduce**

```
# First install Azure CLI of Windows in PowerShell described here: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-powershell

# Then install Azure CLI in WSL2(Ubuntu) according to this post: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt
$ curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

# Verify Azure CLI installation in WSL2(Ubuntu)
$ az --version
azure-cli                         2.28.0

core                              2.28.0
telemetry                          1.0.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\luhsuan_chen\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

# Get Azure CLI installation path in WSL2(Ubuntu)
$ which az
/usr/bin/az

# More interesting, if I run the following command in WSL2(Ubuntu), Azure CLI gets the Linux one
$ /usr/bin/az --version
$ /usr/bin/az --version
azure-cli                         2.28.0

core                              2.28.0
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/home/luhsuanchen/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Sep  3 2021, 06:36:51)
[GCC 9.3.0]
```

**Expected behavior**

The `az` command (without specifying the executable path i.e. `/usr/bin/az`) should get Linux settings.

**Environment summary**

* Installation Method:
  * Windows: Microsoft Installer (MSI) with Command in PowerShell
  * WSL2(Ubuntu): Install with one command
* CLI version: 2.28.0
* OS version:
  * Windows: Windows 10 20H2 (Build 19042.1165) x86_64
  * WSL2(Ubuntu):  5.10.16.3-microsoft-standard-WSL2 x86_64
* Shell type:
  * Windows: PowerShell in Windows Terminal
  * WSL2(Ubuntu): bash in Windows Terminal

**Additional context**

**Comment by yonzhan** [comment]
Core

**Comment by jiasli** [comment]
Could you share your `PATH` environment variable value?

```
$ echo $PATH
... /usr/bin ... /mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin

$ which -a az
/usr/bin/az
/mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin/az
```

**Comment by jiasli** [comment]
I am able to repro. It looks like Bash has some cache on the location of `az` after the first execution. `which` on the other hand is a new process which doesn't honor Bash's cache:

```
$ command -V az
az is /mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin/az

$ az --verison
...

$ command -V az
az is hashed (/mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin/az)

$ curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
...

$ command -V az
az is hashed (/mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin/az)

$ which -a az
/usr/bin/az
/bin/az
/mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin/az
```

See https://stackoverflow.com/questions/37056192/which-vs-command-v-in-bash

The solution is simply to restart Bash.
