### ISSUE TITLE
WebApp:Web App Persistent Storage gets disabled after each deployment

### ISSUE THREAD

**Issue by yull1860** [Azure/azure-cli#19519]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
WEBSITES_ENABLE_APP_SERVICE_STORAGE=true will be overwrite to false automatically with below cmdlet
     az webapp config set --linux-fx-version
 or 
     az webapp config container set 

**To Reproduce**

Save application details into variables so we don't have to repeat them in every upcoming command

APP='--subscription [subid] --resource-group [rgname] --name [appname]'

Enable persistent storage in the application as explained in official docs https://docs.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-linux#use-persistent-shared-storage

az webapp config appsettings set $APP \\
--settings WEBSITES_ENABLE_APP_SERVICE_STORAGE=true \\
--query='[?name=='WEBSITES_ENABLE_APP_SERVICE_STORAGE'].{Name:name, Value:value}' \\
--output=table

Output:

Name                                 Value
-----------------------------------  -------
WEBSITES_ENABLE_APP_SERVICE_STORAGE  true

run any of below cmdlet will reset WEBSITES_ENABLE_APP_SERVICE_STORAGE  to false

     az webapp config set $APP --linux-fx-version 'DOCKER|xxxxxxx'

or 
     az webapp config container set $APP \\
       --docker-registry-server-url https://lupmixregistry.azurecr.io \\
       --docker-registry-server-user $DOCKER_REGISTRY_USER \\
       --docker-registry-server-password $DOCKER_REGISTRY_PASSWROD \\
       --docker-custom-image-name '[acrname].azurecr.io/[path]' \\

**Expected behavior**

WEBSITES_ENABLE_APP_SERVICE_STORAGE should be intact once customer config it. 

**Environment summary**
Linux Container app , https://docs.microsoft.com/en-us/azure/app-service/faq-app-service-linux#i-m-using-my-own-custom-container--i-want-the-platform-to-mount-an-smb-share-to-the---home---directory- say by default is false , that totally fine . but you can't automatic reset it to false again .

**Additional context**
https://github.com/Azure/azure-cli/blob/ed1fe586d24b5d78127c0b616cd7e32b765d0bfc/src/azure-cli/azure/cli/command_modules/appservice/custom.py

in update_site_configs() , CLI will reset the key to false when linux-fx-version startwith 'docker'

![image](https://user-images.githubusercontent.com/17472445/132813930-0ef2b755-3b20-4050-b743-f191b59c0c73.png)

![image](https://user-images.githubusercontent.com/17472445/132813944-1cf9a8b3-a87d-42ab-805a-23ad0509e71d.png)

![image](https://user-images.githubusercontent.com/17472445/132813958-4c44d819-1733-4559-af21-6053e5d37eb7.png)

**Comment by yonzhan** [comment]
route to service team

**Comment by yull1860** [comment]
Hi , Any Updates ?

**Comment by panchagnula** [comment]
@Kotasudhakarreddy can you check if this issue?

**Comment by Kotasudhakarreddy** [comment]
Sure will check.

**Comment by panchagnula** [comment]
@Kotasudhakarreddy any update on this?
