### ISSUE TITLE
Listing network security groups fails to list all groups

### ISSUE THREAD

**Issue by D3m1urg3** [Azure/azure-cli#19521]
**Describe the bug**
Suddenly 'az network nsg list' fails to list security groups of newly created resource group for aks cluster. This start happening a week ago and invalidates or cluster deploy scripts as there is no way to retrieve the ngs name in a new cluster in order to add rules.

After a period of time that can be as long as 20 minutes the new resource groups appear when the command is executed.

**To Reproduce**
Create resource group and aks cluster from scratch via bash script using az cli.

Run 'az network nsg list'. Observe that the new groups are not listed.

**Expected behavior**
Up until now the new groups where listed properly.

**Environment summary**
I'm executing az cli command from bash script.

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
It is a know issue and service team is fixing it.

**Comment by D3m1urg3** [comment]
> It is a know issue and service team is fixing it.

Nice. There is an estimate of when it will be fixed?.

**Comment by Stateofminf** [comment]
i

**Comment by kairu-ms** [comment]
Hi @jennyhunter-msft, is there an estimate of when it will be fixed?

**Comment by D3m1urg3** [comment]
Hi.

Seems to me that something has been done here. Now the network security group appears way quickly. However there is a problem still.

When you create an aks cluster using az cli it creates another resouce group automatically "MC_{ResourceGroupName}_{ClusterName}_{region}" and inside this group there is the nsg and other system resources. Why this is created? i don't know. The problem is that when 'az network nsg list' is called the name of this "system" resource group is all in low caps. In all other places in azure portal or otherwise is not. So my script have to try regular name and then low caps.

Is this going to be fixed?

**Comment by phealy** [comment]
The MC resource group is a **m**anaged **c**luster resource group, and is where AKS puts resources that it creates and owns. Generally (with limited exceptions) you should not make changes inside this resource group (NSG rules is currently one of the exceptions). 

Where are you finding resource group name to be case sensitive?

**Comment by D3m1urg3** [comment]
When using the following command:

```az network nsg list --query "[?resourceGroup=='${AKS_SYSTEM_RESOURCE_GROUP}'][].name" | jq -r .[0]```

The security group is all in lowercase, unlike anywhere else on azure. That was not the case a couple of months ago and I fear that this will also change in the future ruining all the scripts depending on it.

The reason I need this is that I want to set inbound rules from my script and the name of the nsg is not predictable as is the mc resource group (for the most part). Hence, I need to query for the name when the cluster is created.

**Comment by phealy** [comment]
I'd suggest passing the resource group to the `--resource-group/-g` argument of `az network nsg list` instead of putting it in JMESPath, as the `-g` comparison isn't case sensitive. It's also a much more efficient query, as it only gets the NSGs in that RG on the server side, instead of getting every NSG in the subscription and filtering on the client. You can use `-o tsv` to output in a non-JSON format without needing to call `jq`.

```shell
$ az network nsg list -g MC_stopcluster_stopcluster_westus2 --query '[].name' -o tsv
aks-agentpool-22870882-nsg

$ az network nsg list -g MC_sToPcLuStEr_stopcluster_westus2 --query '[].name' -o tsv
aks-agentpool-22870882-nsg

$ az network nsg list -g MC_STOPCLUSTER_STOPCLUSTER_WESTUS2 --query '[0].name' -o tsv
aks-agentpool-22870882-nsg

# If you want to make certain you only get one result, like you have in jq:
$ az network nsg list -g MC_sToPcLuStEr_stopcluster_westuS2 --query '[0].name' -o tsv
aks-agentpool-22870882-nsg
```

**Comment by D3m1urg3** [comment]
Thanks @phealy! That will do wonders on making the script less ugly.

**Comment by phealy** [comment]
Seems like we can close this out - let me know if you need anything further.
