### ISSUE TITLE
Support Storage API version 2020-06-12 for Rehydration Update support on SetBlobTier

### ISSUE THREAD

**Issue by fhryo-msft** [Azure/azure-cli#19523]
**Is your feature request related to a problem? Please describe.**
Storage API SetBlobTier starts allowing customers to update rehydration priority in the second call since 2020-06-12. We need CLI to support 2020-06-12 as well, so customers can use the feature via CLI.

**Describe the solution you'd like**
CLI supports Storage API 2020-06-12.

**Describe alternatives you've considered**

**Additional context**
SetBlobTier API: https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-tier#remarks

**Comment by evelyn-ys** [comment]
We only need to bump API version, no interface changed or added, right?
