### ISSUE TITLE
VMSS Flex GA Manage Updates

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#19547]
**Resource Provider**

Microsoft.compute

**Description of Feature or Work Requested**

Targeting 
Complete CLI Update for VMSS Flexible Orchestration Mode for GA

* Update create and manage commands for those that do or don't support VMSS Flex

Link to more detailed change request
https://microsoft.sharepoint.com/:w:/t/vmssvmorchestrationmode/EcHgeCAZFUFIjYhel8EistsB6Rx7LbRT7b1u7DzcgqWjnQ?e=FMxut7

**Minimum API Version Required**

2021-03-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2021-07-01/compute.json

**Target Date**

10/17, to get ready for Ignite conference

**PLR Signoff Link**
https://global.azure.com/signoffs/azureglobal/signoff;id=33104

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele  Since we have planed other projects for this sprint, can we develop and release this requirement in next sprint (for ignite, on **11-02**)?

**Comment by fitzgeraldsteele** [comment]
Is there any way to break up the work and get some of the requirements in now? Maybe possible to do the main quick create experience updates this sprint, and then get the rest of the manage update next sprint, for example?

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele  Yes, that's a good idea~ Because this requirement is large and complex, we can split this requirement into multiple smaller requirement segments. Could you split this large requirement into multiple small feature requests?
And please also tell us the priority of these small requirements and what requirements you want to complete in this sprint, then we will arrange some requirements to be developed and released in this sprint according to the requirements splitting.

**Comment by fitzgeraldsteele** [comment]
Hi. I think the most critical asks: 
    list-instance-connection-info   : Get the IP address and port number used to connect to
                                      individual VM instances within a set.
    list-instance-public-ips        : List public IP addresses of VM instances within a set.

These two are cli convenience functions, and don't have a direct analogy on the API. For these, if the VMSS orchestration mode is 'flexible' we should show a message like. "This command is not available for VMSS in Flexible Orchestration Mode. Use az network commands to retrieve networking information."

list-instances                  : Gets a list of all virtual machines in a VM scale sets.

This one is in the API and returns a response, but it is not super useful to customers at this point. On this, would be good to show a warning or info message to use the single vm az vm list to get VM details.

**Comment by fitzgeraldsteele** [comment]
Hi. I think the most critical asks: 
    list-instance-connection-info   : Get the IP address and port number used to connect to
                                      individual VM instances within a set.
    list-instance-public-ips        : List public IP addresses of VM instances within a set.

These two are cli convenience functions, and don't have a direct analogy on the API. For these, if the VMSS orchestration mode is 'flexible' we should show a message like. "This command is not available for VMSS in Flexible Orchestration Mode. Use az network commands to retrieve networking information."

list-instances                  : Gets a list of all virtual machines in a VM scale sets.

This one is in the API and returns a response, but it is not super useful to customers at this point. On this, would be good to show a warning or info message to use the single vm az vm list to get VM details.

**Comment by fitzgeraldsteele** [comment]
The others throw some kind of reasonable error message from the RP. Can we focus on these few, and tackle the others as needed?

**Comment by zhoxing-ms** [comment]
> list-instance-connection-info : Get the IP address and port number used to connect to
individual VM instances within a set.
list-instance-public-ips : List public IP addresses of VM instances within a set.
These two are cli convenience functions, and don't have a direct analogy on the API. For these, if the VMSS orchestration mode is 'flexible' we should show a message like. "This command is not available for VMSS in Flexible Orchestration Mode. Use az network commands to retrieve networking information."
list-instances : Gets a list of all virtual machines in a VM scale sets.
This one is in the API and returns a response, but it is not super useful to customers at this point. On this, would be good to show a warning or info message to use the single vm az vm list to get VM details.

@fitzgeraldsteele Thank you for your reply and clarification. I will focus on completing these features in ignite.

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele  Thank you for your reply and clarification. I still have two questions to ask you
1. The fixed value setting of two properties should have been completed in public preview, but it has not been implemented yet. Do we need to set these fixed values for Flex VMSS in this GA development?
> overprovisioning must be false for vmss flex preview 
> SPG must be false for VMSS flex 

2. Questions about printing error messages
> if the VMSS orchestration mode is 'flexible' we should show a message like. "This command is not available for VMSS in Flexible Orchestration Mode. Use az network commands to retrieve networking information."
For `az vmss list-instance-connection-info` and `az vmss list-instance-public-ips` commands, if the user queries Flex VMSS, should CLI directly throw the error exception or just print the warning log?

> This one is in the API and returns a response, but it is not super useful to customers at this point. On this, would be good to show a warning or info message to use the single vm az vm list to get VM details.
Is this warning message only for Flex VMSS? If not, I suggest writing this message directly into help. Otherwise, if there is too much data in the list, then user may not see the printed warning message.
