### ISSUE TITLE
Unable to login Az Login

### ISSUE THREAD

**Issue by msaranga** [Azure/azure-cli#19548]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Typed Az Login --debug

throwed following error

cli.azure.cli.core.azclierror: <urllib3.connection.HTTPSConnection object at 0x044321C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
az_command_data_logger: <urllib3.connection.HTTPSConnection object at 0x044321C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Following is Az version
C:\WINDOWS\system32>az version
{
  "azure-cli": "2.28.0",
  "azure-cli-core": "2.28.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "databricks": "0.7.2"
  }
}

**To Reproduce**
 Run az login

**Expected behavior**
Need to get authenticated and get access token to my subscription

**Environment summary**
On my Local Machine.

**Additional context**

My Machine in Corp Network and it is in Seattle US. I believe request should gone to westus2 of arm region. 
While looking into logs, Az login is internally calling https://eastus2euap.management.azure.com/tenants?api-version=2019-11-01

When we call above URL (https://eastus2euap.management.azure.com/tenants?api-version=2019-11-01), we see cli.azure.cli.core.azclierror: <urllib3.connection.HTTPSConnection object at 0x044321C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
az_command_data_logger: <urllib3.connection.HTTPSConnection object at 0x044321C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Why is it going to eastus2euap instead of management.azure.com?

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
I tested and it seems https://eastus2euap.management.azure.com/ is indeed not responding.

```
> curl https://eastus2euap.management.azure.com --connect-timeout 5
curl: (28) Connection timed out after 5016 milliseconds
```

I believe you have registered your own cloud with `az cloud register`. You may check your current cloud setting with `az cloud show`:

```
> az cloud show
{
  "endpoints": {
    ...
    "resourceManager": "https://management.azure.com/",
    ...
  "name": "AzureCloud",
```

- If you are on another cloud, change to `AzureCloud` with `az cloud set --name AzureCloud`.
- If you are on `AzureCloud` with modified settings, you may delete `~/.azure/clouds.config` to revert to default.

**Comment by msaranga** [comment]
@jiasli : Yes, I have modified clouds.config endpoint to management.azure.com instead of canary region. Things started working. It was very difficult to identify az login getting failed. Probably because canary drill, eastus2euap.management.azure.com is not working

**Comment by jiasli** [comment]
> It was very difficult to identify az login getting failed.

You may simply use `--debug` in the command which is design explicitly for troubleshooting issues during command execution.
