### ISSUE TITLE
Different errors for what-if and create

### ISSUE THREAD

**Issue by t-dedah** [Azure/azure-cli#19540]
**Describe the bug**

One of our customers is getting two separate errors when using what-if and create for subscription level deployments.
1.  Is this an expected outcome?
2.  If no then what can be done to solve this?

https://github.com/Azure/cli/issues/43

> Today i did try to deploy a Private Link endpoint en was getting the following error when deploy with:
> 
> az deployment sub what-if --template-file .\Azure.bicep --location 'west europe' --parameters @Azure.parameters.json
> 
> error:
> 
> "error": {
> "code": "InvalidRequestFormat",
> "message": "Cannot parse the request.",
> "details": []
> 
> And this is the error what az command gives:
> 
> DeploymentWhatIfResourceInvalidResponse - The request to predict template deployment changes to scope '/subscriptions/' has failed due to missing or unexpected response on request '/subscriptions//resourceGroups//providers/Microsoft.Network/privateEndpoints//privateDnsZoneGroups/dnsgroupname?api-version=2021-02-01'. Diagnostic information: timestamp '20210706T182248Z', tracking id '', request correlation id '', location 'westeurope'.
> 
> but when deploy with:
> 
> az deployment sub create --template-file .\Azure.bicep --location 'west europe' --parameters @Azure.parameters.json
> 
> getting this error:
> ```json
>     {
>         "code": "DeploymentFailed",
>          "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see 
>           https://aka.ms/DeployOperations for usage details.",
>          "details": [
>          { 
>                    "code": "MoreThanOnePrivateDnsZoneGroupPerPrivateEndpointNotAllowed",
>                    "message": "Cannot create more than one private dns zone groups in the private endpoint tm-aws-prod-pl01. Current private dns zone group count: 2."
>           }]
>       }
> ```

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by zhoxing-ms** [comment]
@shenglol It seems related to the output of what-if, could you please help to have a look at this issue?

**Comment by shenglol** [comment]
Will take a look.

**Comment by Stateofminf** [comment]
Or

**Comment by shenglol** [comment]
@t-dedah Do you mind sharing the template the customer used? It would be great if you can email it to me at shenglol@microsoft.com

**Comment by t-dedah** [comment]
@shenglol Forwarded you the template files.

**Comment by shenglol** [comment]
I was not reproduce this with the templates on my machine, though I had to modify them a bit and change some parameters. Also, I could find any thing helpful in our logs since logs will only be kept for 2 months and the request was done was done over 2 months ago. Can we check with the customer to see if they are still seeing the same error?

**Comment by t-dedah** [comment]
Ill the customer if he is still facing this issue. https://github.com/Azure/cli/issues/43

**Comment by t-dedah** [comment]
Closing this issue due to no response from customer.
