### ISSUE TITLE
Get error when running az aks check-acr in AzureChinaCloud

### ISSUE THREAD

**Issue by susanandwang** [Azure/azure-cli#19556]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When trying to run the command az aks check-acr in AzureChinaCloud, get the following error:

Getting managed identity token failed with: failed to refresh ARM access token: Metadata endpoint returned error status: 400. body: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://management.azure.com/ was not found in the tenant named xxxxxx. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

**To Reproduce**
This issue is found in both version 2.26.1 and 2.28.0.

Run the command az aks check-acr.

**Expected behavior**
This error should not happen.

**Environment summary**
Centos 8

**Additional context**
NA

**Comment by yonzhan** [comment]
route to service team

**Comment by susanandwang** [comment]
I tested in az CLI version 2.30.0, and it seems that this issue has been fixed.
