### ISSUE TITLE
Bug in Publish Azure Function with Core Tools

### ISSUE THREAD

**Issue by JoseACastilloH** [Azure/azure-cli#19552]
## Describe the bug

**Command Name**
`az functionapp create`

**Errors:**
```
no supported --runtime-version found for the selected --runtime node and --functions-version 2

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp create --resource-group {} --name {} --storage-account {} --runtime {} --consumption-plan-location {} --functions-version {}`

## Environment Summary
```
Linux-5.4.0-1058-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@JoseACastilloH Apologies for the late reply. Could you please let us know the command that you executed along with the values that were passed to the parameters ? Please let us know if you are still facing the same issue. Awaiting your reply.
