### ISSUE TITLE
arm64 Debian bullseye apt package does not work, seems to be x86 version

### ISSUE THREAD

**Issue by Chuxel** [Azure/azure-cli#19567]
**Describe the bug**
It looks like the arm64 Debian bullseye apt package is either the x86 version or has a bad dependency. Trying to use the CLI after installing causes it to bomb with the following error:

```
/lib64/ld-linux-x86-64.so.2: No such file or directory
```

This affects arm64 Linux devices and Docker images on M1 macs. I assume this would also affect WSL on a Windows ARM device.

**To Reproduce**
1. With Docker Desktop installed, create the following Dockerfile:
    ```
    FROM buildpack-deps:bullseye-curl
    RUN . /etc/os-release \
        && curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/microsoft-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/azure-cli/ ${VERSION_CODENAME} main" > /etc/apt/sources.list.d/azure-cli.list \
        && apt-get update \
        && apt-get install -y azure-cli
    ```
2. Run `docker build --platform linux/arm64 -t az-cli-bullseye-test .` in a terminal in the folder with the Dockerfile to build the image for arm64
3. Run `docker run --platform linux/arm64 -it --rm az-cli-bullseye-test az` to run the Azure CLI in the container (emulated as arm64 if you are on a x86 device)

**Expected behavior**
Normal Azure CLI help text appears

**Actual behavior**
Errors complaining about a x86 library path:
```
/lib64/ld-linux-x86-64.so.2: No such file or directory
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by Chuxel** [comment]
//cc: @joshspicer as FYI

**Comment by Chuxel** [comment]
EDIT: I also see the following error now:

```
/usr/bin/az: line 3: /usr/bin/../../opt/az/bin/python3: No such file or directory
```

**Comment by jiasli** [comment]
As you saw in #7368, ARM64 is currently not supported. You could use `pip` to install Azure CLI: https://github.com/Azure/azure-cli/issues/7368#issuecomment-864817687

For the error:

```
/usr/bin/az: line 3: /usr/bin/../../opt/az/bin/python3: No such file or directory
```

`/usr/bin/az` is the entry script created by the `deb` package.

You may remove the previous installation first:

```
apt remove azure-cli
```

`pip` on the other hand will create the entry script at

```
# command -v az
/usr/local/bin/az
```

**Comment by Chuxel** [comment]
In this case, there seems to be a package and it gets installed, but is wrong.  (This didn't seem to be one from debian.) There was no azure-cli installed previously since this was in a fresh Dockerfile.

If this isn't expected to work at all, then I guess we can close - however, isn't the pip install not recommended?

**Comment by jiasli** [comment]
> In this case, there seems to be a package and it gets installed, but is wrong.

As I tested, `buildpack-deps:bullseye-curl` doesn't seem have an `az` entry script. Could you share your `Dockerfile` you used to install Azure CLI from `pip`?

I tried to create a docker image with `Dockerfile`:

```dockerfile
FROM buildpack-deps:bullseye-curl
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip install azure-cli
```

```
docker build --platform linux/amd64 -t az-cli-bullseye-test .
```

The image works as expected: 

```
> docker run --platform linux/amd64 -it --rm az-cli-bullseye-test az --version
azure-cli                         2.28.1

core                              2.28.1
telemetry                          1.0.6

Python location '/usr/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

A even easier approach is to use the `python` docker image:

```dockerfile
FROM python:bullseye
RUN pip install azure-cli
CMD bash
```

**Comment by Chuxel** [comment]
Yeah pip is an option, it's just slow, and [this comment indicated not recommended](https://github.com/Azure/azure-cli/issues/7368#issuecomment-900781603).  We can do that tactically.

**Comment by jiasli** [comment]
Perhaps I need to change my wording. It is _less_ recommended compared to the `apt` option, but it is still the only solution on unsupported platforms.

**Comment by jjgriff93** [comment]
@jiasli why does the az cli get listed with ARM64 variants in the [packages repository](https://packages.microsoft.com/repos/azure-cli/dists/bullseye/) if it isn't supported? As @chuxel rightly points out you're led to believe it should work due to apt pulling an 'arm64' and installing successfully, only to find out it doesn't when you run a command.

**Comment by antoniogeko** [comment]
I've wasted hours because what @jjgriff93 pointed out. Please, if there is no deb package arm64 version, the deb arm64 should be removed from the package repository...

**Comment by EmbeddedAndroid** [comment]
Any update on this? This is an easy packaging fix. Is ARM not a supported platform for IoT edge?

**Comment by bebound** [comment]
It should be fixed by https://github.com/Azure/azure-cli/pull/24180
