### ISSUE TITLE
First example on this page requires the --use-k8s flag

### ISSUE THREAD

**Issue by chrisadkin-zz** [Azure/azure-cli#19564]
The first example on this page requires the --use-k8s flag in order to work, per this error message:

For indirect connectivity mode, please include the [--use-k8s] argument.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53cc4830-ab2e-6f3a-2928-837a986027e9
* Version Independent ID: 8747ea08-2b72-e518-018c-2118dd070c8f
* Content: [az arcdata dc](https://docs.microsoft.com/en-us/cli/azure/arcdata/dc?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/arcdata/dc.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/arcdata/dc.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
@chrisadkin-zz 
Its now included 
az arcdata dc create --name name --k8s-namespace namespace --connectivity-mode indirect --resource-group group  --location location --subscription subscription **--use-k8s**

and document also mentions it as required.
--use-k8s
[Required] Create data controller using local Kubernetes APIs.
