### ISSUE TITLE
VMSS Flex GA Create Updates

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#19578]
**Resource Provider**

Microsoft.compute

**Description of Feature or Work Requested**

Per discussion in issue #19547 , breaking the request up into 2. This one is removing preview tags, updating the defaults to enable a quick, easy create experience similar to what we have with VMSS Uniform today
* Add support to quick create experiences for flexible orchestration mode like:

`az vmss create -n MyVmss -g MyResourceGroup --image MyImage – orchestration-mode flexible`

* Update defaults for NetworkAPIVersion when creating VMSS Flex
* Remove preview tags for networkApiVersion, orchestrationMode

See doc:
https://microsoft.sharepoint.com/:w:/t/vmssvmorchestrationmode/EcHgeCAZFUFIjYhel8EistsB6Rx7LbRT7b1u7DzcgqWjnQ?e=SbGIKQ

**Minimum API Version Required**

2021-03-01

**Swagger Link**

**Target Date**

10/17

**Comment by fitzgeraldsteele** [comment]
Per discussion in #19547 , breaking this up into two. If there is any way to get this one in for the 10/17 sprint, I would prioritize this one. Thank you! Happy to answer any questions

**Comment by yonzhan** [comment]
VMSS Flex GA

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele  Thank you for helping to create this subdivided requirement. I have three questions with the description document of this requirement:

1. Is the SKU used by flexible VMSS related to the user's cloud?
As for uniform VMSS, when the user's cloud is not `AzureUSGovernment`, the SKU used is `Standard_DS1_v2`. When the cloud is `AzureUSGovernment`, then the SKU used is `Standard_D1_v2`.
However, the document only says that the SKU of flexible VMSS is `Standard_DS1_v2`. Do we need to keep cloud related logic for flexible VMSS?

2. I'd like to confirm with you what the `manual upgrade mode` means? My understanding is that it may be the `upgrade policy mode`, right?

3. May I ask the single placement group can only be `False` for flexible VMSS? 
If so, when the `--single-placement-group` passed in by the user is `True` for flexible VMSS, should we raise an error to let users input the `Ture` for the single placement group?
In addition, when the users do not pass in the `--single-placement-group` parameter, should we set the single placement group to `False` for flexible VMSS, or we do not need to set this property?

**Comment by fitzgeraldsteele** [comment]
Is the SKU used by flexible VMSS related to the user's cloud?
_fisteele: Yes, please keep the same logic for default sku. I wasn't aware Gov cloud was different. THank you_

I'd like to confirm with you what the manual upgrade mode means?
_fisteele: correct. In the template, do not pass the upgradepolicy block. It is not yet available for VMSS flex, and deployment will fail._ 
Similar for:
* LBNatInboundPools
* Overprovision

If so, when the --single-placement-group passed in by the user is True for flexible VMSS, should we raise an error to let users input the False for the single placement group?
_fisteele I'm ok if you pass through the singlePlacementGroup parameter - the API will reject requests. As long as the default for VMSS Flex is singlePlacemetnGroup=false_


In addition, when the users do not pass in the --single-placement-group parameter, should we set the single placement group to False for flexible VMSS, or we do not need to set this property?
_fisteele Only for VMSS Flex for now, please. We have some ongoing work that will allow us to set the default to 'false' for all deployments, but we're not quite there yet._

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele  Thank you for your quick reply. So when users create flexible VMSS without passing in the parameter `--single-placement-group`, we will set the default value to `False` for single placement group, right?

**Comment by fitzgeraldsteele** [comment]
That's correctly. Similarly, set default value for --network-api-version to '2020-11-01'



Jerry
Steele
Microsoft
senior program manager
425.421.2566


________________________________

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele I encountered a service error in the process of development, could you find relevant developers to help me investigate the reason?

The error information are as follows:

x-ms-correlation-request-id: 9124bc9b-1b15-49c5-ba71-13a290d72bb5

Response body: 
```json
{
	"status": "Failed",
	"error": {
		"code": "DeploymentFailed",
		"message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
		"details": [{
			"code": "BadRequest",
			"message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"Required parameter 'platformFaultDomainCount' is missing (null).\",\r\n    \"target\": \"platformFaultDomainCount\"\r\n  }\r\n}"
		}]
	}
}
```

**Comment by fitzgeraldsteele** [comment]
That is as designed. Platform fault domain count is required param for vmss flex

**Comment by fitzgeraldsteele** [comment]
Default to platformFaultDomainCount=1

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele `computerNamePrefix`  has the same problem.
Error information
```json
{
	"status": "Failed",
	"error": {
		"code": "DeploymentFailed",
		"message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
		"details": [{
			"code": "BadRequest",
			"message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"Required parameter 'computerNamePrefix' is missing (null).\",\r\n    \"target\": \"computerNamePrefix\"\r\n  }\r\n}"
		}]
	}
```

Do we also need to give a default value to `computerNamePrefix`?

**Comment by fitzgeraldsteele** [comment]
Yes, please:

For windows deployments, default to first 8 chars of the VMSS name
For linux deployments, default to first 55 chars of VMSS name

We append 9 char unique string to the computer name. Windows and linux have different computername lengths. <https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftcompute>


[cid:69b09016-4180-413e-a6c4-7fa38dac46cf]


Jerry
Steele
Microsoft
senior program manager
425.421.2566


________________________________

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele Could we simplify the logic of getting `computerNamePrefix`? Such as taking the first 8 characters of VMSS name in all operating systems? In this way, our code implementation will be simpler

**Comment by fitzgeraldsteele** [comment]
That's fine, as long as customer can override. Thank you!



Jerry
Steele
Microsoft
senior program manager
425.421.2566


________________________________

**Comment by zhoxing-ms** [comment]
> We need to add the ability to quickly create with VMSS Flexible Orchestration, like 
Create a Linux VM scale set in flexible orchestration mode using the default existing public SSH key. 
        az vmss create -n MyVmss -g MyResourceGroup --image MyImage – orchestration-mode flexible 

@fitzgeraldsteele Hi, in the scenario of quickly creating VMSS from your doc, because network and other related resources will be created in this scenario, do users have to pass in the `--image` parameter?

I found that the command `az vmss create` does not need the `--image` parameter when only creating the resource `Microsoft.Compute/virtualMachineScaleSets`, but if the network and other dependent resources are added for creation, the following error will appear:
```
{
	"status": "Failed",
	"error": {
		"code": "DeploymentFailed",
		"message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
		"details": [{
			"code": "BadRequest",
			"message": "{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Virtual Machine Scale Set with orchestration mode 'Flexible' and a Virtual Machine profile must use managed disks.\"\r\n  }\r\n}"
		}]
	}
}
```

**Comment by fitzgeraldsteele** [comment]
Image should have the same default as vmss create does today. If image is required parameter now then let's keep that.

Both vmss uniform today and vmss flex should default to using managed disks. However flex will fail if unmanaged disks are used.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zhoxing-ms** [comment]
In fact, the Flex VMSS can be successfully created without `virtualMachineProfile` and `storageProfile`, such as:
```json
{
    "properties": {
        "template": {
            "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#", 
            "contentVersion": "1.0.0.0", 
            "parameters": { }, 
            "variables": { }, 
            "resources": [
                {
                    "type": "Microsoft.Compute/virtualMachineScaleSets", 
                    "name": "vmss1", 
                    "location": "westus", 
                    "tags": { }, 
                    "apiVersion": "2021-04-01", 
                    "dependsOn": [ ], 
                    "properties": {
                        "singlePlacementGroup": false, 
                        "platformFaultDomainCount": 3, 
                        "proximityPlacementGroup": {
                            "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_vmss_orchestration_mode_000001/providers/Microsoft.Compute/proximityPlacementGroups/ppg1"
                        }, 
                        "orchestrationMode": "Flexible"
                    }
                }
            ], 
            "outputs": {
                "VMSS": {
                    "type": "object", 
                    "value": "[reference(resourceId(''Microsoft.Compute/virtualMachineScaleSets'', ''vmss1''),providers(''Microsoft.Compute'',''virtualMachineScaleSets'').apiVersions[0])]"
                }
            }
        }, 
        "parameters": { }, 
        "mode": "incremental"
    }
}
```

Therefore, we can create Flex VMSS without specifying the disk/image to use, and there is no default disk/image. 

However, if network and other dependent resources are added, the following error will be reported if the disk/image is not specified:
```
{
	"status": "Failed",
	"error": {
		"code": "DeploymentFailed",
		"message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
		"details": [{
			"code": "BadRequest",
			"message": "{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Virtual Machine Scale Set with orchestration mode 'Flexible' and a Virtual Machine profile must use managed disks.\"\r\n  }\r\n}"
		}]
	}
}
```
Therefore, my current idea is that the settings of these default dependent resources and attributes only take effect when the `--image` parameter is passed in (and the disk is also specified), otherwise it will break the original usage of creating only Flex VMSS and not other resources
![Screenshot 2021-09-30 101131](https://user-images.githubusercontent.com/16612065/135374518-1be54db9-79e4-46a1-b151-254329cfe805.png)
Do you think this idea is feasible?

**Comment by fitzgeraldsteele** [comment]
So if customer specifies --image, then we will make the dependent resources (networking, storage, sku, etc). We have defaults for those dependent resources, which the customer can override. That makes sense to me. Thank you for looking into this!



Jerry
Steele
Microsoft
senior program manager
425.421.2566


________________________________

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele You can use the latest release branch code of CLI in dev environment, or wait until **11-02** to use the latest version of official CLI
