### ISSUE TITLE
`az login` fails with "certificate verify failed: unable to get local issuer certificate"

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#19571]
## Symptom

Azure CLI is configured to use a proxy as specified by the `HTTPS_PROXY` environment variable.

After logging into https://login.microsoftonline.com/, Azure CLI fails with 

```
HTTPSConnectionPool(host='login.microsoftonline.com', port=443):
Max retries exceeded with url: /common/oauth2/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)')))
```

**Comment by jiasli** [comment]
## Cause

This is because the proxy intercepts Azure CLI's HTTPS traffic, decrypts and re-encrypts it with its own certificate, but **the proxy can't return all intermediate and root CA certificates**, leading to the failure.

## Solution

**All intermediate and root CA certificates** should be added to `cacert.pem` following https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#work-behind-a-proxy

## References

- Unable to get local issuer certificate when using requests in python: https://stackoverflow.com/questions/51925384/unable-to-get-local-issuer-certificate-when-using-requests-in-python
- Export & Download — SSL Certificate from Server (Site URL): https://medium.com/@menakajain/export-download-ssl-certificate-from-server-site-url-bcfc41ea46a2

**Comment by Sanjib-Chowdhury** [comment]
Hi,

Try this & share the outcome -

1. convert the Sever certificate from .cer/ .crt to .pem (if not using proxy)/ proxy certificate (if using proxy) using OpenSSL/ Portecle or similar tools. Just renaming the certificate won't work.
2. Download run the script from https://github.com/Sanjib-Chowdhury/407-proxy-authentication-required-CERTIFICATE_VERIFY_FAILED-from-AWS-Azure-Git-NPM-CLI

**Comment by jiasli** [comment]
@Sanjib-Chowdhury, thanks for the script. 

### ⚠️ For anyone else, please be aware this script is not provided by Microsoft. Please use it with caution!
