### ISSUE TITLE
Subscription?

### ISSUE THREAD

**Issue by MikeGBurns** [Azure/azure-cli#19589]
Is --subscription a valid parameter?  2.28.0 seems ok with it.

If so, please update docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa2d288d-9ff4-a51c-3f30-1d79ea6564ab
* Version Independent ID: 4483e7d2-49f0-c2f4-afa2-3d7137ea70be
* Content: [az logic workflow](https://docs.microsoft.com/en-us/cli/azure/logic/workflow?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/logic/workflow.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/logic/workflow.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
subscription is an optional parameter & can be used if you want to run commands on the non active or default subscription being used by azure-cli client.
