### ISSUE TITLE
webapp:`webapp config access-restriction add` authorization failing for subnet ID under different subscription

### ISSUE THREAD

**Issue by joshRooz** [Azure/azure-cli#19588]
## Describe the bug

**Command Name**
`az webapp config access-restriction add`

**Errors:**
```
Operation returned an invalid status 'Bad Request'
```

**Logging Snippet:**
Note that sensitive values have been redacted.
```json
  "Code": "BadRequest",
  "Message": "IpSecurityRestriction.VnetSubnetResourceId is invalid.  For request GET https://management.azure.com/subscriptions/{}/resourceGroups/{}/providers/Microsoft.Network/virtualNetworks/{}/taggedTrafficConsumers?api-version=2018-01-01 with clientRequestId {} and correlationRequestId {}, received a response with status code Forbidden, error code AuthorizationFailed, and response content: {\"error\":{\"code\":\"AuthorizationFailed\",\"message\":\"The client '{}' with object id '{}' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/taggedTrafficConsumers/read' over scope '/subscriptions/{}/resourceGroups/{}/providers/Microsoft.Network/virtualNetworks/{}' or the scope is invalid. If access was recently granted, please refresh your credentials.\"}}. Request content was ",
  "Target": null,
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Owner role assigned to both subscriptions (*not a recent assignment in this instance*)
- `az account login --tenant {}`
- `az account set --subscription {}`
- `az webapp config access-restriction add -i --name {} -g {} --priority {} --action {} --rule-name {} --subnet {}` where the subnet argument provided is the full subnet resource ID

## Expected Behavior
Creation of access restriction rule that would allow VMs in a cross-subscription subnet to access the API App.

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

Extensions:
monitor-control-service 0.2.0
automation 0.1.0
subscription 0.1.4
datafactory 0.4.0
azure-devops 0.18.0
ip-group 0.1.2
kusto 0.3.0
resource-graph 2.0.0
azure-firewall 0.12.0
portal 0.1.1

```
## Additional Context
- Service endpoint has been enabled on the cross-subscription subnet. 
- Subnet resource ID obtained from `az network vnet subnet list -g {} --vnet-name {}` and copy/pasted
- Encountered the issue on azure-cli 2.27.0 as well

**Comment by yonzhan** [comment]
route to service team

**Comment by suwatch** [comment]
@joshRooz  could you please provide the UTC time and correationId of the failing request/operation?

**Comment by joshRooz** [comment]
Thanks @suwatch and yep -
* Thu, 16 Sep 2021 21:37:24 GMT
* Request header `x-ms-correlation-request-id` - c7752b35-ee20-4a8c-abe3-151447138b03
* `correlationRequestId` in the response - cafbd6bc-996c-47dc-8abc-0995d0eba257

**Comment by suwatch** [comment]
Try to create a free dummy App Service on subscription (91de...bd5a) owning vnet and retry the operation - see if that helps.   

The issue seems to be the subscription in question does not have Microsoft.Web (App Service Resource Provider) registered; as a result, all VNET operations are not properly granted to the provider.   The work around is to register provider.   This can be done implicitly by creating an App Service Resource (FREE or any) on a given subscription.

**Comment by joshRooz** [comment]
That was it. Thank you very much!

**Comment by madsd** [comment]
@joshRooz would you mind closing the issue.

Thanks.
