### ISSUE TITLE
AAD app delete: "Value cannot be null"

### ISSUE THREAD

**Issue by dkisselev** [Azure/azure-cli#19608]
## Describe the bug

`az ad app` cli returns a value error when trying to delete certain apps.

#18738 reported the same problem but the reporter found a workaround and closed the issue - the bug is still present in the CLI.
I can provide sample app ID's internally for testing/repro.

**Command Name**
`az ad app delete`

**Errors:**
```
Value cannot be null.
Parameter name: requestContext
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az ad app delete --id {}`

## Expected Behavior

The app is deleted.

The same command successfully deletes some, but not all other apps in my environment.

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.27.0 *

Extensions:
azure-iot 0.10.9
aks-preview 0.5.25
azure-devops 0.16.0
interactive 0.4.4

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
`az ad` is now out of maintenance, and we don't keep the interoperability between `az ad` and Azure Portal. Please see https://github.com/Azure/azure-cli/issues/18738#issuecomment-875548675 as the solution.

The migration from AD Graph to MS Graph is tracked at https://github.com/Azure/azure-cli/issues/12946.

**Comment by brad-lucas** [comment]
@jiasli `az ad` isn't a supported Azure CLI module anymore? The comment from Sep 19 seems to imply that this will never be fixed.

**Comment by jiasli** [comment]
Please see the solution at https://github.com/Azure/azure-cli/issues/18738#issuecomment-875548675.

> `az ad` isn't a supported Azure CLI module anymore?

We are migrating the underlying API of `az ad` to Microsoft Graph. Then it will be actively supported again. Stay tuned!
