### ISSUE TITLE
Az Cli does not support using AES for encrypt/decrypt when using Managed HSM

### ISSUE THREAD

**Issue by x509cert** [Azure/azure-cli#19600]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
AKV and MHSM both support the ability to ecrypt/decrypt using asymmetric keys (RSA), but MHSM also supports using AES keys. Using the Az CLI with MHSM I can encrypt/decrypt using RSA, but if I use AES, this raises an error even though MHSM supports AES. The same AES encrypt process works fine when using the Azure SDK and C#. 

**To Reproduce**
TYPE:
az login
 az keyvault key encrypt --algorithm oct-hsm --value 1234 --data-type plaintext --name testingtesting123 --hsm-name MHSMDemoInstance

ERROR:
az keyvault key encrypt: 'oct-hsm' is not a valid value for '--algorithm'. Allowed values: RSA-OAEP, RSA-OAEP-256, RSA1_5

Note the algs are ONLY RSA, there's no AES or OCT or OCT-HSM (OCT is AES in this instance)

**Expected behavior**
The cli should return a JSON file with the ciphertext and no error msg.

**Environment summary**
Using Azure Portal Shell, PS.
azure-cli is 2.28.0
core is 2.28.0

**Additional context**
Please note that this process, encrypting with AES, works correctly from C#

using Azure.Security.KeyVault.Keys.Cryptography;
using Azure.Identity;
using Azure.Security.KeyVault.Keys;
using System.Text;

string managedHsmUrl = @"https://xxxxxxxxx.managedhsm.azure.net";

var managedHsmClient = new KeyClient(new Uri(managedHsmUrl), new DefaultAzureCredential());

var octKeyOptions = new CreateOctKeyOptions($"OctKey-{Guid.NewGuid()}") {
    KeySize = 256,
};

KeyVaultKey cloudOctKey = managedHsmClient.CreateOctKey(octKeyOptions);

var cryptoClient = new CryptographyClient(cloudOctKey.Id, new DefaultAzureCredential());

byte[] plaintext = Encoding.UTF8.GetBytes("Some data to encrypt");
byte[] aad = Encoding.UTF8.GetBytes("additional authenticated data");

EncryptParameters encryptParams = EncryptParameters.A256GcmParameters(plaintext, aad);
EncryptResult encryptResult = cryptoClient.Encrypt(encryptParams);

DecryptParameters decryptParams = DecryptParameters.A256GcmParameters(
    encryptResult.Ciphertext,
    encryptResult.Iv,
    encryptResult.AuthenticationTag,
    encryptResult.AdditionalAuthenticatedData);

DecryptResult decryptResult = cryptoClient.Decrypt(decryptParams);

**Comment by yonzhan** [comment]
keyvault

**Comment by x509cert** [comment]
@yonzhan technically, the issue lies with Managed HSM, not Key Vault... same team, different product..

**Comment by yonzhan** [comment]
@x509cert for adding label purpose, we only mark the bigger module/family:)
