### ISSUE TITLE
Azure CLI support for VM Hibernate feature

### ISSUE THREAD

**Issue by pavanrachapudy** [Azure/azure-cli#19611]
**Resource Provider**
Microsoft.Compute

**Description of Feature or Work Requested**
This request is for VM hibernate feature. Feature can be divided into two parts:
1.	As part of Create/Update VM, customers should be able to pass hibernationEnabled intent as part of additional capabilities.
2.	As part of Hibernating VM, passing hibernate query parameter as part of Deallocate operation
Design doc - [https://microsoft.sharepoint.com/:w:/r/teams/ComputeVM/_layouts/15/Doc.aspx?sourcedoc=%7B7468e5aa-fae0-440c-be50-4cec49af7aa9%7D&action=edit&wdPid=44260826&cid=e4086670-d549-43ea-948a-14af9097ca3b&share=IQGq5Wh04PoMRL5QTOxJr3qpAT-gQNgLpN_7JeLKVCCSKT8](url)

**Minimum API Version Required**
2021-03-01

**Swagger Link**
PR link - [https://github.com/Azure/azure-rest-api-specs/pull/15067](url)
References in main branch:
[https://github.com/Azure/azure-rest-api-specs/blob/f7bdc95b45115dd1d5d7aec82d1b88ea17a938a7/specification/compute/resource-manager/Microsoft.Compute/stable/2021-07-01/compute.json#L11066](url)
[https://github.com/Azure/azure-rest-api-specs/blob/f7bdc95b45115dd1d5d7aec82d1b88ea17a938a7/specification/compute/resource-manager/Microsoft.Compute/stable/2021-07-01/compute.json#L3436](url)

**Target Date**
Targeting public preview by Nov 2021

**Comment by yonzhan** [comment]
feature ask

**Comment by zhoxing-ms** [comment]
@pavanrachapudy As I'm on a long holiday, I'm sorry for the late reply. At present, we have arranged many high priority requirements in ignite (11-02), so we may not have enough time to develop and release this requirement in the next sprint. May I ask we plan to complete its development and release in December, is this date acceptable?

**Comment by pavanrachapudy** [comment]
@zhoxing-ms Thanks for the reply. Do have an approximate date for this release. We have public preview planned around 1st week of december. If it's around that time frame, then it should be fine.

**Comment by pavanrachapudy** [comment]
@zhoxing-ms Wondering if this is available to test?

**Comment by zhoxing-ms** [comment]
@pavanrachapudy You can pull the latest code from the remote dev branch and test it with the development environment. Guidance documents: https://github.com/Azure/azure-cli-dev-tools#setting-up-your-development-environment

We will officially release it on **12-07**

**Comment by zhoxing-ms** [comment]
@pavanrachapudy Or you can try the private package from edge build [package link](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1192558&view=artifacts&pathAsName=false&type=publishedArtifacts)
