### ISSUE TITLE
[Compute] Unable to create VM using existing OS disk

### ISSUE THREAD

**Issue by lwilts** [Azure/azure-cli#1961]
The --os-disk-vhd option from the xplat CLI is no longer available. This makes restoring VMs from OS disk snapshots impossible. Being able to create a new VM using an existing OS disk blob should be a basic requirement.
(Using --image and the existing VHD doesn't work).

**Comment by devigned** [comment]
@lwilts this script (https://github.com/devigned/azure-cli-samples/blob/master/vm-custom-vhd/vm-custom-vhd#L68-L71) uses --image to create a VM from a custom vhd. Does this demonstrate the functionality you are referring to?

**Comment by tjprescott** [comment]
Yes, `--image` can be an URN, URI to an existing VHD or an URN alias. Please try using your VHD URI for the `--image` field.

**Comment by tjprescott** [comment]
> (Using --image and the existing VHD doesn't work).

I just saw this--what error do you get when you use the URI for your VHD?

**Comment by lwilts** [comment]
I'm getting some other error about subscription limits - but it's prompting for an admin password, implying that it will try to clone the image to create a 'fresh' one, rather than simply attaching the existing VHD - is that what you meant?

**Comment by tjprescott** [comment]
Hi @lwilts, I've looked into this and here are a couple things to note:

1. You must specify an image for a properly generalized OS VHD. Please see: https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-capture-image
2. As noted in that article, you must create the VM with the same storage account that the generalized VHD is in. If the storage account is in a different resource group from where you want to create the VM, you would need to specify the fully qualified ID for the `--storage-account` property (I will open an issue to simplify this. Ideally you shouldn't have to specify the storage account at all for this scenario.)
3. HOWEVER, currently if you try that, you will get an error that the OS VHD name is not a System.URI. I will have a bug fix out for that today.

**Comment by lwilts** [comment]
Thanks for that explanation - but what I'm trying to do is simply attach the disk to the new VM, not clone it as if it were a generalised/gold image. This is the result of using the --os-disk-vhd in the xplat.

**Comment by tjprescott** [comment]
Okay, I see. Currently, that is not a supported scenario in the CLI. You either specify a URN or a URI to a generalized image and end up with a new OS disk.

We will look at adding this in the near future. Thanks for the feedback!

**Comment by tjprescott** [comment]
@yugangw-msft since you are doing work to add different OS profiles, could you add support for this at the same time? I thought about doing it but realized it would likely conflict with your major changes.

My thoughts are that we could make `--image` optional, change `--os-disk-name` to `--os-disk` and the help would essentially be "The OS disk name to use when creating a new OS disk from an image, or an existing VHD URI to use for the OS disk."  Apparently this is a supported feature in Xplat, so we should support it as well for GA.

**Comment by yugangw-msft** [comment]
with #1977, this becomes possible 
```bash
   az disk create --source-blob-uri -g myrg -n mySpecializedOsDisk
   az vm  --managed-os-disk mySpecializedOsDisk
```

**Comment by yugangw-msft** [comment]
@tjprescott, I will chat with CRP team for whether we should still support attaching to unmanaged disk directly.

**Comment by tjprescott** [comment]
> with #1977, this becomes possible
>    az disk create --source-blob-uri -g myrg -n mySpecializedOsDisk
>    az vm  create --managed-os-disk mySpecializedOsDisk --os-type ...

However, this only applies to managed disks, correct?

**Comment by yugangw-msft** [comment]
@tjprescott, that is correct. So far, only attaching to a managed os disk is supported
