### ISSUE TITLE
az repos show --id  ... 'repos' is misspelled or not recognized by the system.

### ISSUE THREAD

**Issue by Anandharajv** [Azure/azure-cli#19627]
## Describe the bug

**Command Name**
`Unknown`

**Errors:**
```
'repos' is misspelled or not recognized by the system.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az repos show --id --org {} --project {} -r {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

```

**Comment by jsntcy** [comment]
@Anandharajv, from the error, it seems you machine didn't install the extension "azure-devops" which contains the command group `az repos`, please run the command `az extension add -n azure-devops` to install the extension first, then try the command `az repos show --id --org {} --project {} -r {}` again to see if it resolves the issue.

You can also config to install extensions automatically in the future following the doc [here](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview#install-extensions-automatically]

**Comment by RakeshMohanMSFT** [comment]
@Anandharajv Hope you doing good. Can you please help us understand if the solution provided by @jsntcy resolved your issue?

Awaiting for your response.
