### ISSUE TITLE
Install Site Extension returns 400 Bad Request

### ISSUE THREAD

**Issue by colin-higgins** [Azure/azure-cli#19624]
**Describe the bug**
The Try It feature of the `installsiteextension` endpoint returns a cryptic HTTP 400 status.
The Try It feature works for both `start` and `stop` for the same site.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/rest/api/appservice/webapps/installsiteextension
2. Click on Try It
3. Enter valid Azure App Service name
3. Enter valid Azure App Service resource group name
3. Enter valid Azure App Service Site Extension Id

**Expected behavior**
The site extension should attempt install or return some actionable error.

**Screenshots**
Attempt to install the site extension
![image](https://user-images.githubusercontent.com/1801443/106945846-5345bf80-66f6-11eb-929c-f0b4cea761d7.png)

400 Response
![image](https://user-images.githubusercontent.com/1801443/106945319-a66b4280-66f5-11eb-96e5-8908f9398fab.png)

**Desktop (please complete the following information):**
 - OS: Windows Pro
 - Browser: Chrome
 - Version 10.0.19041

The same exact behavior is present when hitting this endpoint through azure cli locally.
Issue opened in the docs repo: https://github.com/MicrosoftDocs/feedback/issues/3448

**Comment by yonzhan** [comment]
route to service team

**Comment by yonzhan** [comment]
appservice team may have insight for this

**Comment by benne** [comment]
We are relying on this to work for our IaC - having a manuel step in the middle defeats the purpose of automation :)

+1

**Comment by colin-higgins** [comment]
It has been nearly a year since opening the original issue and there has been no feedback or action?
https://github.com/MicrosoftDocs/feedback/issues/3448

**Comment by horihiro** [comment]
Please try with JSON `{}` as a request body and `Content-Type: application/json` as a request header when using curl, wget, or Postman.

**Comment by BryceBarbara** [comment]
@horihiro Thank you, that workaround worked for me!

**Comment by RakeshMohanMSFT** [comment]
Work around provided, Closing the Issue.

**Comment by litan1106** [comment]
btw, this is still broken on pulumi native provider because the hacky workaround.

**Comment by GrimGadget** [comment]
> Work around provided, Closing the Issue.

A workaround is not a solution, and doesn't work in all cases.

**Comment by AIZ-THerring** [comment]
> Please try with JSON `{}` as a request body and `Content-Type: application/json` as a request header when using curl, wget, or Postman.

How about when using Azure CLI?
