### ISSUE TITLE
No module named 'azure.mgmt.storage.v2021_04_01

### ISSUE THREAD

**Issue by peterzeller** [Azure/azure-cli#19625]
## Describe the bug

Azure CLI does not find the storage account module.

I also have some problems with other commands. Some are solved, if I don't run in a python venv, but the storage module cannot be found even when run without venv.

I installed `az` via `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`.

**Command Name**
`az storage account show`

**Errors:**
```
No module named 'azure.mgmt.storage.v2021_04_01'
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 231, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 556, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 517, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
<frozen importlib._bootstrap>, ln 961, in _find_and_load_unlocked
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.storage.v2021_04_01'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage account show`

## Expected Behavior

Don't show a stacktrace error.

The Azure CLI should not depend on my python environment.

## Environment Summary
```
Linux-5.11.0-34-generic-x86_64-with-glibc2.29
Python 3.8.10
Installer: PIP

azure-cli 2.28.1

```

**Comment by yonzhan** [comment]
Storage

**Comment by peterzeller** [comment]
Figured it out: The bin folder of a python virtualenv environment was in my path, even when the environment was not activated.
