### ISSUE TITLE
AZ image copy is failing...

### ISSUE THREAD

**Issue by ranthwar-vcx** [Azure/azure-cli#19629]
### **This is autogenerated. Please review and update as needed.**

Image Name is like --> testvm_Image_pre-v1.9.9_24062021_01-dev-southeastasia
## Describe the bug

**Command Name**
`az image copy`

**Errors:**
```
the following arguments are required: --source-resource-group, --source-object-name, --target-location, --target-resource-group

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image copy {} {} {} {} {} {} {} {}`

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit, Darwin 20.6.0
Python 3.9.7
Installer: HOMEBREW

azure-cli 2.28.0

Extensions:
image-copy-extension 0.2.8

```

**Comment by RakeshMohanMSFT** [comment]
Please upgrade to latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and retry.
