### ISSUE TITLE
az repos

### ISSUE THREAD

**Issue by Anandharajv** [Azure/azure-cli#19626]
## Describe the bug

**Command Name**
`Unknown`

**Errors:**
```
'repos' is misspelled or not recognized by the system.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az repos show --id --org {} --project {} -r {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

```

**Comment by jsntcy** [comment]
Close this one as it's duplicated with #19627.
