### ISSUE TITLE
Unpin cryptography package in azure-cli-core

### ISSUE THREAD

**Issue by ivanst0** [Azure/azure-cli#19635]
Would it be possible to unpin the `cryptography` dependency by changing 
`cryptography>=3.2,<3.4`
to
`cryptography~=3.2`
in `/src/azure-cli-core/setup.py`?

This change won't affect great majority of Azure CLI users (who are using prebuilt packages with `cryptography==3.3.2`).

The users who are still using an older OS which doesn't have rust support (e.g. Alpine) can still apply a simple workaround (installing cryptography==3.3.2 before installing Azure-CLI).
If it is important that [install.py](https://azurecliprod.blob.core.windows.net/install.py) works on those platforms without any additional fixes, this script can be modified to install `cryptography==3.3.2` before installing `azure-cli`.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The reason an upper bound is set is explained in https://github.com/Azure/azure-cli/pull/15687#discussion_r578898876.

By following https://cryptography.io/en/latest/installation/#building-cryptography-on-linux, I am now able to install `cryptography` on Alpine Linux (https://github.com/Azure/azure-cli/issues/19591).

Let me unpin the dependency on `cryptography`.

**Comment by jiasli** [comment]
@glaubitz, I have totally removed the lower bound. Will this suit your need?
