### ISSUE TITLE
DiskRP 2021-04-01 CLI changes

### ISSUE THREAD

**Issue by rytruong** [Azure/azure-cli#19636]
**Resource Provider**
Microsoft.Azure.Management.Compute (specifically DiskRP)

**Description of Feature or Work Requested**
- Customers can set, read and update PublicNetworkAccess, AcceleratedNetwork, and Architecture on Managed Disks and Snapshots.
- Customers can read CompletionPercent on Snapshots.

PublicNetworkAccess
`az disk show`
`az snapshot show`
`az disk create [--public-network-access {Disabled, Enabled}]`
`az disk update [--public-network-access {Disabled, Enabled}]`
`az snapshot create [--public-network-access {Disabled, Enabled}]`
`az snapshot update [--public-network-access {Disabled, Enabled}]`
AcceleratedNetwork
`az disk show`
`az snapshot show` 
`az disk create [--accelerated-network {true, false}]`
`az disk update [--accelerated-network {true, false}]`
`az snapshot create [--accelerated-network {true, false}]`
`az snapshot update [--accelerated-network {true, false}]`
[Architecture](https://github.com/Azure/azure-cli/issues/20141)
`az disk show`
`az snapshot show`
`az disk create [--architecture {x64, Arm64}]`
`az disk update [--architecture {x64, Arm64}]`
`az snapshot create [--architecture {x64, Arm64}]`
`az snapshot update [--architecture {x64, Arm64}]`
CompletionPercent 
`az snapshot show`

Powershell design doc: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1030

**Minimum API Version Required**
2021-04-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/15665

**Target Date**
09/30/2021

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
> Customers can set, read and update PublicNetworkAccess, AcceleratedNetwork, and Architecture on Managed Disks and Snapshots.

@rytruong Hi, this requirement requires us to support new parameters `PublicNetworkAccess`, `AcceleratedNetwork` and `Architecture` on four commands `az disk create`,`az disk update`, `az snapshot create` and `az snapshot update`, and support corresponding queries, right?

As for `PublicNetworkAccess`, those commands already have parameter `--network-access-policy`, which is similar to the `PublicNetworkAccess`. May I ask are they the same thing?
```p
--network-access-policy        : Policy for accessing the disk via network.  Allowed values:
                                AllowAll, AllowPrivate, DenyAll.
```
As for `Architecture`, there seems to be a similar feature request here https://github.com/Azure/azure-cli/issues/20141 , could you confirm it?

**Comment by zhoxing-ms** [comment]
> Customers can read CompletionPercent on Snapshots.

@rytruong This point requires the command `az snapshot show` to support return `CompletionPercent` data, right? 
May I ask does CLI request for REST have additional parameter changes? How do we create the `CompletionPercent` data to test?

**Comment by zhoxing-ms** [comment]
> Customers can create a snapshot using CreateOption "CopyStart".

@rytruong This seems to have been supported in PR https://github.com/Azure/azure-cli/pull/19875 at present. Could you please try whether the latest CLI is already supported it?

**Comment by rytruong** [comment]
> > Customers can set, read and update PublicNetworkAccess, AcceleratedNetwork, and Architecture on Managed Disks and Snapshots.
> 
> @rytruong Hi, this requirement requires us to support new parameters `PublicNetworkAccess`, `AcceleratedNetwork` and `Architecture` on four commands `az disk create`,`az disk update`, `az snapshot create` and `az snapshot update`, and support corresponding queries, right?
> 
> As for `PublicNetworkAccess`, those commands already have parameter `--network-access-policy`, which is similar to the `PublicNetworkAccess`. May I ask are they the same thing?
> 
> ```gnuplot
> --network-access-policy        : Policy for accessing the disk via network.  Allowed values:
>                                 AllowAll, AllowPrivate, DenyAll.
> ```
> 
> As for `Architecture`, there seems to be a similar feature request here #20141 , could you confirm it?

@zhoxing-ms 

@rytruong Hi, this requirement requires us to support new parameters `PublicNetworkAccess`, `AcceleratedNetwork` and `Architecture` on four commands `az disk create`,`az disk update`, `az snapshot create` and `az snapshot update`, and support corresponding queries, right?

Yes

As for `PublicNetworkAccess`, those commands already have parameter `--network-access-policy`, which is similar to the `PublicNetworkAccess`. May I ask are they the same thing?

No, they are different. `PublicNetworkAccess` can have value as Enabled or Disabled

As for `Architecture`, there seems to be a similar feature request here #20141 , could you confirm it?

Yes, it is similar feature.

**Comment by rytruong** [comment]
> > Customers can read CompletionPercent on Snapshots.
> 
> @rytruong This point requires the command `az snapshot show` to support return `CompletionPercent` data, right? May I ask does CLI request for REST have additional parameter changes? How do we create the `CompletionPercent` data to test?

The CompletionPercent is only returned for snapshot created with createOption 'CopyStart'. When it is ready to be tested, I can help create a snapshot for testing.

**Comment by rytruong** [comment]
> > Customers can create a snapshot using CreateOption "CopyStart".
> 
> @rytruong This seems to have been supported in PR #19875 at present. Could you please try whether the latest CLI is already supported it?

Yes, it is supported. Thanks.

**Comment by wangzelin007** [comment]
@rytruong
I have deleted this feature (Customers can create a snapshot using CreateOption "CopyStart".) since it is already done.
And for `Architecture` @laurawu19 has confirmed that we don't need `az snapshot update [--architecture {x64, Arm64}]`.
Can you check with `PublicNetworkAccess` and `AcceleratedNetwork` ?
