### ISSUE TITLE
Add --zone-redundant parameter to az servicebus namespace create

### ISSUE THREAD

**Issue by DanielLarsenNZ** [Azure/azure-cli#19641]
Please add `--zone-redundant parameter` to `az servicebus namespace create`.

#10468 said this had been fixed and [would be deployed in September 2019](https://github.com/Azure/azure-cli/issues/10468#issuecomment-529729964), but this param has still not shipped in latest AZ CLI version 2.28.0.

Without this parameter, customers must use `az group deployment` plus Bicep template.

**Comment by yonzhan** [comment]
route to service team

**Comment by Saglodha** [comment]
Hi @DanielLarsenNZ, apologies for delay here. 

We would triage this internally, and I should be able to share updates soon.

**Comment by Saglodha** [comment]
Hi @DanielLarsenNZ, this has been shipped in our latest release. More info here: https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest#service-bus. 

Please retry the operation and let us know in case you run into any issues. Thanks
