### ISSUE TITLE
"az synapse workspace key activate" not recognised

### ISSUE THREAD

**Issue by minhdn90** [Azure/azure-cli#19648]
**Describe the bug**
Latest version of az cli 2.28.0 doesn't recognised the command as opposed to what's in the release notes
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#synapse

```
$ az synapse workspace key activate
ERROR: 'activate' is misspelled or not recognized by the system.
```

**To Reproduce**
Install az cli 2.28.0
Run
`az synapse workspace key activate`

**Expected behavior**
Help document being shown

**Environment summary**
```
$ az --version
WARNING: Unable to check if your CLI is up-to-date. Check your internet connection.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
azure-cli                         2.28.0

core                              2.28.0
telemetry                          1.0.6

Extensions:
blueprint                          0.3.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
```

**Comment by yonzhan** [comment]
route to service team

**Comment by yonzhan** [comment]
@idear1203 you could contact Lily Ma for bot configuration.

**Comment by kevinzz6** [comment]
@minhdn90 Hi, there is a mistake in the release note. The correct cmdlet is az synapse workspace activate.
You can use 'az synapse workspace activate -h' to get help message.
