### ISSUE TITLE
WebApp: Update parameter descriptions for az webapp config storage-account commands

### ISSUE THREAD

**Issue by Kotasudhakarreddy** [Azure/azure-cli#19645]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

The commands for az webapp config storage-account require an update for the following parameter descriptions.

-Custom id is name of the share configured within the web app
-Mount path the path which the web app uses to read-write data ex: /share1 or /share2
-Share name is name of the file share as given  in the storage account
 
Example:

az webapp config storage-account add -g <<resource group name>> -n <<web app name>> --custom-id <<name of BYOS share used by the web app>>  --storage-type AzureFiles --account-name <<storage account name>> --share-name <<name of file share in the storage account >> --access-key <<storage account access key>>  --mount-path <<mount path used by the web app to read\write content>>
**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
route to service team
