### ISSUE TITLE
How can I add short name to global arguments like --subscription?

### ISSUE THREAD

**Issue by Mossaka** [Azure/azure-cli#19656]
**Is your feature request related to a problem? Please describe.**

The ml team wishes to add a short argument `-s` to `--subscription` global parameter. Is there a easy way to override the existing implemention in azure.cli.core? 

**Describe the solution you'd like**

`az ml <command> create -s <my-subscription-id>`

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by jiasli** [comment]
With the current implementation, you need to ignore `_subscription` and register your own `subscription` parameter.

https://github.com/Azure/azure-cli/blob/02166047196e791058854790bca8af3d2ed0b736/src/azure-cli/azure/cli/command_modules/profile/__init__.py#L66-L68

```py
        with self.argument_context('account') as c:
            c.argument('subscription', options_list=['--subscription', '-s'], arg_group='', help='Name or ID of subscription.', completer=get_subscription_id_list)
            c.ignore('_subscription')
```

**Comment by jiasli** [comment]
With the current implementation, you need to ignore `_subscription` and register your own `subscription` argument.

https://github.com/Azure/azure-cli/blob/02166047196e791058854790bca8af3d2ed0b736/src/azure-cli/azure/cli/command_modules/profile/__init__.py#L66-L68

**Comment by Mossaka** [comment]
For some reason, I added line 67 to our code base, but we didn't see subscription in argument group. Neither did I see it in global args. It just magically disappears.

**Comment by Mossaka** [comment]
![image](https://user-images.githubusercontent.com/5447827/135010357-89e47610-b352-464f-9f6f-999d0264c24f.png)
![image](https://user-images.githubusercontent.com/5447827/135010377-e27a4dcb-e4d1-422d-8273-c67e6980dde1.png)

**Comment by jiasli** [comment]
You will need to have a corresponding `subscription` parameter in your custom function to get it work:

https://github.com/Azure/azure-cli/blob/63ba90ae819d391a757ea628663d289741bf0c04/src/azure-cli/azure/cli/command_modules/profile/custom.py#L89
