### ISSUE TITLE
Disassociation of VM/VMSS from Capacity reservation group request is not working as expected.

### ISSUE THREAD

**Issue by hari-bodicherla** [Azure/azure-cli#19659]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
As per https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az_vm_update ( AZ VM update ) documentation, to disassociate a VM from CRG, we need to pass the "None" in the --capacity-reservation-group --crg params. But when we are entering this  as shown in below example, the update request is failing since ARM is invalidating the value since the value for CapacityReservationGroup.id is "" instead of null. Also can we update the CLI logic to accept Null from the user in the cmd instead of None and then populate the VM update request with CapacityReservationGroup.id as null which can fix this issue.

This issue needs to be fixed for the AZ VMSS update cmd too.

**To Reproduce**
1. Create a VM associating with a Capacity reservation group 
2. Dealllcoate the VM
3. Try to disassociate the VM from  CRG using the below cmd
>>> az vm update -g myresourcegroup22 -n myVM --capacity-reservation-group None

Argument '--capacity-reservation-group' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(LinkedInvalidPropertyId) Property id '' at path 'properties.capacityReservation.capacityReservationGroup.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.

**Expected behavior**
The request should be populated as capacityReservationGroup.id as null instead of "" and The VM should be disassociated from CRG

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@hari-bodicherla  In fact, when I developed and tested this feature, the parameter `properties.capacityReservation.capacityReservationGroup.id` passed into `""` can disassociate VM. Has this behavior of the REST service changed recently?
If so, I will modify the value of `properties.capacityReservation.capacityReservationGroup.id` from `""` to null.

**Comment by zhoxing-ms** [comment]
> Also can we update the CLI logic to accept Null from the user in the cmd instead of None and then populate the VM update request with CapacityReservationGroup.id as null which can fix this issue.

In fact, we recommend using the value of `None` to disassociate VM/VMSS, because we generally use `None` to clear the exists value in other commands (such as `--nsg-rule`), so we want to keep consistent. What do you think of it?

**Comment by hari-bodicherla** [comment]
> > Also can we update the CLI logic to accept Null from the user in the cmd instead of None and then populate the VM update request with CapacityReservationGroup.id as null which can fix this issue.
> 
> In fact, we recommend using the value of `None` to disassociate VM/VMSS, because we generally use `None` to clear the exists value in other commands (such as `--nsg-rule`), so we want to keep consistent. What do you think of it?

Sure @zhoxing-ms , that makes sense, we can go with None option if that is the norm across the CLI cmds. but could you let me know when this fix will be released to public.

**Comment by zhoxing-ms** [comment]
@hari-bodicherla We will release it in this sprint **10-12**
