### ISSUE TITLE
[DocDB] Does the create command need to require region failover?

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1966]
After being familiar with the creation process for DocDB in the portal, I was confused to see the `--locations` flag be required in the CLI, especially since the description talks about region failover. Ideally, you could simply run `az documentdb create -n <NAME> -g <GROUP> -k MongoDB`, in order to make the getting started experience as streamlined as possible.

> The above idealistic sample also asks if we could alias the `--kind` flag as `-k` :)

**Comment by dmakwana** [comment]
PR here: #1978

**Comment by tjprescott** [comment]
#1978 merged.
