### ISSUE TITLE
Support for additional enum values in WAF Policy Exclusion Match Variables

### ISSUE THREAD

**Issue by tejasshah7** [Azure/azure-cli#19674]
**Resource Provider**

Network (NRP)

**Description of Feature or Work Requested**

We are adding support for additional Match Variables within the Exclusions structure for Web Application Firewall Policy. Specifically, we support 3 values today:
            "RequestHeaderNames",
            "RequestCookieNames",
            "RequestArgNames"

We plan to add 6 more:
            "RequestArgNames",
            "RequestHeaderKeys",
            "RequestHeaderValues",
            "RequestCookieKeys",
            "RequestCookieValues",
            "RequestArgKeys",
            "RequestArgValues

Here is a link to the design document for reference.
https://microsoft.sharepoint.com/:w:/t/ApplicationGateway9/EbgOPKsTc-BLvn6OU9N7__wBBR6qN-DIe3-48CEkGBl8lg?e=qc2mst

**Minimum API Version Required**

2021-05-01

**Swagger Link**

Swagger PR is in review. Here is a link for this:
https://github.com/Azure/azure-rest-api-specs/pull/16124

**Target Date**

Target Date for this feature release is End of October 2021.

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
@tejasshah7 Is this feature required for Ignite?

**Comment by tejasshah7** [comment]
Yes this is required for Ignite.

Thanks
Tejas

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kairu-ms** [comment]
> Yes this is required for Ignite. Thanks Tejas Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)
> ________________________________ From: kai ru ***@***.***> Sent: Monday, September 27, 2021 8:25:44 PM To: Azure/azure-cli ***@***.***> Cc: Tejas Shah ***@***.***>; Mention ***@***.***> Subject: Re: [Azure/azure-cli] Support for additional enum values in WAF Policy Exclusion Match Variables (#19674) @tejasshah7<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftejasshah7&data=04%7C01%7Ctejas.shah%40microsoft.com%7C468da7c426e94542d35708d9822fa888%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637683963482491867%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gQ6qDGCZxl8mT2VNE6E4p3yoFTdk%2B41LtAzMTa2Clo8%3D&reserved=0> Is this feature required for Ignite? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fissues%2F19674%23issuecomment-928709592&data=04%7C01%7Ctejas.shah%40microsoft.com%7C468da7c426e94542d35708d9822fa888%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637683963482501824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=se%2FOXOrV8Gy8x1EOmOa4LhhFBbzAW5xW%2FztNTMeezNQ%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALYKWOQXAIL45G3TX4BMRSLUEEYTRANCNFSM5EUT7KPA&data=04%7C01%7Ctejas.shah%40microsoft.com%7C468da7c426e94542d35708d9822fa888%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637683963482501824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ut5JaYKZfzKT8paAAe%2BurpJQfaJcdFJCG5aTaI%2BkBfU%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctejas.shah%40microsoft.com%7C468da7c426e94542d35708d9822fa888%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637683963482511779%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VgasCWDKfhwHoTRIKEMOYSMgPhPI42aRO5zXTR6KPws%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctejas.shah%40microsoft.com%7C468da7c426e94542d35708d9822fa888%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637683963482511779%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IgxAJ%2Ff9fMKlcsidbl6Na3qezGxjEDXWTNUlt4UaI%2BM%3D&reserved=0>.

I see. However the network Python SDK with 2021-05-01 version is not release.

**Comment by tejasshah7** [comment]
@kairu-ms why is Python SDK needed for this? How can I have the Python SDK generated?

**Comment by tejasshah7** [comment]
> @tejasshah7 The network Python SDK with 2021-05-01 version is not release. We can start to add this feature only when Python SDK is ready. Could you tell us when will the Python SDK be ready?

@kairu-ms why is Python SDK needed for this? How can I have the Python SDK generated?

**Comment by tejasshah7** [comment]
> > @tejasshah7 The network Python SDK with 2021-05-01 version is not release. We can start to add this feature only when Python SDK is ready. Could you tell us when will the Python SDK be ready?
> 
> @kairu-ms why is Python SDK needed for this? How can I have the Python SDK generated?

Swagger for this API version will be merged and released on Oct 18. Then Python SDK can be generated.

**Comment by kairu-ms** [comment]
@tejasshah7, Python SDK should be ready on Oct 18 as well. Otherwise we don't have enough time to bump up api-version to 2021-05-01 and develop your feature.

**Comment by 00Kai0** [comment]
Already supported in cli:

![image](https://user-images.githubusercontent.com/26342317/142112970-0ea08d1a-1d62-4c42-be55-25b6b58f8697.png)
