### ISSUE TITLE
Incorrect description for optional paramater in az apim api import

### ISSUE THREAD

**Issue by Tankatronic** [Azure/azure-cli#19673]
The documentation for command `az apim api import` has an incorrect description for optional parameter `--api-id`. 

"API revision identifier. Must be unique in the current API Management service instance. Non-current revision has ;rev=n as a suffix where n is the revision number."

the description should read:

"Unique name of the api to import. If an API of the same name exists it will be replaced. Otherwise a new API resource will be created."
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f27e34-66e0-1d08-f734-26ce29c56c36
* Version Independent ID: d1a421eb-807c-c0bd-cee3-a5aed7335625
* Content: [az apim api](https://docs.microsoft.com/en-us/cli/azure/apim/api?view=azure-cli-latest#az_apim_api_update)
* Content Source: [latest/docs-ref-autogen/apim/api.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/apim/api.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team
