### ISSUE TITLE
[DocDB] List command requires a resource group parameter

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1967]
It would be great if we could remove the resource group as a required parameter for the `az documentdb list` command, in order to be consistent with the general behavior of `list` commands in the CLI.

**Comment by tjprescott** [comment]
That depends entirely on whether the service has list_by_resource_group and a list_all methods.

**Comment by lostintangent** [comment]
I'm also not sure if it's just me, but the `list` command actually throws an exception, so even if I specify a resource group, it doesn't work.

**Comment by dmakwana** [comment]
There are 2 list commands (**list** - by resource group) and (**list-all** by subscription). @lostintangent can you send me the exception and what your input was? Was not able to reproduce.

**Comment by lostintangent** [comment]
@dmakwana Having two separate commands for this is inconsistent with most of the existing `list` commands. Ideally, the CLI could maintain consistent behavior across resource types, so that common operations are as consistent as possible.

**Comment by dmakwana** [comment]
so 1 'list' command should be okay with the --resource-group-name parameter optional?

**Comment by lostintangent** [comment]
Yep! That would be ideal, and consistent with other command groups.

**Comment by dmakwana** [comment]
PR here: #2025
