### ISSUE TITLE
Listing/showing nodes associated with a nodepool

### ISSUE THREAD

**Issue by kmathewmk** [Azure/azure-cli#19681]
Could you please document how nodes associated with a nodepool can be listed/shown?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fce7ab-ab56-44c6-b9a8-405444247a0b
* Version Independent ID: dabbb6c6-c616-a6ec-61f6-1b9d3bb069e8
* Content: [az aks nodepool](https://docs.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/aks/nodepool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/aks/nodepool.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@kmathewmk Apologies for the late reply. Thanks for the feedback. We have created the above PR for the same and it is pending on review. In the meantime, if you have any questions, please feel free to ask.
