### ISSUE TITLE
Azure Load Balancer inbound NAT rule v2 

### ISSUE THREAD

**Issue by irenehua** [Azure/azure-cli#19688]
**Is your feature request related to a problem? Please describe.**
New inbound NAT rule model for all VMSS (VMO and VMSS), where customers can specify frontend port range and a backend pool which LB will honor to create individual port mapping with a frontend port from the specific range and an individual instance form the backend pool.

**Describe the solution you'd like**
CLI API customers can leverage to create, update, delete inbound NAT rule 

**Describe alternatives you've considered**

**Additional context**

**Comment by irenehua** [comment]
Swagger: 
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2021-03-01/loadBalancer.json

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
@irenehua Is it a feature required for Ignite?

**Comment by irenehua** [comment]
@kairu-ms Not for Ignite but we would like to ship this as soon as possible :)

**Comment by kairu-ms** [comment]
@irenehua --frontend-port-range-start and --frontend-port-range-end is supported. `--backend-pool-name` is not supported because we still have issue to test it.
