### ISSUE TITLE
Create multiple blob containers in a single command

### ISSUE THREAD

**Issue by waterflyer** [Azure/azure-cli#19686]
[Enter feedback here]
Hi, I've used the command az storage container create --name to create blob storage successfully, I wonder that if we can create multiple blob containers by using this single command instead of executing this command many times? If so, what's the correct command to accomplish it. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcba5ed-e693-6345-2c1b-c17422d7b8f9
* Version Independent ID: 58297400-b777-6868-1687-0af3a512a16f
* Content: [az storage container](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#az_storage_container_create)
* Content Source: [latest/docs-ref-autogen/storage/container.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/storage/container.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Storage

**Comment by evelyn-ys** [comment]
So far, there's no command for creating multiple containers in one request. Service doesn't have such plan I guess. So both CLI and Portal won't have such support either.

**Comment by waterflyer** [comment]
Ok, I see. Thanks for the answer. @evelyn-ys
