### ISSUE TITLE
'Azure-cli-ml Version': '1.5.0', 'Error': AuthenticationException

### ISSUE THREAD

**Issue by toby-htx** [Azure/azure-cli#19690]
I am using Azure DevOps to automate the release of my Azure ML model to ACI, but I keep getting the error below:

I am using azure-cli==2.20 and azure-cli-ml==1.5.0 with ubuntu-20.04 as my agent.

Can anyone help please?

**Comment by toby-htx** [comment]
Now, I get this error:

![image](https://user-images.githubusercontent.com/81354022/134783199-d8ea54a8-c219-473e-b579-2c9dc93a40b2.png)

**Comment by toby-htx** [comment]
Now, I get this error:

![image](https://user-images.githubusercontent.com/81354022/134783228-fe3e3a9b-d0e8-49e8-bdc9-39abf79d5d63.png)

**Comment by yonzhan** [comment]
route to service team

**Comment by toby-htx** [comment]
Hi, this issue is fixed on my end! Thanks!
