### ISSUE TITLE
az apim api list authenticationSettings property in response is always null

### ISSUE THREAD

**Issue by ivanignatiev** [Azure/azure-cli#19727]
## Describe the bug
Confusing response of `az apim api list`

**Command Name**
`az apim api list`

**Errors:**
None

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Configure APIM Service with API with Security -> User authorization -> OpenID Connect or OAuth 2.0
- `az login`
- `az apim api list --resource-group {} --service-name {}`
- Get response where all APIs have `authenticationSettings: null`
- Call `az apim api show --resource-group {} --service-name {} --api-id {}` for API ID where User authentication is configured
- Get response with 
```json
"authenticationSettings": {
    "oAuth2": null,
    "openid": {
      "bearerTokenSendingMethods": null,
      "openidProviderId": "openid-connect-azuread"
    }
  }
```

## Expected Behavior

- Option 1. The same value of `authenticationSettings` property in `az apim api list` and `az apim api show` responses
- Option 2. Absence of `authenticationSettings` property in `az apim api list` response

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1 *

```
## Additional Context

Account has Contributor access to the APIM Service resource

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
@ivanignatiev We are returning authenticationSettings as null for both the command.
