### ISSUE TITLE
Support for Per Rule Exclusions in Application Gateway WAF

### ISSUE THREAD

**Issue by tejasshah7** [Azure/azure-cli#19734]
**Resource Provider**

Network (NRP)

**Description of Feature or Work Requested**

Support for WAF Per Rule Exclusions. Currently we support Global exclusions only. We are modifying existing structure so limits on exclusions will still hold as before. 

Here is a design document for swagger:
https://microsoft.sharepoint.com/:w:/t/ApplicationGateway9/EdN7W0EO9qhNuuRfkizbuR0BWSNOCYycQkoAjV9T9fGMDw?e=fEbALl

**Minimum API Version Required**

2021-05-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/16154

**Target Date**

End of October 2021 (Targeting for Ignite)

**Comment by yonzhan** [comment]
Network for Ignite

**Comment by kairu-ms** [comment]
Hi @tejasshah7, we can't working on your features because Python SDK contains api-version 2021-05-01 is not released.

**Comment by tejasshah7** [comment]
I understand and there isn't much I can do. Can this be worked upon once the SDK is available? I am fine if it gets released next month.

Thanks,
Tejas

**Comment by tejasshah7** [comment]
Can you move it or I need to do it?

**Comment by kairu-ms** [comment]
I can move it.
