### ISSUE TITLE
az sql server update --identity-type SystemAssigned not working

### ISSUE THREAD

**Issue by GunnarHakansson** [Azure/azure-cli#19731]
## Describe the bug

Specifying `--identity-type SystemAssigned` together with `--assign_identity` results in the command being ignored and no managed identity is created.

Just using `--assign_identity` without `--identity-type SystemAssigned` works as expected.

Setting the default value for `--identity-type`  results in nothing happening.

**Command Name**
`az sql server update`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a sql server without any managed identity.
- `az sql server update --name {} --resource-group {} --assign_identity --identity-type SystemAssigned`

## Expected Behavior

`az sql server update --name {} --resource-group {} --assign_identity`

and 

`az sql server update --name {} --resource-group {} --assign_identity --identity-type SystemAssigned`

Should give the same result, which is that a System Assigned Managed Identity is created for the SQL Server.

## Environment Summary
```
Linux-5.4.0-1058-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

Extensions:
resource-graph 1.0.0
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route service team

**Comment by strehan1993** [comment]
LGTM
