### ISSUE TITLE
Automatic In-Guest Patching for VMSS

### ISSUE THREAD

**Issue by mayanknayar** [Azure/azure-cli#19737]
**Resource Provider**
Compute

**Description of Feature or Work Requested**
Automatic in-guest patching provides customers an easy-to-onboard solution to maintain security compliance for their virtual machines. This feature provides:

Simple onboarding – Enrolling a VMSS requires configuring one property on the VMSS model (process detailed below) with no further onboarding actions needed.
Automatic compliance – Most VMs (including dev/test) have compliance requirements for security/critical vulnerabilities and using automatic in-guest patching keeps the virtual machine compliant without additional overhead.
Availability-first patching – Automatic in-guest patching is orchestrated through an availability-first process (detailed below) which ensures maximum uptime for the customer’s application.

This property is already available for VM:
https://docs.microsoft.com/en-us/azure/virtual-machines/automatic-vm-guest-patching#azure-cli-for-windows-vms
https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az_vm_create

Reference CLI request for VM: 
Windows: https://github.com/Azure/azure-cli/issues/14458
Linux: https://github.com/Azure/azure-cli/issues/16159

To onboard a new VM to automatic in-guest patching, the following property settings must be included in the VMSS model/template either under windowsConfiguration or linuxConfiguration:

"windowsConfiguration": {
"provisionVMAgent": true,
"patchSettings": {
"patchMode": "AutomaticByPlatform"
}
}

"linuxConfiguration": {
"provisionVMAgent": true,
"patchSettings": {
"patchMode": "AutomaticByPlatform"
}
}

Allowed values for Windows  AutomaticByOS, AutomaticByPlatform, Manual
Allowed values for Linux VM: AutomaticByPlatform, ImageDefault

CLI support is requested to set the above flag on the VMSS model when creating the VMSS or modifying it.

**Minimum API Version Required**
2020-12-01

**Swagger Link**
Windows case;

Swagger ref: https://github.com/Azure/azure-rest-api-specs/blob/4d1cfdb75ea7ba87f91caf3c943205730c739101/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json#L12536
This will be mapped to https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.patchsettings.patchmode?view=azure-dotnet#Microsoft_Azure_Management_Compute_Models_PatchSettings_PatchMode
Linux case:

Swagger ref: https://github.com/Azure/azure-rest-api-specs/blob/4d1cfdb75ea7ba87f91caf3c943205730c739101/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json#L12558
This should be mapped to LinuxPatchSettings in https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.linuxconfiguration?view=azure-dotnet

**Target Date**
Ignite 2021 (Nov 02, 2021)

**Comment by mayanknayar** [comment]
@Deepali-Gupta FYI

**Comment by yonzhan** [comment]
Compute for Ignite

**Comment by zhoxing-ms** [comment]
@mayanknayar  Since we have arranged the work of the next sprint, we may not have enough time to develop and release. Is it acceptable to release in the sprint after the next sprint ( in early December)?

**Comment by mayanknayar** [comment]
@zhoxing-ms yes, this request is to get the CLI cmdlets for VMSS in line with the implemented CLI for VMs. I included the template samples in the my original request. Can you take a look and let me know which other details you need to get started? Here are some more examples for template from the doc: 
https://docs.microsoft.com/en-us/azure/virtual-machines/automatic-vm-guest-patching#rest-api-for-linux-vms
https://docs.microsoft.com/en-us/azure/virtual-machines/automatic-vm-guest-patching#rest-api-for-windows-vms
The same osProfile block applies to VMSS same as I included in my request details.

**Comment by mayanknayar** [comment]
@zhoxing-ms for timelines, this feature is an Ignite release, so December would be too late. Can you include it for the release immediately after Ignite hopefully by mid-November?

**Comment by zhoxing-ms** [comment]
＠mayanknayar Thank you for your reply. At present, our Chinese team is taking the National Day holiday. We will arrange the development and release of this requirement after the holiday

**Comment by jsntcy** [comment]
As currently `az vmss create` cannot add extension while adding health extension to vmss is a prerequisite to set patchMode to "AutomaticByPlatform", so we cannot support set patchMode for `az vmss create` yet.  @mayanknayar will create another feature request for adding extension during vmss creation (do it after Ignite).
Currently we will only need support updating patchMode for `az vmss update` using dot syntax (`az vmsss update --set virtualMachineProfile.osProfile.linuxConfiguration.patchSettings.patchMode=AutomaticByPlatform`) to be consist with 'az vm update`.
