### ISSUE TITLE
WebApp:not able to set webapp auth set

### ISSUE THREAD

**Issue by Iceymann18777** [Azure/azure-cli#19738]
## Describe the bug

**Command Name**
`az webapp auth set`

**Errors:**
```
argument --name/-n: expected one argument

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp auth set --name`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0

Extensions:
authV2 0.1.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
@Iceymann18777 az webapp auth needs -n -g as required parameters https://docs.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest#az_webapp_auth_set
Please re-try the command with these required values

**Comment by panchagnula** [comment]
Please re-open if this repros.

**Comment by panchagnula** [comment]
@Hamster-Huey FYI

**Comment by Hamster-Huey** [comment]
Took a look, 

That error: 
`argument --name/-n: expected one argument`
is returned when you run the command exactly: 
`az webapp auth set --name`
without providing any name.

A full command would look like 
`az webapp auth set --name mysitename --resource-group myresourcegroup --body someauthv2json` 

That being said, @Iceymann18777 what is your purpose for using the set command? That command allows you to update your auth settings via the full authv2 json schema, but I would only recommend that for use cases that are not provided through the other auth command available.

**Comment by PramodValavala-MSFT** [comment]
@Iceymann18777 Just following up here to see if the response here help. If not, please do share more details about the exact command you are running and your scenario.
