### ISSUE TITLE
Azure Machine Learning Cli Extension fail installation

### ISSUE THREAD

**Issue by freedev** [Azure/azure-cli#19744]
## The installation of the azure ml cli extension fails. 

the installation of the azure ml cli extension fails. 

**Command Name**
`az extension add`

**Errors:**
```
An error occurred. Pip failed with status code 1. Use --debug for more information.

```

## To Reproduce:

just try to execute the following command:

- `az extension add --name azure-cli-ml --debug`

## Expected Behavior

the extension should be installed

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit
Python 3.9.6
Installer: HOMEBREW

azure-cli 2.27.2

Extensions:
azure-devops 0.20.0
deploy-to-azure 0.2.0
application-insights 0.1.14

~  az --version                                                                                                                      INT  Azure Cognitive Services Development az
azure-cli                         2.27.2

core                              2.27.2
telemetry                          1.0.6

Extensions:
azure-devops                      0.20.0
deploy-to-azure                    0.2.0
application-insights              0.1.14

Python location '/usr/local/Cellar/azure-cli/2.27.2/libexec/bin/python'
Extensions directory '/Users/freedev/.azure/cliextensions'

Python (Darwin) 3.9.6 (default, Jun 29 2021, 05:25:02)
[Clang 12.0.5 (clang-1205.0.22.9)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
```
## Additional Context

 ~  az extension add --name azure-cli-ml --debug                                                                                       ok  Azure Cognitive Services Development az
cli.knack.cli: Command arguments: ['extension', 'add', '--name', 'azure-cli-ml', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x10fef6940>, <function OutputProducer.on_global_arguments at 0x10ff64160>, <function CLIQuery.on_global_arguments at 0x10ff813a0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'extension': ['azure.cli.command_modules.extension']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: extension                 0.004         1         7
cli.azure.cli.core: Total (1)                 0.004         1         7
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 1 groups, 7 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : extension add
cli.azure.cli.core: Command table: extension add
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x110582d30>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/freedev/.azure/commands/2021-09-30.10-20-03.extension_add.20311.log'.
az_command_data_logger: command args: extension add --name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x1105a41f0>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x1105fec10>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x1105fed30>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x1105fee50>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x10ff641f0>, <function CLIQuery.handle_query_parameter at 0x10ff81430>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x1105feca0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x1105fedc0>]
urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool: https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool: Starting new HTTPS connection (1): azcliextensionsync.blob.core.windows.net:443
urllib3.connectionpool: https://azcliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 1272317
cli.azure.cli.core.extension._resolve: Candidates ['azure_cli_ml-1.33.0-py3-none-any.whl', 'azure_cli_ml-1.5.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['azure_cli_ml-1.33.0-py3-none-any.whl', 'azure_cli_ml-1.5.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['azure_cli_ml-1.33.0-py3-none-any.whl', 'azure_cli_ml-1.5.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['azure_cli_ml-1.33.0-py3-none-any.whl', 'azure_cli_ml-1.5.0-py2.py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Choosing the latest of the remaining candidates.
cli.azure.cli.core.extension._resolve: Chosen {'downloadUrl': 'https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.33.0-py3-none-any.whl', 'filename': 'azure_cli_ml-1.33.0-py3-none-any.whl', 'metadata': {'azext.minCliCoreVersion': '2.3.1', 'classifiers': ['Development Status :: 3 - Alpha', 'Intended Audience :: Developers', 'Intended Audience :: System Administrators', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: 3.9'], 'description_content_type': 'text/x-rst', 'extensions': {'python.details': {'contacts': [{'email': 'azpycli@microsoft.com', 'name': 'Microsoft Corporation', 'role': 'author'}], 'document_names': {'description': 'DESCRIPTION.rst', 'license': 'LICENSE.txt'}, 'project_urls': {'Home': 'https://docs.microsoft.com/python/api/overview/azure/ml/?view=azure-ml-py'}}}, 'extras': [], 'generator': 'bdist_wheel (0.30.0)', 'license': 'Proprietary https://aka.ms/azureml-preview-sdk-license ', 'metadata_version': '2.0', 'name': 'azure-cli-ml', 'requires_python': '>=3.5,<4', 'run_requires': [{'requires': ['adal (>=1.2.1)', 'azureml-cli-common (~=1.33.0)', 'cryptography (<=3.3.2)', 'docker (>=3.7.2)', 'msrest (>=0.6.6)', 'pyyaml (>=5.1.0)', 'requests (>=2.21.0)']}], 'summary': 'Microsoft Azure Command-Line Tools AzureML Command Module', 'test_requires': [{'requires': ['azure-keyvault', 'mock', 'nose', 'unittest-xml-reporting']}], 'version': '1.33.0'}, 'sha256Digest': '8ed9f235f417672a27c6f1abb1473d063e2adf11f6cbf91683124cfa7b8ac8e4'}
cli.azure.cli.core.extension.operations: Extension source is url? True
cli.azure.cli.core.extension.operations: Downloading https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.33.0-py3-none-any.whl to /var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/tmpzp7h7p89/azure_cli_ml-1.33.0-py3-none-any.whl
urllib3.connectionpool: Starting new HTTPS connection (1): azurecliext.blob.core.windows.net:443
urllib3.connectionpool: https://azurecliext.blob.core.windows.net:443 "GET /release/azure_cli_ml-1.33.0-py3-none-any.whl HTTP/1.1" 200 96124
cli.azure.cli.core.extension.operations: Downloaded to /var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/tmpzp7h7p89/azure_cli_ml-1.33.0-py3-none-any.whl
cli.azure.cli.core.extension.operations: Validating the extension /var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/tmpzp7h7p89/azure_cli_ml-1.33.0-py3-none-any.whl
cli.azure.cli.core.extension.operations: Checksum of /var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/tmpzp7h7p89/azure_cli_ml-1.33.0-py3-none-any.whl is OK
cli.azure.cli.core.extension.operations: Validation successful on /var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/tmpzp7h7p89/azure_cli_ml-1.33.0-py3-none-any.whl
cli.azure.cli.core.extension.operations: Linux distro check: Reading from: /etc/apt/sources.list.d/azure-cli.list
cli.azure.cli.core.extension.operations: Linux distro check: An error occurred while checking linux distribution version source list consistency.
cli.azure.cli.core.extension.operations: [Errno 2] No such file or directory: '/etc/apt/sources.list.d/azure-cli.list'
cli.azure.cli.core.extension.operations: Executing pip with args: ['install', '--target', '/Users/freedev/.azure/cliextensions/azure-cli-ml', '/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/tmpzp7h7p89/azure_cli_ml-1.33.0-py3-none-any.whl']
cli.azure.cli.core.extension._homebrew_patch: Homebrew patch: Temporarily creating /Users/freedev/.pydistutils.cfg to support extension installation on Homebrew.
cli.azure.cli.core.extension.operations: Running: ['/usr/local/Cellar/azure-cli/2.27.2/libexec/bin/python', '-m', 'pip', 'install', '--target', '/Users/freedev/.azure/cliextensions/azure-cli-ml', '/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/tmpzp7h7p89/azure_cli_ml-1.33.0-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']
cli.azure.cli.core.extension.operations: Using pip 21.1.3 from /usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/pip (python 3.9)
Non-user install due to --prefix or --target option
Created temporary directory: /private/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/pip-target-35rvf6_3
Created temporary directory: /private/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/pip-ephem-wheel-cache-7tn72htg
Created temporary directory: /private/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/pip-req-tracker-6ygacyq2
Initialized build tracking at /private/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/pip-req-tracker-6ygacyq2
Created build tracker: /private/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/pip-req-tracker-6ygacyq2
Entered build tracker: /private/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/pip-req-tracker-6ygacyq2
Created temporary directory: /private/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/pip-install-elbzv3ym
Processing /var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/tmpzp7h7p89/azure_cli_ml-1.33.0-py3-none-any.whl
  Added azure-cli-ml==1.33.0 from file:///var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/tmpzp7h7p89/azure_cli_ml-1.33.0-py3-none-any.whl to build tracker '/private/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/pip-req-tracker-6ygacyq2'
  Removed azure-cli-ml==1.33.0 from file:///var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/tmpzp7h7p89/azure_cli_ml-1.33.0-py3-none-any.whl from build tracker '/private/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/pip-req-tracker-6ygacyq2'
1 location(s) to search for versions of azureml-cli-common:
* https://pypi.org/simple/azureml-cli-common/
Fetching project page and analyzing links: https://pypi.org/simple/azureml-cli-common/
Getting page https://pypi.org/simple/azureml-cli-common/
Found index url https://pypi.org/simple
[... omissis ...]
Skipping link: not a file: https://pypi.org/simple/azureml-cli-common/
Given no hashes to check 1 links for project 'azureml-cli-common': discarding no candidates
Collecting azureml-cli-common~=1.33.0
  Created temporary directory: /private/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/pip-unpack-wc_583k3
  Starting new HTTPS connection (1): files.pythonhosted.org:443
  https://files.pythonhosted.org:443 "GET /packages/de/98/cbc12fb02ab75853d71fb32a0228b7476e6a58b2616cf66124cc15dfe6b0/azureml_cli_common-1.33.0-py3-none-any.whl HTTP/1.1" 200 12870
  Downloading azureml_cli_common-1.33.0-py3-none-any.whl (12 kB)
  Added azureml-cli-common~=1.33.0 from https://files.pythonhosted.org/packages/de/98/cbc12fb02ab75853d71fb32a0228b7476e6a58b2616cf66124cc15dfe6b0/azureml_cli_common-1.33.0-py3-none-any.whl#sha256=81083e2e7587b14338516db23c4fb95674640fd991a7e405149e9228b4e8bb7e (from azure-cli-ml==1.33.0) to build tracker '/private/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/pip-req-tracker-6ygacyq2'
  Removed azureml-cli-common~=1.33.0 from https://files.pythonhosted.org/packages/de/98/cbc12fb02ab75853d71fb32a0228b7476e6a58b2616cf66124cc15dfe6b0/azureml_cli_common-1.33.0-py3-none-any.whl#sha256=81083e2e7587b14338516db23c4fb95674640fd991a7e405149e9228b4e8bb7e (from azure-cli-ml==1.33.0) from build tracker '/private/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/pip-req-tracker-6ygacyq2'
1 location(s) to search for versions of msrest:
* https://pypi.org/simple/msrest/
Fetching project page and analyzing links: https://pypi.org/simple/msrest/
Getting page https://pypi.org/simple/msrest/

INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of azure-cli-ml to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement azureml-core~=1.33.0 (from azureml-cli-common) (from versions: 0.1.50, 0.1.57, 0.1.58, 0.1.59, 0.1.65, 0.1.68, 0.1.74, 0.1.80, 1.0rc83, 1.0rc85, 1.0.2, 1.0.6, 1.0.8, 1.0.10, 1.0.15, 1.0.17, 1.0.17.1, 1.0.18, 1.0.21, 1.0.23, 1.0.30, 1.0.33, 1.0.33.1, 1.0.39, 1.0.41, 1.0.41.1, 1.0.43, 1.0.43.1, 1.0.45, 1.0.48, 1.0.53, 1.0.55, 1.0.57, 1.0.57.1, 1.0.60, 1.0.62, 1.0.62.1, 1.0.65, 1.0.65.1, 1.0.69, 1.0.72, 1.0.74, 1.0.76, 1.0.76.1, 1.0.79, 1.0.81, 1.0.81.1, 1.0.83, 1.0.85, 1.0.85.1, 1.0.85.2, 1.0.85.3, 1.0.85.4, 1.0.85.5, 1.0.85.6, 1.1.0rc0, 1.1.1rc0, 1.1.1.1rc0, 1.1.1.2rc0, 1.1.2rc0, 1.1.5, 1.1.5.1, 1.1.5.2, 1.1.5.3, 1.1.5.4, 1.1.5.5, 1.1.5.6, 1.1.5.7)
ERROR: No matching distribution found for azureml-core~=1.33.0
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 377, in resolve
    raise ResolutionImpossible(causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('azureml-core~=1.33.0'), parent=LinkCandidate('https://files.pythonhosted.org/packages/de/98/cbc12fb02ab75853d71fb32a0228b7476e6a58b2616cf66124cc15dfe6b0/azureml_cli_common-1.33.0-py3-none-any.whl#sha256=81083e2e7587b14338516db23c4fb95674640fd991a7e405149e9228b4e8bb7e (from https://pypi.org/simple/azureml-cli-common/) (requires-python:>=3.6,<4)'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 136, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for azureml-core~=1.33.0
Removed build tracker: '/private/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/pip-req-tracker-6ygacyq2'

cli.azure.cli.core.extension.operations: Command '['/usr/local/Cellar/azure-cli/2.27.2/libexec/bin/python', '-m', 'pip', 'install', '--target', '/Users/freedev/.azure/cliextensions/azure-cli-ml', '/var/folders/fc/58xbxq617qg07rf73fhdtznc0000gn/T/tmpzp7h7p89/azure_cli_ml-1.33.0-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
cli.azure.cli.core.extension._homebrew_patch: Homebrew patch: Deleting the temporarily created /Users/freedev/.pydistutils.cfg
cli.azure.cli.core.extension.operations: Pip failed so deleting anything we might have installed at /Users/freedev/.azure/cliextensions/azure-cli-ml
cli.azure.cli.core.extension.operations: Failed to delete '/Users/freedev/.azure/cliextensions/azure-cli-ml': [Errno 2] No such file or directory: '/Users/freedev/.azure/cliextensions/azure-cli-ml'. Retrying ...
cli.azure.cli.core.extension.operations: Failed to delete '/Users/freedev/.azure/cliextensions/azure-cli-ml': [Errno 2] No such file or directory: '/Users/freedev/.azure/cliextensions/azure-cli-ml'. Retrying ...
cli.azure.cli.core.extension.operations: Failed to delete '/Users/freedev/.azure/cliextensions/azure-cli-ml': [Errno 2] No such file or directory: '/Users/freedev/.azure/cliextensions/azure-cli-ml'. Retrying ...
cli.azure.cli.core.extension.operations: Failed to delete '/Users/freedev/.azure/cliextensions/azure-cli-ml': [Errno 2] No such file or directory: '/Users/freedev/.azure/cliextensions/azure-cli-ml'. You may try to delete it manually.
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 339, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/usr/local/Cellar/azure-cli/2.27.2/libexec/lib/python3.9/site-packages/azure/cli/core/extension/operations.py", line 173, in _add_whl_ext
    raise CLIError('An error occurred. Pip failed with status code {}. '
knack.util.CLIError: An error occurred. Pip failed with status code 1. Use --debug for more information.

cli.azure.cli.core.azclierror: An error occurred. Pip failed with status code 1. Use --debug for more information.
az_command_data_logger: An error occurred. Pip failed with status code 1. Use --debug for more information.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x110582f70>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 8.997 seconds (init: 0.109, invoke: 8.888)
telemetry.save: Save telemetry record of length 3238 in cache
telemetry.check: Negative: The /Users/freedev/.azure/telemetry.txt was modified at 2021-09-30 10:12:32.695331, which in less than 600.000000 s

**Comment by yonzhan** [comment]
route to service team

**Comment by harneetvirk** [comment]
azureml-core 1.33.0 requires python Python >=3.6, <3.9. I believe, you are trying to install vi cli on latest version of python 3.9/3.10

**Comment by freedev** [comment]
I see is finally available a distribution for azureml-core and now is possible successfully install azure-ml-cli:

    az extension add --name azure-cli-ml

I can close the ticket now.
