### ISSUE TITLE
`az acr login` fails with `DBus.Error.UnknownMethod`

### ISSUE THREAD

**Issue by robin-wayve** [Azure/azure-cli#19759]
## Describe the bug

`az acr login` fails on one of our servers, while succeeding on another server of ours with a near-identical setup.

**Command Name**
`az acr login`

**Errors:**
```
** Message: 15:16:10.503: Remote error from secret service: org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/login
Error saving credentials: error storing credentials - err: exit status 1, out: `No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/login`
Login failed.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az acr login -n {}`

## Expected Behavior

```
Login Succeeded
```

## Environment Summary
```
Linux-5.4.0-81-generic-x86_64-with-debian-buster-sid, Ubuntu 18.04.6 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.28.0
```

**Comment by robin-wayve** [comment]
I think installing the `pass` package seems to have worked around the problem but I have no idea why? 😄

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@robin-wayve Apologies for the late reply. Could you please refer [this](https://unix.stackexchange.com/questions/265503/how-do-i-fix-no-such-secret-collection-at-path-for-gnome-keyring-and-arch-l/295652) article and [this](https://github.com/zalando/go-keyring/issues/18) github thread and check if that helps? Also this github thread has been inactive for quite sometime. Could you confirm if you still need assistance on this? Awaiting your reply.

**Comment by robin-wayve** [comment]
As I mentioned before, I worked around this by installing `pass` (with `sudo apt install pass` on Ubuntu 18.04) -- I didn't look into exactly why that solved the issue.

I left this open in case this dependency problem relates directly to Azure CLI: the documentation does not mention needing to install any other packages in order for Azure CLI to work so I wasn't sure where the problem lies.

**Comment by navba-MSFT** [comment]
@robin-wayve Thanks for your reply. We will get back to you once we have more details.
@toddysm @luisdlp @northtyphoon Could you please look into this issue and provide an update on this thread ?

**Comment by Wwwsylvia** [comment]
Hi @robin-wayve , thanks for the feedback.  `az acr login` internally calls `docker login`,  so this error was probably thrown by docker. 
Can you compare the docker version on the machine where this issue happened and the another machine?
