### ISSUE TITLE
CVM security profile Cli extension support request

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#19754]
**Is your feature request related to a problem? Please describe.**

Gallery team currently plans to support a new field 'SecurityProfile' for feature 'Confidential VM'. The security profile will be a part of os disk encryption, user can choose encryption type and disk encryption set.

**Describe the solution you'd like**

Currently for cli command "az sig image-version create -h",
add a new option "--target-region-cvm-encryption", and format for each region is "<os_cvm_encryption_type>, <os_cvm_des>"

In the future, we might add support for data disk encryption, that means changing format of "--target-region-cvm-encryption", will it be a breaking change?

**Describe alternatives you've considered**

Currently for cli command "az sig image-version create -h",
we can see that there is an option "--target-region-encryption", this is for SSE-CMK encryption. We plan to use this option for CVM encryption as well.
Current value for option "--target-region-encryption" is "<os_des>,<lun1>,<lun1_des>,<lun2>,<lun2_des>" of each region, proposed solution is to update it to be  "<os_ssecmk_des>,**<os_cvm_encryption_type>, <os_cvm_des>**,<lun1>,<lun1_ssecmk_des>,<lun2>,<lun2_ssecmk_des>" 

**Additional context**

Swagger link: https://github.com/Azure/azure-rest-api-specs/pull/16185/files
For CLI Extension, ApiVersions: 2021_07_01
For official CLI, ApiVersions: 2021_10_01

target date: end of October/early Nov

**Comment by yonzhan** [comment]
Compute

**Comment by kangsun-ctrl** [comment]
> Does this feature target for Ignite event?

The estimate delivery target date of this feature is Nov

**Comment by zhoxing-ms** [comment]
@kangsun-ctrl May I ask do you mean that the format of parameter `--target-region-encryption` should change from `<os_des>,<lun1>,<lun1_des>,<lun2>,<lun2_des>` to `<os_des>, <os_cvm_encryption_type>, <os_cvm_des>, <lun1>, <lun1_des>, <lun2>, <lun2_des>`?
If so, there is a breaking change in this requirement because it will change the passing logic of existing parameter. Could we consider adding a new parameter to support this feature and adding an deprecate flag to the existing parameters without affecting the existing usage?

**Comment by zhoxing-ms** [comment]
@kangsun-ctrl In addition, do you want us to create an new extension to support this feature?

**Comment by kangsun-ctrl** [comment]
> @kangsun-ctrl In addition, do you want us to create an new extension to support this feature?

Yeah, we hope it can be an extension request so we can ship it ASAP once backend is ready.

**Comment by zhoxing-ms** [comment]
> I was meaning current design is "<os_cvm_encryption_type>, <os_cvm_des>" of each region, it is only for os disk, and and in the future we might want to support data disks, which could be "<os_cvm_encryption_type>, <os_cvm_des> ,<lun1_cvm_encryption_type>, <lun1_des>,,<lun2_cvm_encryption_type>, <lun2_des>", will this be a breaking change?

If the original `<os_cvm_encryption_type>, <os_cvm_des>` can be supported after changing to `<os_cvm_encryption_type>, <os_cvm_des> ,<lun1_cvm_encryption_type>, <lun1_des>,,<lun2_cvm_encryption_type>, <lun2_des>`, it is not breaking change. However, it is still recommended to use two parameters to avoid user confusion，one is used to set `<os_cvm_encryption_type>, <os_cvm_des>` and the other is used to set `<lun1_cvm_encryption_type>, <lun1_des>,,<lun2_cvm_encryption_type>, <lun2_des>`

**Comment by zhoxing-ms** [comment]
Confirmed with @kangsun-ctrl and @grace-liang on Teams that this feature is implemented in the official CLI
