### ISSUE TITLE
Ephemeral OS Disk Placement option for customers to choose the Ephemeral OS disk provisioning location.

### ISSUE THREAD

**Issue by hari-bodicherla** [Azure/azure-cli#19751]
**Is your feature request related to a problem? Please describe.**
 we currently support Ephemeral os disks provisioning from the dedicated Cache disk space that comes with the VM size. So the customer is limited to use the max cache disk size space for provisioning the ephemeral OS disk. Due to increasing adaptation of Ephemeral OS disk and having a wide variety of VM Sizes without Cache disk space but having the temp disk space, we have implemented and started supporting the provisioning of Ephemeral OS disk from temp disk space also which will ensure customers can use the VM Sizes without Cache disk but with Temp disk space. Currently, VM Sizes which are having premium storage only support Cache disk, and also our popular lsv2 series does have a large temp disk but does not support Cache disk. so this feature can help in all these cases.

**Describe the solution you'd like**
This change exposes a new param along with the boolean param ephemeral-os-disk in the create VM CLI cmds. Customer can choose the Ephemeral OS disk location to be in either Cache disk or resource disk by setting the new param EphemeralDisklocation value to CacheDisk or ResourceDisk

**Describe alternatives you've considered**
N/A

**Additional context**

The cli cmds to be updated are az vmss create, az vm create

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@hari-bodicherla I'm sorry for my late reply because I'm on a long holiday. May I ask have the updates of Swagger and Python SDK been completed? The development and release of CLI depends on them first.
If so, could you provide the PR of specific Swagger changes, the example of request parameters and the specific design of CLI commands?

**Comment by hari-bodicherla** [comment]
> @hari-bodicherla I'm sorry for my late reply because I'm on a long holiday. May I ask have the updates of Swagger and Python SDK been completed? The development and release of CLI depends on them first. If so, could you provide the PR of specific Swagger changes, the example of request parameters and the specific design of CLI commands?

Np Xing, Sorry for bothering you on your holiday vacations. 
Here is the swagger link PR: https://github.com/Azure/azure-rest-api-specs/pull/8847 ( As i mentioned this one is merged into swagger long time back in 2019-12-01 API version) So I am sure that SDK python should have these changes.

Updates should be like 
For **az vmss create, az vm** create cmds, currently we have param called [--ephemeral-os-disk {false, true}] , we should have another param called that goes together with this is **[--ephemeral-os-disk-placement {CacheDisk,ResourceDisk}]** which customer can set when customer selected the **ephemeral-os-disk** value as **true**.

**Comment by wangzelin007** [comment]
@hari-bodicherla Hi,
May I ask did vmss support `"placement": "CacheDisk"`?
When I read examples\compute\CreateAScaleSetWithDiffOsDiskUsingDiffDiskPlacement.json, I only find `"placement": "ResourceDisk"` examples.
