### ISSUE TITLE
Az extension is required

### ISSUE THREAD

**Issue by isiahto** [Azure/azure-cli#19764]
This command requires `azure-devops` extensions:
`az extension add --name azure-devops`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9141b71a-a774-9d71-4e81-47c5762f831b
* Version Independent ID: 0ca15749-b657-37f9-24ea-0a420458089f
* Content: [Azure Artifacts](https://docs.microsoft.com/en-us/cli/azure/service-page/azure%20artifacts?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/service-page/Azure Artifacts.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/service-page/Azure Artifacts.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by isiahto** [comment]
Add a [link](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops) to additional details?

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
Please reopen if you still need assistance.
