### ISSUE TITLE
Support for adding/updating BGP community values on virtual networks 

### ISSUE THREAD

**Issue by tanuballa** [Azure/azure-cli#19763]
**Is your feature request related to a problem? Please describe.**
This feature request is for CLI support for a new ExpressRoute/virtual network feature that allows a user to set a BGP community value on their virtual network. This will associate the custom value to the virtual network via the NRP schema, at which point the ExpressRoute gateway will include the custom value in the routing information for packets sent back to on-premises. This enables users to see which virtual network their traffic is coming from in the case of complicated Azure networking setups.

**Describe the solution you'd like**
We would like to be able to set the custom BGP community value on a virtual network at creation time, or be able to update an existing virtual network with a new BGP community value.

**Describe alternatives you've considered**
We already have PowerShell support for adding a value upon virtual network creation (see the -BgpCommunity field listed [here](https://docs.microsoft.com/en-us/powershell/module/az.network/new-azvirtualnetwork?view=azps-6.4.0)) and update the value by changing the property $vnetvariable.BgpCommunities.VirtualNetworkCommunity and using Set-AzVirtualNetwork.

**Additional context**
Minimum API Version: 2020-06-01
Swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2020-06-01/virtualNetwork.json
Feature Status: Not released, can test by working with Tanu Balla (taballa) to enable feature flags on subscription
ETA: Aiming for Public Preview by Ignite Nov21

**Comment by yonzhan** [comment]
network
