### ISSUE TITLE
Specifying "Developer" as the sku but ended up with "Enterprise"

### ISSUE THREAD

**Issue by LH-MSFT** [Azure/azure-cli#19762]
C:\>az sql vm group create -n sql-fc -l eastus -g winsrvgroup --image-offer SQL2017-WS2016 --image-sku Developer ...
{
  "id": "/subscriptions/xxx/resourceGroups/WinSrvGroup/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachineGroups/sql-fc",
  "location": "eastus",
  "name": "sql-fc",
  "provisioningState": "Succeeded",
  "resourceGroup": "WinSrvGroup",
  "sqlImageOffer": "SQL2017-WS2016",
  "sqlImageSku": "Enterprise",
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888091be-7582-cd4b-9cee-f4b504290272
* Version Independent ID: f199c46d-8cec-aa84-93c7-0f383d6fdc95
* Content: [az sql vm group](https://docs.microsoft.com/en-us/cli/azure/sql/vm/group?view=azure-cli-latest#az-sql-vm-group-create)
* Content Source: [latest/docs-ref-autogen/sql/vm/group.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/sql/vm/group.yml)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team
