### ISSUE TITLE
az aks get-credentials does not respect --context when --admin flag is passed

### ISSUE THREAD

**Issue by geekifier** [Azure/azure-cli#19779]
```shell
 $ az version
{
  "azure-cli": "2.28.0",
  "azure-cli-core": "2.28.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

## Issue:

When both the `--context` and `--admin` flags are set for `az aks get-credentials`, the `context` flag is not fully respected. Instead, a context gets created with an `-admin` suffix. This is undocumented behavior.

## Steps to reproduce

`az aks get-credentials --resource-group rg-foo--name cluster-foo --overwrite-existing --admin --context cluster-bar`

The above results in a `~/kube/config` file entry with `cluster-foo` under `clusters:`, and `cluster-foo-admin` under `contexts:`.

## Expectations:

When `--context` option is specified, the context name should reflect the value specified with `--context`. No strings should be appended to the context name.

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@geekifier Apologies for the late reply. Thanks for the feedback. The above PR has been created to address this. In the meantime, if you have any questions, please feel free to ask.
