### ISSUE TITLE
az cosmosdb identity assign fails for user assigned identity

### ISSUE THREAD

**Issue by sanjaydebnath** [Azure/azure-cli#19776]
**Describe the bug**
When I try to add an existing user assigned identity using "az cosmosdb identity assign" command, it fails with error saying "unrecognized arguments: --identities".

**To Reproduce**
$applicationIdentity="********"
$RG_NAME="******"
$COSMOS_NAME = "*****"
$identityResourceId = az identity show -g $RG_NAME -n $applicationIdentity --query id -o tsv
az cosmosdb identity assign --name $COSMOS_NAME -g $RG_NAME --identities $identityResourceId

**Expected behavior**
We should be able to assign user defined identity using az cli. Documentation says its available https://docs.microsoft.com/en-us/cli/azure/cosmosdb/identity?view=azure-cli-latest#az_cosmosdb_identity_assign. But if I search for az cosmosdb identity assign --help, it does not show --identities argument as an option.

![image](https://user-images.githubusercontent.com/28987981/135998906-de3f6319-8fe3-45bc-97b6-6c250578d5cf.png)

**Environment summary**
Bash on Windows with

{
  "azure-cli": "2.28.0",
  "azure-cli-core": "2.28.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "account": "0.2.1",
    "aks-preview": "0.5.34",
    "application-insights": "0.1.14",
    "cosmosdb-preview": "0.10.0",
    "deploy-to-azure": "0.2.0",
    "dev-spaces": "1.0.6",
    "kusto": "0.3.0"
  }
}

**Additional context**
It does work from Azure portal through (takes some time to refresh).

**Comment by yonzhan** [comment]
route to service team

**Comment by zehende** [comment]
Hello @sanjaydebnath - support for user-assigned identity, and the `--identities` parameter, was released on [10-12](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#cosmos-db-1). Please verify that you are using this version or higher and try again. If you would like to manage system-assigned identity, the `--identities` parameter is not needed - `identity assign` will assign system-managed identity, and `identity remove` will remove it.

**Comment by navba-MSFT** [comment]
@sanjaydebnath Could you please let me know if you had a chance to follow the above suggestion ? Please let me know if you need any further assistance on this. Awaiting your reply.
