### ISSUE TITLE
Support for cross-region copy of incremental snapshots

### ISSUE THREAD

**Issue by jamesc** [Azure/azure-cli#19773]
**Resource Provider**
Microsoft.Compute

**Description of Feature or Work Requested**
Support CopyStart of incremental snapshots of managed disks via CLI. The REST API changes introduces a new option called CopyStart for the creationOption for creating snapshots of managed disks. 
```
{ 
  "id": "/subscriptions/sub/resourceGroups/rg1e47ff76-fc12-483f-9c76-4b74673669ef/providers/Microsoft.Compute/disks/slowDisk",    
  "name": "slowDisk"    
  "type": "Microsoft.Compute/snapshots",    
  "location": "westus",    
  "sku": {    
    "name": "Standard_LRS",    
    "tier": "Standard"    
  },    
  "properties": {    
    "osType": "Windows",    
    "creationData": {    
      "createOption": "CopyStart", 
      "sourceResourceId": "/subscriptions/sub/resourceGroups/resg/providers/Microsoft.Compute/snapshots/mySnapshot
    }
  },    
  "tags": {    
    "department": "Development",    
    "project": "ManagedDisks"    
  }   
  "provisioningState": "Pending",  
  "completionPercent": 75 // readonly: ignored on inputs 
}   
```

**Minimum API Version Required**

**Swagger Link**
* https://github.com/Azure/azure-rest-api-specs/pull/15665
* https://github.com/Azure/azure-rest-api-specs/pull/15665/commits/0f1cd823abe0c4508984619b0fb94387c8dac4fd

Example: https://github.com/rytruong/azure-rest-api-specs/blob/1f561a67f29460998e4ff8020e0691779ff50756/specification/compute/resource-manager/Microsoft.Compute/stable/2021-04-01/examples/CreateASnapshotFromAnExistingSnapshotInDifferentRegion.json

**Target Date**
Ignite

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@jamesc So CLI needs to add a new parameter to support Copy Start, right? Could you provide the design which includes specific commands and parameters that need to be modified?

**Comment by evelyn-ys** [comment]
Thanks @vikramd-ms @ramankumarlive. So we will autodetect `CopyStart` for cross-region scenario and provide an extra `--copy-start` to specify forcibly.

Do both `az disk create` and `az snapshot create` need to change or only `az snapshot create` need this?

**Comment by ramankumarlive** [comment]
@arorasam 

#1: We expect to announce the GA of the feature by the end of this month or early March. 
#2: We dont have the performance numbers to share now. We can share the number by the end of April 2022. 
#3: You can find the list of regions here: https://docs.microsoft.com/en-us/azure/virtual-machines/disks-incremental-snapshots?tabs=azure-cli#restrictions-1

**Comment by ramankumarlive** [comment]
@arorasam the feature in GA now worldwide.
