### ISSUE TITLE
Unable to Use az synapse workspace-package Command

### ISSUE THREAD

**Issue by osuleiman** [Azure/azure-cli#19780]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When trying to list the workspace packages setup on a workspace using the command "az synapse workspace-package list --workspace-name <workspaceName>" (ref: https://docs.microsoft.com/en-us/cli/azure/synapse/workspace-package?view=azure-cli-latest#az_synapse_workspace_package_list), we get an error as follows:

'workspace-package' is misspelled or not recognized by the system.

This has been tested using the latest Az CLI version available (using Azure cloud shell and locally): 

![image](https://user-images.githubusercontent.com/34806809/136051715-137b03f4-0081-4892-b07d-ba7a504b8c06.png)

When using "az synapse --help" command, workspace-pacakge does not exist in the list of available commands:

![image](https://user-images.githubusercontent.com/34806809/136051944-c3e58de3-9283-4475-bd98-ce7e7bd0316f.png)

**Comment by yonzhan** [comment]
route to service team
