### ISSUE TITLE
Source-vault is not a required field for creating Disk Encryption Sets 

### ISSUE THREAD

**Issue by ramankumarlive** [Azure/azure-cli#19786]
**Resource Provider**
Compute.DiskRP

**Description of Feature or Work Requested**
It has been a while since we removed the source-vault as required field for creating Disk Encryption Set. However, it looks like CLI is still not updated. 

 az disk-encryption-set create -h

Command
    az disk-encryption-set create : Create a disk encryption set.

Arguments
    --key-url                       [Required] : URL pointing to a key or secret in KeyVault.
    --name -n                       [Required] : Name of disk encryption set.
    --resource-group -g             [Required] : Name of resource group. You can configure the
                                                 default group using `az configure --defaults
                                                 group=<name>`.
    **--source-vault                  [Required] : Name or ID of the KeyVault containing the key or
                                                 secret.**
    --auto-rotation --enable-auto-key-rotation : Enable automatic rotation of keys.  Allowed values:
                                                 false, true.

**Minimum API Version Required**
2020-09-30

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/11202

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2020-09-30/disk.json#L2200

**Target Date**
10/30/2021

**Comment by ramankumarlive** [comment]
@zhoxing-ms early december will be late. We are planning to announce GA by mid-November. Can we plan to release the changes before thanks giving holidays?

**Comment by PARADISSEEKR** [comment]
@ramankumarlive  Source-vault is a required field in the current SDK(23.1.0), could you please release a new SDK?

**Comment by zhoxing-ms** [comment]
@ramankumarlive As mentioned by @PARADISSEEKR. At present, because the declaration of `source_vault` in the Python SDK is required, so the required declaration should be removed from the Python SDK and Swagger

**Comment by zhoxing-ms** [comment]
@ramankumarlive Please note if the public Python SDK cannot be updated and released tomorrow, then it will not catch up with the release of this sprint and can only be postponed to the next sprint (official release date is **2022-01-04**)

**Comment by parkhyukjun89** [comment]
Disk encryption set no longer uses KeyVaultAndSecretReference; it uses KeyForDiskEncryptionSet instead, which does not require source_vault. https://github.com/Azure/azure-sdk-for-python/blob/053a2bcedd775f4a557c2ad904ce7a0ef38e8bee/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2020_09_30/models/_models_py3.py#L2865

**Comment by ramankumarlive** [comment]
@zhoxing-ms do you have everything you need to make the changes in the Azure CLI now?

**Comment by PARADISSEEKR** [comment]
Hi,  @parkhyukjun89 @ramankumarlive , after use `KeyForDiskEncryptionSet`, source-vault is not a required field, but `az disk-encryption-set update` will return an error when updating `--source-vault` field for a resource without `sourceVault`. Does the `update` command need to be changed?

**Comment by ramankumarlive** [comment]
@PARADISSEEKR KeyVaultAccessForbidden error means that you havent provided the DiskEncryptionSet permission in the new Key Vault before associating the DiskEncryptionSet to a Key in the KeyVault. Please provide necessary permission before updating the DiskEncryptionSet with a new Key Url.
