### ISSUE TITLE
Error is coming while running az

### ISSUE THREAD

**Issue by gkrout** [Azure/azure-cli#19788]
## Describe the bug

**Command Name**
`az group delete`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group delete --name {}`

## Environment Summary
```
Linux-5.4.0-1059-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment]
ARM

**Comment by gkrout** [comment]
Thanks
