### ISSUE TITLE
az apim release

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-cli#19791]
Hello

I'd like to know the release plan for az apim (will it be released?), as it still throws this message when used:

Command group 'apim' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus

I need to use it in a production environment.

Thanks.

**Comment by navba-MSFT** [comment]
@sjuarezgx Apologies for the late reply. We are looking into this and we will update once we have more details.

@adrianhall Could you please let us know when will the az apim CLI command be ready for production use ? Awaiting your reply.

**Comment by adrianhall** [comment]
Hello,

We are currently working on that specific release!  The next release will be GA, not experimental.

#please-close

**Comment by adrianhall** [comment]
The service team is not in control of the release schedule for the az CLI.  As a result, I do not have that information.

**Comment by sjuarezgx** [comment]
Ok, thank you.

**Comment by jsntcy** [comment]
This change will be released in July 5th.
