### ISSUE TITLE
--kerberos5i-rw and others missing option

### ISSUE THREAD

**Issue by elfcounsel** [Azure/azure-cli#19798]
__--kerberos5i-rw_ 
_--kerberos5i-r__
and all the other kerberos options look like they need a false | true set for them and the docs don't indicate that. If you don't indicate true | false you get error: "_argument --kerberos5i-rw: expected one argument_"

Would be nice to have an example of how to configure a krb encrypted volume from the CLI. There are a lot of dependencies for the commands that aren't noted.

_"Parameter allowed-clients needs to be set when protocol-type is NFSv4.1"_
So I set the allowed-clients to 0.0.0.0/0

_Parameter rule-index needs to be set when protocol-type is NFSv4.1_
So i set the --rule-index to 1

_(BadRequest) Mismatch between KerberosEnabled flag value and ExportPolicyRule's access type parameter values._
I'm stuck here. I don't know wht "ExportPolicyRule" is. I guessed and set "--policy-enforced true" but that didn't work.

As it stands now the command I am issuing is: az netappfiles volume create -g $rg --account-name $account --pool-name $pool --name $volname --location $region --usage-threshold 100 --file-path $volname --vnet $vnet --subnet $subnet --protocol-types NFSv4.1 --allowed-clients 0.0.00/0 --rule-index 1 --kerberos-enabled true --kerberos5i-rw true --policy-enforced true

...but it's failing and I am stuck with whatever this ExportPolicyRule setting is. Nothing in the docs indicating what that is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 298ada99-369a-1c65-50ca-617931d26b7a
* Version Independent ID: 5fbd1cdf-e27f-8ffe-1c72-14f5d9e186f1
* Content: [az netappfiles volume](https://docs.microsoft.com/en-us/cli/azure/netappfiles/volume?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/netappfiles/volume.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/netappfiles/volume.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team
