### ISSUE TITLE
[VM] Could the open-port command allow specifying a port?

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1982]
The simplified `az network nsg rule create` command is awesome, however, it would be great if you could use the `az vm open-port` command as a VM-focused way of achieving the same thing, but without having to look up and manage the NSG explicitly (fewer concept counts for new Azure users would be great!).

Since `az vm create` auto-creates an NSG behind the scenes, being able to expose a port on the VM would help support an easier "getting started" experience with VMs. Instead of the `open-port` command exposing all ports, it would nice to do something like the following:

```shell
az vm create -g <group> -n <name> --image UbuntuLTS
az vm open-port -g <group> -n <name> -p 80
```

Even further, I would actually love if it the `az vm create` command allowed specifying a list of ports to expose on the resulting NSG. Something like the following would be amazing:

```shell
az vm create -g <group> -n <name> --image UbuntuLTS --expose-ports 80,443
```

Both of these help achieve the same goal of preventing a user from needing to think about the NSG until necessary. Since exposing a port is such a common operation, it seems like this would be a nice companion/extension of the already-great abstraction created by the `az vm create` command in the first place.

**Comment by devigned** [comment]
Based on the name of "open-port" I though it was intended to be used with `-p $PORT`. I was actually a bit surprised when it open *all* traffic.

**Comment by lostintangent** [comment]
@devigned Me too :) This command would be immensely useful if it just had a `-p` flag.

**Comment by tjprescott** [comment]
Reviewing the email threads with @squillace, it looks like there wouldn't be a problem exposing a port(s) parameter here. I felt the default of "*" was a bit broad anyways.
