### ISSUE TITLE
AZ iot 

### ISSUE THREAD

**Issue by chiomao23** [Azure/azure-cli#19822]
## Describe the bug

**Command Name**
`az iot`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot {} {} --device-id {} --login {}`

## Environment Summary
```
Linux-5.4.0-1059-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.28.0

Extensions:
azure-iot 0.11.0
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by vilit1** [comment]
Closing the issue due to no response. If you still need help with this issue, please re-open.
