### ISSUE TITLE
scheduled-query must move to 2021-02-01-preview ASAP

### ISSUE THREAD

**Issue by avjerafi** [Azure/azure-cli#19831]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Scheduled Query Rules (Azure Log Search Alerts) plans to publish a new stable API version by end of October.
The new stable API version will be: 2021-08-01.
Traces shown to us by CSS have indicated that the CLI is currently using API version 2020-05-01-preview.
Please move away from the 2020-05-01-preview API version.
API version 2021-02-01-preview is already public and offers the same features and identical structure and defaults as 2021-08-01, which have changed since 2020-05-01-preview.
We ask you to to please move to 2021-02-01-preview ASAP, and later to 2021-08-01 as soon as it becomes GA.

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
@avjerafi, It's already been done in PR https://github.com/Azure/azure-cli-extensions/pull/3753

**Comment by kairu-ms** [comment]
Please create another feature request issue when 2021-08-01 is ready.

**Comment by avjerafi** [comment]
> @avjerafi, It's already been done in PR [Azure/azure-cli-extensions#3753](https://github.com/Azure/azure-cli-extensions/pull/3753)

Thank you Kai. Can you please direct me to where could I have found this fact in the code in the repo? I looked everywhere for evidence of the api versions being used for scheduled-query before submitting this issue, but failed to find any.
