### ISSUE TITLE
[VM] Allow creating an availability set along with a VM

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#1983]
Would it be reasonable for the `az vm create` command to allow auto-creating an availability set if the `--availability-set` parameter was specified, but the specified name didn't already exist. This is the same behavior of other arguments (e.g. `--public-ip-address`, `vnet`), and would help make the `az vm create` command a little more "atomic", which it seems to already be striving for.

**Comment by tjprescott** [comment]
This is a very reasonable request that we can do now that we've changed how VM create is executed.

**Comment by yugangw-msft** [comment]
We will live with what we have, till we have enough user voices
