### ISSUE TITLE
Updating devops extension

### ISSUE THREAD

**Issue by SenseiJoe** [Azure/azure-cli#19849]
How do I update a previously installed devops extension?
Looks like what I need is to publish a devops extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 688236b5-3de5-2adf-4e45-d080dfeac2aa
* Version Independent ID: 3b62252a-245b-1df1-9024-1f62b5338557
* Content: [az devops extension](https://docs.microsoft.com/en-us/cli/azure/devops/extension?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/devops/extension.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/devops/extension.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
You can use this command `az extension update -n azure-devops` to update an already installed extension.
