### ISSUE TITLE
WebApp:Cannot use `appservice plan create` with dynamic SKU (Y1)

### ISSUE THREAD

**Issue by viclin-msft** [Azure/azure-cli#19864]
**Is your feature request related to a problem? Please describe.**

Function apps require dynamic SKU (#8388). I would like to create one with a custom name using `appservice plan create`, but `Y1` is not currently supported.

```
$ az appservice plan create -g MyResourceGroup -n MyPlan --sku Y1
az appservice plan create: 'Y1' is not a valid value for '--sku'. Allowed values: F1, FREE, D1, SHARED, B1, B2, B3, S1, S2, S3, P1V2, P2V2, P3V2, P1V3, P2V3, P3V3, PC2, PC3, PC4, I1, I2, I3, I1v2, I2v2, I3v2.
```

**Describe the solution you'd like**

Ability to run the above command without error.

**Describe alternatives you've considered**

Using `az resource create` as suggested in #8388:

```
az resource create
    --resource-group myresourcegroup
    --name myconsumptionplan
    --resource-type Microsoft.web/serverfarms
    --is-full-object
    --properties "{\"location\":\"northeurope\",\"sku\":{\"name\":\"Y1\",\"tier\":\"Dynamic\"}}"
```

**Comment by yonzhan** [comment]
route to service team

**Comment by viclin-msft** [comment]
@Kotasudhakarreddy thanks, I wasn't aware of the difference. I just tried `az functionapp plan create --sku Y1` but this also doesn't work. The error is:

```
$ az functionapp plan create -n testplan --resource-group test-rg --sku Y1
Invalid sku(pricing tier), please refer to command help for valid values
```

yet `az functionapp plan create -h` doesn't show a list of valid values as described in the error message.

**Comment by Kotasudhakarreddy** [comment]
@viclin-msft - to create a function app based on consumption(server less) plan with `--sku Y1` , it is not required to create an explicit `function plan`. Using `--consumption-plan-location` option during `function app create` will create the necessary host plan for you with `SKU Y1`. below is the sample. Please refer [here](https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest#az_functionapp_create)  for more details.

`az functionapp create --consumption-plan-location westus --name MyUniqueAppName --os-type Windows --resource-group MyResourceGroup --runtime dotnet --storage-account MyStorageAccount`

**Comment by panchagnula** [comment]
Closing this since the error or usage is explained in the gitHub issue.
