### ISSUE TITLE
Support for updating load balancer backendpool

### ISSUE THREAD

**Issue by thisisanniefang** [Azure/azure-cli#19867]
**Resource Provider**
Microsoft.Network/LoadBalancers

**Description of Feature or Work Requested**
We'd like to support the ability to update a load balancer's backendpool without having to run both delete/add commands. This is already supported through PowerShell - https://docs.microsoft.com/en-us/powershell/module/az.network/set-azloadbalancerbackendaddresspool?view=azps-6.4.0

For parity's sake, we'd like to support the command "az network lb address-pool update", which should behave as the above PowerShell command does, as part of the supported CLI commands here: https://docs.microsoft.com/en-us/cli/azure/network/lb?view=azure-cli-latest

Here is the documentation for updating a backend pool via REST API as well: https://docs.microsoft.com/en-us/rest/api/load-balancer/load-balancer-backend-address-pools/create-or-update

**Minimum API Version Required**

**Swagger Link**

**Target Date**
ASAP

**Comment by thisisanniefang** [comment]
@kairu-ms I saw the associated PRs, just to confirm - has this been rolled out to prod already?

**Comment by kairu-ms** [comment]
@thisisanniefang It's released.
