### ISSUE TITLE
az sql server ad-admin create throws error:  The 'parameters.properties' segment in the url is invalid.

### ISSUE THREAD

**Issue by guestdj** [Azure/azure-cli#19873]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When running this command:
`az sql server ad-admin create --resource-group --server --subscription --object-id --output tsv --debug`

in Windows terminal or Azure Portal Cli I get this error:

cli.azure.cli.core.azclierror: (InvalidResourceIdSegment) The 'parameters.properties' segment in the url is invalid.

I have noted at least 5 other identical issues that have been raised that are not resolved, is this not a priority for MS?

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

Error log (when in debug mode)
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/48bd5a14-5dcf-4cec-8e95-922b2ebb8882/resourceGroups/rg-asset_data_loader-stg-uks/providers/Microsoft.Sql/servers/lqsqlassetdataloaderstguks01/administrators/ActiveDirectory?api-version=2020-11-01-preview HTTP/1.1" 400 210
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '210'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'd83ff2ca-7bdc-44d4-adb0-f64af4ac9b67'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '827cffab-9bed-429d-ad6a-4be0f498fb7b'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORTHEUROPE:20211013T080329Z:827cffab-9bed-429d-ad6a-4be0f498fb7b'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 13 Oct 2021 08:03:29 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"details":[{"code":"InvalidResourceIdSegment","message":"","target":"parameters.properties"}],"code":"InvalidResourceIdSegment","message":"The 'parameters.properties' segment in the url is invalid."}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/sql/custom.py", line 3703, in server_ad_admin_set
    parameters=kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/sql/operations/_server_azure_ad_administrators_operations.py", line 219, in begin_create_or_update
    **kwargs
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/sql/operations/_server_azure_ad_administrators_operations.py", line 160, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InvalidResourceIdSegment) The 'parameters.properties' segment in the url is invalid.

cli.azure.cli.core.azclierror: (InvalidResourceIdSegment) The 'parameters.properties' segment in the url is invalid.
az_command_data_logger: (InvalidResourceIdSegment) The 'parameters.properties' segment in the url is invalid.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f768c3c2400>]

**Comment by guestdj** [comment]
Is there any update on this?

**Comment by jamesryanuk** [comment]
I encountered this issue today, but found a workaround in #20795. The `--display-name` parameter appears to be required, despite what it says on the [documentation](https://docs.microsoft.com/en-us/cli/azure/sql/server/ad-admin?view=azure-cli-latest). When I supply this parameter the command works as expected.

**Comment by RakeshMohanMSFT** [comment]
@guestdj Let us know if suggestion of @jamesryanuk works for you
