### ISSUE TITLE
Cannot create App plan in sub A for ASEv3 in Sub B  

### ISSUE THREAD

**Issue by bengimblett** [Azure/azure-cli#19893]
## Describe the bug

**Command Name**
`az appservice plan create`

**Errors:**
```
App service environment 'subscriptions/<subB>/resourceGroups/ase-rg/providers/Microsoft.Web/hostingEnvironments/begimase' not found in subscription.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan create --name {} --resource-group {} --app-service-environment {} --location {} --number-of-workers {} --sku {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.29.0

Extensions:
aks-preview 0.5.34

```

**Comment by yonzhan** [comment]
route to service team

**Comment by bengimblett** [comment]
Template works, so it's just CLI and PS1

{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
   "parameters": {},
    "variables": {},
    "resources": [
      {
        "type": "Microsoft.Web/serverfarms",
        "apiVersion": "2020-06-01",
        "name": "begim-ase-wap2",
        "location": "uksouth",
        "sku": {
          "name": "I1v2"
        },
        "properties":{
            "capacity": 1,
            "hostingEnvironmentProfile": {
                "id": "/subscriptions/<subB>/resourceGroups/ase-rg/providers/Microsoft.Web/hostingEnvironments/begimase"
            }
        }
      }
    ]
  }
  
  #deploy context subA
