### ISSUE TITLE
Login to az acr fails

### ISSUE THREAD

**Issue by zlb323** [Azure/azure-cli#19906]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I am unable to login to my acr through the az acr login --name <name> command, I receive the error 

Error saving credentials: error storing credentials - err: exit status 1, out: `error storing credentials - err: exit status 1, out: `A specified logon session does not exist. It may already have been terminated.``
Login failed.

I have tried to disconnect from my vpn, restarting my computer, trying in both powershell and wsl and have not been able to fix this issue or encounter a more meaningful error message.

**To Reproduce**
```az acr login --name <name>```

**Expected behavior**
az cli logs in to my azure docker registry

**Environment summary**
I have tried this with a standard az cli install on both powershell and wsl. My docker engine is running via wsl2.

**Comment by navba-MSFT** [comment]
@zlb323 Apologies for the late reply. Could you please follow the above suggestions and let me know if you still face this issue ? Awaiting your reply.
