### ISSUE TITLE
ReceiveDisabled option missing in Service bus queue statuses

### ISSUE THREAD

**Issue by rangarnow** [Azure/azure-cli#19915]
Hi, 

**Is your feature request related to a problem? Please describe.**
Missing **ReceiveDisabled** option in Service bus queue status updated. While it's existing in Azure portal, Powershell command and Service bus documentation, it was deleted in one of the PR for Azure CLI:

https://github.com/Azure/azure-cli/pull/11566.

Official documentation about Service bus:
https://docs.microsoft.com/en-us/azure/service-bus-messaging/entity-suspend#queue-status.

Is it scheduled to delete it also in other components? (Azure portal for example). I need to use that option for setting my queue status and now I am not sure if it's good to rely on this queue status in production.

**Describe the solution you'd like**
Revert the setting back or clarify the purpose of deletion just in Azure CLI.

**Comment by rangarnow** [comment]
Hi, do you have any update about my question?

**Comment by Mortana89** [comment]
+1 here

**Comment by yonzhan** [comment]
service bus service team should take a look

**Comment by Saglodha** [comment]
@rangarnow, thanks for bringing this to our attention. As per my understanding, Receivedisabled holds true for Service bus queues. 

I would triage internally with team and keep you posted with additional updates.
