### ISSUE TITLE
Unable to create Linux datascience vm using azure cli 

### ISSUE THREAD

**Issue by kailashms** [Azure/azure-cli#1991]
Hi Team,

I am trying to create a Linux data science vm using azure cli .
using the below commands I was able to get the urn for the image.

azure vm image list-publishers [options] <location>

the command to create the vm:

 azure vm create -g johan -n  datascience1 -Q  microsoft-ads:linux-data-science-vm:linuxdsvm:1.0.2 -o johandisks187 -l westeurope -f newnic -y Linux --plan-name microsoft-ads --plan-publisher linux-data-science-vm --plan-product microsoft-ads:linux-data-science-vm:linuxdsvm: 

where we have given in the plan and publisher name and the product name.

But we are failing with the below details:

[error for command1.txt](https://github.com/Azure/azure-cli/files/757723/error.for.command1.txt)

we have also tried using the below command:

azure vm create -g johan -n  datascience -Q  microsoft-ads:linux-data-science-vm:linuxdsvm:1.0.2 -o johandisks187 -l westeurope -f newnic -y Linux
info:    Executing command vm create
+ Looking up the VM "datascience"
Enter username:  azure
Enter password for azure: ************
Confirm password: ************
info:    Using the VM Size "Standard_DS1"
info:    The [OS, Data] Disk or image configuration requires storage account
+ Looking up the storage account johandisks187
+ Looking up the NIC "newnic"
info:    Found an existing NIC "newnic"
info:    Found an IP configuration with virtual network subnet id "/subscriptions/5eefe034-2471-4f40-96ea-e5e8a7dac305/resourceGroups/johan/providers/Microsoft.Network/virtualNetworks/johan-vnet/subnets/default" in the NIC "newnic"
info:    This is an NIC without publicIP configured
info:    The storage URI 'https://johandisks187.blob.core.windows.net/' will be used for boot diagnostics settings, and it can be overwritten by the parameter input of '--boot-diagnostics-storage-uri'.
+ Creating VM "datascience"
error:   Long running operation failed with error: 'Creating a virtual machine from Marketplace image requires Plan information in the request. OS disk name is cli5448053ac97934f2-os-1486473668342.'.
error:   Error information has been recorded to /root/.azure/azure.err
error:   vm create command failed

Here it shows the plan and publisher information.

[error2command.txt](https://github.com/Azure/azure-cli/files/757727/error2command.txt)

Could you please assist me in creatin the Linux data science vm,

**Comment by tjprescott** [comment]
Hi @kailashms, you are using Azure Xplat CLI, which is a different repo.  Please repost your issue here:
https://github.com/Azure/azure-xplat-cli
and they should be able to better assist you.
