### ISSUE TITLE
Azure Purview - Add private endpoint connection CLI commands support

### ISSUE THREAD

**Issue by shaileshsk94** [Azure/azure-cli#19921]
**Resource Provider**
Microsoft.Purview

**Description of Feature or Work Requested**
Requesting support for private endpoint connection and private link resource related CLI commands for Azure Purview
(similar to Azure storage)
https://docs.microsoft.com/en-us/cli/azure/storage/account/private-endpoint-connection?view=azure-cli-latest

**Minimum API Version Required**
2020-12-01-preview (This is our preview version which had PE support)
2021-07-01 is our current GA version

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/purview/resource-manager/Microsoft.Purview/stable/2021-07-01/purview.json

**Target Date**
We have a customer reachout for this. Azure Purview RP already supports PE related APIs. Basically, CLI support is missing. We would like to have this as early as possible to unblock customer.

**Comment by kairu-ms** [comment]
Hi @shaileshsk94, I close this issue as `Purview/account` is already supported in `az network private-endpoint-connection`.
