### ISSUE TITLE
"az batch pool supported-images list" error: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by MattMcL4475** [Azure/azure-cli#19934]
## Describe the bug

**Command Name**
`az batch pool supported-images list`

**Errors:**
```
'NoneType' object has no attribute 'startswith'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az batch pool supported-images list`

## Expected Behavior
The list of supported images is displayed.  Note that the docs say there are no required parameters: https://docs.microsoft.com/en-us/cli/azure/batch/pool/supported-images?view=azure-cli-latest

However, I was able to get this to work only when I specified all three of these parameters, so it seems they are required: 
--account-endpoint
--account-name
--subscription

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.29.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
@MattMcL4475 Apologies for the delay, Those parameters are optional if the environment variables are AZURE_BATCH_ENDPOINT, AZURE_BATCH_ACCESS_KEY, AZURE_BATCH_ACCOUNT.

Please update the latest of az cli 2.43.0 and retry.
