### ISSUE TITLE
On reshat 8.2 az cli not installed

### ISSUE THREAD

**Issue by himanshukgit** [Azure/azure-cli#19930]
sudo dnf install -y Azure-cli
Cmd gives err about 404 Fedora project epel proj not found on red hat 8.2

Workaround : sed -i 's/$releasever/8/g' 
 /etc/yum.repos.d/epel*.rep 

After that the az cli installed, make provision for future releases to avoid Fedora 404 error

**Comment by jiasli** [comment]
Per https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf, Azure CLI's repo is added to `/etc/yum.repos.d/azure-cli.repo`. `/etc/yum.repos.d/epel*.rep` is irrelevant to Azure CLI.
