### ISSUE TITLE
` az login --use-device-code` errors out with multiple accounts error.

### ISSUE THREAD

**Issue by pratiksanglikar** [Azure/azure-cli#19937]
```Powershell
azure-cli> az login --use-device-code
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <code> to authenticate.
Found multiple accounts with the same username. Please report to us via Github: https://github.com/Azure/azure-cli/issues/new
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This should only happen on the `dev` branch. 

It is triggered here:

https://github.com/Azure/azure-cli/blob/6442bedce93ea849dc02700fde4befef6313219a/src/azure-cli-core/azure/cli/core/auth/msal_authentication.py#L43-L45

The corresponding change on MSAL is https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/349.

Please run `azdev setup` to re-setup the CLI dev environment which will bump MSAL and see if the issue gone.
