### ISSUE TITLE
the azure dev support mentiones i cant trigger/start logic apps with azure cli on dictionary parameters

### ISSUE THREAD

**Issue by rifaterdemsahin** [Azure/azure-cli#19932]
if that is true why they are here and documented here?
https://docs.microsoft.com/en-us/cli/azure/logicapp?view=azure-cli-latest#az_logicapp_start

**If the logic apps can't be used in automation with parameters why do they exist in the first place ?**

**this trigger** to take in a dictionary parameter **to start**
![image](https://user-images.githubusercontent.com/5270036/137934171-d6b8ec6a-5aed-4fb2-81ba-1e299aac82d6.png)

**### _This is regarding the ticket you have raised with Microsoft - 2109170050000932_**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e21e02-e42f-a0aa-e437-0ec8e73ab81b
* Version Independent ID: 29316eb6-a99d-6ccf-6e4d-5e352e391c31
* Content: [az logicapp](https://docs.microsoft.com/en-us/cli/azure/logicapp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/logicapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/logicapp.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rifaterdemsahin** [comment]
I need this start with a dictionary parameter to work from my dockercontainer
![image](https://user-images.githubusercontent.com/5270036/137932822-9ced8afe-0940-48fc-8b6e-bd23f8f3e640.png)

**Comment by yonzhan** [comment]
route to service team

**Comment by archidda** [comment]
The commands starting with `az logicapp` are used for Logic App Standard SKU offering only. `az logicapp start` starts the logic app site. This doesn't trigger the workflows in it. To trigger a workflow, we need workflow level commands which are not released yet.


From the screenshot, it looks like you are using the LogicApp Consumption SKU. For that these are the commands you can use-
https://docs.microsoft.com/en-us/cli/azure/logic?view=azure-cli-latest

**Comment by archidda** [comment]
I understand, so your ask for logicapp CLI extension is of a command to trigger a workflow with custom payload(like a dictionary). As of latest version, we do not have a command for that.

only workaround I can think of is to get the callback URI from portal or from ARM client, ad then call it again using ARM client. What are your security concerns with ARMClient?
