### ISSUE TITLE
VM Access: command renaming

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#1995]
This is polishing like change regarding 4 existing commands under `vm access`, including `delete-linux-user`, `reset-linux-ssh`, `reset-windows-admin`, `set-linux-user`. The naming oddness reflects the service function difference between windows and linux vm, particularly on windows vm, you will not be able to add/rename/delete users, even though the API invoke always succeeds but nothing really happens at vm side
The change details are:
1. Rename category `vm access` to `vm user`
2. Collapse into 3 commands
    `delete`: delete a user from linux vm
    `update`: for windows vm, you can only update the admin password, for linux vm, you can add, or change both username and password, also you can upload public ssh key
    `reset-ssh`: reset linux vm’s SSH configurations

**Comment by tjprescott** [comment]
Instead of `vm user delete/update-user` it would make more sense to just call those commands `vm user update/delete` with `vm user reset-ssh` as the third command.

**Comment by yugangw-msft** [comment]
@tjprescott, thanks. I have update the text,
