### ISSUE TITLE
functionapp:az functionapp update doesn't support https-only true

### ISSUE THREAD

**Issue by gavinbarron** [Azure/azure-cli#19951]
**Is your feature request related to a problem? Please describe.**
Yes, there's a security mandate to enable httpsOnly on all our function app. We have a lot; I can't script this change :(

**Describe the solution you'd like**
`az functionapp update -g myRg-n myFnApp --https-only true` works as it does for `az webapp update`

**Describe alternatives you've considered**
Using the webapp sibling command:
```
❯ az functionapp list --query "[?!httpsOnly].{ rg: resourceGroup, n: name}
>> " | ConvertFrom-Json | %{ az webapp update -g $_.rg -n $_.n --https-only true}
please use 'az functionapp update' to update this function app
```
😭Manually using the portal and clicking for hours
We have fixed this in our ARM template for future deployments but it doesn't solve for running apps that don't require updates

**Comment by yonzhan** [comment]
route to service team
