### ISSUE TITLE
Adding ssl binding to deployment slot returns az : ERROR: Operation returned an invalid status 'Not Found'

### ISSUE THREAD

**Issue by GurdipS5** [Azure/azure-cli#19953]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I run the following command:

az webapp config ssl bind --certificate-thumbprint "$thumbprint" --name "testapp12345gsx" --resource-group "tfmgrtest" --slot "testapp12345gsx-testslot" --ssl-type "SNI"

But get the error 
az : ERROR: Operation returned an invalid status 'Not Found'

**To Reproduce**
To reproduce, please enter the command like above, with the same arguments.

**Expected behavior**

**Environment summary**
Windows Server 2019, 

  "azure-cli": "2.29.0",
  "azure-cli-core": "2.29.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}

Thanks

**Comment by yonzhan** [comment]
route to service team
