### ISSUE TITLE
Better error handling for `--parameters` flag (Please just add `--parameters-file` back?)

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#1996]
I don't remember the discussion regarding it, but I constantly field questions about `No JSON object could be decoded` because someone left off the `@` for the `--parameters` flag.

1. Can we please just have `--parameters-file` back? Is there any example, in the real world... anywhere... where someone is passing a JSON literal there? Even when I dynamically construct a parameters file, I do it in a temp json file and pass the path to it on the command line.

2. In lieu of that, can we please get a more helpful error message than `No JSON object could be decoded`. Even just a `Did you mean to specify "--parameters=@./whatever/the/user/passed.json" ? `

**Comment by colemickens** [comment]
ping @tjprescott / @derekbekoe Sorry for the direct ping but this still seems confusing...

Some folks on our team are on slightly different minor versions of the module handling group template deployments and to be blunt, we've spent a silly amount of time trying to figure out what the correct method is for specifying paramters. Can either of you point me at any PRs related to any recent changes to how this flag is handled?

Also, I'd like to reiterate how much simpler and desirable it would be to just have `--parameters-file` to coincide with `--template-file` instead of doing some sort of smart sniffing heuristic to determine if it's a JSON literal or file path or whatnot.

**Comment by derekbekoe** [comment]
A couple related PRs:
https://github.com/Azure/azure-cli/pull/3850
https://github.com/Azure/azure-cli/pull/3743

**Comment by tjprescott** [comment]
The PR that addressed this was https://github.com/Azure/azure-cli/pull/3637.

You can specify any of the following (or a combination):
```
--parameters {file_path}
--parameters {json_string}
--parameters @{file_path} (which is really the same as the JSON string one)
--parameters KEY=VALUE KEY=VALUE ...
```

We would not have `--parameters` and `--parameters-file`. That is a very Xplatty thing that we purposefully avoid (unfortunately it probably exists in a few places in the CLI).

**Comment by tjprescott** [comment]
I'm going to go ahead and close this as #3637 improved the options for supplying parameters and #3850 improved the error handling.
