### ISSUE TITLE
List supported Master and Worker VMsize 

### ISSUE THREAD

**Issue by giovannifl** [Azure/azure-cli#19998]
Please could you list all supported Master and Worker vmSize ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08eb181a-b377-c854-69cc-3b9307f59f72
* Version Independent ID: 2142cb43-b027-86a1-6d3c-2f77bf86d177
* Content: [az aro](https://docs.microsoft.com/en-us/cli/azure/aro?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/aro.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/aro.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bennerv** [comment]
Documentation can be found here: https://learn.microsoft.com/en-us/azure/openshift/support-policies-v4#supported-virtual-machine-sizes

@yonzhan can close this.
