### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'private_dns_zone_configs'

### ISSUE THREAD

**Issue by thanh-nguyen-van** [Azure/azure-cli#20036]
## Describe the bug

**Command Name**
`az network private-endpoint dns-zone-group add`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'private_dns_zone_configs'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/azure/cli/command_modules/network/custom.py", line 3106, in add_private_endpoint_private_dns_zone
    private_dns_zone_group.private_dns_zone_configs.append(private_dns_zone)
AttributeError: 'NoneType' object has no attribute 'private_dns_zone_configs'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network private-endpoint dns-zone-group add --endpoint-name {} -g {} -n {} --zone-name {} --private-dns-zone {}`

## Environment Summary
```
macOS-10.15.3-x86_64-i386-64bit
Python 3.9.6
Installer: PIP

azure-cli 2.27.2 *

```

**Comment by alexangas** [comment]
I'm experiencing this issue. Is there any way around it?

**Comment by necusjz** [comment]
> I'm experiencing this issue. Is there any way around it?

Hi @alexangas ,

I cannot reproduce this issue locally, I'd like to know did you create dns-zone-group successfully? i.e.,
```
az network private-endpoint dns-zone-group create -n {} -g {} --endpoint-name {} --zone-name {} --private-dns-zone {} 
```

**Comment by alexangas** [comment]
@necusjz I'm still learning how the private link functionality works outside of the Portal. However I think that the dns-zone-group associated with the web app did not exist.

**Comment by necusjz** [comment]
> @necusjz I'm still learning how the private link functionality works outside of the Portal. However I think that the dns-zone-group associated with the web app did not exist.
> 
> > The command failed with an unexpected error. Here is the traceback:
> > 'NoneType' object has no attribute 'private_dns_zone_configs'
> > Traceback (most recent call last):
> > File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
> > File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/**init**.py", line 658, in execute
> > File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/**init**.py", line 721, in _run_jobs_serially
> > File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/**init**.py", line 692, in _run_job
> > File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/**init**.py", line 328, in **call**
> > File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
> > File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 3388, in add_private_endpoint_private_dns_zone
> > AttributeError: 'NoneType' object has no attribute 'private_dns_zone_configs'
> 
> > azure-cli                         2.32.0
> > core                              2.32.0
> > telemetry                          1.0.6
> > Extensions:
> > aks-preview                       0.5.51
> > application-insights              0.1.14
> > azure-devops                      0.22.0
> > front-door                        1.0.16
> > interactive                        0.4.5
> > next                               0.1.2
> > Dependencies:
> > msal                              1.16.0
> > azure-mgmt-resource               20.0.0
> > Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

I think so. As I mentioned, maybe we should create a dns-zone-group firstly. : )

**Comment by alexangas** [comment]
@necusjz Yes agreed. Do you think there might be a way to improve the error message?
