### ISSUE TITLE
az vm list-usages fails for westindia: "No registered resource provider"

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#2003]
`az vm list-usage --location=westindia | jq -r ".[] | [\"$location\", .name.localizedValue, .limit, .currentValue] | @tsv"`

`No registered resource provider found for location 'westindia' and API version '2016-04-30-preview' for type 'locations/usages'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview, 2016-08-30, 2017-03-30'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest, eastus2euap, centraluseuap'.`

All other locations were fine. The api-version, and the location, are both mentioned in the supported list returned in the error.

**Comment by colemickens** [comment]
Actually, I just got it for two other locations, but I can't find any mention of them online, so I'm omitting them here in case they're not meant to be public.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
