### ISSUE TITLE
Install instructions don't work for Ubuntu 21.10 (No 21.10 debs are built)

### ISSUE THREAD

**Issue by YoloClin** [Azure/azure-cli#20058]
The guidelines at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt don't work on Ubuntu 21.10 because no 21.10 repository exists on https://packages.microsoft.com/repos/azure-cli/dists/

Is it possible to get these added to the build chain? 

Thanks!

**Comment by SecurityHat** [comment]
Could you add a symlink?
