### ISSUE TITLE
Azure China / Mooncake - "az feature" commands fail with: The resource type 'providers' could not be found in the namespace 'Microsoft.Features' for api version '2021-07-01'

### ISSUE THREAD

**Issue by ohadschn** [Azure/azure-cli#20087]
**Describe the bug**
Cannot execute `az feature` commands in `AzureChinaCloud` (mooncake), getting the following error:
> (InvalidResourceType) The resource type 'providers' could not be found in the namespace 'Microsoft.Features' for api version '2021-07-01'. The supported api-versions are '2014-08-01-preview,2015-12-01'.

**To Reproduce**
`az feature list --namespace Microsoft.Storage`

**Expected behavior**
`az feature` works normally as it does in the public cloud (`AzureCloud`).

**Environment summary**
Started happening since az `2.28.0`, still happens with the latest release `2.29.1`.

**Additional context**
Might be related to https://github.com/Azure/azure-cli/issues/18828

**Comment by ohadschn** [comment]
@yonzhan @jiasli this is still happening in the latest version (2.30.0)...

**Comment by karataliu** [comment]
could you please ensure apiversion is ready in all clouds before publishing cli? This is blocking customers.

**Comment by jiasli** [comment]
I think this is a general topic, as this also happens to Key Vault or other services where **an API version is available in `AzureCloud`, but not in sovereign clouds - `AzureChinaCloud`, `AzureUSGovernment`, `AzureGermanCloud`**. 

Clouds are defined here:

https://github.com/Azure/azure-cli/blob/3feea02888ea67f033f407174a3a7a340158b81a/src/azure-cli-core/azure/cli/core/cloud.py#L297-L301

However, `AzureCloud` and other sovereign clouds all use the same `latest` profile which defines the API versions to call:

https://github.com/Azure/azure-cli/blob/5439a64ab624d19716cd868643a02620dff22c26/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L143-L146

@zhoxing-ms, let's work internally with `Microsoft.Features` service team to drive the ononboarding to sovereign clouds.

**Comment by matt-mi** [comment]
Hi, is there any update on this topic since we're encountering the same issue which prevented us significantly from automated deployment.

**Comment by zhoxing-ms** [comment]
This issue requires `Microsoft.Features` service team to deploy their service of api-version` 2021-07-01` to `AzureChinaCloud`.
@mkarmark Hi, do you know who is the `Microsoft.Features` service team member? If so, please help add the relevant person

**Comment by ohadschn** [comment]
> This issue requires `Microsoft.Features` service team to deploy their service of api-version` 2021-07-01` to `AzureChinaCloud`

IMHO this would not be the right approach. I don't think it wise to globally upgrade an API version in the tool, thereby breaking all clouds where this version doesn't exist, and then wait in this broken state until the API's service team deploys to that cloud (for months on end, this one is almost 3 months and still counting)...

It will only be a matter of time until some other API service team you depend on lag behind some version you upgrade to, causing this issue to crop up all over again - in China/Mooncake or other clouds (such as US Government / Fairfax).

I see 2 reasonable options:
1. Always use API versions that are deployed to ALL azure-cli supported clouds (AFAIK Public, China, US Government, Germany).
2. Keep some configuration that maps each cloud instance to an API version which is deployed to it, and work with that version.

As a mitigation, at the very least you could allow the user to somehow override the API version (assuming of course the API didn't change to the point that the existing azure-cli code wouldn't be able to work with the older version).

**Comment by jiasli** [comment]
As this API version lag problem also happens on other services like keyvault and network, I think we do need a solution.

## Possible solutions

1. **Enforce service team to eliminate API version lag and always make the latest API version available in all clouds**. I personally prefer this solution, as we did enforce keyvault service team to onboard their new API versions to sovereign clouds before.
2. **Azure CLI introduces different API version profiles for different clouds**, like currently how to use Azure Stack. This needs big effort, as CLI needs to maintain a large list of all API versions for different clouds. As those API versions will eventually became synchronized, the list is only temporarily and will eventually be dropped.
3. As @ohadschn mentioned, **support a global argument `--api-version` to override the default version**. However, this is not a small change and would require the user to know which API version to use beforehand, so I don't personally prefer this either.

**Comment by jiasli** [comment]
## Workaround

For now, you may install old versions of Azure CLI. I have provided detailed instruction on how to install a specific version of Azure CLI in our document: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**Comment by matt-mi** [comment]
I think workaround of installing a specific version only works for people who use az cli in a unmanaged environment like laptop or PC. People who is using az cli in a shared and centrally-managed production environment may not be able to downgrade certain commonly used software easily and freely, since no matter what kind of change on a managed environment would essentially require lots of evaluations and considerations, and unfortunately I didn't see such caution has been taken into consideration in this case.

I totally agree with @ohadschn, if you cannot cover the obvious defect that all the api-version lagging among these Azure instances, then provide an option to customer to specify certain api-version in the command line, or make sure the upgrade doesn't impact anything beforehand.

Please either get API upgraded in Azure China, or make enhancement on az cli part, otherwise people would suffer the same issue again and again whenever you upgrade az cli and not including a valid api-version there.

**Comment by ohadschn** [comment]
> ## Possible solutions
> 1. **Enforce service team to eliminate API version lag and always make the latest API version available in all clouds**. I personally prefer this solution, as we did enforce keyvault service team to onboard their new API versions to sovereign clouds before.
> 2. **Azure CLI introduces different API version profiles for different clouds**, like currently how to use Azure Stack. This needs big effort, as CLI needs to maintain a large list of all API versions for different clouds. As those API versions will eventually became synchronized, the list is only temporarily and will eventually be dropped.
> 3. As @ohadschn mentioned, **support a global argument `--api-version` to override the default version**. However, this is not a small change and would require the user to know which API version to use beforehand, so I don't personally prefer this either.

Well there's also:
4. Don't upgrade to unsupported API versions, and downgrade all currently unsupported API versions to their supported counterparts on all clouds.

Looking at the API change for `Microsoft.Features` specifically, it looks like the only semantic difference is better error reporting:
https://github.com/Azure/azure-rest-api-specs/tree/88e7838a09868a51de3894114355c75929847a46/specification/resources/resource-manager/Microsoft.Features/stable

Now, far be it from me to say good error reporting is not important. On the contrary, I think it's really important - just not important enough to break the usage entirely. So I think at least in this specific case downgrading the API version used by az cli would be the clear choice - you don't even lose functionality.

Regarding `--api-version` I just want to emphasize again - while it definitely could be a good and relatively simple workaround, the fact that the user would need to know which API version to use is really the least of our problems. Indeed, while on the subject of error messages - you get a very clear one as I mentioned above: `The resource type 'Foo' could not be found in the namespace 'Bar' for api version 'xxx'. The supported api-versions are 'yyy,zzz'` so you can tell which API version you could use immediately. The real problem would be actually breaking changes to the API, such as new mandatory parameters added or some property no longer returned - both could break az cli (for the examples I provided - fail the call and break the parsing, respectively).

**Comment by jiasli** [comment]
We have contacted service team to deploy the latest API version to `AzureChinaCloud`:

```
> az feature list --namespace Microsoft.Storage --debug
...
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.chinacloudapi.cn/subscriptions/d3b15b72-0b9d-4e12-911c-451d1b510c0e/providers/Microsoft.Features/providers/Microsoft.Storage/features?api-version=2021-07-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
...
cli.azure.cli.core.sdk.policies: Response status: 200
...
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":[{"properties":{"state":"NotRegistered"},"id":"/subscriptions/d3b15b72-0b9d-4e12-911c-451d1b510c0e/providers/Microsoft.Features/providers/Microsoft.Storage/features/AllowAttributeBasedAccessControl","type":"Microsoft.Features/providers/features","name":"Microsoft.Storage/AllowAttributeBasedAccessControl"},{"properties":{"state":"NotRegistered"},"id":"/subscriptions/d3b15b72-0b9d-4e12-911c-451d1b510c0e/providers/Microsoft.Features/providers/Microsoft.Storage/features/AllowNfsFileShares","type":"Microsoft.Features/providers/features","name":"Microsoft.Storage/AllowNfsFileShares"},{"properties":{"state":"NotRegistered"},"id":"/subscriptions/d3b15b72-0b9d-4e12-911c-451d1b510c0e/providers/Microsoft.Features/providers/Microsoft.Storage/features/AllowRequireInfrastructureEncryption","type":"Microsoft.Features/providers/features","name":"Microsoft.Storage/AllowRequireInfrastructureEncryption"},{"properties":{"state":"NotRegistered"},"id":"/subscriptions/d3b15b72-0b9d-4e12-911c-451d1b510c0e/providers/Microsoft.Features/providers/Microsoft.Storage/features/AllowSMBMultichannel","type":"Microsoft.Features/providers/features","name":"Microsoft.Storage/AllowSMBMultichannel"},{"properties":{"state":"NotRegistered"},"id":"/subscriptions/d3b15b72-0b9d-4e12-911c-451d1b510c0e/providers/Microsoft.Features/providers/Microsoft.Storage/features/BlobIndex","type":"Microsoft.Features/providers/features","name":"Microsoft.Storage/BlobIndex"},{"properties":{"state":"NotRegistered"},"id":"/subscriptions/d3b15b72-0b9d-4e12-911c-451d1b510c0e/providers/Microsoft.Features/providers/Microsoft.Storage/features/EncryptionAtRest","type":"Microsoft.Features/providers/features","name":"Microsoft.Storage/EncryptionAtRest"}]}
```

 Please retry the operation and let us know if the issue is resolved. Thanks.

**Comment by matt-mi** [comment]
I got same response from 21vianet support team as well, now az cli in 2.32 version can execute the `az feature` related commands now, thanks for the help.
