### ISSUE TITLE
assignee-object-id is not valid

### ISSUE THREAD

**Issue by regisgimenis** [Azure/azure-cli#20089]
the argument --assignee-object-id is not valid with the following error "UnrecognizedArgumentError: unrecognized arguments: --assignee-object-id". 

The documentation must be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfc71a73-f8b7-8b89-ad44-30045b1e057d
* Version Independent ID: 10dc03f8-8337-c693-8401-a6080de80e41
* Content: [az synapse role assignment](https://docs.microsoft.com/en-us/cli/azure/synapse/role/assignment?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/synapse/role/assignment.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/synapse/role/assignment.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by zesluo** [comment]
Hello @regisgimenis , thanks for your feedback! I just tried  "az synapse role assignment list --workspace-name wsname --assignee-object-id objectid. It can work. May I know which version( you can type az --version) you are trying? By the way, would you also provide the  full command you are using? Thanks!

**Comment by cawoodm** [comment]
The command example was posted [here](https://learn.microsoft.com/en-us/answers/questions/1662476/function-app-error-no-user-assigned-or-delegated-m) but does not work:

```
> az role assignment list --assignee-object-id 6e7c24be-3e11-4a8e-97fa-11cbfc733532
unrecognized arguments: --assignee-object-id 6e7c24be-3e11-4a8e-97fa-11cbfc733532

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
```

### az --version
```
azure-cli                         2.66.0 *

core                              2.66.0 *
telemetry                          1.1.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\MarcCawood\.azure\cliextensions'

Python (Windows) 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal
```
