### ISSUE TITLE
az cli drops caret in --parameter of az vm run-command invoke

### ISSUE THREAD

**Issue by dbiegunski** [Azure/azure-cli#20096]
az cli version 2.1.2 

**Describe the bug**
When a string contains a caret character and it is passed as an argument to --parameter it gets dropped.

--parameters password='test^test'

Tested scenarios

--parameters password='test^test'  - PS Script receives: testtest
--parameters password="test^test" - PS Script receives: testtest
--parameters password='"test^test"'  - PS Script receives: "test^test"
--parameters password="'test^test'"  - PS Script receives: 'testtest'

**To Reproduce**
az vm run-command invoke --command-id RunShellScript --name VM_Name -g Ressource_Group --scripts @PS.ps1 --parameters password='test^test'

**Expected behavior**
Powershell script should receive the following string : test^test as it is enclosed with single-quotes.

**Environment summary**
Azure DevOps
task: AzureCLI@2
az cli version 2.1.2
bash inlineScript on latest-ubuntu

**Comment by nl-saw** [comment]
Hi,

1. any update to this? Also ran unto this unexpected issue which ruined my day.
2. why is it labeled feature request? Seems nothing short of a bug to me.

Cheers.

**Comment by zhoxing-ms** [comment]
@nl-saw Could you please send me the debug log and the script you used to my email? My email address is Zhou.Xing@microsoft.com

**Comment by zhoxing-ms** [comment]
In fact, this problem is not caused by Azure CLI itself, but because `^` is a special character (such as `^` is escape character for CMD https://ss64.com/nt/syntax-esc.html#escape ), the interpreter loses it when it is passed into Azure CLI.

So we need to use double quotes to make `^` as a literal string, for example:

- The usage in PowerShell scirpt can be:
```pwsh
$secret_servicePass = '\"test^test\"'
az vm run-command invoke -g test -n test --command-id RunPowerShellScript --scripts "@ps1" --parameters "servicePassword=${secret_servicePass}" --debug
```

- The usage in PowerShell terminal can be: `--parameters 'secret_servicePass=\"test^test\"'` or `--% --parameters password=\"test^test\"`

- The usage in CMD terminal can be: `--parameters password=\"test^test\"`

**Comment by nl-saw** [comment]
Thanks for the suggested workaround. Following worked for me although I had to remove the extra 2x " in the PS script again:

``` 

$secret_servicePass = '\"$(Password-ServiceAccount-from-KV)\"'

               az vm run-command invoke -g $qs_resourcegroup -n $QSVM `
               --command-id RunPowerShellScript --scripts "@.\tmp_.ps1" `
               --parameters "servicePassword=$secret_servicePass" `
               --debug

```

**Comment by nl-saw** [comment]
Azure CLI is indeed not the problem. I can set variables in azure CLI with ^ char with no issues at all. Also, the parameter, including the ^ is passed correctly in azure CLI to the AZ command. It is the AZ tool that then strips it for some reason.

This is where imho a bug resides, as the parameter is normally passed with encapsulating ", that should not happen. When you then set the actual variable value to start and end with " the character (current workaround) the ^ is no longer stripped (reinforcing the bug suspicion) but leaves you with a value containing two " which you then need to strip again, in my case at the PowerShell script. AZ handles the parameter wrong internally.

**Comment by zhoxing-ms** [comment]
@nl-saw If you want the inputting variable value not to be wrapped by `"`, you can try `$secret_servicePass = '"test^test"'`. *（Removed escape character `\`)*
