### ISSUE TITLE
StaticApp:Static web application settings cannot be set with "az staticwebapp appsettings set"

### ISSUE THREAD

**Issue by yaroslav-ddt** [Azure/azure-cli#20108]
Hello, 
I have tried to add application settings to the static web app with the command 
`az staticwebapp appsettings set -n sitename --setting-names 'key=value'`
but got the error "cli.azure.cli.core.azclierror: Operation returned an invalid status 'Bad Request'". 

Debug log shows the possible issue with request: 
> cli.azure.cli.core.sdk.policies: {"Code":"BadRequest","Message":"Parameter appSettings is null or empty.","Target":null,"Details":[{"
> Message":"Parameter appSettings is null or empty."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51011","MessageTemplate":"P
> arameter {0} is null or empty.","Parameters":["appSettings"],"Code":"BadRequest","Message":"Parameter appSettings is null or empty."}
> }],"Innererror":null}

Applying the same settings on the same static web application with `az rest --method PUT ` works well without issues.

Best regards,
Yaroslav

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57306327-4c21-d60b-758f-e7c2a23a6b5c
* Version Independent ID: 58b831b8-dcdb-d9b3-d3df-2793ef1b2a05
* Content: [az staticwebapp appsettings](https://docs.microsoft.com/en-us/cli/azure/staticwebapp/appsettings?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/staticwebapp/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/staticwebapp/appsettings.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Kotasudhakarreddy** [comment]
Able to repro the issue.

**Comment by zachpetersen** [comment]
Can confirm the same issue here.

```
azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Extensions:
azure-devops                      0.21.0
resource-graph                     1.0.0

Python (Linux) 3.6.10 (default, Oct 29 2021, 10:11:34) 
[GCC 9.3.0]
```

```
az staticwebapp appsettings set -n swaAppName --setting-names key1=val1
```

Response from debug

```
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"Code":"BadRequest","Message":"Parameter appSettings is null or empty.","Target":null,"Details":[{"Message":"Parameter appSettings is null or empty."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51011","MessageTemplate":"Parameter {0} is null or empty.","Parameters":["appSettings"],"Code":"BadRequest","Message":"Parameter appSettings is null or empty."}}],"Innererror":null}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/static_sites.py", line 159, in set_staticsite_function_app_settings
    resource_group_name, name, app_settings=setting_dict)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/web/v2021_01_15/operations/_static_sites_operations.py", line 2138, in create_or_update_static_site_function_app_settings
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
```

**Comment by panchagnula** [comment]
@StrawnSC is working on fixing appsetting support for SWA

**Comment by StrawnSC** [comment]
Thanks for reporting this issue. It was resolved by https://github.com/Azure/azure-cli/pull/20320, which was included in the latest release
Please upgrade to the latest CLI version (2.31.0) and reopen the issue if you're still seeing this bug
