### ISSUE TITLE
[VM] Allow specifying additional ports to expose when creating a VM

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2011]
Thanks to #1982, the `az vm open-port` command provides a simple solution for managing a VM's open ports, however, it would be nice if this could also be achieved as part of the `az vm create` command, by adding a new flag that accepts a list of ports to open on the underlying NSG.

This command already allows automatically exposing the right port for SSH/RDP access, and it would be a nice addition to also open more ports in a declarative way, without needing to use an additional command (either `vm open-port` or `network nsg rule create`) in order to satisfy simple scenarios (e.g. spinning up a web server VM that will always need port 80 exposed).

```shell
az vm create -n <name> -g <group> --image UbuntuLTS --expose-ports 80
```

**Comment by tjprescott** [comment]
I would argue that VM create is already complex enough. This would run into the same problems that happened when I tried to make `vm open-port` accept a list of ports--namely, there is no good heuristic for specifying the priority and each inbound or outbound rule must have a different priority.

**Comment by lostintangent** [comment]
@tjprescott I fully agree, and could appreciate that argument. I just wanted to open this for discussion. The fact that `vm create` was enhanced to allow provisioning entirely new data disks made it seem reasonable to me to also "allocating" exposed ports as part of the operation as well.

Users could obviously run `az disk create` before hand, or `az vm disk attach` afterwards, but being able to declare what you want for your VM in a single operation, without caring about the individual steps needed to achieve it, is really nice. It seems like exposed ports fall into a similar category of commonly used resources for a VM.

But I agree this command is getting large, so I respect your team's judgement here.

**Comment by yugangw-msft** [comment]
There are couple exceptions, but the principal of exposing options from `VM create` are like following:
1. All required so VM can boot
2. All required you can remote connect to it
3. All required that can only be done on `create` such as the custom data
4. Lots of people ask for it.  
For this issue, it doesn't fall into the above list, hence debatable. 
At the same time, considering `VM create` is essentially a builder on a json formatted template, maybe we can expose the pipeline, so users can pass in a general setter for extra settings.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
