### ISSUE TITLE
General: hide the return value if it is operation_status_response 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#2012]
(For tracking, this might need some cooperation from autorest) 
With the integration with the latest compute SDK, a few compute operations (`deallocate`, `start`, `stop`, etc) start to return `operation_status_response` objects 
```json
{
  "endTime": "2017-02-08T18:02:31.477182+00:00",
  "error": null,
  "name": "02bdfc3f-6236-4064-9894-15b89ad6b70d",
  "startTime": "2017-02-08T18:02:20.070584+00:00",
  "status": "Succeeded"
}
```
This output is not interesting, because we will get `CloudError` on any error causes. I would very much like the old silent behavior on success

It is possible to hide it by using the transformation. The problem is this response type is per library, not a general type from the auto run time, so the [detection code](https://github.com/yugangw-msft/azure-cli/commit/e91b108d22fd2caf47e1d989943d1a091e23dcb2#diff-08bf3d69436b952a8bf0b428f808dc01R92) at CLI would become pretty hacky, and each command module will need same piece of code to deal with this.

I will open a bug at autorest, that we should at least move the type to common runtime, so cli will handle it at core layer

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
