### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by nomchom** [Azure/azure-cli#20127]
## Describe the bug

**Command Name**
`az eventhubs namespace create`

**Errors:**
```
Please run 'az login' to setup account.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az eventhubs namespace create -n {} -g {} -l {} --enable-kafka`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.28.0 *

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Saglodha** [comment]
Hi @nomchom, Thanks for reaching out to us. 

From the error message, it looks like you haven't logged in to Azure before using any of the CLI cmdlets and thus not being able to create namespace (which is expected behavior). Can you elaborate more on the steps you have been taking?

**Comment by navba-MSFT** [comment]
@nomchom Apologies for the late reply. Could you please run the below commands in order and then let us know if you still face this issue ?

>az login    # Run this command to login to your Azure Account
>az account set --subscription "1234-XXXX-XXXX-1234"  # Run this command to set the default Azure Subscription context

Then run [this](https://docs.microsoft.com/en-us/cli/azure/eventhubs/namespace?view=azure-cli-latest#az-eventhubs-namespace-create) EventHub command to create an EH resource. Please let me know if you still run into any issues. Awaiting your reply.
