### ISSUE TITLE
Azure CLI:  –data-disk-delete-option : Data disk is not deleted automatically after the VM is deleted

### ISSUE THREAD

**Issue by gitoboc** [Azure/azure-cli#20133]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Run the below in Azure Cloud Shell to create a VM

 az vm create -n Delete_CLI1 -g Delete_CLI --image RedHat:RHEL:7-RAW:7.4.2018010506 -l northeurope --size Standard_E8as_v4 --generate-ssh-keys --public-ip-address "" --os-disk-size-gb 64 --data-disk-sizes-gb 200 --data-disk-delete-option

As per https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest when using --data-disk-delete-option, data disk should be deleted or detached upon VM deletion.

After I go and delete VM, the data disk is not deleted automatically

**To Reproduce**

Open Azure Cloud Shell
Type command to create VM using the --data-disk-delete-option
VM gets created
When deleting VM, attached data disk is not deleted automatically

**Expected behavior**
Data Disk should be deleted automatically

**Comment by yonzhan** [comment]
Compute
