### ISSUE TITLE
Add RepairAction property to AutomaticRepairsPolicy for 'az vmss create' and 'az vmss update'

### ISSUE THREAD

**Issue by frank-pang-msft** [Azure/azure-cli#20139]
**Resource Provider**

- Compute 

**Description of Feature or Work Requested**

- Existing VMSS AutomaticRepairsPolicy needs to add RepairAction as a supported property. [See previous CLI support request](https://github.com/Azure/azure-cli/issues/10949)

CLI Examples
```
az vmss create--name myScaleSet --resource-group myResourceGroup --automatic-repairs-action replace

az vmss update --name myScaleSet --resource-group myResourceGroup --set AutomaticRepairsPolicy.Enabled=true AutomaticRepairsPolicy.GracePeriod=PT0S AutomaticRepairsPolicy.RepairAction=replace

az vmss update --name myScaleSet --resource-group myResourceGroup --enable-automatic-repairs true --automatic-repairs-grace-period PT0S --automatic-repairs-action replace
```

automatic-repairs-action/RepairAction - String [Replace, Restart, Reimage] Default: Replace

**Minimum API Version Required**

- 2021-11-01

**Swagger Link**

- Swagger Specs and SDK PRs are still in-progress by SDK team. 
      - https://github.com/Azure/azure-rest-api-specs/pull/16535

**Target Date**

- November/December/ASAP

**Comment by yonzhan** [comment]
Compute

**Comment by frank-pang-msft** [comment]
Hi just following up if this issue is okay?

**Comment by zhoxing-ms** [comment]
@frank-pang-msft Yes, we will plan to release it on **12-07**

**Comment by PARADISSEEKR** [comment]
@frank-pang-msft  There is no RepairAction in the SDK currently in use. I downloaded the SDK here(https://github.com/Azure/azure-rest-api-specs/pull/16535#issuecomment-951344893), but I didn’t find RepairAction in it. Could you please check it out?

**Comment by frank-pang-msft** [comment]
Hi, @PARADISSEEKR, sorry first time doing this. Since SDK team does not want to change prior api versions, RepairAction property will be available only for 2021-11-01 api. I was able to build SDK but unable to test as ARM manifest rollout is still in progress (live APIs will not work). Below is .NET PR with the SDK built.

https://github.com/Azure/azure-sdk-for-net/pull/25095/files

**Comment by zhoxing-ms** [comment]
@frank-pang-msft  In fact, what we need is the Python SDK. Could you provide it?

**Comment by frank-pang-msft** [comment]
Hi @zhoxing-ms, let me loop in SDK team. @Sandido, @grizzlytheodore, would you be able to help with this?

**Comment by zhoxing-ms** [comment]
@frank-pang-msft For the release of Python SDK, you can ask @msyyc for help~
