### ISSUE TITLE
How do I register a model from an AML experiment run using the CLI?

### ISSUE THREAD

**Issue by natke** [Azure/azure-cli#20134]
It looks like there used to be a az ml model register command but that doesn't exist any more. What is the command to do this now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 110fd5df-299e-f288-867f-c307a2f2ba9f
* Version Independent ID: ac8d15ce-b17b-8da8-8d60-cf98d448c9bd
* Content: [az ml model](https://docs.microsoft.com/en-us/cli/azure/ml/model?view=azure-cli-latest#az_ml_model_create)
* Content Source: [latest/docs-ref-autogen/ml/model.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/model.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by azureml-github** [comment]
+ @***@***.***>, @***@***.***> as DRIs.

**Comment by harneetvirk** [comment]
In CLI v2, you can create the model using the command: az ml model create

For more specific examples, use: "az ml model create -h"

**Comment by luigiw** [comment]
Azure CLI v2 is GAed and the active version AzureML supports. Please consider switching to v2. https://learn.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli?tabs=public
