### ISSUE TITLE
Add "Architecture" property for disk api version 2021_04_01 for private package request

### ISSUE THREAD

**Issue by laurawu19** [Azure/azure-cli#20141]
**Resource Provider**
Microsoft.Compute/DiskRP

**Description of Feature or Work Requested**
Update the disk and snapshot commands to accept a new optional property called "architecture". It is an enum and values could be {x64, Arm64}

az disk create [--architecture {x64, Arm64}]
az snapshot create [--architecture {x64, Arm64}]
az disk update [--architecture {x64, Arm64}]

**Minimum API Version Required**
2021_04_01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/16629

**Target Date**
November, 2021

**Comment by yonzhan** [comment]
Compute

**Comment by wangzelin007** [comment]
Hi @laurawu19
I found `New-AzSnapshotUpdateConfig` in [Powershell Design](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1030).
So I think we need support az snapshot update [--architecture {x64, Arm64}]
