### ISSUE TITLE
Unable to pass parameters file nor interactive prompt for paramters

### ISSUE THREAD

**Issue by Teodelas** [Azure/azure-cli#2014]
If you look at this example:
https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-dockerextension
"Answer the prompts to name your storage account, provide a username and password, and provide a DNS name. The output is similar to the following example"

Teo
teodelas@microsoft.com

**Comment by tjprescott** [comment]
That example is written for Azure XPlat CLI. If the prompts don't happen in Xplat, please file an issue in their repo:   https://github.com/Azure/azure-xplat-cli

If the issue is just that Azure CLI 2.0 Preview does not prompt for missing deployment parameters, there is already an issue open for that (#1778).

You can pass a parameters file by specifying: `--parameters @{filename}`

**Comment by Teodelas** [comment]
OK.  I was providing the XPlat example just as a reference of what I was trying to do.

Related to this, I cannot do --parameters “{JSON}” either (as stated in the docs):
https://docs.microsoft.com/en-us/cli/azure/group/deployment#create

  *   This fails:
  *   az group deployment create -g myResourceGroup --template-uri https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/docker-simple-on-ubuntu/azuredeploy.json --parameters "{''newStorageAccountName'': {''value'': ''GEN-UNIQUE''},''adminUsername'': { ''value'': ''ubuntu''},''adminPassword'': { ''value'': P4$$w0rd'' },''dnsNameForPublicIP'': {''value'': ''GEN-UNIQUE''} }"
  *   az : ERROR: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
  *   At line:1 char:1
  *

**Comment by tjprescott** [comment]
If you specify a raw JSON string for `--parameters` it needs to be properly escaped:
`--parameters "{\"key\":\"value\"}"`
Hence why you would put your parameters in a JSON file and then just use the @ syntax to load the contents of the file `--parameters @myfile.json`

**Comment by johanste** [comment]
@Teodelas, which shell are you using? cmd.exe? bash? They have different escaping rules for quotes. If you are using bash, you can either escape as @tjprescott suggests, or use single quotes (') for the outermost quoting. Also, you are using double single quotes where you probably want double quotes. And you are missing the leading double quote for the password value :)

See below for what I ran in bash:

`az group deployment create -g myResourceGroup --template-uri https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/docker-simple-on-ubuntu/azuredeploy.json --parameters '{"newStorageAccountName": {"value": "GEN-UNIQUE"},"adminUsername": { "value": "ubuntu"},"adminPassword": { "value": "P4$$w0rd" },"dnsNameForPublicIP": {"value": "GEN-UNIQUE"} }'`

**Comment by iainfoulds** [comment]
To add another element, this isn't a great experience when using a template from the GitHub quick start repo or a template shared with you. You may not know what parameters to pass in until you try to deploy, and then have to work through each successive failure - the CLI 2.0 is only prompting on the first parameter it sees as missing, not providing a list of all the parameters it's going to need from the template.

With the CLI 1.0, when you deploy from template and there are parameters values you need to provide, the CLI will prompt for those if you don't specify them. With the CLI 2.0, you have to load the json template, see what parameters are being requested, and then pass a big long json string in under `--parameters` or take the additional step to create a parameters file and then pass that in. That's not a great experience.

So here's a working sample from one of our docs with CLI 1.0:

`azure group create --name myResourceGroup --location "West US" --template-uri https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/docker-simple-on-ubuntu/azuredeploy.json`

And then what I need to update the doc to with CLI 2.0:

`az group create --name myResourceGroup --location westus`

`az group deployment create --resource-group myResourceGroup --parameters '{"newStorageAccountName": {"value": "mystorageaccount"},"adminUsername": {"value": "azureuser"},"adminPassword": {"value": "P@ssw0rd!"},"dnsNameForPublicIP": {"value": "mypublicdns"}}' --template-uri https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/docker-simple-on-ubuntu/azuredeploy.json`

The CLI 2.0 implementation is not as user-friendly or intuitive. That's not an easy block to copy and paste and have a successful experience. Add in the differences in escaping and that's not cool.

Suggestion would be to provide interactive prompt for the required values or at the least to parse the provided template and provide a list of all the parameters the user needs to pass in and indicate what the user needs to add to the command.

@squillace for awareness.

**Comment by JasonRShaver** [comment]
This experience (interactive prompting) is part of our goals for the Az Shell project (github.com/azure/azure-cli-shell).

**Comment by raykao** [comment]
I'm having this issue on MacOS Sierra.

Using a local parameters file and getting error:

```
Deployment template validation failed: 'The value for the template parameter 'jumpboxServerName' at line '1' and column '89' is not provided. Please see https://aka.ms/arm-deploy/#param
eter-file for usage details.'.
```

Filed issue [#3001](https://github.com/Azure/azure-cli/issues/3001)
