### ISSUE TITLE
Add Instance view to RunCommand

### ISSUE THREAD

**Issue by koralski** [Azure/azure-cli#20155]
**Is your feature request related to a problem? Please describe.**
Current run-command only supports --expand that is not easily discoverable what parameter to pass.
This change applies to:
az vm run-command
az vmss run-command

**Describe the solution you'd like**
Add alternative parameter --status that will be the same as --expand instance-view
This is most common use scenario to track a run command progress, so we need to make it easy

**Describe alternatives you've considered**
Improve documentation/help to show the only option for expand is instance-view, or make this a default parameter if
only --expand is specified

**Additional context**

**Comment by yonzhan** [comment]
Compute
