### ISSUE TITLE
Exercise - Create a new API in API Management from a function app

### ISSUE THREAD

**Issue by amrahmed101** [Azure/azure-cli#20167]
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
The function app 'OrderFunction66bde89982' was not found in resource group 'learn-55d180f2-8d31-4a41-8dfb-20a4c1ca30f8'. Please make sure these values are correct.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip -g {} -n {} --src {}`

## Environment Summary
```
Linux-5.4.0-1062-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@amrahmed101  Apologies for the delayed response. Could you please upgrade to the most [recent version of Azure CLI ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and ensure that you have selected the right subscription using below command and then  test the behavior?

>az account set --subscription "1234-***-***-1234"

Please let us know if you still run into the same issue. We would be happy to assist you further. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@amrahmed101 Please let us know if you are still facing this issue. If no further assistance is required on this, can we proceed with closure of this issue? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@amrahmed101 We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
