### ISSUE TITLE
RBAC: support AD group commands

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#2016]
1. Author commands under `az ad group`, to be in parity with xplat's
2. On `group list`, add `--display-name` filtering
3. support group name when resolve `--assignee' on role creation

**Comment by ashb** [comment]
On point 1) above all the code to speak to the graph API is already there. I hacked in the following 4 lines into azure/cli/command_modules/role/commands.py:

```python
cli_command(__name__, 'ad group create', 'azure.graphrbac.operations.groups_operations#GroupsOperations.create', factory)
cli_command(__name__, 'ad group list-members', 'azure.graphrbac.operations.groups_operations#GroupsOperations.get_group_members', factory)
cli_command(__name__, 'ad group add-member', 'azure.graphrbac.operations.groups_operations#GroupsOperations.add_member', factory)
cli_command(__name__, 'ad group remove-member', 'azure.graphrbac.operations.groups_operations#GroupsOperations.remove_member', factory)
```

And the commands worked, but the interface wasn't the cleanest so it will need a tiny bit of custom wrapping to make the params consistent.
