### ISSUE TITLE
Cant approve storage account private endpoint using the cli

### ISSUE THREAD

**Issue by dakar-etoro** [Azure/azure-cli#20176]
## Describe the bug

**Command Name**
`az storage account private-endpoint-connection approve`

**Errors:**
```
'NoneType' object is not subscriptable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account private-endpoint-connection approve --id {}`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.2 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
datafactory 0.5.0

```

**Comment by yonzhan** [comment]
storage

**Comment by dakar-etoro** [comment]
Hey, there are news about the issue?
Thanks

**Comment by evelyn-ys** [comment]
Can you share more info with `--debug`?

**Comment by dakar-etoro** [comment]
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f0b17ecfb70>, <function OutputProducer.on_global_arguments at 0x7f0b17dff730>, <function CLIQuery.on_global_arguments at 0x7f0b17e1c840>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.032        55       256
cli.azure.cli.core: Total (1)                 0.032        55       256
cli.azure.cli.core: Loaded 55 groups, 256 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage account private-endpoint-connection approve
cli.azure.cli.core: Command table: storage account private-endpoint-connection approve
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f0b1793e400>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/dakar/.azure/commands/2021-12-19.19-36-20.storage_account_private-endpoint-connection_approve.2461.log'.
az_command_data_logger: command args: storage account private-endpoint-connection approve --id {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f0b178f82f0>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f0b17870510>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 597, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2021_06_01.models' has no attribute 'AccountType'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/profiles/_shared.py", line 597, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2021_06_01.models' has no attribute 'ListKeyExpand'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f0b17870598>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f0b178706a8>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f0b17dff7b8>, <function CLIQuery.handle_query_parameter at 0x7f0b17e1c8c8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f0b17870488>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f0b17870620>]
Command group 'storage account private-endpoint-connection' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.azclierror: 'NoneType' object is not subscriptable
az_command_data_logger: 'NoneType' object is not subscriptable
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f0b1793e620>]
az_command_data_logger: exit code: 2
cli.__main__: Command ran in 0.461 seconds (init: 0.106, invoke: 0.355)
telemetry.save: Save telemetry record of length 3166 in cache
telemetry.check: Negative: The /home/dakar/.azure/telemetry.txt was modified at 2021-12-19 19:33:34, which in less than 600.000000 s

**Comment by evelyn-ys** [comment]
Can't reproduce.

Please make sure you have passed in the correct private endpoint connection id. You can use `az storage account show -n mystorageaccount -g myresourcegroup --query "privateEndpointConnections[0].id"` to check the correct format. 

It should looks like `/subscriptions/0000-0000-0000-0000/resourceGroups/MyResourceGroup/providers/Microsoft.Storage/storageAccounts/mystorageaccount/privateEndpointConnections/mystorageaccount.b56b5a95-0588-4f8b-b348-15db61590a6c`

**Comment by dakar-etoro** [comment]
irrelevancy
