### ISSUE TITLE
multiple accounts with same username

### ISSUE THREAD

**Issue by Tomnowell** [Azure/azure-cli#20172]
console output and error message:

The default web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`. Found multiple accounts with the same username. Please report to us via Github: https://github.com/Azure/azure-cli/issues/new

Error encountered trying to log in to Azure CLI on local system for the first time.  Sorry, still a newb! :D

Not sure exactly how this happened.  I've tried 'merging' the accounts in my account (with a browser, too).  But they still show up separately.  One says it was created by my IT department, and one created by me.  I don't have an IT department, so that can't be totally correct.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Could you check https://github.com/Azure/azure-cli/issues/20168#issuecomment-958765085 and share the required information. Many thanks!

**Comment by jiasli** [comment]
Let's work on https://github.com/Azure/azure-cli/issues/20168.
