### ISSUE TITLE
`az snapshot create` sets `--copy-start true` by default

### ISSUE THREAD

**Issue by cavemandaveman** [Azure/azure-cli#20182]
[Azure CLI 2.30.0](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli#november-02-2021) introduces a breaking change where `--copy-start` needs to be set to `false` for subscriptions which do not support CopyStart, otherwise you get this error:

```shell
ERROR: (OperationNotAllowed) CopyStart creation is not supported for this subscription.
Code: OperationNotAllowed
Message: CopyStart creation is not supported for this subscription.
```

Please update the documentation to include a message that `--copy-start` is set to `true` by default, even if not specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fca6f8c5-a518-04ee-08e3-4ad8d4c9516e
* Version Independent ID: 17710c8c-9cd9-57ea-b6b0-1411648ea03f
* Content: [az snapshot](https://docs.microsoft.com/en-us/cli/azure/snapshot?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/snapshot.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/snapshot.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Compute

**Comment by evelyn-ys** [comment]
Hi @cavemandaveman, this could happen because the source resource location you want to use is different from the location you want to create the snapshot in. CLI will auto-detect whether to use `Copy` or `CopyStart` according to location. We don't default `--copy-start true`.

**Comment by cavemandaveman** [comment]
Hmm. I am not specifying the location. My resource group and source disk are in the same location.

The command I have been using is:
`az snapshot create --resource-group {{ resource_group }} --name {{ snap_name }} --source {{ source_disk }}`

This has worked flawlessly, but now that I have upgraded to CLI 2.30.0, it fails with the error I posted earlier.

**Comment by evelyn-ys** [comment]
@cavemandaveman Thanks for reporting! This is a bug for using same region resource group without specifying `--location`.
You can see my fix PR comment for details: https://github.com/Azure/azure-cli/pull/20190#discussion_r742510869

**Comment by cavemandaveman** [comment]
Great! Glad you were able to find the root cause.

Do you think we well see this fix included in the next point release of CLI?

**Comment by kostukp96** [comment]
I dont understand what i need change in my powershell script, if i use az snapshot create --resource-group {{ resource_group }} --name {{ snap_name }} --source {{ source_disk }} ??

**Comment by evelyn-ys** [comment]
> Do you think we well see this fix included in the next point release of CLI?

Yes, definitely!

**Comment by evelyn-ys** [comment]
> I dont understand what i need change in my powershell script, if i use az snapshot create --resource-group {{ resource_group }} --name {{ snap_name }} --source {{ source_disk }} ??

If everything is going well, then noting need to be changed. If you fail with `(OperationNotAllowed) CopyStart creation is not supported for this subscription`, please use `az snapshot create --resource-group {{ resource_group }} --name {{ snap_name }} --source {{ source_disk }} --copy-start false`
