### ISSUE TITLE
[Documentation] Please document upgrade procedures

### ISSUE THREAD

**Issue by larryms** [Azure/azure-cli#2020]
Please document the best way to upgrade to the latest release when not using apt-get (e.g, on Windows)
Do I re-run 'pip install --user azure-cli'?  Or do I run 'az component update' with no other parameters?

**Comment by lostintangent** [comment]
I was actually wondering the exact same thing yesterday. I typically re-run `pip install --upgrade --pre --user --extra-index-url https://azureclinightly.blob.core.windows.net/packages azure-cli`, however, I've noticed that I need to run `az component update --pre --private` to update components that aren't installed by default (e.g. `redis` or `documentdb`). 

That said, I just ran `az component update`, and that seemed to update all of the CLI components as expected, so it would be great to know if running `az component update --pre --private` is in fact the recommended/best way of reving to the latest nightly bits.
