### ISSUE TITLE
Issues found for Azure Virtual Network Manager

### ISSUE THREAD

**Issue by yanfa317** [Azure/azure-cli#20208]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
1, For list-active-connectivity-config, after I add parameter regions, it will still return results from all regions.
2,  Security-type in security configuration should be readonly. Can you remove it from example.
3,  When creating security configuration with only required parameters(resource group/name/networkmanager name), the request will fail.
I checked the debug log. It seems the request body is empty({}), which is not acceptable for our gateway. So can you make a change so that it will contain empty property({“property”:{}}). (I am not 100% sure that it will work, so can you try it after making such change)?
4, in rule collection example, it should be network-group-id="**/subscriptions**/sub_id/resourceGroups/rgid/providers/Microsoft.Network/networkManagers/TestNetworkManager/networkGroups/TestNetworkGroup"
5, The targetlocation in post-commit should be required.

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Hi @yanfa317, I've some issue for 3 point. Does the 'property' marked as required in swagger definition?
