### ISSUE TITLE
az ams account sp create does not work and throw "Values of identifierUris property must use a verified domain" error 

### ISSUE THREAD

**Issue by xinyi-frieda** [Azure/azure-cli#20217]
**Describe the bug**
Unable to create/update SP using az ams account sp create
Error:
'Values of identifierUris property must use a verified domain of the organization or its subdomain: XXX'

**To Reproduce**
use command az ams account sp create.

**Expected behaviour**
Able to do the role assignment

**Environment summary**
CLI version: 2.30

**Tested workaround** 
Use a subdomain of the verified domain as the SP name and it can work: 
If needed, add your custom domain name using Azure Active Directory portal
Create the application with an authorized IdentifierUri
Create the service principal referring to this application

**Related Breaking change on AAD**
https://techcommunity.microsoft.com/t5/azure-tools/azure-active-directory-breaking-change-impacting-azure-cli-and/ba-p/2848388

**Comment by jiasli** [comment]
Here is how this issue is solved by

- `az ad`: https://github.com/Azure/azure-cli/pull/18312
- `az aro`: https://github.com/Azure/azure-cli/pull/20095

We also made an announcement at https://github.com/Azure/azure-cli/issues/19892.
