### ISSUE TITLE
`az account get-access-token` returns `expiresOn` as `null` for managed identity

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#20211]
Receiving "Error parsing Token Expiration Date" when using Azure CLI 2.30.0 with managed identity:

- https://github.com/getporter/azure-plugins/issues/39
- https://github.com/microsoft/AzureTRE/issues/1067

```
e51bc50c-7b3f-453a-bcec-30a3266982e8: Error context message = Error: could not save the pending action's status, the bundle was not executed:could not read storage schema document:Failed to login with Azure CLI:Error parsing Token Expiration Date \"\":Error parsing expiration date \"\".  

CloudShell Error: parsing time \"\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"\" as \"2006\"

CLI Error: parsing time \"\" as \"2006-01-02 15:04:05.999999\": cannot parse \"\" as \"2006\"
```

_Originally posted by @squillace in https://github.com/Azure/azure-cli/issues/19480#issuecomment-961395746_

**Comment by jiasli** [comment]
This issue is because Azure CLI 2.30.0 fails to set `expiresOn` for managed identity credential: 

https://github.com/Azure/azure-cli/blob/6442bedce93ea849dc02700fde4befef6313219a/src/azure-cli-core/azure/cli/core/_profile.py#L367-L374

The returned credential is later used by acr:

https://github.com/Azure/azure-cli/blob/04210197837bbceb547f86df7f086a42c96e0d2a/src/azure-cli/azure/cli/command_modules/acr/_docker_utils.py#L129

I will submit a PR to fix it.

For now, please pin Azure CLI to 2.29.2 which is the last working version. You may follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli to install specific versions of Azure CLI.

Also see

- https://github.com/Azure/azure-cli/issues/19700

**Comment by jiasli** [comment]
A quick search on `"Error parsing Token Expiration Date"` suggests some command is using Azure Go SDK to call `az account get-access-token` to get the access token and `expiresOn`: https://github.com/search?q=%22Error+parsing+Token+Expiration+Date%22&type=code

https://github.com/Azure/azure-sdk-for-go/blob/47db7e2935fc81ededd911e1b268c8729d5af38d/sdk/azidentity/azure_cli_credential.go#L163

```go
	tokenExpirationDate, err := parseExpirationDate(t.ExpiresOn)
	if err != nil {
		return nil, fmt.Errorf("Error parsing Token Expiration Date %q: %+v", t.ExpiresOn, err)
	}
```

But Azure CLI 2.30.0 fails to set `expiresOn` for managed identity credential: 


```
$ az account get-access-token
{
  "accessToken": "...",
  "expiresOn": null,
  "subscription": "0b1f6471-1bf0-4dda-aec3-cb9272f09590",
  "tenant": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
  "tokenType": "Bearer"
}
```

I will submit a PR to fix it.

For now, please pin Azure CLI to 2.29.2 which is the last working version. You may follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli to install specific versions of Azure CLI.

Also see

- https://github.com/Azure/azure-cli/issues/19700

**Comment by sdebruyn** [comment]
I can reproduce this, `expiresOn` is always `null` when using an MSI

**Comment by jiasli** [comment]
@sdebruyn, could you try the workaround and let us know if that works?

**Comment by sdebruyn** [comment]
I can confirm both workarounds work for me

**Comment by etiedem** [comment]
Just as a note for others with the workaround of installing the older 2.29.2 version on Mac. I had to delete the ~/.azure folder first.

**Comment by jiasli** [comment]
@etiedem, thanks for the information. I am a little bit curious:

1. How did you install the old Azure CLI 2.29.2 on MacOS? Did you install with `brew`? 
3. I am not aware that MacOS can support managed identity. How did you get managed identity work for MacOS?
4. `~/.azure/azureProfile.json` doesn't change between Azure CLI 2.29.2 and 2.30.0 for managed identity. Could you share the error you got?

**Comment by etiedem** [comment]
@jiasli - 

1. I did install with brew
`curl https://raw.githubusercontent.com/Homebrew/homebrew-core/7607de411f8ac0ad926ff2caadf8a9abf713cec8/Formula/azure-cli.rb > $(find $(brew --repository) -name azure-cli.rb) && brew reinstall azure-cli`
2. My use case was more for the Azure SDK portion of your comment. 
3. I was using the Python SDK and received the following:

`AzureCliCredential.get_token failed: Unexpected output from Azure CLI: 'AccessToken`

followed by my actual access token.

**Comment by jiasli** [comment]
Thanks for the information.

I tested with a docker:

```
# brew --repository
/home/linuxbrew/.linuxbrew/Homebrew

# find $(brew --repository) -name azure-cli.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/azure-cli.rb
```

It is indeed pretty smart to replace `/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/azure-cli.rb` with https://raw.githubusercontent.com/Homebrew/homebrew-core/7607de411f8ac0ad926ff2caadf8a9abf713cec8/Formula/azure-cli.rb and use `brew reinstall azure-cli`, given it is difficult to install an old version (https://github.com/Homebrew/discussions/discussions/155). 😸

---

As for your problem, I don't think this is the same problem as the one in this PR. This PR's issue only happens to **managed identity**.

1. Could you share the output of `az account get-access-token`?
2. Have you [configured your default output](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-values-and-environment-variables) to be `table`? I guess it is because `--output` doesn't work that caused your problem (https://github.com/Azure/azure-cli/issues/20269).
