### ISSUE TITLE
Unable to load extension aks-preview on linux

### ISSUE THREAD

**Issue by RaananHadar** [Azure/azure-cli#20214]
**Describe the bug**
I am getting an `unable to load aks-preview` extension under ubuntu linux.

**To Reproduce**
I have been facing multiple issues with azure-cli as I attempted to follow the user story documented in this [official document](https://docs.microsoft.com/en-us/azure/aks/gpu-cluster#add-a-node-pool-for-gpu-nodes). I can install aks-preview when using the azure-cli in the azure portal (no errors there) but not under my linux host.

**Expected behavior**
The model should load successfully.

**Environment summary**
az-cli 2.0.81 via apt-get.
on python 3.8.10
using ubuntu 20.04

**Comment by yonzhan** [comment]
route to service team

**Comment by jiasli** [comment]
Could you run the failed command again with `--debug` and share the output? Thanks.

**Comment by phealy** [comment]
[Please see the WARNING box on the Ubuntu azure-cli install page:](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#:~:text=Ubuntu%2020.04%20\(Focal,apt%20autoremove%20-y.)

```Ubuntu 20.04 (Focal Fossa) and 20.10 (Groovy Gorilla) include an azure-cli package with version 2.0.81 provided by the universe repository. This package is outdated and not recommended. If this package is installed, remove the package before continuing by running the command sudo apt remove azure-cli -y && sudo apt autoremove -y.```

You're using a very old version of Azure CLI (2.0.81; current is 2.30.0). Please follow the instructions on the page listed above to remove the old version, add the Microsoft repository, and reinstall a current version. After that you should be good to go!

**Comment by phealy** [comment]
Please feel free to reopen the issue if this doesn't resolve your problem!

**Comment by RaananHadar** [comment]
Thank you, this was the correct solution.
