### ISSUE TITLE
az network vnet subnet list-available-delegations not working

### ISSUE THREAD

**Issue by steveosacky** [Azure/azure-cli#20225]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I run the command with latest az cli version installed, as shown in the documentation, and I get the following error, 'list-available-delegations' is misspelled or not recognized by the system.

**To Reproduce**
Run az network vnet subnet list-available-delegations --location $region --subscription $subscriptionName --resource-group $resourceGroupName 

**Expected behavior**
Working response

**Environment summary**
Running PowerShell terminal in VS Code.

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
@steveosacky, Could you update your CLI and try again?

**Comment by steveosacky** [comment]
I have the latest version 2.30.0. The error message remains the same. 
Command: az network vnet subnet list-available-delegations --location $region --subscription $subscriptionName --resource-group $resourceGroupName
Error: 'list-available-delegations' is misspelled or not recognized by the system.
Can you not reproduce the error?

az --version

azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Extensions:
account                            0.2.1
azure-devops                      0.21.0
costmanagement                     0.1.1
resource-graph                     2.1.0

**Comment by kairu-ms** [comment]
@steveosacky Could you run following command to reset azure-cli target cloud and try again.
```
az cloud set --name AzureCloud --profile latest
```
