### ISSUE TITLE
--workspace-name is now --name

### ISSUE THREAD

**Issue by madiepev** [Azure/azure-cli#20220]
When working with the workspace with Azure Machine Learning CLI v2 (latest update), you have to specify the workspace name with the parameter --name or -n. In the documentation it still says --workspace-name or -w. Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63446f78-d3ac-0cc3-a102-a1612c54d90e
* Version Independent ID: a20a657c-aeaa-d122-0714-1aa2cfecd966
* Content: [az ml workspace](https://docs.microsoft.com/en-us/cli/azure/ml/workspace?view=azure-cli-latest#az_ml_workspace_delete)
* Content Source: [latest/docs-ref-autogen/ml/workspace.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/workspace.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by paulshealy1** [comment]
Thank you for the feedback! We have updated the documentation.
