### ISSUE TITLE
Azure Key Vault API Error - Azure CLI version 2.30.0

### ISSUE THREAD

**Issue by sgiddings-kunzleigh** [Azure/azure-cli#20226]
## I am unable to add a network access restriction to an azure key vault using the az keyvault network-rule add command.
**az keyvault network-rule add**
``

**Errors:(NoRegisteredProviderFound) No registered resource provider found for location 'usgovarizona' and API version '2021-06-01-preview' for type 'vaults'. The supported api-versions are '2015-06-01, 2016-10-01, 2018-02-14-preview, 2018-02-14, 2019-09-01, 2021-04-01-preview'. The supported locations are 'usgovvirginia, usgoviowa, usdodcentral, usdodeast, usgovtexas, usgovarizona'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'usgovarizona' and API version '2021-06-01-preview' for type 'vaults'. The supported api-versions are '2015-06-01, 2016-10-01, 2018-02-14-preview, 2018-02-14, 2019-09-01, 2021-04-01-preview'. The supported locations are 'usgovvirginia, usgoviowa, usdodcentral, usdodeast, usgovtexas, usgovarizona'.**
```

```

## To Reproduce:
az keyvault network-rule add --name (KEY VAULT NAME) --ip-address (IP ADDRESS) --resource-group (RSG NAME)

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
macOS-12.0.1-x86_64-i386-64bit, Darwin 21.1.0
Python 3.9.7
Installer: HOMEBREW
azure-cli 2.30.0

Extensions:
ssh 0.1.8
interactive 0.4.5

```
## Additional Context
This also happens on Linux Ubuntu 20.04 with version 2.30.0 but it works as expected in version Azure CLI version 2.28.0.

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
@jlichwa for awareness
Customers are getting '2021-06-01-preview' not registered error for mgmt plane 'vaults'

**Comment by jlichwa** [comment]
@sgiddings-kunzleigh the 2021-06-01 is supported in gov clouds now. Thank you
