### ISSUE TITLE
[Compute] Shared Gallery Get/List Update.

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#20224]
**Is your feature request related to a problem? Please describe.**

Currently Shared Gallery List return uses paging, CLI does not support nextLink for shared gallery right now, we need to support nextLink.

**Describe the solution you'd like**

For the return of shared gallery, support nextLink, user can use link from 'nextLink' return field and put it to get next page.

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Compute

**Comment by PARADISSEEKR** [comment]
Hi @kangsun-ctrl , In what way should `nextLink` be used, as a parameter or in other ways, could you explain it in detail?

**Comment by kangsun-ctrl** [comment]
@PARADISSEEKR  Actually Xing Zhou implemented nextLink for community gallery before, so how this works is that this is for paging. For example, we return 40 items one page and there are totally 100 items,  so we need to return the nextLink and user call the nextLink to get the next 40 items.

**Comment by zhoxing-ms** [comment]
@PARADISSEEKR Please refer to the paging function implementation of `az sig image-definition\image-version list-community`
[code link](https://github.com/Azure/azure-cli-extensions/blob/0c092feacc3ea493e1cc7b1ca3cbc0b2336cabda/src/image-gallery/azext_image_gallery/_params.py#L49-L50)
