### ISSUE TITLE
dataset instead of data

### ISSUE THREAD

**Issue by madiepev** [Azure/azure-cli#20239]
When running the following command in Cloud Shell: `az ml data create --file ./mslearn-aml-cli/Allfiles/Labs/01/data-local-path.yml` 

I get this notification:
This command is implicitly deprecated because command group 'ml data' is deprecated and will be removed in a future release. Use 'ml dataset' instead.
Command group 'ml data' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus

I'm using the CLI (v2), the (v1) is not installed. Should the documentation be updated to use dataset instead of data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5a19a0-c37e-4567-0c30-7efe1c433dfb
* Version Independent ID: 8c4e79d0-0f84-3a28-bfb4-9f972e02a37f
* Content: [az ml data](https://docs.microsoft.com/en-us/cli/azure/ml/data?view=azure-cli-latest#az_ml_data_create)
* Content Source: [latest/docs-ref-autogen/ml/data.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/data.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by paulshealy1** [comment]
Thanks for the feedback! We're investigating this now.

**Comment by paulshealy1** [comment]
The documentation is now up to date: https://docs.microsoft.com/en-us/cli/azure/ml?view=azure-cli-latest
