### ISSUE TITLE
'az ml endpoint' seems to no longer exist

### ISSUE THREAD

**Issue by roalexan** [Azure/azure-cli#20247]
looks like the latest version of the cli has to use, for example, "online-deployment"

**Comment by yonzhan** [comment]
route to service team

**Comment by paulshealy1** [comment]
@roalexan - you are correct that "az ml endpoint" was split into "az ml online-endpoint", "az ml online-deployment", "az ml batch-endpoint", and "az ml batch-deployment". The full command reference is here: https://docs.microsoft.com/en-us/cli/azure/ml?view=azure-cli-latest
