### ISSUE TITLE
`portalocker` error: FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by edvinas31** [Azure/azure-cli#20252]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 75, in get_access_token
    tenant=tenant)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 381, in get_raw_token
    credential = self._create_credential(account, tenant)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 588, in _create_credential
    return identity.get_user_credential(username_or_sp_id)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 182, in get_user_credential
    return UserCredential(self.client_id, username, **self._msal_app_kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/msal_authentication.py", line 41, in __init__
    accounts = self.get_accounts(username)
  File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 872, in get_accounts
    accounts = self._find_msal_accounts(environment=self.authority.instance)
  File "/opt/az/lib/python3.6/site-packages/msal/application.py", line 912, in _find_msal_accounts
    query={"environment": environment})
  File "/opt/az/lib/python3.6/site-packages/msal_extensions/token_cache.py", line 53, in find
    with CrossPlatLock(self._lock_location):
  File "/opt/az/lib/python3.6/site-packages/msal_extensions/cache_lock.py", line 29, in __enter__
    file_handle = self._lock.__enter__()
  File "/opt/az/lib/python3.6/site-packages/portalocker/utils.py", line 199, in __enter__
    return self.acquire()
  File "/opt/az/lib/python3.6/site-packages/portalocker/utils.py", line 161, in acquire
    fh = self._prepare_fh(fh)
  File "/opt/az/lib/python3.6/site-packages/portalocker/utils.py", line 194, in _prepare_fh
    fh.truncate(0)
FileNotFoundError: [Errno 2] No such file or directory

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --resource {} --subscription {} -o={}`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
azure-devops 0.20.0

**Comment by edvinas31** [comment]
Also, wanted to notify that I am using terragrunt for deploying azure resources and after I switched from 2.29.2 to 2.30.0 using this manual https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#install-specific-version it is showing similar error like above. Seems to me that the new az cli version is broken somehow

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The error is from `portalocker`. 

https://github.com/WoLpH/portalocker/blob/3025e66895ce819d806ac7201041af9d0b4f67bb/portalocker/utils.py#L298

```py
            fh.seek(0)
            fh.truncate(0)
```

It is pretty weird that `seek` succeeds, but `truncate` failed.

Could you check if `msal_token_cache.json.lockfile` was deleted during execution? 

\+@rayluo

**Comment by jiasli** [comment]
Is this a steady repro? Or are you running multiple `az` instances concurrently?

**Comment by rayluo** [comment]
> The error is from `portalocker`.
> 
> https://github.com/WoLpH/portalocker/blob/3025e66895ce819d806ac7201041af9d0b4f67bb/portalocker/utils.py#L298
> 
> ```python
>             fh.seek(0)
>             fh.truncate(0)
> ```
> 
> It is pretty weird that `seek` succeeds, but `truncate` failed.
> 
> Could you check if `~/.azure/msal_token_cache.json.lockfile` was deleted during execution?
> 
> +@rayluo

+ portalocker author @wolph for awareness

**Comment by rayluo** [comment]
> Could it somehow be a race condition where something else is either deleting the file? It looks like the `cache_lock.py` code can remove the lock file on exit which might be related: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/26240cbc092e0fd28badf52753888051db3a4cec/msal_extensions/cache_lock.py#L65-L74

Possibly. Currently MSAL Extensions indeed creates and deletes that lock file frequently.

Does portalocker expect the lock file to remain available most of the time?

Could portalocker be refactored so that any failure during [this preparation](https://github.com/WoLpH/portalocker/blob/v2.3.2/portalocker/utils.py#L256-L257) can be put inside the [retry logic](https://github.com/WoLpH/portalocker/blob/v2.3.2/portalocker/utils.py#L230-L249)?

**Comment by WoLpH** [comment]
> Does portalocker expect the lock file to remain available most of the time?

As soon as the lock is acquired, portalocker does not expect the lock to disappear anymore. That seems a reasonable assumption to me since nothing else should be able to acquire the lock at that point.

> Could portalocker be refactored so that any failure during [this preparation](https://github.com/WoLpH/portalocker/blob/v2.3.2/portalocker/utils.py#L256-L257) can be put inside the [retry logic](https://github.com/WoLpH/portalocker/blob/v2.3.2/portalocker/utils.py#L230-L249)?

Yes, that's certainly an option. But I think there might be an underlying bug somewhere that is causing this. This scenario should never occur if locking works properly.

**Comment by edvinas31** [comment]
> Is this a steady repro? Or are you running multiple `az` instances concurrently?

I am not 100 % sure, but I would say it is running multiple 'az' instances concurrently, because when running "terragrunt run-all ..." it goes to multiple directories and as far I suspect executes az token command at the same time

**Comment by rayluo** [comment]
> > Does portalocker expect the lock file to remain available most of the time?
> 
> As soon as the lock is acquired, portalocker does not expect the lock to disappear anymore. That seems a reasonable assumption to me since nothing else should be able to acquire the lock at that point.
> 
> > Could portalocker be refactored so that any failure during [this preparation](https://github.com/WoLpH/portalocker/blob/v2.3.2/portalocker/utils.py#L256-L257) can be put inside the [retry logic](https://github.com/WoLpH/portalocker/blob/v2.3.2/portalocker/utils.py#L230-L249)?
> 
> Yes, that's certainly an option. But I think there might be an underlying bug somewhere that is causing this. This scenario should never occur if locking works properly.

@wolph, yes, I understand that the MSAL EXtension's usage pattern of frequently creating and deleting the locker file sounds somewhat unusual. MSAL EX chose to do so, because it wants to inter-operate with its counterparts written in other languages, which collectively chose to use the presence or absence of the lock file as part of the locking mechanism.

In terms of portalocker, it seems there would be no downside if we put that `truncate(0)` into the retry logic?

**Comment by WoLpH** [comment]
> In terms of portalocker, it seems there would be no downside if we put that `truncate(0)` into the retry logic?

There's no real downside, the only "downside" I see is that it could hide these errors. This scenario should not occur so I do believe it should warrant a warning that your lock might not be valid anymore.

Once the lockfile has disappeared, your lock has disappeared as well and anyone else could lock in the mean time.

**Comment by rayluo** [comment]
> > In terms of portalocker, it seems there would be no downside if we put that `truncate(0)` into the retry logic?
> 
> There's no real downside, the only "downside" I see is that it could hide these errors. This scenario should not occur so I do believe it should warrant a warning that your lock might not be valid anymore.
> 
> Once the lockfile has disappeared, your lock has disappeared as well and anyone else could lock in the mean time.

Thank you, @WoLpH , I agree with your assessment. I am currently trying to make some change from our side. I'll ping you again if we need your attention.

**Comment by edvinas31** [comment]
Hello, any updates on that?

**Comment by rayluo** [comment]
> Hello, any updates on that?

We are still working on it. But perhaps you won't mind try this experimenting adjustment? https://github.com/Azure/azure-cli/issues/20273#issuecomment-971409849

If you try it, please report back here in this issue to let us know the result. Thanks!

**Comment by rayluo** [comment]
@edvinas31 , [this solution](https://github.com/Azure/azure-cli/issues/20273#issuecomment-992121775) should work. Please reopen if that does not work for you.

**Comment by edvinas31** [comment]
> @edvinas31 , [this solution](https://github.com/Azure/azure-cli/issues/20273#issuecomment-992121775) should work. Please reopen if that does not work for you.

Good morning @rayluo . Tried to use your mentioned solution and ran following line on my local computer "python3 -m pip install -U msal-extensions" (used wsl2 ubuntu) and still got the same issue:

`
....
│ Error: Error obtaining Authorization Token from the Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: ERROR: The command failed with an unexpected error. Here is the traceback:
│ ERROR: [Errno 2] No such file or directory
...
`

This happens when using 2.31.0 version

**Comment by jiasli** [comment]
On Ubuntu, the quick fix should be 

```
sudo /opt/az/bin/python3 -m pip install --upgrade msal-extensions
```

As for `[Errno 2] No such file or directory`, could you share the full call stack?

**Comment by edvinas31** [comment]
I have ran command: 

`sudo /opt/az/bin/python3 -m pip install --upgrade msal-extensions`

However I got:

```
│ Error: Error obtaining Authorization Token from the Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: ERROR: The command failed with an unexpected error. Here is the traceback:
│ ERROR: Ran out of input
│ Traceback (most recent call last):
│   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
│     cmd_result = self.invocation.execute(args)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
│     raise ex
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
│     results.append(self._run_job(expanded_arg, cmd_copy))
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
│     result = cmd_copy(params)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
│     return self.handler(*args, **kwargs)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
│     return op(**command_args)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 77, in get_access_token
│     tenant=tenant)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 383, in get_raw_token
│     credential = self._create_credential(account, tenant)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 593, in _create_credential
│     return identity.get_user_credential(username_or_sp_id)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 209, in get_user_credential
│     return UserCredential(self.client_id, username, **self._msal_app_kwargs)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 84, in _msal_app_kwargs
│     Identity._msal_http_cache = self._load_msal_http_cache()
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 113, in _load_msal_http_cache
│     persisted_http_cache = pickle.load(f)
│ EOFError: Ran out of input
│ To open an issue, please run: 'az feedback
```

**Comment by jiasli** [comment]
This is another problem caused by `~/.azure/msal_http_cache.bin`. I am not very clear how it happens.

Could you remove `~/.azure` and try again?

**Comment by edvinas31** [comment]
Removed `~/.azure` and tried again. Same issue happens:

```
│ Error: unable to get authorization token for resource manager: Error obtaining Authorization Token from the Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: ERROR: The command failed with an unexpected error. Here is the traceback:
│ ERROR: Ran out of input
│ Traceback (most recent call last):
│   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
│     cmd_result = self.invocation.execute(args)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
│     raise ex
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
│     results.append(self._run_job(expanded_arg, cmd_copy))
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
│     result = cmd_copy(params)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
│     return self.handler(*args, **kwargs)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
│     return op(**command_args)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 77, in get_access_token
│     tenant=tenant)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 383, in get_raw_token
│     credential = self._create_credential(account, tenant)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 593, in _create_credential
│     return identity.get_user_credential(username_or_sp_id)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 209, in get_user_credential
│     return UserCredential(self.client_id, username, **self._msal_app_kwargs)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 84, in _msal_app_kwargs
│     Identity._msal_http_cache = self._load_msal_http_cache()
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 113, in _load_msal_http_cache
│     persisted_http_cache = pickle.load(f)
│ EOFError: Ran out of input
│ To open an issue, please run: 'az feedback'
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on terraform_config.tf line 13, in provider "azurerm":
│   13: provider "azurerm" {
```

**Comment by jiasli** [comment]
Moving to a new issue #20707.
