### ISSUE TITLE
Azure Create Deployment User - PHP App

### ISSUE THREAD

**Issue by percepticus** [Azure/azure-cli#20255]
## Describe the bug

**Command Name**
`az webapp deployment user set`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment user set --user-name {} --password {}`

## Environment Summary
```
Linux-5.11.0-1020-azure-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@percepticus Apologies for the late reply. Could you please install the most recent version of the [AzCLI ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)and let us know if you still face this issue ? Awaiting your reply.

Similar issue: https://github.com/Azure/azure-cli/issues/14800 https://github.com/Azure/azure-cli/issues/15105
