### ISSUE TITLE
Issues when trying to create a snapshot of a Uniform VMSS OS disk in AzureCLI

### ISSUE THREAD

**Issue by nameier** [Azure/azure-cli#20258]
## Describe the bug

**Command Name**
`az snapshot create`

**Errors:**
```
(ResourceNotFound) The Resource 'Microsoft.Compute/disks/datadiskvmss1_datadiskvmss1_0_OsDisk_1_dca81669e5884c35ad5150dfd854934e' under resource group 'DATADISK' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.Compute/disks/datadiskvmss1_datadiskvmss1_0_OsDisk_1_dca81669e5884c35ad5150dfd854934e' under resource group 'DATADISK' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `vmssosdisk=$(az vmss show -g {} -n {} --instance-id {} --query storageProfile.osDisk.managedDisk.id -o tsv) //this command DOES pull the correct resourceURI if you run it by itself without turning it into a variable
- `az snapshot create -g {} -n {} --source $vmssosdisk --debug`

## Expected Behavior
I am trying to replicate the steps to create a snapshot of a VMSS instance OS disk in CLI.  The PowerShell steps are listed here: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#how-do-i-take-a-snapshot-of-a-virtual-machine-scale-set-instance-

## Environment Summary
```
Linux-4.4.0-22000-Microsoft-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
interactive 0.4.5
maintenance 1.3.0
resource-graph 2.1.0
vm-repair 0.3.8

```

**Comment by nameier** [comment]
Working with a colleague who has Azure CLI version 2.29.1, and they are not getting the same issues.

**Comment by yonzhan** [comment]
Compute

**Comment by evelyn-ys** [comment]
Hi @nameier, I have raised a PR to fix this. For now, you can specify `--copy-start false` to bypass this issue. Sorry for the inconvenience.

**Comment by nameier** [comment]
@evelyn-ys thank you very much!  This worked.

**Comment by Michael-Sinz** [comment]
> Hi @nameier, I have raised a PR to fix this. For now, you can specify `--copy-start false` to bypass this issue. Sorry for the inconvenience.

That worked great with newer Azure CLIs but not older versions (such as needed in certain other azure "clouds")

**Comment by evelyn-ys** [comment]
> > Hi @nameier, I have raised a PR to fix this. For now, you can specify `--copy-start false` to bypass this issue. Sorry for the inconvenience.
> 
> That worked great with newer Azure CLIs but not older versions (such as needed in certain other azure "clouds")

In other azure clouds, if you are using 
- Azure CLI 2.30.0, you can add `--copy-start false` to bypass this issue
- Azure CLI 2.29.2 or older, there's no issue when creating snapshot of VMSS OS disk

**Comment by Michael-Sinz** [comment]
> > > Hi @nameier, I have raised a PR to fix this. For now, you can specify `--copy-start false` to bypass this issue. Sorry for the inconvenience.
> > 
> > 
> > That worked great with newer Azure CLIs but not older versions (such as needed in certain other azure "clouds")
> 
> In other azure clouds, if you are using
> 
> * Azure CLI 2.30.0, you can add `--copy-start false` to bypass this issue
> * Azure CLI 2.29.2 or older, there's no issue when creating snapshot of VMSS OS disk

Yes - we just had to add an azure CLI version check to see if it is 2.30.0 or later and add the --copy-start false flag only then.
