### ISSUE TITLE
Support with Updating Management Groups CLI

### ISSUE THREAD

**Issue by git-thomasdolan** [Azure/azure-cli#20265]
**Resource Provider**
Management Groups

**Description of Feature or Work Requested**
I need assistance in updating the Management Groups CLI to be up to date with the latest version our our APIs using the CodeGen tool. The CLI has not been updated in over two years and I am not sure if we have used CodeGen before.

**Minimum API Version Required**
2021-04-01
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/managementgroups/resource-manager/Microsoft.Management

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/managementgroups/resource-manager/Microsoft.Management/stable

**Target Date**
ASAP, we have customers reporting issues with our CLI triggering IcMs

**Comment by yonzhan** [comment]
PLR

**Comment by zhoxing-ms** [comment]
@git-thomasdolan  I see that you have submitted a PR https://github.com/Azure/azure-cli-extensions/pull/4198 about managementgroup extension.
I'd like to confirm with you that your PR is used to complete this requirement?

**Comment by git-thomasdolan** [comment]
@zhoxing-ms Yes that PR would satisfy this requirement. Any timeline on when this can be reviewed?

**Comment by zhoxing-ms** [comment]
@git-thomasdolan OK, I'll review when I'm free these two days
