### ISSUE TITLE
Migrate community gallery from private package to CLI extension

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#20262]
**Is your feature request related to a problem? Please describe.**

This is for Azure Compute community gallery private package. Current solution is to use private package Xing Zhou provided. However, it requires user to install python virtual env and it might cause confusion. To have better user experience, we plan to use CLI extension full support for community gallery and edge build link for 'az vm/vmss' deployment for community gallery vm deployment.

**Describe the solution you'd like**

It is above.

**Describe alternatives you've considered**

**Additional context**

https://github.com/Azure/azure-cli/issues/19882

**Comment by yonzhan** [comment]
Compute
