### ISSUE TITLE
Found multiple accounts with the same username.

### ISSUE THREAD

**Issue by dohnuts** [Azure/azure-cli#20276]
Please report to us via Github: https://github.com/Azure/azure-cli/issues/new

well , reported :-/

but how to give you anything relevant, because the login is a email , i don't want to put that here

**Comment by GroupeCitypassengerInc** [comment]
Please help us microsoft
<img src='https://pa1.narvii.com/6558/ea8bcd469914da0610ac21927929c310e0decaf6_hq.gif' alt='meme'/>

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This has been reported at #20168. Could you try https://github.com/Azure/azure-cli/issues/20168#issuecomment-963747032 and see if you can get unblocked?

**Comment by dohnuts** [comment]
It s ok apparently
