### ISSUE TITLE
Multiple Accounts with same username

### ISSUE THREAD

**Issue by davidt241** [Azure/azure-cli#20272]
Trying to connect to my azure account from local machine using Azure CLI in Powershell
az login opens up MS sign in which I sign into and am presented with Authenticator app I authenticate. The webbrowser presents the wait 10 sec screen whilst powershell  shows
 PS C:\Users\DavidTyrrell> az login
The default web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
Found multiple accounts with the same username. Please report to us via Github: https://github.com/Azure/azure-cli/issues/new

I have my personal account linked to my work account to take advantage of the MS ESI scheme. Are you able to advise?

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This has been reported at #20168. Could you try https://github.com/Azure/azure-cli/issues/20168#issuecomment-963747032 and see if you can get unblocked?

**Comment by davidt241** [comment]
That worked thanks
