### ISSUE TITLE
specify aro/ocp version

### ISSUE THREAD

**Issue by TiloGit** [Azure/azure-cli#20279]
how to specify the aro / ocp version to use (e.g. 4.7 , 4.8...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08eb181a-b377-c854-69cc-3b9307f59f72
* Version Independent ID: 2142cb43-b027-86a1-6d3c-2f77bf86d177
* Content: [az aro](https://docs.microsoft.com/en-us/cli/azure/aro?view=azure-cli-latest#az_aro_create)
* Content Source: [latest/docs-ref-autogen/aro.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/aro.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by TiloGit** [comment]
it's on roadmap but currently not available: 

https://github.com/Azure/OpenShift/issues/208

**Comment by mjudeikis** [comment]
Hey @yonzhan . neither I nor Jim is part of the team anymore. @bennerv  can you sort this out once you have time?

**Comment by bennerv** [comment]
@yonzhan this can be closed.  `az aro get-versions -l <location>` and `az aro create --version` supports versions now.
