### ISSUE TITLE
Support private endpoint related command for Azure Data Factory

### ISSUE THREAD

**Issue by ligengatms** [Azure/azure-cli#20282]
**Is your feature request related to a problem? Please describe.**
This is the swagger commit: https://github.com/Azure/azure-rest-api-specs/commit/08c507864c686ee9cdbbeb4a3d12cdccd591afc8#diff-70731da8ee74a2c2d94d6cce21b715ca2e36ce87ebb2dd732a459a28ba5b28cb

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
network
