### ISSUE TITLE
az network bastion create: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by BhargaviAnnadevara-MSFT** [Azure/azure-cli#20289]
_<Originally reported by @diongerritzen in MicrosoftDocs/azure-docs-cli#2822>_

## Describe the bug

**Command Name**
`az network bastion create`

**Errors:**
```
'<' not supported between instances of 'NoneType' and 'int'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network bastion create --location {} --name {} --public-ip-address {} --resource-group {} --vnet-name {}`

## Expected Behavior
Successful execution of this command should create an Azure bastion host machine.

## Environment Summary
```
Linux-5.4.0-1063-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.30.0
azure-cli-ml 1.19.0

Extensions:
vmware 0.5.5
db-up 0.2.4
customlocation 0.1.2
aks-preview 0.4.50
resource-graph 1.1.0
log-analytics-solution 0.1.1
k8s-extension 0.4.2
azure-cli-ml 1.19.0
ai-examples 0.2.5
ssh 0.1.8
```
## Additional Context
As quoted by @diongerritzen in the referenced issue:

> According to the docs the required parameters of the `az network bastion create` command are `--name`, `--public-ip-address`, `--resource-group` and `--vnet-name`. However, running the command with just these four parameters results in the following error: `'<' not supported between instances of 'NoneType' and 'int'`
> 
> This can apparently be resolved by adding the optional parameter `--scale-units`.

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
@necusjz This issue caused by this line when unit_num is None. https://github.com/Azure/azure-cli/blob/4048103ca7ae022ab5526758d824b1566535764f/src/azure-cli/azure/cli/command_modules/network/_validators.py#L747-L748
