### ISSUE TITLE
No (documented) way to perform env var interpolation in container group yml file

### ISSUE THREAD

**Issue by m1stermanager** [Azure/azure-cli#20280]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
when specifying a yml file in the `az container create` the format $VAR ${VAR} and ${env:VAR} are all passed as literals

**To Reproduce**
create a container group from a yml file and attempt to include a value from your env.

**Expected behavior**
the value should be interpolated into the yml file when submitted to azure

**Environment summary**
▶ az --version
azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Python location '/opt/az/bin/python3'
Extensions directory '/home/josh/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Oct 29 2021, 10:11:58)
[GCC 7.5.0]

**Additional context**

**Comment by yonzhan** [comment]
route to service team
