### ISSUE TITLE
Bug in Docu

### ISSUE THREAD

**Issue by azurepilot** [Azure/azure-cli#20292]
There seems to be a bug in the documentation: there are 2 entries for Referenence/Azure Devops and DevOps.
One leads to start page, the other to the content. 

BR, Jörg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db571e2-29f1-aa5b-9879-82564633e5b7
* Version Independent ID: c6331f40-2660-1830-9a7c-0ed62463a994
* Content: [az devops](https://docs.microsoft.com/en-us/cli/azure/devops?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/devops.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/devops.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
@azurepilot Apologies for the delayed response. Are you referring to this link https://docs.microsoft.com/en-us/rest/api/azure/devops/ document? it seems to pointing to the same document in both the place. If something else you are referring to let us know we will be happy to assist you.
