### ISSUE TITLE
Support forceDeletion of a VM in Azure CLI

### ISSUE THREAD

**Issue by Aishwarya-C-S** [Azure/azure-cli#20299]
**Resource Provider**
 Compute Resource Provider 

**Description of Feature or Work Requested**
This feature enables force deleting a virtual machine. Swagger link : https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/delete#force-delete-a-vm. Customer experience is to delete a VM with more reliability and much faster. Also enables customer to delete a failed VM better. Force delete customer onboarding doc here : https://microsoft.sharepoint.com/:w:/r/teams/AZCompute/fabric/_layouts/15/Doc.aspx?sourcedoc=%7B66152580-5B9C-4E6A-B375-79ED3E619BE7%7D&file=Force%20Delete%20VM%20Customer%20Documentation.docx&wdLOR=c788FA57E-50D6-49D6-837E-A0A2E780F8F0&action=default&mobileredirect=true&share=IQGAJRVmnFtqTrN1ee0-YZvnAdLGYDbUfhBZmdNdTHceSf8

**Minimum API Version Required**
2020-06-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/10801

**Target Date**
Nov 2021

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
In fact, the command `az vm delete` already has the parameter `--force-deletion`. Could you please see if it can meet this requirement?

**Comment by Aishwarya-C-S** [comment]
> @Aishwarya-C-S In fact, the command `az vm delete` already has the parameter `--force-deletion`. Could you please see if it can meet this requirement?

I see, yes it seems like it is there, does it get translated from SDK changes? I haven't explicitly requested before

**Comment by zhoxing-ms** [comment]
Yes, because this command directly calls the related methods in the Python SDK

**Comment by zhoxing-ms** [comment]
@Aishwarya-C-S  If this requirement is satisfied, please close it, thank you

**Comment by zhoxing-ms** [comment]
@Aishwarya-C-S Since this requirement seems to have been implemented, so I close it first. If you think it has additional features to implement, please reopen it~
