### ISSUE TITLE
functionapp: unhide Node.js 16 preview (alrod)

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-cli#20303]
**Resource Provider**
functionapp

**Description of Feature or Work Requested**
Unhide Node.js 16

**Target Date**
ASAP (next release)

@alrod @panchagnula

**Comment by yonzhan** [comment]
route to service team

**Comment by anthonychu** [comment]
@alrod will take a look at this.

**Comment by anthonychu** [comment]
Resolved by https://github.com/Azure/azure-cli/pull/20659
