### ISSUE TITLE
Support forceDeletion of in VMSS ScaleIn Policy in Azure CLI

### ISSUE THREAD

**Issue by Aishwarya-C-S** [Azure/azure-cli#20301]
**Resource Provider**
Compute Resource Provider

**Description of Feature or Work Requested**
This property allows you to specify if virtual machines chosen for removal have to be force deleted when a virtual machine scale set is being scaled-in.

**Minimum API Version Required**
2021-07-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/15073

**Target Date**
Dec 2021

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@Aishwarya-C-S Could you tell me which CLI commands are specifically involved in this requirement?

**Comment by Aishwarya-C-S** [comment]
> @Aishwarya-C-S Could you tell me which CLI commands are specifically involved in this requirement?

az vmss update is the cmd and newest member is ScaleInPolicy.forceDeletion as per : https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-sets/create-or-update#scaleinpolicy

**Comment by PARADISSEEKR** [comment]
@Aishwarya-C-S I updated vmss according to the example(https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2021-07-01/examples/compute/CreateAScaleSetWithScaleInPolicy.json) but service returns this `Virtual Machine Scale Sets with property scaleInPolicy.forceDeletion set is not supported in this region.`
