### ISSUE TITLE
Support forceDeletion of a VMSS in Azure CLI

### ISSUE THREAD

**Issue by Aishwarya-C-S** [Azure/azure-cli#20300]
**Resource Provider**
Compute Resource Provider

**Description of Feature or Work Requested**
This feature enables force deleting a virtual machine scale set and VM instances in virtual machine scaleset. Customer experience is to delete a VM/VMSS with more reliability and much faster. Also enables customer to delete a failed VM better. Force delete customer onboarding doc here : https://microsoft.sharepoint.com/:w:/r/teams/AZCompute/fabric/_layouts/15/Doc.aspx?sourcedoc=%7B66152580-5B9C-4E6A-B375-79ED3E619BE7%7D&file=Force%20Delete%20VM%20Customer%20Documentation.docx&wdLOR=c788FA57E-50D6-49D6-837E-A0A2E780F8F0&action=default&mobileredirect=true&share=IQGAJRVmnFtqTrN1ee0-YZvnAdLGYDbUfhBZmdNdTHceSf8

**Minimum API Version Required**
2020-12-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/11620/

**Target Date**
December 2021

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@Aishwarya-C-S In fact, the command `az vmss delete` already has the parameter `--force-deletion`. Could you please see if it can meet this requirement?

**Comment by Aishwarya-C-S** [comment]
> @Aishwarya-C-S In fact, the command `az vmss delete` already has the parameter `--force-deletion`. Could you please see if it can meet this requirement?

thank you, I think it is sufficient, thanks
