### ISSUE TITLE
Allow az synapse workspace-package upload-batch to accept an Azure Blob location

### ISSUE THREAD

**Issue by ross-p-smith** [Azure/azure-cli#20310]
It would more advantageous for us to be able to upload a batch of jar files that exist in Blob Storage rather than a local directory. The jars that we wish to upload are already in the cloud, we are having to download them and re-upload them. Surely we could hook into the az storage copy so that we copy large binaries in the cloud from one storage account to another.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a81dc62-06e0-08aa-c35b-7fa90b468746
* Version Independent ID: 6f06bdcd-7cc3-d5e4-c2b9-2cf8fb85621a
* Content: [az synapse workspace-package](https://docs.microsoft.com/en-us/cli/azure/synapse/workspace-package?view=azure-cli-latest#az_synapse_workspace_package_upload_batch)
* Content Source: [latest/docs-ref-autogen/synapse/workspace-package.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/synapse/workspace-package.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by wonner** [comment]
Hi @ross-p-smith , thanks for your feedback! It's more like a PM problem. We don't have plan to support this scenario for now. In Synapse Studio, we only support to upload workspace package from local file, so we keep the same user experience in Azure CLI. As you said, you can download the files then re-upload them to the workspace as a workaround. Sorry for the inconvenience.
