### ISSUE TITLE
Registering namespace Microsoft.LoadTestService is stuck for more than 16 hours

### ISSUE THREAD

**Issue by faisalcse98** [Azure/azure-cli#20318]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
At the subscription ProjectTorch (f34bfe3a-54d9-42e5-a7c1-a4513b714b11), I was looking to register the namespace Microsoft.LoadTestService using the following command from Azure CLI:

az provider register --namespace Microsoft.LoadTestService

The operation is stuck at "Registering" state for more than 16 hours now.

**To Reproduce**
Run the following command:
az provider register --namespace Microsoft.LoadTestService

Then the operation is stuck at "Registering" state forever.

**Expected behavior**
The operation should successfully register the namespace within few minutes.

**Environment summary**
N/A

**Additional context**
N/A

**Comment by yonzhan** [comment]
az provider

**Comment by michalmlaka** [comment]
Hi, have you solved this somehow ? 

I am stuck at the same point for 2nd day.

Thanks

![image](https://user-images.githubusercontent.com/41904537/149653535-9137a75a-f037-4510-8bb1-435c31207cd9.png)

**Comment by faisalcse98** [comment]
@michalmlaka I was unblocked after few hours. The team can confirm whether they tool any action to unblock me.
