### ISSUE TITLE
Cannot run deployment on azure sandbox: Found multiple accounts with the same username

### ISSUE THREAD

**Issue by mohit-gitlearn** [Azure/azure-cli#20317]
I am not able to run deployment on azure sandbox from my learning account.
Please resolve the issue as soon as possible.
error 
"Found multiple accounts with the same username."

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This issue is tracked at https://github.com/Azure/azure-cli/issues/20168.

@mohit-gitlearn, could you let us know 

1. What instruction you followed to "run deployment on azure sandbox from my learning account"?
2. How is the learning account set up?
