### ISSUE TITLE
az vm list -o table does not list the VMs in table format on macOS Monterey version 12.0.1

### ISSUE THREAD

**Issue by mingqxu7** [Azure/azure-cli#20322]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

az vm list -o table doesn't work

**To Reproduce**

% az --version
azure-cli                         2.30.0

core                              2.30.0
telemetry                          1.0.6

Python location '/usr/local/Cellar/azure-cli/2.30.0/libexec/bin/python'
Extensions directory '/Users/mingqxu/.azure/cliextensions'

Python (Darwin) 3.9.8 (main, Nov 10 2021, 03:55:42)
[Clang 13.0.0 (clang-1300.0.29.3)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

% az vm list -o table
[
  {
    "additionalCapabilities": null,
    "applicationProfile": null,
    "availabilitySet": null,
    "billingProfile": null,
    "capacityReservation": null,
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true,
        "storageUri": null
      }
     ... 
]

**Expected behavior**

I expect the output will be in table format, listing the VMs under the current subscription.

**Environment summary**

brew install azure-cli

**Additional context**

**Comment by yonzhan** [comment]
Compute

**Comment by ecker00** [comment]
Got the same issue. Every `--output xxx` seems to always end up as `json` format.

**Comment by zhoxing-ms** [comment]
> Python (Darwin) 3.9.8 (main, Nov 10 2021, 03:55:42)

@mingqxu7 @ecker00 This is a known issue #20269 due to a serious regression in Python 3.9.8.
Could you use other versions of Python to execute CLI commands?

**Comment by jiasli** [comment]
I don't think it is allowed on MacOS and brew to install old versions of Python (like 3.9.7). We are working with brew team to release Azure CLI on Python 3.10 as soon as possible which is not affected (https://github.com/Homebrew/homebrew-core/pull/86758).

For now, you may manually install Python 3.10 and install `azure-cli` with 

```
brew install python@3.10
pip install azure-cli
```

**Comment by abdrrahimelh** [comment]
It's `az vm list -otable `
