### ISSUE TITLE
`--output` and `--query` global args not working with v2.30.0 on macOS

### ISSUE THREAD

**Issue by mouellet** [Azure/azure-cli#20327]
**Describe the bug**

Since upgrading to v2.30.0, `--output` and `--query` args don't apply anymore.

**To Reproduce**
```shell
$ az extension list-available --query "[?name=='azure-devops'].{Name:name}" --output table
[
  {
    "experimental": true,
    "installed": false,
    "name": "account",
    "preview": false,
    "summary": "Microsoft Azure Command-Line Tools SubscriptionClient Extension",
    "version": "0.2.1"
  },
  {
    "experimental": false,
    "installed": false,
    "name": "acrtransfer",
    "preview": true,
    "summary": "Microsoft Azure Command-Line Tools Acrtransfer Extension",
    "version": "1.0.0"
  },
  ...
]
```

Result is the same when using `--query` or `--output` alone (`az extension list-available --query "[?name=='azure-devops'].{Name:name}"` or `az extension list-available --output table`).

**Expected behavior**
```shell
$ az extension list-available --query "[?name=='azure-devops'].{Name:name}" --output table
Name
------------
azure-devops
```

**Environment summary**
- Install Method: `brew install azure-cli`
- CLI version: 2.30.0
- OS version: macOS Big Sur
- Shell Type: Bash

**Additional context**

`az extension list-available` command is used as an example, but the issue is present on all other commands.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by ToxicWar** [comment]
The same issue in Alpine (Docker image: python:3.9-alpine3.13)

Simple `az account list -o table` shows JSON output instead of table

Environment summary

Install Method: `pip install azure-cli==2.30.0`
CLI version: 2.30.0
OS version: alpine3.13
Shell Type: Bash

**Comment by jiasli** [comment]
This issue is caused by a regression in Python 3.9.8, please see https://github.com/Azure/azure-cli/issues/20269.
