### ISSUE TITLE
Support Az CLI new Databricks preview API version  2021-04-01-preview

### ISSUE THREAD

**Issue by msaranga** [Azure/azure-cli#20321]
**Is your feature request related to a problem? Please describe.**
No. This is new feature ask

**Describe the solution you'd like**
Few Months back, Databricks RP released public preview of API version 2021-04-01-preview. As part of this API, we support customer to create private endpoint on workspace. New Properties like "publicNetworkAccess" and "requiredNsgRules". Above parameters are enum, which decides whether workspaces can be accessed on a public network. 

Also API exposes information related to private endpoints associated to workspace. 

**Describe alternatives you've considered**
 
New Parameters like "publicNetworkAccess" and "requiredNsgRules" will allow to create Private Workspaces. Some of our top customers like UBS, TD Bank are looking for AzCLI support of private endpoint.  

AzCLI : should support creation private endpoints on to workspace and display number of private endpoint connections on a workspace.

Swagger :https://github.com/Azure/azure-rest-api-specs/blob/main/specification/databricks/resource-manager/Microsoft.Databricks/preview/2021-04-01-preview/databricks.json

**Comment by yonzhan** [comment]
network
