### ISSUE TITLE
can't create logic app with standard plan as I can't create the service app plan workflow based.

### ISSUE THREAD

**Issue by dariuszbz** [Azure/azure-cli#20337]
as in description. 

I try to create a logic app standard plan (app service plan for workflow) but there is no option to create an app service plan with workflow.

**Comment by dariuszbz** [comment]
$AppservicePlanSKU = "WS1"

az appservice plan create -n $AppservicePlanName --sku $AppservicePlanSKU --is-linux false

az logicapp create -p $AppservicePlanName -n $LogicAppName -s $StorageAccountName --os-type "Windows"


WS1 plan is not is not supported.

**Comment by yonzhan** [comment]
route to service team

**Comment by archidda** [comment]
@dariuszbz 

1. were you able to create Workflow standard SKU app serivce plan using CLI?
az appservice plan create -n $AppservicePlanName --sku $AppservicePlanSKU --is-linux false

2. Currently, we can't create the app service plan with 'az logicapp create' command. 

If you have created any logicapp from portal, it will create a WS appservice plan for you. You can use that plan from CLI.

**Comment by archidda** [comment]
@dariuszbz 
We are working with Appservice team to add feature to create workflow standard plan from their CLI create command. Workaround I can suggest right now is to create a logicapp in portal and use the plan created by it from CLI.

**Comment by dariuszbz** [comment]
Thank You! 
Any road map on that available?

**Comment by dariuszbz** [comment]
hello ..... any one at home ?

**Comment by archidda** [comment]
Hey @dariuszbz , the tentative ETA is the Jan CLI release

**Comment by dariuszbz** [comment]
thank You!
