### ISSUE TITLE
Setting App/Function AppSettings with Key Vault secret reference - Missing Closing Bracket

### ISSUE THREAD

**Issue by irishtechie** [Azure/azure-cli#20338]
Running Azure CLI version 2.30.0 on PowerShell 7.2.0.

**Command:**
`az functionapp config appsettings set --name $AppName --resource-group $RG --settings "$($setting.Name)=@Microsoft.KeyVault(VaultName=$($vaultName);SecretName=$($setting.Value))"`

When running the above command to create an App Setting with Key Vault secret reference within a Function App, the final parenthesis is left off the setting. This causes the Function App to fail to recognise it as a Key Vault reference.

**See image with missing bracket:**
![image](https://user-images.githubusercontent.com/4664690/141820867-340ee0ee-7dd3-4886-b6a5-77d6f1c5e859.png)

**Please Note:** I attempted the same with the 'az webapp' command and get the same result. If I use the PowerShell Az.Functions cmdlets it works as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f254bb-7dfd-417b-b08d-f2ac34247d99
* Version Independent ID: 9d22f523-579b-ea66-04ed-20f09c72bcbb
* Content: [az functionapp](https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/functionapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/functionapp.yml)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@irishtechie Apologies for the delayed response. The similar issue is discussed [here](https://stackoverflow.com/questions/67654041/issue-with-when-using-azure-cli-to-set-azure-function-app-configurations). I tried to run the below Az CLI command and that worked fine for me. Could you please test the same and let us know if you face any issues?

```
----CLI Command START----
az functionapp config appsettings set --name [my-app-name] --resource-group [my-app-res-group] --settings `""PublicKey=@Microsoft.KeyVault(VaultName=[vault-name];SecretName=[secret-name])"`"
----CLI Command END----

```
Awaiting your reply.

**Comment by navba-MSFT** [comment]
@irishtechie We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by Antebios** [comment]
> @irishtechie Apologies for the delayed response. The similar issue is discussed [here](https://stackoverflow.com/questions/67654041/issue-with-when-using-azure-cli-to-set-azure-function-app-configurations). I tried to run the below Az CLI command and that worked fine for me. Could you please test the same and let us know if you face any issues?
> 
> ```
> ----CLI Command START----
> az functionapp config appsettings set --name [my-app-name] --resource-group [my-app-res-group] --settings `""PublicKey=@Microsoft.KeyVault(VaultName=[vault-name];SecretName=[secret-name])"`"
> ----CLI Command END----
> ```
> 
> Awaiting your reply.

I don't know about OP, but it worked for me!!!

**Comment by vienleidl** [comment]
The following code snippet 💯 worked for me when applying an Azure Key Vault reference in PowerShell — escaping the full app setting value using backticks **inside double quotes**:

>     $kvRef = "@Microsoft.KeyVault(VaultName=$KeyVaultName;SecretName=$SecretName)"
>     $escapedSetting = "$AppSettingKeyName=`"$kvRef`""
> 
>     Write-Host "`n⚙  Adding app setting '$AppSettingKeyName' with Key Vault reference..." -ForegroundColor Cyan
> 
>     az webapp config appsettings set `
>         --name $AppServiceName `
>         --resource-group $ResourceGroup `
>         --settings $escapedSetting `
>         | Out-Null
>
