### ISSUE TITLE
[ExpressRoute Direct] Add Non-XPN Ciphers and SCI Support for MACsec configuration

### ISSUE THREAD

**Issue by mialdrid** [Azure/azure-cli#20339]
**Resource Provider**

Microsoft.Network
**Description of Feature or Work Requested**
Customers can configure MACsec encryption with ExpressRoute. We now allow customers to use Non-XPN ciphers and enable/disable a setting called SCI (Secure Channel Identifier). 

- [How to document](https://docs.microsoft.com/en-us/azure/expressroute/expressroute-howto-macsec)
- [ExpressRoute encryption](https://docs.microsoft.com/en-us/azure/expressroute/expressroute-about-encryption)

**Minimum API Version Required**

 api-version=2021-05-01
**Swagger Link**

- [ExpressRoute Direct Swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2021-05-01/expressRoutePort.json)

**Target Date**

End of Calendar year 2021.

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Hi @mialdrid, could you describe more about the feature request? I think the `sciState` and `cipher` has already been supported in this PR #18814 
![image](https://user-images.githubusercontent.com/69238381/146863705-3df64df2-f92d-43ff-b89e-58e9d637ac65.png)
