### ISSUE TITLE
Multiple Accounts with same username.

### ISSUE THREAD

**Issue by DaleNicholsSTG** [Azure/azure-cli#20342]
I'm doing the exercises for:
    https://docs.microsoft.com/en-us/learn/modules/create-azure-resource-manager-template-vs-code/3-exercise-create-and-deploy-template?pivots=cli

When I issued the command:
     az deployment group create --name $DeploymentName --template-file $templateFile
I got the error:
    Found multiple accounts with the same username. Please report to us via Github: https://github.com/Azure/azure-cli/issues/new

Changing the deployment name does not change the error message.  I suspect this means that the deployment name is fine and not the source of the error.

Changing the template name to one that doesn't exist returns '[Errno 2] No such file or directory'.  I suspect this means that whatever the original error is, it occurs after opening (and perhaps validating) the template file.

I'm logged into Azure with a 'Concierge Subscription'.  The template file is just the empty one ($schema and contentVersion have data, everything else is empty) for the start of that exercise.

I have no idea what it means by 'account'.  Account on what system?  I logged into Azure successfully.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by DaleNicholsSTG** [comment]
I'm not sure how, but I got past this problem.  But later, the subscription and/or resource group for the 'Microsoft Learn Sandbox' tenant disappeared.  I was going through that same exercise.  For one command it worked, for the next I got {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'learn-c3d5f225-87d2-4b53-b0a1-9b8bbfda1a76' could not be found."}}.

The original error says that the resource group is missing, but when I logged in again (az login), it says I don't have a subscription.  Az account list still shows the 'Concierge Subscription' with a subscription id, but the az commands still report errors, and the portal says I do not have a subscription, even though I'm connected to the 'Concierge Subscription' directory.  (This is confusing.  Is 'Concierge Subscription' a tenant [what the az login command calls it], a directory [what the portal calls it], or a subscription [the noun of its name]?)

I still have an hour left on my sandbox.  I'm hoping once that expires, I can create a new one that works.

**Comment by jiasli** [comment]
For `Multiple Accounts with same username` issue, please see https://github.com/Azure/azure-cli/issues/20168#issuecomment-963747032 for the solution. We are still investigating the scenario. 

In order to do experiment, you have to have a valid Azure Subscription. For difference between Subscription and Directory/Tenant, you may see https://techcommunity.microsoft.com/t5/azure/understanding-azure-account-subscription-and-directory/m-p/34800.

**Comment by DaleNicholsSTG** [comment]
I've had similar problems 4 times now.  It appears that resource groups in Azure disappear at random.  Items in those groups still exist, but you can't access them.

My guess is that one of:
    The resource doesn't actually get committed to some database (i.e., it is inserted into a database, but the response is send before the commit [which fails]).
    Other people have access to the resources I created, and someone is deleting stuff to be a jerk.  This could be someone at Microsoft (which I assume has access, since they own the servers) or it could be someone that got access through a backdoor.

Either way, I wouldn't want to use this technology for a production system.

**Comment by jiasli** [comment]
> It appears that resource groups in Azure disappear at random. Items in those groups still exist, but you can't access them.

If you are seeing any problem with Azure resources, you may create a support ticket: https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
