### ISSUE TITLE
Unrecognized arguments: -l australiaeast

### ISSUE THREAD

**Issue by ngoc7sao9** [Azure/azure-cli#20341]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Please provide the detailed command and error info

**Comment by RakeshMohanMSFT** [comment]
@ngoc7sao9 Since we need no further update from you, we are closing this issue
