### ISSUE TITLE
Missing Add-AzureADServicePrincipalPolicy equivalent for the Azure CLI?

### ISSUE THREAD

**Issue by archubbuck** [Azure/azure-cli#20340]
I need to associate a custom claims mapping policy with an application and am not seeing an equivalent to PowerShell's **Add-AzureADServicePrincipalPolicy** in the documentation. Am I missing it?

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
`Add-AzureADServicePrincipalPolicy` is from [AzureAD](https://docs.microsoft.com/en-us/powershell/module/azuread/?view=azureadps-2.0) PowerShell module calling Azure Active Graph API. 

`az ad` command module from Azure CLI is _not_ designed to cover all Azure Active Graph APIs - it is only designed to facilitate the usage of Azure Resource Manager.

You may use `az rest` to directly invoke Microsoft Graph follow examples provided by https://github.com/Azure/azure-cli/issues/12946.

**Comment by archubbuck** [comment]
@jiasli, I haven't been able to find any information identifying which endpoint `Add-AzureADServicePrincipalPolicy` is calling. Am I looking in all the wrong places?
