### ISSUE TITLE
Error building ARM Config: Error populating Client ID from the Azure CLI: No Authorization Tokens were found - please ensure the Azure CLI is installed and then log-in with `az login`.

### ISSUE THREAD

**Issue by roosterhr** [Azure/azure-cli#20356]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Terraform init fails with the error "Error building ARM Config: Error populating Client ID from the Azure CLI: No Authorization Tokens were found - please ensure the Azure CLI is installed and then log-in with `az login`." Even though az login is successful and able to execute az commands. Same code worked fine couple of weeks back.

**To Reproduce**

1. create service principle app.
2. Update azure.yml with azure and app details.
3. Run terraform init
**Expected behavior**

The run should be successful and the resources should get created after terraform apply
**Environment summary**

Terraform : 0.12.28
Azure cli : 2.29.1
**Additional context**

Same code worked fine couple of weeks back. No new changes done.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Were you able to run `az account get-access-token`?

**Comment by AndersRunningen** [comment]
@roosterhr Had the same issue in my Terraform setup, but when using the Azurerm provider version 2.26.0. When upgrading to the latest Azurerm provider 2.85.0 the issue went away and I were able to run terraform init/plan/apply again 🤔 Maybe it could help you as well 🤷‍♂️

**Comment by jiasli** [comment]
It may be possible that Azurerm provider version 2.26.0 directly reads from `~/.azure/accessToken.json` which has been droped during MSAL migration: https://docs.microsoft.com/en-us/cli/azure/msal-based-azure-cli

**Comment by sshantel** [comment]
@jiasli Correct, the MS docs specifically mention it is not backwards compatible. If you do end up with that version,  you can run the following two commands to downgrade to 2.29.2.
```
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/7607de411f8ac0ad926ff2caadf8a9abf713cec8/Formula/azure-cli.rb
```
```
brew install --formula azure-cli.rb
```
(Source: https://twitter.com/neumanndaniel/status/1458558376900694021)

**Comment by jiasli** [comment]
The correct course is to update to the latest Terraform Azurerm provider, which internally subprocesses `az account get-access-token`.
