### ISSUE TITLE
webapp:az webapp auth update v2 - cannot set authentication settings RedirectTo

### ISSUE THREAD

**Issue by LotteVoorhorst** [Azure/azure-cli#20359]
**Describe the bug**
When wanting to enable authentication on a webapp, it is not possible to select an "Identity Provider" by using the az cli. 

![image](https://user-images.githubusercontent.com/77776940/141958551-0d7b8f2d-26b4-425e-94f8-0a28b3f9b4db.png)

**To Reproduce**
Step 1: 
Run ` az webapp auth microsoft update --resource-group '{resourcegroup}' --name {AppServiceName} --client-id {client-id} --client-secret {client-secret} --issuer {issuer} --yes` 

This adds the Identity provider "Microsoft". At this point, the Authentication settings are not set. 

Step 2: 
Run `az webapp auth update --resource-group '{resourcegroup}' --name {AppServiceName } --enabled true --action RedirectToLoginPage` 

This enables the authentication setting and sets everything except for the "Redirect to", see the screenshot. 

**Expected behavior**
The ability to set the auth settings for v2 correctly by using the az cli. 

**Additional context**
When using the authv2 extension, the documentation is not up to date. I added another issue for this, [20358](https://github.com/Azure/azure-cli/issues/20358) .

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
@mkarmark please take a look at the feedback on V2 extension. Thanks!

**Comment by panchagnula** [comment]
@Hamster-Huey FYI

**Comment by Hamster-Huey** [comment]
Hi @LotteVoorhorst ,

I can see your problem with the cli was solved in the linked issue, I'll comment here for clarity. 

The ability to set "RedirectTo" as per the portal is with the command 
`az webapp auth update --name {name} --resource-group {resource-group} --redirect-provider {provider}`
