### ISSUE TITLE
WebApp:az webapp auth update v2 - documentation not updated

### ISSUE THREAD

**Issue by LotteVoorhorst** [Azure/azure-cli#20358]
## Describe the bug

Cannot find the updated documentation for `az webapp auth update` for v2 , see https://docs.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest#az_webapp_auth_update 

The  command below is an example, but several settings I am not able to use anymore.

**Command Name**
`az webapp auth update`

**Errors:**
```
az webapp auth update: 'LoginWithAzureActiveDirectory' is not a valid value for '--unauthenticated-client-action'. Allowed values: RedirectToLoginPage, AllowAnonymous, RejectWith401, RejectWith404.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp auth update --resource-group {} --name {} --enabled {} --action LoginWithAzureActiveDirectory`

## Expected Behavior

Updated documentation or a referral to where I can find the correct information. 

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.29.0 *

Extensions:
account 0.2.1
application-insights 0.1.14
authV2 0.1.1
azure-devops 0.20.0
log-analytics-solution 0.1.1
scheduled-query 0.4.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
Thanks for your feedback. We will check and update as required.

**Comment by shobhitvaish** [comment]
@LotteVoorhorst Please use this command to set the correct 'Redirect To': `az webapp auth update --name {name} --resource-group {group} --redirect-provider AzureActiveDirectory`

**Comment by LotteVoorhorst** [comment]
@shobhitvaish  Thanks for the correct command! That seems to do the trick!

**Comment by DrReedo** [comment]
Can the documentation be updated for v2 please as we are having the same issue?

**Comment by panchagnula** [comment]
@mkarmark please update the help on v2? Thanks!

**Comment by panchagnula** [comment]
@Hamster-Huey FYI

**Comment by Hamster-Huey** [comment]
We are aware of the documentation issue, it looks to be a merge collision between commands shared between the core az cli and the authV2 extension. We're currently evaluating options to improve the docs, but for now I would suggest using the cli's --help functionality. 
`az webapp auth update --help`
