### ISSUE TITLE
SAS token for Blob Index Tags

### ISSUE THREAD

**Issue by Tbohunek** [Azure/azure-cli#20368]
**Is your feature request related to a problem? Please describe.**

Azure CLI doesn't support [Blob Index Tags](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs?tabs=azure-portal#account-sas) permissions `t f x`. It throws validation error.

```azcli
az storage account generate-sas --account-key xxx --account-name myaccount --expiry 2020-01-01 --https-only --permissions rwdlactfx --resource-types cos --services b

valid values are (a)dd (c)reate (d)elete (l)ist (p)rocess (r)ead (u)pdate (w)rite (a)dd (c)reate (d)elete (l)ist (p)rocess (r)ead (u)pdate (w)rite or a combination thereof
```

**Describe the solution you'd like**

Add `t` `f` and `x` to acceptable values for `--permissions`.

**Describe alternatives you've considered**

**Additional context**

Works with `PowerShell` and is [well documented with `REST`](https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas?redirectedfrom=MSDN#specifying-account-sas-parameters).
```PowerShell
$storage = Get-AzStorageAccount -Name myaccount -ResourceGroupName mygroup
New-AzStorageAccountSASToken -Service Blob -ResourceType Service,Container,Object -Permission rwdlactfx -Protocol HttpsOnly -StartTime (Get-Date) -ExpiryTime (Get-Date).AddDays(1) -Context $storage.context
```

**Comment by yonzhan** [comment]
storage

**Comment by Tbohunek** [comment]
Note: this is kind of a bug as it is lack of support of an Azure feature which should have been supported since day one.
@yonzhan Given the apparent simplicity of the solution I believe it should be addressed sooner. Is that possible?

**Comment by jiasli** [comment]
Looks like Azure Portal haven't supported `t`, `f`, `x` either:

![image](https://user-images.githubusercontent.com/4003950/142563518-16fdfba3-77bc-4980-ae89-bb43add1465c.png)

Azure Storage Explorer only supports `t`, `x`:

![image](https://user-images.githubusercontent.com/4003950/142573317-9024ef44-3f68-4f4e-bae0-f0b421e5c9ae.png)

> this is kind of a bug as it is lack of support of an Azure feature which should have been supported since day one.

I agree. Per https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#permissions-for-a-directory-container-or-blob, `t`, `f` and `x` are just literal characters SDK should be able to bypass the validation.

I wrote a simple script to help generate the SAS token with `t`, `f`, `x` permissions:

```py
import requests
from azure.storage.common._common_conversion import _sign_string
from azure.storage.common._serialization import url_quote

# string_to_sign is constructed following
# https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#constructing-the-signature-string

key = 'kyZcwi...'
query = ('sp=racwdxltf&'  # signedPermissions
         'st=2021-11-19T00%3A00%3A00Z&'  # signedStart
         'se=2021-12-01T00%3A00%3A00Z&'  # signedExpiry
         'sv=2020-12-06&'  # signedVersion
         'sr=c'  # signedResource
         )
string_to_sign = ('racwdxltf\n'  # signedPermissions
                  '2021-11-19T00:00:00Z\n'  # signedStart
                  '2021-12-01T00:00:00Z\n'  # signedExpiry
                  '/blob/jlst1007/con1\n'  # canonicalizedResource
                  '\n'  # signedIdentifier
                  '\n'  # signedIP
                  '\n'  # signedProtocol
                  '2020-12-06\n'  # signedVersion
                  'c\n'  # signedResource
                  '\n'  # signedSnapshotTime
                  '\n'  # signedEncryptionScope
                  '\n'  # rscc
                  '\n'  # rscd
                  '\n'  # rsce
                  '\n'  # rscl
                  )
sig = url_quote(_sign_string(key, string_to_sign))
sas = f"{query}&sig={sig}"
print(sas)
r = requests.get(f'https://myst.blob.core.windows.net/con1/test.txt?comp=tags&{sas}')
print(f"{r.text}")
```

**Comment by Tbohunek** [comment]
@jiasli Interesting. Portal supports it on Storage account level though.

![image](https://user-images.githubusercontent.com/16520646/142577624-a9136bd5-aba5-4bdd-b523-5a6e602dbc14.png)

**Comment by jiasli** [comment]
@Tbohunek I also noticed that! 😃 It's just generating container SAS doesn't support those.

**Comment by pdebruin** [comment]
Why has this been added to a milestone and removed multiple times?

**Comment by evelyn-ys** [comment]
This is blocked by Python SDK gap between track1 and track2. We will add support as soon as Python SDK fix
