### ISSUE TITLE
Not able to access AZ sandbox: Found multiple accounts with the same username

### ISSUE THREAD

**Issue by mohit-gitlearn** [Azure/azure-cli#20364]
I am getting this error while accessing the sandbox during Azure self learning training.

"Found multiple accounts with the same username"

Please fix this.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/20168#issuecomment-963747032 for the solution. We are still investigating the scenario.
