### ISSUE TITLE
Code change in monitor module to support event hub in Azure CLI

### ISSUE THREAD

**Issue by Gykyoo** [Azure/azure-cli#20371]
**Resource Provider**

Microsoft.Insights

**Description of Feature or Work Requested**

**1. Add event hub receivers** 
        **EventHub required fields:**
            Format:     --action eventhub NAME SUBSCRIPTION_ID EVENTHUBNAMESPACE EVENTHUBNAME [usecommonalertschema]
            Example:    --action eventhub eventhub1 5def922a-3ed4-49c1-b9fd-05ec533819a3 eventhub1NameSpace1 testEventHubName1 usecommonalertschema
        **EventHub required syntax:**
        'eventhub': 'NAME SUBSCRIPTION_ID EVENTHUBNAMESPACE EVENTHUBNAME [usecommonalertschema]'
  
**2. Update related tests**
Test cases:
1.  Test command line without usecommonalertschema field
2.  Test command line with usecommonalertschema field
3.  Test command line with some other missing fields

**Minimum API Version Required**

2021-09-01

**Swagger Link**

Created new API version for Monitor Action Groups by ritwik8119 · Pull Request #16107 · Azure/azure-rest-api-specs (github.com) 
Files changed: https://github.com/Azure/azure-rest-api-specs/pull/16107/files

**Target Date**

2021-12-29

**Comment by yonzhan** [comment]
monitor
