### ISSUE TITLE
az upgrade Python error

### ISSUE THREAD

**Issue by ShaunDayaram** [Azure/azure-cli#20379]
I get the follow issue after I upgraded my az. Any az command I write displays this message.

az -h
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 14, in <module>
ImportError: bad magic number in 'azure.cli.core': b'3\r\r\n'

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Found this post: https://stackoverflow.com/questions/514371/whats-the-bad-magic-number-error

Could you try to reinstall Azure CLI follow https://github.com/Azure/azure-cli/issues/18477#issuecomment-861108175?

**Comment by ShaunDayaram** [comment]
@jiasli Thanks the Uninstall, then reinstall worked. If the upgrade gives me an issue I will uninstall, then reinstall.

**Comment by jiasli** [comment]
It looks like some problem with Windows MSI. Re-installing can usually solve the problem.
