### ISSUE TITLE
OperationalInsights: add support for cluster create as long running operation

### ISSUE THREAD

**Issue by dabenhamMic** [Azure/azure-cli#20382]
**Resource Provider**
OperationalInsights

**Description of Feature or Work Requested**
Add support for cluster update as long-running operation 

**Minimum API Version Required**

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/16690
**Python link**
https://pypi.org/project/azure-mgmt-loganalytics/12.0.0/

**Target Date**

**Comment by yonzhan** [comment]
monitor
