### ISSUE TITLE
Error on az login: Found multiple accounts with the same username

### ISSUE THREAD

**Issue by fbsanches** [Azure/azure-cli#20384]
Trying to login with fernandoarce@grpereira.com.br
$ az login
WARNING: The default web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
ERROR: Found multiple accounts with the same username. Please report to us via Github: https://github.com/Azure/azure-cli/issues/new

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/20168#issuecomment-963747032 for the solution. We are still investigating the scenario.

**Comment by fbsanches** [comment]
thanks, it worked for me
