### ISSUE TITLE
FunctionaApp:az functionapp cors show does not work with deployment slots

### ISSUE THREAD

**Issue by JacobStruiksma** [Azure/azure-cli#20385]
## Describe the bug
When getting the CORS settings of a functionapp deployment slot, you get the settings of the functionapp itself. it does not give the right information and it does not give an error.
**Command Name**
`az functionapp cors show`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- get the ids of a function app deployment slot slot, something like: 
/subscriptions/{guid{/resourceGroups/{resource_group_name}/providers/Microsoft.Web/sites/{functionapp name}/slots/{slot name}

- `az functionapp cors show --ids {}`

## Expected Behavior
Show the cors settings of the slot, not of the main function app

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0

Extensions:
azure-devops 0.18.0
log-analytics 0.2.2
portal 0.1.2

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
Able to repro the issue. We will triage for fixing in coming releases.

**Comment by Kotasudhakarreddy** [comment]
`--ids` argument will work only for the functionapp. to work with slots we must pass `--slot` argument. This is the common behavior across all the `cli`  commands.

**Comment by Kotasudhakarreddy** [comment]
Closing this as this is an expected behavior from CLI.
