### ISSUE TITLE
Command "az network application-gateway http-listener update" doesn't work with parameter "--ssl-profile"

### ISSUE THREAD

**Issue by phibao37** [Azure/azure-cli#20395]
## Describe the bug

**Command Name**
`az network application-gateway http-listener update`

**Errors:**
```
usage error: --ssl-profile [KEY=VALUE ...]

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

I tried some command as below:
- `SSL_PROFILE_ID=/subscriptions/***********/resourceGroups/***********/providers/Microsoft.Network/applicationGateways/***********ApplicationGateway/sslProfiles/***********`
- Command 1: `az network application-gateway http-listener update --gateway-name {} -g {} -n {} --ssl-profile $SSL_PROFILE_ID --only-show-errors`
- Command 2: `az network application-gateway http-listener update --gateway-name {} -g {} -n {} --ssl-profile name=my_client_profile --only-show-errors`

## Expected Behavior
Either Command 1 or Command 2 should succeed to update the SSL profile for the existing HTTP listener.
However, error occurred on both commands:

Command 1: `ERROR: usage error: --ssl-profile [KEY=VALUE ...]`
Command 2: <pre>
ERROR: (InvalidRequestFormat) Cannot parse the request.
Code: InvalidRequestFormat
Message: Cannot parse the request.
Exception Details:      (SubscriptionsPrefixMissingInJsonReferenceId) Value of id property has to start with '/subscriptions/'. Provided value doesn't: [{'name': 'my_client_profile'}]. Path properties.httpListeners[0].properties.sslProfile.
        Code: SubscriptionsPrefixMissingInJsonReferenceId
        Message: Value of id property has to start with '/subscriptions/'. Provided value doesn't: [{'name': 'my_client_profile'}]. Path properties.httpListeners[0].properties.sslProfile
</pre>

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
network

**Comment by aferland1** [comment]
Is there any workaround with version 2.30.0?

**Comment by kairu-ms** [comment]
Hi @aferland1, you can use `--set` to update property directly.
