### ISSUE TITLE
webapp:az webapp list-runtimes doesn't provide the most up to date information

### ISSUE THREAD

**Issue by nulltoken** [Azure/azure-cli#20392]
Running this today (2021-17-11) returns

```
az webapp list-runtimes --linux
[
  "DOTNETCORE|2.1",
  "DOTNETCORE|3.1",
  "DOTNET|5.0",
  "NODE|14-lts",
  "NODE|12-lts",
  "NODE|10-lts",
  "NODE|10.1",
  "NODE|10.6",
  "NODE|10.14",
  "JAVA|8-jre8",
  "JAVA|11-java11",
  "TOMCAT|8.5-jre8",
  "TOMCAT|9.0-jre8",
  "TOMCAT|8.5-java11",
  "TOMCAT|9.0-java11",
  "JBOSSEAP|7.2-java8",
  "PHP|7.2",
  "PHP|7.3",
  "PHP|7.4",
  "PYTHON|3.8",
  "PYTHON|3.7",
  "PYTHON|3.6",
  "RUBY|2.5",
  "RUBY|2.6"
]
```

Nothing is displayed related to .NET 6.
Although 
  - it's GA.
  - tweaking the Portal UI and exporting the settings as an ARM template shows that "DOTNETCORE|6.0" is a supported value.

Where can one go to find the list of up-to-date supported values?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by seligj95** [comment]
@nulltoken - Thank you for bringing this to our attention. We are getting this updated.

**Comment by nulltoken** [comment]
> @nulltoken - Thank you for bringing this to our attention. We are getting this updated.

@seligj95 Thanks for your answer. However this doesn't cover the part *"Where can one go to find the list of up-to-date supported values?"* of the initial issue?

Applying reverse-engineering practices to find the magic values to properly configure your deployment isn't the sweetest experience.

**Comment by seligj95** [comment]
@nulltoken - Apologies for the confusion. Currently the CLI command runs off a list of hardcoded values while the portal uses an API to get the available runtimes so the portal is the current "source of truth". We are working on getting the list-runtimes command to use that same API so there is parity. This update should roll out with the next CLI release which is scheduled for the first week of December.

**Comment by seligj95** [comment]
@nulltoken - which version of the CLI are you using? The latest version (2.30.0) has already been updated and includes .net 6. Please let me know if there is an issue otherwise we can close this.

**Comment by nulltoken** [comment]
@seligj95 I don't know (at this moment) the version of the CLI. Will get back to you tomorrow about that.

However, what you're writing seems to infer that the list of runtimes is hardcoded in the CLI source code/resources. Would that be the case could you please point me to the github file containing this up-to-date runtime list?

>Please let me know if there is an issue otherwise we can close this.

I don't think closing this will resolve the underlying issue. There's still nothing helping the user, at any random moment, point to the latest up-to-date available runtimes.

The doc states 

![image](https://user-images.githubusercontent.com/92363/142489111-8603e718-2fa5-4be7-98ce-49d52ff38cc5.png)

Nowhere is mentioned "for this to work, you have to run against the latest version of the CLI otherwise you'll only see outdated information".

Sorry for being dense but it looks to me there's a real usability issue here that's not dealt with.

**Comment by seligj95** [comment]
Once the command uses the API rather than the hard-coded list (https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/resources/WebappRuntimeStacks.json) which we try to avoid for our commands for obvious reasons, I think that will solve the usability issue, assuming users update to the latest version of the CLI which they should be prompted to do when a new version is released. 

> Nowhere is mentioned "for this to work, you have to run against the latest version of the CLI otherwise you'll only see outdated information".

Agreed that this would have been good to add for the current cli, but we are expecting the next release to use the API. Help text updates go out at the same time as CLI releases so it shouldn't be necessary moving forward as I can't make a change to a previous version. If for some reason we can't get the API out with the next release, that help text will be included.

**Comment by nulltoken** [comment]
@seligj95 Thanks for the pointer to the hard coded list!

> we are expecting the next release to use the API

Could you please point me to this API endpoint? I'm unable to find anything relevant (https://docs.microsoft.com/en-us/rest/api/?term=runtime%20versions) about that

**Comment by seligj95** [comment]
GET https://management.azure.com/providers/Microsoft.Web/webAppStacks?api-version=2020-10-01

for Linux only:
GET https://management.azure.com/providers/Microsoft.Web/webAppStacks?stackOsType=linux&api-version=2020-10-01 

Reference:
https://docs.microsoft.com/en-us/rest/api/appservice/provider/get-web-app-stacks

**Comment by nulltoken** [comment]
@seligj95 Thanks! 

I've got provided with all the answers I needed.

Good to be closed.
