### ISSUE TITLE
`az ml batch-endpoint invoke` returns a invalid 'scope'

### ISSUE THREAD

**Issue by marcopinheiro** [Azure/azure-cli#20397]
I receive a problem when use `az ml batch-endpoint invoke -n my-deployment --input-dataset azureml:inference_points:4 --resource-group my-resource-group --workspace my-workspace`.

`my-workspace`, `my-resource-group` and `my-deployment` exists.

AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://ml.azure.com offline_access openid profile is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>.
Trace ID: 15115095-dcbd-4629-873c-0ce8a4ed1f00
Correlation ID: f4e74338-264c-40ef-8ea7-72befc9f020e
Timestamp: 2021-11-17 18:08:10Z

Might this be a invalid scope created internally by module ml?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6818cd91-604d-d963-7510-acdb495d87e8
* Version Independent ID: 5f85a963-4a23-ac2c-d6ec-668bbd7766e4
* Content: [az ml dataset](https://docs.microsoft.com/en-us/cli/azure/ml/dataset?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/dataset.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/dataset.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by singankit** [comment]
@marcopinheiro Thanks for reaching out. This is a known issue due to latest cli (>=2.30) moving to use msal for authentication. Fix is in progress, a release is planned by EOW and will contain the fix for this issue.
