### ISSUE TITLE
Support swapping Website Deployment Slots

### ISSUE THREAD

**Issue by KirillOsenkov** [Azure/azure-cli#2039]
Azure CLI used to have `azure site swap -q` but it seems unsupported or only available in ARM mode?

This is a very confusing customer experience. As an Azure customer I'd like a simple and discoverable way to automate swapping deployment slots through a simple CLI.

`azure site swap` doesn't work for me because it has a bug where it loses my credentials even if I have exported the credentials file. It keeps saying I should login again, and that is not acceptable for a nightly cron job.

**Comment by yugangw-msft** [comment]
Please try `az appservice web deployment slot swap`
