### ISSUE TITLE
Service principal context left in inconsistent state after `az account list --refresh`

### ISSUE THREAD

**Issue by jackhorton** [Azure/azure-cli#20402]
Repro steps:

```sh
# use a clean configuration directory
export AZURE_CONFIG_DIR="$(pwd)/foo"

az login --service-principal --username ...

# at this point, everything should work; for instance, az keyvault list should return whatever keyvaults your service principal can read
az keyvault list

# refreshing the account list leaves the account configuration in an inconsistent state.
az account list --refresh

# this command fails and prints "Could not retrieve credential from local cache for service principal None. Run `az login` for this service principal."
az keyvault list

# if you look in $AZURE_CONFIG_DIR/azureProfile.json, you will see that the "user" field of every subscription object is null now
```

It seems like a regression in 2.30.0, likely due to #19707

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Please clear Azure CLI's login context and start from scratch:

```
az account clear
az login
```

**Comment by jackhorton** [comment]
Yes, that is the workaround. However, this functionality worked as of 2.29.

**Comment by jiasli** [comment]
I see. I can reproduce this issue. Actually `az account list --refresh` is always problematic, even in ADAL-based Azure CLI. We are considering to deprecate `--refresh` (#20429). 

Anyway, let me fix this issue for now.

**Comment by jackhorton** [comment]
Thank you for the quick fix! We will investigate whether we still need this functionality at all and if so, switch to `az account clear; az login`
