### ISSUE TITLE
AttributeError: 'ComputeManagementClientConfiguration' object has no attribute 'accept_language'

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-cli#2041]
Environment:
 * Ubuntu 16.04
 * Python 3.5.2
 * azure-cli 0.1.1b3

## Reproduce

 1. I logged in as an SPN, configured with the Reader role.
 1. I executed the command 'az vm extension image list -p Microsoft.OSTCExtensions -o table'

I logged out the SPN, and I logged back in under my normal account and it still failed.

## azure-cli

```text
chrboum@chrboum00:~$ az --version
azure-cli (0.1.1b3)

acr (0.1.1b2)
acs (0.1.1b3)
appservice (0.1.1b2)
cloud (0.1.1b2)
component (0.1.0rc2)
configure (0.1.1b3)
container (0.1.1b2)
context (0.1.1b2)
core (0.1.1b3)
feedback (0.1.1b2)
network (0.1.1b2)
nspkg (0.1.2)
profile (0.1.1b2)
resource (0.1.1b2)
role (0.1.1b2)
storage (0.1.1b2)
vm (0.1.1b3)

Python (Linux) 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]
```

## stacktrace
```text
'ComputeManagementClientConfiguration' object has no attribute 'accept_language'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/commands/__init__.py", line 333, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/command_modules/vm/custom.py", line 230, in list_vm_extension_images
    publisher_name, name, version, image_location, latest)
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/command_modules/vm/_actions.py", line 130, in load_extension_images_thru_services
    publishers = client.virtual_machine_images.list_publishers(location)
  File "/usr/local/lib/python3.5/dist-packages/azure/mgmt/compute/operations/virtual_machine_images_operations.py", line 290, in list_publishers
    if self.config.accept_language is not None:
AttributeError: 'ComputeManagementClientConfiguration' object has no attribute 'accept_language'
```

**Comment by yugangw-msft** [comment]
//cc @derekbekoe, @johanste @tjprescott, @troydai 
This issue has nothing to do with compute command, rather msrestazure introduced a breaking change so recent client should enforce `msrestazure>=0.4.7`. See [ChangeLog](https://github.com/Azure/msrestazure-for-python/blob/master/README.rst#2016-01-23-version-047)

We need to sort this out by next week's release, and have a receipt ready to deal with such situation moving forward.

**Comment by derekbekoe** [comment]
In azure-cli-core, we have `'msrestazure>=0.4.0'`. Of course pip should use the version requirement defined in the SDK as that is stricter than this but it does not.
https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/setup.py#L57
It may be sufficient to update the dependency version in azure-cli-core.

**Comment by yugangw-msft** [comment]
//CC: @lmazuel 
> It may be sufficient to update the dependency version in azure-cli-core.

Make sure on the same page, so when autorest runtime has change happened (even it is compatible)
1. All sdk libs should be re-generated, and published
2. Cli will first update top dependencies at azure-cli-core and publish all command modules 

W/o doing these, any cli command module might fail to load if it starts to use newly generated sdk lib which depends on the new runtime change?

**Comment by johanste** [comment]
@boumenot, out of curiosity, how did you install the CLI? If you used az component update, then this shouldn't have happened, nor if you used the script. In other words, am I correct in assuming that you installed using pip?

**Comment by boumenot** [comment]
Correct, I installed using pip.

**Comment by lmazuel** [comment]
@yugangw-msft 
1. I see no reason to regenerate all SDKs client if the changes are backward compatible. This is related to the removal in `__init__` of timeout, accept_language, etc. Technically, it's an msrestazure issue that was hidden (like the timeout parameter was not working).
2. You should depend on msrestazure 0.4.7 which works with all SDKs

**Comment by yugangw-msft** [comment]
@lmazuel
any proposal will work for me, as long as when the change happens, cli can efficiently coordinate so there is zero breaking at users' side.
