### ISSUE TITLE
Documentation should say "Cluster ARM ID of the Namespace." rather than "Luster ARM ID of the Namespace."

### ISSUE THREAD

**Issue by gabriel-kohen-by** [Azure/azure-cli#20416]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2a1ce05-6574-eaa1-cde9-640de52af451
* Version Independent ID: 4dc152fd-ca4f-6dca-9f63-b1ca2f90e2e9
* Content: [az eventhubs namespace](https://docs.microsoft.com/en-us/cli/azure/eventhubs/namespace?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/eventhubs/namespace.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/eventhubs/namespace.yml)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@gabriel-kohen-by Apologies for the late reply. Thanks for sharing the feedback. A PR Azure/azure-cli#21460 has been filed to address this issue. It is being reviewed now. In the meantime, if you have any questions, please feel free to ask. Awaiting your reply.
