### ISSUE TITLE
--web only works from local CLI?

### ISSUE THREAD

**Issue by madiepev** [Azure/azure-cli#20412]
It seems that --web only works if you use CLI from a local machine.
It doesn't work if you submit a job from the Azure Cloud Shell. If this is true, could this be added to the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636db626-82b8-8d7f-b284-41f6ecffa93b
* Version Independent ID: 62b5f487-5b77-6eb6-499f-2bcf1e95d6ff
* Content: [az ml job](https://docs.microsoft.com/en-us/cli/azure/ml/job?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/job.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/ml/job.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by paulshealy1** [comment]
Thanks for the feedback! We'll update the docs and add a warning.
