### ISSUE TITLE
Azure-cli request for a Subscription API new version

### ISSUE THREAD

**Issue by Ochirkhuyag** [Azure/azure-cli#20420]
**Resource Provider**
Microsoft.Subscription

**Description of Feature or Work Requested**
We have released GA version for Microsoft.Subscription APIs and would like to AzureCLI to refer to latest apiVersion.

**Minimum API Version Required**
2021-10-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/subscription/resource-manager/Microsoft.Subscription/stable/2021-10-01/subscriptions.json

**Target Date**
12/10

**Comment by yonzhan** [comment]
subscription

**Comment by PARADISSEEKR** [comment]
Hi, @Ochirkhuyag , The `2021-10-01` api version of subscription is not included in the latest [SDK](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions), please release a new version python SDK for CLI to support it.

**Comment by zhoxing-ms** [comment]
@Ochirkhuyag Hi, please note that the `SubscriptionClient` used by official CLI is in `azure.mgmt.resource` instead of `azure.mgmt.subscription`, it requests ARM REST （such as `/providers/Microsoft.Resources/checkResourceName` and `/subscriptions/xxx`) , not `Microsoft.Subscription` RP.
At present, only two CLI extensions `az account`, `az subscription` are requested `Microsoft.Subscription` RP APIs. So do we need to upgrade the api-version for these two extensions?

**Comment by sriramvu** [comment]
Hi @zhoxing-ms, we are requesting for CLI extensions that refer / use Microsoft.Subscription RP APIs. If 'Official CLI' is different one which does not refer to Subscription RP APIs, we are good not to upgrade that.

Corresponding CLI commands from public doc like: 
https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest
https://docs.microsoft.com/en-us/cli/azure/account/subscription?view=azure-cli-latest

Found one of azure-cli issues (in case for reference): https://github.com/Azure/azure-cli/issues/15436

**Comment by PARADISSEEKR** [comment]
Hi @Ochirkhuyag @sriramvu  `SubscriptionOperations.create_subscription_in_enrollment_account `[(link)](https://github.com/Azure/azure-cli-extensions/blob/ddba03626f75e10984652bf74235bb3cd5c4c894/src/subscription/azext_subscription/subscription/operations/subscription_factory_operations.py#L93-L95) is used in `az account create`, but it has been removed in the new [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/subscription/resource-manager/Microsoft.Subscription/stable/2021-10-01/subscriptions.json), do we still need to upgrade it?  
Other parts have been upgraded(https://github.com/Azure/azure-cli-extensions/pull/4409).

**Comment by Ochirkhuyag** [comment]
Checked this. Current ([2021-10-01](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/subscription/resource-manager/Microsoft.Subscription/stable/2021-10-01/subscriptions.json)) and previous version ([2020-09-01](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/subscription/resource-manager/Microsoft.Subscription/stable/2020-09-01/subscriptions.json)) of our Subscription RP don't have it. 

In older version 2020-01-01 and some preview versions (2018-03-01-preview and 2019-10-01-preview) have it.

So, how have we done the azure-cli for our previous version?

**Comment by Ochirkhuyag** [comment]
@zhoxing-ms 

As it removed from previous swagger, we should be good to remove the dependency on the referred URI. 

We are now going through "az account alias create".

Here is a public documentation which refers to it. 
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=azure-cli

Please let us know if you need anything else!

**Comment by zhoxing-ms** [comment]
@Ochirkhuyag So we don't need to upgrade the api-version for `az account create` command, but just need to upgrade the `az account alias create` command, right?

**Comment by sriramvu** [comment]
@zhoxing-ms: as we have removed that API itself from the Swagger as a breaking change couple of apiVersions before, do we still want to maintain the command referring to that?
by any chance, can we get some telemetry on usage of the command?

**Comment by sriramvu** [comment]
> @Ochirkhuyag So we don't need to upgrade the api-version for `az account create` command, but just need to upgrade the `az account alias create` command, right?

- [ ] 

- [ ] #

**Comment by zhoxing-ms** [comment]
>/providers/Microsoft.Billing/enrollmentAccounts/{enrollmentAccountName}/providers/Microsoft.Subscription/createSubscription

@sriramvu Hi, may I ask will the service team maintain the REST in the future?  And do you confirm that command `az account alias create` (REST: https://management.azure.com/providers/Microsoft.Subscription/aliases/sampleAlias) has the same function as command `az account create`, and suggest that we deprecate command `az account create` and replace it with command `az account alias create`?

In fact, we have the Telemetry to view the user's usage of `az account create` command: in the last month, 108 subscriptions executed this command 538 times.

**Comment by sriramvu** [comment]
Yes, with 'az account alias create', we should be getting same functionality as of 'az account create'.
1) as the command is currently getting used by many customers, can you please share the process of deprecation.
2) will check with my manager and confirm either if we want to leave the command as is or remove as there is other equivalent command to achieve the same functionality.  

referring to below 2 documents:
1) https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest#az-account-create
2) https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=azure-cli

**Comment by zhoxing-ms** [comment]
@sriramvu If we need to deprecated this command, we will mark the `deprecate_info` [doc_link](https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#deprecating-commands-and-arguments). So when users use it, they will be prompted `This command is implicitly deprecated because command 'account create' is deprecated and will be removed in a future release. Use 'account alias create' instead.`

After some sprints, we will continue to observe the usage of this command. When only a few users are using this command, we will remove this command, so as to reduce the impact of this breaking change.

**Comment by sriramvu** [comment]
@zhoxing-ms: based on telemetry & internal discussions - request to keep 'az account create' as is - and only upgrade alias commands.

**Comment by zhoxing-ms** [comment]
@sriramvu OK, but I suggest we can add the `deprecate_info` flag to this command in advance. So as to inform users that this command may be deprecated in the future and guide them to migrate to the new command.
It will not affect the subsequent normal usage of this command, but will add some prompt message to users

**Comment by zhoxing-ms** [comment]
@sriramvu Yes, `expiration`  is not mandatory, I also mean that it only indicates deprecated information, but does not specify the target date and version

**Comment by sriramvu** [comment]
@zhoxing-ms: as the permission gap takes more time to bridge - we would like to defer the deprecation plan for now and to proceed with the upgrading alias commands with the latest.

**Comment by zhoxing-ms** [comment]
@sriramvu May I ask what is the permission gap you mean?

**Comment by sriramvu** [comment]
@zhoxing-ms: here is bit more details:

CLI command 'az account create':
* user needs permission on enrollmentAccounts/{enrollmentAccountObjectId}
* public doc: https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-preview?tabs=rest#create-subscriptions-under-a-specific-enrollment-account

CLI command 'az account alias create':
* user needs permission on billingAccounts/{billingAccountId}/enrollmentAccounts/{enrollmentAccountId} 
* public doc: https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=azure-cli#create-subscriptions-under-a-specific-enrollment-account

**Comment by zhoxing-ms** [comment]
Yes, we have finished the upgrade in PR #4409, you can have a try~
