### ISSUE TITLE
not able to deploy templates on sandbox for practice

### ISSUE THREAD

**Issue by mohit-gitlearn** [Azure/azure-cli#20421]
Please fix this issue.
I am getting this error "Found multiple accounts with the same username" when I try to deploy something via ARM template on azure sandbox. I am not able to complete the training.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/20168#issuecomment-963747032 for the solution. We are still investigating the scenario.
