### ISSUE TITLE
create-for-rbac's Help Message is Misleaing

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-cli#2042]
Environment:
 * Ubuntu 16.04
 * Python 3.5.2
 * azure-cli 0.1.1b3

The help message for *az ad sp create-for-rbac* says the following for the -n argument:
```text
    --name -n      : A display name or an app id uri. Command will generate one if missing.
```

I created the SPN using this command.
```sh
az ad sp create-for-rbac -n "http://MyGreatSpn" --role Reader --years 2 --password VerySecret
```

The command returned the following display name instead.
```json
{
  "appId": "2e3c163e-3581-4021-9fef-ff31ef6119ff",
  "displayName": "azure-cli-2017-02-10-22-32-11",
  "name": "http://MyGreatSpn,
  "password": "VerySecret",
  "tenant": "be9c53c3-21fe-4f07-aa2e-b17347fbfa91"
}
```

I expected the SPN to have a display name of "http://MyGreatSpn" instead of a value assigned by azure-cli.  What is the correct way to control this value?

**Comment by colemickens** [comment]
Looks like this PR might have a small bug: https://github.com/Azure/azure-cli/pull/1715/files#diff-a4414434466c749f838ddfb378472311R455

I think if line 455 read    `app_display_name = name` then it would have the desired effect...

cc: @yugangw-msft
