### ISSUE TITLE
enable-secret-rotation throws exception

### ISSUE THREAD

**Issue by sylvaingirardbe** [Azure/azure-cli#20438]
**Describe the bug**
When running `az aks update -n <clustername> -g <rg> --enable-secret-rotation` I get an exception.

**To Reproduce**
Run `az aks update -n <clustername> -g <rg> --enable-secret-rotation`

**Expected behavior**
Secret rotation enabled on cluster.

**Environment summary**
PowerShell on Windows 10. Azure Cloud Shell does the same.

**Additional context**
Exception: 
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 2717, in aks_update
TypeError: 'NoneType' object does not support item assignment
```

**Comment by yonzhan** [comment]
route to service team

**Comment by FumingZhang** [comment]
Sorry for the inconvenience. Could you please also provider the version of azure-cli and python you are using? You could check the version of azure-cli by `az version` and python by `python --version`.

Besides, could you please also check if the secret provider addon profile exists by `az aks show -g {resource_group_name} -n {cluster_name} --query "addonProfiles"`?

As for the workaround, may consider using the `az aks enable-addons` command to enable this option. Example would be `az aks enable-addons -g {resource_group_name} -n {cluster_name} -a azure-keyvault-secrets-provider --enable-secret-rotation`.

**Comment by sylvaingirardbe** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/1567350/142985279-5f6f3b40-e59d-4df6-8f51-89982d4c8671.png)

**Comment by FumingZhang** [comment]
Sadly we save the `config` for this addon as `null`. We will investigate why this happens.

As for the workaround, could you please disable the addon first by `az aks disable-addons -g {resource_group_name} -n {cluster_name} -a azure-keyvault-secrets-provider` and then enable this addon by `az aks enable-addons -g {resource_group_name} -n {cluster_name} -a azure-keyvault-secrets-provider --enable-secret-rotation`?

**Comment by sylvaingirardbe** [comment]
That doesn't work:
(BadRequest) AzureKeyvaultSecretsProvider addon cannot be disabled due to more than 0 Secret Provider Classes
Code: BadRequest
Message: AzureKeyvaultSecretsProvider addon cannot be disabled due to more than 0 Secret Provider Classes

That provider is in use on the cluster.

**Comment by FumingZhang** [comment]
OK, if this won't disrupt your service, could you please remove the secret provider classes in use and then perform the above-mentioned disable and enable operations one by one?

**Comment by sylvaingirardbe** [comment]
I'll get on that in the evening so I won't ruin anyone's day. Specially not mine :)

**Comment by sylvaingirardbe** [comment]
After disabling and re-enabling the addon, rotation is on and config isn't null anymore.

**Comment by ozbillwang** [comment]
> OK, if this won't disrupt your service, could you please remove the secret provider classes in use and then perform the above-mentioned disable and enable operations one by one?

Here is the real command we need run, after run it, you can disable the addon successfully
```
$ kk get secretproviderclasses

$ kubectl delete secretproviderclasses <the_name>
```
