### ISSUE TITLE
Please fix azure-cli-core dependencies

### ISSUE THREAD

**Issue by olafskaug** [Azure/azure-cli#20442]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Using VS Code to deploy to Azure Function App. Dependencies are b0rked.
You didn't get the memo that other packages get updated as well. This is not a major package version. Also it's 11 months old.

**To Reproduce**
$ pip install requests

**Expected behavior**
Error Code 0

**Environment summary**
Not relevant since you should have fixed the dependencies in 11 months.

**Additional context**
Deploying to Azure Function using Function App Core Libs and Python.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
azure-cli-core 2.30.0 requires requests[socks]~=2.25.1, but you have requests 2.26.0 which is incompatible.

**Comment by yonzhan** [comment]
route to service team

**Comment by olafskaug** [comment]
It's already been fixed in dev: [https://github.com/Azure/azure-cli/commit/9a0d5162897b2761e26a2ce7026f9081538f22f4](url)

**Comment by panchagnula** [comment]
closing this since this is fixed
