### ISSUE TITLE
Azure CLI not asking for 2FA and therefore unable to login

### ISSUE THREAD

**Issue by princevince** [Azure/azure-cli#20441]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.

Trace ID: 34750106-c9e4-4238-b6eb-484960ca3e00

Correlation ID: 3b85e4be-06c7-4da5-a53c-3eff6526a4eb

Timestamp: 2021-11-19 10:20:06Z

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login -u {} -p {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Could you try to re-login with 

```
az account clear
az login
```

**Comment by princevince** [comment]
This gives me the same result.

> The ID token is not yet valid.

**Comment by jiasli** [comment]
> The ID token is not yet valid.

This is a new error, indicating your computer's time is not correct. Please see the discussion at #20434.

**Comment by princevince** [comment]
Ah, I see. This was indeed the case. For some reason my computer's clock wouldn't synchronize. I changed the time manually and now I'm able to login!

**Comment by jiasli** [comment]
Glad to know that! 😊
