### ISSUE TITLE
Command not working anymore within python script, but still working with cli

### ISSUE THREAD

**Issue by mcomisso-elux** [Azure/azure-cli#20464]
## Describe the bug

**Command Name**
`az network vnet list`

**Errors:**
```
The credential data used by CLI has been expired because you might have changed or reset the password. Please clear browser's cookies and run 'az login'

```

## To Reproduce:
Script to reproduce the behavior.

```
#!/usr/bin/python3
from azure.cli.core import get_default_cli

def azurer(args_str):
    args = args_str.split()
    cli = get_default_cli()
    cli.invoke(args)
    return cli.result.result

subscriptions = azurer("account list")
for s in subscriptions:
    vnets = azurer("network vnet list --subscription " + s['name'])
    if type(vnets) == dict:
        for v in vnets:
            print(v['name'])
```
## Expected Behavior

Last time I used this script (some weeks ago) it was working fine.
Also, the same command (network vnet list --subscription xxxxxx) executed from the CLI is still working fine.

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.30.0
```
## Additional Context

I've cleared my account (az account clear) and tried again, same result. I've also tried with this environment:

```
Windows-10-10.0.19041-SP0, 
Python 3.9.4
Installer: PIP

azure-cli 2.30.0
```
obtaining this output:

```
User xxxxxxxxxxxxxxx does not exist in MSAL token cache. Run `az login`.
```

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Please login and try again.

**Comment by mcomisso-elux** [comment]
1. Cleared previous logins

`~ » az account clear
`

2. New login, getting the list of subscriptions

```
~ » az login --username 'username@domain'
Password:
[
  {
    "cloudName": "AzureCloud",
		(...)
  }
]
```

3. Running the script, getting the list of subscriptions but not the list of networks in each subscription

```
~ » python3 myscript.py
DEBUG: output from "az account list"
[
  {
    "cloudName": "AzureCloud",
		(...)
  }
]
DEBUG: output from "az network vnet list --subscription xxxxxxxxxx"
The credential data used by CLI has been expired because you might have changed or reset the password. Please clear browser's cookies and run 'az login'
```

4. Running the same command manually from the cli, getting the result

```
~ » az network vnet list --subscription xxxxxxxxxx
[
  {
    "addressSpace": {
		(...)
   }
  }
]
```

**Comment by kairu-ms** [comment]
@jiasli Could you have a look? Thanks.

**Comment by jiasli** [comment]
This is because the Python script and direct `az network vnet list` command are calling **different versions of Azure CLI**.

The error message `The credential data used by CLI ...` has long been removed by #17072. Please make sure the correct version of Azure CLI is called by upgrading to the latest version

```
pip install --upgrade azure-cli
```

---

By the way, your script uses **subscription name** as `--subscription` which may break if there are spaces in it. You can use either subscription ID of [`shlex.split`](https://docs.python.org/3/library/shlex.html#shlex.split).

Use subscription ID:

```py
from azure.cli.core import get_default_cli


def azurer(args_str):
    args = args_str.split()
    cli = get_default_cli()
    cli.invoke(args)
    return cli.result.result

subscriptions = azurer("account list")
for s in subscriptions:
    vnets = azurer("network vnet list --subscription " + s['id'])
    if type(vnets) == dict:
        for v in vnets:
            print(v['name'])
```


Use `shlex.split`:

```py
from azure.cli.core import get_default_cli
import shlex


def azurer(args_str):
    args = shlex.split(args_str)
    cli = get_default_cli()
    cli.invoke(args)
    return cli.result.result

subscriptions = azurer("account list")
for s in subscriptions:
    vnets = azurer("network vnet list --subscription '" + s['name'] + "'")
    if type(vnets) == dict:
        for v in vnets:
            print(v['name'])
```

**Comment by mcomisso-elux** [comment]
Thanks a lot @jiasli, I've been able to solve the issue!

Regards,
Matteo

**Comment by jiasli** [comment]
Glad to know that! 😊
