### ISSUE TITLE
2 Accounts Issue

### ISSUE THREAD

**Issue by 202012092** [Azure/azure-cli#20467]
Hello, I have created a student benefit account which have $100 fir 1 year subscription using my college's email ID.

I have logged in using the same email id and worked with azure multiple times.

But today when I was trying to login it's show that you have 2 accounts with same name and when I am trying to login. It's showing "Found multiple accounts with the same username" error.

Please help
![cloud](https://user-images.githubusercontent.com/83826260/142891583-a55466b5-f132-4541-b6fa-0e135a1eaa8b.PNG)

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/20168#issuecomment-963747032 for the solution. We are still investigating the scenario.

**Comment by 202012092** [comment]
> Please see [#20168 (comment)](https://github.com/Azure/azure-cli/issues/20168#issuecomment-963747032) for the solution. We are still investigating the scenario.


This worked.

Thanks a lot for the help.

**Comment by 202012092** [comment]
Can I know what caused that issue of multiple accounts?
Is it a mistake from my side or was that something else?

**Comment by jiasli** [comment]
I don't think you have done anything wrong. It should be something related to Microsoft Learn sandbox account. We are still investigating. 

For now, please only **stick to one account**.
