### ISSUE TITLE
Drop old Track 2 Azure SDK support

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#20462]
https://github.com/Azure/azure-cli/pull/15806 introduced patches for problematic old Track 2 SDKs. As autorest has been updated to generate new SDKs with these bugs fixed:

- https://github.com/Azure/autorest.python/pull/239
- https://github.com/Azure/autorest.python/pull/745

`azure-cli-core` should drop these patches as they introduces **extra maintenance effort**.

**Comment by yonzhan** [comment]
Drop old Track 2
