### ISSUE TITLE
FunctionApp:Azure CLI 2.30.0 - az webapp show throws ERROR: 'str' object has no attribute 'value'

### ISSUE THREAD

**Issue by Kotasudhakarreddy** [Azure/azure-cli#20479]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

`az webapp show` throws an error trace rather than a friendly message when used to get the `function app` details. 
**To Reproduce**

1. create a `function app`
2. use `az webapp show` to get the `functionapp` details created in first step.
**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
Duplicate of #20437
