### ISSUE TITLE
Error while creating the azure container app

### ISSUE THREAD

**Issue by ShafeerAli** [Azure/azure-cli#20471]
## Describe the bug

**Command Name**
`az containerapp env create`

**Errors:**
```
No module named 'azure.cli.core.azclierror'
Traceback (most recent call last):
pip-install-0u_uiwkq\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 528, in execute
azure\cli\core\__init__.py, ln 299, in load_arguments
cli\core\commands\__init__.py, ln 291, in load_arguments
pip-install-0u_uiwkq\knack\knack\commands.py, ln 97, in load_arguments
azure\cli\core\__init__.py, ln 496, in default_arguments_loader
...
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
cliextensions\containerapp\azext_workerapp\custom.py, ln 10, in <module>
    from azure.cli.core.azclierror import (ResourceNotFoundError, RequiredArgumentMissingError, MutuallyExclusiveArgumentError, ValidationError)
ModuleNotFoundError: No module named 'azure.cli.core.azclierror'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az containerapp env create --name {} --resource-group {} --logs-workspace-id {} --logs-workspace-key {} --location {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.80

Extensions:
aro 1.0.0
containerapp 0.2.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by avinashupadhya99** [comment]
Incorrectly labeled as `Container Instances` instead of `ContainerApp`

**Comment by RakeshMohanMSFT** [comment]
@ShafeerAli Can you please upgrade to the latest version of CLI [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
