### ISSUE TITLE
ReadMe missing

### ISSUE THREAD

**Issue by akashrd** [Azure/azure-cli#20498]
The doc refer to a ReadMe.Md multiples times but does not provide a link to the ReadMe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa2d288d-9ff4-a51c-3f30-1d79ea6564ab
* Version Independent ID: 4483e7d2-49f0-c2f4-afa2-3d7137ea70be
* Content: [az logic workflow](https://docs.microsoft.com/en-us/cli/azure/logic/workflow?view=azure-cli-latest#az_logic_workflow_list)
* Content Source: [latest/docs-ref-autogen/logic/workflow.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/logic/workflow.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by CTroessaert** [comment]
any update on this ?

**Comment by jsntcy** [comment]
Need add [readme link](https://github.com/Azure/azure-cli-extensions/blob/main/src/logic/README.md) in help (overwrite help for parameters with readme.md in https://github.com/Azure/azure-cli-extensions/blob/main/src/logic/azext_logic/generated/_params.py).

We'll release a fix at the end of May.
