### ISSUE TITLE
Improve output and error status in az vm run-command

### ISSUE THREAD

**Issue by tomkregenbild** [Azure/azure-cli#20495]
Currently we have about thousands of ubuntu VM's that we manage by using a tool called [Rundeck ](https://www.rundeck.com/videos) to orchestrate and connect to our VM's in a centralized way using SSH. We have hundreds of jobs that perform many different actions on our servers.

Because of security requirements we want to migrate from using SSH to using the run-command mechanism in Azure and integrate it into our command running mechanism (currently ssh based). I have tested the run-command feature and found a few limitations that makes this process challenging for us and I want to know what is the possibility to provide the following features

1. The old command of "az vm run-command invoke" provides a very limited log output and in some cases we need very large logs. On the other hand the new "az vm run-command create" is not providing the output back to stdout in any way. Is it possible to provide a feature to get the full output to stdout at the end of the run? if not, is it possible to write the file to some local file on the machine that is running the az command and not only to a blob?

2. The "az vm run-command create" command is not providing a clear exit status even if the command is failing. If the command itself return status code that is not 0, the output will still show "provisioningState": "Succeeded" - with this scenario it is very hard to manage operations at large scale and to understand what failed. Is there a possibility to provide an error code status in the output?

3. In both commands the output is provided only at the end and not during the running of the command.
In some cases the process might get stuck on an operation and there will be no way to know what is going on until the command will reach a timeout. In some use cases this very challenging for debugging. Is there a way to make the output live during the run?

These features can be a huge improvement to all customers using the run command and it can allow a great secure mechanism of managing VM's in a large scale

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
As we discussed offline in email *"Azure cli run-command features"*, since the output data (include full log output and error status) should be returned by REST service, so those requirements need the support from service team.

@koralski Could you help look at these suggestions and feedback?

**Comment by Drewm3** [comment]
@amjads1, could you please work with the RunCommand team to see if this feature request can be accommodated?

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by koralski** [comment]
After you call az run-command create
output you need can be fetched by calling 
az vm run-command show --name "myRunCommand" --vm-name "myVM" --resource-group "myRG" –expand instanceView

with the expand option you get details execution state and output streams. 

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/run-command-managed

**Comment by amjads1** [comment]
@tomkregenbild Can you please confirm if the above comments and options shared and if that works for your use case on what you are looking for?

**Comment by tomkregenbild** [comment]
@koralski I tested the command these are the finding:
1. First I had to run the "az vm run-command create" command and after that I needed to run the "az vm run-command show" to view the output something that makes much less efficient and hard to manage automatically.

2. The output under the show command is still limited to what seems to be 4779 characters which is not enough for long executions with a lot of output.

3. Even though I ran a non existing command and the error field provided an error. The exit status code was 0 and executionState was "Succeeded". Once again this is hard to debug.

4. While running the --expand instanceView parameter I got the following warning:
Argument 'expand' has been deprecated and will be removed in a future release.

**Comment by amjads1** [comment]
@tomkregenbild Just to confirm, are you looking into the latest release of managed RunCommand?
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/run-command-managed

**Comment by tomkregenbild** [comment]
@amjads1 Yes, I used the latest version

**Comment by navba-MSFT** [comment]
@tomkregenbild Apologies for the late reply. We are looking in to this issue. We will provide an update once we have more details.

@amjads1 Could you please provide an update on this once you get a chance ? Awaiting your reply.

**Comment by streamye2022** [comment]
do we know how to work around the output limitation for 4096 bytes

**Comment by nikhilpatel909** [comment]
@tomkregenbild We appreciate your feedback. - provisioningState issue will be fixed as part of GA, Next two weeks.
- There is no live output feature as of today. If you use "asyncExecution": "false" you will be able to check the status of runcommand using get API

**Comment by keklinke** [comment]
@navba-MSFT - Do you have any update on this feature request? It seems like we can sort of get around it by using the "--expand instanceView" flag since that dumps the exit code and the output/error streams, but as @tomkregenbild notes there is a warning today saying that that flag will be deprecated soon.

**Comment by vivlingaiah** [comment]
@tomkregenbild,
1. stdout output issue is already fixed for az vm run-command create (Managed Run Command). Please try again now. We are not making any changes to az vm run-command invoke (Action Run Command)
2.  Exit codes should be fixed now. Try again. use "-treatFailureDeploymentFailure" API parameter. If it is true, the RunCommand's ProvisioningState will be set to "Failed" if Run Command terminates with non-zero exit code. Note this flag is not available in Powershell /CLI cmdlet yet. It should be available after https://github.com/Azure/azure-powershell/issues/22401 has been completed.
3. Yes. Stream your logs and errors to a blob using -OutputBlobUri and -ErrorBlobUri parameters. Please refer https://learn.microsoft.com/en-us/azure/virtual-machines/linux/run-command-managed#create-or-update-run-command-on-a-vm-using-outputbloburi-errorbloburi-to-stream-standard-output-and-standard-error-messages-to-output-and-error-append-blobs  or
https://learn.microsoft.com/en-us/azure/virtual-machines/windows/run-command-managed#create-or-update-run-command-on-a-vm-using-outputbloburi-errorbloburi-to-stream-standard-output-and-standard-error-messages-to-output-and-error-append-blobs
Complete logs would be available in the blobs
