### ISSUE TITLE
Not able to login azure through cli

### ISSUE THREAD

**Issue by AnilPeriyedath** [Azure/azure-cli#20507]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unable to get authority configuration for https://login.microsoftonline.com/9a2e6147-7e4b-4c5a-b997-dfedfb47a1a3. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant_name
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/msal/authority.py", line 83, in __init__
    openid_config = tenant_discovery(
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/msal/authority.py", line 151, in tenant_discovery
    raise ValueError("OIDC Discovery endpoint rejects our request")
ValueError: OIDC Discovery endpoint rejects our request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 145, in login
    subscriptions = profile.login(
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 160, in login
    identity.login_with_service_principal(username, password, scopes=scopes)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 146, in login_with_service_principal
    cred = ServicePrincipalCredential(sp_auth, **self._msal_app_kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/auth/msal_authentication.py", line 120, in __init__
    super().__init__(service_principal_auth.client_id, client_credential=client_credential, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/msal/application.py", line 381, in __init__
    self.authority = Authority(
  File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/msal/authority.py", line 87, in __init__
    raise ValueError(
ValueError: Unable to get authority configuration for https://login.microsoftonline.com/9a2e6147-7e4b-4c5a-b997-dfedfb47a1a3. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant_name

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --service-principal -u {} -p {} --tenant {}`

## Environment Summary
```
macOS-12.0.1-x86_64-i386-64bit, Darwin 21.1.0
Python 3.10.0
Installer: HOMEBREW

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by rayluo** [comment]
> File "/usr/local/Cellar/azure-cli/2.30.0_1/libexec/lib/python3.10/site-packages/msal/authority.py", line 151, in tenant_discovery
>     raise ValueError("OIDC Discovery endpoint rejects our request")
> ValueError: OIDC Discovery endpoint rejects our request

This error is raised from [here](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.15.0/msal/authority.py#L148-L151):

```python
    if 400 <= resp.status_code < 500:
        # Nonexist tenant would hit this path
        # e.g. https://login.microsoftonline.com/nonexist_tenant/v2.0/.well-known/openid-configuration
        raise ValueError("OIDC Discovery endpoint rejects our request")
```

Indeed, the url derived from the reporter's tenant GUID is `https://login.microsoftonline.com/9a2e6147-7e4b-4c5a-b997-dfedfb47a1a3/v2.0/.well-known/openid-configuration`, visiting it in browser, it will give us an error.

Looks like @AnilPeriyedath pasted an incorrect GUID. Can you check that, Anil?

P.S.: MSAL Python would need to improve the error message in this case, to help self-troubleshooting. :-/

**Comment by rayluo** [comment]
I have merged in the error message improvement in upstream. It will be shipped with next release of MSAL.

This issue here can be closed due to inactivity.

**Comment by simondevries** [comment]
I ran into this issue recently. It turns out I had fiddler open which was messing with the network request. Closing Fiddler fixed the issue

**Comment by rjsalicco** [comment]
If there is nothing in ~/.azure and you use the interactive login which is directed to the MS Azure login screen, how is this a user error when the wrong tenant id is being configured? Just for clarity.

**Comment by jiasli** [comment]
@rjsalicco,

> how is this a user error when the wrong tenant id is being configured?

Tenant ID is specified **by the user** via the `--tenant` argument in `az login`, such as:

```
> az login --tenant 54826b22-38d6-4fb2-bad9-b7b93a3e0000
Unable to get authority configuration for https://login.microsoftonline.com/54826b22-38d6-4fb2-bad9-b7b93a3e0000. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.
```

That's why it is a user error.

If you don't specify `--tenant`, `az login` with use a special tenant called `organizations`:

https://github.com/Azure/azure-cli/blob/7e8a4d9d0d6dc621d13a7fac4d4104b1d34a3f6a/src/azure-cli-core/azure/cli/core/auth/identity.py#L362

It will never raise this error.

**Comment by rjsalicco** [comment]
@jiasli, as you note:

_If you don't specify --tenant, az login with use a special tenant called organizations:_

and that behavior, as expected above, was failing

no worries, thank you.

**Comment by jiasli** [comment]
> that behavior, as expected above, was failing

Could you share the full error message for us to investigate?

**Comment by angustatchell** [comment]
@jiasli to confirm, this isn't a user error as mentioned by @rjsalicco, is it? 

The CLI docs list `az login` without `--tenant flag` as valid authentication flow for [signing in interactively](https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli#sign-in-interactively). This works for me in other Azure accounts, but I am having the problem described above in an account where a tenant seems to have been deleted. The AZ CLI seems to be getting passed the deleted tenant's ID by `https://login.microsoftonline.com/organizations`.

Is this coming from MSAL? Do you know where I can find further information on the source of this issue?

**Comment by jiasli** [comment]
@angustatchell, could you run `az login --debug` and check if the delete tenant is returned by [Tenants - List](https://learn.microsoft.com/en-us/rest/api/resources/tenants/list?tabs=HTTP) API?

```
GET https://management.azure.com/tenants?api-version=2020-01-01
```

If it returns a deleted tenant, this should be checked by ARM service (Azure support) since this looks like caching issue.

**Comment by angustatchell** [comment]
Hi @jiasli I see in debug output that the call to the [TENANTS?] API returns a list of objects for my current tenants AND the deleted tenant as well. 

The existing tenant objects have keys for: 
`"id"`, `"tenantId"`, `"countryCode"`, `"displayName"`, `"domains"`, and `"tenantCategory"`. 

However, the deleted tenant returns only has keys for: 
`"id"`, `"tenantId"`, and `"tenantCategory"`. 

All the tenants have their `"tenantCategory"` set to "Home".

Would that indicate the problem is indeed from the ARM service? 
Also, is there anything else from the debug output worth sharing?

**Comment by jiasli** [comment]
> Would that indicate the problem is indeed from the ARM service?

Yes. You may share the HTTP trace with Azure support to help them check why deleted tenant is still returned.
