### ISSUE TITLE
[Network] VNET gateway should support configuration of active-active gateways

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#2050]
This is a new feature which was also announced in Ignite last year. Please refer to the Powershell cmdlet documentation or get in touch with me.

- [x] Active-Active Cross Premise
- [x] Active-Active VNet-to-VNet
- [x] Active-Standby to Active-Active
- [x] Active-Active to Active-Standby

**Comment by tjprescott** [comment]
Reference:
https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-activeactive-rm-powershell

**Comment by aanandr** [comment]
That’s a good place to start. If you need any help let me know.
