### ISSUE TITLE
[Network] VNET-gateway Create and Update require peer IP addr for BGP

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#2051]
As far as BGP is concerned this command is only used to change the BGP ASN no. It shouldnt even have a BGP peer IP address param (refer to the corresponding cmdlet too). When i try to run the command without specifying this param it doesnt work.

**Comment by tjprescott** [comment]
If this parameter is read only, then this is a bug in the REST API specs. Please file an issue there.
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-09-01/swagger/virtualNetworkGateway.json#L1210

**Comment by aanandr** [comment]
This is not about the param being read-only. It shouldn’t even be an option in the command. There is no need to specify the BGP end-point. PS doesn’t provide it either. Can you please remove it? The other problem is that this command should allow me to specify the ASN which it doesn’t, until I specify the BGP end point IP. VNET-VNET BGP is broken as a result because there is a need to change the ASN using this command.

I am concluding all this because that’s how PS works. CLI should work the same way else we will lose the consistency. Ping me if you need more info.

**Comment by tjprescott** [comment]
If the service exposes it as a settable parameter (which it does by virtue of not being read-only) then we will continue to expose the parameter. For all we know PS is incorrect for not exposing it. However, I will make it optional in the CLI.

If it truly cannot/should not be set by the user, then please file that issue in the REST API specs. I don't have the expert knowledge to know one way or the other or else I'd gladly file it.

**Comment by aanandr** [comment]
Travis
I had a chat with the devs and learnt that when you set the BGP IP addr it is not even honored by the platform underneath. So its better to completely remove it. Otherwise customers might set it and either see an error or it wont take effect – both of which are dangerous.
BTW, this is only for virtual network gateway. For local network gateway this parameter is required.

Aanand
