### ISSUE TITLE
APIM apply network configuration CLI has an invalid description

### ISSUE THREAD

**Issue by vlad610** [Azure/azure-cli#20521]
This operation has the wrong description:
https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest#az_apim_apply_network_updates

The current description is:
_Back up an API Management service to the configured storage account._

This is not correct. The operation does the same thing as:
https://docs.microsoft.com/en-us/rest/api/apimanagement/2020-12-01/api-management-service/apply-network-configuration-updates

A better description would be something like:
_Updates the Microsoft.ApiManagement resource running in the Virtual network to pick the updated DNS changes._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 197d8382-ee16-6001-4941-768877379c0d
* Version Independent ID: 1423fa76-977f-ad88-8129-0b52a38e68e6
* Content: [az apim](https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest#az_apim_apply_network_updates)
* Content Source: [latest/docs-ref-autogen/apim.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/apim.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by RakeshMohanMSFT** [comment]
@vlad610 This issue is fixed https://github.com/Azure/azure-cli/pull/21708
