### ISSUE TITLE
Cannot remove multiple address rules on Key Vault firewall in one command (but can add multiple)

### ISSUE THREAD

**Issue by davecluderay** [Azure/azure-cli#20520]
## Description

The commands to add and remove network rules on a Key Vault are inconsistently implemented.

**Commands**

`az keyvault network-rule add --name kv-xyz --resource-group rg-xyz --output none --ip-address 20.37.158.0/23 40.74.28.0/23`
`az keyvault network-rule remove --name kv-xyz --resource-group rg-xyz --output none --ip-address 20.37.158.0/23 40.74.28.0/23`

## Expected Behaviour

The `add` command adds two rules, one for each CIDR.
The `remove` command removes the rules for each CIDR.

## Actual Behaviour

The `remove` command is not able to handle multiple CIDRs, which makes the API inconsistent.
Separate `remove` commands are required for each CIDR, which is inefficient.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0

```

**Comment by yonzhan** [comment]
keyvault
