### ISSUE TITLE
[ACR]: Generate credential for token fails if token name contains a dash (`-`)

### ISSUE THREAD

**Issue by ThorstenHans** [Azure/azure-cli#20538]
**Describe the bug**

Generating credential fails if the underlying token name contains a dash (`-`):

```bash
acrName=youracrname
rgName=yourrgname

az acr token credential generate -n sample-token -r $acrName -g $rgName --expiration-in-days 90 --password1
```

However, if you change the name of the token to `SampleToken` or `sampletoken`, everything works as expected.

**To Reproduce**

Execute the following commands:

```bash
acrName=test1234
rgName=rg-1234
az acr scope-map create -n scope-read-everything -r $acrName -g $rgName --repository content/read metadata/read
az acr token create -n sample-token -r $acrName -g $rgName --no-passwords true --scope-map scope-read-everything
az acr token credential generate -n sample-token -r $acrName -g $rgName --expiration-in-days 90 --password1
```
Last command will fail with:

```
(ResourceNotFound) The resource smaple-token could not be found.
Code: ResourceNotFound
Message: The resource smaple-token could not be found.
```

**Expected behavior**

Credential should be generated.

**Environment summary**
```
macOS-12.0.1-x86_64-i386-64bit, Darwin 21.1.0
Python 3.9.9
Installer: PIP

azure-cli 2.30.0

Extensions:
k8sconfiguration 0.2.1
connectedk8s 1.1.3
log-analytics-solution 0.1.1
k8s-extension 0.2.1
aks-preview 0.5.42
resource-graph 1.1.0
containerapp 0.2.0
application-insights 0.1.13
account 0.2.1
connectedmachine 0.3.0
```

**Comment by yonzhan** [comment]
route to service team

**Comment by gildardogmsft** [comment]
Hi @ThorstenHans it seems that there was a typo in your command, based out of the output 
`The resource smaple-token could not be found.`

Perhaps the smaple-token should be replaced by sample-token?

**Comment by ThorstenHans** [comment]
Yeah the typo was just here in the issue, I can re-verify this evening CEST


https://thorsten-hans.com
________________________________

**Comment by ThorstenHans** [comment]
@gildardogmsft you were right. I had a typo locally too. My bad!

Sorry, and thanks for pointing me to this one.
