### ISSUE TITLE
Command sample is cut off

### ISSUE THREAD

**Issue by seligj95** [Azure/azure-cli#20547]
## Describe the bug
The suggested command when an incorrect command is executed seems to be getting cut off due to a character limit issue.

**Command Name**
`az webapp config set`

**Errors:**
```
unrecognized arguments: -

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- You need to enter in a command that will prompt the "AI knowledge base" to give samples. You can do that by entering a command with some sort of typo or input the below with a missing argument.
- `az webapp config set -`
- Running `az find "az webapp config set"` will give the full list of sample commands

## Expected Behavior
The suggestion given seems to be cut off as shown in the below image.
![image](https://user-images.githubusercontent.com/11475594/143916966-82fc0162-73c2-4ef9-a421-2632f716591e.png)

The expectation is that the full sample should be given as shown in the below image.
![image](https://user-images.githubusercontent.com/11475594/143916985-1f7ef1c1-a7e9-4130-94ac-7d96882158a9.png)

## Environment Summary
```
Linux-5.4.0-1063-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
customlocation 0.1.2
db-up 0.2.6
webapp 0.4.0
connectedk8s 1.1.11
authV2 0.1.1
interactive 0.4.5
k8s-extension 0.7.1
ai-examples 0.2.5
ssh 0.1.8

```

**Comment by yonzhan** [comment]
route to service team

**Comment by seligj95** [comment]
@yonzhan - We have reviewed and this is not a Web Apps/App Service specific issue that we can fix. We believe the issue here happens from the core-cli shared code that parses the examples from the help file. Can this be routed to the core cli team for review?

**Comment by jiasli** [comment]
The example is auto-generated by Aladdin service, so let me involve Aladdin team.

P.S. That's why we changed the description from `TRY THIS:` to `Examples from AI knowledge base:` (https://github.com/Azure/azure-cli/pull/17888)

**Comment by seligj95** [comment]
@mirdaki - any chance you can have a look?

**Comment by mirdaki** [comment]
@seligj95 thanks for the ping! Missed this while I was on vacation. I suspect it's a parsing issue before we send it to the client. Let me investigate it more and I'll post any updates

**Comment by seligj95** [comment]
@mirdaki - thanks for looking into this! did you have a chance to find the source of the error?

**Comment by mirdaki** [comment]
@seligj95 yes! We are reviewing a permanent fix, but I was able to push a short term solution out. Can you please verify that the error is gone?

**Comment by seligj95** [comment]
@mirdaki - things looks good from my side now. I'll close this issue. appreciate the help!
