### ISSUE TITLE
Referencing Azure Functions Project (eg. Unit Testing) breaks dotnet CLI build.

### ISSUE THREAD

**Issue by v-bbalaiagar** [Azure/azure-cli#20543]
**Steps To Reproduce** :

1.Create an Azure Function empty project.
2.Create a class library project.
3.Create a MSTest project.
4.Add the class library as a project reference to the the azure function project.
5.Add the azure function project as a project reference to the MSTest project.
6.Build via dotnet build:

`dotnet build UnitTestProject1\UnitTestProject1.csproj -c Release -o publish_output `

**Expected Result** 

The build should succeed with no errors.

**Actual Result** 

```
λ dotnet build UnitTestProject1\UnitTestProject1.csproj -c Release -o publish_output
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  ClassLibrary1 -> C:\Users\jtong\source\repos\Example\publish_output\ClassLibrary1.dll
  FunctionApp1 -> C:\Users\jtong\source\repos\Example\publish_output\bin\FunctionApp1.dll
CSC : error CS0006: Metadata file 'C:\Users\jtong\source\repos\Example\publish_output\ClassLibrary1.dll' could not be found [C:\Users\jtong\source\repos\Example\UnitTestProject1\UnitTestProject1.csproj]

Build FAILED.

CSC : error CS0006: Metadata file 'C:\Users\jtong\source\repos\Example\publish_output\ClassLibrary1.dll' could not be found [C:\Users\jtong\source\repos\Example\UnitTestProject1\UnitTestProject1.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.74
```
I believe the workaround we used was to build without the -o parameter and also to use dotnet publish.

Issue still is present in 5.0.203. Note that a .NET Core 3.1 API project with the same reference to a class library and unit test does not reproduce this behavior when building the unit test project.

**Comment by yonzhan** [comment]
Not related to Azure CLI
