### ISSUE TITLE
Az powershell: Stop-AzSynapseTrigger not working

### ISSUE THREAD

**Issue by afogarty85** [Azure/azure-cli#20550]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

According to the docs: https://docs.microsoft.com/en-us/powershell/module/az.synapse/stop-azsynapsetrigger?view=azps-6.6.0

```
Stop-AzSynapseTrigger
    -WorkspaceName <String>
    -Name <String>
```

Returns this error:

```
Stop-AzSynapseTrigger: The requested operation requires an element of type 'Object', but the target element has type 'String'.
```

**To Reproduce**

**Expected behavior**
I expected the command to run given two strings

**Environment summary**

I am using the web-based Azure CLI
```
$PSVersionTable.PSVersion
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      0
```

**Additional context**

**Comment by yonzhan** [comment]
Not related to Azure CLI
