### ISSUE TITLE
`az container create` fails due to invalid literal for int()

### ISSUE THREAD

**Issue by lukejgaskell** [Azure/azure-cli#20568]
**Describe the bug**
when running `az container create` it fails and gives the following error: 
`ERROR: invalid literal for int() with base 10: '12/01/2021 20:58:42 +00:00'`

**To Reproduce**
create container with the env as listed below... then run the command:
`az container create -g resource-group-name --name container-name --image my.registry/path/to/image --environment-variables key='value'`

**Expected behavior**
I would expect the container to be created and not give an error.

**Environment summary**
- az cli version 2.29.2
- docker image: `mcr.microsoft.com/azure-cli:2.29.2`
- running on app service
- logged in with `az login --identity` in which the app service had contributor over the resource group.

**Additional context**
We had to roll back to version `2.29.2` because `az login --identity` throws an the same error when on `2.30.0`. It looks like it has to do with a breaking change in an azure active directory api.

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@lukejgaskell Apologies for the late reply. Could you please try to use the most recent version of the CLI and the Python libraries and check if the issue occurs ? Please let me know if you need any further assistance on this issue. Awaiting your reply.

**Comment by lukejgaskell** [comment]
@navba-MSFT if I remember correctly the version published in mid December fixed the issue.

**Comment by navba-MSFT** [comment]
@lukejgaskell Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
