### ISSUE TITLE
[Network] az network profile list --resource-group {} returns empty result

### ISSUE THREAD

**Issue by NimitzDEV** [Azure/azure-cli#20587]
## Describe the bug
`az network profile list` outputs the empty result

This outputs empty results without errors.

**Command Name**
`az network profile list`

**Errors:**
```

```

## To Reproduce:
Following the document describing how to deploy a container inside a virtual network,
1. Deploy a container into a new virtual network
```
az container create \
  --name appcontainer \
  --resource-group myResourceGroup \
  --image mcr.microsoft.com/azuredocs/aci-helloworld \
  --vnet aci-vnet \
  --vnet-address-prefix 10.0.0.0/16 \
  --subnet aci-subnet \
  --subnet-address-prefix 10.0.0.0/24

```

2. Try to get networkProfileId for the automated deployment process
```
az network profile list --resource-group myResourceGroup \
  --query [0].id --output tsv
```

(There is a subnetIds field in the output of the first step, is this the same?)

## Expected Behavior
output a network profile id

## Environment Summary
```
Linux-5.4.0-1063-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
ai-examples 0.2.5
ssh 0.1.8

```

**Comment by jiasli** [comment]
@kairu-ms, could you help take a look?

**Comment by dtheodor** [comment]
Can you take a look at this? This makes it impossible at the moment to deploy a private IP address in a virtual network through a yaml file with this error

```
Code: PrivateIPAddressNotSupported
Message: IP Address type in container group 'smg_logs' is invalid. Private IP address is only supported when network profile is defined.
```

**Comment by kairu-ms** [comment]
Hi @joseph-porter, can you have a look at this? Thanks.

**Comment by joseph-porter** [comment]
Looks like the CLI version here is 2.30.0, which no longer uses or creates a Network Profile. The newer API version for ACI has removed Network Profile and now uses the subnet ID property directly for deploying with virtual networks.

The CLI create command in the initial question should still deploy a container in a virtual network, it just no longer creates a Network Profile and instead fills the request to ACI with the proper subnet information used by the more recent API version.

Previous versions of the API still support Network Profile, so those can still be used if you wish to continue using the Network Profile. The last CLI version that automatically creates the Network Profile would be 2.28.0 and could be used if you still want to create Network Profiles via the CLI.

**Comment by dtheodor** [comment]
CLI was the only practical way to create a network profile. Now you have to call the rest API directly, which for bonus points is hidden from the azure API documentation.

The network profile is needed for the YAML based container group deployment https://docs.microsoft.com/en-us/azure/container-instances/container-instances-vnet which requires a network profile id. Does the yaml configuration support specifying subnets directly in some undocumented form?

Did you consider that you hinder this use case when you removed network profile functionality from the most recent CLI versions?

**Comment by joseph-porter** [comment]
The updated documentation was recently published with details of the changes and example usage: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-vnet

**Comment by NimitzDEV** [comment]
This solves my problem, thanks

**Comment by dtheodor** [comment]
When replacing network profile with subnet ids in the YAML configuration, I get
```
Code: PrivateIPAddressNotSupported
Message: IP Address type in container group 'smg_logs' is invalid. Private IP address is only supported when network profile is defined.
```
