### ISSUE TITLE
`az cosmosdb` crashes on startup

### ISSUE THREAD

**Issue by cizra** [Azure/azure-cli#20581]
## Describe the bug

**Command Name**
`az cosmosdb`

**Errors:**
```
The operation 'azure.mgmt.cosmosdb.operations#DatabaseAccountsOperations.regenerate_key' is invalid.
Traceback (most recent call last):
azure/cli/core/__init__.py, ln 831, in get_op_handler
    op = getattr(op, part)
AttributeError: type object 'DatabaseAccountsOperations' has no attribute 'regenerate_key'

...

azure/cli/core/__init__.py, ln 836, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.mgmt.cosmosdb.operations#DatabaseAccountsOperations.regenerate_key' is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cosmosdb`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python 3.9.2
Installer: DEB

azure-cli 2.18.0 *

```

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@cizra Apologies for the late reply. Could you please use the [most recent version ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)of AzCLI and let me know if you still see this issue. Awaiting your reply.

**Comment by cizra** [comment]
Tried, doesn't reproduce anymore.
