### ISSUE TITLE
Typo: "galley" should be "gallery"

### ISSUE THREAD

**Issue by mbrightcpacket** [Azure/azure-cli#20580]
https://github.com/Azure/azure-cli/blob/a8c410f7d610df28cf7ce042d88cc406d2f64859/src/azure-cli/azure/cli/command_modules/vm/_params.py#L166

**Comment by yonzhan** [comment]
Compute

**Comment by jiasli** [comment]
Thanks for reporting. Actually you may directly open a PR. 😊

**Comment by mbrightcpacket** [comment]
Done: https://github.com/Azure/azure-cli/pull/20593
