### ISSUE TITLE
Azure CLI Deployment Commands Timeout Unit

### ISSUE THREAD

**Issue by vsha041** [Azure/azure-cli#20596]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Firstly, For these 3 commands, I need to know if the documentation is correct or not. For two commands, it says the timeout is in seconds and for the third command the timeout is in milliseconds. Why there is a difference?

az webapp deployment source config-zip ([documentation says seconds](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest#az_webapp_deployment_source_config_zip-examples))

az functionapp deployment source config-zip ([document says seconds](https://docs.microsoft.com/en-us/cli/azure/functionapp/deployment/source?view=azure-cli-latest#az_functionapp_deployment_source_config_zip-optional-parameters))

az webapp deploy ([documentation says milliseconds](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_deploy-optional-parameters))

Secondly, when I look at the [source code](https://github.com/Azure/azure-cli/blob/df7aaf1468aa185f0976882d1790e35bfc1a4a4c/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L3372), it looks like it's not timeout, it's actually a polling operation to check if the deployment has succeeded or not. Is that right? Or I am looking at the wrong place? Thanks.

**To Reproduce**
N/A

**Expected behavior**
All three units should be the same - either seconds or milliseconds

**Environment summary**
N/A

**Additional context**
N/A

**Comment by jiasli** [comment]
Adding webapp service team to take a look.

**Comment by seligj95** [comment]
@JasonFreeberg - can you please have a look?

**Comment by panchagnula** [comment]
@vsha041 yes the timeout is a polling operation for client to not use the default timeout, because based on the package to deploy & build (if enabled by appsetting) this can take longer for config zip (webapp & functionapp) the implementation is seconds, need to check the logic of the new deployment command to check if this is seconds or milliseconds & keep it consistent.

**Comment by vsha041** [comment]
Hi @panchagnula - ok thanks, that's fine. Just reply here when you have found out whether it's seconds or milliseconds for these 3 commands.
az webapp deployment source config-zip .......
az functionapp deployment source config-zip .......
az webapp deploy .......

**Comment by vsha041** [comment]
@navba-MSFT - great thanks, it's sorted now.
