### ISSUE TITLE
az login --identity failed

### ISSUE THREAD

**Issue by longchenyang** [Azure/azure-cli#20605]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Failed to connect to MSI. Please make sure MSI is configured correctly and check the network connection.
Error detail: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01&msi_res_id=%2Fsubscriptions%2Fsubscriptionid%2Fresourcegroups%2Fresourcegroupname%2Fproviders%2FMicrosoft.ManagedIdentity%2FuserAssignedIdentities%2Fidentityfrom<managed identities> (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03DBD958>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity -u {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: 

azure-cli 2.30.0

```

**Comment by jiasli** [comment]
`az login --identity` is only used for [managed identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) on Azure resources. 

Please make sure `az login --identity` in invoked on an Azure resource, like Azure VM, and managed identity is configured correctly.
