### ISSUE TITLE
Python deprecation warning for humanfriendly

### ISSUE THREAD

**Issue by stan-sz** [Azure/azure-cli#20607]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
```
python3.8/site-packages/azure/cli/core/commands/progress.py:182: DeprecationWarning: humanfriendly.Spinner was moved to humanfriendly.terminal.spinners.Spinner, please update your imports
    spinner=humanfriendly.Spinner(  # pylint: disable=no-member
```

Possibly related to #20409

**To Reproduce**
Run pytest on a project that includes azure-cli.

**Expected behavior**
No deprecation warning.

**Environment summary**
az cli 2.30.0

**Additional context**
https://github.com/Azure/azure-cli/blob/ea0286bf612f66eb4c0f0179feccbfe226a99292/src/azure-cli-core/azure/cli/core/commands/progress.py#L118

**Comment by jiasli** [comment]
@zhoxing-ms, please take a look as `humanfriendly` is used by progress bar.
