### ISSUE TITLE
FunctionApp:"az functionapp" usage description ref link broken

### ISSUE THREAD

**Issue by msavel2i** [Azure/azure-cli#20617]
## Describe the bug
link broken

## To Reproduce:
>> az
click on https://github.com/Azure/azure-functions-core-tools at "functionapp" 
it's broken! :(

## Environment Summary
```
Linux-5.4.0-1064-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.30.0

Extensions:
ai-examples 0.2.5
ssh 0.1.8

```

**Comment by zhoxing-ms** [comment]
@msavel2i Hi, I can normally access link https://github.com/Azure/azure-functions-core-tools. What do you mean by broken?

**Comment by RakeshMohanMSFT** [comment]
@msavel2i Can you please help us with more information, like where is this broken link? so that we can help you fix it. Because based on the error description we can clearly see that the link is working.

Awaiting your reply.
