### ISSUE TITLE
Az network vpn-connection list doesnt show values of the Gateway settings

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#2061]
I see only NULL values. I had opened a bug for this a few months back and it is supposed to have been fixed but i still see the issue.

aanandr@AANANDR-WORK11:/mnt/c/Users/aanandr$ az network vpn-connection list -g Vnet-Vnet
[
  {
    "authorizationKey": "",
    "connectionStatus": null,
    "connectionType": "Vnet2Vnet",
    "egressBytesTransferred": 0,
    "enableBgp": false,
    "etag": "W/\"13c0ae93-a622-4b9b-b270-5553e8dfb88b\"",
    "id": "/subscriptions/d6ff83d6-713d-41f6-a025-5eb76334fda9/resourceGroups/Vnet-Vnet/providers/Microsoft.Network/connections/GW1GW2",
    "ingressBytesTransferred": 0,
    "localNetworkGateway2": null,
    "location": "westus",
    "name": "GW1GW2",
    "peer": null,
    "provisioningState": "Succeeded",
    "resourceGroup": "Vnet-Vnet",
    "resourceGuid": "860d8c5f-0003-4457-8885-cb6b90aab703",
    "routingWeight": 10,
    "sharedKey": null,
    "tags": {},
    "tunnelConnectionStatus": null,
    "type": "Microsoft.Network/connections",
    "virtualNetworkGateway1": {
      "activeActive": null,
      "bgpSettings": null,
      "enableBgp": null,
      "etag": null,
      "gatewayDefaultSite": null,
      "gatewayType": null,
      "id": "/subscriptions/d6ff83d6-713d-41f6-a025-5eb76334fda9/resourceGroups/Vnet-Vnet/providers/Microsoft.Network/virtualNetworkGateways/GWVNet1",
      "ipConfigurations": null,
      "location": null,
      "name": null,
      "provisioningState": null,
      "resourceGroup": "Vnet-Vnet",
      "resourceGuid": null,
      "sku": null,
      "tags": null,
      "type": null,
      "vpnClientConfiguration": null,
      "vpnType": null
    },
    "virtualNetworkGateway2": {
      "activeActive": null,
      "bgpSettings": null,
      "enableBgp": null,
      "etag": null,
      "gatewayDefaultSite": null,
      "gatewayType": null,
      "id": "/subscriptions/d6ff83d6-713d-41f6-a025-5eb76334fda9/resourceGroups/Vnet-Vnet/providers/Microsoft.Network/virtualNetworkGateways/GWVNet2",
      "ipConfigurations": null,
      "location": null,
      "name": null,
      "provisioningState": null,
      "resourceGroup": "Vnet-Vnet",
      "resourceGuid": null,
      "sku": null,
      "tags": null,
      "type": null,
      "vpnClientConfiguration": null,
      "vpnType": null
    }
  },
  {
    "authorizationKey": "",
    "connectionStatus": null,
    "connectionType": "Vnet2Vnet",
    "egressBytesTransferred": 0,
    "enableBgp": false,
    "etag": "W/\"9052f3e8-4bc8-4cdd-b75b-7a97b9e5f28b\"",
    "id": "/subscriptions/d6ff83d6-713d-41f6-a025-5eb76334fda9/resourceGroups/Vnet-Vnet/providers/Microsoft.Network/connections/GW2GW1",
    "ingressBytesTransferred": 0,
    "localNetworkGateway2": null,
    "location": "eastus",
    "name": "GW2GW1",
    "peer": null,
    "provisioningState": "Succeeded",
    "resourceGroup": "Vnet-Vnet",
    "resourceGuid": "7e122c2d-4a4f-4b6c-a99f-4a2f58f6ba64",
    "routingWeight": 10,
    "sharedKey": null,
    "tags": {},
    "tunnelConnectionStatus": null,
    "type": "Microsoft.Network/connections",
    "virtualNetworkGateway1": {
      "activeActive": null,
      "bgpSettings": null,
      "enableBgp": null,
      "etag": null,
      "gatewayDefaultSite": null,
      "gatewayType": null,
      "id": "/subscriptions/d6ff83d6-713d-41f6-a025-5eb76334fda9/resourceGroups/Vnet-Vnet/providers/Microsoft.Network/virtualNetworkGateways/GWVNet2",
      "ipConfigurations": null,
      "location": null,
      "name": null,
      "provisioningState": null,
      "resourceGroup": "Vnet-Vnet",
      "resourceGuid": null,
      "sku": null,
      "tags": null,
      "type": null,
      "vpnClientConfiguration": null,
      "vpnType": null
    },
    "virtualNetworkGateway2": {
      "activeActive": null,
      "bgpSettings": null,
      "enableBgp": null,
      "etag": null,
      "gatewayDefaultSite": null,
      "gatewayType": null,
      "id": "/subscriptions/d6ff83d6-713d-41f6-a025-5eb76334fda9/resourceGroups/Vnet-Vnet/providers/Microsoft.Network/virtualNetworkGateways/GWVNet1",
      "ipConfigurations": null,
      "location": null,
      "name": null,
      "provisioningState": null,
      "resourceGroup": "Vnet-Vnet",
      "resourceGuid": null,
      "sku": null,
      "tags": null,
      "type": null,
      "vpnClientConfiguration": null,
      "vpnType": null
    }
  }
]
aanandr@AANANDR-WORK11:/mnt/c/Users/aanandr$

**Comment by tjprescott** [comment]
As pointed on in #1615, these are the values returned by the server. Since the service does not support the `expand` parameter for this endpoint, we would have to make additional REST calls to retrieve these values. You should file a bug against the REST api specs to support the expand parameter:
https://github.com/Azure/azure-rest-api-specs

**Comment by aanandr** [comment]
Travis – in the absence of the capability we shouldn’t attempt to even display all the GW configuration. You can just point to the GW JSON like PS does or you can just specify the GW ID or name. That’s a much better looking output.
