### ISSUE TITLE
Incorrect/Missing documentation for az ml workspace create

### ISSUE THREAD

**Issue by Broomhilde** [Azure/azure-cli#20614]
1. az ml workspace create --resource-group
                       [--file,]
                       [--location]
                       [--no-wait]
                       [--set]
                       **[--workspace-name]   --> [--name]**   needs correction in the documentation (in multiple locations)

2. az ml workspace create **--exist-ok**     is missing in new version of CLI

**Comment by jiasli** [comment]
@azureml-github, please help take a look.

**Comment by deeikele** [comment]
@Broomhilde Thank you for your feedback! Could you tell me more on the scenario you are looking to accomplish? Are you looking to update some of the workspace properties? Similar az ml update commands exist and may help accomplish that scenario.

**Comment by amitsood** [comment]
Yeah same issue when i try to create a workspace for my Machine learning pipeline. 
The documentation says "[--workspace-name]" but  accepts "[--name]"
**Below is working** 
az ml workspace create -g $(ml.resourceGroup) --name $(ml.workspace) -l $(ml.region)

**Comment by deeikele** [comment]
Thank you @jiasli @amitsood @dsandii for your feedback! We will update the documentation. There's no substitute for --exist-ok at this moment. You could check whether a workspace exist by evaluating if the following command returns a non-empty list _az ml workspace list --query "[?name=='workspacename']"_. We'll look at introducing an 'az ml workspace exists' parameter in consistency with az group exists command.

**Comment by Broomhilde** [comment]
@deeikele Thank you, ` We'll look at introducing an 'az ml workspace exists' parameter in consistency with az group exists command.`
I would highly appreciate this optimal solution.

**Comment by kapoor1992** [comment]
@deeikele is there a feature ticket for `--exist-ok` out there? It's a shame that we're auto-upgraded to a version in Azure DevOps which doesn't even have full functionality for us to cleanly change our API calls.

**Comment by deeikele** [comment]
@kapoor1992 Yes, we are tracking a feature item to add az ml workspace exists per above comments. Could you please share how you are installing the ML CLI on your build agents? Please note that he CLI v2 is under preview status and requires a different azure cli extension name (v1: azure-cli-ml, v2: ml) to install https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli.

**Comment by deeikele** [comment]
@kapoor1992 Could you please clarify how you depend on --exist-ok today to help us understand your scenario?

**Comment by kapoor1992** [comment]
Thanks for the reply @deeikele. I took another closer look at our YAML and it looks like the auto-upgrade was *not* for the azure-cli-ml version but another module (causing pain points with something else), apologies on the wrong information there.

To answer your other question, we currently issue the command `ml workspace create` with `--exist-ok` to create a workspace and just move on if it's already there. We now get an error since `--exist-ok` is gone, so what we're in the process of testing is listing out the workspaces and only issuing the `create` command if it isn't there. Just more steps is all to get around the missing argument which IMO was more elegant. Hope this helps.

**Comment by deeikele** [comment]
Thanks for the added context @kapoor1992. I understand the current workaround would require more logic at this moment. With the workspace exist command to come we should have a one-liner approach again, but also consistency with other cli experiences. Hope that provides more elegance and fits your approach.

**Comment by luigiw** [comment]
@kapoor1992 I'm curious what do you think if we make `--exit-ok` the default behavior? i.e. the create command doesn't raise an error if an existing workspace is found.

**Comment by kapoor1992** [comment]
@luigiw that makes sense to me, as long as there's some logging output like "Workspace already found with these settings, ignoring". Side note, but is the codebase for this extension open source? I'd be interested in seeing it if so (I can't find it) and possibly contributing.

**Comment by luigiw** [comment]
@kapoor1992 Thx for your response. In case of the existing workspace having some different settings, do you prefer an error or override?

We do have a plan to open source the extension code, it will likely come in the next 6 month.

**Comment by kapoor1992** [comment]
@luigiw IMO override seems like it makes sense if the output tells what was changed.
