### ISSUE TITLE
FunctionApp:func azure functionapp publish timeouts with "Updating Application Settings for Remote build..." message

### ISSUE THREAD

**Issue by ljorquera** [Azure/azure-cli#20627]
**When installing Python functions for a function app, sometimes the tool timeouts after printing 'Updating Application Settings for Remote build... ' message**

**Just run the following command from the Azure Functions folder:
 func azure functionapp publish dt-shao2-vi-rest-function-app-uspklrodz4yzi --python
**

**The call should just create the functions and not timeout. In fact, re running the command without any changes often does that**

**This happens both in Linux (zsh) and Windows, installing the later version**

**Comment by jiasli** [comment]
Adding service team to take a look.

**Comment by panchagnula** [comment]
This is related to funccli & not azure-cli please report to the right GitHub project. Thanks!
