### ISSUE TITLE
Missing required parameters in az account lock

### ISSUE THREAD

**Issue by bigdatamoore** [Azure/azure-cli#20633]
The documentation and help for the following commands is not correct.  

az account lock delete
az account lock show
az account lock update

Per the docs, these all have no required parameters, however the --name parameter is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95f0c0b1-af08-4ac0-fafa-35878fba3d02
* Version Independent ID: 86ba5e1f-9b7d-a329-d7d4-e6134e7afab6
* Content: [az account lock](https://docs.microsoft.com/en-us/cli/azure/account/lock?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/account/lock.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/account/lock.yml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
Adding @zhoxing-ms to help investigate.

**Comment by zhoxing-ms** [comment]
@bigdatamoore In fact, `--name` is not a required parameter for those commands. When you use `--ids` parameter, you don't need to pass in `--name`. 
Please note that specifying resources by `--name` or `--ids` is a common behavior in CLI

**Comment by bigdatamoore** [comment]
Ok thanks.  I misunderstood.  So one of those two are required then.   I guess there is no way in the docs to easily specify that.
________________________________
