### ISSUE TITLE
Static IP Configuration + ASG Support + NicName Windows Powershell Request

### ISSUE THREAD

**Issue by Wistlie** [Azure/azure-cli#20639]
**Resource Provider**

Microsoft.Network
**Description of Feature or Work Requested**

https://microsoft.sharepoint.com/:p:/t/Aznet/EbMWSK_OqjJCkMKbe24RcEUB3veFnnnjnlaz7-MdqNurcw?e=fx1ZGd
Static IP configurations - Way for customers to specify Network interface ip configurations for their private endpoint
Networkinterface name - way for customers to specify private endpoint network interface's name
Application Security Group - way for customers to specify rules for their networkinterface from Private Endpoint
**Minimum API Version Required**

2021-03-01 - Static IP Configuration, ASG Support
2021-05-01 - Custom Nic Name
**Swagger Link**

https://github.com/Wistlie/azure-rest-api-specs/tree/shbaden-nicname-changes-8/4 - Custom Network Interface Name
https://github.com/Azure/azure-rest-api-specs/pull/14662 - Static Ip Configurations 
https://github.com/Azure/azure-rest-api-specs/pull/14620 - Application Security Groups

**Target Date**

ASAP (Before 12/15)

**Comment by kairu-ms** [comment]
Network
