### ISSUE TITLE
SIG soft delete CLI fix

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#20658]
**Resource Provider**

Azure Compute

**Description of Feature or Work Requested**

Currently when user creates a new gallery without properties, the softDeletePolicy is null, however, if user does a 'az sig update' call on this gallery, the input softDeletePolicy is not null, it is the default value, this needs to be fixed. When user does update, the input SoftDeletePolicy needs to be null too.

**Minimum API Version Required**

2021-03-01

**Swagger Link**

**Target Date**

Next sprint release

**Comment by jiasli** [comment]
Adding @zhoxing-ms to help with with issue.

**Comment by zhoxing-ms** [comment]
Related PR #19569
