### ISSUE TITLE
Running 'az aks' with no command or additional arguments attempts to do a delete and throws giant stack trace

### ISSUE THREAD

**Issue by dumez-k** [Azure/azure-cli#20657]
## Describe the bug

**Command Name**
`az aks`

**Errors:**
```
The operation 'azure.mgmt.containerservice.v2020_09_01.operations._managed_clusters_operations#ManagedClustersOperations.delete' is invalid.
Traceback (most recent call last):
azure/cli/core/__init__.py, ln 831, in get_op_handler
    op = getattr(op, part)
AttributeError: type object 'ManagedClustersOperations' has no attribute 'delete'

...

azure/cli/core/__init__.py, ln 836, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.mgmt.containerservice.v2020_09_01.operations._managed_clusters_operations#ManagedClustersOperations.delete' is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Freshly installed az cli
- `az aks`

## Expected Behavior
Not to throw a giant error stack trace, also apparently trying to do a delete? Why is it trying to do a delete? I just ran `az aks`.

## Environment Summary
```
Linux-5.10.47-linuxkit-x86_64-with-glibc2.31
Python 3.9.2
Installer: DEB

azure-cli 2.18.0 *

Extensions:
azure-devops 0.19.0

```

**Comment by jiasli** [comment]
`azure-cli 2.18.0 *` running on `Python 3.9.2` is not maintained by Microsoft. Please see https://github.com/Azure/azure-cli/issues/19640.

**Comment by navba-MSFT** [comment]
@dumez-k Could you please make use of [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of CLI and [upgrade Python Libraries](https://www.python.org/downloads/) and let us know if that helps ? Awaiting your reply.
