### ISSUE TITLE
Support for VMSizecustomization for VM (high priority)

### ISSUE THREAD

**Issue by raktdas** [Azure/azure-cli#20655]
**Is your feature request related to a problem? Please describe.**

Starting from the latest General Purpose VM Sizes (Fsv2, Dsv3, Esv3, Dsv4, Esv4, Dasv4, Easv4), we have released hyperthreaded VMs for customers who have applications that need to maximize the full physical core for performance on the VM sizes (e.g. Electronic Design Automation (EDA) Application), they would like the ability to disable hyperthreading on their VMs. Customer can only get this done by filing a support ticket to CSS which are both costly to Microsoft as well as to our customers. One of the features that we like to enable is to provide customer the ability to disable hyperthreaded on their VMs at the time of creation.

Another issue that we would like to address and as part of the first phase of the VM customization is allow customization of the “constrained core counts” which will help to optimize the database licensing cost like Oracle that our customers need to pay for. Our customers required VM size that will provide them with a certain memory and IOPs throughput but not necessary the large amount of the vCPU count to run their application on. The only VM size options are the pre-defined VM size that has the largest vCPU count to achieve the memory or IOPs that they need, even though they are willing to pay for the Compute cost for that VM size but the database licensing cost which calculated based on the vCPU count will add huge amount of the additional cost that has a large impact of their business. This is the first step that will provide benefits to our customers who need help to reduce their database licensing cost.

**Describe the solution you'd like**
vCPUsAvailable and vCPUsPerCore propertes are strings. Users can specify these property when creating a new VM, or when updating an existing VM.

**Additional context**

Complete Swagger changes for this feature request are below:
https://github.com/Azure/azure-rest-api-specs/pull/14785

Resource Provider
Compute Resource Provider

Minimum API Version Required

2021-07-01

Target Date

We would like to for Public Preview in Early January and planning for the GA in March.
we are on a tight deadline.

**Comment by jiasli** [comment]
Adding @zhoxing-ms to help.

**Comment by zhoxing-ms** [comment]
> vCPUsAvailable and vCPUsPerCore propertes are strings. Users can specify these property when creating a new VM, or when updating an existing VM.

@raktdas  So we need to support those new parameters on commands `az vm create` and `az vm update`, right?
By the way, may I ask do you have any designs for naming those parameters?

**Comment by raktdas** [comment]
> > vCPUsAvailable and vCPUsPerCore propertes are strings. Users can specify these property when creating a new VM, or when updating an existing VM.
> 
> @raktdas So we need to support those new parameters on commands `az vm create` and `az vm update`, right? By the way, may I ask do you have any designs for naming those parameters?

@zhoxing-ms Yes you are right, we need to support new parameters on the create and update. I would like to add parameters vCPUsPerCore and vCPUsAvailable as parameters.
