### ISSUE TITLE
GA az storage copy command

### ISSUE THREAD

**Issue by amishra-dev** [Azure/azure-cli#20666]
**Is your feature request related to a problem? Please describe.**
az storage copy uses azcopy which is GA. removing the preview message from this command will give confidence to more people to use it.

**Describe the solution you'd like**
The preview message removed

**Describe alternatives you've considered**

**Additional context**

**Comment by jiasli** [comment]
Thanks @evelyn-ys for handling this issue.

**Comment by evelyn-ys** [comment]
Has planned in this sprint
