### ISSUE TITLE
Azure CLI bug

### ISSUE THREAD

**Issue by hendersonmersedes** [Azure/azure-cli#20660]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Cannot complete azure exercise due to CLI not comprehending my app name
**To Reproduce**

**Expected behavior**

I justwant to be able to finish.

**Environment summary**

**Additional context**

**Comment by jiasli** [comment]
To help us better understand you problem, please share 

1. the "exercise" you followed
2. the Azure CLI command you used
3. the error message you see

**Comment by hendersonmersedes** [comment]
Hello,

I attached a screenshot of the message I received after completing the
exercise. I used the code that was provided. The only modifications that
were made, was changing the name of the storage group to a unique name. Now
I have a blank screen when going to my profile. I cannot even get to the
Azure Developer cloud challenge.

**Comment by hendersonmersedes** [comment]
Hello,

This is the code provided in the exercise.

az storage account create \
  --kind StorageV2 \
  --resource-group [sandbox resource group name] \
  --location centralus \
  --name [your-unique-storage-account-name]

The only modifications that were made was changing the name of the storage
account to a unique name.

I have attacked screenshots of the name of the exercise and the error
message.

**Comment by jiasli** [comment]
> I attached a screenshot of the message I received after completing the exercise.

We can't see your screenshot in this issue https://github.com/Azure/azure-cli/issues/20660.

Please directly reply to this issue in a web browser, instead of using email. Thanks.

**Comment by hendersonmersedes** [comment]
It's fixed now. Thanks.
