### ISSUE TITLE
Upgrade AzCopy to the latest in the installer

### ISSUE THREAD

**Issue by amishra-dev** [Azure/azure-cli#20662]
**Is your feature request related to a problem? Please describe.**
AzCopy that ships with azcli is v10.5, there have been multiple perf improvements and features added. kindly upgrade the version

**Describe the solution you'd like**
azcopy move to the latest version 10.13

**Describe alternatives you've considered**
manually replacing the exe but that is not scalable to tell all customers

**Additional context**

**Comment by jiasli** [comment]
Thanks @evelyn-ys for handling this issue.

**Comment by evelyn-ys** [comment]
Has planned in this sprint
