### ISSUE TITLE
Allow new license type values for Linux Images

### ISSUE THREAD

**Issue by mathapli** [Azure/azure-cli#20667]
For Red Hat images

RHEL_BASE 
RHEL_SAPAPPS
RHEL_SAPHA
RHEL_EUS

FOR SLES/SUSE images
SLES_BASE
SLES_SAP
SLES_HPC

**Comment by zhoxing-ms** [comment]
@mathapli Hi, I have a question: in the previous PR, `RHEL_ELS_6` is added only for `az vm update`. Do we still need to keep this logic? Or let both `az vm/vmss create` and `az vm/vmss update` support `RHEL_ELS_6`?

**Comment by mathapli** [comment]
Please allow these values for both VMs and VMSS

**Comment by zhoxing-ms** [comment]
@mathapli  OK, how about `RHEL_ELS_6`? Should both az vm/vmss create and az vm/vmss update support RHEL_ELS_6?

**Comment by mathapli** [comment]
Please allow RHEL_ELS_6 for both.

**Comment by mathapli** [comment]
@zhoxing-ms please update the allowed value
SLES_BASE should not be allowed
Instead SLES_STANDARD should be allowed

**Comment by zhoxing-ms** [comment]
@mathapli I have modified it in #20765. please review whether the license types in this PR meets your expectations

**Comment by mathapli** [comment]
Approved

**Comment by mathapli** [comment]
@zhoxing-ms 
Thanks you for all the help
Can you allow the following two license types as well?
RHEL_BASESAPAPPS
RHEL_BASESAPHA

**Comment by zhoxing-ms** [comment]
＠mathapli It seems that license type needs to be modified frequently, and it only needs to modify one line of code. 
Do you mind submitting PR to modify it? If so, I can review and merge the PR for you, I think this may be a more efficient way.

Please refer to https://github.com/Azure/azure-cli/pull/20765/files for modifications
