### ISSUE TITLE
Generate Azure CLI for Microsoft.EdgeOrder

### ISSUE THREAD

**Issue by sojain** [Azure/azure-cli#20671]
**Resource Provider**
Microsoft.EdgeOrder

**Description of Feature or Work Requested**
Generate CLI for it. https://review.docs.microsoft.com/en-us/azure/azure-edge-hardware-center/?branch=pr-en-us-177860

**Minimum API Version Required**
2021-12-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2021-12-01

**Target Date**
GA date is 17 Jan

**Comment by jiasli** [comment]
Adding @kairu-ms to help.

**Comment by kairu-ms** [comment]
Hi @sojain, we have limited bandwidth to do it this month. Could we work on it in next month?

**Comment by chasewilson** [comment]
Hey @kairu-ms, After talking with the team. This timeline will work. I'll place it in next months milestone. 

@sojain feel free to respond here with any questions or concerns.
