### ISSUE TITLE
Webapp:az webapp up - zip deployment failed

### ISSUE THREAD

**Issue by kayceegu** [Azure/azure-cli#20674]
## Describe the bug
ReactJS deployment - Zip deployment failed.

**Command Name**
`az webapp up`

**Errors:**
```
Zip deployment failed. {'id': '7d8a6658659944e5a02b2b7c07225974', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2021-12-09T14:06:00.9192897Z', 'start_time': '2021-12-09T14:06:02.4144008Z', 'end_time': '2021-12-09T14:08:14.4248797Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://interpre-x.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://interpre-x.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'interpre-x'}. Please run the command az webapp log deployment show -n interpre-x -g appsvc_linux_centralus

```
When I ran the suggested command, I got the following:

Command group 'webapp log deployment' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
[
{
"details_url": null,
"id": "08d1c08a-b3f3-4b0b-ace1-2c906489804a",
"log_time": "2021-12-09T14:06:01.0954111Z",
"message": "Updating submodules.",
"type": 0
},
{
"details_url": null,
"id": "dad927a7-7b83-40d2-947f-fb0cc99e9e4e",
"log_time": "2021-12-09T14:06:02.3145311Z",
"message": "Preparing deployment for commit id '7d8a665865'.",
"type": 0
},
{
"details_url": null,
"id": "a49b8b81-3c73-42c6-bc5b-39c34d3c1fb4",
"log_time": "2021-12-09T14:06:03.5798031Z",
"message": "Repository path is /tmp/zipdeploy/extracted",
"type": 0
},
{
"details_url": "https://interpre-x.scm.azurewebsites.net/api/deployments/7d8a6658659944e5a02b2b7c07225974/log/42a078f2-1090-4711-aaf6-db66fd466f68",
"id": "42a078f2-1090-4711-aaf6-db66fd466f68",
"log_time": "2021-12-09T14:06:03.6783993Z",
"message": "Running oryx build...",
"type": 2
}
]

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- az webapp up --sku F1 --name interpre-x --location centralus -r "node|14-lts" -g appsvc_linux_centralus
- 
## Environment Summary
```
azure-cli 2.31.0

```

**Comment by jiasli** [comment]
Adding service team to help.

**Comment by kayceegu** [comment]
Just to add: I'm using the latest version of CLI (azure-cli 2.31.0) and I'm running the command from the folder where the root is present. 

I then tried to deploy via zip, the deployment was successful (message below) but the site still isn't working.

Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
{
  "active": true,
  "author": "N/A",
  "author_email": "N/A",
  "complete": true,
  "deployer": "Push-Deployer",
  "end_time": "2021-12-09T19:52:04.4994992Z",
  "id": "535b5de8d2484e119feaa60963b2d8ed",
  "is_readonly": true,
  "is_temp": false,
  "last_success_end_time": "2021-12-09T19:52:04.4994992Z",
  "log_url": "https://interpre-x.scm.azurewebsites.net/api/deployments/latest/log",
  "message": "Created via a push deployment",
  "progress": "",
  "received_time": "2021-12-09T19:52:02.1058292Z",
  "site_name": "interpre-x",
  "start_time": "2021-12-09T19:52:03.5209664Z",
  "status": 4,
  "status_text": "",
  "url": "https://interpre-x.scm.azurewebsites.net/api/deployments/latest"
}

**Comment by Kotasudhakarreddy** [comment]
@kayceegu - Please diagnose the application using a built-in logging mechanism provided. For more details go through [this](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs) article.

**Comment by kayceegu** [comment]
I managed to find the issue - turns out there was a Google Analytics node module preventing it from successful deployment. Once I uninstalled the module, I was able to deploy without a problem.
