### ISSUE TITLE
Az Cli issue 

### ISSUE THREAD

**Issue by hanurao55** [Azure/azure-cli#20672]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-5.4.0-1064-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.30.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.8

```

**Comment by jiasli** [comment]
Please share more details and errors you see.
