### ISSUE TITLE
Azure Image Builder API 2021-10-01 Release

### ISSUE THREAD

**Issue by zdelacerda-microsoft** [Azure/azure-cli#20680]
**Resource Provider**
Azure VM Image Builder

**Description of Feature or Work Requested**
We now support the option for customers to specify a ProxyVmSize and any UserAssignedIdentities during template creation.

changes:

2 new parameters for `az image builder create` 
   - `--proxy-vm-size <string>`, type <string>, example inputs: "Standard_A1_v1" 
   - `-build-vm-identities <string[]>`, type array of string, example: [subscriptions/SUBSCRIPTION/resourceGroups/IDENTITY_RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/MANAGED_IDENTITY]

Restrictions:
 --proxy-vm-size will only be used when --subnet is provided
  

**Minimum API Version Required**
2021-10-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/16669

**Target Date**

12/14/2021

**Comment by jiasli** [comment]
Adding @zhoxing-ms to help.

**Comment by zhoxing-ms** [comment]
@zdelacerda-microsoft Since the swagger of this PR seems to change a lot, it seems to be a big demand.
Could you please explain the design of specific commands and parameters that need CLI support?

**Comment by zdelacerda-microsoft** [comment]
> 

Hi @zhoxing-ms, we just need to upgrade the api-version for Microsoft.VirtualMachineImages. Thanks!

**Comment by zhoxing-ms** [comment]
@zdelacerda-microsoft  Thank you for your clarification. We plan to release it on **2022-02-01**, do you think this date is acceptable?

**Comment by zdelacerda-microsoft** [comment]
Hi @zhoxing-ms, there are actually 2 features that i missed. I will update the issue.

**Comment by zhoxing-ms** [comment]
@zdelacerda-microsoft OK, it would be better if there are the designs for specific commands and parameters. Thank you

**Comment by zdelacerda-microsoft** [comment]
@zhoxing-ms, the description has been updated. 2022-02-01 will work, however we already have SDKs updated so the earlier the better. Let me know if you need anything else from me. Thanks!

**Comment by zhoxing-ms** [comment]
@zdelacerda-microsoft Sorry, the date of the milestone is wrong because it ignores the Chinese Spring Festival
Since we have arranged other projects this year, after which we will experience Christmas, New Year's day and Chinese Spring Festival holiday, so the release time of the next sprint is In early February (about **02-08**), may I ask is this date acceptable?

**Comment by zdelacerda-microsoft** [comment]
Hi @zhoxing-ms the release of this api was supposed to be October 2021. Due to delays, we are already very behind schedule, if possible it would be great to move the release time as early as possible. If the earliest you can do is 02-08 then it is acceptable. Thank you!
