### ISSUE TITLE
[BotService] Http body should align with the http method (PUT or PATCH) to decide whether to update incrementally or fully 

### ISSUE THREAD

**Issue by Danieladu** [Azure/azure-cli#20697]
**Describe the bug**
We are using "Az bot update" to update the bot info. It works fine when the update operations are serial. 
But once the two updates are performed at the same time, one result would totally override the other one. Is does not make sense, 
because the properties they update do not with same.

**To Reproduce**
Open two terminals and run the command "az bot update" at the same time, one command updates displayName, the other one updates endpoint, you always could find that only one property is updated successfully.

**Expected behavior**
Both the properties would be updated successfully.

**Additional context**
I found the update logic code here: https://github.com/Azure/azure-cli/blob/e5450560db1fa3e8f15cabc91cadf81689aee01e/src/azure-cli/azure/cli/command_modules/botservice/custom.py#L693
It shows that, before update/patch, client would go through a "GET" request to get the bot info, and then assign the bot properties to "PUT/PATCH" body, is it not right.
In my opinion, if the http method is "PUT", a full bot info should be provided, but if the method is PATCH, only additional property should be provided, otherwise, there would exist A -> B -> A issue.
Notice that "az bot update" is a "PATCH" operation.

**Comment by jiasli** [comment]
Routing to service team.
