### ISSUE TITLE
Front-Door routing-rule Unable to update frontend-endpoints

### ISSUE THREAD

**Issue by Poil** [Azure/azure-cli#20706]
Hi,

When I want to add a frontend-endpoint to an existant routing-rule, if using this

```
'network', 'front-door', 'routing-rule', 'update',
                             '--front-door-name', fd,
                             '--resource-group', rg,
                             '--name', rr_name,
                             '--forwarding-protocol', 'HttpOnly',
                             '--caching', caching,
                             '--frontend-endpoints', fqdns
```

I got this error `conflicts with same or another RoutingRule that has the same AcceptedProtocol, FrontendEndpoint, and PatternsToMatch in the same Front Door`

But the conflicting domain is the one that are already set to this routing-rule

I think I should use "--set" or "--add" options but it looks like really complicated to just add a frontend-endpoint to an existant routing-rule ?

Best regards

**Comment by jiasli** [comment]
Adding @kairu-ms to help.

**Comment by YuanyuanNi** [comment]
'--frontend-endpoints' is a required parameters when creating a routing-rule, so user could not use 'update'  command to add a new one

**Comment by Poil** [comment]
So how to do ?

**Comment by YuanyuanNi** [comment]
You can try to use '--frontend-endpoints DefaultFrontendEndpoint'

**Comment by Poil** [comment]
Hi,

Sorry I don't understand: what I want is to add a new FrontendEnpoint to an existent routing rules ?

Regards

**Comment by YuanyuanNi** [comment]
Hi,  Poil:
     You can refer below doc:
https://docs.microsoft.com/en-us/cli/azure/network/front-door/frontend-endpoint?view=azure-cli-latest#az_network_front_door_frontend_endpoint_create
Best wishes.

**Comment by Poil** [comment]
Hi,

Still not what I want, sometime I think my english is very bad :x

"Add a new FrontendEnpoint to an existent routing rules"

Best regards

**Comment by kairu-ms** [comment]
Hi @Poil, we cannot reproduce the issue. As error message show there may be some another RoutingRule that has the same AcceptedProtocol, FrontendEndpoint, and PatternsToMatch in the same Front Door. So could you run command `az network front-door routing-rule list --front-door-name your-front-name -g your-resource-group-name` to check above properties accross ruls first?

**Comment by kairu-ms** [comment]
If you want to add new FrontedEndpoint of an existing routing rules, you should pass the whole array (including new and the old ones) in `--frontend-endpoints` parameter.
