### ISSUE TITLE
Fail to unpickle `msal_http_cache.bin`: EOFError: Ran out of input

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#20707]
Removed `~/.azure` and tried again. Same issue happens:

```
│ Error: unable to get authorization token for resource manager: Error obtaining Authorization Token from the Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: ERROR: The command failed with an unexpected error. Here is the traceback:
│ ERROR: Ran out of input
│ Traceback (most recent call last):
│   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
│     cmd_result = self.invocation.execute(args)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
│     raise ex
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
│     results.append(self._run_job(expanded_arg, cmd_copy))
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
│     result = cmd_copy(params)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
│     return self.handler(*args, **kwargs)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
│     return op(**command_args)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 77, in get_access_token
│     tenant=tenant)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 383, in get_raw_token
│     credential = self._create_credential(account, tenant)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 593, in _create_credential
│     return identity.get_user_credential(username_or_sp_id)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 209, in get_user_credential
│     return UserCredential(self.client_id, username, **self._msal_app_kwargs)
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 84, in _msal_app_kwargs
│     Identity._msal_http_cache = self._load_msal_http_cache()
│   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 113, in _load_msal_http_cache
│     persisted_http_cache = pickle.load(f)
│ EOFError: Ran out of input
│ To open an issue, please run: 'az feedback'
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on terraform_config.tf line 13, in provider "azurerm":
│   13: provider "azurerm" {
```

_Originally posted by @edvinas31 in https://github.com/Azure/azure-cli/issues/20252#issuecomment-992255336_

**Comment by jiasli** [comment]
According to our implementation:

https://github.com/Azure/azure-cli/blob/713b0edca860a8e4037bfc865d847b945fb12886/src/azure-cli-core/azure/cli/core/auth/identity.py#L106-L123

It is very unusually for `~/.azure/msal_http_cache.bin` to be empty. Does it work if you manually run `az` commands without Terraform?

**Comment by rayluo** [comment]
> According to our implementation:
> 
> https://github.com/Azure/azure-cli/blob/713b0edca860a8e4037bfc865d847b945fb12886/src/azure-cli-core/azure/cli/core/auth/identity.py#L106-L123
> 
> It is very unusually for `~/.azure/msal_http_cache.bin` to be empty. Does it work if you manually run `az` commands without Terraform?

@jiasli , given that this happens in Terraform, which is now known to have high concurrency pattern, now I suspect that our [naive http_cache pattern at line 117 & 121](https://github.com/Azure/azure-cli/blob/713b0edca860a8e4037bfc865d847b945fb12886/src/azure-cli-core/azure/cli/core/auth/identity.py#L117-L121) could encounter a race condition, when `open(_cache_file, 'rb')` created an empty file but `pickle.dump(...)` has not yet start writing. :-(

So, the workaround would happen to be also catch `EOFError` at line 114.

But then, thinking one step ahead, there will probably still be some other exception, if/when the `pickle.load(...)` happens to read some incomplete content written by an in-progress `pickle.dump(...)`. We might have to change line 114 to a broad `except Exception`, despite I/we previously thought it was unnecessary. :-(

**Comment by edvinas31** [comment]
> According to our implementation:
> 
> https://github.com/Azure/azure-cli/blob/713b0edca860a8e4037bfc865d847b945fb12886/src/azure-cli-core/azure/cli/core/auth/identity.py#L106-L123
> 
> It is very unusually for `~/.azure/msal_http_cache.bin` to be empty. Does it work if you manually run `az` commands without Terraform?

What exactly commands should I run to test that?

**Comment by jiasli** [comment]
> What exactly commands should I run to test that?

Any command would do.

**Comment by jiasli** [comment]
## Workaround

The easiest approach is to add `EOFError` here

https://github.com/Azure/azure-cli/blob/713b0edca860a8e4037bfc865d847b945fb12886/src/azure-cli-core/azure/cli/core/auth/identity.py#L114

The location of `identity.py` is shown in the call stack.

If that's not possible, you may install Azure CLI 2.30.0 which doesn't have MSAL HTTP cache enabled. See https://docs.microsoft.com/en-us/cli/azure/install-azure-cli.

**Comment by edvinas31** [comment]
> > What exactly commands should I run to test that?
> 
> Any command would do.

You can see my last ran commands here:

 az account list
 az vm list
 az acr list
 az sql server list
 az aks list
 az image list
 az container list

And none of it failed

**Comment by jiasli** [comment]
@edvinas31, this further validates our deduction - Terraform invokes Azure CLI in a way that a racing condition occurred. Could you follow https://github.com/Azure/azure-cli/issues/20707#issuecomment-993229576 and see if you can get unblocked?

**Comment by jiasli** [comment]
Meanwhile, I am proposing a more robust solution to this race condition in https://github.com/Azure/azure-cli/pull/20722.

**Comment by edvinas31** [comment]
> 

Actually it looks like it was just one time error. I deployed infrastructure with terraform few times back and fourth and it looks fine by now (I do not get same error againt). However, I will keep you updated in the next few days if something comes up again

**Comment by claudhg9** [comment]
Getting the same thing, just trying to do az login in WSL (Win 11):

`The command failed with an unexpected error. Here is the traceback:
Ran out of input
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 158, in login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 155, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 140, in login_with_auth_code
    "with `az login --use-device-code`.", self._msal_app.authority.authorization_endpoint)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 98, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 84, in _msal_app_kwargs
    Identity._msal_http_cache = self._load_msal_http_cache()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/auth/identity.py", line 113, in _load_msal_http_cache
    persisted_http_cache = pickle.load(f)
EOFError: Ran out of input`

**Comment by jiasli** [comment]
@claudhg9, did you somehow run `az` concurrently?

**Comment by claudhg9** [comment]
Yup, I had more than one WSL terminal open.

**Comment by kensykora** [comment]
I can confirm this is also happening with us, it occurs during `terraform plan` operations -- we have to create some calls to the azure CLI to work around limitations with azurerm terraform provider, and some of them run concurrently, so that is consistent with the hypotheses above. It can often take 2-3 attempts to get a successful deploy on Azure devops agents.

**Comment by rayluo** [comment]
> some of them run concurrently

@kensykora do you have a rough idea on how many concurrent `az` commands being run?

**Comment by kensykora** [comment]
Somewhere between 12-16 on our larger modules. 

We are calling the diagnostics API to retrieve available diagnostic options (logs, metrics) so we can make sure they're all enabled. 

Each set (metrics, logs) is an individual API call and we have about 8 applicable resources on our larger modules.
