### ISSUE TITLE
DedicatedHostReboot

### ISSUE THREAD

**Issue by vbhasker-msft** [Azure/azure-cli#20718]
**Resource Provider**

Microsoft.Compute

**Description of Feature or Work Requested**

The new API allows users to restart their dedicated host.

**Minimum API Version Required**

July 2021

**Swagger Link**

Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/16737
SDK PR: https://github.com/Azure/azure-sdk-for-net/pull/25258
Powershell Design: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1087

**Target Date**

January 2022

**Comment by zhoxing-ms** [comment]
@vbhasker-msft  The new commands and parameters that CLI needs to support are designed as follows. 

New command: `az vm host restart`
New parameters: `--resource-group/g`, `--dedicated-host-group`, `--dedicated-host`

Do you think this meet the expectations?

**Comment by zhoxing-ms** [comment]
@vbhasker-msft By the way, I plan to release this feature on **2022-02-01**, do you think this date is acceptable?

**Comment by vbhasker-msft** [comment]
@zhoxing-ms  Yes, that date is acceptable

Yep, those parameters are good.

**Comment by smotwani** [comment]
> @zhoxing-ms  Yes, that date is acceptable for me.
> 
> 
> 
> Yep, those parameters are good.
> 
> 
> 
> @smotwani Is this acceptable?

Yes, it is acceptable.

**Comment by PARADISSEEKR** [comment]
Hi, @vbhasker-msft , when I use `az vm host restart`, the service return `(BadRequest) Operation 'restart' is not supported on the resource 'my-host'`, are there any restrictions on the host? 

vm host info:
{
  "autoReplaceOnFailure": true,
  "hostId": "869e8e2d-5bd4-4cfc-a0d5-7da5064268e4",
  "id": "/subscriptions/mysub/resourceGroups/myrg/Microsoft.Compute/hostGroups/my-host-group/hosts/my-host",
  "instanceView": null,
  "licenseType": null,
  "location": "westus",
  "name": "my-host",
  "platformFaultDomain": 2,
  "provisioningState": "Succeeded",
  "provisioningTime": "2022-01-07T07:23:40.988401+00:00",
  "resourceGroup": "myrg",
  "sku": {
    "capacity": null,
    "name": "DSv3-Type1",
    "tier": null
  },
  "tags": {
    "foo": "bar"
  },
  "timeCreated": "2022-01-07T07:23:38.816516+00:00",
  "type": "Microsoft.Compute/hostGroups/hosts",
  "virtualMachines": [{
      "id": "/subscriptions/mysub/resourceGroups/myrg/providers/Microsoft.Compute/virtualMachines/myvm",
      "resourceGroup": "myrg"
    }]
}
