### ISSUE TITLE
az login fails after update: TypeError: __init__() got an unexpected keyword argument 'http_cache'

### ISSUE THREAD

**Issue by bj-tukker** [Azure/azure-cli#20723]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'http_cache'
Traceback (most recent call last):
  File "/home/bart/.local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 149, in login
    subscriptions = profile.login(
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 155, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/auth/identity.py", line 140, in login_with_auth_code
    "with `az login --use-device-code`.", self._msal_app.authority.authorization_endpoint)
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/auth/identity.py", line 98, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
  File "/home/bart/.local/lib/python3.8/site-packages/msal/application.py", line 1408, in __init__
    super(PublicClientApplication, self).__init__(
TypeError: __init__() got an unexpected keyword argument 'http_cache'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.3 LTS
Python 3.8.10
Installer: PIP

azure-cli 2.31.0

Extensions:
sentinel 0.1.1
dataprotection 0.2.0
log-analytics-solution 0.1.1
ssh 1.0.0

```

**Comment by jiasli** [comment]
You installed Azure CLI with `pip` but `msal` is not the one Azure CLI requires for some reason:

https://github.com/Azure/azure-cli/blob/d52397ab0f9e80c1f5e68e200ae66b6a272da0ac/src/azure-cli-core/setup.py#L55

Please install the last MSAL and retry.

**Comment by bj-tukker** [comment]
Tried that (sudo pip install msal)
`
Collecting msal
  Downloading msal-1.16.0-py2.py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 1.6 MB/s
Requirement already satisfied: PyJWT[crypto]<3,>=1.0.0 in /usr/lib/python3/dist-packages (from msal) (1.7.1)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/lib/python3/dist-packages (from msal) (2.22.0)
Requirement already satisfied: cryptography<38,>=0.6 in /usr/lib/python3/dist-packages (from msal) (2.8)
Installing collected packages: msal
Successfully installed msal-1.16.0
 bart  DESKTOP-TSL105M  mnt  c  Data  Repo  $  az login
The command failed with an unexpected error. Here is the traceback:
__init__() got an unexpected keyword argument 'http_cache'
Traceback (most recent call last):
  File "/home/bart/.local/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/command_modules/profile/custom.py", line 149, in login
    subscriptions = profile.login(
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 155, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/auth/identity.py", line 140, in login_with_auth_code
    "with `az login --use-device-code`.", self._msal_app.authority.authorization_endpoint)
  File "/home/bart/.local/lib/python3.8/site-packages/azure/cli/core/auth/identity.py", line 98, in _msal_app
    self._msal_app_instance = PublicClientApplication(self.client_id, **self._msal_app_kwargs)
  File "/home/bart/.local/lib/python3.8/site-packages/msal/application.py", line 1408, in __init__
    super(PublicClientApplication, self).__init__(
TypeError: __init__() got an unexpected keyword argument 'http_cache'
`

Also tried a re-install of azure-cli, but still the same error.

**Comment by jiasli** [comment]
```
/home/bart/.local/lib/python3.8/site-packages/msal/application.py", line 1408, 
in __init__ super(PublicClientApplication, self).__init__( 

TypeError: __init__() got an unexpected keyword argument 'http_cache'
```

In the error message, line 1408 of `msal/application.py` doesn't match the real MSAL:

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.16.0/msal/application.py#L1408

Perhaps you manually edited the MSAL package file?

Please try to force a reinstall:

```
pip install msal --force-reinstall
```

**Comment by rayluo** [comment]
> ```
> /home/bart/.local/lib/python3.8/site-packages/msal/application.py", line 1408, 
> in __init__ super(PublicClientApplication, self).__init__( 
> 
> TypeError: __init__() got an unexpected keyword argument 'http_cache'
> ```
> 
> In the error message, line 1408 of `msal/application.py` doesn't match the real MSAL:
> 
> https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.16.0/msal/application.py#L1408

I concur with @jiasli's triage. The msal used by @bj-tukker 's Az CLI is located at `/home/bart/.local/lib/python3.8/site-packages/msal/application.py`, whose line 1408 is different than the [real MSAL 1.16](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.16.0/msal/application.py#L1408).

I believe @bj-tukker 's installation method "**sudo** pip install msal" does NOT change his/her "**/home/bart**/.local/lib/python3.8/site-packages/msal/application.py". The **sudo** here will not magically make it right. Please try not using "sudo", @bj-tukker .

By the way, @jiasli , now that MSAL becomes one important component in Azure CLI. Shall we adjust `az --version` so that it will also display MSAL version number in the diagnose output?

**Comment by bj-tukker** [comment]
I didn't even know that msal was used, let alone that I changed anything there... :-) 
OK, the force helped, a bit; I can now run 'az login' again, but when trying to login to Azure (with MFA), I can select the user for the portal to use, but then the browser gives an error: ERR_CONNECTION_REFUSED. 

Device login works, however. Also, when doing the login from a Powershell session, with 'az login', that works, too.

**Comment by rayluo** [comment]
> I didn't even know that msal was used, let alone that I changed anything there... :-)

Fair point. Until @jiasli changes Azure CLI to also output the version of its MSAL component, there is currently one way to manually find out which version of MSAL your Azure CLI is using: you use any text editor to open this file (whose location is pinpointed by the exception trace) - `/home/bart/.local/lib/python3.8/site-packages/msal/application.py` - and then at around line 29 you will find its version declaration `__version__`.

That being said, ...

> OK, the force helped, a bit; I can now run 'az login' again,

... if you already did a `pip install -U msal` (or any equivalent command), and the initial "... http_cache ..." error message is now gone, you probably fix the msal versioning thing at this point. And we won't know why/how it went wrong in the first place. #shrug

> but when trying to login to Azure (with MFA), I can select the user for the portal to use, but then the browser gives an error: ERR_CONNECTION_REFUSED.
> 
> Device login works, however. Also, when doing the login from a Powershell session, with 'az login', that works, too.

Is that ERR_CONNECTION_REFUSED reproducible? If so, please share the steps to us.

(FWIW, if `az login` is being run inside a VM, it is probably unable to open a browser automatically, and even if you managed to open a browser manually, the browser won't be able to deliver the eventual authentication result back to Azure CLI running inside the VM. That is why `az login` would also print a hint beforehand, telling you to fallback to device login, which is less convenient but always works. - But, based on your initial report, you were using WSL2. Again, if you have steps to reproduce this, that would help our investigation a lot.)

**Comment by jiasli** [comment]
> Shall we adjust `az --version` so that it will also display MSAL version number in the diagnose output?

Currently Azure CLI always forces the latest MSAL version:

https://github.com/Azure/azure-cli/blob/d52397ab0f9e80c1f5e68e200ae66b6a272da0ac/src/azure-cli-core/setup.py#L55

Azure CLI packages released by us (DEB, RPM, docker image) all have a fixed MSAL version:

https://github.com/Azure/azure-cli/blob/58383c0a5cd72ffff9b84330d683706c47df0531/src/azure-cli/requirements.py3.Linux.txt#L114

So the MSAL version can be deducted from the Azure CLI version.

If a user installs Azure CLI with `pip` and hit MSAL versioning issues, he/she can always use `pip list` to find out the actual MSAL version installed.

**Comment by rayluo** [comment]
> > Shall we adjust `az --version` so that it will also display MSAL version number in the diagnose output?
> 
> Currently Azure CLI always forces the latest MSAL version:
> 
> https://github.com/Azure/azure-cli/blob/d52397ab0f9e80c1f5e68e200ae66b6a272da0ac/src/azure-cli-core/setup.py#L55
>
But that would already mean a pip-installed Azure CLI would use the latest MSAL available at the installation time, and won't be upgraded afterwards. Wouldn't it still be nice to have Azure CLI to print MSAL's version in its auto-generated Environment Summary?
 
> Azure CLI packages released by us (DEB, RPM, docker image) all have a fixed MSAL version:
> 
> https://github.com/Azure/azure-cli/blob/58383c0a5cd72ffff9b84330d683706c47df0531/src/azure-cli/requirements.py3.Linux.txt#L114
> 
> So the MSAL version can be deducted from the Azure CLI version.
> 
That is fair. But I still think a readily available diagnose output would be unbeatable in convenience.

> If a user installs Azure CLI with `pip` and hit MSAL versioning issues, he/she can always use `pip list` to find out the actual MSAL version installed.

In the current particular issue, at one point the msal was installed by a "**sudo** pip install msal", so a subsequent "pip list" and "**sudo** pip list" would probably show different results. Not every end user necessarily knows the difference. I'd still suggest Azure CLI to print the msal version it uses, as a single source of truth.

**Comment by bj-tukker** [comment]
Thanks @jiasli and @rayluo ; apparently a reboot fixed the login issue after installing the correct msal version.

**Comment by jiasli** [comment]
@rayluo, that makes sense. Let me do it in #20754.
