### ISSUE TITLE
[App Service] Allow configuring/detecting the current web app

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2072]
Similar to the request in #1377, it would be awesome if a user could also configure a default/current web app instance, so that they could use all of the `az appservice web` commands, without needing to specify either a resource group or a web app.
 
This would help improve the overall efficiency of the CLI, for scenarios where a dev is working exclusively with a specific web app, and therefore, shouldn't need to be explicit about the context we could otherwise infer. Many ubiquitous CLIs provide this kind of behavior, to enable an increased ergonomic experience.

I could see this either being a new setting of the `az configure` command, or a config file that is placed within the app directory itself. That way, when you `cd` into a project directory, it can automatically know which web app you're dealing with. I'm not too opinionated about the exact solution to this, but I would very much love to see `az appservice web` commands be usable without needing to specify the `-n` flag at all.

**Comment by yugangw-msft** [comment]
This one is resolved now by #2414
