### ISSUE TITLE
`az role definition create` propagation delay

### ISSUE THREAD

**Issue by grzn** [Azure/azure-cli#20727]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Running az role definition list returned mixed results right after creating a role using `az role definition create`:
Its as if the API requests reach different replicas in the backend, and they are out of sync.

Is there a way to wait/block on the replication to finish, so all the following requests will be consistent?

**To Reproduce**
```
$ az role definition create --role-definition @role.json
$ az role definition list --query '[?roleName=='\''TestCustomRol'\'']' --scope /providers/Microsoft.Management/managementGroups/devgroup
[]
$ az role definition list --query '[?roleName=='\''TestCustomRol'\'']' --scope /providers/Microsoft.Management/managementGroups/devgroup
[]
az role definition list --query '[?roleName=='\''TestCustomRol'\'']' --scope /providers/Microsoft.Management/managementGroups/devgroup
[
  {
    ...
  ]
]
$ az role definition list --query '[?roleName=='\''TestCustomRol'\'']' --scope /providers/Microsoft.Management/managementGroups/devgroup
[]
```

**Expected behavior**
What we want to is to wait until the role is synced and ready for use; how can we do that?

**Comment by jiasli** [comment]
The result of `az role definition list` comes from ARM service and Azure CLI just returns it as-is.

Does it eventually return the same result?

**Comment by grzn** [comment]
Eventually yes, but it takes time.
I understand that its a backend issue, because I guess there's no github repository for the API service, so I reported the issue here; can you find the PM/dev responsible for it and let him know of this issue?

**Comment by jiasli** [comment]
> can you find the PM/dev responsible for it and let him know of this issue?

@dagoroz, could you help take a look?

**Comment by grzn** [comment]
Hi @jiasli, do you have an updated on this for us?

**Comment by yonzhan** [comment]
ARM service team should take a look

**Comment by dagoroz** [comment]
the usual propagation delay is around 5 minutes
the absolute worse we've seen is 30 minutes but this is quite an uncommon scenario.

**Comment by jiasli** [comment]
As @dagoroz suggested, this is the **designed behavior of ARM**, and affects all client tools like Azure CLI, Azure PowerShell, SDKs, we will close this issue.
