### ISSUE TITLE
Missing dependency of `msrestazure` from `azure-cli-core`

### ISSUE THREAD

**Issue by irvokopo** [Azure/azure-cli#20732]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Is there a missing dependency?

**To Reproduce**

In this code CLoudError is imported from msrestazure: https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/commands/validators.py#:~:text=from%20msrestazure.azure_exceptions%20import%20CloudError 

**Expected behavior**

Should the 'msrestazure' package be listed as a dependency here: https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/setup.py#:~:text=%5D-,DEPENDENCIES%20%3D%20%5B,%5D,-%23%20dependencies%20for%20specific

**Environment summary**

**Additional context**

**Comment by jiasli** [comment]
@zhoxing-ms, is this line still valid after we migrate to Track 2 for `azure-mgmt-resource`?

https://github.com/Azure/azure-cli/blob/e3fb82480bfd34b6b42f2f5fb541f925a52eebf8/src/azure-cli-core/azure/cli/core/commands/validators.py#L74

**Comment by zhoxing-ms** [comment]
Good catch! I have submitted a PR #20739 to fix this issue

**Comment by irvokopo** [comment]
Hello,
Thank you very much for this!
Would it, maybe make sense to tackle similar usage of CloudError elsewhere as well, for e.g.:
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/util.py#:~:text=exceptions%20import%20JMESPathError-,from%20msrestazure.azure_exceptions%20import%20CloudError,-from%20msrest.exceptions

Thank you again!

**Comment by jiasli** [comment]
Actually we can't, as some SDKs are still on Track 1. Azure CLI needs to catch those `CloudError` so that Track 1 SDKs' exceptions can be correctly handled.

**Comment by irvokopo** [comment]
I see - thank you again for addressing the issue getting back to me - happy to have this closed : )

**Comment by irvokopo** [comment]
P.S.: Just to mention, I've had one other missing-dependency issue of 'packaging', from here:
https://github.com/Azure/azure-cli/blob/d52397ab0f9e80c1f5e68e200ae66b6a272da0ac/src/azure-cli-core/azure/cli/core/__init__.py#:~:text=from%20packaging.version%20import%20parse

**Comment by jiasli** [comment]
Ah, nice finding. I actually just bumped `packaging` recently: https://github.com/Azure/azure-cli/pull/20661

Just wondering how you are able to find those missing dependencies? 😸
