### ISSUE TITLE
Unable to enable addon for azure-keyvault-secrets-provider

### ISSUE THREAD

**Issue by JudasGeiten** [Azure/azure-cli#20742]
## Describe the bug

**Command Name**
`az aks enable-addons`

**Errors:**
```
'azure-keyvault-secrets-provider'
Traceback (most recent call last):
Temp\pip-install-0u_uiwkq\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 608, in execute
azure\cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 659, in _run_job
Local\Temp\pip-install-0u_uiwkq\six\six.py, ln 696, in reraise
azure\cli\core\commands\__init__.py, ln 636, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 493, in default_command_handler
azure\cli\command_modules\acs\custom.py, ln 1841, in aks_enable_addons
azure\cli\command_modules\acs\custom.py, ln 2188, in _update_addons
KeyError: 'azure-keyvault-secrets-provider'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az aks enable-addons --addons {} --name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.80

```

**Comment by phealy** [comment]
@JudasGeiten - you are running a version of Azure CLI that is almost two years old (2.0.80 was released in January 2020). As it's a new feature and per the documentation, [Azure Key Vault Provider requires a newer Azure CLI version of at least 2.30.0](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#:~:text=ensure%20that%20your%20version%20of%20the%20Azure%20CLI%20is%202.30.0%20or%20later) to be configured. Please follow the directions in the [Azure CLI documentation to update your client](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux) and reopen the issue if you still experience problems. Thanks!
