### ISSUE TITLE
az acr create should support associating a registry with a cluster

### ISSUE THREAD

**Issue by SteveLasker** [Azure/azure-cli#2074]
To assist in the initial configurations, az acr create could add a registry parameter that would associate a container registry with the cluster. The service principal would be registered with ACR with readonly permissions for docker pull. 
I'm not suggesting az acs create should create a registry as we expect customers to use registries across multiple services. In the Azure Portal we might optimize the creation of new, or link existing experiences. The additional parameters needed on az acs create to create a new registry feels more complicated than running that command prior then linking as a secondary command. 
```
--container-registry -r               : Associates a Service Principal between the cluster and the registry, providing docker pull capabilities. 
```

**Comment by davenemeth** [comment]
It would be nice, when you use only one container, but how would this work, when you need to pull from different container registries?

**Comment by SteveLasker** [comment]
Many clips support passing the same parameter  -r multiple times

**Comment by SteveLasker** [comment]
Clis

**Comment by SteveLasker** [comment]
As many services need access to a registry, we're inverting this model for the service to grant permission to the registry. the `az aks`, `az devops`, `az aci` and other services should add this capability. 
This is also blocked by the default ARM permissions being assigned to resources.
