### ISSUE TITLE
Error in using the command "az network private-endpoint-connection approve"

### ISSUE THREAD

**Issue by csj-cvation** [Azure/azure-cli#20752]
I tried using this command for a approving a private endpoint connection of type 'Microsoft.Sql/servers/'. I tried both by using the id of the connection and name, resource name and type. Same error:

**Bad Request({"error":{"details":[{"code":"InvalidResourceIdSegment","message":"","target":"parameters.properties.privateLinkServiceConnectionState"}],"code":"InvalidResourceIdSegment","message":"The 'parameters.properties.privateLinkServiceConnectionState' segment in the url is invalid."}})**

I tried the same command for a private endpoint connection with type 'Microsoft.DocumentDB/databaseAccounts' that worked fine. So it seems to be isolated to the type 'Microsoft.Sql/servers/'

**Comment by ZengTaoxu** [comment]
HI, @csj-cvation. May I ask how to reproduce the problem? 
By the way, which CLI version do you use?

**Comment by csj-cvation** [comment]
Im using CLI version 2.31.0
This command fails: az network private-endpoint-connection approve --id /subscriptions/*******/resourceGroups/*****/providers/Microsoft.Sql/servers/*****/privateEndpointConnections/*****
The id is a sql server private endpoint

**Comment by ZengTaoxu** [comment]
Hello, @csj-cvation. Your ID may be wrong. you should enter the command "az network private-endpoint-connection list -g MyResourceGroup -n MyServer --type Microsoft.Sql/servers" to get the ID, please try this command to see if you still have problems. @csj-cvation

**Comment by csj-cvation** [comment]
As mentioned in my initial description, I already tried that, same error

**Comment by ZengTaoxu** [comment]
Hello, @csj-cvation. Could you please provide relevant debug information?
By the way, After you enter the command 'az network private-endpoint-connection list', do you return the following information?
 "privateLinkServiceConnectionState": {
        "actionsRequired": "None",
        "description": "",
        "status": "Pending"
      }

**Comment by csj-cvation** [comment]
Im not sure i understand what more you need, but this is what you have to do:

1. Create a private endpoint for a SQL server
2. Try to approve it using Azure CLI with the command i wrote earlier
3. It fails with the error i wrote when i created the issue

Please go through this, because it WILL fail

**Comment by csj-cvation** [comment]
![image](https://user-images.githubusercontent.com/73532521/150750311-4e0b833d-5efc-49cd-9815-f5c5960a43bd.png)

**Comment by csj-cvation** [comment]
The command fails without the --description parameter

**Comment by ZengTaoxu** [comment]
Please add the parameter --description "Approved" and try again. This error should not be reported. Thank you!

**Comment by csj-cvation** [comment]
I guess its a usability issue. Its not stated that the description parameter is mandatory and it is not failing if you leave it out

**Comment by michaelhambe** [comment]
Any idea why the description parameter is required for authorising SQL private endpoints, but not for storage or keyvault endpoints?
