### ISSUE TITLE
az login error

### ISSUE THREAD

**Issue by madhusathya** [Azure/azure-cli#20758]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04A4B2E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0

```

**Comment by madhusathya** [comment]
Issue resolved by disabling the proxy which I haven't noticed before.
Thanks!!

**Comment by jiasli** [comment]
I provided some more details for troubleshooting this problem in https://github.com/Azure/azure-cli/issues/20367#issuecomment-972797022.
