### ISSUE TITLE
az acr task error when pulling data from github

### ISSUE THREAD

**Issue by 3rdmillkev** [Azure/azure-cli#20761]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I used the command below to create  2 acr tasks based on "push to source code" trigger:  
```
az acr task create `
    --registry myregistry `
    --name build-main`
    --image myimage-main:{{.Run.ID}} `
    --context https://github.com/$GIT_USER/acr-build-helloworld-node.git#main `
    --file Dockerfile `
    --git-access-token myonlytoken

az acr task create `
    --registry myregistry `
    --name build-dev`
    --image myimage-dev:{{.Run.ID}} `
    --context https://github.com/$GIT_USER/acr-build-helloworld-node.git#dev `
    --file Dockerfile `
    --git-access-token myonlytoken
```
Using the command above, I created 2 tasks on the same github private repository with same PAT token.  
The problem is, when running the " build-dev" task, it runs without no issues and image is built as expected but when running "build-main" task, it fails with this error:  
```
2021/12/15 21:43:23 Downloading source code...  
Run ID: cs1a failed after 5s. Error: failed to download context. Please check if the URL is incorrect. If it has credentials, please check if they are expired
```
my token has the below permissions:  
* repo
* repo:status
* repo_deployment
* public_repo
* repo:invite
* security_events
* workflow
* admin:repo_hook
* write:repo_hook
* read:repo_hook
* admin:org_hook

Also please note that there is no difference in source code in both #dev and #main branch.
I came to believe that there is a bug in the agent that it cannot download data from source code.
**To Reproduce**
since we are using private repo, I am not sure how to provide steps to reproduce. support can advise.

**Expected behavior**
The run should be successful on both "build-main" and "build-dev" task as they are in same repo, using same PAT and even source code is the same in both branches.

**Environment summary**
```
az acr task create `
    --registry myregistry `
    --name build-main`
    --image myimage-main:{{.Run.ID}} `
    --context https://github.com/$GIT_USER/acr-build-helloworld-node.git#main `
    --file Dockerfile `
    --git-access-token myonlytoken

az acr task create `
    --registry myregistry `
    --name build-dev`
    --image myimage-dev:{{.Run.ID}} `
    --context https://github.com/$GIT_USER/acr-build-helloworld-node.git#dev `
    --file Dockerfile `
    --git-access-token myonlytoken
```
* Pulling data from same repository
* Using same token for both tasks

**Additional context**

**Comment by jiasli** [comment]
Routing to service team.

**Comment by AntonioVT** [comment]
@3rdmillkev Could you try using the latest CLI? Current version is 2.31.0, but the one mentioned is 2.0.62.

**Comment by rosanch** [comment]
@3rdmillkev There used to be a bug in older CLI versions regarding the branching. So upgrading the CLI might fix the problem for you

**Comment by 3rdmillkev** [comment]
@AntonioVT @rosanch After updating the cli and recreating the build task, it was successful.
Thanks for your help
