### ISSUE TITLE
`az vm create` and `az vmss create` should allow you to specify secrets

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#2077]
In VM and VMSS creation we should be able to specify key vault secrets. This is significant for DevOpsSec scenarios where we need to have the secrets present prior to execution of the cloud-init script.

I'm not 100% sure how we should specify this on the command line and am open to suggestions. Seems like @yugangw-msft and @johanste might have some thoughts on this subject.

**Comment by tjprescott** [comment]
@devigned didn't your PR implement this?

**Comment by devigned** [comment]
Yep. Closing this.
