### ISSUE TITLE
Create flexible VMSS fail, expected string or bytes-like object

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli#20790]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

```
az vmss create -g vmssflex -n vmss --orchestration-mode flexible --image ubuntults --instance-count 2
```
I get
```
cli.azure.cli.core.azclierror: expected string or bytes-like object
az_command_data_logger: expected string or bytes-like object
```
Don't understand the error. Can you have a look? Thanks!

**To Reproduce**

```
az vmss create -g vmssflex -n vmss --orchestration-mode flexible --image ubuntults --instance-count 2
```

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by jiasli** [comment]
Thank you for reporting this issue. We will take a look. Please expect some delay due to the holiday season.

**Comment by qwordy** [comment]
The error disappears after a reboot👍

**Comment by zhoxing-ms** [comment]
@qwordy OK, if this issue can be reproduced in the feature, please send me the debug log
