### ISSUE TITLE
I am not being able to create a appservice plan from AZ CLI

### ISSUE THREAD

**Issue by wpalmeida** [Azure/azure-cli#20798]
## Describe the bug

**Command Name**
`az appservice plan create`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan create -n {} -g {} -l {} --sku {} --tags {} {} {} {}`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
Python 3.8.5
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by StrawnSC** [comment]
Hi @wpalmeida sorry you're running into an issue here. It looks like your CLI version is a bit behind (the latest version is `2.31.0`, but you're running `2.0.81`). Could you upgrade your CLI version with `az upgrade` and retry the command?

**Comment by jiasli** [comment]
azure-cli 2.0.81 running on Python 3.8.5 is not the official Azure CLI distributed by Microsoft. Please see https://github.com/Azure/azure-cli/issues/19640.
