### ISSUE TITLE
`az role assignment list`: "Failed to resolve graph object information" with managed identity

### ISSUE THREAD

**Issue by Iain-S** [Azure/azure-cli#20792]
## Describe the bug

**Command Name**
`az role assignment list

**Errors:**

Failed to resolve graph object information per error '403 Client Error: Forbidden for url: https://graph.windows.net/4395f4a7-e455-4f95-8a9f-1fbaef6384f9/getObjectsByObjectIds?api-version=1.6'

## To Reproduce:

Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a VM on Azure and assign a managed identity
- Give RBAC permissions (e.g. owner) to the managed identity to some subscription
- Connect via SSH to the VM
- Install azure-cli
- Login with `az login --identity`
- `az role assignment list --verbose --subscription {}`

## Expected Behavior

I would expect to see users' usernames in the `principalName` field (as I do when I run the `az role assignment list` command locally). However, I do not get the principal name and, when I add the `--verbose` flag, I see the "Failed to resolve graph object info..." error given above.

## Environment Summary
```
Linux-5.11.0-1022-azure-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by jiasli** [comment]
The [Role Assignments - Get](https://docs.microsoft.com/en-us/rest/api/authorization/role-assignments/get) REST API only returns the `principalId` (object ID in Graph) of the assignee, without the usernames.

Azure CLI has to query Graph API for the usernames (principal names). However, managed identity can't be granted `Directory.Read.All` permission (https://docs.microsoft.com/en-us/graph/api/directoryobject-getbyids), so `az role assignment list` cannot get usernames.

**Comment by Iain-S** [comment]
Thanks @jiasli. I had not seen the https://docs.microsoft.com/en-us/graph/api/directoryobject-getbyids docs before (though I certainly had tried to search for it). So I should grant my managed identity `Directory.Read.All` permissions and, in theory, I should be able to get the full names rather than only the IDs?

**Comment by jiasli** [comment]
@Iain-S, 

> So I should grant my managed identity `Directory.Read.All` permissions and, in theory, I should be able to get the full names rather than only the IDs?

This is true. However, this permission can only be granted to **user** account or a **service principal** account, not managed identity. Managed identity is only designed to access Azure resources (like storage, key vault), not Microsoft Graph or AD Graph.

**Comment by Iain-S** [comment]
Hi @jiasli, thanks for getting back to us.

We tried the following but still get an `Failed to resolve graph object information per error '403 Client Error: Forbidden for url: https://graph.windows.net/xxx-yyy-zzz/getObjectsByObjectIds?api-version=1.6'` error 

1. Removed the managed identity from our VM
2. Created a service principal `my-service-principal`
3. Gave `my-service-principal` the `Directory.Read.All` permission
4. Logged in as `my-service-principal` on our VM with `az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID`
5. Gave `my-service-principal` the Reader role on `my-subscription`
6. Ran `az role assignment list --subscription my-subscription-id` 

Are there any other role, permissions or settings you can think of that might be stopping this from working? 

Again, thanks for your patience.

**Comment by jiasli** [comment]
@Iain-S, I think you probably gave the service principal Microsoft Graph permission in Azure Portal. This is described in our pinned issue https://github.com/Azure/azure-cli/issues/19818.

As Azure CLI still internally uses AD Graph, (we are on the way to Microsoft Graph 😉) you need to give the service principal AD Graph permission `Directory.Read.All` instead. Please see https://github.com/Azure/azure-cli/issues/19818#issuecomment-939216867

I will provide a more detailed instruction next week when I back to office.

**Comment by Iain-S** [comment]
Yes, you're probably right. I don't think I quite understand the difference but we did it through the portal so likely Microsoft Graph (if it also has a Directory.Read.All permission).

Looks from the linked ticket like we'll have to run something like

```shell
API_PERMISSIONS=??  # Is there somewhere to look this up or do we need to `az ad sp show`?

az ad app permission add \  # Or should this be grant?
    --api 00000002-0000-0000-c000-000000000000 \ # AD graph, right?
    --api-permissions $API_PERMISSIONS  # Only Directory.Read.All or Directory.AccessAsUser.All too?
    --id $MY_SERVICE_PRINCIPAL_ID
```

I'll wait for you to confirm.

Have a good weekend.

**Comment by jiasli** [comment]
@Iain-S, thanks for your patience.

> Is there somewhere to look this up or do we need to `az ad sp show`?

I don't think there is a document published by AAD service for the API ID. 😥 So yes, calling `az ad sp show` is required.

Below we create a service principal with [Reader](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#reader) role assignment and give it AD Graph `Directory.Read.All` permission:

```sh
# Create a new service principal
$ az ad sp create-for-rbac --role Reader --scope /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590
{
  "appId": "457791f9-4c78-4f99-8b28-997692440681",
  "displayName": "azure-cli-2022-01-17-06-19-30",
  "password": "xxx",
  "tenant": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a"
}

# Query its objectId
$ az ad sp show --id 457791f9-4c78-4f99-8b28-997692440681 --query objectId --output tsv
d19a73ec-ea2c-47ba-a41b-a9b8ff30eba3

# Get the API ID of AD Graph Directory.Read.All and objectId of AD Graph
$ az ad sp show --id 00000002-0000-0000-c000-000000000000
{
  "appDisplayName": "Windows Azure Active Directory",
  "appId": "00000002-0000-0000-c000-000000000000",
    {
      "allowedMemberTypes": [
        "Application"
      ],
      "description": "Allows the app to read data in your company or school directory, such as users, groups, and apps.",
      "displayName": "Read directory data",
      "id": "5778995a-e1bf-45b8-affa-663a9f3f4d04",
      "isEnabled": true,
      "value": "Directory.Read.All"
    },
    ...
  "objectId": "fba255ef-08f7-4f9b-b673-318fcb87f042",
  ...

# Add permission to the service principal
$ az ad app permission add --api 00000002-0000-0000-c000-000000000000 --api-permissions 5778995a-e1bf-45b8-affa-663a9f3f4d04=Role --id 457791f9-4c78-4f99-8b28-997692440681

# Grant admin consent
# DO NOT use the old `az ad app permission admin-consent` API
$ az rest --method POST --uri https://graph.microsoft.com/v1.0/servicePrincipals/fba255ef-08f7-4f9b-b673-318fcb87f042/appRoleAssignedTo --body '{"principalId": "d19a73ec-ea2c-47ba-a41b-a9b8ff30eba3", "resourceId": "fba255ef-08f7-4f9b-b673-318fcb87f042", "appRoleId": "5778995a-e1bf-45b8-affa-663a9f3f4d04"}'
```

Now you may login with the newly created service principal and query Graph API or call `az role assignment list` with `principalName` filled:

```
$ az login --service-principal --username 457791f9-4c78-4f99-8b28-997692440681 --password xxx --tenant 54826b22-38d6-4fb2-bad9-b7b93a3e9c5a
```

**Comment by Iain-S** [comment]
Thanks, that's really helpful. I'll try this out in the next few days and let you know how it goes.

**Comment by Iain-S** [comment]
@jiasli Wanted to say a big "thank you" for walking me through this. We made the changes listed above and it worked. We can now run `az role assignment list...` to get the full RBAC list without any errors or warnings. Much appreciated.
