### ISSUE TITLE
az ml workspace update syntax

### ISSUE THREAD

**Issue by rp-msft** [Azure/azure-cli#20794]
az ml workspace update this command runs with -w for workspace name and -f for file name. Doesn't seem to run with --name and --file options. -f option seems to point to friendly name instead of the file option. This was with the latest az ml extension as of 12/21/2021. 

AZ CLI version 2.31.0
az-cli-ml 1.37.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63446f78-d3ac-0cc3-a102-a1612c54d90e
* Version Independent ID: a20a657c-aeaa-d122-0714-1aa2cfecd966
* Content: [az ml workspace](https://docs.microsoft.com/en-us/cli/azure/ml/workspace?view=azure-cli-latest#az_ml_workspace_update)
* Content Source: [latest/docs-ref-autogen/ml/workspace.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ml/workspace.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
Routing to service team to take a look. Please expect delay due to the holiday season.

**Comment by deeikele** [comment]
There are currently two version of the CLI experience for Azure Machine Learning, of which v2 is in preview. These versions require different arguments and are documented here: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-manage-workspace-cli?tabs=createnewresources%2Cvnetpleconfigurationsv1cli%2Cworkspaceupdatev1%2Cworkspacesynckeysv1%2Cworkspacedeletev1#using-the-cli-to-manage-workspaces.
