### ISSUE TITLE
"az synapse spark-job-definition create" doesn't respect the folder specified in definition in version 2.31.0 (works in 2.29.0)

### ISSUE THREAD

**Issue by sushantsaxena** [Azure/azure-cli#20802]
**Command Name**
`az synapse spark-job-definition create`

**Errors:**
`az synapse spark-job-definition create` is creating job definition at the root even when folder is specified.

## To Reproduce:
az synapse spark-job-definition create --workspace-name {workspace name} --name "MyJob" --file @FileDefinition.json

Content of FileDefinition.json is:
```
{
  "description": null,
  "folder": {
    "name": "Dev/Jobs"
  },
  "jobProperties": {
    "args": [
      "-i",
"tst",
"-n",
"Enrichment1"
    ],
    "file": "abfss://jobsdev@{adlsAccount}.dfs.core.windows.net/mainFile.py",
    "files": [
      "abfss://jobsdev@{adlsAccount}.dfs.core.windows.net/file1.py"
    ],
    "numExecutors": 2,
    "driverCores": 4,
    "driverMemory": "28g",
    "executorCores": 4,
    "executorMemory": "28g"
  },
  "language": "python",
  "requiredSparkVersion": "3.1",
  "targetBigDataPool": {
    "referenceName": "Dev",
    "type": "BigDataPoolReference"
  }
}
```

## Expected Behavior
"MyJob" is created in folder "Dev/Jobs". However, it is created at root level when using az cli version 2.31.0. If we use version 2.29.0, the job is created in correct folder.

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0 *

```

**Comment by jiasli** [comment]
Routing to service team to take a look. Please expect delay due to the holiday season.

**Comment by kevinzz6** [comment]
Hi @sushantsaxena , because in new version we add a argument "--folder-path". So could you please try to use this argument to set folder path and remove related field.

**Comment by sushantsaxena** [comment]
That worked, thanks!!
