### ISSUE TITLE
Change to access to User.Read.All in MS Graph

### ISSUE THREAD

**Issue by ymasaoka** [Azure/azure-cli#20801]
Recently, I can no longer select Azure AD Graph as a service principal.
Therefore, you cannot grant the service principal permission to do things like `az ad user list`.
I've confirmed that with the latest version, but it seems that the API of Azure AD Graph is accessed by the Azure CLI, which is very troublesome.
Please adapt the az ad user command of Azure CLI as soon as possible to refer to `User.Read.All` of MS Graph.

**Comment by jiasli** [comment]
> Recently, I can no longer select Azure AD Graph as a service principal.

This is explained in the pinned issue https://github.com/Azure/azure-cli/issues/19818.

> Please adapt the az ad user command of Azure CLI as soon as possible to refer to `User.Read.All` of MS Graph.

This is tracked by https://github.com/Azure/azure-cli/issues/12946.
