### ISSUE TITLE
Unexpected Error when using az aks get-os-option

### ISSUE THREAD

**Issue by Hanimaru** [Azure/azure-cli#20803]
## Describe the bug

**Command Name**
`az aks get-os-options`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

cannot import name 'edge_zone_type'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 556, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 502, in load_arguments
  File "C:\Users\fumin\.azure\cliextensions\aks-preview\azext_aks_preview\__init__.py", line 47, in load_arguments
    from ._params import load_arguments
  File "C:\Users\fumin\.azure\cliextensions\aks-preview\azext_aks_preview\_params.py", line 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-os-options --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.22.1 *

Extensions:
aks-preview 0.5.41

```

**Comment by jiasli** [comment]
Routing to service team to take a look. Please expect delay due to the holiday season.

**Comment by FumingZhang** [comment]
Hi @Hanimaru, sorry for the late reply. Please update your azure-cli to at least 2.27.0, aks-preview 0.5.41 is not compatible with azure-cli 2.22.1.
![Screenshot 2021-12-31 104731](https://user-images.githubusercontent.com/81607949/147800134-3ab8b466-704d-40d7-86e7-e832de00fe31.png)

**Comment by FumingZhang** [comment]
The current version dependency is like this

| aks-preview | Azure-cli |
|-|-|
| 0.5.40 ~ 0.5.41 |  >= [2.23.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.23.0), miss hint |
| 0.5.42 ~ 0.5.44 | >= [2.27.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.27.0) |
| 0.5.45 ~ 0.5.48 | >= [2.30.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.30.0) |
| 0.5.49 ~ 0.5.50 | >= [2.31.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.31.0) |

**Comment by navba-MSFT** [comment]
@Hanimaru Apologies for the late reply. Could you please let us know if you had a chance to follow the action plan suggested by @FumingZhang ? Please let me know if you are still facing this issue. Awaiting your reply.
