### ISSUE TITLE
`az ad sp create-for-rbac` should not default `--scope` to the subscription

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#20806]
**Describe the bug**

For `az ad sp create-for-rbac`, even though we have stopped creating the default "Contributor on Subscription" role assignment (https://github.com/Azure/azure-cli/pull/19805), when `--role` is given, this command defaults `--scope` to the subscription:

```
> az ad sp create-for-rbac --role Reader
...
Creating 'Reader' role assignment under scope '/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590'
...
{
  "appId": "9eb7e5f0-7a0b-4601-9d72-3f438fcace9f",
  "displayName": "azure-cli-2021-12-22-08-39-11",
  "password": "",
  "tenant": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a"
}
```

Without explicit consent from the user on the `--scope`, this behavior is considered Elevation of Privilege.

**Expected behavior**

`az ad sp create-for-rbac` should require both `--role` and `--scope` in order to create a role assignment for the newly created service principal.

**Comment by yonzhan** [comment]
az ad sp create-for-rbac
