### ISSUE TITLE
az synapse workspace activate fails for --ids option

### ISSUE THREAD

**Issue by t-dedah** [Azure/azure-cli#20814]
[Customer Issue]

az --version
azure-cli 2.31.0

core 2.31.0
telemetry 1.0.6

**Describe the bug**
I am trying to activate Synapse workspace via AZ CLI command using --ids option. What exactly is needed for --ids to work? The command is unable to get the --name option. Its ignores if I provide the option.

--W/O --name option
az synapse workspace activate --ids /subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/rg-mddsha1prodeastus-synapse-ws/providers/Microsoft.Synapse/workspaces/synmddsha1prodeastus --key-identifier https://xxxxxxxxx.vault.azure.net/keys/key-cmk-mddsha1prodeastus

Argument --name cannot be derived from ID /subscriptions/a0b62ca5-4dbf-4ddb-8d97-9d36cea4875c/resourceGroups/rg-mddsha1prodeastus-synapse-ws/providers/Microsoft.Synapse/workspaces/synmddsha1prodeastus,. Please provide a complete resource ID containing all information of 'Resource Id' arguments.

---With --name option

az synapse workspace activate --ids /subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/rg-mddsha1prodeastus-synapse-ws/providers/Microsoft.Synapse/workspaces/synmddsha1prodeastus --key-identifier https://xxxxxxxxx.vault.azure.net/keys/key-cmk-mddsha1prodeastus --name key-cmk-xxxxxxxx

option '--name' will be ignored due to use of '--ids'.

To Reproduce
Create synapse workspace with double encryption/system managed identity and run above command
Additional context

Duplicate Issue - https://github.com/Azure/cli/issues/67

**Comment by yonzhan** [comment]
route to service team

**Comment by kevinzz6** [comment]
Hi @t-dedah , --ids need to send a keyvault resourceid, not workspace resourceid. And if use --ids, don't need to use --workspace-name and --name.

**Comment by t-dedah** [comment]
Thanks @kevinzz6 , the above answer worked. Closing the issue now.
