### ISSUE TITLE
Synapse workspace creation w/o git configuration

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#20815]
### Discussed in https://github.com/Azure/azure-cli/discussions/20731

<div type='discussions-op-text'>

<sup>Originally posted by **dejan-shuki** December 14, 2021</sup>
I see a reason for you to make git configuration mandatory when Synapse workspace is created. 
However, there are valid use cases for synapse w/o git configuration. For example:
- We want to use Synapse in CI/CD scenario. Our test and production servers in that case should not have git configuration.
- We want to use scripts to deploy integration artifacts (i.e. pipelines, linked services, datasets) on Synapse workspace. We cannot do that when it has git configured. The artifacts can only be deployed to Synapse Live.
Can you relax requirements for creation of workspace to be w/o git configuration?
</div>

**Comment by jiasli** [comment]
Routing to service team to take a look. Please expect delay due to the holiday season.

**Comment by kevinzz6** [comment]
Hi, now git configuration is not mandatory for Synapse Workspace creation.

**Comment by wonner** [comment]
Hi @dejan-shuki, as @kevinzz6 mentioned, git configuration related arguments are optional in command `az synapse workspace create/update`. If you don't specify these arguments, it will create a workspace w/o git configuration.
