### ISSUE TITLE
az webapp config container set should be updated to support Managed Identity image pull

### ISSUE THREAD

**Issue by kemurayama** [Azure/azure-cli#20817]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Azure Web Apps for Containers now supports pulling image from Azure Container Registry (ACR) with Managed Identity but the command ​`az webapp config container set` still shows the message below when I disabled admin user on ACR. 

```bash
No credential was provided to access Azure Container Registry. Trying to look up...
Retrieving credentials failed with an exception:'Failed to retrieve container registry credentials. Please either provide the credentials or run 'az acr update -n <myacr> --admin-enabledtrue' to enable admin first.'
```
The command sets ACR user and password to AppSettings if the ACR admin user is enabled.

**To Reproduce**
Run the command after we disable admin user on ACR. 

```bash
az webapp config container set --name <mywebapp> --resource-group myResourceGroup --docker-custom-image-name <myacr>.azurecr.io/appsvc-tutorial-custom-image:1.0 --docker-registry-server-url https://<myacr>.azurecr.io
```

**Expected behavior**
Now App Services supports Managed Identity. This command should not add admin user name and password of ACR or show errors  when it is dissabled.

**Environment summary**
Tested on Azure Cloudshell.
```bash
$ az version
{
  "azure-cli": "2.31.0",
  "azure-cli-core": "2.31.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5",
    "ssh": "1.0.0"
  }
}
```
**Additional context**
Talked with @madsd on [the issue](https://github.com/MicrosoftDocs/azure-docs/issues/64660)

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@kemurayama Apologies for the late reply. Please follow the below action plan and let me know if you face any issues.

Enable [the system-assigned managed identity](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity) for the web app by using the [az webapp identity assign](https://docs.microsoft.com/en-us/cli/azure/webapp/identity#az_webapp_identity-assign) command:
```
az webapp identity assign --resource-group myResourceGroup --name <app-name> --query principalId --output tsv
```
Replace <app-name> with the name you used in the previous step. The output of the command (filtered by the --query and --output arguments) is the service principal of the assigned identity, which you can use in below command.

Managed identity allows you to grant permissions to the web app to access other Azure resources without needing any specific credentials.

```
az role assignment create --assignee <principal-id> --scope /subscriptions/<subscription-id>/resourceGroups/myResourceGroup/providers/Microsoft.ContainerRegistry/registries/<registry-name> --role "AcrPull"
```

More Info [here](https://docs.microsoft.com/en-us/azure/app-service/tutorial-custom-container?pivots=container-linux#configure-app-service-to-deploy-the-image-from-the-registry). Please test this and let me know if you face any issues.

**Comment by navba-MSFT** [comment]
Discussed with @madsd and involving Service Team.

@azureappservicecli @antcp Could you please look into this issue and provide an update on this thread ? cc @panchagnula

**Comment by panchagnula** [comment]
Hmm @navba-MSFT not sure what the conversation with @madsd  was here about. In short no ETA at this time to share @seligj95 - can you check as well

**Comment by madsd** [comment]
Just that while there is a workaround to configure this using calls to az resource update... the command that is meant for this, does not support it and is throwing an error when trying to configure it. Sot it is more missing functionality/feature ask in the cli used to configure container.
