### ISSUE TITLE
az servicebus queue create/update doesn't allow setting max message size

### ISSUE THREAD

**Issue by mdroogendijk** [Azure/azure-cli#20823]
We've got a queue that needs to be able to receive messages larger than the default 1024 KB size.
In the portal, we can manually change the Max message size up to 102400 KB, but this doesn't seem possible with the az cli commands.

![image](https://user-images.githubusercontent.com/38788886/147255588-0f6a073e-f4be-49b8-a2f5-ed7e1db57a0e.png)

Could this be added?

**Comment by yonzhan** [comment]
route to service team

**Comment by Ettores88** [comment]
Any update on this?

**Comment by Saglodha** [comment]
Hi @mdroogendijk , thanks for bringing this to our attention. 

We would review the behavior and keep you posted with updates.

**Comment by eugene-jo** [comment]
Any update on this?

**Comment by Saglodha** [comment]
@eugene-jo, thanks for following up. 

This would be fixed in this month release; I would circle back once the fix is live.

**Comment by Saglodha** [comment]
Hi @eugene-jo / @mdroogendijk, 

This has been fixed in our latest release. Please retry the operation and let us know if you have additional concerns.
