### ISSUE TITLE
`az functionapp function keys list` sometimes returns wrong slot keys

### ISSUE THREAD

**Issue by joeyj** [Azure/azure-cli#20824]
**Describe the bug**
When executing `az functionapp function keys list --name $Name --resource-group $ResourceGroup --slot staging --function-name $FuncName` sometimes it returns the production slot. 

**To Reproduce**
1. perform a staging slot swap to production
2. execute `az functionapp function keys list --name $Name --resource-group $ResourceGroup --slot staging --function-name $FuncName` 
3. notice the keys returned are for the production slot (sometimes)

**Expected behavior**
Should return the keys for the slot provided in arguments

**Environment summary**
```
azure-cli                         2.28.0 *

core                              2.28.0 *
telemetry                          1.0.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\there\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
```
**Additional context**

**Comment by yonzhan** [comment]
route to service team

**Comment by joeyj** [comment]
any update? this is really annoying to encounter in my deployment scripts :(

**Comment by panchagnula** [comment]
@joeyj given this is not a CLI specific issue but the response from API which the feature team needs to handle - there is not much update I can provide. I have shared this with the functions team - please create a support case if needed. Thanks!
