### ISSUE TITLE
--subscription-required parameter of az apim product create not working

### ISSUE THREAD

**Issue by mossywell** [Azure/azure-cli#20826]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
The "az apim product create" is used to create a new product in APIM. Products can have subscriptionRequired set to true or false. There is an Azure CLI argument "--subscription-required" to allow this. However, in all circumstances, the subscriptionRequired value is set to true.

**To Reproduce**
1. Create a new API Management
2. Create a new Product
3. Run this:
az apim product create --resource-group "<my RG>" --service-name "<My APIM>" --product-id "<My Product>" --product-name "<My Product>" --state "published" --subscription-required "false"
Or
az apim product create --resource-group "<my RG>" --service-name "<My APIM>" --product-id "<My Product>" --product-name "<My Product>" --state "published" --subscription-required false
Or
az apim product create --resource-group "<my RG>" --service-name "<My APIM>" --product-id "<My Product>" --product-name "<My Product>" --state "published" --subscription-required $false
All result in subscriptionRequired : true

**Expected behavior**
The value of subscriptionRequired should be set to false if "false" is used on the CLI argument.

**Environment summary**
Azure CLI either in a cloud shell or locally.

**Additional context**
N/A

**Comment by yonzhan** [comment]
route to service team

**Comment by mossywell** [comment]
> @mossywell Apologies for the late reply. I was able to reproduce this issue. We will update this thread once we have more details on the fix.
> 
> @adrianhall Could you please look into this and provide an update on you get a chance ? Awaiting your reply.

Thank you

**Comment by adrianhall** [comment]
Thanks for the report.  I've included this in our backlog so that a fix will be available in the next APIM release of the CLI.  I'll update when then release happens.

**Comment by mossywell** [comment]
Excellent - thanks for the update.

**Comment by BCIfernando1989mg** [comment]
i have this problem too, please fix it soon!!

**Comment by BCIfernando1989mg** [comment]
> > @mossywell Apologies for the late reply. I was able to reproduce this issue. We will update this thread once we have more details on the fix.
> > @adrianhall Could you please look into this and provide an update on you get a chance ? Awaiting your reply.
> 
> Thank you

bro, do you have any solution for this?

**Comment by mossywell** [comment]
It can be done in PowerShell as follows:

$context = New-AzApiManagementContext -ResourceGroupName "my-rg" -ServiceName "my-apim"
$product = Get-AzApiManagementProduct -Context $context -ProductId "my-product"
$product.SubscriptionRequired = $false
$product | Set-AzApiManagementProduct -Context $context
