### ISSUE TITLE
Azure CLI cannot get dogfood scoped token for https://api-dogfood.resources.windows-int.net/

### ISSUE THREAD

**Issue by arsdragonfly** [Azure/azure-cli#20836]
See [internal stackoverflow](https://stackoverflow.microsoft.com/questions/287438/287526#287526)

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Azure CLI is registered as a first-party app, so it doesn't need to explicitly apply for consent. 

According to https://stackoverflow.microsoft.com/questions/122681, `https://api-dogfood.resources.windows-int.net/` is only the ARM endpoint. Even in dogfood, ARM's resource should be `https://management.core.windows.net/`.

So you will need to run

```
az account get-access-token --output json --resource https://management.core.windows.net/
```

If you are calling Azure CLI with Python SDK `azure.identity.AzureCliCredential`, make sure the `credential_scopes` parameter is correctly set to `['https://management.core.windows.net/']`.
