### ISSUE TITLE
az keyvault secret set exposes value, option to hide this output?

### ISSUE THREAD

**Issue by nc-ruth** [Azure/azure-cli#20858]
**Is your feature request related to a problem? Please describe.**
It is pretty frustrating that every time I use the `az keyvault secret set`, it exposes the value of the secret (even if it is a file). 
The following example illustrates the issue: 
```
$ az keyvault secret set --vault-name my-vault-name --name my-file-name -f my-secret-file.key
{
  "attributes": {
    "created": "2021-12-29T12:16:23+00:00",
    "enabled": true,
    "expires": null,
    "notBefore": null,
    "recoveryLevel": "CustomizedRecoverable+Purgeable",
    "updated": "2021-12-29T12:16:23+00:00"
  },
  "contentType": null,
  "id": "<SNIPED>",
  "kid": null,
  "managed": null,
  "name": "my-file-name",
  "tags": {
    "file-encoding": "utf-8"
  },
  "value": "-----BEGIN RSA PRIVATE KEY-----\n-----END RSA PRIVATE KEY-----\n"
}
```

**Describe the solution you'd like**

It would be nice with an argument/option, where the response does not contain the "value" property.
Fx. 
```
$ az keyvault secret set --vault-name my-vault-name --name my-file-name -f my-secret-file.key --hide-value
```

**Describe alternatives you've considered**

Current working solution is:
```
$ az keyvault secret set --vault-name my-vault-name --name my-file-name -f my-secret-file.key 1> /dev/null
```
**Additional context**

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
Hi @nc-ruth , service side is working on not returning the secret in the response. Currently from client side, you can add `-o none` to output nothing or add `--query '{attributes:attributes, contentType:contentType, id:id, kid:kid, managed:managed, name:name, tags:tags}'` to hide secret value:
![image](https://user-images.githubusercontent.com/10227683/147714807-73aaa799-1b9a-40f2-8eb9-e1b859537535.png)

**Comment by nc-ruth** [comment]
@evelyn-ys is there any update on this?

**Comment by yonzhan** [comment]
@nc-ruth Did you try out the above solution?

**Comment by navba-MSFT** [comment]
@nc-ruth Apologies for the late reply. Could you please let us know if you had a chance to follow the suggestions provided by @evelyn-ys in the [above](https://github.com/Azure/azure-cli/issues/20858#issuecomment-1002836587) comment ? Awaiting your reply.

**Comment by nc-ruth** [comment]
Hi @yonzhan and @navba-MSFT the above suggestions works.
Sorry for the late reply, and  thank you for the suggestions.
