### ISSUE TITLE
[Compute] Availability Set create defaults can be invalid

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2085]
The following defaults:
```
--platform-fault-domain-count : Default: 5.
--platform-update-domain-count: Default: 5.
```
can be invalid depending on the region the availability set is created in. For example, when I tried to create a VM in westus with an availability set in westus, I got a deployment error requesting I use a value between 1 and 3.

We should either set the default to something that works across all regions or see if there's a way to query what the default should be for the selected region.

**Comment by yugangw-msft** [comment]
I will get this clarified

**Comment by yugangw-msft** [comment]
@tjprescott, CRP is exposing the sku api which we can query the domain count. At the same time, I suggest we remove the default number. We can add it later, which won't become a break change.

**Comment by yugangw-msft** [comment]
@tjprescott, I have submitted #2111 to remove the defaults. With new API coming up, we can do validation at client, but we will not have default value.
So I am closing this one
