### ISSUE TITLE
GraphQL APIM Azure CLI Support

### ISSUE THREAD

**Issue by tylerkb2** [Azure/azure-cli#20863]
**Feature Request:**
Please add support to the Azure CLI to include the new GraphQL APIM feature.

**Background:**
Our team uses the Azure CLI to manage our APIM resources. We would like to extend this to our GraphQL API's.

**Issue Encountered:**
"Cannot bind parameter 'SpecificationFormat'. Cannot convert value "graphql" to type "Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Models.PsApiManagementApiFormat". Error: "Unable to match the identifier name graphql to a valid enumerator name. Specify one of the following enumerator names and try again:
Wadl, Swagger, Wsdl, OpenApi, OpenApiJson"

The above error is consistent with the [Azure CLI APIM Documentation](https://docs.microsoft.com/en-us/cli/azure/apim/api?view=azure-cli-latest#az_apim_api_import).

**Note:**
The feature is in preview. The CLI would understandably not be updated yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 197d8382-ee16-6001-4941-768877379c0d
* Version Independent ID: 1423fa76-977f-ad88-8129-0b52a38e68e6
* Content: [az apim](https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/apim.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/apim.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by RamakantDBA** [comment]
Graphql in APIM is now GA. I still cannot find the SpecificationFormat to import a graphql api. Please help

**Comment by wpooley** [comment]
We'll need to add the Graphql specification-format to the [az apim api import cmdlet](https://docs.microsoft.com/en-us/cli/azure/apim/api?view=azure-cli-latest#az-apim-api-import).

Perhaps as a workaround, we do support the creation of a GraphQL Api and the upload of a GraphQL Schema in cli using the example below.

az apim api create --service-name MyApim -g MyResourceGroup --api-id MyGraphqlApi --path '/mygraphqlapi' --display-name 'My GraphQL API' --api-type **graphql** --service-url "https://MyServiceUrl.com"

az apim api schema create --service-name MyApim -g MyResourceGroup --api-id MyApi --schema-id **graphql** --schema-type **application/vnd.ms-azure-apim.graphql.schema** --schema-path "c:\path\to\schema.gql"
