### ISSUE TITLE
[DNS] Change 'az network dns record update-soa' to 'az network dns record soa update'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#2087]
Under 'az network dns record', we have a bunch of subgroups (one for each record type) followed by a one-off command 'update-soa'.

The SOA record set is a bit of a special case, in that it can be edited but doesn't support add/remove.

However, I think there's a cleaner way to support this. Remove the 'update-soa' command, and move it to an 'update' command under the 'soa' command group

That way, under 'records' we have a clean list of command groups, one for each record type including SOA. Under each record type, we support add/remove commands, except for SOA which supports an update command instead.

**Comment by tjprescott** [comment]
We do not create command groups that only have a single command. In that case, we move the command up one "level" and expose it with a hyphenated command name.

**Comment by jtuliani** [comment]
That sucks. 'soa update' is SO much cleaner and more consistent with the other record types than 'update-soa'. It's a much better customer experience.

Given the issue of consistency across record types, can we make an exception?

**Comment by tjprescott** [comment]
@johanste thoughts? It would be inconsistent with the rest of the CLI, but we have talked about ditching this convention before. If we do, it would make sense to do so before GA.
