### ISSUE TITLE
az cli login redirects to 'https://login.windows-ppe.net' instead of 'login.micosoftonline.com'

### ISSUE THREAD

**Issue by jaeyonglee8687** [Azure/azure-cli#20883]
I have tried to sign in to my azure account via 'az login' command, and it opens a window redirecting me to 'https://login.windows-ppe.net' instead of 'login.micosoftonline.com'.

I used the same credential to login, 'jaeyonglee@microsoft.com', but it brings a different set of subscriptions; Cloud name 'dogfood' that are not under my actual azure production account. I see that 'https://login.windows-ppe.net' is navigating me to 'Microsoft dogfood' authentification process.
![image](https://user-images.githubusercontent.com/87626977/147814347-8fd30b2b-f13f-4ef6-af74-63044ad2d016.png)

I've tried to directly sign in with the tenant ID, which is blocked.
![image](https://user-images.githubusercontent.com/87626977/147814443-52ea58d9-cd67-408f-b891-55e1e9c26a94.png)

When I try to see the list of subscriptions via Cloud Shell on Azure, I can see all subscriptions I have.
This results in a weird behavior in VS code, 
- Using Azure extension in VSC and I am able to see all my subscriptions.
- When I try to list the subscriptions via cli, then it shows different subscription

![image](https://user-images.githubusercontent.com/87626977/147814551-bc81e33e-c1af-4ea2-b55e-5c50eea8fa1d.png)

Is there any way I can change the default behavior?

**Comment by jiasli** [comment]
This is because you registered `dogfood` cloud before and switched to it.

To use public Azure, please run

```
az cloud set --name AzureCloud
```

For more info, see https://docs.microsoft.com/en-us/cli/azure/manage-clouds-azure-cli

**Comment by jaeyonglee8687** [comment]
@jiasli Problem solved! Would be nice if there were some guidance to hint at this solution. I spent quite some time googling this issue, but couldn't really get the answer (probably because I am not familiar with this, but I also asked other 2 engineers, but this issue was not familiar with them at all as well).

**Comment by jiasli** [comment]
Azure CLI by default does use `AzureCloud`, thus https://login.micosoftonline.com to log in. 

The user must 

1. manually register `dogfood` with `az cloud register`
2. switch to it with `az cloud set`

for it to take effect.

Adding guidance or hint for **something the user deliberately did** would make the terminal output too crowded in my opinion. It's like I turned on auto-hold in my car, and the display hints me to turn it off, right?

 @chasewilson
