### ISSUE TITLE
Error when running az network vnet create command

### ISSUE THREAD

**Issue by Kamran-Bilgrami** [Azure/azure-cli#20886]
## Describe the bug

**Command Name**
z network vnet create --name ADLabNet  --resource-group ADLab --address-prefix 10.0.1.0/24 --subnet-name default --subnet-prefix 10.0.1.0/24

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'standard_medium'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 518, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/network/__init__.py", line 39, in load_arguments
    load_arguments(self, command)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/network/_params.py", line 135, in load_arguments
    c.argument('sku', arg_group='Gateway', help='The name of the SKU.', arg_type=get_enum_type(ApplicationGatewaySkuName), default=ApplicationGatewaySkuName.standard_medium.value)
AttributeError: 'NoneType' object has no attribute 'standard_medium'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network vnet create --name {} --resource-group {} --address-prefix {} --subnet-name {} --subnet-prefix {}`

## Environment Summary
```
Linux-5.14.0-kali4-amd64-x86_64-with-glibc2.33, Kali GNU/Linux Rolling
Python 3.9.9
Installer: DEB

azure-cli 2.31.0

Extensions:
azure-devops 0.22.0

```
## Additional Context
az --version                                                                        
azure-cli                         2.31.0

core                              2.31.0
telemetry                          1.0.6

Extensions:
azure-devops                      0.22.0

Python location '/usr/bin/python3'
Extensions directory '/home/kali/.azure/cliextensions'
Extensions system directory '/usr/lib/python3/dist-packages/azure-cli-extensions'

Python (Linux) 3.9.9 (main, Dec 16 2021, 23:13:29) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
                                                                                                                
┌──(kali㉿kali)-[~]
└─$ uname -a
Linux kali 5.14.0-kali4-amd64 #1 SMP Debian 5.14.16-1kali1 (2021-11-05) x86_64 GNU/Linux

**Comment by yonzhan** [comment]
network

**Comment by YuanyuanNi** [comment]
Hi, 
 It works well on CLI 2.32.0, maybe you can upgrade your CLI and try it again , thanks.
Best wishes.

**Comment by Kamran-Bilgrami** [comment]
It worked well for me to after upgrading to 2.32.0. However, now that I upgraded to 2.33.0, the exact same error is back

**Comment by Kamran-Bilgrami** [comment]
Any comment/update about this?

**Comment by kairu-ms** [comment]
Hi @YuanyuanNi, Could you have a look? Thanks.

**Comment by YuanyuanNi** [comment]
Hi，
      I have tried this command in version 2.33.0/2.33.1/2.34.0  and all works well, maybe you can upgrade to the latest version (2.34.0) and try again, if you still have this issue, pls describe your pre condition in detail, thanks.
Best wishes.

**Comment by Kamran-Bilgrami** [comment]
I upgraded to 2.34.1 and its working again. Thanks for looking into this.

**Comment by yrro** [comment]
I am seeing this with 2.45.0, anyone else?

**Comment by yrro** [comment]
[update] this was caused by unintentionally upgrading to the `azure-cli` package from the Debian package repository. `azure-cli` from the microsoft repository works fine.
