### ISSUE TITLE
Microsot.OperationalInsights: Required CLI changes.

### ISSUE THREAD

**Issue by dulikvor** [Azure/azure-cli#20903]
**Resource Provider**
Microsot.OperationalInsights

**Description of Feature or Work Requested**
A new public api version was published targeting an upcoming public preview. changes spans across two resources and requires an update to CLI client.

and in particular:
1. Supporting default data collection rule association with a specify workspaces.
Update - az monitor log-analytics workspace update
Need to add a new parameter - [--defaultDataCollectionRuleResourceId]
az monitor log-analytics workspace | Microsoft Docs

2. All tables recent changes.
List (requires an update) - az monitor log-analytics workspace table list
Get (requires an update) - az monitor log-analytics workspace table show
Patch (requires an update) - az monitor log-analytics workspace table update
Delete – Not supported by CLI today.
Put – Not supported by CLI today.

Its important to indicate Patch/Delete/Put now also supports async operations, meaning on some occasions 202 will be returned instead of 200 and azure async headers are mandatory for the user:
•	Retry-After
•	Location
•	Azure-AsyncOperation

Property enumeration by feature:
Property Name	                     Affected feature
ArchiveRetenionInDays	               Basic logs
LastPlanModifiedDate	               Basic logs
Plan	                               Basic logs
provisioningState	                   CLV2/Sentinel
restoredLogs	                       Sentinel
resultsStatistics	                   Sentinel
schema	                               CLV2/Sentinel
searchResults	                       Sentinel
systemData	                           Sentinel
totalRetentionInDays                   Basic logs
defaultDataCollectionRuleResourceId	   CLV2

Table_Create/Delete/Update/Get/List – Mandatory.

**Minimum API Version Required**
2021-12-01-preview

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/preview/2021-12-01-preview

**Target Date**
Public preview begins 2/1/22, target date for CLI changes - 1/23/22.

Changes in 2021-12-01-preview:
![image](https://user-images.githubusercontent.com/16348853/148879996-17e04cc0-0d1a-4f2d-be72-04f2c7fea01c.png)

**Comment by yonzhan** [comment]
Monitor

**Comment by jsntcy** [comment]
Since public SDK is still in releasing, we can use private SDK for development first.

How to generate private SDK?
https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/private_package/get_private_package.md
