### ISSUE TITLE
azure functionapp update does not properly handle the --slot setting

### ISSUE THREAD

**Issue by dannmichelson** [Azure/azure-cli#20901]
**Describe the bug**
When the trying to update properties for a Azure Function Slot (specifically the loadBalancing property) using Azure CLI, the change is applied to the production slot rather than the slot specified

**To Reproduce**
ex: `az functionapp update -g $resourceGroup -n $name -s $slotName --set siteConfig.loadBalancing=PerSiteRoundRobin`

**Expected behavior**
The expectation is that properties for the `$slotName` slot is updated.

**Environment summary**
run in Powershell Core 7.1.3, Azure CLI 2.31.0

**Additional context**
The biggest reason this is a big problem is that we change all our configuration in our staging slot and then swap into the main slot, which ensures no down time during deployments.

**Comment by yonzhan** [comment]
route to service team

**Comment by dannmichelson** [comment]
Any updates on this?

**Comment by dannmichelson** [comment]
I'm still seeing this issue. This should be a bigger deal because people may be intending to modify a staging slot but end up modifying their production slot, causing unexpected production restarts!!

**Comment by navba-MSFT** [comment]
@kevin-secrist Just checked the details about the PR https://github.com/Azure/azure-cli/pull/21698 and got a confirmation that the fix is yet to be released. Sending you the next release milestone details: https://github.com/Azure/azure-cli/milestone/116 which is planned for April 6th. Hope this helps.

**Comment by kevin-secrist** [comment]
From a non-expert perspective that PR doesn't look like it solves the particular issue that I was facing. The PR appears to be related to zip deployments, but this is changing settings on the app service.

**Comment by panchagnula** [comment]
@haroonf can you check if we can repro this? seems like update command is ignoring the --slot setting ? Thanks!

**Comment by haroonf** [comment]
Wasn't able to repro this, could you try upgrading to latest version of cli?

**Comment by kevin-secrist** [comment]
@haroonf I replicated this again using the instructions I posted on https://github.com/Azure/azure-cli/issues/15800#issuecomment-1075235705

```
$ az --version
azure-cli                         2.37.0

core                              2.37.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/kevin/.azure/cliextensions'

Python (Linux) 3.10.4 (main, May 23 2022, 14:03:08) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```
