### ISSUE TITLE
unable to add a record to the newly created record-set-name

### ISSUE THREAD

**Issue by reddy268** [Azure/azure-cli#20902]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.31.0

**Describe the bug**

Through shell script,  record-set-name is created and adding "A" record to it.
While doing so, I get the following error:

ERROR: (AuthorizationFailed) The client 'xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxx' with object id 'xxx-xxxx-xxxx-xxxxxx-xxxxxxxxxxxxxxxx' does not have authorization to perform action 'Microsoft.Network/privateDnsZones/a/read' over scope '/subscriptions/'xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxx' /resourceGroups/rg-base/providers/Microsoft.Network/privateDnsZones/xxx.local/a/recordset or the scope is invalid. If access was recently granted, please refresh your credentials.
Code: AuthorizationFailed
Message: The client ''xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxx' ' with object id 'xxx-xxxx-xxxx-xxxxxx-xxxxxxxxxxxxxxxx' does not have authorization to perform action
'Microsoft.Network/privateDnsZones/a/read' over scope '/subscriptions/xxx-xxxx-xxxx-xxxxxx-xxxxxxxxxxxxxxxx/resourceGroups/rgbase/providers/Microsoft.Network/privateDnsZones/xxxx.local/a/recordset' or the scope is invalid. If access was recently granted, please refresh your credentials._

But, if ran the same script again, the IP gets added successfully.
With the sleep till 120, I could not added the IP to the newly created recordset.

**To Reproduce**

Run below commands via .sh script 

_az network private-dns record-set a create -g "MyResourceGroup " -z "mysite.com" -n "MyRecordSet"
az network private-dns record-set a create -g "MyResourceGroup " -z "mysite.com" -n "MyRecordSet" -a <IP>_

**Expected behavior**

Record set should be created successfully, along with IP added to the record set

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
network

**Comment by YuanyuanNi** [comment]
Hi:
    First you may upgrade your CLI to the latest version( 2.32.0), then you may use "az network private-dns record-set a add-record -g  MyResourceGroup -z www.mysite.com -n MyRecordSet -a MyIpv4Address“   to add a record to your newly create record-set-name.
Best wishes.

**Comment by reddy268** [comment]
Resolved!
Please close the git.

**Comment by reddy268** [comment]
Resolved!
Please close the git.
