### ISSUE TITLE
[Monitor] Support Application Insights Web Test

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#20916]
**Resource Provider**
Microsoft.Insights

**Description of Feature or Work Requested**

Create, update, show, delete and list Application Insights web test.

Add new commands: `az monitor app-insights web-test create/update/delete/show/list` to https://github.com/Azure/azure-cli-extensions/tree/main/src/application-insights/azext_applicationinsights

PowerShell cmdlets reference: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1063

Help docs: https://docs.microsoft.com/en-us/azure/azure-monitor/app/monitor-web-app-availability

**Minimum API Version Required**
2018-05-01-preview

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/e1eca381eca8ec1f80b722e5dbf060fdeef48653/specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2018-05-01-preview/webTests_API.json

**Target Date**

**Comment by yonzhan** [comment]
Monitor
