### ISSUE TITLE
Update Stream Analytics CLI

### ISSUE THREAD

**Issue by roslynlu** [Azure/azure-cli#20913]
Is your feature request related to a problem? Please describe.
New Stream Analytics swagger specs were added recently, and they were missed in the latest release.  

Describe the solution you'd like
Update Stream Analytics CLI with additional swagger specs (clusters.json and privateendpoints.json)

Describe alternatives you've considered
N/A

Additional context
Swagger: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/streamanalytics/resource-manager/Microsoft.StreamAnalytics/stable/2020-03-01
Documentation: https://docs.microsoft.com/en-us/azure/stream-analytics/

**Comment by yonzhan** [comment]
Stream Analytics
