### ISSUE TITLE
Az extension | aks-preview commands failing

### ISSUE THREAD

**Issue by vamsivellanki** [Azure/azure-cli#20912]
## Describe the bug

**Command Name**
`az aks maintenanceconfiguration add`

**Errors:**
```
**cannot import name 'edge_zone_type'**
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 558, in execute
pip-unpacked-wheel-34tyr6f2\azure\cli\core\__init__.py, ln 479, in load_arguments
.azure\cliextensions\aks-preview\azext_aks_preview\__init__.py, ln 47, in load_arguments
    from ._params import load_arguments
.azure\cliextensions\aks-preview\azext_aks_preview\_params.py, ln 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks maintenanceconfiguration add -g {} --cluster-name {} --name {} --weekday {} --start-hour {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1 *

Extensions:
aks-preview 0.5.41
vm-repair 0.3.4

```

**Comment by yonzhan** [comment]
route to service team

**Comment by vamsivellanki** [comment]
Any command I run after trying to update (az extension update --name aks-preview) is giving the same error

**Comment by phealy** [comment]
Please upgrade your Azure-cli version - you're running 2.17.1, while current is 2.32.0. Let me know if the bug continues under the new version. Thanks!

**Comment by vamsivellanki** [comment]
Its working after upgrading to latest CLI version, 
azure-cli - 2.32.0
Thank you, this thread can be closed.
