### ISSUE TITLE
Quota RP Create Azure CLI

### ISSUE THREAD

**Issue by rahuls-microsoft** [Azure/azure-cli#20914]
**Resource Provider**

Microsoft.Quota

**Description of Feature or Work Requested**

Please generate - AzCLI, PowerShell and Terraform modules for Microsoft.Quota RP.

**Minimum API Version Required**

2021-03-15-preview

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/quota/resource-manager/Microsoft.Quota/preview/2021-03-15-preview/quota.json

**Target Date**

2/22/2022

**Comment by yonzhan** [comment]
Quota

**Comment by yonzhan** [comment]
pending on Service readiness
