### ISSUE TITLE
[DNS] DNS record management commands should support --if-match

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#2092]
The commands under 'az network dns record ...' are used to add/remove records from DNS record sets. They can also create a new record set if one does not already exist.

These operations need to support optimistic concurrency to protect against concurrent changes.

To address this, the '--if-match <value>' parameter should be supported on both the 'add' and 'remove' commands (and 'update-soa').

When the record set doesn't already exist and thus a new record set is being created, the command should *always* include '--if-none-match *' to protect against concurrent operations. This this should always be applied in this case, there is no need to expose it in the command parameters.

**Comment by yonzhan** [comment]
@MyronFanQiu  add to S162.

**Comment by MyronFanQiu** [comment]
@jtuliani Hello. The suggestion sounds good. But I don't want to bring breaking change to user suddenly. I add warning information in #11900 and create a new issue #11901 to do it.

**Comment by jtuliani** [comment]
Thank you!

**Comment by MyronFanQiu** [comment]
@jtuliani Hello. Thanks for feedback. Do you still remember your original thoughts? I want to double confirm, do you want an extra argument `'--if-not-match`. Only the command with `--if-not-match` will create a new record-set for customer by default.
