### ISSUE TITLE
FunctionApp:az functionapp deployment failed

### ISSUE THREAD

**Issue by athapong** [Azure/azure-cli#20925]
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
HTTPSConnectionPool(host='xxx.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x07BFB7B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Traceback (most recent call last):
pip-install-t7say61i\urllib3\urllib3\connection.py, ln 159, in _new_conn
urllib3\urllib3\util\connection.py, ln 57, in create_connection
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip --src {} -n {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.77

```

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
Can you just please re-try the error indicates there was an issue for the CLI client to reach the Scm endpoint for deployment.

**Comment by Kotasudhakarreddy** [comment]
@athapong Hope you have re-tried the command again.

**Comment by Kotasudhakarreddy** [comment]
closing due to lack of response. Please file a new issue if this is still a problem.

**Comment by athapong** [comment]
Sorry for my late response..
Once I fixed some issue due to organization policy it's working now.

Appreciate for your help

**Comment by tijujohn83** [comment]
> Sorry for my late response.. Once I fixed some issue due to organization policy it's working now.
> 
> Appreciate for your help

which policy was it?
