### ISSUE TITLE
[DNS] 'arecords' should be 'aRecords'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#2094]
Consider the JSON output for A records (could be from simply showing a record set, or when listing record sets, or when creating a record, or whatever):

C:\Users\jonatul>az network dns record-set show -g rg1 -n cli2 -z jt-test.com -t A
{
  "arecords": [
    {
      "ipv4Address": "1.2.3.5"
    },
    {
      "ipv4Address": "1.2.3.6"
    }
  ],
  "etag": "bc3841f6-ba92-49d2-93da-b10c09d2fec9",
  "id": "/subscriptions/a385a691-bd93-41b0-8084-8213ebc5bff7/resourceGroups/rg1/providers/Microsoft.Network/dnszones/jt-test.com/A/cli2",
  "metadata": null,
  "name": "cli2",
  "resourceGroup": "rg1",
  "ttl": 3600,
  "type": "Microsoft.Network/dnszones/A"
}

For consistency with other record types, the string 'arecords' above should be 'aRecords'.

**Comment by tjprescott** [comment]
This is an SDK issue. It happens because the model for this property is "arecords" instead of "a_records".

**Comment by jtuliani** [comment]
SDK issue tracked as [VSO bug 1213981](https://msazure.visualstudio.com/web/wi.aspx?pcguid=41bf5486-7392-4b7a-a7e3-a735c767e3b3&id=1213981)
