### ISSUE TITLE
Add warning info to affected MS Graph commands

### ISSUE THREAD

**Issue by chasewilson** [Azure/azure-cli#20946]
**Is your feature request related to a problem? Please describe.**

WIth the upcoming migration to MS Graph and planned retirement of the AAD Graph endpoint, customers need to be informed of upcoming changes and recommendations on how to prepare for migration. 

**Describe the solution you'd like**

An [issue has been created](https://github.com/MicrosoftDocs/azure-docs-cli/issues/2908) to track the Azure CLI Docs side of things, but another solution is to provide messaging directly in-tool for future affected commands to inform customers currently using said commands that they will need to update/migrate for new MS Graph integration.

**Describe alternatives you've considered**

Documentation, blogposts and Social media blasts will happen as well

**Additional context**

**Comment by yonzhan** [comment]
@jiasli for awareness
