### ISSUE TITLE
Cannot scale down a AKS nodepool

### ISSUE THREAD

**Issue by katomaso** [Azure/azure-cli#20950]
## Describe the bug
Could not scale down a nodepool (that is in state Failed)

**Command Name**
`az aks nodepool scale`

**Errors:**
```
'AgentPoolsOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure/cli/core/__init__.py, ln 786, in default_command_handler
    return op(**command_args)
cli/command_modules/acs/custom.py, ln 3390, in aks_agentpool_scale
    return sdk_no_wait(no_wait, client.create_or_update, resource_group_name, cluster_name, nodepool_name, instance)
AttributeError: 'AgentPoolsOperations' object has no attribute 'create_or_update'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks nodepool scale --node-count {} -n {} --cluster-name {} -g {}`

## Environment Summary
```
Linux-5.13.0-23-generic-x86_64-with-glibc2.34
Python 3.9.7
Installer: DEB

azure-cli 2.18.0 *

Extensions:
azure-devops 0.19.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by phealy** [comment]
You have a fairly out of date version of Azure CLI; [please follow the instructions here to upgrade](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) and see if the issue continues. If it does, please post a new error message; if not, please let us know and close the issue. Thanks!
