### ISSUE TITLE
az vm extension set --force-update ignored or doesn't work

### ISSUE THREAD

**Issue by izenk** [Azure/azure-cli#20953]
## Describe the bug

**Command Name**
`az vm extension set`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az vm extension set --force-update -n "KeyVaultForLinux" --publisher Microsoft.Azure.KeyVault --resource-group "RG" --vm-name "vm" --version 2.0 --settings keyvault_ext.json`

## Expected Behavior
extension configuration should be updated

## Environment Summary
```
macOS-12.0.1-x86_64-i386-64bit, Darwin 21.1.0
Python 3.10.1
Installer: HOMEBREW

azure-cli 2.32.0
```
## Additional Context

KeyVault extension was installed on vm. After, I wanted to update extension settings. I updated my json file and ran command mentioned above - new settings were applied few times, but then for some reason extension stopped applying new settings. I can see in extension logs (on vm side) that old configuration is used.

Initial settings:
```
{
  "secretsManagementSettings": {
    "pollingIntervalInS": "3600",
    "requireInitialSync": true,
    "observedCertificates": ["link to my cert"],
    "certificateStoreName": "",
    "linkOnRenewal": false,
    "certificateStoreLocation": "/tmp"
  }
}
```

First update (which was applied correctly)
```
{
  "secretsManagementSettings": {
    "pollingIntervalInS": "30",
    "requireInitialSync": true,
    "observedCertificates": ["link to my cert"],
    "certificateStoreName": "",
    "linkOnRenewal": false,
    "certificateStoreLocation": "/tmp"
  }
}
```

Second update (which was applied correctly)
```
{
  "secretsManagementSettings": {
    "pollingIntervalInS": "30",
    "requireInitialSync": true,
    "observedCertificates": ["link to my cert"],
    "certificateStoreName": "",
    "linkOnRenewal": false,
    "certificateStoreLocation": "/tmp"
  }
}
```

Next update (which was ignored)
```
{
  "secretsManagementSettings": {
    "pollingIntervalInS": "35",
    "requireInitialSync": true,
    "observedCertificates": [],
    "certificateStoreName": "",
    "linkOnRenewal": false,
    "certificateStoreLocation": "/tmp"
  }
}
```

What I see on vm side:
There is a dir "/var/lib/waagent/Microsoft.Azure.KeyVault.KeyVaultForLinux-2.1.1774.23/config/" which seems store configuration for extension
```
ls /var/lib/waagent/Microsoft.Azure.KeyVault.KeyVaultForLinux-2.1.1774.23/config/ -1
0.settings
1.settings
2.settings
3.settings
4.settings
HandlerState
HandlerStatus
```
Files from 0 to 4 contain settings from my keyvault_ext.json file. But no new versions appear after near 4-5 updates

**Comment by yonzhan** [comment]
Compute

**Comment by izenk** [comment]
Noticed one thing:
empty list of observed certs is not allowed - if I try to install extension (first time execute az vm extension set) and set setting "observedCertificates" to [], it fails with error "observedCertificates can't be empty". **But** if I try to **update** extension settings (when it was already installed) there are no any errors, "az vm extension set" just shows "Running". On vm side there are no any errors in extension logs or waagent logs. So may be extension just silently ignores new settings, when  "observedCertificates" is set to [] (which is not allowed) and that is why --force-update has no effect.

**Comment by zhoxing-ms** [comment]
Could you send me the debug log by email, my email address is Zhou.Xing@microsoft.com, thanks

**Comment by izenk** [comment]
what kind of debug log do you need? from az cli or extension or waagent?

**Comment by zhoxing-ms** [comment]
Please add `--debug` parameter after the executed command, and then send the printed log to me

**Comment by izenk** [comment]
@zhoxing-ms do you still need debug log?

**Comment by zhoxing-ms** [comment]
@izenk Yes, please send it to me

**Comment by izenk** [comment]
Unfortunately I cant reproduce the problem.. I reinstalled extension and after that I can update configuration without any problems or just get an error if something is wrong.

**Comment by zhoxing-ms** [comment]
OK, maybe the service side has fixed this bug, let me close this issue first. When you can reproduce this issue, please feel free to contact me to reopen it
