### ISSUE TITLE
[Storage] support download managed disk from SASUri + bearer token

### ISSUE THREAD

**Issue by blueww** [Azure/azure-cli#20969]
**Resource Provider**

Storage Dataplane

**Description of Feature or Work Requested**

Download blob from a SASUri of management disk, with a bearer token

Like following is a sample request from .net SDK. 
Note it has both SAS in Uri, and `Authorization: Bearer`
```
HEAD https://md-hdd-zhkcjtvz5j3s.z5.blob.storage.azure.net/q1vl4npgqcpb/abcd?sv=2018-03-28&sr=b&si=fd9b7490-bd27-4ebd-9f49-8e7f40f2c860&sig=[hidden] HTTP/1.1
x-ms-version: 2020-10-02
Accept: application/xml
User-Agent: AzurePowershell/v1.0.0,azsdk-net-Storage.Blobs/12.10.0 (.NET Framework 4.8.4300.0; Microsoft Windows 10.0.19044 )
x-ms-client-request-id: c276f6ac-158e-4a93-b448-9aee351b7a2f
x-ms-return-client-request-id: true
Authorization: Bearer [token hidden]
Host: weirp1.blob.core.windows.net
Connection: Keep-Alive
```

**Minimum API Version Required**

TBD
(per my test, it works on 2020-10-02 API version.)

**Swagger Link**

No Swagger change

**Target Date**

TBD, firstly it's better we can provide private package for CLI for internal test.

**Comment by yonzhan** [comment]
Storage

**Comment by evelyn-ys** [comment]
Need Storage data plane Python SDK team to confirm if it's supported or not.

**Comment by jiasli** [comment]
Is there any document describing why and how SAS and Bearer token should be used at the same time? Is this similar to https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas ?

**Comment by blueww** [comment]
@jiasli 
Doc has shared in teams. 
The usage is not user delegation SAS. It need both SAS and bearer token request.
