### ISSUE TITLE
Implement incremental blob copy

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#2099]
https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/incremental-copy-blob

**Comment by timwieman** [comment]
Python SDK 0.34.0 with PageBlobService incremental_copy_blob API was released:  https://github.com/Azure/azure-storage-python/blob/master/azure/storage/blob/pageblobservice.py#L206

**Comment by derekbekoe** [comment]
The change from 0.33.0 to 0.34.0 changes the storage data-plane API that is used from 2015-07-08 to 2016-05-31.
https://github.com/Azure/azure-storage-python/blob/master/ChangeLog.md#version-0340

Does 0.34.0 still support the older API version? If not, upgrading the SDK version involves much more than adding support for incremental_copy_blob. For instance if API version 2016-05-31 is not available on sovereign clouds, all data-plane storage commands would stop working on this cloud.

**Comment by troydai** [comment]
It was done.
