### ISSUE TITLE
az consumption budget show returns error

### ISSUE THREAD

**Issue by LotteVoorhorst** [Azure/azure-cli#20995]
## Describe the bug

When running `az consumption budget show`, I get the following error: 

`(400) You are using old version :2018-01-31 with new filter interface - change the version to 2019-04-01-preview (Request ID: 95daf08c-61fc-496f-85a6-aa81ac5b2889)`

Any idea on how to fix this? 

**Command Name**
`az consumption budget show`

**Errors:**
```
(400) You are using old version :2018-01-31 with new filter interface - change the version to 2019-04-01-preview (Request ID: 95daf08c-61fc-496f-85a6-aa81ac5b2889)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az consumption budget show --budget-name {}`

## Expected Behavior
The commando returns a budget and its information. 

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.32.0

Extensions:
account 0.2.1
application-insights 0.1.14
authV2 0.1.1
azure-devops 0.20.0
log-analytics-solution 0.1.1
portal 0.1.2
scheduled-query 0.4.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to service team

**Comment by yougotdirked** [comment]
Hi @LotteVoorhorst, Is there any update on this? I have a similar problem which causes a lot of trouble in our DEV tenant...
I outlined it here on stackoverflow: 
https://stackoverflow.com/questions/71485636/az-module-problem-get-azconsumptionbudget-returns-422-unproccessable-entity

Ill come back to this thread to check if there's any news..

**Comment by DevonK3** [comment]
same issue here.

```
 > az consumption budget show --budget-name MyBudget

Command group 'consumption' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(400) You are using old version :2018-01-31 with new filter interface - change the version to 2019-04-01-preview (Request ID: 99c555ef-d135-47cd-baaa-85a4124b3771)
```
