### ISSUE TITLE
[2.32.0] az aks update --enable-secret-rotation fails : 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by ianjirka** [Azure/azure-cli#21003]
## Describe the bug
az aks update --enable-secret-rotation fails with opaque error.

**Command Name**
`az aks update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 2298, in aks_update
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/decorator.py", line 5886, in update_default_mc_profile
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/decorator.py", line 5832, in update_addon_profiles
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/decorator.py", line 5766, in update_azure_keyvault_secrets_provider_addon_profile
TypeError: 'NoneType' object does not support item assignment

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Not sure if there are other preconditions unique to my environment.
If it is useful, I enabled the plugin via Bicep template as such:
```bicep
addonProfiles: {
      azureKeyvaultSecretsProvider: {
        enabled: true
      }
    }
```

- `az aks update -g {} -n {} --enable-secret-rotation`

## Expected Behavior
Autorotation is enabled.

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.32.0 *

Extensions:
azure-devops 0.20.0
ssh 1.0.0

```json
{
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.22.0",
    "ssh": "1.0.0"
  }
}
```
```
## Additional Context

<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by yonzhan** [comment]
route to service team

**Comment by navba-MSFT** [comment]
@ianjirka Apologies for late reply. I was able to run the below command and it ran successfully.

>az aks enable-addons --addons azure-keyvault-secrets-provider --name myAKSCluster --resource-group myResourceGroup
az aks update -g myResourceGroup -n myAKSCluster --enable-secret-rotation

I am sending you the az version that I used. Could you please try with the same and let me know if you face any issues? Awaiting your reply.

>az version
{
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.51",
    "application-insights": "0.1.14",
    "blueprint": "0.3.1",
    "storage-blob-preview": "0.6.1"
  }
}

**Comment by ianjirka** [comment]
Thank you @navba-MSFT.  Unfortunately I still get the same behavior.  

One thing I noticed is when I leave out --enable-secret-rotation, it gives me a list of parameters, but that is not one of them.  Is there another thing I need to register?

```ps
PS G:\rep\uhe> az aks update -g xxx --name yyy
Please specify one or more of "--enable-cluster-autoscaler" or "--disable-cluster-autoscaler" or "--update-cluster-autoscaler" or "--cluster-autoscaler-profile" or "--load-balancer-managed-outbound-ip-count" or "--load-balancer-outbound-ips" or "--load-balancer-outbound-ip-prefixes" or "--load-balancer-outbound-ports" or "--load-balancer-idle-timeout" or "--auto-upgrade-channel" or "--attach-acr" or "--detach-acr" or "--uptime-sla" or "--no-uptime-sla" or "--api-server-authorized-ip-ranges" or "--enable-aad" or "--aad-tenant-id" or "--aad-admin-group-object-ids" or "--enable-ahub" or "--disable-ahub" or "--windows-admin-password" or "--enable-managed-identity" or "--assign-identity" or "--enable-azure-rbac" or "--disable-azure-rbac" or "--enable-public-fqdn" or "--disable-public-fqdn" or "--tags" or "--nodepool-labels".
```

**Comment by ianjirka** [comment]
I did just try with the aks-preview extension enabled - same behavior.

```ps
> az version
{
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.51",
    "azure-devops": "0.22.0",
    "ssh": "1.0.0"
  }
}
```

**Comment by navba-MSFT** [comment]
@ianjirka There is no issue on the AzCLI side as the same command worked for me. So could you please use the most recent version of [Python libraries ](https://www.python.org/downloads/) and test again? I am using the below version if that helps:

>python --version
Python 3.10.0

Please let me know if you see any issues after upgrading the Python version. Awaiting your reply.

**Comment by ianjirka** [comment]
I have the same python version as you.  Is there some additional tracing I can enable to help track this down?

```ps1
PS> python --version
Python 3.10.0
```

**Comment by ianjirka** [comment]
I do think the major clue is `--enable-secret-rotation` isn't offered as a valid flag when I don't specify any flag (see my previous comment).  Do you know what component that comes from?

**Comment by navba-MSFT** [comment]
@ianjirka While I do some research on what component that parameter comes from ? Could you please refer this github thread for the similar issue and try workaround suggested there which is to disable the addon and then enable it again:

>az aks disable-addons -g {resource_group_name} -n {cluster_name} -a azure-keyvault-secrets-provider 
az aks enable-addons -g {resource_group_name} -n {cluster_name} -a azure-keyvault-secrets-provider --enable-secret-rotation

Awaiting your reply.

**Comment by ianjirka** [comment]
I ran into a similar issue as the person on the other thread - I can't remove because it is in use

```
>az aks disable-addons -g x --name y -a azure-keyvault-secrets-provider
The behavior of this command has been altered by the following extension: aks-preview
(BadRequest) AzureKeyvaultSecretsProvider addon cannot be disabled due to more than 0 Secret Provider Classes
Code: BadRequest
Message: AzureKeyvaultSecretsProvider addon cannot be disabled due to more than 0 Secret Provider Classes
```

I don't want to un-deploy anything to attempt a workaround at the moment - this is a production cluster.

**Comment by mkemmerz** [comment]
Any update on this? The disable and enable of the addon takes quite some time and does only work sometimes on the cluster for us.

**Comment by olsenme** [comment]
@mkemmerz  is it just this addon that takes alot of time to disable/enable, or have you experienced the same with other addons?

**Comment by dingliu** [comment]
I had the same issue:

```
az aks update --resource-group '<RG_NAME>' --name '<CLUSTER_NAME>' --enable-secret-rotation --rotation-poll-interval 2m
```

```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 2369, in aks_update
    mc = aks_update_decorator.update_default_mc_profile()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/decorator.py", line 6061, in update_default_mc_profile
    mc = self.update_addon_profiles(mc)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/decorator.py", line 6007, in update_addon_profiles
    self.update_azure_keyvault_secrets_provider_addon_profile(azure_keyvault_secrets_provider_addon_profile)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/decorator.py", line 5943, in update_azure_keyvault_secrets_provider_addon_profile
    ] = "true"
TypeError: 'NoneType' object does not support item assignment
```

The OS is Ubuntu 20.04 running on WSL 2, kernel version `5.10.60.1-microsoft-standard-WSL2`.

The version of Az CLI is:

```
az --version
azure-cli                         2.33.1
core                              2.33.1
telemetry                          1.0.6
Extensions:
azure-devops                      0.18.0

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

Python location '/opt/az/bin/python3'

Python (Linux) 3.6.10 (default, Feb 14 2022, 04:04:37)
[GCC 9.3.0]
```

**Comment by dingliu** [comment]
I looked at #20438 and noticed something from the suggested workaround:

When querying the AKS cluster **before** disabling and re-enabling the `azure-keyvault-secrets-provider` addon, it has a `null` valued `config`:

```
az aks show --resource-group '<RG_NAME>' --name '<CLUSTER_NAME>' --output json | jq '.addonProfiles'
```

```
{
  "azureKeyvaultSecretsProvider": {
    "config": null,
    "enabled": true,
    "identity": {
      "clientId": "<CLIENT_ID>",
      "objectId": "<OBJECT_ID>",
      "resourceId": "<RESOURCE_ID>"
    }
  },
  ...
}
```

**After** disabling and re-enabling the `azure-keyvault-secrets-provider` addon, querying the AKS cluster returns a properly populated `config`

```
{
  "azureKeyvaultSecretsProvider": {
    "config": {
      "enableSecretRotation": "false",
      "rotationPollInterval": "2m"
    },
    "enabled": true,
    "identity": {
      "clientId": "<CLIENT_ID>",
      "objectId": "<OBJECT_ID>",
      "resourceId": "<RESOURCE_ID>"
    }
  },
  ...
}
```

I encountered this issue on a brand new AKS cluster, which is created only about 10 minutes. However it is created from an ARM template deployment with below specifications:

```
"addonProfiles": {
  "azureKeyvaultSecretsProvider": {
    "enabled": true
  }
}
```

I was wondering if it is possible that the `config` of the `azure-keyvault-secrets-provider` addon will be `null` valued, when the addon is provisioned along with the AKS cluster through an ARM template like above? Thanks.

**Comment by dbielik** [comment]
If you cannot (or don't want to) disable addon, then rotation can be enabled directly using REST API
```bash
# get current config
az rest --method GET 'https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{resourceName}?api-version=2022-01-01' > update.json

# update config
az rest --method PUT 'https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{resourceName}?api-version=2022-01-01' --body @update.json
```

For update you only need AKV section in addon profiles
```json
{
  "id": "<RESOURCE_ID>",
  "location": "<LOCATION>",
  "name": "<CLUSTER_NAME>",
  "properties": {
    "addonProfiles": {
      "azureKeyvaultSecretsProvider": {
        "config": {
          "enableSecretRotation": "true",
          "rotationPollInterval": "2m"
        },
        "enabled": true,
        "identity": {
          "clientId": "<CLIENT_ID>",
          "objectId": "<OBJECT_ID>",
          "resourceId": "<RESOURCE_ID>"
        }
      }
    }
  },
  "type": "Microsoft.ContainerService/ManagedClusters"
}

```

**Comment by navba-MSFT** [comment]
@dbielik Thanks for sharing the plan.
@ianjirka @dingliu Could you please try the [above mentioned plan ](https://github.com/Azure/azure-cli/issues/21003#issuecomment-1080593340) and check if that helps ? Awaiting your reply.

**Comment by dingliu** [comment]
@navba-MSFT Thank you for reminding.

I'm intentionally adding the `config` part to the definition of `azureKeyvaultSecretsProvider` to avoid this issue right now.

However, my understanding of this ticket is that there are two things caused this issue:

- When provisioning an AKS cluster `azureKeyvaultSecretsProvider` addon, the Azure Resource Manager backend won't populate the `config` part with a default value that is other than `null`. To me this seems not to be an optimal option.
- When trying to update the secret rotation setting of the `azureKeyvaultSecretsProvider` addon, `az aks update --enable-secret-rotation` command is not able to handle the scenario of `null` valued `config` property. This seems not to be an optimal decision as well.

Please consider improving the robustness of `az aks update --enable-secret-rotation` command. Thank you.

**Comment by ianjirka** [comment]
@navba-MSFT - adding the `config` to `azureKeyvaultSecretsProvider` worked for me.  I agree with @dingliu that this could be more robust, but I am unblocked.  Thank you!

**Comment by SindibadJafar** [comment]
@dbielik god bless you dude, you saved me from destroying a cluster

**Comment by navba-MSFT** [comment]
@ianjirka Thanks for confirmation and feedback. The Service team is looped in this email can look into this feedback. If you have any questions in the meantime, feel free to ask.

**Comment by ebbypeter** [comment]
Adding the config with a variation of the [above approach](https://github.com/Azure/azure-cli/issues/21003#issuecomment-1080593340) worked for me... 
I was running the command from PowerShell and  I had to get the contents of the update.json to a variable and pass it to the put method...

So the steps were:
```
# get current config
az rest --method GET --url 'https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{resourceName}?api-version=2022-01-01' > update.json

# edit the update.json file as shown in the below section

# get the update.json data. 
$updateContent = = Get-Content -Path .\update.json

# update config
az rest --method PUT --url 'https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{resourceName}?api-version=2022-01-01' --body $updateContent
```

update.json
``` json
{
  "id": "<RESOURCE_ID>",
  "location": "<LOCATION>",
  "name": "<CLUSTER_NAME>",
  "properties": {
    "addonProfiles": {
      "azureKeyvaultSecretsProvider": {
        "config": {
          "enableSecretRotation": "true",
          "rotationPollInterval": "2m"
        },
        "enabled": true,
        "identity": {
          "clientId": "<CLIENT_ID>",
          "objectId": "<OBJECT_ID>",
          "resourceId": "<RESOURCE_ID>"
        }
      }
    }
  },
  "type": "Microsoft.ContainerService/ManagedClusters"
}
```

> if you are getting 'Unsupported Media Type' error, convert the update.json with the following
> * escaping the " (double qoute) to \" (slash double quote) 
> * making the json to a single line
