### ISSUE TITLE
Bot Service az bot authsetting show - Scopes filed is not returned by az bot authsetting show 

### ISSUE THREAD

**Issue by dawwa** [Azure/azure-cli#21011]
**Version** 
 2.22.1

**Describe the bug**
Scope is not included in the return value of `az bot authsetting show`

**To Reproduce**
* Create a Bot Auth Setting `MyTestAuthSetting` with `Azure Active Directory v2`
* Fill up the fields and have some test value in the `Scopes` filed.
* In PowerShell, try to use the following code to loop through all the properties in the return result.
```powershell
# Load setting details
$sourceSettingDetail = az bot authsetting show --subscription $subscriptionId --resource-group $resourceGroup --name $botName --setting-name "MyTestAuthSetting" | Out-String | ConvertFrom-Json
		
# Check the returned value
$parameters = @()
foreach ($parameter in $sourceSettingDetail.properties.parameters) {
	Write-Host $parameter
}
```

**Expected behavior**
The `Scopes` field value can be found in the return result

**Comment by yonzhan** [comment]
route to service team

**Comment by dawwa** [comment]
open in the bf cli repo
https://github.com/microsoft/botframework-cli/issues/1333
