### ISSUE TITLE
Does Azure Cli work on AIX?

### ISSUE THREAD

**Issue by datadeveloper1** [Azure/azure-cli#21021]
Hi everyone, does anyone know if Azure Cli works on AIX? thanks.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Hi @datadeveloper1, unfortunately, we don't officially support AIX, but you may follow https://github.com/Azure/azure-cli/issues/20476#issuecomment-1007131837 and try to play around.

**Comment by ruudhanegraaf** [comment]
@datadeveloper1: Hi datadeveloper1.
We're also intending to use the Azure CLI on AIX. Did you get it working, or did you encounter any problems?
