### ISSUE TITLE
Install `az login` only

### ISSUE THREAD

**Issue by th0ger** [Azure/azure-cli#21031]
Hi, 
Is it possible to install a lightweight version of `az login`?

We're installing just `az login` for CI/CD jobs (with `pip`/`pipenv`). But installing `azure-cli` downloads an extreme amount of dependencies for ever sub module.

I have tried to install [azure-cli-profile](https://pypi.org/project/azure-cli-profile/), but is does not provide the cli.

Othwerwise, it would be super useful to be able to install selected [command_modules](https://github.com/Azure/azure-cli/tree/dev/src/azure-cli/azure/cli/command_modules) via python "extras".

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Currently, `az login` is part of `azure-cli` package and there is no way to install it separately. [`azure-cli-profile`](https://pypi.org/project/azure-cli-profile/) is the old package for `az login` before all command modules are merged into one monolithic `azure-cli` package.

**Comment by th0ger** [comment]
Why was this closed?
This feature request is still relevant to us.

**Comment by yonzhan** [comment]
We have no way to install `az login` separately and will track loose weight of Azure CLI package in https://github.com/Azure/azure-cli/issues/7387

**Comment by th0ger** [comment]
@yonzhan, yes i get it, @jiasli already said that.

But that's not how feature requests work... You can't close a feature request by arguing that the feature is not implemented... That's what status "open" is for.

It can be a decision to "won't fix" from the PM/core team (based on e.g. architectural limitations), but that dialogue has not taken place here.

Even though the size of azure-cli is trimmed, it will install a huge amount of unneeded dependencies for users only needing az login (which is a very common scenario). It takes time to install, but also clutters the venv and increases the risk of conflicts/bugs.

Is it possible to implement "extras" python modules?

**Comment by se7enack** [comment]
In a world of lightweight containers this would be great. I can't understand why this was chose to closed. I understand that it would take work, everything does.

**Comment by martinitus** [comment]
Reopened this as #27755
