### ISSUE TITLE
aks pod identity tutorial cannot create the proper aks any help !

### ISSUE THREAD

**Issue by wassimbenregaya1** [Azure/azure-cli#21049]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
cannot import name 'edge_zone_type'
Traceback (most recent call last):
lib/python3.6/site-packages/knack/cli.py, ln 231, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 556, in execute
    self.commands_loader.load_arguments(command)
site-packages/azure/cli/core/__init__.py, ln 502, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
.azure/cliextensions/aks-preview/azext_aks_preview/__init__.py, ln 47, in load_arguments
    from ._params import load_arguments
.azure/cliextensions/aks-preview/azext_aks_preview/_params.py, ln 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create -g {} -n {} --enable-pod-identity --network-plugin {}`

## Environment Summary
```
Linux-4.15.0-153-generic-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.22.1 *

Extensions:
storage-preview 0.7.3
azure-devops 0.20.0
aks-preview 0.5.41
account 0.2.1

```

**Comment by yonzhan** [comment]
route to service team

**Comment by miwithro** [comment]
@bcho

**Comment by bcho** [comment]
@FumingZhang could you have a look on this one? I guess it's because the version of `azure-cli` is too old to use the newer version of the aks-preview extension here.

**Comment by FumingZhang** [comment]
> @FumingZhang could you have a look on this one? I guess it's because the version of azure-cli is too old to use the newer version of the aks-preview extension here.

Yes, aks-preview 0.5.41 is not compatible with azure-cli 2.22.1, please update your azure-cli to latest version (2.32.0) via `az upgrade`.

**Comment by FumingZhang** [comment]
We recently refactored azure-cli and aks-preview, now aks-preview directly depends on azure-cli, the following are the dependencies between the two. And we are sorry about missing incompatibility hints between some versions.

| aks-preview | acs |
|-|-|
| 0.4.4 ~ 0.5.39 | >=  2.0.49 |
| 0.5.40 ~ 0.5.41 | >= [2.23.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.23.0), missing hint |
| 0.5.42 ~ 0.5.44 | >= [2.27.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.27.0) |
| 0.5.45 ~ 0.5.48 | >= [2.30.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.30.0) |
| 0.5.49 ~ 0.5.50 | >= [2.31.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.31.0) |

**Comment by wassimbenregaya1** [comment]
thanks all for replying im clossing this issue  its like you said the problem was azure-cli version
