### ISSUE TITLE
Strategy to clean up ".azure"

### ISSUE THREAD

**Issue by yasukura** [Azure/azure-cli#21040]
I would like to check my understandings for strategy to clean up “.azure”.
Regarding Azure CLI, related information including logs are written to “.azure” directory.
We have concern on the scenario these kind of log files keep growing.
As my understand, these files are not automatically deleted or rotated. Therefore, we need to consider strategy to get rid of these files, like rm command, etc.  My understanding is correct?
Or, are there any feature to rotate logfiles or delete old files?

**Comment by yonzhan** [comment]
@Jiasli for awareness

**Comment by jiasli** [comment]
Your observation is correct. You may follow this strategy to clean up `~/.azure`:

- All files _directly_ under `~/.azure` should not be deleted, as this will break Azure CLI's login context.
- `~/.azure/commands` and `~/.azure/telemetry` are auto-rotated, so you don't need to delete them.
- Command logs are not enabled by default and you need to turn it on with `az config set logging.enable_log_file=true`. By default without configuring `logging.log_dir`, logs are stored to `~/.azure/commands/az.log`. You may delete this file.
- `~/.azure/commands/telemetry.log` is used by `azure-cli-telemtry` and you may delete this file.

**Comment by yasukura** [comment]
Thank you so much. appreciated.
