### ISSUE TITLE
Comma or space delimited?

### ISSUE THREAD

**Issue by realrubberduckdev** [Azure/azure-cli#21046]
Hi the documentation says that 
```
--aad-allowed-token-audiences
One or more token audiences (space-delimited).
```

But if space delimited argument is provided the resulting resource json seems to update it as a single string instead of an array.
e.g.

if 
```
--aad-allowed-token-audiences "https://first.url https://second.url"
```
resulting json is 
```
"allowedAudiences": [
      "https://first.url https://second.url"
    ],
```

But with comma delimited argument,
```
--aad-allowed-token-audiences "https://first.url, https://second.url"
```
resulting json is 
```
"allowedAudiences": [
      "https://first.url", 
     "https://second.url"
    ],
```

Should the documentation say one or more comma delimited token audiences?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeb196c8-e408-8563-26ba-5c3ae6e38c48
* Version Independent ID: 5f150c9a-e142-2fd7-fe84-b298dc83fd02
* Content: [az webapp auth](https://docs.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/auth.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/auth.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
@realrubberduckdev thanks for reporting. We will fix our documentation to not be misleading. Thanks!

**Comment by panchagnula** [comment]
Updated this with out latest release.
