### ISSUE TITLE
Add shortcut -s for --subscription on 'az account set'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#2105]
'subscription' is a long word to type

It would be nice to have -s as a shortcut, on 'az account set' (and perhaps other 'az account' commands as appropriate.)

Just a thought :)

**Comment by derekbekoe** [comment]
The CLI supports prefix matching of arguments.
```
$ az account set --subscriptiom <sub_id>
$ az account set --sub <sub_id>
```

Even the following would work.
```
$ az account set --s <sub_id>
```

https://docs.python.org/3/library/argparse.html#argument-abbreviations-prefix-matching

**Comment by jimsander** [comment]
Maybe even keep it positional, since it's the only argument to that subcommand
