### ISSUE TITLE
Internal support Q: In closed network, which URLs need to be registered in the firewall?

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#21052]
Azure CLI engineering team, please see the internal support email below.  If your response necessitates a doc update, I can work on that.
********************************************************************
From: Jungkwan Park <jungkwanpark@microsoft.com> 
Sent: Tuesday, January 11, 2022 9:55 PM
To: Michael Blythe <mblythe@microsoft.com>
Subject: Question for official document.

Hello.
After I see below official document, I have a question, so I’m sending email to you.

[Allow the Azure portal URLs on your firewall or proxy server - Azure portal | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-portal/azure-portal-safelist-urls?tabs=public-cloud)
[Get started with Azure Command-Line Interface (CLI) | Microsoft Docs](https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli)

Firstly, I think below questions cannot be directly covered by yourself, 
so it would be appreciative if I know which colleague can cover below question. 😊

I describe question like below:

One of our customer has closed network, (no internet connectivity by default), and he/she installed “Azure CLI” program in Linux Server. 
So, before customer uses “Azure CLI” in closed network, he/she needs to register below URLs or IP addresses, in his/her firewall which protects this closed network.
But, when customer registered below URLs in firewall, this fire shows message, “DNS query was failed, for this URL redirection”

Failed DNS Query URLs are like below :
*.aadcdn.microsoftonline-p.com
*.applicationinsights.io
*.azure-api.net
*.azuredatalakestore.net
*.azureedge.net
*.loganalytics.io
*.microsoftonline.com
*.microsoftonline-p.com
*.msauth.net
*.msftauth.net
*.trafficmanager.net
*.graph.windows.net (Azure AD Graph)

1. So, when customer wants to use “Azure CLI” program in closed network, which URLs need to be registered in firewall?

2. If some URLs failed to URL redirection, is there any other workaround to solve this problem? 
For example, instead of URL, which ip addresses should be opened for “Azure CLI”? in customer’s private firewall? 

I have difficulties in finding appropriate SAP, so it would be appreciative 😊

Thank you.

Best Regards.
Jungkwan Park

**Comment by yonzhan** [comment]
network

**Comment by jiasli** [comment]
> But, when customer registered below URLs in firewall, this fire shows message, “DNS query was failed, for this URL redirection”

Where does this error message come from? Could you or the customer share a screenshot?

Some Azure-related domains Azure CLI accesses can be found at

https://github.com/Azure/azure-cli/blob/3feea02888ea67f033f407174a3a7a340158b81a/src/azure-cli-core/azure/cli/core/cloud.py#L297-L301

However, there are other domains that are not listed here, such as https://aka.ms, https://github.com for other functionalities, like `az upgrade`, `az extension`.

**Comment by dbradish-microsoft** [comment]
@yonzhan , @kairu-ms , @jiasli , I believe this Issue can be closed as we have published [Azure CLI endpoints for proxy bypass](https://learn.microsoft.com/en-us/cli/azure/azure-cli-endpoints?view=azure-cli-latest&tabs=azure-cloud)

**Comment by jiasli** [comment]
Reopening this issue as the list in https://learn.microsoft.com/en-us/cli/azure/azure-cli-endpoints is not complete. I commented at https://github.com/MicrosoftDocs/azure-docs-cli/pull/3412#issuecomment-1413228107.

**Comment by dbradish-microsoft** [comment]
@jiasli, this is PR https://github.com/MicrosoftDocs/azure-docs-cli/pull/3550
