### ISSUE TITLE
az netappfiles volume create --cifs is incorrect

### ISSUE THREAD

**Issue by elfcounsel** [Azure/azure-cli#21054]
Under az netappfiles volume create parameters list it shows:
--cifs
**Allows NFSv3 protocol.** Enable only for NFSv3 type volumes.

accepted values: false, true

I think this should be "Allows SMB protocol. Enable only for SMB type volumes"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 298ada99-369a-1c65-50ca-617931d26b7a
* Version Independent ID: 5fbd1cdf-e27f-8ffe-1c72-14f5d9e186f1
* Content: [az netappfiles volume](https://docs.microsoft.com/en-us/cli/azure/netappfiles/volume?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/netappfiles/volume.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/netappfiles/volume.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by audunn** [comment]
The documentation string has been fixed

```
--cifs
Allows CIFS protocol. Enable only for CIFS type volumes. Exists for backwards compatibility, please use --export-policy-rules --rules instead.

Accepted values: 0, 1, f, false, n, no, t, true, y, yes
```
