### ISSUE TITLE
az network bastion rdp does not recognize valid VM resource ID

### ISSUE THREAD

**Issue by JeffBrownTech** [Azure/azure-cli#21056]
**Describe the bug**
When using the az network bastion rdp command, the command returns that the virtual machine resource ID is not valid.

![az_network_bastion_rdp_error](https://user-images.githubusercontent.com/12574689/150237205-ebd79968-20cb-411e-a865-dc79de7be31f.png)

Reference:
[Connect to a Windows VM](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-to-a-windows-vm)

**To Reproduce**
Follow the guide on the reference link to connect to a Windows VM using Azure Bastion from a Windows 10 system.

**Expected behavior**
Opens the native Windows RDP client to connect to the VM.

**Environment summary**
Git Bash on Windows 10
Azure CLI 2.32.0

**Additional context**
If I use the same command on PowerShell 7, it works as expected. This shows the VM resource ID I am using is accurate. Not sure if this is an issue with the Azure CLI command or maybe an issue with Git Bash on Windows.

**Comment by yonzhan** [comment]
route to service team

**Comment by isamorris** [comment]
Hi there, Bastion PM here. You may have two issues here that aren't allowing you to connect to your VM with the native client. Please check in your VM: 1) Is AADLogin enabled in the "Extensions + Applications" blade of your VM? 2) Also, have you given yourself the role assignment under "Access Control (IAM)" as "Virtual Machine Administrator Login" or "Virtual Machine User Login"?

**Comment by JeffBrownTech** [comment]
I add the permissions and extension and I receive the same error message:

`Please enter a valid Virtual Machine resource Id.`

The error occurs before I get the chance to authenticate. It is currently failing using Git Bash on Windows.

If I take this command and use it in PowerShell 7 (replacing with the appropriate multiline character), the command works as expected. I receive a login prompt and can authenticate using a local account. This shows the virtual machine resource Id I am using in the command is valid. Running the command in Bash seems to think the resource ID in invalid.

**Comment by isamorris** [comment]
Hmm. I'm not sure what is causing the problem here. Please submit a support request so our support team can look into this and better assist you.

**Comment by JeffBrownTech** [comment]
Unfortunately, I am not a business/enterprise, just someone doing labs and testing these features for knowledge gain. I don't have a paid support plan in Azure to open a ticket.

**Comment by aavalang** [comment]
@JeffBrownTech this seems like an issue with GitBash, maybe they are encoding/wrapping the commands which makes it so that the resource cant be found. Can you use powershell on windows?

**Comment by aavalang** [comment]
@yonzhan can you please close this issue? Seems to be something with git bash rather than cli or bastion

**Comment by edgreenberg-mri** [comment]
Way to pass the buck and duck responsibility.  Microsoft owns git, so why not investigate and fix.  Poor support.

**Comment by edgreenberg-mri** [comment]
I found a workaround for this.  I put the 'az network bastion tunnel command' in a good old dos batch file. Saved it on gitbash's path, and ran it a filename.bat (the .bat is important).  Since gitbash seamlessly launched cmd to run this, no need for a cmd window.

**Comment by MHebes** [comment]
For future finders: this might be git bash auto converting the `/subscriptions/asdf` to a windows file path like `subscriptions:/asdf`.

I fixed by prefixing `az` with `MSYS_NO_PATHCONV=1`

So

    MSYS_NO_PATHCONV=1 az network bastion ssh ...

Alternatively, you can probably put an extra slash in front of `/subscriptions` (so, `//subscriptions`)
