### ISSUE TITLE
StaticWebApp:az staticwebapp create - skip GitHub workflow generation

### ISSUE THREAD

**Issue by bmay-cloudwallcapital** [Azure/azure-cli#21058]
Bit of feedback for the CLI team - az staticwebapp create should have an option to NOT create the GitHub action workflow file, in case the user is using Azure Pipelines or another model.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e683c181-f005-a6c8-cb11-74ce557e51f8
* Version Independent ID: 860411b7-f2f1-af2b-b5e2-7d67e1b8e028
* Content: [az staticwebapp](https://docs.microsoft.com/en-us/cli/azure/staticwebapp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/staticwebapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/staticwebapp.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
@panchagnula can you please take a look in to the ask and comment on the same.

**Comment by panchagnula** [comment]
@StrawnSC can you follow up with SWA team on this - AFAIK SWA cannot be used with DevOps pipeline & so this is not specific to CLI.

**Comment by bmay-cloudwallcapital** [comment]
@panchagnula for your reference, DevOps Pipelines can be used with it: https://docs.microsoft.com/en-us/azure/static-web-apps/publish-devops

**Comment by panchagnula** [comment]
@simonaco FYI. @StrawnSC from the learning supporting this on function apps my proposal would be to make this a separate command in azure-cli extensions, which has devops pipeline support as well. See https://github.com/Azure/azure-cli/pull/19716/files
