### ISSUE TITLE
needs sample of an environment yaml file

### ISSUE THREAD

**Issue by danielsc** [Azure/azure-cli#21061]
This page really needs an example of an environment yaml file. 
Just show this one or point to it somehow: https://github.com/Azure/azureml-examples/blob/main/cli/assets/environment/docker-image-plus-conda.yml 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 385ead8e-c1d5-0a76-d717-88b64d19b8cf
* Version Independent ID: 048580a0-834d-90ce-7822-75f483155c94
* Content: [az ml environment](https://docs.microsoft.com/en-us/cli/azure/ml/environment?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/environment.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ml/environment.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team
