### ISSUE TITLE
needs sample of job.yaml and link to schema doc

### ISSUE THREAD

**Issue by danielsc** [Azure/azure-cli#21063]
this page really needs a sample of job.yaml and it needs to link to the schema docs for jobs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636db626-82b8-8d7f-b284-41f6ecffa93b
* Version Independent ID: 62b5f487-5b77-6eb6-499f-2bcf1e95d6ff
* Content: [az ml job](https://docs.microsoft.com/en-us/cli/azure/ml/job?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/job.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ml/job.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team
