### ISSUE TITLE
Need example of dataset creation without yaml file

### ISSUE THREAD

**Issue by danielsc** [Azure/azure-cli#21062]
this page should provide an example of how to create a dataset without creating a yaml file (provide all parameters on the cmd line)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6818cd91-604d-d963-7510-acdb495d87e8
* Version Independent ID: 5f85a963-4a23-ac2c-d6ec-668bbd7766e4
* Content: [az ml dataset](https://docs.microsoft.com/en-us/cli/azure/ml/dataset?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/dataset.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ml/dataset.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team
