### ISSUE TITLE
Pre-check validation for attaching public IPs to NAT gateway service

### ISSUE THREAD

**Issue by aimee-littleton** [Azure/azure-cli#21069]
**Resource Provider**
This request is for the Azure VNet NAT (NAT Gateway) service.

**Description of Feature or Work Requested**
Context:
We have gotten a few customer support cases in which customers forget to attach a public IP address or prefix to NAT gateway and then have issues with being able to use NAT gateway for connecting outbound to the internet. 

In order for NAT gateway to direct traffic from a subnet in a private network to the internet, it must be attached to at least one public IP address or public IP prefix. 

Issue: 
Customers can create a NAT gateway without adding a public IP address. No error messages are generated when creating a NAT gateway without a public IP address or prefix attached.

Requirements for resolving this issue:
Require that customers must do one of the following when creating a new NAT gateway resource:
Create one new public IP address -or-
Create one new public IP prefix -or-
Attach at least one existing and available public IP address in the network to NAT gateway -or-
Attach at least one existing and available public IP prefix in the virtual network to NAT gateway

**Minimum API Version Required**
Will need to follow up on this and provide later

**Swagger Link**
<!--- Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or here is the link to the cli commands for NAT gateway: https://docs.microsoft.com/en-us/cli/azure/network/nat/gateway?view=azure-cli-latest

When you create a nat gateway, you can specify which public IP address or prefix should be attached to NAT gateway, however, currently, NAT gateway can be created without using the --public-ip-address or --public-ip-prefixes commands

**Target Date**
No target date as of yet, but will update if this changes.

**Comment by yonzhan** [comment]
network
