### ISSUE TITLE
different APIs called when create subnet with Azure cli "az network vnet subnet create" and Azure portal

### ISSUE THREAD

**Issue by binblu** [Azure/azure-cli#21065]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
The user account has the full permission Microsoft.Network/virtualNetworks/subnets/,  but did not has the permission Microsoft.Network/virtualNetworks/write. When the user create the subnet on the Azure portal and Azure Cli and find the API called with the below difference, since the user has no permission with Microsoft.Network/virtualNetworks/write, then the AuthorizationFailed happened in the Azure cli command, Azure portal can create the subnet as expected.

API USES FROM PORTAL:
https://management.azure.com/subscriptions/7d5f9f0d-5f8a-4159-9fd5-42435ad8b764/resourceGroups/zne-eds1-n-02-net-rsg/providers/Microsoft.Network/virtualNetworks/zne-eds1-n-02-net-test-00-net/subnets/mksubnettest1?api-version=2019-04-01

Api uses from Azure Cli:
“PUT /subscriptions/7d5f9f0d-5f8a-4159-9fd5-42435ad8b764/resourceGroups/zne-eds1-n-02-net-rsg/providers/Microsoft.Net
work/virtualNetworks/zne-eds1-n-02-net-test-00-net?api-version=2021-05-01 HTTP/1.1"

**To Reproduce**
 Assign the user who will create the subnet with the permission of Vnet read and subnet full permission.
https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-manage-subnet#permissions 

Azure portal create subnet, working.

Azure Cli command: no-working.
az login
# Set subscription by Name
az account set --subscription "zne-eds1-n-test-sbc"
az network vnet subnet create -g zne-eds1-n-02-net-rsg --vnet-name zne-eds1-n-02-net-test-00-net -n mksubtest --address-prefixes 10.95.224.64/28 --network-security-group zne-eds1-n-02-net-test-00-default-nsg --route-table zne-eds1-n-02-net-test-00-default-udr --debug
 
{"error":{"code":"AuthorizationFailed","message":"The client 'manish.kumar6@bp.com' with object id '007afc33-4261-4e81-a735-0bb061073690'
does not have authorization to perform action 'Microsoft.Network/virtualNetworks/write' over scope
'/subscriptions/7d5f9f0d-5f8a-4159-9fd5-42435ad8b764/resourceGroups/zne-eds1-n-02-net-rsg/providers/Microsoft.Network/virtualNetworks/zne-eds1-n-02-net-test-00-net' or the scope is
invalid. If access was recently granted, please refresh your credentials."}}

**Expected behavior**
Since this put action is for subnet, not for Vnet, Azure cli "az network vnet subnet create" should called the API "https://management.azure.com/subscriptions/7d5f9f0d-5f8a-4159-9fd5-42435ad8b764/resourceGroups/zne-eds1-n-02-net-rsg/providers/Microsoft.Network/virtualNetworks/zne-eds1-n-02-net-test-00-net/subnets/" as well, so the permission could be align with the description as the Doc.
https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-manage-subnet#permissions 

**Environment summary**
OS Name	Microsoft Windows 11 Enterprise
Version	10.0.22000 Build 22000

PS C:\WINDOWS\system32> az version
{
  "azure-cli": "2.27.2",
  "azure-cli-core": "2.27.2",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Additional context**

**Comment by yonzhan** [comment]
network

**Comment by necusjz** [comment]
Hi @binblu ,

It seems that currently CLI regards subnet as a sub-property of vnet, so vnet's API will be called when creating subnet.

Since we have no plans to make adjustments in the short term, we provide a workaround here:
If grant write permission is unfeasible, we could use [az rest](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-rest) to invoke a custom request as a workaround.

**Comment by binblu** [comment]
Hi @necusjz 
Thanks for you help on this, the customer has accepted the workaround and the case was closed on CSS side. I think you can close this ticket as well.
