### ISSUE TITLE
Warn users when newer extension versions are masked by an older Azure CLI version

### ISSUE THREAD

**Issue by phealy** [Azure/azure-cli#21078]
**Is your feature request related to a problem? Please describe.**
I've been seeing a lot of issues with customers who have a version of `aks-preview` that's too old for what they're trying to do, but when they do `az extension update -n aks-preview` it doesn't update them because the newer versions have a `min_version` higher than their Azure CLI version.

As an example, let's say I need an AKS feature that depends on aks-preview >= 0.5.49. If I have Azure CLI 2.25.0 installed, this is the result of adding the extension:

```bash
$ az version
{
  "azure-cli": "2.25.0",
  "azure-cli-core": "2.25.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

$ az extension add -n aks-preview
The installed extension 'aks-preview' is in preview.

$ az extension update -n aks-preview
No updates available for 'aks-preview'. Use --debug for more information.

$ az version
{
  "azure-cli": "2.25.0",
  "azure-cli-core": "2.25.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.41"
  }
}
```

Nowhere was I told that there's a newer aks-preview available if I update Azure CLI:

```bash
$ az version
{
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.51",
    "fzf": "1.0.2"
  }
}
```

**Describe the solution you'd like**

Add warning text during `az extension add` and `az extension update` if there are newer extension versions that aren't eligible candidates because their minimum version is higher than the currently installed version.

**Describe alternatives you've considered**

* Error during adding/updating if they can't get the newest version, thus preventing them from any version. This seems much less user friendly.

**Additional context**

I have seen this on at least four or five issues or ICMs just in the last two weeks. It's a common problem.

**Comment by yonzhan** [comment]
Core

**Comment by YuanyuanNi** [comment]
Hi，
     Thank you for your suggesting, we will improve it .
Best wishes.
