### ISSUE TITLE
FunctionApp:[az functionapp list] error on Ubuntu 20.04

### ISSUE THREAD

**Issue by Daxaar** [Azure/azure-cli#21071]
## Describe the bug
On Ubuntu 20.04 with az cli installed from repositories the command failed with exception message as below.  I've tried a number of the commands [in the docs](https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest#az-functionapp-list) without success.

Tested various other commands such as listing resource groups successfully.

**Command Name**
`az functionapp list`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:

An example command from the docs that failed with the exception:

- `az functionapp list --query "[?state=='Running']"`

- _Put any pre-requisite steps here..._

## Expected Behavior
Lists all running function apps.

## Environment Summary
```
Linux-5.13.0-27-generic-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
route to service team

**Comment by Kotasudhakarreddy** [comment]
@Daxaar can you please try with the latest Azure CLI version `2.33.0`.

**Comment by Kotasudhakarreddy** [comment]
closing due to lack of response. Please file a new issue if this is still a problem.
