### ISSUE TITLE
Add Azure CLI support for new service - Microsoft.Network/dnsResolvers

### ISSUE THREAD

**Issue by rahisshaikh** [Azure/azure-cli#21087]
**Resource Provider**

Microsoft.Network/dnsResolvers
Microsoft.Network/dnsForwardingRulesets

**Description of Feature or Work Requested**

Our service is currently in private preview phase. We need to develop the az cli for preview version for now. 

**Minimum API Version Required**

2020-01-01-preview

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs-pr/blob/Microsoft.Network-dnsresolver-2020-01-01-preview/specification/dnsresolver/resource-manager/Microsoft.Network/preview/2020-04-01-preview/dnsresolver.json

**Target Date**

This is expected to be released around March-2022

Swagger Specs: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/dnsresolver/resource-manager/Microsoft.Network/preview/2020-04-01-preview/dnsresolver.json

**Comment by yonzhan** [comment]
network
