### ISSUE TITLE
Cloud App Security has been renamed Defender for Cloud Apps.

### ISSUE THREAD

**Issue by dcurwin** [Azure/azure-cli#21099]
Cloud App Security has been renamed Defender for Cloud Apps.

I'm responsible for Defender for Cloud Apps documentation. Feel free to be in contact with me if you have questions about the rebrand.

Thanks,

David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31d0aa0a-1f5a-1d1d-49dd-164e69a388be
* Version Independent ID: 641d4e73-669e-58e9-f793-fc5d9e9b0ca1
* Content: [az sentinel data-connector](https://docs.microsoft.com/en-us/cli/azure/sentinel/data-connector?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/sentinel/data-connector.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sentinel/data-connector.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by dcurwin** [comment]
@yonzhan @jsntcy @amirkeren  - Any updates?

**Comment by amirkeren** [comment]
@yonzhan sorry, just seeing this. How is this related to Sentinel? What is the ask/issue here?

**Comment by dcurwin** [comment]
@amirkeren @yonzhan  - The page referred to in this issue:

https://docs.microsoft.com/en-us/cli/azure/sentinel/data-connector?view=azure-cli-latest#az-sentinel-data-connector-create-optional-parameters

mentions MCAS (Microsoft Cloud App Security)

That is no longer the name of the product. It should be replaced with Microsoft Defender for Cloud Apps.

**Comment by amirkeren** [comment]
@dcurwin Thanks for bringing it to our attention. We will work on fixing this and will update you once it's done.

**Comment by dcurwin** [comment]
@amirkeren  @yonzhan  - The page in question has still not been updated. Please address this issue.

**Comment by jsntcy** [comment]
@amirkeren, service team need fix swagger file as the help of Azure CLI is generated from swagger. https://github.com/Azure/azure-rest-api-specs/blob/main/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/stable/2022-08-01/DataConnectors.json#L527

**Comment by amirkeren** [comment]
I'll contact the relevant team and have them follow up on this

**Comment by dcurwin** [comment]
@amirkeren  - Any updates?

**Comment by amirkeren** [comment]
@dcurwin reached out to the owners for update

**Comment by dcurwin** [comment]
@amirkeren  - Is there a work item open where I can follow the progress?

**Comment by amirkeren** [comment]
@dcurwin will check and let you know

**Comment by dcurwin** [comment]
@amirkeren  - Any news?

**Comment by amirkeren** [comment]
@dcurwin I'm sorry there is no response yet from the team. I pinged them again and if I don't get a reply in the next few days, I will escalate this further.

**Comment by dcurwin** [comment]
@amirkeren  - Any updates?

**Comment by amirkeren** [comment]
@dcurwin Please check the ADO item for updates. The team doesn't use Github for comms. If you don't get a response there please let me know and I'll escalate.
