### ISSUE TITLE
IPV4 or CIDR for Storage, event hub etc

### ISSUE THREAD

**Issue by t-dedah** [Azure/azure-cli#21098]
[Customer Query]

> 
> I am trying to add 2 IP or CIDR ranges to my storage account or event hub namespsace in this case using az cli but it won't let me add more than one at a time. I am using this following command:
> az eventhubs namespace network-rule add
> --namespace-name ns-name
> --resource-group rg-name
> --ip-address 10.1.0.0/16,162.168.0.0/24 (allows me add one IP, how can I add more IPs here?)
> I keep getting this error when I add more than one IP:
> ERROR: BadRequest: The provided ip address mask does not follow the CIDR notation.
> 
> When I run the command twice with separate IPs then it works fine but I don't want that. I want to be able to add more IPs to one single command such as above az cli script. Any ideas? Thanks!

Issue - https://github.com/Azure/cli/issues/70

**Comment by yonzhan** [comment]
route to service team

**Comment by t-dedah** [comment]
Hi @yonzhan do we have any updates on this issue?

**Comment by yonzhan** [comment]
eventhub service team should take a look

**Comment by Saglodha** [comment]
@t-dedah, Thanks for bringing this to our attention. I would look at API structure, triage internally and get back to you with more updates.
