### ISSUE TITLE
None error message in az webapp deployment source config

### ISSUE THREAD

**Issue by Prometeus99** [Azure/azure-cli#21107]
## Describe the bug

**Command Name**
`az webapp deployment source config`

**Errors:**
```
'None' app doesn't exist

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config --name {} --resource-group {} --repo-url {} --branch {} --manual-integration`

## Environment Summary
```
Linux-5.4.0-1067-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.32.0

Extensions:
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to service team
