### ISSUE TITLE
Missing Python module in azure-cli on Ubuntu

### ISSUE THREAD

**Issue by fdouw** [Azure/azure-cli#21110]
## Describe the bug
azure-cli gives an error when trying to list webapps.

**Command Name**
`az webapp list`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behaviour. Note that argument values have been redacted, as they may contain sensitive information.

- in Docker image:
```Dockerfile
FROM ubuntu:latest
RUN apt update
RUN apt install -y azure-cli
```
- connect to azure tenant via `az login --tenant <tenantId>`
- run `az webapp list`

## Expected Behaviour
- I expected a list of webapps in the tenant (1 exists)

## Environment Summary
```
Linux-5.13.0-27-generic-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by fdouw** [comment]
I haven't tested this exhaustively, but it seems to happen with any `az webapp ...` command; at least in this installation.

**Comment by yonzhan** [comment]
route to service team

**Comment by fdouw** [comment]
I think this is similar to #21205. I was using the `azure-cli` from the Ubuntu repo, the version from the Microsoft repo does not seem to have this bug anymore.
