### ISSUE TITLE
az keyvault commands fail on WSL ubuntu

### ISSUE THREAD

**Issue by jmagosta** [Azure/azure-cli#21118]
## Describe the bug

**Command Name**
`az keyvault secret list`

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
<frozen importlib._bootstrap>, ln 961, in _find_and_load_unlocked
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault secret list --vault-name {}`

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```
## debug output for adding keyvault extension

(base) jma@LAPTOP-5K7B8M9C:/mnt/c/Users/joagosta$ az extension add --name keyvault --debug
Command arguments: ['extension', 'add', '--name', 'keyvault', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f37f689f550>, <function OutputProducer.on_global_arguments at 0x7f37f6877280>, <function CLIQuery.on_global_arguments at 0x7f37f68144c0>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.002 seconds.
Loaded module 'acs' in 0.004 seconds.
Loaded module 'advisor' in 0.000 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.002 seconds.
Loaded module 'apim' in 0.001 seconds.
Loaded module 'appconfig' in 0.001 seconds.
Loaded module 'appservice' in 0.013 seconds.
Loaded module 'backup' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.004 seconds.
Loaded module 'batchai' in 0.001 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'botservice' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.001 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.001 seconds.
Loaded module 'configure' in 0.000 seconds.
Loaded module 'consumption' in 0.001 seconds.
Loaded module 'container' in 0.001 seconds.
Loaded module 'cosmosdb' in 0.003 seconds.
Loaded module 'deploymentmanager' in 0.001 seconds.
Loaded module 'dla' in 0.001 seconds.
Loaded module 'dls' in 0.001 seconds.
Loaded module 'dms' in 0.001 seconds.
Loaded module 'eventgrid' in 0.001 seconds.
Loaded module 'eventhubs' in 0.001 seconds.
Loaded module 'extension' in 0.000 seconds.
Loaded module 'feedback' in 0.000 seconds.
Loaded module 'find' in 0.000 seconds.
Loaded module 'hdinsight' in 0.001 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.002 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.003 seconds.
Loaded module 'kusto' in 0.001 seconds.
Loaded module 'lab' in 0.001 seconds.
Loaded module 'managedservices' in 0.001 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.002 seconds.
Loaded module 'natgateway' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.001 seconds.
Loaded module 'network' in 0.011 seconds.
Loaded module 'policyinsights' in 0.001 seconds.
Loaded module 'privatedns' in 0.002 seconds.
Loaded module 'profile' in 0.001 seconds.
Loaded module 'rdbms' in 0.002 seconds.
Loaded module 'redis' in 0.001 seconds.
Loaded module 'relay' in 0.002 seconds.
Loaded module 'reservations' in 0.001 seconds.
Loaded module 'resource' in 0.003 seconds.
Loaded module 'role' in 0.002 seconds.
Loaded module 'search' in 0.001 seconds.
Loaded module 'security' in 0.001 seconds.
Loaded module 'servicebus' in 0.002 seconds.
Loaded module 'servicefabric' in 0.001 seconds.
Loaded module 'signalr' in 0.001 seconds.
Loaded module 'sql' in 0.003 seconds.
Loaded module 'sqlvm' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.011 seconds.
Loaded module 'vm' in 0.007 seconds.
Loaded all modules in 0.110 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/jma/.azure/cliextensions'
Found 1 extensions: ['azure-devops']
Extensions directory: '/home/jma/.azure/cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.81 min_required=2.0.69 max_required=None
Extensions directory: '/home/jma/.azure/cliextensions'
Loaded extension 'azure-devops' in 0.011 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f37f62aa940>]
az_command_data_logger : command args: extension add --name {} --debug
metadata file logging enabled - writing logs to '/home/jma/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f37f62449d0>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f37f6278d30>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f37f6278e50>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f37f5574820>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f37f6877310>, <function CLIQuery.handle_query_parameter at 0x7f37f6814550>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f37f6278dc0>, <function handler at 0x7f37f5431700>, <function DevCommandsLoader.post_parse_args at 0x7f37f4c2b160>]
Extensions directory: '/home/jma/.azure/cliextensions'
urllib3.connectionpool : Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool : https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool : Starting new HTTPS connection (1): azcliextensionsync.blob.core.windows.net:443
urllib3.connectionpool : https://azcliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 1513037
No extension found with name 'keyvault'

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
`azure-cli 2.0.81` is not our official Azure CLI. 

Please install our CLI following https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
The latest version is 2.32.0

**Comment by evelyn-ys** [comment]
#19640 for details
