### ISSUE TITLE
sdk-auth Switch Explanation

### ISSUE THREAD

**Issue by ptiseo-tegria** [Azure/azure-cli#21124]
The --sdk-auth switch explanation needs to be better defined with a fuller explanation, and information about defaults and such.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ad/sp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ad/sp.yml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Please see

- https://github.com/Azure/azure-cli/issues/20743
- https://github.com/Azure/azure-cli/issues/19949
- https://github.com/Azure/azure-cli/pull/19414
- https://github.com/Azure/login/issues/190
