### ISSUE TITLE
Executive Order SBOM addition

### ISSUE THREAD

**Issue by chasewilson** [Azure/azure-cli#21120]
**Is your feature request related to a problem? Please describe.**

To meet standards set by [CyberEO](https://eng.ms/docs/initiatives/executive-order/executive-order-requirements/executiveorderoncybersecurity/overview), the Azure DevOps pipeline needs to be updated to produce and maintain an SBOM for Azure CLI releases. 

**Describe the solution you'd like**

Add [SBOM Generator](https://www.1eswiki.com/wiki/ADO_sbom_Generator) to Azure DeVOps Pipeline

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
To meet standards set by CyberEO

**Comment by yonzhan** [comment]
Some packages are missing from the SBOM generator (ado-sbom-generator)

**Comment by wangzelin007** [comment]
> Some packages are missing from the SBOM generator (ado-sbom-generator)

Add two issues here:
https://github.com/microsoft/component-detection/issues/73
https://github.com/microsoft/component-detection/issues/74
