### ISSUE TITLE
Not able to complete this excersise

### ISSUE THREAD

**Issue by girishofficial** [Azure/azure-cli#21121]
## Describe the bug

**Command Name**
`az appservice plan create`

**Errors:**
```
(ResourceGroupBeingDeleted) The resource group 'learn-1f879ab7-9d76-40d1-bbd7-5a97c244b9b3' is in deprovisioning state and cannot perform this operation.
Code: ResourceGroupBeingDeleted
Message: The resource group 'learn-1f879ab7-9d76-40d1-bbd7-5a97c244b9b3' is in deprovisioning state and cannot perform this operation.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan create --name {} --resource-group {} --location {} --sku {}`

## Environment Summary
```
Linux-5.4.0-1067-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.32.0

Extensions:
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to service team

**Comment by seligj95** [comment]
It looks like you tried creating a resource in a resource group that was being deleted. Please try again with a new resource group. Closing this for now.
