### ISSUE TITLE
azure namespace stuck on registering

### ISSUE THREAD

**Issue by isha199409** [Azure/azure-cli#21127]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I am trying to register Microsoft.MachineLearningServices through powershell. I ran the commands:
Connect-AzAccount
Set-AzContext -Subscription "<sub name>"
Register-AzResourceProvider -ProviderNamespace Microsoft.MachineLearningServices

However its stuck on registering since the last few hours. 
![image](https://user-images.githubusercontent.com/98474735/151193550-2d997028-d6f8-45c3-acff-de54daee0148.png)

Please help in resolving this. 

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Please open this issue in azure-powershell repo
