### ISSUE TITLE
az vm run-command results in ERROR: InvalidApiVersionParameter

### ISSUE THREAD

**Issue by bitdeft** [Azure/azure-cli#21137]
**Describe the bug**

It seems the API being used to run az command by the azure-cli is too new for Az Compute resource provider? Target VM is on East US 2, Azure Commercial Cloud.

Error is as follows:
```
Code: InvalidApiVersionParameter
Message: The api-version '2021-07-01' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
Boot config for cvuv-appliance1: 
```

**To Reproduce**

 
Command being run:
```
az vm run-command invoke -g "$resourceGroup" -n "$vm" --command-id RunShellScript --scripts "echo 'test az run command'"
```
This is just an example, but populate the $resoruceGroup and $vm variables as needed and the error will return the same.

**Expected behavior**

The command should have run on the target VM. It was running fine a few days ago. As far as I know the API didn't change?

**Environment summary**

Azure CLI Version:
```
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
```

OS: Debian WSL - 5.10.60.1-microsoft-standard-WSL2

/etc/os-release contents:
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
```

**Comment by yonzhan** [comment]
Compute

**Comment by bitdeft** [comment]
Sorry, this is incorrect. Viewing https://github.com/Azure/azure-cli/issues/10641 I noticed I am having the same issue. I simply did not define one of the shell variables. The error does not match what is wrong here.

You can close the issue or make a new one regarding this error code inaccuracy. Thanks
