### ISSUE TITLE
`az login` opens Edge (if installed) instead of default browser on linux

### ISSUE THREAD

**Issue by PauloGDPeixoto** [Azure/azure-cli#21136]
`az login` always opened a window in my default browser, until I installed Edge. From that moment on, when I run `az login`, the message still states that it will open the login window in the default browser, but launches Edge instead.

This is happening on linux, I don't know if it happens in Windows/Mac OS as well.

I'm running the latest version of az-cli from the dnf repo.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
I believe this is the expected behavior of MSAL (https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/388). +@rayluo

**Comment by rayluo** [comment]
> I believe this is the expected behavior of MSAL ([AzureAD/microsoft-authentication-library-for-python#388](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/388)). +@rayluo

That is correct.

"It is not a bug. It is a feature." <sup>TM</sup>

**Comment by PauloGDPeixoto** [comment]
> > I believe this is the expected behavior of MSAL ([AzureAD/microsoft-authentication-library-for-python#388](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/388)). +@rayluo
> 
> That is correct.
> 
> "It is not a bug. It is a feature." TM

Understood. Is there any configuration I can add to azure cli in order to disable this feature?

**Comment by rayluo** [comment]
@PauloGDPeixoto , quick question. When you use Edge to sign in, does your sign-in experience include a prompt of "Stay signed-in"?

![image](https://user-images.githubusercontent.com/821550/151639180-f3e5a84a-7f12-4241-b771-21c493bf4752.png)

**Comment by PauloGDPeixoto** [comment]
>@PauloGDPeixoto , quick question. When you use Edge to sign in, does your sign-in experience include a prompt of "Stay signed-in"?
It does not, both on Edge or Firefox, just tested.

Also, please let me know how I can overrider the browser setting, I do not wish for Edge to be opened for this, the alternative for me will be to uninstall it.

**Comment by rayluo** [comment]
> > @PauloGDPeixoto , quick question. When you use Edge to sign in, does your sign-in experience include a prompt of "Stay signed-in"?
>
> It does not, both on Edge or Firefox, just tested.

That is strange.  (FWIW, months ago I also observed no "Stay signed-in" when I was using an Edge Beta.) This time, I tested it on my Debian VM just now, with Firefox 91.5.0esr and Edge Stable 97.0.1072.69. I can see that "Stay signed-in" prompt.

When/if it shows, it would be the easier way to let Edge keep your signed-in session alive across browser closure and restart. That way, you subsequent sign-in would just be as convenient as if you are reusing your signed-in session in your default browser.

> 
> Also, please let me know how I can overrider the browser setting, I do not wish for Edge to be opened for this, the alternative for me will be to uninstall it.

Well, if you insist to, you can set env var `BROWSER=/path/to/your/favorite/browser` and then Azure CLI ('s auth component MSAL Python) will honor that.

**Comment by PauloGDPeixoto** [comment]
> That is strange. (FWIW, months ago I also observed no "Stay signed-in" when I was using an Edge Beta.) This time, I tested it on my Debian VM just now, with Firefox 91.5.0esr and Edge Stable 97.0.1072.69. I can see that "Stay signed-in" prompt.
There is something I did not mention: I'm logging in to a corporate domain, after inserting my email I am redirected to the corporate login of my employer. 

> Well, if you insist to, you can set env var `BROWSER=/path/to/your/favorite/browser` and then Azure CLI ('s auth component MSAL Python) will honor that.
Thank you very much for this!

**Comment by PauloGDPeixoto** [comment]
Just to confirm that the env var worked brilliantly, thank you very much! I'm closing this issue now.

**Comment by thomas-seifried-hoylu** [comment]
Uninstalling Edge on Ubuntu solved the problem for me.

**Comment by PauloGDPeixoto** [comment]
> Uninstalling Edge on Ubuntu solved the problem for me.

It was already mentioned that setting the BROWSER env var solves the issue, without the need to uninstall anyting.

**Comment by lostcitizen** [comment]
> > Uninstalling Edge on Ubuntu solved the problem for me.
> 
> It was already mentioned that setting the BROWSER env var solves the issue, without the need to uninstall anyting.

not in ubuntu. I had to uninstall edge too.

**Comment by bebosudo** [comment]
Adding the following to `~/.bashrc` works in ubuntu 24.04:
```bash
alias az='BROWSER="$(which firefox)" az'
```

**Comment by icc-garciaju** [comment]
So, the options are to use a non-namespaced, extremely generic variable to override a setting despite having a configuration file or to uninstall edge.

I only use edge to log into a CloudPC provided by my employer because Win365 doesn't work well in Brave.

Thank you for the env var tip anyway.

**Comment by rayluo** [comment]
> So, the options are to use a non-namespaced, extremely generic variable to override a setting despite having a configuration file or to uninstall edge.
> 
> I only use edge to log into a CloudPC provided by my employer because Win365 doesn't work well in Brave.
> 
> Thank you for the env var tip anyway.

That generic env var `BROWSER` was not our choice. It was a choice long been made [inside Python itself](https://docs.python.org/3/library/webbrowser.html).
