### ISSUE TITLE
SKU options

### ISSUE THREAD

**Issue by petrkoutnycz** [Azure/azure-cli#21144]
As I'm new to Azure world, I'd really appreciate having a link to all possible SKU options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15cb3fd0-5d13-ab34-223b-f7972aae16a2
* Version Independent ID: 65cc59ca-c366-dbe0-b95d-7dcfa3a4438d
* Content: [az functionapp plan](https://docs.microsoft.com/en-us/cli/azure/functionapp/plan?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/functionapp/plan.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/functionapp/plan.yml)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to service team

**Comment by StrawnSC** [comment]
Hi @petrkoutnycz, you can see App Service Plan SKUs for function apps under the parameter help text for `--sku`. You can open the help text with `az functionapp plan create --help`. The `--help` (and it's equivalent `-h`) parameters can be used to view the help text on any command / command group

**Comment by petrkoutnycz** [comment]
I was not aware of this command, thank you. 
Though I dont think it is much of a help. I've attached value I see in the output. It does not tell me possible values for SKU that I can use. Even though there are couple of examples down below, it does not list all possible options for SKU.
![image](https://user-images.githubusercontent.com/9723402/158758198-120ac2e9-9f96-424d-9da6-acc8f3d31afd.png)

**Comment by StrawnSC** [comment]
It looks like your version of the CLI may be behind (or you may have installed an unofficial version). I get the following when I run `az functionapp plan create --help`: 

<img width="764" alt="Screen Shot 2022-03-18 at 3 40 37 PM" src="https://user-images.githubusercontent.com/10121214/159093569-ac7818b2-ff79-4f44-99e1-d7ae2c7a6737.png">

As you can see, the help text should contain the sku options. You should try upgrading your CLI with `az upgrade`. When you run `az --version`, it should show the version number as `2.34.1` (the latest version)

**Comment by petrkoutnycz** [comment]
You are right, thanks a lot.
