### ISSUE TITLE
The command failed with an unexpected error. Read-only file system

### ISSUE THREAD

**Issue by u30758** [Azure/azure-cli#21153]
az commnds are not working power shell or bash command prompts;

Getting following error: The command failed with an unexpected error. Here is the traceback:
[Errno 30] Read-only file system: '/home/neel/.azure/versionCheck.json'

I was trying to use microsoft training pass subscription. Has my access been revoked?

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This is the same issue as https://github.com/Azure/azure-cli/issues/13855.
