### ISSUE TITLE
CLI cmdlets for application gateway L4 properties

### ISSUE THREAD

**Issue by gk-ms** [Azure/azure-cli#21165]
**Resource Provider**
Network resource provider (NRP)

**Description of Feature or Work Requested**
The new cmdlets would enable customers to manage new application gateway sub-resources namely - listeners, routing rules and backend settings for handling TCP/TLS requests. Currently application gateway supports just HTTP and HTTPs requests and the new feature aims to widen the scope for handling even L4 traffic.

**Minimum API Version Required**
2021-08-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/17561/files

**Target Date**
15th Feb

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Bump up network sdk required

**Comment by kairu-ms** [comment]
Hi @gk-ms, we cannot support this feature unless python SDK with api version 2021-08-01 is public released.
