### ISSUE TITLE
az network private-endpoint-connection list fails for Private Link Service resources

### ISSUE THREAD

**Issue by johndowns** [Azure/azure-cli#21160]
## Describe the bug

**Command Name**
`az network private-endpoint-connection list`

**Errors:**
```
Resource type must be one of Microsoft.Batch/batchAccounts, Microsoft.Automation/automationAccounts, Microsoft.Authorization/resourceManagementPrivateLinks, Microsoft.AppConfiguration/configurationStores, Microsoft.BotService/botServices, Microsoft.Cache/Redis, Microsoft.CognitiveServices/accounts, Microsoft.Compute/diskAccesses, Microsoft.ContainerRegistry/registries, Microsoft.DBforMySQL/servers, Microsoft.DBforMariaDB/servers, Microsoft.DBforPostgreSQL/servers, Microsoft.Devices/IotHubs, Microsoft.DocumentDB/databaseAccounts, Microsoft.DigitalTwins/digitalTwinsInstances, Microsoft.EventGrid/topics, Microsoft.EventGrid/domains, Microsoft.EventHub/namespaces, Microsoft.HDInsight/clusters, Microsoft.HealthcareApis/services, microsoft.insights/privateLinkScopes, Microsoft.KeyVault/managedHSMs, Microsoft.Keyvault/vaults, Microsoft.MachineLearningServices/workspaces, Microsoft.Media/mediaservices, Microsoft.Network/applicationGateways, Microsoft.Purview/accounts, Microsoft.PowerBI/privateLinkServicesForPowerBI, Microsoft.Search/searchServices, Microsoft.ServiceBus/namespaces, Microsoft.SignalRService/signalr, Microsoft.Sql/servers, Microsoft.Storage/storageAccounts, Microsoft.StorageSync/storageSyncServices, Microsoft.Synapse/workspaces, Microsoft.Web/sites, Microsoft.Web/hostingEnvironments, Microsoft.SignalRService/WebPubSub
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Deploy a Private Link Service resource and create a private endpoint that needs approval. An easy way to do this is to deploy this sample:
   ```
   az group deployment create -g MyResourceGroup --template-uri https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/quickstarts/microsoft.network/front-door-premium-vm-private-link/azuredeploy.json
   ``` 
- Get the resource ID of the Private Link Service resource.
- `az network private-endpoint-connection list --id resource-id-of-private-link-service`

## Expected Behavior

This should return a list of private endpoint connections that are associated with the Private Link Service resource.

Note that this behaves correctly for resources like Azure Storage accounts, App Service apps, etc.

Also, note that the same problem here happens when approving connections by using the `az network private-endpoint-connection approve` command.

## Environment Summary
```
macOS-12.1-arm64-arm-64bit, Darwin 21.2.0
Python 3.10.1
Installer: HOMEBREW

azure-cli 2.32.0

Extensions:
azure-devops 0.22.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
network

**Comment by YuanyuanNi** [comment]
Hi, 
     The id you choose must be the id of the private endpoint connection, not the Private Link Service resource, please try again.
Best wishes.

**Comment by johndowns** [comment]
@YuanyuanNi I don't think that's accurate. If I deploy a storage account with a private endpoint, then I can run

```
az network private-endpoint-connection list --id storage-account-resource-id
```

And it successfully returns a list of private endpoint connections for that storage account.

My feedback here is that it should behave the same way when I run the command and provide a Private Link Service resource ID.

(Note that your comment would be correct for other commands, such as `az network private-endpoint-connection approve`, but not for `list`.)

**Comment by yonzhan** [comment]
Add @necusjz for awareness

**Comment by ZengTaoxu** [comment]
Hello, I am trying to reproduce this problem, but there is no error any more. Microsoft.Network/privateLinkServices resource has been added to the code. Please upgrade the CLI version and try again, thank you!

**Comment by johndowns** [comment]
@ZengTaoxu yes this has been fixed in a recent version of the CLI. Thanks.

**Comment by simonesavi** [comment]
Hi @ZengTaoxu,
I'm facing the same problem with Az CLI version 2.41.0

``
 id=`az network private-endpoint-connection list -g $adx_resource_group \
            --name $storageName --type "Microsoft.Storage/storageAccounts" \
           --query "[].properties.privateEndpoint.id" -o tsv`
``

`
  az network private-endpoint-connection approve --id $id --description "Approved"
`

I'm receiving below error: `'child_name_1'`

**Comment by ZengTaoxu** [comment]
Hi simonesavi, You have an incorrect id in the 'az network private-endpoint-connection approve' command. Try --query "[].id" instead of --query "[].properties.privateEndpoint.id".

**Comment by simonesavi** [comment]
Hi @ZengTaoxu,
I have tried to change the code following your suggestion, but I have received another error:

``
id=`az network private-endpoint-connection list -g $adx_resource_group \ --name $storageName --type "Microsoft.Storage/storageAccounts" \ --query "[].id" -o tsv`
``

`
az network private-endpoint-connection approve --id $id --description "Approved"
`

The error:

`Bad Request({"error":{"code":"InvalidValuesForRequestParameters","message":"Values for request parameters are invalid: privateLinkServiceConnectionState.status."}})`

**Comment by ZengTaoxu** [comment]
Hi @simonesavi, I have no way to repeat your question, please provide specific command steps. Or you can try the following command steps:
az network vnet create -g {rg} -n {vnet_name} --subnet-name {subnet_name}
az network vnet subnet update -g {rg} --vnet-name {vnet_name} --name {subnet_name} --disable-private-endpoint-network-policies true
storage_id = az storage account create --name {account_name} --resource-group {rg}  --query "[].id" -o tsv
group_id = az network private-link-resource list --id {storage_id} --query "[].properties.groupId" -o tsv
az network private-endpoint create -g {rg} -n {endpoint_name} --vnet-name {vnet_name} --subnet {subnet_name} --private-connection-resource-id {storage_id} --connection-name {endpoint_connection_name} --group-id {group_id} --manual-request
private-endpoint-connection-id = az network private-endpoint-connection list --id {storage_id} --query "[].id" -o tsv
az network private-endpoint-connection approve --id {private-endpoint-connection-id} --description "Approved"

**Comment by OrestesK** [comment]
> Hi @ZengTaoxu, I have tried to change the code following your suggestion, but I have received another error:
> 
> `` id=`az network private-endpoint-connection list -g $adx_resource_group \ --name $storageName --type "Microsoft.Storage/storageAccounts" \ --query "[].id" -o tsv` ``
> 
> `az network private-endpoint-connection approve --id $id --description "Approved"`
> 
> The error:
> 
> `Bad Request({"error":{"code":"InvalidValuesForRequestParameters","message":"Values for request parameters are invalid: privateLinkServiceConnectionState.status."}})`

This is because the status is invalid, meaning it is already approved or not in a status that can be approved.

**Comment by krupakar1329** [comment]
@OrestesK  is the azure rest endpoint PUT https://learn.microsoft.com/en-us/rest/api/storagerp/private-endpoint-connections/put?view=rest-storagerp-2023-05-01&tabs=HTTP
idempotent?

Though its in Approved state. on re-running the same command , error shouldn't arise
