### ISSUE TITLE
When using commands in bash getting this issue

### ISSUE THREAD

**Issue by ArunKumarVj27** [Azure/azure-cli#21163]
## Describe the bug

**Command Name**
`az acr create`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-5.4.0-1067-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.32.0

Extensions:
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by SubhashVasarapu-MSFT** [comment]
@ArunKumarVj27, Looks like error box is greyed out. Could you please post the error details for futher investigation?

**Comment by SubhashVasarapu-MSFT** [comment]
@ArunKumarVj27, I was wondering if you have had a chance to look over our previous reply yet? Let us know if you have any query or input for us or if we are good to close this issue.
