### ISSUE TITLE
how to solve 

### ISSUE THREAD

**Issue by amitsingharoy** [Azure/azure-cli#21179]
## Describe the bug

**Command Name**
`az appservice plan create`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan create --name {} --sku {} --location {} --resource-group {}`

## Environment Summary
```
Linux-5.4.0-1067-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.32.0

Extensions:
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by navba-MSFT** [comment]
@amitsingharoy Thanks for reporting the issue. The error details is blank. Looking at the issue details, I am assuming you are creating an app service plan. Please execute the below commands in order:

>az account set --subscription "1234---1234" # set the right subscription id 
az group create -l azRegion -n MyResourceGroup # create the resource group
az appservice plan create -g MyResourceGroup -n MyPlan # create a basic web app Plan


Refer the examples [here](https://docs.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest#az-appservice-plan-create-examples).

Hope this helps. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@amitsingharoy This is a quick follow-up to check if you had a chance to follow the action plan in my above comment. Please let me know if you are still facing the issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@amitsingharoy Please follow the above mentioned action plan once you get a chance. We will now proceed with the closure of this issue. If you need any further assistance, please feel free to reopen this github thread. We would be happy to help.
