### ISSUE TITLE
b

### ISSUE THREAD

**Issue by Akshay-gade** [Azure/azure-cli#21175]
## Describe the bug

**Command Name**
`az webapp create`

**Errors:**
```
Unable to retrieve details of the existing app 'myapp12'. Please check that the app is a part of the current subscription

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create --plan {} --resource-group {} --name {}`

## Environment Summary
```
Linux-5.4.0-1067-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.32.0

Extensions:
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by navba-MSFT** [comment]
@Akshay-gade Thanks for reporting the issue. Looking at the problem description, I assume you are creating an azure web app from Azure CLI. Please execute the below commands in order:

>az account set --subscription "1234-****-****-1234"  # set the right subscription id where you would like to create webapp
az group create -l azRegion -n MyResourceGroup  # create the resource group
az appservice plan create -g MyResourceGroup -n MyPlan # create a basic web app Plan
az webapp create -g MyResourceGroup -p MyPlan -n MyUniqueAppName # create web app 

Refer the examples [here](https://docs.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest#az-appservice-plan-create-examples).

Hope this helps. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Akshay-gade Are you still facing the issue? This is a quick follow-up to check if you had a chance to look at my above comment.  Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Akshay-gade We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
