### ISSUE TITLE
az apim api import wrong parameters

### ISSUE THREAD

**Issue by andrkole** [Azure/azure-cli#21187]
## Describe the bug

**Command Name**
`az apim api import`

**Errors:**
_subscription-key-header-name_ and _subscription-key-query-param-name_ parameter values are reversed.

Value I put as the _subscription-key-header-name_ is applied as "Query parameter name" and _subscription-key-query-param-name_ is applied as "Header name" once the API is imported.

## To Reproduce:
Run the Azure CLI command:
- `az apim api import -g {} -n {} --specification-url {} --specification-format {} --api-id {} --subscription-key-header-name {someHeaderName} --subscription-key-query-param-name {someQueryParamName} --path {} --subscription {}`

## Expected Behavior
_subscription-key-header-name_ corresponds to Header name and _subscription-key-query-param-name_ to Query parameter name.

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.32.0

Extensions:
alias 0.5.2
application-insights 0.1.14
interactive 0.4.5
support 1.0.3

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```
## Additional Context
**Sent:**
--subscription-key-header-name Ocp-Apim-Subscription-Key
--subscription-key-query-param-name subscription-key

**Result:**
<img width="499" alt="image" src="https://user-images.githubusercontent.com/44214882/152346473-1925c05c-f3b0-479a-9cac-fac331f2c9aa.png">

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by PramodValavala-MSFT** [comment]
@andrkole Thanks for the feedback! Looks like they are flipped in [this line](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/apim/custom.py#L366). We are working up a PR to fix this.
