### ISSUE TITLE
Trusted Launch Az CLI VMSS Support

### ISSUE THREAD

**Issue by sirfamelin** [Azure/azure-cli#21180]
**Resource Provider**

Microsoft.compute\virtualMachineScaleSets

**Description of Feature or Work Requested**

Add Trusted Launch properties to the “az vmss create” and “az vmss update” Azure CLI Commands

(1) Create a VMSS with Trusted Launch.
az vmss create
--resource-group myRG
--name myVMSS
[--security-type {TrustedLaunch}]
[--enable-secure-boot {false, true}]
[--enable-vtpm {false, true}]

--security-type: specify if the VM is Trusted Launch enabled. Accepted value (enum): TrustedLaunch
--enable-secure-boot: toggle secure boot. Accepted values: false, true.
--enable-vtpm: toggle vTPM. Accepted values: false, true.

(2) Enable/disable secure boot and vTPM settings on existing Trusted Launch enabled VMSS:
az vmss update
--resource-group myRG
--name myVMSS
[--enable-secure-boot {false, true}]
[--enable-vtpm {false, true}]

--enable-secure-boot: toggle secure boot. Accepted values: false, true.
--enable-vtpm: toggle vTPM. Accepted values: false, true.

**Minimum API Version Required**

2020-12-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json

**Target Date**

ASAP - please include this change in the next Az Cli API milestone / version

**Related Request (already closed)**
https://github.com/Azure/azure-cli/issues/16692

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@sirfamelin For VMSS, are the positions and property names of these parameters in the request body similar to those in VM #17354?
It would be better if you could give us the examples of the request body~

**Comment by sirfamelin** [comment]
@zhoxing-ms, what you say request body, do you mean what the az cli command should look like? If so, I have two examples under the description for az vmss create and az vmss update

**Comment by zhoxing-ms** [comment]
@sirfamelin In fact, I mean the request body of the HTTP request when requesting REST API
Such as: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/examples/CreateAScaleSetWithUefiSettings.json

**Comment by sirfamelin** [comment]
@zhoxing-ms, I see - looks like you found the VMSS example with SecurityProfile and UefiSettings from the 2020-12-01 version. Is that what you needed?

**Comment by zhoxing-ms** [comment]
@sirfamelin Yes, exactly

**Comment by PARADISSEEKR** [comment]
Hi, @sirfamelin When I use the image in the [example](https://github.com/Azure/azure-rest-api-specs/blob/1659cfde425308fc46b5f2cd962c3be40ba04ace/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/examples/CreateAScaleSetWithUefiSettings.json#L17-L21) to test the new parameters, the service return `The value of parameter version is invalid`.. When I use the common image to test, the service returns `Use of TrustedLaunch setting is not supported for the provided image`.How can I test it?

**Comment by PARADISSEEKR** [comment]
Hi @sirfamelin ,When I test the new parameters, the service returns `Use of TrustedLaunch setting is not supported for the provided image`. What conditions should the image used meet? Can you provide an image for testing? Thank you.

**Comment by sirfamelin** [comment]
@PARADISSEEKR, please ensure you are using the gen2 version of the images. Examples:
publisher: CANONICAL, SUSE
offer: UBUNTUSERVER, SLES-15-SP2
Sku: 18_04-gen2, 18_04-LTS-GEN2, 20_04-LTS-GEN2, GEN2

Is Windows going to be tested as well?
