### ISSUE TITLE
Authoring Commands Readme improvements

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-cli#2118]
As a first time command author and neophyte Python user, below are the bumps I hit along the way when following the readme:
* lack of explanation and examples around the azure.cli.core.commands.parameters (tags_type, location_type, enum_choice_list, etc.)
* how completion lists work and when to use them (such as resource_name_completion_list)
* how completers work in general and when to use them, although I think this is a more general python gap for me, it would be nice to understand why and when we would use argcomplete.completers to enable certain customer scenarios (for example, FilesCompleter, what does it mean to include this in a command?)

**Comment by tjprescott** [comment]
Thanks!

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
