### ISSUE TITLE
az network nic ip-config address-pool add . What is the right sintaxis to use when the load balancer does not belong to the same resource group of the NIC that you are trying to add to the backend pool

### ISSUE THREAD

**Issue by GonzaloMurillo** [Azure/azure-cli#21183]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When using the command "az network nic ip-config address pool add" to add a NIC to the backend of an existing SLB, it works if the NIC belongs to the same resource group as the SLB, but if the NIC that you are trying to add belongs to a Resource Group different from the Resource Group of the SLB, it fails

**To Reproduce**

Having an SLB called GONZALO-LB, with a backend POOL called UNDER_LB and a NIC linux-5295 all belonging to the resource group GONZALO-LB-RG, the following command works as expected.

az network nic ip-config address-pool add --address-pool UNDER_LB --ip-config-name IPConfigLinux5 --nic-name linux-5295 --resource-group --lb-name GONZALO-LB

However, if we try to add an interface linux-4855 that belongs to a VM in a  different Resource Group called: "LINUX-4_group", we need to use absolute references like "/subscriptions/id_subscription/resourceGroups/LINUX-4_group/providers/Microsoft.Network/networkInterfaces/linux-4855/ipConfigurations/IPConfigLinux4" to identify where the resources are located, and if we proceed this way, it fails.

Example:

az network nic ip-config address-pool add --address-pool UNDER_LB --ip-config-name /subscriptions/id_subscription/resourceGroups/LINUX-4_group/providers/Microsoft.Network/networkInterfaces/linux-4855/ipConfigurations/IPConfigLinux4 --nic-name /subscriptions/id_subscription/resourceGroups/LINUX-4_group/providers/Microsoft.Network/networkInterfaces/linux-4855 --resource-group /subscriptions/id_subscription/resourceGroups/GONZALO-LB-RG --lb-name /subscriptions/id_subscription/resourceGroups/GONZALO-LB-RG/providers/Microsoft.Network/loadBalancers/GONZALO-LB

The error that we are receiving is: 

(InvalidApiVersionParameter) The api-version '2021-05-01' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
Code: InvalidApiVersionParameter
Message: The api-version '2021-05-01' is invalid. The supported versions are '2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

This is because LINUX4 belongs to a resource group “LINUX-4_group” different from the resource group of the Load Balancer “Gonzalo-LB”, and I am using “absolute references”

From azure.portal.com, I can easily add a LINUX 4 belonging to Resource Group LINUX-4_group to the backend UNDER_LB belonging to the SLB Gonzalo-LB belonging to the resource group GONZALO-LB-RG

**Expected behavior**

AZ CLI must allow the same functionality as the portal. If the portal allows to add an interface to a load balancer, when then interface and the load balancer do not belong to the same Resource Group, then the AZ CLI should allow it.

What is the right syntax to refer to a resource that is not in the same resource group as the load balancer?

**Comment by yonzhan** [comment]
network

**Comment by ZengTaoxu** [comment]
Hello, your CLI command is incorrect.Please try it 'az network nic ip-config address-pool add -g LINUX-4_group --nic-name linux-4855 --ip-config-name IPConfigLinux4 --address-pool /subscriptions/id_subscription/resourceGroups/GONZALO-LB-RG/providers/Microsoft.Network/loadBalancers/GONZALO-LB/backendAddressPools/UNDER_LB'
You do not need to write this parameter --lb-name
