### ISSUE TITLE
WebApp:set dotnet core version using azure cli in azure windows webapp

### ISSUE THREAD

**Issue by sri2850** [Azure/azure-cli#21192]
We have windows webapp in Azure, we want to change the stack to dotnet core version(3.1,2.1) using Azure cli. If it is a linux webapp, we can use az webapp config set -g $group -n $webappName --linux-fx-version "DOTNETCORE|2.1". But for windows couldn't find anything. Help is appreciated. Thank you![Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e50d77a-f2fa-6d6e-0c57-2f434c12766f
* Version Independent ID: f9a98805-6e16-487a-03ce-237cb964f83c
* Content: [az webapp config](https://docs.microsoft.com/en-us/cli/azure/webapp/config?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/config.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by navba-MSFT** [comment]
@sri2850 Apologies for the late reply. You can try to use the parameter --windows-fx-version:

>--windows-fx-version
A docker image name used for your windows container web app

I tried to execute the below command in my environment. Could you please test the same and let us know if that helps ?

>az webapp config set -g 'MyWebAppName' -n 'RGName' --windows-fx-version '"DOTNETCORE|2.1"' # set .NET core version 
az webapp config show -g 'MyWebAppName' -n 'RGName' # To list the web app configuration

Refer [this](https://docs.microsoft.com/en-us/cli/azure/webapp/config?view=azure-cli-latest#az-webapp-config-set) docs for more information. Hope this helps.

**Comment by sri2850** [comment]
@navba-MSFT, it's windows based webapp but not using docker containers. Actually, it should change in webapp> configuration> General Settings> Tech stack. It's not changing there. 
![image](https://user-images.githubusercontent.com/32320907/152733976-7b392fe3-e8c0-411d-bb0b-5f9e0af38fea.png)

**Comment by navba-MSFT** [comment]
@sri2850 Thanks for getting back. Could you please confirm if you are changing the .NET framework version or the DOTNET core version ? Because the available version for DOTNETCORE is 3.1 | 2.1. This is what I see now in my Configuration settings after running my above command.

![image](https://user-images.githubusercontent.com/57353862/152735127-ede22832-4d7c-4bcf-9402-307b01b07ce8.png)

Awaiting your reply.

**Comment by sri2850** [comment]
Hello @navba-MSFT, any update on the cli command. Awaiting for your reply.

**Comment by navba-MSFT** [comment]
@sri2850 Apologies for the late reply. Thanks for clarifying your requirement. AFAIK unlike LinuxFxVersion, for Linux, there is nothing CLI command can expose this setting at this time for the dotnetcore in windows webapp. 

I did come across [this](https://docs.microsoft.com/en-us/azure/app-service/configure-language-dotnetcore?pivots=platform-windows#set-net-core-version) article which you can refer for now:

>Set the target framework in the project file for your ASP.NET Core project. For more information, see [Select the .NET Core version to use](https://docs.microsoft.com/en-us/dotnet/core/versions/selection) in .NET Core documentation.

In the meantime, Could you try the below and check if that helps ?

```
Set-AzWebApp -ResourceGroupName 'MyRG' -Name 'MyWebApp' -AppServicePlan ' MyWebAppPlan'
$PropertiesObject = @{
"CURRENT_STACK" = "dotnetcore"
}

New-AzResource -PropertyObject $PropertiesObject -ResourceGroupName 'MyRG' -ResourceType Microsoft.Web/sites/config/metadata -ResourceName 'MyWebApp' -ApiVersion 2021-03-01 -Force


```
I am doing some more research on this. I will reply on this thread once I have an update.

**Comment by sri2850** [comment]
@navba-MSFT, thanks for powershell script. It is working as expected. But having this in Azure-cli will really help. Can I close this issue?

**Comment by navba-MSFT** [comment]
@sri2850 Thanks for getting back. I also found that changing the .Net version doesn’t reflect on any of the site config or properties as investigated using resource explorer. [https://resources.azure.com/]. So there is no Az CLI available at this time to perform the set dotnetcore version operation on windows webapp(non-containerized app). 

So you can leverage the PS sample which was shared earlier and you can also specify the version of .NETCore within your project settings as per [this](https://docs.microsoft.com/en-us/dotnet/core/versions/selection#target-framework-monikers-define-build-time-apis) and [this](https://docs.microsoft.com/en-us/azure/app-service/configure-language-dotnetcore?pivots=platform-windows#set-net-core-version) documentation for now. Hope this helps. 

We will now proceed with the closure of this thread. If you need any further assistance in future, please feel free to reach out to us.

**Comment by DimitarGrozev** [comment]
How can I set the specific .net version using this snippet:
```

Set-AzWebApp -ResourceGroupName 'MyRG' -Name 'MyWebApp' -AppServicePlan ' MyWebAppPlan'
$PropertiesObject = @{
"CURRENT_STACK" = "dotnetcore"
}

New-AzResource -PropertyObject $PropertiesObject -ResourceGroupName 'MyRG' -ResourceType Microsoft.Web/sites/config/metadata -ResourceName 'MyWebApp' -ApiVersion 2021-03-01 -Force
```
