### ISSUE TITLE
WebApp:az webapp --help

### ISSUE THREAD

**Issue by notywala433** [Azure/azure-cli#21193]
## Describe the bug

**Command Name**
`az webapp`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp --help`

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by PramodValavala-MSFT** [comment]
@notywala433 Looks like you are using a pretty old version of `az`. Could you try upgrading to a newer version and try again?

**Comment by panchagnula** [comment]
@notywala433 please upgrade your CLI version & re-try. The error indicates something missing on the cli install package.
