### ISSUE TITLE
az bicep decompile : type object 'datetime.datetime' has no attribute 'fromisoformat'

### ISSUE THREAD

**Issue by MartinPriebe** [Azure/azure-cli#21194]
The ARM template contains only...
Microsoft.Insights/metricAlerts

## Describe the bug

**Command Name**
`az bicep decompile`

**Errors:**
```
type object 'datetime.datetime' has no attribute 'fromisoformat'
Traceback (most recent call last):
cli\Lib\site-packages\knack\cli.py, ln 231, in invoke
azure\cli\core\commands\__init__.py, ln 657, in execute
azure\cli\core\commands\__init__.py, ln 720, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 691, in _run_job
azure\cli\core\commands\__init__.py, ln 328, in __call__
site-packages\azure\cli\core\__init__.py, ln 807, in default_command_handler
azure\cli\command_modules\resource\custom.py, ln 3298, in decompile_bicep_file
azure\cli\command_modules\resource\_bicep.py, ln 63, in run_bicep_command
azure\cli\command_modules\resource\_bicep.py, ln 152, in _load_bicep_version_check_result_from_cache
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bicep decompile --file {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.22.0 *

Extensions:
application-insights 0.1.14
azure-devops 0.18.0
azure-iot 0.10.10
kusto 0.4.0

```
## Additional Context

Any tipps what to check?

**Comment by MartinPriebe** [comment]
command called on a file which was successfully decompiled before also shows this error now.

**Comment by MartinPriebe** [comment]
new command window (using cmder.net) - it´s working. 
but just in case

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by MartinPriebe** [comment]
seems like update azure cli to v2.32.0 fixed it. hopefully :)

**Comment by navba-MSFT** [comment]
@MartinPriebe Apologies for the late reply. Thanks for sharing an update on this. Please let us know if any further assistance is required on this issue. Awaiting your reply.

**Comment by MartinPriebe** [comment]
Hi, no I don´t need any assistance right now. Thanks a lot.
I have another issue with error message "lineStarts must not be empty"
But I think this is already fixed for the next version upgrade.
