### ISSUE TITLE
Update a virtual network to delete DNS server not work ??

### ISSUE THREAD

**Issue by PvlD** [Azure/azure-cli#21199]
Behaviour not the according documentation .

![image](https://user-images.githubusercontent.com/10778065/152567670-f75e083d-1a0f-4eca-9425-b7314a2434b2.png)

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
For powershell please use ` --dns-servers '""'`

**Comment by PvlD** [comment]
still not work.  please check in real environment .


![image](https://user-images.githubusercontent.com/10778065/152807093-3612ca22-bd30-4878-96c5-b32c00ebcafc.png)
