### ISSUE TITLE
az resource invoke-action

### ISSUE THREAD

**Issue by masonhuemmer** [Azure/azure-cli#21190]
Add support for --no-wait argument.

You don't have to wait for the long-running operation to finish.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76a8ad2-efd8-9e8a-9b2b-eebeb1e9d1d4
* Version Independent ID: 280b7ea9-eb6c-9601-464b-09bf8e0cff5d
* Content: [az resource](https://docs.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/resource.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/resource.yml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ARM

**Comment by blueboxes** [comment]
To add an example where this is useful, the Azure Image Builder run command can run for up to 4 hours by default and typically runs at least for 30 mins.
