### ISSUE TITLE
az storage share delete --delete-snapshots include-leased not allowed

### ISSUE THREAD

**Issue by pixeye33** [Azure/azure-cli#21196]
**Describe the bug**
When using `az storage share delete --name xxx --account-name xxx --account-key xxx --delete-snapshots include-leased`
we get
```
ERROR: az storage share delete: 'include-leased' is not a valid value for '--delete-snapshots'. Allowed values: include.
```

for blob `x-ms-delete-snapshots` can be `{include, only}` [as seen in Docs](https://docs.microsoft.com/en-us/rest/api/storageservices/Delete-Blob#request-headers)
blob commands allows it
`az storage blob delete [--delete-snapshots {include, only}]`

for share `x-ms-delete-snapshots` can be `{include, include-leased}` [as seen in Docs](https://docs.microsoft.com/en-us/rest/api/storageservices/delete-share#request-headers)
but share commands do not allow include-leased
`az storage share delete [--delete-snapshots {include}]
`

**Expected behavior**
being able to use the "include-leased" value.
`az storage share delete [--delete-snapshots {include, include-leased}]`

**Environment summary**
we use the Docker container with version 2.32.0

**Additional context**
this was attempted because when using `az storage share delete --name xxx --account-name xxx  --account-key xxx --delete-snapshots include`
we got
```
Unable to delete share because one or more share snapshots have active leases. Release the share snapshot leases or delete the share with the include-leased parameter for x-ms-delete-snapshots. ErrorCode: DeleteShareWhenSnapshotLeased
<?xml version="1.0" encoding="utf-8"?><Error><Code>DeleteShareWhenSnapshotLeased</Code><Message>Unable to delete share because one or more share snapshots have active leases. Release the share snapshot leases or delete the share with the include-leased parameter for x-ms-delete-snapshots.
RequestId:b5e6aa40-d01a-0027-625a-1709a1000000
Time:2022-02-01T10:57:06.2359390Z</Message></Error>
```

**Comment by yonzhan** [comment]
storage

**Comment by MeCRO-DEV** [comment]
Any updates for this bug? I'm having the same error these days.

**Comment by MeCRO-DEV** [comment]
I think the rest api has the bug a well.
```
uri="https://management.azure.com/subscriptions/$sid/resourceGroups/$rg_name/providers/Microsoft.Storage/storageAccounts/$sa_name/fileServices/default/shares/${sName}?api-version=2023-01-01&$include=leased-snapshots"
az rest --method delete --uri "$uri" --verbose
```
error:

> Unable to delete share because one or more share snapshots have active leases. Release the share snapshot leases or delete the share with the include-leased parameter for x-ms-delete-snapshots.

**Comment by MeCRO-DEV** [comment]
https://learn.microsoft.com/en-us/rest/api/storagerp/file-shares/delete?tabs=HTTP

**Comment by calvinhzy** [comment]
Hi @pixeye33, opened an [issue](https://github.com/Azure/azure-sdk-for-python/issues/33659) for the Python SDK, once that is fixed, can support this on the CLI side as well. Thanks.
