### ISSUE TITLE
az apim api --protocols support both HTTP and HTTPS as input

### ISSUE THREAD

**Issue by cyljacky** [Azure/azure-cli#21208]
**Is your feature request related to a problem? Please describe.**

I am writing pipeline that imports the generated swagger.json into Azure APIM service. Although Azure APIM supports HTTP, HTTPS and **both of them** as URL scheme, the Azure CLI APIM module only accepts HTTP **or** HTTPS for the corresponding option (--protocol). I need to access APIM web interface to change the URL scheme to **both** manually every time when the pipeline is run, which is really annoying.

**Describe the solution you'd like**

`az apim api import --protocols` support extra value that changes the URL schema in web interface to **both** option

**Describe alternatives you've considered**

According to [document](https://docs.microsoft.com/en-us/cli/azure/apim/api?view=azure-cli-latest#az-apim-api-import), the `--protocols` should support one or more protocols, but I can't find any documentation about how to implement it. Maybe there's a way to set both protocols which is not documented?

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by cyljacky** [comment]
It works! Thanks a lot! It saves me a lot of annoyance!
