### ISSUE TITLE
Python module error in az keyvault subgroups on Linux

### ISSUE THREAD

**Issue by fdouw** [Azure/azure-cli#21205]
## Describe the bug

**Command Name**
`az keyvault key`

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 554, in execute
    parsed_args = self.parser.parse_args(args)
python3/dist-packages/knack/parser.py, ln 259, in parse_args
    return super(CLICommandParser, self).parse_args(args)
usr/lib/python3.8/argparse.py, ln 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
...
<frozen importlib._bootstrap>, ln 961, in _find_and_load_unlocked
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault key -h`

## Expected Behavior
- list options for `az keyvault key`

## Environment Summary
```
Linux-5.13.0-28-generic-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```
## Additional Context
Subgroups `certificate`, `key`, `secret`, and `storage` of `az keyvault` all seem to have similar issues. Other subgroups and commands are unaffected.

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
`azure-cli 2.0.81` is not our official Azure CLI, please follow this document to install official Azure CLI: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

For more details, see #19640

**Comment by fdouw** [comment]
Thanks for the reply. I was using the default package in the Ubuntu repository. Can confirm that the version from the Microsoft repo does not have this issue.
