### ISSUE TITLE
[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.12.0:deploy (default-cli) on project PROJECTNAME

### ISSUE THREAD

**Issue by RiccardoSofi** [Azure/azure-cli#21211]
Encoutering error when deploying to azure: 'Failed to authenticate with Azure. Please check your configuration.'

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by RiccardoSofi** [comment]
How can I route to CXP team?

**Comment by SubhashVasarapu-MSFT** [comment]
@RiccardoSofi, could you please post the complete error info and your pom.xml data here for further analysis?

**Comment by RiccardoSofi** [comment]
This is the complete error:

[ERROR] Failed to execute goal [32mcom.microsoft.azure:azure-webapp-maven-plugin:1.12.0:deploy[m [1m(default-cli)[m on project [36mtmi-fac-simile-api[m: [1;31mEncoutering error when deploying to azure: 'Failed to authenticate with Azure. Please check your configuration.'[m -> [1m[Help 1][m
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal [32mcom.microsoft.azure:azure-webapp-maven-plugin:1.12.0:deploy[m [1m(default-cli)[m on project [36mtmi-fac-simile-api[m: [1;31mEncoutering error when deploying to azure: 'Failed to authenticate with Azure. Please check your configuration.'[m

this is the pom.xml:

![immagine](https://user-images.githubusercontent.com/75128425/152761511-a7a4f4be-51a1-4edc-83d9-ebd80dd82318.png)

**Comment by SubhashVasarapu-MSFT** [comment]
@RiccardoSofi, it states you there is an authentication issue. Can you verify whether you have necessary permissions on your subscription? Also do let us know the authentication type you were using here to access Azure resources.

**Comment by panchagnula** [comment]
@JasonFreeberg FYI - this is not CLI specific issue.

**Comment by RiccardoSofi** [comment]
> @JasonFreeberg FYI - this is not CLI specific issue.

SOLVED: INSTALL azure-cli-2.20.0 ANGULAR CLI 

Angular CLI versions over azure-cli-2.20.0 do not provide any accessToken.json fully filled files.
When trying 'az login' my file was empty and STS was not able to build with succes.

My STS version is:

Spring Tool Suite 4 
Version: 4.10.0.RELEASE
Build Id: 202103111225

and they seems dont work properly togheter.
