### ISSUE TITLE
az postgres server firewall-rule create not taking --name parameter and rule gets over written

### ISSUE THREAD

**Issue by abhiramani-iptiq** [Azure/azure-cli#21212]
Hi
This command is not taking Rule name and creates rule with generic name allowip and next command overwrites first commands's IP because name is same allowip 

az postgres server firewall-rule create --name Rule1 -g my-rg -s my-psql -n allowip --start-ip-address <start ip> --end-ip-address <end ip>
az postgres server firewall-rule create --name Rule2 -g my-rg -s my-psql -n allowip --start-ip-address <start ip> --end-ip-address <end ip>

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca574ee0-11f3-5eb3-4ab6-3fed9e42d6d6
* Version Independent ID: d4febc64-c4a8-742e-63fc-1bcab825d36c
* Content: [az postgres server firewall-rule](https://docs.microsoft.com/en-us/cli/azure/postgres/server/firewall-rule?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/postgres/server/firewall-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/postgres/server/firewall-rule.yml)
* Service: **postgresql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by abhiramani-iptiq** [comment]
Hi
i had both --name and -n parameter specified in same line thats why its was nto working
below command works fine.

az postgres server firewall-rule create --name Rule1 -g my-rg -s my-psql  --start-ip-address --end-ip-address
az postgres server firewall-rule create --name Rule2 -g my-rg -s my-psql  --start-ip-address --end-ip-address
