### ISSUE TITLE
Application Gateway backend pool

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#2121]
azureuser@amitubuntu15:~$ az network application-gateway create --name "AdatumAppGateway" --location "eastus" --resource-group "AdatumAppGatewayRG" --vnet-name "AdatumAppGatewayVNET" --vnet-address-prefix "10.0.0.0/16" --subnet "Appgatewaysubnet" --subnet-address-prefix "10.0.0.0/28" --servers "10.0.0.4 10.0.0.5" --capacity 2  --sku Standard_Small --http-settings-cookie-based-affinity Enabled --http-settings-protocol Http --frontend-port 80 --routing-rule-type Basic --http-settings-port 80

this gives a single backend pool with element as 10.0.0.4 10.0.0.5 instead of two backend pool members. Without enclosing servers as string, it fails.

**Comment by tjprescott** [comment]
You should not enclose the servers in quotes.
