### ISSUE TITLE
Azure Virtual Network Manager CLI Extension Update

### ISSUE THREAD

**Issue by jago2136** [Azure/azure-cli#21215]
**Resource Provider**

Azure Virtual Network Manager

**Description of Feature or Work Requested**

The virtual-network-manager extension to be updated with all of the changes included in the new API version. Details on these changes are included below. 

**Minimum API Version Required**

2021-05-01-preview

**Swagger Link**

Swagger Spec: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/network/resource-manager/Microsoft.Network/preview/2021-05-01-preview
Exact changes included in the new API version: https://github.com/Azure/azure-rest-api-specs/pull/17311/files/c028f637de80943d1cbc6b5cbc4ad1b26dcf394c..0490baeedd2050b3f52fbe99a1ccc8ab5df26a14

**Target Date**

2/21 would be an ideal date for these changes, allowing enough time for us to test/debug before releasing to customers. 

**Additional Resources** 
- Existing CLI extension: https://github.com/Azure/azure-cli-extensions/tree/main/src/network-manager
- Design proposal doc for PowerShell: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1123 I'm attaching the PowerShell proposal doc, because it describes all of the changes we'll be making to our PowerShell cmdlet. I'd imagine there are parallel changes made in CLI, so it should be helpful. It's currently under development, but will be completed by 2/8. Once 'Draft' is removed from the title, it will have been finalized will all planned changes.

**Comment by yonzhan** [comment]
Virtual network manager
