### ISSUE TITLE
Incorrect max-burst limit with az functionapp plan

### ISSUE THREAD

**Issue by vhhughes** [Azure/azure-cli#21225]
## Describe the bug
[Documentation for the EastUS2 region my Windows EP3 Azure Function Premium Plan is running in](https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal#region-max-scale-out) says that I should be able to set the maximum instances up to 100. The Azure Portal allows me to do this successfully. When I try to use the Azure CLI to set any value about 20, however, it fails every time.

**Command Name**
`az functionapp plan update`

**Errors:**
```
Usage error: --max-burst is expected to be between 0 and 20 (inclusive)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az functionapp plan update --name {} --resource-group {} --max-burst {}`

## Expected Behavior
The command should allow values above 20 up to the actual limit for the location.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.29.1 *

Extensions:
application-insights 0.1.14
cosmosdb-preview 0.10.0
front-door 1.0.16

```

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by navba-MSFT** [comment]
@vhhughes Apologies for the late reply. I was able to reproduce the issue at my end. I am doing some research on this and update this thread once I have more details. In the meantime, Could you please test with the PS [Update-AzFunctionAppPlan](https://docs.microsoft.com/en-us/powershell/module/az.functions/update-azfunctionappplan?view=azps-7.2.0#example-1--update-an-app-service-plan-to-ep2-sku-with-twenty-maximum-workers-) cmdlet and check if that helps ? Awaiting your reply.

**Comment by vhhughes** [comment]
@navba-MSFT, I tried the Azure PowerShell command, and it works fine. 

That said, we don't install or use Azure PowerShell, because we found over time that it seemed to be a second-class citizen compared to the Azure CLI. (i.e., support for new resource types, capabilities, etc. came later than for Azure CLI and with fewer supported options)

**Comment by navba-MSFT** [comment]
@vhhughes Thanks for getting back. I am discussing this issue with the product owners and checking on the fix. I will keep you posted about this.

**Comment by navba-MSFT** [comment]
@vhhughes Please expect the changes to be available with the next CLI release (in March). see [this](https://github.com/Azure/azure-cli/milestone/115).

**Comment by Scot-Bernard** [comment]
I'm still having this issue with az cli 2.71.0.
