### ISSUE TITLE
Application Gateway Create fails

### ISSUE THREAD

**Issue by georgewallace** [Azure/azure-cli#2122]
When running the example below I get the following error.  This occurs even with 1 IP address

### Error

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "InvalidJson",
        "message": "Error converting value \"{'ip_address': '10.0.0.4', 'fqdn': None}\" to type 'Microsoft.WindowsAzure.Networking.Nrp.Frontend.Contract.Csm.Public.ApplicationGatewayBackendAddress'. Path 'properties.backendAddressPools[0].properties.BackendAddresses[0]', line 1, position 914."
      },
      {
        "code": "InvalidJson",
        "message": "Error converting value \"{'ip_address': '10.0.0.5', 'fqdn': None}\" to type 'Microsoft.WindowsAzure.Networking.Nrp.Frontend.Contract.Csm.Public.ApplicationGatewayBackendAddress'. Path 'properties.backendAddressPools[0].properties.BackendAddresses[1]', line 1, position 957."
      }
    ]
  }
}  Correlation ID: ea3c90fb-a7ad-4e30-8d8f-c0f4f905d50f

### Example
az network application-gateway create \
--name "AdatumAppGateway" \
--location "eastus" \
--resource-group "AdatumAppGatewayRG" \
--vnet-name "AdatumAppGatewayVNET" \
--vnet-address-prefix "10.0.0.0/16" \
--subnet Appgatewaysubnet \
--subnet-address-prefix "10.0.0.0/28" \
--servers 10.0.0.4 10.0.0.5 \
--cert-file "/mnt/c/Users/gwallace/Desktop/application-gateway/fabrikam.pfx" \
--cert-password "P@ssw0rd" \
--capacity 2 \
--sku-tier Standard \
--sku-name Standard_Small \
--http-settings-cookie-based-affinity Enabled \
--http-settings-protocol Http \
--frontend-port 443 \
--routing-rule-type Basic \
--http-settings-port 80

**Comment by tjprescott** [comment]
If you run `pip list` what version of the `azure-cli-network` package are you using? I have confirmed that this works correctly on the latest master.

**Comment by georgewallace** [comment]
@tjprescott I reinstalled azure-cli and it is working now, apologize for that. Had to rip and replace.
