### ISSUE TITLE
Request to update Powershell and CLI for Microsoft.HardwareSecurityModules.

### ISSUE THREAD

**Issue by sunil-archt** [Azure/azure-cli#21228]
**Resource Provider**
Microsoft.HardwareSecurityModules

**Description of Feature or Work Requested**

https://azure.microsoft.com/en-us/services/payment-hsm/#overview

**Minimum API Version Required**

The new SKU names are supported even in the older API versions.
The new managementNEtworkProfile that is added is only for new API version: 2021-11-30

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/f203c1b73639b7e2f85aa96902cfe36c6dd2ffad/specification/hardwaresecuritymodules/resource-manager/Microsoft.HardwareSecurityModules/stable/2021-11-30/dedicatedhsm.json

**Target Date**

Our GA target date is 06/01/2022

**Comment by yonzhan** [comment]
PLR

**Comment by kairu-ms** [comment]
Done https://github.com/Azure/azure-cli-extensions/pull/4898
