### ISSUE TITLE
Azure CLI - Az functionapp deploy not mentioned as [Preview]

### ISSUE THREAD

**Issue by hrmsft** [Azure/azure-cli#21236]
Please check and add the information that the command "Az functionapp deploy" is in preview.
The information should be provided in order to guide customer on weather choose to use it or not.

Command used to see it: az functionapp --help

Please see the screenshot of the command run on CLI:
![image](https://user-images.githubusercontent.com/83068299/153206179-4cc7a786-f28f-455a-bb23-ea19118293b7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f254bb-7dfd-417b-b08d-f2ac34247d99
* Version Independent ID: 9d22f523-579b-ea66-04ed-20f09c72bcbb
* Content: [az functionapp](https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest#az-functionapp-deploy)
* Content Source: [latest/docs-ref-autogen/functionapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/functionapp.yml)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by SatishBoddu-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
