### ISSUE TITLE
az communication sms send-sms does not work - Python Error

### ISSUE THREAD

**Issue by pwillia6** [Azure/azure-cli#21239]
## Describe the bug

**Command Name**
`az communication sms send-sms`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
The operation 'azext_communication.custom#communication_send_sms' is invalid.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 61, in get_op_handler
    handler = getattr(handler, part)
AttributeError: module 'azext_communication.custom' has no attribute 'communication_send_sms'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 556, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 515, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 313, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/local/Cellar/azure-cli/2.33.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 66, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(op_path))
ValueError: The operation 'azext_communication.custom#communication_send_sms' is invalid.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az communication sms send-sms --sender {} --recipient {} --message {}`

## Environment Summary
```
macOS-12.2-x86_64-i386-64bit, Darwin 21.3.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.33.0

Extensions:
communication 1.1.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by navba-MSFT** [comment]
@pwillia6 Apologies for the late reply. I hope you are aware of the fact that SMS messages can be sent to and received from United States phone numbers as of now. Phone numbers located in other geographies are not yet supported by Communication Services SMS. Refer [this](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/sms/send) article.

While I am trying to repro this issue at my end and checking in the background on possible action plan, Could you please test with [this](https://docs.microsoft.com/en-us/rest/api/communication/sms/send#successfulsend) REST API and check if that serves your requirement ? Awaiting your reply.

**Comment by pwillia6** [comment]
Hi, 

I need to send SMS to Australia so the server is no good.    Are you able to use the command line at all to send an SMS ?   

Cheers,

Paul

**Comment by navba-MSFT** [comment]
@pwillia6 Thanks for getting back. SMS messages can be sent to and received from United States phone numbers. Phone numbers located in other geographies are not yet supported by Communication Services SMS. see [this](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/sms/send?pivots=programming-language-csharp). Did you try sending SMS to United States phone number and check if that works ?

@m4tx Could you please let me know which region you are sending the sms to ?

**Comment by m4tx** [comment]
@navba-MSFT none, the issue happens even when I just exec `az communication sms send-sms --help`. I haven't tried sending messages to any specific phone numbers. My Communication Services resource Data Location is Europe, if that matters.

**Comment by navba-MSFT** [comment]
@m4tx I ran the same above command on my Windows box with AzCLI 2.33.1 and it worked just fine. Could you please test it using the Azure Cloud Shell by clicking on the [Try It option here](https://docs.microsoft.com/en-us/cli/azure/communication/sms?view=azure-cli-latest#code-try-1) and test if you are facing the same issue ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@m4tx Thanks for the update.

@pwillia6 Since you are using the AzCLI on macOS (x86_64) installed via homebrew, Could you also test with Azure Cloud shell [TryIt option ](https://docs.microsoft.com/en-us/cli/azure/communication/sms?view=azure-cli-latest#code-try-1)instead ?

**Comment by navba-MSFT** [comment]
@pwillia6 A quick follow-up to check if you had a chance to look at my above comment. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@pwillia6 We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
