### ISSUE TITLE
set acl on storage container level 

### ISSUE THREAD

**Issue by Freia3** [Azure/azure-cli#21235]
**Is your feature request related to a problem? Please describe.**
I can use `az storage fs access` to set the POSIX access control rights on files and directories. But I want to set the access control on the container level. I don't see a way how to do this as the --path argument is mandatory.

**Describe the solution you'd like**
Make the --path argument optional

**Describe alternatives you've considered**
I've tried the following:  `az storage fs access set -f raw --acl "user::rwx,group::rwx,other::r-x,default:user::rwx,default:group::rwx,default:other::rwx" --account-name sa_name -p *` or
`az storage fs access set -f raw --acl "user::rwx,group::rwx,other::r-x,default:user::rwx,default:group::rwx,default:other::rwx" --account-name sa_name -p /*` but it does not work.

**Comment by yonzhan** [comment]
storage

**Comment by jonie001** [comment]
Hi @Freia3 ,you can try the following: 
az storage fs access set -f raw --acl "user::rwx,group::rwx,other::r-x,default:user::rwx,default:group::rwx,default:other::rwx" --account-name sa_name -p /
