### ISSUE TITLE
FunctionApp:`az functionapp config ssl bind` returns error saying webapp not found

### ISSUE THREAD

**Issue by calvinsID** [Azure/azure-cli#21237]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Running `az functionapp config ssl bind` returns error even if functionapp exists
![image](https://user-images.githubusercontent.com/14339314/153291412-c1540541-3f8b-4f51-8e94-c7dfa2fb74f1.png)

**To Reproduce**
`az functionapp config ssl bind`

**Expected behavior**
Expected not to error

**Environment summary**
Happens in az cli version 2.33.0+

**Comment by yonzhan** [comment]
route to service team

**Comment by panchagnula** [comment]
Closing this since the change related to this is merged.
