### ISSUE TITLE
Add "--no-auto-upgrade" or similar, to avoid quiet hangs in various SDK

### ISSUE THREAD

**Issue by elygre** [Azure/azure-cli#21249]
**Is your feature request related to a problem? Please describe.**
The Azure Python SDK uses the Azure CLI under the covers. Sometimes, nothing happens, and it's not obvious that the problem is the azure cli with autoupgrade. Aborting the program may for example show this stack trace:

```
subprocess.TimeoutExpired: Command '['cmd', '/c', 'az account get-access-token --output json --resource https://vault.azure.net']' timed out after 10 seconds
```

**Describe the solution you'd like**
Please add an option of type `--no-auto-upgrade` that disables the auto upgrade check. Once the Python SDK uses this, we will avoid this problem.

**Comment by elygre** [comment]
@yonzhan I yesterday opened two issues, this one here and on in the SDK repo (https://github.com/Azure/azure-sdk-for-python/issues/23016). The problem lives in the interaction between the SDK and the CLI, and changes are need in *both* places:

* It must be possible to instruct the CLI to not ask the upgrade question. This issue would ensure that this capability exists.
* Then the SDK must use this (new, yet unexisting) CLI capability. An issue was raised in the SDK repo to ensure they do.

But the SDK cannot fix this on their own; they need the capability to exist in the CLI. Please reopen this issue.

Also tagging @xiangyan99 , who was the first to react to this issue.

**Comment by derekantrican** [comment]
Looks like this is closed now. I had the same problem and turning off `auto-upgrade` worked, but I would still like the option that @elygre suggested of a `--no-auto-upgrade` global arg. Is that possible?

I am writing a AZ CLI wrapper (similar to the "various SDK" mentioned in the original report) and I don't want to have to change users' AZ configs to avoid these hangs.

**Comment by cedric05** [comment]
to disable auto upgrade prompt, use 
`az config set auto-upgrade.enable=no`
