### ISSUE TITLE
not able to create appservice plan. also it shows no tags (parameters) available for this command on pressing tab

### ISSUE THREAD

**Issue by kandarpgautam** [Azure/azure-cli#21242]
## Describe the bug

**Command Name**
`az appservice plan create`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan create -n {} -g {} --sku {}`

## Environment Summary
```
Linux-5.13.0-28-generic-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by PramodValavala-MSFT** [comment]
@kandarpgautam Looks like you are using a pretty old version of `az`. I can confirm this works with the latest version. Could you upgrade to the latest and try again?

**Comment by kandarpgautam** [comment]
@PramodValavala-MSFT ok I'll try that. but users can be thrown an error message if the CLI version being used is obsolete.
