### ISSUE TITLE
Add support for new APIs for Action Group Resource Provider

### ISSUE THREAD

**Issue by thomasp98296** [Azure/azure-cli#21251]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem.

**Describe the solution you'd like**
Our team owns the notification services which send out different types (SMS, Phone, Email, Webhooks, etc.) of notifications to Azure customers. We recently added a feature call Test Notifications which enabled customers to test the notifications (SMS, Phone, Emails, etc.). The feature is in public preview right now, but before we can declare this feature GA, we are required to add this support in Azure CLI Tool.

This feature only has two APIs.
1. createNotifications, a POST API which sends out notifications
2. notificationStatus, a GET API which gets the statuses of the notifications

**Describe alternatives you've considered**
There is no alternative as this is a feature request.

**Swagger**
https://github.com/Azure/azure-rest-api-specs/pull/18156

**Additional context**
You could find more about the Action Group Resource Provider here.
https://docs.microsoft.com/en-us/azure/azure-monitor/alerts/action-groups

https://docs.microsoft.com/en-us/rest/api/monitor/action-groups

**Comment by yonzhan** [comment]
Monitor
