### ISSUE TITLE
Application Gateway ssl-cert list shows data and password fields

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#2125]
Running a ssl-cert list shows data as null for all certificates while the actual data is in publicCertData. Can this and password field be hidden?

appgw ssl-cert list --gateway-name appgwtest -g appgw-rg
[
  {
    "data": null,
    "etag": "W/\"71acba41-aec9-48ea-b426-cf7c622c3e2e\"",
    "id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/appgw-RG/providers/Microsoft.Network/applicationGateways/appgwtest/sslCertificates/contosocert",
    "name": "contosocert",
    "password": null,
    "provisioningState": "Succeeded",
    "publicCertData": "MIIClTCCAf4CCQCycO33Jvo+9zANBgkqhkiG9w0BAQUFADCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAldBMRAwDgYDVQQHDAdSZWRtb25kMRQwEgYDVQQKDAtjb250b3NvLmNvbTEQMA4GA1UECwwHY29udG9zbzEUMBIGA94ToCIMn1CITZAsq5yAKT8BuYKkrZVHda2G7w9wnlvVCJszFlJA1sc2nvyvbZF2QPOym8bxmY1DjAg6SLoWgnw5twBy7rGu1qOX5rYNAgMBAAEwDQYJKoZIhvcNAQEFBQADgYEAuhF0HmHbBguWIiayMLsMihKtNtAA7rWGJ9ej/rEA480qSpz/Jm+Qo0SemEAx4k0+OHcK7gas1blTg1UsDXNzWceXF0PDN7z2i0YhbujJWtIt5w6sdFXPA9qlvKfbqTRU5WXONiam/aVOi5nCt53d/i/AcBFSOmO8DDNtwXToqTg=",
    "resourceGroup": "appgw-RG"
  },
  {
    "data": null,
    "etag": "W/\"71acba41-aec9-48ea-b426-cf7c622c3e2e\"",
    "id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/appgw-RG/providers/Microsoft.Network/applicationGateways/appgwtest/sslCertificates/fabrikamcert",
    "name": "fabrikamcert",
    "password": null,
    "provisioningState": "Succeeded",
    "publicCertData": "MIICnzCCAggCCQCTOjdp0b9z+jANBgkqhkiG9w0BAQUFADCBkzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAldBMRAwDgYDVQQHDAdSZWRtb25kMRUwEwYDVQQKDAxmYWJyaWthbS5jb20xETAPBgNVBAsMCGZhYnJpa2FtMRUwEwYDVQQDDAxmYWJyaWthbS5jb20xJDAiBgkqhkiG9w0BCQEWFWZhYnJpa2FtQGZhYnJpa2FtLmNvbTAeFw0xNjA3MDgyMjQzMTFaFw0xNzA3MDgyMjQzMTFaMIGTMQswCQYDVQQGEwJVUzELMAkGA1UECAwCV0ExEDAOBgNVBAcMB1JlZG1vbmQxFTATBgNVBAoMDGZhYnJpa2FtLmNvbTERMA8GA1UECwwIZmFicmlrYW0xFTATBgNVBAMMDGZhYnJpa2FtLmNvbTEkMCIGCSqGSIb3DQEJARYVZmFicmlrYW1AZmFic",
    "resourceGroup": "appgw-RG"
  }
]

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
