### ISSUE TITLE
Secure virtual networks availability in China region

### ISSUE THREAD

**Issue by Ashakya1511** [Azure/azure-cli#21250]
Hello,

We are trying to setup a virtual network in china region(east,east2,north and north2) with DDOS protection enabled but feature doesn't seem to be available from Azure portal or CLI. As per available documentations and blogs DDOS protection is generally available(GA), could you please help here? either by helping us enable the feature in Azure China region or indicate when this feature will be GA in China region.

**Issue**
DDOS protection setting unavailability in China region(s)
**Steps to reproduce**
1)Login to portal.azure.cn
2)Look for virtual networks in the marketplace
3)Create virtual network
4)On security page you will notice that ddos setting is missing
![image](https://user-images.githubusercontent.com/72612651/153519070-4ece8118-07cb-4946-b91b-2111a5645ce0.png)
Refer below image from Azure US region for comparison
![image](https://user-images.githubusercontent.com/72612651/153519169-db76957c-7793-41f1-a720-8b4c6ddfc122.png)
5) When tried to enable ddos from cli, getting the error below
![image](https://user-images.githubusercontent.com/72612651/153519247-c191e2ef-7047-4f23-a672-08b3fec99659.png)

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
@Ashakya1511 We have DDOS protection commands supported.  This is the test case. It may help you.

https://github.com/Azure/azure-cli/blob/30216d0268f3491b8af2aa060d90a9e1f94f9b3c/src/azure-cli/azure/cli/command_modules/network/tests/hybrid_2018_03_01/test_network_commands.py#L585-L623

**Comment by Ashakya1511** [comment]
Hello,

Thanks for your reply. I tried to configure an existing vnet in China east region but encountered similar error while creating ddos plan.

![image](https://user-images.githubusercontent.com/72612651/153742369-b69c0f05-1a8a-4a3c-9322-c22d51809a4f.png)

Regards,
Ashish

**Comment by PramodValavala-MSFT** [comment]
@Ashakya1511 According to the [products available by region page](https://azure.microsoft.com/en-us/global-infrastructure/services/?regions=all&products=ddos-protection), looks like DDoS Protection isn't available in the China Region.

![image](https://user-images.githubusercontent.com/43602528/155068673-9acca3fa-ebe2-4ad9-9a50-89d5da11cf03.png)
