### ISSUE TITLE
az login error- Failed to establish a new connection: [Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by shivamnamdeo43** [Azure/azure-cli#21267]
I have never seen this error before. While trying to authenticate with browser, I am getting below error. I checked that I am able to resolve other external as well as internal url's without any problem. The problem so far seems to be with az login only. 
I am using az docker 2.32.0 as my image. 
 
docker run -it -v ${HOME}/azcli/:/root/ --network bridge mcr.microsoft.com/azure-cli:2.32.0

bash-5.1# az login 
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXX to authenticate.

<urllib3.connection.HTTPSConnection object at 0x7f31ba0839d0>: Failed to establish a new connection: [Errno -2] Name does not resolve

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Similar to https://github.com/Azure/azure-cli/issues/21247

**Comment by jiasli** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/16524
