### ISSUE TITLE
Unable to connect to VM using bastion ssh

### ISSUE THREAD

**Issue by dilip814** [Azure/azure-cli#21269]
## Describe the bug

**Command Name**
`az network bastion ssh`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
The extension ssh is not installed.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 7995, in ssh_bastion_host
    _test_extension(SSH_EXTENSION_NAME)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 7928, in _test_extension
    ext = get_extension(extension_name)
  File "/usr/local/Cellar/azure-cli/2.32.0/libexec/lib/python3.10/site-packages/azure/cli/core/extension/__init__.py", line 340, in get_extension
    raise ExtensionNotInstalledException(ext_name)
azure.cli.core.extension.ExtensionNotInstalledException: The extension ssh is not installed.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network bastion ssh --name {} --resource-group {} --target-resource-id {} --auth-type {}`

## Environment Summary
```
macOS-12.1-x86_64-i386-64bit, Darwin 21.2.0
Python 3.10.1
Installer: HOMEBREW

azure-cli 2.32.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@dilip814 Apologies for the late reply. Could you please install the ssh extension using the below command ?

>az extension add --name ssh 

Then confirm if the extension is successfully installed by running the below command:

>az extension show -n ssh

After this you can try to run the _az network bastion ssh_ command to connect to the VM and test. Awaiting your reply.

**Comment by dilip814** [comment]
Hello,

Apologies, I missed to respond. Thanks for follow up. Yes, I am able to ssh VM using bastion but problem is it is only allowing to do only one connection to VM.

Thanks,
Dilip Patel

From: navba-MSFT ***@***.***>
Reply-To: Azure/azure-cli ***@***.***>
Date: Friday, 18 February 2022 at 12:07 PM
To: Azure/azure-cli ***@***.***>
Cc: Dilip Patel ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/azure-cli] Unable to connect to VM using bastion ssh (Issue #21269)


@dilip814<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdilip814&data=04%7C01%7Cdilip.1.patel-ext%40jci.com%7C5cf9d39711ad43f084c408d9f2a92219%7Ca1f1e2147ded45b681a19e8ae3459641%7C0%7C0%7C637807630499066996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AIkT5usQvaN7pieIf4DM6REcAwcoOPujeJbna9z6dp4%3D&reserved=0> A quick follow-up to check if you had a chance to try the action plan suggested in my above comment. Awaiting your reply.

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fissues%2F21269%23issuecomment-1043996721&data=04%7C01%7Cdilip.1.patel-ext%40jci.com%7C5cf9d39711ad43f084c408d9f2a92219%7Ca1f1e2147ded45b681a19e8ae3459641%7C0%7C0%7C637807630499066996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=C%2FKINEo2lBI7sTHboyKAdbzQIcZ%2FFS9Lfn2FB%2FXGxzw%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWBGKOJ4B4MQ2OBJJ4YAQYDU3XSKPANCNFSM5OGVR7NQ&data=04%7C01%7Cdilip.1.patel-ext%40jci.com%7C5cf9d39711ad43f084c408d9f2a92219%7Ca1f1e2147ded45b681a19e8ae3459641%7C0%7C0%7C637807630499066996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=95sELoGYHbzgKYVdywOsLPkBj2I3ofNRvD4ah2M5Ouc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdilip.1.patel-ext%40jci.com%7C5cf9d39711ad43f084c408d9f2a92219%7Ca1f1e2147ded45b681a19e8ae3459641%7C0%7C0%7C637807630499066996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=76JI8YDE73%2FKzE2bENA6SAlmqhqN5Vzz2D%2Fg4nBJwM0%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdilip.1.patel-ext%40jci.com%7C5cf9d39711ad43f084c408d9f2a92219%7Ca1f1e2147ded45b681a19e8ae3459641%7C0%7C0%7C637807630499066996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BOLMY%2BoypK9Ed3F6T7HymgOQEjp7ic6k9ty0kqQLvps%3D&reserved=0>.

**Comment by navba-MSFT** [comment]
@dilip814 Thanks for getting back. Each instance can support 10 concurrent RDP connections and 50 concurrent SSH connections. The number of connections per instances depends on what actions you are taking when connected to the client VM. For example, if you are doing something data intensive, it creates a larger load for the instance to process. Once the concurrent sessions are exceeded, an additional scale unit (instance) is required. Refer [this](https://docs.microsoft.com/en-us/azure/bastion/configuration-settings#instance) and [this](https://docs.microsoft.com/en-us/answers/questions/677179/connect-multiple-monitors-in-azure-bastion.html) article for more info.

**Comment by navba-MSFT** [comment]
@dilip814 Hope you had a chance to look at my above comment. Please let me know if you need any further assistance on this.

**Comment by dilip814** [comment]
Yes, we are good now.

**Comment by navba-MSFT** [comment]
Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
