### ISSUE TITLE
Release docker image for arm64

### ISSUE THREAD

**Issue by odidev** [Azure/azure-cli#21280]
Hi Team, 

I am trying to use the **microsoft/azure-cli** image on the arm64 platform but it seems it is not available for arm64. 

I have successfully built the image using the command docker build -t image_name . on the arm64 platform by making some changes in the files **Dockerfile** and **.github/workflows/ci.yml**. 

I have used Github action to build and push the image for both the platforms. 

**Commit Link** - https://github.com/odidev/azure-cli/commit/62456566b6b13b3012bf646cddfdb407cba299c0 

**Github action link** - https://github.com/odidev/azure-cli/runs/5153354004?check_suite_focus=true 

**Docker Hub Link** - https://hub.docker.com/repository/docker/odidev/azure-cli 

Do you have any plans on releasing arm64 images? 

It will be very helpful if an arm64 image is available. If interested, I will raise a PR

**Comment by yonzhan** [comment]
arm64

**Comment by iemejia** [comment]
Any news on this? Wondering if with the new Azure instances for ARM64 + the Microsoft Dev Kit this makes more and more sense to publish the arm64 version too

**Comment by bebound** [comment]
I'm working on ARM64 support, docker image is also included in the plan.
Here is the PR: https://github.com/Azure/azure-cli/pull/24180
