### ISSUE TITLE
az logicapp create command not working

### ISSUE THREAD

**Issue by Chandrb** [Azure/azure-cli#21288]
**Describe the bug**
I am trying to create a logic app workflow on a  Logic App standard plan and it is giving me error.

**Steps to reproduce the issue**
I ran the below command (with the Logic app standard plan: chanmylogcapp and storage: chanmystgacct8 in the same resource group).
az logicapp create -g mygroup --subscription sub-83 -p chanmylogcapp -n chanlogcapp1 -s chanmystgacct8

**Error Message**
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'reserved'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 38, in _ex_handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/logicapp/custom.py", line 99, in create_logicapp
    is_linux = plan_info.reserved
AttributeError: 'NoneType' object has no attribute 'reserved'

**Expected behavior**
I expect the command to create a workflow in the logicapp standard plan.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@Chandrb You are using wrong cmdlet and if you want to create a logic app workflow then you need to use `az logic workflow create` as described [here](https://docs.microsoft.com/en-us/cli/azure/logic/workflow?view=azure-cli-latest#az-logic-workflow-create).
The command you are using creates a new logic app and you are getting this error as you are not passing correct values against `--plan` of `-p`.  You need to pass the App service plan name under which you want your logic app to reside.
Thanks

**Comment by Chandrb** [comment]
> Thanks @SaurabhSharma-MSFT. I have a quick question in that case, how do i create the workflow in the logic app standard plan by giving plan name to the az workflow create command and not the consumption mode.

**Comment by SaurabhSharma-MSFT** [comment]
@Chandrb You cannot pass the plan information while creating a workflow as the plan name is required while creating the logic app itself.

**Comment by archidda** [comment]
@SaurabhSharma-MSFT, Here, @Chandrb is working with logic app standard and not consumption. commands starting with `az logic` are for consumption and commands starting with `az logicapp` are for standard.

@Chandrb, can you confirm the plan that you are using is either Workflow standard plan (WS1, WS2, or WS3) or ASEv3 because we only support these two types of plans for Logicapp standard. Moreover, the command you have used will create a logicapp standard and not add workflows to it. We currently do not have commands for CRUD operations on workflows. You can use zip deploy if you have workflows to deploy.

Here are some links to Microsoft docs for you-

- https://docs.microsoft.com/en-us/azure/logic-apps/set-up-devops-deployment-single-tenant-azure-logic-apps?tabs=azure-cli#install-azure-logic-apps-standard-extension-for-azure-cli
- https://docs.microsoft.com/en-us/azure/logic-apps/azure-arc-enabled-logic-apps-create-deploy-workflows?tabs=azure-cli

**Comment by Chandrb** [comment]
Thanks @archidda, @SaurabhSharma-MSFT  and it worked.

**Comment by archidda** [comment]
Happy to help :)

**Comment by Rajuvimal** [comment]
getting this error
az: 'logicapp' is not in the 'az' command group.
I try this az extension add --yes --source "https://aka.ms/logicapp-latest-py2.py3-none-any.whl"
but still have the issue

**Comment by archidda** [comment]
@Rajuvimal can you create a new issue to track it separately? Also provide output of `az version`

**Comment by Rajuvimal** [comment]
can you please help me too
identify that who are not using mfa in azure by listing with azure cli command

**Comment by Rajuvimal** [comment]
when i use " az ad group list '  get an error Insufficient privileges to complete the operation.

**Comment by Rajuvimal** [comment]
@archidda im ubuntu terminal in Windows

**Comment by Rajuvimal** [comment]
The underlying Active Directory Graph API will be replaced by Microsoft Graph API in a future version of Azure CLI. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration

**Comment by meetpatel1111** [comment]
@archidda Can I get the same solution for databricks and datafactory?
Need source link for databricks and datafactory.

e.g. - az extension add --yes --source "https://aka.ms/logicapp-latest-py2.py3-none-any.whl"
or command to get the status of these services .e.g- running or not

Thanks in advance

**Comment by archidda** [comment]
@meetpatel1111 you will have to open a separate ticket for that so folks from those teams can help you.
