### ISSUE TITLE
AZ Cli Commands Do Nothing

### ISSUE THREAD

**Issue by mslentz** [Azure/azure-cli#21295]
This appears to be very similar to: https://github.com/Azure/azure-cli/issues/13569

To Reproduce
- install azure CLI tool
- open a power shell window, type az login (or any other command from the az CLI)
- nothing happens

OS Name	                Microsoft Windows 11 Pro
Version	                10.0.22000 Build 22000
Azure CLI is              2.33.1
power shell              7.2.1

When running get-command az I get:
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     az.cmd                                             0.0.0.0    C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd

az.cmd looks like this:
::
:: Microsoft Azure CLI - Windows Installer - Author file components script
:: Copyright (C) Microsoft Corporation. All Rights Reserved.
::

@IF EXIST "%~dp0\..\python.exe" (
  SET AZ_INSTALLER=MSI
  "%~dp0\..\python.exe" -IBm azure.cli %*
) ELSE (
  echo Failed to load python executable.
  exit /b 1
)

![screen-capture](https://user-images.githubusercontent.com/18287652/153959068-68746e34-1126-4ce7-8371-485ee7216183.png)

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by veerun14** [comment]
I have the same issue. 
Running any _az_ command does nothing and returns without any errors.

Installed az cli using this command

`Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'`


OS: Windows Server 2022 Datacenter
Version 10.0.20348.587
Azure CLI verion: _well, az --version does nothing_
Windows PowerShell 5.1.20348.558

**Comment by jiasli** [comment]
1. Could you check if there are some registry items like `AutoRun` configured https://github.com/Azure/azure-cli/issues/19202#issuecomment-898271305

2. Does it work if you directly invoke 
   ```
   & "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -IBm azure.cli
   ```

3. If you create a cmd file like `test.cmd`:
   ```
   echo "Hello World"
   ```   
   Are you able to successfully run `./test.cmd` and get `Hello World` printed?

**Comment by mslentz** [comment]
> 1. Could you check if there are some registry items like `AutoRun` configured [Program 'az.cmd' failed to run: The system cannot find the file specifiedAt line:1 char:1 #19202 (comment)](https://github.com/Azure/azure-cli/issues/19202#issuecomment-898271305)
> 2. Does it work if you directly invoke
>    ```
>    & "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -IBm azure.cli
>    ```
> 3. If you create a cmd file like `test.cmd`:
>    ```
>    echo "Hello World"
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Are you able to successfully run `./test.cmd` and get `Hello World` printed?

I checked HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun and found the value: 

if exist & if exist "C:\Users\xxxxxx\Anaconda3\condabin\conda_hook.bat" "C:\Users\xxxxx\Anaconda3\condabin\conda_hook.bat"

I removed it as suggested in the linked issue and everything works correctly now.  Thank you so much for your help!!
