### ISSUE TITLE
az pipelines variable-group variable list -o table truncates variable values.

### ISSUE THREAD

**Issue by samrueby** [Azure/azure-cli#21291]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
If you run `az pipelines variable-group variable list -o table` truncates variable values. Variable values will be truncated after about 70 characters. There is no way to avoid this truncation.

**To Reproduce**
Run `az pipelines variable-group variable list -o table truncates variable values.` (with additional required parameters) with at least one variable value greater than 70 characters. The end of the value will have an ellipsis instead of the rest of the value.

**Expected behavior**
Either do not truncate or provide a command line argument to remove truncation.

**Environment summary**
cmd, win10.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@samrueby Apologies for the late reply. Did you try using `Format-Table -Wrap -Autosize `  to the output and check if that helps ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@samrueby I wanted to do quick follow-up to check if you had a chance to look at my above comment. This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by samrueby** [comment]
I'm sorry, I don't think I understand. This is `az`, so I'm using cmd, not PowerShell. I recognize you can run az in powershell, but I'm not a powershell expert. I tried to pipe the output to | Format-Table -Wrap -Autosize, but that didn't do anything because the default output is json, and it wouldn't make sense to do it to the output with -o table because the values are already truncated before it goes anywhere, which is the problem I'm describing.

**Comment by navba-MSFT** [comment]
@samrueby Thanks for getting back. Did you check the feasibility of the second action plan mentioned in my above comment ?

>Adding another plan here to check if you can split your variable into smaller strings and concatenate them after (e.g. var_1=”FOO”, var_2=”BAR”, var="$( var_1) $( var_2) such that var=”FOOBAR”" ) and check if that helps.
