### ISSUE TITLE
Add new property of hub routing preference in virtual hub

### ISSUE THREAD

**Issue by zaynchen115** [Azure/azure-cli#21292]
**Resource Provider**

Azure Network
**Description of Feature or Work Requested**

A new parameter 'HubRoutingPreference' need be added when create or update virtual hubs to allow customer change the routing preference in virtual hub
**Minimum API Version Required**

2021-08-01
**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/17609/files
**Target Date**

2022-03-20

**Comment by yonzhan** [comment]
network

**Comment by kairu-ms** [comment]
Hi @zaynchen115, we cannot support this feature unless python SDK with api version 2021-08-01 is public released.

**Comment by YuanyuanNi** [comment]
PR:https://github.com/Azure/azure-cli-extensions/pull/4788
