### ISSUE TITLE
[ElasticSan] request for release (private preview on May)

### ISSUE THREAD

**Issue by blueww** [Azure/azure-cli#21299]
**Resource Provider**

Microsoft.ElasticSan

**Description of Feature or Work Requested**

Azure Elastic SAN is a new block storage offering designed as an evolution of Azure Disk.
See details in doc: 

- [Cloud SAN Strategy (2 pager) (1).docx](https://nam06.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fmicrosoftapc-my.sharepoint.com%2F%3Aw%3A%2Fg%2Fpersonal%2Fpprahalad_microsoft_com%2FEYRO1vapxxVAisbPdLzU9FwBpPcrd8MvxeX7Y9MyXaiPEQ%3FwdOrigin%3DTEAMS-ELECTRON.p2p.mw%26wdExp%3DTEAMS-TREATMENT%26wdhostclicktime%3D1640235930463%26isSPOFile%3D1&data=04%7C01%7Cweiwei%40microsoft.com%7C4acac78077e74536e17508d9d47ef16b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637774463952169023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fctllAIRBJpA77FYbRYFdMywfshA9b1jjysBZiwbgwU%3D&reserved=0)
-  [ElasticSAN design draft.docx](https://microsoft.sharepoint.com/:w:/t/AzureStorage/EV3yeGDiDw5OhxhAxN_V7WIBfCfdoeaScjJxhyERlHtXPQ?e=UwIcQV&wdOrigin=TEAMS-ELECTRON.p2p.bim&wdExp=TEAMS-TREATMENT&wdhostclicktime=1636563076335&isSPOFile=1) 

**Minimum API Version Required**

2021-11-20-preview

**Swagger Link**

swagger PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/5723

**Target Date**

private preview in May
It would be better can give a private CLI package early before that, for feature team to test. 

For you reference: [Powershell Design](https://microsoft.sharepoint.com/:w:/t/AzureStorage/ETFjaWGEkHJKmPYONbGV7-MB2C3Y1wKTSVpxgrn00PPZXQ?e=24Dj3q&CID=064C48C4-4894-4437-BAC0-FA2687068EDC&wdLOR=c47976599-D41A-49A4-BAAF-ECD7B843EE68)
Please note, Powershell is auto-generated from swagger.
Current we still not get a ready environment to test it.

**Comment by yonzhan** [comment]
PLR

**Comment by calvinhzy** [comment]
Please try this whl file https://zhiyihuangsa.blob.core.windows.net/sharing/elastic_san-0.1.0-py3-none-any.whl
