### ISSUE TITLE
Azure KeyVault certificate's secret download gives error message when providing --file

### ISSUE THREAD

**Issue by RemcoBuddelmeijer** [Azure/azure-cli#21290]
**Describe the bug**

When executing the command `az keyvault secret download --vault-name {0} --name {CERTIFICATE_NAME} --file {2}` for exporting a secret (private key) from a **certificate**, the following error message is printed out: 
`the following arguments are required: --file/-f`

However when you supply it with `-f` instead of `--file` it does work.

**To Reproduce**

1. Create or import a certificate in Azure KeyVault.
2. Export a secret (private key) of the **certificate** in Azure KeyVault using Azure CLI. The steps to do this are described [here](https://docs.microsoft.com/en-us/azure/key-vault/certificates/how-to-export-certificate?tabs=azure-cli#export-stored-certificates).

**Expected behavior**

No error message is given and the behaviour works just as when executing the command with `-f`

**Environment summary**

Azure DevOps Pipelines AzureCLI@2 task: v2.32.0

**Additional context**
Fixed in Azure CLI v2.33.1

**Comment by yonzhan** [comment]
keyvault

**Comment by RemcoBuddelmeijer** [comment]
Fixed in Azure CLI v2.33.1
