### ISSUE TITLE
a bug while creating service plan

### ISSUE THREAD

**Issue by pmalczak** [Azure/azure-cli#21310]
## Describe the bug

**Command Name**
`az appservice plan create`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az appservice plan create -g {} -n {} -l {} --is-linux --sku {}`

## Environment Summary
```
Linux-5.4.0-99-generic-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@pmalczak I believe this has since been fixed and I can confirm that it does work with the latest version of Azure CLI. Could you upgrade and try again?

**Comment by pmalczak** [comment]
I've been installing and upgrading azure-cli via apt-get.
It's not enough to fix the problem. 

As I see, **/etc/apt/sources.list.d/azure-cli** contains:
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ una main

which ends up with:
Błąd:13 https://packages.microsoft.com/repos/azure-cli stable Release
  404  Not Found [IP: 13.81.215.193 443]
Czytanie list pakietów... Gotowe                                
E: The repository 'https://packages.microsoft.com/repos/azure-cli stable Release' does not have a Release file.

Sorry, it's messed up much more.
I've surrendered and moved from linux to windows power shell and finished up the job.
Anyway, thank you for assistance

**Comment by pmalczak** [comment]
I've been installing and upgrading azure-cli via apt-get.
It's not enough to fix the problem. 

As I see, **/etc/apt/sources.list.d/azure-cli** contains:
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ una main

which ends up with:
Błąd:13 https://packages.microsoft.com/repos/azure-cli stable Release
  404  Not Found [IP: 13.81.215.193 443]
Czytanie list pakietów... Gotowe                                
E: The repository 'https://packages.microsoft.com/repos/azure-cli stable Release' does not have a Release file.

Sorry, it's messed up much more.
I've surrendered and moved from linux to windows power shell and finished up the job.
Anyway, thank you for assistance
