### ISSUE TITLE
Trying to update existing aks cluster with OIDC Issuer

### ISSUE THREAD

**Issue by mirakelsvampen** [Azure/azure-cli#21325]
## Describe the bug
Following [this guide here ](https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#oidc-issuer-preview) I tried to update my existing cluster with the OIDC Issuer and got the following error.

Complete command: `az aks update -n aks -g myResourceGroup --enable-oidc-issuer`

**Command Name**
`az aks update `

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

cannot import name 'edge_zone_type'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 559, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 506, in load_arguments
  File "H:\\.azure\cliextensions\aks-preview\azext_aks_preview\__init__.py", line 47, in load_arguments
    from ._params import load_arguments
  File "H:\\.azure\cliextensions\aks-preview\azext_aks_preview\_params.py", line 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update -n {} -g {} --enable-oidc-issuer`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.21.0 *

Extensions:
aks-preview 0.5.41
ml 2.0.1a1

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@mirakelsvampen Thanks for reaching out to us. You are using an older version of Azure CLI. Please upgrade to the most [recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) (2.33.1) of the Az CLI and run the command again. Please let me know if you face any issues. Awaiting your reply.

Similar issue #20912

**Comment by navba-MSFT** [comment]
@mirakelsvampen I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mirakelsvampen We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
