### ISSUE TITLE
Clarify that diagnostic settings retention only applies for Storage

### ISSUE THREAD

**Issue by jelledruyts** [Azure/azure-cli#21328]
The `az monitor diagnostic-settings` doc should clarify the `retentionPolicy` schema as it's now only shown in an example, and most importantly it should call out that **retention policies can only be used when targeting a Storage account**. That example which now shows retention policy furthermore has a `--event-hub-rule {eventHubRuleID}` parameter which doesn't make sense in this case as the diagnostics target is a Storage account, not Event Hub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9ae3afa-74ff-12e8-a32c-c01240bd37da
* Version Independent ID: 522b7e55-2510-8e51-021a-2fc134fabfbe
* Content: [az monitor diagnostic-settings](https://docs.microsoft.com/en-us/cli/azure/monitor/diagnostic-settings?view=azure-cli-latest#az_monitor_diagnostic_settings_create)
* Content Source: [latest/docs-ref-autogen/monitor/diagnostic-settings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/monitor/diagnostic-settings.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
monitor

**Comment by jelledruyts** [comment]
@yonzhan @kairu-ms I'm not sure what the process is for CLI repo contributions but is there any action required on me please? Can we look to incorporate this small change to remove confusion for customers?

**Comment by kairu-ms** [comment]
Hi @jelledruyts, are you talking about this command? https://github.com/Azure/azure-cli/blob/086e8934ed2c18c65debfb8a867e05961bd3521a/src/azure-cli/azure/cli/command_modules/monitor/_help.py#L822-L876

**Comment by jelledruyts** [comment]
Hi @kairu-ms, yes those commands include either `--log` or `--metrics` which contain `diagnosticSettings` but the schema isn't mentioned, only examples. I'd say the following actions would be good:

- Under the **Optional parameters** header, the `--logs` and `--metrics` parameters should link to the schema definitions, respectively [here](https://docs.microsoft.com/rest/api/monitor/diagnostic-settings/create-or-update#logsettings) and [here](https://docs.microsoft.com/rest/api/monitor/diagnostic-settings/create-or-update#metricsettings).
- That [API doc has the RetentionPolicy schema defined](https://docs.microsoft.com/rest/api/monitor/diagnostic-settings/create-or-update#retentionpolicy), but it should mention that retention only applies when the target is a storage account. Perhaps that doc is owned by a different team, but if that's the case then I'm not sure how to approach them to ask for this clarification?
- Ideally, the CLI doc we're talking about here would also note the fact that retention only applies when the target is a storage account to avoid customer confusion.
- The CLI doc should remove the `--event-hub-rule {eventHubRuleID}` parameter from [the example](https://docs.microsoft.com/en-us/cli/azure/monitor/diagnostic-settings?view=azure-cli-latest#az-monitor-diagnostic-settings-create-examples) as it doesn't make sense.

Hope that helps!

**Comment by kairu-ms** [comment]
Thanks @jelledruyts, we will fix it.
