### ISSUE TITLE
Intermittent rate limit errors cause CI/CD pipelines to fail when using the azure cli

### ISSUE THREAD

**Issue by Xitric** [Azure/azure-cli#21338]
**Describe the bug**
We are running the azure cli in a pipeline on Bitbucket to deploy Bicep templates to our development environment, and soon enough to production as well. Intermittently, our pipelines fail due to rate limits when the Azure CLI performs a version check for Bicep. Running `az deployment group create ...` _sometimes_ fails with:

```
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/resource/_bicep.py", line 157, in get_bicep_latest_release_tag
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Azure/bicep/releases/latest
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/resource/custom.py", line 542, in deploy_arm_template_at_resource_group
    return _deploy_arm_template_at_resource_group(cmd=cmd,
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/resource/custom.py", line 571, in _deploy_arm_template_at_resource_group
    deployment_properties = _prepare_deployment_properties_unmodified(cmd, 'resourceGroup', template_file=template_file,
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/resource/custom.py", line 982, in _prepare_deployment_properties_unmodified
    run_bicep_command(["build", "--stdout", template_file])
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/resource/_bicep.py", line 63, in run_bicep_command
    ensure_bicep_installation(stdout=False)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/resource/_bicep.py", line 106, in ensure_bicep_installation
    release_tag = release_tag if release_tag else get_bicep_latest_release_tag()
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/resource/_bicep.py", line 160, in get_bicep_latest_release_tag
    raise ClientRequestError(f"Error while attempting to retrieve the latest Bicep version: {err}.")
azure.cli.core.azclierror.ClientRequestError: Error while attempting to retrieve the latest Bicep version: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Azure/bicep/releases/latest.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/arm.py", line 109, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'ClientRequestError' object has no attribute 'inner_exception'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/arm.py", line 114, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: Error while attempting to retrieve the latest Bicep version: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Azure/bicep/releases/latest.
ERROR: cli.azure.cli.core.azclierror: Error while attempting to retrieve the latest Bicep version: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Azure/bicep/releases/latest.
ERROR: az_command_data_logger: Error while attempting to retrieve the latest Bicep version: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Azure/bicep/releases/latest.
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f458d57df70>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 0.642 seconds (init: 0.137, invoke: 0.505)
INFO: telemetry.save: Save telemetry record of length 3236 in cache
WARNING: telemetry.check: Negative: The /root/.azure/telemetry.txt was modified at 2022-02-17 09:03:42.859799, which in less than 600.000000 s
```

**To Reproduce**
Run `az deployment group create ...` in a Bitbucket pipeline, and hope for the worst I guess.

**Expected behavior**
We expect that our `az deployment group create ...` behaves consistently, and is not failing due to rate limits in version checks.

**Environment summary**
Bitbucket pipelines using the image:

```
mcr.microsoft.com/azure-cli@sha256:d2a53ad219b28567e256693eba1b985bbebea4687fddf293b0ab6d75ab9f728b
```

**Additional context**
We are worried that this behavior may be caused by multiple clients sharing the same IP address in Bitbucket pipelines, which thus increases the risk of hitting this API limit. In any event, we can think of two solutions that seem reasonable:

- Do not return an erroneous exit code just because the version check fails, but rather log a warning and carry on with the command
- Add a flag to disable version checks entirely, which could be useful in CI/CD environments

If this is simply because we are using the tool incorrectly, please let us know how to do better!

**Comment by yonzhan** [comment]
ARM

**Comment by Agger1995** [comment]
Hi.

As this has become a recurring issue for us, we would like to bring further attention to it.
We (@Xitric and myself) have spent some time identifying the root cause of the issue, and it seems to boil down to a simple matter of incorrect error suppression in try-except constructions.

The error occurs during the function `ensure_bicep_installation`, when it invokes `get_bicep_latest_release_tag`.
https://github.com/Azure/azure-cli/blob/f70a427035f4577c817942968183d475a415bcb2/src/azure-cli/azure/cli/command_modules/resource/_bicep.py#L103

A rate limit error returned from the GitHub API will be translated correctly into a `ClientRequestError`, as seen in the function `get_bicep_latest_release_tag`.
https://github.com/Azure/azure-cli/blob/f70a427035f4577c817942968183d475a415bcb2/src/azure-cli/azure/cli/command_modules/resource/_bicep.py#L149-L155

However, when that function is invoked by `ensure_bicep_installation` it happens within a scope that doesn't suppress the `ClientRequestError`. All of this is contained in the function `run_bicep_command`.
https://github.com/Azure/azure-cli/blob/f70a427035f4577c817942968183d475a415bcb2/src/azure-cli/azure/cli/command_modules/resource/_bicep.py#L54-L82

The fix we have identified for this, is to simply move the error suppression already defined in `run_bicep_command`, to include the function call to `ensure_bicep_installation`.
https://github.com/Azure/azure-cli/blob/f70a427035f4577c817942968183d475a415bcb2/src/azure-cli/azure/cli/command_modules/resource/_bicep.py#L66

Please let us know if this will be an acceptable solution, and whether there are other angles to this, that we may not have considered.

**Comment by zhoxing-ms** [comment]
@Shenglol Could you help  look at the bicep related issue?

**Comment by rouke-broersma** [comment]
@Agger1995 the issue with your solution is that this only works if your client already has been installed. There is still the case where the bicep binary is not yet available on the system but rate limiting is hit due to requests to the github api by other clients.

**Comment by justinmchase** [comment]
@rouke-broersma @Agger1995 

I was going to say the same thing, in my case is its not installed at all yet. That being said, I don't see why you wouldn't take the change proposed, because in the other case it likely would help. But I wouldn't consider it to solve the issue.

**Comment by rouke-broersma** [comment]
I agree, I just think that case does need to be caught and have it's own error message instead of adding this suppression and then dying somewhere else down the line because the binary doesn't actually exist.

**Comment by Xitric** [comment]
We just went over the source code again, and it turns out that we had a wrong impression of the Docker image we were using - we assumed Bicep was included, but we see now that it is in fact installed every time. So in that regard, the CLI is working correctly. But it is true that a more descriptive error message would be preferred.

Until they find a solution to their rate limit issues in the Bicep project, I guess we will just resort to using a custom Docker image for our pipeline.

**Comment by alex-frankel** [comment]
Just as FYI - we plan to host bicep on a CDN in the near future to avoid hitting the rate limit:
https://github.com/Azure/bicep/issues/3689

**Comment by navba-MSFT** [comment]
@Xitric Thanks for the update. Please let us know if you need any further assistance on this issue. Awaiting your reply.

**Comment by Xitric** [comment]
Hello @navba-MSFT, we do not need any more assistance on this issue, and are simply waiting for updates on the use of a CDN. In the meantime we may need to use workarounds.

**Comment by DevStarOps** [comment]
@alex-frankel / @navba-MSFT 
Any ETA on this moving to a CDN? 7 months feels a little excessive to just let the tooling break.

**Comment by gammelgaard52** [comment]
I am facing the same problems when using GitHub Actions - it's really starting to be annoying and impact business, due to the lack of ability to simply deploy resources to Azure.

**Comment by murratore** [comment]
same here for me. sometimes it is working, sometimes not.
