### ISSUE TITLE
[DNS] Zone import output doesn't indicate overall progress

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#2133]
During zone import, I see a progress report listing each record imported.

The problem is that importing a large zone may take a long time, and I don't get any information that tells me how far I've got / how much is left to run.

Can we change the output to include current record number / total records?

E.g.

`Importing record 35,234 of 250,000, of type CNAME, record name "foo.bar.com"`

**Comment by derekbekoe** [comment]
This is related to https://github.com/Azure/azure-cli/issues/987.

**Comment by jtuliani** [comment]
I'm not so sure.  #987 seems to relate to operations that are long-running on the server side.  That is not the case here.

Zone import is highly unusual, in that it has substantial CLI logic to parse the zone file and turn it into individual API calls. Each call is short, the time is consumed because there are so many calls to make when importing a large file.

**Comment by derekbekoe** [comment]
I guess I meant it's related in that you're looking to get **progress** whilst the command is running.
This issue can still stand on its own.
