### ISSUE TITLE
Azure CLI to automatically print help message when there is a missing argument

### ISSUE THREAD

**Issue by vxfield** [Azure/azure-cli#21337]
**Is your feature request related to a problem? Please describe.**
Azure CLI should automatically print the help message in the absence of a sub_command or required parameter.
Still, differently then running it with "--help", which has a successful exit code with value `0`, it should still return a failure non-zero exit code.

Some users get confused with the current error message. See #21307

For example, consider the following scenarios:
1) When you run just `az` you get a list of base commands.
2) When you run `az storage` you get an error message saying `the following arguments are required: _subcommand` which is not much helpful as in scenario (1)
3) When you run `az storage account` you also get an error message saying `the following arguments are required: _subcommand` which is not much helpful as in scenario (1)

**Describe the solution you'd like**
When you run `az storage` you should still get an error message like `the following arguments are required: _subcommand`.
But then, automatically print the help message for that command/sub_command, equivalent of running `az storage --help` but with a non-zero exit code.

_Current result:_
```
> az storage
the following arguments are required: _subcommand

Examples from AI knowledge base:
az storage account list
List all storage accounts in a subscription.

https://docs.microsoft.com/en-US/cli/azure/storage/account#az_storage_account_list
Read more about the command in reference docs
```

_Desired result:_
```
> az storage
the following arguments are required: _subcommand

Group
    az storage : Manage Azure Cloud Storage resources.

Subgroups:
    account          : Manage storage accounts.
    blob             : Manage object storage for unstructured data (blobs).
    container        : Manage blob storage containers.
    container-rm     : Manage Azure containers using the Microsoft.Storage resource provider.
    cors             : Manage storage service Cross-Origin Resource Sharing (CORS).
    directory        : Manage file storage directories.
    entity           : Manage table storage entities.
    file             : Manage file shares that use the SMB 3.0 protocol.
    fs               : Manage file systems in Azure Data Lake Storage Gen2 account.
    logging          : Manage storage service logging information.
    message          : Manage queue storage messages.
    metrics          : Manage storage service metrics.
    queue            : Manage storage queues.
    share            : Manage file shares.
    share-rm         : Manage Azure file shares using the Microsoft.Storage resource provider.
    table            : Manage NoSQL key-value storage.

Commands:
    copy             : Copy files or directories to or from Azure storage.
    remove [Preview] : Delete blobs or files from Azure Storage.

To search AI knowledge base for examples, use: az find "az storage"

Please let us know how we are doing: https://aka.ms/azureclihats
```

Same thing when you run `az storage account` you should still get an error message like `the following arguments are required: _subcommand`.
But then, automatically print the help message for that command/sub_command, equivalent of running `az storage account --help` but with a non-zero exit code.

And so on...

**Additional context**

See issue #21307

**Comment by yonzhan** [comment]
Storage

**Comment by jiasli** [comment]
Tracked by #19592
