### ISSUE TITLE
keyvault network-rule Add/Remove incorrect behavior

### ISSUE THREAD

**Issue by 5dive** [Azure/azure-cli#21330]
Network rule for IP Address added to a keyvault can not be removed using the same IP Address

Environment
Azure CLI version:

> azure-cli                         2.28.0
core                              2.28.0
telemetry                          1.0.6
Extensions:
ssh                                0.1.6

Prerequisite:
* key vault resource added in a subscription
* key vault name is assumed to be "todelete"

**Steps:**
1. Authenticate using az login
2. Update the key vault to have default action as Deny using following command:

`az keyvault update --name todelete --default-action Deny`

This command generates output.  following is snippet from the same:

>     "networkAcls": {
>       "bypass": "AzureServices",
>       "defaultAction": "Deny",
>       "ipRules": [],
>       "virtualNetworkRules": []
>     },
> 

3. Add network rule for IP Address using following command

`az keyvault network-rule add -n todelete --ip-address 123.0.0.1`

This command generates output.  following is snippet from the same:

>     "networkAcls": {
>       "bypass": "AzureServices",
>       "defaultAction": "Deny",
>       "ipRules": [
>         {
>           "value": "123.0.0.1/32"
>         }
>       ],
>       "virtualNetworkRules": []
>     },

4. Remove network rule for the IP address used in earlier step using following command:

`az keyvault network-rule remove -n todelete --ip-address 123.0.0.1`

This command generates output.  following is snippet from the same:

>     "networkAcls": {
>       "bypass": "AzureServices",
>       "defaultAction": "Deny",
>       "ipRules": [
>         {
>           "value": "123.0.0.1/32"
>         }
>       ],
>       "virtualNetworkRules": []
>     },

**Behavior:**
_Actual:_ az keyvault network-rule remove command does not remove the specified IP address from the ip rules
_Expected:_ az keyvault network-rule remove command should have removed the specified ip address from the ip rules.

**Note:** similar commands are available for storage account resource with different behavior.

**Comment by yonzhan** [comment]
keyvault

**Comment by 5dive** [comment]
similar ticket: https://github.com/Azure/azure-cli/issues/18167 .  seems quite an old behavior.

**Comment by jonie001** [comment]
#21630

**Comment by 5dive** [comment]
many thanks!!
