### ISSUE TITLE
'VMCustomization' is not enabled for the Subscription.

### ISSUE THREAD

**Issue by neslop8** [Azure/azure-cli#21343]
**Resource Provider**
VMCustomization

**Description of Feature or Work Requested**
USERNAME=azureuser
PASSWORD=$(openssl rand -base64 32)
az vm create \
  --resource-group learn-71120265-74f9-4e22-9c89-7e151156f4d9 \
  --name myVM \
  --image win2019datacenter \
  --admin-username $USERNAME \
  --admin-password $PASSWORD

**Minimum API Version Required**
az --version
azure-cli                         2.33.0 *

core                              2.33.0 *
telemetry                          1.0.6

Extensions:
ai-examples                        0.2.5
ssh                                1.0.0

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

**Swagger Link**
https://docs.microsoft.com/es-es/learn/modules/protect-vm-settings-with-dsc/4-exercise-setup-dsc-configuration

**Target Date**
28 de febrero 2022

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
Fixed by #21232
