### ISSUE TITLE
Python error thrown with az role assignment create: AttributeError: 'RoleAssignmentsOperations' object has no attribute 'config'

### ISSUE THREAD

**Issue by bion** [Azure/azure-cli#21349]
## Describe the bug

**Command Name**
`az role assignment create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'RoleAssignmentsOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 166, in create_role_assignment
    return _create_role_assignment(cmd.cli_ctx, role, object_id, resource_group_name, scope, resolve_assignee=False,
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 183, in _create_role_assignment
    assignments_client.config.subscription_id)
AttributeError: 'RoleAssignmentsOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role assignment create --role {} --assignee {} --scope {}`

## Environment Summary
```
Linux-5.15.15-1rodete1-amd64-x86_64-with-glibc2.33, Debian GNU/Linux rodete
Python 3.9.9
Installer: DEB

azure-cli 2.32.0 *

Extensions:
azure-devops 0.22.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by bion** [comment]
uninstalled and then reinstalled using [this method](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script#option-1-install-with-one-command) and it works now

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
See https://github.com/Azure/azure-cli/issues/19640

**Comment by likamrat** [comment]
Been seen the same behavior while running az login in a PowerShell session
_az login --service-principal --username $Env:spnClientID --password $Env:spnClientSecret --tenant $Env:spnTenantId_
<img width="855" alt="Snag_286cf40" src="https://user-images.githubusercontent.com/46730876/154619812-79265a96-a7c1-466a-a06b-31470640e22e.png">

**Comment by DCMattyG** [comment]
Issues in the last day or so with similar behavior:

https://github.com/Azure/azure-cli/issues/21306
https://github.com/Azure/azure-cli/issues/21331
https://github.com/Azure/azure-cli/issues/21332
https://github.com/Azure/azure-cli/issues/21333

Possibly some systemic issue with the latest Azure CLI release?

**Comment by DCMattyG** [comment]
Thanks for clarifying @jiasli!

**Comment by bion** [comment]
> See #19640
> 
> I searched for `Debian GNU/Linux rodete` but didn't get too much useful info. May I know what system this is?

@jiasli  yep:

```
$ uname -a
Linux bionj1 5.15.15-1rodete1-amd64 #1 SMP Debian 5.15.15-1rodete1 (2022-01-20) x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux rodete
Release:	rodete
Codename:	rodete

$ arch
x86_64
```

**Comment by yrro** [comment]
I have a patch for this at https://github.com/Azure/azure-cli/issues/22231#issuecomment-1113136152
