### ISSUE TITLE
Cloudshell, lost file access

### ISSUE THREAD

**Issue by SenorRagequit** [Azure/azure-cli#21342]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I created some files in the cloudshell, one xyz.ps1 and one xyz.yaml for Terraform. 
Since today, I can't open those files anymore.
![grafik](https://user-images.githubusercontent.com/50502395/154490536-7fd9c8a1-40f8-4a47-a068-a441d21799d9.png)
I created those files a while back in the cloudshell itself and used it without any problem every day - until today.

I can even open those files with "cat xyz.ps1" f.e, but it won't let me start the ps1 script.
**To Reproduce**

**Expected behavior**
Files can be started / opened

**Environment summary**
Cloudshell, Bash

**Comment by SenorRagequit** [comment]
Additional note: Switching the Cloudshell to Powershell helped, as I could start the *.ps1 script. 
But Bash won't execute it. But iirc I started the ps1 script always with Bash sofar(?)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@SenorRagequit You need the execute (x) flag for the file too. Try running the following and then run your script again

```sh
chmod +x ./deleteapim.ps1
```

**Comment by SenorRagequit** [comment]
That worked, thanks.

**Comment by PramodValavala-MSFT** [comment]
@SenorRagequit Glad we could help! Closing.
