### ISSUE TITLE
keyvault- How to add tags to existing key vault

### ISSUE THREAD

**Issue by shayco-tr** [Azure/azure-cli#21341]
Hi,
I am trying to add tags to key vault, after running this command:
az keyvault update --resource-group test-rg --name test-kv --set tags.test=test
its not adding the tags. ( this comand works on vm)
Can anyone assist?

Thanks,
Shay

**Comment by shayco-tr** [comment]
Don't work...  also I don't get any error

**Comment by evelyn-ys** [comment]
@shayco-tr After #21350 get merged and released, this should be fixed.
Do you mean that you tested with the modified code and it doesn't work?

**Comment by shayco-tr** [comment]
@evelyn-ys  I found the comand to do it.
Let me share the comand -
az resource update --set tags.test=test -g test-rg -n test --resource-type "Microsoft.KeyVault/vaults"
