### ISSUE TITLE
Found multiple accounts with the same username.

### ISSUE THREAD

**Issue by Adulis** [Azure/azure-cli#21358]
$ az deployment group validate --template-file main.bicep
Found multiple accounts with the same username. Please report to us via
 Github: https://github.com/Azure/azure-cli/issues/new

No other info was given.

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
Could you please provide specific information and debug logs to me by email? My email address is Zhou.Xing@microsoft.com

**Comment by Adulis** [comment]
Hi,
Thanks for reaching out but that is all I have to give.
Az login after the sandbox was created may have solved the problem.
I don't have the problem anymore.

Regards

**Comment by jiasli** [comment]
The multiple accounts issue is tracked by https://github.com/Azure/azure-cli/issues/20168.
