### ISSUE TITLE
Creating a non-ssl listener seems impossible

### ISSUE THREAD

**Issue by bewatts** [Azure/azure-cli#2135]
Related: 

We're trying to run a `az network application-gateway http-listener create` command

`az network application-gateway http-listener create --help` tells us that --ssl-cert is not required.  

But when we try and create one without an ssl certificate specified, we get the following: 
`Resource ...sslCertificates/None referenced by resource ...httpListeners/listener02 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.`   

There doesn't seem to be way to specify http instead of https when creating the listener.

**Comment by tjprescott** [comment]
Hi @bewatts, the reason you can't set the protocol directly is because the CLI automatically sets the protocol based on whether or not you specified an SSL cert. Which commands did you run prior?

**Comment by tjprescott** [comment]
Nevermind--I have confirmed this is a bug.

**Comment by tjprescott** [comment]
@bewatts the fix has been merged in. Please try again. Thanks for reporting this!
