### ISSUE TITLE
I never want to see this error again: the following arguments are required: _subcommand

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/azure-cli#21352]
**Is your feature request related to a problem? Please describe.**

Why does azcli not produce command help when it doesn't see the appropriate subcommand?  you can still fail with exit code 2 but also throw me a bone with showing me what I would've gotten with -h. in fact, save me from typing -h when you don't understand.

**Describe the solution you'd like**

when I enter az bicep show me what I would've seen with az bicep -h
typing -h is totally unnecessary in this situation and _subcommand isn't human readable/loveable

**Describe alternatives you've considered**

n/a

**Additional context**

**Comment by christiankuhtz** [comment]
This is not unique to the bicep command. I’ve seen it all over the place. Needs hygiene.
________________________________

**Comment by christiankuhtz** [comment]
any plans to fix this?

**Comment by jiasli** [comment]
Tracked by #19592
