### ISSUE TITLE
List the subscription for any azure resource(vm,aks,subnet.. etc) using az cli

### ISSUE THREAD

**Issue by pradeep-upadhyay** [Azure/azure-cli#21366]
I tried the _az resource list --name <aks-cluster-name>._ 
To get the details of the aks-cluster. but it returned empty.

Is there any other way to search for this? I want to find the subscription/subscriptionID and Resource-group for a particular aks-cluster-name.
 As pre-steps, I have just logged in to my Azure tenant, from which I can access all other subscriptions
I get the below output.
```
[prupadhy01@myvm001 ~/aks_script]$ az resource list --name aks-cluster-name-01
[]
[prupadhy01@myvm001 ~/aks_script]$
```
I cannot depend on searching the subscriptionID or resource group from the portal first as I have 600 Subscriptions, with average 3 rg in them

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76a8ad2-efd8-9e8a-9b2b-eebeb1e9d1d4
* Version Independent ID: 280b7ea9-eb6c-9601-464b-09bf8e0cff5d
* Content: [az resource](https://docs.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#az-resource-list)
* Content Source: [latest/docs-ref-autogen/resource.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/resource.yml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ARM

**Comment by pradeep-upadhyay** [comment]
I tried the below 
[prupadhy001@myvm002~/aks_script]$ az resource list --resource-type=Microsoft.ContainerService/managedClusters/privateLinkResources
[]


Still, the answer is nothing. Is az resource list not capable to run for the above tag?

**Comment by zhoxing-ms** [comment]
> [prupadhy01@myvm001 ~/aks_script]$ az resource list --name aks-cluster-name-01
[]

@pradeep-upadhyay Could you send me the debug log after the command is executed and tell me the information of the resource you want to query? My email address is Zhou.Xing@microsoft.com

> az resource list --resource-type=Microsoft.ContainerService/managedClusters/privateLinkResources
[]

Please note that the format of `--resource-type` parameter is `namespace/type`, so the parameter input here should be `Microsoft.ContainerService/managedClusters`.

In addition, you can also try to use `--query` parameter to filter the desired data from the results. For the specific query syntax, please refer to document  http://jmespath.org/
```pwsh
Global Arguments
   ......
    --query             : JMESPath query string. See http://jmespath.org/ for more information and
                          examples.
```

**Comment by pradeep-upadhyay** [comment]
[prupadhy01@myvm001 ~/aks_script]$ az resource list --name aks-cluster-name-01

Does this above command works only for the set subscription only. and not across all the subscriptions in a tenant

**Comment by zhoxing-ms** [comment]
> Does this above command works only for the set subscription only. and not across all the subscriptions in a tenant?

@pradeep-upadhyay Yes

**Comment by zhoxing-ms** [comment]
@adthorn Currently, REST service does not support querying all resources under a tenant. If you have the requirements, please submit a new feature request and we will transfer it to the relevant service team

**Comment by eswues** [comment]
> @adthorn Currently, REST service does not support querying all resources under a tenant. If you have the requirements, please submit a new feature request and we will transfer it to the relevant service team

and how to raise such request. I am dealing with huge infrastructure of two clients. Both around thousand subscriptions. I need to loop all subscriptions on by one to get the statistics I need, which takes ages. There should be a nicer way to get this done.

**Comment by navba-MSFT** [comment]
@pradeep-upadhyay @eswues @adthorn You could use the below shell script to achieve your requirement. This fetches all your subscriptions within your tenant which you have access to and then enumerates through each of the subscription to list the resource details. Hope this helps.

```
#! /bin/bash 
for subs in $(az account list --query [].name -o tsv); do 
    az resource list -o tsv --subscription $subs 2>/dev/null --query [].name -o tsv 2>/dev/null | grep -i $1 && echo "SUBSCRIPTION:  $subs" && exit
done
```

PS: You need to tweak the above script based on your requirement to filter based on ResourceName / resourceType.
