### ISSUE TITLE
example should be corrected

### ISSUE THREAD

**Issue by alexxiongxiong** [Azure/azure-cli#21367]
Please correct the example part https://docs.microsoft.com/en-us/cli/azure/vmss/run-command?view=azure-cli-latest#az-vmss-run-command-invoke-examples

No need " \ " in it
![image](https://user-images.githubusercontent.com/87124423/154904909-08216807-17ee-4a85-8583-00f78390019c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7554cf46-91ab-b4c2-57fe-c20702dce3a3
* Version Independent ID: 7649340e-481b-a118-2406-c971733b9ce7
* Content: [az vmss run-command](https://docs.microsoft.com/en-us/cli/azure/vmss/run-command?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vmss/run-command.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vmss/run-command.yml)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Compute
