### ISSUE TITLE
trying to import iterator from collections with python 3.10 for az ml

### ISSUE THREAD

**Issue by lsnliu** [Azure/azure-cli#21377]
**Describe the bug**
Get the following error when trying to submit a training script to the remote computer cluster via az ml 

cannot import name 'Iterator' from 'collections' (/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

![image](https://user-images.githubusercontent.com/2326746/155043598-de2bbf3f-0e4f-41e4-aed4-61a32449e185.png)

**To Reproduce**
az ml run submit-script -c train-amlcompute -e amlcompute -t run.json

**Expected behavior**
The experiment runs and run.json is generated to be used for model registration

**Environment summary**
Home-brew 3.3.16
az-cli 2.33.1
azure-cli-ml 1.37.0
python 3.10.0

**Additional context**
After testing, the -t run.json is what causes the problem.  The command runs fine if -t is not used

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@lsnliu Thanks for reaching out to us. This issue seems to be related to #20348. Could you please refer this github thread and check if that helps ? Awaiting your reply.

**Comment by lsnliu** [comment]
I installed azure cli with pip from python 3.9 and it works.  I have a work around.  This ticket is just to let you know that this bug requires attention
________________________________

**Comment by navba-MSFT** [comment]
@lsnliu Thanks for getting back and providing the feedback. Could you please share the `--debug` output while running the above command ? You can remove the sensitive information from the output before sharing. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@lsnliu I wanted to do quick follow-up to check if you had a chance to look at my above comment. Awaiting your reply.

**Comment by lsnliu** [comment]
@navba-MSFT sorry missed your last email.  Is this the chunk you want?

![image](https://user-images.githubusercontent.com/2326746/155940109-5623c125-1567-4963-b2b0-c4a165c169a5.png)

**Comment by navba-MSFT** [comment]
@lsnliu Thanks for getting back. I am discussing this internally. In the meantime, I also did some quick research on the above error, I could see a compatibility issue with Python 3.10 version. If you have a requirement to use just Python 3.10, could you please check these 2 threads [this](https://github.com/platformio/platformio-home/issues/3316) and [this](https://github.com/Kozea/pygal/issues/514) ? if that helps.

**Comment by lsnliu** [comment]
@navba-MSFT as I mentioned before, I have work arounds.  This ticket is solely to notify you that such a bug exists with 3.10.  I do not need this ticket resolved.

**Comment by navba-MSFT** [comment]
@lsnliu Thanks for your reply. I am involving the Service Team to look into this and provide an update.

@azureml-github Could you please look into this issue once you get a chance ?

**Comment by dhoeltgen** [comment]
Is there any solution to this yet?

**Comment by lsnliu** [comment]
@dhoeltgen - if you just want a work around, install any python before 3.10 then uninstall your current az cli (brew  uninstall azure-cli), then install with python39 -m pip install azure-cli.  It will be functionally the same for this purpose and it will bypass the iterator error

**Comment by navba-MSFT** [comment]
@lsnliu E2e scenarios for AzureML is not validated on python 3.10. We will update the python requirements dependencies on next sdk release to fix the documentation highlighted below in red.  More Info here[ azureml-core · PyPI](https://pypi.org/project/azureml-core/).

![image](https://user-images.githubusercontent.com/57353862/156718192-73910312-c181-45f2-9734-79b53d5f0747.png)

**Comment by dhoeltgen** [comment]
@lsnliu - thank you that worked perfectly. There wasn't even the need for a new login or configuration.

**Comment by erikadanis0312** [comment]
Hi is there a proper fix this yet? I am trying to run this on Microsoft Hosted Agents ADO pipeline and im having trouble controlling which version of python the azure-cli is picking up. I am specifying version 3.7 using the task "UsePythonVersion@0"
![image](https://user-images.githubusercontent.com/75587367/171621116-fbf01923-a021-4040-ac19-29738b0c2eb7.png)

 but in the "train model" task logs i can see its using 3.10.4 
![image](https://user-images.githubusercontent.com/75587367/171620963-ddcb080e-8c9e-4c8e-a48b-75483d21434a.png)
I am also getting the same error
![image](https://user-images.githubusercontent.com/75587367/171621056-33971aa8-bc81-41c0-a645-1b4402913f7f.png)

**Comment by arsenerei** [comment]
@erikadanis0312 I used `UsePythonVersion@0` and had to remove the pre-installed Azure CLI and install a new one with:

```shell
# remove buggy azure-cli
sudo apt-get remove -y azure-cli

# upgrade necessary tools
python -m pip install --upgrade pip setuptools wheel

# install working azure-cli
python -m pip install azure-cli
```

**Comment by amy-chue** [comment]
> 

Thank you! Works like a magic!!

**Comment by amy-chue** [comment]
> @erikadanis0312 I used `UsePythonVersion@0` and had to remove the pre-installed Azure CLI and install a new one with:
> 
> ```shell
> # remove buggy azure-cli
> sudo apt-get remove -y azure-cli
> 
> # upgrade necessary tools
> python -m pip install --upgrade pip setuptools wheel
> 
> # install working azure-cli
> python -m pip install azure-cli
> ```

Thank you! Works like a magic!!
