### ISSUE TITLE
az functionapp deployment source config-zip fails in obscure way when Code Function runtime mismatched

### ISSUE THREAD

**Issue by alexhudson** [Azure/azure-cli#21388]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When deploying a new code function written in python and built as a local Zip, I could not convince az-cli to deploy it:

```
> az functionapp deployment source config-zip --build-remote -g rg -n newfunc --src func-latest.zip
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
Configuring default logging for the app, if not already enabled
Zip deployment failed. {'id': '0f430ea955a544a5a57940b41xxxxxx', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2022-02-22T14:20:56.1147382Z', 'start_time': '2022-02-22T14:20:57.1494739Z', 'end_time': '2022-02-22T14:21:02.6971019Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://newfunc.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://newfunc.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'newfunc'}. Please run the command az webapp log deployment show -n newfunc -g rg
>  az webapp log deployment show -n newfunc -g rg
Command group 'webapp log deployment' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
[]
```

None of the log options suggested helped, and there was no useful output. However, when I then went to deploy directly (without zip) I got something useful:

```
> func azure functionapp publish newfunc
Your Azure Function App has 'FUNCTIONS_WORKER_RUNTIME' set to 'node' while your local project is set to 'python'.
You can pass --force to update your Azure app with 'python' as a 'FUNCTIONS_WORKER_RUNTIME'
```

**Expected behavior**

It would be great to get that same error back somehow, or figure out where it would appear. Had I not tried "functionapp publish" I would still be stuck!

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@alexhudson Thanks for reaching out to us. I tried to run the same below command using the Function App [python sample](https://github.com/yokawasa/azure-functions-python-samples) and I was able to successfully deploy to function app.

>az functionapp deployment source config-zip --build-remote -g rg -n newfunc --src func-latest.zip

I was using the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) of Azure CLI in my box. Could you please try the same at your end and check if you still same the same issue ? Awaiting your reply.

**Comment by panchagnula** [comment]
@alexhudson thanks for the feedback - does the command webapp log deployment (that the zip deploy offered at the end of the error message)  offer any guidance as to cause of failure here?

**Comment by navba-MSFT** [comment]
@alexhudson Hope you had a chance to look at the above comment. Awaiting your reply.

**Comment by mathiasmaerker** [comment]
I have the same issue, but only when trying to `--build-remote` with private packages from GitHub, even thou I provide a `.npmrc` with the proper tokens and uris. I am using the latest version of the Azure CLI

**Comment by panchagnula** [comment]
> I have the same issue, but only when trying to `--build-remote` with private packages from GitHub, even thou I provide a `.npmrc` with the proper tokens and uris. I am using the latest version of the Azure CLI

@mathiasmaerker thanks for reporting as well. For CLI we do plan to add some pre-validations (like runtime check) to improve the experience. Regarding the  build using private GitHub packages I will pass this info to the function apps runtime team.

**Comment by Francisco-Gamino** [comment]
Hello @gzuber / @amamounelsayed -- Could you please help with this Functions deployment inquiry? Thank you.
