### ISSUE TITLE
Cannot deploy Azure Machine Learning online endpoint using Cli

### ISSUE THREAD

**Issue by tobys-playground** [Azure/azure-cli#21387]
I was trying to create an endpoint and deployment in Cloud Shell and Azure Pipelines using the commands from this documentation

https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-mlflow-models-online-endpoints?tabs=endpoint%2Cstudio

My commands are :
`
az ml online-endpoint create  --resource-group $(databricks.resourcegroup) --workspace-name $(databricks.workspace.name) --file create-endpoint.yml`

`
az ml online-deployment create --name deployment --endpoint model-endpoint -f endpoint-config.yml --all-traffic`

However, I get the errors:

`'online-endpoint' is misspelled or not recognized by the system.`

`'online-deployment' is misspelled or not recognized by the system.`

I am using the following versions:

```
{
  "azure-cli": "2.33.1",
  "azure-cli-core": "2.33.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5",
    "azure-cli-ml": "1.37.0",
    "ssh": "1.0.0"
  }

```
Is this a bug?

**Comment by migdaepp** [comment]
Az ml and azi-cli-ml https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli is a conflicting extension -- see [this doc](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli ) to troubleshoot

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@migdaepp Please look into the above suggestions.  Additionally, you could try to upgrade the ML extension to the latest version by using `az extension update -n ml`.
