### ISSUE TITLE
az ml : 'ml' is misspelled or not recognized by the system

### ISSUE THREAD

**Issue by migdaepp** [Azure/azure-cli#21390]
I'm trying to update a model that was deployed with az ml. 
When I run any command starting with `az ml` (e.g. `az ml -h`) I now get the error:

> Error loading command module 'network': No module named 'azure.core.rest'
cannot import name 'ARMChallengeAuthenticationPolicy'
'ml' is misspelled or not recognized by the system.

> Examples from AI knowledge base:
az extension add --name anextension
Add extension by name

> az extension list-available
List all publicly available extensions

> https://docs.microsoft.com/en-US/cli/azure/extension#az_extension_add

I am using the following versions:
`az version`
>{
  "azure-cli": "2.33.1",
  "azure-cli-core": "2.33.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ml": "2.1.2"
  }
}

`az extension list`
> [
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "ml",
    "path": "/opt/az/extensions/ml",
    "preview": true,
    "version": "2.1.2"
  }
]

**Comment by yonzhan** [comment]
route to CXP team

**Comment by harneetvirk** [comment]
This seems like an issue with the dependency of azure-core in azure-cli that does not contains azure.core.rest.  azure.core.rest is the new public simple HTTP library in azure.core introduced in azure-core 1.20.0
A similar issue (No module named 'azure.core.rest') has been reported here: https://github.com/Azure/azure-cli-extensions/issues/4462

**Comment by adba-msft** [comment]
Upgrading the Az CLI fixed the issue.

**Comment by adba-msft** [comment]
[Upgrading the Az CLI](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli) fixed this issue.

[](url)

PowerShell output:

```powershell
PS C:\Users\adba> az --version
azure-cli                         2.37.0

core                              2.37.0
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0
ml                                 2.5.0

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\adba\.azure\cliextensions'

Python (Windows) 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 22:57:10) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
PS C:\Users\user> az ml -h

Group
    az ml : Manage Azure Machine Learning resources with the Azure CLI ML extension v2.
        Install Azure CLI ML extension v2
        https://docs.microsoft.com/azure/machine-learning/how-to-configure-cli.

Subgroups:
    batch-deployment               : Manage Azure ML batch deployments.
    batch-endpoint                 : Manage Azure ML batch endpoints.
    component                      : Manage Azure ML components.
    compute                        : Manage Azure ML compute resources.
    connection           [Preview] : Manage Azure ML workspace connection.
    data                           : Manage Azure ML data assets.
    dataset [Deprecated] [Preview] : Manage Azure ML dataset assets.
    datastore                      : Manage Azure ML datastores.
    environment                    : Manage Azure ML environments.
    job                            : Manage Azure ML jobs.
    model                          : Manage Azure ML models.
    online-deployment              : Manage Azure ML online deployments.
    online-endpoint                : Manage Azure ML online endpoints.
    workspace                      : Manage Azure ML workspaces.

To search AI knowledge base for examples, use: az find "az ml"

Please let us know how we are doing: https://aka.ms/azureclihats
PS C:\Users\user>
```

**Comment by natasha-savic-msft** [comment]
I had a similar issue and had to switch python to a higher version via `conda activate azureml_py310_sdkv2` . Then, re-install the az ml v2 sdk via: 
`az extension remove -n ml`
`az extension add -n ml`

And finally check with: `az ml -h`

**Comment by maciejskorski** [comment]
> The error can be resolved by installing the extension using the following command:
> az extension add -n azure-cli-ml

Is it recommended to use `azure-cli-ml`?

**************************************************************************************************************
* WARNING:                                                                                                   *
* Extension "azure-cli-ml" cannot be used along with extension "ml". This may result in unexpected behaviour.*
* Please remove azure-cli-ml extension by running  "az extension remove -n azure-cli-ml                      *
**************************************************************************************************************

**Comment by rui-ren** [comment]
For Linux users, you can use blow command to install `az ml`

```
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash 
az extension add -n ml -y
```

**Comment by wenqian157** [comment]
still same issue. in the end I used az 2.55.0, remove ml v1 and ml v2:
 ``az extension remove -n azure-cli-ml``
 ``az extension remove -n ml``
and reinstall ml v1:
``az extension  add -n ml``
it works for me. ml version 2.22.0

**Comment by saikrishna-1996** [comment]
It is not working for me. 
```
az extension add -n ml

Default enabled including preview versions for extension installation now. Disabled in May 2024. Use '--allow-preview true' to enable it specifically if needed. Use '--allow-preview false' to install stable version only. 
An error occurred. Pip failed with status code 1. Use --debug for more information.
```

**Comment by Cameron-oos** [comment]
I have the same error. When I use:  az extension add --name ml

Error: An error occurred. Pip failed with status code 1. Use --debug for more information. 

az version 2.59.0 

Can't remove it or anything.
