### ISSUE TITLE
az cli equivalent of Get-AzureRmVMExtension

### ISSUE THREAD

**Issue by simratsatia** [Azure/azure-cli#21393]
Aim: Get the output of the script provisioned using 'Custom Script Extension' using azure-cli

Approach: I came across the answer [here](https://stackoverflow.com/questions/38152873/how-can-i-get-the-output-of-a-customscriptextenstion-when-using-azure-resource-m) that uses "Get-AzureRmVMExtension" with "status" field

Question: What is the azure-cli equivalent of Get-AzureRmVMExtension that allows us to get the output of a script provisioned using Custom Script Extension

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ebbeb5f-6ab6-3fb3-c969-5d935e60f251
* Version Independent ID: 9d4169c9-f5b5-512a-8061-2234d6dec1eb
* Content: [az vm extension](https://docs.microsoft.com/en-us/cli/azure/vm/extension?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm/extension.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm/extension.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@simratsatia Could you please try `az vm extension show`?

**Comment by simratsatia** [comment]
# az vm extension show -g <rg-name> --vm-name rhel79-2 -n customScript
{
  "autoUpgradeMinorVersion": true,
  "enableAutomaticUpgrade": null,
  "forceUpdateTag": null,
  "id": "/subscriptions/18938738-9a46-4644-90d4-b899dee5c934/resourceGroups/ahbv3-cloudtest-testvms-rg/providers/Microsoft.Compute/virtualMachines/rhel79-2/extensions/customScript",
  "instanceView": null,
  "location": "eastus",
  "name": "customScript",
  "protectedSettings": null,
  "provisioningState": "Succeeded",
  "publisher": "Microsoft.Azure.Extensions",
  "resourceGroup": "ahbv3-cloudtest-testvms-rg",
  "settings": null,
  "suppressFailures": null,
  "tags": null,
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "typeHandlerVersion": "2.1",
  "typePropertiesType": "customScript"
}

Protected Settings during execution:
{
    "commandToExecute": "echo 'hello world'"
}

Problem: I don't see the output of the command I ran ie 'hello world'

**Comment by simratsatia** [comment]
Attaching output of CustomScript Extension from Azure Portal:
![image](https://user-images.githubusercontent.com/28175383/155281835-cc188c69-0232-44fb-b200-024fc8a1608b.png)

I want to retrieve the stdout/stderr of the status message

**Comment by zhoxing-ms** [comment]
@simratsatia Could you please show me the results of `Get-AzureRmVMExtension` and the debug log (I‘d like to see what the requested REST URL is) ? So I can know more about the effect you want

**Comment by simratsatia** [comment]
##OUTPUT USING Get-AzVMExtension

$output = Get-AzVMExtension -ResourceGroupName ahbv3-cloudtest-testvms-rg -VMName rhel79-2 -Name customScript -Status

PS C:\Users\sisatia> $output.Statuses.Message
Enable succeeded:
[stdout]
hello world

[stderr]

##Debug Output
HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/18938738-9a46-4644-90d4-b899dee5c934/resourceGroups/ahbv3-cloudtest-testvms-rg/providers/Microsoft.Compute/virtualMachines/rhel79-2/extensions/customScript?$expand=i
nstanceView&api-version=2019-03-01

Headers:
x-ms-client-request-id        : <client-id>
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/LowCostGet3Min;3996,Microsoft.Compute/LowCostGet30Min;31986
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 28f2b452-1525-4459-bb53-c8cf00099b5e
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11990
x-ms-correlation-request-id   : 73a0c35d-65b0-4f07-ae71-2d421706fbde
x-ms-routing-request-id       : SOUTHINDIA:20220223T132112Z:73a0c35d-65b0-4f07-ae71-2d421706fbde
X-Content-Type-Options        : nosniff
Date                          : Wed, 23 Feb 2022 13:21:11 GMT

Body:
{
  "name": "customScript",
  "id": "/subscriptions/18938738-9a46-4644-90d4-b899dee5c934/resourceGroups/ahbv3-cloudtest-testvms-rg/providers/Microsoft.Compute/virtualMachines/rhel79-2/extensions/customScript",
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "location": "eastus",
  "properties": {
    "autoUpgradeMinorVersion": true,
    "provisioningState": "Succeeded",
    "instanceView": {
      "name": "customScript",
      "type": "Microsoft.Azure.Extensions.customScript",
      "typeHandlerVersion": "2.1.6",
      "statuses": [
        {
          "code": "ProvisioningState/succeeded",
          "level": "Info",
          "displayStatus": "Provisioning succeeded",
          "message": "Enable succeeded: \n[stdout]\nhello world\n\n[stderr]\n"
        }
      ]
    },
    "publisher": "Microsoft.Azure.Extensions",
    "type": "customScript",
    "typeHandlerVersion": "2.1"
  }
}

DEBUG: AzureQoSEvent: CommandName - Get-AzVMExtension; IsSuccess - True; Duration - 00:00:01.2339625; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 6:51:13 PM - GetAzureVMExtensionCommand end processing.
DEBUG: 6:51:13 PM - GetAzureVMExtensionCommand end processing.

**Comment by simratsatia** [comment]
So interestingly, I see the '--expand instanceView' doing the trick as follows:

az vm extension show -g ahbv3-cloudtest-testvms-rg --vm-name rhel79-2 -n customScript --expand instanceView

Argument 'expand' has been deprecated and will be removed in version '3.0.0'.
{
  "autoUpgradeMinorVersion": true,
  "enableAutomaticUpgrade": null,
  "forceUpdateTag": null,
  "id": "/subscriptions/18938738-9a46-4644-90d4-b899dee5c934/resourceGroups/ahbv3-cloudtest-testvms-rg/providers/Microsoft.Compute/virtualMachines/rhel79-2/extensions/customScript",
  "instanceView": {
    "name": "customScript",
    "statuses": [
      {
        "code": "ProvisioningState/succeeded",
        "displayStatus": "Provisioning succeeded",
        "level": "Info",
        "message": "Enable succeeded: \n[stdout]\nhello world\n\n[stderr]\n",
        "time": null
      }
    ],
    "substatuses": null,
    "type": "Microsoft.Azure.Extensions.customScript",
    "typeHandlerVersion": "2.1.6"
  },
  "location": "eastus",
  "name": "customScript",
  "protectedSettings": null,
  "provisioningState": "Succeeded",
  "publisher": "Microsoft.Azure.Extensions",
  "resourceGroup": "ahbv3-cloudtest-testvms-rg",
  "settings": null,
  "suppressFailures": null,
  "tags": null,
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "typeHandlerVersion": "2.1",
  "typePropertiesType": "customScript"
}

Question: Since 'expand' is going to be deprecated in version 3.0.0, what is the recommended way then?

**Comment by zhoxing-ms** [comment]
Because the meaning of parameter `--expand`  is not clear enough, it was deprecated in PR #7868. We will develop a more explicit parameter `--instance-view` to replace it in the next sprint (04-05), do you think it is acceptable?

**Comment by simratsatia** [comment]
Yes, that would be good. Thanks!
