### ISSUE TITLE
[StorageMover] public preview

### ISSUE THREAD

**Issue by blueww** [Azure/azure-cli#21404]
**Resource Provider**

Microsoft.StorageMover

**Description of Feature or Work Requested**

https://microsoft.sharepoint.com/:w:/r/teams/AzureStorageMigration/_layouts/15/Doc.aspx?sourcedoc=%7B34B68371-4359-4821-A644-2234678AE055%7D&file=Azure%20Data%20Mover%20Resource%20Provider%20Design%20and%20Use%20Cases.docx&action=default&mobileredirect=true&share=IQFxg7Y0WUMhSKZEIjRniuBVAQENHVNHc6Uznb-8w1epIEM

**Minimum API Version Required**

TBD

**Swagger Link**

[Private swagger PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/5203
Pending for public swagger](https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSMaster/specification/storagemover/resource-manager/Microsoft.StorageMover/preview/2022-07-01-preview/storagemover.json)
Still in private swagger repo. 
Per agreement with feature team, will be merged to public repo at least 2-3 weeks before PSH/CLI release for public preview.
Currently target public preview on 7/8. PSH/CLI release can target 7/5.

**Target Date**

7/5

**Comment by yonzhan** [comment]
storage

**Comment by kairu-ms** [comment]
@blueww I think there are some issues in swaggers. 'x-ms-long-running-operation' property should not defined in response. https://github.com/Azure/azure-rest-api-specs-pr/blob/582f5cb3c6324608bbc520742c857de785d5dd3c/specification/storagemover/resource-manager/Microsoft.StorageMover/preview/2022-07-01-preview/storagemover.json#L319

**Comment by blueww** [comment]
@kairu-ms 

Thanks for raising this swagger issue!
I have written a mail to feature team for this issue and include you
BTW, does this issue blocks CLI code generation?

**Comment by calvinhzy** [comment]
Here is the new package with the latest swagger changes. 
https://zhiyihuangsa.blob.core.windows.net/sharing/storage_mover-0.1.1-py3-none-any.whl

**Comment by calvinhzy** [comment]
CLI package is ready for this feature, feel free to follow below steps for test:

install/update cli:
pip install azure-cli -U

install Storage-Mover extension
az extension add -n storage-mover

try new commands:
az storage-mover -h to see all the commands and you can use -h for the commands to see their required arguments
az storage-mover create -h
az storage-mover endpoint create-for-storage-container -h
