### ISSUE TITLE
CLI to attach multiple disks to a VM in one single operation

### ISSUE THREAD

**Issue by ravkash** [Azure/azure-cli#21413]
**Is your feature request related to a problem? Please describe.**
az config set core.disable_concurrent_ids=True will result in Azure CLI sequentially attaching the disks and not attaching them in one single operation (related to https://github.com/Azure/azure-cli/issues/15765) which takes a long time

**Describe the solution you'd like**

change the behavior of Azure CLI to add all disks with one API call

 
**Additional context**
disk attach time using CLI vs API:

![image](https://user-images.githubusercontent.com/26795040/155353593-391531f8-5feb-4323-b8a8-906fb1007d8f.png)

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
This solution is feasible, but we can only support attaching multiple disks by one API call through another parameter (such as `--disk`). Because `--ids` parameter is a global parameter, each id in `--ids` will be processed by independent API call, which is a common logic in CLI core.
