### ISSUE TITLE
az storage blob sync's deletion behavior can lead to unexpected data loss

### ISSUE THREAD

**Issue by jayqi** [Azure/azure-cli#21414]
**Is your feature request related to a problem? Please describe.**

Currently, the `az storage blob sync` command will delete blobs at the destination that are not present in the source. This is hardcoded into the command, with no documentation of its behavior or an option to change it. Additionally, this is inconsistent with the default behavior of other prominent tools for Azure as well as other cloud providers' storage services, including `azcopy`, which [include a flag to enable deleting but do not do so by default](https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-sync#options). 

In fact, this command is implemented in `azure-cli` by wrapping `azcopy sync` but then overriding `azcopy`'s default. Relevant source code: 

https://github.com/Azure/azure-cli/blob/92c50bc2f847907b0628dfc3bd885bac05b96c36/src/azure-cli/azure/cli/command_modules/storage/operations/azcopy.py#L84-L87 

This is a risky design that can lead to unexpected deletion by users and result in data loss. (This happened to me.)

**Describe the solution you'd like**

1. Add a `--delete-destination ` to match the functionality of `azcopy sync`.
2. Have that flag default to false.

**Comment by yonzhan** [comment]
storage
