### ISSUE TITLE
Publish Community Gallery to official CLI

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#21423]
**Resource Provider**

Azure.Compute

**Description of Feature or Work Requested**

Previously we had this request:
https://github.com/Azure/azure-cli/issues/19882

And all commands have been published to cli extension.
We will do public preview at the end of next month and we hope to publish all the commands into official CLI.

**Minimum API Version Required**

2021_10_01 for community gallery publishing
2022_01_03 for community gallery list/get

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/17548

For community gallery list/get, the swagger has not been merged: https://github.com/Azure/azure-rest-api-specs/pull/17985

**Target Date**

05/31/2022

**Comment by yonzhan** [comment]
Compute

**Comment by PARADISSEEKR** [comment]
Hi @kangsun-ctrl, Could you please provide a swagger link for python.

**Comment by zhoxing-ms** [comment]
Replaced by #22222
