### ISSUE TITLE
az apim api import --api-revision bug

### ISSUE THREAD

**Issue by barneschism** [Azure/azure-cli#21422]
When importing a new api using `az apim api import`, the newly imported api always has a revision number of 1, regardless of the value of the parameter passed to --api-revision.  

This issue is not present when using --api-id to import an api to an existing api as a new revision.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f27e34-66e0-1d08-f734-26ce29c56c36
* Version Independent ID: d1a421eb-807c-c0bd-cee3-a5aed7335625
* Content: [az apim api](https://docs.microsoft.com/en-us/cli/azure/apim/api?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/apim/api.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/apim/api.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@barneschism Apologies for the delay, we are looking into it.
