### ISSUE TITLE
why is the new version of ML not allowed to set location when creating compute?

### ISSUE THREAD

**Issue by duclinh84bk** [Azure/azure-cli#21429]
why is the new version of ML not allowed to set location when creating compute?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71c25404-a256-62b2-3ac8-dd699fc677ba
* Version Independent ID: 5f3dccba-b2ee-224b-9e84-80ba2bbde641
* Content: [az ml compute](https://docs.microsoft.com/en-us/cli/azure/ml/compute?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/compute.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ml/compute.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@duclinh84bk An [Azure ML Workspace](https://docs.microsoft.com/en-us/azure/machine-learning/concept-workspace) is the top-level resource, which is deployed to the location of your choice, containing all required resources. You create your compute resources in the workspace, which are deployed in the same resource as the workspace.

**Comment by duclinh84bk** [comment]
Thank you for your response!

I've known this, but it is not convenient. We need to create
many workspaces.
When I use REST API, I can deploy any location in the same workspace.


Vào Th 5, 24 thg 2, 2022 vào lúc 12:09 Pramod Valavala <
***@***.***> đã viết:

**Comment by luigiw** [comment]
@duclinh84bk , you can specify location in the compute YAML file. Please see reference here. https://docs.microsoft.com/en-us/azure/machine-learning/reference-yaml-compute-aml

**Comment by duclinh84bk** [comment]
> @duclinh84bk , you can specify location in the compute YAML file. Please see reference here. https://docs.microsoft.com/en-us/azure/machine-learning/reference-yaml-compute-aml
 
Hi Hanchi Wang,

I've tried to use YAML to specify a location but this did not affect the result. The location after creation still folow the location of the workspace!
