### ISSUE TITLE
Query inbound NAT rule port mapping on Azure Load Balancer

### ISSUE THREAD

**Issue by irenehua** [Azure/azure-cli#21426]
Customer should be able to query port mapping after creating inbound NAT rule for the entire backend pool.
Upon creation of inbound NAT rule for backend pool, LB will create port mappings for individual Virtual Machine of the backend pool. Customer can use the assigned frontend port to access a specific Virtual Machine in the backend. Thus they should be able to query the port mappings of the backend pool.

Spec: https://microsoft-my.sharepoint.com/:w:/p/irrogozh/ER6aq40IrklPsTfo-pYT6QAB17LfUz2YKnjiiijGXpRx2Q?wdOrigin=TEAMS-ELECTRON.p2p.bim&wdExp=TEAMS-CONTROL&wdhostclicktime=1632766390475

Swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2021-03-01/loadBalancer.json

**Comment by yonzhan** [comment]
network

**Comment by necusjz** [comment]
@irenehua, I'm aware that "queryInboundNatRulePortMapping" (mentioned in the doc) is not shown in the above swagger link. But shown in ".../stable/2021-05-01/...", is it the correct link?

**Comment by irenehua** [comment]
@necusjz you are correct. Let's use the latest swagger which is 2021-05-01. Thanks for catching this!

**Comment by irenehua** [comment]
@necusjz could you point me to the documentation that hosts the new commands for this ask? I didn't find anything here maybe I'm missing something: https://docs.microsoft.com/en-us/cli/azure/network/lb/address-pool?view=azure-cli-latest

**Comment by necusjz** [comment]
> @necusjz could you point me to the documentation that hosts the new commands for this ask? I didn't find anything here maybe I'm missing something: https://docs.microsoft.com/en-us/cli/azure/network/lb/address-pool?view=azure-cli-latest

FYI: https://docs.microsoft.com/en-us/cli/azure/network/lb?view=azure-cli-latest#az-network-lb-list-mapping
