### ISSUE TITLE
Permission Denied Error

### ISSUE THREAD

**Issue by malikmtayyab** [Azure/azure-cli#21433]
I am trying to deploy my bot via ARM template but in the template file it gives me **PERMISSION DENIED** error in the path, I am giving it an absolute path and the command I am using is:
az deployment group create --resource-group "Resource group" --template-file "Template Path" --parameters appId="My appId" appType="UserAssignedMSI" tenantId="My tenantId" existingUserAssignedMSIName="Identity Name" existingUserAssignedMSIResourceGroupName="Resource Group Name" botId="My botId" newWebAppName="Web App Name" existingAppServicePlan="My app service plan" appServicePlanLocation="West US" --name "The deployment Name"
![Capture](https://user-images.githubusercontent.com/97073232/155484398-1bf262cf-905c-47d5-a489-1dd6af62cc4a.PNG)

**Comment by yonzhan** [comment]
ARM
