### ISSUE TITLE
Cha'che'

### ISSUE THREAD

**Issue by Aminadad27** [Azure/azure-cli#21431]
![5b94ce351c53a1c6a74cc88695131dd574ff8cba0de486dfd7799f93f53cc0ef.0.gif](https://user-images.githubusercontent.com/82472953/155480681-492492bd-bcd0-460a-ab73-5dfebacf1919.gif)h

**Comment by jiasli** [comment]
Spam. Similar to https://github.com/python/cpython/pull/31140.
