### ISSUE TITLE
unexpected error running az aks scale

### ISSUE THREAD

**Issue by Segflow** [Azure/azure-cli#21434]
## Describe the bug

**Command Name**
`az aks scale`

**Errors:**
```
'UserAssigned' is not valid value for enum <enum 'ResourceIdentityType'>
Traceback (most recent call last):
python3/dist-packages/msrest/serialization.py, ln 910, in serialize_enum
    enum_obj(result)
usr/lib/python3.8/enum.py, ln 339, in __call__
    return cls.__new__(cls, value)
usr/lib/python3.8/enum.py, ln 663, in __new__
    raise ve_exc
ValueError: 'UserAssigned' is not a valid ResourceIdentityType

...

python3/dist-packages/msrest/serialization.py, ln 917, in serialize_enum
    raise SerializationError(error.format(attr, enum_obj))
msrest.exceptions.SerializationError: 'UserAssigned' is not valid value for enum <enum 'ResourceIdentityType'>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks scale --resource-group {} --name {} --node-count {} --nodepool-name {} --subscription {}`

## Expected Behavior

I expected the nodepool to scale up correctly. 

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
Python 3.8.10
Shell: zsh

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@Segflow Thanks for reaching out to us. Please update your [python libraries ](https://www.python.org/downloads/)and use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) of the AzCLI and check if you still see the issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Segflow I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Segflow Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
