### ISSUE TITLE
Warning text output to error stream (2) instead of warning stream (3)

### ISSUE THREAD

**Issue by spricesoft-samuel** [Azure/azure-cli#21435]
"az functionapp create" and "az webapp create" both send "Warning:" messages to the error stream. 
This causes deployments to fail when running in a Parallel context.

Example warning messages sent to error stream:
az functionapp create:
WARNING: Application Insights "<name>" was created for this Function App. You can visit <URL>/overview to view your Application Insights component

az webapp create:
WARNING: Webapp '<name>' already exists. The command will use the existing app's settings.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by spricesoft-samuel** [comment]
Actually I think this is a general issue with Powershell " ForEach-Object -Parallel " redirecting the warning stream to error. I will close this bug, investigate further and maybe post something in the powershell issues if needed.
