### ISSUE TITLE
Contradicting example for az webapp deploy, parameter --async

### ISSUE THREAD

**Issue by armaciej** [Azure/azure-cli#21439]
For the command `az webapp deploy`, in the code template it says: `... --async {true, false}`.

However, in the example it says `... --async IsAsync`.

Which of those is true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-deploy)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@armaciej Thanks for catching that! We have worked up a PR to address this.

**Comment by yonzhan** [comment]
route to CXP team
