### ISSUE TITLE
Updation of CLI for AzureStackHCI

### ISSUE THREAD

**Issue by priyjain358** [Azure/azure-cli#21432]
**Resource Provider**
 AzureStackHCI

**Description of Feature or Work Requested**

We want to update our CLI based on the swagger. Currently, we have the cli commands for clusters resource, we would like to add for our other resources: arcsettings, extensions as well. 

Extension: https://github.com/Azure/azure-cli-extensions/tree/main/src/stack-hci

**Minimum API Version Required**
 2021-09-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI/stable/2021-09-01

**Target Date**

31st March, 2022

**Comment by yonzhan** [comment]
AzureStackHCI

**Comment by priyjain358** [comment]
Hi, is there any update on this?

**Comment by necusjz** [comment]
@priyjain358, I'm working on this and hopefully next week will deliver. : )
