### ISSUE TITLE
Image List shows an empty list of images

### ISSUE THREAD

**Issue by snowsky** [Azure/azure-cli#21436]
## Describe the bug

**Command Name**
`az image list --debug --verbose`

**Errors:**
```
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x101d5e320>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/profiles/_shared.py", line 600, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.compute.v2021_04_01.models' has no attribute 'DiskStorageAccountTypes,'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/profiles/_shared.py", line 600, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.compute.v2021_07_01.models' has no attribute 'EncryptionType'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.33.1/libexec/lib/python3.10/site-packages/azure/cli/core/profiles/_shared.py", line 600, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.compute.v2021_07_01.models' has no attribute 'EncryptionType'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az image list --debug --verbose`
- show an empty list of images (it should show one existing image)

## Expected Behavior
Should show one existing image

## Environment Summary
```
macOS-12.2.1-x86_64-i386-64bit, Darwin 21.3.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.33.1

Extensions:
azure-iot 0.13.0
storage-blob-preview 0.6.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by snowsky** [comment]
Not sure if this is related to throttling issue, I can see the response header `'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/HighCostGetImages3Min;79,Microsoft.Compute/HighCostGetImages30Min;399'` in a working request, but not in the response of an empty image list.

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@snowsky Could you please send the debug log to me by email, my email address is Zhou.Xing@microsoft.com, thanks

**Comment by snowsky** [comment]
@zhoxing-ms sent, thanks :)

**Comment by snowsky** [comment]
It happened after a new image was pushed to Azure and after a certain period (sometimes an hour, or half a day), the image can be seen in the outputs of `az image list`

**Comment by zhoxing-ms** [comment]
This should be a service related issue. For the same REST request
```
GET https://management.azure.com/subscriptions/4bdb63d7-b6a0-47f8-b0bf-a78afa5ad75e/providers/Microsoft.Compute/images?api-version=2021-07-01
```

One request returned data: **'x-ms-correlation-request-id': 'c6d303a1-5c58-47d2-965a-486f0f486635'**

Another request did not return data: **'x-ms-correlation-request-id': '196cb60e-3d5a-414d-85b1-e698cb121b2f'**

**Comment by snowsky** [comment]
Thanks @zhoxing-ms, how can we inform service team?

**Comment by zhoxing-ms** [comment]
Don't worry. After we label this issue as `CXP Attention`, our CXP team will route the issue to service team. If this issue does not receive a timely reply, please tell me again and I will find the relevant team

**Comment by snowsky** [comment]
Awesome, thanks @zhoxing-ms

**Comment by snowsky** [comment]
Hi @zhoxing-ms, just touching base to know if there is any update from service team. Thanks :)

**Comment by zhoxing-ms** [comment]
Here is a question related to the REST of image list [comment](https://github.com/Azure/azure-cli/issues/21436#issuecomment-1054002539) @grizzlytheodore Do you know who can help us investigate this issue?

**Comment by navba-MSFT** [comment]
@snowsky Apologies for the late reply. I tried to run the same command and it worked just fine for me. 

>C:\>az image list --resource-group shashs-bastion-idLab
[
  {
    "extendedLocation": null,
    "hyperVGeneration": "V1",
    "id": "/subscriptions/XXXXXXXXXXXXX/resourceGroups/XXXXXXXXXXXXX/providers/Microsoft.Compute/XXXXXXXXXXXX",
    "location": "westus2",
    "name": "shbhost",
    "provisioningState": "Succeeded",
    "resourceGroup": "XXXXXXXX",
    "sourceVirtualMachine": {
      "id": "/subscriptions/XXXXXXXXXXXXX/resourceGroups/XXXXXXXXXXXXX/providers/Microsoft.Compute/XXXXXXXXXXXXX",
      "resourceGroup": "XXXXXXX"
    },
    "storageProfile": {
      "dataDisks": [],
      "osDisk": {
        "blobUri": null,
        "caching": "ReadWrite",
        "diskEncryptionSet": null,
        "diskSizeGb": 127,
        "managedDisk": {
          "id": "/subscriptions/XXXXXXXXXXXXX/resourceGroups/XXXXXXXXXXXXX/providers/Microsoft.Compute/disks/XXXXXXXXXXXXX9708d164c816134e80c",
          "resourceGroup": "XXXXXX"
        },
        "osState": "Generalized",
        "osType": "Windows",
        "snapshot": null,
        "storageAccountType": "StandardSSD_LRS"
      },
      "zoneResilient": null
    },
    "tags": {},
    "type": "Microsoft.Compute/images"
  }
]

Sharing my Az CLI version if that helps.
>C:\>az version
{
  "azure-cli": "2.35.0",
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.60",
    "application-insights": "0.1.16",
    "arcdata": "1.3.1",
    "attestation": "0.2.0",
    "azure-iot": "0.14.0",
    "connectedk8s": "1.2.8",
    "db-up": "0.2.7",
    "kusto": "0.5.0",
    "ssh": "1.1.1"
  }
}

Could you please let me know if you are still facing the same issue ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@snowsky I wanted to do quick follow-up to check if you had a chance to look at my above comment. This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@snowsky We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by snowsky** [comment]
@navba-MSFT sorry, just saw the replies. I don't know if I can reproduce the issue. Will keep you posted :)
