### ISSUE TITLE
Redis V6 doesnt allow scaling down from c1 to c0, but v4 did

### ISSUE THREAD

**Issue by bruno-salapic** [Azure/azure-cli#21447]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When i was working with azure redis v4 i was able to scale down from a c1 to a c0 on the standard tier, but now with redis v6 i cannot perform that very same action.
**To Reproduce**

create azure v4 scale down from c1 to c0,
create azure v6 scale down from c1 to c0, fails

**Expected behavior**

 to be able to scale down to c0

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@[bruno-salapic](https://github.com/bruno-salapic)  Apologies for the late reply. Thanks for reaching out to us. In both v4 and v6 version of Azure Redis, cache, scaling down to C0 (250 MB) size is unsupported. The same has been documented in our article. Refer [this](https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-scale#operations-that-arent-supported). 

&gt;You can't scale from a larger size down to the **C0 (250 MB)** size. However, you can scale down to any other size within the same pricing tier. For example, you can scale down from C5 Standard to C1 Standard.

Hope this helps. Please let me know if you have any queries on this.

**Comment by navba-MSFT** [comment]
@bruno-salapic I wanted to do quick follow-up to check if you had a chance to look at my above comment.  Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@bruno-salapic We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
