### ISSUE TITLE
az aks (...) --enable-managed-identity creates a user-assigned managed identity

### ISSUE THREAD

**Issue by FlorentATo** [Azure/azure-cli#21441]
According to this article, https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest using the argument `--enable-managed-identity` creates a system-assigned managed identity for the control plane (i.e. nodes):

Quotes:
> Create a kubernetes cluster which enables managed identity.
> az aks create -g MyResourceGroup -n MyManagedCluster --enable-managed-identity

Unclear; the type of identity should be specified i.e. user-assigned

> Update the cluster to use system assigned managed identity in control plane.
> az aks update -g MyResourceGroup -n MyManagedCluster --enable-managed-identity

This is incorrect. Instead it creates a user-assigned managed identity, named as follow `<aks_cluster_name>-agentpool` if the argument `--assign-identity` isn't specified.

The documentation should perhaps clarify that a _system-assigned_ managed identity, name after the name of the AKS cluster, is always created at the creation of the cluster.

On a side node, the Azure documentation refers to managed identity both with and without the use of hyphen (i.e. "{user,system}-assigned" or "{user,system} assigned").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks.yml)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@FlorentATo I could see a System managed identity not a user assigned identity is being created when creating the cluster with `--enable-managed-identity`.  Please see below -
![image](https://user-images.githubusercontent.com/38112130/156258620-8894dfbf-6a34-4e9f-be72-cb326e0d04c2.png)

Also, agent pool user assigned managed identity with name like `<aks_cluster_name>-agentpool` is separate identity which gets created while creating the cluster.
Please let me know if you have any other questions.

**Comment by FlorentATo** [comment]
@SaurabhSharma-MSFT indeed, I got confused between the AKS cluster system-assigned managed identity and the user-assigned managed identity created for the default agentpool. My mistake 🙇 Feel free to close this issue.

**Comment by SaurabhSharma-MSFT** [comment]
@FlorentATo Sure. We will proceed with the closure of this case.  Regarding your second ask please visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.

For further details please go through [this](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity) official documentation. Thanks.
