### ISSUE TITLE
"az sf application list" and "az sf application-type list" commands do not return any results.

### ISSUE THREAD

**Issue by ptsapralis** [Azure/azure-cli#21450]
## Describe the bug

**Command Name**
`az sf application list`

**Errors:**
No results returned by these commands although several applications / application-types do exist on the target cluster. Different output formats have been tested without any success. Bug seen in interactive 'az' shell, too. Tested on Linux hosts - failing on those, too.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sf application list --resource-group {} --cluster-name {}`

## Environment Summary
```
macOS-12.2.1-x86_64-i386-64bit, Darwin 21.3.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.33.1

Extensions:
arcdata 1.1.2
interactive 0.4.5

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SubhashVasarapu-MSFT** [comment]
@ptsapralis, The "az sf" commands only support ARM deployed applications. Try using [sfctl](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/service-fabric/service-fabric-sfctl-application.md#sfctl-application-type-list) here in this case.

**Comment by ptsapralis** [comment]
> @ptsapralis, The "az sf" commands only support ARM deployed applications. Try using [sfctl](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/service-fabric/service-fabric-sfctl-application.md#sfctl-application-type-list) here in this case.

Thank you for this reply. All applications are deployed on the Service Fabric using Azure DEVOPS pipelines: are they not compatible with ARM-deployed applications?

**Comment by mwesigwaguma** [comment]
![Screenshot 2024-09-04 105753](https://github.com/user-attachments/assets/eded3b4f-651b-4595-9d6e-cd04e0eb55b3)
Command seems to be working. If applications were deployed directly to cluster, this behavior is expected
