### ISSUE TITLE
Add support for updating APIM policies using the AZ Cli

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-cli#21451]
Please add support to add/update policies in APIM at any level, using the az CLI.
It would be great to be part of the az apim commands.
https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest

**Comment by yonzhan** [comment]
route to CXP team

**Comment by sjuarezgx** [comment]
Hello
Is this already implemented?

**Comment by adrianhall** [comment]
The next release of the APIM module has not yet been released.

**Comment by sjuarezgx** [comment]
Have you got any estimated time of when it will be released?

thanks

**Comment by ulluoink** [comment]
any thing new here ? over a year ago ? @adrianhall

**Comment by adrianhall** [comment]
I am no longer on the API Management team.   I'll re-assign to the new owners.

**Comment by mikebudzynski** [comment]
@SubhashVasarapu-MSFT or @yonzhan, could you assign me to this issue?
