### ISSUE TITLE
Az cli add additional new line into string output

### ISSUE THREAD

**Issue by chinadragon0515** [Azure/azure-cli#21457]
For command like 
az k8s-extension show \
    --cluster-type connectedClusters \
    --cluster-name $clusterName \
    --resource-group $groupName \
    --name $extensionName \
    --query id \
    --output tsv > id.txt

If we open id.txt, we can see it has string with additional new line, and this is some for other commands like az monitor related cli.

This will cause some issue when to use these output.

Expected behavior, no new line for single string output.

**Comment by yonzhan** [comment]
route ton CXP team

**Comment by kairu-ms** [comment]
It seems `-o tsv` will add a newline at the end of output.

**Comment by kairu-ms** [comment]
This part of logic is in knack. @jiasli Could you have a look. Thanks. https://github.com/microsoft/knack/blob/d407b81d451d36c6ca1baeb3cd067a3f1275cb85/knack/output.py#L231-L258

**Comment by chinadragon0515** [comment]
this is a breaking changes and cause all the doc which has base64 encoding will not work for customer, can we make this as high priority?

**Comment by jiasli** [comment]
BTW, you may check what's actually in the variable using a very simply Python script:

```
$ python3 -c "import sys; print(sys.argv)" $name
['-c', 'clitest.rg6i4hl6iakg\r']
```

Note the `\r` in `$name`.
