### ISSUE TITLE
Default Key Policy Parameter for CVM Disk Encryption

### ISSUE THREAD

**Issue by jackrichins** [Azure/azure-cli#21467]
**Resource Provider**

Azure Key Vault

**Description of Feature or Work Requested**

az keyvault key create --default-cvm-policy
Passes a default policy to be specified by CVM team.

**Minimum API Version Required**

7.3

**Swagger Link**

**Target Date**

**Comment by yonzhan** [comment]
keyvault

**Comment by RunCai** [comment]
Hi, here is default CVM key release policy json file.

{
    "anyOf": [
        {
            "allOf": [
                {
                    "claim": "x-ms-attestation-type",
                    "equals": "sevsnpvm"
                },
                {
                    "claim": "x-ms-compliance-status",
                    "equals": "azure-compliant-cvm"
                }
            ],
            "authority": "[https://sharedeus.eus.attest.azure.net/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsharedeus.eus.attest.azure.net%2F&data=04%7C01%7CRun.Cai%40microsoft.com%7C5f7374cc19f2463a67d908d9fb1b7c07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637816917730113331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v11HJQH%2FljOq%2BLIysC1dMcnFmUbqtpUXBgcgH%2FYYUxw%3D&reserved=0)"
        },
        {
            "allOf": [
                {
                    "claim": "x-ms-attestation-type",
                    "equals": "sevsnpvm"
                },
                {
                    "claim": "x-ms-compliance-status",
                    "equals": "azure-compliant-cvm"
                }
            ],
            "authority": "[https://sharedwus.wus.attest.azure.net/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsharedwus.wus.attest.azure.net%2F&data=04%7C01%7CRun.Cai%40microsoft.com%7C5f7374cc19f2463a67d908d9fb1b7c07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637816917730113331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mxBLQVhi%2BM%2FY4aKZiv4xtC63dvftoRT%2FJ%2Bp1A6Epu4M%3D&reserved=0)"
        },
        {
            "allOf": [
                {
                    "claim": "x-ms-attestation-type",
                    "equals": "sevsnpvm"
                },
                {
                    "claim": "x-ms-compliance-status",
                    "equals": "azure-compliant-cvm"
                }
            ],
            "authority": "[https://sharedneu.neu.attest.azure.net/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsharedneu.neu.attest.azure.net%2F&data=04%7C01%7CRun.Cai%40microsoft.com%7C5f7374cc19f2463a67d908d9fb1b7c07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637816917730113331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7kj480xi7Z30IUBNUzzulcc%2BWxOtb%2BO2AdSpvwBoMM8%3D&reserved=0)"
        },
        {
            "allOf": [
                {
                    "claim": "x-ms-attestation-type",
                    "equals": "sevsnpvm"
                },
                {
                    "claim": "x-ms-compliance-status",
                    "equals": "azure-compliant-cvm"
                }
            ],
            "authority": "[https://sharedweu.weu.attest.azure.net/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsharedweu.weu.attest.azure.net%2F&data=04%7C01%7CRun.Cai%40microsoft.com%7C5f7374cc19f2463a67d908d9fb1b7c07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637816917730113331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5Yw%2Fq%2BOuwLEsEUeyHg776WVxABIhQYFmzndGsoN77tQ%3D&reserved=0)"
        }
    ],
    "version": "1.0.0"
}

**Comment by evelyn-ys** [comment]
@RunCai I see the authority you provided in the default policy is a link, Shall I use `https://shared***.***.attest.azure.net/` itself or the real link `https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsharedweu.weu.attest.azure.net%2F&data=04%7C01%7CRun.Cai%40microsoft.com%7C5f7374cc19f2463a67d908d9fb1b7c07%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637816917730113331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5Yw%2Fq%2BOuwLEsEUeyHg776WVxABIhQYFmzndGsoN77tQ%3D&reserved=0` as default policy?
