### ISSUE TITLE
`az staticwebapp update` should have `-g/--resource-group` param

### ISSUE THREAD

**Issue by StrawnSC** [Azure/azure-cli#21465]
**Is your feature request related to a problem? Please describe.**

If you have two static webapps with the same name (in different RGs) you can't specify which one to make the update to

**Describe the solution you'd like**

`az staticwebapp update` should have `-g/--resource-group` param

**Describe alternatives you've considered**

Allow `-n/--name` to take an RID 

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@StrawnSC Thanks for reaching out to us. I see that you have created and assigned this issue to yourself. I just wanted to check if you will be working on this issue or need any assistance from the CXP team. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@StrawnSC As discussed, I am removing the `CXP attention` label and adding the `Service Attention` label since you are actively working on fixing this issue.
