### ISSUE TITLE
NoRegisteredProviderFound for 'az synapse spark pool' for AzureUSGovernment environment

### ISSUE THREAD

**Issue by dayland** [Azure/azure-cli#21462]
## Describe the bug
When trying to access a spark pool in environment AzureUSGovernment, none of the available Azure CLI profiles match the resource provider versions available in the sovereign cloud. 

**Command Name**
`az synapse spark pool show`

**Errors:**
```
(NoRegisteredProviderFound) No registered resource provider found for location 'usgovvirginia' and API version '2021-06-01-preview' for type 'workspaces/bigDataPools'. The supported api-versions are '2019-06-01-preview, 2020-12-01, 2021-03-01, 2021-04-01-preview, 2021-05-01, 2021-06-01'. The supported locations are 'usgovarizona, usgovvirginia, usgovtexas'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'usgovvirginia' and API version '2021-06-01-preview' for type 'workspaces/bigDataPools'. The supported api-versions are '2019-06-01-preview, 2020-12-01, 2021-03-01, 2021-04-01-preview, 2021-05-01, 2021-06-01'. The supported locations are 'usgovarizona, usgovvirginia, usgovtexas'.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Deploy an Azure Synapse Workspace. 
- Attach a Spark Pool to the Synapse Workspace. 
- `az synapse spark pool show --workspace-name {} --resource-group {} --name {} --output {} --query {}`

## Expected Behavior
The spark pool json is returned. 

## Environment Summary
```
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-debian-11.2, Debian GNU/Linux 11 (bullseye)
Python 3.6.10
Installer: DEB

azure-cli 2.33.1

Extensions:
datafactory 0.5.0
authV2 0.1.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```
## Additional Context
We have tried all of the following Azure CLI profiles: 2017-03-09-profile, 2018-03-01-hybrid, 2019-03-01-hybrid, 2020-09-01-hybrid, latest. None of them match the resource provider in AzureUSGovernment.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@dayland Have you tried updating the Azure CLI version to latest ?

**Comment by SaurabhSharma-MSFT** [comment]
@dayland I have got confirmation internally that `2021-06-01-preview` version is not enabled in non-public regions.  You should be using the latest stable version of the SDK/CLI.
Also, you can try to use [az rest](https://docs.azure.cn/zh-cn/cli/reference-index?view=azure-cli-latest#az-rest) with [REST API Big Data Pools - Get - REST API](https://docs.microsoft.com/en-us/rest/api/synapse/big-data-pools/get) by changing the api version to "2021-06-01" if that works for you.

Please let me know if any questions.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@dayland We haven't heard back from you.  Please let us know if you have any other questions else we will proceed with the closure of this issue.

**Comment by dayland** [comment]
We are trying this, but are dealing with extra complications of the REST APIs that are not working the same as the CLI. This is a big overhaul for our automation scripts to have to move from CLI to REST. 

One very major difference is that on the CLI you can only specify the parameters that you want to update. In our scenario we only needed to update the --package and --library-requirements attributes, since the remainder of our Synapse Spark Pool is configured by terraform. 

Now that we are required to use the REST APIs, I have to remove the configuration in terraform or do it twice as the REST API requires the entire contents be provided in the body JSON. If I leave out sparkConfigProperties or any other attribute configured by terraform, it gets removed and cleared by the REST API. 

I cannot stress enough how frustrating this is, having to add another layer to our deployment architecture and rolling back working terraform code.

**Comment by SaurabhSharma-MSFT** [comment]
@dayland I have received the below workaround PowerShell script to get/update spark pool:

```
# show a spark pool 
$subscriptionID = "<your-subscription-id>"
$resourcegroupName = "<your-resourcegroup-name>"
$workspaceName = "<your-worksapce-name>"
$sparkpoolName = "<your-sparkpool-name>"
$sparkpool = az rest --resource $ResourceId --method GET -u "[https://management.azure.com/subscriptions/${subscriptionID}/resourceGroups/${resourcegroupName}/providers/Microsoft.Synapse/workspaces/${workspaceName}/bigDataPools/${sparkpoolName}?api-version=2021-06-01](https://management.azure.com/subscriptions/$%7bsubscriptionID%7d/resourceGroups/$%7bresourcegroupName%7d/providers/Microsoft.Synapse/workspaces/$%7bworkspaceName%7d/bigDataPools/$%7bsparkpoolName%7d?api-version=2021-06-01)" 
$sparkpool

# update spark pool package (Requirements files)

$libraryRequirementstxt = "<path-to-your-sparkpoolproperties-file>"
$libraryRequirement = Get-Content $libraryRequirementstxt -Raw
$json = $sparkpool| ConvertFrom-Json
$json.properties.libraryRequirements.content = $libraryRequirement
$filepath = Get-ChildItem $libraryRequirementstxt
$json.properties.libraryRequirements.filename = $filepath.Name
$json1 = $json | ConvertTo-Json | ConvertFrom-Json
$json.properties.libraryRequirements.content = $json1.properties.libraryRequirements.content.value
$json | ConvertTo-Json | Out-File body.json

az rest --resource $ResourceId --method PUT -u "[https://management.azure.com/subscriptions/${subscriptionID}/resourceGroups/${resourcegroupName}/providers/Microsoft.Synapse/workspaces/${workspaceName}/bigDataPools/${sparkpoolName}?api-version=2021-06-01](https://management.azure.com/subscriptions/$%7bsubscriptionID%7d/resourceGroups/$%7bresourcegroupName%7d/providers/Microsoft.Synapse/workspaces/$%7bworkspaceName%7d/bigDataPools/$%7bsparkpoolName%7d?api-version=2021-06-01)" --body `@body.json
Remove-Item body.json
```
I hope it is helpful.
Please let me know if you have any questions.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@dayland  Please let me know if you have any questions.  Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@dayland Please let me know if you have any questions else we will proceed to close this thread.

**Comment by dayland** [comment]
We have had to reconfigure our CI/CD pipelines to use the REST APIs.
