### ISSUE TITLE
CLI request for community gallery list 

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#21470]
**Is your feature request related to a problem? Please describe.**

For azure compute gallery, from https://github.com/Azure/azure-cli/issues/19882, we have GET community gallery/image/version and LIST community image/version. The LIST community galleries call is missing there because we do not have API level support for it.

**Describe the solution you'd like**

Currently on portal we plan to reply on ARG query for user to explore the LIST call, so no gallery service API won't be called. For CLI, we can schedule the same flow. CLI can just query ARG community galleries resources and display the result to user.

Command: sig image list-community --location xxx
**Describe alternatives you've considered**

**Additional context**

Sample ARG request url: 
POST https://centraluseuap.management.azure.com/providers/Microsoft.ResourceGraph/resources?api-version=2021-06-01-preview

request body:
{ "query": "CommunityGalleryResources| where type == 'microsoft.compute/locations/communitygalleries' |where location contains 'centraluseuap' "}

target date: 05/31/2022

**Comment by yonzhan** [comment]
compute

**Comment by zhoxing-ms** [comment]
Replaced by #22222
