### ISSUE TITLE
Links to cert info not found. 

### ISSUE THREAD

**Issue by anders2202** [Azure/azure-cli#21487]
[https://docs.microsoft.com/rest/api/keyvault/createkey/createkey#jsonwebkeycurvename](https://docs.microsoft.com/en-us/rest/api/keyvault/createkey/createkey#jsonwebkeycurvename).

And

[https://docs.microsoft.com/rest/api/keyvault/createkey/createkey#jsonwebkeytype](https://docs.microsoft.com/en-us/rest/api/keyvault/createkey/createkey#jsonwebkeytype).

retuns 404. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0f363b-7f21-0ea9-3e27-da7866c94102
* Version Independent ID: 6cc413e4-4f7d-9baa-a365-c9275fc6a7ad
* Content: [az keyvault key](https://docs.microsoft.com/en-us/cli/azure/keyvault/key?view=azure-cli-latest#az-keyvault-key-create)
* Content Source: [latest/docs-ref-autogen/keyvault/key.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/keyvault/key.yml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
keyvault
