### ISSUE TITLE
"az synapse pipeline create" FROM "az synapse pipeline show" output does not work

### ISSUE THREAD

**Issue by wibbico** [Azure/azure-cli#21489]
## Describe the bug

**Command Name**
`az synapse pipeline create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'properties'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/synapse/manual/operations/artifacts.py", line 82, in create_or_update_pipeline
    properties = PipelineResource.from_dict(definition_file['properties'])
KeyError: 'properties'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- az synapse pipeline show --workspace-name NAME-OF-WORKSPACE --name NAME-OF-PIPELINE_TO_COPY > NAME-OF-PIPELINE_TO_COPY.json
- `az synapse pipeline create --workspace-name NAME-OF-WORKSPACE --name NAME-OF-PIPELINE_TO_COPY_COPY --file @PIPELINE_TO_COPY.json`

## Expected Behavior

New Pipeline will be created

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-debian-bullseye-sid, Ubuntu 20.04.3 LTS
Python 3.6.10
Installer: DEB

azure-cli 2.33.1 *
```

**Comment by SaurabhSharma-MSFT** [comment]
@wibbico Could you please share the json file you are using to create the pipeline? Please remove any PII data before sharing the file.

**Comment by wibbico** [comment]
This is an example for a show output
```
{
	"id": "/subscriptions/XXXXX/resourceGroups/RGGGGG/providers/Microsoft.Synapse/workspaces/YYYYY/pipelines/wait_30",
	"name": "wait_30",
	"type": "Microsoft.Synapse/workspaces/pipelines",
	"properties": {
		"activities": [
			{
				"name": "Wait1",
				"type": "Wait",
				"dependsOn": [],
				"userProperties": [],
				"typeProperties": {
					"waitTimeInSeconds": 30
				}
			}
		],
		"policy": {
			"elapsedTimeMetric": {},
			"cancelAfter": {}
		},
		"folder": {
			"name": "root"
		},
		"annotations": [],
		"lastPublishTime": "2022-03-02T10:52:18Z"
	},
	"etag": "YYYY"
}
```

**Comment by wibbico** [comment]
This is an actual output from "show"

`{
  "activities": [
    {
      "additionalProperties": null,
      "dependsOn": [],
      "description": null,
      "name": "Wait1",
      "type": "Wait",
      "userProperties": [],
      "waitTimeInSeconds": 1
    }
  ],
  "additionalProperties": null,
  "annotations": [],
  "concurrency": null,
  "description": null,
  "etag": "***************",
  "folder": {
    "name": "root"
  },
  "id": "/subscriptions/********/pipelines/wait_0",
  "name": "wait_0",
  "parameters": null,
  "resourceGroup": "***************",
  "runDimensions": null,
  "type": "Microsoft.Synapse/workspaces/pipelines",
  "variables": null
}`

**Comment by wibbico** [comment]
Expected (actual output from rest api)

```
{
	"id": "/subscriptions/****/pipelines/wait_0",
	"name": "wait_0",
	"type": "Microsoft.Synapse/workspaces/pipelines",
	"properties": {
		"activities": [
			{
				"name": "Wait1",
				"type": "Wait",
				"dependsOn": [],
				"userProperties": [],
				"typeProperties": {
					"waitTimeInSeconds": 1
				}
			}
		],
		"policy": {
			"elapsedTimeMetric": {},
			"cancelAfter": {}
		},
		"folder": {
			"name": "root"
		},
		"annotations": [],
		"lastPublishTime": "2022-03-03T07:05:25Z"
	},
	"etag": "***"
}
```

**Comment by SaurabhSharma-MSFT** [comment]
@wibbico Sorry for the delay.  I am still waiting for internal reply from products team on this and get back to you. Thanks

**Comment by SaurabhSharma-MSFT** [comment]
@wibbico We don’t support passing the output of  `az synapse pipeline show` cmdlet to `az synapse pipeline create`. The input JSON file of `az synapse pipeline create` should be the definition file that you can retrieve from Synapse Studio. When designing and implementing these commands, we are trying to keep align with the original ADF ones as much as possible to minimize effort from ADF to Synapse. 
Please let me know if you have any questions. 
Thanks
Saurabh

**Comment by wibbico** [comment]
@SaurabhSharma-MSFT 

Unfortunately, this answer leaves me perplexed. The architecture of the CLI seemed to me to be clearly designed to migrate pipelines from Synapse A to Synapse B.

Why should I manually copy the JSON from the Synapse portal to import it via CLI? That makes no sense. It makes much more sense to use CLI -> CLI and Portal -> Portal.

How else should it be possible to migrate or update parts of a workspace (e.g. within a framework or components) to other Synapse workspaces?

As a professional data engineer, such migration paths are extremely important to me, as I do not want to rebuild every solution. Frameworks (through generalized pipelines) are an important part of professionalizing a solution.

Translated with www.DeepL.com/Translator (free version)

**Comment by SaurabhSharma-MSFT** [comment]
@wibbico We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
