### ISSUE TITLE
Support private endpoint management for AKS (aka Microsoft.ContainerService/managedClusters)

### ISSUE THREAD

**Issue by BzSpi** [Azure/azure-cli#21497]
The API for private endpoint management for AKS clusters has been published with version 2022-01-01, can you please implement the private endpoint related subcommands in the Azure CLI.

The related specs: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2022-01-01/managedClusters.json#L1445

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@BzSpi Apologies for the late reply. Could you please let us know your use case so that this will help us to look into this ask on priority ? Awaiting your reply.

**Comment by BzSpi** [comment]
Hi @navba-MSFT 

I'm trying to approve a private connection (without auto approval) from the Azure CLI.
Here's the command and the error message

Command
```
az network private-endpoint-connection approve --id /subscriptions/<redacted>/resourcegroups/rg_aksyohan/providers/Microsoft.ContainerService/managedClusters/<redacted>/privateEndpointConnections/<redacted> --description "Approved"
```

Error
```
Resource type must be one of Microsoft.Batch/batchAccounts, Microsoft.Automation/automationAccounts, Microsoft.Authorization/resourceManagementPrivateLinks, Microsoft.AppConfiguration/configurationStores, Microsoft.BotService/botServices, Microsoft.Cache/Redis, Microsoft.CognitiveServices/accounts, Microsoft.Compute/diskAccesses, Microsoft.ContainerRegistry/registries, Microsoft.DBforMySQL/servers, Microsoft.DBforMariaDB/servers, Microsoft.DBforPostgreSQL/servers, Microsoft.Devices/IotHubs, Microsoft.DocumentDB/databaseAccounts, Microsoft.DigitalTwins/digitalTwinsInstances, Microsoft.EventGrid/topics, Microsoft.EventGrid/domains, Microsoft.EventHub/namespaces, Microsoft.HDInsight/clusters, Microsoft.HybridCompute/privateLinkScopes, Microsoft.HealthcareApis/services, microsoft.insights/privateLinkScopes, Microsoft.KeyVault/managedHSMs, Microsoft.Keyvault/vaults, Microsoft.MachineLearningServices/workspaces, Microsoft.Media/mediaservices, Microsoft.Network/applicationGateways, Microsoft.Purview/accounts, Microsoft.PowerBI/privateLinkServicesForPowerBI, Microsoft.Search/searchServices, Microsoft.ServiceBus/namespaces, Microsoft.SignalRService/signalr, Microsoft.Sql/servers, Microsoft.Storage/storageAccounts, Microsoft.StorageSync/storageSyncServices, Microsoft.Synapse/workspaces, Microsoft.Web/sites, Microsoft.Web/hostingEnvironments, Microsoft.SignalRService/WebPubSub, Microsoft.DataFactory/factories, Microsoft.Databricks/workspaces, Microsoft.RecoveryServices/vaults
```

**Comment by navba-MSFT** [comment]
@BzSpi Thanks for your reply. I am looking into this ask. I have also reached out to the Product Owners in the background to check the Azure CLI command supportability for the private endpoint in AKS. I will get back on this thread once I have more details.

**Comment by navba-MSFT** [comment]
@BzSpi I had a follow-up question on this. In your use case, Are you trying to connect to a private AKS cluster from another vnet? Are you not able to peer ? Awaiting you reply.

**Comment by BzSpi** [comment]
Hello @navba-MSFT 
This is exactly my use case, I try to connect a private AKS with a private endpoint in another subnet. I cannot use a vnet peering in this use case.

**Comment by navba-MSFT** [comment]
@BzSpi Thanks for getting back. I have heard back from the product Owners on this. Currently, there are no immediate plans to add the Azure CLI support to achieve this ask. 

1. Could you please let me know the priority of this issue ?
2. And what is the ETA you are dealing with to get this implemented on your cluster ?

Based on this, I can provide some alternatives or recommendations. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@BzSpi Thanks for getting back. I will do some research on this for the available alternatives and get back to you.

**Comment by navba-MSFT** [comment]
@BzSpi I have heard back from from the product owners, unfortunately the workaround you have followed now seems to be the only option. There are no plans in the pipeline to have this in AzCLI.  
On a side note, We have a new type of cluster being released in the upcoming months that will allow for a much cleaner use of this scenario. There is no ETA for the release or no documentation available which I can share at this moment.

**Comment by navba-MSFT** [comment]
@BzSpi I hope you had a chance to look at my above comment. Please let me know if you have any follow-up questions on this.

**Comment by navba-MSFT** [comment]
@BzSpi It might take a month or two for this new feature. I will update this thread once it is released. In the meantime if you have any pending questions please feel free to ask.

**Comment by navba-MSFT** [comment]
@BzSpi We will update this thread once the feature is released. As of now no ETA for the same. So proceeding with the archival. If you have any follow-up questions, please feel free to reopen this thread.
