### ISSUE TITLE
az vm image terms documentation not updated

### ISSUE THREAD

**Issue by CalvoM** [Azure/azure-cli#21496]
The documentation for `az vm image terms` has not been updated. It is still showing `az vm image accept-terms`,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dfc804-87d6-913a-27fe-a9446a04eb13
* Version Independent ID: bfcb97df-2055-9eca-7a93-60811136d8cd
* Content: [az vm image](https://docs.microsoft.com/en-us/cli/azure/vm/image?view=azure-cli-latest#az-vm-image-accept-terms)
* Content Source: [latest/docs-ref-autogen/vm/image.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm/image.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
In fact, the document of `az vm image terms` command already exists. [doc link](https://docs.microsoft.com/en-us/cli/azure/vm/image/terms?view=azure-cli-latest)

**Comment by zhoxing-ms** [comment]
If there are no other questions, I will close the issue first. If there are any other questions later, we will reopen it
