### ISSUE TITLE
Azcli API issue: No registered resource provider found for location 'chinaeast2' and API version '2022-01-02-preview' for type 'managedClusters'

### ISSUE THREAD

**Issue by Icybiubiubiu** [Azure/azure-cli#21492]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

when use latest azcli in Mooncake/ChinaAzure, always found API issue as bellow:

Message: No registered resource provider found for location 'chinaeast2' and API version '2022-01-02-preview' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31, 2019-02-01, 2019-04-01, 2019-06-01, 2019-08-01, 2019-10-01, 2019-11-01, 2020-01-01, 2020-02-01, 2020-03-01, 2020-04-01, 2020-06-01, 2020-07-01, 2020-09-01, 2020-11-01, 2020-12-01, 2021-02-01, 2021-03-01, 2021-05-01, 2021-07-01, 2021-08-01, 2021-09-01, 2021-10-01, 2021-11-01-preview'. The supported locations are 'chinaeast2, chinanorth2'.

**To Reproduce**

Ubuntu: 18.04.6 LTS
azcli:2.34.0
kubectl:1.22.4

![image](https://user-images.githubusercontent.com/61815812/156331525-8b219ba8-08a9-4de5-a4ee-83c9eaab1f77.png)

**Expected behavior**

should return credential of my cluster.

**Environment summary**

Ubuntu: 18.04.6 LTS
azcli:2.34.0
kubectl:1.22.4
Cloud: Azure China

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@Icybiubiubiu Apologies for the late reply. You can run the below commands in order to use Azure CLI on Azure China Cloud:

>az cloud set --name AzureChinaCloud
az login
az account list
az account set -s <subscription-name>

**Note**: Also from the error it seems like the '2022-01-02-preview' API version is not yet available in China East 2. So in the meantime, You could try to use an [older version](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli#november-02-2021) of Azure CLI and then try to connect to your cluster. 

Refer [this](https://github.com/Azure/container-service-for-azure-china/blob/master/aks/README.md) article. Please let me know if you face any issues. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Icybiubiubiu I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by Icybiubiubiu** [comment]
@navba-MSFT Thanks for your prompt response. I have been taken AL these days.
I know it is this API is not available in ChinaEast2. If it is convenient for you, could you please help to follow up the ETA of this API in ChinaEast2?

Thanks in advance.

**Comment by navba-MSFT** [comment]
@Icybiubiubiu Thanks for getting back. I am checking this with our internal teams. I will update this thread once I have more details on this.

**Comment by navba-MSFT** [comment]
@Icybiubiubiu Could you please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) of AzCLI and test the command again? Seems like this API version should be available in Azure China Cloud now. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Icybiubiubiu Could you please provide an update on this ?

**Comment by navba-MSFT** [comment]
@Icybiubiubiu Please test again with the same above command and let us know if you face any issues. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by Icybiubiubiu** [comment]
Hi @navba-MSFT ,

Thanks for help and sorry for late response. I have taken a log AL.
It works now 
![image](https://user-images.githubusercontent.com/61815812/158734210-17c71062-a872-4bdd-96c3-34a9f94317af.png)
