### ISSUE TITLE
Azure-Cli install script doesn't work, issue with the Microsoft ubuntu repository? 

### ISSUE THREAD

**Issue by jeremy-albuixech** [Azure/azure-cli#21507]
Since approximately 8PM Pacific Time, our CI/CD system fails to build new images due to an issue with packages.microsoft.com. 

This is currently still reproducible by using the Azure-Cli install script provided in the cli [documentation](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-1-install-with-one-command) 

```
curl -sL https://aka.ms/InstallAzureCLIDeb | bash
[...]
Fetched 3964 B in 0s (8129 B/s)
Reading package lists... Done
W: Conflicting distribution: https://packages.microsoft.com/repos/azure-cli focal InRelease (expected focal but got xenial)
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/focal/main/binary-amd64/Packages.gz  File has unexpected size (8601 != 18731). Mirror sync in progress? [IP: 40.117.131.251 443]
   Hashes of expected file:
    - Filesize:18731 [weak]
    - SHA512:d2791dca6a9339e8f57a5d5ec6922f1c072a7baa0bad951e11551849df01b86776c28da810f05353e20cf4e48e980d307d243a232e25735fe89fa9554696fb8e
    - SHA256:4f529a893071dc1985f3ea3c806d0efc6790761bc4dca0c955ea59d6ccb05318
    - SHA1:9aef2de691b04069761dcad22906d00f0ecb3461 [weak]
    - MD5Sum:46be8f6e68b2c5efede1017b9ce99f37 [weak]
   Release file created at: Thu, 03 Mar 2022 03:27:53 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**To Reproduce**
Run the bash script provided at https://aka.ms/InstallAzureCLIDeb from a debian distribution. Tested on: 

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```

**Expected behavior**

Install script should work as usual. 

**Environment summary**

**Additional context**

**Comment by jeremy-albuixech** [comment]
It just started working again, it looks like this issue was happening for about ~30 to 50 minutes, I am wondering if there is a way to see status of the registry?

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
We have contacted https://packages.microsoft.com/ team and this issue should now have been fixed.

**Comment by jeremy-albuixech** [comment]
Thanks! 

I can confirm that it started working less than an hour after the initial issue, it did cause us some small troubles during that time since we had to restart a bunch of builds. 

I am wondering if there are any actionable items that we can track, for example is there any way to track the status/health of this registry?

**Comment by jiasli** [comment]
@jeremy-albuixech, apologize for the inconvenience caused. This issue was caused by a regression introduced by a recent update to  https://packages.microsoft.com/ and the change had been rolled back. 

> I am wondering if there are any actionable items that we can track, for example is there any way to track the status/health of this registry, or is there a better/more appropriate place to see communication and issues about this platform?

Currently there is no health dashboard for https://packages.microsoft.com/. If you see any problems, please feel free to open a GitHub issue and put something like "URGENT" in the title so that we can notice it and work on it with high priority. 😊
