### ISSUE TITLE
add function "readModules"

### ISSUE THREAD

**Issue by arobal** [Azure/azure-cli#21500]
Hi,

there is a neat az-function to set the modules of an iot edge device via the command line (set-modules), but the function to read the modules is missing. 

This would be quite helpful in some cases (f.e. use the same module config which is already set at one device for several other devices...I know there is the function of deployments...but still I need this function in some cases)

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afcbe3a0-4ef9-932f-b23e-a9bc6b1d25b8
* Version Independent ID: 98bc371a-8376-29f3-a1d1-d21112332def
* Content: [az iot edge](https://docs.microsoft.com/en-us/cli/azure/iot/edge?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/iot/edge.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/iot/edge.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@arobal Thanks for the feedback! We are routing this to the concerned team to consider.

**Comment by vilit1** [comment]
Added with https://github.com/Azure/azure-iot-cli-extension/pull/617. This method should be out with the next azure-iot extension release
