### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by shreya-bajpais1** [Azure/azure-cli#21514]
I am not able to access my azure clusters. 

I am getting this error:-
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /2d96bd7b-8880-437c-8d23-6a248a2d3323/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb595dc5f8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/az/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/az/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

**Comment by yonzhan** [comment]
Which Azure CLI command do you use?

**Comment by shreya-bajpais1** [comment]
az login

**Comment by PramodValavala-MSFT** [comment]
@shreya-bajpais1 Based on the error, DNS resolution has failed. Could you confirm if you are able to access the internet from the shell prompt? You could try running

```
nslookup login.microsoftonline.com
```

**Comment by shreya-bajpais1** [comment]
@PramodValavala-MSFT, I am getting this error:- ";; connection timed out; no servers could be reached".

**Comment by PramodValavala-MSFT** [comment]
@shreya-bajpais1 In that case, Azure CLI can't really do much on its own. You would want to check network settings to first restore internet access or check any firewall rules that might be blocking access.
