### ISSUE TITLE
Warning about the underlying Active Directory Graph API, the link doesn't exist.

### ISSUE THREAD

**Issue by pmatthews05** [Azure/azure-cli#21512]
**Describe the bug**
When calling given `az ad` commands a warning appears on the screen.
The link doesn't go to a valid page.

WARNING: The underlying Active Directory Graph API will be replaced by Microsoft Graph API in a future version of Azure CLI. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration

**To Reproduce**
Run a `az ad` command.

**Expected behavior**
The link  https://docs.microsoft.com/cli/azure/microsoft-graph-migration to beto the correct page or the page for that link to exist.

**Environment summary**
CLI Version 2.34.0
OS Windows Server
Shell PowerShell

**Additional context**
Code where the link is here: https://github.com/Azure/azure-cli/blob/release/src/azure-cli/azure/cli/command_modules/role/__init__.py

**Comment by jiasli** [comment]
@pmatthews05, you have sharp eyes. The PR for updating the doc is https://github.com/MicrosoftDocs/azure-docs-cli/pull/2985. We will publish the doc as soon as conversations are resolved.

**Comment by pmatthews05** [comment]
@jiasli I have code that checks/creates a bunch of App Registrations and assigns API permissions. This morning after my update of az cli I just had warning messages everywhere. 

That link to the PR you supplied allows me to read the docs. So thank you. Assuming the PR is being accepted shortly, I'm happy to close this.
