### ISSUE TITLE
az vm create command generates stderr for public-ip behaviour change

### ISSUE THREAD

**Issue by BCOps** [Azure/azure-cli#21529]
## Describe the bug

**Command Name**
az vm create (as below)

az vm create -g $rgName -n $vmName --location $location 
            --nics $nicName--image $image --size $vmSku 
            --data-disk-sizes-gb $size--storage-sku $storageSku 
            --admin-username $userName --admin-password $pwd
            --tags @("tag1=value1","tag2=value2") 
            -o json

**Errors:**
Error generated from Azure DevOps build agent when running comand (windows-latest)
```
#[error]WARNING: It is recommended to use parameter "--public-ip-sku Standard" to create new VM with Standard public IP. Please note that the default public IP used for VM creation will be changed from Basic to Standard in the future.
##[error]Script has output to stderr. Failing as failOnStdErr is set to true.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Simply run the command populated with appropriate values, and a warning will be generated to stderr about the public ip.
This causes a pipeline run task to fail unless stderr is ignored.

- Create resource group and Nic to allow command to run

## Expected Behavior

No public IP was specified in the command, I would not expect there to be an error output to stderr about the public-ip behaviour change. If there was going to be a warning generated regardless, I would expect it to be a stdout message as it is not a breaking warning, stderr seems to be incorrect here.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.33.0

Extensions:
aks-preview 0.5.51
automation 0.1.1
azure-devops 0.23.0
connectedk8s 1.2.0
containerapp 0.2.0
resource-graph 2.1.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
Compute

**Comment by jiasli** [comment]
The topic of using `failOnStdErr` is tracked by https://github.com/Azure/azure-cli/issues/18372.
