### ISSUE TITLE
"az account list" returncode is 0 while not logged in.

### ISSUE THREAD

**Issue by nonpolarity** [Azure/azure-cli#21522]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

After "az logout", "az account list" output is "Please run "az login" to access your accounts.", but the command's returncode is 0, which I think should be a non-zero value.

**To Reproduce**

alvin@wechen3-u20-5:~$ az logout
There are no active accounts.
alvin@wechen3-u20-5:~$ az account show
Please run 'az login' to setup account.
alvin@wechen3-u20-5:~$ az account list
Please run "az login" to access your accounts.
[]
alvin@wechen3-u20-5:~$ echo $?
0

**Expected behavior**

The returncode should be a non-zero value in this case that the returncode can indicate the exception.

**Environment summary**

Ubuntu 20.04, 
alvin@wechen3-u20-3:~/ACC-FACVM-Tooling$ az --version
azure-cli                         2.34.1

core                              2.34.1
telemetry                          1.0.6

Extensions:
mesh                              0.10.7
fdacvm                             0.1.0
ssh                                1.0.0

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/alvin/.azure/cliextensions'
Development extension sources:
    /home/alvin/ACC-FACVM-Tooling

Python (Linux) 3.8.12 (default, Mar  2 2022, 07:26:21)
[GCC 9.3.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Additional context**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by calvinhzy** [comment]
By design, list commands never return non zero exit code. 
It is returning an empty list [], which is not an exception. 
Please see  https://github.com/Azure/azure-cli#exit-codes for detailed explanations of the exit code design.
