### ISSUE TITLE
[Service Team Request] Azure CLI support for Azure Healthcare APIs

### ISSUE THREAD

**Issue by kyclai** [Azure/azure-cli#21536]
**Resource Provider**
HealthcareApis

**Description of Feature or Work Requested**
Azure Healthcare APIs is a set of managed API services based on open standards and frameworks that enable workflows to improve healthcare and offer scalable and secure healthcare solutions.
Feature overview: https://azure.microsoft.com/services/healthcare-apis
Feature documentation: https://docs.microsoft.com/azure/healthcare-apis

**Minimum API Version Required**
2021-11-01

**Swagger Link**
Feature: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/healthcareapis/resource-manager
Pull request: https://github.com/Azure/azure-rest-api-specs/pull/16108

**Target Date**
2022-03-15

**Comment by yonzhan** [comment]
PLR

**Comment by kyclai** [comment]
Hi @jsntcy, I'm just wondering how this work item is progressing and if it's still estimated to complete by April 26, 2022.

**Comment by jsntcy** [comment]
Yes, we planed it in this sprint and will release it around April 26.

**Comment by kyclai** [comment]
Hi @jsntcy / @wangzelin007 / @yonzhan, I noticed that this work item is still open and its milestone has changed. Has the release been postponed to May 24, 2022?

**Comment by wangzelin007** [comment]
> 

Sorry for replying so late.
Upgrading the new API version has changed a lot.
And I found that the old version has a part of the code that is not automatically generated by codegen.
I'm looking for Mark Baker and Peiyuan to confirm how to upgrade this part.
I will release this version as soon as possible.

**Comment by wangzelin007** [comment]
> Hi @jsntcy / @wangzelin007 / @yonzhan, I noticed that this work item is still open and its milestone has changed. Has the release been postponed to May 24, 2022?

Sorry for replying so late.
Upgrading the new API version has changed a lot.
And I found that the old version has a part of the code that is not automatically generated by codegen.
I'm looking for Mark Baker and Peiyuan to confirm how to upgrade this part.
I will release this version as soon as possible.
