### ISSUE TITLE
Link to format of JSON file

### ISSUE THREAD

**Issue by egoward** [Azure/azure-cli#21531]
Hi there,

This page talks about a file which may or may not be JSON.  It would be great to call out how it should be structured and give an example.  Azure CLI seems to come back with "not enough values to unpack" for me which isn't super helpful.

Thanks,

Ed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* Content: [az webapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by seligj95** [comment]
@egoward - the json structure referenced here can vary depending on what you're trying to do but is consistent with the other Azure cli commands. for example, if you're trying to set app settings, you can do the below. can you share some more details about what you're looking for here?

`az webapp config appsettings set -g my-rg -n my-app --settings @settings.json` 

and the settings.json file would look like:

```
{
    "test1": "1234",
    "test2": "123",
    "test3": "1234",
    "test4": "12345"
}
```

**Comment by seligj95** [comment]
additionally, we have guidance for bulk editing here: https://learn.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal#edit-app-settings-in-bulk. i will get this link added to the `--settings` parameter

**Comment by egoward** [comment]
Thanks @seligj95, link to docs as source of truth is a good plan.

For what it's worth, your example file was a JSON object `{"test1":"1234"}` but the [linked example](https://learn.microsoft.com/en-gb/azure/app-service/configure-common?tabs=cli#edit-app-settings-in-bulk) is a JSON array `[{"name":"test1","value":"1234"} ]`.
