### ISSUE TITLE
Add `--no-wait` parameter to `az postgres flexible-server start/stop` commands

### ISSUE THREAD

**Issue by marlowp** [Azure/azure-cli#21533]
**Is your feature request related to a problem? Please describe.**
The command to start/stop the postgres flexible-server instance can be long-running. This can cause issues in automated environments where many start/stop operations are being performed sequentially.

**Describe the solution you'd like**
Add a `--no-wait` parameter to the start/stop commands.

**Additional context**
The `--no-wait` parameter is available on many other long-running CLI commands, for example `az aks start/stop --no-wait`

**Comment by yonzhan** [comment]
route to CXP team

**Comment by nachoalonsoportillo** [comment]
Support for this was added through PR #25212.

@yonzhan, please close this one as resolved. Thanks!
