### ISSUE TITLE
az webapp list is showing null values for siteConfig

### ISSUE THREAD

**Issue by junaidahmed92** [Azure/azure-cli#21548]
I want to get list of all webapps where healhCheckPath is not nult. I tried `az webapp list --query "[?not_null(siteConfig.healthCheckPath)].{Name:name, ResourceGroup:resourceGroup}"` and `az webapp list --query "[?siteConfig.healthCheckPath!=null].{Name:name, ResourceGroup:resourceGroup}"`  but the cli was returning empty array. I then ran the command `az webapp list --query "[?name=='web_app_where_health_check_is_enabled']"` and this returns one record but heathCheckPath was null but in reality health check is enabled for this specific app.
Later I tried `az webapp show -g <resource-group> -n <name>` and this showed me the value for healthCheckPath. So the issue is with the list command. 
I can't use webapp show command because I want to fetch all the webapps which meet specific conditions.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@junaidahmed92 Looks like this is a limitation of the underlying REST API ([Web Apps - List](https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/list)) where it doesn't include `siteConfig` data. I will check with the concerning team for more insights.

**Comment by PramodValavala-MSFT** [comment]
@junaidahmed92 This seems to be by design with an extra REST API call required to get the configuration for a web app, which the CLI is performing when running `az webapp show`. Here is a workaround you can use instead.

```sh
az webapp list --query '[].id' -o tsv | xargs | xargs -I{} bash -c "az webapp show --ids {} --query '[?not_null(siteConfig.healthCheckPath)].{Name:name,
ResourceGroup:resourceGroup}'"
```

**Comment by junaidahmed92** [comment]
@PramodValavala-MSFT , thanks for the clarification. Now by running the command you shared, I am getting following error:

xargs : The term 'xargs' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:41
+ az webapp list --query '[].id' -o tsv | xargs | xargs -I{} bash -c "a ...
+                                        ~~~~~
    + CategoryInfo          : ObjectNotFound: (xargs:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by PramodValavala-MSFT** [comment]
@junaidahmed92 Sorry about that. I updated my answer for PowerShell too. I was tricky to convert the same command to PowerShell and it might be more complicated than it needs to be (not really a hard-core PowerShell user 😝). Feel free to simplify it and share here.

**Comment by panchagnula** [comment]
@junaidahmed92 given SiteConfig is not part of the Site Object call we don't support this for performance issue reasons on List commands - should be supported with show for a single resource.
