### ISSUE TITLE
Failed to create container with exisiting vnet and subnet

### ISSUE THREAD

**Issue by ramganesh19** [Azure/azure-cli#21542]
## Describe the bug

**Command Name**
`az container create`

**Errors:**
```
'NetworkProfile' object has no attribute 'result'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-pnzu83p3\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 659, in execute
cli\core\commands\__init__.py, ln 722, in _run_jobs_serially
cli\core\commands\__init__.py, ln 715, in _run_job
Local\Temp\pip-unpacked-wheel-ruxb6hpy\six.py, ln 703, in reraise
...
cli\command_modules\container\custom.py, ln 348, in _get_vnet_network_profile
AttributeError: 'NetworkProfile' object has no attribute 'result'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az container create --resource-group {} --name {} --image {} --cpu {} --memory {} --registry-login-server {} --registry-username {} --registry-password {} --dns-name-label {} --ports {} {} --azure-file-volume-account-name {} --azure-file-volume-account-key {} --azure-file-volume-share-name {} --azure-file-volume-mount-path {} --vnet {} --subnet {} --environment-variables {} {} {} {} {} {} {} {} {} {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.0 *

```

**Comment by navba-MSFT** [comment]
@ramganesh19 Thanks for reaching out to us. This issue is addressed in Azure/azure-cli#17486. Could you please use the [most recent version ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)of Azure CLI and then try running the same command ? Awaiting your reply.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@ramganesh19 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ramganesh19 We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
