### ISSUE TITLE
Java NPE error and java minor version selection

### ISSUE THREAD

**Issue by florentpln** [Azure/azure-cli#21540]
I have a Azure Linux Webapp using Apache poi that is raising the following error:

java.lang.InternalError: java.lang.reflect.InvocationTargetException
at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
...
Caused by: java.lang.NullPointerException: null
at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:379)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:324)
at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
... 198 common frames omitted
I have seen that such error can happen using openjdk, and can be solved doing some conf, but how to solve this on Azure?

Doing some tests, I have found that it is working fine using java 11.0.11 instead of last default one 11.0.12, the thing is that I didn't found any way to force the minor version of java using "az webapp create" command. So I am stuck here...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest&source=docs#az-webapp-create)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by panchagnula** [comment]
This is not a CLI error but a Runtime issue - please create a support case so Java team can help with the investigation.

**Comment by panchagnula** [comment]
@JasonFreeberg FYI.

**Comment by florentpln** [comment]
Thank you for your detailed answer.

What about my second question : it is working fine using java 11.0.11 instead of last default one 11.0.12, the thing is that I didn't found any way to force the minor version of java using "az webapp create" command. ?

Thanks.

**Comment by JasonFreeberg** [comment]
@florentpln -- Go to the Configuration blade in the portal and you can set your patch version there.

**Comment by florentpln** [comment]
Thanks. I already seen this detail. My question was to be able to set this using "az webapp create".
The available runtimes are not allowing me to select the minor version:
az webapp list-runtimes --linux | grep JAVA
  "JAVA|8-jre8",
  "JAVA|11-java11",

**Comment by florentpln** [comment]
Why did you close this ticket?
The problem is that everytime webapp restart or re-install, java minor version setting is overwritten.
This is not usable on a production environment!!

**Comment by JasonFreeberg** [comment]
Here are the strings for the minor versions: https://github.com/Azure/azure-functions-ux/blob/dev/server/src/stacks/2020-10-01/stacks/web-app-stacks/JavaContainers.ts

Don't know what you mean by the Java version being overwritten when it restarts

**Comment by florentpln** [comment]
Ok, thanks. You are right restarts does not overwrite java version.

Minor versions on settings does not work on "az create" command.

I was however able to use minor version on devops pipeline, using something like:
- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy'
  inputs:
    azureSubscription: MY_SUBS
    appType: webAppLinux
    appName: MY_APP_NAME
    package: MY_PACKAGE
    runtimeStack: 'JAVA|11.0.11'
