### ISSUE TITLE
az Keyvault list-deleted wrong information

### ISSUE THREAD

**Issue by osmadrig** [Azure/azure-cli#21555]
[Enter feedback here]
Hello Team,

I found where reads "When --resource-type is not present the command will list all deleted vaults and HSMs." Is misleading because the Manage HSM are not listed. If is not specific  --resource-type Manage HSM will not be listed . Test have been done.

![image](https://user-images.githubusercontent.com/101149235/157128854-682c1973-cb5c-430a-88f9-72c19fc36c73.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226e5769-f6c8-a480-db78-727fb96348ec
* Version Independent ID: 8ee06a2a-6eda-11be-3c8e-6ad948be207e
* Content: [az keyvault](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az-keyvault-list-deleted)
* Content Source: [latest/docs-ref-autogen/keyvault.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/keyvault.yml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
keyvault
