### ISSUE TITLE
application-security-groups update with multiple ip configurations in vm nic

### ISSUE THREAD

**Issue by nishil-ck** [Azure/azure-cli#21551]
Hello,

I have a scenario with multiple IP address on the vm nic and I have to add this vm into application security group as well. The az cli worked well with single ip configuration, but failed to update with multiple configurations.

`az network nic ip-config list -g $RG --nic-name testvm96 --query "[].id" -o tsv |awk -F'/' '{print $11}'
ipconfig1
ipconfig2`

`az network nic ip-config update  -g $RG --nic-name testvm96 --name ipconfig1 --application-security-groups testasg`

```
Error code: 
(AllIpConfigurationsOnANicMustBelongToTheSameApplicationSecurityGroups) All IPConfigurations on a Network Interface should reference the same set of Application Security Groups. IPConfiguration /subscriptions/b57363f8-033b-49e7-a8d5-ed90fce76951/resourceGroups/HEC45-CHM-eastus2euap-1/providers/Microsoft.Network/networkInterfaces/testvm96/ipConfigurations/ipconfig1 references ASG(s) /subscriptions/b57363f8-033b-49e7-a8d5-ed90fce76951/resourceGroups/HEC45-CHM-eastus2euap-1/providers/Microsoft.Network/applicationSecurityGroups/testasg, wheras IPConfiguration /subscriptions/b57363f8-033b-49e7-a8d5-ed90fce76951/resourceGroups/HEC45-CHM-eastus2euap-1/providers/Microsoft.Network/networkInterfaces/testvm96/ipConfigurations/ipconfig2 references ASG(s) .
Code: AllIpConfigurationsOnANicMustBelongToTheSameApplicationSecurityGroups
Message: All IPConfigurations on a Network Interface should reference the same set of Application Security Groups. IPConfiguration /subscriptions/b57363f8-033b-49e7-a8d5-ed90fce76951/resourceGroups/HEC45-CHM-eastus2euap-1/providers/Microsoft.Network/networkInterfaces/testvm96/ipConfigurations/ipconfig1 references ASG(s) /subscriptions/b57363f8-033b-49e7-a8d5-ed90fce76951/resourceGroups/HEC45-CHM-eastus2euap-1/providers/Microsoft.Network/applicationSecurityGroups/testasg, wheras IPConfiguration /subscriptions/b57363f8-033b-49e7-a8d5-ed90fce76951/resourceGroups/HEC45-CHM-eastus2euap-1/providers/Microsoft.Network/networkInterfaces/testvm96/ipConfigurations/ipconfig2 references ASG(s) .

```
 
I tried to include both ipconfig1 and ipconfig1 in the command line using delimiter as space, coma etc. But couldn't get the correct usage with multiple ip configurations.

Could you please get the correct usage in this scenario ?

**Comment by yonzhan** [comment]
network

**Comment by YuanyuanNi** [comment]
Hi :
     @nishil-ck As the error message mentioned that "All IP configuration on a nic should belong to the same ASG" ,it means that the ipconfig1 and ipconfig2 you used here should belong to the same ASG（testasg for example), maybe you should change your command in this way and try again.
Best wishes.

**Comment by shiniizuka** [comment]
Workaround does not work even if we specify all of ipconfigurations as --ids.

Command I tried:
az network nic ip-config update --application-security-groups asg --ids /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/networkInterfaces/nic/ipconfigurations/ipconfig1 /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/networkInterfaces/nic/ipconfigurations/ipconfig2

Error:
    "code": "AllIpConfigurationsOnANicMustBelongToTheSameApplicationSecurityGroups",
    "message": "All IPConfigurations on a Network Interface should reference the same set of Application Security Groups. IPConfiguration /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/networkInterfaces/nic/ipConfigurations/ipconfig1 references ASG(s) , wheras IPConfiguration /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/networkInterfaces/nic/ipConfigurations/ipconfig2 references ASG(s) /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/applicationSecurityGroups/asg.",
