### ISSUE TITLE
‘ascii’ codec can’t encode character’s - NVIDIA® NVLink®

### ISSUE THREAD

**Issue by abbassayyed-msft** [Azure/azure-cli#21554]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
**Bash Script :** 
Running Azure CLI via sh script (Bash) which run Python script.
CLI is run as a part of MLOps deployment via Bash

**CLI command from sh script -** 

     #!/bin/bash
    az ml run submit-script -g ResourceGroupName  -e ExpName -w MLWorkSpaceName --ct ComputeName -d 'conda_dependencies.yml'  'Deploy.py'

**Error Message**
```
The Output of this CLI throwing error message:
    ERROR: 'ascii' codec can't encode character '\xae' in position 53: ordinal not in range(128)
```

**Failing on :**

    . Please ignore this if the GPUs don't utilize NVIDIA® NVLink® switches.

**To Reproduce**
CLI command from sh script - 

from EV2 (MsSigned) run bash script as below.
```
     #!/bin/bash
    az ml run submit-script -g ResourceGroupName  -e ExpName -w MLWorkSpaceName --ct ComputeName -d 'conda_dependencies.yml'  'Deploy.py'
```

**Expected behavior**
The CLI should work successfully. 

**Environment summary**
Bash script as sh running from Ev2 as a part of complaint release.

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@abbassayyed-msft Sorry for the delay here! Looks like you are using version 2.0.62 of Azure CLI. Could you upgrade to the latest version (2.34.1) and confirm if you are seeing this in the newer version too? Also, could you share the version of the `ml` extension and upgrade to the latest version (2.1.2) there as well?

**Comment by abbassayyed-msft** [comment]
I fixed it; this was an issue with ubuntu. I had to change locale in POSX format.

**Comment by PramodValavala-MSFT** [comment]
@abbassayyed-msft Glad to hear that! Thanks for sharing the solution! This could help others with the same issue.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
