### ISSUE TITLE
az webapp config storage-account add falsely returns "InvalidCredentials"

### ISSUE THREAD

**Issue by tokleine** [Azure/azure-cli#21571]
## Describe the bug
When mounting an existing Azure FileShare to an existing Azure Function App, I receive the info that the credentials (i.e. storage account key) are invalid. However, the mount still works, as I can call my Function App HTTP Trigger and it can access files on the FileShare. 

In the past I have had "InvalidCredential" response before, but back then I actually had made a mistake with the Storage Account key. Now everything is correct, just the response is for some reason wrong. 

I also double checked that this command returns the same when run from an Azure DevOps Pipeline as when run from Powershell locally.

I am not aware of having updated my az cli or really any other component of the solution (Build Pipeline, Storage Account, Keys or Function App)

**Command Name**
`az webapp config storage-account add`

**Errors:**
```
{
  "myMountId": {
    "accessKey": "correctStorageAccountKey",
    "accountName": "myStorageAccount",
    "mountPath": "/mounted",
    "shareName": "realtime-models-and-data",
    "state": "InvalidCredentials",
    "type": "AzureFiles"
  }
}
```

## To Reproduce:
- `az webapp config storage-account add --name {} -g {} --custom-id {} --storage-type {} --share-name {} --account-name {} --mount-path {} --access-key {}`

## Expected Behavior
```
{
  "myMountId": {
    "accessKey": "correctStorageAccountKey",
    "accountName": "myStorageAccount",
    "mountPath": "/mounted",
    "shareName": "realtime-models-and-data",
    "state": "Ok",
    "type": "AzureFiles"
  }
}
```
## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.24.2

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by panchagnula** [comment]
Not a CLI error but the response from API - informed feature team of this.

**Comment by tokleine** [comment]
Is there any update on this @panchagnula ? It would be great to be able to rely on logs again...

**Comment by panchagnula** [comment]
@tokleine like I mentioned this is not a CLI issue but rather API returning this repsonse - we reported this to the API team, & once their fix is released the CLI will reflect the same.

**Comment by imeya** [comment]
hello @panchagnula , could you please let us know where we can check this information with the API team? thanks.

**Comment by panchagnula** [comment]
> hello @panchagnula , could you please let us know where we can check this information with the API team? thanks.

you will need open a support case for that most likely or however one would reach out to the platform team to report issues. This is for CLI only, sorry I can't provide more assistance here.
