### ISSUE TITLE
Route all through CLI

### ISSUE THREAD

**Issue by jhonnatanpb** [Azure/azure-cli#21573]
When you add vnet to webapps or functions, there is an option to set 'route all', and I don't see a way to do it by the CLI command, just the UI. So adding the vnet integration to the function through CLI, after that you need to go to the portal and manually  set route all if it's needed for that resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f714ea49-754e-486f-938d-5394399d233a
* Version Independent ID: 2b0a24e2-be87-4dee-9991-5e35589a3b07
* Content: [az functionapp vnet-integration](https://docs.microsoft.com/en-us/cli/azure/functionapp/vnet-integration?view=azure-cli-latest#az-functionapp-vnet-integration-add)
* Content Source: [latest/docs-ref-autogen/functionapp/vnet-integration.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/functionapp/vnet-integration.yml)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@jhonnatanpb We are looking into it and get back to you for any additional information.

**Comment by jhonnatanpb** [comment]
> @jhonnatanpb We are looking into it and get back to you for any additional information.

Thank you.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
Hello @jhonnatanpb Thanks for the feedback, we are routing this to the Service Team's attention!

**Comment by seligj95** [comment]
@jhonnatanpb - We have the following CLI commands that set this:

`az webapp config set --vnet-route-all-enabled`

`az functionapp config set --vnet-route-all-enabled`

Closing this issue as this should cover the ask. Feel free to reach out with any additional questions.
