### ISSUE TITLE
az resource show fails for Azure Compute Gallery image versions with API 2022-01-03

### ISSUE THREAD

**Issue by stefanes** [Azure/azure-cli#21572]
**Describe the bug**
`az resource show --ids /subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.Compute/galleries/<gal>/images/<name>/versions/<version>` fails with error:
```
(InvalidParameter) The value of parameter api-version is invalid.
Code: InvalidParameter
Message: The value of parameter api-version is invalid.
Target: api-version
Inner error: {
    "internalErrorCode": "ParameterValueInvalid"
}
```

Same error is returned if `--api-version 2022-01-03` explicitly specified. The command works as expected with `--api-version 2021-10-01`.

**To Reproduce**
Run command `az resource show --ids /subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.Compute/galleries/<gal>/images/<name>/versions/<version>`

**Expected behavior**
The resource JSON is returned.

**Environment summary**

Azure Cloud Shell:

```
azure-cli                         2.34.1

core                              2.34.1
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0
ai-examples                        0.2.5
ssh                                1.0.0

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0
```

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
This should be a service related issue. @kangsun-ctrl Do you know who can help us investigate this issue?

**Comment by RakeshMohanMSFT** [comment]
@stefanes Can you please try upgrading to latest version of [azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)? Its working for me with both versions of API `2021-10-01` and `2022-01-03` and without explicitly specifying the versions too. I am using 2.35.0 and the latest is [2.36.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)

**Comment by stefanes** [comment]
I can confirm this now seems to work with the Azure CLI version in Azure Cloud Shell:

```
PS /home/stefan> az --version
azure-cli                         2.37.0

core                              2.37.0
telemetry                          1.0.6

Extensions:
quota                              0.1.0
azure-devops                      0.18.0
ai-examples                        0.2.5
ssh                                1.1.1

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1
```
