### ISSUE TITLE
Inconsistent naming for parameters in application-gateway

### ISSUE THREAD

**Issue by askpatrickw** [Azure/azure-cli#21577]
**Describe the bug**
Why Name and sometime Gateway-name?

**To Reproduce**

`az network application-gateway stop --help` shows `--name`
`az network application-gateway frontend-ip list --help` shows `--gateway-name`

I'm sure there others, I'm not going to test all of them. ;-)

**Expected behavior**
Use Name like in the column output for list (and its less typing)

```cli
az network application-gateway list -o table

EnableHttp2    Location    Name               OperationalState    ProvisioningState    ResourceGroup    ResourceGuid
-------------  ----------  -----------------  ------------------  -------------------  ---------------  ------------------------------------
```

**Environment summary**
{
  "azure-cli": "2.34.1",
  "azure-cli-core": "2.34.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-iot": "0.13.0"
  }
}

**Comment by yonzhan** [comment]
network

**Comment by RakeshMohanMSFT** [comment]
@askpatrickw Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@askpatrickw [az network application-gateway frontend-ip](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/frontend-ip?view=azure-cli-latest#az-network-application-gateway-frontend-ip-create) has another parameter named `--name`, to maintain consistency we have kept the parameter as `--gateway-name` in the list command as well.

--gateway-name
Name of the application gateway.

--name -n
The name of the frontend IP configuration.

**Comment by askpatrickw** [comment]
No worries.. closing.
