### ISSUE TITLE
New automation variable by cli or ansible

### ISSUE THREAD

**Issue by DuongThiNgocHoa** [Azure/azure-cli#21578]
After create a runbook and edit content, I want to create variable and set value for them. How can I do it by ansible or azure cli ? Please help me

**Comment by yonzhan** [comment]
route to CXP team

**Comment by jiasli** [comment]
To help us better understand the problem, could you please share the Azure CLI command you used?

**Comment by PramodValavala-MSFT** [comment]
@DuongThiNgocHoa Unfortunately, this isn't available in Azure CLI _yet_. There is a [feature request](https://feedback.azure.com/d365community/idea/9caaa6e5-0225-ec11-b6e6-000d3a4f0858) that you could up vote to add support for them.

In the meantime, you could use the [`az rest`](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#rest-api-commands) subcommand to directly work with the [Variables REST API](https://docs.microsoft.com/en-us/rest/api/automation/variable).

Alternatively, you can use the available PowerShell cmdlets as mentioned in [Manage variables in Azure Automation doc](https://docs.microsoft.com/en-us/azure/automation/shared-resources/variables?tabs=azure-powershell).
