### ISSUE TITLE
az webapp up - with F0 - when F0 is already taken - improve error text

### ISSUE THREAD

**Issue by diberry** [Azure/azure-cli#21588]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
If I create a webapp, `az webapp up --sku F1 --name XYZ` when for whatever reason the F1 is already take or not allowed, I get an  `unauthorized` error instead of something that tells me I need to pick a different SKU.

**To Reproduce**
On internal subscription, when  F1 isn't allowed or already taken, create resource with command. Get error shown in image.

**Expected behavior**
Error indicates pricing sku as issue. 

**Environment summary**

**Additional context**

![image](https://user-images.githubusercontent.com/41597107/157739420-1400f123-c368-4ce3-8cbd-2075a6c6d07f.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by diberry** [comment]
@yonzhan - are you asking me to do that or you are doing that?

**Comment by yonzhan** [comment]
webapp related CLI commands are owned by service team, so I added CXP team to help with.

**Comment by navba-MSFT** [comment]
Since @StrawnSC from the webapp CLI team is owning this, I am removing the `CXP Attention` label from this and adding `Service attention` label.

**Comment by StrawnSC** [comment]
@diberry thanks for reporting this. Could you rerun the failing command with `--debug` and share the output? Be sure to obfuscate any nonpublic info or feel free to DM me a screenshot on teams/email

**Comment by StrawnSC** [comment]
Based on our email exchange, it seems like this issue was fixed in a recent release. Please reopen if you're still running into this bug
