### ISSUE TITLE
az aks get-credentials should not point to privatelink dns zone

### ISSUE THREAD

**Issue by weltonrodrigo** [Azure/azure-cli#21584]
## Describe the bug
```az aks get-credentials``` generate an entry on `~/.kube/config` pointing to privatelink via private zone.
Example:

```
https://my-aks-cluster-my-aks-cluster-a12345-a1234567.privatelink.<region>.azmk8s.io:443
name: my-aks-cluster
```

The correct address should be:
```
https://my-aks-cluster-my-aks-cluster-a12345-a1234567.hcp.<region>azmk8s.io
```
If I'm understanding this wrongly, maybe the documentation on https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns#on-premises-workloads-using-a-dns-forwarder should be updated.

## Environment Summary
```
macOS-11.6.3-x86_64-i386-64bit, Darwin 20.6.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.32.0 *

Extensions:
azure-devops 0.23.0
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@weltonrodrigo I could see the correct server entry in config file.  Please check below.
![image](https://user-images.githubusercontent.com/38112130/157994558-8c94c58c-3178-4560-8740-8d5339bb5363.png)
You may be getting the private link entry if your cluster is a [Private AKS](https://docs.microsoft.com/en-us/azure/aks/private-clusters).  Please verify and let us know if that's not the case.

**Comment by weltonrodrigo** [comment]
That’s the case, it’s a private cluster.

But shouldn’t private clusters get the public dns zone name? If I change the `server` url entry in kubeconfig to the public dns, I get a private IP, as expected.

At the portal, API endpoint is shown as cluster_name-resource_group-XXXXXX-XXXXXXXX.hcp.brazilsouth.azmk8s.io: 



A DNS query for that address at 1.1.1.1 results (surprisingly) in its private IP (!) .



At the internal (on-premises) DNS server, the query returns the same result, NOT the privatelink zone address. The privatelink address for that cluster is cluster_name-resource_group-XXXXXX-XXXXXXXX.privatelink.brazilsouth.azmk8s.io.

In other Azure products we have private links for, when we query the public zone at the internal server, we got a CNAME to the private zone, but with a A entry on the same response. If we query an external server like 1.1.1.1 we got an Azure IP (not ours).

To wrap up:

- External (public) DNS resolution for private clusters seems strange (unlike other azure products), leaking our private IP in a public query.
- The get-credentials command give me the private zone address, which we don’t (as per the azure documentation) have no forwarder on-premises to.
- Nonetheless, the api endpoint responds on the public zone address, which allows us to use it as long as kubeconfig is changed.

Thanks for your response.

**Comment by SaurabhSharma-MSFT** [comment]
@weltonrodrigo I am checking internally on this and get back to you. Thanks

**Comment by SaurabhSharma-MSFT** [comment]
@weltonrodrigo Can you please try using `az aks get-credentials -n <cluster> -g <rg>  --public-fqdn` ?

**Comment by weltonrodrigo** [comment]
```—public-fqdn``` gives me the public zone. Thank you.
