### ISSUE TITLE
Breaking behavior change in 2.34.1 with `az storage blob upload-batch` and `--if-unmodified-since`

### ISSUE THREAD

**Issue by digimaun** [Azure/azure-cli#21593]
**Describe the bug**
In prior CLI versions when using `az storage blob upload-batch` with precondition `--if-unmodified-since`, the CLI would not error and stop if a target file exists in the destination blob container. Instead it would continue to the next file from source and attempt to upload if the precondition check succeeds.

**To Reproduce**
`az storage blob upload-batch -s {} -d {} --account-name {} --if-unmodified-since 2018-01-01T01:01:01Z --auth-mode login  --pattern "*.json"`

**Expected behavior**
Like prior behavior....if the precondition `--if-unmodified-since` fails, the file upload is skipped, and the next file is attempted. Now the command errors and stops processing with error:

![image](https://user-images.githubusercontent.com/28658112/157791818-9f2e74b3-7c21-4a00-9242-8408b53fbf91.png)

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
duplicate with #21477

**Comment by digimaun** [comment]
> duplicate with #21477

@evelyn-ys , @yonzhan the issue linked has to do with usage of `--overwrite` and seems to be closed with an intended fix in 2.34.1. This issue I created is about honoring the pre-condition `--if-unmodified-since` which is failing in 2.34.1 and never required an `--overwrite` flag.

The first example shown here covers my use case  https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-upload-batch-examples

I'm unclear if there is a `2.34.2` hotfix coming, or what is supposed to be the new correct command usage, to upload file only if a precondition (`--if-unmodified-since`) is met.

**Comment by calvinhzy** [comment]
We will roll out the fix for next sprint. Thanks.
