### ISSUE TITLE
Failed to establish a new connection error when using command from a cron script

### ISSUE THREAD

**Issue by fairmonk** [Azure/azure-cli#21597]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
**az storage blob download** command is failing when executed from cron job. Same command executes fine if the shell script ( containing the command ) is manually executed.
The error that is displayed when running via cron is:
_**ERROR: HTTPSConnectionPool(host='mystorage.blob.core.windows.net', port=443): Max retries exceeded with url: /mycontainer/myfile.tar.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff1b7a9bcd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))**_

**To Reproduce**
create a shell script with this command:
**_#!/usr/bin/sh
 az storage blob download --account-name <account-name> --container-name <container-name> --name <file-name.tar.gz> --file /home/myuser/file-name.tar.gz --auth-mode login_**
then create a cron job to run the script. 

**Expected behavior**
The script is executed and the file download is successfull.

**Environment summary**
Ubuntu 20.04.3

**Comment by yonzhan** [comment]
storage

**Comment by fairmonk** [comment]
Problem solved. It was a proxy issue. Since cron doesn't load by default environment variables, I had to explicitly define them within script containing az storage command.
