### ISSUE TITLE
az network bastion rdp command gives - Please enter a valid Virtual Machine resource Id. with Azure CLI Bash

### ISSUE THREAD

**Issue by zapadoody** [Azure/azure-cli#21605]
Getting "Please enter a valid Virtual Machine resource Id." when running:
$ az network bastion rdp --name "mybastion" --resource-group "my-rg" --target-resource-id "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/MY-RG/providers/Microsoft.Compute/virtualMachines/myvm01'
in VSCode Bash.

Open Bash Terminal in VSCode
az login
az network bastion rdp --name "mybastion" --resource-group "my-rg" --target-resource-id "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/MY-RG/providers/Microsoft.Compute/virtualMachines/myvm01'
Response:  Please enter a valid Virtual Machine resource Id. as a response when a valid VM resource ID was provided

Open Powershell Terminal in VSCode
az login
az network bastion rdp --name "mybastion" --resource-group "my-rg" --target-resource-id "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/MY-RG/providers/Microsoft.Compute/virtualMachines/myvm01'
Response:  A RDP session is spawned

**Expected behavior**
Response:  A RDP session should be spawned

**Environment summary**
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1

**Additional context**

**Comment by navba-MSFT** [comment]
@zapadoody Apologies for the late reply. I couldn't reproduce this issue using [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) of the AzCLI. Could you please check and let me know if you are still seeing the same issue ? awaiting your reply.

**Comment by navba-MSFT** [comment]
@zapadoody I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had a chance to test again with the most recent version of AzCLI. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@zapadoody Please follow the above action plan and k tp us if it doesn't resolve the issue. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
