### ISSUE TITLE
I can not run a command with specific user and password

### ISSUE THREAD

**Issue by v-fearam** [Azure/azure-cli#21602]
I need to run a script with specific user and pass ,  like
``
az vm run-command create --name "myRunCommand" --vm-name "MyVM" --resource-group my-rg  --script "C:\temp\test.ps1"  --run-as-user "user1" --run-as-password "<runAsPassword>"
```
but I'm not able to execute, the state is always 
"executionMessage": "Script cannot be executed with specified runAsUser/runAsPassword parameters",
    "executionState": "Failed",
    "exitCode": 0,

The password must be encrypted but there is not documentation about how to do it
I tried  power shell  ConvertTo-SecureString, and it doesn't work
I need to used from bash, and I don't have idea how to do it there.

Could you help me? I need 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f04b196d-7d11-7213-f037-f12b85b19c52
* Version Independent ID: adc05d8e-b13b-134b-5f61-42aaf23666df
* Content: [az vm run-command](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm/run-command.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm/run-command.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
This looks like a service related issue. Could you send me the debug log by email ? My email address is Zhou.Xing@microsoft.com

**Comment by v-fearam** [comment]
I sent the log requested by you.

**Comment by zhoxing-ms** [comment]
In fact, this should be an error message returned by the REST service, so we need the investigation of the service team

Request URL:
```
GET /subscriptions/a012a8b0-522a-4f59-81b6-aa0361eb9387/resourceGroups/far-arcbox-bicep/providers/Microsoft.Compute/virtualMachines/ArcBox-Client/runCommands/myRunCommandFar?$expand=instanceView&api-version=2021-11-01 HTTP/1.1
```

**'x-ms-correlation-request-id': 'ddd51e9f-6be2-487d-92a5-e1cf02cc6b7f'**

**Comment by v-fearam** [comment]
Hi, let me know if there is something that I can do.
Let me know when there is any news

**Comment by navba-MSFT** [comment]
@v-fearam Apologies for the late reply. Could you please let me know if you still need assistance on this issue ? Awaiting your reply.

**Comment by v-fearam** [comment]
I moved away Azure run-command, we needed to solve the issue. We installed OpenSSH on a not standard port and execute on the context of a specific user.
You can close this ticket as not needed, but unresolved.
I think It is good to follow the topic in order to document in a proper way the functionality, and the the community is able to use the Microsoft products.

**Comment by navba-MSFT** [comment]
@v-fearam Thanks for getting back. We are sorry to hear about this. We sincerely apologize for the delay in reaching out to you. You can refer [this](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest#az-vm-run-command-create-examples) docs for more details on this command. We have taken your feedback. We will now proceed with the closure of this issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help you.

**Comment by malchowc** [comment]
I'm seeing the exact same issue, and I've noted that it is reported for the Azure Powershell library as well: [https://github.com/Azure/azure-powershell/issues/17534#issuecomment-1075509019](url)

Executing the following simple test fails when providing a 'run-as' username and password:

`az vm run-command create --name "myRunCommand" --vm-name "testvm" --resource-group "PFTestGroup" --script "Write-Host Hello World!" --run-as-password "***" --run-as-user "***"`

The following is the result (truncated) after running `az vm run-command show`:

`{ "executionMessage": "Script cannot be executed with specified runAsUser/runAsPassword parameters", "executionState": "Failed" }`

**Comment by navba-MSFT** [comment]
@malchowc Please open a new issue and share the above details in it. We would be happy to assist on that.
