### ISSUE TITLE
Azure Databricks Access Connector Resource Onboarding Request

### ISSUE THREAD

**Issue by mvvsubbu** [Azure/azure-cli#21608]
**Resource Provider**: Microsoft.Databricks

**Description of Feature or Work Requested**: We are onboarding a new resource under our namespace, we want to enable Az CLI operations for CRUD and Add/Remove Identity to the resource. 

**Minimum API Version Required**: 2022-10-01-preview

**Swagger Link** : https://github.com/Azure/azure-rest-api-specs/pull/19759

**Target Date** : 2022-10-31

**Comment by mvvsubbu** [comment]
This feature is required by Walmart

**Comment by yonzhan** [comment]
Databricks

**Comment by jsntcy** [comment]
@mvvsubbu,

- When will the swagger be merged into [public swagger repo](https://github.com/Azure/azure-rest-api-specs/)?

- What's the release phase for the service? private preview? public preview? GA?

**Comment by mvvsubbu** [comment]
- We are doing Private Preview by 5/30 
- Public Preview 
   1. System Assigned Identity Support by 6/30
   2. User Assigned Identity Support by 9/30
- Merging of Swagger to Public Repo will be done ~6/30
- For User Assigned Identity I will add new API version after 6/30 in Public Repo
- We are looking for Az CLI release by 9/30 milestone for both System Assigned and User Assigned Identities Support
- GA would be by end of the calendar year

**Comment by mvvsubbu** [comment]
We have completed milestone 1 targeted at 6/30 and published swagger for that milestone in Public Repository with API version 2022-04-01-preview: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/databricks/resource-manager/Microsoft.Databricks/preview/2022-04-01-preview

Working milestone 2 for which is targeted to be released by 10/31.

**Comment by mvvsubbu** [comment]
Can you help get this CLI released as well for 2022-04-01-preview version, we have PS already got released. So it would be good to have this released as well to be on par experience for customers.

**Comment by jsntcy** [comment]
We'll plan it in this sprint and try to release it early next month.

**Comment by jsntcy** [comment]
Close this one as this feature was supported in https://github.com/Azure/azure-cli-extensions/pull/5600

**Comment by mvvsubbu** [comment]
Thanks for helping us with onboarding Az CLI for this feature.
