### ISSUE TITLE
Host key conflict error not displayed to terminal when using `as ssh vm`

### ISSUE THREAD

**Issue by Sumtin** [Azure/azure-cli#21604]
**Describe the bug**
`az ssh vm` doesn't display host key conflict error message to console. Instead, returns to command prompt with no indication of error.

**To Reproduce**
1) Create linux VM
2) SSH to linux VM from Machine A 
3) Delete linux VM
4) Recreate linux VM ensuring it is assigned **SAME IP as machine in step 1**
5) SSH to new linux VM using `az ssh vm` command from Machine A 
6) After a pause, the command prompt will appear. No errors will be shown.
7) SSH to new linux VM using `ssh user@linuxVmIP`
8) Error about host key conflict will appear

**Expected behavior**
Would be very helpful if the host key error bubbled up to the terminal when using `az ssh vm` command.

**Environment summary**
AZ CLI on Windows 10, installed via Chocolatey.

```
{
  "azure-cli": "2.34.1",
  "azure-cli-core": "2.34.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ssh": "1.0.0"
  }
}
```

Screenshot of issue is below:
![image](https://user-images.githubusercontent.com/6676557/157888746-393f6863-a46c-4807-b0db-896314ea0942.png)

**Comment by yonzhan** [comment]
route to service team

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by jaylabell** [comment]
@zhoxing-ms Please provide an update

**Comment by zhoxing-ms** [comment]
@vthiebaut10 Could you please help take a look the `ssh vm` related issue?

**Comment by vthiebaut10** [comment]
@zhoxing-ms  @jaylabell @Sumtin That issue has been fixed in more recent versions of the extension. Try updating to the latest version and see if that solves the problem.

**Comment by jaylabell** [comment]
Thank you!
