### ISSUE TITLE
az ad sp create-for-rbac misconfigured --years value.

### ISSUE THREAD

**Issue by peangulo** [Azure/azure-cli#21609]
[Enter feedback here]
When using for example "az ad sp create-for-rbac --keyvault MyVault --cert CertName --create-cert --years 1" the command is creating a certificate with 13 months validity instead of 12 months validity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ad/sp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ad/sp.yml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli for awareness
