### ISSUE TITLE
Azure Cli for synapse is not working as expected

### ISSUE THREAD

**Issue by Sharan441** [Azure/azure-cli#21613]
I am following the below documentation to import a notebook and pipeline into synapse but getting below issue

1. it is not respecting the folder structure

https://docs.microsoft.com/en-us/cli/azure/synapse/notebook?view=azure-cli-latest#az-synapse-notebook-set

Command:
az synapse notebook import --workspace-name workspace5 --name sharan_test2  --file '@C:\\Users\\shkanduk\\SharanKandukuri\\Test\\sharan1.ipynb' --folder-path 'mainfolder/subfolder1/'

as per documentation it should deploy the file in to the folder location but the file is getting deployed at root location

2. https://docs.microsoft.com/en-us/cli/azure/synapse/pipeline?view=azure-cli-latest#az-synapse-pipeline-list
 below caoomd is erroring out
az synapse pipeline set --workspace-name testsynapseworkspace \\
  --name testpipeline --file @'path/pipeline.json'

Error:
The command failed with an unexpected error. Here is the traceback:
'properties'
Traceback (most recent call last):
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\knack/cli.py', line 231, in invoke
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/__init__.py', line 658, in execute
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/__init__.py', line 721, in _run_jobs_serially
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/__init__.py', line 692, in _run_job
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/__init__.py', line 328, in __call__
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/command_operation.py', line 121, in handler
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/command_modules/synapse/manual/operations/artifacts.py', line 82, in create_or_update_pipeline
KeyError: 'properties'

**Comment by SaurabhSharma-MSFT** [comment]
@Sharan441 Is your Synapse Workspace Git-Enabled ?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@Sharan441 Sorry for your inconvenience, it’s a bug which will be fixed in the next release (tentatively around 04-26). Also, I have provided an alternative solution over internal call.  Providing the workaround over here for others - 
```
$synapseAnalyticsResourceId = https://dev.azuresynapse.net

$workspaceName = "<your-workspace-name>"
$notebookName = "<your-notebook-name>"
$ipynbFile = "<your-notebook-path>"
$folderName = "<your-folder-name>"

# To import a notebook
$properties = Get-Content $ipynbFile -Raw
$properties = $properties.Substring(1,$properties.Length-2)

$body = "{""name"":""${notebookName}"",""properties"": {""folder"":{""name"":""${folderName}""}, ${properties}}}"
$body | Out-File body.json
az rest --resource $synapseAnalyticsResourceId --method PUT --url https://${workspaceName}.dev.azuresynapse.net/notebooks/${notebookName}?api-version=2019-06-01-preview --body `@body.json
```
We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
