### ISSUE TITLE
Invalid range of values for `max-interval` and `max-staleness-prefix`

### ISSUE THREAD

**Issue by Rashair** [Azure/azure-cli#21617]
It's stated that the range of values for `max-interval` is [1, 100], whereas it's actually  [5, 86400] seconds.
Simirarily, with `max-staleness-prefix` - it's [1, 2147483647], whereas it's actually  [10, 1000000].

![image](https://user-images.githubusercontent.com/33404585/158015077-443b2e06-ffa6-4f1c-9e1d-c899003ab4bb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc8d652-2eda-296f-28ea-8d5f1ea855b3
* Version Independent ID: 80b87995-d339-61e9-1cac-b5c9ad6efe5e
* Content: [az cosmosdb](https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/cosmosdb.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/cosmosdb.yml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@Rashair Thanks for reaching out to us and reporting this issue. The above PR has been filed to address this issue and it is currently in the review phase. In the meantime, if you have any questions, please feel free to ask.
