### ISSUE TITLE
generate-sas generate useless SAS if permission and expiry are not given. 

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#2161]
The only required parameters in blob generate-sas command are container name and blob name. When other parameters are omitted, the result is useless. The SAS token can do nothing because neither permission or expiry are represented in the token.

Recommendation, have default permission or expiry set to the token.

**Comment by tjprescott** [comment]
Talk to the folks in storage because I believe you can generate a SAS token using an ACL entry, in which case the expiry and permissions may be tied to that.

**Comment by tjprescott** [comment]
If you specify --policy-name you can link to a stored access policy which can already have set permissions and/or expiry. Perhaps we should have a validator that either the policy or the other things are specified... although I believe you could point to a SAP that DOESN'T specify those things and would still have to provide them.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
