### ISSUE TITLE
socket-timeout missing from az storage blob upload

### ISSUE THREAD

**Issue by marcurdy** [Azure/azure-cli#21611]
I have a failure on a regular script showing me that --socket-timeout is no longer available under az storage blob upload. Upon running az storage blob -h, I do not see it. The documentation for this command shows it still valid. I'm running 2.34.1.

Thanks.

**Comment by yonzhan** [comment]
storage

**Comment by calvinhzy** [comment]
This argument has been deprecated in track2 sdk. Thanks.

**Comment by bassarisse** [comment]
What should we use now? I can't find documentation about this change anywhere, and we have several uploads failing =/

**Comment by calvinhzy** [comment]
SDK supports a separate parameter, will update this in the next release, thanks.

**Comment by calvinhzy** [comment]
> What should we use now? I can't find documentation about this change anywhere, and we have several uploads failing =/

Please try this new build 
Download:
https://artprodcus3.artifacts.visualstudio.com/A0fb41ef4-5012-48a9-bf39-4ee3de03ee35/29ec6040-b234-4e31-b139-33dc4287b756/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2F6dXJlLXNkay9wcm9qZWN0SWQvMjllYzYwNDAtYjIzNC00ZTMxLWIxMzktMzNkYzQyODdiNzU2L2J1aWxkSWQvMTY5MzM0Mi9hcnRpZmFjdE5hbWUvcHlwaQ2/content?format=zip

Extract and install the three whl files 
![image](https://user-images.githubusercontent.com/17182306/177912245-018a1a1c-9958-4bc2-9f90-df54208700a3.png)

It the parameter is not functional, please let me know.
