### ISSUE TITLE
g

### ISSUE THREAD

**Issue by me1221** [Azure/azure-cli#21624]
## Describe the bug

**Command Name**
`Unknown`

**Errors:**
```
'get--resource' is misspelled or not recognized by the system.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az get--resource`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.33.1 *

Extensions:
account 0.2.2
ai-examples 0.2.5
arcdata 1.2.0
fzf 1.0.2
init 0.1.0
interactive 0.4.5
next 0.1.2
redisenterprise 0.1.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
Please provide detailed CLI command
