### ISSUE TITLE
Import Python package for Automation account

### ISSUE THREAD

**Issue by DuongThiNgocHoa** [Azure/azure-cli#21628]
Now i want to use ansible to import Python package when i have manual downloaded. 

![image](https://user-images.githubusercontent.com/49944383/158121643-f6df6af6-5a29-4186-81c3-655a06f05de1.png)

How to do it by power shell or cli or ansible ? Thanks

**Comment by yonzhan** [comment]
Please open this issue in ansible repo, thanks
