### ISSUE TITLE
error login without different account 

### ISSUE THREAD

**Issue by edixred** [Azure/azure-cli#21620]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login -u {} -p {}`

## Environment Summary
```
Linux-5.4.0-104-generic-x86_64-with-debian-bullseye-sid, Linux Mint 20.1
Python 3.6.10
Installer: DEB

azure-cli 2.33.1 *

Extensions:
ssh 1.0.0
interactive 0.4.5

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Please share more detail for us to troubleshoot.
