### ISSUE TITLE
Microsoft.CognitiveServices, Keep "Registering" / "Unregistering", so that cannot create related services and cannot resolve

### ISSUE THREAD

**Issue by RaymondTang** [Azure/azure-cli#21632]
Because "Microsoft.CognitiveServices" keep "Registering", so that I cannot create Bot Services about it.

Used "Get-AzResourceProvider -ProviderNamespace Microsoft.CognitiveServices", there had 15 ResourceTypes that related to CognitiveServices.

But I tried to "Unregister-AzResourceProvider -ProviderNamespace "Microsoft.CognitiveServices" or "Register-AzResourceProvider -ProviderNamespace "Microsoft.CognitiveServices", still "Registering" and "Unrregistering" for long time, and nothing changed.

Could someone help on this?

Thanks a lot!

**Comment by yonzhan** [comment]
Please open this issue in Azure PowerShell repo

**Comment by RaymondTang** [comment]
> Please open this issue in Azure PowerShell repo

Thanks so much!
