### ISSUE TITLE
az functionapp config appsettings set fails to update broken keyvault reference

### ISSUE THREAD

**Issue by CorrenSoft** [Azure/azure-cli#21634]
**Describe the bug**
The '_az functionapp config appsettings set_' command fails to update a setting when the current value is a broken key vault reference with **Error: None** message.

**To Reproduce**
- Add a setting with a key vault reference with the format @Microsoft.KeyVault(VaultName=<kv Name>;SecretName=<secret name>)
- Restart the function and check that the reference gets resolved.
- Delete the secret from the key vault, restart the function and check the reference status (should be unresolved).
- Run the command to update the setting with a plain text value (does not matter if the new value is another key vault reference or just plain text).

**Expected behavior**
The Setting value should be updated (at least if the new value is valid).

**Environment summary**
az CLI version 2.34.1 (Windows and Linux)

**Additional context**
- Fails on individual or multiple assignments, as long as the broken reference is one of the values intended to update.
- The current workaround is to delete the existing broken setting first and then set the new value.
- I could not verify the same behavior happens when the reference is not resolved for other reason than a nonexisting secret, but I think that is possible.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@CorrenSoft Thanks for reaching out to us. I used the below command to create and update the KeyVault reference in config appsettings. I tried with both existing and non-existing keyvault references. Could you please test the same and let us know if you face any issues?

```
----CLI Command START----
az functionapp config appsettings set --name [my-app-name] --resource-group [my-app-res-group] --settings `""PublicKey=@Microsoft.KeyVault(VaultName=[vault-name];SecretName=[secret-name])"`"
----CLI Command END----
```
Also if you still face the issue, could you please provide me more information about the _reference status_ and _broken reference_? I am not sure if I understood it quite right. Awaiting your reply.

**Comment by CorrenSoft** [comment]
We had a setting with a key vault reference in place, but after a review, we decided that the value was not sensitive and decided to change it to plain text format. So, in the CI/CD process, we deleted the secret from the key vault and then tried to update the setting, but the command failed each time until we actually deleted the setting.
Today, I rebuilt the same scenario as yesterday, and I get the error again one time, and then start to work, and I could not reproduce it again. The very same command that was failing now is working. Could be another issue platform-related?

Thanks for your time, if you can not reproduce the error in the described scenario I think that you can close this, and I will be back if the issue returns in the future.

**Comment by navba-MSFT** [comment]
@CorrenSoft unlikely a platform issue. If you are consistently able to reproduce the issue, please feel free to reopen this thread. We would be happy to work with you with on this again.
