### ISSUE TITLE
How to specify the storage account and container when using az webapp log config with azureblobstorage option? 

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-cli#21633]
When using  [az webapp log config](https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#az-webapp-log-config)   --application-logging azureblobstorage ...

How do you specify:

1. The storage account to be used?
2. The storage container to be used?

When using the Azure Portal and setting the **Application logging (Blob)** option to **On** -- the portal allows you to select a **storage account** and **container name** -- Is there any way to do this via the CLI?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bee2e287-5fb7-a849-9d3b-87013b783f16
* Version Independent ID: 97f9e1c4-1573-b776-0fce-53c65839d713
* Content: [az webapp log](https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#commands)
* Content Source: [latest/docs-ref-autogen/webapp/log.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/log.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
Hello @bdcoder2 Thanks for the query. I hope the below steps will unblock with initial query.

Pre-Req: Generate the SAS URL of the storage Container:

First Set\Update the Log config by using the below command:

`az resource update --ids "/subscriptions/4fb-b5ba-2b83a124dr567hu/resourceGroups/mYResources/providers/Microsoft.Web/sites/WebApplication120/config/logs" --set properties.applicationLogs.azureBlobStorage.sasUrl="https://strgacc.blob.core.windows.net/delcontainer?sp=racwdl&st=2022-03-15T05:59:03Z&se=2022-03-16T13:59:03Z&spr=https&sv=2020-08-04&sr=c&sig=bwWlln3sSh9S2U4rJi7mzmQBA3%2F2Egx%2B11wtk066Xq4%3D`


Now run the log config command:

`az webapp log config --name WebApplication120 --resource-group mYResources --application-logging azureblobstorage --level error`

**Comment by bdcoder2** [comment]
@SatishBoddu-MSFT - Almost -- can you expand on where the "?sp=racwdl&st=2022-03-15T05:59:03Z" comes from?

Thanks

**Comment by SatishBoddu-MSFT** [comment]
> @SatishBoddu-MSFT Satish Boddu FTE - Almost -- can you expand on where the "?sp=racwdl&st=2022-03-15T05:59:03Z" comes from?
> 
> Thanks

```
$sas = az storage container generate-sas --account-name mystorageaccount --expiry 2022-01-01 --name mycontainer --permissions dlrw
$sasUrl = 'https://mystorageaccount.blob.core.windows.net/mycontainer?' + $sas.Trim('"')


$logConfigResourceId = az webapp log show --name MyWebApp --resource-group MyResourceGroup --query 'id' -o json

az resource update --ids $logConfigResourceId --set properties.applicationLogs.azureBlobStorage.sasUrl=$sasUrl,properties.httpLogs.azureBlobStorage.sasUrl=$sasUrl,properties.httpLogs.azureBlobStorage.enabled=true

az webapp log config --name WebApplication120 --resource-group mYResources --application-logging azureblobstorage --level error
```

Please try the above one!

**Comment by bdcoder2** [comment]
@SatishBoddu-MSFT - no go, the "az resource update" blows up with:

`Couldn't find 'applicationLogs' in 'properties.applicationLogs'. Available options: ['adminEnabled', 'availabilityState', 'buildVersion', 'cers', 'clientAffinityEnabled', 'clientCertEnabled', 'clientCertExclusionPaths', 'clientCertMode', 'cloningInfo', 'computeMode', 'containerSize', 'contentAvailabilityState', 'csrs', 'customDomainVerificationId', 'dailyMemoryTimeQuota', 'defaultHostName', 'deploymentId', 'domainVerificationIdentifiers', 'eligibleLogCategories', 'enabled', 'enabledHostNames', 'ftpUsername', 'ftpsHostName', 'functionExecutionUnitsCache', 'geoDistributions', 'homeStamp', 'hostNameSslStates', 'hostNames', 'hostNamesDisabled', 'hostingEnvironment', 'hostingEnvironmentId', 'hostingEnvironmentProfile', 'httpsOnly', 'hyperV', 'inProgressOperationId', 'inboundIpAddress', 'isXenon', 'keyVaultReferenceIdentity', 'kind', 'lastModifiedTimeUtc', 'maxNumberOfWorkers', 'migrationState', 'name', 'outboundIpAddresses', 'owner', 'possibleInboundIpAddresses', 'possibleOutboundIpAddresses', 'privateEndpointConnections', 'redundancyMode', 'repositorySiteName', 'reserved', 'resourceGroup', 'runtimeAvailabilityState', 'scmSiteAlsoStopped', 'selfLink', 'serverFarm', 'serverFarmId', 'siteConfig', 'siteDisabledReason', 'siteMode', 'siteProperties', 'sku', 'slotName', 'slotSwapStatus', 'sslCertificates', 'state', 'storageAccountRequired', 'storageRecoveryDefaultState', 'suspendedTill', 'tags', 'targetBuildVersion', 'targetSwapSlot', 'trafficManagerHostNames', 'usageState', 'virtualNetworkSubnetId', 'webSpace']`

**Comment by SatishBoddu-MSFT** [comment]
Ok, I have run the command once again, no errors on my side.

![image](https://user-images.githubusercontent.com/62923178/158480145-2edd692c-503d-48dd-bc70-f128950248ac.png)

**Comment by bdcoder2** [comment]
@SatishBoddu-MSFT - Thanks - and apologies, I missed the "/config/log" portion in the the script.

For those that stumble here - the complete script to create an App Service that uses a blob storage container for logging is:

@SatishBoddu-MSFT - if you spot anything that can be improved upon, please do ...  Thanks again !!!

```
# Set as needed ...

location_name=<location-name> 

resource_group_name=<your-resource-group-name>

web_app_name=<your-app-name>

storage_account_name=<your-storage-account-name>

container_name=<your-container-name>

expiry_date=$( date -d "+1 days" +"%Y-%m-%dT%H:%MZ" )


# Create the resource group ...

az group create \
   --location $location_name \
   --name $resource_group_name


# Create an App Service plan in Free tier ...

az appservice plan create \
   --name $web_app_name \
   --resource-group $resource_group_name \
   --sku F1


# Create the web app ...

az webapp create \
   --name $web_app_name \
   --resource-group $resource_group_name \
   --plan $web_app_name


# Create storage account ...

az storage account create \
   --name $storage_account_name \
   --resource-group $resource_group_name \
   --location $location_name \
   --sku Standard_LRS


# Get storage account key ...

storage_account_key=$( az storage account keys list \
   --resource-group $resource_group_name \
   --account-name $storage_account_name \
   --query "[0].value" \
   --output tsv )


# Create container ...

az storage container create \
 --name $container_name \
 --resource-group $resource_group_name \
 --account-name $storage_account_name \
 --account-key $storage_account_key


# Get storage account blob endpoint ...

blob_endpoint=$( az storage account show \
   --resource-group $resource_group_name \
   --name $storage_account_name \
   --query "primaryEndpoints.blob" \
   --output tsv )


# Generate a SAS token for a storage container. ...

sas_token=$( az storage container generate-sas \
   --account-name $storage_account_name \
   --name $container_name \
   --permissions rwdl \
   --expiry $expiry_date \
   --account-key $storage_account_key \
   --output tsv )

# Build SAS URL ...

sas_url="$blob_endpoint$container_name?$sas_token"


# Get ID of web app ...

webapp_id=$(az webapp list \
  --resource-group $resource_group_name \
  --query "[0].id" \
  --output tsv )

webapp_id="$webapp_id/config/logs"


# Configure web app logs ...

props="properties.applicationLogs.azureBlobStorage.sasUrl=$sas_url,"
props+="properties.httpLogs.azureBlobStorage.sasUrl=$sas_url,"
props+="properties.httpLogs.azureBlobStorage.enabled=true"

az resource update \
   --ids $webapp_id \
   --set $props


# Configure logging ...

az webapp log config \
   --name $web_app_name \
   --resource-group $resource_group_name \
   --application-logging azureblobstorage \
   --level error

```

**Comment by bdcoder2** [comment]
@SatishBoddu-MSFT - Sorry, one other question if I may:

Where do I find the documentation regarding the "properties"?, i.e.:

- "properties.applicationLogs.azureBlobStorage.sasUrl"
- "properties.httpLogs.azureBlobStorage.sasUrl"
- "properties.httpLogs.azureBlobStorage.enabled"

Thank-you so much -- again !!

**Comment by SatishBoddu-MSFT** [comment]
Hello @bdcoder2

Please refer to the below doc:

[az resource update](https://docs.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#az-resource-update)

`az resource update --ids $id --set properties.connectionType=Proxy`

**Comment by bdcoder2** [comment]
Hi @SatishBoddu-MSFT -- yes, but I guess I was asking where is the list of **property paths**?   Is there a list of property paths for the various resources?   For example, where would I find the "properties.applicationLogs.azureBlobStorage.sasUrl" property path or even know that was the path to use?  (for newbies such as myself, there is no way I would ever know to include that path in the command had it not been for you coming to the rescue !!

**Comment by SatishBoddu-MSFT** [comment]
Oh yeah , here we are, try this to fetch the available props

`az webapp log show --name WebApplication120220311071911 --resource-group MyRG`
![image](https://user-images.githubusercontent.com/62923178/158484309-e269332e-8528-4f5c-8646-b5808fc7bde8.png)

**Comment by bdcoder2** [comment]
AH, I see now -- the property path corresponds to the JSON path as per your example !! -- who knew!?

@SatishBoddu-MSFT - You are the master !!   

Hopefully, I shouldn't have to bother you again; at least not for a while ;)
