### ISSUE TITLE
Cannot delete subnet with serviceAssociationLinks which cannot be deleted.

### ISSUE THREAD

**Issue by askpatrickw** [Azure/azure-cli#21637]
## Describe the bug

This subnet was used by PowerBI and cannot be deleted, we cannot set the serviceAssociationLinks to None in the portal either.
The PowerBI objects have already been deleted.

```json
[
  {
    "addressPrefix": "10.0.0.0/24",
    "addressPrefixes": null,
    "applicationGatewayIpConfigurations": null,
    "delegations": [
      {
        "actions": [
          "Microsoft.Network/virtualNetworks/subnets/join/action"
        ],
        "etag": "W/\"<snip>\"",
        "id": "/subscriptions/<snip>/resourceGroups/Pilot/providers/Microsoft.Network/virtualNetworks/power-bi-virtual-network/subnets/default/delegations/Microsoft.PowerPlatform.vnetaccesslinks",
        "name": "Microsoft.PowerPlatform.vnetaccesslinks",
        "provisioningState": "Succeeded",
        "resourceGroup": "Pilot",
        "serviceName": "Microsoft.PowerPlatform/vnetaccesslinks",
        "type": "Microsoft.Network/virtualNetworks/subnets/delegations"
      }
    ],
    "etag": "W/\"<snip>\"",
    "id": "/subscriptions/<snip>/resourceGroups/Pilot/providers/Microsoft.Network/virtualNetworks/power-bi-virtual-network/subnets/default",
    "ipAllocations": null,
    "ipConfigurationProfiles": null,
    "ipConfigurations": null,
    "name": "default",
    "natGateway": null,
    "networkSecurityGroup": null,
    "privateEndpointNetworkPolicies": "Enabled",
    "privateEndpoints": null,
    "privateLinkServiceNetworkPolicies": "Enabled",
    "provisioningState": "Succeeded",
    "purpose": null,
    "resourceGroup": "Pilot",
    "resourceNavigationLinks": null,
    "routeTable": null,
    "serviceAssociationLinks": [
      {
        "allowDelete": false,
        "etag": "W/\"<snip>\"",
        "id": "/subscriptions/<snip>/resourceGroups/pilot/providers/Microsoft.Network/virtualNetworks/power-bi-virtual-network/subnets/default/serviceAssociationLinks/PowerPlatformSAL",
        "link": null,
        "linkedResourceType": "Microsoft.PowerPlatform/vnetaccesslinks",
        "locations": [],
        "name": "PowerPlatformSAL",
        "provisioningState": "Succeeded",
        "resourceGroup": "pilot",
        "type": "Microsoft.Network/virtualNetworks/subnets/serviceAssociationLinks"
      }
    ],
    "serviceEndpointPolicies": null,
    "serviceEndpoints": [],
    "type": "Microsoft.Network/virtualNetworks/subnets"
  }
]
```

**Command Name**
`az network vnet subnet delete`

**Errors:**
```
(InUseSubnetCannotBeDeleted) Subnet default is in use by /subscriptions/<snip>/resourceGroups/pilot/providers/Microsoft.Network/virtualNetworks/power-bi-virtual-network/subnets/default/serviceAssociationLinks/PowerPlatformSAL and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.
Code: InUseSubnetCannotBeDeleted
Message: Subnet default is in use by /subscriptions/<snip>/resourceGroups/pilot/providers/Microsoft.Network/virtualNetworks/power-bi-virtual-network/subnets/default/serviceAssociationLinks/PowerPlatformSAL and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.

```

## To Reproduce:
See other context...

- _Put any pre-requisite steps here..._
- `az network vnet subnet delete --ids {}`

## Expected Behavior

Delete Subnet

## Environment Summary
```
macOS-12.2-arm64-arm-64bit, Darwin 21.3.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1

Extensions:
azure-iot 0.13.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```
## Additional Context

This has been a known issue for some time, as seen here: https://github.com/MicrosoftDocs/azure-docs/issues/48902
But that issue was closed without a fix or any communication to users as to a status or what to do.

**Comment by yonzhan** [comment]
network

**Comment by YuanyuanNi** [comment]
Hi:
    @askpatrickw  As the error info shows :Subnet default is in use by PowerPlatformSAL and if you want to delete the subnet, you should delete all resources related with the subnet first.
Best wishes.

**Comment by askpatrickw** [comment]
This should be reopened.

@YuanyuanNi, @kairu-ms , @yonzhan there are NO resources in this subscription but this one virtual network and the one subnet which cannot be deleted due to the orphaned serviceAssociationLinks. 

This appears to be a known issue (with no open issue) since 2020.

https://learn.microsoft.com/en-us/answers/questions/140197/unable-to-delete-vnet-due-to-serviceassociationlin

**Comment by mischa69** [comment]
same problem

**Comment by fdonnet** [comment]
Same here with a postgres resource I took 2 weeks to delete... stuck in a bad state... and now I cannot delete the subnet association link that exists for an already deleted resource... cannot delete the vnet or subnet or resource grp

**Comment by brad-dawson** [comment]
Stuck here as well because of a "Microsoft.DBforMySQL/flexibleServers". It seems to me like the bug is that the `properties.link` is null and or not set in the properties object so Azure won't allow it to delete. I tried updating the resource to add this back in with `az resource update --ids /subscriptions/... --set properties.link="/subscriptions..."` but I was returned the error "(UnauthorizedClientApplication) Unauthorized client application id".

**Comment by fdonnet** [comment]
@brad-dawson  I took one month support to be able to contact Azure support and after 2 weeks they were able to remove this ghost resource for me...

**Comment by mierea** [comment]
Just in case someone else has this issue:

my serviceAssociationLinks was looking like
```
/subscriptions/<subid>/resourceGroups/<rg>/providers/Microsoft.Network/virtualNetworks/<vnet>/subnets/<sn>/serviceAssociationLinks/acisal
```

in the delete command instead of using acisal i had to use default then it worked:

```
az resource delete `
  --ids "/subscriptions/<sub id>/resourceGroups/<rg>/providers/Microsoft.Network/virtualNetworks/<vnet>/subnets/<subnet>/serviceAssociationLinks/default" `
   --api-version 2023-11-01 `
  --verbose
```
or 

```
az rest --method delete --uri https://management.azure.com/subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.Network/virtualNetworks/<vnet>/subnets/<subnet>/providers/Microsoft.ContainerInstance/serviceAssociationLinks/default?api-version=2017-12-01-preview
```

if you run it from bashj replace ` with \
