### ISSUE TITLE
Unable to turn off autoinflate from CLI using 

### ISSUE THREAD

**Issue by assures** [Azure/azure-cli#21654]
The below command from cloudshell doesn't disable auto inflate. I run this, it executes with no error. But later I see the properties, and isAutoInflateEnabled is still True.

**az eventhubs namespace update --resource-group Default-EventHub-EastUS --name assures-autoinflissue --subscription e8baea74-64ce-459b-bee3-5aa4c47b3ae3 --enable-auto-inflate false**

After the command, run the below command to see if it is updated.

**az eventhubs namespace show --resource-group kafkanovfetchlatency --name kafkanodejsissue --subscription e8baea74-64ce-459b-bee3-5aa4c47b3ae3**
{
"clusterArmId": null,
"createdAt": "2021-11-30T18:12:08.920000+00:00",
"disableLocalAuth": false,
"encryption": null,
"id": "/subscriptions/e8baea74-64ce-459b-bee3-5aa4c47b3ae3/resourceGroups/kafkanovfetchlatency/providers/Microsoft.EventHub/namespaces/kafkanodejsissue",
"identity": null,
**"isAutoInflateEnabled": true,**
"kafkaEnabled": true,
"location": "West US",
"maximumThroughputUnits": 3,
"metricId": "e8baea74-64ce-459b-bee3-5aa4c47b3ae3:kafkanodejsissue",
"name": "kafkanodejsissue",
"privateEndpointConnections": null,
"provisioningState": "Succeeded",
"resourceGroup": "kafkanovfetchlatency",
"serviceBusEndpoint": "[https://kafkanodejsissue.servicebus.windows.net:443/"](https://kafkanodejsissue.servicebus.windows.net/%22),
"sku": {
"capacity": 2,
"name": "Standard",
"tier": "Standard"
},
"status": "Active",
"systemData": null,
"tags": {},
"type": "Microsoft.EventHub/Namespaces",
"updatedAt": "2022-03-15T00:47:52.347000+00:00",
"zoneRedundant": false
}

**To Reproduce**
1. Create an EventHubs namespace with current capacity as 1 TU, autoInflate enabled, set max capacity as 2 or higher.
2. Run this command from cloudshell 
**az eventhubs namespace update --resource-group Default-EventHub-EastUS --name assures-autoinflissue --subscription <subscription-id> --enable-auto-inflate false**
**Expected behavior**
isAutoInflateEnabled": false 

the above is expected. But it is always true.

**Additional context**
The issue is only for disabling, an enabling command works fine if we supply max capacity value along with it.
I have checked the debug logs with the command, and the request to RP is sending True, despite me supplying false. debug logs from cloudshell is attached: [debug (1).txt](https://github.com/Azure/azure-cli/files/8258210/debug.1.txt)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@assures Thanks for reaching out to us and sharing this feedback. We are looking into this issue and we will update this once we have more details on this.

**Comment by navba-MSFT** [comment]
@assures I have reached out to Product Owners and they have confirmed that this is a known issue. We will keep you posted about the ETA for the fix.

**Comment by assures** [comment]
@navba-MSFT Thanks for the update

**Comment by navba-MSFT** [comment]
@assures The above PR has been filed and that should fix this issue. In the meantime, Please let me know if you have any questions. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@assures The PR https://github.com/Azure/azure-cli/pull/21816 is now merged and has the fix for this issue. Thanks for reporting this issue and providing the feedback. We will now proceed with closure. If you have any further questions on this, please reopen this issue. We would be happy to help.
