### ISSUE TITLE
Exception while creating an azure container app with dapr components

### ISSUE THREAD

**Issue by ShafeerAli** [Azure/azure-cli#21659]
## Describe the bug

**Command Name**
`az extension update`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az extension update -n {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1

Extensions:
aro 1.0.0
containerapp 0.2.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@ShafeerAli Can you please share the exception details?

**Comment by ShafeerAli** [comment]
@SaurabhSharma-MSFT created another issue with proper details pls refer to
https://github.com/Azure/azure-cli/issues/20862

**Comment by SaurabhSharma-MSFT** [comment]
@ShafeerAli Thanks. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
