### ISSUE TITLE
Exclude files/folders form upload when using az ml job create --file xyz.yml

### ISSUE THREAD

**Issue by Mahelita** [Azure/azure-cli#21664]
**Is your feature request related to a problem? Please describe.**
Because of internal legacy and dependencies, some large files are included in the local path. These files should not be uploaded to the azure ML workspace when submitting a job to azure ML using a yml file. Unfortunately, I did not find a way to specify files/folders to exclude from upload.

**Describe the solution you'd like**
Possibility to specify files/folders to exclude from upload to the azure ML workspace.

**Describe alternatives you've considered**
Currently I am duplicating the folder to be uploaded and removing unnecessary files.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@Mahelita Could you please share examples of unnecessary files (include screenshots if possible) which are getting included in the path ?

**Comment by SaurabhSharma-MSFT** [comment]
@Mahelita Please let me know if you need any help on this.

**Comment by SaurabhSharma-MSFT** [comment]
@Mahelita We will now proceed to close this thread as we have not heard back. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by Mahelita** [comment]
I have been pointed to the solution by a MS support engineer!
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-save-write-experiment-files#where-to-save-input-files
Simply specify the files to ignore in a .gitignore or .amlignore file :-)
