### ISSUE TITLE
CLI for SecurityInsights based on 2022-01-01-preview (with codegen)

### ISSUE THREAD

**Issue by anat-gilenson** [Azure/azure-cli#21665]
**Resource Provider**

SecurityInsights

**Description of Feature or Work Requested**

Update CLI to be based on latest API preview version, which includes latest features

**Minimum API Version Required**

2022-01-01-preview

**Swagger Link**

[https://github.com/Azure/azure-rest-api-specs/tree/main/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2022-01-01-preview](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2022-01-01-preview)

**Target Date**

End of June.

**Comment by necusjz** [comment]
@anat-gilenson, I saw there is a new swagger specs merged with 2022-04-01-preview.

Do you think we should adapt to the latest version, or keep adapting to 2022-01-01-preview?

**Comment by anat-gilenson** [comment]
> @anat-gilenson, I saw there is a new swagger specs merged with 2022-04-01-preview.
> 
> Do you think we should adapt to the latest version, or keep adapting to 2022-01-01-preview?

Yes, that would be better as it contains more features.
Thank you!

**Comment by necusjz** [comment]
@anat-gilenson, no problem : )

Another question is about the module status, I saw the current status is *Experimental*:
![image](https://user-images.githubusercontent.com/12371639/165879120-d4dd11b0-72a1-40e1-8e19-40ce41dfe92a.png)

For this time, will we keep it or choose some others? You can check this link: https://docs.microsoft.com/en-us/cli/azure/reference-types-and-status#what-is-reference-status for more details.

**Comment by anat-gilenson** [comment]
@necusjz Best to keep it experimental. Thanks!
