### ISSUE TITLE
Error running az webapp config appsettings list command

### ISSUE THREAD

**Issue by sgiddings-kunzleigh** [Azure/azure-cli#21669]
## Describe the bug
I am unable to run the az webapp config appsettings list command to generate current app settings on a web app.

**Command Name**
`az webapp config appsettings list --name web-app --resource-group resource-group`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'4'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 236, in invoke
    formatter = self.output.get_formatter(output_type)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/knack/output.py", line 166, in get_formatter
    return OutputProducer._FORMAT_DICT[format_type]
KeyError: '4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
- `az webapp config appsettings list --name web-app --resource-group resource-group`

## Expected Behavior
Expected it to output a list (probably JSON formatted) of current app settings set on a web app.

## Environment Summary
```
macOS-12.3-x86_64-i386-64bit, Darwin 21.4.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1

Extensions:
resource-graph 2.1.0
ssh 0.1.8
interactive 0.4.5

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@sgiddings-kunzleigh Thanks for reaching out to us. I was able to run the above command and it worked. Could you please install the Azure CLI from [this](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos) link and test it again ? Alternatively, could you also test the same command from the cloud shell [TryIT](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#code-try-3) option? Awaiting your reply.

**Comment by sgiddings-kunzleigh** [comment]
Hello @navba-MSFT,

I tried the same command in the Azure Cloud shell and it worked without issue. Is this potentially an issue from the Homebrew install on macOS then? I looked at the MS Docs page but it just asks me to install the Azure CLI via Homebrew, which is how I have it installed currently.

**Comment by sgiddings-kunzleigh** [comment]
I got it working locally. I had to uninstall `azure-cli` via Homebrew, `rm -rf ~/.azure` directory, and reinstall `azure-cli` via Homebrew. I believe upgrading certbot screwed it up because it changed the Python dependency.
