### ISSUE TITLE
Add redirectURI for single page application deployment in azure using Microsoft Graph API and Az rest command.

### ISSUE THREAD

**Issue by abi-kannan** [Azure/azure-cli#21668]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Get error in deployment when adding SPA redirectURIs using microsoft Graph API.
command used:
az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/<APP REG OBJECT ID>' --headers 'Content-Type=application/json' --body '{"spa":{"redirectUris":["https:<APP DOMAIN>"]}}'
error:
##[error]WARNING: The underlying Active Directory Graph API will be replaced by Microsoft Graph API in a future version of Azure CLI. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration

this is causing the deployment to fail. I get this error intermittently. 

**To Reproduce**
Add redirecturi to single page application using az command and deploy using azure devops pipeline.  

**Expected behavior**
I am already using Microsoft Graph DB and redirectURIs instead of replyurl as mentioned in error. So I except  deployment should completed without any warnings and error.

**Environment summary**
I am deploying using azure devops and default az version.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
> WARNING: The underlying Active Directory Graph API will be replaced by Microsoft Graph API in a future version of Azure CLI. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration

This warning is only added for `az ad` and `az role` commands (https://github.com/Azure/azure-cli/pull/21302). The warning won't be shown for `az rest`. It is also only a warning, not an error.

If you see any error with `az rest`, please share the corresponding error message.

`spa` support in `az ad app create/update` is currently not included in the Microsoft Graph migration:

 - https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0
 - https://github.com/Azure/azure-cli/issues/12946

We will consider this as a feature request.

**Comment by jiasli** [comment]
> 👍 for `spa` support request.

Tracked by https://github.com/Azure/azure-cli/issues/14880
