### ISSUE TITLE
ERROR: Invalid challenge parameters 

### ISSUE THREAD

**Issue by v-smeadows** [Azure/azure-cli#21670]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
$ az version
{
  "azure-cli": "2.34.1",
  "azure-cli-core": "2.34.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-iot": "0.10.13",
    "costmanagement": "0.1.1"
  }
}

$ az keyvault secret list --vault-name kvcnspsqldev-1 --verbose
**ERROR: Invalid challenge parameters**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**
Works in Cloud Shell, does not work in CLI

**Comment by yonzhan** [comment]
keyvault

**Comment by v-smeadows** [comment]
I'm not sure what the process is. This is my first time submitting.  What should I expect/do next?

**Comment by evelyn-ys** [comment]
Can you share the debug log with `az keyvault secret list --vault-name kvcnspsqldev-1 --debug`?

**Comment by v-smeadows** [comment]
$ az keyvault secret list --vault-name kvcnspsqldev-1 --debug
DEBUG: cli.knack.cli: Command arguments: ['keyvault', 'secret', 'list', '--vault-name', 'kvcnspsqldev-1', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x02285190>, <function OutputProducer.on_global_arguments at 0x02301028>, <function CLIQuery.on_global_arguments at 0x02418BB0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'keyvault': ['azure.cli.command_modules.keyvault']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: keyvault                  0.013        20       122
DEBUG: cli.azure.cli.core: Total (1)                 0.013        20       122
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0
DEBUG: cli.azure.cli.core: Loaded 20 groups, 122 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : keyvault secret list
DEBUG: cli.azure.cli.core: Command table: keyvault secret list
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03EEA898>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\jhines\.azure\commands\2022-03-17.06-43-57.keyvault_secret_list.27856.log'.
INFO: az_command_data_logger: command args: keyvault secret list --vault-name {} --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03F3D460>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03F3D4F0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03F96610>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x02301070>, <function CLIQuery.handle_query_parameter at 0x02418BF8>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03F965C8>]
DEBUG: msrest.universal_http.requests: Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
DEBUG: msrest.async_paging: Paging async iterator protocol is not available for SecretItemPaged
DEBUG: msrest.service_client: Accept header absent and forced to application/json
DEBUG: msrest.universal_http: Configuring redirects: allow=True, max=30
DEBUG: msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
DEBUG: msrest.universal_http: Configuring proxies: ''
DEBUG: msrest.universal_http: Evaluate proxies against ENV settings: True
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): kvcnspsqldev-1.vault.usgovcloudapi.net:443
DEBUG: urllib3.connectionpool: [https://kvcnspsqldev-1.vault.usgovcloudapi.net:443](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fkvcnspsqldev-1.vault.usgovcloudapi.net%2F&data=04%7C01%7Cv-smeadows%40microsoftsupport.com%7C08067b4a99394ee4544308da080342a1%7Cb4c546a47dac46a6a7dded822a11efd3%7C0%7C0%7C637831107347782203%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ada8HEw%2BRctdjvJq%2F1CAVFG9AFc4TK51%2FFSpohJSQF4%3D&reserved=0) "GET /secrets?api-version=7.0 HTTP/1.1" 401 848
DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_command_type.py", line 116, in keyvault_command_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_transformers.py", line 12, in _multi_transformers
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_transformers.py", line 29, in filter_out_managed_resources
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_transformers.py", line 29, in <listcomp>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/paging.py", line 143, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/paging.py", line 129, in advance_page
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/keyvault/v7_0/key_vault_client.py", line 1918, in internal_paging
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/service_client.py", line 336, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/__init__.py", line 197, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/__init__.py", line 150, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/requests.py", line 72, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/requests.py", line 137, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/__init__.py", line 150, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/pipeline/requests.py", line 193, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/universal_http/requests.py", line 333, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/universal_http/requests.py", line 139, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 542, in request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 662, in send
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/hooks.py", line 31, in dispatch_hook
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/keyvault/key_vault_authentication.py", line 120, in _handle_401
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/keyvault/http_challenge.py", line 43, in __init__
ValueError: Invalid challenge parameters

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_command_type.py", line 138, in keyvault_command_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_command_type.py", line 51, in keyvault_exception_handler
knack.util.CLIError: Invalid challenge parameters

ERROR: cli.azure.cli.core.azclierror: Invalid challenge parameters
ERROR: az_command_data_logger: Invalid challenge parameters
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03EEA9B8>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 1.113 seconds (init: 0.208, invoke: 0.905)
INFO: telemetry.save: Save telemetry record of length 2968 in cache
WARNING: telemetry.check: Negative: The C:\Users\jhines\.azure\telemetry.txt was modified at 2022-03-17 06:42:27.696980, which in less than 600.000000 s

**Comment by v-smeadows** [comment]
Following up on this.  Anything to provide my CX? Or is there any more information required?

**Comment by evelyn-ys** [comment]
Can you check your local `azure-keyvault` package? Seems not the version CLI uses:
https://github.com/Azure/azure-cli/blob/3bdf16a43dbf5250d038f7b9aff93b0571a9f4e8/src/azure-cli/setup.py#L65

**Comment by v-smeadows** [comment]
The CX provided me with this information:

I'm not sure how you were able to determine what my local azure-keyvault package is because when I do a version command I don't see it:
{
  "azure-cli": "2.34.1",
  "azure-cli-core": "2.34.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-iot": "0.10.13",
    "costmanagement": "0.1.1"
  }
}

However, I did find this Azure GitHub repo about Key Vault Preview Extension<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-keyvault-cli-extension&data=04%7C01%7Cv-kclaridy%40microsoftsupport.com%7Cfbef871c94ed40ffa12d08da130aba52%7Cb4c546a47dac46a6a7dded822a11efd3%7C0%7C0%7C637843234047612646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FP9n6mPSCVfa89xMPBh60teXd7wCL3j2jg64IdJSgsE%3D&reserved=0>. Is this something I need to add?


Steven Meadows

Support Engineer | Azure Information Protection - Azure Key Vault
Customer Services & Support | Microsoft Corporation
*(480)509-2475; * ***@***.******@***.***>
My working hours: Monday - Friday | 8am - 5pm PST
Need help outside of my working hours? 1-800-936-3100
Manager: Julie Dunn ***@***.******@***.***> 470-826-7403

**Comment by evelyn-ys** [comment]
The keyvault-extension has nothing to do with this issue. You can check the dependency with `& "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -m pip list` and find `azure-keyvault` package

**Comment by v-smeadows** [comment]
Apologies. This case fell between the cracks. Trying to get it back on track. 

What exactly does the CX need to input so that they can provide the information you need?

**Comment by evelyn-ys** [comment]
The customer probably had his dependency environment broken. So the easy way is to ask customer to reinstall AzureCLI. If he wants to verify where his dependency breaks, then please run 
```
& "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -m pip list
```
And find `azure-keyvault` package version from the output. It should be `1.1.0`

**Comment by v-smeadows** [comment]
Response from CX


Good Afternoon Steven,

I ran that command but I didn’t see any results with ‘azure-keyvault’ in the name. Here’s the results:
$ "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -m pip list
Package                Version
---------------------- ---------
adal                   1.2.7
antlr4-python3-runtime 4.7.2
applicationinsights    0.11.7
argcomplete            1.11.1
asn1crypto             0.24.0
bcrypt                 3.2.0
certifi                2021.10.8
cffi                   1.15.0
chardet                3.0.4
charset-normalizer     2.0.12
colorama               0.4.4
cryptography           3.3.2
Deprecated             1.2.13
fabric                 2.4.0
humanfriendly          10.0
idna                   2.8
invoke                 1.2.0
isodate                0.6.0
javaproperties         0.5.1
Jinja2                 2.11.3
jmespath               0.9.5
jsondiff               1.3.0
knack                  0.9.0
MarkupSafe             1.1.1
msal                   1.16.0
msal-extensions        0.3.1
msrest                 0.6.21
msrestazure            0.6.4
oauthlib               3.0.1
packaging              21.3
paramiko               2.6.0
pbr                    5.3.1
pip                    21.0.1
pkginfo                1.8.2
portalocker            2.3.2
psutil                 5.9.0
pycparser              2.19
PyGithub               1.55
Pygments               2.11.2
PyJWT                  2.1.0
PyNaCl                 1.4.0
pyOpenSSL              19.0.0
pyparsing              3.0.7
pyreadline3            3.4.1
PySocks                1.7.1
python-dateutil        2.8.0
pywin32                302
PyYAML                 6.0
requests               2.26.0
requests-oauthlib      1.2.0
scp                    0.13.2
semver                 2.13.0
setuptools             56.0.0
six                    1.14.0
sshtunnel              0.1.5
tabulate               0.8.9
urllib3                1.26.7
vsts                   0.1.25
wcwidth                0.1.7
websocket-client       0.56.0
wheel                  0.36.2
wrapt                  1.13.3
xmltodict              0.12.0

**Comment by evelyn-ys** [comment]
CLI does depend on `azure-keyvault` package so probably the dependencies are somehow broken. The easiest way is to ask customer to completely uninstall and then re-install with: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**Comment by v-smeadows** [comment]
Update from the CX this morning

Everything is working as intended and all commands are functioning. 


Thank you! for your help!
