### ISSUE TITLE
Application Gateway HTTPListeners do not support host parameter

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#2167]
For multisite support both host and sni fields should be allowed. sni field could be implicit based on http/https type. However lack of host field on listeners renders this scenario not workable. This is a big functionality gap.

azureuser@amitubuntu15:~$ appgw http-listener create -h

Command
    az network application-gateway http-listener create: Create a new application gateway HTTP
    listener.

Arguments
    --frontend-ip       [Required]: The name or ID of the frontend IP configuration.
    --frontend-port     [Required]: The name or ID of the frontend port.
    --gateway-name      [Required]: The name of the application gateway.
    --name -n           [Required]: The name of the HTTP listener.
    --resource-group -g [Required]: Name of resource group.
    --no-wait                     : Do not wait for the long running operation to finish.
    --ssl-cert                    : The name or ID of the SSL certificate to use.

**Comment by tjprescott** [comment]
@amarzavery please not that Xplat also does not support these parameters.

**Comment by amarzavery** [comment]
@MikhailTryakhov - Please look into this.

**Comment by MikhailTryakhov** [comment]
Hi @amitsriva 
it wasn't implemented because we didn't know anything about these changes :(
As for xplat-cli - see ```host name``` parameter in SDK, it's implemented in [PR#3510](https://github.com/Azure/azure-xplat-cli/pull/3510).
