### ISSUE TITLE
Azure Virtual Network Manager CLI extension.

### ISSUE THREAD

**Issue by jago2136** [Azure/azure-cli#21673]
**Resource Provider**

Azure Virtual Network Manager (extension name virtual-network-manager)

**Description of Feature or Work Requested**

We're releasing a new API version which includes...
- Adding force delete flags to various resources
- Fixing URI for network manager connection resource
- Splitting configuration and rule collection into admin rule collection/configuration and user rule/configuration
- Update static member to operations to include aux token for cross-tenant support.
 - - A static member has a resource id property. This will be a vnet id, which may exist in another tenant. We need to use an auxiliary token to authenticate this cross-tenant vnet, likely using this function [https://github.com/Azure/azure-cli/blob/110f7b402020f3d3ebd2bfb923ac5a01d026cdd1/src/azure-cli-core/azure/cli/core/commands/client_factory.py#L50-L75](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fblob%2F110f7b402020f3d3ebd2bfb923ac5a01d026cdd1%2Fsrc%2Fazure-cli-core%2Fazure%2Fcli%2Fcore%2Fcommands%2Fclient_factory.py%23L50-L75&data=04%7C01%7Cjaredgorthy%40microsoft.com%7C0c8fbaea746c4727f82a08da11f8cfd4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637842057614180403%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PJBchGF6WMBgr4cHRCRVNTuSwlJChDY5lMmNMWodqRs%3D&reserved=0)
 - Issues found in our team's bug bash after the last extension update, listed in this doc
https://microsoft-my.sharepoint.com/:w:/p/jaredgorthy/EU_hEZ1_TipBtMWIRwVhIqwBLGy6n1FDyFOCL2pqi1KP1w?e=wkK29J&wdOrigin=TEAMS-ELECTRON.p2p.bim&wdExp=TEAMS-CONTROL&wdhostclicktime=1648672661333 

 **Minimum API Version Required**

2022-02-01-preview

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/network/resource-manager/Microsoft.Network/preview/2022-02-01-preview

**Target Date**

ASAP, ideally early April

**Comment by yonzhan** [comment]
network
