### ISSUE TITLE
Application Gateway http-settings probe not found error

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#2168]
Creation of a new http setting without a probe name should go through fine (default probe is created by platform). However it complaints with cli that a probe named /None does not exist. New http setting can be created only by creating a new custom probe.

azureuser@amitubuntu15:~$ appgw http-settings create -n settin2 --port 80 --cookie-based-affinity Enabled --protocol Http --gateway-name azurewebsitetest -g azurewebsitetest

Resource /subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/probes/None referenced by resource /subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/backendHttpSettingsCollection/settin2 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.

**Comment by tjprescott** [comment]
Please try this again with the latest master. PR #2137 fixed the bug that would trigger this.
