### ISSUE TITLE
Error attempting to connect to aks cluster from WSL

### ISSUE THREAD

**Issue by osobeso** [Azure/azure-cli#21687]
## Describe the bug
I'm getting an error while trying to connect to a cluster using az aks, from WSL.
When I don't use WSL it works fine.

**Command Name**
`az aks get-credentials`

**Errors:**
```
cannot import name 'UnclassifiedUserFault'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 553, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 478, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
cliextensions/aks-preview/azext_aks_preview/custom.py, ln 46, in <module>
    from azure.cli.core.azclierror import ManualInterrupt, InvalidArgumentValueError, UnclassifiedUserFault, CLIInternalError, FileOperationError, ClientRequestError, DeploymentError, ValidationError, ArgumentUsageError, MutuallyExclusiveArgumentError, RequiredArgumentMissingError, ResourceNotFoundError
ImportError: cannot import name 'UnclassifiedUserFault'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials -g {} -n {}`

## Environment Summary
```
Linux-4.4.0-22000-Microsoft-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9
Installer: 

azure-cli 2.13.0 *

Extensions:
aks-preview 0.5.41

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@osobeso Thank you reaching out we are looking into the issue and will help you with an update as soon as possible. Thank you for your patience and understanding.

**Comment by RakeshMohanMSFT** [comment]
@osobeso can you please try removing the aks-preview using command "az extension remove --name aks-preview" and see if that resolves the issue?
