### ISSUE TITLE
az webapp deployment using zip file fails

### ISSUE THREAD

**Issue by na-init** [Azure/azure-cli#21685]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az webapp deployment fails ,
Following not very friendly error is coming

 WARNING: Getting scm site credentials for zip deployment
null_resource.run_script_curl (local-exec):   0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
 WARNING: Starting zip deployment. This operation can take a while to complete ...
 ERROR: The command failed with an unexpected error. Here is the traceback:
 ERROR: ('Connection aborted.', OSError(0, 'Error'))
 Traceback (most recent call last):
   File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
     chunked=chunked,
   File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
     self._validate_conn(conn)
   File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
     conn.connect()
   File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 421, in connect
     tls_in_tls=tls_in_tls,
   File "/opt/az/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
     sock, context, tls_in_tls, server_hostname=server_hostname
   File "/opt/az/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
   File "/opt/az/lib/python3.6/ssl.py", line 407, in wrap_socket
     _context=self, _session=session)
   File "/opt/az/lib/python3.6/ssl.py", line 817, in __init__
     self.do_handshake()
   File "/opt/az/lib/python3.6/ssl.py", line 1077, in do_handshake
     self._sslobj.do_handshake()
   File "/opt/az/lib/python3.6/ssl.py", line 689, in do_handshake
     self._sslobj.do_handshake()
 OSError: [Errno 0] Error

**To Reproduce**
az webapp deployment source config-zip -g $FUNC_APP_RESOURCE_GROUP -n $FUNC_APP_NAME --src $FUNC_APP_PACKAGE_SRC

**Expected behavior**
 it should publish the package

**Environment summary**
azure-cli                         2.25.0 *

core                              2.25.0 *
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0

I am using consumption plan, with Windows. 
**Additional context**
Why this is so unstable?.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@na-init Apologies for the late reply. Could you please confirm if there is any corporate proxy in your environment? If Yes, then you should follow the steps mentioned in [this](https://jiasli.github.io/azure-notes/cli/cli-proxy.html#add-certificate-to-ca-bundle) article to make the AzCLI work via proxy.

Alternatively to test the functionality, you can try to run the command from another machine which is not in your corporate network (without the proxy) and try to run the command again? and check if that helps. 

On a side note, please use the [most recent version ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)of the Azure CLI to perform the test. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@na-init I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@na-init I hope you had a chance to follow the suggested action plan in above comment. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
