### ISSUE TITLE
az storage blob upload-batch truncates blob URIs after v2.34.1

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli#21699]
## Describe the bug

**Command Name**

`az storage blob upload-batch`

### On v2.31.0:

`az storage blob upload-batch --destination extensions --source d:\temp\1 --destination-path sometest/blah --account-name someaccount --account-key "somekey"`

Responds with 

```
[
  {
    "Blob": "https://someaccount.blob.core.windows.net/extensions/sometest/blah/filename",
    "Last Modified": "2022-03-18T20:05:08+00:00",
    "Type": null,
    "eTag": "\"0x8DA091A9A03E9CB\""
  },
  {
    "Blob": "https://someaccount.blob.core.windows.net/extensions/sometest/blah/anotherfilename",
    "Last Modified": "2022-03-18T20:05:08+00:00",
    "Type": null,
    "eTag": "\"0x8DA091A9A0AED96\""
  }
]
```

### After upgrading to v2.34.1:

`az storage blob upload-batch --destination extensions --source d:\temp\1 --destination-path sometest/blah --account-name someaccount --account-key "somekey"`

```
[
  {
    "Blob": "https://someaccount.blob.core.windows.net/",
    "Last Modified": "2022-03-18T20:15:00+00:00",
    "Type": null,
    "eTag": "\"0x8DA091BFB2C42F2\""
  },
  {
    "Blob": "https://someaccount.blob.core.windows.net/",
    "Last Modified": "2022-03-18T20:15:00+00:00",
    "Type": null,
    "eTag": "\"0x8DA091BFB3430F5\""
  }
]
```

As you can see, file path is gone.

## Expected Behavior

Blob property contains full URI to the newly uploaded file.

Our automation is completely broken because of this change.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1

Extensions:
aks-preview 0.5.52
azure-devops 0.22.0
front-door 1.0.16
log-analytics 0.2.1
resource-graph 2.1.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by wasker** [comment]
Looks like [this change](https://github.com/Azure/azure-cli/commit/9268b9ee57fcfc481ed7efbfa1132b98e1e97d8c#diff-94011053dda390a736cbfca1ce3f1db2e83b7cfc00b88f3ccfb12095aa379e0e) broke it.

@calvinhzy

**Comment by yonzhan** [comment]
@evelyn-ys @calvinhzy please take a look
