### ISSUE TITLE
min max count 1000

### ISSUE THREAD

**Issue by dzanter** [Azure/azure-cli#21695]
I think there is a typo in the 
--max-count and --min-count sections.

The portal.azure.com, has min and max = 1000.

And the aks nodepool does let me create > 100.  So I think it's just a typo with one missing zero.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fce7ab-ab56-44c6-b9a8-405444247a0b
* Version Independent ID: dabbb6c6-c616-a6ec-61f6-1b9d3bb069e8
* Content: [az aks nodepool](https://docs.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/aks/nodepool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks/nodepool.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@dzanter Thanks for reporting this.  We will look into this and get back to you. Thanks

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@dzanter Thanks for reporting this.  I have submitted a PR to fix this documentation issue.

**Comment by SaurabhSharma-MSFT** [comment]
@dzanter We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
