### ISSUE TITLE
az sf cluster node-type add does not add a new node type

### ISSUE THREAD

**Issue by abhisek88** [Azure/azure-cli#21697]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az cli for service fabric nodetype add is throwing error with "StorageAccountsOperations"

Below command was executed where the error description was observed. It is reproducable by running the below cli command

az sf cluster node-type add --capacity 2 `
--cluster-name clustername `
--node-type workers `
--resource-group resourcegroupname `
--vm-password password `
--vm-user-name vmusername `
--durability-level Bronze `
--vm-sku 'vmsku'

Error:

The command failed with an unexpected error. Here is the traceback:
'StorageAccountsOperations' object has no attribute 'create'
Traceback (most recent call last):
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\knack/cli.py', line 231, in invoke
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/__init__.py', line 658, in execute
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/__init__.py', line 721, in _run_jobs_serially
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/__init__.py', line 692, in _run_job
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/__init__.py', line 328, in __call__
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/core/commands/command_operation.py', line 121, in handler
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/command_modules/servicefabric/custom.py', line 695, in add_cluster_node_type
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/command_modules/servicefabric/custom.py', line 916, in _create_vmss
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/command_modules/servicefabric/custom.py', line 880, in create_vhd
  File 'D:\\a\\1\\s\\build_scripts\\windows\\artifacts\\cli\\Lib\\site-packages\\azure/cli/command_modules/servicefabric/custom.py', line 888, in create_storage_account
AttributeError: 'StorageAccountsOperations' object has no attribute 'create'

**To Reproduce**
On an existing service fabric cluster the below command can be executed to add a new node type

az sf cluster node-type add --capacity 2 `
--cluster-name clustername `
--node-type workers `
--resource-group resourcegroupname `
--vm-password password `
--vm-user-name vmusername `
--durability-level Bronze `
--vm-sku 'vmsku'

**Expected behavior**
The expected behavior is to add new node type with defined new node type name to the existing cluster. In the process it creates a new vmss and adds it to the existing cluster. However the command does not execute complaining about the storage account creations.

**Environment summary**
The cli was used on a Windows 11 workstation. 

The service fabric cluster(not managed cluster) was used for the test. The cluster already was configured with primary/seed nodes and was healthy. If we want to add a new node type as per the below documentation.

https://docs.microsoft.com/en-us/cli/azure/sf/cluster/node-type?view=azure-cli-latest

**Additional Context**
Az powershell worked fine for the use case. However there are 2 other issues which were observed and will be reported in appropriate section.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@abhisek88 Apologies for the late reply. Thanks for reporting this issue. I am able to reproduce this issue. We are looking into this issue. I will update this thread once I have more details on this.

**Comment by navba-MSFT** [comment]
Thanks @a-santamaria for your assistance on this issue. Could you please let me know if you have an update on this issue ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@a-santamaria Could you please provide an update on this ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@abhisek88 Apologies for the late reply. We are looking into this issue. We will try to include it for the April release. 

CC @a-santamaria

**Comment by navba-MSFT** [comment]
@abhisek88 Apologies for the delay in getting back. in this sprint we didn't have time to get this issue fixed. This fix is planned for the May month release. We will keep you posted if there is any change in the release date. We appreciate your patience on this.

**Comment by navba-MSFT** [comment]
@abhisek88 The above PR has been filed to fix this issue. 

Thanks @a-santamaria

**Comment by navba-MSFT** [comment]
@abhisek88 This PR https://github.com/Azure/azure-cli/pull/22283 includes the fix and it is merged now. The fix should be available in the next release. Refer the [May milestone ](https://github.com/Azure/azure-cli/milestone/118). With that we will proceed with closure of this thread. If you need any further assistance on this in future, feel free to reopen this. We would be happy to help.
