### ISSUE TITLE
Application Gateway probe create inconsitency

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#2170]
Steps to reproduce - create a probe, update it by setting threhhold, timeout parameters. Now create another probe without giving threshold/timeout params. This creates a new probe but takes old timeout etc parameters.

appgw probe create -n probe3 --host 127.0.0.1 --path / --protocol Http  --gateway-name azurewebsitetest -g azurewebsitetest
this sets unhealthythreshold, timeout and interval to values specified in update operation of an earlier probe
azureuser@amitubuntu15:~$ appgw probe create -n probe5 --host 127.0.0.1 --path / --protocol Http  --gateway-name azurewebsitetest -g azurewebsitetest --debug
Command arguments ['network', 'application-gateway', 'probe', 'create', '-n', 'probe5', '--host', '127.0.0.1', '--path', '/', '--protocol', 'Http', '--gateway-name', 'azurewebsitetest', '-g', 'azurewebsitetest']
Registered application event handler 'CommandTableParams.Loaded' at <function add_id_parameters at 0x7fdec8d14f50>
Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x7fdec8d14f50>
Successfully loaded command table from module 'network'.
Application event 'CommandTable.Loaded' with event data {'command_table': OrderedDict([('network application-gateway ssl-policy show', <azure.cli.core.commands.CliCommand object at 0x7fdec88c5f10>), ('network application-gateway address-pool create', <azure.cli.core.commands.CliCommand object at 0x7fdec88c55d0>), ('network dns zone update', <azure.cli.core.commands.CliCommand object at 0x7fdec875f5d0>), ('network lb inbound-nat-pool show', <azure.cli.core.commands.CliCommand object at 0x7fdec8890390>), ('network lb address-pool delete', <azure. [...]
Application event 'CommandParser.Loaded' with event data {'parser': AzCliCommandParser(prog='az', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)}
Application event 'CommandTableParams.Loaded' with event data {'command_table': OrderedDict([('network application-gateway ssl-policy show', <azure.cli.core.commands.CliCommand object at 0x7fdec88c5f10>), ('network application-gateway address-pool create', <azure.cli.core.commands.CliCommand object at 0x7fdec88c55d0>), ('network dns zone update', <azure.cli.core.commands.CliCommand object at 0x7fdec875f5d0>), ('network lb inbound-nat-pool show', <azure.cli.core.commands.CliCommand object at 0x7fdec8890390>), ('network lb address-pool delete', <azure. [...]
Application event 'CommandParser.Parsed' with event data {'args': Namespace(_command_package='network', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_verbose=False, _output_format='json', _parser=AzCliCommandParser(prog='az network application-gateway probe create', usage=None, description='', version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), _validators=[], application_gateway_name='azurewebsitetest', command='network application-gateway probe create', func=<function _ex [...]
Getting management service client client_type=NetworkManagementClient
msrest.pipeline : Adding 'log_request' callback before event: 'request'
msrest.pipeline : Callback to overwrite original call: False
msrest.pipeline : Adding 'log_response' callback after event: 'response'
msrest.pipeline : Callback to overwrite original call: False
adal-python : 5adb2611-c074-4d24-80e0-07368cca5e1a - Authority:Performing instance discovery: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47
adal-python : 5adb2611-c074-4d24-80e0-07368cca5e1a - Authority:Performing static instance discovery
adal-python : 5adb2611-c074-4d24-80e0-07368cca5e1a - Authority:Authority validated via static instance discovery
adal-python : 5adb2611-c074-4d24-80e0-07368cca5e1a - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : 5adb2611-c074-4d24-80e0-07368cca5e1a - OAuth2Client:finding with query: {"_clientId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46", "userId": "amsriva@microsoft.com"}
adal-python : 5adb2611-c074-4d24-80e0-07368cca5e1a - OAuth2Client:Looking for potential cache entries:
adal-python : 5adb2611-c074-4d24-80e0-07368cca5e1a - OAuth2Client:{"_clientId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46", "userId": "amsriva@microsoft.com"}
adal-python : 5adb2611-c074-4d24-80e0-07368cca5e1a - OAuth2Client:Found 4 potential entries.
adal-python : 5adb2611-c074-4d24-80e0-07368cca5e1a - OAuth2Client:Resource specific token found.
adal-python : 5adb2611-c074-4d24-80e0-07368cca5e1a - OAuth2Client:Returning token from cache lookup, AccessTokenId: y7qZLfyXwU/469NXS9U03rU36ei213VXzNmaKJAzK84=, RefreshTokenId: 7ytblspYLDkx9OIBxlQ/IfUTufGPDppSZj3AizcxpA4=
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest?api-version=2016-09-01'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'User-Agent': 'python/2.7.10 (Linux-4.2.0-35-generic-x86_64-with-Ubuntu-15.10-wily) requests/2.13.0 msrest/0.4.5 msrest_azure/0.4.7 networkmanagementclient/0.30.0 Azure-SDK-For-Python AZURECLI/0.1.1b3'
msrest.http_logger :     'x-ms-client-request-id': '433f9334-f63b-11e6-92e8-000d3a0178fa'
msrest.http_logger :     'CommandName': 'network application-gateway probe create'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger : Request body:
msrest.http_logger : None
requests.packages.urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com
requests.packages.urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest?api-version=2016-09-01 HTTP/1.1" 200 None
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Transfer-Encoding': 'chunked'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'ETag': 'W/"1ea02840-65a6-49d0-857b-95d1dfda2538"'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'x-ms-request-id': 'd427bf15-2ee9-42d1-bcdd-4a450eb839b8'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-reads': '14994'
msrest.http_logger :     'x-ms-correlation-request-id': '303b3bf8-e55f-4d5b-af7d-5d382e537606'
msrest.http_logger :     'x-ms-routing-request-id': 'EASTUS2:20170219T003509Z:303b3bf8-e55f-4d5b-af7d-5d382e537606'
msrest.http_logger :     'Date': 'Sun, 19 Feb 2017 00:35:08 GMT'
msrest.http_logger : Response content:
msrest.http_logger : Body contains chunked data.
Starting long running operation 'Starting network application-gateway probe create'
adal-python : 6247f903-65ca-4c23-b7e0-a8ba41de4a29 - Authority:Performing instance discovery: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47
adal-python : 6247f903-65ca-4c23-b7e0-a8ba41de4a29 - Authority:Performing static instance discovery
adal-python : 6247f903-65ca-4c23-b7e0-a8ba41de4a29 - Authority:Authority validated via static instance discovery
adal-python : 6247f903-65ca-4c23-b7e0-a8ba41de4a29 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : 6247f903-65ca-4c23-b7e0-a8ba41de4a29 - OAuth2Client:finding with query: {"_clientId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46", "userId": "amsriva@microsoft.com"}
adal-python : 6247f903-65ca-4c23-b7e0-a8ba41de4a29 - OAuth2Client:Looking for potential cache entries:
adal-python : 6247f903-65ca-4c23-b7e0-a8ba41de4a29 - OAuth2Client:{"_clientId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46", "userId": "amsriva@microsoft.com"}
adal-python : 6247f903-65ca-4c23-b7e0-a8ba41de4a29 - OAuth2Client:Found 4 potential entries.
adal-python : 6247f903-65ca-4c23-b7e0-a8ba41de4a29 - OAuth2Client:Resource specific token found.
adal-python : 6247f903-65ca-4c23-b7e0-a8ba41de4a29 - OAuth2Client:Returning token from cache lookup, AccessTokenId: y7qZLfyXwU/469NXS9U03rU36ei213VXzNmaKJAzK84=, RefreshTokenId: 7ytblspYLDkx9OIBxlQ/IfUTufGPDppSZj3AizcxpA4=
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest?api-version=2016-09-01'
msrest.http_logger : Request method: 'PUT'
msrest.http_logger : Request headers:
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'User-Agent': 'python/2.7.10 (Linux-4.2.0-35-generic-x86_64-with-Ubuntu-15.10-wily) requests/2.13.0 msrest/0.4.5 msrest_azure/0.4.7 networkmanagementclient/0.30.0 Azure-SDK-For-Python AZURECLI/0.1.1b3'
msrest.http_logger :     'x-ms-client-request-id': '433f9334-f63b-11e6-92e8-000d3a0178fa'
msrest.http_logger :     'CommandName': 'network application-gateway probe create'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Length': '9031'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger : Request body:
msrest.http_logger : {"location": "eastus", "etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"sku": {"tier": "Standard", "capacity": 1, "name": "Standard_Small"}, "frontendPorts": [{"etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"port": 80, "provisioningState": "Succeeded"}, "name": "appGatewayFrontendPort", "id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendPorts/appGatewayFrontendPort"}, {"etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"port": 443, "provisioningState": "Succeeded"}, "name": "sslport", "id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendPorts/sslport"}], "requestRoutingRules": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/requestRoutingRules/rule1", "etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"backendAddressPool": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/backendAddressPools/appGatewayBackendPool"}, "httpListener": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/httpListeners/appGatewayHttpListener"}, "ruleType": "Basic", "backendHttpSettings": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/backendHttpSettingsCollection/appGatewayBackendHttpSettings"}, "provisioningState": "Succeeded"}, "name": "rule1"}], "backendHttpSettingsCollection": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/backendHttpSettingsCollection/appGatewayBackendHttpSettings", "etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"cookieBasedAffinity": "Disabled", "requestTimeout": 30, "protocol": "Http", "port": 80, "provisioningState": "Succeeded"}, "name": "appGatewayBackendHttpSettings"}], "probes": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/probes/probe2", "etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"host": "127.0.0.1", "protocol": "Http", "timeout": 120, "path": "/", "unhealthyThreshold": 8, "interval": 30, "provisioningState": "Succeeded"}, "name": "probe2"}, {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/probes/probe3", "etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"host": "127.0.0.1", "protocol": "Http", "timeout": 120, "path": "/", "unhealthyThreshold": 8, "interval": 30, "provisioningState": "Succeeded"}, "name": "probe3"}, {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/probes/probe4", "etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"host": "127.0.0.1", "protocol": "Http", "timeout": 120, "path": "/", "unhealthyThreshold": 8, "interval": 30, "provisioningState": "Succeeded"}, "name": "probe4"}, {"properties": {"host": "127.0.0.1", "protocol": "Http", "timeout": 120, "path": "/", "interval": 30, "unhealthyThreshold": 8}, "name": "probe5"}], "backendAddressPools": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/backendAddressPools/appGatewayBackendPool", "etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"backendAddresses": [], "provisioningState": "Succeeded"}, "name": "appGatewayBackendPool"}, {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/backendAddressPools/temp1", "etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"backendAddresses": [{"ipAddress": "10.0.0.5"}], "provisioningState": "Succeeded"}, "name": "temp1"}], "gatewayIPConfigurations": [{"etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"subnet": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/virtualNetworks/azurewebsitetest/subnets/default"}, "provisioningState": "Succeeded"}, "name": "appGatewayIpConfig", "id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/gatewayIPConfigurations/appGatewayIpConfig"}], "frontendIPConfigurations": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendIPConfigurations/appGatewayFrontendIP", "etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"privateIPAllocationMethod": "Dynamic", "provisioningState": "Succeeded", "publicIPAddress": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/publicIPAddresses/azurewebsitetest"}}, "name": "appGatewayFrontendIP"}], "sslCertificates": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/sslCertificates/newcert", "etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "name": "newcert", "properties": {"publicCertData": "MIIClAYJKoZIhvcNAQcCoIIChTCCAoECAQExADALBgkqhkiG9w0BBwGgggJpMIICZTCCAc4CCQC6bHNqqn4VSDANBgkqhkiG9w0BAQsFADB3MQswCQYDVQQGEwJVUzELMAkGA1UECAwCV0ExEDAOBgNVBAcMB1JlZG1vbmQxDTALBgNVBAoMBGFtaXQxDTALBgNVBAsMBGFtaXQxDTALBgNVBAMMBGFtaXQxHDAaBgkqhkiG9w0BCQEWDWFtaXRAYW1pdC5jb20wHhcNMTYwOTEzMDYxODU5WhcNMTcwOTEzMDYxODU5WjB3MQswCQYDVQQGEwJVUzELMAkGA1UECAwCV0ExEDAOBgNVBAcMB1JlZG1vbmQxDTALBgNVBAoMBGFtaXQxDTALBgNVBAsMBGFtaXQxDTALBgNVBAMMBGFtaXQxHDAaBgkqhkiG9w0BCQEWDWFtaXRAYW1pdC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMmrOwqp2511v6pg5e+c7RmS3aoI4zfUcbqMZqF8TcJPGqH6V+xxtUd79lGnngnlrplc761Btyx5AaFVo+W1lQrQMDA8hGWZXkD9iGO1zfcFWb6ntNVuUE29QS+CqVXF9dnNak1AmOMsO+XcYEyOAq2I0zqq1cShqPt5RkgkTM2hAgMBAAEwDQYJKoZIhvcNAQELBQADgYEAwhYpFtFdB3yrA8ofqLBaeA0u6TjHMag6iGye+CbGZbXUgOPUz0ne62Jg8ceW6p6OckQ3S5b1o1vGgRHZostHoMRj6PzWZuac+q5XERlpnlh/n+dPiS/jTQQJJdlp3ihZV/NwHrgxGNLOuWtJt76sGQxwau2hbSm6ldXwie9DUTAxAA==", "provisioningState": "Succeeded"}}], "authenticationCertificates": [], "httpListeners": [{"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/httpListeners/appGatewayHttpListener", "etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"provisioningState": "Succeeded", "protocol": "Http", "frontendIPConfiguration": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendIPConfigurations/appGatewayFrontendIP"}, "requireServerNameIndication": false, "frontendPort": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendPorts/appGatewayFrontendPort"}}, "name": "appGatewayHttpListener"}, {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/httpListeners/sslListener", "etag": "W/\"1ea02840-65a6-49d0-857b-95d1dfda2538\"", "properties": {"requireServerNameIndication": false, "protocol": "Https", "sslCertificate": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/sslCertificates/newcert"}, "frontendPort": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendPorts/sslport"}, "frontendIPConfiguration": {"id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/frontendIPConfigurations/appGatewayFrontendIP"}, "provisioningState": "Succeeded"}, "name": "sslListener"}], "resourceGuid": "c46e09cd-503e-47b2-98c7-c753dffcf60b", "urlPathMaps": [], "provisioningState": "Succeeded"}, "id": "/subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest"}
requests.packages.urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest?api-version=2016-09-01 HTTP/1.1" 200 None

**Comment by tjprescott** [comment]
This is not a bug but the intended behavior. Each probe has independent values of threshold, timeout, etc. If you do not specify values, the default values for the command are used.

**application-gateway probe create -h**
```
Arguments
    --gateway-name      [Required]: The name of the application gateway.
    --host              [Required]: The name of the host to send the probe.
    --name -n           [Required]: The name of the probe.
    --path              [Required]: The relative path of the probe. Valid paths start from "/".
    --protocol          [Required]: The HTTP settings protocol.  Allowed values: Http, Https.
    --resource-group -g [Required]: Name of resource group.
    --interval                    : The time interval in seconds between consecutive probes.
                                    Default: 30.
    --no-wait                     : Do not wait for the long running operation to finish.
    --threshold                   : The number of failed probes after which the back end server is
                                    marked down.  Default: 8.
    --timeout                     : The probe timeout in seconds.  Default: 120.
```

**Comment by amitsriva** [comment]
No I am reporting something else. If I create a probe with defaults and update its timeout to lets say 100. Now I create another new probe and do not specify a timeout value. It should be null or default. However I am seeing it takes the first probe's updated timeout value of 100. That  is definitely not intended.

**Comment by tjprescott** [comment]
I cannot reproduce this on the latest master. I just tested it and it used the default values for the CLI parameters.
