### ISSUE TITLE
az apim apply-network-updates has incorrect help text

### ISSUE THREAD

**Issue by johndowns** [Azure/azure-cli#21706]
## Describe the bug

**Command Name**
`az apim apply-network-updates`

**Errors:**
No error messasge, but the wrong help text is displayed.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az apim apply-network-updates -h`
- The help text displayed is:
   ```
   Back up an API Management service to the configured storage account.
   ```

   But this is the help text for the `az apim backup` command.

## Expected Behavior

The correct help text should be displayed.

## Environment Summary
```
macOS-12.3-arm64-arm-64bit, Darwin 21.4.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1

Extensions:
azure-devops 0.23.0
containerapp 0.2.2

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@johndowns Thank you reaching out we are looking into the issue and will help you with an update as soon as possible. Thank you for your patience and understanding.

**Comment by RakeshMohanMSFT** [comment]
@johndowns I have created a PR to fix this documentation issue. Reference# https://github.com/Azure/azure-cli/pull/21708

**Comment by johndowns** [comment]
@RakeshMohanMSFT Thanks for fixing this so promptly!
