### ISSUE TITLE
Application Gateway http-settings update not working

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#2171]
appgw http-settings update -n settin2 --port 80 --cookie-based-affinity Enabled  --probe probe5 --protocol Http --gateway-name azurewebsitetest -g azurewebsitetest

this does not update the probe to probe5. operation returns immediately. it still shows as probe2 in portal

**Comment by tjprescott** [comment]
I have confirmed this is working correctly on the latest master branch.
