### ISSUE TITLE
DNS zone import fails for hyphenated SRV record targets

### ISSUE THREAD

**Issue by huws** [Azure/azure-cli#21716]
**Describe the bug**
When attempting to import a DNS zone file, (e.g. via `az network private-dns zone import`) it will fail if you have any SRV records where the targets contain hyphens.

**To Reproduce**
Take the valid zone file `db.example.com`:
```
@                 3600 IN SOA  ns admin ( 2014010800 ; Serial
                                          3600       ; Refresh
                                          3600       ; Retry
                                          3600       ; Expire
                                          300 )      ; Minimum TTL

_sip._tcp.pool 300 IN SRV 20 10 5060 valid-target-1
_sip._tcp.pool 300 IN SRV 20 10 5060 valid-target-2
_sip._tcp.pool 300 IN SRV 20 10 5060 valid-target-3
```
and import it using:  `az network private-dns zone import --resource-group <RG NAME> --name example.com --file-name db.example.com`

The following output is produced:
```
	== BEGINNING ZONE IMPORT: example.com ==
	
	(1/4) Imported 1 records of type 'soa' and name '@'
	(BadRequest) The list of record sets of type 'SRV' may not contain multiple entries with the same '(priority, weight, target)'.
	Code: BadRequest
	Message: The list of record sets of type 'SRV' may not contain multiple entries with the same '(priority, weight, target)'.
	
	== 1/4 RECORDS IMPORTED SUCCESSFULLY: 'example.com' ==
```

**Expected behavior**
The DNS SRV record `_sip_tcp.pool.example.com` should be created, with three targets (`valid-target-1.example.com`, `valid-target-2.example.com`, `valid-target-3.example.com`)

**Environment summary**
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.2 LTS
Python 3.8.12
Installer: DEB

**Additional context**
This is down to an incorrect regular expression in the zone file parser.  I've got a fix for this bug, and will submit a PR.

**Comment by yonzhan** [comment]
network
