### ISSUE TITLE
Application Gateway rule update

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#2172]
Address pool, http setting , listener etc are all listed as non-mandatory. This would make user believe that they can update just one setting on rule and leave others intact - similar to rest patch operation. That is not the case.

azureuser@amitubuntu15:~$ appgw rule update -n rule2 --http-settings appGatewayBackendHttpSettings --gateway-name azurewebsitetest -g azurewebsitetest
Resource /subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/httpListeners/None referenced by resource /subscriptions/a932c0e6-b5cb-4e68-b23d-5064372c8a3c/resourceGroups/azurewebsitetest/providers/Microsoft.Network/applicationGateways/azurewebsitetest/requestRoutingRules/rule2 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.

**Comment by tjprescott** [comment]
This was fixed in PR #2137. If the issue still persists, please reopen.
