### ISSUE TITLE
Question for Azure App Service: Can you list files on the hosting platform? 

### ISSUE THREAD

**Issue by diberry** [Azure/azure-cli#21726]
Is there a way to see the files I've deployed to the App Service through AZ CLI? Is there a way to look at files on the hosting platform, that the platform creates, such as logs?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by seligj95** [comment]
For this you'll need to either use FTP or the kudu API. We don't have this functionality built into the CLI. Marking this as closed. Please let us know if you have any questions about this.

https://learn.microsoft.com/en-us/azure/app-service/resources-kudu
https://learn.microsoft.com/en-us/azure/app-service/deploy-ftp?tabs=portal
