### ISSUE TITLE
Multiple accounts with same username

### ISSUE THREAD

**Issue by jtrubin** [Azure/azure-cli#21727]
I am trying to install the Azure command line tool and when I try to sign in, it errors out saying that there are multiple accounts with the same username. There are two accounts for jason.rubin@shelfengine.com, one of which was created by my IT department, and the other was created by me. I would like to keep the one created by the IT department.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jtrubin** [comment]
I wish to keep both accounts as deleting either of them could cause some permission issues at my organization. Please disregard this.

**Comment by jiasli** [comment]
The multiple accounts issue is tracked by https://github.com/Azure/azure-cli/issues/20168.

**Comment by jtrubin** [comment]
Was able to resolve the issue using the steps in that ticket. Thanks!
