### ISSUE TITLE
Missing defaults

### ISSUE THREAD

**Issue by mateuszdrab** [Azure/azure-cli#21725]
Hi team

I have a customer asking about the default values for the `az aks create` command.

The parameters they're interested in are:
```
--vm-set-type
--zones
```

Our documentation is missing defaults for many available options.
Can this be resolved?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks.yml)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@mateuszdrab Thank you for reaching out we are looking into the issue and will help you with an update as soon as possible. Thank you for your patience and understanding.

**Comment by RakeshMohanMSFT** [comment]
@mateuszdrab the aforementioned parameters (--vm-set-type, --zones) do not have any default values we just send in None when nothing is passed) the some of the parameters do have valid default values like --nodepool-name or --node-count they have valid default values like nodepool1 and 3 respectively that is why they are mentioned in our documents. 

Hope that helps you! Do let me know if you have any follow up questions, I will be happy to assist you.

**Comment by mateuszdrab** [comment]
Thanks @RakeshMohanMSFT 

Hopefully we can get more insights on that, because --vm-set-type is a choice of two options, and one of them will be chosen if not provided, I'd assume the newer VMSS would be chosen. 
Same with --zones, when a VMSS option is used, zones have to be provided so something is making a default selection somewhere.

Not sure why our documentation is unclear about this.

**Comment by mateuszdrab** [comment]
I found some answers myself in the documentation of our REST api:

https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update#agentpooltype
![image](https://user-images.githubusercontent.com/26556541/159746346-a3075675-b4f1-4c3a-947c-17944c8c6b6b.png)

https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update#managedclusteragentpoolprofile
`The list of Availability zones to use for nodes. This can only be specified if the AgentPoolType property is 'VirtualMachineScaleSets'.`
