### ISSUE TITLE
Runtimes documentation slightly misleading

### ISSUE THREAD

**Issue by leighghunt** [Azure/azure-cli#21728]
> 
> --runtime -r
> 
> Canonicalized web runtime in the format of Framework|Version, e.g. "PHP|5.6". Use "az webapp list-runtimes" for available list.
> 

The documentation is subtly misleading here - I read it to mean I could take the output from `az webapp list-runtimes` and use that output in the `github-actions add` call - however, I need to change the colon to a pipe.

```
az webapp list-runtimes
{
  "linux": [
    "DOTNETCORE:6.0",              // Note name listed here uses colon, not pipe.
    "DOTNETCORE:5.0",
    "DOTNETCORE:3.1",
...
```

Mistakenly using `DOTNETCORE:6.0` fails as follows:
```
az webapp deployment github-actions add --name <name>--repo <repo> --resource-group <resource group> --branch development --token <ghp_xxx> --runtime "DOTNETCORE:6.0"
Verified GitHub repo and branch
The app runtime: {app_runtime_string} does not match the runtime specified: {runtime}. Using the specified runtime {runtime}.
Runtime DOTNETCORE:6.0 is not supported for GitHub Actions deployments.
```

Using the correct format `DOTNETCORE|6.0` succeeds:
```
az webapp deployment github-actions add --name <name>--repo <repo> --resource-group <resource group> --branch development --token <ghp_xxx> --runtime "DOTNETCORE|6.0"
```

I wonder if either this could be made clearer in the documentation, or perhaps the az cli commands could be made consistent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b397bce-4a07-9d15-d36c-ebed2f8bcc4e
* Version Independent ID: f31c415e-bb0f-14f3-b19f-e3496d816101
* Content: [az webapp deployment github-actions](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/github-actions?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/deployment/github-actions.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/deployment/github-actions.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@leighghunt Thanks for reaching out to us and proving the feedback. We have filed this https://github.com/Azure/azure-cli/pull/21741 PR. It is currently under the review phase. In the meantime, if you have any questions, please feel free to ask.

**Comment by navba-MSFT** [comment]
@leighghunt Please see the comment https://github.com/Azure/azure-cli/pull/21741#pullrequestreview-917660433 Another PR has been filed https://github.com/Azure/azure-cli/pull/21771 to address the az webapp deployment github-actions add to allow passing runtime with colon delimiter. This should address your concern. Thanks for reporting this issue and sharing feedback. Please let me know if you need any further assistance on this issue.

**Comment by navba-MSFT** [comment]
Refer the https://github.com/Azure/azure-cli/pull/21771 for the fix . Closing this github thread for now. Please feel free to reopen this thread if you have any queries on this. we would be happy to help.
