### ISSUE TITLE
Application Gateway rule update does not work

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#2173]
azureuser@amitubuntu15:~$ appgw rule update -n rule2 --http-settings appGatewayBackendHttpSettings --address-pool temp1 --http-listener ssllistener --gateway-name azurewebsitetest -g azurewebsitetest

this returns immediately and does not change the http-setting as indicated.

**Comment by tjprescott** [comment]
Cannot reproduce. I tested this on the latest master and it works as intended. It may have been fixed in one of the two recent PRs for app-gateway. If this persists, please reopen.
