### ISSUE TITLE
 Error while finding module specification for 'azure.cli' (ModuleNotFoundError: No module named 'azure')

### ISSUE THREAD

**Issue by Kmumuda** [Azure/azure-cli#21737]
==============================================================================
C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat --version"
C:\hostedtoolcache\windows\Python\3.8.10\x64\python.exe: Error while finding module specification for 'azure.cli' (ModuleNotFoundError: No module named 'azure')
##[error]Error Code: [1]
##[error]Script failed with error: C:\hostedtoolcache\windows\Python\3.8.10\x64\python.exe: Error while finding module specification for 'azure.cli' (ModuleNotFoundError: No module named 'azure')

Finishing: Azure CLI

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
It seems you are running Azure CLI on a ML instance: https://github.com/Azure/azure-cli/issues/18626
