### ISSUE TITLE
az costmanagement documentation is out of date

### ISSUE THREAD

**Issue by justinsmits** [Azure/azure-cli#21748]
query method was removed but documentation isn't updated:

https://github.com/Azure/azure-cli-extensions/blob/main/src/costmanagement/HISTORY.rst

Documentation link: https://docs.microsoft.com/en-us/cli/azure/costmanagement?view=azure-cli-latest#az-costmanagement-query

**Comment by yonzhan** [comment]
costmanagement

**Comment by jsntcy** [comment]
@justinsmits, the documentation has been updated now, please re-check.
