### ISSUE TITLE
(InternalServerError) An unexpected error occured while processing the request

### ISSUE THREAD

**Issue by mohakhlf** [Azure/azure-cli#21745]
## Describe the bug

**Command Name**
`az postgres flexible-server db list`

**Errors:**
```
(InternalServerError) An unexpected error occured while processing the request. Tracking ID: '06d9f962-0e94-42a1-bb60-146427932bde'
Code: InternalServerError
Message: An unexpected error occured while processing the request. Tracking ID: '06d9f962-0e94-42a1-bb60-146427932bde'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres flexible-server db list --resource-group {} --server-name {}`

## Environment Summary
```
macOS-12.2.1-x86_64-i386-64bit, Darwin 21.3.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1

Extensions:
interactive 0.4.5

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team
