### ISSUE TITLE
az afd profile show returns Null for frontDoorId

### ISSUE THREAD

**Issue by dtupy** [Azure/azure-cli#21751]
## Describe the bug
When using the below command and querying for frontdoorId it returns null. The front door profile has an ID based on the portal and the json provided in the portal. This cli command does return what I am looking for `az resource show -g rg -n profileName --namespace Microsoft.Cdn --resource-type Profiles --query properties.frontDoorId --output tsv` with the correct params for the afd profile will return frontdoorID. I would assume `az afd profile show` would also return fronDoorId not Null.

**Command Name**
`az afd profile show`

**Errors:**
```
az afd profile show -g rg --profile-name fdProfile
Command group 'afd' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
{
  "frontdoorId": null,
  "id": "*****",
  "kind": "frontdoor",
  "location": "Global",
  "name": "**********",
  "provisioningState": "Succeeded",
  "resourceGroup": "************",
  "resourceState": "Active",
  "sku": {
    "name": "Standard_AzureFrontDoor"
  },
  "systemData": null,
  "tags": {},
  "type": "Microsoft.Cdn/profiles"
}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az afd profile show -g {} --profile-name {} --query {}`

## Environment Summary
```
Linux-5.4.0-1072-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12
Installer: DEB

azure-cli 2.34.1

Extensions:
front-door 1.0.16
ai-examples 0.2.5
ssh 1.0.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by jsntcy** [comment]
@t-bzhan, could you please look at the issue?

**Comment by RakeshMohanMSFT** [comment]
@dtupy Thank you for reaching out, we are looking into the issue and will help you with an update as soon as possible. Appreciate your patience and understanding.

**Comment by dtupy** [comment]
With that PR merged should this be fixed now? @RakeshMohanMSFT

**Comment by RakeshMohanMSFT** [comment]
@dtupy usually after the PR merge, release will be scheduled once it is done, it should be fixed.

**Comment by dtupy** [comment]
any update here? @RakeshMohanMSFT @t-bzhan

**Comment by RakeshMohanMSFT** [comment]
@dtupy Let me check and confirm the details of the ETA. Sorry for the delay.

**Comment by t-bzhan** [comment]
Fixed in https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.35.0
