### ISSUE TITLE
Soft Delete for Files and Folders CLI GA

### ISSUE THREAD

**Issue by ellievail** [Azure/azure-cli#21757]
We have released Soft Delete for Files and Folders to be Generally Available. The only CLI package for this is the preview package, and we need to have the GA version of the CLI package. 

We would like the CLI package for Soft Delete for Files and Folders to be generally Available.

I don't think there are any alternatives to this. Hopefully this should be simple-- we have had customers test out the preview in CLI and like it, and we just need the package to be GA.

**Comment by yonzhan** [comment]
storage
