### ISSUE TITLE
Azure Bicep deployment fails with permission denied using az cli on Mac

### ISSUE THREAD

**Issue by devatas** [Azure/azure-cli#21769]
## Describe the bug

**Command Name**
`az deployment sub create`

**Errors:**
```
[Errno 13] Permission denied: '/Users/${username}/.azure/bin/bicep'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az deployment sub create -f {} -l {}`

## Environment Summary
```
macOS-11.5.2-x86_64-i386-64bit, Darwin 20.6.0
Python 3.10.1
Installer: HOMEBREW

azure-cli 2.31.0 *

Extensions:
alias 0.5.2

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by zhoxing-ms** [comment]
@shenglol Could you please help have a look at the `bicep` related issue~

**Comment by navba-MSFT** [comment]
@devatas Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. Could you please test this using the [most recent version of Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)? If you still see the same issue, please share the complete` --debug `trace with us. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@devatas I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please test with the most recent version of the AzCLI and share the --debug output. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@devatas We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
