### ISSUE TITLE
Application Gateway url-path-map

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#2177]
https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-create-url-route-arm-ps
The CLI input for url-path map seems to take a single backend pool, single http setting, default setting and default pool. It does take a space separated list of url paths. This wouldnt work. Each path in the list is associated with a http setting and a address pool. Apart from these there are a default pool and default setting. Please look at the documentation listed above.

azureuser@amitubuntu15:~$ appgw url-path-map create -h --gateway-name azurewebsitetest -g azurewebsitetest

Command
    az network application-gateway url-path-map create: Create a new application gateway URL path
    map.

Arguments
    --address-pool      [Required]: The name or ID of the backend address pool to use with the
                                    created rule.
    --gateway-name      [Required]: The name of the application gateway.
    --http-settings     [Required]: The name or ID of the HTTP settings to use with the created
                                    rule.
    --name -n           [Required]: The name of the URL path map.
    --paths             [Required]: Space separated list of paths to associate with the rule. Valid
                                    paths start and end with "/" (ex: "/bar/").
    --resource-group -g [Required]: Name of resource group.
    --default-address-pool        : The name or ID of the default backend address pool, if different
                                    from --address-pool.
    --default-http-settings       : The name or ID of the default HTTP settings, if different from
                                    --http-settings.
    --no-wait                     : Do not wait for the long running operation to finish.
    --rule-name                   : The name of the url-path-map rule.  Default: default.

Global Arguments
    --debug                       : Increase logging verbosity to show all debug logs.
    --help -h                     : Show this help message and exit.
    --output -o                   : Output format.  Allowed values: json, jsonc, list, table, tsv.
                                    Default: json.
    --query                       : JMESPath query string. See http://jmespath.org/ for more
                                    information and examples.
    --verbose                     : Increase logging verbosity. Use --debug for full debug logs.

**Comment by tjprescott** [comment]
While a bit of a strange command, I believe it does work as intended. 

You cannot create the URL path map (the containing type) without having at least one rule. If you could, this command would simply create an empty map and you would then fill it with calls to `application-gateway url-path-map rule create`. 

Thus this command has to create the "first rule". According to the URL path map rule object structure, a single rule can have multiple paths. That is why paths accepts multiple strings. You cannot create multiple rules with this command, only the first rule. Subsequent rules must be added with calls to `application-gateway url-path-map rule create`.
