### ISSUE TITLE
Add ability to use Bastion to tunnel database connection

### ISSUE THREAD

**Issue by kf6kjg** [Azure/azure-cli#21774]
As a developer using Azure CLI I'm frustrated that I have to set up and maintain a whole Virtual Machine just to access a database that's in a private VNet

I'd like to be able to use the Azure Bastion native tunnel feature to directly tunnel to a database inside the connected VNet in the [same manner as currently is used for accessing a VM via SSH or RDP](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-linux). In my particular case I'd like to connect to an Azure Database for MySQL flexible server instance that is set to [Private Access (VNet Integration)](https://docs.microsoft.com/en-us/azure/mysql/flexible-server/concepts-networking-vnet) - though it'd be good for any solution to handle any database.

Possible example:
```sh
az network bastion tunnel --resource-group test --name bastion-test --target-resource-id "$(az mysql flexible-server show --resource-group test --name db-test --query id --output tsv)" --resource-port 3306 --port 3306

mysql -u db_admin -p -h 127.0.0.1
```

Alternatives exist:
- [Create a VM inside the VNet, expose SSH to the world, use SSH to connect to the VM, then in the VM connect to the database](https://docs.microsoft.com/en-us/azure/mysql/flexible-server/quickstart-create-connect-server-vnet).
- Create a VM inside the VNet, expose SSH to the world, and use SSH to tunnel the database traffic.
- Create a VM inside the VNet, create a Bastion host, connect to the VM via Bastion in Azure Portal, then in the VM connect to the database.
- Create a VM inside the VNet, create a Bastion host, connect to the VM via Azure CLI `az network bastion tunnel`, then in the VM connect to the database.

Note that every alternative requires the creation of a VM. A VM that my company has to maintain. Bastion's [promise is to limit exposure](https://azure.microsoft.com/en-us/services/azure-bastion/#features) - but is currently limited to VMs. VMs aren't the only services that should have limited exposure.

**Comment by kf6kjg** [comment]
Note that attempting to accomplish the above example, since it is a currently unsupported idea, using `az cli 2.34.1` will result in the tunnel crashing:
```plaintext
cli.azure.cli.command_modules.network.custom: Opening tunnel on port: 3306
cli.azure.cli.command_modules.network.custom: Tunnel is ready, connect on port 3306
cli.azure.cli.command_modules.network.custom: Ctrl + C to close
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/392b58e2-29ce-464a-b20a-51b8bb9c217e/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/392b58e2-29ce-464a-b20a-51b8bb9c217e/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/392b58e2-29ce-464a-b20a-51b8bb9c217e/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/392b58e2-29ce-464a-b20a-51b8bb9c217e/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/392b58e2-29ce-464a-b20a-51b8bb9c217e/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/392b58e2-29ce-464a-b20a-51b8bb9c217e/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/392b58e2-29ce-464a-b20a-51b8bb9c217e/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 2268786a-c498-4e24-8974-0d17fa404329
urllib3.connectionpool: Starting new HTTPS connection (1): REDACTED.bastion.azure.com:443
urllib3.connectionpool: https://REDACTED.bastion.azure.com:443 "POST /api/tokens HTTP/1.1" 500 None
msrest.exceptions: Unexpected internal error
Exception in thread Thread-1 (_start_tunnel):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 8232, in _start_tunnel
    tunnel_server.start_server()
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/tunnel.py", line 184, in start_server
    self._listen()
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/tunnel.py", line 117, in _listen
    auth_token = self._get_auth_token()
  File "/usr/local/Cellar/azure-cli/2.34.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/tunnel.py", line 104, in _get_auth_token
    raise exp
msrestazure.azure_exceptions.CloudError: Unexpected internal error
```

**Comment by PramodValavala-MSFT** [comment]
@kf6kjg Azure Bastion is currently designed for connecting to VMs like you've mentioned. The [Azure Feedback](https://feedback.azure.com/d365community/forum/8ae9bf04-8326-ec11-b6e6-000d3a4f0789) forum would be the best place to get this idea recorded and have users up vote for it to gain traction.

Once the service supports it, then Azure CLI too would be updated to support the new scenarios as required.

**Comment by justinmchase** [comment]
I came here to file this bug also, I'm trying to tunnel to cosmosdb and it fails with this same error. 

This is a legit bug at least in the sense that it shouldn't be crashing with an `Unexpected internal error` and should probably at least give feedback about what is going wrong.

**Comment by w0rldart** [comment]
After running `az network bastion tunnel --resource-group bieno-cih-t-shared-services --name bastion --target-resource-id "$(az mysql flexible-server show --resource-group bieno-cih-t-shared-services --name cih --query id --output tsv)" --resource-port 3306 --port 33060`

I get a different error

```
msrestazure.azure_exceptions.CloudError: Resource id is of an invalid format:
```

**Comment by justinmchase** [comment]
Again, it should just check the resource type and throw an error saying that the command will only work specifically for VM's and cannot be used to tunnel to whatever resource type is attempting to be tunneled to.

**Comment by prees1** [comment]
> Moved to https://feedback.azure.com/d365community/idea/9f8d9743-b0ae-ec11-a81c-6045bd7d1bee

I get a 404 on this link. Any one have any update or planned status on this capability?

**Comment by kf6kjg** [comment]
🤦‍♂️ Lovely of MS. I'm the author of it and I can't even find it. Looks like it got deleted.

**Comment by Harsha102** [comment]
> Create a VM inside the VNet, create a Bastion host, connect to the VM via Azure CLI az network bastion tunnel, then in the VM connect to the database.


Are there any resources that can explain, how we can establish connection with database server using the above method? I am particularly looking for the final step. I want to run mysql commands from local, that can get forwarded to mysql flexible server (in private network) through the bastion host and VM. @kf6kjg

**Comment by Harsha102** [comment]
> Create a VM inside the VNet, create a Bastion host, connect to the VM via Azure CLI az network bastion tunnel, then in the VM connect to the database.


@kf6kjg , Can you provide any documentation on how the above can be done? In AWS, we can do it simply using [SSM](https://aws.amazon.com/blogs/database/securely-connect-to-an-amazon-rds-or-amazon-ec2-database-instance-remotely-with-your-preferred-gui/). In Azure, I am unable to figure out as the docs aren't clear. 

Once I establish the bastion tunnel from localhost to VM, is it possible to connect to database without explicitly ssh'ng into VM.

**Comment by justinmchase** [comment]
For CosmosDB we ended up running a socks5 proxy server in a pod inside of aks. Then you use `kubectl port-forward...` to your proxy and then configure your database connection string to point to the localhost port. To connect to azure sql server you can setup an nginx reverse proxy to your database as well. Theres some tricks but it works, it will even go through private links.

Thats all bastion is really is a proxy tunnel to a VM.
