### ISSUE TITLE
az policy assignment create and ---subscription

### ISSUE THREAD

**Issue by williamhbell** [Azure/azure-cli#21789]
Would it be possible to allow `az policy assignment create`  to be used with `--subscription`, where the subscription is the name or id of the subscription?  If  `--resource-group` is used,  `az policy assignment create` cannot find the resource group if it is in another subscription.  The `--role` does not appear to work as expected and is less obvious than providing  `--subscription`.

**Comment by yonzhan** [comment]
policy

**Comment by cxznmhdcxz** [comment]
Hi, parameter `--scope`  can specify which subscription to apply to.
`az policy assignment create --scope /subscriptions/<subscription-id>`

**Comment by williamhbell** [comment]
The `--scope` flag has to be used with the subscription id, instead of the name.  For other commands, they allow `--subscription`, where the value can be the id or the name of the subscription.  The issue that one could execute a large number of commands using the name, but then find that the id has to be looked up for this one command.  While it is possible to lookup the id from the name using `az account list`, it adds another step for the user.

If the resource group is not in the default subscription:

`$ az policy assignment create --name some_name --policy some_policy --scope "/subscriptions/some_subscription_id/resourceGroups/some_resource_group"
ERROR: (MissingSubscription) The request did not have a subscription or a valid tenant level resource provider.
Code: MissingSubscription
Message: The request did not have a subscription or a valid tenant level resource provider.`

The subscription id given was correct, but the command still reports an error.  Setting the default subscription to the subscription that contains the resource group

`$ az policy assignment create --name some_name --policy some_policy --resource-group some_resource_group`

works.  It seems a nasty hack to have to change the default subscription just for this command to work.  I am missing something?
