### ISSUE TITLE
[Change Analysis] Onboarding Microsoft.ChangeAnalysis RP

### ISSUE THREAD

**Issue by LinglingTong** [Azure/azure-cli#21792]
**Resource Provider**
Microsoft.ChangeAnalysis

**Description of Feature or Work Requested**
Support Azure CLI commands for ChangeAnalysis
ADO item: [Product Backlog Item 13859349](https://msazure.visualstudio.com/One/_workitems/edit/13859349): Application Change Analysis - microsoft.changeanalysis - [Ni] CLI Engagement Onboard

**Minimum API Version Required**
2021-04-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/changeanalysis/resource-manager/Microsoft.ChangeAnalysis/stable/2021-04-01/changeanalysis.json

**Target Date**
5/31/2022

**Comment by yonzhan** [comment]
PLR

**Comment by jsntcy** [comment]
@LinglingTong, we'll have a new CLI code generator ready around the middle of this month, and we'd like to invite you as our first customer to try our new code generator to generate CLI code automatically.

**Comment by LinglingTong** [comment]
> @LinglingTong, we'll have a new CLI code generator ready around the middle of this month, and we'd like to invite you as our first customer to try our new code generator to generate CLI code automatically.

Happy to help. Could I know what would you need from my side? I would also like to learn more about how the code generator   work if you could point me to any documentation you have.

**Comment by jsntcy** [comment]
> > @LinglingTong
> >             
> >             Lingling Tong
> >             FTE, we'll have a new CLI code generator ready around the middle of this month, and we'd like to invite you as our first customer to try our new code generator to generate CLI code automatically.
> 
> Happy to help. Could I know what would you need from my side? I would also like to learn more about how the code generator work if you could point me to any documentation you have.

We'll set up a quick meeting with you at the middle of May to guide you generate code step by step using the tool.
Here is [Introduction to AAZDev](https://github.com/kairu-ms/aaz-dev-tools/tree/dev/Docs) which is not complete yet. You can first take a look to have a basic understanding for the tool if you have time. If any questions or issues, please let us know.

**Comment by jsntcy** [comment]
Supported in https://github.com/Azure/azure-cli-extensions/pull/4931
