### ISSUE TITLE
Not able to access key vault

### ISSUE THREAD

**Issue by coolchirag** [Azure/azure-cli#21805]
## Describe the bug

**Command Name**
`az keyvault secret set`

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault secret set --vault-name {} --name {} --value {}`

## Environment Summary
```
Linux-5.13.0-35-generic-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
`azure-cli 2.0.81` is not our official Azure CLI. See #19640 for details

Please install our CLI following https://docs.microsoft.com/cli/azure/install-azure-cli

**Comment by SaurabhSharma-MSFT** [comment]
@coolchirag Please let us know in case you have any questions, else we are proceeding with the closure of this issue.

**Comment by SaurabhSharma-MSFT** [comment]
@coolchirag We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by coolchirag** [comment]
Yes you can close this issue.

**Comment by jiasli** [comment]
https://github.com/Azure/azure-cli/issues/19640#issuecomment-1148202854
