### ISSUE TITLE
[DNS] Deleting a record requires a confirmation prompt

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#2180]
Deleting a record set is a potentially catastrophic operation.

For this reason, in the Portal, PowerShell, and CLI1.0, the operation has a confirmation prompt.

We need to add a similar confirmation prompt in CLI2.0. This applies to both `az network dns record-set <type> delete` and `az network dns record-set <type> remove-record`.

The prompt should be suppressible for scripting purposes (e.g. via `--yes -y` same as `az network dns zone delete`)

**Comment by tjprescott** [comment]
I can see that deleting a record set warrants a prompt, but I don't see how removing a single record rises to this level.

**Comment by jtuliani** [comment]
Most record sets have just one record... So they're really equivalent.

Imagine deleting the www record for Microsoft.com...

Sent from my Windows Phone
________________________________

**Comment by jtuliani** [comment]
Even a short outage is a problem. During the time the record is missing, failed requests will result in negative caching, which will hang around outside your control eg on google 8.8.8.8 potentially for many minutes

Sent from my Windows Phone
________________________________
