### ISSUE TITLE
[Storage] Support SAS with sr= and sdd=

### ISSUE THREAD

**Issue by blueww** [Azure/azure-cli#21819]
**Resource Provider**

dataplane.

**Description of Feature or Work Requested**

Allow to generate and use sas with new options for datalakegen2, like:  sr= and sdd=, 
See more details in sas doc: https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#specify-the-directory-depth

**Minimum API Version Required**

Version 2020-02-10 and later

**Swagger Link**

n/a , no swagger change.

**Target Date**

asap

**Comment by yonzhan** [comment]
Storage
