### ISSUE TITLE
az monitor log-analytics workspace show returns duplicate property

### ISSUE THREAD

**Issue by fgheysels** [Azure/azure-cli#21811]
**Describe the bug**
I have an Azure DevOps pipeline where I execute the following command:

```azcli
az monitor log-analytics workspace show --resource-group <rgname> --workspace-name <wsname> | ConvertFrom-Json
```
This command suddenly fails with the following error message:

> ConvertFrom-Json : Cannot convert the JSON string because it contains keys with different casing. Please use the -AsHashTable switch instead. The key that was attempted to be added to the existing key 'eTag' was 'etag'.

When I execute the az monitor log-analytics workspace show command on my laptop, I can indeed see that the output of this command contains both an `etag` and an `eTag` property.

I can work-around this by specifying the `-HasHashTable` parameter as advised, but I don't think it it's meant that this property appears twice in the output/result.

![image](https://user-images.githubusercontent.com/3605786/160198410-952e6c37-5b94-4cbb-83d8-22196649fbe0.png)

**Environment summary**
- Powershell Core 7.2.1
- Azure CLI 2.34.1

**Comment by yonzhan** [comment]
monitor

**Comment by necusjz** [comment]
@fgheysels, thanks for catching this, the fix is on the way: https://github.com/Azure/azure-rest-api-specs/pull/18447.
