### ISSUE TITLE
'az acr taks create' missing remote tarball for the context

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#21817]
[Enter feedback here]

Hello, all !

Pls. have a look at the https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-build, where there are the following options to point to the context (source location): git repository, remote tarball and OCI artifact.

The link https://docs.microsoft.com/en-us/cli/azure/acr/task?view=azure-cli-latest#az-acr-task-create is missing remote tarball option:

'
--context -c
The full URL to the source code repository (Requires '.git' suffix for a github repo) or the repository of an OCI artifact in an Azure container registry (e.g., 'oci://myregistry.azurecr.io/myartifact:mytag'). If '/dev/null' is specified, the value will be set to None and ignored. This is a required argument if the task is not a system task.
'

Pls. fix it for 'az acr task create' as well as for the other parts of ACR documentations (if any)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0e3f3c-5aed-28b6-1e28-22ff32a8521d
* Version Independent ID: 128e5bc6-e518-bd5a-f511-48e0ed185739
* Content: [az acr task](https://docs.microsoft.com/en-us/cli/azure/acr/task?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/acr/task.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/acr/task.yml)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@alexeyshishkin01 Thank you for reaching out to us, we are looking into this request,
