### ISSUE TITLE
az cli command ignores cloud reg and defaults to public?

### ISSUE THREAD

**Issue by ryanewillis** [Azure/azure-cli#21828]
Hello,
What is the default behavior for az cli commands? I have a private (onprem) Azure Stack Hub cloud which is registered in az cli, but when running specific az commands, it seems to ignore the cloud reg and defaults to public cloud?

e.g. 
C:\windows\system32\windowspowershell\v1.0> Get-AzWebAppPublishingProfile -ResourceGroupName "rp01" -Name "test-AzureStack01" -Format "Ftp" -OutputFile "C:\Users\xxxxxx\Desktop\outputfile.publishsettings"

_Get-AzWebAppPublishingProfile : Your Azure credentials have not been set up or have expired, please run Connect-AzAccount to set up your Azure
credentials.
At line:1 char:1
+ Get-AzWebAppPublishingProfile -ResourceGroupName "rp01" -Name "test ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : CloseError: (:) [Get-AzWebAppPublishingProfile], ArgumentException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.GetAzureWebAppPublishingProfileCmdlet__

or

_Get-AzWebAppPublishingProfile : No subscription found in the context. Please ensure that the credentials you provided are authorized to access an
Azure subscription, then run Connect-AzAccount to login. 
At line:1 char:1
+ Get-AzWebAppPublishingProfile -ResourceGroupName "rp01" -Name "test ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : CloseError: (:) [Get-AzWebAppPublishingProfile], ApplicationException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.GetAzureWebAppPublishingProfileCmdlet_

Thanks.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8655f313-0a82-5fcc-e8f9-87199bbddcad
* Version Independent ID: ec2ef23a-6e82-937d-b8e0-02bca39bf603
* Content: [az cloud](https://docs.microsoft.com/en-us/cli/azure/cloud?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/cloud.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/cloud.yml)
* Service: **cloud-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ryanewillis** [comment]
Here is my cloud reg with private info removed. 
{
    "endpoints": {
      "activeDirectory": "https://login.microsoftonline.com",
      "activeDirectoryDataLakeResourceId": null,
      "activeDirectoryGraphResourceId": "https://graph.windows.net/",
      "activeDirectoryResourceId": "https://management.azurestackonprem.onmicrosoft.com/xxxxxxxxxxxxxxxxxxxxxxxxxx",
      "appInsightsResourceId": null,
      "appInsightsTelemetryChannelResourceId": null,
      "attestationResourceId": null,
      "azmirrorStorageAccountResourceId": null,
      "batchResourceId": null,
      "gallery": "https://providers.azurestack.local:30016/",
      "logAnalyticsResourceId": null,
      "management": "https://management.azurestackonprem.com",
      "mediaResourceId": null,
      "microsoftGraphResourceId": null,
      "ossrdbmsResourceId": null,
      "portal": null,
      "resourceManager": "https://management.azurestackonprem.com",
      "sqlManagement": null,
      "synapseAnalyticsResourceId": null,
      "vmImageAliasDoc": null
    },
    "isActive": true,
    "name": "azurestack",
    "profile": "latest",
    "suffixes": {
      "acrLoginServerEndpoint": null,
      "attestationEndpoint": null,
      "azureDatalakeAnalyticsCatalogAndJobEndpoint": null,
      "azureDatalakeStoreFileSystemEndpoint": null,
      "keyvaultDns": ".vault.azurestackonprem.com",
      "mariadbServerEndpoint": null,
      "mhsmDns": null,
      "mysqlServerEndpoint": null,
      "postgresqlServerEndpoint": null,
      "sqlServerHostname": null,
      "storageEndpoint": null,
      "storageSyncEndpoint": null,
      "synapseAnalyticsEndpoint": null
    }
  }

**Comment by yonzhan** [comment]
Please ask your Azure PowerShell question directly in azure-powershell repo.
