### ISSUE TITLE
"az managedapp definition create" CLI command does not provide a way to set the deployment mode

### ISSUE THREAD

**Issue by cbellee** [Azure/azure-cli#21827]
When developing and testing Azure Managed Applications I use the `az managedapp definition create` Azure CLI command to create the service catalog definition in their Azure subscription for testing prior to publishing in Azure Marketplace.

Currently, this CLI command does not provide a way to explicitly specify the Deployment Mode (i.e. Incremental or Complete), and the default mode that the managed app definition gets is “Complete”. 

In the portal, you are able to specify Incremental or Complete mode for deployment, but that switch is not available in the CLI.
The operation is included in the REST API body call as 'properties.deploymentPolicy'. This feature could theoretically be added to the CLI
[Application Definitions - Create Or Update - REST API (Azure Managed Applications) | Microsoft Docs](https://docs.microsoft.com/en-us/rest/api/managedapplications/application-definitions/create-or-update#applicationdeploymentpolicy)

**Describe the solution you'd like**
Provide a `--deployment-mode [incremental | complete]` parameter in the `az managedapp definition create` CLI command.

**Describe alternatives you've considered**
Portal, REST API, ARM Template

**Comment by cbellee** [comment]
Is there any update on this feature request?

**Comment by zhoxing-ms** [comment]
@cbellee We plan to develop and release it in the next sprint, and the expected release time is **07-04**. Is it acceptable?

**Comment by Jing-song** [comment]
Hi @cbellee , I noticed that `create` and `update` use the same API, so do we need add `--deployment-mode` for  `az managedapp definition update`?
