### ISSUE TITLE
[Feature]: Add warning for users of eventual change of default for "az network lb create" and "az network lb frontend-ip create"

### ISSUE THREAD

**Issue by brianlehr** [Azure/azure-cli#21831]
In the latest profile and the profiles that use the same api-version as latest profile, the default public IP used for creation for an LB frontend with "az network lb create" and/or "az network lb frontend-ip create" will be changed from Basic to Standard. In advance of eventual breaking change, would like to add warning for users.

Similar change done for "az vm create" - [https://github.com/Azure/azure-cli/pull/18662](https://github.com/Azure/azure-cli/pull/18662)

**Comment by yonzhan** [comment]
network

**Comment by brianlehr** [comment]
@necusjz I am not seeing this as completed when I test with latest cloud shell

brian@Azure:~$ az network lb create --name testinglbbasic --resource-group upgradetest --location westus 
{
  "loadBalancer": {
    "backendAddressPools": [
      {
        "etag": "W/\"76bf8845-6c44-4d33-bfd0-fcb4a317b462\"",
        "id": "/subscriptions/6bb4a28a-db84-4e8a-b1dc-fabf7bd9f0b2/resourceGroups/upgradetest/providers/Microsoft.Network/loadBalancers/testinglbbasic/backendAddressPools/testinglbbasicbepool",
        "name": "testinglbbasicbepool",
        "properties": {
          "provisioningState": "Succeeded"
        },
        "resourceGroup": "upgradetest",
        "type": "Microsoft.Network/loadBalancers/backendAddressPools"
      }
    ],
    "frontendIPConfigurations": [
      {
        "etag": "W/\"76bf8845-6c44-4d33-bfd0-fcb4a317b462\"",
        "id": "/subscriptions/6bb4a28a-db84-4e8a-b1dc-fabf7bd9f0b2/resourceGroups/upgradetest/providers/Microsoft.Network/loadBalancers/testinglbbasic/frontendIPConfigurations/LoadBalancerFrontEnd",
        "name": "LoadBalancerFrontEnd",
        "properties": {
          "privateIPAllocationMethod": "Dynamic",
          "provisioningState": "Succeeded",
          "publicIPAddress": {
            "id": "/subscriptions/6bb4a28a-db84-4e8a-b1dc-fabf7bd9f0b2/resourceGroups/upgradetest/providers/Microsoft.Network/publicIPAddresses/PublicIPtestinglbbasic",
            "resourceGroup": "upgradetest"
          }
        },
        "resourceGroup": "upgradetest",
        "type": "Microsoft.Network/loadBalancers/frontendIPConfigurations"
      }
    ],
    "inboundNatPools": [],
    "inboundNatRules": [],
    "loadBalancingRules": [],
    "probes": [],
    "provisioningState": "Succeeded",
    "resourceGuid": "3ca992e4-8bfe-48bd-96fb-c640eb93cb39"
  }
}

**Comment by brianlehr** [comment]
I see the warning now, thank you @necusjz
