### ISSUE TITLE
VMSS Flex: Enable Single Placement Group

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#21834]
**Resource Provider**

Microsoft.compute

**Description of Feature or Work Requested**

Enable --single-placement-group true for flexible orchestration mode deployments (default should still be false)

**Certain vmss flex deployments with specialty skus requires single-placement-group=true**
PS C:\Users\fisteele> az vmss create -n mseriescli -g specialtysku --orchestration-mode flexible --platform-fault-domain-count 2 -l eastus2euap --image UbuntuLTS --vm-sku Standard_M8ms
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"error\": {\r\n    \"code\": \"OperationNotAllowed\",\r\n    \"message\": \"Virtual Machine Scale Sets with Flexible Orchestration Mode and a fault domain count of 2, or Virtual Machines referencing such Virtual Machine Scale Sets can only use VM Size Standard_M8ms, if single placement group on such Virtual Machine Scale Sets is set to true.\"\r\n  }\r\n}"}]}}

**It looks like there is a client side block on this scenario. I believe this was as designed; when we went GA we did not expect to ever enable single placement group. Now we know we do need single placement group**
PS C:\Users\fisteele> az vmss create -n mseriescli -g specialtysku --orchestration-mode flexible --platform-fault-domain-count 2 -l eastus2euap --image UbuntuLTS --vm-sku Standard_M8ms --single-placement-group true
usage error: --single-placement-group can only be set to False for Flex mode
PS C:\Users\fisteele>

**Minimum API Version Required**

2021-07-01

**Swagger Link**

This is live in production, regular CRP Swagger link

**Target Date**

4/15/2022

**Comment by yonzhan** [comment]
VMSS Flex

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele Hi, because the work of this sprint has been fully arranged, and the interval of this sprint is short due to Chinese Labor Day, so I'm worried that we don't have enough time to develop and release this requirement in this sprint. 
May I ask can this feature be postponed to the next sprint (release date: 05-24)?

**Comment by fitzgeraldsteele** [comment]
5/24 is great, thank you!

**Comment by PARADISSEEKR** [comment]
Hi, @fitzgeraldsteele , When I test `az vmss create -n mseriescli -g specialtysku --orchestration-mode flexible --platform-fault-domain-count 2 -l eastus2euap --image UbuntuLTS --vm-sku Standard_M8ms --single-placement-group true` , 
service returned the error `Operation could not be completed as it results in exceeding approved standardMSFamily Cores quota. Additional details - Deployment Model: Resource Manager, Location: EastUS2EUAP, Current Limit: 0, Current Usage: 0, Additional Required: 16, (Minimum ) New Limit Required: 16.` ， how can I fix it， or could you please provide some other test examples(other region or sku)?

**Comment by fitzgeraldsteele** [comment]
You don't have quota for that SKU. You need to request quota for M series. Or N series - both will work

**Comment by PARADISSEEKR** [comment]
> You don't have quota for that SKU. You need to request quota for M series. Or N series - both will work

I have submitted the request, how long will it take to succeed?
![image](https://user-images.githubusercontent.com/37168047/165666242-5be85c11-3f26-4ad8-a839-ccef7ca3901b.png)

**Comment by fitzgeraldsteele** [comment]
If manual approval, maybe a day or two. Did you try the automated request process?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PARADISSEEKR** [comment]
@fitzgeraldsteele  The request passed, but with a new error: 
az vmss create -n vmss -g rg --orchestration-mode flexible --platform-fault-domain-count 2 -l eastus2euap --image UbuntuLTS --vm-sku Standard_M8ms --single-placement-group true
 `The requested VM size Standard_M8ms is not currently supported by Virtual Machine Scale Sets with Flexible Orchestration Mode or by Virtual Machines referencing such Virtual Machine Scale Sets.`

**Comment by fitzgeraldsteele** [comment]
You'll need to register your subscription for the feature flag:


  1.  Register your subscription to use the SpecialSkusForVmssFlex feature flag

az feature register --namespace Microsoft.Compute --name SpecialSkusForVmssFlex

See [?docx icon]  VMSS Flex + Specialty Skus Preview.docx<https://microsoft.sharepoint.com/:w:/t/vmssvmorchestrationmode/EStc7sYXvONOmlWtAUsOqLcBwMssWkqhgg0CaCPtklVFTw?e=1nzL0k> for more info about the preview
