### ISSUE TITLE
add context for Dockerfile

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#21847]
[Enter feedback here]

Hello, all !

This question is regarding 'az acr build' command - https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-build

It implies that Docker file and the source code have to be in the same context (local, git repository, remote tarball or repository of OCI artifact).

Consider the following case:
- there's a git repository (ex. https://github.com/postgres/postgres)
- there's no Dockerfile in this repository so far
- there's no way to add Dockerfile to this repository so far

The questions is how to build an image for this case ?

One way of doing that could be adding a context for Dockerfile, like '--filecontext' parameter which describes a context for Dockerfile if it's not in the git repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/acr.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/acr.yml)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@alexeyshishkin01 Thank you for reaching out, let me get back to you with an update.

**Comment by PramodValavala-MSFT** [comment]
@alexeyshishkin01 You can already achieve this with one of the following options

**1. Setup Context Locally**
This is straightforward where you get all the files you need locally first, and then call the command to queue the build which will upload the local context to ACR.

**2. Pull External Sources in your Dockerfile**
This is the better approach since you don't have to download/upload files. Instead your Dockerfile will have all required steps and would run completely in ACR.

You could either `git clone` the repository using a `RUN` command or even add the archive as mentioned in [this comment](https://github.com/moby/moby/issues/14704#issuecomment-355166976).

**Comment by alexeyshishkin01** [comment]
ok, the following command does the job:

az acr build --image acr:{{.Run.ID}} --image acr:latest --registry $PGPROACR --file Dockerfile https://github.com/Azure/acr-cli.git

**Comment by PramodValavala-MSFT** [comment]
@alexeyshishkin01 Glad to hear that! Closing this issue.

**Comment by PramodValavala-MSFT** [comment]
@alexeyshishkin01 Yes. Ideally you would have to build the container for every update. Could you elaborate on your scenario?

**Comment by alexeyshishkin01** [comment]
my scenario is on very top of this chat, I'm duplicating it:

This question is regarding 'az acr build' command - https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-build

It implies that Docker file and the source code have to be in the same context (local, git repository, remote tarball or repository of OCI artifact).

Consider the following case:

there's a git repository (ex. https://github.com/postgres/postgres)
there's no Dockerfile in this repository so far
there's no way to add Dockerfile to this repository so far
The questions is how to build an image for this case ?

One way of doing that could be adding a context for Dockerfile, like '--filecontext' parameter which describes a context for Dockerfile if it's not in the git repository.

**Comment by PramodValavala-MSFT** [comment]
@alexeyshishkin01 If its just building a container, then either one of the options should work for. To keep up with the remote changes, you would just have to automate it to build whenever there are new changes in the repo.
