### ISSUE TITLE
"az acr task run" does not return status code 1 when run fails

### ISSUE THREAD

**Issue by oleterno-equinor** [Azure/azure-cli#21846]
## Describe the bug
When running `az acr task run` and the task fails, the exit code for the command is 0. 

**Command Name**
`az acr task run`

**Errors:**
```
$ az acr task run \
    --name my-acr-task \
    --registry my-acr \
    --context https://github.com/org/repo.git#branch \
    --file https://github.com/org/repo.git#branch/path/to/Dockerfile \
    --subscription xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Sending context to registry: my-acr...
Queued a run with ID: cg83p2d
...
2022/03/29 12:55:40 Output from dependency scanning: error opening dockerfile: Dockerfile, error: open Dockerfile: no such file or directory
failed to run step ID: acb_step_0: failed to scan dependencies: exit status 1
Run ID: cg83p2d failed after 8s. Error: failed during run, err: exit status 1

$ echo $?
0
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create an acr task. The task itself is not relevant to this bug.
- Run the task with `az cli` and use some false values to make the task run fail. 
- `az acr task run --name {} --registry {} --context {} --file {} --subscription {}`
- Echo the exit code of the last performed command. 
- `echo $?`

## Expected Behavior
The task run should return with exit code 1 when the task run fails. When running `az acr build` it does exactly that, which makes me see this as a bug. 

Here is an example output when running `az acr build` and it fails:

```
$ az acr build \
    -t my-acr.azurecr.io/image:y8r4r \
    -r my-acr https://github.com/org/repo.git#branch \
    -f https://github.com/org/repo.git#branch/path/to/Dockerfile \
    --no-push
Sending context to registry: my-acr....
Queued a build with ID: cg28p86
...
2022/03/29 13:11:30 Output from dependency scanning: error opening dockerfile: https://github.com/org/repo.git#branch/path/to/Dockerfile, error: open https://github.com/org/repo.git#branch/path/to/Dockerfile: no such file or directory
failed to run step ID: build: failed to scan dependencies: exit status 1

Run ID: cg28p86 failed after 5s. Error: failed during run, err: exit status 1
Run failed

$ echo $?
1
```

## Environment Summary
```
macOS-12.3-x86_64-i386-64bit, Darwin 21.4.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1

Extensions:
aks-preview 0.5.58
azure-devops 0.25.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
acr

**Comment by SaurabhSharma-MSFT** [comment]
@oleterno-equinor I am redirecting this to services team to look into and provide their inputs.

**Comment by indirect** [comment]
This bug is not fixed, and should not have been closed by #21983. You can still reproduce it using the reproduction steps in the original post.

**Comment by martinemde** [comment]
@SaurabhSharma-MSFT this is still failing. The PR that closed this issue was unrelated (maybe a typo of the issue number).

**Comment by SaurabhSharma-MSFT** [comment]
@zhoxing-ms Can you please help here.

**Comment by zhoxing-ms** [comment]
@northtyphoon Could you please help look at this issue again?

**Comment by martinemde** [comment]
Since this doesn't seem to be getting attention and since the ticket isn't even re-opened, here is a workaround I settled on until it's fixed. Hopefully it will help someone else:

```
                output=$( \
                  az acr task run --registry=$(CONTAINER_REGISTRY_NAME) \
                  --name=build-final-image \
                  --context=https://github.com/WorldHealthOrganization/ihrbenchmark.git#$(build.SourceVersion) \
                  --arg COMMIT_SHA=$(Build.SourceVersion) \
                  --arg DOCKER_IMAGE_TAG=$(buildVersionTag) \
                  --arg DOCKER_IMAGE_TAG=$(dockerTag) \
                  --arg BUILDER_IMAGE=$(builderImageName) 2>&1 \
                )

                echo "$output"

                if [[ $output =~ "Error: failed during run" ]]; then
                  exit 1
                fi```

**Comment by martinemde** [comment]
Since this doesn't seem to be getting attention and since the ticket isn't even re-opened, here is a workaround I settled on until it's fixed. Hopefully it will help someone else:

```
output=$( \
  az acr task run --registry=$(CONTAINER_REGISTRY_NAME) \
  ... \
)

echo "$output"

if [[ $output =~ "Error: failed during run" ]]; then
  exit 1
fi
```
