### ISSUE TITLE
az kusto data-connection event-hub create , missing docs for --event-system-properties

### ISSUE THREAD

**Issue by jci-zimm** [Azure/azure-cli#21849]
Az CLI command `az kusto data-connection event-hub create`  is missing sufficient docs to use opt arg **`--event-system-properties`** [documented here](https://docs.microsoft.com/en-us/cli/azure/kusto/data-connection/event-hub?view=azure-cli-latest#az-kusto-data-connection-event-hub-update-optional-parameters). 

A user may wish to select multiple event-system-properties, what is missing from the docs is how to include multiple properties. Is it a space, comma, or semicolon separated list?

E.g. should it be 

```
az kusto data-connection event-hub create ... --event-system-properties "x-opt-enqueued-time iothub-connection-device-id"
``` 
Above i'm attempting to add properties `x-opt-enqueued-time` and `iothub-connection-device-id`.  Describing the format of this argument for multiple properties would be appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7172063-2683-0fe3-4f80-809c1e5a93a6
* Version Independent ID: 683fc430-2df1-815a-2ff4-0368884bee03
* Content: [az kusto data-connection event-hub](https://docs.microsoft.com/en-us/cli/azure/kusto/data-connection/event-hub?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/kusto/data-connection/event-hub.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/kusto/data-connection/event-hub.yml)
* Service: **data-explorer**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jci-zimm** [comment]
Trial and error, eventually got it to work via: 
```
--event-system-properties "x-opt-enqueued-time" "iothub-connection-device-id"
```

Some type of additional info would be helpful versus the current docs: 

![image](https://user-images.githubusercontent.com/83723367/160683286-a24c1670-ce4d-40dc-9041-f44a994e38e0.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@jci-zimm Apologies for the delay. The above PR has been filed and it is under review. In the meantime if you have any questions, please feel free to ask.
