### ISSUE TITLE
Frontdoor link-to-default-domain is enabled

### ISSUE THREAD

**Issue by arunvc** [Azure/azure-cli#21844]
**--link-to-default-domain** was **Disabled** but on response json

`"linkToDefaultDomain": "Enabled",`

```
 az afd route create -g "rg-eastus" --custom-domains "test" \
 --endpoint-name "test-ep" --profile-name "profile1" --route-name "test-route" \
 --https-redirect Enabled --origin-group "test-group" \
 --supported-protocols Http Https \
 --link-to-default-domain "Disabled" \
 --forwarding-protocol HttpOnly
```

**Comment by SatishBoddu-MSFT** [comment]
Hello @arunvc Thanks for reporting this issue!

For further actions we are routing this issue to Service Team's attention!!
![image](https://user-images.githubusercontent.com/62923178/162315161-707bc3ce-4ea6-46d1-a3dc-d7fe633b6dc9.png)
