### ISSUE TITLE
Support Ubuntu 22.04 Jammy Jellyfish

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#21857]
According to https://wiki.ubuntu.com/Releases, Ubuntu 22.04 Jammy Jellyfish will be released on April 21, 2022.

As this is a LTS version of Ubuntu, Azure CLI should publish `jammy` package as soon as Ubuntu 22.04 Jammy Jellyfish becomes available.

### Additional information

- https://packages.microsoft.com/ has now support zstd compression which is the standard since Ubuntu 21.10
- Azure CLI's `jammy` Linux repo has already been created: https://packages.microsoft.com/repos/azure-cli/dists/jammy/
- https://github.com/Azure/azure-cli/issues/21532
- https://github.com/Azure/azure-cli/pull/21151

**Comment by yonzhan** [comment]
Jammy Jellyfish

**Comment by jiasli** [comment]
> The azure-cli package from focal does not install on jammy anymore (used to work until this weekend).

The focal package is never compatible with jammy. Many commands will fail due to incompatible binary files.

> With jammy (hopefully) released end of april - can we get working jammy repositories? Currently they look empty.

This is because jammy hasn't been officially released yet. We will support it once it is officially released.

**Comment by jiasli** [comment]
If you do want to use Azure CLI on the unreleased Jammy, you may manually add the `impish` repo and give it a try: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions, but it is not guaranteed to work.

**Comment by ctophs** [comment]
> If you do want to use Azure CLI on the unreleased Jammy, you may manually add the `impish` repo and give it a try: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions, but it is not guaranteed to work.

I tried using the impish package but as I said there is a breakage concerning jammy libssl and impish package has the same non-problem. Jammy goes openssl 3 so for jammy I now build from source.

**Comment by sbrunner** [comment]
The repository steals be empty, can you notify us in this ticket when he is available?
Thanks in advance :-)

**Comment by jiasli** [comment]
> The repository steals be empty, can you notify us in this ticket when he is available? Thanks in advance :-)

It will be available since Azure CLI 2.36.0, which will be released on 2022-04-26.

**Comment by sbrunner** [comment]
Thanks :-)

**Comment by jiasli** [comment]
I have released an edge build for Jammy at https://aka.ms/InstallAzureCliJammyEdge. You may follow https://github.com/Azure/azure-cli#edge-builds to install it.

The official instruction will be added by https://github.com/Azure/azure-cli/pull/21993.

**Comment by sbrunner** [comment]
Thanks, first test is working well :-)
