### ISSUE TITLE
Can't list blob information when a blob is leased

### ISSUE THREAD

**Issue by LoofahBu** [Azure/azure-cli#21856]
**Describe the bug**
I want to check whether a blob is leased so I execute command below:

``
az storage blob show --account-name xxx -c xxx --name xxx --query 'properties.lease.status' -otsv
``

It only works when a blob's lease status is unlocked.

If I try to show a blob which lease status is leased, it will get stuck until it reaches the timeout limit.

**To Reproduce**
Run the command above on two blobs. One lease status is unlocked, another is leased.

**Expected behavior**
When I execute the command, a leased blob can show its lease status.

**Environment summary**
- macOS Monterey 12.2.1
- Azure CLI 2.20.0

**Additional context**
None

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Should be storage blob service issue

**Comment by LoofahBu** [comment]
@navba-MSFT I upgraded version to 2.34.1 and it works! Thanks!

**Comment by navba-MSFT** [comment]
@LoofahBu Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
