### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)

### ISSUE THREAD

**Issue by LydsLido** [Azure/azure-cli#21868]
**Describe the bug**
1. Azure cloud shell not opening: both Bash and Powershell
2. Therefore I Installed azure-cli-2.34.1 and tried to login to Azure. Browser login is successful, but on command prompt get the below error:
>az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)

**To Reproduce**
az login on command prompt

**Expected behavior**
should get the azure command prompt with user logged in

**Environment summary**
Windows 10

C:\Users\310176540>az --version
azure-cli                         2.34.1

core                              2.34.1
telemetry                          1.0.6

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\310176540\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Additional context**
Logs of the problem:
[Az_Login_Error_log.txt](https://github.com/Azure/azure-cli/files/8380949/Az_Login_Error_log.txt)

**Comment by yonzhan** [comment]
@jiasli for awareness
