### ISSUE TITLE
App Service list locations with linux workers enabled?

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#2187]
I tried creating a linux worker plan in centralus (the location of my RG) and got the following error.
```
$ az appservice plan create -g com-appservice-1 -n com-plan-1 --sku S1 --is-linux 
Plan with linux worker is not supported in current region. Run 'az appservice list-locations --linux-workers-enabled' to cross check
```

I tried to run the command that's suggested but that command no longer exists.
```
$ az appservice list-locations --linux-workers-enabled
az: error: unrecognized arguments: --linux-workers-enabled
usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {appservice} ..
```

```
$ az appservice list-locations --help

Command
    az appservice list-locations: Get a list of available geographical regions.
        Get a list of available geographical regions.

Arguments
    --sku      : Name of SKU used to filter the regions.
```

Version info:
```
azure-cli (0.1.2rc1)
appservice (0.1.1b3)
Python (Darwin) 2.7.10 (default, Jul 30 2016, 19:40:32) 
```

**Is there still a way to list locations with linux workers enabled through the CLI?**

**Comment by derekbekoe** [comment]
After some searching through the online documentation of the service, I did find this.
https://docs.microsoft.com/en-us/azure/app-service-web/app-service-linux-intro

> This public preview is currently only available in the following regions:
West US
West Europe
Southeast Asia

**Comment by yugangw-msft** [comment]
Thanks for spotting this. ` az appservice list-locations` is an auto-command, but the new SDK has changed the signature with function loss. Looks like even for auto-command, we still need test coverage.

**Comment by yugangw-msft** [comment]
The swagger spec is being updated to get this API back.  https://github.com/Azure/azure-rest-api-specs/pull/991

**Comment by Mmdixon** [comment]
I get the same error with:
```
azure-cli (2.0.4)
appservice (0.1.4)
Python (Windows) 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
```

**Comment by yugangw-msft** [comment]
fixed in the upcoming release
