### ISSUE TITLE
Changes needed in az-restore-point and az-restore-point collection cmdlets to support cross region copy

### ISSUE THREAD

**Issue by dikethir** [Azure/azure-cli#21878]
**Is your feature request related to a problem? Please describe.**
Three issues:

1. az restore-point collection show – is returning all the restore points even without the –expand parameter. 
2. az restore-point show does not have a way to get the instance view details of the restore point. 
3. In az restore-point create, sourceRestorePointId is not listed as an input optional parameters. This is needed for cross region copy of restore points scenario. sourceRestorePointId is the Resource Id of the source restore point from which a copy needs to be created. 

**Describe the solution you'd like**

1.  *az restore-point collection show* should have an optional –restore-points parameter. Only when this parameter is specified we need to return all the restore points inside the restore point collection. Without the –restore-points parameter, az restore-point collection should not show restore points inside it as this is an expensive operation  When using the REST APIs, we need to specify "$expand=RestorePoints" in the URL to get the restore points inside the collection.
2.  *az restore-point show* should have an  –instance-view parameter to get the instance view details of the restore point. Without the --instance-view parameter the instance view details of the restore point should not be returned.
3. *az restore-point create* should have an sourceRestorePointId optional parameter to support cross region copy of restore points. sourceRestorePointId is the Resource Id of the source restore point from which a copy needs to be created. Link to the API reference doc: https://docs.microsoft.com/en-us/rest/api/compute/restore-points/create#request-body

**Additional context**
Link to public documentation: https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-create-restore-points#copy-a-vm-restore-point-between-regions
Link to API reference for restore points: https://docs.microsoft.com/en-us/rest/api/compute/restore-points
Link to API reference for restore points collection: https://docs.microsoft.com/en-us/rest/api/compute/restore-point-collections

**Comment by yonzhan** [comment]
Compute
