### ISSUE TITLE
Double quote is required for --pattern

### ISSUE THREAD

**Issue by zhangyuezhong** [Azure/azure-cli#21876]
[Enter feedback here]
https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-upload-batch

az storage blob upload-batch -d mycontainer --account-name mystorageaccount --account-key 00000000 -s <path-to-directory> **--pattern *.py** --if-unmodified-since 2018-08-27T20:51Z

I think we need double quote ".py"  otherwise, invalid argument error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/blob.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/blob.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by amkondi** [comment]
Hello,

it's still not working what ever the way that you will use it will just break your neurves

Example :
az storage blob download-batch -d . -s $blob --pattern downloads/* --account-name $storageAccName --account-key $key --overwrite $true
Error :
az : 
Au caractère Ligne:1 : 1
+ az storage blob download-batch -d . -s $blob --pattern downloads/* -- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
  
  Link to the official doc : 
  https://learn.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-download-batch-examples

**Comment by calvinhzy** [comment]
Hi @amkondi, can you run `az storage blob list` to show all the blobs, and which specific ones you are trying to download? 
You can check what cli version you are running with `az version`
![image](https://github.com/Azure/azure-cli/assets/17182306/9c0771c8-7d6e-499a-b172-2a2036fc982e)

**Comment by gleason-m** [comment]
Seeing this bug as well. 

Repro folder structure:
data/
  - file.json
  - file.csv
package.json

az storage blob upload-batch --account-name <account> -d <container> -s ./data --pattern *.json --overwrite --auth-mode login --verbose --dryrun

output:
upload action: from /home/mglea/src/az_storage_repro/data to <container>
    pattern package.json
  container <container>
       type block
      total 0
[]

Notice, the pattern in output is the "package.json" from the cwd where the command was run.

Output with the pattern in double quotes:
az storage blob upload-batch --account-name <account> -d <container> -s ./data --pattern "*.json" --overwrite --auth-mode login --verbose --dryrun
upload action: from /home/mglea/src/az_storage_repro/data to <container>
    pattern *.json
  container <container>
       type block
      total 1
[
  {
    "Blob": <blob_url>,
    "Last Modified": null,
    "Type": "application/json",
    "eTag": null
  }
]
Command ran in 0.517 seconds (init: 0.136, invoke: 0.381)

**Comment by calvinhzy** [comment]
Hi @gleason-m, I am using Windows and PowerShell 7.4 and both with and without quotes would return the same result. Which platform and terminal are you using by any chance? I can just make the help/example to include double quotes for all platforms.
![image](https://github.com/Azure/azure-cli/assets/17182306/a51c3978-5712-4f33-b3f1-7b345fcdc0f3)

**Comment by gleason-m** [comment]
@calvinhzy Ubuntu 22.04 on WSL

**Comment by calvinhzy** [comment]
@gleason-m I can reproduce this in WSL. Will add the double quotes to the help info. Quoting behavior is likely environment dependent.
