### ISSUE TITLE
az afd secret create not working

### ISSUE THREAD

**Issue by LotteVoorhorst** [Azure/azure-cli#21882]
## Describe the bug

**Command Name**
`az afd secret create`

**Errors:**
```
(InternalServerError) The server encountered an internal error. Please try again later.
Code: InternalServerError
Message: The server encountered an internal error. Please try again later.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az afd secret create --resource-group {} --profile-name {} --secret-name {} --use-latest-version {} --secret-source {}`

## Expected Behavior
The secret (certificate) can be added from the keyvault it's in.

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1

Extensions:
front-door 1.0.16

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```
## Additional Context
 This doesn't work with the CLI or with the portal.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by LotteVoorhorst** [comment]
For additional information, this error seems to occur when the tenant-based Service Principal has not been added. After adding it, this error doesn't occur anymore. Not closing the ticket, since the error information could be clearer.

**Comment by SaurabhSharma-MSFT** [comment]
@LotteVoorhorst I am not able to reproduce this.  I have tried this without adding CDN profile service principal to Key vault access policy and getting the correct error information -
![image](https://user-images.githubusercontent.com/38112130/163067506-58417185-8c41-4325-9918-435ee82ec9bc.png)
I am using the same extension version as yours.

**Comment by SaurabhSharma-MSFT** [comment]
@LotteVoorhorst We will now proceed to close this thread as we haven't heard back. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
