### ISSUE TITLE
Heading is incorrectly capitalized

### ISSUE THREAD

**Issue by rvandenbedem** [Azure/azure-cli#21886]
"Azure VMWare Solution" heading needs to change to "Azure VMware Solution".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f53521a1-d23a-9b87-d41e-7d0b096cbcdd
* Version Independent ID: 22703361-7e6b-3436-0ff8-87d7698f5143
* Content: [Azure VMWare Solution](https://docs.microsoft.com/en-us/cli/azure/service-page/azure%20vmware%20solution?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/service-page/Azure VMWare Solution.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/service-page/Azure VMWare Solution.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by jsntcy** [comment]
Need update service name in https://github.com/Azure/azure-cli-extensions/blob/main/src/service_name.json

**Comment by rvandenbedem** [comment]
Closing, change captured in this pull request: https://github.com/Azure/azure-cli-extensions/pull/4633
