### ISSUE TITLE
[AppService] No resource name completion on 'az appservice web config hostname list'

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#2189]
```
$ az appservice web config hostname list -g com-appservice-1 --webapp-name <tab><tab>
```

This should have should my web apps but returns nothing in tab completion.

**Comment by yugangw-msft** [comment]
This was broken by #1985 which renamed the parameter, but didn't update the params.py file
//cc: @twitchax
I will fix it today

**Comment by twitchax** [comment]
Awesome: thanks!
