### ISSUE TITLE
az artifacts documentation not easy to follow

### ISSUE THREAD

**Issue by hvl71** [Azure/azure-cli#21896]
As a user of AZ CLI it is hard to figure out what the 
az artifacts universal
az artifacts universal download
az artifacts universal publish

commands actually do and how they should be used.

as seen on:
https://docs.microsoft.com/en-us/cli/azure/artifacts?view=azure-cli-latest

what does universal mean? It would be super helpful to many many az users with a few examples and possibly an explanation about the universal part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ae588e5-6e79-0a3e-56fb-78976019b011
* Version Independent ID: 70e209c8-948c-8baf-3472-e1920c498a2c
* Content: [az artifacts universal](https://docs.microsoft.com/en-us/cli/azure/artifacts/universal?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/artifacts/universal.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/artifacts/universal.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@hvl71 The [official doc](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops) explains this in detail. This is only the reference doc for the sub-command.
