### ISSUE TITLE
az network bastion ssh fails with 'Profile' object has no attribute 'get_msal_token'

### ISSUE THREAD

**Issue by dweverett** [Azure/azure-cli#21909]
## Describe the bug

**Command Name**
`az network bastion ssh`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'Profile' object has no attribute 'get_msal_token'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/network/custom.py", line 8146, in ssh_bastion_host
    azssh.ssh_cert(cmd, cert_path=os.path.join(cert_folder, "id_rsa.pub-aadcert.pub"))
  File "/home/deverett/.azure/cliextensions/ssh/azext_ssh/custom.py", line 33, in ssh_cert
    cert_file, _ = _get_and_write_certificate(cmd, public_key_file, cert_path)
  File "/home/deverett/.azure/cliextensions/ssh/azext_ssh/custom.py", line 58, in _get_and_write_certificate
    _, certificate = profile.get_msal_token(scopes, data)
AttributeError: 'Profile' object has no attribute 'get_msal_token'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.  

This is on a Windows 11 computer using Windows Subsystem for Linux.

az network bastion ssh --name "<bastionname>" --resource-group "<rgname>" --target-resource-id "<ResourceURIofUbuntu20.04VM>" --auth-type  "AAD"

Azure bash shell also fails with this error:

Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The generated SSH keys are stored at /tmp/aadsshcertlox4cdqq. Please delete SSH keys when the certificate is no longer being used.
VM SSH currently doesn't support managed identity or Cloud Shell.

The az network bastion ssh --name command fails regardless of connection type, but --auth-type "AAD" is desired.

## Expected Behavior

Tunnel should be established.

## Environment Summary
```
Linux-4.4.0-22000-Microsoft-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.12
Installer: DEB

azure-cli 2.34.1

Extensions:
ssh 0.1.5

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by kairu-ms** [comment]
Hi @aavalang, please have a look. Thanks.

**Comment by navba-MSFT** [comment]
@dweverett Apologies for the late reply. Thanks for reaching out to us and sharing this feedback.

Here is the snippet of your error message:

>File "/home/deverett/.azure/cliextensions/ssh/azext_ssh/custom.py", line 58, in _get_and_write_certificate
    _, certificate = profile.get_msal_token(scopes, data)
AttributeError: 'Profile' object has no attribute 'get_msal_token'

profile.get_msal_token is guarded. See Lines 161 to 169 in this:
[azure-cli-extensions/src/ssh/azext_ssh/custom.py](https://github.com/Azure/azure-cli-extensions/blob/4e4b9c2f225ca4236667d47465b140e40eb202bc/src/ssh/azext_ssh/custom.py#L161-L169)


Also, your `/home/deverett/.azure/cliextensions/ssh/azext_ssh/custom.py` doesn't match the content of https://github.com/Azure/azure-cli-extensions/blob/4e4b9c2f225ca4236667d47465b140e40eb202bc/src/ssh/azext_ssh/custom.py

Looks like your file is somehow not updated correctly. Please delete/home/deverett/.azure/cliextensions/ssh and try to install again with the below command:

>az extension add --name ssh

Hope this helps. Awaiting your reply.

**Comment by dweverett** [comment]
Thank you! Deleting "/home/<username>/.azure/cliextensions/ssh" and running "az extension add --name ssh" resolved my issue.

I wasn't sure if running "az extension add --name ssh" was required or not.  This guidance is not discussed in Step 2 under the "Azure AD" section of this doc (https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-linux), its only discussed under the "SSH" section. 

Also, the Note in the "az ssh" doc "https://docs.microsoft.com/en-us/cli/azure/ssh?view=azure-cli-latest" says, "This reference is part of the ssh extension for the Azure CLI (version 2.4.0 or higher). The extension will automatically install the first time you run an az ssh command. Learn more about extensions." I ran "sudo apt update && sudo apt upgrade" but my version of azure-cli is 2.34.1 which appears to be too old to autoupdate, and "az upgrade" says I have the latest version.

**Comment by aavalang** [comment]
ssh extension is required for the bastion operation. I know there were some breaking changes in SSH extension to get the token for which we had made change. Looks like you had latest cli core but ssh extension wasnt latest. 1.0.1 or later of ssh extension should fix this issue.
