### ISSUE TITLE
Error when creating aks cluster

### ISSUE THREAD

**Issue by aeortic** [Azure/azure-cli#21902]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

When running 
"az aks create --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER --node-count $NODES"

Which attempted to create

/subscriptions/1ce38113-49dd-4462-b657-beef2b90b5d1/resourceGroups/devclusterrg2/providers/Microsoft.Resources/deployments/microsoft.aks-20220401104010/operations/21C27FB181386007

I get the error

"Values of identifierUris property must use a verified domain of the organization or its subdomain: '[https://74def9.devcluster-devclusterrg2-1ce381.eastus.cloudapp.azure.com']()"

**To Reproduce**

See above

**Expected behavior**

I expected to that I would be able to create a cluster with the command.

**Environment summary**

az command line interface

**Additional context**

I was able to create an aks cluster through the web portal as a work around.

**Comment by SaurabhSharma-MSFT** [comment]
@aeortic We are looking into it and get back to you for any questions.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by DominusFlevit** [comment]
Running that command results in:
![image](https://user-images.githubusercontent.com/55561970/163469672-2d84bd06-4c1c-41bc-9b6b-8e3b14dd518c.png)

**Comment by the-artist-henry** [comment]
[image](https://user-images.githubusercontent.com/23616928/163471800-90d3f54d-4d78-4a7d-8352-c63b1fe6c2e2.jpeg)

**Comment by SatishBoddu-MSFT** [comment]
> Running that command results in: ![image](https://user-images.githubusercontent.com/55561970/163469672-2d84bd06-4c1c-41bc-9b6b-8e3b14dd518c.png)

Hello @aeortic ,

Did you check the CLI and extension versions? Is it running fine on the Azure Portal cloud shell? (Which Region is used?)

I was able to run the same command from the Azure cloud shell and from my Windows PC Command line! (West US 2)

![image](https://user-images.githubusercontent.com/62923178/163478417-8b728577-3f35-4f72-8057-5a4b42459646.png)

**Comment by SatishBoddu-MSFT** [comment]
Since we didn't receive any response, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.

**Comment by doggy8088** [comment]
@SatishBoddu-MSFT I'm suffering by the same of this issue today. Has no clue how to fix this.
