### ISSUE TITLE
Incorrect spelling in example instructions

### ISSUE THREAD

**Issue by MindlessMuppet** [Azure/azure-cli#21901]
In the section 'az mysql server ad-admin create', the example appears to have the incorrect spelling of the word 'Create'.

'Crate Active Directory Administrator username@domain.com in the server testsvr.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52c4d40c-b3ed-5ca3-df62-f0920ee3550f
* Version Independent ID: fe543012-30b7-b727-e754-bb2d486c175c
* Content: [az mysql server ad-admin](https://docs.microsoft.com/en-us/cli/azure/mysql/server/ad-admin?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/mysql/server/ad-admin.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/mysql/server/ad-admin.yml)
* Service: **mysql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@MindlessMuppet Thank you for reaching out to us. We are looking into it.
