### ISSUE TITLE
az vm list fails for AzureUSGovernment

### ISSUE THREAD

**Issue by devkeydet** [Azure/azure-cli#2190]
I created a new context for AzureUSGovernment, switched to it, then executed 'az vm list' and got the following:

The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'. The suppo
rted api-versions are '2015-05-01-preview,2015-06-15,2016-03-30,2016-08-30'.

**Comment by derekbekoe** [comment]
@devkeydet What version of the CLI are you running?
`az --version`

**Comment by devkeydet** [comment]
I realized I may not have the latest version, so I updated.  Now I have 0.1.2rc1.  However, az context seems to be gone.  How do I switch to an environment other than AzureCloud?

**Comment by derekbekoe** [comment]
` az cloud set --name AzureUSGovernment `

**Comment by devkeydet** [comment]
I still get:

The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'. The supported api-versions are '2015-05-01-preview,2015-06-15,2016-03-30,2016-08-30'.

Repro:

az cloud set --name AzureUSGovernment
az login
az vm list

az --version results in:

azure-cli (0.1.2rc1)

acr (0.1.1b2)
acs (0.1.2rc1)
appservice (0.1.1b3)
batch (0.1.1b3)
cloud (0.1.2rc1)
component (0.1.1rc1)
configure (0.1.2rc1)
container (0.1.1b2)
context (0.1.1b2)
core (0.1.2rc1)
documentdb (0.1.1b1)
feedback (0.1.2rc1)
iot (0.1.1b2)
keyvault (0.1.1b4)
network (0.1.1b2)
nspkg (0.1.2)
profile (0.1.2rc1)
redis (0.1.1b2)
resource (0.1.2rc1)
role (0.1.2rc1)
sql (0.1.1b3)
storage (0.1.2rc1)
vm (0.1.2rc1)

Python (Windows) 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]

**Comment by yugangw-msft** [comment]
@derekbekoe, this is about the profile support

**Comment by derekbekoe** [comment]
@devkeydet The API version is available on Public Azure but not AzureUSGovernment yet. We're investigating with the service team.

**Comment by derekbekoe** [comment]
Related to https://github.com/Azure/azure-cli/issues/2199

**Comment by yugangw-msft** [comment]
@derekbekoe @johanste
Will it make sense in future till we have profile support/installers, for each release, we also upload the result of "pip freeze" to some public links for people to install if they want to go back to older version?

**Comment by benkoller** [comment]
This seems to fail for AzureGermanCloud, too:

```
$ az vm list-sizes -l germanycentral
The resource type 'locations/vmSizes' could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'. The supported api-versions are '2015-05-01-preview,2015-06-15,2016-03-30'.
```

I'm running on 0.1.2rc1 as well.

**Comment by yugangw-msft** [comment]
I confirmed with Compute team that sovereign clouds' manifests have not been updated with newer api-version that CLI is using. I will update the issue when the change occurs

**Comment by kfiresmith** [comment]
+1 for AzureUSGovernment environment support.

**Comment by yugangw-msft** [comment]
Hey, folks, the API version of `2016-04-30-preview` has been deployed to USGovernment. But the managed disk support is not yet rolled out, and that means when you create VM/VMSS, please use the flag of `--use-unmanaged-disk`

**Comment by shabiel** [comment]
Affect me too.

The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'.

**Comment by jimyjohny** [comment]
"az image create " fails with same message for the gov cloud. Is there any eta ?

**Comment by hankl** [comment]
"az image create " fails with the same message for China Azure Cloud. Is there any solution to workaround? When can be supported?

**Comment by yugangw-msft** [comment]
Update: 
`China Cloud` and `German Cloud` should work now. 
`US Government` is still being worked on. I will post updates when it is ready

**Comment by yugangw-msft** [comment]
The service deployment to USGov and China is done. Issues mentioned here should be fixed. Please verify
