### ISSUE TITLE
Azure Orbital CLI

### ISSUE THREAD

**Issue by thisisdevanshu** [Azure/azure-cli#21903]
**Resource Provider**
Azure Orbital

**Description of Feature or Work Requested**
Generate CLI from the stable API version

**Minimum API Version Required**
2022-03-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/orbital/resource-manager/Microsoft.Orbital/stable/2022-03-01

**Target Date**
June, 2022

**Comment by yonzhan** [comment]
PLR

**Comment by jsntcy** [comment]
@thisisdevanshu,

- When will the swagger be merged into [public swagger repo](https://github.com/Azure/azure-rest-api-specs/)?
- What's the release phase for the service? private preview? public preview? GA?

**Comment by thisisdevanshu** [comment]
@jsntcy 
The swagger is merged to the public swagger repo now.
The release phase of the service is GA,

**Comment by jsntcy** [comment]
@thisisdevanshu, Got it, thanks.

**Comment by jsntcy** [comment]
@thisisdevanshu,
We'd like to share a good news to you:
Recently we developed a new CLI code generator and we'd like to invite you (or someone from your team) as our first customer to try our new code generator to generate CLI code automatically.
We can set up a quick meeting with you to guide you to generate code step by step using the tool.
Really appreciated if you can try our new codegen tool and provide feedback for us to improve the tool.

**Comment by chasewilson** [comment]
Hey @thisisdevanshu, just wanted to pin on @jsntcy's earlier message as we are trying to improve the expereince for our partner teams to easily Generate CLI commands for their service. We'd greatly appreciate any and all feedback you have :)

**Comment by chasewilson** [comment]
Hey @thisisdevanshu, just wanted to pin on @jsntcy's earlier message as we are trying to improve the expereince for our partner teams to easily Generate CLI commands for their service. We'd greatly appreciate any and all feedback you have :)

**Comment by jsntcy** [comment]
Already released in https://github.com/Azure/azure-cli-extensions/tree/main/src/orbital
