### ISSUE TITLE
az deployment randomly crashes with: ERROR: 'bytes' object has no attribute 'get'

### ISSUE THREAD

**Issue by zaidmohd** [Azure/azure-cli#21905]
Run az deployment sub validate \
  az deployment sub validate \
  --location canadaeast \
  --template-file ./orchestrations/landing-zones/containers.primary.bicep \
  --parameters env=dev \
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    environmentAzure: dev
    modulePath: ./orchestrations/landing-zones
    AZURE_CREDENTIALS: ***
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
ERROR: 'bytes' object has no attribute 'get'

**Comment by zaidmohd** [comment]
I have not specified any version in the az command.runs:
  using: 'composite'
  steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    # [Validate execution] task(s) bash
    # ------------------------------
    - name: 'Validate [${{ inputs.templateFilePath }}]'
      shell: bash
      id: validate_step
      run: |
        az deployment sub validate \
        --location ${{ inputs.location }} \
        --template-file ${{ inputs.templateFilePath }} \
        --parameters env=${{ inputs.environmentAzure }} \

runs:
  using: 'composite'
  steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    # [Validate execution] task(s) bash
    # ------------------------------
    - name: 'Validate [${{ inputs.templateFilePath }}]'
      shell: bash
      id: validate_step
      run: |
        az deployment sub validate \
        --location ${{ inputs.location }} \
        --template-file ${{ inputs.templateFilePath }} \
        --parameters env=${{ inputs.environmentAzure }} \

**Comment by zaidmohd** [comment]
It is similar to the service side issue. 
#19743

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@zaidmohd Apologies for the late reply. Thanks for reporting the issue and sharing the feedback. Could you please let me know the AzCLI version you are using? Also please run the same above command with the parameter `--debug ` while running the same above command. Awaiting your reply.

**Comment by zhoxing-ms** [comment]
@zaidmohd The similar issue have been fixed in version `2.34.0` [PR link](https://github.com/Azure/azure-cli/pull/21220). Could you please check the CLI version you used is older than  `2.34.0`？

**Comment by zaidmohd** [comment]
yes, I updated the deployment task from Bash to Azure CLI task with specific version 2.34.1 and don't have this issue anymore.
