### ISSUE TITLE
AZ CLI defaulting to 4 MiB chunk size - failing to upload large blobs with 50K block limit - auto chunking not working

### ISSUE THREAD

**Issue by GaneshMSFT** [Azure/azure-cli#21914]
## Describe the bug

**Command Name**
Latest Az CLI default chunking seems to be broken. It's defaulting to 4 MiB block size even though blob I was trying to upload was around 220 GB. It's causing the upload to fail with the following error. 

`az storage blob upload`

**Errors:**
```
The block list may not contain more than 50,000 blocks.
RequestId:bdd2bf0d-701e-004e-094f-46344a000000
Time:2022-04-02T05:05:49.1346278Z
ErrorCode:BlockListTooLong

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload --account-name {} --container-name {} --file {} --name {} --auth-mode {} --verbose`

## Expected Behavior
If the size of the blob is bigger, CLI should take bigger chunks (100 MiB) automatically to complete upload successfully. 

## Environment Summary
```
Linux-4.19.0-20-cloud-amd64-x86_64-with-glibc2.28, Debian GNU/Linux 10 (buster)
Python 3.8.12
Installer: DEB

azure-cli 2.34.1
```

**Comment by yonzhan** [comment]
storage
