### ISSUE TITLE
q

### ISSUE THREAD

**Issue by lihaybs** [Azure/azure-cli#21921]
## Describe the bug

**Command Name**
``

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
macOS-12.3.1-x86_64-i386-64bit, Darwin 21.4.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.34.1
```

**Comment by yonzhan** [comment]
Please provide the detailed CLI commands
