### ISSUE TITLE
Error raised

### ISSUE THREAD

**Issue by navid-ahrary** [Azure/azure-cli#21926]
## Describe the bug

**Command Name**
`az webapp`

**Errors:**
```
cannot import name 'DefaultErrorResponseException'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 231, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 579, in execute
    parsed_args = self.parser.parse_args(args)
python3.6/site-packages/knack/parser.py, ln 260, in parse_args
    return super().parse_args(args)
usr/lib64/python3.6/argparse.py, ln 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
...
<frozen importlib._bootstrap_external>, ln 678, in exec_module
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
cli/command_modules/appservice/custom.py, ln 39, in <module>
    from azure.mgmt.web.models import KeyInfo, DefaultErrorResponseException
ImportError: cannot import name 'DefaultErrorResponseException'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp`

## Environment Summary
```
Linux-5.3.18-59.10-default-x86_64-with-glibc2.3.4
Python 3.6.13
Installer: PIP

azure-cli 2.14.2 *

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@navid-ahrary Thanks for reaching out to us and sharing this feedback. I wasn't able to reproduce this issue. You are using a pretty old version of AzCLI. Could you please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) of the AzCLI and then test again ? Awaiting your reply.

**Comment by navid-ahrary** [comment]
> @navid-ahrary Thanks for reaching out to us and sharing this feedback. I wasn't able to reproduce this issue. You are using a pretty old version of AzCLI. Could you please use the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) of the AzCLI and then test again ? Awaiting your reply.

You are right, I installed with pip latest version and issue resolved. Thanks

**Comment by navba-MSFT** [comment]
@navid-ahrary Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
