### ISSUE TITLE
Not able to allow the SP to access your Azure Machine Learning workspace: __init__() got an unexpected keyword argument 'async_persist'

### ISSUE THREAD

**Issue by luoanabecher** [Azure/azure-cli#21925]
**Describe the bug**
Running https://docs.microsoft.com/en-us/azure/machine-learning/how-to-setup-authentication#code-try-5 to create a SP for AML workspace. 

**To Reproduce**
az ad sp create-for-rbac --sdk-auth --name ml-auth --role Contributor --scopes /subscriptions/<subscription id>
az ad sp show --id your-client-id
az ml workspace share -w your-workspace-name -g your-resource-group-name --user your-sp-object-id --role owner

**Expected behavior**
The last call from above should allow the SP to access the ml workspace and 'This call does not produce any output on success.'
However, for me it says: __init__() got an unexpected keyword argument 'async_persist'

**Environment summary**
current cli version 3.4, downgraded to 2.29 to see if it works, said failure to authenticate and run az login though I was already authenticated

**Comment by navba-MSFT** [comment]
@luoanabecher Thanks for reaching out to us and sharing this feedback. Could you please upgrade your ml extension and check if that helps ?

>az extension update -n ml

Also if you have downgraded the AzCLI version, please upgrade it again to the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli). Then test again with your above command.

Similar issue: https://github.com/Azure/azure-cli/issues/20150  and  https://github.com/microsoft/MCW-ML-Ops/issues/59

Please let me know if you still see the same issue after following the above action plan. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@luoanabecher I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@luoanabecher We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
