### ISSUE TITLE
azcopy-based commands leak valid SAS in console

### ISSUE THREAD

**Issue by PurkkaKoodari** [Azure/azure-cli#21920]
**Describe the bug**
All azcopy-based commands, such as `az storage blob sync` or `az storage copy`, print the raw `azcopy` command in console. This includes a valid read/write SAS for the destination container. This was previously mentioned in #16519, `azcopy` still doesn't use `az login` credentials after a year.

There's no official way to use `azcopy` directly in GitHub Actions and this leak makes it impossible to use `azcopy`-based commands securely either with `azure/CLI`. Therefore, instead of `blob sync`, we're having to use the inferior `blob delete-batch` followed by `blob upload-batch`.

Relevant line:

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/azcopy/util.py#L77

**To Reproduce**
1. Run e.g. `az storage copy --account-name someacct --destination-container somecontainer --source somefolder`
2. Console shows `Azcopy command: ['/home/user/bin/azcopy', 'copy', 'somefolder', 'https://someacct.blob.core.windows.net/somecontainer/?se=2022-04-04T08%3A49%3A18Z&sp=wac&sv=2018-03-28&ss=b&srt=co&sig=redacted']`

**Expected behavior**
Credentials aren't unconditionally printed to console in commands one might want to use in CI/CD.

**Environment summary**
Latest version from <https://packages.microsoft.com/repos/azure-cli/> for Debian Bullseye.

```
az version
{
  "azure-cli": "2.34.1",
  "azure-cli-core": "2.34.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.23.0"
  }
}
```

**Comment by yonzhan** [comment]
storage
