### ISSUE TITLE
"az monitor log-analytics workspace show" returns case-insensitive id property

### ISSUE THREAD

**Issue by huf1** [Azure/azure-cli#21936]
**Describe the bug**
The "az monitor log-analytics workspace show" command returns the id property case-insensitive

**To Reproduce**
run this command to reproduce:
az monitor log-analytics workspace show -n <your_workspace_name> -g <your_resource_group_name>

**Expected behavior**
The id property should show the "static" parts of the string case-sensitive (e.g. ../resource**G**roup/.. or ../**M**icrosoft.**O**perational**I**nsights/..

For example (for comparison) the "az storage account show" command correctly outputs the id property case-senstive

**Environment summary**
azure-cli version 2.34.1
Any OS

**Additional context**
![image](https://user-images.githubusercontent.com/2862811/161763631-634dcafd-3171-4e6e-a375-95ad21ff53bb.png)

**Comment by yonzhan** [comment]
monitor

**Comment by YuanyuanNi** [comment]
![image](https://user-images.githubusercontent.com/95396631/161919738-c1932def-a933-4f8a-86da-b6ceba69d992.png)
Hi, 
@huf1 "az monitor log-analytics workspace show " works well from my side as picture attached, if you still has this issue, pls provide more pre conditions so that we can reproduce.
 Best wishes.

**Comment by huf1** [comment]
> ![image](https://user-images.githubusercontent.com/95396631/161919738-c1932def-a933-4f8a-86da-b6ceba69d992.png) Hi, @huf1 "az monitor log-analytics workspace show " works well from my side as picture attached, if you still has this issue, pls provide more pre conditions so that we can reproduce. Best wishes.

ok, thats strange..
First i created a whole new log-analytics workspace via portal and queried it with powershell (like in your picture). But the result was the same:
![image](https://user-images.githubusercontent.com/2862811/162038724-7e094ca6-3ace-4fe7-aa01-aa8f123f6e63.png)

In the portal i get the same case-insensitive resource id:
![image](https://user-images.githubusercontent.com/2862811/162039143-9d89c26b-29ae-4259-8363-d65164ac0878.png)

Any other resource shows the id correct in case-sensitive format:
![image](https://user-images.githubusercontent.com/2862811/162040006-2af976a9-2fca-4da4-a14d-990ef6b6a1f0.png)
And with cli:
![image](https://user-images.githubusercontent.com/2862811/162040769-31ecb508-6415-498d-b957-7902681f8a15.png)

My last try was to create a new log-analytics workspace in the location "westus" (as in your example, i previously created mine in location "westeurope"). And surprisingly the id was correct case-sensitive:
![image](https://user-images.githubusercontent.com/2862811/162043408-ba03ed8c-38e0-468b-9d6c-c62c12b4f7a2.png)


@YuanyuanNi can you please check/reproduce this on your site, that this issue is location dependant?

Best wishes and thank you ;)

**Comment by yonzhan** [comment]
monitor service team could take a look

**Comment by huf1** [comment]
> monitor service team could take a look

could or will take a look?
