### ISSUE TITLE
GA of "az account alias"

### ISSUE THREAD

**Issue by joergjo** [Azure/azure-cli#21937]
Hi,

is there are timeline when the command group `az account alias` will become GA? 

It's currently marked experimental, but it is required when programmatically creating subscriptions (https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=azure-cli) using the latest APIs.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by joergjo** [comment]
That is fine - the old APIs are still around and have not been obsoleted yet.

**Comment by zhoxing-ms** [comment]
At present, the `az account alias` command group has GA, and the api-version used is `2021-10-01`, does this meet your expectations?

**Comment by t-esslinger** [comment]
> @joergjo At present, the `az account alias` command group has GA, and the api-version used is `2021-10-01`, does this meet your expectations?

@zhoxing-ms Since Joerg also asked on my behalf, many thanks from my side for the quick implementation. I thought the required changes might be bigger, but this is exactly meets our expectations
