### ISSUE TITLE
az aks nodepool update not updating node-taints

### ISSUE THREAD

**Issue by abhiramani-iptiq** [Azure/azure-cli#21945]
[Enter feedback here]
this command throws error "unrecognized arguments: --node-taints sku=smarts:NoSchedule"
az aks nodepool update --cluster-name $aks --name $poolname --resource-group $rg --node-taints sku=smarts:NoSchedule

documentations shows that --node-taints is valid option for az aks nodepool update command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fce7ab-ab56-44c6-b9a8-405444247a0b
* Version Independent ID: dabbb6c6-c616-a6ec-61f6-1b9d3bb069e8
* Content: [az aks nodepool](https://docs.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/aks/nodepool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks/nodepool.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@abhiramani-iptiq Thanks for reaching out to us and sharing this feedback. I wasn't able to reproduce this issue.
I tried to run the command and that worked just fine. See below:

>az aks nodepool update --cluster-name MyCluster --name MyNodePool --resource-group MyRG --node-taints sku=smarts:NoSchedule

<<TRIMMING FOR SPACE>>>
"mode": "User",
  "name": "*********",
  "nodeImageVersion": "AKSUbuntu-1804gen2containerd-2022.03.23",
  "nodeLabels": null,
  "nodePublicIpPrefixId": null,
  "nodeTaints": [
    **"sku=smarts:NoSchedule"**
  ],
  "orchestratorVersion": "1.21.9",
  "osDiskSizeGb": 128,
  "osDiskType": "Managed",

Sending you the screenshot from the AKS cluster portal, Node Pool Overview blade: 

![image](https://user-images.githubusercontent.com/57353862/161933858-8cb16f87-f041-453a-9b3f-19843d9b545a.png)

Could you please use the [most recent version of the AzCLI ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)and check if that helps ? Awaiting your reply.

**Comment by abhiramani-iptiq** [comment]
Hi I am using Azure cloudshell so i don't have choice of updating it. can you advise if this is compatible with azure cloudshell?

**Comment by navba-MSFT** [comment]
@abhiramani-iptiq Yes the same command should work on Azure Cloud shell too. I just ran the same above command on Azure Portal cloud shell and that worked fine. 

>XXXXX@Azure:~$ az aks nodepool update --cluster-name MyCluster --name MyNodePool --resource-group MyRG --node-taints sku=smarts:NoSchedule
>
>{
  "availabilityZones": null,
  "count": 1,
  "creationData": null,
  "enableAutoScaling": false,
  "enableEncryptionAtHost": null,
  "enableFips": false,
  "enableNodePublicIp": false,
  "enableUltraSsd": null,
  "gpuInstanceProfile": null,
  "id": "/subscriptions/XXXXXXX/resourcegroups/XXXX/providers/Microsoft.ContainerService/managedClusters/XXXXX/agentPools/XXX",
  "kubeletConfig": null,
  "kubeletDiskType": "OS",
  "linuxOsConfig": null,
  "maxCount": null,
  "maxPods": 110,
  "minCount": null,
  "mode": "User",
  "name": "*******",
  "nodeImageVersion": "AKSUbuntu-1804gen2containerd-2022.03.23",
  "nodeLabels": null,
  "nodePublicIpPrefixId": null,
  "nodeTaints": [
    "**sku=smarts:NoSchedule**"
  ],
  "orchestratorVersion": "1.21.9",
  "osDiskSizeGb": 128,
  "osDiskType": "Managed",
  "osSku": "Ubuntu",
  "osType": "Linux",
  "podSubnetId": null,
  "powerState": {
    "code": "Running"
  },
  "provisioningState": "Succeeded",
  "proximityPlacementGroupId": null,
  "resourceGroup": "XXXX",
  "scaleDownMode": "Delete",
  "scaleSetEvictionPolicy": null,
  "scaleSetPriority": null,
  "spotMaxPrice": null,
  "tags": null,
  "type": "Microsoft.ContainerService/managedClusters/agentPools",
  "typePropertiesType": "VirtualMachineScaleSets",
  "upgradeSettings": {
    "maxSurge": null
  },
  "vmSize": "Standard_B2s",
  "vnetSubnetId": null,
  "workloadRuntime": null
}

I ran the `az version` command in the Azure Cloud Shell and I see that it was using 2.34.1. If you are still facing the same issue, could you please run the same above command with `--debug` switch and share the output here ? PS: Remove sensitive information from the output.

**Comment by abhiramani-iptiq** [comment]
this is my az version

abhijit@Azure:~$ az version 
{
  "azure-cli": "2.35.0",
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ai-examples": "0.2.5",
    "aks-preview": "0.5.22",
    "application-insights": "0.1.14",
    "azure-devops": "0.12.0",
    "dev-spaces-preview": "0.1.6",
    "log-analytics-solution": "0.1.1",
    "ssh": "1.0.1"
  }
}

**Comment by abhiramani-iptiq** [comment]
here is output with my debug command

abhijit@Azure:~$ az aks nodepool update --cluster-name $aks --name $poolname --resource-group $rg --node-taints sku=smarts:NoSchedule --debug
cli.knack.cli: Command arguments: ['aks', 'nodepool', 'update', '--cluster-name', 'IPTIQA-MICROSVC-SIT-EUS2-AKS-1', '--name', 'agentpool2', '--resource-group', 'iptiq-microsvc-sit-eus2-rg', '--node-taints', 'sku=smarts:NoSchedule', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f96ba8451f0>, <function OutputProducer.on_global_arguments at 0x7f96ba77d0d0>, <function CLIQuery.on_global_arguments at 0x7f96ba70f5e0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'aks': ['azext_aks_preview', 'azure.cli.command_modules.acs']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acs                       0.104        10        64
cli.azure.cli.core: Total (1)                 0.104        10        64
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.knack.cli: Event: CommandLoader.OnLoadCommandTable []
cli.azure.cli.core: aks-preview               0.004         7        41  /home/abhijit/.azure/cliextensions/aks-preview
cli.azure.cli.core: ai-examples               0.077         1         1  /opt/az/lib/python3.8/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (2)                 0.081         8        42  
cli.azure.cli.core: Loaded 15 groups, 81 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : aks nodepool update
cli.azure.cli.core: Command table: aks nodepool update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f96b9eeb550>]
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f96b9e6f940>]
cli.knack.cli: Event: CommandLoader.OnLoadArguments []
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f96b9da9ca0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f96b9da9dc0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.azure.cli.core.command_recommender: "--node-taints" is an invalid parameter for command "aks nodepool update".
urllib3.connectionpool: Starting new HTTPS connection (1): app.aladdin.microsoft.com:443
urllib3.connectionpool: https://app.aladdin.microsoft.com:443 "GET /api/v1.0/suggestions?query=%7B%22command%22%3A+%22aks+nodepool+update%22%2C+%22parameters%22%3A+%22%22%7D&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.35.0%22%2C+%22errorType%22%3A+%22UnrecognizedArguments%22%7D HTTP/1.1" 200 None
cli.azure.cli.core.command_recommender: "--node-taints" is an invalid parameter for command "aks nodepool update".
cli.azure.cli.core.azclierror: unrecognized arguments: --node-taints sku=smarts:NoSchedule
az_command_data_logger: unrecognized arguments: --node-taints sku=smarts:NoSchedule

Examples from AI knowledge base:
az aks nodepool update --enable-cluster-autoscaler --min-count 1 --max-count 5 --resource-group MyResourceGroup --name nodepool1 --cluster-name MyManagedCluster
Enable cluster-autoscaler within node count range [1,5]

az aks nodepool update --update-cluster-autoscaler --min-count 1 --max-count 10 --resource-group MyResourceGroup --name nodepool1 --cluster-name MyManagedCluster
Update min-count or max-count for cluster autoscaler.

https://docs.microsoft.com/en-US/cli/azure/aks/nodepool#az_aks_nodepool_update
Read more about the command in reference docs
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f96b9eeb790>]
cli.__main__: Command ran in 0.542 seconds (init: 0.153, invoke: 0.389)

**Comment by navba-MSFT** [comment]
@abhiramani-iptiq Thanks for your reply. I am able to run the same command successfully even using the most recent version (2.35.0) of the AzCLI from my machine and from the Azure Cloud shell. 

>AKS cluster version used: 1.21.9
>C:\>az version
{
  "azure-cli": "2.35.0",
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.60"
  }
}

**Action Plan**
Please follow the below action plan in order:

>az login
az aks get-credentials -n AKSCluster -g AKSRG
Kubectl get nodes   # Get the name of the node nd then run the below command
kubectl taint nodes NodeName sku=smarts:NoSchedule

Hope this helps. Awaiting your reply.

**Comment by abhiramani-iptiq** [comment]
Hi i need to taint whole nodepool and not individual nodes. otherwise when cluster autoscales how will new nodes get those taints?

**Comment by navba-MSFT** [comment]
@abhiramani-iptiq Thanks for getting back. Since I am unable to reproduce this issue with the AzCLI, I am adding the Service Team to assist further on this.

@Azure/aks-pm Could you please look into this and help us to provide us the pointers to resolve this issue ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
While we are waiting for the reply from @Azure/aks-pm, @abhiramani-iptiq Could you please confirm if you are still facing the same issue ? Awaiting your reply.

**Comment by abhiramani-iptiq** [comment]
this issue is not happening anymore
