### ISSUE TITLE
az acr import can leave an image tag in ACR in an inconsistent state

### ISSUE THREAD

**Issue by nwohlgemuth** [Azure/azure-cli#21944]
**Describe the bug**
When az acr import is called for an image by tag (and the image pointed to for import actually exists), the result of the operation can be that the tag now no longer points to a valid image manifest, whereas it did before.

**To Reproduce**
To reproduce this bug:
Have a process that is frequently generating new docker images in one ACR, all with the same repository and tag.
Have another process (invoked in parallel with the first) that is running az acr import that transfers the docker image from the first ACR to a second ACR.
After each az acr import command finishes, try to pull the image (by tag) from the second ACR. Sometimes, you will observe that the pull will fail saying that the manifest for the tag is invalid.

**Expected behavior**
az acr import should always leave things in a consistent state. If az acr import is invoked for a tag that gets modified (meaning, the image that the tag points to changes), it should either use the old one or the new one, but it must be consistent. It seems that the bug is that the tag ends up pointing to the new version of the image but only the old version of the image gets copied. So, when you go to pull by that tag, it tries to pull the new version of the image but since it wasn't actually copied (only the old version was), you get an error.

**Environment summary**
```
Linux-4.15.0-153-generic-x86_64-with-Ubuntu-18.04-bionic, Ubuntu 18.04.6 LTS
Python 3.6.9
Installer: PIP

azure-cli 2.34.1

Dependencies:
msal 1.16.0
```

**Additional context**
This bug is actually very dangerous when it manifests in an ACR that is used by a kubernetes cluster. The image(s) that get affected become "broken" in that they cannot be pulled anymore. This means that over time, the number of running pods can drop lower and lower as there is no way for the kubernetes cluster to add more pods (since it can't pull the image(s) that is needs from ACR). When this bug happens, you must notice it and rerun az acr import until the image(s) get back into a consistent state, otherwise you can see availability drops of the services in your kubernetes cluster that depend on the image(s).
For anyone else being affected by this bug, one option to avoid this altogether is to not use tags as hashes fundamentally cannot suffer from this type of problem.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@nwohlgemuth Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. Could you please share the complete error message you received during pull failure along with the output of `--debug ` parameter ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@nwohlgemuth I wanted to do quick follow-up to check if you had a chance to look at my above comment.  Could you please share the complete error message you received during pull failure along with the output of --debug parameter? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@nwohlgemuth Please provide details on this issue once you get a chance.

**Comment by navba-MSFT** [comment]
@nwohlgemuth We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please provide us more details on the error message and the --debug output and reopen this thread. We would be happy to help.
