### ISSUE TITLE
Add support for storage account creation with --access-tier Archive

### ISSUE THREAD

**Issue by dvasdekis** [Azure/azure-cli#21946]
**Is your feature request related to a problem? Please describe.**
I am unable to create archive storage accounts using the AZ CLI.

For example:
`az storage account create -n archivetest -g mysandbox --access-tier Archive`
Returns result:
`az storage account create: 'Archive' is not a valid value for '--access-tier'. Allowed values: Hot, Cool.`

Archive storage is described [here](https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview).

**Describe the solution you'd like**
Allow the creation of archive storage.

**Describe alternatives you've considered**
There are no alternatives as we need to procedurally create some archive storage accounts. Terraform support for Archive storage is waiting on support within the Azure CLI.

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Hi @dvasdekis, Archive tier is not for storage account, actually it's for blob. Here's some doc FYI:
- [Archive access tier](https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview#archive-access-tier)
- [Archive a blob](https://docs.microsoft.com/en-us/azure/storage/blobs/archive-blob?tabs=azure-cli)
