### ISSUE TITLE
cosmos db with cmk and continuous backup

### ISSUE THREAD

**Issue by matluri-fi** [Azure/azure-cli#21963]

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@matluri-fi Could you please let me know if you had a chance to look at my above comment ? Please share the detailed ask so that we can assist you better. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@matluri-fi This is a quick follow-up to check if you can provide more details on the ask. Looking at the issue title, I believe you are trying to use CMD with continuous backup for cosmosdb. You can do it using [Azure CLI](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-cmk#to-create-a-continuous-backup-account-by-using-the-azure-cli) or an [Azure Resource Manager template](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-cmk#to-create-a-continuous-backup-account-by-using-an-azure-resource-manager-template). Note that currently, only user-assigned managed identity is supported for creating continuous backup accounts. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@matluri-fi I hope you had a chance to look at the above comment and follow the suggestion. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please provide more details on the issue and feel free to reopen this thread. We would be happy to help.
