### ISSUE TITLE
Usage error: To create role assignments, specify both --role and --scopes.

### ISSUE THREAD

**Issue by SSPJ** [Azure/azure-cli#21960]
## Describe the bug

Previously working `az ad sp create-for-rbac` command has stopped working.

**Command Name**
`az ad sp create-for-rbac`

**Errors:**
```
Usage error: To create role assignments, specify both --role and --scopes.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az ad sp create-for-rbac --name {} --scopes {} --sdk-auth`

## Expected Behavior

Service principal is created.

## Environment Summary
```
Linux-5.4.0-1074-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.12
Installer: DEB

azure-cli 2.35.0

Extensions:
ai-examples 0.2.5
ssh 1.0.1

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by SaurabhSharma-MSFT** [comment]
@SSPJ We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by ConcreteGannet** [comment]
This is by design, see #21323 . Just specify your scope. The documentation at https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-create-for-rbac says what to to to get your subscription ID if that's the scope you want.

**Comment by SSPJ** [comment]
Appreciate the replies.

In case anyone else finds this helpful, it seems you can still do `az ad sp create-for-rbac --name <name>` (just leave `--scope` and `--role` entirely off).

**Comment by jiasli** [comment]
> In case anyone else finds this helpful, it seems you can still do `az ad sp create-for-rbac --name <name>` (just leave `--scope` and `--role` entirely off).
>
> To be clear, that won't create a role assignment, but it suited my use case perfectly.

Exactly! This has been the designed behavior since

- https://github.com/Azure/azure-cli/pull/19805
