### ISSUE TITLE
Latest az cli fails to run download-batch command

### ISSUE THREAD

**Issue by taoisu** [Azure/azure-cli#21966]
%23%23%23 **This is autogenerated. Please review and update as needed.**

%23%23 Describe the bug

**Command Name**
`az storage blob download-batch`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'BlobServiceClient' object has no attribute 'exists'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/storage/__init__.py", line 385, in new_handler
    first(ex)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/storage/__init__.py", line 385, in new_handler
    first(ex)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/storage/_exception_handler.py", line 17, in file_related_exception_handler
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 363, in storage_blob_download_batch
    source_blobs = collect_blobs(client, source_container_name, pattern)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/storage/util.py", line 16, in collect_blobs
    return [name for (name, _) in collect_blob_objects(blob_service, container, pattern)]
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/storage/util.py", line 16, in <listcomp>
    return [name for (name, _) in collect_blob_objects(blob_service, container, pattern)]
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/storage/util.py", line 31, in collect_blob_objects
    if blob_service.exists(container, pattern):
AttributeError: 'BlobServiceClient' object has no attribute 'exists'

```

%23%23 To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob download-batch -d {} -s {} --auth-mode {} --account-name {} --subscription {} --pattern {}`

%23%23 Expected Behavior

%23%23 Environment Summary
```
Linux-5.4.0-1063-azure-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.8.12
Installer: DEB

azure-cli 2.35.0

Extensions:
azure-cli-ml 1.37.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```
%23%23 Additional Context

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Can you share which pattern you are using?

**Comment by taoisu** [comment]
Something as simple as "model.onnx".

It doesn't matter as far as I can tell, any pattern would fail. This just started to happen today, I was using azure cli in a docker image, I built the image yesterday it was working just fine, today I re-built the docker image the error started to show up.

**Comment by evelyn-ys** [comment]
Actually `--pattern` only supports few cases. You can check the help message with [CLI doc](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-download-batch-optional-parameters) or `az storage blob download-batch -h`:

> `--pattern`
The pattern used for globbing files or blobs in the source. The supported patterns are '*', '?', '[seq]', and '[!seq]'. For more information, please refer to https://docs.python.org/3.7/library/fnmatch.html.

**Comment by evelyn-ys** [comment]
If you are giving a blob name as `--pattern`, I'll suggest you to use `az storage blob download`.
It used to work with previous CLI using `az storage blob download-batch` but we have an bug dealing with full blob name in latest CLI. This will be fixed in next release. But this usage is not documented in our help message or doc, so it's not recommended.

**Comment by taoisu** [comment]
@evelyn-ys thanks for the investigation, but I'm afraid that is not the case for me. We've been using the same command for two years in one of our pipeline, and it was just broken today, so it is clear something is wrong in the az cli.

**Comment by taoisu** [comment]
```
az storage blob download-batch -d {} -s jobs --auth-mode key --account-name {} --subscription {} --pattern output/invoice/20220402/layoutlm-TT_MH5MSL1024_Tier1_FT2/layoutlm@2022-04-02_22-37-11/model_artifacts/model.onnx
```
This is the full command we're using.

**Comment by taoisu** [comment]
`az storage blob download` is not an option for us because we need `--pattern` specifically, one of the patterns is something like "*.bias"

**Comment by taoisu** [comment]
I'm not sure if you just need to fix the latest CLI, because I've also tried installing previous versions (which works in the past), and I'm seeing the exactly the same issue.

**Comment by evelyn-ys** [comment]
When installing previous versions, please make sure all the dependencies of latest version are uninstalled. I'm afraid there's some storage dependency left.

> I'm not sure if you just need to fix the latest CLI, because I've also tried installing previous versions (which works in the past), and I'm seeing the exactly the same issue.

**Comment by evelyn-ys** [comment]
> ```
> az storage blob download-batch -d {} -s jobs --auth-mode key --account-name {} --subscription {} --pattern output/invoice/20220402/layoutlm-TT_MH5MSL1024_Tier1_FT2/layoutlm@2022-04-02_22-37-11/model_artifacts/model.onnx
> ```
> 
> This is the full command we're using.

For patterns not following the four cases(`*`, `?`, `[seq]`, `[!seq]`), we used to take it as a full blob name. And the latest CLI does have a bug here.

**Comment by venkymns** [comment]
I am facing same issue.  what is the solution for this issue ?  going back to previous version?

https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-download-batch

as per the documentation below command is valid .

az storage blob download-batch --destination target --source {} --pattern folder/filename.jar --account-name {}

**Comment by evelyn-ys** [comment]
@venkymns for specific blob file, you can use `az storage blob download` as workaround

**Comment by taoisu** [comment]
> When installing previous versions, please make sure all the dependencies of latest version are uninstalled. I'm afraid there's some storage dependency left.
> 
> > I'm not sure if you just need to fix the latest CLI, because I've also tried installing previous versions (which works in the past), and I'm seeing the exactly the same issue.

What is interesting is that even if I install azure-cli=2.29.2-1~bionic freshly inside the docker image this exact same error would occur, any ideas why?

**Comment by taoisu** [comment]
> > ```
> > az storage blob download-batch -d {} -s jobs --auth-mode key --account-name {} --subscription {} --pattern output/invoice/20220402/layoutlm-TT_MH5MSL1024_Tier1_FT2/layoutlm@2022-04-02_22-37-11/model_artifacts/model.onnx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is the full command we're using.
> 
> For patterns not following the four cases(`*`, `?`, `[seq]`, `[!seq]`), we used to take it as a full blob name. And the latest CLI does have a bug here.

I can understand that if the pattern is not working I might end up downloading the wrong files, but the callstack tells me that seems the API has been deleted or some wrong version of dependencies are installed. Are you sure this is related to the bug you are talking about?

**Comment by evelyn-ys** [comment]
> I can understand that if the pattern is not working I might end up downloading the wrong files, but the callstack tells me that seems the API has been deleted or some wrong version of dependencies are installed. Are you sure this is related to the bug you are talking about?

We upgraded the dependency Python SDK and the APIs have changed a lot. For patterns not following `*`, `?`, `[seq]`, [!seq], the API is unchanged so making the command fail

**Comment by taoisu** [comment]
I use something like “model.onnx”, but it doesn’t matter as far as I know, any pattern fails for me. And it just happens today after I rebuilt the docker image which reinstalls the azure cli with latest version.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
