### ISSUE TITLE
Support for 'undelete' of storage containers

### ISSUE THREAD

**Issue by dvasdekis** [Azure/azure-cli#21967]
**Is your feature request related to a problem? Please describe.**
We are unable to 'undelete' storage containers using the Azure CLI. Expecting an option like `az storage container undelete` on the page with all the other [container commands](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest).

We can do this via the Azure browser UI - see here: https://raw.githubusercontent.com/dvasdekis/images/master/azure_container_undelete.png

**Describe the solution you'd like**
New command: `az storage container undelete`

**Describe alternatives you've considered**
Doing it via the UI - but we don't do things this way! Everything is programmatic here.

**Additional context**
Will be creating an issue in the Terraform provider to support this once it's enabled here.

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
You can install cli extension `storage-blob-preview` by
```
az extension add -n storage-blob-preview
```
and then try
```
az storage container restore
```

**Comment by dvasdekis** [comment]
> az storage container restore

This works great, thank you, sorry I didn't see it!
