### ISSUE TITLE
[Fea Req] "az storage message put" transforms the base64 string to actual message automatically

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-cli#21970]
**Is your feature request related to a problem? Please describe.**
az storage message put --content aGVsbG93b3JsZAo= -q queue1 --connection-string "connectionstring"

The command will transform the base64 string aGVsbG93b3JsZAo= to "helloworld" automatically.

**Describe the solution you'd like**
Can we add a parameter to switch behavior?

In azure portal, there is option "Encode the message body in base64".

The Powershell command does not transform the base64 string to actual message.

$ctx = New-AzStorageContext -StorageAccountName "saName" -StorageAccountKey 'HIDDEN'

# Retrieve a specific queue
$queue = Get-AzStorageQueue -Name queue1 -Context $ctx
# Show the properties of the queue
$queue

$queueMessage = [Microsoft.Azure.Storage.Queue.CloudQueueMessage]::new("aGVsbG93b3JsZAo=")

# Add a new message to the queue
$queue.CloudQueue.AddMessageAsync($queueMessage)

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Hi @yangchengs, this seems powershell cmdlets. Maybe you can create a new issue in https://github.com/Azure/azure-powershell repo and close this one?
