### ISSUE TITLE
postgress command erroneously stating "servername X already exists."

### ISSUE THREAD

**Issue by seajhawk** [Azure/azure-cli#21999]
## Describe the bug
If I run postgres server create and pass a servername with underscores ("_") in it, I get an error telling me that the server already exists. However, the actual problem is that underscores are not allowed in the name.

**Command Name**
`az postgres server create`

**Errors:**
```
The server name 'charris_superset_xxx' already exists.Please re-run command with some other server name.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- use a name that contains underscores in the command below:
- `az postgres server create --resource-group {} --name {} --location {} --admin-user {} --sku-name {}`

## Expected Behavior
I expect to get an error telling me that "Server name must only contain lowercase letters, numbers, and hyphens." (this is what I see in the Azure Databases extension for VS Code.

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0

Extensions:
azure-dev 0.0.1b456
containerapp 0.1.3
rdbms-connect 1.0.1

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team
