### ISSUE TITLE
Updating Azure Function App Connection Strings Unexpected

### ISSUE THREAD

**Issue by choukimasri** [Azure/azure-cli#21996]
Hey, I'm having trouble updating azure function app connection strings as per documentation, I'm running this ps script on deployment:
```ps
$settings= "@$(System.DefaultWorkingDirectory)/_drop/AZF01/functions/AppParameters.json" 
az webapp config appsettings set  --name app --resource-group rg -settings $settings

az webapp config connection-string set -t Custom  --name app --resource-group rg --settings "@$(System.DefaultWorkingDirectory)/_drop/AZF01/functions/AppConnectionStrings.json"

```

The appsettings set call works as intended, 
the connection-string call generated a single entry with the entire file inside.
as a workaround, I took the json file and wrapped it in a for each loop,
passing it as single separate objects, like this: 
```ps
foreach ($con in $connections) {
    az webapp config connection-string set -t $($con.type)  --name app --resource-group rg --settings "$($con.name)=$($con.value)"
}
```
however my keyvault references were missing the ')' and were not recognized as keyvault references despite the correct json file on input. which might be a second bug.

I don't see how the cli assumes the type of multiple connection-strings inside the file, and I don't understand the creation of multi type connection strings, as all of them are string variables inside, this just complicates the usage of this feature.

As in for the user experience, the entire app config experience must be redesigned as it's tedious and frustrating.

**Comment by SaurabhSharma-MSFT** [comment]
@choukimasri We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by choukimasri** [comment]
I found a workaround by writing this instead:
```ps 

$connections = Get-Content "$(System.DefaultWorkingDirectory)/_drop/AZF01/functions/AppConnectionStrings.json" | ConvertFrom-Json

az webapp config appsettings set --name "af01" --resource-group "rg" --settings "@$(System.DefaultWorkingDirectory)/_drop/AZF01/functions/AppParameters.json"

foreach ($con in $connections) {
     $line = "$($con.name)=$($con.value)" -replace '\s',''
     $setting = "`"$line`"" -replace '\s',''
     Write-Host "Inserting $setting"
     az webapp config connection-string set -t ($con.type)  --name "af01" --resource-group "rg" --settings $setting
}
```

**Comment by RakeshMohanMSFT** [comment]
@choukimasri Thank you for the confirmation, glad you could fix the issue. We will pass on this feedback. Closing this thread for now.
