### ISSUE TITLE
Changes related to dedicated host group for Ultra SSD support 

### ISSUE THREAD

**Issue by hari-bodicherla** [Azure/azure-cli#21997]
**Is your feature request related to a problem? Please describe.**
we currently don't support VM deployments against the dedicated hosts using ultra SSD capabilities.  The ultra SSD capabilities along with host level isolation using dedicated hosts enable our customers to conquer their most IO intensive and extremely scalable workloads along with achieving compliance. Currently, the ultra SSD support for dedicated hosts is enabled only for zonal dedicated host group resources.

**Describe the solution you'd like**
This change exposes new param customers can use to enable/disable the ultra SSD support for dedicated host group resources so that customers can deploy their ultra SSD enabled VM/VMSS resource on this dedicated host to allocate resources on the ultra SSD support enabled clusters. 

**Describe alternatives you've considered**
 N/A

**Additional context**
The cli command where we need to add this property "UltraSSDEnabled" is in 
{ [ az vm host group create ] (https://docs.microsoft.com/en-us/cli/azure/vm/host/group?view=azure-cli-latest#az-vm-host-group-create)}

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@hari-bodicherla Could you please provide the link of Swagger changes and the specific design of CLI commands and parameters in the issue description?

**Comment by zhoxing-ms** [comment]
@hari-bodicherla Could you provide the specific commands and parameter names that we need to support for this feature?

**Comment by hari-bodicherla** [comment]
> @hari-bodicherla Could you provide the specific commands and parameter names that we need to support for this feature?

As mentioned in the PR description, we need to add a property like "UltraSSDEnabled" or "EnableUltraSSD" in the below cmdlet

{ [ az vm host group create ] ([https://docs.microsoft.com/en-us/cli/azure/vm/host/group?view=azure-cli-latest#az-vm-host-group-create)}](https://docs.microsoft.com/en-us/cli/azure/vm/host/group?view=azure-cli-latest#az-vm-host-group-create)%7D)

**Comment by vamckMS** [comment]
@zhoxing-ms, do you know if this change will make it to the May CLI release? I believe that is the latest release you have, am I right?

**Comment by zhoxing-ms** [comment]
> do you know if this change will make it to the May CLI release? I believe that is the latest release you have, am I right?

Yes, we plan to release it in this sprint (**05-24**)
