### ISSUE TITLE
"az monitor metrics alert show" command is not able to show alerts rule targeted on Log Analytics Workspace 

### ISSUE THREAD

**Issue by hugo-zhang-uipath** [Azure/azure-cli#22006]
I have an alert rule set on a Log Analytics Workspace (LAW) to monitor the logs in the LAW. However, when I try to modify it in Azure cli, I am not able to find it using 
`az monitor metrics alert show --ids`
and `az monitor metrics alert show --name xxx --resourcegroup xxxx`

error
`(ResourceNotFound) The Resource 'Microsoft.Insights/metricalerts/xxxxxxxxxxxxxxxx' under resource group 'xxxxxxxxxx' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix`

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
Hi @YuanyuanNi, could you help with this usage issue?

**Comment by YuanyuanNi** [comment]
Hi:
     @hugo-zhang-uipath Notice that the id of LAW alert rule is "/subscriptions/xxxx/resourceGroups/nyy/providers/microsoft.insights/activityLogAlerts/xxxx" is different with the alert created with "az monitor metrics alert create" command,which is 'Microsoft.Insights/metricalerts/xxxxxxxxxxxxxxxx', so CLI shows the resource not found when using "az monitor metrics alert show" command.
Best wishes.
