### ISSUE TITLE
az acr create : Fails if name contains upper-case letters.

### ISSUE THREAD

**Issue by adrianFHNW** [Azure/azure-cli#22003]
**az acr create** doesn't accept names with upper-case letters.  Even the examples given fail.  Upper-case letters work when using the Portal.

The apparent bug is that the "az acr create" command does a name validation taken from "az acr connected-registry create" and hence fails.

Output from terminal:
adrian ~ > **az acr create --name AdriansRegistryName --resource-group RG-common --sku Standard**
ERROR: argument error: Connected registry name must use only lowercase.
adrian ~ > **az acr check-name --name AdriansRegistryName --output table**
NameAvailable: True

Either the documentation (and worked examples) should be changed to all lower-case or the command should be fixed to allow upper-case names.
***

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/acr.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/acr.yml)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by northtyphoon** [comment]
@adrianFHNW, sorry for the confusion. Mixed case or upper case can work, however they don't work well with other tools in the broader docker eco-system if your are not careful. To avoid future problems, we start to encourage the customers to use lowercase to create new registries.

@rosanch can you please take a look? It looks we need to update the error message and the samples to be consistent.

**Comment by adrianFHNW** [comment]
Thanks for the fast response.  I'll use lower-case names from now on.

WithoutBeingAbleToUseUpperCase or-maybe-using-hyphens_or_underscores itcanbehardtoworkouttheindividualwords :)
This is definitely a "me" problem, as most people won't really mind what the resource names are.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@adrianFHNW Thanks for sharing the feedback and reporting this issue. I will look into this and update the docs accordingly.

**Comment by navba-MSFT** [comment]
@adrianFHNW The above PR has been approved and merged. The `--name `parameter description has been fixed to explicitly indicate the use of lowercase. This will be addressed in the next release. We will now proceed with closure of this issue. If you need any assistance in future, please feel free to reopen this github issue.

**Comment by CaduceusInc** [comment]
> Thanks for the fast response. I'll use lower-case names from now on.
> 
> WithoutBeingAbleToUseUpperCase or-maybe-using-hyphens_or_underscores itcanbehardtoworkouttheindividualwords :) This is definitely a "me" problem, as most people won't really mind what the resource names are.

itsnotayouproblem,thatsforsure :(
