### ISSUE TITLE
'--cmd' key for 'az acr run'

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#22020]
[Enter feedback here]

Hello, all !

the documentation https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-run says:

'--cmd
Commands to execute. This also supports additional docker run parameters or even other docker commands.'

Where can I find more information which additional docker run parameters I can use and even more important which other docker commands can I execute ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/acr.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/acr.yml)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@alexeyshishkin01 Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@alexeyshishkin01 --cmd is a short cut for [YAML reference - ACR Tasks - Azure Container Registry | Microsoft Docs](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-reference-yaml#cmd), we have also updated the documentation through a PR. Closing the issue now.
