### ISSUE TITLE
Typo 'Description' in az role definition list result table

### ISSUE THREAD

**Issue by jaredmoo** [Azure/azure-cli#2203]
Typo at https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/commands.py#L16

Repro steps:
1. Configure cli to return results as table
2. `az role definition list` -> the table heading is called 'Descritpion'

**Comment by yugangw-msft** [comment]
Don't know when we fixed this typo, but just now I checked and it is fine now
