### ISSUE TITLE
az aks nodepool update --min-count cannot be 0 after az cli update

### ISSUE THREAD

**Issue by siematypie** [Azure/azure-cli#22032]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
After cli update to version 2.35.0 from 2.33.1 we started getting `--min-count must be in the range [1,100]` errors when running 
this command `az aks nodepool update --name <nodepool> --cluster-name <cluster>  --resource-group <rg> --min-count 0 --max-count 2 --update-cluster-autoscaler --mode user`
Setting nodepool min-count to 0 is possible both from older version of cli and azure portal. Was this change intentional?

**To Reproduce**
Run `aks nodepool update --name <nodepool> --cluster-name <cluster>  --resource-group <rg> --min-count 0 --max-count 2 --update-cluster-autoscaler --mode user` on user nodepool with autoscaler enabled

**Expected behavior**
Nodepool should be updated instead of throwing validation errors

**Environment summary**
CLI version: 2.35.0

**Additional context**

**Comment by Sidewinder53** [comment]
This is a pretty serious issue as you can't easily downgrade the Azure CLI on Azure DevOps / Github Actions, effectively making scaling changes with a minimum count of 0 unavailable to many automated processes.

**Comment by PramodValavala-MSFT** [comment]
@siematypie @Sidewinder53 Apologies for the delay here! We have worked up a PR to address this.
