### ISSUE TITLE
Zip Deploy for ASEv3

### ISSUE THREAD

**Issue by crizzs** [Azure/azure-cli#22044]
Currently, im using azure cli 2.35.0 to do zip deployment on ASE v3. Have encountered problems to do zip deploy.

I am able to configure appsettings using azure cli. As for zip config, it timeout-ed.

WARNING: Getting scm site credentials for zip deployment
error	13-Apr-2022 09:28:05	WARNING: Starting zip deployment. This operation can take a while to complete ...
error	13-Apr-2022 09:30:12	ERROR: The command failed with an unexpected error. Here is the traceback:
error	13-Apr-2022 09:30:12	ERROR: HTTPSConnectionPool(host='XXXX.appserviceenvironment.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd62d8f0748>: Failed to establish a new connection: [Errno 110] Connection timed out',))
error	13-Apr-2022 09:30:12	Traceback (most recent call last):
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 170, in _new_conn
error	13-Apr-2022 09:30:12	    (self._dns_host, self.port), self.timeout, **extra_kw
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/urllib3/util/connection.py", line 96, in create_connection
error	13-Apr-2022 09:30:12	    raise err
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/urllib3/util/connection.py", line 86, in create_connection
error	13-Apr-2022 09:30:12	    sock.connect(sa)
error	13-Apr-2022 09:30:12	TimeoutError: [Errno 110] Connection timed out
error	13-Apr-2022 09:30:12	
error	13-Apr-2022 09:30:12	During handling of the above exception, another exception occurred:
error	13-Apr-2022 09:30:12	
error	13-Apr-2022 09:30:12	Traceback (most recent call last):
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
error	13-Apr-2022 09:30:12	    chunked=chunked,
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
error	13-Apr-2022 09:30:12	    self._validate_conn(conn)
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
error	13-Apr-2022 09:30:12	    conn.connect()
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 353, in connect
error	13-Apr-2022 09:30:12	    conn = self._new_conn()
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/urllib3/connection.py", line 182, in _new_conn
error	13-Apr-2022 09:30:12	    self, "Failed to establish a new connection: %s" % e
error	13-Apr-2022 09:30:12	urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd62d8f0748>: Failed to establish a new connection: [Errno 110] Connection timed out
error	13-Apr-2022 09:30:12	
error	13-Apr-2022 09:30:12	During handling of the above exception, another exception occurred:
error	13-Apr-2022 09:30:12	
error	13-Apr-2022 09:30:12	Traceback (most recent call last):
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
error	13-Apr-2022 09:30:12	    timeout=timeout
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
error	13-Apr-2022 09:30:12	    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
error	13-Apr-2022 09:30:12	    raise MaxRetryError(_pool, url, error or ResponseError(cause))
error	13-Apr-2022 09:30:12	urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='XXX.appserviceenvironment.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd62d8f0748>: Failed to establish a new connection: [Errno 110] Connection timed out',))
error	13-Apr-2022 09:30:12	
error	13-Apr-2022 09:30:12	During handling of the above exception, another exception occurred:
error	13-Apr-2022 09:30:12	
error	13-Apr-2022 09:30:12	Traceback (most recent call last):
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
error	13-Apr-2022 09:30:12	    cmd_result = self.invocation.execute(args)
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
error	13-Apr-2022 09:30:12	    raise ex
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
error	13-Apr-2022 09:30:12	    results.append(self._run_job(expanded_arg, cmd_copy))
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
error	13-Apr-2022 09:30:12	    result = cmd_copy(params)
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
error	13-Apr-2022 09:30:12	    return self.handler(*args, **kwargs)
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
error	13-Apr-2022 09:30:12	    return op(**command_args)
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 398, in enable_zip_deploy_functionapp
error	13-Apr-2022 09:30:12	    return enable_zip_deploy(cmd, resource_group_name, name, src, timeout, slot)
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 431, in enable_zip_deploy
error	13-Apr-2022 09:30:12	    res = requests.post(zip_url, data=zip_content, headers=headers, verify=not should_disable_connection_verify())
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/requests/api.py", line 119, in post
error	13-Apr-2022 09:30:12	    return request('post', url, data=data, json=json, **kwargs)
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/requests/api.py", line 61, in request
error	13-Apr-2022 09:30:12	    return session.request(method=method, url=url, **kwargs)
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
error	13-Apr-2022 09:30:12	    resp = self.send(prep, **send_kwargs)
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
error	13-Apr-2022 09:30:12	    r = adapter.send(request, **kwargs)
error	13-Apr-2022 09:30:12	  File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
error	13-Apr-2022 09:30:12	    raise ConnectionError(e, request=request)
error	13-Apr-2022 09:30:12	requests.exceptions.ConnectionError: HTTPSConnectionPool(host='XXXX..appserviceenvironment.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd62d8f0748>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by yonzhan** [comment]
Please provide detailed CLI command.

**Comment by crizzs** [comment]
Hi Yon Zhan,

I am deploying through pipeline. The XXX are existing variables use by the ASE v2, and it is still working well.
az functionapp deployment source config-zip -g XXX -n XXX --src PATH_TO_FILE

**Comment by navba-MSFT** [comment]
@crizzs Thanks for reaching out to us and sharing this feedback. Looking at the above debug output, it seems like the issue is due to the network connectivity causing timeout error. The https connection to this request url _apisvc-afunc-s-omabizcard-v3-uatez.scm.ase-oma-uatezapp-20900015.appserviceenvironment.net_ seems to be timing out. 

Could you please let me know if you have any proxy in your corporate network ? Could you please test the same command from a different network and test if that works fine ? Awaiting your reply.

**Comment by crizzs** [comment]
Hi Navba,

I am able perform 
1. ) nslookup to the address -ILB of ASEv3 (Added to DNS)
2) No proxy in the front and,
3) Able to use az cli to configure this app

**Comment by navba-MSFT** [comment]
@crizzs Thanks for getting back. Sure, Please test it from the portal and please share the debug output again if you see the same issue there.

**Comment by navba-MSFT** [comment]
@crizzs Sure. Take your time. I shall follow-up with you next week.

**Comment by crizzs** [comment]
Hi navba,

It seems like my vm is able to hit the DNS and retrieve the correct ILB IP. However, the ASEv3 ILB is not reachable from my vm with nsg opened.

The azcli should be working as intended. This should be network issue.

Thanks for your help!
Kai

**Comment by navba-MSFT** [comment]
@crizzs Thanks for getting back and sharing the update. Since we have isolated that the issue isn't related to the AzCLI we will proceed with archival of this issue. If you need any assistance in future, please feel free to reopen this issue and we would be happy to help.
