### ISSUE TITLE
 Failed to get subscription status / activate TRIGGER

### ISSUE THREAD

**Issue by k1ko00** [Azure/azure-cli#22051]
Hi all,

I'm having some troubles to create a new trigger in my Azure, it's a Storage Event.

The strange thing here it is working when I trigger manually but when I try to put Status : "Started" and publish it bring me this issue.

I already checked about Resource Provider : Microsoft.StorageAccount and about my V2 of Storage Account

![image](https://user-images.githubusercontent.com/103579065/163181604-e69c7c58-b059-4664-9298-be2d139617eb.png)

**Comment by yonzhan** [comment]
Please provide your detailed CLI command

**Comment by k1ko00** [comment]
{
    "name": "Event_Disponibilidad",
    "properties": {
        "annotations": [],
        "runtimeState": "Stopped",
        "pipelines": [
            {
                "pipelineReference": {
                    "referenceName": "blob-to-sql-Disponibilidad",
                    "type": "PipelineReference"
                }
            }
        ],
        "type": "BlobEventsTrigger",
        "typeProperties": {
            "blobPathBeginsWith": "/1206030/blobs/",
            "blobPathEndsWith": "SC x Sku.xlsx",
            "ignoreEmptyBlobs": true,
            "scope": "/subscriptions/2a51c165-d958-4b6b-9d23-c662f3fdior9/resourceGroups/nmex-pr-1206030-usw2-rgp/providers/Microsoft.Storage/storageAccounts/namspr1206030idusw2sta",
            "events": [
                "Microsoft.Storage.BlobCreated"
            ]
        }
    }
}

**Comment by k1ko00** [comment]
> Please provide your detailed CLI command

**Comment by k1ko00** [comment]
> Please provide your detailed CLI command

{
    "name": "Event_Disponibilidad",
    "properties": {
        "annotations": [],
        "runtimeState": "Stopped",
        "pipelines": [
            {
                "pipelineReference": {
                    "referenceName": "blob-to-sql-Disponibilidad",
                    "type": "PipelineReference"
                }
            }
        ],
        "type": "BlobEventsTrigger",
        "typeProperties": {
            "blobPathBeginsWith": "/906030/blobs/",
            "blobPathEndsWith": "SC x Sku.xlsx",
            "ignoreEmptyBlobs": true,
            "scope": "/subscriptions/2a57c165-d958-4b6a-9d24-c662f3fdabc9/resourceGroups/nmex-pr-906030-usw2-rgp/providers/Microsoft.Storage/storageAccounts/namspr906030idusw2sta",
            "events": [
                "Microsoft.Storage.BlobCreated"
            ]
        }
    }
}
