### ISSUE TITLE
RemoteDisconnected Error When Updating Postgres Server

### ISSUE THREAD

**Issue by zhusulai** [Azure/azure-cli#22054]
## Describe the bug
RemoteDisconnected is thrown when running az command to ensure managed identity is assigned to a Postgres server.

**Command Name**
`az postgres server update --name <server_name> --resource-group <rg_name> --assign-identity`

**Errors:**
```
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- deploy a PostgreSQL signle server (with replica)
- `az postgres server update --name <master_server_name> --resource-group <rg_name> --assign-identity`
- `az postgres server update --name <replica_server_name> --resource-group <rg_name> --assign-identity`

## Expected Behavior
The command should complete without error.

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit, Darwin 20.6.0
Python 3.10.2
Installer: HOMEBREW

azure-cli 2.35.0

Extensions:
azure-cli-ml 1.37.0
azure-devops 0.23.0
resource-graph 2.1.0
ml 2.1.2
interactive 0.4.5

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by SaurabhSharma-MSFT** [comment]
@zhusulai We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@zhusulai I am not seeing any using the cmdlet.  This error means sever somehow closed the connection.  Can you please try executing the same using a Azure Cloud Shell. Additionally, you can try executing the same for some other Postgre server.

**Comment by SaurabhSharma-MSFT** [comment]
@zhusulai Please let me know if you have any questions else we will proceed with closing this case.

**Comment by zhusulai** [comment]
Please keep the ticket open for a few days as I try to reproduce the issue from another environment.

**Comment by SaurabhSharma-MSFT** [comment]
@zhusulai Just wanted to check if you still see any issues with the cli cmdlet.

**Comment by zhusulai** [comment]
I'm not able to reproduce this issue in another environment. The initial error is likely related to the Corp firewall. Thanks for looking into the issue.
