### ISSUE TITLE
Vm Stuck on booting phase for pending update

### ISSUE THREAD

**Issue by yuvaraj-azurevm** [Azure/azure-cli#22053]
[Enter feedback hereOn the day-to-day scenario we receive case for VM failed to boot from Boot diagnostic, its stuck for pending update.

After creating nested VM we ask users to Run DISM /image: <drive letter for problematic disk>:\ /cleanup-image /revertpendingactions.

Adding as a switch in Run Id would beneficial all.
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 355a594a-22ef-fd15-0b58-07701dd1815c
* Version Independent ID: d8356a0a-9aaf-900b-ce7a-021c9a0af509
* Content: [az vm repair](https://docs.microsoft.com/en-us/cli/azure/vm/repair?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm/repair.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm/repair.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
compute

**Comment by zhoxing-ms** [comment]
Since `vm-repair` is owned by the service team, @haagha Could you please help have a look~

**Comment by navba-MSFT** [comment]
@yuvaraj-azurevm Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. 

Depending on the number of updates that are getting installed or rolled backing, the VM update process can take a while. Leave the VM in this state for 8 hours. If the VM is still in this state after that period, restart the VM from the Azure portal, and see if it can start normally. If this step doesn't work, try the solution mentioned [here](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-stuck-updating-boot-error#remove-the-update-that-causes-the-problem). Hope this helps.
The run-id parameter has the 'Unique run id for run scripts'. Could you please elaborate on what details would you like to be included in the [run-id parameter](https://docs.microsoft.com/en-us/cli/azure/vm/repair?view=azure-cli-latest#az-vm-repair-run-examples) ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@yuvaraj-azurevm I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you have any update on this. Awaiting your reply.

**Comment by yuvaraj-azurevm** [comment]
Hello Team,

I had reviewed the article which explains how to remove the update which had caused the problem, However in Generic if the VM is stuck for the updates as referenced in the below Community forum
Virtual Image is stuck in Windows starting screen (microsoft.com)<https://social.msdn.microsoft.com/Forums/azure/en-US/a666a9bf-3619-4633-a432-85952ace6a03/virtual-image-is-stuck-in-windows-starting-screen?forum=WAVirtualMachinesforWindows>

The quick steps for restoring the machine is using dism.exe /image:e:\ /cleanup-image /revertpendingactions

I am reaching out to check if the "dism.exe /image:<attacheddiskvolume>:\ /cleanup-image /revertpendingactions" can be added in the run-id parameter.

Regards,
Yuvaraj Jayaraman

**Comment by navba-MSFT** [comment]
@yuvaraj-azurevm I have initiated an email thread with Product Owners and looped you in that email thread. We can continue the conversation there and check the feasibility of having such feature.

**Comment by navba-MSFT** [comment]
@yuvaraj-azurevm We have reached out to the right PM owner for this feature over email and continuing our conversation there. So archiving this thread for now.
