### ISSUE TITLE
Please make the description of the --tags parameter clearer.

### ISSUE THREAD

**Issue by ahanafusa** [Azure/azure-cli#22059]
The description of the --tags parameter is confusing.
![image](https://user-images.githubusercontent.com/98443502/163295243-45dd6262-5ac6-40ce-ba8a-41987543f28f.png)

It is misleading that [] is required.
For example, I did not understand that the tag name including the space is specified as follows.
--tags "Department Code=784500" 

Would you please describe it in an easy-to-understand manner?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ce5e4a8-6bd4-cb82-4709-8d9ed53e41b2
* Version Independent ID: 3d808e36-e1fe-6e2d-c812-63df2bc6b732
* Content: [az monitor alert-processing-rule](https://docs.microsoft.com/en-us/cli/azure/monitor/alert-processing-rule?view=azure-cli-latest#az-monitor-alert-processing-rule-update)
* Content Source: [latest/docs-ref-autogen/monitor/alert-processing-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/monitor/alert-processing-rule.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
monitor

**Comment by YuanyuanNi** [comment]
Hi：
     @ahanafusa As the way to use tags, you can refer below examples:
1.Add or update tags: az image update -n ImageName -g ResourceGroup --tags tag1=val1 tag2=val2
2.Remove all tags：az image update -n ImageName -g resourceGroup --tags
Best wishes.
