### ISSUE TITLE
Error message: VM SSH currently doesn't support managed identity or Cloud Shell.

### ISSUE THREAD

**Issue by maertendMSFT** [Azure/azure-cli#22057]
https://github.com/Azure/azure-cli/blob/2e0a42f304f5fd543818a98a9eab2faf8d1fd6d6/src/azure-cli-core/azure/cli/core/auth/adal_authentication.py#L23

This line should tell the users to run `az login` prior to running `az ssh`, not the current text, `VM SSH currently doesn't support managed identity or Cloud Shell.`

New recommended text "`az login` must be run before `az ssh` in Cloud Shell."

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
We are working on Azure Cloud Shell's SSH support right now! See #22063.
