### ISSUE TITLE
CLI: az vm update --host argument not working as expected

### ISSUE THREAD

**Issue by brittanyrowe** [Azure/azure-cli#22069]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az vm update for VMs on multitenant doesn't work as expected in the following use cases:
1. For a multitenant VM in the same region/zone as the host/host group, if the host group does NOT have VM autoplacement enabled, the value for the --host argument should be the host name, not the host ID:
![image](https://user-images.githubusercontent.com/75815751/163480510-5da72341-e1c4-4b84-b888-cf5d1ba3390f.png)
Host ID in this case, is confusing to the customer in that there are multiple properties that seem like they could be the correct ID (asset ID, host ID, essentials ID):
![image](https://user-images.githubusercontent.com/75815751/163480768-b3c4ff35-c536-4fc2-abed-64c592f57ec9.png)
It would be more intuitive to use the host name (e.g. testHost)

2. For a VM on ADH, you cannot use az vm update to change the host assignment to nothing (e.g. moving it to multitenant rather than ADH). This is the same for host group assignment for autoplaced VMs.
![image](https://user-images.githubusercontent.com/75815751/163480571-093a3874-4eff-4d99-92d1-a1b7e32ca5cc.png)

**To Reproduce**
Scenario 1: Create a VM in multitenant and a HG/ADH in the same region/zone as the VM. Stop/deallocate the VM. Try to use az vm update with the --host argument using just the host name or the host ID, not the full /subscriptions/... resource path.
Scenario 2: Have a VM running on an ADH. Stop the VM. Invoke az vm update with --host "" or -- host "" --host-group "". Or set either to null.

**Expected behavior**
For manual placement, the VM should be able to use the simple host name (rather than ID) to be assigned to the host. Automatic VM placement works as expected to place the VM onto the host (e.g. az vm update with **only** --host-group specified in a host group with autoplacement is enabled). 
For manual placement, the VM should be able to be removed from the host by removing any value assigned to host via --host "" (or null? Whatever is best practice). For autoplaced VMs, the VM should be able to be removed from the host group by removing any value assigned to the host group by --host-group "" (or null, whatever is best practice).

**Environment summary**
CLI: 2.35.0
OS: Windows 11

**Additional context**

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@cxznmhdcxz Please help have a look~

**Comment by cxznmhdcxz** [comment]
Hi @brittanyrowe , for Scenario 2, this command could remove a vm from host:
`az vm update -n vm -g group --set "host={}" `

**Comment by brittanyrowe** [comment]
@cxznmhdcxz  can we please update documentation to include how to remove a VM from a host?
