### ISSUE TITLE
Single Click SSH in Azure Cloud Shell

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#22063]
## Requirement

Using Azure Cloud Shell account to SSH into an Azure VM is currently not supported:

https://github.com/Azure/azure-cli/blob/2e0a42f304f5fd543818a98a9eab2faf8d1fd6d6/src/azure-cli-core/azure/cli/core/auth/adal_authentication.py#L23

We are working with MSAL and VM team to implement Single Click SSH in Azure Cloud Shell.

## Workaround

As pointed out by https://github.com/Azure/azure-cli/issues/22057#issue-1203904439, a workaround is to run `az login` in Cloud Shell to replace the default Cloud Shell account with a user/service principal account. Then `az ssh vm` will work as expected.

## References

- https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/420
- https://github.com/Azure/azure-cli-extensions/pull/4641
- https://github.com/Azure/azure-cli/issues/22057
- https://docs.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-linux

**Comment by jiasli** [comment]
## Workaround

As pointed out by https://github.com/Azure/azure-cli/issues/22057#issue-1203904439, a workaround is to run `az login` in Cloud Shell to replace the default Cloud Shell account with a user/service principal account.

**Comment by svrooij** [comment]
Why are all these issues closed, when it still isn't working on the cloudshell? Are they in the process of being released? @jiasli or @yonzhan ?

**Comment by jiasli** [comment]
The code change for Azure CLI is already finished by https://github.com/Azure/azure-cli/pull/22162.
