### ISSUE TITLE
Subscription parameter is missing in documentation.

### ISSUE THREAD

**Issue by MichaelJRogersGM** [Azure/azure-cli#22065]
[Enter feedback here]
The subscription parameter is missing documentation.

It is included on this page:
https://docs.azure.cn/en-us/cli/deployment/group?view=azure-cli-latest#az-deployment-group-create

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649a07bb-0fa2-6c51-2820-88b1bafa80ba
* Version Independent ID: ace434b7-7549-8e6d-cab0-1612f422a0cf
* Content: [az deployment group](https://docs.microsoft.com/en-us/cli/azure/deployment/group?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/deployment/group.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/deployment/group.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
What do you mean by missing documents? In fact, I can see the relevant document doc link: [az-deployment-group-create-optional-parameters](https://docs.azure.cn/en-us/cli/deployment/group?view=azure-cli-latest#az-deployment-group-create-optional-parameters)
![Screenshot 2022-04-15 094242](https://user-images.githubusercontent.com/16612065/163504836-6c205718-f7ee-4bca-ab44-b268ff107ccc.png)

**Comment by MichaelJRogersGM** [comment]
Hi @zhoxing-ms 

It is included on that link but not on this page:
Content: [az deployment group](https://docs.microsoft.com/en-us/cli/azure/deployment/group?view=azure-cli-latest)

![image](https://user-images.githubusercontent.com/25063204/163623529-e68aea10-2ffd-4ebf-b0bd-8fa22f9786b0.png)

https://docs.microsoft.com/en-us/cli/azure/deployment/group?view=azure-cli-latest

**Comment by zhoxing-ms** [comment]
In fact, `az deployment group` is a command group that contains only sub commands but no parameters
![Screenshot 2022-04-16 121830](https://user-images.githubusercontent.com/16612065/163661112-f37fc58f-e500-42b9-9888-8ef465a8f18e.png)
