### ISSUE TITLE
[resource] Bump `azure-mgmt-resource` to latest version(> 21.0.0)

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-cli#22073]
**Is your feature request related to a problem? Please describe.**

There is a bug in `azure-mgmt-resource` and it shall also influence azure cli. For more details, see https://github.com/Azure/azure-sdk-for-python/issues/23828

**Describe the solution you'd like**

Bump version to latest (> 21.0.0)

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
resource
