### ISSUE TITLE
Issue with az webapp log tail

### ISSUE THREAD

**Issue by omerblecher** [Azure/azure-cli#22075]
## Describe the bug

**Command Name**
`az webapp log tail`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp log tail --name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0 *

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
Hello @omerblecher Could you please add more information to the issue? any short detail on the error encountered?

![image](https://user-images.githubusercontent.com/62923178/164103713-01c7a6fc-4050-46b7-9a13-08fdb5db1f53.png)

![image](https://user-images.githubusercontent.com/62923178/164104378-812f50a3-0d31-472e-9491-d4467ad94cdd.png)

**Comment by SatishBoddu-MSFT** [comment]
Hello @omerblecher Just checking back, could you please let us know if you need further help in this matter.
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
