### ISSUE TITLE
az acr login hangs

### ISSUE THREAD

**Issue by roy-work** [Azure/azure-cli#22080]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
```
» az acr login -n <snip> --debug
cli.knack.cli: Command arguments: ['acr', 'login', '-n', '<snip>', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x10fef2290>, <function OutputProducer.on_global_arguments at 0x10ff3d120>, <function CLIQuery.on_global_arguments at 0x10ff9a680>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'acr': ['azure.cli.command_modules.acr']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acr                       0.007        28       116
cli.azure.cli.core: Total (1)                 0.007        28       116
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 28 groups, 116 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : acr login
cli.azure.cli.core: Command table: acr login
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x1105c9360>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/roy/.azure/commands/2022-04-15.14-04-37.acr_login.54779.log'.
az_command_data_logger: command args: acr login -n {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x1105eab90>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x1106b0790>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x1106b0820>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x1106b0940>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x10ff3d1b0>, <function CLIQuery.handle_query_parameter at 0x10ff9a710>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x1106b0700>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x1106b08b0>]

```
And it hangs there.

**To Reproduce**
Other than running `az`, 🤷. It reproduces for me, presently.

**Expected behavior**
It doesn't hang.

**Environment summary**
macOS, installed via brew.
```
» az version
{
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "automation": "0.1.1",
    "ssh": "1.0.0"
  }
}
```

**Additional context**

The output appears to indicate that this is a different hang than the one in #16312.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@roy-work Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. I was able to run the az acr login `cmd` on my box. Sharing my Az CLI version here:

az version
{
  "azure-cli": "2.35.0",
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.60",
    "attestation": "0.2.0",
    "db-up": "0.2.7"
  }
}

The `az acr login` cmd helps to Log in to an Azure Container Registry through the Docker CLI. So Docker must be installed on your machine. Could you please confirm if that is done ? Once done, use 'docker logout ' to log out. 

Note: If you only need an access token and do not want to install Docker, specify **'--expose-token'** parameter. Please let me know if that works fine. Awaiting your reply.

**Comment by roy-work** [comment]
> Docker must be installed on your machine. Could you please confirm if that is done ? 

… even if it _weren't_, hanging would hardly be the appropriate response. But, it is.

What I suspect happened here is that `az` was making a silent call to `docker`, and it was *that* that was hanging. I found today that *any* `docker` command on my machine was hanging, and a force-restart of docker & all its parts fixed that.

After that, `az acr login` appears to work again.

It would be helpful to have a log in `--debug` if that is what's going on; if I had known that `az` was trying (unsuccessfully) to run `docker`, I'd know who to try restarting.

**Comment by navba-MSFT** [comment]
@roy-work I am glad that post restarting of the docker the issue is resolved. Regarding your suggestion on the --debug logs, You could check the logs that are saved in this path: /Users/roy/.azure/commands/2022-04-15.14-04-37.acr_login.54779.log and check if that has the details about the call being done to docker CLI. 

If you need any further assistance on this github thread, please let us know.

**Comment by navba-MSFT** [comment]
@roy-work I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@roy-work We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
