### ISSUE TITLE
Add support for pre-existing resource group

### ISSUE THREAD

**Issue by sercast** [Azure/azure-cli#22086]
As a support engineer, we constantly run into issues trying to use az vm repair create with customers that do not have the necessary permissions at the subscription scope to create the necessary resources. Often, they might be scoped to a certain resource group, or can only request these permissions at the RG scope.

Currently az vm repair create will not let you specify an existing RG.

Ask. Add option to specify an existing (empty) RG that customer has the necessary permissions to and add parameter to confirm the specified RG is empty and user understands it will be deleted during the restore/cleanup phase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 355a594a-22ef-fd15-0b58-07701dd1815c
* Version Independent ID: d8356a0a-9aaf-900b-ce7a-021c9a0af509
* Content: [az vm repair](https://docs.microsoft.com/en-us/cli/azure/vm/repair?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm/repair.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm/repair.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@sercast Thank you for reaching out to us, we are looking into it.
