### ISSUE TITLE
Unable to off auto-pause of azure sql server db

### ISSUE THREAD

**Issue by anandadake** [Azure/azure-cli#22095]
Hello There.. 

I'm trying to off the auto-pause sql service but
i could not found any option in web UI or Azure cli

if you cloud proved the guidance to off my azure sql auto pause option that will be appreciated.
 
basically i'm trying to do something like =>

az sql db update -g $resourceGroupName -s $serverName -n $databaseName  --auto-pause OFF

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@anandadake If you are using a serverless database then you need to use `--auto-pause-delay` with a value of -1 to disable the automatic pause for the DB.
You can also do the same from Azure portal by clicking on "Auto-pause Delay"
![image](https://user-images.githubusercontent.com/38112130/163893367-313fb651-b362-45a4-8c1f-05292f80bbdb.png)
and disable it by using "Enable Auto-pause" checkbox.
![image](https://user-images.githubusercontent.com/38112130/163893472-80599c06-1d0f-4c77-8f19-ddeca8b05b1f.png)

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@anandadake Please let me know if you have any other questions else we will proceed with closing this issue. Thanks

**Comment by SaurabhSharma-MSFT** [comment]
@anandadake We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by anandadake** [comment]
Thank you so much folks...

I really Appreciate your time and efforts...

**Comment by anandadake** [comment]
Thank you so much folks...

I really Appreciate your time and efforts...
