### ISSUE TITLE
unable to import zone file

### ISSUE THREAD

**Issue by EnrgyOrg** [Azure/azure-cli#22097]
## Describe the bug

**Command Name**
`az network dns zone import`

**Errors:**
```
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-49qlvzn7\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 711, in _run_job
AppData\Local\Temp\pip-unpacked-wheel-tle01379\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
pip-unpacked-wheel-03qxfwck\azure\cli\core\__init__.py, ln 784, in default_command_handler
azure\cli\command_modules\network\custom.py, ln 2050, in import_zone
cli\command_modules\network\zone_file\parse_zone_file.py, ln 413, in parse_zone_file
cli\command_modules\network\zone_file\parse_zone_file.py, ln 305, in _add_record_names
cli\command_modules\network\zone_file\parse_zone_file.py, ln 205, in _serialize
TypeError: argument of type 'NoneType' is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network dns zone import -g {} -n {} -f {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.14.0 *

```

**Comment by EnrgyOrg** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kaan.ara/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kaan.ara/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Name | Type | Data | Record Source | Principal | Protected | Comment | Monitored Since | Last Queried | Reclaimable | Creation Time
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | A Record | 13.93.41.213 | Static |   | No | 1.02E+08 | Not Monitored | Not Monitored | No | 2020-01-16 21:24:08 AST
mail | A Record | 195.87.219.3 | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-01-16 21:24:08 AST
webmail | A Record | 193.243.207.230 | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-01-16 21:24:08 AST
autodiscover | CNAME Record | autodiscover.outlook.com | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-01-16 21:24:08 AST
enterpriseenrollment | CNAME Record | enterpriseenrollment.manage.microsoft.com | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-01-16 21:24:08 AST
enterpriseregistration | CNAME Record | enterpriseregistration.windows.net | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-01-16 21:24:08 AST
lyncdiscover | CNAME Record | webdir.online.lync.com | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-01-16 21:24:08 AST
msoid | CNAME Record | clientconfig.microsoftonline-p.net | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-01-16 21:24:08 AST
sip | CNAME Record | sipdir.online.lync.com | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-01-16 21:24:08 AST
www | CNAME Record | seturtm.trafficmanager.net | Static |   | No | 89020282 / 102095838 | Not Monitored | Not Monitored | No | 2020-06-25 18:38:57 AST
  | MX Record | 1 mx2.aspmsg.net | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-01-16 21:24:07 AST
  | MX Record | 0 mx.aspmsg.net | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-01-16 21:24:07 AST
_sip._tls | SRV Record | 1 100 443 sipdir.online.lync.com | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-01-16 21:24:08 AST
_sipfederationtls._tcp | SRV Record | 0 5 5061 sipfed.online.lync.com | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-01-16 21:24:08 AST
  | TXT Record | "v=spf1 ip4:193.243.210.5 ip4:195.87.219.151 ip4:195.87.219.152   ip4:195.87.219.153 ip4:31.145.3.85 ip4:31.145.3.86   include:spf.protection.outlook.com include:euromsg.net -all" | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-01-16 21:24:07 AST
awverify | TXT Record | setur-setair-web.azurewebsites.net | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-06-26 17:53:30 AST
awverify.www | TXT Record | setur-setair-web.azurewebsites.net | Static |   | No |   | Not Monitored | Not Monitored | No | 2020-06-26 17:53:42 AST



</body>

</html>

**Comment by EnrgyOrg** [comment]
it seems because of line starting with space.

**Comment by yonzhan** [comment]
network
