### ISSUE TITLE
Microsoft.Compute/ProximityPlacementGroup cmd to support User intent

### ISSUE THREAD

**Issue by aspand** [Azure/azure-cli#22101]
**Resource Provider**
Azure.Compute

**Description of Feature or Work Requested**
Intent
Intent is an optional parameter which you can provide while creating a [proximity placement group](https://docs.microsoft.com/en-us/azure/virtual-machines/co-location). It can also be added or modified while updating the PPG after deallocating all VMs in the proximity placement group.

The intent allows you to provide one or more [VM Sizes](https://docs.microsoft.com/en-us/azure/virtual-machines/sizes) that you require to be deployed as part of the proximity placement group(across single VMs, Availability Sets and VM Scale Sets).

Availability zone
In addition to the intent, an optional availability zone can be provided using zones parameter in case the proximity placement group must be created within a specific zone. Please note:

The availability zone can be provided only during proximity placement group creation and cannot be modified subsequently; unlike the intent, it cannot be updated even when the proximity placement group has all VM resources deallocated

The availability zone can be provided only when an intent is provided

Only one zone can be indicated as part of the availability zone

Please note that specifying a zone does not allow the proximity placement group to span the entire zone. It only helps select a data center within the specified zone rather than anywhere in the region.

The PPG create and update API with zones and intent parameters will look like the following:

API Version
API version must be 2021-11-01 or higher for using proximity placement group Intent

{
"apiVersion": "2021-11-01", 
"type": "Microsoft.Compute/proximityPlacementGroups", 
"name": "[parameters('ppgName')]", 
"location": "[resourceGroup().location]", 
“zones”: [“2”],
"properties": { 
    "proximityPlacementGroupType": "Standard", 
    “intent”: {
     "vmSizes": ["Standard_E64s_v4", "Standard_M416ms_v2"]
  }
}

Role of Intent in Proximity Placement Groups:
The PPG creation or update will succeed only when at least one datacenter supports all the VM Sizes in the intent. Otherwise, it will fail with ProximityPlacementGroupOverconstrainedIntent indicating that the combination of VM Sizes cannot be supported within a PPG.

When you ask for the first VM in a proximity placement group(or when the first VM is started in a deallocated proximity placement group ), the intent is used to select an appropriate datacenter. This reduces the chances of failures arising from non-existence of the VM Sizes (provided in the intent) in the selected datacenter. This also allows VMs (whose sizes are mentioned in the intent) in the proximity placement group to be deployed in any order.

The intent does not provide any capacity guarantee or capacity reservation; hence AllocationFailure can still occur if there’s no capacity for the VM size at the time of VM deployment.

**Minimum API Version Required**
"apiVersion": "2021-11-01"

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/18159

**Target Date**

**Comment by SaurabhSharma-MSFT** [comment]
@zhoxing-ms We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@aspand @SaurabhSharma-MSFT Could you please provide the specific design for related CLI commands and parameters?
And may I ask what's the ETA for this requirement?

**Comment by zhoxing-ms** [comment]
@Drewm3 Could you please provide the specific design for related CLI commands and parameters?
And may I ask what's the ETA for this requirement?

**Comment by Drewm3** [comment]
I believe the functionality is available in the REST API now. The input is a list of VM SKUs. This list is optional.

I didn't open this originally, so I am unsure if there are specific customers who need this sooner rather than later. I would suggest adding it when it is convenient for the CLI team.

**Comment by yanzhudd** [comment]
Hello @Drewm3 and @aspand, we notice that this feature is similar with #22466. Can this feature be replaced by #22466 or is there any new request for this feature that is different from that?
If this feature cannot be repalced, could you please provide the specific design for related CLI commands and parameters?
