### ISSUE TITLE
'compute' is misspelled or not recognized by the system

### ISSUE THREAD

**Issue by fepegar** [Azure/azure-cli#22107]
Hi! I've been trying to start my compute instance using `az ml compute`, but the following happens:

```console
$ az ml compute list                                                    
'compute' is misspelled or not recognized by the system.
Did you mean 'computetarget' ?

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
```

Upgrading doesn't help:

```console
$ az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
You already have the latest azure-cli version: 2.35.0
Upgrading extensions
Checking update for azure-cli-ml
No updates available for 'azure-cli-ml'. Use --debug for more information.
Checking update for ssh
Upgrade finished.You can enable auto-upgrade with 'az config set auto-upgrade.enable=yes'. More details in https://docs.microsoft.com/cli/azure/update-azure-cli#automatic-update
```

Am I doing anything wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71c25404-a256-62b2-3ac8-dd699fc677ba
* Version Independent ID: 5f3dccba-b2ee-224b-9e84-80ba2bbde641
* Content: [az ml compute](https://docs.microsoft.com/en-us/cli/azure/ml/compute?view=azure-cli-latest&source=docs)
* Content Source: [latest/docs-ref-autogen/ml/compute.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ml/compute.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@fepegar The `compute` subcommand is part of the v2 extension (`ml` instead of `azure-cli-ml`). You can uninstall and install v2 of the extension using the following commands

```sh
az extension remove --name azure-cli-ml
az extension add --name ml
```

**Comment by fepegar** [comment]
Got it. Thanks, @PramodValavala-MSFT!
