### ISSUE TITLE
"az iot dps enrollment-group registration" - How to register a device in an enrollment group with az cli?

### ISSUE THREAD

**Issue by jonmikeli** [Azure/azure-cli#22111]
[Enter feedback here]

Hi,

Is there a way to register a device in an enrollment group using az cli?
I am maybe missing something but I have not seen it in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5507493c-f13f-002f-9ce4-e1f344fd0ac2
* Version Independent ID: e32141a2-7b8e-5339-bde8-c454c69cf307
* Content: [az iot dps enrollment-group registration](https://docs.microsoft.com/en-us/cli/azure/iot/dps/enrollment-group/registration?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/iot/dps/enrollment-group/registration.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/iot/dps/enrollment-group/registration.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@jonmikeli We are looking into it and get back to you for any additional information.

**Comment by SatishBoddu-MSFT** [comment]
Hello @jonmikeli thanks for the great query!

I see the current [documentation](https://docs.microsoft.com/en-us/cli/azure/iot/dps/enrollment?view=azure-cli-latest) only shows CLI commands with enrollment create,delete,list,show, and update.

![image](https://user-images.githubusercontent.com/62923178/164108462-55551828-dfc7-4185-81a8-37bf0a98a541.png)

I am checking internally on this!

**Comment by SatishBoddu-MSFT** [comment]
Hoello @jonmikeli ,

May i know the use case on this ask?

**Comment by jonmikeli** [comment]
Hello @SatishBoddu-MSFT ,

Sure.

The idea was to create industrialized tests for IoT (integration tests, validating complete use cases) and for that, I was thinking of provisioning the devices by script. az cli would have been a great solution.
For now, I have implemented containerized device simulators but please, let me know if at some point in time, device provisioning at DPS level will be possible by az cli.

**Comment by SatishBoddu-MSFT** [comment]
Hello @jonmikeli thanks for sharing the scenario!
I hope you have already visited the below document/
[Group Enrollments](https://docs.microsoft.com/en-us/azure/iot-dps/concepts-symmetric-key-attestation?tabs=azure-cli#group-enrollments)
The symmetric keys for group enrollments are not used directly by devices when provisioning. Instead devices that belong to an enrollment group provision using a derived device key.

![image](https://user-images.githubusercontent.com/62923178/164320627-ca3eb12e-a8d0-4da7-83b6-fb82c0c2a563.png)

**Comment by jonmikeli** [comment]
Hello @SatishBoddu-MSFT ,

Thank you for your answer.
Yes, I already read the documentation you mention. I am taking it into account in my simulators.

As for the last question, that is exactly what I need :).
It would unlock (or simplify) quite a lot of DevOps-oriented use cases in IoT (basically tests and quality indicators).

**Comment by SatishBoddu-MSFT** [comment]
Hello @jonmikeli Thanks for the suggestion on this topic, i hope this will be addressed soon!.

Could you please submit a feature request with the scenario on the Official Ideas Portal?
[feedback.azure.com](https://feedback.azure.com/d365community/forum/fcb810f7-f824-ec11-b6e6-000d3a4f0da0)

![image](https://user-images.githubusercontent.com/62923178/164804612-1bc76eec-28dd-4a5f-a35c-e5d79d5a32c7.png)

We have conveyed this to our team internally.

**Comment by digimaun** [comment]
@jonmikeli as of IoT extension release [0.15.0](https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.15.0), we offer an in preview `az iot device registration create` command. Here are the reference docs for it https://docs.microsoft.com/en-us/cli/azure/iot/device/registration?view=azure-cli-latest#az-iot-device-registration-create . Let us know if you have any questions - [this repo](https://github.com/Azure/azure-iot-cli-extension) is specifically for the IoT extension, you would get help faster for `az iot` related questions/issues.

**Comment by jonmikeli** [comment]
Hi @digimaun,

Thank you for keeping me updated (and for implementing the feature). I truly appreciate.
I will try to use the new command in the upcoming weeks and let you know if I have more questions.
Thanks.
