### ISSUE TITLE
Cannot find specified id in system when trying to update throughput

### ISSUE THREAD

**Issue by team-gangreen-gang** [Azure/azure-cli#22121]
### **This is autogenerated. Please review and update as needed.**

Cannot find specified id in system when trying to update throughput

**Command Name**
`az cosmosdb mongodb collection throughput show`

**Errors:**
```
(NotFound) Entity with the specified id does not exist in the system. More info: https://aka.ms/cosmosdb-tsg-not-found

ActivityId: 6d5bb5b0-c021-11ec-bd0b-c8b29b8ad6c5, Microsoft.Azure.Documents.Common/2.14.0
Code: NotFound
Message: Entity with the specified id does not exist in the system. More info: https://aka.ms/cosmosdb-tsg-not-found

ActivityId: 6d5bb5b0-c021-11ec-bd0b-c8b29b8ad6c5, Microsoft.Azure.Documents.Common/2.14.0

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cosmosdb mongodb collection throughput show -a {} -d {} -g {} -n {}`

## Environment Summary
```
Windows-10-10.0.18363-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0

Extensions:
account 0.2.2

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@team-gangreen-gang Thanks for reaching out to us. We are looking into this issue. We will provide an update once we have more details on this.

**Comment by navba-MSFT** [comment]
@team-gangreen-gang Please refer [this](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/troubleshoot-not-found#reading-throughput-for-a-container-or-database-resource) article. 

>Using PowerShell or Azure CLI and receive not found error message while reading throughput for a container or database resource

>Solution:
Throughput can be provisioned at the database level, container level, or both. If getting a not found error, try reading throughput the parent database resource, or child container resource.

Try to run the below command to check the throughput at the database level and that should work.

```
az cosmosdb mongodb database throughput show --account-name   --name    --resource-group
```                                             
More Info [here](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/mongodb/database/throughput?view=azure-cli-latest#az-cosmosdb-mongodb-database-throughput-show). Hope this helps.

**Comment by team-gangreen-gang** [comment]
@navba-MSFT that command works, but I am trying to get the throughput on the collections level, which doesn't seem to work.

**Comment by navba-MSFT** [comment]
@team-gangreen-gang Thanks for getting back. Before you fetch the thrpughput value at the collection level, Could you please confirm if you have set the throughput value at the collection level using the [update](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/mongodb/collection/throughput?view=azure-cli-latest#az-cosmosdb-mongodb-collection-throughput-update) command ? Awaiting your reply.

**Comment by team-gangreen-gang** [comment]
when trying to run that command I get the following error: local variable 'throughput_resource' referenced before assignment

**Comment by navba-MSFT** [comment]
@team-gangreen-gang Thanks for for getting back. We are looking into this issue and we will provide an update on this thread. 
In the meantime, As a workaround could you please try to run [this](https://docs.microsoft.com/en-us/azure/cosmos-db/scripts/powershell/mongodb/create?toc=/powershell/module/toc.json) Powershell script to set the throughput at the collection level ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@team-gangreen-gang I was able to reproduce this issue in Powershell too. I have involved the Product Owners and awaiting their reply.

**Comment by navba-MSFT** [comment]
@team-gangreen-gang On your Cosmos MongoDB API account, Could you please create a new database and collection using the below settings and then test updating the throughput ?
1. **Uncheck** the setting 'share throughput across collection'
2. Select 'Manual collection throughput' option

![image](https://user-images.githubusercontent.com/57353862/164480796-63efc159-71be-4440-9982-95a0fa0d089f.png)

Then you can try to run the above command and see if that helps. Awaiting your reply.

**Comment by team-gangreen-gang** [comment]
I did what you said and I am able to get throughput of the new database. But I am still getting the same `(NotFound) Entity with the specified id does not exist in the system.` error when trying to get the throughput of my existing collection

**Comment by navba-MSFT** [comment]
@team-gangreen-gang You are right. Also a container with provisioned throughput cannot be converted to shared database container. Conversely a shared database container cannot be converted to have a dedicated throughput. 
More Info [here](https://docs.microsoft.com/en-us/azure/cosmos-db/set-throughput#set-throughput-on-a-container). Please let us know if you need any further help on this or we can proceed with archival of this thread.

**Comment by navba-MSFT** [comment]
> when trying to run that command I get the following error: local variable 'throughput_resource' referenced before assignment

@team-gangreen-gang Thanks for reporting this bug. This has been fixed in this PR https://github.com/Azure/azure-cli/pull/22138 and it will be addressed in the next release.
