### ISSUE TITLE
Change Entity Table Data Type using Az CLI

### ISSUE THREAD

**Issue by v-paulocunha** [Azure/azure-cli#22130]
Hi,

Have a customer that is trying to change the data type to String on entity table but unfortunately customer is facing difficulties to do that since the command that is being used doesn't work with the latest version (2.35.0) of Az CLI modules.

Tried the following command "_**az storage entity insert --entity PartitionKey="AAA" RowKey="BBB" Content="ADSF2" CostCenterId="111111" CostCenterId@odata.type="Edm.String" --if-exists merge --table-name "teste1" --connection-string $connectionString**_" and with the version 2.34.1 it worked:

![2 34 1 - complete](https://user-images.githubusercontent.com/104090389/164278470-7608b70f-92b9-4fac-9362-7ffeca79a8ff.PNG)

Tried as well with the same command and with the version 2.35.0 it doesn't work:

![2 35 0 - Failed](https://user-images.githubusercontent.com/104090389/164279678-9c243c07-d850-4c5a-9085-455268e42e42.PNG)

Request ID of the error: 495fea4e-2002-006a-76d4-54f291000000

Can you please help?

Paulo Cunha

**Comment by yonzhan** [comment]
storage

**Comment by danielriedmann** [comment]
Version 2.36.0 of azure cli fixed the issue with the string but introduced a new problem. When using Edm.Boolean the value is added as string and not like an boolean value.

**Comment by evelyn-ys** [comment]
@danielriedmann thanks for reaching out. It seems like Python SDK issue.

The azure-data-tables SDK doesn't handle Edm.Boolean properly, see [SDK code](https://github.com/Azure/azure-sdk-for-python/blob/feb23dc92c252d63c04048bd332944bfc1e7e72c/sdk/tables/azure-data-tables/azure/data/tables/_serialize.py#L82-L83):

```
def _to_entity_bool(value):
    return None, value
```

Unlike other convertors([_to_entity_binary](https://github.com/Azure/azure-sdk-for-python/blob/feb23dc92c252d63c04048bd332944bfc1e7e72c/sdk/tables/azure-data-tables/azure/data/tables/_serialize.py#L78-L79), [_to_entity_datetime](https://github.com/Azure/azure-sdk-for-python/blob/feb23dc92c252d63c04048bd332944bfc1e7e72c/sdk/tables/azure-data-tables/azure/data/tables/_serialize.py#L86-L97), [_to_entity_float](https://github.com/Azure/azure-sdk-for-python/blob/feb23dc92c252d63c04048bd332944bfc1e7e72c/sdk/tables/azure-data-tables/azure/data/tables/_serialize.py#L100-L107) ...), It doesn't do anything. It should at least return `None, bool(value)`
