### ISSUE TITLE
'az ssh config' failure

### ISSUE THREAD

**Issue by jeanbaptisteng** [Azure/azure-cli#22144]
**Describe the bug**
After automatic upgrade of Azure-cli for Windows 11, az ssh config was not worked. It is related to ssh extension 1.1.0. 

**To Reproduce**
1. Upgrade azcli and ssh extension to the latest version 
> az upgrade 
...
> az version
{
  "azure-cli": "2.35.0",
  "azure-cli-core": "2.35.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ssh": "1.1.0"
  }
}
> az ssh config --file C:\Users\*** (username) \.ssh\config --ip *** (ip address)

The following error message were prompted, which is unexpected

Failed to create ssh key file with error: [WinError 2] System cannot find the file.
Ensure OpenSSH is installed and the PATH Environment Variable is set correctly.
Alternatively, use --ssh-client-folder to provide OpenSSH folder path.

Even I added "--ssh-client-folder C:\Windows\System32\OpenSSH", I could still get the error message 

**Expected behavior**
> az ssh config --file C:\Users\<USERNAME>\.ssh\config --ip <IP ADDRESS>
C:\Users\roqqett\.ssh\**** contains sensitive information (id_rsa, id_rsa.pub, id_rsa.pub-aadcert.pub) valid: from ***
Please delete it once you no longer need this config file.

**Environment summary**

Here are my running environment
Operating System: Windows 11 Home edition (21H2) (traditional chinese)
azure-cli: "2.35.0",
azure-cli-core: "2.35.0",
azure-cli-telemetry: "1.0.6",
extensions: 
    ssh: "1.1.0"

**Additional context**
az ssh config resume normal after downgrading ssh extension to 1.0.0 with the following command

> az extension remove --name ssh

> az extension add --name ssh --version 1.0.0

**Conclusion**
ssh extension 1.0.0: OK
ssh extension 1.1.0: Got the issue

I think it is related to the issue of ssh extension (version 1.1.0). Please check. 

Regards, 
Jean

**Comment by SatishBoddu-MSFT** [comment]
Hello @jeanbaptisteng Thanks for reporting the issue, we are routing this to Service Teams' attention!

![image](https://user-images.githubusercontent.com/62923178/164563767-5ef65b9a-b602-4fef-bac8-038e37755ae8.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by kasperbilde** [comment]
I can confirm similar behaviour on Windows 10. When trying to `ssh` to a VM, I get the following error:
```
Could not find C:\Windows\System32\OpenSSH"\ssh-keygen.exe in provided --ssh-client-folder C:\Windows\System32\OpenSSH". Attempting to use pre-installed OpenSSH.
Failed to create ssh key file with error: [WinError 2] The system cannot find the file specified.
Ensure OpenSSH is installed and the PATH Environment Variable is set correctly.
Alternatively, use --ssh-client-folder to provide OpenSSH folder path.
```

When downgrading to version 1.0.0 as mentioned above, I can connect to the VM.

**Comment by lbergeron01** [comment]
The new code of extension v1.1.0 is not able to translate ``C:\Windows\System32\OpenSsh`` to ``c:\windows\sysnative\openssh``. 

You can either : 
- specify flag ``--ssh-client-folder`` with ``c:\windows\sysnative\openssh`` 
- set ``c:\windows\sysnative\openssh`` to the ``PATH`` environment variable.

This is what fixed it for us.

**Comment by jeanbaptisteng** [comment]
> The new code of extension v1.1.0 is not able to translate `C:\Windows\System32\OpenSsh` to `c:\windows\sysnative\openssh`.
> 
> You can either :
> 
> * specify flag `--ssh-client-folder` with `c:\windows\sysnative\openssh`
> * set `c:\windows\sysnative\openssh` to the `PATH` environment variable.
> 
> This is what fixed it for us.

I have tried to specify flag --ssh-client-folder with c:\windows\sysnative\openssh. It won't help the problem, and the following error message prompted

unrecognized arguments: --ssh-client-folder c:\windows\sysnative\openssh

**Comment by jeanbaptisteng** [comment]
I can confirm the ssh extension can work fine on Linux so far. (No error is observed on Linux client)

**Comment by navba-MSFT** [comment]
@jeanbaptisteng @lbergeron01 @kasperbilde Thanks for sharing an update and the workaround you followed. We have involved the Product Owners in the background and they are working on permanent fix. We will share an ETA on the fix release as soon as we have more details.

**Comment by navba-MSFT** [comment]
@jeanbaptisteng @lbergeron01 @kasperbilde sharing the PR details for the fix https://github.com/Azure/azure-cli-extensions/pull/4728. This is under review phase now.

**Comment by jeanbaptisteng** [comment]
@navba-MSFT @vthiebaut10 It is to confirm **ssh extension v1.1.1** do not have this issue. 

Thank you for solving the problem.

**Comment by navba-MSFT** [comment]
@jeanbaptisteng Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
