### ISSUE TITLE
Suggestion: Prompt for confirmation on disk delete

### ISSUE THREAD

**Issue by iainfoulds** [Azure/azure-cli#2215]
When deleting a disk with `az disk delete`, there is no prompt that you wish to continue. When deleting a resource group with `az group delete`, you are prompted or can pass `--yes` to continue without a prompt.

Deleting an NSG rule with `az nsg rule delete` also doesn't prompt for confirmation, though deleting a disk is potentially a more destructive process. There are likely other similar examples.

I'd recommend that at the least, a confirmation is added to `az disk delete`, and ideally some amount of consistency across potentially destructive commands that delete resources.

**Comment by tjprescott** [comment]
Most deletes in the CLI don't prompt. Prompting is an opt-in behavior. While you are right that deleting an NSG rule doesn't prompt... neither does deleting the entire NSG ;)

You are right though that we should seek consistency on when to use prompt. The general rule that seems to be bubbling up is that deleting things that contain multiple things (resource group, storage account, DNS zone, etc) should prompt, while deleting single items should not. Deleting a disk could be seen as a container so this would be appropriate I think.

**Comment by jtuliani** [comment]
That said, I'm personally in favour of prompting for DNS record / record set deletes. For me, it's not about whether the resource is a collection or not, it's about the potential impact of the delete and how easy it is to detect/undo.

**Comment by iainfoulds** [comment]
Thanks for the response @tjprescott . That all makes sense. 

That said, I agree with @jtuliani and what I'd originally commented in that for anything that's potentially destructive, such as deleting a disk, NSG, or DNS record, should prompt. There's a balance, I acknowledge, in allowing commands to run without requiring interaction, and wanting to protect resources from deletion. And yes, RBAC works great, but only once set up ;)

**Comment by yugangw-msft** [comment]
Since we have general prompt support now, I will fix this

**Comment by iainfoulds** [comment]
Nice! Thanks.

**Comment by AbianG** [comment]
@yugangw-msft could you specify whats "general prompt support"? Does it mean there's a flag for every `delete` command in AZ CLI to prompt for confirmation? I haven't been able to find information about it except for this old issue
