### ISSUE TITLE
afd endpoint create with origin-response-timeout-seconds fails

### ISSUE THREAD

**Issue by arunvc** [Azure/azure-cli#22159]
## Describe the bug

**Command Name**
`az afd endpoint create`

**Errors:**
```
unrecognized arguments: --origin-response-timeout-seconds 60

```

## To Reproduce:
Steps to reproduce the behavior. 
- `az afd endpoint create -g group --endpoint-name endname --profile-name profile --origin-response-timeout-seconds 60 --enabled-state Enabled`
- `az afd endpoint create -g {} --endpoint-name {} --profile-name {} --origin-response-timeout-seconds {} --enabled-state {}`

## Environment Summary
```
Linux-5.4.0-107-generic-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.10
Installer: 

azure-cli 2.35.0

Extensions:
front-door 1.0.16

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by SaurabhSharma-MSFT** [comment]
@arunvc We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by t-bzhan** [comment]
Hi @SaurabhSharma-MSFT  and @arunvc , the origin-response-timeout-seconds option is moved to profile level after GA: https://docs.microsoft.com/en-us/cli/azure/afd/profile?view=azure-cli-latest#az-afd-profile-create-optional-parameters
![image](https://user-images.githubusercontent.com/61817681/164954421-c13d8bf8-290d-4d32-947e-07c59ab20c2d.png)
