### ISSUE TITLE
Azure CLI fails to install on jammy - no package found? 

### ISSUE THREAD

**Issue by joshuafernandes** [Azure/azure-cli#22161]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When attempting to install azure cli from the instructions here: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-1-install-with-one-command
Running curl -sL https://aka.ms/InstallAzureCLIDeb | bash results in no package is found 

```
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
Get:1 http://au.archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Hit:2 http://au.archive.ubuntu.com/ubuntu jammy-updates InRelease                                            
Hit:3 https://dl.google.com/linux/chrome/deb stable InRelease                                                
Hit:4 http://packages.microsoft.com/repos/code stable InRelease                                              
Hit:5 https://packages.microsoft.com/repos/azure-cli impish InRelease                                        
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Fetched 270 kB in 1s (208 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (7.81.0-1).
gnupg is already the newest version (2.2.27-3ubuntu2).
lsb-release is already the newest version (11.1.0ubuntu4).
apt-transport-https is already the newest version (2.4.5).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
Get:1 http://au.archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Hit:2 http://au.archive.ubuntu.com/ubuntu jammy-updates InRelease                                            
Hit:3 http://packages.microsoft.com/repos/code stable InRelease                                              
Hit:4 https://dl.google.com/linux/chrome/deb stable InRelease                                                
Get:5 https://packages.microsoft.com/repos/azure-cli jammy InRelease [5,812 B]                               
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Fetched 276 kB in 1s (311 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package azure-cli
```

**To Reproduce**
1. Clean install of Ubuntu 22.04 LTS (Jammy)
2. curl -sL https://aka.ms/InstallAzureCLIDeb | bash

**Expected behavior**
There is a package available to install and we can actually use azure cli again (22.04 is an LTS OS as well so this is really not great)

**Environment summary**
Single line command as per the docs  https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-1-install-with-one-command

**Additional context**
Downgrading to `impish` in the sources finds a package but is not installable and throws the error below
```
The following packages have unmet dependencies:
 azure-cli : Depends: libssl1.1 (>= 1.1.1) but it is not installable
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by GabrielJean** [comment]
I'm facing the same issue, azure-cli package not found.

**Comment by jiasli** [comment]
See https://github.com/Azure/azure-cli/issues/21532. We will release for Ubuntu Jammy on 04/26/2022.

**Comment by joshuafernandes** [comment]
Excellent, thanks for the update @jiasli

**Comment by jiasli** [comment]
No problem!

By the way, the **unsigned** deb package is at https://azurecliprod.blob.core.windows.net/archive/20220421.27/ubuntu-jammy/azure-cli_2.36.0-1~jammy_all.deb

Before we sign it and publish it to https://packages.microsoft.com/, you may install the unsigned deb if you want.
