### ISSUE TITLE
az network local-gateway update fails when configuring local address prefixes

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#2216]
See the following errors

Operation failed with status: 'Not Found'. Details: 404 Client Error: Not Found for url: https://management.azure.com/subscriptions/d6ff83d6-713d-41f6-a025-5eb76334fda9/providers/Microsoft.Network/locations/westus/operations/f078b03b-7577-4377-aeac-4fc87a2b8fe1?api-version=2016-09-01

**Comment by tjprescott** [comment]
This has already been fixed: https://github.com/Azure/azure-cli/pull/2204
