### ISSUE TITLE
az image copy exception

### ISSUE THREAD

**Issue by MayXuQQ** [Azure/azure-cli#22166]
## Describe the bug

**Command Name**
`az snapshot create`

**Errors:**
```
(BadRequest) Changing property 'sourceUri' is not allowed for existing disk 'qe-rhel77-proxy-registry-7_os_disk_snapshot-centralus'.
Code: BadRequest
Message: Changing property 'sourceUri' is not allowed for existing disk 'qe-rhel77-proxy-registry-7_os_disk_snapshot-centralus'.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az snapshot create --resource-group {} --name {} --location {} --source {} --source-storage-account-id {} --hyper-v-generation {} --output {} --tags {}`

## Environment Summary
```
Linux-5.15.16-200.fc35.x86_64-x86_64-with-fedora-35-Thirty_Five, Fedora Linux 35 (Cloud Edition)
Python 3.6.15
Installer: RPM

azure-cli 2.35.0

Extensions:
image-copy-extension 0.2.9

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
Compute

**Comment by cxznmhdcxz** [comment]
Hi @MayXuQQ , could you provide more information to reproduce, including what type of source(blob, disk, snapshot) to create a snapshot?

**Comment by MayXuQQ** [comment]
I do **image copy** (different region) without target name, then  retry with target name ,  got the exception. after delete the snapshot in the target region, it is succeed.

**Comment by cxznmhdcxz** [comment]
Hi @grizzlytheodore , when there is a snapshot called `mysnapshot` created from a blob, if try to create a new snapshot from different blob source, but with the same name `mysnapshot`, this error will return:
`Code: BadRequest  Message: Changing property 'sourceUri' is not allowed for existing disk 'mysnapshot'`
Is this error expected?

**Comment by cxznmhdcxz** [comment]
@MayXuQQ  Could you delete a resource group called `image-copy-rg`, then add `--cleanup` in `az image copy` and try again?
```
az image copy --source-resource-group {} --source-object-name {} --target-location {} --target-resource-group {}  --cleanup
```

If still fail, please share your debug log by adding `--debug` in the command. Thanks.

**Comment by MayXuQQ** [comment]
after delete the snapshot of target-region, it is ok
