### ISSUE TITLE
Support deleteOption for Disks for VMSS with OrchestrationMode == Flexible

### ISSUE THREAD

**Issue by kimberlyyipc** [Azure/azure-cli#22182]
**Resource Provider**
CRP

**Description of Feature or Work Requested**
User experience:

If VMSS orchestrationMode = Flexible allow users to specify disk delete-Option for OS Disks and Data Disks

Add the following new parameters to CLI command **az vmss create**:

az vmss create --name
               --resource-group
               [--accelerated-networking {false, true}]
               [--accept-term]
               [--admin-password]
               [--admin-username]
               [--app-gateway]
               [--app-gateway-capacity]
               [--app-gateway-sku]
               [--app-gateway-subnet-address-prefix]
               [--asgs]
               [--assign-identity]
               [--authentication-type {all, password, ssh}]
               [--automatic-repairs-action {Reimage, Replace, Restart}]
               [--automatic-repairs-grace-period]
               [--backend-pool-name]
               [--backend-port]
               [--capacity-reservation-group]
               [--computer-name-prefix]
               [--custom-data]
               [--data-disk-caching]
               [--data-disk-encryption-sets]
               [--data-disk-iops]
               [--data-disk-mbps]
               [--data-disk-sizes-gb]
			   **[--data-disk-delete-option] /* accepted values are String Delete or Detach
			   [--os-disk-delete-option]  /* accepted values are String Delete or Detach**

New optional parameters:
data-disk-delete-option : this is a new optional parameter allowed only for VMSS using orchestrationMode= Flexible  that allows configuring whether the VMSS Flex VM data disks will be deleted or detached upon VM deletion

os-disk-delete-option : this is a new optional parameter allowed only for VMSS using orchestrationMode= Flexible that allows configuring whether the VMSS Flex VM OS Disks will be deleted or detached upon VM deletion

deleteOption allowed values: Delete or Detach (or null, this is optional parameter)
Delete: Disk will be deleted when VM is deleted
Detach: Disk will be detached when VM is deleted

**Minimum API Version Required**
2022-03-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/18433 (PR has been merged)

**Target Date**
No specific target date but ideally should be available when the CRP 2022-03-01 API is available

**Comment by yonzhan** [comment]
Compute

**Comment by kimberlyyipc** [comment]
@yonzhan Hi, could I get an update on this request? Is it approved?

**Comment by zhoxing-ms** [comment]
We haven't started developing this requirement in this sprint, so please feel free to update it~
@kimberlyyipc By the way, may I ask what is the ETA for CRP 2022-03-01 API to be available?

**Comment by kimberlyyipc** [comment]
Hi @zhoxing-ms, according to an email from @grizzlytheodore the CRP 2022-03-01 SDK should be May6. Tagging Theodore in case he has any more insights.

**Comment by zhoxing-ms** [comment]
@kimberlyyipc Hi, since our work in this sprint has been fully arranged, we don't have enough time to support more requirements. Can this feature request be postponed to the release of the next sprint (**08-02**)?

**Comment by kimberlyyipc** [comment]
@zhoxing-ms OK, but please do not delay it any further. thanks.

**Comment by zhoxing-ms** [comment]
We have a PR #23200 to support this feature, and it will be released in 08-02
