### ISSUE TITLE
az-cli > 2.34.1:  az sql db export leads to ImportExportJobError

### ISSUE THREAD

**Issue by thomastrinamix** [Azure/azure-cli#22191]
Since the upgrade 2.35.0 our command
`az sql db export -s $(DatabaseServer) -n $(DatabaseName) -g $(ResourceGroup) -p $(sql-server-admin-password) -u $(sql-administrator-login) --storage-key $sasToken --storage-key-type SharedAccessKey --storage-uri $destination`
does rais the error:

`ERROR: (ImportExportJobError) The ImportExport operation with Request Id 'b92dc2c8-e42f-414a-ac2a-1176891f8385' failed due to 'An internal error occurred. Please contact Microsoft support and reference the server name, database name, and operation ID.'.
Code: ImportExportJobError
Message: The ImportExport operation with Request Id 'b92dc2c8-e42f-414a-ac2a-1176891f8385' failed due to 'An internal error occurred. Please contact Microsoft support and reference the server name, database name, and operation ID.'.`

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
Hello @thomastrinamix 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by thomastrinamix** [comment]
we also raised a ticket #2204260050001917

**Comment by sredman** [comment]
Fixed by #22609
