### ISSUE TITLE
 az aks show OIDC url failure

### ISSUE THREAD

**Issue by BinHan0** [Azure/azure-cli#22198]
## Describe the bug

**Command Name**
`az aks show --resource-group <rg> --name <aks> --query "oidcIssuerProfile.issuerUrl" -otsv

**Errors:**
```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:

cannot import name 'edge_zone_type'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-2lthyver\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-84ckl4fg\azure\cli\core\commands\__init__.py", line 553, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-84ckl4fg\azure\cli\core\__init__.py", line 479, in load_arguments
  File "C:\Users\bihan.FAREAST\.azure\cliextensions\aks-preview\azext_aks_preview\__init__.py", line 47, in load_arguments
    from ._params import load_arguments
  File "C:\Users\bihan.FAREAST\.azure\cliextensions\aks-preview\azext_aks_preview\_params.py", line 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks show --resource-group {} --name {} --query {} -o{}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.15.1 *

Extensions:
aks-preview 0.5.41

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@BinHan0 I see that you are using an older version of `aks-preview`.  You need to have `aks-preview` extension version 0.5.50 or later to use this command. Please upgrade your extension using `az extension update --name aks-preview` and try executing the above command.
I have used the command with the latest version and it worked fine.
![image](https://user-images.githubusercontent.com/38112130/165871833-c2c2c002-8669-4ed3-a40e-d6fb38b72c3e.png)
Please refer to [OIDC Issuer (Preview)](https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#oidc-issuer-preview) for details.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@BinHan0 Please let me know if you have any questions else we will proceed with the issue closure. Thanks

**Comment by SaurabhSharma-MSFT** [comment]
@BinHan0 We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
