### ISSUE TITLE
Confidential Compute CLI Change Request - VM OS Disk / Disk Encryption Set Create

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-cli#22200]
## Is your feature request related to a problem? Please describe

No, feature request to add new parameter and add values into existing parameters for following commands to support **Confidential VM - Planned GA by end of June CY22:**

- [az disk create](https://docs.microsoft.com/en-us/cli/azure/disk?view=azure-cli-latest#az-disk-create)
- [az disk-encryption-set create](https://docs.microsoft.com/en-us/cli/azure/disk-encryption-set?view=azure-cli-latest#az-disk-encryption-set-create)

Feature is to support customers with:
- creating Disk Encryption Set which will support Confidential VM Creation using customer encryption keys.
- creating managed OS Disk for Confidential VM with flexibility to choose between Platform keys and customer-managed keys.

#### `az disk create`

Customer to use `az disk create` command with parameter **--security-type** to set Security Type. For confidential VM Additional accepted security type should be ***ConfidentialVM_DiskEncryptedWithCustomerKey, ConfidentialVM_VMGuestStateOnlyEncryptedWithPlatformKey, ConfidentialVM_DiskEncryptedWithPlatformKey***

Post change, following values will be accepted:

|SecurityType
--- |
|TrustedLaunch
|ConfidentialVM_VMGuestStateOnlyEncryptedWithPlatformKey
|ConfidentialVM_DiskEncryptedWithPlatformKey
|ConfidentialVM_DiskEncryptedWithCustomerKey

#### `az disk-encryption-set create`

Customer to use `az disk-encryption-set create` command with parameter **--encryption-type** to set Encryption type. For confidential VM, additional accepted encryption type should be ***ConfidentialVmEncryptedWithCustomerKey***

Post change, following values will be accepted:

|EncryptionType
--- |
|EncryptionAtRestWithPlatformKey
|EncryptionAtRestWithCustomerKey
|EncryptionAtRestWithPlatformAndCustomerKeys
|ConfidentialVmEncryptedWithCustomerKey

#### --secure-vm-disk-encryption-set (`az disk create`)

New Parameter **--secure-vm-disk-encryption-set** for command `az disk create`:

- Allows customer to provide ARM ID for Disk Encryption Set created with *ConfidentialVmEncryptedWithCustomerKey* encryption type. This will allow customer to use Customer Managed Key (CMK) encryption.
- Mandatory and required only when **--security-type** is set to *ConfidentialVM_DiskEncryptedWithCustomerKey*

#### Scenario 1 - Managed OS Disk Create

1. Store Disk Encryption Set ID in variable:

    `diskEncryptionSetId=$(az disk-encryption-set show -n $diskEncryptionSetName -g $rgName --query [id] -o tsv)`

2. Create Virtual Machine Disk with ***ConfidentialVM_DiskEncryptedWithCustomerKey*** Security Type

    ```azurecli
    az disk create --name $diskName -g $rgName \
        --hyper-v-generation V2 --os-type Windows \
        --security-type ConfidentialVM_DiskEncryptedWithCustomerKey \
        --secure-vm-disk-encryption-set $diskEncryptionSetId \
        --image-reference "MicrosoftWindowsServer:WindowsServer:2019-datacenter-gensecond:latest"
    ```

#### Scenario 2 - Disk Encryption Set Create

1. Create New key vault with premium SKU
    ```azurecli
    KeyVault="myKeyVault"
    az keyvault create --name $KeyVault --resource-group $rgName --location $region --sku Premium --enable-purge-protection 
    ```

2. Create RSA-HSM Key with [key release policy](https://cvmprivatepreviewsa.blob.core.windows.net/cvmpublicpreviewcontainer/skr-policy.json)

    ```azurecli
    $KeyName = <name of key>
    $KeySize = 3072
    az keyvault key create --vault-name $KeyVault --name $KeyName --ops wrapKey unwrapkey --kty RSA-HSM --size $KeySize --exportable true --policy "@.\skr-policy.json"
    ```  
3. Query Key-vault key required for Disk Encryption Set

    `keyUrl=$(az keyvault key show -n $keyName --vault-name $keyVaultName --query [key.kid] -o tsv)`

4. Create Disk Encryption Set

    ```azurecli
    az disk-encryption-set create -n $diskEncryptionSetName \
        -g $rgName -l $location \
        --key-url $keyUrl --encryption-type "ConfidentialVmEncryptedWithCustomerKey"
    ```
5. Assign Access to Disk Encryption Set

    ```azurecli
    desIdentity=$(az disk-encryption-set show -n $diskEncryptionSetName -g $rgName --query [identity.principalId] -o tsv)
    
    az keyvault set-policy -n $KeyVault \
    -g $rgName \
    --object-id $desIdentity \
    --key-permissions wrapkey unwrapkey get
    ```
## Describe alternatives you've considered

Not Applicable, new product feature request.

## Additional context

Related to #22199 

Request for Confidential VM - Planned GA by end of June CY22

- [Link to CVM Disk RP Swagger Spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2021-08-01/disk.json)
- [Link to Compute RP Swagger Spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2021-11-01/compute.json)
- [Confidential VM with Customer Managed Keys ARM JSON](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2021-11-01/examples/compute/CreateAVmWithSecurityTypeConfidentialVMWithCustomerManagedKeys.json)
- [Confidential VM with Platform Managed Keys ARM JSON](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2021-11-01/examples/compute/CreateAVmWithSecurityTypeConfidentialVM.json)
- [Confidential Compute CLI Change Request - VM / VMSS Create](https://github.com/Azure/azure-cli/issues/22199)
- [Confidential VM GA Request Powershell change on Set-AzDiskSecurityProfile cmdlet](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1138)
- [Confidential VM GA Request Powershell change on Set-AzVmSecurityProfile cmdlet](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1136)
- [Confidential VM GA Request Powershell change on Set-New-AzDiskEncryptionSetConfig cmdlet](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1140)

### Additional Checks

- User provides value for **--hyper-v-generation** as **V2** when **--security-type** parameter is used. If not, help message to be printed - ***SecurityType value* for parameter --security-type is supported with --hyper-v-generation set to v2.**, where *SecurityType value* will be replaced by value passed for parameter `--security-type`.
- When parameter `--security-type` is used, supported create options for disk are FromImage, Import, ImportSecure, UploadPreparedSecure. `Empty` is not supported.
- ARM URI of Disk Encryption Set ID provided for new parameter **--secure-vm-disk-encryption-set** should have encryption type set to **ConfidentialVmEncryptedWithCustomerKey**.

### Contacts

Role    |    Contact
-|-
Main developer contacts (emails + github aliases)    |    Abhishek Verma (AZURE) <Abhishek.Verma@microsoft.com>, Anshul Solanki <Anshul.Solanki@microsoft.com>
PM contact (email + github alias)    |    Ajay Kundnani <ajay.kundnani@microsoft.com>
Other people who should attend a design review (email)    |    Run Cai <run.cai@microsoft.com>, Deepak J V <J.Deepak@microsoft.com>

**Comment by yonzhan** [comment]
Compute

**Comment by AjKundnani** [comment]
@zhoxing-ms - Updated Disk encryption set scenario with key vault key creation commands as well.

**Comment by cxznmhdcxz** [comment]
Hi @AjKundnani , after supporting the arguments in CLI, I could create a DES with ConfidentialVmEncryptedWithCustomerKey as described in Scenario 2. Then I tried Scenario 1 with the DES just created, and returned this error:
```
{
  "error": {
    "code": "InvalidParameter",
    "message": "SecurityType 'ConfidentialVM_DiskEncryptedWithCustomerKey' is not supported by given image.",
    "target": "securityProfile.securityType"
  }
}
```
So could you please provide an image that would support ConfidentialVM_DiskEncryptedWithCustomerKey?

**Comment by AjKundnani** [comment]
@cxznmhdcxz - if you can try with image **2019-datacenter-cvm** or **2022-datacenter-cvm** under offer **windows-cvm**

**Comment by zhoxing-ms** [comment]
> Mandatory and required only when --security-type is set to ConfidentialVM_DiskEncryptedWithCustomerKey.
Allows customer to provide ARM ID for Disk Encryption Set created with ConfidentialVmEncryptedWithCustomerKey encryption type. This will allow customer to use Customer Managed Key (CMK) encryption.
ARM URI of Disk Encryption Set ID provided for new parameter --securevm-disk-encryption-set should have encryption type set to ConfidentialVmEncryptedWithCustomerKey.

@AjKundnani These sentences mean that the `--securevm-disk-encryption-set` must be passed in when parameter `--security-type` is `ConfidentialVM_DiskEncryptedWithCustomerKey`, and `--securevm-disk-encryption-set` can only be passed in when parameter `--security-type` is `ConfidentialVM_DiskEncryptedWithCustomerKey`, right?

**Comment by AjKundnani** [comment]
> > Mandatory and required only when --security-type is set to ConfidentialVM_DiskEncryptedWithCustomerKey.
> > Allows customer to provide ARM ID for Disk Encryption Set created with ConfidentialVmEncryptedWithCustomerKey encryption type. This will allow customer to use Customer Managed Key (CMK) encryption.
> > ARM URI of Disk Encryption Set ID provided for new parameter --securevm-disk-encryption-set should have encryption type set to ConfidentialVmEncryptedWithCustomerKey.
> 
> @AjKundnani These sentences mean that the `--securevm-disk-encryption-set` must be passed in when parameter `--security-type` is `ConfidentialVM_DiskEncryptedWithCustomerKey`, and `--securevm-disk-encryption-set` can only be passed in when parameter `--security-type` is `ConfidentialVM_DiskEncryptedWithCustomerKey`, right?

@zhoxing-ms - Right, `--sercurevm-disk-encryption-set` only required when `--security-type` is set to **ConfidentialVM_DiskEncryptedWithCustomerKey** else its not needed.

**Comment by AjKundnani** [comment]
Updated request to reflect `--secure-vm-disk-encryption-set` as parameter name.

**Comment by zhoxing-ms** [comment]
> --security-type should be ConfidentialVM_* ONLY if --hyper-v-generation is set to V2

@AjKundnani When `--hyper-v-generation` is `V2`, `--security-type` can only be `ConfidentialVM_*` or other values can also be supported?

**Comment by zhoxing-ms** [comment]
＞　--hyper-v-generation is set to V2 when --security-type parameter is used.
＞　any value of --security-type parameter needs --hyper-v-generation set to V2

@AjKundnani Do you mean that when the user passes in the `--security-type` parameter, CLI needs to set `--hyper-v-generation` to `V2`?

I think a better solution may be to verify that users must input `--hyper-v-generation` as `V2` when using `--security-type`.
Otherwise, users may be confused because the `--hyper-v-generation` parameters they passed in will be modified by CLI without their knowledge.

**In addition, please note that since the `--hyper-v-generation` and `--security-type` parameters are pre-existing parameters, no matter which solution we use above, it will lead to breaking change!**

**Comment by zhoxing-ms** [comment]
@AjKundnani In current official CLI, if users pass in the `--security-type` parameter but do not pass in `--hyper-v-generation` parameter or specify the `--hyper-v-generation` parameter as `V1`, will the service raise an error at present? 
If so, there is no breaking change. Otherwise, it will block this usage so as to cause breaking change

**Comment by AjKundnani** [comment]
> @AjKundnani In current official CLI, if users pass in the `--security-type` parameter but do not pass in `--hyper-v-generation` parameter or specify the `--hyper-v-generation` parameter as `V1`, will the REST service raise an error at present? If so, there is no breaking change. Otherwise, it will block this usage so as to cause breaking change

@zhoxing-ms : Below is the current behavior for `--security-type` **TrustedLaunch**, if we can retain same behavior for new values please:

1. It checks for `CreateOption` if image reference is not passed, Error *(BadRequest) Security Type 'TrustedLaunch' is not supported for CreateOption 'Empty'. Supported create options are FromImage, Import, ImportSecure, UploadPreparedSecure.*
2. After adding image reference, it checks for size, if less than 128GB, it throws error *(ResizeDiskError) The disk/snapshot resource with id https://md-txp1chwkmhw1.z20.blob.storage.azure.net/ghgfvpxvrqx4/abcd cannot be resized down. Reducing disk/snapshot size is not supported in Azure to prevent data loss. If you do need to reduce the size of the disk, please create new snapshot/disks with the appropriate size. More information is available at https://aka.ms/AzureDisksFAQ.*
3. After passing image reference and size 128GB, without specifying parameter `--hyper-v-generation`, the disk is created with `--hyper-v-generation` set to **V2**
4. Adding parameter `--hyper-v-generation` with value **V2**, same result as step 3 above.
5. Adding parameter `--hyper-v-generation` with value **V1**, it creates the disk with Hyper-V generation v1, this shouldnt occur but to avoid breaking change, please do not add this check at present, if we can add a help message stating **<Security Type value> is supported with Hyper-V Generation V2.**, if that will be ok?

**Comment by zhoxing-ms** [comment]
@AjKundnani Out of curiosity, I would like to ask why we need to limit the parameter `--hyper-v-generation` to `V2` even the `--hyper-v-generation V1` and `--security-type` can be used at the same time to create a disk successfully?

**Comment by zhoxing-ms** [comment]
> - In case user does not specifies --hyper-v-generation parameter, as it is auto-setting itself to V2 in current release, we can skip the warning log.

@AjKundnani Please note that the default value of the `--hyper-v-generation` parameter is set to `V1` in the CLI.  [code link](https://github.com/Azure/azure-cli/blob/16026226fb2e9746f65d53afcac4bf708bbd279f/src/azure-cli/azure/cli/command_modules/vm/_params.py#L96-L99
) 
Are you sure that the `V2` disk will be created if users do not specify `--hyper-v-generation parameter`? If so, could you please you provide me with the debug log?

> - In case user specifies value V1 for --hyper-v-generation parameter, if CLI can print warning log, that'll be good, prompt should be non-interactive.

Yes, the warning log is non-interactive and will not block users' automation scenarios.

> - Yes, will submit new request to add verification in sprint close to Ignite event.

OK, thanks much for your active help!
