### ISSUE TITLE
az storage entity does not set Boolean type data properly

### ISSUE THREAD

**Issue by jsteenbekkers** [Azure/azure-cli#22209]
## Describe the bug
The "storage entity insert" command does not correctly set the boolean type in v2.36.0 when the type is specified. This was working correctly in v2.35.

**Command Name**
```az storage entity insert ... --entity Active=true Active@odata.type="Edm.Boolean"```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a storage table
- Use ```az storage entity insert``` command to insert data
- Specify one of the value as boolean: ```--entity Active=true Active@odata.type="Edm.Boolean"```

## Expected Behavior
The value should be stored in the table as Edm.Boolean, and a query should return the data as a boolean value.

This was working in previous versions. Compare with how it used to work in 2.35:
```
PS> az storage entity insert --table-name $tableName --if-exists merge --entity PartitionKey="$partitionKey" RowKey="$rowKey" Active=true Active@odata.type="Edm.Boolean"
{
  "date": "2022-04-27T13:37:22+00:00",
  "etag": "W/\"datetime'2022-04-27T13%3A37%3A22.8457701Z'\"",
  "version": "2019-02-02"
}
PS> az storage entity query --table-name $tableName --filter "PartitionKey eq '$partitionKey' and RowKey eq '$rowKey'" --select Active
{
  "items": [
    {
      "Active": true,
      "Timestamp": null,
      "etag": "W/\"datetime'2022-04-27T13%3A37%3A22.8457701Z'\""
    }
  ],
  "nextMarker": {}
}
```

Behavior in 2.36:
```
PS> az storage entity insert --table-name $tableName --if-exists merge --entity PartitionKey="$partitionKey" RowKey="$rowKey" Active=true Active@odata.type="Edm.Boolean"
{
  "date": "2022-04-27T13:43:56+00:00",
  "etag": "W/\"datetime'2022-04-27T13%3A43%3A56.9536465Z'\"",
  "version": "2019-02-02"
}
PS> az storage entity query --table-name $tableName --filter "PartitionKey eq '$partitionKey' and RowKey eq '$rowKey'" --select Active
{
  "items": [
    {
      "Active": "true",
      "Timestamp": null,
      "etag": "W/\"datetime'2022-04-27T13%3A43%3A56.9536465Z'\""
    }
  ],
  "nextMarker": {}
}
```

Viewed in Azure Storage Explorer:
2.35
![image](https://user-images.githubusercontent.com/83605442/165532561-7a97e3df-8a8e-42fb-8eff-ee00ed78b313.png)

2.36
![image](https://user-images.githubusercontent.com/83605442/165533305-cdfc9fde-2ca5-4543-8d09-127c573540b4.png)

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0

Extensions:
application-insights 0.1.16
azure-devops 0.25.0
datafactory 0.5.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by jsteenbekkers** [comment]
This is a breaking change for me because I am relying on the query values to be returned with the expected type.

Looks like this change in behavior was introduced with changes related to https://github.com/Azure/azure-cli/issues/22018

**Comment by yonzhan** [comment]
storage

**Comment by jsteenbekkers** [comment]
Can anyone comment on the availability of a workaround, or a timeline for a fix?

**Comment by steverash** [comment]
For a workaround - I ended up replacing with a call directly to the storage rest service.

**Comment by evelyn-ys** [comment]
The fix will be released on 5/24
