### ISSUE TITLE
when to use --add vs --set should be clearer + examples in help text

### ISSUE THREAD

**Issue by lebaro-msft** [Azure/azure-cli#22219]
**Is your feature request related to a problem? Please describe.**

Our team was frustrated trying to understand when to use --add and when to use --set, and what the correct syntax was. The error messages were also not helpful when trying to parse what was wrong.
From Chase Wilson, we got this explanation: Ok, so add is to add a new property or object. meaning if it already exists, that's not what to use and should use set as it states in the help. When using the update, the description property is at the root of the object so you can just use the following syntax to update this. az ml dataset update -n testdataset -w myworkspace -v 1 -set description="Test an update"

**Describe the solution you'd like**

2 things would be great:
1. The error message tries to relate directly to the command attempted - if it should have been --set instead of --add, something to indicate that (I realize this may be technically challenging, so more hoping for any amount of improvement to help user unblock). Even just examples of correct usage passed back in the error message would be great.
2. The --set and --add help descriptions to better describe when to use which, what it looks like if the property is at the root of the object, and have an example of correct usage with a real example.

**Describe alternatives you've considered**

![image](https://user-images.githubusercontent.com/99359352/165817374-e953d911-90fb-476f-bebf-d201a9513247.png)
To be fair, once I had the explanation from Chase, the help text made sense fine. But for a user that isn't educated, the help text could be more descriptive regarding "root of object" vs "child property" and give more realistic examples. For example, if you try to modify tags, I think you would need to do --set tags.tagName = "tagValue", but a user may think that can "add a new tag" by doing --add tags.tagName = "tagValue" since they are "adding a new tag" but tags is already a property. This is where I see the confusion

**Additional context**

This is a full screenshot of the data example we were looking at:
![image](https://user-images.githubusercontent.com/99359352/165818323-7d3a5108-a948-45c2-b2a7-7256b5d44579.png)

this was an unsuccessful attempt to set description: 
![image](https://user-images.githubusercontent.com/99359352/165818501-0ed6a1ee-7e1e-47fb-afeb-eb120ac9742f.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@lebaro-msft @yonzhan This is created by internal Microsoft personal, i think we do not need CXP Attension label?

**Comment by lebaro-msft** [comment]
Is there any update here? I can connect internally to someone as well?

**Comment by luigiw** [comment]
@lebaro-msft please connect with me if this issue is still relevant.
