### ISSUE TITLE
Azure CLI failing to finish/return from az vm start ... command 

### ISSUE THREAD

**Issue by AdamRiddick** [Azure/azure-cli#22211]
**Describe the bug**
We have an Azure DevOps Release Pipeline with the Azure CLI task where we run the following command:

`az vm start --ids $(az vm list --resource-group myResourceGroup --query "[].id" -o tsv)`

Today we experienced an issue from 2pm-4pm BST whereby the command did not return any output, despite the VMs being started successfully. I cancelled the task twice after running for over 50 minutes, and then ran it manually from my local machine and got the same result. 

Trying the pipeline again at 4.30pm BST ran successfully.

When running locally, I could see that the operations checks always returned `InProgress`, even after the machine is showing as running within the portal.

**To Reproduce**

- az vm start --ids $(az vm list --resource-group myResourceGroup --query "[].id" -o tsv)

Note: In my case, `az vm list --resource-group myResourceGroup --query "[].id" -o tsv` returns 7 VMs

**Expected behavior**
The command completes after the VMs are started, allowing either the Azure CLI release pipeline task to continue or the CLI command prompt to return to user.

**Environment summary**
**Azure DevOps**
windows-2022 VM image

**Local**
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0
```

**Additional context**

My issues appears to replicate this one: https://github.com/Azure/azure-cli/issues/14841

**Comment by yonzhan** [comment]
Compute

**Comment by AkechiShiro** [comment]
@yonzhan @cxznmhdcxz @zhoxing-ms  I've ran into a similar issue, please let us know, when will this be fixed, what kind of information Microsoft needs to fix this.

I will definitely open a support ticket as well as follow news here.

We can't keep paying for something that barely works at such a price, this was already reported (in 2020 for others extensions that were used) by others users that these issues are happening, a proper test suite should be created by Azure's team on their CLI, but I understand Microsoft is for profit so it's not in its best interest to squash all bugs, just the one, their users notice by using their tools.

You guys can't even test `az vm start` for all your extensions ? If it's really just that, this is sad, I'll need to follow this up to my hierarchy so we plan to move out of Azure.

**Comment by AkechiShiro** [comment]
The API seems to be stuck to InProgress without ever ending from the management.azure.com API endpoint

**Comment by AkechiShiro** [comment]
I'd like detailed docs on the extensions and what could be their consequence on the Azure CLI's functionality.

**Comment by AkechiShiro** [comment]
Can I get a roadmap/a deadline on this fix, I need this fixed by Monday in order to do my work.
What is the SLA on this issue, I have asked a support ticket to be created on my work license, because this is unacceptable.

**Comment by TravisCragg-MSFT** [comment]
@AkechiShiro I cannot give an ETA at this time. 

Nothing in the original issue pertains to extensions, can you clarify what extensions are part of this?

The status will delay until all extensions have returned their status to Azure.

**Comment by AkechiShiro** [comment]
I don't understand like what do you mean by we need to wait for extensions status ?

**Comment by AkechiShiro** [comment]
> @AkechiShiro I cannot give an ETA at this time.
> 
> Nothing in the original issue pertains to extensions, can you clarify what extensions are part of this?

Well that's what was mentioned in the original issue, that was deemed fixed by Microsoft, hence why I believe this is due to extensions. 

But I have no access to Azure's technology stack and cannot debug that far, so sorry for not being able to peer into it much, best would be to give a proper ETA for this, especially for big customers...

**Comment by TravisCragg-MSFT** [comment]
@AkechiShiro Your best bet as a starting point is to create a support request. 

There are several things that can delay the return of a VM start, ranging from issues with the platform, to an extension taking a long time to complete. Troubleshooting with a support engineer can help identify these issues and figure out if anything from Azure's stack or other configurations are causing this issue. 

If this is a result in the bug in Azure or with the CLI, we will identify it from there and move to resolve. 

@AdamRiddick are you still experiencing this issue?

**Comment by AkechiShiro** [comment]
@TravisCragg-MSFT I think I found the issue, the Debian 11, I'm using, has the OmsAgent that is failing for some reason, to be deployed, [it seems Debian 11 is not supported according to this issue, so I'll probably be forking the OmsAgent and maintaining one that works](https://github.com/microsoft/OMS-Agent-for-Linux/issues/1515), that's truly sad tho if support isn't official from Microsoft for Debian 11. But it is, what it is.

If that starts taking too much time, I'll remove the OmsAgent from the extension.

An image on Azure running Debian 12, with no extension, starts and stops properly.

**Comment by TravisCragg-MSFT** [comment]
@AkechiShiro Thank you for the follow ups. I am following up internally with our extensions & Linux teams to make sure they are aware of this issue.

**Comment by AkechiShiro** [comment]
@TravisCragg-MSFT Could you ask around internally if the new Agent Monitor for Azure (AMA) : https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration 
Is that one compatible with Debian 11/12 ?

**Comment by TravisCragg-MSFT** [comment]
@AkechiShiro From https://learn.microsoft.com/en-us/azure/azure-monitor/agents/agents-overview#linux Azure Monitor Agent does support it. I am still waiting for a response from the PM for AMA / OMS for additional information.

**Comment by AkechiShiro** [comment]
Thanks for the helpful help @TravisCragg-MSFT, is there any way to automatically configure VMs to use AMA agent instead of OMS Agent, is that setting enforced at the subscription level ? (Basically, when I create a VM, it gets automatically provisioned with the OMS Agent and not the AMA Agent), I'd like to have as default the AMA Agent.

**Comment by TravisCragg-MSFT** [comment]
@AkechiShiro You can use Azure Policy to do that, but it might prevent updates on your VMs with OMS Agent. 

I do not know of a way to automatically migrate existing VMs, your best bet is to write a script (I would use PS, but CLI should work just fine) to get the VM, update the extensions to not have OMS and add AMA agent, then make an update call to update that status.

**Comment by AkechiShiro** [comment]
@TravisCragg-MSFT you mean to make a script using Azure CLI to update the extension of prexisting VMs ?

To clarify a few points : 
1. Update the VMs to remove the OMS extension (if it is enforced/preinstalled on any VM by some Azure Policy currently, will removing the extension still work fine ?)  using `az vm extension delete` 
2. then `az vm extension set` to set AMA agent on VMs ?
3. I don't understand when you say make an update call to update that status ? Wdym exactly ? Is it an operation to be done on the Azure Portal or using the CLI ? If using the CLI, could you link the documentation of that update command please ?
4. Why using PS would be better than the CLI ? (is it more robust/reliable than using the CLI, some features of the CLI are still marked as experimental, not sure if operations on VMs extensions are tho)

Just a question, quickly like that, if I deploy a Linux VM and there are extensions that are preinstalled/deployed (during VM creation, I do not select any extensions to install), after the first boot/reboot, there are still extensions that do show up, does that implies there is an ongoing Azure Policy enforcing the installation of those extension ?

**Comment by TravisCragg-MSFT** [comment]
My apologies, I missed this past response. 

This issue has significantly derailed from its original intent, and I am closing it. 

To answer your questions.: When you update a VM or anything related (including extensions) it makes an 'update' call to the VM, and we try to update the VM based upon what you specified in the update. In your case, the update is to remove / add / edit extensions, specifically the AMA / OMS agents. Any method you use is fine, with PS / CLI / Portal all going to the same place (our REST API).

For extensions that appear without your explicit permission, it could be something that the portal adds, or a policy. If you are using the CLI, it will only be policy that adds it.
