### ISSUE TITLE
Update Example

### ISSUE THREAD

**Issue by AdeptusNil** [Azure/azure-cli#22210]
When setting subscription through az acocunt the Name no longer exists. The example should reflect the guidance provided when an error is received using -name 

_|| 
z : ERROR: the following arguments are required: --subscription/-s
At C:\ps\scripts\Delete-funappARrules.ps1:9 char:1
+ az account set --name $sub
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: the foll...subscription/-s:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
TRY THIS:
az account set --subscription mysubscription
Set a subscription to be the current active subscription. (autogenerated)
az account list
Get a list of subscriptions for the logged in account. (autogenerated)
az account show
Get the details of a subscription. (autogenerated)
https://docs.microsoft.com/en-US/cli/azure/account#az_account_set
Read more about the command in reference docs
az : ERROR: (ResourceGroupNotFound) Resource group 'sen-intpriv-dev-rg-cloudarchtesting-99' could not be found.
At C:\ps\scripts\Delete-funappARrules.ps1:10 char:1
+ az functionapp config access-restriction remove -g $rg -n $wa --rule- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: (Resourc...d not be found.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
||_ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abfaa54-0895-29f7-f3bb-ff604912b2ac
* Version Independent ID: d1ff3478-8a86-59e4-62ef-449900132a67
* Content: [az account](https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/account.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/account.yml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@AdeptusNil We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by SaurabhSharma-MSFT** [comment]
@AdeptusNil Can you please clarify your ask.  I could see the cmdlet works with ` --name` parameter and I do not see any errors using cmdlet like `az account set --name {Subsription Name}`.

**Comment by AdeptusNil** [comment]
If you cannot see any issues, please disregard and close. Errors were encountered from my end that could not be resolved without using –subscription, which is what I will continue to use.

Thank You,

Carl Werner
Solution Architect
Sentara Healthcare
E: ***@***.******@***.***>
[5DD225B4]

**Comment by SaurabhSharma-MSFT** [comment]
@AdeptusNil Sure, thanks for the confirmation.  We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
