### ISSUE TITLE
Cannot delete tags via az tag delete

### ISSUE THREAD

**Issue by yargolan** [Azure/azure-cli#22216]
[Enter feedback here]
I am trying to remove all tags from a resource (disk for the matter) by running:
`az tag delete --yes --resource-id /subscriptions/...`

The command ends with no errors, but when verifying it by running:
`az tag list --resource-id /subscriptions/...`
I see that no tag actually removed.

{
  "id": "/subscriptions/...",
  "name": "default",
  "properties": {
    "tags": {
      "auto_fix": "yes",
      "contact_dl": "me@ISP.com",
      "env": "dev"
    }
  },
  "resourceGroup": "myrg",
  "type": "Microsoft.Resources/tags"
}

Any idea how to overcome it and manage to remove all the tags to that resource, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9984dc8-c276-354c-6c40-db77fad8e7cc
* Version Independent ID: f785cf84-06f2-946e-c8c6-c2a227394335
* Content: [az tag](https://docs.microsoft.com/en-us/cli/azure/tag?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/tag.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/tag.yml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ARM

**Comment by RakeshMohanMSFT** [comment]
@yargolan Thank you for reaching out to us. We are looking into it.

**Comment by yargolan** [comment]
I will test your recommendations and report.

**Comment by yargolan** [comment]
Well. since the tag contains a white space, I cannot delete it from CLI.
Will do it manually from the portal.

You may close the ticket.
Thanks.

**Comment by buggsdummy** [comment]
Regex would be nice
