### ISSUE TITLE
Add docs on how to install `az acr manifest` commands from non-interactive prompt

### ISSUE THREAD

**Issue by justinmchase** [Azure/azure-cli#22226]
Can you please show which pip module is needed to get this installed? I have to run this on my CI and I can't figure out how to install the extension that enables this from a non-interactive terminal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910dd2c9-dac2-4464-6e7e-60115fc5e15f
* Version Independent ID: 629e20da-ae9a-6a7f-d0a4-ea6a86a0aa45
* Content: [az acr manifest](https://docs.microsoft.com/en-us/cli/azure/acr/manifest?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/acr/manifest.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/acr/manifest.yml)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@justinmchase Thank you for reaching out, we are looking into it.

**Comment by justinmchase** [comment]
Yes thank you that is exactly what I was wondering.

**Comment by RakeshMohanMSFT** [comment]
You're Welcome @justinmchase.
