### ISSUE TITLE
List Community Galleries from ARG 

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#22222]
**Resource Provider**

Azure.Compute

**Description of Feature or Work Requested**

In the email thread "Azure CLI tools reaching ARG", we mentioned that we want to support  List Community Galleries. The catch is that  we do not support list community galleries call from SIG backend, currently users are using it from ARG portal to list all community galleries. We hope that it can be done by using a sig command to call ARG SDK to fetch community gallery resources.

**Minimum API Version Required**
2021-07-01

**Swagger Link**
This is related to ARG swagger which SIG team does not own.

**Target Date**
06/30, this is Community Gallery GA date.

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@kangsun-ctrl May I ask what parameters other than the `--location` parameter need to be supported by the `az sig list-community` command?

**Comment by kangsun-ctrl** [comment]
> @kangsun-ctrl May I ask what parameters other than the `--location` and `--skip-token` parameters need to be supported by the `az sig list-community` command?

@zhoxing-ms  The '--location' support is needed to be consistent with shared gallery. For '--skip-token', it depends on the ARG rest api/sdk requirement, they should support paging in some way, and as long as we provide user a way to go to the next page, it is good! thanks!

**Comment by kangsun-ctrl** [comment]
> @kangsun-ctrl Since the data structure returned by ARG REST is different from the data structure from `az sig list-shared`, do we need to ensure that the return structure is consistent to ensure the consistency of the experience, and to avoid possible breaking changes when migrating from ARG REST to CRP REST in the future, right?

Hey @zhoxing-ms, if you have that extra time, it would be great to convert the data structure. But SIG team will not migrate List call from ARG REST to SIG REST.
