### ISSUE TITLE
Enable Direct Sharing/Community Gallery conversion

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#22223]
**Resource Provider**

Azure.Compute

**Description of Feature or Work Requested**

Previously we disable user to update gallery from community/groups to private before they share to public/others, for GA, we plan to support both directions. We will support update gallery from private to community/groups and from community/groups to private.

This need to be released after service end is rolled out.

**Minimum API Version Required**
2021-07-01

**Swagger Link**
https://github.com/kangsun-ctrl/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2021-10-01/gallery.json

**Target Date**
06/30

**Comment by yanzhudd** [comment]
After communicating with @kangsun-ctrl, this issue will implement updating gallery from community to private and from private to community, and the conversion between private and groups is not included. The related commands are as follows:

#### Update gallery from private to community
Related commands: 
`az sig update -g myResourceGroup --gallery-name myGalleryName --permissions Community --publisher-uri myPublisherUri --publisher-email myPublisherEmail --eula myEula --public-name-prefix myPublicNamePrefix`

Note: Add 4 parameters for community, which previously only applied to the `az sig create` command: `--publisher-uri`, `--publisher-email`, `--eula`, `--public-name-prefix`

#### Update gallery from community to private
Related commands:
`az sig share reset --gallery-name myGalleryName -g myResourceGroup`
