### ISSUE TITLE
AttributeError: 'RoleAssignmentsOperations' object has no attribute 'config' with az ad sp create-for-rbac

### ISSUE THREAD

**Issue by yrro** [Azure/azure-cli#22231]
## Describe the bug

**Command Name**
`az ad sp create-for-rbac`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'RoleAssignmentsOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/commands.py", line 68, in graph_err_handler
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 1474, in create_service_principal_for_rbac
    _create_role_assignment(cmd.cli_ctx, role, sp_oid, None, scope, resolve_assignee=False,
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/role/custom.py", line 183, in _create_role_assignment
    assignments_client.config.subscription_id)
AttributeError: 'RoleAssignmentsOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az ad sp create-for-rbac --role Contributor --name name-of-sp --scopes 425da26a-c7a2-11ec-b990-b3910ed1cd8c`

## Expected Behavior

No error

## Environment Summary
```
Linux-5.16.0-1-amd64-x86_64-with-glibc2.33, Debian GNU/Linux 11 (bullseye)
Python 3.10.4
Installer: DEB

azure-cli 2.36.0

Extensions:
azure-devops 0.24.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 21.0.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by serprex** [comment]
I'm seeing this with `az aks create` when it's trying to update permissions on ACR. Using Debian bullseye

```
> az version
{
  "azure-cli": "2.36.0",
  "azure-cli-core": "2.36.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.66",
    "azure-devops": "0.23.0"
  }
}
```

**Comment by jiasli** [comment]
Judging from the installation location `dist-packages`, this is not the official Azure CLI packaged. See https://github.com/Azure/azure-cli/issues/19640.

**Comment by yrro** [comment]
Thanks. In case anyone else has this problem, the way to ensure that Microsoft's `azure-cli` packages take precedence against Debian's is:

```
$ cat /etc/apt/preferences.d/azure-cli.pref 
Package: *
Pin: Release o=azure-cli bullseye
Pin-Priority: 600
```

We can now ask apt which version of the package is installed & why:

```
$ apt-cache policy azure-cli
azure-cli:
  Installed: 2.36.0-1
  Candidate: 2.36.0-1
  Version table:
 *** 2.36.0-1 550
        550 http://deb.debian.org/debian bookworm/main amd64 Packages
        530 http://deb.debian.org/debian sid/main amd64 Packages
  2.36.0-1~bullseye 600
        600 https://packages.microsoft.com/repos/azure-cli bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
     2.35.0-1~bullseye 600
        600 https://packages.microsoft.com/repos/azure-cli bullseye/main amd64 Packages
[...]
     2.18.0-2 570
        570 http://deb.debian.org/debian bullseye/main amd64 Packages
```

Note that apt will now prefer to install from the Microsoft repository if installing `azure-cli` on a system where it's not already installed. But since the pin priority is 600, it won't prefer to downgrade the package. We can manually downgrade the package with `apt install azure-cli=2.36.0-1~bullseye` and from then on, apt will not upgrade it to the version in bookwork/sid.

**Comment by glaubitz** [comment]
> Judging from the installation location `dist-packages`, this is not the official Azure CLI packaged. You are probably installing https://packages.debian.org/sid/azure-cli on Debian sid. See #19640.

That doesn't mean the bug shouldn't be fixed though.

This issue is a typical example of the Azure SDK and the CLI API deviating from each other when one of the Azure SDK component packages have been updated.

I know that the Azure CLI PyPi package uses version pinning for the dependencies to address these issues.

However, from the distributions' point of view it would be preferable that the CLI works with the latest stable versions of all SDK components.
