### ISSUE TITLE
Filter for Az storage entity query has no explanation for what it expects in the doc

### ISSUE THREAD

**Issue by erose96** [Azure/azure-cli#22234]
Doc says:
```
--filter

Specify a filter to return certain entities.
```
But gives no explanation of what filter syntax it's looking for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a4d128f-a98f-d07b-0183-90ca79cc5fdc
* Version Independent ID: 83084fff-ea1b-a9e7-b7a9-40023de43542
* Content: [az storage entity](https://docs.microsoft.com/en-us/cli/azure/storage/entity?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/entity.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/entity.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by erose96** [comment]
Looked at the REST documentation and I think the information from "Supported Query Options" to "Query String Encoding" in "Querying tables and entities" is relevant: https://docs.microsoft.com/en-us/rest/api/storageservices/querying-tables-and-entities

**Comment by RakeshMohanMSFT** [comment]
Closing this thread.
