### ISSUE TITLE
Bug Report for "--if-exists" flag in "az storage entity insert"

### ISSUE THREAD

**Issue by ClassicalHang** [Azure/azure-cli#22236]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

The flag "--if-exist false" doesn’t work in the latest cli version  2.36.0
**To Reproduce**

**Expected behavior**

Run following cli twice and the second call will update the entity instead of failing, which is unexpected. This flag works normally in version 2.32.0.

cli: az storage entity insert --connection-string "yourconnectionstring" --entity PartitionKey=AAA1 RowKey=BBB1 Content=ASDF3 --if-exists fail --table-name tablename

**Environment summary**

![image](https://user-images.githubusercontent.com/37521320/166081748-3fe7981d-fcab-47a9-939e-65852bacecc4.png)

**Additional context**

**Comment by yonzhan** [comment]
storage
