### ISSUE TITLE
Error in --select documentation

### ISSUE THREAD

**Issue by RDavis3000** [Azure/azure-cli#22249]
Document reads:

--select
Space-separated list of properties to return for each entity.

This is incorrect, list need to be comma separated.

Attempting to use space separated throws an error:

Term 'PartitionKey Row Active' is not valid in a $select or $expand expression.
RequestId:938109ca-b002-0014-5d9f-5e1748000000
Time:2022-05-03T03:37:20.7960453Z
ErrorCode:InvalidInput

az --version
azure-cli                         2.36.0

core                              2.36.0
telemetry                          1.0.6

Extensions:
azure-devops                      0.25.0

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a4d128f-a98f-d07b-0183-90ca79cc5fdc
* Version Independent ID: 83084fff-ea1b-a9e7-b7a9-40023de43542
* Content: [az storage entity](https://docs.microsoft.com/en-us/cli/azure/storage/entity?view=azure-cli-latest#az-storage-entity-show)
* Content Source: [latest/docs-ref-autogen/storage/entity.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/entity.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by jonie001** [comment]
Hi, @RDavis3000
When I try to use space separation, no error is raised. Can you provide more information about the command？
![image](https://user-images.githubusercontent.com/99947323/167529018-74eec8bc-1ea3-4dde-9349-f4bd7c27f073.png)

**Comment by RDavis3000** [comment]
> Hi, @RDavis3000 When I try to use space separation, no error is raised. Can you provide more information about the command？ ![image](https://user-images.githubusercontent.com/99947323/167529018-74eec8bc-1ea3-4dde-9349-f4bd7c27f073.png)

Yep you are correct, I must have been doing something else wrong!
Please close.
