### ISSUE TITLE
`az iot dps linked-hub create` hub and DPS on different subscriptions broken!?

### ISSUE THREAD

**Issue by DanoThom** [Azure/azure-cli#22257]
When running `az iot dps linked-hub create` from the az CLI it would appear that we are unable to specify linking to a hub in a different subscription from the DPS.

When running under the context being set to the subscription where the DPS exists, and despite passing a valid IoTHub connectionstring param to the command, it still responds with _"No IoT Hub found with name 'iot-hub-foo' in current subscription."_.

```
az iot dps linked-hub create --dps-name $IoTDPSName -g $ResourceGroupIoTDPS --connection-string $IoTHubCN
```

It's worth noting that the command obviously works when both the DPS and the IotHub exist in the same Azure Subscription. Additionally, I've also ensured that I'm owner of the resource in case it was possibly related to [this issue](https://github.com/Azure/azure-cli/issues/22038) for a related command.

Can anyone from the Azure team please confirm that my observations above are correct and we're currently unable to link an IoTHub to a DPS in a different Subscription?

**Comment by SaurabhSharma-MSFT** [comment]
@DanoThom We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by vilit1** [comment]
Hi @SaurabhSharma-MSFT - you need to specify the location for the linked hub create. If not, the command will try to look up the hub location within the current subscription. I will change the error to be more specific.
