### ISSUE TITLE
Missing command for updating CDN endpoint rule

### ISSUE THREAD

**Issue by remimarek** [Azure/azure-cli#22260]
Azure Portal UI can update an engine rule but Azure CLI can't.
It would be extremely helpful to be able to update an Azure CDN endpoint rule directly in one command using Azure CLI to avoid downtime.

Right now, we have to deal with temporary rules creation/deletion to avoid downtime when we just want to update an existing rule.

Problem: We are using a rule engine to redirect user to specific javascript bundle file from short URL.
If to update this rule we have to remove and re-create it, it might have a downtime where user will not be redirected to anything since our rule is missing.

Please let me know if you need more details.

Thank you :) !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fef54fc4-b4a8-d366-40de-a0ae2586961d
* Version Independent ID: 1231852d-d3b4-9bcf-e9d4-ba12cffb7603
* Content: [az cdn endpoint rule](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint/rule?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/cdn/endpoint/rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/cdn/endpoint/rule.yml)
* Service: **azure-cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@remimarek Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@remimarek The portal uses this [Rules-update](https://docs.microsoft.com/en-us/rest/api/frontdoor/azurefrontdoorstandardpremium/rules/update) to update the rules. You can use the `az rest` to achieve the same for now to unblock yourself. In the meantime let me raise a request product team to include az command to edit rules.
```
az rest --method PATCH \
--uri '' \
--body ''
```

**Comment by RakeshMohanMSFT** [comment]
@remimarek are you using classic/legacy CDN?

**Comment by remimarek** [comment]
Thanks @RakeshMohanMSFT , I'm using Microsoft CDN (classic) indeed. Will have a try with this REST API thanks a lot :)

**Comment by RakeshMohanMSFT** [comment]
@remimarek You're Welcome, Do let me know if you need any assistance.

**Comment by remimarek** [comment]
Actually it seems this API will update all the rules within this CDN endpoint. It's more complicated than I expected to handle this case for me, as I only want to update a single rule within this endpoint without touching the other ones.

Do you know if there is a way for me to only target a specific rule update without having to load all rules beforehand and do the merge myself?

**Comment by RakeshMohanMSFT** [comment]
@remimarek Unfortunately because of the order property, the API expects all the rules to be mentioned while updating. :( But the portals network tab can give you the entire body required you can just copy from there and edit what is required, i know its a ugly solution but only easy option available.

**Comment by remimarek** [comment]
Alright @RakeshMohanMSFT, I think it would be really great to have these two new commands:
1. Updating a single engine rule from its name
2. Getting a single engine rule from its name

**Comment by RakeshMohanMSFT** [comment]
@remimarek Sure, will update the engineering team. For now I will close this issue.
