### ISSUE TITLE
Build RPM for Fedora

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#22278]
**Is your feature request related to a problem? Please describe.**

Currently RPMs are built with CentOS 7 and Red Hat UBI 8:

https://github.com/Azure/azure-cli/blob/1d065f0cb183ab32fef32c7eeb27882ce03dfaa0/azure-pipelines.yml#L719-L769

These RPMs depend on Python 3.6 which is deprecated and fail on the latest Fedora 35 (https://github.com/Azure/azure-cli/issues/22235) which doesn't have Python 3.6 by default.

**Describe the solution you'd like**

We should build RPM for Fedora. Actually we do have a dockerfile for Fedora - https://github.com/Azure/azure-cli/blob/dev/scripts/release/rpm/fedora.dockerfile, but this dockerfile has not been maintained for a long time.

**Comment by yonzhan** [comment]
Fedora

**Comment by jiasli** [comment]
According to https://docs.fedoraproject.org/en-US/releases/eol/, Fedora Linux 34 reached EOL on 2022-06-07. We should only build RPM for 35 and 36.
