### ISSUE TITLE
Application Gateway - Error creating rule: Either all or no rule should have the priority specified

### ISSUE THREAD

**Issue by marlowp** [Azure/azure-cli#22279]
**Related command**
`az network application-gateway rule create`

**Describe the bug**
Attempting to create a new rule produces the following error:

`ERROR: (ApplicationGatewayRequestRoutingRulePartialPriorityDefined) Either all or no rule should have the priority specified.`

The CLI command does not provide the `--priority` flag so the priority number should be automatically generated (all other rules in the AGW have a priority already set).

**To Reproduce**
Execute the following command:

```
az network application-gateway rule create `
        --gateway-name test-gateway-name `
        --name test-rule-name `
        --resource-group test-rg-name `
        --http-listener test-listener-name `
        --http-settings test-httpsetting-name `
        --address-pool test-address-pool-name
```

**Expected behavior**
The priority value should be automatically generated by the service when it is not provided in the command.

**Environment summary**
The CLI command is being executed by a ubuntu-18.04 Azure DevOps work agent.

**Additional context**
This has only recently started failing (last couple of days).

**Comment by yonzhan** [comment]
network

**Comment by RobHofmann** [comment]
We are observing the same behaviour since about 24-72 hours.

We have a automated setup which has been working for over 2 years. and we noticed yesterday that we cannot create new gateway entrypoints due to this bug.

PS. We never give priorities to the App Gateway (it has been deciding this for itself).

**Comment by necusjz** [comment]
As there is no changes from Azure CLI, involve service team for help.

IMO, the default priority order should be the order of adding rules to application gateway, isn't it?

**Comment by mferris2421** [comment]
Experiencing the same issue. WAG deployments are scripted via Azure CLI and no priority was ever supplied prior to Thursday.

**Comment by necusjz** [comment]
FYI. The logic has been changed from the service side:
- https://github.com/Azure/azure-cli/issues/22329#issuecomment-1122155395.

**Comment by johnrsierra** [comment]
Same behavior here. We are using API Fluent to create/modify settings on AppGW. On 1.38.1 (latest) we haven't seen any option to set priority on Rules.

**Comment by necusjz** [comment]
> I confirm we are observing the same behavior. but it works for CUS region and doesn't work for EUS2

It might be related to the deployment strategy, as you known, East US 2 is one of the canary regions. Let's wait for the service team to jump in and provide us more information. : )

**Comment by hernandezcolomina** [comment]
I confirm we have the same issue since today on EMEA region.
It works after adding the Priority input parameter to the Add-AzApplicationGatewayRequestRoutingRule  command.
 
As stated by [necusjz](https://github.com/necusjz) the API has changed and Priority is now mandatory

**Comment by Kerry-G** [comment]
We had the same issue with az cli version 2.37. There is no problem creating a rule without any priority with az cli 2.34. Is this intended?

**Comment by necusjz** [comment]
> We had the same issue with az cli version 2.37. There is no problem creating a rule without any priority with az cli 2.34. Is this intended? I can't find anything in the azure cli release docs that would imply a breaking change related to creating appgw rules.

@Kerry-G, actually, it's a breaking change involved by service, you can refer to this document: https://docs.microsoft.com/en-us/azure/application-gateway/multiple-site-overview.

**Comment by Kerry-G** [comment]
> > We had the same issue with az cli version 2.37. There is no problem creating a rule without any priority with az cli 2.34. Is this intended? I can't find anything in the azure cli release docs that would imply a breaking change related to creating appgw rules.
> 
> 
> 
> @Kerry-G, actually, it's a breaking change involved by service, you can refer to this document: https://docs.microsoft.com/en-us/azure/application-gateway/multiple-site-overview.

Are you saying that it is intended to not have the same behaviour between az cli version 2.34 and 2.37 because of the service? I understand the change in the service part, what I am still confuse is why we have different response depending on our az cli version.

**Comment by necusjz** [comment]
> Are you saying that it is intended to not have the same behaviour between az cli version 2.34 and 2.37 because of the service? I understand the change in the service part, what I am still confuse is why we have different response depending on our az cli version.

More specifically, the reason is 2.34 and 2.37 send requests based on different API versions:
- 2.34: https://github.com/Azure/azure-cli/blob/598673dae676ead1fee4f58afa8c127b67f41be6/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L147
- 2.37: https://github.com/Azure/azure-cli/blob/913767e3d77868586cb50eab1053aef20a7aa010/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L150

And, as I mentioned before, the breaking change is involved since '2021-08-01'.

**Comment by necusjz** [comment]
> HI, I have an issue too.
> 
> Depending of the application gateway instance that I use I have an error or not.
> 
> I use the same AZ CLI version and the same command (except for the name of the rule and app gtw instance refs).
> 
> With my first application gateway instance I receive the following error when creating a rule with this AZ CLI cmd
> 
> az network application-gateway rule create --subscription XXX --resource-group RG_XXX --gateway-name AG_XXX --name PTAIL_CLNT_souscriptionpp_INT --rule-type PathBasedRouting --http-listener PTAIL_CLNT_souscriptionpp_INT --url-path-map PTAIL_CLNT_souscriptionpp_INT --address-pool See-Warning --http-settings See-Warning **--priority 50**
> 
> **ERROR: (ApplicationGatewayRequestRoutingRulePartialPriorityDefined) Either all or no rule should have the priority specified.**
> 
> Setting the rule with the same priority (50) via Azure portal is **OK**.
> 
> Other rules (of other listeners) have the priority 10 & 20

Please follow [this reference](https://github.com/Azure/azure-cli/issues/23079#issuecomment-1185068194) to add `--priority` at the correct level, and the corresponding documents will be updated soon.

**Comment by Brudem** [comment]
> > HI, I have an issue too.
> > Depending of the application gateway instance that I use I have an error or not.
> > I use the same AZ CLI version and the same command (except for the name of the rule and app gtw instance refs).
> > With my first application gateway instance I receive the following error when creating a rule with this AZ CLI cmd
> > az network application-gateway rule create --subscription XXX --resource-group RG_XXX --gateway-name AG_XXX --name PTAIL_CLNT_souscriptionpp_INT --rule-type PathBasedRouting --http-listener PTAIL_CLNT_souscriptionpp_INT --url-path-map PTAIL_CLNT_souscriptionpp_INT --address-pool See-Warning --http-settings See-Warning **--priority 50**
> > **ERROR: (ApplicationGatewayRequestRoutingRulePartialPriorityDefined) Either all or no rule should have the priority specified.**
> > Setting the rule with the same priority (50) via Azure portal is **OK**.
> > Other rules (of other listeners) have the priority 10 & 20
> 
> Please follow [this reference](https://github.com/Azure/azure-cli/issues/23079#issuecomment-1185068194) to add `--priority` at the correct level, and the corresponding documents will be updated soon.

Thanks for the link but I think it don't really suit my issu. 

I don't want to create a new application gateway but only updating a rule.

The link provided is about "az network application-gateway create" not az network application-gateway **rule** create.

As you create applicaiton gateway only one time, how do you do to just add or update a rule via AZ CLI on an existing app gtw ?

**Comment by necusjz** [comment]
@Brudem, I see, as it's a different story, could you please open a new issue for that? We'll work on triaging it. Thanks.
