### ISSUE TITLE
Unclear difference V1 and v2, especially the --body format in v2's az webapp auth set

### ISSUE THREAD

**Issue by owingruters** [Azure/azure-cli#22289]
- I just had to move from v1 webapp authentication to v2. 
- After the conversion my old script using "az webapp auth update" are not working any more. From the documentation https://docs.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest#az-webapp-auth-update I think I see (but not very clear, that I should use "az webapp auth set" now. and it seems all settings have to be in a json object specified in the --body parameter. But it is totally unclear how this json object should look like.
- Can you add this to the description of the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeb196c8-e408-8563-26ba-5c3ae6e38c48
* Version Independent ID: 5f150c9a-e142-2fd7-fe84-b298dc83fd02
* Content: [az webapp auth](https://docs.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/auth.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/auth.yml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@owingruters Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@owingruters Are you looking for this https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/update-auth-settings-v2#request-body?
