### ISSUE TITLE
Cannot specify custom ip prefix in other subscription when using public-ip prefix create

### ISSUE THREAD

**Issue by brianlehr** [Azure/azure-cli#22295]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az network public-ip prefix create needs to recognize object in other subscription as input for --custom-ip-prefix-name parameter.  This functionality works in PowerShell but not CLI.

**Describe the bug**
Currently not able to specify a Custom IP Prefix object in other subscription as parameter for input.

Example 1:
PS C:\Users\blehr> az account set --subscription 6bb4a28a-db84-4e8a-b1dc-fabf7bd9f0b2
PS C:\Users\blehr> $customipprefix = az network custom-ip prefix show --name TestBYOIP --resource-group anavi_GWLB_cli
PS C:\Users\blehr> az account set --subscription c9f7da78-9fdd-4cbf-a881-45466556bb0a
PS C:\Users\blehr> az network public-ip prefix create --length 31 --name othersubprefix --resource-group othersubRG --location eastus --zone 2 --custom-ip-prefix-name $customipprefix
**'194.41.20.0' is not recognized as an internal or external command, operable program or batch file.**

This fails, as $customipprefix variable does not have the id of the Custom IP Prefix from the first subscription.

Example 2:
PS C:\Users\blehr> az network public-ip prefix create --length 31 --name othersubprefix --resource-group othersubRG --location eastus --zone 2 --custom-ip-prefix-name /subscriptions/6bb4a28a-db84-4e8a-b1dc-fabf7bd9f0b2/resourceGroups/anavi_GWLB_cli/providers/Microsoft.Network/customIPPrefixes/TestBYOIP
**(ResourceNotFound) The Resource 'Microsoft.Network/customIpPrefixes/subscriptions' under resource group 'othersubRG' was not found.** 

This also fails, as it does not understand the ID of an object in another subscription.

**To Reproduce**
See above

**Expected behavior**
Both Examples 1 and 2 should work (best case) or at least one of them (minimum viable case).

**Environment summary**
azure-cli 2.28.0

**Additional context**
See this original issue for the creation of the custom-ip prefix commands and related commands: https://github.com/Azure/azure-cli/issues/18953

**Comment by yonzhan** [comment]
network
