### ISSUE TITLE
[BASTION] az rest - cannot update properties

### ISSUE THREAD

**Issue by jetnet** [Azure/azure-cli#22304]
**Related command**
```
az rest --method patch --uri "$BastionId?api-version=2020-11-01" --body '{"properties":{"enableTunneling":false}}' -o none  --debug
```

**Describe the bug**
Value of the parameter does not change

**To Reproduce**
```
BastionName="YOUR_BASTION"
BastionId=$(az network bastion show -n $BastionName -o tsv --query id --only-show-errors)

az network bastion show -n $BastionName -o tsv --query enableTunneling --only-show-errors
# => true

az rest --method patch --uri "${BastionId}?api-version=2021-05-01" --body '{"properties":{"enableTunneling":false}}' -o none

# monitor until the status is Succeeded:
az network bastion show -n $BastionName -o tsv --query "{state:provisioningState,tunnel:enableTunneling}" --only-show-errors

# => Succeeded        True
```

**Expected behavior**
The `enableTunneling` should be changed to `False`

**Environment summary**
```
$ uname -a
Linux host 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ az --version
azure-cli                         2.36.0

core                              2.36.0
telemetry                          1.0.6

Extensions:
ssh                                1.1.0

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/c/Users/user/.azure/cliextensions'

Python (Linux) 3.8.13 (default, Apr 22 2022, 04:53:09)
[GCC 9.4.0]
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@jetnet Thanks for reaching out to us and sharing this feedback. Looking at [the REST API](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/bastion-hosts/create-or-update), I see that it uses the PUT method. 

So could you please try the below command instead ? 

>az resource update --ids /subscriptions/XXXXXXX/resourceGroups/MyBastionRG/providers/Microsoft.Network/bastionHosts/MyBastionName --set properties.enableTunneling=**true** 

Hope this helps.

**Comment by jetnet** [comment]
@navba-MSFT , it works! Thank you for pointing to another way how to change a property :)
Just curious: should the `az rest patch` method work too? In theory, of cause :)

**Comment by navba-MSFT** [comment]
@jetnet Thanks for getting back. Patch wouldn't work here. The above mentioned RESTAPI supports PUT. 
We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
