### ISSUE TITLE
LogAnalytics: support new resources of QueryPacks

### ISSUE THREAD

**Issue by dabenhamMic** [Azure/azure-cli#22310]
**Related command**

our latest swagger change included an update to QueryPacks module: https://github.com/Azure/azure-rest-api-specs/pull/17923
Python SDK: https://pypi.org/project/azure-mgmt-loganalytics/13.0.0b4/

**Resource Provider**

OperationalInsights (LogAnalytics)

**Description of Feature or Work Requested**

A request to bump up CLI cersion to latest Python SDK was already creatted after Python SDK was released: https://github.com/Azure/azure-cli/pull/22013

this did not include any [changes to 2 modules](https://github.com/Azure/azure-rest-api-specs/pull/17923/files#diff-41cf180e082b83bc1ed1dcc0e32609b39a89f7396bec2285067b10dd606a3e8cR239):
1. QueryPAcks
2. QueryPackQueries

**Minimum API Version Required**

Python SDK ver 13.0.0b4

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/operationalinsights/resource-manager/readme.md#tag-package-2022-02

**Target Date**

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
@dabenhamMic I'm confuse about this swagger [property](https://github.com/dabenhamMic/azure-rest-api-specs/blob/7d1b7dc08e4dbb1a9e8d569ee29ed59e5731757c/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2019-09-01/QueryPackQueries.json#L452-L455). What's it used for and why it does have any detailed schema definition? Is this property read-only?

**Comment by dabenhamMic** [comment]
> @dabenhamMic I'm confuse about this swagger [property](https://github.com/dabenhamMic/azure-rest-api-specs/blob/7d1b7dc08e4dbb1a9e8d569ee29ed59e5731757c/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2019-09-01/QueryPackQueries.json#L452-L455). What's it used for and why it does have any detailed schema definition? Is this property read-only?

you can leave this property out of CLI experience

**Comment by dabenhamMic** [comment]
Hi @kairu-ms @jsntcy 

We have a couple of open tickets on the CLI module:
https://msazure.visualstudio.com/One/_workitems/edit/14318495
https://msazure.visualstudio.com/One/_workitems/edit/14318510

Bugs description:

1.	Updating CMK key with empty version “” fails. I verified and it works fine in REST
PS C:\Users\yossiy> $kUri = 'https://yossiy-eus.vault.azure.net'
PS C:\Users\yossiy> $kName = 'yossiy-test1'
PS C:\Users\yossiy> $kVersion = ''
PS C:\Users\yossiy> az monitor log-analytics cluster update --name $clusterName --resource-group $rg --key-name $kName --key-vault-uri $kUri --key-version $kVersion
argument --key-version: expected one argument


2.	Updating BillingType not supported. I verified and it works fine in REST
PS C:\Users\yossiy> az monitor log-analytics cluster update --name $clusterName --resource-group $rg 'Workspaces'
unrecognized arguments: Workspaces

can you please add these changes to the upcoming update as well?

**Comment by kairu-ms** [comment]
> Hi @kairu-ms @jsntcy
> 
> We have a couple of open tickets on the CLI module: https://msazure.visualstudio.com/One/_workitems/edit/14318495 https://msazure.visualstudio.com/One/_workitems/edit/14318510
> 
> Bugs description:
> 
> 1. Updating CMK key with empty version “” fails. I verified and it works fine in REST
>    PS C:\Users\yossiy> $kUri = 'https://yossiy-eus.vault.azure.net'
>    PS C:\Users\yossiy> $kName = 'yossiy-test1'
>    PS C:\Users\yossiy> $kVersion = ''
>    PS C:\Users\yossiy> az monitor log-analytics cluster update --name $clusterName --resource-group $rg --key-name $kName --key-vault-uri $kUri --key-version $kVersion
>    argument --key-version: expected one argument
> 2. Updating BillingType not supported. I verified and it works fine in REST
>    PS C:\Users\yossiy> az monitor log-analytics cluster update --name $clusterName --resource-group $rg 'Workspaces'
>    unrecognized arguments: Workspaces
> 
> can you please add these changes to the upcoming update as well?

Hi @dabenhamMic, could you create another feature request issue for this? Thanks.

**Comment by dabenhamMic** [comment]
@kairu-ms thanks for your response.
opened a new issue: https://github.com/Azure/azure-cli/issues/22842
