### ISSUE TITLE
az sql server ad-admin create does not work if we do not pass both object-id and display-name at same time

### ISSUE THREAD

**Issue by ramdaspotale** [Azure/azure-cli#22316]
as per the documentation, object-id and display-name are optional parameters, however, actually they are required. you can not configure ad-admin without passing both object-id and display-name parameters.

so i propose you should modify documentation to say all parameters are required for create/update actions.
===============================================================================
az sql server ad-admin create --server <server_name> --resource-group <Resource_Group> --display-name <user/group name>
(InvalidResourceIdSegment) The 'parameters.properties' segment in the url is invalid.
Code: InvalidResourceIdSegment
Message: The 'parameters.properties' segment in the url is invalid.
Exception Details:      (InvalidResourceIdSegment)
        Code: InvalidResourceIdSegment
        Message:
        Target: parameters.properties

===========================================================================
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bca10a0-5310-1ed6-8391-57a8ccafb27f
* Version Independent ID: 4144f2fa-35f1-533c-e48b-17180f03203e
* Content: [az sql server ad-admin](https://docs.microsoft.com/en-us/cli/azure/sql/server/ad-admin?view=azure-cli-latest#az-sql-server-ad-admin-create)
* Content Source: [latest/docs-ref-autogen/sql/server/ad-admin.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sql/server/ad-admin.yml)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@ramdaspotale Thank you for reaching out to us, we are looking into it.

**Comment by ramdaspotale** [comment]
Hi,

Thanks for the update. to explain a bit more. 

I have tried running below command by passing one parameter among object-id and display-name and it did not work. like below

az sql server ad-admin create --server <server_name> --resource-group <Resource_Group> --display-name <user/group name>
or
az sql server ad-admin create --server <server_name> --resource-group <Resource_Group> --object-id <object-id>

it only worked when i passed both parameters same time. like below

az sql server ad-admin create --server <server_name> --resource-group <Resource_Group> --display-name <user/group name> --object-id <object-id>

**Comment by RakeshMohanMSFT** [comment]
@ramdaspotale Thank you for further details provided, appreciate it. Will check and update the document if required.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@ramdaspotale I think what you said is correct. This document does mention that too.
https://docs.microsoft.com/en-us/rest/api/sql/2021-02-01-preview/server-azure-ad-administrators/create-or-update. 
Let me get the document updated.

**Comment by ramdaspotale** [comment]
@RakeshMohanMSFT Thanks a lot Rakesh. 👍
