### ISSUE TITLE
Error message after SFC scale-in process finished.

### ISSUE THREAD

**Issue by ptsapralis** [Azure/azure-cli#22315]
Received this error as part of a process reducing the number of nodes in the primary node-type of an SFC. The scale-in process seems to have completed successfully and the cluster is running OK.

**Command Name**
`az sf cluster node remove`

**Errors:**

The command failed with an unexpected error. Here is the traceback:
'ClustersOperations' object has no attribute 'update'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/servicefabric/custom.py", line 503, in remove_cluster_node
    return client.update(resource_group_name, cluster_name, patch_request)
AttributeError: 'ClustersOperations' object has no attribute 'update'

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sf cluster node remove --verbose --cluster-name {} --resource-group {} --node-type {} --nodes-to-remove {}`

## Environment Summary

Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.8.13
Installer: DEB

azure-cli 2.36.0

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@ptsapralis Thanks for reaching out to us and sharing this feedback. I am looking into this issue. I will update this thread once I have more details on this.

**Comment by navba-MSFT** [comment]
@ptsapralis I am able to reproduce this issue at my end. I have reached out to the Product Owners with my findings. I will get back to you as soon as I hear from them.

**Comment by ptsapralis** [comment]
@***@***.***>, thank you very much for this update – looking forward to hearing from Product Owners.

Regards,
Panos Tsapralis
Head of Networks
(M) 07507477883
(direct) 442082755505
4 Imperial Place, Maxwell Road, Borehamwood, Hertfordshire, WD6 1JN
***@***.******@***.***>

[signature_1068431720]   [signature_38683042]     ***@***.***

From: navba-MSFT ***@***.***>
Date: Wednesday, 11 May 2022 at 11:32
To: Azure/azure-cli ***@***.***>
Cc: Panos Tsapralis ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/azure-cli] Error message after SFC scale-in process finished. (Issue #22315)

CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@ptsapralis<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fptsapralis&data=05%7C01%7Cpanos.tsapralis%40buyagift.com%7C1789edf687b541c7ffdc08da33399c7c%7C1691bca2aa30424db58761d9d74d6c21%7C0%7C0%7C637878619768928694%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=S3df31n9ArW7%2FjfGff%2FY33O9IJMwNw97nGpKALay2Xw%3D&reserved=0> I am able to reproduce this issue at my end. I have reached out to the Product Owners with my findings. I will get back to you as soon as I hear from them.

**Comment by navba-MSFT** [comment]
@ptsapralis The above PR has been filed to fix this issue. Currently @a-santamaria is working to activate the tests that runs through this code paths but it should be ready to be included on the next release [May 2022 (2022-05-24)](https://github.com/Azure/azure-cli/milestone/118).

Thanks @a-santamaria for your help.

**Comment by ptsapralis** [comment]
@navba-MSFT / @a-santamaria : thank you both very much for this update and for your assistance.

**Comment by navba-MSFT** [comment]
@ptsapralis While the PR is under review, In the meantime if you have any questions, please feel free to ask here.

**Comment by navba-MSFT** [comment]
@ptsapralis This PR https://github.com/Azure/azure-cli/pull/22283 includes the fix and it is merged now. The fix should be available in the next release. Refer the [May milestone ](https://github.com/Azure/azure-cli/milestone/118). With that we will proceed with closure of this thread. If you need any further assistance on this in future, feel free to reopen this. We would be happy to help.
