### ISSUE TITLE
Priority is "required" now not "optional"

### ISSUE THREAD

**Issue by maotsuk** [Azure/azure-cli#22329]
if we didn't add this parameter then the below error message would return

ApplicationGatewayRequestRoutingRulePartialPriorityDefined
Either all or no rule should have the priority specified.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d6ba93c-4a1c-c69d-f52a-001791e0220a
* Version Independent ID: 2dd75bbb-a92c-c8f5-354b-6d40e531190b
* Content: [az network application-gateway rule](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/rule?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/application-gateway/rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/application-gateway/rule.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network
