### ISSUE TITLE
Shared gallery replace '--seletct=permissions' with '--expand=sharingProfile/Groups'

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#22327]
**Related command**

az sig show

**Resource Provider**

Azure.Compute

**Description of Feature or Work Requested**

Previous we have project direct sharing CLI support and for command 'az sig show', we do not show gallery's sharing profile- groups unless user input '--select=permissions' and that is a bad design which does not have anything to do with 'permissions' and it does not conform to OData standard, we plan to correct it and replace it '--expand=sharingProfile/Groups'.

**Minimum API Version Required**

2021-10-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/blob/3abdf3eaf45b42d78e242a2cca4a977e8dcf3103/specification/compute/resource-manager/Microsoft.Compute/stable/2021-10-01/gallery.json#L3159-L3173

**Target Date**

06/30

**Comment by yonzhan** [comment]
Compute
