### ISSUE TITLE
az storage blob directory metadata show - always gives error - The specified blob does not exist

### ISSUE THREAD

**Issue by willieowens** [Azure/azure-cli#22323]
I always get this error when trying to look up the metadata of a directory:
```
This command is implicitly deprecated because command group 'storage blob directory' is deprecated and will be removed in a future release. Use 'az storage fs directory' instead.
The specified blob does not exist. ErrorCode: BlobNotFound
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:dddaf9d3-001e-00a5-2be8-638c5e000000
Time:2022-05-09T21:03:21.5394215Z</Message></Error>
```

Is this supposed to work? Is it deprecated? The page itself seems to imply it's new/experimental functionality, rather than old/deprecated, but maybe it's... both?

> This reference is part of the storage-preview extension for the Azure CLI (version 2.25.0 or higher). The extension will automatically install the first time you run an az storage blob directory metadata command. [Learn more](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview) about extensions.

https://docs.microsoft.com/en-us/cli/azure/storage/blob/directory/metadata?view=azure-cli-latest

`az storage blob directory metadata show --auth-mode login --account-name XXXX --container-name XXXX --directory-path /`
`az storage blob directory metadata show --auth-mode login --account-name XXXX --container-name XXXX --directory-path \\`
`az storage blob directory metadata show --auth-mode login --account-name XXXX --container-name XXXX --directory-path ''`
`az storage blob directory metadata show --auth-mode login --account-name XXXX --container-name XXXX --directory-path test`
`az storage blob directory metadata show --auth-mode login --account-name XXXX --container-name XXXX --directory-path test/`
`az storage blob directory metadata show --auth-mode login --account-name XXXX --container-name XXXX --directory-path /test`
`az storage blob directory metadata show --auth-mode login --account-name XXXX --container-name XXXX --directory-path \\test`
`az storage blob directory metadata show --auth-mode login --account-name XXXX --container-name XXXX --directory-path test\\`

Tried w/ single and double quotes around all those above commands as well. What _does_ work is specifying a single blob/file, ie:
`az storage blob directory metadata show --auth-mode login --account-name XXXX --container-name XXXX --directory-path file`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06985730-49e0-fd92-af9c-6f6b90a2ce1c
* Version Independent ID: 47647ba2-c9e6-0039-34bd-1756273aa402
* Content: [az storage blob directory metadata](https://docs.microsoft.com/en-us/cli/azure/storage/blob/directory/metadata?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/blob/directory/metadata.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/blob/directory/metadata.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Hi @willieowens, as the warning message said, can you try `az storage fs directory metadata show`? It should work well:
![image](https://user-images.githubusercontent.com/10227683/167534011-10463d3a-00a1-4a29-8cd1-b2739c46320f.png)

**Comment by willieowens** [comment]
Thanks, unfortunately I've tried to use `fs` as well (forgot to mention), with the same issue.

In your test above, are you pointing at an Azure Storage `container` explicitly, or a file share?

I have tried the `az storage fs` commands on both a container that has `Container` and one that has `Blob` level access, both give the same error when specifying a directory that exists. Similar to the original command(s) tried, I do get back a response fine when pointing to a file, or a file within a directory path.

![image](https://user-images.githubusercontent.com/1161333/167656463-984005e7-b0e7-4049-b52d-9afbe35e79bb.png)

![image](https://user-images.githubusercontent.com/1161333/167656555-e5a73374-c8bf-46c1-aaea-f5a054c75a40.png)

**Comment by evelyn-ys** [comment]
If you want to get metadata for a directory from file share, you should use `az storage directory metadata show`.

`az storage fs directory metadata show` is used for blobs which have enabled hierarchical namespace in ADLS Gen2 storage account.

**Comment by willieowens** [comment]
So are the docs... wrong? I have storage account containers in blob storage, I'm not using filesystem or data lakes.

![image](https://user-images.githubusercontent.com/1161333/167861795-10178fb2-5b30-44c5-9d3b-f8e1e866f8fe.png)

**Comment by evelyn-ys** [comment]
For normal storage account, blob directory isn't real directory, it's just part of the blob name😅
Only ADLS Gen2 storage account has real directory. So `az storage blob directory` is designed for ADLS Gen2 container and blob. And it has been renamed to `az storage fs directory` now.

Sorry for any inconvenience😂

**Comment by willieowens** [comment]
Ok, thanks. I'll... close this I guess. Seems like what I ultimately wanted to do (set Cache-Control info/headers on all blobs in my container) isn't even possible in the CLI. Feature request! I ultimately did this with a powershell script instead using the Az Powershell module.

I do think the docs are confusing here and could use some polish.

Thanks for the help!
