### ISSUE TITLE
Azure VM Image List show architecture

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#22326]
**Related command**

az vm image list

**Is your feature request related to a problem? Please describe.**

Curently 'az vm image list' does not return property 'architecture', we hope this can be applied for filter.

**Describe the solution you'd like**

az vm image list [--all]
                 [--edge-zone]
                 [--location]
                 [--offer]
                 [--publisher]
                 [--sku]
                 **[--architecture] {x64 | Arm64}**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Compute
