### ISSUE TITLE
az devops security group membership list - Returns dictionary instead of JSON array

### ISSUE THREAD

**Issue by VNoveski** [Azure/azure-cli#22346]
When running following command
```
az devops security group membership list --id < vssgp ID or descriptor > \
                                        --detect false \
                                        --org < org. URL>
```
result is returned like
```
{
  "aad.YjU...": {
    "descriptor": "aad.YjU...",
    "directoryAlias": "...",
    "displayName": "...",
    "domain": "...",
    "legacyDescriptor": null,
    "mailAddress": "...",
    "metaType": "member",
    "origin": "aad",
    "originId": "...",
    "principalName": "...",
    "subjectKind": "user",
    "url": "..."
  },
  "aad.ZWM...": {
    "descriptor": "aad.ZWM...",
    ...
  }
}
```
Am I wrongly expecting result to be JSON array? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3724db0b-ba6d-0ea6-be45-656a44d6b4dd
* Version Independent ID: 6fe9ab83-4f17-8021-ff21-a1196f510c6b
* Content: [az devops security group membership](https://docs.microsoft.com/en-us/cli/azure/devops/security/group/membership?view=azure-cli-latest#az-devops-security-group-membership-list)
* Content Source: [latest/docs-ref-autogen/devops/security/group/membership.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/devops/security/group/membership.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
@VNoveski 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by v-anvashist** [comment]
@VNoveski We are owing only azure devOps CLI service.

We are not owing the same.

Thanks,
Anjali

**Comment by FokkoVeegens** [comment]
@yonzhan / @SatishBoddu-MSFT / @v-anvashist can you please route this to the correct team? I am running into the same issue.

**Comment by FokkoVeegens** [comment]
@yonzhan Can you mention the right people, so they are aware?

**Comment by yonzhan** [comment]
cc @v-anvashist, @V-hmusukula

**Comment by FokkoVeegens** [comment]
Seems to me like an infinite loop... These guys have already been cc'd and have indicated that they are not involved with this Azure CLI extension.

**Comment by v-soujanya** [comment]
Hi @VNoveski,
we have checked in our system the output in is JSON array. Please check the image for reference, and we confirmed by using JSON Viewer in online the result is in formatted string. Please let us know if any queries.

![image](https://user-images.githubusercontent.com/101401302/172805653-6f7650ef-13f4-498d-87d2-cc02feff122e.png)
 
Double checked in JSON Viewer
![image](https://user-images.githubusercontent.com/101401302/172806339-2b467c25-4673-4932-b94d-9437181daf4a.png)

**Comment by FokkoVeegens** [comment]
Although you have valid XML, the expected format would be:
```
[
   {
      "descriptor": "aad.****"
      "directoryAlias": "johndoe"
      "displayName": "John Doe"
   }
]
```
Please note the brackets and the absence of the additional line with the descriptor as name of the object.

**Comment by v-soujanya** [comment]
Hi @FokkoVeegens 
we digged the code and identified the same response is coming from the API ((https://vssps.dev.azure.com/{organization}/_apis/Graph/Users/aad.{vssgp ID}),
 so, we need to work with the API team to make any changes. we will get back to you once we connect with the API team.

**Comment by FokkoVeegens** [comment]
Ok, so can you fix this @v-soujanya ?

**Comment by v-soujanya** [comment]
@FokkoVeegens, we are receiving the same response from API, and we already reported this request to the API team. Once they have the sufficient bandwidth they will work on this request. if we have any updates from API team we will share with you.
Thanks!

**Comment by FokkoVeegens** [comment]
Already more than a year old. Is this ever going to be fixed? Running into the same issue again...

**Comment by V-hmusukula** [comment]
Hi,

Consider for delay, will look into this and get back to you with investigation.

@***@***.***> & @***@***.***> : Can you please look into this on priority.

Thank you!!
Regards,
Harjun Reddy M
Organization: LTIMindtree
Mobile : 9642099199
Email : ***@***.******@***.***>

**Comment by v-soujanya** [comment]
@FokkoVeegens  apologies for the delay here, we are checking this and get back to you shortly.

**Comment by v-soujanya** [comment]
Hi @FokkoVeegens, we checked it here in our devops extension we are making a call to the API and receiving response from API, we are not manipulating the response after receiving from API, we are in communication with API team to know how they are sending the data. Will post the updates once we get.

**Comment by FokkoVeegens** [comment]
@v-soujanya Sounds like the previous comment from @V-hmusukula more than a year ago;

> Consider for delay, will look into this and get back to you with investigation.

**Comment by v-anvashist** [comment]
Hi @FokkoVeegens 
PG understands the concern regarding az devops security group membership list command, which returns dictionary instead of list. However, the behavior exists in CLI since the introduction of this command and mimics the REST API response format. Azure DevOps does not have plans in the nearest future to change this behavior, as it introduces breaking change for existing customers' automation. Customers are advised to map output of CLI in-place, according to their needs e.g., using jq for JSON manipulations.

**Comment by FokkoVeegens** [comment]
@v-anvashist Ok, clear. It would be nice to change it as part of a new major version, but for now please go ahead and close this issue.

**Comment by v-anvashist** [comment]
@yonzhan  Can we close this issue now?
