### ISSUE TITLE
Add "federatedClientId" and UserAssignedIdentities for disk api version 2022-03-02 for public preview

### ISSUE THREAD

**Issue by laurawu19** [Azure/azure-cli#22350]
**Related command**
az disk-encryption-set create --federatedClientId "13ebe945-1314-41b4-8b58-f3784e0dd278" --identityType "UserAssigned" --userAssignedIdentities "{ /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName} :{}}"

az disk-encryption-set update --federatedClientId "13ebe945-1314-41b4-8b58-f3784e0dd278" --identityType "UserAssigned" --userAssignedIdentities "{ /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName} :{}}"

**Resource Provider**
<Microsoft.Azure.Management.Compute (specifically DiskRP)>

**Description of Feature or Work Requested**
Customer can use multi-tenant application client id to access key vault in a different tenant. Setting federatedClientId to 'None' will clear the property.

Need to support new identityTypes. Previously the default identityType is systemAssigned, now CLI need to support 2 more options for identityType: UserAssigned, and "SystemAssigned, UserAssigned".

UserAssignedIdentities is a dictionary with key-value pairs.

Powershell design:
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1196

**Minimum API Version Required**
<2021-08-01>

**Swagger Link**
<https://github.com/Azure/azure-rest-api-specs/pull/18866>

**Target Date**
<July 8th,2022>

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@laurawu19 Hi, since our work in this sprint has been fully arranged, we don't have enough time to support more requirements. Can this feature request be postponed to the release of the next sprint (**08-02**)?

**Comment by zhoxing-ms** [comment]
@laurawu19 After our internal discussion, we will develop and release this requirement in this sprint.
By the way, for the support of managed identity, we usually do not use `--identity-type`, but we have an unified specifications. Please refer to the [managed_identity_command_guideline.md](https://github.com/Azure/azure-cli/blob/dev/doc/managed_identity_command_guideline.md)for details
May I ask can the design of managed identity related parameters according to our guidelines meet your expectations?

**Comment by zhoxing-ms** [comment]
In addition, I found that the property of `federatedClientId` was introduced in the `2022-03-02` api-version folder [Swagger link](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2022-03-02/DiskRP/diskEncryptionSet.json#L418
) so we need to use version `2022-03-02` instead of api-version `2021-08-01`, right?

**Comment by laurawu19** [comment]
> @laurawu19 For the support of managed identity, we usually do not use `--identity-type`, but we have an unified specifications. Please refer to the [managed_identity_command_guideline.md](https://github.com/Azure/azure-cli/blob/dev/doc/managed_identity_command_guideline.md) for details May I ask can the design of managed identity related parameters according to our guidelines meet your expectations?

Yes. The design you provided looks good to us.

**Comment by laurawu19** [comment]
> In addition, I found that the property of `federatedClientId` was only introduced in the `2022-03-02` api-version folder [Swagger link](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2022-03-02/DiskRP/diskEncryptionSet.json#L418). So we need to use version `2022-03-02` instead of api-version `2021-08-01`, right?

In DiskRP internally, the minimun api version required is 2021-08-01, and it is included in the swagger for "2022-03-02". Is the policy that cli should follow the same as swagger? If so, we will go with 2022-03-02.

**Comment by zhoxing-ms** [comment]
> Is the policy that cli should follow the same as swagger? If so, we will go with 2022-03-02.

Yes, because CLI depends on the Python SDK, and the api-version folder of Python SDK comes from the definition of Swagger

**Comment by yanzhudd** [comment]
> > @laurawu19 For the support of managed identity, we usually do not use `--identity-type`, but we have an unified specifications. Please refer to the [managed_identity_command_guideline.md](https://github.com/Azure/azure-cli/blob/dev/doc/managed_identity_command_guideline.md) for details May I ask can the design of managed identity related parameters according to our guidelines meet your expectations?
> 
> Yes. The design you provided looks good to us.

@laurawu19 The modified commands are attached following, and are they meet your expectations?

For federatedClientId:
1. create: az disk-encryption-set create ... --federatedClientId "13ebe945-1314-41b4-8b58-f3784e0dd278"
2. update: az disk-encryption-set update ... --federatedClientId "13ebe945-1314-41b4-8b58-f3784e0dd278"

For managed identity:
1. enable managed identity during disk creation
az disk-encryption-set create ... --mi-system-assigned --mi-user-assigned <AzureResourceId1> <AzureResourceId2>
2. operate managed identity on existing disk
a. assign identities: az disk-encryption-set identity assign ... --system-assigned --user-assigned <AzureResourceId1> <AzureResourceId2>
b. remove identities: az disk-encryption-set identity remove ... --system-assigned --user-assigned <AzureResourceId1> <AzureResourceId2> (no values for --user-assigned should remove all user assigned identities)
