### ISSUE TITLE
az aks check-acr error, AKS cannot pull image from container registry anymore

### ISSUE THREAD

**Issue by rfcdejong** [Azure/azure-cli#22353]
Our managed AKS cluster is unable to pull a new image from our container registry. I have tried everything listed in https://docs.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/cannot-pull-image-from-acr-to-aks-cluster without success. Checking if the cluster can connect to the registry gives this error.

**Command Name**
`az aks check-acr`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'serverVersion'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 1599, in aks_check_acr
    kubectl_version["serverVersion"]["minor"])
KeyError: 'serverVersion'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az aks check-acr --name {} --resource-group {} --acr {}`

## Expected Behavior

I want to see the real errormessage behind "ImagePullBackOff" or "ErrImagePull". 

## Environment Summary
```
Linux-5.4.0-1077-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.13
Installer: DEB

azure-cli 2.36.0

Extensions:
azure-devops 0.17.0
ai-examples 0.2.5
ssh 1.1.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by andyzhangx** [comment]
@rfcdejong could you try this demo, it could run canipull pod on specific node, that could help troubleshoot the issue: https://github.com/andyzhangx/demo/blob/master/aks/canipull/canipull.yaml

actually my `az aks check-acr` works with below version:
```
# az version 
{
  "azure-cli": "2.36.0",
  "azure-cli-core": "2.36.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.0",
    "hack": "0.1.0",
    "hpc-cache": "0.1.5",
    "k8s-extension": "1.0.0"
  }
}
```

**Comment by andyzhangx** [comment]
what's your `kubectl version -o json` output? could you use 1.21 kubectl binary?
```
# kubectl version -o json
{
  "clientVersion": {
    "major": "1",
    "minor": "21",
    "gitVersion": "v1.21.1",
    "gitCommit": "5e58841cce77d4bc13713ad2b91fa0d961e69192",
    "gitTreeState": "clean",
    "buildDate": "2021-05-12T14:18:45Z",
    "goVersion": "go1.16.4",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "21",
    "gitVersion": "v1.21.7",
    "gitCommit": "a326522ffdc578d1ac5c14cf8d0160feda9b13fc",
    "gitTreeState": "clean",
    "buildDate": "2022-04-21T07:40:45Z",
    "goVersion": "go1.16.10",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

**Comment by andyzhangx** [comment]
you could download kubectl here: http://mirror.azure.cn/kubernetes/kubectl/v1.21.7/bin/linux/amd64/

**Comment by rfcdejong** [comment]
I don't mind about that aks check-acr not working.

We believe we have found the error, it is the container being build on windows-2022 and not on 2019
This could be the fix

![image](https://user-images.githubusercontent.com/2665653/167804318-a48740bc-7b70-4b07-bbb3-f1d27ee856c8.png)

**Comment by rfcdejong** [comment]
The issue why i wanted to use check-acr in the first place.
canipull pod works fine

Our container image was build with windows 2022 which is probl the reason we cannot pull it from AKS

The aks check-acr doesn't work from the azure shell, didn't even try it locally

**Comment by andyzhangx** [comment]
> The issue why i wanted to use check-acr in the first place. canipull pod works fine
> 
> Our container image was build with windows 2022 which is probl the reason we cannot pull it from AKS
> 
> The aks check-acr doesn't work from the azure shell, didn't even try it locally

@rfcdejong AKS does not support Windows 2022 yet, pls build with 2019.

shall I close this issue?

**Comment by rfcdejong** [comment]
I'll close the issue as I don't need to use the functionality anymore and your canipull image yaml more usefull anyway.

I know it doesn't work on 2022, did cost me a day to figure out why pulling didn't work ;)
