### ISSUE TITLE
az command for adding a new Private Link configuration and associate it with an existing Frontend IP

### ISSUE THREAD

**Issue by elshat128** [Azure/azure-cli#22366]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
--- az network application-gateway private-link add --frontend-ip  --name  --subnet --gateway-name  --resource-group  ---

**Describe the bug**
--- For using existing subnet, If I put name of a existing subnet into '--subnet' argument, it won't start the operation, and return 'subnet duplicates' error msg, however, it will work, if I put subnet resource ID. 

**To Reproduce**
--- create a App GW with 2 subnets, one for app GW, and one for Private Link, then run command ---

**Expected behavior**
--- Users would think subnet name and subnet resource ID, both should work, and expecting better explanation with error msg---

**Environment summary**
--- Cloud shell / az CLI  ---

**Additional context**

**Comment by yonzhan** [comment]
Please provide detailed info in the description

**Comment by elshat128** [comment]
updated. thx

**Comment by necusjz** [comment]
@elshat128, I have a concern here:
If a Subnet already exists in the VNet of this Application Gateway, why should we add it again? It doesn't seem like a valid usage.

**Comment by elshat128** [comment]
> @elshat128, I have a concern here: If a Subnet already exists in the VNet of this Application Gateway, why should we add it again? It doesn't seem like a valid usage.

so this command is to add new one or Use/specify existing one, As we know App GW subnet and Bastion subnet can't be used for Private link, so in the case a user have a subnet other than these two, and want to use it for private link, this is the use case.

**Comment by necusjz** [comment]
@elshat128, for this case, we don't need to prepare a subnet in advance. We can create the subnet during [az network application-gateway private-link add](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/private-link?view=azure-cli-latest#az-network-application-gateway-private-link-add), i.e., it's a new *--subnet* at that moment.

**Comment by elshat128** [comment]
@necusjz what if user just happened to have a subnet handy which wasn't prepared in advance for this private link, and now they want to use this subnet, in this case during the command, users are potentially forced to create a new subnet, aren't they?

**Comment by necusjz** [comment]
@elshat128, so true, but such design also avoids the problem of subnet reuse.

**Comment by elshat128** [comment]
@necusjz that's right, I understand the design. because there is user posted questions about this on the internet, maybe return error msg can be more clear, let user know, in order to use existing subnet, please enter subnet resources ID. thanks.
