### ISSUE TITLE
Failing to deploy microsoft.insights/scheduledqueryrules log alert

### ISSUE THREAD

**Issue by JohnLudlow** [Azure/azure-cli#22360]
**Related command**

    az deployment group create 

**Describe the bug**

With a template (attached) that looks correct according to the [docs](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/scheduledqueryrules?tabs=json), we get this error:

    {
        "status": "Failed",
        "error": {
            "code": "DeploymentFailed",
            "message":"At least one resource deployment operation failed. Please list deployment operations for details.
    Please see https: //aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"BadRequest\",\r\n
    \"message\": \"{\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"InvalidRequestContent\\\",\\r\\n \\\"message\\\": \\\"The request content was invalid and could
    not be deserialized:
    'Error converting value \\\\\\\"/subscriptions/[sub-id]/resourceGroups/[resource-group-name]/providers/microsoft.insights/actiongroups/[app-insights-name]\\\\\\\" to type
    'System.Collections.Generic.List`1[System.String
            ]'. Path 'properties.actions.actionGroups', line 1, position 1047.'\\\"\\r\\n }\\r\\n}\"\r\n }\r\n}"
        }
    ]
    }
    }

**To Reproduce**

* Prepare an Azure resource group to contain the relevant alert. Ensure all prerequisites for a rule are in place
* Download and extract the attached arm.zip
* Modify parameters.json to replace [sub-id], [resource-group-name], and [app-insights-name] with the appropriate values.
* Run the template with the following command:
   `az deployment group create --template-file template.json --parameters parameters.json --resource-group [resource-group-name]`

**Expected behavior**
The template successfully creates the expected log alert with associated action group(s)

**Environment summary**

Install Method: Chocolatey, MSI
CLI Version:

    azure-cli   2.35.0 *
    core        2.35.0 *
    telemetry   1.0.6

    Extensions:
    azure-devops 0.18.0

    Dependencies:
    msal                1.17.0
    azure-mgmt-resource 20.0.0

    Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
    Extensions directory 'C:\Users\[user]\.azure\cliextensions'

    Python (Windows) 3.10.3 (tags/v3.10.3:a342a49, Mar 16 2022, 12:53:06) [MSC v.1929 32 bit (Intel)]

OS Version: Windows 10 21H2 (19044.1645)

Shell: Windows Powershell, `$PSVersionTable`:

    Name                      Value
    ----                      -----
    PSVersion                 5.1.19041.1645
    PSEdition                 Desktop
    PSCompatibleVersions      {1.0, 2.0, 3.0, 4.0...}
    BuildVersion              10.0.19041.1645
    CLRVersion                4.0.30319.42000
    WSManStackVersion         3.0
    PSRemotingProtocolVersion 2.3
    SerializationVersion      1.1.0.1

**Additional context**

[arm.zip](https://github.com/Azure/azure-cli/files/8669096/arm.zip)

We have been able to create the resource through the portal, but haven't been able to find a working ARM syntax with the current docs.

* [Microsoft.Insights/scheduledQueryRules](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/scheduledqueryrules?tabs=json)
* [Sample](https://docs.microsoft.com/en-us/azure/azure-monitor/alerts/resource-manager-alerts-log)

**Comment by yonzhan** [comment]
ARM

**Comment by JohnLudlow** [comment]
Hi @yonzhan,

Are you saying we need to raise this somewhere else? I believe the same behaviour is observed with the PowerShell cmdlets, so it's certainly reasonable this needs to be moved to a different repo. If you could point us in the right direction, that would be great.

Thanks

**Comment by JohnLudlow** [comment]
Seems we didn't have the syntax quite correct:

We had:

    "actionGroups": "[parameters('actionGroupId')]",

We should have had:

    "actionGroups": [
      "[parameters('actionGroupId')]"
    ],

Thanks
