### ISSUE TITLE
Should not use CreateOption 'CopyStart' for full snapshot creation

### ISSUE THREAD

**Issue by rytruong** [Azure/azure-cli#22370]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az snapshot create -g $resourceGroupName -n $snapshotName --source $yourDiskID

**Describe the bug**
If source disk is in different region, CLI will use CreateOption 'CopyStart', but 'CopyStart' is not supported for full snapshot.

**To Reproduce**
Create full snapshot in different region from the source disk

**Expected behavior**
-	For full snapshot use CreateOption Copy
-	For incremental snapshot use CreateOption Copy if same region and use CreateOption CopyStart if different region.

**Environment summary**

latest CLI version

**Additional context**

**Comment by yonzhan** [comment]
Compute

**Comment by PARADISSEEKR** [comment]
Hi @rytruong , If source disk is in different region, `az snapshot create -g rg -n snapshot --source disk --incremental true -l eastus2euap` return `(InvalidParameter) Entity not of expected type`, is this as expected?
