### ISSUE TITLE
Cannot set --client-secret or --client-secret-setting-name to empty via az-cli

### ISSUE THREAD

**Issue by petetnt** [Azure/azure-cli#22376]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.36.0.

**Related command**
```
 az webapp auth microsoft update --name="service-name" --resource-group="RG" --client-secret-setting-name "" --client-secret "cats-and-dogs"
```

**Describe the bug**
The Azure API cannot set `client-secret` or `client-secret-service-name` if one of those are already set, as seen in 

```
Error: updating Authentication Settings for App Service "metsatilat-staging": web.AppsClient#UpdateAuthSettings: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Cannot set the setting ClientSecret while ClientSecretSettingName is already set. To use ClientSecret instead of ClientSecretSettingName, set setting ClientSecretSettingName to an empty string in the same request that sets ClientSecret for site service-name" Details=[{"Message":"Cannot set the setting ClientSecret while ClientSecretSettingName is already set. To use ClientSecret instead of ClientSecretSettingName, set setting ClientSecretSettingName to an empty string in the same request that sets ClientSecret for site service-name."}
```

Running the following command:

```
 az webapp auth microsoft update --name="service-name" --resource-group="RG" --client-secret-setting-name "" --client-secret "cats-and-dogs"
```

Results in

```
Usage Error: --client-secret and --client-secret-setting-name cannot both be configured to non empty strings
```

Despite client-secret-setting-name being an empty string "".

This also fails the other way around. Additionally when using the `auth-classic` command for v1 setting `--<provider>-client-secret` and `--<provider>-client-secret-setting-name`  seems to do nothing

**To Reproduce**

- Upgrade your app service auth from V1 to v2
- Try to set `client-secret` and see the error
- Add `--client-secret-setting-name`
- Run into the error

**Expected behavior**
The other value is set, the other value is set to null

**Environment summary**
MacOS, az cli 2.36.0

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@petetnt Thank you for reaching out to us, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@petetnt It seems that the error message is misleading, essentially you cannot set both `--client-secret-setting-name --client-secret` together in the same statement. You can use two different statements to update these parameters. 

I will get the error message updated and also the document. Let me know if you have any follow up question.
