### ISSUE TITLE
az aks command invoke failing due to API call returning broken Location

### ISSUE THREAD

**Issue by datadot** [Azure/azure-cli#22375]
**Related command**

az aks command invoke

**Describe the bug**

When running az aks command invoke to run any command eg kubectl get pods -A, the API returns a malformed Location on a 202 response header without the subscription id, causing crash.

Actual invoked command is run on AKS cluster.

**To Reproduce**

az aks command invoke --resource-group <my-rg> --name <my-aks-cluster> --command 'kubectl get pods -A'

**Expected behavior**

Location header to return including Subscription ID and result of invoked command.

**Environment summary**

azure-cli 2.34.1 -> 2.36.0
Tested on Windows 11, Azure DevOps pipeline (Ubuntu), WSL (Ubuntu)

**Additional context**

**Comment by bobalong79** [comment]
Having same issue. Same command was working yesterday.

**Comment by kevinnesta** [comment]
Same issue here. Blocking all our CI/CD

**Comment by harrisonsp** [comment]
We are seeing this too.

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by datadot** [comment]
Thanks @yonzhan 

They seem to have done an API fix - invoke command is working again.

**Comment by navba-MSFT** [comment]
Thanks @datadot for sharing an update. If any further assistance is needed on this, feel free to reopen this thread. We would be happy to help.
