### ISSUE TITLE
update "az sig image-version create --managed-image" for different source

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#22424]
**Related command**

az sig image-version

**Resource Provider**

Az.Compute

**Description of Feature or Work Requested**
Currently when we create sig image from vm/another sig, users need to use "--managed-image" command and that's not precise, user should not use "--managed-image" for any other source except managed image. So we need to update the command and doc: https://docs.microsoft.com/en-us/cli/azure/sig/image-version?view=azure-cli-latest#az-sig-image-version-create

Proposed design:

for VM source:
az sig image-version create --resource-group MyResourceGroup \
--gallery-name MyGallery --gallery-image-definition MyImage \
--gallery-image-version 1.0.0 \
**--virtual-machine** /subscriptions/00000000-0000-0000-0000-00000000xxxx/resourceGroups/imageGroups/providers/Microsoft.Compute/virtualMachines/MyVM

for gallery image version source:
az sig image-version create --resource-group MyResourceGroup \
--gallery-name MyGallery --gallery-image-definition MyImage \
--gallery-image-version 1.0.0 \
**--image-version** /subscriptions/00000000-0000-0000-0000-00000000xxxx/resourceGroups/imageGroups/providers/Microsoft.Compute/galleries/MyGallery/images/MyImageDefinition/versions/1.0.0

**Minimum API Version Required**

this does not need any recent api model change, just need to match it to galleryImageVersion - storageProfile - id
**Swagger Link**

**Target Date**

06/30

**Comment by yonzhan** [comment]
Compute
