### ISSUE TITLE
List all endpoints command requires the ID of a specific endpoint.

### ISSUE THREAD

**Issue by michaelhambe** [Azure/azure-cli#22422]
Hi,

The documentation for “az network private-endpoint-connection list” states that this command will "List all private endpoint connections".

However, the command requires an "--id" parameter and only returns the connection details referenced by the id.

This seems incorrect as the command should return a list of all endpoints (perhaps limited by resource group).

Thanks
Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e4446d-f721-eb1f-2d78-c8e6da619051
* Version Independent ID: e53bdc70-7750-b452-56b8-1caa2d938f0a
* Content: [az network private-endpoint-connection](https://docs.microsoft.com/en-us/cli/azure/network/private-endpoint-connection?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/private-endpoint-connection.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/private-endpoint-connection.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by YuanyuanNi** [comment]
Hi： 
       @michaelhambe As the examples below ,az network private-link-resource list should return all private link resources in a certain range ( --id/ -n -rg -type ):
1:List all private link resources for a storage account.:
az network private-link-resource list -g MyResourceGroup -n MySA --type Microsoft.Storage/storageAccounts
2.List all private link resources for a keyvault:
az network private-link-resource list -g MyResourceGroup -n MyKV --type Microsoft.Keyvault/vaults
3.List all private link resources for an ACR:
az network private-link-resource list --id /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.ContainerRegistry/registries/testreg000002
Best wishes.

**Comment by michaelhambe** [comment]
Thank you @YuanyuanNi,
