### ISSUE TITLE
Support Put disk for Community Gallery and Shared Gallery

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#22425]
**Related command**

az disk create -g MyResourceGroup -n MyDisk --gallery-image-reference

**Resource Provider**

Az.Compute

**Description of Feature or Work Requested**

Currently users can create a disk from gallery image version by:
az disk create -g MyResourceGroup -n MyDisk --gallery-image-reference /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myRG/providers/Microsoft.Compute/galleries/myGallery/images/myImage/versions/1.0.0

and backend match the --gallery-image-reference input to [disk - properties - creationData - galleryImageReference - id]

for community gallery, user can do 
az disk create -g MyResourceGroup -n MyDisk --gallery-image-reference /CommunityGalleries/{communityGalleryPublicGalleryName}/Images/{imageName}/Versions/1.0.0

backend should match the --gallery-image-reference input to [disk - properties - creationData - galleryImageReference - communityGalleryImageId]

for shared gallery/direct sharing, user can do 
az disk create -g MyResourceGroup -n MyDisk --gallery-image-reference /SharedGalleries/{sharedGalleryUniqueName}/Images/{imageName}/Versions/1.0.0

backend should match the --gallery-image-reference input to [disk - properties - creationData - galleryImageReference - sharedGalleryImageId]

**Minimum API Version Required**

2022-03-02

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/18945 (this has not been merged to main, but it should be soon)

**Target Date**

06/30

**Comment by yonzhan** [comment]
Compute
