### ISSUE TITLE
Azure Bastion Deployment fails in westeurope region: Compute allocation failed. Please retry later

### ISSUE THREAD

**Issue by TahaBenseddik** [Azure/azure-cli#22433]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

New-AzBastion : Long running operation failed with status 'Failed'. Additional Info:'Compute allocation failed. Please retry later.' StatusCode: 200 ReasonPhrase: OK Status: Failed ErrorCode: GatewayAllocationFailed ErrorMessage: Compute allocation failed. Please retry later. At line:107 char:20 + $bastion = New-AzBastion -ResourceGroupName $bastionrg ` + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [New-AzBastion], NetworkCloudException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.Bastion.NewAzBastionCommand

**Describe the bug**

The deployment of azure bastion fails in the westeurope region. I have tried to create Azure Bastion through powershell commands and the portal, but it keeps failing. The error is: **Long running operation failed with status 'Failed'. Additional Info:'Compute allocation failed. Please retry later.'** 

**To Reproduce**

New-AzBastion -ResourceGroupName $rg -Name "test-Bastion2" -PublicIpAddress $publicip -VirtualNetwork $vnet

**Expected behavior**

A succesful deployment of Azure Bastion

**Environment summary**

It is run with the Azure Automation Runbook, powershell version 5.1

**Additional context**

**Comment by yonzhan** [comment]
Please open this issue in azure-powershell repo

**Comment by leom-restack** [comment]
Hello, I think this issue needs to be reopened. Im getting similar issue using Powershell Module, Azure Cli and Terraform using the WestEurope region. See below samples.

*Terraform*: 
```
╷
│ Error: waiting for creation/update of Bastion Host: (Name "bastion-test-01" / Resource Group "rg-test-01"): Code="GatewayAllocationFailed" Message="Compute allocation failed. Please retry later." Details=[]
│ 
```

*Azure cli*:
```
PS C:\Users\devBox005> az network bastion create --name "Bastion-Test" --public-ip-address "Bastion-Test-pip" --resource-group "rg-test-01" --vnet-name "vnet-test-01" --location "westeurope"
Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(InternalServerError) An error occurred.
Code: InternalServerError
Message: An error occurred.
```

*Powershell module*:
```
PS C:\Users\devBox007> New-AzBastion -ResourceGroupName "rg-test-01" -Name "Bastion-Test-01" `
>>    -PublicIpAddressRgName "rg-test-01" -PublicIpAddressName "Bastion-Test-pip" `
>>    -VirtualNetworkRgName "rg-test-01" -VirtualNetworkName "vnet-test-01" `
>>    -Sku "Standard"
New-AzBastion: Long running operation failed with status 'Failed'. Additional Info:'An error occurred.'
StatusCode: 200
ReasonPhrase: OK
Status: Failed
ErrorCode: InternalServerError
ErrorMessage: An error occurred.
PS C:\Users\devBox007>
```

What I don't understand is why it keeps the resources even if its in a failed state. See below:

*Sample on the Azure portal*: 
![image](https://user-images.githubusercontent.com/93972728/168835955-d9108bca-4500-4e9c-9720-a7cca746446b.png)
