### ISSUE TITLE
az aks nodepool add --max-count range should be 1, 1000

### ISSUE THREAD

**Issue by s20lee** [Azure/azure-cli#22438]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az aks nodepool add ...  --max-count 1000

**Describe the bug**

az aks nodepool add ...  --max-count 1000  is not allowed due to the validation check (range must be in [1,100]). 
Based on the documentation (https://docs.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest#az-aks-nodepool-add-optional-parameters), it should be range up to 1000. 
**To Reproduce**

az aks nodepool add ... --enable-cluster-autoscaler --max-count 1000 
**Expected behavior**

It should be able to take 1000 as the max-count.
**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@s20lee Thanks for the feedback! We have an open PR that addresses this.

**Comment by s20lee** [comment]
Hi @PramodValavala-MSFT , I see that the PR is now merged. Does it mean it's available in aks-preview extension?

**Comment by PramodValavala-MSFT** [comment]
@s20lee The fix was done to the module shipped as part of Azure CLI itself. It should be part of the next release.
