### ISSUE TITLE
Can you document how to use --linux-fx-version with .net 6.0?

### ISSUE THREAD

**Issue by EmilAlipiev** [Azure/azure-cli#22444]
In the link provided in the article only shows how to do on the Portal but not using Az CLI is not clear. Using "DOTNETCORE|6.0" or "DOTNET|6.0" doesnt work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09a3700-4b7b-6720-bec4-2d07ff96ef23
* Version Independent ID: 7d06e377-4659-b3c5-4b7f-8448cc0c102f
* Content: [az functionapp config](https://docs.microsoft.com/en-us/cli/azure/functionapp/config?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/functionapp/config.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/functionapp/config.yml)
* Service: **azure-functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@EmilAlipiev Ideally "linux_fx_version": "DOTNETCORE|6.0" should work, can you please be more specific and let me know what issue are you facing? if you could share debug log it would help me to troubleshoot the issue further.

**Comment by EmilAlipiev** [comment]
@RakeshMohanMSFT i have had posted the full question on SO here https://stackoverflow.com/questions/72242689/azure-functions-linux-upgrading-from-net-core-3-1-to-net-6-doesnt-upgrade-lin

**Comment by RakeshMohanMSFT** [comment]
@EmilAlipiev `--linux-fx-version "DOTNET|6.0"` this is the correct command to use for .net 6, You can get the supported functionapp linux runtimes with `az functionapp list-runtimes --os linux`

I will get the document updated.

**Comment by panchagnula** [comment]
@RakeshMohanMSFT can this be close or transferred to doc team, since this not an active CLI issue?

**Comment by EmilAlipiev** [comment]
Thats obviously not working see SO post for more please

**Comment by panchagnula** [comment]
> Thats obviously not working see SO post for more please

I understand that - my point being here that this is not CLI specific issue, & hence the documentation needs to be updated. The BADREQUEST is from the API level, so this needs to be routed to the right team.
