### ISSUE TITLE
Azure Security Center is now Microsoft Defender for Cloud

### ISSUE THREAD

**Issue by bmansheim** [Azure/azure-cli#22446]
There may be other locations that require updating as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe5ba99-4e05-2332-7575-949c7944f3fa
* Version Independent ID: 36deb6a4-026a-02a7-5be8-3e4ec5addba8
* Content: [Azure Security Center](https://docs.microsoft.com/en-us/cli/azure/service-page/azure%20security%20center?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/service-page/Azure Security Center.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/service-page/Azure Security Center.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
It seems not related to Azure CLI

**Comment by bmansheim** [comment]
@yonzhan Does that mean that someone else needs to update the branding in https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/service-page/Azure%20Security%20Center.yml?

**Comment by yonzhan** [comment]
You could contact Delora from doc team to help with
