### ISSUE TITLE
Examples won't always work when copy and pasted

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#2246]
After a talk with @twitchax about examples and feedback we've received regarding the ability to copy and paste examples and have them reliably work, I think we might be able to achieve this by making examples a little more dynamic. I think we have a few issues to overcome.
- execution environment (bash, ps, cmd)
- globally defined resources (dns entries -- storage accounts, web apps, etc -- others)
- rules for parameter values (password strength, account name requirements, etc)

If the examples were dynamic enough to produce content for the above criteria, I think we could ensure that example commands would execute reliably (within reason) when copied and pasted.

Thoughts? @Azure/azure-cli

**Comment by yugangw-msft** [comment]
//cc @bradygaster

**Comment by twitchax** [comment]
This is one reason I removed the `\` everywhere.  It is not copypasteable in all shells.

As for the other two, the guidance from on high is still:
* Globally-defined resources: add something in the name that makes it apparent that it is supposed to be unique (e.g., "MyUniqueApp").
* Passwords: leave off examples that show passing a password as a parameter value.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
