### ISSUE TITLE
[Feature Request] Release Azure CLI as ZIP packages

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#22462]
**Is your feature request related to a problem? Please describe.**

Currently Azure CLI on Windows is released as an MSI package. This has several problems:

- The MSI requires admin permission (https://github.com/Azure/azure-cli/issues/15381), which makes it impossible to install Azure CLI as a normal user.
- The installation location is fixed to `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2`, making it impossible to customize the installation location.
- ZIP allows installing multiple versions side-by-side
- Some corporate firewall/policy may block downloading `.exe`, `.msi` (https://github.com/Azure/azure-cli/issues/22447) 
- Updating with MSI is slow and takes several minutes.

**Describe the solution you'd like**

We could release Azure CLI as a portable ZIP packages, like PowerShell releases its ZIP packages at https://github.com/PowerShell/PowerShell/releases.

**Additional context**

As there is no official way to sign a ZIP, we can only use SHA256 to compute the hash of the ZIP and publish the hash along with the ZIP, but there is no way to sign it with Microsoft certificate.

**Comment by l3ender** [comment]
Just curious if this has been prioritized in the backlog? It would greatly ease the onboarding pain for organizational users which often have limited access to their environment. Thanks!

**Comment by l3ender** [comment]
Hello--is there any update on this issue?
