### ISSUE TITLE
CLI Update for Azure Stack HCI 2022-05-01 Release

### ISSUE THREAD

**Issue by lsweeney24** [Azure/azure-cli#22470]
**Resource Provider**

AzureStackHCI

**Description of Feature or Work Requested**

We want to update our CLI based on the swagger. 

**Swagger and PR link**
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI/stable/2022-05-01 

https://github.com/Azure/azure-rest-api-specs/pull/18851

**Target Date**
May 31, 2022

**Comment by yonzhan** [comment]
AzureStackHCI

**Comment by zhoxing-ms** [comment]
@lsweeney24 Hi, since our work in this sprint has been fully arranged, we don't have enough time to support more requirements. Can this feature request be postponed to the release of the next sprint (**08-02**)?

**Comment by zhoxing-ms** [comment]
@lsweeney24 I‘d like to confirm with you whether we only need to upgrade the api-version for `Microsoft.AzureStackHCI` or we need to add new commands/parameters?

**Comment by lsweeney24** [comment]
Hello,

We will need both an Api version upgrade and new commands. Here is an example of the desired changes based on the PowerShell cmdlets we just had released - https://github.com/Azure/azure-powershell/pull/18559
[https://opengraph.githubassets.com/8efb8043bef1d804aa3076fb337df9540e5b0825f5723cc4b0d9b5c305dcecc0/Azure/azure-powershell/pull/18559]<https://github.com/Azure/azure-powershell/pull/18559>
Generation of the stackhci ps cmdlets by lsweeney24 · Pull Request #18559 · Azure/azure-powershell<https://github.com/Azure/azure-powershell/pull/18559>
Description Using autorest to automatically create the cmdlets for the stackhci rp. Adding in tests for all cmdlets exposed to a customer. Checklist I have read the Submitting Changes section of ...
github.com



Thanks,

Luke



________________________________

**Comment by zhoxing-ms** [comment]
@lsweeney24 May I ask do you want CLI to add some new specific commands, or do you want CLI to support all the contents defined in Swagger?

**Comment by PARADISSEEKR** [comment]
Hi @lsweeney24 , when creates a Stack HCI cluster, how to get [AadTenantId, AadClientId and CloudManagementEndpoint ](https://github.com/Azure/azure-powershell/pull/18559/files#diff-108d24ddc4d9bec48b817e51e432e54b9d5b46210a0ffa9bcac70106f35e3420) in CLI, we need to add automated tests for it 
[request body](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI/stable/2022-05-01/examples/CreateCluster.json#L10-L12)

**Comment by lsweeney24** [comment]
Hello,


For the AAD tenant id this is just the value for the tenant you would be testing in example “"AadTenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47",”. For the AAD client id this can be any GUID string for testing purposes but it must be a valid GUID. Lately, the CloudManagementEndpoint is an optional parameter, but this would just be the ARM endpoint for that region, example “https://management.azure.com/”


Thanks,

Luke

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by PARADISSEEKR** [comment]
Hi @lsweeney24 , The return value of  `az stack-hci cluster upload-certificate` and `az stack-hci extension update` form service is wrong(Operation returned an invalid status 'OK', [error](https://github.com/Azure/azure-cli-extensions/pull/5132/files#diff-bd591a247bc308f09abca52167a77d46d49e40aca784c6f4a3aceeda513138df)), could you please fix it, or remove it as before?

**Comment by lsweeney24** [comment]
Hello, we don’t need these cmdlets implemented, so that is ignorable. Here is a reference to what cmdlets we are looking for


Using this PR - https://github.com/Azure/azure-powershell/pull/18559, the cmdlets we don’t want are “Update-AzStackHciExtension”, “Invoke-AzStackHciUploadClusterCertificate”, “New-AzStackHciArcSettingPassword”, “Update-AzStackHciArcSetting”. The rest from the Swagger spec are good.

Thanks,
Luke

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lsweeney24** [comment]
Hello,

We will want certain commands not included but the rest from the Swagger spec are fine.

Using this PR - https://github.com/Azure/azure-powershell/pull/18559, the cmdlets we don't want are "Update-AzStackHciExtension", "Invoke-AzStackHciUploadClusterCertificate", "New-AzStackHciArcSettingPassword", "Update-AzStackHciArcSetting". The rest from the Swagger spec are good.


Thanks,
Luke
