### ISSUE TITLE
Its unclear where command to do a template deployment lives

### ISSUE THREAD

**Issue by scotmoor** [Azure/azure-cli#2247]
From the output of the "az" command below, it's not clear or intuitive that the command to execute a deployment via an ARM template lives under the **"group"** base command. In fact, since we're creating resources, it would seem reasonable that it would live under the **"resource"** base command but it doesn't. While I personally believe template deployment should be it's own "base" command, if you're going to put it under another base command, then you should at least reference it in the description text of that base command.

"az" output:

    account   : Commands to manage subscriptions.
    acs       : Commands to manage Azure Container Services.
    ad        : Synchronize on-premises directories and manage Azure Active Directory (AAD)
                resources.
    appservice: Commands to manage your Azure web apps and App Service plans.
    batch     : Commands for working with Azure Batch.
    cloud     : Manage the Azure clouds registered.
    component : Commands to manage and update Azure CLI 2.0 (Preview) components.
    configure : Configure Azure CLI 2.0 Preview or view your configuration. The command is
                interactive, so just type `az configure` and respond to the prompts.
    container : Set up automated builds and deployments for multi-container Docker applications.
    disk      : Commands to manage 'Managed Disks'.
    documentdb: Commands to manage your Azure DocumentDB (NoSQL) database accounts.
    feature   : Commands to manage resource provider features, such as previews.
    feedback  : Loving or hating the CLI?  Let us know!
    group     : Commands to manage resource groups.
    image     : Commands to manage custom virtual machine images based on managed disks/snapshots.
    iot       : Commands to connect, monitor, and control millions of IoT assets.
    keyvault  : Safeguard and maintain control of keys, secrets, and certificates.
    lock
    login     : Log in to access Azure subscriptions.
    logout    : Log out to remove access to Azure subscriptions.
    network   : Manages Network resources.
    policy    : Commands to manage resource policies.
    provider  : Manage resource providers.
    redis     : Access to a secure, dedicated cache for your Azure applications.
    resource  : Generic commands to manage Azure resources.
    role      : Use role assignments to manage access to your Azure resources.
    snapshot  : Commands to manage snapshots.
    sql       : Commands to manage Azure SQL databases.
    storage   : Durable, highly available, and massively scalable cloud storage.
    tag       : Manage resource tags.
    vm        : Provision Linux and Windows virtual machines in minutes.
    vmss      : Create highly available, auto-scalable Linux or Windows virtual machines.

**Comment by brendandburns** [comment]
See:
https://github.com/Azure/azure-cli/pull/2466/files
