### ISSUE TITLE
[Stream Analytics] Update 2020 version with Azure Function and Blob MSI

### ISSUE THREAD

**Issue by roslynlu** [Azure/azure-cli#22482]
**Related command**
az stream-analytics

**Is your feature request related to a problem? Please describe.**
We updated our swagger specs recently to fix some s360 bugs, and we would like our CLI to reflect those bug fixes: https://github.com/Azure/azure-rest-api-specs/pull/17697

**Describe the solution you'd like**
Update Stream Analytics CLI to include these new features (Azure Function and Blob MSI)

**Describe alternatives you've considered**
N/A

**Additional context**
Swagger: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/streamanalytics/resource-manager/Microsoft.StreamAnalytics/stable/2020-03-01
Documentation: https://docs.microsoft.com/en-us/azure/stream-analytics/

**Comment by yonzhan** [comment]
Stream Analytics

**Comment by jsntcy** [comment]
@roslynlu, is this feature request same as #22481?
