### ISSUE TITLE
Update "az sig gallery-application version" to include new parameter

### ISSUE THREAD

**Issue by D1v38om83r** [Azure/azure-cli#22499]
**Related command**
az sig 

**Resource Provider**
Microsoft.Compute

**Description of Feature or Work Requested**
Command to update, new parameters in **bold** 

az sig gallery-application version create
--application-name
--gallery-name
--install-command
--name
--package-file-link
--remove-command
--resource-group
[--default-file-link]
[--end-of-life-date]
**[--package-file-name]
[--config-file-name]**
[--exclude-from {false, true}]
[--location]
[--no-wait]
[--tags]
[--target-regions]
[--update-command]

Description:
PackageFileName - The file to rename the downloaded package to on the VM. If not present, then the file will be called . This is limited to 4096 characters.
ConfigFileName - The file to rename the downloaded config to on the VM. If not present, then the file will be called _config. This is limited to 4096 characters.
Note that PackageFileName and ConfigFileName are not updateable, hence they are not present on Update-AzGalleryApplicationVersion.

**Minimum API Version Required**
2022-01-03

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/18722

**Target Date**
2022-06-15

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@D1v38om83r Hi, since our work in this sprint has been fully arranged, we don't have enough time to support more requirements. Can this feature request be postponed to the release of the next sprint (**08-02**)?

**Comment by D1v38om83r** [comment]
I can't afford it being postponed, our GA date is June 30th.
