### ISSUE TITLE
az webapp identity assign wipes out access restrictions

### ISSUE THREAD

**Issue by alin-devnet** [Azure/azure-cli#22495]
**Related command**
`az webapp identity assign -g resourceGroupName -n resourceName --identities [system]`

**Describe the bug**
Enabling system managed identity for an Azure App Service wipes out access restrictions. This started happening recently, was fine 1-2 weeks ago. 

**To Reproduce**
Add an access restriction to an azure app service. 
Enable system managed identity for the app service by running the `az webapp identity assign` command.

**Expected behavior**
Access restrictions should remain.

**Comment by gavinbarron** [comment]
Another data point here. We first observed access restrictions being removed from some of our resources on May 13th PDT. 

We had a number of other changes which we had initially attributed this issue to and had only just ruled them out today when I found this issue.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by peter-banks** [comment]
Also ran into this problem yesterday. From what I can tell its the resource manager returning an incorrect `ipSecurityRestrictions` property value, you can verify this by using resources.azure.com.

**Comment by BrunoDrljanovcan** [comment]
Also ran into this problem today, setting the identity manually is working as expected but using this CLI command it is removing all the network access rules for the webapp.

**Comment by panchagnula** [comment]
@calvinsID can you take a loo at this - might be the similar fix you did for update with access-restrictions properties being cleaned up by API PUT call - we might need to do a GET first for this command as well?

**Comment by zoeperryman** [comment]
This is a rather big issue for us as our deployments are now randomly removing the access restrictions and opening up what should be private services to the public internet.

I first found the issue setting the managed identity like this issue describes, but then found that some of our later scripts added a tag to the web app and that was also wiping the access restrictions. Both of these commands below appear to wipe the access restrictions. 

```sh
az resource tag --tags MyTag=MyValue -g my-rg -n my-web-app --resource-type "Microsoft.Web/sites"
```

```sh
az webapp update -g my-rg -n my-web-app --set tags.MyTag=MyValue
```

I noticed this about a week ago, it didn't seem to matter what cli version I used (had an old one and updated to the latest, both have the same problem)

**Comment by panchagnula** [comment]
> This is a rather big issue for us as our deployments are now randomly removing the access restrictions and opening up what should be private services to the public internet.
> 
> I first found the issue setting the managed identity like this issue describes, but then found that some of our later scripts added a tag to the web app and that was also wiping the access restrictions. Both of these commands below appear to wipe the access restrictions.
> 
> ```shell
> az resource tag --tags MyTag=MyValue -g my-rg -n my-web-app --resource-type "Microsoft.Web/sites"
> ```
> 
>  ```shell
> az webapp update -g my-rg -n my-web-app --set tags.MyTag=MyValue
> ```
> 
> I noticed this about a week ago, it didn't seem to matter what cli version I used (had an old one and updated to the latest, both have the same problem)

@madsd /can we get some one from the feature team take a look as to why access-restrictions is being overridden when adding tags. Given this has the same experience, looks more to do with API than client az resource tag --tags MyTag=MyValue -g my-rg -n my-web-app --resource-type "Microsoft.Web/sites"

**Comment by ishepherd** [comment]
@panchagnula @madsd  This is a security bug which caused access restrictions to be removed from some apps deployed on Azure. We happened to notice but other Azure customers might not have.

Therefore please handle appropriately
* Please try to work out who is affected, and let them know.
* Please conduct a root cause analysis and take action to prevent it recurring.

**Comment by panchagnula** [comment]
> @panchagnula @madsd This is a security bug which caused access restrictions to be removed from some apps deployed on Azure. We happened to notice but other Azure customers might not have.
> 
> Therefore please handle appropriately
> 
> * Please try to work out who is affected, and let them know.
> * Please conduct a root cause analysis and take action to prevent it recurring.

@ishepherd if we need security analysis, could you please create an ICM for the team to track the ask, instead of the gitHub issue, so the @madsd & the right feature owners can do the needful, instead of using the CLI GitHub issue to track.

**Comment by madsd** [comment]
@ishepherd yes, please raise a support incident/IcM for this. I suspect this is something in control plane and therefore a CLI issue is not the right way to route this to the appropriate team.

**Comment by madsd** [comment]
@alin-devnet @ishepherd this issue should have been mitigated. Sorry for the inconvenience.

**Comment by panchagnula** [comment]
Closing this since we got confirmation from the feature team.

**Comment by ishepherd** [comment]
@madsd @panchagnula Thanks for your investigation.

I'm glad to see the feature team sent out a security advisory. Copying it here for anyone who lands here in future

----

> ### [URGENT] Action Required: Reapply your Azure App Service access configuration settings
> You're receiving this message because our records indicate that you have deployed an Azure App Service that could be affected by this configuration issue.

> Azure App Service deployed an update that contained a code regression which may have reverted existing IP restrictions configured on some Azure App Service deployments. As a result, some of your Azure App service deployments may have been exposed to public internet access after 06 May 2022. We mitigated this issue by deploying a fix on 25 May 2022. The issue only affects customers that programmatically applied access restrictions (not through the Azure portal) to their site resources after 06 May 2022.

> Further immediate action is required by you.

>

> Action Required

> In order to safeguard your Azure App Service resources from public access, you must reapply your [Azure App Service access restrictions](https://docs.microsoft.com/azure/app-service/app-service-ip-restrictions).

> 
> A list of affected App Service resource IDs has been emailed to administrators and owners of the affected Azure subscriptions.

>
> If you have any questions or concerns, please open a support case through the Azure Portal at [aka.ms/azsupt](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview) referencing tracking ID (redacted)
