### ISSUE TITLE
Quotes in --set parameter of redis update command given in the doc looks inaccurate 

### ISSUE THREAD

**Issue by evanlwj** [Azure/azure-cli#22498]
[Enter feedback here]

I followed [az redis update](https://docs.microsoft.com/en-us/cli/azure/redis?view=azure-cli-latest#az-redis-update) doc to update shardCount for an existing redis instance.

If double quotes are included in --set parameter like *--set "shardCount"="1"*, An usage error promoted to me

```
az redis update --subscription xxxxxx --name {my redis} --resource-group {my resourcegroup} --set "shardCount"="1" --output json
usage error: Empty key in --set. Correct syntax: --set KEY=VALUE [KEY=VALUE ...]
```

If try this, another error promoted to me
```
az redis update --subscription xxxxxx --name {my redis} --resource-group {my resourcegroup} --set \"shardCount\"=\"1\" --output json
Property '\shardCount\' not found on root. Send it as an additional property .
(InvalidRequestContent) The request content was invalid and could not be deserialized: 'Could not find member '\shardCount\' on object of type 'ResourceDefinition'. Path '['\\shardCount\\']', line 1, position 359.'.
Code: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Could not find member '\shardCount\' on object of type 'ResourceDefinition'. Path '['\\shardCount\\']', line 1, position 359.'.
```

If --set doesn't include double quotes like *--set shardCount=1*, command worked for me and updated the redis instance with a desired shard count in couple minutes later.

`az redis update --subscription xxxxxx --name {my redis} --resource-group {my resourcegroup} --set shardCount=1 --output json`

Thus, I am wondering the sample command with double quotes in --set parameter below in the doc is inaccurate.

`az redis update --name MyRedisCache --resource-group MyResourceGroup --set "shardCount"="2"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb66426-9b0f-be54-5530-0673e6821f39
* Version Independent ID: 3d89a838-9a95-3cfe-ea58-7d7484e94956
* Content: [az redis](https://docs.microsoft.com/en-us/cli/azure/redis?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/redis.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/redis.yml)
* Service: **cache**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@evanlwj Thanks for reaching out to us and reporting this issue. We are looking into this issue. We will provide an update once we get a chance.

**Comment by navba-MSFT** [comment]
@evanlwj Thanks for sharing the feedback. The above PR has been filed to address this issue. It is currently under review phase. In the meantime, if you have any questions, please let us know. We would be happy to help.

**Comment by evanlwj** [comment]
Thanks for an update. Just a reminder, I guessed --set "sku.capacity"="2" might have the similar issue (I didn't verify it myself).
