### ISSUE TITLE
Automation: persist command help documentation and detect changes between commits.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#2249]

**Comment by oakeyc** [comment]
https://github.com/oakeyc/azure-cli/pull/8

**Comment by troydai** [comment]
http://www.reactiongifs.com/r/2013/05/Ron-Paul_Its-Happening1.gif

**Comment by troydai** [comment]
![](http://www.reactiongifs.com/r/2013/05/Ron-Paul_Its-Happening1.gif)
