### ISSUE TITLE
Azure Bastion - ERROR: Compute allocation failed. Please retry later - InternalServerError

### ISSUE THREAD

**Issue by leom-restack** [Azure/azure-cli#22496]
Hello, I think this issue needs to be reopened. Im getting similar issue using Powershell Module, Azure Cli and Terraform using the WestEurope region. See below samples.

*Terraform*: 
```
╷
│ Error: waiting for creation/update of Bastion Host: (Name "bastion-test-01" / Resource Group "rg-test-01"): Code="GatewayAllocationFailed" Message="Compute allocation failed. Please retry later." Details=[]
│ 
```

*Azure cli*:
```
PS C:\Users\devBox005> az network bastion create --name "Bastion-Test" --public-ip-address "Bastion-Test-pip" --resource-group "rg-test-01" --vnet-name "vnet-test-01" --location "westeurope"
Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(InternalServerError) An error occurred.
Code: InternalServerError
Message: An error occurred.
```

*Powershell module*:
```
PS C:\Users\devBox007> New-AzBastion -ResourceGroupName "rg-test-01" -Name "Bastion-Test-01" `
>>    -PublicIpAddressRgName "rg-test-01" -PublicIpAddressName "Bastion-Test-pip" `
>>    -VirtualNetworkRgName "rg-test-01" -VirtualNetworkName "vnet-test-01" `
>>    -Sku "Standard"
New-AzBastion: Long running operation failed with status 'Failed'. Additional Info:'An error occurred.'
StatusCode: 200
ReasonPhrase: OK
Status: Failed
ErrorCode: InternalServerError
ErrorMessage: An error occurred.
PS C:\Users\devBox007>
```

What I don't understand is why it keeps the resources even if its in a failed state. See below:

*Sample on the Azure portal*: 
![image](https://user-images.githubusercontent.com/93972728/168835955-d9108bca-4500-4e9c-9720-a7cca746446b.png)

I also requested the below issues be reopened as the issue is similar:

https://github.com/Azure/azure-cli/issues/21678#issuecomment-1128947414
https://github.com/Azure/azure-powershell/issues/18155#issuecomment-1128953059
https://github.com/Azure/azure-cli/issues/22433#issuecomment-1128960016

**Comment by yonzhan** [comment]
route to CXP team

**Comment by GeneralGorgonzola** [comment]
Also fails in region east-us:

`az network bastion create --name test-bastion --public-ip-address test-ip --resource-group test-group --vnet-name test-vnet --sku Standard --location eastus`

Gives:
`ERROR: (GatewayAllocationFailed) Compute allocation failed. Please retry later.
Code: GatewayAllocationFailed
Message: Compute allocation failed. Please retry later.`

Or:
`ERROR: (InternalServerError) An error occurred.
Code: InternalServerError
Message: An error occurred.`

**Comment by navba-MSFT** [comment]
@leom-restack @GeneralGorgonzola Apologies for the late reply. Thanks for reaching out to us and reporting this issue. 

The `Compute allocation failed` error message would occur when there is a capacity related resource crunch in that particular region. During such issues, you can wait for sometime and then retry the operation. Alternatively you could also try to create the resource in some other region. 

If its a production down issue, you could also open a support ticket so that our support professionals can reach out to the product group team in the background to fix the issue on priority.

**Comment by navba-MSFT** [comment]
@leom-restack I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you have any pending queries. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@leom-restack I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you have any follow-up queries. Awaiting your reply.

**Comment by GeneralGorgonzola** [comment]
@navba-MSFT 
It works now.
It seems to have improved significantly sometime last week.
I also noticed that cleaning up resources is a lot faster now.

**Comment by navba-MSFT** [comment]
@GeneralGorgonzola Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
