### ISSUE TITLE
Update "az vm application set" and "az vmss application set" to include new parameters

### ISSUE THREAD

**Issue by D1v38om83r** [Azure/azure-cli#22501]
**Related command**
az vm

**Resource Provider**
microsoft.compute

**Description of Feature or Work Requested**
New parameters in bold

az vm application set --app-version-ids
[--app-config-overrides]
[--ids]
[--name]
[--order-applications]
**[--treat-deployment-as-failure]**
[--resource-group]

az vmss application set --app-version-ids
[--app-config-overrides]
[--ids]
[--name]
[--order-applications]
**[--treat-deployment-as-failure]**
[--resource-group]

Description:
--treat-deployment-as-failure 
This optional parameter is used to specify space separated 'true' or 'false' items. The same number of items must be the same as application version ids. This property is mapped to application version ids by the relative position of the items. If true, any failure for any operation in the VmApplication referenced by the application version id will fail the deployment. If the optional parameter is not set, it is the equivalent of passing a list of items that is all 'false'. 

**Minimum API Version Required**
2022-03-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/18609/files

**Target Date**
2022-06-15

**Comment by yonzhan** [comment]
Compute

**Comment by D1v38om83r** [comment]
I can't afford it being postponed, our GA date is June 30th.
