### ISSUE TITLE
az bicep decompile --force argument is unrecognized

### ISSUE THREAD

**Issue by madsaune** [Azure/azure-cli#22505]
## Describe the bug

The `az bicep decompile` will suggest to use `--force` when decompiling to an already existing `.bicep` file. The `--force` argument does not exist on `az bicep decompile` and throws an `unrecognized argument: --force`.

**Command Name**
`az bicep decompile`

**Errors:**
```
unrecognized arguments: --force
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az bicep decompile --file "existing_arm.json"`
- Now you will have a `existing_arm.bicep` file
- Make some changes to `exiting_arm.json` and run the decompile command again
- This will throw the following error: `The output path "/Users/user1/code/existing_arm.bicep" already exists. Use --force to overwrite the existing file.`
- `az bicep decompile --file "existing_arm.json" --force`
- You will get the `unrecognized arguments: --force` error

## Expected Behavior

Either `--force` should exists as an argument, or the command should not suggest using `--force`.

## Environment Summary
```
macOS-12.3.1-x86_64-i386-64bit, Darwin 21.4.0
Python 3.10.4
Installer: HOMEBREW

azure-cli 2.36.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by robinmalik** [comment]
Hitting this too.

```
Windows 10 21H2 Build 19044.1706
bicep cli 0.6.18.56646
```

**Comment by RakeshMohanMSFT** [comment]
@madsaune Apologies for the delay! we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@madsaune This is fixed in the latest version, can you please upgrade to the latest version of cli [2.38.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)

**Comment by madsaune** [comment]
Can confirm it works in latest version 2.38.0 of azure-cli on my system. Thank you very much!

```
macOS-12.4-x86_64-i386-64bit, Darwin 21.5.0
Python 3.10.5
Installer: HOMEBREW

azure-cli 2.38.0
```
