### ISSUE TITLE
Update/Fix help text for "az vm application set" and "az vmss application set" parameter --order-applications

### ISSUE THREAD

**Issue by D1v38om83r** [Azure/azure-cli#22502]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az vm application set
az vmss application set

**Describe the bug**
Documentation for the parameter --order-applications has a grammatical error and is unclear. The text should be as follows.

--order-applications

Whether to set order index at each gallery applications. If specified, the first app version id get specified an order = 1, then next one 2, and so on. This parameter is meant to be used when the VMApplications specified by app version ids must be installed in a particular order; lowest order is installed first. 

**To Reproduce**
N/A only documentation update required

**Expected behavior**
N/A only documentation update required

**Environment summary**
N/A only documentation update required

**Additional context**
N/A only documentation update required

**Comment by yonzhan** [comment]
Compute
