### ISSUE TITLE
az ssh vm only works when VM has public IP

### ISSUE THREAD

**Issue by jaypee1990** [Azure/azure-cli#22509]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az ssh vm -n <vmname> -g <rgname>
az ssh vm --ip <privateip>
az ssh vm -n <vmname> -g <rgname> --prefer-prviate-ip

**Describe the bug**
Trying to SSH from Azure cloud shell into Azure Linux VM using AADSSHLoginForLinux extension using above commands however it doesnt work and needs a public IP instead. 

**To Reproduce**
Using a VM with only private IP and using above commands, it doesnt work. But as soon as you use a public IP, it starts working.

**Expected behavior**
Its expected to let me login to VM from cloud shell using the private IP instead of having to connect a public IP to the VM NIC.
I believe it works if you have private connectivity to your VM using VPN or ER, but not from cloud shell. My understanding was it uses azure backbone to connect to the VM if Im to use cloud shell-
**Environment summary**

**Additional context**

<img width="367" alt="with PIP" src="https://user-images.githubusercontent.com/98926476/169046123-cf7a67fd-1f55-454a-9826-19eb04553ae5.PNG">
<img width="783" alt="without pip" src="https://user-images.githubusercontent.com/98926476/169046552-ebff49b9-caca-44fc-ac79-ceca6dfecb20.PNG">

**Comment by maertendMSFT** [comment]
@jaypee1990, Cloud Shell does not have any additional visibility to the private IP address. You can use Cloud Shell in a VNET to access the machine over a private IP, but the default Cloud Shell experience does cannot view into the VNET and does not use any Azure backbone.
