### ISSUE TITLE
Kodi crashing

### ISSUE THREAD

**Issue by Alonzoxxx** [Azure/azure-cli#22512]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by Alonzoxxx** [comment]
kodi crashes upon interaction with addons

**Comment by yonzhan** [comment]
Please provide detailed CLI command and error message.
