### ISSUE TITLE
Source Config using SKU Y1

### ISSUE THREAD

**Issue by Condabas** [Azure/azure-cli#22514]
## Describe the bug

When trying to use this CLI command with a Linux Function App using the "Y1" sku, it fails. If we change the sku to EP1, it completes. 

**Command Name**
`az functionapp deployment source config`

**Errors:**
```
Operation returned an invalid status 'Bad Request'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config --branch {} --name {} --repo-url {} --resource-group {} --git-token {} --debug`

az functionapp deployment source config --branch development --name "adosnow-functionapp" --repo-url "https://github.com/Seagen/ado-sync-functions" --resource-group "ets-dev-westus3-snow_ado_integration-rg01" --git-token "ghp_xxxx"

## Expected Behavior

command to complete successfully - 200

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.0 *

Extensions:
account 0.2.2

```

**Comment by RakeshMohanMSFT** [comment]
@Condabas Thank you for reaching out to us, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@Condabas can you confirm if the bad request is showing this error message in the logs? `There was a conflict. Conflict with existing ScmType: GitHub`. If so please delete the existing source control configuration using this API https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/delete-source-control#code-try-0 and try again. If not please share the --debug trace with us for further troubleshooting. 

Note: Please update to the latest version of Azure CLI [2.36.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
