### ISSUE TITLE
 az vm extension list to include support "--ids"

### ISSUE THREAD

**Issue by Klaas-** [Azure/azure-cli#22527]
**Related command**

`az vm extension list --help`

**Is your feature request related to a problem? Please describe.**

I prefer to use IDs of VMs instead of --subscription ... --resource-group ... --vm-name ...

**Describe the solution you'd like**

All (most?) other commands support an ID, for example `az vm extension show --help`

**Describe alternatives you've considered**

I can split an ID into subscription, resource group and vm-name, but I'd like azure-cli to be consistent with allowing ids.

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@Klaas- Since our work in this sprint has been fully arranged, I plan to schedule this requirement for development and release in the next sprint (**09-06**). Can you accept this time?
