### ISSUE TITLE
az logicapp command not found

### ISSUE THREAD

**Issue by MrMoshkovitz** [Azure/azure-cli#22526]
[Enter feedback here]
Command Not Existed
![image](https://user-images.githubusercontent.com/50079480/169265080-4a851157-3f45-4de7-b0fe-60e24eb4bf65.png)
```
az: 'logicapp' is not in the 'az' command group. See 'az --help'. If the command is from an extension, please make sure
the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/
cli/azure/azure-cli-extensions-overview
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e21e02-e42f-a0aa-e437-0ec8e73ab81b
* Version Independent ID: 29316eb6-a99d-6ccf-6e4d-5e352e391c31
* Content: [az logicapp](https://docs.microsoft.com/en-us/cli/azure/logicapp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/logicapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/logicapp.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@MrMoshkovitz can you please let us know which version of CLI are you using? please install latest CLI [2.36.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli)
