### ISSUE TITLE
`az lock create`: `properties.owners` is not supported

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#22528]
**Related command**
`az lock create`

**Describe the bug**

[Management Locks - Create Or Update At Resource Group Level](https://docs.microsoft.com/en-us/rest/api/resources/management-locks/create-or-update-at-resource-group-level) API has `properties.owners` which is a list of `ManagementLockOwner`s.

![image](https://user-images.githubusercontent.com/4003950/169281520-08321510-1663-4d54-8d5e-9335f6766248.png)

However, there is no corresponding CLI argument to set this property:

```
> az lock create -h

Command
    az lock create : Create a lock.
        Locks can exist at three different scopes: subscription, resource group and resource.
        For how to add locks at different levels, please refer to the following examples.

Arguments
    --lock-type -t  [Required] : The type of lock restriction.  Allowed values: CanNotDelete,
                                 ReadOnly.
    --name -n       [Required] : Name of the lock.
    --namespace                : Provider namespace (Ex: 'Microsoft.Provider').
    --notes                    : Notes about this lock.
    --parent                   : The parent path (Ex: 'resA/myA/resB/myB').
    --resource --resource-name : Name or ID of the resource being locked. If an ID is given, other
                                 resource arguments should not be given.
    --resource-group -g        : Name of resource group. You can configure the default group using
                                 `az configure --defaults group=<name>`.
    --resource-type            : The resource type (Ex: 'resC'). Can also accept namespace/type
                                 format (Ex: 'Microsoft.Provider/resC').
```

Manually setting this property gives a vague error message with a broken link https://aka.ms/arm-lock :

```
$ az rest -m PUT --url https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/rgtest1/providers/Microsoft.Authorization/locks/dl?api-version=2016-09-01 -b '{"properties": {"level": "CanNotDelete", "owners":[{"applicationId":"233dd73b-72e3-424a-9367-7588d957267e"}]}}'
Unauthorized({"error":{"code":"UnauthorizedApplicationId","message":"Application '233dd73b-72e3-424a-9367-7588d957267e' is not allowed to add 'Owners' for management lock 'dl'. Please see https://aka.ms/arm-lock for detail."}})
```

**Comment by yonzhan** [comment]
ARM

**Comment by jiasli** [comment]
Explanation from ARM service team:

> The usage of the `owners` parameter is limited only for specific applications within Azure. This is not a mandatory field and it will be used directly by Azure on internal specific applications.
>
> Having that said, it is not expected that customer uses it. In fact, if we review the public documentation for Lock creation https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources, there is no reference of this parameter and their need to use. Same can be used when using PS/CLI: https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azresourcelock?view=azps-8.0.0 / https://docs.microsoft.com/en-us/cli/azure/lock?view=azure-cli-latest#az-lock-create

I feel the REST API spec should remove it or at least explain this is an Azure-internal property.

**Comment by jennyhunter-msft** [comment]
@tfitzmac - Is updating the REST API spec in your realm, or do we need to update the related Swagger?
