### ISSUE TITLE
I got an error while trying to install the kubectl tool on cloudshell. Is there an alternative way to achieving that? The command I used was "az aks install-cli --install-location=./kubectl"

### ISSUE THREAD

**Issue by haybeewhy** [Azure/azure-cli#22536]
## Describe the bug

**Command Name**
`az aks install-cli`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: '/usr/local/bin/kubelogin'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/tmp/tmpiqroks6p/bin/linux_amd64/kubelogin' -> '/usr/local/bin/kubelogin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 369, in k8s_install_cli
    k8s_install_kubelogin(cmd, kubelogin_version,
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/acs/custom.py", line 496, in k8s_install_kubelogin
    shutil.move(download_path, install_location)
  File "/opt/az/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/opt/az/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/az/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/kubelogin'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks install-cli --install-location={}`

## Environment Summary
```
Linux-5.4.0-1078-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.8.13
Installer: DEB

azure-cli 2.36.0

Extensions:
ai-examples 0.2.5
ssh 1.1.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@haybeewhy Thanks for reaching out to us and sharing this feedback. We are looking into this issue. We will provide an update once we have more details.

**Comment by navba-MSFT** [comment]
@haybeewhy Apologies for the late reply. The error is documented [here](https://docs.microsoft.com/en-gb/azure/cloud-shell/troubleshooting#user-permissions). This issue would occur if you don't have the full access to the installing folder. 

So you can follow the below steps to install in Cloud Shell:

To install kubectl (specific version) in a specified path in the home folder, for example:

>XXXX/Azure:~$ az aks install-cli --install-location **mykubetools**/kubectl1.23.5 --client-version 1.23.5 --kubelogin-install-location **mykubetools**/kubelogin

**Output:**
>Downloading client to "mykubetools/kubectl1.23.5" from [https://storage.googleapis.com/kubernetes-release/release/v1.23.5/bin/linux/amd64/kubectl]
Please ensure that mykubetools is in your search PATH, so the kubectl1.23.5 command can be found.
Downloading client to "/tmp/tmps1qp6p1e/kubelogin.zip" from [https://github.com/Azure/kubelogin/releases/download/v0.0.11/kubelogin.zip]

Please ensure that **mykubetools** is in your search PATH, so the kubelogin command can be found.

>XXXX/Azure:~$ ./mykubetools/kubectl1.19.1 version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Hope this helps. Please let me know if you have any further questions on this.

**Comment by navba-MSFT** [comment]
@haybeewhy I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@haybeewhy The action is currently pending on you to follow the above plan. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
