### ISSUE TITLE
Azure CLI login issue: Error building AzureRM Client: Azure CLI Authorization Profile was not found

### ISSUE THREAD

**Issue by ugurtaftali** [Azure/azure-cli#22530]
**Related command**

**Resource Provider**

**Description of Feature or Work Requested**

**Minimum API Version Required**

**Swagger Link**

**Target Date**

**Comment by jiasli** [comment]
Please provide more info for us to investigate. Thanks.

**Comment by jiasli** [comment]
> When I tried to run a terraform script on Azure CLI

Could you further explain how this is done? If this is terraform issue, you may refer to https://github.com/Azure/azure-cli/issues/14778 or report to https://github.com/hashicorp/terraform-provider-azurerm

**Comment by ugurtaftali** [comment]
Actually, I'm able to run another module of the same terraform script in the same Azure CLI. But for this module I keep getting this error. Can it be a compatibility issue? 
Azure RM version is 2.11.0
Azure CLI version is 2.34.1

**Comment by jiasli** [comment]
> I'm able to run another module of the same terraform script in the same Azure CLI.

Could you share the command and terraform script you used? 

This issue looks more like a terraform issue to me, instead of Azure CLI.

**Comment by ugurtaftali** [comment]
This is just a part of first module which works fine:
provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  features{}
}

terraform {
  backend "azurerm" {}
}


resource "azurerm_resource_group" "rg" {
  name     = "${var.resource_group}"
  location = "${var.location}"
}

**Comment by ugurtaftali** [comment]
provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  features{}
}

terraform {
  backend "azurerm" {}
  required_providers {
    azurerm={
      source="hashicorp/azurerm"
      version="=2.11.0"
    }
  }
}

resource "azurerm_resource_group" "rg" {
  name     = "${var.resource_group}"
  location = "${var.location}"
}

**Comment by ugurtaftali** [comment]
terraform init -backend-config=".\backend.tfvars" 
terraform plan

These are the commands

**Comment by ugurtaftali** [comment]
Terraform version is v1.1.6

**Comment by jiasli** [comment]
I am afraid this is not a problem of Azure CLI. You may feel free to reach out to Terraform: https://github.com/hashicorp/terraform-provider-azurerm
