### ISSUE TITLE
Missing support for --force param for decompile

### ISSUE THREAD

**Issue by stan-sz** [Azure/azure-cli#22548]
## Describe the bug

**Command Name**
`az bicep decompile`

**Errors:**
```
unrecognized arguments: --force

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az bicep decompile --file {} --force`

## Expected Behavior

The --force flag is passed to bicep

## Environment Summary
```
Windows-10-10.0.19044-SP0, 
Python 3.10.4
Installer: PIP

azure-cli 2.34.1 *

Extensions:
acrtransfer 1.1.0
application-insights 0.1.15
azure-devops 0.25.0
blueprint 0.3.1
interactive 0.4.5

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```
## Additional Context

See the Bicep code change: https://github.com/Azure/bicep/pull/6029

This is a repro in Bicep repo:

> az bicep decompile --file docs\examples\101\vm-simple-linux\main.json
The output path "docs\examples\101\vm-simple-linux\main.bicep" already exists. Use --force to overwrite the existing file.
> az bicep decompile --file docs\examples\101\vm-simple-linux\main.json --force
unrecognized arguments: --force

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
@stan-sz 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by robinmalik** [comment]
I think this is a dupe of https://github.com/Azure/azure-cli/issues/22505

**Comment by stan-sz** [comment]
Closing as a duplicate.
