### ISSUE TITLE
Could not create keyvault with service principal after graph module migration

### ISSUE THREAD

**Issue by FumingZhang** [Azure/azure-cli#22540]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

`az keyvault create`

**Describe the bug**

Could not create keyvault with service principal after graph module migration.

![image](https://user-images.githubusercontent.com/81607949/169479609-afd10b7c-ff7b-4276-8f34-0baf7a8cf222.png)

**To Reproduce**

Create keyvault with a service principal.

**Expected behavior**

Able to create keyvault with a service principal like it used to be.

**Environment summary**

WSL2, Ubuntu18.04, Python3.8, CLI `dev` branch + `tags/azure-cli-2.36.0`

**Additional context**

Before the migration, function [_get_current_user_object_id](https://github.com/Azure/azure-cli/blob/azure-cli-2.36.0/src/azure-cli/azure/cli/command_modules/keyvault/custom.py#L753) would raise GraphErrorException and retry with [_get_object_id](https://github.com/Azure/azure-cli/blob/azure-cli-2.36.0/src/azure-cli/azure/cli/command_modules/keyvault/custom.py#L755).

![Screenshot 2022-05-20 152110](https://user-images.githubusercontent.com/81607949/169477287-21bd1cbd-eff2-467f-a232-e830b0e8a123.png)

After the migration, function [_get_current_user_object_id](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/custom.py#L748) would not raise an error. Without retry, empty object id would result in raising [CLIError](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/custom.py#L752).

![Screenshot 2022-05-20 152633](https://user-images.githubusercontent.com/81607949/169477308-5e44bdc9-b652-4cd8-afce-43a0ede6c2b3.png)

**Comment by yonzhan** [comment]
keyvault
