### ISSUE TITLE
Example command in "az vmss diagnostics set" docs fails

### ISSUE THREAD

**Issue by terry-citrix** [Azure/azure-cli#22555]
**Command Name**
`az vmss diagnostics set`

**Overview**
I'm running almost verbatim the example command from the docs at https://docs.microsoft.com/en-us/cli/azure/vmss/diagnostics?view=azure-cli-latest&WT.mc_id=Portal-Microsoft_Azure_Security

I'm doing so on a test VM Scale Set.  In particular on this test VM Scale Set the MS Defender for Cloud gave me a recommendation that "Diagnostic logs in Virtual Machine Scale Sets should be enabled", which then has a link to the above documentation page on enabling diagnostics logs in VM SSs.

In my case, instead of this from the docs:
```az vmss diagnostics set --protected-settings {protected-settings} --resource-group MyResourceGroup --settings '{"commandToExecute": "echo testing"}' --vmss-name MyVmss```

I instead ran this (since I'm running this from PowerShell):
```az vmss diagnostics set --resource-group {my group name} --vmss-name {my vmss name} --settings '{\"commandToExecute\": \"echo testing\"}'```

I've confirmed that I've done `az login` and that my `az account` is set to the correct Azure subscription. I created the VM Scale Set in question.

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'mode'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/vm/custom.py", line 3662, in set_vmss_diagnostics_extension
AttributeError: 'NoneType' object has no attribute 'mode'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

1. `az login`
1. `az account set --name {}`
1. `az vmss diagnostics set --resource-group {} --vmss-name {} --settings {}`

## Expected Behavior

I expected it to succeed.  Barring that, I expected it to give me an error that explained what I did wrong (assuming I did something wrong).

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0
```

**Comment by yonzhan** [comment]
Compute

**Comment by RakeshMohanMSFT** [comment]
@terry-citrix Can you please try this command?
`az vmss diagnostics set --protected-settings protectedsettings.json -g Issue22555 --settings "{\"commandToExecute\": \"echo testing\"}" --vmss-name Issue22555vmss`

**Comment by terry-citrix** [comment]
I tried the command you suggested, but it's giving me an error:
```
PS C:\> az vmss diagnostics set --protected-settings protectedsettings.json -g terrydu-group --settings "{\"commandToExecute\": \"echo testing\"}" --vmss-name terrydu-test
JSON file does not exist: 'protectedsettings.json'
Please provide a valid JSON file path or JSON string.
```

I searched for a `protectedsettings.json` file on my system, but I didn't find one.

I can still reproduce the problem as well (I actually attempted this first before running your suggested command):
```
PS C:\> az vmss diagnostics set --resource-group terrydu-group --vmss-name terrydu-test --settings '{\"commandToExecute\": \"echo testing\"}'
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'mode'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/vm/custom.py", line 3823, in set_vmss_diagnostics_extension
AttributeError: 'NoneType' object has no attribute 'mode'
To open an issue, please run: 'az feedback'
```

**Comment by RakeshMohanMSFT** [comment]
@terry-citrix its a protected settings file you have to create with content as below.
![image](https://user-images.githubusercontent.com/49954584/189092680-b897ae8d-4f31-4f94-8fa9-9b74bbe074e2.png)

**Comment by terry-citrix** [comment]
First I tried the original command, but I got a different error today:
`PS C:\Users\terrydu\temp> az vmss diagnostics set --resource-group terrydu-group --vmss-name terrydu-test --settings '{\"commandToExecute\": \"echo testing\"}'
Network api version in network profile of virtual machine /subscriptions/8f986d9c-f3ff-4026-8a62-7b858cb1c71d/resourceGroups/TERRYDU-GROUP/providers/Microsoft.Compute/virtualMachines/terrydu-test028838c
d-5f05-4a86-8db6-d1f7e1d260a9 must be specified if network interface configurations are specified.`

Then I created a SAS token to my storage account (in the same resource group) and put that in a protectedsettings.json file (this is truncated, the actual SAS is quite long):
![image](https://user-images.githubusercontent.com/24683321/190528788-e167e75d-1d43-452e-abcd-cca2ca7f7b91.png)

And I tried again with the `--protected-settings` optional parameter:
`PS C:\Users\terrydu\temp> az vmss diagnostics set --resource-group terrydu-group --vmss-name terrydu-test --settings '{\"commandToExecute\": \"echo testing\"}' --protected-settings .\protectedsettings.json
Network api version in network profile of virtual machine /subscriptions/8f986d9c-f3ff-4026-8a62-7b858cb1c71d/resourceGroups/TERRYDU-GROUP/providers/Microsoft.Compute/virtualMachines/terrydu-test49860ce8-f7ce-45c6
-878a-bd2573a29c51 must be specified if network interface configurations are specified.`

Same error, though note that the GUID appended to the VM name always changes every time I run this az command.

If I try in a cmd prompt I get the same error:
`C:\Users\terrydu\temp>az vmss diagnostics set --resource-group terrydu-group --vmss-name terrydu-test --settings "{\"commandToExecute\": \"echo testing\"}" --protected-settings protectedsettings.json
Network api version in network profile of virtual machine /subscriptions/8f986d9c-f3ff-4026-8a62-7b858cb1c71d/resourceGroups/TERRYDU-GROUP/providers/Microsoft.Compute/virtualMachines/terrydu-testb7a6c534-cc58-4eb4-97ed-4b32b27032fb must be specified if network interface configurations are specified.`

**Comment by RakeshMohanMSFT** [comment]
@terry-citrix Can you please try upgrading to the latest version of az cli [2.40.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli) and retry?
