### ISSUE TITLE
az quota list giving an error

### ISSUE THREAD

**Issue by mpowrie** [Azure/azure-cli#22564]
Following the instructions for `az quota list`, I get an error:
Command:
```
az quota list --scope "subscriptions/${CUSTOMER_SUBSCRIPTION_ID}/providers/Microsoft.Compute/locations/australiaeast"
```

Error:
```
Command group 'quota' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(InvalidResourceType) The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2021-03-15-preview'.
Code: InvalidResourceType
Message: The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2021-03-15-preview'.
```
[Enter feedback here]

Version of az cli:
```
az version
{
  "azure-cli": "2.36.0",
  "azure-cli-core": "2.36.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "account": "0.2.2",
    "ad": "0.1.0",
    "aks-preview": "0.5.56",
    "azure-cli-ml": "1.37.0",
    "azure-devops": "0.23.0",
    "dataprotection": "0.2.0",
    "quota": "0.1.0"
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96b74af1-0d1f-759a-1b76-85f8b97b4869
* Version Independent ID: 3ec784bc-0bff-e794-2fc3-dcb3d0e14ee3
* Content: [az quota](https://docs.microsoft.com/en-us/cli/azure/quota?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/quota.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/quota.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
quota

**Comment by jamesongithub** [comment]
is there way to change the api version to work around this?

**Comment by nharper285** [comment]
I am getting this same error. Is there any update on a workaround?

**Comment by ZengTaoxu** [comment]
Hi, currently quota only supports Network RP , not Compute RP, which is expected in 2-4 weeks. In addition, your parameter seems to be wrong, it should be ‘ az quota list --scope "subscriptions/${CUSTOMER_SUBSCRIPTION_ID}/providers/Microsoft.Compute/locations/australiaeast" '. Please refer to : https://review.docs.microsoft.com/en-us/rest/api/quota/quota/list?branch=newquota

**Comment by jamesongithub** [comment]
the docs show compute examples, so there was expectation that they would work (in preview)

https://docs.microsoft.com/en-us/cli/azure/quota?view=azure-cli-latest#az-quota-list-examples

**Comment by ZengTaoxu** [comment]
Compute RP is not working yet, and is expected to be available in 2-4 weeks.

**Comment by mpowrie** [comment]
> Hi, currently quota only supports Network RP , not Compute RP, which is expected in 2-4 weeks. In addition, your parameter seems to be wrong, it should be ‘ az quota list --scope "subscriptions/${CUSTOMER_SUBSCRIPTION_ID}/providers/Microsoft.Compute/locations/australiaeast" '. Please refer to : https://review.docs.microsoft.com/en-us/rest/api/quota/quota/list?branch=newquota

Thanks - I updated the scope. I'm still getting the error with azure-cli 2.37.0, and will wait for Compute RP to be supported

**Comment by ZengTaoxu** [comment]
Hi, @Rahul Singh. May I ask how long it will take to support Compute PR?

**Comment by jainr** [comment]
Is it working now? I am getting same error. 
Command group 'quota' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(InvalidResourceType) The resource type 'locations' could not be found in the namespace 'Microsoft.Compute' for api version '2021-03-15-preview'. The supported api-versions are '2015-05-01-preview,2015-06-15,2016-03-30,2016-04-30-preview,2016-08-30,2017-03-30,2017-12-01,2018-04-01,2018-06-01,2018-10-01,2019-03-01,2019-07-01,2019-12-01,2020-06-01,2020-12-01,2021-03-01,2021-04-01,2021-07-01,2021-11-01,2022-03-01,2022-08-01'.
Code: InvalidResourceType
Message: The resource type 'locations' could not be found in the namespace 'Microsoft.Compute' for api version '2021-03-15-preview'. The supported api-versions are '2015-05-01-preview,2015-06-15,2016-03-30,2016-04-30-preview,2016-08-30,2017-03-30,2017-12-01,2018-04-01,2018-06-01,2018-10-01,2019-03-01,2019-07-01,2019-12-01,2020-06-01,2020-12-01,2021-03-01,2021-04-01,2021-07-01,2021-11-01,2022-03-01,2022-08-01'.

**Comment by ZengTaoxu** [comment]
Quota does not currently support Compute PR.

**Comment by jainr** [comment]
Can you give me few examples of what command currently works? I am trying to check quota for Purview, Synapse and SQL DB.

**Comment by jsntcy** [comment]
> Can you give me few examples of what command currently works? I am trying to check quota for Purview, Synapse and SQL DB.

@rahuls-microsoft, could you please help provide some information?

**Comment by rahuls-microsoft** [comment]
The Microsoft.Compute Resource provider is not supported yet, only Microsoft.Network Resource provider is supported through this Api. We will notify when more RPs are onboarded. Currently QuotaRP is in private preview, so all the subscriptions will not have access to the APIs. We will notify, when it's public preview starts.

**Comment by jainr** [comment]
Is there any other way to find quota for  Purview, Synapse and SQL DB? I couldn't find it on portal.

**Comment by coderplay** [comment]
It's August, still see the same error.

**Comment by jtvcodes** [comment]
I even tried it with Network and failed

az quota list --scope "subscriptions/<MY SUB ID>/providers/Microsoft.Network/locations/eastus"
Command group 'quota' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(InvalidResourceType) The resource type 'locations' could not be found in the namespace 'Microsoft.Network' for api version '2021-03-15-preview'. The supported api-versions are '2014-12-01-preview,2015-05-01-preview,2015-06-15,2016-03-30,2016-06-01,2016-07-01,2016-08-01,2016-09-01,2016-10-01,2016-11-01,2016-12-01,2017-03-01,2017-04-01,2017-06-01,2017-08-01,2017-09-01,2017-10-01,2017-11-01,2018-01-01,2018-02-01,2018-03-01,2018-04-01,2018-05-01,2018-06-01,2018-07-01,2018-08-01,2018-10-01,2018-11-01,2018-12-01,2019-02-01,2019-04-01,2019-06-01,2019-07-01,2019-08-01,2019-09-01,2019-11-01,2019-12-01,2020-01-01,2020-03-01,2020-04-01,2020-05-01,2020-06-01,2020-07-01,2020-08-01,2020-11-01,2021-01-01,2021-02-01,2021-03-01,2021-04-01,2021-05-01,2021-06-01,2021-08-01,2021-12-01,2022-01-01,2022-05-01'.
Code: InvalidResourceType
Message: The resource type 'locations' could not be found in the namespace 'Microsoft.Network' for api version '2021-03-15-preview'. The supported api-versions are '2014-12-01-preview,2015-05-01-preview,2015-06-15,2016-03-30,2016-06-01,2016-07-01,2016-08-01,2016-09-01,2016-10-01,2016-11-01,2016-12-01,2017-03-01,2017-04-01,2017-06-01,2017-08-01,2017-09-01,2017-10-01,2017-11-01,2018-01-01,2018-02-01,2018-03-01,2018-04-01,2018-05-01,2018-06-01,2018-07-01,2018-08-01,2018-10-01,2018-11-01,2018-12-01,2019-02-01,2019-04-01,2019-06-01,2019-07-01,2019-08-01,2019-09-01,2019-11-01,2019-12-01,2020-01-01,2020-03-01,2020-04-01,2020-05-01,2020-06-01,2020-07-01,2020-08-01,2020-11-01,2021-01-01,2021-02-01,2021-03-01,2021-04-01,2021-05-01,2021-06-01,2021-08-01,2021-12-01,2022-01-01,2022-05-01'.

**Comment by jamesongithub** [comment]
@rahuls-microsoft @ZengTaoxu @yonzhan 

I think people are coming to this github issue since the docs doesn't exactly state with resource providers are currently supported with `az quota`

the docs even use `az quota` with the [compute](https://docs.microsoft.com/en-us/cli/azure/quota?view=azure-cli-latest#az-quota-list-examples) resource provider even though it's not supported yet.

clarifying the docs with exactly which resource providers are supported along with working examples of supported ones i think would go a long way

**Comment by rahuls-microsoft** [comment]
That's correct, the doc for QuotaRP will include what RPs are onboarded and will be updated, when new RPs are onboarded.

**Comment by rahuls-microsoft** [comment]
Now Compute RP is available. It can only be used by the subscriptions registered with QuotaRP.

**Comment by omarkass** [comment]
Hi, iam getting the same error
 az quota list --scope "subscriptions/(sub-id)/providers/Microsoft.Network/location/eastus"                            Command group 'quota' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus                                             (InvalidResourceType) The resource type could not be found in the namespace 'Microsoft.Network' for api version '2021-03-15-preview'.

**Comment by derekpurdy** [comment]
> Now Compute RP is available. It can only be used by the subscriptions registered with QuotaRP.

has anyone got it working since @rahuls-microsoft commented about it being available for Compute 14 days ago?

**Comment by dawlysd** [comment]
It's end September, still see the same error.

**Comment by hengv** [comment]
Me too, it is not work still.

**Comment by rahuls-microsoft** [comment]
The planned date for public preview is 10/20/22. I will update the thread, as we go public preview.

**Comment by rahuls-microsoft** [comment]
The Quota APIs are now in public preview. You can access the APIs now.
Previously, it was behind AFEC (Feature flag) that's why you got the error.

**Comment by derekpurdy** [comment]
Thanks for the update, it does appear to work now.

I have a question though, maybe I'm missing an arguement or overlooking something.

When running "az quota usage show --resource-name "cores" --scope "subscriptions/XXXXX-XXXXX-XXXXX-XXXXX/providers/Microsoft.Compute/locations/canadaeast"

I only get the number of cores used, and not total used and the current quota value.

**Comment by derekpurdy** [comment]
also, it doesn't support output as a table properly

$ az quota show --resource-name "cores" --scope "subscriptions/XXXXX-XXXXX-XXXXX-XXXXX/providers/Microsoft.Compute/locations/canadaeast" -o table
Command group 'quota' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Name
------
cores

**Comment by rahuls-microsoft** [comment]
> Thanks for the update, it does appear to work now.
> 
> I have a question though, maybe I'm missing an argument or overlooking something.
> 
> When running "az quota usage show --resource-name "cores" --scope "subscriptions/XXXXX-XXXXX-XXXXX-XXXXX/providers/Microsoft.Compute/locations/canadaeast"
> 
> I only get the number of cores used, and not total used and the current quota value.
> 
> Edit: I see the total amount with "az quota show --resource-name "cores" --scope "subscriptions/XXXXX-XXXXX-XXXXX-XXXXX/providers/Microsoft.Compute/locations/canadaeast"
> 
> but there is no simple way that I've seen just to show you're using 100/200 cores for example.

For usage, please call usage API-
https://learn.microsoft.com/en-us/cli/azure/quota/usage?view=azure-cli-latest
