### ISSUE TITLE
Error when trying to upload an aerospike (only?) stdout binary file to azure storage account using CLI

### ISSUE THREAD

**Issue by lencarnacao** [Azure/azure-cli#22563]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
asbackup -n trigger -v -z zstd --output-file - | az storage blob upload --auth-mode login --data @- -c containername--account-name accountname --name test_upload_file_name

**Describe the bug**
Using Aerospike (in this particular case) to export data and upload it to Azure Storage Account using CLI command. 
The data is exported and compressed using zstd resulting on a binary file, "posted" on stdout to be picked up by the az storage blob upload command and sent to storage. 

Notes:
Works OK without compression. 

Works OK when split the command in 2. First Produce the file and second Upload it. 
Works NOK when the upload is through pipe. 

The command is the **Upload to a through pipe. **
https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-upload

The error message is: 
![image](https://user-images.githubusercontent.com/106066883/169800881-c32f7464-0382-45ce-bc2c-fdfbaaf42065.png)

**To Reproduce**
Having Aerospike or any binary file to the stdout. Read it with the az storage blob upload through pipe. 
asbackup -n trigger -v -z zstd --output-file - | az storage blob upload --auth-mode login --data @- -c containername--account-name accountname --name test_upload_file_name

**Expected behavior**
The expected behavior is an upload without issues. 

**Environment summary**
CLI version is 2.36

**Additional context**
Similar command works fine for AWS. 
asbackup -n data -v -z zstd --output-file - | aws s3 cp - s3://BUCKET_NAME/FOLDER_NAME/aerospike_backup.asd

Using the same command with 2 pipes gives the same error. 
asbackup -n trigger -v --output-file - | -z zstd | az storage blob upload --auth-mode login --data @- -c containername --account-name accountname-name test_upload_file_name

**Comment by yonzhan** [comment]
storage
