### ISSUE TITLE
AVNM CLI Extension Update -- GA/Stable API

### ISSUE THREAD

**Issue by jago2136** [Azure/azure-cli#22573]
**Resource Provider**

Azure Virtual Network Manager (extension name virtual-network-manager)

**Description of Feature or Work Requested**

We are migrating AVNM to the network stable API version. We are also going from Public Preview to GA on July 1st, so we would like anything related to PP to be removed from the extension. Changes in this new API version include:
- update/add link for our external docs https://docs.microsoft.com/en-us/azure/virtual-network-manager/
- 'network manager group' no longer has property 'memberType'
- security-user-config and all of its subgroups should be hidden. We will not be offering this feature in GA
- prior to this api version, security-user-config and security-admin-config were separate resource definitions, but their child resources (rule-collection and rule) shared common schemas. These child resource schemas have now diverged, and in swagger we no longer only have 'RuleCollection', instead we have 'AdminRuleCollection' and 'UserRuleCollection'. Same goes for the rule resource. The ask here: please make sure the 'security-admin-config' and its child resources are up to date with the swagger definitions.
- force delete flag should be available for the following resources: network manager, network manager group, network manager connect-config, network manager security-admin-config, network manager security-admin-config rule-collection, network manager security-admin-config rule-collection rule. For the delete operation of these resources, if the user **does not** use the force flag, we would like a confirmation message that says "The '-force' flag was not provided for the delete operation. If this resource or any of its child resources are part of a deployed configuration, this delete will fail. Would you like to proceed?" Please reach out to alias jaredgorthy if its unclear when this text should be displayed, or if you would like the alter the user interaction for these deletes.
- All resources mentioned in the point above now have async deletes and may return 202 responses. Within the response, the 'location' header contains the URL of the resource used to check the status of the asynchronous operation. I'm not sure whether its standard to display this link in CLI, please help us with your expertise here.
- for 'network manager group static-member create', there is currently a user defined property 'id'. This is the id of a virtual network, and now that we are offering cross-tenant support, it may be the id of a vnet on another tenant. In the event this is a cross-tenant vnet id, we need an additional auth token to be passed in the request's 'x-ms-authorization-auxiliary', which authenticates for the vnet reference. I believe one example of where this is already done can be found [here](https://github.com/Azure/azure-cli/blob/110f7b402020f3d3ebd2bfb923ac5a01d026cdd1/src/azure-cli-core/azure/cli/core/commands/client_factory.py#L50-L75) and [here](https://github.com/Azure/azure-cli/blob/90e6f75514cec2d5dfd2df7526007105c6d207ba/src/azure-cli/azure/cli/command_modules/network/custom.py#L6931-L6960). 

 **Minimum API Version Required**

2022-01-01

**Swagger Link**

https://github.com/Azure/azure-rest-api-specs/pull/19169

**Target Date**

ASAP, ideally by 6/17

**Comment by yonzhan** [comment]
network
