### ISSUE TITLE
az aks show getting python error

### ISSUE THREAD

**Issue by adonaicosta** [Azure/azure-cli#22574]
## Describe the bug

**Command Name**
`az aks show`

**Errors:**
```
cannot import name 'edge_zone_type'
Traceback (most recent call last):
lib/python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 563, in execute
    self.commands_loader.load_arguments(command)
site-packages/azure/cli/core/__init__.py, ln 511, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
azure/cliextensions/aks-preview/azext_aks_preview/__init__.py, ln 47, in load_arguments
    from ._params import load_arguments
azure/cliextensions/aks-preview/azext_aks_preview/_params.py, ln 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks show -n {} -g {}`

## Environment Summary
```
Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-centos-8.3.2011
Python 3.6.8
Installer: RPM

azure-cli 2.19.1 *

Extensions:
aks-preview 0.5.41

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@adonaicosta Thanks for reaching out to us and sharing this feedback. I see that you are using an older version of the `aks-preview` extension and Azure CLI. Could you please use the [most recent version of Azure CLI ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)and update your extension using the below command ?

>az extension update --name aks-preview

Awaiting your reply.
