### ISSUE TITLE
Please enable Azure monitor diagnostic settings AZ cmds to support the latest API version "2021-05-01-preview".

### ISSUE THREAD

**Issue by ChangLiuMS** [Azure/azure-cli#22572]
**Related command**
az monitor diagnostic-settings 

**Is your feature request related to a problem? Please describe.**
Please enable Azure monitor diagnostic settings AZ cmds to support the latest API version "2021-05-01-preview".
Details of the APIs version please refer to https://docs.microsoft.com/en-us/rest/api/monitor/diagnostic-settings 

Thanks.

**Comment by yonzhan** [comment]
monitor
