### ISSUE TITLE
'SnapshotsOperations' object has no attribute 'resource_groups'

### ISSUE THREAD

**Issue by bd-clara** [Azure/azure-cli#22581]
## Describe the bug

Hi
I have a python error when trying to create a snapshot on a netapp volume

**Command Name**
`az netappfiles snapshot create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'SnapshotsOperations' object has no attribute 'resource_groups'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/netappfiles/_exception_handler.py", line 18, in netappfiles_exception_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/netappfiles/custom.py", line 425, in create_snapshot
    location = client.resource_groups.get(resource_group_name).location
AttributeError: 'SnapshotsOperations' object has no attribute 'resource_groups'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az netappfiles snapshot create --account-name {} --name {} --pool-name {} --resource-group {} --volume-name {}`

## Environment Summary
```
Linux-5.4.0-110-generic-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
front-door 1.0.16
azure-firewall 0.12.0
ip-group 0.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by navba-MSFT** [comment]
@bd-clara Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. I am looking into this issue. I will reach out to you, if I need more information.

**Comment by navba-MSFT** [comment]
@bd-clara I was able to create the netappfiles snapshot successfully. I am sharing you the commands which I ran inorder:

>az login
>az account set --subscription "XXXXXXXX"

This command creates the Resource group
>az group create --name MyRgName --location eastus 

This command creates the netappFiles account
>az netappfiles account create -g MyRgName --name MyAccountname -l eastus --tags Reason=Repro

This command creates the pool
>az netappfiles pool create -g MyRgName --account-name MyAccountname --name Mypoolname -l eastus --size 4 --service-level standard

This command creates volume
>az netappfiles volume create -g MyRgName  --account-name MyAccountname --pool-name Mypoolname --name myvolname -l eastus --service-level premium --usage-threshold 100 --file-path "unique-file-path" --vnet myvnet --subnet mysubnet --protocol-types NFSv3 NFSv4.1

This command creates snapshot
>az netappfiles snapshot create -g MyRgName --account-name MyAccountname --pool-name Mypoolname --volume-name myvolname --name Mysnapname -l eastus

**Comment by navba-MSFT** [comment]
@bd-clara I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@bd-clara The action is currently pending on you to follow the above suggestion. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by Poil** [comment]
It looks like OK, probably I forget to do an `az account set -s`.

It should be probably better catched

Best regards,
