### ISSUE TITLE
--query option not working in az logic workflow show

### ISSUE THREAD

**Issue by vkamlesh** [Azure/azure-cli#22584]
While running az logic workflow list, I am able to fetch the version but when trying the same thing with az logic workflow show, I am not getting any response.

##### az logic workflow list output 

`$ az logic workflow list --subscription 0000-xxxx-xxx-xxx-xxxxxxx -g operations --query "[].["version","name"]"
Command group 'logic' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
[
  [
    "0008xxx0010200000xx",
    "monitor"
  ]
]`

##### az logic workflow show  output

`
$az logic workflow show --name monitor --subscription 0000-xxxx-xxx-xxx-xxxxxxx -g operations --query "[].["version"]"
Command group 'logic' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa2d288d-9ff4-a51c-3f30-1d79ea6564ab
* Version Independent ID: 4483e7d2-49f0-c2f4-afa2-3d7137ea70be
* Content: [az logic workflow](https://docs.microsoft.com/en-us/cli/azure/logic/workflow?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/logic/workflow.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/logic/workflow.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@vkamlesh Apologies for the delay, if its a single item there wont be an array, therefore i suggest you try this `az logic workflow show --subscription "your subscription" -g "" -n Test --query "version"`
