### ISSUE TITLE
--query does not support fields with "." in name

### ISSUE THREAD

**Issue by nayato** [Azure/azure-cli#22591]
## Describe the bug

**Command Name**
`az sf application show`

**Errors:**
Empty result returned instead of value matching supplied query.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sf application show --name {} -g {} -c {} --query parameters."abc.def"`

## Expected Behavior
Application parameters are a JSON object with key-value pairs defined by user. Querying just `parameters` returns `{"abc.def": "123"}` for instance. Querying into the object like `parameters."abc.def"` must return `"123"`.

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.13
Installer: DEB

azure-cli 2.36.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@nayato I was able to fetch the value by wrapping the query in quotes. Here is what I used, for both Linux (WSL) / PowerShell and Windows

### Linux / PowerShell
```sh
--query 'parameters."abc.def"'
```

### Windows
```sh
--query "parameters.\"abc.def\""
```
