### ISSUE TITLE
az monitor diagnostic-settings list does not return diagnostic settings for Log Analytics workspaces

### ISSUE THREAD

**Issue by sivetic** [Azure/azure-cli#22598]
## Describe the bug

**Command Name**
`az monitor diagnostic-settings list`

**Errors:**
Command does not return any diagnostic settings, even though a diagnostic setting can be observed in Azure Portal.  Command result:
```
{
  "value": []
}
```

Portal:
![image](https://user-images.githubusercontent.com/1087320/170136016-c16c25c7-503c-41fa-800b-0857cbb7b4e3.png)

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a Log Analytic workspace
- Add a diagnostic setting to Log Analytic workspace
- `az monitor diagnostic-settings list --resource {} --resource-group {} --resource-type Microsoft.OperationalInsights/workspaces`

## Expected Behavior
Command should return all defined diagnostic settings for Azure Log Analytic workspace.

For example, works fine for AKS:

```PS C:\uce_code\DevOps.UCE.Infra.Tests> az monitor diagnostic-settings list --resource {} --resource-group {} --resource-type Microsoft.ContainerService/managedClusters
{
  "value": [
    {
      "eventHubAuthorizationRuleId": null,
      "eventHubName": null,
      "id": "/subscriptions/{...}/resourcegroups/{...}/providers/microsoft.containerservice/managedclusters/{...}/providers/microsoft.insights/diagnosticSettings/diag-aks",
      "identity": null,
{...snip...}
```

## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0 *

Extensions:
application-insights 0.1.14
azure-firewall 0.13.0
log-analytics 0.2.2
resource-graph 2.1.0

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
This issue will be fixed in https://github.com/Azure/azure-cli/issues/22572

**Comment by Scherlac** [comment]
I see very similar issue with virtual network. The ARM template I'm using is '2019-09-01' the az tool is "azure-cli": "2.36.0". 
I've created the diagnostic settings manually on portal called `network-all`. I tried to export using az tools. 

```script
PS /workspaces/ESS12_CSP_Hyvos/build/templates/diagnostics> az monitor diagnostic-settings show --name "network-all" --resource $resourceId 
(ResourceNotFound) The diagnostic setting 'network-all' doesn't exist.
Code: ResourceNotFound
PS /workspaces/ESS12_CSP_Hyvos/build/templates/diagnostics> az monitor diagnostic-settings list --resource $resourceId                      
{
  "value": []
}
PS /workspaces/ESS12_CSP_Hyvos/build/templates/diagnostics> az monitor diagnostic-settings create `                                         
>>     --name "network-all" `
>>     --resource $resourceId --workspace $workspace `
>>     --logs ($logs -replace '"','\"') `
>>     --metrics ($metrics -replace '"','\"')
(BadRequest) Invalid API version used to modify diagnostic setting with one or more category groups selected: network-all, please use version higher than: 2021-05-01-preview
Code: BadRequest
Message: Invalid API version used to modify diagnostic setting with one or more category groups selected: network-all, please use version higher than: 2021-05-01-preview
```

I will try with different ARM template version, I hope that will help.

**Comment by CTroessaert** [comment]
I'm facing the same issue with repro for: keyvault, data factory, Azure Machine Learning, Container registries and Databricks. Any feedback or ETA on resolution ?

**Comment by kairu-ms** [comment]
We created a PR to fix it. And it will be released early of October.

**Comment by Kon-formity** [comment]
Hi there - just checking on the status of this fix?

**Comment by yonzhan** [comment]
Will be shipped on October 12th

**Comment by yonzhan** [comment]
already shipped

**Comment by saarp-cyera** [comment]
Hey, I still receive the same error when running 'az monitor diagnostics-settings list --resource <storage_account_resource_id>' with az cli version 2.42.0
