### ISSUE TITLE
Bastion needs a --no-wait option

### ISSUE THREAD

**Issue by bcosden** [Azure/azure-cli#22594]
Takes a long time to deploy and there is minimal dependency on it. Would be great to not wait and continue with script execution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c10d6dab-e042-91dc-a213-943af0d5ad0e
* Version Independent ID: 399a501c-b96d-8867-078f-73dd9b8b3da2
* Content: [az network bastion](https://docs.microsoft.com/en-us/cli/azure/network/bastion?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/bastion.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/bastion.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@bcosden Apologies for not getting back on this sooner! We worked up a PR to include support for this.
