### ISSUE TITLE
az acr repository show fails intermittently

### ISSUE THREAD

**Issue by pallavgupta** [Azure/azure-cli#22593]
We're running "az acr repository show" command in a loop and seeing it fails intermittently. In order to reproduce this issue I've created a bash script:

![image](https://user-images.githubusercontent.com/11171356/170110769-717cd003-f643-44f0-8ede-7ceb0ec0fef3.png)

command fails at 24th iteration and continue giving output at 25th iteration.

![image](https://user-images.githubusercontent.com/11171356/170110984-ae2998b5-c034-46e3-ac93-1273c45ebd6e.png)

**Command Name**
`az acr repository show`

**Errors:**
```
Error: authentication required, visit https://aka.ms/acr/authorization for more information. Correlation ID: a59cdda0-7938-475a-8ff4-4e68e90de46d.

```

## Expected Behavior

Command should produce same output as earlier without any fail.

## Environment Summary
```
Linux-5.13.0-1023-azure-x86_64-with-glibc2.29, Ubuntu 20.04.4 LTS
Python 3.8.13
Installer: DEB

azure-cli 2.36.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by pallavgupta** [comment]
@navba-MSFT we didn't see this issue today, so closing it now. We will reopen it, if we see same issue in future. Thanks.
