### ISSUE TITLE
Need ability to enable native client via Azure CLI

### ISSUE THREAD

**Issue by bcosden** [Azure/azure-cli#22595]
I am sure this is already planned. But would be great if this rolled out soon and was part of the creation process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c10d6dab-e042-91dc-a213-943af0d5ad0e
* Version Independent ID: 399a501c-b96d-8867-078f-73dd9b8b3da2
* Content: [az network bastion](https://docs.microsoft.com/en-us/cli/azure/network/bastion?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/network/bastion.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/bastion.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@bcosden You can already connect using native clients as covered in [this doc](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows). Currently, it opens Remote Desktop Connection for RDP and `az ssh` for SSH connections.

For other clients, you can create a tunnel first and then connect via the local tunnelled port.

**Comment by jamescrowley** [comment]
@PramodValavala-MSFT I believe the issue is you can connect using native clients, but you cannot configure the bastion to *enable* the native client support. (the properties.enableTunneling   attribute documented here: https://docs.microsoft.com/en-us/rest/api/virtualnetwork/bastion-hosts/list-by-resource-group)

**Comment by bcosden** [comment]
So you need to enable native client first in Azure Bastion after deploying it in order to use native client. The enablement must be done in the portal or via REST. This request is to ask for the command to be added to Azure CLI.

**Comment by maxwmsft** [comment]
+1  I would like this ability as well. I currently script creation of a VM and bastion with az cli, and need to then open the portal and manually enable native client. It would be very nice to be able to set that with the cli, so I don't have to do this manual step every time.

**Comment by PramodValavala-MSFT** [comment]
@bcosden @maxwmsft Apologies for not getting back to this sooner! I am working up a PR as part of [this issue](https://github.com/Azure/azure-cli/issues/23525) on the same ask.
