### ISSUE TITLE
Unable to install Azure CLI ML Extension on MacOS

### ISSUE THREAD

**Issue by osiotugo** [Azure/azure-cli#22590]
## Describe the bug

**Command Name**
`az extension add -n azure-cli-ml`

**Errors:**
```
An error occurred. Pip failed with status code 1. Use --debug for more information.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
- Pre-req: Install Azure CLI - https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos
- Run `az extension add -n azure-cli-ml`

## Expected Behavior
Install Azure CLI Tools extension

## Environment Summary
```
macOS-12.4-arm64-arm-64bit, Darwin 21.5.0
Python 3.10.4
Installer: HOMEBREW

azure-cli 2.37.0
```
## Additional Context
Installed another extension, ssh, without issue. See attached file for debug output
[debug_output.txt](https://github.com/Azure/azure-cli/files/8764087/debug_output.txt)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@osiotugo Thanks for reaching out to us and sharing this feedback. Could you please confirm if you are using a Mac OS with an **M1 chip** ? If Yes, check if running the below command helps. Awaiting your reply.

```
brew install openssl@1.1
export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"
az extension add -n ml -y
```

If it doesn't help, my recommendations would be to add and use the CLIv2 (ml) extension using the below command. More Info [here](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli?tabs=public).

>az extension add -n ml -y

Similar issue https://github.com/Azure/azure-cli/issues/22140

**Comment by osiotugo** [comment]
Ah I missed that issue. I am running on the m1 chip and installed v2 yesterday, so it looks like the export commands did the trick. Thank you!
