### ISSUE TITLE
Installed extensions are not available on WSL

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-cli#22619]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az postgres flexible-server`

**Describe the bug**
Installed *az cli* on Windows 11 environment and switched to doing dev tasks in WSL. Saw that *az cli* was available but that my extensions were not. *az cli* said they were installed when I listed my extensions but they weren't recognized when I tried the commands.

**To Reproduce**
1. Install az cli on Windows
2. Install the *containerapp* extension `az extension add --name containerapp  --upgrade`
3. Install the *rdbms-connect* extension `az extension add --name rdbms-connect --upgrade`
4. Install WSL
5. Launch WSL terminal
6. Run an az cli command that uses the extension

**Actual behavior**
![Install containerapp extension but not recognized](https://user-images.githubusercontent.com/23503973/170358345-8915d7df-7977-4ebc-b40e-f58f8cf9d6f3.png)

The extension is not found but AZ cli is recognized as valid.

**Environment summary**
- Ubuntu 20.04.3 LTS
- Windows 11
- az cli version 2.36.0

**Additional context**
Noted that when I was in WSL the extensions were listed as installed in a Windows folder
1. Installed az cli for linux following the [provided steps](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)
2. Restarted
3. Launched the same command and the container app command succeeded
4. Tried the rdbms-connect but received the errors in #21998
5. Uninstalled the rdbms-connect extension, and reinstalled. Noted that this installed additional dependencies. The command started working as expected.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@KSchlobohm I wasn't able to reproduce this behavior. Could you upgrade both Azure CLI and the ContainerApp extension to the latest, 2.37.0 and 0.3.5 respectively and try again?

**Comment by KSchlobohm** [comment]
Hi @PramodValavala-MSFT I installed another WSL instance after upgrading to the latest versions of `az cli` and the two extensions mentioned. I was also unable to recreate any issue.

Sorry about that, I didn't realize how out of date my `az cli` was.

**Comment by PramodValavala-MSFT** [comment]
@KSchlobohm Glad that you are unblocked! It wasn't that old per se but upgrading to the latest is a quick way to get unblocked for most issues since we are constantly improving Azure CLI. It happens more often that you would expect 😄
