### ISSUE TITLE
Unable to create an elastic monitor resource

### ISSUE THREAD

**Issue by kadzu** [Azure/azure-cli#22617]
**Related command**
`az elastic monitor create`

**Describe the bug**
Unable to create an Elastic Cloud resource from the AZ CLI.
A valid value is requested for SKU (I counldn't find information in the official documentation about possible values, the only one they show is "_free_Monthly_" and it doesn't work).

**To Reproduce**
`az elastic monitor create --name "myEC" --resource-group "MyResourceGroup" --location "West US 2" --sku "free_Monthly" --user-info "{\"companyInfo\":{\"business\":\"Technology\",\"country\":\"US\",\"domain\":\"microsoft.com\",\"employeeNumber\":\"10000\",\"state\":\"WA\"},\"companyName\":\"Microsoft\",\"emailAddress\":\"alice@microsoft.com\",\"firstName\":\"Alice\",\"lastName\":\"Bob\"}"  --debug`

**Expected behavior**
Return a 200 (Be able to create an Elastic Cloud resource Successfully).

**Environment summary**
- elastic extension version: "0.1.0" (latest)

**Comment by yonzhan** [comment]
elastic monitor

**Comment by kairu-ms** [comment]
Could you try `ess-monthly-consumption_Monthly`?

**Comment by kairu-ms** [comment]
Hi @v-sadafm. The enum value missed in swagger definition.

**Comment by v-sadafm** [comment]
Hi @kairu-ms,
I have tried creating elastic monitor resource with below az command which worked for me
az elastic monitor create --name "testcli" --resource-group "rg-name" --location "West US 2" --sku "ess-monthly-consumption_Monthly" --user-info "{'companyInfo':{'business':'Technology','country':'US','domain':'microsoft.com','employeeNumber':'10000','state':'WA'},'companyName':'Microsoft','emailAddress':'your-alias@microsoft.com','firstName':'Alice','lastName':'Bob'}"

Could you please recheck if its some issue with CLI or something as service is working as expected

**Comment by kairu-ms** [comment]
> Hi @kairu-ms, I have tried creating elastic monitor resource with below az command which worked for me az elastic monitor create --name "testcli" --resource-group "rg-name" --location "West US 2" --sku "ess-monthly-consumption_Monthly" --user-info "{'companyInfo':{'business':'Technology','country':'US','domain':'microsoft.com','employeeNumber':'10000','state':'WA'},'companyName':'Microsoft','emailAddress':'[your-alias@microsoft.com](mailto:your-alias@microsoft.com)','firstName':'Alice','lastName':'Bob'}"
> 
> Could you please recheck if its some issue with CLI or something as service is working as expected

 I see. The customer don't know which values are valid to pass into sku property. "ess-monthly-consumption_Monthly" is not appeared in swagger. The customer tried with "free_Monthly" value which is used in [swagger example](https://github.com/Azure/azure-rest-api-specs/blob/ef5e61721cf3ce245ec78f2908da1aced5a83b42/specification/elastic/resource-manager/Microsoft.Elastic/stable/2020-07-01/examples/Monitors_Create.json#L10), however it's not valid. 

So could you please define valid enum values for sku in this [swagger file](https://github.com/Azure/azure-rest-api-specs/blob/ef5e61721cf3ce245ec78f2908da1aced5a83b42/specification/elastic/resource-manager/Microsoft.Elastic/stable/2020-07-01/elastic.json#L911-L914). Thanks.

**Comment by v-sadafm** [comment]
Thank you for your feedback @kairu-ms, we will consider defining enum values for sku in upcoming development cycles.

**Comment by kadzu** [comment]
Exactly,
`--sku "ess-monthly-consumption_Monthly"` works as expected. However, please enhance your swagger file. 

Thanks all of you.
