### ISSUE TITLE
`az webapp list` No module named 'decorator'

### ISSUE THREAD

**Issue by techmist** [Azure/azure-cli#22618]
## Describe the bug

**Command Name**
`az webapp list`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp list --resource-group {}`

## Environment Summary
```
Linux-5.4.0-113-generic-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@techmist Thanks for reaching out to us and sharing this feedback. I see that you are using an older version of Azure CLI. Could you please use the [most recent version of AzCLI ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)and check if you are still facing the same issue ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@techmist I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@techmist The action is currently pending on you to update the AzCLI version and test again. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
