### ISSUE TITLE
az repo create command must include the option to initialize a branch with README.md

### ISSUE THREAD

**Issue by saikumar843** [Azure/azure-cli#22610]
**Related command**
 az repo create

**Is your feature request related to a problem? Please describe.**
A default/specific branch must be initialized while creating the repo. 

**Describe the solution you'd like**
az repo create --org *** -p *** --name *** --default-branch heads/main

**Describe alternatives you've considered**
Referred the "az repo ref create" as well which requires an object-id of an existing ref in the repository.
What if the repo is not having any default branch with an object-id

**Additional context**

![image](https://user-images.githubusercontent.com/48977506/170239103-18767843-c28f-4820-9324-fbf44a0500c9.png)
Repo must be initialized while creation

**Comment by yonzhan** [comment]
route to CXP team

**Comment by v-soujanya** [comment]
Hi @saikumar843 
we have checked the doc https://docs.microsoft.com/en-us/cli/azure/repos?view=azure-cli-latest#az-repos-create related to this command and, we found that API is not supported the requested parameter.

**Comment by smadep** [comment]
@v-soujanyaj, it should say hopefully "not yet supported" ;-) 
would be great to get this. meanwhile any workaround through REST api?!

**Comment by saikumar843** [comment]
@v-soujanya  Is this going to be brought in upcoming rollouts? Atleast a REST api for Initializing a repo

**Comment by wscherphof** [comment]
I'm still looking for a way to initialize (from a script) a newly created repository. Why is this issue closed as completed?

**Comment by wscherphof** [comment]
Well, managed to solve it like this:
```bash
# Create the new repo.
az repos create \
    --project "$project" \
    --name "$repository" &&
    # Query the new repo's webUrl.
    webUrl=$(
        az repos show \
            --project "$project" \
            --repository "$repository" \
            --query webUrl
    ) &&
    # Remove the "" around the value.
    eval "webUrl=$webUrl" &&
    # Initialise the new repo.
    (
        temp=$(mktemp --directory)
        cd "$temp" || exit
        git init
        git commit --allow-empty -m "initialise repository"
        git branch -m main
        git remote add origin "$webUrl"
        git push origin main
        rm -rf "$temp"
    ) &&
    # Set the repo's default branch to "main".
    az repos update \
        --project "$project" \
        --repository "$repository" \
        --default-branch main
```
