### ISSUE TITLE
All az commands result in "Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError"

### ISSUE THREAD

**Issue by gdrozario** [Azure/azure-cli#22613]
No matter what az command I run, I get the following error message:

Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

Az version
{
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "account": "0.2.3",
    "application-insights": "0.1.16",
    "azure-devops": "0.25.0",
    "logic": "0.1.6",
    "storage-preview": "0.8.2"
  }
}

OS - Windows 11

Have uninstalled and reinstalled without effect.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by gdrozario** [comment]
Resolved by deleting:
C:\Users\<username>\.azure\
    - msal_http_cache.bin
    - msal_token_cache.bin

**Comment by jiasli** [comment]
Duplicate of #20231
