### ISSUE TITLE
[Regression] `--stdout` does not work for `az bicep build` in v2.37.0

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-cli#22621]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az bicep build

**Describe the bug**
Since v2.37.0 the `--no-restore` flag has to be passed to `bicep build`, as well as `--stdout` to for the compiled template to be printed.

**To Reproduce**
run `az bicep build --stdout -f <path-to-bicep>` and you'll see not output.  Add `--no-restore` and you will.

**Additional context**
It was introduced, I think, with https://github.com/Azure/azure-cli/commit/215960c2a6f1da41f5e60df041b2a75c52ff2ed0.

Note that previously, when `--stdout` was set, we would print the result of calling `run_bicep_command`. When the restore feature was added, the extra if block that was introduced meant that we only printed the result when `--no-restore` was also set.

**Comment by yonzhan** [comment]
route to CXP team
