### ISSUE TITLE
 azure cli  application=databricks databricks-environment=true defaultExperience=Azure Cosmos DB for MongoDB API MLWorkspaceLinkUpdateTime=05/11/2022 16:44:01 +00:00 ms-resource-usage=azure-cloud-shell  

### ISSUE THREAD

**Issue by Euanher** [Azure/azure-cli#22623]
## Describe the bug

**Command Name**
`Unknown`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s connect --name {} --resource-group {} --location {} --tags {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.36.0 *

Extensions:
arcdata 1.3.1
connectedk8s 1.2.8

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@Euanher Thanks for reaching out to us. Could you please share the below details ?

1. Az CLI command that you have executed
2. Error details with the --debug output
3. Elaborate the issue you are facing. 

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Euanher I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please provide us the above details so that we can assist you further. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Euanher Since we didn't hear back from you, we will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by Euanher** [comment]
Thank you Kubelc was implemented and clusters formed all is well.
