### ISSUE TITLE
Proposal: move tests folder to the root of each command module folder

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#2262]
Change will look like:
From: `src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/tests/`
To: `src/command_modules/azure-cli-acs/tests/'

This will:
1. Shorten the path length to test folder;
2. Ease the logic of searching for tests (https://github.com/Azure/azure-sdk-for-python/blob/master/azure_nosetests.py); and 
3. Be consistent with azure-sdk-for-python repo.

**Comment by derekbekoe** [comment]
This would mean you can't run tests with `python -m azure.cli.command_modules.acs.tests` right?
Not saying this is a reason to not do this but calling it out.

**Comment by derekbekoe** [comment]
If there are other ways to achieve the same result, it's not an issue. 👍

**Comment by troydai** [comment]
replacement would be like `nosetests ./src/command_modules/azure-cli-acs`

**Comment by tjprescott** [comment]
So now how do I run a single test?  

python -m unittest azure.cli.command_modules.vm.tests.test_vm_commands.VMCreateLinuxSecretsScenarioTest

This no longer works....

**Comment by tjprescott** [comment]
The nosetests line runs all of the tests in that file, which is not what I want.

**Comment by tjprescott** [comment]
For reference, here's the way: 
`python {path}\test_foo.py {class name}`

Thanks @troydai !

**Comment by troydai** [comment]
Done
