### ISSUE TITLE
Python error when trying to list keyvault role assignments

### ISSUE THREAD

**Issue by ac101m** [Azure/azure-cli#22634]
**Related command**
az keyvault role assignment list --id ${HSM_URI}

**Describe the bug**
The following python error occurs when trying to list keyvault role assignments:

`'dict' object has no attribute 'object_id'`

There is no accompanying stack trace.

**To Reproduce**
Create an HSM via the cli (I used [these](https://docs.microsoft.com/en-us/azure/key-vault/managed-hsm/quick-create-cli) instructions), then attempt to get the role information using the aforementioned command.

**Expected behaviour**
A role list or actionable error to be printed out.

**Environment summary**
- OS: Ubuntu 20.04
- Output of `az --version`:
```
azure-cli                         2.37.0

core                              2.37.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1
```

**Comment by yonzhan** [comment]
keyvault

**Comment by evelyn-ys** [comment]
This is a bug during our MSGraph migration. We will fix in our next release. Sorry for the inconvenience.
