### ISSUE TITLE
Allow custom tenant for login instead of always using common

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#2263]
Currently we support a custom tenant for service principal login but not username/password login.

**Comment by colemickens** [comment]
Out of curiosity, what does this enable?

**Comment by derekbekoe** [comment]
AD login where the tenant 'common' is not available.
Typically, the CLI uses the 'common' tenant to determine the real tenant for the user.
However, though not recommended, some ADs can be set up without the 'common' tenant so the user has to pass in the tenant the CLI should use on the command line.

Main use-case was for Azure Stack.

@yugangw-msft can provide more info if needed.

**Comment by yugangw-msft** [comment]
When login to AAD, your account can be associated with multiple tenants. AAD makes it possible to deal with this by exposing a particular endpoint, where the tenant parameter is not known up front. `common` is  such a particular value which tells Azure AD that the requester is not mandating any particular tenant, so any tenant will do. If you are using org-id, the particular tenant you land will be your org's default tenant, say, `microsoft.com`.  Under this context, Azure CLI will hit the common tenant first and with the access token, we can use ARM service's `list_tenants' and `list_subscriptions` to further discover all subscriptions you have accesses to.

But Azure Stack's AAD endpoint doesn't support `common`; hence we need to change. 

For regular login, you can leverage this new arg if you like to skip tenants you are not interested,
