### ISSUE TITLE
Create VM using private image

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-cli#22630]
I have some images that show up under Private Products on the Azure Portal.

I tried to deploy VM using the "`az vm create`" command and specifying the SKU for the image but it returns a "`ERROR: (NotFound) Artifact: VMImage was not found.`" message.

Is it possible to deploy such image from the cli ?

Screenshot from Azure Portal:

![image](https://user-images.githubusercontent.com/106444/170432569-840726dc-bb9a-4154-a9a8-268bbff125dd.png)

**Comment by yonzhan** [comment]
Compute

**Comment by cxznmhdcxz** [comment]
Hi @johanburati  could you share the command with arguments that you specified?

**Comment by johanburati** [comment]
Looking at the debug log I realized that the image required to specify the plan information. Closing this issue.
