### ISSUE TITLE
Terraform and CLI work for GA of Site Recovery: V2ARCM 

### ISSUE THREAD

**Issue by Sharmistha-Rai** [Azure/azure-cli#22631]
**Related command**

**Resource Provider**
Microsoft.RecoveryService

**Description of Feature or Work Requested**
Azure Site Recovery allows customer to enable disaster recovery on their machines. As a part of the service, we allow customers to perform DR of Azure VMs, VMware VMs, Hyper-V VMs and physical servers. This feature focuses on the DR of VMware VMs and we are working on the GA release of this feature. Currently, this capability already exists, but we have made improvements to the process and experience and are re-launching the modernized experience.

**Minimum API Version Required**

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2021-10-01/service.json

**Target Date**
15th August 2022

**Comment by yonzhan** [comment]
PLR

**Comment by jsntcy** [comment]
@Sharmistha-Rai, could you please tell the relationship between this feature and https://github.com/Azure/azure-rest-api-specs/tree/master/specification/recoveryservices/resource-manager as the resource provider is also Microsoft.RecoveryService. We already have [commands](https://github.com/Azure/azure-cli/blob/1fc5ac9c9bc43198c91173db15e6538ae3ecbf09/src/azure-cli/azure/cli/command_modules/backup/commands.py#L31) for https://github.com/Azure/azure-rest-api-specs/tree/master/specification/recoveryservices/resource-manager

**Comment by Sharmistha-Rai** [comment]
Hi @jsntcy - the resource provider RecoveryServices covers two products - Azure Site Recovery and Azure Backup. The commands which you have shared are all related to Azure Backup. 

This request has been submitted for Azure Site Recovery.

**Comment by jsntcy** [comment]
> Hi @jsntcy - the resource provider RecoveryServices covers two products - Azure Site Recovery and Azure Backup. The commands which you have shared are all related to Azure Backup.
> 
> This request has been submitted for Azure Site Recovery.

Got it, thanks.

**Comment by shrauta-ms** [comment]
Please use this https://github.com/Azure/azure-rest-api-specs/blob/main/specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2022-08-01/service.json Swagger Link.

**Comment by chasewilson** [comment]
Is this work still planned an being worked on this sprint or will it be delayed? @jsntcy

**Comment by calvinhzy** [comment]
It is being worked on but there might be delays for testing. Most likely it will be out by next sprint. Thanks.
