### ISSUE TITLE
cli_generic_update_command doesn't play nice with SQL firewall rules api

### ISSUE THREAD

**Issue by jaredmoo** [Azure/azure-cli#2264]
I’m facing a problem where the cli_generic_update_command base code is totally unable to call into one of the SDK APIs.

Here’s what’s going on. The Python SDK has the following methods:

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-sql/azure/mgmt/sql/operations/servers_operations.py#L38
    def create_or_update_firewall_rule(
self, resource_group_name, server_name, firewall_rule_name, start_ip_address=None, end_ip_address=None, custom_headers=None, raw=False, **operation_config):

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-sql/azure/mgmt/sql/operations/servers_operations.py#L180
    def get_firewall_rule(
self, resource_group_name, server_name, firewall_rule_name, custom_headers=None, raw=False, **operation_config):

The cli_generic_update_command code (https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/commands/arm.py#L209) does the following:
1.	calls the getter (get_firewall_rule),
2.	does some complicated stuff to update the instance properties (startIpAddress and endIpAddress)
3.	shoves the instance properties into ‘getterargs’ (https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/commands/arm.py#L307 )
4.	then calls the setter (create_or_update_firewall_rule) with ‘getterargs’ (https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/commands/arm.py#L313)

This doesn’t work for these APIs because create_or_update_firewall_rule doesn’t have a ‘properties’ arg, instead it has start_ip_address and end_ip_address args. So the ‘instance’ that is updated in step 2 is unused, and  start_ip_address/end_ip_address args are never specified – so they always keep the default values of ‘None’. 

So the update command never updates anything. I can’t implement an update firewall command.

**Comment by johanste** [comment]
The generic update (cli_generic_update_command) is built to handle most of the “normal” (and recommended pattern) from ARM – i.e. the model type returned by a GET is the same as the model type for the body parameter for PUT. This is used in cases where PATCH is not supported (most services). If this is *not* the case, you are officially in custom command land for your update command. 

In addition, there are some cases where the parameter flattening kicks in and the PUT ends up with all method parameters where the generic update command will not work as well. But, again, there is nothing stopping you from implementing a custom command in these cases.

**Comment by jaredmoo** [comment]
Ok. Makes sense. Can you add that as a comment in cli_generic_update_command?

**Comment by tjprescott** [comment]
In this case, you can (and should) still use generic update. The difference is that rather than reflecting on the SDK's create_or_update command for the setter, you would point it to a custom setter. The custom setter would accept the instance (which has been modified by any custom arguments and  the generic arguments) and then populate the individual parameters in the call to create_or_update.  For example:

```Python
def custom_setter(client, resource_group_name, instance_name, instance):
   return client.create_or_update(resource_group_name,
                                  instance_name,
                                  prop_a=instance.prop_a,
                                  prop_b=instance.prop_b,
                                  ...)
```
