### ISSUE TITLE
az aks command invoke: read from stdin

### ISSUE THREAD

**Issue by jetnet** [Azure/azure-cli#22641]
**Related command**

*PowerShell*
```
$ExecutionContext.InvokeCommand.ExpandString($(gc "manifest.yml" -Raw)) | `
  az aks command invoke -n ${AksName} -f - -c "kubectl apply -f -"

- is not valid file, or not accessable.
```
*bash*
```
envsubst < manifest.yml | \
  az aks command invoke -n ${AksName} -f - -c "kubectl apply -f -"

- is not valid file, or not accessable.
```

**Is your feature request related to a problem? Please describe.**
az-aks invoke command cannot read configuration from the standard input.

**Describe the solution you'd like**
Since kubernetes does not support variables in manifests, that would be great if the `az aks command` would support `STDIN` to read manifest from the standard input.
Please note, that many Azure documents use this format, e.g.:
```
cat <<EOF | kubectl create -f -
...
  resourceID: $TRAEFIK_USER_ASSIGNED_IDENTITY_RESOURCE_ID
...
```

**Describe alternatives you've considered**
Workaround: create a temp file with substituted variables.

**Additional context**
```
azure-cli                         2.36.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by jetnet** [comment]
@PramodValavala-MSFT , thanks for clarifying this. Yes, the "temp-file" workaround is better.
Since it looks like I'm the only person, who would like to use STDIN with `az aks command invoke`, the feature would probably never get implemented :)
The issue can be closed.
Thanks again.

**Comment by PramodValavala-MSFT** [comment]
@jetnet Glad I could help! Closing.
