### ISSUE TITLE
Azure MDE.extension stucks on 'Deleting' on an Azure Arc vm

### ISSUE THREAD

**Issue by bogd-a-n** [Azure/azure-cli#22647]
I wanted to delete this extension from the machine but It got stucked:

![image](https://user-images.githubusercontent.com/106374076/170657506-055a073d-2e3f-4c27-970b-07703a2212d9.png)

Also tried to remove it from PowerShell but it gets stuck too..

![image](https://user-images.githubusercontent.com/106374076/170657660-631dfa95-6dad-415d-a708-e084ac0ed28e.png)

any ideas?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@bogd-a-n Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@bogd-a-n I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you  have tried the above suggesstion. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@bogd-a-n The action is currently pending on you to isolate the issue by following the above plan. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
