### ISSUE TITLE
az synapse trigger update issues

### ISSUE THREAD

**Issue by solwr-ssk** [Azure/azure-cli#22656]
## Describe the bug

**Command Name**
`az synapse trigger update`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'properties'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/synapse/manual/operations/artifacts.py", line 142, in create_or_update_trigger
    properties = Trigger.from_dict(definition_file['properties'])
KeyError: 'properties'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az synapse trigger update --file {} --name {} --workspace-name {}`

## Environment Summary
```
Linux-5.13.0-35-generic-x86_64-with-debian-11.0, Ubuntu 21.10
Python 3.6.10
Installer: DEB

azure-cli 2.32.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@solwr-ssk Thank you for reaching out to us, we will look into it. In the meantime can you please upgrade to latest Azure CLI [2.37.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and try?

**Comment by solwr-ssk** [comment]
Tried `az upgrade`
<pre>azure-cli is already the newest version (2.32.0-1~hirsute).
The following packages were automatically installed and are no longer required:
  libgdk-pixbuf-xlib-2.0-0 libgdk-pixbuf2.0-0 linux-headers-5.13.0-23
  linux-headers-5.13.0-23-generic linux-image-5.13.0-23-generic
  linux-modules-5.13.0-23-generic linux-modules-extra-5.13.0-23-generic
  python3-debconf update-notifier-common
Use &apos;sudo apt autoremove&apos; to remove them.
0 upgraded, 0 newly installed, 0 to remove and 110 not upgraded.
<font color="#E9AD0C">CLI upgrade failed or aborted.</font>
</pre>

**Comment by RakeshMohanMSFT** [comment]
@solwr-ssk https://docs.microsoft.com/en-us/cli/azure/install-azure-cli 2.37.0 is the latest version of azure cli, perhaps i am missing something. I will troubleshoot further and update. In the meantime go through this document https://docs.microsoft.com/en-us/cli/azure/install-azure-cli and see if you could update.

**Comment by solwr-ssk** [comment]
Install worked but upgrade does not
`azure-cli                         2.37.0`
I have switched to `az rest`, might try `az synapse` after it is out of preview.
