### ISSUE TITLE
Use ARM 'resource manager' endpoint instead of RDFE 'management' endpoint

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#2265]
Currently, we use `CLOUD.endpoints.management` but should use `CLOUD.endpoints.resource_manager`

**Comment by yugangw-msft** [comment]
@derekbekoe, let us stick to the `CLOUD.endpoints.management`, and do not change at this moment. Sorry I didn't call this out early, but the token will be shared with CLI 1.0, which might use the token to access legacy ASM artifacts

**Comment by derekbekoe** [comment]
Okay.

As another data point, Stack does not use RDFE endpoints.
Not changing it would mean a Stack user has to set this value to be the same as `CLOUD.endpoints.resource_manager`. If they don't set `management`, API calls wouldn't work.

**Comment by derekbekoe** [comment]
We want to keep both `management` and `resource_manager` endpoints for backwards compat. with xplat as tokens are shared.

**Comment by derekbekoe** [comment]
@yugangw-msft In the linked PR, I set the management endpoint to equal the resource manager endpoint if it isn't set. https://github.com/Azure/azure-cli/pull/2398/files#diff-69bacf5348b997023cd1e8e6f475a0daR248
