### ISSUE TITLE
az batch pool autoscale parameter "--auto-scale-evaluation-interval" lacks documentation

### ISSUE THREAD

**Issue by ttsakpc** [Azure/azure-cli#22667]
I am trying to use `az batch pool autoscale` and set the "--auto-scale-evaluation-interval" parameter.

The [docs](https://docs.microsoft.com/en-us/cli/azure/batch/pool/autoscale?view=azure-cli-latest#az-batch-pool-autoscale-enable) do not provide any help on how this parameter should be set.

The error I am getting when using this parameter is:

`msrest.exceptions.SerializationError: Unable to serialize value: '00:05:00' as type: 'duration'., ISO8601Error: Unable to parse duration string '00:05:00'`

I have tried the following values (with and without quotes) and all resulted in a similar error:

* 00:05:00
* 00:05
* T000500.0
* T000500
* T00:05:00
* T00:05
* 5
* 5m

The result is that "--auto-scale-evaluation-interval" parameter is unusable

az cli version : 2.37.0 (current latest)

install on mac using brew 
Python (Darwin) 3.10.4 (main, Apr 26 2022, 19:42:59) [Clang 13.1.6 (clang-1316.0.21.2)]

**Comment by RakeshMohanMSFT** [comment]
@ttsakpc Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@ttsakpc You can refer this for ISO 8601 duration format https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_duration_format.htm. I will get the document updated

**Comment by RakeshMohanMSFT** [comment]
@ttsakpc Engineering team will get the document updated soon, closing the thread for now.
