### ISSUE TITLE
User `objectId` is returned as `null` 

### ISSUE THREAD

**Issue by iddqdiddqd** [Azure/azure-cli#22666]
## Describe the bug

**Command Name**
`az ad signed-in-user show`

**Errors:**
```
{
  "object_id": null
}
```

## To Reproduce:
- `az ad signed-in-user show --query {object_id:objectId} -o json`

## Expected Behavior
`object_id` of the user currently logged in should be returned.

## Environment Summary
```
Linux-5.15.0-33-generic-x86_64-with-glibc2.35, Ubuntu 22.04 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0
```
## Additional Context
I am also trying to `terraform apply` the below code that utilizes user `object_id`. According to terraform provider (`azurerm 3.6.0`), the account information is retrieved from the `az login` context. Terraform can not retrieve the `object_id` with non-null payload as well.

```
resource "azurerm_key_vault_access_policy" "client_function" {
  key_vault_id                                  = azurerm_key_vault.function.id
  tenant_id                                     = data.azurerm_client_config.current.tenant_id
  object_id                                     = data.azurerm_client_config.current.object_id

  secret_permissions                            = ["Backup", "Delete", "Get", "List", "Purge", "Recover", "Restore", "Set"]
}
```
Error related with above desribed issue:
```
Error: expected "object_id" to be a valid UUID, got 
│ 
│   with azurerm_key_vault_access_policy.client_function,
│   on key_protect.tf line 25, in resource "azurerm_key_vault_access_policy" "client_function":
│   25:   object_id                                     = data.azurerm_client_config.current.object_id
```
## Personal Assumptions
I've already executed the same code successfully earlier this month on Ubuntu 21.10. The `object_id` of the current user was returned properly, with non-null payload.

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/22328#issuecomment-1122159498

As described in https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration?view=azure-cli-latest&tabs=powershell#breaking-changes

> For example, the most outstanding change is that the `objectId` property in the output JSON of a Graph object is replaced by `id`.
