### ISSUE TITLE
Dynatrace.Observability GA Release

### ISSUE THREAD

**Issue by divyansh3131** [Azure/azure-cli#22675]
**Related command**

**Resource Provider**
Dynatrace.Observability

**Description of Feature or Work Requested**
New GA Service through PLR.
High-level overview: https://review.docs.microsoft.com/en-us/azure/partner-solutions/dynatrace/dynatrace-create?branch=pr-en-us-199600

**Minimum API Version Required**
2021-09-01-preview

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/dynatrace/resource-manager/Dynatrace.Observability/stable/2021-09-01/dynatrace.json

**Target Date**
23-Aug-2022

**Comment by yonzhan** [comment]
PLR

**Comment by PARADISSEEKR** [comment]
Hi  @divyansh3131 The service returned an error when testing create dynatrace monitors, could you please help to fix it?
Error: **Index was outside the bounds of the array**.
Request body: [request body](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/dynatrace/resource-manager/Dynatrace.Observability/preview/2021-09-01-preview/examples/Monitors_CreateOrUpdate_MaximumSet_Gen.json)
correlation_id: cd0e8f6c-ad4c-49d0-a5b5-3ba09d2ebf83

    "identity":{
        "type":"SystemAssigned"
    },
    "location":"eastus",
    "properties":{
        "dynatraceEnvironmentProperties":{
            "accountInfo":{

            },
            "environmentInfo":{

            },
            "singleSignOnProperties":{

            }
        },
        "marketplaceSubscriptionStatus":"Active",
        "monitoringStatus":"Enabled",
        "planData":{
            "billingCycle":"monthly",
            "effectiveDate":"2022-07-28T16:00:00.000Z",
            "planDetails":"dynatraceapitestplan",
            "usageType":"committed"
        },
        "userInfo":{
            "country":"westus",
            "emailAddress":"alice@microsoft.com",
            "firstName":"alice",
            "lastName":"bob",
            "phoneNumber":"123456"
        }
    },
    "tags":{
        "test":"asd"
    }
}

**Comment by divyansh3131** [comment]
@PARADISSEEKR You are getting this error due to planId. There was a recent change in the planId format. Can you please test by passing **azureportalintegration_privatepreview@TIDhjdtn7tfnxcy** as planId

**Comment by PARADISSEEKR** [comment]
> @PARADISSEEKR You are getting this error due to planId. There was a recent change in the planId format. Can you please test by passing **azureportalintegration_privatepreview@TIDhjdtn7tfnxcy** as planId

Where should I put the planid, could you please provider an example like above(request body)？ Thanks!

**Comment by divyansh3131** [comment]
Sorry in the planDetails you should pass this

**Comment by PARADISSEEKR** [comment]
> Sorry in the planDetails you should pass this

Service return : **Failed to process eligibility check with error Failed to check if marketplace is enabled for Azure subscription 00000000-0000-0000-0000-000000000000. Plan 'azureportalintegration_privatepreview' not found in offer 'dynatrace_portal_integration'.**

**Comment by divyansh3131** [comment]
Can you please share the correlation id?

> > Sorry in the planDetails you should pass this
> 
> Service return : **Failed to process eligibility check with error Failed to check if marketplace is enabled for Azure subscription 00000000-0000-0000-0000-000000000000. Plan 'azureportalintegration_privatepreview' not found in offer 'dynatrace_portal_integration'.**

**Comment by PARADISSEEKR** [comment]
> Can you please share the correlation id?

correlation id: 61fb0115-80b1-4cbe-990a-8bf6c7bc65fe

**Comment by divyansh3131** [comment]
It is failing while trying to create an MP resource. I need to check the exact issue further as the MP side's error message is not precise. One thing is this plan is a private plan so maybe because of this it is giving you the error. Can you please share the tenant Id in which you are testing and also the payload?

**Comment by PARADISSEEKR** [comment]
> It is failing while trying to create an MP resource. I need to check the exact issue further as the MP side's error message is not precise. One thing is this plan is a private plan so maybe because of this it is giving you the error. Can you please share the tenant Id in which you are testing and also the payload?

"tenantId": "2f4a9838-26b7-47ee-be60-ccc1fdec5953", how to get the payload？

**Comment by divyansh3131** [comment]
The request body that you are sending during create

**Comment by PARADISSEEKR** [comment]
> The request body that you are sending during create




    "identity":{
        "type":"SystemAssigned"
    },
    "location":"eastus",
    "properties":{
        "dynatraceEnvironmentProperties":{
            "accountInfo":{

            },
            "environmentInfo":{

            },
            "singleSignOnProperties":{

            }
        },
        "marketplaceSubscriptionStatus":"Active",
        "monitoringStatus":"Enabled",
        "planData":{
            "billingCycle":"monthly",
            "effectiveDate":"2022-08-01T14:00:00.000Z",
            "planDetails":"azureportalintegration_privatepreview@TIDhjdtn7tfnxcy",
            "usageType":"committed"
        },
        "userInfo":{
            "country":"westus",
            "emailAddress":"alice@microsoft.com",
            "firstName":"alice",
            "lastName":"bob",
            "phoneNumber":"123456"
        }
    },
    "tags":{
        "test":"asd"
    }
}

**Comment by divyansh3131** [comment]
@PARADISSEEKR Can you please try creating a resource again? I've added your tenant for the plan that you are trying

**Comment by PARADISSEEKR** [comment]
> @PARADISSEEKR Can you please try creating a resource again? I've added your tenant for the plan that you are trying

Still fail: **Failed to process eligibility check with error Failed to check if marketplace is enabled for Azure subscription 0b1f6471-1bf0-4dda-aec3-cb9272f09590. Plan 'azureportalintegration_privatepreview' not found in offer 'dynatrace_portal_integration'.**

**Comment by divyansh3131** [comment]
> > The request body that you are sending during create
> 
> ```
> {"identity":{
>     "type":"SystemAssigned"
> },
> "location":"eastus",
> "properties":{
>     "dynatraceEnvironmentProperties":{
>         "accountInfo":{
> 
>         },
>         "environmentInfo":{
> 
>         },
>         "singleSignOnProperties":{
> 
>         }
>     },
>     "marketplaceSubscriptionStatus":"Active",
>     "monitoringStatus":"Enabled",
>     "planData":{
>         "billingCycle":"monthly",
>         "effectiveDate":"2022-08-01T14:00:00.000Z",
>         "planDetails":"azureportalintegration_privatepreview@TIDhjdtn7tfnxcy",
>         "usageType":"committed"
>     },
>     "userInfo":{
>         "country":"westus",
>         "emailAddress":"alice@microsoft.com",
>         "firstName":"alice",
>         "lastName":"bob",
>         "phoneNumber":"123456"
>     }
> },
> "tags":{
>     "test":"asd"
> }}
> ```

Can you please update the user info section and add the real values for the user who is trying to create this resource. MP check if failing because of this user. alice@microsoft.com is just the dummy value that was used in the examples for reference
