### ISSUE TITLE
Create Container Apps CLI Docs is wrong - Log analytics  

### ISSUE THREAD

**Issue by jonasnorlund** [Azure/azure-cli#22671]
Below is from docs page 

--logs-workspace-id

Name or resource ID of the Log Analytics workspace to send diagnostics logs to. You can use "az monitor log-analytics workspace create" to create one. Extra billing may apply.

It doesn't work with name or resource ID, however it works with Workspace ID (=guid), so docs need to be updated. 

 az monitor log-analytics workspace show -g $RESOURCE_GROUP -n $WORKSPACE_NAME --query customerId -o tsv 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5783ae85-c228-8bbe-d53e-c5452d8fe6b6
* Version Independent ID: 3c33cc2d-e8d1-d0ae-db45-e3db3ec8717c
* Content: [az containerapp env](https://docs.microsoft.com/en-us/cli/azure/containerapp/env?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/containerapp/env.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/containerapp/env.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@jonasnorlund Apologies for the delay here but this has now been fixed. Closing.
