### ISSUE TITLE
Getting No module named 'azure.keyvault.v7_0' error 

### ISSUE THREAD

**Issue by VNBharadwaja** [Azure/azure-cli#22680]
I installed `azure cli` in Dockerfile like so:

`RUN echo Y | apt-get install azure-cli`

and I don't see any errors. I also logged into a service principal like so:
`RUN az login --verbose --service-principal -u  $AZ_APPID -p $AZ_PASSWORD --tenant $AZ_TENANT_ID --allow-no-subscriptions`

but when I'm trying to run the following command in Dockerfile:
`RUN az keyvault secret show --name "<secretname>" --vault-name "<vaultname>" --query "value"`

I get an error saying:

```
1.586 ERROR: CLIInternalError: The command failed with an unexpected error. Here is the traceback:
#0 1.587 ERROR: No module named 'azure.keyvault.v7_0'
```
The online solutions suggest using a specific version of azure-keyvault through `pip` but I'm using `apt-get` to install things. Does anyone know how to fix this?

**Comment by yonzhan** [comment]
keyvault

**Comment by VNBharadwaja** [comment]
> 

what is this supposed to mean?

**Comment by evelyn-ys** [comment]
Can you share the CLI version with `az version`?

Our official installation doc is https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**Comment by VNBharadwaja** [comment]
`az version`
`2.18.0`

**Comment by evelyn-ys** [comment]
Can you reinstall following https://docs.microsoft.com/en-us/cli/azure/install-azure-cli and see if the keyvault dependency works?

**Comment by VNBharadwaja** [comment]
everything works fine if I install with `pip` . I still face issues when I use `apt`

**Comment by evelyn-ys** [comment]
@jiasli Do you know what could happen to cause this with `apt`?

**Comment by VNBharadwaja** [comment]
> 
I'm not sure honestly

**Comment by jiasli** [comment]
Apparently, you are not installing the official Azure CLI. Please see https://github.com/Azure/azure-cli/issues/19640.
