### ISSUE TITLE
(InvalidApiVersionParameter) The api-version '2020-07-01-preview' is invalid.

### ISSUE THREAD

**Issue by BigBearBrian** [Azure/azure-cli#22684]
**Related command**
`az policy exemption create -n "Exempt_<SNOWINC>_Tags_<RSGName>" --policy-assignment "/providers/Microsoft.Management/managementGroups/<MGName>/providers/Microsoft.Authorization/policyAssignments/<AssignmentName>" --exemption-category "Waiver" --resource-group "/subscriptions/<SubGUID>/resourceGroups/<RSGName>" --expires-on "2022-06-02T00:00:00Z"`

**Describe the bug**
Using most-recent AZ CLI (and immediately previous version):
```
PS C:\Users\brian.pickering> az version
{
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "account": "0.2.3",
    "aks-preview": "0.5.76",
    "automation": "0.1.1"
  }
}
```

Receiving the following error response to the command given above:
```
Command group 'policy exemption' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(InvalidApiVersionParameter) The api-version '2020-07-01-preview' is invalid. The supported versions are '2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
Code: InvalidApiVersionParameter
Message: The api-version '2020-07-01-preview' is invalid. The supported versions are '2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
```

**To Reproduce**
Run the command as specified above (of course, one needs to replace the descriptive "macros" given in <>.)

**Expected behavior**
Create exemption on the policy initiative.

**Environment summary**
Found error on previous version of az cli, updated to current version, error remained the same.

**Additional context**
N/A

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
This issue is caused by ARM service does not support api-version `2020-07-01-preview`, so ARM service team needs to investigate it

**Comment by BigBearBrian** [comment]
Public cloud only. I'll try to get you a debug log after I log in to work tomorrow (6/1/2022).

**Comment by BigBearBrian** [comment]
[debugoutput.txt](https://github.com/Azure/azure-cli/files/8856928/debugoutput.txt)

Sorry for the delay. I've attached the debug output, with critical GUIDs like TenantId, SubscriptionId, and my calling ObjectId obfuscated.

I noticed in the list of allowed APIs, api-version '2020-07-01' *is* valid, even though '2020-07-01-preview' is not. Doesn't sound as much like an ARM problem, as ARM has taken the version out of preview, but the az cli hasn't kept up.

**Comment by zhoxing-ms** [comment]
This is the error message from service
>  {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2020-07-01-preview' is invalid. The supported versions are '2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}

Request URL:
> PUT /subscriptions/<subscriptionId>/resourceGroups//subscriptions/<subscriptionId>/resourceGroups/BLPSandbox/providers/Microsoft.Authorization/policyExemptions/Exempt_Sandbox_Tags?api-version=2020-07-01-preview HTTP/1.1

Currently, the version of `PolicyExemptionsOperations` used in the Python SDK is [`2020-07-01-preview`](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/resources/azure-mgmt-resource/azure/mgmt/resource/policy/v2021_06_01/operations/_operations.py#L4333), so this issue needs the ARM service team to see why the api-version `2020-07-01-preview` for `Microsoft.Authorization` RP is not registered on the public cloud

**Comment by zhoxing-ms** [comment]
@robga Please take a look at this issue

**Comment by robga** [comment]
@zhoxing-ms , the error message is not from the auth RP. It's from ARM. 
Another thing is the request Uri is not a legit Uri. I don't think ARM can parse it correctly.

PUT /subscriptions//resourceGroups//subscriptions//resourceGroups/BLPSandbox/providers/Microsoft.Authorization/policyExemptions/Exempt_Sandbox_Tags?api-version=2020-07-01-preview HTTP/1.1

It should be something like 
/subscriptions/{subscriptionId}/resourceGroups/BLPSandbox/providers/Microsoft.Authorization/policyExemptions/Exempt_Sandbox_Tags?api-version=2020-07-01-preview HTTP/1.1

**Comment by zhoxing-ms** [comment]
@robga This URI comes from the deg log [debugoutput.txt](https://github.com/Azure/azure-cli/files/8856928/debugoutput.txt) provided by customer @BigBearBrian. I believe he may have made some manual modifications to hide the name of the resource. The real URI he used should be valid, this issue is mainly about the api-version

 > It's from ARM.

Yes, I know that. Because I see you submitted the related PR #17565, so I think you may know more about the context of this api-version, could you help route to the person who can investigate this issue?

**Comment by robga** [comment]
@zhoxing-ms There is correlationId in the debug log you shared. The Uri format is incorrect. It should be the client issue. Will send you the query via email.

**Comment by BigBearBrian** [comment]
OK, found the problem. Was giving parameter --resource-group in the full URI format (/subscriptions/<subID>/resourceGroups/<rsgName>) instead of simply giving just the Resource Group name. When I entered ONLY the Resource Group name, the exemption got created.

Sorry to have wasted your time.
