### ISSUE TITLE
az start and stop failing after apt update / upgrade: ModuleNotFoundError: No module named 'azure.mgmt.compute.v2022_03_01'

### ISSUE THREAD

**Issue by arty-hlr** [Azure/azure-cli#22697]
## Describe the bug

**Command Name**
`az vm start`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No module named 'azure.mgmt.compute.v2022_03_01'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 515, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 318, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib/python3/dist-packages/knack/commands.py", line 104, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 125, in arguments_loader
    op = self.get_op_handler(self.op_path)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.mgmt.compute.v2022_03_01'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az vm start --ids`

## Expected Behavior

VMs succesfully started and stopped

## Environment Summary
```
Linux-5.10.0-kali9-amd64-x86_64-with-glibc2.33, Kali GNU/Linux Rolling
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
azure-devops 0.24.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.0.0
```
## Additional Context

Azure CLI fails at starting and stopping VMs after the last update

**Comment by arty-hlr** [comment]
![image](https://user-images.githubusercontent.com/38589602/171365136-d1eb6f12-fa81-47d7-96ee-46019f8c94ea.png)

Apparently API version 2022-03-01 can't operate on virtual machines??!

**Comment by arty-hlr** [comment]
@yonzhan The azure.mgmt.compute seems to be missing indeed. I don't see how I can fix it myself though, that's the azure cli installed from apt. If you have any solution more than one word long, I'm all in :)

**Comment by zhoxing-ms** [comment]
@arty-hlr Please refer to this document [install-azure-cli-linux?pivots=apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) reinstall CLI with apt

**Comment by arty-hlr** [comment]
@zhoxing-ms I just did a `apt remove --purge azure-cli`, `apt update && apt upgrade`, and `apt autoremove`, then again `apt install azure-cli`. I have the *exact* same issue. I installed azure-cli a while ago following that document you linked. Everything is up-to-date. The issue doesn't seem to come from my end, I have the latest version of azure-cli, 2.37.0 coming straight from apt.

**Comment by zhoxing-ms** [comment]
This is an issue related to the package installation. @jiasli Could you help take a look?

**Comment by jiasli** [comment]
Judging from the `dist-packages` in file path, this is not the official Azure CLI, please see https://github.com/Azure/azure-cli/issues/19640

**Comment by arty-hlr** [comment]
@jiasli Thank you, that makes sense. I'll try uninstalling and reinstalling the manual way making sure it's the official packages.

**Comment by jiasli** [comment]
Could you share the logs of `sudo apt-get install azure-cli` and `apt show azure-cli`? They should look like 

```
$ sudo apt install azure-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libfwupdplugin1
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  azure-cli
0 upgraded, 1 newly installed, 0 to remove and 78 not upgraded.
Need to get 0 B/79.3 MB of archives.
After this operation, 1098 MB of additional disk space will be used.
Selecting previously unselected package azure-cli.
(Reading database ... 40568 files and directories currently installed.)
Preparing to unpack .../azure-cli_2.37.0-1~focal_all.deb ...
Unpacking azure-cli (2.37.0-1~focal) ...
Setting up azure-cli (2.37.0-1~focal) ...

$ apt show azure-cli
Package: azure-cli
Version: 2.37.0-1~focal
Priority: extra
Section: python
Maintainer: Azure Python CLI Team <azpycli@microsoft.com>
Installed-Size: 1098 MB
Depends: libc6 (>= 2.30), libssl1.1 (>= 1.1.1)
Homepage: https://github.com/azure/azure-cli
Download-Size: 79.3 MB
APT-Manual-Installed: yes
APT-Sources: https://packages.microsoft.com/repos/azure-cli focal/main amd64 Packages
Description: Azure CLI
 A great cloud needs great tools; we're excited to introduce Azure CLI,
 our next generation multi-platform command line experience for Azure.
```

**Comment by arty-hlr** [comment]
```
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ stretch main
```

**Comment by jiasli** [comment]
As shown in https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt, we dropped Debian 9 (Stretch) in Azure CLI 2.37.0. Could you update `/etc/apt/sources.list.d/azure-cli.list` to use a newer distribution like buster or bullseye?

**Comment by arty-hlr** [comment]
![image](https://user-images.githubusercontent.com/38589602/176166794-c5ddb7fc-ea07-4d97-b4b0-a4af9a8dcaba.png)
Will do. Then it would probably be good to update the documentation as it says to use stretch for debian based distros.

**Comment by jiasli** [comment]
Will do too! Maybe you may just submit a PR to edit the doc! 😉

![image](https://user-images.githubusercontent.com/4003950/176239299-37858883-dff5-45cb-834a-8271b69a1e76.png)

**Comment by iaacautomation** [comment]
I think its better to just use
```
pip install azure-cli
```
