### ISSUE TITLE
Description types

### ISSUE THREAD

**Issue by kazeshini178** [Azure/azure-cli#22699]
There just seems to be some minor typos when referring to `rsa` some places refer to `ras` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662379f5-1e62-d0f0-1a86-d98b6a32e2e8
* Version Independent ID: 1bca0624-d1a2-89f2-f86a-e79382ab31a4
* Content: [az storage account local-user](https://docs.microsoft.com/en-us/cli/azure/storage/account/local-user?view=azure-cli-latest#az-storage-account-local-user-create)
* Content Source: [latest/docs-ref-autogen/storage/account/local-user.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/account/local-user.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage
