### ISSUE TITLE
`az ad group show --group` breaks with group names that use `+` in v2.37

### ISSUE THREAD

**Issue by jtmackoy** [Azure/azure-cli#22700]
**Related command**
`az ad group show --group <group_name>`

**Describe the bug**
Prior to `v2.37` of the azure-cli, this command would complete successfully:
`az ad group show --group some_group+`
As of `v2.37` that same command returns the following error:
`No group matches the name of 'some_group+'`

If you execute the same command on another group that does not have the `+` in its name:
`az ad group show --group some_group`
...then the command completes successfully.

**To Reproduce**
1. Ensure `az --version` returns a version < 2.37.
2. `az ad group show --group some_group+` - command successful.
3. Upgrade azure-cli to version 2.37.
4. `az ad group show --group some_group+` - command fails.

Further, no amount of shell escaping results in success:
- `az ad group show --group "some_group+"` - command fails.
- `az ad group show --group 'some_group+'` - command fails.
- `az ad group show --group some_group\+` - command fails.

**Expected behavior**
I suspect this behavior is a result of the [recent move from the `Active Directory Graph API` to the `Microsoft Graph API` when upgrading to v2.37 of the azure-cli](https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration).  That said, I think there is a reasonable expectation that rules around illegal characters should at least be harmonized between the two graphs before migrating from one to the other.

I found no mention of this behavior in [the documentation I was able to locate on the differences between the two graphs](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-audit-api-use).

**Environment summary**
Experienced in Azure Cloud Shell which recently upgraded azure-cli to v2.37, and also in an installed azure-cli instance on a Manjaro Linux workstation.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jtmackoy** [comment]
I believe this confirms the problem is with the azure-cli and not the Microsoft Graph as the following command executes successfully:

```bash
az rest \
--url 'https://graph.microsoft.com/v1.0/groups?$search="displayName:some_group+"' \
--headers ConsistencyLevel=eventual
```

**Comment by jiasli** [comment]
`az ad group show` internally uses [`$filter` query parameter](https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter) to find groups.

It seems [`$search`](https://docs.microsoft.com/en-us/graph/query-parameters#search-parameter) follows a different pattern that does allow `+` to be un-encoded.

```
$ az rest --url 'https://graph.microsoft.com/v1.0/groups?$search="displayName:azure-cli-test+"' --headers ConsistencyLevel=eventual --debug
cli.azure.cli.core.util: Request URL: 'https://graph.microsoft.com/v1.0/groups?$search=%22displayName:azure-cli-test+%22'
```

Anyway, I will fix the encoding issue in https://github.com/Azure/azure-cli/pull/22739.

**Comment by jtmackoy** [comment]
@jasli - Confirmed that after [building](https://github.com/Azure/azure-cli/blob/dev/doc/try_new_features_before_release.md#install-from-source-code) against 25912763773261340f880bab8f5e360ebc5f735c `az ad group show --group some_group+` works as before.

Thanks!

**Comment by jiasli** [comment]
Our release schedule can be found at https://github.com/Azure/azure-cli/milestones.

The next release 2.38.0 is 07/05/2022.
