### ISSUE TITLE
Convert create commands to dynamic template generation

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#2270]
Some `create` commands need to be converted to use either SDK calls or dynamic template generation.

This change is required so these `create` commands can also support multiple API profiles.

**Comment by derekbekoe** [comment]
https://github.com/Azure/azure-cli/issues/2198 addresses this for Network.
We should look at other `create` commands and determine which other ones should be converted.

**Comment by tjprescott** [comment]
Network is the only module that still does this (compute was the other).

**Comment by derekbekoe** [comment]
Okay thanks
