### ISSUE TITLE
`az storage account create` ignores encryption parameters when configuring table/queue encryption key type

### ISSUE THREAD

**Issue by baaym** [Azure/azure-cli#22704]
**Related command**

```shell
az storage account create \
  --name "test-storage-account" \
  -g "test-rg" \
  --location "westeurope" \
  --sku Standard_GRS \
  --encryption-key-source "Microsoft.Keyvault" \
  --encryption-key-vault "[INSERT_VAULT_URI_HERE]" \
  --encryption-key-name "my-key" \
  --encryption-services blob file queue table \
  --encryption-key-type-for-queue Account \
  --encryption-key-type-for-table Account
```

**Describe the bug**

When including the `--encryption-key-type-for-queue` or `--encryption-key-type-for-table` properties, other provided encryption parameters are ignored.

I could trace back the section of code that triggers this behavior here: https://github.com/Azure/azure-cli/blob/azure-cli-2.37.0/src/azure-cli/azure/cli/command_modules/storage/operations/account.py#L182-L186

**To Reproduce**

- Configure a key vault and key for storage account encryption (as described [on this documentation page](https://docs.microsoft.com/en-us/azure/storage/common/customer-managed-keys-configure-key-vault?tabs=azure-cli))
  - Either system-managed or user-managed identities reproduces this issue
- Create the storage account using above command
- Observe that the command completes successfully, and has created a storage account does not have the CMK configured

**Expected behavior**

To have the storage account created with the CMK

**Environment summary**

Bash, Azure CLI 2.37.0, MacOS and Linux (Azure DevOps agent)

**Additional context**

**Comment by chrisking81** [comment]
We've just come across this exact issue, and doesn't look like it has been fixed yet. 

@jiasli / @evelyn-ys - any update on this? could we get this prioritised to be worked on please?

**Comment by calvinhzy** [comment]
Hi @chrisking81 , @baaym , here is the private package to test https://zhiyihuangsa.blob.core.windows.net/sharing/cli-private-for-fixing-storage-account-create-with-encryption.zip  Let me know if it fixes the issue. 

Instructions to install: ## 1. Prepare and Use a separate virtual environment

Create a python virtual env named `testenv` with:
```
python -m venv testenv
```
Activate the env (if you are using powershell):
```
.\testenv\Scripts\Activate.ps1
```
Activate the env (if you are using bash):
```
source venv/bin/activate
```

## 2. Install CLI private package

Unzip the file and install three cli whl packages (azure_cli, azure_cli_core, azure_cli_telemetry):
```
pip install azure_cli-2.50.0.post20230710052857-py3-none-any.whl azure_cli_core-2.50.0.post20230710052857-py3-none-any.whl azure_cli_telemetry-1.0.8.post20230710052857-py3-none-any.whl
```
