### ISSUE TITLE
az webapp config appsettings set fails with error No module named 'decorator'

### ISSUE THREAD

**Issue by UQRakesh** [Azure/azure-cli#22711]
## Describe the bug

**Command Name**
`az webapp config appsettings set`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config appsettings set --name {} --resource-group {} --settings {} {}`

## Environment Summary
```
Linux-5.4.0-113-generic-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
@UQRakesh 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SatishBoddu-MSFT** [comment]
Hello @UQRakesh Could you please try one more time and do let us know if the issue still persists?

![image](https://user-images.githubusercontent.com/62923178/172493918-670fdccd-de51-4f35-96ea-6ccd1b98f1fe.png)

**Comment by SatishBoddu-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
