### ISSUE TITLE
Cannot delete and purge an app configuration via CLI

### ISSUE THREAD

**Issue by derekjoos** [Azure/azure-cli#22714]
## Describe the bug

**Command Name**
`az appconfig delete`
`az appconfig list-deleted`
`az appconfig purge`

**Describe the bug**
I cannot delete and purge an app configuration instance

**Errors:**
```
az appconfig create -g MyResourceGroup -n MyAppConfiguration -l eastus --sku Standard
(NameUnavailable) The specified name is already in use.
Code: NameUnavailable
Message: The specified name is already in use.

az appconfig purge --name MyAppConfiguration
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Failed to find the deleted App Configuration store 'MyAppConfiguration'. If you think that the store name is correct, please validate all your input parameters again.

```

## To Reproduce:
1. `az appconfig create -g MyResourceGroup -n MyAppConfiguration -l eastus --sku Standard` (successfully completes)
2. `az appconfig delete -g MyResourceGroup -n MyAppConfiguration` (successfully completes)
3. `az appconfig list-deleted` (completes, but doesn't return any deleted instances)
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
[]
4. `az appconfig create -g MyResourceGroup -n MyAppConfiguration -l eastus --sku Standard` (errors)
(NameUnavailable) The specified name is already in use.
Code: NameUnavailable
Message: The specified name is already in use.
5. `az appconfig purge --name MyAppConfiguration`
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Failed to find the deleted App Configuration store 'MyAppConfiguration'. If you think that the store name is correct, please validate all your input parameters again.

## Expected Behavior

I expected the deleted app configuration to be shown by the `list-deleted` and to be able to purge that with the `purge`. If it was indeed already hard deleted, I expect to be able to create a new app configuration with the same name.

## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0
```
## Additional Context
```
output from az appconfig create
{
  "createMode": null,
  "creationDate": "2022-05-01T15:42:24+00:00",
  "disableLocalAuth": false,
  "enablePurgeProtection": false,
  "encryption": {
    "keyVaultProperties": null
  },
  "endpoint": "https://myappconfiguration.azconfig.io",
  "id": "<id to my app config in my subscription and resource group>",
  "identity": null,
  "location": "eastus",
  "name": "MyAppConfiguration",
  "privateEndpointConnections": null,
  "provisioningState": "Succeeded",
  "publicNetworkAccess": null,
  "resourceGroup": "MyResourceGroup",
  "sku": {
    "name": "standard"
  },
  "softDeleteRetentionInDays": 7,
  "systemData": {
    "createdAt": "2022-05-01T15:42:24+00:00",
    "createdBy": "<my email>",
    "createdByType": "User",
    "lastModifiedAt": "2022-05-01T15:42:24+00:00",
    "lastModifiedBy": "<my email>",
    "lastModifiedByType": "User"
  },
  "tags": {},
  "type": "Microsoft.AppConfiguration/configurationStores"
}

I experience similar behavior through the portal UI also.
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by derekjoos** [comment]
Any progress on this?

**Comment by RakeshMohanMSFT** [comment]
@derekjoos Apologies for the delay, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@derekjoos Azure App Configuration's Soft delete feature allows recovery of your data such as key-values, feature flags, and revision history of a deleted store. **It's automatically enabled for all stores in the standard tier**. In this article, learn more about the soft delete feature and its functionality.

And in your example you are creating one using standard sku.
`az appconfig create -g MyResourceGroup -n MyAppConfiguration -l eastus --sku Standard`

We could get the recently created config array using the below command
`az appconfig list-deleted`

If you want to purge an already deleted config you can use this command
`az appconfig purge --name issue22714config`

**Comment by derekjoos** [comment]
@RakeshMohanMSFT Thanks for taking a look!

I have tried the command you provided several times (See To Produce section above) and I am not getting the expected results. I also had a colleague try them also. It doesn't appear that others are having this issue as I don't see others asking similar questions. Are there settings/permissions that I need to check in my environment that are required for these commands to work properly?

**Comment by RakeshMohanMSFT** [comment]
@derekjoos Perhaps you have issues with your permissions  (RBAC). Perhaps you do not have permissions to delete/purge.

**Comment by RakeshMohanMSFT** [comment]
@derekjoos Sure, will request the product team to get it updated. For now can i close this issue?
