### ISSUE TITLE
az webapp create-remote-connection needs Kudu Basic Auth enabled

### ISSUE THREAD

**Issue by ffarinha-msft** [Azure/azure-cli#22728]
On the following section (for the command az webapp create-remote-connection): https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-create-remote-connection

A NOTE should be added that in order to use this command, Kudu Basic Auth needs to be enabled or else you well get an HTTP 401 error message without further explanation for the reason.

![image](https://user-images.githubusercontent.com/92974977/171904121-fc9bd2da-2b8d-428b-85a1-ae00cb663b25.png)

Based on the bellow article, to make sure this is set all you need is to run: az resource update --resource-group <resource-group> --name scm --namespace Microsoft.Web --resource-type basicPublishingCredentialsPolicies --parent sites/<site-name> --set properties.allow=**true**

https://azure.github.io/AppService/2020/08/10/securing-data-plane-access.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SatishBoddu-MSFT** [comment]
Hello @ffarinha-msft What is the CLI version you are using, just wanted to check if it is the latest one.

![image](https://user-images.githubusercontent.com/62923178/172498587-e0237ce0-0b2c-4044-94b9-b8685c46514b.png)

**Comment by SatishBoddu-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
