### ISSUE TITLE
Edit of existing Azure SQL Firewall setting displays delete operation scope error

### ISSUE THREAD

**Issue by curlybapchap** [Azure/azure-cli#22723]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
Azure Portal => SQL Server => Security => Networking => Edit firewall rule

**Describe the bug**
Changing any of the firewall rule settings (name, strt ip or end ip) for an existing firewall rule generates a "cannot perform delete operation because following scope(s) are locked" error:

"ScopeLocked"
"The scope '/xxx/resourceGroups/xxx/providers/Microsoft.Sql/servers/xxx-db-server/firewallRules/PaulAccessFromHome
' cannot perform delete operation because following scope(s) are locked: '/..../resourceGroups/xxx/providers/Microsoft.Sql/servers/xxx-db-server'.
Please remove the lock and try again."}},"contentLength":463}

**To Reproduce**
Azure Portal => SQL Server => Security => Networking => Edit firewall rule => Change any of the three values in the "Edit firewall rule" popup, click OK and the click Save.

**Expected behavior**
I expect the previous behaviour when this screen was accessed from the previous sidebar menu option Settings => Firewall.
That version of the screen did not show a pop-up for the values, but allowed you to change them in-line by changing the existing values from labels to inputs.
I could then change any of the values, click Save and the new values were saved.

**Environment summary**
Azure portal (https://portal.azure.com/)

**Additional context**
Has there been a change to the process that an update actually performs a delete and create?

Perhaps a related issue : https://github.com/Azure/azure-cli/issues/11162

**Comment by RakeshMohanMSFT** [comment]
@curlybapchap This forum is specifically for azure cli related issues and not of portal. But looking at your issue it looks like some permission issue with your account. 

Read more about it here https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources?tabs=json#understand-scope-of-locks

Also if you have further questions, please open a support ticket from the portal.
