### ISSUE TITLE
'Dynamic template creates' should work with different profiles

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#2272]
After https://github.com/Azure/azure-cli/issues/2198, we should extend those dynamic template creates to support multiple API profiles.

**Comment by derekbekoe** [comment]
@tjprescott is this still something we need to track?
Thinking of closing.

**Comment by tjprescott** [comment]
I think it can safely be closed.  If issues arise, we can address them on a case-by-case basis.
