### ISSUE TITLE
Unable to deploy VM bicep template due to error: The value of parameter linuxConfiguration.ssh.publicKeys.keyData is invalid

### ISSUE THREAD

**Issue by ivana-a** [Azure/azure-cli#22725]
## Describe the bug

**Command Name**
`az deployment group create`

**Errors:**
```
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"The value of parameter linuxConfiguration.ssh.publicKeys.keyData is invalid.\",\r\n    \"target\": \"linuxConfiguration.ssh.publicKeys.keyData\"\r\n  }\r\n}"}]}}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az deployment group create --resource-group {} --template-file {} --name {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0 *
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@ivana-a Thank you for reaching out. It seems to be an issue with your template and not specific to cli command.

Can you go through this thread please and let us know if it helps? https://github.com/Azure/azure-quickstart-templates/issues/680
