### ISSUE TITLE
Improve --actions documentation for Az sql db audit-policy update

### ISSUE THREAD

**Issue by luticm** [Azure/azure-cli#22729]
"Az sql db audit-policy update" documentation doesn't state how to proper use parameter "--actions" with multiple entries, and example only shows one action group.

Trying to use command with comma separated list will fail with generic error "(InvalidBlobAuditActionsAndGroups) Invalid audit actions or action groups." (ex.: --actions SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP, FAILED_DATABASE_AUTHENTICATION_GROUP)

The proper way to use the parameter is to provide a **space separated list**, which is not intuitive at differs from PowerShell module (--actions SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP  FAILED_DATABASE_AUTHENTICATION_GROUP).

Suggestions: 
- Update parameter definition on "command_modules/sql/_params.py" informing this is NOT a comma separated list.
- Provide one additional example on command_modules/sql/_help.py for actions, including a list of actions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f158476-a880-5ae8-8b05-dc0dbe37b4a0
* Version Independent ID: c02a5c94-c6e5-e93f-1639-cde7b65f5702
* Content: [az sql db audit-policy](https://review.docs.microsoft.com/en-us/cli/azure/sql/db/audit-policy?branch=main&view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/sql/db/audit-policy.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sql/db/audit-policy.yml)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@luticm Thank you for reaching out, we are looking into it.
