### ISSUE TITLE
'az monitor metrics alert create' does not support namespaces containing dashes

### ISSUE THREAD

**Issue by sgerace** [Azure/azure-cli#22724]
**Related command**
az monitor metrics alert create

**Describe the bug**
When trying to create a new metric alert where the namespace contains a dash (e.g., `some-namespace`), the command fails with the message: "Couldn't find a metric named some-namespace.Sample Alert. Make sure the name is correct." even though the metric exists. It appears as though the namespace is not being parsed properly from the metric name and the command is attempting to find a metric named "some-namespace.Sample Alert" and not a metric named "Sample Alert" in the namespace "some-namespace"

**To Reproduce**
Attempt to create an alert for a custom metric in a namespace that contains a dash.

**Expected behavior**
I would expect the alert to be created successfully.

**Environment summary**
macOS Big Sur, az version: 1.37.0, installed via brew

**Additional context**
I've investigated the problem a little bit, and at first glance the issue appears to be related to the grammar used to parse the metric alert condition. If you look at where the `namespace` part is defined here: https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/grammar/metric_alert/MetricAlertCondition.g4#L11, you can see that "-" is not allowed. However, it is allowed in the definition of `metric`, which I believe is why the command is not recognizing the namespace in the definition.

**Comment by kairu-ms** [comment]
Hi @sgerace, thanks for your feedback. The namespace format maybe out of date now. We will update its format. Before that could you provide an example with '-' contained in namespace? Thanks.

**Comment by sgerace** [comment]
Hi @kairu-ms, in our case, we were attempting to create an alert for a custom metric located in a custom namespace. We were attempting something similar to:
```
az monitor metrics alert create -n alert1 -g {ResourceGroup} --scopes {VirtualMachineID}
        --condition "avg custom-namespace.Custom Metric > 90"
```
