### ISSUE TITLE
`az webapp up` should not change previous configuration when argument not specified

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-cli#22731]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az webapp up`

**Describe the bug**
I created a Python web app using the following command:
az webapp up --runtime "PYTHON:3.9" --logs

**To Reproduce**
- Create a new site and specify the runtime version as Python 3.9
  - `az webapp up --runtime "PYTHON:3.9"` 
- confirm that the webapp has a runtime of Python 3.9 
  - PS > `(az webapp list | convertfrom-json).siteConfig.linuxFxVersion`
- change some files
- Deploy the updates without specifying the --runtime argument 
  - `az webapp up` 
- See the output indicating that the runtime version is changing
  - `Updating runtime version from PYTHON|3.9 to PYTHON|3.7`
- See that the webapp now has a runtime version of Python 3.7
  - PS > `(az webapp list | convertfrom-json).siteConfig.linuxFxVersion`

**Expected behavior**
Once I have created a site, I expect that running `az webapp up` without any arguments will deploy new bits and that is it. No other settings or changes should be made regardless of the defaults.

**Environment summary**
Install Method: winget
Shell: PowerShell on Windows 11
Version:
azure-cli 2.37.0

core 2.37.0
telemetry 1.0.6

Extensions:
azure-dev 0.0.1b456
containerapp 0.1.3
rdbms-connect 1.0.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\charris.azure\cliextensions'

Python (Windows) 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 22:57:10) [MSC v.1929 32 bit (Intel)]

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding Service team to look into this ask

**Comment by panchagnula** [comment]
@StrawnSC is this being tracked with an ADO work item? If so can you create one, so we can track the updates & status of this during scrum.
