### ISSUE TITLE
New Premiumv2_LRS SKU for disks storage 

### ISSUE THREAD

**Issue by ramankumarlive** [Azure/azure-cli#22732]
### Related command

1.	az vm create must accept Premiumv2_LRS value for --storage-sku parameter
3.	az vm disk must accept Premiumv2_LRS value for –sku parameter
4.	az vmss create must accept Premiumv2_LRS value for --storage-sku parameter
5.	az vmss disk must accept Premiumv2_LRS value for –sku parameter

### Resource Provider

Microsoft.Compute/disks;Microsoft.Compute/virtualMachines;Microsoft.Compute/virtualMachineScaleSets

### Description of Feature or Work Requested

We are introducing a new disk storage SKU Premiumv2_LRS besides the current available SKUs: Standard_LRS, Premium_LRS, StandardSSD_LRS, UltraSSD_LRS, Premium_ZRS, StandardSSD_ZRS. We need to ensure that CLI uses the Compute's API version 2022-03-01 and sku and storage-sku parameters accepted by az vm, az disk, az vmss, az vmss disk commands must accept the new SKU Premiumv2_LRS. 

### Minimum API Version Required

2022-03-01, 2022-03-02

### Swagger PR link

https://github.com/Azure/azure-rest-api-specs/pull/18809/files
https://github.com/Azure/azure-rest-api-specs/pull/18786/files

### Target Date

2022-06-30

**Comment by yonzhan** [comment]
Compute

**Comment by wangzelin007** [comment]
Hi @ramankumarlive,

When I test Premiumv2_LRS, the server always returns:
SKU PremiumV2_LRS is not supported for resource type Disk in this region. Supported SKUs for this region are Premium_LRS,StandardSSD_LRS,Standard_LRS,UltraSSD_LRS.
May I ask which region should I use? 
I have already tried in these regions: west us, east us

-----

I want to confirm if these commands also need to support Premiumv2_LRS?
az disk create --sku
az disk update --sku
az image create --storage-sku
