### ISSUE TITLE
How to get Product Id and API Id information?

### ISSUE THREAD

**Issue by rudraTransact2** [Azure/azure-cli#22749]
How do you get product id and api id to be used in some of these commands?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 197d8382-ee16-6001-4941-768877379c0d
* Version Independent ID: 1423fa76-977f-ad88-8129-0b52a38e68e6
* Content: [az apim](https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/apim.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/apim.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@rudraTransact2 you can use these commands and store them in [variables ](https://docs.microsoft.com/en-us/cli/azure/azure-cli-variables)
[az apim product list -g "v-aghose-Mindtree" -n "ajaymttest" --query "[].[id, name]" -o table
az apim api list -g "v-aghose-Mindtree" -n "ajaymttest" --query "[].[id, name]" -o table
az apim api list -g "v-aghose-Mindtree" -n "ajaymttest" --filter-display-name "brtrachtest" --query "[].[id, name]" -o table](url)

**Comment by rudraTransact2** [comment]
See https://github.com/Azure/azure-cli/issues/22748
