### ISSUE TITLE
Consistent "az storage account management-policy" FAILURE

### ISSUE THREAD

**Issue by cT-m00cat** [Azure/azure-cli#22744]
## Description

**Command Name**
`az storage account management-policy create`

**Errors:**
```
Parameter 'ManagementPolicySchema.rules' can not be None.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage account management-policy create --account-name MyStorageAcc --resource-group MyResourceGroup --policy .\policy.json`

## Expected Behavior
I expect it to parse the json and create the policy but it consistently fails. I even tried in the cloudshell cli in the portal and it does the exact same thing.

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.31.0 *

Extensions:
azure-devops 0.23.0
interactive 0.4.5

```
## Additional Context
The json in the "policy.json" is as follows:
{
  "id": "/subscriptions/some_GUID_Here/resourceGroups/MyResourceGroup/providers/Microsoft.Storage/storageAccounts/MyStorageAccount/managementPolicies/default",
  "lastModifiedTime": "2022-06-06T15:07:53.922968+00:00",
  "name": "DefaultManagementPolicy",
  "resourceGroup": "MyResourceGroup",
  "type": "Microsoft.Storage/storageAccounts/managementPolicies",
  "policy": {
    "rules": [
      {
        "definition": {
          "actions": {
            "baseBlob": {
              "delete": {
                "daysAfterLastAccessTimeGreaterThan": null,
                "daysAfterModificationGreaterThan": 7.0
              },
              "enableAutoTierToHotFromCool": null,
              "tierToArchive": null,
              "tierToCool": null
            },
            "snapshot": null,
            "version": null
          },
          "filters": {
            "blobIndexMatch": null,
            "blobTypes": [
              "blockBlob"
            ],
            "prefixMatch": [
              "adxstudioportals/"
            ]
          }
        },
        "enabled": true,
        "name": "MyPolicyName",
        "type": "Lifecycle"
      }
    ]
  }
}

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
The policy format is wrong. See https://docs.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-overview#lifecycle-management-policy-definition
