### ISSUE TITLE
How can I find out which product contains a given API?

### ISSUE THREAD

**Issue by rudraTransact2** [Azure/azure-cli#22748]
I am trying to figure out if a given API is part of any products. The "az apim api list" command does not have any information on products for a given api.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 197d8382-ee16-6001-4941-768877379c0d
* Version Independent ID: 1423fa76-977f-ad88-8129-0b52a38e68e6
* Content: [az apim](https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/apim.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/apim.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@rudraTransact2 You can use these commands to check APIs mapped to a particular product 
https://docs.microsoft.com/en-us/cli/azure/apim/product/api?view=azure-cli-latest
```
az apim product api check --api-id
                          --product-id
                          --resource-group
                          --service-name
az apim product api list --product-id
                         --resource-group
                         --service-name
```

**Comment by rudraTransact2** [comment]
@RakeshMohanMSFT Here is what I did. I used following query to get the product id:

az apim product list -g "v-aghose-Mindtree" -n "ajaymttest" 
(from https://github.com/Azure/azure-cli/issues/22749)

The product id format from the above list is something similar to below:
`/subscriptions/xxxxxx-xxxx-xxxx-xxxx-xxxxx/resourceGroups/rg-xx-xxx/providers/Microsoft.ApiManagement/service/my-apim-service/products/my-product-name-1`

When I used the above product id in the following command, I got 404 Not Found.
`az apim product api list --product-id "/subscriptions/xxxxxx-xxxx-xxxx-xxxx-xxxxx/resourceGroups/rg-xx-xxx/providers/Microsoft.ApiManagement/service/my-apim-service/products/my-product-name-1" -g "rg-xx-xxx" --service-name "my-apim-service"`

Then I changed the command to following:
`az apim product api list --product-id "my-product-name-1" -g "rg-xx-xxx" --service-name "my-apim-service"`

**It worked.**

**_This means I can only use the product name and not product id._**

Does this mean either the documentation is incorrect or the command needs to be fixed? Or am I interpreting your documentation in a wrong way?

**Comment by RakeshMohanMSFT** [comment]
@rudraTransact2 i understand the confusion now, earlier the product name and id used to be different values to make the product id unique, now the entire path is considered to be unique "/subscriptions/****/resourceGroups/****/providers/Microsoft.ApiManagement/service/****/products/22748" therefore they are same. Also the product id is accepting the value after /products/**{Id}** and not the name though it can cause misunderstanding. I will let our PG know to consider this as a change request.
 {
      "id": "/subscriptions/****/resourceGroups/****/providers/Microsoft.ApiManagement/service/****/products/22748",
      "type": "Microsoft.ApiManagement/service/products",
      "name": "22748",
      "properties": {
        "displayName": "22748",
        "description": "22748",
        "terms": null,
        "subscriptionRequired": true,
        "approvalRequired": false,
        "subscriptionsLimit": null,
        "state": "notPublished"
      }
    },
