### ISSUE TITLE
Improve the az upgrade locking

### ISSUE THREAD

**Issue by mikeblakeuk** [Azure/azure-cli#22741]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az upgrade

**Describe the bug**
Terminal spawns the MSI so the MSI locks Python. If you close the terminal window, the installation will stop.
![image](https://user-images.githubusercontent.com/1986660/172174117-16bf1714-76a4-4218-bb72-ad90137420ae.png)

**To Reproduce**
Upgrade within a terminal

**Expected behavior**
Install with no locks.

**Environment summary**
Windows-10-10.0.19043-SP0, 
Python 3.10.4
MSI
Windows 10, Terminal, PowerShell

**Additional context**
none

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by in-fke** [comment]
This should have tons of votes - happens all the time.
