### ISSUE TITLE
Azure Image Builder API 2022-02-14 Update

### ISSUE THREAD

**Issue by zdelacerda-microsoft** [Azure/azure-cli#22751]
**Resource Provider** 
Azure VM Image Builder

**Description of Feature or Work Requested**
We now support VM Validation and custom resource group naming.

changes:

1. 1 new parameter for `az image builder create`
* `--stagingResourceGroup <string>`, type string, example inputs: "Custom_RG_Name001"

2. 3 new commands
*`az image builder validator`, get's validate information from template
*`az image builder validator add`, adds validate object to template
*`az image builder validator remove`, removes validate object from template
this includes 2 parameters
*`--continueDistributeOnFailure <boolean>`, type boolean (default false)
*`--sourceValidationOnly <boolean>`, type boolean (default false)

**Minimum API Version Required**
2022-02-14

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/18896

**Target Date**
ASAP

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@zdelacerda-microsoft Since the workload of this sprint has been arranged **super fully** *(**17-18** requirements have been committed in this sprint, **6** requirements have been postponed to the next sprint)*, so this requirement is proposed a little late. And this requirement needs much effort, so I am worried that there is not enough time for us to develop and release it in this sprint. May I ask can we release it in the next sprint (08-02)?

**Comment by yanzhudd** [comment]
Hello @zdelacerda-microsoft, there are some unified specifications in our cli's naming convention:
1. multi-word parameter should be hyphenated
2. all command names should contain a verb

Thus we propose to change the parameters to the following format. Could you please help to confirm this?

1. new parameter for `az image builder create`
- **`--staging-resource-group <string>`**, type string, example inputs: "Custom_RG_Name001"
2. 3 new commands
- **`az image builder validator show`**, get's validate information from template

- `az image builder validator add`, adds validate object to template
this includes 2 parameters
**`--continue-distribute-on-failure <boolean>`**, type boolean (default false)
**`--source-validation-only <boolean>`**, type boolean (default false)

- `az image builder validator remove`, removes validate object from template

**Comment by yanzhudd** [comment]
@zdelacerda-microsoft Hi, when we develop this feature, we meet some questions about the api version and we have sent an email named "**Question about Microsoft.VirtualMachineImages version from 2021-10-01 to 2022-02-14**" to you. Since this has blocked our development progress, please check if there is a breaking change from 2021-10-01 to 2022-02-14 version and reply to me **before July 25th**. Otherwise, this sprint will not have enough time for us to develop and test, so we will have to postpone it to the next sprint (09-06)
Thanks for your understanding~

**Comment by zdelacerda-microsoft** [comment]
Hi @yanzhudd these changes look good to me. I'm going to send this PR to the team to get one more confirmation. Please hold off until you hear back from me or another reviewer. Thanks

**Comment by feiyushi** [comment]
> Hello @zdelacerda-microsoft, there are some unified specifications in our cli's naming convention:
> 
> 1. multi-word parameter should be hyphenated
> 2. all command names should contain a verb
> 
> Thus we propose to change the commands to the following format. Could you please help to confirm this?
> 
> 1. new parameter for `az image builder create`
> 
> * **`--staging-resource-group <string>`**, type string, example inputs: "Custom_RG_Name001"
> 
> 2. 3 new commands
> 
> * **`az image builder validator show`**, get's validate information from template
> * `az image builder validator add`, adds validate object to template
>   this includes 2 parameters
>   **`--continue-distribute-on-failure <boolean>`**, type boolean (default false)
>   **`--source-validation-only <boolean>`**, type boolean (default false)
> * `az image builder validator remove`, removes validate object from template

After checking the az cli doc for [az image builder](https://docs.microsoft.com/en-us/cli/azure/image/builder?view=azure-cli-latest), I found there are usually 3 verbs for `customizer` and `output`: `add`, `clear`, `remove`. not sure about `show` as it's not there for `customizer` and `output`

**Comment by yanzhudd** [comment]
Hi @zdelacerda-microsoft, when we update an existing image template resource, the below error is reported. **If the image builder still does not support this update operation?** 
![image](https://user-images.githubusercontent.com/105691024/180416632-f3c75312-b560-449d-8019-d947eb17b44a.png)
If so, is parameter **`--defer`** need to be added to **`az image builder validator`** subgroup to manage validate of image template in the local cache?

**Comment by feiyushi** [comment]
> 

I see that customizer commands group has the same `--defer` parameter. Considering they face the same issue, I'd say it's ok.

**Comment by KshitijAgrawal** [comment]
@zdelacerda-microsoft we dont have any breaking changes right? All of these are new features, so we shouldn't have.

**Comment by zdelacerda-microsoft** [comment]
> @zdelacerda-microsoft we dont have any breaking changes right? All of these are new features, so we shouldn't have.

there were some small breaking changes. I forwarded the breaking change email thread so they can see what we did. (sorry there are multiple threads of communication between myself and yanzhudd so that is why i'm not replying to all the comments here)
