### ISSUE TITLE
typo at "az vm encryption enable"

### ISSUE THREAD

**Issue by jkb1372** [Azure/azure-cli#22763]
..., see: ttps://docs.microsoft.com/azure/security/fundamentals/azure-disk-encryption-vms-vmss.

Should be 'https', not 'ttps'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4762f857-8a1e-f1bb-7843-3d8fefe28f8e
* Version Independent ID: 91ce956c-c915-5053-56b0-a489fb2f7b00
* Content: [az vm encryption](https://docs.microsoft.com/en-us/cli/azure/vm/encryption?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm/encryption.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm/encryption.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@cxznmhdcxz Please help correct the help message of `az vm encryption enable` command
![Screenshot 2022-06-08 105725](https://user-images.githubusercontent.com/16612065/172522074-7edc1fd1-7393-4c20-be9a-48eff6a18af2.png)
