### ISSUE TITLE
`az acr repository show-tags` Unable to get AAD authorization tokens

### ISSUE THREAD

**Issue by ben-garside** [Azure/azure-cli#22766]
When running: `az acr repository show-tags -n <regName> --repository <repoName> -o tsv` in an ADO pipeline (so running as a service priciple) we are getting the following error:

    Unable to get AAD authorization tokens with message: An error occurred: CONNECTIVITY_ACCESS_TOKEN_ERROR
    Access to registry '<regName>.azurecr.io' was denied. Response code: 504. Please try running 'az login' again to refresh permissions.

We have tried running this locally following these steps:
1. `az login --service-principal -u <spId> -p <secret> --tenant <tenant>`
2. `az account set -s <subId>`
3. `az acr repository show-tags -n <regName> --repository <repoName>  -o tsv`

The result will always show the tags for my repo, but will also _sometimes_ show the same error as above.
![image](https://user-images.githubusercontent.com/9353593/172430155-8270aa98-5547-4b44-b55b-9c7bb35510d5.png)

I have checked and the SP has contributor access to the acr resource and if run under a user account we are not seeing the issue.

**Comment by ben-garside** [comment]
Also, to add. this has previously worked without issue. We are only seeing this error as of today.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@ben-garside did you try this action plan? https://docs.microsoft.com/en-us/azure/container-registry/container-registry-health-error-reference#connectivity_access_token_error
