### ISSUE TITLE
az security alerts-suppression-rule upsert_scope is not accepting IP ranges for entities.ip.address field

### ISSUE THREAD

**Issue by DmitriSmirnovCTL** [Azure/azure-cli#22769]
## Describe the bug

**Command Name**
`az security alerts-suppression-rule upsert scope`

**Errors:**
```
Operation returned an invalid status 'Bad Request'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az security alerts-suppression-rule update --rule-name SQL_DW_GeoAnomaly-Name --alert-type "SQL.DW_GeoAnomaly" --reason "SpecificEntityFalsePositive" --state "Enabled"`
- `az security alerts-suppression-rule upsert_scope --rule-name SQL_DW_GeoAnomaly0-Name --field "entities.ip.address" --any-of "192.168.0.0/16"`

## Expected Behavior
{
  "in": "192.168.0.0/16",
  "field": "entities.ip.address"
}

## Environment Summary
```
macOS-12.4-arm64-arm-64bit, Darwin 21.5.0
Python 3.10.4
Installer: HOMEBREW

azure-cli 2.37.0

Extensions:
sentinel 0.1.2
interactive 0.4.5

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@DmitriSmirnovCTL There is a known bug with --any-of parameter and it is being worked up, currently we do not any ETA for the fix.
