### ISSUE TITLE
`az webapp up` says it's "creating" AppServicePlan even when the plan already exists

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-cli#22767]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az webapp up`

**Describe the bug**
When using `az webapp up` to update a deployment and specifying the --runtime, --resource-group and --name, it re-uses the same AppServicePlan, but the output in the console says:

```
...
Creating AppServicePlan '[plan_name]' ...
...
```
This gives the mistaken impression that it is in fact creating a new plan

**To Reproduce**
1. run `az webapp up --runtime 'PYTHON:3.9' -g my-group-1 --name my-app-1`
2. notice it will tell you it is creating an AppServicePlan
3. run `az webapp up --runtime 'PYTHON:3.9' -g my-group-1 --name my-app-1`
4. notice it will tell you it is creating an AppServicePlan with the same name as above

**Expected behavior**
Rather than writing "Creating AppServicePlan" to the console
If there are changes to the AppServicePlan then it should say "Updating AppServicePlan"
If there are no changes to the AppServicePlan it should not mention the AppServicePlan at all

**Environment summary**
Install Method: winget
Shell: PowerShell on Windows 11
Version:
azure-cli 2.37.0

core 2.37.0
telemetry 1.0.6

Extensions:
azure-dev 0.0.1b456
containerapp 0.1.3
rdbms-connect 1.0.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\charris.azure\cliextensions'

Python (Windows) 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 22:57:10) [MSC v.1929 32 bit (Intel)]

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding Service Team to look into this ask.

@AzureAppServiceCLI @antcp Could you please look into this ask and provide an update ?

**Comment by panchagnula** [comment]
thanks for reporting. We will investigate & fix.

**Comment by flytzen** [comment]
It seems that a side effect is that if you have a Policy that puts restrictions on the App Service Plan - for example requiring certain Tags to be present - `webapp up` will fail with a policy violation. 
In other words, it looks like the CLI goes through all the pre-flight checks for actually creating the app service plan - even though it already exists.

**Comment by seligj95** [comment]
closing, linked PR resolves this
