### ISSUE TITLE
Terraform and CLI work for GA of |

### ISSUE THREAD

**Issue by arikt-ms** [Azure/azure-cli#22772]
Related command

Resource Provider
Microsoft.RecoveryService

Description of Feature or Work Requested
Azure Site Recovery allows customer to enable disaster recovery on their machines. As a part of the service, we allow customers to perform DR of Azure VMs, VMware VMs, Hyper-V VMs and physical servers. This feature focuses on the DR of VMware VMs and we are working on the GA release of this feature. Currently, this capability already exists, but we have made improvements to the process and experience and are re-launching the modernized experience.

Minimum API Version Required

Swagger Link
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices/stable/2021-10-01/service.json

Target Date
15th August 2022

**Comment by yonzhan** [comment]
RecoveryService

**Comment by jsntcy** [comment]
@arikt-ms, there is another similar request in https://github.com/Azure/azure-cli/issues/22631, are they the same?

**Comment by arikt-ms** [comment]
Oops ... this must have been submitted accidentally, my bad. I was using the contents of the issue submitted for Recovery Service as a template to author a similar issue for our service, however our swagger spec is not ready for this yet. I am closing this issue and will open another one when we are ready. Apologies for inconvenience.
