### ISSUE TITLE
Add wait/no-wait support to Commands

### ISSUE THREAD

**Issue by sdavis3** [Azure/azure-cli#22788]
az vm run-command needs ```--no-wait``` option.

**Related command**
``` 
az vm run-command invoke -g rgName -n vmName --no-wait --command-id RunPowerShellScript --scripts @c:\temp\run_this_script.ps1
```

**Is your feature request related to a problem? Please describe.**
When trying to run PowerShell scripts against a VM, the CLI forces you to await the results before being able to continue. A long running command reduces productivity. A ```--no-wait``` option could significantly improve productivity.

**Describe the solution you'd like**
Add ```--no-wait``` to the ```run-command``` invocation.

**Describe alternatives you've considered**
The alternative is to open multiple terminal windows and issue separate commands. This is the same experience as using the portal to navigate between VMs to issue commands.

**Additional context**
N/A

**Comment by yonzhan** [comment]
compute

**Comment by zhoxing-ms** [comment]
@sdavis3 Since our work in this sprint has been fully arranged, I plan to schedule this requirement for development and release in the next sprint (**09-06**). Can you accept this time?

**Comment by sdavis3** [comment]
Yes, of course. Thank you for the update.

**Comment by PARADISSEEKR** [comment]
Hi @sdavis3 , do we need to add `--no-wait` to `az vmss run-command` as well?

**Comment by sdavis3** [comment]
I think that makes sense, but it’s not part of my immediate scenario.
