### ISSUE TITLE
`az webapp up` needs --startup-file argument for single command deployment of FastAPI apps

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-cli#22789]
**Related command**
`az webapp up`, `az webapp create`

**Is your feature request related to a problem? Please describe.**
I'm trying to write docs on deploying python webapps with `az webapp up`. However, because app service doesn't have auto-detection for FastAPI applications, instead of running a single command, I have to run `az webapp up` followed by another long command:

`az webapp config set --resource-group charris_rg_1234 --name 'glacial-island-3456' --startup-file "python -m uvicorn main:app --host 0.0.0.0`

or a shorter one if I include a startup.sh script in my app:

`az webapp config set --resource-group charris_rg_1234 --name 'glacial-island-3456' --startup-file "startup.sh"`

**Describe the solution you'd like**
I would like `az webapp up` to include the --startup-file argument so I can deploy my FastAPI application with a single command:

`az webapp up --startup-file "startup.sh"`

**Describe alternatives you've considered**
One alternative is to not use `az webapp up`, but that means creating the rg and resources individually with more steps, or using something like VS Code which is already included in the doc i'm working on.

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding Service team to look into this ask.

@AzureAppServiceCLI @antcp Could you please look into this ask and provide an update on this ?

**Comment by panchagnula** [comment]
This is not something being considered for up at this time. We will add this to our internal backlog as a feature request, so we can discuss/ track this as needed. Thanks!
