### ISSUE TITLE
[Feature Request] Add routing intent CRUD as child resource of virtual hub

### ISSUE THREAD

**Issue by zaynchen115** [Azure/azure-cli#22795]
**Related command**

Similar PS command, not sure about cli
Get-AzRoutingIntent
Get-AzRoutingPolicy
Add-AzRoutingPolicy
New-AzRoutingPolicy
New-AzRoutingIntent
Set-AzRoutingPolicy
Set-AzRoutingIntent
Remove-AzRoutingPolicy
Remove-AzRoutingIntent

**Is your feature request related to a problem? Please describe.**

Virtual Wan customers will be able to create a routing intent resource (which will be a child resource of the VirtualHub resource) which will enable them to configure custom routing policies that will help in either routing their traffic via firewall deployed in the hub or via a network virtual appliance deployed in a spoke vnet connected to the virtual hub.

**Describe the solution you'd like**

Provide command to let customer create routing policy and routing intent in the virtual hub
Customers are able to update the routing intent in virtual hub or routing policy in routing intent
Customers are able to delete the routing intent or routing policy
**Describe alternatives you've considered**

**Additional context**

powershell PR https://github.com/Azure/azure-powershell/pull/18088/
swagger PR https://github.com/Azure/azure-rest-api-specs/pull/15998

**Comment by yonzhan** [comment]
network

**Comment by zaynchen115** [comment]
@necusjz Did the dev part finished?

**Comment by necusjz** [comment]
@zaynchen115, as planned we'll work on this feature in current sprint (~08/02/2022). We just closed a duplicated request as above, sorry for misleading.
