### ISSUE TITLE
CLI support for predictive autoscale 

### ISSUE THREAD

**Issue by ritaroloff** [Azure/azure-cli#22794]
Targeting GA mid-October
Service: Autoscale

**Comment by yonzhan** [comment]
Did you go through the PLR process and please put more info about this such as swagger spec link, etc.

**Comment by yonzhan** [comment]
Autoscale for monitor

**Comment by ritaroloff** [comment]
Sorry the late reply. Yes we are going through the PLR process. Swagger link is here: https://github.com/Azure/azure-rest-api-specs/pull/19765/

**Comment by jsntcy** [comment]
@ritaroloff, will there be a new API version for GA later?

**Comment by ritaroloff** [comment]
No there will not be a new API version for GA. @jsntcy

**Comment by jsntcy** [comment]
@ritaroloff, so you will use the preview API (https://github.com/azure/azure-rest-api-specs/blob/main/specification/monitor/resource-manager/Microsoft.Insights/preview/2021-05-01-preview/autoscale_API.json) for October GA release?

**Comment by ritaroloff** [comment]
@PatrickTseng , can you verify that the above preview link is accurate for GA?

**Comment by jsntcy** [comment]
@ritaroloff, @PatrickTseng, https://github.com/Azure/azure-rest-api-specs/blob/main/specification/monitor/resource-manager/Microsoft.Insights/stable/2022-10-01/autoscale_API.json, is this API used for October GA release?

**Comment by PatrickTseng** [comment]
Yes, that is correct.
