### ISSUE TITLE
`az keyvault role assignment create` doesn't add `Authorization` header and body

### ISSUE THREAD

**Issue by chgeuer** [Azure/azure-cli#22801]
## Describe the bug

**Command Name**

`az keyvault role assignment create`

**Errors:**

```
Operation returned an invalid status 'Not Found'
```

### Run on 'latest' version (2.37.0)

```shell
$ az version

{
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "application-insights": "0.1.16",
    "azure-iot": "0.14.1",
    "datafactory": "0.5.0",
    "front-door": "1.0.16",
    "storage-preview": "0.8.2"
  }
}
```
### Have a KeyVault which is enabled for RBAC 

```shell
az keyvault show `
   --resource-group $resourceGroupName `
   --name $keyVaultName

{
  "id": "/subscriptions/.../resourceGroups/.../providers/Microsoft.KeyVault/vaults/SRBKV07062chgp",
  "location": "westeurope",
  "name": "SRBKV07062chgp",
  "properties": {
    "vaultUri": "https://srbkv07062chgp.vault.azure.net/"
    "enableRbacAuthorization": true,
    "sku": { "family": "A", "name": "standard" },
    ...
    "provisioningState": "Succeeded",
    "publicNetworkAccess": "Enabled",
    "tenantId": "..."
  },
  "resourceGroup": "...",
  "type": "Microsoft.KeyVault/vaults"
}
```

### Try to use `az keyvault role assignment create` against the KeyVault
```shell
$ az keyvault role assignment create `
    --scope "/keys" `
    --id https://srbkv07062chgp.vault.azure.net/ `
    --role 00482a5a-887f-4fb3-b363-3b7fe8e74483 `
    --assignee-object-id 28ca90d0-bbb7-4ccb-b7ca-f71f05d7cb92 `
    --assignee-principal-type User

Operation returned an invalid status 'Not Found'
```

### Underlying HTTP trace

The underlying HTTP trace (captured with Fiddler) shows absence of both an `Authorization` header, as well as a JSON body containing the details. 

According to the (HSM) [docs](https://docs.microsoft.com/en-us/rest/api/keyvault/managedhsm-rbac/role-assignments/create#putroleassignments), the call should contain a body, but `az` CLI didn't put it in.

```http
PUT https://srbkv07062chgp.vault.azure.net/keys/providers/Microsoft.Authorization/roleAssignments/387ea84c-8003-481a-bd8c-2daa921f8f13?api-version=7.2-preview HTTP/1.1
Host: srbkv07062chgp.vault.azure.net
User-Agent: azsdk-python-keyvault-administration/4.0.0b3 Python/3.10.4 (Windows-10-10.0.22000-SP0)
Accept-Encoding: gzip, deflate
Accept: application/json
Connection: keep-alive
Content-Type: application/json
Content-Length: 0
x-ms-client-request-id: 598b56db-e7c1-11ec-b1e0-a0cec8f8f997

HTTP/1.1 404 Not Found
Content-Type: text/html
Date: Thu, 09 Jun 2022 06:56:55 GMT

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>404 - File or directory not found.</title></head>
<body>
...Server Error
...404 - File or directory not found.
...
</body></html>
```

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0

Extensions:
application-insights 0.1.16
azure-iot 0.14.1
datafactory 0.5.0
front-door 1.0.16
storage-preview 0.8.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by evelyn-ys** [comment]
`az keyvault role assignment create` only accepts a HSM but you are using a vault
![image](https://user-images.githubusercontent.com/10227683/172850200-569db75a-10fa-4fb2-a428-f051dc744a41.png)

**Comment by chgeuer** [comment]
Thanks @evelyn-ys , you're right, I'm using a 'regular' vault, not a dedicated HSM. 

When looking at the documentation for the feature (https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli), the article indicated this:

> Key Vault resource provider supports two resource types: vaults and managed HSMs. Access control described in this article only applies to vaults. To learn more about access control for managed HSM, see [Managed HSM access control](https://docs.microsoft.com/en-us/azure/key-vault/managed-hsm/access-control).

So my understanding was that the given `az` command applies to vaults as well.

**Comment by chgeuer** [comment]
So are you saying for a vault, the RBAC data is a regular role assignment in the ARM management plane, and for an HSM the permissions are inside the HSM?
