### ISSUE TITLE
"az functionapp deployment source config-zip --slot" generates 503 on production slot

### ISSUE THREAD

**Issue by JSCProjects** [Azure/azure-cli#22808]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az functionapp deployment source config-zip --slot staging --src ".\azure-net-function.zip" -n FunctionName -g ResourceGroupName

**Describe the bug**
I've got multiple azure v4 functions on .net 6 running with slots and when I deploy our functions with Azure Devops task AzureFunctionApp@1 on our staging slot it gives 503 after the command is accepted. The same thing happens when I deploy the zip with the above cli command!

**To Reproduce**
Run cli command which is described in **Related command**

**Expected behavior**
That the production slot never gives a 503 when I deploy to staging

**Environment summary**
Azure Dev Ops & Azure Cli

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@JSCProjects Apologies for the late reply. Thanks for reaching out to us and reporting this issue. This would require us to look into the backend logs to identify the cause. Could you please file a support ticket so that our support professionals can reach out to you for more details ? Awaiting you reply.

**Comment by JSCProjects** [comment]
@navba-MSFT do you mean via the Azure portal?

**Comment by navba-MSFT** [comment]
@JSCProjects You can open the support ticket using [Azure portal](https://portal.azure.com/)  or [Support ticket ](https://azure.microsoft.com/en-us/support/create-ticket/)website.

**Comment by JSCProjects** [comment]
Opening a support ticket is disabled according to the portal I first have to contact our service provider

**Comment by navba-MSFT** [comment]
@JSCProjects Sure. Also you can reach out to your subscription owner / admin and take their help to create a support ticket from the azure portal since they will be having permissions to create the support ticket.

**Comment by navba-MSFT** [comment]
@JSCProjects A quick follow-up on this to check the status of opening a support ticket. Awaiting your reply.

**Comment by JSCProjects** [comment]
We have created a ticket with our service provider, but we don't have received a ticket number from Microsoft

**Comment by navba-MSFT** [comment]
@JSCProjects I am following up to check if you got the ticket # created from Microsoft Support.

**Comment by JSCProjects** [comment]
Hi @navba-MSFT we received a tracking number friday late in the evening. It's TrackingID#2206160040002677

**Comment by navba-MSFT** [comment]
@JSCProjects Thanks for the update. Our CSS engineer has reached out to the point of contact mentioned in support ticket and currently waiting for the details of the resource and time of the issue. Once the support professional gets this info, he should be able to take this forward and identify the cause of the issue and assist you further.

**Comment by navba-MSFT** [comment]
@JSCProjects Since the issue is worked upon on the support ticket we are proceeding with closure of this GitHub thread.
