### ISSUE TITLE
Azure-cli incompatible with azureml-core

### ISSUE THREAD

**Issue by MatthewGleeson** [Azure/azure-cli#22816]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

I'm trying to install this package in a python environment. In my requirements.txt, I have:

azure-cli==2.37.0
azureml-core==1.42.0

**Describe the bug**

Cannot pip install both packages, the conflict is caused by:
    azure-cli 2.37.0 depends on azure-mgmt-resource==21.1.0b1
    azureml-core 1.42.0 depends on azure-mgmt-resource<=21.0.0 and >=15.0.0

These are the most recent versions of both packages, so I would expect them to be able to coexist in the same python environment. Is it possible to relax the strict version dependency on azure-mgmt-resource?

**To Reproduce**

**Expected behavior**

The most recent version of both packages should work together. I've tried relaxing dependencies on either side but the only compatibility I was able to find is azure-cli 2.37.0, azureml-core 1.14. However azureml-core 1.14 doesn't contain the modules that I need.

**Environment summary**

Tested on conda environment on windows, AzureDevops Build Pipeline. Both fail with the same error.

**Additional context**

Cross-post on azure-sdk-for-python repository: https://github.com/Azure/azure-sdk-for-python/issues/24787

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@MatthewGleeson Looks like this has been addressed in the linked python issue. Closing this.
