### ISSUE TITLE
VM/VMSS create: expose generic set/add for extra resource setting 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#2281]
This is to expose the extensiblity point for users to supply uncommon extra resource settings, which otherwise would become a blocking issue for them. Based on feedback I have received, this will help user supply plan info on creating VM from market palce image, turning on more ports, etc. 
The flag can be like generic set, `--add, --remove, --set`

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
