### ISSUE TITLE
https://docs.microsoft.com/en-us/azure/aks/devops-pipeline?pivots=pipelines-yaml&tryIt=true&source=docs#code-try-1

### ISSUE THREAD

**Issue by rotorr** [Azure/azure-cli#22812]
## Describe the bug

**Command Name**
`az acr create`

**Errors:**
```
argument error: Connected registry name must use only lowercase.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr create --resource-group {} --name {} --sku {}`

## Environment Summary
```
Linux-5.4.0-1083-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
containerapp 0.3.5
application-insights 0.1.15
aks-preview 0.5.51
azure-firewall 0.13.0
ai-examples 0.2.5
ssh 1.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@rotorr Thanks for reaching out to us and sharing this feedback. Could you please use the _lowercase_ for the ACR name and test again ? More Info [here](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-create).

>--name -n
>The name of the container registry. It should be specified in lower case. 

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@rotorr I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you are still facing the same issue after using lowercase for ACR name. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@rotorr The action plan is currently pending on you to test the above plan. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
