### ISSUE TITLE
Commands fail to load all of a sudden

### ISSUE THREAD

**Issue by grgarcia-ms** [Azure/azure-cli#2282]
Error loading command module 'acr'
Error loading command module 'acs'
Error loading command module 'appservice'
Error loading command module 'cloud'
Error loading command module 'container'
Error loading command module 'network'
Error loading command module 'profile'
Error loading command module 'resource'
Error loading command module 'role'
Error loading command module 'storage'
Error loading command module 'vm'

Log says: error loading command module [one of the above]

**Comment by derekbekoe** [comment]
@grgarcia-ms what's the output from `az --debug` and `az --version`?

**Comment by grgarcia-ms** [comment]
As for az --debug, It is full of "error loading command X", and no module named Y not found.

As for version:
acr (0.1.1b2)
acs (0.1.1b3)
appservice (0.1.1b2)
cloud (0.1.2rc2)
component (0.1.0rc2)
configure (0.1.1b3)
container (0.1.1b2)
context (0.1.1b2)
core (0.1.1b3)
feedback (0.1.1b2)
network (0.1.1b2)
nspkg (0.1.2)
profile (0.1.1b2)
resource (0.1.1b2)
role (0.1.1b2)
storage (0.1.1b2)
vm (0.1.1b3)

**Comment by grgarcia-ms** [comment]
I uninstalled everything and installed again, issue solved. No idea what happened there...
