### ISSUE TITLE
 az aks get-credentials: FAILURE

### ISSUE THREAD

**Issue by HariHaraReddyD** [Azure/azure-cli#22825]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
'clusters'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/acs/custom.py, ln 1180, in merge_kubernetes_configurations
    _handle_merge(existing, addition, 'clusters', replace)
cli/command_modules/acs/custom.py, ln 1115, in _handle_merge
    if existing[key] is None:
KeyError: 'clusters'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --name {} --resource-group {} --overwrite-existing`

## Environment Summary
```
Linux-4.18.0-348.20.1.el8_5.x86_64-x86_64-with-redhat-8.5-Ootpa
Python 3.6.8

azure-cli 2.1.0

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@HariHaraReddyD Thanks for reaching out to us and sharing this feedback. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@HariHaraReddyD  You can check under the user profile for file ~/.kube/config. There are 3 required sections which must be present: clusters, contexts and users. I feel there seems to be an issue while reading the Clusters section in this config file. You can try to rename or delete the file and run the [az aks get-credentials ](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials)command and check if that works.

Alternatively you can pass the --file or --overwrite-existing parameter and run the command again. More Info [here](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials).

on a side note: I also see you are using a very old version of AzCLI. Please upgrade it to the [most recent version.](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli#install-or-update)

Please let us know if you still need any assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@HariHaraReddyD I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by HariHaraReddyD** [comment]
cleaning up & re-installing aws cli worked for me.
Thanks.
