### ISSUE TITLE
bash run "az login --scope https://management.azure.com/.default " raise error

### ISSUE THREAD

**Issue by MeepoZhao** [Azure/azure-cli#22831]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

Authentication failed
invalid_resource: AADSTS500011: The resource principal named https://management.azure.com was not found in the tenant named Bosch China. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: beb23d90-3822-4ac3-8e5d-a2e74e41b600 Correlation ID: 089eac60-7c0c-405a-86da-bfa9a8261369 Timestamp: 2022-06-10 13:33:30Z. (https://login.partner.microsoftonline.cn/error?code=500011)

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The error `AADSTS500011` is from AAD service, not Azure CLI.

Are you using the `AzureCloud` public cloud? In sovereign clouds or Azure Stack, the resource URI of ARM is different. For example, in `AzureChinaCloud`, it's 

https://github.com/Azure/azure-cli/blob/31e396bed780b8db5641d73ba02fb4ce66db194e/src/azure-cli-core/azure/cli/core/cloud.py#L343

Please make sure you are using the correct ARM URI and try again.

If you still can't solve it, please [contact Azure Support](https://azure.microsoft.com/en-us/support/create-ticket/) or your cloud administrator.

**Comment by MeepoZhao** [comment]
I use the CLI to sign in AzureChinaCloud, and then i use the .py file to access the Cloud, but raise error. so i use the CLI once again and run the command according to error information.

the error is below:
AzureCliCredential.get_token failed: Please run 'az login' to set up an account
Traceback (most recent call last):
  File "C:\Zhao\AnacondaEnvs\myazure\lib\site-packages\azure\identity\_credentials\azure_cli.py", line 141, in _run_command
    return subprocess.check_output(args, **kwargs)
  File "C:\Zhao\AnacondaEnvs\myazure\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Zhao\AnacondaEnvs\myazure\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmd', '/c', 'az account get-access-token --output json --resource https://management.azure.com']' returned non-zero exit status 1.
