### ISSUE TITLE
PowerShell command to perform swap with preview

### ISSUE THREAD

**Issue by lipalath-ms** [Azure/azure-cli#22833]
I have an **_Azure Function App_** with two deployment slots. Is there a PowerShell command to **_swap deployment slots with preview_**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9f5bf9-d178-de1a-645b-be6947a7c049
* Version Independent ID: cb7fb876-160c-e6d9-d473-7ac39b930b48
* Content: [az webapp deployment slot](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/slot?view=azure-cli-latest#az-webapp-deployment-slot-swap)
* Content Source: [latest/docs-ref-autogen/webapp/deployment/slot.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/deployment/slot.yml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@lipalath-ms Apologies for the delay. Thanks for reaching out to us and sharing this feedback. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@lipalath-ms Could you use the below Azure CLI command to achieve this ask ?

>az functionapp deployment slot swap  -g MyResourceGroup -n MyUniqueApp --slot staging --target-slot production

More Info [here](https://docs.microsoft.com/en-us/cli/azure/functionapp/deployment/slot?view=azure-cli-latest#az-functionapp-deployment-slot-swap). Awaiting your reply.

**Comment by lipalath-ms** [comment]
This is not swapping with preview. On trying this, I see app settings are set incorrectly.

**Comment by lipalath-ms** [comment]
![image](https://user-images.githubusercontent.com/6519992/173436908-2d4b8fd7-8cea-439e-a484-4865ba3ebab8.png)

**Comment by navba-MSFT** [comment]
@lipalath-ms Thanks for getting back and clarifying the ask. Could you please test with the below command and let me know if that helps?

>$ParametersObject = @{targetSlot  = "[slot name – e.g. "production"]"}
Invoke-AzResourceAction -ResourceGroupName [resource group name] -ResourceType Microsoft.Web/sites/slots -ResourceName [app name]/[slot name] -Action applySlotConfig -Parameters $ParametersObject -ApiVersion 2015-07-01

Refer [this](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots#initiate-a-swap-with-a-preview-multi-phase-swap-and-apply-destination-slot-configuration-to-the-source-slot) docs for the example commands.

**Comment by navba-MSFT** [comment]
@lipalath-ms I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let me know if you had a chance to follow the above plan. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@lipalath-ms The action is currently pending you to follow the above action plan. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
