### ISSUE TITLE
Auto Delete on Idle not working as intended

### ISSUE THREAD

**Issue by amoradiaz** [Azure/azure-cli#22834]
**Related command**
`az servicebus topic subscription update --auto-delete-on-idle "PT5M"  --ids <xyz>`
`az servicebus topic subscription update --auto-delete-on-idle "00:05:00"  --ids <xyz>`

**Describe the bug**
After calling any of these commands the operation seemingly succeeds but nothing gets updated. 

The resulting JSON shows a random date:

```json
{
  "accessedAt": "0001-01-01T00:00:00+00:00",
  **"autoDeleteOnIdle": "10675199 days, 2:48:05.477581",**
  "clientAffineProperties": null,
  "countDetails": {
    "activeMessageCount": 0,
    "deadLetterMessageCount": 0,
    "scheduledMessageCount": 0,
    "transferDeadLetterMessageCount": 0,
    "transferMessageCount": 0
  },
  "createdAt": "2022-06-10T15:38:19.880700+00:00",
  "deadLetteringOnFilterEvaluationExceptions": true,
  "deadLetteringOnMessageExpiration": false,
  "defaultMessageTimeToLive": "366 days, 0:00:00",
  "duplicateDetectionHistoryTimeWindow": null,
  "enableBatchedOperations": true,
  "forwardDeadLetteredMessagesTo": null,
  "forwardTo": "...",
  "id": "<xyz>",
  "isClientAffine": false,
  "location": "East US 2",
  "lockDuration": "0:01:00",
  "maxDeliveryCount": 10,
  "messageCount": 0,
  "name": "<abc>",
  "requiresSession": false,
  "resourceGroup": "mygroup",
  "status": "Active",
  "systemData": null,
  "type": "Microsoft.ServiceBus/Namespaces/Topics/Subscriptions",
  "updatedAt": "2022-06-10T15:38:19.880700+00:00"
}
```

**To Reproduce**
Run command above on an existing topic subscription

**Expected behavior**
After calling this command I would expect the referenced subscription **Auto Delete on Idle** time updated to 5 minutes.

**Environment summary**

```
azure-cli                         2.37.0

core                              2.37.0
telemetry                          1.0.6

Extensions:
arcdata                            1.4.1
containerapp                       0.3.5

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xyz\.azure\cliextensions'

Python (Windows) 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 22:57:10) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@amoradiaz Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@amoradiaz I wasn't able to reproduce this issue. While I ran the below command, I was able to set the `autoDeleteOnIdle` property successfully. See below:

>az servicebus topic subscription update --resource-group MyRGName --namespace-name MyResource --topic-name MyTopic --name MySubName --auto-delete-on-idle PT7M

**Output:**
>{
  "accessedAt": "0001-01-01T00:00:00+00:00",
  **"autoDeleteOnIdle": "0:07:00",**
  "clientAffineProperties": null,
  "countDetails": {
    "activeMessageCount": 0,
    "deadLetterMessageCount": 0,
    "scheduledMessageCount": 0,
    "transferDeadLetterMessageCount": 0,
    "transferMessageCount": 0
  },
  "createdAt": "2022-06-14T07:50:42.039807+00:00",
  "deadLetteringOnFilterEvaluationExceptions": false,
  "deadLetteringOnMessageExpiration": false,
  "defaultMessageTimeToLive": "14 days, 0:00:00",
  "duplicateDetectionHistoryTimeWindow": null,
  "enableBatchedOperations": true,
  "forwardDeadLetteredMessagesTo": null,
  "forwardTo": null,
  "id": "XXXXX",
  "isClientAffine": false,
  "location": "South India",
  "lockDuration": "0:00:30",
  "maxDeliveryCount": 2,
  "messageCount": 0,
  "name": "XXXXX",
  "requiresSession": false,
  "resourceGroup": "XXXXX",
  "status": "Active",
  "systemData": null,
  "type": "Microsoft.ServiceBus/Namespaces/Topics/Subscriptions",
  "updatedAt": "2022-06-14T07:50:42.039807+00:00"
}

I am using the same Azure CLI version as that of your environment 2.37.0.

As a next action plan, Could you please run the below command check if that helps ? Awaiting your reply.

>az resource update --ids /subscriptions/12345678910/resourceGroups/XXXXXX/providers/Microsoft.ServiceBus/namespaces/XXXXX/topics/XXXXX/subscriptions/XXXXX --set properties.autoDeleteOnIdle=PT10M

**PS**: Update the SubscriptionID, RG name, SB namespace, Topic Name, Subscription name and --auto-delete-on-idle value before running the command.

**Comment by amoradiaz** [comment]
No dice, I tried what you used, and still the same issue
`az servicebus topic subscription update --resource-group <xyz> --namespace-name <abc> --topic-name <def> --name <ghi> --auto-delete-on-idle PT7M`

```json
{
  "accessedAt": "0001-01-01T00:00:00+00:00",
  **"autoDeleteOnIdle": "10675199 days, 2:48:05.477581",**
  "clientAffineProperties": null,
  "countDetails": {
    "activeMessageCount": 0,
    "deadLetterMessageCount": 0,
    "scheduledMessageCount": 0,
    "transferDeadLetterMessageCount": 0,
    "transferMessageCount": 0
  },
  "createdAt": "2022-06-14T12:56:07.444982+00:00",
  "deadLetteringOnFilterEvaluationExceptions": true,
  "deadLetteringOnMessageExpiration": false,
  "defaultMessageTimeToLive": "00:10:00"
  "duplicateDetectionHistoryTimeWindow": null,
  "enableBatchedOperations": true,
  "forwardDeadLetteredMessagesTo": null,
  "forwardTo": "<jkl>",
  "id": "/subscriptions/<tuv>/resourceGroups/<xyz>/providers/Microsoft.ServiceBus/namespaces/<abc>/topics/<def>/subscriptions/<ghi>",
  "isClientAffine": false,
  "location": "East US 2",
  "lockDuration": "0:01:00",
  "maxDeliveryCount": 10,
  "messageCount": 0,
  "name": "<ghi>",
  "requiresSession": false,
  "resourceGroup": "<xyz>",
  "status": "Active",
  "systemData": null,
  "type": "Microsoft.ServiceBus/Namespaces/Topics/Subscriptions",
  "updatedAt": "2022-06-14T12:56:07.444982+00:00"
}
```
Then tried what you suggested with the resource update, and it gave me the same result.

`az resource update --ids /subscriptions/<tuv>/resourceGroups/<xyz>/providers/Microsoft.ServiceBus/namespaces/<abc>/topics/<def>/subscriptions/<def> --set properties.autoDeleteOnIdle=PT10M`

Then I tried with a different property just for fun and it worked:

`az resource update --ids /subscriptions/<tuv>/resourceGroups/<xyz>/providers/Microsoft.ServiceBus/namespaces/<abc>/topics/<def>/subscriptions/<def> --set properties.defaultMessageTimeToLive=PT7M`

```json
{
  "accessedAt": "0001-01-01T00:00:00+00:00",
  "autoDeleteOnIdle": "10675199 days, 2:48:05.477581",
  "clientAffineProperties": null,
  "countDetails": {
    "activeMessageCount": 0,
    "deadLetterMessageCount": 0,
    "scheduledMessageCount": 0,
    "transferDeadLetterMessageCount": 0,
    "transferMessageCount": 0
  },
  "createdAt": "2022-06-14T12:56:07.444982+00:00",
  "deadLetteringOnFilterEvaluationExceptions": true,
  "deadLetteringOnMessageExpiration": false,
  **"defaultMessageTimeToLive": "0:07:00",**
  "duplicateDetectionHistoryTimeWindow": null,
  "enableBatchedOperations": true,
  "forwardDeadLetteredMessagesTo": null,
  "forwardTo": "<jkl>",
  "id": "/subscriptions/<tuv>/resourceGroups/<xyz>/providers/Microsoft.ServiceBus/namespaces/<abc>/topics/<def>/subscriptions/<ghi>",
  "isClientAffine": false,
  "location": "East US 2",
  "lockDuration": "0:01:00",
  "maxDeliveryCount": 10,
  "messageCount": 0,
  "name": "<ghi>",
  "requiresSession": false,
  "resourceGroup": "<xyz>",
  "status": "Active",
  "systemData": null,
  "type": "Microsoft.ServiceBus/Namespaces/Topics/Subscriptions",
  "updatedAt": "2022-06-14T14:50:55.551864+00:00"
}
```
It also worked with `maxDeliveryCount` 

Interestingly enough, I don't see this property in the Portal UI, is this under some sort of extra permission?

![image](https://user-images.githubusercontent.com/65770472/173618201-2afe5107-69c0-4990-8152-178eee7f4f02.png)

**Comment by navba-MSFT** [comment]
@amoradiaz This is a quick follow-up to check if you had a chance to follow the above suggestions to isolate this issue. Awaiting your reply.

**Comment by amoradiaz** [comment]
After following the steps that you detailed, the command successfully updated the auto-delete idle property, and I can even see it in the portal:

![image](https://user-images.githubusercontent.com/65770472/174100902-40ec851f-5253-4fc9-bde8-94f319eae24b.png)

From the API perspective, what command sets the "Never auto-delete" property to `true`?  This is something I'm not doing consciously

```batch
az servicebus topic subscription create --name
                                        --namespace-name
                                        --resource-group
                                        --topic-name
                                        [--auto-delete-on-idle]
                                        [--dead-letter-on-filter-exceptions {false, true}]
                                        [--default-message-time-to-live]
                                        [--enable-batched-operations {false, true}]
                                        [--enable-dead-lettering-on-message-expiration {false, true}]
                                        [--enable-session {false, true}]
                                        [--forward-dead-lettered-messages-to]
                                        [--forward-to]
                                        [--lock-duration]
                                        [--max-delivery-count]
                                        [--status {Active, Disabled, ReceiveDisabled, SendDisabled}]
```

**Comment by navba-MSFT** [comment]
@amoradiaz Thanks for getting back. I am glad that my above suggestions helped. 

The `--auto-delete-on-idle` property is optional and if **_not_** specified while creating the subscription using AzureCLI it will be set to `Never`.  The minimum duration that can be set for this property is 5 minutes.

You can tweak / update this property even after the subscription is created. If you would like to Turn Off the Auto delete (change it to Never). You can do it either from portal or AzCLI:

**From portal:**
![image](https://user-images.githubusercontent.com/57353862/174543613-47799f9a-d6c2-4ca3-b527-0c62d864d596.png)

You can enable the Checkbox to Never auto-delete:
![image](https://user-images.githubusercontent.com/57353862/174543377-4f371574-44c5-4325-8a3f-38fc655b9964.png)


**From AzCLI:**

>az servicebus topic subscription update --name MySubscription --namespace-name MyNamespace --resource-group MYRG --topic-name MyTopic --auto-delete-on-idle P10675198DT2H48M5.477S

The above command will update the --auto-delete-on-idle to Never. Hope this answers.

**Comment by navba-MSFT** [comment]
@amoradiaz I hope you had a chance to look at my above comment. Please let me know if you need any further assistance on this or we can proceed with closure.

**Comment by amoradiaz** [comment]
I can confirm that what you suggested checks out. I can do all of that as long as I don't add a forwarding queue/topic.

As soon as I do that, the Auto-delete option disappears from the portal view.

before:
![image](https://user-images.githubusercontent.com/65770472/175030101-100ad51f-c362-47f2-94a8-3dd335119c93.png)

after:
![image](https://user-images.githubusercontent.com/65770472/175030157-5db07872-0d20-4c74-b93b-e1e58f5e0198.png)

After running the update the command, it returns the "never" time span no matter what I had before.
![image](https://user-images.githubusercontent.com/65770472/175030228-19e93265-3939-40e4-91a4-b1fb7989c2ff.png)


This is the scenario that I'm currently in, where I wanted some of this subscriptions to expire on their own, even if they were tied to queues. Some of my queues are also auto expiring, which creates this scenario where the topic subscription remains forever (never autodelete), but the queue it was pointing to is already auto-deleted. 

Is there any way to propagate the auto-delete from a queue to its subscription so that we don't leave subscriptions pointing to nowhere?

**Comment by navba-MSFT** [comment]
Involving Service Team to comment on this.

@Saglodha Please look into the above ask once you get a chance.

**Comment by Saglodha** [comment]
@navba-MSFT - Ack on above ask.

@amoradiaz - Thanks for sharing details about your setup. I would look into this use case of yours and share feedback soon.

**Comment by Saglodha** [comment]
Adding @EldertGrootenboer  for visibility here. @EldertGrootenboer , can you review this ask and confirm if this is expected behavior?

**Comment by EldertGrootenboer** [comment]
We are looking into this, and will come back when we have more information.

**Comment by vinaysurya** [comment]
@amoradiaz this is expected behavior by design. The behavior has been documented here as well. 

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-auto-forwarding#using-autoforwarding

Unfortunately, today there is no mechanism to relay the inactiveness of destination entity on to the source entity and clean that up as well.

It has typically been our belief that Autoforwarding is more of a configuration set up by customer that is set to work whenever there is a message on the source entity. Therefore, when such a configuration is set up, we choose not to interfere with the lifetime of the entity through Autodelete.

Having said that, we did notice a documentation issue in the above link that the destination entity's lifetime will also be adjusted. That is incorrect. We have opened a workitem to correct that part of the documentation soon.
