### ISSUE TITLE
az synapse pipeline update error

### ISSUE THREAD

**Issue by ManojLava** [Azure/azure-cli#22839]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
<!az synapse pipeline update --workspace-name wrkname5001 --name MypipelineToSynapse --file @"C:\Users\commom\..\..\PipelineSettings.json"
Command group 'synapse' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
'properties'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/synapse/manual/operations/artifacts.py", line 82, in create_or_update_pipeline
KeyError: 'properties'>

**Describe the bug**
<!-Unable to update the pipeline parameter from the input JSON. JSON file consist of the parameters generated from az synapse pipeline show command>

**To Reproduce**
< just execute below  command with inputs in JSON file.
az synapse pipeline update --workspace-name wrkname5001 --name MypipelineToSynapse --file @"C:\Users\commom\..\..\PipelineSettings.json">

**Expected behavior**
<!Synapse Pipeline parameter must be updated based on the input parameters in the JSON file>

**Environment summary**
<!azure-cli                         2.37.0

core                              2.37.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1>

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@ManojLava Thank you for reaching out to us, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@ManojLava I was unable to reproduce this issue, can you please share more details? `az synapse pipeline update --workspace-name samplewspace --name Issue22839 --file @"pipeline.json"` 
This is the response body I used as json file https://docs.microsoft.com/en-us/rest/api/synapse/data-plane/pipeline/create-or-update-pipeline.

Can you retry this please and let me know what happens?

Here are my environment details.
azure-cli                         2.37.0
core                              2.37.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

**Comment by ManojLava** [comment]
Hi Team,
Thanks for your reply. My issue is still not resolved. My guess is that my JSON file format is not correct. Please guide how to get correct format JSON file from existing Pipeline.

**Comment by RakeshMohanMSFT** [comment]
@ManojLava You can find the sample response JSON Body here and tweak according to your need https://docs.microsoft.com/en-us/rest/api/synapse/data-plane/pipeline/create-or-update-pipeline#request-body

**Comment by ManojLava** [comment]
Hi Team,

I trying to execute below command to JSON response for a specific file as per details share in above link

PUT {endpoint}/pipelines/{pipelineName}?api-version=2020-12-01

Below is the steps I have execute to make this api call

Piece of my code to get access token and moving it to headers variable

$Credential = Get-Credential
Connect-AzAccount -Credential $Credential
$token = (Get-AzAccessToken).Token
$headers = @{ Authorization = "Bearer $token" }

Assigning the uri variable with Azure details and Pipeline name
 
$uri = "https://web.azuresynapse.net/subscriptions/$SubscriptionID/"
$uri += "resourceGroups/$ResourceGroup/providers/Microsoft.Synapse/"
$uri += "workspaces/$workspaceName/"
$uri += "pipelines/MyPipeline?api-version=2020-12-01"

$response = Invoke-RestMethod -Method Put -ContentType "application/json" -Uri $uri -Headers $headers

I'm getting below error stating invalidate operation. 
CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

what is the wrong with my api call? I'm not able to debug this issue.

**Comment by RakeshMohanMSFT** [comment]
@ManojLava we could see 404 response which is expected because we do not have that synapse resource. Hope you are calling it from powershell. Also this forum is for azure cli issues exclusively.

I will mark this issue for closure now.

**Comment by sark1** [comment]
can anyone please confirm whether this line is a warning or an error response?
