### ISSUE TITLE
Mounting a file share with a key containing a control character silently fails to mount

### ISSUE THREAD

**Issue by iSplasher** [Azure/azure-cli#22830]
## Describe the bug

Hello, we just solved an issue after hours of debugging with not being able to mount a file share using `az container create`.
The issue is that if your `--azure-file-volume-account-key` contains a control character like so `<storage-key>\r`, the container will be created as if the storage key was correct, however, it will hang in a `Waiting` state, and after a few minutes, you start getting `FailedMountAzureFileVolume` warnings.
If you remove the control character from `<storage-key>`, the mount will succeed as expected.
We hope you can fix this issue as it can lead to frustrating debugging sessions. 

**Command Name**
`az container create`

**Errors:**
```
You get no errors on wrong storage key if the key contains a control character
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- STORAGE_KEY=123434\r
- `az container create --resource-group {} --name {} --image {} --location {} --ports {} --azure-file-volume-account-name {} --azure-file-volume-account-key $STORAGE_KEY --azure-file-volume-share-name {} --azure-file-volume-mount-path {} --registry-username {}`

## Expected Behavior

An error is raised on wrong storage key

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.10.4
Installer: 

azure-cli 2.37.0
```

**Comment by RakeshMohanMSFT** [comment]
@iSplasher Thank you for reaching out, we are looking into it.

**Comment by iSplasher** [comment]
I was using the command with bash using WSL. I'm not sure how the control character appeared but I remember copying and pasting commands spanning over multiple lines. I was also using an environment variable like below. The control character couldn't be seen with `echo AZURE_FILE_KEY`, only in the `--debug` log of the `az` command.
```
export AZURE_FILE_KEY="key\r"
az container create -g Issue22830 --name issue22830container --image mcr.microsoft.com/azuredocs/aci-helloworld --location eastus --azure-file-volume-account-name issue22830storage --azure-file-volume-account-key AZURE_FILE_KEY --azure-file-volume-share-name issue22830volume --azure-file-volume-mount-path /mnt/azfile
```

**Comment by RakeshMohanMSFT** [comment]
@iSplasher Let me try with WSL and get back to you.

**Comment by iSplasher** [comment]
Yes, I'm not sure how that control character ended up in my string, and I also fail to reproduce it. We can close this.
