### ISSUE TITLE
Az VM repair-- Inplace upgrade

### ISSUE THREAD

**Issue by yuvaraj-azurevm** [Azure/azure-cli#22832]
Hello Team,

We have a existing az Vm repair command to Create Rescue VM and attach the problematic disk, For performing in place upgrade through nested hyper-v, there should be add-on step for attaching ISO file with option to select Windows server 2016/ Windows Server 2019.

There is internal TSG , we wanted the same incorporated through AZ vm repair command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 355a594a-22ef-fd15-0b58-07701dd1815c
* Version Independent ID: d8356a0a-9aaf-900b-ce7a-021c9a0af509
* Content: [az vm repair](https://docs.microsoft.com/en-us/cli/azure/vm/repair?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm/repair.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm/repair.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Compute

**Comment by yuvaraj-azurevm** [comment]
Team wanted to check on the feedback which I had provided, curious to know if there is an ETA

**Comment by zhoxing-ms** [comment]
@dkulkarni-ms Could you please take a look at the `vm repair` related issue?

**Comment by jaylabell** [comment]
This item is being discussed with engineering team

**Comment by Drewm3** [comment]
Moving Jayla's issues over to me.

**Comment by Drewm3** [comment]
Hi @yuvaraj-azurevm, we have released the ability to do an inplace upgrade directly on VMs without using VM repair. Please see the following documentation on this process: https://learn.microsoft.com/en-us/azure/virtual-machines/windows-in-place-upgrade.

With this new capability, do you still feel something is needed in VM Repair, or can I close this issue?

**Comment by Drewm3** [comment]
Moving this to closed now that in-place upgrades are generally supported for Windows Server.
