### ISSUE TITLE
LogAnalytics: log-analytics cluster update 

### ISSUE THREAD

**Issue by dabenhamMic** [Azure/azure-cli#22842]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

We have a couple of open tickets on the CLI module:
https://msazure.visualstudio.com/One/_workitems/edit/14318495
https://msazure.visualstudio.com/One/_workitems/edit/14318510

Bugs description:

Updating CMK key with empty version “” fails. I verified and it works fine in REST
PS C:\Users\yossiy> $kUri = 'https://yossiy-eus.vault.azure.net/'
PS C:\Users\yossiy> $kName = 'yossiy-test1'
PS C:\Users\yossiy> $kVersion = ''
PS C:\Users\yossiy> az monitor log-analytics cluster update --name $clusterName --resource-group $rg --key-name $kName --key-vault-uri $kUri --key-version $kVersion
argument --key-version: expected one argument

Updating BillingType not supported. I verified and it works fine in REST
PS C:\Users\yossiy> az monitor log-analytics cluster update --name $clusterName --resource-group $rg 'Workspaces'
unrecognized arguments: Workspaces

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
monitor

**Comment by dabenhamMic** [comment]
@kairu-ms , @yonzhan Can you please add this to the upcoming July milestone? [Jun 2022 (2022-07-05)](https://github.com/Azure/azure-cli/milestone/119)
