### ISSUE TITLE
Typo "Azure bastion"→"Azure Bastion"

### ISSUE THREAD

**Issue by hyoshioka0128** [Azure/azure-cli#22846]
https://docs.microsoft.com/en-us/cli/azure/network/bastion?view=azure-cli-latest

![image](https://user-images.githubusercontent.com/40815708/173272614-049239fd-65ed-4acd-bb31-201c2a692889.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c10d6dab-e042-91dc-a213-943af0d5ad0e
* Version Independent ID: 399a501c-b96d-8867-078f-73dd9b8b3da2
* Content: [az network bastion](https://docs.microsoft.com/en-us/cli/azure/network/bastion?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/bastion.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/bastion.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@hyoshioka0128 Will create a PR to fix it.
