### ISSUE TITLE
ERROR: 'ml' is misspelled or not recognized by the system.

### ISSUE THREAD

**Issue by MurugeswariMuthurajan** [Azure/azure-cli#22843]
Hi Team,

I am trying to deploy my model, but I am getting an error :- 

ERROR: 'ml' is misspelled or not recognized by the system.
2022-06-12T10:56:39.4631524Z 
2022-06-12T10:56:39.4632840Z TRY THIS:
2022-06-12T10:56:39.4634550Z az extension add --name anextension
---------------------------------------------------------------------
Kindly find the versions below:-

**_azure-cli                         2.29.2 *
core                              2.29.2 *
telemetry                          1.0.6
azure-devops                      0.21.0_**

Please let me know how to solve this. When I change the version of any of the components I am getting various errors:-

For Example:-

1. If I kept azure -cli as 2.30.0 version i am getting below error:-

 azure-cli 2.30.0 throws ERROR: {'Error': TypeError("init() got an unexpected keyword argument 'async_persist'",)} 
---------------------------
2. If I kept 2.29.2 azure -cli version, I am getting the below error:-

**The 'azure-devops' extension version 0.22.0 is not compatible with your current CLI core version 2.29.2**

### So I have downgraded the devops version to 0.21.0
------------------------------------------------------------
Now I am getting this error :-  'ml' is misspelled or not recognized by the system.

Please let us know versions for corresponding component and which agent have to be used

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@MurugeswariMuthurajan Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@MurugeswariMuthurajan The latest version of azure cli is 2.37.0 https://docs.microsoft.com/en-us/cli/azure/install-azure-cli. Can you please try to upgrade to the it and see if that helps?

**Comment by MurugeswariMuthurajan** [comment]
Hi Rakesh,

Now I am getting a new Error, if I kept the azure cli version - 2.37.0

![image](https://user-images.githubusercontent.com/107349920/173396584-2d47a4cf-ed5b-4e35-8342-a343ee8c3aae.png)

**Comment by RakeshMohanMSFT** [comment]
@MurugeswariMuthurajan Can you please let me know your python version? and please try to follow this instruction document https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli?tabs=public
