### ISSUE TITLE
Support restore/create a disk from diskRestorePoint

### ISSUE THREAD

**Issue by dikethir** [Azure/azure-cli#22850]
### Related command

az disk create --resource-group “ExampleRg” --name “ExampleOSDisk” --sku Premium_LRS --size-gb 128 --source $osDiskRestorePoint

### Resource Provider

Microsoft.Compute/Disks

### Description of Feature or Work Requested

DiskRestorePoints are similar to managed disk snapshots and we should be able to restore disks using them, however currently its failing with the following error:
“usage error: --source {SNAPSHOT | DISK} | --source VHD_BLOB_URI [--source-storage-account-id ID]”

### Minimum API Version Required

2021-03-01

### Swagger PR link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2022-03-01/ComputeRP/restorePoint.json

### Target Date

2022-07-19

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@dikethir I'd like to confirm with you that `$osDiskRestorePoint` can be obtained by the id returned by `az restore-point show` command, right?

**Comment by zhoxing-ms** [comment]
This feature request will be released by PR #22898 on 07-05
