### ISSUE TITLE
knack.util.CLIError: Please run 'az login' to setup account

### ISSUE THREAD

**Issue by MurugeswariMuthurajan** [Azure/azure-cli#22853]
Hi,

In my ML model training step, **_I am getting the below error:-_**

raise CLIError(_AZ_LOGIN_MESSAGE)
knack.util.CLIError: Please run 'az login' to setup account

_**Also I am getting a warning**_

The STDIO streams did not close within 10 seconds of the exit event from process 'C:\Program Files\Git\bin\bash.exe'. This may indicate a child process inherited the STDIO streams and has not yet exited.
C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\az.bat account clear"
WARNING: Auto upgrade failed. name 'exit_code' is not defined
--------------------------------------------------------------------------------
**DETAILS:-**

azure-cli                         2.37.0
core                              2.37.0
telemetry                          1.0.6

Extensions:
azure-cli-ml                      1.41.0
azure-devops                      0.25.0

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource               21.0.0
-----------------------------------------------------------
Kindly help me to sort out this issue

![image](https://user-images.githubusercontent.com/107349920/173352728-bf990963-d2c3-4dcc-9239-9fca368df1b3.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by jiasli** [comment]
This is out of the scope of Azure CLI. Please reach out to the corresponding repo of "ML model training".
