### ISSUE TITLE
Command doesn't work as expected

### ISSUE THREAD

**Issue by iamsunny** [Azure/azure-cli#22867]
[Enter feedback here]

command in the Example section doesn't work:
> az monitor app-insights component connect-webapp -g myRG -a myAI --web-app myApp --enable-profiler --enable-snapshot-debugger

throws error: "unrecognized arguments: -a <a--pinsights-resource-name> --webapp <web-app-name>
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7674ea80-0d76-8e00-aa8f-ba6b91e0d5cc
* Version Independent ID: b7a32927-d7a9-3da5-3e76-d780a32b60f7
* Content: [az monitor app-insights component](https://docs.microsoft.com/en-us/cli/azure/monitor/app-insights/component?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/monitor/app-insights/component.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/monitor/app-insights/component.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by YuanyuanNi** [comment]
Hi:
  @iamsunny the command works well as below, notice that it is '--web-app' not '--webapp', and you should use below commands to create relative resouce first:
1:create a app:   az monitor app-insights component create -g nyy02 -l westus --app demoapp
2: create a webapp : az appservice plan create -g nyy02 -n plan01
                                 az webapp create -g nyy02 -n webunique001 --plan plan01
3: the last command :   az monitor app-insights component connect-webapp -g nyy02 -a demoapp --web-app webunique001 --enable-profiler --enable-snapshot-debugger
![image](https://user-images.githubusercontent.com/95396631/173760159-c024705a-87ef-49cb-b980-d950fa5069d2.png)

**Comment by surexxx** [comment]
Same problem here, the command doesn't work as expected running from azure portal.
<img width="1103" alt="Screenshot 2023-01-13 at 14 15 15" src="https://user-images.githubusercontent.com/18722513/212328741-4e406754-bf20-4040-8e6c-dae0523f9a6e.png">
The underlining webapp and application insights resources exist. Any suggestion?

**Comment by yonzhan** [comment]
@AllyW for awareness
