### ISSUE TITLE
az apim api import resets User authorization from OAuth 2.0 to None

### ISSUE THREAD

**Issue by marc-ellis-dev** [Azure/azure-cli#22871]
When the "az apim api import" command is run, the Security -> User authorization setting for the API is reset from OAuth 2.0 to None.
![image](https://user-images.githubusercontent.com/103236775/173712701-4cb9505b-8408-4392-871d-7cf2b87dc2d8.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@marc-ellis-dev Thank you for reaching out, we are looking into it

**Comment by RakeshMohanMSFT** [comment]
@marc-ellis-dev We use this command to import new apis, therefore it wont be having any security settings for that API to reset. May be i am missing something. Can you please share more details or debug logs please?

**Comment by pavanabhange** [comment]
Hey @RakeshMohanMSFT, we are also having the same issue. We use Terraform to create our APIM and the API structure (which includes the OAuth settings) and run a pipeline on our API to import the swagger file for endpoints (when there are updates to the code). This pipeline uses the az command listed above. When the az import command runs, it overrides our OAuth settings to null and this is causing issues as there is no user authorization parameter on the az command to restore our original Auth settings on the API. Below is the output of the above command.

`***
  "apiRevision": "1",
  "apiRevisionDescription": "",
  "apiType": null,
  "apiVersion": "1.0",
  "apiVersionDescription": "",
  "apiVersionSet": null,
  "apiVersionSetId": "*******",
  "authenticationSettings": ***
    "oAuth2": null,
    "openid": null
  ***,
  "description": "******",
  "displayName": "*****",
  "id": "**********",
  "isCurrent": true,
  "isOnline": null,
  "name": "********",
  "path": "*******",
  "protocols": [
    "https"
  ],
  "resourceGroup": "**********",
  "serviceUrl": "***************",
  "sourceApiId": null,
  "subscriptionKeyParameterNames": ***
    "header": "Ocp-Apim-Subscription-Key",
    "query": "subscription-key"
  ***,
  "subscriptionRequired": true,
  "type": "Microsoft.ApiManagement/service/apis"
***`

*Note: masked the fields for privacy.

**Comment by pavanabhange** [comment]
@RakeshMohanMSFT Can we get any update on this? We are having issues in our prod environments and having to manually update the OAuth settings every single time a pipeline is run, because of this command.

**Comment by tgrnwd** [comment]
There hasn't been a response on this but I was previously experiencing the behavior described by @pavanabhange and it seems to have begun functioning as I expected about 1 week ago, `authenticationSettings` is no longer being overwritten with `null` values.

**Comment by RakeshMohanMSFT** [comment]
@marc-ellis-dev @tgrnwd Apologies for the delay, we are working on it. Should be fixed soon, can we please upgrade to the latest version of azure cli? https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
