### ISSUE TITLE
Improve error message instead of: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by matkosoric** [Azure/azure-cli#22881]
**Related command**
`az deployment group create
`
`az deployment group validate 
`
Similar error message appears in multiple other subcommands.

**Describe the solution you'd like**
If I am deploying ARM template for Azure Data factory with linked service which contains empty value, validation and deployment will fail. Parameter in **adf_publish** branch looks something like this:

```
		"some_important_parameter": {
			"value": ""
		},
```

Please add more detailed output so that error message indicates the reason for failure.
Currently, if linked service parameter is empty, error message simply states:

`'str' object has no attribute 'get'
`

More verbose logginig with **--debug** flag is also not informative.
Providing dummy value for parameter can be a quick fix for successful validation or deployment, although linked service in target environment will probably not work.

**Comment by yonzhan** [comment]
ARM

**Comment by RakeshMohanMSFT** [comment]
@matkosoric Apologies for the delay in responding to your request. Can you please help us with the ARM template you are using for this scenario?

**Comment by matkosoric** [comment]
Unfortunately, I can not share ARM templates, but **ArmTemplateParameters_master.json** can start something like this:


```
{
	"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
		"factoryName": {
			"value": "my-adf-name-82372"
		},
		"ADLS_linked_service_properties_typeProperties_serviceEndpoint": {
			"value": ""
		},

...
```

**Comment by RakeshMohanMSFT** [comment]
@matkosoric I tried a simple arm template to deploy a storage account having and i got a valid error message as shown below.
![image](https://user-images.githubusercontent.com/49954584/186843858-520c41ed-e788-46a2-aa67-538eb5d4ca9e.png)

![image](https://user-images.githubusercontent.com/49954584/186844053-40bcc789-d49c-45c9-a739-4ee7f6442021.png)

Note: which version of az cli are you using? If you are not using the latest version [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) can you upgrade please and try again?

**Comment by matkosoric** [comment]
At the time, we were using 2.37.0  and updated az cli in the meantime. I can not roll it back to experiment. If it behaves as demonstrated, that is definitely much better. Is it also the case when default value is not provided?

**Comment by RakeshMohanMSFT** [comment]
Sure, please upgrade and try and let us know. Yes, even if you do not provide default value it works as expected. Please see the image below

![image](https://user-images.githubusercontent.com/49954584/188542858-065c65d9-6cf3-4a48-bb30-6b5f696f3d99.png)

**Comment by SMHodges** [comment]
Still an issue to this day.
