### ISSUE TITLE
Docs say space-separated instead of comma-separated

### ISSUE THREAD

**Issue by mdenhoedt** [Azure/azure-cli#22891]
The documentation of `az storage entity query` says the following:

> `--select`
> Space-separated list of properties to return for each entity.

However I got the following error:

> ERROR: Term 'PartitionKey RowKey' is not valid in a $select or $expand expression.

After trying `--select 'PartitionKey,RowKey'`, so comma-separated, it did work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a4d128f-a98f-d07b-0183-90ca79cc5fdc
* Version Independent ID: 83084fff-ea1b-a9e7-b7a9-40023de43542
* Content: [az storage entity](https://docs.microsoft.com/en-us/cli/azure/storage/entity?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/entity.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/entity.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
storage

**Comment by jonie001** [comment]
Hi, @mdenhoedt 
When you use `--select` parameters, you do not need to use '' marks, you can try `--select PartitionKey RowKey` again.

**Comment by RakeshMohanMSFT** [comment]
@mdenhoedt Did you try what @jonie001 suggested?
