### ISSUE TITLE
error with --linux-workers-enabled flag "unrecognized arguments"

### ISSUE THREAD

**Issue by idkjs** [Azure/azure-cli#2289]
Im using the dockerized version of the azure-cli 2.0. When i run the following command, I get an error.

command: `bash-4.3# az appservice plan create -n random-plan -g random-app --is-linux`

Output:
```
Plan with linux worker is not supported in current region. Run 'az appservice list-locations --linux-workers-enabled' to cross check
bash-4.3# az appservice list-locations --linux-workers-enabled
az: error: unrecognized arguments: --linux-workers-enabled
usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {appservice} ...
```

Has the format changed for this flag? Does it work in the docker version of the cli?

Thank you.

**Comment by tjprescott** [comment]
Hi @idkjs it seems that the flag mentioned in the error message is not supported by the command. Looking at the output of the command, it doesn't look like there's an obvious way to determine whether a location supports Linux workers or not. We'll look into the appropriate fix: either fixing the error message or enabling the flag. Thanks for your report!

cc/ @yugangw-msft

**Comment by derekbekoe** [comment]
Same as this? - https://github.com/Azure/azure-cli/issues/2187

**Comment by yugangw-msft** [comment]
@derekbekoe, correct
It is a known feature missing in the new SDK, and we have an active thread going on with the webapp team. In the latest release, you should see an error with a link pointing to a page with valid regions
