### ISSUE TITLE
No way to pass the protocol while creating a listner for custom port

### ISSUE THREAD

**Issue by DrDarinda** [Azure/azure-cli#22899]
No parameter available to pass protocol(https/http) while creating a listener:

`az network application-gateway http-listener create (--protocal??)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dce00db-c8d7-9b93-7ac8-114a500a6a34
* Version Independent ID: 14a03192-a30b-d273-fa11-32413868a5fa
* Content: [az network application-gateway http-listener](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/http-listener?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/application-gateway/http-listener.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/application-gateway/http-listener.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by necusjz** [comment]
@DrDarinda, the https protocol will be used if the `--ssl-cert` parameter is passed.

**Comment by asudbring** [comment]
Thanks for your dedication to our documentation. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. 

#please-close
