### ISSUE TITLE
'az functionapp list-runtimes' throws error ['list-runtimes' is misspelled or not recognized by the system.]

### ISSUE THREAD

**Issue by william-li-nintex** [Azure/azure-cli#22906]
[Enter feedback here]
'az functionapp list-runtimes' throws error ['list-runtimes' is misspelled or not recognized by the system.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f254bb-7dfd-417b-b08d-f2ac34247d99
* Version Independent ID: 9d22f523-579b-ea66-04ed-20f09c72bcbb
* Content: [az functionapp](https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest#az-functionapp-list-runtimes)
* Content Source: [latest/docs-ref-autogen/functionapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/functionapp.yml)
* Service: **azure-functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@william-li-nintex Thank you for reaching out, we are looking into it.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@william-li-nintex we are unable to reproduce this issue, here is my environment details. Can you share your Environment details please?
```
azure-cli                         2.37.0
core                              2.37.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python (Windows) 3.10.4
```

**Comment by speedyankur** [comment]
Issue is reproducible with 



`{
  "azure-cli": "2.33.1",
  "azure-cli-core": "2.33.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "storage-preview": "0.8.0"
  }
}
`

**Comment by StrawnSC** [comment]
The `az functionapp list-runtimes` command was introduced in version 2.34 (see the release history [here](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli#app-service-4)). @speedyankur @william-li-nintex you should make sure your CLI is version 2.34 or later to use this command. You can get the latest CLI version with `az upgrade`
