### ISSUE TITLE
Simplify VCR test base

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#2290]
- [ ] Enable to reuse resource group
- [ ] Enable to use existing, specified resource group and
- [ ] Enable to use existing, specified storage account
- [x] Streamline modules for updating records before and after recording.

**Comment by tjprescott** [comment]
With ScenarioTest being failrly robust, do we need this anymore?  The Knack conversion is actively replacing all instances of VCRTestBase so we can probably just close this.
