### ISSUE TITLE
Invalid sample --custom condition for az image builder wait

### ISSUE THREAD

**Issue by roycornelissen** [Azure/azure-cli#22901]
The example for `az image builder wait` under https://docs.microsoft.com/en-us/cli/azure/image/builder?view=azure-cli-latest#az-image-builder-wait-examples shows a custom condition `--custom "lastRunStatus.runState!='running'"`. However, the condition is case sensitive, so this particular example will immediately finish waiting. A correct sample would be `--custom "lastRunStatus.runState!='Running'"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e24b37-83e6-abcb-65f3-8e10aca64fa5
* Version Independent ID: 803fa652-41f2-dcdd-ed5b-2e60b11186af
* Content: [az image builder](https://docs.microsoft.com/en-us/cli/azure/image/builder?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/image/builder.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/image/builder.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Compute

**Comment by RakeshMohanMSFT** [comment]
@roycornelissen Thank you for reaching out, we are looking into it.
