### ISSUE TITLE
unable to create VM using CLI

### ISSUE THREAD

**Issue by KathySundar** [Azure/azure-cli#22905]
## Describe the bug

**Command Name**
`Unknown`

**Errors:**
```
'groupcreate' is misspelled or not recognized by the system.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az groupcreate --location {} --name {}`

## Environment Summary
```
Linux-5.4.0-1085-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.4
Installer: DEB

azure-cli 2.37.0

Extensions:
ai-examples 0.2.5
ssh 1.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by RakeshMohanMSFT** [comment]
@KathySundar if you are trying to create resource group, please use this command https://docs.microsoft.com/en-us/cli/azure/group?view=azure-cli-latest#az-group-create.
