### ISSUE TITLE
logs-workspace-id description needs correction

### ISSUE THREAD

**Issue by gabesmsft** [Azure/azure-cli#22914]
For the --logs-workspace-id description, need to change the following...:
Name or resource ID of the Log Analytics workspace to send diagnostics logs to. You can use "az monitor log-analytics workspace create" to create one. Extra billing may apply.

...to the following:
Workspace ID of the Log Analytics workspace to send diagnostics logs to. You can use "az monitor log-analytics workspace create" to create one. Extra billing may apply.

If you try to use the name or resource id, the following error will occur, whereas if you use the workspace id as the parameter name and error message suggest, it succeeds:
LogAnalyticsConfiguration.CustomerId is invalid.  CustomerId must be a GUID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5783ae85-c228-8bbe-d53e-c5452d8fe6b6
* Version Independent ID: 3c33cc2d-e8d1-d0ae-db45-e3db3ec8717c
* Content: [az containerapp env](https://docs.microsoft.com/en-us/cli/azure/containerapp/env?view=azure-cli-latest#az-containerapp-env-create-optional-parameters)
* Content Source: [latest/docs-ref-autogen/containerapp/env.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/containerapp/env.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@gabesmsft Thank you for reaching out, we are looking into it.
