### ISSUE TITLE
Azure CLI Service Principle policies

### ISSUE THREAD

**Issue by ChaseGarr** [Azure/azure-cli#22923]
I was just wondering if there was a way yet in azure cli to get the service principle policies

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
If you are talking about APIs such as [Assign claimsMappingPolicy](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-claimsmappingpolicies), there is currently no native command support. Please see https://github.com/Azure/azure-cli/issues/22580#issuecomment-1150686865 for the `az rest` solution.
