### ISSUE TITLE
Deleting last function also app service plan

### ISSUE THREAD

**Issue by HenrikSommer-Energinet** [Azure/azure-cli#22934]
**Related command**
az functionapp delete

**Is your feature request related to a problem? Please describe.**
When deleting the last function app in a plan, this command is also deleting the app service plan.

**Describe the solution you'd like**
add argument `--keep-empty-plan` like we have in `az webapp delete `

**Comment by yonzhan** [comment]
route to CXP team

**Comment by Francisco-Gamino** [comment]
Hello @panchagnula -- For the Az.Functions cmdlets, I changed the default behavior of `Remove-AzFunctionApp` to not delete the app service plan if this is the last app in the plan (for more information, please see https://github.com/Azure/azure-powershell/issues/16487). Perhaps we could do something similar here for the next breaking release of the Az CLI.

**Comment by HenrikSommer-eng** [comment]
If you do that then please also update `az webapp delete` to have the same default behavior.

**Comment by panchagnula** [comment]
Thanks for reporting, We will ensure the consistency b/w the commands. Need to verify this needs to be done for LA as well?
https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-delete

**Comment by kamperiadis** [comment]
Closing this issue as the latest CLI version supports `keep-empty-plan`
