### ISSUE TITLE
Add new operators in WAF custom rule condition

### ISSUE THREAD

**Issue by AdishreeM** [Azure/azure-cli#22932]
**Related command**
az network application-gateway waf-policy custom-rule match-condition add

**Is your feature request related to a problem? Please describe.**
New operators for custom rule condition have been added to NRP- "Any", "GeoMatch". Changes are submitted in azure-powershell. Azure-cli needs to be updated accordingly.

**Describe the solution you'd like**
Customer should be able to add a custom rule condition with the new operators

**Describe alternatives you've considered**

**Additional context**
 [Powershell PR](https://github.com/Azure/azure-powershell/pull/18458)

**Comment by yonzhan** [comment]
network
