### ISSUE TITLE
Azure ML CLI v2 submit ML Job failed.  command:  az ml job create -f jobs/basics/hello-mlflow.yml --web

### ISSUE THREAD

**Issue by JianxinLi333** [Azure/azure-cli#22931]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

az version
{
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ml": "2.5.0"
  }
}

**Related command**

az ml job create -f jobs/basics/hello-mlflow.yml --web

**Describe the bug**

When follow the document https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-cli to submit ML job to China Azure ML Workspace, Command _az ml job create -f jobs/basics/hello-mlflow.yml_ --web raised the error: **Error with code: Unable to determine account name for shared key credential.**

![image](https://user-images.githubusercontent.com/31917253/174542693-42d798ca-67d6-4248-832e-a94696ea9fc1.png)

**To Reproduce**

**Expected behavior**

In the code “/azure/ai/ml/_azure_environments.py” in the CLI v2, it sets the storage URL in Azure China to :
ENDPOINT_URLS.STORAGE_ENDPOINT=".core.chinacloudapi.cn”
But it should be 
ENDPOINT_URLS.STORAGE_ENDPOINT="core.chinacloudapi.cn”

![image](https://user-images.githubusercontent.com/31917253/174542864-30c71066-28d6-40ae-967b-67d24724bc5b.png)

                
I manually changed the code and now AML SDK v2 can run in Azure China. 
![image](https://user-images.githubusercontent.com/31917253/174543067-5832b74a-ff94-4709-bc6b-9720ce8f779a.png)

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team
