### ISSUE TITLE
Logs failed to download

### ISSUE THREAD

**Issue by cisarpavel** [Azure/azure-cli#22936]
## Describe the bug

**Command Name**
`az webapp log download`

**Errors:**
```
('Connection broken: IncompleteRead(25 bytes read)', IncompleteRead(25 bytes read))
Traceback (most recent call last):
lib/python3.8/http/client.py, ln 556, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
lib/python3.8/http/client.py, ln 523, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

...

python3/dist-packages/urllib3/response.py, ln 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(25 bytes read)', IncompleteRead(25 bytes read))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp log download --name {} --resource-group {}`

## Environment Summary
```
Linux-5.13.0-40-generic-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by navba-MSFT** [comment]
@cisarpavel I see that you are using an older version of Azure CLI. Could you update your AzCLI to the [most recent version](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) and test the download again ?

On a side note, ensure that you are using a reliable network which has a better download speed while testing the command. 

Awaiting your reply.

**Comment by cisarpavel** [comment]
@navba-MSFT  Thanks, I used default repo version. Newer one works well.

**Comment by MrMCake** [comment]
For me the issue persists also with version `2.37.0`. In the meantime, `2.38.0` was released so I'll try to re-test with that one too.

Just one interesting observation: About every 3rd query via `az webapp log download` actually worked without any problem. But then I would re-run the pipeline (with the command) and it would fail again.

**Comment by MrMCake** [comment]
Ok, I can confirm the issue persists in version `2.38.0`. Sometimes it works, sometimes it doesn't...

**Comment by StrawnSC** [comment]
@MrMCake, I'm unable to repro this. Can you provide more info about the app you're using (OS, SKU, app kind, etc.)?
