### ISSUE TITLE
Terraform and CLI work for GA of Azure Fluid Relay

### ISSUE THREAD

**Issue by arikt-ms** [Azure/azure-cli#22938]
**Resource Provider**
Microsoft.FluidRelay

**Description of Feature or Work Requested**
Azure Fluid Relay is a new PaaS offering providing a platform for building low-latency, collaborative experiences. We are working on GA release and would like to request the release of Terraform and CLI libraries.

**Minimum API Version Required**
2022-06-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/fluidrelay/resource-manager/Microsoft.FluidRelay/stable/2022-06-01/fluidrelay.json

**Target Date**
30th June 2022

**Comment by yonzhan** [comment]
Fluid Relay
