### ISSUE TITLE
Add az bicep generate-params

### ISSUE THREAD

**Issue by nielsvanderkaap** [Azure/azure-cli#22930]
**Related command**
az bicep 

**Is your feature request related to a problem? Please describe.**
New Bicep CLI command generate-params is not supported using az CLI. This command generates a parameter file for a given bicep file.

**Describe the solution you'd like**
Add az bicep generate-params, thus allowing the generation of parameter files through az CLI.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team
