### ISSUE TITLE
We need way more infos on MLTable

### ISSUE THREAD

**Issue by danielsc** [Azure/azure-cli#22954]
Our documentation is lacking deeper information on the MLTable format. 
I cannot seem to find any reference docs, nor a JSON schema, nor any samples that go beyond referencing a single csv or jsonl file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5a19a0-c37e-4567-0c30-7efe1c433dfb
* Version Independent ID: 8c4e79d0-0f84-3a28-bfb4-9f972e02a37f
* Content: [az ml data](https://docs.microsoft.com/en-us/cli/azure/ml/data?view=azure-cli-latest#az-ml-data-create)
* Content Source: [latest/docs-ref-autogen/ml/data.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ml/data.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by Man-MSFT** [comment]
Those are all good points and I agree. For points 1+2, we will take an action item to update current docs to add the `$schema` line for examples to include the schema and point to schema very obviously.

For the third point, the library and pip link is referenced in the how to create doc, but the pip page is lacking. @QianqianNie can you take ownership on this? https://pypi.org/project/mltable 
Few things I'm seeing that can be improved: Description, sample usage, project link back to the msdoc.

**Comment by QianqianNie** [comment]
@SturgeonMi is working on adding sample notebook

**Comment by Man-MSFT** [comment]
@QianqianNie , @SturgeonMi , gentle reminder on the pip package information too! Thanks!

**Comment by maoding** [comment]
More information would be a great deal. I created a dataset in Azure ML via the GUI but now I struggle to do so using CLI `az ml data create` since I do not have enough information how to write the MLTable file residing next to the parquet files.
From the serveral steps in the GUI I can more or less assume what is needed but I do not find any reference how to write the MLTable file properly.

E.g. tabular data from blobstorage, include columns, change type and specify date format.

**Comment by eavanvalkenburg** [comment]
Documentation is indeed lacking a lot! I have been able to create a mltable deltalake set, but reading that into a dataframe based on the data asset is causing all sorts of issues with the error messages that do not help and the docs lacking examples!

**Comment by luigiw** [comment]
@QianqianNie @SturgeonMi can you provide an update on mltable documentations? Thank you.

**Comment by samuel100** [comment]
@luigiw this is now complete:

https://learn.microsoft.com/en-us/azure/machine-learning/how-to-mltable?tabs=cli%2Cadls

**Comment by samuel100** [comment]
#please-close
