### ISSUE TITLE
Keep getting key missing error while using Approve-AzPrivateEndpointConnection.

### ISSUE THREAD

**Issue by VigneshB-AzurePaaS** [Azure/azure-cli#22957]
Keep getting key missing error while using Approve-AzPrivateEndpointConnection. What is the parameter actually missing here?

Approve-AzPrivateEndpointConnection -Name "privateEndpointName" -ResourceGroupName "resourceGroupName" -ServiceName "storageAccountName"

Is there anything missing or wrong in the way I am giving this request?

![image](https://user-images.githubusercontent.com/104787499/174890016-6421264c-b139-44b6-8cf9-f92a65f918a5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e4446d-f721-eb1f-2d78-c8e6da619051
* Version Independent ID: e53bdc70-7750-b452-56b8-1caa2d938f0a
* Content: [az network private-endpoint-connection](https://docs.microsoft.com/en-us/cli/azure/network/private-endpoint-connection?view=azure-cli-latest#az-network-private-endpoint-connection-approve)
* Content Source: [latest/docs-ref-autogen/network/private-endpoint-connection.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/private-endpoint-connection.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Please create this issue in azure-powershell repo
