### ISSUE TITLE
"Auto grow feature for replica server cannot be disabled." when creating new mysql flexible-server

### ISSUE THREAD

**Issue by despian** [Azure/azure-cli#22968]
## Describe the bug

I'm hitting this error when trying to create a new MySQL server. As far as I can see it should not be a replica server. 

https://github.com/Azure/azure-cli/blob/fc3b0940514a0ed1d032a5c86f27dbfa655a2547/src/azure-cli/azure/cli/command_modules/rdbms/validators.py#L199

**Command Name**
`az mysql flexible-server create`

**Errors:**
```
Auto grow feature for replica server cannot be disabled.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```azurecli
az mysql flexible-server create \
  --location $LOCATION \
  --resource-group $RESOURCE_GROUP \
  --name $MYSQL \
  --admin-user $MYSQL_USER \
  --admin-password $MYSQL_PASS \
  --sku-name Standard_B1s \
  --tier Burstable \
  --public-access 0.0.0.0 \
  --storage-size 20 \
  --version 5.7 \
  --geo-redundant-backup Disabled \
  --high-availability Disabled \
  --storage-auto-grow Disabled \
  --iops 400 \
  --yes
```

## Expected Behavior

The MySQL server should be created without the error.

## Environment Summary
```
macOS-12.3.1-x86_64-i386-64bit, Darwin 21.4.0
Python 3.10.4
Installer: HOMEBREW

azure-cli 2.37.0

Extensions:
containerapp 0.3.4

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@despian Thank you for reaching out, we are looking into it.
