### ISSUE TITLE
Please help to provide az cli sopport for Azure Automation update management 

### ISSUE THREAD

**Issue by qiqiqiqil** [Azure/azure-cli#22961]
**Related command**

should be az automtion xxx

**Is your feature request related to a problem? Please describe.**

Customer has hundreds of VMs in Azure that would like to use Automation Update management to manage patch. currently most of their jobs are done using Az cli. Customer want az cli can also manage UM. 

**Describe the solution you'd like**

https://docs.microsoft.com/en-us/rest/api/automation/ 
This is the Azure automation rest api. Please let az cli can have according commands of below operations
![image](https://user-images.githubusercontent.com/107970730/174927950-f8b52672-d002-4735-a098-3f62a99ee9e6.png)

**Describe alternatives you've considered**

**Additional context**

[Schedule](https://docs.microsoft.com/en-us/rest/api/automation/schedule)	Schedule operations for runbooks.
[Software Update Configuration Machine Runs](https://docs.microsoft.com/en-us/rest/api/automation/software-update-configuration-machine-runs)	Provide information for Software Update Configuration Machine Runs.
[Software Update Configuration Runs](https://docs.microsoft.com/en-us/rest/api/automation/software-update-configuration-machine-runs)	Provide information for Software Update Configuration Runs.
[Software Update Configurations](https://docs.microsoft.com/en-us/rest/api/automation/software-update-configurations)	Manage Software Update Configurations.

**Comment by yonzhan** [comment]
automation
