### ISSUE TITLE
Issue deploying VM using CLI - az vm create 

### ISSUE THREAD

**Issue by aalmowaled** [Azure/azure-cli#22969]
Hello,

Trying to deploy a VM using pre-existing components as the user has a custom role that denies him from creating any new components (NIC, VNet, Subnet)
 
We've attempted the deployment from the portal and manually chose preexisting NIC/VNet/Subnet, and the deployment was successful
 
When we tried to deploy using cloudshell with specifying all the needed flags, we're getting the below error although we've specified all the required pre-existing components parameters in the command
 
**Command:**
az vm create --name VMName --resource-group RGName --attach-os-disk OSDiskName --nsg NSGName --os-type linux --vnet-name VNetName --public-ip-address "" --subnet SUBNETNAME

**Error:**
{"error":{"code":"InvalidTemplateDeployment","message":"Deployment failed with multiple errors: '**Authorization failed** for template resource 'VNETNAME' of type 'Microsoft.Network/virtualNetworks'. The client 'USERNAME' with object id 'OBJECTID' does not have permission to perform action 'Microsoft.Network/virtualNetworks/**write**' at scope '/subscriptions/SUBID/resourceGroups/RGNAME/providers/Microsoft.Network/virtualNetworks/VNETNAME'.:Authorization failed for template resource 'NSGNAME' of type 'Microsoft.Network/networkSecurityGroups'. The client 'USERNAME' with object id 'OBJECTID' does not have permission to perform action 'Microsoft.Network/networkSecurityGroups/write' at scope '/subscriptions/SUBID/resourceGroups/RGNAME/providers/Microsoft.Network/networkSecurityGroups/NSGNAME'.'"}}

As a workaround, we've tried to use an existing NIC, and it worked, using below command:
az vm create --resource-group "RGNAME" --name VMName --nics NICNAME --attach-os-disk OSDiskName --os-type linux --size Standard_B2ms 

So, we've tried to create a NIC serparately using pre-existing network components, and it worked just fine.
az network nic create --name NICNAME --resource-group RGNAME --vnet-name VNETName --subnet SubnetName --network-security-group NSGNAME --location eastus --public-ip-address ""

The question here, is why the deployment is succeeding when using a pre-defined NIC, but returning an authorization error (write) when using each networking component separately, noting that we are not creating(writing) any new components, we are using pre-existing ones?

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create)
* Content Source: [latest/docs-ref-autogen/vm.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Compute

**Comment by RakeshMohanMSFT** [comment]
@aalmowaled Apologies for the delay, can you please give the complete debug trace for us to troubleshoot the issue?

**Comment by Divya1388** [comment]
Hi We are having the same issue.
 We are wondering why we are needing Microsoft.Network/virtualNetworks/write when done with CLI versus the portal clicks do not require the same permission. 

Any help on this would be awesome

**Comment by Divya1388** [comment]
@RakeshMohanMSFT  would you please be able to help with this or should i create a new issue
