### ISSUE TITLE
Az cli version 2.37.0 breaks backwards compatibility

### ISSUE THREAD

**Issue by kjoth** [Azure/azure-cli#22977]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az ad sp list --filter "displayName eq '${SVC_PRINCIPAL_NAME}'" | jq -r '.[].appOwnerTenantId'
az ad sp list --filter "displayName eq '${SVC_PRINCIPAL_NAME}'" | jq -r '.[].appOwnerOrganizationId'

**Describe the bug**
In the versions 2.22.0 to 2.36.0, the command to get the TenantId is referenced by appOwnerTenantId field.
But in the version 2.37.0,  the command to get the TenantId is referenced by appOwnerOrganizationId field and not by the appOwnerTenantId.

**To Reproduce**
Run the command in az cli versions 2.37 and in the prior version 2.22 to 2.36.
az ad sp list --filter "displayName eq '${SVC_PRINCIPAL_NAME}'" | jq -r '.[].appOwnerTenantId'

**Expected behavior**
In the az-cli version 2.37 it will return null and the field appOwnerTenantId is not present. 

**Environment summary**
***Version 2.22***
On any az-cli, 
azure-cli                         2.22.1 *
core                              2.22.1 *
telemetry                          1.0.6
Extensions:
managementpartner                  0.1.3
databricks                         0.8.0
storage-preview                    0.7.3
account                            0.2.2
Python location '/usr/local/Cellar/azure-cli/2.22.1/libexec/bin/python'
Extensions directory '/Users/karthickj/.azure/cliextensions'
Python (Darwin) 3.8.9 (default, Apr  3 2021, 01:50:09)
[Clang 12.0.0 (clang-1200.0.32.29)]

***Version 2.37***
azure-cli                         2.36.0 *
core                              2.36.0 *
telemetry                          1.0.6
Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0
Python location '/opt/az/bin/python3'
Extensions directory '/home/ecaeskickstartadmininstallation/.azure/cliextensions'
Python (Linux) 3.8.13 (default, Apr 22 2022, 04:53:04)
[GCC 7.5.0]

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
We have clearly documented breaking changes in https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration, which points to https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-property-differences#serviceprincipal-property-differences.

`az ad sp list` also displays an in-tool warning for the breaking change.

```
> az ad sp list
This command or command group has been migrated to Microsoft Graph API. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
```
