### ISSUE TITLE
Return types not included in documentation

### ISSUE THREAD

**Issue by jonest** [Azure/azure-cli#22988]
At one point there were examples showing what was returned and what the different enums mean, but I can't seem to find where those exist anymore. I would expect the doc page for something like `az repos pr list` to show me the object that gets returned so I can understand what different things mean, but no matter where I look, I get redirected back to the page that just shows me the list of options for the command.

What happened to the example responses? Can those be linked in the documentation somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e48ddaa-64b8-e414-7ea9-2746827fcc5f
* Version Independent ID: 952f1742-6d3b-a177-a2e0-164b563c1771
* Content: [az repos pr](https://docs.microsoft.com/en-us/cli/azure/repos/pr?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/repos/pr.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/repos/pr.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@jonest Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@jonest you should be able to get sample responses here https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/get-pull-requests?view=azure-devops-rest-6.0#response.  

Also when you said enum, did you mean the enum of status parameter? --status {abandoned, active, all, completed}

**Comment by jonest** [comment]
> @jonest you should be able to get sample responses here https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/get-pull-requests?view=azure-devops-rest-6.0#response.

Thanks! I completely forgot about looking at the REST response docs. Is that something that you plan to include in the CLI docs, too? Some sort of "see also" or something :)

> Also when you said enum, did you mean the enum of status parameter? --status {abandoned, active, all, completed}

Yes, that's what I was referring to. The response was just returning the integer, but I didn't know which integer corresponded to which status

**Comment by RakeshMohanMSFT** [comment]
@jonest Thank you for the confirmation, to be honest its a lot of information for the cli documentation and we do not support links in cli help yet. but we will definitely consider this for future releases.

Let me know if you have any follow up questions, before we close this issue
