### ISSUE TITLE
az webapp config appsettings set: config key is not correctly generated when JSON settings file contains a hierarchy

### ISSUE THREAD

**Issue by fgheysels** [Azure/azure-cli#22993]
I'm running an Azure CLI command to update the configuration for a WebApp in Azure.
This command is executed via a DevOps pipeline, through an `AzureCLI@2` task (scripttype=pscore), running on a Linux agent (ubuntu-20.04).
The version of AzureCLI running on that agent: 2.198.0

**Related command**
I execute this code from the pipeline:

```
$tempFile = Join-Path -Path $(Agent.TempDirectory) -ChildPath "settingsfile"
Out-File -FilePath $tempFile -InputObject "{'ClientSettings': {'AzureB2C': {'ClientSecretSecretUri': '$b2cClientSecretSettingValue'}}}"

az webapp config appsettings set -n $myApp -g $myResourceGroup --settings @$tempFile
```

I would expect that a config value is added to my webapp, where the key would be: `ClientSettings:AzureB2C:ClientSecretUri`.
However, the setting's key is just `ClientSettings` and the value contains the remainder of the JSON, like this:

![image](https://user-images.githubusercontent.com/3605786/175428373-19632999-6829-482d-a966-030a3b4c4348.png)

When I run similar code, but with a JSON file that only contains a 2-level hierarchy, the same problem occurs.

PS: I use this method as a workaround, since executing the command like this:
```
az  webapp config appsettings set -n $myApp -g $myResourceGroup --settings "ClientSettings:AzureB2C:ClientSecret"="@Microsoft.KeyVault(SecretUri=....)"
```
also results in errors, as described here: https://github.com/Azure/azure-cli/issues/10066#issuecomment-516072988

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@fgheysels Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@fgheysels its seems to be as designed., nothing specific to CLI. Even the rest api is doing the same. @StrawnSC need your confirmation on this please.

**Comment by fgheysels** [comment]
I've currently solved it by not using `:` as a separator but use a double underscore instead `__`

I was calling this command in a DevOps pipeline that ran on a Windows Agent, but that didn't work as it should have.  (I thought the final ) was removed from my config value).   Switching to a Linux agent solved that problem.

**Comment by RakeshMohanMSFT** [comment]
@fgheysels Thank you for the update. Let us get a confirmation from @StrawnSC

**Comment by StrawnSC** [comment]
@RakeshMohanMSFT, yes this is working as expected. We don't traverse nested json when you pass a file in. It's assumed to be in the format `{key1: value1, key2: value2, ...}`, just like if you you called the command with `--settings key1=value1 key2=value2 ...`.

**Comment by fgheysels** [comment]
So, then this means that `az webapp config appsettings set` does not support nested config settings ?

**Comment by RakeshMohanMSFT** [comment]
@fgheysels yes.

**Comment by fgheysels** [comment]
Are there any plans to support this ?

**Comment by RakeshMohanMSFT** [comment]
@StrawnSC Can you please help with the above question?
