### ISSUE TITLE
Where can I find the --command-id?

### ISSUE THREAD

**Issue by zaminda** [Azure/azure-cli#22997]
I'm trying to use the `az aks command result` command but it's not clear how to get the command id. Can you add a bit more clarification here? az aks command invoke doesn't seem to return a command id.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d05319-449e-2d13-170a-3ad696849fe5
* Version Independent ID: c2fa8e60-a5f3-2510-5162-772d99570647
* Content: [az aks command](https://docs.microsoft.com/en-us/cli/azure/aks/command?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/aks/command.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks/command.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@zaminda Thank you for reaching out, we will help you with that.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@zaminda You can use these commands
`az aks command invoke -n "clustername" -g "resourcegroup" --command "kubectl get pods -n kube-system" --query id -otsv` This will give you a command id, which you can use like this.
`az aks command result -n "clustername" -g "resourcegroup" --command-id "id returned by the above query"` eg:, a690f2caa*********476d085df

**Comment by zaminda** [comment]
Thanks, @RakeshMohanMSFT, This was exactly what I was looking for.
