### ISSUE TITLE
Add an optional parameter called 'Location' to the Add/Update ActionGroup command

### ISSUE THREAD

**Issue by thomasp98296** [Azure/azure-cli#23002]
**Related command**

https://docs.microsoft.com/en-us/cli/azure/monitor/action-group?view=azure-cli-latest

We want to add an optional parameter named 'Location' which takes a string input. If location is not provided, then default it to 'Global' as current.

az monitor action-group create --action webhook https://alerts.contoso.com apiKey={APIKey} type=HighCPU --name MyActionGroup --resource-group MyResourceGroup

**Is your feature request related to a problem? Please describe.**

No, it is not a problem. We have always hardcoded it to "Global", but now we have regional action group, this is the support we like to add.
 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
monitor

**Comment by thomasp98296** [comment]
Hi @yonzhan , @kairu-ms , thanks for your help on this. Could you share with me an ETA when this change will be available? Thanks!

**Comment by kairu-ms** [comment]
We will support it in this sprint. It will be in the release of 2022-09-06
