### ISSUE TITLE
A call stack is reported instead of an error message on a malformed ISO-8601 duration

### ISSUE THREAD

**Issue by gh-andre** [Azure/azure-cli#23013]
## Describe the bug

If a malformed ISO-8601 duration is used when creating a Service Bus queue, a call stack is reported instead of a usable error that the duration is invalid.

**Command Name**

`az servicebus queue create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Unrecognised ISO 8601 date format: ''
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
...
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\isodate/isodates.py", line 203, in parse_date
isodate.isoerror.ISO8601Error: Unrecognised ISO 8601 date format: ''
```

## To Reproduce:

Try to create a Service Bus queue with a malformed ISO-8601 duration. For example:
```
az servicebus queue create --resource-group ABC --namespace-name XYZ --name Q1 --default-message-time-to-live PT7D
```
Note that there is an erroneous `T` in `PT7D`, which should be `P7D` instead.

## Expected Behavior

A useful error is reported, such as that this is not a valid ISO-8601 duration.

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0 *

Extensions:
azure-devops 0.23.0
ml 2.0.7

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@gh-andre Thank you for reaching out, we are looking into it.
