### ISSUE TITLE
`az batch application package create` errors on upload

### ISSUE THREAD

**Issue by mmckechney** [Azure/azure-cli#23011]
## Describe the bug
When trying to upload a Zip package, it errors on uploading to the storage account

**Command Name**
`az batch application package create`

**Errors:**
```
('Connection aborted.', TimeoutError('The write operation timed out'))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az batch application package create --name {} --resource-group {} --application-name {} --version {} --package-file {} -o {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0

Extensions:
aks-preview 0.5.85
containerapp 0.3.7
virtual-wan 0.2.12

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@mmckechney Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@mmckechney Can you please share the `--debug` log with us? It seems more like an issue with the service than the azure cli.

**Comment by RakeshMohanMSFT** [comment]
@mmckechney Thank you for the information provided. It looks like a network connectivity issue. Do you happen to have a proxy or firewall in place? can you try this is operation from a different network?

I believe CLI is python based which uses urllib3 and PowerShell uses .net (winhttp/winniet). Possibly that is causing the issue, these are just my assumptions.

**Comment by RakeshMohanMSFT** [comment]
@mmckechney Thank you for the update, I suggest you leverage PowerShell to unblock yourself and perhaps you can open a support ticket and they might help you with network log analysis to understand the root cause.
