### ISSUE TITLE
az functionapp create ERROR: usage error: --plan NAME_OR_ID | --consumption-plan-location LOCATION

### ISSUE THREAD

**Issue by BlaneG** [Azure/azure-cli#23029]
**Related command**
`az functionapp create`

**Describe the bug**
ERROR: usage error: --plan NAME_OR_ID | --consumption-plan-location LOCATION

**To Reproduce**
I copy and pasted an example from the Azure Functions documentation:
```az functionapp create --consumption-plan-location westeurope --runtime python --runtime-version 3.9 --functions-version 4 --name <APP_NAME> --os-type linux --storage-account <STORAGE_NAME>```

**Expected behavior**
The function app resources are created in Azure.

**Environment summary**
Install method: MSI
Shell Type: Bash
```
az --version

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
azure-cli                         2.37.0

core                              2.37.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\b_gra\.azure\cliextensions'

Python (Windows) 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 22:57:10) [MSC v.1929 32 bit (Intel)]

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@BlaneG Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@BlaneG We are unable to reproduce this issue. This is the command we used. In a similar environment.
`az functionapp create --consumption-plan-location westeurope --runtime python --runtime-version 3.9 --functions-version 4 --name issue23029 --os-type linux --storage-account issue23029 -g issue23029`

Can you share the debug log with us please? --debug

**Comment by BlaneG** [comment]
Hi @RakeshMohanMSFT 

From the debug log, it looks like it might be some default configuration:
```
cli.knack.commands: Configured default 'resource-group-west3d9hs' for arg resource_group_name
cli.knack.commands: Configured default 'webappplanmigrate3d9hs' for arg plan
``` 

So I am passing `--plan` and `--consumption-plan-location` parameters, but this might not be allowed. I'm not sure how the default configuration was set.

Here is the full debug log for `az functionapp create --consumption-plan-location westeurope --runtime python --runtime-version 3.9 --functions-version 4 --name issue23029 --os-type linux --storage-account issue23029 -g $resourceGroup --debug`:
cli.knack.cli: Command arguments: ['functionapp', 'create', '--consumption-plan-location', 'westeurope', '--runtime', 'python', '--runtime-version', '3.9', '--functions-version', '4', '--name', 'issue23029', '--os-type', 'linux', '--storage-account', 'issue23029', '-g', 'resource-group-west3d9hs', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Init colorama.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x020C7BB0>, <function OutputProducer.on_global_arguments at 0x0228D4F0>, <function CLIQuery.on_global_arguments at 0x022AB148>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'functionapp': ['azure.cli.command_modules.appservice']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: appservice                0.569        66       240
cli.azure.cli.core: Total (1)                 0.569        66       240
cli.azure.cli.core: Loaded 66 groups, 240 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : functionapp create
cli.azure.cli.core: Command table: functionapp create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x04723658>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\b_gra\.azure\commands\2022-06-27.11-59-28.functionapp_create.18356.log'.
az_command_data_logger: command args: functionapp create --consumption-plan-location {} --runtime {} --runtime-version {} --functions-version {} --name {} --os-type {} --storage-account {} -g {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0475E1D8>]
cli.knack.commands: Configured default 'resource-group-west3d9hs' for arg resource_group_name
cli.knack.commands: Configured default 'webappplanmigrate3d9hs' for arg plan
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0476D778>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0476D808>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0228D538>, <function CLIQuery.handle_query_parameter at 0x022AB190>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0476D7C0>]
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 39, in _ex_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 3392, in create_functionapp
azure.cli.core.azclierror.MutuallyExclusiveArgumentError: usage error: --plan NAME_OR_ID | --consumption-plan-location LOCATION

cli.azure.cli.core.azclierror: usage error: --plan NAME_OR_ID | --consumption-plan-location LOCATION
az_command_data_logger: usage error: --plan NAME_OR_ID | --consumption-plan-location LOCATION
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x04723778>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 3.210 seconds (init: 0.835, invoke: 2.375)
telemetry.save: Save telemetry record of length 3180 in cache
telemetry.check: Negative: The C:\Users\b_gra\.azure\telemetry.txt was modified at 2022-06-27 11:57:50.754353, which in less than 600.000000 s

**Comment by BlaneG** [comment]
@RakeshMohanMSFT here is the output of `az config param-persist show`:
```
Command group 'config param-persist' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
{}
```

**Comment by StrawnSC** [comment]
@BlaneG what output do you see if you enter `az config get defaults`?

**Comment by BlaneG** [comment]
@StrawnSC `az config get defaults` returns `[]`. I tried to create the resource again with az cli and it was created successfully. I had deleted some existing resource groups in the azure portal so perhaps this resulted in clearing some configuration defaults that I had set by accident.
