### ISSUE TITLE
Add support for --public-network-access for eventhubs namespace

### ISSUE THREAD

**Issue by vcariven** [Azure/azure-cli#23025]
**Related command**

`az eventhubs namespace create|update`

**Is your feature request related to a problem? Please describe.**

There seems to be no way of setting the `publicNetworkAccess` (`Enabled` or `Disabled`) of an eventhubs namespace, neither at creation/update time (with `az eventhubs namespace create|update`) nor with the `az eventhubs namespace network-rule` subcommand

**Describe the solution you'd like**

A new option `--public-network-access` (`Enabled`, `Disabled`) to the command `az eventhubs namespace create|update` like it exists for other resource type (rdbs, batch, ...)
**Describe alternatives you've considered**

I have tested the `--default-action` (`Allow`, `Deny`) of the `az eventhubs namespace create|update` command.
**Additional context**

```
azure-cli                         2.36.0 *

core                              2.36.0 *
telemetry                          1.0.6

Extensions:
azure-firewall                    0.12.0
resource-graph                     2.1.0
account                            0.2.1

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by Saglodha** [comment]
@vcariven- thanks for reaching out, we have added the required flag to our cmdlets, and it should go live by next week. Kindly reach out to us in case you have any additional questions. Thanks.
