### ISSUE TITLE
Az login is giving me below error 

### ISSUE THREAD

**Issue by gunjan4425** [Azure/azure-cli#23030]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by gunjan4425** [comment]
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20231

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by RakeshMohanMSFT** [comment]
@gunjan4425 Thank you for reaching out to us. did you get a chance to try https://github.com/Azure/azure-cli/issues/20231#issuecomment-1006381416 or any other solution provided here https://github.com/Azure/azure-cli/issues/20231. 

Also do share your environment details with us `az --version`

**Comment by gunjan4425** [comment]
yes. i tried to uninstall the azure CLI and tried to install via powershell but still it is giving the same error.

please find the azure cli version below

PS C:\Windows\system32> az --version
azure-cli                         2.37.0

core                              2.37.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\hp\.azure\cliextensions'

Python (Windows) 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 22:57:10) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Comment by repogh** [comment]
I am also facing this issue with both az login and connect-azaccount.

![azlogin error](https://user-images.githubusercontent.com/49834835/184646494-e81a5fd3-c5f4-4e3e-9ddf-63dbd8fed96c.PNG)


and even if I login to connect-azaccount which does not show any errors at login, but then try run my terraform, I get the attached:

![connectazAccount error](https://user-images.githubusercontent.com/49834835/184646514-842febf5-4738-42c9-be5d-525e84e085ff.PNG)


any suggestions?

**Comment by Glebuwka** [comment]
> I am also facing this issue with both az login and connect-azaccount.
> 
> ![azlogin error](https://user-images.githubusercontent.com/49834835/184646494-e81a5fd3-c5f4-4e3e-9ddf-63dbd8fed96c.PNG)
> 
> and even if I login to connect-azaccount which does not show any errors at login, but then try run my terraform, I get the attached:
> 
> ![connectazAccount error](https://user-images.githubusercontent.com/49834835/184646514-842febf5-4738-42c9-be5d-525e84e085ff.PNG)
> 
> UPDATE:
> 
> Solved it as suggested before, by deleting the .azure folder in the C:\Users\username folder

Thanks, had the error in Visual Studio `Tried to get token using Visual Studio. Access token could not be acquired. 
Exception for Visual Studio token provider Microsoft.Asal.TokenService.exe : TS003: Error, TS004: Unable to get access token.  'AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access `. Nothing helped until I tried your solution, saved my day.
