### ISSUE TITLE
Feature Error when trying to create app Gateway settings

### ISSUE THREAD

**Issue by AndyBunning** [Azure/azure-cli#23038]
Hi,

When trying to run the CLI command as described, I get an error "Subscription is note registered for feature TlsProxy", however, I get an error that this feature cannot be found.  Same in multiple subscriptions and tenancies and the same if run locally or in the Azure Shell.

To replicate issues, try running:
`az network application-gateway settings create --gateway-name <GatewayName> --name <Settings Name> --port 80 --resource-group <ResourceGroupName>`

Error received is:
```
(SubscriptionNotRegisteredForFeature) Subscription /subscriptions/xxx/resourceGroups//providers/Microsoft.Network/subscriptions/ is not registered for feature TlsProxy required to carry out the requested operation.
Code: SubscriptionNotRegisteredForFeature
Message: Subscription /subscriptions/xxx/resourceGroups//providers/Microsoft.Network/subscriptions/ is not registered for feature TlsProxy required to carry out the requested operation.
```

To check if this is a preview feature, I have tried:
`az feature show --name TlsProxy --namespace Microsoft.Network`
but get the error:
```
(FeatureNotFound) The feature 'TlsProxy' could not be found.
Code: FeatureNotFound
Message: The feature 'TlsProxy' could not be found.
```

Is this a fault with the documentation or the CLI?

Thanks,
  Andrew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c63d4d-6849-749c-73c4-3688e8c9ba55
* Version Independent ID: b86be45e-214c-d117-aed7-865558af497c
* Content: [az network application-gateway settings](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/settings?view=azure-cli-latest#az-network-application-gateway-settings-create)
* Content Source: [latest/docs-ref-autogen/network/application-gateway/settings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/application-gateway/settings.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by necusjz** [comment]
It's a typical error of feature registration. You can leverage [az feature register](https://docs.microsoft.com/en-us/cli/azure/feature?view=azure-cli-latest#az-feature-register) to register it by yourself or contact your administer to help you with it.

**Comment by Chrisw32** [comment]
Might be unrelated to you, as you could actually mean to create a "setting" but I ran into the same issue and noticed that the application gateway has 2 different "settings" a "settings" and a "http-settings". Querying our existing application gateway showed that the "Backend settings" shown in the portal are actually "http-settings".
https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/http-settings?view=azure-cli-latest

Changing my cli statement to the below worked without the above error
az network application-gateway http-settings create

**Comment by AndyBunning** [comment]
Thanks @Chrisw32 - that was the issue and need to use http-settings.

**Comment by juan-alcazar** [comment]
Thanks @Chrisw32, had the same issue when trying to create a listener with az network application-gateway liste create instead of az network application-gateway http-listener create

**Comment by Snodio** [comment]
Hi!

I got this same error message, and this solution seems a bit unclear.

As far as i understand, i need to register a resource provider. If so, which one do i need to register? Microsoft.network is registered.
