### ISSUE TITLE
az cognitiveservices account create: Examples for --encryption and --storage missing

### ISSUE THREAD

**Issue by timoklimmer** [Azure/azure-cli#23056]
I need to better understand how the --encryption and --storage parameters of the "az cognitiveservices account create" command are used. Can you provide a more detailed explanation and examples? Specifically, I am interested in using this in context of Form Recognizer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7172de-478b-5200-6370-747a8c40efb2
* Version Independent ID: baffbf17-2f5d-44a6-de77-7ecb320f35ed
* Content: [az cognitiveservices account](https://docs.microsoft.com/en-us/cli/azure/cognitiveservices/account?view=azure-cli-latest#az-cognitiveservices-account-create)
* Content Source: [latest/docs-ref-autogen/cognitiveservices/account.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/cognitiveservices/account.yml)
* Service: **cognitive-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@timoklimmer Thank you for reaching out, we are looking into it.

**Comment by timoklimmer** [comment]
I would appreciate concrete examples in the article. It's difficult for customers to infer what the JSON should look like from the documentation you passed.

**Comment by RakeshMohanMSFT** [comment]
@timoklimmer Sure, I understand. Let me get the document updated.
