### ISSUE TITLE
Ability to suppress MS Graph migration warning

### ISSUE THREAD

**Issue by Tiberriver256** [Azure/azure-cli#23057]
**Related command**
az ad group <any-command>

**Is your feature request related to a problem? Please describe.**
When running these commands I get the following very helpful warning message:

![image](https://user-images.githubusercontent.com/6989492/176283924-7ba8218e-2e3c-4365-aae4-2fdfe2560981.png)

However, I cannot make it go away. I would like other warnings to show up so `only-show-errors` is not an option.

**Describe the solution you'd like**
I'd like a configuration option to be able to mark that I have completed the migration and the warnings are no longer necessary.

**Describe alternatives you've considered**
`--only-show-errors` was considered but that hides ALL warnings which means I'd miss future helpful warnings.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Thanks for the feedback. I am very glad the warning is helpful. However, `--only-show-errors` is currently the only option to disable the warning.

Good news is that we have removed the warning in https://github.com/Azure/azure-cli/pull/22612 and the next version 2.38.0 that will be released on [08/02/2022](https://github.com/Azure/azure-cli/milestone/120) won't have it. 

You may also try our [edge build](https://github.com/Azure/azure-cli#edge-builds) if you want the warning to be removed right away. 😉

**Comment by Tiberriver256** [comment]
Thanks for the info @jiasli! We're using Azure DevOps hosted agents and the install requires admin rights so we, unfortunately, don't have control over what version is installed/used but waiting for 2.38.0 won't be too much of a problem.
