### ISSUE TITLE
Commands to add azure extensions

### ISSUE THREAD

**Issue by meetpatel1111** [Azure/azure-cli#23054]
I need to add databricks and datafsctory extension in the pipeline. Need commands for them go install extensions. Need links to pagess yo directly download extension like below. 

e.g. - az extension add --yes --source "https://aka.ms/logicapp-latest-py2.py3-none-any.whl"

or command to get the status of these services .e.g- running or not. 

Thanks in advance

**Comment by yonzhan** [comment]
extensions

**Comment by meetpatel1111** [comment]
Can you specify commands like I have given example for logic app extensions installation. I need commands for databricks and datafactory

**Comment by kairu-ms** [comment]
Why not use ` az extension add --name databricks `

**Comment by meetpatel1111** [comment]
@kairu-ms Used it not working so need the same solution as this - az extension add --yes --source "https://aka.ms/logicapp-latest-py2.py3-none-any.whl"

Reply ASAP.
Thanks

**Comment by kairu-ms** [comment]
https://azcliprod.blob.core.windows.net/cli-extensions/databricks-0.8.0-py3-none-any.whl

**Comment by kairu-ms** [comment]
@meetpatel1111 you can always find above links in [index.json](https://raw.githubusercontent.com/Azure/azure-cli-extensions/main/src/index.json) file

**Comment by meetpatel1111** [comment]
@kairu-ms getting error running command - az logicapp list --query "[?contains (name, 'std-app-na-uks-${PLATFORMENV}-$cl{CLAIMSDATAPLATFORMENV}-ais')].{Name:name, State:state}" --output table that ERROR: "list" is misspelled or not recognized by the system.

What could be the issue?
and any solution that you can provide. already tried upgrading cli.
TIA

**Comment by meetpatel1111** [comment]
@yonzhan Is there extension available for cognitive services? 
az cognitiveservices account list not working for querying status of the service.
