### ISSUE TITLE
'az ad app list --display-name' uses wildcard instead of exact match

### ISSUE THREAD

**Issue by SjoerdV** [Azure/azure-cli#23053]
**Related command**
az ad app list --display-name 'MYAPP'

**Describe the bug**
When multiple apps/service principals with similar names are present like: MYAPP, MYAPP2, MYAPP3 multiple apps are returned when running the command mentioned

**To Reproduce**
When running the command `az ad app list --display-name 'MYAPP'` returns all the apps mentioned above (like a wildcard)

**Expected behavior**
I expect the '`--display-name`' argument to behave like an exact match operator

**Environment summary**
apt-get / 2.37.0 / Linux (Debian-based) / bash -> pwsh

**Additional context**
Workaround is available, but is somewhat cumbersome: use the filter argument: `az ad app list --filter "displayname eq 'MYAPP'"`

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This logic of listing with `--display-name` as prefix has been there since 2016-07-29:

https://github.com/Azure/azure-cli/blob/33cbd01f75c7d4c3814de5a1cbf6f42de7890467/src/azure-cli/azure/cli/command_modules/role/custom.py#L748-L749

https://github.com/Azure/azure-cli/blame/33cbd01f75c7d4c3814de5a1cbf6f42de7890467/src/azure-cli/azure/cli/command_modules/role/custom.py#L748-L749

![image](https://user-images.githubusercontent.com/4003950/176338427-6b585c70-9f4a-4917-9c79-78daf86c60eb.png)

I am not sure if changing the behavior is a good choice...

**Comment by jiasli** [comment]
> it feels illogical to return more than one object when specifying --display-name, don't you agree?

Even though when creating an app, Azure CLI checks if there is an existing app with the specified `--display-name`:

https://github.com/Azure/azure-cli/blob/33cbd01f75c7d4c3814de5a1cbf6f42de7890467/src/azure-cli/azure/cli/command_modules/role/custom.py#L617-L627

The truth is `displayName` is not an identifier in Graph service and you may have multiple apps with the same display name!

```
> az ad app list --display-name myapp1 --output table
DisplayName    Id                                    AppId                                 CreatedDateTime
-------------  ------------------------------------  ------------------------------------  --------------------
myapp1         5607c536-27be-4e5b-97b9-65afaa553bd5  285149de-9e22-4410-85b9-38b2d2c0553d  2022-06-30T03:38:01Z
myapp1         b3781aac-6ee1-4e12-88e2-efdb9f01fd0e  8700fdad-f6ab-4d38-9909-7bae2c62cf31  2022-06-30T03:38:44Z
```

So my recommendation is to always use `appId` or `id` to uniquely identify your application.

**Comment by SjoerdV** [comment]
> The truth is displayName is not an identifier in Graph service and you may have multiple apps with the same display name!

@jiasli, Cool, that's very clear. Thanks! Closing this issue
