### ISSUE TITLE
Please elaborate on {PolicyName}

### ISSUE THREAD

**Issue by zaalion** [Azure/azure-cli#23068]
[Enter feedback here]
Mentioning {PolicyName} without any example is not very helpful. Could you please update the documentation with valid/read-world example of a PolicyName?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c6760bb-c278-da56-a95c-4e82e221f1e8
* Version Independent ID: e25cbd2a-b415-214f-7d50-c403992c9361
* Content: [az policy assignment](https://docs.microsoft.com/en-us/cli/azure/policy/assignment?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/policy/assignment.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/policy/assignment.yml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ARM

**Comment by RakeshMohanMSFT** [comment]
@zaalion PolicyName is an existing policy definition https://docs.microsoft.com/en-us/cli/azure/policy/definition?view=azure-cli-latest#az-policy-definition-create. These documents are specific to the respective commands and their usages and not related to all the related commands. 

For information on Azure Policy https://docs.microsoft.com/en-us/azure/governance/policy/assign-policy-portal
