### ISSUE TITLE
Can't upload anymore anything on my azure storage account

### ISSUE THREAD

**Issue by cleconte987** [Azure/azure-cli#23060]
## Describe the bug

Two days ago I tried to upload images on my storage account with the command "az storage blob upload --account-name --account-key" and got this error.
I cannot upload anything anymore.
I logged out of my account from az-cli and locked backed in again. I verified RBAC rules and everything seems fine, There is only me as administrator and I should have full access. I verified the two keys from my storage account and they are exactly what I am using, I tried using the other access key (2nd) from my storage account but still cannot access, I rotated this second key and tried with this new key but still coudn't access.
I really don't know either understand what is happening. Plz help

**Command Name**
`az storage blob upload`

**Errors:**
```

Authentication failure. This may be caused by either invalid account key, connection string or sas token value provided for your storage account.
                    

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload --account-name {} --account-key {} --container-name {} -f {} -n {} --content-type {} --content-encoding {} --overwrite`

## Environment Summary
```
Linux-5.15.0-40-generic-x86_64-with-glibc2.35, Ubuntu 22.04 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0
```

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Need storage service side to check why the account key is invalid

**Comment by cleconte987** [comment]
What should I do then?

**Comment by cleconte987** [comment]
I still can't upload anything.. I mean how much time is gonna take this issue?

**Comment by cleconte987** [comment]
Found the issue. Because of '../' present in --name
