### ISSUE TITLE
Application-Gateways can no longer be created via Azure-CLI

### ISSUE THREAD

**Issue by MrRdmGuy** [Azure/azure-cli#23079]
**Related command**

az network application-gateway create \
  --name myAppGateway \
  --location eastus \
  --resource-group myResourceGroup \
  --capacity 2 \
  --sku Standard_v2 \
  --http-settings-protocol http \
  --public-ip-address myAGPublicIPAddress \
  --vnet-name myVNet \
  --subnet myAGSubnet \
  --servers "$ACI_IP" \
  --routing-rules-type Basic

**Describe the bug**

Its not possible to create an application gatway via Azure CLI anymore, as due to the new API changes routing rules are required and there is now way to create the rules before the gateway.
Error:
.../Microsoft.Network/applicationGateways/MultivendorAppGateway01/requestRoutingRules/rule1 cannot be empty. All request routing rules should have a priority defined starting from api-version 2021-08-01","details":[]}]}}

**To Reproduce**

Try to create an application-gateway using the Azure CLI.

**Expected behavior**

The Application Gateway should be created.
**Environment summary**

azure-cli                         2.37.0
core                              2.37.0
telemetry                          1.0.6
Extensions:
ai-examples                        0.2.5
ssh                                1.1.1
Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1
**Additional context**

In my case I wanted to create the appgateway for container instaces.
The command above is from a MS-Docs article (https://docs.microsoft.com/en-us/azure/container-instances/container-instances-application-gateway#create-application-gateway)

**Comment by necusjz** [comment]
@MrRdmGuy, it's a known breaking change from service side (**priority is now mandatory**), you can refer to a previous issue for details:
- https://github.com/Azure/azure-cli/issues/22279

**Comment by Joelith** [comment]
This can be resolved by passing `--priority XXXX` to the command. The documentation should be updated as this is marked as an optional field. See: https://docs.microsoft.com/en-us/cli/azure/network/application-gateway?view=azure-cli-latest#az-network-application-gateway-create
