### ISSUE TITLE
az add app create - problem with parameters

### ISSUE THREAD

**Issue by stevefutcher** [Azure/azure-cli#23104]
I'm not sure if this is an issue with the docs or the cli.

The az app create command docs: https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-create show that there are 2 optional parameters --web-home-page-url and --web-redirect-uris.

Attempting to use either of these results in an error

`az ad app create --display-name new-app-3 --web-home-page-url https://VisualStudio/SPN`
 `unrecognized arguments: --web-home-page-url https://VisualStudio/SPN`

I have verified that the az ad app create --display-name test-app works within my subscription, and I have tried both parameters with and without quotes

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
You are using an older version of Azure CLI. `--web-home-page-url` and `--web-redirect-uris` are introduced in Azure CLI 2.37.0. Please update to 2.37.0 and see https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration.
