### ISSUE TITLE
Wrong commands in this document

### ISSUE THREAD

**Issue by HamzaAqel** [Azure/azure-cli#23108]
[Enter feedback here]
Please remove the section "Restore 'testserver2' to 'testserverNew', where 'testserverNew' is in a different resource group from 'testserver2'." and the command line below too because it is not supported in flexible server.

az postgres flexible-server restore --resource-group testGroup --name testserverNew \
  --source-server "/subscriptions/${SubID}/resourceGroups/${ResourceGroup}/providers/Microsoft.DBforPostgreSQL/servers/testserver2" \ --restore-time "2017-06-15T13:10:00Z"

![image](https://user-images.githubusercontent.com/42034142/177183753-dd7196be-f207-4c00-b1bd-9aa478b5eb5e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 065fdfa8-5ed2-e032-6ea7-99a1f5dc28b6
* Version Independent ID: 71881d7f-c4b3-ce3c-1a1a-6c17dc533852
* Content: [az postgres flexible-server](https://docs.microsoft.com/en-us/cli/azure/postgres/flexible-server?view=azure-cli-latest#az-postgres-flexible-server-restore)
* Content Source: [latest/docs-ref-autogen/postgres/flexible-server.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/postgres/flexible-server.yml)
* Service: **postgresql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@HamzaAqel Thank you for reaching out, we are looking into it.
