### ISSUE TITLE
az login

### ISSUE THREAD

**Issue by einkel** [Azure/azure-cli#23105]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-10-05T11:50:24.4394320Z and was inactive for 90.00:00:00.\r\nTrace ID: d580793e-e9a6-4b1e-8bcf-a868e4628700\r\nCorrelation ID: 37ed27a4-c7c0-46aa-82d5-78c1b329ef95\r\nTimestamp: 2022-07-04 10:28:43Z","error_codes":[700082],"timestamp":"2022-07-04 10:28:43Z","trace_id":"d580793e-e9a6-4b1e-8bcf-a868e4628700","correlation_id":"37ed27a4-c7c0-46aa-82d5-78c1b329ef95","error_uri":"https://login.microsoftonline.com/error?code=700082"}
Traceback (most recent call last):
Temp\pip-unpacked-wheel-rpp6y7vh\knack\cli.py, ln 215, in invoke
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --output {} --resource {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.17.1 *

Extensions:
azure-devops 0.18.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The error message is pretty clear:

>  The refresh token has expired due to inactivity. The token was issued on 2021-10-05T11:50:24.4394320Z and was inactive for 90.00:00:00.

Please re-run `az login`.
