### ISSUE TITLE
How to refresh durable function key "durabletask_extension" using Az Cli

### ISSUE THREAD

**Issue by alessiofilippin** [Azure/azure-cli#23107]
We are facing a strange issue with one of our Az Functions. We are using a durable functions which it does have several AppKeys configured, one of them is called "durabletask_extension".

We are trying to automate the refresh of the keys using Az Cli but apparently when we try to refresh the key - the shell gives an error like "Operation Returned an invalid status "NotFound" "

However, I can see from listing the keys that the key-name provided is supposed to be correct.

Kindly see images attached :)

is this a bug or am I doing something wrong?

** Refresh of default or master keys seems to be working just fine. **

![keylist](https://user-images.githubusercontent.com/47082128/175517032-bdd74c52-2348-4ec9-9cbf-902d21593a28.PNG)
![keyset](https://user-images.githubusercontent.com/47082128/175517038-9a7e8a19-ec4a-4bb1-b9ae-1cdb0598eec7.PNG)

**Comment by RakeshMohanMSFT** [comment]
@alessiofilippin Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@alessiofilippin you cannot set a system key. Read more about it here under **System Key**. https://docs.microsoft.com/en-us/azure/azure-functions/security-concepts?tabs=v4

The scope of system keys is determined by the extension, but it generally applies to the entire function app. System keys can only be created by specific extensions, **and you can't explicitly set their values**. Like other keys, you can generate a new value for the key from the portal or by using the key APIs.

**Comment by alessiofilippin** [comment]
Thank for your answer Rakesh - however this is part of a pw/key rotation automation exercise.

It's a pity as I am able to renew all the other keys but this durable key won't work from the AZ cli, only from the portal.

Do you know if there are any plans to make this key renewable from AzCli?

**Comment by RakeshMohanMSFT** [comment]
@alessiofilippin unfortunately no plans for now. But you can raise a feature request here. https://feedback.azure.com/d365community/forum/9df02822-f224-ec11-b6e6-000d3a4f0da0
