### ISSUE TITLE
 az deployment group create no response

### ISSUE THREAD

**Issue by HenrikSommer-eng** [Azure/azure-cli#23116]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
 az deployment group create

**Describe the bug**
When calling az deployment group create from powershell
and the parameters contains `>f` it $result is null, the output is instead saved in a file called `f`

**To Reproduce**
```
$overrideParameters = @(`
'environmentName=dev',`
'sqladminpassword=test>f',`
'test=random' )

$result = az deployment group create --debug `
            --name "Test" `
            --resource-group "RG-Test" `
            --template-file "C:\Projects\main.json" `
            --parameters $overrideParameters
```

main.json:
```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "environmentName": {
      "type": "string",
      "allowedValues": [
        "dev"
      ],
      "metadata": {
        "description": "Specify the environmentName."
      }
    },
    "sqladminpassword": {
      "type": "securestring"
    },
    "test": {
      "type": "string"
    }
  },  
  "resources": [],
  "outputs": {
    "output1": {
      "type": "string",
      "value": "outputfromarm"
    }
  }
}
```

**Expected behavior**
output is saved in `$result`

**Environment summary**
OS:Windows 10 
PSVersion                      5.1.19041.1682
az version
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.25.0"
  }
}

**Additional context**
It is a problem in ARM and also Bicep

**Comment by yonzhan** [comment]
ARM

**Comment by RakeshMohanMSFT** [comment]
@HenrikSommer-eng can you please try this instead? $overrideParameters = @('environmentName=dev','sqladminpassword="test>f"','test=random'). Its working i tested it.

**Comment by HenrikSommer-eng** [comment]
> @HenrikSommer-eng can you please try this instead? $overrideParameters = @('environmentName=dev','sqladminpassword="test>f"','test=random'). Its working i tested it.

Hi.
It is also working for me.

**Comment by RakeshMohanMSFT** [comment]
@HenrikSommer-eng Thank you for the confirmation. Glad to hear its working for you. I will close this issue now.
