### ISSUE TITLE
Issue in creating storage container via command line

### ISSUE THREAD

**Issue by lichardbaliuag** [Azure/azure-cli#23110]
## Describe the bug

**Command Name**
`az storage container create`

**Errors:**
```
unrecognized arguments: --accountkey ZIcz2Ld0dRCtfDXB/g+Ct+fjpxlXnJtZAas44MKXuV2FEVh8tK6drgxulD5cc2tpHCUzBe9choCO+AStsXeVFw==

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container create --name {} --account-name {} --accountkey {}`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0 *
```

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Hi @lichardbaliuag, this command doesn't required account key parameter, you can create simply by `az storage container create --name {} --account-name {}`

**Comment by evelyn-ys** [comment]
Hi @lichardbaliuag, Please make sure the storage account exist first.

You can create storage account with `az storage account create`
