### ISSUE TITLE
az network application-gateway rewrite-rule condition create missing documentation 

### ISSUE THREAD

**Issue by thelostfrayman** [Azure/azure-cli#23128]
in az network application-gateway rewrite-rule condition create
the --patern parameter strips charaters for some reason to make it keep the correct pattern you need to wrap it with 3 quotes
as per this issue:
https://github.com/Azure/azure-cli/issues/17897

`the same problem occurs for "^$" where the ^ character disapear unless you use """^$"""`

in addition the --variable parameter is missing documentation:
```
--variable
The variable whose value is being evaluated.
value from: az network application-gateway rewrite-rule condition list-server-variables
```

the problem is that this values in that list are incorrect... this is because this one parameter is used for multiple types of variables:
server variables
http request variables
http reponse vaiables

each of those have a prefix that needs to be added in front of the correct variable to be valid.. for example 
server variable "request_scheme" is actually "var_request_scheme" and http response header "strict-transport-security" is actually "http_resp_Strict-Transport-Security".

the prefix are not listed anywhere
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc60a4b6-f028-28ed-6fa3-274c13dd058a
* Version Independent ID: 124f693c-73d6-e2cc-721b-e681211681cc
* Content: [az network application-gateway rewrite-rule condition](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/rewrite-rule/condition?view=azure-cli-latest#az-network-application-gateway-rewrite-rule-condition-create)
* Content Source: [latest/docs-ref-autogen/network/application-gateway/rewrite-rule/condition.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/application-gateway/rewrite-rule/condition.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network
