### ISSUE TITLE
'Az ad show' not returning requested fields

### ISSUE THREAD

**Issue by manschoe** [Azure/azure-cli#23125]
**Related command**
az ad user show --id "email" --query="accountEnabled"

**Describe the bug**
Above command doesn't return the property accountEnabled. When asked for id it returns the id so it seems that not all fields can be queried since Microsoft Graph API is used. Also when no query is specified only a limited set of fields is returned in comparison of az cli versions under 2.37.

**Expected behavior**
Selecting the field returns the value.

**Environment summary**
Az cli version = 2.38.0

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by reiinoldo** [comment]
The same happens when I try to get the objectId

`az ad user show --id userEmail --query objectId`

**Comment by jiasli** [comment]
@manschoe, your problem is similar to https://github.com/Azure/azure-cli/issues/23017

@reiinoldo, as stated in https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration, `objectId` is now `id`.
