### ISSUE TITLE
Doc comments for --node-taints option. 

### ISSUE THREAD

**Issue by pecrow** [Azure/azure-cli#23127]
If you create a nodepool with X number of tags, and later update them to Y number of tags using the "--node-taints" flag they do get updated, but if you scale up the new nodes will go back to using X number if tags. Should we add a "note" section explaining or noting this behavior? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fce7ab-ab56-44c6-b9a8-405444247a0b
* Version Independent ID: dabbb6c6-c616-a6ec-61f6-1b9d3bb069e8
* Content: [az aks nodepool](https://docs.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest#az-aks-nodepool-update)
* Content Source: [latest/docs-ref-autogen/aks/nodepool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks/nodepool.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@pecrow Thank you for reaching out, we are looking into it.
