### ISSUE TITLE
az extension add fails

### ISSUE THREAD

**Issue by bweissman** [Azure/azure-cli#23123]
**Command Name**
`az extension add --source arcdata-1.4.2-py2.py3-none-any.whl --pip-proxy http://10.192.7.77:8080/ --debug`

**Errors:**
I am trying to add the arcdata extension on a system behind a proxy. 

```
An error occurred. Pip failed with status code 1. Use --debug for more information.
```

The CLI is complaining about failed SSL verification:

```
Starting new HTTPS connection (1): pypi.org:443
Incremented Retry for (url='/simple/jinja2/'): Retry(total=4, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))': /simple/jinja2/
```

Is there a way to simply ignore this error?

I did set

ADAL_PYTHON_SSL_NO_VERIFY=1
AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1

however, this doesn't seem to affect the PIP downloads.

## Expected Behavior

This should add the arcdata extension to the CLI.

## Environment Summary

```
azure-cli 2.37.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@bweissman I believe you could set the host as trusted in the [configuration file](https://pip.pypa.io/en/stable/topics/configuration/#repeatable-options) for pip.
