### ISSUE TITLE
az role assignment create - how do I add more than 1 role at a time?

### ISSUE THREAD

**Issue by diberry** [Azure/azure-cli#23133]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

It isn't clear how to add more than 1 role assignment at a time. Is it multiple calls to this command or can the value be an array or a string in a single call?

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by RakeshMohanMSFT** [comment]
@diberry Except the scope all other parameter are single values. Only scope is comma separated array. Therefore you will have to make multiple calls to this commands to create multiple roles.
