### ISSUE TITLE
Clarify documentation around id fields

### ISSUE THREAD

**Issue by mmyers299** [Azure/azure-cli#23138]
There needs to be clarification around the field --api-id based off of the name it sounds like it should be the azure Id field, which if you do az apim product api list is what comes back as the id. In reality it wants the api name. This is very unclear. Same thing with --product-id

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f1d8a83-6a7b-9193-c190-5cbc48dfefa9
* Version Independent ID: bab09491-36b3-ac03-b619-2728532b59e0
* Content: [az apim product api](https://docs.microsoft.com/en-us/cli/azure/apim/product/api?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/apim/product/api.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/apim/product/api.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@mmyers299 Thank you for reaching out, we will get back to you on this.

**Comment by RakeshMohanMSFT** [comment]
@mmyers299 We have explained this in detail here https://github.com/Azure/azure-cli/issues/22748. Let me know if you have any follow up question.
