### ISSUE TITLE
Cannot export credentials after successful az login

### ISSUE THREAD

**Issue by ysguy** [Azure/azure-cli#23158]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
[[](https://docs.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-linux)
](https://docs.microsoft.com/en-us/azure/active-directory/devices/howto-vm-sign-in-azure-ad-linux)

az ssh config --file ~/.ssh/config --ip 10.11.123.456

error: Config file destination folder C:\Users\ysguy\~\.ssh does not exist.

**Describe the bug**
While the Microsoft docs document refers to being able to export the client certificate for use in other applications, the command does not work when logging in with Azure AD credentials during the az login process

**To Reproduce**
az login
-- <complete login using your Azure AD credentials>
-- Test logging into the linux based VM with AD credentials: az ssh vm --ip 11.22.33.44
-- if you can successfully log in, now disconnect and run
az ssh config --file ~/.ssh/config --ip 11.22.33.44
-- Notice the error and it fails to export the .pub related to the user for auth. 
-- error: Config file destination folder C:\Users\ysguy\~\.ssh does not exist.

**Expected behavior**
The authenticated users .pub is exported for use in other SSH based applications (e.g. putty)

**Environment summary**
Installed on windows 11 using the Azure CLI installer 

az -v 

azure-cli                         2.38.0

core                              2.38.0
telemetry                          1.0.6

Extensions:
ssh                                1.1.2

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\ysguy\.azure\cliextensions'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Additional context**
Nothing additional to report.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@ysguy Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@ysguy On your windows machine you could navigate to your user profile directory and then run the below command:

>C:\Users\XXXX>az ssh config --file ./.ssh/config --ip 11.22.33.44
Generated SSH certificate C:\Users\XXXX\.ssh\az_ssh_config\11.22.33.44\id_rsa.pub-aadcert.pub is valid until 2022-07-13 01:30:27 PM in local time.
C:\Users\XXXX\.ssh\az_ssh_config\11.22.33.44 contains sensitive information (id_rsa, id_rsa.pub, id_rsa.pub-aadcert.pub). Please delete it once you no longer need this config file.

Hope this helps.

**Comment by ysguy** [comment]
That folder contains nothing other than the file 'known_hosts'

I traced the ssh session with a -- -v and it is writing to %temp% folders with temporary copies of the keys. 
Note: 1.1.1.1 has been substituted for the actual IP. myuserid has been substituted for actual external VM IP address. as you can see the session is generating a dynamic certificate and dumping it into a temp\aadsshcertg_<random>\ folder and using it for that session. I have recovered those cert files and tried them in puttygen but they do not properly conform to rsa standards. I am guessing something has been modified or they are using keychains of a non-standard length. 

`PS C:\Users\myuserid\.ssh>  az ssh vm --ip 1.1.1.1 -- -v
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug1: Connecting to 1.1.1.1 [1.1.1.1] port 22.
debug1: Connection established.
debug1: identity file C:\\Users\\myuserid\\AppData\\Local\\Temp\\aadsshcertg_8arp7c\\id_rsa type 0
debug1: certificate file C:\\Users\\myuserid\\AppData\\Local\\Temp\\aadsshcertg_8arp7c\\id_rsa.pub-aadcert.pub type 4
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
debug1: match: OpenSSH_8.2p1 Ubuntu-4ubuntu0.5 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 1.1.1.1 as 'user@azureaddomain.com'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:la+6uks9ZDUCUYS35Ysji+QiVnrE5lto4ai6bgdW9rw
debug1: Host '1.1.1.1' is known and matches the ECDSA host key.
debug1: Found key in C:\\Users\\myuserid/.ssh/known_hosts:1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: Will attempt key: C:\\Users\\myuserid\\AppData\\Local\\Temp\\aadsshcertg_8arp7c\\id_rsa.pub-aadcert.pub RSA-CERT SHA256:DwBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxGI explicit
debug1: Will attempt key: C:\\Users\\myuserid\\AppData\\Local\\Temp\\aadsshcertg_8arp7c\\id_rsa RSA SHA256:DwBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxGI explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: C:\\Users\\myuserid\\AppData\\Local\\Temp\\aadsshcertg_8arp7c\\id_rsa.pub-aadcert.pub RSA-CERT SHA256:DwBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxGI explicit
debug1: Server accepts key: C:\\Users\\myuserid\\AppData\\Local\\Temp\\aadsshcertg_8arp7c\\id_rsa.pub-aadcert.pub RSA-CERT SHA256:DwBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxGI explicit
debug1: Authentication succeeded (publickey).
Authenticated to 1.1.1.1 ([1.1.1.1]:22).
<port forwarding stuff removed>
debug1: channel 1: new [port listener]
debug1: channel 2: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: ENABLE_VIRTUAL_TERMINAL_INPUT is supported. Reading the VTSequence from console
debug1: ENABLE_VIRTUAL_TERMINAL_PROCESSING is supported. Console supports the ansi parsing
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Remote: /usr/sbin/aad_certhandler %u %k:5: key options: agent-forwarding port-forwarding principals pty user-rc x11-forwarding
debug1: Remote: /usr/sbin/aad_certhandler %u %k:5: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Remote: /usr/sbin/aad_certhandler %u %k:5: key options: agent-forwarding port-forwarding principals pty user-rc x11-forwarding
debug1: Remote: /usr/sbin/aad_certhandler %u %k:5: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-1031-azure x86_64)

<connected to shell>

`

**Comment by navba-MSFT** [comment]
@ysguy Try running the below command and check where the key is being saved:

>az sshkey create --location "MyVMLocation" --resource-group "MyVMRG" --name "Name"

This will help in finding the default location used by the ssh. In my machine it is using the user profile.

You can then navigate to that path and then run the below command using the switch` --keys-destination-folder`  and check if that helps:

>az ssh config --ip 20.219.88.39 --file /sshconfig --keys-destination-folder D:/sshkeys

**Comment by ysguy** [comment]
I think the crux of the issue is that a lot of people create local SSH credentials inside the VM and export them to the client, hence the sharing of the keys. I am NOT using this method, i am using my Azure AD account with MFA to log into the VM.  I am assuming because this is the case there is some dynamic generation of tokens occuring allowing a one-time session to the VM which in turn refreshes throughout the logged in process.

if i do a cat /etc/passwd in the VM my userid does not show up. however if i type `id` my account does appear

uid=13608044(userid@domain.com) gid=13608044(userid@domain.com) groups=13608044(userid@domain.com),116(admin),1001(aad_admins)

**It appears some kind of PAM authentication is taking place (pam_aad.so).  https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/auth-ssh and based on tthe image on that URL "a Short-lived OpenSSH Certificate" is requested. So perhaps the documentation needs to be updated and this may not be possible at a..** 

Also
**Get SSH key-based authentication without needing to distribute SSH keys to users or provision SSH public keys on any Azure Linux VMs that you deploy. This experience is much simpler than having to worry about sprawl of stale SSH public keys that could cause unauthorized access.**

Full output of action requested. 

PS C:\Users\myname> az sshkey create --location "East US" --resource-group "Grafana_group" --name "Grafana"
(AuthorizationFailed) The client 'myuserid@mydomain.com' with object id 'a77GUID49ee' does not have authorization to perform action 'Microsoft.Compute/sshPublicKeys/write' over scope '/subscriptions/63bffdGUID7d/resourceGroups/Grafana_group/providers/Microsoft.Compute/sshPublicKeys/Grafana' or the scope is invalid. If access was recently granted, please refresh your credentials.
Code: AuthorizationFailed
Message: The client 'myuserid@mydomain.com' with object id 'a77bGUID9ee' does not have authorization to perform action 'Microsoft.Compute/sshPublicKeys/write' over scope '/subscriptions/63bGUIDa7d/resourceGroups/Grafana_group/providers/Microsoft.Compute/sshPublicKeys/Grafana' or the scope is invalid. If access was recently granted, please refresh your credentials.

**Comment by navba-MSFT** [comment]
@ysguy Thanks for your reply. Could you please follow the below action plans in order and let me know if that helps ? Awaiting you reply.

**Plan 1:**
It seems that the problem is happening because you are trying to create the config file under a folder that doesn't exist "~/.ssh". The extension doesn't create a new folder for the config file if it doesn't exist. So could you try to create a the .ssh folder inside your user profile before running `az ssh config`.

**Plan 2:**
This might be a problem with how python generates an absolute path from the relative path provided by the user. It seems that the path is formatted wrong in the error message. Could you also check if providing the absolute path to the config file instead of relative path works ?

**Plan 3:**
If you are only interested in getting the credentials generated by the command and not the config file, in this case, you might prefer to use "[az ssh cert](https://docs.microsoft.com/en-us/cli/azure/ssh?view=azure-cli-latest#az-ssh-cert)" instead of "[az ssh config](https://docs.microsoft.com/en-us/cli/azure/ssh?view=azure-cli-latest#az-ssh-config)".

**Comment by ysguy** [comment]
Looks like you are right. the syntax of my command was wrong. This works:

az ssh config --file .ssh\config --ip 11.22.33.44

You cannot do ~\.ssh\config or any other permutation.

Generated SSH certificate C:\Users\MyUserID\.ssh\az_ssh_config\11.22.33.44\id_rsa.pub-aadcert.pub is valid until 2022-07-18 09:44:52 AM in local time.
C:\Users\MyUserID\.ssh\az_ssh_config\11.22.33.44 contains sensitive information (id_rsa, id_rsa.pub, id_rsa.pub-aadcert.pub). Please delete it once you no longer need this config file.


Thank you.
