### ISSUE TITLE
Release of MSI version 2022-01-31-preview

### ISSUE THREAD

**Issue by isolenov** [Azure/azure-cli#23152]
### Related command

az identity

### Resource Provider

Microsoft.ManagedIdentity

### Description of Feature or Work Requested

MSI has added a new resource Federated Identity Credentials (FIC) as a sub-resource of existing User Assigned Identities "userAssignedIdentities/federatedIdentityCredentials"

CLI is expected to provide CRUD operation for the given sub-resource. Take a look Request example.

high-level documentation: https://aka.ms/ami/wif/docs

FIC object looks like this:
```
{
        "issuer": "https://oidc.prod-aks.azure.com/IssuerGUID",
        "subject": "system:serviceaccount:ns:svcaccount",
        "audiences": ["api://AzureADTokenExchange"],
}
```
In AAD context Audiences array is supposed to have exactly one element in most of the cases. 
Is it possible to make "audiences": ["api://AzureADTokenExchange"] a default value with the ability to override?

### Minimum API Version Required

2022-01-31-preview

### Swagger PR link

https://github.com/Azure/azure-rest-api-specs/pull/19548

#### Existing command to create managed identity
```
az identity create --name $uaId --resource-group $rg --location $location --subscription $subscription
```
then this managed identity can be used for FIC CRUD operations below. Those 4 operations are expected to become available in CLI.

#### create/update FIC
```
az rest --method put `
--url "/subscriptions/$subscription/resourceGroups/$rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/$uaId/federatedIdentityCredentials/$ficId?api-version=2022-01-31-PREVIEW" `
--headers "Content-Type=application/json" `
--body "{'properties': { 'issuer': 'https://kubernetes-oauth.azure.com/', 'subject': 'system:serviceaccount:ns:svcaccount', 'audiences': ['api://AzureADTokenExchange'] }}"
```

#### read FIC
```
az rest --method get --url "/subscriptions/$subscription/resourceGroups/$rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/$uaId/federatedIdentityCredentials/$ficId?api-version=2022-01-31-PREVIEW"
```

#### supports paging
```
az rest --method get --url "/subscriptions/$subscription/resourceGroups/$rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/$uaId/federatedIdentityCredentials?api-version=2022-01-31-PREVIEW"
```

#### delete fic
```
az rest --method delete --url "/subscriptions/$subscription/resourceGroups/$rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/$uaId/federatedIdentityCredentials/$ficId?api-version=2022-01-31-PREVIEW"
```

### Target Date

July

### Additional context

pypi link: https://pypi.org/project/azure-mgmt-msi/6.1.0/
Given API version "2022-01-31-PREVIEW" is available in public cloud, mooncake, fairfax, but not air-gapped clouds

**Comment by yonzhan** [comment]
@zhoxing for awareness

**Comment by isolenov** [comment]
Hey, @yonzhan please advise what is the timeline for this request?

**Comment by zhoxing-ms** [comment]
@isolenov Since the work of this sprint is fully scheduled, we plan to release this feature in the next sprint **(09-06)**

**Comment by yanzhudd** [comment]
Hello @isolenov, could you please help to confirm below design for the cli command? To be consistent with the naming convention of other commands in the cli, we refer to the naming convention of `az ad app federated-credential`.

**create FIC:**
az identity federated-credential create --federated-credential-name  myFicName --name myIdentityName --resource-group myResourceGroup --issuer myIssuer --subject mySubject --audiences myAudiences

**update FIC:**
az identity federated-credential update --federated-credential-name  myFicName --name myIdentityName --resource-group myResourceGroup --issuer myIssuer --subject mySubject --audiences myAudiences

**read FIC:**
az identity federated-credential show --federated-credential-name  myFicName --name myIdentityName --resource-group myResourceGroup 

**read all FICs associated with the user-assigned identity:**
az identity federated-credential list --name myIdentityName --resource-group myResourceGroup

**delete FIC:**
az identity federated-credential delete --federated-credential-name  myFicName --name myIdentityName --resource-group myResourceGroup

**Comment by isolenov** [comment]
Hey @yanzhudd 
thank you for providing CLI commands.

Have one proposal from the team. In our impression '--name' is quite confusing in this context. User is creating federated-credential object and name should refer to this object name.

Would it be possible to change commands this way?
```
az identity federated-credential --name myFicName  --identity-name myIdentityName 
```

**Comment by yanzhudd** [comment]
> Hey @yanzhudd thank you for providing CLI commands.
> 
> Have one proposal from the team. In our impression '--name' is quite confusing in this context. User is creating federated-credential object and name should refer to this object name.
> 
> Would it be possible to change commands this way?
> 
> ```
> az identity federated-credential --name myFicName  --identity-name myIdentityName 
> ```

okay, looks great!

**Comment by isolenov** [comment]
awesome. thanks.

**Comment by yanzhudd** [comment]
Hello @isolenov, when we develop this feature, an error **'Request contains additional data that the service does not understand'** is reported. The details are attached below. Could you please help to take a look?

**Request URL**: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/zytest/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ide/federatedIdentityCredentials/fic?api-version=2022-01-31-preview'
**Request body**:
{
   "properties": {
      "audiences": ["api://AzureADTokenExchange"]
   }
}
**x-ms-request-id**: '37218ee2-4b4a-49b1-9f9e-8ec0941b9324'
**x-ms-correlation-request-id**: '37218ee2-4b4a-49b1-9f9e-8ec0941b9324'
**x-ms-routing-request-id**: 'SOUTHEASTASIA:20220803T101847Z:37218ee2-4b4a-49b1-9f9e-8ec0941b9324'
![image](https://user-images.githubusercontent.com/105691024/182585153-66fe169a-49db-463d-8c1f-4a383cd4b56f.png)

**Comment by isolenov** [comment]
this basically means that body cant be deserialized. it should not be "properties": {} object inside

body should look like this

{
        "issuer": "[https://oidc.prod-aks.azure.com/IssuerGUID"](https://oidc.prod-aks.azure.com/IssuerGUID%22),
        "subject": "system:serviceaccount:ns:svcaccount",
        "audiences": ["api://AzureADTokenExchange"],
}

**Comment by yanzhudd** [comment]
> this basically means that body cant be deserialized. it should not be "properties": {} object inside
> 
> body should look like this
> 
> { "issuer": "[https://oidc.prod-aks.azure.com/IssuerGUID"](https://oidc.prod-aks.azure.com/IssuerGUID%22), "subject": "system:serviceaccount:ns:svcaccount", "audiences": ["api://AzureADTokenExchange"], }

Okay, thanks. We will try it.

**Comment by yanzhudd** [comment]
> this basically means that body cant be deserialized. it should not be "properties": {} object inside
> 
> body should look like this
> 
> { "issuer": "[https://oidc.prod-aks.azure.com/IssuerGUID"](https://oidc.prod-aks.azure.com/IssuerGUID%22), "subject": "system:serviceaccount:ns:svcaccount", "audiences": ["api://AzureADTokenExchange"], }

Hi @isolenov, when our request body contains all three parameters (issuer, subject, audiences) and **not** remove the 'peoperties' object, the error is **not** reported (The request and response are attached below). It seems that only when we pass one or two parameters, the error is reported. So we thought it may not be deserialization causing the problem, could you please help to check it again? 
![image](https://user-images.githubusercontent.com/105691024/183854095-2f73fae2-742d-4ea6-8e9c-c480b08284f4.png)
![image](https://user-images.githubusercontent.com/105691024/183853846-3b52565f-b204-4297-b586-9c09f7118961.png)

**Comment by yanzhudd** [comment]
> > this basically means that body cant be deserialized. it should not be "properties": {} object inside
> > body should look like this
> > { "issuer": "[https://oidc.prod-aks.azure.com/IssuerGUID"](https://oidc.prod-aks.azure.com/IssuerGUID%22), "subject": "system:serviceaccount:ns:svcaccount", "audiences": ["api://AzureADTokenExchange"], }
> 
> Hi @isolenov, when our request body contains all three parameters (issuer, subject, audiences) and **not** remove the 'peoperties' object, the error is **not** reported (The request and response are attached below). It seems that only when we pass one or two parameters, the error is reported. So we thought it may not be deserialization causing the problem, could you please help to check it again? ![image](https://user-images.githubusercontent.com/105691024/183854095-2f73fae2-742d-4ea6-8e9c-c480b08284f4.png) ![image](https://user-images.githubusercontent.com/105691024/183853846-3b52565f-b204-4297-b586-9c09f7118961.png)

Hello @isolenov, since this has blocked our development progress, please check the reason causing this problem and reply to me before **Aug 22th**. Otherwise, this sprint will not have enough time for us to develop and test, so we will have to postpone it to the next sprint for **Ignite Event (10-12)**. Thanks for understanding.

**Comment by isolenov** [comment]
@yanzhudd, sorry for the late response, just returned back from vacation.

Results look good now. "properties" object is expected in body as it is a part if ARM resource definition, please, have a look on samples in [preview docs](https://review.docs.microsoft.com/en-us/rest/api/documentation-preview/federated-identity-credentials/create-or-update?view=azure-rest-preview&branch=result_54a08aa4-b4d2-469c-bfa4-86493e82b5ac)

All 3 parameters (issuer, subject, audiences) are mandatory that's why creation is failing when anything is missing.
So, the CLI looks as expected. 

This item is for Ignite as well. Kubernetes team is planning to announce FIC feature public preview on the event ant this can't happen without the CLI. Please let me know if this can be released.

**Comment by yanzhudd** [comment]
> @yanzhudd, sorry for the late response, just returned back from vacation.
> 
> Results look good now. "properties" object is expected in body as it is a part if ARM resource definition, please, have a look on samples in [preview docs](https://review.docs.microsoft.com/en-us/rest/api/documentation-preview/federated-identity-credentials/create-or-update?view=azure-rest-preview&branch=result_54a08aa4-b4d2-469c-bfa4-86493e82b5ac)
> 
> All 3 parameters (issuer, subject, audiences) are mandatory that's why creation is failing when anything is missing. So, the CLI looks as expected.
> 
> This item is for Ignite as well. Kubernetes team is planning to announce FIC feature public preview on the event ant this can't happen without the CLI. Please let me know if this can be released.

Hello @isolenov,
Since the error message **`Request contains additional data that the service does not understand`** may confuse user why the creation is failing, we propose to add a check logic in our side, i.e. if any parameters are missing we will report
`RequiredArgumentMissingError` error. Could you please help to confirm this?

**Comment by isolenov** [comment]
@yanzhudd 
"Request contains additional data that the service does not understand" appears when "issuer" or "subject" is missing. This is a bug on server side which is hiding more meaningful error message. This will be fixed on our side eventually.
Since all 3 properties are mandatory, please add a check on az cli side:
"issuer" - mandatory, not empty string
"subject" - mandatory, not empty string
"audiences" - mandatory, not empty array (array with at least one element)

**Comment by yanzhudd** [comment]
> @yanzhudd "Request contains additional data that the service does not understand" appears when "issuer" or "subject" is missing. This is a bug on server side which is hiding more meaningful error message. This will be fixed on our side eventually. Since all 3 properties are mandatory, please add a check on az cli side: "issuer" - mandatory, not empty string "subject" - mandatory, not empty string "audiences" - mandatory, not empty array (array with at least one element)

Since a default value of "audiences" is specified above (https://github.com/Azure/azure-cli/issues/23152#issue-1298911431):
> Is it possible to make "audiences": ["api://AzureADTokenExchange"] a default value with the ability to override?

may I ask if the parameter "audiences" also need to be checked?

**Comment by yanzhudd** [comment]
> @yanzhudd for the sake of consistency "audiences" should be checked as well. "audiences" should have a default value of ["api://AzureADTokenExchange"] when overridden by the user let's check that it is not empty array (array with at least one element)

Is that the rule for parameter "audiences" check is as follows?
- If the user does not pass this parameter, no error is reported. The default value ["api://AzureADTokenExchange"] is used.
- if the user passes this parameter, we check the size of the array.

**Comment by isolenov** [comment]
@yanzhudd this is correct. thank you
