### ISSUE TITLE
az aks nodepool snapshot list fails to show snapshot that exists in that rg

### ISSUE THREAD

**Issue by ddanboyle** [Azure/azure-cli#23159]
## Describe the bug
command az aks nodepool snapshot show --name SPCDevNodepool1Snapshot-2022.06.13 --resource-group rg-spc-dev-eastus2 shows the snapshot.  Yet right after that command az aks nodepool snapshot list --resource-group rg-spc-dev-eastus2 shows an empty list, even though the rg is specified.  Note this worked a week ago when I created the snapshot, the aks snapshot list displayed the snapshot, but it doesn't display the snapshot anymore.
This isn't a matter of being az account set in the correct subscription, I checked that.  We are in the correct subscription otherwise the snapshot show wouldn't have worked, yet right after that a submitted snapshot list command shows nothing.

**Command Name**
`az aks nodepool snapshot list`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks nodepool snapshot list --resource-group {}`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI

azure-cli 2.37.0 *

Extensions:
application-insights 0.1.16
azure-devops 0.25.0
azure-firewall 0.14.1
connectedk8s 1.2.8
k8s-configuration 1.5.1
log-analytics 0.2.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by ddanboyle** [comment]
C:\bin>az aks nodepool snapshot show --name SPCDevNodepool1Snapshot-2022.06.13 --resource-group rg-spc-dev-eastus2
{
  "creationData": {
    "sourceResourceId": "/subscriptions/3662312a-0355-4793-9e66-0f722fdb63c4/resourcegroups/rg-spc-dev-eastus2/providers/Microsoft.ContainerService/managedClusters/aks-spc-dev-eastus2-dev1-01/agentPools/nodepool1"
  },
  "enableFips": null,
  "id": "/subscriptions/3662312a-0355-4793-9e66-0f722fdb63c4/resourceGroups/rg-spc-dev-eastus2/providers/Microsoft.ContainerService/snapshots/SPCDevNodepool1Snapshot-2022.06.13",
  "kubernetesVersion": "1.21.7",
  "location": "eastus2",
  "name": "SPCDevNodepool1Snapshot-2022.06.13",
  "nodeImageVersion": "AKSUbuntu-1804gen2containerd-2022.06.13",
  "osSku": "Ubuntu",
  "osType": "Linux",
  "resourceGroup": "rg-spc-dev-eastus2",
  "snapshotType": "NodePool",
  "systemData": {
    "createdAt": "2022-07-05T21:13:40.031694+00:00",
    "createdBy": "Darwin.Boyle@travelport.com",
    "createdByType": "User",
    "lastModifiedAt": "2022-07-05T21:13:40.031694+00:00",
    "lastModifiedBy": "Darwin.Boyle@travelport.com",
    "lastModifiedByType": "User"
  },
  "tags": null,
  "type": "Microsoft.ContainerService/Snapshots",
  "vmSize": "Standard_D4s_v3"
}

Then

C:\bin>az aks nodepool snapshot list --resource-group rg-spc-dev-eastus2
[]

Should show that snapshot in the list, but instead it shows an empty list.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@ddanboyle Thank you for reaching out to us, we are looking into it. Can you please share the debug trace for both show and list command?

**Comment by RakeshMohanMSFT** [comment]
We are unable to reproduce the issue, we tried the following commands and they all are working as expected.
```
az aks snapshot create -n issue23159 -g Issue23159 --nodepool-id <resourceeId>
az aks nodepool snapshot show -n issue23159 -g Issue23159
az aks nodepool list --cluster-name issue23159 -g Issue23159
az aks nodepool snapshot list
```
Pleasee verify your permissions once and do share the --debug trace of the non working command
