### ISSUE TITLE
az login无法使用: Authentication failed: 'utf-8' codec can't decode byte 0xb5 in position 3: invalid start byte

### ISSUE THREAD

**Issue by xgzwlkj** [Azure/azure-cli#23150]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Authentication failed: 'utf-8' codec can't decode byte 0xb5 in position 3: invalid start byte
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.8.10

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
2.8.10 is very old version. Could you update to the latest 2.38.0 and try again? See https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli
