### ISSUE TITLE
az ml workspace update --application-insights does not work

### ISSUE THREAD

**Issue by sebgros-ms** [Azure/azure-cli#23154]
> az ml workspace update --resource-group XXXXX --name xxxx --application-insights /subscriptions/xxx/resourceGroups/XXX/providers/microsoft.insights/components/xxxx --update-dependent-resources

Does not work => The application insight remains unchanged

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@sebgros-ms Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@sebgros-ms We are unable to reproduce the issue, i could map  the application insights  successfully.

![image](https://user-images.githubusercontent.com/49954584/178198088-7f22aa65-86d3-4ebb-b1d5-688e4911e1d5.png)

Here is the command i used
`az ml workspace update -g Issue23154 -n Issue23154 --update-dependent-resources`
