### ISSUE TITLE
Missing parameter "--http-proxy-config" documentation on "az aks create" and "az aks update" command

### ISSUE THREAD

**Issue by j-pedrosa** [Azure/azure-cli#23169]
It's missing information related with the parameter "--http-proxy-config" on "az aks create" command and "az aks update".
This is based on the documentation below:
https://docs.microsoft.com/en-us/azure/aks/http-proxy

Please note that on az aks create help command we already have a short description of the parameter.

azure-cli                         2.36.0 *

$ az aks create -h | less | grep "http-proxy-config"
    --http-proxy-config                           : Http Proxy configuration for this cluster.

$ az aks update -h | less | grep "http-proxy-config"
    --http-proxy-config                           : HTTP Proxy configuration for this cluster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks.yml)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@j-pedrosa Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by navba-MSFT** [comment]
@Azure/aks-pm Could you please look into this issue and provide an update once you get a chance ?

**Comment by FumingZhang** [comment]
cc @alexeldeib

**Comment by alexeldeib** [comment]
sorry about that! should be fixed in https://github.com/Azure/azure-cli/pull/23352 pending next release.

looks like you already found the workaround with preview extension
