### ISSUE TITLE
Typo colunm_name instead of column_name

### ISSUE THREAD

**Issue by askpatrickw** [Azure/azure-cli#23161]
Typo colunm_name instead of column_name in two places.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1e4e3d-3872-95c6-5089-fcfcbf74b325
* Version Independent ID: b665e74a-272e-f511-3042-75939704d7f5
* Content: [az monitor log-analytics workspace table](https://docs.microsoft.com/en-us/cli/azure/monitor/log-analytics/workspace/table?view=azure-cli-latest#az-monitor-log-analytics-workspace-table-list)
* Content Source: [latest/docs-ref-autogen/monitor/log-analytics/workspace/table.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/monitor/log-analytics/workspace/table.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
monitor
