### ISSUE TITLE
az costmanagement is unavailable (misspelled)

### ISSUE THREAD

**Issue by mjbright** [Azure/azure-cli#23168]
Running "az costmanagement export" tells me ```'costmanagement' is misspelled or not recognized by the system.```

Clearly the plugin is not being auto-installed as this page suggests.

```
az --version
azure-cli                         2.38.0

core                              2.38.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/mjb/.azure/cliextensions'

Python (Linux) 3.10.5 (main, Jul  1 2022, 04:14:40) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23e59ee9-036f-374f-3029-747d94336052
* Version Independent ID: 3d0d61b6-99bc-327d-c549-7722ca230eb6
* Content: [az costmanagement](https://docs.microsoft.com/en-us/cli/azure/costmanagement?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/costmanagement.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/costmanagement.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
costmanagement

**Comment by jsntcy** [comment]
@mjbright, could you try to install the extension manually by running the command `az extension add --name costmanagement` to see if it's installed or not?
