### ISSUE TITLE
[webapp] [Discussion] Promote the slot/appsettings command groups up a level

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2316]
This is somewhat subjective, but I can't help but feel like some of the command groups within the `appservice` module are unnecessarily deep, and could be potentially simplified a little bit.

One area that I've noticed being a bit "wordy" is working with deployment slots for a web app. For example, to swap two slots, you need to run the following command: `az appservice web deployment slot swap`, which is quite a mouthful. 

I can't help but feel like slots are a valuable enough concept that they could be promoted directly underneath the `web` group, which would reduce the extra group level (i.e. `deployment`), and allow typing `az appservice web slot swap`, which is quite a bit more ergonomic.

Another example of a commonly-used command group, that would potentially be nice to "promote" is `appservice web config appsettings`. I completely appreciate the logical/semantic grouping of commands, but at the same time, in my usage, I feel like having four levels of command group nesting (for commonly-used features), gets a bit tiresome to use. Could `appsettings` also be lifted directly underneath `web`? It feels like that would be helpful, but that could just be me.

The storage module is a good example of a command group that could have been nested more deeply than it is (e.g. both `blob` and `container` are top-level groups underneath `storage`, as opposed to nesting them underneath a more general group for blob-related commands), and the act of flattening groups a little bit makes the overall experience better.

In general, I'd love to see some simplifications of the App service commands, but in particular, it would be great to try to reduce group depth for commonly used commands.

**Comment by lostintangent** [comment]
In addition to "lifting" the `appsettings` command group up a level, I'd also like to propose renaming it to `env`. This not only shortens it (to improve efficiency), but I feel like that is a more idiomatic name for what they represent: environment variables.

**Comment by lostintangent** [comment]
@yugangw-msft Any updates on this discussion? With #2325 coming (yay!), it would be amazing to flatten some of the other core command groups as well:

```
az webapp env update
az webapp slot swap
```

**Comment by yugangw-msft** [comment]
After through numerous rounds of discussion & review since last year, i believe we have settled on what we have now. :)
