### ISSUE TITLE
az consumption usage list - resulting error message is unclear

### ISSUE THREAD

**Issue by mjbright** [Azure/azure-cli#23170]
I tried to use ```az consumption usage list``` and got the following error (when using the latest ```az cli```):

```
Command group 'consumption' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(400) Subscription scope usage is not supported for current api version. Please use api version after 2019-10-01 (Request ID: 2f1d12d0-ce2e-4d85-a2ed-6443607f8edc)
```

What's user to do ?

There should be. a simple solution to this - and that should be evoked here

```
 az --version
azure-cli                         2.38.0

core                              2.38.0
telemetry                          1.0.6

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/mjb/.azure/cliextensions'

Python (Linux) 3.10.5 (main, Jul  1 2022, 04:14:40) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e05c0768-9cfc-3b78-4f39-70a8c1f0b6bd
* Version Independent ID: b5e5d8fa-e84c-408a-3f49-19d245563abd
* Content: [az consumption usage](https://docs.microsoft.com/en-us/cli/azure/consumption/usage?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/consumption/usage.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/consumption/usage.yml)
* Service: **cost-management-billing**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@mjbright Thanks for reaching out to us and sharing this feedback. Cost Management supports only Enterprise Agreement, Web direct and Microsoft Customer Agreement offer types. I hope that your subscription XXXXXX is associated with a valid offer type.

Could you please run the below command and check if that helps?

> az rest --method GET 'https://management.azure.com/subscriptions/XXXXXXXX/providers/Microsoft.Consumption/usageDetails?api-version=2019-10-01'

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mjbright I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you  have any update on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mjbright The action is currently pending on you to test the above plan. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by geosword** [comment]
> @mjbright Thanks for reaching out to us and sharing this feedback. Cost Management supports only Enterprise Agreement, Web direct and Microsoft Customer Agreement offer types. I hope that your subscription XXXXXX is associated with a valid offer type.
> 
> Could you please run the below command and check if that helps?
> 
> > az rest --method GET 'https://management.azure.com/subscriptions/XXXXXXXX/providers/Microsoft.Consumption/usageDetails?api-version=2019-10-01'
> 
> Awaiting your reply.

Just for anyone else stumbling on this like I did. I couldnt get this command to work. It kept returning `Bad Request`, I found that `usageDetails` should actually be `UsageDetails` and that `--url` was required.
```
az rest --method GET --url 'https://management.azure.com/subscriptions/<subscription-id>/providers/Microsoft.Consumption/UsageDetails?api-version=2019-10-01'
```

**Comment by Swaps76** [comment]
In the long output of the command then, what are we looking for to check the agreement type?

**Comment by CarlosJoseChaconChavarria** [comment]
> > @mjbright Thanks for reaching out to us and sharing this feedback. Cost Management supports only Enterprise Agreement, Web direct and Microsoft Customer Agreement offer types. I hope that your subscription XXXXXX is associated with a valid offer type.
> > Could you please run the below command and check if that helps?
> > > az rest --method GET 'https://management.azure.com/subscriptions/XXXXXXXX/providers/Microsoft.Consumption/usageDetails?api-version=2019-10-01'
> > 
> > 
> > Awaiting your reply.
> 
> Just for anyone else stumbling on this like I did. I couldnt get this command to work. It kept returning `Bad Request`, I found that `usageDetails` should actually be `UsageDetails` and that `--url` was required.
> 
> ```
> az rest --method GET --url 'https://management.azure.com/subscriptions/<subscription-id>/providers/Microsoft.Consumption/UsageDetails?api-version=2019-10-01'
> ```

very helpful command I was trying to delete a budget using Azure DevOps using AZ CLI and this is the way to do it 

these 2 did not work 
```
Remove-AzConsumptionBudget -Name budget01 -PassThru
az consumption budget delete --budget-name budget01
```
