### ISSUE TITLE
az afd route update - required for app service connectivity

### ISSUE THREAD

**Issue by harvey-k** [Azure/azure-cli#23182]
## Describe the bug

Multiple `az afd route update` commands are required for requests to be properly sent from a Azure Front Door Standard to Azure App Service.

**Command Name**
`az afd route update`

**Errors:**
```
Our services aren't available right now - We're working to restore all services as soon as possible
```

## To Reproduce:

I'm experiencing an issue when attempting to connect an Azure Front Door Standard SKU to an Azure App Service. The deployment configuration is very similar to this:
https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.cdn/front-door-standard-premium-custom-domain-customer-certificate

The issue is upon on initial infrastructure creation in a new Resource Group, Azure Front Door Standard returns html responses similar to:
`Our services aren't available right now - We're working to restore all services as soon as possible`

This will continue, for at least several hours so it's not a propagation issue, until the following azure cli commands are executed:

```
az afd route update -g ${rgName} \
  --profile-name ${profileName} \
  --endpoint-name ${endpointName} \
  --route-name ${routeName} \
  --enabled-state Disabled;

az afd route update -g ${rgName} \
  --profile-name ${profileName} \
  --endpoint-name ${endpointName} \
  --route-name ${routeName} \
  --enabled-state Enabled;
```

After the above commands are executed, and after the normal propagation delay, Azure Front Door returns expected responses.

Is this expected behavior? I found what appears to be a similar scenario on stackoverflow:
https://stackoverflow.com/questions/71484194

## Expected Behavior

The `az afd route update` commands should not need to be executed.

## Environment Summary
```
Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.31, Ubuntu 20.04.2 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0 *

Extensions:
storage-preview 0.8.2
resource-graph 2.1.0
front-door 1.0.16
ssh 1.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@harvey-k Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@harvey-k https did you get a chance to see this? ://stackoverflow.com/questions/54312954/azure-front-door-configured-site-is-returning-services-not-available. Also this forum is for azure cli issue specifically. If the issue persists after trying the suggestion provided in the stackoverflow. Please open a support ticket from the azure portal.
