### ISSUE TITLE
Unable to set up tab completion.

### ISSUE THREAD

**Issue by jgardner04** [Azure/azure-cli#2318]
I have run the install command with sudo privileges on my macOS Sierra and am getting the error below.

```
Backed up '/Users/jgardner/.bash_profile' to '/Users/jgardner/.bash_profile.backup'
-- Unable to set up tab completion. ERROR: [Errno 13] Permission denied: '/Users/jgardner/.bash_profile'
-- Installation successful.
-- Run the CLI with /Users/jgardner/bin/az --help
Jonathans-MacBook-Pro:~ jgardner$ az --help
-bash: az: command not found
```

**Comment by derekbekoe** [comment]
@jgardner04 What's the output of the following command?
```
$ ls -la /Users/jgardner/.bash_profile
```

Also, how did you install? I assume it was `curl -L https://aka.ms/InstallAzureCli | bash` but were there any other steps?

**Comment by teerasej** [comment]
@derekbekoe I got same error in macOS Sierra 10.12.3. I install Azure CLI with official command: `curl -L https://aka.ms/InstallAzureCli | bash`

After run your suggested command, I got following message:

`-rw-r--r--  1 root  staff  36 Jan 12 15:28 /Users/teerasejjiraphatchandej/.bash_profile`

I proceed the installation step, one by one with default setting. Nothing special.

**Comment by derekbekoe** [comment]
Your `.bash_profile` file is not owned by you so the install script couldn't write to it to set up tab completion. You can use `chown` to change ownership of the file to your user OR use `chmod` to give your user access to to the file (e.g. `chmod g+w .bash_profile`).
