### ISSUE TITLE
Replace `az ml compute` commands with `az ml computetarget` commands instead.

### ISSUE THREAD

**Issue by EarthlyAlien** [Azure/azure-cli#23188]
`az ml compute` commands don't work anymore. `compute` is replaced by `computetarget` as per suggestions from Azure CLI. 

![image](https://user-images.githubusercontent.com/29950445/178715062-03016925-bf30-4cb4-80d3-fd919c009396.png)

But, docs weren't updated yet.

![image](https://user-images.githubusercontent.com/29950445/178715219-57070835-2af6-4571-af05-ed7ec0cecebc.png)

So, please update the docs accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63446f78-d3ac-0cc3-a102-a1612c54d90e
* Version Independent ID: a20a657c-aeaa-d122-0714-1aa2cfecd966
* Content: [az ml workspace](https://docs.microsoft.com/en-us/cli/azure/ml/workspace?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/workspace.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ml/workspace.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@EarthlyAlien Thank you for reaching out to us, we are looking into it.

**Comment by EarthlyAlien** [comment]
Apologies for the confusion. Understood the difference. Apparently I installed older extension [v1](azure-cli-ml) instead of newer extension [v2](ml).

Sorry about that. Everything's fine now. But, it'd be better if you could add the `az extension add --name ml` for v2 commands and `az extension add --name azure-cli-ml` for v1 commands.
