### ISSUE TITLE
"az account get-access-token --scope ..." fails on Azure Cloud Shell

### ISSUE THREAD

**Issue by dvasdekis** [Azure/azure-cli#23183]
## Describe the bug

When running in Azure Cloud Shell (pressing button from portal.azure.com), the `az account get-access-token --scope ...` command fails, but it works fine on my PC. This happens regardless of running `az login --identity` (which succeeds) or not.

**Command Name**
`az account get-access-token`

**Errors:**
```
Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned: <Response [400]>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Open Azure Cloud Shell from portal.azure.com
- `az login --identity`
- `az account get-access-token --scope "499b84ac-1321-427f-aa17-267ca6975798/user_impersonation"` (this is the fixed scope for Azure Devops)

## Expected Behavior

Token request succeeds and CLI returns token, as it does on my Windows PC

## Environment Summary
```
Linux-5.4.0-1086-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.5
Installer: DEB

azure-cli 2.38.0

Extensions:
databricks 0.7.3
ai-examples 0.2.5
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by jiasli** [comment]
Cloud Shell only allows limited set of scopes. See https://github.com/Azure/azure-cli/issues/11386

**Comment by satumkurmsft** [comment]
> Cloud Shell only allows limited set of scopes. See #11386

@jiasli - Where is this set of resources / scopes defined? How do we get on this list? (we are MS internal 1P service)
