### ISSUE TITLE
Example of az sigs --tags on documentation 

### ISSUE THREAD

**Issue by AzySir** [Azure/azure-cli#23191]
Hi there - can someone please review the documentation and provide a nice and clean example with an updated definition of how to use the --tags for sigs (https://docs.microsoft.com/en-us/cli/azure/sig?view=azure-cli-latest)

```
--tags
Space-separated tags: key[=value] [key[=value] ...]. Use "" to clear existing tags.
```

^^ This literally has no meaning - anyone who has not use to azure/windows would get lost with this. Please update and provide an example

```
az vm update \
    --resource-group myResourceGroup \
    --name myVM \
    --set tags.myNewTagName1=myNewTagValue1 tags.myNewTagName2=myNewTagValue2
```

Let's ignore the absence of consistency but if someone could at least provide an example - with a proper definition that would be greatly appreciated and I'm sure a great timesaver 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1f9155c-108c-b602-3d8e-d17a213eb3d0
* Version Independent ID: 90421467-30f0-75b6-d171-02b8e37e7d07
* Content: [az sig](https://docs.microsoft.com/en-us/cli/azure/sig?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/sig.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sig.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

---

**Comment by yonzhan** [comment]
Compute

**Comment by RakeshMohanMSFT** [comment]
@AzySir `az sig update -g Issue23191 -r issue23191gallery --set tags.tag1=tag1 tags.tag2=tag2` This should work for you. I will get the document updated soon.

**Comment by AzySir** [comment]
@RakeshMohanMSFT there is still no update in the documentation?

I've passed this issue since - but I have a feeling that method did not work...

<img width="638" alt="Screenshot 2022-08-22 at 9 16 27 pm" src="https://user-images.githubusercontent.com/37623164/186010956-be216492-6a0c-4ca1-9292-0547da4ee842.png">
