### ISSUE TITLE
az sig image-version create --tags break in version 2.38.0-1

### ISSUE THREAD

**Issue by LiliDeng** [Azure/azure-cli#23194]
Install latest version Azure CLI on ubuntu 1804
run ```az sig image-version create .... --tags test=true``` encounter this error ```
Parameter 'tags' must be of type 'dict[str, str]'```, downgrade version into 2.37.0-1, it works well.

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
> 2.37.0-1
> 2.38.0-1
I believe these version numbers are unofficial like https://github.com/Azure/azure-cli/issues/23094#issuecomment-1173262831
It should be related to issue https://github.com/Azure/azure-cli/issues/19640 @jiasli Please be aware

**Comment by LiliDeng** [comment]
we encounter this issue on ADO pipeline, then I install latest version on ubuntu following this guide https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-1-install-with-one-command, repro this issue.

**Comment by rafalslaby** [comment]
Seeing the same issue on azure-cli/focal 2.38.0-1~focal. We're forced to downgrade to 2.37.0-1 as a workaround

**Comment by eric-desrochers** [comment]
I did notice 2 workarounds:
- Downgrade
- Break the tagging portion out into separate operation.

Is there any permanent solution on the way ?

Note: This is preventing the release of SBI (Secure Base Image) using Ubuntu as the OS, as it is failing LISAv3 testing.

In the immediate situation, what approaches/workaround azure-cli team would suggest to unblock us ?

**Comment by qbradley** [comment]
I am also impacted by this bug.

**Comment by zhoxing-ms** [comment]
> 2.37.0-1
2.38.0-1

> I believe these version numbers are unofficial like https://github.com/Azure/azure-cli/issues/23094#issuecomment-1173262831
It should be related to issue https://github.com/Azure/azure-cli/issues/19640 @jiasli Jiashuo Li FTE Please be aware

As I mentioned before, please confirm whether you are installing the official version of CLI *(the version number does not have any suffix)*. In fact, we do not maintain the unofficial version of CLI

**Comment by zhoxing-ms** [comment]
I have submitted a PR #23393 to fix this issue, and it will be released in this sprint **09-06**
