### ISSUE TITLE
Machine Learning Studio: Allow multiple paths in input_data for parallel run steps

### ISSUE THREAD

**Issue by davystrong** [Azure/azure-cli#23196]
**Related command**

`az ml job create -f deployment_configs/inference_pipeline.yaml -s`

**Is your feature request related to a problem? Please describe.**

I need to run batched inference when data is added to a blob storage folder. For example, I have a container with three folders, A, B and C. I add two more folders, D and E. I would like to run a parallel inference pipeline and give it these two folders as input.

**Describe the solution you'd like**

Either the parallel job YAML config should accept a list for the input_data parameter or inputs should accept more than one path. The parallel job would run the init() function once and call run() as many times as necessary to consume all values from each input.

**Describe alternatives you've considered**

The only way I can find to do this is to register a v1 dataset using Python pointing to these folders and run inference on this dataset. This is annoying and requires registering a new dataset every time I want to run a job. Also, this type of dataset is described as "v1 legacy" so doesn't seem like it will be around long term.

The other possibility would be to create an individual job for each folder, however this doesn't work because of the startup overhead (pulling the docker image etc). I might have 50 folders I want to process, each taking 1 minute. 1 minute of startup overhead is ok for the whole batch, 1 minute each is unacceptable.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by diondrapeck** [comment]
Parallel jobs in pipelines for v2 is not yet ready for public preview or general availability. We will take your feedback into account as we continue to work on the feature.
