### ISSUE TITLE
Unable to execute az command invoke in a private cluster 

### ISSUE THREAD

**Issue by tdn-revan** [Azure/azure-cli#23203]
**Related command**
az command invoke

**Describe the bug**
While running az command invoke to run kubectl commands, it returns an error.
`(KubernetesOperationError) Failed to run command due to cluster perf issue, container command-5672af31a4494f459c14f0bf5e44215c in aks-command namespace did not start within 30s on your cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).
Code: KubernetesOperationError
Message: Failed to run command due to cluster perf issue, container command-5672af31a4494f459c14f0bf5e44215c in aks-command namespace did not start within 30s on your cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).`

Another similar issue has been raised and it was mentioned that the bug has been fixed. However, I still encounter this even with the latest az version.

**To Reproduce**
az aks command invoke --resource-group --name --command 'kubectl get pods -A'

**Expected behavior**
Command should return kubectl command result successfully.

**Environment summary**
az version:
`{
"azure-cli": "2.38.0",
"azure-cli-core": "2.38.0",
"azure-cli-telemetry": "1.0.6",
"extensions": {}
}`

**Comment by yonzhan** [comment]
route to CXP team

**Comment by tdn-revan** [comment]
Do let me know if you need the `--debug` output.

**Comment by tdn-revan** [comment]
Please see below debug output.

`[root@7c78fa9a337d azp]# az aks command invoke -g <<RESOURCE_GROUP>> -n <<AKS_NAME>> -c "kubectl get pod -A" --debug
cli.knack.cli: Command arguments: ['aks', 'command', 'invoke', '-g', '<<RESOURCE_GROUP>>', '-n', '<<AKS_NAME>>', '-c', 'kubectl get pod -A', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f3677b5bdc0>, <function OutputProducer.on_global_arguments at 0x7f3677664700>, <fu
nction CLIQuery.on_global_arguments at 0x7f3677683ca0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'aks': ['azure.cli.command_modules.acs']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acs                       0.116         8        58
cli.azure.cli.core: Total (1)                 0.116         8        58
cli.azure.cli.core: Loaded 8 groups, 58 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : aks command invoke
cli.azure.cli.core: Command table: aks command invoke
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f3674a8b4c0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/jboss/.azure/commands/2022-07-14.03-25-20.aks_command_invoke.32267.log'.
az_command_data_logger: command args: aks command invoke -g {} -n {} -c {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f3674819940>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f367477edc0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f367477eee0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f3677664790>, <function CLIQuery.handle_query_parameter at 0x7f3677683d30>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f367477ee50>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ContainerServiceClient
urllib3.connectionpool: Starting new HTTP connection (1): <<IP_ADDRESS>>
urllib3.connectionpool: http://<<IP_ADDRESS>> "GET /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01&client_id=<<CLIENT_ID>> HTTP/1.1" 200 1798
msrestazure.azure_active_directory: MSI: Retrieving a token from http://<<IP_ADDRESS>>/metadata/identity/oauth2/token, with payload {'resource': 'https://management.core.windows.net/', 'api-version': '2018-02-01', 'client_id': '<<CLIENT_ID>>'}
msrestazure.azure_active_directory: MSI: Token retrieved
cli.azure.cli.core._debug: Using CA bundle file at '/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem'.
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msrestazure.azure_active_directory: MSI: token is found in cache.
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1657855068' -> 1657855068
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<<SUBSCRIPTION_ID>>/resourceGroups/<<RESOURCE_GROUP>>/providers/Microsoft.ContainerService/managedClusters/<<AKS_NAME>>?api-version=2022-04-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '96f6884c-0324-11ed-aa12-0242ac110008'
cli.azure.cli.core.sdk.policies:     'CommandName': 'aks command invoke'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n -c --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.38.0 (RPM) azsdk-python-azure-mgmt-containerservice/19.1.0 Python/3.9.7 (Linux-5.4.0-1085-azure-x86_64-with-glibc2.28)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<<SUBSCRIPTION_ID>>/resourceGroups/<<RESOURCE_GROUP>>/providers/Microsoft.ContainerService/managedClusters/<<AKS_NAME>>?api-version=2022-04-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20220714T032539Z:4746f6f5-4bf7-4c32-b277-c66b1f504a3f'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11997'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '4746f6f5-4bf7-4c32-b277-c66b1f504a3f'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '1c79c74f-65d4-45e2-ad6c-b67983bdf44a'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Server': 'nginx'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 14 Jul 2022 03:25:38 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "id": "/subscriptions/<<SUBSCRIPTION_ID>>/resourcegroups/<<RESOURCE_GROUP>>/providers/Microsoft.ContainerService/managedClusters/<<AKS_NAME>>",
  "location": "southeastasia",
  "name": "<<AKS_NAME>>",
  "tags": {
   <<TAGS>>
  },
  "type": "Microsoft.ContainerService/ManagedClusters",
  "properties": {
   "provisioningState": "Succeeded",
   "powerState": {
    "code": "Running"
   },
   "kubernetesVersion": "1.23",
   "currentKubernetesVersion": "1.23.5",
   "dnsPrefix": "<<AKS_NAME>>",
   "azurePortalFQDN": "<<AZURE_PORTAL_FQDN>>",
   "privateFQDN": "<<PRIVATE_FQDN>>",
   "agentPoolProfiles": [
    {
     "name": "<<NAME>>",
     "count": 1,
     "vmSize": "Standard_F2s_v2",
     "osDiskSizeGB": 128,
     "osDiskType": "Managed",
     "kubeletDiskType": "OS",
     "vnetSubnetID": "<<VNET_SUBNET_ID>>",
     "maxPods": 30,
     "type": "VirtualMachineScaleSets",
     "enableAutoScaling": false,
     "provisioningState": "Succeeded",
     "powerState": {
      "code": "Running"
     },
     "orchestratorVersion": "1.23.5",
     "currentOrchestratorVersion": "1.23.5",
     "enableNodePublicIP": false,
     "mode": "System",
     "enableEncryptionAtHost": false,
     "enableUltraSSD": false,
     "osType": "Linux",
     "osSKU": "Ubuntu",
     "nodeImageVersion": "AKSUbuntu-1804gen2containerd-2022.06.22",
     "upgradeSettings": {},
     "enableFIPS": false
    }
   ],
   "windowsProfile": {
    "adminUsername": "azureuser",
    "enableCSIProxy": true
   },
   "servicePrincipalProfile": {
    "clientId": "msi"
   },
   "addonProfiles": {
    "azureKeyvaultSecretsProvider": {
     "enabled": true,
     "config": {
      "enableSecretRotation": "false",
      "rotationPollInterval": "2m"
     },
     "identity": {
      "resourceId": "<<RESOURCE_ID>>",
      "clientId": "<<CLIENT_ID>>",
      "objectId": "<<OBJECT_ID>>"
     }
    },
    "azurepolicy": {
     "enabled": true,
     "config": null,
     "identity": {
      "resourceId": "<<RESOURCE_ID>>",
      "clientId": "<<CLIENT_ID>>",
      "objectId": "<<OBJECT_ID>>"
     }
    },
    "ingressApplicationGateway": {
     "enabled": true,
     "config": {
      "applicationGatewayId": "<<APPLICATION_GATEWAY_ID>>",
      "effectiveApplicationGatewayId": "<<EFFECTIVE_APPLICATION_GATEWAY_ID>>"
     },
     "identity": {
      "resourceId": "<<RESOURCE_ID>>",
      "clientId": "<<CLIENT_ID>>",
      "objectId": "<<OBJECT_ID>>"
     }
    },
    "omsagent": {
     "enabled": true,
     "config": {
      "logAnalyticsWorkspaceResourceID": "<<LAW_RESOURCE_ID>>"
     },
     "identity": {
      "resourceId": "<<RESOURCE_ID>>",
      "clientId": "<<CLIENT_ID>>",
      "objectId": "<<OBJECT_ID>>"
     }
    }
   },
   "nodeResourceGroup": "<<NODE_RESOURCE_GROUP>>",
   "enableRBAC": true,
   "networkProfile": {
    "networkPlugin": "azure",
    "loadBalancerSku": "Standard",
    "loadBalancerProfile": {
     "managedOutboundIPs": {
      "count": 1
     },
     "effectiveOutboundIPs": [
      {
       "id": "<<ID>>"
      }
     ]
    },
    "serviceCidr": "10.0.0.0/16",
    "dnsServiceIP": "10.0.0.10",
    "dockerBridgeCidr": "172.17.0.1/16",
    "outboundType": "loadBalancer",
    "serviceCidrs": [
     "10.0.0.0/16"
    ],
    "ipFamilies": [
     "IPv4"
    ]
   },
   "aadProfile": {
    "managed": true,
    "adminGroupObjectIDs": null,
    "adminUsers": null,
    "enableAzureRBAC": true,
    "tenantID": "<<TENANT_ID>>"
   },
   "maxAgentPools": 100,
   "privateLinkResources": [
    {
     "id": "<<ID>>",
     "name": "management",
     "type": "Microsoft.ContainerService/managedClusters/privateLinkResources",
     "groupId": "management",
     "requiredMembers": [
      "management"
     ]
    }
   ],
   "apiServerAccessProfile": {
    "enablePrivateCluster": true,
    "privateDNSZone": "system",
    "enablePrivateClusterPublicFQDN": false
   },
   "identityProfile": {
    "kubeletidentity": {
     "resourceId": "<<RESOURCE_ID>>",
      "clientId": "<<CLIENT_ID>>",
      "objectId": "<<OBJECT_ID>>"
    }
   },
   "autoUpgradeProfile": {
    "upgradeChannel": "none"
   },
   "disableLocalAccounts": false,
   "securityProfile": {},
   "storageProfile": {
    "diskCSIDriver": {
     "enabled": true
    },
    "fileCSIDriver": {
     "enabled": true
    },
    "snapshotController": {
     "enabled": true
    }
   },
   "publicNetworkAccess": "Disabled"
  },
  "identity": {
   "type": "SystemAssigned",
   "principalId": "<<PRINCIPAL_ID>>",
   "tenantId": "<<TENANT_ID>>"
  },
  "sku": {
   "name": "Basic",
   "tier": "Free"
  }
 }
urllib3.connectionpool: Starting new HTTP connection (1): <<IP_ADDRESS>>
urllib3.connectionpool: http://<<IP_ADDRESS>> "GET /metadata/identity/oauth2/token?resource=<<RESOURCE>>&api-version=2018-02-01&client_id=<<CLIENT_ID>> HTTP/1.1" 200 1490
msrestazure.azure_active_directory: MSI: Retrieving a token from http://<<IP_ADDRESS>>/metadata/identity/oauth2/token, with payload {'resource': '<<RESOURCE>>', 'api-version': '2018-02-01', 'client_id': '<<CLIENT_ID>>'}
msrestazure.azure_active_directory: MSI: Token retrieved
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('<<SCOPE>>/.default',), kwargs={}
msrestazure.azure_active_directory: MSI: token is found in cache.
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1657855263' -> 1657855263
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<<SUBSCRIPTION_ID>>/resourceGroups/<<RESOURCE_GROUP>>/providers/Microsoft.ContainerService/managedClusters/<<AKS_NAME>>/runCommand?api-version=2022-04-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '1318'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '96f6884c-0324-11ed-aa12-0242ac110008'
cli.azure.cli.core.sdk.policies:     'CommandName': 'aks command invoke'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n -c --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.38.0 (RPM) azsdk-python-azure-mgmt-containerservice/19.1.0 Python/3.9.7 (Linux-5.4.0-1085-azure-x86_64-with-glibc2.28)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"command": "kubectl get pod -A", "context": "", "clusterToken": "<<CLUSTER_TOKEN>>"}
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/<<SUBSCRIPTION_ID>>/resourceGroups/<<RESOURCE_GROUP>>/providers/Microsoft.ContainerService/managedClusters/<<AKS_NAME>>/runCommand?api-version=2022-04-01 HTTP/1.1" 400 368
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '368'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1198'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'ef0bae0d-bebb-4dfa-8a4f-09437ac1c272'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '3f7a0b79-6564-4957-adb0-78df4829630e'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'nginx'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20220714T032610Z:ef0bae0d-bebb-4dfa-8a4f-09437ac1c272'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 14 Jul 2022 03:26:10 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "code": "KubernetesOperationError",
  "message": "Failed to run command due to cluster perf issue, container command-3f7a0b7965644957adb078df4829630e in aks-command namespace did not start within 30s on your cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).",
  "subcode": "PerfError"
 }
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 2694, in aks_runcommand
    command_result_poller = sdk_no_wait(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/util.py", line 697, in sdk_no_wait
    return func(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/containerservice/v2022_04_01/operations/_managed_clusters_operations.py", line 2447, in begin_run_command
    raw_result = self._run_command_initial(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/containerservice/v2022_04_01/operations/_managed_clusters_operations.py", line 2389, in _run_command_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (KubernetesOperationError) Failed to run command due to cluster perf issue, container command-3f7a0b7965644957adb078df4829630e in aks-command namespace did not start within 30s on your cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).
Code: KubernetesOperationError
Message: Failed to run command due to cluster perf issue, container command-3f7a0b7965644957adb078df4829630e in aks-command namespace did not start within 30s on your cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).
cli.azure.cli.core.azclierror: (KubernetesOperationError) Failed to run command due to cluster perf issue, container command-3f7a0b7965644957adb078df4829630e in aks-command namespace did not start within 30s on your cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).
Code: KubernetesOperationError
Message: Failed to run command due to cluster perf issue, container command-3f7a0b7965644957adb078df4829630e in aks-command namespace did not start within 30s on your cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).
az_command_data_logger: (KubernetesOperationError) Failed to run command due to cluster perf issue, container command-3f7a0b7965644957adb078df4829630e in aks-command namespace did not start within 30s on your cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).
Code: KubernetesOperationError
Message: Failed to run command due to cluster perf issue, container command-3f7a0b7965644957adb078df4829630e in aks-command namespace did not start within 30s on your cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f3674a8b700>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 31.888 seconds (init: 0.103, invoke: 31.785)
telemetry.save: Save telemetry record of length 3641 in cache
telemetry.check: Negative: The /home/jboss/.azure/telemetry.txt was modified at 2022-07-14 03:17:30.868841, which in less than 600.000000 s`

**Comment by navba-MSFT** [comment]
@tdn-revan Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@tdn-revan 


Feature | AAD | AAD RBAC | Local Accounts | Outcome
-- | -- | -- | -- | --
noazrbacnoaad | No | No | No | Works
noazrbac | Yes | No | No | Doesn't
localnoaad | Yes | No | Yes | Doesn't

**Comment by tdn-revan** [comment]
> @tdn-revan This issue seems to be related to this issue: [Azure/AKS#2698](https://github.com/Azure/AKS/issues/2698) which is created for `az aks command invoke` doesn't work on AAD-enabled clusters.
> 
> Feature	AAD	AAD RBAC	Local Accounts	Outcome
> noazrbacnoaad	No	No	No	Works
> noazrbac	Yes	No	No	Doesn't
> localnoaad	Yes	No	Yes	Doesn't
> AAD: AAD-enabled feature AAD RBAC: --enable-azure-rbac Local accounts: --disable-local-accounts. Note, for the noazrbacnoaad cluster, the command works, but you need to enable local accounts to connect to cluster (since there's no AAD).

This doesn't solve our issue. Our current requirement requires us to enable both AAD and RBAC. 

Are you implying that this setup is not supported for usage of `az aks command invoke`? If so, please share use the link to the documentation.

**Comment by navba-MSFT** [comment]
@tdn-revan Thanks for getting back. Could you please let me know what kind of internet access does your subnet have ?

**Comment by navba-MSFT** [comment]
@tdn-revan Adding on to the above comment, How the “command invoke” works is by:
 1) creating a pod in k8s; 
 2) exec to the pod. It will be mostly the same as to troubleshoot those, with the exception that the AKS does the pod creation / deletion.

Please:
1.	Check if the pod issued is up and running; --->  This needs to be investigated to check why the pod created is not running;
2.	Check if we have problem exec to arbitrary pods with `kubectl exec`. ---> We need to isolate on the tunnel connectivity / exec troubleshooting path if exec fails for pods.

Hope this helps.

PS: Apologies for [this](https://github.com/Azure/azure-cli/issues/23203#issuecomment-1185186428) comment. I was able to run the command invoke on AKS private cluster which has AAD RBAC enabled.

**Comment by navba-MSFT** [comment]
@tdn-revan I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you have any questions on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@tdn-revan The action is currently pending on you to test the above suggestion. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
