### ISSUE TITLE
[Docs] The long summary field for the `az aks enable-addons` command is poorly spaced and hard to read. 

### ISSUE THREAD

**Issue by miguelarcilla** [Azure/azure-cli#23201]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az aks enable-addons

**Describe the bug**
The long summary field for the `az aks enable-addons` command is poorly spaced and hard to read. 

**To Reproduce**
Navigate to https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest and review the long summary of the az aks enable-addons command.

**Expected behavior**
More readable description of available add-ons.

**Environment summary**

**Additional context**

**Comment by RakeshMohanMSFT** [comment]
@miguelarcilla Thank you for reaching out, we are looking into it.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@miguelarcilla Unfortunately these are auto generated documents, there are very limited options we have to control the way these document descriptions are rendered.

**Comment by miguelarcilla** [comment]
Thanks @RakeshMohanMSFT understood on the limitation. I opted to create an issue rather than create a pull request because I myself did not understand how to write it to be formatted properly.

If there is a larger issue for similar cases this can be linked to, I would request it be linked. Otherwise I think it can be closed.

**Comment by RakeshMohanMSFT** [comment]
@miguelarcilla for now i will go ahead close the issue, but if we see multiple issues for the same i will link this to those issues.
