### ISSUE TITLE
Please bump argcomplete dependency to 2.0.0 or higher

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-cli#23222]
The `azure-cli-core` component still depends on `argcomplete ~= 1.8` while 2.0.0 has been available since Jan 3, 2022.

Could you bump the version for `argcomplete` so that Linux distributions are not stuck in older versions of the dependency?

**Comment by yonzhan** [comment]
bump argcomplete

**Comment by jiasli** [comment]
`argcomplete` will be bumped by https://github.com/Azure/azure-cli/pull/22991

**Comment by Nydhal** [comment]
#22991 is closed :/

**Comment by bebound** [comment]
It will bump to 2.0.0 once https://github.com/Azure/azure-cli/pull/24752 is merged.

**Comment by jiasli** [comment]
I saw @major has deleted the repo/branch, so https://github.com/Azure/azure-cli/pull/22991 can't be reopened. Let's bump `argcomplete` for now, regardless of https://github.com/Azure/azure-cli/pull/24752.

**Comment by major** [comment]
Thanks, @jiasli. I think I recreated the fork a while back. Oops. 🤭

**Comment by jiasli** [comment]
I still can't access https://github.com/major/azure-cli. Do you mind recreating that branch so that we can reopen https://github.com/Azure/azure-cli/pull/22991 (and giving you credit for it)?

**Comment by jiasli** [comment]
https://github.com/Azure/azure-cli/pull/24903 has been merged.
