### ISSUE TITLE
Kubenetes Cluster setup time-out

### ISSUE THREAD

**Issue by QuantumAtom** [Azure/azure-cli#23226]
## Describe the bug
I was practicing setting up a Kubernetes Cluster for AZ-104 and it timed out after 1.5 hours(?). I did it again a few days later and it still timed out. Just letting you know. Thank you.

**Command Name**
`az aks create`

**Errors:**
```
(InternalOperationError) Operation timeout, please retry.
Code: InternalOperationError
Message: Operation timeout, please retry.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --enable-addons {} --generate-ssh-keys`

## Environment Summary
```
Linux-5.4.0-1086-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.5
Installer: DEB

azure-cli 2.38.0

Extensions:
ai-examples 0.2.5
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by navba-MSFT** [comment]
@QuantumAtom Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@QuantumAtom Thanks for reaching out to us and sharing this feedback. To isolate this issue, could you please run the command without the  `--enable-addons` switch and check if that helps ? So once the cluster is created, you can enable the add-on later as well. This will help us to isolate the issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@QuantumAtom I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you have any update on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@QuantumAtom The action is currently pending on you to isolate the issue by running the command without the --enable-addons switch. Please feel free to reopen this issue once you have these details. We would be happy to help.
