### ISSUE TITLE
BUG STILL EXISTS - module 'time' has no attribute 'clock' in v2.38.0

### ISSUE THREAD

**Issue by erniedavisAA** [Azure/azure-cli#23220]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
after first running login successfully, any subsequent command produces the error "module 'time' has no attribute 'clock'" in v2.38.0

File "/venv/lib/python3.9/site-packages/azure/cli/core/_session.py", line 46, in load
if st.st_mtime + max_age < time.clock():
AttributeError: module 'time' has no attribute 'clock'

for example: after running login successfully, running 'account list' will yield the above error.

I have opened the file in the image: /venv/lib/python3.9/site-packages/azure/cli/core/_session.py

and have verified that "< time.clock()" still exists in the code

I have monkey patched the line of code to read:
if st.st_mtime + max_age < time.time()

and it now produces the expected results

login
account list

**Describe the bug**

time.clock() for python has been long depreciated, yet a reference to the command remains in the azure-cli image

**To Reproduce**

az_cli(f"login -u {azcliuser} -p {azclipass}")
az_cli(f"account list")

**Expected behavior**

a list of accounts for the user logging in

**Environment summary**
ubuntu20.04
python3.9
azure-cli 2.38.0

running in kuberbentes as a container image

**Additional context**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/19504#issuecomment-915869524

`AttributeError: module 'time' has no attribute 'clock'` has long been fixed by `azure-cli-2.0.77` (https://github.com/Azure/azure-cli/pull/10777). The current code is:

https://github.com/Azure/azure-cli/blob/fa307d6fdfea663e64977c4bbf8a3dbee5d97753/src/azure-cli-core/azure/cli/core/_session.py#L35

I highly doubt your `az_cli` is not calling the latest Azure CLI

**Comment by erniedavisAA** [comment]
Thank you... I verified that the requirements.txt file was not locked on a previous version... moved the presence of the azure-cli to the top of the requirements file, and it moved the installed version from 2.0.67 to 2.38.0.

Thank you for pointing me towards the incorrect version.

this can be closed as I believe a dependency in the installation order was driving the installation of the incorrect version.
