### ISSUE TITLE
Measure the load performance of individual command model

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#2323]
Moving forward, more and more command modules will be introduced. The performance of `az` relies on the performance of individual command modules as well. Especially in the case of loading commands and parameters. If one command module regresses the performance, the overall performance will be bad.

We don't have a mechanism to measure individual command module's performance in place. We need one for the 3rd party contributors to validate their performance as well as serves as gatekeeper for az cli.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
