### ISSUE TITLE
`az security automation-action-event-hub create` does not create anything

### ISSUE THREAD

**Issue by liranms** [Azure/azure-cli#23235]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az security automation-action-event-hub create

**Describe the bug**
This command does nothing, it simply prints a json, instead of actually calling the client and sending it to azure API
Looking at the code all the automation-action-* does nothing, somewhat embarrassing 

**To Reproduce**
az security automation-action-event-hub create --event-hub-resource-id <..> --connection-string <..>

**Expected behavior**
Create a the automation

**Environment summary**
azure-cli                         2.38.0

core                              2.38.0
telemetry                          1.0.6

Extensions:
kusto                              0.5.0
portal                             0.1.2

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/liran/.azure/cliextensions'

Python (Linux) 3.10.5 (main, Jul  1 2022, 04:14:40) [GCC 9.4.0]

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@liranms Could you please let us know scenario under which you are trying to use this command?

**Comment by liranms** [comment]
the most straightforward scenario you can think of - create a continuous export to eventhub, as your documentation describes here:
https://docs.microsoft.com/en-us/azure/defender-for-cloud/continuous-export?tabs=rest-api

**Comment by SaurabhSharma-MSFT** [comment]
@liranms Regarding [az security automation-action-event-hub](https://docs.microsoft.com/en-us/cli/azure/security/automation-action-event-hub?view=azure-cli-latest), it’s a utility command that allows to create automation action PS Object (see more detail about automation action [here](https://docs.microsoft.com/en-us/rest/api/securitycenter/automations/create-or-update?tabs=HTTP#automation) – look for properties.actions), then this object can be used later on the main command [az security automation create_or_update](https://docs.microsoft.com/en-us/cli/azure/security/automation?view=azure-cli-latest#az-security-automation-create-or-update) as parameter for ‘--actions’.

Regarding setting continuous export, beside using Continuous Export blade, you can use one of the following methods:
1.	Azure CLI: [az security automation create_or_update](https://docs.microsoft.com/en-us/cli/azure/security/automation?view=azure-cli-latest#az-security-automation-create-or-update)
2.	Azure Powershell: [New-AzSecurityAutomation](https://docs.microsoft.com/en-us/powershell/module/az.security/new-azsecurityautomation?view=azps-8.1.0)
3.	[Automation ARM API](https://docs.microsoft.com/en-us/rest/api/securitycenter/automations/create-or-update?tabs=HTTP)

**Comment by SaurabhSharma-MSFT** [comment]
@liranms Please let me know if you have any questions else we will proceed with the closure of this issue.

**Comment by SaurabhSharma-MSFT** [comment]
@liranms We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
