### ISSUE TITLE
The examples and 'Create a policy set definition.' and 'Create a policy set definition with parameters.' are swapped.

### ISSUE THREAD

**Issue by Wind010** [Azure/azure-cli#23246]
The documentation examples and 'Create a policy set definition.' and 'Create a policy set definition with parameters.' are swapped.

Should be:

Create a policy set definition with parameters.
```sh
az policy set-definition create -n readOnlyStorage \
    --definitions '[ { \"policyDefinitionId\": \"/subscriptions/mySubId/providers/ \
        Microsoft.Authorization/policyDefinitions/storagePolicy\" } ]'
```

Create a policy set definition with parameters.
```sh
az policy set-definition create -n readOnlyStorage \
    --definitions "[ { \"policyDefinitionId\": \"/subscriptions/mySubId/providers/ \
        Microsoft.Authorization/policyDefinitions/storagePolicy\", \"parameters\": \
            { \"storageSku\": { \"value\": \"[parameters(\\"requiredSku\\")]\" } } }]" \
    --params "{ \"requiredSku\": { \"type\": \"String\" } }"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe29c90-ab37-174c-3365-d33044447272
* Version Independent ID: 3118d6a2-bb53-a881-0017-0313a15c9ef1
* Content: [az policy set-definition](https://docs.microsoft.com/en-us/cli/azure/policy/set-definition?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/policy/set-definition.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/policy/set-definition.yml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
ARM

**Comment by RakeshMohanMSFT** [comment]
@Wind010 Thank you for reaching out, we are looking into it.
