### ISSUE TITLE
Error 13 ‘az network’ Permission Denied (conn.rdp)

### ISSUE THREAD

**Issue by FalkoWienBBT** [Azure/azure-cli#23242]
## Describe the bug

**Command Name**
`az network bastion rdp`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
[Errno 13] Permission denied: 'conn.rdp'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/network/custom.py", line 8487, in rdp_bastion_host
PermissionError: [Errno 13] Permission denied: 'conn.rdp'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
Please see https://petri.com/azure-bastion-native-client-support/#Error_13_8216az_network8217_Permission_Denied_connrdp 

- _Put any pre-requisite steps here..._
- `az network bastion rdp --name {} --resource-group {} --target-resource-id {} --only-show-errors`

## Expected Behavior
The native RDP client opens and connects to the VM. (as it does when the session runs as an administrator)

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.38.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@FalkoWienBBT Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@FalkoWienBBT Could you please confirm if you ran this from the Cloud Shell ? If Yes, please try to run the same command using the PS with Azure CLI and let us know if you see the same issue.

If you see the same issue again, please share the --debug output here. Awaiting your reply.

**Comment by FalkoWienBBT** [comment]
It’s also not working in the Cloud Shell.
That’s the command I used:
az network bastion rdp --name …-AZ-BASTION --resource-group RG-…-NETWORK-FRA --target-resource-id /subscriptions/…/resourceGroups/RG-…-VM…01-FRA/providers/Microsoft.Compute/virtualMachines/… --debug

Cloud Shell output:
cli.knack.cli: Command arguments: ['network', 'bastion', 'rdp', '--name', …-AZ-BASTION', '--resource-group', 'RG-…-NETWORK-FRA', '--target-resource-id', '/subscriptions/…/resourceGroups/RG-…-…-FRA/providers/Microsoft.Compute/virtualMachines/…, '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7ff0299e7be0>, <function OutputProducer.on_global_arguments at 0x7ff0297484c0>, <function CLIQuery.on_global_arguments at 0x7ff0297756c0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.natgateway', 'azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: natgateway                0.002         3         6
cli.azure.cli.core: network                   0.155       144       668
cli.azure.cli.core: privatedns                0.004        14        66
cli.azure.cli.core: Total (3)                 0.160       161       740
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.086         1         1  /opt/az/lib/python3.10/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.086         1         1  
cli.azure.cli.core: Loaded 160 groups, 741 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : network bastion rdp
cli.azure.cli.core: Command table: network bastion rdp
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7ff028e63400>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home//.azure/commands/2022-07-29.09-37-03.network_bastion_rdp.161.log'.
az_command_data_logger: command args: network bastion rdp --name {} --resource-group {} --target-resource-id {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7ff028c74e50>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7ff028d212d0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7ff028d213f0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7ff029748550>, <function CLIQuery.handle_query_parameter at 0x7ff029775750>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7ff028d21360>]
Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 8457, in rdp_bastion_host
    from ._process_helper import launch_and_wait
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/_process_helper.py", line 9, in <module>
    from ctypes import WinDLL, c_int, c_size_t, Structure, WinError, sizeof, pointer
ImportError: cannot import name 'WinDLL' from 'ctypes' (/opt/az/lib/python3.10/ctypes/__init__.py)

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: cannot import name 'WinDLL' from 'ctypes' (/opt/az/lib/python3.10/ctypes/__init__.py)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 8457, in rdp_bastion_host
    from ._process_helper import launch_and_wait
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/_process_helper.py", line 9, in <module>
    from ctypes import WinDLL, c_int, c_size_t, Structure, WinError, sizeof, pointer
ImportError: cannot import name 'WinDLL' from 'ctypes' (/opt/az/lib/python3.10/ctypes/__init__.py)
az_command_data_logger: cannot import name 'WinDLL' from 'ctypes' (/opt/az/lib/python3.10/ctypes/__init__.py)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 8457, in rdp_bastion_host
    from ._process_helper import launch_and_wait
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/_process_helper.py", line 9, in <module>
    from ctypes import WinDLL, c_int, c_size_t, Structure, WinError, sizeof, pointer
ImportError: cannot import name 'WinDLL' from 'ctypes' (/opt/az/lib/python3.10/ctypes/__init__.py)

PS with Azure CLI output:
  
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x017EBDA8>, <function 
OutputProducer.on_global_arguments at 0x018AC6E8>, <function CLIQuery.on_global_arguments at 0x018BE340>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.natgateway', 'azure.cli.command_modules.network', 
'azure.cli.command_modules.privatedns']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: natgateway                0.004         3         6
DEBUG: cli.azure.cli.core: network                   0.184       144       668
DEBUG: cli.azure.cli.core: privatedns                0.004        14        66
DEBUG: cli.azure.cli.core: Total (3)                 0.192       161       740
DEBUG: cli.azure.cli.core: Loaded 159 groups, 740 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : network bastion rdp
DEBUG: cli.azure.cli.core: Command table: network bastion rdp
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03CD3028>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 
'C:\Users\\.azure\commands\2022-07-29.11-36-44.network_bastion_rdp.10868.log'.
INFO: az_command_data_logger: command args: network bastion rdp --name {} --resource-group {} --target-resource-id {} --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter 
at 0x03D09C88>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03D09D60>, 
<function register_cache_arguments.<locals>.add_cache_arguments at 0x03D1C2F8>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x018AC730>, <function 
CLIQuery.handle_query_parameter at 0x018BE388>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03D1C2B0>]
WARNING: Command group 'network bastion' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\\\.azure\\msal_token_cache.bin', encrypt=True
DEBUG: cli.azure.cli.core.auth.binary_cache: load: C:\Users\\.azure\msal_http_cache.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 
'https://login.microsoftonline.com//oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': 
['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 
'https://login.microsoftonline.com//discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 
'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 
'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 
'https://login.microsoftonline.com//v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 
'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 
'https://login.microsoftonline.com//oauth2/v2.0/authorize', 'device_authorization_endpoint': 
'https://login.microsoftonline.com//oauth2/v2.0/devicecode', 'http_logout_supported': True, 
'frontchannel_logout_supported': True, 'end_session_endpoint': 
'https://login.microsoftonline.com//oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 
'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 
'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 
'https://login.microsoftonline.com//kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 
'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: 67988143-5364-4833-8978-8d9a567df08c
DEBUG: cli.azure.cli.command_modules.network.custom: Response ….
-F7D5r0KYtBJBPZ1uPPyCN_5_qE-RByJ6lIP1iki0hVJMTum-4r4kHAHRrvNwzvYEf0qWmmV
t_6JY1xkgo54CS2zEBLMcBQWj0gt79FfivrEJD83ENhCbwaGyB8aQQbet4wGQe57L-aZxhEfrw
DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=NetworkManagementClient
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 
'https://login.microsoftonline.com//oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': 
['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 
'https://login.microsoftonline.com//discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 
'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 
'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 
'https://login.microsoftonline.com//v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 
'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 
'https://login.microsoftonline.com//oauth2/v2.0/authorize', 'device_authorization_endpoint': 
'https://login.microsoftonline.com//oauth2/v2.0/devicecode', 'http_logout_supported': True, 
'frontchannel_logout_supported': True, 'end_session_endpoint': 
'https://login.microsoftonline.com//oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 
'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 
'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 
'https://login.microsoftonline.com//kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 
'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: 6fca8944-62f1-45b5-bc11-a90c5fff7d31
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions//resourceGroups/
RG--NETWORK-FRA/providers/Microsoft.Network/bastionHosts/-AZ-BASTION?api-version=2021-08-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'f5735-0f21-11ed-a992-00155d103602'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'network bastion rdp'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --resource-group --target-resource-id --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.38.0 (MSI) azsdk-python-azure-mgmt-network/20.0.0 Python/3.10.5 
(Windows-10-10.0.22000-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions//resourceGroups/RG--N
ETWORK-FRA/providers/Microsoft.Network/bastionHosts/-AZ-BASTION?api-version=2021-08-01 HTTP/1.1" 200 None
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 200
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'ETag': 'W/"d07a5a1a-f6c7-42b9-a786-b7444a5f150d"'
DEBUG: cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'd3f161f3-1d85-4137-b789-b0e6b5a7910e'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '4cb63d5a-8f48-444a-a6e2-377b7585ea79'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-arm-service-request-id': '9c0b6fd3-6ffa-428e-90a2-f9941d00377f'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'FRANCESOUTH:20220729T093645Z:4cb63d5a-8f48-444a-a6e2-377b7585ea79'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 29 Jul 2022 09:36:44 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {
  "name": "-AZ-BASTION",
  "id": "/subscriptions//resourceGroups/RG--NETWORK-FRA/providers/Microsoft.Network/bastionHosts/
-AZ-BASTION",
  "etag": "W/\"d07a5a1a6-d\"",
  "type": "Microsoft.Network/bastionHosts",
  "location": "germanywestcentral",
  "properties": {
    "provisioningState": "Succeeded",
    "dnsName": "bst-2d9b5167-8e90-.bastion.azure.com",
    "scaleUnits": 2,
    "enableTunneling": true,
    "disableCopyPaste": false,
    "enableKerberos": true,
    "ipConfigurations": [
      {
        "name": "IpConf",
        "id": "/subscriptions//resourceGroups/RG--NETWORK-FRA/providers/Microsoft.Network/bastionHosts/BL
UETEAM-AZ-BASTION/bastionHostIpConfigurations/IpConf",
        "etag": "W/\" -b7444a5f150d\"",
        "type": "Microsoft.Network/bastionHosts/bastionHostIpConfigurations",
        "properties": {
          "provisioningState": "Succeeded",
          "privateIPAllocationMethod": "Dynamic",
          "publicIPAddress": {
            "id": "/subscriptions//resourceGroups/RG--NETWORK-FRA/providers/Microsoft.Network/publicIPAdd
resses/PBIP--AZ-BASTION"
          },
          "subnet": {
            "id": "/subscriptions//resourceGroups/RG--NETWORK-FRA/providers/Microsoft.Network/virtualNetw
orks/VNET--FRA/subnets/AzureBastionSubnet"
          }
        }
      }
    ]
  },
  "sku": {
    "name": "Standard"
  }
}
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): bst-2d9b5167-.bastion.azure.com:443
DEBUG: urllib3.connectionpool: https://bst- -b966b3c21903.bastion.azure.com:443 "GET /api/rdpfile?resourceId=/subscriptions/5c8
/resourceGroups/RG--VM01-FRA/providers/Microsoft.Compute/virtualMachines/dsVM01&format=rdp HTTP/1.1" 200 
None
DEBUG: cli.azure.cli.command_modules.network.custom: Platform architecture: ('32bit', 'WindowsPE')
DEBUG: cli.azure.cli.command_modules.network.custom: System Root: C:\Windows
DEBUG: cli.azure.cli.command_modules.network.custom: Attempting to run rdp from path C:\Windows\System32\mstsc.exe
DEBUG: cli.azure.cli.command_modules.network._process_helper: Waiting for process 8236
ERROR: cli.azure.cli.command_modules.network._process_helper: Could not run '['C:\\Windows\\System32\\mstsc.exe', 'C:\\Windows\\system32/conn.rdp']' 
command. Exception: [WinError 234] Es sind mehr Daten verfügbar.
DEBUG: cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x03D09148>, <function 
_x509_from_base64_to_hex_transform at 0x03D09190>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnFilterResult []
DEBUG: cli.knack.cli: Event: Cli.SuccessfulExecute []
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03CD3148>]
INFO: az_command_data_logger: exit code: 0
INFO: cli.__main__: Command ran in 2.709 seconds (init: 0.335, invoke: 2.374)
INFO: telemetry.save: Save telemetry record of length 2971 in cache
WARNING: telemetry.check: Negative: The C:\Users\\.azure\telemetry.txt was modified at 2022-07-29 11:33:58.220462, which in less than 
600.000000 s 

Cause:
The command tries to create / modify the “conn.rdp” file at the location where the script / command has been executed from. The user must have write / modify permissions on the file.
In my case I only have read access to the file. If I change ACL to modify on the file, it works.
Solution:
I suggest that the “conn.rdp” file has been stored somewhere I the users Temp – or profile folders per default.

**Comment by navba-MSFT** [comment]
@FalkoWienBBT I wasn't able to reproduce this issue at my end. Could you please delete the existing conn.rdp file and then launch the **cmd** prompt using Admin mode ( Run As Administrator) and then navigate to the folder where you need the conn.rdp file to be created and then run the below command again. 

>az network bastion rdp --name MyBastionHost --resource-group MyResourceGroup --target-resource-id vmResourceId

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@FalkoWienBBT I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you are still facing the same issue after following the above suggestions. Awaiting your reply.

**Comment by rmc515** [comment]
@navba-MSFT I am getting the same error when I attempt to connect to RDP through Bastion command line. I don't see conn.rdp anywhere to delete. What else can I try?

**Comment by navba-MSFT** [comment]
@rmc515 Thanks for the update.

**Comment by navba-MSFT** [comment]
@FalkoWienBBT The action is currently pending on you to try the suggestion provided [here](https://github.com/Azure/azure-cli/issues/23242#issuecomment-1202012035). We will now proceed with archival of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by jiasli** [comment]
`ImportError: cannot import name 'WinDLL' from 'ctypes'` is tracked by #23143
