### ISSUE TITLE
Unable to add owner on AD group using AZ CLI: Invalid URL format specified in payload

### ISSUE THREAD

**Issue by sanjeev40084** [Azure/azure-cli#23245]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

`az ad group owner add --group xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --owner-object-id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`

**Describe the bug**

I am trying to add new owner of existing AD group where i am owner of, however i keep getting '_Invalid URL format specified in payload_.' error message. I tried using both 'objectId' and 'displayName' for group parameter but both gave me same error message. My az version info:

**To Reproduce**

- az login
- (find AD group where you are owner of in Azure Portal and find user object Id whom you want to add as owner)
- az ad group owner add --group [group-object-id] --owner-object-id [user-object-id]

**Expected behavior**

User [user-object-id] should have been added as owner of group [group-object-id] successfully.

**Environment summary**

```
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

**Additional context**

i assumed it might be my credential which might not have permission to add member in the group so i did try adding the user manually and it worked. Also i ran the az command to list out owner of the ad group and i was able to successfully see the list of existing owner of the group. This same issue happens when i try to add owner of  one of the app registration that is owned by me. 

![az-cli-error](https://user-images.githubusercontent.com/3292092/179550309-36658b08-ce7e-4fb7-b5ab-dbe0e32a767f.png)

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by RakeshMohanMSFT** [comment]
@sanjeev40084 We are unable to reproduce the issue from our end. Can you please share --debug trace with us for further troubleshooting?

**Comment by sanjeev40084** [comment]
@RakeshMohanMSFT  sure. Do I just concatenate --debug at the end to get the trace log??

**Comment by RakeshMohanMSFT** [comment]
@sanjeev40084 Yes, ensure to sanitize sensitive information while sharing the logs

**Comment by jiasli** [comment]
I am not able to reproduce either:

```
> az ad group owner add -g 796cd246-84fa-468d-a8ef-97b80b0943da --owner-object-id 90c3d926-9c03-4d90-86f4-12866a6da212 --debug
...
cli.azure.cli.core.util: Request URL: 'https://graph.microsoft.com/v1.0/groups/796cd246-84fa-468d-a8ef-97b80b0943da/owners/$ref'
cli.azure.cli.core.util: Request method: 'POST'
cli.azure.cli.core.util: Request headers:
cli.azure.cli.core.util:     'User-Agent': 'python/3.10.5 (Windows-10-10.0.22000-SP0) AZURECLI/2.38.0 (MSI)'
cli.azure.cli.core.util:     'Accept-Encoding': 'gzip, deflate'
cli.azure.cli.core.util:     'Accept': '*/*'
cli.azure.cli.core.util:     'Connection': 'keep-alive'
cli.azure.cli.core.util:     'x-ms-client-request-id': 'e1ad7c51-1c65-4952-b148-24f6b7a6c811'
cli.azure.cli.core.util:     'Content-Type': 'application/json'
cli.azure.cli.core.util:     'CommandName': 'ad group owner add'
cli.azure.cli.core.util:     'ParameterSetName': '-g --owner-object-id --debug'
cli.azure.cli.core.util:     'Authorization': 'Bearer eyJ0eXAiOiJKV...'
cli.azure.cli.core.util:     'Content-Length': '103'
cli.azure.cli.core.util: Request body:
cli.azure.cli.core.util: {"@odata.id": "https://graph.microsoft.com/v1.0/directoryObjects/90c3d926-9c03-4d90-86f4-12866a6da212"}
...
cli.azure.cli.core.util: Response status: 204
...

> az ad group owner list -g 796cd246-84fa-468d-a8ef-97b80b0943da
[
  {
    "@odata.type": "#microsoft.graph.user",
    "businessPhones": [],
    "displayName": "admin07",
    "givenName": null,
    "id": "90c3d926-9c03-4d90-86f4-12866a6da212",
    "jobTitle": null,
    "mail": null,
    "mobilePhone": null,
    "officeLocation": null,
    "preferredLanguage": null,
    "surname": null,
    "userPrincipalName": "admin07@AzureSDKTeam.onmicrosoft.com"
  }
]
```

The `--debug` log will be very helpful.

**Comment by jiasli** [comment]
This is very weird. In my test, `b85b844e-8d36-4a88-b3b1-51a07e0ccd92` was correctly translated to `https://graph.microsoft.com/v1.0/directoryObjects/b85b844e-8d36-4a88-b3b1-51a07e0ccd92`:

```
> az ad group owner add -g 796cd246-84fa-468d-a8ef-97b80b0943da --owner-object-id b85b844e-8d36-4a88-b3b1-51a07e0ccd92 --debug
...
cli.azure.cli.core.util: Request URL: 'https://graph.microsoft.com/v1.0/groups/796cd246-84fa-468d-a8ef-97b80b0943da/owners/$ref'
cli.azure.cli.core.util: Request method: 'POST'
...
cli.azure.cli.core.util: Request body:
cli.azure.cli.core.util: {"@odata.id": "https://graph.microsoft.com/v1.0/directoryObjects/b85b844e-8d36-4a88-b3b1-51a07e0ccd92"}
```

But your debug log shows `b85b844e-8d36-4a88-b3b1-51a07e0ccd92` was used in this API as-is:

```
cli.azure.cli.core.util: Request body:
cli.azure.cli.core.util: {"@odata.id": "b85b844e-8d36-4a88-b3b1-51a07e0ccd92"}
```

which indicates `is_guid` returned `False`:

https://github.com/Azure/azure-cli/blob/33cbd01f75c7d4c3814de5a1cbf6f42de7890467/src/azure-cli/azure/cli/command_modules/role/_msgrpah/_graph_client.py#L388-L395

Could you run this command and share the output in order to verify that?

```
> & "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "from azure.cli.core.util import is_guid; print(is_guid('b85b844e-8d36-4a88-b3b1-51a07e0ccd92'))"
True
```

I am not sure if you are hitting https://github.com/Azure/azure-cli/issues/20990.

**Comment by sanjeev40084** [comment]
@jiasli the output is true. Also i installed az cli just couple days ago so don't think it is related to other issue. 
```
& "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "from azure.cli.core.util import is_guid; print(is_guid('b85b844e-8d36-4a88-b3b1-51a07e0ccd92'))" 
True
```
