### ISSUE TITLE
Tenanted passthrough will be disabled on 2022-08-02

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#23255]
Starting from 2022-08-02, users from other organizations or Microsoft account (consumers) will not be able to sign in with Azure CLI to a tenant where they aren't invited as a guest.

For example, if your user account is not a guest in Microsoft tenant, signing in to Microsoft tenant will fail:

```
az login --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47
```

You will see following error message in the web browser:

> AADSTS50020: User account 'xxx@xxx.onmicrosoft.com' from identity provider 'https://sts.windows.net/xxx' does not exist in tenant 'Microsoft' and cannot access the application '04b07795-8ddb-461a-bbee-02f9e1bf7b46'(Microsoft Azure CLI) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

In order to log in to a tenant, make sure the user is either

1. a member of that tenant
2. a guest invited to that tenant

**Comment by yonzhan** [comment]
disable Tenanted passthrough

**Comment by jiasli** [comment]
Now you will receive an error while logging in to a tenant where you are not a guess there. For example:

```
az login --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47
```

![image](https://user-images.githubusercontent.com/4003950/185023123-3214792a-9079-41f2-85fe-8ad0149eef38.png)
