### ISSUE TITLE
[App Service] [Discussion] Shorten appservice command group name to just "app"

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2325]
I'd love to discuss whether we could shorten the `appservice` command group to just `app` (or equivalent)  in order to improve the ergonomics around frequent use. The use of `az` instead of "Azure" feels so fluid to type (as does nsg, vm, nic, acs, acr, etc.), and I wonder whether we couldn't apply a similar naming abbreviation "principal" for App Service, in order to improve the efficiency of using its command on a regular basis, while balancing intuitiveness/discoverability.

Personally, I don't find the use of &lt;TAB&gt; for auto-completing long command names to be very ergonomic, which is why I've thrown out the possibility of shortening names vs. relying on tab completion. Others may find this acceptable, so I'm just providing one input, which may not be that useful. Apologies if this conversation has already happened. I just wanted to throw it out there while the App Service module was still in beta, and could potentially make a breaking change like this.

**UPDATE:** As discussed below, an alternative solution to this could be to "flatten" out the `appservice` command group and provide top-level support for web apps itself (e.g. `az webapp`). I personally prefer this solution, and would support it over the above previous proposal

**Comment by stewartadam** [comment]
imho `az as` or `az appsv` would be better to avoid confusion with Azure AD apps (`az ad app`).

**Comment by yugangw-msft** [comment]
@lostintangent, @stewartadam 
Chatted with AppService team on this. We plan to flatten out the command structures. `appservice plan` becomes `appservice-plan` and `appservice web` becomes `webapp`.
The `webapp` was chosen over general terms of like `app`, mainly for easier discovering, considering we have close to 40 top categories now. And the name is still short enough.

**Comment by lostintangent** [comment]
What about "web" instead of "webapp"? Does the app suffix actually add anything here? I'm cool with "appservice-plan", but I wonder whether we couldn't just repurpose the "appservice" group to be specific to the plan. That way, "appservice create" was the equivalent of "appservice plan create".

I'd be happy either way, I'm just thinking out loud.

**Comment by yugangw-msft** [comment]
`web` was proposed but deemed too general to be in the CLI, and also inconsistent with terms used in existing docs.
`appservice` is a general term which would mean each individual offering like `mobile`, `webapp`, 'logic', etc. Adding `plan` to be explicit is reasonable.  
I care less on the `plan` now. Since on `webapp create` we will create/reuse a plan automatically, and the `plan` will mostly become transparent.

**Comment by lostintangent** [comment]
Sounds good!

**Comment by stewartadam** [comment]
The plan part makes sense, but what's the plan to unify branding around the [other app types](https://docs.microsoft.com/en-us/azure/app-service/app-service-value-prop-what-is#app-types-in-app-service) (e.g. API, logic, mobile) then? What will happen to existing scripts that make use of the 'appservice' namespace?

**Comment by tjprescott** [comment]
@stewartadam raises a great point. I believe that API and mobile apps are really just webapps under the hood, but logic apps aren't. Are we going to have "logicapp" and "webapp" as top level resources (my vote is an emphatic no).

You could also have a structure with "app" as the root and place "service-plan" as a subgroup inside, while the commands to create and manage apps would be at this basic "app" level. This is a bit of an inversion from the norm, but I think it could be justified based on (1) the fact that the appservice team wants the concept of "app service plans" to be essentially transparent, and (2) the fact that we can (and it has been recommended) that we create the service plan when we create the webapp if it doesn't already exist.

**Comment by yugangw-msft** [comment]
(The discussion with appservice group is still on-going, and I will incorporate all feedback here)
The plan is to get all app types to be on-top like `az logicapp`. There are business needs and market effort to align with, hence followed the requirements of visibility and discoverability to their service users. Nesting under a general term is not favorable option to service teams, even though it makes logic sense to CLI team. Also very few users I know of will use across all commands in CLI, rather just limited to couple of services' command-set, and they do want to find those commands quickly, and mostly by just following the market term to spot a category in CLI.

**Comment by tjprescott** [comment]
FTR, webapplinux is a terrible name.

**Comment by lostintangent** [comment]
Yeah I really don't like "webapplinux" either :) Once web apps on Linux GAs, I was actually hoping we could make Linux the default, so that users didn't even need to know the difference of platform unless they wanted Windows.

**Comment by yugangw-msft** [comment]
This still stays at the level of an `idea` circulated internally and there is no plan on board to really do it at this point

**Comment by stewartadam** [comment]
Note that the portal also further distinguishes between bot, API, web, etc apps as well. A decision to use top-level namespaces will need to be clear on how to brand these types of apps (if it is going to at all), and if so then any new possible new classes of apps going forward.

imho, a single top-level group like @tjprescott described is best and provides the most flexibility going onward. Understood that there are other pressures here for the naming, but my 2 cents: this is a CLI tool, and should be treated as such. Do what's makes the most sense for CLI tooling.

**Comment by yugangw-msft** [comment]
//cc: @SyntaxC4, @davidebbo, @Ahmedelnably

**Comment by stewartadam** [comment]
Wanted to check in to see if there have been any updates here -- happy to discuss further (both here or privately) if you'd like.

**Comment by yugangw-msft** [comment]
We went with `webapp`
