### ISSUE TITLE
`urn:ietf:wg:oauth:2.0:oob` will be removed from Azure CLI's Reply URLs on 2022-08-02

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#23256]
The deprecated Reply URL `urn:ietf:wg:oauth:2.0:oob` will be removed from first party application Azure CLI (`04b07795-8ddb-461a-bbee-02f9e1bf7b46`)'s Reply URLs on 2022-08-02.

After that, valid Reply URLs will be
- `http://localhost`
- `https://login.microsoftonline.com/common/oauth2/nativeclient`

## ⚠️ Warning

**Azure CLI's client ID `04b07795-8ddb-461a-bbee-02f9e1bf7b46` is only meant to be used by Azure CLI. Using it in your own application is not supported and may cause unexpected failure at any time.**

**Comment by yonzhan** [comment]
remove urn:ietf:wg:oauth:2.0:oob

**Comment by jiasli** [comment]
The change has been rolled out. If you encounter error while using old Azure Storage Explorer to log in, please upgrade to the latest version of Azure Storage Explorer.

**Comment by aremo-ms** [comment]
today is October 7, 2022, I still see this URI required when connecting with Public Client (WinUI)
thoughts?
