### ISSUE TITLE
az storage blob metadata update -> lease-id parameter removed in 2.38

### ISSUE THREAD

**Issue by vincent-aviva** [Azure/azure-cli#23262]
## Describe the bug
After acquiring a lease through "az storage blob lease acquire --proposed-lease-id " we would like to update the metadata on that blob. Untill 2.37 we could provide --lease-id to the command and then it should work.
However, in 2.38 this parameter is removed and if you remove it in the call then you get the response

_There is currently a lease on the blob and no lease ID was specified in the request.
ErrorCode:LeaseIdMissing_

**Command Name**
`az storage blob metadata update`

**Errors:**
```
unrecognized arguments: --lease-id 952eea37-83c3-4c34-a975-460eff59eae6
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage blob lease acquire --account-name {} --subscription {} --auth-mode {} --container-name {} --blob-name {} --lease-duration {} --proposed-lease-id {}
- `az storage blob metadata update --account-name {} --subscription {} --auth-mode {} --container-name {} --name {} --metadata {} {} --lease-id {} --output {} --verbose`

## Expected Behavior
The metadata of the blob is updated.

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.38.0

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by timkowal** [comment]
Seeing the same.

Code that worked two days ago now produces error message:

ERROR: unrecognized arguments: --lease-id _xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_

And the documentation page no longer lists the "--lease-id" parameter.

Previous page (courtesy of the Wayback Machine):
![image](https://user-images.githubusercontent.com/81479839/180303163-44c26439-1c18-4cf5-aa90-c79dfe5e4aa6.png)

**Comment by olehb** [comment]
Any update on this regression issue?

**Comment by evelyn-ys** [comment]
@bebound Can you check if this is caused by track2 migration?
