### ISSUE TITLE
Azure Bastion native client rdp connection opens on all windows with no ability to change

### ISSUE THREAD

**Issue by annullator** [Azure/azure-cli#23261]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az network bastion rdp --name [bastion name --resource-group [bastion rg] --target-resource-id [vm resource id]
**Describe the bug**

When running the above command to generate a tunnel and leverage the bastion native rdp client connection. The RDP session opens on all screen with no ability to change it.
**To Reproduce**

run above command to connect to an azure vm using azure bastion native client connection
**Expected behavior**

azure bastion command to leverage the default.rdp file setting so that they can be manipulated
**Environment summary**

MSI install
Version:
az version
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
**Additional context**

**Comment by sgsvetko** [comment]
Any update on the topic?

**Comment by annullator** [comment]
> Any update on the topic?

You can rollback to 2.37 and it works. Hopefully it's fixed in the next version.

**Comment by sgsvetko** [comment]
Good point, i gave it a chance, but once i start Azure RDP native client with az account set ************ it automatically start upgrade process to azure cli 2.38 , even if i cancel the update, update process starts again 
New Azure CLI version available. Running 'az upgrade' to update automatically...so your suggestion doesn't help a lot
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.37.0. It will be updated to 2.38.0.
Updating Azure CLI with MSI from https://aka.ms/installazurecliwindows
Downloading MSI to C:\Users\<Users>\AppData\Local\Temp\tmpmovgy5au\azure-cli-2.38.0.msi

**Comment by annullator** [comment]
> Good point, i gave it a chance, but once i start Azure RDP native client with az account set ************ it automatically start upgrade process to azure cli 2.38 , even if i cancel the update, update process starts again New Azure CLI version available. Running 'az upgrade' to update automatically...so your suggestion doesn't help a lot This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus Your current Azure CLI version is 2.37.0. It will be updated to 2.38.0. Updating Azure CLI with MSI from https://aka.ms/installazurecliwindows Downloading MSI to C:\Users<Users>\AppData\Local\Temp\tmpmovgy5au\azure-cli-2.38.0.msi

You run "AZ config set auto-upgrade.enable=no" to turn off the auto update.

**Comment by sgsvetko** [comment]
Great!!!!! Works perfect.
Thanks a lot !!!

**Comment by sgsvetko** [comment]
Few versions later, in 2.40 still not fixed.

**Comment by PramodValavala-MSFT** [comment]
This has been addressed in [this PR](https://github.com/Azure/azure-cli/pull/24434) which adds a flag, `--configure`, to the command that opens the Remote Desktop Connection UI allowing you to configure the session to your liking. Closing.
