### ISSUE TITLE
Failed to run Event Hub command using CLI 2.38.0

### ISSUE THREAD

**Issue by yuanchenCY** [Azure/azure-cli#23270]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az eventhubs eventhub list --resource-group MediaRG --namespace-name test01
az eventhubs eventhub show --resource-group MediaRG --namespace-name test01 --name test 
az eventhubs namespace network-rule update --resource-group MediaRG --namespace-name test01 --public-network-access Disabled --enable-trusted-service-access true

**Describe the bug**

We are using Azure CLI 2.38.0, the latest version. But when we tried to run the event hub commands, below errors were returned:
![image](https://user-images.githubusercontent.com/75459922/179928664-adf5e387-c80b-4867-bc1d-d5b492b382da.png)
The latest API version is not found.

**To Reproduce**

1. Install Azure CLI 2.38.0
2. Run the command listed in "Related command"

**Expected behavior**

The commands should run successfully.

**Environment summary**

Azure China 
CLI 2.38.0

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@yuanchenCY I think this api version is not supported for Azure China environment however redirecting this to services team to confirm back on the same. Thanks.

**Comment by yuanchenCY** [comment]
> @yuanchenCY I think this api version is not supported for Azure China environment however redirecting this to services team to confirm back on the same. Thanks.

If this is not yet supported, which CLI version with supported API version could we use to run network-rule update command for event hub in Azure China?

**Comment by Saglodha** [comment]
@yuanchenCY - You can try to use CLI version 2.37.0 for Azure China environment. Please let us know if you bump into any issues there as well.

**Comment by yuanchenCY** [comment]
> @yuanchenCY - You can try to use CLI version 2.37.0 for Azure China environment. Please let us know if you bump into any issues there as well.

@Saglodha I tried 2.37.0, but also failed:
![image](https://user-images.githubusercontent.com/75459922/181170564-4e16724b-af7d-40f3-81fb-66fcc6c72e51.png)
We found there is no update command in 2.37.0:
![image](https://user-images.githubusercontent.com/75459922/181170784-d5a8375b-b6b7-4830-a6e6-0d493504b92c.png)

**Comment by Saglodha** [comment]
@yuanchenCY - Thanks for sharing details, update cmdlet was released in latest release hence it is probably not deployed in China environment

We should be pushing another update that should resolve this. 2nd week of August should be ETA.

**Comment by yuanchenCY** [comment]
> @yuanchenCY - Thanks for sharing details, update cmdlet was released in latest release hence it is probably not deployed in China environment
> 
> We should be pushing another update that should resolve this. 2nd week of August should be ETA.

Thanks @Saglodha for sharing the plan with us. Looking forward to the new update to Azure China.

**Comment by Saglodha** [comment]
@yuanchenCY , Update should be live in China region. Can you please retry the operation and share feedback? Thanks.
