### ISSUE TITLE
Creating a rule in application gateway via AZ CLI fail with message 'ERROR: (ApplicationGatewayRequestRoutingRulePartialPriorityDefined) Either all or no rule should have the priority specified.'

### ISSUE THREAD

**Issue by Brudem** [Azure/azure-cli#23271]
HI, I have this issue when trying to create a new rule in app gtw.

Depending of the application gateway instance that I use I have an error or not.

I use the same AZ CLI version and the same command (except for the name of the rule and app gtw instance refs).

With my first application gateway instance I receive the following error when creating a rule with this AZ CLI cmd :

az network application-gateway rule create --subscription XXX --resource-group RG_XXX --gateway-name AG_XXX --name PTAIL_CLNT_souscriptionpp_INT --rule-type PathBasedRouting --http-listener PTAIL_CLNT_souscriptionpp_INT --url-path-map PTAIL_CLNT_souscriptionpp_INT --address-pool See-Warning --http-settings See-Warning **--priority 50**

 **ERROR: (ApplicationGatewayRequestRoutingRulePartialPriorityDefined) Either all or no rule should have the priority specified.**

Setting the rule with the same priority (50) via Azure portal is **OK**.
Other rules (on other listeners of the same app gtw) have the priority 10 & 20, so 50 should be accepted for this one ...

_Originally posted by @Brudem in https://github.com/Azure/azure-cli/issues/22279#issuecomment-1189936465_

**Comment by yonzhan** [comment]
network

**Comment by necusjz** [comment]
@Brudem, could you attach the debug information (append --debug) for this command? And it's better to have the result of "az network application-gateway rule list -g {} --gateway-name {}". Thanks.

**Comment by Brudem** [comment]
@necusjz I tried again the request but it succeded this time ...

The only thing I did between my failed attemps and the one I just tried is to change the priority of the rule via azure portal (as mentioned in my initial comment changing the rule via Azure portal was working without issue).
I wonder if setting the rule priority via AZ portal  did not had an effect on my rule status (or the whole app gtw ?) in a way that now it is working via AZ CLI ?

Anyway I made several consecutive tries today via AZ CLI without any fail ..? So sorry but I not able to reproduce the issue anymore ...

**Comment by Brudem** [comment]
@necusjz no really a so big story but since the issue can't be reproduced I think it can be closed if you agree.
