### ISSUE TITLE
AZ Blob list not working 

### ISSUE THREAD

**Issue by lokeshs053** [Azure/azure-cli#23279]
## Describe the bug

**Command Name**
`az storage blob list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 237, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 148, in out
MemoryError

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob list --account-name {} --container-name {} --auth-mode {} --num-results {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.30.0 *

```

**Comment by yonzhan** [comment]
storage

**Comment by bebound** [comment]
This issue is not related to Azure-cli, `MemoryError` means you run out of memory.
Close some apps or restart you PC and try again.

Or you can use `--num-results` to limit the maximum number of items to return.

**Comment by bebound** [comment]
We've released the 64-bit MSI, hope this error is eliminated. https://github.com/Azure/azure-cli/pull/26640
