### ISSUE TITLE
CDN Adding certificate from keyvault to CDN Endpoint (from other subscription) throws error

### ISSUE THREAD

**Issue by shiftychris** [Azure/azure-cli#23276]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az cdn custom-domain enable-https `
                        --resource-group $sc.resource `
                        --subscription $Endpoint.subscription `
                        --profile-name $cdnProfile `
                        --endpoint-name $endpointName `
                        --name $domainName `
                        --user-cert-subscription-id $kvSubscription`
                        --user-cert-group-name $kvResource `
                        --user-cert-vault-name $kvVaultName `
                        --user-cert-secret-name $kvSecret `
                        --user-cert-protocol-type 'sni'

**Describe the bug**
Receive error: az : ERROR: (BadRequest) The subscription ID of the Key Vault account is different from the subscription ID of the CDN profile

**To Reproduce**
Add certificate from KeyVault (exists in Subscription 1) to a CDN endpoint (lives in Subscription 2) 

**Expected behavior**
Supports a KV in multiple subscriptions across the same tenant 

**Environment summary**
azure-cli                         2.36.0 *

core                              2.36.0 *
telemetry                          1.0.6

Extensions:
aks-preview                       0.5.51

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@shiftychris This is expected behavior of CDN service as Key Vault account needs to be under the same subscription as the Azure CDN profile.  Please refer to [this](https://docs.microsoft.com/en-us/azure/cdn/cdn-custom-ssl?tabs=option-2-enable-https-with-your-own-certificate#prepare-your-azure-key-vault-account-and-certificate) documentation.

**Comment by SaurabhSharma-MSFT** [comment]
@shiftychris We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by tibor19** [comment]
[SaurabhSharma-MSFT](https://github.com/SaurabhSharma-MSFT) The documentation should reflect the product capabilities, and not the other way around (in other words what is in documentation should not drive the features of the application). However, if we are to following this line of thought according to this: https://learn.microsoft.com/en-us/cli/azure/cdn/custom-domain?view=azure-cli-latest#az-cdn-custom-domain-enable-https using cli you can specify the subscription id for the keyvault (there are two different parameters in the command, one for the keyvault one for the CDN) which leads one to believe that there is an error in the product.
