### ISSUE TITLE
azure bastion RDP stopped working

### ISSUE THREAD

**Issue by MichaelFitzTech** [Azure/azure-cli#23273]
Last week I could run the following cmd in powershell and the native RDP session would open for me to input the azure vm's log on creds and it worked.  
az network bastion rdp --name "BASTIONNAME" --resource-group "RGNAME" --target-resource-id "/subscriptions/*********/resourceGroups/*********/providers/Microsoft.Compute/virtualMachines/VMNAME"

Whats started to happen now is i get a message saying "Invalid connection file (C:\Windows\system32/conn.rdp) specified"

If I create a new file called conn.rdp and place it this location the cmd runs and opens the RDP connection box asking for the vm's name.  Whatever details I put in here do not work.
When the powershell cmd did work last week the RDP box had the details in and connected, all I had to do was input the log on creds and the RDP session to the azure vm opened fine

**Comment by yonzhan** [comment]
route to CXP team

**Comment by MichaelFitzTech** [comment]
I've fixed my issue.  I deleted everything from %temp% in my profile and the connection RDP session started working again

**Comment by MichaelFitzTech** [comment]
Started happening again, tried deleting the file in $temp% again but this didn't work this time.  Any suggestions what is causing this issue?

**Comment by nagakei05** [comment]
@MichaelFitzTech 
Does this issue relate?
If you are trying to connect from a admin powershell, will trying the Azure CLI command from a non-admin powershell resolve the issue?
#23515

**Comment by PramodValavala-MSFT** [comment]
@MichaelFitzTech The command creates the `conn.rdp` file in the current working directory which is `C:\Windows\System32` since you are running as admin. While I'm not sure why it fails to create the file (without actually failing 😕), you should be able to resolve this simply by changing into a different directory and running the command.
