### ISSUE TITLE
Incorrect description for `az cosmosdb network-rule remove`

### ISSUE THREAD

**Issue by t-bzhan** [Azure/azure-cli#23299]
The description for `az cosmosdb network-rule remove` is incorrect. It should be "Remove" instead of "Add".
![image](https://user-images.githubusercontent.com/61817681/180346534-ed432c4d-0311-489b-8bd0-b63029261982.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceafa346-5ac6-9a5b-b36b-fb6a91449ae0
* Version Independent ID: 12dc1540-3a61-aece-0ef0-0d4c192d930e
* Content: [az cosmosdb network-rule](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/network-rule?view=azure-cli-latest#az-cosmosdb-network-rule-remove)
* Content Source: [latest/docs-ref-autogen/cosmosdb/network-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/cosmosdb/network-rule.yml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team
