### ISSUE TITLE
Cosmos DB: SQL Database Throughput Migrate Fails

### ISSUE THREAD

**Issue by adthorn** [Azure/azure-cli#23296]
## Describe the bug

**Command Name**
`az cosmosdb sql database throughput migrate`

**Errors:**
```
(NotFound) Entity with the specified id does not exist in the system. More info: https://aka.ms/cosmosdb-tsg-not-found
ActivityId: 4b92e1ae-08fe-11ed-b3e1-168bbf3396af, Microsoft.Azure.Documents.Common/2.14.0
Code: NotFound
Message: Entity with the specified id does not exist in the system. More info: https://aka.ms/cosmosdb-tsg-not-found
ActivityId: 4b92e1ae-08fe-11ed-b3e1-168bbf3396af, Microsoft.Azure.Documents.Common/2.14.0

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az cosmosdb sql database throughput migrate --subscription {} --resource-group {} --account-name {} --name {} --throughput-type {}`

## Environment Summary
```
Linux-5.4.0-1086-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.5
Installer: DEB

azure-cli 2.38.0

Extensions:
virtual-wan 0.2.12
authV2 0.1.1
application-insights 0.1.16
ai-examples 0.2.5
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context
Resources exist, and can confirm the commands are correct. Databases and everything exist. Does not want to work.

**Comment by SaurabhSharma-MSFT** [comment]
@adthorn We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@adthorn I do not see any issues with migrating throughput to manual. 
![image](https://user-images.githubusercontent.com/38112130/180584223-b07cc537-3235-4a27-9d29-d8e995b71a30.png)

 Did you create your database with provisioned throughput as mentioned over [here](https://docs.microsoft.com/en-us/azure/cosmos-db/set-throughput#set-throughput-on-a-database-and-a-container) before executing the `migrate` command? 
Also, can you try creating a new database with provisioned throughput and try migrating?
