### ISSUE TITLE
Deprecated documentation page az storage blob directory

### ISSUE THREAD

**Issue by vaclav-stummer** [Azure/azure-cli#23305]
This page for the `az storage blob directory` is not relative anymore as it seems that the cli tool uses `az storage directory instead.

```
azure-cli                         2.0.81
core                              2.0.81
telemetry                          1.0.4
Extensions:
azure-devops                      0.17.0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 978a095c-3ead-282f-304f-fb627dad53a4
* Version Independent ID: 43fb2b4e-3f87-f3b8-2e85-ed5812a69ffc
* Content: [az storage blob directory](https://docs.microsoft.com/en-us/cli/azure/storage/blob/directory?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/storage/blob/directory.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/blob/directory.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by vaclav-stummer** [comment]
After further reading of the documentation. I find out the documentation is fine and it is just a bit confusing on the first reading. Keep doing great job 🚀

**Comment by yonzhan** [comment]
Thanks for your feedback
