### ISSUE TITLE
The --destination-ports param is declared as optional for the add filter collection.

### ISSUE THREAD

**Issue by ahmedkhamessi** [Azure/azure-cli#23306]
[The --destination-ports parameter in the  'az network firewall policy rule-collection-group collection add-filter-collection' is actually not optional as it's required by the api and i can share the debug messages.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6638413c-945b-bcfb-faf9-902dc792fbcb
* Version Independent ID: 852c0d17-43b9-4fdc-0d6f-bc34355ab586
* Content: [az network firewall policy rule-collection-group collection](https://docs.microsoft.com/en-us/cli/azure/network/firewall/policy/rule-collection-group/collection?view=azure-cli-latest#az-network-firewall-policy-rule-collection-group-collection-add-filter-collection)
* Content Source: [latest/docs-ref-autogen/network/firewall/policy/rule-collection-group/collection.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/firewall/policy/rule-collection-group/collection.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
network

**Comment by ZengTaoxu** [comment]
Hi @ahmedkhamessi, when the rule-type is "NetworkRule", --destination-ports is mandatory. However, when the type is not "NetworkRule", the parameter --destination-ports is not required.

**Comment by ahmedkhamessi** [comment]
@ZengTaoxu  Thanks for the reply, I think it should be more explicit in the documentation, I have received so many inquiries regarding that command line therefor i opened the request.

**Comment by ZengTaoxu** [comment]
Hi @ahmedkhamessi, if you want to modify documentation, you may need to contact doc team. If you want to prompt when typing this command, we can update this command.

**Comment by ahmedkhamessi** [comment]
@ZengTaoxu , I think a prompt is already good enough. Thanks for the support!
