### ISSUE TITLE
`az login --use-device-code` should always show device code

### ISSUE THREAD

**Issue by doggy8088** [Azure/azure-cli#23320]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

```sh
az login --use-device-code
```

**Describe the bug**

I previously configured `only_show_errors = true` in my azure cli config file. That cause `az login --use-device-code` show nothing on the screen and it looks like a bug.

**To Reproduce**

```sh
az config set core.only_show_errors=true
az login --use-device-code
```

**Expected behavior**

I expected the `az login --use-device-code` should always show device code for login purpose.

**Environment summary**

```log
azure-cli                         2.38.0

core                              2.38.0
telemetry                          1.0.6

Extensions:
account                            0.2.3
azure-devops                      0.25.0
front-door                        1.0.16
interactive                        0.4.5
k8s-extension                      1.2.4
managementpartner                  0.1.3

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\wakau\.azure\cliextensions'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Additional context**

N/A

**Comment by yonzhan** [comment]
@Jiasli for awareness

**Comment by jiasli** [comment]
This is because device code message is printed using `logger.warning` which is controlled by `core.only_show_errors` config option. If `core.only_show_errors` is set to `true`, device code message will be hidden.

I will refine this behavior in #23647.
