### ISSUE TITLE
Handling $skipToken in az rest doesn't work properly

### ISSUE THREAD

**Issue by caroysMSFT** [Azure/azure-cli#23327]
**Related command**

az rest

**Describe the bug**

When you are working with the az rest command, you may find that some REST API's cut you off at a lower threshold than 1000 (in the case of listing ADF pipelines, it's 50).  When this happens, you get a nextLink element in the returned JSON which gives you a URI with a $skipToken baked in which lets you fetch the next page of results.

When you attempt to feed this $skipToken URI back into AZ Rest, it doesn't handle the skip token correctly.  Instead, it calls the URI without the skip token and you get the first page of results and this error:\

```
az : '$skipToken' is not recognized as an internal or external command,
At line:1 char:1
+ az rest --uri 'https://management.azure.com/subscriptions/aebde77f-71 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('$skipToken' is...ternal command,:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
operable program or batch file.
```

**To Reproduce**

1. Find an ADF which has more than 50 pipelines
2. Try to list the pipelines via az rest like:

az rest --uri 'https://management.azure.com/subscriptions/(subid)/resourceGroups/(rgname)/providers/Microsoft.DataFactory/factories/(factoryname)/pipelines?api-version=2018-06-01' --method get"

3. verify that it sends back in the JSON the nextLink element containing the URI with the skip token.
4. Feed that URI back into the az rest command

**Expected behavior**

You receive in the JSON output the second page of results (and if in excess of 50, _another_ nextLink URI pointing to the next page of results)

**Environment summary**

MSI install, 2.37.0
Windows 10

**Additional context**

It seems likely it's the dollar sign in the $skipToken parameter which is the problem.  Here's the URI format you get back:

https://management.azure.com/subscriptions/(subid)/resourceGroups/(rgname)/providers/Microsoft.DataFactory/factories/(factoryname)/pipelines?api-version=2018-06-01&$skipToken=%2bRID%3a~nhMwANW5IRHQI9YFAAAAAA%3d%3d%23RT%3a1%23TRC%3a50%23ISV%3a2%23IEO%3a65551%23QCF%3a8

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This is not related to Azure CLI, but a PowerShell usage question. See

- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.2
- https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#use-quotation-marks-in-parameters
