### ISSUE TITLE
Support for EnableFatFlowLogging parameter on Azure Firewall

### ISSUE THREAD

**Issue by jashwanth** [Azure/azure-cli#23325]
**Resource Provider**
Network (NRP)

**Description of Feature or Work Requested**
Need to add a new parameter named EnableFatFlowLogging to the base command of creating the Firewall.
az network firewall create -g MyResourceGroup -n MyFirewall --enable-fat-flow-logging true

Only parameter needed is:

enable-fat-flow-logging
Default value is false

No NRP/Swagger change needed 
**Additional context**

**Comment by jashwanth** [comment]
Powershell PR for reference 
https://github.com/Azure/azure-powershell/pull/18992

**Comment by jashwanth** [comment]
Original PR : https://github.com/Azure/azure-powershell/pull/18948

Field renames after discussion with PM team:
https://github.com/Azure/azure-powershell/pull/18992

**Comment by yonzhan** [comment]
network feature

**Comment by necusjz** [comment]
@jashwanth, we cannot support this feature since the swagger is not ready.

**Comment by Gizachew-Eshetie** [comment]
> @jashwanth, we cannot support this feature since the swagger is not ready.

It will be sent to backend as an additional property (Network.AdditionalLogs.EnableFatFlowLogging) like it is done in the above PowerShell PR? Do we still need swagger change?
e.g mapping from SDK to PS => {PSFirewallObj}.EnableFatFlowLogging = {SDKFirewallObj}.AdditionalProperties?.SingleOrDefault(kvp => kvp.Key.Equals("Network.AdditionalLogs.EnableFatFlowLogging", StringComparison.OrdinalIgnoreCase)).Value;

**Comment by necusjz** [comment]
@Gizachew-Eshetie, thanks for your explanation, we'll develop it in this sprint.

**Comment by saisujithreddym** [comment]
Thank you @necusjz and @ZengTaoxu . Please let us know if you need more information to get this work done. Also can you please provide the ETA for the changes?

**Comment by necusjz** [comment]
> Thank you @necusjz and @ZengTaoxu . Please let us know if you need more information to get this work done. Also can you please provide the ETA for the changes?

Around 09/06/2022.
