### ISSUE TITLE
Issue with AKS connectivity using az cli

### ISSUE THREAD

**Issue by PawelMJanicki** [Azure/azure-cli#23333]
Dear All,

**Related command**
```
az aks get-credentials
az aks list
```

**Describe the bug**
it is impossible to connect to the AKS cluster from the Cloud Shell and BASH scripts executed within the CI/CD. Errors point to EntityStoreOperationError. Examples of failing commands with outputs are presented below

```
az aks get-credentials --resource-group XXX --name XXX --admin --only-show-errors
(EntityStoreOperationError) Failed to get managed cluster XXX in subscription XXX, resource group XXX. A database operation failed. Please retry later. If this error persists, contact AKS support.
Code: EntityStoreOperationError
Message: Failed to get managed cluster XXX in subscription XXX, resource group XXX. A database operation failed. Please retry later. If this error persists, contact AKS support.
```

```
az aks list
(EntityStoreOperationError) We are unable to serve this request due to an internal error, Correlation ID: 53be7944-c8ea-4782-8d01-12f2aa459853, Operation ID: bdd088cf-685f-40b8-ab7c-2a1a76c9d892, Timestamp: 2022-07-26T06:41:18Z.
Code: EntityStoreOperationError
Message: We are unable to serve this request due to an internal error, Correlation ID: 53be7944-c8ea-4782-8d01-12f2aa459853, Operation ID: bdd088cf-685f-40b8-ab7c-2a1a76c9d892, Timestamp: 2022-07-26T06:41:18Z.
```

**To Reproduce**
trigger commands

**Expected behaviour**
it is possible to obtain credentials and connect with the AKS cluster using AZ CLI

**Environment summary**
The issue occurs from Azure Cloud Shell from Azure Portal and locally from BASH.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by FumingZhang** [comment]
Hey @PawelMJanicki, from the information you provided, this error (EntityStoreOperationError) occurs on the server side. Please retry the command/operation later or open a support ticket via Azure Portal if the error still occurs.

**Comment by navba-MSFT** [comment]
@PawelMJanicki Thanks for reaching out to us and reporting this issue. Hope you had a chance to look at the above comment by @FumingZhang. Please let us know if you are still seeing the same issue after a retry operation. Awaiting your reply.

**Comment by PawelMJanicki** [comment]
Thanks. The issue didn't occur again. Indeed it seems that this was a problem on the server site, nevertheless, AKS reported a healthy state.

**Comment by navba-MSFT** [comment]
@PawelMJanicki Thanks for getting back. During such issue a retry operation should fix it. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by naveenreddyin** [comment]
I also tried to create a cluster using the portal and I get the exact error.
