### ISSUE TITLE
Table output of Azure CLI 2.0 is not as user friendly as default output of Azure CLI 1.0

### ISSUE THREAD

**Issue by ogrisel** [Azure/azure-cli#2333]
For instance under 1.0:

```
$ azure vm list-usage -l eastus  | head
info:    Executing command vm list-usage
data:    Name                          Unit   CurrentValue  Limit
data:    ----------------------------  -----  ------------  -----
data:    Availability Sets             Count  0             2000 
data:    Total Regional Cores          Count  246           560  
data:    Virtual Machines              Count  38            10000
data:    Virtual Machine Scale Sets    Count  0             2000 
data:    Standard NC Family Cores      Count  246           558  
data:    Basic A Family Cores          Count  0             20   
data:    Standard A0-A7 Family Cores   Count  0             20   
``` 

now same command with 2.0:

```
$ az vm list-usage -l eastus -o table | head
  Limit    CurrentValue
-------  --------------
   2000
    560             246
  10000              38
   2000
    558             246
     20
     20
     20
```

**Comment by lostintangent** [comment]
The issue with the `list-usage` command specifically is currently tracked via #2019.

**Comment by ogrisel** [comment]
I found that this is not the only command. Pretty much all the az commands lack important info that are displayed by default with the matching `azure` commands. For instance:

```
$ az vm list -o table
Name                    ResourceGroup           Location
----------------------  ----------------------  --------------
vm-name1                GROUP1                  eastus
vm-name2                GROUP1                  eastus
```
vs

```
data:    ResourceGroupName       Name                    ProvisioningState  PowerState      Location        Size         
data:    ----------------------  ----------------------  -----------------  --------------  --------------  -------------
data:    GROUP1                  vm-name1                Succeeded          VM deallocated  eastus          Standard_NC6 
data:    GROUP2                  vm-name2                Succeeded          VM deallocated  eastus          Standard_NC6 

```

I think a systematic review of all the commands is needed to ensure that UX is not degraded when switching from azure CLI 1.0 to azure CLI 2.0.

**Comment by yugangw-msft** [comment]
@ogrisel, for `vm list/show`, please use `-d` which should show extra useful information like `ip address` and `power state`. 
For the `list-usage`, the default table view skips any property with composite type; hence it appears info missing.  I will chat with my teams to get it easier for commands author to pick the nested fields for table output. Either way, we have a bug to fix.
Regarding how useful of the table output, imo, you can use it to view the overall resource state, but to perform extended operations, it will not be helpful. The screen real estate limits how much we can display, and it is hard to nominate a list which will be universally helpful to all, so it is highly recommended to use `--query` to pick columns tailoring to individual scenario

**Comment by ogrisel** [comment]
At least power state and probably ip and size would be generally useful for the vm list in my opinion.

**Comment by sknkmn** [comment]
for some reason if i 'az vm list' it returns outputs in JSON rather than tabular.. any ideas here?

**Comment by tjprescott** [comment]
The CLI only has a single default output format, unlike CLI 1.0 that had default formats per command. If you would like table output, run your command with `-o table`.  You can also set table to be your default output format, but I don't recommend it as it inherently displays less information.

**Comment by sknkmn** [comment]
Thanks!!

**Comment by troydai** [comment]
@JasonRShaver can you take care of this?

**Comment by yugangw-msft** [comment]
Closing this as both cases were taken care of. For showing `powerState` through `-d`, we would like keep this way, as it involves more expensive API so opt-in is reasonable
For other commands, we have already fixed a lot.  Let us can open individual ones for specific commands
