### ISSUE TITLE
TDE name is fixed coding as "current", thus this information should be mentioned in the documentation and the example should be modified to use "current" as TDE name

### ISSUE THREAD

**Issue by KeeveySongMS** [Azure/azure-cli#23334]
TDE name is fixed coding as "current", thus this information should be mentioned in this documentation and all the examples in the doc should be modified to use "current" as TDE name
for example:
--transparent-data-encryption-name current

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a60f739-3b96-2f08-03e9-6bd11b73a614
* Version Independent ID: 8b154795-cb91-3254-fe23-3d89c6bf787b
* Content: [az synapse sql pool tde](https://docs.microsoft.com/en-us/cli/azure/synapse/sql/pool/tde?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/synapse/sql/pool/tde.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/synapse/sql/pool/tde.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@KeeveySongMS Thank you for reaching out, we are looking into it.
