### ISSUE TITLE
JSON set as default output format is not user friendly

### ISSUE THREAD

**Issue by ogrisel** [Azure/azure-cli#2334]
I find it very unexpected to get huge JSON blobs when calling `az` commands in an interactive terminal. I would have expected to have the `table` output which is much more human readable as default and expose machine readable formats such as JSON as non defaults options primarily used for scripting.

Note that the `table` output should also be improved to be as informative as the default output of azure CLI 1.0 as reported in #2333.

**Comment by derekbekoe** [comment]
`az configure` allows you to change the default output format.

**Comment by ogrisel** [comment]
Thanks for the info but I think default matters a lot from a UX point of view. Feel free to close this issue if you disagree.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
