### ISSUE TITLE
az vm list-skus filtering out VM sizes that are available regionally when they are restricted in all zones

### ISSUE THREAD

**Issue by arsenvlad** [Azure/azure-cli#23341]
**Related command**
az vm list-skus

**Describe the bug**
The current logic for "vm list-skus" is filtering out VM sizes that are available regionally when they are restricted in all zones. Relevant code line is this https://github.com/Azure/azure-cli/blob/b4759064b7e38203ef9d67a581105206a17f513b/src/azure-cli/azure/cli/command_modules/vm/custom.py#L1285

This does not appear to be correct behavior, since a VM size maybe restricted for all 3 zones "zonally" but still be available for a subscription when deployed "regionally".

* When restrictionInfo.type=”Zone” it means it is a zonal restriction for the subscription: i.e., not available to deploy this VM size in the subscription in the zones specified in the restrictionInfo properties (and could be all 3 zones)
* When restrictionInfo.type=”Location” it means it is a regional restriction for the subscription: i.e., not available to deploy this VM size in the subscription in the region even when not specifying a zone

**To Reproduce**
Execute "az vm list-skus" on an Azure subscription that has some VM sizes that are restricted zonally in all 3 zones but are not restricted regionally. Review the output to see that the VMs sizes are not listed.

As expected, all VM sizes are returned when using the `--all` parameter, but the available sizes should also be returned without using `--all` if these sizes are not restricted regionally as well as zonally.

**Expected behavior**
VM sizes that are available for a subscription, either regionally or zonally, should be returned by the "az vm list-skus" command even without including the `--all` parameter.

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by yanzhudd** [comment]
Hello @arsenvlad, we will fix this issue in #23457, could you please help to confirm if it meets your expectations?
https://github.com/Azure/azure-cli/pull/23457/files

**Comment by arsenvlad** [comment]
Thanks. I left a comment on the PR #23457
