### ISSUE TITLE
Unable to install Azure CLI: File has unexpected size (11552 != 11770). Mirror sync in progress?

### ISSUE THREAD

**Issue by luisve1427** [Azure/azure-cli#23343]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
apt-get update -y
apt-get install ca-certificates curl apt-transport-https lsb-release gnupg -y
curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
    tee /etc/apt/sources.list.d/azure-cli.list
apt-get update -y
apt-get install azure-cli -y

**Describe the bug**
Err:5 https://packages.microsoft.com/repos/azure-cli buster/main amd64 Packages
  File has unexpected size (11552 != 11770). Mirror sync in progress? [IP: 40.117.131.251 443]
  Hashes of expected file:
   - Filesize:11770 [weak]
   - SHA512:d3712a63ce0d8aaa2067aa6003fa2052f691002a1faad809760d3c4ab01ea6571a3311b50351937b610fee3a8bde4c0973a019f97d7dfb836fb79b34a1a56fce
   - SHA256:09e44633d0bedb4d1702e6a4ec18150d7bc9a7084d37065f6a66706f7a7747eb
   - SHA1:2b3387f166da17078df2946ec425bbf60a0859d9 [weak]
   - MD5Sum:4d38699d75f06cec44a8f4934f298271 [weak]
  Release file created at: Tue, 05 Jul 2022 03:16:01 +0000
Get:6 https://packages.microsoft.com/repos/azure-cli buster/main all Packages [11.6 kB]
Fetched 41.3 kB in 1s (66.1 kB/s)
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/buster/main/binary-amd64/Packages.bz2  File has unexpected size (11552 != 11770). Mirror sync in progress? [IP: 40.117.131.251 443]
   Hashes of expected file:
    - Filesize:11770 [weak]
    - SHA512:d3712a63ce0d8aaa2067aa6003fa2052f691002a1faad809760d3c4ab01ea6571a3311b50351937b610fee3a8bde4c0973a019f97d7dfb836fb79b34a1a56fce
    - SHA256:09e44633d0bedb4d1702e6a4ec18150d7bc9a7084d37065f6a66706f7a7747eb
    - SHA1:2b3387f166da17078df2946ec425bbf60a0859d9 [weak]
    - MD5Sum:4d38699d75f06cec44a8f4934f298271 [weak]
   Release file created at: Tue, 05 Jul 2022 03:16:01 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**To Reproduce**
try to install azure cli using steps in documentation

**Expected behavior**
azure cli is installed

**Environment summary**
script in Linux

**Comment by svallebro** [comment]
We are also experiencing this!
It also happens when running inside of docker build.
From another IP 137.135.134.16

**Comment by svallebro** [comment]
It seems related to the release of  #22161

**Comment by jiasli** [comment]
> It seems related to the release of #22161

It is irrelevant.

We worked with Microsoft Linux Repo team to fix this issue. Please retry the installation and let us know if it is now working. Thanks.

**Comment by svallebro** [comment]
This now works for me.
Great work.

If one finds similar issues with the https://packages.microsoft.com/repos/
What is the best way to notify the right team from outside, i.e. the Microsoft Linux Repo team, and where can one learn that kind of stuff?

I would imagine that @jiasli can't be this responsive all the time.

**Comment by luisve1427** [comment]
this is now working, thanks for the help
