### ISSUE TITLE
When running `az` I get `No such file or directory`

### ISSUE THREAD

**Issue by VedAustin** [Azure/azure-cli#23342]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**
Installing azure cli on Mac M1 and after installation is complete, and I run the `az` command, it returns 
```
/opt/homebrew/bin/az: line 2: /opt/homebrew/Cellar/azure-cli/2.36.0/libexec/bin/python: No such file or directory
```

**To Reproduce**
Followed all the steps under installing azure-cli for MacOS. The only difference being I used `ibrew` instead of `brew` since I have to use the rosetta terminal for all my applications.

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by bebound** [comment]
I install `ibrew` but I can't reproduce this. It works as expected.

Why the installed version is `2.36.0` rather than `2.38.0` on your computer?

**Comment by VedAustin** [comment]
That is an interesting question: 
When I run `az`, it shows up in `/opt/homebrew/Cellar/azure-cli/2.36.0/`
But when I try to uninstall azure-cli, it does it from this loc: `/usr/local/Cellar/azure-cli/2.38.0`

**Comment by VedAustin** [comment]
I resolved it by uninstalling azure-cli from `arch:amd 64` and only having it under `i386`
