### ISSUE TITLE
documentation lacks examples of content parameter

### ISSUE THREAD

**Issue by sheridanharrison-msft** [Azure/azure-cli#23354]
The examples are not documenting what the body of the content parameter should contain beyond indicating it can be json or a path to a json file.  What does the json look like? Please provide examples of the content parameter for all of these CLI commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 423b46b0-9716-ed78-02c3-7a184b6780f7
* Version Independent ID: 81b8ae77-52ba-3b78-6504-147553fea924
* Content: [az iot central device attestation](https://docs.microsoft.com/en-us/cli/azure/iot/central/device/attestation?view=azure-cli-latest#az-iot-central-device-attestation-create)
* Content Source: [latest/docs-ref-autogen/iot/central/device/attestation.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/iot/central/device/attestation.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@sheridanharrison-msft Thank you for reaching out to us, you can find more information about the content here in the Rest API documentation https://docs.microsoft.com/en-us/rest/api/iotcentral/1.2-previewdataplane/devices/create-attestation?tabs=HTTP#request-body

**Comment by yonzhan** [comment]
route to CXP team
