### ISSUE TITLE
Spelling mistake in SQL Managed Instance CLI

### ISSUE THREAD

**Issue by garvkariya** [Azure/azure-cli#23357]
# There is a spelling mistake in SQL Managed Instance CLI document:

Places where "Azure Active Directory" need to be mentioned in this document,
Instead "Azure Active Directly" is been used, Directly should be replaced with Directory,
In Commands section for below document:

Link: https://docs.microsoft.com/en-us/cli/azure/sql/mi?view=azure-cli-latest#commands

- az sql mi ad-only-auth | Manage a Managed Instance's Azure Active "Directly" only settings.
- az sql mi ad-only-auth disable | Disable Azure Active "Directly" only Authentication for this Managed Instance.
- az sql mi ad-only-auth enable | Enable Azure Active "Directly" only Authentication for this Managed Instance.
- az sql mi ad-only-auth get | Get a specific Azure Active "Directly" only Authentication property.

![image](https://user-images.githubusercontent.com/110147113/181417353-9e83e6c0-51c9-4c08-99ec-1fb31ef58655.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@garvkariya Thank you for reaching out, we are looking into it.
