### ISSUE TITLE
Login Failed: Decryption failed: [WinError -2146893813] Key not valid for use in specified state

### ISSUE THREAD

**Issue by nazana01** [Azure/azure-cli#23355]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --use-device-code`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.38.0
```

**Comment by yonzhan** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/20231
