### ISSUE TITLE
VMSS Create: support to create application gateway for scaleset with 100+ instance

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#2335]
LB has NAT rule limitation which can't go more than 100 instances

**Comment by yugangw-msft** [comment]
Plan for the release at the end of March

**Comment by yugangw-msft** [comment]
//cc: @tjprescott @gbowerman @gatneil 
Points captured from our conversation:

If we need multiple arguments for this, maybe we can expose from `app gateway create` such as:
    `az appgateway create -g gggg -n aaaaa –vmss-name xxxxx`

That’s still a fairly good user experience, without making create too heavy.

**Comment by tjprescott** [comment]
Good reference:
https://github.com/Azure/azure-quickstart-templates/blob/master/201-vmss-windows-app-gateway/azuredeploy.json
