### ISSUE TITLE
Access problem after upgrade azure-cli to 2.38.0

### ISSUE THREAD

**Issue by KMVPrograms** [Azure/azure-cli#23369]
## Describe the bug
Hello, We had an issue related to the access problems after upgrading azure-cli to 2.38.0 (the version 2.37.0 was worked fine). The storage account has an "Enabled from selected virtual networks and IP addresses" and if I add my IP to the allowed list it starts working, but it was worked fine without my IP too in previous version. The main issue is that we are using that in DevOps and "az storage file url" just become unworkable after azure-cli updates and I am not sure what I need to wrote to the allowed list to make it work again.

**Command Name**
`az storage file url`

**Errors:**
```
This request is not authorized to perform this operation.
RequestId:73c3cbc3-301a-0051-678b-a2016a000000
Time:2022-07-28T14:05:37.3303597Z
ErrorCode:AuthorizationFailure

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage file url -s {} -p {} --connection-string {} -o {}`

## Environment Summary
```
Linux-4.15.0-180-generic-x86_64-with-glibc2.27, Linux Mint 19.1
Python 3.10.5
Installer: DEB

azure-cli 2.38.0

Extensions:
confidentialledger 1.0.0
azure-devops 0.25.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
storage

**Comment by evelyn-ys** [comment]
Need storage service team debug. The requestId is given: `RequestId:73c3cbc3-301a-0051-678b-a2016a000000`

**Comment by navba-MSFT** [comment]
@KMVPrograms Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
