### ISSUE TITLE
az network nic ip-config address-pool add command fails

### ISSUE THREAD

**Issue by marty2bell** [Azure/azure-cli#2336]
Using the cli 2.0 to bind a nic to an address pool with the following command produces this error:

command:

az network nic ip-config address-pool add \
    --resource-group ${resource_group} \
    --nic-name ${nic_name} \
    --lb-name ${lb_name} \
    --address-pool ${lb_address_pool_name} \
    --ip-config-name ${lb_name}-binding

produces the following:

'NoneType' object has no attribute 'load_balancer_backend_address_pools'
Traceback (most recent call last):
  File "/Users/marty.bell/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/marty.bell/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/Users/marty.bell/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in _execute_command
    raise ex
AttributeError: 'NoneType' object has no attribute 'load_balancer_backend_address_pools'

Below is the azure client version:

 az --version
azure-cli (2.0.0)

acs (2.0.0)
appservice (0.1.1b5)
batch (0.1.1b4)
cloud (2.0.0)
component (2.0.0)
configure (2.0.0)
container (0.1.1b4)
core (2.0.0)
documentdb (0.1.1b2)
feedback (2.0.0)
iot (0.1.1b3)
keyvault (0.1.1b5)
network (2.0.0)
nspkg (2.0.0)
profile (2.0.0)
redis (0.1.1b3)
resource (2.0.0)
role (2.0.0)
sql (0.1.1b5)
storage (2.0.0)
vm (2.0.0)

Python (Darwin) 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

There do seem to be a number of similar issues with other use cases with the cli, but the remediation wasn't clear.....

Marty

**Comment by tjprescott** [comment]
Hi @marty2bell thanks for the report. I have reproduced the issue and confirmed that it could potentially affect a number of child operations for app gateway, load balancer and nic.

**Comment by tjprescott** [comment]
Until the fix is in and released, the following command should unblock your scenario.  It uses the generic update advanced feature:

```
az network nic update -g ${resource-group} --name ${nic-name} 
  --set ipConfigurations[name=${ip-config-name}].loadBalancerBackendAddressPools=[] 
  --add ipConfigurations[name=${ip-config}].loadBalancerBackendAddressPools id=${backend-address-pool-id}
```
Once you have added one in this way, you can use the add command as you tried.

**Comment by marty2bell** [comment]
Great.....thanks Travis

Marty
