### ISSUE TITLE
az monitor log-analytics workspace table create missing required parameter

### ISSUE THREAD

**Issue by wiperpaul** [Azure/azure-cli#23368]
Missing information regarding ` az monitor log-analytics workspace table create`

In the docs for the table create command seen here: https://docs.microsoft.com/en-us/cli/azure/monitor/log-analytics/workspace/table?view=azure-cli-latest#az-monitor-log-analytics-workspace-table-create-examples

The Required Parameters section is missing the fact there must be a 'TimeGenerated' column included in the table. It is not mentioned in the optional parameters or the required parameters however is mandatory as seen in the error below

ERROR: (SchemaUpdateFatalError) {"error":{"code":"BadRequest","message":"ServiceClient: Response status code does not indicate success - 400 (Bad Request), for request - /cms/apiv2/workspaces/redacted/tables/Testtable123_CL, due to reason - [Table validation failed with following errors: MSG 1005: Table missing mandatory 'TimeGenerated' column]."}}
Code: SchemaUpdateFatalError

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1e4e3d-3872-95c6-5089-fcfcbf74b325
* Version Independent ID: b665e74a-272e-f511-3042-75939704d7f5
* Content: [az monitor log-analytics workspace table](https://docs.microsoft.com/en-us/cli/azure/monitor/log-analytics/workspace/table?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/monitor/log-analytics/workspace/table.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/monitor/log-analytics/workspace/table.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
monitor

**Comment by kairu-ms** [comment]
Thanks for the feedback. It's a breaking change in API behaviors. We will add this argument in the next milestone.

**Comment by kairu-ms** [comment]
Already Fixed
