### ISSUE TITLE
containerapp create: the magic string secretRef is ignored when referencing a secret

### ISSUE THREAD

**Issue by guybarrette** [Azure/azure-cli#23365]
**Command**
az containerapp create

**Bug describtion**
When using **az containerapp create** to create a container app, a secret, and an env variable referencing the secret, the magic string **secretRef** is ignored.

The result:

  template:
   containers:
     - env:
     - name: thesecret
        value: secretRef:mysecret  <======= The magic string is ignored

**To Reproduce**
`az containerapp create -n test -g test --environment managedEnvironment-test --image nginx:latest --target-port 80 --cpu 0.5 --memory 1.0Gi --ingress 'external' --secrets mysecret=MySecretValue --env-vars "thesecret=secretRef:mysecret"`

**Expected behavior**

  template:
   containers:
     - env:
     - name: thesecret
        value: ''  <======= The secret is hidden

**Environment summary**

  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.76",
    "application-insights": "0.1.16",
    "containerapp": "0.3.8",
    "log-analytics": "0.2.2"
}

**Comment by yonzhan** [comment]
route to CXP team

**Comment by yonzhan** [comment]
route to CXP team

**Comment by guybarrette** [comment]
Anthony Chu MSFT pointed out that the **secretref** must be lowercase. This is not a CLI bug but a documentation bug. Anthony will review the doc: https://docs.microsoft.com/en-us/azure/container-apps/manage-secrets?tabs=azure-cli#example
