### ISSUE TITLE
Could not import runpy module

### ISSUE THREAD

**Issue by AlecWolman-msft** [Azure/azure-cli#23376]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

All az commands fail with the error "Could not import runpy module.  ModuleNotFoundError: No module named 'runpy'.

**To Reproduce**

Install azure-cli v2.38 on Ubuntu 22.04 in WSL2, using the documented installation instructions.

**Expected behavior**

az commands should work.

**Environment summary**

Shell is zsh on Ubuntu 22.04 on WSL2.

**Additional context**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Could you let us know how you installed Azure CLI and share the full call stack?

**Comment by AlecWolman-msft** [comment]
> Could you let us know how you installed Azure CLI and share the full call stack?

Yes, for install, I followed the instructions here:

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

I used apt to install the prerequisites.  I then installed the signing key, and added the following repo to /etc/apt/sources.list.d/azure-cli.list:
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ jammy main

And then I did:
apt intall azure-cli

When I run any thing I get:
> az --help
Could not import runpy module
ModuleNotFoundError: No module named 'runpy'
zsh: exit 1     az --help

**Comment by jiasli** [comment]
I tried to installed Azure CLI in a docker container but couldn't repro:

```
docker run -it --rm ubuntu:jammy
```

```
apt-get update
apt-get install --yes ca-certificates curl apt-transport-https lsb-release gnupg

curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list

apt-get update
apt-get install azure-cli
az --help
```

I found some related stackoverflow posts:

- https://stackoverflow.com/questions/44463879/could-not-import-runpy-module
- https://stackoverflow.com/questions/51405139/pip-not-working-modulenotfounderror-no-module-named-runpy

Could you run these commands and share the result?

```
env
which az
/opt/az/bin/python3 -c "import sys; print(sys.path)"
```

`runpy` is actually at

```
/opt/az/bin/python3 -c "import runpy; print(runpy.__file__)"
/opt/az/lib/python3.10/runpy.py
```

**Comment by AlecWolman-msft** [comment]
Sorry for the delay.

Here is some of the output requested:

% env
HOSTTYPE=x86_64
LANG=en_US.UTF-8
PATH=/home/alecw/bin.x86_64-linux:/home/alecw/bin.sh:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/bin/X11:.
TERM=xterm-256color
WSLENV=WT_SESSION::WT_PROFILE_ID
WT_SESSION=ed52d7ab-de4c-4146-9121-d9d059a4c79b
WT_PROFILE_ID={17bf3de4-5353-5709-bcf9-835bd952a95e}
WSL_INTEROP=/run/WSL/4938_interop
NAME=debris
HOME=/home/alecw
USER=alecw
LOGNAME=alecw
SHELL=/usr/bin/zsh
WSL_DISTRO_NAME=Ubuntu-22.04
SHLVL=1
PWD=/home/alecw
OLDPWD=/mnt/c/Users/alecw
TMPDIR=/var/tmp
LC_CTYPE=en_US.UTF-8
GTK_OVERLAY_SCROLLING=0
HISTFILE=/home/alecw/.zhistory
HISTSIZE=1000
SAVEHIST=1000
LESS=--no-init --quit-at-eof
EDITOR=emacs
OSTYPE=Linux
ARCHOS=x86_64-linux
HOSTNAME=debris
ALREADYDONE=true
domain=
LS_COLORS=no=00:fi=00:di=34:ln=35:pi=30;44:so=35;44:do=35;44:bd=33;44:cd=37;44:or=05;37;41:mi=05;37;41:ex=01;31:*.cmd=01;31:*.exe=01;31:*.com=01;31:*.bat=01;31:*.reg=01;31:*.app=01;31:*.txt=32:*.org=32:*.md=32:*.mkd=32:*.h=32:*.c=32:*.C=32:*.cc=32:*.cxx=32:*.objc=32:*.sh=32:*.csh=32:*.zsh=32:*.el=32:*.vim=32:*.java=32:*.pl=32:*.pm=32:*.py=32:*.rb=32:*.hs=32:*.php=32:*.htm=32:*.html=32:*.shtml=32:*.xml=32:*.rdf=32:*.css=32:*.js=32:*.man=32:*.0=32:*.1=32:*.2=32:*.3=32:*.4=32:*.5=32:*.6=32:*.7=32:*.8=32:*.9=32:*.l=32:*.n=32:*.p=32:*.pod=32:*.tex=32:*.bmp=33:*.cgm=33:*.dl=33:*.dvi=33:*.emf=33:*.eps=33:*.gif=33:*.jpeg=33:*.jpg=33:*.JPG=33:*.mng=33:*.pbm=33:*.pcx=33:*.pdf=33:*.pgm=33:*.png=33:*.ppm=33:*.pps=33:*.ppsx=33:*.ps=33:*.svg=33:*.svgz=33:*.tga=33:*.tif=33:*.tiff=33:*.xbm=33:*.xcf=33:*.xpm=33:*.xwd=33:*.xwd=33:*.yuv=33:*.aac=33:*.au=33:*.flac=33:*.mid=33:*.midi=33:*.mka=33:*.mp3=33:*.mpa=33:*.mpeg=33:*.mpg=33:*.ogg=33:*.ra=33:*.wav=33:*.anx=33:*.asf=33:*.avi=33:*.axv=33:*.flc=33:*.fli=33:*.flv=33:*.gl=33:*.m2v=33:*.m4v=33:*.mkv=33:*.mov=33:*.mp4=33:*.mp4v=33:*.mpeg=33:*.mpg=33:*.nuv=33:*.ogm=33:*.ogv=33:*.ogx=33:*.qt=33:*.rm=33:*.rmvb=33:*.swf=33:*.vob=33:*.wmv=33:*.doc=31:*.docx=31:*.rtf=31:*.dot=31:*.dotx=31:*.xls=31:*.xlsx=31:*.ppt=31:*.pptx=31:*.fla=31:*.psd=31:*.7z=1;35:*.apk=1;35:*.arj=1;35:*.bin=1;35:*.bz=1;35:*.bz2=1;35:*.cab=1;35:*.deb=1;35:*.dmg=1;35:*.gem=1;35:*.gz=1;35:*.iso=1;35:*.jar=1;35:*.msi=1;35:*.rar=1;35:*.rpm=1;35:*.tar=1;35:*.tbz=1;35:*.tbz2=1;35:*.tgz=1;35:*.tx=1;35:*.war=1;35:*.xpi=1;35:*.xz=1;35:*.z=1;35:*.Z=1;35:*.zip=1;35:*.ANSI-30-black=30:*.ANSI-01;30-brblack=01;30:*.ANSI-31-red=31:*.ANSI-01;31-brred=01;31:*.ANSI-32-green=32:*.ANSI-01;32-brgreen=01;32:*.ANSI-33-yellow=33:*.ANSI-01;33-bryellow=01;33:*.ANSI-34-blue=34:*.ANSI-01;34-brblue=01;34:*.ANSI-35-magenta=35:*.ANSI-01;35-brmagenta=01;35:*.ANSI-36-cyan=36:*.ANSI-01;36-brcyan=01;36:*.ANSI-37-white=37:*.ANSI-01;37-brwhite=01;37:*.log=01;34:*~=01;34:*#=01;34:*.bak=01;36:*.BAK=01;36:*.old=01;36:*.OLD=01;36:*.org_archive=01;36:*.off=01;36:*.OFF=01;36:*.dist=01;36:*.DIST=01;36:*.orig=01;36:*.ORIG=01;36:*.swp=01;36:*.swo=01;36:*,v=01;36:*.gpg=34:*.gpg=34:*.pgp=34:*.asc=34:*.3des=34:*.aes=34:*.enc=34:
WSL=WSL2
_=/usr/bin/env

% which az
/usr/bin/az

% /opt/az/bin/python3 -c "import sys; print(sys.path)"
['', '/opt/az/lib/python310.zip', '/opt/az/lib/python3.10', '/opt/az/lib/python3.10/lib-dynload', '/opt/az/lib/python3.10/site-packages']

% /opt/az/bin/python3 -c "import runpy; print(runpy.__file__)"
/opt/az/lib/python3.10/runpy.py

**Comment by Chuxel** [comment]
I think might I see the bug. If there's a symlink to az anywhere in the path, the az command will fail.

```
#!/usr/bin/env bash
bin_dir=`cd "$(dirname "$BASH_SOURCE[0]")"; pwd`
AZ_INSTALLER=DEB "$bin_dir"/../../opt/az/bin/python3 -Im azure.cli "$@"
```
$BASH_SOURCE would return the path to the symlink, not the actual path... so `../../opt` will fail.  

This works

```
#!/usr/bin/env bash
AZ_INSTALLER=DEB /opt/az/bin/python3 -Im azure.cli "$@"
```

**Comment by AlecWolman-msft** [comment]
Awesome find!  Thanks!

-Alec

**Comment by jiasli** [comment]
Thanks @Chuxel, but according to the output @AlecWolman-msft provided, `az` on the `PATH` is not a symlink.

```
% which az
/usr/bin/az
```

and `runpy` can be imported successfully：

```
% /opt/az/bin/python3 -c "import runpy; print(runpy.file)"
/opt/az/lib/python3.10/runpy.py
```

@AlecWolman-msft, does it work if you directly run 

```
/opt/az/bin/python3 -m azure.cli --version
```

**Comment by beautysleep-at-JLR** [comment]
Could [this ](https://stackoverflow.com/a/75133478/14843373) be ther bug cause? Users creating poorly/confictingly named files in their own python projects.

**Comment by AlecWolman-msft** [comment]
I can no longer repro this bug.  I don't know what changed, but it is working fine now.
