### ISSUE TITLE
Required Parameters in az vm delete

### ISSUE THREAD

**Issue by arjuntheguru** [Azure/azure-cli#23379]
In the documentation, it is specified that --resource-group -g and --name -n are optional parameters despite being required parameters. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-delete)
* Content Source: [latest/docs-ref-autogen/vm.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
Please note that for the `az vm delete` command, you can pass in `--resource-group`, `--name` or `--ids`.
See the help examples of `az vm delete -h` for details:
```pwsh
Examples
    Delete a VM without a prompt for confirmation.
        az vm delete -g MyResourceGroup -n MyVm --yes


    Delete all VMs in a resource group.
        az vm delete --ids $(az vm list -g MyResourceGroup --query "[].id" -o tsv)
```
So `--resource-group`, `--name` are not required parameters
