### ISSUE TITLE
Not able to use wildcard * while checking a specific resource group name with * wildcard pattern

### ISSUE THREAD

**Issue by onenessboy** [Azure/azure-cli#23371]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
```
 if [ $(az group exists --name *tes*) = true ]; then
      echo "resource group exist"
 fi
```

**Describe the bug**
```
 ERROR: Operation returned an invalid status 'Bad Request'
sh: false: unknown operand
```
**To Reproduce**
Only its allowed full name of resource group , but not wildcard patterns like * 
for example, if we have resource groups in our subscription like 
1) test
2) testresourcegroup
3) webapp
4) dbresource group

I want az group exist to find only resource group if its name contain test in it. ie. 
we should get output as 
```
test
testresourcegroup
```

**Expected behavior**
It should list all resource groups where resource group name contains` '`test'` `in its name

**Environment summary**
bash

**Additional context**

**Comment by yonzhan** [comment]
ARM

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
This requires the REST service [resource-groups/check-existence](https://docs.microsoft.com/en-us/rest/api/resources/resource-groups/check-existence) to support wildcard * for resource group name

**Comment by onenessboy** [comment]
> 

Hi @zhoxing-ms  

can you please clarify what I need to do.. I need to use Rest api ? 
Can you me one working example please

**Comment by zhoxing-ms** [comment]
@onenessboy No, you don't need to do anything. I mean that REST service doesn't support this feature at present, so we need our Azure service team to look this issue

**Comment by zhoxing-ms** [comment]
@tjegbejimba Could you please help have a look at this feature request?

**Comment by navba-MSFT** [comment]
@onenessboy Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We will provide an update on this shortly.

**Comment by navba-MSFT** [comment]
@onenessboy I believe you are trying to list the resource group names which contains a particular string pattern in it. Could you please test with the below command and see if that helps ?

>az group list --query "[?contains(name,'TestName')]" --output table

Replace the `TestName` in the above command before executing it. Hope this helps.

**Comment by onenessboy** [comment]
> @onenessboy I believe you are trying to list the resource group names which contains a particular string pattern in it. Could you please test with the below command and see if that helps ?
> 
> > az group list --query "[?contains(name,'TestName')]" --output table
> 
> Replace the `TestName` in the above command before executing it. Hope this helps.

Hi @navba-MSFT 

Thanks for reply, 

I tried something like below 
`az group list --query "[?name.contains(@,'clb')]"`

It should return me only 2 resource group names, but its listing all resource group...  here that clb is part of resource group name. I cant give full name of resource group as part of automation, we searching for some keywords and filter out resource groups.

Can you please Investigate from your end.

**Comment by navba-MSFT** [comment]
@onenessboy Interestingly, the same command works fine for me. It ONLY lists the RG which has the keyword in its name. (see below example for **bas** keyword). It doesn't list other resource groups. I am using 2.38 version of Azure CLI. Could you please check the version of CLI you are using ? then update to the [most recent CLI version ](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli)and check if that helps.

>az group list --query "[?contains(name,'**bas**')]" --output table
>
>Name                                 Location
>------------------------------  ----------
>centralus_basic                   centralus
windows_centralus_basic   centralus
magbasic_group                 centralus
sini-Databases                    westus2
shar-Databases                  westus2
shs-bastion-idLab             westus2
ba-Databases                   westus2
ar-Databases                    westus2
num-Databases                 westus2
avbasf                               eastus
Databases-Res                   westus2

**Comment by onenessboy** [comment]
> @onenessboy Interestingly, the same command works fine for me. It ONLY lists the RG which has the keyword in its name. (see below example for **bas** keyword). It doesn't list other resource groups. I am using 2.38 version of Azure CLI. Could you please check the version of CLI you are using ? then update to the [most recent CLI version ](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli)and check if that helps.
> 
> > az group list --query "[?contains(name,'**bas**')]" --output table
> > Name                                 Location
> > 
> > centralus_basic                   centralus
> > windows_centralus_basic   centralus
> > magbasic_group                 centralus
> > sini-Databases                    westus2
> > shar-Databases                  westus2
> > shs-bastion-idLab             westus2
> > ba-Databases                   westus2
> > ar-Databases                    westus2
> > num-Databases                 westus2
> > avbasf                               eastus
> > Databases-Res                   westus2

Hi @navba-MSFT 

Hmm, It what worked was 

`az group list --query "[?name.contains(@,'te') && managedBy == null]" `

because some of resource group managed by Microsoft which I dont want to filter..

hence closing the issue.. thanks for help
