### ISSUE TITLE
Release of Microsoft.Authorization 2022-04-01

### ISSUE THREAD

**Issue by zhihaoxue** [Azure/azure-cli#23372]
### Related command
az role

### Resource Provider
Microsoft.Authorization

### Description of Feature or Work Requested
Request CLI team to upgrade the Az CLI to start consuming the API version 2022-04-01 for role assignment, role definition and deny assignment operations
No behavior changes.

### Minimum API Version Required
2022-04-01

### Swagger PR link
https://github.com/Azure/azure-rest-api-specs/pull/19937

### Target Date
July/August

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This requires migration to [`azure-mgmt-authorization`](https://pypi.org/project/azure-mgmt-authorization/) Track 2 SDK.
