### ISSUE TITLE
The subscription of 'xxx' does not exist or has more than one match in cloud 'AzureCloud'.

### ISSUE THREAD

**Issue by guybartal** [Azure/azure-cli#2339]
I have two subscription with name "Microsoft Azure Sponsorship" in my account,
I get this error: The subscription of 'xxx' does not exist or has more than one match in cloud 'AzureCloud'.
when trying to set subscription using subscription id:
az account set --subscription "xxx"
while xxx is the subscription id.

**Comment by derekbekoe** [comment]
Does it appear in `az account list`?

**Comment by guybartal** [comment]
yes

**Comment by yugangw-msft** [comment]
@guybartal, to confirm, using subscription id with `az account set -s ` still  doesn't work out?

**Comment by yugangw-msft** [comment]
please reactivate with more information

**Comment by grgarcia-ms** [comment]
This is also happening to us with our SPs on our tests!
@yugangw-msft

**Comment by pgampe** [comment]
Workaround: run `az account clear` once to fix the issue
