### ISSUE TITLE
How to install Azure CLI 2.0 on Windows

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/azure-cli#2340]
I followed official instructions and got the 0.10.9 version. 

`pip install --upgrade azure-cli` also did not help.

**Comment by derekbekoe** [comment]
0.10.9 does not exist for Azure CLI 2.0.
Looks like you're running Azure CLI 1.0 - https://www.npmjs.com/package/azure-cli.

To run 2.0, use `az` instead of `azure`.

**Comment by philskents** [comment]
What error do you get when running "pip install ..."?

**Comment by lmiroslaw** [comment]
I turned out there is a conflict between Azure CLI and Azure Cross Platform Command Interface. I uninstalled both of them and installed Azure CLI again. It worked.
