### ISSUE TITLE
az aks install-cli failed

### ISSUE THREAD

**Issue by winsonluo** [Azure/azure-cli#23405]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az aks install-cli

**Describe the bug**
when run install cli there is error blow:
Downloading client to "/usr/local/bin/kubectl" from "https://mirror.azure.cn/kubernetes/kubectl/v1.24.3/bin/darwin/amd64/kubectl"
Connection error while attempting to download client (HTTP Error 404: Not Found)

**Environment summary**
macOS Monterey Apple M1 Pro
azure-cli  2.38.0

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@winsonluo Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@winsonluo For the stable kubectl  version 1.24.3, I see just Linux and Windows here. hence the error.

https://mirror.azure.cn/kubernetes/kubectl/v1.24.3/bin/

![image](https://user-images.githubusercontent.com/57353862/182533341-de09223d-8c31-4b41-a008-2d8190a5abc9.png)


_**Action Plan:**_
The following methods exist for installing kubectl on macOS. You could follow any one of the below steps:

[Install kubectl binary with curl on macOS](https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/#install-kubectl-binary-with-curl-on-macos)
[Install with Homebrew on macOS](https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/#install-with-homebrew-on-macos)
[Install with Macports on macOS](https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/#install-with-macports-on-macos)

Hope this helps. Awaiting your reply.

**Comment by winsonluo** [comment]
yes, installed kubectl via Homenrew!

**Comment by navba-MSFT** [comment]
@winsonluo Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
