### ISSUE TITLE
Add a field: cloud name in the azure cli client-side telemetry as part of Azure CLI command execution

### ISSUE THREAD

**Issue by harneetvirk** [Azure/azure-cli#23409]
**Related command**

Add a field: cloud name in the azure cli client-side telemetry as part of Azure CLI command execution

**Is your feature request related to a problem? Please describe.**

As of now, we have no way to track the usages of extension in different clouds.

**Describe the solution you'd like**

Since azure cli does collect some basic telemetry. Is it possible if azure cli can also collect the cloud name as one additional dimension where it is running from? That can help understand the usage of the CLI across different clouds.

**Describe alternatives you've considered**

Add a new property for all cli commands, leveraging telemetry.add_extension_event() function to add custom info only for a specific extension. Almost all of the commands need to be updated to start sending the cloud name as new dimension in the telemetry.

**Additional context**

**Comment by yonzhan** [comment]
add cloudname in telemetry
