### ISSUE TITLE
`az functionapp github-actions add` creates workflow files that fail for java apps 

### ISSUE THREAD

**Issue by StrawnSC** [Azure/azure-cli#23417]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

`az functionapp github-actions add` 

**Describe the bug**

See title. The GitHub action that's created for java function apps always fails to run 

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by StrawnSC** [comment]
This will be fixed by https://github.com/Azure/azure-cli/pull/23375. I just created this issue for tracking purposes. In the meantime customers can work around this problem by manually editing the workflow file like so: 
- open your workflow file in GitHub by navigating to the `.github/workflows` directory. The workflow should be named in the form `<branch>_<app_name>.yaml`
-  Under the `env:` section, change the value corresponding to `POM_FUNCTIONAPP_NAME` to the correct functionapp name in your project's pom.xml file. This name should be the text in between`<functionAppName>` and `</functionAppName>` in your pom

**Comment by yonzhan** [comment]
route to CXP team
