### ISSUE TITLE
unable to auth

### ISSUE THREAD

**Issue by hcary** [Azure/azure-cli#23415]
## Describe the bug

**Command Name**
``

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
macOS-12.4-x86_64-i386-64bit, Darwin 21.5.0
Python 3.10.5
Installer: HOMEBREW

azure-cli 2.39.0

Extensions:
azure-devops 0.23.0
resource-graph 1.1.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
Please provide the detailed CLI command in description
