### ISSUE TITLE
Adding support for Per Rule Actions in Application Gateway Web application Firewall

### ISSUE THREAD

**Issue by sindhualuguvelli1** [Azure/azure-cli#23418]
### Resource Provider

Network (NRP)

### Description of Feature or Work Requested

We are adding support to enable customers to override the action to be applied when a rules matches. For example, if the default action for a rule is "Block" and Cx changes it to "Log", the request will not be blocked but a log entry will be added. We are supporting below 4 actions. If the Cx does not specify any override action then the default action will be applied.
Action supported.
1) AnomalyScoring
2) Allow
3) Block
4) Log

Azure-CLI should have the support to configure any of these actions for a given rule.
Here is a link to the design document for reference.
https://microsoft.sharepoint.com/:w:/r/teams/ApplicationGateway9/Shared%20Documents/WAF/Documents/PerRuleAction/PerRuleActions.docx?d=w9e3f37c827734373ba9643775094937b&csf=1&web=1&e=zo0Mr4 

### Minimum API Version Required

2022-05-01

### Swagger PR link

https://github.com/Azure/azure-rest-api-specs/pull/20027

https://github.com/Azure/azure-rest-api-specs/blob/network-2022-05-01/specification/network/resource-manager/Microsoft.Network/stable/2022-05-01/webapplicationfirewall.json

### Target Date

Target Date for this feature release is September 2022.

**Comment by yonzhan** [comment]
network

**Comment by necusjz** [comment]
As limited bandwidth, we plan to deliver it in the next sprint.

**Comment by necusjz** [comment]
@sindhualuguvelli1 Could you give me access to the mentioned design document? Thanks.

**Comment by sindhualuguvelli1** [comment]
[PerRuleActions (1).docx](https://github.com/Azure/azure-cli/files/9539278/PerRuleActions.1.docx)

@necusjz Uploaded the design document here.

**Comment by sindhualuguvelli1** [comment]
@necusjz Any update on this?

**Comment by necusjz** [comment]
> @necusjz Any update on this?

WIP and the same situation as https://github.com/Azure/azure-cli/issues/23936#issuecomment-1252580954.
