### ISSUE TITLE
For basic Sku firewall we need to make sure we include the Management NIC (Forced tunneling on by default)

### ISSUE THREAD

**Issue by Gizachew-Eshetie** [Azure/azure-cli#23429]
**Related command**

Please have a look at this PowerShell PR for the same requirement.
https://github.com/Azure/azure-powershell/pull/18916

**Describe the solution you'd like**

Please read this documentation about forced tunning.
https://docs.microsoft.com/en-us/azure/firewall/forced-tunneling

**Additional context**

Whenever we are creating a Basic Sku firewall, we need to make sure Management NIC is enabled by default. Making sure AzureFirewallManagementSubnet subnet and ManagementPublicIpAddress  should be provided.

**Comment by yonzhan** [comment]
@necusjz to estimate this request.

**Comment by necusjz** [comment]
@Gizachew-Eshetie, due to workload, we plan to develop it in the next sprint.
