### ISSUE TITLE
'az' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by andy26nash** [Azure/azure-cli#2342]
Tried to Installed on Windows 10 (148986).
Installed Python 3.5.3
ran pip install --user azure-cli with no errors.
Rebooted just in case Path needed to be updated but I get the above error when using CMD or PS prompt

Did get it working in Bash on Windows by following the Ubuntu installation steps.

**Comment by derekbekoe** [comment]
Have you added `%APPDATA%\PythonXY\Scripts` or `%APPDATA%\Python\PythonXY\Scripts` to your PATH?
See https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows

**Comment by andy26nash** [comment]
Yes they seem to be added by the Python install and python and pip work ok from the command line

PATH=...;C:\Users\anash\AppData\Local\Programs\Python\Python35\Scripts\; C:\Users\anash\AppData\Local\Programs\Python\Python35\;

**Comment by philskents** [comment]
The issue is the LOCAL part of those paths (Python hides its goodies in Roaming). add ";%APPDATA%\Python\PythonXY\Scripts" to the end of your PATH and all will be good (replace XY with the Python version eg. Python35)

**Comment by andy26nash** [comment]
Yes that fixed it. Thanks
