### ISSUE TITLE
Should the resourcegroup parameter be clarified?

### ISSUE THREAD

**Issue by keithmitworks** [Azure/azure-cli#23426]
Which resource group is this? The vnet, or the web app ? It should be specified.
"--resource-group -g
Name of resource group. You can configure the default group using az configure --defaults group=<name>"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cf5a035-926f-1cef-8335-963b497cbed8
* Version Independent ID: 296a49f5-bc7a-d56a-6fe2-914d276b2a9e
* Content: [az webapp vnet-integration](https://docs.microsoft.com/en-us/cli/azure/webapp/vnet-integration?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/vnet-integration.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/vnet-integration.yml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@keithmitworks The Resource Group parameter is primarily used to locate the webapp since that is the main command here but also uses it for the VNET as well. If your VNET is in a different resource group, you can then pass in the Resource ID instead for the VNET.

**Comment by keithmitworks** [comment]
> @keithmitworks The Resource Group parameter is primarily used to locate the webapp since that is the main command here but also uses it for the VNET as well. If your VNET is in a different resource group, you can then pass in the Resource ID instead for the VNET.

Thank you for the reply. I did determine myself that the webapp resource group was what was needed.
