### ISSUE TITLE
sql server ad-admin create fails with "ERROR: Operation returned an invalid status 'Accepted'"

### ISSUE THREAD

**Issue by dreeko** [Azure/azure-cli#23437]
**Related command**

```
az sql server ad-admin create \
  --display-name "{displayName}" \
  --resource-group "{resourceGroupName}" \
  --subscription "{subscriptionId}" \
  --object-id "{sqlAdminADGroupID}" \
  --server "{sqlServerName}" \
  --debug
```

**Describe the bug**

sql server ad-admin create fails with "ERROR: Operation returned an invalid status 'Accepted'"

With pipeline debugging enabled and the debug flag on the az command i can observe that the underlying HTTP call appears to succeed but the az tool cannot handle the ```202 Accepted``` Response from that call

**To Reproduce**

Execute ```az sql server ad-admin create```

**Expected behavior**

Call succeeds, the ad user nominated in the call is assigned as the AD Admin of the SQL Server, the result of the operation is printed to the console.

**Environment summary**

```executing azure pipeline AzureCLI task on microsoft hosted Ubuntu Agent
[section]Starting: AzureCLI
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
[command]/usr/bin/az --version
WARNING: You have 3 updates available. Consider updating your CLI installation with 'az upgrade'
azure-cli                         2.38.0 *
Please let us know how we are doing: https://aka.ms/azureclihats
core                              2.38.0 *
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
telemetry                          1.0.6 *
Extensions:
azure-devops                      0.25.0
Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1
Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'
Python (Linux) 3.10.5 (main, Jul  1 2022, 04:14:40) [GCC 9.4.0]
```

**Additional context**
```Request URL: 'https://management.azure.com/subscriptions/{subscription}/resourceGroups/{resourceGroup}/providers/Microsoft.Sql/servers/{serverName}/administrators/ActiveDirectory?api-version=2020-11-01-preview'```

The Azure Pipeline task currently executes with 2.38, We have also force updated the az cli version to 2.39 and the bug is also present in this version.

**Comment by yonzhan** [comment]
route to CXP team
