### ISSUE TITLE
Azure Advisory recommendation issue

### ISSUE THREAD

**Issue by Miti-Shah** [Azure/azure-cli#23434]
Hi , we have updated our setting on the resource as per advisory recommendation but when it got refreshed next , the recommendation is still there. what to do? @navba-MSFT
"Improve resiliency by migrating your Azure Cosmos DB accounts to continuous backup"
we have enabled continuous backup on cosmos DB around 48 hours ago.. but recommendation is still there

**Comment by yonzhan** [comment]
Advisory

**Comment by navba-MSFT** [comment]
@Miti-Shah Thanks for reaching out to us and reporting this issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
