### ISSUE TITLE
Need better error message for cli the sub command is not supplied: the following arguments are required: _subcommand

### ISSUE THREAD

**Issue by harneetvirk** [Azure/azure-cli#23430]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az storage blob
the following arguments are required: **_subcommand**

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs

az ml job
the following arguments are required: _subcommand

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs

**Describe the bug**

The cli command fails with a very vague message when the user does not supply the full command in CLI and fails with the following error:

the following arguments are required: **_subcommand**

**To Reproduce**

run `az storage blob`
or
run `az ml job`

**Expected behavior**

A better error message would have helped that shows the list of sub commands. 

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by navba-MSFT** [comment]
@harneetvirk Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@harneetvirk In order to get the command suggestions or list the available subcommands, You should run the command with `--help` argument. Considering a`z storage blob`  and `az ml job` and not complete commands, You will get the error message which says: _`the following arguments are required: _subcommand`_

See the output while running with the `--help` parameter.

```
C:\>az storage blob --help

Group
    az storage blob : Manage object storage for unstructured data (blobs).
       
Subgroups:
    copy                     : Manage blob copy operations. Use `az storage blob show` to check the
                               status of the blobs.
    immutability-policy      : Manage blob immutability policy.
    incremental-copy         : Manage blob incremental copy operations.
    lease                    : Manage storage blob leases.
    metadata                 : Manage blob metadata.
    service-properties       : Manage storage blob service properties.
    tag            [Preview] : Manage blob tags.
```

```
C:\>az ml job --help

Group
    az ml job : Manage Azure ML jobs.
        An Azure ML job executes a task against a specified compute target. You can configure jobs
        to scale out model training on Azure. Azure ML supports different job types with different
        capabilities. 

Commands:
    archive  : Archive a job.
    cancel   : Cancel a job.
    create   : Create a job.
    download : Download all job-related files.
    list     : List jobs in a workspace.
    restore  : Restore an archived job.
    show     : Show details for a job.
    stream   : Stream job logs to the console.
    update   : Update a job.
```

**Comment by harneetvirk** [comment]
yes, passing --help works, but the user needs to know the --help parameter also.

_Subcommand required does not seems to be a very user-friendly error message when the user does not know what the possible parameters are available to be supplied while running the CLI command.

**Comment by evelyn-ys** [comment]
Similar issue with #576

As https://github.com/Azure/azure-cli/issues/576#issuecomment-236698079 said, we could consider to make a change in cli core to override the behavior of `argparse`. Need time to investigate.

**Comment by jiasli** [comment]
See https://github.com/Azure/azure-cli/issues/19592
