### ISSUE TITLE
"az synapse pipeline show/list/create" considering activity type for activity "Fail" as "activity" which is leading to blank pipeline canvas

### ISSUE THREAD

**Issue by avnishsinghhh** [Azure/azure-cli#23441]
**Related command**
az synapse pipeline <show/list/create> --workspace-name <workspace name> --name <pipeline name>

**Describe the bug**
"az synapse pipeline <show/list/create>" considering activity type  for activity "Fail" as "activity" instead of "Fail" which is leading to blank pipeline canvas, however pipelines can be validated. Pipeline activities appears back once activity type is manually changed from "activity" to "Fail" in the JSON code

_**Updated:**
"typeProperties" are also loading as blank in this case which leads to validation failure._

**To Reproduce**
Execute "az synapse <show/list/create>" on pipeline having at least one "Fail" activity. Activity type will be marked as "activity" instead of "Fail" in results of "az sypanse <show/list>" command and pipeline canvas will appear blank on creating pipeline using "az synapse create" command.

**Expected behavior**
Pipeline should be created successfully and pipeline canvas should not be blank and show all the activities.

_**Updated:**
"typeProperties" should be populated._

**Environment summary**

**Install Method:** MSI

**CLI Version:**
azure-cli                         2.38.0 *
core                              2.38.0 *
telemetry                          1.0.6 *
Extensions:
import-export                      0.1.1
interactive                        0.4.5
Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

**OS:** Windows
**Shell:** Powershell

**Comment by SaurabhSharma-MSFT** [comment]
@avnishsinghhh We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@avnishsinghhh I could see the same behavior for "type" attribute and checking internally with the team, however I do not see any issues with "typeProperties" and it is getting populated correctly.
![image](https://user-images.githubusercontent.com/38112130/183194318-d75ccbbc-01e6-4861-899d-493b8cee2eaa.png)

**Comment by avnishsinghhh** [comment]
Looks like **typeProperties** are not loaded with "az synapse pipeline create" command however it is present in 'az synapse pipeline show/list' command:

![image](https://user-images.githubusercontent.com/6954444/183373935-18eae74e-5d18-40b9-b38d-d8e1202c8706.png)

**Comment by SaurabhSharma-MSFT** [comment]
@avnishsinghhh Fail activity related fix will be mostly rolled out in the month of October. For now, please call REST API to get correct activity type would be the workaround.

**Comment by avnishsinghhh** [comment]
Hi Saurabh,

I am already using REST API as a workaround for this and it works perfectly fine.

Thank You.
