### ISSUE TITLE
Getting supported images list for an Azure Batch pool fails with nondescript error

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-cli#23445]
## Describe the bug

**Command Name**
`az batch pool supported-images list`

**Errors:**
```
'NoneType' object has no attribute 'startswith'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az batch pool supported-images list --account-name {}`

## Environment Summary
```
Linux-5.4.0-1086-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.5
Installer: DEB

azure-cli 2.38.0 *

Extensions:
ai-examples 0.2.5
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@brandonh-msft Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@brandonh-msft Please run the below command and that should work.

>az batch pool supported-images list --account-endpoint https://MyBatchAccount.region.batch.azure.com --account-name MyBatchAccount

Hope this helps.
