### ISSUE TITLE
CLI | Trusted Launch as Default - New VM with minimal Inputs

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-cli#23440]
### Related command

- [az vm create --name 'vmname' --resource-group 'vm-rgname'](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create)
- [az vmss create --name 'vmssname' --resource-group 'rgname'](https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-create)

### Resource Provider

Microsoft.Compute/virtualMachines

### Description of Feature or Work Requested

# Trusted Launch as Default
As part of making compute layer secure for customers to deploy workloads, request is to make [Trusted Launch](https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch) (GA Date: November 2021) as default deployment option in CLI. Following changes will need to be made for same:

## Scenario 1 - User runs `az vm create` with minimal parameters.

Present Behavior | Updated Behavior post change
-|-
New VM with minimal parameters: <ol><li>User runs command `az vm create --name vmname --resource-group rgname`.<li>User gets prompted for value of `--image` parameter. User provides specific image ID or URNAlias<li>CLI creates VM with size `Standard_DS1_v2`.</li></ol> | Updated default parameters: <ol><li>User runs command `az vm create --name vmname --resource-group rgname`.<li>CLI takes default value for `--image` parameter as **MicrosoftWindowsServer:WindowsServer:2022-datacenter-azure-edition:latest** i.e., no prompt for user for value of `--image` parameter.<li>Following parameters are set by default:<ul><li>`--enable-secure-boot` with value **true**<li>`--enable-vtpm` with value **true**<li>`--security-type` with value **TrustedLaunch**</ul><li>CLI creates VM with size `Standard_DS1_v2` and default values for parameters mentioned in Step 2 & 3</ol>

## Scenario 2 - User runs `az vmss create` with minimal parameters.

Present Behavior | Updated Behavior post change
-|-
New VMSS with minimal parameters: <ol><li>User runs command `az vmss create --name vmssname --resource-group rgname`.<li>User gets prompted for value of `--image` parameter. User provides specific image ID or URNAlias<li>CLI creates VMSS with size `Standard_DS1_v2`.</li></ol> | Updated default parameters: <ol><li>runs command `az vmss create --name vmssname --resource-group rgname`.<li>CLI takes default value for `--image` parameter as **MicrosoftWindowsServer:WindowsServer:2022-datacenter-azure-edition:latest** i.e., no prompt for user for value of `--image` parameter.<li>Following parameters are set by default:<ul><li>`--enable-secure-boot` with value **true**<li>`--enable-vtpm` with value **true**<li>`--security-type` with value **TrustedLaunch**</ul><li>CLI creates VMSS with size `Standard_DS1_v2` and default values for parameters mentioned in Step 2 & 3</ol>

>**NOTE**: Please review limitations [Trusted Launch VM Limitations](https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch#limitations) to assess any impact for CLI users.

### Minimum API Version Required

2021-11-01

### Swagger PR link

[Compute Swagger 2021-11-01](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2021-11-01/compute.json)

### Request Example

- [Create VM with UEFI Settings JSON](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2021-11-01/examples/compute/CreateAVmWithUefiSettings.json)
- [Create VMSS with UEFI Settings JSON](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2021-11-01/examples/compute/CreateAScaleSetWithUefiSettings.json)

### Target Date

2023-11-15 (Ignite 2023)

### Additional context

- TLVM-as-default for Azure Portal is already implemented in April 2023.
- **Change in request since October 2022 (Warning message implementation)**: NA

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@AjKundnani In fact, when users only execute the `az vm create --name vmname --resource-group rgname` command without other parameters, CLI will prompt `incorrect usage: --image IMAGE | --attach-os-disk DISK`
This is because at present, users can also create a VM by attaching the OS disk without using the `--image` parameter, such as execute `vm create -g {rg} -n vm2 --attach-os-disk {disk_uri} --os-type linux --use-unmanaged-disk`. And it is similar for VMSS.

So I want to confirm whether these default behaviors only take effect when the user has neither passed in `--image` parameter nor `--attach-os-disk` parameter?

**Comment by AjKundnani** [comment]
> @AjKundnani In fact, when users only execute the `az vm create --name vmname --resource-group rgname` command without other parameters, CLI will prompt `incorrect usage: --image IMAGE | --attach-os-disk DISK` This is because at present, users can also create a VM by attaching the OS disk without using the `--image` parameter, such as execute `vm create -g {rg} -n vm2 --attach-os-disk {disk_uri} --os-type linux --use-unmanaged-disk`. And it is similar for VMSS.
> 
> So I want to confirm whether these default behaviors only take effect when the user has neither passed in `--image` parameter nor `--attach-os-disk` parameter?

That is correct, for this scenario we assume user has not passed values to parameter `--image` nor for `--attach-os-disk`. For scenario where users will pass specific values (and other scenarios), I'll be submitting different request.

**Comment by AjKundnani** [comment]
@zhoxing-ms - Based on other initiatives, updated default OS Image to Windows Server 2022 Azure Edition. Will not impact notification message, it will be needed during implementation.

**Comment by zhoxing-ms** [comment]
@AjKundnani OK, got it. Please also update the default OS Image in the feature description~

**Comment by yanzhudd** [comment]
Hi @AjKundnani 
could you please help review this [change](https://github.com/Azure/azure-cli/pull/27635)?

**Comment by AjKundnani** [comment]
> Hi @AjKundnani could you please help review this [change](https://github.com/Azure/azure-cli/pull/27635)?

@yanzhudd - The condition in validator.py looked good to me. Will validate further during bug bash.
