### ISSUE TITLE
CLI | Trusted Launch as Default - VM/VMSS Deployment with Marketplace Image

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-cli#23450]
### Related command

- [az vm create --name 'vmname' --resource-group 'vm-rgname' --image 'imagealias'](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create)
- [az vmss create --name 'vmssname' --resource-group 'rgname' --image 'imagealias'](https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-create)
- [az vm image list](https://docs.microsoft.com/en-us/cli/azure/vm/image?view=azure-cli-latest#az-vm-image-list)

### Resource Provider

Microsoft.Compute/virtualMachines

### Description of Feature or Work Requested

# Trusted Launch as Default
As part of making compute layer secure for customers to deploy workloads, request is to make [Trusted Launch](https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch) (GA Date: November 2021) as default deployment option in CLI. Following changes will need to be made for same:

## Scenario 1 - User runs query using `az vm image list` minimal parameters
[Aliases.json](https://github.com/Azure/azure-rest-api-specs/blob/main/arm-compute/quickstart-templates/aliases.json) will need to be updated for supporting Generation 2 VM Images.

Alias | Current URN | Requested URN Update
-|-|-
CentOS | OpenLogic:CentOS:7.5:latest | OpenLogic:CentOS:7_5-gen2:latest
Debian | Debian:debian-10:10:latest | Debian:debian-10:10-gen2:latest
Flatcar | kinvolk:flatcar-container-linux-free:stable:latest | kinvolk:flatcar-container-linux-free:stable-gen2:latest
RHEL | Redhat:RHEL:7-LVM:latest | RedHat:RHEL:7lvm-gen2:latest
UbuntuLTS | Canonical:UbuntuServer:18.04-LTS:latest | Canonical:UbuntuServer:18_04-lts-gen2:latest
Win2019Datacenter | MicrosoftWindowsServer:WindowsServer:2019-Datacenter:latest | MicrosoftWindowsServer:WindowsServer:2019-datacenter-gensecond:latest
Win2016Datacenter | MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest | MicrosoftWindowsServer:WindowsServer:2016-datacenter-gensecond:latest
Win2022Datacenter | MicrosoftWindowsServer:WindowsServer:2022-Datacenter:latest | MicrosoftWindowsServer:WindowsServer:2022-datacenter-g2:latest

Following images do **NOT** require change in [Aliases.json](https://github.com/Azure/azure-rest-api-specs/blob/main/arm-compute/quickstart-templates/aliases.json) file:

Alias | Current URN | No Change to URN
-|-|-
Win2012R2Datacenter | MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest | *No Change* 
Win2012Datacenter | MicrosoftWindowsServer:WindowsServer:2012-Datacenter:latest | *No Change* MicrosoftWindowsServer:WindowsServer:2012-Datacenter:latest
Win2008R2SP1 | MicrosoftWindowsServer:WindowsServer:2008-R2-SP1:latest | *No Change* MicrosoftWindowsServer:WindowsServer:2008-R2-SP1:latest
Win2022AzureEditionCore | MicrosoftWindowsServer:WindowsServer:2022-datacenter-azure-edition-core:latest | *No change* MicrosoftWindowsServer:WindowsServer:2022-datacenter-azure-edition-core:latest
openSUSE-Leap | SUSE:opensuse-leap-15-3:gen2:latest | *No change* SUSE:opensuse-leap-15-3:gen2:latest
SLES | SUSE:sles-15-sp3:gen2:latest | *No change*  SUSE:sles-15-sp3:gen2:latest

## Scenario 2 - User creates VM with command `az vm create` and imageAlias

Present Behavior | Updated Behavior post change
-|-
New VM with image parameter: <ol><li>User runs command `az vm create --name vmname --resource-group rgname --image imagealias --size vmsize`.<li>If `--size` parameter is not specified, CLI creates VM with **Standard_DS1_v2** VM SIze.</li></ol> | Updated default parameters: <ol><li>User runs command `az vm create --name vmname --resource-group rgname --image imagealias --size vmsize`<li>CLI will set default VM Size **Standard_DS1_v2** if  no size specified,<li>Following parameters are set by default:<ul><li>`--enable-secure-boot` with value **true**<li>`--enable-vtpm` with value **true**<li>`--security-type` with value **TrustedLaunch**</li></ul><li>API will return error in following scenarios:<ul><li>Image Alias is Win2012R2Datacenter or Win2012Datacenter or Win2008R2SP1 - As these OS versions are deprecated or near deprecation they do not support Trusted Launch.<li>VM Size does not supports Gen2 or Trusted Launch.</li></ul></ol>

## Scenario 3 - User creates VMSS with command `az vmss create` and image alias

Present Behavior | Updated Behavior post change
-|-
New VMSS with image parameter: <ol><li>User runs command `az vmss create --name vmssname --resource-group rgname --image imagealias --size vmsize`.<li>If `--size` parameter is not specified, CLI creates VMSS with **Standard_DS1_v2** VM SIze.</li></ol> | Updated default parameters: <ol><li>User runs command `az vmss create --name vmssname --resource-group rgname --image imagealias --size vmsize`<li> CLI will set VM size as  **Standard_DS1_v2** If no size specified,<li>Following parameters are set by default:<ul><li>`--enable-secure-boot` with value **true**<li>`--enable-vtpm` with value **true**<li>`--security-type` with value **TrustedLaunch**</li></ul><li>API will return error in following scenarios:<ul><li>Image Alias is Win2012R2Datacenter or Win2012Datacenter or Win2008R2SP1 - As these OS versions are deprecated or near deprecation they do not support Trusted Launch.<li>VM Size does not supports Gen2 or Trusted Launch.</li></ul></ol>

## Scenario 4 - User creates VM with command `az vm create` and image URN

Present Behavior | Updated Behavior post change
-|-
New VM with image parameter: <ol><li>User runs command `az vm create --name vmname --resource-group rgname --image imageURN --size vmsize`.<li>If `--size` parameter is not specified, CLI creates VM with **Standard_DS1_v2** VM SIze.</li></ol> | Updated default parameters: <ol><li>User runs command `az vm create --name vmname --resource-group rgname --image imageURN --size vmsize`<li>CLI will set default VM Size **Standard_DS1_v2** if  no size specified,<li>**Check**: CLI will check if input URN is Gen2 OS image using [Virtual Machine Images - GET API](https://learn.microsoft.com/rest/api/compute/virtual-machine-images/get).<li>Conditions:<ul><li>If hyperVGeneration for OS image is **v2** then following parameters are set by default:<ul><li>`--enable-secure-boot` with value **true**<li>`--enable-vtpm` with value **true**<li>`--security-type` with value **TrustedLaunch**</li></ul><li>If hyperVGeneration for OS image is **v1** securityType is set to **Standard** with the following message displayed and Trusted Launch default is not applied. `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`</li></ul><li>API will return error in following scenarios:<ul><li>Image URN provided is Gen2 but not TrustedLaunchSupported.<li>VM Size does not supports Gen2 or Trusted Launch.</li></ul></ol>

## Scenario 5 - User creates VMSS with command `az vmss create` and image URN

Present Behavior | Updated Behavior post change
-|-
New VMSS with image parameter: <ol><li>User runs command `az vmss create --name vmssname --resource-group rgname --image imageURN --size vmsize`.<li>If `--size` parameter is not specified, CLI creates VMSS with **Standard_DS1_v2** VM SIze.</li></ol> | Updated default parameters: <ol><li>User runs command `az vmss create --name vmssname --resource-group rgname --image imageURN  --size vmsize`<li>CLI will set default VM Size **Standard_DS1_v2** if  no size specified,<li>**Check**: CLI will check if input URN is Gen2 OS image using [Virtual Machine Images - GET API](https://learn.microsoft.com/rest/api/compute/virtual-machine-images/get).<li>Conditions:<ul><li>If hyperVGeneration for OS image is **v2** then following parameters are set by default:<ul><li>`--enable-secure-boot` with value **true**<li>`--enable-vtpm` with value **true**<li>`--security-type` with value **TrustedLaunch**</li></ul><li>If hyperVGeneration for OS image is **v1** securityType is set to **Standard** with the following message displayed and Trusted Launch default is not applied. `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`</li></ul><li>API will return error in following scenarios:<ul><li>Image URN provided is Gen2 but not TrustedLaunchSupported.<li>VM Size does not supports Gen2 or Trusted Launch.</li></ul></ol>

>**NOTE**: Please review limitations [Trusted Launch VM Limitations](https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch#limitations) to assess any impact for CLI users.

### Minimum API Version Required

2021-11-01

### Swagger PR link

[Compute Swagger 2021-11-01](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2021-11-01/compute.json)

### Request Example

- [Create VM with UEFI Settings JSON](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2021-11-01/examples/compute/CreateAVmWithUefiSettings.json)
- [Create VMSS with UEFI Settings JSON](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2021-11-01/examples/compute/CreateAScaleSetWithUefiSettings.json)

### Target Date

2022-10-10

### Additional context

- **Change in request since October 2022 (Warning message implementation)**:
   - VM Size check using Resource SKU LIST API request is removed.
   - Legacy OS Images WS2012 and WS2008R2 are not getting updated in Aliases.json.
   - Server / API side error message added.
   - OS image check scoped to hyperVGeneration = v2
- Breaking change process is approved to proceed with this implementation.
- Error message from API: 

Id | PS/CLI Scenario | Existing API Error Message | Updated API Error Message (November 2023)
-|-|-|-
1 | Input VM Size is Gen1-Only and PS/CLI enables TL. | Not Available | The VM size '<VM Size Name> is not supported for creation of VMs and Virtual Machine Scale Set with 'TrustedLaunch' security type. For more information, see https://aka.ms/TrustedLaunch-FAQ
2 | Input VM Size is Non-TL supported. PS/CLI TLaD enables TL for deployment | The VM size 'Standard_A4_v2' is not supported for creation of VMs and Virtual Machine Scale Set with 'TrustedLaunch' security type. | The VM size '<VM Size Name> is not supported for creation of VMs and Virtual Machine Scale Set with 'TrustedLaunch' security type. For more information, see https://aka.ms/TrustedLaunch-FAQ
3 | Input PIR Gen2 OS Image is not TL supported. PS/CLI enables TL for deployment. | Use of TrustedLaunch setting is not supported for the provided image. | Use of TrustedLaunch setting is not supported for the provided image “<image name>”. Please select Trusted Launch Supported Gen2 OS Image. For more information, see https://aka.ms/TrustedLaunch-FAQ

**Comment by AjKundnani** [comment]
Related closely to request #23440

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@AjKundnani Regarding this requirement, I have some concerns about the need to request REST [Resource SKU List API](https://docs.microsoft.com/en-us/rest/api/compute/resource-skus/list), because it mainly has three problems:

1. It's performance is too slow, and the response time often **exceeds 110 seconds**, which has a big impact on the command execution speed
2. The data size returned is too large, accounting for about **82+MB**, which will seriously occupy the user's bandwidth resources
3. It returns too much data (about 1.77w+), which leads to too much content in the debug log. It will occupy the space of users who have enabled the debug log, and it will make it difficult for us to troubleshoot problems related to `az vm/vmss create` through debug log.

**Comment by AjKundnani** [comment]
> 

@zhoxing-ms - Can we cache the JSON response similar to [Aliases.json](https://github.com/Azure/azure-rest-api-specs/blob/main/arm-compute/quickstart-templates/aliases.json) or locally as part of CLI package and make reference to same?

**Comment by zhoxing-ms** [comment]
@AjKundnani Personally, I think there are many problems with this solution: 
Please note that since the data returned by this API is too large **(size: 82+MB, count: 1.77w+)**
Even if the cache files is used, some problems still exist, such as: slow response, digestion of bandwidth resources, occupation of space, and the impact on the debug log. 
Moreover, because the number of SKUs is too large, this will lead to the challenge of data synchronization and consistency.

In fact, I personally think a more reasonable solution is that the service provides a GET rest API, which can support us to query the information of a single SKU. 
In this way, we can avoid the problem of returning too much data by requesting the list API to query all SKUs.

**Comment by AjKundnani** [comment]
> @AjKundnani Personally, I think there are many problems with this solution: Please note that since the data returned by this API is too large **(size: 82+MB, count: 1.77w+)** Even if the cache files is used, some problems still exist, such as: slow response, digestion of bandwidth resources, occupation of space, and the impact on the debug log. Moreover, because the number of SKUs is too large, this will lead to the challenge of data synchronization and consistency.
> 
> In fact, I personally think a more reasonable solution is that the service provides a GET API, which can support us to query the information of a single SKU. In this way, we can avoid querying the LIST API to obtain all SKU data _(the amount of data is too large)_

@zhoxing-ms - I was testing using below PS cmdlet which is using same API for VM Size capabilities:
`Get-AzComputeResourceSku -Location WestUS -Debug | where {$_.Name -eq "Standard_GS4-4"} | select -ExpandProperty Capabilities`
The command took around 3 seconds to complete, I'll share debug log offline.

**Comment by zhoxing-ms** [comment]
> If VM Size and Image both supports Generation 2 and Trusted Launch - Following parameters are set by default:
--enable-secure-boot with value true
--enable-vtpm with value true
--security-type with value TrustedLaunch

Does this request need to support `--disable-integrity-monitoring` like request #23476?

**Comment by AjKundnani** [comment]
> > If VM Size and Image both supports Generation 2 and Trusted Launch - Following parameters are set by default:
> > --enable-secure-boot with value true
> > --enable-vtpm with value true
> > --security-type with value TrustedLaunch
> 
> Does this request need to support `--disable-integrity-monitoring` like request #23476?

@zhoxing-ms - No it does not need to support `--disable-integrity-monitoring`. When SecureBoot and vTPM are set to true, Integrity monitoring should also be enabled by default.

In the request #23476? we've SecureBoot disabled hence Integrity monitoring is disabled as well.

**Comment by zhoxing-ms** [comment]
@AjKundnani Got it, thanks~ By the way, may I ask why sets `--enable-secure-boot` as `False` in https://github.com/Azure/azure-cli/issues/23476 ?

**Comment by AjKundnani** [comment]
> @AjKundnani Got it, thanks~ By the way, may I ask why sets `--enable-secure-boot` as `False` in #23476 ?

@zhoxing-ms - Existing disk or image OS can be deployed in a way which doesnt supports SecureBoot and if API enables SecureBoot for un-supported OS, the VM will not boot up. To avoid these broken boot process, requested to keep it disabled for existing disks and images.

**Comment by zhoxing-ms** [comment]
> In fact, I personally think a more reasonable solution is that the service provides a GET API, which can support us to query the information of a single SKU. In this way, we can avoid querying the LIST API to obtain all SKU data (the amount of data is too large)

May I ask what is the current status for the SKU GET API? If it is not ready at present, because the SKU LIST API responds slowly and returns many irrelevant data. can we simplify the scenario of printing warning log to avoid calling the [Resource SKU List API](https://docs.microsoft.com/en-us/rest/api/compute/resource-skus/list)?

**Comment by AjKundnani** [comment]
> > In fact, I personally think a more reasonable solution is that the service provides a GET API, which can support us to query the information of a single SKU. In this way, we can avoid querying the LIST API to obtain all SKU data (the amount of data is too large)
> 
> May I ask what is the current status for the SKU GET API? If it is not ready at present, because the SKU LIST API responds slowly and returns many irrelevant data. can we simplify the scenario of printing warning log to avoid calling the [Resource SKU List API](https://docs.microsoft.com/en-us/rest/api/compute/resource-skus/list)?

@zhoxing-ms - It's not committed for Zn semester, if we can try with location filter please? Or alternatively with PS cmdlet `(Get-AzComputeResourceSku -Location westus2 | Where-Object {$psitem.Name -eq "Standard_NC12s_v2"}).Capabilities` If you can check the debug log for above cmdlet and API used?

**Comment by zhoxing-ms** [comment]
@AjKundnani Even if the query results are filtered by location, there are still a lot of irrelevant data returned by LIST API and the query time still takes several seconds.
In addition, I have another concern: may I ask whether the LIST SKU API has hot issues? For example, the distribution of SKUs in location is uneven. Some locations contain a large number of SKUs, which will result in long service response times and consume a large amount of user's bandwidth.

Since the `az vm create` command is very core and widely used, could we print the warning log with simpler logic before the SHOW SKU API is completed, and then improve the logic of the warning log after SHOW SKU API is ready?

**Comment by zhoxing-ms** [comment]
@AjKundnani For the simpler logic, could we just consider whether the image can support Gen 2 and Trusted Launch for the time being, without considering VM size? 
Because we only provide warning logs first, I imagine that even if our warning logs are inaccurate, they will not have a direct impact on users' business.
For example: we may recommend users to enable Trusted Launch when the VM size does not support Trusted Launch, then users will receive an exception returned by API after trying to enable Trusted Launch. 
Compared with the overall impact on the performance and bandwidth of `az vm/vmss create` command, I think this is not a big problem. what do you think of it?

**Comment by AjKundnani** [comment]
> MicrosoftWindowsServer:WindowsServer:2019-datacenter-gen2:latest

@zhoxing-ms - The time taken for CRP API to return error is ~5 seconds, if the resource list API with filter is taking longer? Additionally the API error does not includes link or how to correct the error for user, if that will be ok from user experience?

```
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"The selected VM size 'Standard_D2_v3' cannot boot Hypervisor Generation '2'. If this was a Create operation please check that the Hypervisor Generation of the Image matches the Hypervisor Generation of the selected VM Size. If this was an Update operation please select a Hypervisor Generation '2' VM Size.\"\r\n  }\r\n}"}]}}
```

**Comment by zhoxing-ms** [comment]
> Scenario 1 - User runs query using az vm image list minimal parameters

@AjKundnani I'd like to confirm with you my opinion about this point. For changing the image returned by the `az vm image list` command from Gen 1 to Gen, I think it is unnecessary to print notification message in advance. Because the change of the data returned by the list command is a normal change rather than a breaking change, the breaking change occurs only when the returned data structure changes

**Comment by zhoxing-ms** [comment]
@AjKundnani Hi, I'd like to confirm with you the core scenarios of printing the notification message.

- When users deploy the Gen 1 VM, CLI will print the following notification message to recommend them to use Trusted Launch VMs:
> Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch

Regarding this message, do we need to also recommend users to use Gen 2, as we do for `az disk create`? PR link: #23942
> Please consider upgrading security for your VM resources by using Gen 2 OS image and Trusted Launch security type. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch

- When users deploy the Gen 2 VM without enabling Trusted launch, if the image they use supports Trusted launch, CLI will print the following notification message to recommend them to enable Trusted Launch:
> Starting xx/xx/xxxx az vmss create command will deploy Trusted Launch VM by default. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch

Please check my understanding. Please feel free to let me know if there are any mistakes or omissions~

**Comment by AjKundnani** [comment]
@zhoxing-ms - Adding comments in-line



> * When users deploy the Gen 1 VM, CLI will print the following notification message to recommend them to use Trusted Launch VMs:

Correct


> Regarding this message, do we need to also recommend users to use Gen 2, as we do for `az disk create`? PR link: #23942

No, we should stay with simplified message without adding any switch or parameter details. Adding switch details for `--hyper-v-generation V2` is causing some confusion, Can we remove it from `az disk create` command as well, i.e. both VM and disk commands are using same message.


> * When users deploy the Gen 2 VM without enabling Trusted launch, if the image they use supports Trusted launch, CLI will print the following notification message to recommend them to enable Trusted Launch:

Agreed, looks good.

**Comment by AjKundnani** [comment]
@zhoxing-ms - Please note of following changes:

> Win2022Datacenter

Moved from No change to Change list under Aliases.json, as we've Gen2 version of Windows Server 2022 without Azure Edition available now.




> * **[VM Managed Images](https://learn.microsoft.com/en-us/azure/virtual-machines/windows/capture-image-resource)** do not support _Trusted Launch VMs_. In scenario where user is trying to deploy VM using **Managed Image**, _Trusted Launch_ parameters should be set to _false_ and VM should be deployed as **Hyper-V Generation V2**

Added limitation of Managed Image & Trusted Launch VMs parity in additional context.

**Comment by zhoxing-ms** [comment]
> No, we should stay with simplified message without adding any switch or parameter details. Adding switch details for --hyper-v-generation V2 is causing some confusion, Can we remove it from az disk create command as well, i.e. both VM and disk commands are using same message.

In fact, I mean the notification message which can refer to `az disk create` is:
> Please consider upgrading security for your VM resources by using Gen 2 OS image and Trusted Launch security type. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch

Another notification message containing parameters `--hyper-v-generation V2` is only given to users when they pass in parameters `--hyper-v-generation V1` but the image they used is Gen 2. This is belonged to the user's incorrect usage of this parameter, we need to tell users the correct usage of this parameter. But this is not the notification message I want to refer to.
My main concern is that if we only recommend users to use Trusted Launch VMs, users may not know that they need to deploy the Gen 2 VMs first

**Comment by zhoxing-ms** [comment]
> Moved from No change to Change list under Aliases.json, as we've Gen2 version of Windows Server 2022 without Azure Edition available now.

Got it. In addition, since modifying the [Aliases.json](https://github.com/Azure/azure-rest-api-specs/blob/main/arm-compute/quickstart-templates/aliases.json) will not cause breaking change, can we modify it earlier rather than wait for the next breaking change window? Personally, I think this can increase the probability of customers using Gen 2 image in advance

**Comment by zhoxing-ms** [comment]
＞Moved from No change to Change list under Aliases.json, as we've Gen2 version of Windows Server 2022 without Azure Edition available now.

Got it, thanks~

> [VM Managed Images](https://learn.microsoft.com/en-us/azure/virtual-machines/windows/capture-image-resource) do not support Trusted Launch VMs. In scenario where user is trying to deploy VM using Managed Image, Trusted Launch parameters should be set to false and VM should be deployed as Hyper-V Generation V2

How can we determine that an image is Managed Image? And the notification message no longer needed for this scenario?

In addition, could you please answer this question? https://github.com/Azure/azure-cli/issues/23450#issuecomment-1299484327

**Comment by AjKundnani** [comment]
> > Scenario 1 - User runs query using az vm image list minimal parameters
> 
> @AjKundnani For changing the image returned by the `az vm image list` command from Gen 1 to Gen 2, I personally think it is unnecessary to print notification message in advance. Because the change of the data returned by the list command is a normal change rather than a breaking change, the breaking change occurs only when the returned data structure changes.

@zhoxing-ms - It can be breaking change from Workload OS perspective, as the underlying OS SKU is changed from Gen1 (BIOS) to Gen2 (UEFI).

**Comment by zhoxing-ms** [comment]
@AjKundnani Thanks for your explanation. Yes, I understand that modifying [Aliases.json](https://github.com/Azure/azure-rest-api-specs/blob/main/arm-compute/quickstart-templates/aliases.json) will cause a breaking change when using the image alias to create a VM with the `az vm create` command, but the `az vm image list` command itself does not have a breaking change. The notification message will be added to `az vm create` command and the `az vm image list` command should not be needed, right?

**Comment by AjKundnani** [comment]
> > It can be breaking change from Workload OS perspective, as the underlying OS SKU is changed from Gen1 (BIOS) to Gen2 (UEFI). Will recommend implementing notification for users to be aware that underlying OS SKU will change.
> 
> @AjKundnani Thanks for your explanation. Yes, I understand that modifying [Aliases.json](https://github.com/Azure/azure-rest-api-specs/blob/main/arm-compute/quickstart-templates/aliases.json) will cause a breaking change when using the image alias to create a VM with the `az vm create` command, but the `az vm image list` command itself does not have a breaking change. The notification message will be added to `az vm create` command and the `az vm image list` command should not be needed, right?

Yes, as message is setup for `az vm create`, notification for `az vm image` command is redundant, can be skipped for implementation.

**Comment by AjKundnani** [comment]
> How can we determine that an image is Managed Image? And the notification message recommending Trusted Launch no longer needed for using the Managed Image, right?

Correct, users generally would use `--image` parameter to pass both Platform, Managed image or Gallery Image. Managed image is passed as name like `MyImage` vs Gallery image are passed as Resource ID with `Microsoft.Compute/galleries` making part of the resource ID.

[Example - Create a VM from a custom managed image.](https://learn.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create)

**Comment by PARADISSEEKR** [comment]
Hi @AjKundnani , we have two questions to confirm.
1. Does `Unmanaged VHD BASED Images` need to recommend Trusted Launch?
2. How to distinguish `custom managed image id` and `image id` with `image get(az image show)`, their formats are `/Subscriptions/00000000-0000-000000000000/ResourceGroups/rg/Providers/microsoft.Computes/image`

**Comment by AjKundnani** [comment]
@PARADISSEEKR 
> 1. Does `Unmanaged VHD BASED Images` need to recommend Trusted Launch?
No, as we cannot validate if the VHD supports Gen2 / Trusted Launch capabilities.

> 2\. How to distinguish `custom managed image id` and `image id` with `image get(az image show)`, their formats are

- `Managed Image` can be queried using `az image get` with resource ID of type `Microsoft.Compute`
- `Gallery Image` can be queried using `az sig image-version` with resource ID of type `Microsoft.Compute/galleries`
- `Platform Image` can be queried using [Virtual Machines Images GET API](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-images/get?tabs=HTTP)

**Comment by PARADISSEEKR** [comment]
@AjKundnani Do we need to recommend Trusted Launch if use other SecurityTypes (e.g. `ConfidentialVM`)?

**Comment by AjKundnani** [comment]
> @AjKundnani Do we need to recommend Trusted Launch if use other SecurityTypes (e.g. `ConfidentialVM`)?

No, recommendation should only occur if user has not specified `--security-type` parameter. That's where defaults will be changed during next breaking change implementation window.

**Comment by PARADISSEEKR** [comment]
> * `Managed Image` can be queried using `az image get` with resource ID of type `Microsoft.Compute`
> * `Gallery Image` can be queried using `az sig image-version` with resource ID of type `Microsoft.Compute/galleries`
> * `Platform Image` can be queried using [Virtual Machines Images GET API](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-images/get?tabs=HTTP)

@AjKundnani 
Does this mean that all images obtained by the [Images - Get - REST API](https://learn.microsoft.com/en-us/rest/api/compute/images/get?tabs=HTTP) are managed images?

**Comment by AjKundnani** [comment]
> > * `Managed Image` can be queried using `az image get` with resource ID of type `Microsoft.Compute`
> 
> @AjKundnani Does this mean that all images obtained by the [Images - Get - REST API](https://learn.microsoft.com/en-us/rest/api/compute/images/get?tabs=HTTP) are managed images?

@PARADISSEEKR 
Based on API doc looks like it, I haven't tried using this API for gallery image but my guess is it will not work for gallery images.
- **Gallery Images** - [Gallery Image Version GET](https://learn.microsoft.com/en-us/rest/api/compute/gallery-image-versions/get?tabs=HTTP)
- **Platform Images** - [Virtual Machine Images GET](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-images/get?tabs=HTTP)

**Comment by zhoxing-ms** [comment]
> [VM Managed Images](https://learn.microsoft.com/en-us/azure/virtual-machines/windows/capture-image-resource) do not support Trusted Launch VMs. In scenario where user is trying to deploy VM using Managed Image, Trusted Launch parameters should be set to false and VM should be deployed as Hyper-V Generation V2

In fact, we would like to confirm how to judge whether an image is `Managed Image`, so that the Gen 2 and Trusted Launch will not be recommended to customers who use `Managed Image`.
At present, it seems that `Managed Image` and `Platform Image` cannot be distinguished by the ID format, so we want to confirm that the image that can be queried by [/virtual-machine-images/get](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-images/get?tabs=HTTP) is `Platform Image`, and the image that can be queried by [images/get](https://learn.microsoft.com/en-us/rest/api/compute/images/get?tabs=HTTP) is `Managed Image`, right?

**Comment by AjKundnani** [comment]
@zhoxing-ms , As a user I can pass following values to parameter `--image`:
- URN of image, example **RedHat:RHEL:7-RAW:7.4.2018010506** - This will be platform image
- Platform image alias or Managed Image Name, example **Win2012R2Datacenter** is image alias resolved by `aliases.json`, anything other than aliases.json will be name of managed image in same resource group.
- Gallery Image resource ID - example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myRG/providers/**Microsoft.Compute/galleries/**myGallery/images/myImage/versions/1.0.0 (For managed Image resource ID, it'll not contain **galleries** in the resource URI path)

How does CLI differentiates today between PIR/Managed/Gallery image, if we can re-use same ?

**Comment by zhoxing-ms** [comment]
@AjKundnani In the existing logic of CLI, if users passe in the complete and valid resource ID to `--image` parameter, then we think this value is a managed image ID. If we reuse this logic, does it meet your expectations?
code link:
https://github.com/Azure/azure-cli/blob/62492854bd972efa06f4ba64952592afcb3fcf25/src/azure-cli/azure/cli/command_modules/vm/_validators.py#L245-L247
https://github.com/Azure/azure-cli/blob/62492854bd972efa06f4ba64952592afcb3fcf25/src/azure-cli/azure/cli/command_modules/vm/_validators.py#L398-L400

**Comment by AjKundnani** [comment]
> @AjKundnani In the existing logic of CLI, if users passe in the complete and valid resource ID to `--image` parameter, then we think this value is a managed image ID. If we reuse this logic, does it meet your expectations?
> 
> code link:
> 
> https://github.com/Azure/azure-cli/blob/62492854bd972efa06f4ba64952592afcb3fcf25/src/azure-cli/azure/cli/command_modules/vm/_validators.py#L245-L247
> 
> 
> https://github.com/Azure/azure-cli/blob/62492854bd972efa06f4ba64952592afcb3fcf25/src/azure-cli/azure/cli/command_modules/vm/_validators.py#L398-L400

As discussed, kindly use existing logic of CLI to differentiate between Platform, Managed, Gallery and Community image.

**Comment by AjKundnani** [comment]
@PARADISSEEKR @zhoxing-ms - If we can remove the block highlighted below, do not want to confuse users between Gen2 and Trusted Launch.

All notification message should be consistent **Starting Build 2023 event, "az vm/vmss create" command will deploy Trusted Launch VM by default. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch**

![image](https://user-images.githubusercontent.com/18166395/204488352-c0f7b31e-9978-4a15-aab3-5a77994b85c9.png)

**Comment by zhoxing-ms** [comment]
@AjKundnani Could you please take a look at this comment? https://github.com/Azure/azure-cli/pull/24674/files#r1034524150

**Comment by PARADISSEEKR** [comment]
@AjKundnani Could you please take a look at this comment? https://github.com/Azure/azure-cli/pull/24674/files#diff-186fe5ac9ed55ed82cf0936ff789c6a13a636d8fd90c46b116adee47e71dbf46R7625

**Comment by yanzhudd** [comment]
> Scenario 1 - User runs query using az vm image list minimal parameters

Hi @AjKundnani, let me check with you that if the [_alias.py](https://github.com/Azure/azure-cli/blob/dcac3dff7e4ec7190b8ce632814971bf9c9cca91/src/azure-cli/azure/cli/command_modules/vm/_alias.py) also need to be changed from CLI. If so, please aware of some unversioned image aliases mentioned in Scenario 1 will be removed in https://github.com/Azure/azure-cli/issues/27564.

**Comment by AjKundnani** [comment]
> > Scenario 1 - User runs query using az vm image list minimal parameters
> 
> Hi @AjKundnani, let me check with you that if the [_alias.py](https://github.com/Azure/azure-cli/blob/dcac3dff7e4ec7190b8ce632814971bf9c9cca91/src/azure-cli/azure/cli/command_modules/vm/_alias.py) also need to be changed from CLI. If so, please aware of some unversioned image aliases mentioned in Scenario 1 will be removed in #27564.

@yanzhudd, if the **alias.py** file is used for VM & VMSS deployments then yes it needs to be updated inline with **aliases.json** file requested above.
Ack that unversioned image aliases will be removed. Goal is all remaining aliases should be referring to Gen2-TrustedLaunchSupported platform images.

**Comment by yanzhudd** [comment]
Hi @AjKundnani, could you please help review this [PR](https://github.com/Azure/azure-cli/pull/27636/files)? Thanks

**Comment by AjKundnani** [comment]
@yanzhudd - Validated the change to image alias and condition for TL-as-Default, code wise looks good.
Will validate further during bug bash.
