### ISSUE TITLE
Deleting user from VM, unsupported

### ISSUE THREAD

**Issue by garrygbain** [Azure/azure-cli#23453]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0474c5a5-4231-0e39-f63f-f7bc05cb7797
* Version Independent ID: 22ea94c8-cc6f-97aa-77b1-4ffca845807e
* Content: [az vm user](https://docs.microsoft.com/en-us/cli/azure/vm/user?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm/user.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm/user.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by garrygbain** [comment]
Attempting to delete a user from a VM, returns "Deleting a user is not supported on Windows VM"!

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@garrygbain Could you please send the debug log *(add `--debug` parameter)* to me by email? My email address is Zhou.Xing@microsoft.com

**Comment by zhoxing-ms** [comment]
This problem was by designed. We need the Compute team to confirm whether the current Windows VM supports deleting the user

**Comment by navba-MSFT** [comment]
@garrygbain Thanks for reaching out to us and reporting this issue. Could you please elaborate on your ask ? What is your use case and what are you trying to achieve ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@garrygbain Adding on to the above comment, please let me know if you are using a Windows VM or Linux VM. Awaiting your reply.

**Comment by garrygbain** [comment]
Hi @navba-MSFT  We have 10 Windows VMs; These are used to access environments and we often setup user accounts on each VM. I have scripted adding the accounts but unable to delete the accounts by script, so this is being completed manually.

**Comment by navba-MSFT** [comment]
@garrygbain You can try the below workaround and check if that helps:

Create a file by name `script.ps1` with below content:

> Remove-LocalUser -Name 'testUser'

Then you can run the below command remotely:
>Invoke-AzVMRunCommand -ResourceGroupName $resourceGroup -Name $vmName -CommandId 'RunPowerShellScript' -ScriptPath .\script.ps1 

Hope this helps.

**Comment by navba-MSFT** [comment]
@garrygbain Thanks for getting back. Could you please run the below command to set the subscription context first and then run the above invoke command ?

>Set-AzContext -Subscription $subscriptionId
Select-AzSubscription -SubscriptionId 'XXXX-XXXX-XXXX-XXXX'
az account set --subscription "XXXX-XXXXX-XXXXX-XXXX"

**Comment by navba-MSFT** [comment]
@garrygbain Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by JereO-Nc** [comment]
HI, what about if i want to delete the user across multiple  VMs in different subscriptions, the az cli, 'az vm user delete' allows you to provide ids for all the VMs irrespective of subscription. Also the workaround doesnt address the issue which is why the cmd isnt working. ANy ideas on how to resolve? Thanks

**Comment by aamad777** [comment]
> @garrygbain Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

not working for domain user

**Comment by JereO-Nc** [comment]
@navba-MSFT i raised a similar issue and it got closed, without a response. Your solution doesn't cover the use-case where i am trying to delete a user across multiple vms in didfferent subscriptions. can you kindly recommend a way forward, why does the az vm user --ids state that it can do that when the error states otherwise. Also @zhoxing-ms and @yonzhan where should this issue be addressed, seeing as my issue was closed before a solution was given? Thank you.

**Comment by navba-MSFT** [comment]
@JereO-Nc see my reply in your github issue https://github.com/Azure/azure-cli/issues/23595
