### ISSUE TITLE
Batch Endpoint Invoke - Input Dataset Declaration is not working.

### ISSUE THREAD

**Issue by sherlynnw-fac** [Azure/azure-cli#23466]
Example 1: Invoke a batch endpoint with input data from a registered Azure ML data asset 
It was working for some time, but has stopped working, invocation works but pipeline in AML fails with Service Error: Experiment submission failed due to error 'id' cannot be null.

Example 3: Invoke a batch endpoint with input file from a registered datastore & Example 5: Invoke a batch endpoint with input folder from a registered datastore
Results in InternalServerError during batch endpoint invocation.

my az version is as follows:

{
  "azure-cli": "2.39.0",
  "azure-cli-core": "2.39.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ml": "2.6.1"
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5233a95c-48d7-d49b-3e21-b42c94a31290
* Version Independent ID: 60a98b3a-a7b9-ae58-ab5e-4b1d086a7dd0
* Content: [az ml batch-endpoint](https://docs.microsoft.com/en-us/cli/azure/ml/batch-endpoint?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/batch-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ml/batch-endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@sherlynnw-fac Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@sherlynnw-fac Apologies for the delay in getting back. Can you please share the debug trace for the issue?

**Comment by sherlynnw-fac** [comment]
Apologies for the delay. I just retested this today to get the logs but seems to be working fine now. Closing this issue. Thank you.
