### ISSUE TITLE
CLI | Trusted Launch as Default - New VM from existing disk or image (SIG/ACG/Managed)

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-cli#23476]
### Related command

- [az vm create --name 'vmname' --resource-group 'rgname' --attach-os-disk 'diskId'](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create)
- [az vm create --name 'vmname' --resource-group 'rgname' --image 'galleryImageId'](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create)
- [az vmss create --name 'vmssname' --resource-group 'rgname' --image 'galleryImageId'](https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-create)
- [az disk show](https://docs.microsoft.com/en-us/cli/azure/disk?view=azure-cli-latest#az-disk-show)
- [az sig image-version show](https://docs.microsoft.com/en-us/cli/azure/sig/image-version?view=azure-cli-latest#az-sig-image-version-show)
- [az image show](https://docs.microsoft.com/en-us/cli/azure/image?view=azure-cli-latest#az-image-show)

### Resource Provider

Microsoft.Compute/virtualMachines

### Description of Feature or Work Requested

# Trusted Launch as Default

As part of making compute layer secure for customers to deploy workloads, request is to make [Trusted Launch](https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch) (GA Date: November 2021) as default deployment option in CLI. Following changes will need to be made for same:

## Scenario 1 - User creates VM from existing disk using `az vm create --attach-os-disk`

Present Behavior | Updated Behavior post change
-|-
New VM with existing managed disk:<ol><li>User runs command `az vm create -g MyResourceGroup -n MyVm --attach-os-disk MyOsDisk --os-type linux --size VMSize`<li>VM is created with specified configuration. If `--size` parameter is not specified, CLI deploys VM with size **Standard_DS1_v2**.</li></ol> | OS Disk securityProfile has 1-1 mapping with VM, i.e., OS Disk enabled with Trusted Launch can only deploy VM with Trusted Launch.<ol><li>If OS disk enabled with securityType TrustedLaunch, enable following parameters by default:<ul><li>`--enable-secure-boot` set to true<li>`--enable-vtpm` set to true<li>`--security-type` set to TrustedLaunch</li></ul><li>If no, Deploy VM with user passed configuration along with Notification message should be printed for user. Notification Message `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`</li></ol>

## Scenario 2 - User creates VM from existing shared image (Azure Compute Gallery) or managed image using `az vm create --image`

Present Behavior | Updated Behavior post change
-|-
New VM with existing image in Azure Compute Gallery:<ol><li>User runs command `az vm create -g MyResourceGroup -n MyVm --image MyImage --size VMSize`<li>VM is created with specified configuration. If `--size` parameter is not specified, CLI deploys VM with size **Standard_DS1_v2**.</li></ol> | <ul><li>**No change** due to potential impact surface due to ACG not being TrustedLaunchSupported and Managed Image does not support Trusted Launch.<li>Set securityType to **Standard** by default if no inputs by end user<li>If securityType is not set to `TrustedLaunch` then Deploy VM with user passed configuration along with Notification message should be printed for user. Notification Message `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`</li></ul>

## Scenario 3 - User creates VMSS from existing shared image (Azure Compute Gallery) or managed image using `az vmss create --image`

Present Behavior | Updated Behavior post change
-|-
New VMSS with existing image in Azure Compute Gallery:<ol><li>User runs command `az vmss create -g MyResourceGroup -n MyVmss --image /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myRG/providers/Microsoft.Compute/galleries/myGallery/images/myImage`<li>VM is created with specified configuration. If `--size` parameter is not specified, CLI deploys VM with size **Standard_DS1_v2**.</li></ol> | <ul><li>**No change** due to potential impact surface due to ACG not being TrustedLaunchSupported and Managed Image does not support Trusted Launch.<li>Set securityType to **Standard** by default if no inputs by end user<li>If securityType is not set to `TrustedLaunch` then Deploy VM with user passed configuration along with Notification message should be printed for user. Notification Message `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`</li></ul>

>**NOTE:** Please review limitations [Trusted Launch VM Limitations](https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch#limitations) to assess any impact for CLI users.

### Minimum API Version Required

2021-11-01

### Swagger PR link

[Compute Swagger 2021-11-01](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2021-11-01/compute.json)

### Request Example

- [Create VM with UEFI Settings JSON](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2021-11-01/examples/compute/CreateAVmWithUefiSettings.json)
- [Create VMSS with UEFI Settings JSON](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2021-11-01/examples/compute/CreateAScaleSetWithUefiSettings.json)

### Target Date

2022-10-10

### Additional context

- **Change in request since October 2022 (Warning message implementation):**
   - Trusted Launch as default bypassed for Azure Compute gallery
   - VM Size check using Resource SKU LIST API request is removed.
   - Server / API side error message added.
   - OS image check scoped to hyperVGeneration = v2
- OS Disk and Virtual Machine have 1-1 mapping of HyperVGeneration and SecurityType. No defaults change implementation required.
- Due to high impact for ACG scenario and unknowns, it is not approved to implement breaking change for this scenario.
- Managed images do not support Trusted Launch. Hence, if input image is Managed image, Trusted Launch as default should be bypassed.
- **Image Providers**:
   - Azure Compute Gallery: https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/**providers/Microsoft.Compute/galleries/**myGalleryName/images/myGalleryImageName?api-version=2022-03-03
   - Marketplace: https://management.azure.com/subscriptions/{subscription-id}/providers/Microsoft.Compute/locations/aaaaaa/**publishers/aaa/artifacttypes/vmimage/offers/**aaaaaaaaaaaaaaaaaaaaaaaaaaaaa/skus/aaaaaaaaaaaaaaaaaaaaaaaaaaa/versions/aaaaaaaaaaaaaaaaaaa?api-version=2023-07-01
   - Managed Image: https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/**providers/Microsoft.Compute/images/**myImage?api-version=2023-07-01
   - Shared Image: **/sharedGalleries/**
   - Community Image: **/communityGalleries/**

**Comment by AjKundnani** [comment]
Related closely to request #23450

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by AjKundnani** [comment]
@PARADISSEEKR @zhoxing-ms  If we can remove the block highlighted below, do not want to confuse users between Gen2 and Trusted Launch.

All notification message should be consistent Starting Build 2023 event, "az vm/vmss create" command will deploy Trusted Launch VM by default. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch

![image](https://user-images.githubusercontent.com/18166395/204491786-0d2fd690-3463-4c99-aba4-801f0f2e6525.png)

**Comment by AjKundnani** [comment]
@PARADISSEEKR @zhoxing-ms - For Scenario **User creates VM from existing shared image (Azure Compute Gallery) or managed image using az vm create --image** - Notification message is not generated when submitting resource ID for ACG image version:

![image](https://user-images.githubusercontent.com/18166395/204494939-7f5e1532-1dc7-4883-b8ea-dc2d5708ec08.png)

**Comment by yanzhudd** [comment]
Hi @AjKundnani could you please help review this [PR](https://github.com/Azure/azure-cli/pull/27722)? Thanks!

**Comment by AjKundnani** [comment]
> Hi @AjKundnani could you please help review this [PR](https://github.com/Azure/azure-cli/pull/27722)? Thanks!

@yanzhudd at cursory review it looks ok to me, can confirm more confidently post validating with bug bash.
