### ISSUE TITLE
Invalid status 'Accepted' when using the `az sql db copy` command

### ISSUE THREAD

**Issue by fleed** [Azure/azure-cli#23472]
## Describe the bug

**Command Name**
`az sql db copy `

**Errors:**
```
ERROR: Operation returned an invalid status 'Accepted'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Run the command (PowerShell syntax):

```
az sql db copy `
--dest-name "destinationname" --dest-resource-group "destinationresourcegroup" --dest-server "destinationserver" `
  --elastic-pool "destinationelasticpoolid" `
  --name "sourcename" --resource-group "sourceresourcegroup" --server "sourceserver" `
  --subscription "subscriptionid" `
  --zone-redundant false
```

## Expected Behavior

The command is executed and doesn't return an error.

**Important: it seems that the Azure operation is correctly executed (the database is copied successfully)**

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0

Extensions:
storage-preview 0.7.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context

The command is run in an Azure DevOps pipeline using a self-hosted build agent. It was working until few weeks ago.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@fleed I am not able to reproduce this issue and az sql db copy worked as expected -
![image](https://user-images.githubusercontent.com/38112130/183778239-194aa9f8-e1be-49ef-95b5-64d449b54a62.png)
