### ISSUE TITLE
webspp:No way to generate deployment scripts for WebApps

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#2347]
It is common to generate a sample deployment script for customizing deployments to WebApps via Kudu.  CLI 1.0 supported this, but no such command exists in 2.0.

**Comment by yugangw-msft** [comment]
Plan to do it at the second half of March

**Comment by yugangw-msft** [comment]
//cc:@davidebbo
This might need kudu script which currently is a npm module, not pip package

**Comment by davidebbo** [comment]
Correct, it's based on kuduscript.

Note that there is now a simpler workflow to get the starter script:

- Deploy to Kudu once with the default script generation
- Go to Kudu an download script from menu
- Modify at will and commit to repo

**Comment by lostintangent** [comment]
@davidebbo What is the recommendation here for Linux-based Web Apps? The `Tools...Download deployment script` menu isn't displayed in Kudu for Linux.

@yugangw-msft Was there any further discussion on this item? It'd be cool to see something happen to support this scenario.

**Comment by davidebbo** [comment]
@lostintangent You can install [kuduscript](https://www.npmjs.com/package/kuduscript) directly from npm and run that. e.g. try:

```
npm install -g kuduscript
kuduscript -y --node
```

**Comment by lostintangent** [comment]
@davidebbo Ah cool! Thanks for the quick response. Was this tool what the Azure CLI 1.0 was using behind the scenes to generate the deployment script?

**Comment by davidebbo** [comment]
@lostintangent Yep. So all the switches are identical.

**Comment by lostintangent** [comment]
@davidebbo Very cool. Thanks so much for that pointer! I'd definitely love to see this integrated into Az CLI 2.0 (per this request), but it's awesome to know about this NPM module in the meantime.

**Comment by davidebbo** [comment]
I guess it comes down to the feasibility of shelling out to a Node tool from a Python tool. I'll let @yugangw-msft comment further.

**Comment by troydai** [comment]
The problem with shelling out approach is that we can't guarantee that node.js is installed. We probably could look into the possibility of migrating https://www.npmjs.com/package/kuduscript to python.

**Comment by davidebbo** [comment]
@troydai that's a much bigger investment. Not saying it can't happen, but definitely not in the near term.

**Comment by panchagnula** [comment]
Closing this since this not something planned.
