### ISSUE TITLE
Azure-keyvault-secrets not installed with azure-cli

### ISSUE THREAD

**Issue by Ceglowa** [Azure/azure-cli#23477]
**Related command**
pip install azure-cli

**Is your feature request related to a problem? Please describe.**
Why when installing azure-cli, the `azure-keyvault` is installed and `azure-keyvault-secrets` is not installed? Also, like seen here -https://pypi.org/project/azure-keyvault/#description - `azure-keyvault-secrets` is a direct dependency of the `azure-keyvault`. And additionally, why the version of `azure-keyvault` that is being installed is 1.1.0, when this version is already 4 years old?

**Describe the solution you'd like**
To include the `azure-keyvault-secrets` in the setup.py of the `azure-cli` package and also to update the version of `azure-keyvault`

**Describe alternatives you've considered**
Right now, I need to install `azure-keyvault-secrets` additionally.

**Comment by yonzhan** [comment]
@evelyn-ys  for awareness

**Comment by evelyn-ys** [comment]
`azure-keyvault 1.1.0` is track1 SDK including all API for keys, secrets, certificates...
`azure-keyvault 4.X` is track2 SDK which is just a bundle for `azure-keyvault-keys`, `azure-keyvault-secrets`, `azure-keyvault-certificates`...

CLI has no plan for migrating secrets to track2 SDK so we don't rely on `azure-keyvault-secrets`
