### ISSUE TITLE
azure-devops: [az acr manifest show] command is 10 to 20 times slower than [docker manifest inspect]

### ISSUE THREAD

**Issue by aluty** [Azure/azure-cli#23483]
## Describe the bug
azure-devops: [az acr manifest show] command is 10 to 20 times slower than [docker manifest inspect]

(Below is just one example.  How do other az acr commands compare to the docker CLI equivalents?)

**Command Name**
`az acr manifest show`

Output from script below:
```
VERBOSE: BEGIN: docker manifest inspect
cdpxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.azurecr.io/IMAGE:TAG
VERBOSE: END: docker manifest inspect 00:00:01.8266440
VERBOSE: BEGIN: az acr manifest show -r cdpxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -n
IMAGE:TAG
WARNING: Command group 'acr manifest' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
VERBOSE: END: az acr manifest show 00:00:25.9186843

Reference                                                                                          Command                 Elapsed
---------                                                                                          -------                 -------
https://docs.docker.com/engine/reference/commandline/manifest_inspect/                             docker manifest inspect 00:00:01.8314278
https://docs.microsoft.com/en-us/cli/azure/acr/manifest?view=azure-cli-latest#az-acr-manifest-show az acr manifest show    00:00:25.9214653


VERBOSE: How much slower is az vs. docker? 14.1536921630217
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
docker.exe installed for comparison.  See manual prerequisite (login docker and az) in script below.
- `az acr manifest show -r {} -n {}`

Script
```
# PerfTestDockerVersusAzCLI.ps1 2022-08-06

<#
.SYNOPSIS
    Performance test comparison of Docker versus Az Command Line Interface (CLI).
.REMARKS
   Use the Docker command line https://docs.docker.com/engine/reference/commandline/cli/
   Azure Container Registry https://docs.microsoft.com/en-us/cli/azure/service-page/azure%20container%20registry?view=azure-cli-latest

   Manual prerequisite:
   docker login cdpxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.azurecr.io -u UUUUUUUU-UUUU-UUUU-UUUU-UUUUUUUUUUUU -p ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
   az login --service-principal -u UUUUUUUU-UUUU-UUUU-UUUU-UUUUUUUUUUUU -p ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●● --tenant TTTTTTTT-TTTT-TTTT-TTTT-TTTTTTTTTTTT
#>

$results = @()

# Docker
$stopwatch = [System.Diagnostics.Stopwatch]::StartNew()
Write-Verbose -Message "BEGIN: docker manifest inspect cdpxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.azurecr.io/IMAGE:TAG" -Verbose
$dockerOut = docker manifest inspect cdpxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.azurecr.io/IMAGE:TAG
#$dockerOut
Write-Verbose -Message "END: docker manifest inspect $($stopwatch.Elapsed)" -Verbose
$results += [PSCustomObject]@{
    Reference = "https://docs.docker.com/engine/reference/commandline/manifest_inspect/"
    Command = "docker manifest inspect"
    Elapsed = $stopwatch.Elapsed
}

# Az
$stopwatch = [System.Diagnostics.Stopwatch]::StartNew()
Write-Verbose -Message "BEGIN: az acr manifest show -r cdpxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -n IMAGE:TAG" -Verbose
$azOut = az acr manifest show -r cdpxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -n IMAGE:TAG
#$azOut
Write-Verbose -Message "END: az acr manifest show $($stopwatch.Elapsed)" -Verbose
$results += [PSCustomObject]@{
    Reference = "https://docs.microsoft.com/en-us/cli/azure/acr/manifest?view=azure-cli-latest#az-acr-manifest-show"
    Command = "az acr manifest show"
    Elapsed = $stopwatch.Elapsed
}

$results | Format-Table -AutoSize
Write-Verbose -Message "How much slower is az vs. docker? $($results[1].Elapsed.TotalSeconds / $results[0].Elapsed.TotalSeconds)" -Verbose
```

## Expected Behavior
Comparable execution time, not 10 to 20 times slower!
- docker manifest inspect 00:00:01.8266440
- az acr manifest show 00:00:25.9186843

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team to help with

**Comment by navba-MSFT** [comment]
@aluty Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@aluty I was able to reproduce the issue at my end using your sample script. I had reached out to the Product owners who had written the `az acr manifest show` command. I am pasting their response as-is. 

>By perf testing above, it seems that `az acr manifest show` takes 2.5x as long as docker manifest inspect. 
>
>This difference in performance is not unexpected. The primary contributor is that the az acr auth flow often includes one or more calls to ARM prior to the request for the manifest itself. You can see these calls by running the command with the –debug flag. These calls aren’t made at all for docker manifest inspect. A smaller contributing factor is that az cli is written in Python and the Docker client is written in Golang. 


Hope this answers.

**Comment by aluty** [comment]
How does az CLI performance compare with other docker CLI commands?  Comparison table would be nice if at least to show equivalent commands between az and docker.
Why are ARM calls needed by az?  What advantages would az provide over docker CLI?

**Comment by navba-MSFT** [comment]
@aluty Considering you are internal to Microsoft, I am looping you on an email thread with the Product Group team of ACR. They have provided the answer to your question.

**Comment by navba-MSFT** [comment]
@aluty Archiving this thread for now since we have an active thread running with the Product group team to track this further.
