### ISSUE TITLE
Command needed to launch marketplace templates

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#2348]
The portal offers a number of marketplace templates for complex deployments such as CloudFoundry.  There is no equivalent command in the CLI.

**Comment by brendandburns** [comment]
@binderjoe is there a place where I can download those templates? I don't think that the templates for those solutions are necessarily publically accessible.

I could add a command for all of the quickstarts that are here:

https://github.com/Azure/azure-quickstart-templates

**Comment by brendandburns** [comment]
Please see the recently launched Managed Applications:

https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-overview

For a better way to do this.

Closing this.
