### ISSUE TITLE
Typo "GitHub action workflow"→"GitHub Actions workflow"

### ISSUE THREAD

**Issue by hyoshioka0128** [Azure/azure-cli#23480]
https://docs.microsoft.com/en-us/cli/azure/mysql/flexible-server/deploy?view=azure-cli-latest

![image](https://user-images.githubusercontent.com/40815708/183694304-abfc9104-06a0-4b59-ac92-32d13bf249c4.png)

![image](https://user-images.githubusercontent.com/40815708/183694021-0473e5a5-e402-4e87-b19d-c93ccacf95e2.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46c8f2c1-7766-331a-de77-f3a94e73cc19
* Version Independent ID: 2425123a-b737-cd3b-16da-5ed74846a24f
* Content: [az mysql flexible-server deploy](https://docs.microsoft.com/en-us/cli/azure/mysql/flexible-server/deploy?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/mysql/flexible-server/deploy.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/mysql/flexible-server/deploy.yml)
* Service: **mysql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@hyoshioka0128 We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@hyoshioka0128 I have submitted a PR to fix this issue.  Thanks.

**Comment by yonzhan** [comment]
route to CXP team
