### ISSUE TITLE
[VM] [Feature Request] Provide a way to define custom VM aliases

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2349]
The current set of VM aliases makes it really simply to spin up base VMs (e.g. `UbuntuLTS`), but I'd love to be able to spin up VMs that provided a baseline for certain app platforms, instead of needing to provision a base VM and then immediately turn around to install a core dependency (e.g. Node.js).

For example, Bitnami maintains VMs for Node.js LTS in the marketplace, and it would be really cool to be able to run `az vm create --image NodeLTS` as opposed to needing to lookup/specify the full URN for the Bitnami Node.js VMs.

The [VM alias file](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json) seems pretty specific to OS baselines, so I'm not sure that it makes sense to augment that, but maybe the CLI could provide some mechanism to define custom VM aliases?

**Comment by lostintangent** [comment]
It would be cool if the user were able to be able to register their own alias file, in order to add new aliases and customize existing ones. That way, it would simply augment the existing alias file, but could encourage sharing aliases within teams/companies and the community (you could even host it as a GitHub gist).

The following is total pseudo, and the name is kind of horrible, but is a general though about how this could look:

``` az vm image set-user-alias -u http://foo.bar/useraliases.json```

**Comment by yugangw-msft** [comment]
we can live with till we have more user voices
