### ISSUE TITLE
Support NVMe flag

### ISSUE THREAD

**Issue by eymizrac** [Azure/azure-cli#23492]
### Resource Provider

Microsoft.compute/Storage 

### Description of Feature or Work Requested

Overlake 1.1 introduced new capability to Azure called NVMe which in the future will replace SCSI. In order to create a VM w/ NVMe controller, we added the support of NVME flag and as a result the CRP API has been changed. The NVMe triple the storage performance 

We will need CLI to support the new Swagger for our PublicP with customers

CRP design doc
[[https://microsoft.sharepoint.com/:w:/t/ComputeVM/EV-sIDNhNZNMnuYhcxpqIaABGuUqRST01TUTr0KUnffkhw?e=YkN1XM](https://microsoft.sharepoint.com/:w:/t/ComputeVM/EV-sIDNhNZNMnuYhcxpqIaABGuUqRST01TUTr0KUnffkhw?e=YkN1XM&isSPOFile=1)](url)

### Minimum API Version Required

N/A yet

### Swagger PR link

Swagger will be ready by Aug' 19th 

### Request Example

You can find Jason file example at the below link
[https://microsoft-my.sharepoint.com/:w:/p/eymizrac/Ea9-QblAsTJHovDo05h34uQB6zal3ysUFJSiQVhC4XeDUg?e=15STdJ](url)

### Target Date

PublicP  is target to mid' Sep'

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@eymizrac Any update for the Swagger link?

**Comment by eymizrac** [comment]
***@***.*** ***@***.***>
They have completed the Swagger spec and we are waiting for VMSS team since yesterday to approve it

Thanks!
Eyal

**Comment by zhoxing-ms** [comment]
@eymizrac Any update?

**Comment by yanzhudd** [comment]
Hello @eymizrac, any update for the Swagger link?

**Comment by yanzhudd** [comment]
@eymizrac Any update?

**Comment by zhoxing-ms** [comment]
@eymizrac May I ask whether the feature request of these two issues https://github.com/Azure/azure-cli/issues/23492 https://github.com/Azure/azure-cli/issues/23664 are actually the same? 
If so, could you please help close this duplicate one?

**Comment by eymizrac** [comment]
Yes
Thanks!
Eyal

השג את Outlook עבור iOS<https://aka.ms/o0ukef>
________________________________
מאת: Xing Zhou ***@***.***>
‏‏נשלח: Sunday, September 18, 2022 7:31:27 PM
‏‏אל: Azure/azure-cli ***@***.***>
עותק: Eyal Mizrachi ***@***.***>; Mention ***@***.***>
‏‏נושא: Re: [Azure/azure-cli] Support NVMe flag (Issue #23492)


@eymizrac<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feymizrac&data=05%7C01%7CEyal.Mizrachi%40microsoft.com%7C4a57920d60b347adbdd608da99e70dd8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637991514898108526%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aI1StGZDjgn39cXVArjqdL1B47dHs8Nf5tTD330M%2BXI%3D&reserved=0> May I ask whether the feature request of these two issues #23492<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fissues%2F23492&data=05%7C01%7CEyal.Mizrachi%40microsoft.com%7C4a57920d60b347adbdd608da99e70dd8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637991514898264301%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hdnXOTN2VGnJngBucxGYEHrvzpqZMQOSmz3iz8pE8ag%3D&reserved=0> #23664<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fissues%2F23664&data=05%7C01%7CEyal.Mizrachi%40microsoft.com%7C4a57920d60b347adbdd608da99e70dd8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637991514898264301%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fjv1AlEtzZScd2qj4k6nhlrpQSEoFkQj43tmSljLgdU%3D&reserved=0> are actually the same?
If so, could you please help close this duplicate one?
