### ISSUE TITLE
az network bastion / fail to connect / decryption failed

### ISSUE THREAD

**Issue by szymonbr** [Azure/azure-cli#23511]
## Describe the bug

**Command Name**
`az network bastion rdp`

**Errors:**
```
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network bastion rdp --name {} --resource-group {} --target-resource-id {}`
- `az network bastion tunnel --name {} --resource-group {} --target-resource-id {} --resource-port {} --port {}`

## Expected Behavior
Connect to a Windows Azure VM from RDP native client or be able to transfer files with SCP. 

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0

Extensions:
arcdata 1.4.5

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@szymonbr Just checking in here to see if you are still facing this issue. If so, it would be best to try with the latest version by upgrading Azure CLI using the `az upgrade` command. Also, add the `--debug` flag to your command and share the logs if you are still facing the same issue.

**Comment by szymonbr** [comment]
@PramodValavala-MSFT Thanks a lot!. Now it works like a charm. :)
