### ISSUE TITLE
ImportError: cannot import name 'edge_zone_type'

### ISSUE THREAD

**Issue by kylejulian** [Azure/azure-cli#23513]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
cannot import name 'edge_zone_type'
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-yccaebu4\knack\cli.py, ln 233, in invoke
azure\cli\core\commands\__init__.py, ln 563, in execute
pip-unpacked-wheel-8u6uejh7\azure\cli\core\__init__.py, ln 511, in load_arguments
.azure\cliextensions\aks-preview\azext_aks_preview\__init__.py, ln 47, in load_arguments
    from ._params import load_arguments
.azure\cliextensions\aks-preview\azext_aks_preview\_params.py, ln 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --kubernetes-version {} --generate-ssh-keys --windows-admin-password {} --windows-admin-username {} --vm-set-type {} --load-balancer-sku {} --network-plugin {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1 *

Extensions:
aks-preview 0.5.41

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@kylejulian Can you please upgrade to the latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)? and retry

**Comment by kylejulian** [comment]
yes, that works. thanks.
