### ISSUE TITLE
azure-cli behind a firewall

### ISSUE THREAD

**Issue by ragemnky** [Azure/azure-cli#23517]
**Related command**
az deployment tenant create --template-file xxx/xxx/template.bicep ....

**Describe the bug**
The environment I'm running the command in restricts outbound internet access.
With --debug on I can see the following error:

ERROR: cli.azure.cli.core.azclierror: Error while attempting to download Bicep CLI: <urlopen error [Errno 104] Connection reset by peer>

The debug log references:

DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
DEBUG: urllib3.connectionpool: https://aka.ms:443 "GET /BicepLatestRelease HTTP/1.1" 301 0
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): api.github.com:443
DEBUG: urllib3.connectionpool: https://api.github.com:443 "GET /repos/Azure/bicep/releases/latest HTTP/1.1" 200 2672

Both aka.ms and api.github.com have since been whitelisted on the firewall but we can see it trying to get to a number of other IP's, which are registered to either Microsoft or Akamai and the IP's change if we try the command again later on.

Other azure-cli commands like az login, az account list, etc all work as expected. As such, is there way to either disable this command from trying to fetch the latest bicep cli, we have tried the following to no avail:

az config set auto-upgrade.enable=no
az config set auto-upgrade.all=no

Or a list of the outbound network requirements for azure-cli commands to work so we can get these added to the firewall?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@ragemnky Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by Grant-Rc** [comment]
> @ragemnky Could you please share the complete `--debug` trace ? You could remove the sensitive info like resource name / subscription id etc from the output and share it.

Im working With @ragemnky but they are on leave atm, here is an output

`$ az deployment mg create --management-group-id $ManagementGroupPrefix --template-file infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep --parameters infra-as-code/bicep/modules/policy/definitions/parameters/customPolicyDefinitions.parameters.all.json --location $Location --name create_policy_defs-$RunID --debug
DEBUG: cli.knack.cli: Command arguments: ['deployment', 'mg', 'create', '--management-group-id', '***', '--template-file', 'infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep', '--parameters', 'infra-as-code/bicep/modules/policy/definitions/parameters/customPolicyDefinitions.parameters.all.json', '--location', 'australiaeast', '--name', 'create_policy_defs-95436', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f6602953be0>, <function OutputProducer.on_global_arguments at 0x7f66025fc700>, <function CLIQuery.on_global_arguments at 0x7f6602631990>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'deployment': ['azure.cli.command_modules.resource']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: resource                  0.015        47       207
DEBUG: cli.azure.cli.core: Total (1)                 0.015        47       207
DEBUG: cli.azure.cli.core: Loaded 47 groups, 207 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : deployment mg create
DEBUG: cli.azure.cli.core: Command table: deployment mg create
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f6601be5240>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/root/.azure/commands/2022-08-16.21-43-57.deployment_mg_create.15.log'.
INFO: az_command_data_logger: command args: deployment mg create --management-group-id {} --template-file {} --parameters {} --location {} --name {} --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f660194ec20>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f6601a0f010>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f6601a0f130>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f66025fc790>, <function CLIQuery.handle_query_parameter at 0x7f6602631a20>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f6601a0f0a0>]
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
DEBUG: urllib3.connectionpool: https://aka.ms:443 "GET /BicepLatestRelease HTTP/1.1" 301 0
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): api.bicep.azure.com:443
DEBUG: urllib3.connectionpool: https://api.bicep.azure.com:443 "GET /releases/latest HTTP/1.1" 200 2687
DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 113, in ensure_bicep_installation
    request = urlopen(_get_bicep_download_url(system, release_tag, target_platform=target_platform))
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/resource/custom.py", line 627, in deploy_arm_template_at_management_group
    return _deploy_arm_template_at_management_group(cmd=cmd,
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/resource/custom.py", line 655, in _deploy_arm_template_at_management_group
    deployment_properties = _prepare_deployment_properties_unmodified(cmd, 'managementGroup', template_file=template_file,
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/resource/custom.py", line 976, in _prepare_deployment_properties_unmodified
    run_bicep_command(["build", "--stdout", template_file])
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 63, in run_bicep_command
    ensure_bicep_installation(stdout=False)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/resource/_bicep.py", line 127, in ensure_bicep_installation
    raise ClientRequestError(f"Error while attempting to download Bicep CLI: {err}")
azure.cli.core.azclierror.ClientRequestError: Error while attempting to download Bicep CLI: <urlopen error [Errno 104] Connection reset by peer>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/arm.py", line 109, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'ClientRequestError' object has no attribute 'inner_exception'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/arm.py", line 114, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: Error while attempting to download Bicep CLI: <urlopen error [Errno 104] Connection reset by peer>
ERROR: cli.azure.cli.core.azclierror: Error while attempting to download Bicep CLI: <urlopen error [Errno 104] Connection reset by peer>
ERROR: az_command_data_logger: Error while attempting to download Bicep CLI: <urlopen error [Errno 104] Connection reset by peer>
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f6601be5480>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 2.764 seconds (init: 0.165, invoke: 2.599)
INFO: telemetry.save: Save telemetry record of length 3159 in cache
WARNING: telemetry.check: Negative: The /root/.azure/telemetry.txt was modified at 2022-08-16 21:43:57.320346, which in less than 600.000000 s
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1`

**Comment by navba-MSFT** [comment]
@ragemnky Could you please whitelist the below 2 URLs too in your firewall if its not yet done  and test again ?

>https://aka.ms/BicepLatestRelease
https://api.bicep.azure.com/releases/latest

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Grant-Rc Thanks for getting back. The commands [az config set auto-upgrade.enable](url) and `az config set auto-upgrade.all` are used if you would like to keep up with the latest version of Az CLI and CLI extensions. This command isn't related to the Azure Bicep release call that is happening in your scenario. Because Bicep is not part of CLI extension.

As mentioned above, please work with your internal network team and whitelist the above mentioned URLs. That should address this issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ragemnky @Grant-Rc I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any update on this. Awaiting your reply.

**Comment by Grant-Rc** [comment]
@navali-msft our Network Team have found a way to URL whitelist these 2 address and so far I have been successful in my deployment. waiting on @ragemnky to get back and check for me but im happy for this to be closed but this is not my ticket.

**Comment by navba-MSFT** [comment]
@Grant-Rc Thanks for getting back. 

@ragemnky Please feel free to reopen this issue if you have any follow-up questions or need any further assistance on this. We would be happy to help.
