### ISSUE TITLE
az aks nodepool update can update taints, docs could use this detail

### ISSUE THREAD

**Issue by christianag54** [Azure/azure-cli#23510]
The command has these options 

az aks nodepool update --cluster-name
                       --name
                       --resource-group
                       [--aks-custom-headers]
                       [--disable-cluster-autoscaler]
                       [--enable-cluster-autoscaler]
                       [--labels]
                       [--max-count]
                       [--max-surge]
                       [--min-count]
                       [--mode {System, User}]
                       [--no-wait]
                       [--node-taints]
                       [--scale-down-mode {Deallocate, Delete}]
                       [--tags]
                       [--update-cluster-autoscaler]

In the command description it could include a statement indicating the commands allows to update the node pool by adding a node taint (even if the node pool doesn’t have one already) or to update an existing taint.

I performed the following test, and it does work.

I have two node pools; one already has taint applied to it

![image](https://user-images.githubusercontent.com/107078811/184185458-bb1529d1-36aa-4b59-b149-f62dcca3eec9.png)

I indeed can update the existing taint value 

Executed
az aks nodepool update --cluster-name christiancluster --resource-group christiancluster_group --name taintnp --node-taints key2=value2:NoSchedule

Result

![image](https://user-images.githubusercontent.com/107078811/184185601-23bccdb6-8cdf-4b14-8087-3dff10f79a94.png)

I can also add a taint to an existing node pool with no taint

Added node pool
az aks nodepool add     --resource-group christiancluster_group    --cluster-name christiancluster    --name taintnp2     --no-wait

![image](https://user-images.githubusercontent.com/107078811/184185736-fd734df1-1a92-4f85-af2b-f827eb5e173d.png)

Added taint post creation

az aks nodepool update --cluster-name christiancluster --resource-group christiancluster_group --name taintnp2 --node-taints key1=value1:NoSchedule

![image](https://user-images.githubusercontent.com/107078811/184185842-cc81ae76-a0e3-4043-a3df-f94613ccd754.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fce7ab-ab56-44c6-b9a8-405444247a0b
* Version Independent ID: dabbb6c6-c616-a6ec-61f6-1b9d3bb069e8
* Content: [az aks nodepool](https://docs.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest#az-aks-nodepool-update)
* Content Source: [latest/docs-ref-autogen/aks/nodepool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks/nodepool.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@christianag54 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
The above PR has been created and it is currently pending under review.
