### ISSUE TITLE
Not possible to enable Native Client Support through az CLI

### ISSUE THREAD

**Issue by Strobodov** [Azure/azure-cli#23525]
## Describe the bug

**Command Name**
`az network bastion ssh`

**Errors:**
When you set up Azure Bastion with `az network bastion create` there are various required and optional parameters, but to _enable native client support_ is impossible. It is also not shown as parameter in the `arm template` that you can download from Azure Portal.

This means you are required to log in to Azure Portal to manually check a box.  Would be nice if an extra optional parameter was added such as `--native-client-support {Enable, Disable (default: Disable)}` for use with `az cli` or ARM templates.

Without this step it is not possible to connect to VM's on non-public subnet through Bastion with `az network bastion ssh`. After enabling  this works fine.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

## Environment Summary
```
Linux-5.18.16-100.fc35.x86_64-x86_64-with-glibc2.34, Fedora Linux 35 (Workstation Edition)
Python 3.10.5
Installer: PIP

azure-cli 2.39.0

Extensions:
account 0.2.3
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team
