### ISSUE TITLE
Set `content_type` of keyvault secrets at creation time

### ISSUE THREAD

**Issue by ltalirz** [Azure/azure-cli#23527]
**Related command**
`az keyvault secret set`

**Is your feature request related to a problem? Please describe.**
Azure keyvault secrets [have associated content types](https://docs.microsoft.com/en-us/azure/key-vault/secrets/about-secrets), but `az keyvault secret set` currently does not allow to set the content type of the created secret.

In enterprise Azure subscriptions, policies may forbid the creation of secrets without associated content type, which then makes it impossible to create keyvault secrets via the azure cli.

**Describe the solution you'd like**
`az keyvault secret set` could get a `--content-type` option.
If the option is not provided, the default behavior would remain unchanged (no content type passed).

**Describe alternatives you've considered**
In cases where it suffices to set the content type of the secret *after* creation, this can already be achieved today via `az keyvault secret set-attributes` (see [here](https://stackoverflow.com/q/58097004/1069467)).
However, this does not solve the problem when an Azure policy is in place. 

**Additional context**
Issue has been raised on StackOverflow before https://stackoverflow.com/q/58097004/1069467

**Comment by ltalirz** [comment]
For anyone needing a workaround for this issue, here is a quick hack to get the azure-cli to set a "password" content type when no content type is provided (fix is for my specific azure-cli version, your mileage may vary)

```
--- /tmp/key_vault_client.py    2022-08-14 13:55:02.571314002 +0000
+++ /opt/az/lib/python3.10/site-packages/azure/keyvault/v7_0/key_vault_client.py        2022-08-14 13:52:23.882755180 +0000
 
@@ -1595,6 +1595,7 @@
 
         :raises:
 
          :class:`KeyVaultErrorException<azure.keyvault.v7_0.models.KeyVaultErrorException>`
 
         """
 
+        content_type = content_type or "password"
 
         parameters = models.SecretSetParameters(value=value, tags=tags, content_type=content_type, secret_attributes=secret_attributes)
 
 
 
         # Construct URL
```

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
@ltalirz Actually the parameter for setting `content_type` in CLI is `--description`, I have added an alias `--content-type` for the original `--description` in #23988

**Comment by ltalirz** [comment]
Great, thanks for adding this @evelyn-ys !
