### ISSUE TITLE
Onboard Azure Functions commands

### ISSUE THREAD

**Issue by Zazcallabah** [Azure/azure-cli#2352]
The https://github.com/Azure/azure-functions-cli project has removed the command that creates azure function apps, and instead references to this repository (https://github.com/Azure/azure-functions-cli/issues/50)

Before I could just do 

    func azure functionapp create -n "$name" -g "$group" -s "$subscription" -p "Consumption" -l "West Europe"

What do I need to do in order to create function apps now? Or, alternatively, please point me to the relevant documentation. Unfortunately trying to google "azure cli create function app" only gives me guides on running functions locally.

**Comment by tjprescott** [comment]
Hi @Zazcallabah currently the Azure CLI 2.0 appservice command module only supports creation of app service plans and web apps. Support for function apps, logic apps, mobile apps and API apps will be added in the future.

**Comment by yugangw-msft** [comment]
Not actionable, closing. We will announce when the work is done

**Comment by yugangw-msft** [comment]
Onboard-ed and released. Please open individual issues for feature requests
