### ISSUE TITLE
AZ resource group create issue in VS Code cli command

### ISSUE THREAD

**Issue by ramesheducation** [Azure/azure-cli#23535]
## Describe the bug

**Command Name**
`az deployment group create`

**Errors:**
```
[Errno 2] No such file or directory: 'C:\\Learning\\Azure Cloud Architect\\az-303\\RandEnt-Project\\randent-rg-template\\rg-parameters.json'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az deployment group create --resource-group {} --template-file {}`

## Environment Summary
```
Linux-5.4.0-1089-azure-x86_64-with-glibc2.28 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.10.5
Installer: DEB

azure-cli 2.39.0

Extensions:
ai-examples 0.2.5
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@ramesheducation Please see if this document [auto-translation-of-resource-ids](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_with_git_bash.md#auto-translation-of-resource-ids) can solve your problem

**Comment by navba-MSFT** [comment]
@ramesheducation Thanks for reaching out to us and reporting this issue. I created the same folder hierarchy as yours and ran the command and it did work fine. Could you please confirm if you ran the command like below ? 

> az deployment group create --resource-group MyRgName --template-file "C:\Learning\Azure Cloud Architect\az-303\RandEnt-Project\randent-rg-template\rg-parameters.json"

Sharing my Azure CLI version if that helps.

C:\>az version
{
  **"azure-cli": "2.39.0",**
  "azure-cli-core": "2.39.0",
  "azure-cli-telemetry": "1.0.6"
  }
  
Hope this helps.

**Comment by navba-MSFT** [comment]
@ramesheducation I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ramesheducation The action is currently pending on you to test the above action plan. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
