### ISSUE TITLE
Misleading example

### ISSUE THREAD

**Issue by Deondrede** [Azure/azure-cli#23537]
In the example section on this page it shows the token as 
```
az devops security permission update  --allow-bit 7 --namespace-id 52d39943-cb85-4d7f-8fa8-c6baac873819 --subject user@fabrikam.com --token "$PROJECT:vstfs:///Classification/TeamProject/e479xxxx-2be8-xxxx-bb0b-3a0209cxxxx"
```
The example fails to acknowledge that in order to for the token parameter to be correct you need to escape the $.
The working example is 
```
az devops security permission update  --allow-bit 7 --namespace-id 52d39943-cb85-4d7f-8fa8-c6baac873819 --subject user@fabrikam.com --token "`$PROJECT:vstfs:///Classification/TeamProject/e479xxxx-2be8-xxxx-bb0b-3a0209cxxxx"
```
The first command also does not fail or provide an error of any kind. It would be nice to have this rectified to avoid future confusion

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1121ea02-7c35-1af4-0226-e277c8d1d566
* Version Independent ID: 5697a5d6-2a89-282c-1b83-22bf82068a6c
* Content: [az devops security permission](https://docs.microsoft.com/en-us/cli/azure/devops/security/permission?view=azure-cli-latest#az-devops-security-permission-update)
* Content Source: [latest/docs-ref-autogen/devops/security/permission.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/devops/security/permission.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding Service team to look into the devops issue.

 @v-anvashist, @V-hmusukula Could you please look into this and provide an update ?

**Comment by Arvindgade** [comment]
@Deondrede could you please check the below similar issue having the solution provided
https://github.com/Azure/azure-cli/issues/23759
Hope this will work. Thanks!

**Comment by RakeshMohanMSFT** [comment]
Will be fixed by this PR https://github.com/Azure/azure-devops-cli-extension/pull/1333

**Comment by RakeshMohanMSFT** [comment]
This PR will fix this issue https://github.com/Azure/azure-devops-cli-extension/pull/1333
