### ISSUE TITLE
Storage blob upload fails if tags parameter is used

### ISSUE THREAD

**Issue by rellis-of-rhindleton** [Azure/azure-cli#23536]
This is with Azure CLI version 2.37.0.

**Related command**
az storage blob upload

**Describe the bug**
Uploading a file to blob storage works fine if the --tags parameter is not used, but if it is used, a permission denied error occurs. 

This is with a storage account using roles for authorization rather than a key or token. The Storage Blob Data Contributor role has been granted. 

**To Reproduce**
These are the commands I'm using. This is on a storage blob account to which I have been granted Storage Blob Data Contributor. 

Without the tags parameter:
```
az storage blob upload --auth-mode login --account-name storageacctname -c containername -n blobname -f ./filename.txt -t block --overwrite true --no-progress

Argument '--overwrite' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
{
  "client_request_id": "(redacted)",
  "content_md5": "(redacted)",
  "date": "(redacted)",
  "encryption_key_sha256": null,
  "encryption_scope": null,
  "etag": "(redacted)",
  "lastModified": "(redacted)",
  "request_id": "(redacted)",
  "request_server_encrypted": true,
  "version": "2021-06-08",
  "version_id": null
}
``` 

Now add the tags parameter, and it fails:
```
az storage blob upload --auth-mode login --account-name storageacctname -c containername -n blobname -f ./filename.txt -t block --overwrite true --no-progress --tags ""

Argument '--overwrite' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus

You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"
    "Storage Table Data Contributor"
    "Storage Table Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.
```

**Expected behavior**
The --tags parameter (either `--tags key=value` or `--tags ""`) should not affect authorization.

**Environment summary**
This occurs when running on Windows 10 from my own account, and also when running on an Ubuntu GitHub runner using a service principal.

**Additional context**

It is possible that adding tags to blobs requires different roles than Storage Blob Data Contributor, but there isn't anything in the documentation that I can find that says so.

I have also tried the upload command using an account key, rather than roles, and it works as expected whether the tags parameter is present or not.

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
Need storage server side debug

**Comment by navba-MSFT** [comment]
@rellis-of-rhindleton Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@rellis-of-rhindleton The error message talks about the permissions issue. [This](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-index-how-to?tabs=azure-cli#upload-a-new-blob-with-index-tags) article talks about the permissions required to _Upload a new blob with index tags_.

>This task can be performed by a [Storage Blob Data Owner](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-owner) or a security principal that has been given permission to the Microsoft.Storage/storageAccounts/blobServices/containers/blobs/tags/write

Please grant the Storage Blob Data Owner permission to your user at the Storage account or container level and run the command again. Hope this helps.

**Comment by rellis-of-rhindleton** [comment]
Ah, thank you. I wondered if a different role was required! The documentation for the Azure CLI is what I was reading. It doesn’t mention this. But the blob storage docs are clear. If I get time I’ll submit a pull request for the CLI doc.
