### ISSUE TITLE
Wrong Explaination for “az signalr upstream Clear”

### ISSUE THREAD

**Issue by pankajraj1810** [Azure/azure-cli#23538]
[The Explaination for az signalr upstream Clear mentions to list the setting rather than clearing. It is at two position which I have highlighted in the snapshot  attached]

![F9EBD1B4-BA6D-4476-ABCC-818BC0808205](https://user-images.githubusercontent.com/111325563/184772510-5c677897-028e-4f6d-99f9-462befe337d9.jpeg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0e82e1d-879c-bb74-fc9d-3867b4b8f8be
* Version Independent ID: 492ef7f0-55ee-4d11-6131-4562e6f0e9c2
* Content: [az signalr upstream](https://docs.microsoft.com/en-us/cli/azure/signalr/upstream?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/signalr/upstream.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/signalr/upstream.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@pankajraj1810 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@pankajraj1810 Thanks for reporting this issue and providing the feedback. The above PR has bene filed for the same. It is currently under review.
