### ISSUE TITLE
Microsoft.OperationalInsights: New stable version 2022-10-01 support.

### ISSUE THREAD

**Issue by dulikvor** [Azure/azure-cli#23546]
### Related command

[CLI_OperationInsights_2022-10-01.docx](https://github.com/Azure/azure-cli/files/9351167/CLI_OperationInsights_2022-10-01.docx)

### Resource Provider

Microsoft.OperaitonalInsights

### Description of Feature or Work Requested

New stable version, adding the following new and breaking change functionalities:

Resource - Workspaces:
* Identity support.

Resource - Tables:
* Search cancel operation.
* Response contract changes.

### Minimum API Version Required

2022-10-01

### Swagger PR link

https://github.com/Azure/azure-rest-api-specs/pull/20236

### Target Date

2022-10-01

**Comment by dulikvor** [comment]
Hi, we are looking to postpone the release date to February 1st 2023.

**Comment by dulikvor** [comment]
Please make sure to consult with me prior for releasing the changes. one of the LA regions do not support the change yet.

**Comment by kairu-ms** [comment]
Postpone to Jan 2023

**Comment by dulikvor** [comment]
Hi, sadly there was another push back for GA, new deadline April 1st 2023, let's review the release schedule in end of February.

**Comment by dulikvor** [comment]
Hi, 2022-10-01 is ready and available in prod cloud realm. feel free to move forward with the required development.

Also, worth to note - RestoredLogs.endRestoreTime, RestoredLogs.startRestoreTime do not support date-time anymore but restricted to date only.
