### ISSUE TITLE
Expose "View all role assignments" via az CLI

### ISSUE THREAD

**Issue by papadeltasierra** [Azure/azure-cli#23548]
**Related command**
az role assignment list

**Is your feature request related to a problem? Please describe.**
This command appears to list only **my** role assignments.  From Azure Portal I can list assignments for all users, groups etc.  I want the same function so I can write a simple-ish auditing tool.

**Describe the solution you'd like**
Some option that allows the output to be for all users not just me.

**Describe alternatives you've considered**
Haven't managed to find one.  The REST API might do it (will try shortly) but certainly don't want to use the Azure Portal and screen scrape.

**Additional context**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by dallmair** [comment]
There is `--all` nowadays, which addresses this I think. Maybe simply forgot to close?

**Comment by jiasli** [comment]
> This command appears to list only **my** role assignments.

This is not true. Without specifying `--assignee`, `az role assignment list` does show role assignments of all users/groups/service principals on the subscription.

`--all` is used to show role assignments on sub-scopes, such as resource groups and resources.

Make sure you have the correct RBAC role assignment (such as **Reader** role) to list role assignments: https://learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments-list-portal#prerequisites
