### ISSUE TITLE
[App Service] [Feature Request] Allow streaming log tail as part of browsing a web app

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2354]
I frequently find myself running `az appservice web browse`, and then immediately running `az appservice web log tail` in order to view the stdout of the app I'm testing.

In order to provide an "accelerator" for this workflow, it would be nice if the `az appservice web browse` command had a flag that allowed you to begin reading the logs immediately after launching the app in a browser, without requiring the extra gesture to do so. This would effectively be the CLI equivalent of "running" an app within an IDE, which traditionally has the effect of launching the app, but also displaying output as well.

**Comment by yugangw-msft** [comment]
Agreed.
