### ISSUE TITLE
Azure CLI SDK code gen for Azure Automanage

### ISSUE THREAD

**Issue by AndrewCS149** [Azure/azure-cli#23552]
### Resource Provider

providersMicrosoft.Compute/virtualMachines/<vmName>/providers/Microsoft.Automanage

### Description of Feature or Work Requested

Autorest code generation support for Azure CLI extensions.

### Minimum API Version Required

2022-05-04

### Swagger PR link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/automanage/resource-manager/Microsoft.Automanage/stable/2022-05-04/automanage.json

### Request Example

[Create configuration profile](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/automanage/resource-manager/Microsoft.Automanage/stable/2022-05-04/examples/createOrUpdateConfigurationProfile.json)
[Create configuration profile assignment](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/automanage/resource-manager/Microsoft.Automanage/stable/2022-05-04/examples/createOrUpdateConfigurationProfileAssignment.json)

### Target Date

2022-08-19

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by Jacekey23** [comment]
Hi @AndrewCS149,
If this is a request for onboarding a service RP, here is the Azure formal onboarding process via a survey. Noted that it'is one of necessary step to onboard the new RP with CLI team(https://aka.ms/PLRCLIOnboardSurvey).
you might also need the CLI onboarding meeting conversation if possible (Please book 15-min slot here if you have not already done so: https://aka.ms/PLRCLIOnboardCalendar) APEX onboarding.

Let us know anything we could help. Thx.

**Comment by AndrewCS149** [comment]
Thanks @Jacekey23! I've submitted the form.

**Comment by calvinhzy** [comment]
CLI package is ready for this feature, feel free to follow below steps for test:

install/update cli:
`pip install azure-cli -U`

install Automange extension
`az extension add -n automanage`

try new commands:
`az automanage -h` to see all the commands and you can use -h for the commands to see their required arguments
`az automanage configuration-profile create -h`
`az automanage configuration-profile-assignment vm create` -h
