### ISSUE TITLE
$filter example not present

### ISSUE THREAD

**Issue by MarcoEnxuto** [Azure/azure-cli#23551]
Hi,
This page does not show an example on how to filter the results.
You should provide an example.
I'm struggling to get the results i want while i need to delete some content key policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c257bbd6-4d8c-aedf-48dc-fa8a34304984
* Version Independent ID: c76388c4-8cb7-6702-255f-2872bd617473
* Content: [az ams content-key-policy](https://docs.microsoft.com/en-us/cli/azure/ams/content-key-policy?view=azure-cli-latest#az-ams-content-key-policy-delete)
* Content Source: [latest/docs-ref-autogen/ams/content-key-policy.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ams/content-key-policy.yml)
* Service: **media-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@MarcoEnxuto Thank you for reaching out, we will help you with an example.

**Comment by RakeshMohanMSFT** [comment]
@MarcoEnxuto Here is an example you can try this.
az ams content-key-policy list -a issue23551mediaservices -g Issue23551 --filter "properties/lastModified gt 2022-08-16 or properties/created lt 2022-08-17"

**Comment by MarcoEnxuto** [comment]
@RakeshMohanMSFT please update the doc with that example. Thanks.
