### ISSUE TITLE
sdk-auth Deprectated ?

### ISSUE THREAD

**Issue by ravitellakula** [Azure/azure-cli#23561]
## Describe the bug

**Command Name**
`az account show`

**Errors:**
```
unrecognized arguments: --sdk-auth

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account show --sdk-auth --debug`

## Environment Summary
```
macOS-12.5-x86_64-i386-64bit, Darwin 21.6.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.39.0

Extensions:
azure-devops 0.23.0
application-insights 0.1.16

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by RakeshMohanMSFT** [comment]
@revinjchalil Please go through this issue for further details https://github.com/MicrosoftDocs/azure-docs/issues/92827

**Comment by ravitellakula** [comment]
Well, i wasn't doing `az ad sp create-for-rbac` but instead was doing a `az account show`. So, is it deprecated for both of these commands?

Also, what was really weird was - look at the output in the below screen shot - the first example it lists down is with the option of `--sdk-auth`  - **_missing documentation update?_**

![image](https://user-images.githubusercontent.com/69060107/185509339-81eafda6-7959-4637-8979-b0f3b325090e.png)

**Comment by jiasli** [comment]
`az ad sp create-for-rbac` still has `--sdk-auth`, but we don't recommend using it anymore.

`--sdk-auth` was dropped from `az account show` in https://github.com/Azure/azure-cli/pull/21219. You may check that PR for more details.

The examples are from Aladdin AI knowledge base. We are working with Aladdin team to remove it.

**Comment by ravitellakula** [comment]
@jiasli  - Thank you for the clarification. Our use case is indeed to leverage the Azure Login Github Action. If `--sdk-auth` is not recommended, what is the alternate way to use this Github Action?

Unfortunately, our organization needs elevated privilege(s) to execute the `az ad sp create-for-rbac` command. Anyways, I think the option for me is to manually construct the `json` to leverage in Github Actions.

**Comment by jiasli** [comment]
We have removed the outdated example with Aladdin recommendation team:

![image](https://user-images.githubusercontent.com/4003950/189295009-984864f3-2d9b-4405-891b-a7c638ad81ff.png)
