### ISSUE TITLE
Request CLI for Liftr.Nginx

### ISSUE THREAD

**Issue by limingu** [Azure/azure-cli#23567]
Information required from service team:

1.Resource provider. What is the Azure resource provider your feature is part of?
NGINX.NGINXPLUS

2. Description of feature or work requested. Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
Create CLI commands for NGINX.

3. Minimum API version required. What is the minimum API version of your service required to implement your feature?
2022-08-01

4.Swagger link. Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/nginx/resource-manager/NGINX.NGINXPLUS/stable/2022-08-01/swagger.json

5. Target date. If you have a target date for releasing this feature/work, please provide it. While we can't guarantee these dates, it will help us prioritize your request against other requests.
11/01/2022

6. Where do you want the feature to locate? A command module or an extension? Here is a [Comparison](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/onboarding/azurecli/modules_and_extensions).
An extension

7.Status of the service. Is it in preview or GA?
Public preview

8.Examples of the feature. Usually REST API specs repo should contain examples. An independent documentation or tutorial is also OK.
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/nginx/resource-manager/NGINX.NGINXPLUS/stable/2022-08-01/examples

9.Prerequisite to use this feature. Whitelisting subscription? Registering the feature for subscription? Is it available in public Azure?
No prerequisite. It is available in public Azure.

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by Jacekey23** [comment]
@limingu 
If this is a request for onboarding a service RP, here is the Azure formal onboarding process via a survey. Noted that it'is one of necessary step to onboard the new RP with CLI team(https://aka.ms/PLRCLIOnboardSurvey).
you might also need the CLI onboarding meeting conversation if possible (Please book 15-min slot here if you have not already done so: https://aka.ms/PLRCLIOnboardCalendar) APEX onboarding.

Let us know anything we could help. Thx.

**Comment by limingu** [comment]
@Jacekey23 we have done the PLR survey and the CLI onboarding meeting.
Here is the work item: https://msazure.visualstudio.com/One/_workitems/edit/14618432
At that time, we only had the preview version swagger. Now we just have the stable version swagger ready. Is there anything else needed from us? Thanks!

**Comment by jsntcy** [comment]
Close this as it has been supported in https://github.com/Azure/azure-cli-extensions/tree/main/src/nginx
