### ISSUE TITLE
Service Principal Credential Reset does not appear in Azure Portal App Registration GUI 

### ISSUE THREAD

**Issue by arindam0310018** [Azure/azure-cli#23566]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bef1f12-de16-93ed-1cb7-3f3d5d99d786
* Version Independent ID: 4e9329a6-50f8-ee2a-af63-f750d66ed574
* Content: [az ad sp credential](https://docs.microsoft.com/en-us/cli/azure/ad/sp/credential?view=azure-cli-latest#az-ad-sp-credential-reset)
* Content Source: [latest/docs-ref-autogen/ad/sp/credential.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ad/sp/credential.yml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by arindam0310018** [comment]
Hello Team, I am Resetting Service Principal Using az cli and az devops.
The Reset works with the reference command - "az ad sp credential reset".

The new Secret gets stored in KV, however, when I browse to Azure Portal --> App Registration --> Required App Registration --> Certificates and Secrets, I cannot see the New Secret Generated. There is no new entry found.

All details can be found in my blog - https://dev.to/arindam0310018/reset-service-principal-secret-and-store-in-key-vault-using-az-devops-2h8o

Please let me know if this is bug or if my understanding is in correct.

Thank you

Arindam Mitra

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by arindam0310018** [comment]
Hello Team,
Is there any update? Can you please let me know when time permits.

Many Thanks
Regards, Arindam Mitra

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/21195#issuecomment-1205007225.

**Comment by jiasli** [comment]
@madforchili, that depends on the business logic of AKS. +@FumingZhang to help take a look.

**Comment by FumingZhang** [comment]
Hey @madforchili, @jiasli, basically, the `app credential reset` command also applies to the AKS cluster.

This is actually related to the relationship between the app and the sp itself. For a single tenant app, the two reset commands are almost equivalent, while for a multi tenant app, the `sp credential reset` only takes effect for the corresponding tenant, while the `app credential reset` will take effect for all tenants.

**Comment by mgstate** [comment]
Any changes expected to allow credential list to show sp, seems like an important thing to see as well. only way i got it to show was az ad sp show currently
