### ISSUE TITLE
Azure SQL LTR recovery from backup fails with internal server error

### ISSUE THREAD

**Issue by jakub-i** [Azure/azure-cli#23577]
Azure ClI version
azure-cli                         2.39.0

core                              2.39.0
telemetry                          1.0.6 *

Extensions:
ai-examples                        0.2.5
ssh                                1.1.2

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/jakub/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.10/site-packages/azure-cli-extensions'

Python (Linux) 3.10.5 (main, Jul 29 2022, 03:26:48) [GCC 8.3.0]

**Related command**
az sql db ltr-backup restore --backup-id <backup-id> --dest-database <dest-database> --dest-resource-group <dest-resource-group> --dest-server <dest-sql-server>

**Describe the bug**
Get following output when executing command above:
(InternalServerError) An unexpected error occured while processing the request. Tracking ID: 'be502c18-93d7-4063-bd8c-3555bfb0df72'
Code: InternalServerError
Message: An unexpected error occured while processing the request. Tracking ID: 'be502c18-93d7-4063-bd8c-3555bfb0df72

**To Reproduce**
Use the _related command_ with appropriate Azure SQL database.

**Expected behavior**
The same as in portal, when recovering a backup, a copy of the database based on the backup is created.

**Environment summary**
The command failed in our GitLab pipeline and in Azure Portal Cloud Shell

**Additional context**
I have succesfully used the command before, but I have no other information to go on with and hence no clue as to how to proceed.

\Jakub

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@jakub-i  Thank you for reaching out, we are looking into it.

**Comment by jakub-i** [comment]
@RakeshMohanMSFT Thanks, looking forward to hearing from you

\Jakub

**Comment by RakeshMohanMSFT** [comment]
@jakub-i Can you share debug trace with us please?

**Comment by jakub-i** [comment]
I get following stack trace when running the command with the --debug option:

`ack.cli: Command arguments: ['sql', 'db', 'ltr-backup', 'restore', '--backup-id', '/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RES_GROUP_NAME>/providers/Microsoft.Sql/locations/westeurope/longTermRetentionServers/sql-mssql-template-test-singlet/longTermRetentionDatabases/sqldb-mssql-template-test-singlet/longTermRetentionBackups/<BACKUP_ID>', '--dest-database', 'sqldb-mssql-template-test-singlet-ltrtest', '--dest-resource-group', '<RES_GROUP_NAME>', '--dest-server', 'sql-mssql-template-test-singlet', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7ff1d9ff5b80>, <function OutputProducer.on_global_arguments at 0x7ff1d9f0a5e0>, <function CLIQuery.on_global_arguments at 0x7ff1d9f29b80>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'sql': ['azure.cli.command_modules.sql', 'azure.cli.command_modules.sqlvm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: sql                       0.010        45       179
cli.azure.cli.core: sqlvm                     0.190         4        18
cli.azure.cli.core: Total (2)                 0.201        49       197
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.123         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.123         1         1  
cli.azure.cli.core: Loaded 49 groups, 198 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : sql db ltr-backup restore
cli.azure.cli.core: Command table: sql db ltr-backup restore
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7ff1d94ef430>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/jakub/.azure/commands/2022-08-22.07-01-23.sql_db_ltr-backup_restore.127.log'.
az_command_data_logger: command args: sql db ltr-backup restore --backup-id {} --dest-database {} --dest-resource-group {} --dest-server {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7ff1d95238b0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7ff1d9489d30>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7ff1d9489e50>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7ff1d9f0a670>, <function CLIQuery.handle_query_parameter at 0x7ff1d9f29c10>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7ff1d9489dc0>]
Command group 'sql db ltr-backup' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=SqlManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2812
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=SqlManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2812
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2812
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1661155905' -> 1661155905
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RES_GROUP_NAME>/providers/Microsoft.Sql/servers/sql-mssql-template-test-singlet?api-version=2021-02-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '3b6c25b2-21e8-11ed-acbb-42601b029581'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sql db ltr-backup restore'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--backup-id --dest-database --dest-resource-group --dest-server --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.39.0 (RPM) azsdk-python-mgmt-sql/4.0.0b2 Python/3.9.13 (Linux-5.4.0-1089-azure-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RES_GROUP_NAME>/providers/Microsoft.Sql/servers/sql-mssql-template-test-singlet?api-version=2021-02-01-preview HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '1ebb5707-6255-46ec-807a-e8141d535006'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11998'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '4dc916b4-b185-4ab4-8726-c1cc44271555'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20220822T070123Z:4dc916b4-b185-4ab4-8726-c1cc44271555'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 22 Aug 2022 07:01:23 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"identity":{"principalId":"f1c83bb9-8425-496c-b713-5bcee86b6f12","type":"SystemAssigned","tenantId":"a1993db6-d7ac-4499-8555-bc4022bf5429"},"kind":"v12.0","properties":{"administratorLogin":"mssql-template-test-nonp-admin","version":"12.0","state":"Ready","fullyQualifiedDomainName":"sql-mssql-template-test-singlet.database.windows.net","privateEndpointConnections":[{"id":"/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RES_GROUP_NAME>/providers/Microsoft.Sql/servers/sql-mssql-template-test-singlet/privateEndpointConnections/pe-mssql-template-test-singlet-3ccf244e-6a33-405e-b0e0-16fa57647c57","properties":{"privateEndpoint":{"id":"/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RES_GROUP_NAME>/providers/Microsoft.Network/privateEndpoints/pe-mssql-template-test-singlet"},"groupIds":["sqlServer"],"privateLinkServiceConnectionState":{"status":"Approved","description":"Auto-approved","actionsRequired":"None"},"provisioningState":"Ready"}}],"minimalTlsVersion":"1.2","publicNetworkAccess":"Disabled","administrators":{"administratorType":"ActiveDirectory","principalType":"Group","login":"alm-np-integration","sid":"e70f4f87-4c68-4d9c-9dcf-864293b7ae48","tenantId":"a1993db6-d7ac-4499-8555-bc4022bf5429"},"restrictOutboundNetworkAccess":"Disabled"},"location":"westeurope","tags":{"stage":"T","AppOwner":"<*****>","AppProvider":"<**************>","BusinessCriticality":"Supporting","BusinessUnit":"Architects","ComplianceReview":"none","DataClassification":"K2:Confidential Data","DeptNumber":"3160","Environment":"NonProduction","ProjectCode":"31190","Runtime":"24hrs","SLA":"none","Solution":"Solution for non-migrated integrations","SystemService":"APIM"},"id":"/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RES_GROUP_NAME>/providers/Microsoft.Sql/servers/sql-mssql-template-test-singlet","name":"sql-mssql-template-test-singlet","type":"Microsoft.Sql/servers"}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2812
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1661155905' -> 1661155905
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RES_GROUP_NAME>/providers/Microsoft.Sql/servers/sql-mssql-template-test-singlet/databases/sqldb-mssql-template-test-singlet-ltrtest?api-version=2021-05-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '465'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '3b6c25b2-21e8-11ed-acbb-42601b029581'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sql db ltr-backup restore'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--backup-id --dest-database --dest-resource-group --dest-server --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.39.0 (RPM) azsdk-python-mgmt-sql/4.0.0b2 Python/3.9.13 (Linux-5.4.0-1089-azure-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "westeurope", "properties": {"createMode": "RestoreLongTermRetentionBackup", "longTermRetentionBackupResourceId": "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RES_GROUP_NAME>/providers/Microsoft.Sql/locations/westeurope/longTermRetentionServers/sql-mssql-template-test-singlet/longTermRetentionDatabases/sqldb-mssql-template-test-singlet/longTermRetentionBackups/<BACKUP_ID>"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RES_GROUP_NAME>/providers/Microsoft.Sql/servers/sql-mssql-template-test-singlet/databases/sqldb-mssql-template-test-singlet-ltrtest?api-version=2021-05-01-preview HTTP/1.1" 202 88
cli.azure.cli.core.sdk.policies: Response status: 202
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '88'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Location': 'https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RES_GROUP_NAME>/providers/Microsoft.Sql/locations/westeurope/databaseOperationResults/85d56cc5-5f87-4502-ac28-6139775acb1d?api-version=2021-05-01-preview'
cli.azure.cli.core.sdk.policies:     'Retry-After': '15'
cli.azure.cli.core.sdk.policies:     'Azure-AsyncOperation': 'https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RES_GROUP_NAME>/providers/Microsoft.Sql/locations/westeurope/databaseAzureAsyncOperation/85d56cc5-5f87-4502-ac28-6139775acb1d?api-version=2021-05-01-preview'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '85d56cc5-5f87-4502-ac28-6139775acb1d'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'cb82bb0a-9d28-454b-93e4-3dc6bcff30ec'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20220822T070124Z:cb82bb0a-9d28-454b-93e4-3dc6bcff30ec'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 22 Aug 2022 07:01:23 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"operation":"CreateRestoreFromLtrBackupRequest","startTime":"2022-08-22T07:01:24.237Z"}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RES_GROUP_NAME>/providers/Microsoft.Sql/locations/westeurope/databaseAzureAsyncOperation/85d56cc5-5f87-4502-ac28-6139775acb1d?api-version=2021-05-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '3b6c25b2-21e8-11ed-acbb-42601b029581'
cli.azure.cli.core.sdk.policies:     'CommandName': 'sql db ltr-backup restore'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--backup-id --dest-database --dest-resource-group --dest-server --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.39.0 (RPM) azsdk-python-mgmt-sql/4.0.0b2 Python/3.9.13 (Linux-5.4.0-1089-azure-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RES_GROUP_NAME>/providers/Microsoft.Sql/locations/westeurope/databaseAzureAsyncOperation/85d56cc5-5f87-4502-ac28-6139775acb1d?api-version=2021-05-01-preview HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Retry-After': '15'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '70e4f73f-2c56-4ddc-ae09-599b2d589fda'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11998'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'a7a2c2f9-11b0-49a8-842b-9cdcaabad21f'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20220822T070139Z:a7a2c2f9-11b0-49a8-842b-9cdcaabad21f'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 22 Aug 2022 07:01:38 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"name":"85d56cc5-5f87-4502-ac28-6139775acb1d","status":"Failed","startTime":"2022-08-22T07:01:24.237Z","error":{"code":"InternalServerError","message":"An unexpected error occured while processing the request. Tracking ID: '70e4f73f-2c56-4ddc-ae09-599b2d589fda'"}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/base_polling.py", line 517, in run
    self._poll()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/base_polling.py", line 556, in _poll
    raise OperationFailed("Operation failed or canceled")
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 708, in _run_job
    result = LongRunningOperation(cmd_copy.cli_ctx, 'Starting {}'.format(cmd_copy.name))(result)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 1013, in __call__
    raise exception
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 1000, in __call__
    result = poller.result()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/_poller.py", line 255, in result
    self.wait(timeout)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/_poller.py", line 275, in wait
    raise self._exception # type: ignore
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/_poller.py", line 192, in _start
    self._polling_method.run()
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/polling/base_polling.py", line 535, in run
    raise HttpResponseError(
azure.core.exceptions.HttpResponseError: (InternalServerError) An unexpected error occured while processing the request. Tracking ID: '70e4f73f-2c56-4ddc-ae09-599b2d589fda'
Code: InternalServerError
Message: An unexpected error occured while processing the request. Tracking ID: '70e4f73f-2c56-4ddc-ae09-599b2d589fda'

cli.azure.cli.core.azclierror: (InternalServerError) An unexpected error occured while processing the request. Tracking ID: '70e4f73f-2c56-4ddc-ae09-599b2d589fda'
Code: InternalServerError
Message: An unexpected error occured while processing the request. Tracking ID: '70e4f73f-2c56-4ddc-ae09-599b2d589fda'
az_command_data_logger: (InternalServerError) An unexpected error occured while processing the request. Tracking ID: '70e4f73f-2c56-4ddc-ae09-599b2d589fda'
Code: InternalServerError
Message: An unexpected error occured while processing the request. Tracking ID: '70e4f73f-2c56-4ddc-ae09-599b2d589fda'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7ff1d94ef670>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 17.062 seconds (init: 0.107, invoke: 16.955)
telemetry.save: Save telemetry record of length 3439 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/jakub/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.`

**Comment by RakeshMohanMSFT** [comment]
@jakub-i I see that the target database's service level objective "SLO" (Elastic Pool) or edition is invalid. Checking further..
