### ISSUE TITLE
az synapse workspace create should provide the option to specify the Managed Resource Group name.

### ISSUE THREAD

**Issue by plynch66** [Azure/azure-cli#23579]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az synapse workspace create

**Describe the bug**
Deploying an Azure Synapse workspace requires a separate managed resource group. This resource group should be able to be created when running the az synapse workspace create CLI command. Currently this is not possible. This is clearly an omission and should be rectified.

**To Reproduce**
az synapse workspace create

**Expected behavior**
Should give the user the option to create the managed resource group. It doesn't

**Environment summary**
Azure CLI 2.39.0 on Windows 10

**Additional context**
None

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding Service team to look into this ask.

@wonner @zesluo Could you please look into this and provide an update ?

**Comment by kevinzz6** [comment]
Hi @plynch66, we will add a parameter "--managed-resource-group-name" to support managed resource group feature. Wish to deploy on the next release. Thank you.
