### ISSUE TITLE
Az cli webapp ip restrictions: can't add CIDR range in similar matter as in Azure Portal

### ISSUE THREAD

**Issue by tokleine** [Azure/azure-cli#23576]
## Describe the bug

**Command Name**
`az webapp config access-restriction add`

**Errors:**
```
XXX.XXX.XXX.XXX/29 has host bits set; I obscured the IP

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp config access-restriction add -g {} -n {} --rule-name {} --action {} --ip-address {} --priority {}`

## Expected Behavior
Using the Azure Portal I can add this exact CIDR Range to the IP Restrictions. With the CLI I need to chunk it into 8 subranges. is this expected behavior or am I misunderstanding the usage of CIDR?

I am also able to add CIDR Ranges of /32, /31, /30 using the CLI.
## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.3
Installer: MSI

azure-cli 2.35.0
```

**Comment by yonzhan** [comment]
route to CXP team
