### ISSUE TITLE
ERROR: Parameter 'tags' must be of type 'dict[str, str]' in command az sig image-version create

### ISSUE THREAD

**Issue by rupeshyl** [Azure/azure-cli#23572]
With latest version azure cli 2.39.0 out image build pipeline is failing to create and impacting production upgrades. 

Kindly suggest when will be new fix ready

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
Known issue, fixed by this PR #23393, it will be released in **09-06**

**Comment by rupeshyl** [comment]
Thank you Team
