### ISSUE TITLE
Deployment - PostgreSQL Flexible Server by Azure Portal (InternalServerError)

### ISSUE THREAD

**Issue by Wexleron** [Azure/azure-cli#23578]
Hi,

i occur this problem about a day now. Deploying PostgreSQL Flexible server worked for me normally in the past (3 months last time). Now it throws "InternalServerError" no matter the settings - which is by the azure portal validated and ok.

I dont know if I can give more info except batch of numbers which probably wont help.

{
    "status": "Failed",
    "error": {
        "code": "InternalServerError",
        "message": "An unexpected error occured while processing the request. Tracking ID: '4ff64595-b790-49e8-a4e5-e4ce51577bdf'"
    }
}

Any idea? Should I just wait and try next day and next day ?

Thanks in advance

**Comment by yonzhan** [comment]
Seems not related to Azure CLI commands

**Comment by Wexleron** [comment]
> Seems not related to Azure CLI commands

Sorry, I am still quite new to GitHub :-) I just clicked "report problem" in official azure documentation,

**Comment by yonzhan** [comment]
Please reopen if you find the issue is related to Azure CLI commands.

**Comment by Wexleron** [comment]
After like 20 tries, trying to change every single option I finally succeed. The problem was in admin username "Dissidence" is simply not accepted. Worked two times ok with just different username.
