### ISSUE TITLE
config appservice list: value at null instead of the one that I see in portal

### ISSUE THREAD

**Issue by sycured** [Azure/azure-cli#23581]
## Describe the bug

**Command Name**
`az webapp config appsettings list`

**Errors:**
Return `"value": null` instead of the correct one for some environment variables
```json
  {
    "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
    "slotSetting": false,
    "value": null
  },
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az webapp config appsettings list --name {} --resource-group {}`

## Expected Behavior
Having the right value that I see in portal.azure.com:
```json
  {
    "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
    "slotSetting": false,
    "value": "@Microsoft.KeyVault(VaultName=xxxxxxxxxxx;SecretName=xxxxxxxx)"
  },
```
## Environment Summary
```
macOS-12.5.1-x86_64-i386-64bit, Darwin 21.6.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.39.0
```

**Comment by sycured** [comment]
I tried [the REST API](https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/list-application-settings?tryIt=true&source=docs#code-try-0) and the value is the correct one

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@sycured Thank you for reaching out, we are looking into it.

**Comment by sycured** [comment]
@RakeshMohanMSFT  Thank you but it's not as expected…
Tell me why it's not affecting all values with `"@Microsoft.KeyVault(VaultName=xxxx; SecretName=xxxxx)"` ?

Also, it's not about Azure DevOps but Azure CLI for Azure Portal (resources and in this case App Services - Web App)

I've a script dumping the config of all our web app and storing them in a versioned system and automatically triggering alerts based on specific logic.

So `az webapp config appsettings list` is never executed on Azure DevOps but exclusively on workstation/server.

**Comment by sycured** [comment]
I tried Azure SDK for Python and it's working as expected returning the value for all environment variables with KeyVault reference so having `"value": "@Microsoft.KeyVault(VaultName=xxxxxxxxxxx;SecretName=xxxxxxxx)"`

My code to test it:

```python
from azure.identity import AzureCliCredential
from azure.mgmt.web import WebSiteManagementClient

credential = AzureCliCredential()

subscription_id = 'xxx'
resource_group = 'yyy'
webapp_name = 'zzz'

web_client = WebSiteManagementClient(credential=credential, subscription_id=subscription_id)

get_web_app = web_client.web_apps.list_application_settings(resource_group_name=resource_group, name=webapp_name)

print(get_web_app)
```

**The real problem is Azure CLI replacing it with null**

**Comment by RakeshMohanMSFT** [comment]
@sycured I do see masking logic in the code, but let me discuss internally and get back to you.

**Comment by panchagnula** [comment]
@sycured the reason in CLI these settings were masked because of security issue that passwords shouldn't be displayed in plaintext. This an open issue on the platform end, that the GET API GET /subscriptions/e483435e-282d-4ac1-92b5-d6123f2aa360/resourceGroups/sisirap-rg/providers/Microsoft.Web/sites/clitestapp/config/slotConfigNames? shouldn't return passwords , hence the masking change on CLI, Unfortunately we cannot change this behavior due to security concerns on CLI. For now the workaround would be to use az rest with the API to return these values. Thanks!

**Comment by sycured** [comment]
@panchagnula Thank you so moving to the Rust SDK for the Rest API
