### ISSUE TITLE
Error while running: az appconfig show-deleted

### ISSUE THREAD

**Issue by VSE-ops** [Azure/azure-cli#23599]
Hello!
I found out that one of azure cli comand for appconfig is not working and throwing error that this key is misspelled.
az appconfig show-deleted 
https://docs.microsoft.com/en-us/cli/azure/appconfig?view=azure-cli-latest#az-appconfig-show-deleted

`az appconfig show-deleted -n <AppConfig name>`
`'show-deleted' is misspelled or not recognized by the system.`

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 141619ee-fd83-7493-88a3-afd818d6c56e
* Version Independent ID: 25e4c840-d438-02ef-2363-77b9616f006b
* Content: [az appconfig](https://docs.microsoft.com/en-us/cli/azure/appconfig?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/appconfig.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/appconfig.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@VSE-ops Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@VSE-ops We unable to reproduce the issue, can you please upgrade to the latest version of az cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
