### ISSUE TITLE
Deleting a user is not supported on Windows VM

### ISSUE THREAD

**Issue by JereO-Nc** [Azure/azure-cli#23595]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az vm user delete --ids 

**Describe the bug**
Hi, I am trying to delete a user across multiple VMs in different subscriptions, the az cli, 'az vm user delete' allows you to provide ids for all the VMs irrespective of subscription.  when i use the az vm user delete cmd, i get the error "**Deleting a user is not supported on Windows VM**".
However i noticed a workaround  on this [issue](https://github.com/Azure/azure-cli/issues/23453#issue-1330246475), which doesn't quite cover my use-case. Any ideas on how to resolve? 
Thanks

**Expected behavior**
The local account user  should be deleted from the VMs

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
Same as [#23453](https://github.com/Azure/azure-cli/issues/23453#issuecomment-1207589188)

**Comment by JereO-Nc** [comment]
@yonzhan can i ask why this was closed. I havent gotten a response on my issue.

**Comment by JereO-Nc** [comment]
@zhoxing-ms this issue isnt quite the same as https://github.com/Azure/azure-cli/issues/23453#issuecomment-1207589188 , seeing as the workaround there resolved his issue because it only addresses deleting a user on VMs in the same resourcegroup,the Pwshell cmdlet does not do the same for my usecase where i am trying to delete a user across multiple vms in multiple subscriptions.

**Comment by zhoxing-ms** [comment]
This problem was by designed on CLI side [code link](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/custom.py#L2894). We need the Compute team to confirm whether the current Windows VM supports deleting the user 

@grizzlytheodore Could you please help confirm whether the REST [virtual-machine-extensions/update](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-extensions/update?tabs=HTTP) can support deleting users for Windows VM or does the service team have relevant plan?

**Comment by JereO-Nc** [comment]
@zhoxing-ms thanks for the feedback.looking forward to the response.

**Comment by grizzlytheodore** [comment]
this is a question for CRP team specifically someone who works in extensions. I can refer manuj bhardwaj, but I cannot find his github. I will share him this thread via email

**Comment by grizzlytheodore** [comment]
turns out Manuj does not work with VM Ex. I forwarded email to correct team.

**Comment by zhoxing-ms** [comment]
@nkuchta As you mentioned in the email thread: `The Windows version of VM Access doesn't support deleting a user account`. May I ask if service team has any plans to support it in the future?

**Comment by navba-MSFT** [comment]
@JereO-Nc I hope you had a chance to look at the above comment from our Compute Service team. `The Windows version of VM Access doesn't support deleting a user account`.

I have developed a [sample PS script ](https://github.com/Azure-Samples/Azure-CXP-Developer-Support/blob/main/VirtualMachine/Powershell/PSAzVMRemoveUser.ps1) as a workaround to achieve your requirement. You can modify it to serve your requirement. Hope this helps.

**Comment by aamad777** [comment]
Not working no option to define which user u need yo delete or RG>

**Comment by aamad777** [comment]
Parameter cannot be processed because the parameter name 'subs

**Comment by aamad777** [comment]
Update the script delete local user what we request is domain user

**Comment by navba-MSFT** [comment]
@aamad777 As mentioned in the above comment, you need to tweak the PS script as per your requirement.

To answer your question related to define the username which needs to be deleted, This is mentioned under the[ Pre-requisites section in this Powershell script.](https://github.com/Azure-Samples/Azure-CXP-Developer-Support/blob/main/VirtualMachine/Powershell/PSAzVMRemoveUser.ps1)

Within the **script.ps1** file you need to add this line **Remove-ADUser -Identity GlenJohn** . This line will help you to remove the AD user.

**Comment by aamad777** [comment]
@navba-MSFT  it only work when i delete   Get-AzSubscription -SubscriptionName $sub.Name | Set-AzContext however

I need to delete Azure account not AD account i tried the script nothing has been removed

**Comment by navba-MSFT** [comment]
@JereO-Nc Could you please confirm if you have tried the above script and if it helped you ?

**Comment by aamad777** [comment]
@navba-MSFT  Tried the same nothing delete even it give succuss put when i checked using local account the  user still exists with file and folder

**Comment by navba-MSFT** [comment]
@aamad777 Thanks for getting back. May I know the feasibility of opening a support ticket ? Our support professionals can have closer look at the issue and troubleshoot this further.

**Comment by aamad777** [comment]
Not sure what you mean @navba-MSFT  ?? this is already a ticket no?

**Comment by navba-MSFT** [comment]
@aamad777 This is a GitHub issue. My suggestion is to open a support ticket. So that our Microsoft Support Professionals can contact you over email / phone and work with you over a screen sharing session and troubleshoot this issue.

The process to open a support ticket is explained **[here](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request)**.

**Comment by navba-MSFT** [comment]
@JereO-Nc As mentioned in the above comment. The Windows version of VM Access doesn't support deleting a user account. However, I have developed a [sample PS script ](https://github.com/Azure-Samples/Azure-CXP-Developer-Support/blob/main/VirtualMachine/Powershell/PSAzVMRemoveUser.ps1)as a workaround to achieve your requirement of deleting a user across multiple VMs in different subscriptions. You can modify it to serve your requirement. Please test this and get back to us with an update.

**Comment by navba-MSFT** [comment]
@JereO-Nc The action is now pending on you to test the above workaround and get back to us. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by JereO-Nc** [comment]
@navba-MSFT  pardon the late response. i didnt get notified with these updates, will test the script and get back to you.
