### ISSUE TITLE
Getting error when deploying Azure Function Code through Zip deploy on Linux Consumption Plan

### ISSUE THREAD

**Issue by alisharepoint** [Azure/azure-cli#23598]
## Getting command failed with an unexpected error

**Command Name**
`az functionapp deployment source config-zip`

**Command Example**
`az functionapp deployment source config-zip --resource-group RtoElDev --name rtoelinuxfunc --src "E:\ziptestfunc.zip"`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
dictionary update sequence element #0 has length 1; 2 is required
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 519, in enable_zip_deploy_functionapp
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 687, in upload_zip_to_storage
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storage/v2018_11_09/blob/blockblobservice.py", line 144, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py", line 197, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storage/v2018_11_09/common/_connection.py", line 110, in get_service_parameters
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/multiapi/storage/v2018_11_09/common/_connection.py", line 135, in _from_connection_string
ValueError: dictionary update sequence element #0 has length 1; 2 is required

```
## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0
```
## ZIP Folder Content Details
<b>Function1.cs file</b>
```
using System;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace ziptestfunc
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            string name = req.Query["name"];

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            string responseMessage = string.IsNullOrEmpty(name)
                ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
                : $"Hello, {name}. This HTTP triggered function executed successfully.";

            return new OkObjectResult(responseMessage);
        }
    }
}
```

<b>host.json file</b>
```
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        }
    }
}
```

<b>ziptestfunc.csproj file</b>
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by alisharepoint** [comment]
Any update on the issue?

**Comment by alisharepoint** [comment]
Any update on this issue ?

**Comment by RakeshMohanMSFT** [comment]
@alisharepoint I unable to reproduce this issue 

az functionapp deployment source config-zip -g Issue23598 -n issue23598function --src "C:\CXP\Issues\Samples\FunctionApp\githubzip\githubzip\githubzip.zip"
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
{
  "active": true,
  "author": "N/A",

Here are the list of file i have included in my zip and its a sample function app template, which i see you are using as well.

![image](https://user-images.githubusercontent.com/49954584/185929159-3ffd30da-7bae-4dbf-b908-4445f57b1e31.png)

**Comment by alisharepoint** [comment]
@RakeshMohanMSFT 

Now when I run zip deployment command I'm getting uploading 100% below is the detailed outpout:

E:\>az functionapp deployment source config-zip --resource-group RtoElDev --name rtoelinuxfunc --src "E:\ziptestfunc.zip"
←[K - Uploading ============================== 100.0% ..
E:\>

![image](https://user-images.githubusercontent.com/111578920/185957613-765830cc-13b1-46db-b46a-5c44fad25ea2.png)

**Comment by RakeshMohanMSFT** [comment]
@alisharepoint Please share the debug trace with us for further troubleshooting please

**Comment by alisharepoint** [comment]
@RakeshMohanMSFT 

Where can I find the debug trace ?

**Comment by RakeshMohanMSFT** [comment]
@alisharepoint along with your comment use --debug

**Comment by alisharepoint** [comment]
@RakeshMohanMSFT

Can you please copy the required info from the log that you needed and paste in the comment, so I will edit my comment and remove the unnecessary parts.

Thanks

**Comment by alisharepoint** [comment]
@RakeshMohanMSFT 

Are you able to trace what's the issue with the help of debug trace ?

**Comment by alisharepoint** [comment]
@RakeshMohanMSFT 

Any update on this issue?

**Comment by RakeshMohanMSFT** [comment]
@alisharepoint I see that everything is working as expected are you not seeing the functions deployed in the portal?

**Comment by alisharepoint** [comment]
@RakeshMohanMSFT 

I'm only facing this issue in Linux Consumption Plan, it's working fine on Windows plan.

**Comment by RakeshMohanMSFT** [comment]
@alisharepoint Are you following these steps to create the function?
![image](https://user-images.githubusercontent.com/49954584/186638297-c5713e54-538c-4b96-8718-2655f58904a4.png)

**Comment by alisharepoint** [comment]
@RakeshMohanMSFT 

I'm creating function using Visual Studio 2022 and deploying it through Zip deployment. Same process working fine for me in Windows Consumption plan. But unable to do in Linux Consumption. 

Can you please check the zip deployment in Linux Consumption?

**Comment by RakeshMohanMSFT** [comment]
@alisharepoint  Its working fine for me. Please try to follow previous screenshot i shared and create the function and publish the same using visual studio and see if that works for you.
![image](https://user-images.githubusercontent.com/49954584/186716502-58e4ddfb-521c-4352-a8c8-09ac67f4a9cb.png)
