### ISSUE TITLE
Deleting user from VM, unsupported

### ISSUE THREAD

**Issue by aamad777** [Azure/azure-cli#23605]
### Resource Provider

Azure

### Description of Feature or Work Requested

Deleting user from VM, unsupported in cli

### Minimum API Version Required

1

### Swagger PR link

azure

### Target Date

2022

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
Same as https://github.com/Azure/azure-cli/issues/23453#issuecomment-1207589188

**Comment by zhoxing-ms** [comment]
@grizzlytheodore Could you please help confirm whether the REST [virtual-machine-extensions/update](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-extensions/update?tabs=HTTP) can support deleting users for Windows VM or does the service team have relevant plan?

**Comment by aamad777** [comment]
why you close it?

**Comment by yonzhan** [comment]
We can track the same one https://github.com/Azure/azure-cli/issues/23453#issuecomment-1207589188

**Comment by aamad777** [comment]
@yonzhan  #23453 is closed already too

**Comment by zhoxing-ms** [comment]
I reopened a similar issue. Please see if it is the same as this issue #23595
