### ISSUE TITLE
Remove Microsft team meeting  ID  for the user

### ISSUE THREAD

**Issue by aamad777** [Azure/azure-cli#23606]
**Related command**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Please provide detailed CLI command and error log if any.

**Comment by navba-MSFT** [comment]
@aamad777 Thanks for reaching out to us. Could you please elaborate your ask ? Also wanted to confirm if your concern is anyway related to Azure CLI ?

**Comment by navba-MSFT** [comment]
@aamad777 This is a quick follow-up on this issue to gather more details about this issue.Looking at your issue description the issue doesnt seem to be related to AzCLI. Please let us know the Azure CLI command that you are running along with the --debug output. This will help us to assist you better.

**Comment by navba-MSFT** [comment]
@aamad777 Please provide us an update on this and feel free to reopen this issue. We would be happy to resume our investigation and assist you further.
