### ISSUE TITLE
Include option for PowerShell in az functionapp config set

### ISSUE THREAD

**Issue by MadhuraBharadwaj-MSFT** [Azure/azure-cli#23603]
Per the documentation, seems like it is currently not possible to set Function App **PowerShell** version using **az functionapp config set**. There are options for java, php, python, but not for  PS.

![image](https://user-images.githubusercontent.com/108835427/185716613-ac323b97-15f0-4b69-bf83-a032536ac1ab.png)

Please add a parameter for PowerShell under az functionapp config set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09a3700-4b7b-6720-bec4-2d07ff96ef23
* Version Independent ID: 7d06e377-4659-b3c5-4b7f-8448cc0c102f
* Content: [az functionapp config](https://docs.microsoft.com/en-us/cli/azure/functionapp/config?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/functionapp/config.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/functionapp/config.yml)
* Service: **azure-functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MadhuraBharadwaj-MSFT** [comment]
cc @Francisco-Gamino , @AnatoliB

**Comment by yonzhan** [comment]
route to CXP team

**Comment by MadhuraBharadwaj-MSFT** [comment]
Hello @PramodValavala-MSFT ,
Any updates on this request, please?

**Comment by PramodValavala-MSFT** [comment]
@MadhuraBharadwaj-MSFT Apologies for the delay here! We have worked up a PR to add this option.

**Comment by MadhuraBharadwaj-MSFT** [comment]
> @MadhuraBharadwaj-MSFT Apologies for the delay here! We have worked up a PR to add this option.

Great, thanks! Could you update here when this option is available? We would like to test this out.
