### ISSUE TITLE
az keyvault create command parameters aren't documented/don't work as expected

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#2361]
The following parameters suggest they are flags but they are not.  The help does not describe their meaning or intended values

`                          [--enabled-for-disk-encryption ENABLED_FOR_DISK_ENCRYPTION]
                          [--enabled-for-template-deployment ENABLED_FOR_TEMPLATE_DEPLOYMENT]
                          [--enabled-for-deployment ENABLED_FOR_DEPLOYMENT]`

`    --enabled-for-deployment         : Property to specify whether Azure Virtual Machines are
                                       permitted to retrieve certificates stored as secrets from the
                                       key vault.
    --enabled-for-disk-encryption    : Property to specify whether Azure Disk Encryption is
                                       permitted to retrieve secrets from the vault and unwrap keys.
    --enabled-for-template-deployment: Property to specify whether Azure Resource Manager is
                                       permitted to retrieve secrets from the key vault.`

**Comment by tjprescott** [comment]
These will be treated as "three state flags", meaning you can specify true or false (and nothing else) OR you can treat it like a flag (in which case it will be as if you specified true).
