### ISSUE TITLE
CLI | Trusted Launch Default - New Az VM OS Disk

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-cli#23614]
### Related command

- [az disk create --name 'diskname' -g 'diskrgname'](https://docs.microsoft.com/en-us/cli/azure/disk?view=azure-cli-latest#az-disk-create)

### Resource Provider

Microsoft.Compute/disks

### Description of Feature or Work Requested

# Trusted Launch as Default

As part of making compute layer secure for customers to deploy workloads, request is to make [Trusted Launch](https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch) (GA Date: November 2021) as default deployment option in CLI. Following changes will need to be made for same:

>**NOTE**: Below scenarios are applicable only for **OS Disks** created **FromImage** and **LUN** is not set by end user, i.e., if command is used to create *Data Disk*, below scenarios and change requests do not apply.

## Scenario 1 - User creates OS disk from PIR image using `az disk create --image-reference`

Present Behavior | Updated Behavior post change
-|-
New disk with create option FromImage:<ol><li>User runs command `az disk create -n diskname -g diskrgname --image-reference 'urnofPIRimage'`<li>OS Disk with image reference and Premium_LRS SKU is created.</li></ol> | Updated default parameters and sequence:<ol><li>User runs command `az disk create -n diskname -g diskrgname --image-reference 'urnofPIRimage'`<li>CLI queries image capabilities using API [Virtual Machines Images GET API](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-images/get?tabs=HTTP)<ul><li>For Gen2, use property **hyperVGeneration** with value of **V2**</li></ul><li>Conditions:<ul><li>If PIR image supports **hyperVGeneration = v2**, enable following parameters by default:<ul><li>--hyper-v-generation with value **V2**<li>--security-type with value **TrustedLaunch**</li></ul><li>Else, Disk will get deployed per user inputs. If securityType is not set to _TrustedLaunch_, Notification message should be printed for user. **Notification Message**:  `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`</li></ul></ol>

## Scenario 2 - User creates OS disk from ACG image using `az disk create --gallery-image-reference`

**No change** due to potential impact surface due to ACG not being TrustedLaunchSupported and Managed Image does not support Trusted Launch.
- Set securityType to Standard by default if no inputs by end user
- If securityType is not set to _TrustedLaunch_ then Deploy VM with user passed configuration along with Notification message should be printed for user. **Notification Message** `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`

>**NOTE**: Please review limitations [Trusted Launch VM Limitations](https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch#limitations) to assess any impact for CLI users.

### Minimum API Version Required

2021-12-01

### Swagger PR link

[Disk RP Swagger 2021-12-01](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/DiskRP/stable/2021-12-01/disk.json)

### Request Example

[Create disk with Trusted Launch Security Type](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/DiskRP/stable/2021-12-01/examples/CreateAManagedDiskWithSecurityProfile.json)

### Target Date

2023-11-15

### Additional context

- Change in request since October 2022 (Warning message implementation):
   - Trusted Launch as default bypassed for Azure Compute gallery
   - Platform/Marketplace OS image check scoped to hyperVGeneration = v2
Server / API side error message added.
- Image capability to support Gen2 or Trusted Launch VM can be queried using API [Virtual Machines Images GET API](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-images/get?tabs=HTTP)
   - For Gen2, use property hyperVGeneration with value of V2
- Trusted Launch as default implemented for Azure Portal in April 2023.
- Image Providers:
   - Azure Compute Gallery: [https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/**providers/Microsoft.Compute/galleries/**myGalleryName/images/myGalleryImageName?api-version=2022-03-03](https://management.azure.com/subscriptions/%7Bsubscription-id%7D/resourceGroups/myResourceGroup/**providers/Microsoft.Compute/galleries/**myGalleryName/images/myGalleryImageName?api-version=2022-03-03)
   - Marketplace: [https://management.azure.com/subscriptions/{subscription-id}/providers/Microsoft.Compute/locations/aaaaaa/**publishers/aaa/artifacttypes/vmimage/offers/**aaaaaaaaaaaaaaaaaaaaaaaaaaaaa/skus/aaaaaaaaaaaaaaaaaaaaaaaaaaa/versions/aaaaaaaaaaaaaaaaaaa?api-version=2023-07-01](https://management.azure.com/subscriptions/%7Bsubscription-id%7D/providers/Microsoft.Compute/locations/aaaaaa/**publishers/aaa/artifacttypes/vmimage/offers/**aaaaaaaaaaaaaaaaaaaaaaaaaaaaa/skus/aaaaaaaaaaaaaaaaaaaaaaaaaaa/versions/aaaaaaaaaaaaaaaaaaa?api-version=2023-07-01)
   - Managed Image: [https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/**providers/Microsoft.Compute/images/**myImage?api-version=2023-07-01](https://management.azure.com/subscriptions/%7Bsubscription-id%7D/resourceGroups/myResourceGroup/**providers/Microsoft.Compute/images/**myImage?api-version=2023-07-01)
   - Shared Image: **/sharedGalleries/**
   - Community Image: **/communityGalleries/**

**Comment by yonzhan** [comment]
Compute

**Comment by yanzhudd** [comment]
Hello @AjKundnani, could you please help to confirm below two details in this issue?
- what is the difference between creating OS disk and data disk in terms of user passing parameters?
- in the scenario 1, is the condition of setting the default value met when the value of `DiskCreateOption` is passed as empty?

**Comment by AjKundnani** [comment]
> Hello @AjKundnani, could you please help to confirm below details in this issue?
> 
> * what is the difference between creating OS disk and data disk in terms of user passing parameters?
> * in the scenario 1, is the condition of setting the default value met when the value of `DiskCreateOption` is passed as empty?
> * in the scenario 3, it seems that [az sig image-version show](https://docs.microsoft.com/en-us/cli/azure/sig/image-version?view=azure-cli-latest#az-sig-image-version-show) does not contain the information of hyperVGeneration and Trusted Launch, since the command `az sig image-version show` use the api of [Gallery Image Versions GET](https://docs.microsoft.com/en-us/rest/api/compute/gallery-image-versions/get?tabs=HTTP).
> 
> Thanks
@yanzhudd 
1. Disk will be OS disk if:
    - If the `CreateOption` is set to **FromImage**
    - If the `CreateOption` is Import, Upload or Empty and `--os-type` parameter is provided.
2. Correct, when `CreateOption` is set to **Empty**
3. It should be [az sig image-definition show](https://docs.microsoft.com/en-us/cli/azure/sig/image-definition?view=azure-cli-latest#az-sig-image-definition-show)

**Comment by yanzhudd** [comment]
> Notification Message if needed to be provided to end users prior to making changes - Starting xx/xx/xxxx az disk create command will deploy Trusted Launch VM by default. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch

Hello @AjKundnani, since the time of next build conference has not been determined, can the notification be modified to look like this?
**Starting next breaking window (sprint for 2023 Build Event) az disk create command will deploy Trusted Launch VM by default. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch**

**Comment by AjKundnani** [comment]
> > Notification Message if needed to be provided to end users prior to making changes - Starting xx/xx/xxxx az disk create command will deploy Trusted Launch VM by default. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch
> 
> Hello @AjKundnani, since the time of next build conference has not been determined, can the notification be modified to look like this? Starting **next breaking window (sprint for 2023 Build Event)** az disk create command will deploy Trusted Launch VM by default. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch

@yanzhudd - Is it ok from CLI perspective to call-out `breaking change window` for end users? Or if we can simplify perhaps, like `Starting Build 2023, az disk create command will deploy Trusted Launch VM by default. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch`, thoughts?

**Comment by yanzhudd** [comment]
> > > Notification Message if needed to be provided to end users prior to making changes - Starting xx/xx/xxxx az disk create command will deploy Trusted Launch VM by default. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch
> > 
> > 
> > Hello @AjKundnani, since the time of next build conference has not been determined, can the notification be modified to look like this? Starting **next breaking window (sprint for 2023 Build Event)** az disk create command will deploy Trusted Launch VM by default. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch
> 
> @yanzhudd - Is it ok from CLI perspective to call-out `breaking change window` for end users? Or if we can simplify perhaps, like `Starting Build 2023 event, az disk create command will deploy Trusted Launch VM by default. To know more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch`, thoughts?

It looks great. We will show this notification message to end users.

**Comment by AjKundnani** [comment]
@yanzhudd @zhoxing-ms - If we can remove the below block of message please, goal is to keep message consistent and avoid confusion for end user (this request is based on one of the team member)

![image](https://user-images.githubusercontent.com/18166395/204501059-dfa099b9-8d49-4338-9abf-4855eb69ce8a.png)

**Comment by AjKundnani** [comment]
@yanzhudd - Per discussion with Disk resource provider team, removed the scenario for **CreateOption = Empty**.
Scope if for OS disks created from image i.e., **CreateOption = FromImage**

**Comment by yanzhudd** [comment]
Hi @AjKundnani, let me check with you some details:
- Is the following filter still needed before setting `--security-type` default value with TrustedLaunch in Scenario 1?
https://github.com/Azure/azure-cli/blob/bbdf30570f44fa5f1ea41ef072a78cfaeb633198/src/azure-cli/azure/cli/command_modules/vm/custom.py#L428-L431 

- In the present version, creating OS disk using `--gallery-image-reference` param has a similar logic with using `--image-reference`
https://github.com/Azure/azure-cli/blob/bbdf30570f44fa5f1ea41ef072a78cfaeb633198/src/azure-cli/azure/cli/command_modules/vm/custom.py#L467-L480
Will the logic of Scenario 2 be similar with Scenario 1, i.e., setting default values `--hyper-v-generation` with V2 and `--security-type` with TrustedLaunch?

**Comment by AjKundnani** [comment]
@yanzhudd 
> * Is the following filter still needed before setting `--security-type` default value with TrustedLaunch in Scenario 1?
>   https://github.com/Azure/azure-cli/blob/bbdf30570f44fa5f1ea41ef072a78cfaeb633198/src/azure-cli/azure/cli/command_modules/vm/custom.py#L428-L431

Checking **features** and `securityType` of platform image is not required. Only the `hyperVGeneration` of image should be `v2`.

> * In the present version, creating OS disk using `--gallery-image-reference` param has a similar logic with using `--image-reference`
>   https://github.com/Azure/azure-cli/blob/bbdf30570f44fa5f1ea41ef072a78cfaeb633198/src/azure-cli/azure/cli/command_modules/vm/custom.py#L467-L480
>   Will the logic of Scenario 2 be similar with Scenario 1, i.e., setting default values `--hyper-v-generation` with V2 and `--security-type` with TrustedLaunch?

No, for Scenario 2 where OS disk is created from Azure Compute Gallery image, defaults do not apply.
Only change is if `--security-type` is not `TrustedLaunch` then print notification message to end user `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`

**Comment by yanzhudd** [comment]
> @yanzhudd
> 
> > * Is the following filter still needed before setting `--security-type` default value with TrustedLaunch in Scenario 1?
> >   https://github.com/Azure/azure-cli/blob/bbdf30570f44fa5f1ea41ef072a78cfaeb633198/src/azure-cli/azure/cli/command_modules/vm/custom.py#L428-L431
> 
> No, checking **features** and `securityType` of platform image is not required. Only the `hyperVGeneration` of image should be `v2`.
> 
> > * In the present version, creating OS disk using `--gallery-image-reference` param has a similar logic with using `--image-reference`
> >   https://github.com/Azure/azure-cli/blob/bbdf30570f44fa5f1ea41ef072a78cfaeb633198/src/azure-cli/azure/cli/command_modules/vm/custom.py#L467-L480
> >   Will the logic of Scenario 2 be similar with Scenario 1, i.e., setting default values `--hyper-v-generation` with V2 and `--security-type` with TrustedLaunch?
> 
> No, for Scenario 2 where OS disk is created from Azure Compute Gallery image, defaults do not apply. Only change is if `--security-type` is not `TrustedLaunch` then print notification message to end user `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`

@AjKundnani 
- For Scenario 1, should the warning messages other than mentioned above be removed?
https://github.com/Azure/azure-cli/blob/bbdf30570f44fa5f1ea41ef072a78cfaeb633198/src/azure-cli/azure/cli/command_modules/vm/custom.py#L421-L434
- For Scenario 2, should the warning messages other than mentioned above be removed? If so, since the Get API once added was to check whether the gallery images support hyperVGeneration V2 and then print warning logs, should the the Get logic be removed as well?
https://github.com/Azure/azure-cli/blob/bbdf30570f44fa5f1ea41ef072a78cfaeb633198/src/azure-cli/azure/cli/command_modules/vm/custom.py#L467-L480
- In Scenario 2, do setting securityType to Standard by default and print warning log apply for all gallery images? i.e., ignore the type of gallery image like community or shared or something and all filters mentioned above?

**Comment by AjKundnani** [comment]
@yanzhudd, **For Scenario 1**, based on current code:
1. If source OS image is Gen1 - Then print notification to consider upgrading security of deployment. (Correct).
2. If source OS image is Gen2 AND input `--hyper-v-generation` is **V1** then instead of printing notification message, apply `Trusted Launch defaults` - `--hyper-v-generation` = **V2**, `--security-type` = **TrustedLaunch** OR print error message because Gen1 OS disk cannot be created using Gen2 OS image.
3. L428 to 432 not required, if OS image is Gen2, then deployment should default to Trusted Launch.

**For Scenario 2**
1. Yes, the logic can be simplified if `--security-type` is not set to `TrustedLaunch` then print warning message for end user.
2. Yes, printing warning log applies to all Azure Compute gallery images - Shared, Community.

**Comment by yanzhudd** [comment]
> 2. If source OS image is Gen2 AND input `--hyper-v-generation` is **V1** then instead of printing notification message, apply `Trusted Launch defaults` - `--hyper-v-generation` = **V2**, `--security-type` = **TrustedLaunch** OR print error message because Gen1 OS disk cannot be created using Gen2 OS image.
> 3. L428 to 432 not required, if OS image is Gen2, then deployment should default to Trusted Launch.

If source OS image is Gen2 AND input `--hyper-v-generation` is **V1**, would `--security-type` = **TrustedLaunch** be set directly or when `--security-type` is not input by end users?

**Comment by AjKundnani** [comment]
> If source OS image is Gen2 AND input `--hyper-v-generation` is **V1**, would `--security-type` = **TrustedLaunch** be set directly or when `--security-type` is not input by end users?

In this scenario `--hyper-v-generation` should be **V2**. `--security-type` should be set to **TrustedLaunch** if no input by end user.
If value for `--security-type` provided by end user then no change or defaults do not apply.

**Comment by yanzhudd** [comment]
Got it! Thanks @AjKundnani :)
BTW, the PR has been opened, could you please help review this PR?

**Comment by AjKundnani** [comment]
> Got it! Thanks @AjKundnani :) BTW, the PR has been opened, could you please help review this [PR](https://github.com/Azure/azure-cli/pull/27620/files)?

@yanzhudd - Reviewed PR, looks good to me, will validate further during bug bash, thanks.
