### ISSUE TITLE
Azure Virtual Network Manager CLI extension.

### ISSUE THREAD

**Issue by jago2136** [Azure/azure-cli#23613]
**Related command**

az network manager group create
az network manager post-commit
az network manager connection management-group {all actions}

**Is your feature request related to a problem? Please describe.**

I've discussed with Taoxu Zeng the commands that were missed/critical bugs that slipped through in the last release for network-manager azure CLI extension. A brief summary is described below
- 'az network manager group create' does not work if no description field is provided.
- 'az network manager post-commit' does not work at all and throws an error internal to the extension.
- 'az network manager connection management-group {all actions}' was not exposed, as requested in the latest feature request from our team. The commands are to be uncommented and tests run.

**Describe the solution you'd like**

The above bugs to be fixed and commands to be released.

**Describe alternatives you've considered**

N/A

**Additional context**

I've been in touch with Taoxu Zeng and collaborating with them on the fixes.

**Comment by yonzhan** [comment]
network
