### ISSUE TITLE
cant create resources with terraform

### ISSUE THREAD

**Issue by armenmelkonyan90** [Azure/azure-cli#23628]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'https://batch.core.windows.net'.\r\nTrace ID: 00f2482c-3711-4889-8fdf-3e8642634b00\r\nCorrelation ID: 1f30ba37-c071-4dab-a4bd-79d3201baf84\r\nTimestamp: 2022-08-22 19:58:09Z","error_codes":[50076],"timestamp":"2022-08-22 19:58:09Z","trace_id":"00f2482c-3711-4889-8fdf-3e8642634b00","correlation_id":"1f30ba37-c071-4dab-a4bd-79d3201baf84","error_uri":"https://login.microsoftonline.com/error?code=50076","suberror":"basic_action"}
Traceback (most recent call last):
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --resource {} --subscription {} -o={}`

## Environment Summary
```
Linux-5.15.0-46-generic-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by jiasli** [comment]
`2.0.81` is not the official Azure CLI. See https://github.com/Azure/azure-cli/issues/19640

Please install the official one and try again. It will prompt you how to do interactive re-auth with `--scope`.

**Comment by wangzelin007** [comment]
@jiasli,
May I ask is there a command to tell if the installed Azure CLI is official?

**Comment by jiasli** [comment]
According to https://github.com/Azure/azure-cli/issues/19640, if Azure CLI version is 2.0.81 or 2.18.0, most likely it is unofficial Azure CLI.

**Comment by navba-MSFT** [comment]
@armenmelkonyan90 Thanks for reaching out to us and reporting this issue. As mentioned in the above comment, please install the _[most recent version of official Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)_ and check if you are still facing this issue. Awaiting your reply.
