### ISSUE TITLE
Command `az aks enabled-addons` failed

### ISSUE THREAD

**Issue by lam-man** [Azure/azure-cli#23629]
## Describe the bug

**Command Name**
`az aks enable-addons`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'case_insensitive_dict' from 'azure.core.utils' (/opt/az/lib/python3.10/site-packages/azure/core/utils/__init__.py)
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/home/liwen/.azure/cliextensions/aks-preview/azext_aks_preview/_client_factory.py", line 31, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- Please follow the steps in this doc: https://docs.microsoft.com/en-us/azure/aks/web-app-routing#import-certificate-to-azure-keyvault
- `az aks enable-addons --resource-group <myResourceGroup> --name <myAKSCluster> --addons azure-keyvault-secrets-provider,open-service-mesh,web_application_routing`

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0 *

Extensions:
account 0.2.2
aks-preview 0.5.94

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@lam-man Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@lam-man I am unable to replicate this issue using the same version of aks-preview extension. The only difference was that I am using most recent version of Azure CLI.

I could see that you are using an older version of azure-cli 2.37.0 * . To isolate this issue, Could you please use the[ most recent version of AzCLI ](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli)and test again ?

Tagging another similar issue here https://github.com/Azure/azure-cli-extensions/issues/5215

**Comment by lam-man** [comment]
Hi @navba-MSFT 

Thank you very much. You are correct. After upgrading the `az` module, the problem got resolved. I think a reminder might be able to help others in the document here:  https://docs.microsoft.com/en-us/azure/aks/web-app-routing#import-certificate-to-azure-keyvault . 

Thanks again for help.

**Comment by navba-MSFT** [comment]
@lam-man Thanks for getting back. I am glad that the issue is resolved. More details about the fix is explained [here](https://docs.microsoft.com/en-us/cli/azure/aks/addon?view=azure-cli-latest#az-aks-addon-enable). We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
