### ISSUE TITLE
vnet peering create --allow-vnet-access help text wrong

### ISSUE THREAD

**Issue by yrro** [Azure/azure-cli#23639]
**Related command**
`az network vnet peering create`

**Describe the bug**
The description for `allow-forwarded-traffic` reads:

> Allows forwarded traffic from the local VNet to the remote VNet

It seems that local and remote are the wrong way around in this text.

In the portal, the option text is "Traffic forwarded from remote virtual network" which can be set to allow/block. The help popup reads

> This setting allows forwarded traffic from VNET-REMOTE (traffic not originating from inside VNET-REMOTE) into VNET-LOCAL.

Where VNET-LOCAL is the vnet whose peering I am editing, and VNET-REMOTE is the vnet that the peering is with.

**To Reproduce**
`$ az network vnet peering create --help`

**Expected behavior**

**Environment summary**
```
Linux-5.18.0-3-amd64-x86_64-with-glibc2.34, Debian GNU/Linux 11 (bullseye)
Python 3.10.5
Installer: DEB

azure-cli 2.39.0

Extensions:
azure-firewall 0.13.0
ip-group 0.1.2
support 1.0.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Additional context**
Incorrect help text was introduced in #9051

**Comment by yonzhan** [comment]
@necusjz for awareness
