### ISSUE TITLE
--main-class-name seems a mandatory parameter when submitting the spark job. However, it is mentioned in Optional Parameters

### ISSUE THREAD

**Issue by HarryUlysses** [Azure/azure-cli#23631]
[Enter feedback here]
For submitting spark job, --main-class-name seems a mandatory parameter. Otherwise, it will return the error. 

However, it is in the Optional Parameters as below. I thinks it is incorrect and misunderstanding. Please verify it.
https://docs.microsoft.com/en-us/cli/azure/synapse/spark/job?view=azure-cli-latest#az-synapse-spark-job-submit
![image](https://user-images.githubusercontent.com/24678016/186056231-16d4e470-246d-4f43-b396-c779a671bb4c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f015a773-72ac-d61b-1778-190d6c051d13
* Version Independent ID: 8ca2a37f-b4c1-9413-fd30-3d5ad1fe5dba
* Content: [az synapse spark job](https://docs.microsoft.com/en-us/cli/azure/synapse/spark/job?view=azure-cli-latest#az-synapse-spark-job-submit)
* Content Source: [latest/docs-ref-autogen/synapse/spark/job.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/synapse/spark/job.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@HarryUlysses You are correct, and I have created a PR to address it and it will be merged once approved. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.

Thanks
Saurabh
