### ISSUE TITLE
--query outputs to null

### ISSUE THREAD

**Issue by joben** [Azure/azure-cli#2363]
When I issue the command
az vm list-sizes -l southeastasia --query "[*].{name:name, maxDataDiskCount:maxdisk}"

the maxDataDiskCount column is null. 

Same behavior for other fields with numeric value (numberOfCores, etc)

Without --query, az vm list-sizes -l southeastasia is able to display all fields. 

I should be able to use --query to filter or select specific rows/records that match my query

**Comment by derekbekoe** [comment]
It should be:
```
$ az vm list-sizes -l southeastasia --query "[*].{name:name, maxDataDiskCount:maxDataDiskCount}"
```

**Comment by derekbekoe** [comment]
`maxdisk` did not exist on the original object
