### ISSUE TITLE
doc:  duplicate blocks

### ISSUE THREAD

**Issue by ziyeqf** [Azure/azure-cli#23636]
There are two same blocks in the doc.
https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sig/image-definition.yml#L152
and
https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sig/image-definition.yml#L163

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ea8a20-1ce0-a34c-872e-8101f1494479
* Version Independent ID: ed92d5cf-a13b-de7c-9693-337e7c20f3ae
* Content: [az sig image-definition](https://docs.microsoft.com/en-us/cli/azure/sig/image-definition?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/sig/image-definition.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sig/image-definition.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness
