### ISSUE TITLE
az webapp download fail

### ISSUE THREAD

**Issue by mckenzm** [Azure/azure-cli#23634]
## Describe the bug

az login -tenant xxxxxxxxxxxxxxxxx  OK

**Download zip from streaming (preview) under App Service on Portal was OK after allowing IP  as a workaround.** 

**Command Name**
`az webapp log download`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
('Connection broken: IncompleteRead(990 bytes read)', IncompleteRead(990 bytes read))
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/http/client.py", line 565, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/opt/az/lib/python3.10/http/client.py", line 532, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/http/client.py", line 582, in _read_chunked
    chunk_left = self._get_chunk_left()
  File "/opt/az/lib/python3.10/http/client.py", line 567, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/opt/az/lib/python3.10/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/opt/az/lib/python3.10/http/client.py", line 459, in read
    return self._read_chunked(amt)
  File "/opt/az/lib/python3.10/http/client.py", line 597, in _read_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(990 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2575, in download_historical_logs
    _get_log(url, user_name, password, log_file)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 2607, in _get_log
    data = r.read(1024)
  File "/opt/az/lib/python3.10/site-packages/urllib3/response.py", line 512, in read
    with self._error_catcher():
  File "/opt/az/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/az/lib/python3.10/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(990 bytes read)', IncompleteRead(990 bytes read))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp log download --name {} --resource-group {}`

## Environment Summary
```
Linux-5.15.0-46-generic-x86_64-with-glibc2.31, Zorin OS 16.1
Python 3.10.5
Installer: DEB

azure-cli 2.39.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@mckenzm Thanks for reaching out to us and reporting this issue. I am sharing a few action plans here to isolate this issue:

- Do you have a proxy / firewall within your network ? If yes, could you bypass it and check if you see the same issue ?

- Could you please try running the same command from another network which is faster and more reliable ?

- Did you try to run the same command from the [Azure Cloud Shell ](https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#code-try-4)and check if you encounter the same issue ?

If the above action plans doesn't help, Could you please run the same command with `--debug` output and share it here ?

Awaiting your reply.

**Comment by mckenzm** [comment]
Run in cloud shell for same (or very similar result Python 3.9).

**Comment by navba-MSFT** [comment]
@mckenzm Thanks for getting back. May I know if you had any update on the below plans ?

>Do you have a proxy / firewall within your network ? If yes, could you bypass it and check if you see the same issue ?

>Could you please try running the same command from another network which is faster and more reliable ?

**Comment by navba-MSFT** [comment]
@mckenzm I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you  had any update on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mckenzm Please provide an update on the below and reopen this issue. We would be happy to help.

>Do you have a proxy / firewall within your network ? If yes, could you bypass it and check if you see the same issue ?

>Could you please try running the same command from another network which is faster and more reliable ?

If the above action plans doesn't help, Could you please run the same command with --debug output and share it here ?

**Comment by mckenzm** [comment]
[debug.txt](https://github.com/Azure/azure-cli/files/9485588/debug.txt)
This file has not been privatised.
Run from cloudshell, which should presumably provide best network performance.

**Comment by navba-MSFT** [comment]
@mckenzm Thanks for providing the debug file.  Could you please confirm if the [log show](https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#az-webapp-log-show) & [log tail](https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#az-webapp-log-tail) commands work as expected & download is the only one having problem ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mckenzm  Yes it seems to be a bug on the kudu site. Our docs explains this saying download might fail on Linux: [az webapp log | Microsoft Docs](https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#az-webapp-log-download)

![image](https://user-images.githubusercontent.com/57353862/189274888-bb40db37-416a-4b7c-ab16-fad7795c563a.png)

**Comment by navba-MSFT** [comment]
@mckenzm Our Product Group team has identified the cause and shared the below RCA:

The Microsoft Azure Team has investigated the issue you reported regarding log download not working for your app.

Upon investigation, engineers determined that this was due to a code bug in the Kudu site, which creates the zip archive containing all logs. We identified a race condition which could cause the zip archive to be malformed. The CLI could not parse the malformed zip and threw the error you were seeing.

We have identified the fix for the issue and will be releasing it as part of our next platform upgrade.

As workaround, you may download logs directly using [Kudu REST API](https://github.com/projectkudu/kudu/wiki/REST-API#zip) /api/zip or using the File Manager on [Kudu NewUI](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/new-kudu-ui-for-app-service-on-linux-preview/ba-p/3212270) /newui.

We are continuously taking steps to improve the Azure Web App service and our processes to ensure such incidents do not occur in the future, and in this case it includes (but is not limited to):

- Bug fix for Kudu
- CLI changes to handle such errors more gracefully

We apologize for any inconvenience.
