### ISSUE TITLE
Cannot restore if storage account in different resource group

### ISSUE THREAD

**Issue by ynden** [Azure/azure-cli#23655]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
```pwsh
az backup restore restore-disks \
    --resource-group myResourceGroup \
    --vault-name myRecoveryServicesVault \
    --container-name myVM \
    --item-name myVM \
    --restore-mode OriginalLocation 
    --storage-account mystorageaccount \ 
    --rp-name myRecoveryPointName 
```

**Describe the bug**
Command succeeds when the storage account is in the same resource group as the recovery service vault.
However, the command fails when the storage account is in a different resource group.

**To Reproduce**
1. Have a recovery service vault in a resource group **A** 
2. Create a storage account in a resource group **B** (different than the one for the recovery service vault)
3. Execute the command above (by replacing with the correct values)

**Expected behavior**
Command should restores disks even when storage account is in a different resource group.

**Environment summary**

```
azure-cli                         2.39.0

core                              2.39.0
telemetry                          1.0.8

Extensions:
account                            0.2.1

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python (Darwin) 3.9.13
[Clang 13.1.6 (clang-1316.0.21.2)]
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@ynden Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@ynden I see that you have created the above PR to address this and it is currently under review.
