### ISSUE TITLE
AuthenticationException while running `az acs dcos browse`

### ISSUE THREAD

**Issue by yoanisgil** [Azure/azure-cli#2365]
I'm running this command:
    
     az acs dcos browse --name containerservice-name --resource-group resource-group-name

which yields the following exception:

```python
Authentication failed.
Traceback (most recent call last):
  File "/Users/ygil/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/ygil/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/Users/ygil/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in _execute_command
    raise ex
AuthenticationException: Authentication failed.
```

Here is the output from `az --version`:

> azure-cli (2.0.0)
> 
> acs (2.0.0)
> appservice (0.1.1b5)
> batch (0.1.1b4)
> cloud (2.0.0)
> component (2.0.0)
> configure (2.0.0)
> container (0.1.1b4)
> core (2.0.0)
> documentdb (0.1.1b2)
> feedback (2.0.0)
> iot (0.1.1b3)
> keyvault (0.1.1b5)
> network (2.0.0)
> nspkg (2.0.0)
> profile (2.0.0)
> redis (0.1.1b3)
> resource (2.0.0)
> role (2.0.0)
> sql (0.1.1b5)
> storage (2.0.0)
> vm (2.0.0)
> 
> Python (Darwin) 2.7.13 (default, Dec 18 2016, 07:03:39)
> [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

**Comment by brendandburns** [comment]
I believe that your ssh key is wrong here. Where did you create this cluster? Is there an ssh key present on this machine?

**Comment by christianhxc** [comment]
@yoanisgil try specifying the --ssh-key-file parameter and put the full path of the RSA private key. If it doesn't work, try adding the key with Pageant and run the same command again. I reported the same problem here #3232

**Comment by yoanisgil** [comment]
I'll keep that in mind for the next time, since  we finally decided to move on and use Kubernetes.

**Comment by mboersma** [comment]
This does look like a local SSH key problem as in #3232 that could be fixed with `--ssh-key-file`.

@tjprescott let's close this old issue.
