### ISSUE TITLE
Optional parameters instead of Required

### ISSUE THREAD

**Issue by valsar6** [Azure/azure-cli#23668]
[Enter feedback here]
Just as the title says:
while trying the command **az webapp config hostname add** without any param I get the following error:

_(--resource-group --webapp-name --hostname | --ids) are required_

Now, the ids or the other 3 params should be considered as required parameters. Leaving the title as optional might cause confusion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e390289-90cc-30e2-de78-33b080f9c27d
* Version Independent ID: df152c25-2434-0831-46b7-e9d0e3015f06
* Content: [az webapp config hostname](https://docs.microsoft.com/en-us/cli/azure/webapp/config/hostname?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/hostname.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/config/hostname.yml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by seligj95** [comment]
Closing, thanks for the feedback. Will take this back to the team for review.
