### ISSUE TITLE
az batch application package create errors on upload

### ISSUE THREAD

**Issue by rafaldev** [Azure/azure-cli#23669]
azure-cli                         2.39.0
core                              2.39.0
telemetry                          1.0.6 *
Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

az batch application package create --application-name cdsrunner --name testaccount --package-file "C:\azagent\A6\_work\r1\a\proj\bin\release\net6.0\test.zip" --resource-group RESOURCE-GROUP --version-name 2.0
Client-Request-ID=xxx Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=('Connection aborted.', TimeoutError('The write operation timed out')).
('Connection aborted.', TimeoutError('The write operation timed out'))

file size 43 MB - smaller file I don`t get error 

I have no problem with uploading files to 41MB blob storage, that's not a problem, but this command doesn't work well with large files. The timeout increase parameter is missing. Is there any workaround, e.g. I put the file on blob storage and add the connection to the Azure Application?

urllib3.connectionpool: Starting new HTTPS connection (1): xxx.blob.core.windows.net:443
azure.multiapi.storage.v2018_11_09.common.storageclient: Client-Request-ID=xxx Operation failed: checking if the operation should be retried. Current retry count=0, , HTTP status code=Unknown, Exception=('Connection aborted.', TimeoutError('The write operation timed out')).
azure.multiapi.storage.v2018_11_09.common.storageclient: Client-Request-ID=xxx Retry policy is allowing a retry: Retry count=1, Interval=16.033451511906392.
azure.multiapi.storage.v2018_11_09.common.storageclient: Client-Request-ID=xxx Outgoing request: Method=PUT, Path=/xxx/2.0, Query={'timeout': None, 'sv': '2018-03-28', 'sr': 'b', 'sig': 'REDACTED', 'st': '2022-08-25T13:02:48Z', 'se': '2022-08-25T17:07:48Z', 'sp': 'rw'}, Headers={'x-ms-blob-type': 'BlockBlob', 'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'Content-Length': '44958475', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.10.5; Windows 10)', 'x-ms-client-request-id': 'xxx', 'x-ms-date': 'Thu, 25 Aug 2022 13:08:25 GMT'}.
urllib3.connectionpool: Starting new HTTPS connection (2): xxx.blob.core.windows.net:443
azure.multiapi.storage.v2018_11_09.common.storageclient: Client-Request-ID=xxx Operation failed: checking if the operation should be retried. Current retry count=1, , HTTP status code=Unknown, Exception=('Connection aborted.', TimeoutError('The write operation timed out')).
azure.multiapi.storage.v2018_11_09.common.storageclient: Client-Request-ID=xxx Retry policy is allowing a retry: Retry count=2, Interval=15.17169554117862.
azure.multiapi.storage.v2018_11_09.common.storageclient: Client-Request-ID=xxx Outgoing request: Method=PUT, Path=/xxx/2.0, Query={'timeout': None, 'sv': '2018-03-28', 'sr': 'b', 'sig': 'REDACTED', 'st': '2022-08-25T13:02:48Z', 'se': '2022-08-25T17:07:48Z', 'sp': 'rw'}, Headers={'x-ms-blob-type': 'BlockBlob', 'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'Content-Length': '44958475', 'x-ms-version': '2018-11-09', 'User-Agent': 'Azure-Storage/2.0.0-2.0.1 (Python CPython 3.10.5; Windows 10)', 'x-ms-client-request-id': 'xxx', 'x-ms-date': 'Thu, 25 Aug 2022 13:09:01 GMT'}.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@rafaldev Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Looking at the error message seems like the request didn't make it to the storage account due to the connectivity issue. Do you happen to have a proxy or firewall in place? Can you try this is operation from a different network? ? Could you please let us know if the issue still persists ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@rafaldev I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@rafaldev The action is currently pending on you to get back to us on the above questions. Please feel free to reopen this thread, once you are ready to resume troubleshooting. We would be happy to help.
