### ISSUE TITLE
pip install --user azure-cli fails

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#2366]
### Create a new VM
```
az vm create -g ${project_id} -n ${vm_name} --admin-username deploy --image UbuntuLTS
```
### SSH into the VM and run
```
deploy@habitat-dev:~$sudo apt-get install python-pip
deploy@habitat-dev:~$pip install --user azure-cli
deploy@habitat-dev:~$ pip install --user azure-cli
Downloading/unpacking azure-cli
  Downloading azure_cli-2.0.0-py2.py3-none-any.whl
Downloading/unpacking azure-cli-network (from azure-cli)
  Downloading azure_cli_network-2.0.0-py2.py3-none-any.whl (243kB): 243kB downloaded
Downloading/unpacking azure-cli-appservice (from azure-cli)
  Could not find a version that satisfies the requirement azure-cli-appservice (from azure-cli) (from versions: 0.1.1b1, 0.1.1b5, 0.1.1b2, 0.1.0b11, 0.1.1b4, 0.1.0b9, 0.1.1b5, 0.1.1b2, 0.1.0b10, 0.1.1b3, 0.1.0b9, 0.1.0b11, 0.1.1b1, 0.1.0b10, 0.1.1b3, 0.1.1b4)
Cleaning up...
No distributions matching the version for azure-cli-appservice (from azure-cli)
Storing debug log for failure in /home/deploy/.pip/pip.log

deploy@habitat-dev:~$ python --version
Python 2.7.6
```

**Comment by devigned** [comment]
16.04 seemed to work just fine

**Comment by tjprescott** [comment]
I experienced the same issue, even after installing the prerequisites.  The curl script was successful. @derekbekoe is there a way to run the curl script with prompts?

**Comment by derekbekoe** [comment]
This looks the same as https://github.com/Azure/azure-cli/issues/1308.
Old versions of pip require the `--pre` flag to get prerelease packages.

**Comment by tjprescott** [comment]
This failed for a different reason, but for @devigned here's what did work (thanks to @derekbekoe):

After you install the pre-reqs, run:
`wget https://bootstrap.pypa.io/get-pip.py`
`sudo python get-pip.py`

This will install the latest version of PIP, and then your pip install should succeed. If you do what Ubuntu suggest and do `sudo apt-get install python-pip` you will get an ancient version of pip that will not work.

**Comment by devigned** [comment]
@derekbekoe `pip install --user azure-cli --pre` also failed

**Comment by tjprescott** [comment]
Ultimately the reason this failed was the ancient version of Pip that Ubuntu 14 fetches with apt-get. @devigned are there any remaining action items for this issue or can it be closed?

**Comment by devigned** [comment]
Nah, we can close this. I mostly wanted to make sure there was an issue out here for this as it's likely someone will come across this.
