### ISSUE TITLE
no working

### ISSUE THREAD

**Issue by aamad777** [Azure/azure-cli#23663]
Not working i tried every workaround not working we need to delete azure user and its not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0474c5a5-4231-0e39-f63f-f7bc05cb7797
* Version Independent ID: 22ea94c8-cc6f-97aa-77b1-4ffca845807e
* Content: [az vm user](https://docs.microsoft.com/en-us/cli/azure/vm/user?view=azure-cli-latest#code-try-2)
* Content Source: [latest/docs-ref-autogen/vm/user.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm/user.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@aamad777 Can you please help us with debug trace for the issue?

**Comment by aamad777** [comment]
> @aamad777 Can you please help us with debug trace for the issue?

I just run the command and the output mention that not supported,

**Comment by RakeshMohanMSFT** [comment]
@aamad777 you mean when you add --debug to the command, its not supported?

**Comment by aamad777** [comment]
li.knack.cli: Command arguments: ['vm', 'user', 'delete', '-u', 'username', '-n', 'vm3', '-g', 'tlb', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f71c0b06b80>, <function OutputProducer.on_global_arguments at 0x7f71c0a1c5e0>, <function CLIQuery.on_global_arguments at 0x7f71c0a3bb80>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'vm': ['azure.cli.command_modules.vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: vm                        0.207        56       292
cli.azure.cli.core: Total (1)                 0.207        56       292
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.102         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.102         1         1  
cli.azure.cli.core: Loaded 57 groups, 293 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : vm user delete
cli.azure.cli.core: Command table: vm user delete
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f71c0001430>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/ahmad/.azure/commands/2022-08-26.07-35-24.vm_user_delete.115.log'.
az_command_data_logger: command args: vm user delete -u {} -n {} -g {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f71c00368b0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f71bff96d30>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f71bff96e50>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f71c0a1c670>, <function CLIQuery.handle_query_parameter at 0x7f71c0a3bc10>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f71bff96dc0>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ComputeManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2140
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2140
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1661503696' -> 1661503696
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/abc472da-8b7a-4eaf-aa94-561887e98d1a/resourceGroups/tlb/providers/Microsoft.Compute/virtualMachines/vm3?$expand=instanceView&api-version=2022-03-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'a5a1b1dc-2511-11ed-8e26-f6b88e8b23c8'
cli.azure.cli.core.sdk.policies:     'CommandName': 'vm user delete'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-u -n -g --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.39.0 (RPM) azsdk-python-azure-mgmt-compute/27.1.0 Python/3.9.13 (Linux-5.4.0-1089-azure-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/abc472da-8b7a-4eaf-aa94-561887e98d1a/resourceGroups/tlb/providers/Microsoft.Compute/virtualMachines/vm3?$expand=instanceView&api-version=2022-03-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/LowCostGet3Min;3999,Microsoft.Compute/LowCostGet30Min;31999'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '864804d4-3a90-44f6-8054-074e2bdfd35b'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '63df86b1-6848-4308-89bc-6ca12627ca04'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20220826T073527Z:63df86b1-6848-4308-89bc-6ca12627ca04'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 26 Aug 2022 07:35:27 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "name": "vm3",
  "id": "/subscriptions/abc472da-8b7a-4eaf-aa94-561887e98d1a/resourceGroups/tlb/providers/Microsoft.Compute/virtualMachines/vm3",
  "type": "Microsoft.Compute/virtualMachines",
  "location": "japaneast",
  "properties": {
    "vmId": "858d8746-8a3d-4a7d-877d-0dc4444add31",
    "hardwareProfile": {
      "vmSize": "Standard_DC1s_v3"
    },
    "storageProfile": {
      "imageReference": {
        "publisher": "MicrosoftWindowsDesktop",
        "offer": "Windows-10",
        "sku": "win10-21h2-pro-g2",
        "version": "latest",
        "exactVersion": "19044.1889.220805"
      },
      "osDisk": {
        "osType": "Windows",
        "name": "vm3_OsDisk_1_123aded9ad254a41abd8e4222abedd1c",
        "createOption": "FromImage",
        "caching": "ReadWrite",
        "managedDisk": {
          "storageAccountType": "StandardSSD_LRS",
          "id": "/subscriptions/abc472da-8b7a-4eaf-aa94-561887e98d1a/resourceGroups/TLB/providers/Microsoft.Compute/disks/vm3_OsDisk_1_123aded9ad254a41abd8e4222abedd1c"
        },
        "deleteOption": "Delete",
        "diskSizeGB": 127
      },
      "dataDisks": []
    },
    "osProfile": {
      "computerName": "vm3",
      "adminUsername": "ahmadk",
      "windowsConfiguration": {
        "provisionVMAgent": true,
        "enableAutomaticUpdates": true,
        "patchSettings": {
          "patchMode": "AutomaticByOS",
          "assessmentMode": "ImageDefault",
          "enableHotpatching": false
        },
        "enableVMAgentPlatformUpdates": false
      },
      "secrets": [],
      "allowExtensionOperations": true,
      "requireGuestProvisionSignal": true
    },
    "networkProfile": {"networkInterfaces":[{"id":"/subscriptions/abc472da-8b7a-4eaf-aa94-561887e98d1a/resourceGroups/TLB/providers/Microsoft.Network/networkInterfaces/vm3994","properties":{"deleteOption":"Detach"}}]},
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true
      }
    },
    "licenseType": "Windows_Client",
    "provisioningState": "Succeeded",
    "instanceView": {
      "computerName": "vm3",
      "osName": "Windows 10 Pro",
      "osVersion": "10.0.19044.1889",
      "vmAgent": {
        "vmAgentVersion": "2.7.41491.1057",
        "statuses": [
          {
            "code": "ProvisioningState/succeeded",
            "level": "Info",
            "displayStatus": "Ready",
            "message": "GuestAgent is running and processing the extensions.",
            "time": "2022-08-26T07:34:40.294+00:00"
          }
        ],
        "extensionHandlers": [
          {
            "type": "Microsoft.Azure.AzureDefenderForServers.MDE.Windows",
            "typeHandlerVersion": "1.0.7.0",
            "status": {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Ready"
            }
          },
          {
            "type": "Microsoft.CPlat.Core.RunCommandWindows",
            "typeHandlerVersion": "1.1.11",
            "status": {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Ready"
            }
          },
          {
            "type": "Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent",
            "typeHandlerVersion": "1.0.18067.0",
            "status": {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Ready",
              "message": "This virtual machine has successfully connected to Azure Log Analytics."
            }
          }
        ]
      },
      "disks": [
        {
          "name": "vm3_OsDisk_1_123aded9ad254a41abd8e4222abedd1c",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "time": "2022-08-24T12:53:53.5245894+00:00"
            }
          ]
        }
      ],
      "bootDiagnostics": {},
      "extensions": [
        {
          "name": "MDE.Windows",
          "type": "Microsoft.Azure.AzureDefenderForServers.MDE.Windows",
          "typeHandlerVersion": "1.0.7.0",
          "substatuses": [
            {
              "code": "ComponentStatus/executionlog/failed/51",
              "level": "Error",
              "displayStatus": "Provisioning failed",
              "message": "[2022-08-25 07:35:15Z][Information] Major version: 10\r\n[2022-08-25 07:35:15Z][Information] Minor version: 0\r\n[2022-08-25 07:35:15Z][Information] Build version: 19044\r\n[2022-08-25 07:35:15Z][Information] OS Name: Microsoft Windows 10 Business\r\n[2022-08-25 07:35:15Z][Information] Product type: 1\r\n[2022-08-25 07:35:15Z][Information] OperatingSystem SKU: 48\r\n[2022-08-25 07:35:15Z][Information] MDE onboarding package applicability: 0\r\n[2022-08-25 07:35:15Z][Error] Onboarding to MDE via Microsoft Defender for Cloud for this operating system is not supported \r\n[2022-08-25 07:35:15Z][Error] Failed to configure Microsoft Defender for Endpoint: Onboarding to MDE via Microsoft Defender for Cloud for this operating system is not supported\r\n[2022-08-25 07:35:15Z][Information] Set handler status (C:\\Packages\\Plugins\\Microsoft.Azure.AzureDefenderForServers.MDE.Windows\\1.0.7.0\\Status\\0.status), Status=error, Code=51, Message='Failed to configure Microsoft Defender for Endpoint: Onboarding to MDE via Microsoft Defender for Cloud for this operating system is not supported'"
            }
          ],
          "statuses": [
            {
              "code": "ProvisioningState/failed/51",
              "level": "Error",
              "displayStatus": "Provisioning failed",
              "message": "Failed to configure Microsoft Defender for Endpoint: Onboarding to MDE via Microsoft Defender for Cloud for this operating system is not supported",
              "time": "2022-08-25T07:35:15+00:00"
            }
          ]
        },
        {
          "name": "MicrosoftMonitoringAgent",
          "type": "Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent",
          "typeHandlerVersion": "1.0.18067.0",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "message": "Latest configuration has been applied to the Microsoft Monitoring Agent."
            }
          ]
        }
      ],
      "hyperVGeneration": "V2",
      "statuses": [
        {
          "code": "ProvisioningState/succeeded",
          "level": "Info",
          "displayStatus": "Provisioning succeeded",
          "time": "2022-08-25T07:35:20.1517109+00:00"
        },
        {
          "code": "PowerState/running",
          "level": "Info",
          "displayStatus": "VM running"
        }
      ]
    },
    "timeCreated": "2022-08-22T05:41:33.313072+00:00"
  },
  "resources": [
    {
      "name": "MDE.Windows",
      "id": "/subscriptions/abc472da-8b7a-4eaf-aa94-561887e98d1a/resourceGroups/tlb/providers/Microsoft.Compute/virtualMachines/vm3/extensions/MDE.Windows",
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "location": "japaneast",
      "properties": {
        "autoUpgradeMinorVersion": true,
        "forceUpdateTag": "2ebcd39d-4124-4e94-be93-f2933e04c377",
        "provisioningState": "Failed",
        "publisher": "Microsoft.Azure.AzureDefenderForServers",
        "type": "MDE.Windows",
        "typeHandlerVersion": "1.0",
        "settings": {"azureResourceId":"/subscriptions/abc472da-8b7a-4eaf-aa94-561887e98d1a/resourceGroups/TLB/providers/Microsoft.Compute/virtualMachines/vm3","forceReOnboarding":false,"vNextEnabled":true}
      }
    },
    {
      "name": "MicrosoftMonitoringAgent",
      "id": "/subscriptions/abc472da-8b7a-4eaf-aa94-561887e98d1a/resourceGroups/tlb/providers/Microsoft.Compute/virtualMachines/vm3/extensions/MicrosoftMonitoringAgent",
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "location": "japaneast",
      "properties": {
        "autoUpgradeMinorVersion": true,
        "provisioningState": "Succeeded",
        "enableAutomaticUpgrade": false,
        "publisher": "Microsoft.EnterpriseCloud.Monitoring",
        "type": "MicrosoftMonitoringAgent",
        "typeHandlerVersion": "1.0",
        "settings": {"workspaceId":"defb9037-7607-4c49-88bf-8afc5cb9f433"}
      }
    }
  ]
}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 2894, in delete_user
    raise CLIError('Deleting a user is not supported on Windows VM')
knack.util.CLIError: Deleting a user is not supported on Windows VM

cli.azure.cli.core.azclierror: Deleting a user is not supported on Windows VM
az_command_data_logger: Deleting a user is not supported on Windows VM
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f71c0001670>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 3.436 seconds (init: 0.105, invoke: 3.331)
telemetry.save: Save telemetry record of length 3099 in cache
telemetry.check: Negative: The /home/ahmad/.azure/telemetry.txt was modified at 2022-08-26 07:34:27.891267, which in less than 600.000000 s

**Comment by RakeshMohanMSFT** [comment]
Which version of az cli are you using? the latest is [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)

please share details of az --version

**Comment by aamad777** [comment]
azure-cli                         2.39.0

**Comment by RakeshMohanMSFT** [comment]
@aamad777 Please go through this issue https://github.com/Azure/azure-cli/issues/23453

**Comment by RakeshMohanMSFT** [comment]
@aamad777 https://github.com/Azure/azure-cli/issues/23595 here it is already suggested that you open a support ticket. Can you please follow that? I will continue to investigate it but in the meantime try to create a support ticket
