### ISSUE TITLE
Adding DiskController type to VM and VMSS

### ISSUE THREAD

**Issue by raktdas** [Azure/azure-cli#23664]
**Is your feature request related to a problem? Please describe.**

The Azure Storage Acceleration Platform (ASAP) is a hardware accelerator for remote storage that lives in compute (host) nodes and runs in an FPGA. In Overlake Phase 1.1, ASAP will only offer measurable performance benefits to UltraDisks. The Storage team is working to bring the ASAP technology to Premium disks, but this effort is currently a year+ out and will likely intersect with Overlake Phase 2 (post-Gen 9). Although XIO and Std disks will not see any perf benefits from ASAP, VMs that are built with ASAP integration will present all remote disks as “NVMe” instead of “SCSi.”  

SCSI stands for Small Computer Systems Interface. SCSI is a set of legacy standards for physically connecting and transferring data between computers and [peripheral devices](https://en.wikipedia.org/wiki/Peripheral). NVMe (non-volatile memory express) on the other hand is a communications protocol developed specifically for all-flash storage, NVMe enables faster performance and greater density compared to legacy protocols.

Going forward we are adding a new parameter called as **DiskControllerType** which is an enum of strings and has two values to start with: SCSI and NVMe.

**Describe the solution you'd like**
Going forward, we will be introducing a new property in Sku configuration called DiskControllerTypes which will denote the type of controller supported by the size. Currently, it could be NVMe or SCSI or both.

**Additional context**

Complete Swagger changes for this feature request are below:
https://github.com/Azure/azure-rest-api-specs/pull/20211

Resource Provider
Compute Resource Provider

Minimum API Version Required

2022-08-01

Target Date

We would like to for Public Preview in October.

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@raktdas Could you please provide the specific command and parameter related designs?

**Comment by raktdas** [comment]
Editted description. Please let me know if you need further clarifications

**Comment by zhoxing-ms** [comment]
> Going forward we are adding a new parameter called as DiskControllerType which is an enum of strings and has two values to start with: SCSI and NVMe.

@raktdas So do we need to add a new parameter `--disk-controller-type` to support `DiskControllerType`, and apply it to `az vm create` and `az vmss create` commands, right? Does it need to be supported for updated commands?

**Comment by raktdas** [comment]
yes it needs to be supported by both create and update commands

**Comment by PARADISSEEKR** [comment]
>We would like to for Public Preview in October.

Hi @raktdas ,do we need to add a preview tag to this parameter?

**Comment by raktdas** [comment]
Yes I think so. Since this feature is still under private preview and not released publicly yet.

**Comment by zhoxing-ms** [comment]
@raktdas Since CLI relies on Python SDK, in order to bump new SDK package version and develop/release this feature on this basis in time, could you help us release the new Python SDK package as soon as possible?
About how to release the new version of Python SDK package, you can ask @msyyc for help

**Comment by PARADISSEEKR** [comment]
@raktdas `BadRequest:Disk Controller Type is not supported in location eastus.` 
Some common locations(westus, eastus, CentralUSEUAP etc) have failed when I tested them. Which regions support this feature?
Do we need to add this feature to our subscription to use it?
