### ISSUE TITLE
Should UbuntuLTS image alias be 16.04.2?

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#2367]
I was surprised 16 was not the default for UbuntuLTS.
```json
{
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "14.04.4-LTS",
    "urn": "Canonical:UbuntuServer:14.04.4-LTS:latest",
    "urnAlias": "UbuntuLTS",
    "version": "latest"
}
```

**Comment by tjprescott** [comment]
@johanste thoughts?

**Comment by yugangw-msft** [comment]
@gatneil, i thought we updated already on the alias doc , but looks like we have not. We can go with 14.04.5-LTS, or 16.04-LTS. Either way, we should stop using 14.04.4 which is no longer considered stable.

**Comment by gatneil** [comment]
PR here: https://github.com/Azure/azure-cli/pull/2372

:)

**Comment by yugangw-msft** [comment]
@gatneil, I thought we can just update the [alias doc](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/quickstart-templates/aliases.json#L56) at swagger repro, and CLI will pick it up automatically.

**Comment by gatneil** [comment]
Oops; I was looking at the wrong repo; here's the actual PR: https://github.com/Azure/azure-rest-api-specs/pull/992

:)

**Comment by yugangw-msft** [comment]
fixed.
