### ISSUE TITLE
Error while copying an image from one location another location

### ISSUE THREAD

**Issue by Rajesh-u816200** [Azure/azure-cli#23670]
## Describe the bug

**Command Name**
`az image`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image {} --source-resource-group {} --source-object-name {} --target-location {} --target-resource-group {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.26.1 *

Extensions:
account 0.2.0
costmanagement 0.1.0
image-copy-extension 0.2.9

```

**Comment by Rajesh-u816200** [comment]
Error :

command failed: ['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'fl-devops-agent-image-ubuntu2004_os_disk_snapshot', '--location', 'eastus2', '--resource-group', 'fzeu2-azdagp-li-npd-rgp-01', '--source', '/subscriptions/bf8fda85-0344-4b1d-842a-7b28afee60e4/resourceGroups/pkr-Resource-Group-xxuo3yri68/providers/Microsoft.Compute/disks/pkrosxxuo3yri68', '--hyper-v-generation', 'V1', '--output', 'json', '--tags', 'created_by=image-copy-extension']
output: ERROR: (NotFound) Resource pkrosxxuo3yri68 is not found.

The command failed with an unexpected error. Here is the traceback:
Command '['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'fl-devops-agent-image-ubuntu2004_os_disk_snapshot', '--location', 'eastus2', '--resource-group', 'fzeu2-azdagp-li-npd-rgp-01', '--source', '/subscriptions/bf8fda85-0344-4b1d-842a-7b28afee60e4/resourceGroups/pkr-Resource-Group-xxuo3yri68/providers/Microsoft.Compute/disks/pkrosxxuo3yri68', '--hyper-v-generation', 'V1', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\u816200\.azure\cliextensions\image-copy-extension\azext_imagecopy\custom.py", line 108, in imagecopy
    run_cli_command(cli_cmd)
  File "C:\Users\u816200\.azure\cliextensions\image-copy-extension\azext_imagecopy\cli_utils.py", line 45, in run_cli_command
    raise ex
  File "C:\Users\u816200\.azure\cliextensions\image-copy-extension\azext_imagecopy\cli_utils.py", line 21, in run_cli_command
    cmd_output = check_output(cmd, stderr=STDOUT, universal_newlines=True)
  File "subprocess.py", line 415, in check_output
  File "subprocess.py", line 516, in run
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'azure.cli', 'snapshot', 'create', '--name', 'fl-devops-agent-image-ubuntu2004_os_disk_snapshot', '--location', 'eastus2', '--resource-group', 'fzeu2-azdagp-li-npd-rgp-01', '--source', '/subscriptions/bf8fda85-0344-4b1d-842a-7b28afee60e4/resourceGroups/pkr-Resource-Group-xxuo3yri68/providers/Microsoft.Compute/disks/pkrosxxuo3yri68', '--hyper-v-generation', 'V1', '--output', 'json', '--tags', 'created_by=image-copy-extension']' returned non-zero exit status 3.

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by Rajesh-u816200** [comment]
I am trying to copy an image from one location to another location and i am facing this error. 
How can i solve this?

**Comment by zhoxing-ms** [comment]
I can reproduce this problem, and I find that it should be a service issue. 

```
REST API: https://docs.microsoft.com/en-us/rest/api/compute/snapshots/create-or-update?tabs=HTTP
Request Body:
{
    "location": "westus", 
    "tags": { }, 
    "sku": {
        "name": "Standard_LRS"
    }, 
    "properties": {
        "hyperVGeneration": "V1", 
        "creationData": {
            "createOption": "Copy", 
            "sourceResourceId": "/subscriptions/{subscription}/resourceGroups/zhoxing-test/providers/Microsoft.Compute/disks/zhoxing-test_OsDisk_1_c24b21c9ece3474589aa4dcb5d667921"
        }
    }
}
Response Body:
{
  "error": {
    "code": "NotFound",
    "message": "Resource zhoxing-test_OsDisk_1_c24b21c9ece3474589aa4dcb5d667921 is not found."
  }
}
```
When the location of the `sourceResourceId` is inconsistent with the `location` parameter *(target location)*, the resource cannot be found error will be returned. Therefore, this issue needs to be investigated by the service team.
**'x-ms-request-id': '9038e696-6c76-4933-a6d4-24f660334389'**

**Comment by RakeshMohanMSFT** [comment]
@Rajesh-u816200 Did you get a chance to go through this thread https://github.com/Azure/azure-cli/issues/11909?
