### ISSUE TITLE
Doc: command in core package isn't showed under parent command module reference doc

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli#23679]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62
`az containerapp` is command module in extension package.
`az containerapp connection` is command in core package.
In reference doc of `az containerapp`, there's no `az containerapp connection`:  https://docs.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest.

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@yungezz Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@panchagnula Would you be able to help us in answering this one ?

**Comment by panchagnula** [comment]
Sorry I don't own any of the "connection" for webapp or containerapp , would be a better question for core-cli, & they can engage the owner of that code. Another team owns that part of the logic which not part of az containerapp code, & being made to look like its part of az containerapp.

**Comment by yungezz** [comment]
hi @navba-MSFT we own the `az containerapp connection` command. just ping me if any question. thanks

**Comment by navba-MSFT** [comment]
@yonzhan Since the ask is around the CLI doc improvement to help look at how to generate the doc correctly, could you please tag the right folks who can help on this ?

**Comment by yungezz** [comment]
the item is tracked by feature in docs team ADO, close the issue for now.
