### ISSUE TITLE
`az cosmosdb network-rule remove` unable to remove rule  due to subnet case-sensitivity issue

### ISSUE THREAD

**Issue by t-bzhan** [Azure/azure-cli#23680]
**Related command**

`az cosmosdb update`
`az cosmosdb network-rule remove`

**Describe the bug**

I used `az cosmosdb update` to add multiple virtual network rules, one of the rules has the subnet id with `/subscriptions/d7cfdb98-c118-458d-8bdf-246be66b1f5e/resourceGroups/AFDX-Portal-BugBash/providers/Microsoft.Network/virtualNetworks/testnetwork/subnets/default`, it looks like Cosmos DB's backend will normalize the subnet id to `/subscriptions/d7cfdb98-c118-458d-8bdf-246be66b1f5e/resourceGroups/afdx-portal-bugbash/providers/Microsoft.Network/virtualNetworks/testnetwork/subnets/default` (the resource group name has been converted to lowercase)

When the command `az cosmosdb network-rule remove` is used to remove the rule with the origin subnet id, it will fail with error:

> cli.azure.cli.core.azclierror: This rule does not exist for the Cosmos DB account
> az_command_data_logger: This rule does not exist for the Cosmos DB account

It looks like CLI is doing case-sensitive comparison [here](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/cosmosdb/custom.py#L1644-L1652):
![image](https://user-images.githubusercontent.com/61817681/186819581-e6c01939-51f2-491b-b3ec-6b1532e05b29.png)

We might consider to change it to case-insensitive.

**To Reproduce**

Add a network rule with subnet that has uppercase letters in its resource group name
Use `az cosmosdb network-rule remove` to remove the network rule

**Expected behavior**

`az cosmosdb network-rule remove` should be able to remove the network rule

**Environment summary**

> azure-cli                         2.23.0 *
> 
> core                              2.23.0 *
> telemetry                          1.0.6

**Additional context**
Debug output:

> cli.knack.cli: Command arguments: ['cosmosdb', 'network-rule', 'remove', '--resource-group', 'bo-private', '--name', 'nwisolation-demo', '--subnet', '/subscriptions/d7cfdb98-c118-458d-8bdf-246be66b1f5e/resourceGroups/AFDX-Portal-BugBash/providers/Microsoft.Network/virtualNetworks/testnetwork/subnets/default', '--debug']
> cli.knack.cli: __init__ debug log:
> Enable color in terminal.
> cli.knack.cli: Event: Cli.PreExecute []
> cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fc2604b8bf8>, <function OutputProducer.on_global_arguments at 0x7fc25ffe3730>, <function CLIQuery.on_global_arguments at 0x7fc260002840>]
> cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
> cli.azure.cli.core: Modules found from index for 'cosmosdb': ['azure.cli.command_modules.cosmosdb']
> cli.azure.cli.core: Loading command modules:
> cli.azure.cli.core: Name                  Load Time    Groups  Commands
> cli.azure.cli.core: cosmosdb                  0.007        33       126
> cli.azure.cli.core: Total (1)                 0.007        33       126
> cli.azure.cli.core: Loaded 33 groups, 126 commands.
> cli.azure.cli.core: Found a match in the command table.
> cli.azure.cli.core: Raw command  : cosmosdb network-rule remove
> cli.azure.cli.core: Command table: cosmosdb network-rule remove
> cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fc25ee94f28>]
> cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/bzhan/.azure/commands/2022-08-25.16-32-40.cosmosdb_network-rule_remove.2211.log'.
> az_command_data_logger: command args: cosmosdb network-rule remove --resource-group {} --name {} --subnet {} --debug
> cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fc25eec0f28>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7fc25eddb048>]
> cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
> cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fc25eddb0d0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fc25eddb1e0>]
> cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
> cli.knack.cli: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7fc25ed62a60>]
> cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fc25ffe37b8>, <function CLIQuery.handle_query_parameter at 0x7fc2600028c8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7fc25ee4af28>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fc25eddb158>]
> cli.azure.cli.core.commands.client_factory: Getting management service client client_type=CosmosDBManagementClient cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)
> cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
> cli.azure.cli.core.util: attempting to read file /home/bzhan/.azure/accessTokens.json as utf-8-sig
> adal-python: 9ccdae77-1037-40d7-8217-0f3b02a83c71 - Authority:Performing instance discovery: ...
> adal-python: 9ccdae77-1037-40d7-8217-0f3b02a83c71 - Authority:Performing static instance discovery
> adal-python: 9ccdae77-1037-40d7-8217-0f3b02a83c71 - Authority:Authority validated via static instance discovery
> adal-python: 9ccdae77-1037-40d7-8217-0f3b02a83c71 - TokenRequest:Getting token from cache with refresh if necessary.
> adal-python: 9ccdae77-1037-40d7-8217-0f3b02a83c71 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
> adal-python: 9ccdae77-1037-40d7-8217-0f3b02a83c71 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
> adal-python: 9ccdae77-1037-40d7-8217-0f3b02a83c71 - CacheDriver:Found 3 potential entries.
> adal-python: 9ccdae77-1037-40d7-8217-0f3b02a83c71 - CacheDriver:Resource specific token found.
> adal-python: 9ccdae77-1037-40d7-8217-0f3b02a83c71 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'Gclelib00ZXydn21ArrXSityWPSCyEImrYnRBgVp3mc=', RefreshTokenId: b'+meSf96WYSu7DVmW3Jga6xtdlzbo9AxdgycPsK+p8Nk='
> cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourceGroups/bo-private/providers/Microsoft.DocumentDB/databaseAccounts/nwisolation-demo?api-version=2021-03-15'
> cli.azure.cli.core.sdk.policies: Request method: 'GET'
> cli.azure.cli.core.sdk.policies: Request headers:
> cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
> cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '7b40d786-2450-11ed-b8ab-00155d7c28b6'
> cli.azure.cli.core.sdk.policies:     'CommandName': 'cosmosdb network-rule remove'
> cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --subnet --debug'
> cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.23.0 (DEB) azsdk-python-mgmt-cosmosdb/6.2.0 Python/3.6.10 (Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-debian-buster-sid)'
> cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
> cli.azure.cli.core.sdk.policies: Request body:
> cli.azure.cli.core.sdk.policies: This request has no body
> urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
> urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourceGroups/bo-private/providers/Microsoft.DocumentDB/databaseAccounts/nwisolation-demo?api-version=2021-03-15 HTTP/1.1" 200 None
> cli.azure.cli.core.sdk.policies: Response status: 200
> cli.azure.cli.core.sdk.policies: Response headers:
> cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-store, no-cache'
> cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
> cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
> cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
> cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
> cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
> cli.azure.cli.core.sdk.policies:     'x-ms-gatewayversion': 'version=2.14.0'
> cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
> cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
> cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '3e9f9fbc-2f79-4ddf-84a7-e8d33dced47f'
> cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '3e9f9fbc-2f79-4ddf-84a7-e8d33dced47f'
> cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20220825T083241Z:3e9f9fbc-2f79-4ddf-84a7-e8d33dced47f'
> cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
> cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 25 Aug 2022 08:32:40 GMT'
> cli.azure.cli.core.sdk.policies: Response content:
> cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourceGroups/bo-private/providers/Microsoft.DocumentDB/databaseAccounts/nwisolation-demo","name":"nwisolation-demo","location":"West US","type":"Microsoft.DocumentDB/databaseAccounts","kind":"GlobalDocumentDB","tags":{"defaultExperience":"Core (SQL)","hidden-cosmos-mmspecial":""},"systemData":{"createdAt":"2022-07-21T02:17:48.2574042Z"},"properties":{"provisioningState":"Succeeded","documentEndpoint":"https://nwisolation-demo.documents.azure.com:443/","publicNetworkAccess":"Enabled","enableAutomaticFailover":false,"enableMultipleWriteLocations":false,"enablePartitionKeyMonitor":false,"isVirtualNetworkFilterEnabled":true,"virtualNetworkRules":[{"id":"/subscriptions/d7cfdb98-c118-458d-8bdf-246be66b1f5e/resourceGroups/afdx-portal-bugbash/providers/Microsoft.Network/virtualNetworks/testnetwork/subnets/default","ignoreMissingVNetServiceEndpoint":false}],"EnabledApiTypes":"Sql","disableKeyBasedMetadataWriteAccess":false,"enableFreeTier":false,"enableAnalyticalStorage":false,"analyticalStorageConfiguration":null,"instanceId":"0232e3dc-0ce4-4e75-a192-814506e8c9c0","databaseAccountOfferType":"Standard","defaultIdentity":"FirstPartyIdentity","networkAclBypass":"None","consistencyPolicy":{"defaultConsistencyLevel":"Session","maxIntervalInSeconds":5,"maxStalenessPrefix":100},"configurationOverrides":{},"writeLocations":[{"id":"nwisolation-demo-westus","locationName":"West US","documentEndpoint":"https://nwisolation-demo-westus.documents.azure.com:443/","provisioningState":"Succeeded","failoverPriority":0,"isZoneRedundant":false}],"readLocations":[{"id":"nwisolation-demo-westus","locationName":"West US","documentEndpoint":"https://nwisolation-demo-westus.documents.azure.com:443/","provisioningState":"Succeeded","failoverPriority":0,"isZoneRedundant":false}],"locations":[{"id":"nwisolation-demo-westus","locationName":"West US","documentEndpoint":"https://nwisolation-demo-westus.documents.azure.com:443/","provisioningState":"Succeeded","failoverPriority":0,"isZoneRedundant":false}],"failoverPolicies":[{"id":"nwisolation-demo-westus","locationName":"West US","failoverPriority":0}],"cors":[],"capabilities":[],"ipRules":[{"ipAddressOrRange":"104.42.195.92"},{"ipAddressOrRange":"40.76.54.131"},{"ipAddressOrRange":"52.176.6.30"},{"ipAddressOrRange":"52.169.50.45"},{"ipAddressOrRange":"52.187.184.26"},{"ipAddressOrRange":"167.220.255.3"}],"backupPolicy":{"type":"Periodic","periodicModeProperties":{"backupIntervalInMinutes":240,"backupRetentionIntervalInHours":8,"backupStorageRedundancy":"Geo"}},"networkAclBypassResourceIds":[]},"identity":{"type":"None"}}
> cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
> cli.azure.cli.core.util: Traceback (most recent call last):
>   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
>     cmd_result = self.invocation.execute(args)
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
>     raise ex
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
>     results.append(self._run_job(expanded_arg, cmd_copy))
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
>     result = cmd_copy(params)
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
>     return self.handler(*args, **kwargs)
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
>     return op(**command_args)
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/cosmosdb/custom.py", line 1397, in cli_cosmosdb_network_rule_remove
>     raise CLIError("This rule does not exist for the Cosmos DB account")
> knack.util.CLIError: This rule does not exist for the Cosmos DB account
> 
> cli.azure.cli.core.azclierror: This rule does not exist for the Cosmos DB account
> az_command_data_logger: This rule does not exist for the Cosmos DB account
> cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fc25ee991e0>]

**Comment by SaurabhSharma-MSFT** [comment]
@t-bzhan We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@t-bzhan The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
