### ISSUE TITLE
az webapp create failure

### ISSUE THREAD

**Issue by mantissystems** [Azure/azure-cli#23689]
## Describe the bug

**Command Name**
`az webapp create`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp create --resource-group {} --plan {} --name {} --runtime {} --deployment-local-git`

## Environment Summary
```
Linux-5.15.0-46-generic-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@mantissystems Can you please upgrade to the latest version of azure cli [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) and retry
