### ISSUE TITLE
az keyvault delete fails with cryptic error message

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#2369]
When trying to delete a valid KeyVault, the command fails with the following unhelpful error message:
`Operation failed with status: 204. Details: none`

**Comment by tjprescott** [comment]
Does the keyvault successfully delete?

**Comment by tjprescott** [comment]
But Details: none makes sense since a 204 is a no content response code. :smile:

**Comment by binderjoe** [comment]
Sorry, should have added that info.  The keyvault does not get deleted, so 204 is the wrong error code but the message does indeed match the code, which is something :).  I suspect this happens if you don't have rights to delete the keyvault, but I would love  better error message.  To repro, create a keyvault with --no-self-perms then try to delete it.

**Comment by tjprescott** [comment]
You will also get this if you try to delete a keyvault that doesn't exist.

**Comment by tjprescott** [comment]
I think you are right about not having the rights to delete because when I ran it (without --no-self-perms) I was able to delete it and the second attempt triggered the error.

**Comment by tjprescott** [comment]
@binderjoe I created a keyvault with no-self-perms and I was still able to delete the vault with no issues. I didn't get the 204 error until I tried to delete the already deleted vault. Were you logged in as a user or service principal (though I tried both scenarios and was able to delete the keyvault)

**Comment by tjprescott** [comment]
I cannot repro this. If you still encounter this issue now that the service principal scenario has been enabled, please reopen.
