### ISSUE TITLE
Microsoft.ConnectVMwarevSphere Resource provider will not register / unregister.

### ISSUE THREAD

**Issue by aabel1** [Azure/azure-cli#23692]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
Register-AzResourceProvider -ProviderNamespace Microsoft.ConnectedVMwarevSphere

**Describe the bug**
Microsoft.ConnectedVMwarevSphere stuck registering or unregistering, unable to get resource provider to register.

**To Reproduce**
Register-AzResourceProvider -ProviderNamespace Microsoft.ConnectedVMwarevSphere
or:
Unregister-AzResourceProvider -ProviderNamespace "Microsoft.ConnectedVMwarevSphere"

**Expected behavior**
Microsoft.ConnectedVMwarevSphere to be registered or not registered. Status message stuck indefinitely in either registering or unregistering.
**Environment summary**
Possible to force the Microsoft.ConnectedVMwarevSphere module to register / unregister? 

Azure Cloud Shell
**Additional context**

**Comment by yonzhan** [comment]
Please open this issue on azure-powershell repo.
