### ISSUE TITLE
CLI should support specific storage endpoint for shared key auth mode

### ISSUE THREAD

**Issue by Zhupku** [Azure/azure-cli#23702]
### Related command

All datapath command

### Resource Provider

Microsoft.Storage

### Description of Feature or Work Requested

Now since CLI parse the storage account name from the endpoint by using ".core" key word, when using shared key auth mode. It will throw an exception when parsing the endpoint not including ".core" (https://github.com/Azure/azure-sdk-for-python/blob/afce4523ab32e6f3b12bc7f65f2076b99516972e/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py#L87-L94). CLI should use "--account-name" parameters if it's provided.

### Minimum API Version Required

/

### Swagger PR link

/

### Target Date

ASAP

**Comment by yonzhan** [comment]
storage
