### ISSUE TITLE
Azure CLI not found on path Stack

### ISSUE THREAD

**Issue by Marwen-TAALLAH** [Azure/azure-cli#23706]
### Resource Provider

azure function app

### Description of Feature or Work Requested

I'm working on an azure python app function of queue trigger type that create a VM once triggered.
To do so, I need to work with the **ManagedIdentityCredential()** in order to acquire a credential object using CLI-based authentication but I'm having this error:

**Result: Failure Exception: CredentialUnavailableError: Azure CLI not found on path Stack: File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py"**

Here's the piece of code that causing the error:

```import logging
import json
import base64
import azure.functions as func
import requests
from azure.identity import ManagedIdentityCredential
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.network import NetworkManagementClient
from azure.mgmt.compute import ComputeManagementClient

credential = ManagedIdentityCredential()
```

### Minimum API Version Required

none

### Swagger PR link

none

### Target Date

30/08/2022

### Additional context

Result: Failure Exception: CredentialUnavailableError: Azure CLI not found on path Stack: File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py"

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@Marwen-TAALLAH Based on the path in the error message, you seem to be running Azure Functions in a docker container and are likely using the `AzureCLICredential`. Could you double check to make sure you are using the right container image?

Also, note that `ManagedIdentityCredential` doesn't actually use CLI-based authentication, instead uses the Managed Identity Endpoint available when running on Azure.
