### ISSUE TITLE
python module not found on the azure app function

### ISSUE THREAD

**Issue by Marwen-TAALLAH** [Azure/azure-cli#23700]
### Resource Provider

azure function app

### Description of Feature or Work Requested

I'm not able to execute my cloud function due to failures to import modules, module azure-identity for example, it's telling me module not found, I had my requirements.txt file:

azure-functions
msrestazure
azure-identity
azure.keyvault.secrets
azure-cli

and my code imports:

import logging
import json
import base64
import azure.functions as func
import requests
from azure.identity import AzureCliCredential
from azure.mgmt.resource import ResourceManagementClient
from azure.mgmt.network import NetworkManagementClient
from azure.mgmt.compute import ComputeManagementClient
import os

![no_module](https://user-images.githubusercontent.com/29490363/187159693-6025be12-7ab5-4caa-9292-18fcff27597e.png)

My files hierarchy:

![tree](https://user-images.githubusercontent.com/29490363/187160105-12b7c7de-8ec0-4806-9916-e63e9f1bf370.png)

This issue is not related to the module itself, I tried with different modules, requests for example and always the same issue.

### Minimum API Version Required

none

### Swagger PR link

none

### Target Date

30/08/2022

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@Marwen-TAALLAH This is usually a deployment problem. Could you share more details on how you are deploying your function app here?

**Comment by PramodValavala-MSFT** [comment]
@Marwen-TAALLAH That could be the problem since you might be building (and hence fetching required packages) for the wrong platform, which isn't recommended since native dependencies might not still work. This is why most of the tooling for Azure Functions uses [Remote Build](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#remote-build), which fetches (and builds if required) all the dependencies on Azure itself.

Ensure you have the following application settings mentioned in the Remote Build docs.

```
ENABLE_ORYX_BUILD=true
SCM_DO_BUILD_DURING_DEPLOYMENT=true
```

Check out the [Publishing to Azure section](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=asgi%2Capplication-level#publishing-to-azure) of the Python Reference docs for more information.

**Comment by Marwen-TAALLAH** [comment]
> @Marwen-TAALLAH That could be the problem since you might be building (and hence fetching required packages) for the wrong platform, which isn't recommended since native dependencies might not still work. This is why most of the tooling for Azure Functions uses [Remote Build](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#remote-build), which fetches (and builds if required) all the dependencies on Azure itself.
> 
> Ensure you have the following application settings mentioned in the Remote Build docs.
> 
> ```
> ENABLE_ORYX_BUILD=true
> SCM_DO_BUILD_DURING_DEPLOYMENT=true
> ```
> 
> Check out the [Publishing to Azure section](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=asgi%2Capplication-level#publishing-to-azure) of the Python Reference docs for more information.

I already specified that in my code and I can see them correctly in the azure portal but i'm still having the same problem:

```resource "azurerm_function_app" "dworker" {
    name = "${var.function_app_name}"
    location = "${var.location}"
    resource_group_name = local.rg
    app_service_plan_id        = azurerm_app_service_plan.sp.id
    storage_account_name       = azurerm_storage_account.function.name
    storage_account_access_key = azurerm_storage_account.function.primary_access_key

    app_settings = {
        https_only = false
        FUNCTIONS_WORKER_RUNTIME = "python"
        FUNCTION_APP_EDIT_MODE     = "readwrite"
        SCM_DO_BUILD_DURING_DEPLOYMENT = true
        ENABLE_ORYX_BUILD     =   true
        "WEBSITE_RUN_FROM_PACKAGE"    = "https://${azurerm_storage_account.function.name}.blob.core.windows.net/${azurerm_storage_container.storage_container.name}/${azurerm_storage_blob.storage_blob.name}${data.azurerm_storage_account_blob_container_sas.storage_account_blob_container_sas.sas}"
        HASH = "${base64encode(filesha256("${data.archive_file.file_function_app.output_path}"))}"
        APPINSIGHTS_INSTRUMENTATIONKEY = azurerm_application_insights.appinsights.instrumentation_key
    }
}
```

**Comment by PramodValavala-MSFT** [comment]
@Marwen-TAALLAH Remote Build doesn't happen when using an External Package URL as mentioned [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#external-package-url). You will have to do a zip deploy to trigger it.

**Comment by Marwen-TAALLAH** [comment]
> @Marwen-TAALLAH Remote Build doesn't happen when using an External Package URL as mentioned [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#external-package-url). You will have to do a zip deploy to trigger it.

Even the zip deploy doesn't work. Here's the situation:
I have this terraform rsource:

```
resource "azurerm_function_app" "dworker" {
    name = "${var.function_app_name}"
    location = "${var.location}"
    resource_group_name = local.rg
    app_service_plan_id        = azurerm_app_service_plan.sp.id
    storage_account_name       = azurerm_storage_account.function.name
    storage_account_access_key = azurerm_storage_account.function.primary_access_key

    app_settings = {
        https_only = false
        FUNCTIONS_WORKER_RUNTIME = "python"
        FUNCTION_APP_EDIT_MODE     = "readwrite"
        HASH = "${base64encode(filesha256("${data.archive_file.file_function_app.output_path}"))}"
        APPINSIGHTS_INSTRUMENTATIONKEY = azurerm_application_insights.appinsights.instrumentation_key
    }

    provisioner "local-exec" {
    command = "az webapp deployment source config-zip --resource-group ${local.rg} --name ${var.function_app_name} --src ${data.archive_file.file_function_app.output_path}"
  }
}
```

Nos as you can see, I'm using the zip deploy but now i'm having this error:
![local_exec](https://user-images.githubusercontent.com/29490363/189126246-5b4b3fc3-c465-4616-a063-087d1d9724b0.png)
 
I noticed that a lot of people had this error before since even 2020 and no one suggested a solution!

**Comment by PramodValavala-MSFT** [comment]
@Marwen-TAALLAH Could you run the command shown at the end of the error log - `az webapp log deployment show -n dworkerFnexec -g dev-de-azure-test` and share the log from there?

**Comment by Marwen-TAALLAH** [comment]
Here's a screenshot with all the app setting set as you told me and the WEBSITE_RUN_FROM_PACKAGE = 1:

![2nd](https://user-images.githubusercontent.com/29490363/189233566-b16f12f2-4cf1-4fcd-93b1-e8ef865b4a20.png)
I'm still grtting the exact same problem:


![error_exec2](https://user-images.githubusercontent.com/29490363/189234195-58fc108e-5698-4c4c-aeb3-a079c56a57ca.png)

and when running `az webapp log deployment show -n dworkerFnexec -g dev-de-azure-test`, I get the same message:

![webapp_log2](https://user-images.githubusercontent.com/29490363/189234394-d733dd37-5dce-4816-a13f-83dbf8143060.png)

**Comment by Marwen-TAALLAH** [comment]
Adding the **version** an the **site_config** to the resource made the **terraform apply** pass but with a **202 status code** so after the apply passes I don't find my function in the azure portal.

The changes I added:

![5th](https://user-images.githubusercontent.com/29490363/189365723-56208a7d-41ba-42f4-85f7-c21ea1067c76.png)

The result i'm getting:
![202-1](https://user-images.githubusercontent.com/29490363/189366684-29bf1561-54b0-4d31-ac3d-d6b6c9c826fd.png)

Any ideas?

**Comment by PramodValavala-MSFT** [comment]
@Marwen-TAALLAH You still have the `WEBSITE_RUN_FROM_PACKAGE` app setting [which should be removed](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#general-considerations) for Remote Build to work. Sorry for not being explicit about this earlier.

**Comment by Marwen-TAALLAH** [comment]
Now after doing that, the function is uploaded but I'm not able to use the **ManagedIdentityCredential** in my python app function.
Te piece of code that is causing the error (line 31):
![mds](https://user-images.githubusercontent.com/29490363/189405471-1305206c-1eeb-4bc8-81d0-455e20865fa3.png)

the error message i'm getting:
![mds_error](https://user-images.githubusercontent.com/29490363/189405983-1ad94eb6-b87b-4c08-b581-ffebd5700e43.png)

**Comment by PramodValavala-MSFT** [comment]
@Marwen-TAALLAH Could you confirm if you have Managed Identity configured correctly, since the terraform code you shared doesn't seem to have the [`identity`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app#identity) block in it.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by Marwen-TAALLAH** [comment]
> @Marwen-TAALLAH Could you confirm if you have Managed Identity configured correctly, since the terraform code you shared doesn't seem to have the [`identity`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app#identity) block in it.

Thanks, that solved my issue.

**Comment by PramodValavala-MSFT** [comment]
@Marwen-TAALLAH Glad that your issue was resolved! Closing.
