### ISSUE TITLE
az synapse spark pool update 

### ISSUE THREAD

**Issue by Danny-de-bree** [Azure/azure-cli#23719]
az synapse spark pool update

Missing an parameter to set dynamic allocators and set the range of those dynamic allocators.

**Describe the solution you'd like**
Add some thing like  --dynamic-allocators {false, true} --dynamic-allocators-min-count {integer] --dynamic-allocators-max-count {integer]  

Really needed in our DevOps pipelines to prevent certain update issues.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by wonner** [comment]
Hi @Danny-de-bree, thanks for your feedback. @kevinzz6 is working on the change.

**Comment by wonner** [comment]
https://github.com/Azure/azure-cli/pull/23960 Close as PR checked in.
