### ISSUE TITLE
az ad sp credential list does not show the same as the Azure portal

### ISSUE THREAD

**Issue by yrro** [Azure/azure-cli#23717]
## Describe the bug

**Command Name**
`az ad sp credential list --id ID`

**Errors:**
The output shows me the credential reset with `az ad sp credential reset --id ID`. But in the Azure portal, looking at the app registration's secrets, there is a different secret displayed with a different (shorter) expiry date.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

* Create an app registration
* Create a secret in the Azure portal. Max lifetime is 2 years :facepalm:
* `az ad sp credential list --id ID` outputs nothing. The secret created in the Azure portal cannot be seen in the CLI
* `az ad sp credential reset --id ID --years 100`
* Look at the app registration's secrets in the Azure portal. The newly created secret is not there - the old one is still present
* `az ad sp credential list --id ID` will show the new 100 year secret.

## Environment Summary
```
Linux-5.18.0-3-amd64-x86_64-with-glibc2.34, Debian GNU/Linux 11 (bullseye)
Python 3.10.5
Installer: DEB

azure-cli 2.39.0

Extensions:
azure-firewall 0.13.0
ip-group 0.1.2
support 1.0.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by yrro** [comment]
I've done a bit more experimentation. Created a brand new app registration and reset its secret with `az ad app credential reset`. After a few minutes (and a web page refresh) the new credential appears in the Azure portal.

So I think it's simply that the docs are wrong: `az ad sp ...` commands are not equivalent to `az ad app ...` commands; they operate on the enterprise application, as opposed to the app registration.

To be precise, [this page](https://docs.microsoft.com/en-us/cli/azure/ad/sp/credential?view=azure-cli-latest) says:

> The credential update will be applied on the Application object the service principal is associated with. In other words, you can accomplish the same thing using "az ad app credential".

So it appears that enterprise applications/service principals have their own set of secrets, that are not visible anywhere in the Azure portal. A fun place to stash away backdoor credentials!

**Comment by RakeshMohanMSFT** [comment]
@yrro Thank you for reaching out, we will look into it.

**Comment by RakeshMohanMSFT** [comment]
@yrro Thank you for reaching out to us. As you pointed out they are used for different purposes. [az ad app credential list](https://docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&tabs=http) uses application api for ad graph and [az ad sp credential list](https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0) uses the application api.

We will get the document updated to use better words to avoid confusion.

**Comment by yrro** [comment]
I don't think there's any feedback required from me?

**Comment by RakeshMohanMSFT** [comment]
@yrro No we do not need it. Thank you. I will close this thread, if you have no further questions.

**Comment by yrro** [comment]
Is there a link to the issue # for the doc update?

**Comment by RakeshMohanMSFT** [comment]
@yrro No yet. We will get it updated soon.

**Comment by yrro** [comment]
https://learn.microsoft.com/en-us/cli/azure/ad/sp/credential?view=azure-cli-latest no longer has text similar to 'The credential update will be applied on the Application object the service principal is associated with. In other words, you can accomplish the same thing using "az ad app credential".' so I am closing this issue.

**Comment by jiasli** [comment]
Duplicate of #23566
