### ISSUE TITLE
Azure-cli request to update for a Subscription API

### ISSUE THREAD

**Issue by Ochirkhuyag** [Azure/azure-cli#23727]
**Resource Provider**
Microsoft.Subscription

**Description of Feature or Work Requested**
We have found an issue missing field for a response of "acceptOwnershipStatus" API on swagger. On the service side, it is there. So, we have corrected it on swagger specs and generated python SDK. The python SDK is released now. We would like AzureCLI to refer to latest changes.

**Minimum API Version Required**
2021-10-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/subscription/resource-manager/Microsoft.Subscription/stable/2021-10-01/subscriptions.json

**Python SDK**
https://pypi.org/project/azure-mgmt-subscription/3.1.0/

**Target Date**
ASAP

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by PARADISSEEKR** [comment]
Hi @Ochirkhuyag What should we do for it? To add a command for acceptOwnershipStatus? such as `az accept ownership status`?

**Comment by Ochirkhuyag** [comment]
@PARADISSEEKR We have found an issue missing field for a response of "acceptOwnershipStatus" API on swagger. On the service side, it is there and there is no change. So, we have corrected it on swagger specs and generated python SDK. The python SDK is released now. We would like AzureCLI to refer to latest changes.

I am not sure how to hit it from azure-cli. Current azure-cli should be based on previous wrong swagger specs and python SDK that generated by the wrong swagger specs. So, we would like to get azure-cli call corrected python SDK.

**Comment by PARADISSEEKR** [comment]
> I am not sure how to hit it from azure-cli. Current azure-cli should be based on previous wrong swagger specs and python SDK that generated by the wrong swagger specs. So, we would like to get azure-cli call corrected python SDK.

@Ochirkhuyag  
Usually one CLI command uses one swagger API.
There is no command corresponding to `acceptOwnershipStatus` API in CLI before, do we need to add a command for it?
There is no API for `az account create` in the latest swagger version, do we need to delete this command?

**Comment by Ochirkhuyag** [comment]
@PARADISSEEKR 

Since CLI for the swagger version (2021-10-01) is already released, acceptOwnershipStatus API should be in the latest/current CLI. The current changes is just updating the v2021-10-01, just adding a missing field for a response of acceptOwnershipStatus API.

I am not sure how to check the current CLI. 

Please check a conversation for [previous cli release for 2021-10-01](https://github.com/Azure/azure-cli/issues/20420)
[Above/previous conversation](https://github.com/Azure/azure-cli/issues/20420) is for 2021-10-01 version. There is nothing mentioned about the acceptOwnershipStatus API. As long as the swagger specs for v2021-10-01 has acceptOwnershipStatus API, it should be released, I think.

I found a huge conversation about 'az account create'. Based on the [conversation](https://github.com/Azure/azure-cli/issues/20420), 'az account alias create' has the same function as command 'az account create' and 'deprecate_info' flag should be added to 'az account create' command. But does not specify the expiration date and version.

Please check a conversation for [previous cli release for 2021-10-01](https://github.com/Azure/azure-cli/issues/20420)! You will find all of these conversation in detailed.
