### ISSUE TITLE
How to update security patches in azure container registry automatically?

### ISSUE THREAD

**Issue by shaikmoeed** [Azure/azure-cli#23734]
**Scenario:**

1. There is an azure container registry(acr) with many repositories (around 20)
2. Each repository has different tags like image:dev0.1, dev0.2, prod0.1, prod0.2
3. There are more than 100 images which include all available tags within each repository

I know about the `acr` task, which can be used to update an image automatically when we update its base image.

In my scenario, I need to create more than 100 `acr` tasks for each tag and also maintain a backup of old images for recovery in case of production failures.

I would like to know, Is there a standard and simple way to deal with this case?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@shaikmoeed Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@shaikmoeed I am doing some research on this. I will update this thread once I have more details on this.

**Comment by shaikmoeed** [comment]
@navba-MSFT Any update?

**Comment by navba-MSFT** [comment]
@shaikmoeed I have reached out to the Product Owners to get some pointers and currently awaiting their reply.

**Comment by navba-MSFT** [comment]
@shaikmoeed Apologies for the late response. I have heard back from the Product Owners and unfortunately, there are no other options available at the moment. Customers can use a combination of ACR Tasks, ADO tasks, and custom implementation to achieve your goals but there is no out-of-the-box solution you can leverage. An alternative is for you to host your own [Dependabot](https://github.com/dependabot/dependabot-core#--------------------------------)/[Renovatebot](https://github.com/renovatebot/renovate#renovate) infrastructure to manage their dependencies. Hope this helps.
If ypu have any follow-up question on this, please feel free to reopen this issue. We would be happy to help.

**Comment by weshockley** [comment]
@navba-MSFT - I have a cx asking the same question. Is there any update or any new features in the roadmap could avoid re-deploy the ci/cd. Thanks in advance.

**Comment by navba-MSFT** [comment]
@weshockley Since you are internal to Microsoft, I have sent you an email with suggestion.
