### ISSUE TITLE
[Compute] Update az sig image-version for targetExtendedLocations

### ISSUE THREAD

**Issue by MSFT-BrianEddy** [Azure/azure-cli#23745]
**Resource Provider**

Compute

**Description of Feature or Work Requested**

Add support for edge zones to sig image-version. This work is similar to the –-target-region-encryption and –-target-regions parameters currently used, we need the following supported optional parameters:

**--target-edge-zone-encryption**

Space-separated list of customer managed keys for encrypting the OS and data disks in the gallery artifact for each region. Format for each edge zone: \<edge zone\>, \<os_des\>,\<lun1\>,\<lun1_des\>,\<lun2\>,\<lun2_des\>. Use "null" as a placeholder. This should add the encryption information to the edge zone (a targetExtendedLocation in the spec)

**--target-edge-zones**

Space-separated list of regions, edge zones, replica counts, and storage types. Use \<region\>=\<edge zone\>[=\<replica count\>][=\<storage account type\>] to optionally set the replica count and/or storage account type for each region. If a replica count is not specified, the default replica count will be used. If a storage account type is not specified, the default storage account type will be used.

_This information should be used to build the targetExtendedLocations array of GalleryImageTargetLocations which are used in a GalleryImageVersion or GalleryImageVersionUpdate included in the Swagger/OpenAPI link._

Note: the underlying ARM property for an EdgeZone is called “extended locations”, and is intended to cover several types of extended locations including EdgeZone, among others. We do not want to directly reflect this into the cmdlets (by say, having a --target-extended-location parameter). 

Add optional parameters **--target-edge-zone-encryption** and **--target-edge-zones** to the following Az.Compute cmdlets:

```
az sig image-version create
az sig image-version update
```

Additionally, we need the following operation needs to be updated to show information similar to targetRegions for EdgeZones (targetExtendedLocations):

`az sig image-version show`

**Minimum API Version Required**

2022-01-03

**Swagger\OpenAPI Link**

[azure-rest-api-specs/gallery.json at fce14f3880315a422a59851fa5ffda4aba4f17e4 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/blob/fce14f3880315a422a59851fa5ffda4aba4f17e4/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-01-03/gallery.json)

[Link to Example from Swagger\OpenAPI](https://github.com/Azure/azure-rest-api-specs/blob/fce14f3880315a422a59851fa5ffda4aba4f17e4/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-01-03/examples/galleryExamples/GalleryImageVersion_Create_WithTargetExtendedLocations.json)

**Target Date**

September 2022 (**Private**)

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by yanzhudd** [comment]
Hello @MSFT-BrianEddy, does the target date (September 2022 (Private)) mentioned above mean that we only need to provide private package built through the edge in September?

**Comment by MSFT-BrianEddy** [comment]
That's right. The goal right now is to unblock some other work. We want to make a private package for now before we release it to 3p customers.

**Comment by yanzhudd** [comment]
Hello @MSFT-BrianEddy, when we develop this feature, we met some questions and raised them in the mail. Please check.

**Comment by yanzhudd** [comment]
Hi @MSFT-BrianEddy 
It seems that the values `attdallas1` and `microsoftlosangeles1` of the `--target-edge-zones` parameter are invalid now. Could you please share the available values for the parameter, so that we could test it from Azure CLI side?
