### ISSUE TITLE
az datafactory pipeline update modifying activities JSON

### ISSUE THREAD

**Issue by PrestonGiorgianni** [Azure/azure-cli#23744]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az datafactory pipeline update

**Describe the bug**

This snippet of my config is being changed when updating a pipeline or creating a new one.
```json
"sink": {
  "type": "AzurePostgreSQLSink",
  "writeBatchSize": 10000,
  "writeBatchTimeout": "2:00:00",
  "preCopyScript": "delete from ${table_name}",
  "writeMethod": "CopyCommand"
}
```
--->
```Json
"sink": {
  "additionalProperties": null,
  "disableMetricsCollection": null,
  "maxConcurrentConnections": null,
  "sinkRetryCount": null,
  "sinkRetryWait": null,
  "type": "CopySink",
  "writeBatchSize": 10000,
  "writeBatchTimeout": "02:00:00"
}
```

then when I log into the data factory, it has no sink block at all on the copy command.

**To Reproduce**

- Run `az datafactory pipeline update` with an activities block for a copy with AzurePostgreSQLSink
- Look at the output and see it was changed to "CopySink"
- Look in the Data Factory creator UI, pipeline, JSON view has no sink block

**Expected behavior**

The sink block shall not be modified and shall be present in the Data Factory UI

**Environment summary**

- installed via brew
- Macos 12.5.1
  - Type Bash 
- versions 
<img width="294" alt="Screen Shot 2022-08-31 at 2 03 48 PM" src="https://user-images.githubusercontent.com/61525781/187781859-376f2a07-ea52-4e9d-8cec-657671f86d5d.png">

**Additional context**

This issue was first Identified while trying to use terraform to create a Data Pipeline. After digging deeper and running the az cli command manually I noticed that it is the az cli has the underlying issue.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PrestonGiorgianni** [comment]
@evelyn-ys Are there any updates on this issue?

**Comment by PrestonGiorgianni** [comment]
After opening a support case through azure I got the following response

```text
 please change "AzurePostgreSQLSink" to "AzurePostgreSqlSink" and the issue will be solved. The root cause is that Az CLI has limitation on case matching.
 ```
 
 Following the advise fixed the issue, however it would be nice in the future if the Azure GUI and the CLI could agree on the casing of terms
