### ISSUE TITLE
Can we access resources from multiple subscriptions using azure cli?

### ISSUE THREAD

**Issue by ranjeetkpGit** [Azure/azure-cli#23743]
Hi, 
I am running following azure cli command on a service connection (Azure Devops).
az containerapp up --name 'subscription1container'
                                    --image 'subscription2image'
                                    
It works fine when all the resources belong to same subscription. (Default behavior)
Our requirement is to access image from different subscription. Is there any way we can write cross/mix subscriptions
cli commands which can access resources from other subscriptions too?

**Comment by ynden** [comment]
Hey @ranjeetkpGit,

You can use the `--subscription NAME_OR_ID` global parameter. In your case, it would something like:
```
az containerapp up \
--name 'subscription1container' \
--image 'subscription2image' \
--subscription NAME_OR_ID
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@ranjeetkpGit Did you look into @ynden's suggestion ?

**Comment by ranjeetkpGit** [comment]
> @ranjeetkpGit Did you look into @ynden's suggestion ?

Yes but no success.

**Comment by ynden** [comment]
@ranjeetkpGit, what kind of error do you get?
