### ISSUE TITLE
Error loading command module 'rdbms': cannot import name 'case_insensitive_dict' from 'azure.core.utils'

### ISSUE THREAD

**Issue by arif9799** [Azure/azure-cli#23741]
Hi,
I was working on components in azure ml, building them in azure notebooks section and deploying those components from the Azure CLI on the terminal of directory containing code for component in Azure notebooks, to be used in frontend UI on designer tab.
I was successful in creating multiple of those until I ran into error shown below in the snapshot.
It lists out three errors at one time. And I have literally no clue as to what caused this to happen.

![image](https://user-images.githubusercontent.com/93501171/187754702-f2bcc255-d3c0-43da-97ed-50c9cc4ac85e.png)

But I can tell when things started going south. On creating the 4th or 5th component in which I was trying to install packages from azure ml and azure ml core, after that none of the components were created neither existing ones could be modified. 
If anyone's come across same issue please share how did you come around a solution to this problem.
LMK if more indepth code is needed to understand the problem

**Comment by yonzhan** [comment]
route to CXP team

**Comment by arif9799** [comment]
Hi 
Thanks for the response 
I was able to resolve the issue by uninstalling the azure libraries and then installing it back again, then it worked like a charm

just run these few commands:

**_python -m pip uninstall azure-common
python -m pip uninstall azure-storage
python -m pip uninstall azure-nspkg
python -m pip uninstall azure-storage-blob_**

and then reinstall package:

**_python -m pip install azure-storage-blob_**
