### ISSUE TITLE
login to azure through cli as in the tutorial does not work

### ISSUE THREAD

**Issue by MonivaPython** [Azure/azure-cli#23750]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
Please run 'az login' to setup account.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --runtime {} --sku {} --logs`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0
```

**Comment by RakeshMohanMSFT** [comment]
@MonivaPython `az login` is a prerequisite that you must run before any commands, to set the context to your subscription and ensure you have access to those resources. 

More information here https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli

**Comment by yonzhan** [comment]
route to CXP team
