### ISSUE TITLE
Support for EnableUDPLogOptimization parameter on Azure Firewall

### ISSUE THREAD

**Issue by jashwanth** [Azure/azure-cli#23758]
Resource Provider
Network (NRP)

Description of Feature or Work Requested
Need to add a new parameter named EnableUDPLogOptimization to the base command of creating the Firewall.
az network firewall create -g MyResourceGroup -n MyFirewall --enable-udp-log-optimization true

Only parameter needed is:

enable-udp-log-optimization
Default value is false

No NRP/Swagger change needed

**Comment by yonzhan** [comment]
@necusjz for awareness
