### ISSUE TITLE
The --display-name option does not match the complete name

### ISSUE THREAD

**Issue by Mu4all** [Azure/azure-cli#23752]
You have two app registrations called 'AppReg01' and 'AppReg011'

If you do `az ad list --display-name "AppReg01"` you will get both of them. This is either a bug, or undocumented behaviour.
As a workaround, the `--filter "displayname eq 'AppReg01'"` option works as expected.

**Comment by RakeshMohanMSFT** [comment]
@Mu4all Thank you for reaching out, we are looking into it.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by RakeshMohanMSFT** [comment]
@Mu4all Its a "startswith" search, therefore the result is expected. We will update the document to be more clear.

**Comment by Mu4all** [comment]
Thanks for the research guys!
