### ISSUE TITLE
az vm create references a URL that doesn't exist

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#2375]
The help document for az vm create refers to 

> Create an Ubuntu Linux VM and provide a cloud-init script (https://docs.microsoft.com/azure
    /virtual-machines/virtual-machines-linux-using-cloud-init).

But [https://docs.microsoft.com/azure
    /virtual-machines/virtual-machines-linux-using-cloud-init](https://docs.microsoft.com/azure
    /virtual-machines/virtual-machines-linux-using-cloud-init) does not exist.

**Comment by devigned** [comment]
I just cut and pasted https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-using-cloud-init into a browser and it seems to work. Am I missing something?

**Comment by binderjoe** [comment]
Indeed you are correct--sorry about that.  Either I pasted it incorrectly or the link was fixed.  Thanks for checking.
