### ISSUE TITLE
az resource show (Microsoft.Cache/Redis) bad request - "You must include the api-version parameter in your URI query segment"

### ISSUE THREAD

**Issue by HatakuSec** [Azure/azure-cli#23755]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
` az resource show --ids /subscriptions/<subscription/resourceGroups/<resource group>/providers/Microsoft.Cache/Redis/<redis name>` - **Fails**

` az resource show --ids /subscriptions/<subscription/resourceGroups/<resource group>/providers/Microsoft.Cache/Redis/<redis name> --api-version 2022-06-01` - **Fails**

` az resource show --ids /subscriptions/<subscription/resourceGroups/<resource group>/providers/Microsoft.Cache/Redis/<redis name> --api-version 2022-05-01` - **Success**

**Describe the bug**
By default if you do not specify an api-version in the az resource show command, it will default to the latest api version which is intended. 
However, without specifying an api-version, it currently uses the API version "2022-06-01" which fails due to bad request:
`{"Message":"Bad Request. You must include the api-version parameter in your URI query segment."}`

If this parameter is required, the request should automatically include the parameter specify the latest API version in the request

**To Reproduce**
Run the above commands against a Azure redis cache

**Expected behavior**
The api-version parameter should be included in the request without having to specify 

**Environment summary**
Not sure if it's related, but this occurred after create a private endpoint for the redis cache. After deleting the private endpoint, it still occurs (Only when using the latest API version)

**Additional context**

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
> az resource show --ids /subscriptions/<subscription/resourceGroups/<resource group>/providers/Microsoft.Cache/Redis/<redis name> - Fails
az resource show --ids /subscriptions/<subscription/resourceGroups/<resource group>/providers/Microsoft.Cache/Redis/<redis name> --api-version 2022-06-01 - Fails

Sorry, I can't reproduce this issue. Could you send me the debug log *(add `--debug` parameter)* by email? My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by HatakuSec** [comment]
Strangely, this is now working fine after trying this morning. I guess we can close this for now
