### ISSUE TITLE
az vm create --generate-ssh-keys documentation should specify where keys are generated and what they are named.

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#2376]
The --generate-ssh-keys parameter is useful, but it isn't clear what key files it creates or where it puts them.  The docs should describe the behavior.

**Comment by VishalVMishra** [comment]
You can find the ssh keys (both public and private) under /etc/ssh, and yes the documentation should ideally mention the path of generated keys, so no one should have to search for it.
