### ISSUE TITLE
can login with with az login even though I have active subscription

### ISSUE THREAD

**Issue by toki0709** [Azure/azure-cli#23768]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
No subscriptions found for tokitazwar@hotmail.com.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.38.0 *
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by RakeshMohanMSFT** [comment]
@toki0709 Please check if this action plan helps https://docs.microsoft.com/en-us/answers/questions/738782/no-subscription-found-for-function-during-azure-cl.html

**Comment by albertocavalcante** [comment]
I just faced this issue using `az 2.62.0` which uses Web Account Manager (WAM) for authentication but had to switch back to browser-based authentication in order for it to work. 

```sh
az account clear
az config set core.enable_broker_on_windows=false
az login
```

Documentation: https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli-interactively#sign-in-with-web-account-manager-wam-on-windows
