### ISSUE TITLE
Azure - problem connecting aks to acr

### ISSUE THREAD

**Issue by TalissaDreossi** [Azure/azure-cli#23771]
## Bug description
I want to deploy some pods on my aks, which will pull image from my acr.
I had already attached my acr to my aks but inside aks I cannot pull the images 

**Command Name**
`az aks check-acr`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'serverVersion'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1621, in aks_check_acr
KeyError: 'serverVersion'

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@TalissaDreossi Thank you for reaching out to us, can you please share your environment details? az --version. If you are not using the latest Az CLI [2.39.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli), please upgrade to it and retry the operation.

**Comment by TalissaDreossi** [comment]
that's the output of az --version 

```
azure-cli                         2.39.0

core                              2.39.0
telemetry                          1.0.6 *

Extensions:
account                            0.2.3

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\TalissaDreossi\.azure\cliextensions'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 1 updates available.

```
do you need any other information?

**Comment by TalissaDreossi** [comment]
I have tryed now to run: `az aks check-acr -g sviluppo -n devaks --acr svacr.azurecr.io`
the output is: 
```
Merged "devaks" as current context in C:\Users\TALISS~1\AppData\Local\Temp\tmp0m0ht6u0
Unable to use a TTY - container canipull-5796523e-b928-4ff6-b574-b54b42ed2e1a did not allocate one
[2022-09-05T07:09:43Z] Checking host name resolution (svacr.azurecr.io): SUCCEEDED
[2022-09-05T07:09:43Z] Canonical name for ACR (svacr.azurecr.io): ***.cloudapp.azure.com.
[2022-09-05T07:09:43Z] ACR location: westeurope
[2022-09-05T07:09:43Z] Checking managed identity...
[2022-09-05T07:09:43Z] Kubelet managed identity client ID: ****
[2022-09-05T07:09:43Z] Validating managed identity existance: SUCCEEDED
[2022-09-05T07:09:43Z] Validating image pull permission: SUCCEEDED
[2022-09-05T07:09:43Z]
Your cluster can pull images from svacr.azurecr.io!
```

but it still has the same problem when pulling image in pod: 
```
Failed to pull image "svacr.azurecr.io/prova:1": [rpc error: code = Unknown
  desc = failed to pull and unpack image "svacr.azurecr.io/prova:1": failed to
  copy: httpReadSeeker: failed open: failed to do request: Get
  "https://weumanaged122.blob.core.windows.net/13a2e27dc73e4e4c8b018f39e89e2137-bikbp9lp9c//docker/registry/v2/blobs/sha256/96/963f543139050cf70a4b30b7b829a5ab45afb1579a81eb5b24e9b2ca3baf9289/data?se=2022-09-05T07%3A36%3A38Z&sig=ZmJWahZVQSR8f7WPh%2BC7rQx32B%2BbGGxZ%2FkLuFoItjH4%3D&sp=r&spr=https&sr=b&sv=2016-05-31&regid=13a2e27dc73e4e4c8b018f39e89e2137":
  dial tcp 52.239.213.100:443: i/o timeout, rpc error: code = Unknown desc =
  failed to pull and unpack image "svacr.azurecr.io/prova:1": failed to resolve
  reference "svacr.azurecr.io/prova:1": failed to authorize: failed to fetch
  anonymous token: unexpected status: 401 Unauthorized]
```

**Comment by RakeshMohanMSFT** [comment]
@TalissaDreossi Can you check your storage connection please? try accessing it externally and see if that works.

Also please edit your previous comment and retract any credential information in it.

**Comment by TalissaDreossi** [comment]
> @TalissaDreossi Can you check your storage connection please, the token seems to be incorrect? try accessing it externally and see if that works.
> 
do you mean by pulling the image locally? It works  

> Also please edit your previous comment and retract any credential information in it.
> 
> Please refer: https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#service-sas-example
> 
> Sample url: https://myaccount.blob.core.windows.net/sascontainer/sasblob.txt?sv=2019-02-02&st=2019-04-29T22%3A18%3A26Z&se=2019-04- [30T02%3A23%3A26Z&sr=b&sp=rw&sip=168.1.5.60-168.1.5.70&spr=https&sig=Z%2FRHIX5Xcg0Mq2rqI3OlWTjEg2tYkboXr1P9ZUXDtkk%3D](https://myaccount.blob.core.windows.net/sascontainer/sasblob.txt?sv=2019-02-02&st=2019-04-29T22%3A18%3A26Z&se=2019-04-30T02%3A23%3A26Z&sr=b&sp=rw&sip=168.1.5.60-168.1.5.70&spr=https&sig=Z%2FRHIX5Xcg0Mq2rqI3OlWTjEg2tYkboXr1P9ZUXDtkk%3D)


ops sorry, I edited it, thanks

**Comment by RakeshMohanMSFT** [comment]
@TalissaDreossi Please open a support ticket, it is difficult to troubleshoot this issue over git forum, also its not specific to cli commands. Therefore open a support ticket a dedicated engineer will help you resolve this issue.

**Comment by TalissaDreossi** [comment]
@RakeshMohanMSFT thanks for your help!
In the end I decided to recreate everything new and now it works
