### ISSUE TITLE
Getting all version ids for a single blob using CLI

### ISSUE THREAD

**Issue by zaalion** [Azure/azure-cli#23777]
[Enter feedback here]
Hi, How can I get a list of all version IDs for a single blob object. The _blob show_ command only returns the latest version id.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/blob.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/blob.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
Hi @zaalion, You can use `az storage blob list -c $containerName --account-name $accountName --prefix $blobName --include v` to get all versions of a specific blob
