### ISSUE TITLE
 az storage container generate-sas command not working 

### ISSUE THREAD

**Issue by piojagcodes** [Azure/azure-cli#23778]
## Describe the bug

**Command Name**
`az storage container generate-sas`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'account_key'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 410, in new_handler
    first(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/__init__.py", line 409, in new_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 869, in generate_container_shared_access_signature
    account_key = client.credential.account_key
AttributeError: 'NoneType' object has no attribute 'account_key'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container generate-sas --name {} --policy-name {} --account-name {}`

## Environment Summary
```
Linux-5.15.0-47-generic-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.39.0
```

**Comment by piojagcodes** [comment]
az storage container generate-sas --name piotrjzjazd1 --policy-name App1 --account-name pj@akademiacloudops.onmicrosoft.com 

I used that command and something like that popped up

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
The dependency `azure-multiapi-storage` package is not installed properly. So that we get `None` for enum definition from SDK.

Please make sure you have installed CLI successfully following https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script

**Comment by evelyn-ys** [comment]
Please make sure the storage account `pj@akademiacloudops.onmicrosoft.com` does exist.

**Comment by piojagcodes** [comment]
I cant because i declined in participating for Lufthansa Database Engineer
longer. Health issues mostly.

czw., 8 wrz 2022, 05:39 użytkownik msftbot[bot] ***@***.***>
napisał:

**Comment by piojagcodes** [comment]
I hope mine commit wasn't misleading. I noticed such error during
realisation tasks on Lufthansa Database engineer. I can send more data like
from commands like hostnamectl so you will figure out if this might be
larger later.I worked on VMWare instances

Thank you for patience while reading this mail

Have a nice day
Peter Jagiello

sob., 3 wrz 2022, 13:52 użytkownik Yong Zhang ***@***.***>
napisał:

**Comment by navba-MSFT** [comment]
> az storage container generate-sas --name piotrjzjazd1 --policy-name App1 --account-name [pj@akademiacloudops.onmicrosoft.com](mailto:pj@akademiacloudops.onmicrosoft.com)
> 
> I used that command and something like that popped up

@piojagcodes  I am unable to replicate the issue with the above command you had shared. Sharing the output here if that helps:

>az storage container generate-sas --name piotrjzjazd1 --policy-name App1 --account-name pj@akademiacloudops.onmicrosoft.com

**Output:**
Storage account 'pj@akademiacloudops.onmicrosoft.com' not found.

Also note that, **pj@akademiacloudops.onmicrosoft.com** cannot be a valid storage account name. Because the Storage Account name must be 3 to 24 characters long, and can contain only lowercase letters and numbers.

**Comment by navba-MSFT** [comment]
@piojagcodes I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by piojagcodes** [comment]
Welcome

User which was managing pool of participants in Lufthansa database engineer
pool simply removed me because I resigned.
The account from what i heard was deprovisioned and space on which mine
profile was created also got removed from Identity and Access Management
dashboard.

Hope this helps and have a good day to you Sir

Jagiello Piotr


wt., 25 paź 2022 o 05:57 navba-MSFT ***@***.***> napisał(a):

**Comment by navba-MSFT** [comment]
@piojagcodes 

> Welcome User which was managing pool of participants in Lufthansa database engineer pool simply removed me because I resigned. The account from what i heard was deprovisioned and space on which mine profile was created also got removed from Identity and Access Management dashboard. Hope this helps and have a good day to you Sir Jagiello Piotr 

Unfortunately this information may not help me to debug this issue further. If you have any technical details about how to reproduce this issue ? and `--debug `output please feel free to get back to us. We would be happy to help.

**Comment by navba-MSFT** [comment]
@piojagcodes As mentioned above, Please share the technical details about how to reproduce this issue ? and` --debug `output and feel free to reopen this thread. We would be happy to help.

**Comment by kohtala** [comment]
@navba-MSFT , I get this error on `az storage container generate-sas` with an expired login. The error does not happen after a new `az login`.

The traceback is preceded by

    Skip querying account key due to failure: AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2025-04-02T12:19:09.7212590Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2025-04-03T06:14:30.0000000Z'. Trace ID: 87603004-562f-4c27-bdcc-8638be570700 Correlation ID: abeaa7fd-a27b-4bcf-b271-63acdd68d795 Timestamp: 2025-04-03 06:27:28Z

```
$ az --version
azure-cli                         2.71.0

core                              2.71.0
telemetry                          1.1.0

Dependencies:
msal                            1.31.2b1
azure-mgmt-resource               23.1.1

Python location '/opt/az/bin/python3'
Config directory '/home/kohtala/.azure'
Extensions directory '/home/kohtala/.azure/cliextensions'

Python (Linux) 3.12.8 (main, Mar 25 2025, 10:54:53) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```
