### ISSUE TITLE
az role assignment: ERROR: A hash conflict was encountered for the role Assignment ID. Please use a new Guid.

### ISSUE THREAD

**Issue by tshaiman** [Azure/azure-cli#23770]
## Describe the bug
when running az role assignment create , a user may hit hash conflict which he cannot control , only re-run the command.
this is a source of frustration and issue that exists for many years so far.
since there is no API to allow users to pass a GUID or any other mean of uniqueness I believe this is a bug , not feature request.
Also in the Error description , users are asked to "use a new Guid , where in fact there is no option to do so.

**Command Name**
`az role assignment create`

**Errors:**
```
ERROR: A hash conflict was encountered for the role Assignment ID. Please use a new Guid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- run az role assignment many times and you will hit the issue
-  issue is already reported since 2020 and has not been addressed since 
 https://github.com/Azure/azure-cli/issues/13368

## Expected Behavior
- either provide API so users can pass their own Guid
- fix the issue on Az CLI server side and perform retry mechanism if needed
-  fix the error description as its misleading
## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.4
Installer: DEB

azure-cli 2.37.0 *

Extensions:
aks-preview 0.5.91
azure-devops 0.25.0
containerapp 0.3.7

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
There is no fancy logic in Azure CLI to create role assignment name - simply a GUID created with Python's built-in [`uuid.uuid4()`](https://docs.python.org/3/library/uuid.html#uuid.uuid4) function:

https://github.com/Azure/azure-cli/blob/98f7865402569ec9a6ae05ccdd0d27d5ea20927c/src/azure-cli/azure/cli/command_modules/role/custom.py#L1563-L1564

I tried to hardcode assignment name to a GUID `ccfed017-7179-4c62-b6b5-236377f1e9b3` when creating role assignments:

https://github.com/Azure/azure-cli/blob/98f7865402569ec9a6ae05ccdd0d27d5ea20927c/src/azure-cli/azure/cli/command_modules/role/custom.py#L201-L203

Then if I run `az role assignment create` multiple times, it doesn't give any error:

```
> az role assignment create --assignee-object-id 9b25c27f-0eb3-43a3-83e4-a513fc3ef7ce --assignee-principal-type ServicePrincipal --role reader --scope /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/azure-cli-test-rg --debug
...
msrest.http_logger: Request URL: 'https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/azure-cli-test-rg/providers/Microsoft.Authorization/roleAssignments/ccfed017-7179-4c62-b6b5-236377f1e9b3?api-version=2020-04-01-preview'
msrest.http_logger: Request method: 'PUT'
msrest.http_logger: Request headers:
msrest.http_logger:     'Accept': 'application/json'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'accept-language': 'en-US'
msrest.http_logger:     'Content-Length': '270'
msrest.http_logger:     'User-Agent': 'python/3.10.7 (Windows-10-10.0.22621-SP0) msrest/0.7.1 msrest_azure/0.6.4 azure-mgmt-authorization/0.61.0 Azure-SDK-For-Python AZURECLI/2.41.0 (PIP)'
msrest.http_logger: Request body:
msrest.http_logger: {"properties": {"roleDefinitionId": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7", "principalId": "9b25c27f-0eb3-43a3-83e4-a513fc3ef7ce", "principalType": "ServicePrincipal"}}
...
msrest.http_logger: Response status: 201
msrest.http_logger: Response headers:
msrest.http_logger:     'Cache-Control': 'no-cache'
msrest.http_logger:     'Pragma': 'no-cache'
msrest.http_logger:     'Content-Length': '889'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'Expires': '-1'
msrest.http_logger:     'x-ms-request-id': 'a34b2413-44b9-49b8-820d-fd5a48212424'
msrest.http_logger:     'X-Content-Type-Options': 'nosniff'
msrest.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger:     'Set-Cookie': 'x-ms-gateway-slice=Production; path=/; secure; samesite=none; httponly'
msrest.http_logger:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger:     'x-ms-correlation-request-id': 'd1aabcbb-cf66-4591-87cf-b12486bcc5c8'
msrest.http_logger:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20221013T112447Z:d1aabcbb-cf66-4591-87cf-b12486bcc5c8'
msrest.http_logger:     'Date': 'Thu, 13 Oct 2022 11:24:47 GMT'
msrest.http_logger: Response content:
msrest.http_logger: {"properties":{"roleDefinitionId":"/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7","principalId":"9b25c27f-0eb3-43a3-83e4-a513fc3ef7ce","principalType":"ServicePrincipal","scope":"/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/azure-cli-test-rg","condition":null,"conditionVersion":null,"createdOn":"2022-10-13T11:24:44.0399539Z","updatedOn":"2022-10-13T11:24:44.3993881Z","createdBy":null,"updatedBy":"0d504196-1423-4569-9a6e-15149656f0ee","delegatedManagedIdentityResourceId":null,"description":null},"id":"/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/azure-cli-test-rg/providers/Microsoft.Authorization/roleAssignments/ccfed017-7179-4c62-b6b5-236377f1e9b3","type":"Microsoft.Authorization/roleAssignments","name":"ccfed017-7179-4c62-b6b5-236377f1e9b3"}
```

This means the [Role Assignments - Create](https://learn.microsoft.com/en-us/rest/api/authorization/role-assignments/create?tabs=HTTP) API is idempotent.

It seems to be ARM RBAC service issue. Let's discuss internally.

**Comment by tshaiman** [comment]
1. You will not be able to reproduce this by running it many times as GUID conflict are hard to reproduce.
The bug I've opened is around the fact that on one hand the error exists and happens quite often to teams which are running many workload, while the error message provided is wrong. 
2. The error message claims "you should call the command with new GUID" while in fact we don't have ANY API to pass the GUID -> and that is the real bug here.
3. If for example we could have passed a GUID , we would always pass the same GUID for the same role assignment , hence avoiding this conflict 
4. This is actually how ARM is handling this - they let users to pick either a name or a constant GUID/String to always use the same one for the same role assignment. -> that is the ask here .

**Comment by jiasli** [comment]
https://github.com/Azure/azure-cli/pull/24324 worked around this issue by introducing `--name` in `az role assignment create`. You can now provide your own GUID as `--name` to have a predictable role assignment created and bypass this service issue.

**Comment by tshaiman** [comment]
@jiasli  great ! thanks a lot !
