### ISSUE TITLE
Change needed in az restore-point create to support consistencyMode parameter

### ISSUE THREAD

**Issue by dikethir** [Azure/azure-cli#23785]
### Related command

az restore-point create

### Resource Provider

Microsoft.Compute

### Description of Feature or Work Requested

Currently restore points are app consistent by default, however we are introducing an option for customers to create crash consistent restore points by setting the new optional property "consistencyMode" to "CrashConsistent". 

This is an optional property that the customer will set if they want crash consistent restore points instead of the default app consistent restore points

### Minimum API Version Required

2021-07-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-03-01/restorePoint.json

SDK: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/Models/RestorePoint.cs

### Request Example

az restore-point create --exclude-disks "/subscriptions/{subscription-id}/resourceGroups/myResour               ceGroup/providers/Microsoft.Compute/disks/disk123" --resource-group "myResourceGroup" --collection-name "rpcName" --name "rpName" --consistency-mode "CrashConsistent"

### Target Date

2022-10-10

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness
