### ISSUE TITLE
az storage blob upload not overwriting / issue with entity 

### ISSUE THREAD

**Issue by Smoogles** [Azure/azure-cli#23783]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az storage blob upload -f <path-to-file> --account-name <storage-account> -c dev -n <path-to-upload-in-container> --overwrite true --% --sas-token "sp=racwdlmeop&st=2022-09-05T03:56:59Z&se=2022-10-01T11:56:59Z&spr=https&sv=2021-06-08&sr=c&sig=[redacted]"`

**Describe the bug** and **To Reproduce**
My goal has been to dynamically create a directory and upload a file to it. The name of directory is set using pscore with `${date} = Get-Date -Format "yyyy/MM/dd"` so that the directory of my file and path to directory in blob would be 2022/09/05/file.txt. 
`az config set extension.use_dynamic_install=yes_without_prompt`
So I can use storage-preview as it asks for it. 
`az storage fs directory create -n dev/${date} -f dev --account-name $(StorageAccount) --% --sas-token "$(SASToken)"`
The --% as the SAS token in ps thinks it a command otherwise. 
Then do the upload command gives:
```
Argument '--overwrite' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The requested operation is not allowed in the current state of the entity.
RequestId:7df8fed3-901e-0024-7fdc-c04548000000
Time:2022-09-05T04:01:03.3425146Z
ErrorCode:OperationNotAllowedInCurrentState
If you want to overwrite the existing one, please add --overwrite in your command.
```

**Expected behavior**
It will say you need to overwrite yet the overwrite is in it already and the permissions for the SAS token are all permissions and the date is set to at least a month away so will not expire. 

**Environment summary**

```
azure-cli                         2.39.0

core                              2.39.0
telemetry                          1.0.6 *

Extensions:
azure-devops                      0.25.0
storage-preview                    0.8.3

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1
```
These are my local versions but ideally I'm aiming to use azure-pipeline for this. 

**Additional context**
I feel like it's an overwrite issue but could be SAS issue although I don't think I'm generating it wrong. I've chosen all permissions multiple times and made sure date won't expire. I also have Storage blob owner and contributor to the storage account.
In Azure-pipeline I have to use ubuntu vm for this so either bash or pscore I can use for this but unsure.

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
Need storage service to check reason for `OperationNotAllowedInCurrentState`

**Comment by navba-MSFT** [comment]
@Smoogles Thanks for reaching out to us and reporting this issue. If you are able to reproduce this issue, Could you please send the **RequestId** from the error response of most recent issue occurrence ? This will help us in looking at the backend logs for the cause of the issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Smoogles I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please share the RequestId from the error response of most recent issue occurrence. Awaiting your reply.

**Comment by Smoogles** [comment]
Sorry been busy. Can I get back to you start of this week coming? I'll try
again when at work and will send it through.

Thanks

**Comment by navba-MSFT** [comment]
@Smoogles Thanks for getting back. We shall wait for the updates from your end.

**Comment by navba-MSFT** [comment]
@Smoogles The action is currently pending on you to share the RequestId from the error response of most recent issue occurrence. Once you have these details, please feel free to reopen this issue, we would be happy to help.

**Comment by Smoogles** [comment]
> @Smoogles The action is currently pending on you to share the RequestId from the error response of most recent issue occurrence. Once you have these details, please feel free to reopen this issue, we would be happy to help.

Apologies for the delay:
![image](https://user-images.githubusercontent.com/50223826/198938305-1ff0b283-e75d-4fef-9a72-c5dd335fb401.png)
RequestId: ecb734b2-b01e-002d-1aea-ec6d97000000
Thanks.

**Comment by navba-MSFT** [comment]
@Smoogles I had a quick look at the backend logs. The failure seems to be for the path: /dev/Raw/devOps/2022/10/31

The failure is due to a conflict issue with the **31** file. Considering your storage account **onyXXXXXke** is a Data Lake Storage Account. Could you please confirm if **31** is a file or a Directory ? 

If possible, could you try to **delete** and **recreate** that complete above path using [this fs command](https://learn.microsoft.com/en-us/cli/azure/storage/fs/directory?view=azure-cli-latest#az-storage-fs-directory-create) ? 

Also since this is a data lake storage account, My recommendation is to use could you use [this](https://learn.microsoft.com/en-us/cli/azure/storage/fs/directory?view=azure-cli-latest#az-storage-fs-directory-create) command instead of `az storage blob upload ` ? Hope this helps.

**Comment by Smoogles** [comment]
Hi, I checked 31 and it says it is a directory and I had used `az storage fs directory create` to create it. 
I used the `az storage fs directory upload` to upload the file and it worked. Unsure if it was because I added another slash at the end of the date format "yyyy/mm/dd/" instead of "yyyy/mm/dd" or the change to a different upload command. But given my concern in this issue was the `az storage blob upload` command itself, I'm happy to have found an alternate one that can overwrite the file as well. Not sure if you would like more information regarding testing the `az storage blob upload` command but otherwise the issue is resolved for me. 
Thanks.

**Comment by navba-MSFT** [comment]
@Smoogles Thanks for getting back. I am glad that its working now. It is better to use the `fs` CLI commands considering its a ADLS Gen 2 storage account. Our backend logs didn't complain about the / though. Though blob and dfs endpoiint should both be interoperable, there is a difference in either HNS file system semantics (ADLS) or flat structure (Standard Blob Storage). If the same issue resurfaces in future, feel free to reopen this thread. We would be happy to help.
