### ISSUE TITLE
ERROR: Please run 'az login' to setup account.

### ISSUE THREAD

**Issue by SamaRamya** [Azure/azure-cli#23791]
I am trying to deploy the **Azure Data Factory** Using **GitHub Actions.**
So in my Github Actions i have created one workflow file where i have several jobs required for my deployment.

**My 1st job** in the workflow file is **Azure-Login** where im using the below command for login:
az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_SECRET_VALUE --tenant $AZURE_TENANT_ID 
And in this job im using one container where it has azure cli latest version installed in it to run the above command in the container. Iam able to login here succesfully.

**The Problem Arrives Here:**
**My 2nd job** in the workflow file is to **deploy the arm template** to the target environment.
When i run the workflow my 2nd job is throwing me the below error to login.
**ERROR: Please run 'az login' to setup account.**

Since  i have created a separate job for login,i dont want to login again in my 2nd job and that makes my 1st job of no use.

Can you please suggest me how to make my 2nd job run succesfully without using azure login again.

**Comment by yonzhan** [comment]
@jiasli for awareness
