### ISSUE TITLE
"az aks command invoke" doesn't propagate exit codes

### ISSUE THREAD

**Issue by slnowak** [Azure/azure-cli#23808]
**Related command**

```az aks command invoke```

**Describe the bug**

We're using `az aks command invoke` in our CICD pipelines for deployment purposes, however it seems like it does not propagate the exit code of the underlying command. Thus, we've observed some false positive deployments - our pipeline reported success even though the actual command failed. 

**To Reproduce**

Run the following code:
```
➜  ~ az aks command invoke --resource-group your-rg --name your-cluster --command "kubectl get non-existing-resource"
command started at 2022-09-07 14:35:03+00:00, finished at 2022-09-07 14:35:06+00:00 with exitcode=1
error: the server doesn't have a resource type "non-existing-resource"

➜  ~ echo $?
0
```

**Expected behavior**

It should propagate the actual return code, in this case:
```
➜  ~ kubectl get non-existing-resource
W0907 16:36:05.714438   65949 azure.go:92] WARNING: the azure auth plugin is deprecated in v1.22+, unavailable in v1.26+; use https://github.com/Azure/kubelogin instead.
To learn more, consult https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
error: the server doesn't have a resource type "non-existing-resource"
➜  ~ echo $?
1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@slnowak Thanks for the feedback! We will review and update accordingly.

**Comment by PramodValavala-MSFT** [comment]
@slnowak A workaround in the meantime is to pass `-o json`  to get the full output which includes the logs and exit code, which can be parsed using something like `jq` or even just pass `-o json --query exitCode` if you are interested in the logs. Something like this could get `$?` to have the right value

```sh
bash -c "exit `az aks command invoke -g <rg> -n <name> --command "kubectl get no-resource" --query exitCode -o json`"
```

**Comment by jvitor83** [comment]
Why not having an argument to allow the underlying command exit code to be used?
Something like: `--exit-code`
