### ISSUE TITLE
absence of az command to set public_network_access_enabled missing for azure synapse

### ISSUE THREAD

**Issue by onenessboy** [Azure/azure-cli#23803]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az synapse workspace update --name synapsews --resource-group rgname --public_network_access_enabled true

**Describe the bug**
didnt find option to enable / disbale public access to synapse workspace via az workspace update command

**To Reproduce**
az synapse workspace update --name synapsews --resource-group rgname --public_network_access_enabled true

**Expected behavior**
synapse workspace networking property should change

**Environment summary**
Linux

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by onenessboy** [comment]
Can some one help here please @yonzhan

**Comment by jsntcy** [comment]
@kevinzz6, please help take a look.

**Comment by kevinzz6** [comment]
@onenessboy  Hi, thanks for your issue. We will add a parameter to support this feature.

**Comment by Prasanth-Sundarrajan** [comment]
> @onenessboy Hi, thanks for your issue. We will add a parameter to support this feature.

Thanks for reply @kevinzz6 is there any ETA for this. the reason being we need to use this for many account as part of cicd process...thank you in advance

**Comment by navba-MSFT** [comment]
@onenessboy @Prasanth-Sundarrajan Please _modify_ and _run_ the below command. This should help you in setting the Public Network access for your synapse workspace.

The below command helps you to **Enable** the publicNetworkAccess:
```
az resource update --ids /subscriptions/XXXX-XXXX-XXXX-XXXX/resourceGroups/MyRGName/providers/Microsoft.Synapse/workspaces/MySynapseName --set properties.publicNetworkAccess=Enabled
```

The below command helps you to **Disable** the publicNetworkAccess:
```
az resource update --ids /subscriptions/XXXX-XXXX-XXXX-XXXX/resourceGroups/MyRGName/providers/Microsoft.Synapse/workspaces/MySynapseName --set properties.publicNetworkAccess=Enabled
```

Please test and let me know. Awaiting your reply.

**Comment by onenessboy** [comment]
> 

for disabled is that  --set properties.publicNetworkAccess=Disabled ?

**Comment by navba-MSFT** [comment]
@onenessboy > > 
> 
> for disabled is that --set properties.publicNetworkAccess=Disabled ?

Yes. My Bad. It was a Typo in my comment. I just edited and corrected it in my comment.

Please test this and let me know if that serves your requirement.

**Comment by Prasanth-Sundarrajan** [comment]
> ```
> az resource update --ids /subscriptions/XXXX-XXXX-XXXX-XXXX/resourceGroups/MyRGName/providers/Microsoft.Synapse/workspaces/MySynapseName --set properties.publicNetworkAccess=Disabled
> ```

Hi @navba-MSFT 

This is working now... thanks for quick response. can we get this updated in official documentation as well so that it will help others...

**Comment by onenessboy** [comment]
> @onenessboy > >
> 
> > for disabled is that --set properties.publicNetworkAccess=Disabled ?
> 
> Yes. My Bad. It was a Typo in my comment. I just edited and corrected it in my comment.
> 
> Please test this and let me know if that serves your requirement.

Hi @navba-MSFT 

It works now. thank you so much for quick turnaround. can we please update documentation as well so that it can help others..
