### ISSUE TITLE
az ad user get-member-groups returns "Specified HTTP method is not allowed for the request target."

### ISSUE THREAD

**Issue by gsrx** [Azure/azure-cli#23807]
Calling az ad user get-member-groups --id "someuserprincipalname" returns error: "Specified HTTP method is not allowed for the request target."

--debug switch shows attempting POST to graph api eg.
https://graph.microsoft.com:443 "POST /v1.0/users/username HTTP/1.1" 405 None

Running on Windows 10
az version
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.1",
    "azure-devops": "0.22.0",
    "datafactory": "0.5.0"
  }
}

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Could you please share the full URL, but removing your personal information? I doubt something is wrong with the URL.

**Comment by jiasli** [comment]
I think it is because you have `#` in your user principal ID:

```
> az ad user get-member-groups --id 'jiasli_microsoft.com#EXT#@AzureSDKTeam.onmicrosoft.com' --debug
...
cli.azure.cli.core.util: Request URL: 'https://graph.microsoft.com/v1.0/users/jiasli_microsoft.com#EXT%23@AzureSDKTeam.onmicrosoft.com/getMemberGroups'
urllib3.connectionpool: https://graph.microsoft.com:443 "POST /v1.0/users/jiasli_microsoft.com HTTP/1.1" 405 None
```

When the URL was sent to Graph service, characters after `#` are dropped. I will fix it in a PR.
