### ISSUE TITLE
az postgres flexible-server create - The api-version '2022-01-20-preview' is invalid

### ISSUE THREAD

**Issue by plynch66** [Azure/azure-cli#23810]
## Describe the bug

I'm trying to create an Azure Database for PostgreSQL Flexible Server with VNet integration and I am getting an error relating to the API version as per below.

**Command Name**
`az postgres flexible-server create`

**Errors:**
```
(InvalidApiVersionParameter) The api-version '2022-01-20-preview' is invalid. The supported versions are '2021-06-01'.
Code: InvalidApiVersionParameter
Message: The api-version '2022-01-20-preview' is invalid. The supported versions are '2021-06-01'.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az postgres flexible-server create -l {} -g {} --admin-user {} --admin-password {} -n {} --sku-name {} --tier {} --version {} --storage-size {} --zone {} --vnet {} --subnet {} --private-dns-zone {}`

## Environment Summary
```
Windows-10-10.0.19043-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
aks-preview 0.5.98
application-insights 0.1.16
azure-cli-ml 1.41.0
azure-firewall 0.14.3
databricks 0.8.0
datafactory 0.6.0
dns-resolver 0.1.0
front-door 1.0.16
logic 0.1.6

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by alanenriqueo** [comment]
Hi @plynch66, there is an ongoing deployment that will fix this. I'll keep you posted.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by alanenriqueo** [comment]
Hi @plynch66, the deployment just completed. Can you try again?

**Comment by plynch66** [comment]
> Hi @plynch66, the deployment just completed. Can you try again?

Hi Alan - I can confirm that the deployment completed successfully using AZ CLI version 2.40.0

**Comment by RakeshMohanMSFT** [comment]
@plynch66 Thank you for the confirmation. I will close this issue now.
