### ISSUE TITLE
[Lock] Creating locks seems like it could be simplified a little bit

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2381]
The lack of help text for the `az lock create` command makes it a little difficult (for me at least) to know what input it expects, even when being familiar with creating locks in the portal.

<img src="https://cloud.githubusercontent.com/assets/116461/23574572/8bcceaf4-0034-11e7-92b5-cfc9b36d251e.png" width="400px" />

For example, I wanted to lock a resource group, so I tried running the following command, assuming that the `--lock-type` arg was what I wanted, and guessing that `delete` was a valid option: `az lock create --name <name> -g <group> --lock-type delete`.

This resulted in an `The lock '<name>' request is invalid.` error, so I double-checked the portal, which seemed to match the usage I was trying to achieve (e.g. lock type = delete).

<img src="https://cloud.githubusercontent.com/assets/116461/23574622/3238f996-0035-11e7-9136-f46d54cf21f5.png" width="400px" />

I decided to create the lock via the portal and then ran `az lock list` to see what the lock's metadata looked like. Surprisingly, I noticed that it's `level` was set to `CanNotDelete` and it's `type` was set to `Microsoft.Authorization/locks`. So I tried running `az lock create` again, but this time setting the `--lock-type` argument to `CanNotDelete`, and that failed with the same error as above.

I'm probably missing something here (apologies!), but it would be awesome if the `az lock create` command could add help text for each arg, provide the list of allowable values for enum args (e.g. `--lock-level`), as well as an example of what it looks like to create common locks (e.g. prevent deleting a resource group).

Additionally, the only arg that is marked as required is `--name`, and I'm not sure if that's accurate or if `--lock-level` or `--lock-type` are also required? (unless they provide a smart default?). The portal seems to require a lock type, so if that's the case, it would be cool if that requirement could be made clear in the help text of the `az lock create` command as well.

Finally, for ergonomic purposes, it would be cool if we could add short aliases for common args of this command (e.g. `-n` for `--name`, `-t` for `--lock-type`).

**Comment by brendandburns** [comment]
@lostintangent thanks for the feedback, sent a PR.

The current magic incantation is:

```sh
az lock create --resource-group=<group> --name=<name> --level=ReadOnly
```

The flags were confusing, I fixed it up in the referenced PR, once that's in, the call will be:

```sh
az lock create -g=<group> -n=<name> -t=CanNotDelete
```
