### ISSUE TITLE
Exmaples referenced but not provided 

### ISSUE THREAD

**Issue by situssoft** [Azure/azure-cli#23812]
The documentation on this page mentions that we should "see the example below" in a few places. However there appear to be no examples provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ad/app.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ad/app.yml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This is indeed an inconsistency between in-tool doc and online doc.

In in-tool help, the examples appear **below** the argument help.

```
> az ad app create -h

...
JSON property Arguments
    --app-roles                    : The collection of roles assigned to the application. With app
                                     role assignments, these roles can be assigned to users, groups,
                                     or service principals associated with other applications.
                                     Should be JSON file path or in-line JSON string. See examples
                                     below for details.
...

Examples
    ...

    Create an application with a role
        az ad app create --display-name mytestapp --identifier-uris https://mytestapp.websites.net
        --app-roles @manifest.json
        ("manifest.json" contains the following content)
        [{
            "allowedMemberTypes": [
              "User"
            ],
            "description": "Approvers can mark documents as approved",
            "displayName": "Approver",
            "isEnabled": "true",
            "value": "approver"
        }]
```

But in the document, the examples appear **above** the argument help.
