### ISSUE TITLE
No module named 'azure.keyvault.v7_0'

### ISSUE THREAD

**Issue by JamiePan** [Azure/azure-cli#23816]
## Describe the bug

**Command Name**
`az keyvault secret set`

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault secret set --vault-name {} --name {} --value {}`

## Environment Summary
```
Linux-5.15.0-1019-azure-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
`2.0.81` is not official CLI. Please follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli to install CLI and all dependencies correctly

**Comment by evelyn-ys** [comment]
@wangzelin007 Can bot detect `2.0.81` and auto reply?

**Comment by wangzelin007** [comment]
> @wangzelin007 Can bot detect `2.0.81` and auto reply?
Sure, we will see this feature soon.

**Comment by wangzelin007** [comment]
> @wangzelin007 Can bot detect `2.0.81` and auto reply?

Sure, we will use this feature soon.
