### ISSUE TITLE
Function runtime not being set properly when using ~4

### ISSUE THREAD

**Issue by RyanHill-MSFT** [Azure/azure-cli#23827]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az functionapp create --name funcapp --storage-account storageaccount --os-type Windows --consumption-plan-location eastus2 --runtime dotnet --runtime-version 6 --functions-version 4 --disable-app-insights

**Describe the bug**
When using the above command, the portal reports that the function runtime version is reported as being an unsupported version.

![image](https://user-images.githubusercontent.com/47189704/189253898-56c908de-4bb2-44e3-999a-622eb0b990e2.png)

![image](https://user-images.githubusercontent.com/47189704/189253937-981295d3-fb1c-4106-9c3c-c2b56c137cd6.png)

**To Reproduce**
Run the related command

**Expected behavior**
Function runtime version set to 4 rather than custom

**Environment summary**
azure-cli: 2.39.0
azure-cli-core: 2.39.0
azure-cli-telemetry: 1.0.6
extensions:
  azure-devops: 0.23.0
  containerapp: 0.3.5
  webpubsub: 1.1.0

**Additional context**
https://docs.microsoft.com/en-us/answers/questions/989385/index.html

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RyanHill-MSFT** [comment]
@PramodValavala-MSFT let me know what you think. It could be an ARM issue.

**Comment by panchagnula** [comment]
@RyanHill-MSFT can you do a az functionapp show post creating & check the properties set. if the right value is set on the properties then this might be a portal issue & should be reported to them. Thanks!

**Comment by RyanHill-MSFT** [comment]
@panchagnula `az functionapp show` doesn't show the runtime worker version or dotnet version. I'll send you the output.

**Comment by navba-MSFT** [comment]
Adding Service team.

@Stefanus Hinardi, @Francisco-Gamino. Could you please look into this once you get a chance ?

**Comment by Francisco-Gamino** [comment]
Adding Functions Az CLI team @amamounelsayed @apawast

**Comment by kamperiadis** [comment]
I was able to reproduce this. Will need to investigate further.
