### ISSUE TITLE
Certificate Verify Failed for az login command on mac

### ISSUE THREAD

**Issue by vyshnavi-gadiparthi** [Azure/azure-cli#23820]
Getting the below error after setting REQUESTS_CA_BUNDLE=cacert.pem file path:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/oauth2/v2.0/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle. More info: https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy.

Complete details of my error :
**Command Name**
`az login`

**Errors:**
```
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/oauth2/v2.0/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --debug`

## Environment Summary
```
macOS-11.6-x86_64-i386-64bit, Darwin 20.6.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.40.0
```

Could someone please help me to resolve this issue

**Comment by yonzhan** [comment]
Please go through this issue and see if it helps
https://github.com/Azure/azure-cli/issues/21514

**Comment by vyshnavi-gadiparthi** [comment]
Hi @yonzhan ,

I tried #21514 that doesnot help, I see nothin gworng from the network side in my system.

**Comment by vyshnavi-gadiparthi** [comment]
Hi @yonzhan,

Could you please help me to resolve this issue. I tried multiple versions as well but still nothing works. I am blocked with this error.

**Comment by vyshnavi-gadiparthi** [comment]
Hi @yonzhan,

Could you please help me to resolve this issue. I tried multiple versions as well but still nothing works. I am blocked with this error.

**Comment by bebound** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/19571

@vyshnavi-gadiparthi This error is caused by your certificate, there is nothing we can do about it. Disable proxy/VPN/Trust CA may help.
