### ISSUE TITLE
Desejo trabalhar com Kubernete Aks para fazer o load Ballancer

### ISSUE THREAD

**Issue by devedsonbelem** [Azure/azure-cli#23823]
i wish to work with load ballancer and aks and jenkins treadmill

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@devedsonbelem The [official AKS docs](https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard) should cover the details on this.
