### ISSUE TITLE
Getting Authorization error

### ISSUE THREAD

**Issue by gnaneshke** [Azure/azure-cli#23822]
## Describe the bug

**Command Name**
`az account get-access-token`

**Errors:**
```
Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2022-09-07T11:08:13.6140630Z and the maximum allowed lifetime for this request is 28800.\r\nTrace ID: 37459880-5813-4b55-95b4-89cd9f78e900\r\nCorrelation ID: b3e39851-a101-4b5d-a246-bf2e73b40bce\r\nTimestamp: 2022-09-08 08:18:14Z","error_codes":[70043],"timestamp":"2022-09-08 08:18:14Z","trace_id":"37459880-5813-4b55-95b4-89cd9f78e900","correlation_id":"b3e39851-a101-4b5d-a246-bf2e73b40bce","suberror":"token_expired"}
Traceback (most recent call last):
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az account get-access-token --resource {} --subscription {} -o={}`

## Environment Summary
```
Linux-5.15.0-1019-azure-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by RakeshMohanMSFT** [comment]
@gnaneshke Please go through this article https://stackoverflow.com/questions/68160287/microsoft-azure-ad-error-descriptiondue-to-a-configuration-change-made-by-you also I suggest you open a support ticket for further troubleshooting. This isn't really a CLI issue per se.

**Comment by jiasli** [comment]
2.0.81 is not the official Azure CLI (https://github.com/Azure/azure-cli/issues/19640).

Please follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt to install the official latest version which has Conditional Access support (https://github.com/Azure/azure-cli/pull/17738). It will let you know which command to call.
