### ISSUE TITLE
az storage failed, not able tp upload files

### ISSUE THREAD

**Issue by devdp** [Azure/azure-cli#23837]
## Describe the bug

**Command Name**
`az storage blob upload`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload --file {} --container-name {} --account-name {} --connection-string {}`

## Environment Summary
```
Linux-5.4.0-1089-azure-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.39.0
```

**Comment by yonzhan** [comment]
Please provide detailed error log

**Comment by navba-MSFT** [comment]
@devdp Thanks for reaching out to us and reporting this issue. Could you please elaborate your issue and run the same command with `--debug `switch ? Please share the detailed debug out here so that we can assist you better. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@devdpI wanted to do quick follow-up to check if you had a chance to look at my above comment. Please elaborate your issue and run the same command with --debug switch and share the output. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@devdp Please provide us more details on this issue and share the debug output once you get a chance. Once you are available to work on this, please feel free to reopen this thread and provide the requested details. We would be happy to help.
