### ISSUE TITLE
Issue with "getaddrinfo" failed 

### ISSUE THREAD

**Issue by Abhinavgundapaneni** [Azure/azure-cli#23838]
## Describe the bug

**Command Name**
`az synapse notebook create`

**Errors:**
```
<urllib3.connection.HTTPSConnection object at 0x058E71D8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az synapse notebook create --workspace-name {} --name {} --file {} -o {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
application-insights 0.1.16

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@Abhinavgundapaneni Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Abhinavgundapaneni Looking at the error message, its pretty clear that the issue is due to the network connectivity. Could you please confirm if you have any proxy / firewall within your corporate network ? This seems to be causing the network connectivity to fail.

Could you please test from a different network and check if the same command fails ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Abhinavgundapaneni I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Abhinavgundapaneni The action is currently pending on you to test the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by Snodio** [comment]
Hi! I get this same error when trying to do a backup of a keyvault in a subscription, i have tried multiple networks to no avail.

My command:
az keyvault backup start --hsm-name kv-eid-static --storage-account-name sasystest --blob-container-name keyvault-backup --storage-container-SAS-token $sas --subscription sub-eid

Error message:
<urllib3.connection.HTTPSConnection object at 0x05900100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
