### ISSUE TITLE
Misleading example documentation for az containerapp secret

### ISSUE THREAD

**Issue by thohan88** [Azure/azure-cli#23833]
The example uses `MySecretName1` which according to the following CLI-command (AZ Cli 2.40.0 containerapp 0.3.10)
```
az containerapp secret set \
  -n myapp
  -g myrg
  --secrets MySecretName1=MySecretValue1
```
returns
```
Property 'secrets.name' has an invalid value 'MySecretName1'. A value must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
```

According to this, it should be `mysecretname1`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a4c2a84-890b-8c80-35ba-4b88f4fd52f3
* Version Independent ID: dc8c1147-dd84-6ef3-2744-63853b1a1d20
* Content: [az containerapp secret](https://docs.microsoft.com/en-us/cli/azure/containerapp/secret?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/containerapp/secret.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/containerapp/secret.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@thohan88 The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.

**Comment by matt-bourne-bi** [comment]
One year later, not fixed
