### ISSUE TITLE
A way to manage Azure Backup please? (perhaps with Cli2\Python SDK?)

### ISSUE THREAD

**Issue by 4c74356b41** [Azure/azure-cli#2384]
http://stackoverflow.com/questions/42274160/how-to-manage-azure-backup-with-azure-python-sdk-or-azure-cli/42303540#42303540

Can only be done with Powershell or REST, which is anything but user-friendly.

**Comment by agates** [comment]
I mentioned this in #2083 as well.

We are currently managing this with the REST API, which causes many hairs to become split.  Better than powershell, though.

**Comment by 4c74356b41** [comment]
Why would REST be better than powershell? this is ridiculous. Powershell is so much better than REST API. Following your logic c# compiler is so much better then minesweeper. Ofc you can do more with c# compiler, but how much time and effort would that cost?

**Comment by agates** [comment]
The necessary PowerShell commandlets for this feature are not (yet) available to use on Linux, where our tooling infrastructure is located.  That's all.

Our small Python wrapper around the REST API is a worthwhile compromise.  For other features we are using the CLI and it's awesome.

**Comment by Cato2** [comment]
@agates - any chance you could share your Python wrapper for the Azure Backup REST API, even as a GitHub gist?

**Comment by JasonRShaver** [comment]
We (the CLI and Azure Batch teams) are working on Azure Batch for CLI 2.0 presently.

**Comment by agates** [comment]
@Cato2 I've made a repo for it.  It's a bit rough as we just needed something quick and dirty.

https://github.com/agates/azure-python-scripts

**Comment by Cato2** [comment]
Thanks for sharing that code @agates - looks very useful!

**Comment by mikemcfarlane-iproov** [comment]
Is there any progress on adding Backup to the CLI or Python?

**Comment by tjprescott** [comment]
Azure Backup has been merged and will be available in the next CLI release.
