### ISSUE TITLE
tag parameter is not documented for az acr import

### ISSUE THREAD

**Issue by jonassamuelssoncab** [Azure/azure-cli#23841]
**az acr import** does not list **tag** as a possible parameter, even though it is supported & included in some of the examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/acr.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/acr.yml)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@jonassamuelssoncab do you mean with the help command? -h.

**Comment by jonassamuelssoncab** [comment]
@RakeshMohanMSFT I was referring to the [online docs](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-import).

I've now seen that `-t` is documented as part of `--image`.
It took me a few passes to see this though since I expected `-t` to be a short form of `--tag`.

**Comment by RakeshMohanMSFT** [comment]
@jonassamuelssoncab Usual image and tags are added as a single parameter right? also even in the --image param you can send both imagename:tagname. I am not sure if there is any scope to change the document. Let me know if you are ok to close this thread.

**Comment by jonassamuelssoncab** [comment]
@RakeshMohanMSFT Yes it's perfectly doable to pass both image name and tag, that is what I'm doing now 😃 you can close this issue.
