### ISSUE TITLE
Support --min-instances  as part of az functionapp create command

### ISSUE THREAD

**Issue by SushmithaVReddy** [Azure/azure-cli#23840]
**Related command**
az functionapp create

**Is your feature request related to a problem? Please describe.**
We have a use case where we want to be able to define the minReplicas for a function app on arc to be 0 (The default is being set to 1 currently). Function apps in arc are created using az functionapp create command and so we are looking if --min-instances can be supported by the command

**Describe the solution you'd like**
Support --min-instances  as part of az functionapp create command

**Additional context**
We wonder if this will create any issues for non arc environments. Ideally for customers on consumption plan we don't provide a --min-instances setting through portal. The ask here might change that.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by panchagnula** [comment]
No plans at this time to support this property with create. This can be supported using config set & --generic-configurations on an existing app. We do have plans to add this property as its own parameter in the set command.
https://docs.microsoft.com/en-us/cli/azure/functionapp/config?view=azure-cli-latest#az-functionapp-config-set

**Comment by SushmithaVReddy** [comment]
@panchagnula , We've tried the command suggested and couldn't see the number of workers change.

Command ran:
az functionapp config set --number-of-workers 0 --name testapp005 --resource-group testapp005_group

Response:
{
  "acrUseManagedIdentityCreds": null,
  "acrUserManagedIdentityId": null,
  "alwaysOn": null,
  "apiDefinition": null,
  "apiManagementConfig": null,
  "appCommandLine": null,
  "appSettings": null,
  "autoHealEnabled": null,
  "autoHealRules": null,
  "autoSwapSlotName": null,
  "azureStorageAccounts": null,
  "connectionStrings": null,
  "cors": {
    "allowedOrigins": [
      "https://ms.portal.azure.com"
    ],
    "supportCredentials": false
  },
  "defaultDocuments": null,
  "detailedErrorLoggingEnabled": null,
  "documentRoot": null,
  "experiments": null,
  "ftpsState": "FtpsOnly",
  "functionAppScaleLimit": null,
  "functionsRuntimeScaleMonitoringEnabled": null,
  "handlerMappings": null,
  "healthCheckPath": null,
  "http20Enabled": null,
  "httpLoggingEnabled": null,
  "id": "/subscriptions/2dbbb6e5-eda7-4de9-9fc2-c124430a7491/resourceGroups/testapp005_group/providers/Microsoft.Web/sites/testapp005",
  "ipSecurityRestrictions": [
    {
      "action": "Allow",
      "description": "Allow all access",
      "headers": null,
      "ipAddress": "Any",
      "name": "Allow all",
      "priority": 2147483647,
      "subnetMask": null,
      "subnetTrafficTag": null,
      "tag": null,
      "vnetSubnetResourceId": null,
      "vnetTrafficTag": null
    }
  ],
  "javaContainer": null,
  "javaContainerVersion": null,
  "javaVersion": null,
  "keyVaultReferenceIdentity": null,
  "kind": null,
  "limits": null,
  "linuxFxVersion": "DOTNET|6.0",
  "loadBalancing": null,
  "localMySqlEnabled": null,
  "location": "East US",
  "logsDirectorySizeLimit": null,
  "machineKey": null,
  "managedPipelineMode": null,
  "managedServiceIdentityId": null,
  "minTlsVersion": "1.2",
  "minimumElasticInstanceCount": null,
  "name": "testapp005",
  "netFrameworkVersion": null,
  "nodeVersion": null,
 ###  "numberOfWorkers": null,
  "phpVersion": null,
  "powerShellVersion": null,
  "preWarmedInstanceCount": null,
  "publicNetworkAccess": null,
  "publishingUsername": "$testapp005",
  "push": null,
  "pythonVersion": null,
  "remoteDebuggingEnabled": null,
  "remoteDebuggingVersion": null,
  "requestTracingEnabled": null,
  "requestTracingExpirationTime": null,
  "resourceGroup": "testapp005_group",
  "scmIpSecurityRestrictions": [
    {
      "action": "Allow",
      "description": "Allow all access",
      "headers": null,
      "ipAddress": "Any",
      "name": "Allow all",
      "priority": 2147483647,
      "subnetMask": null,
      "subnetTrafficTag": null,
      "tag": null,
      "vnetSubnetResourceId": null,
      "vnetTrafficTag": null
    }
  ],
  "scmIpSecurityRestrictionsUseMain": null,
  "scmMinTlsVersion": null,
  "scmType": "None",
  "tags": {
    "hidden-link: /app-insights-resource-id": "/subscriptions/2dbbb6e5-eda7-4de9-9fc2-c124430a7491/resourceGroups/testapp005_group/providers/Microsoft.Insights/components/testapp005"
  },
  "tracingOptions": null,
  "type": "Microsoft.Web/sites",
  "use32BitWorkerProcess": true,
  "virtualApplications": null,
  "vnetName": null,
  "vnetPrivatePortsCount": null,
  "vnetRouteAllEnabled": null,
  "webSocketsEnabled": null,
  "websiteTimeZone": null,
  "windowsFxVersion": null,
  "xManagedServiceIdentityId": null
}

Please let us know if the response suggests any failure.

**Comment by panchagnula** [comment]
The set command doesn't support that as first class property, the ask was to use --settings which can take a key value pair or a JSON file with the properties to be set 
https://learn.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest#az-functionapp-config-appsettings-set

**Comment by SushmithaVReddy** [comment]
Hi @panchagnula , https://learn.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest#az-functionapp-config-appsettings-set seems to set the appsettings which is part of site config https://github.com/Azure/azure-cli/blob/c1c805f5680f27b17412acf6fd53228b50edb8b2/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L3058 . We'd need an option where the site_config num_of_workers property needs to be set (geomaster considers this property to set min instances value for our case - https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites?path=/src/Hosting/AdministrationService/Microsoft.Web.Hosting.Administration.Kube/K8SEHelper.cs&version=GBdev&line=375&lineEnd=376&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)
