### ISSUE TITLE
az appservice web deployment push

### ISSUE THREAD

**Issue by atrauzzi** [Azure/azure-cli#2385]
Would really love to see this.  I don't like having to manage out-of-channel FTP credentials and host names for my deployments and I've already authenticated with `az`.  Seems only logical that I can just point it at directories and have them sent over.

(whatever `az` would end up using behind the scenes really doesn't matter, so long as my file management experience is unified via this tool)

And no, I do not use git for deployment.

**Comment by yugangw-msft** [comment]
@atrauzzi, there are lots of great ftp clients around, and i don't think writing another one in cli would better them. Use `az webapp deployment list-publishing-profiles --query ...` should extract out the ftp client creds to give to a ftp client tool to open the connection, and then upload files.
If you can tell me the ftp client tool you like the best, I can put in a few samples in the command help to show the end to end flow.

**Comment by atrauzzi** [comment]
@yugangw-msft - I've had quite a fair bit of discussion recently about this, particularly with @davidebbo.

While I think we came to a solution a few weeks back, you should be aware that FTP shouldn't be considered an option.  I also suspect that some clarification is in order: I'm not asking for samples on how to use FTP clients.

I'm talking about an integrated application deployment command, which I still think is somewhat badly needed given the manual flow I've had to put together to leverage Azure's built-in deployment infrastructure.

**Comment by davidebbo** [comment]
@atrauzzi I think it may help to clarify the deployment scenario that you're after, as there are subtleties. e.g.

1. Do you want to deploy one local file, a whole local folder, a local zip file?
2. If deploying a whole folder/zip, do you expect deletions to be carried (msdeploy supports that), or just have it blast all the files over whatever happens to be there (Kudu zip API behavior)

**Comment by yugangw-msft** [comment]
@atrauzzi, please reactivate it with clarifications
