### ISSUE TITLE
Network Profile creation step cannot be performed

### ISSUE THREAD

**Issue by tshaiman** [Azure/azure-cli#23851]
[Enter feedback here]
at the top of the page it is stated that `az network profile` create is only available on the resource create phase 
and that uses should consult the specific resource. the only supported resource for now is `container instances`

when looking at container instances created CLI you see no reference / command to create network profile :
https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-create

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1651f497-06fd-d00c-0b0c-1b4a51f90f9d
* Version Independent ID: 57fa7b63-4563-2ad2-4dc4-621f7295cd20
* Content: [az network profile](https://docs.microsoft.com/en-us/cli/azure/network/profile?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/profile.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/profile.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
Please refer to the description in https://github.com/Azure/azure-cli/issues/13191.
