### ISSUE TITLE
Getting "Unable to parse parameter" with "az deployment group create" and parameter files since 2.40.0

### ISSUE THREAD

**Issue by John-Bosch** [Azure/azure-cli#23854]
**Related command**
az deployment group create

**Describe the bug**

Some Azure Dev Ops MS hosted agents have upgraded their Azure CLI from 2.39.0 to 2.40.0. Whenever we get and agent with 2.40.0 our Azure CLI scripts that trigger bicep deployments fail with the error

ERROR: Unable to parse parameter: @D:\a\1\s\Infrastructure\FunctionApps\common-parameters.json @D:\a\1\s\Infrastructure\FunctionApps\AddressValidation\AddressValidation-parameters.json

The following two images are of two runs of exactly the same pipeline that picked up agents with differing versions of the Azure CLI.

![image](https://user-images.githubusercontent.com/5135377/189805290-f33648aa-cdd3-40b5-a91c-d356b3956f7d.png)
![image](https://user-images.githubusercontent.com/5135377/189805302-1655fe56-05f5-4497-93dc-e536c87e2bfd.png)

I have since run the same Azure CLI command locally on a pre-2.40.0 build (2.36.0 to be precise) and the command succeeded. After upgrading my local Azure CLI to 2.40.0 the same command now fails in the same fashion.

Further testing locally found that this piece of code no longer works (but did pre 2.40.0)

![image](https://user-images.githubusercontent.com/5135377/189808621-282c41a1-2a49-4d99-a083-6ca42794d27a.png)

whereas modifying the code to 

![image](https://user-images.githubusercontent.com/5135377/189808706-9361fc1e-f370-4a08-88fe-8aa7883616b7.png)

does work. So it would appear that the issue is related to "az deployment group create" being passed an array of paths to parameters files.

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by krokofant** [comment]
This issue seems to be bigger. We're seeing a similar issue with az acr
```powershell
$importArguments = @(
    '--name', 'a-name'
    '--subscription', 'a-subscription'
    '--source', "foo.azurecr.io/example:1.2.3"
    '--image', 'example:1.2.4'
)
az acr import $importArguments --debug
```
With 2.40.0
![image](https://user-images.githubusercontent.com/5908498/189859987-77891d6c-30a7-403c-8b0c-7fc0b66e4e72.png)
With 2.39.0
![image](https://user-images.githubusercontent.com/5908498/189860110-5ca3f398-94aa-4a7c-a727-46947e29f65c.png)

Our ci pipelines are broken because of this. The latest Azure Pipelines / (GitHub?) runner-images have 2.40.0 included https://github.com/actions/runner-images/blob/releases/win22/20220911/images/win/Windows2022-Readme.md#cli-tools

**Comment by krokofant** [comment]
@John-Bosch You can probably use something like this as a workaround, but with your own command and arguments. Just use Invoke-Expression and interpolate the arguments directly in a string.
```powershell
Invoke-Expression "az acr import $importArguments"
```

**Comment by krokofant** [comment]
Related to https://github.com/Azure/azure-cli/pull/23514

**Comment by zhoxing-ms** [comment]
Same issue as #23797
