### ISSUE TITLE
ARM Deployement with Azure CLI failing

### ISSUE THREAD

**Issue by Abhinavgundapaneni** [Azure/azure-cli#23860]
## Describe the bug

**Command Name**
`az deployment group create`

**Errors:**
```
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"\"\r\n  }\r\n}"}]}}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az deployment group create --name {} --resource-group {} --template-file {} --parameters {} {} {} {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
application-insights 0.1.16

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by Abhinavgundapaneni** [comment]
This is the deployment json I'm trying to execute.

{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
      "workspaceName": {
        "type": "string"
      },
      "LS_SQL_Serverless_OEA": { "type": "string" },
      "LS_ADLS_OEA": { "type": "string" },
      "LS_HTTP": { "type": "string" }
    },
    "variables": {
      "workspaceId": "[concat('Microsoft.Synapse/workspaces/', parameters('workspaceName'))]"
    },
    "resources": [
        {
            "name": "[concat(parameters('workspaceName'), '/DS_HTTP_binary')]",
            "type": "Microsoft.Synapse/workspaces/datasets",
            "apiVersion": "2019-06-01-preview",
            "properties": {
              "description": "Retrieves data from an http endpoint.\nThe data can be in any format - the binary dataset allows us to pull any payload without affecting it.",
              "linkedServiceName": {
                "referenceName": "[parameters('LS_HTTP')]",
                "type": "LinkedServiceReference",
                "parameters": {
                  "baseURL": { "value": "@dataset().URL", "type": "Expression" }
                }
              },
              "parameters": { "URL": { "type": "string" } },
              "folder": { "name": "OEA_Framework" },
              "annotations": [],
              "type": "Binary",
              "typeProperties": { "location": { "type": "HttpServerLocation" } }
            },
            "dependsOn": []
          }
    ]
}

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by norvegec** [comment]
The same release in Azure Devops that worked for us just yesterday today (September, 13nth, 2022) started failing.
The step that fails is Azure Devops task "Azure CLI" (ver. 2). It runs our custom PS-core script and fails in line similar to this:
`az deployment sub create -l $loc --template-file $template --parameters @("p1=$p1", "p2=$p2")`
where `p1` and `p2` are ARM template parameters and `$p1` and `$p2` powershell variables defined and set within that very script.
Comparing logs, I can see that Azure CLI on the machine (Azure agent windows-2019) was bumped from 2.39.0 to 2.40.0.
Does anything changed in the way Azure CLI works with array parameters in Powershell console?

**Comment by norvegec** [comment]
Just reproduced this on local dev machine:
Script succeeded on Azure CLI ver. 2.39.0 and after upgrade to 2.40.0 it failed.

I suppose if you follow semver, minor upgrades should not introduce breaking changes like this.

**Comment by zhoxing-ms** [comment]
> "baseURL": { "value": "@dataset().URL", "type": "Expression" }
> az deployment sub create -l $loc --template-file $template --parameters @("p1=$p1", "p2=$p2")
where p1 and p2 are ARM template parameters and $p1 and $p2 powershell variables defined and set within that very script.
Comparing logs, I can see that Azure CLI on the machine (Azure agent windows-2019) was bumped from 2.39.0 to 2.40.0.

Same issue as #23797
