### ISSUE TITLE
SKU error on creation of workspace linked to cluster

### ISSUE THREAD

**Issue by wiperpaul** [Azure/azure-cli#23867]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az monitor log-analytics workspace create`

**Describe the bug**
After a workspace has been linked to a dedicated LA Cluster which has a cluster level commitment tier. That workspace can be deleted and created again however during recreation of the workspace there is an error. 

`{"code":"DeploymentFailed","details":[{"code":"BadRequest","message":"sku.name can not be changed while workspace is linked to cluster"}]}`

In the Azure Portal, In the _Resource Group -> Deployments_ blade it then shows that the deployment Failed

However the workspace does in fact create and appears up a few moments later with its SKU as the expected cluster level commitment tier.

**To Reproduce**
- Link Workspace to Cluster with Cluster Level Commitment Tier that will be inherited by workspaces
- Delete Workspace 
- Create Workspace and receive error 

**Expected behavior**
Warning that SKU could not be changed as there is an existing Cluster Workspace link. Also that the Deployment does not show as failed.

**Environment summary**

Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.208.0

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by kairu-ms** [comment]
It's because you delete workspace in soft-delete. You can add `--force` in delete workspace commands.

**Comment by wiperpaul** [comment]
Thanks, I tested force and you are right. I was wrong in thinking it was because of the cluster link operation. 
It does indeed create the workspace again with pergb2018. Does this mean that the 'limit of two link operations ' resets for the workspace ?
