### ISSUE TITLE
Azure CLI command error

### ISSUE THREAD

**Issue by BBoardley** [Azure/azure-cli#23869]
## Describe the bug

**Command Name**
`az sql db list`

**Errors:**
```
(--server --resource-group | --ids) are required
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sql db list`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.0

```

**Comment by SaurabhSharma-MSFT** [comment]
@BBoardley We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@BBoardley I am not seeing any errors while executing `az sql db list`.  Can you please share the error details and the debug log using `--debug`.

**Comment by SaurabhSharma-MSFT** [comment]
@BBoardley Please let me know if you are still having issues else we will proceed with the issue closure. Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@BBoardley We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by BBoardley** [comment]
Nothing has changed it still does not work for me.
