### ISSUE TITLE
az afd origin-group create and update descriptions are same.

### ISSUE THREAD

**Issue by mertbezirgan** [Azure/azure-cli#23864]
[Enter feedback here]
In the documentation the definitions of az afd origin-group create and az aft origin-group update commands' descriptions are same which is "Creates a new origin group within the specified profile". Definition of update command needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f327aba4-4def-7df8-a182-d35c44e54ba0
* Version Independent ID: 2396414e-db40-d7ff-1cd9-7bb159e9b44a
* Content: [az afd origin-group](https://docs.microsoft.com/en-us/cli/azure/afd/origin-group?view=azure-cli-latest#az-afd-origin-group-update)
* Content Source: [latest/docs-ref-autogen/afd/origin-group.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/afd/origin-group.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@mertbezirgan Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@mertbezirgan Thanks for reporting this issue. We have created the above PR to fix this. It is currently under review. In the meantime if you have any questions, please feel free to ask.
