### ISSUE TITLE
Network NIC creation with subnet in different resource group fails

### ISSUE THREAD

**Issue by jongpieter** [Azure/azure-cli#2387]
Situation:

Resource group `Production` contains the virtual network `vlan`. In this vnet the subnet `implementation-subnet` is created under the resource group `Production`. In a different resource group `implementation`, a new nic is created with a reference to the subnet `implementation-subnet`, as this resource requires access to the main network. 

In the Azure Portal it is possible to create the above situation. 

Using the Azure-CLI this command fails with `The Resource 'Microsoft.Network/virtualNetworks/vlan' under resource group 'implementation' was not found.`

```bash
az group create -n Production -l westeurope
az group create -n implementation -l westeurope

az network vnet create -g Production --vnet-name vlan 

az network vnet subnet create -g Production --vnet-name vlan --address-prefix 10.0.100.0/24 --name implementation-subnet

az network nic create --resource-group implementation --name implementation-nic \
  --vnet-name vlan --subnet implementation-subnet \
  --private-ip-address 10.0.100.1
```

Any suggestions how to make this work using the CLI. A workaround is using the Portal, but is not preffered.

**Comment by tjprescott** [comment]
Hi @jongpieter when you supply names, the CLI resolves those names to the resource group you specify (which can only be one). For your scenario, instead of using `--subnet NAME --vnet-name NAME` instead use `--subnet ID`.  By supplying the fully qualified ID for the subnet parameter (and OMIT vnet-name) your scenario should work.

**Comment by tjprescott** [comment]
If you want to use programmatically (like in a bash script):
`az network vnet subnet show -g {rg} -n {subnet} --vnet-name {vnet} --query id -o tsv`

If you just need to copy/paste:
`az network vnet subnet show -g {rg} -n {subnet} --vnet-name {vnet} --query id`
