### ISSUE TITLE
--image-version is not recognize

### ISSUE THREAD

**Issue by juliocfc** [Azure/azure-cli#23875]
[Enter feedback here]
--image-version is not a recognized argument.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99108d44-6c69-d481-7c5e-891905799635
* Version Independent ID: 142e71ef-a7cd-2acb-786b-7ac359863e91
* Content: [az sig image-version](https://docs.microsoft.com/en-us/cli/azure/sig/image-version?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/sig/image-version.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sig/image-version.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@juliocfc Could you show me the command and parameters you used for more detailed information? thanks~

**Comment by PramodValavala-MSFT** [comment]
@juliocfc Could you share more details like the exact command and complete output here?
