### ISSUE TITLE
az tag create is returning AuthorationFailed error while executing it from azure pipelines as cli task

### ISSUE THREAD

**Issue by vivek602** [Azure/azure-cli#23889]
az tag create is giving authorization failed error for the azure CLI version 2.39.0

**Related command**
 az tag create --resource-id /subscriptions/xxxaxxxxx-xqxx-xxxx-xxxx-xxxxxxxxxxx/resourceGroups/AZ-RG-xxxxxxxxxxxx-xx-xx/providers/Microsoft.Databricks/workspaces/databrickstest --tags version=1.2.1

**Describe the bug**
I am executing yaml file which contains tasks for az tag create from azure pipelines and getting AuthorizationFailed error.

**To Reproduce**
 - task: AzureCLI@2
      displayName: 'Tagging Databricks on Azure Cloud'
      continueOnError: false
      inputs:
        azureSubscription: 'xxxxxxxxxxxxxxxxxxxxx'
        scriptLocation: 'inlineScript'
        scriptType: 'bash'
        inlineScript: |
            set -euovx pipefail
            echo -e "\e[1mWriting resource tag on Azure\e[0m"
            az tag create \
            --resource-id /subscriptions/$(azureSubscriptionprd)/resourceGroups/$(resgroup)/providers/Microsoft.Databricks/workspaces/$(databricksWspk) \
            --tags version=${{parameters.version}}

**Expected behavior**
resources (Databricks) tag number should get updated after successful execution of the task

**Environment summary**
azure-cli                         2.39.0 *

core                              2.39.0 *
telemetry                          1.0.6 *

Extensions:
azure-devops                      0.18.0

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

**Comment by yonzhan** [comment]
route to CXP team

**Comment by vivek602** [comment]
Apologies it was caused due to RBAC. Thus closing this issue
