### ISSUE TITLE
az functionapp config appsettings set for multiple config not working from 2.40

### ISSUE THREAD

**Issue by kornbo2-dev** [Azure/azure-cli#23887]
az functionapp config appsettings set command for multiple config not working from 2.40

https://docs.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest

This use to work before 2.40:
_az functionapp config appsettings set --name $FunctionAppName --resource-group $ResourceGroupName --slot-settings "AppConfig1=test" "AppConfig2=test2"_

now still works, but all the values will be stored in AppConfig1

AppConfig1=**_test AppConfig2=test2_**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@kornbo2-dev Thank you for reaching out, we are looking into it.

**Comment by kornbo2-dev** [comment]
> @kornbo2-dev Thank you for reaching out, we are looking into it.

Thank you.  This is causing all our deployments to fail as devOps is running the scripts using 2.40.  Let us know if there is a workaround.  thank you.

**Comment by kornbo2-dev** [comment]
we are actually using this one....  via a variable and it was working....

$FunctionAppConfigCreate  = @("AppConfig1=test" "AppConfig2=test2")
 
az functionapp config appsettings set --name $FunctionAppName --resource-group $ResourceGroupName --slot-settings $FunctionAppConfigCreate

**Comment by RakeshMohanMSFT** [comment]
@kornbo2-dev We are unable to reproduce this issue at our end with 2.40.0, please see below screenshots
![image](https://user-images.githubusercontent.com/49954584/190307118-92b6fe5e-e3f5-4365-a81c-4cedb71f81a0.png)
![image](https://user-images.githubusercontent.com/49954584/190307162-db799a6e-8a56-48c6-833c-4d3bd5d3bec4.png)

**Comment by kornbo2-dev** [comment]
> @kornbo2-dev We are unable to reproduce this issue at our end with 2.40.0, please see below screenshots ![image](https://user-images.githubusercontent.com/49954584/190307118-92b6fe5e-e3f5-4365-a81c-4cedb71f81a0.png) ![image](https://user-images.githubusercontent.com/49954584/190307162-db799a6e-8a56-48c6-833c-4d3bd5d3bec4.png)

We are actually putting it on a variable, apologies... can you try below? thanks

$FunctionAppConfigCreate = @("AppConfig1=test" "AppConfig2=test2")

az functionapp config appsettings set --name $FunctionAppName --resource-group $ResourceGroupName --slot-settings $FunctionAppConfigCreate

**Comment by rick-hayek** [comment]
similar issue happens for 
`az webapp config appsettings set`

**Comment by RakeshMohanMSFT** [comment]
@StrawnSC / @panchagnula  is this a regression?

**Comment by haroonf** [comment]
This is not a regression. This is failing due to the $FunctionAppConfigCreate powershell var. When a powershell string array is passed, it is automatically converted to a string with quotation delimiters, so you end up passing `"AppConfig1=test AppConfig2=test2"` instead of `"AppConfig1=test" "AppConfig2=test2"`. The `config appsettings --slot-settings` requires separate strings delimited by spaces, and since a single string is passed, this command won't work.

**Comment by kornbo2-dev** [comment]
> This is not a regression. This is failing due to the $FunctionAppConfigCreate powershell var. When a powershell string array is passed, it is automatically converted to a string with quotation delimiters, so you end up passing `"AppConfig1=test AppConfig2=test2"` instead of `"AppConfig1=test" "AppConfig2=test2"`. The `config appsettings --slot-settings` requires separate strings delimited by spaces, and since a single string is passed, this command won't work.

this used to work before in all our pipelines... in 2.39 it will work with or without commas

anyway, we have found a workaround not to use an array variable as we have over 50+ config that we need to pass...

**Comment by panchagnula** [comment]
> > This is not a regression. This is failing due to the $FunctionAppConfigCreate powershell var. When a powershell string array is passed, it is automatically converted to a string with quotation delimiters, so you end up passing `"AppConfig1=test AppConfig2=test2"` instead of `"AppConfig1=test" "AppConfig2=test2"`. The `config appsettings --slot-settings` requires separate strings delimited by spaces, and since a single string is passed, this command won't work.
> 
> this used to work before in all our pipelines using 2.39
> 
> anyway, we have found a workaround not to use an array variable as we have over 50+ config that we need to pass...

There is no changes on specifically to this command that can explain any regressions. Glad you found a work around.

**Comment by jiasli** [comment]
Duplicate of #23797

**Comment by sreagleeye** [comment]
@panchagnula I don't think this issue should be closed. There is something weird here.

All of our MS Hosted pipelines that use the Azure CLI task with PowerShell Core started to break after they upgraded their image to use Azure CLI version 2.40. I have narrowed the issue down to using to the `az webapp config appsettings set` command with PowerShell string variable.

**The following works:**
```
az webapp config appsettings set --settings "Key1=val" "Key2=other val" --name $resourceName --resource-group $resourceGroupName --subscription $subscription
```

**The following throws an error (due to the space in the value of Key2):**
```
$settingsPairs = '"Key1=val" "Key2=other val"'
az webapp config appsettings set --settings $settingsPairs --name $resourceName --resource-group $resourceGroupName --subscription $subscription
```

```
The command failed with an unexpected error. Here is the traceback:
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 557, in shell_safe_json_parse
  File "json\__init__.py", line 359, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 392, in update_app_settings
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 583, in shell_safe_json_parse
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse string as JSON:
val
Error detail: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 403, in update_app_settings
ValueError: not enough values to unpack (expected 2, got 1)
```

As others have mentioned, I have been using this command (within Azure pipelines as well as from my local computer's PowerShell) successfully previously. It's only when I upgraded my local Azure CLI to version 2.40 that I started to get this error.

**Comment by panchagnula** [comment]
@sreagleeye use the parent bug for updates/ discussions. As mentioned there were no changes specific to this command.

**Comment by RakeshMohanMSFT** [comment]
@sreagleeye Please see the explanation and solution at https://github.com/Azure/azure-cli/issues/23797#issuecomment-1238997338

**Comment by sreagleeye** [comment]
@RakeshMohanMSFT Thank you for that update. I had not seen that comment/solution. This is an issue across all commands that use array parameters. Using splatting as that comment specifies has fixed the issue.
