### ISSUE TITLE
application gateway rule create - priority required when not supported

### ISSUE THREAD

**Issue by abunnyuk** [Azure/azure-cli#23884]
## Describe the bug

Since version `2.40.0` commands to create rules on a non-v2 (WAF) Application Gateway fail stating that a priority is needed despite it only being supported on v2 gateways. The same commands have been working perfectly over the past 12 months with no script changes being made.

Environment summary generated by `az feedback` is from my local machine but it is also failing using pipeline task `AzureCLI@2` in image `windows-latest` with the following summary:

```
azure-cli                         2.40.0

core                              2.40.0
telemetry                          1.0.8

Extensions:
azure-devops                      0.25.0

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1
```

**Command Name**
`az network application-gateway rule create`

**Errors:**
```
the following arguments are required: --priority

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network application-gateway rule create --resource-group {} --gateway-name {} --address-pool {} --http-listener {} --http-settings {} --name {} --rule-type {} --no-wait`

## Expected Behavior

Create a rule on a non-v2 Application Gateway.

When attempting to run the same command with adding `--priority 10` the following error is then returned:

```
ERROR: (ApplicationGatewayFeatureCannotBeEnabledForSelectedSku) Application Gateway {} does not support Priority for the selected SKU tier WAF.
 
Supported SKU tiers are Standard_v2,WAF_v2.```
```

## Environment Summary
Windows-10-10.0.22622-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
account 0.2.3
azure-devops 0.25.0
cloud-service 0.2.0
datadog 0.1.1

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context

<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by abunnyuk** [comment]
In the meantime, to try to work around it, I'm trying to find a way to force pipeline task `AzureCLI@2` to use a different version rather than `latest` as this issue is blocking all infrastructure deployments.

Is there a simple way of achieving this?

**Comment by abunnyuk** [comment]
As a workaround I've added the following to the script which I've tested as working with image `windows-latest` but should also work for Linux build agents.

```
$targetAzVersion = "2.39.0"
pip3 install azure-cli==$targetAzVersion
```

This then results in the rule being successfully created.

**Comment by necusjz** [comment]
It should be a bug, I'll fix it then.
