### ISSUE TITLE
Docs on how to create firewall rule that allows all Azure services missing info

### ISSUE THREAD

**Issue by vmagelo** [Azure/azure-cli#23881]
I'm looking for equivalent of setting in Portal "allow all Azure Services". Is it just "0.0.0.0" or something different? I'm having trouble figuring it out.

Following the example `az postgres flexible-server firewall-rule create --resource-group testGroup --name testserver --start-ip-address 0.0.0.0`

give "expected string or bytes-like object" and doesn't configure the firewall.

Then I remembered doing it with Single server and tried 

`az postgres flexible-server firewall-rule create --resource-group testGroup --name testserver --start-ip-address 0.0.0.0 --rule-name AllowAllWindowsAzureIps`

This should be documented. Is the name "AllowAllWindowsAzureIps" specific or any name would do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d05c93e-2c3b-e576-665b-2fd529c7ed50
* Version Independent ID: 04c3f3c0-6a25-0b00-5b04-c37ad204222a
* Content: [az postgres flexible-server firewall-rule](https://docs.microsoft.com/en-us/cli/azure/postgres/flexible-server/firewall-rule?view=azure-cli-latest#az-postgres-flexible-server-firewall-rule-update)
* Content Source: [latest/docs-ref-autogen/postgres/flexible-server/firewall-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/postgres/flexible-server/firewall-rule.yml)
* Service: **postgresql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@vmagelo Thank you for reaching out to us, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@vmagelo its documented [here ](https://docs.microsoft.com/en-us/cli/azure/postgres/flexible-server/firewall-rule?view=azure-cli-latest#az-postgres-flexible-server-firewall-rule-create)`az postgres flexible-server firewall-rule create`
**--rule-name**
The name of the firewall rule. If name is omitted, default name will be chosen for firewall name. The firewall rule name can only contain 0-9, a-z, A-Z, '-' and '_'. Additionally, the firewall rule name cannot exceed 128 characters.

**Comment by vmagelo** [comment]
Okay, but First of all, if I'm looking at update command, and maybe as a user I won't think to look at create command. Or put link from one to the other if create command has more info.  

Second, I tried that and my point was that I *think* the special text "AllowAllWindowsAzureIps" is needed or else it just doesn't work. If you tried it and see it work, then I'll consider it my error. Thanks!

**Comment by RakeshMohanMSFT** [comment]
@vmagelo Rule names are not special text, its usedefined texts (see below).
![image](https://user-images.githubusercontent.com/49954584/198495941-dbdf71b0-3516-4bd2-abf7-e85dfe94b505.png)
