### ISSUE TITLE
az command returns 0 when failing

### ISSUE THREAD

**Issue by fuhuifang** [Azure/azure-cli#23880]
**Related command**
`az  extension show -n azure-ml-cli`

**Describe the bug**
When azure-ml-cli is not installed, we expect an error with exitcode 1. This works properly for 2.39 and older, but with 2.40, it returns 0.

**To Reproduce**
Run the following python script:
```python
import subprocess
subprocess.run(args=['pwsh', '-EncodedCommand', 'YQB6ACAAZQB4AHQAZQBuAHMAaQBvAG4AIABzAGgAbwB3ACAALQBuACAAYQB6AHUAcgBlAC0AYwBsAGkALQBtAGwA'])
```
Outputs
2.40
![image](https://user-images.githubusercontent.com/32152743/190076962-9fdaf8b0-54d4-4c84-a5e6-37d56c8debad.png)
2.39
![image](https://user-images.githubusercontent.com/32152743/190077035-e0587dbf-35f3-4326-b6cd-3003b4f68b1e.png)

**Expected behavior**
CompletedProcess(args=['pwsh', '-EncodedCommand', 'YQB6ACAAZQB4AHQAZQBuAHMAaQBvAG4AIABzAGgAbwB3ACAALQBuACAAYQB6AHUAcgBlAC0AYwBsAGkALQBtAGwA'], returncode=**1**)

**Environment summary**
Windows, python 3.8

**Additional context**
Similar to https://github.com/Azure/azure-cli/issues/23808

**Comment by yonzhan** [comment]
route to CXP team

**Comment by yjm607** [comment]
Hi Yong, will there be an IcM ticket filed for this issue? It is affecting all customers of the Substrate Intelligence AI platform and the Shrike library.

**Comment by jiasli** [comment]
This looks like some issue with PowerShell.

Say we have the same `test.cmd` and `test.ps1`:

```
python -c "exit(1)"
```

The exit code is correct when they are invoked directly:

```
PS D:\> ./test.cmd ; echo $LASTEXITCODE

D:\>python -c "exit(1)"
1
PS D:\> ./test.ps1 ; echo $LASTEXITCODE
1
```

However, when invoked by `pwsh.exe`, they return different result:

```
PS D:\> pwsh -Command "./test.cmd" ; echo $LASTEXITCODE

D:\>python -c "exit(1)"
1
PS D:\> pwsh -Command "./test.ps1" ; echo $LASTEXITCODE
0
```

If `test.ps1` contains 

```powershell
Exit 1
```

It works as expected:

```
PS D:\> ./test.ps1 ; echo $LASTEXITCODE
1
PS D:\> pwsh -Command "./test.ps1" ; echo $LASTEXITCODE
1
```

Azure CLI switched to `az.ps1` in https://github.com/Azure/azure-cli/pull/23514, leading to this problem.

**Comment by jiasli** [comment]
On contrary, `cmd.exe` works as expected:

```
D:\>cmd.exe /c "test.cmd" & echo %ErrorLevel%

D:\>python -c "exit(1)"
1
```

So does Bash:

```
user2@DESKTOP-A79F1:~$ ./test.sh ; echo $?
1
user2@DESKTOP-A79F1:~$ bash -c "./test.sh" ; echo $?
1
```

**Comment by jiasli** [comment]
We will revert the change in #24015

**Comment by saisankargochhayat** [comment]
Also facing the same issue, looking forward to the next release fixing this issue!

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/milestone/122  Build to Cloud Shell: 10/10/2022 Official Release: 10/12/2022
