### ISSUE TITLE
SQL DB import/export no-wait option

### ISSUE THREAD

**Issue by michelletaal-shell** [Azure/azure-cli#23885]
**Related command**

az sql db import
az sql db export

**Is your feature request related to a problem? Please describe.**

az sql db import/export commands can take so long to run that it will time out the CLI or DevOps pipeline leveraging AzureCLI

**Describe the solution you'd like**

a no-wait flag as described in https://github.com/Azure/azure-cli/issues/1528

**Describe alternatives you've considered**

a no-wait flag should ideally be added as a global option

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@michelletaal-shell Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@michelletaal-shell  The above PR has been filed to address this. It is currently under review. Please let me know if you have any questions in the meantime.
