### ISSUE TITLE
[az resource tag] command change casing for ApplicationInsights name

### ISSUE THREAD

**Issue by jvilimek** [Azure/azure-cli#23898]
**Related command**

`az resource tag`

**Describe the bug**

Calling `az resource tag --ids “.../microsoft.insights/components/appinsightname”` with a different casing than the AppInsights component currently have will change the casing to the called one.

**To Reproduce**

Having an Application Insights resource with

- id: “/subscriptions/…/resourcegroups/ResourceGroup/providers/microsoft.insights/components/AppInsightName”
- name: “AppInsightName”
- applicationId: “AppInsightName”
- tags: {}

and calling

`az resource tag --ids “/subscriptions/…/resourcegroups/resourcegroup/providers/microsoft.insights/components/appinsightname” --tags tagName=tagValue` (note the lower casing)

will cause the following change
- id: “/subscriptions/…/resourcegroups/ResourceGroup/providers/microsoft.insights/components/AppInsightName”
- name: “**appInsightname**”
- applicationId: “**appInsightname**”
- tags: {“tagName”:”tagValue”}

The change of the tags is OK, but there is one unexpected change and that is the change in casing of the applicaiton insights component **name** and **applicationId**. It is **not described in the documentation** and IMHO a bug.

**Expected behavior**

There are basically 2 options how to handle it IMHO:

- not changing the name+applicationId properties
- or throwing “not found” (exception/http404) as the resourceId casing differs.

**Environment summary**

```text
azure-cli                         2.37.0 *

core                              2.37.0 *
telemetry                          1.0.6 *

Extensions:
account                            0.2.3
azure-devops                      0.25.0
costmanagement                     0.2.1
dataprotection                     0.3.0
log-analytics                      0.2.2
managementpartner                  0.1.3
portal                             0.1.2
resource-graph                     2.1.0
scheduled-query                    0.5.0
storage-preview                    0.8.3

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\JVilimek\.azure\cliextensions'

Python (Windows) 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 22:57:10) [MSC v.1929 32 bit (Intel)]
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@josephkwchan, @jennyhunter-msft Please help us out here. The PUT operation used to update appinsights is causing the issue.

**Comment by jennyhunter-msft** [comment]
This is by design.

From our [public documentation:](https://learn.microsoft.com/azure/azure-resource-manager/management/resource-name-rules)
"When using various APIs to retrieve the name for a resource or resource group, the returned value may have different casing than what you originally specified for the name... Always perform a case-insensitive comparison of names."

This is because we preserve the most recently specified casing by the user. We will look into updating the documentation to be clearer on that.

**Comment by jvilimek** [comment]
> This is by design.
> 
> From our [public documentation:](https://learn.microsoft.com/azure/azure-resource-manager/management/resource-name-rules) "When using various APIs to retrieve the name for a **resource** or **resource group**, the returned value may have different casing ...

@jennyhunter-msft thanks for the answer. I am a bit confused, can you please explain more? The documentation you mentioned is related to **resource name**  (or resource group name). Now the bug I have described is about Application Insights **properties**.name and ApplicationId. When I check the Azure portal, the resource itself has still the name with the old casing, but when we run the kusto query, the casing of AppName was changed.

The bug manifests by calling `az resource tag` over an **application insights** resource. If you call the very same on some other resource type (sql server, virtual machine,...) the casing of the name of the resource is not affected. Thus the bug is related to App Insights resource.

I have updated the description to be more specific. Hope this helps.

PS: And more specifically the bug is about the fact, that calling `az resource tag` should affect only tags and should not change any other name, property, whatever.

**Comment by jennyhunter-msft** [comment]
That's interesting. I don't see a properties.name in the [REST API schema](https://learn.microsoft.com/rest/api/application-insights/components/get?tabs=HTTP) for that resource type. Only the top-level "name" property which should be the resource name.

**Comment by jvilimek** [comment]
@jennyhunter-msft thanks for comment. Yes, I found this interesting too. Is it interesting enough to re-open the bug? Would be much appreciated!

**Comment by jvilimek** [comment]
@jennyhunter-msft  maybe it's a low priority bug but still it would be great to keep it open, WDYT?

**Comment by jennyhunter-msft** [comment]
@jvilimek - Just to confirm, is the main problem here that the casing for the name property doesn't match the stored URI? Given that the APIs are explicitly case insensitive, is there a specific aspect of this that is causing issues with your logic?

**Comment by jvilimek** [comment]
@jennyhunter-msft sorry for not reaching you earlier. The main issue here is, that an `az cli` command that should chnage just the tag is changing also other properties. As you can see in the screenshot from kusto query this change affects data from AppInsights (the `appName`):

![image](https://user-images.githubusercontent.com/16001792/194371400-bddccce6-c572-4984-aed7-00b24159aadd.png)

(for query see the original description of the bug)
