### ISSUE TITLE
az snapshot not using the latest API version 2022-03-02

### ISSUE THREAD

**Issue by ramankumarlive** [Azure/azure-cli#23895]
**Related command**

az snapshot create

**Is your feature request related to a problem? Please describe.**

The change request is related to the feature request (link below) to use the API version 2022-03-02 for the Compute resources for supporting Premium SSD v2. Snapshot support for Premium SSD v2 does not work with CLI. We are launching Premium SSD v2 in GA Ignite and this will become a blocker. Premium SSD v2 is also part of Satya's 

https://github.com/Azure/azure-cli/issues/22732

We forgot to update the snapshot resource to use the latest API version 2022-03-02

**Describe the solution you'd like**

Update the az snapshot commands to use the latest API version 2022-03-02

**Describe alternatives you've considered**

There are no alternatives

**Additional context**
Here is an example script that is failing currently

subscriptionId="dd80b94e-0463-4a65-8d04-c94f403879dc"
diskName="ddsnaptestvm1_DataDisk_0"
resourceGroupName="DDSnapshotsTesting"
snapshotName="ddsnaptestvm1_DataDisk_0_snapshot4"
az account set --subscription $subscriptionId
diskId=$(az disk show -n $diskName -g $resourceGroupName --query "id" --output tsv)
az snapshot create -g $resourceGroupName -n $snapshotName --source $diskId --incremental true

(BadRequest) Minimum api-version of 2022-03-02 required to create snapshots on ultra or premiumV2 disks.
Code: BadRequest
Message: Minimum api-version of 2022-03-02 required to create snapshots on ultra or premiumV2 disks.

**Comment by ramankumarlive** [comment]
@wangzelin007 as per our chat raised this issue.

**Comment by yonzhan** [comment]
@wangzelin007 @zhoxing-ms for awareness

**Comment by PARADISSEEKR** [comment]
Hi @ramankumarlive  `(BadRequest) 'Snapshot on Ultra or PremiumV2 disks' is not supported for this subscription/region`
Which region support this feature？
