### ISSUE TITLE
Why does this command needs Public Internet access?

### ISSUE THREAD

**Issue by abu3lia** [Azure/azure-cli#23899]
We are trying to copy an image to another subscription (both subs are in UK South), however, we have an ARM policy that prevents Public access to Storage accounts. When running "_az image copy --source-resource-group rg-imagemgmt --source-object-name xxxx --target-location uksouth --target-resource-group xxxx --target-subscription xxxx_" we received the following error:

`Message: Resource 'xxxx' was disallowed by policy. Policy identifiers: '[{'policyAssignment':{'name':'Disallow-Public-Network-Access-Blob-Storage-Account','id':'/subscriptions/xxx/providers/Microsoft.Authorization/policyAssignments/Disallow-Public-Network-Access-Blob-Storage-Account'},'policyDefinition':{'name':'Disallow-Public-Network-Access-Blob-Storage-Account','id':'/subscriptions/xxx/providers/Microsoft.Authorization/policyDefinitions/Disallow-Public-Network-Access-Blob-Storage-Account'}},{'policyAssignment':{'name':'Disallow-Public-Network-Access-Storage-Account','id':'/subscriptions/xxx/providers/Microsoft.Authorization/policyAssignments/Disallow-Public-Network-Access-Storage-Account'},'policyDefinition':{'name':'Disallow-Public-Network-Access-Storage-Account','id':'/subscriptions/xxx/providers/Microsoft.Authorization/policyDefinitions/Disallow-Public-Network-Access-Storage-Account'}}]'.`

How does this command works exactly? and why it needs Public Internet access?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c81f4c-ac29-2f6e-96f2-b6fba3ef3098
* Version Independent ID: 2a24cd5b-8798-a175-5bde-7d2850bf9015
* Content: [az image](https://docs.microsoft.com/en-us/cli/azure/image?view=azure-cli-latest#az-image-copy)
* Content Source: [latest/docs-ref-autogen/image.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/image.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
> 'policyDefinition':{'name':'Disallow-Public-Network-Access-Blob-Storage-Account',

@abu3lia Please note that this command is blocked by the custom policy under you subscription, so you may need to consider disabling or bypassing this policy yourself

**Comment by abu3lia** [comment]
> > How does this command works exactly? and why it needs Public Internet access?
> 
> It executes storage related commands to copy images, such as `storage account generate-sas` and `storage blob copy start`.

Thanks for the reply. However, I just need your input regarding the need for Public internet access with "az image copy"?

**Comment by abu3lia** [comment]
As tested, generating the SAS is not possible unless enabling the Public Access. Thanks!
