### ISSUE TITLE
az functionapp config appsettings set fails with 'int' object is not iterable when large number of string separated settings.  Works fine in V 2.39 but not V 2.40

### ISSUE THREAD

**Issue by robrow01** [Azure/azure-cli#23891]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.40.0

**Related command**
az functionapp config appsettings set --name $appServiceName --resource-group $resourceGroup --settings $settings --output none --slot $slotName

**Describe the bug**
Fails with large number of space separated strings in the form of key=value.  Even batching the settings into smaller chunks causes the same error after the first couple of batches are ran.

**To Reproduce**
Run above command against a function app with a large number of settings and using key vault pointers for a number of them.  Our service has 76 settings.

**Expected behavior**
Should work.  Use to work just fine in previous versions of the CLI.

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@robrow01 Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@robrow01 We tried with 55 values and we are unable to reproduce this issue, perhaps its something to do with the way you are passing the values. Can you share the parameters you are passing with some sample values, having integers or --debug trace with us.

![image](https://user-images.githubusercontent.com/49954584/190309059-915bec87-f41c-474b-a0b1-9f46e05a8c94.png)

**Comment by santhoshtns** [comment]
@RakeshMohanMSFT,
I have similar issue (passing the array parameter in the command) with another command after upgrading to az cli to v2.40.0.

The issue can be reproduced with the below example. And works with cli version 2.39.0
`$Permissions = @('get', 'list')
az keyvault set-policy --name $KvName --object-id $objectId --secret-permissions $Permissions`

Running the below command works fine.
`az keyvault set-policy --name $KvName --object-id $objectId --secret-permissions **get list**`

**Comment by robrow01** [comment]
@RakeshMohanMSFT Try with more values.  Our one app service actually has 76.

**Comment by mjhilton** [comment]
@santhoshtns there seems to be an issue here that exactly matches your scenario: https://github.com/Azure/azure-cli/issues/23890

**Comment by RakeshMohanMSFT** [comment]
@robrow01 Can you look into this? https://github.com/Azure/azure-cli/issues/23797#issuecomment-1238997338
