### ISSUE TITLE
az acr create ends in storage account not found

### ISSUE THREAD

**Issue by ritazh** [Azure/azure-cli#2389]
Using the following command, trying to create a registry:
`az acr create -g $RESOURCE_GROUP -n $REGISTRY_NAME -l eastus`

Error:
```
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
 "message": "Storage account <omitted>was not found in subscription <omiited>."
}
```
Same issue if a storage account is provided in the command.

az --version
```
azure-cli (2.0.0)
```
This is also reproducible with `azure-cli (2.0.0+dev)` @sozercan

**Comment by sivagms** [comment]
@ritazh We have a fix for this and deploying soon

**Comment by jpoon** [comment]
@sivagms ETA?

**Comment by sivagms** [comment]
ETA is early next week. Will update this thread.

**Comment by jpoon** [comment]
@sivagms is there a workaround for deploying ACR in the meantime? I've tried deploying through the portal, az/azure cli, ARM quick start templates and all fail with this error.

**Comment by jpoon** [comment]
After a debugging session with @sivagms, he attributed it to using a subscription with a lot of storage accounts. I re-attempted deployment in a different subscription and that worked.

**Comment by sivagms** [comment]
The fix is deployed to all regions. 
@ritazh  Could you check if this solves the issue..

**Comment by ritazh** [comment]
@sivagms Just tested my original script. It works now! 🎉  Closing this issue.
