### ISSUE TITLE
Refenced material links

### ISSUE THREAD

**Issue by BertusV** [Azure/azure-cli#23905]
Hi documenters,

Overall, I think you are doing a fantastic job keeping the documentation up to date.  Well done.

I'm trying to get an example of the referenced document "@"path/linkedservice.json"".   I think it will improve the documentation if links are provided to these types of references.  They are not always easy to track down.

In this case I can't get this commend "az synapse linked-service set --workspace-name testsynapseworkspace \
  --name testlinkedservice --file @"path/linkedservice.json" " to work and I believe the issue is possibly in the formatting of the document.

While the command executes without any error the Authorisation Headers never appear on the linked service.

Regards,
Bertus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fedd821-b852-d1b7-c5dc-4b75e230dd4d
* Version Independent ID: fb5a4dd8-e499-0109-84c4-c5b89d27d0f6
* Content: [az synapse linked-service](https://docs.microsoft.com/en-us/cli/azure/synapse/linked-service?view=azure-cli-latest#az-synapse-linked-service-set)
* Content Source: [latest/docs-ref-autogen/synapse/linked-service.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/synapse/linked-service.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@BertusV Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@BertusV Here is a sample for storage account as linked service, there are too many external linked services that can be mapped, having samples of all of them are difficult, but the basic template for all of them should be similar as below.
```

{
  "properties": {
    "type": "AzureBlobStorage",
    "typeProperties": {
      "connectionString": "DefaultEndpointsProtocol=https;AccountName=issue23887***;EndpointSuffix=core.windows.net;AccountKey=********;"
    }
  }
}
```

**Comment by BertusV** [comment]
Would you happen to have an example of using a https auth header?

**Comment by RakeshMohanMSFT** [comment]
@BertusV I believe you are looking for this.

```
{
  "properties": {
    "description": "Issue23905HttpServer",
    "annotations": [],
    "type": "HttpServer",
    "typeProperties": {
      "url": "http://localhost:1981/",
      "enableServerCertificateValidation": true,
      "authenticationType": "Basic",
      "userName": "Issue23905username",
      "password": {
        "type": "SecureString",
        "value": "Issue23905pwd"
      },
      "authHeaders": {
        "APIKey": {
          "type": "SecureString",
          "value": "Issue23905ApiKey"
        }
      }
    }
  }
}
```
