### ISSUE TITLE
Azure Synapse Pipeline Deployment using ARM Template through Azure CLI

### ISSUE THREAD

**Issue by Abhinavgundapaneni** [Azure/azure-cli#23916]
## Describe the bug
I have a pipeline published in Azure Synapse studio. I tried to export as template and deploy this template in an another workspace using Azure CLI (version 2.40.0). But the command is failing with a generic error. I checked to import the pipeline in the Synapse Studio UI and it worked.

**Command Name**
`az deployment group create`

**Errors:**
```
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"\"\r\n  }\r\n}"}]}}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- Create pipeline in synapse studio. 
- Click in export template.
- Run the below CLI command in local powershell terminal to deploy the template in another synapse studio.
- `az deployment group create --name {DEPLOYMENT_NAME} --resource-group {RG_NAME} --template-file {path to deploymentTemplate JSON file}`

## Expected Behavior
It must create the desired Synapse pipeline in synapse studio.
## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
application-insights 0.1.16

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by Abhinavgundapaneni** [comment]
Let me know if you need any more information to better resolve this issue.

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
＠Abhinavgundapaneni Could you please send the debug log *(add `--debug` parameter) and the ARM template file to me by email? My email address is Zhou.Xing@microsoft.com

**Comment by zhoxing-ms** [comment]
This is the error message returned by the REST service. It seems that the information is not clear enough:

> {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"\"\r\n  }\r\n}"}]}}

Therefore, it needs the help from ARM team to investigate the root cause of this error
**'x-ms-correlation-request-id': '17f82463-1b89-4393-9b01-a477892276d3'**

**Comment by RakeshMohanMSFT** [comment]
@zhoxing-ms I am looking into it.
