### ISSUE TITLE
Support for CustomIpPrefix (BYOIP) GA+ features

### ISSUE THREAD

**Issue by brianlehr** [Azure/azure-cli#23921]
### Related command

az network custom-ip prefix create
az network custom-ip prefix update

### Resource Provider

Microsoft.Network

### Description of Feature or Work Requested

Hello CLI team, aim here is to add the new functionality that Custom IP Prefix has.

1. BYOASN (with an -asn parameter)
2. Granular Commissioning (with a -nointernetadvertise parameter)
3. Regional advertisements (with a -geo parameter)
4. BYOIP over ExpressRoute (with an -expressrouteadvertise parameter)
5. BYOIPv6 (using "parent" and "child" customipprefix resources

### Minimum API Version Required

2022-05-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/blob/network-2022-05-01/specification/network/resource-manager/Microsoft.Network/stable/2022-05-01/customIpPrefix.json

### Target Date

2022-10-15

### Additional context

Examples for items 1-4:

```
az network custom-ip prefix create
(other arguments)
--asn <int>

```
```
az network custom-ip prefix update
(other arguments)
--state {commission}
--no-internet-advertise
```

```
az network custom-ip prefix create
(other arguments)
--geo <string>
```

```
az network custom-ip prefix create
(other arguments)
--expressrouteadvertise
```

For item 5, note the new "customIpPrefixParent" and "childCustomIpPrefixes" aspects of the customipprefix swagger.  This is because for IPv6 (and eventually IPv4), you would create a "parent" (global, advertised by WAN) range and "children" (regional, advertised by SLB in a region) ranges.  For parent ranges, they should be able to be provisioned (with an "az network custom-ip prefix create" command) that does not include a zone.  For children ranges, they should be able to be provisioned (same "create" command) but without the signedmessage or authorization message parameters, but with the zone.  These child ranges must also use the --cip-prefix-parent command.

**Comment by yonzhan** [comment]
network feature

**Comment by brianlehr** [comment]
Thanks @yonzhan -- let me know any questions you have about the requirements.

**Comment by necusjz** [comment]
@brianlehr If my understanding is correct, are we planning to release GA this time? (Previously, we have been releasing Preview).

**Comment by brianlehr** [comment]
This feature has been in GA since March 2022 :-)  These are additions to the already GA feature.

**Comment by brianlehr** [comment]
This feature has been in GA since March 2022 :-)  These are additions to the already GA feature.

**Comment by necusjz** [comment]
@brianlehr
A small question here: I saw the enum values for `commissionedState` in Swagger are as follows:
- https://github.com/Azure/azure-rest-api-specs/blob/611405a0f1cb5761fe273ec1691925e6b2669ced/specification/network/resource-manager/Microsoft.Network/stable/2022-05-01/customIpPrefix.json#L393-L402

But the valid values of it don't seem to match them:
![image](https://user-images.githubusercontent.com/12371639/194833206-167b7831-ed54-4210-819c-aafa722cda35.png)
Is that as expected? Thanks.

**Comment by gitlwh** [comment]
@brianlehr  @necusjz That is expected. What command you are using? if you want to commission it, commissioned would be invalid for the command.
