### ISSUE TITLE
Not able to connect to cluster when using Azure CLI

### ISSUE THREAD

**Issue by strange2x** [Azure/azure-cli#23923]
## Describe the bug
When am trying to connect to an AKS cluster using Azure CLI, its getting this error. 

**Command Name**
`az aks get-credentials`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
API version 2022-06-01 does not have operation group 'managed_clusters'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acs/_client_factory.py", line 27, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
  File "/usr/lib/python3/dist-packages/azure/mgmt/containerservice/_container_service_client.py", line 492, in managed_clusters
    raise ValueError("API version {} does not have operation group 'managed_clusters'".format(api_version))
ValueError: API version 2022-06-01 does not have operation group 'managed_clusters'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Linux-5.19.0-1-amd64-x86_64-with-glibc2.34, Debian GNU/Linux bookworm/sid
Python 3.10.7
Installer: DEB

azure-cli 2.40.0

Extensions:
azure-devops 0.24.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by strange2x** [comment]
@yonzhan Will it be routed automatically or should I be doing some steps to route to CXP team?

**Comment by yonzhan** [comment]
automatically with CXP Attention label

**Comment by navba-MSFT** [comment]
@strange2x Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@strange2x I wasn't able to reproduce this issue at my end. I had a look at the below details from your environment:

```
Linux-5.19.0-1-amd64-x86_64-with-glibc2.34, Debian GNU/Linux bookworm/sid
Python 3.10.7
Installer: DEB
```

This is not the official Azure CLI published by Microsoft. Please see https://github.com/Azure/azure-cli/issues/19640.

**Action Plan:**
For now, please follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt to install Azure CLI on stable/GA versions of Debian, like 11 Bullseye, instead of sid.

https://wiki.debian.org/DebianUnstable

>Sid is forever doomed to being unstable.

Hope this helps.

**Comment by navba-MSFT** [comment]
@strange2x I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@strange2x The action is currently pending on you see the above suggestion. Please feel free to reopen this thread, if you need any further assistance on this. We would be happy to help.

**Comment by eswues** [comment]
I used 'install script (any)' option. but still cannot get auto-completion sorted

**Comment by strange2x** [comment]
I had changed the version to a lower one and it worked then and now I have changed the machine and its working perfectly
