### ISSUE TITLE
AZ build file error 

### ISSUE THREAD

**Issue by musaddiqueans** [Azure/azure-cli#23927]
## Describe the bug

**Command Name**
`az bicep build`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bicep build -f {}`

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.40.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@musaddiqueans Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@musaddiqueans Can you please share more details of the error you are getting? we are not seeing any issues with the command at our end with similar environments az cli 2.40.0, bicep cli 0.10.61
