### ISSUE TITLE
az servicebus namespace update min-tls-version not working

### ISSUE THREAD

**Issue by jkdf-nnit** [Azure/azure-cli#23926]
az servicebus namespace update --namespace ****** -- resource-group ***** --minimum-tls-version 1.2
unrecognized arguments: --minimum-tls-version 1.2

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@jkdf-nnit Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@jkdf-nnit I was able to update the tls version using the parameter `--min-tls`. Please run the below command and check if that helps.

>az servicebus namespace update --resource-group MyRgName --name MySBName **--min-tls** 1.2

More Info [here](https://learn.microsoft.com/en-us/cli/azure/servicebus/namespace?view=azure-cli-latest#az-servicebus-namespace-update).

**Comment by navba-MSFT** [comment]
@jkdf-nnit I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@jkdf-nnit The action is currently pending on you to try the above action plan. Please feel free to reopen this thread, if you need any further assistance on this. We would be happy to help.
