### ISSUE TITLE
The new feature "Show status during deployment for linux apps" gets stuck waiting

### ISSUE THREAD

**Issue by DavidZidar** [Azure/azure-cli#23925]
## Describe the bug
**Command Name**
`az webapp deployment source config-zip`

The command gets stuck waiting seemingly forever for some build to finish even though the zip already deployed just fine.
```
WARNING: Getting scm site credentials for zip deployment
WARNING: Starting zip deployment. This operation can take a while to complete ...
WARNING: Deployment endpoint responded with status code 202
/ Running...

| Running...

\ Running...
BuildRequestReceived...          
BuildRequestReceived...          -
BuildRequestReceived...          Success! 
BuildPending...                  

BuildPending...                  /
BuildPending...                  Success! 
BuildInProgress...               

BuildInProgress...               |

BuildInProgress...               \

BuildInProgress...               -

BuildInProgress...               /
```

"BuildInProgress..." then just repeated for more than 5 minutes before I aborted, normally I can deploy in 15-30 seconds.

## To Reproduce
I deployed to a stopped slot which my scripts starts up after the deploy is completed, I'm not sure if that is the cause. I did start the slot manually after a couple of minutes and verified that the deployment was indeed working but Azure CLI just kept on printing "BuildInProgress..."

The reason I deploy to a stopped slot is so I don't start an old version of the site since it's just going to be replaced with a new version anyway.

## Expected Behavior
Deployment should not get stuck waiting for something that is already completed.

## Environment Summary
```
Linux-5.10.0-16-amd64-x86_64-with-glibc2.31, Debian GNU/Linux 11 (bullseye)
Python 3.10.5
Installer: DEB

azure-cli 2.40.0
```

## Additional Context
It's a zip deploy, there shouldn't be a build step. The Kudu deployment API lists the following times:
```json
"received_time" : "2022-09-17T19:46:01.6550694Z",
"start_time" : "2022-09-17T19:46:02.945671Z",
"end_time" : "2022-09-17T19:46:03.9086207Z",
"last_success_end_time" : "2022-09-17T19:46:03.9086207Z",
```
It seems to me the deployment completed in just over 2 seconds so Azure CLI has no reason waiting for over 5 minutes.

I believe it was #23464 that introduced this unwanted behavior.

**Comment by DavidZidar** [comment]
A command line flag to skip this behavior would be an acceptable solution to me.

**Comment by mcalthrop** [comment]
> route to CXP team

@yonzhan How do we do this?

It's causing a mess of logs in our CI environment, so we need to be able to disable it ASAP.

**Comment by yonzhan** [comment]
webapp service team can help with

**Comment by mcalthrop** [comment]
> webapp service team can help with

Yep - so how do we draw this issue to their attention?

**Comment by DavidZidar** [comment]
@mcalthrop I wrote a comment in the PR that implemented this feature, I hope it helps draw attention to this.

**Comment by panchagnula** [comment]
@seligj95 this is the feedback from the new deployment status API implemented. @DavidZidar the reason this status was added because, completion of Zip deploy doesn't necessarily mean the full operation is complete (example build etc) & the app is ready. This status was added just to ensure the progress of the full deployment process is visible to the customer & once completed the app is ready & runs as expected.

**Comment by DavidZidar** [comment]
@panchagnula I get the intent but it is not working right.

**Comment by panchagnula** [comment]
> @panchagnula I get the intent but it is not working right.

Yes, completely understand. Sorry for the inconvenience caused. @JasonFreeberg FYI.

**Comment by mcalthrop** [comment]
> @seligj95 this is the feedback from the new deployment status API implemented. @DavidZidar the reason this status was added because, completion of Zip deploy doesn't necessarily mean the full operation is complete (example build etc) & the app is ready. This status was added just to ensure the progress of the full deployment process is visible to the customer & once completed the app is ready & runs as expected.

> @panchagnula I get the intent but it is not working right.

@panchagnula: @DavidZidar has nailed it. Have a look at the original issue raised.

Our CI logs are getting spammed with hundreds of lines of this:

```
WARNING: Getting scm site credentials for zip deployment
WARNING: Starting zip deployment. This operation can take a while to complete ...
WARNING: Deployment endpoint responded with status code 202
/ Running...

| Running...

\ Running...
BuildRequestReceived...          
BuildRequestReceived...          -
BuildRequestReceived...          Success! 
BuildPending...                  

BuildPending...                  /
BuildPending...                  Success! 
BuildInProgress...               

BuildInProgress...               |

BuildInProgress...               \

BuildInProgress...               -

BuildInProgress...               /

BuildInProgress...               |

BuildInProgress...               \

BuildInProgress...               -

BuildInProgress...               /

BuildInProgress...               |

BuildInProgress...               \

BuildInProgress...               -

BuildInProgress...               /

BuildInProgress...               |

BuildInProgress...               \

BuildInProgress...               -

BuildInProgress...               /

BuildInProgress...               |

BuildInProgress...               \

BuildInProgress...               -

BuildInProgress...               /
```

We need an option to disable the above.

**Comment by mcalthrop** [comment]
@panchagnula @StrawnSC @zhoxing-ms Thank you for the fix!

**Comment by DavidZidar** [comment]
@panchagnula I think I have figured out why it gets stuck. It seems to be waiting for the site to start before continuing, but that will never happen if the slot is stopped... but surprisingly it doesn't even happen when the slot is already running unless an external web request comes in and starts it up. So it just sits there waiting forever. I hope a new version is released soon.
