### ISSUE TITLE
App Service Plans Not Listed in Output

### ISSUE THREAD

**Issue by jaredbrogan** [Azure/azure-cli#23938]
## Describe the bug

**Command Name**
`az resource list`

**Errors:**
```
n/a
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az resource list -g "$resourceGroup" | jq .[].id | grep -i serverfarms`

## Expected Behavior
List out the created app service plan IDs.

## Environment Summary
```
Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.40.0

Extensions:
account 0.2.3
authV2 0.1.1
azure-devops 0.25.0
kusto 0.5.0
support 1.0.3

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context
The issue here is that there is a difference in output due to the somewhat recent change in case sensitivity for certain resource IDs.

The command `az resource list -g "$resourceGroup" | jq .[].id | grep -i serverfarms` only lists out ASPs that contain a capitalized "F" in the word "server**F**arms" within the resource ID. Whereas the command `az appservice plan list -g $resourceGroup | jq .[].id` lists out resources with a lowercase "F" in the word "server**f**arms" within the resource ID.

The interesting thing is that I *don't* have an issue with the second command due to the fact that it converts "server**F**arms" to the current standard of "server**f**arms" by default.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@jaredbrogan Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@jaredbrogan Please run the below command to List app service plans.

>az appservice plan list

**Examples:**
>az appservice plan list --query "[?sku.tier=='Free']"
>az appservice plan list --query "[?hostingEnvironmentProfile.name=='<ase-name>']"
>az appservice plan list [--resource-group]

More Info [here](https://learn.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest#az-appservice-plan-list). Please let me know if this helps.

**Comment by jaredbrogan** [comment]
> @jaredbrogan Please run the below command to List app service plans.
> 
> > az appservice plan list
> 
> **Examples:**
> 
> > az appservice plan list --query "[?sku.tier=='Free']"
> > az appservice plan list --query "[?hostingEnvironmentProfile.name=='']"
> > az appservice plan list [--resource-group]
> 
> More Info [here](https://learn.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest#az-appservice-plan-list). Please let me know if this helps.

Hi @navba-MSFT, 
As my post already stated, I'm aware of the suggested command. What I'm calling to attention is the fact that the `az resource list` command does not accurately output all App Service Plans when the ID doesn't specifically contain the word `serverFarms` with a capitalize letter "F".

**Comment by navba-MSFT** [comment]
@jaredbrogan Thanks for getting back and clarifying the ask. I would like to do a repro at my end and debug this further. I don't have any resources with serverfarms (lower case f). May I know how did you create those server**f**arms with lowercase **f** ?

**Comment by jaredbrogan** [comment]
When using the portal, it will create a resource with an upper case F. Using either the azure cli or the latest azurerm terraform provider, they will create a resource with a lower case f.

_However_, it would now appear that the issue has been fixed...?
This screenshot was taken the day this issue was posted:
![image](https://user-images.githubusercontent.com/42228088/191563649-d016f260-c60c-4f6f-b00e-32e17307dd53.png)


This was taken moments ago:
![image](https://user-images.githubusercontent.com/42228088/191563124-0249ad5b-1c3b-47c0-ba0a-7ad9d4b43fc4.png)

The only difference between the 2 resources were the time they were provisioned, as I had deleted them after the screenshot was taken yesterday. The deployment methods remained the same.

Seems like something may have changed along the way on Azure's end?

**Comment by navba-MSFT** [comment]
@jaredbrogan Thanks for getting back. There hasn't been any changes done from our end. I tried creating the service plan from Azure CLi, though the type returned in smaller case **f**, while querying the plan it did list with capitalized **F**. So I am unable to reproduce this issue.

**Created using CLI:**
>az appservice plan create -g navbatest99 -n navbaMyPlan --is-linux --number-of-workers 2 --sku S1

**Output:**
{
  "isXenon": false,
  "kind": "linux",
  "kubeEnvironmentProfile": null,
  "location": "eastus",
  "maximumElasticWorkerCount": 2,
  "maximumNumberOfWorkers": 0,
  "name": "navbaMyPlan",
  "numberOfSites": 0,
  "numberOfWorkers": 2,
  **"type": "Microsoft.Web/serverfarms"**   <------ Smaller case **f**
}


**Queried using az resource list:**
{
    "ID": "/subscriptions/XXXXXXXX/resourceGroups/XXXXXX/providers/Microsoft.Web/server**F**arms/navbaMyPlan",
    "Name": "navbaMyPlan"
  }
  

If you are still able to reproduce this issue do let us know.

**Comment by jaredbrogan** [comment]
At this point, it seems to be resolved, so you may close this out. I'll post again if I run into this once more. Thanks!

**Comment by navba-MSFT** [comment]
@jaredbrogan Thanks for the update. We will now proceed with archival of this GitHub issue. If issue resurfaces in future, please feel free to reopen this thread. We would be happy to help.
