### ISSUE TITLE
Cannot use entity variable in az storage entity insert using Azure CLI 2.40.0

### ISSUE THREAD

**Issue by rubenmiddel** [Azure/azure-cli#23932]
**Related command**
az storage entity insert

**Describe the bug**
Using a Powershell variable for inserting a Storage Entity results in error using Azure CLI 2.40. Same command was working fine in Azure CLI 2.37.0. Running the same command without using a variables also works fine.

**To Reproduce**
1. Open a PowerShell window and set variables $storageAccount, $tableName, $partitionKey, $rowKey and $content to valid values
2. Run the commands below and notice the error

`$entity = @()`
`$entity += "PartitionKey=$partitionKey"`
`$entity += "RowKey=$rowKey"`
`$entity += "Content=$content"`
`az storage entity insert -t $tableName --account-name $storageAccount --auth-mode login -e $entity`

**Actual behavior**
incorrect usage: entity requires: RowKey PartitionKey

**Expected behavior**
An entity is inserted to the table storage. 

**Environment summary**
CLI version 2.40.0

**Additional context**
-

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
Similar with #23797. Please see detailed info in #23797 's comments

**Comment by rubenmiddel** [comment]
@evelyn-ys Thank you, using `@entity` instead of `$entity` indeed fixes the issue!
