### ISSUE TITLE
Dependency on azure-mgmt-authorization 0.61.0 which is more than two years old

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-cli#23933]
The Azure CLI package still depends on `azure-mgmt-authorization` which was released in August 2020 according the release history of the package [1]. The current version of `azure-mgmt-authorization` is 2.0.0 which was released in September 2021.

With `azure-mgmt-authorization` 2.0.0, various CLI commands fail with `'RoleAssignmentsOperations' object has no attribute 'config'`.

See, for example: https://github.com/Azure/azure-cli/issues/22231 and https://github.com/Azure/azure-cli/issues/21349

> [1] https://pypi.org/project/azure-mgmt-authorization/#history

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by glaubitz** [comment]
Any news on this?

**Comment by jiasli** [comment]
Will migrate to `azure-mgmt-authorization` Track 2 in https://github.com/Azure/azure-cli/issues/23372.
