### ISSUE TITLE
Need a way to get custom script extension logs

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#2394]
Authoring and using a custom script extension from the CLI is an inherently iterative process.  Getting the stderr/stdout for the script is an essential part of the process, but getting these logs is very hard to do.  A top-level command to fetch/tail the stderr or stdout would be extremely helpful.

**Comment by yugangw-msft** [comment]
Unless you use the extension with VMSS, you can consider "az vm run-command invoke" which routes to the API built upon the custom script extension, and the command does return you the stdout and stderr. The service API is still in preview and looks a bit immature, but should fulfill the ask here. So give it a try

**Comment by yugangw-msft** [comment]
Fix was committed for https://github.com/Azure/custom-script-extension-linux/issues/107

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please let us know if this issue if it is still a concern.
