### ISSUE TITLE
New Load Balancer health probe parameter

### ISSUE THREAD

**Issue by thisisanniefang** [Azure/azure-cli#23957]
### Related command

az network lb probe create [--probeThreshold]
az network lb probe update [--probeThreshold]

### Resource Provider

Microsoft.Network/loadbalancers

### Description of Feature or Work Requested

Feature request to add new optional parameter --probeThreshold to the following commands:
az network lb probe create
az network lb probe update

Due to a longstanding known issue regarding the property --threshold, otherwise known as numberOfProbes in ARM, and "Unhealthy threshold" in Portal, we are supporting a new property known as probeThreshold that will functionally replace the old property numberOfProbes. This is avoid a breaking change. We will eventually go through the appropriate process to deprecate --threshold, however, for the moment we would just like --probeThreshold to be added as a new parameter. The new parameter is available in API versions 2022-05-01 and above.

### Minimum API Version Required

2022-05-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/20001

### Target Date

2022-10-31

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by thisisanniefang** [comment]
@yonzhan just checking in - any ETA for when the new parameter will be ready?

**Comment by necusjz** [comment]
@thisisanniefang You can track it by the right "Milestone", it means we plan to deliver it in 11/01/2022.

**Comment by thisisanniefang** [comment]
@necusjz @ZengTaoxu apologies for the delayed ask as I saw that the PR has already been merged. Is it possible to add a warning to the same commands when the property --probeThreshold is specified, as such? Happy to create a new issue if preferred.

“Please note that the parameter --probeThreshold is currently in preview and is not recommended for production workloads. For most scenarios, we recommend maintaining the default value of 1 by not specifying the value of the property.”

**Comment by necusjz** [comment]
@thisisanniefang We can only add it in the next sprint/release (around 12/06), sorry for that.

**Comment by necusjz** [comment]
> 

@thisisanniefang It's better to summarize your 2 requirements into a new issue:
1. https://github.com/Azure/azure-cli/pull/18136#issuecomment-1293756273
2. https://github.com/Azure/azure-cli/issues/23957#issuecomment-1296375923
