### ISSUE TITLE
passing list to --rules isn't working

### ISSUE THREAD

**Issue by saicharan8** [Azure/azure-cli#23959]
$ruleIds = [System.Collections.ArrayList]@('921130','921140')
az network application-gateway waf-policy managed-rule rule-set add --policy-name $Name -g $ResourceGroupName --type $disabledRule.ruleSetType --version $disabledRule.ruleSetVersion --group-name $ruleGroup.ruleGroupName --rules $ruleIds

Error Message: The override Rule '921130 921140' is unknown for RuleGroup 'REQUEST-921-PROTOCOL-ATTACK' for Application Gateway Firewall in context ''.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69735220-baba-8209-3360-beafe13138cb
* Version Independent ID: d0cfd033-613d-12e0-4de3-cdea1972fcc0
* Content: [az network application-gateway waf-policy managed-rule rule-set](https://learn.microsoft.com/en-us/cli/azure/network/application-gateway/waf-policy/managed-rule/rule-set?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/application-gateway/waf-policy/managed-rule/rule-set.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/application-gateway/waf-policy/managed-rule/rule-set.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by saicharan8** [comment]
Code: ApplicationGatewayFirewallUnknownRuleOverride
Message: The override Rule '921110 921130' is unknown for RuleGroup 'REQUEST-921-PROTOCOL-ATTACK' for Application Gateway Firewall in context ''.

**Comment by necusjz** [comment]
Does `--rules 921130 921140` work? If yes, please temporarily take it as a workaround.

**Comment by saicharan8** [comment]
> Does `--rules 921130 921140` work? If yes, please temporarily take it as a workaround.

yes this is working

**Comment by navba-MSFT** [comment]
@saicharan8 Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
