### ISSUE TITLE
ERROR: Cannot convert the literal 'xxxxxx' to the expected type 'Edm.Binary'

### ISSUE THREAD

**Issue by dawwa** [Azure/azure-cli#23968]
**Related command**
```powershell
az ad app create --display-name "MyApp" --key-display-name Default --key-type Password --key-value "xxxxxx" --sign-in-audience AzureADMultipleOrgs
```

**Describe the bug**
Got the error of "ERROR: Cannot convert the literal 'xxxxxx' to the expected type 'Edm.Binary'."

**Additional context**
We were with the following command and it had been working fine previously, however seems recently this way is deprecated? and when I tried the new command, we face this issue.

```powershell
az ad app create --display-name "MyApp" --credential-description Default --password "xxxxxx" --available-to-other-tenants true
```

Related KB: https://learn.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-create

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
The Microsoft Graph migration is documented at https://learn.microsoft.com/en-us/cli/azure/microsoft-graph-migration

As described in the doc, `az ad app create` no longer has `--password` argument:

> - Remove `--password` and `--credential-description`. Use `az ad app credential reset` to let Graph service create a password for you (https://github.com/Azure/azure-cli/issues/20675)

For `az ad app create ... --key-value "xxxxxx"`, could you share several starting bytes of `"xxxxxx"` and the `--debug` log?

**Comment by jiasli** [comment]
As discussed offline, for `--key-value "xxxxxx"`, `"xxxxxx"` should be the public key of a certificate, not password.

To let Graph service generate a password, use `az ad app credential reset`.
