### ISSUE TITLE
az webapp auth update --action

### ISSUE THREAD

**Issue by willem-plug-io** [Azure/azure-cli#23975]
az webapp auth update --action seem to have different behavior and syntax than stated in the documents.
When I look at the docs this is what optional values I can give with the --action flag:
"--action
accepted values: AllowAnonymous, LoginWithAzureActiveDirectory, LoginWithFacebook, LoginWithGoogle, LoginWithMicrosoftAccount, LoginWithTwitter"

I used the value "LoginWithAzureActiveDirectory" in a script that I use for my Azure DevOps pipeline.

This is the error I get:
"ERROR: az webapp auth update: 'LoginWithAzureActiveDirectory' is not a valid value for '--unauthenticated-client-action'. Allowed values: RedirectToLoginPage, AllowAnonymous, RejectWith401, RejectWith404."

I have effort with understanding why the flag is named differently in the error than in the script. Also I dont get why the value is not accepted.

Hope I made my issue clear and you can use my feedback to improve the docs.
Sorry if I made a mistake in my understanding of the technology.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aeb196c8-e408-8563-26ba-5c3ae6e38c48
* Version Independent ID: 5f150c9a-e142-2fd7-fe84-b298dc83fd02
* Content: [az webapp auth](https://learn.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/auth.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/auth.yml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@willem-plug-io Thank you for reaching out, we are looking into it. Can you please share your environment details using az --version command?

**Comment by willem-plug-io** [comment]
Thanks Rakesh,
Sorry for my delayed response.
When running az --version I get the following output:

**Comment by RakeshMohanMSFT** [comment]
@willem-plug-io Can you share the exact command and parameters you are using, of course not the real values of the parameters

**Comment by willem-plug-io** [comment]
az webapp auth update  -g $resourcegroup `
        -n $webAppName `
        --enabled true `
        --action LoginWithAzureActiveDirectory `
        --aad-client-id $appId `
        --aad-client-secret $appregSecretPassword `
        --aad-token-issuer-url "https://sts.windows.net/$tenantId/"

**Comment by RakeshMohanMSFT** [comment]
@willem-plug-io I unable to reproduce this issue at our end. Please look at the screenshots below.

![image](https://user-images.githubusercontent.com/49954584/192497381-cbefff91-4aed-4e59-8061-079c2ee1296e.png)

![image](https://user-images.githubusercontent.com/49954584/192497960-57e36b79-b07b-489d-9c5b-4037ad4ac784.png)

Are you able to reproduce this issue if you run in your local machine?

**Comment by willem-plug-io** [comment]
Thanks for the quick follow up.
At this moment I am not able to reproduce this, because of several issues.
But this helps a lot showing me this command is supposed to work.

**Comment by willem-plug-io** [comment]
If I use the exact command you use I get the following error:
"az webapp auth update: 'LoginWithAzureActiveDirectory' is not a valid value for '--unauthenticated-client-action'"

As you might understand I did not use the flag '--unauthenticated-client-action', because I used the same command as you(with my own parameters).

I used this in my AzDevops pipeline. I am not in the position to run this locally at the moment.

Hope this clarifies something.

**Comment by RakeshMohanMSFT** [comment]
@willem-plug-io --unauthenticated-client-action seems to be missing in the [documentation](https://learn.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest#az-webapp-auth-update)? It looks like a deprecated feature?

**Comment by ebibibi** [comment]
This behavior is repro here.

## command
$authCommand = "az webapp auth update -g $resourceGroupName -n $webAppName --enabled true --action LoginWithAzureActiveDirectory --aad-allowed-token-audiences https://$webAppName.azurewebsites.net/.auth/login/aad/callback --aad-client-id $clientId --aad-client-secret $clientSecret --aad-token-issuer-url https://sts.windows.net/$tenantId/"      
Invoke-Expression $authCommand

## result
az webapp auth update: 'LoginWithAzureActiveDirectory' is not a valid value for '--unauthenticated-client-action'. Allowed values: RedirectToLoginPage, AllowAnonymous, Return401, Return404, Return403.

## version
azure-cli                         2.63.0

core                              2.63.0
telemetry                          1.1.0

Extensions:
authV2                             0.1.3

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\mebisuda\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)] 

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by ebibibi** [comment]
I believe this document is wrong.

https://learn.microsoft.com/en-us/cli/azure/webapp/auth?view=azure-cli-latest#az-webapp-auth-set

"az webapp auth update --help" looks like return correct document.

az webapp auth update --help
The behavior of this command has been altered by the following extension: authV2

Command
    az webapp auth update : Update the authentication settings for the webapp in the v2 format.   

Arguments
    --action --unauthenticated-client-action          : The action to take when an unauthenticated
                                                        client attempts to access the app.  Allowed
                                                        values: AllowAnonymous, RedirectToLoginPage,
                                                        Return401, Return403, Return404.
