### ISSUE TITLE
AZ GROUP CREATE NOT WORKING AFTER SUCCESSFUL LOGIN

### ISSUE THREAD

**Issue by othukeodoko** [Azure/azure-cli#23973]
## Describe the bug

**Command Name**
`az group create`

**Errors:**
```
Please run 'az login' to setup account.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group create --name {} --location {}`

## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by othukeodoko** [comment]
The issue has been fixed. It was a system time zone setting issue.

**Comment by cceneag** [comment]
👍
