### ISSUE TITLE
Azure Firewall Network rule creation with an ip prefix

### ISSUE THREAD

**Issue by saisujithreddym** [Azure/azure-cli#23980]
![Picture1](https://user-images.githubusercontent.com/6829181/191843038-07cf0744-870c-4e8b-ab1b-74be8272c9f5.png)
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az network firewall network-rule create

**Describe the bug**

Looks like CLI is not taking an ipprefix in the network rules during the firewall creation

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
Cannot reproduce and I have tried almost the same parameters as yours, but works:
```text
1. az network firewall create -n ethan-af -g ethan-rg
2. az network firewall network-rule create -n ethan-rule -c ethan-cc -f ethan-af -g ethan-rg --dest-addr * --destination-ports * --protocols Any --priority 300 --source-addresses 10.0.0.0/8 --action Allow

{
  "description": null,
  "destinationAddresses": [
    "*"
  ],
  "destinationFqdns": [],
  "destinationIpGroups": [],
  "destinationPorts": [
    "*"
  ],
  "name": "ethan-rule",
  "protocols": [
    "Any"
  ],
  "sourceAddresses": [
    "10.0.0.0/8"
  ],
  "sourceIpGroups": []
}
```
