### ISSUE TITLE
az container create - should have an option to create an instance in a stopped state

### ISSUE THREAD

**Issue by sdg002** [Azure/azure-cli#23998]
**Related command**

az container create

**Is your feature request related to a problem? Please describe.**

I have Python file in a Docker image. I would like to run this through an Azure Container instance.  The Dockerfile is as follows:

```dockerfile
FROM python:3.9
WORKDIR /code
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD [ "python", "./hello.py" ]

```
I am creating the container instance using the CLI option `restart-policy Never`.  I want control the schedule of the execution using the CLI `az container start`.

However, when I deploy the image created by the above Dockerfile, the image goes into a running state immediately. This is undesirable because I no longer have control on the schedule.

**Describe the solution you'd like**

I would like the `az container create` CLI to have an additional argument which allows me to specify the initial "running" state of the container.  Example:
`ac container create --name my-container --resource-group rg-my-group --image someimage   --restart-policy never --state stopped`

**Describe alternatives you've considered**
I am yet to try the following, but I think it might work.

- Remove the `CMD` command from the `Dockerfile`. 
- By doing so, I stop the container from immediately starting my script at the very beginning.
- I can then use the CLI `az container exec /hello.py --name my-container --resource-group rg-my-group` as per my desired schedule

**Additional context**
Nil.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@sdg002 Looks like the underlying API doesn't support this. The alternative that you've suggested is a great way to approach this.

Feel free to upvote [this feature request](https://feedback.azure.com/d365community/idea/a336647a-5de6-ec11-a81b-6045bd7ac9f9) to support this and once supported on the API, the Azure CLI would be updated to add support for this as well.

**Comment by sdg002** [comment]
Upvoted.  I hope I will not have to chase 2 separate teams inside MS to get this done.

**Comment by PramodValavala-MSFT** [comment]
@sdg002 Thanks! Since this is more of a service side request, once supported there, it should come down to the clients as well. Closing this to prevent duplicate discussions.
