### ISSUE TITLE
[az functionapp config appsettings] multiple settings added as one if keyvault references

### ISSUE THREAD

**Issue by abushokry** [Azure/azure-cli#24008]
**Related command**
az functionapp config appsettings set  --settings $string-array

**Describe the bug**
Pushing multiple app settings using the command **_az functionapp config appsettings set  --settings $string-array _** adds all settings as one setting only if the first setting is a keyvault reference. For example, if the settings string array passes to the --settings argument looks like "key1=@Microsoft.KeyVault(secreturi=xxx)" "key2=@Microsoft.KeyVault(secreturi=yyy)" the azure function app will end up having one setting as follows: 
`
  {
    "name": "key1",
    "slotSetting": false,
    "value": "@Microsoft.KeyVault(secreturi=xxx) key2=@Microsoft.KeyVault(secreturi=yyy)"
  }
`

**To Reproduce**
consider the following code:

```
$functionAppSettings = @()
$x_name = "TESTKEY1"
$x_value = "@Microsoft.KeyVault(SecretUri=https://xxx)"

$y_name = "TESTKEY2"
$y_value = "@Microsoft.KeyVault(SecretUri=https://yyy)"

$z_name = "TESTKEY3"
$z_value = "@Microsoft.KeyVault(SecretUri=https://zzz)"
$functionAppSettings += @("$x_name=$x_value")
$functionAppSettings += @("$y_name=$y_value")
$functionAppSettings += @("$z_name=$z_value")

az functionapp config appsettings set --resource-group myRG --name myFA --settings $functionAppSettings

```

**Expected behavior**
I should end up having three keys in the function app as follows
`  
{
    "name": "TESTKEY1",
    "slotSetting": false,
    "value": "@Microsoft.KeyVault(SecretUri=https://xxx)"
  },
{
    "name": "TESTKEY2",
    "slotSetting": false,
    "value": "@Microsoft.KeyVault(SecretUri=https://yyy)"
  },
{
    "name": "TESTKEY3",
    "slotSetting": false,
    "value": "@Microsoft.KeyVault(SecretUri=https://zzz)"
  },
`

**Environment summary**

azure-cli                         2.40.0

core                              2.40.0
telemetry                          1.0.8

Extensions:
azure-devops                      0.25.0
interactive                        0.4.5

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\aaa\.azure\cliextensions'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]

**Additional context**
we've been using the above code for over a year without problems. We believe the latest 2.40.0 update has broken it

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@abushokry When using the `$` sign, you are passing the collection as a single input (list of array items in new lines, in this case) and instead should use [splatting](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.2) to pass them as a collection itself.

So, a command like this should work

```ps1
az functionapp config appsettings set --resource-group myRG --name myFA --settings @functionAppSettings
```

**Comment by abushokry** [comment]
Thanks @PramodValavala-MSFT that worked indeed. It's interesting though as passing the collection with a $ was working for long time until we've upgraded to cli 2.40

**Comment by PramodValavala-MSFT** [comment]
@abushokry Glad to hear that! Closing this issue.

As for why the behavior has changed, I will check with the concerning team to see if there were any changes in this regard. As far as PowerShell is concerned, the way to pass collections is clear though.
