### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sg31011991** [Azure/azure-cli#24001]
## Describe the bug

**Command Name**
`az version`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az version -o={}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0 *
```

**Comment by yonzhan** [comment]
Please provide detailed error log.
