### ISSUE TITLE
Updating Batch account to use encryption key in Key Vault fails

### ISSUE THREAD

**Issue by tompaana** [Azure/azure-cli#24007]
**Related command**

```plaintext
az batch account set \
    --resource-group-name <resource group name> \
    --name <Batch account name> \
    --encryption-key-source Microsoft.KeyVault \
    --encryption-key-identifier <key identifier>
```
**Describe the bug**

The following error is returned:

```plaintext
(MissingRequiredProperty) A required property was not specified in the request body.
RequestId:********-****-****-****-************
Time:2022-09-19T11:32:03.4833177Z
Code: MissingRequiredProperty
Message: A required property was not specified in the request body.
RequestId:********-****-****-****-************
Time:2022-09-19T11:32:03.4833177Z
Target: BatchAccount
Exception Details:      (PropertyName) keyVaultProperties
        Code: PropertyName
        Message: keyVaultProperties     (PropertyPath) properties.encryption.keyVaultProperties
        Code: PropertyPath
        Message: properties.encryption.keyVaultProperties
```

**To Reproduce**

1. Prerequisites:
    - An existing Batch account
    - An existing Key Vault containing the key as described in [Configure customer-managed keys for your Azure Batch account with Azure Key Vault and Managed Identity](https://learn.microsoft.com/azure/batch/batch-customer-managed-key#generate-a-key-in-azure-key-vault)
    - Batch account authorized to read keys in Key Vault
1. Run the `az batch account set` command with the parameters listed above

**Expected behavior**

Batch account successfully updated to use the encryption key.

**Environment summary**

The same error observed when testing locally on Windows machine and in Azure DevOps using Microsoft-hosted Linux build agent (Ubuntu 20.04).

Windows Azure CLI version info:

```plaintext
azure-cli                         2.31.0 *

core                              2.31.0 *
telemetry                          1.0.6 *

Extensions:
aks-preview                       0.5.41
storage-preview                    0.3.0

...

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
```

Build agent Azure CLI version info:

```plaintext
azure-cli                         2.39.0 *

core                              2.39.0 *
telemetry                          1.0.6 *

Extensions:
azure-devops                      0.25.0

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.10.5 (main, Jul 29 2022, 03:26:59) [GCC 9.4.0]
```

**Additional context**

I briefly inspected the following files and the recent history of their changes in source:

- [Azure/azure-cli/src/azure-cli/azure/cli/command_modules/batch/custom.py](https://github.com/Azure/azure-cli/blob/main/src/azure-cli/azure/cli/command_modules/batch/custom.py)
- [Azure/azure-sdk-for-python/sdk/batch/azure-mgmt-batch/azure/mgmt/batch/models/_models_py3.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/batch/azure-mgmt-batch/azure/mgmt/batch/models/_models_py3.py)

I couldn't see any obvious bugs in the code, but there is a fair chance I missed them - or the bug can be somewhere else.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by dpwatrous** [comment]
Just a quick update from the Batch team: we were able to reproduce this issue and we're tracking it internally. Hoping to get this fix into the December release.

**Comment by SaurabhSharma-MSFT** [comment]
@dpwatrous Do you have any latest insights.
