### ISSUE TITLE
Property to manage OCSP revocation check on client certificate

### ISSUE THREAD

**Issue by 3quanfeng** [Azure/azure-cli#24011]
**Related command**
az network application-gateway create 
az network application-gateway update

**Is your feature request related to a problem? Please describe.**
az command support on the new property to manage client cert revocation options
PS support the new property can be referred from https://github.com/Azure/azure-rest-api-specs/pull/20301

**Describe the solution you'd like**
Cx should be able to set the verifyClientRevocation options via az command
Cx is able to create/update the sslProfile by creating/updating ApplicationGatewayClientAuthConfiguration to enable client cert revocation via OCSP

**Describe alternatives you've considered**
N/A

**Additional context**
Swagger Change: https://github.com/Azure/azure-rest-api-specs/pull/20301/files
PS change: https://github.com/Azure/azure-powershell/pull/19515

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
As limited bandwidth (only 2 days until dev close), we have to develop it in the early of the next sprint.
