### ISSUE TITLE
List Everything

### ISSUE THREAD

**Issue by kbocock-krg** [Azure/azure-cli#24010]
Hello trying to setup alerts in terraform. How do I list everything for a resource like an app insights instance? Examples seem overly complex vs kubectl commands. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c722777b-9914-5c57-b869-a92bb16e159e
* Version Independent ID: 19b7e250-35b0-6e41-6662-b86791cf4c78
* Content: [az monitor metrics](https://learn.microsoft.com/en-us/cli/azure/monitor/metrics?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/monitor/metrics.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/monitor/metrics.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by kairu-ms** [comment]
Hi @kbocock-krg, please try `az monitor metrics list -h` for list command help.
