### ISSUE TITLE
az cli 2.40.0; az network application-gateway update errors ' selected SKU tier WAF_v2 must have a valid WAF policy or configuration' when changing WAF tier

### ISSUE THREAD

**Issue by manikg321** [Azure/azure-cli#24029]
## Describe the bug

**Command Name**
`az network application-gateway update`

**Errors:**
```
(ApplicationGatewayFirewallNotConfiguredForSelectedSku) Application Gateway /subscriptions/Subscription_ID/resourceGroups/MC_xyz-rg_xyz-aks_eastus/providers/Microsoft.Network/applicationGateways/xyz-aks-apgtw with the selected SKU tier WAF_v2 must have a valid WAF policy or configuration
Code: ApplicationGatewayFirewallNotConfiguredForSelectedSku
Message: Application Gateway /subscriptions/Subscription_ID/resourceGroups/MC_xyz-rg_xyz-aks_eastus/providers/Microsoft.Network/applicationGateways/xyz-aks-apgtw **with the selected SKU tier WAF_v2 must have a valid WAF policy or configuration**

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
By the way, the application-gateway is 'autogenerated' with kubernetes, so the resource group  naming is MC_xyz-rg_xyz-aks_eastus.

- _Put any pre-requisite steps here..._
- `az network application-gateway update --name {} --resource-group {} --sku {}`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.27, Ubuntu 18.04.6 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.40.0

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context

![image](https://user-images.githubusercontent.com/81321710/192578801-f5beab99-28ea-4503-91c0-064171040fdb.png)

**Comment by manikg321** [comment]
Same error on 

> az network application-gateway rewrite-rule set create --resource-group --gateway-name --name

**Comment by manikg321** [comment]
Same error on 

> az network application-gateway rewrite-rule create --resource-group --gateway-name  --rule-set-name --name --response-headers

**Comment by manikg321** [comment]
Same error on 

> az network application-gateway update --name --resource-group --set sku.tier=WAF_v2

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by manikg321** [comment]
@necusjz / @yonzhan  If there is any work around using az cli 2.40.0 commands can you please let me ASAP, I am in need of it. Thanks!

**Comment by necusjz** [comment]
@manikg321 Thanks for your detailed user scenarios and I'll jump into them.

Here could be a workaround:
https://www.reddit.com/r/AZURE/comments/wvgtlg/waf_policy_application_gateway_and_rest_api/

**Comment by manikg321** [comment]
> @manikg321 Thanks for your detailed user scenarios and I'll jump into them.
> 
> Here could be a workaround: https://www.reddit.com/r/AZURE/comments/wvgtlg/waf_policy_application_gateway_and_rest_api/

Same error. Works on older az cli versions, but not on az cli 2.40.0.

**Comment by necusjz** [comment]
> > @manikg321 Thanks for your detailed user scenarios and I'll jump into them.
> > Here could be a workaround: https://www.reddit.com/r/AZURE/comments/wvgtlg/waf_policy_application_gateway_and_rest_api/
> 
> Same error. Works on older az cli versions, but not on az cli 2.40.0.

I do think you're right: https://stackoverflow.com/a/73475665/19233978. And how about this: https://stackoverflow.com/a/73460058/19233978

**Comment by necusjz** [comment]
As it's a breaking change from service side, we can do nothing about that. But here's a workaround for creating an application gateway with a WAF policy:
```text
1. az network public-ip create -g {rg} -n pubip1 --sku Standard
2. az network application-gateway waf-policy create -n waf1 -g {rg}
3. az network application-gateway create -g {rg} -n ag1 --sku WAF_v2 --public-ip-address pubip1 --priority 1001 --waf-policy waf1
```
