### ISSUE TITLE
Argument passthrough `--` stops working in PowerShell since 2.40.0

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#24034]
**Describe the bug**
There is a regression in Azure Quantum CLI extension introduced by Azure CLI latest release (2.40.0). 

The command below, which used to work with 2.39.0, is now complaining about "ERROR: unrecognized arguments: --submit-config-file".

```
> az quantum job submit --target-id echo-qci -- --submit-config-file .\SubmissionConfigFile.json
cli.knack.cli: Command arguments: ['quantum', 'job', 'submit', '--target-id', 'echo-qci', '--submit-config-file', '.\\SubmissionConfigFile.json', '--debug']
```

Our CLI extension passes through those arguments, which follow `--`, to invoke our executable underneath the CLI. With this regression, this argument pass through mechanism is not working any more.

`az storage copy` also supports `--` notation (https://github.com/Azure/azure-cli/pull/20702) and it stops working:

```
> az storage copy -s source_file -d destination_container_url -- --block-size-mb=0.25 --check-length --debug
cli.knack.cli: Command arguments: ['storage', 'copy', '-s', 'source_file', '-d', 'destination_container_url', '--block-size-mb=0.25', '--check-length', '--debug']
```

**Comment by jiasli** [comment]
Tested with a simple `test.ps1`:

```
echo $args
```

Apparently, `--` is discarded by PowerShell:

```
> ./test.ps1 a -- b
a
b
```

**Comment by navba-MSFT** [comment]
Removing CXP attention label since this was created internally by the CLI team

**Comment by shenyingjun** [comment]
@yonzhan / @jiasli Has this issue been fixed yet?

**Comment by yonzhan** [comment]
This issue should be fixed already, please verify.
