### ISSUE TITLE
AZ CLI extension not installing

### ISSUE THREAD

**Issue by famemo-paasdev** [Azure/azure-cli#24046]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az extension add --source ~/anextension-0.0.1-py2.py3-none-any.whl

**Describe the bug**
The customer is downloading the .whl to the local drive and installing from there but so far with no luck and no error messages. have tried the both Debug and Verbose but it’s not giving any error information, The ISE keeps spinning for a while then I have to force close ISE by End Task.

I have tried using in the VM and It’s working but When I am trying from proxy, it’s fails without giving me any future exception details. One thing I want to ask is, Please correct me If I am going on the wrong direction. I have downloaded the .whl to my local drive and trying to add the extension from my local drive, why It’s failing? What is there to relate it to proxy? Why it’s going to network?

**To Reproduce**
When running the command from behind a proxy. the install does not complete nor does it provide any useful feedback. Seems to be stuck in a waiting/spinning state. 

**Expected behavior**
When installing locally it should not need to go to the internet. It should install without issues. 

**Environment summary**
The Script:
az extension add --source 'C:\Temp\AzAlias\account-0.2.2-py3-none-any.whl'
az extension add --source 'C:\Temp\AzAlias\alias-0.5.2-py2.py3-none-any.whl'
 
Tools Version:
PSVersion                      5.1.19041.1682                                                                 
PSEdition                      Desktop                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                        
BuildVersion                   10.0.19041.1682                                                                
CLRVersion                     4.0.30319.42000                                                                
WSManStackVersion              3.0                                                                            
PSRemotingProtocolVersion      2.3                                                                             
SerializationVersion           1.1.0.1   
Python 3.9.0

**Additional context**
![image](https://user-images.githubusercontent.com/55082437/192795217-49c93504-3e76-45dd-817d-83348dff80e8.png)

**Comment by kairu-ms** [comment]
Hi @famemo-paasdev, did you try the latest version (2.40.0) of azure-cli?
