### ISSUE TITLE
Set runbook to draft state

### ISSUE THREAD

**Issue by angryconsultant** [Azure/azure-cli#24047]
Is there no way to set an existing runbook to draft state? I cant work how to replace content "az automation runbook replace-content" without manually setting the runbook to draft in the Azure Portal

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cbb98a7a-2739-73ec-f20b-03367f919215
* Version Independent ID: 3125cea7-248b-9ba0-f304-248b2c766edc
* Content: [az automation runbook](https://learn.microsoft.com/en-us/cli/azure/automation/runbook?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/automation/runbook.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/automation/runbook.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@angryconsultant We are looking into it and get back to you for any additional information.

**Comment by PramodValavala-MSFT** [comment]
@angryconsultant Looks like running the replace content command does change the status to `In edit` already. Do you see an error when trying the same?

**Comment by angryconsultant** [comment]
I get following error if I do not set the Runbook to draft before the replace-content code is running. When runbook is in draft it works. 

`ERROR: (BadRequest) Runbook draft is not in edit state.
Code: BadRequest
Message: Runbook draft is not in edit state.
`


```
az automation runbook replace-content \
                      --automation-account-name $(AutomationAccount) \
                      --resource-group $(ResourceGroupName) \
                      --content @./GetPCConsumption.ps1 \
                      --name "AzurePlan" \
                      --verbose
```

**Comment by angryconsultant** [comment]
I solved the issue and I had to run this before: 

`az automation runbook update`

Can you please clarify the documenation about the `update` so that its clear that the only thing it does is to set the Runbook to draft. Draft is not mentioned in the documentation

**Comment by angryconsultant** [comment]
Its running in a Microsoft Hosted DevOps Pipeline

```
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.208.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
```

**Comment by angryconsultant** [comment]
This might have been an issue caused by a encoding error of a dash in my code in the runbook. However it still a weird error message stating "Runbook draft is not in edit state" when there is such error.

**Comment by PramodValavala-MSFT** [comment]
@angryconsultant Could you give an example of the erroneous dash that you mention so that I could investigate further?
