### ISSUE TITLE
Unable to connect Azure ADLS from Unix

### ISSUE THREAD

**Issue by sanu-hack** [Azure/azure-cli#24043]
## Describe the bug

**Command Name**
`az dls fs test`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


SellInSellOut/tempnew/3400
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
PermissionError: SellInSellOut/tempnew/3400
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az dls fs test --account {} --path {}`

## Environment Summary
```
Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-redhat-7.6-Maipo
Python 2.7.5
Shell: bash

azure-cli 2.0.70

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@sanu-hack Thanks for reaching out to us and reporting this issue. I see that you are using an older version of AzCLI. Could you please update to the [most recent version ](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli) of AzCLI and check if you are still facing this issue ? Awaiting your reply.

**Comment by sanu-hack** [comment]
Thanks for your email . I will upgrade my CLI and test it .

**Comment by navba-MSFT** [comment]
@sanu-hack Thanks for your reply. I shall wait for the update from you.

**Comment by navba-MSFT** [comment]
@sanu-hack I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by sanu-hack** [comment]
Hello,
Thanks for your response.when I tried to upgrade my cli version there was
an peer certificate issue that is not allowing me to connect over the
internet. Trying to get it resolved now .

Regards,
Saravana Kumar B

**Comment by navba-MSFT** [comment]
@sanu-hack Thanks for getting back. Please keep me posted about the update.

**Comment by navba-MSFT** [comment]
@sanu-hack I wanted to do quick follow-up to check if you had a chance to look into this. Please let us know if you had any updates. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@sanu-hack The action is currently pending on you to upgrade to the [most recent version ](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli)of AzCLI. Please feel free to reopen this thread, if you still face the same issue after upgrading. We would be happy to help.
