### ISSUE TITLE
When creating an asset filter, "--tracks" is not an optional parameter as the docs suggest

### ISSUE THREAD

**Issue by Copennin** [Azure/azure-cli#24059]
As the title suggests. Running the command without the parameter --tracks, in the CLI (both Azure and Linux), results in the following error:

_(BadRequest) Properties can not be null.
Code: BadRequest
Message: Properties can not be null._

Example command, produces the unwanted results:
` az ams asset-filter create -a AccountName -g ResourceTestGroup-n test-filter --asset-name Asset123`

Indicating that --tracks, or whatever 'Properties' should be, _is required_ should fix the issue and help alleviate confusion.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa7f2730-5663-8321-f78f-71abe984e552
* Version Independent ID: f20b5b83-2c59-d76f-5c0d-0cd91b9e63a5
* Content: [az ams asset-filter](https://learn.microsoft.com/en-us/cli/azure/ams/asset-filter?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ams/asset-filter.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ams/asset-filter.yml)
* Service: **media-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@akucer For some reason we are not sending request body. Please help us look into it.

**Comment by akucer** [comment]
Closing as won't fix as Azure Media Services was retired on 6/30/2024 (https://aka-ms/ams-retirement)
