### ISSUE TITLE
Support For Routemaps

### ISSUE THREAD

**Issue by arganapathy** [Azure/azure-cli#24061]
### Resource Provider

Microsoft.Network

### Description of Feature or Work Requested

1. Need cli support for VnetLocalRouteOverrideCriteria in command to create static routing configuration. 
2. Need new commands to put/get/delete/list RouteMap resources on VirtualHub
3. Need new commands getinboundroutes and getoutboundroutes, 
4. Need To be able to specify routemap uri as associated inbound/outbound routemap in commands to create/update hubvnetconnection, ergatewayconnection, vpngwconnection. These fields should also be shown when connection object is returned
All changes are specd in swagger update below.

### Minimum API Version Required

2023-03-15

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/20091/files

### Target Date

2023-03-15

**Comment by yonzhan** [comment]
network feature

**Comment by necusjz** [comment]
@arganapathy Please clarify the mapping between the 4 features and their **related commands**.

**Comment by arganapathy** [comment]
Here is a detailed list of commands to implement
[routemapclicommands.docx](https://github.com/Azure/azure-cli/files/10376513/routemapclicommands.docx)
