### ISSUE TITLE
Maximum Burst for Elastic Plan cannot be set above 20 with Azure CLI

### ISSUE THREAD

**Issue by vhhughes** [Azure/azure-cli#24064]
## Describe the bug

**Command Name**
`az functionapp plan update`

**Errors:**
```
Usage error: --max-burst is expected to be between 0 and 20 (inclusive)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create an Elastic Plan (1, 2, or 3) and create a Function app in it.
- Try to run `az functionapp plan update --name {} --resource-group {} --max-burst 100`

## Expected Behavior
It should succeed. 

I can set the slider for "Maximum Burst" in the Azure Portal for my EP3 plan on the "Scale out (App Service Plan)" blade to 100. It successfully saves that. But the Azure CLI does not allow me to do the same.

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0

Extensions:
application-insights 0.1.16

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@vhhughes Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@vhhughes I am able to reproduce this issue at my end. This PR https://github.com/Azure/azure-cli/pull/21398 was filed to address this issue previously. But seems like the issue still exist. I am discussing this with the product owners. We have no ETA for the fix just yet. 

Until the fix is released please use the below AzCLI command to address this issue:

>az login
>az account set --subscription "XXX-XXXX-XXXX-XXXX"
>az resource update --ids /subscriptions/XXX-XXXX-XXXX-XXXX/resourceGroups/MyRGName/providers/Microsoft.Web/serverfarms/MyPlanName --set properties.maximumElasticWorkerCount=**100**

Hope this helps.

**cc: @panchagnula**

**Comment by navba-MSFT** [comment]
@vhhughes I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@vhhughes Please try the below workaround for now and if you still face the same issue with the below command, feel free to reopen this thread. We would be happy to help.

>az resource update --ids /subscriptions/XXX-XXXX-XXXX-XXXX/resourceGroups/MyRGName/providers/Microsoft.Web/serverfarms/MyPlanName --set properties.maximumElasticWorkerCount=100
