### ISSUE TITLE
Simplify archiving Append Blob and Page Blob with CLI

### ISSUE THREAD

**Issue by fhryo-msft** [Azure/azure-cli#24067]
The asks on archiving Append Blob and Page Blob Archive grow. However, Archive doesn't support Append Blob and Page Blob natively today. The only workaround is that customers need to convert Append Blob and Page Blob to block blobs then tier to and from Archive. We need to simplify the conversion process to increase more cost savings on Append Blob and Page Blob. It would be great to keep such conversion behavior consistent with Azcopy.

**Comment by yonzhan** [comment]
storage feature
