### ISSUE TITLE
Conditional Access policy error inside the python virtual environment

### ISSUE THREAD

**Issue by rosanch** [Azure/azure-cli#24062]
## Describe the bug
When I try to run any command inside my virtual environment, I get this error. But it doesn't happened when I run the same commands outside the venv in a normal powershell terminal.

**Command Name**
`az keyvault create`

**Errors:**
```
AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2022-09-29T04:56:56.5680000Z and the maximum allowed lifetime for this request is 43200.

Trace ID: b82baab7-0346-4ffb-940f-40da9c2e2900

Correlation ID: 6275b0bd-2241-4b3d-bc64-749ea22b4dab

Timestamp: 2022-09-29 18:42:04Z

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault create -g {} -n {}`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.7.8
Installer: PIP

azure-cli 2.39.0 *

Extensions:
azure-devops 0.23.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by jiasli** [comment]
Duplicate of #16209
