### ISSUE TITLE
what does this mean? "Attach local standard output and error streams to a container in a container group."

### ISSUE THREAD

**Issue by sijucm** [Azure/azure-cli#24074]
Not clear what exactly happens with that command. Just one sentence. So, does it mean that I can see the logs and errors of the container in the local command line where it is executed from? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5d1da7-7c4f-c9e6-e4b9-a30407675acf
* Version Independent ID: ba32e12d-8283-f980-e1d0-1ca2a75a5152
* Content: [az container](https://learn.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/container.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/container.yml)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@sijucm Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@sijucm The [az container attach](https://learn.microsoft.com/en-us/cli/azure/container#az_container_attach) command provides diagnostic information during container startup. Once the container has started, it streams STDOUT and STDERR to your local console.

Refer to the description and example [here](https://learn.microsoft.com/en-us/azure/container-instances/container-instances-get-logs#attach-output-streams) if that helps. I will also be creating a PR to update the documentation and include the above details to make it more description. Hope this helps.
