### ISSUE TITLE
 Unable to use 'az webapp auth update' to set 'unauthenticatedClientAction as RejectWith404

### ISSUE THREAD

**Issue by rajana** [Azure/azure-cli#24086]
I'm trying to use below command to set unauthenticatedclientaction 
 **az webapp auth update --name<name> --resource-group<rg> --unauthenticated-client-action RejectWith404**

but it always sets it to RedirectToLoginPage.

My azure cli version is 2.38.

Any help will be appreciated

**Comment by yonzhan** [comment]
route to CXP team

**Comment by seligj95** [comment]
Closing since fix was merged. Please update to the latest CLI version and try again. Please re-open if there is still an issue.
