### ISSUE TITLE
Sentence takes time to understand "Create a new event subscription for an Azure subscription subscription, using default filters."

### ISSUE THREAD

**Issue by sijucm** [Azure/azure-cli#24085]
The page has a sentence that says `Create a new event subscription for an Azure subscription subscription, using default filters.`
That could be made easier to say, "Create a new event-subscription for Azure Subscription"

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63e73e1b-aad9-0ce8-be1f-a9b9d02ca6d4
* Version Independent ID: 73525c5f-94f3-1c07-e3b6-3a022aab2a10
* Content: [az eventgrid event-subscription](https://learn.microsoft.com/en-gb/cli/azure/eventgrid/event-subscription?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/eventgrid/event-subscription.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/eventgrid/event-subscription.yml)
* Service: **event-grid**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@sijucm Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
