### ISSUE TITLE
Gallery 2022_03_03 Changes

### ISSUE THREAD

**Issue by tiregan** [Azure/azure-cli#24087]
# Related command

az sig image-version
az sig share

# Resource Provider

Az.Compute

# Description of Feature or Work Requested

Need to update to include changes in latest Swagger release: https://github.com/Azure/azure-rest-api-specs/pull/20396

# Minimum API Version Required

2022-03-03

# Target Date

10/14

# Description of changes and examples

Regional exludeFromLatest flag 
See [Gallery.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json) line 2535
> az sig image-version update -g EastUS-rg --gallery-name Terraform_sig --gallery-image-definition Disk_def --gallery-image-version 1.0.0 --add publishingProfile.targetRegions name=eastus regionalReplicaCount=3 **regionalExcludeFromLatest=true**

Safety Profile
See [Gallery.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json) line 2424
> az sig image-version create --gallery-image-definition $galleryDefinitionName --gallery-image-version $galleryImageVersionName --gallery-name $galleryName --resource-group $rg --location $region --managed-image $vmResourceID --target-regions $region=$replicaCount1=$storageAccount1 $region2=$replicaCount2=$storageAccount2 **--set safetyProfile.allowDeletionOfReplicatedLocations=true**

Create SIG Image Version from Community Gallery SIG Image Version
very similar to existing 'Add a new image version from another image version' example, but for community gallery it needs to be in new api field.  See [Gallery.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json) line 2741
> az sig image-version create --resource-group MyResourceGroup \
--gallery-name MyGallery --gallery-image-definition MyImage \
--gallery-image-version 1.0.0 \
**--community-image-version /subscriptions/00000000-0000-0000-0000-00000000xxxx/resourceGroups/imageGroups/providers/Microsoft.Compute/galleries/MyGallery/images/MyImageDefinition/versions/1.0.0**

PrivacyStatementUri & Eula on direct shared galleries.
See [SharedGallery.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/sharedGallery.json) line 558 & 562
> az sig share add --resource-group MyResourceGroup --gallery-name MyGallery
--gallery-image-definition MyImage \
--subscription-ids subId1 subId2 --tenant-ids tenantId1 tenantId2 **--privacy-statement-uri https://www.microsoft.com/en-us/ -eula https://www.microsoft.com/en-us/**

**Comment by yonzhan** [comment]
Compute feature

**Comment by yanzhudd** [comment]
Hi @tiregan, could you please help to confirm below details? Thanks.

#### Regional exludeFromLatest flag
> Regional exludeFromLatest flag
> See [Gallery.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json) line 2535
> 
> > az sig image-version update -g EastUS-rg --gallery-name Terraform_sig --gallery-image-definition Disk_def --gallery-image-version 1.0.0 --add publishingProfile.targetRegions name=eastus regionalReplicaCount=3 **regionalExcludeFromLatest=true**

Since the fields of --add parameter should be consistent with the swagger, we propose that the format of the command could be changed to like this:
az sig image-version update -g EastUS-rg --gallery-name Terraform_sig --gallery-image-definition Disk_def --gallery-image-version 1.0.0 --add publishingProfile.targetRegions name=eastus regionalReplicaCount=3 **excludeFromLatest=true**


#### Safety Profile

> Safety Profile
> See [Gallery.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json) line 2424
> 
> > az sig image-version **create** --gallery-image-definition $galleryDefinitionName --gallery-image-version $galleryImageVersionName --gallery-name $galleryName --resource-group $rg --location $region --managed-image $vmResourceID --target-regions $region=$replicaCount1=$storageAccount1 $region2=$replicaCount2=$storageAccount2 **--set safetyProfile.allowDeletionOfReplicatedLocations=true**

Since the parameter `--set` is usually present in **update** command, a new parameter would be added if the change is made in **create** command. May I ask the change would be made in `az sig image-version create` instead of `az sig image-version update`? If is `az sig image-version create`, is it a matter of adding a new parameter to support this change?

**Comment by yanzhudd** [comment]
Hi @tiregan, since this feature has several problems to be solved, it has to be postponed to the next sprint (2022-12-06).

**Comment by tiregan** [comment]
we are very behind on this and cannot wait until 12-06.  Could we please schedule this for this sprint?


> Regional exludeFromLatest flag
> See [Gallery.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json) line 2535
> az sig image-version update -g EastUS-rg --gallery-name Terraform_sig --gallery-image-definition Disk_def --gallery-image-version 1.0.0 --add publishingProfile.targetRegions name=eastus regionalReplicaCount=3 regionalExcludeFromLatest=true
> Since the fields of --add parameter should be consistent with the swagger, we propose that the format of the command could be changed to like this:
> az sig image-version update -g EastUS-rg --gallery-name Terraform_sig --gallery-image-definition Disk_def --gallery-image-version 1.0.0 --add publishingProfile.targetRegions name=eastus regionalReplicaCount=3 excludeFromLatest=true


[TR] Your suggestion sounds fine to me.

> Safety Profile
> Safety Profile
> See [Gallery.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json) line 2424
> az sig image-version create --gallery-image-definition $galleryDefinitionName --gallery-image-version $galleryImageVersionName --gallery-name $galleryName --resource-group $rg --location $region --managed-image $vmResourceID --target-regions $region=$replicaCount1=$storageAccount1 $region2=$replicaCount2=$storageAccount2 --set safetyProfile.allowDeletionOfReplicatedLocations=true
> Since the parameter --set is usually present in update command, a new parameter would be added if the change is made in create command. May I ask the change would be made in az sig image-version create instead of az sig image-version update? If is az sig image-version create, is it a matter of adding a new parameter to support this change?



[TR] I suppose this can be added to update if that’s the typical way we’ve always done this.

> PrivacyStatementUri & Eula on direct shared galleries
> See [SharedGallery.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/sharedGallery.json) line 558 & 562
> az sig share add --resource-group MyResourceGroup --gallery-name MyGallery --gallery-image-definition MyImage --subscription-ids subId1 subId2 --tenant-ids tenantId1 tenantId2 --privacy-statement-uri https://www.microsoft.com/en-us/ -eula https://www.microsoft.com/en-us/
> The request path of az sig share add command is '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/share' and the parameters of this command is in gallery.json. It seems that the --privacy-statement-uri and --eula parameters may not apply to the az sig share add command. Could you please help to check it?



[TR] Forget this one.  I misunderstood these changes when I made the request.  These changes shouldn’t require any change on CLI.

**Comment by zhoxing-ms** [comment]
@tiregan In fact, since we got the answers to these questions late, we will launch the release of this sprint the day after tomorrow, so we have only **two days left** for development and testing which is not an enough time

So I have two alternatives maybe we can consider:
1. We continue to plan to officially release it in **12-06**, but we will generate the **private CLI package** which contains those features in advance from edge build, so you can provide the private package to customers who have urgent needs to experience it first
2. If some features must be officially released in this sprint *(11-01)*, please separate them from this big feature request. Then we still need to evaluate whether the divided requirements can be completed in **one day**. We can't guarantee that this time is enough for us to release one of the features, but we will try our best to meet the urgent needs.

**Comment by yanzhudd** [comment]
> > Safety Profile
> > Safety Profile
> > See [Gallery.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json) line 2424
> > az sig image-version create --gallery-image-definition $galleryDefinitionName --gallery-image-version $galleryImageVersionName --gallery-name $galleryName --resource-group $rg --location $region --managed-image $vmResourceID --target-regions $region=$replicaCount1=$storageAccount1 $region2=$replicaCount2=$storageAccount2 --set safetyProfile.allowDeletionOfReplicatedLocations=true
> > Since the parameter --set is usually present in update command, a new parameter would be added if the change is made in create command. May I ask the change would be made in az sig image-version create instead of az sig image-version update? If is az sig image-version create, is it a matter of adding a new parameter to support this change?
> 
> 
> 
> [TR] I suppose this can be added to update if that’s the typical way we’ve always done this.

Hi @tiregan, 
If `--set` need to be added in create command, a developing feature (https://github.com/Azure/azure-cli/pull/24364) may meet this request. Could you please check if it meets your expectation?

**Comment by yanzhudd** [comment]
> Create SIG Image Version from Community Gallery SIG Image Version
> very similar to existing 'Add a new image version from another image version' example, but for community gallery it needs to be in new api field. See [Gallery.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json) line 2741
> 
> 
> > az sig image-version create --resource-group MyResourceGroup
> > --gallery-name MyGallery --gallery-image-definition MyImage
> > --gallery-image-version 1.0.0
> > --community-image-version **_/subscriptions/00000000-0000-0000-0000-00000000xxxx/resourceGroups/imageGroups/providers/Microsoft.Compute/galleries/MyGallery/images/MyImageDefinition/versions/1.0.0_**

Hello @tiregan,

When we create sig image version from community gallery sig image version, an error is reported. Could you please help to have a look?
![image](https://user-images.githubusercontent.com/105691024/197700119-c9ed9781-0e9a-4d53-ae96-74532823444a.png)

Besides, in the GalleryImageVersion_Create_withCommunityImageVersionAsSource.json file, the format of communityGalleryImageId is '**_/communityGalleries/{communityGalleryName}/images/{communityGalleryImageName}_**' (attached below). Could you please help to confirm which format is supported?
![image](https://user-images.githubusercontent.com/105691024/197701013-3eb3b98b-0761-43e8-9cef-cac171f1ac5b.png)

**Comment by yanzhudd** [comment]
Hello @tiregan, could you please help to have a look https://github.com/Azure/azure-cli/issues/24087#issuecomment-1290060518 ?

**Comment by tiregan** [comment]
@yanzhudd I thought this feature was finished but just talked to the feature owner and it's still in PR.  Let's exclude it and we will make a separate request for it when it's finished.

**Comment by msandu62** [comment]
Is this available in the sdk for python also? or packer during the image build? cannot find the option (in packer at least)
