### ISSUE TITLE
az network application-gateway create and specifying subnet + vnet creates new vnet and subnet

### ISSUE THREAD

**Issue by Candelit** [Azure/azure-cli#24093]
The following 

az network application-gateway create \
     --subnet $SUBNET_NAME \
    --vnet-name $VNET_NAME \
    --and all the other parameters...
    
When pointing to an existing vnet and existing subnet, it still creates a new vnet and subnet in the same rg as the app gateway.
The prefix of the new subnet is set to 10.0.0.0/24
This can not be the expected behavior?

After creating the app gateway, I now have two vnets with identical name in the same subscription but different resource groups.

It actually took me a while to discover this...

The expected behaviour is to use the named vnet and subnet...that already exists. If they don't exist, fail and give me an error.

(I know now that I can fix this using the subnetId, but I still think you should change this behaviour, or add a warning to the article on 'az network application-gateway create'

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d85e1042-f9fe-a899-7a64-99796558a7aa
* Version Independent ID: 2573afce-d2fa-6f5f-3647-ea8696b8d0e2
* Content: [az network application-gateway](https://learn.microsoft.com/en-us/cli/azure/network/application-gateway?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/application-gateway.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/application-gateway.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
Such information is already provided in the document:

![image](https://user-images.githubusercontent.com/12371639/203910520-c982b213-19bf-439a-a45d-99b40ee31e69.png)

https://learn.microsoft.com/en-us/cli/azure/network/application-gateway?view=azure-cli-latest#az-network-application-gateway-create

**Comment by Candelit** [comment]
No, it does not. I think that I along with everyone, assumes that 'resource' in 'Will create resource if it does not exist' refers to the App GW or what you are trying to create. Not a Virtual Network...
The vnet does exist, the subnet does exist...so don't create them again for me, right?

**Comment by Candelit** [comment]
Why is it always so hard to get you to change these things? Change it and make life easier for everyone, instead of just clinging to your version of the truth.

**Comment by Candelit** [comment]
I can add, its ONLY in your demo/quick starts that you create a vnet at the same time as your resources...it never happens in the real world. The vnet always exist...

**Comment by fuzzykiller** [comment]
I’ll have to agree here, this command is very counter-intuitive, and the documentation is outright wrong. Not only will it try to create a new VNet + subnet, it will even attempt to _delete_ an existing VNet. Surely this cannot be right?!

The `--vnet-name` parameter _must_ clarify that it is not required for existing VNets. (The CLI says “Ignoring: --vnet-name”). The `--subnet` parameter _must_ clarify that using an ID is _always_ required when using an existing subnet.
