### ISSUE TITLE
az create error

### ISSUE THREAD

**Issue by Sreejamuppalla** [Azure/azure-cli#24096]
## Describe the bug

**Command Name**
`az group create`

**Errors:**
```
az: error: unrecognized arguments: Central US
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group create --location {} {} {} --name {}`

## Environment Summary
```
Linux-5.15.0-1020-azure-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by navba-MSFT** [comment]
@Sreejamuppalla Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Sreejamuppalla I just ran the below command and my resource group was created successfully. Could you please try the same and let me know ?

>az group create -l **centralus** -n MYResourceGroupName

Hope this helps.

**Comment by navba-MSFT** [comment]
@Sreejamuppalla I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Sreejamuppalla The action is currently pending on you to try the above action plan. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
