### ISSUE TITLE
az sig image-version --do-not-delete

### ISSUE THREAD

**Issue by kunalwaghrayismyalias** [Azure/azure-cli#24099]
**Related command**

- No command exists
- Example syntax could be `az sig image-version --do-not-delete {true, false}` similar to soft-delete

**Is your feature request related to a problem? Please describe.**
We tried replicating sig image to new region. This request did not include all regions already replicated to, which caused an outage for our service. Setting this flag would prevent this. 

**Describe the solution you'd like**
Please allow setting the allowDeletionOfReplicatedLocations to false via azure cli. 
```
$body = @{
  "location"= "West US 2"
  "properties" = @{
    "safetyProfile" = @{
        "allowDeletionOfReplicatedLocations" = $false
    }
  }
}
```

**Describe alternatives you've considered**
- Currently setting via powershell directly, this uses different authentication mechanism, so it not preferred

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@kunalwaghrayismyalias This should be a new feature request, right?
It is recommended that you use this template [Service_team_request](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=feature-request&template=Service_team_request.yaml) to create the feature request, because we need some important information such as min api-version, Swagger link, ETA...
Please refer to this issue #22275 for details

**Comment by PARADISSEEKR** [comment]
Hi @kunalwaghrayismyalias ,`az sig image-version` has many subcommands(create, update, etc), which commands need to add this parameter?
And `allowDeletionOfReplicatedLocations` does not exist in the SDK currently used, is the swagger it uses [this swagger](https://github.com/Azure/azure-rest-api-specs/blob/dc4bf6c71a3bbf76f3f56b018645d8869f7f3d9d/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2022-03-03/gallery.json#L2837-L2839)? Please release new SDK so we can develop it.

**Comment by kunalwaghrayismyalias** [comment]
Please add to either or both the create and update
`az sig image-version create --do-not-delete {true, false}` 
`az sig image-version update --set allowDeletionOfReplicatedLocations={false,true}`

In return value from the command, please return the value that was set. For example, 
```
>> az sig image-version create --do-not-delete false ...

"id": "/subscriptions/<subid>/resourceGroups/<rg-name>/providers/Microsoft.Compute/galleries/<GalleryName>/images/<imagename>/versions/<imageversion>",
"location": "westus2",
"name": "1.0.0",
"provisioningState": "Succeeded",
"allowDeletionOfReplicatedLocations" : "false"
```


The SDK with this should be released, requesting a teammate to add this information.

**Comment by zhoxing-ms** [comment]
> --do-not-delete 

@kunalwaghrayismyalias This parameter name does not conform to the CLI specification, and it's meaning is unclear which is easy to confuse users
How about the parameter name `--allow-replicated-location-deletion`?

**Comment by kunalwaghrayismyalias** [comment]
Hi @zhoxing-ms, I agree. `--allow-replicated-location-deletion` is more clear. That works

**Comment by tiregan** [comment]
Yes, this is in the newest swagger 2022_03_03.  The swagger has been merged and the SDK is in review and should be merged any day now.

**Comment by PARADISSEEKR** [comment]
> Yes, this is in the newest swagger 2022_03_03. The swagger has been merged and the SDK is in review and should be merged any day now.

@tiregan  Could you please provide the swagger PR link that includes `allowDeletionOfReplicatedLocations` and private python SDK?

**Comment by kunalwaghrayismyalias** [comment]
Hi @PARADISSEEKR, 

Please see the swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/20396
