### ISSUE TITLE
"az vm run-command create" - is not uploading the output to the "output-blob-uri" anymore

### ISSUE THREAD

**Issue by dorocri** [Azure/azure-cli#24095]
az vm run-command create 
        --name $name 
        --vm-name $vm_name 
        --resource-group $rg 
        --script $script
        --output-blob-uri $output

I used this command to execute, remotely,  a script on a VM and upload the output to a Blob Storage, this solution worked properly for the past 4 months but something happened and for the past 2 weeks the upload to the --output-blob-uri is not working anymore

Powershell script to be executed is located on a VM, I am running the logic from another location. The command is not uploading the output of the execution anymore. It is generating the proper output on the VM, script gets executed correctly but the output-blob-uri file is nowhere to be found on the storage.

I would expect the output to be uploaded in the Blob storage

This is the result of running the command, please keep in mind that I replaced any sensitive information with "xyz"
{
  "asyncExecution": false,
  "errorBlobUri": "https://xyz.blob.core.windows.net/xyz/error.txt",   
  "id": "/subscriptions/xyz/resourceGroups/xyz-rg/providers/Microsoft.Compute/virtualMachines/xyz/runCommands/result",
  "instanceView": null,
  "location": "Location",
  "name": "result",
  "outputBlobUri": "https://xyz.blob.core.windows.net/xyz/output.txt",
  "parameters": null,
  "protectedParameters": null,
  "provisioningState": "Succeeded",
  "resourceGroup": "xyz-rg",
  "runAsPassword": null,
  "runAsUser": null,
  "source": {
    "commandId": null,
    "script": "Get-Content C:\\xyz\\xyz\\xyz\\xyz\\results.xml",
    "scriptUri": null
  },
  "tags": {
    "xyz": "\"\"",
    "xyz": "\"\""
  },
  "timeoutInSeconds": 0,
  "type": "Microsoft.Compute/virtualMachines/runCommands"
}

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by l4rd** [comment]
I'm not sure that this is limited to the CLI as I am getting the same problem with a resource group deployment from bicep.

**Comment by jodem** [comment]
This breaks lots of automated system on our company, please fix asap

**Comment by yanzhudd** [comment]
We have reproduced this problem, and we found that the value of parameter `--output-blob-uri` is successfully passed in the service side. Thus, this problem may need service team to help to troubleshoot together.

Hello @D1v38om83r, could you please help to take a look about this problem? Here are some details of our request. Thanks!
![image](https://user-images.githubusercontent.com/105691024/194816426-1b605225-64d4-41cb-a375-9d63766749fc.png)
**Request URL**: https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/zytest/providers/Microsoft.Compute/virtualMachines/vm2/runCommands/runcommand7?api-version=2022-08-01
**Request body**: {"location": "westus", "properties": {"source": {"script": "Write-Host \"Do I have param1?\""}, "asyncExecution": false, "outputBlobUri": "https://zyaccount.blob.core.windows.net/container/test"}}
**x-ms-request-id**: 10a4decb-9e77-4d7f-b872-5cbdbda5010b
**x-ms-correlation-request-id**: 957af0dc-30ff-4f80-9a42-8acfe6b1cb03
**x-ms-routing-request-id**: SOUTHEASTASIA:20221010T062927Z:957af0dc-30ff-4f80-9a42-8acfe6b1cb03

**Comment by vivlingaiah** [comment]
Hi, user will need to use SAS URIs for --output-blob-uri to work. This is a recent change since Sep 20 or so. We've stopped auto-generating SAS URIs on behalf of users due to security concerns. User need to use SAS URI with racw permissions (Read, Append, Create, Write)

**Comment by vivlingaiah** [comment]
Refer aka.ms/RunCommandManaged for up to date documentation

**Comment by vivlingaiah** [comment]
Example SAS URI for --output-blob-uri
https://mystorageaccount.blob.core.windows.net/mycontainer/RuncommandOutput.txt?sp=racw&st=2022-10-17T19:02:15Z&se=2022-10-18T03:02:15Z&spr=https&sv=2021-06-08&sr=b&sig=3BxtEasfdasdfasdfdYki9yvYsqc60V0%3D

**Comment by AndrewQuartic** [comment]
@vivlingaiah Uh, but what about managed identity access? Isn't that the point of a managed identity is that I don't need a SAS?
