### ISSUE TITLE
docs spell parameter name wrong

### ISSUE THREAD

**Issue by ncook-hxgn** [Azure/azure-cli#24091]
az repos pr create

It's --organisation, not --org

According to my error logs

Please fix docs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e48ddaa-64b8-e414-7ea9-2746827fcc5f
* Version Independent ID: 952f1742-6d3b-a177-a2e0-164b563c1771
* Content: [az repos pr](https://learn.microsoft.com/en-us/cli/azure/repos/pr?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/repos/pr.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/repos/pr.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@ncook-hxgn I can be either `--org` or  `--organization`.  I have tested this, and I do not see any errors. 
![image](https://user-images.githubusercontent.com/38112130/194429834-006a0c68-6a10-4bc3-886f-cbda813c2ad4.png)

**Comment by ncook-hxgn** [comment]
Indeed, it was spelled correctly. I got the error `--organisation must be supplied` even though I was supplying an organisation, but it turns out my organisation wasn't a URL. Bit of a misleading error message, but probably not a docs issue.
