### ISSUE TITLE
Installation script needs to be fixed for ARM64

### ISSUE THREAD

**Issue by yozik04** [Azure/azure-cli#24117]
Mistake is here:
https://github.com/Azure/azure-cli/blob/c92d0d0048d3f4f1435a4263bcf6583c34880cee/scripts/release/debian/deb_install.sh#L84

It should not be hardcoded for amd64

**Comment by yonzhan** [comment]
ARM64 related

**Comment by bebound** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/24180
