### ISSUE TITLE
[az 2.40.0] Cannot Create New App Service Plan with existing Zone Redundant App Service Environment

### ISSUE THREAD

**Issue by trindels** [Azure/azure-cli#24112]
## Cannot create new App Service Plan with existing Zone Redundant App Service Environment

**Command Name**
`az appservice plan create`

**Errors:**
```
Zone redundancy cannot be enabled for sku I1V2

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Existing Zone Redundant App Service Environment
- `az appservice plan create --resource-group {} --name {} --location {} --sku [ I1v2 | I2v2 | I3v2 ] --is-linux --app-service-environment {} --subscription {} --no-wait --number-of-workers {} --zone-redundant --debug`

## Expected Behavior
The expected behavior should be to create a new App Service Plan inside an existing Zone-Redundant App Service Environment.

## Environment Summary
```
Windows-10-10.0.22623-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding Service team to assist

**Comment by madsd** [comment]
#assign:madsd
