### ISSUE TITLE
Add Asn Param to az vhub & vpn-gateway create/update commands

### ISSUE THREAD

**Issue by ureridu** [Azure/azure-cli#24125]
### Related command

az network vhub create
az network vhub update
az network vpn-gateway create
az network vpn-gateway update

### Resource Provider

Microsoft.Network

### Description of Feature or Work Requested

uint VirtualRouterAsn param needs to be added to the below commands as an optional parameter
az network vhub create
az network vhub update

uint Asn param needs to be added to the below commands as an optional parameter
az network vpn-gateway create
az network vpn-gateway update

API Doc: https://microsoft.sharepoint.com/:w:/r/teams/Aznet/_layouts/15/Doc.aspx?sourcedoc=%7BEED9EB88-BD47-4748-A42C-0E1FB32A44FB%7D&file=ConfigurableAsnApiReview.docx&action=default&mobileredirect=true&share=IQGI69nuR71IR6QsDh-zKkT7ARNtKLhAYk35XDkMN2tSVlk

Powershell PR: https://github.com/Azure/azure-powershell/pull/19498
Swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2022-05-01/virtualWan.json

### Minimum API Version Required

2022-01-01

### Swagger PR link / SDK link

N/A

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2022-05-01/examples/VpnGatewayPut.json

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2022-05-01/examples/VirtualHubPut.json

### Target Date

10/24/2022

**Comment by yonzhan** [comment]
network feature
