### ISSUE TITLE
az group create does not create tags

### ISSUE THREAD

**Issue by BasSmuldersCZ** [Azure/azure-cli#24129]
## Describe the bug
The tags are not created with the az group create command, although they are specified in the --tags parameter

**Command Name**
`az group create --name 'name' --location 'location' --tags 'tags'`
 tags are specified as key value pairs as described in the documentation

**Errors:**
Because we have a tagging policy in place, the resourcegroup creation fails.
It fails local and on Microsoft Hosted devops agents

## To Reproduce:
see command above

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by RakeshMohanMSFT** [comment]
@BasSmuldersCZ Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@BasSmuldersCZ Can you please try the below command, we are unable to reproduce the issue at our end.
az group create -n Issue24129 -l eastus --tags issue=24129
![image](https://user-images.githubusercontent.com/49954584/195003416-b25ba3ec-2406-479c-8b8e-fda3f80244a1.png)

**Comment by BasSmuldersCZ** [comment]
The command above succeeds. However it turns out that tags parameter is not working in the way it has worked before:
$tags=@()
$tags+= "tag1=value1"
$tags+= "tag2=value2"
az group create -n Issue24129 -l eastus --tags $tags

result
"tag1": "value1 tag2=value2"

because of our tagging policy it fails

what is the correct way to use a variable to pass the tags as a parameter?

**Comment by RakeshMohanMSFT** [comment]
@BasSmuldersCZ Please see the explanation and solution at https://github.com/Azure/azure-cli/issues/23797#issuecomment-1238997338

**Comment by BasSmuldersCZ** [comment]
thx!
