### ISSUE TITLE
az cli commands in documentation to change subnet for an existing Application Gateway does not work (Error: ApplicationGatewayFrontendIpSubnetCannotBeDifferentFromGatewaySubnet)

### ISSUE THREAD

**Issue by subhasishdc** [Azure/azure-cli#24122]
The following link mentions the `az cli` commands to change the subnet for an existing Application Gateway. We tried it out at our end and looks like there are some missing components to these commands. Can you please validate at your end and update the documentation accordingly.

https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-faq#can-i-change-the-virtual-network-or-subnet-for-an-existing-application-gateway

**ERROR: ApplicationGatewayFrontendIpSubnetCannotBeDifferentFromGatewaySubnet**

Example: We are trying to change subnet on an application gateway. This was done after the gateway was stopped.

`az network application-gateway update -g scus-ei-rg  -n ei-aag01-scus --set gatewayIpConfigurations[0].subnet.id=/subscriptions/XYZ-123/resourceGroups/scus-ei-rg/providers/Microsoft.Network/virtualNetworks/eiVnet/subnets/aag2subnet`

ERROR: (ApplicationGatewayFrontendIpSubnetCannotBeDifferentFromGatewaySubnet) FrontendIpConfiguration /subscriptions/XYZ-123/resourceGroups/scus-ei-rg/providers/Microsoft.Network/applicationGateways/ei-aag01-scus/frontendIPConfigurations/appGatewayFrontendIP subnet /subscriptions/XYZ-123/resourceGroups/scus-ei-rg/providers/Microsoft.Network/virtualNetworks/eiVnet/subnets/Aag1Subnet and gateway subnet /subscriptions/XYZ-123/resourceGroups/scus-ei-rg/providers/Microsoft.Network/virtualNetworks/eiVnet/subnets/Aag2Subnet can not be different.
Code: ApplicationGatewayFrontendIpSubnetCannotBeDifferentFromGatewaySubnet
Message: FrontendIpConfiguration /subscriptions/XYZ-123/resourceGroups/scus-ei-rg/providers/Microsoft.Network/applicationGateways/azureei1-aag01-scus/frontendIPConfigurations/appGatewayFrontendIP subnet /subscriptions/XYZ-123/resourceGroups/scus-ei-rg/providers/Microsoft.Network/virtualNetworks/eiVnet/subnets/Aag1Subnet and gateway subnet /subscriptions/XYZ-123/resourceGroups/scus-ei-rg/providers/Microsoft.Network/virtualNetworks/eiVnet/subnets/Aag2Subnet can not be different.

To fix this, we had to run the following command.

`az network application-gateway update -g scus-ei-rg  -n ei-aag01-scus --set gatewayIpConfigurations[0].subnet.id=/subscriptions/XYZ-123/resourceGroups/scus-ei-rg/providers/Microsoft.Network/virtualNetworks/eiVnet/subnets/aag2subnet --set frontendIPConfigurations[0].subnet.id=/subscriptions/XYZ-123/resourceGroups/scus-ei-rg/providers/Microsoft.Network/virtualNetworks/eiVnet/subnets/aag2subnet`

**Comment by yonzhan** [comment]
network

**Comment by necusjz** [comment]
IMO, the document describes a scenario for changing a subnet without a private frontend IP configuration. If you have a more complicated scenario, you can refer to the above PowerShell's procedures.
