### ISSUE TITLE
`TypeError: begin_start() got an unexpected keyword argument 'no_wait'` in CI pipeline command `az ml compute start`

### ISSUE THREAD

**Issue by iddqdiddqd** [Azure/azure-cli#24128]
**Related command**
```
az ml compute start \
        --name "${COMPUTE_INSTANCE_NAME}" \
        --workspace-name "${WS_NAME}" \
        --resource-group "${RESOURCE_GROUP}"
```

After the command from above is run, the following error is returned:
```
Traceback (most recent call last):
  File "/home/user/.azure/cliextensions/ml/azext_mlv2/manual/custom/compute.py", line 171, in ml_compute_start
    compute = ml_client.compute.begin_start(name=name, no_wait=no_wait)
  File "/usr/lib/azure-cli/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/user/.azure/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_telemetry/activity.py", line 260, in wrapper
    return f(*args, **kwargs)
TypeError: begin_start() got an unexpected keyword argument 'no_wait'
```

The issue persists with `ml` v2 extension only. The same command executes successfully when running it with `ml` v1 extension installed.  

**Expected behavior**
AML compute instance should be started, no python3 error should be returned.

**Environment summary**
Install Method: `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`
CLI version:  `2.39.0`
OS version: `Ubuntu 20.04.5 LTS`
Shell Type: `bash`
Python version: `Python 3.8.10`
ML extension version: `2.8.0`

**Comment by yonzhan** [comment]
route to CXP team

**Comment by leosannlsn** [comment]
I'm hitting this error too. Sub-commands `show` and `stop` work as expected, but `az ml compute start` fails with this message on a freshly updated `az ml`.

**Comment by iddqdiddqd** [comment]
Any updates on this case so far?

**Comment by navba-MSFT** [comment]
@iddqdiddqd Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please update to the most recent version of the `ml extension` ? 

> **az extension update -n ml** 

Hope this helps.
