### ISSUE TITLE
`az aks update` - unrecognized arguments: --enable-oidc-issuer

### ISSUE THREAD

**Issue by ElvenSpellmaker** [Azure/azure-cli#24132]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az aks update --resource-group <rg> --name <name> --subscription <subid> --enable-oidc-issuer`

**Describe the bug**
> unrecognized arguments: --enable-oidc-issuer

**To Reproduce**
Above command

**Expected behavior**
It to enable the OIDC URL

**Environment summary**
Windows 10, Cygwin, az 2.40.0
```
$ az version
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "resource-graph": "1.1.0"
  }
}

```

**Additional context**
This Microsoft document states you need version 2.42.0 of the CLI tool which doesn't even exist as 2.40.0 is the latest version.
> The Azure CLI version 2.42.0 or higher. Run az --version to find your version. If you need to install or upgrade, see [Install Azure CLI](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli).

https://learn.microsoft.com/en-us/azure/aks/cluster-configuration#upgrade-an-aks-cluster-with-oidc-issuer

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@ElvenSpellmaker Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@ElvenSpellmaker  Can you please run this command first? az extension add --name aks-preview
and then try enabling oidc

**Comment by giskou** [comment]
Running `az extension add --name aks-preview` before `az aks update` worked for me

**Comment by ElvenSpellmaker** [comment]
Hey @RakeshMohanMSFT, did a ticket get open for changing the documentation, or is it being done as part of this?

**Comment by RakeshMohanMSFT** [comment]
@ElvenSpellmaker I go the document updated, next release should have the update.

**Comment by ElvenSpellmaker** [comment]
@RakeshMohanMSFT Excellent thanks 🙂
