### ISSUE TITLE
In az cdn endpoint purge the --profile-name is not an optional parameter

### ISSUE THREAD

**Issue by pankajdevrani** [Azure/azure-cli#24135]
[Enter feedback here]
In az cdn endpoint purge the --profile-name is not an optional parameter, you are required to give either --profile-name or --ids parameter. Please update the doc page.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17e2b3b2-3e26-a47f-ee80-5bd5c3b065c4
* Version Independent ID: 72ef6ca0-b8f6-4952-732d-34aefa414bb6
* Content: [az cdn endpoint](https://learn.microsoft.com/en-us/cli/azure/cdn/endpoint?view=azure-cli-latest&source=docs#az-cdn-endpoint-purge)
* Content Source: [latest/docs-ref-autogen/cdn/endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/cdn/endpoint.yml)
* Service: **azure-cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@pankajdevrani Thank you for reaching out, we are looking into it.
