### ISSUE TITLE
how to make role definitinons for cosmos DB tables?

### ISSUE THREAD

**Issue by santo2** [Azure/azure-cli#24143]
Hi, this document helped me creating RBAC for our development testers using their AD account, although I can't seem to find the exact actions and role definition type for this for a CosmosDB Table?
- there isn't a similar article on tables as this article
- the list of operations described in https://learn.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftdocumentdb don't really show me how to do this
- there is not a "TablesRoleDefinition" as we have for SqlRoleDefinition

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 474373c4-d9d9-48ed-025c-6f82454da4a2
* Version Independent ID: a9b051b2-7796-70b5-1c2a-0dec89da3776
* Content: [az cosmosdb sql role definition](https://learn.microsoft.com/en-us/cli/azure/cosmosdb/sql/role/definition?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/cosmosdb/sql/role/definition.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/cosmosdb/sql/role/definition.yml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@santo2 Thanks for reaching out to us and reporting this issue. Could you please share your use case here and what are you trying to accomplish ? This will help us to assist you better.

**Comment by santo2** [comment]
Hi @navba-MSFT, we have testers that need access to read and write in Cosmos DB instances on pre-production environments, using the azure portal and their own AD credentials, for Cosmos DB SQL API we specifically needed to provide write permissions using a custom role because the only other option we found was to make them contributor, which is of course not what we wanted. the SqlRoleDefinition seems to work fine for that.

We also have Cosmos DB Tables for which we want the same read/write permissions, but I can not seem to find any clear information specifically for Tables

PS I don't find it at all logical that these (SQL) role definitions are not just the default role definitions from AD. It makes it unclear and invisible who has which permissions.

This feels kinda that it's all created by different teams that don't share the same ideas on how this needs to work :-)

**Comment by navba-MSFT** [comment]
@santo2 Thanks for getting back clarifying your ask. The support RBAC for data plane operations on Table API, is currently not supported and there is no ETA for the same.

**Comment by navba-MSFT** [comment]
@santo2 I hope you had a chance to look at my above comment. If you have any follow-up questions, please feel free to reopen this thread. We would be happy to help.
