### ISSUE TITLE
I cannot make a script and running with WSL to a VM running on Azure

### ISSUE THREAD

**Issue by Kishox3** [Azure/azure-cli#24149]
## Describe the bug

**Command Name**
`az vm extension set`

**Errors:**
```
(VMExtensionProvisioningError) VM has reported a failure when processing extension 'customScript'. Error message: "Enable failed: failed to get configuration: json validation error: invalid public settings JSON: location: Additional property location is not allowed"

More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot 
Code: VMExtensionProvisioningError
Message: VM has reported a failure when processing extension 'customScript'. Error message: "Enable failed: failed to get configuration: json validation error: invalid public settings JSON: location: Additional property location is not allowed"

More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot 

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm extension set --resource-group {} --vm-name {} --name {} --publisher {} --settings {}`

## Environment Summary
```
Linux-4.4.0-22621-Microsoft-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.40.0
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
> json validation error: invalid public settings JSON: location: Additional property location is not allowed

Please check whether the `--settings` parameter has additional property `location`
