### ISSUE TITLE
Clarification needed in sintaxis for --Zones values entered not valid.

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/azure-cli#24145]
document states:
--zones -z
Availability zones where agent nodes will be placed.

accepted values: 1, 2, 3

please add clarification, in situations were customers wants to have all 3 zones , then the values are expected to be entered as 👍 
--zones 1 2 3 
no commas needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39fce7ab-ab56-44c6-b9a8-405444247a0b
* Version Independent ID: dabbb6c6-c616-a6ec-61f6-1b9d3bb069e8
* Content: [az aks nodepool](https://learn.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest#az-aks-nodepool-add)
* Content Source: [latest/docs-ref-autogen/aks/nodepool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks/nodepool.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@porrascarlos802018 Thanks for your feedback! We will investigate and update as appropriate.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@porrascarlos802018 The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
