### ISSUE TITLE
"az network front-door waf-policy managed-rules add" only working for Type DefaultRuleSet Version 1.0 

### ISSUE THREAD

**Issue by mossywell** [Azure/azure-cli#24148]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az network front-door waf-policy managed-rules add --policy-name MyWaf" --resource-group "MyRg" --type Microsoft_DefaultRuleSet --version 2.0

**Describe the bug**

When the above command is run, it should add the "Microsoft_DefaultRuleSet" version 2.0 rule set to the WAF. However, it actually errors with:
(BadRequest) WebApplicationFirewallPolicy validation failed. More information "Managed rule set types or versions are not compatible.".
Indeed, the only combination of types and versions that work is:
--type DefaultRuleSet --version 1.0

**To Reproduce**

az network front-door waf-policy managed-rules add --policy-name MyWaf" --resource-group "MyRg" --type Microsoft_DefaultRuleSet --version 2.0

**Expected behavior**

The CLI should allow addition of all the rules sets specified in the GUI including:
Microsoft_DefaultRuleSet version 1.1 AND
Microsoft_DefaultRuleSet version 2.0

**Environment summary**

Azure Cloud Shell (PowerShell)

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@mossywell Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@mossywell Could you please confirm if you are using a **Classic** Azure front door or **Standard / Premium** Front door ? Awaiting your reply.

**Comment by mossywell** [comment]
Premium

**Comment by navba-MSFT** [comment]
@mossywell Thanks for your reply.

[az afd ](https://learn.microsoft.com/en-us/cli/azure/afd?view=azure-cli-latest)CLI command helps in the managing  Azure Front Door Standard/Premium resource. Could you please confirm if you have tried running this command ?

**Comment by mossywell** [comment]
A few points here:
1. There is no "afd" subcommand for WAF policy (that I am aware of) hence why I am using the older command.
2. As per the documentation: https://learn.microsoft.com/en-us/azure/frontdoor/create-front-door-cli you will see that this ("az network front-door waf-policy" ) is how MS recommend doing it for Standard/Premium.
3. In addition, this https://learn.microsoft.com/en-us/cli/azure/network/front-door/waf-policy?view=azure-cli-latest shows that there is a SKU for the newer Standard/Premium.
4. I did look at the az afd command set and saw nothing relating to WAF policy.
5. It (the older style CLI) _does_ actually work fine for DefaultRuleSet 1.0.

So, AFAICT, the documentation is right? However, if the documentation is incorrect, please do say (and what "az afd" I need to run). Cheers!

**Comment by navba-MSFT** [comment]
@mossywell Thanks for getting back and clarifying. I was able to reproduce this issue on my resource. I am working with the Product owners now to check the status on the fix.

**Comment by t-bzhan** [comment]
Hi @mossywell , could you update the front-door extension version to 1.0.17 to see whether the issue is addressed or not:
`az extension add --upgrade --name front-door --version 1.0.17`

**Comment by mossywell** [comment]
Hello, when I run this:
az extension add --upgrade --name front-door --version 1.0.17
followed by this:
az network front-door waf-policy managed-rules add --policy-name MyWaf" --resource-group "MyRg" --type Microsoft_DefaultRuleSet --version 2.0

I still get an error:
This rule set action value is not supported

**Comment by Moustafa-Moustafa** [comment]
[This](https://github.com/MicrosoftDocs/azure-docs/issues/118472#issuecomment-1879504235) might be related. Including the --action parameter seems to be needed.
