### ISSUE TITLE
Az aks update fails

### ISSUE THREAD

**Issue by ianEROAD** [Azure/azure-cli#24147]
## Describe the bug

**Command Name**
`az aks update`

**Errors:**
```
cannot import name 'edge_zone_type'
Traceback (most recent call last):
lib/python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
azure/cli/core/commands/__init__.py, ln 559, in execute
    self.commands_loader.load_arguments(command)
site-packages/azure/cli/core/__init__.py, ln 503, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
.azure/cliextensions/aks-preview/azext_aks_preview/__init__.py, ln 47, in load_arguments
    from ._params import load_arguments
.azure/cliextensions/aks-preview/azext_aks_preview/_params.py, ln 12, in <module>
    from azure.cli.core.commands.parameters import (
ImportError: cannot import name 'edge_zone_type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --resource-group {} --name {} --enable-managed-identity`

## Environment Summary
```
Linux-5.4.0-1063-azure-x86_64-with-debian-buster-sid
Python 3.6.10
Installer: DEB

azure-cli 2.20.0 *

Extensions:
aks-preview 0.5.41

```

**Comment by ianEROAD** [comment]
az extension update --name aks-preview
No updates available for 'aks-preview'. Use --debug for more information.

**Comment by PramodValavala-MSFT** [comment]
@ianEROAD You are using a pretty old version of Azure CLI (that latest is 2.40.0). Could you try upgrading that to the latest and try again as well, just to be sure.

**Comment by yonzhan** [comment]
route to CXP team
