### ISSUE TITLE
Creating a SIG image definition with security type TrustedLaunchSupported fails

### ISSUE THREAD

**Issue by malt3** [Azure/azure-cli#24142]
## Describe the bug

**Command Name**
`az sig image-definition create`

**Errors:**
```
(InvalidParameter) The value 'TrustedLaunchSupported' for feature 'SecurityType' is invalid. Allowed characters are English alphanumerical characters with spaces and commas. The length of the value cannot exceed 100 characters.
Code: InvalidParameter
Message: The value 'TrustedLaunchSupported' for feature 'SecurityType' is invalid. Allowed characters are English alphanumerical characters with spaces and commas. The length of the value cannot exceed 100 characters.
Target: galleryImage.properties.features

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create SIG
- `az sig image-definition create --resource-group {} -l {} --gallery-name {} --gallery-image-definition {} --publisher {} --offer {} --sku {} --os-type Linux --os-state generalized --hyper-v-generation V2 --features SecurityType=TrustedLaunchSupported`

## Expected Behavior

Image definition should be created successfully. See examples in the docs: https://learn.microsoft.com/en-us/cli/azure/sig/image-definition?view=azure-cli-latest#az-sig-image-definition-create

## Environment Summary
```
Linux-5.15.0-48-generic-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.40.0

Extensions:
ssh 1.0.1
account 0.2.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@malt3 Could you please send the debug log *(add `--debug` parameter)* to me by email? My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by zhoxing-ms** [comment]
Request REST: https://learn.microsoft.com/en-us/rest/api/compute/gallery-images/create-or-update?tabs=HTTP

Request Body
```
{
	"location": "northeurope",
	"tags": {},
	"properties": {
        ......
		"features": [{
			"name": "SecurityType",
			"value": "TrustedLaunchSupported"
		}]
	}
}
```

Response Body
```
{
  "error": {
    "code": "InvalidParameter",
    "message": "The value 'TrustedLaunchSupported' for feature 'SecurityType' is invalid. Allowed characters are English alphanumerical characters with spaces and commas. The length of the value cannot exceed 100 characters.",
    "target": "galleryImage.properties.features"
  }
}
```

**'x-ms-correlation-request-id': '226b0620-7b9d-4703-9015-20071a88337c'**

@kangsun-ctrl For trusted launch, do you know what value of `SecurityType` user should pass in for `--features SecurityType=xxx`?

**Comment by litian1992** [comment]
If you create a image definition with Trusted Launch supported (in portal or anyway), you will see something like below with `az sig image-definition show`:
```
...
  "features": [
    {
      "name": "SecurityType",
      "value": "TrustedLaunch"
    }
  ],
...
```
And so I'm able to create one again using CLI with `SecurityType` equal to `TrustedLaunch`.
But then where I fail to execute is it equal to `TrustedLaunchAndConfidentialVmSupported`. Any help please?

**Comment by zhoxing-ms** [comment]
> And so I'm able to create one again using CLI with SecurityType equal to TrustedLaunch.
But then where I fail to execute is it equal to TrustedLaunchAndConfidentialVmSupported. Any help please?

@AjKundnani Could you please help take a look at this question?

**Comment by sandeepraichura** [comment]
@malt3 @litian1992 - I'm looking into this, and I'll keep you posted soon

**Comment by sandeepraichura** [comment]
Hi @malt3 @litian1992 - TrustedLaunchSupported and TrustedLaunchAndConfidentialVmSupported are not yet supported and we are working on supporting this in the coming months. apologies for the confusion this may have caused.  We are working on updating the docs.
