### ISSUE TITLE
Incorporate `msrestazure`'s code for managed identity authentication

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#24150]
**Related command**

`az login --identity`

**Is your feature request related to a problem? Please describe.**

Managed identity has lots of variations in different services (VM, app service, Azure Arc, hybrid runbook). Each variation requires special handling.

There are feature requests to support new types of managed identities:

- https://github.com/Azure/azure-cli/issues/16573
- https://github.com/Azure/azure-cli/issues/22243

But there are some technical difficulties:

- Azure CLI dropped Azure Identity and now directly uses MSAL for user/service principal authentication
- Currently, Azure CLI uses `msrestazure` for managed identity authentication, but `msrestazure` has been replaced by Azure Identity and out of maintainance
- MSAL has no managed identity support, and it is not planed in the near future (https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/58)

**Describe the solution you'd like**

In order to support new variations of managed identity, Azure CLI needs to incorporate `msrestazure`'s code and make changed on top of that.

**Describe alternatives you've considered**

MSAL to support managed identity.

**Comment by yonzhan** [comment]
managed identity authentication

**Comment by jiasli** [comment]
MSAL has supported managed identity. Azure CLI will use MSAL for managed identity authentication in the future: https://github.com/Azure/azure-cli/pull/25959.
