### ISSUE TITLE
Cosmos DB --network-acl-bypass-resource-ids need to be validated further

### ISSUE THREAD

**Issue by chshihMSFT** [Azure/azure-cli#24156]
**Related command**
az cosmosdb update --name MyCosmosDBDatabaseAccount--resource-group MyResourceGroup--network-acl-bypass AzureServices --network-acl-bypass-resource-ids "/subscriptions/subId/resourceGroups/rgName/providers/Microsoft.Synapse/workspaces/wsName"

**Describe the bug**
It's possible to input resource id without leading '/' in URI, and this cause Cosmos DB Analytical Store to be unable to identify the mentioned resources and by-pass on network acl checking.
Without the leading '/' in resource URI, CLI execution won't report any errors or indicate it's actually an invalid format.
Cosmos DB can still store the invalid URI at last, but no help to allow querying from Synapse.

**To Reproduce**
az cosmosdb update --name MyCosmosDBDatabaseAccount--resource-group MyResourceGroup--network-acl-bypass AzureServices --network-acl-bypass-resource-ids "subscriptions/subId/resourceGroups/rgName/providers/Microsoft.Synapse/workspaces/wsName"

**Expected behavior**
Please validate the input values of --network-acl-bypass-resource-ids, to ensure customer configuring their resource correctly.

## Environment Summary
```
Linux-5.4.0-1091-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.13
Installer: RPM

azure-cli 2.40.0

Extensions:
kusto 0.4.0
cosmosdb-preview 0.17.0
ai-examples 0.2.5
ml 2.7.1
ssh 1.1.2

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@chshihMSFT Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@chshihMSFT The above PR has been filed to address this issue. It is currently under review. If you have any pending concerns in the meantime, please let me know.

**Comment by chshihMSFT** [comment]
Hi @navba-MSFT, @evelyn-ys,
Thanks for the PR merge.
I've executed command ```az upgrade``` to get latest update for CLI modules but looks like the issue still exists; I can still input the resourceId (URI) without leading '/', then leads ill-format configuration in Cosmos DB account.
```
{
  "azure-cli": "2.41.0",
  "azure-cli-core": "2.41.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "ai-examples": "0.2.5",
    "cosmosdb-preview": "0.20.0",
    "kusto": "0.5.0",
    "ml": "2.10.0",
    "ssh": "1.1.2"
  }
}
```

![image](https://user-images.githubusercontent.com/45855145/196329442-91c5e771-f0e4-4ea2-ba5b-766c33ac191a.png)

**Comment by navba-MSFT** [comment]
@chshihMSFT The PR was merged a while ago. The fix is part of this milestone Targeted for 2022-11-01 and not yet released. https://github.com/Azure/azure-cli/milestone/123 .

**Comment by chshihMSFT** [comment]
Thanks! Looking forward to it.

**Comment by claus18** [comment]
A bit unrelated, but my search always end up here.  
- How can I reset a value on --network-acl-bypass-resource-ids  ?
For the --network-acl-bypass  it works by setting to None,   but I have found no value that resets the ids
