### ISSUE TITLE
WAF Policy Managed Rule Exclusion Remove Rule not working as expected

### ISSUE THREAD

**Issue by KapilAnanth-MSFT** [Azure/azure-cli#24169]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az network application-gateway waf-policy managed-rule exclusion rule-set remove

**Describe the bug**

- The above command is supposed to remove a Rule from an exception in Managed Rules Exclusion of App gateway WAF Policy
- However, instead, I notice every other rule under OWASP is getting added to the exclusion

**To Reproduce**

- Add a test exclusion to the Managed Rules from Portal
- Make sure the exclusion contains a Rule from the Managed Rule Group.
- Now, with Azure CLI, execute the above command specifying the Rule Group name to remove it
- Instead of the Rule Group getting removed, I see every rule under OWASP is getting added to the exclusion

**Expected behavior**

The Rule Group associated to the specified exclusion policy should have been removed

**Environment summary**

- Contains an App gateway WAF policy
- I was using OWASP 3.2

**Additional context**
NA

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by KapilAnanth-MSFT** [comment]
@necusjz , may I know if there are any updated on this.

**Comment by necusjz** [comment]
@KapilAnanth-MSFT 
I haven't reproduced this issue yet, my procedures are as follows:
1. Create a waf-policy
```
az network application-gateway waf-policy create -g {rg} -n {waf}
```
2. Add one rule group to exclusion
```
az network application-gateway waf-policy managed-rule exclusion rule-set add -g {rg} --policy-name {waf} --match-variable RequestHeaderNames --match-operator StartsWith --selector Bing --type OWASP --version 3.2 --group-name REQUEST-921-PROTOCOL-ATTACK --rule-ids 921140 921150
```
3. Add another rule group to exclusion
```
az network application-gateway waf-policy managed-rule exclusion rule-set add -g {rg} --policy-name {waf} --match-variable RequestHeaderNames --match-operator StartsWith --selector Bing --type OWASP --version 3.2 --group-name REQUEST-931-APPLICATION-ATTACK-RFI --rule-ids 931100
```
4. Remove the first rule group
```
az network application-gateway waf-policy managed-rule exclusion rule-set remove -g {rg} --policy-name {waf} --match-variable RequestHeaderNames --match-operator StartsWith --selector Bing --type OWASP --version 3.2 --group-name REQUEST-921-PROTOCOL-ATTACK
```

**Comment by KapilAnanth-MSFT** [comment]
@necusjz , I was using Azure Cloudshell to repo this.


1. I am adding a Rule Group Exclusion

`az network application-gateway waf-policy managed-rule exclusion rule-set add -g appGateway --policy-name appGatewayPolicy --match-variable RequestHeaderValues --match-operator Contains --selector kapil --type OWASP --version 3.2 --group-name REQUEST-921-PROTOCOL-ATTACK --rule-ids 921140 921150`

2. I am adding the second Rule Group Exclusion

`az network application-gateway waf-policy managed-rule exclusion rule-set add -g appGateway --policy-name appGatewayPolicy --match-variable RequestHeaderNames --match-operator StartsWith --selector Bing --type OWASP --version 3.2 --group-name REQUEST-920-PROTOCOL-ENFORCEMENT --rule-ids 920340`

3. I am trying to delete the first Rule Group Exclusion

`az network application-gateway waf-policy managed-rule exclusion rule-set remove -g appGateway --policy-name appGatewayPolicy --match-variable RequestHeaderValues --match-operator Contains --selector kapil --type OWASP --version 3.2 --group-name REQUEST-921-PROTOCOL-ATTACK`

4. Post this, I can see all the Rule Groups getting added to the Exclusion.
![image](https://user-images.githubusercontent.com/107474080/196692932-63327018-0ad5-4a36-ba20-a9134e90b7a1.png)

My cloudshell azure-CLI version is 2.41.0

**Comment by necusjz** [comment]
> @necusjz , I was using Azure Cloudshell to repo this.
> 
> 1. I am adding a Rule Group Exclusion
> 
> `az network application-gateway waf-policy managed-rule exclusion rule-set add -g appGateway --policy-name appGatewayPolicy --match-variable RequestHeaderValues --match-operator Contains --selector kapil --type OWASP --version 3.2 --group-name REQUEST-921-PROTOCOL-ATTACK --rule-ids 921140 921150`
> 
> 2. I am adding the second Rule Group Exclusion
> 
> `az network application-gateway waf-policy managed-rule exclusion rule-set add -g appGateway --policy-name appGatewayPolicy --match-variable RequestHeaderNames --match-operator StartsWith --selector Bing --type OWASP --version 3.2 --group-name REQUEST-920-PROTOCOL-ENFORCEMENT --rule-ids 920340`
> 
> 3. I am trying to delete the first Rule Group Exclusion
> 
> `az network application-gateway waf-policy managed-rule exclusion rule-set remove -g appGateway --policy-name appGatewayPolicy --match-variable RequestHeaderValues --match-operator Contains --selector kapil --type OWASP --version 3.2 --group-name REQUEST-921-PROTOCOL-ATTACK`
> 
> 4. Post this, I can see all the Rule Groups getting added to the Exclusion.
>    ![image](https://user-images.githubusercontent.com/107474080/196692932-63327018-0ad5-4a36-ba20-a9134e90b7a1.png)
> 
> My cloudshell azure-CLI version is 2.41.0

I do think it could be a good test scenario and I have reproduced. Fix WIP.

**Comment by KapilAnanth-MSFT** [comment]
@necusjz , @yonzhan

I am able to repo this error with my local machine as well.
I also checked with few colleagues and they were all able to reproduce the issue.

I request you to re-open this thread and check this behavior with the latest Azure CLI.

**Comment by necusjz** [comment]
@KapilAnanth-MSFT Please wait until Azure CLI 2.42.0 is released in 11/01, it'll be fixed by https://github.com/Azure/azure-cli/pull/24322.
