### ISSUE TITLE
Certificate file from az login has to be kept alive

### ISSUE THREAD

**Issue by KarlWindhager** [Azure/azure-cli#24168]
## Describe the bug

I login in via the azure cli using a service principal and a certificate like this:

`$account = az login --service-principal -u $applicationId -p $certPath -t $tenantId`

Then I delete the locally created certificate file to avoid, that the certificate file with private key remains on the host (if my script should fail, is cancelled or anything unexpected happens).

After deleting it I can't use the cli anymore:
**Invalid certificate, please use a valid PEM file. Error detail: [('PEM routines', 'get_name', 'no start line')]**

 I tried the following commands (and I'm pretty sure there are more):
`az webapp show`
`az webapp list-runtimes`
`az functionapp list-runtimes`

Without deleting the certificate file, all of those commands work.
The commands work also as expected, after fogging in via password or an interactive login.

## To Reproduce:
Login with a certificate:
`$account = az login --service-principal -u $applicationId -p $certPath -t $tenantId`

Delete the file '$certPath'

Use any of these commands:
`az webapp show`
`az webapp list-runtimes`
`az functionapp list-runtimes`

## Expected Behavior

A successful login should be cached, regardless of using a certificate or a password, until I logout or my session expires.

## Environment Summary
```
Windows-10-10.0.19042-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.41.0

Extensions:
authV2 0.1.1
azure-devops 0.25.0
ml 2.10.0

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by KarlWindhager** [comment]
Can you say if that issue can be reproduced and if it will be tackled?

**Comment by KarlWindhager** [comment]
bump

**Comment by navba-MSFT** [comment]
@jiasli Could you please share some pointers on this ? Thanks in advance.

**Comment by KarlWindhager** [comment]
Hello everyone,
could you give me an update on that issue.
We do have a (rather ugly) workaround in place, however the actual problem still persists.

Could you investigate it already?
Is there a proper workaround or is the current behavior the intended behavior?

Thanks, Karl

**Comment by jiasli** [comment]
Hi @KarlWindhager, currently this is the intended behavior, as the underlying MSAL library requires `client_credential` (which contains the certificate string) to be constructed and provided when constructing [`msal.application.ConfidentialClientApplication`](https://msal-python.readthedocs.io/en/latest/#confidentialclientapplication), so yes, please do keep the certificate on your disk for Azure CLI to function properly.

As for caching the login session, we can only cache the access token of the service principal, as service principal doesn't have a refresh token. The access token will only last one hour.

If we cache the whole certificate string, it must be copied to Azure CLI's `service_principal_entries` store, which will introduce more complexity and security concerns regarding certificate management.

**Comment by KarlWindhager** [comment]
Ok, thank you for your feedback.
It is rather an issue of cleaning up properly than of security concerns. It is part of a larger framework and runs quite often.

But we will take that information in consideration.
Thank you!

**Comment by rayluo** [comment]
> It is rather an issue of cleaning up properly than of security concerns

Correct.

For the sake of completeness, there is indeed a way to use Service Principal without managing its credential/cert. That is the [Managed Identity](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview). And [Azure CLI supports Managed Identity](https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli#sign-in-with-a-managed-identity), too.

**Comment by xkszltl** [comment]
@rayluo Got some questions/requests regarding this behavior:

> In fact, service principal is meant to be used as a "confidential client" (as compared to "public client"). The former is considered to be able to hold its secret or cert securely. (See also this [specs](https://www.rfc-editor.org/rfc/rfc6749#section-2.1).) If @KarlWindhager has concerns about storing a cert in that environment, the use case might not be suitable for service principal.

I also have the same concern about storing cert.
We would like to store it as tmp file to start the session, and remove afterward, not because of security concern, but because in general it is a bad practice to leave/leak unmanaged files on user disk.
Ideally we would like to have az cli cache the cert file internally for us.

> For the sake of completeness, there is indeed a way to use Service Principal without managing its credential/cert. That is the [Managed Identity](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview). And [Azure CLI supports Managed Identity](https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli#sign-in-with-a-managed-identity), too.

My understanding is that's specific to Azure itself, meaning code won't work on-prem or locally.
That's often a blocking issue for both development and hybrid deployment.
Any solution to those use cases?

**Comment by rayluo** [comment]
> I also have the same concern about storing cert.
> We would like to store it as tmp file to start the session, and remove afterward, not because of security concern, but because in general it is a bad practice to leave/leak unmanaged files on user disk.

Solutions and limitations have been mentioned in earlier messages. [This doc](https://learn.microsoft.com/en-us/entra/identity-platform/msal-client-applications) also describes the differences between the two types of clients, also how to manage confidential client's secrets. If deploying a cert to your user's machine is concerning (and rightfully so), you may revisit whether your app could switch from "confidential client" to "public client" and then do "az login" as a user.

P.S.: Your follow up questions, if any, shall probably be a new post on Stackoverflow, such as [this one](https://stackoverflow.com/questions/36317292/azure-ad-differentiate-between-app-token-and-user-token).

The current github issue can probably be locked.
