### ISSUE TITLE
what-if seems to be ignoring some properties

### ISSUE THREAD

**Issue by tholmesdev** [Azure/azure-cli#24163]
**Related command**
az deployment group what-if

**Describe the bug**
The what-if analysis seems to ignore some properties or incorrectly report they not yet set. For example, I'll create an app service with a `siteConfig` via bicep template and when I run the what-if analysis afterwards, it says the `siteConfig` values are not yet set. Am I missing something or is this by design and there's a limitation to be accepted with the what-if analysis? I'm looking to utilize bicep for azure resource creation and am starting with existing resources.

**To Reproduce**
Using bicep with a single module to create an app service plan and app service.

```bicep
resource appServicePlan 'Microsoft.Web/serverFarms@2022-03-01' = {
  name: 'myAppServicePlan'
  location: location
  sku: {
    name: 'F1'
  }
}

resource appServiceApp 'Microsoft.Web/sites@2022-03-01' = {
  name: 'myAppService'
  location: location
  properties: {
    serverFarmId: appServicePlan.id
    httpsOnly: true
    siteConfig:{
      cors: {
        allowedOrigins: ['https://{some-site.domain}.com']
      }
    }
  }
}
```

1. Run `az deployment group create --template-file .\main.bicep -g {rg-yourrg} --parameters environmentName=test location=centralus`
2. Observe that the asp and app have been created, including the cors allowed origin
![image](https://user-images.githubusercontent.com/73268658/195202223-d924d07f-abb9-459b-94a0-e1d01a20b210.png)
3. Run `az deployment group create --template-file .\main.bicep -g {rg-yourrg} --parameters environmentName=test location=centralus -c`
4. Observe that the what-if analysis says the cors allowed origin is new and will be added, even though it already exists
![image](https://user-images.githubusercontent.com/73268658/195202315-c3437cba-f7b1-4e3c-a933-f57d6253198d.png)

**Expected behavior**
1. Run `az deployment group create --template-file .\main.bicep -g {rg-yourrg} --parameters environmentName=test location=centralus`
2. Observe that the asp and app have been created, including the cors allowed origin
3. Run `az deployment group create --template-file .\main.bicep -g {rg-yourrg} --parameters environmentName=test location=centralus -c`
4. Observe that the what-if analysis says there are no modifications to be made

**Environment summary**

azure-cli `2.40.0`
OS Windows 10 `19042`
Shell Type `PowerShell`

**Comment by yonzhan** [comment]
route to CXP team

**Comment by zhoxing-ms** [comment]
@shenglol Could you please help take a look at the `what-if` related issue?

**Comment by tholmesdev** [comment]
Hello, any update on this? Thanks!

**Comment by navba-MSFT** [comment]
Adding Service team to look into this. 

@shenglol @josephkwchan, @jennyhunter-msft Could you please assist on this ? Thanks in advance.

**Comment by shenglol** [comment]
This is due the web RP not returning `siteConfig` in GET responses because. It is a known service provider issue and is tracked by https://github.com/Azure/arm-template-whatif/issues/265. Unfortunately, there is no workaround we can do on the What-If side. @zhoxing-ms Feel free to close this since we are tracking it in the What-If issues repo.

**Comment by navba-MSFT** [comment]
@tholmesdev Tracking this here https://github.com/Azure/arm-template-whatif/issues/265
