### ISSUE TITLE
az resource lock not accepting resource id for Microsoft.ContainerRegistry/registries resource

### ISSUE THREAD

**Issue by herbeck558** [Azure/azure-cli#24161]
## Describe the bug
any az resource lock command will not accept the fully qualified resource name to my container registry.
az lock list --resource /subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.ContainerRegistry/registries/{containerregistry} 
returns an error 
**Command Name**
`az resource lock list`

**Errors:**
```
--resource-type is required if the name, --resource, is present

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `ACR_NAME=myregistry`
- `ACR_REGISTRY_ID=$( az acr show --name $ACR_NAME --query "id" --output tsv)`
-  `echo $ACR_REGISTRY_ID`
- `az resource lock list --resource $ACR_REGISTRY_ID`
- echo $REGISTRY_ID

## Expected Behavior
If --resource is a fully qualified resource id (with a type and a resource group embedded in it) it should use that and not ask for other fields.  Even if i put the other fields 

## Environment Summary
```
macOS-12.6-arm64-arm-64bit, Darwin 21.6.0
Python 3.10.7
Installer: HOMEBREW

azure-cli 2.40.0

Extensions:
init 0.1.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@herbeck558 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@herbeck558 I was able to run the below command and get the details without any errors:

>**az resource lock list --resource $ACR_REGISTRY_ID**
[
  {
    "id": "/subscriptions/XXXXXXXXX0/resourcegroups/MyRG/providers/Microsoft.ContainerRegistry/registries/MyACRName/providers/Microsoft.Authorization/locks/test",
    "level": "ReadOnly",
    "name": "test",
    "notes": "",
    "owners": null,
    "resourceGroup": "MyRG",
    "type": "Microsoft.Authorization/locks"
  }
]

Could you please use the [TryIt option here](https://learn.microsoft.com/en-us/cli/azure/resource/lock?view=azure-cli-latest#code-try-8) and check if the issue occurs on Azure Cloud Shell too ? Awaiting your reply.

**Comment by herbeck558** [comment]
@navba-MSFT it works in the cloud shell just fine with the commands i gave you. 
So here's the missing peice of the puzzle -
before i did any of this i set my default resource group using something like:
RG_NAME=my_rg_name
az config set defaults.group=$RG_NAME
where my_rg_name is my actual resource group name where the ACR is created at.
Then run the commands i get the error.  This i recreated in the cloud shell as well.   I noticed the experimental warning on the az config command - having that set that must be messing up use of a fully qualified resource id on the resource lock command?   running 'az config unset defaults.group' allows my resource lock commands to work.

**Comment by navba-MSFT** [comment]
@herbeck558 Thanks for your reply.

That's an expected behavior because the Resource Group is implicitly used by the AzCLI (from the config), it will be similar to running the below command:

>az resource lock list -g MyRgName --resource /subscriptions/XXXXXXXXX/resourceGroups/MyRGName/providers/Microsoft.ContainerRegistry/registries/MyACRName 

And this is expected to fail with the below error:
>cli.azure.cli.core.azclierror: --resource-type is required if the name, --resource, is present

Configuration values used by the CLI are evaluated in the following precedence, with items higher on the list taking priority.
1. Command-line parameters
2. Parameter persisted values set with az config param-persist
3. Environment variables
4. Values in the configuration file set with az config or az init

Hope this answers.

**Comment by navba-MSFT** [comment]
@herbeck558 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any further queries on this. Awaiting your reply.

**Comment by herbeck558** [comment]
@navba-MSFT  sorry i just got back to this.  I understand now what its doing but the error message is kinda off and could be improved - its says i need to specify --resource-type if I have --resource but that's confusing.  It could say 'if resource-group' is specified for example.  Or have a diff parameter for fully-qualified resource path vs a resource-name only. 
But now i know and will adjust as needed here - Thanks!
