### ISSUE TITLE
'az network front-door rules-engine rule condition add' command fails for GeoMatch with Country List

### ISSUE THREAD

**Issue by adsathye** [Azure/azure-cli#24160]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az network front-door rules-engine rule condition add `
        -f $Name `
        -g $ResourceGroup `
        --rules-engine-name $RulesEngineName `
        --name $RuleName `
        --match-variable RemoteAddr `
        --operator GeoMatch `
        --match-values ["AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR"] `
        --negate-condition false

**Describe the bug**
ERROR: (BadRequest) Rules Engines validation failed. More information: AT BE BG HR CY CZ DK EE FI FR are not supported country codes..
Code: BadRequest
Message: Rules Engines validation failed. More information: AT BE BG HR CY CZ DK EE FI FR are not supported country codes..

**To Reproduce**
Execute rule condition add command with multiple country codes as match-values.
az network front-door rules-engine rule condition add `
        -f $Name `
        -g $ResourceGroup `
        --rules-engine-name $RulesEngineName `
        --name $RuleName `
        --match-variable RemoteAddr `
        --operator GeoMatch `
        --match-values ["AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR"] `
        --negate-condition false

**Expected behavior**
Front door rule with geo match condition with multiple countries should be created.

**Environment summary**
azure-cli                         2.40.0
 
 core                              2.40.0
 telemetry                          1.0.8
 
 Extensions:
 azure-devops                      0.25.0
 
 Dependencies:
 msal                            1.18.0b1
 azure-mgmt-resource             21.1.0b1

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@adsathye Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by t-bzhan** [comment]
Hi @adsathye , it seems that you are not using the correct way to pass in multiple-value arguments.  You are suggested to use space-separated list of values for --match-values:
![image](https://user-images.githubusercontent.com/61817681/195246892-a470b4d7-6f96-4911-9330-d823dcc17c6f.png)

Instead of using:

> az network front-door rules-engine rule condition add -f $Name
> -g $ResourceGroup --rules-engine-name $RulesEngineName
> --name $RuleName --match-variable RemoteAddr
> --operator GeoMatch --match-values ["AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR"]
> --negate-condition false

Could you try:

> az network front-door rules-engine rule condition add -f $Name
> -g $ResourceGroup --rules-engine-name $RulesEngineName
> --name $RuleName --match-variable RemoteAddr
> --operator GeoMatch --match-values "AT" "BE" "BG" "HR" "CY" "CZ" "DK" "EE" "FI" "FR"
> --negate-condition false

Or using the [splatting ](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.2)to pass list as multiple arguments like below

> $regions = @("AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR")
> az network front-door rules-engine rule condition add -f $Name
> -g $ResourceGroup --rules-engine-name $RulesEngineName
> --name $RuleName --match-variable RemoteAddr
> --operator GeoMatch --match-values @regions 
> --negate-condition false

**Comment by navba-MSFT** [comment]
Thanks @t-bzhan .

@adsathye Could you please try the above suggestion provided in the above comment and let us know if you still face this issue ? Awaiting your reply.

**Comment by adsathye** [comment]
This still does not work with Azure CLI version 2.40.0 but, I can now see it works with new version released yesterday 2.41.0. The same script worked for couple of years. It seems to be problem with one particular version.

**Comment by t-bzhan** [comment]
@adsathye , that might be related to https://github.com/Azure/azure-cli/issues/23797#issuecomment-1238997338, Azure CLI has made some changes in 2.40.0 regarding to passing PowerShell arrays as multiple values argument to CLI.
