### ISSUE TITLE
How are role assignment name guids generated?

### ISSUE THREAD

**Issue by CosX** [Azure/azure-cli#24170]
My team is currently migrating parts of our infrastructure from az cli to bicep. We want the process of switching over to bicep as smooth as possible, however we're experiencing some validation errors with role assignments. "The role assignment already exists". I've read the Microsoft docs on how to make role assigments idempotent with ARM/bicep with the use of guid(). Is it possible to know the format of how to generate this guid in a similar way that az cli does it?

**Comment by yonzhan** [comment]
role assignment

**Comment by PramodValavala-MSFT** [comment]
@CosX I believe the default IDs are just standard GUIDs which is what the `guid()` function in bicep should also generate.

**Comment by matsest** [comment]
The function used in az cli is Pythons `uuid.uuid64()` (see implementation here https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/role/custom.py#L1581)

So it's random upon role assignment creation in az cli.. If you're creating them idempotently with `guid(<argument1>, <argument2>)` in Bicep you need to remove the ones created with az cli first.
