### ISSUE TITLE
Confusing help text for config file

### ISSUE THREAD

**Issue by jdkr0220** [Azure/azure-cli#24172]
For the `az repos policy create` command, the `--config` command lists this help text: "Local file path for configuration file. Please use / backslash when typing in directory path.". Note the appearance of the "/" character and the word "backslash". It's not clear which should be used and/or if it is platform dependent. The same helptext confusion appears in the the `az repos policy create --help` command.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81eb6db8-249f-2ab0-963c-7e9141191dc6
* Version Independent ID: 417fb6c8-75ea-c351-ac79-504405fcac2f
* Content: [az repos policy](https://learn.microsoft.com/en-us/cli/azure/repos/policy?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/repos/policy.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/repos/policy.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@jdkr0220 The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
