### ISSUE TITLE
[Question] Is there any way to list all the supported features in the gallery image-definition?

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/azure-cli#24178]
**Related command**
az sig image-definition -h

**Is your feature request related to a problem? Please describe.**
I cannot find a doc or any help messages that can list all the supported features in the gallery image-definition. Even in https://learn.microsoft.com/en-us/cli/azure/sig/image-definition?view=azure-cli-latest there are only some examples but no clear features list. 
When I create image-definition with a wrong feature(e.g. --features SecurityType=A) it only shows:
```
Message: The value 'A' for feature 'SecurityType' is invalid. Allowed characters are English alphanumerical characters with spaces and commas. The length of the value cannot exceed 100 characters.
Target: galleryImage.properties.features
```

**Is there any way to show the supported features list?** Thanks!

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by MichalSino** [comment]
@zhoxing-ms  Any news about this?

**Comment by zhoxing-ms** [comment]
@kangsun-ctrl May I ask if you can provide features supported by service, or provide relevant documentation link to allow CLI to add it to the help message?

**Comment by MichalSino** [comment]
@zhoxing-ms I found here something, may be it can help https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sig/image-definition.yml

**Comment by sandeepraichura** [comment]
Thank you for the feedback, we will review how this can be addressed at the API.

**Comment by sandeepraichura** [comment]
The API may take time, but we are working on updating the docs with the list of supported features.

**Comment by sandeepraichura** [comment]
The list of features and accepted values are updated here: https://learn.microsoft.com/en-us/azure/virtual-machines/shared-image-galleries?tabs=azure-cli#image-definitions

Closing this for now, reopen if it didn't answer your question.
