### ISSUE TITLE
az vm run-command invoke --no-wait report unrecognized arguments: --no-wait

### ISSUE THREAD

**Issue by wbypai** [Azure/azure-cli#24184]
az vm run-command invoke --no-wait -g UBUNTU -n UBUNTU --command-id RunShellScript --scripts 'echo $1 $2' --parameters hello world 
unrecognized arguments: --no-wait

remove --no-wait cab be work
az vm run-command invoke -g UBUNTU -n UBUNTU --command-id RunShellScript --scripts 'echo $1 $2' --parameters hello world           
 / Running ..

 az version
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "account": "0.2.3",
    "aks-preview": "0.5.100",
    "automation": "0.1.1",
    "k8s-extension": "1.2.2",
    "ssh": "1.1.1"
  }
}

btw test in az cli 2.41.0. the issue disappear

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by blueboxes** [comment]
I am still seeing this on version 2.49

**Comment by zhoxing-ms** [comment]
@blueboxes Could you please send the debug log *(add `--debug` parameter)* to me? My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by blueboxes** [comment]
Thanks for your quick response, I have sent you an email.

**Comment by zhoxing-ms** [comment]
@blueboxes Thank you for providing the debug log. I found that the `--no-wait` parameter is not supported by the `az resource invoke-action` command *(not `az vm run-command invoke`)* in the log. 
If you need the `az resource invoke-action` command to also support the `--no-wait` parameter, please help submit a new Github issue to help us follow up on this requirement.

**Comment by blueboxes** [comment]
Thanks, good spot. I have found an existing request for this  #21190
