### ISSUE TITLE
az grafana update command is throwing 'update' is misspelled or not recognized by the system.

### ISSUE THREAD

**Issue by docast** [Azure/azure-cli#24182]
<> While trying to update the Managed grafana using "az grafana update", getting error:

[root@xxxxxxxxxxxxxxxxxxx 0]# az grafana update --name dev-grafana --api-key Enabled
'update' is misspelled or not recognized by the system.

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs

<> Able to run commands like "az grafana create", "az grafana user list", "az grafana show" command, however, "az grafana update" is throwing the above error. 

<> The managed identity used has Grafana admin Role based access to Grafana setup.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 045ea646-7299-b619-3b8f-4a5d66161298
* Version Independent ID: 0db3c5ae-b8a2-5160-909a-b762979ed500
* Content: [az grafana](https://learn.microsoft.com/en-us/cli/azure/grafana?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/grafana.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/grafana.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@docast Looks like the `update` sub-command has been added in recently. Could you try upgrading the extension to the latest version by running the following command and try again?

```sh
az extension update --name amg
```

**Comment by docast** [comment]
@PramodValavala-MSFT : I executed  "az extension update --name amg", but no update available.
No updates available for 'amg'. Use --debug for more information.

With my account, I am able to run the above command. However with the user Managed Identity account, az grafana update is failing. The User managed Identity account has owner rights at subscription level and Grafana Admin access at managed grafana resource level.

**Comment by PramodValavala-MSFT** [comment]
@docast Thanks for the details! The error is from Azure CLI itself, so I doubt it would be related to the access the Managed Identity has.

Are you running the command using your personal account from the same prompt? Based on the prompt, I would guess you are running within a container?

Could you run and share the output for `az grafana --help`? Does it include `update` under commands?
