### ISSUE TITLE
az deployment mg create --mode

### ISSUE THREAD

**Issue by petr-stupka** [Azure/azure-cli#24193]
**Related command**
Please add `--mode` support for `az deployment mg create`

**Is your feature request related to a problem? Please describe.**
It is not related to any problem

**Describe the solution you'd like**
Having possibility to create `Complete` deployment instead of default `Incremental` mode. Example when deploying Azure Policies and RBAC Role Assignments. They sometimes require manual cleanup.

**Describe alternatives you've considered**
Alternative may be to use `az deployment mg delete` before, to clean up resources, however it is not convenient in case of deploying Azure Policies to Management Group. There will be "downtime" of Azure Policies between `delete` and `create` operation

**Additional context**
Thank you!

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness
