### ISSUE TITLE
az aks check-acr: FAILURE - KeyError: 'serverVersion'

### ISSUE THREAD

**Issue by ryanbick** [Azure/azure-cli#24190]
## Describe the bug
**az aks check-acr --resource-group ih-aks --name *** --acr ***.azurecr.io**

**Command Name**
`az aks check-acr`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'serverVersion'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acs/custom.py", line 1294, in aks_check_acr
KeyError: 'serverVersion'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks check-acr --resource-group {} --name {} --acr {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.41.0

Extensions:
azure-devops 0.22.0
ssh 1.0.0

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by PramodValavala-MSFT** [comment]
@ryanbick The command internally calls `kubectl version -o json`. Could you run this command and share its output?

**Comment by ryanbick** [comment]
What application or tool is the version difference warning referring to?

{
"clientVersion": {
"major": "1",
"minor": "25",
"gitVersion": "v1.25.0",
"gitCommit": "a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2",
"gitTreeState": "clean",
"buildDate": "2022-08-23T17:44:59Z",
"goVersion": "go1.19",
"compiler": "gc",
"platform": "windows/amd64"
},
"kustomizeVersion": "v4.5.7",
"serverVersion": {
"major": "1",
"minor": "23",
"gitVersion": "v1.23.8",
"gitCommit": "e18a4970ca206398e987600929fec300cb85d0ca",
"gitTreeState": "clean",
"buildDate": "2022-09-16T05:13:38Z",
"goVersion": "go1.17.11",
"compiler": "gc",
"platform": "linux/amd64"
}
}WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
------- Original Message -------

**Comment by ryanbick** [comment]
Also, here is the full output with the first few lines also included.

PS C:\Users\Ryan> kubectl version -o json
W1013 13:57:01.702272 8356 azure.go:92] WARNING: the azure auth plugin is deprecated in v1.22+, unavailable in v1.26+; use https://github.com/Azure/kubelogin instead.
To learn more, consult https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
{
"clientVersion": {
"major": "1",
"minor": "25",
"gitVersion": "v1.25.0",
"gitCommit": "a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2",
"gitTreeState": "clean",
"buildDate": "2022-08-23T17:44:59Z",
"goVersion": "go1.19",
"compiler": "gc",
"platform": "windows/amd64"
},
"kustomizeVersion": "v4.5.7",
"serverVersion": {
"major": "1",
"minor": "23",
"gitVersion": "v1.23.8",
"gitCommit": "e18a4970ca206398e987600929fec300cb85d0ca",
"gitTreeState": "clean",
"buildDate": "2022-09-16T05:13:38Z",
"goVersion": "go1.17.11",
"compiler": "gc",
"platform": "linux/amd64"
}
}WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1

------- Original Message -------

**Comment by PramodValavala-MSFT** [comment]
@ryanbick The version difference is between client (kubectl) and server (k8s).

I wasn't able to reproduce this issue locally. Since you are running this on Azure CLI, could you confirm if you are seeing the same locally?
