### ISSUE TITLE
Key Vault: Create command accepts any value for --enabled-for-* flag as true

### ISSUE THREAD

**Issue by amitbapat** [Azure/azure-cli#2420]
az keyvault create --resource-group demo9300 --name demo9371 --sku premium --location  westus **--enabled-for-deployment 0 --enabled-for-disk-encryption 0** --enabled-for-template-deployment 1 --tags tag1=vaule1 tag2=value2

Irrespective of the value provided for parameters --enabled-for-* it's treated as 'true'.

**Comment by tjprescott** [comment]
These will be treated as "three state flags", meaning you can specify true or false (and nothing else) OR you can treat it like a flag (in which case it will be as if you specified true).
