### ISSUE TITLE
Direct shared gallery share with sub example command is incorrect

### ISSUE THREAD

**Issue by sandeepraichura** [Azure/azure-cli#24215]
In the example in the following link, there is parameter “--gallery-image-definition” which is not supported when adding share and needs to be removed otherwise the command will not succeed.

https://learn.microsoft.com/en-us/cli/azure/sig/share?view=azure-cli-latest

az sig share add --resource-group MyResourceGroup --gallery-name MyGallery
--gallery-image-definition MyImage \
--subscription-ids subId1 subId2 --tenant-ids tenantId1 tenantId2

**Related command**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness
