### ISSUE TITLE
Key Vault: Cannot set Enabled-For-* options AFTER a key vault is created.

### ISSUE THREAD

**Issue by amitbapat** [Azure/azure-cli#2421]
az keyvault set-policy 

This command does not accept --enabled-for-* options. Equivalent PSH command allows user to set the EnabledFor* options.

For example,
Set-AzureRmKeyVaultAccessPolicy [-VaultName] <String> [[-ResourceGroupName] <String>] [-EnabledForDeployment] [-EnabledForDiskEncryption]
[-EnabledForTemplateDeployment] [-PassThru] [-Confirm] [-WhatIf] [<CommonParameters>]

**Comment by tjprescott** [comment]
You can actually set these options:
`az keyvault update -g {rg} -n {vault} --set properties.enabledForDiskEncryption={value}`

However, we will expose convenience parameters here as well.

**Comment by amitbapat** [comment]
That’s a little hokey and also it’s not documented in the command-line help. I think it’s better to offer direct command line options just like PSH does.
Also we do offer command line option for the same flags while creating the vault, so why not offer them during update?

**Comment by tjprescott** [comment]
@amitbapat generic update is a standard feature in the CLI, so it would not be documented within KeyVault itself. The coming PR will in fact expose the flags as convenience parameters. I was merely pointing out how to unblock your scenario.
