### ISSUE TITLE
Remove TVMSupported and TVMandCVMSupported from CLI examples for SIG

### ISSUE THREAD

**Issue by sandeepraichura** [Azure/azure-cli#24214]
In the following examples for SIG image definition, TrustedLaunchSupported and TrustedLaunchAndConfidentialVmSupported are not ready yet and need to be removed.

https://learn.microsoft.com/en-us/cli/azure/sig/image-definition?view=azure-cli-latest#az-sig-image-definition-create

az sig image-definition create --resource-group MyResourceGroup \
--gallery-name MyGallery --gallery-image-definition MyImage \
--publisher GreatPublisher --offer GreatOffer --sku GreatSku \
--os-type linux --os-state Specialized \
--features SecurityType=TrustedLaunchSupported

az sig image-definition create --resource-group MyResourceGroup \
--gallery-name MyGallery --gallery-image-definition MyImage \
--publisher GreatPublisher --offer GreatOffer --sku GreatSku \
--os-type linux --os-state Specialized \
--features SecurityType=TrustedLaunchAndConfidentialVmSupported

**Related command**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
Since these examples are introduced by @olayemio in PR #19270, @olayemio could you help to confirm that these examples should be removed?
