### ISSUE TITLE
az aks nodepool list returns null for minCount and maxCount

### ISSUE THREAD

**Issue by wasker** [Azure/azure-cli#24216]
**Describe the bug**

Output of `az aks nodepool list` command shows `null` for `minCount` and `maxCount` values of the node pool. Could be related to AKS version in use.

**To Reproduce**

`az aks nodepool list --cluster-name mycluster --resource-group myrg --query "[?osType=='Linux' && osSku=='Ubuntu']" --output json --only-show-errors`

On k8s 1.23.12:

```
"maxCount": null,

"maxPods": 30,
"messageOfTheDay": null,

"minCount": null,

"mode": "System",
"name": "nodepool1",
"networkProfile": null,
"nodeImageVersion": "AKSUbuntu-1804containerd-2022.09.22",
"nodeLabels": null,
"nodePublicIpPrefixId": null,
"nodeTaints": null,
"orchestratorVersion": "1.23.12",
```

**Expected behavior**

On k8s 1.23.5:

```
"maxCount": 3,

"maxPods": 30,
"messageOfTheDay": null,

"minCount": 1,

"mode": "System",
"name": "nodepool1",
"networkProfile": null,
"nodeImageVersion": "AKSUbuntu-1804containerd-2022.09.22",
"nodeLabels": null,
"nodePublicIpPrefixId": null,
"nodeTaints": null,
"orchestratorVersion": "1.23.5",
```

**Environment summary**

Azure Cloud Shell, az CLI v2.40, aks-preview v0.5.106

**Comment by yonzhan** [comment]
route to CXP team

**Comment by wasker** [comment]
Update: the nodepool had autoscaler disabled, which results in this behavior.
