### ISSUE TITLE
Key Vault: Set attributes on a cert

### ISSUE THREAD

**Issue by amitbapat** [Azure/azure-cli#2422]
Set attributes on a cert

Fails to set enabled to false
`az keyvault certificate set-attributes --enabled false -n cert-import --vault-name cli20vault`

Fails to set expires date
`az keyvault certificate set-attributes -n cert-import --vault-name cli20vault --expires 2017-12-31T01:02:03Z`

Fails to set not-before date
`az keyvault certificate set-attributes -n cert-import --vault-name cli20vault --not-before 2017-12-31T01:02:03Z`

**Comment by tjprescott** [comment]
The CLI is sending the correct PATCH request to the server, but the service is not processing the contents:

**msrest.http_logger : Request URL: 'https://tjp-keyvault-test.vault.azure.net/certificates/cert1/?api-version=2016-10-01'**
msrest.http_logger : Request method: 'PATCH'
msrest.http_logger : Request headers:
msrest.http_logger :     'x-ms-client-request-id': '3fa4dcec-080a-11e7-917e-a0b3ccf7272a'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Content-Length': '53'
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Authorization': '<Redacted>'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'User-Agent': 'python/3.5.1 (Windows-10-10.0.14393-SP0) requests/2.9.1 msrest/0.4.6 msrest_azure/0.4.7 keyvaultclient/0.1.0 Azure-SDK-For-Python'
msrest.http_logger : Request body:
**msrest.http_logger : {"attributes": {"enabled": false, "exp": 1514764800}}**

The body contains a serialized CertificateUpdateParameters object, which is being correctly populated by the CLI and serialized by the SDK.

This looks like a service bug to me.

**Comment by amitbapat** [comment]
@Scott<mailto:scottcot@exchange.microsoft.com> can probably designate someone to take a look

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by tjprescott** [comment]
It turns out that enabled stats is being updated correctly; however, you may be looking at the enabled status within the certificate policy, which is not what the command sets.  Additionally, the `expires` and `not-before` fields are apparently read only, so that is why they do not update.  We will suppress them.
