### ISSUE TITLE
az acr login - fail

### ISSUE THREAD

**Issue by chrom** [Azure/azure-cli#24228]
## Bug  Description  

Problem with login

**Command Name**
`az acr login`

**Errors:**
```
'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/parameters.py, ln 136, in get_resources_in_subscription
    rcf = get_mgmt_service_client(cli_ctx, ResourceType.MGMT_RESOURCE_RESOURCES)
cli/core/commands/client_factory.py, ln 74, in get_mgmt_service_client
    **kwargs)
cli/core/commands/client_factory.py, ln 176, in _get_mgmt_service_client
    logger.debug('Getting management service client client_type=%s', client_type.__name__)
AttributeError: 'NoneType' object has no attribute '__name__'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- az login
- az account set --subscription *********
- az acr login -n **************

## Expected Behavior
- login

## Environment Summary
```
Linux-5.14.21-150400.24.21-default-x86_64-with-glibc2.3.4
Python 3.6.15
Installer: PIP
OponSUSE 15.4

azure-cli 2.17.1 *

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@chrom Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@chrom I see that you are using an older version of Azure CLI. Could you please upgrade to the [most recent version ](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli)of the AzCLI and check if you still see the same issue ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@chrom I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@chrom I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by estebanreyl** [comment]
I tried using the above CLI version and run the steps to reproduce but was unable to. The package issues outlined in the error could however to indicate an improper CLI installation

**Comment by navba-MSFT** [comment]
@chrom The action is currently pending on you to try the most recent AzCLI and check if that helps. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by chrom** [comment]
close this issue pls
