### ISSUE TITLE
`az lab create vm` command fails with "The system cannot find the file specified." error 

### ISSUE THREAD

**Issue by DanBrown-TechSmith** [Azure/azure-cli#24233]
## Describe the bug
The command works in Azure CLI 2.40 but fails in 2.41

**Command Name**
```
az lab vm create --lab-name $LabName --resource-group $LabResourceGroup `
                --image-type custom `
                --image $image.name `
                --name $VMName `
                --size $VMSize `
                --disk-type 'Premium' `
                --admin-username $VMAdminUser `
                --admin-password $VmAdminPassword `
                --debug
```

**Errors:**
```
az : The system cannot find the file specified.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

We have a PowerShell script that executes this CLI command to create a DevTest lab VM from an existing custom image.
When run under Azure CLI 2.40, it succeeds but it fails when using CLI 2.41.
This script is part of an Azure DevOps pipeline and started failing when the hosted Azure Pipelines agents were updated to Azure CLI 2.41 recently.

I have no idea what file it is referring to in the error.

## Expected Behavior
The specified VM is created in the DevTest Lab

## Environment Summary
```
Windows-10-10.0.22623-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.41.0

Extensions:
azure-devops 0.25.0
image-gallery 0.1.3
vm-repair 0.4.6

Dependencies:
msal 1.20.0b1
azure-mgmt.-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@DanBrown-TechSmith Could you share the complete output that you see? Also, try running the command by passing `--debug` to enable debug logs as well.

**Comment by DanBrown-TechSmith** [comment]
After further experimentation, I have determined that the issue is related to the transition from a CMD launch script and a PS1 launch script for the AZ commands. It relates to this issue #24015.
The 2.40 CLI ends up using the az.ps1 script whereas 2.41 uses the az.cmd due to the rename of the PS1 script as detailed in that issue.
If I replace `az lab vm create` with `azps lab vm create` when using 2.41, it works fine.

This is the extent of the debug output:
```
az : The system cannot find the file specified.
At D:\Projects_Git\TechSmith\Tools-Build-DTL\scripts\CreateLabVMFromImage.ps1:229 char:17
+ ...             az lab vm create --lab-name $LabName --resource-group $La ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The system cann...file specified.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

The really odd thing is that it only seems to be that specific command that fails since we run other AZ commands in the same script without issue.

**Comment by PramodValavala-MSFT** [comment]
@DanBrown-TechSmith Thanks for sharing your findings here! That is odd to see that only one command fails, and like I've thought earlier, the error is about not finding `az` itself.

Glad to see that you have resolved your immediate issue! You could perhaps try a clean install of Azure CLI just to make sure everything is correct or try out some of the checks [here](https://github.com/Azure/azure-cli/issues/19202). Closing this issue.
