### ISSUE TITLE
Unable to Delete Custom Domain from Storage Account per Documentation

### ISSUE THREAD

**Issue by emu7800** [Azure/azure-cli#24234]
Deleting a custom domain from a storage account by specifying "" does not work as described by the documentation. Instead, the Azure CLI returns "argument --custom-domain: expected one argument".  Version 2.41.0

https://learn.microsoft.com/en-us/azure/storage/blobs/storage-custom-domain-name?tabs=azure-cli
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92115d19-d7a0-93a8-bf2b-5126d1cddcd0
* Version Independent ID: a657f09b-e1ac-12a2-4b9c-7aaa1f0e3f5c
* Content: [az storage account](https://learn.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/storage/account.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/account.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by MoChilia** [comment]
@emu7800 
If you use PowerShell as the terminal to run Azure CLI commands, please use `'""'` instead of `""` when your value is an empty string. You can refer to [Quoting issues with PowerShell](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md) for more information.
