### ISSUE TITLE
`az login` fails to connect even though internet connection works

### ISSUE THREAD

**Issue by kfirf-cyera** [Azure/azure-cli#24276]
## Describe the bug
When running `az login` from terminal it fails, producing the backtrace with most recent call:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104ee5e10>: Failed to establish a new connection: [Errno 54] Connection reset by peer'))

Trying to curl this url from the same terminal (and browsing link from browser) seems to work just fine, which indicates no real internet connection issue. 
Running `brew reinstall azure-cli` and then re-run the az login doesn't help.

**Command Name**
`az login`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
macOS-12.5-arm64-arm-64bit, Darwin 21.6.0
Python 3.10.8
Installer: HOMEBREW

azure-cli 2.41.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
`Connection reset by peer` is definitely a network issue.

Could you run this command to see if you can connect to `https://login.microsoftonline.com` with `python`?

```
python -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
```

**Comment by kfirf-cyera** [comment]
seems indeed it was a proxifier configured specifically for python and proxy was down.

Thanks!
