### ISSUE TITLE
Can't set environment variables  --set-env-vars

### ISSUE THREAD

**Issue by mbiernatek** [Azure/azure-cli#24287]
Can't make  az containerapp update to work with --set-env-vars. Trying to do something like this:
```
az containerapp update \
                --name appscontainer-app \
                --set-env-vars test=testvalue \
                --resource-group test-resourcegroup ...
```
				
but getting error: ERROR: unrecognized arguments: --set-env-vars test=testvalue.

Without --set-env-vars test=testvalue script works ok.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a547dc79-17cc-2b4f-da2f-10021075c355
* Version Independent ID: ba7c6a08-bb0f-622e-8876-08788dca02ba
* Content: [az containerapp](https://learn.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/containerapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/containerapp.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@mbiernatek Could you ensure you are the latest version of Azure CLI and the `containerapp` extension by running `az upgrade`, and try again?

The latest version of Azure CLI is `2.41.0` and the `containerapp` extension is `0.3.13`, which you can check using the `az version` command.

**Comment by mbiernatek** [comment]
@PramodValavala-MSFT below output from az version. Unfortunately I'm running script from Microsoft-hosted agents and az upgrade is probalby don't an option for me. What shuld i do in that case? 

 `{
  "azure-cli": "2.41.0",
  "azure-cli-core": "2.41.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "azure-devops": "0.25.0"
  }
}
`

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@mbiernatek Looks like you are on the latest version of Azure CLI but don't see the `containerapp` extension installed. Are you installing a particular version of the extension?

The following command will install the latest version of the extension
```sh
az extension install --name containerapp
```
