### ISSUE TITLE
group invalid command

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-cli#2428]
trying to create new resource group using `az group create` 

```
$ az group create --location westus --name testingazgroupcreate
usage: az [-h] [--output {json,tsv,list,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {storage,network,account,vm,appservice,vmss,resource,cloud,logout,acr,role,acs,tag,ad,provider,context,container,component,feedback,login,configure}
          ...
az: error: argument _command_package: invalid choice: 'group' (choose from 'storage', 'network', 'account', 'vm', 'appservice', 'vmss', 'resource', 'cloud', 'logout', 'acr', 'role', 'acs', 'tag', 'ad', 'provider', 'context', 'container', 'component', 'feedback', 'login', 'configure')
```

Following CLI docs here: https://docs.microsoft.com/en-us/cli/azure/group#create

@allenclark

**Comment by derekbekoe** [comment]
What version is installed? `az --version`

**Comment by derekbekoe** [comment]
Does it match https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?

**Comment by spboyer** [comment]
0.1.0b9 - and will not upgrade even after following - https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#troubleshooting

Is there a "remove all / previous" or "clean"

**Comment by derekbekoe** [comment]
@spboyer 
How did you attempt to upgrade?
What error did you see?

**Comment by spboyer** [comment]
running the instal script, no errors.

**Comment by derekbekoe** [comment]
If the install script was successful then running `~/bin/az --version` should show the latest version if you chose all the defaults when running the script.
If `which az` does not point to the above location, `az` still points to an old install of the CLI,

**Comment by spboyer** [comment]
ok, managed to repair installation doing the following:

`rm -rf /python/site-packages/azure*` (not sure this was necessary)
`npm uninstall -g azure` (removing node cli, no longer needed this)

ran `sudo pip install --upgrade --no-deps --force-reinstall azure-cli`
then `sudo pip install azure-cli`

**Comment by spboyer** [comment]
```console
 az --version
azure-cli (2.0.0)

acs (2.0.0)
appservice (0.1.1b5)
batch (0.1.1b4)
cloud (2.0.0)
component (2.0.0)
configure (2.0.0)
container (0.1.1b4)
core (2.0.0)
documentdb (0.1.1b2)
feedback (2.0.0)
iot (0.1.1b3)
keyvault (0.1.1b5)
network (2.0.0)
nspkg (2.0.0)
profile (2.0.0)
redis (0.1.1b3)
resource (2.0.0)
role (2.0.0)
sql (0.1.1b5)
storage (2.0.1)
vm (2.0.0)

Python (Darwin) 2.7.12 (default, Jun 29 2016, 14:05:02)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```
