### ISSUE TITLE
az sig gallery-application version create unable to handle sas uris

### ISSUE THREAD

**Issue by aravindyeduvaka** [Azure/azure-cli#24313]
**Related command**

az sig gallery-application version create

**Describe the bug**

az sig gallery-application version create fails with the following error when I try to provide a SAS URI. However, the same works when using Azure portal to create a new version.

ERROR: (InvalidParameter) Source uri: '"https://.blob.core.windows.net//<blob.zip>?sp=r&sv=2021-06-08&sr=b&sig=***************************************"' must be an absolute uri.
Code: InvalidParameter
Message: Source uri: '"https://.blob.core.windows.net//<blob.zip>?sp=r&sv=2021-06-08&sr=b&sig=***************************************" must be an absolute uri.
Target: galleryApplicationVersion.properties.publishingProfile.source.mediaLink
**To Reproduce**

Pass in a SAS URI to the --package-file-link argument when creating with cli.

**Expected behavior**

Expected behavior is that this should work with SAS URI since that's the behavior in the Portal. (easy to verify when you create from the portal and use the browse option for "Source application package")

**Environment summary**

cli version 2.41.0a

**Additional context**

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
> Code: InvalidParameter
Message: Source uri: '"https://.blob.core.windows.net//<blob.zip>?sp=r&sv=2021-06-08&sr=b&sig=" must be an absolute uri.
Target: galleryApplicationVersion.properties.publishingProfile.source.mediaLink

This error message is returned by the REST service [gallery-application-versions/create-or-update](https://learn.microsoft.com/en-us/rest/api/compute/gallery-application-versions/create-or-update?tabs=HTTP#userartifactsource). The REST service needs to support the `mediaLink` parameter as SAS URI. So I transfer this issue to service team.

**Comment by jaylabell** [comment]
@sandeepraichura Can you please look into this sig issue?

**Comment by jaylabell** [comment]
@sandeepraichura Can you please provide an update on this sig issue?

**Comment by sandeepraichura** [comment]
@nikhilpatel909 - This seems to be an issue with VM Apps, can you please take a look

**Comment by nikhilpatel909** [comment]
@aravindyeduvaka it looks to be an issue on the customer side. The uri is malformed.

 There's an initial . in .blob.core.windows.net      Please recreate uri and try again

**Comment by jaylabell** [comment]
Closing this issue. If any new issues arise, please re-open
