### ISSUE TITLE
Not able to connect to cloud shell

### ISSUE THREAD

**Issue by Alimomin23** [Azure/azure-cli#24354]
## Describe the bug

**Command Name**
`az aks`

**Errors:**
```
the following arguments are required: _subcommand

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks`

## Environment Summary
```
Linux-5.4.0-1094-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.13
Installer: RPM

azure-cli 2.41.0

Extensions:
ai-examples 0.2.5
ml 2.10.0
ssh 1.1.2

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@Alimomin23 You need to pass a subcommand to `az aks`.  Please refer to [as aks documentation](https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest) for details.

**Comment by Alimomin23** [comment]
The issue has been resolved. Thank you for the resolution.
