### ISSUE TITLE
az network not working with default resource-group

### ISSUE THREAD

**Issue by gallium-arsenide** [Azure/azure-cli#24368]
## Describe the bug
It seems subcommands from `az network` can't read default resource group. Commands worked fine with version 2.38. With `az config get defaults` I can see default group was set correctly. Also, other commands are using default resource group without problem.

**Command Name**
`az network vnet show`

**Errors:**
```
InvalidArgumentValue: Missing required field: --resource-group

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az config set defaults.group={}`
- `az network vnet show --name {}`

## Expected Behavior
command should use default resource-group and show specific vnet

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.41.0

Extensions:
authV2 0.1.1
cosmosdb-preview 0.20.0
monitor-control-service 0.3.0

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
It's a breaking change involved in Azure CLI 2.41.0, which related to `[BREAKING CHANGE] az network vnet: Deprecate parameter --defer` (see details in [Release Notes](https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli)).

Please use the entire command instead.

**Comment by gallium-arsenide** [comment]
Please do not close it. It has nothing to do with `--defer` parameter.
Release notes doesn't tell `--resource-group` became required. If it is, then documentation is outdated.

[https://learn.microsoft.com/en-us/cli/azure/network/vnet?view=azure-cli-latest#az-network-vnet-show](url)
> **Optional Parameters**
> --resource-group -g
> Name of resource group. You can configure the default group using `az configure --defaults group=<name>`.

```
$ az network vnet subnet show --help
...
Resource Id Arguments
    --resource-group -g : Name of resource group. You can configure the default group using `az
                          configure --defaults group=<name>`.
```

Same is for `az network public-ip show` and `az network public-ip show`. Resource group is optional according to documentation but seems to be required

**Comment by necusjz** [comment]
@gallium-arsenide Sorry, I didn't catch your point well before and I'll re-open it then.

**Comment by necusjz** [comment]
It'll be fixed by https://github.com/Azure/azure-cli/pull/24411 with Azure CLI 2.42.0 in 11/01.
