### ISSUE TITLE
Cannot derive public ips in different resource group from public ip prefix

### ISSUE THREAD

**Issue by brianlehr** [Azure/azure-cli#24377]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az network public-ip create

**Describe the bug**
Cannot derive public ips in different resource group from public ip prefix

**To Reproduce**

Sample command from ICM shown below:

az network public-ip create --name myTestPIP --resource-group dvts-ondmd-ha5-we-rg --allocation-method Static --location westeurope  --public-ip-prefix "/subscriptions/b65b0225-ce9b-4a79-9dd9-c00071d40d64/resourcegroups/dvts-ondmd-config-rg/providers/Microsoft.Network/publicipprefixes/myTestIPPrefix" --sku Standard --query publicIp  --zone 1 2 3  --output json

(ResourceNotFound) The Resource 'Microsoft.Network/publicIPPrefixes/myTestIPPrefix' under resource group 'dvts-ondmd-ha5-we-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.Network/publicIPPrefixes/myTestIPPrefix' under resource group 'dvts-ondmd-ha5-we-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

**Expected behavior**
Public IP "myTestPIP" should have been created in RG dvts-ondmd-ha5-we-rg

**Environment summary**
Same in any CLI environment 

**Additional context**
See [https://portal.microsofticm.com/imp/v3/incidents/details/344043782/home](https://portal.microsofticm.com/imp/v3/incidents/details/344043782/home) for more details.

**Comment by yonzhan** [comment]
@necusjz for awareness
