### ISSUE TITLE
az network bastion rdp not working with Azure AD enabled VM

### ISSUE THREAD

**Issue by nosalan** [Azure/azure-cli#24375]
**Related command**
az network bastion rdp --name BASTION_NAME --resource-group RG_NAME  --target-resource-id VM_ID

**Describe the bug**
There is a VM deployed with the AAD Extension.
There is a bastion deployed with Kerberos enabled.
Both Vnet and Bastion are in the same Vnet.
Both the VM and my computer are Windows 10 connected to the same Azure AD.
The VM is assigned the Virtual Machine Administrator Login Role to the security group in which I am.
When trying to connect, using PIN or Fingerprint ro simply domain login/password this appears:
![image](https://user-images.githubusercontent.com/2273250/197579445-4d9def53-c13a-4d34-b281-8e64e8f81875.png)

_The remote computer that you are trying to connect to requires Network Level Authentication (NLA), but your Windows domain controller cannot be contacted to perform NLA. You can try connecting to the remote computer using your username and password instead._

**To Reproduce**
Execute `az login`
Execute the `az bastion rdp..` command mentioned above.

**Expected behavior**
The prompt for authentication appears like PIN or Fingerprint and is sufficient to log in. Instead the problematic error appears. It was working like 2 weeks ago with older version of az cli.

**Environment summary**
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.41.0

Extensions:
aks-preview 0.5.111
storage-preview 0.8.3

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1

**Additional context**
<!--- Add any other context about the problem here. --->

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@nosalan Apologies for the late reply. Thanks for reaching out to us and reporting this issue. The cause for this issue and the troubleshooting steps to be followed is explained in [this ](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/cannot-connect-rdp-azure-vm#:~:text=The%20remote%20computer,Properties%20dialog%20box.)article. Please follow this and let us know if you face any issues.

**Comment by navba-MSFT** [comment]
@nosalan I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@nosalan The action is currently pending on you to try the suggestion in above comment. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
