### ISSUE TITLE
security iot-solution update returns bad request

### ISSUE THREAD

**Issue by vilit1** [Azure/azure-cli#24382]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az security iot-solution update`

**Describe the bug**
The update command returns a `Operation returned an invalid status 'Bad Request'`

with debug, we further see two serialization issues:
```
msrest.serialization: displayName is not a known attribute of class <class 'azure.mgmt.security.models._models_py3.UpdateIotSecuritySolutionData'> and will be ignored
msrest.serialization: iotHubs is not a known attribute of class <class 'azure.mgmt.security.models._models_py3.UpdateIotSecuritySolutionData'> and will be ignored
```

**To Reproduce**
1. create an iot-solution with `az security iot-solution create`
2. update that iot-solution with `az security iot-solution update`

**Expected behavior**
The update to work (or at least not give a bad request)

**Environment summary**
```
az --version
azure-cli                         2.41.0

core                              2.41.0
telemetry                          1.0.8

Extensions:
azure-iot                         0.17.2
ai-examples                        0.2.5
ml                                2.10.0
ssh                                1.1.2

Dependencies:
msal                            1.20.0b1
azure-mgmt-resource             21.1.0b1

Python location '/usr/bin/python3.9'
Extensions directory '/home/victoria/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.13 (main, Jul 31 2022, 23:00:51) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

@chlahav Could you please look into this and provide an update ?

**Comment by vakuras** [comment]
Hi @navba-MSFT @vilit1,

The issue was fixed, and will be available in the second week of November.

**Comment by navba-MSFT** [comment]
Thanks @vakuras for your quick reply.

@vilit1 Hope this answers. Please feel free to reopen this thread if you need further information on this. We would be happy to help.
