### ISSUE TITLE
Yaml reference docs for Azure ML registry link is broken

### ISSUE THREAD

**Issue by thongonary** [Azure/azure-cli#24383]
In the documentation for [Azure ML Registry](https://learn.microsoft.com/en-us/cli/azure/ml/registry?view=azure-cli-latest#az-ml-registry-create-optional-parameters), the link to the YAML reference doc is broken:
>Local path to the YAML file containing the Azure ML registry specification. The YAML reference docs for registry can be found at: https://aka.ms/ml-cli-v2-registry-yaml-reference.

cc: @ApGa

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12aabebd-7419-909a-8c65-5168e838ba02
* Version Independent ID: a69b580c-3664-ad0a-e731-0b31ed88420b
* Content: [az ml registry](https://learn.microsoft.com/en-us/cli/azure/ml/registry?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ml/registry.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ml/registry.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@thongonary Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@thongonary You can get the YAML CLI v2 workspace schema from [here](https://learn.microsoft.com/en-us/azure/machine-learning/reference-yaml-workspace). In the meantime, we are also working on getting the documentation updated.

**Comment by navba-MSFT** [comment]
@thongonary The above short link is now fixed and doesn't redirect to invalid location now. If you need any further help in future feel free to reopen this thread. We would be happy to help.

**Comment by amasciotta** [comment]
> @thongonary You can get the YAML CLI v2 workspace schema from [here](https://learn.microsoft.com/en-us/azure/machine-learning/reference-yaml-workspace). In the meantime, we are also working on getting the documentation updated.

The link provided contains the YAML schema for the _workspace_, while OP was asking for the YAML schema for the [_registry_](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-manage-registries). Where is this schema located?
