### ISSUE TITLE
Bastion Error

### ISSUE THREAD

**Issue by atul55** [Azure/azure-cli#24398]
## Describe the bug

**Command Name**
`az network bastion rdp`

**Errors:**
```
the following arguments are required: --target-resource-id

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network bastion rdp --name {} --resource-group {}`

## Environment Summary
```
Linux-3.10.0-1127.el7.x86_64-x86_64-with, Alpine Linux v3.16
Python 3.10.7
Installer: DOCKER

azure-cli 2.41.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@atul55 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please let me know if you have tried running the below command? Awaiting your reply. 

> **az network bastion rdp --name MyBastionHost --resource-group MyResourceGroup --target-resource-id vmResourceId**

`--target-resource-id:` This is a required parameter and it is the ResourceId of the target Virtual Machine. Refer [this](https://learn.microsoft.com/en-us/cli/azure/network/bastion?view=azure-cli-latest#az-network-bastion-rdp).

**Comment by navba-MSFT** [comment]
@atul55 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@atul55 The action is currently pending on you to check and try the above suggestion. Please feel free to reopen this thread. We would be happy to help.
