### ISSUE TITLE
Using --sas-token to access storage causing parsing error in powershell core

### ISSUE THREAD

**Issue by aDisplayName** [Azure/azure-cli#24399]
## Describe the bug
In Powershell Core 7.x, when accessing the blob storage using `--sas-token` argument with:
* sas-token directly;
* sas-token enclosed with double quote
* sas-token enclosed with single quotes, 

the command always fails with following error:
```
Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:0b1666a5-601e-0063-3daf-e88fb4000000
Time:2022-10-25T20:19:29.6466268Z
ErrorCode:NoAuthenticationInformation
'ss' is not recognized as an internal or external command,
operable program or batch file.
'srt' is not recognized as an internal or external command,
operable program or batch file.
'sp' is not recognized as an internal or external command,
operable program or batch file.
'se' is not recognized as an internal or external command,
operable program or batch file.
'st' is not recognized as an internal or external command,
operable program or batch file.
'spr' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.
```

Based on https://stackoverflow.com/questions/71225811/azure-cli-and-sas-token-issue-in-powershell, we managed to get it work by enclose the sas-token with both single and double quotes:
`'"?sv=xxxxxxxxx....xxx%3D"'`

**Command Name**
` az storage blob list --account-name myaccount --container-name mycontainer --sas-token "?sv=2022-06-08&ss=b&srt=co&sp=rltf&se=2022-11-09T06:33:06Z&st=2022-11-08T22:33:06Z&spr=https&sig=z%2B.............%3D"`

**Errors:**
```
Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:0b1666a5-601e-0063-3daf-e88fb4000000
Time:2022-10-25T20:19:29.6466268Z
ErrorCode:NoAuthenticationInformation

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Acquire an SAS token with value of `?sv=2022-06-08&ss=b&srt=co&sp=rltf&se=2022-11-09T06:33:06Z&st=2022-11-08T22:33:06Z&spr=https&sig=z%2B.............%3D`
- Tried: `az storage blob list --account-name myaccount --container-name mycontainer --sas-token "?sv=2022-06-08&ss=b&srt=co&sp=rltf&se=2022-11-09T06:33:06Z&st=2022-11-08T22:33:06Z&spr=https&sig=z%2B.............%3D"`
- Tried: `az storage blob list --account-name myaccount --container-name mycontainer --sas-token '?sv=2022-06-08&ss=b&srt=co&sp=rltf&se=2022-11-09T06:33:06Z&st=2022-11-08T22:33:06Z&spr=https&sig=z%2B.............%3D'`

## Expected Behavior
command succeeded
## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.4
Installer: MSI
PowerShell Core 7.2.6

azure-cli 2.36.0 *
```

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by bebound** [comment]
You need to surround is with both single and double quotes:  `'"SAS"'`

**Comment by aDisplayName** [comment]
> You need to surround is with both single and double quotes: `'"SAS"'`

Is it mentioned somewhere in the Microsoft documents?

**Comment by bebound** [comment]
In CLI doc
https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md#ampersand--is-interpreted-by-command-prompt
