### ISSUE TITLE
`az network application-gateway auth-cert list` shows incorrect output

### ISSUE THREAD

**Issue by subhasishdc** [Azure/azure-cli#24402]
`az network application-gateway auth-cert list -g rg --gateway-name aag01` should only show the authorization certificates which are currently deployed in the backend HTTP settings. However, we see two things happening here:

- It shows certificates which have already been deleted ( the portal does not show them but the az cli output does)
- It displays certificates from an application gateway in another subscription/resource group

There seems to be some bug in the command which needs to be checked.

**Comment by yonzhan** [comment]
@necusjz for awareness
