### ISSUE TITLE
Azure Cli report Decryption failed

### ISSUE THREAD

**Issue by MarvinWenS** [Azure/azure-cli#24420]
Azure Cli report me a error when I login in and exec a cmd:

Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by bebound** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/20231
