### ISSUE TITLE
`functionapp config appsettings set` with roundtrip datetime values does not set specified value

### ISSUE THREAD

**Issue by matt-tfl** [Azure/azure-cli#24429]
**Related command**
```
az functionapp config appsettings set --name my-function-app-func --resource-group my-resource-group-rg --settings 'MySettingKey=2022-10-24T14:35:50.1806413Z'
```

**Describe the bug**
When running the command above I want the value specified to be set to the MySettingKey setting. Instead the setting is updated thus:
```
  {
    "name": "MySettingKey",
    "slotSetting": false,
    "value": "10/24/2022 14:35:50"
  }
```
This behaviour is seen on a dev-machine running with British English local-settings, however the date is being saved in US English format.
I need to set the raw value as my code is expecting the invariant format specified on the command.

**Expected behavior**
```
  {
    "name": "MySettingKey",
    "slotSetting": false,
    "value": "2022-10-24T14:35:50.1806413Z"
  }
```

**Environment summary**
Windows 10 Pro, 21H2.
Powershell 5.1

```
az --version
azure-cli                         2.41.0

core                              2.41.0
telemetry                          1.0.8

Extensions:
azure-devops                      0.23.0

Dependencies:
msal                            1.20.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\USERNAME\.azure\cliextensions'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
```

**Additional context**
Azure support agent (case 2210240050001804) has confirmed that this doesn't occur with the Rest API.

If I place a space around the equals sign then the value is set 'raw' but it's not possible to update a value that has already been set (i.e. only the first set runs for each key).

**Comment by yonzhan** [comment]
route to CXP team

**Comment by matt-tfl** [comment]
After some more testing it seems that the comment from Azure Support was incorrect, and the problem occurs when using the REST API directly. Closing this case
