### ISSUE TITLE
Add support for `marketplacePartnerId` to `az monitor diagnostic-settings create`

### ISSUE THREAD

**Issue by kf6kjg** [Azure/azure-cli#24438]
**Related command**
`az monitor diagnostic-settings create`

The core problem is that while the `list` and `show `subcommands will read out the `marketplacePartnerId`, the create command has no ability to set it that I can find.

What I'd like is the ability to create/update diagnostics settings that point the log output to a Partner Solution, e.g. DataDog.

I've explored doing this via the `az rest` command, but my lack of knowledge has blocked that workaround for now.

**Comment by yonzhan** [comment]
@kairu-ms for awareness

**Comment by AllyW** [comment]
@kf6kjg  'marketplacePartnerId' will be added in next release.
