### ISSUE TITLE
`az policy assignment create` throws scope error no matter what I pass to --scope

### ISSUE THREAD

**Issue by erwelch** [Azure/azure-cli#24440]
## Describe the bug

**Command Name**
`az policy assignment create`

**Errors:**
```
(InvalidPolicyUri) The policy request scope '/providers/Microsoft.Authorization/policyDefinitions/"/subscriptions/<redacted>' should be '/', '/subscriptions/id' or '/providers/Microsoft.Management/managementGroups/id'.
Code: InvalidPolicyUri
Message: The policy request scope '/providers/Microsoft.Authorization/policyDefinitions/"/subscriptions/<redacted>' should be '/', '/subscriptions/id' or '/providers/Microsoft.Management/managementGroups/id'.

```

## To Reproduce:
I have been trying to assign a policy definition with a managed user identity. The scope is subscription level. I keep getting the above error with the following attempts: 

`az policy assignment create --name add-service-tags-to-resources  --policy $policyId --mi-user-assigned $identityId --location westus2 --scope /subscriptions/<redacted>`

Or without the scope flag at all. Same error. 

## Expected Behavior

Creates a policy assignment at the subscription scope. 
Or gives a better error message if this not referring to the scope I'm trying to assign to the az command. 

## Environment Summary
```
macOS-12.5.1-x86_64-i386-64bit, Darwin 21.6.0
Python 3.10.4
Installer: HOMEBREW

azure-cli 2.37.0 *
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by RakeshMohanMSFT** [comment]
@erwelch Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@erwelch Can you please try to upgrade to latest version of az cli [2.41.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli) and retry?

`az policy assignment create -n issue24440 --policy "/subscriptions/b83c1ed3-c5b6-44fb-b5ba-2b83a074c23f/providers/Microsoft.Authorization/policyDefinitions/f6b97bd5-175f-4aec-806a-ecf36f8136c9" -p "{ \"allowedLocations\": { \"value\": [ \"australiaeast\", \"eastus\", \"japaneast\" ] } }" --location eastus2 --scope "/subscriptions/b83c1ed3-c5b6-44fb-b5ba-2b83a074c23f/resourceGroups/Issue18880"`

![image](https://user-images.githubusercontent.com/49954584/198544637-b653c718-51c7-4965-b405-a9f8574010ee.png)
