### ISSUE TITLE
'az network public-ip delete' fails if `az config param-persist` is enabled

### ISSUE THREAD

**Issue by msterin** [Azure/azure-cli#24443]
## Describe the bug

**Command Name**

az network public-ip delete consistently fails when persist-params is enabled

Workaround: turn off persist-params and it succeeds 

**Errors:**
```
InvalidArgumentValue: Missing required field: --resource-group

```

## To Reproduce:

`az config param-persist on` , then create an RG with location, then create VM/Ip - all works. 

After which `az network public-ip delete -g <group name>` fails with stack trace below. 
if group name is omitted, it still fails: 

```
az network public-ip delete  -n rportPublicIP
InvalidArgumentValue: Missing required field: --resource-group
```

Turning off persist-param recovers the correct functionality (public-ip deleted)

## Environment Summary
```
Linux-5.19.16-200.fc36.x86_64-x86_64-with-glibc2.35, Fedora Linux 36 (Workstation Edition)
Python 3.10.7
Installer: PIP

azure-cli 2.41.0

Extensions:
aks-preview 0.5.111
resource-graph 2.1.0
interactive 0.4.5
azure-devops 0.25.0
account 0.2.5
azure-iot 0.17.3

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by necusjz** [comment]
It'll be fixed by https://github.com/Azure/azure-cli/pull/24411
