### ISSUE TITLE
'az ad' command don't response or return any output

### ISSUE THREAD

**Issue by khlph** [Azure/azure-cli#24446]
## Describe the bug

**Command Name**
`az ad app list`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login` with guest account - owner to the subscription
- `az ad app list`

## Environment Summary
```
macOS-12.6-arm64-arm-64bit, Darwin 21.6.0
Python 3.10.6
Installer: HOMEBREW

azure-cli 2.39.0 *
```

**Comment by yonzhan** [comment]
Please provide detailed error log.

**Comment by khlph** [comment]
Had retried the command with another env and eventually got the response 
I'll reinstall the az cli again at the prev env.

`az ad app list`

## Environment Summary
```
Linux-5.4.0-66-generic-x86_64-with-glibc2.31, Ubuntu 20.04.2 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.41.0

Extensions:
datafactory 0.6.0

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context
