### ISSUE TITLE
"az network vnet update" disables DDOS protection but fails to remove the DDOS protection plan from the vNET

### ISSUE THREAD

**Issue by achechen** [Azure/azure-cli#24462]
## Describe the bug
When I run `az network vnet update -g <resource group> -n <vnet> --ddos-protection false` command, `enableDdosProtection` property of the vnet is set to `false` sucessfully. But, the `ddosProtectionPlan` property is not cleared out and still contains a reference to the DDOS protection plan, which makes it impossible to remove the DDOS protection plan.

**Command Name**
`az network vnet update`

**Errors:**
```
not available
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a vnet and a DDOS plan
- Enable DDOS protection for the vnet and link it to the DDOS plan
- Run `az network vnet update -g <resource group> -n <vnet> --ddos-protection false`
- Run `az network vnet show -g <resource group> -n <vnet>` to observe that `enableDdosProtection` is set to false but `ddosProtectionPlan` still contains a reference to the DDOS plan
- Run `az network ddos-protection delete --resource-group <resource group> --name <ddos plan name>` and observe `InUseDdosProtectionPlanCannotBeDeleted` error.

## Expected Behavior
I expect the ddos plan reference to be removed from the vnet properties when I set ddos-protection as false
Alternatively, a separate method to clear the `ddosProtectionPlan` parameter value should exist.
## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.34.1 *

Extensions:
account 0.2.1

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
As limited bandwidth, could you please append `--ddos-protection-plan ""` as a workaround?

**Comment by necusjz** [comment]
Are you using PowerShell? `""` should be `'""'` then.
