### ISSUE TITLE
az account list-locations should include geocode

### ISSUE THREAD

**Issue by MmAtBosch** [Azure/azure-cli#24478]
**Related command**
az account list-locations

**Is your feature request related to a problem? Please describe.**
We use the azure geo code for our azure resource names. Sadly the only list of Microsofts geocode mapping is [[here](https://learn.microsoft.com/en-us/azure/backup/scripts/geo-code-list)](url).

But this is not useful in automation processes.

**Describe the solution you'd like**
It would be great if az account list-locations would include the geocode for each location.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
This is a feature request for the underlying REST API, similar to https://github.com/Azure/azure-cli/issues/10421.

@Paul-at-Seequent, for REST API and service-related feature request, please feel free to submit a feedback at https://feedback.azure.com/. The corresponding service team will review the feedback and evaluate whether it should be implemented. Thanks for your understanding.
