### ISSUE TITLE
az webapp deployment github-actions add command creates workflow file that doesn't work

### ISSUE THREAD

**Issue by vmagelo** [Azure/azure-cli#24474]
I'm using this command:

az webapp deployment github-actions add \
  --repo "\<github-user>/\<github-repo>" \
  --resource-group \<resource-group-name> \
  --branch \<branch-name> \
  --name \<app-service-name> \
  --login-with-github

What I noticed is this goes into the workflow file:

    - name: 'Deploy to Azure Web App'
    - uses: azure/webapps-deploy@v2
      with: 
        app-name: 'vmagelotestcicd3'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b63f3310b68c4535a98aa7614d491019 }}

Note the "dash" before "uses". The workflow fails and then I remove that dash and it works. Am I doing something wrong?

Creating workflow file through portal doesn't add dash before "uses".

Workflow error:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/51368918/198674012-78efce34-3090-4aaf-abcb-a46ce2f7864a.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b397bce-4a07-9d15-d36c-ebed2f8bcc4e
* Version Independent ID: f31c415e-bb0f-14f3-b19f-e3496d816101
* Content: [az webapp deployment github-actions](https://review.learn.microsoft.com/en-us/cli/azure/webapp/deployment/github-actions?branch=main&view=azure-cli-latest#az-webapp-deployment-github-actions-add)
* Content Source: [latest/docs-ref-autogen/webapp/deployment/github-actions.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/deployment/github-actions.yml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by vmagelo** [comment]
Not sure if it's related, but will add that just using webapp upfor the vscode flask sample apa

`az webapp up -n somename` 

gives me a workflow file using Python:3.10 and that doesn't seem to work, even after adjusting the dash issue above. The workflow fails. It might be that the other actions used are the problem.

I had to fix runtime:

`az webapp up -n somename --runtime Python:3.9`

and then it was okay.

**Comment by PramodValavala-MSFT** [comment]
@vmagelo Thanks for catching that! Looks like the templates are just incorrect. We will work up a PR to fix them.

For the second issue, it would be best to create a new issue with the fill log of what the workflow fails with.
