### ISSUE TITLE
az storage account create --enable-nfs-v3 true doesn't work and raises error

### ISSUE THREAD

**Issue by adehaan-rlcm** [Azure/azure-cli#24479]
## Describe the bug

**Command Name**
`az storage account create`

**Errors:**
```
(InvalidRequestPropertyValue) The value 'True' is not allowed for property isNfsv3Enabled.
Code: InvalidRequestPropertyValue
Message: The value 'True' is not allowed for property isNfsv3Enabled.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage account create --resource-group <rg name> --name <sa name> --kind StorageV2 --enable-nfs-v3 true`

## Expected Behavior
create a nfsv3 enabled storage account
## Environment Summary
```
macOS-12.6-x86_64-i386-64bit, Darwin 21.6.0
Python 3.10.8
Installer: HOMEBREW

azure-cli 2.41.0
az version
{
  "azure-cli": "2.41.0",
  "azure-cli-core": "2.41.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
```

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by adehaan-rlcm** [comment]
anything? @evelyn-ys ?

**Comment by evelyn-ys** [comment]
You can only enable nfs v3 in ADLS Gen2 storage account. So you need to specify `--hns true` together with `--enable-nfs-v3`.

This is not client issue, this is restricted by service. See storage doc: https://learn.microsoft.com/en-us/azure/storage/blobs/network-file-system-protocol-support-how-to#step-3-create-and-configure-a-storage-account

**Comment by navba-MSFT** [comment]
@adehaan-rlcm Could you please let us know if you had a chance to follow the[ above suggestion](https://github.com/Azure/azure-cli/issues/24479#issuecomment-1306544356) ? Awaiting your reply.

**Comment by adehaan-rlcm** [comment]
/unresolve
apologies for not responding earlier.
there is more to it than just using the --enable-nfs-v3 and --enable-hierarchical-namespace qualifiers. It is also a combination of --access-tier and --kind together with the --vnet-name and --subnet qualifiers. 
Apart from addressing this in the documentation, the error messages from the az cli command could be more descriptive also.

I have to mention that with the addition of the afore mentioned qualifiers I was able to create the nfs-v3 storage container endpoint.

If you think this is not something that needs to be addressed, than I will close it.

**Comment by aronchick** [comment]
/unresolve

the documentation is still out of date, and the SDK is similarly so
