### ISSUE TITLE
Single quotes do not work - Examples need to be updated

### ISSUE THREAD

**Issue by jmsteinbrunner** [Azure/azure-cli#24489]
When trying to add a vnet, the documentation shows to use single quotes when referencing a vnet by Resource ID.

When I include the single quotes, it does not work.
`az webapp vnet-integration add -g resource-group-name -n resource-name  --subnet subnet-name  --vnet '/subscriptions/.../vnet-name'
`
When I exclude the quotes, it works 
`az webapp vnet-integration add -g resource-group-name -n resource-name  --subnet subnet-name  --vnet /subscriptions/.../vnet-name
`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cf5a035-926f-1cef-8335-963b497cbed8
* Version Independent ID: 296a49f5-bc7a-d56a-6fe2-914d276b2a9e
* Content: [az webapp vnet-integration](https://learn.microsoft.com/en-us/cli/azure/webapp/vnet-integration?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/vnet-integration.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/vnet-integration.yml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@jmsteinbrunner Thank you for reaching out, we are looking into it.
