### ISSUE TITLE
Update SKR Policy Location

### ISSUE THREAD

**Issue by thaiolivia** [Azure/azure-cli#24488]
### Resource Provider

CVM

### Description of Feature or Work Requested

We have decided to shift the key release policy to GitHub which you can find here: https://raw.githubusercontent.com/Azure/confidential-computing-cvm/main/cvm_deployment/key/skr-policy.json

We would like for skr-policy reference to point to this GitHub as well for CLI to have a local backup copy.

### Minimum API Version Required

N/A

### Swagger PR link / SDK link

N/A

### Target Date

2022-11

**Comment by yonzhan** [comment]
@evelyn-ys for awareness
