### ISSUE TITLE
I can't list my clusters

### ISSUE THREAD

**Issue by AliceMongodin** [Azure/azure-cli#24538]
## Describe the bug

**Command Name**
`az aks list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
API version 2022-07-01 does not have operation group 'managed_clusters'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 112, in handler
    client = self.client_factory(self.cli_ctx, command_args) if self.client_factory else None
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acs/_client_factory.py", line 27, in cf_managed_clusters
    return get_container_service_client(cli_ctx).managed_clusters
  File "/usr/lib/python3/dist-packages/azure/mgmt/containerservice/_container_service_client.py", line 492, in managed_clusters
    raise ValueError("API version {} does not have operation group 'managed_clusters'".format(api_version))
ValueError: API version 2022-07-01 does not have operation group 'managed_clusters'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks list`

## Environment Summary
```
Linux-5.19.0-kali2-amd64-x86_64-with-glibc2.35, Kali GNU/Linux Rolling
Python 3.10.8
Installer: DEB

azure-cli 2.41.0 *

Extensions:
azure-devops 0.24.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.0.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@AliceMongodin Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@AliceMongodin Judging by the below:

```
Linux-5.19.0-kali2-amd64-x86_64-with-glibc2.35, Kali GNU/Linux Rolling
Python 3.10.8
Installer: DEB
```

This is not the official Azure CLI published by Microsoft. Community packagers release unofficial Azure CLI deb packages on multiple Linux repositories. Please see https://github.com/Azure/azure-cli/issues/19640 for more information.

For now, please follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt to install Microsoft official Azure CLI. That should fix this issue.

**Comment by navba-MSFT** [comment]
@AliceMongodin I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@AliceMongodin The action is currently pending on you to try the [Microsoft official AzCLI ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)and check if you face the same issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
