### ISSUE TITLE
Internal Server Error while creating Postgres Flexible Server version 14

### ISSUE THREAD

**Issue by florfederico-sr** [Azure/azure-cli#24537]
![internal_error](https://user-images.githubusercontent.com/99897724/199535276-d28fbaa3-f588-4757-8ecd-912fab56fafb.png)
I'm getting an InternalServerError trying to create a new Postgres flexible server.

I've tried it several time, changing the type of server and size. But I'm getting the same error every time.
This example was with: Standard_B1ms (size: 32)
But I've tried with Standard_D2ds_v4 (size: 256) too.

[
  {
    "id": "/subscriptions/e86a5f2d-fc45-4610-bb85-4a35e1c6360c/resourceGroups/Development/providers/Microsoft.Resources/deployments/PostgreSqlFlexibleServer_67d613c368f24095aabdaac6ca85b9a6/operations/8942618C09E48C27",
    "operationId": "8942618C09E48C27",
    "properties": {
      "provisioningOperation": "Create",
      "provisioningState": "Failed",
      "timestamp": "2022-11-02T15:02:35.6815811Z",
      "duration": "PT10M12.1304977S",
      "trackingId": "aba6ed45-a8e4-4722-84e9-9c397d9751fe",
      "statusCode": "Conflict",
      "statusMessage": {
        "status": "Failed",
        "error": {
          "code": "InternalServerError",
          "message": "An unexpected error occured while processing the request. Tracking ID: '75b89c5c-186a-448e-9e5f-82c02fe639e2'"
        }
      },
      "targetResource": {
        "id": "/subscriptions/e86a5f2d-fc45-4610-bb85-4a35e1c6360c/resourceGroups/Development/providers/Microsoft.DBforPostgreSQL/flexibleServers/sr-musicbrainz-postgres-v14",
        "resourceType": "Microsoft.DBforPostgreSQL/flexibleServers",
        "resourceName": "sr-musicbrainz-postgres-v14"
      }
    }
  }
]

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@florfederico-sr Thank you for reaching out, we are looking into it. It looks like something from the service side and not from the client (CLI). But let me look further and will keep you posted.

**Comment by RakeshMohanMSFT** [comment]
@florfederico-sr Can you please retry this operation and let us know if you are still facing this issue?

**Comment by florfederico-sr** [comment]
> @florfederico-sr Can you please retry this operation and let us know if you are still facing this issue?

@RakeshMohanMSFT I was able to create it without any problem! Thank you! 👍

**Comment by Brijesh-BH** [comment]
can we update existing PG 13 to PG 14 using ARM templates?

**Comment by chandralakagwad** [comment]
@RakeshMohanMSFT , I am still facing the same error `error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '1b8eb450-dc7a-4bc7-8007-43d69d7ea22e'"`

I am using IaC tool Pulumi to provision the postgresql flexible server. 
Following configurations are set,
sku : General purpose Standard_D2s_v3
Storage : 128 GiB
High Availability is disabled
Customer managed key for security. 

Any help on this will be appreciated. 
Thank you.

**Comment by sebnyberg** [comment]
@chandralakagwad Did you find a solution? Struggling with exactly the same problem.
