### ISSUE TITLE
 New API version 2022-04-01-preview for Microsoft.Network trafficmanager

### ISSUE THREAD

**Issue by imsiddhartha** [Azure/azure-cli#24532]
### Related command

az network traffic-manager endpoint create

### Resource Provider

Microsoft.Network/trafficManagerProfiles

### Description of Feature or Work Requested

Added a new flag “Always Serve”, When it is enabled, ATM bypasses the health checks and always serves the endpoint. ATM asserts that endpoints that are “always served” are healthy. The customer will be configuring this flag for every endpoint that the ATM profile resolves to.  Details in the [doc here](https://microsoft-my.sharepoint.com/:w:/p/samimodak/EbHOz_mYXddMg9C9JnolFy4BOVnGrSoNEVgGS_QG1xBkOA?e=pvFrma )

### Minimum API Version Required

2022-04-01-preview

### Swagger PR link / SDK link

- Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/trafficmanager/resource-manager/Microsoft.Network/preview/2022-04-01-preview/trafficmanager.json#L1045
- Specs PR: https://github.com/Azure/azure-rest-api-specs/pull/21308
- SDK request release: https://github.com/Azure/sdk-release-request/projects/1382

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/trafficmanager/resource-manager/Microsoft.Network/preview/2022-04-01-preview/examples/Endpoint-PUT-External-WithAlwaysServe.json

### Target Date

2022-11-26

**Comment by yonzhan** [comment]
@necusjz for awareness
