### ISSUE TITLE
Simply the AZ login experience

### ISSUE THREAD

**Issue by nicolehaugen79** [Azure/azure-cli#2454]
The current experience for signing into Azure from the command line feels sluggish and requires multiple steps - here are some suggestions for simplifying this experience:

1.)  When you enter the command "az login" it takes several seconds without any indication that something is happening - at first, I wasn't sure it was working and I cancelled out of the command. To help with this, the command should provide some sort of output to the console to indicate that it's doing something.

2.) After entering the "az login" command, it eventually says "To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code XXXXX to authenticate".  After the user enters this code into the browser, then they can log-in with their azure creds. This part of the experience could be improved by either allowing the creds to be entered directly in the command line without having the user go to the browser. Or, at least the browser could be automatically launched and the code already entered for them so that they don't have to manually launch the browser and enter in the code.

**Comment by yugangw-msft** [comment]
> When you enter the command "az login" it takes several seconds without any indication that something is happening - at first

2 factors might be involved, performance latency on command loading (a known issue), and CLI was contacting AAD endpoint for a device code(usually is pretty fast). 

 > this part of the experience could be improved by either allowing the creds to be entered directly in the command line without having the user go to the browser

You can use `az login -u <user> -p <password>`, but it has a few limitations. For accounts with higher security requirements like 2FA enforced, you need to go through the default interactive flow

 > at least the browser could be automatically launched and the code already entered for them so that they don't have to manually launch the browser and enter in the code.

We have communicated this ask to AAD team. To do this, we need to know the control information in the client page, and establish the contract that AAD team will maintain 

JFYI, the login is only needed once every 3 months as long as you use the CLI at least once every 2 weeks.

**Comment by JasonRShaver** [comment]
Let's track the North Star for the login improvements (and do it holistically)
