### ISSUE TITLE
`az account clear` and `az logout` fails in Azure Government: ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by tom-navarra-nnl** [Azure/azure-cli#24553]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

`az account clear`
`az logout`

**Describe the bug**

After logging into AzureUSGovernment, a subsequent logout fails. This occurs in cli v2.42.0 and 2.41.0 but does not in 2.40.0

> ERROR: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/common/oauth2/authorize (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/az/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/az/lib/python3.10/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/az/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/az/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/az/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/az/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/az/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

**To Reproduce**

az cloud set --name AzureUSGovernment
az login --service-principal -u [spid] -p [sppassword] --tenant [sptenant]
az account set -s [subscription]
az account clear

**Expected behavior**

az account clear and az logout complete successfully.

**Environment summary**

- Install method: apt-get from Microsoft package source https://packages.microsoft.com/
- CLI Version
>azure-cli                         2.42.0
> core                              2.42.0
> telemetry                          1.0.8
> Dependencies:
> msal                              1.20.0
> azure-mgmt-resource             21.1.0b1

**Additional context**

The authentication endpoint in the error on logout appears to point to Azure commercial.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by bebound** [comment]
That's usually caused by network issue. 
But you said you can login but fail to logout, which is weird.
Can you check the output of `python3 -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"` in different version?

**Comment by jiasli** [comment]
The URL in the error message is 

```
/common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/common/oauth2/authorize
```

Searching `api-version=1.1` in MSAL's source code indicates the URL is generated by this line:

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/789342c4bc57f80314a83662af614f6f02a207d0/msal/application.py#L1117

```py
    def _get_instance_metadata(self):  # This exists so it can be mocked in unit test
        resp = self.http_client.get(
            "https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/common/oauth2/authorize",  # TBD: We may extend this to use self._instance_discovery endpoint
            headers={'Accept': 'application/json'})
```

`_get_instance_metadata` is called by [`_get_authority_aliases`](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/789342c4bc57f80314a83662af614f6f02a207d0/msal/application.py#L1122), which is called by [`get_accounts`](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/789342c4bc57f80314a83662af614f6f02a207d0/msal/application.py#L1053).

So I don't think this is related to Azure CLI's different versions, but how MSAL discovers authority's aliases.

As @bebound indicated, it is very possible that your network blocks `https://login.microsoftonline.com/`, but MSAL requires it to find aliases of `https://login.microsoftonline.us/`.

We saw similar issue before. The current solution is to make sure your network has access to `https://login.microsoftonline.com/`, until MSAL removes its dependency on it. @rayluo

**Comment by tom-navarra-nnl** [comment]
@jiasli Thank you. This does appear to be an endpoint access issue. With the MSAL requirements in place, logout works as expected.
