### ISSUE TITLE
az iot hub invoke-module-method also covers non-edge devices

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-cli#24555]
The article describes `az iot hub invoke-module-method` as a way to invoke direct methods on "Edge" modules, although it also covers  modules from regular (non-edge) devices

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9afeaa5c-1af2-8fcc-69b4-15ae81a0d342
* Version Independent ID: dea97474-170e-f678-f812-a1e4cdf56c76
* Content: [az iot hub](https://learn.microsoft.com/en-us/cli/azure/iot/hub?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/iot/hub.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/iot/hub.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by digimaun** [comment]
Resolved in `azure-iot` release `0.18.1` https://learn.microsoft.com/en-us/cli/azure/iot/hub?view=azure-cli-latest#az-iot-hub-invoke-module-method
