### ISSUE TITLE
pip install Azure cli  taking longer then 10min

### ISSUE THREAD

**Issue by MuhammadPathan** [Azure/azure-cli#24551]
Got the following requirements.txt which i am pip installing. azure-cli is taking forever, longer then 10 min just to install. how can i speed this up?

my requirements.txt file:

azureml-train-core==1.47.0
azureml-sdk==1.47.0
azure-storage-blob==12.13.1
matplotlib==3.6.1
numpy==1.23.4
pandas== 1.5.1
pathlib==1.0.1
python-dotenv==0.14.0
pytz==2020.4
azure-cli== 2.42.0

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by bebound** [comment]
I think there is nothing we can do about this.
It takes 1min 40s to install `azure-cli==2.42.0` on Cloud Shell.
Your bandwidth or disk speed might be the bottleneck.
