### ISSUE TITLE
Move Azure Bastion to Extension

### ISSUE THREAD

**Issue by aavalang** [Azure/azure-cli#24563]
### Related command

az network bastion --create
az network bastion --update
az network bastion --list
az network bastion --show
az network bastion --delete

### Resource Provider

Microsoft.network/bastionHosts

### Description of Feature or Work Requested

bastion az cli commands are part of cli repo, we want to move to our own extension

This will help us plan features and releases going forward.

### Minimum API Version Required

2022-05-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs-pr/pull/9564

### Target Date

2023-01-01

### Additional context

bastion az cli commands are part of cli repo, we want to move to our own extension rather than be a part of the cli repo.

**Comment by yonzhan** [comment]
route to service team since these Bastion related commands are owned by service

**Comment by kairu-ms** [comment]
> route to service team since these Bastion related commands are owned by service

This is a request from service team. They want us to help move the commands into extension.
