### ISSUE TITLE
az webapp list-runtimes with minor versions

### ISSUE THREAD

**Issue by YusukeTobo** [Azure/azure-cli#24569]
**Related command**
az webapp list-runtimes

**Is your feature request related to a problem? Please describe.**
`az webapp list-runtimes` shows available runtimes. It is really useful to view what runtimes Web Apps support, but Java related runtimes like Tomcat, JavaSE have some minor versions (like 9.0.62, 9.0.54, 9.0.52) and they are not listed in the command like below. 

```
az webapp list-runtimes
{
  "linux": [
    "DOTNETCORE:7.0",
    "DOTNETCORE:6.0",
    "DOTNETCORE:3.1",
    "NODE:18-lts",
    "NODE:16-lts",
    "NODE:14-lts",
    "PYTHON:3.10",
    "PYTHON:3.9",
    "PYTHON:3.8",
    "PYTHON:3.7",
    "PHP:8.1",
    "PHP:8.0",
    "PHP:7.4",
    "RUBY:2.7",
    "JAVA:17-java17",
    "JAVA:11-java11",
    "JAVA:8-jre8",
    "JBOSSEAP:7-java11",
    "JBOSSEAP:7-java8",
    "TOMCAT:10.0-java17",
    "TOMCAT:10.0-java11",
    "TOMCAT:10.0-jre8",
    "TOMCAT:9.0-java17",
    "TOMCAT:9.0-java11",
    "TOMCAT:9.0-jre8",
    "TOMCAT:8.5-java11",
    "TOMCAT:8.5-jre8",
    "GO:1.19",
    "GO:1.18"
  ],
...
}
```

**Describe the solution you'd like**
like https://management.azure.com/providers/Microsoft.Web/webAppStacks, it would be nice if the command could show available runtimes including minor versions.

**Describe alternatives you've considered**
```
az rest -u "https://management.azure.com/providers/Microsoft.Web/webAppStacks?api-version=2022-03-01"
```

**Comment by RakeshMohanMSFT** [comment]
The latest version of Az CLI 2.42.0 is actually using the same rest API (2022-03-01) and i do see that the response of the api (Json) also contains the result, but it is not displayed to users for some reason, need to check why.

**Comment by yonzhan** [comment]
route to CXP team
