### ISSUE TITLE
az network bastion rdp exception (unexpected error)

### ISSUE THREAD

**Issue by fabio-s-franco** [Azure/azure-cli#24560]
## Describe the bug
az cli throws an exception when trying to access bastion private subnet within azure, to enable RDP from local machine.

**Command Name**
`az network bastion rdp`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
libffi.so.7: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/custom.py", line 8396, in rdp_bastion_host
    from ._process_helper import launch_and_wait
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/network/_process_helper.py", line 9, in <module>
    from ctypes import WinDLL, c_int, c_size_t, Structure, WinError, sizeof, pointer
  File "/opt/az/lib/python3.10/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Setup a bastion host within a private subnet (no access from internet)
- Setup a debian VM within same private vnet and install a (window manager)[https://learn.microsoft.com/en-us/azure/virtual-machines/linux/use-remote-desktop?tabs=azure-cli]
- Allow RDP and SSH connections within the VNET
- Run the following command from WSL2 terminal on your workstation (outside vnet, internet access)
- `az network bastion rdp --name {} --resource-group {} --target-resource-id {}`

## Expected Behavior
Command succeeds

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.40.0 *

Extensions:
aks-preview 0.5.104

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by iseliweb** [comment]
I have the same issue but with "az network bastion tunnel" (while rdp works for me)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@fabio-s-franco Thanks for reaching out to us and reporting this issue.
Could you please run the below command to check if you have the libffi.so.7 package installed and share the output here ?  

>  apt list --installed | grep libffi

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@fabio-s-franco I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@fabio-s-franco The action is currently pending on you to share the update on the [above action plan](https://github.com/Azure/azure-cli/issues/24560#issuecomment-1305071157). If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
