### ISSUE TITLE
[az ad sp create-for-rbac] Command doesn't work in git bash on windows, works fine on cmd

### ISSUE THREAD

**Issue by sinedied** [Azure/azure-cli#24562]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
```
az ad sp create-for-rbac --name="sp-test" --role="Contributor" --scopes="/subscriptions/<subscription_id>" --sdk-auth --only-show-errors
```

**Describe the bug**
Running the command above on Git Bash terminal fails with the error shown below. The exact same command works when run in regular cmd terminal.

![image](https://user-images.githubusercontent.com/593151/200008684-f0c5c78f-4ab5-45ee-b390-75781053aba2.png)

**To Reproduce**
1. On a windows machine with Git For Windows installed, open a Git Bash terminal
2. Run the command: `az ad sp create-for-rbac --name="sp-test" --role="Contributor" --scopes="/subscriptions/<subscription_id>" --sdk-auth --only-show-errors`

**Expected behavior**
The command works the same, whatever the terminal.

**Environment summary**

Freshly installed Azure CLI on a Windows 10 machine.

```
 az --version
azure-cli                         2.42.0

core                              2.42.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\sinedied\.azure\cliextensions'

Python (Windows) 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:37:59) [MSC v.1933 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Additional context**
On a 3h workshop where we're using Azure CLI to provision the whole infrastructure, this is the only command not working on a git Bash terminal. Here's the workshop for context: https://azure.github.io/aca-java-runtimes-workshop/#creating-an-azure-service-principal

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by bebound** [comment]
I guess it's caused by [bash path conversion](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_with_git_bash.md#auto-translation-of-resource-ids)
Can you `MSYS_NO_PATHCONV=1` at the beginning of command and try again?

**Comment by sinedied** [comment]
It worked with `MSYS_NO_PATHCONV=1`.

Wouldn't it be possible to set this flag directly in the CLI command where no file paths are to be expected to avoid these kind of errors?
Or is there another way to setting a subscription scope that doesn't rely on a starting slash?

**Comment by bebound** [comment]
You can also export it as environment variable. But this may break other command, I suggest you unset it if you do not use it anymore.
Or use `//subscriptions` instead of `/subscriptions` in scope.

    is there another way to setting a subscription scope that doesn't rely on a starting slash
I'm afraid not.

**Comment by sinedied** [comment]
> Or use //subscriptions instead of /subscriptions in scope.

Thanks for the workaround suggestion. Does this work on all platforms?

**Comment by bebound** [comment]
No, it only works in Git Bash.
