### ISSUE TITLE
Create Managed Identity for Azure Stream Analytics using az cli

### ISSUE THREAD

**Issue by ravitellakula** [Azure/azure-cli#24566]
**Related command**

`az stream-analytics `

**Is your feature request related to a problem? Please describe.**

We do have an automated script to create ASA job and was looking for an option to also assign a Managed Identity right after the ASA job has been created

**Describe the solution you'd like**

Similar to other Azure PaaS Services, looking for an az cli command something like `az stream-analytics identity assign` that we could use to assign a Managed Identity from cli.

**Describe alternatives you've considered**

While we can assign Managed Identity from portal, its not ideal for our infrastructure automation.

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@ravitellakula Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Did you explore the [**az stream-analytics job update** ](https://learn.microsoft.com/en-us/cli/azure/stream-analytics/job?view=azure-cli-latest#az-stream-analytics-job-update) command with `--identity `parameter to which describes the system-assigned managed identity assigned to this job that can be used to authenticate with inputs and outputs.

If you wish to assign identity using az rest, you can follow the below:

> **az rest --method PATCH --uri "https://management.azure.com/subscriptions/XXXXXXXX/resourcegroups/MyRGName/providers/Microsoft.StreamAnalytics//streamingjobs/MyJob?api-version=2020-03-01" --body @update.json**

**Content of update.json**
{
  "identity": {
    "type": "SystemAssigned",
    "principalId": "a572b0db-6552-4b6c-9556-8b57c6b97a09",
    "tenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47"
  }
}

**Comment by navba-MSFT** [comment]
@ravitellakula I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ravitellakula The action is currently pending on you to test the above suggestion. Please feel free to reopen this thread, if you need any further assistance on this. We would be happy to help.

**Comment by ravitellakula** [comment]
@navba-MSFT ,

> Did you explore the [az stream-analytics job update ](https://learn.microsoft.com/en-us/cli/azure/stream-analytics/job?view=azure-cli-latest#az-stream-analytics-job-update)command with --identity parameter to which describes the system-assigned managed identity assigned to this job that can be used to authenticate with inputs and outputs.

I was trying to assign a System Managed Identity, and from the description you have provided this seems to authorize an existing Managed Identity vs creating a new Managed Identity.

> If you wish to assign identity using az rest, 

Will explore this option to verify if we can use the az rest, our GitHub actions are purely based on az cli commands and was hoping we could leverage cli commands over using rest api. Can you also provide a sample update.json to review the sample payload that needs to be sent to az rest command.
