### ISSUE TITLE
github action --- ERROR: unrecognized arguments: az webapp config set --startup-file=/home/site/scripts/startup.sh

### ISSUE THREAD

**Issue by SteveDevOps** [Azure/azure-cli#24573]
I am running az cli as a github action step in a called, reusable, workflow. I am specifying version 2.4.2 and error is:  unrecognized argument for --startup-file.

**step in workflow:**

 - name: Seed startup script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            az webapp deploy --resource-group `${{ inputs.TARGET_RG }}` --name `${{ inputs.TARGET_APP }}` --src-path "../scripts/startup.sh"  --type=startup --subscription "xxxx --slot `${{ inputs.TARGET_SLOT}}` \\
            az webapp config set --startup-file="/home/site/scripts/startup.sh" --resource-group `${{ inputs.TARGET_RG }}` --name `${{ inputs.TARGET_APP }}` --slot `${{ inputs.TARGET_SLOT }}` --subscription "xxxx"
    

**output from github actions debug:**

`##[debug]Result: 'az webapp deploy --resource-group xxxxx --name xxxxx --src-path "../scripts/startup.sh"  --type=startup --subscription "xxxxx" --slot pr85 \
##[debug]az webapp config set --startup-file="/home/site/scripts/startup.sh" --resource-group xxxxx --name xxxxx --slot pr85 --subscription "xxxxx"
##[debug]'
##[debug]Loading env
Run azure/CLI@v1
  with:
    azcliversion: 2.42.0
    inlineScript: az webapp deploy --resource-group xxxxxx --name spright-staging --src-path "../scripts/startup.sh"  --type=startup --subscription "xxxxx" --slot pr85 \
  az webapp config set --startup-file="/home/site/scripts/startup.sh" --resource-group xxxxx --name xxxxx --slot pr85 --subscription "xxxxx"
  
  env:
    REPO_PKG_TOKEN: ***
    SSH_AUTH_SOCK: /tmp/ssh-CNqGUNQoiram/agent.1832
    SSH_AGENT_PID: 1833
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
Starting script execution via docker image mcr.microsoft.com/azure-cli:2.42.0
ERROR: unrecognized arguments: az webapp config set --startup-file=/home/site/scripts/startup.sh
`

Of note, if I copy the resultant command from debug and run from my own local shell (also running v2.4.2), it works. I have tried different combinations of single quotes, double quotes, with/without equals sign. I have also just tried running as a normal run: command / not using the Azure/CLI marketplace action and I get the same error. -- what am I missing? Please advise. I'm stuck.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SteveDevOps** [comment]
**update**: in an attempt to get more feedback on error from cli, I broke up the two commands into separate steps.. each utilizing the marketplace azure cli action (azure/CLI@v1). Once I did this, the true error was revealed -- and it was a problem with the first commnd to upload the script:

ERROR: Either '../scripts/startup.sh' is not a valid local file path or you do not have permissions to access it

Why does this error not get revealed when both commands are combined?

So I kept commands as separate steps and I fixed the path to be a  full path within my repo.. '.github/scripts/startup.sh'

walah, fixed.

So, some feedback. How could this have been better written, using both commands in same InlineScript: | ? Is there a better debug switch to uitlize?

Or is this truly a bug?

**Comment by SteveDevOps** [comment]
This may be a pain point for lots of folks using the azure cli within github actions, when having multiple commands run at once. If you're facing "unrecognized arguments" or other strangeness, try breaking up your script to zero in on the true error. Azure CLI peeps, help us out with running multiline scripts -- recommendations -- on how we can debug better so that first error exits, to reveal itself, or some other options..  any feedback appreciated.

**Comment by SteveDevOps** [comment]
**update:** after this finding, I tried to recombine... same error (even with correct path in first command). Having to leave as separate steps.

**Comment by sarsharma** [comment]
Hi @SteveDevOps, you seem to be using `\` operator between your two inline CLI commands, you should use the `&&` operator to combine the two commands. 
Therefore, your inline command should look something like this :
````
az webapp deploy --resource-group ${{ inputs.TARGET_RG }} --name ${{ inputs.TARGET_APP }} --src-path "../scripts/startup.sh" --type=startup --subscription "xxxx --slot ${{ inputs.TARGET_SLOT}} &&
az webapp config set --startup-file="/home/site/scripts/startup.sh" --resource-group ${{ inputs.TARGET_RG }} --name ${{ inputs.TARGET_APP }} --slot ${{ inputs.TARGET_SLOT }} --subscription "xxxx"
```

**Comment by SteveDevOps** [comment]
tyvm for the feedback, I had ended up splitting into two separate steps to get it working.. (had submitted the original prob last year) -- but I will circle back and revise.. thx for  submitting a response albeit extremely delayed :P
