### ISSUE TITLE
Various Azure Virtual Network Manager extension bugs

### ISSUE THREAD

**Issue by jago2136** [Azure/azure-cli#24579]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62
Using version 2.41.0 for all bugs. We found a number of bugs from our recent bug bash. Most are minor, so I'm grouping many into one bug report. Thanks!  
1. 
**Related command**
az network manager connection subscription --help

**Describe the bug**
The description is incorrect.

**Expected behavior**
Should be "Create a connection from a subscription to a cross-tenant network manager."

2. 
**Related command**
az network manager list-active-security-admin-rule --help

**Describe the bug**
The description is not helpful.

**Expected behavior**
Should be "List all security admin rules that have been deployed by this network manager."

3. 
**Related command**
_az network manager list-active-security-admin-rule_ and _az network manager list-active-connectivity-config_

**Describe the bug**
One of the parameters for this command is '--regions' which will filter the response based on the regions provided. However, the current behavior is that no items are being filtered, because the request is not being sent with the regions list.

**Expected behavior**
The user should have the option to specify one or more regions. If they do, a list of regions should be passed in the request.

4. 
**Related command**
az network manager create

**Describe the bug**
'--display-name' is listed as a parameter in the example.

**Expected behavior**
Display name is no longer a parameter on any of our service's resources. Please remove 'display name' from any descriptions or examples. 

5. 
**Related command**
az network manager group list -- **please check all commands for this though!**

**Describe the bug**
If the system data contains any null properties, an error is displayed to the user as the list cannot be parsed.

**Expected behavior**
If system data contains any null properties, the data should still be parsed and returned to the user. See below where I have a network group with no createdBy or createdAt value. When this network group is present in the list response, the following error will be displayed. Please check all commands to ensure these null systemdata values are handled properly.
![image](https://user-images.githubusercontent.com/42753636/200380013-06d0176e-cec5-4fd4-b85e-999aab9ba91d.png)
![image](https://user-images.githubusercontent.com/42753636/200379869-472a6d44-b3b4-4433-aa6e-49be18896ac2.png)

**Comment by yonzhan** [comment]
@necusjz for awareness
