### ISSUE TITLE
az billing invoice download asks for --invoice-name despite being provided

### ISSUE THREAD

**Issue by AtiX** [Azure/azure-cli#24571]
## Describe the bug

When attempting to get a download URL for an invoice, the CLI throws an error expecting the `--invoice-name` parameter - despite having it provided as part of the call.

**Command Name**
`az billing invoice download`

**Errors:**
```
--invoice-name is also required
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az billing invoice download --invoice-name "Exxx" --download-token "Drs_xxx" --account-name "xxx"`

## Expected Behavior

It should process the command and return a URL for download

## Environment Summary

```
macOS-13.0-x86_64-i386-64bit, Darwin 22.1.0
Python 3.10.8
Installer: HOMEBREW

azure-cli 2.42.0

Extensions:
account 0.2.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@AtiX Thank you for reaching out, we are looking into it.
