### ISSUE TITLE
Running "az extension add --name containerapp" results in error

### ISSUE THREAD

**Issue by jasontaylordev** [Azure/azure-cli#24586]
**Related command**
az extension add --name containerapp

**Describe the bug**
The extension fails to install. I receive the error:
`An error occurred. Pip failed with status code 2. Use --debug for more information.`

**To Reproduce**
`az extension add --name containerapp`

**Expected behavior**
The extension is installed.

**Environment summary**
Install Method: MSI
CLI Version: Azure CLI 2.4.2
OS: Windows 11 10.0.22621 Build 22621
Shell Type: PowerShell 7.2.7

**Additional context**
Running `az extension add --name containerapp --debug *> .\debug.txt`

[debug.txt](https://github.com/Azure/azure-cli/files/9958108/debug.txt)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@jasontaylordev I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by jasontaylordev** [comment]
> @jasontaylordev I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

See **Additional context** in issue description:

![image](https://user-images.githubusercontent.com/1988321/201267379-3281ecdf-7a9a-465c-b636-f290c349dd2e.png)

**Comment by navba-MSFT** [comment]
@jasontaylordev My Bad, I complete missed the attached debug.txt file from your issue description. I am looking into this. I will update this thread once I am done.

**Comment by navba-MSFT** [comment]
@jasontaylordev I am unable to reproduce this issue at my end. This issue seems to be specific to your environment. Could you please run `pip list ` command to show the version of setuptools and share the output here ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@jasontaylordev Looking deeper into the debug logs, We could see in the log, that packages are installed by C:\Users\jason\AppData\Roaming\Python\Python310-32\site-packages\pip, which should be C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip. Uninstall that python and try reinstalling again.
