### ISSUE TITLE
az role assignment create fails

### ISSUE THREAD

**Issue by hoffmann** [Azure/azure-cli#2458]
az role assignment create --debug --assignee XXX-XXX-XXX-XXX-XXX  --role XXX-XXX-XXX-XXX-XXX --resource-group rgname

fails with The request was incorrectly formatted.
```

msrest.http_logger : Request body:
msrest.http_logger : {"properties": {"roleDefinitionId": "XXX-XXX-XXX-XXX-XXX", "principalId": "XXX-XXX-XXX-XXX-XXX"}}
requests.packages.urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com
requests.packages.urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/XXX-XXX-XXX-XXX-XXX/resourceGroups/XXX/providers/Microsoft.Authorization/roleAssignments/XXX-XXX-XXX-XXX-XXX?api-version=2015-07-01 HTTP/1.1" 400 88
msrest.http_logger : Response status: 400

msrest.http_logger : Response content:
msrest.http_logger : b'{"error":{"code":"BadRequestFormat","message":"The request was incorrectly formatted."}}'
msrest.exceptions : The request was incorrectly formatted.
```

**Comment by tjprescott** [comment]
@yugangw-msft can you take a look?

**Comment by yugangw-msft** [comment]
@hoffmann, please use '--debug' and share with the verbose output

**Comment by lanpar** [comment]
this thing is still a problem

**Comment by asc-adean** [comment]
Agreed with @lanpar this is still a problem, even in Terraform (I understand this isn't a Terraform problem, but I see it in Terraform just the same)

This works:
```
resource "azurerm_role_assignment" "Azure-Admins_roleassignment" {
  scope              = "/subscriptions/${var.subscription_id}/resourceGroups/${var.resource_group_name}/providers/Microsoft.Compute/virtualMachines/vmname-VM"
  role_definition_name = "Virtual Machine Administrator Login"
  principal_id       = "014a520d-9a93-4dee-9644-9f1b1f228b87"
}
```
`azurerm_role_assignment.Azure-Admins_roleassignment: Creation complete after 2s (ID: /subscriptions/e465f7b1-95ef-4fab-69b6-...s/63644e80-73a8-0158-b49d-ac9426abe562)`

This does not:
```
resource "azurerm_role_assignment" "Azure-Admins_roleassignment" {
  scope              = "/subscriptions/${var.subscription_id}/resourceGroups/${var.resource_group_name}/providers/Microsoft.Compute/virtualMachines/vmname-VM"
  role_definition_id = "1c0163c0-47e6-4577-8991-ea5c82e286e4"
  principal_id       = "014a520d-9a93-4dee-9644-9f1b1f228b87"
}
```
`* azurerm_role_assignment.Azure-Admins_roleassignment: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequestFormat" Message="The request was incorrectly formatted."`

**Comment by hasheddan** [comment]
@asc-adean are you still experiencing this issue?

**Comment by asc-adean** [comment]
@hasheddan I will try it again this afternoon, thank you for responding

**Comment by RoozbehBandpey** [comment]
Change your `roleDefinitionId` to absolute. Following is ARM resource snippet
`
"resources": [
        {
            "type": "Microsoft.Authorization/roleAssignments",
            "apiVersion": "[parameters('apiVersion')]",
            "name": "[variables('roleAssignmentName')]",
            "properties": {
                "roleDefinitionId": "[resourceId('Microsoft.Authorization/roleDefinitions', parameters('roleDefinitionId'))]",
                "principalId": "[parameters('principalId')]",
                "principalType": "[parameters('principalType')]",
                "canDelegate": "false",
				"scope": "[resourceGroup().id]"
            }
        }
    ],
`

**Comment by jiasli** [comment]
This issue has long been fixed in #2667. 

`--role` now supports 3 formats:

- ARM resource ID, like `/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7`
- GUID, like `acdd72a7-3385-48ef-bd42-f606fba81ae7`
- Name, like `Reader`

Source code:

https://github.com/Azure/azure-cli/blob/df737edb429a03a16794f8eb8d63435507c84562/src/azure-cli/azure/cli/command_modules/role/custom.py#L561-L579

**Comment by tzaroon** [comment]
### Issue Resolved on my end.

I was trying to give the role to the storage in the bicep.

`var storageBlobDataContributorRoleID = 'ba92f5b4-2d11-453d-a403-e96b0029c9fe'`

**I was writing this property as :**
`roleDefinitionId: storageBlobDataContributorRoleID`

**The I tried this one:**
`roleDefinitionId: resourceId('Microsoft.Authorization/roleDefinitions', storageBlobDataContributorRoleID)`

It worked perfectly.

**Comment by jiasli** [comment]
@tzaroon, your issue doesn't seem to be related to Azure CLI. Please only report Azure CLI-related issues in this repo. Thanks.

**Comment by AndreasHassing** [comment]
> @tzaroon, your issue doesn't seem to be related to Azure CLI. Please only report Azure CLI-related issues in this repo. Thanks.

An argument could be made that @tzaroon posting their findings are useful because this GH issue is one of the first results when you search for the error message in relation to role definitions. I had a similar issue and @tzaroon's post resolved it for me 🤷‍♂️.

**Comment by kenchon** [comment]
@jiasli 
I came across this issue during deploying resources using ARM template (not az cli).
I hope the maintainers to improve documentations as there're no sample values to input.
c.f. https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/scenarios-rbac#scope
