### ISSUE TITLE
AzureCLI@2 in Azure DevOps overrides python version

### ISSUE THREAD

**Issue by fuhuifang** [Azure/azure-cli#24585]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

task: AzureCLI@2 in Azure DevOps pipeline

**Describe the bug**

In my ADO pipeline yaml, I first have a task to pin down python version to 3.8, and then a `AzureCLI@2` task to run some python commands.
![image](https://user-images.githubusercontent.com/32152743/200479976-1ed5dc4c-54ef-454f-a07a-76a126d7d6c3.png)
![image](https://user-images.githubusercontent.com/32152743/200480009-3c1bb56c-43df-4e44-a541-7ea15d4abc95.png)
However, in the pipeline https://msdata.visualstudio.com/Vienna/_build/results?buildId=76061171&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ed51bc88-ea39-56fb-53bb-66c4adef626f, the python version is 3.10.
![image](https://user-images.githubusercontent.com/32152743/200480266-dbc387f0-605f-4143-9506-dc90403e7a96.png)
This didn't happen before, and if I pin down azure-cli explicitly to 2.41.0, https://msdata.visualstudio.com/Vienna/_build/results?buildId=76058939&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ed51bc88-ea39-56fb-53bb-66c4adef626f shows correct python version.
![image](https://user-images.githubusercontent.com/32152743/200480396-72dd160e-bcd2-4412-a3f2-199393b83e50.png)

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
@wangzelin007 for awareness

**Comment by wangzelin007** [comment]
Hi @fuhuifang,
I think you should open this issue in [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues).
I don't think the azure-cli team is responsible for the ADO task `AzureCLI@2`. 
@jiasli,
Please correct me if I'm wrong.

**Comment by fuhuifang** [comment]
Thanks @yonzhan and @wangzelin007. Reposting as https://github.com/microsoft/azure-pipelines-tasks/issues/17133.
