### ISSUE TITLE
'az monitor app-insights component connect-webapp' needs to support cross resource groups

### ISSUE THREAD

**Issue by toddfoust** [Azure/azure-cli#24584]
### Related command

az monitor app-insights component connect-webapp -g Azmontest -a anapaquete --web-app /subscriptions/a0ff1dda-2b82-49f2-b600-2c67613f04b0/resourceGroups/myjavawebappforai_group/providers/Microsoft.Web/sites/myjavawebappforai --enable-profiler false --enable-snapshot-debugger false

### Resource Provider

Microsoft.Web

### Description of Feature or Work Requested

Hey team, customers who own App Services may want to enable Application Insights so that telemetry from their web app flows into an App Insights instance. The customer was running the following command but it fails because the Application Insights and App Services are not in the same resource group. The request here is that the "-g" resource group parameter apply to one but not both of the resources, or allow customers to supply full URIs to the App Insights or Web Site instance. 

az monitor app-insights component connect-webapp -g Azmontest -a anapaquete --web-app /subscriptions/a0ff1dda-2b82-49f2-b600-2c67613f04b0/resourceGroups/myjavawebappforai_group/providers/Microsoft.Web/sites/myjavawebappforai --enable-profiler false --enable-snapshot-debugger false

The above cmdlet fails on this API call because the URI formed does not exist due to wrong resource group selection. https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/list-application-settings. Customers should be allowed to tie these two resources together if they are in different resource groups or in different subscriptions. 

Note, I've been told by Kai Ru the following above the issue above... "The command `az monitor app-insights component connect-webapp` is a convenience command of `az webapp config appsettings set`. The customer can use the following commands to work around.

# 1. get the instrumentationKey of AI
instrumentationKey=$(az monitor app-insights component show --app anapaquete -g Azmontest --query instrumentationKey -o tsv) 

# 2. update appsetting
az webapp config appsettings set --name myjavawebappforai --resource-group myjavawebappforai_group --settings APPINSIGHTS_INSTRUMENTATIONKEY=$instrumentationKey APPINSIGHTS_PROFILERFEATURE_VERSION=disabled APPINSIGHTS_SNAPSHOTFEATURE_VERSION=disabled
"

We'll use the workaround for now, but the az cmdlet should support connecting the two resources together who are in separate resource groups or in separate subscriptions. 

### Minimum API Version Required

N/A

### Swagger PR link / SDK link

N/A

### Target Date

2023-02-01

### Additional context

No rush on this, but it would make sense to allow customers to point App Services to an App Insights instance in a diff subscription or resource group. Kai provided us a workaround that we'll take to the customer impacted by this limitation in the CLI

**Comment by yonzhan** [comment]
monitor feature
