### ISSUE TITLE
Uppercase transform in CLI

### ISSUE THREAD

**Issue by rahulbissa2727** [Azure/azure-cli#24596]
### Related command

 az network application-gateway waf-policy custom-rule match-condition add --resource-group MyResourceGroup --policy-name MyPolicy --name MyWAFPolicyRule --match-variables RequestHeaders.value --operator contains --values foo boo --transform uppercase

### Resource Provider

Microsoft.Network

### Description of Feature or Work Requested

Changes for this are already added in CLI. But usage of this feature requires min API version of 2022-05-01 but currently CLI seems to be on 2022-01-01. Therefore, we request you to update the API version used by CLI.

### Minimum API Version Required

2022-05-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/20674

### Target Date

2022-11-20

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by rahulbissa2727** [comment]
Any updates on this. Our team needs this change in the current milestone for GA of Uppercase transform feature.

**Comment by necusjz** [comment]
@rahulbissa2727 As limited bandwidth, we plan to deliver it in the next sprint (details: https://github.com/Azure/azure-cli/milestone/125).
