### ISSUE TITLE
Incorrect references in `az network private-endpoint create` documentation

### ISSUE THREAD

**Issue by jdkr0220** [Azure/azure-cli#24592]
There are references to `az network private-link-resource list` that aren't valid. Perhaps they're supposed to be `az network private-endpoint list-types`, although that doesn't match per the error... To get the value I needed, I had to run `az keyvault private-link-resource list --vault-name $kvName` which unfortunately isn't very generic

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8911e94f-9496-a68d-50c0-b5d536a375a4
* Version Independent ID: cc37b77b-0fa2-991b-e16b-fcdbbf183853
* Content: [az network private-endpoint](https://learn.microsoft.com/en-us/cli/azure/network/private-endpoint?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/private-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/private-endpoint.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by RakeshMohanMSFT** [comment]
@jdkr0220 Thank you for reaching out us, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@jdkr0220 The command is valid for returning private link references. You can read more about it here https://learn.microsoft.com/en-us/cli/azure/network/private-link-resource?view=azure-cli-latest You can see below screenshot having an example.
![image](https://user-images.githubusercontent.com/49954584/200993015-8a2a241f-a164-4539-a068-89618e93297f.png)
