### ISSUE TITLE
az login --tennat <tenant-ID> failing because of SSLCertVerification

### ISSUE THREAD

**Issue by ARaheem-Work** [Azure/azure-cli#24597]
> ### `az login --tenant <tenant-id>` failes on windows 10, Powershell console (PS version:5.1.19041.1682 ). Az CLI version: 2.42.0

**Related command**

az login
az login --tenant tenant-guid
**Describe the bug**

I just installed Azure CLI on windows 10 Enterprise (10.0.19044) and I am getting following error when I run az login --tenant <tenant-id> command. My machine can talk to internet fine. 

HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /a4f66939-8f60-4185-b79b-032685a0e82a/v2.0/.well-known/openid-configuration (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle. More info: https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy.

**To Reproduce**
Install Azure CLI (version 2.42.0) on Windows 10 and run command: az login --tenant tenant-guid

**Expected behavior**

Az CLI should be authenticated.

**Environment summary**

OS Version: Windows 10 Enterprise (10.0.19044)
PowerShell Version: 5.1.19041.1682
Az CLI Version: 2.42.0

**Additional context**

The machine experiencing problem has internet. I can login to Azure portal and same tenant successfully using MS Edge browser.

**Comment by yonzhan** [comment]
Could you run this command to see if you can connect to https://login.microsoftonline.com with python?

python -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"

**Comment by jiasli** [comment]
Per the error message:

```
certificate verify failed: self signed certificate in certificate chain
```

This seems to be caused by intercepted HTTPS traffic by a proxy. Could you run this command to see if you can connect to `https://login.microsoftonline.com` directly with Python?

```
"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import requests; print(requests.get('https://login.microsoftonline.com/').status_code)"
```

If not, could you follow https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy to add your self-signed certificate to the CA bundle?

**Comment by ARaheem-Work** [comment]
I followed instructions and was able to connect to Azure using Azure CLI. This issue can be closed now. Thanks.
