### ISSUE TITLE
No options to append operations while importing API using az apim api import

### ISSUE THREAD

**Issue by Gauravpitroda** [Azure/azure-cli#24591]
There is no option into **az apim api import** for import method or conflict resolution in Azure CLI's az apim api import command.
![image](https://user-images.githubusercontent.com/3489049/200644894-5b134683-953d-4a05-b0ee-bf91487d1cf7.png)

Using the import command always overwrites all APIs and there is no way to append operations using OpenAPI specification file.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@Gauravpitroda Thank you for reaching out, we are looking into it.
