### ISSUE TITLE
Remove access policy from key vault

### ISSUE THREAD

**Issue by casfrost** [Azure/azure-cli#24598]
**Related command**

`az keyvault delete-policy`

**Is your feature request related to a problem? Please describe.**

I am writing a script that should remove all user access policys for key vaults in a given environment. This is not possible with the azure-cli, but only with a Powershell module (https://learn.microsoft.com/en-us/powershell/module/az.keyvault/remove-azkeyvaultaccesspolicy?view=azps-9.1.0).

**Describe the solution you'd like**

an `az keyvault delete-policy` that takes an ObjectID and removes the access policy for the given object.

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
@evelyn-ys for awareness
