### ISSUE TITLE
Add az vm list filter for VMSS

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#24609]
### Related command

`az vm list -g myResourceGroup --vmss myVMSSFlex`

### Resource Provider

Microsoft.compute/virtualmachines

### Description of Feature or Work Requested

List VM API supports ability to filter list to instances in a vmss. Would like to add this filter to the VM list command

### Minimum API Version Required

2021-03-01

### Swagger PR link / SDK link

This is in production in the ComputeRP swaggeeeer already

### Request Example

GET https://management.azure.com/subscriptions/576f5e67-b043-4ec9-81e9-47c7e8692cc4/resourceGroups/tutorials/providers/Microsoft.Compute/virtualMachines?api-version=2022-08-01&$filter='virtualMachineScaleSet/id' eq '/subscriptions/576f5e67-b043-4ec9-81e9-47c7e8692cc4/resourceGroups/tutorials/providers/Microsoft.Compute/virtualMachineScaleSets/create-1'

### Target Date

2023-01-31

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness
