### ISSUE TITLE
Azure CLI release for Microsoft.Elastic for version 2023-02-01-preview

### ISSUE THREAD

**Issue by utkarshjain1508** [Azure/azure-cli#24618]
### Resource Provider

Microsoft.Elastic

### Description of Feature or Work Requested

We want a new azure cli release which supports the features present in our api version 2022-07-01-preview.

### Minimum API Version Required

2022-07-01-preview

### Swagger PR link / SDK link

latest PR : https://github.com/Azure/azure-rest-api-specs/pull/22638
Swagger : https://github.com/Azure/azure-rest-api-specs/tree/main/specification/elastic/resource-manager/Microsoft.Elastic/preview/2023-02-01-preview

### Target Date

2022-11-18

### Additional context

The feature request has been edited to release the latest RP version.

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by jsntcy** [comment]
Involve CLI PM @Jacekey23 Jeremy Li FTE to help you go through APEX onboarding process.

**Comment by Jeremygarden** [comment]
@utkarshjain1508 Below is the formal onboarding survey. It's required procedure to have Azure CLI to sign-off.
https://aka.ms/PLRCLIOnboardSurvey

We are not mandatory if it's not GA, please refer to [APEX Criteria from Azure Global team](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/39224/APEX-Launch-Criteria) 

If you've done the survey, it means the request tracked in ADO, please reply if having any questions, or we are going to close this issue. Thanks.

cc: @jsntcy

**Comment by Jacekey23** [comment]
@utkarshjain1508 Below is the APEX onboard survey link that is required step to do before CLI get started to work.
https://aka.ms/PLRCLIOnboardSurvey

We CLI are not mandatory till GA phase according to [APEX Criteria](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/39224/APEX-Launch-Criteria) from Azure Global.

If you've done the survey and have it tracked in ADO, please reply to keep us posted. Or we are about to move/drop this due to CLI sprint cadence.

Thanks, J

**Comment by utkarshjain1508** [comment]
Hi @Jacekey23 . Our service is in GA and already onboarded to CLI. This issue was meant for a new CLI release. However the release is blocked because of some issues in our swagger which have now trigged breaking changes. You can follow the latest PR https://github.com/Azure/azure-rest-api-specs/pull/21670. We will update once the swagger the changes are updated and then continue with the release.

**Comment by jsntcy** [comment]
@utkarshjain1508, 
".Our service is already onboarded to CLI.", do you mean there is already CLI module?

**Comment by utkarshjain1508** [comment]
@jsntcy Yes we already have a cli module for our service. We created this issue for a new cli release which contains some new features. However during cli release we faced some swagger issues which we are fixing.

**Comment by jsntcy** [comment]
@utkarshjain1508, Got it. Once the swagger is ready, we encourage your team to use our [new codegen tool](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/teams_docs/azcli_docs/setup_for_codegen) (UI based, easy to use) to generate CLI commands automatically.

**Comment by utkarshjain1508** [comment]
@Jing-song as discussed I have updated the feature request to release the cli for the latest RP version. Please let us know if anything else is needed.
