### ISSUE TITLE
az vm list returns empty, even though there are VMs in the RG

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#24612]
## Describe the bug

az vm list shows zero results, even though there are VMs in the rg

**Command Name**
`az vm list`

**Errors:**
```
![image](https://user-images.githubusercontent.com/157768/201040619-1a7c5392-1921-4165-b790-e60dad678684.png)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm list -g {} --debug`

## Expected Behavior

Should show the VMs I have in the resource group
## Environment Summary
```
Linux-5.4.0-1094-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.42.0

Extensions:
ai-examples 0.2.5
ml 2.10.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@fitzgeraldsteele Could you please send the debug log *(add --debug)* to me by email? My email address is Zhou.Xing@microsoft.com
