### ISSUE TITLE
Microsoft.Storage/storageAccounts networkAcls.virtualNetworkRules.id property does not accept functions

### ISSUE THREAD

**Issue by Mrlnvndn** [Azure/azure-cli#24613]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
When deploying a storage account (Microsoft.Storage/storageAccounts) via an ARM template, I cannot set the value for the virtualNetworkRules.id property, because it does not accept functions as a value. I need this because I want to use the same template for different environments

**To Reproduce**
deploy an arm template with the resource 'Microsoft.Storage/storageAccounts' where the property networkAcls.virtualNetworkRules.id gets its value via a variable, parameter or a function

**Expected behavior**
The function is evaluated and the resulting value is used as the value for the networkAcls.virtualNetworkRules.id property

**Environment summary**
ARM template deployment in Azure DevOps pipeline

**Comment by yonzhan** [comment]
route to CXP team

**Comment by Mrlnvndn** [comment]
Could I get an update?

**Comment by navba-MSFT** [comment]
@Mrlnvndn Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please check if [this](https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.storage/blob-storage-private-endpoint) ARM template sample helps ?

**Comment by navba-MSFT** [comment]
@Mrlnvndn I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by Mrlnvndn** [comment]
I would like to link a storage account to a virtual network directly upon creating the storage account in an ARM template, where the id of the virtual network is passed down via a variable which allows us to use the same arm template for multiple environments. The provided solution above does not help with that.

![image](https://user-images.githubusercontent.com/34515034/211290342-bd86d8af-f245-42cf-aace-c3e90ce6ea22.png)

**Comment by navba-MSFT** [comment]
@Mrlnvndn Thanks for your reply and clarifying your ask. Please find the sample template that creates a storage account and allows you to specify a list of virtual network rules as a variable:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "storageAccountName": {
            "type": "string",
            "metadata": {
                "description": "The name of the storage account to create."
            }
        },
        "virtualNetworkRules": {
            "type": "array",
            "metadata": {
                "description": "An array of virtual network rules to apply to the storage account."
            }
        }
    },
    "resources": [
        {
            "type": "Microsoft.Storage/storageAccounts",
            "name": "[parameters('storageAccountName')]",
            "apiVersion": "2021-06-01",
            "location": "[resourceGroup().location]",
            "sku": {
                "name": "Standard_LRS"
            },
            "kind": "Storage",
            "properties": {
                "networkAcls": {
                    "virtualNetworkRules": "[parameters('virtualNetworkRules')]"
                }
            }
        }
    ]
}

```
You would then pass the virtualNetworkRules parameter as a variable when deploying the template. Each item in the virtualNetworkRules array should be an object with properties for id (the ID of the virtual network) and subnet (the name of the subnet within the virtual network).

Here is an example of how you would define the virtualNetworkRules parameter when deploying the template:

```
{
    "virtualNetworkRules": [
        {
            "id": "/subscriptions/12345678-1234-1234-1234-1234567890ab/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/myVnet1",
            "subnet": "subnet1"
        },
        {
            "id": "/subscriptions/12345678-1234-1234-1234-1234567890ab/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/myVnet2",
            "subnet": "subnet2"
        }
    ]
}

```
Please note, this is an example and for the actual deployment you should replace the variables, ids and properties specific to your implementation.

**Comment by navba-MSFT** [comment]
@Mrlnvndn I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.
