### ISSUE TITLE
Not a able to create empty folder on blob container

### ISSUE THREAD

**Issue by kranthikumar-kvs-by** [Azure/azure-cli#24614]
Using below command not allowing to create empty folder on blob container -

`az storage blob directory create --container-name oa-custom-container --directory-path Custom --account-name "<Removed>" --account-key "<Removed>"`

![image](https://user-images.githubusercontent.com/60686473/201119221-ba382064-19b6-4b16-8efa-4d5c15115648.png)

And we even tried to use another command but still same issue -

`az storage fs directory create --name oa-custom-container --file-system Custom --account-name "<Removed>" --account-key "<Removed>"`

![image](https://user-images.githubusercontent.com/60686473/201120758-5d6ac438-9b9a-49da-b193-531a7b9e82d7.png)

Please suggest how can we create an empty folder on blob container.

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
To create real directory, please create storage account enabling hierarchical namespace: `az storage account create --hns true`

**Comment by kranthikumar-kvs-by** [comment]
What do you mean by real folder?
We have a use case to create an empty folder in the blob container.

How does hns related for creating empty folder in the blob container?
Please provide some documentation which states this.

**Comment by evelyn-ys** [comment]
Here's the doc from storage service: https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction#one-service-multiple-concepts

**Comment by kranthikumar-kvs-by** [comment]
Thank you, after enabling HNS it worked.
