### ISSUE TITLE
`az storage blob upload` can't upload file `%C3%90_%EF%BF%BD_test.txt`: HTTP Error 400. The request URL is invalid.

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#24623]
**Related command**
`az storage blob upload`

**Describe the bug**

The file name `Ð_�_test.txt` contains Unicode. When uploading this file, get error:

```
> az storage blob upload --account-name jlst1111 --container-name con1 -f Ð_�_test.txt --overwrite
Argument '--overwrite' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus

There are no credentials provided in your command and environment, we will query for account key for your storage account.
It is recommended to provide --connection-string, --account-key or --sas-token in your command as credentials.

You also can add `--auth-mode login` in your command to use Azure Active Directory (Azure AD) for authorization if your login account is assigned required RBAC roles.
For more information about RBAC roles in storage, visit https://docs.microsoft.com/azure/storage/common/storage-auth-aad-rbac-cli.

In addition, setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information about environment variable usage.
Unexpected return type <class 'str'> from ContentDecodePolicy.deserialize_from_http_generics.
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>

ErrorCode:None
```

**Comment by jiasli** [comment]
According to

- https://stackoverflow.com/questions/7291120/get-unicode-code-point-of-a-character-using-python
- https://docs.python.org/3/library/codecs.html#text-encodings

we can use a Python script get the string representation and Unicode codepoint of file name `%C3%90_%EF%BF%BD_test.txt`:

```py
from urllib.parse import unquote
print(unquote('%C3%90_%EF%BF%BD_test.txt'))
print(unquote('%C3%90_%EF%BF%BD_test.txt').encode('unicode_escape').decode('latin-1'))
```

Output:

```
Ð_�_test.txt
\xd0_\ufffd_test.txt
```

According to https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#unicode-characters-not-supported-in-container-or-blob-names, `U+FFFD` is not an allowed character in blob name.

Weirdly though, as I tested, these names work:

```
_�.txt
Ð_test.txt
D_�.txt
test�.txt
�.txt
```

Not sure how Storage service detects whether a name is allowed or not. 🤔

**Additional information**

A Unicode character's codepoint can also be retrieved using `ord`:

```py
print('微软'.encode('unicode_escape').decode('latin-1'))
print(hex(ord('微')))
print(hex(ord('软')))
```

Output:

```
\u5fae\u8f6f
0x5fae
0x8f6f
```

See https://note.nkmk.me/en/python-chr-ord-unicode-code-point/

**Comment by yuaw** [comment]
Very helpful! This explains how to convert a URL encoded string to a unicode character. Thanks for the great insight on this topic.
