### ISSUE TITLE
Can not create linux runtime for AppService

### ISSUE THREAD

**Issue by sokichi-fj** [Azure/azure-cli#24620]
We confirmed the AppService's node.js runtime for Linux.

```
az webapp list-runtimes --os-type linux
[
           : 
  "NODE:18-lts",
  "NODE:16-lts",
  "NODE:14-lts",
           :
]
```

But azure-cli try to create windows runtime even if we write linux runtime name.

```
az webapp create --resource-group RG --plan PLAN --name APP --runtime "NODE:18-lts" --deployment-local-git
Windows runtime 'NODE|18-lts' is not supported. Please invoke 'az webapp list-runtimes' to cross check
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by sokichi-fj** [comment]
I could understand the situation: 

- In AppService, a plan can not have both Linux and Windows 
- Default plan might be for windows if developer use `az` command to create the plan
- So our plan was for Windows
- Then above error message was displayed.

However the error message is little confusing because `az webapp list-runtimes` displays linux tuntimes. 

If plan is for windows, above error message should display `az webapp list-runtimes --os-type windows`.

**Comment by navba-MSFT** [comment]
@sokichi-fj Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@sokichi-fj I tried to run the same above command from PowerShell and CMD prompt. It worked fine on both. I am unable to reproduce this issue.

I am sending you the series of commands that I ran.

>az group create -l eastus -n MyRgName
>az appservice plan create -g MyRgName -n MyPlan --is-linux --number-of-workers 4 --sku S1
>az webapp create --resource-group MyRgName --plan MyPlan --name MyAppName --runtime "NODE:18-lts" --deployment-local-git

Please try to run again and check if that helps.

- May I know where are you running your AzureCLI command from ? 
- May I know your Azure CLI Version ? 

Awaiting your reply.

**Comment by sokichi-fj** [comment]
@navba-MSFT Of course, we also could work on `--is-linux` plan. 

Problem is about Windows plan like:

```
az group create -l eastus -n MyRgName
az appservice plan create -g MyRgName -n MyPlan 
az webapp create --resource-group MyRgName --plan MyPlan --name MyAppName --runtime "NODE:18-lts" --deployment-local-git
```

This command display error message that force user to execute `az webapp list-runtimes` which displays linux runtime.
`az webapp list-runtimes --os-type windows` is the right message.

**Comment by navba-MSFT** [comment]
@sokichi-fj Thanks for getting back and clarifying the ask. The command `az webapp list-runtimes` displays **both** linux and windows see below:

>az webapp list-runtimes
{
  "**linux**": [
    "DOTNETCORE:7.0",
    "DOTNETCORE:6.0",
    "DOTNETCORE:3.1",
    "NODE:18-lts",
    "NODE:16-lts",
    "NODE:14-lts",
    "PYTHON:3.10",
    "PYTHON:3.9",
    "PYTHON:3.8",
    "PYTHON:3.7",
    "PHP:8.1",
    "PHP:8.0",
    "PHP:7.4",
    "RUBY:2.7",
    "JAVA:17-java17",
    "JAVA:11-java11",
    "JAVA:8-jre8",
    "JBOSSEAP:7-java11",
    "JBOSSEAP:7-java8",
    "TOMCAT:10.0-java17",
    "TOMCAT:10.0-java11",
    "TOMCAT:10.0-jre8",
    "TOMCAT:9.0-java17",
    "TOMCAT:9.0-java11",
    "TOMCAT:9.0-jre8",
    "TOMCAT:8.5-java11",
    "TOMCAT:8.5-jre8",
    "GO:1.19",
    "GO:1.18"
  ],
  "**windows**": [
    "dotnet:7",
    "dotnet:6",
    "DOTNETCORE:3.1",
    "ASPNET:V4.8",
    "ASPNET:V3.5",
    "NODE:18LTS",
    "NODE:16LTS",
    "NODE:14LTS",
    "PHP:7.4",
    "java:1.8:Java SE:8",
    "java:11:Java SE:11",
    "java:17:Java SE:17",
    "java:1.8:TOMCAT:10.0",
    "java:11:TOMCAT:10.0",
    "java:17:TOMCAT:10.0",
    "java:1.8:TOMCAT:9.0",
    "java:11:TOMCAT:9.0",
    "java:17:TOMCAT:9.0",
    "java:1.8:TOMCAT:8.5",
    "java:11:TOMCAT:8.5",
    "java:17:TOMCAT:8.5"
  ]
}

**Comment by sokichi-fj** [comment]
@navba-MSFT Thank you for supporting my report.
