### ISSUE TITLE
[Virtual WAN] Deprecate RTv2 CLI commands

### ISSUE THREAD

**Issue by dedhar** [Azure/azure-cli#24629]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
Deprecate RTv2 CLI commands : --connections is supported only for RTv2 and not RTv3 and should now be removed
az network vhub route-table create --name
                                   --resource-group
                                   --vhub-name
                                   **[--connections {All_Branches, All_Vnets}]**
                                   [--destination-type {CIDR, ResourceId, Service}]
                                   [--destinations]
                                   [--labels]
                                   [--next-hop]
                                   [--next-hop-type {IPAddress, ResourceId}]
                                   [--next-hops]
                                   [--no-wait]
                                   [--route-name]
![image](https://user-images.githubusercontent.com/16656177/201392764-032842f4-0415-4ef1-9f87-0af00da5a6e4.png)

**Describe the bug**
Remove the parameter --connections which was part of RTv2 vWAN CLI cmdlets.
https://portal.microsofticm.com/imp/v3/incidents/details/348194049/home

**To Reproduce**
![image](https://user-images.githubusercontent.com/16656177/201393096-64a6b4b7-54f6-4874-9fc6-740458fe2fd5.png)

**Expected behavior**
Following is a working cmdlet 👍 az network vhub route-table create -n MyRouteTable -g MyResourceGroup --vhub-name MyVhub --route-name MyRoute --destination-type CIDR --destinations "10.4.0.0/16" "10.6.0.0/16" --next-hop-type ResourceId --next-hop /subscriptions/MySub/resourceGroups/MyResourceGroup/providers/Microsoft.Network/azureFirewalls/MyFirewall --labels label1 label2

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
@necusjz for awareness
