### ISSUE TITLE
`az sig image-version create` in `2.42.0`: os-vhd-storage-account must be a managed disk or snapshot.

### ISSUE THREAD

**Issue by Mikebeem** [Azure/azure-cli#24624]
## Describe the bug
I'm getting an error message, while I don't think this error applies to my parameters. The error started in azure cli 2.42.0. 
I'm using this in a pipeline in Azure DevOps. Until last monday the agent was on azure cli 2.41.0 and the pipeline including this command was running without any issues. 

I'm using the example from here:
https://learn.microsoft.com/en-us/cli/azure/sig/image-version?view=azure-cli-latest#az-sig-image-version-create

Using the exmample with text: Add a new image version from a snapshot of an OS disk and add additional snapshots as data disks

**Command Name**
`az sig image-version create` 

And including the parameters:
```
az sig image-version create --resource-group MyResourceGroup \
--gallery-name MyGallery --gallery-image-definition MyImage \
--gallery-image-version 1.0.0 \
--os-vhd-storage-account /subscriptions/00000000-0000-0000-0000-00000000xxxx/resourceGroups/imageGroups/providers/Microsoft.Storage/storageAccounts/mystorageaccount \
--os-vhd-uri https://mystorageaccount.blob.core.windows.net/container/path_to_vhd_file
```
**Errors:**

```
WARNING: source is not a known attribute of class <class 'azure.mgmt.compute.v2022_03_03.models._models_py3.GalleryImageVersionPublishingProfile'> and will be ignored
WARNING: uri is not a known attribute of class <class 'azure.mgmt.compute.v2022_03_03.models._models_py3.GalleryArtifactVersionSource'> and will be ignored

ERROR: (InvalidParameter) The source id: '/subscriptions/00000000-0000-0000-0000-00000000xxxx/resourceGroups/imageGroups/providers/Microsoft.Storage/storageAccounts/mystorageaccount' must be a managed disk or snapshot.
Code: InvalidParameter
Message: The source id: '/subscriptions/00000000-0000-0000-0000-00000000xxxx/resourceGroups/imageGroups/providers/Microsoft.Storage/storageAccounts/mystorageaccount' must be a managed disk or snapshot.
Target: galleryImageVersion.properties.storageProfile.osDiskImage.source.id

```

Note that argument values have been redacted to the values from the example. The error shows the value of os-vhd-storage-account, stating it should be managed image or snapshot, while it should be the id for a storage account.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Install azure cli 2.42.0
- Have a vhd stored in your storage account
- Create an image gallery and definition
- `az sig image-version create --gallery-image-definition {} --gallery-image-version {} --gallery-name {} --resource-group {} --os-vhd-storage-account {} --os-vhd-uri {}`

## Expected Behavior
A new image version is created in the Image Definition.

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.42.0

Extensions:
azure-devops 0.25.0
monitor-control-service 0.3.0
ssh 1.1.2

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context
Running this command from an Azure DevOps pipeline. Using a Self-Hosted agent, build with the tools described here: https://github.com/actions/runner-images. 
Reproduced the error on my own VM. Upgrading to az 2.42.0 introduced this error.

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by baidarka** [comment]
Currently our image build process cannot be properly completed. ("AzureCLI 2.42 error '... must be a managed disk or snapshot'")
Can you please provide a status regarding this issue?
  - Do you suggest a workaround? Should we approach this differently?
  - Should we wait for a fix? (timeframe?)

**Comment by yanzhudd** [comment]
Hi @baidarka,

> Do you suggest a workaround? Should we approach this differently?

We could provide you with an edge package first, or you could choose to downgrade the CLI version first.
> Should we wait for a fix? (timeframe?)

We would fix this issue in this sprint (release date is 2022-12-06).

**Comment by baidarka** [comment]
Dear @yanzhudd, 

Thank you for your reply! It is very nice to read that this issue is scheduled for fix.

> We could provide you with an edge package first, or you could choose to downgrade the CLI version first.
> We would fix this issue in this sprint (release date is 2022-12-06).
We'll downgrade the CLI version for now (actually: we'll build on an older build image, since we cannot version-pin individual packages :)
