### ISSUE TITLE
Link to CLI doc needs to be updated

### ISSUE THREAD

**Issue by halkazwini** [Azure/azure-cli#24630]
Hi Team,

The link to the reference doc for **az network vnet peering create** is not updated:

![image](https://user-images.githubusercontent.com/85655443/201425878-249462e1-8f9e-4cb0-a6ef-a531f6886668.png)

https://learn.microsoft.com/en-us/cli/azure/network/vnet/peering#az-network-vnet-peering-create

Regards,
Hussein

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6754f86-e867-36a8-ad76-26ef330f5c28
* Version Independent ID: 2542c6dd-cece-3fce-8738-02c43f6496f4
* Content: [az network vnet peering](https://learn.microsoft.com/en-us/cli/azure/network/vnet/peering?view=azure-cli-latest#az-network-vnet-peering-sync)
* Content Source: [latest/docs-ref-autogen/network/vnet/peering.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/vnet/peering.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@necusjz for awareness
