### ISSUE TITLE
The argument name in the deprecation warning message should use the format "--foo-bar" instead of "foo_bar"

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-cli#24647]
### Related command

```
$ az aks create -g binxi1114 -n binxi111401 --enable-pod-security-policy -c 1
Argument 'enable_pod_security_policy' has been deprecated and will be removed in a future release.
Argument '--enable-pod-security-policy' is in preview and under development.
```

### Extension name (the extension in question)

It's not an issue to a specific extension. It is a common issue.

### Description of issue (in as much detail as possible)

I'm working a [PR](https://github.com/Azure/azure-cli-extensions/pull/5542) to deprecate the argument '--enable-pod-security-policy', and I get the message like below. The warning message should be "Argument '--enable-pod-security-policy' has been deprecated and will be removed in a future release.". `Argument 'enable_pod_security_policy'` is not good.

```
$ az aks create -g binxi1114 -n binxi111401 --enable-pod-security-policy -c 1
Argument 'enable_pod_security_policy' has been deprecated and will be removed in a future release.
Argument '--enable-pod-security-policy' is in preview and under development.
```

-----

**Comment by jiasli** [comment]
It is the designed behavior of knack to show `argument_dest` in the warning message if deprecation target is not specified:

https://github.com/microsoft/knack/blob/cd590312b9b4ea1402d7a0a76814f6ca4da7fab8/knack/arguments.py#L221-L222

```py
        if deprecate_info:
            deprecate_info.target = deprecate_info.target or argument_dest
```

To override the `enable_pod_security_policy` in the warning message, please specify 

```py
deprecate_info=c.deprecate(target='--enable-pod-security-policy')
```

Here is an example from `resource` command module:

https://github.com/Azure/azure-cli/blob/5b91300bb788d59683461b4570854c41dd8c3659/src/azure-cli/azure/cli/command_modules/resource/_params.py#L390-L391

**Comment by bingosummer** [comment]
`deprecate_info=c.deprecate(target='--enable-pod-security-policy')` works.
