### ISSUE TITLE
az postgres flexible-server slow (AZ CLI) took longer than psql

### ISSUE THREAD

**Issue by shardulb2709** [Azure/azure-cli#24654]
I tested myself with the simple "select * from test" both with psql and also with az cli for around 1000 records in the table and I found AZ cli took longer than psql-

Please find the below results-
 
From Az cli-
cli.__main__: Command ran in 1.388 seconds 

  From psql-
Execution Time: 0.312 ms 

Could someone explain why AZ CLI is slower compared to psql?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by nachoalonsoportillo** [comment]
@yonzhan Please proceed to close this one. Thanks!
