### ISSUE TITLE
New performance plus property for Azure Disks

### ISSUE THREAD

**Issue by albecker1** [Azure/azure-cli#24662]
Related command
az disk create --performance-plus  {false, true}

Resource Provider
Microsoft.Compute/disks

Description of Feature or Work Requested
We are introducing a new disk storage SKU Premiumv2_LRS besides the current available SKUs: Standard_LRS, Premium_LRS, StandardSSD_LRS, UltraSSD_LRS, Premium_ZRS, StandardSSD_ZRS. We need to ensure that CLI uses the Compute's API version 2022-03-01 and sku and storage-sku parameters accepted by az vm, az disk, az vmss, az vmss disk commands must accept the new SKU Premiumv2_LRS.

Minimum API Version Required
2022-03-02

Swagger PR link
https://github.com/Azure/azure-rest-api-specs/pull/19958

Request Example
No response

Target Date
2022-12-12

Additional context
No response

**Comment by yonzhan** [comment]
Compute feature

**Comment by albecker1** [comment]
Hey has this been implemented? How can I test this to verify?

**Comment by zhoxing-ms** [comment]
@albecker1 The PR of this feature had been merged, and it will be released in the latest version of CLI *(2.44.0)* on January 10
