### ISSUE TITLE
[BUG]  "az storage fs file list" not working in private endpoint

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-cli#24666]
customer reported issue

> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62
2.42.0

**Related command**
az storage fs file list -f container1 --account-name testaccountXXX --account-key  XXXXX

az storage blob list --account-name testaccountXXX --container-name container1 --account-key XXXX

**Describe the bug**
I have storage account testaccountXXX and a VM that has a private endpoint to storage account

**To Reproduce**
az storage blob list --account-name testaccountXXX --container-name container1 --account-key XXXX

can get the list 

but "az storage fs file list -f" has network error

**Expected behavior**
az storage fs file list -f should return the blob list

**Comment by yangchengs** [comment]
![image](https://user-images.githubusercontent.com/71274085/202144326-74fd075b-b832-4886-9d26-1a30494198ef.png)

**Comment by yangchengs** [comment]
![image](https://user-images.githubusercontent.com/71274085/202144525-af68cd19-d80b-4759-93f8-5acc7c3fd932.png)

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by yangchengs** [comment]
az storage fs file list needs dfs endpoint.
