### ISSUE TITLE
Az CLI install from command line is not updating %PATH% on Azure Stack HCI 22H2

### ISSUE THREAD

**Issue by dkirby-ms** [Azure/azure-cli#24686]
![image](https://user-images.githubusercontent.com/32211549/202549768-9d8f4590-45c6-41c3-ae2d-04a8d0657af2.png)

**To Reproduce**
1) Install Az CLI from PowerShell command using msiexec on Azure Stack HCI 22H2
2) try to run Az CLI command from user folder
3) Note that Az CLI is installed, but PATH has not been updated

**Expected behavior**
This just started happening in the past couple days. Previously, installing az cli on Stack HCI OS worked fine and the PATH was updated properly.

**Environment summary**
Installed Az CLI using msiexec command line install option onto Azure Stack HCI 22H2

This breaks a lot of automation in projects like the Azure Arc Jumpstart where we rely on Az Cli commands for much of the scripts.

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by dkirby-ms** [comment]
This issue is actually on my side. sorry for the churn

**Comment by dkirby-ms** [comment]
I'm actually still seeing a lot of this happening with multiple install attempts. Its possible I am doing something wrong but I am not sure what it would be.

**Comment by dkirby-ms** [comment]
I finally figured this out. The reason I am missing it from the path is because the Install-Moc command from

**Comment by rvdouderaa** [comment]
We did a installation of 2 Azure Stack HCI clusters, and are seeing the same issue. Made a Microsoft Call and the Engineer was able to reproduce this in his lab. Seems to be a real issue.

**Comment by rvdouderaa** [comment]
@dkirby-ms Should I create a new ticket or can you reopen this one?
