### ISSUE TITLE
az network vnet show (required parameters)

### ISSUE THREAD

**Issue by halkazwini** [Azure/azure-cli#24682]
Hi Team,

I think the command az-network-vnet-show needs two required parameters:

- --name -n
- --resource-group -g

![image](https://user-images.githubusercontent.com/85655443/202514379-d70edcb7-dced-4d40-bef9-cd7b428a1e14.png)

https://learn.microsoft.com/en-us/cli/azure/network/vnet?view=azure-cli-latest#az-network-vnet-show

Regards,
Hussein

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc99d572-abdb-ab6b-7a9a-c6951a1c1466
* Version Independent ID: 0a50e966-cbc8-8960-c01f-e117cac842d4
* Content: [az network vnet](https://learn.microsoft.com/en-us/cli/azure/network/vnet?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/network/vnet.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/vnet.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
@halkazwini `-n` and `-g` are optional when `--ids` is explicitly specified.
