### ISSUE TITLE
Azure CLI | Minimum value of Max throughput for Cosmos DB container is 4000

### ISSUE THREAD

**Issue by andigwandi** [Azure/azure-cli#24681]
With Terraform I am able to set Max Throughput for a container to <4000 (which is mentioned in the documentation). Is there a way to use CLI to set max throughput < 4000 after the container is created?

![image](https://user-images.githubusercontent.com/11092753/202477422-7b594d82-6072-4854-84e9-c85f167335d6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8118fcf7-5433-71bc-a345-6ac30584660d
* Version Independent ID: 03183f36-fa95-c56b-254a-54663639e3b2
* Content: [az cosmosdb sql container throughput](https://learn.microsoft.com/en-us/cli/azure/cosmosdb/sql/container/throughput?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/cosmosdb/sql/container/throughput.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/cosmosdb/sql/container/throughput.yml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@andigwandi Can you please refer to the below document to change the throughput properties on a container via the Azure CLI.

[Throughput (RU/s) operations with Azure CLI for a database or container for Azure Cosmos DB for NoSQL](https://learn.microsoft.com/en-au/azure/cosmos-db/scripts/cli/nosql/throughput)

**Comment by SaurabhSharma-MSFT** [comment]
@andigwandi Please let me know if you have any questions.

**Comment by SaurabhSharma-MSFT** [comment]
@andigwandi We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
