### ISSUE TITLE
Auto upgrade kubelogin

### ISSUE THREAD

**Issue by AntoineAtLeocare** [Azure/azure-cli#24693]
When installing kubelogin with `az aks install-cli`, kubelogin is never automatically upgraded thereafter. Is it possible to automatically upgrade kubelogin when, for example, upgrading az-cli? Or maybe it is possible to check if there is a new version every time we use kubelogin and ask the user to update if so?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@AntoineAtLeocare Thanks for the feedback! Since this is specific to AKS, I will have to investigate if it can upgraded when running `az upgrade`.

But if you were to re-run the `az aks install-cli` command, both commands should be updated to their latest.

**Comment by AntoineAtLeocare** [comment]
Thank you @PramodValavala-MSFT! My `az` is installed with my package manager (`brew` on MacOS) so I usually update my packages with brew. I think sysadmins are used to using their package manager to upgrade their packages. ;)

**Comment by PramodValavala-MSFT** [comment]
@AntoineAtLeocare Well, in that case you could just [install `kubelogin` using `brew`](https://github.com/Azure/kubelogin#setup-homebrew) right? And same goes for `kubectl`.

The `aks install-cli` is more of a helper for a quick install like on Cloud Shell but I prefer maintaining my own packages too. 😄

**Comment by AntoineAtLeocare** [comment]
You're right. I followed the microsoft documentation which says to use `az aks install-cli` (<https://learn.microsoft.com/en-us/azure/aks/managed-aad#prerequisites>). Maybe the documentation should advise using a package manager. You can close this issue if you think it's better. Thank you @PramodValavala-MSFT.

**Comment by PramodValavala-MSFT** [comment]
@AntoineAtLeocare Glad I could help! You are right about the docs mentioning that but if someone meets the prerequisites, I doubt they would install it a second time.

Will close this for now considering the nature of this command, unless more folks feel like this should be enhanced. Thanks for again for the feedback!
