### ISSUE TITLE
Seems bug in `az network nic ip-config inbound-nat-rule add`

### ISSUE THREAD

**Issue by goodwill** [Azure/azure-cli#2469]
As title, I tried to do that with following command:

```
az network nic ip-config inbound-nat-rule add --inbound-nat-rule /subscriptions/<subscription_id>/resourceGroups/<rg_name>/providers/Microsoft.Network/loadBalancers/<lb_name>/inboundNatRules/<nat_rule_name> --ip-config-name default-ip-config --nic-name <nic_name> -g <resource_group>
```

then I got the following:

```
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/goodwill/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/goodwill/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/Users/goodwill/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in _execute_command
    raise ex
TypeError: 'NoneType' object is not iterable
```

Anyone has idea whats going wrong?

I believe this is a bug in new azure cli 2.0. The exact same command works in the old Xplat-CLI:
`azure network nic ip-config inbound-nat-rule create -g <resource_group> -l <lb_name> -r <nat_rule_name> -c <nic_name>`

I also posted this on stackoverflow:

http://stackoverflow.com/questions/42756166/azure-cli-2-0-how-to-add-inbound-nat-rule

**Comment by tjprescott** [comment]
Hi @goodwill, you are correct, this is a bug; however, this has already been fixed in PR #2345. 

Please see #2336 for a workaround until the next release. The syntax will be nearly identical for your situation.
