### ISSUE TITLE
Getting instance view of a VM and a VMSS VM are different (No '--expand' parameter for 'az vm scaleset-vm show')

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#247]
The result has an instanceView but it can't be expanded as there is no --expand parameter for scaleset-vm show.

Command
    az vm scaleset-vm show

Arguments
    --instance-id       [Required]: The instance id of the virtual machine.
    --name -n           [Required]: The name of the virtual machine scale set.
    --resource-group -g [Required]: The name of the resource group
##### Example from az vm show:

Command
    az vm show

Arguments
    --name -n           [Required]: The name of the virtual machine.
    --resource-group -g [Required]: The name of the resource group
    --expand                      : The expand expression to apply on the operation.

**Comment by yugangw-msft** [comment]
I think we are fine now.
VMSS doesn't expose the `expand` parameter on retrieving an instance. And later I have exposed strong typed command of "get-instance-view" for both standalone vm and a vm instance in a scale set.
