### ISSUE TITLE
az role assignment create --assignee "${PRINCIPAL_ID}" --role 'Contributor' --scope "{RESOURCE_GROUP_ID}"

### ISSUE THREAD

**Issue by djohn99** [Azure/azure-cli#24701]
## Describe the bug

**Command Name**
`az role assignment create`

**Errors:**
```
'RESOURCE_GROUP_ID'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
lib/python3/dist-packages/six.py, ln 703, in reraise
    raise value
...
python3/dist-packages/msrest/service_client.py, ln 168, in get
    request = self._request('GET', url, params, headers, content, form_content)
python3/dist-packages/msrest/service_client.py, ln 108, in _request
    request = ClientRequest(method, self.format_url(url))
python3/dist-packages/msrest/service_client.py, ln 151, in format_url
    url = url.format(**kwargs)
KeyError: 'RESOURCE_GROUP_ID'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az role assignment create --assignee {} --role {} --scope {}`

## Environment Summary
```
Linux-5.15.0-1023-azure-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Could you check https://github.com/Azure/azure-cli/issues/23160#issuecomment-1179901988 and see if the issue can be solved? If not, could you share the full command with its argument values?

**Comment by djohn99** [comment]
thanks for your response.
this was how i was calling the command before i make i change to it and it work for me
export PRINCIPAL_ID=`az identity show -g ${RESOURCE_GROUP} -n ${INFRA_ID}-identity --query principalId --out tsv`

export RESOURCE_GROUP_ID=`az group show -g ${RESOURCE_GROUP} --query id --out tsv`

az role assignment create --assignee "${PRINCIPAL_ID}" --role 'Contributor' --scope "${RESOURCE_GROUP_ID}"

this work for me
export PRINCIPAL_ID=$(az identity show -g ${RESOURCE_GROUP} -n ${INFRA_ID}-identity --query principalId --out tsv)
export RESOURCE_GROUP_ID=$(az group show -g ${RESOURCE_GROUP} --query id --out tsv)
az role assignment create --assignee "${PRINCIPAL_ID}" --role 'Contributor' --scope "${RESOURCE_GROUP_ID}"

**Comment by jiasli** [comment]
@djohn99, Bash will replace `"${RESOURCE_GROUP_ID}"` even though it is not set:

I guess you were using single quotes around `${RESOURCE_GROUP_ID}`:

```
user2@DESKTOP-A79F1:~$ echo ${RESOURCE_GROUP_ID}

user2@DESKTOP-A79F1:~$ echo '${RESOURCE_GROUP_ID}'
${RESOURCE_GROUP_ID}
```
