### ISSUE TITLE
`az disk create` commands fails to create disk using `gallery-image-reference` in another subscription

### ISSUE THREAD

**Issue by angop95** [Azure/azure-cli#24704]
## Describe the bug

**Command Name**
`az disk create`

**Errors:**
```
(ResourceGroupNotFound) Resource group 'ABCD' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'ABCD' could not be found.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

-  Fetch the `id` of the image in Compute Image Gallery using `az sig image-version show --resource-group {} --gallery-name {} --gallery-image-version {} --gallery-image-definition {}` in `Subscription 1`
- Switch to `Subscription 2`
- `az disk create --resource-group {} --location {} --name {} --gallery-image-reference {}`

## Expected Behavior
-  The same sequence of operation worked without issues in az cli version 2.40.0
## Environment Summary
```
Windows-10-10.0.19045-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.42.0

Extensions:
aks-preview 0.5.102
azure-devops 0.21.0
storage-preview 0.8.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness
