### ISSUE TITLE
az vm extension image list issue

### ISSUE THREAD

**Issue by jinmiaoms** [Azure/azure-cli#2470]
This is run against Azure China.

C:\Users\jinmiao>az vm extension image list --query "[].publisher" -o tsv
The resource type 'locations/publishers' could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'. The supported api-versions are '2015-05-01-preview,2015-06-15,2016-03-30'.

Same for: az vm extension image list -l chinaeast -p TrendMicro.DeepSecurity

**Comment by yugangw-msft** [comment]
Unfortunately, it is a known issue that sovereign cloud envs have not had their manifest updated to support newer api-version.

**Comment by mayurid** [comment]
@jinmiaoms : We are working on lighting up the sovereign clouds in the az cli to work seamlessly.
We will keep you posted once that is fully lit up.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
