### ISSUE TITLE
az synapse workspace-package upload command results in TypeError: LibraryOperations.append() missing 1 required positional argument: 'content'

### ISSUE THREAD

**Issue by tschouunas** [Azure/azure-cli#24718]
**Related command**
az synapse workspace-package upload

**Describe the bug**
az synape workspace upload command does not produce the same result as when few days ago. It no longer uploads the provided packages to the Azure Synapse Workspace. Instead it fails with the below traceback.

![image](https://user-images.githubusercontent.com/33125059/203494263-dac3a0fd-2af5-48ee-bee1-344928d68a39.png)

**To Reproduce**
Azure Synapse environment with a sparkPool set-up is required. To reproduce in a local environment. Make sure to be permitted to connect to Synapse from local. Have the package in a local dir and provide the path alongside the workspace name to az synapse command.

Example:
az synapse workspace-package upload --file 'file.whl' --workspace-name 'subscription'

**Expected behavior**
To succesfully upload the workspace package to the Synapse workspace.

**Environment summary**
ubuntu version               Ubuntu 20.04.5 LTS
azure-cli                          2.42.0

core                                 2.42.0
telemetry                         1.0.8

Dependencies:
msal                                 1.20.0
azure-mgmt-resource      21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/AzDevOps_azpcontainer/.azure/cliextensions'

Python (Linux) 3.10.8 (main, Oct 28 2022, 04:19:40) [GCC 9.4.0]

**Additional context**
Probably related issue then with upload batch command (https://github.com/Azure/azure-cli/issues/24700)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by devlace** [comment]
I am facing similar issue. This is breaking release pipelines.

**Comment by CribberSix** [comment]
I think it is a bug introduced in `azure-cli=2.42.0` or `core=2.42.0`, I just checked our logs from before and it worked with `azure-cli=2.41.0` and `core=2.41.0`. All of our deployment pipelines crash since yesterday due to this error .

**Comment by RakeshMohanMSFT** [comment]
@tschouunas Thank you for reaching out, we are looking into it.

**Comment by CribberSix** [comment]
For anyone else looking, there is a work-around for Azure DevOps pipeline tasks to revert to an older version until the issue is being fixed: https://stackoverflow.com/questions/72556823/how-to-specify-version-for-az-cli-in-azure-pipelines-in-yaml

**Comment by CribberSix** [comment]
Any news when an update will be available?

**Comment by gonzalez40** [comment]
Any news when an update will be available?
