### ISSUE TITLE
az afd rule documentation update

### ISSUE THREAD

**Issue by anton-dealmeida** [Azure/azure-cli#24711]
Hi there,

Could we update the documentation around this CLI to perhaps just hint at the fact that certain parameters like `--match-values` take a space separated and not comma separated list?

I'll gladly make a PR to update it if I knew where.
This is related to this issue: https://github.com/Azure/azure-cli/issues/21386
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b80260f-cee3-ad69-4243-08755342325f
* Version Independent ID: d4e72781-eadc-1f91-46cc-f8f40bb0d7ae
* Content: [az afd rule](https://learn.microsoft.com/en-us/cli/azure/afd/rule?view=azure-cli-latest#az-afd-rule-create)
* Content Source: [latest/docs-ref-autogen/afd/rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/afd/rule.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by anton-dealmeida** [comment]
I create a pull request for this:
https://github.com/MicrosoftDocs/azure-docs-cli/pull/3400

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@anton-dealmeida Thank you for reaching out, we are looking into it.
