### ISSUE TITLE
Bastion RDP with native client

### ISSUE THREAD

**Issue by Jian-Mai** [Azure/azure-cli#24736]
## Describe the bug

**Command Name**
`az network bastion rdp`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.9/ctypes/__init__.py)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/custom.py", line 8352, in rdp_bastion_host
    from ._process_helper import launch_and_wait
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/network/_process_helper.py", line 9, in <module>
    from ctypes import WinDLL, c_int, c_size_t, Structure, WinError, sizeof, pointer
ImportError: cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.9/ctypes/__init__.py)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network bastion rdp --name {} --resource-group {} --target-resource-id {}`

## Environment Summary
```
Linux-5.4.0-1094-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.42.0

Extensions:
ai-examples 0.2.5
ml 2.10.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by MichaelP-SCALES** [comment]
Hello,

I have the same problem running from Windows 11 22H2 (22621.819) using Windows Terminal (1.15.2875.0) Azure Cloud Shell CLI.

AZ version
"azure-cli": "2.43.0",
  "azure-cli-core": "2.43.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "ai-examples": "0.2.5",
    "ml": "2.11.0",
    "ssh": "1.1.3"

Did a similar setup on a Windows 10 computer with Azure CLI (2.43.0) and it worked. 

Guessing it is because the Windows Terminal Azure Cloud Shell CLI is running in the cloud and is then not able to start the local Remote Desktop client.

What is the correct way to use Bastion RDP with native client in Windows 11? Is it to install Azure CLI (2.43.0) locally, instead of using Windows Terminal with Azure Cloud Shell (AZ version 2.43.0)?

**Comment by navba-MSFT** [comment]
@Jian-Mai Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please confirm if you are running this from a cloudshell ? If Yes, it wont be able to open the RDP on your local machine. For this reason, _we recommend using **powershell** with az cli (on Windows machine)._

Also, note that RDP command works best on Windows, for other OS’ (like Linux or Mac) you can do the [tunnel command](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-tunnel) and then use the client of your choice.

>Connect to a VM using the [az network bastion tunnel command](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-tunnel). This lets you do the following:

>-  Use native clients on non-Windows local computers (example: a Linux PC).
>-  Use the native client of your choice. (This includes the Windows native client.)
>-  Connect using SSH or RDP.
>-  Set up concurrent VM sessions with Bastion.
>-  [Upload files](https://docs.microsoft.com/en-us/azure/bastion/vm-upload-download-native#tunnel-command) to your target VM from your local computer. File download from the target VM to the local client is currently not supported for this command.

>Currently, this feature has the following limitation:
Signing in using an SSH private key stored in Azure Key Vault isn’t supported with this feature. Before signing in to your Linux VM using an SSH key pair, download your private key to a file on your local machine.

Hope this helps.

**Comment by navba-MSFT** [comment]
@Jian-Mai Please update your bastion extension by running the below command and that should fix this.

**> az extension update -n bastion**

Hope this helps.

**Comment by jiasli** [comment]
Duplicate of #23143
