### ISSUE TITLE
"az vmware cluster list" return an empty list

### ISSUE THREAD

**Issue by labiol** [Azure/azure-cli#24737]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az vmware cluster list --private-cloud XX --resource-group XX

**Describe the bug**
Return empty list. Private cloud has at least one cluster populated by default 

**To Reproduce**

**Expected behavior**
Lists of all clusters (that are visible in VMware vCenter)

**Environment summary**
macos, zsh (zsh 5.8.1 (x86_64-apple-darwin21.0)), 
az --version
azure-cli                         2.42.0

core                              2.42.0
telemetry                          1.0.8

Extensions:
connectedmachine                   0.5.1
scheduled-query                    0.5.1
vmware                             4.1.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/usr/local/Cellar/azure-cli/2.42.0/libexec/bin/python'

Python (Darwin) 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@labiol Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please run the same command with `--debug` output and share the detailed output here ? Awaiting your reply. 

PS: You can remove the sensitive information from the output before sharing it here.

**Comment by navba-MSFT** [comment]
@labiol I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@labiol The action is currently pending on you share the `--debug` traces.  Please feel free to reopen this thread, once you are ready to resume troubleshooting on this. We would be happy to help.
