### ISSUE TITLE
Documentation contains outdated argument

### ISSUE THREAD

**Issue by HansZimmer5000** [Azure/azure-cli#24749]
**Related command**
Documentation in this repository. 

**Describe the bug**
`doc/authoring_command_modules/README.md` lists outdated argument "--module".

Argument "--module" is not existent, as it can be seen via `azdev style --help`. 
Further proof in the [azdev history](https://github.com/Azure/azure-cli-dev-tools/blob/eee6d32a6653d639d01a23481063675f175e8b41/HISTORY.rst#005): ("[...] to allow modules as a positional argument, consistent with other azdev commands. [...]")

**To Reproduce**
`azdev style --modules <someinput>`

**Expected behavior**
Setting of modules, that is now done via positional argument (as mentioned above).
For example: `azdev style CLI`

**Environment summary**
Executed `azdev` within the python3.9 venv described in the Azure CLI dev setup.

```
> azdev --version
0.1.40

Python (Darwin) 3.9.15 (main, Oct 11 2022, 22:27:25) 
[Clang 14.0.0 (clang-1400.0.29.102)]

Python location '/Users/<user>/<path-to-repo>/azure-cli/env/bin/python3.9'
```

**Additional context**
Will provide a PR.

**Comment by HansZimmer5000** [comment]
See PR #24750

**Comment by yonzhan** [comment]
@kairu-ms for awareness
