### ISSUE TITLE
[az disk] Portal v/s CLI, Ability to change public-network-access without changing network-access-policy

### ISSUE THREAD

**Issue by Miraj50** [Azure/azure-cli#24743]
Team,
I have noticed a difference in the ability to set networking configuration for Azure Managed disks from Portal and CLI.

In Portal, we are presented with three options:
![image](https://user-images.githubusercontent.com/23695844/204006501-2f73e831-323b-4252-9e1e-a2465be8b31b.png)

Here is what, selecting each leads to for the two parameters:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

Configuration | PublicNetworkAccess | NetworkAccessPolicy
-- | -- | --
Enable public   access from all networks | Enabled | AllowAll
Disable public   access and enable private access | Enabled | AllowPrivate
Disable public and   private access | Disabled | DenyAll

</div>

</body>
</html>

On CLI though, what I have noticed is that, we can control the two parameters individually. So, I can create a disk with public access and then edit it through CLI to have `PublicNetworkAccess = Disabled` & `NetworkAccessPolicy = AllowAll`.

Can you please tell me if this is an intended behaviour and if yes, what would be the meaning of having this configuration: `PublicNetworkAccess = Disabled` & `NetworkAccessPolicy = AllowAll` for a managed disk?
 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 74997eeb-6fa3-4318-79da-8cf4dce59cfe
* Version Independent ID: c8cea09f-196e-7269-dc42-b6b8933dbaf1
* Content: [az disk](https://learn.microsoft.com/en-us/cli/azure/disk?view=azure-cli-latest#az-disk-update)
* Content Source: [latest/docs-ref-autogen/disk.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/disk.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@Miraj50 I can reproduce this behavior. At present, the REST service [disks/create-or-update](https://learn.microsoft.com/en-us/rest/api/compute/disks/create-or-update?tabs=HTTP)  supports independent updates for `networkAccessPolicy` and `publicNetworkAccess` properties without binding restriction logic.
In fact, I have seen similar behavior on other RPs. In most cases, this means that `NetworkAccessPolicy` will not take effect when `PublicNetworkAccess` is `Disabled`. But if `NetworkAccessPolicy` is `Enabled` again, the `NetworkAccessPolicy = AllowAll` will take effect normally, so users do not need to set the `NetworkAccessPolicy` repeatedly.

**Comment by Miraj50** [comment]
@zhoxing-ms Thank you for your response. 
In your last line, I believe you meant .. "But if ~`NetworkAccessPolicy`~ `PublicNetworkAccess` is `Enabled` again, the `NetworkAccessPolicy = AllowAll` will take effect normally, so users do not need to set the `NetworkAccessPolicy` repeatedly". Right?

**Comment by zhoxing-ms** [comment]
@Miraj50 Yes, exactly

**Comment by adi-garg** [comment]
Hello,
Shouldn't 2nd line read Disabled for PublicNetwork Access?

![Disk Nw Access Options in json](https://github.com/Azure/azure-cli/assets/73249037/bac4d8e0-0997-4f94-8220-ebdbd6e95400)

Reference [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.publicnetworkaccess?view=azure-dotnet#definition).

Regards,
Aditya Garg

**Comment by zhoxing-ms** [comment]
@Miraj50 Could you please answer the question from adi-garg above?

**Comment by Miraj50** [comment]
@adi-garg I have mentioned the current behavior at the time. Are you saying that you have noticed something else?

**Comment by adi-garg** [comment]
Hello and Greetings,The query was regarding the table's 2nd column which was been corrected in red.

**Comment by Miraj50** [comment]
The CLI/DiskRP team can better convey if the above said behaviour was something they intended.
