### ISSUE TITLE
Action "AnomalyScoring" for an override on a managed rule supported in Azure Portal but not CLI

### ISSUE THREAD

**Issue by vhhughes** [Azure/azure-cli#24758]
## Describe the bug

**Command Name**
`az network front-door waf-policy managed-rules override add`

**Errors:**
```
az network front-door waf-policy managed-rules override add: 'AnomalyScoring' is not a valid value for '--action'. Allowed values: Allow, Block, Log, Redirect.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Use action of "AnomalyScoring" for az network front-door waf-policy managed-rules override add
- `az network front-door waf-policy managed-rules override add --policy-name {} --resource-group {} --type {} --rule-group-id {} --rule-id {} --action AnomalyScoring --disabled {}`

## Expected Behavior

Should set the action for a rule to AnomalyScoring.

As a side note, if I set the action in the Azure Portal, the Azure CLI will correctly show "action": "AnomalyScoring" when I do a az network front-door waf-policy managed-rules override **list**. The CLI just does not let me set this value. (unlike the Azure Portal)

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.41.0

Extensions:
application-insights 0.1.16
cosmosdb-preview 0.19.0
datafactory 0.6.0
front-door 1.0.16

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@vhhughes Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
The enum values `Allow, Block, Log, Redirect` for `--action ` parameter seem to be taken from the auto-generated code here:

https://github.com/Azure/azure-cli-extensions/blob/main/src/front-door/azext_front_door/vendored_sdks/models/_front_door_management_client_enums.py#L29

We are looking into this further. We will keep you updated.
