### ISSUE TITLE
Creating role assignment must require all assignee, role definition and scope to be specified explicitly

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#24753]
**Related command**
`az ad sp create-for-rbac`
`az role assignment create`
Other commands related to role assignment creation, such as `az vm identity assign`.

## Context

`az ad sp create-for-rbac` stopped creating role assignment for newly created service principal if `--role` (#19805) and `--scopes` (#21323) are not specified.

The current behavior of `az role assignment create` is to default `--scope` to the current subscription. If `--scope` is not specified and

- if `--resource-group` is not specified, the scope is set to the current subscription
- if `--resource-group` is specified, the scope is set to the resource group under the current subscription

**This behavior is against the Principle of Least Privilege and should be modified to align with `az ad sp create-for-rbac`.**

## Proposal

For _any_ Azure CLI command, **creating role assignment must require all assignee, role definition and scope to be specified explicitly. No default value should be used.**

For `az role assignment create`, this will be a breaking change. Similar to what we previously did for `az ad sp create-for-rbac`'s `--role` (#19805) and `--scopes` (#21323), there are 2 steps:

1. Show a warning to instruct the user to always explicitly specify scope.
2. Make scope mandatory.

## Discussion

One open discussion is **whether we should drop `--resource-group` and `--subscription` from `az role assignment create`**.

`--scope` is the all-in-one argument covering subscription level, resource group level and resource level.

Subscription level:

- `--scope /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590`
- `--subscription 0b1f6471-1bf0-4dda-aec3-cb9272f09590`

Resource group level:

- `--scope /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/mygroup`
- `--subscription 0b1f6471-1bf0-4dda-aec3-cb9272f09590 --resource-group mygroup`

Resource level:

- `--scope /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/ZYTEST/providers/Microsoft.Compute/virtualMachines/myvm`
- Not supported by individual arguments

Using individual argument `--resource-group` and `--subscription` has several disadvantages:

- It encourages over-privileged assignment on subscription or resource group level as fine-grained resource-level assignment is not supported.
- It encourages different calling patterns for the same functionality, introducing complexity and inconsistency within `az role assignment create` and with `az ad sp create-for-rbac` (only has `--scopes`), `az vm identity assign` (which only has `--scopes`; `--resource-group` and `--subscription` are `Resource Id Arguments` for the VM resource, not scope).
- Not consistent with [Role Assignments - Create](https://learn.microsoft.com/en-us/rest/api/authorization/role-assignments/create?tabs=HTTP) REST API which uses `scope` as URI parameter.

**Comment by yonzhan** [comment]
@jiasli we can sync up with PM team about this.

**Comment by jiasli** [comment]
This is the code for computing final scope from `--scope`, `--subscription` and `--resource-group`:

https://github.com/Azure/azure-cli/blob/e14c60fa5e2a755a2d545294b815a4b1c86bb7a0/src/azure-cli/azure/cli/command_modules/role/custom.py#L583-L596

**Comment by jiasli** [comment]
It may not be necessary to drop `--subscription` as **it can still serve the purpose of temporarily switching the auth context**.

Notice the account shown by `az account show` contains not only subscription ID `id`, but also `tenantId` and `user.name` that are used for authentication:

```
> az account show
{
  "environmentName": "AzureCloud",
  "homeTenantId": "xxx",
  "id": "xxx",
  "isDefault": true,
  "managedByTenants": [
    {
      "tenantId": "xxx"
    }
  ],
  "name": "AzureSDKTest",
  "state": "Enabled",
  "tenantId": "xxx",
  "user": {
    "name": "xxx@microsoft.com",
    "type": "user"
  }
}
```

Azure CLI is smart enough to extract subscription ID from `--scope`:

https://github.com/Azure/azure-cli/blob/710c821b2920df504ae037e7b05763193b051a30/src/azure-cli/azure/cli/command_modules/role/_client_factory.py#L11-L16

However, if `--scope` doesn't contain subscription information (in the form of `/subscriptions/xxx`), such as the tenant-level scope `/`, `get_mgmt_service_client` will receive `subscription_id` as `None`. Then, the auth context specified by `--subscription` or the default subscription will be used:

https://github.com/Azure/azure-cli/blob/21266e02457263420b62fba1c529f69e28852414/src/azure-cli-core/azure/cli/core/commands/client_factory.py#L69-L70

I admit this is counterintuitive as the tenant-level scope `/` is not bound to any subscription. **The `--subscription` argument is merely used to temporarily switch to the auth context bound to that subscription.**

If we drop `--subscription`, for tenant-level `--scope`, there will be no way to temporarily switch the auth context. We must run `az account set`. This is exactly the case for `az ad` which totally ignores `--subscription` (#6516):

https://github.com/Azure/azure-cli/blob/e8efb791ea2f0ba5e4f172b26f75725fd8aa8079/src/azure-cli/azure/cli/command_modules/role/_params.py#L26

Even though it is reasonable to not support `--subscription`, as `az ad` commands are tenant-level commands and are not bound to a subscription, it becomes impossible to switch auth context temporarily with `--subscription`, which is inconvenient.
