### ISSUE TITLE
Az group delete --force-deletion-types fails with api-version mismatch

### ISSUE THREAD

**Issue by MinKPark** [Azure/azure-cli#24766]
## Describe the bug
Az group delete --force-deletion-types fails with api-version mismatch. 

**Command Name**
`az group delete`

**Errors:**
```
(ResourceGroupDeletionTimeout) Deletion of resource group 'ResourceGroupName' did not finish within the allowed time as resources with identifiers 'Microsoft.Compute/virtualMachineScaleSets/VMSSName' could not be deleted. The provisioning state of the resource group will be rolled back. The tracking Id is '51aab640-2cb2-4cd2-a505-43b71602644b'. Please check audit logs for more details.
Code: ResourceGroupDeletionTimeout
Message: Deletion of resource group 'ResourceGroupName' did not finish within the allowed time as resources with identifiers 'Microsoft.Compute/virtualMachineScaleSets/VMSSName' could not be deleted. The provisioning state of the resource group will be rolled back. The tracking Id is '51aab640-2cb2-4cd2-a505-43b71602644b'. Please check audit logs for more details.
Exception Details:      (None) {"error":{"code":"BadRequest","message":"This request can be made with api-version '2022-03-01' or newer."}}
        Code: None
        Message: {"error":{"code":"BadRequest","message":"This request can be made with api-version '2022-03-01' or newer."}}
        Target: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-13c8e4160d62/resourceGroups/ResourceGroupName/providers/Microsoft.Compute/virtualMachineScaleSets/VMSSName

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group delete --name {} --yes --debug --force-deletion-types Microsoft.Compute/virtualMachineScaleSets`

## Expected Behavior
Successfully delete a resource group with the forcedelete option. 
## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.42.0

Extensions:
aks-preview 0.5.114

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by navba-MSFT** [comment]
@MinKPark Thanks for reaching out to us and reporting this issue. I am unable to reproduce this issue at my end. I was able to delete the RG containing VMSS resource.

Could you please re-run the same command again with the `--no-wait ` switch and check if the issue reoccurs ?

> az group delete -n MyResourceGroup --force-deletion-types Microsoft.Compute/virtualMachines --no-wait

**Comment by navba-MSFT** [comment]
@MinKPark I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by MinKPark** [comment]
@navba-MSFT thanks for pinning me on this. I asked my team to confirm this. I'll let you know once it is confirmed.

**Comment by navba-MSFT** [comment]
@MinKPark I wanted to do quick follow-up to check if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@MinKPark Currently I see that you are getting a different error. Could you please share the complete cli command that you ran ? Also run the command with `--debug` switch and share the error output.

**Comment by BigRollTide** [comment]
I get the same issue when deleting a VMSS from the Portal.  Seems to be an issue with the API for VMSS's

Error details name_of_my_vmss: This request can be made with api-version '2022-03-01' or newer. (Code: BadRequest)

I had to use the az resource delete command with the api version explicitly stated

**Comment by bviala** [comment]
for a VMSS:

az resource delete \
  --resource-group my-vmss-rg \
  --name my-vmss \
  --resource-type "Microsoft.Compute/virtualMachineScaleSets" \
  --api-version 2022-03-01
