### ISSUE TITLE
Autocomplete is slow when command is not complete

### ISSUE THREAD

**Issue by bebound** [Azure/azure-cli#24762]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

If I press TAB after `az account cle`, it takes 4seconds to show suggestion `az account clear`. However `az account -h` only takes 2seconds.

The debug log shows that it reloads modules and extensions when run `az account cle --debug`.
```
cli.azure.cli.core: Could not find a match in the command or command group table for 'account cle'. The index may be outdated.
cli.azure.cli.core: Loading command modules:
```

I think we can make reload rules stricter. When ` _ARGCOMPLETE=1`, if `account cle` is not found, check if `account` is matched. If still not matched, reload.

Related issue: https://github.com/Azure/azure-cli/issues/9157

**Comment by yonzhan** [comment]
Good investigation for the slowness of autocomplete
