### ISSUE TITLE
Azure Managed Lustre - Requesting CLI development support for AzCLI

### ISSUE THREAD

**Issue by blepore** [Azure/azure-cli#24773]
We are requesting CLI development support for AzCLI for Azure Managed Lustre.

- Swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2023-05-01/amlfilesystem.json
- Command group can be `az amlfilesystem` or `az amlfs`.

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by jsntcy** [comment]
Involve CLI PM @Jacekey23 to help you go through APEX onboarding process.

**Comment by blepore** [comment]
Hi @jsntcy - thanks for your support.

Azure Managed Lustre is a new service offering currently in Private Preview. Public Preview is scheduled to begin on February 22. GA is scheduled for May '23. 

This service is built on top of the existing Microsoft.StorageCache RP. Here is the swagger (recently approved): 
https://github.com/Azure/azure-rest-api-specs/pull/19724

We are asking for AZCLI support at the very least, Terraform support is a close second.

**Comment by jsntcy** [comment]
@blepore, Azure CLI already had an extension for storage cache, [here](https://learn.microsoft.com/en-us/cli/azure/hpc-cache?view=azure-cli-latest) is the doc and [here](https://github.com/Azure/azure-cli-extensions/tree/main/src/hpc-cache/azext_hpc_cache) is the source code. Some questions for you:

- Is Azure Managed Lustre referred to this file https://github.com/Azure/azure-rest-api-specs/blob/main/specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2023-05-01/amlfilesystem.json?
- Do we need create a new CLI extension for Azure Managed Lustre? or we just add new command groups in existing extension?

Here are some existing command groups for storage cache,
![image](https://github.com/Azure/azure-cli/assets/16348853/4180a870-9f00-47f2-bd77-3ede7160868c)

**Comment by blepore** [comment]
Hi - I could swear I answered this. I'm sorry about that. 

1. Yes, Azure Managed Lustre is referring to the amlfilesystem parts of the swagger and source code
2. Yes, we do need to create a new extension. "amlfs" or "amlfilesystem" make sense - whatever you suggest.

**Comment by blepore** [comment]
> I could swear I answered this.

Ah yes - I saw a similar comment from Yu Chen here and responded:

https://msazure.visualstudio.com/One/_workitems/edit/16449787#24205197
