### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by niejam** [Azure/azure-cli#24782]
## Describe the bug

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
HTTPSConnectionPool(host='ptsg4crbrwb01.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Traceback (most recent call last):
pip-unpacked-wheel-nmdz9lpd\urllib3\contrib\pyopenssl.py, ln 472, in wrap_socket
Temp\pip-unpacked-wheel-rdjxxv4b\OpenSSL\SSL.py, ln 1915, in do_handshake
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip --resource-group {} --name {} --src {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.10.1

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by niejam** [comment]
Is this because of not using a multi-tenant setting?

**Comment by RakeshMohanMSFT** [comment]
@niejam Can you please upgrade to the latest version of azure CLI [2.42.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli) and retry?
