### ISSUE TITLE
private-ranges parameter support for 'az network firewall policy create' and 'az network firewall policy update'

### ISSUE THREAD

**Issue by Gizachew-Eshetie** [Azure/azure-cli#24789]
**Related command**

az network firewall policy create, az network firewall policy update

Do we have a an option to specify private-ranges when creating new firewall policy or updating an existing one? This parameter is used for setting Perform SNAT options that are available in the portal shown on the below image.

![image](https://user-images.githubusercontent.com/18257706/205154968-4c133b14-4401-46a2-ae82-d2c87fe5fd96.png)

**Is your feature request related to a problem? Please describe.**

Unable / don't know how to set Perform SNAT options in CLI. In PowerShell below command is used to specify the private ranges and based on the privates ranges provided the Perform SNAT is determined. 

New-AzFirewallPolicy -Name myFp -ResourceGroupName myRg -Location westus2 -PrivateRange @("3.3.0.0/24", "98.0.0.0/8","10.227.16.0/20")

**Describe the solution you'd like**

Can we add private-ranges parameter to firewall policy create or update commands if we don't already have. If we already have, can you please provide usage and documentations?

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
network feature

**Comment by necusjz** [comment]
@Gizachew-Eshetie Does it meet your needs? https://learn.microsoft.com/en-us/cli/azure/network/firewall?view=azure-cli-latest#az-network-firewall-create (1st example)
