### ISSUE TITLE
Example commands do not work, no scaling operation is initiated but the command does not throw an exception 

### ISSUE THREAD

**Issue by meepstei** [Azure/azure-cli#24808]
[Enter feedback here]
running command: az webapp scale -g <resourcegroup> -n <webappname> --instance-count <any #>  

does not work. The command does not fail or return any exception, no changes are made and no ARM requests found when tracing session ID. 

Working command: az appservice plan update --name '<AppServicePlanName>' --resource-group '<ResourceGroup>' --number-of-workers <desired # of workers>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://learn.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by seligj95** [comment]
`az webapp scale` is part of the appservice-kube extension. If you are not using a kube environment, this command is not relevant for you. Web apps on the standard App Service can be scaled using `az appservice plan update` as you identified.

**Comment by meepstei** [comment]
@SaurabhSharma-MSFT @seligj95 Thanks for confirming this. Can we adjust the info in the linked doc to explicitly state this is for kube environments? The doc reads as if all commands are for Web Apps/App Services, the reference simply states "Manage web apps."

**Comment by seligj95** [comment]
If you try running the command without the appservice-kube extension, you should get the following error. Did you not get this?

<img width="847" alt="image" src="https://user-images.githubusercontent.com/11475594/207666440-e60bb6b4-5369-413e-81da-9958e7b31dab.png">

After installing the extension and trying the command on a non-kube environment app, it did actually work. So as long as you have the extension installed, it can be used. However the recommended method is to use `az appservice plan update`. I will need to go back to the team and investigate why this is the case.

**Comment by meepstei** [comment]
> If you try running the command without the appservice-kube extension, you should get the following errors. Did you not get this?
> 
> <img alt="image" width="847" src="https://user-images.githubusercontent.com/11475594/207666440-e60bb6b4-5369-413e-81da-9958e7b31dab.png">
> 
> <img alt="image" width="851" src="https://user-images.githubusercontent.com/11475594/207668095-f93c713f-2d49-4464-b087-0a3506b78eb7.png">
> 
> After installing the extension and trying the command on a non-kube environment app, it did actually work. So as long as you have the extension installed, it can be used. However the recommended method is to use `az appservice plan update`. I will need to go back to the team and investigate why this is the case.

I was testing this from the Cloud shell CLI in the Azure portal, and the "try It" option linked in the doc. No exception was returned because I assume this extension is already installed in the Azure hosted CLI. However, I was asked to install the extension from the doc "Try It" option today (I honestly do not remember being asked before), but after its installed, the command "runs" and does not fail, it also does not scale the App either. No requests are logged in ARM to initiate the scaling operation for the test windows Web App I was using.

**Comment by apwestgarth** [comment]
Hi @meepstei - you mention a test Windows web app.  Windows Apps are not supported on App Service on Arc which is what the appservice-kube extension is for.  I've just tested the extension on a web app deployed to an App Service on Arc enabled Kubernetes cluster in Cloud Shell and see successful scaling operations, the pods on my kubernetes cluster scale also.

Can you confirm you are attempting to use the command to scale a web app deployed to an App Service on Arc Enabled Kubernete cluster please?

**Comment by meepstei** [comment]
> Hi @meepstei - you mention a test Windows web app. Windows Apps are not supported on App Service on Arc which is what the appservice-kube extension is for. I've just tested the extension on a web app deployed to an App Service on Arc enabled Kubernetes cluster in Cloud Shell and see successful scaling operations, the pods on my kubernetes cluster scale also.
> 
> Can you confirm you are attempting to use the command to scale a web app deployed to an App Service on Arc Enabled Kubernete cluster please?

@apwestgarth  I think we are focusing on the wrong point. Yes, I was testing from an unsupported environment, this was a repro of an two existing support cases. The problem we have established now is the command "runs" and does not return an exception or failure, it also does not scale the App Service Plans(expected for non-kube environments). We had two cases come in asking why the command did not work or throw exceptions and it was only confirmed in this feedback request that its not supported in non-kube environments, I could not locate any other public forum that indicates the command should not be used for App Services in general. 

 I am wanting the doc to be updated to explicitly state these commands are for Kube environments, and if possible, have the command return an exception when attempted on non-kube hosted resources.

**Comment by apwestgarth** [comment]
@meepstei got it, sorry for my misunderstanding, will work on incorporating your feedback.

**Comment by apwestgarth** [comment]
Command has been updated along with docs, blocks when attempting to us with non Azure Arc enabled App Service apps.  Provides command to use as alternative.  To see change ensure to update appservice-kube extension to 0.1.9
