### ISSUE TITLE
Request to remove the support of the Send and get test notifications at Subscription and Resource Group Level

### ISSUE THREAD

**Issue by thomasp98296** [Azure/azure-cli#24809]
**Related command**
Please remove the support for the follow APIs.
1.	Send and get test notifications at Subscription Level
2.	Send and get test notifications at Resource Group Level

Please note that we should not remove the Send and get test notifications at the Action Group level.

**Is your feature request related to a problem? Please describe.**
Yes, we initially added the supports for the send and get test notifications at Subscription and Resource Group level. However, this turned out that ARM cannot route these APIs to the right regional endpoint. So we must remove them. Otherwise, these APIs will be routed to the global endpoint and that will jeopardize customer's privacy.

**Describe the solution you'd like**
Simple remove the support for the above APIs

**Describe alternatives you've considered**
No other solution is available at the moment without jeopardizing customer's privacy.

**Additional context**
None

**Comment by yonzhan** [comment]
@kairu-ms fo awareness
