### ISSUE TITLE
Add os imagescheduled event configurability

### ISSUE THREAD

**Issue by johnzhang-microsoft** [Azure/azure-cli#24811]
**Resource Provider**
What is the Azure resource provider your feature is part of?

CRP, Microsoft.Compute

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.

Adding some Virtual Machine Scale Set properties in ScheduledEventsProfile.OSImageNotificationProfile.

OSImageNotificationProfile.enable is a configurable property on Create or Update of VMSS. When enabled, this will enable a notification to be sent to the VM on the instance metadata server that a VM is undergoing an operation on the OS image, such as a reimage or an OS update.

The feature is disabled by default. By default scheduledEventsProfile is null, which disables this feature. This is equivalent to setting OSImageNotificationProfile.enable = false.

This is similar to the below:
https://github.com/Azure/azure-cli/issues/10124
https://github.com/Azure/azure-cli/pull/10445

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

2022-11-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. This should be on the master branch
of the REST API specs repo.

PR:
https://github.com/Azure/azure-rest-api-specs/pull/21253

Not merged into master branch yet. This is where it will eventually be though, you can replace commit hash with "master":
https://github.com/Azure/azure-rest-api-specs/blob/f0900e97e33c476881e6e54de58f19293c96c56a/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-11-01/examples/virtualMachineScaleSetExamples/VirtualMachineScaleSet_Create_WithOSImageScheduledEventEnabled.json

All references from scheduledEventsProfile

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

Last week of January, 2023. We're targeting a February 2023 GA release, so it'd be great if we could see this happen before then.
Thanks!

**Comment by yonzhan** [comment]
compute feature

**Comment by zhoxing-ms** [comment]
@johnzhang-microsoft Since we have no release window at the end of January, and the closest release time is **02-07**. Does this release date **02-07** meet your expectations?

**Comment by PARADISSEEKR** [comment]
Hi @johnzhang-microsoft I can't find `OSImageNotificationProfile`  in the python SDK here(https://github.com/Azure/azure-rest-api-specs/pull/21253#issuecomment-1289713658), `2022-11-01 ` folder does not exist, could you please provide a package containing `OSImageNotificationProfile` for me to develop. And azure cli requires publish SDK, so please release it on pypi as soon as possible.

**Comment by johnzhang-microsoft** [comment]
Hi @PARADISSEEKR . There were holidays in the USA, so the 2022-11-01 API release master needed to wait. He just submitted SDK generation for 2022-11-01 for python today. Should be available by end of this week or beginning of next week. Will that work?

**Comment by PARADISSEEKR** [comment]
> Hi @PARADISSEEKR . There were holidays in the USA, so the 2022-11-01 API release master needed to wait. He just submitted SDK generation for 2022-11-01 for python today. Should be available by end of this week or beginning of next week. Will that work?

Yes, could you please provide the link, I can use private package to develop first.

**Comment by johnzhang-microsoft** [comment]
Does this link work for you? https://github.com/Azure/sdk-release-request/issues/3624

I was told the release schedule is changed and the official one will be 1/27/2023.

**Comment by PARADISSEEKR** [comment]
> Does this link work for you? [Azure/sdk-release-request#3624](https://github.com/Azure/sdk-release-request/issues/3624)
> 
> I was told the release schedule is changed and the official one will be 1/27/2023.

Could you please provide a private python sdk package containing `OSImageNotificationProfile`, I can't find python sdk with `2022-11-01  folder in https://github.com/Azure/sdk-release-request/issues/3624#issuecomment-1376669064, https://github.com/Azure/azure-rest-api-specs/pull/21571#issuecomment-1316162321 ,it seems that it is not generated correctly.

**Comment by johnzhang-microsoft** [comment]
I am sorry, I have never generated python SDK packages for features before. Is there a guide that can be followed?

If not, there is no rush on my end, and development on this feature can wait until python SDK is released, so you can move on to other things and not be blocked.

**Comment by msyyc** [comment]
Here is the private package including 2022-11-01: https://github.com/Azure/azure-rest-api-specs/pull/22144/checks?check_run_id=10569374082
![image](https://user-images.githubusercontent.com/70930885/211736514-c3d276bf-5e97-4cb8-9a5a-096dc6ba4369.png)

Here is the guideline: https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/private_package/get_private_package.md

**Comment by johnzhang-microsoft** [comment]
Thanks @msyyc. @PARADISSEEKR is that enough for you to work with right now?

**Comment by PARADISSEEKR** [comment]
> 谢谢@msyyc。@PARADISSEEKR这足以让您现在使用吗？

yes, do we need to add OSImageNotificationProfile.enable and OSImageNotificationProfile.notBeforeTimeout as new parameters?

**Comment by johnzhang-microsoft** [comment]
Please add `OSImageNotificationProfile.enable` as `enable-osimage-notification` to both. It should be similar to terminate notification enable.

https://learn.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-update

`OSImageNotificationProfile.notBeforeTimeout` has to be 15 minutes right now. No need to add. If you do add, the only valid value is 15 minutes.
