### ISSUE TITLE
Dependencies are pinned 

### ISSUE THREAD

**Issue by rickardp** [Azure/azure-cli#24818]
For example, pytz and semver dependencies is pinned to an exact version rather than specifying a minimum required version. This causes dependency hell and makes it awkward to use azure-cli in a Docker image shared with other Python packages.

Please consider specifying an open version range for all the dependencies to this package.

Workaround is to install this dependency first, then stage installation of other dependencies to allow them to upgrade the shared dependencies such as pytz. No issue has been observed with running a different (later) version of pytz or semver.

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by bebound** [comment]
Azure-cli is an independent package. If your code does not contain `from azure.cli import xxx`, you can install it into a virtual env or install it from package manager.

**Comment by rickardp** [comment]
I am specifically trying to use a package manager (pip).

I'm building a Docker image in this scenario so I try to avoid hacks like virtualenv. (Docker being the method to virtualize the Python environment in my case).

Is "independent package" a concept? I never heard of it before.

It is considered best practice to use version ranges to avoid dependency hell in Python.

**Comment by bebound** [comment]
We provide packages for Linux. https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt
