### ISSUE TITLE
az webapp delete --name argument description appears incorrect

### ISSUE THREAD

**Issue by flcdrg** [Azure/azure-cli#24822]
## Describe the bug
The description for the --name argument includes the following text which makes no sense in the context of deletion:

> "If left unspecified, a name will be randomly generated. You can configure the default using \`az configure --defaults web=<name>\`."

**Command Name**
`az webapp delete`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp delete -h`

## Expected Behavior
Correct documentation

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.43.0

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@flcdrg Thank you for reaching out, we are looking into it.
