### ISSUE TITLE
Found multiple accounts with the same username 

### ISSUE THREAD

**Issue by Rakigh** [Azure/azure-cli#24848]
Found multiple accounts with the same username 'cloud@lucid.house': [{'home_account_id': '00000000-0000-0000-e9bc-9a2410da1d63.9188040d-6c67-4c5b-b112-36a304b66dad', 'environment': 'login.microsoftonline.com', 'username': 'cloud@lucid.house', 'authority_type': 'MSSTS', 'local_account_id': 'vtq1A3mKmzNtJriD136B0F3a4EGy71cRdM6b_4M7EIk', 'realm': 'organizations'}, {'home_account_id': 'dcc4f9d0-67dd-426f-b337-2156df61f8a2.f2edcb73-0019-4a18-b6aa-05cbd5ff54b1', 'environment': 'login.microsoftonline.com', 'username': 'cloud@lucid.house', 'authority_type': 'MSSTS', 'local_account_id': 'dcc4f9d0-67dd-426f-b337-2156df61f8a2', 'realm': 'f2edcb73-0019-4a18-b6aa-05cbd5ff54b1'}, {'home_account_id': '0a6bbec6-8b91-45ca-9dec-21b8486ae8f0.7d6ebeb4-e2db-4f28-aeec-abd810635a08', 'environment': 'login.microsoftonline.com', 'username': 'cloud@lucid.house', 'authority_type': 'MSSTS', 'local_account_id': '0a6bbec6-8b91-45ca-9dec-21b8486ae8f0', 'realm': '7d6ebeb4-e2db-4f28-aeec-abd810635a08'}]
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20168

Please can anyone help with this issue

**Comment by yonzhan** [comment]
duplicate with https://github.com/Azure/azure-cli/issues/20168
