### ISSUE TITLE
Add max surge in vmss rolling upgrade policy configurability

### ISSUE THREAD

**Issue by johnzhang-microsoft** [Azure/azure-cli#24846]
### Related command

`az vmss create --maxsurge`

https://learn.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-create

### Resource Provider

CRP, Microsoft.Compute

### Description of Feature or Work Requested

Users will set enable to true for max surge. If enabled, VMSS will create new virtual machines to upgrade the scale set, rather than updating the existing virtual machines. Existing virtual machines will be deleted once the new virtual machines are created for each batch.

### Minimum API Version Required

2022-11-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/21253
https://github.com/Azure/azure-sdk-for-net/pull/32880

### Request Example

Not merged into master branch yet. This is where it will eventually be though, you can replace commit hash with "master":

https://github.com/Azure/azure-rest-api-specs/blob/f0900e97e33c476881e6e54de58f19293c96c56a/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-11-01/examples/virtualMachineScaleSetExamples/VirtualMachineScaleSets_Update_MaximumSet_Gen.json

https://github.com/Azure/azure-rest-api-specs/blob/f0900e97e33c476881e6e54de58f19293c96c56a/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-11-01/virtualMachineScaleSet.json

See usage of "maxSurge"

### Target Date

CLI team's planned 02/07/2023 release window should be okay

**Comment by PARADISSEEKR** [comment]
Hi @johnzhang-microsoft I can't find `maxSurge` in the python SDK here(https://github.com/Azure/azure-rest-api-specs/pull/21253#issuecomment-1289713658), `2022-11-01` folder does not exist, could you please provide a private package containing `maxSurge` for me to develop. And azure cli requires publish SDK, so please release it on pypi as soon as possible.

**Comment by johnzhang-microsoft** [comment]
Hi @PARADISSEEKR . There were holidays in the USA, so the 2022-11-01 API release master needed to wait. He just submitted SDK generation for 2022-11-01 for python today. Should be available by end of this week or beginning of next week. Will that work?

**Comment by mimckitt** [comment]
Checking in on the status of this. Thanks!
