### ISSUE TITLE
New Isolated v2 (I4v2, I5v2, I6v2) Azure App Service Plan Tiers Not Supported in CLI

### ISSUE THREAD

**Issue by adchungcsc** [Azure/azure-cli#24858]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

`az appservice list-locations --sku I5v2 `

`az appservice plan update --name PLAN_NAME -g PLAN_RG --sku "I4v2" `

**Describe the bug**

I was taking a look at the new Isolated v2 SKUs announced on the [appservice blog](https://azure.github.io/AppService/2022/12/01/Announcing-Larger-Isolatedv2-SKUs.html) and tried to use CLI appservice commands like `list-locations` and `update` with the new SKUs (I4v2, I5v2, I6v2) but they appear to not work with the CLI even though they're referenced in the blog as being available with the latest CLI 2.43.0 and are referenced throughout the help documentation

![Screen Shot 2022-12-09 at 3 38 55 PM](https://user-images.githubusercontent.com/45158195/206792324-086f90e6-1652-4981-af1d-c8b94ef1f8bd.png)

**To Reproduce**

1. Verify CLI is on version 2.43.0 with `az version`
2. Perform `az appservice list-locations --sku I5v2`
3. See CLI returns error "Invalid sku(pricing tier), please refer to command help for valid values
" when SKUs I(4-6)v2 are passed in 
4. If testing update/create, provision an ASEv3 in North Central US & provision a plan on it.
5. Perform an update `az appservice plan update --name PLAN_NAME -g PLAN_RG --sku "I4v2" `
6. See CLI returns error "Invalid sku(pricing tier), please refer to command help for valid values"

**Expected behavior**

Expected that the CLI existing behaviors (list-locations, update) work with the newly added Azure App Service SKUs I4v2, I5v2, I6v2.

**Environment summary**

- CLI Version: 2.43.0
- OS Version: Mac OS Monterey 12.6
- Shell Type: fish

**Additional context**

These tiers were released recently and the other older tiers in the Isolatedv2 family appear to work with the CLI.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@adchungcsc  Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@adchungcsc I am able to replicate this issue at my end. As a workaround, Could you please test with the below workaround and let us know if that helps?

> az rest --url https://management.azure.com/subscriptions/XXX- XXX/providers/Microsoft.Web/geoRegions?api-version=2022-03-01&sku=**I5V2**

**Comment by adchungcsc** [comment]
hi @navba-MSFT 

The workaround you recommended for directly calling the geo regions API endpoint appears to work.

**Comment by adchungcsc** [comment]
On a separate note, is this the correct usage of the geo regions API? It looks like you can only pass the app service family name for the sku parameter with a predetermined SkuName item ie "PremumV3" or "IsolatedV2" and you cannot pass in the tier name ie I5v2 based on the docs.

https://learn.microsoft.com/en-us/rest/api/appservice/list-geo-regions/list-geo-regions#skuname

This is also related to that endpoint. The new tiers in Isolated v2 (I4-6 v2) are in the Isolated v2 family but are only in two regions compared to the other members of the family which are available in many more. Would this mean that for example, the API would say that I4v2 is available in a region I2v2 is available in since the API appears to be considering family and not tier?

I also saw that this API call is returning back quite a few regions even though I expect it to only return the two preview regions (North Central US & West Central US). The endpoint seems to also return all regions when passing in invalid skunames like random strings.

`az rest --url "https://management.azure.com/subscriptions/XXX-XXX/providers/Microsoft.Web/geoRegions?api-version=2022-03-01&sku=RANDOMSTRING"`

**Comment by madsd** [comment]
Hi,

we are building out special geoRegion API for ASE to allow returning only the regions in which the SKU exists. It will take a few cycles before it is ready to use from the CLI.

**Comment by zboldyga** [comment]
@madsd we are running into an issue upgrading to the higher tiers (I4v2, I5v2, I6v2) in South Central US. CLI doesn't work, and suggested workaround in this Issue doesn't work. 

``` az appservice list-locations --sku I5v2  ```

shows 

```
[
  {
    "name": "East US"
  },
  {
    "name": "North Europe"
  },
  {
    "name": "West Europe"
  },
  {
    "name": "Southeast Asia"
  },
  {
    "name": "East Asia"
  },
  {
    "name": "West US"
  },
  {
    "name": "Japan West"
  },
  {
    "name": "Japan East"
  },
  {
    "name": "East US 2"
  },
  {
    "name": "North Central US"
  },
  {
    "name": "South Central US"
  },
  {
    "name": "Brazil South"
  },
  {
    "name": "Australia East"
  },
  {
    "name": "Australia Southeast"
  },
  {
    "name": "Central US"
  },
  {
    "name": "Central India"
  },
  {
    "name": "West India"
  },
  {
    "name": "South India"
  },
  {
    "name": "Canada Central"
  },
  {
    "name": "Canada East"
  },
  {
    "name": "West Central US"
  },
  {
    "name": "West US 2"
  },
  {
    "name": "UK West"
  },
  {
    "name": "UK South"
  },
  {
    "name": "Korea South"
  },
  {
    "name": "Korea Central"
  },
  {
    "name": "France Central"
  },
  {
    "name": "Australia Central"
  },
  {
    "name": "South Africa North"
  },
  {
    "name": "Switzerland North"
  },
  {
    "name": "Germany West Central"
  },
  {
    "name": "UAE North"
  },
  {
    "name": "Norway East"
  },
  {
    "name": "West US 3"
  },
  {
    "name": "Sweden Central"
  },
  {
    "name": "Qatar Central"
  },
  {
    "name": "Poland Central"
  }
]
```

but we get an invalid SKU error when running the update

does this pertain to the geoRegion API issue you mentioned? And are the listed regions accurate?
