### ISSUE TITLE
Azure CLI installation & take effect for Windows

### ISSUE THREAD

**Issue by Jidong-Yang** [Azure/azure-cli#24879]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

`$ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi`

**Describe the bug**

The above Azure CLI installation script seems to rely on certain DotNet runtimes as its dependency, and will fail if ALL DotNet runtimes are uninstalled from the machine.

**To Reproduce**

Use [DotNet uninstall tool](https://github.com/dotnet/cli-lab/releases/download/1.5.255402/dotnet-core-uninstall-1.5.255402.msi) to uninstall all runtimes on the machine, then run the Azure CLI installation script, then it will fail.

**Expected behavior**

- I want to know whether above conclusion (Azure CLI installation script depends on .NET runtime) is correct.
- Besides from that, I also want to know whether there is a way to let the [Azure CLI command] take effect immediately without re-opening the PowerShell window.
  - I am asking this because I am working on a CI pipeline that aims to automate the installation and usage of the Azure CLI. Since "Azure CLI" will need a "PowerShell Reboot" before it can take effect, I currently have to reboot the pipeline machine to achieve this. (Because it seems there is no way for me to "reboot a PowerShell window through my automation pipeline).

**Environment summary**
- Windows Server 2019

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by bebound** [comment]
1. We use WiX Toolset v3 to build msi package, and it requires .NET 3.5. https://wixtoolset.org/docs/v3/main/

2. You need to reload `PATH` to make `az` available. `$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")` works on my machine. Ref: https://stackoverflow.com/questions/17794507/reload-the-path-in-powershell
