### ISSUE TITLE
az account list-locations returns incorrect paired regions for australiacentral and australiacentral

### ISSUE THREAD

**Issue by grillba** [Azure/azure-cli#24871]
## Describe the bug

The ` az account list-locations` command lists incorrect information for the paired regions for `australiacentral` and `australiacentral`

In the output:
  * The pairedRegion for `australiacentral` is shown as `australiacentral` - whereas it is documented as `australiacentral2`.
  * The pairedRegion for `australiacentral2` is equal to `australiacentral2`  - whereas it is documented as `australiacentral`.

These paired regions are documented at https://learn.microsoft.com/en-us/azure/reliability/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies

**Command Name**
` az account list-locations`

**Errors:**

N/A

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Run the following command to list the information for the `australiacentral` and `australiacentral2` regions 

`az account list-locations --query "[? name == 'australiacentral' || name == 'australiacentral2' ]"`

In the output:
  * The pairedRegion for `australiacentral` is shown as `australiacentral` - whereas it is documented as `australiacentral2`.
  * The pairedRegion for `australiacentral2` is equal to `australiacentral2`  - whereas it is documented as `australiacentral`.

```
[
  {
    "displayName": "Australia Central",
    "id": "/subscriptions/2592e385-7a16-4a94-81ec-ac7eb3ac43fe/locations/australiacentral",
    "metadata": {
      "geographyGroup": "Asia Pacific",
      "latitude": "-35.3075",
      "longitude": "149.1244",
      "pairedRegion": [
        {
          "id": "/subscriptions/2592e385-7a16-4a94-81ec-ac7eb3ac43fe/locations/australiacentral",
          "name": "australiacentral",
          "subscriptionId": null
        }
      ],
      "physicalLocation": "Canberra",
      "regionCategory": "Other",
      "regionType": "Physical"
    },
    "name": "australiacentral",
    "regionalDisplayName": "(Asia Pacific) Australia Central",
    "subscriptionId": null
  },
  {
    "displayName": "Australia Central 2",
    "id": "/subscriptions/2592e385-7a16-4a94-81ec-ac7eb3ac43fe/locations/australiacentral2",
    "metadata": {
      "geographyGroup": "Asia Pacific",
      "latitude": "-35.3075",
      "longitude": "149.1244",
      "pairedRegion": [
        {
          "id": "/subscriptions/2592e385-7a16-4a94-81ec-ac7eb3ac43fe/locations/australiacentral2",
          "name": "australiacentral2",
          "subscriptionId": null
        }
      ],
      "physicalLocation": "Canberra",
      "regionCategory": "Other",
      "regionType": "Physical"
    },
    "name": "australiacentral2",
    "regionalDisplayName": "(Asia Pacific) Australia Central 2",
    "subscriptionId": null
  }
]
```

## Expected Behavior

Output lists:
  * The pairedRegion for `australiacentral` as `australiacentral2`.
  * The pairedRegion for `australiacentral2` `australiacentral`.
  
## Environment Summary
```
Linux-4.4.0-22000-Microsoft-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.40.0 *

Extensions:
account 0.2.3
resource-graph 2.1.0
azure-devops 0.25.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by jiasli** [comment]
As the `az account list-locations --debug` shows, the JSON is from REST API.

I tried to run API **Subscriptions - List Locations** at https://learn.microsoft.com/en-us/rest/api/resources/subscriptions/list-locations, and see exactly the same result:

![image](https://user-images.githubusercontent.com/4003950/206949235-dc25c836-a1b3-476b-aaf7-6f8396dbf33c.png)

So the incorrect information is from ARM service.

Could you please create a support ticket at https://azure.microsoft.com/en-us/support/create-ticket in order to directly report this issue to ARM service team? Thanks for understanding.
