### ISSUE TITLE
--assign-identity VS. --mi-system-assigned

### ISSUE THREAD

**Issue by rafaarcangel** [Azure/azure-cli#24884]
The page said we needed to use '--assign-identity' when working with system-managed identity...
but I received a warning on pipelines that said:

WARNING: Argument 'assign_identity' has been deprecated and will be removed in a future release. Use '--mi-system-assigned' instead.

![image](https://user-images.githubusercontent.com/19646006/207072439-61a75fb3-9297-4f7f-8486-6d0e6a7f8cd5.png)
![image](https://user-images.githubusercontent.com/19646006/207072773-54d9ae14-296f-400a-ba3e-359cb26db3da.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19f647d0-36be-3633-03fa-eb5ad31169aa
* Version Independent ID: 7476c99b-5867-2a21-62ed-8bd94e2b2b57
* Content: [az dt](https://learn.microsoft.com/en-us/cli/azure/dt?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/dt.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/dt.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@wangzelin007 for awareness

**Comment by wangzelin007** [comment]
Hi @rafaarcangel,
Can you try `az dt create --dt-name ${{parameters.instanceName}} --resource-group ${{parameters.resourceGroup}} --location ${{parameters.region}} --mi-system-assigned`?
Can you explain what exactly you mean by `the page`?
It would be even better if you can send the complete pipeline execution log.
You can click `View raw log` on the top right and copy the full log.

**Comment by rafaarcangel** [comment]
My pipeline runs successfully, with both commands. But there is a warning to change to 'new' my-system-assigned'.

This it's only a comment to update the documents you have on Microsoft, with the latest info:
- https://learn.microsoft.com/en-us/azure/digital-twins/how-to-set-up-instance-cli -> section System-assigned identity command

**Comment by wangzelin007** [comment]
@Azure/azure-iot-cli-triage,
Maybe you should update the [docs](https://learn.microsoft.com/en-us/azure/digital-twins/how-to-set-up-instance-cli#system-assigned-identity-command).

**Comment by wangzelin007** [comment]
> My pipeline runs successfully, with both commands. But there is a warning to change to 'new' my-system-assigned'.
> 
> This it's only a comment to update the documents you have on Microsoft, with the latest info:
> 
> * https://learn.microsoft.com/en-us/azure/digital-twins/how-to-set-up-instance-cli -> section System-assigned identity command
>   ![image](https://user-images.githubusercontent.com/19646006/208056069-8487f5d2-b4f6-4630-8fcb-66170457df6b.png)

Hi @rafaarcangel,
Thanks for your feedback, it has been routed to the azure-iot team.

**Comment by baanders** [comment]
Hi! I'm the author of the [Azure Digital Twins document](https://learn.microsoft.com/azure/digital-twins/how-to-set-up-instance-cli) you mentioned above. 

I've confirmed the parameter should be updated from `--assign-identity` to `--mi-system-assigned`, and made the update to this document (and in a few other spots) in this pull request: https://github.com/MicrosoftDocs/azure-docs-pr/pull/221769

This should resolve this issue. Thank you for helping us keep our docs up to date! :)

**Comment by vilit1** [comment]
Closing issue as the doc has been updated for a while. If there are any other questions, feel free to create another issue
