### ISSUE TITLE
"az network application-gateway stop --ids" requires resource group and resource name

### ISSUE THREAD

**Issue by AdamSharif-MSFT** [Azure/azure-cli#24883]
## Describe the bug

**Command Name**
`az network application-gateway stop --ids <appgwResourceId>`

**Errors:**
```
the following arguments are required: -n/--name, --resource-group/-g

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network application-gateway stop --ids <appgwResourceId>`

## Expected Behavior

The Application Gateway should be stopped without requiring the resource group nor resource name as well as the URI.

## Environment Summary
```
Linux-5.4.0-1098-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.43.0

Extensions:
ai-examples 0.2.5
ml 2.11.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@necusjz for awareness
