### ISSUE TITLE
cannot remove global custom error page for application gateway with Azure CLI 2.43.0

### ISSUE THREAD

**Issue by Abbott-fu** [Azure/azure-cli#24902]
**Describe the bug**
use below command to add global custom error page to application gateway by using Azure CLI 2.43.0
az network application-gateway update -n cn3gw -g fuzlasrrg  --custom-error-pages HttpStatus502=https://fuzlnorth2st.blob.core.chinacloudapi.cn/apple/502.html

but I  cannot remove this global error page by using Azure CLI 2.43.0
az network application-gateway update  --resource-group agic-test-rg01 --name agic-appgw01 --remove customErrorConfigurations  

error shows below:
Couldn't find 'customErrorConfigurations' in ''. Available options: ['etag', 'id', 'identity', 'location', 'name', 'properties', 'tags', 'type']

**To Reproduce**

Remove global error page with Azure CLI 2.43.0
az network application-gateway update  --resource-group agic-test-rg01 --name agic-appgw01 --remove customErrorConfigurations

**Expected behavior**
Fix the bug in Azure CLI 2.43.0

**Environment summary**
Azure CLI 2.43.0

**Additional context**
But I could remove this global custom error page for application gateway by using Azure CLi 2.37.0
az network application-gateway update -n cn3gw -g fuzlasrrg  --remove customErrorConfigurations
![image](https://user-images.githubusercontent.com/10708253/207505368-332a94a7-0cec-4faf-b31b-697154075ee4.png)
az version
{
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.44",
    "azure-firewall": "0.14.4",
    "ssh": "1.1.1"
  }
}

**Comment by necusjz** [comment]
Thanks for your feedback. It's a known issue, we'll fix it in Azure CLI 2.44.0.

**Comment by Abbott-fu** [comment]
@necusjz Thank you for confirmation

**Comment by necusjz** [comment]
BTW, we can leverage [Shorthand Syntax](https://github.com/Azure/azure-cli/blob/dev/doc/shorthand_syntax.md#null-value-in-update-commands) to make a workaround here, e.g.,
```bash
az network application-gateway update  --resource-group agic-test-rg01 --name agic-appgw01 --custom-error-pages null
```

**Comment by necusjz** [comment]
Will be fixed by https://github.com/Azure/azure-cli/pull/24960
