### ISSUE TITLE
Can't create a role assignment for Storage account with the latest CLI version: No registered resource provider found for location 'northcentralus' and API version '2020-04-01-preview' for type 'storageAccounts'.

### ISSUE THREAD

**Issue by vlardn** [Azure/azure-cli#24919]
Can't create a role assignment for the Storage account with the latest Azure CLI version. The API version '2020-04-01-preview' requested by CLI is not supported in all Azure regions.

**Command Name**
`az role assignment create`

**Errors:**
```
No registered resource provider found for location 'northcentralus' and API version '2020-04-01-preview' for type 'storageAccounts'. The supported api-versions are '2022-09-01, 2022-05-01, 2021-09-01, 2021-08-01, 2021-06-01, 2021-05-01, 2021-04-01, 2021-02-01, 2021-01-01, 2020-08-01-preview, 2019-06-01, 2019-04-01, 2018-11-01, 2018-07-01, 2018-03-01-preview, 2018-02-01, 2017-10-01, 2017-06-01, 2016-12-01, 2016-05-01, 2016-01-01, 2015-06-15, 2015-05-01-preview'. The supported locations are 'eastus, eastus2, westus, westeurope, eastasia, southeastasia, japaneast, japanwest, northcentralus, southcentralus, centralus, northeurope, brazilsouth, australiaeast, australiasoutheast, southindia, centralindia, westindia, canadaeast, canadacentral, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth, switzerlandnorth, germanywestcentral, norwayeast, westus3, jioindiawest, swedencentral, qatarcentral'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage account create --name $NAME --resource-group $RESOURCE_GROUP --sku Standard_LRS --kind Storage`
- `STORAGE_ACCOUNT_ID=$(az storage account show --name $NAME --query id -o tsv)`
- `az role assignment create --name SomeName --scope $STORAGE_ACCOUNT_ID --role "Storage Table Data Contributor" --assignee $AD_OBJECT_ID`

## Expected Behavior
Role assignment created

## Environment Summary
```
Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.43.0

Extensions:
account 0.2.5
front-door 1.0.17
aks-preview 0.5.120
k8s-extension 1.3.7
log-analytics 0.2.2

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
I am not able to repro:

```
> az group create -n jlrg1219 -l northcentralus
> az storage account create -g jlrg1219 -n jlst1219 -l northcentralus
> az role assignment create --scope /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/jlrg1219/providers/Microsoft.Storage/storageAccounts/jlst1219 --role "Storage Table Data Contributor" --assignee 0d504196-1423-4569-9a6e-15149656f0ee
{
  "canDelegate": null,
  "condition": null,
  "conditionVersion": null,
  "description": null,
  "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/jlrg1219/providers/Microsoft.Storage/storageAccounts/jlst1219/providers/Microsoft.Authorization/roleAssignments/2ca0503c-fbd4-41ca-9cf9-8713134587a7",
  "name": "2ca0503c-fbd4-41ca-9cf9-8713134587a7",
  "principalId": "0d504196-1423-4569-9a6e-15149656f0ee",
  "principalType": "User",
  "resourceGroup": "jlrg1219",
  "roleDefinitionId": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.Authorization/roleDefinitions/0a9a7e1f-b9d0-4cc4-a60d-0319b160aaa3",
  "scope": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/jlrg1219/providers/Microsoft.Storage/storageAccounts/jlst1219",
  "type": "Microsoft.Authorization/roleAssignments"
}
```

The correct URL for role assignment operation should look like

```
https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/jlrg1219/providers/Microsoft.Storage/storageAccounts/jlst1219/providers/Microsoft.Authorization/roleAssignments/2ca0503c-fbd4-41ca-9cf9-8713134587a7?api-version=2020-04-02-preview
```

The role assignment creation is made for type `roleAssignments`, so if an API version (like `2020-04-02-preview`) is not supported, it should result in an error like

```
> az rest -m get -u https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/jlrg1219/providers/Microsoft.Storage/storageAccounts/jlst1219/providers/Microsoft.Authorization/roleAssignments/2ca0503c-fbd4-41ca-9cf9-8713134587a7?api-version=2020-04-02-preview
Bad Request({"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'northcentralus' and API version '2020-04-02-preview' for type 'roleAssignments'. The supported api-versions are '2014-04-01-preview, 2014-07-01-preview, 2014-10-01-preview, 2015-05-01-preview, 2015-06-01, 2015-07-01, 2016-07-01, 2017-05-01, 2017-09-01, 2017-10-01-preview, 2018-01-01-preview, 2018-07-01, 2018-09-01-preview, 2018-12-01-preview, 2019-04-01-preview, 2020-03-01-preview, 2020-04-01-preview, 2020-08-01-preview, 2020-10-01-preview, 2021-04-01-preview, 2022-01-01-preview, 2022-04-01'. The supported locations are ''."}})
```

But your error message shows the operation is made for type `storageAccounts`. I doubt your URL may somehow be corrupted. Could you share the value of `STORAGE_ACCOUNT_ID` and `--debug` log?

```
echo $STORAGE_ACCOUNT_ID
az role assignment create --name SomeName --scope $STORAGE_ACCOUNT_ID --role "Storage Table Data Contributor" --assignee $AD_OBJECT_ID --debug
```

**Comment by jiasli** [comment]
Could be similar to https://github.com/Azure/azure-cli/issues/24919

**Comment by vlardn** [comment]
> I am not able to repro:
> 
> ```
> > az group create -n jlrg1219 -l northcentralus
> > az storage account create -g jlrg1219 -n jlst1219 -l northcentralus
> ...
> ```
@jiasli You've missed ` --sku Standard_LRS --kind Storage` options for the `az storage account create` command from my example (that options forces to create V1 storage account instead of default V2).

**Comment by vlardn** [comment]
Btw, after small investigation I just found that this bug is even more weird than I thought initially: it's not related to the storage account type but to the value for the `--name` option of `az role assignment create` command :-/

- This command:
`az role assignment create --name "/a/providers/Microsoft.Storage/t" --scope $STORAGE_ACCOUNT_ID --role "$ROLE_NAME" --assignee $AD_OBJECT_ID`
results in:
`No registered resource provider found for location 'northcentralus' and API version '2020-04-01-preview' for type 'storageAccounts'. The supported api-versions are '2022-09-01, 2022-05-01, 2021-09-01, 2021-08-01, 2021-06-01, 2021-05-01, 2021-04-01, 2021-02-01, 2021-01-01, 2020-08-01-preview, 2019-06-01, 2019-04-01, 2018-11-01, 2018-07-01, 2018-03-01-preview, 2018-02-01, 2017-10-01, 2017-06-01, 2016-12-01, 2016-05-01, 2016-01-01, 2015-06-15, 2015-05-01-preview'. The supported locations are 'eastus, eastus2, westus, westeurope, eastasia, southeastasia, japaneast, japanwest, northcentralus, southcentralus, centralus, northeurope, brazilsouth, australiaeast, australiasoutheast, southindia, centralindia, westindia, canadaeast, canadacentral, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth, switzerlandnorth, germanywestcentral, norwayeast, westus3, jioindiawest, swedencentral, qatarcentral'.`

- The same command but with another `--name`:
`az role assignment create --name "abc" --scope $STORAGE_ACCOUNT_ID --role "$ROLE_NAME" --assignee $AD_OBJECT_ID`
gives:
`The role assignment ID 'abc' is not valid. The role assignment ID must be a GUID.`

- And without `--name` option or with some GUID value for it the command succeed:
`az role assignment create --scope $STORAGE_ACCOUNT_ID --role "$ROLE_NAME" --assignee $AD_OBJECT_ID`
`az role assignment create --scope $STORAGE_ACCOUNT_ID --role "$ROLE_NAME" --assignee $AD_OBJECT_ID --name $AD_OBJECT_ID`

**Comment by jiasli** [comment]
> You've missed ` --sku Standard_LRS --kind Storage` options for the `az storage account create` command from my example (that options forces to create V1 storage account instead of default V2).

This is not relevant as role assignment doesn't care which kind of resource it is.

> Btw, after small investigation I just found that this problem is even more weird.

Not really. 🙂

`az role assignment create` supports `--name` since https://github.com/Azure/azure-cli/pull/24324.

If you provide it like `/a/providers/Microsoft.Storage/t`, the URL for calling [Role Assignments - Create](https://learn.microsoft.com/en-us/rest/api/authorization/role-assignments/create?tabs=HTTP) API becomes something like 

```
https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/jlrg1219/providers/Microsoft.Storage/storageAccounts/jlst1219/providers/Microsoft.Authorization/roleAssignments/a/providers/Microsoft.Storage/t?api-version=2020-04-02-preview
```

which makes ARM think you are calling `2020-04-02-preview` for type `storageAccounts`.

I can now repro the original error with such URL:

```
> az rest -u https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/jlrg1219/providers/Microsoft.Storage/storageAccounts/jlst1219/providers/Microsoft.Authorization/roleAssignments/a/providers/Microsoft.Storage/t?api-version=2020-04-02-preview
Bad Request({"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'northcentralus' and API version '2020-04-02-preview' for type 'storageAccounts'. The supported api-versions are '2022-09-01, 2022-05-01, 2021-09-01, 2021-08-01, 2021-06-01, 2021-05-01, 2021-04-01, 2021-02-01, 2021-01-01, 2020-08-01-preview, 2019-06-01, 2019-04-01, 2018-11-01, 2018-07-01, 2018-03-01-preview, 2018-02-01, 2017-10-01, 2017-06-01, 2016-12-01, 2016-05-01, 2016-01-01, 2015-06-15, 2015-05-01-preview'. The supported locations are 'eastus, eastus2, westus, westeurope, eastasia, southeastasia, japaneast, japanwest, northcentralus, southcentralus, centralus, northeurope, brazilsouth, australiaeast, australiasoutheast, southindia, centralindia, westindia, canadaeast, canadacentral, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth, switzerlandnorth, germanywestcentral, norwayeast, westus3, jioindiawest, swedencentral, qatarcentral, eastus2euap, centraluseuap'."}})
```

So in order to make it work, either omit `--name` or provide `--name` with your own GUID.

**Comment by vlardn** [comment]
Would it be good to add checking for the  `--name` argument to be GUID?

**Comment by jiasli** [comment]
This is a good idea! I am considering refining the help message for `--name` in https://github.com/Azure/azure-cli/pull/24926. 

However, "add checking for the --name argument to be GUID" is a client-side behavior and is hard to maintain cross client tools - Azure PowerShell, Azure SDK, etc. I will discuss within the team.
