### ISSUE TITLE
Unable to create or delete NSG rules in the latest version of Azure CLI

### ISSUE THREAD

**Issue by VishalShindeTR** [Azure/azure-cli#24910]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

In the above command, I am passing an array of strings read from a csv file in which they are stored as space separated values. This command was working fine till azure CLI version 2.39 but it fails for CLI version 2.40 and above. The error says that "The template language function 'int' cannot convert provided value '' to integer value". We are facing the same issue while issuing a delete command for NSG rules also. Attaching screenshots for your reference.

**To Reproduce**

**Expected behavior**

When I issue the command, I need the NSG rule to be created in my NSG according to the parameters given.

**Environment summary**

I am running the script on microsoft hosted agents on Azure Devops Pipeline.

**Additional context**

The error seems to be occurring due to some interference from our policy assignment. (The policy is in place for more than two years and it didn't interfere with the command in earlier CLI versions)
<img width="339" alt="NSG_POLICY_ERROR" src="https://user-images.githubusercontent.com/99705126/207851110-79b367c1-7d0a-4a29-aeb4-e907dad374d9.PNG">

**Comment by yonzhan** [comment]
route to CXP team

**Comment by necusjz** [comment]
@VishalShindeTR Thanks for your screenshot, and could you provide which specific command (with parameters) in the scripts is failing?
