### ISSUE TITLE
List connected devices on vnet/subnet using az cli

### ISSUE THREAD

**Issue by satrox28** [Azure/azure-cli#24921]
I am looking to list all connected devices from a vnet/subnet using az cli. Currently, am using below query to get the information.
```
az network vnet subnet show -g <rg_name> -n <subnet_name> --vnet-name <vnet_name> -o json| jq ".ipConfigurations[].id"

```
Unable to get a result similar to the Azure Portal connected devices on vnet result.

Is there any az query to achieve the same result.

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
Could you please explain in detail which result is expected and what's the current result?

**Comment by satrox28** [comment]
Hi @yonzhan 

Is it resolved so that the issue is closed now?.

**Comment by yonzhan** [comment]
@satrox28 could you answer the comment raised by @necusjz then we can reopen this issue. Normally we will close the issue if no response for 10 days.
