### ISSUE TITLE
SharedAccessKeyName

### ISSUE THREAD

**Issue by alezhao** [Azure/azure-cli#24920]
## Describe the bug

**Command Name**
`az iot hub monitor-events`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub monitor-events -h`

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.4 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.43.0

Extensions:
azure-iot 0.17.1

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@alezhao Can you please share the error details ?

**Comment by alezhao** [comment]
Hi,

The error was auto generated, not my post. And currently already resolved. Thanks.

AlexZhao
Data & AI Sr. Cloud Solution Architect
GCS GSI Partner
Office +86 (21) 61888776 Mobile +86 13761484208

**Comment by SaurabhSharma-MSFT** [comment]
@alezhao Thanks for the confirmation.  We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
