### ISSUE TITLE
Add WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE app settings when Linux Consumption function app is created.

### ISSUE THREAD

**Issue by khkh-ms** [Azure/azure-cli#24928]
**Related command**
az functionapp create

**Is your feature request related to a problem? Please describe.**
Currently we have special conditions for Linux Consumption for these app settings and because of special conditions, these app settings are only added for Python, Powershell and Node. There are not added for Java and dotnet.  They need to be added for all languages. 

**Describe the solution you'd like**
Basically, the ask is to remove the special handling for Linux Consumption in terms of the mentioned app settings and implement whatever we do for Windows consumption today.

**Describe alternatives you've considered**

**Additional context**
Deployment team has implemented WEBSITE_RUN_FROM_PACKAGE=1 for Linux Consumption. The mentioned app settings are needed for WEBSITE_RUN_FROM_PACKAGE=1 is work on any SKU including Linux Consumption.

**Comment by kamperiadis** [comment]
Looking at the code, we set the `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` and `WEBSITE_CONTENTSHARE` app settings for all Linux consumption function apps regardless of language. Also, when I tested it myself and created Linux consumption function apps in Java and Dotnet, these app settings were added.
