### ISSUE TITLE
Error in docs for az network nic ip-config address-pool add

### ISSUE THREAD

**Issue by barakbd** [Azure/azure-cli#24932]
Docs mention `--address-pool` can be **Name** OR **ID**.
https://learn.microsoft.com/en-us/cli/azure/network/nic/ip-config/address-pool?view=azure-cli-latest#az-network-nic-ip-config-address-pool-add-required-parameters

```
$ az network nic ip-config address-pool add --resource-group FAKE-RG --address-pool loadBalancerBackEnd --nic-name FAKE-NIC --ip-config-name ext

> usage error: --address-pool ID | --lb-name NAME --address-pool NAME | --gateway-name NAME --address-pool NAME

```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14aebf6f-e419-ed83-e60e-00cd511d5eb8
* Version Independent ID: d75451d9-e39a-d239-b864-b0fab210e61a
* Content: [az network nic ip-config address-pool](https://learn.microsoft.com/en-us/cli/azure/network/nic/ip-config/address-pool?view=azure-cli-latest#az-network-nic-ip-config-address-pool-remove)
* Content Source: [latest/docs-ref-autogen/network/nic/ip-config/address-pool.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/nic/ip-config/address-pool.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by necusjz** [comment]
`usage error: --address-pool ID | --lb-name NAME --address-pool NAME | --gateway-name NAME --address-pool NAME` means if we use **Name** of --address-pool, there must be one and only one of `--lb-name` and `--gateway-name`.

Hence, just add `--lb-name` or `--gateway-name` for your use case.

**Comment by SaurabhSharma-MSFT** [comment]
@barakbd Please let us know if you still need help on this issue.

**Comment by barakbd** [comment]
Thank you. Understood
