### ISSUE TITLE
az functionapp list-consumption-locations command error

### ISSUE THREAD

**Issue by jpaulobf** [Azure/azure-cli#24941]
## Describe the bug

**Command Name**
`az functionapp list-consumption-locations`

**Errors:**
```
No module named 'decorator'
Traceback (most recent call last):
python3/dist-packages/fabric/connection.py, ln 5, in <module>
    from invoke.vendor.six import StringIO
ModuleNotFoundError: No module named 'invoke.vendor.six'

...

python3/dist-packages/fabric/connection.py, ln 10, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp list-consumption-locations`

## Environment Summary
```
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
spring-cloud 2.3.0
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@jpaulobf Thank you for reaching out, Please upgrade to latest version of azure cli [2.43.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) and also consider updating [python ](https://docs.python.org/release/3.11.1/) as well
