### ISSUE TITLE
How to Rollback a Dotnet framework upgrade on Azure functions

### ISSUE THREAD

**Issue by emanuel-v-r** [Azure/azure-cli#24945]
We've recently upgraded an azure function to v4, and therefore had to upgrade the dotnet framework version as well, in this way
(specified [here](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-version-3-version-4?tabs=net6-in-proc%2Cazure-cli%2Cwindows&pivots=programming-language-csharp#upgrade-your-function-app-in-azure)):
`az functionapp config set --net-framework-version v6.0 -g {resourceGroupName} -n {appName}`
Unfortunately we found some issues with V4, and we rollbacked to V3.
How to rollback the framework version to dotnet core 3.1 (as V3 is only compatible with dotnet core 3.1)?

Unfortunately something like this does not seem to work:
`az functionapp config set --net-framework-version netcoreapp3.1 -g {resourceGroupName} -n {appName}`

Thank you.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@emanuel-v-r Thank you for reaching out, we are looking into it.

**Comment by Francisco-Gamino** [comment]
Adding Functions Az CLI team @amamounelsayed @apawast

**Comment by kamperiadis** [comment]
Hello @emanuel-v-r Dotnet version 3.1 is already deprecated so I am not too sure that you might be able to go back to that version. If you run `az functionapp list-runtimes`, you can see the list of supported runtimes and I no longer see version 3.1 listed. But in general, to update the dotnet runtime, you would usually just run it like `az functionapp config set -g {resourceGroupName} -n {appName} --net-framework-version <version-number (e.g. 6)>` Please let me know if you have any follow up questions/comments.
