### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sandole** [Azure/azure-cli#24943]
On the documentation under Docker extension example:
az vm extension image list-versions --publisher Microsoft.Azure.Extensions \
    -l westus -n DockerExtension -otable

There are no flags labelled "-otable". I believe the author's intent was "-o table"

Thank you,

John

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75b43753-55c6-9a97-79e7-cb102ca16905
* Version Independent ID: b88b763f-9855-5a37-ab97-375e7438f8c9
* Content: [az vm extension image](https://learn.microsoft.com/en-us/cli/azure/vm/extension/image?view=azure-cli-latest#az-vm-extension-image-list-names)
* Content Source: [latest/docs-ref-autogen/vm/extension/image.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm/extension/image.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by SaurabhSharma-MSFT** [comment]
@sandole The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
