### ISSUE TITLE
az aks nodepool add --os-sku Windows20XX w/o --os-type fails with confusing error message

### ISSUE THREAD

**Issue by atakadams** [Azure/azure-cli#24966]
## Describe the bug

**Command Name**
`az aks nodepool add`

**Errors:**
```
(InvalidOSSKU) OSSKU='Windows2019' is invalid, details: Unrecognized OSSKU
Code: InvalidOSSKU
Message: OSSKU='Windows2019' is invalid, details: Unrecognized OSSKU

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Prepare an AKS cluster
- `az aks nodepool add -g {} --cluster-name {} --os-sku Windows2019 -n {}`  (w/o --os-type Windows)

## Expected Behavior
You will say it lacks `--os-type Windows`, however it isn't obvious from the error message.
It will be better to assume `--os-type :Windows` automatically and succeeds, or at least indicates that OSSKU 'Windows2019' is invalid **for os-type: Linux**

## Environment Summary
```
Linux-5.4.0-1098-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.43.0

Extensions:
ai-examples 0.2.5
ml 2.11.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context
It seems azure cli sends REST API request with osType: Linux (simply using the default value) and outputs the error message just given from ARM.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@atakadams  Thanks for your feedback.  I have submitted a PR for the same and it will be merged once approved. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
