### ISSUE TITLE
Support for DDoS Per IP SKU - Bundle Mode for GA Release

### ISSUE THREAD

**Issue by mchakka** [Azure/azure-cli#24968]
### Related command

az network public-ip

### Resource Provider

Microsoft.Network

### Description of Feature or Work Requested

We want to allow customers to link a Ddos Protection Plan to a Public IP Resource  only if ProtectionMode = Enabled

For little more specifics:

az network public-ip
Add DDoS Protection Plan param (--ddos-protection-plan)

For reference, Vnet currently has a similar parameter - so you can probably look at that for reference for implementation

### Minimum API Version Required

2022-05-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/19985

### Target Date

2022-01-31

### Additional context

We need this feature finished by our targeted GA date above - thanks :)

We created this issue from this previous issue that we created a while back https://github.com/Azure/azure-cli/issues/23936

**Comment by yonzhan** [comment]
network feature
