### ISSUE TITLE
vm/vmss: full support for caching mechanism of managed disks

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#2497]
We should support
- [x] For vm/vmss create: expose caching on data disks, as it become clears that data disk needs different caching from os disk 
- [x]  Support no caching
- [x] For vm/vmss disk attach, expose `caching` argument as well

**Comment by tjprescott** [comment]
Currently we use the `--storage-caching` argument. With this change it will be unclear what this refers to without reading the help. I would recommend the following for VM/VMSS create:

- Expose `--storage-caching, --os-caching` for the OS cache and `--data-caching` for the data disk cache. This will allow either alias to work for the OS caching.
- At some point in the future, retire `--storage-caching`

@yugangw-msft @johanste thoughts?
