### ISSUE TITLE
`acr manifest` commands don't support OCI artifact

### ISSUE THREAD

**Issue by northtyphoon** [Azure/azure-cli#24976]
## Describe the bug

**Command Name**
`az acr manifest list`

**Errors:**
```
2022-12-24 02:52:01.430373 Error: OCI artifact found, but accept header does not support OCI artifacts. Correlation ID: d77f9b93-7c13-41e4-a41c-2526059d130f.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- push an [oci artifact manifest](https://github.com/opencontainers/image-spec/blob/v1.1.0-rc2/artifact.md) to Azure Container Registry
- `az acr manifest list {}`

## Expected Behavior

return manifest list in the json array

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.43.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@northtyphoon The above PR has a few tests that has failed. Please fix it. Post that the PR assignees can review and approve it.
