### ISSUE TITLE
Failure of creating image version

### ISSUE THREAD

**Issue by yuriwoof** [Azure/azure-cli#24972]
**Related command**

[az sig image-version create](https://learn.microsoft.com/ja-jp/cli/azure/sig/image-version?view=azure-cli-latest#az-sig-image-version-create:~:text=%E3%82%92%E5%BE%85%E3%81%A1%E3%81%BE%E3%81%99%E3%80%82-,az%20sig%20image%2Dversion%20create,-%E6%96%B0%E3%81%97%E3%81%84%E3%82%A4%E3%83%A1%E3%83%BC%E3%82%B8%20%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3)

**Describe the bug**

Unable to specified generalized VM with following error.

```
(BadRequest) The resource with id '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/LABWIN/providers/Microsoft.Compute/virtualMachines/winsvr2019' has a different OS state ['Specialized'] than the parent gallery image OS state ['Generalized'].
Code: BadRequest
```

**To Reproduce**

1. Deploy virtual machine (Windows Server 2019 - Gen1) from Azure portal
2. Geneliaze VM (reference: [Generalize a VM before creating an image - Azure Virtual Machines | Microsoft Learn](https://learn.microsoft.com/en-us/azure/virtual-machines/generalize#windows))
3. Create image definition.

```bash
$ az sig image-definition create --resource-group labwin --gallery-name labcg --gallery-image-definition win19lab --publisher myPublisher2 --offer myOffer --sku mySKU --os-type Windows --os-state generalized
```

4. Create image version

```bash
$ az sig image-version create --resource-group labwin --gallery-name labcg --gallery-image-definition win19lab --gallery-image-version 1.0.0 --target-regions 'Japan East' --replica-count 1 --virtual-machine '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/LABWIN/providers/Microsoft.Compute/virtualMachines/winsvr2019'
(BadRequest) The resource with id '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/LABWIN/providers/Microsoft.Compute/virtualMachines/winsvr2019' has a different OS state ['Specialized'] than the parent gallery image OS state ['Generalized'].
Code: BadRequest
Message: The resource with id '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/LABWIN/providers/Microsoft.Compute/virtualMachines/winsvr2019' has a different OS state ['Specialized'] than the parent gallery image OS state ['Generalized'].
$ 
```

```--managed-image``` either (described as this is supportable way in [public document](https://learn.microsoft.com/en-us/azure/virtual-machines/image-version?tabs=cli#create-an-image:~:text=%2D%2Dmanaged%2Dimage%20%22/subscriptions/%3CSubscription%20ID%3E/resourceGroups/MyResourceGroup/providers/Microsoft.Compute/virtualMachines/myVM%22))

```bash
$ az sig image-version create --resource-group labwin --gallery-name labcg --gallery-image-definition win19lab --gallery-image-version 1.0.0 --target-regions 'Japan East' --replica-count 1 --managed-image '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/LABWIN/providers/Microsoft.Compute/virtualMachines/winsvr2019'
(BadRequest) The resource with id '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/LABWIN/providers/Microsoft.Compute/virtualMachines/winsvr2019' has a different OS state ['Specialized'] than the parent gallery image OS state ['Generalized'].
Code: BadRequest
Message: The resource with id '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/LABWIN/providers/Microsoft.Compute/virtualMachines/winsvr2019' has a different OS state ['Specialized'] than the parent gallery image OS state ['Generalized'].
$ 
```

**Expected behavior**

Able to create image version from generalized VM.

**Environment summary**

I try this on Azure Cloud Shell.

```
$ env | grep ACC_VERSION
ACC_VERSION=master_20221202.1
$ az version
{
  "azure-cli": "2.43.0",
  "azure-cli-core": "2.43.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "ai-examples": "0.2.5",
    "ml": "2.11.0",
    "resource-graph": "2.1.0",
    "ssh": "1.1.3",
    "vm-repair": "0.4.3"
  }
}
```

**Additional context**

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
> az sig image-version create --resource-group labwin --gallery-name labcg --gallery-image-definition win19lab --gallery-image-version 1.0.0 --target-regions 'Japan East' --replica-count 1 --managed-image '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/LABWIN/providers/Microsoft.Compute/virtualMachines/winsvr2019'
(BadRequest) The resource with id '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/LABWIN/providers/Microsoft.Compute/virtualMachines/winsvr2019' has a different OS state ['Specialized'] than the parent gallery image OS state ['Generalized'].
Code: BadRequest
Message: The resource with id '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/LABWIN/providers/Microsoft.Compute/virtualMachines/winsvr2019' has a different OS state ['Specialized'] than the parent gallery image OS state ['Generalized'].

@yuriwoof `--managed-image '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/LABWIN/providers/Microsoft.Compute/virtualMachines/winsvr2019'` May I ask is the source of VM for this image is generalized?

**Comment by zhoxing-ms** [comment]
```
az vm create -g {rg} -n {vm} --image ubuntults --subscription {sub_id}
az vm deallocate -g {rg} -n {vm} --subscription {sub_id}
az vm generalize -g {rg} -n {vm} --subscription {sub_id}
az image create -g {rg} -n {image_name} --source {vm} --subscription {sub_id}
az sig create -g {rg} --gallery-name {sig_name} --subscription {sub_id}
az sig image-definition create -g {rg} --gallery-name {sig_name} --gallery-image-definition {image_def} --os-type linux -p publisher1 -f offer1 -s sku1
az sig image-version create -g {rg} --gallery-name {sig_name} --gallery-image-definition {image_def} --gallery-image-version {version} --managed-image {image_name}
```
@yuriwoof I suggest you refer to the above example of E2E scenario to create the image version

**Comment by yuriwoof** [comment]
@zhoxing-ms thank you for your help.
I just didn't mark the VM as "generalized" and finally, it succeeded with following steps.
Please close this.

```
az vm deallocate -g labwin -n winsvr2019
az vm generalize -g labwin -n winsvr2019
az sig image-definition create --resource-group labwin --gallery-name labcg --gallery-image-definition win19lab2 --publisher myPublisher3 --offer myOffer --sku mySKU --os-type Windows --os-state generalized
az sig image-version create --resource-group labwin --gallery-name labcg --gallery-image-definition win19lab2 --gallery-image-version 1.0.0 --target-regions 'Japan East' --replica-count 1 --virtual-machine '/subscriptions/<subscription id>/resourceGroups/labwin/providers/Microsoft.Compute/virtualMachines/winsvr2019'
