### ISSUE TITLE
Azure Virtual Network Manager Missing Enum

### ISSUE THREAD

**Issue by jago2136** [Azure/azure-cli#24970]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az network manager security-admin-config update
az network manager security-admin-config create

**Describe the bug**

An enum value is missing for '--apply-on-network-intent-policy' property. 

**To Reproduce**

Run the create or update command, passing this parameter with value "AllowRulesOnly", and the command will be rejected.

**Expected behavior**

The enum value "AllowRulesOnly" should be accepted. This enum is only available in API version 2022-05-01 (current latest extension is on 2022-01-01) so **please upgrade all commands to use 2022-05-01** network manager API version.

**Environment summary**

Extensions:
virtual-network-manager               0.5.3

**Additional context**

**Comment by yonzhan** [comment]
@necusjz for awareness
