### ISSUE TITLE
Image create fails

### ISSUE THREAD

**Issue by phs4suse** [Azure/azure-cli#24989]
## Describe the bug

**Command Name**
`az image create`
`az image create --resource-group "phs-AKS" --name phs-sle15sp3-base --source phs-sle15sp3a`

**Errors:**
```
'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 715, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/client_factory.py, ln 74, in get_mgmt_service_client
    **kwargs)
cli/core/commands/client_factory.py, ln 176, in _get_mgmt_service_client
    logger.debug('Getting management service client client_type=%s', client_type.__name__)
AttributeError: 'NoneType' object has no attribute '__name__'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az image create --resource-group {} --name {} --source {}`

## Environment Summary
```
Linux-5.14.21-150400.24.33-default-x86_64-with-glibc2.3.4
Python 3.6.15
Installer: PIP

azure-cli 2.17.1 *

```

**Comment by RakeshMohanMSFT** [comment]
@phs4suse Can you please upgrade to latest version of azure cli [2.43.0](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) and retry the operation?

**Comment by yonzhan** [comment]
@phs4suse please let us know whether above comment can resolve your issue.
