### ISSUE TITLE
Typo "resouce"→"resource"

### ISSUE THREAD

**Issue by hyoshioka0128** [Azure/azure-cli#24980]
https://learn.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest

![image](https://user-images.githubusercontent.com/40815708/209474675-ed481b83-8df5-47eb-9110-b0e2b164f80d.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1bdd674-b454-e863-c943-9c979b466a92
* Version Independent ID: b15341f9-3f1b-00e0-a1c2-970f25a6ab03
* Content: [az sql db](https://learn.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/sql/db.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sql/db.yml)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@hyoshioka0128 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@hyoshioka0128 Thanks for providing your valuable feedback. The above PR has been filed. It5 is currently under review.
