### ISSUE TITLE
Azure CLI not on PATH after APT install to WSL

### ISSUE THREAD

**Issue by dlwhitehurst** [Azure/azure-cli#24987]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
Using second install method to Ubuntu. APT update, then repo, then update and install.

**Describe the bug**
After azure-cli was installed, the software is not on PATH. A `which azure-cli` produces no output.

**To Reproduce**
On WSL on Windows 11 Pro, install `azure-cli` latest version 2.43.0 using the second Ubuntu method.

**Expected behavior**
I expect that `azure-cli` would be on my `$PATH`.

**Environment summary**
Windows 11 Pro, WSL Ubuntu

**Additional context**
Tried single command first and not on PATH. Then tried second method and not on PATH.

**Comment by dlwhitehurst** [comment]
My bad. Normally apt-installed products follow the same namespace as the install. So `az --version` did work. Moving too fast, but sorry for the issue.

**Comment by jiasli** [comment]
`az` executable is installed as 

```
$ command -v az
/usr/bin/az
```

https://github.com/Azure/azure-cli/blob/1d065f0cb183ab32fef32c7eeb27882ce03dfaa0/scripts/release/debian/prepare.sh#L109

So it should be available immediately after installing with `apt install`.
