### ISSUE TITLE
Microsoft.Billing new APIs for CLI and SDK

### ISSUE THREAD

**Issue by shagundaral** [Azure/azure-cli#24990]
### Related command

az rest --url 

### Resource Provider

Microsoft.Billing

### Description of Feature or Work Requested

New GA release. Add APIs to CLI and SDK.
I want to understand the process of adding APIs to CLI and SDK to be able to access them via Azure CLI and Powershell.

### Minimum API Version Required

2023-04-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/22650/files

### Request Example

Multiple:
https://github.com/Azure/azure-rest-api-specs/pull/22650/files

### Target Date

2023-04-01

### Additional context

Feature is for releasing payment related APIs for ARM users.

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by jsntcy** [comment]
Involve CLI PM @Jacekey23  to help you go through APEX onboarding process.

**Comment by shagundaral** [comment]
@Jacekey23 can you please ping me on teams @shdaral. I would like to schedule a short meeting with you to help start writing the CLI for my new APIs.

**Comment by Jacekey23** [comment]
@shagundaral We Azure CLI are one link of the chain from APEX global. Please make sure you might need to follow the onboarding process via this [onboarding survey](https://aka.ms/PLRCLIOnboardSurvey) , once you submitted, service teams could [book](https://aka.ms/PLRCLIOnboardCalendar) a consultation meeting with Az CLI, Az PowerShell and TerraForm (if necessary) all together. Hope it helps.

**Comment by Jing-song** [comment]
![image](https://github.com/Azure/azure-cli/assets/37168047/75e2c33c-2dd1-4f04-b5e8-64e38d400747)

**Comment by Jing-song** [comment]
![image](https://github.com/Azure/azure-cli/assets/37168047/f7feb484-549d-488d-848e-3f52cfed8b1d)
