### ISSUE TITLE
azure-cli-2.43 pkg missing from https://packages.microsoft.com/yumrepos/azure-cli/

### ISSUE THREAD

**Issue by tuttipazzo** [Azure/azure-cli#24998]
azure-cli-2.43 rpm pkg is not in

https://packages.microsoft.com/yumrepos/azure-cli/

repo. And running 'az upgrade' doesn't work either.

Can you please update the MS yumrepos repo to include latest MS azure-cli pkgs.
Details below...

superdude@cafe:~> az --version |& egrep azure-cli
azure-cli 2.38.0 *

superdude@cafe:~> zypper -n lr -s azure-cli
Alias : azure-cli
Name : Azure CLI
URI : https://packages.microsoft.com/yumrepos/azure-cli
Enabled : Yes
GPG Check : (r ) Yes
Priority : 50 (raised priority)
Autorefresh : On
Keep Packages : Off
Type : rpm-md
GPG Key URI : https://packages.microsoft.com/keys/microsoft.asc
Path Prefix :
Parent Service :
Keywords : ---
Repo Info Path : /etc/zypp/repos.d/azure-cli.repo
MD Cache Path : /var/cache/zypp/raw/azure-cl

superdude@cafe:~> zypper update azure-cli
Loading repository data...
Reading installed packages...
No update candidate for 'azure-cli-2.38.0-1.el7.x86_64'. The highest available version is already installed.
Resolving package dependencies...
Nothing to do.

# 'az upgrade' doesn;t work either

superdude@cafe:~> az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.38.0. Latest version available is 2.43.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): y

Repository 'Azure CLI' is up to date.

All repositories have been refreshed.
Loading repository data...
Reading installed packages...
No update candidate for 'azure-cli-2.38.0-1.el7.x86_64'. The highest available version is already installed.
Resolving package dependencies...
Nothing to do.
CLI upgrade failed or aborted.

**Comment by yonzhan** [comment]
@bebound @jiasli for awareness

**Comment by bebound** [comment]
2.38.0 is the latest version for CentOS 7
> Starting from Azure CLI 2.39.0 (released on 08/02/2022), no RPM packages will be released for RHEL 7 and CentOS 7. You may continue to use historical versions of Azure CLI on these systems, but there will be no updates or bugfixes. Consider upgrading to newer versions of RHEL or CentOS to use the latest Azure CLI.

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf#overview
