### ISSUE TITLE
Resource Group provided to az vm repair create is silently deleted if script fails

### ISSUE THREAD

**Issue by Sandido** [Azure/azure-cli#25001]
https://msazure.visualstudio.com/One/_workitems/edit/16434702 summarizes this issue. 
Repro:
Az vm repair create -g W10_group -n W10 –repair-group-name ReproTest –verbose
![image](https://user-images.githubusercontent.com/57574409/210010665-8dadb16d-296c-496a-92e6-20bc3cbda5c1.png)

If the script fails, then the resource group provided in the Repair Group Name parameter is deleted. This may include prod data and there is no warning to the user that this will happen. 

**Ask:**

1. Update the description for the Repair Group Name parameter to state that the provided resource group will be deleted if the script fails in any way.
Example description addition: "This resource group will be deleted if this command fails."
2. A longer term solution is being looked at.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 355a594a-22ef-fd15-0b58-07701dd1815c
* Version Independent ID: d8356a0a-9aaf-900b-ce7a-021c9a0af509
* Content: [az vm repair](https://learn.microsoft.com/en-us/cli/azure/vm/repair?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm/repair.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm/repair.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by Sandido** [comment]
@SaurabhSharma-MSFT , please take a look at this soon. This issue can and has led to production resources being deleted without the customer's knowledge.

**Comment by haagha** [comment]
@Sandido  this PR should take care of this issue:  https://github.com/Azure/azure-cli-extensions/pull/5597/files

**Comment by Sandido** [comment]
Haider has taken care of this issue and improved the documentation, so I will close this issue.
