### ISSUE TITLE
Error When Setting a Tag on a Load Balancer

### ISSUE THREAD

**Issue by andrewpleasants-bjss-nhs** [Azure/azure-cli#25008]
**Related command**
`az network lb update`

**Describe the bug**
When setting a tag that is an 'int', e.g. `az network lb update -g ... -n ... --set 'tags.label=1544'` we get the following error:

> invalid argument: Expect <class 'str'>, got 1544 (<class 'int'>

**To Reproduce**

Run the command above ensuring that the tag value is an integer value.  

**Expected behavior**
The 'int' value should be set as the tag value

**Environment summary**
```
Windows-10-10.0.19045-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.43.0
```

**Additional context**

- This has been tested on azure-cli 2.36.0 and it works.
- We have also tested 2.43.0 on Ubuntu and get the same error.
- We have tested using the 2.43.0 Docker image and get the same error.  
- We can set tags as long as they aren't integers (e.g. `az network lb update -g ... -n ... --set 'tags.label=a1'`)
- We can set int tags using other sub-commands (e.g. `az vm update -g ... -n ... --set 'tags.label=1'`)

**Update**

Issue first appears in 2.42.0 (tested using Docker image)

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by andrewpleasants-bjss-nhs** [comment]
Just done some additional tests using the Docker image, this issue first appears in **2.42.0** (2.41.0 is fine)

**Comment by necusjz** [comment]
@andrewpleasants-bjss-nhs We can take `az network lb update -n {} -g {} --set tags.label=1544 --force-string` as a workaround, and we'll expose `--tags` in Azure CLI 2.44.0 (https://github.com/Azure/azure-cli/pull/25035, around 01/10/2023).

After that, we can use:
```bash
az network lb update -n {} -g {} --tags label=1544
```
