### ISSUE TITLE
List all possible values for --scale-rule-type

### ISSUE THREAD

**Issue by arambazamba** [Azure/azure-cli#25014]
Hi. In a SDK reference I would expect all possible values for --scale-rule-types to be listed: http-rule, azure-queue, cpu-scaling-rule, ...

Or at least you could link to the following page: https://learn.microsoft.com/en-us/azure/container-apps/scale-app

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a547dc79-17cc-2b4f-da2f-10021075c355
* Version Independent ID: ba7c6a08-bb0f-622e-8876-08788dca02ba
* Content: [az containerapp](https://learn.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/containerapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/containerapp.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@arambazamba We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@arambazamba The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
