### ISSUE TITLE
Invalid permission for sas token in the example

### ISSUE THREAD

**Issue by nosalan** [Azure/azure-cli#25016]
In the example section for `az sql db export` ([link](https://learn.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#az-sql-db-export-examples)), the sas token permissions should be `rw` not `w`. Write permission is not enough and will cause this error: `The storage account cannot be accessed. Please check the storage account name and key and try again`

Please change this code:
`az storage blob generate-sas --account-name myAccountName -c myContainer -n myBacpac.bacpac \
    --permissions w --expiry 2018-01-01T00:00:00Z`
to following:
`az storage blob generate-sas --account-name myAccountName -c myContainer -n myBacpac.bacpac \
    --permissions rw --expiry 2018-01-01T00:00:00Z`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1bdd674-b454-e863-c943-9c979b466a92
* Version Independent ID: b15341f9-3f1b-00e0-a1c2-970f25a6ab03
* Content: [az sql db](https://learn.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#az-sql-db-export)
* Content Source: [latest/docs-ref-autogen/sql/db.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sql/db.yml)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@nosalan We will fix it.
