### ISSUE TITLE
az network application-gateway update failing to parse --set arg (v2.43)

### ISSUE THREAD

**Issue by rennerg** [Azure/azure-cli#25010]
## Describe the bug
After upgrading to the latest version of `az-cli`, the `az network application-gateway update` command is now unable to parse the argument passed to `--set`. 

**Command Name**
`az network application-gateway update -n <name> -g <rg> --set <args>`

**Errors:**
```
ERROR: Couldn't find 'requestRoutingRules' in 'requestRoutingRules'. Available options: ['etag', 'id', 'identity', 'location', 'name', 'properties', 'tags', 'type']
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network application-gateway update -n {} -g {} --set requestRoutingRules[0].priority=210 requestRoutingRules[1].priority=200 requestRoutingRules[2].priority=220 requestRoutingRules[3].priority=230`

## Expected Behavior

Success.

## Environment Summary
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.27, Ubuntu 18.04.5 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.43.0
```

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
Similar issues as https://github.com/Azure/azure-cli/issues/24902 and will be fixed by https://github.com/Azure/azure-cli/pull/24960.

**Comment by rennerg** [comment]
Is there a workaround? Our AD pipeline is broken until this fix is available

**Comment by necusjz** [comment]
> Is there a workaround? Our AD pipeline is broken until this fix is available

Let's try this:
```
--set properties.requestRoutingRules[0].priority=210 properties.requestRoutingRules[1].priority=200 properties.requestRoutingRules[2].priority=220 properties.requestRoutingRules[3].priority=230
```

**Comment by rennerg** [comment]
> properties.requestRoutingRules[0].priority=210 properties.requestRoutingRules[1].priority=200 properties.requestRoutingRules[2].priority=220 properties.requestRoutingRules[3].priority=230

Yes! That worked, thank you.

**Comment by rennerg** [comment]
> > properties.requestRoutingRules[0].priority=210 properties.requestRoutingRules[1].priority=200 properties.requestRoutingRules[2].priority=220 properties.requestRoutingRules[3].priority=230
> 
> Yes! That worked, thank you.

I may have spoke too soon. The suggested workaround did not error out, however the routing rule priorities were not updated.

**Comment by necusjz** [comment]
> > > properties.requestRoutingRules[0].priority=210 properties.requestRoutingRules[1].priority=200 properties.requestRoutingRules[2].priority=220 properties.requestRoutingRules[3].priority=230
> > 
> > 
> > Yes! That worked, thank you.
> 
> I may have spoke too soon. The suggested workaround did not error out, however the routing rule priorities were not updated.

@rennerg Unfortunately, Azure CLI 2.44.0 will fix it on around 01/10/2023. After that, we can keep use:
```bash
az network application-gateway update -n {} -g {} --set requestRoutingRules[0].priority=210 requestRoutingRules[1].priority=200 requestRoutingRules[2].priority=220 requestRoutingRules[3].priority=230
```
