### ISSUE TITLE
Unable to tag microsoft.insights/workbooks using az resource tag command

### ISSUE THREAD

**Issue by Data-Alchemy** [Azure/azure-cli#25022]
## Describe the bug

**Command Name**
`az resource tag`

**Errors:**
```
(BadRequest) Value cannot be null.

Parameter name: The serializedData field is missing or null. Use canFetchContent=true or api-version=2018-06-17-preview when using the GET API to ensure this field is present, or use PATCH if trying to perform a partial update.
Code: BadRequest
Message: Value cannot be null.

Parameter name: The serializedData field is missing or null. Use canFetchContent=true or api-version=2018-06-17-preview when using the GET API to ensure this field is present, or use PATCH if trying to perform a partial update.
Inner error: {
    "trace": [
        "System.ArgumentNullException"
    ]
}

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information. Values have been redacted for security reasons but in actual code do not have parameters.

- _Put any pre-requisite steps here..._
- `az resource tag --tags Type=Test --ids /subscriptions/$subscription/resourceGroups/$resource_group/providers/microsoft.insights/workbooks/$id`

## Expected Behavior
The resource should have whatever tags I pass

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.8.0
Installer: PIP

azure-cli 2.43.0

Extensions:
account 0.2.5
azure-devops 0.25.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by Data-Alchemy** [comment]
Hello team is there any update on this?

**Comment by zhoxing-ms** [comment]
@Data-Alchemy We will fix the issue in this sprint, the expected release time is 02-07, does this time meet your expectations?

**Comment by zhoxing-ms** [comment]
@Data-Alchemy I have completed the development and built the private package. Could you help experience whether the private package has solved your problem? [package link](https://dev.azure.com/azclitools/public/_build/results?buildId=26487&view=artifacts&pathAsName=false&type=publishedArtifacts)
