### ISSUE TITLE
Documentation cheange in az vm repair

### ISSUE THREAD

**Issue by diogomp94** [Azure/azure-cli#25043]
[Enter feedback here]

Optional features: 

--repair-group-name
Repair resource group name.

Edition Suggestion:
--repair-group-name
Create new resource group for repair VM, do not add the name of existing resource group or it can delete in failure case

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 355a594a-22ef-fd15-0b58-07701dd1815c
* Version Independent ID: d8356a0a-9aaf-900b-ce7a-021c9a0af509
* Content: [az vm repair](https://learn.microsoft.com/en-us/cli/azure/vm/repair?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm/repair.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm/repair.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@diogomp94 This pull request will take care of the suggested documentation change -https://github.com/Azure/azure-cli-extensions/pull/5597/files.

> ![image](https://user-images.githubusercontent.com/38112130/210741922-4631a152-6723-4a4c-9466-9df0e00b7fc0.png)

**Comment by SaurabhSharma-MSFT** [comment]
@diogomp94 We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
