### ISSUE TITLE
az tag delete incomplete details

### ISSUE THREAD

**Issue by juagliet** [Azure/azure-cli#25041]
The first example for **az tag delete** indicates that `az tag delete --name MyTag` deletes a tag from a subscription. However, it doesn't specify that it will remove predefined tags only, using this API call: <br>
https://learn.microsoft.com/en-us/rest/api/resources/tags/delete <br><br>
In addition, the same command with the --resource-id will end up removing all tags for a resource, even if using --name to specify a single tag. This should be specified to avoid accidental deletion of tags.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9984dc8-c276-354c-6c40-db77fad8e7cc
* Version Independent ID: f785cf84-06f2-946e-c8c6-c2a227394335
* Content: [az tag](https://learn.microsoft.com/en-us/cli/azure/tag?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/tag.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/tag.yml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@juagliet The PR for the fix has been created and it will be merged upon PR approval. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
