### ISSUE TITLE
Update API version from 2021-04-01 to 2022-09-01 for resources module

### ISSUE THREAD

**Issue by meghanagupta95** [Azure/azure-cli#25049]
### Resource Provider

Microsoft.Resources/resources

### Description of Feature or Work Requested

We need to update the API version from 2021-04-01 to 2022-09-01 for the resources module. The Swagger changes have been merged in https://github.com/Azure/azure-rest-api-specs/pull/21203.

### Minimum API Version Required

2022-09-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/21203

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/examples/PutTagsSubscription.json, https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/examples/PatchTagsSubscription.json, https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/examples/DeleteTagsSubscription.json, https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/examples/PutTagsResource.json, https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/examples/PatchTagsResource.json, https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/examples/DeleteTagsResource.json

### Target Date

01-31-2022

**Comment by yonzhan** [comment]
update API for resources

**Comment by zhoxing-ms** [comment]
@meghanagupta95 I'd like to confirm with you whether we only need to upgrade the api-version, or we also need to support some new commands and parameters? I see that in `Request Example` , there are some examples related to tag, does this need us to update the tag related commands?

**Comment by meghanagupta95** [comment]
@zhoxing-ms the new API version introduces a new HTTP response code of 202 for existing tags PUT/PATCH/DELETE operations (The examples are related to these pre-existing tags commands.) I don't think that should qualify as a new command or parameter, but please correct me if I'm wrong?

**Comment by zhoxing-ms** [comment]
> the new API version introduces a new HTTP response code of 202 for existing tags PUT/PATCH/DELETE operations (The examples are related to these pre-existing tags commands.

@meghanagupta95 Yes, they do not generate new commands and parameters. So you don't need us to add new commands and parameters, right?

**Comment by meghanagupta95** [comment]
@zhoxing-ms No, it is not needed.

**Comment by zhoxing-ms** [comment]
@meghanagupta95 Sorry, I have to tell you that there are risks in completing the bumping version of `Microsoft.Resources` in this sprint. The main reasons for the risk are as follows:
1. The bumping version for RP `Microsoft.Resources` affects too many modules, and **850 files** need to be re-recorded. Unfortunately, other modules are also doing the bumping version, resulting in a large number of conflicts in PR.
2. The bumping version pipeline we used recently is being upgraded, this leads to more time than usual to create PR.
3. Our Chinese team has just experienced a long Chinese Spring Festival holiday, so some works were interrupted during the holiday.

So I'd like to confirm with you in advance whether this feature request is very urgent? Could you accept that we plan to postpone it's release to the next sprint **(03-07)**? Before that, we can provide the private package through edge build to let customers with urgent needs use it in advance.
If this feature request is really very urgent and important, I will consider completing it in time through working overtime in the last few days

**Comment by meghanagupta95** [comment]
Hi @zhoxing-ms, to clarify, do you mean the changes will be out by 03-07? That should be fine.

**Comment by zhoxing-ms** [comment]
> do you mean the changes will be out by 03-07? That should be fine.

@meghanagupta95 Yes, we will release it in **03-07**, thanks for your understanding~

**Comment by yonzhan** [comment]
@meghanagupta95 since we have some urgent security related feature to deal with in this sprint and this resource version bump needs more time to collaborate with other module owners and test, we have to postpone this to the next sprint (04-04). Sorry for the inconvenience caused.
