### ISSUE TITLE
Cannot create azure service principal and assign permissions: The request did not have a subscription or a valid tenant level resource provider.

### ISSUE THREAD

**Issue by mclacore** [Azure/azure-cli#25044]
**Related command**
```
az ad sp create-for-rbac -n test --role owner --scopes /subscription/<sub id>
```

**Describe the bug**
This same command worked a month or so ago, but it doesn't anymore, and nothing has changed about my permissions. In fact I've tried this same command in several subscriptions and tenants where I'm owner & global admin.

**To Reproduce**
Paste command into azure CLI and replace w/ own sub info

**Expected behavior**
Create an azure service principal with owner permissions to the subscription

**Environment summary**
Azure portal built-in CLI

**Additional context**
Error info:
```
Creating 'owner' role assignment under scope '/subscription/<sub id>
  Role assignment creation failed.

  role assignment response headers: {'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'x-ms-failure-cause': 'gateway', 'x-ms-request-id': 'xxxx2af47', 'x-ms-correlation-request-id': 'xxxx22af47', 'x-ms-routing-request-id': 'EASTUS:20230104T175742Z:xxxx22af47', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 04 Jan 2023 17:57:41 GMT', 'Content-Length': '135'}

The request did not have a subscription or a valid tenant level resource provider.
```

**Comment by mclacore** [comment]
I confirm that it **creates** the service principal and secret, but it does **not** add the role to the subscription (and I can't seem to add it manually either).

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Wait, I can repro with your command. It seems you misspelled `--scope` as `/subscription/<sub id>`. Instead, there should be an `s` following `subscription` - `/subscriptions/<sub id>`.

**Comment by mclacore** [comment]
That's how I initially had it written, and it was failing with that too. But, it is working today. Probably user error on my part. Thanks!
