### ISSUE TITLE
Obtaining Logic App config appsettings searches for resource with Mircosoft.Web/sites provider rather than resource with Mircosoft.Logic provider

### ISSUE THREAD

**Issue by banani720** [Azure/azure-cli#25046]
## Describe the bug

**Command Name**
`az logicapp config appsettings list --name {1} --resource-group {2}`

**Errors:**
```
(ResourceNotFound) The Resource 'Microsoft.Web/sites/{1}' under resource group '{2}' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.Web/sites/{1}' under resource group '{2}' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az logicapp config appsettings list --name {} --resource-group {}`

## Expected Behavior
I would expect that the resource it should look for would not be provided by Microsoft.Web/sites but rather the resource it should give the appsettings for would be provided by Microsoft.Logic
## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.43.0

Extensions:
log-analytics-solution 0.1.1

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context
[These docs](https://learn.microsoft.com/en-us/cli/azure/logicapp/config/appsettings?view=azure-cli-latest#az-logicapp-config-appsettings-list-examples) seem to explicitly state only the name of the logic app is needed.

**Comment by PramodValavala-MSFT** [comment]
@banani720 The `logicapp` subcommand is for [Single Tenant Logic App Workflows](https://learn.microsoft.com/en-us/azure/logic-apps/single-tenant-overview-compare), which are deployed as a special case of Web Apps, hence the `Microsoft.Web` resource provider.

I can confirm the command does work as expected for a standard logic app that is present. Considering you are using this command; I assume you are using a standard logic app as well. Could you make sure the logic app is indeed present?

**Comment by yonzhan** [comment]
route to CXP team
