### ISSUE TITLE
az tag update on AKS node pool update the tags on the cluster not the node pool

### ISSUE THREAD

**Issue by mdufourneaud** [Azure/azure-cli#25059]
**Related command**
`az tag update --operation="merge"`

**Describe the bug**
When the resource is an AKS node pool, the command updates the tags of the cluster not those of the node pool.

**To Reproduce**
Run `az tag update` on an AKS node pool resource.

**Expected behavior**
Updates the tags of the node pool.

**Environment summary**
MSI / 2.43.0 / Windows 11 22623.1037 / PowerShell 7.3.1

**Additional context**
N/A

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@mdufourneaud The `az tag update` command is to update the tags for an ARM Resource but that isn't supported for sub resources. If you are instead trying to update the `tags` property of the node pool which applies them to VM Scale set, then you need to use the [`az aks nodepool update`](https://learn.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest#az-aks-nodepool-update) command instead.
