### ISSUE TITLE
az vmss reimage should accept multiple instance ids

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#25060]
## Describe the bug
Not sure if this should be a bug or new feature request. The VMSS Reimage API allows you to specify a list of instances to be reimaged, however CLI only allows a single instance to be reimaged. This should be updated to allow instance-ids list instead of a single instance-id

**Command Name**
`az vmss reimage`

**Errors:**
```
unrecognized arguments: batchtest_183819e2 batchtest_1cd38aa3

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss reimage -n {} -g {} --instance-id {} {} {}`

## Expected Behavior
Expected to be able to reimage multiple instances at once

## Environment Summary
```
Linux-5.4.0-1098-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.43.0

Extensions:
ai-examples 0.2.5
ml 2.11.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness
