### ISSUE TITLE
Please bump dependency on packaging to 23 or newer

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-cli#25076]
The `azure-cli-core` package has version 22 as the maximum version of `packaging` in its dependencies:

```python
'packaging>=20.9,<22.0'
```

Since the current version of `packaging` is now 23 [1], this limitation should be bumped so Linux distributions packaging the Azure CLI don't run into dependency issues.

> [1] https://pypi.org/project/packaging/

**Comment by luigiw** [comment]
+1 on this. I'm using `tox`, which has a dependency of packaging>=23. azure-cli-core is not compatible.

**Comment by bebound** [comment]
@jiasli. We only use `from packaging.version import parse`, can we upgrade it like #20661?
