### ISSUE TITLE
2.43.0 azcli - no file copy via rdp?

### ISSUE THREAD

**Issue by kgouldsk** [Azure/azure-cli#25070]
It seems like when I went from 2.42.0->2.43.0, my rdp file copy capability seems to have disappeared.  Has anyone else observed this?

F:\>az --version
azure-cli                         2.43.0

core                              2.43.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\kgould\.azure\cliextensions'

Python (Windows) 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:37:59) [MSC v.1933 32 bit (Intel)]

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by bebound** [comment]
I can't repro. This is out of CLI's scope, please check you VM and RDP client configuration.

**Comment by kgouldsk** [comment]
> I can't repro. This is out of CLI's scope, please check you VM and RDP client configuration.

Discovered a reboot is required.  
Failing at 2.43.
Downgraded ->2.42
Still failing.
Rebooted.
Copy/paste file works.
Upgraded. 2.42->2.43
Copy/paste file does not work.
Rebooted.
Copy/paste file works.

**Comment by navba-MSFT** [comment]
@kgouldsk Thanks for the update. Please let us know if any further assistance is required on this.
