### ISSUE TITLE
Found multiple accounts with the same username

### ISSUE THREAD

**Issue by jvmahesh** [Azure/azure-cli#25077]
$ az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.

Found multiple accounts with the same username 'vj884x@att.com': [{'home_account_id': '00000000-0000-0000-1701-ddd4ea1c973e.9188040d-6c67-4c5b-b112-36a304b66dad', 'environment': 'login.microsoftonline.com', 'username': 'vj884x@att.com', 'authority_type': 'MSSTS', 'local_account_id': 'mQBXzZAU64Kuvk_0ZaHcSTxFoi9cjIHIHWsgKD5N-Vo', 'realm': 'organizations'}, {'home_account_id': '56d130a3-415f-49c3-8f94-83c1894c041d.e741d71c-c6b6-47b0-803c-0f3b32b07556', 'environment': 'login.microsoftonline.com', 'username': 'vj884x@att.com', 'authority_type': 'MSSTS', 'local_account_id': '56d130a3-415f-49c3-8f94-83c1894c041d', 'realm': 'organizations'}]

Please report to us via Github: https://github.com/Azure/azure-cli/issues/20168

Due to this issue, I'm unable to complete 'az login' command to move further.

Please resolve & suggest.

**Comment by yonzhan** [comment]
duplicate with https://github.com/Azure/azure-cli/issues/20168

**Comment by jvmahesh** [comment]
What is the resolution for this issue ? Please suggest

**Comment by hamroune** [comment]
any suggestion for this issue?
