### ISSUE TITLE
az boards

### ISSUE THREAD

**Issue by ezequielramos** [Azure/azure-cli#25084]
`az boards` is returning `'boards' is misspelled or not recognized by the system.` on az 2.43.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 604e807e-d6ef-9976-27ec-b634e06b0646
* Version Independent ID: 9c5f7bd8-9f03-d8ff-f884-9d8219674baa
* Content: [Azure Boards](https://learn.microsoft.com/en-us/cli/azure/service-page/azure%20boards?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/service-page/Azure Boards.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/service-page/Azure Boards.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@ezequielramos Please install azure-devops extension (`az extension add --name azure-devops`) as this is part of azure-devops extension and then try using the command `az boards`.
