### ISSUE TITLE
az sql ltr-backup restore does not have a --service-objective-name parameter

### ISSUE THREAD

**Issue by MichaelEbert** [Azure/azure-cli#25083]
**Related command**
az sql ltr-backup restore

**Describe the bug**
az sql ltr-backup restore does not have a --service-objective-name parameter. 
Due to a service bug, this can cause issues (incorrect LicenseType) when restoring serverless databases. Additionally, this is functionality that is in az powershell that is not in the az cli. 

**To Reproduce**
az sql ltr-backup restore --service-objective-name GP_S_Gen5_2 --dest-database restoredDB --dest-resource-group rg --dest-server test-use --backup-id "<backup id string>"

**Expected behavior**
az sql ltr-backup restore should have a --service-objective-name parameter and pass it to the internal create or restore api

**Environment summary**
az console on azure

**Additional context**
Restore-AzSqlDatabase -FromLongTermRetentionBackup has a -ServiceObjectiveName parameter and it works.

**Comment by MichaelEbert** [comment]
Looks like the correct parameter might be --service-objective instead

**Comment by yonzhan** [comment]
route to CXP team

**Comment by MichaelEbert** [comment]
Fixed by #25328
