### ISSUE TITLE
az containerapp up expects container registry to be in the same subscription

### ISSUE THREAD

**Issue by Thorstensen** [Azure/azure-cli#25092]
**Related command**
```
az containerapp up --name containerAppName --registry-server myRegistry.azurecr.io \
                   --registry-user myUser --registry-password myPassword \
                   --image myRegistry.azurecr.io/myApp/backend:$(Build.BuildId)
```

**Describe the bug**
Running the command above expects that ACR is in the current subscription, even though the FQDN to ACR is provided with correct credentials. In our current set up, we have one Azure Container Registry in `Subscription Production`, but we want to create resources in `Subscription Test`

**To Reproduce**

1) Make sure that you have two subscriptions in Azure. One where the ACR is located, and one subscription where the ContainerApp should be created. 
2) Install the Azure CLI and containerapp extension by running `az extension add --name containerapp --upgrade`
3) Open you terminal of choice, and run the command above reflecting your environment. 

**Expected behavior**
The ContainerApp will be created in `Subscription Test` based on the specified image from ACR in `Subscription Production`

**Environment summary**
```
azure-cli: 2.43.0
containerapp 0.3.20
```

**Additional context**
* According to [this issue](https://github.com/Azure/azure-cli/issues/23743) the flag `--subscription` can be set, but this will also create the resources in this subscription. 
* According to [this issue](https://github.com/microsoft/azure-container-apps/issues/352#issuecomment-1226335525) it works when the image is located in DockerHub - I can not see any differences between these to image repositories.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by Thorstensen** [comment]
To elaborate: Running `az containerapp up` specifying `--registry-server` `--registry-user` and `--registry-password` result in `ERROR: The resource with name 'xyz' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription 'mySubscription (Some-guid-identifying-subscription)'.` These two resource ARE in two different subscriptions, but why does that matter when all the information above is supplied?

**Comment by SaurabhSharma-MSFT** [comment]
@Thorstensen Can you please look into [this](https://github.com/Azure/acr/issues/345) GitHub issue.  Also, refer to the below documentation if this helps to achieve what you are looking for.
- [My ACR and Webapp are in in a different subscription](https://github.com/Azure/app-service-linux-docs/tree/master/HowTo/Configure%20ACR%20with%20Managed%20Identities)

**Comment by phoenixx** [comment]
I am also seeing this exact issue. A container image from a registry in Subscription A is not accessible when attempting to use `az containerapp up` in Subscription B - I get the exact same error as above: "ERROR: The resource with name 'xyz' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription 'mySubscription (Some-guid-identifying-subscription)'."

I have been able to use Terraform (with the `azure/azapi` provider) to initially deploy the Azure Container App successfully and then `az containerapp update` to deploy new image versions, but this is far from ideal.

Is there any further information I can provide to help get to a solution?

**Comment by giovannifl** [comment]
Please repoen ths ticket again because it has not been fixed and it is still relevant

**Comment by glennsdavis** [comment]
This was working for me but is no longer not working.

1.) Using "az containerapp create" command, create container app in Subscription A from image in Azure Container Register in Subscription B.

2.) Using "az containerapp up" command, update same container app in Subscription A from image in Azure Container Register in Subscription B.

#2 now returns error "type 'Microsoft.ContainerRegistry/registries' could not be found in subscription".

**Comment by wargamez** [comment]
Why is this closed, I am having the same issue...

**Comment by abelal83** [comment]
Please reopen this issue, still hasn't been resolve. The expectation to have container registry in the same subscription as ACA is not reasonable when container registry is in most cases a shared resource between multiple environments/subscriptions.
