### ISSUE TITLE
How to pass empty value for a param that takes a string?

### ISSUE THREAD

**Issue by akhudairymicrosoft** [Azure/azure-cli#25109]
Hi,

I work in MS service bus support.

I had a very hard time trying to update a service bus queue (az servicebus queue update), as I wanted to disable a feature by passing empty value for 'forward-dead-lettered-messages-to'. It was being rejected, and I couldn't find helpful documentation on how to do it.

I ended up using powershell as following
PS C:\Users\akhudairy> $queue=Get-AzServiceBusQueue -Name testdlqforwzz -NamespaceName testnamespace -ResourceGroupName training
PS C:\Users\akhudairy> $queue.ForwardDeadLetteredMessagesTo=''
PS C:\Users\akhudairy> Set-AzServiceBusQueue -Name testdlqforwzz -NamespaceName testnamespace -ResourceGroupName training -QueueObj $queue

I hope documentation can be more clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2889060b-e555-544f-e968-34bf40efb5eb
* Version Independent ID: 70d5931b-5343-f6f8-ebf0-0e79cb0541f5
* Content: [az servicebus queue](https://learn.microsoft.com/en-us/cli/azure/servicebus/queue?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/servicebus/queue.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/servicebus/queue.yml)
* Service: **service-bus**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@akhudairymicrosoft Thanks for reaching out to us and reporting this issue. Did you try running the below command from the **cmd** bash ?

> **az servicebus queue update --resource-group MyRGName --namespace-name MyNamespace --name MyQueue--forward-dead-lettered-messages-to " " --debug**

**Comment by akhudairymicrosoft** [comment]
To be honest I couldn't find the change! maybe page cached on my side.
