### ISSUE TITLE
 The api-version '2022-03-01' is invalid error when running az webapp commands on web app

### ISSUE THREAD

**Issue by GintarasBatura** [Azure/azure-cli#25115]
**Related command**
az webapp config show --name someappservice -g /subscriptions/xxxxxxxxxxxxxx/resourceGroups/rrrrrrrr--subscription yyyyyy
az webapp config appsettings list--name someappservice -g /subscriptions/xxxxxxxxxxxxxx/resourceGroups/rrrrrrrr--subscription yyyyyy

**Describe the bug**
Here is the result:
(InvalidApiVersionParameter) The api-version '2022-03-01' is invalid. The supported versions are '2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
Code: InvalidApiVersionParameter

**To Reproduce**
Run those commands on a web app that is deployed using 
            "type": "Microsoft.Web/sites",
            "apiVersion": "2022-03-01", ...

**Expected behavior**
As per https://learn.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest

**Environment summary**
This happens in AzDO pipelines using task AzureCLI@2 and on a local machine using 
az version
{
  "azure-cli": "2.43.0",
  "azure-cli-core": "2.43.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "azure-devops": "0.25.0"
  }
}

**Comment by yonzhan** [comment]
route to CXP team

**Comment by curt-w** [comment]
I'm experiencing this within Azure Portal CLI and in my deployment scripts.

**Comment by SaurabhSharma-MSFT** [comment]
@curt-w Instead of passing the whole resourcegroup id (-g /subscriptions/xxxxxxxxxxxxxx/resourceGroups/rrrrrrrr--subscription) you need to only pass the resource group to the cmdlet like below - 

`az webapp config show --name {web app name} -g rrrrrrrr --subscription ss`

**Comment by GintarasBatura** [comment]
Indeed, using the name of the resource group instead of the full id fixes the problem for all of these az commands.  Thanks for the assistance.  So the next question is, could you fix that misleading error message?
