### ISSUE TITLE
Capturing Azure Cloud shell Web Preview URL 

### ISSUE THREAD

**Issue by Abhinavgundapaneni** [Azure/azure-cli#25112]
## Describe the bug
I am using the Azure Cloud Shell web preview option to launch my web application in cloud shell. The web preview generates a new gateway URL every time I configure a port. Is there any way to retrieve that URL from any command or something?
We are planning to store that URL in our settings file. Is there any efficient method to retrieve that URL after configuring the port.
**Command Name**
``

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Linux-5.4.0-1100-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.43.0 *

Extensions:
azure-cli-ml 1.33.0
application-insights 0.1.14
account 0.2.5
ai-examples 0.2.5
ml 2.11.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
Please provide detailed CLI commands

**Comment by navba-MSFT** [comment]
> This is not an issue with CLI. Want to know if there is any command to get the Web Preview URL.

@Abhinavgundapaneni Thanks for your reply. This repo is for Azure CLI related issues. Your ask is specific to Cloud Shell, so please create a new issue [here](https://github.com/Azure/CloudShell).
