### ISSUE TITLE
Allow disabling health probes in front door origin group

### ISSUE THREAD

**Issue by AdamJachocki** [Azure/azure-cli#25110]
**Related command**
az afd origin-group create

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to have the possibility to create origin group without health probes enabled. 

**Describe alternatives you've considered**
There is no alternative. After I create origin group using azure cli, I eventually need to login to azure portal and then disable health probes manually.

**Additional context**
When you use a service like ngrok that has limited number of requests per minute, health probes exhaust this limit quite fast. Althought timing is set to 240 seconds, for some reason health probes calls the backend constantly (when backend is not fully functional yet, and that's the big problem).

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@AdamJachocki Thanks for reaching out to us and reporting this issue. Could you please try running the below command instead as a workaround ?

> **az resource create -g myRG -n myApiApp --resource-type Microsoft.web/sites --is-full-object --properties @jsonConfigFile**

You can place the below content within your **jsonConfigFile**:

```
{
  "properties": {
    "loadBalancingSettings": {
      "sampleSize": 3,
      "successfulSamplesRequired": 3,
      "additionalLatencyInMilliseconds": 1000
    },
    "trafficRestorationTimeToHealedOrNewEndpointsInMinutes": 5
  }
}
```
This will not create the probe settings. Hope this helps.

**Comment by navba-MSFT** [comment]
@AdamJachocki I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by AdamJachocki** [comment]
Your workaround is for websites, not front door

**Comment by navba-MSFT** [comment]
@AdamJachocki My Bad. I didn't edit the command. I have edited my above comment and resending it again:

> **az resource create -g myRG -n myApiApp --resource-type Microsoft.Cdn/profiles/origingroups --is-full-object --properties @jsonConfigFile**

You can place the below content within your **jsonConfigFile**:

```
{
  "properties": {
    "loadBalancingSettings": {
      "sampleSize": 3,
      "successfulSamplesRequired": 3,
      "additionalLatencyInMilliseconds": 1000
    },
    "trafficRestorationTimeToHealedOrNewEndpointsInMinutes": 5
  }
}
```
This will not create the probe settings. Hope this helps.

**Comment by navba-MSFT** [comment]
@AdamJachocki Please let me know if you had a chance to look into this.

**Comment by AdamJachocki** [comment]
Now I get the error: "location of the resource is required"

**Comment by navba-MSFT** [comment]
@AdamJachocki Pass the --location parameter too in the above command.

> **Parameter:** --location  -l 
> Location. Values from: `az account list-locations`. You can configure the default location using `az configure --defaults location=<location>`.

**Comment by AdamJachocki** [comment]
When I do: "--location ukwest" it gives me the same error. Nevermind if the location value is in quotes or not.

**Comment by navba-MSFT** [comment]
@AdamJachocki Apologies for the late reply. I was able to get this working with the below Az CLI command. Could you please test the same and let me know if that helps ?

> **az rest --method PUT --url https://management.azure.com/subscriptions/{SUB-id}/resourceGroups/{RgName}/providers/Microsoft.Cdn/profiles/{MyFrontDoorName}/originGroups/{MyOriginName}?api-version=2021-06-01 --body @jsonConfigFile.json --debug**


**Contents of jsonConfigFile.json**
```
{
   "properties":
    {
      "loadBalancingSettings": {
      "sampleSize": 3,
      "successfulSamplesRequired": 3,
      "additionalLatencyInMilliseconds": 1000
    },
    "trafficRestorationTimeToHealedOrNewEndpointsInMinutes": 5
   }
}
```

**Comment by navba-MSFT** [comment]
@AdamJachocki I wanted to do quick follow-up to check if you had a chance to try the above workaround. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@AdamJachocki The action is currently pending on you to try the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by danielvlsc** [comment]
For deployments using bicep scripts or JSON configs, you must simply not include the `healthProbeSettings: {...}` object, which I think is exactly what @navba-MSFT is doing with the JSON configuration. Deleting it from the config after the deployment will disable the health probe as you might expect.
