### ISSUE TITLE
 az login --identity error: requests.exceptions.HTTPError

### ISSUE THREAD

**Issue by Vaisman** [Azure/azure-cli#25122]
## Describe the bug

**Command Name**
` az login --identity -u /subscriptions/<Subscr>/resourcegroups/TEST_MS/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<id>`

**Errors:**
```
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 659, in _run_job
    six.reraise(*sys.exc_info())
...
python3/dist-packages/msrestazure/azure_active_directory.py, ln 649, in get_token
    token_entry = self._retrieve_token_from_imds_with_retry(resource)
python3/dist-packages/msrestazure/azure_active_directory.py, ln 704, in _retrieve_token_from_imds_with_retry
    raise HTTPError(request=result.request, response=result.raw)
requests.exceptions.HTTPError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity -u {}`

## Environment Summary
```
Linux-5.15.0-1030-azure-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
May I know where you are running Azure CLI? As indicated by https://github.com/Azure/azure-cli/issues/15656#issuecomment-716372982, the managed identity on the VM or Azure resource should be configured properly.

Meanwhile, it looks like you are not using the official Azure CLI. See https://github.com/Azure/azure-cli/issues/19640

**Comment by Vaisman** [comment]
@jiasli I created standart Ubuntu VM in Azure, and setup cli by "sudo apt-get install azure-cli"

**Comment by Vaisman** [comment]
fixed by install CLI from https://github.com/Azure/azure-cli/issues/19640
