### ISSUE TITLE
Inline help for storage account create is incorrect

### ISSUE THREAD

**Issue by glennklockwood** [Azure/azure-cli#25125]
## Describe the bug

**Command Name**
`az storage account create`

**Errors:**
```
No errors
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage account create --name {} --resource-group {} --sku Standard_LRS --kind StorageV2 --access-tier cool`

## Expected Behavior

According to `az storage account create --help`, the section for `--access-tier` claims that `--access-tier` and `--sku Standard_LRS` should be incompatible:

> Cannot be set for StandardLRS, StandardGRS, StandardRAGRS, or PremiumLRS account types. It is required for StandardBlob accounts during creation.  Allowed values: Cool, Hot, Premium.

But this works just fine. Is the documentation wrong?  Also, is the "account type" the same as "account kind" specified using `--kind`?

## Environment Summary
```
macOS-13.1-x86_64-i386-64bit, Darwin 22.2.0
Python 3.10.7
Installer: HOMEBREW

azure-cli 2.40.0 *

Extensions:
interactive 0.4.5
account 0.2.4

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context

The inline help for `az storage account create --help` uses a lot of terminology that's inconsistent (`StandardLRS` vs `Standard_LRS`, storage account "kind" vs "type," etc.  Happy to contribute a PR to start cleaning this up if possible.

**Comment by yonzhan** [comment]
@evelyn-ys for awareness
