### ISSUE TITLE
aaz-dev-tool not generation command/code as expected. cli option for list must be backward compatible. 

### ISSUE THREAD

**Issue by KalpeshChavan12** [Azure/azure-cli#25139]
**Related command**
aaz-dev-tool not generation command/code as expected.  command option for list must be backward compatible. following are expectation generated command

az maintenance configuration create --resource-group  'log-dev-eus-rsg' --resource-name 'LinuxNonProd2'  --duration '03:55' --location 'eastus' --maintenance-scope 'InGuestPatch' --maintenance-window-recur-every '1Month Second Sunday' --maintenance-window-start-date-time '2022-07-26 00:00' --maintenance-window-time-zone 'Eastern Standard Time' --reboot-setting 'IfRequired' --visibility 'Custom' --install-patches-linux-parameters **classifications-to-include=Critical classifications-to-include=Security** --debug

Debug output:

 

cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "eastus", "properties": {"maintenanceScope": "InGuestPatch", "visibility": "Custom", "installPatches": {"rebootSetting": "IfRequired", "linuxParameters": **{"classificationsToInclude": ["Critical", "Security"]}}**, "maintenanceWindow": {"startDateTime": "2022-07-26 00:00", "duration": "03:55", "timeZone": "Eastern Standard Time", "recurEvery": "1Month Second Sunday"}}}

**Is your feature request related to a problem? Please describe.**
No, bug in code generation (must provide backward compatibility)

**Describe the solution you'd like**
Provide option to accept list in command line

**Comment by yonzhan** [comment]
Please open this issue in codegen repo
