### ISSUE TITLE
az network list-usages --location eastus -o table throws error saying Table output unavailable. However its an allowed value. Please fix the bug.

### ISSUE THREAD

**Issue by KrishnaG-MSFT** [Azure/azure-cli#25130]
az network list-usages --location eastus -o table throws error saying Table output unavailable. However its an allowed value. Please fix the bug.

<img width="492" alt="image" src="https://user-images.githubusercontent.com/45988031/212554108-d3d7fa90-b634-4fb1-a5e8-3846ffc23350.png">

<img width="592" alt="image" src="https://user-images.githubusercontent.com/45988031/212554139-63c57f3f-84d1-4960-a275-6e26ee85fc95.png">

<img width="159" alt="image" src="https://user-images.githubusercontent.com/45988031/212554160-3a47fcde-0cf0-45b4-bd73-20a825a1d3b6.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a1f75594-b95b-a85d-b971-c06e207e3fe2
* Version Independent ID: 16a09479-ff9b-9029-aae4-6ba14ccc8260
* Content: [az network](https://learn.microsoft.com/en-us/cli/azure/network?view=azure-cli-latest#az-network-list-usages)
* Content Source: [latest/docs-ref-autogen/network.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@necusjz for awareness
