### ISSUE TITLE
Clean up test failure output

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2513]
Nose prints a ton of useless garbage when a test fails. One or two failing tests cause my CMD buffer to fill up with useless VCR output and actually prevents me from see the exception that caused the failure!

1) separate the HTTP requests and responses with other logs
2) group the HTTP requests and responses with corresponding command invocation.
3) Don't print the VCR debugging--or move it to a separate file. This is only useful if you want to figure out why requests are being matched (which is usually not the issue).

__Update: per discussion with @tjprescott the requirement is changed.__

Print the command where the test fails.

**Comment by tjprescott** [comment]
@troydai please address this one as soon as practical. It's a huge headache when the live tests pass locally and the info in the logs does not help.

**Comment by mayurid** [comment]
@troydai moving to current sprint to close on this/
