### ISSUE TITLE
az functionapp deployment source config-zip not working

### ISSUE THREAD

**Issue by stmaute** [Azure/azure-cli#25140]
## Describe the bug
After creating a new function app I get the following error when deploying the zip file.
**Command Name**
`az functionapp deployment source config-zip --name test --src functions.zip --build-remote true`

**Errors:**
```
urllib3.connectionpool: Starting new HTTPS connection (1): func-6k3jj4f2efoq6.scm.azurewebsites.net:443
urllib3.connectionpool: https://func-6k3jj4f2efoq6.scm.azurewebsites.net:443 "GET /api/deployments/latest HTTP/1.1" 404 None
cli.azure.cli.command_modules.appservice.custom: Deployment status endpoint https://func-6k3jj4f2efoq6.scm.azurewebsites.net/api/deployments/latest returns malformed data. Retrying...


Another error in a different run is this one here:

urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/ae22ee6c-f6d3-4cb8-b166-729ef1156bd7/resourceGroups/weud-bosch-io-deployments/providers/Microsoft.Web/sites/weuqfcafdi2test/config/logs?api-version=2022-03-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'ETag': '"1D9299E6A6C6300"'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '9f5c03a0-92f8-4282-90c6-850a97ea1a3d'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '7e775166-d39b-4a29-b755-97701bfb2514'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'GERMANYWESTCENTRAL:20230116T113355Z:7e775166-d39b-4a29-b755-97701bfb2514'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 16 Jan 2023 11:33:55 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/ae22ee6c-f6d3-4cb8-b166-729ef1156bd7/resourceGroups/weud-bosch-io-deployments/providers/Microsoft.Web/sites/weuqfcafdi2test/config/logs","name":"logs","type":"Microsoft.Web/sites/config","location":"West Europe","properties":{"applicationLogs":{"fileSystem":{"level":"Off"},"azureTableStorage":{"level":"Off","sasUrl":null},"azureBlobStorage":{"level":"Off","sasUrl":null,"retentionInDays":null}},"httpLogs":{"fileSystem":{"retentionInMb":100,"retentionInDays":3,"enabled":true},"azureBlobStorage":{"sasUrl":null,"retentionInDays":3,"enabled":false}},"failedRequestsTracing":{"enabled":false},"detailedErrorMessages":{"enabled":false}}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 530, in enable_zip_deploy_functionapp
    return enable_zip_deploy(cmd, resource_group_name, name, src, timeout, slot)
  File "/opt/homebrew/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 568, in enable_zip_deploy
    response = _check_zip_deployment_status(cmd, resource_group_name, name, deployment_status_url,
  File "/opt/homebrew/Cellar/azure-cli/2.44.1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 3831, in _check_zip_deployment_status
    raise CLIError("Zip deployment failed. {}. Please run the command az webapp log deployment show "
knack.util.CLIError: Zip deployment failed. {'id': 'ca442000-8f69-4375-8239-25432b6e2362', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2023-01-16T11:30:57.884338Z', 'start_time': '2023-01-16T11:30:59.0072707Z', 'end_time': '2023-01-16T11:33:52.4718149Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://weuqfcafdi2test.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://weuqfcafdi2test.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'weuqfcafdi2test'}. Please run the command az webapp log deployment show -n weuqfcafdi2test -g weud-bosch-io-deployments

cli.azure.cli.core.azclierror: Zip deployment failed. {'id': 'ca442000-8f69-4375-8239-25432b6e2362', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2023-01-16T11:30:57.884338Z', 'start_time': '2023-01-16T11:30:59.0072707Z', 'end_time': '2023-01-16T11:33:52.4718149Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://weuqfcafdi2test.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://weuqfcafdi2test.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'weuqfcafdi2test'}. Please run the command az webapp log deployment show -n weuqfcafdi2test -g weud-bosch-io-deployments
az_command_data_logger: Zip deployment failed. {'id': 'ca442000-8f69-4375-8239-25432b6e2362', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2023-01-16T11:30:57.884338Z', 'start_time': '2023-01-16T11:30:59.0072707Z', 'end_time': '2023-01-16T11:33:52.4718149Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://weuqfcafdi2test.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://weuqfcafdi2test.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'weuqfcafdi2test'}. Please run the command az webapp log deployment show -n weuqfcafdi2test -g weud-bosch-io-deployments
```

## To Reproduce:
Create a new function app via Bicep template and then run the command.
`@description('The name of the Azure Function app.')
param functionAppName string = 'func-${uniqueString(resourceGroup().id)}'

@description('Storage Account type')
@allowed([
  'Standard_LRS'
  'Standard_GRS'
  'Standard_RAGRS'
])
param storageAccountType string = 'Standard_LRS'

@description('Location for all resources.')
param location string = resourceGroup().location

@description('Location for Application Insights')
param appInsightsLocation string = resourceGroup().location

var applicationInsightsName = functionAppName
var storageAccountName = '${uniqueString(resourceGroup().id)}azfunctions'

resource storageAccount 'Microsoft.Storage/storageAccounts@2022-05-01' = {
  name: storageAccountName
  location: location
  sku: {
    name: storageAccountType
  }
  kind: 'Storage'
}

resource hostingPlan 'Microsoft.Web/serverfarms@2022-03-01' = {
  name: 'WestEuropeLinuxDynamicPlan'
  location: 'West Europe'
  sku: {
    name: 'Y1'
    tier: 'Dynamic'
    size: 'Y1'
    family: 'Y'
    capacity: 0
  }
  kind: 'functionapp'
  properties: {
    perSiteScaling: false
    elasticScaleEnabled: false
    maximumElasticWorkerCount: 1
    isSpot: false
    reserved: true
    isXenon: false
    hyperV: false
    targetWorkerCount: 0
    targetWorkerSizeId: 0
    zoneRedundant: false
  }
}

resource insight 'Microsoft.Insights/components@2020-02-02' = {
  name: applicationInsightsName
  location: appInsightsLocation
  tags: {
    'hidden-link:${resourceId('Microsoft.Web/sites', applicationInsightsName)}': 'Resource'
  }
  properties: {
    Application_Type: 'web'
  }
  kind: 'web'
}

resource sites_weuqfcafditest2_name_resource 'Microsoft.Web/sites@2022-03-01' = {
  name: functionAppName
  location: 'West Europe'
  kind: 'functionapp,linux'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    enabled: true
    hostNameSslStates: [
      {
        name: '${functionAppName}.azurewebsites.net'
        sslState: 'Disabled'
        hostType: 'Standard'
      }
      {
        name: '${functionAppName}.scm.azurewebsites.net'
        sslState: 'Disabled'
        hostType: 'Repository'
      }
    ]
    serverFarmId: hostingPlan.id
    reserved: true
    isXenon: false
    hyperV: false
    vnetRouteAllEnabled: false
    vnetImagePullEnabled: false
    vnetContentShareEnabled: false
    siteConfig: {
      numberOfWorkers: 1
      linuxFxVersion: 'Python|3.8'
      acrUseManagedIdentityCreds: false
      alwaysOn: false
      http20Enabled: true
      functionAppScaleLimit: 200
      minimumElasticInstanceCount: 0
    }
    scmSiteAlsoStopped: false
    clientAffinityEnabled: false
    clientCertEnabled: false
    clientCertMode: 'Required'
    hostNamesDisabled: false
    customDomainVerificationId: '9DD40D35DCD7C0C46565E35AFC6705848C429AB82764AD0A4E83E9F0CB8B988D'
    containerSize: 0
    dailyMemoryTimeQuota: 0
    httpsOnly: false
    redundancyMode: 'None'
    storageAccountRequired: false
    keyVaultReferenceIdentity: 'SystemAssigned'
  }
}

resource sites_weuqfcafditest2_name_web 'Microsoft.Web/sites/config@2022-03-01' = {
  parent: sites_weuqfcafditest2_name_resource
  name: 'web'
  location: 'West Europe'
  properties: {
    numberOfWorkers: 1
    defaultDocuments: [
      'Default.htm'
      'Default.html'
      'Default.asp'
      'index.htm'
      'index.html'
      'iisstart.htm'
      'default.aspx'
      'index.php'
    ]
    netFrameworkVersion: 'v4.0'
    linuxFxVersion: 'Python|3.8'
    requestTracingEnabled: false
    remoteDebuggingEnabled: false
    httpLoggingEnabled: false
    acrUseManagedIdentityCreds: false
    logsDirectorySizeLimit: 35
    detailedErrorLoggingEnabled: false
    publishingUsername: '$weuqfcafditest2'
    appSettings:[
      {
        name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
        value: insight.properties.InstrumentationKey
      }
      {
        name: 'AzureWebJobsStorage'
        value: 'DefaultEndpointsProtocol=https;AccountName=${storageAccountName};AccountKey=${storageAccount.listKeys().keys[0].value};EndpointSuffix=${environment().suffixes.storage}'
      }
      {
        name: 'FUNCTIONS_WORKER_RUNTIME'
        value: 'python'  
      }
      {
        name: 'FUNCTIONS_EXTENSION_VERSION'
        value: '~4'  
      }
    ]
    scmType: 'None'
    use32BitWorkerProcess: false
    webSocketsEnabled: false
    alwaysOn: false
    managedPipelineMode: 'Integrated'
    virtualApplications: [
      {
        virtualPath: '/'
        physicalPath: 'site\\wwwroot'
        preloadEnabled: false
      }
    ]
    loadBalancing: 'LeastRequests'
    experiments: {
      rampUpRules: []
    }
    autoHealEnabled: false
    vnetRouteAllEnabled: false
    vnetPrivatePortsCount: 0
    localMySqlEnabled: false
    ipSecurityRestrictions: [
      {
        ipAddress: 'Any'
        action: 'Allow'
        priority: 2147483647
        name: 'Allow all'
        description: 'Allow all access'
      }
    ]
    scmIpSecurityRestrictions: [
      {
        ipAddress: 'Any'
        action: 'Allow'
        priority: 2147483647
        name: 'Allow all'
        description: 'Allow all access'
      }
    ]
    scmIpSecurityRestrictionsUseMain: false
    http20Enabled: true
    minTlsVersion: '1.2'
    scmMinTlsVersion: '1.2'
    ftpsState: 'AllAllowed'
    preWarmedInstanceCount: 0
    functionAppScaleLimit: 200
    functionsRuntimeScaleMonitoringEnabled: false
    minimumElasticInstanceCount: 0
    azureStorageAccounts: {
    }
  }
}
`

## Environment Summary
```
macOS-13.1-arm64-arm-64bit, Darwin 22.2.0
Python 3.10.9
Installer: HOMEBREW

azure-cli 2.44.1

Extensions:
kusto 0.5.0
datafactory 0.7.0
ssh 1.1.3
account 0.2.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by SaurabhSharma-MSFT** [comment]
@stmaute We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by stmaute** [comment]
I can provide a bit more infos regarding the issue. During an Azure Devops Pipeline run I create the function via Bicep and afterwards deploy the functions via the mentioned CLI command:

Here is the output from the last run: 
`
INFO: Running oryx build...
INFO: Running oryx build...
INFO: Running oryx build...
INFO: Running oryx build...
INFO: Running oryx build...
INFO: Running post deployment command(s)...
INFO: Writing the artifacts to a squashfs file
INFO: Writing the artifacts to a squashfs file
INFO: 
INFO: [/                                                           ]   100/15081   0%
INFO: [/                                                           ]   100/15081   0%
INFO: [/                                                           ]   100/15081   0%
INFO: [/                                                           ]   100/15081   0%
INFO: [/                                                           ]   100/15081   0%
INFO: [/                                                           ]   100/15081   0%
INFO: [/                                                           ]   100/15081   0%
INFO: [/                                                           ]   100/15081   0%
INFO: [/                                                           ]   100/15081   0%
INFO: [/                                                           ]   100/15081   0%
INFO: [-                                                           ]   200/15081   1%
INFO: [-                                                           ]   200/15081   1%
INFO: [-                                                           ]   200/15081   1%
INFO: [-                                                           ]   200/15081   1%
INFO: [-                                                           ]   200/15081   1%
INFO: [-                                                           ]   200/15081   1%
INFO: [-                                                           ]   200/15081   1%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [=====================\                                      ]  5400/15081  35%
INFO: [====================================/                       ]  9400/15081  62%
INFO: [====================================/                       ]  9400/15081  62%
INFO: [====================================/                       ]  9400/15081  62%
INFO: [====================================/                       ]  9400/15081  62%
INFO: [====================================/                       ]  9400/15081  62%
INFO: [====================================/                       ]  9400/15081  62%
INFO: [====================================/                       ]  9400/15081  62%
INFO: [==========================================-                 ] 10800/15081  71%
WARNING: Configuring default logging for the app, if not already enabled
ERROR: Zip deployment failed. {'id': '344285a9-f993-4655-afa7-09c9ceae42cf', 'status': 3, 'status_text': '', 'author_email': 'N/A', 'author': 'N/A', 'deployer': 'Push-Deployer', 'message': 'Created via a push deployment', 'progress': '', 'received_time': '2023-01-16T14:41:53.1419554Z', 'start_time': '2023-01-16T14:41:54.1948512Z', 'end_time': '2023-01-16T14:45:02.9988636Z', 'last_success_end_time': None, 'complete': True, 'active': False, 'is_temp': False, 'is_readonly': True, 'url': 'https://weuqfcafdi2test.scm.azurewebsites.net/api/deployments/latest', 'log_url': 'https://weuqfcafdi2test.scm.azurewebsites.net/api/deployments/latest/log', 'site_name': 'weuqfcafdi2test'}. Please run the command az webapp log deployment show -n weuqfcafdi2test -g weud-bosch-io-deployments
INFO: Command ran in 216.467 seconds (init: 0.264, invoke: 216.203)
`

For me it seems that the upload hasn't finished and maybe that is why the **_check_zip_deployment_status** method call is failing.

**Comment by stmaute** [comment]
It seems to be an issue when reading the AzureWebJobsStorage env variable from keyVault.
...
This is the config in my bicep file. I add it upfront and give the system identity access to get the secret from vault.
{
    name: 'AzureWebJobsStorage'
    value: '@Microsoft.KeyVault(VaultName=myKeyVault;SecretName=mySecret)'
}

When I add the storage account connection string directly the zip deployment via CLI works.
Any ideas how this can be fixed?

**Comment by SaurabhSharma-MSFT** [comment]
@stmaute Can you please refer to the below posts for configuring AzureKeyvault with the template - 

- [Use Azure Key Vault to pass secure parameter value during Bicep deployment](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/key-vault-parameter?tabs=azure-cli#grant-access-to-the-secrets)
- [Azure Bicep - Deploy Function Apps with KeyVault references](https://dev.to/dazfuller/azure-bicep-deploy-function-apps-with-keyvault-references-36o1)

**Comment by stmaute** [comment]
@SaurabhSharma-MSFT Thanks for the feedback.

Regarding the mentioned points in the two posts I don't see any misconfiguration on my side.
My service principal which is creating the resources has Owner rights on the resource group where all resources reside. So **Grant access to the secrets** should not be a problem.
I add an access policy for the functionApp with the 'GET' permission to retrieve the secret from KeyVault.
And as I already mentioned the secret is getting resolved for the **AzureWebJobsStorage** env var i the app settings. 

And I don't see any issues with the syntax for resolving the KeyVault secret in this expression:
```
{
name: 'AzureWebJobsStorage'
value: '@Microsoft.KeyVault(VaultName=myKeyVault;SecretName=mySecret)'
}
```

Do you have any other ideas how we can analyse this issue?

**Comment by SaurabhSharma-MSFT** [comment]
@stmaute I suggest you to please open a [Azure Support Ticket](https://aka.ms/azsupt) so that an engineer can check further on this issue through backend logs.

**Comment by stmaute** [comment]
@SaurabhSharma-MSFT Alright. Thanks.
