### ISSUE TITLE
Cannot specify more than 4 paths with wildcards in application gateway path-based rule settings

### ISSUE THREAD

**Issue by Abbott-fu** [Azure/azure-cli#25155]
**Related command**
az network application-gateway url-path-map rule create --gateway-name cn3-APPGW  --name testPathRule  --resource-group xincn3   --path-map-name url   --paths /scm1/* ,/eba1/* ,/file1/* ,/medias1/* ,/test1/*  --address-pool TEST

**Describe the bug**
When specifying paths with wildcards in path-based rule settings, 4 registrations were possible in the operation of the Azure Portal.
However, when creating with Azure CLI, an error occurred that only up to 3 can be created. below error message shows:
(ApplicationGatewayPathRuleWildCardCharOutofRange) The given path /scm1/* , /eba1/* , /file1/* , /medias1/* , /test1/*  in the path rule /subscriptions/3d23cdde-d7e8-4307-adcf-f50d5547e927/resourceGroups/xincn3/providers/Microsoft.Network/applicationGateways/cn3-APPGW/urlPathMaps/url/pathRules/testPathRule exceeds the max allowed wild card characters, **which is 3**
Code: ApplicationGatewayPathRuleWildCardCharOutofRange
Message: The given path /scm1/* ,/eba1/* ,/file1/* ,/medias1/* ,/test1/*  in the path rule /subscriptions/3d23cdde-d7e8-4307-adcf-f50d5547e927/resourceGroups/xincn3/providers/Microsoft.Network/applicationGateways/cn3-APPGW/urlPathMaps/url/pathRules/testPathRule exceeds the max allowed wild card characters, **which is 3**

**To Reproduce**
use **Related command** to add a url-path-map rule to application gateway

**Expected behavior**
(1)Is this limitation related to the version of AzureCLI? (The version 2.38.0，2.44.1，2.41.0，2.40.0 all has  the same issue) 
(2)Can the upper limit of this restriction (up to 3 wildcards be specified) be changed or lifted? 
(3)Is it possible to register 4 wildcards with another command or method?

**Environment summary**:
"azure-cli" version
2.44.1,
2.41.0
2.40.0 
2.38.0

application gateway version: V2

**Comment by necusjz** [comment]
`ApplicationGatewayPathRuleWildCardCharOutofRange` is an error code from service side, you can ask service team for help.

**Comment by Abbott-fu** [comment]
> `ApplicationGatewayPathRuleWildCardCharOutofRange` is an error code from service side, you can ask service team for help.

I got response from Azure support , It seems not a limited from service side. The solution is that we pass an array to --paths , then it works.
CLI CMD works: 
$urlmap='/scm2/*','/eba2/*','/file2/*','/medias2/*','/test2/*'
az network application-gateway url-path-map rule create -g xincn3 --gateway-name cn3-APPGW -n URL-rule --path-map-name url --paths $urlmap  --address-pool TEST --http-settings test

CLI CMD works( We separate paths with spaces, it works. )
az network application-gateway url-path-map rule create --gateway-name cn3-APPGW  --name testPathRule  --resource-group xincn3   --path-map-name url   --paths /scm1/*  /eba1/*  /file1/*  /medias1/*  /test1/* --address-pool TEST

Not work:
az network application-gateway url-path-map rule create --gateway-name cn3-APPGW  --name testPathRule  --resource-group xincn3   --path-map-name url   --paths /scm1/* ,/eba1/* ,/file1/* ,/medias1/* ,/test1/* --address-pool TEST

Conclusion : We need pass array to --paths
