### ISSUE TITLE
No Context for "az managedapp"

### ISSUE THREAD

**Issue by brentarias** [Azure/azure-cli#25150]
I am attempting to create and deploy my first-ever Azure Marketplace offering.  Everything I have read says that I must have the following three assets in a deployment bundle:

- mainTemplate.json (ARM file)
- createUIDefinition.json
- viewDefinition.json

However, I've just discovered the [documentation for the `az managedapp create` command](https://learn.microsoft.com/en-us/cli/azure/managedapp?view=azure-cli-latest), which seemingly doesn't require the above deployment bundle.  It makes it confusing about what is the REAL purpose of the `az managedapp create` command.  I notice that [further documentation about `az managedapp create`](https://learn.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/scripts/managed-application-define-create-cli-sample) shows a cloud shell script of contributing commands.  One of those commands, `az managedapp definition create` has a parameter `--package-file-uri` which might be referencing the deployment bundle (the documentation doesn't give sufficient clarification).  If that switch does refer to the deployment bundle, then this does make more sense...except that the `--package-file-uri` is _optional_.  Certainly the deployment bundle is not optional, so again there is a lack of clarity from the documentation.

If indeed these cli commands (e.g. `managedapp definition create`, `managedapp create`) are designed to work with the managed app "deployment bundle", then my questions are:
* Why is the switch `--package-file-uri` _optional_ for `az managedapp definition create`?
* Why does the sample script, shown in the last link above, explicitly create an Application Resource Group? Isn't that the job of the ARM template found in the deployment bundle?
* In addition to the [cloud shell sample script for `az managedapp definition create`](https://learn.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/scripts/managed-application-define-create-cli-sample), there is also an Azure [Powershell equivalent in MS documentation](https://learn.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/scripts/managed-application-powershell-sample-create-definition).  Instead of using the `az` CLI tool, the Powershell commands look like Powershell cmdlets, such as `New-AzManagedApplicationDefinition`.  The documentation doesn't explain (1) why are cmdlets being used instead of the `az` CLI tool and (2) where can I get or install these cmdlets for my desktop (assuming they have an advantage over the `az` CLI tool)?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding Service team to assist on this issue.

@MSEvanhi Could you please look into this issue ? Thanks in advance.

**Comment by MSEvanhi** [comment]
You can inline the files or pass a uri to a zip containing them.

ARM templates don't create resource groups unless you deploy one as part of the template, they are not implicit.

The cmdlet is included in the azure az cmdlet and does not need a separate installation. There is not advantage to PS vs CLI here. Ideally these documents should have explored examples for both.
