### ISSUE TITLE
CLI code generation for ContainerInstance from new swagger spec.

### ISSUE THREAD

**Issue by diyellap** [Azure/azure-cli#25167]
Hi,

As per this documentation: https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/73155/Process-Overview, raising an issue here for CLI code generation for ContainerInstance. Our new spec is 2022-10-01-preview.

**Comment by yonzhan** [comment]
Please open code generation related issue in codegen repo.

**Comment by diyellap** [comment]
> Please open code generation related issue in codegen repo.

Hi, where is codegen repo?

**Comment by yonzhan** [comment]
@kairu-ms to help with

**Comment by kairu-ms** [comment]
Hi @diyellap, do you want to add azure-cli supports for `ContainerInstance`? If it's a new APEX on boarding, please contact our PM in teams. If you want to try the swagger for azure-cli code generation. You can try [aaz-dev-tools](https://github.com/Azure/aaz-dev-tools) in your local machine.
