### ISSUE TITLE
az apim update --public-network-access doesn't work to disable public network access

### ISSUE THREAD

**Issue by AaronCoad** [Azure/azure-cli#25168]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az apim

**Describe the bug**
When running **az apim update --public-network-access false** public network access is not disabled. Looking at the documentation I saw that the logic was switched so tried **az apim update --public-network-access true** and received the same result.

**To Reproduce**
In Azure Cloud Shell or a desktop CLI of your choice, run the command **az apim update --name {apim-name} --resource-group {apim-resource-group} --public-network-access false** or **az apim update --name {apim-name} --resource-group {apim-resource-group} --public-network-access true**

**Expected behavior**
Based on the documentation (https://learn.microsoft.com/en-gb/cli/azure/apim?view=azure-cli-latest#az-apim-update) using **az apim update --name {apim-name} --resource-group {apim-resource-group} --public-network-access false** should result in public access being enabled and **az apim update --name {apim-name} --resource-group {apim-resource-group} --public-network-access true** should result in it being disabled. Whether that documentation is valid or not is another question, as the logic seems to be flipped from what would be expected.

The result should be the same as **az apim update --name {apim-name} --resource-group {apim-resource-group} --set publicNetworkAccess=Enabled** and **az apim update --name {apim-name} --resource-group {apim-resource-group} --set publicNetworkAccess=Disabled**

**Additional context**
A work around is to use the --set argument like so:

- **az apim update --name {apim-name} --resource-group {apim-resource-group} --set publicNetworkAccess=Enabled**
- **az apim update --name {apim-name} --resource-group {apim-resource-group} --set publicNetworkAccess=Disabled**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@AaronCoad The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
