### ISSUE TITLE
azcli cmdlet to update powershellVersion for a function app

### ISSUE THREAD

**Issue by Ananda-Gedela** [Azure/azure-cli#25165]
I have a old function app with the runtime env: powershell and powershellVersion: 7
I want to update it to 7.2 as the 7 is deprecating, is there any azcli cmdlet which suffice my requirement. If yes what is the cmdlet?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@Ananda-Gedela You can use the below command to update your PowerShell version to 7.2.
`az functionapp config set --name {functionappname} --resource-group {resourcegroup} --generic-configurations "{\"powerShellVersion\": \"7.2\" }"`

**Comment by Ananda-Gedela** [comment]
@SaurabhSharma-MSFT, Thank you it works for me
