### ISSUE TITLE
Problem in using az login password with special char

### ISSUE THREAD

**Issue by syedhamjath** [Azure/azure-cli#25173]
## Describe the bug

Special chars in password are not handled properly. No matter what format I use it always ends at the ')' parenthesis.

**Command Name**
``
az login --username <username> --password "+SybA?;E)UWYsn12"
az login --username <username> --password '+SybA?;E)UWYsn12'

**Errors:**
```
UWYsn12 was unexpected at this time.
C:\>  "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\\..\python.exe" -IBm azure.cli login --username <username> --password +SybA?;E)UWYsn12
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a user account and use close parenthesis char in password
- Use Az login to login to account

## Expected Behavior
Password string is not fully read, it stop till parenthesis

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.42.0 *

Extensions:
databricks 0.8.0
datafactory 0.7.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by bebound** [comment]
Try this `az login --username --password '"+SybA?;E)UWYsn12"'`

**Comment by keystroke** [comment]
In case other folks encounter this, using a password for a service principal login via azure CLI command line, and calling az commands from within a PowerShell session, you need to escape the quotes to pass to azure CLI.

Assuming you have the service principal client secret in the variable $clientSecret, you should call like this:

```PowerShell
az login --service-principal -u $clientId -p="`"$clientSecret`"" --tenant $tenantId
```

This ensures that the quotes are not stripped when PowerShell parses the arguments before passing them down to az exe / python.

**Comment by jiasli** [comment]
See https://github.com/Azure/azure-cli/issues/15529
