### ISSUE TITLE
az aks update getting error

### ISSUE THREAD

**Issue by bhanumuddhana** [Azure/azure-cli#25179]
## Describe the bug

**Command Name**
`az aks update`

**Errors:**
```
cannot import name 'UnclassifiedUserFault' from 'azure.cli.core.azclierror' (/usr/local/Cellar/azure-cli/2.13.0/libexec/lib/python3.8/site-packages/azure/cli/core/azclierror.py)
Traceback (most recent call last):
python3.8/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 553, in execute
    self.commands_loader.load_arguments(command)
...
ImportError: cannot import name 'UnclassifiedUserFault' from 'azure.cli.core.azclierror' (/usr/local/Cellar/azure-cli/2.13.0/libexec/lib/python3.8/site-packages/azure/cli/core/azclierror.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --resource-group {} --name {} --enable-local-accounts`

## Environment Summary
```
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.6
Installer: HOMEBREW

azure-cli 2.13.0 *

Extensions:
aks-preview 0.5.41

```

**Comment by PramodValavala-MSFT** [comment]
@bhanumuddhana Looks like you are using an outdated version of Azure CLI. Could you try upgrading to the latest by running `az upgrade` and try again?

**Comment by yonzhan** [comment]
route to CXP team

**Comment by bhanumuddhana** [comment]
After upgrading the cli version it worked
