### ISSUE TITLE
Add ubuntu kinetic (22.10) support

### ISSUE THREAD

**Issue by jungm** [Azure/azure-cli#25175]
**Is your feature request related to a problem? Please describe.**
Currently there is no build for the latest ubuntu interim release 22.10, though there have been builds for ubuntu iterim releases in the past. For example #21151 added support for 21.10 during its lifespan.

Due to this the [install instructions](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) are broken for ubuntu 22.10 users because the following entry is added to the apt sources:
`deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ kinetic main`

**Describe the solution you'd like**
debs being built for kinetic until it goes EOL in july.

**Describe alternatives you've considered**
The build for jammy does seem to work fine on kinetic, but this should only be a temporary solution. Especially because interim releases were supported before.

**Additional context**
https://wiki.ubuntu.com/Releases

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jungm** [comment]
Thanks for clarifying this! I'm okay with only supporting LTS releases while the current interim release is binary compatible. Maybe this is just something that needs to be documented in the [install instructions](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) in the troubleshooting guide?
