### ISSUE TITLE
`az storage account blob-service-properties update` fails when privateEndpointConnections exist as of CLI version 2.44.1

### ISSUE THREAD

**Issue by SavaNDragos** [Azure/azure-cli#25176]
### `az storage account blob-service-properties update` fails when privateEndpointConnections exists as of CLI version 2.44.1

**Related command**
az storage account blob-service-properties update `
 --resource-group $ResourceGroupName `
 --account-name $AccountName  `
 --enable-restore-policy true `
 --restore-days 30

**Describe the bug**
 ERROR: (ConflictFeatureEnabled) Conflicting feature 'privateEndpointConnections' is enabled. Please disable it and retry.

**To Reproduce**
- storage account create
- need a private endpoint on the storage account
- run the command

**Expected behavior**
The command works and those properties are set (was working in 2.43)

**Environment summary**
azure-cli                         2.44.1

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by Andrew-George-LG** [comment]
Can confirm this is an issue. Any of our storage accounts that has any private endpoints cannot have Blob Services settings updated. 

ARM template deployments fail, even if those BlobServices settings are the same as existing settings. You can repeat this error in Azure Portal by trying to change the value of the Maximum Restore Point (days ago) in the container point-in-time restore settings

![image](https://user-images.githubusercontent.com/45394629/213685791-7d853565-4bf9-4e83-a346-37083c23b143.png)

The error in the portal is 

![image](https://user-images.githubusercontent.com/45394629/213685855-11a1b05b-7961-45b3-b9cb-bdc3a2a86811.png)

**Comment by muskaanverma2** [comment]
getting "Conflicting feature 'privateEndpointConnections' is enabled. Please disable it and retry." .Didn't modified the code Although was not facing this error earlier .
Can you help in resolving this.

**Comment by cypher244** [comment]
getting "Conflicting feature 'privateEndpointConnections' is enabled. Please disable it and retry." .Didn't modified the code Although was not facing this error earlier .
Can you help in resolving this.

**Comment by Vegoo89** [comment]
This is not related to Azure CLI. I am using ARM via API calls for some resources and it started to happen today when executing ARM deployment related to storage account.

**Comment by SavaNDragos** [comment]
We had a script in terraform that was doing that call. Don't know how azure CLI actually makes the request.
In the latest version of terraform (azurerm plugin) they added the operation to update that property, we tried it and got no failure (think terraform azurerm works with the API, but not 100% certain).
Maybe this info helps.

**Comment by kpakur** [comment]
I have this problem with terraform v1.3.6 and azurerm v3.39.1. Restore policy + private endpoint on a storage account throws the error.

**Comment by Vegoo89** [comment]
Is there any update on this? It blocks all our releases atm.
