### ISSUE TITLE
Azure CLI 2.0 SAS token auth issue 

### ISSUE THREAD

**Issue by maskodnv** [Azure/azure-cli#2518]
I'm trying to use Azure CLI with SAS token but it fails with following error:
`az storage blob list --container-name test --account-name test --sas-token "?sv=XXX&ss=XXX&srt=XXX&sp=XXX&se=XXXst=XXX&spr=https&sig=XXX"`

I've also tired removing "?" but id doesn't help (using --account-key works OK)

```
usage: az storage blob list [-h] [--output {json,tsv,table,jsonc}] [--verbose]
                            [--debug] [--query JMESPATH]
                            [--num-results NUM_RESULTS]
                            [--sas-token SAS_TOKEN] [--delimiter DELIMITER]
                            [--account-key ACCOUNT_KEY] [--prefix PREFIX]
                            [--timeout TIMEOUT] --container-name
                            CONTAINER_NAME [--marker MARKER]
                            [--connection-string CONNECTION_STRING]
                            [--include INCLUDE] [--account-name ACCOUNT_NAME]
az storage blob list: error: 'AccountName'
```
But azure CLI v1.0 works fine:
`azure storage blob list --container test --account-name test --sas "?sv=XXX&ss=XXX&srt=XXX&sp=XXX&se=XXXst=XXX&spr=https&sig=XXX" `

Am I doing something wrong or is there an issue?

**Comment by tjprescott** [comment]
How are you generating the SAS token?

**Comment by maskodnv** [comment]
SAS is generated via portal.azure.com and copied. Also this token works fine with CLI 1.0

**Comment by AjayDec** [comment]
I was running into similar issue.  Using --debug option helped identify issue the sas token was quoted.   I have tested successfully with/without ? prefix. Following bash snippet, $sasQuoted shows the issue, $sas works like a charm
sasQuoted=`az storage container generate-sas --connection-string $StorageAccountConnectionString -n $ContainerName --permissions rl --expiry 'Y-m-dTH:M:SZ'`
sas=`az storage container generate-sas --connection-string $StorageAccountConnectionString -n $ContainerName --permissions rl --expiry 'Y-m-dTH:M:SZ' **--output tsv**`

**Comment by tjprescott** [comment]
@ajaydec yes, the default output format in the CLI is JSON, which will quote that string. If you need programmatic use, you should append `-o tsv`, which will result in the string not being quoted. This is the same thing you'd do if you wanted programmatic access to your connection string for example.

**Comment by williexu** [comment]
@maskodnv were you able to resolve the problem?
I'm closing this for now as `--sas-token` works perfectly on my end with a copied sas token from portal.
