### ISSUE TITLE
Service Bus Rule: custom properties 

### ISSUE THREAD

**Issue by v-Ajnava** [Azure/azure-cli#25183]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
servicebus topic subscription rule create

**Describe the bug**
no parameter to support custom properties for correlation filter

**To Reproduce**
Try to create a Service Bus rule with Correlation filter with custom properties as hash table as supported in PowerShell (-CorrelationFilterProperty)

**Expected behavior**
cmdlet should accept custom properties for correlation filter properties via parameter

**Environment summary**
checked on windows with latest CLI

**Additional context**
Example of PS cmdlet:
New-AzServiceBusRule -Name <String> -NamespaceName <String> -ResourceGroupName <String> -SubscriptionName <String> -TopicName <String> [-SubscriptionId <String>] [-ActionRequiresPreprocessing] [-ActionSqlExpression <String>] [-ContentType <String>] **[-CorrelationFilterProperty <Hashtable>]** [-CorrelationFilterRequiresPreprocessing] [-CorrelationId <String>]
    [-FilterType <FilterType>] [-Label <String>] [-MessageId <String>] [-ReplyTo <String>] [-ReplyToSessionId <String>] [-SessionId <String>] [-SqlExpression <String>] [-SqlFilterRequiresPreprocessing] [-To <String>] [-DefaultProfile <PSObject>] [-Break] [-HttpPipelineAppend <SendAsyncStep[]>] [-HttpPipelinePrepend <SendAsyncStep[]>] [-Proxy <Uri>]
    [-ProxyCredential <PSCredential>] [-ProxyUseDefaultCredentials] [-WhatIf] [-Confirm] [<CommonParameters>]

**Comment by jaganth** [comment]
New-AzServiceBusRule -NamespaceName jag-ch -ResourceGroupName Default-ServiceBus-NorthCentralUS -TopicName dlqtopic -SubscriptionName test -Name myrule3 -FilterType 'CorrelationFilter' **-CorrelationFilterProperty @{myproperty1=1; myproperty2=2}**

Need support in CLI for above PS command - specifically setting the custom properties via "CorrelationFilterProperty" flag.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Issue is assigned to @schaudhari6254888 . Removing CXP-attention label since this is not customer-reported.
