### ISSUE TITLE
Cannot list aks maintenanceconfiguration without a cluster name

### ISSUE THREAD

**Issue by SimonHarrisonSH** [Azure/azure-cli#25186]
- When a cluster is deleted, any maintenanceconfiguration associated with it is not.
- `az aks maintenanceconfiguration list` requires a cluster name.
- listing maintenance configurations on the UI does not list configurations for any clusters

This means that is is easily possible to delete a cluster, and leave an orphaned maintenanceconfiguration, which cannot be deleted (or even seen) unless you happen to know the cluster name.

The `--cluster-name` argument for `az aks maintenanceconfiguration list` should be optional, so that configurations which no longer have an associated aks cluster can still be found (and deleted)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 560b49aa-3fcc-51a1-5b72-d126712d462c
* Version Independent ID: 990a716e-67c1-585a-831c-1ef5d6a5d979
* Content: [az aks maintenanceconfiguration](https://learn.microsoft.com/en-us/cli/azure/aks/maintenanceconfiguration?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/aks/maintenanceconfiguration.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/aks/maintenanceconfiguration.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@SimonHarrisonSH We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@SimonHarrisonSH How are you creating the maintenance configuration. If you are using `az aks maintenanceconfiguration add` to create a maintenance configuration, then it will be deleted when you delete the AKS cluster.  Can you please share more details how are you validating the maintenance configuration if it's deleted or not?

**Comment by SimonHarrisonSH** [comment]
@SaurabhSharma-MSFT 
Hmm.  I was sure I'd observed the behaviour where they persisted after deletion of the cluster.

However, I cannot replicate this, so either I was mistaken or something has changed.

My apologies for the confusion
