### ISSUE TITLE
az aks check-acr error: The azure auth plugin has been removed.

### ISSUE THREAD

**Issue by Styxxy** [Azure/azure-cli#25195]
**Related command**

az aks check-acr

**Describe the bug**

When executing the command, within the Cloud Shell, I get following error:

```
error: The azure auth plugin has been removed.
Please use the https://github.com/Azure/kubelogin kubectl/client-go credential plugin instead.
See https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins for further details
The command failed with an unexpected error. Here is the traceback:
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/acs/custom.py", line 1319, in aks_check_acr
    kubectl_version = json.loads(jsonS)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**

1. Open cloud shell (Bash)
2. Run following commands:
```
az account set --subscription $SUBSCRIPTION
az aks get-credentials -g $CLUSTER_RGR -n $CLUSTER
az aks check-acr --name $CLUSTER  --resource-group $CLUSTER_RGR --acr myacr.azurecr.io
```

**Expected behavior**

I expect the command to work, and not give this error.

**Environment summary**

Cloud shell:

```$ az --version
azure-cli                         2.44.1

core                              2.44.1
telemetry                          1.0.8

Extensions:
ai-examples                        0.2.5
ml                                2.12.1
ssh                                1.1.3

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/usr/bin/python3.9'
Extensions directory '/home/hans/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Dec 15 2022, 01:12:13) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.```

**Additional context**
<!--- Add any other context about the problem here. --->

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@Styxxy We are looking into it and get back to you for any additional information.

**Comment by steven-rhodes** [comment]
I am encountering this issue repeatedly. Is there any progress?
Today I just switched clusters and encountered this issue. So here is a brief summary:
1. az aks get-credentials --name <name> --resource-group <resource group>
2. kubectl get pods -A
`error: The azure auth plugin has been removed.
Please use the https://github.com/Azure/kubelogin kubectl/client-go credential plugin instead.
See https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins for further details
`
4. az login 
5.  kubectl get pods -A
`error: The azure auth plugin has been removed.
Please use the https://github.com/Azure/kubelogin kubectl/client-go credential plugin instead.
See https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins for further details
`

6. rm -rf ~/.kube/config
 kubectl get pods -A
`error: The azure auth plugin has been removed.
Please use the https://github.com/Azure/kubelogin kubectl/client-go credential plugin instead.
See https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins for further details
`
NOTE: 
7. az aks get-credentials --name <cluster name>   --resource-group  <cluster resource group>
Merged "ah-alpha-hub-weu-b-aks" as current context in /home/srhodes/.kube/config
 kubectl get pods -A
`error: The azure auth plugin has been removed.
Please use the https://github.com/Azure/kubelogin kubectl/client-go credential plugin instead.
See https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins for further details
`

`az version
{
  "azure-cli": "2.43.0",
  "azure-cli-core": "2.43.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}

brew info kubelogin
==> azure/kubelogin/kubelogin: stable 0.0.25
A Kubernetes credential (exec) plugin implementing azure authentication
https://github.com/Azure/kubelogin
/home/linuxbrew/.linuxbrew/Cellar/kubelogin/0.0.25 (3 files, 44.7MB) *
  Built from source on 2023-01-25 at 16:31:56
From: https://github.com/azure/homebrew-kubelogin/blob/HEAD/Formula/kubelogin.rb
License: MIT
`

**Comment by akramadel** [comment]
Hi, Is there any update on this, I'm having the same issue,
In my case I'm trying to execute kubectl exec --stdin --tty

**Comment by aston93** [comment]
Hi team! I also have the same update with the same environment.
Any updates?

**Comment by yaron-idan** [comment]
Seeing the same error, will be happy to get some information on how to fix it. Thanks!

**Comment by vzburke** [comment]
Seeing this error as well. Watching...

**Comment by SaurabhSharma-MSFT** [comment]
@Styxxy I have tried this on Azure portal and on my local environment, but I am not seeing this error.
![image](https://user-images.githubusercontent.com/38112130/215857622-0f28023f-90b3-4822-b738-170edcfbdaa1.png)
**Portal:**
![image](https://user-images.githubusercontent.com/38112130/215858177-6e6dc9e1-2e7d-47d0-919c-825e4a879a90.png)

**Comment by SaurabhSharma-MSFT** [comment]
@Styxxy what's the kubectl version you are having ? 
This expected as this error message occurs with kubectl version 1.26 or greater and is due to the deprecation of the auth plugin. 
The kubelogin replacement can be downloaded from [here](https://github.com/Azure/kubelogin#getting-started).
Thanks.

**Comment by gatesry** [comment]
> @Styxxy what's the kubectl version you are having ? This expected as this error message occurs with kubectl version 1.26 or greater and is due to the deprecation of the auth plugin. The kubelogin replacement can be downloaded from [here](https://github.com/Azure/kubelogin#getting-started). Thanks.

Thanks for the link and info. Is `kubelogin` plugin supported in Cloud Shell? Or is AKS auth not supported in that environment anymore?

**Comment by SaurabhSharma-MSFT** [comment]
@gatesry I assume it can be installed on Cloud Shell as well.  [This](https://aptakube.com/blog/how-to-use-azure-kubelogin) is a third-party website, however, thought of sharing it as this blog has a really good explanation of how kubelogin is configured. Please let me know if any other questions.

**Comment by aston93** [comment]
There is something wrong with kubectl v1.26.

Please try:
- Install kubectl v1.25 and use it further
- Use your az aks get-credentials with --admin option:
_az aks get-credentials -g $CLUSTER_RGR -n $CLUSTER --admin_

Please share a comment whether solution above works for you.

**Comment by Styxxy** [comment]
Seems like cloud shell has been updated to kubectl 1.26.1 and now it works.
Tested it locally with latest 1.26.1 kubectl and it works.

Note: the download link on the kubernetes website still refers to 1.26.0 (https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/). You can download the specific version from https://dl.k8s.io/release/v1.26.1/bin/windows/amd64/kubectl.exe .

**Comment by SaurabhSharma-MSFT** [comment]
@Styxxy Thanks for the confirmation. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by mohdshine** [comment]
> kubectl 1.26.1

how we can install this version?

**Comment by steven-rhodes** [comment]
> > kubectl 1.26.1
> 
> how we can install this version?

https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

**Comment by Styxxy** [comment]
> > kubectl 1.26.1
> 
> how we can install this version?

Like I mentioned above, download directly from https://dl.k8s.io/release/v1.26.1/bin/windows/amd64/kubectl.exe (the download page still links to 1.26.0).
