### ISSUE TITLE
Error "--layered was unexpected at this time" when using IS_DEFINED in target-condition when executing "az iot edge deployment create"

### ISSUE THREAD

**Issue by emulic** [Azure/azure-cli#25203]
az version 2.28.0 * with the azure-iot extension v 0.11.0 throws error "--layered was unexpected at this time" when using IS_DEFINED function in target-condition.

Example of the command throwing this error:
`az iot edge deployment create -d "elms-metricscollector" -n "iothub-****" --priority 3 --content "C:\temp\LayeredDEployment.json" --target-condition "IS_DEFINED(tags.elms-metricssollector)" --layered`

Example of the similar command not using IS_DEFINED function in target-condition which is properly working:
`az iot edge deployment create -d "elms-metricscollector" -n "iothub-****" --priority 3 --content "C:\temp\LayeredDEployment.json" --target-condition "tags.elms-metricssollector='123'" --layered`

One more example which is properly working even when using IS_DEFINED function
`az iot edge deployment create -d "elms-metricscollector" -n "iothub-****" --priority 3 --content "C:\temp\LayeredDEployment.json" --target-condition "IS_DEFINED(tags.elms-metricssollector) AND tags.elms-metricssollector='123'" --layered`

Even this is properly working:
One more example which is properly working even when using IS_DEFINED function
`az iot edge deployment create -d "elms-metricscollector" -n "iothub-****" --priority 3 --content "C:\temp\LayeredDEployment.json" --target-condition "IS_DEFINED(tags.elms-metricssollector) AND IS_DEFINED(tags.elms-metricssollector)" --layered`

It looks like the error "--layered was unexpected at this time" occurs only when IS_DEFINED is used without any additional conditions.

Really weird for me, not understanding what is wrong there.

**Comment by SaurabhSharma-MSFT** [comment]
@emulic We are looking into it and get back to you for any additional information.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by vilit1** [comment]
I see that you are using an old version of the azure iot extension. Can you update your CLI core and iot extension?

**Comment by SaurabhSharma-MSFT** [comment]
@emulic Did you try updating your CLI core and IOT extension as mentioned above?  Please let us know if you are still having this problem.

**Comment by SaurabhSharma-MSFT** [comment]
@emulic We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
