### ISSUE TITLE
'az feedback' fails with "Your request URL is too long."

### ISSUE THREAD

**Issue by kashifilyas-ansys** [Azure/azure-cli#25204]
While trying to send feedback about a failing command, when I used `az feedback`, it opened the GitHub url which said "Your request URL is too long."

Not sure what other information can I add here.

![DeepinScreenshot_select-area_20230123113206](https://user-images.githubusercontent.com/117379593/214018590-821140c5-a762-470b-9e56-72e08db2a857.png)

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by bebound** [comment]
I guess you have a long error message so that it exceeds the GitHub URL limit.
You can create the issue manually.
