### ISSUE TITLE
Typo in az vm Help Menu

### ISSUE THREAD

**Issue by Tx0actical** [Azure/azure-cli#25201]
There seems to be a typo in the help section for ```az vm --help```.  Under the command description for ```deallocate```, the description reads : ```Deallocate ...*snip*... allocated(charged no longer apply)...*snip*```. I think they mean to say ```charges``` instead of ```charged```. Below is the screenshot :

![Issue](https://user-images.githubusercontent.com/88306361/213915699-26b548d2-5888-422d-910d-ed4ef1b4a48a.png)

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness
