### ISSUE TITLE
ERROR: Operation returned an invalid status 'Bad Request'

### ISSUE THREAD

**Issue by am8448** [Azure/azure-cli#25205]
I keep getting this error when I run "az functionapp keys list". 

I also run a "az functionapp keys set", sometimes it creates the key other times it results in the same error above and the command fails.

Several people have mentioned similar, clearly this module is not working. Will it ever be resolved?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4246edfd-394e-4d61-360b-b95173159995
* Version Independent ID: e5365558-9b77-c72f-7b6d-f42e36a0a52c
* Content: [az functionapp keys](https://learn.microsoft.com/en-us/cli/azure/functionapp/keys?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/functionapp/keys.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/functionapp/keys.yml)
* Service: **azure-functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@am8448 Thank you for reaching out to us, we are looking into it. Can you please details of your CLI version using `az versions ` command

**Comment by yonzhan** [comment]
route to CXP team

**Comment by RakeshMohanMSFT** [comment]
@am8448 We are unable to reproduce this issue at our end, with similar environment as yours (PFA screenshot)
![image](https://user-images.githubusercontent.com/49954584/214197374-7cb41ab5-d9a6-4ae7-b6d5-09b121a823e0.png)

Please share the debug trace while reproducing the issue for further troubleshooting.
you can use --debug flag in the command for the same.
