### ISSUE TITLE
add --no-wait to every start and stop command

### ISSUE THREAD

**Issue by williamohara** [Azure/azure-cli#25208]
**Related command**

`az mysql flexible-server stop`

**Is your feature request related to a problem? Please describe.**

I like to write a shell script to start and stop my azure resources. I don't like to leave my workstation running at the end of the day - so I sit there and wait for the command to finish - boring. For my AKS cluster - i use the `--no-wait` flag but I have found that it is not available for my mySQL-flexible server

**Describe the solution you'd like**
add `--no-wait` function to all resource start and stop comands

**Comment by PramodValavala-MSFT** [comment]
@williamohara Thanks for the feedback! We will review and update accordingly.

**Comment by yonzhan** [comment]
route to CXP team
