### ISSUE TITLE
'az servicebus topic subscription create' doesn't take '--is-client-affine true --is-durable false --is-shared true' parameters

### ISSUE THREAD

**Issue by ehp246** [Azure/azure-cli#25219]
The following command fails:

`az servicebus topic subscription create --resource-group xtdforce-dev --subscription XtdForce-NonProd --namespace-name sb-xtdforce-dev --topic-name auf-jms.echo.event --name simple-nd --client-id '' --is-client-affine true --is-durable false --is-shared true`

Fails:

`unrecognized arguments: --client-id --is-client-affine true --is-durable false --is-shared true`

This is on Windows:
```
PS C:\Users\yangle> az --version
azure-cli                         2.40.0
```

**Comment by PramodValavala-MSFT** [comment]
@ehp246 These parameters have been added in a newer version of Azure CLI. Upgrading to the latest by running `az upgrade` and trying again should resolve this.

**Comment by yonzhan** [comment]
route to CXP team
