### ISSUE TITLE
Add Option --hub-routing-preference

### ISSUE THREAD

**Issue by yeliMSFT** [Azure/azure-cli#25213]
### Related command

az network routeserver create --hosted-subnet
                              --name
                              --public-ip-address
                              --resource-group
                              **[--hub-routing-preference {ASPath, ExpressRoute, VpnGateway}]**
                              [--location]
                              [--tags]

az network routeserver update [--add]
                              [--allow-b2b-traffic {0, 1, f, false, n, no, t, true, y, yes}]
                              **[--hub-routing-preference {ASPath, ExpressRoute, VpnGateway}]**
                              [--force-string {0, 1, f, false, n, no, t, true, y, yes}]
                              [--ids]
                              [--name]
                              [--no-wait {0, 1, f, false, n, no, t, true, y, yes}]
                              [--remove]
                              [--resource-group]
                              [--set]
                              [--subscription]
                              [--tags]

### Resource Provider

Microsoft.Network/virtualhubs

### Description of Feature or Work Requested

We need to add an option in CLI sdk to specify Hub Routing Preference when creating/updating a route server

### Minimum API Version Required

2021-08-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/17609

### Target Date

2023-03-15

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by yeliMSFT** [comment]
Hi Cli team,

Could you please share the ETA on this task?

BR,
Yeru

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by necusjz** [comment]
@yeliMSFT Click "Milestone" in the right panel, we can see the current ETA is like:
![image](https://user-images.githubusercontent.com/12371639/217990509-27e80ae6-b0d7-4b61-adc2-d2480e23ee8e.png)

**Comment by yeliMSFT** [comment]
Hi Cli team,

Which CLI version would have this update?  Also when will the CLI reference documentation be updated with the latest command?

BR,
Yeru

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by yonzhan** [comment]
2.47.0
