### ISSUE TITLE
Performance plus property for Azure Disks update

### ISSUE THREAD

**Issue by albecker1** [Azure/azure-cli#25221]
### Related command

az disk update --performance-plus {false, true}

### Resource Provider

Microsoft.Compute/disks

### Description of Feature or Work Requested

We are implementing a new performance feature for our Standard HDD, Standard SSD and Premium SSD Azure Disks that increases the scale limits of disks sized 1 TB and larger. The feature can only be enabled and disabled while the Disk is detatched or the VM is shut down at this time.
 
Here's a related PR for the az disk create command for perfromance plus:
https://github.com/Azure/azure-cli/issues/24662

### Minimum API Version Required

2022-03-02

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/19958

### Request Example

no response

### Target Date

2023-02-07

### Additional context

none

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@albecker1 I'd like to confirm whether this feature is still in the state of private preview? If so, I will give you our test subscription, could you help register our subscription for this feature?
![image](https://user-images.githubusercontent.com/16612065/217491986-d7b2cb8c-6ba0-42d4-8724-d3061616759e.png)

**Comment by albecker1** [comment]
Hey @zhoxing-ms, yes this feature is still on private preview. Please send me your sub and I can enable it.

**Comment by wu5bocheng** [comment]
@albecker1 Thank you for your help, our subscription id is: 0b1f6471-1bf0-4dda-aec3-cb9272f09590 and the subscription name is: AzureSDKTest. If you have any questions please feel free to contact us, please let us know when you have finished adding our subscription, thanks!

**Comment by zhoxing-ms** [comment]
@albecker1 By the way, we usually do not release the private preview feature in the new official CLI version, because it may expose the confidentiality feature in advance and most users are confused because they can't use it and don't know how to register it.
So we recommend that customers use the private package built by edge build, may I ask do you think this way meets your expectations?

**Comment by wu5bocheng** [comment]
@albecker1 Thank you for opening this issue and giving us the opportunity to assist. Please make sure that `--performance-plus` property is no longer required for the `az disk update` command and please reply to me on github with the exact message if it is convenient. If the requirement is currently resolved, please close this issue and if you have further needs, feel free to contact us.

**Comment by albecker1** [comment]
Just confirming that --performance-plus property is no longer required for the az disk update command. Sorry for the confusion, but this property will not be able to be set on existing disks. Thank you all for your help!
