### ISSUE TITLE
az staticwebapp list returns Invalid Server Error

### ISSUE THREAD

**Issue by cmielke** [Azure/azure-cli#25220]
## Describe the bug
I get an Internal Server Error when I try to list static webapps for a specific subscription.

**Command Name**
`az staticwebapp list`

**Errors:**
```
Operation returned an invalid status 'Internal Server Error'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az staticwebapp list --subscription {}`

## Expected Behavior
I should get a list of static web apps.

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.44.1

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context
This does not happen for other subscriptions - only one specific subscription has this problem. I do not mind sharing the subscription ID, but was not sure if that was appropriate here.

**Comment by PramodValavala-MSFT** [comment]
@cmielke Could you run the command with the `--debug` flag and share the output here (removing any sensitive information)?

**Comment by cmielke** [comment]
I ran it with -debug but the issue seems to have fixed itself. I am no longer getting the Internal Server Error. Thanks for investigating and I think this issue can be closed.

**Comment by thomcleary** [comment]
Hi, I'm also seeing this issue with `staticwebapp` commands

eg. 
![image](https://user-images.githubusercontent.com/95324561/214473703-1eac81f1-74f8-46d2-9cdd-0d605bb5eeed.png)

Response from `--debug`
```
 Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '36'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '3d76e8da-68bf-470b-bb1c-dbe231f02c0d'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '3d76e8da-68bf-470b-bb1c-dbe231f02c0d'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'AUSTRALIASOUTHEAST:20230125T032404Z:3d76e8da-68bf-470b-bb1c-dbe231f02c0d'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 25 Jan 2023 03:24:04 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"Message":"An error has occurred."}
```

**Comment by thomcleary** [comment]
> Hi, I'm also seeing this issue with `staticwebapp` commands
> 
> eg. ![image](https://user-images.githubusercontent.com/95324561/214473703-1eac81f1-74f8-46d2-9cdd-0d605bb5eeed.png)
> 
> Response from `--debug`
> 
> ```
>  Response status: 500
> cli.azure.cli.core.sdk.policies: Response headers:
> cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Content-Length': '36'
> cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
> cli.azure.cli.core.sdk.policies:     'Expires': '-1'
> cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
> cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
> cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
> cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
> cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
> cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
> cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '3d76e8da-68bf-470b-bb1c-dbe231f02c0d'
> cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '3d76e8da-68bf-470b-bb1c-dbe231f02c0d'
> cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'AUSTRALIASOUTHEAST:20230125T032404Z:3d76e8da-68bf-470b-bb1c-dbe231f02c0d'
> cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
> cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 25 Jan 2023 03:24:04 GMT'
> cli.azure.cli.core.sdk.policies:     'Connection': 'close'
> cli.azure.cli.core.sdk.policies: Response content:
> cli.azure.cli.core.sdk.policies: {"Message":"An error has occurred."}
> ```

Seems to be working now 😄

**Comment by PramodValavala-MSFT** [comment]
@cmielke Thanks for sharing! It is likely just an intermittent issue and which is why it got resolved eventually. In most cases, you should simply be able to retry and have it work again. Closing.

**Comment by iofh** [comment]
Hi. We are still having the same issue with it being internal server error. 

Response from ` --debug` redacted sensitive information

`cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '36'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11998'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '*'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '*'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'AUSTRALIAEAST:20230126T210006Z:*'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 26 Jan 2023 21:00:06 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"Message":"An error has occurred."}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/*/providers/Microsoft.Web/staticSites?api-version=2021-03-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '*'
cli.azure.cli.core.sdk.policies:     'CommandName': 'staticwebapp list'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--query --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.38.0 (MSI) azsdk-python-azure-mgmt-web/6.1.0 Python/3.10.5 (Windows-10-10.0.22000-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Resetting dropped connection: management.azure.com
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/*/providers/Microsoft.Web/staticSites?api-version=2021-03-01 HTTP/1.1" 500 36
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '36'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '*'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '*'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'AUSTRALIAEAST:20230126T210010Z:*'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 26 Jan 2023 21:00:09 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"Message":"An error has occurred."}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/static_sites.py", line 54, in list_staticsites
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 76, in __next__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/v2021_03_01/operations/_static_sites_operations.py", line 2061, in get_next
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Internal Server Error'
Content: {"Message":"An error has occurred."}`

**Comment by iofh** [comment]
> Hi. We are still having the same issue with it being internal server error.
> 
> Response from ` --debug` redacted sensitive information
> 
> ```
> cli.azure.cli.core.sdk.policies: Response headers:
> cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Content-Length': '36'
> cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
> cli.azure.cli.core.sdk.policies:     'Expires': '-1'
> cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
> cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
> cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
> cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
> cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
> cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11998'
> cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '*'
> cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '*'
> cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'AUSTRALIAEAST:20230126T210006Z:*'
> cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
> cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 26 Jan 2023 21:00:06 GMT'
> cli.azure.cli.core.sdk.policies:     'Connection': 'close'
> cli.azure.cli.core.sdk.policies: Response content:
> cli.azure.cli.core.sdk.policies: {"Message":"An error has occurred."}
> cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/*/providers/Microsoft.Web/staticSites?api-version=2021-03-01'
> cli.azure.cli.core.sdk.policies: Request method: 'GET'
> cli.azure.cli.core.sdk.policies: Request headers:
> cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
> cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '*'
> cli.azure.cli.core.sdk.policies:     'CommandName': 'staticwebapp list'
> cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--query --debug'
> cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.38.0 (MSI) azsdk-python-azure-mgmt-web/6.1.0 Python/3.10.5 (Windows-10-10.0.22000-SP0)'
> cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
> cli.azure.cli.core.sdk.policies: Request body:
> cli.azure.cli.core.sdk.policies: This request has no body
> urllib3.connectionpool: Resetting dropped connection: management.azure.com
> urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/*/providers/Microsoft.Web/staticSites?api-version=2021-03-01 HTTP/1.1" 500 36
> cli.azure.cli.core.sdk.policies: Response status: 500
> cli.azure.cli.core.sdk.policies: Response headers:
> cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
> cli.azure.cli.core.sdk.policies:     'Content-Length': '36'
> cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
> cli.azure.cli.core.sdk.policies:     'Expires': '-1'
> cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
> cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
> cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
> cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
> cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
> cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
> cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '*'
> cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '*'
> cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'AUSTRALIAEAST:20230126T210010Z:*'
> cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
> cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 26 Jan 2023 21:00:09 GMT'
> cli.azure.cli.core.sdk.policies:     'Connection': 'close'
> cli.azure.cli.core.sdk.policies: Response content:
> cli.azure.cli.core.sdk.policies: {"Message":"An error has occurred."}
> cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
> cli.azure.cli.core.util: Traceback (most recent call last):
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/static_sites.py", line 54, in list_staticsites
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 76, in __next__
>   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/v2021_03_01/operations/_static_sites_operations.py", line 2061, in get_next
> azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Internal Server Error'
> Content: {"Message":"An error has occurred."}```
> ```

resolved
