### ISSUE TITLE
Error in: Exercise - Optimize applications across regions by using performance routing

### ISSUE THREAD

**Issue by pologoalie8908** [Azure/azure-cli#25222]
https://learn.microsoft.com/en-us/training/modules/distribute-load-with-traffic-manager/5-exercise-performance-routing 

Step 1 work fine.

Step 2 is broken.

First command is:

WestId=$(az network public-ip show \
    --resource-group learn-b2309e64-af28-41f1-8d44-d5c343ee3bb4 \
    --name westus2-vm-nic-pip \
    --query id \
    --output tsv)

Results in:

ERROR: (ResourceNotFound) The Resource 'Microsoft.Network/publicIPAddresses/westus2-vm-nic-pip' under resource group 'learn-b2309e64-af28-41f1-8d44-d5c343ee3bb4' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.Network/publicIPAddresses/westus2-vm-nic-pip' under resource group 'learn-b2309e64-af28-41f1-8d44-d5c343ee3bb4' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

Unable to complete exercise. Required University exercise.

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
@pologoalie8908 IMO, if you wanna complete this exercise, first make sure `westus2-vm-nic-pip` and `eastasia-vm-nic-pip` exist in your sandbox.

You can check it by `az network public-ip list --resource-group {}` or something like that. If it doesn't exist, one can be created by `az network public-ip create -n {} -g {}`.

**Comment by pologoalie8908** [comment]
So i figured it out....my professor isnt really the best...they linked us to unit 5 and said "start here and do these commands"....little did the teacher know, that unit 3 commands are needed to be done first.
