### ISSUE TITLE
Traffic Controller CLI Support

### ISSUE THREAD

**Issue by malpaniHMC** [Azure/azure-cli#25233]
### Resource Provider

Az.ServiceNetworking

### Description of Feature or Work Requested

Azure CLI support for a new offering, Traffic Controller. We are a creating a load balancing solution for containerized workloads (AKS). Requesting support for supporting all operations detailed by the swagger spec. 

### Minimum API Version Required

2022-10-01

### Swagger PR link / SDK link

Swagger PR link: https://github.com/Azure/azure-rest-api-specs/pull/21674
Python SDK: https://pypi.org/project/azure-mgmt-servicenetworking/1.0.0b1/

### Target Date

2022-03-15

### Additional context

Please feel free to reach out to me (@malpaniHMC), Jaishal Shah (@jaishals) or Jack Stromberg (@JackStromberg)

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by malpaniHMC** [comment]
@yonzhan @jsntcy What is the timeline for AzCLI support for our Traffic Controller resource?

**Comment by jsntcy** [comment]
@malpaniHMC, have you gone through the APEX onboarding process for Traffic Controller? If not, @Jacekey23 can help you.

**Comment by malpaniHMC** [comment]
We were able to generate the CLI for our public preview release. @JackStromberg @jaishals
