### ISSUE TITLE
"az monitor autoscale profile create" cannot run if there is existing profile created via portal with "end time" empty

### ISSUE THREAD

**Issue by daisygithuba** [Azure/azure-cli#25249]
## Describe the bug

**Command Name**
`az monitor autoscale profile create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'end'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/monitor/_exception_handler.py", line 23, in exception_handler
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/monitor/operations/autoscale_settings.py", line 255, in autoscale_profile_create
    _create_recurring_profile(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/monitor/operations/autoscale_settings.py", line 224, in _create_recurring_profile
    validate_autoscale_profile(autoscale_profile, start_time, end_time, recurrence)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/monitor/_autoscale_util.py", line 653, in validate_autoscale_profile
    profile_conflicts = [k for k, v in schedule[day].items() if _profile_is_subset(v, start, end)]
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/monitor/_autoscale_util.py", line 653, in <listcomp>
    profile_conflicts = [k for k, v in schedule[day].items() if _profile_is_subset(v, start, end)]
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/monitor/_autoscale_util.py", line 649, in _profile_is_subset
    return profile['start'] >= start and profile['end'] <= end
KeyError: 'end'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az monitor autoscale profile create -g {} --autoscale-name {} -n {} --count {} --start {} --recurrence {} {} {} {} {} {} {} {} --timezone {}`

## Environment Summary
```
Linux-5.4.0-1100-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.44.1

Extensions:
vm-repair 0.4.6
ai-examples 0.2.5
ml 2.12.1
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by wangzelin007** [comment]
@AllyW for awareness

**Comment by daisygithuba** [comment]
Hi team, I've done some tests for this error. I noticed that if there is an existing profile created via portal, which leaves the "end time" as empty, then we run az CLI command again, it will throw python error. it seems that the AZ CLI command does not allow empty vaule in "end time", please confirm.

**Comment by daisygithuba** [comment]
hi @AllyW could you help to check and update?

**Comment by AllyW** [comment]
hi @daisygithuba, yes, what you test is correct. In cli, when creating autoscale profile which already exists, if new start and end time passed in recurrences, cli will compare it with the already existed schedules to see if it conflicts, and both start and end time is needed.

**Comment by AllyW** [comment]
So either you can delete the schedule in the portal which you want to re-schedule a new recurrence in cli, or you can add start-time and end-time in portal to avoid this error.

**Comment by daisygithuba** [comment]
Hi @AllyW  thank you for the confirmation. however, since the official document specifically mentioned to leave the end time empty, "In the portal, the end time field becomes the next start time for the default profile. You can't specify the same time for the end of one profile and the start of the next. The portal will force the end time to be one minute before the start time of the following profile. During this minute, the default profile will become active. If you don't want the default profile to become active between recurring profiles, leave the end time field empty." to avoid the 1 minute gap. 

if create recurrence in cli without end time, the end time will be "23:59" as we saw in portal UI. 

therefore, it's causing confusion on the CLI /portal behavior, is there any way to update document, or  state it more clearly?

**Comment by daisygithuba** [comment]
FYI, here is the link: https://learn.microsoft.com/en-us/azure/azure-monitor/autoscale/autoscale-multiprofile?tabs=templates

**Comment by AllyW** [comment]
Hi @daisygithuba for the info gap given from portal and cli, basically it comes from the different operations about the recurrence's default start-time and end-time settings.
`Feedback` in the document page above can be used if you want to help clarify the different behavior. And for the practical operation, for now I suggest use the same route to set profile recurrence info to avoid misunderstanding. Also, cli will update code to sync the default behaviors about default time setting with portal side.

**Comment by AllyW** [comment]
And @daisygithuba thanks for practicing, testing and feedback.

**Comment by daisygithuba** [comment]
Hi @AllyW  thanks, I'll submit feedback about the document. as to "cli will update code to sync the default behaviors about default time setting with portal side." can you explain more details? is there going to be changes in the future release? 

as of now, if we do not specify "end time" in CLI command, the end time is "23:59" , is there going to be 1 minute gap between 23:59 to 00:00? what will be the auto scale behavior?

**Comment by AllyW** [comment]
hi @daisygithuba for more details about the code change, please follow the newly created issue which will be involved in our future development plan.
