### ISSUE TITLE
No way to disable survey prompt output.show_survey_link does nothing

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-cli#25242]
## Describe the bug

No matter what steps are taken, the CLI *always* displays a survey link

**Command Name**
`az config set output.show_survey_link=no`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az config set output.show_survey_link=no`
- Run any command
- Survey prompt is shown after EVERY COMMAND
```
[Survey] Help us improve Azure CLI by sharing your experience. This survey should take about 5 minutes. Run 'az survey' to open in browser. Learn more at https://go.microsoft.com/fwlink/?linkid=2203309
```

Also trying the following has no effect:

- `az config set output.show_survey_link=no=false`
- `az config set core.display_survey_message=no`
- `az config set core.display_survey_message=false`
- `export AZSURVEYMESSAGE=false`
- `export AZURE_OUTPUT_SHOW_SURVEY_LINK=false`

All of the steps documented here have no effect
https://learn.microsoft.com/en-us/cli/azure/command-line-tools-survey-guidance

## Expected Behavior

No survey prompt is shown

## Environment Summary
```
Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.44.1

Extensions:
azure-dev 0.0.1b1542059
containerapp 0.3.13
k8s-extension 1.0.4
aks-preview 0.5.118
communication 1.3.0
k8s-configuration 1.4.1

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by wangzelin007** [comment]
@jiasli for awareness

**Comment by evelyn-ys** [comment]
Please try `az config set core.survey_message=false`

**Comment by benc-uk** [comment]
> Please try `az config set core.survey_message=false`
> 
> We will update the doc soon. Thanks for your report!

Thanks @evelyn-ys This command finally worked!
