### ISSUE TITLE
keyvault secret set error

### ISSUE THREAD

**Issue by jos2491501** [Azure/azure-cli#25250]
Hello Azure CLI team,

Entering az keyvault secret set, no matter the parameters afterwards, gives a big error.

I am using Ubuntu 20.04 with both powershell and azure cli installed. I installed both on 1/26/2023. Signed into azure cli with user assigned managed identity.

**Command Name**
`az keyvault secret set`

**Errors:**
```
No module named 'azure.keyvault.v7_0'
Traceback (most recent call last):
python3/dist-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 528, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 299, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
cli/core/commands/__init__.py, ln 291, in load_arguments
    super(AzCliCommand, self).load_arguments()
...
<frozen importlib._bootstrap>, ln 961, in _find_and_load_unlocked
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
<frozen importlib._bootstrap>, ln 1014, in _gcd_import
<frozen importlib._bootstrap>, ln 991, in _find_and_load
<frozen importlib._bootstrap>, ln 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azure.keyvault.v7_0'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault secret set`

## Environment Summary
```
Linux-5.15.0-1031-azure-x86_64-with-glibc2.29
Python 3.8.10
Shell: pwsh

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by RakeshMohanMSFT** [comment]
@jos2491501 Please upgrade your azure cli version using `[az upgrade](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli)`

**Comment by jos2491501** [comment]
Yes that command worked after I reinstalled azure-cli using the installation instructions from [https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-1-install-with-one-command]

Thanks for the expert assistance.
