### ISSUE TITLE
unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-cli#25260]
Sometimes I get this error after using an Azure CLI extension on an on-premise environment:
`TypeError: unsupported operand type(s) for +: 'int' and 'str'`

This is the extension if it is required, but the error is not explicitly caused by the extension:
https://github.com/Azure/azure-cli-extensions/tree/main/src/connectedk8s

The stacktrace goes into an Azure CLI code here:
https://github.com/Azure/azure-cli/blob/d005c8fcad763d56d8dbf3da90d8e63bcba234b5/src/azure-cli-core/azure/cli/core/auth/util.py#L161
The fix for the above is to check that a string is not being added to an int for `request_time + token_entry["expires_in"]`. Could `token_entry["expires_in"]` be an empty string? This error happens once after a while, so I would imagine it is caused by token or context being refreshed. After the error happens, if I submit the command again, it moves past the error.

## Describe the bug
The error can be caused by any command that calls util.py line 161 linked above. **Again, it is not related to the command I am showing as an example!**
**Command Name**
```
az ad sp create-for-rbac -n "my-spn" --role owner --scopes "/subscriptions/<subscription ID>" --create-cert
az connectedk8s delete
```

But the error happens with `az connectedk8s connect`, and I'd imagine other extensions as well. Again, as stated above, I think this error is caused by the code in Azure CLI, not the extension. I am only putting this here because GitHub issue asked for it.

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/commands.py", line 51, in graph_err_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/custom.py", line 1173, in create_service_principal_for_rbac
    existing_sps = list(graph_client.service_principal_list(filter=query_exp))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 179, in service_principal_list
    result = self._send("GET", "/servicePrincipals" + _filter_to_query(filter))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/role/_msgrpah/_graph_client.py", line 52, in _send
    r = send_raw_request(self._cli_ctx, method, url, resource=self._resource, uri_parameters=param,
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/util.py", line 987, in send_raw_request
    token_info, _, _ = profile.get_raw_token(resource)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 383, in get_raw_token
    sdk_token = credential.get_token(*scopes)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/msal_authentication.py", line 99, in get_token
    return build_sdk_access_token(result)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/auth/util.py", line 161, in build_sdk_access_token
    return AccessToken(token_entry["access_token"], request_time + token_entry["expires_in"])
TypeError: unsupported operand type(s) for +: 'int' and 'str'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
```

## To Reproduce:
I used the connectedk8s delete command, but it happens with connect command as well. The error only happens once in a while. If it does happen, resubmitting the command again causes it to work.

- `az connectedk8s delete --name {} --resource-group {}`
- `az ad sp create-for-rbac -n "my-spn" --role owner --scopes "/subscriptions/<subscription ID>" --create-cert`

## Expected Behavior
Should not throw unsupported operand types error.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.44.0 *

Extensions:
account 0.2.5
connectedk8s 1.3.4

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context
I am using an on-premise environment.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

@akashkeshari Could you please look into this once you get a chance ?

**Comment by TheOnlyWei** [comment]
@navba-MSFT The error is likely not be related to Azure CLI extension connectedk8s since the error happened within the context and token code inside Azure CLI. The extension may be a red-herring because that's just the command I used that caused the error. Regardless, it might be a good idea to make sure you're adding integers and not integers with strings at the point where the addition operation happens.

**Comment by jiasli** [comment]
`request_time` must be an `int`:

https://github.com/Azure/azure-cli/blob/8474a10fc16b5a168f96dbbe0fd94afc8eecdf4e/src/azure-cli-core/azure/cli/core/auth/util.py#L149

It should never be cast to `str`, so https://github.com/Azure/azure-cli/pull/25566 is not correct.

When refreshing the access token, AAD returns `expires_in` as an `int`.

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/38001a4d087e5d3ec9b77f4096d52d76ab359c46/msal/oauth2cli/oauth2.py#L244

![image](https://user-images.githubusercontent.com/4003950/236421441-b7c4e3f1-1792-4408-abff-453682b89a0d.png)

Then the access token entry bubbles all the way up to

https://github.com/Azure/azure-cli/blob/21266e02457263420b62fba1c529f69e28852414/src/azure-cli-core/azure/cli/core/auth/msal_authentication.py#L69

There is no logic in MSAL or Azure CLI to convert `expires_in` to `str`.

@TheOnlyWei, are you authenticating against public Azure? The most possible reason I guess is your authentication endpoint returned `expires_in` as `str`.

**Comment by TheOnlyWei** [comment]
It was decided to fix this issue on the service side. This was caused by an edge case where we used "/adfs" ending for the login endpoint for an environment with a custom authority that is not well known in order to avoid validating instance discovery or validate authority.
