### ISSUE TITLE
[Generic Update] Not able to include equal sign (=) in the value field 

### ISSUE THREAD

**Issue by xscript** [Azure/azure-cli#2527]
A user complains that when using a generic update command to update service properties, warnings will be displayed if the value contains equal sign. Property update will be dropped.  You can refer to the following example.
```bash
>az iot hub update -n kevinzha-hub --set properties.storageEndpoints.$default.connectionString=Defau
ltEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx

Property 'connection_string=_default_endpoints_protocol=https;_account_name=xxx;_account_key' not fo
und on $default. Update may be ignored.
```

The root cause of this issue is at [line 469 of arm.py](https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/commands/arm.py#L469). `rsplit` is used to parse the key and value. This means that value field can't include equal signs.
Is this by design? If not, the input key value expression shall be parsed more carefully.
I'd like to hear opinions from you guys.
Thanks very much!

**Comment by tjprescott** [comment]
Thanks for the report @xscript!  We'll get that fixed and added to our unit tests.

I would also recommend you expose convenience arguments on your IoT update commands for your most commonly updated properties (most network commands do this currently).  This will improve the experience for your customers by letting them avoid using the generic update properties.

**Comment by xscript** [comment]
Thanks @tjprescott for your quick response!
Good suggestion about the convenience arguments.  I will discuss with our team about implementation plan.

**Comment by jaredmoo** [comment]
On top of adding a convenience parameter for storage connection string, I suggest also adding a convenience parameter for storage account name. It should be possible for you to add custom code that fetches the connection string based on the storage account name. This saves the customer from the tedious step of fetching it themselves. See https://github.com/Azure/azure-cli/pull/2536 where I'm doing something very similar.

**Comment by tjprescott** [comment]
I opened an issue #2531 to enhance these commands (since this will get closed once the bug is fixed)
