### ISSUE TITLE
acr manifest commands don't support OCI artifact for multi architectures

### ISSUE THREAD

**Issue by asgerbolet** [Azure/azure-cli#25280]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az acr manifest list -r MyRegistry -n MyRepository`
`az acr manifest show -r MyRegistry -n MyRepository@sha`

**Describe the bug**
Running the above commands results in the below error: 
 `Error: OCI index found, but accept header does not support OCI indexes. Correlation ID: 01e1ee52-1019-461f-8d72-70f8a262878e.`

**To Reproduce**

1. Build  a multi architecture "image" using docker buildx: 
```sh 
docker buildx build \
	--progress plain \
	--platform linux/amd64,linux/arm64 \
	-t ${REGISTRY}.azurecr.io/${REPOSITORY}:${MANIFEST_TAG} \
	-t ${REGISTRY}.azurecr.io/${REPOSITORY}:latest \
	--push \
	. \
```
   on 
 
   
2. This results in the following  manifest of media type `application/vnd.oci.image.index.v1+json`:
```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "manifests": [
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 3339,
      "digest": "sha256:xxx",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 3339,
      "digest": "sha256:xxx",
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 566,
      "digest": "sha256:xxx",
      "annotations": {
        "vnd.docker.reference.digest": "sha256:xxx",
        "vnd.docker.reference.type": "attestation-manifest"
      },
      "platform": {
        "architecture": "unknown",
        "os": "unknown"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 566,
      "digest": "sha256:xxx",
      "annotations": {
        "vnd.docker.reference.digest": "sha256:xxx",
        "vnd.docker.reference.type": "attestation-manifest"
      },
      "platform": {
        "architecture": "unknown",
        "os": "unknown"
      }
    }
  ]
}

```
3. Now running either of the commands from above in a bash terminal results in the error. 

**Expected behavior**

Returning the manifest, as it dose if the media type is `application/vnd.docker.distribution.manifest.list.v2+json`.

**Environment summary**

- Docker version 20.10.23, build 7155243, 
- Docker buildx version github.com/docker/buildx v0.10.0-docker 876462897612d36679153c3414f7689626251501
- az --version 
```azure-cli                         2.44.1

core                              2.44.1
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/asbol/.azure/cliextensions'

Python (Linux) 3.10.8 (main, Jan 10 2023, 15:48:34) [GCC 11.3.0]

Legal docs and information: aka.ms/AzureCliLegal
```
- Os Ubuntu 22.04
- Bash: 5.1.16(1)-release
**Additional context**

The problem seems to be related to the issue: https://github.com/Azure/azure-cli/issues/24976
However unfortunately the related pull request: https://github.com/Azure/azure-cli/pull/24977, dose not solve the problem as is should be a  part of azure-cli from version: 2.44

**Comment by yonzhan** [comment]
route to CXP team
