### ISSUE TITLE
cannot authenticate with kubelogin to my AKS

### ISSUE THREAD

**Issue by christiannobile** [Azure/azure-cli#25289]
Authentication failed
invalid_client: AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46(Microsoft Azure CLI). Resource value from request: 36bbaa94-2e54-4386-9720-76a8071fb1fa. Resource app ID: 36bbaa94-2e54-4386-9720-76a8071fb1fa. List of valid resources from app registration: . Trace ID: ab8b7fd0-5740-4bc7-a449-30f7fb201e00 Correlation ID: 650cf8ee-1446-4ff3-902e-c5fcabf2eaac Timestamp: 2023-01-30 16:46:38Z. ($error_uri)

You can log an issue at Azure CLI GitHub Repository and we will assist you in resolving it

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@christiannobile Thanks for reaching out to us and reporting this issue. 

**Cause:**
Service principals have not been setup and/or RBAC parameters have incorrect values.

**Action Plan:**
Setup the service principals up correctly: https://docs.microsoft.com/en-us/azure/aks/aad-integration#create-server-application and ensure the correct values are in the right parameters.

If parameters are wrong, then you will need to redeploy.

If the above plan doesn't help, then this issue would require a closer troubleshooting.

**Comment by navba-MSFT** [comment]
@christiannobile I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@christiannobile The action is currently pending on you to try the above suggestion. Please feel free to reopen this thread, once you are ready to resume troubleshooting on this. We would be happy to help.
