### ISSUE TITLE
Create a PR checklist to ensure completeness.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-cli#2528]
It would be nice to have a PR checklist for submitters in a similar vein to the checklist for Azure PowerShell (e.g., https://github.com/Azure/azure-powershell/pull/3466).

As a starting point, I would suggest, at a minimum:
* General:
    * Contribution guidelines.
* Tests:
    * Links to test information.
    * At least one unit test per command.
    * At least two popular scenario tests for each command.
* Documentation:
    * A meaningful description for each command added or updated.
    * A meaningful description for each parameter added or updated.
    * At least one meaningful example for each command added or updated.
* Anything else we think is a good idea to steal from Azure PowerShell.

**Comment by derekbekoe** [comment]
Also, each PR should modify the HISTORY.rst files of the changed modules with appropriate change logs.
