### ISSUE TITLE
ACR with latest CLI is not loading the Hybrid profile correctly.

### ISSUE THREAD

**Issue by rjaini** [Azure/azure-cli#25292]
ACR with latest CLI is not loading the Hybrid profile correctly.
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az acr check-name --name hybridprofile

**Describe the bug**
ACR with latest CLI is not loading the Hybrid profile correctly.

**To Reproduce**
az cloud set -n AzureCloud
az cloud unregister -n AzureStackCloud
az cloud register -n AzureStackCloud 
az cloud set -n AzureStackCloud
az cloud update --profile 2020-09-01-hybrid

One of the command ex: 
az acr check-name --name hybridprofile

**Expected behavior**
The commond should work fine.

**Environment summary**
az version
{
  "azure-cli": "2.42.0",
  "azure-cli-core": "2.42.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
**Additional context**

With portal I was able to get the correct error message

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

@toddysm, @luisdlp, @northtyphoon. Could you please look into the above issue and review this PR https://github.com/Azure/azure-cli/pull/25293  ?

**Comment by rjaini** [comment]
Fix for the issue is in the PR: https://github.com/Azure/azure-cli/pull/25293

**Comment by Wwwsylvia** [comment]
> Fix for the issue is in the PR: #25293

Hi @rjaini @navba-MSFT, are we good to close this issue given that the fix has been merged?

**Comment by navba-MSFT** [comment]
Closing this issue since the PR is merged.
