### ISSUE TITLE
storage account not deleted fully after deleting resource group

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#253]
Commands entered (replace $1 with a numeric value, I used 700):
1. az resource group create -l westus -n demo$1
2. az vm create -n Demo$1VM -g Demo$1 --ssh-key-value ~/.ssh/id_rsa.pub --authentication-type ssh --admin-username ops -l westus  --public-ip-address-type new --image UbuntuLTS --debug
3. az resource group delete -n Demo$1
4. az resource group create -l westus -n demo$1
5. az vm create -n Demo$1VM -g Demo$1 --ssh-key-value ~/.ssh/id_rsa.pub --authentication-type ssh --admin-username ops -l westus  --public-ip-address-type new --image UbuntuLTS --debug

The first VM creates fine, but the 2nd VM always produces this error during deployment:

$ az resource group deployment operation list -g demo700 -n azurecli1463011936.4874926506472
Id             : /subscriptions/af31e005-873c-49b8-820b-494b853fe01f/resourceGroups/Demo700/providers/Microsoft.Resources/deployments/azurecli1463011936.4874926506472/operations/8B44BCEEEEB18B39
Operation Id   : 8B44BCEEEEB18B39
Resource Group : Demo700
Properties     :
   Provisioning State : Failed
   Status Code        : Conflict
   Timestamp          : 2016-05-12T00:15:38.004966+00:00
   Status Message     :
      Status : Failed
      Error  :
         Code    : ResourceDeploymentFailure
         Message : The resource operation completed with terminal provisioning state 'Failed'.
         Details :
            Code    : DeploymentFailed
            Message : At least one resource deployment operation failed. Please list deployment operations for details. Please see http://aka.ms/arm-debug for usage details.
            Details :
               Code    : Conflict
               Message : {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "StorageAccountNotFound",
        "message": "Storage account vhdstorageq5o6gxi4udm64 not found. Ensure storage account is not deleted and belongs to the same Azure location as the VM."
      }
    ]
  }
}
   Target Resource    :
      Id             : /subscriptions/af31e005-873c-49b8-820b-494b853fe01f/resourceGroups/Demo700/providers/Microsoft.Resources/deployments/VMDemo700VM
      Resource Group : Demo700
      Resource Name  : VMDemo700VM
      Resource Type  : Microsoft.Resources/deployments

Id             : /subscriptions/af31e005-873c-49b8-820b-494b853fe01f/resourceGroups/Demo700/providers/Microsoft.Resources/deployments/azurecli1463011936.4874926506472/operations/FFC73FE6A65A381E
Operation Id   : FFC73FE6A65A381E
Resource Group : Demo700
Properties     :
   Provisioning State : Succeeded
   Status Code        : OK
   Status Message     : None
   Timestamp          : 2016-05-12T00:12:58.381952+00:00
   Target Resource    :
      Id             : /subscriptions/af31e005-873c-49b8-820b-494b853fe01f/resourceGroups/Demo700/providers/Microsoft.Resources/deployments/NicIpDemo700VM
      Resource Group : Demo700
      Resource Name  : NicIpDemo700VM
      Resource Type  : Microsoft.Resources/deployments

Id             : /subscriptions/af31e005-873c-49b8-820b-494b853fe01f/resourceGroups/Demo700/providers/Microsoft.Resources/deployments/azurecli1463011936.4874926506472/operations/D9289DA7993A22C7
Operation Id   : D9289DA7993A22C7
Resource Group : Demo700
Properties     :
   Provisioning State : Succeeded
   Status Code        : OK
   Status Message     : None
   Timestamp          : 2016-05-12T00:12:40.756856+00:00
   Target Resource    :
      Id             : /subscriptions/af31e005-873c-49b8-820b-494b853fe01f/resourceGroups/Demo700/providers/Microsoft.Resources/deployments/VNetDemo700VM
      Resource Group : Demo700
      Resource Name  : VNetDemo700VM
      Resource Type  : Microsoft.Resources/deployments

Id             : /subscriptions/af31e005-873c-49b8-820b-494b853fe01f/resourceGroups/Demo700/providers/Microsoft.Resources/deployments/azurecli1463011936.4874926506472/operations/3D02459E09320093
Operation Id   : 3D02459E09320093
Resource Group : Demo700
Properties     :
   Provisioning State : Succeeded
   Status Code        : OK
   Status Message     : None
   Timestamp          : 2016-05-12T00:12:58.811563+00:00
   Target Resource    :
      Id             : /subscriptions/af31e005-873c-49b8-820b-494b853fe01f/resourceGroups/Demo700/providers/Microsoft.Resources/deployments/vhdstorageq5o6gxi4udm64Demo700VM
      Resource Group : Demo700
      Resource Name  : vhdstorageq5o6gxi4udm64Demo700VM
      Resource Type  : Microsoft.Resources/deployments

Id             : /subscriptions/af31e005-873c-49b8-820b-494b853fe01f/resourceGroups/Demo700/providers/Microsoft.Resources/deployments/azurecli1463011936.4874926506472/operations/08587385949471946538
Operation Id   : 08587385949471946538
Resource Group : Demo700
Properties     :
   Provisioning State : Failed
   Status Code        : Conflict
   Status Message     : Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see http://aka.ms/arm-debug for usage details.
   Target Resource    : None
   Timestamp          : 2016-05-12T00:15:38.338702+00:00

**Comment by yugangw-msft** [comment]
No actionable item at our side

**Comment by se7enack** [comment]
Azure is in deprovisioning state and cannot perform any operation.
