### ISSUE TITLE
Support `--destination-blob-type` and `--tier` on `az storage blob copy start-batch`

### ISSUE THREAD

**Issue by maskati** [Azure/azure-cli#25305]
**Related command**
`az storage blob copy start-batch`

**Is your feature request related to a problem? Please describe.**
[az storage blob copy start](https://learn.microsoft.com/en-us/cli/azure/storage/blob/copy?view=azure-cli-latest#az-storage-blob-copy-start) now supports `--destination-blob-type` and `--tier` for [blob type and tier conversion](https://learn.microsoft.com/en-us/azure/storage/blobs/convert-append-and-page-blobs-to-block-blobs?tabs=azure-cli). This functionality is missing from [az storage blob copy start-batch](https://learn.microsoft.com/en-us/cli/azure/storage/blob/copy?view=azure-cli-latest#az-storage-blob-copy-start-batch).

**Describe the solution you'd like**
Add the same support to `az storage blob copy start-batch`.

**Describe alternatives you've considered**
Enumerate and copy.

**Comment by yonzhan** [comment]
storage feature ask
