### ISSUE TITLE
az command error

### ISSUE THREAD

**Issue by moritaango** [Azure/azure-cli#25300]
When I do "az login " command on PowerShell(x64), this error occurs every time.

The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x05F7F520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

please tell me how to remove this

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by moritaango** [comment]
Now, I'm working under proxy environment. I think this is reason error occurs.
So, I'd like to know how to set proxy setting for connecting to the internet from power shell.

**Comment by bebound** [comment]
It's quite similar to #21514
Please make sure `nslookup login.microsoftonline.com` works.
For proxy settings, you can check this doc: https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#work-behind-a-proxy

**Comment by ang0215** [comment]
The environment variables "HTTP_PROXY","HTTPS_PROXY" are the url given by the company, I can access the internet from chrome or other browsers.
Also, when installing extensions in VScode, XHR fails to install, and I am not able to install, and this may be the same cause, so I am sharing this in case you are interested.
