### ISSUE TITLE
az account list-locations does not provide "ExtendedLocation" option per swagger spec

### ISSUE THREAD

**Issue by viananth** [Azure/azure-cli#25309]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
 az account list-locations

**Describe the bug**

Per Swagger spec, "list locations" should provide "includeExtendedLocations" parameter to list EdgeZones as part of the response.

**Ref**:
GET https://management.azure.com/subscriptions/<subscriotionId>/locations?api-version=2021-04-01&includeExtendedLocations=true
Authorization: Bearer <Redacted>

**To Reproduce**

**Expected behavior**

az account list-locations should provide a parameter "includeExtendedLocatios" and should list the EdgeZones as part of the response.

**Environment summary**

Cloud shell.

PS /home/vishnu> az -v                                                                                              azure-cli                         2.44.1                                           

core                              2.44.1
telemetry                          1.0.8

Extensions:
ai-examples                        0.2.5
ml                                2.12.1
ssh                                1.1.3

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/usr/bin/python3.9'
Extensions directory '/home/vishnu/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Dec 15 2022, 01:12:13) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

**Additional context**

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
> Per Swagger spec, "list locations" should provide "includeExtendedLocations" parameter to list EdgeZones as part of the response.

Could you please provide the source of this statement?

I searched for `includeExtendedLocatios` in the swagger repo but didn't see any result: 

https://github.com/Azure/azure-rest-api-specs/search?q=includeExtendedLocatios

![image](https://user-images.githubusercontent.com/4003950/215937654-7e0e82fe-65c5-40ea-ba29-8e0000b5c74c.png)

The swagger for `2021-04-01` API is https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2021-04-01/resources.json

Public documentation of **Subscriptions - List Locations** REST API also has no reference regarding `includeExtendedLocatios`.

https://learn.microsoft.com/en-us/rest/api/resources/subscriptions/list-locations

![image](https://user-images.githubusercontent.com/4003950/215937870-4e8f8709-2741-4197-b699-f092c59f184c.png)

But I do see Azure PowerShell has a similar argument `-ExtendedLocation` from `Get-AzLocation`: https://learn.microsoft.com/en-us/powershell/module/az.resources/get-azlocation?view=azps-9.3.0#-extendedlocation

**Comment by jiasli** [comment]
Ops, apparently, I was looking for the wrong "droid" `includeExtendedLocatios`. It should be `includeExtendedLocations`. (I was just copy-and-pasting without checking).

The only place I see `includeExtendedLocations` is in `2021-01-01`:

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2021-01-01/subscriptions.json#L53

But the API version you provided is `2021-04-01`. Could you please confirm which one is correct?

BTW, the document https://learn.microsoft.com/en-us/rest/api/resources/subscriptions/list-locations is still for `2020-01-01`, which is certainly lagging behind the swagger. I have created an issue to track it:

- https://github.com/Azure/azure-rest-api-specs/issues/22399

**Comment by viananth** [comment]
Hi @jiasli , is there any update on this issue? Any plans on when this is getting fixed?

**Comment by viananth** [comment]
Verified this issue is fixed with az version 2.56.0.
 az account list-locations --include-extended-locations true

**Comment by jiasli** [comment]
`az account list-locations` was moved from `profile` command module to `resource` command module and it supported `--include-extended-locations` at the same time: https://github.com/Azure/azure-cli/pull/27400.
