### ISSUE TITLE
I'm trying to assign a role for my AKS service, but I received the error stating "Cannot find user or service principal"

### ISSUE THREAD

**Issue by Varunr1995** [Azure/azure-cli#25303]
I'm trying to assign a role for my AKS service, but I received the error stating "Cannot find user or service principal in graph database for '"683228cf-85b2-4866-a3bc-49c0af07dfd6"'. If the assignee is an appId, make sure the corresponding service principal is created with 'az ad sp create --id "683228cf-85b2-4866-a3bc-49c0af07dfd6"'.

Even though I created ACR first and created AKS later, issue is still there. Below you can find the configuration I provided through Azure.ps1 & Dependencies in JSON.

**Azure.ps1**

role {
            switch( $config.azure.resourceGroups[$resourceGroupIndex].objects[$objectIndex].assigneeType ) {
                aksPool {
                    $assigneeId=az aks show -g $config.azure.resourceGroups[$resourceGroupIndex].objects[$objectIndex].assigneeResourceGroup `
                        --name $config.azure.resourceGroups[$resourceGroupIndex].objects[$objectIndex].assigneeName --query "identityProfile.kubeletidentity.objectId"
                }
                default {
                    "Unknown assignee type: $($config.azure.resourceGroups[$resourceGroupIndex].objects[$objectIndex].assigneeType)"
                    exit
                }
            }
            "Assignee ID is $assigneeId"
            switch( $config.azure.resourceGroups[$resourceGroupIndex].objects[$objectIndex].scopeType ) {
                acr {
                    $scopeId=az acr show -g $config.azure.resourceGroups[$resourceGroupIndex].objects[$objectIndex].scopeResourceGroup `
                        --name $config.azure.resourceGroups[$resourceGroupIndex].objects[$objectIndex].scopeName --query id
                }
                default {
                    "Unknown scope type: $($config.azure.resourceGroups[$resourceGroupIndex].objects[$objectIndex].scopeType)"
                    exit
                }
            }
            "Scope ID is $scopeId"
            az role assignment create --role $config.azure.resourceGroups[$resourceGroupIndex].objects[$objectIndex].role --assignee $assigneeId --scope $scopeId
            if( -not $? ) {
                "Unable to assign role"
                exit
            }
            "Role has been assigned"
            return
        }

**azure.json**

{
    "objectType": "role",
    "name": "",
    "role": "AcrPull",
    "assigneeType": "aksPool",
    "assigneeName": "aksNonProd01",
    "assigneeResourceGroup": "HawkVisumWebsiteNONPROD",
    "scopeType": "acr",
    "scopeName": "officewebsitecontainer",
    "scopeResourceGroup": "HawkVisumWebsiteNONPROD"
}

All other services are successfully created, in the image below you can see the output.
<img width="1262" alt="Screenshot 2023-01-31 at 5 18 45 PM" src="https://user-images.githubusercontent.com/59080666/215751992-18c0b867-cf45-483f-ac3d-aeca614618de.png">

I feel that something is missed from my end, so the error is popping up. I look forward to hear valuable inputs from the community.

**Comment by yonzhan** [comment]
route to CXP team
