### ISSUE TITLE
Progress bar written to stderr despite being disabled

### ISSUE THREAD

**Issue by philphilphil** [Azure/azure-cli#25318]
## Describe the bug
Despite having `core.disable_progress_bar` set to true and using the `--only-show-errors` flag, the progress bar is displayed and is writing to stderr, causing a automation to fail.

Related to: #19365 and #19464

**Command Name**
`az storage blob download`

**Errors:**
Progress bar is written to stderr

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.
- `az storage blob download --account-name {} --auth-mode {} --account-key {} --container-name {} --name {} --file {} --only-show-errors`

## Expected Behavior
Progress bar should not be written to stderr.

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.44.1
```

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by MoChilia** [comment]
Hi @philphilphil! You can use the parameter `--no-progress` in `az storage blob download` to disable the process bar.  The parameter `only-show-errors` is not specifically designed to disable the process bar. The code logic of it doesn't apply to this command.
