### ISSUE TITLE
[IoT] Add convenience arguments for hub/device update

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2531]
Generic update is intended as a stopgap for new functionality and for advanced scenarios. The `iot hub update` and `iot device update` commands should expose convenience arguments for the most commonly updated parameters. This will improve the customer experience.

See https://github.com/Azure/azure-cli/blob/master/doc/authoring_command_modules/authoring_commands.md#generic-update-commands
 for more info.

**Comment by jlian** [comment]
Feature request

**Comment by jlian** [comment]
Created item to target Nov this year https://msazure.visualstudio.com/One/_workitems/edit/4979134
