### ISSUE TITLE
Does Azure CLI 2.0 support AzureUSGovernment environment?

### ISSUE THREAD

**Issue by tumtum73** [Azure/azure-cli#2532]
In the old CLI there was a --environment parameter that allowed us to connect to other Azure environments like AzureUSGovernment.  How can we do this with Azure CLI 2.0 if possible?

**Comment by derekbekoe** [comment]
@tumtum73 it's
 ```
$ az cloud set --name AzureUSGovernmen
$ az login

```

**Comment by tumtum73** [comment]
Awesome and quick response, I actually found it right after posting this question.  

[https://github.com/Azure/azure-cli/issues/2190](https://github.com/Azure/azure-cli/issues/2190)


Thanks,
Steve
