### ISSUE TITLE
Docs: Specify firewall-rule name requirements fully

### ISSUE THREAD

**Issue by dylan8902** [Azure/azure-cli#25337]
A firewall-rule appears to have a requirement of a minimum length of 3 characters. This should be made clear in the documentation and error message like it is for server name in same command

```
az mysql flexible-server firewall-rule create -g blinky -n blinky-mysql -r ci --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.1
The firewall rule name can only contain 0-9, a-z, A-Z, '-' and '_' and the name cannot exceed 126 characters. 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c994dbd-d36d-e94f-7ac8-942f148b3d82
* Version Independent ID: 878609e1-51d9-9740-a5d0-c7b2c6fac69a
* Content: [az mysql flexible-server firewall-rule](https://learn.microsoft.com/en-us/cli/azure/mysql/flexible-server/firewall-rule?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/mysql/flexible-server/firewall-rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/mysql/flexible-server/firewall-rule.yml)
* Service: **mysql**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by dylan8902** [comment]
The validation is here: https://github.com/Azure/azure-cli/blob/main/src/azure-cli/azure/cli/command_modules/rdbms/validators.py#L477

**Comment by PramodValavala-MSFT** [comment]
@dylan8902 Thanks for catching that! We have worked up a PR to address this.

**Comment by dylan8902** [comment]
Nice one cheers @PramodValavala-MSFT - I'd had a go but too slow getting the az-cli tests to run locally. You have found lots more places to update it too which is great thanks

**Comment by PramodValavala-MSFT** [comment]
@dylan8902 Glad I could help! In the future, you should be able to just run tests for a particular module. So in this case, you would just run

```sh
azdev test rdbms
```

**Comment by yonzhan** [comment]
route to CXP team
