### ISSUE TITLE
Functions v3 has reached EOL -- Remove support to create v3 function apps 

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-cli#25340]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

[Functions v3 has reached EOL](https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=v4&pivots=programming-language-csharp). Remove the ability to create v3 function apps.

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding the Service team to look into this.

**Comment by kamperiadis** [comment]
Closing as it has been addressed
