### ISSUE TITLE
missing cdn frontdoor identity settings

### ISSUE THREAD

**Issue by AlmirKadric** [Azure/azure-cli#25343]
**Related command**
az afd profile create

**Describe the bug**
The webconsole has support to attach an identity to an Azure Frontdoor resource (system assigned or user assigned), however the CLI does not support this.

**To Reproduce**
Create Azure Frontdoor profile using CLI
There is no command to attach an identity

**Expected behavior**
An additional command or argument for the afd profile create command exists which allows an identity to be attached

**Environment summary**
Windows Chocolatey

**Additional context**
Ultimately I want to get this added into terraform to manage this all from code

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@AlmirKadric Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@AlmirKadric Could you please let me know if either of the below command helps ? Awaiting your reply.

> **az resource update --ids <frontdoor_resource_id> --set identity.type=SystemAssigned**

> **az resource update  --ids <frontdoor_resource_id> --set identity="{\"type\": \"UserAssigned\", \"userAssignedIdentities\": {\"/subscriptions/XXXXX/resourceGroups/MyRgName/providers/Microsoft.ManagedIdentity/userAssignedIdentities/MyUserAssignedmi\": {}}}"**

**Comment by navba-MSFT** [comment]
@AlmirKadric I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@AlmirKadric The action is currently pending on you to try the above suggested CLI command. Please feel free to reopen this issue, if you need any further assistance on this issue in future. We would be happy to help.

**Comment by sanjaydebnath** [comment]
@navba-MSFT This throws exception as "(BadRequest) Property Identity is not allowed to set in current API Version". My current az versions are

```csharp
{
  "azure-cli": "2.45.0",
  "azure-cli-core": "2.45.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5",
    "aks-preview": "0.5.129",
    "application-insights": "0.1.18",
    "azure-firewall": "0.14.4",
    "bastion": "0.2.2",
    "cosmosdb-preview": "0.22.0",
    "front-door": "1.0.17",
    "kusto": "0.5.0",
    "ssh": "1.1.3"
  }
}
```

![image](https://user-images.githubusercontent.com/28987981/222255095-8694a657-b529-464a-8eb8-c8472ccb1607.png)

Not able to set identity to AFD via az cli is a blocker to automate end to end deployment ideally.

**Comment by t-bzhan** [comment]
> @navba-MSFT This throws exception as "(BadRequest) Property Identity is not allowed to set in current API Version". My current az versions are
> 
> ```cs
> {
>   "azure-cli": "2.45.0",
>   "azure-cli-core": "2.45.0",
>   "azure-cli-telemetry": "1.0.8",
>   "extensions": {
>     "account": "0.2.5",
>     "aks-preview": "0.5.129",
>     "application-insights": "0.1.18",
>     "azure-firewall": "0.14.4",
>     "bastion": "0.2.2",
>     "cosmosdb-preview": "0.22.0",
>     "front-door": "1.0.17",
>     "kusto": "0.5.0",
>     "ssh": "1.1.3"
>   }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/28987981/222255095-8694a657-b529-464a-8eb8-c8472ccb1607.png)
> 
> Not able to set identity to AFD via az cli is a blocker to automate end to end deployment ideally.

Set the --api-version parameter explicitly should address that, as explained in https://github.com/Azure/azure-cli/issues/25634, front door rest API support managed identity from version "2022-11-01-preview".

`az resource update --ids /subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourcegroups/bogroup/providers/Microsoft.Cdn/profiles/boprofile101 --set identity.type=SystemAssigned --api-version 2022-11-01-preview --debug`
