### ISSUE TITLE
az vm not working

### ISSUE THREAD

**Issue by ThomaswOC** [Azure/azure-cli#25348]
## Describe the bug

**Command Name**
`az ssh vm`

**Errors:**
```
No module named 'azure.cli.core.style'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-o2uit6zy\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 553, in execute
azure\cli\core\__init__.py, ln 478, in load_arguments
cli\core\commands\__init__.py, ln 310, in load_arguments
Temp\pip-unpacked-wheel-o2uit6zy\knack\commands.py, ln 106, in load_arguments
azure\cli\core\__init__.py, ln 787, in default_arguments_loader
azure\cli\core\__init__.py, ln 827, in get_op_handler
...
<frozen importlib._bootstrap>, ln 665, in _load_unlocked
<frozen importlib._bootstrap_external>, ln 678, in exec_module
<frozen importlib._bootstrap>, ln 219, in _call_with_frames_removed
cliextensions\ssh\azext_ssh\custom.py, ln 17, in <module>
    from azure.cli.core.style import Style, print_styled_text
ModuleNotFoundError: No module named 'azure.cli.core.style'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ssh vm --ip {}`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.14.2 *

Extensions:
ssh 1.1.3

```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@ThomaswOC Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@ThomaswOC I see that you are using a very old version of Azure CLI. Could you please update your AzCLI to the [most recent version](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli) and test the above command again ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ThomaswOC I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ThomaswOC The action is currently pending on you to try upgrading your AzCLI and running the command again. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
