### ISSUE TITLE
Unable to authenticate to Azure China Portal

### ISSUE THREAD

**Issue by brenthu** [Azure/azure-cli#25358]
Authentication failed
invalid_resource: AADSTS500011: The resource principal named https://management.core.windows.net/ was not found in the tenant named xxx. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: c8265a59-52af-4e06-8540-46ca7c443c00 Correlation ID: 9e9223f9-f49b-4618-89c3-fe1480a0d364 Timestamp: 2023-02-06 07:29:31Z. (https://login.partner.microsoftonline.cn/error?code=500011)

You can log an issue at [Azure CLI GitHub Repository](https://github.com/azure/azure-cli/issues) and we will assist you in resolving it.

**Comment by yonzhan** [comment]
Please let me know more details which CLI command you used and where you met with this issue.

**Comment by brenthu** [comment]
> When I run below command, azure China portal promoted to authenticate, and type subscription owner credentials, and got the error message.

.\AzureResourceInventory.ps1 -TenantID "xxxxxxxx-8624-42f8-b58f-8d21727a29cf"

**Comment by yonzhan** [comment]
This is not related to Azure CLI command, right? Maybe you can create this issue in Azure PowerShell repo.
