### ISSUE TITLE
Create a function app with location Sweden Central doesn't create a consumption plan correctly

### ISSUE THREAD

**Issue by magsto** [Azure/azure-cli#25364]
**Related command**
`az functionapp create --name myFunction --resource-group myRg --consumption-plan-location swedencentral --storage-account mystorage --functions-version 4 --runtime-version 7--os-type Windows --runtime dotnet-isolated --https-only true`

**Describe the bug**
According to the [documentation](https://learn.microsoft.com/en-us/azure/azure-functions/scripts/functions-cli-create-serverless#run-the-script) a **consumption app service plan** should be auto-generated with the above command. However this does not work in the region **Sweden Central**.

If I try to run the above command but choose West Europe as location for the resource group, the storage account and the function app - then it does work as expected.

**To Reproduce**
Create:
- A resource group in location: swedencentral
- A storage account in location: swedencentral
- An isolated functionapp with --consumption-plan-location swedencentral (as specified above)

**Expected behavior**
A consumption plan with location swedencentral should be created automatically with the created function in the same resource group.

**Additional context**
If, after the creation, I go to the created function and selected to view _App Service Plan_ in the left portal menu, I get an error message saying that the plan "SwedenCentralPlan" is missing. It seems that a plan may have been created during the process and/or an URI has been created but then removed or similar.

Also, it is possible to create a function in swedencentral in the portal wizard, then a consumption plan is created as expected. But it is not possible with cli commands.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by magsto** [comment]
After recreating this problem once more I have submitted a support request in the portal with diagnostic permission granted as well with id: 2302080050003537 if that is accessible for you. (@SaurabhSharma-MSFT)

**Comment by SaurabhSharma-MSFT** [comment]
@magsto I am not able to reproduce this issue and able to create Azure Functions App in Sweden central.
![image](https://user-images.githubusercontent.com/38112130/217618016-4c49f5f3-72c9-4a8e-90a5-def607cc05b3.png)
Sorry, but I don't have access look into to the support case.  Please work with support to know the actual root cause.  
Please let me know if you have any other questions.

**Comment by SaurabhSharma-MSFT** [comment]
@magsto I am getting error while creating the function app from portal and it is throwing the below quota error.
![image](https://user-images.githubusercontent.com/38112130/217627999-8a982208-2573-47a2-9918-e0c3c2ecf0c1.png)
I believe I am not able to create the function app properly because of this.  
Can you please check if you are able to create the function app for SwedenCentral in your current subscription.

**Comment by magsto** [comment]
> 

Yes, that is the error I get. I now have an ongoing conversation with the Azure support team, they have reproduced and confirmed the problem. They will escalate and respond me within 24-48 h how this is proceeding.

**Comment by magsto** [comment]
> @magsto I am getting error while creating the function app from portal and it is throwing the below quota error.
> ![image](https://user-images.githubusercontent.com/38112130/217627999-8a982208-2573-47a2-9918-e0c3c2ecf0c1.png)
> I believe I am not able to create the function app properly because of this.
> Can you please check if you are able to create the function app for SwedenCentral in your current subscription.

Yes, I can create it in my subscription (the problem still persist however). I will update here when I have more answers from Azure support team. Thanks for the effort you did!

**Comment by SaurabhSharma-MSFT** [comment]
@magsto Following up to check if you are unblocked on this.

**Comment by magsto** [comment]
> 

@SaurabhSharma-MSFT The ticket is still open with the Azure support team. The problem is acknowledged and will be escalated to the Application Team. I'm waiting for the next step or resolution.

**Comment by SaurabhSharma-MSFT** [comment]
@magsto Sure, thank you for the updates.

**Comment by SaurabhSharma-MSFT** [comment]
@magsto Just checking in if your issue is resolved.

**Comment by magsto** [comment]
@SaurabhSharma-MSFT Yes, the issue were solved by Azure support a few days ago. It was a configuration problem with the location Sweden Central that is fixed now.
