### ISSUE TITLE
No documentation for specifying "anyof" conditions for "az monitor activity-logs create"

### ISSUE THREAD

**Issue by scottvossen** [Azure/azure-cli#25363]
I don't see a way to specify an "anyof" clause in my conditions. Is this not supported like it is in the ARM templates? If not, then at least clarify that in the docs. Otherwise an example would be really appreciated.

ARM snippet:
```
condition: {
  "allOf": [
    {
      "field": "category",
      "equals": "ResourceHealth"
    },
    {
      "anyOf": [
        {
          "field": "resourceType",
          "equals": "Microsoft.Web/sites"
        }
      ]
    },
    {
      "anyOf": [
        {
          "field": "properties.currentHealthStatus",
          "equals": "Degraded"
        },
        {
          "field": "properties.currentHealthStatus",
          "equals": "Unavailable"
        }
      ]
    }
...
```

Azure CLI command (I don't have any docs on how to specify the last bit):
```
$condition = @"
category=ResourceHealth and
resourceType=Microsoft.Web/sites and
(properties.currentHealthStatus=Degraded or properties.currentHealthStatus=Unavailable) and
(properties.previousHealthStatus=Available or properties.previousHealthStatus=Unknown)
"@
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c78b494-edd2-74b4-fce6-1573cb9c242a
* Version Independent ID: 49b15a27-f990-bb88-eca8-d3f615210012
* Content: [az monitor activity-log alert](https://learn.microsoft.com/en-us/cli/azure/monitor/activity-log/alert?view=azure-cli-latest#az-monitor-activity-log-alert-create)
* Content Source: [latest/docs-ref-autogen/monitor/activity-log/alert.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/monitor/activity-log/alert.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@AllyW for awareness

**Comment by AllyW** [comment]
Hi @scottvossen  for `az monitor activity-log alert create`, `-h` would clarify the condition parameter input pattern which is `FIELD=VALUE[ and FIELD=VALUE...]` by design. Condition pattern like ARM templates is not supported in `activity-log alert`.

**Comment by scottyviscosity** [comment]
Thanks for the clarification. 

Like I mentioned above, it probably makes sense to provide that context in the parameter help text. Something like "anyof and all of conditions are not supported."

**Comment by AllyW** [comment]
hi @scottyviscosity , new api-version `2020-10-01` of activity-log alert is upgrading, which will support the `anyOf` conditioning management in cli side in recent releases. PR link is provided. 
Sorry for any confusions made in previous reply.
