### ISSUE TITLE
upgrade of az fails with command upgrade

### ISSUE THREAD

**Issue by elangelo** [Azure/azure-cli#25378]
## Describe the bug

**Command Name**
`az upgrade`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az upgrade`

## Environment Summary
```
Linux-5.2.11-1.el7.elrepo.x86_64-x86_64-with-centos-7.9.2009-Core, CentOS Linux 7 (Core)
Python 3.6.8
Installer: 

azure-cli 2.39.0 *
```

**Comment by elangelo** [comment]
just some extra info:
if i run az upgrade:
```
az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.39.0. Latest version available is 2.45.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): 
Not able to upgrade automatically. Instructions can be found at https://aka.ms/doc/InstallAzureCli
CLI upgrade failed or aborted.
```

I installed the az tool using the instructions on https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script and that installed version 2.39 while 2.45 is already available... I really need 2.42 for the feature in az that i want to use

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by bebound** [comment]
> Starting from Azure CLI 2.39.0 (released on 08/02/2022), no RPM packages will be released for RHEL 7 and CentOS 7. You may continue to use historical versions of Azure CLI on these systems, but there will be no updates or bugfixes. Consider upgrading to newer versions of RHEL or CentOS to use the latest Azure CLI.     ---https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf

**Comment by samuelverstraete** [comment]
You can resolve this ... but i must say that nothing in the 'error' output of the tool even hinted that there was no support for the version of linux i'm using...
