### ISSUE TITLE
Release of MSI version 2023-01-31

### ISSUE THREAD

**Issue by isolenov** [Azure/azure-cli#25380]
### Related command

az identity

### Resource Provider

Microsoft.ManagedIdentity

### Description of Feature or Work Requested

This is a GA release of the Federated Identity Credentials feature which was added to preview earlier <https://github.com/Azure/azure-cli/issues/23152>

There is no API changes for this feature. Just API version update.

However there is a breaking change:
`UserAssignedIdentitiesOperations` operation is not available API version since feature is not ready for GA and still in preview version. It was added by that chage:<https://github.com/Azure/azure-cli/issues/22112>. MSI is ok to remove it if there are no other options.

### Minimum API Version Required

2023-01-31

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/22354

Python SDK: https://pypi.org/project/azure-mgmt-msi/7.0.0/

### Request Example

same as <https://github.com/Azure/azure-cli/issues/23152>

### Target Date

ASAP no later than March-07

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@isolenov I'd like to confirm with you that this feature request only needs to upgrade the api-version, right? 
In addition, the release time of the next sprint is exactly 03-07, does this date meet your expectations?

**Comment by isolenov** [comment]
@zhoxing-ms 
> I'd like to confirm with you that this feature request only needs to upgrade the api-version, right?
I confirm there are no changes in API methods, interfaces or parameters. However here are 2 points which require attention in this context:
1. Minor: change of common types in swagger definition from v1 to v4 `../common-types/resource-management/v1/types.json` -> `../common-types/resource-management/v4/types.json`
2. Major: New API version `2023-01-31` and [python SDK v7.0](https://pypi.org/project/azure-mgmt-msi/7.0.0/) does not support `listAssociatedResources` command since it is still in preview and we simply not allowed to enable it in GA version. 
- Is it possible to use `listAssociatedResources` from the previous [python package v6.1](https://pypi.org/project/azure-mgmt-msi/6.1.0/) which utilizes `2021-09-30-preview` API version? 
- If this is not possible MSI is ok to remove that command in favor of GA release.

>In addition, the release time of the next sprint is exactly 03-07, does this date meet your expectations?
We are ready to have this release asap, Since CLI has a strict release cadence policy we have an agreement to GA no later than 03-07. However AKS team feature is waiting for this release to go to GA as well. They have 100’s of S500 customers which have sprint plans around the anticipated GA timeline to start the migration of all AKS workloads. If by any chance there would be an intermittent release of the CLI that would help a lot.

**Comment by yanzhudd** [comment]
Hi @isolenov,

> 1. Minor: change of common types in swagger definition from v1 to v4 ../common-types/resource-management/v1/types.json -> ../common-types/resource-management/v4/types.json
> 2. Major: New API version 2023-01-31 and [python SDK v7.0](https://pypi.org/project/azure-mgmt-msi/7.0.0/) does not support listAssociatedResources command since it is still in preview and we simply not allowed to enable it in GA version.
> 2.1. Is it possible to use listAssociatedResources from the previous [python package v6.1](https://pypi.org/project/azure-mgmt-msi/6.1.0/) which utilizes 2021-09-30-preview API version?
> 2.2. If this is not possible MSI is ok to remove that command in favor of GA release.

We currently cannot use two different versions of SDK. Thus, if we upgrade API version to `2023-01-31`, `listAssociatedResources` would not be supported. 

> We are ready to have this release asap, Since CLI has a strict release cadence policy we have an agreement to GA no later than 03-07. However AKS team feature is waiting for this release to go to GA as well. They have 100’s of S500 customers which have sprint plans around the anticipated GA timeline to start the migration of all AKS workloads. If by any chance there would be an intermittent release of the CLI that would help a lot.

We generally would not release a new version during a sprint except fixing urgent bugs. Do you mind we provide a private package generated by edge build firstly? 
In fact, since there would a breaking change (we generally recommend the breaking changes are better released in [breaking change window](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/teams_docs/azcli_docs/breaking_changes)) and our next breaking change window is around May, we suggest that the customers firstly use the private package and the official version will be released in the next breaking change window.

**Comment by isolenov** [comment]
Release in March milestone is crucial for MSI and AKS. Anyway SDK with a breaking change has been released already. 
I'll provide the final confirmation by Feb-14

**Comment by yanzhudd** [comment]
> @yanzhudd Release in March milestone is crucial for MSI and AKS. Anyway SDK with a breaking change has been released already. I'll provide the final confirmation by Feb-14

**Comment by yanzhudd** [comment]
> @yanzhudd Release in March milestone is crucial for MSI and AKS. Anyway SDK with a breaking change has been released already. I'll provide the final confirmation by Feb-14

@isolenov 
Since this feature request is raised just two days ago, this feature would be released on March 7 at the earliest, until then we could provide a private package generated by edge build.

Since a breaking change has a big influence on customers, if this feature needs to be released in March, do you mind providing business justification? And we will statistics on the number of requests of the `listAssociatedResources` command and subscriptions last month, so as to decide whether to release breaking change early.

**Comment by isolenov** [comment]
@yanzhudd here is statistics from ARM logs. Total 514 usages in 14days. Which is not really impressive.

By any chance does CLI provide any usage statistics to make it more accurate?

```
let start = ago(14d);
let end = now();
cluster("Armprod").database("ARMProd").HttpIncomingRequests
| where PreciseTimeStamp between (start .. end)
| where targetResourceProvider == "MICROSOFT.MANAGEDIDENTITY"
| where operationName =~ "POST/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.MANAGEDIDENTITY/USERASSIGNEDIDENTITIES/LISTASSOCIATEDRESOURCES"
| summarize count() by userAgent
| where userAgent contains "cli"
| order by count_

userAgent	count_
python/3.10.8 (Windows-10-10.0.19044-SP0) AZURECLI/2.42.0 (MSI)	82
AZURECLI/2.44.1 (MSI) azsdk-python-azure-mgmt-msi/6.1.0 Python/3.10.8 (Windows-10-10.0.19044-SP0)	68
python/3.10.8 (Windows-10-10.0.20348-SP0) AZURECLI/2.44.1 (MSI) VSTS_5555ff95-7881-497c-b54b-7dd4ababaf18_build_698_0	60
AZURECLI/2.44.1 (RPM) azsdk-python-azure-mgmt-msi/6.1.0 Python/3.9.14 (Linux-5.4.0-1101-azure-x86_64-with-glibc2.35) cloud-shell/1.0	42
FxVersion/6.0.1022.47605 OSName/Windows OSVersion/Microsoft.Windows.10.0.19044 Microsoft.Azure.Internal.Common.AzureRestClient/1.3.64 Az.Accounts/2.10.3 PSVersion/v7.2.7 AzurePowershell/v9.1.0	38
AZURECLI/2.40.0 (HOMEBREW) azsdk-python-azure-mgmt-msi/6.1.0 Python/3.10.6 (macOS-13.0-x86_64-i386-64bit)	36
AZURECLI/2.44.1 (HOMEBREW) azsdk-python-azure-mgmt-msi/6.1.0 Python/3.10.9 (macOS-12.6-arm64-arm-64bit)	36
FxVersion/4.8.9105.0 OSName/Windows OSVersion/Microsoft.Windows.10.0.22621. Microsoft.Azure.Internal.Common.AzureRestClient/1.3.68 Az.Accounts/2.11.1 AzurePowershell/v0.0.0 PSVersion/v5.1.22621.963	14
FxVersion/7.0.22.51805 OSName/Windows OSVersion/Microsoft.Windows.10.0.22000 Microsoft.Azure.Internal.Common.AzureRestClient/1.3.68 AzurePowershell/v9.3.0 PSVersion/v7.3.1 Az.Accounts/2.11.1	14
AZURECLI/2.44.1 (RPM) azsdk-python-azure-mgmt-msi/6.1.0 Python/3.9.13 (Linux-5.4.17-2136.312.3.4.el8uek.x86_64-x86_64-with-glibc2.28)	10
```

**Comment by isolenov** [comment]
@yanzhudd btw MSI python SDK is multiple-api package which permits users to pass in different api version in client. Can it be utilized in CLI to provide `listAssociatedResources` support with API version 2021-09-30-preview ?

**Comment by yanzhudd** [comment]
Hi @isolenov,
thanks for providing the approaches for avoid breaking change. It seems that the first option works for CLI. We would support `listAssociatedResources` with API version 2021-09-30-preview when other commands are using a stable version 2023-01-31.

**Comment by isolenov** [comment]
@yanzhudd awesome, thank you. please please use latest preview version `2022-01-31-preview` for `listAssociatedResources
