### ISSUE TITLE
Correct link to release notes in Releases

### ISSUE THREAD

**Issue by matsest** [Azure/azure-cli#25381]
The current link is a redirect which works on some devices but not all (at least GitHub mobile).
Seems like this is set in some configuration outside this repository?

The link in releases is: https://github.com/Azure/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md

Should be: https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md

![image](https://user-images.githubusercontent.com/10927304/217389959-bb7da8d5-6b3c-4d7b-8b18-655f6cfae08f.png)

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by bebound** [comment]
Thank you. I'll fix this.
