### ISSUE TITLE
Sudden azure-cli installation failure with single-shot script

### ISSUE THREAD

**Issue by bcraun** [Azure/azure-cli#25393]
**Describe the bug**
Beginning 02/07/2023 Bitbucket pipeline execution fails during attempted installation of `azure-cli` package. Error is:

`E: Unable to locate package azure-cli`

The installation method that started failing is:

`curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`

**To Reproduce**
Fails with either of the installation options documented by the following methods

Option 1 (single-shot command): 
https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-1-install-with-one-command

Option 2  (separate steps): 
https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions

**Expected behavior**
`azure-cli` installs successfully using the single-shot command documented in Option 1

**Environment summary**
Bitbucket pipeline execution environment which I believe is Ubuntu Trusty within Docker. Same environment that had previously worked until 02/08/2023. Additional details can be provided, if needed.

**Additional context**
Partial pipeline output from Option 1:

```
lsb_release -cs
curl -sL https://packages.microsoft.com/repos/azure-cli/dists/
Ign http://archive.ubuntu.com/ trusty InRelease
Hit http://archive.ubuntu.com/ trusty-updates InRelease
Hit http://archive.ubuntu.com/ trusty-security InRelease
Get:1 https://packages.microsoft.com/ trusty InRelease
Hit http://ppa.launchpad.net/ trusty InRelease
Hit http://archive.ubuntu.com/ trusty Release.gpg
Hit http://archive.ubuntu.com/ trusty Release
Hit http://archive.ubuntu.com/ trusty-updates/main Sources
Hit http://archive.ubuntu.com/ trusty-updates/restricted Sources
Hit http://archive.ubuntu.com/ trusty-updates/universe Sources
Hit http://archive.ubuntu.com/ trusty-updates/main amd64 Packages
Hit http://archive.ubuntu.com/ trusty-updates/restricted amd64 Packages
Hit http://archive.ubuntu.com/ trusty-updates/universe amd64 Packages
Hit http://archive.ubuntu.com/ trusty-security/main Sources
Hit http://archive.ubuntu.com/ trusty-security/restricted Sources
Hit http://archive.ubuntu.com/ trusty-security/universe Sources
Hit http://archive.ubuntu.com/ trusty-security/main amd64 Packages
Hit http://archive.ubuntu.com/ trusty-security/restricted amd64 Packages
Hit http://archive.ubuntu.com/ trusty-security/universe amd64 Packages
Get:2 https://packages.microsoft.com/ trusty/main amd64 Packages
Hit http://archive.ubuntu.com/ trusty/main Sources
Hit http://archive.ubuntu.com/ trusty/restricted Sources
Hit http://archive.ubuntu.com/ trusty/universe Sources
Hit http://archive.ubuntu.com/ trusty/main amd64 Packages
Hit http://archive.ubuntu.com/ trusty/restricted amd64 Packages
Hit http://ppa.launchpad.net/ trusty/main amd64 Packages
Hit http://archive.ubuntu.com/ trusty/universe amd64 Packages
Fetched 1902 B in 13s (145 B/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package azure-cli
```

Partial output from Option 2:

```
deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ trusty main
Hit http://ppa.launchpad.net/ trusty InRelease
Ign http://archive.ubuntu.com/ trusty InRelease
Hit http://archive.ubuntu.com/ trusty-updates InRelease
Hit http://archive.ubuntu.com/ trusty-security InRelease
Get:1 https://packages.microsoft.com/ trusty InRelease
Hit http://archive.ubuntu.com/ trusty Release.gpg
Hit http://archive.ubuntu.com/ trusty Release
Hit http://ppa.launchpad.net/ trusty/main amd64 Packages
Hit http://archive.ubuntu.com/ trusty-updates/main Sources
Hit http://archive.ubuntu.com/ trusty-updates/restricted Sources
Hit http://archive.ubuntu.com/ trusty-updates/universe Sources
Hit http://archive.ubuntu.com/ trusty-updates/main amd64 Packages
Hit http://archive.ubuntu.com/ trusty-updates/restricted amd64 Packages
Hit http://archive.ubuntu.com/ trusty-updates/universe amd64 Packages
Hit http://archive.ubuntu.com/ trusty-security/main Sources
Hit http://archive.ubuntu.com/ trusty-security/restricted Sources
Hit http://archive.ubuntu.com/ trusty-security/universe Sources
Hit http://archive.ubuntu.com/ trusty-security/main amd64 Packages
Hit http://archive.ubuntu.com/ trusty-security/restricted amd64 Packages
Hit http://archive.ubuntu.com/ trusty-security/universe amd64 Packages
Ign https://packages.microsoft.com/ trusty InRelease
Hit http://archive.ubuntu.com/ trusty/main Sources
Get:2 https://packages.microsoft.com/ trusty/main amd64 Packages
Hit http://archive.ubuntu.com/ trusty/restricted Sources
Hit http://archive.ubuntu.com/ trusty/universe Sources
Hit http://archive.ubuntu.com/ trusty/main amd64 Packages
Hit http://archive.ubuntu.com/ trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com/ trusty/universe amd64 Packages
Fetched 1902 B in 11s (167 B/s)
Reading package lists...
W: GPG error: https://packages.microsoft.com/ trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package azure-cli
```

**Comment by bcraun** [comment]
As an additional data point, I tried the one-shot command locally on Ubuntu 20.04 (focal) which was successful so maybe this is specific to trusty.

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by bebound** [comment]
As a workaround, you change `arch=amd64` to `arch=all` in `/etc/apt/sources.list.d/azure-cli.list` in option 1.
After doing this, `apt update && apt install azure-cli` should work

**Comment by jiasli** [comment]
As for the one-shot command, I can reproduce.

In `ubuntu:trusty`, the log shows:

```
Hit https://packages.microsoft.com trusty InRelease
Hit https://packages.microsoft.com trusty/main amd64 Packages
```

But in `ubuntu:jammy` and the log shows:

```
Get:1 https://packages.microsoft.com/repos/azure-cli jammy InRelease [3029 B]
Get:2 https://packages.microsoft.com/repos/azure-cli jammy/main all Packages [1096 B]
```

For `ubuntu:trusty`:

- The package index is: https://packages.microsoft.com/repos/azure-cli/dists/trusty/main/binary-all/Packages
- The `amd64` index is empty: https://packages.microsoft.com/repos/azure-cli/dists/trusty/main/binary-amd64/Packages

For `ubuntu:jammy`:

- The package index is: https://packages.microsoft.com/repos/azure-cli/dists/jammy/main/binary-all/Packages
- The `amd64` index is empty: https://packages.microsoft.com/repos/azure-cli/dists/jammy/main/binary-amd64/Packages

**Comment by bcraun** [comment]
> 14.04 is [EOL](https://wiki.ubuntu.com/Releases) long long time ago. We only support 18.04 and newer version. We recommend you to update your OS version. We don't guarantee the [script or manual step in the doc](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt) works on 14.04.

Understood about upgrading but, unfortunately, it is not within my control. I'm still not understanding why this worked with the same environment until yesterday?

> As a workaround, you change `arch=amd64` to `arch=all` in `/etc/apt/sources.list.d/azure-cli.list` in option 1.
> After doing this, `apt update && apt install azure-cli` should work again.

Option 1 is a one-shot command. How would one change `/etc/apt/sources.list.d/azure-cli.list` during the automated pipeline execution?
