### ISSUE TITLE
Example Create for az cli is invalid

### ISSUE THREAD

**Issue by Vision2HB** [Azure/azure-cli#25398]
example provided for az dns-resolver inbound-endpoint create is not correct, the string for IP configurations requires double quotes around the variable names and single quotes around the entire string or it won't run

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59d07366-72ab-2e5a-5f8b-8e823aa95952
* Version Independent ID: 090e975b-0a45-9a61-534c-9329fdf1a5cb
* Content: [az dns-resolver inbound-endpoint](https://learn.microsoft.com/en-us/cli/azure/dns-resolver/inbound-endpoint?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/dns-resolver/inbound-endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/dns-resolver/inbound-endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@Vision2HB The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
