### ISSUE TITLE
az cli storage --auth-mode key broke on Azure DevOps agents

### ISSUE THREAD

**Issue by johnathon-b** [Azure/azure-cli#25396]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

```WARNING: 
There are no credentials provided in your command and environment, we will query for account key for your storage account.
It is recommended to provide --connection-string, --account-key or --sas-token in your command as credentials.

You also can add `--auth-mode login` in your command to use Azure Active Directory (Azure AD) for authorization if your login account is assigned required RBAC roles.
For more information about RBAC roles in storage, visit https://docs.microsoft.com/azure/storage/common/storage-auth-aad-rbac-cli.

In addition, setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information about environment variable usage.
WARNING: 
Skip querying account key due to failure: Storage account 'Dataasdfasdfasdf' not found.
ERROR: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:bddd40d6-901e-000d-3c0c-3cbab2000000
Time:2023-02-08T22:28:36.1235041Z
ErrorCode:NoAuthenticationInformation
```

**Related command**

az storage blob delete-batch --account-name cdwolde3a3australiapubst --source '$web' --auth-mode key
az storage blob upload-batch
az storage * --auth-mode key... etc.

**Describe the bug**

When performing a delete-batch or upload-batch, and providing --auth-mode key, our pipelines would fetch a key on-demand and complete the process. Now, all of our pipelines that use this functionality are broken and can no longer deploy or use this functionality. 

**To Reproduce**

Deploy storage account and attempt to upload blob data with --auth-mode key

**Expected behavior**

There are no credentials provided in your command and environment, we will query for account key for your storage account.

**Environment summary**

macOS-13.0.1-arm64-arm-64bit, Darwin 22.1.0
Python 3.10.10
Installer: HOMEBREW

azure-cli 2.45.0

Extensions:
azure-devops 0.26.0
containerapp 0.3.21
account 0.2.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1

**Additional context**

Effecting local installs of az-cli as well as instances using it in Azure DevOps pipelines.

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by johnathon-b** [comment]
We've gotten around this by doing a `pip install azure-cli==2.42.0` before each Azure DevOps task.

Anything above 2.42.0 fails when using `--auth-mode key`.

This also includes our local machines.

**Comment by MoChilia** [comment]
Hi @johnathon-b!
Querying account key was skipped due to the failure: `Storage account 'Dataasdfasdfasdf' not found`. It's possible that the account wasn't created successfully or was deleted before the command was executed. 
Besides, could you share how your pipelines fetch a key on-demand? Since the parameter `--account-key` was not provided in your command, please make sure you have stored the account key in the environment variable: `AZURE_STORAGE_KEY`.
