### ISSUE TITLE
az network bastion fails to connect

### ISSUE THREAD

**Issue by networkneil** [Azure/azure-cli#25391]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az network bastion rdp
az network bastion tunnel

**Describe the bug**
Unable to connect to the VM using the above az command with the following errors.
```
The command failed with an unexpected error. Here is the traceback:
cannot import name 'WinDLL' from 'ctypes' (/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/anil/.azure/cliextensions/bastion/azext_bastion/custom.py", line 223, in rdp_bastion_host
    from ._process_helper import launch_and_wait
  File "/Users/anil/.azure/cliextensions/bastion/azext_bastion/_process_helper.py", line 9, in <module>
    from ctypes import WinDLL, c_int, c_size_t, Structure, WinError, sizeof, pointer
ImportError: cannot import name 'WinDLL' from 'ctypes' (/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py)
```

**To Reproduce**
Connect to a VM in running state and executing an az network bastion command to connect to the VM

**Expected behavior**
The az command should get executed and creates a tunnel for RDP and then connect to the local host on the specified port 

**Environment summary**

Install method - Brew

az --version
```
azure-cli                         2.45.0

core                              2.45.0
telemetry                          1.0.8

Extensions:
bastion                            0.2.0
ssh                                1.1.3
interactive                        0.4.6
containerapp                      0.3.21

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/opt/homebrew/Cellar/azure-cli/2.45.0/libexec/bin/python'
Extensions directory '/Users/anil/.azure/cliextensions'

Python (Darwin) 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```
Shell Type - MacOS - zsh

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@networkneil Thanks for reaching out to us and reporting this issue. Could you please confirm if you are running this from a cloudshell ? If Yes, it wont be able to open the RDP on your local machine. For this reason, we recommend using powershell with az cli (on Windows machine).

Also, note that RDP command works best on Windows, for other OS’ (like Linux or Mac) you can do the [tunnel command](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-tunnel) and then use the client of your choice.

>Connect to a VM using the [az network bastion tunnel command](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-tunnel). This lets you do the following:

>- Use native clients on non-Windows local computers (example: a Linux PC).
>- Use the native client of your choice. (This includes the Windows native client.)
>- Connect using SSH or RDP.
>- Set up concurrent VM sessions with Bastion.
>- [Upload files](https://docs.microsoft.com/en-us/azure/bastion/vm-upload-download-native#tunnel-command) to your target VM from your local computer. File download from the target VM to the local client is currently not supported for this command.

>Currently, this feature has the following limitation:
Signing in using an SSH private key stored in Azure Key Vault isn’t supported with this feature. Before signing in to your Linux VM using an SSH key pair, download your private key to a file on your local machine.

Hope this helps.

**Comment by networkneil** [comment]
@navba-MSFT, Thank you for your reply.

I'm running this command as `az network bastion tunnel` in zsh in MacOS. This was working as expected yesterday before I have updated my az cli version. Unfortunately, I have no recollection of the previous version it was working before the update of az cli. It was installed with Brew.

The exact command is 
` az network bastion tunnel --name bastionResource --resource-group resourceGroup --target-resource-id "/subscriptions/sub1/resourceGroups/resourceGroup/providers/Microsoft.Compute/virtualMachines/vm01" --resource-port "3389" --port "3380"`

**Comment by networkneil** [comment]
> @networkneil Thanks for reaching out to us and reporting this issue. Could you please confirm if you are running this from a cloudshell ? If Yes, it wont be able to open the RDP on your local machine. For this reason, we recommend using powershell with az cli (on Windows machine).
> 
> Also, note that RDP command works best on Windows, for other OS’ (like Linux or Mac) you can do the [tunnel command](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-tunnel) and then use the client of your choice.
> 
> > Connect to a VM using the [az network bastion tunnel command](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-tunnel). This lets you do the following:
> 
> > * Use native clients on non-Windows local computers (example: a Linux PC / MAC).
> > * Use the native client of your choice. (This includes the Windows native client.)
> > * Connect using SSH or RDP.
> > * Set up concurrent VM sessions with Bastion.
> > * [Upload files](https://docs.microsoft.com/en-us/azure/bastion/vm-upload-download-native#tunnel-command) to your target VM from your local computer. File download from the target VM to the local client is currently not supported for this command.
> 
> > Currently, this feature has the following limitation:
> > Signing in using an SSH private key stored in Azure Key Vault isn’t supported with this feature. Before signing in to your Linux VM using an SSH key pair, download your private key to a file on your local machine.
> 
> Hope this helps.

@navba-MSFT , Thank you for your reply.

I'm running this command as az network bastion tunnel in zsh in MacOS. This was working as expected yesterday before I have updated my az cli version. Unfortunately, I have no recollection of the previous version it was working before the update of az cli. It was installed with Brew.

The exact command is
 az network bastion tunnel --name bastionResource --resource-group resourceGroup --target-resource-id "/subscriptions/sub1/resourceGroups/resourceGroup/providers/Microsoft.Compute/virtualMachines/vm01" --resource-port 3389 --port 3380

**Comment by networkneil** [comment]
> @networkneil Thanks for reaching out to us and reporting this issue. Could you please confirm if you are running this from a cloudshell ? If Yes, it wont be able to open the RDP on your local machine. For this reason, we recommend using powershell with az cli (on Windows machine).
> 
> Also, note that RDP command works best on Windows, for other OS’ (like Linux or Mac) you can do the [tunnel command](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-tunnel) and then use the client of your choice.
> 
> > Connect to a VM using the [az network bastion tunnel command](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-tunnel). This lets you do the following:
> 
> > * Use native clients on non-Windows local computers (example: a Linux PC / MAC).
> > * Use the native client of your choice. (This includes the Windows native client.)
> > * Connect using SSH or RDP.
> > * Set up concurrent VM sessions with Bastion.
> > * [Upload files](https://docs.microsoft.com/en-us/azure/bastion/vm-upload-download-native#tunnel-command) to your target VM from your local computer. File download from the target VM to the local client is currently not supported for this command.
> 
> > Currently, this feature has the following limitation:
> > Signing in using an SSH private key stored in Azure Key Vault isn’t supported with this feature. Before signing in to your Linux VM using an SSH key pair, download your private key to a file on your local machine.
> 
> Hope this helps.

@navba-MSFT, Thank you for your reply.

I'm running this command as `az network bastion tunnel` in zsh in MacOS. This was working as expected yesterday before I have updated my az cli version. Unfortunately, I have no recollection of the previous version it was working before the update of az cli. It was installed with Brew.

The exact command is
` az network bastion tunnel --name bastionResource --resource-group resourceGroup --target-resource-id "/subscriptions/sub1/resourceGroups/resourceGroup/providers/Microsoft.Compute/virtualMachines/vm01" --resource-port 3389 --port 3380`

**Comment by navba-MSFT** [comment]
@networkneil Thanks for replying. We have fixed this issue on priority. Please update your `bastion `extension by running the below command and that should fix this. 

> **az extension update -n bastion**

Hope this helps.

**Comment by networkneil** [comment]
Thats awesome! 
I have updated `bastion` extension by running the command `az extension update -n bastion` and its back in action!

Thank you all!

**Comment by navba-MSFT** [comment]
@networkneil Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by jiasli** [comment]
Duplicate of #23143
