### ISSUE TITLE
Find the format of a snapshot using the logicalSectorSize property

### ISSUE THREAD

**Issue by ifeyin** [Azure/azure-cli#25392]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**
Not able to get the format of a snapshot using CLI command

**To Reproduce**

**Expected behavior**
Run a set of command on a snapshot to get the logical sector size (512 logical sector size for VHD and 4096 logical sector size for VHDX)

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Please provide detailed CLI command and error log.

**Comment by jiasli** [comment]
Seems to be related to `az snapshot`. As discussed internally, the customer has solved the issue. Closing.
