### ISSUE TITLE
--clean option does not work.

### ISSUE THREAD

**Issue by toruita** [Azure/azure-cli#25409]
## Describe the bug

**Command Name**
`az webapp deploy`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
If explicitly set --clean true.  az webapp deploy -g xx -n xx --src-path inner/localnew.zip  --target-path /home/site/wwwroot/aaa/ --clean true --debug

OneDeploy deployment succeeded, but the directory of previous existing files not being cleaned up. That is to say, old and new deployed files both existed.

## Expected Behavior
Old deployed files should be removed.

## Environment Summary
```
Linux-5.4.0-1103-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.45.0

Extensions:
containerapp 0.3.6
spring 1.2.0
ai-examples 0.2.5
ml 2.13.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by dannysongg** [comment]
Currently investigating this issue, looks like there is a bug with the underlying deployment API

**Comment by gmoeschi** [comment]
Any updates on this?
I'm unable to update my webapp through  the ci/cd pipeline.

**Comment by btardif** [comment]
@dannysongg / @jvano any update on this?

**Comment by dannysongg** [comment]
@btardif  The fix for this issue has already been rolled out for Windows Web Apps. The same fix is slated to be rolled out in the next KuduLite release for Linux Web Apps

**Comment by btardif** [comment]
@dannysongg in that case I think this issue can be closed as resolved, we just need to provide an ETA for the Linux rollout to complete. 

CC: @tulikac

**Comment by galaplexus** [comment]
Well - I would like to close when it's actually resolved on Linux. That would be great.

**Comment by sarsharma** [comment]
@tulikac - I believe we can close this one since the Kudulite rollout with this fix is done. 
cc: @dannysongg , @btardif
