### ISSUE TITLE
--identities parameter for 'az webapp identity assign' is not clearly documented

### ISSUE THREAD

**Issue by mystiqu** [Azure/azure-cli#25401]
[Enter feedback here]
When assigning an identity, the documentation seems to be wrong regarding the --identities property.
"_Space-separated identities to assign. Use '[system]' to refer to the system assigned identity. Default: '[system]'_."

I interpret this as the principal id(s) (guids). 
However, it expects the fully qualified resource Id.

Testing with the principalId for the user assigned managed identity
```
$principalId = $($principalObject).principalId  #$principalObject here is the user assigned managed identity resource
az webapp identity assign -g $resourcegroup -n $apiName --identities $principalId 
az : ERROR: (LinkedInvalidPropertyId) Property id '70792f8c-c632-4cb3-9ac8-c280cabd35f1' at path '' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
```

When changing to the fully qualified resource Id, it works
```
$principalId = $($principalObject).id      #$principalObject here is the user assigned managed identity resource
PS C:\Repos\INT.InformationServices.Products\Products\infrastructure\dev> az webapp identity assign -g $resourcegroup -n $apiName --identities $id  #$principalId
{
  "principalId": null,
  "tenantId": null,
  "type": "UserAssigned",
  "userAssignedIdentities": {
    "/subscriptions/*****/resourcegroups/*****-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/*****v": {
      "clientId": "**************************",
      "principalId": "**************************"
    }
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2bf26b4-3d91-ec60-c64d-8f910a4f0f00
* Version Independent ID: 33547311-9105-6e41-e477-3681d2a87087
* Content: [az webapp identity](https://learn.microsoft.com/en-us/cli/azure/webapp/identity?view=azure-cli-latest#az-webapp-identity-assign)
* Content Source: [latest/docs-ref-autogen/webapp/identity.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/identity.yml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@mystiqu The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
