### ISSUE TITLE
`az storage account network-rule remove`: allow multiple ips

### ISSUE THREAD

**Issue by yellowhat** [Azure/azure-cli#25402]
**Related command**

`az storage account network-rule remove --account-name xyz --ip-address "*"`
`az storage account network-rule remove --account-name xyz --ip-address ip0 ip1`

**Describe the bug**

I would like to remove all ip network-rules applied to a storage account.

**Describe the solution you'd like**

1. Have an option to remove all ip
2. Remove multiple ips with 1 command

**Describe alternatives you've considered**

Using a for loop on each ip is extremely time consuming almost 5 min for 20 ips.

**Comment by yonzhan** [comment]
@evelyn-ys for awareness
