### ISSUE TITLE
az network commands fail

### ISSUE THREAD

**Issue by Teodelas** [Azure/azure-cli#2541]
With a fresh install of Python and AZ CLI 2.0, az network commands fail.  I get a message to run az component update --add network but that fails as well.  When I add the debug switch I get: 

Exception:
Traceback (most recent call last):
  File "C:\Users\teodelas\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 538, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\users\\teodelas\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\azure\\cli\\command_modules\\network\\mgmt_express_route_circuit\\lib\\__pycache__\\express_route_circuit_creation_client.cpython-35.pyc' -> 'C:\\Users\\teodelas\\AppData\\Local\\Temp\\pip-mu850_b7-uninstall\\users\\teodelas\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\azure\\cli\\command_modules\\network\\mgmt_express_route_circuit\\lib\\__pycache__\\express_route_circuit_creation_client.cpython-35.pyc'

**Comment by tjprescott** [comment]
Can you show the output of `az --version`?

**Comment by Teodelas** [comment]
This is on a Windows machine btw:

$ az --version
azure-cli (2.0.1)

acr (0.1.1b2)
acs (2.0.1)
appservice (0.1.1b6)
batch (0.1.1b5)
cloud (2.0.0)
component (2.0.0)
configure (2.0.1)
container (0.1.1b4)
context (0.1.1b2)
core (2.0.1)
documentdb (0.1.1b2)
feedback (2.0.0)
find (0.0.1b1)
iot (0.1.1b3)
keyvault (0.1.1b6)
network (0.1.1b2)
nspkg (2.0.0)
profile (2.0.1)
redis (0.1.1b3)
resource (2.0.1)
role (2.0.0)
sql (0.1.1b6)
storage (2.0.1)
vm (2.0.1)

Python (Windows) 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]

**Comment by tjprescott** [comment]
The version of the network package you have is incorrect. The latest version is 2.0.1--yours shows 0.1.1b2. 
How did you install the CLI?  Please try running `pip install azure-cli-network --upgrade` to see if it updates to the latest version.

**Comment by derekbekoe** [comment]
The failure of `az component update` was due to this issue on Windows with long file paths https://github.com/Azure/azure-cli/issues/1221.

**Comment by Teodelas** [comment]
No, I get an error as well.  I had the original xplat CLI at one point.  I did a pip uinstall azure-cli, removed python and deleted the directories and reinstalled with the same issue.

**Comment by tjprescott** [comment]
@derekbekoe is there any reason why pip would install anything but the latest?

**Comment by Teodelas** [comment]
Aha!  That worked.  Thank you!  Can we add that to the troubleshooting documentation?

https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation

**Comment by tjprescott** [comment]
Our install troubleshooting links to our list of common issues. This one is in there #1221.
