### ISSUE TITLE
Add state variable to Enable/Disable a custom rule in WAF policy

### ISSUE THREAD

**Issue by tejasshah7** [Azure/azure-cli#25426]
### Related command

az network application-gateway waf-policy custom-rule

https://learn.microsoft.com/en-us/cli/azure/network/application-gateway/waf-policy/custom-rule?view=azure-cli-latest

### Resource Provider

Network (NRP)

### Description of Feature or Work Requested

Need to add support for a state variable with Enabled/Disabled values.

### Minimum API Version Required

2022-09-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/22457

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/462e60d34f84a61f7ada0482c3df3a72aa14f1dd/specification/network/resource-manager/Microsoft.Network/stable/2022-09-01/examples/WafPolicyCreateOrUpdate.json

### Target Date

2023-03-07

**Comment by yonzhan** [comment]
network feature

**Comment by tejasshah7** [comment]
> network feature

SDK with these changes was released. Just curious what is the ETA for CLI release for this? I need to understand this for our release planning.

**Comment by necusjz** [comment]
> > network feature
> 
> SDK with these changes was released. Just curious what is the ETA for CLI release for this? I need to understand this for our release planning.

https://github.com/Azure/azure-cli/milestone/128
