### ISSUE TITLE
az mobile-network: Implement missing commands

### ISSUE THREAD

**Issue by rafaeldnferreira** [Azure/azure-cli#25420]
The following commands for **az mobile-network pccp ** were skipped during the first release as their API were still under development and now are ready and widely available:

- collect-diagnostics-packages
- rollback
- reinstall

The Swagger reference is [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/mobilenetwork/resource-manager/Microsoft.MobileNetwork/stable/2022-11-01/packetCoreControlPlane.json)

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by rafaeldnferreira** [comment]
Hi @yonzhan - is it correct to assume this is scheduled for 04-04 according to the Milestone label on the right side pane?

Thanks

**Comment by jsntcy** [comment]
We probably put it in the sprint of 4-25 as we are busy on OKR review for this semester and next semester planning this sprint.

**Comment by rafaeldnferreira** [comment]
@jsntcy ok, noted.
