### ISSUE TITLE
Support -SKU upgrade for Azure Databricks Workspace

### ISSUE THREAD

**Issue by v-vyedavelly** [Azure/azure-cli#25430]
### Related command

az databricks workspace update --sku

### Resource Provider

Microsoft.Databricks/workspaces

### Description of Feature or Work Requested

We are from Azure Databricks team utilizing Az cli tool for our service. We have test cases where we create and update Azure Databricks workspaces . We refer to this documentation https://learn.microsoft.com/en-us/cli/azure/databricks?view=azure-cli-latest.

As part of Workspace update we have a scenario of updating Sku of an existing Databricks Workspace , which is currently not supported by Az cli commands. Please look at https://learn.microsoft.com/en-us/cli/azure/databricks/workspace?view=azure-cli-latest#az-databricks-workspace-update

We would like to request if this can be supported at the earliest. 

### Minimum API Version Required

2018-04-01

### Swagger PR link / SDK link

N/A

### Target Date

2023-02-28

**Comment by yonzhan** [comment]
route to CXP team

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by jsntcy** [comment]
@v-vyedavelly, what's the API version and swagger link?

**Comment by satishraj777** [comment]
Hey jsntcy, thanks for following up. Below are the details:

API Version: 2023-02-01

Also JFYI our service team support updating workspace SKU for all API versions (2022-04-01-preview etc.)

Swagger Link: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/databricks/resource-manager/Microsoft.Databricks/stable/2023-02-01

Please let me know if you have any questions.

**Comment by satishraj777** [comment]
Hello Yu Chen, do we have any ETA for having this GA?

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/milestone/128 Official Release: 04/04/2023

**Comment by jsntcy** [comment]
@satishraj777, the feature has been released with databricks 0.10.0.
