### ISSUE TITLE
[App Service] [Discussion] Provide first-class/simpler support for retrieving FTP info

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2544]
The new ` az appservice web deployment list-publishing-profiles` command is cool, but I'm not sure whether it's intuitive to look there in order to retrieve FTP info, and if I'm using web apps on Linux, then I'm not sure whether the MSDeploy info would be useful (or even work?). So this command feels a bit "low-level", as opposed to trying to provide a first-class experience for a potentially common scenario (e.g. how do I get FTP access?).

I wonder whether it would be useful to have a command that allowed getting the FTP info specifically, that was effectively the equivalent of running the following command:

```shell
az appservice web deployment list-publishing-profiles --query "[?publishMethod=='FTP'].{URL:publishUrl, Username:userName,Password:userPWD}"
```

Something like the following might be simpler and more discoverable (I'm not a fan of this exact naming, so it's just meant to be illustrative):

```shell
az appservice web deployment show-ftp-info
```

Maybe the above is obvious, and it's just me. Or maybe this isn't a common enough scenario to warrant simplifying it. But I wanted to throw out the discussion topic, and see what folks thoughts were here.

**Comment by yugangw-msft** [comment]
Both `webapp create` and `webapp show` now show the endpoint
