### ISSUE TITLE
az eventhubs namespace networking option for Selected network

### ISSUE THREAD

**Issue by mnadeem** [Azure/azure-cli#25440]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

```
REM ------------------------------
REM Create EventHub Start
REM ------------------------------
REM Exposes eventHubNamespaceName, eventHubBundleSubmittedHubName, bundleSubmittedHubId
set eventHubNamespaceName=%appPrefix%-%environment%-eh
set eventHubBundleSubmittedHubName=bundle.submitted
set eventHubBundleSubmittedAuthRuleName=%eventHubNamespaceName%-%eventHubBundleSubmittedHubName%-ar

echo [32m Creating EventHub namespace %eventHubNamespaceName%  [0m
call az eventhubs namespace create --resource-group %resourceGroupName% --name %eventHubNamespaceName% --location %location% --sku Standard --enable-kafka false --enable-auto-inflate --maximum-throughput-units 20 --tags %envTag% 

FOR /F "tokens=1" %%F IN ('call az eventhubs namespace show --name %eventHubNamespaceName% --resource-group %resourceGroupName% --query "id" --output tsv')  DO SET eventHubServerId=%%F

echo [32m Feteched %eventHubServerId% [0m

echo [32m Creating EventHub Hub %eventHubBundleSubmittedHubName% in namespace %eventHubNamespaceName%  [0m
call az eventhubs eventhub create --name %eventHubBundleSubmittedHubName% --resource-group %resourceGroupName% --namespace-name %eventHubNamespaceName%

echo [32m Getting Bundle submitted hub id for %eventHubBundleSubmittedHubName%  [0m
FOR /F "tokens=1" %%F IN ('call az eventhubs eventhub show --name %eventHubBundleSubmittedHubName% --namespace-name %eventHubNamespaceName% --resource-group %resourceGroupName%  --query id -o tsv')  DO SET bundleSubmittedHubId=%%F

echo [32m Disabling Public access for %eventHubNamespaceName% [0m
call az eventhubs namespace network-rule update --resource-group %resourceGroupName% --namespace-name %eventHubNamespaceName% --enable-trusted-service-access true --public-network-access Disabled

echo [32m Adding %vNetName%-%eventHubSubnetName% to %eventHubNamespaceName% [0m
call az eventhubs namespace network-rule add --namespace-name %eventHubNamespaceName% --resource-group %resourceGroupName% --vnet-name %vNetName% --subnet %eventHubSubnetName%

echo [32m Creating eventhub authorizationo rule on %eventHubBundleSubmittedHubName% [0m
call az eventhubs eventhub authorization-rule create --resource-group %resourceGroupName% --name %eventHubBundleSubmittedAuthRuleName% --namespace-name %eventHubNamespaceName%  --eventhub-name %eventHubBundleSubmittedHubName%  --rights Listen Send
```

**Describe the bug**

When I create event hub using the above command, networking showing as disabled 

<img width="544" alt="image" src="https://user-images.githubusercontent.com/476145/218436283-6158a40c-eff2-4e10-9c5d-6f3adda67463.png">

instead of the following

<img width="599" alt="image" src="https://user-images.githubusercontent.com/476145/218436600-baba43ac-a9f0-4c00-967f-1e71a0dc2716.png">

**Not sure if I am missing any command ?**

What command should be executed to, to show the networking as selected networks instead of disabled ?

**To Reproduce**

Execute the above commands

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@mnadeem Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@mnadeem I was able to run the below command and set the Networking ACl for my Event Hub.

Please update the {variables} run the below AzCLI command from your cmd bash:

> **az rest --method PUT --url "https://management.azure.com/subscriptions/{subID}/resourceGroups/{RgName}/providers/Microsoft.EventHub/namespaces/{EHNamespace}/networkRuleSets/default?api-version=2021-11-01" --body @body.json**


Below is the content of **body.json**:

```
{
  "properties": {
    "defaultAction": "Deny",
    "virtualNetworkRules": [
      {
        "subnet": {
          "id": "/subscriptions/subscriptionid/resourcegroups/resourcegroupid/providers/Microsoft.Network/virtualNetworks/myvn/subnets/subnet2"
        },
        "ignoreMissingVnetServiceEndpoint": true
      },
      {
        "subnet": {
          "id": "/subscriptions/subscriptionid/resourcegroups/resourcegroupid/providers/Microsoft.Network/virtualNetworks/myvn/subnets/subnet3"
        },
        "ignoreMissingVnetServiceEndpoint": false
      },
      {
        "subnet": {
          "id": "/subscriptions/subscriptionid/resourcegroups/resourcegroupid/providers/Microsoft.Network/virtualNetworks/myvn/subnets/subnet6"
        },
        "ignoreMissingVnetServiceEndpoint": false
      }
    ],
    "ipRules": [
      {
        "ipMask": "1.1.1.1",
        "action": "Allow"
      },
      {
        "ipMask": "1.1.1.2",
        "action": "Allow"
      },
      {
        "ipMask": "1.1.1.3",
        "action": "Allow"
      },
      {
        "ipMask": "1.1.1.4",
        "action": "Allow"
      },
      {
        "ipMask": "1.1.1.5",
        "action": "Allow"
      }
    ]
  }
}

```
Hope this helps.

**Comment by navba-MSFT** [comment]
@mnadeem I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by mnadeem** [comment]
Appreciate if you could provide me the az cli command

**Comment by navba-MSFT** [comment]
@mnadeem I ran the command[ az eventhubs namespace network-rule update ](https://learn.microsoft.com/en-us/cli/azure/eventhubs/namespace/network-rule?view=azure-cli-latest#az-eventhubs-namespace-network-rule-update)and it ran successfully.

But the portal was still showing the option as disabled. 

So ran the CLI command [az eventhubs namespace network-rule list](https://learn.microsoft.com/en-us/cli/azure/eventhubs/namespace/network-rule?view=azure-cli-latest#az-eventhubs-namespace-network-rule-list) and that showed that the setting ( configuration) was saved succesfully.

Seems like this is a portal bug which is not allowing the refresh. I am working with the Product owners. I will keep you posted.

**Comment by navba-MSFT** [comment]
@mnadeem After looking into the issue and discussing with the Product Owners, it seems portal is behaving as expected. 

The parameters  `--default-action` and `--public-network ` decides which Radio button should be enabled. After running the below command, I was able to set the **Selected Networks** option:

> az eventhubs namespace network-rule update --resource-group MyRgName --namespace-name MyEHNamespace 
**--default-action Deny --public-network Enabled**

See the below screenshot from the portal:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/57353862/222067696-8234872e-1b74-4266-bdf4-439cd6b5fc24.png">

More Information: We use the logic in the following picture to determine what radio button/section to show in the portal UI:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/57353862/222067412-ba03620f-5141-4bb2-9221-d10269bcbad9.png">

Hope this helps.

**Comment by navba-MSFT** [comment]
@mnadeem I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by mnadeem** [comment]
I am good, thank you

**Comment by navba-MSFT** [comment]
@mnadeem Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
