### ISSUE TITLE
AKS Nodepool Upgrade using az cli is failing, please help.

### ISSUE THREAD

**Issue by shiva-appani-gep** [Azure/azure-cli#25449]
## Describe the bug

**Command Name**
`az aks nodepool upgrade`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks nodepool upgrade --resource-group {} --cluster-name {} --kubernetes-version {} --name {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0

Extensions:
appservice-kube 0.1.7
connectedk8s 1.3.13
customlocation 0.1.3
front-door 1.0.17
k8s-extension 1.3.9
logicapp 0.1.2

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by shiva-appani-gep** [comment]
Routed, thanks !

**Comment by navba-MSFT** [comment]
@shiva-appani-gep Thanks for reaching out to us and reporting this issue. Could you please share the detailed error message that you are receiving while trying to upgrade the node pool ? Awaiting your reply.

**Comment by shiva-appani-gep** [comment]
@navba-MSFT 
[az_nodepool_upgrade_error.log](https://github.com/Azure/azure-cli/files/10753244/az_nodepool_upgrade_error.log)
Attaching complete error for your reference.

**Comment by navba-MSFT** [comment]
@shiva-appani-gep Apologies for the late reply. This issue will be fixed as a part of this PR https://github.com/Azure/azure-cli/pull/25526 . It is currently under review.

**Comment by navba-MSFT** [comment]
@shiva-appani-gep The above PR https://github.com/Azure/azure-cli/pull/25526 is now merged. The fix for this issue will be released as a part of this milestone: https://github.com/Azure/azure-cli/milestone/127
