### ISSUE TITLE
az stream-analytics output create for ADX

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/azure-cli#25459]
Azure Stream Analytics supports many types of outputs.

Creating these output types using the az CLI  command is documented, most of the time.

The Azure Data Explorer output seems to be missing.

Please document how to create a stream analytics output for an Azure Data Explorer output (especially the output type).

Additionally, the same goes for this other (bicep) [documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.streamanalytics/streamingjobs/outputs?pivots=deployment-language-bicep).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d25b5bfc-618f-620a-cf4b-c6c9f387b097
* Version Independent ID: 5dab31b3-9b65-b74b-feaf-2cd5be923745
* Content: [az stream-analytics output](https://learn.microsoft.com/en-us/cli/azure/stream-analytics/output?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/stream-analytics/output.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/stream-analytics/output.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by sandervandevelde** [comment]
Any update?

**Comment by ZengTaoxu** [comment]
Hello sandervandevelde, there seems to be a reference to create a stream analytics output for an Azure Data Explorer output in the documentation.
https://learn.microsoft.com/en-us/azure/templates/microsoft.streamanalytics/streamingjobs/outputs?pivots=deployment-language-bicep#azuredataexploreroutputdatasourceproperties:~:text=AzureDataExplorerOutputDataSource

**Comment by sandervandevelde** [comment]
Thanks, I updated the original [MS Learn question](https://learn.microsoft.com/en-us/answers/questions/1180594/how-to-create-azure-data-explorer-output-connectio?page=1&orderby=Helpful&comment=answer-1175735#newest-answer-comment)
