### ISSUE TITLE
Can't create vpn connection --shared-key not working

### ISSUE THREAD

**Issue by dky** [Azure/azure-cli#2546]
Hello, 

I'm attempting to create a VPN connection with the following:

az network vpn-connection create --verbose --name vpncn --resource-group defaultRg --vnet-gateway1 "defaultgateway" --local-gateway2 "localgateway" --shared-key 'abcd12345677'

however I keep getting:

--shared-key is required for VNET-to-VNET or Site-to-Site connections.

Am I doing something wrong?

**Comment by tjprescott** [comment]
When you run `az --version` what do you see?  What OS are you using and what shell?

**Comment by tjprescott** [comment]
My first thoughts are you might be using a version of the CLI that didn't incorporate fix for #2054. My second thought is that you should not quote your values. Specifically, when I tried to repro, using `'abcd1234'` will cause the deployment to fail because the quotes are included in the string.

**Comment by dky** [comment]
Hello, I'm on OSX Sierra 10.12.3

dky@mba ~ $ az --version
azure-cli (0.1.2rc1)

acs (0.1.2rc1)
appservice (0.1.1b3)
batch (0.1.1b3)
cloud (0.1.2rc1)
component (0.1.1rc1)
configure (0.1.2rc1)
container (0.1.1b2)
core (0.1.2rc1)
documentdb (0.1.1b1)
feedback (0.1.2rc1)
iot (0.1.1b2)
keyvault (0.1.1b4)
network (0.1.2rc1)
nspkg (0.1.2)
profile (0.1.2rc1)
redis (0.1.1b2)
resource (0.1.2rc1)
role (0.1.2rc1)
sql (0.1.1b3)
storage (0.1.2rc1)
vm (0.1.2rc1)

Python (Darwin) 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]


dky@mba ~ $ bash --version
GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

I'll check out that fix #2054. 

Thanks for pointing me to it.

**Comment by dky** [comment]
az was installed via pip. I supposed it would fetch the latest version but I guess not.

Here was the command I used:

pip install --user azure-cli

**Comment by tjprescott** [comment]
Hi @dky yes, you have an old version of the CLI. Try: `pip install --upgrade --user azure-cli`

**Comment by tjprescott** [comment]
It will install the latest, but if you had an old version on there that lingered, it would use that. You can force it to reinstall with `pip install --user azure-cli -I`

**Comment by dky** [comment]
@tjprescott, Thank you, I'll update and give it another shot.
