### ISSUE TITLE
[ams] `ams`'s `retry` decorator never fails

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#25474]
I accidentally discovered a problem with `ams` module, when searching for occurrences of `2020-04-01-preview` API.

In `2022-04-01`, `RoleAssignmentsOperations` changes `list` method to `list_for_subscription`:

https://github.com/Azure/azure-rest-api-specs/blob/b02ad2011daebdaa4ffc1b0b338181a464d49c47/specification/authorization/resource-manager/Microsoft.Authorization/preview/2020-04-01-preview/authorization-RoleAssignmentsCalls.json#L392-L397

```json
    "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/roleAssignments": {
      "get": {
        "tags": [
          "RoleAssignments"
        ],
        "operationId": "RoleAssignments_List",
```

https://github.com/Azure/azure-rest-api-specs/blob/495363bc011ce917f579adc1a5209073565d37f4/specification/authorization/resource-manager/Microsoft.Authorization/stable/2022-04-01/authorization-RoleAssignmentsCalls.json#L37-L42

```json
    "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/roleAssignments": {
      "get": {
        "tags": [
          "RoleAssignments"
        ],
        "operationId": "RoleAssignments_ListForSubscription",
```

so this line will fail:

https://github.com/Azure/azure-cli/blob/8058c09a65b023f3241e9519c72c81ea0ff4905f/src/azure-cli/azure/cli/command_modules/ams/operations/sp.py#L299

However, the `retry` decorator has a bug:

https://github.com/Azure/azure-cli/blob/8058c09a65b023f3241e9519c72c81ea0ff4905f/src/azure-cli/azure/cli/command_modules/ams/operations/sp.py#L245-L258

`retry_time` will always be < `_RETRY_TIMES`, so line 255 will never be hit and the error will be silenced.

See the doc for `range`: https://docs.python.org/3/library/stdtypes.html#typesseq-range

_Originally posted by @jiasli in https://github.com/Azure/azure-cli/issues/25452#issuecomment-1430717609_

### TODO

1. Use the new `list_for_subscription` method
2. Fix the incorrect `retry` decorater
3. Re-record tests

**Comment by jiasli** [comment]
Looks like there is no code owner under `.github/CODEOWNERS`: https://github.com/Azure/azure-cli/blob/32ab2fae8a228249020db4d3306617e7f2439a8e/.github/CODEOWNERS

**Comment by jiasli** [comment]
Also, consider removing 

https://github.com/Azure/azure-cli/blob/8058c09a65b023f3241e9519c72c81ea0ff4905f/src/azure-cli/azure/cli/command_modules/ams/operations/sp.py#L190-L205

and using `assign_identity` provided by Azure CLI core:

https://github.com/Azure/azure-cli/blob/4dda3fce6ba56b78bd7be45cbd828f270c36a6d6/src/azure-cli-core/azure/cli/core/commands/arm.py#L712-L750

**Comment by jsntcy** [comment]
@hivyas from media service team to take a look.
