### ISSUE TITLE
az bicep install error

### ISSUE THREAD

**Issue by vinaydevmd** [Azure/azure-cli#25471]
### Related command

PS C:\Program Files\PowerShell\7> az bicep install
Error while attempting to retrieve the latest Bicep version: HTTPSConnectionPool(host='downloads.bicep.azure.com', port=443): Max retries exceeded with url: /releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))).
PS

### Resource Provider

bicep

### Description of Feature or Work Requested

Getting error while running az bicep install in my office network, whereas its working fine in my personal laptop.
Same version of powershell and azure CLI.
I need help regarding where to fix this issue in my corporate network ?

### Minimum API Version Required

2.045

### Swagger PR link / SDK link

Getting error while running az bicep install in my office network, whereas its working fine in my personal laptop.
Same version of powershell and azure CLI.
I need help regarding where to fix this issue in my corporate network ?

### Target Date

2023-02-16

### Additional context

Getting error while running az bicep install in my office network, whereas its working fine in my personal laptop.
Same version of powershell and azure CLI.
I need help regarding where to fix this issue in my corporate network ?

**Comment by vinaydevmd** [comment]
Bicep is also installed externally but below command is also not working,

az deployment sub create --location eastus --confirm-with-what-if --template-file main.bicep --parameters environmentType='dev'
Error while attempting to retrieve the latest Bicep version: HTTPSConnectionPool(host='downloads.bicep.azure.com', port=443): Max retries exceeded with url: /releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))).

**Comment by vinaydevmd** [comment]
PS C:\Program Files\PowerShell\7> az bicep install --debug
cli.knack.cli: Command arguments: ['bicep', 'install', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x033EA388>, <function OutputProducer.on_global_arguments at 0x035B7B20>, <function CLIQuery.on_global_arguments at 0x035D5778>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'bicep': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: resource                  0.042        47       207
cli.azure.cli.core: Total (1)                 0.042        47       207
cli.azure.cli.core: Loaded 47 groups, 207 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : bicep install
cli.azure.cli.core: Command table: bicep install
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x04326DF0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\vinay.dev\.azure\commands\2023-02-15.21-34-35.bicep_install.18088.log'.
az_command_data_logger: command args: bicep install --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x04355100>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x043551D8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x04363610>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x035B7B68>, <function CLIQuery.handle_query_parameter at 0x035D57C0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x043635C8>]
urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool: https://aka.ms:443 "GET /BicepLatestRelease HTTP/1.1" 301 0
urllib3.connectionpool: Starting new HTTPS connection (1): downloads.bicep.azure.com:443
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 699, in urlopen
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 382, in _make_request
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 1010, in _validate_conn
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py", line 416, in connect
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 439, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py", line 755, in urlopen
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='downloads.bicep.azure.com', port=443): Max retries exceeded with url: /releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 178, in get_bicep_latest_release_tag
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/api.py", line 75, in get
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/api.py", line 61, in request
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 542, in request
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 677, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 677, in <listcomp>
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 237, in resolve_redirects
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/sessions.py", line 655, in send
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='downloads.bicep.azure.com', port=443): Max retries exceeded with url: /releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3648, in install_bicep_cli
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 128, in ensure_bicep_installation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 182, in get_bicep_latest_release_tag
azure.cli.core.azclierror.ClientRequestError: Error while attempting to retrieve the latest Bicep version: HTTPSConnectionPool(host='downloads.bicep.azure.com', port=443): Max retries exceeded with url: /releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))).

cli.azure.cli.core.azclierror: Error while attempting to retrieve the latest Bicep version: HTTPSConnectionPool(host='downloads.bicep.azure.com', port=443): Max retries exceeded with url: /releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))).
az_command_data_logger: Error while attempting to retrieve the latest Bicep version: HTTPSConnectionPool(host='downloads.bicep.azure.com', port=443): Max retries exceeded with url: /releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))).
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x04326F10>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 4.729 seconds (init: 1.864, invoke: 2.865)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3584 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\vinay.dev\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@vinaydevmd Thanks for reaching out to us and reporting this issue. Could you please follow the steps mentioned in the below article depending on your environment to install the bicep CLI ? Hope this helps.

- [Linux](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#linux)
- [macOS](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#macos)
- [Windows](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#windows)

**Comment by navba-MSFT** [comment]
@vinaydevmd I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by vinaydevmd** [comment]
Hi,
Will check and update you soon.

Br\Vinay

**Comment by navba-MSFT** [comment]
Sure @vinaydevmd.

**Comment by vinaydevmd** [comment]
@navba-MSFT - I followed your steps to install on windows node, bicep will install and it works fine. but still the command az bicep calls still failes with same SSL issue.

I finally figured it out to set and environmental variable "AZURE_CLI_DISABLE_CONNECTION_VERIFICATION" set to "1" then run the az bicep install command, now it ran well with warning!! as shown below

cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x032C7BF8>, <function CLIQuery.handle_query_parameter at 0x032E5850>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x04072658>]
urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'aka.ms'. Adding certificate verification is strongly advised. See: [https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings](https://urldefense.proofpoint.com/v2/url?u=https-3A__nam11.safelinks.protection.outlook.com_-3Furl-3Dhttps-253A-252F-252Furllib3.readthedocs.io-252Fen-252F1.26.x-252Fadvanced-2Dusage.html-2523ssl-2Dwarnings-26data-3D05-257C01-257Cd.piwinski-2540avanade.com-257C31196803c2f840d26a3e08db0f867bca-257Ccf36141cddd745a7b073111f66d0b30c-257C0-257C0-257C638120842498859732-257CUnknown-257CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0-253D-257C3000-257C-257C-257C-26sdata-3DgE32W0cj-252B1ErUNlbL3tpwyJy1W3VTTTmMXmEmWCK3UA-253D-26reserved-3D0&d=DwMFAg&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=wCknhlxjOKWs85JQhNovAPXPDVnZPq3mSU9al_TQ4k0&m=k6BkWJuUKnGTnrJ_GUSwdm1TnH9_77DwvIJfYxG1RGDdH8JhFZZX6dQxz2TtQ1_r&s=iAviMuRtfmaLuU3MWASFUTUP332xjs_g4znsY8r4N64&e=)
urllib3.connectionpool: [https://aka.ms:443](https://urldefense.proofpoint.com/v2/url?u=https-3A__nam11.safelinks.protection.outlook.com_-3Furl-3Dhttps-253A-252F-252Faka.ms-252F-26data-3D05-257C01-257Cd.piwinski-2540avanade.com-257C31196803c2f840d26a3e08db0f867bca-257Ccf36141cddd745a7b073111f66d0b30c-257C0-257C0-257C638120842498859732-257CUnknown-257CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0-253D-257C3000-257C-257C-257C-26sdata-3DixUu4m3T0rZl4ekAYIl-252BRr5mY7vOLh5Zdxoz5YY5IbY-253D-26reserved-3D0&d=DwMFAg&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=wCknhlxjOKWs85JQhNovAPXPDVnZPq3mSU9al_TQ4k0&m=k6BkWJuUKnGTnrJ_GUSwdm1TnH9_77DwvIJfYxG1RGDdH8JhFZZX6dQxz2TtQ1_r&s=gNNZXzF0JoMfl1D3Fb7pJObQBbNdf8DPw_9PJqgW-c8&e=) "GET /BicepLatestRelease HTTP/1.1" 301 0
urllib3.connectionpool: Starting new HTTPS connection (1): downloads.bicep.azure.com:443
D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'downloads.bicep.azure.com'. Adding certificate verification is strongly advised. See: [https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings](https://urldefense.proofpoint.com/v2/url?u=https-3A__nam11.safelinks.protection.outlook.com_-3Furl-3Dhttps-253A-252F-252Furllib3.readthedocs.io-252Fen-252F1.26.x-252Fadvanced-2Dusage.html-2523ssl-2Dwarnings-26data-3D05-257C01-257Cd.piwinski-2540avanade.com-257C31196803c2f840d26a3e08db0f867bca-257Ccf36141cddd745a7b073111f66d0b30c-257C0-257C0-257C638120842498859732-257CUnknown-257CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0-253D-257C3000-257C-257C-257C-26sdata-3DgE32W0cj-252B1ErUNlbL3tpwyJy1W3VTTTmMXmEmWCK3UA-253D-26reserved-3D0&d=DwMFAg&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=wCknhlxjOKWs85JQhNovAPXPDVnZPq3mSU9al_TQ4k0&m=k6BkWJuUKnGTnrJ_GUSwdm1TnH9_77DwvIJfYxG1RGDdH8JhFZZX6dQxz2TtQ1_r&s=iAviMuRtfmaLuU3MWASFUTUP332xjs_g4znsY8r4N64&e=)
urllib3.connectionpool: [https://downloads.bicep.azure.com:443](https://urldefense.proofpoint.com/v2/url?u=https-3A__nam11.safelinks.protection.outlook.com_-3Furl-3Dhttps-253A-252F-252Fdownloads.bicep.azure.com-252F-26data-3D05-257C01-257Cd.piwinski-2540avanade.com-257C31196803c2f840d26a3e08db0f867bca-257Ccf36141cddd745a7b073111f66d0b30c-257C0-257C0-257C638120842498859732-257CUnknown-257CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0-253D-257C3000-257C-257C-257C-26sdata-3DpNkBSxr3jcpSFjR6gQeACO7NDbsm5eXX1oHYvxvIfKs-253D-26reserved-3D0&d=DwMFAg&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=wCknhlxjOKWs85JQhNovAPXPDVnZPq3mSU9al_TQ4k0&m=k6BkWJuUKnGTnrJ_GUSwdm1TnH9_77DwvIJfYxG1RGDdH8JhFZZX6dQxz2TtQ1_r&s=Lvy8mLbgSjUx-Ld822011ntsyioZXl9z7ImQ-jHAS_8&e=) "GET /releases/latest HTTP/1.1" 200 37694
Installing Bicep CLI v0.14.46...
Successfully installed Bicep CLI to "C:\Users\vinay.dev\.azure\bin\bicep.exe".


Can you help me what really blocking in my corporate network ? , so it helps me to fix the root cause.

**Comment by navba-MSFT** [comment]
@vinaydevmd For the Azure CLI to work behind a proxy refer this article. https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#work-behind-a-proxy

For Linux environment, refer [this](https://github.com/jiasli/azure-notes/blob/master/cli/proxy-cert-linux.md).  
For Windows environment refer [this](https://github.com/jiasli/azure-notes/blob/master/cli/proxy-cert-win.md).

Hope this helps.

**Comment by navba-MSFT** [comment]
@vinaydevmd I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@vinaydevmd The action is pending on you to follow the above suggestions and check if that helps. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by dean-azure** [comment]
I am having the same issue still.   I tried the workarounds in this post

https://github.com/Azure/azure-cli/issues/25471#issuecomment-1432567050

But I still cannot get bicep to install locally and we are not using any proxy servers of any kind.   My co-workers are able to execute

az bicep install

without issue.   I am able to install using the same on my personal laptop but on my work laptop where I need it most, i continue to get the error


az bicep install
**Error while attempting to retrieve the latest Bicep version: HTTPSConnectionPool(host='aka.ms', port=443): Max retries exceeded with url: /BicepLatestRelease (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))).**
