### ISSUE TITLE
[iot] `identity_assignment` is called on another thread

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#25479]
I discovered a problem with `iot` module:

https://github.com/Azure/azure-cli/blob/9ef066f0571b8c4f03af32c439e669a14b563b85/src/azure-cli/azure/cli/command_modules/iot/custom.py#L588-L590

`polling=True` causes SDK to start a separate thread to do the LRO polling. Even if `identity_assignment` fails, it fails in that separate thread, so the main thread running the CLI command still succeeds, which is not expected.

_Originally posted by @jiasli in https://github.com/Azure/azure-cli/issues/25452#issuecomment-1430959244_

**Comment by yonzhan** [comment]
route to service team

**Comment by jiasli** [comment]
Please also see https://github.com/Azure/azure-cli/pull/17185

**Comment by vilit1** [comment]
Merged. closing issue
