### ISSUE TITLE
Automate aggregation of release notes upon each release.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-cli#2547]
Aggregate the `HISTORY.rst`s as a "release notes" as part of a CI task so we can pass the changes along to documentation writers and partner teams that maintain samples, etc.

**Comment by tjprescott** [comment]
@derekbekoe is this still relevant now that updating the HISTORY file is part of the PR process?

**Comment by derekbekoe** [comment]
The request is for a script that looks through all the HISTORY files and creates a single aggregate.
Also, in a single HISTORY, the script has to potentially go through multiple older versions in the history file. Not just the last release.
