### ISSUE TITLE
[iot] Temp files generated by `test_certificate_lifecycle` are not deleted

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#25481]
**Related command**
`az iot`

**Describe the bug**
`iot` test `test_certificate_lifecycle` generates some temp files:

- testcert-chain.pem
- testcert.cer
- testkey.pvk
- verify.cer

They are not deleted after the test finishes. 

When someone is bumping API versions and run `iot` tests, these files can easily be checked into the source code via `git add .`. This will also trigger CredScan failures when submitted to GitHub.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Non customer-reported issue. Adding Service team to look into this. 

@Azure/azure-iot-cli-triage. Could you please look into this issue ?

**Comment by digimaun** [comment]
This should be resolved from the linked PR merged on March 1st. We can re-open if still an issue.
