### ISSUE TITLE
az webapp deploy does not auto-detect zip file type if there are more than one '.'s in the file name

### ISSUE THREAD

**Issue by AlainSchoorl** [Azure/azure-cli#25497]
## Describe the bug

**Command Name**
`az webapp deploy`

**Warnings:**
```
Deployment type: static. To override deployment type, please specify the --type parameter. Possible values: war, jar, ear, zip, startup, script, static
```

**Errors:**
```
An error occured during deployment. Status Code: 400, Details: "Path must be defined for type=static"
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Have a webapp that can be deployed to in Azure_
- _Create a zip that can be deployed to that web app_
- _Name that zip test.example.zip_
- `az webapp deploy -n {webAppName} -g {resourceGroupName} --src-path test.example.zip`

## Expected Behavior
The command should automatically detect that the file is a zip and use deployment type "zip" instead of deployment type "static".

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0

Extensions:
azure-devops 0.26.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context
The command works for a file named `example.zip`, it appears to not work when more '.'s are added to the file name.

**Comment by yonzhan** [comment]
route to CXP team
