### ISSUE TITLE
Azure pipeline fails when using 'az acr build' task with AzureCli@2 failOnStandardError=true

### ISSUE THREAD

**Issue by roelofvdv** [Azure/azure-cli#25499]
I have a pipeline set up for which I would like to enable failOnStandardError=true, but I can't because az acr build writes messages to the error stream which I don't think are really errors. If I omit failOnStandardError, my build succeeds.

![image](https://user-images.githubusercontent.com/3512379/219619549-c1dc554f-46e2-4f92-94a1-2ee06b734803.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by junczhu** [comment]
I am going to help with this issue

**Comment by junczhu** [comment]
Copied from https://github.com/Azure/azure-cli/issues/12946#issuecomment-1072043736:

Your script shouldn't decide whether a command is successful based on stderr. It should check the exit code instead. Please see https://github.com/Azure/azure-cli#exit-codes

If you want to disable the warning, there is a global argument --only-show-errors to disable warnings for a specific command. You may also disable warnings for all commands with

az config set core.only_show_errors=True
For more info, please see https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration

**Comment by roelofvdv** [comment]
@junczhu thanks for the clarification!
To me it feels a bit quirky, but then again, I'm not that proficient in shell scripting. I'm used to things throwing an exception.

In my case, I have a AzureCLI@2 task using Powershell Core. This task executes multiple statements sequentially.
If I were to have to check the exit code, I would have to do that after every statement. That feels off.

I'll go with your suggestion for now.
