### ISSUE TITLE
az functionapp keys set: Fails with CryptographyDeprecationWarning on Microsoft Build Agents (py 3.10.8, cli 2.45.0)

### ISSUE THREAD

**Issue by runtimeware** [Azure/azure-cli#25505]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az functionapp keys set`

**Describe the bug**
Attempting to set keys using az functionapp keys set results in a CryptographyDeprecationWarning error:

`##[error]/opt/az/lib/python3.10/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated`

Note that this problem is happening on Python 3.10.8 w/ CLI v 2.45.0 (the same configuration as the Microsoft ADO Build Agents)

**To Reproduce**
Command:
`az functionapp keys set -g $(rg) -n 'FunctionAppName' --key-type functionKeys --key-name 'KeyName'--key-value='ValueXYZ' --output none`

**Expected behavior**
Keys should be set without any problems.

**Environment summary**
Described above.  Python 3.10.8 w/ cli 2.45.0.  Note that the same configuration is on the current Microsoft Build agents

**Additional context**
Nothing else needed to reproduce

**Comment by runtimeware** [comment]
Looks like this is related to #25406

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@runtimeware That is correct! This has been fixed as part of [this PR](https://github.com/Azure/azure-cli/pull/25472) and should be part of the next release.

**Comment by oishii-code** [comment]
@PramodValavala-MSFT When can I expect the next release to be available?

**Comment by PramodValavala-MSFT** [comment]
@runtimeware @oishii-code This should be part of the next release on 2023-03-07.
