### ISSUE TITLE
[App Service] [Discussion] Automatically set default web app setting after creating a new one

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2551]
#2072 was resolved by the new `az configure -d` flag via #2414 (yay!), but I wanted to make sure we captured the discussion to automatically set the default web setting when you create a new one. That way, you can call `az appservice web create`, and then immediately run commands on it (e.g. `browse`), without needing to specify the name again or explicitly call `az configure -d web=foo` manually.

Instead of doing (assuming you have a default group already set):

```
az appservice web create -n foo
az configure -d web=foo
az appservice web browse
```

You could do this:

```
az appservice web create -n foo
az appservice web browse
```

**Comment by JasonRShaver** [comment]
We would like to get more feedback on the current default experience (explicit setting), in the future we will look at implicit setting of defaults on creates (where it makes sense)
