### ISSUE TITLE
CLI 2.45.0 breaks Github Actions that tried to install a specific version of Bicep

### ISSUE THREAD

**Issue by graemefoster** [Azure/azure-cli#25510]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
Run on Github actions
az bicep install --version <version> 
az bicep version
<outputs latest bicep version. Not installed one>

**Describe the bug**
New behaviour (use_binary_from_path) / if_found_in_ci has broken Bicep pinning by users. Coupled with breaking changes in Bicep versions, this has resulted in broken CI production build / deploys.

**To Reproduce**
From a Github Action
az bicep install --version <version> 
az bicep build --file main.bicep

#metadata in published file is no longer the explicitly installed bicep version

**Expected behavior**
Either document a breaking change (https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md) doesn't call this as breaking, or revert it to being intuitive where an explicit az bicep install results in the expected version being used.

**Environment summary**
Github Runner ubuntu:latest

**Additional context**
None. This has broken production builds.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@graemefoster Thanks for the feedback! We will review and update accordingly.

In the meantime, setting the following config value in your scripts should fix build pipelines.

```sh
az config set bicep.use_binary_from_path=false
```
