### ISSUE TITLE
How to completely remove azure-cli in macOS? & How to update/upgrade azure-cli?

### ISSUE THREAD

**Issue by Wyvern** [Azure/azure-cli#2552]
Is there a way to update/upgrade itself in az command? or uninstall/remove itself?

**Comment by derekbekoe** [comment]
@Wyvern There is the `az component update` command.
Also, how was the CLI installed?

If installed with `pip`,  you can uninstall with:
`$ pip uninstall -y $(pip freeze | grep azure-cli-) && pip uninstall -y azure-cli`

If you installed with the interactive script, you can uninstall the two directory and executable you installed into.
By default it would be:
```
rm -r ~/lib/azure-cli
rm ~/bin/az
```

**Comment by JasonRShaver** [comment]
Please reopen if this is still an issue or these instructions did not clear your install out.

**Comment by derekbekoe** [comment]
Also, this is now documented here https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#uninstall.

**Comment by lutzroeder** [comment]
The link above recommends running `brew`, which doesn't work when installed via `pip`.

`~: brew uninstall azure-cli
Error: No such keg: /usr/local/Cellar/azure-cli`

Using the command above doesn't seem to work either:

`~: pip uninstall -y $(pip freeze | grep azure-cli-) && pip uninstall -y azure-cli
Uninstalling azure-cli-acr-2.0.12:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 346, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/azure/cli/command_modules/acr/__init__.py'`

I ran this instead:

`pip list --format=legacy | grep ^azure-* | cut -f 1 -d " " | xargs -n 1 sudo -H pip uninstall -y`

**Comment by sptramer** [comment]
@lutzroeder - The instructions linked do begin with "Uninstall using the method you used to install." In your case, the `pip` uninstallation was correct, if that was how you originally installed.

@derekbekoe - It's probably in an email chain somewhere, but we agreed that the CLI should not be directly installed via `pip`, correct? Do we need to include a warning message somewhere about how doing so may lead to issues?

**Comment by derekbekoe** [comment]
@lutzroeder, @sptramer is correct. `brew uninstall azure-cli` didn't work as there was no brew install previously. The `pip` uninstallation was correct expect `sudo` was required as the CLI was installed into `/usr/local/lib/python2.7/site-packages/` which requires sudo access to delete.

@sptramer We have enough installers now that `pip install` isn't required so there's not a huge need to document it in the docs. I think not including `pip` in our install instructions is enough.
It is possible to install with `pip` successfully but it may require extra Python ecosystem knowledge depending on your platform.
