### ISSUE TITLE
issue with --zone and -z (multiple parameters vs single param)

### ISSUE THREAD

**Issue by jerryfreund** [Azure/azure-cli#25534]
Please note that --zone only takes one parameter (not as suggested in the doc as 'space separated')
while -z is the only one (flag) that can take multiple param.

This is not explicit in the documentation.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c12e07f8-d82f-a9ac-895a-b6d980c8c4c2
* Version Independent ID: 43924bb5-20bd-6a0e-9cdc-90b1db46e599
* Content: [az network public-ip](https://learn.microsoft.com/en-us/cli/azure/network/public-ip?view=azure-cli-latest#az-network-public-ip-create)
* Content Source: [latest/docs-ref-autogen/network/public-ip.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/network/public-ip.yml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by jerryfreund** [comment]
A typo was introduced during the commad exec. my apology. closing the issue.
