### ISSUE TITLE
az policy remediation create fails with error:  'policyAssignmentId' not found in JSON

### ISSUE THREAD

**Issue by XtratusCloud** [Azure/azure-cli#25538]
## Describe the bug
Invoking the `az policy remediation create` command, after update to 2.45.0 version, the command fails.

**Command Name**
policy remediation create

**Errors:**
cli.azure.cli.core.azclierror: (InvalidRequestContent) The request content was invalid and could not be deserialized: 'Required property 'policyAssignmentId' not found in JSON. Path 'properties', line 1, position 127.'.
Code: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Required property 'policyAssignmentId' not found in JSON. Path 'properties', line 1, position 127.'.
az_command_data_logger: (InvalidRequestContent) The request content was invalid and could not be deserialized: 'Required property 'policyAssignmentId' not found in JSON. Path 'properties', line 1, position 127.'.
Code: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Required property 'policyAssignmentId' not found in JSON. Path 'properties', line 1, position 127.'. 

## To Reproduce:
Execute:
az policy remediation create `
--name "XT-ARC-AMA_XT-ARC-AMA-ExtensionAzureArc" `
--resource-discovery-mode "ReEvaluateCompliance" `
--policy-assignment "/subscriptions/23ed27b3-xxxx-yyyy-zzzz-a2a1b1622f33/providers/Microsoft.Authorization/policyAssignments/XT-ARC-AMA" `
--definition-reference-id "XT-ARC-AMA-ExtensionAzureArc" `
--subscription "23ed27b3-xxxx-yyyy-zzzz-a2a1b1622f33"

## Expected Behavior
Work as it did before updating the version, from 2.44.1 (only minor version increased)

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0

Extensions:
account 0.2.3
azure-devops 0.25.0
monitor-control-service 0.3.0
rdbms-connect 1.0.3
scheduled-query 0.5.1
subscription 0.1.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by ferike86** [comment]
Having similar issue with Azure CLI 2.45.0 version, worked fine with previous version 2.41.0:
```
ERROR: (InvalidRequestContent) The request content was invalid and could not be deserialized: 'Required property 'properties' not found in JSON. Path '', line 1, position 2.'.
Code: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Required property 'properties' not found in JSON. Path '', line 1, position 2.'.
```

**Comment by XtratusCloud** [comment]
Executing with `--debug` the PUT request to the management API don't include the parameter `policyAssignmentId` in the body
![image](https://user-images.githubusercontent.com/122672536/220598756-31582667-693d-4611-b369-4ae538064370.png)

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
The `PolicyInsights` module is owned by service team, so add service team member @samarthlakhotia to help take a look~

**Comment by samarthlakhotia** [comment]
Hi, currently taking a look at this issue.

**Comment by samarthlakhotia** [comment]
@zhoxing-ms I found the issue. It is with this function: https://github.com/Azure/azure-cli/blob/9e302e32cea27c09864873831de106a48db129ce/src/azure-cli/azure/cli/command_modules/policyinsights/custom.py#L735 returning None. Making the required change and will add some tests for that change. Will create a PR soon. Thank you.
