### ISSUE TITLE
upgrade nodepool command fails with attributeError on cli 2.45.0

### ISSUE THREAD

**Issue by nkalmar-kx** [Azure/azure-cli#25530]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az aks nodepool upgrade --resource-group "rg" --cluster-name "cn" --name "system" --kubernetes-version "1.25.5" --max-surge 1

**Describe the bug**

The command exists with attribute error for --kubernetes-version:
AttributeError: 'AgentPool' object has no attribute 'kubernetes_version'

This happens with az cli 2.45.0, but after downgrading to 2.43.0, command completes and nodepool gets updated.

**To Reproduce**

Try to upgrade nodepool version with the above command

**Expected behavior**

Command completes without error and nodepool is updated to the given k8 version

**Environment summary**

az installed with pip.
```
az --version
azure-cli                         2.45.0

core                              2.45.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/xy/.azure/cliextensions'

Python (Linux) 3.10.8 (main, Feb  3 2023, 09:43:57) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.z
```

```
lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

```
uname -a
Linux LPTP2239 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**

**Comment by nkalmar-kx** [comment]
![command line error](https://user-images.githubusercontent.com/108936584/220325344-21406a3f-e262-4efc-9ddf-b516d884534a.PNG)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@nkalmar-kx Thanks for the feedback! We will review and update accordingly.

**Comment by teocrispy91** [comment]
I am also facing the same issue while trying to upgrade the nodepool with this command  
az aks nodepool upgrade --cluster-name test90 --name agentpool --resource-group 1-2fe95c3a-playground-sandbox  --kubernetes-version 1.24.9
Azure-cli-version 2.45.0

**Comment by PramodValavala-MSFT** [comment]
@nkalmar-kx @teocrispy91 Thanks again for reporting this! We found the issue and are working up a fix for it.
