### ISSUE TITLE
Delete artifacts from ACR asynchronously

### ISSUE THREAD

**Issue by rguptar** [Azure/azure-cli#25532]
### Related command

az acr repository delete --name $registry_name --image $repository:$tag

### Resource Provider

Microsoft.ContainerRegistry/registries

### Description of Feature or Work Requested

Add a `--no-wait` flag to `az acr repository delete`.

### Minimum API Version Required

N/A

### Swagger PR link / SDK link

N/A

### Target Date

2023-04-01

**Comment by PramodValavala-MSFT** [comment]
@rguptar Thanks for the feedback! We will review and update accordingly.

**Comment by rguptar** [comment]
@PramodValavala-MSFT I see, in that case, I'd like an option where it did not block on the response. Our use case is a bulk delete of images.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@rguptar in that you case you could simply run the command in the background so that it does not block script execution by using postfixing the command with ` &` in bash.

If required, you could check the exit code later on as shown in this [SO post](https://stackoverflow.com/a/1570356/10417839).

**Comment by rguptar** [comment]
@PramodValavala-MSFT The script is non-trivial as memory is exhausted quickly with all the python executions. This is our current script. https://paste.microsoft.com/e6da046d-c778-4bb8-b60d-9536e8f25df6

It would be nice if there was a simple solution to bulk delete images that match a regex for example to reduce the burden on customers.

**Comment by PramodValavala-MSFT** [comment]
@rguptar Thanks for the feedback! Unfortunately, that would have to be a service side enhancement to support deleting multiple images. There is [this feature request](https://feedback.azure.com/d365community/idea/f7bf3193-0d25-ec11-b6e6-000d3a4f0858) which is similar in nature, which you could upvote and comment on for it to gain more traction.

Once supported, Azure CLI should follow suit. In the meantime, there is no change that can be made here. Closing.

**Comment by rguptar** [comment]
@PramodValavala-MSFT I just found out about an acr cli which mostly addresses this problem. https://github.com/Azure/acr-cli
