### ISSUE TITLE
az sql db show-connection-string outputs an invalid azure sql connection string

### ISSUE THREAD

**Issue by philippedurocher** [Azure/azure-cli#25546]
**Related command**
`az sql db show-connection-string -s <server name> -n <database> -c ado.net -a SqlPassword`

**Describe the bug**
The connection string from az cli is not the same as the ones from azure portal
The connection string from az cli is not working after replacing userid and password with my credential

Tried to connect with an AspNet Core 7.0 using Entity Framework Core 7.0.x
Connection string from azure portal is working with AspNet Core 7.0 + EF Core 7.0.x

The connection strings are for an Azure Sql Database

**To Reproduce**
When looking at my database sql connection strings in the azure portal I see this
![image](https://user-images.githubusercontent.com/1459389/220826150-2433a7c3-bf08-4dd3-98ea-e175ba25f0b0.png)

when I run `az sql db show-connection-string` command, I get a connection string like this one
![image](https://user-images.githubusercontent.com/1459389/220828029-a88223c2-88d8-4751-99d4-06e202478913.png)

Some parameters are missing : `Persist Security Info`, `MultipleActiveResultSets`
`Catalog` parameter is replaced by `Database`

**Expected behavior**
The connection strings should be identical (or near identical) as the ones coming from Azure Portal
The connection strings obtained by using show-connection-string command should be working

**Environment summary**
![image](https://user-images.githubusercontent.com/1459389/220827363-8aa3d438-8265-4d69-8df3-f527bb87cfda.png)

Installed using winget

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@philippedurocher  I have submitted a PR to address this issue and it will be merged once approved. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
