### ISSUE TITLE
Failed to install extension on Fedora 37 due to missing files

### ISSUE THREAD

**Issue by som-priani-maersk** [Azure/azure-cli#25540]
Both of the files are not present in the YUM/RPM based distros
https://github.com/Azure/azure-cli/blob/1be1db217c70882bc315cd8c7ef4410f87541a1e/src/azure-cli-core/azure/cli/core/extension/operations.py#L45-L46

Hence  "az extension add.." failed with error
```
cli.azure.cli.core.extension.operations: Linux distro check: Reading from: /etc/apt/sources.list.d/azure-cli.list
cli.azure.cli.core.extension.operations: Linux distro check: An error occurred while checking linux distribution version source list consistency.
cli.azure.cli.core.extension.operations: [Errno 2] No such file or directory: '/etc/apt/sources.list.d/azure-cli.list'
```
/etc/apt/ is part of APT based distros (Debian?)
/etc/lsb-release (is non standard) can be changed to /etc/os-release, which is present in all distros

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by bebound** [comment]
The `check_distro_consistency` function does not interrupt installation, it only outputs some error log.
Can you give the full log?
