### ISSUE TITLE
Reimage Support for Standalone VMs

### ISSUE THREAD

**Issue by srcharug** [Azure/azure-cli#25542]
**Related command**

az vm reimage --name
                        --resource-group
                        --subscription
                        [--temp-disk]
                        [--admin-password]
                        [--custom-data]
                        [--exact-version]

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Reimage operation for standalone VMs is supprted from long time ago through REST API and PS command. We need to start supporting through CLI command as well

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Compute feature

**Comment by zhoxing-ms** [comment]
@srcharug Thanks for creating this feature request~
Could you please use this [Microsoft Internal Feature Request template](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=feature-request&template=Service_team_request.yaml) to add some required details about this requirement? Such as the ainimum API version, Swagger PR link and target date?

**Comment by srcharug** [comment]
Added a new issue mentioning the required details - https://github.com/Azure/azure-cli/issues/25722

**Comment by zhoxing-ms** [comment]
Thanks for creating the new issue. Let me close the duplicated issue first
