### ISSUE TITLE
az aks create - 'charmap' codec can't decode byte 0x9d in position 573: character maps to <undefined>

### ISSUE THREAD

**Issue by scryer-David** [Azure/azure-cli#25552]
**Related command**
`az aks create -n test-dev-cluster -g test-dev-group`

**Describe the bug**
Running the most basic version of `az aks create` with only a name parameter and resource group parameter is returning this error: `'charmap' codec can't decode byte 0x9d in position 573: character maps to <undefined>` , and subsequently nothing is created in the relevant resource group.

**Environment summary**

Running az-cli version 2.45.0, python version 3.10.5 on Windows inside of a bash shell.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@scryer-David We will now proceed to close this thread. If there are further questions, please open a new issue and we will gladly continue the discussion.
