### ISSUE TITLE
MR S 

### ISSUE THREAD

**Issue by FGN470** [Azure/azure-cli#25554]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Please provide detailed CLI command and error log.

**Comment by SaurabhSharma-MSFT** [comment]
@FGN470 Please let us know if you need any help.

**Comment by SaurabhSharma-MSFT** [comment]
@FGN470 We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
