### ISSUE TITLE
Cannot list the public-ips

### ISSUE THREAD

**Issue by cdurepo** [Azure/azure-cli#25555]
## Describe the bug

**Command Name**
`az network public-ip list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'standard_medium'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 561, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 508, in load_arguments
    loader.load_arguments(command)  # this adds entries to the argument registries
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/network/__init__.py", line 50, in load_arguments
    load_arguments(self, command)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/network/_params.py", line 113, in load_arguments
    c.argument('sku', arg_group='Gateway', help='The name of the SKU.', arg_type=get_enum_type(ApplicationGatewaySkuName), default=ApplicationGatewaySkuName.standard_medium.value)
                                                                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'standard_medium'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- az login
- `az network public-ip list -o {}`

## Expected Behavior
I expected to get a list of the public-ips 

## Environment Summary
```
Linux-6.1.0-1-amd64-x86_64-with-glibc2.36, Debian GNU/Linux bookworm/sid
Python 3.11.2
Installer: DEB

azure-cli 2.45.0

Extensions:
account 0.2.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```
## Additional Context
I see this was an error that was posted before, the fix was to update to a version that a few versions below mine.

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
@cdurepo Are there any pre-steps? I cannot reproduce it:
![image](https://user-images.githubusercontent.com/12371639/221081265-57d65967-9e9a-4024-b69a-74675ed457dd.png)

**Comment by cdurepo** [comment]
I am not using the -g option.  My goal is to get a list of all the public IPs across all the groups and subscriptions.

**Comment by necusjz** [comment]
> I am not using the -g option. My goal is to get a list of all the public IPs across all the groups and subscriptions.

Without `-g` also works for me:
![image](https://user-images.githubusercontent.com/12371639/221091706-d89b15f2-a3f0-425b-8ae6-b8d69fc9c6f1.png)
