### ISSUE TITLE
Attempted to install a new registry container on Azure Stack Hub using az cli but I’m receiving an error message Invalid API version 

### ISSUE THREAD

**Issue by oliverce1911** [Azure/azure-cli#25572]
I am using Windows Server 2019 as my adminVM to deploy a container registry on Azure Stack Hub.  My current version of az cli is 2.27.0.  
Here is the error I'm receiving.
C:\>az acr login --name ceoregistry
(InvalidApiVersionParameter) The api-version '2021-04-01' is invalid. The supported versions are '2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04,2015-11-01,2015-11-01'.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by oliverce1911** [comment]
Any mitigation steps I need to take in order to resolve the issue?

**Comment by navba-MSFT** [comment]
@oliverce1911 Thanks for reaching out to us and reporting this issue. Could you please upgrade to the [_most recent version_ ](https://learn.microsoft.com/en-us/cli/azure/update-azure-cli)of Azure CLI and check if you are still facing the same issue ? Awaiting your reply.

**Comment by oliverce1911** [comment]
I have upgraded to the latest az cli and I received the same results.  

C:\>az --version
azure-cli                         2.45.0

core                              2.45.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\ceoadmin\.azure\cliextensions'

Python (Windows) 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:37:59) [MSC v.1933 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Unable to check if your CLI is up-to-date. Check your internet connection.

C:\>az login
A web browser has been opened at https://adfs.factory.contosolabs.com/adfs/oauth2/authorize/. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
[
  {
    "cloudName": "factory",
    "homeTenantId": "29c6fdb5-8ccf-4ceb-95a9-005571449798",
    "id": "188fe9c4-f66c-45aa-9b56-c893ec31ba45",
    "isDefault": true,
    "managedByTenants": null,
    "name": "SRE-Testing",
    "state": "Enabled",
    "tenantId": "29c6fdb5-8ccf-4ceb-95a9-005571449798",
    "user": {
      "name": "choliv@restonedge.local",
      "type": "user"
    }
  }
]

C:\>az acr login --name ceoregistry
(InvalidApiVersionParameter) The api-version '2021-04-01' is invalid. The supported versions are '2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04,2015-11-01,2015-11-01'.

**Comment by navba-MSFT** [comment]
@oliverce1911 I tried to connect to my ACR and it worked fine. I ran the CLI command with `--debug` parameter and found that it was using version: `2021-04-01`.

```
C:\> az --version
azure-cli                         2.45.0
```

see below:

```
C:\> az acr login --name MyACRName
Login Succeeded
```

Could you please run your command with with `az acr login --name ceoregistry --debug` parameter and share the debug output here ? Please remove the sensitive information before sharing it.

Also let me know the region where you have this this ACR resource. Awaiting your reply.

**Comment by oliverce1911** [comment]
Could you please run your command with with az acr login --name ceoregistry --debug parameter and share the debug output here ? Please remove the sensitive information before sharing it. 
C:\>az acr login --name ceoregistry --debug
cli.knack.cli: Command arguments: ['acr', 'login', '--name', 'ceoregistry', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01E9A388>, <function OutputProducer.on_global_arguments at 0x02067B20>, <function CLIQuery.on_global_arguments at 0x02085778>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'acr': ['azure.cli.command_modules.acr']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acr                       0.049        32       134
cli.azure.cli.core: Total (1)                 0.049        32       134
cli.azure.cli.core: Loaded 32 groups, 134 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : acr login
cli.azure.cli.core: Command table: acr login
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x04316D60>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\ceoadmin\.azure\commands\2023-03-01.20-54-15.acr_login.4752.log'.
az_command_data_logger: command args: acr login --name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x0433DEC8>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x0434E580>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x0434E658>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x02067B68>, <function CLIQuery.handle_query_parameter at 0x020857C0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x0434E610>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\ceoadmin\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\ceoadmin\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'issuer': 'https://adfs.factory.contosolabs.com/adfs/29c6fdb5-8ccf-4ceb-95a9-005571449798/', 'authorization_endpoint': 'https://adfs.factory.contosolabs.com/adfs/oauth2/authorize/', 'token_endpoint': 'https://adfs.factory.contosolabs.com/adfs/oauth2/token/', 'jwks_uri': 'https://adfs.factory.contosolabs.com/adfs/discovery/keys', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'client_secret_basic', 'private_key_jwt', 'windows_client_authentication'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token', 'code token', 'code id_token token'], 'response_modes_supported': ['query', 'fragment', 'form_post'], 'grant_types_supported': ['authorization_code', 'refresh_token', 'client_credentials', 'urn:ietf:params:oauth:grant-type:jwt-bearer', 'implicit', 'password', 'srv_challenge', 'urn:ietf:params:oauth:grant-type:device_code', 'device_code'], 'subject_types_supported': ['pairwise'], 'scopes_supported': ['email', 'winhello_cert', 'aza', 'allatclaims', 'openid', 'user_impersonation', 'vpn_cert', 'logon_cert', '.default', 'profile'], 'id_token_signing_alg_values_supported': ['RS256'], 'token_endpoint_auth_signing_alg_values_supported': ['RS256'], 'access_token_issuer': 'https://adfs.factory.contosolabs.com/adfs/29c6fdb5-8ccf-4ceb-95a9-005571449798/', 'claims_supported': ['aud', 'iss', 'iat', 'exp', 'auth_time', 'nonce', 'at_hash', 'c_hash', 'sub', 'upn', 'unique_name', 'pwd_url', 'pwd_exp', 'mfa_auth_time', 'sid', 'nbf'], 'microsoft_multi_refresh_token': True, 'userinfo_endpoint': 'https://adfs.factory.contosolabs.com/adfs/userinfo', 'capabilities': ['kdf_ver2'], 'end_session_endpoint': 'https://adfs.factory.contosolabs.com/adfs/oauth2/logout', 'as_access_token_token_binding_supported': False, 'as_refresh_token_token_binding_supported': False, 'resource_access_token_token_binding_supported': False, 'op_id_token_token_binding_supported': False, 'rp_id_token_token_binding_supported': False, 'frontchannel_logout_supported': True, 'frontchannel_logout_session_supported': True, 'device_authorization_endpoint': 'https://adfs.factory.contosolabs.com/adfs/oauth2/devicecode'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.adfs.contosolabs.local/29c6fdb5-8ccf-4ceb-95a9-005571449798/.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.adfs.contosolabs.local/29c6fdb5-8ccf-4ceb-95a9-005571449798/.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: b3b72a04-e18d-477e-8544-ef46fc4f322b
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.factory.contosolabs.com/subscriptions/188fe9c4-f66c-45aa-9b56-c893ec31ba45/resources?$filter=resourceType%20eq%20%27Microsoft.ContainerRegistry%2Fregistries%27&api-version=2021-04-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '3a2206c7-b873-11ed-aed5-001dd8b7000e'
cli.azure.cli.core.sdk.policies:     'CommandName': 'acr login'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.45.0 (MSI) azsdk-python-azure-mgmt-resource/21.1.0b1 Python/3.10.8 (Windows-10-10.0.17763-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.factory.contosolabs.com:443
urllib3.connectionpool: https://management.factory.contosolabs.com:443 "GET /subscriptions/188fe9c4-f66c-45aa-9b56-c893ec31ba45/resources?$filter=resourceType%20eq%20%27Microsoft.ContainerRegistry%2Fregistries%27&api-version=2021-04-01 HTTP/1.1" 400 575
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '2609a1b0-eaa4-4ef9-bccd-b0ac4bf28502'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '2609a1b0-eaa4-4ef9-bccd-b0ac4bf28502'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'FACTORY:20230301T205416Z:2609a1b0-eaa4-4ef9-bccd-b0ac4bf28502'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 01 Mar 2023 20:54:15 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '575'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2021-04-01' is invalid. The supported versions are '2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04,2015-11-01,2015-11-01'."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 290, in acr_login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 450, in get_login_credentials
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_docker_utils.py", line 337, in _get_credentials
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_utils.py", line 109, in get_registry_by_name
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_utils.py", line 88, in get_resource_group_name_by_registry_name
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_utils.py", line 43, in _arm_get_resource_by_name
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/parameters.py", line 138, in get_resources_in_subscription
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 129, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 76, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/resources/v2021_04_01/operations/_operations.py", line 8657, in get_next
azure.core.exceptions.HttpResponseError: (InvalidApiVersionParameter) The api-version '2021-04-01' is invalid. The supported versions are '2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04,2015-11-01,2015-11-01'.
Code: InvalidApiVersionParameter
Message: The api-version '2021-04-01' is invalid. The supported versions are '2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04,2015-11-01,2015-11-01'.

cli.azure.cli.core.azclierror: (InvalidApiVersionParameter) The api-version '2021-04-01' is invalid. The supported versions are '2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04,2015-11-01,2015-11-01'.
Code: InvalidApiVersionParameter
Message: The api-version '2021-04-01' is invalid. The supported versions are '2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04,2015-11-01,2015-11-01'.
az_command_data_logger: (InvalidApiVersionParameter) The api-version '2021-04-01' is invalid. The supported versions are '2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04,2015-11-01,2015-11-01'.
Code: InvalidApiVersionParameter
Message: The api-version '2021-04-01' is invalid. The supported versions are '2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04,2015-11-01,2015-11-01'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x04316E80>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 2.027 seconds (init: 0.484, invoke: 1.543)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4335 in cache
telemetry.check: Negative: The C:\Users\ceoadmin\.azure\telemetry.txt was modified at 2023-03-01 20:53:15.525469, which in less than 600.000000 s

Question 2:
Also let me know the region where you have this ACR resource.
Azure Stack Hub

**Comment by navba-MSFT** [comment]
@oliverce1911 Thanks for sharing the details. I will look into this further and update you.

**Comment by oliverce1911** [comment]
@navba-MSFT thanks for help, the information provided resolved my issue.
