### ISSUE TITLE
Container App Environment vnetConfiguration.outboundSettings

### ISSUE THREAD

**Issue by charlesavos** [Azure/azure-cli#25570]
## Describe the bug
We have been using our Bicep template to deploy container apps for months now with no issues.
Today we got the below error.

The solution was to remove the `environment.properties.vnetConfiguration.outboundSettings` block.
That's okay, but we would like to understand what happened here in more detail.

The [api reference docs](https://learn.microsoft.com/en-us/rest/api/containerapps/managed-environments/create-or-update?tabs=HTTP#vnetconfiguration) indicate that `vnetConfiguration` no longer accepts an `outboundSettings` block. 
Presumably the block ceased to be supported at some point in the last ~24 hours, since we use this bicep command at least daily.
I'm keen to understand what changed here.
Is there an API reference changelog?
I know [this changelog](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/change-log/summary) exists, but that doesn't have any changes in the past 24 hours.
Is there somewhere we should be looking to be alerted of breaking changes like this?

**Command Name**
`az deployment group what-if`

**Errors:**
```
InvalidTemplateDeployment - The template deployment 'v0-7-3' is not valid according to the validation procedure. The tracking id is 'b3d623c3-2e57-44c6-8973-eb4c8b4f858d'. See inner errors for details.
ValidationForResourceFailed - Validation failed for a resource. Check 'Error.Details[0]' for more information.
ManagedEnvironmentInvalidNetworkConfiguration - The environment network configuration is invalid: OutboundSettings is not supported.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Define a Container App Environment with the following 
```
resource environment 'Microsoft.App/managedEnvironments@2022-06-01-preview' = {
...
  properties: {
    vnetConfiguration: {
...
      outboundSettings: {
        outBoundType: 'LoadBalancer'
      }
```
- `az deployment group what-if --template-file {} -g {} --name {} --parameters {} --parameters {}`

## Expected Behavior
`what-if` shows you a diff of the changed your template will make.

## Environment Summary
```
Linux-5.19.0-32-generic-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.8
Installer: DEB

azure-cli 2.44.1 *

Extensions:
containerapp 0.3.20
log-analytics 0.2.2
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```
## Additional Context
We tried this on four different Bicep versions: `0.14.85`, `0.14.46`, `0.14.6` and `0.13.1`, across both Ubuntu and MacOS.

**Comment by zhoxing-ms** [comment]
@Shenglol Could you please help take a look at the `what-if` related issue?

**Comment by shenglol** [comment]
@charlesavos The error was returned by the `Microsoft.App` provider. I would suggest opening a support ticket against the service team to see if there's anything changed on their side.

@zhoxing-ms We may close this since it's not a What-If issue.

**Comment by Wema** [comment]
@charlesavos, I am also running into this issue, did you manage to get a response from the Microsoft.App provider service team?

**Comment by charlesavos** [comment]
Thanks @shenglol, will do 👍

Hi @Wema, no I haven't opened a support ticket yet.
You should be able to fix your problem by removing the part of the `vnetConfiguration` that looks like this:
```
      outboundSettings: {
        outBoundType: 'LoadBalancer'
      }
```
I hope that helps!
