### ISSUE TITLE
az storage blob upload --overwrite does the job and then it throws an error with a warning message.

### ISSUE THREAD

**Issue by JCPuerto** [Azure/azure-cli#25571]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az storage blob upload

**Describe the bug**
In PowerShell when I run `az storage blob upload --account-name myStorageAccount -c myContainer -f myFile --auth-mode login --overwrite;` it does overwrite the existing file but it throws an exception with the message `az : WARNING: Argument '--overwrite' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus`.

Further mode after every AZ command I have the following line of code as recommended by Microsoft so my program fails at this point:

```
if ($? -eq $false) {
    throw "Uploading the file failed!";
}
```

**To Reproduce**
Try to upload a file with the `az storage blob upload ` command and make sure to use the `--overwrite` flag.

**Expected behavior**

- The file should be overwritten and the execution should continue without errors. A warning is ok.
- The last executed command `$?` variable should be false after the `az storage blob upload ` command which means the command ended sucessfully.

**Environment summary**
- Windows PowerShell version: 5.1.20348.1366
- Azure CLI version: 2.45.0

**Additional context**
The PowerShell commands are ran from an Azure Virtual Machine using Managed Identity and RBAC to give the necessary `Reader` and `Storage Blob Data Contributor` roles.

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by MoChilia** [comment]
Hi @JCPuerto! 
I think `$?` variable should be **True** when the command ended successfully in this scenario. I tested `az storage blob upload` with the parameter `--overwrite`, and `$?` was true when the program exited without any error. However, I notice that you have not specified the name of the blob or given a blob url. If you actually forgot to do that, then the program would exit incorrectly and `$?` would be false with the exception "Uploading the file failed!" at this time.
