### ISSUE TITLE
unrecognized arguments: --ssh-key-value .ssh/id_rsa.pub

### ISSUE THREAD

**Issue by SriHarsha001** [Azure/azure-cli#25579]
az version
{
  "azure-cli": "2.45.0",
  "azure-cli-core": "2.45.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "aks-preview": "0.5.104",
    "fleet": "0.1.0"
  }
}

az aks update --name AKScluster --resource-group AKSRG --ssh-key-value .ssh/id_rsa.pub
**unrecognized arguments: --ssh-key-value .ssh/id_rsa.pub**

Documented here - https://learn.microsoft.com/en-us/azure/aks/node-access#prerequisites

https://learn.microsoft.com/en-US/cli/azure/aks?view=azure-cli-latest#az-aks-update

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@SriHarsha001 Can you please upgrade your `aks-preview` version to latest using `az extension update --name aks-preview`.  I am able to see this `ssh-key-value` available.  See below screenshot.  
![image](https://user-images.githubusercontent.com/38112130/223830916-dde4b78e-4b6d-4667-8d1f-c54bee4d2131.png)

Regarding the documentation.  
I have submitted a pull request to update the documentation to include `ssh-key-value` parameter.
