### ISSUE TITLE
`postgres flexible-server create` - Need to enable firewall access for Azure and my local machine

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-cli#25576]
## Describe the feature request
Allow multiple IPs or IP ranges to be passed to `--public-access` parameters

Currently, I have to run the create command and pass 1 ip address, then run another command to create a firewall rule for the 2nd ip address

**Command Name**
`postgres flexible-server create`

## Expected Behavior
`az postgres flexible-server create ... --public-access 0.0.0.0,90.100.115.277`
creates 2 firewall rules
* one for the first ip address that allows all of azure
* one for the second ip address that allows my local machine

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0

Extensions:
acrtransfer 1.1.0
arcdata 1.4.11
azure-dev 0.0.1b456
connectedk8s 1.3.13
connectedmachine 0.5.1
containerapp 0.3.22
containerapp-compose 0.2.2
customlocation 0.1.3
db-up 0.2.7
k8s-configuration 1.7.0
k8s-extension 1.4.0
rdbms-connect 1.0.3
ssh 1.1.3
webapp 0.4.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Non-Customer reported issue. So adding Service team to look into this.

**Comment by navba-MSFT** [comment]
@sunilagarwal, @lfittl-msft, @sr-msft, @niklarin Could you please look into this issue ? Thanks in advance.

**Comment by nachoalonsoportillo** [comment]
@charris-msft Thanks for reporting this issue! The `--public-access` parameter of the `az postgres flexible-server create` command should have allowed the user to only Enable/Disable public access.

However, to make the experience similar to what `az sql server create` supported, it was extended to accept `None`, `0.0.0.0` or a single IP address or range.

For more complex needs, please leverage `az postgres flexible-server firewall-rule create` command.

**Comment by nachoalonsoportillo** [comment]
@yonzhan Please close this one. Thanks!
