### ISSUE TITLE
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info 2.45.0

### ISSUE THREAD

**Issue by DeepMalh44** [Azure/azure-cli#25583]
I am on the latest CLI  2.45.0 version and some of the az commands are giving the Table output unavailable error, for e.g.:

C:\Windows\System32>az network nsg rule list --nsg-name linuxnva-1-nic0-nsg -o table --include-default
Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.

I am on azure-cli version 2.45.0.

Any help on this issue?

**Comment by DeepMalh44** [comment]
@jiasli I saw you were active on resolving similar issue with earlier versions of AZ CLI, so looping you in on this thread  https://github.com/Azure/azure-cli/issues/20348

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
@DeepMalh44 It'll be fixed by https://github.com/Azure/azure-cli/pull/25388 in 2.46.0 on around 03/07.
