### ISSUE TITLE
az acs kubernetes install-cli fails on Windows 10 bash

### ISSUE THREAD

**Issue by xtophs** [Azure/azure-cli#2558]
Permissions error on /usr/local/bin when trying to download kubectl

$ az acs kubernetes install-cli --debug
Downloading client to /usr/local/bin/kubectl
Connection error while attempting to download client ([Errno 13] **Permission denied: '/usr/local/bin/kubectl'**)

**command completes successfully** after making /usr/local/bin writeable
$ sudo chmod 777 /usr/local/bin
$ az acs kubernetes install-cli --debug
Downloading client to /usr/local/bin/kubectl
Application event 'Application.TransformResults' with event data {'event_data': {'result': None}}
Application event 'Application.FilterResults' with event data {'event_data': {'result': None}}

**Versions:**
azure-cli (2.0.1)
acs (2.0.1)

GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by brendandburns** [comment]
This is expected. /usr/local/bin shouldn't be user writeable. you need to either use:

`sudo acs kubernetes install-cli`

or use the `--install-location` to place it in a different location.
