### ISSUE TITLE
az storage blob list does not return nextMarker when combined with certain --query formulations

### ISSUE THREAD

**Issue by MonkeyTennis** [Azure/azure-cli#25595]
**Related command**
az storage blob list --account-name ******* --container-name ****** --num-results 1 --show-next-marker --only-show-errors --include t --query '[?tags.\"a-b\" != null]'

**Describe the bug**
I want to be able to retrieve data about large numbers of blobs using the --query option to avoid returning too much data. However, az storage blob list does not return nextMarker in the json output if combined with certain formulations of the --query option

**To Reproduce**

A blob storage account contains 3 txt files with the tags show below:
|file name|first tag name|second tag name|
|---|---|---|
|wibble.txt|a|a-b|
|wibble2.txt|a||
|wibble3.txt|a-b||

Below are the expected and actual results for different queries:

|query|expected result|actual result|
|---|---|---|
|az storage blob list --account-name ******* --container-name ****** --num-results 2 --show-next-marker --only-show-errors --include t |returns wibble.txt/wibble2.txt with nextMarker (1 more records exist for the query performed)|as expected|
|az storage blob list --account-name ******* --container-name ****** --num-results 2 --show-next-marker --only-show-errors --include t --query '[*]'|returns wibble.txt/wibble2.txt with nextMarker (1 more record exists for the query performed)|as expected|
|az storage blob list --account-name ******* --container-name ****** --num-results 1 --show-next-marker --only-show-errors --include t --query '[?tags.\"a-b\" != null]'|returns wibble.txt with nextMarker (1 more record exists for the query performed)| Not as expected. Returns wibble.txt --> **_with no nextMarker_** <--|

**Expected behavior**
I would expect the third query against blob index tags to return the requested number of results and a continuation token with which to retrieve the next set of results.

**Environment summary**
Windows-10-10.0.19045-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0 *

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1

**Additional context**
In the absence of a fix for the above, can you suggest an efficient way to query large numbers of blobs (potentially millions) using tags as a filter, and iterating through the results with a continuation token.

**Comment by MonkeyTennis** [comment]
I have upgraded to the latest version 2.45.1 but same result.

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by MoChilia** [comment]
Hi @MonkeyTennis!

The working principle of `--query` is to first execute the command and obtain the result in JSON format, then use [JMESPath](https://jmespath.org/) to query from this JSON, and finally filter out the result and return it. 
For the 3rd query you listed, the result JSON before query is something like:
```
[
  {
    "name": "wibble",
      …
    "tags": {
          "a": "",
          "a-b": ""
     }
  }
  {
    "nextMarker": "xxxxx"
  }
]
```
As the second element in the JSON, `nextMarker` is obviously not compatible with `[?tags."a-b" != null]`, so it will be discarded.  Actually, `nextMarker` here points to `wibble2`, not `wibble3`. If your desired effect is to display only the first result, please avoid using `--num-results 1` and instead use [JMESPath syntax](https://jmespath.org/examples.html) like `--query '[?tags."a-b" != null]|[0]'`.

**Comment by MonkeyTennis** [comment]
Hi, I used num-results 1 because I only provided a small set of data, to try and illustrate the point in a simple way.

In reality there are millions of blobs in the container that I need to identify using the criteria --query '[?tags."a-b" != null]'. If this query does not return nextMarker, how do I iterate through millions of blobs without using num-results * (causes an out of memory exception)?

**Comment by MonkeyTennis** [comment]
To put it another way, if I had a record set something like the following:

|record|has tag?|
|---|---|
|1|no|
|5|yes|
|6-999999|no|
|1000000|yes|
|1000001-3999999|no|
|4000000|yes|

What is the most efficient way of returning records 5, 1000000, 4000000 and the other ten million tagged blobs that might be interspersed throughout the data set?

It seems to me that I should filter the results (using --query) and receive a continuation marker due to the large number of records.

**Comment by MoChilia** [comment]
@MonkeyTennis, I got your request. When dealing with massive amounts of data, it's important to use `nextMarker` to mark the starting point for the next query. We will solve the issue ASAP.

**Comment by MoChilia** [comment]
@MonkeyTennis, after reassessing the risks involved, we have decided not to support the feature. However, we suggest two alternative solutions to help you address your issue. Thank you for your understanding.

1.  Run ` az storage blob list --account-name {} --container-name {} --num-results {} --include t --query '[?tags."a-b" != null]'`. By removing `--show-next-marker --only-show-errors `, `nextMarker` will show in the warning.
2. Run `az storage blob list --account-name {} --container-name {} --num-results {} --include t --show-next-marker --only-show-errors --query '[?tags."a-b" != null || nextMarker != null]'`. By adding the condition `nextMarker != null` to avoid `nextMarker` being filtered by JMESPath.

**Comment by MonkeyTennis** [comment]
ok, Option 2 does work in that nextMarker is returned.

However, i've hit another issue where I cannot iterate through more than 5000 records.

If num-results is set to 1000 then I can iterate 5 times before the next call just hangs forever. If num-results is set to 5000 then I get one continuation token and the next call just hangs forever. The following script, where i've removed --query altogether to simplify things, demonstrates the issue, given a large enough volume of blobs to iterate over:

```
$blobs = az storage blob list --account-name {} --container-name {} --only-show-errors --show-next-marker --num-results 1000 --include t | ConvertFrom-Json;

$nextMarker = $blobs.nextMarker;
$nextMarker;

while ($null -ne $nextMarker)
{
    $newBlobs = az storage blob list --account-name {} --container-name {} --only-show-errors --show-next-marker --num-results 1000 --include t --marker $nextMarker | ConvertFrom-Json;
    $nextMarker = $newblobs.nextMarker
    if ($null -eq $nextMarker)
    {
        Write-Host nextMarker is null!!;
    }
    else
    {
        Write-Host nextMarker is not null!!;
    }

    $nextMarker;
}
```

The output of this script is the following (i'm assuming nextMarker is not sensitive data):

2!108!MDAwMDM2ITAwMDRlMDkyLWUxODItNGNlZS1hOWY3LTA0YmYwMDZhZDA5ZiEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-
nextMarker is not null!!
2!108!MDAwMDM2ITAwMDljNzQyLTJkOWMtNGJiNy1hNjFkLTVkNDJiOWU0Njc0MCEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-
nextMarker is not null!!
2!108!MDAwMDM2ITAwMGVjOTE4LWQ0MjYtNGY3Yy1iYTMzLTljOWJiNjBkMDJjYSEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-
nextMarker is not null!!
2!108!MDAwMDM2ITAwMTQwN2Y5LTg5MTYtNDE0NC04NWIwLTViYWI5NmUzZDcwYSEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-
nextMarker is not null!!
2!108!MDAwMDM2ITAwMTkyNmZlLWZmM2YtNDI3MS04YTY0LTRhZTk1ZDNhMWE0NSEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-
nextMarker is not null!!
2!108!MDAwMDM2ITAwMWU5MTEwLWJkZDYtNDJjNC04NjM2LTRkYWQ2YWYwZjc2OCEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-

At this point the script just hangs forever.

**Comment by MonkeyTennis** [comment]
@MoChilia any thoughts on the above? Thanks

**Comment by MoChilia** [comment]
I ran your script with a container having 10000 blobs. It successfully finished the iteration. However, it returned an error: argument --marker: expected one argument. This is because `$nextMarker` in the last iteration is not `$null`, it's an object array. Therefore I recommend you to turn the analyzing condition from `$null -ne $nextMarker` to `($nextmarker | Measure-Object).Count -ne 0`. 

BUT, your program hung with a `nextMarker`. It's strange. Could you share the error information and the full debug logs by running 
`az storage blob list --account-name {} --container-name {} --show-next-marker --num-results 1000 --include t --marker 2!108!MDAwMDM2ITAwMWU5MTEwLWJkZDYtNDJjNC04NjM2LTRkYWQ2YWYwZjc2OCEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE- --debug`
 in the last iteration?

**Comment by MonkeyTennis** [comment]
Hi there, attached is the debug trace for the issue. As you can see, > 5000 records the invocation just goes into a loop for about 15 minutes before terminating with a memory exception:
[az cli debug trace.txt](https://github.com/Azure/azure-cli/files/10876230/az.cli.debug.trace.txt)

**Comment by MonkeyTennis** [comment]
I should mention again that these storage accounts potentially contain tens of millions of blobs. Could there be an inefficiency in retrieving > the default number of records (5000) when such large numbers are involved?

This issue repro's 100% of the time for the storage account in question.

**Comment by evelyn-ys** [comment]
Need storage service side to figure out hanging issue on listing more than 5000 blobs. Cx has shared debug log above.

Hi @MonkeyTennis, we assume that the original issue has been resolved. For the new issue, Can you create a ticket for Storage service so that we can close this one for CLI?

**Comment by MonkeyTennis** [comment]
Yes sure and thanks for your help on this, it has moved things forwards.

**Comment by MonkeyTennis** [comment]
Raised https://github.com/Azure/azure-cli/issues/25674
