### ISSUE TITLE
az storage blob filter does not allow hyphens to be passed in the tag name

### ISSUE THREAD

**Issue by MonkeyTennis** [Azure/azure-cli#25596]
## Describe the bug

**Command Name**
`az storage blob filter`

**Errors:**
```
azure.core.exceptions.HttpResponseError: Error parsing query at or near character position 2: unexpected '1'
RequestId:c803a85e-401e-0097-03c6-4a0900000000
Time:2023-02-27T16:13:56.4469185Z
ErrorCode:InvalidQueryParameterValue
queryparametername:where
queryparametervalue:a-b='value1'
reason:This query parameter value is invalid.
Content: <?xml version="1.0" encoding="utf-8"?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Error parsing query at or near character position 2: unexpected &apos;1&apos;
RequestId:c803a85e-401e-0097-03c6-4a0900000000
Time:2023-02-27T16:13:56.4469185Z</Message><QueryParameterName>where</QueryParameterName><QueryParameterValue>a-b=&apos;value1&apos;</QueryParameterValue><Reason>This query parameter value is invalid.</Reason></Error>

cli.azure.cli.core.azclierror: Error parsing query at or near character position 2: unexpected '1'
RequestId:c803a85e-401e-0097-03c6-4a0900000000
Time:2023-02-27T16:13:56.4469185Z
ErrorCode:InvalidQueryParameterValue
queryparametername:where
queryparametervalue:a-b='value1'
reason:This query parameter value is invalid.
az_command_data_logger: Error parsing query at or near character position 2: unexpected '1'
RequestId:c803a85e-401e-0097-03c6-4a0900000000
Time:2023-02-27T16:13:56.4469185Z
ErrorCode:InvalidQueryParameterValue
queryparametername:where
queryparametervalue:a-b='value1'
reason:This query parameter value is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az storage blob filter --account-name {} --container-name {} --tag-filter "a='value1'" --debug` - works
- `az storage blob filter --account-name {} --container-name {} --tag-filter "a-b='value1'" --debug` - does not work

In both examples above the editor is removing the double quotes that surround the tag name.

## Expected Behavior

Hyphens should be allowed in the tag filter parameter. I have tried to comply with the JMESPath standard, if that even applies here, but with no success.

## Environment Summary
```
Windows-10-10.0.19045-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0

Extensions:
azure-devops 0.25.0
storage-blob-preview 0.6.2

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by MoChilia** [comment]
Hi @MonkeyTennis!
I worked well with the following commands:
1. In CMD: `az storage blob filter --account-name {} --container-name {} --tag-filter """a-b""='value1'"`
2. In PowerShell: `az storage blob filter --account-name {} --container-name {} --tag-filter "\""a-b\""='value1'"`
