### ISSUE TITLE
'az resource update' gets confused if property value contains an equal sign

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-cli#2559]
e.g. consider the following command line, which works fine:

    az resource update --resource-group MyRG --namespace Microsoft.Web --parent sites/MySite --resource-type Extensions --name MSDeploy --set properties.packageUri=https://foo.com/bar.zip --api-version 2015-08-01

But now suppose the url I want to use for the packageUri has a query string, e.g.

    az resource update --resource-group MyRG --namespace Microsoft.Web --parent sites/MySite --resource-type Extensions --name MSDeploy --set properties.packageUri=https://foo.com/bar.zip?a=5 --api-version 2015-08-01

This fails with:

> Couldn't find 'packageUri=https://foo' in 'properties.packageUri=https://foo'. Available options: ['complete', 'deployer', 'endtime', 'provisioningstate', 'starttime']

The = sign is confusing the parsing logic. I tried quoting in various way, but did not find one that worked. e.g same error with `--set properties.packageUri="https://foo.com/bar.zip?a=5"`

PS: relates to [this SO question](http://stackoverflow.com/questions/42894955/clear-an-app-service-instance-and-upload-new-content-from-a-zip-file/42895510#42895510)

**Comment by tjprescott** [comment]
Thanks for the report @davidebbo. We're already tracking this as #2527 and plan to get it fixed in the next couple weeks.

**Comment by davidebbo** [comment]
@tjprescott glad to hear, thanks!
