### ISSUE TITLE
az vm image list has a space in 'urn alias'

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#256]
I suspect we want to follow the same naming as the rest of our json documents.  If the service uses 'urn alias' (with space), we should talk with them about the intention.

{
    "offer": "CentOS",
    "publisher": "OpenLogic",
    "sku": "7.2",
    "urn": "OpenLogic:CentOS:7.2:latest",
    "**urn alias**": "CentOS",
    "version": "latest"
  }

**Comment by yugangw-msft** [comment]
It is the same issue as #575, which i will fix today.
