### ISSUE TITLE
Error when calling - get_default_cli().invoke() with args from python

### ISSUE THREAD

**Issue by AaronSaikovski** [Azure/azure-cli#25602]
Sample python code:
``` python
from azure.cli.core import get_default_cli
resource_group_name = "atest-rsg"
location = "australia east"
args=['group', 'create', '--name', resource_group_name, '--location', location]
get_default_cli().invoke(args)
```

gives the following error:
'group' is misspelled or not recognized by the system.

Examples from AI knowledge base:
https://aka.ms/cli_ref

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by AaronSaikovski** [comment]
there is an issue when using this library outside of a python virtual environment but has been resolved.

**Comment by ys1Co138** [comment]
Hello @AaronSaikovski, I'm experiencing the same issue. Can you provide more detail how you resolved the issue? Thank you so much!

```
>>> from azure.cli.core import get_default_cli
>>> az_cli = get_default_cli()
>>> az_cli.invoke(['login'])
No module named 'azure.cli.command_modules'
'login' is misspelled or not recognized by the system.

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs 
```

**Comment by AaronSaikovski** [comment]
yeah I did..check this repo out - https://github.com/AaronSaikovski/pyazdeploy

**Comment by AaronSaikovski** [comment]
i am working on moving this to miniconda
