### ISSUE TITLE
`az monitor app-insights web-test show` needs support api-version '2018-05-01-preview in specific cloud

### ISSUE THREAD

**Issue by AllyW** [Azure/azure-cli#25600]
**Related command**

az monitor app-insights web-test show
**Is your feature request related to a problem? Please describe.**

Gov cloud is missing the updated API version so cloud shell reports that failure. Our dev team needs to identify if that API version should be deployed to the Gov cloud.
The resource type 'webtests' could not be found in the namespace 'Microsoft.Insights' for api version '2018-05-01-preview'. The supported api-versions are '2014-04-01,2014-08-01,2015-05-01,2022-06-15'.
**Describe the solution you'd like**

Add target api-version in cli extension
**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
monitor feature
