### ISSUE TITLE
DnsRecordIsReserved error

### ISSUE THREAD

**Issue by marcelo321** [Azure/azure-cli#25604]
I am trying to create a vm with the following command:

`az vm create -n whatevername -g FORVMGROUP --public-ip-address-dns-name somednsname --image ubuntults --size Standard_B1ls --generate-ssh-keys -l eastus2`

And I am getting this error:

`
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"DnsRecordIsReserved\",\r\n    \"message\": \"DNS record somednsname.eastus2.cloudapp.azure.com is already reserved by another resource.\",\r\n    \"details\": []\r\n  }\r\n}"}]}}
`

So this is telling me the DNS name is reserved, but that dns name doesn't exist, so what's going on? was it manually reserved? how long will it be reserved?

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
> DNS record somednsname.eastus2.cloudapp.azure.com is already reserved by another resource.

Since this error message is returned by the REST service, it needs the service team to help investigate the root cause of the error message

**Comment by navba-MSFT** [comment]
@marcelo321 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. The parameter `--public-ip-address-dns-name` should be a Globally unique DNS Name for the Public IP. 

The DNS name label is an "A record" that starts with the specified label and resolves to this public IP address will be registered with the Azure-provided DNS servers. Example: mylabel.eastus.cloudapp.azure.com.

**Action Plan:**
1. You could try checking first if somednsname.eastus2.cloudapp.azure.com is already in use. 
2. Please try to **[follow this article](https://learn.microsoft.com/en-us/azure/virtual-machines/custom-domain#add-custom-domain-to-vm-public-ip-address)** and check if you can try creating the dns for your VM from Azure portal. See if that suceeds.

**Comment by marcelo321** [comment]
@navba-MSFT yeah I am checking if it exists and it gives NXDOMAIN status so should be fine, but I get that it already exists.

```
# dig @1.1.1.1 pg-fairy-web.azurewebsites.net

; <<>> DiG 9.18.1-1ubuntu1.3-Ubuntu <<>> @1.1.1.1 pg-fairy-web.azurewebsites.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 4997
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;pg-fairy-web.azurewebsites.net.        IN      A

```

```
# az webapp create --name pg-fairy-web --plan freeplan -g firstgroup --runtime 'php|7.4'
Webapp 'pg-fairy-web' already exists. The command will use the existing app's settings.
Unable to retrieve details of the existing app 'pg-fairy-web'. Please check that the app is a part of the current subscription
```

**Comment by marcelo321** [comment]
Sometimes a friend creates a cloudapp, then deletes it and I can't create it with the same name (the app is deleted). Is there a minimum time we have to wait to create it again? Either that or something is failing at azure because I know for sure some resources names are available but can't use those

**Comment by navba-MSFT** [comment]
@marcelo321 I would suggest waiting for atleast 30 minutes before creating a resource with the same name. This will ensure that the ARM cache is synchronized and the references to the old resource names are deleted.

**Comment by marcelo321** [comment]
@navba-MSFT I already waited more than 12 hours and still get the error both in the web UI and in the azure cli, while my other friends account see that is available. Something is wrong either in azure or my account, this shouldn't be happening.

**Comment by navba-MSFT** [comment]
@marcelo321 This might require a closer troubleshooting. Could you please open a support ticket with Microsoft so that our Support Professionals can look into this issue and assist you further.

**Comment by navba-MSFT** [comment]
@marcelo321 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had a chance to open a support ticket to troubleshoot this issue further. Awaiting your reply.

**Comment by marcelo321** [comment]
Hi @navba-MSFT,

I don't have a support plan to make a ticket to support, it just lists me the available options to manually resolve the issue.

I am aware that sometimes there is a 7day time that no other account can create that resource to prevent subdomain takeovers, but I noticed that sometimes after +7 days I still can't create them.

**Comment by navba-MSFT** [comment]
@marcelo321 Thanks for your reply. As an alternative, You can check if a DNS name is available by running the following command:

> **az network public-ip list --query "[?dnsSettings.domainNameLabel=='<your-dns-name>']"**

Replace <your-dns-name> with the DNS name you want to use. If the command returns an empty list, then the DNS name is available and you can use it for your VM's public IP address.

If the DNS name is not available, you can try using a different DNS name or contacting the person who reserved the DNS name to see if they can release it.

**Comment by sumgr0** [comment]
Hi @navba-MSFT,

I've been facing this same issue and not sure of how to figure out, if the issue persists with my account or the service.

Please help.

**Comment by marcelo321** [comment]
@sumgr0  My guess it is some protection against subdomain takeovers or something like that, otherwise it has no reasonable explanation.

It is not my account, it seems that is happening with all the accounts. If you create and delete a resource, after you delete it, it isn't available for everyone like before, seems like there are some protections that the azure cli team isn't aware of
