### ISSUE TITLE
az webapp deploy | spelling error in ResourceGroup parameter name

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#25613]
Moving MicrosoftDocs/azure-docs-cli PR #[3532](https://github.com/MicrosoftDocs/azure-docs-cli/pull/3532/files) which is an update to autogenerated reference content.

There is a spelling error in ResourceGroup parameter **value**.  The parameter value needs the letter `r`.  I think the source code might be in **azure-cli\src\azure-cli\azure\cli\command_modules\appservice\_help.py**

**Screen print from azure-docs-cli PR:**
![image](https://user-images.githubusercontent.com/58762114/221925744-fe610035-e31a-410d-a219-136b4f3d0a99.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@dbradish-microsoft The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
