### ISSUE TITLE
az webapp browser in cloud shell in Azure portal

### ISSUE THREAD

**Issue by diberry** [Azure/azure-cli#25616]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62
az webapp browse --name frontend-dfberry-3

**Related command**

**Describe the bug**

I ran this command from the Azure portal cloud shell. No web browser opened. 

**To Reproduce**

**Expected behavior**

I assume this is because it was cloud shell. Maybe the docs can say it doesn't work on cloud shell?

**Environment summary**

**Additional context**

**Comment by seligj95** [comment]
Able to repro. Confirming if this is expected behavior. If so, will update the help text.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by vmagelo** [comment]
Does this also apply to "az webapp up --launch-browser"? If so, would be good to say so. Thanks.
