### ISSUE TITLE
parameter --show-details

### ISSUE THREAD

**Issue by a12com** [Azure/azure-cli#25629]
[Enter feedback here]

Description of parameter --show-details -d for az vm show command tells that command will provide publicIP which is incorrect
actually it will provide private ip (yes, there are publicIps section, but it is actually not filled in):

"privateIps": "10.176.225.197",
  "provisioningState": "Succeeded",
  "proximityPlacementGroup": null,
  "publicIps": "", 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://learn.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/vm.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/vm.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness
