### ISSUE TITLE
Can not set azure front door identity settings using az cli

### ISSUE THREAD

**Issue by sanjaydebnath** [Azure/azure-cli#25634]
**Related command**
az resource update

**Describe the bug**
can not set user defined identity or system generated one by using below command on azure front door (premium)

```
PRIMARY_API_IDENTITY_ID="/subscriptions/######/resourcegroups/######/providers/Microsoft.ManagedIdentity/userAssignedIdentities/######"
AFD_ID="/subscriptions/######/resourcegroups/######/providers/Microsoft.Cdn/profiles/######"
az resource update --ids $AFD_ID --set identity="{\"type\": \"UserAssigned\", \"userAssignedIdentities\": {\"$PRIMARY_API_IDENTITY_ID\": { }}}"`
az resource update --ids $AFD_ID --set identity.type=SystemAssigned
```

**To Reproduce**
As `az afd profile create` has no option to set the identity (but can be done from portal), I am using the above commands as suggested in this [bug](https://github.com/Azure/azure-cli/issues/25343).

**Expected behavior**
Should be able to assign user defined identity.

**Environment summary**
```
{
  "azure-cli": "2.45.0",
  "azure-cli-core": "2.45.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5",
    "aks-preview": "0.5.129",
    "application-insights": "0.1.18",
    "azure-firewall": "0.14.4",
    "bastion": "0.2.2",
    "cosmosdb-preview": "0.22.0",
    "front-door": "1.0.17",
    "kusto": "0.5.0",
    "ssh": "1.1.3"
  }
}
```

![image](https://user-images.githubusercontent.com/28987981/222266135-6f872c79-6c57-4a69-9ce3-b735e07d2002.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by t-bzhan** [comment]
@sanjaydebnath Managed Identity for Front door is supported after Front Door rest API version "2022-11-01-preview", the related module need a SDK upgrade from existing "2021-06-01" to support that in "az afd profile" command, engineer team will support that in upcoming releases.

As a work around, you could set the --api-version parameter explicitly as below:
`az resource update --ids /subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourcegroups/bogroup/providers/Microsoft.Cdn/profiles/boprofile101 --set identity.type=SystemAssigned --api-version 2022-11-01-preview --debug`

**Comment by SwathiDhanwada-MSFT** [comment]
@sanjaydebnath  Have you had chance to try the command mentioned by @t-bzhan  ? Do revert if you have further questions.

**Comment by SwathiDhanwada-MSFT** [comment]
@sanjaydebnath Hope the information provided is useful. As we haven't heard from you, we will close the issue for now. If there are further questions, please revert and we will be glad to assist you.
