### ISSUE TITLE
Update cross-region LB CLI rule update

### ISSUE THREAD

**Issue by mahipdeora** [Azure/azure-cli#25637]
**Related command**

az network cross-region-lb rule
**Is your feature request related to a problem? Please describe.**

**No this is not related to any recent issue**
**Describe the solution you'd like**

We would like to disable the ability to have custom TCP rst or idle timeout values for the cross-region load balancer. Currently, any custom value a user inputs is ignored in the backend. Prior to this product going GA, we would like to remove these parameters. Whenever a user makes a new CRLB rule, CLI should pass in TCP rst 'false' and idle timeout to 4 mins to the backend rest API. 
**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by mahipdeora** [comment]
@necusjz any update on this item?

**Comment by yonzhan** [comment]
Planned in https://github.com/Azure/azure-cli/milestone/129

**Comment by necusjz** [comment]
@mahipdeora 

FYI. The above PR is for setting default values. For removing parameters part, as it's a kind of breaking change, we can only do that in the breaking change window, i.e., next sprint.

**Comment by mahipdeora** [comment]
Sounds good, is there a way for me to track the new change and is there a timeline for the new sprint?

**Comment by necusjz** [comment]
Let's continue to use the current issue to track. 2.49.0 is for breaking changes and it will be released around 05/23.

**Comment by mahipdeora** [comment]
Hi, will the azure cross-region rule update CLI command also be updated? 

https://learn.microsoft.com/en-us/cli/azure/network/cross-region-lb/rule?view=azure-cli-latest#az-network-cross-region-lb-rule-update

If not, can that be rolled in the 5/23 release?

**Comment by mahipdeora** [comment]
Hi, when will the new CLI + the doc changes roll out?
