### ISSUE TITLE
Requesting CLI Development Support for PaloAltoNetworks.Cloudngfw

### ISSUE THREAD

**Issue by Vibhuti-Sharma-Microsoft** [Azure/azure-cli#25651]
Requesting CLI Development Support for PaloAltoNetworks.Cloudngfw

- Swagger: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/paloaltonetworks/resource-manager/PaloAltoNetworks.Cloudngfw/stable/2022-08-29
- GA date: 2023-08-01

**Comment by yonzhan** [comment]
Add CLI PM @Jacekey23 to help you go through APEX onboarding process.
