### ISSUE TITLE
unrecognized authorization error  k8s-extension

### ISSUE THREAD

**Issue by danielvargasbm** [Azure/azure-cli#25654]
**Related command**

`az k8s-extension create`

**Describe the bug**

I am trying to install AzureML extensions to AKS using this URL.
https://learn.microsoft.com/en-us/azure/machine-learning/how-to-deploy-kubernetes-extension?tabs=deploy-extension-with-cli#azure-machine-learning-extension-deployment---cli-examples-and-azure-portal

I get however this error,
```
Error Message
Request failed to https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.ContainerService/managedclusters/<CLUSTER_NAME>/extensionaddons/test-extention?api-version=2021-03-01. Error code: Forbidden. Reason: Forbidden.{"error":{"code":"AuthorizationFailed","message":"The client '<CLIENT_ID>' with object id '<CLIENT_ID>' does not have authorization to perform action 'Microsoft.ContainerService/managedclusters/extensionaddons/read' over scope '/subscriptions/<SUBSCRIPTION>/resourceGroups/<RESOURCE GROUP>/providers/Microsoft.ContainerService/managedclusters/test-cluster/extensionaddons/azureml' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
```

**To Reproduce**

Run 
`az extension update -n k8s-extension`
`az k8s-extension create --name azureml --extension-type Microsoft.AzureML.Kubernetes --cluster-name CLUSTER_NAME --resource-group RESOURCE_GROUP --cluster-type managedClusters --config enableTraining=True enableInference=True allowInsecureConnections=True inferenceRouterServiceType=LoadBalancer inferenceRouterHA=False`

**Expected behavior**
Install the azureml extension

**Environment summary**

```
az version                                                                                                                                                                                            ─╯
{
  "azure-cli": "2.45.0",
  "azure-cli-core": "2.45.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5",
    "aks-preview": "0.5.131",
    "azure-devops": "0.26.0",
    "k8s-extension": "1.4.0",
  }
}
```

**Additional context**

Related existing issue: https://github.com/Azure/azure-cli-extensions/issues/5144
But created one here as this one is for v2

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@danielvargasbm I am not able to reproduce the issue and the AzureML extension is getting installed correctly.  Can you please try - 
1. Re-register Microsoft.KubernetesConfiguration to get rid of the Forbidden error
2. Register Microsoft.ContainerService/AKS-ExtensionManager
Please refer to [Register the KubernetesConfiguration service provider](https://learn.microsoft.com/en-us/azure/aks/dapr#register-the-kubernetesconfiguration-service-provider) for registration steps. Thanks.

**Comment by vrgsdaniel** [comment]
After re-registering, and updating k8s-extension the error persists. Any hints?
```
# az provider list --query "[?contains(namespace,'Microsoft.KubernetesConfiguration')]" -o table                                                                                                        
Namespace                          RegistrationState    RegistrationPolicy
---------------------------------  -------------------  --------------------
Microsoft.KubernetesConfiguration  Registered           RegistrationRequired
```
