### ISSUE TITLE
az functionapp function list causes a Blowfish deprecation error

### ISSUE THREAD

**Issue by edgeofsanity76** [Azure/azure-cli#25653]
**Related command**
az functionapp function list

**Describe the bug**
Outputs a stderror indicating that Blowfish cryptography is deprecated

```
az : D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
At line:1 char:1
+ az functionapp function list -n *hidden* ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (D:\a\_work\1\s\...been deprecated:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**To Reproduce**
Run the command

**Expected behavior**
Does not output a stderror of this kind

**Environment summary**
Run in powershell or powershell ISE
Particularly problematic in Azure YML pipelines which cause tasks to fail if their failOnStandardError is true

**Comment by yonzhan** [comment]
route to CXP team

**Comment by kamperiadis** [comment]
Hi @edgeofsanity76 Just wanted to check in and see if you are still experiencing this issue? Thank you.

**Comment by kamperiadis** [comment]
Closing as we have not heard back from the customer.
