### ISSUE TITLE
az monitor log-analytics workspace table update validation wrong

### ISSUE THREAD

**Issue by ryan-royals** [Azure/azure-cli#25660]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

`az monitor log-analytics workspace table update --name {Table} --retention-time 730 --total-retention-time 2556 --resource-group {Resource Group} --workspace-name {Workspace}`

**Describe the bug**

Total Retention time should be able to be set to 2556, but azcli does not validate this value. 
Az CLI allows 2555, but API reponds with error:
"The specified total retention value is invalid. The value beyond two years is restricted to full years. Allowed values are: [4-730], 1095,1460, 1826, 2191, 2556 days"

**To Reproduce**

Run command:
`az monitor log-analytics workspace table update --name {Table} --retention-time 730 --total-retention-time 2556 --resource-group {Resource Group} --workspace-name {Workspace}`
Errors with Validation.

`az monitor log-analytics workspace table update --name {Table} --retention-time 730 --total-retention-time 2555 --resource-group {Resource Group} --workspace-name {Workspace}`
Errors with API response.

**Expected behavior**

Value should update as documented.

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
@AllyW for awareness

**Comment by AllyW** [comment]
Hi @ryan-royals , yes, az cli does not validate the two parameters `total-retention-time` and `retention-time` for now and we are planning updating this part. Once future development plan is settled, I'll link it to this issue for infos. 
Thanks for reminding.

**Comment by ryan-royals** [comment]
Hi @AllyW, there is some light validation on these parameters, but it was slightly incorrect.
I have submitted a PR to resolve the issue.

https://github.com/Azure/azure-cli/pull/25666

**Comment by AllyW** [comment]
@dulikvor please have a look at this pr requested about the default value of `total-retention-time`

**Comment by dulikvor** [comment]
Hi @AllyW, this is true, total retention values are eligible for any number between [4-730] days, anything beyond two years is limited to a list of fixed number of days, specifically - 1095, 1460, 1826, 2191, 2556

**Comment by AllyW** [comment]
@dulikvor thanks for clarification. Is there any related update on swagger file about the new restriction of parameter `total-retention-time` so that we can update the validation in cli side?

**Comment by AllyW** [comment]
@ryan-royals fix pr is  linked above for your reference
