### ISSUE TITLE
Typo in output of az spring connection create/update postgres-flexible

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-cli#25672]
## Describe the bug

**Command Name**
`az spring connection update postgres-flexible`

**Errors:**
`vualt` is typo in below output. Besides update, create operation has the same issue.
```
get valid key vualt reference connection
key vualt reference connection: /subscriptions/9e223dbe-3399-4e19-88eb-0975f02ac87f/resourceGroups/dixue/providers/Microsoft.AppPlatform/Spring/dixueasa/apps/catalog-service/deployments/default/providers/Microsoft.ServiceLinker/linkers/keyvault_dpn0a
{
  "additionalProperties": {},
  "authInfo": {
    "additionalProperties": {},
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az spring connection update postgres-flexible --resource-group {} --service {} --app {} --connection {} --system-identity --vault-id {}`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0

Extensions:
spring 1.6.6

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to service team
