### ISSUE TITLE
az network  - this is related to trying to activate Bastion RDP

### ISSUE THREAD

**Issue by dougherring** [Azure/azure-cli#25678]
## Describe the bug

**Command Name**
`az network`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network {} {} --name {} --resource-group {} --target-resource-id {}`

## Environment Summary
```
Linux-5.4.0-1104-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.45.0

Extensions:
bastion 0.2.3
ai-examples 0.2.5
ml 2.13.0
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by necusjz** [comment]
@dougherring `az network {} {} --name {} --resource-group {} --target-resource-id {}` is too crude, please provide the essential information.

**Comment by dougherring** [comment]
I was trying to run this command to enable bastion RDP: az network bastion rdp --name "MVD05-P-NEU-AFW01-BH" --resource-group "MVD-AADJ-NETWORKS-RG" --target-resource-id "/subscriptions/a1ffc958-d2c7-493e-9f1e-125a0477f536/resourceGroups/MVD-AADJ-NETWORKS-RG/providers/Microsoft.Compute/virtualMachines/EUDBNEUADM"

**Comment by necusjz** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@dougherring Thanks for reaching out to us and reporting this issue. 

> Could you please elaborate the issue ? Are you getting any errors while running the above command ?
> Could you please share that error message ?
> Could you run the same above command with `--debug `parameter and share the detailed output here ? 

This will help us to assist you better.  Awaiting your reply.

**Comment by dougherring** [comment]
Here's the output from -debug:

PS /home/doug> az network bastion rdp --name "MVD05-P-NEU-AFW01-BH" --resource-group "MVD-AADJ-NETWORKS-RG" --target-resource-id "/subscriptions/a1ffc958-d2c7-493e-9f1e-125a0477f536/resourceGroups/MVD-AADJ-NETWORKS-RG/providers/Microsoft.Compute/virtualMachines/EUDBNEUADM" --debug
cli.knack.cli: Command arguments: ['network', 'bastion', 'rdp', '--name', 'MVD05-P-NEU-AFW01-BH', '--resource-group', 'MVD-AADJ-NETWORKS-RG', '--target-resource-id', '/subscriptions/a1ffc958-d2c7-493e-9f1e-125a0477f536/resourceGroups/MVD-AADJ-NETWORKS-RG/providers/Microsoft.Compute/virtualMachines/EUDBNEUADM', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f458fa38160>, <function OutputProducer.on_global_arguments at 0x7f458f955b80>, <function CLIQuery.on_global_arguments at 0x7f458f8e7160>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.natgateway', 'azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns', 'azext_bastion']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: natgateway                0.003         3         6
cli.azure.cli.core: network                   0.403       120       386
cli.azure.cli.core: privatedns                0.004        14        66
cli.azure.cli.core: Total (3)                 0.410       137       458
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: bastion                   0.007         2         9  /home/doug/.azure/cliextensions/bastion
cli.azure.cli.core: ai-examples               0.096         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (2)                 0.103         3        10
cli.azure.cli.core: Loaded 137 groups, 468 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : network bastion rdp
cli.azure.cli.core: Command table: network bastion rdp
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f458eb8bc10>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/doug/.azure/commands/2023-03-06.16-25-56.network_bastion_rdp.166.log'.
az_command_data_logger: command args: network bastion rdp --name {} --resource-group {} --target-resource-id {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f458eb33820>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f458eafc0d0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f458eafc280>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f458f955c10>, <function CLIQuery.handle_query_parameter at 0x7f458f8e71f0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f458eafc1f0>]
az_command_data_logger: extension name: bastion
az_command_data_logger: extension version: 0.2.3
Command group 'az network' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/doug/.azure/cliextensions/bastion/azext_bastion/custom.py", line 229, in rdp_bastion_host
    from ._process_helper import launch_and_wait
  File "/home/doug/.azure/cliextensions/bastion/azext_bastion/_process_helper.py", line 9, in <module>
    from ctypes import WinDLL, c_int, c_size_t, Structure, WinError, sizeof, pointer
ImportError: cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.9/ctypes/__init__.py)

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.9/ctypes/__init__.py)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/doug/.azure/cliextensions/bastion/azext_bastion/custom.py", line 229, in rdp_bastion_host
    from ._process_helper import launch_and_wait
  File "/home/doug/.azure/cliextensions/bastion/azext_bastion/_process_helper.py", line 9, in <module>
    from ctypes import WinDLL, c_int, c_size_t, Structure, WinError, sizeof, pointer
ImportError: cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.9/ctypes/__init__.py)
az_command_data_logger: cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.9/ctypes/__init__.py)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/doug/.azure/cliextensions/bastion/azext_bastion/custom.py", line 229, in rdp_bastion_host
    from ._process_helper import launch_and_wait
  File "/home/doug/.azure/cliextensions/bastion/azext_bastion/_process_helper.py", line 9, in <module>
    from ctypes import WinDLL, c_int, c_size_t, Structure, WinError, sizeof, pointer
ImportError: cannot import name 'WinDLL' from 'ctypes' (/usr/lib/python3.9/ctypes/__init__.py)
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f458eb8be50>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.656 seconds (init: 0.119, invoke: 1.538)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 7087 in cache
telemetry.check: Negative: The /home/doug/.azure/telemetry.txt was modified at 2023-03-06 16:24:59.109272, which in less than 600.000000 s
PS /home/doug>

Target machine is EUDBNEUADM - Windows (Windows 11 Pro)

Please let me know what other information you need. This is blocking me from setting up an environment.

Thanks,
Doug

**Comment by navba-MSFT** [comment]
@dougherring Thanks for sharing the debug logs. I am looking in this further. I will get back to you with an update.

**Comment by dougherring** [comment]
Any ETA on a fix for this? I am blocked from setting up a new environment due to this issue.

Thanks,
Doug

**Comment by navba-MSFT** [comment]
@dougherring Thanks for your reply. While you mentioned you are using Target machine (Windows 11 Pro).  The environment summary says that you are using Linux. 

```
Linux-5.4.0-1104-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM
```

Also, note that bastion RDP command works best on Windows, for other OS’ (like Linux) you can do the [tunnel command](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-tunnel) and then use the client of your choice.

>Connect to a VM using the [az network bastion tunnel command](https://docs.microsoft.com/en-us/azure/bastion/connect-native-client-windows#connect-tunnel). This lets you do the following:

>- Use native clients on non-Windows local computers (example: a Linux PC).
>- Use the native client of your choice. (This includes the Windows native client.)
>- Connect using SSH or RDP.
>- Set up concurrent VM sessions with Bastion.
>- [Upload files](https://docs.microsoft.com/en-us/azure/bastion/vm-upload-download-native#tunnel-command) to your target VM from your local computer. File download from the target VM to the local client is currently not supported for this command.

>Currently, this feature has the following limitation:
Signing in using an SSH private key stored in Azure Key Vault isn’t supported with this feature. Before signing in to your Linux VM using an SSH key pair, download your private key to a file on your local machine.


So could you please try with tunnel command and check if that helps.

Hope this helps.

**Comment by dougherring** [comment]
The machine I am trying to enable this on is Windows.

[A screenshot of a computer  Description automatically generated with medium confidence]

What needs to be done in order to get this working? My coworkers ran the exact same command on their instances without issue. I have been blocked now for several days on this. I have filed a ticket with Azure Support as well.

If you are Microsoft FTE - can we try to sync over Teams to get this resolved?

Thanks,
Doug

**Comment by navba-MSFT** [comment]
@dougherring Thanks for your reply. Could you please check the `bastion `extension version used by your colleagues and check if their `bastion `extension version is same as yours ? You can check this by running `az --version` command.

**Comment by dougherring** [comment]
Hello,

I found out the root cause of my issue.

Azure CLI running from the portal is different than running directly from your machine. Running the command on my machine got me past the issue I have reported.

Thanks for the help and support here. You can resolve the issue that was reported.

Doug

**Comment by navba-MSFT** [comment]
@dougherring Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by jiasli** [comment]
`ImportError: cannot import name 'WinDLL' from 'ctypes'` is tracked by #23143
