### ISSUE TITLE
az storage blob list polls continuously when > 5000 records are retrieved using nextMarker continuation tokens

### ISSUE THREAD

**Issue by MonkeyTennis** [Azure/azure-cli#25674]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
```
$blobs = az storage blob list --account-name "<redacted>" --container-name <redacted> --only-show-errors --show-next-marker --num-results 1000 --include t | ConvertFrom-Json;

$nextMarker = $blobs.nextMarker;
$nextMarker;

while ($null -ne $nextMarker)
{
    $newBlobs = az storage blob list --account-name "<redacted>" --container-name <redacted> --show-next-marker --num-results 1000 --include t --marker $nextMarker --debug | ConvertFrom-Json;
    $nextMarker = $newblobs.nextMarker
    if ($null -eq $nextMarker)
    {
        Write-Host nextMarker is null!!;
        Write-Host $(Get-Date);
    }
    else
    {
        Write-Host nextMarker is not null!!;
        Write-Host $(Get-Date);
    }

    $nextMarker;
}
```

**Describe the bug**
For the storage account in question, which contains tens of millions of blobs (which might not be relevant), the script above executes 5 times, returning batches of 1000 records and a continuation token.

This is as expected.

Upon the 6th invocation, the CLI seems to poll forever, eventually giving up with a memory exception. I have attached the debug log below.

[az cli debug trace.txt](https://github.com/Azure/azure-cli/files/10880212/az.cli.debug.trace.txt)

**To Reproduce**
Run the script above.

**Expected behavior**
Batches of 1000 blobs should be returned until the list is exhausted.

**Environment summary**
Windows-10-10.0.19045-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.45.0 *

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1

**Comment by MonkeyTennis** [comment]
Previous issue which has likely been superseded by this one: https://github.com/Azure/azure-cli/issues/25595

**Comment by MonkeyTennis** [comment]
@xgithubtriage for visibility.

**Comment by yonzhan** [comment]
route to service team
