### ISSUE TITLE
Older version of setup tool and setuptool dist-info getting flagged by S360 and other scans

### ISSUE THREAD

**Issue by ronitshaw1993** [Azure/azure-cli#25682]
![image](https://user-images.githubusercontent.com/126830425/222863880-8dd5e9a0-5fbb-4c3c-8e31-5bed2bb11ae6.png)

An older version of setup tools is installed in the latest release version of az cli == 2.45.0. 
![image](https://user-images.githubusercontent.com/126830425/222864046-6e657ddb-4d5e-4d22-8559-55551567ce90.png)

I have noticed that in dev the version is upgraded, but not sure when the release will happen. 
![image](https://user-images.githubusercontent.com/126830425/222864134-77e9c085-5d11-422e-8661-d6bde86913ad.png)

**### Our deployments are getting flagged. Let us know if there is a way around this before the next release as the setup tools inside the usr/lib/az is getting flagged, so installing an updated version overall is not helping.**

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by jiasli** [comment]
Per my understanding, `requirements.txt` is only used `azdev setup`. @ronitshaw1993, are you using `azdev setup` in your pipelines?

**Comment by bebound** [comment]
We use default `setuptools` bundle with python.
Workaround:
`/opt/az/bin/python3 -m pip install -U setuptools`

**Comment by ronitshaw1993** [comment]
@jiasli 
This is how I'm installing az cli in my mariner python3.9 base image. 
![image](https://user-images.githubusercontent.com/126830425/223227373-81a0ba98-5325-47ab-b8f0-ae132c10261b.png)

**Comment by ronitshaw1993** [comment]
@bebound I guess that needs to be updated. 
As I'm not able to find the python bin specifically installed by az cli.

root [ / ]# find / -name python3.9
/usr/lib/python3.9
**/usr/lib/az/lib/python3.9**
/usr/bin/python3.9


This is the location **/usr/lib/az/lib/python3.9** where S360 and other scans are flagging for vulnerability and an older version of setup tools exist. 

Would be happy to go on a quick call as well.

**Comment by ronitshaw1993** [comment]
![image](https://user-images.githubusercontent.com/126830425/223229250-34691cf2-f80b-4f31-9a49-b619ed93e600.png)

**Comment by bebound** [comment]
`PYTHONPATH="/lib64/az/lib/python3.9/site-packages" python3.9 -m pip install -U setuptools`

**Comment by bebound** [comment]
2.47 will be released on April 4.
