### ISSUE TITLE
Logic app integration account map

### ISSUE THREAD

**Issue by rguptar** [Azure/azure-cli#25687]
**Related command**
az logic integration-account

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to see the following commands added to the cli.
`az logic integration-account map {create, delete, list, show, update }`
Az Powershell has this but not the cli.

**Describe alternatives you've considered**
Az Powershell supports it. https://learn.microsoft.com/en-us/powershell/module/az.logicapp/new-azintegrationaccountmap

**Additional context**
n/a

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
Non-customer reported issue. Adding Service team to look into this.

**Comment by navba-MSFT** [comment]
@Azure/azure-logicapps-team Please look into this.

**Comment by jsntcy** [comment]
@rguptar, could you please provide swagger here?

**Comment by rguptar** [comment]
@jsntcy https://github.com/Azure/azure-rest-api-specs/blob/main/specification/logic/resource-manager/Microsoft.Logic/stable/2019-05-01/logic.json

**Comment by rguptar** [comment]
@yonzhan looks like this was reprioritized, can you share an updated timeline?

**Comment by jsntcy** [comment]
We plan to release it in next sprint (7/4)
