### ISSUE TITLE
Lack of response's description

### ISSUE THREAD

**Issue by DamianGiebas-Xebia** [Azure/azure-cli#25692]
I wanted check the description of "status" field in response and couldn't find it.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla witryny learn.microsoft.com ➟ Linkowanie do problemu w usłudze GitHub.*

* ID: ebc5cbbe-2cb1-8430-3843-638fa3fd3f1b
* Version Independent ID: eb60de03-08d0-141f-9fb2-5970e3a2bd7f
* Content: [az functionapp deployment source](https://learn.microsoft.com/pl-pl/cli/azure/functionapp/deployment/source?view=azure-cli-latest#az-functionapp-deployment-source-config-zip)
* Content Source: [latest/docs-ref-autogen/functionapp/deployment/source.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/functionapp/deployment/source.yml)
* Service: **azure-functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by kamperiadis** [comment]
Hi @DamianGiebas-Xebia I am pretty sure we do not have any official documentation for the deployment status value but:
- status=3 means that the zip deployment failed
- status=4 means that the zip deployment succeeded
- We will keep polling the deployment status API as long as we get in 'progress' from the deployment status API
- After a certain amount of time, if we do not get status=4, then we simply show a timeout error

I hope this helps! Let me know if you have any follow up questions. We will need to add this in official documentation at some point.
