### ISSUE TITLE
[Network] Expose VPN Client Config Create for Vnet Gateway

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2569]

**Comment by tjprescott** [comment]
Currently this issue is blocked due to https://github.com/Azure/azure-rest-api-specs/issues/1093. cc/ @aanandr

**Comment by aanandr** [comment]
Thanks for keeping me informed Travis. Want to make sure I understand this properly. What is the autorest generated SDK? Is it an SDK exclusive for Python? Swagger is the same for PS and CLI so I was wondering what this means.

Is this issue to be fixed by the GW team? Let me know.

**Comment by tjprescott** [comment]
Autorest https://github.com/Azure/autorest is the tool that converts the Swagger definitions into the language SDKs. The call to create the client VPN package doesn't work for Python. It was suggested that it was due to a swagger bug, so I created the issue there.  If it isn't a swagger issue, it may be that the Python component of autorest isn't handling it appropriately.  cc/ @lmazuel

**Comment by aanandr** [comment]
Travis – I doubt this is a Swagger level bug because Powershell works just fine. It may be the Python component of Autorest. How do we confirm this? It “lmazuel” looking into it?

**Comment by tjprescott** [comment]
I created an issue in the Python SDK repo https://github.com/Azure/azure-sdk-for-python/issues/1069.

**Comment by tjprescott** [comment]
This was a Swagger bug that has been fixed. Closing.
