### ISSUE TITLE
Azure CLI development for Azure Monitor Workspace

### ISSUE THREAD

**Issue by divya-jay** [Azure/azure-cli#25697]
Resource provider: *microsoft.monitor*
Description of feature or work requested. *CLI for CRUD operations on microsoft.moitor/accounts resource type. Also add a command to approve manual Private Endpoint Connections.*
Minimum API version required. *2023-04-03*
Swagger link. *https://github.com/Azure/azure-rest-api-specs/blob/main/specification/monitor/resource-manager/Microsoft.Monitor/stable/2023-04-03/monitoringAccounts_API.json*
Target date. *04/01/2023*
Where do you want the feature to locate? A command module or an extension? *We would like an Extension at this time.*
Status of the service. Is it in preview or GA? **
Examples of the feature. Usually REST API specs repo should contain examples. *It is available in Public Azure. Examples can be found in the REST api specs Repo: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/monitor/resource-manager/Microsoft.Monitor/stable/2023-04-03/examples*

**Comment by yonzhan** [comment]
monitor feature

**Comment by AllyW** [comment]
hi @divya-jay , extension cmd can be generated using CodeGenv2.  For more infos, please refer to https://github.com/Azure/aaz-dev-tools
