### ISSUE TITLE
Getting Key Vault policies is not consistent, sometimes it shows display name

### ISSUE THREAD

**Issue by armandete** [Azure/azure-cli#25711]
## Describe the bug
We are trying to create scripts to cleanup KV policies, but command is not consistent, also from Az Cli vs Az Powershell outputs are very different
For example in Az Cli we can´t even get displayName property, so only Powershell can be used for this solution

Why am I reporting a bug?
Because when I execute PS command in my laptop, output is complete
In a VM with windows server using same version of PS is not showing full output
But after testing in Azure runbook, functions, pipelines, output is incomplete. display name always showing empty

**Command Name**
(Get-AzKeyVault -VaultName $VaultName).AccessPolicies
Running from laptop, with PS it´s listing more than 20 policies by their name, exactly as in portal.azure, this is the expected result always

Example of displayName
![portal](https://user-images.githubusercontent.com/55021283/223515824-ab49413d-9224-478d-a0fa-ca68cd44bfeb.png)

But exact same command in azure solutions: runbook, functions & pipelines, it´s showing only 2 policies with correct display name, the rest are showing as empty

**Errors:**
```
No error from command execution, only incomplete/inconsistent output
```

## To Reproduce:
From command line only execute direct command in PS, azure runbook & functions will be the same
$VaultName = "dev-vault"
(Get-AzKeyVault -VaultName $VaultName).AccessPolicies

For azure pipeline using next task
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'your-connection'
      ScriptType: 'InlineScript'
      Inline: |
        $VaultName = "dev-vault"
        (Get-AzKeyVault -VaultName $VaultName).AccessPolicies
      errorActionPreference: 'continue'
      azurePowerShellVersion: 'LatestVersion'

## Expected Behavior
Always same output should be expected, as we are trying to identify Unknown policies which are covered by next condition, but because of inconsistent display name, we can´t complete automation

`(Get-AzKeyVault -VaultName $VaultName).AccessPolicies|Where-Object {($_.ApplicationId -eq $null) -and ($_.DisplayName -eq '')}|Select-Object -ExpandProperty ObjectId
`

## Environment Summary
```
![psoutput](https://user-images.githubusercontent.com/55021283/223516654-f7131511-9934-4d7c-91cf-f9bc61f411bf.png)

Working good in local PSVersion                      7.2.9
Failing in same version using windows server 2019
Azure Runbooks tested using 5.1, 7.1, 7.2
Azure function tested using Powershell core 7.2
```

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by armandete** [comment]
Just asking if for this kind of requests is there any ETA ?
Thx in advance

**Comment by evelyn-ys** [comment]
Hi @armandete, per my understanding, your ask is `(Get-AzKeyVault -VaultName $VaultName).AccessPolicies` doesn't always show displayName correctly, right?

As this is a Powershell cmdlet, you can consider creating a new issue in [azure-powershell](https://github.com/Azure/azure-powershell/issues) repo.
