### ISSUE TITLE
Add snat parameter to az network firewall policy create and az network firewall policy update

### ISSUE THREAD

**Issue by Gizachew-Eshetie** [Azure/azure-cli#25725]
**Related command**
az network firewall policy create and az network firewall policy update

Add snat parameter to az network firewall policy create and az network firewall policy update commands so that 
Private ranges and auto learn private ranges can be configured using this parameter.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Please refer proposed solution below and this PowerShell PR : https://github.com/Azure/azure-powershell/pull/20854

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/18257706/223831792-5c3bc958-81e8-4fe5-963a-7ea452a1a3f5.png)

**Comment by yonzhan** [comment]
network feature
