### ISSUE TITLE
Reimage Support for Standalone VMs

### ISSUE THREAD

**Issue by srcharug** [Azure/azure-cli#25722]
### Related command

az vm reimage --name
--resource-group
--subscription
[--temp-disk]
[--admin-password]
[--custom-data]
[--exact-version]

### Resource Provider

Microsoft.Compute/virtualMachines

### Description of Feature or Work Requested

https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/reimage?tabs=HTTP

### Minimum API Version Required

2022-11-01

### Swagger PR link / SDK link

Swagger PR - https://github.com/Azure/azure-rest-api-specs/pull/21090

### Target Date

2023-04-04

**Comment by yonzhan** [comment]
compute feature
