### ISSUE TITLE
Add RouteServerId parameter to firewall create/update commands and implement get learned ip prefixes command

### ISSUE THREAD

**Issue by Gizachew-Eshetie** [Azure/azure-cli#25724]
**Related command**
az network firewall create, az network firewall update

- Add RouteServerId parameter to these commands : az network firewall create, az network firewall update
- Add a new command that will return learned ip prefixes for a firewall given firewall name and resource group name

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Please refer this powershell PR : https://github.com/Azure/azure-powershell/pull/19825

**Describe alternatives you've considered**

**Additional context**

**Comment by saisujithreddym** [comment]
Swagger changes: https://github.com/Azure/azure-rest-api-specs/pull/19215
