### ISSUE TITLE
Can't install az cli: File has unexpected size (13238 != 13167). Mirror sync in progress? [IP: 13.93.152.112 443]

### ISSUE THREAD

**Issue by dmmusil** [Azure/azure-cli#25731]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
N/A

**Describe the bug**
We're seeing a high failure rate attempting to install az cli on Linux build agents (ubuntu 20.04). This appears to be an exact duplicate of #23343. We see about a 50% failure rate.

**To Reproduce**
We're running the following script

```
        sudo apt-get update
        sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
        sudo mkdir -p /etc/apt/keyrings
        curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
            gpg --dearmor |
            sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
        sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
            sudo tee /etc/apt/sources.list.d/azure-cli.list
        sudo apt-get update
        sudo apt-get install azure-cli=$azversion-1~$AZ_REPO --allow-downgrades
```
where `$azversion` is `2.46.0`.

**Expected behavior**
Can install a specific version using apt-get

**Environment summary**
Ubuntu 20.04 github actions agent

**Additional context**
Attempting to work around the Blowfish issue from earlier in the week with version `2.45.0`. We have also attempted to use `2.44.1` and see the same failure rates.

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by bebound** [comment]
packages.microsoft.com engineers are working on this.

**Comment by dmmusil** [comment]
OK thanks. We had a successful run so I will close this. Is there another place to report issues with packages.microsoft.com in case there are future problems? I don't want to create unrelated issues if possible.
