### ISSUE TITLE
az login

### ISSUE THREAD

**Issue by kerberos5** [Azure/azure-cli#25733]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-4.18.0-408.el8.x86_64-x86_64-with-glibc2.28, CentOS Linux 8 (Core)
Python 3.9.6
Installer: RPM

azure-cli 2.45.0
```

**Comment by yonzhan** [comment]
@jiasli for awareness
