### ISSUE TITLE
az cosmosdb sql container throughput show return messages

### ISSUE THREAD

**Issue by Phoenax** [Azure/azure-cli#25737]
So, recently started using this API, but I'm having issues with this command

"az cosmosdb sql container throughput show"

mainly because of how the error messages are handled. Cannot find anything on the documentation (unless I'm looking into the wrong place) regarding this. In this case, using the command on a container with Shared Throughput returns a "Not Found" error. Initially tried catching it with try/except but to no use. Would be good to have something related to possible occurring errors on use, and the return possibilities (like, is it a simple string?). 

Thanks for your concern!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8118fcf7-5433-71bc-a345-6ac30584660d
* Version Independent ID: 03183f36-fa95-c56b-254a-54663639e3b2
* Content: [az cosmosdb sql container throughput](https://learn.microsoft.com/en-us/cli/azure/cosmosdb/sql/container/throughput?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/cosmosdb/sql/container/throughput.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/cosmosdb/sql/container/throughput.yml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@Phoenax can you please share the debug log using `az cosmosdb sql container throughput show --debug`

**Comment by Phoenax** [comment]
Hi again! Updates:

Went back at it and found the "problem": this exception inherits from BaseException instead of Exception, hence why I couldn't catch it. Found it after calling python **type()** function to the **cli.resource.error**  ( cli = get_default_cli() ) and looking for **SystemExit** in python docs. 

My only issue now is not being able to suppress the output in case of such error ocurring (I have --output None in the command, works if the command is successful, but still outputs  "ERROR: (NotFound) Entity with the specified id does not exist in the system. More info: https://aka.ms/cosmosdb-tsg-not-found ... " case not). As stated, I'm new to the API, so it may just be me being noob on the use.

Regardless the first topic, I leave the feedback that it may be useful to have the expected possible returns for these types of calls.

Anyways, tomorrow I'll close this thread. Thank you for your input!
