### ISSUE TITLE
Add versioned Image alias names and remove image aliases whose images do not exist

### ISSUE THREAD

**Issue by Sandido** [Azure/azure-cli#25736]
### Related command

az vm image list

### Resource Provider

Microsoft.Compute/compute

### Description of Feature or Work Requested

As discussed with several PMs and Xing Zhou from the CLI team, we had to update the Image aliases in PS. We want CLI to be change in parallel to this. 
The PS image updates: https://github.com/Azure/azure-powershell/pull/21012/files#diff-2b55a7c7b9a159041f1adb1ba967b55a8840ddc6e88df099b70a50c17331f6e2L9 

There is also a breaking change warning being added to New-AzVM to help amplify the communications and future changes in the Oct 2023 breaking change. We plan to update the CLI docs, https://learn.microsoft.com/en-us/azure/virtual-machines/linux/cli-ps-findimage#list-popular-images , that we know that refer to these image aliases. We want to include a link to these docs in the breaking change warning. 

### Minimum API Version Required

2022-11-01

### Swagger PR link / SDK link

N/A , should only be client side changes.

### Target Date

2023-04-01

### Additional context

We want this released in the next available CLI release. There may be some updates to the PS breaking change warning we would want mirrored in the CLI codebase too.

**Comment by yonzhan** [comment]
add versioned image alias names

**Comment by zhoxing-ms** [comment]
@Sandido This is the configuration file for image alias [aliases.json](https://github.com/Azure/azure-rest-api-specs/blob/main/arm-compute/quickstart-templates/aliases.json) used by the CLI, since it is currently maintained by the service team, could you help submit a PR to modify this configuration file? 
And then we will review it and add some warning log to notify the possible breaking changes in advance

**Comment by Sandido** [comment]
I need to make some edits to the PS work, so I will do that first before raising the CLI PR.

**Comment by zhoxing-ms** [comment]
@Sandido Thanks for creating the PR for CLI alias.json

> I don't know if there are any tests to update/create, or where to add the upcoming breaking change warning in New-AzVM and New-AzVmss like in PS.

We will do the rest of the work ourselves, and then let you help review the related PR
