### ISSUE TITLE
resource: improve the 'resource update' command

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#2573]
This command uses generic update mechanism and surface the API w/o polishing, which brings up 2 usabilility issues we should address?
1. The parent resource is not marked as mandatory in help, but the API needs it, and error out during the execution. We should eliminate this requirement unless we do have parent resource involved. 
2. It doesn't support resource id as other commands

We don't expect generic update to be easy to use, but this one is getting impossible to use, so we need to do somthing

**Comment by tjprescott** [comment]
There are many resources that have no parent... vnet for instance. What parent value is required here?

**Comment by yugangw-msft** [comment]
You need to provide an empty string.

**Comment by tjprescott** [comment]
We should default them to empty string if they are none.

**Comment by yugangw-msft** [comment]
That works. But the main work would be to support `resource-id`. Parent path by itself is very very confusing.

**Comment by yugangw-msft** [comment]
Fixed by #2640
