### ISSUE TITLE
Example shown for servicebus namespace cli is incorrect

### ISSUE THREAD

**Issue by dgunawan** [Azure/azure-cli#25741]
[Enter feedback here]
This example below:

List the Service Bus Namespaces under subscription

is not going to work with the newly introduced requirement of having to specify the resource group for the command to execute successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a85faa5-3912-4e96-2c27-1cb3b2314800
* Version Independent ID: cf596bc8-22e8-c839-97c4-305a9f151b78
* Content: [az servicebus namespace](https://learn.microsoft.com/en-us/cli/azure/servicebus/namespace?view=azure-cli-latest#az-servicebus-namespace-list-required-parameters)
* Content Source: [latest/docs-ref-autogen/servicebus/namespace.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/servicebus/namespace.yml)
* Service: **service-bus**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by Saglodha** [comment]
Hi @dgunawan , specifying resource group is not mandatory to list namespaces at subscription level. We are working on the fix : https://github.com/Azure/azure-cli/pull/26513, I would keep you posted.
