### ISSUE TITLE
Support for Routing Pref IpTag for PublicIpPrefix

### ISSUE THREAD

**Issue by brianlehr** [Azure/azure-cli#25740]
Resource Provider
NRP

Description of Feature or Work Requested
Need to have CLI support for way to add Routing Preference Internet IpTag to PublicIpPrefix

[https://github.com/Azure/azure-rest-api-specs/blob/release-Microsoft.Network-2022-09-01/specification/network/resource-manager/Microsoft.Network/stable/2022-09-01/publicIpPrefix.json](https://github.com/Azure/azure-rest-api-specs/blob/release-Microsoft.Network-2022-09-01/specification/network/resource-manager/Microsoft.Network/stable/2022-09-01/publicIpPrefix.json)

The command
**az network public-ip prefix create**

Needs to be able to utilize 
**--ip-tags 'RoutingPreference=Internet'**

This already exists in PowerShell and will soon work in portal, so this is just to cover all bases. 

Minimum API Version Required
2022-09-01

**Comment by yonzhan** [comment]
network feature

**Comment by brianlehr** [comment]
Hello @yonzhan what is status here?  I see it is backlog for April, does that mean it should finish this month?

**Comment by necusjz** [comment]
@brianlehr Yes, it should be released around 04/25.
