### ISSUE TITLE
Riyadh 

### ISSUE THREAD

**Issue by Marzog00** [Azure/azure-cli#25755]
![submarine](https://user-images.githubusercontent.com/124639536/224432433-3588c943-aa7b-4c5a-a5fe-8d82922772dd.png)

[Enter feedback here]

---
####muDocument Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7655de2-a91e-38e5-d672-a223ed0a3762
* Version Independent ID: ab1d3260-d618-863d-5572-eae492f4fa26
* Content: [az afd](https://learn.microsoft.com/en-us/cli/azure/afd?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/afd.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/afd.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@Marzog00 Can you please provide your issue description along with the cmdlet debug logs to further assist you.

**Comment by SaurabhSharma-MSFT** [comment]
@Marzog00 Please help us providing proper details to help you else we will proceed with the issue closure.

**Comment by SaurabhSharma-MSFT** [comment]
@Marzog00 We will now proceed to close this thread as we haven't heard back. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
