### ISSUE TITLE
 Top priority - Restrict basic sku on these regions when creating/updating a firewall

### ISSUE THREAD

**Issue by Gizachew-Eshetie** [Azure/azure-cli#25757]
**Related command**
az network firewall create, az network firewall update

**Is your feature request related to a problem? Please describe.**
Can you please block creating/updating a firewall on these regions since basic sku firewall is not available in these regions yet? Taiwan North, Canada East, Jlo India West, Poland Central, Spain Central, USSec West Central, Belgium Central, Germany North, Sweden South, China East 3

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
network feature

**Comment by necusjz** [comment]
should be handled by the server side
