### ISSUE TITLE
The word format is misspelled multiple times in the az bicep format examples section

### ISSUE THREAD

**Issue by gorlandor** [Azure/azure-cli#25760]
The word `Format` is misspelled multiple times in the `az bicep format` examples section. Currently says `Foramt` instead of `Format`. See screenshot and Diff below: 

<img width="1440" alt="Screen Shot 2023-03-11 at 3 21 24 PM" src="https://user-images.githubusercontent.com/11283367/224507896-b56a3dec-4462-4445-80aa-a4b30d865564.png">

## Diff

```diff
- Foramt a Bicep file.
+ Format a Bicep file.

- Foramt a Bicep file and print all output to stdout.
+ Format a Bicep file and print all output to stdout.

- Foramt a Bicep file and save the result to the specified directory.
+ Format a Bicep file and save the result to the specified directory.

- Foramt a Bicep file and save the result to the specified file.
+ Format a Bicep file and save the result to the specified file.

- Foramt a Bicep file insert a final newline.
+ Format a Bicep file insert a final newline.

- Foramt a Bicep file set indentation kind. Valid values are ( Space | Tab ).
+ Format a Bicep file set indentation kind. Valid values are ( Space | Tab ).

- Foramt a Bicep file set number of spaces to indent with (Only valid with --indent-kind set to Space).
+ Format a Bicep file set number of spaces to indent with (Only valid with --indent-kind set to Space).
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ed4cbd3-8434-dd97-a842-5ececa8010cb
* Version Independent ID: 60edc003-8f74-62af-e9fd-79efb5a77d9f
* Content: [az bicep](https://learn.microsoft.com/en-us/cli/azure/bicep?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/bicep.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/bicep.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@gorlandor Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@gorlandor The above PR has been created to address this. It is currently under Review.
