### ISSUE TITLE
"az ad app" no way to update spa redirect uri

### ISSUE THREAD

**Issue by AnthonyPhan** [Azure/azure-cli#25766]
**Related command**
Using the az command below you can update the re-direct URI for an Azure App Registration. However there seems to be no way to update the redirect URI for the single-page application section.

```
az ad app update --id {myId} --public-client-redirect-uris {myUrl}
or 
az ad app update --id {myId} --web-redirect-uris {myUrl}
```

<img width="827" alt="image" src="https://user-images.githubusercontent.com/12785492/224554656-04114376-cef5-4e9a-ae0d-572296ca3182.png">

**Is your feature request related to a problem? Please describe.**
To take advantage of the more secure authorization code flow with PKCE you need to add your redirect URL in the SPA section of an Azure app registration ([reference](https://github.com/MicrosoftDocs/azure-docs/issues/70484)). However, there seems to be no way to add this using the azure CLI which limits what can be done in our CI in Github actions. 

**Describe the solution you'd like**
Add a --spa-redirect-uris option to update this field.

**Describe alternatives you've considered**
Using the REST API

**Additional context**
There seems to be no option outline in the [docs here](https://learn.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-show).

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by jiasli** [comment]
Updating `spa.redirectUris` is currently not supported. Please see https://learn.microsoft.com/en-us/cli/azure/microsoft-graph-migration#known-issues for workarounds.

**Comment by leonk** [comment]
Just to add how I've managed to do it (as there's currently nothing on [known issues link](https://learn.microsoft.com/en-us/cli/azure/microsoft-graph-migration#known-issues) specifically about this).

Using the graph api, e.g.

```
az rest \
  --method "patch" \
  --uri "https://graph.microsoft.com/v1.0/applications/<<object-id>>" \
  --headers "{'Content-Type': 'application/json'}" \
  --body "{'spa': {'redirectUris': [ 'https://jwt.ms', 'https://www.example.com/callbacks' ]}}"
```

**Comment by jiasli** [comment]
Tracked by https://github.com/Azure/azure-cli/issues/14880

**Comment by laurentbel** [comment]
The CLI obviously supports setting SPA redirect URIs via : 
`az ad app update --id {yourID} --set 'spa={"redirectUris": ["https://whatever.com/","https://whatever.me/"]}'`

This worked, using recent AZ CLI on Ubuntu WSL. Hope this will help.

**Comment by VigneshC08** [comment]
> The CLI now obviously supports setting SPA redirect URIs via : `az ad app update --id {yourID} --set 'spa={"redirectUris": ["https://whatever.com/","https://whatever.me/"]}'`
> 
> This worked, using recent AZ CLI on Ubuntu WSL. Hope this will help.

Thanks @laurentbel
