### ISSUE TITLE
ACR Build Error on Github Actions

### ISSUE THREAD

**Issue by Malay-Acharya** [Azure/azure-cli#25765]
While Deploying on Github Actions, this message appears on the ACR Build Step:
Logging into azure..
[
  ***
    "cloudName": "AzureCloud",
    "homeTenantId": "***",
    "id": "db936aea-bdec-4955-94eb-bedb32a8aad1",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Pay-As-You-Go",
    "state": "Enabled",
    ***,
    "user": ***
      "name": "***",
      "type": "servicePrincipal"
    ***
  ***
]
Sending build job to ACR..
WARNING: Sending context to registry: ***...
WARNING: Queued a build with ID: ca37
WARNING: Waiting for an agent...
20[23](https://github.com/team-listnr/listnr-backend/actions/runs/4395331031/jobs/7697046958#step:4:24)/03/12 02:[32](https://github.com/team-listnr/listnr-backend/actions/runs/4395331031/jobs/7697046958#step:4:33):56 Downloading source code...
Run ID: ca[37](https://github.com/team-listnr/listnr-backend/actions/runs/4395331031/jobs/7697046958#step:4:38) failed after 2s. Error: failed to download context. Please check if the URL is incorrect. If it has credentials, please check if they are expired
ERROR: Run failed

I am on a private repository. I tried building the image and deploying to Azure on my local machine and that is working perfectly.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@Malay-Acharya Could you share the complete command that you are trying to run here? Also, are you trying to pull context from another ACR by any chance?

**Comment by Malay-Acharya** [comment]
Hey @PramodValavala-MSFT , I solved the problem, It was related to the PAT used for accessing the private repo in ACR Build, Changed it and it worked. Our DevOps guy had left the organization and probably used his PAT in the ACR build step, that caused the problem.
