### ISSUE TITLE
Addition of the Data Box Import Export Jobs SKU support in the Azure Data Box Azure CLI.

### ISSUE THREAD

**Issue by jeevanbalanmanoj** [Azure/azure-cli#25777]
Import Export jobs in Data Box enable customers to send in their own hardware to do the copy. This is currently not supported in Azure CLI and we need this support by April

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by jsntcy** [comment]
@jeevanbalanmanoj, please provide more details for this request, such as what command/argument you want to add/update? what's API version? where is the properties/operations related to this request in swagger?
