### ISSUE TITLE
Support for Customer Managed Key for Data Box Disk in Azure Data Box Azure CLI.

### ISSUE THREAD

**Issue by jeevanbalanmanoj** [Azure/azure-cli#25778]
Customer Managed key support is missing in Azure CLI for Data Box Disk

> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by jsntcy** [comment]
@jeevanbalanmanoj, please provide more details for this request, such as what command/argument you want to add/update? what's API version? where is the properties/operations related to this request in swagger?
