### ISSUE TITLE
az ad app gives not consistent output

### ISSUE THREAD

**Issue by GBreply** [Azure/azure-cli#25786]
**Related command**

`az ad app show ` and `az ad app credential list`

**Describe the bug**

When calling `az ad app show --id <id> | jq '.passwordCredentials[]'` (or `az ad app credential list --id <id>`) on my local machine I receive the key `endDateTime` among the others:
![image](https://user-images.githubusercontent.com/109596790/223779046-5d1dbe79-0130-4b4d-a34a-f5384bf0edf2.png)
When calling the same command with the same image in a devops pipeline, the key returned is `endDate`:
![image](https://user-images.githubusercontent.com/109596790/223779487-2351e1cc-2d4a-4c50-83a8-de87e00cfddc.png)

Also, in the local machine `az ad app show --id <id>` provides the `hint` field, while in the pipeline this field is not provided: \
local:
![image](https://user-images.githubusercontent.com/109596790/224685367-9de56f3f-b28e-420b-938c-55e616cbb1a3.png)
remote:
![image](https://user-images.githubusercontent.com/109596790/224685840-5701d4dc-367a-46f5-8970-012c6c1d81fc.png)

The only difference is that the pipeline is running on a node in Frankfurt, while my local machine is in Italy. The authentication is the same.

**To Reproduce**

Not sure, maybe calling the API from different part of the world.

**Expected behavior**

I would expect the api to be consistent if the image of the container is the same, thus the az cli version.

**Environment summary**

az cli version -> 2.40.0

**Comment by yonzhan** [comment]
@jiasli for awareness
