### ISSUE TITLE
The latest supported azure cli version for SUSE 12 or SUSE 15

### ISSUE THREAD

**Issue by tujack-msft** [Azure/azure-cli#25781]
The current az cli version is 2.46 but when I follow the document add the microsoft azure cli repo [Install the Azure CLI on Linux | Microsoft Learn](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=zypper#install-azure-cli) to install the latest version of azure cli on Suse 12 and Suse 15. 
The latest version i found is 2.38.
![image](https://user-images.githubusercontent.com/127732530/224657088-db199472-22b3-42f0-80b6-3360ae24c765.png)

Please kindly advise if Azure CLI 2.45/2.46 is supported on Suse os 12/15 or not. If it is supported, when can I expect the azure cli 2.45 version available in the azure cli repo. 
If it's supported, could you please kindly share the step to install the azure cli 2.45 on suse 12/15. Thanks!

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by stephan-uhlmann** [comment]
I experienced the same problem. The packages in https://packages.microsoft.com/yumrepos/azure-cli/ stopped being updated with 2.38.0.

@tujack-msft you created it but also closed the ticket without comment. Was there an actual solution to it?
The documentation at https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=zypper still references the outdated repo.

**Comment by tujack-msft** [comment]
> I experienced the same problem. The packages in https://packages.microsoft.com/yumrepos/azure-cli/ stopped being updated with 2.38.0.
> 
> @tujack-msft you created it but also closed the ticket without comment. Was there an actual solution to it? The documentation at https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=zypper still references the outdated repo.

@stephan-uhlmann  Hi Stephan, after I check internally, it is found in the official document warning part that the azure CLI support in SUSE stopped.
Paste the warning part below for your reference:

_The last Azure CLI package developed by Microsoft for SUSE Linux Enterprise Server (SLES), and OpenSUSE (Leap), is version 2.39.0 (released on 08/02/2022). You may continue to use historical versions of Azure CLI on these systems, but there will be no further updates or bug fixes from Microsoft for those versions.

Azure CLI and the Linux [Install script](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script) will continue to be developed and supported by Microsoft. Packages provided by SUSE/OpenSUSE repositories are maintained and supported by SUSE._

**Comment by stephan-uhlmann** [comment]
Thanks @tujack-msft . I missed the warning. Too bad.
Fortunately openSUSE Tumbleweed releases new versions of the azure-cli so I found a way. The curl|bash of the generic Install script isn't for me. ;-)
