### ISSUE TITLE
Build the dependency between Extensions.

### ISSUE THREAD

**Issue by howang-ms** [Azure/azure-cli#25782]
Today, a CLI extension can be used to overwrite the command in the Core CLI, which give us the capability to put the stable-only feature in the Core CLI and use the extension for the preview-only feature. For example, the aks-preview extension. 

Can we support a similar capability between the two CLI extensions? For example, we can have the "containerapp" and "containerapp-preview" extensions. And the "containerapp-preview" extension will overwrite the selected command in the "containerapps" extension.

**Comment by yonzhan** [comment]
feature ask for CLI extensions

**Comment by wangzelin007** [comment]
New feature:
Support `azext.minGaExtensionVersion` and `azext.minGaExtensionName` parameters. 
After specifying these two parameters, if user upgrade the preview extension, need to check the Ga extension version.

**Comment by wangzelin007** [comment]
Question:
Can we support that Ga extension and preview extension depend on different versions of packages? 
Workaround:
1. Use the rest api with api version directly
2. Use vendored_sdks to avoid conflicts
