### ISSUE TITLE
`azure container` requires unavailable api version in sovereign clouds (e.g., Azure Government)

### ISSUE THREAD

**Issue by timothymeyers** [Azure/azure-cli#25791]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

`az container <all commands>`

**Describe the bug**

2.46.0 depends on the 2022-10-01-preview api for Microsoft.ContainerInstance/containerGroups resource type. This api version is not available in our sovereign clouds, namely Azure Government, and since the upgrade of Cloudshell to use 2.46.0 of the cli last week, we can no longer manage Azure Container Instances via the command line.

The most recent api-version available is 2021-09-01.

I see changes to the cli automated tests updated the api version in this commit - https://github.com/Azure/azure-cli/commit/dc24c81d635a1ffec15ba5ff2c78e120ab593169 - but I've been unable to locate the actual dependency.

**To Reproduce**

On Azure Government, open Cloudshell, `az container list` will produce an InvalidResourceType exception with

> Message: The resource type 'containerGroups' could not be found in the namespace 'Microsoft. Containerlnstance' for api version '2022-10-01-preview'.

**Expected behavior**

**Environment summary**

CloudShell on Azure Government

**Additional context**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@timothymeyers Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@timothymeyers This API version parity issue in the Azure Government cloud is being looked into. The ETA is end of week.

**Comment by navba-MSFT** [comment]
@timothymeyers The new API version is available in the US Gov Arizona region. It will be available in the US Gov Virginia region by Monday.

**Comment by timothymeyers** [comment]
Thanks @navba-MSFT - I just tested and its working. Thanks for the quick turn!

**Comment by navba-MSFT** [comment]
@timothymeyers Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
