### ISSUE TITLE
[Monitor] Simplify experience around taking list of complex objects instead of JSON

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-cli#2583]
Some of the monitor commands, accept JSON as the input. We should think about simplifying the experience around take/constructing those parameters. 

Example commands:
```
az monitor alert-rules create -h
```
```
az monitor autoscale-settings create -h
```

**cc**
@tjprescott / @johnkemnetz

**Comment by tjprescott** [comment]
These have both been done.
