### ISSUE TITLE
az sql server list fails with AzureChinaCloud

### ISSUE THREAD

**Issue by charlesRollandy** [Azure/azure-cli#25842]
Running command `az sql server list -g $ResourceGroup` in azure china cloud with a valid resource group fails with the following error message:

> (InvalidResourceType) The resource type 'servers' could not be found in the namespace 'Microsoft.Sql' for api version '2022-08-01-preview'. The supported api-versions are '2014-04-01,2014-04-01-preview,2015-05-01-preview,2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview'.

Azure CLI version : 2.46.0

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@charlesRollandy Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@charlesRollandy Could you please run the below command and check if that helps ?

> **az rest --method get --url "https://management.azure.com/subscriptions/XXXXXX/providers/Microsoft.Sql/servers?api-version=2022-05-01-preview"**

**Comment by navba-MSFT** [comment]
@charlesRollandy I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by ondrejmichlicekips** [comment]
We suffered from same issue with latest Az-cli in ChinaCloud in past days as well. There was problem with not available REST API 2022-08-01-preview. But it seems, it was fixed today and now REST API 2022-08-01-preview is available in ChinaCloud and problem is gone.

**Comment by charlesRollandy** [comment]
I can also confirm the issue is gone for me too
