### ISSUE TITLE
No longer able to AllowAzureServices with az storage account network-rule since 2.46.0

### ISSUE THREAD

**Issue by drjwelch** [Azure/azure-cli#25849]
**Related command**
az storage account network-rule add --account-name XXXXX --ip-address 0.0.0.0/0

**Describe the bug**
In 2.45: there is no check for overlapping IP ranges
In 2.46: [this check](https://github.com/Azure/azure-cli/pull/25514/files#diff-62db8acc792b674b2cce2a480af9d1d39511fff32f946f9624aca39dd5c493c5R2251) prevents adding 0.0.0.0/0 (AllowAzureServices) because it overlaps with any other existing rule

**To Reproduce**
Create storage account
Add network rule with CIDR range e.g. 80.80.80.80/28
Run the above command

**Expected behavior**
All existing rules retained and 0.0.0.0/0 is added

**Actual behaviour**
WARNING: IP/CIDR 0.0.0.0/0 overlaps with 123.123.123.123, which exists already. Not adding duplicates.
and 0.0.0.0/0 is not added

**Environment summary**
Build agent in Azure devops pipeline running bash script task
/usr/bin/az --version
azure-cli 2.46.0
core 2.46.0
telemetry 1.0.8 
Extensions:
azure-devops 0.26.0 
Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1

**Comment by evelyn-ys** [comment]
Can you allow AzureServices by `az storage account update --name $accountName --resource-group $rgName --bypass AzureServices`?

**Comment by drjwelch** [comment]
This does work, thank you.

However it still doesn't allow the build agent to query the state of the fileshare because DevOps pipelines are not included in the trusted Azure services list.

We have worked around this using `az storage account update --name $accountName --default-action Allow`
