### ISSUE TITLE
How to change az network application-gateway rewrite-rule create --response-header "action-type"?

### ISSUE THREAD

**Issue by manikg321** [Azure/azure-cli#25856]
Using az network application-gateway rewrite-rule create --response-header, how to change 'action-type'. Documentation provided isn't clear.
![image](https://user-images.githubusercontent.com/81321710/225786115-6069765d-7685-46bc-8619-37bf731148d9.png)
![image](https://user-images.githubusercontent.com/81321710/225786547-b7c6db85-4287-406b-9c13-0e1701bba68d.png)
![image](https://user-images.githubusercontent.com/81321710/225786966-d249974b-4c96-4b34-b87c-3b709d454383.png)

The following command used to work in az versions till 2.40.0, now it is not working any more.
```az network application-gateway rewrite-rule create --resource-group  --gateway-name  --name rewriteHeaders --response-headers Server=""```
Errors: Failed to parse '--response-headers' argument: argument value cannot be blank

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
@manikg321 You can use `--response-headers Server=''` to input an empty string.

**Comment by manikg321** [comment]
[cid:640337fc-a03e-48d8-b37f-00f9f4bef019]

Failed to parse '--response-headers' argument: argument value cannot be blank

Thanks,
Mani

Mani Kiran Gatla​
 |
Senior DevOps Engineer
Elekta
1450 Beale Street, Suite 205
St. Charles,
MO
63303,
United States
***@***.******@***.***>
 |
www.elekta.com<https://www.elekta.com/>
***@***.***
This message is confidential and may be legally privileged or otherwise protected from disclosure. ​If you are not the intended recipient, please telephone or email the sender and delete this message ​and any attachment from your system; you must not copy or disclose the contents of this message ​or any attachment to any other person.
Any views expressed in this message are those of the individual sender, except where the sender specifies ​and with authority, states them to be the views of Elekta. Elekta may monitor email traffic data.
________________________________

**Comment by necusjz** [comment]
If you wanna input an empty string, please try `--request-headers Server="''"` in PowerShell.

**Comment by manikg321** [comment]
Command seem to be incorrect with --request-headers Server="''" or --request-headers Server='""'. I see resource group not found error. Az cli is not able interpret command.

Thanks,
Mani



Mani Kiran Gatla | Senior DevOps Engineer
Elekta
1450 Beale Street, Suite 205
St. Charles, MO 63303, United States
***@***.*** | www.elekta.com
This message is confidential and may be legally privileged or otherwise protected from disclosure. ​If you are not the intended recipient, please telephone or email the sender and delete this message ​and any attachment from your system; you must not copy or disclose the contents of this message ​or any attachment to any other person.
Any views expressed in this message are those of the individual sender, except where the sender specifies ​and with authority, states them to be the views of Elekta. Elekta may monitor email traffic data.

**Comment by manikg321** [comment]
actually it is not --request-headers, it is --response-headers. Quotes within quotes isn't working.

Thanks,
Mani
Mani Kiran Gatla​
 |
Senior DevOps Engineer
Elekta
1450 Beale Street, Suite 205
St. Charles,
MO
63303,
United States
***@***.******@***.***>
 |
www.elekta.com<https://www.elekta.com/>
***@***.***
This message is confidential and may be legally privileged or otherwise protected from disclosure. ​If you are not the intended recipient, please telephone or email the sender and delete this message ​and any attachment from your system; you must not copy or disclose the contents of this message ​or any attachment to any other person.
Any views expressed in this message are those of the individual sender, except where the sender specifies ​and with authority, states them to be the views of Elekta. Elekta may monitor email traffic data.
________________________________

**Comment by necusjz** [comment]
I have to say it works in my environment, both --request-headers and --response-headers:

![image](https://user-images.githubusercontent.com/12371639/226251681-4dff2dbb-9751-4e9e-90aa-c8c0ecc82dc3.png)

Never mind, let's back to the original question, i.e., how to change "action-type"?
- For set operation: az network application-gateway rewrite-rule create --response-headers foo=bar
- For delete operation: az network application-gateway rewrite-rule **update** --response-headers foo=**null**

**Comment by manikg321** [comment]
Thank you! Quotes within quotes works.
