### ISSUE TITLE
Improve experience adding/removing VMs/NICs to/from load balancers

### ISSUE THREAD

**Issue by iainfoulds** [Azure/azure-cli#2586]
Couple of suggestions for improving the experience when working with load balancers. Or set me straight if I'm just doing it all wrong :)

To add or remove a VM from the load balancer, you actually work with a virtual NIC resource. Logically, and architecturally, this makes sense. But really, it's the VM you're working on.

`az vm create` allows you to specify `--nsg` or `--subnet` to hook a VM up to existing network resources. Adding the option for `--lb-name` and `--lb-backend-pools` would be awesome. Or am I missing how to create a VM, let a new virtual NIC be created, and add it to a load balancer? Now it seems like you have to create the NIC with:

```
az network nic create \
  --resource-group myResourceGroup \
  --name myNic \
  --vnet-name myVnet \
  --subnet mySubnet \
  --network-security-group myNetworkSecurityGroup \
  --lb-name myLoadBalancer \
  --lb-address-pools myBackEndPool
```

And then create the VM with `az vm create --nics myNic [...]`

Kind of along the same lines, adding or removing a VM from a load balancer means working with the virtual NIC resource. Cool, a VM could have more than virtual NIC, but then it seems like I have to obtain the ID for a virtual NIC, strip to get just the name, and then remove or add from the load balancer. I can get the ID for a virtual NIC from a VM, but `az network nic ip-config address-pool remove` or `address-pool add` wants a NIC **name**, not **ID**. So I end up with:

```
vmnic=$(az vm show --resource-group myResourceGroup --name myVM \
    --query [networkProfile.networkInterfaces[*].id] --output tsv | sed 's:.*/::')

az network nic ip-config address-pool remove \
    --resource-group myResourceGroup \
    --nic-name $vmnic \
    --ip-config-name ipConfig1 \
    --lb-name myLoadBalancer \
    --address-pool myBackEndPool 
```

Or again, am I missing an easier way here? 

Suggestion would be to either

- allow `az network nic ip-config add | remove` to accept something like `--nic-id` rather than `--nic-name`, or 
- allow for `--vm-name` and then take the first virtual NIC attached to the VM.

**Comment by tjprescott** [comment]
Hi @iainfoulds the help text for `nic ip-config backend-address add`:

```
Resource Id Arguments
    --ids                    : One or more resource IDs (space delimited). If provided, no other
                               'Resource Id' arguments should be specified.
    --ip-config-name -n      : The name of the IP configuration.
    --nic-name               : The network interface (NIC).
    --resource-group -g      : Name of resource group. You can configure the default group using 'az
                               configure --defaults group=<name>'.
```

So you can either specify --nic-name + --resource-group + --ip-config-name  OR --ids, which should accept the ID of the nic IP config.

**Comment by tjprescott** [comment]
However, more to the substance, you are absolutely right that we could have a better way of adding/removing VMs to/from not just load balancers but also application gateways. Currently, we basically expose the REST endpoints, but I think this would be a VERY good case for convenience commands which handle this messy business. I would suggest something like:

`az network lb/application-gateway backend-address-pool add/remove-vm`

Or something similiar. Thoughts?

**Comment by iainfoulds** [comment]
Totally missed being able to add in `--ids`, thanks Travis. That's more reasonable and on parity with other commands :) Ignore that part then!

On the second part, totally get just following how the REST endpoints are used. I like the proposal for accepting a VM name/ID to be specified, and performing a look-up for the user that then maps that to what the REST call is going to need. That fits more in line with how `az vm create` has a bunch of convenience flags that are doing similar look-ups behind the scenes to make the appropriate calls on behalf of the user. 

So for `az network lb/app-gw`, that's a good approach. I'd still suggest something similar be added to `az vm create` so you don't have to pre-create virtual NICs and hook them up accordingly, and then attach to the NIC to the VM. For larger deployments, the current approach is probably technically more valid, but for simplicity and wanting to just get something running, exposing it during the VM create would be awesome.

**Comment by tjprescott** [comment]
My thought would be that you would have something like:
```
az network lb create ...
az vm create ...
az network lb backend-pool add-vm ...
```

**Comment by iainfoulds** [comment]
That would work. Only argument for including in `az vm create` is that (from example tutorial I'm working on), you define your load balancer rules and health probe ahead of time. If you create the VM using cloud-init or custom script extension to then configure an app on the VM, once the health probe receives a healthy response from the VM/app, it is added to the load balancer rotation. Otherwise, you'd have to wait until the VM is created, configured, and then add it to the LB. Not sure which is the most appropriate, really.

**Comment by tjprescott** [comment]
cc/ @johanste, since we were talking about this very thing just the other day. Thoughts?

**Comment by johanste** [comment]
Both suggestions sound reasonable. I would definitely advocate to do something along the lines of what @tjprescott  suggests (have explicit/easy option to add VMs/NICs to the load balancer without having to go through hoops of finding nics associated with VM/backend address pool names)

Adding the ability to specify a load balancer in the VM/NIC create is also interesting, but that would come with the additional baggage of adding more parameters to commands that are already crowded. This makes it less of a slam-dunk from my perspective. 

@iainfoulds, if you could do:

```bash
az network nic create --name blah ...
az network lb backend-pool add-nic --nic-name blah ...
az vm create --nics blah ...
```

would that be a reasonable alternative to being able to specify the lb name on vm create?

**Comment by iainfoulds** [comment]
That workflow isn't too dissimilar to the current approach. Here's where all this came from, when I was first putting together a tutorial that details how to load balance VMs - how we add and remove from LB now - https://docs.microsoft.com/en-us/azure/virtual-machines/linux/tutorial-load-balancer#add-and-remove-vms

I'm totally glossing over the fact that you already know/assume myNic**2** is attached to myVM**2**. Otherwise I need to query the VM to find out which NIC is connected, and then pass that NIC name or ID.

Yes, you can have VMs with multiple NICs if the CLI does this under the hood for you. And yes, NICs can be long standing resources whereas the VM resource itself could be torn down and a new one stood up :) But, for the quick-ish start scenario where folks just want two or three VMS behind a load balancer so they can test how their app responds, can make the case they'd only have one NIC per VM.

So I'm cool with not adding to bloat of `az vm create`, but at least the CLI doing the lookup of NIC to VM for those load balancer operations would be sweet. That way I have a few commands to build the LB, use `az vm create` to prop my vnet, subnet, and NSG, and then just attach my _VM_ to the LB without worrying about what NIC was created or having to create all those networking resources first and _then_ attach the NIC to the VM.

Is that a good middle ground? `az network lb backend-pool add-vm` or `az network lb backend-pool remove-vm` where the CLI looks up the NIC mapping based on the VM provided?

**Comment by tjprescott** [comment]
> Or am I missing how to create a VM, let a new virtual NIC be created, and add it to a load balancer? Now it seems like you have to create the NIC with:
> az network nic create .. --lb-name myLoadBalancer --lb-address-pools myBackEndPool
> And then create the VM with az vm create --nics myNic [...]

You can just create the LB, create the VM, and then use:

`az network nic ip-config address-pool add --lb-name myLoadBalancer --address-pool myBackEndPool --id <NIC ip-config ID>`

**Comment by tjprescott** [comment]
Due to the perceived amount of engineering effort needed to simplify these scenarios balanced against the lack of customer asks in this area, we have decided to not pursue these changes.
