### ISSUE TITLE
az vmss create change request - "--orchestration-mode" should default to flexible instead of uniform

### ISSUE THREAD

**Issue by hilaryw29** [Azure/azure-cli#25863]
### Related command

az vmss create

### Resource Provider

Microsoft.Compute/ComputeRP

### Description of Feature or Work Requested

Feature request to change **default "--orchestration-mode"** for [az vmss create](https://learn.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-create) from "uniform" to **"flexible"** orchestration.

This feature request will go alongside a PowerShell change to default the OrchestrationMode of "New-AzVMSS" to Flexible orchestration for both Default and Simple parameter sets. 

**Ask on CLI team**

Today, **`az vmss create -n simplescaleset -g demorg --image ubuntults`** creates a VMSS in **uniform** orchestration mode with defaults for other parameters (new vnet/subnet, new load balancer, manual update mode). 

We are asking to change the default for "--orchestration-mode" so that **`az vmss create -n simplescaleset -g demorg --image ubuntults`** will create a VMSS in **flexible** orchestration mode with:
-  a new vnet/subnet (no change from previous)
- new load balancer (no change from previous)
- (NEW) **nat rules instead of nat pool** 
- (NEW) **null or [] for upgrade policy instead of 'manual'**

As this will be a breaking change, we are asking CLI to display a warning in the meantime notifying customers that the default orchestration mode for `az vmss create` will be changing to Flex. An example of the breaking change message for Powershell can be found [here](https://github.com/Azure/azure-powershell/pull/21022/files).

### Minimum API Version Required

current

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable

### Target Date

2023-05-01

**Comment by yonzhan** [comment]
compute feature

**Comment by zhoxing-ms** [comment]
In addition, could we consider releasing the real changes in the next **Ignite release** (after the Build release). Otherwise, I'm worried that this breaking change will have a very huge and incalculable impact for customers.
+ VMSS PM @fitzgeraldsteele + CLI PM @dcaro to be aware of this matter

**Comment by hilaryw29** [comment]
Hi Xing, thanks for your response. 

The context for this change was due to a [bug discovered on Powershell](https://github.com/Azure/azure-powershell/issues/18217) where New-AzVMSS defaulted to two different orchestration modes when neither are given any Vm Profile properties on Default vs Simple parameter set.

1. Default parameter set – default to OrchestrationMode: **Flexible**
$RGName = "dp-vmss"
$VMSSName = "sap-flex"
$Location = "westus2"
$vmssConfig = New-AzVmssConfig -Location $Location -PlatformFaultDomainCount 3
$VMSS = New-AzVmss -ResourceGroupName $RGName -Name $VMSSName -VirtualMachineScaleSet $vmssConfig -Verbose

2. Simple parameter set – default to OrchestrationMode: **Uniform**
New-AzVmss -ResourceGroupName dp-vmss -Name sap-flex3 -Location westus2 -PlatformFaultDomainCount 3

In case 1, VM Profile = null and created a Flex VMSS, case 2 created a VMSS in Uniform mode with VmProfile. This created an inconsistent user experience for New-AzVmss parameter sets. 

**To address this, the change we are making on PS is the following:**
- **Have simple parameter set (case 2) always default to OrchestrationMode: Flexible with VmProfile (this will be a breaking change on PS)**

The expected behaviour on PS after this change will be:
- Default parameter set – default to OrchestrationMode: Flexible with VmProfile = null (no change from previous)
- Simple parameter set – default to OrchestrationMode: **Flexible** with VmProfile

The reason for this request is so that the VMSS create experience remains consistent for customers on both PS and CLI. This default (orchestration mode = Flex) is also being rolled out on Portal. 

We understand that this will be a significant breaking change so we would like to get guidance from CLI on how to best make this transition (what level of customer communication we can provide, timelines we should follow, etc.). Happy to work with @dcaro and yourself to understand the process here.

**Comment by zhoxing-ms** [comment]
@hilaryw29 @fitzgeraldsteele Since this is a very large and complex breaking change, we may need to consider publishing a special document for this breaking change to inform users of the details of specific changes, and then adding the document link to the notification message of warning log, what do you think of it?
@dcaro May I ask do you have any ideas and suggestions for this request with significant breaking change?

**Comment by fitzgeraldsteele** [comment]
I like this idea... @Hilary ***@***.***> lets work on a doc that will:

  *   Highlight the change and rationale
  *   How to update scripts to keep the existing behavior (specify --orchestration-mode uniform)
  *   What they will have to change to update to Flex (point to the migration docs)




Jerry
Steele
Microsoft
senior program manager
425.421.2566


________________________________

**Comment by hilaryw29** [comment]
@zhoxing-ms @fitzgeraldsteele The docs suggestion makes sense, I can help drive that.

Thoughts on the following timeline?:
- end of April/first week of May: Publish documentation + announcement of breaking change. Add breaking change notification message to warning log with link to the documentation/announcement
- Between May - September: Customers receive warning message of impending changes. Cx are expected to update scripts if they would like to keep existing behaviour (by specifying uniform orchestration).
- September: Breaking change release with `az vmss create` defaulting to flexible orchestration mode

**Comment by zhoxing-ms** [comment]
> end of April/first week of May: Publish documentation + announcement of breaking change. Add breaking change notification message to warning log with link to the documentation/announcement

The release time for our next sprint is `-04-25`, we can plan to catch up with this date.

> Between May - September: Customers receive warning message of impending changes. Cx are expected to update scripts if they would like to keep existing behaviour (by specifying uniform orchestration).

Sounds good!

> September: Breaking change release with az vmss create defaulting to flexible orchestration mode

The **Ignite** breaking change window is not September but November. May I ask is this date acceptable?

**Comment by hilaryw29** [comment]
Hi Xing,

Just updating this thread. Ignite breaking change window in November is acceptable. We'll be working on a tech communities blog post announcing the breaking change + migration options. We'll also be reaching out to top customers expected to be impacted by this change via support channels/email in early May. Will share an update once the blog post is published so that we can update the warning messages for CLI. Let me know if this works!

Thanks,
Hilary

**Comment by zhoxing-ms** [comment]
@hilaryw29 Sounds good, thanks for the help!

**Comment by zhoxing-ms** [comment]
@hilaryw29 @fitzgeraldsteele I have submitted a PR #26171 to add the warning log. Could you please help review it to see if it meets your expectations?

**Comment by hilaryw29** [comment]
Hi @yonzhan, just want to confirm, we are planning to roll out this breaking change on PowerShell and CLI during Ignite (November 2023), not Build.

**Comment by zhoxing-ms** [comment]
>  just want to confirm, we are planning to roll out this breaking change on PowerShell and CLI during Ignite (November 2023), not Build. This is to give customers more lead time to update their deployment scripts/make changes. We'll also be reaching out to large customers over next 6 months to make sure they are aware of this breaking change.

Yes, this is a good plan. In fact, our warning message also indicates that `Ignite (November) 2023` is the actual date of launching breaking change

**Comment by yonzhan** [comment]
Yes, we will move it to the Ignite sprint after creating.

**Comment by Jing-song** [comment]
-(NEW) **null or [] for upgrade policy instead of 'manual'**

Hi @hilaryw29   This requirement may not be met
When `upgradePolicy` is `null`, service return vmss with `“upgradePolicy: {"mode": "Manual"} `
When `upgradePolicy` is `[]`, service return error, because the parameters do not meet the [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/afa158ef56a05f6603924f4a493817cec332b113/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-07-01/virtualMachineScaleSet.json#L3621-L3646)

**Comment by hilaryw29** [comment]
Hi @Jing-song, what is the current value/default for "upgradePolicy" when customer makes a VMSS Flexible deployment on CLI today? If it is not already null/manual, we should set upgradePolicy to null with this update. Thanks!

**Comment by Jing-song** [comment]
> Hi @Jing-song, what is the current value/default for "upgradePolicy" when customer makes a VMSS Flexible deployment on CLI today? If it is not already null/manual, we should set upgradePolicy to null with this update. Thanks!

Hi @hilaryw29  
Before change, the default value was manual, create a vmss  with `az vmss create -n simplescaleset -g demorg --image ubuntults`

**Part of the request body**: 
```
"upgradePolicy": {
    "mode": "Manual"
}
```
**result:**
![image](https://github.com/Azure/azure-cli/assets/37168047/ac6e390a-8d69-49aa-8102-142c6c05381d)

after change, the default value is null

**Part of the request body**: 
```
"upgradePolicy": null
```
**result:**
![image](https://github.com/Azure/azure-cli/assets/37168047/2f5e9a55-9fd7-4734-aeed-05711b9213d7)


We cannot change it to null, is this expected?

**Comment by hilaryw29** [comment]
Hi @Jing-song,

"We can change the default value of the parameter(--upgrade-policy-mode) from manual to None, but the result does not change, is this as expected?"

- Do you mean from manual to **null**? If so, yes, this is as expected. Upgrade policy is currently omitted for VMSS Flex because we only have Manual. So "null" will automatically default to Manual. Thanks!

**Comment by hilaryw29** [comment]
@Jing-song Do you know if this breaking change will be rolled out in phases (following SDP)? Or will it be released to all regions at the same time? Is there any way for our support engineers to test this change prior to full release? Thanks!

**Comment by zhoxing-ms** [comment]
@hilaryw29 Yes, this feature will be released in the Ignite sprint on **11-14**, please use the private package [package link](https://dev.azure.com/azclitools/public/_build/results?buildId=103097&view=artifacts&pathAsName=false&type=publishedArtifacts) from edge build to test this feature in advance

**Comment by Jing-song** [comment]
Hi @hilaryw29 ,  Does **Azure Stack Hub**’s `--orchestration-mode` need to set the default value to `flexible`? https://github.com/Azure/azure-cli/issues/27806

**Comment by yanzhudd** [comment]
Hi @hilaryw29,
it appears this breaking change would cause the response of "/subscriptions/{}/resourceGroups/{}/providers/microsoft.Compute/virtualMachineScaleSets/{}/networkInterfaces" returned 404. More details could refer to the issue #28258.
Could you please help confirm if this is meet your expectation?

**Comment by hilaryw29** [comment]
Hi @yanzhudd, looking into this.
