### ISSUE TITLE
Update OS disk selection when creating a VMSS resource through CLI using a non-premium VM

### ISSUE THREAD

**Issue by lorbichara** [Azure/azure-cli#25874]
### Related command

az vmss create \
  --resource-group lobichar-rg \
  --name lorraine-vmss-test-4 \
  --orchestration-mode Flexible \
  --image UbuntuLTS \
  --upgrade-policy-mode automatic \
  --instance-count 2 \
  --admin-username azureuser \
  --generate-ssh-keys \
  --vm-sku Standard_D2_v4

### Resource Provider

N/A

### Description of Feature or Work Requested

When creating a virtual machine scale set (VMSS) through the Azure Portal, the default OS disk selection when selecting a VM that does not support premium storage, is a Standard SSD disk (exact disk SKU name is _StandardSSD_LRS_). When creating a VMSS resource using CLI, using the same VM (Standard_D2_v4, for example), the OS disk gets defaulted to Standard HDD (_Standard_LRS_).

The ask is to update the creation template so when creating a VMSS through CLI using a VM that doesn't support premium storage, the OS disk selection defaults to Standard SDD as well. This will provide consistency with the portal experience, and Standard SDD disks are better in terms of performance and availability.

### Minimum API Version Required

N/A

### Swagger PR link / SDK link

N/A

### Target Date

N/A - the sooner the better as Standard HDD disks aren't as reliable as Standard SSD.

**Comment by yonzhan** [comment]
compute feature

**Comment by zhoxing-ms** [comment]
@lorbichara Could you please specifically describe the changes in the interface of CLI command?

**Comment by zhoxing-ms** [comment]
@lorbichara Yes, the `az vmss create` command uses the ARM template to deploy VMSS.
However, I found that when creating VMSS, if the `--vm-sku` is `Standard_D2_v4`, then in the ARM template built by CLI the `storageAccountType` is `null`
```json
"storageProfile": {
    "osDisk": {
        "createOption": "FromImage", 
        "caching": "ReadWrite", 
        "managedDisk": {
            "storageAccountType": null
        }
    }, 
    "imageReference": {
        "publisher": "Canonical", 
        "offer": "UbuntuServer", 
        "sku": "18.04-LTS", 
        "version": "latest"
    }
}
```
But from the response returned by the service, the `storageAccountType` becomes `Standard_LRS`
```
"storageProfile": {
    "imageReference": {
        "offer": "UbuntuServer",
        "publisher": "Canonical",
        "sku": "18.04-LTS",
        "version": "latest"
    },
    "osDisk": {
        "caching": "ReadWrite",
        "createOption": "FromImage",
        "diskSizeGB": 30,
        "managedDisk": {
        "storageAccountType": "Standard_LRS"
        },
        "osType": "Linux"
    }
}
```
**'x-ms-correlation-request-id': '32e3e286-6e9b-40a4-9c16-fb09ffa4dce3'**

So the default value is `Standard_LRS` not from the CLI side, but from the REST service.

**Comment by lorbichara** [comment]
Thanks for pointing this out @zhoxing-ms. I'm checking if it's VMSS team or DiskRP that owns the REST service and will ask them to update. I will close this issue for now, assuming that once they update, no change is needed from CLI side. Thank you!
