### ISSUE TITLE
Document update  for url-path-map create option

### ISSUE THREAD

**Issue by rnautiyal** [Azure/azure-cli#25889]
We have identified the issues with our current document. It needs to be corrected. Document in question -  https://learn.microsoft.com/en-us/cli/azure/network/application-gateway/url-path-map?view=azure-cli-latest 

CLI - az network application-gateway url-path-map create 

We have optional parameters that need to be part of the required field. Details in this document -
https://microsoft-my.sharepoint.com/:w:/p/rnautiyal/EZADAhQMm81KgLKMxrWW8WQB-a9Y96Ok1QHrh5MkDjIeZQ?e=iLGxIX
[AppGW url-path-map document update.docx](https://github.com/Azure/azure-cli/files/11022346/AppGW.url-path-map.document.update.docx)

**Comment by yonzhan** [comment]
@necusjz for awareness

**Comment by necusjz** [comment]
@rnautiyal Is it a breaking change when such optional parameters (--default-address-pool and --default-http-settings) become required?

**Comment by rnautiyal** [comment]
@necusjz  -   There is no impact. Nothing is new. It was a document error that we are correcting now. Please let me know when we can update.  Thanks

**Comment by rnautiyal** [comment]
@necusjz  - Are we on track for 4/4?

**Comment by necusjz** [comment]
@rnautiyal No, since we haven't reached a consensus on "mandatory or not". What's our finial solution now?

**Comment by rnautiyal** [comment]
@necusjz  - This is mandatory. The only time it will not be used is if the target type is redirection.
Update is in document. 
--default-address-pool

Name or ID of the default backend address pool. This is not required if the target type is redirection.   

--default-http-settings

Name or ID of the default HTTP settings. This is not required if the target type is redirection.


https://microsoft-my.sharepoint.com/:w:/p/rnautiyal/EZADAhQMm81KgLKMxrWW8WQB-a9Y96Ok1QHrh5MkDjIeZQ?e=ypch92
