### ISSUE TITLE
'postgres flexible-server upgrade' can't upgrade 'Burstable' instances

### ISSUE THREAD

**Issue by ipg-informatik** [Azure/azure-cli#25886]
**Related command**
`az postgres flexible-server upgrade --subscription mysubscription --resource-group myresourcegroup --name mypostgresql --version 13`

**Describe the bug**
An "Azure Database for PostgreSQL flexible server" upgrade with Standard_B2s sku from v12 to v13 is not possible with azure cli. The upgrade works in the azure portal, but with azure cli there is an error message: "Major version update is not supported for the Burstable pricing tier."

**To Reproduce**
See related command

**Expected behavior**
An upgrade should be possible

**Environment summary**
Azure CLI Version: 2.46.0

**Additional context**
Looks like a similar error: https://github.com/Azure/azure-cli/issues/15387

**Comment by yonzhan** [comment]
route to CXP team

**Comment by mtlljm** [comment]
Is there any progress on this?

**Comment by nachoalonsoportillo** [comment]
@ipg-informatik, @mtlljm Thanks for reporting this issue. The fix is coded now. Once reviewed and merged, it will surface on a future version of Azure CLI.

**Comment by nachoalonsoportillo** [comment]
PR with the fix has been merged now. @yonzhan Please, close this one. Thanks!
