### ISSUE TITLE
appservice: support webapp extensions

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-cli#2590]
Need a az command to install an extension on a webapp. Something like:

```console
az appservice web addextension python353x86
```

and if possible all kudu endpoints about extensions:
```console
az appservice web list_installed_extensions
az appservice web list_available_extensions
az appservice web deleteextension python353x86
```

**Comment by frankfuu** [comment]
Is there a workaround for this at the moment? am i able to use Kudu's REST API to install a site extension say.. [New Relic](https://www.siteextensions.net/packages/NewRelic.Azure.WebSites/)?

I tried to take a dig around the [Kudu docs](https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions) but didn't have much luck.

**Comment by lmazuel** [comment]
The [Kudu RestAPI](https://github.com/projectkudu/kudu/wiki/REST-API) defines the PUT for extensions and I never got an issue with it.

```
PUT /api/siteextensions/{id}
Install or update the package to local machine. The payload is the package info returned by List/Get apis above.
```

So this should work (not tested personally):
```
PUT /api/siteextensions/NewRelic.Azure.WebSites
```

**Comment by frankfuu** [comment]
Thanks @lmazuel will give it a shot

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
