### ISSUE TITLE
'az {item} list --query' fails requiring --resource-group/-g

### ISSUE THREAD

**Issue by mike-wood-dywidag** [Azure/azure-cli#25900]
**Related command**
``` powershell
$eventHubNamespace = az eventhubs namespace list --query "[?tags.environment == 'dev' && tags.service == 'primary']" | ConvertFrom-Json
$hubId = az eventhubs eventhub list --namespace-name $eventHubNamespace.name  -g $eventHubNamespace.resourceGroup --query "[?name == 'example-hub'].id" -otsv
```

also failing

```powershell
$serviceBusNamespace = az servicebus namespace list --query "[?tags.environment == 'dev' && tags.service == 'primary']" | ConvertFrom-Json
$queueId = az servicebus queue show --namespace-name $serviceBusNamespace.name  -g $serviceBusNamespace.resourceGroup --name 'example-queue' --query "id" -otsv 
```
**Describe the bug**
Unable to discover services by tags/query without specifying a resource group which was previously possible. 
Documentation also states `--resource-group/-g` is in "Optional Parameters"

**To Reproduce**
Command works in CLI v2.41.0, upgrading to Azure CLI v2.46.0 causes failure both locally and within Azure Pipelines.

**Expected behavior**
`list --query` works without having to specify `-g` or `--resource-group`

**Environment summary**

Windows 10, MSI install. 
and 
Azure Pipelines Hosted Agent (windows-latest & ubuntu-latest)

**Comment by mike-wood-dywidag** [comment]
possibly linked to #25187

**Comment by mike-wood-dywidag** [comment]
also linked to #25015

**Comment by yonzhan** [comment]
route to CXP team

**Comment by 11qqaazzqwerty** [comment]
Any updates? Will it be fixed?

**Comment by Saglodha** [comment]
Hi @mike-wood-dywidag , we are currently working on the fix for the above issue : https://github.com/Azure/azure-cli/pull/26513,  I would keep you posted about the progress.
