### ISSUE TITLE
az login failed with CERTIFICATE_VERIFY_FAILED but not behind a proxy environment

### ISSUE THREAD

**Issue by paulliu10** [Azure/azure-cli#25906]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az login

**Describe the bug**

HTTPSConnectionPool(host='login.chinacloudapi.cn', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle. More info: https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy

**To Reproduce**

az login

**Expected behavior**

Please help to resolve the issue "az login failed in azure china environment"

**Environment summary**

Install Method (MSI) / CLI version (`2.46.0`）/Windows 10 enterprise 20h2 / Shell Type (cmd.exe)

**Additional context**

refer to https://github.com/Azure/azure-cli/issues/20921 have run "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -m pip install pip-system-certs" but it doesn't solve the problem.
![23322cliloginerror1](https://user-images.githubusercontent.com/32628891/226789170-7b9eb566-5a8a-4faf-9fd3-f9b907c637dd.png)

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by paulliu10** [comment]
Hi,

Are there any suggestions or solutions for login errors?

Thank you!

**Comment by bebound** [comment]
Apparently, you're behind a proxy. Please check this doc: https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#work-behind-a-proxy
