### ISSUE TITLE
Parameter limitation/requirements in documentation

### ISSUE THREAD

**Issue by dotdash-ben** [Azure/azure-cli#25918]
It'd be nice if documentation also included the limitations/requirements of the parameters, e.g.: the name of the web app has the following limitations (according to the CLI):

"Site names only allow alphanumeric characters and hyphens, cannot start or end in a hyphen, and must be less than 64 chars."

But this is not provided in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://learn.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
route to CXP team

**Comment by navba-MSFT** [comment]
@dotdash-ben Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@dotdash-ben Thanks for sharing your feedback on improving our documentation.  The above PR has been filed. It is currently pending under review.
