### ISSUE TITLE
Cryptography Package S360 Security Vulnerability

### ISSUE THREAD

**Issue by ronitshaw1993** [Azure/azure-cli#25913]
The cryptography package installed by Azure CLI is getting flagged for security vulnerabilities. 

![image](https://user-images.githubusercontent.com/126830425/227035171-d78c2839-4044-41a3-9ace-f55998b79cab.png)

Any leads on when the next release is scheduled with the latest/above fix? 

This is similar to the earlier issue I filed: https://github.com/Azure/azure-cli/issues/25682
Do I need to apply a similar fix here? Would do so if the next release is a little far ahead or the next release wouldn't contain the fix

**Comment by yonzhan** [comment]
@bebound for awareness

**Comment by bebound** [comment]
Cryptography is reverted to 38.0.4. Please see the explanation in https://github.com/Azure/azure-cli/pull/25690
Before updating cryptography, we need to use 64bit Python on Windows, which may take some time.

You can update build-in package with `PYTHONPATH="/lib64/az/lib/python3.9/site-packages" python3.9 -m pip install -U xxxx`

**Comment by ronitshaw1993** [comment]
So updating Cryptography using the above method when building a container out of a Mariner-based base image should be fine correct?

**Comment by bebound** [comment]
Yes.

**Comment by jwstein3400** [comment]
@yonzhan What is the confidence that this will be delivered tomorrow with release as part of Azure CLI 2.48?

**Comment by bebound** [comment]
This won't happen in 2.48.
We'll update cryptography with the release of windows 64-bit version.
