### ISSUE TITLE
mobil-network: Wrong site create command in the Examples

### ISSUE THREAD

**Issue by rafaeldnferreira** [Azure/azure-cli#25919]
Hello there's a wrong command in the site create example, it is using the mobile-network and not the site. It should be like:

az mobile-network site create // parameters for site

instead of az mobile-network create // parameters for mobile network

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4005bf-aa67-916e-8f35-9518f5e26fbb
* Version Independent ID: ecc1156c-b2ca-31c3-0d31-6a7b66c51e79
* Content: [az mobile-network site](https://learn.microsoft.com/en-us/cli/azure/mobile-network/site?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/mobile-network/site.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/mobile-network/site.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by jsntcy** [comment]
@Jing-song could you please help fix the example?
