### ISSUE TITLE
Installing Bicep in Windows Sandbox WM

### ISSUE THREAD

**Issue by ugreg** [Azure/azure-cli#25924]
I am trying to install Bicep in my Windows Sandbox VM. First I used `winget install -e --id Microsoft.AzureCLI` and then run `az bicep install`.

![image](https://user-images.githubusercontent.com/8151045/227422058-80f26e9c-d7ee-4d90-bccd-04875e8cbb03.png)

I get the following error and ensure what this means or how to resolve.

![image](https://user-images.githubusercontent.com/8151045/227422046-0358fc38-a165-4bfa-8cba-9d883d753522.png)

**Comment by yonzhan** [comment]
route to CXP team

**Comment by PramodValavala-MSFT** [comment]
@ugreg Apologies for the inconvenience! This is being tracked [here](https://github.com/Azure/azure-cli/issues/25710). Closing this in favor of that.

Currently, the workaround is to either

- Use Azure CLI 2.45.0
- Run this command first
   ```sh
   az config set bicep.use_binary_from_path=false
   ```
