### ISSUE TITLE
The 'az keyvault list' command defaults to resourceType = ManagedHSM

### ISSUE THREAD

**Issue by FabianGonzalez-MSFT** [Azure/azure-cli#25933]
The [az keyvault list ](https://learn.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az-keyvault-list) command defaults to resourceType = Microsoft.KeyVault/Managedhsm when it should be to Microsoft.KeyVault/Vaults by default and then if the customer wants to list Managed HSM resources they may specify it through the '--resource-type' parameter.

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
@FabianGonzalez-MSFT The default behavior is to list both vaults and managed HSMs. If customers want to list specific type, they can use `--resource-type`

**Comment by FabianGonzalez-MSFT** [comment]
@evelyn-ys Please give it a try, when you try the command without the '--resource-type' parameter, it calls ManagedHSMs. It can be observed with the --debug' flag.

**Comment by evelyn-ys** [comment]
Yes it calls MangedHSMs, but that's not the only service it calls. It actually requests both vaults list and HSM list, what you notices from debug is the second call.
See my sample result:
![image](https://user-images.githubusercontent.com/10227683/227854061-f0c01448-f561-4d09-85f0-a371da127cc5.png)
