### ISSUE TITLE
az monitor metrics alert list command does on show alerts with invalid actiongroup and invalid scope

### ISSUE THREAD

**Issue by raghava28041978** [Azure/azure-cli#25947]
[The az monitor metrics alert list command does not display all the alerts that are configured in Azure portal. For example, if the alerts scope has changed or if the Actiongroup no longer exists, then such alerts are not displayed by the command. Kindly look in to it.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d97968df-72c9-e50c-d5b1-54562c1bdef7
* Version Independent ID: 0cde4f15-6464-3106-b787-3ee37c7de0ee
* Content: [az monitor metrics alert](https://learn.microsoft.com/en-us/cli/azure/monitor/metrics/alert?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/monitor/metrics/alert.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/monitor/metrics/alert.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@AllyW for awareness

**Comment by AllyW** [comment]
@raghava28041978 `az monitor metrics alert list` is used to list all the metric-based alert rules. If `--resource-group` is provided, it lists the alert rule of this resource group. If no info is provided, then it will list all the alert for current subscription. If scope is changed or action group is removed, please check if the alert rules still exist or are they removed already.

**Comment by raghava28041978** [comment]
Hi Ally,

Those alerts were created on subscription level and obviously part of a resource group. All alerts got displayed except the ones with scoping or action group missing ones.

**Comment by AllyW** [comment]
hi @raghava28041978 `az monitor metrics alert list` fetches alert info either by `resource-group` or by `subscription`. No other parameters are passed into the service side. Users can add `--debug` to find how this cmd works.

**Comment by raghava28041978** [comment]
Hi Ally,

If no resource group parameter is passed, the expectation is that the command should list all the alerts irrespective of the resource group membership. I will run with debug parameter and check.

**Comment by raghava28041978** [comment]
Thanks for considering my input!
