### ISSUE TITLE
Error upgrading k8s from 1.22.6 to 1.23.12 - 'UserAssigned' is not valid value for enum <enum 'ResourceIdentityType'>

### ISSUE THREAD

**Issue by ccastillo232** [Azure/azure-cli#25950]
## Describe the bug

**Command Name**
`az aks upgrade`

**Errors:**
```
'UserAssigned' is not valid value for enum <enum 'ResourceIdentityType'>
ValueError: 'UserAssigned' is not a valid ResourceIdentityType

...

python3/dist-packages/msrest/serialization.py, ln 917, in serialize_enum
    raise SerializationError(error.format(attr, enum_obj))
msrest.exceptions.SerializationError: 'UserAssigned' is not valid value for enum <enum 'ResourceIdentityType'>
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks upgrade --resource-group {} --name {} --kubernetes-version {}`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29
Python 3.8.2
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by navba-MSFT** [comment]
@ccastillo232 Thanks for reaching out to us and reporting this issue. Could you please follow the suggestions provided [here ](https://github.com/Azure/azure-cli/issues/25950#issuecomment-1485715199)?
