### ISSUE TITLE
azure-cli-2.46.0.msi and bicep-setup-win-x64.exe already installed, run the command: az bicep install failed

### ISSUE THREAD

**Issue by a314159kelly199835** [Azure/azure-cli#25952]
Here is the error messages:

Installing Bicep CLI v0.15.31...
The command failed with an unexpected error. Here is the traceback:
No section: 'bicep'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3648, in install_bicep_cli
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 141, in ensure_bicep_installation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 99, in get
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 94, in get
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 208, in get
  File "configparser.py", line 783, in get
  File "configparser.py", line 1154, in _unify_values
configparser.NoSectionError: No section: 'bicep'

## Describe the bug

**Command Name**
`az bicep install`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az bicep install`

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.46.0
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by a314159kelly199835** [comment]
![vscode_bugs](https://user-images.githubusercontent.com/129051565/228114012-4530951c-5a68-4541-8076-3d6398b7cf59.JPG)

**Comment by navba-MSFT** [comment]
@a314159kelly199835 Thanks for reaching out to us and reporting this issue. Could you please install the bicep using[ windows installer ](https://github.com/Azure/bicep/releases/latest/download/bicep-setup-win-x64.exe)and check if that helps ?

After the installation, Bicep CLI is added to your user PATH. Close and reopen any open command shell windows for the PATH change to take effect.

If you want to **Manually Install with Powershell** follow the below steps:

```
# Create the install folder
$installPath = "$env:USERPROFILE\.bicep"
$installDir = New-Item -ItemType Directory -Path $installPath -Force
$installDir.Attributes += 'Hidden'
# Fetch the latest Bicep CLI binary
(New-Object Net.WebClient).DownloadFile("https://github.com/Azure/bicep/releases/latest/download/bicep-win-x64.exe", "$installPath\bicep.exe")
# Add bicep to your PATH
$currentPath = (Get-Item -path "HKCU:\Environment" ).GetValue('Path', '', 'DoNotExpandEnvironmentNames')
if (-not $currentPath.Contains("%USERPROFILE%\.bicep")) { setx PATH ($currentPath + ";%USERPROFILE%\.bicep") }
if (-not $env:path.Contains($installPath)) { $env:path += ";$installPath" }
# Verify you can now access the 'bicep' command.
bicep --help
# Done!
```


Alternatively you could also follow the below manual steps:

- Download bicep-win-x64.exe from the [Bicep release page](https://github.com/Azure/bicep/releases/latest/).

- Copy the executable to the %UserProfile%/.azure/bin directory. Rename file to bicep.exe.

- Add the PATh to the enviornment variable. Close your CMD prompt / PS window and launch it again and test.

**Comment by navba-MSFT** [comment]
@a314159kelly199835  Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by a314159kelly199835** [comment]
Hi,

Thank you for replying. I used windows installer yesterday.  I clicked the hyper link you provided and proved that the windows installer is the same as I installed one. Then I still went through the install process one more time, and still got the same error in VS code…
***@***.***

**Comment by navba-MSFT** [comment]
@a314159kelly199835 Thanks for getting back. I am discussing this internally and I will get back to you with an update.

**Comment by a314159kelly199835** [comment]
Dear,

Do I need to edit the environment PATH? If so, I didn’t do that.
I thought when installing on clicking Next, system would add the PATH to environment automatically.

After I add bicep.exe to the PATH, it works for CMD. While in VS Code virtual environment, it doesn’t work…
When it comes to PATH environment, did I add it correctly?
***@***.***

***@***.***


***@***.***

Thank you!
Best regards,
Kelly

**Comment by navba-MSFT** [comment]
@a314159kelly199835 Thanks for your reply. Could you please follow the below steps and let me know if that helps ?

1. Close all instances of VS code.
2. Reluanch the VS code.
3. Open a New terminal and launch the cmd prompt (instaed of powershell) as shown below:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/57353862/228460313-192ed6e9-3615-4870-99dc-d938ad6d4b2b.png">

4. After you open the cmd prompt in VS code then you can try running the `bicep --version `command and check if that helps ?

<img width="593" alt="image" src="https://user-images.githubusercontent.com/57353862/228475353-870bee1b-2e24-4b33-b982-0fc58ada6e87.png">

**Comment by a314159kelly199835** [comment]
Hi,

I follow your instruction:

  1.  Close all the VS Code windows.
  2.  Open the bicep repository in VS Code
  3.  Switch from power shell to CMD and type the command ***@***.***

Do that mean I could only use bicep in the path of C:\Users\kelly , not in any of other path?

Thank you for the reply!
Have a good day.
Kelly

**Comment by navba-MSFT** [comment]
@a314159kelly199835 You can use it from any other path too, since it has been added as an environment variable. 

So could you please confirm if it worked fine while you accessed it from the _cmd bash in VS code ?_

**Comment by navba-MSFT** [comment]
@a314159kelly199835 If you are still getting **`configparser.NoSectionError: No section: 'bicep'`** error then this is a known issue and it is fixed as a part of
PR [#25729](https://github.com/Azure/azure-cli/pull/25729) . The fix should be released in 4/4/2023 AzCLI release as a part of this milestone: https://github.com/Azure/azure-cli/milestone/128

**Comment by a314159kelly199835** [comment]
Hi,
I did try that. (change VS code terminal to bash) Have you seen that email? If not, please see the attached email which recorded how I did

Did I try it correctly?
Still don’t know why there are so many errors……

Or do I need to do another confirm?
I’m new to bicep so I have little knowledge about it…
Thank you for your patient.
Kelly

**Comment by navba-MSFT** [comment]
@a314159kelly199835 I didn't see any attachment here. Could you please attach it here in GitHub instead of sending it over email. Please share the error details you are observing now via BASH cmd prompt.

**Comment by navba-MSFT** [comment]
@a314159kelly199835 Could you please share the error details here in GitHub for the errors you are observing while accessing from cmd prompt ?

**Comment by a314159kelly199835** [comment]
The original message in 29th March mail sent to you is like this:
I follow your instruction:
1.	Close all the VS Code windows.
2.	Open the bicep repository in VS Code
3.	Switch from power shell to CMD and type the command, but still got the error. 
![bicep](https://user-images.githubusercontent.com/129051565/230254252-633de803-d7c9-4bd7-bba3-a4ce6fe73ec4.JPG)

After I went back for the long break, I thied to represent the error and paste the error in GitHub instead of mail, and found it has been OK now!
So you could close the case. Thank you very much!

**Comment by navba-MSFT** [comment]
@a314159kelly199835 Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
