### ISSUE TITLE
Max retries exceeded error while runnig "az aks get-credentials"

### ISSUE THREAD

**Issue by saggy6210** [Azure/azure-cli#25961]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /31c9411c-7391-4f8f-ae11-4e429f1be2dd/v2.0/.well-known/openid-configuration (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {} --subscription {} --overwrite --file {}`

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.41.0

Extensions:
image-copy-extension 0.2.11
azure-batch-cli-extensions 7.0.0

Dependencies:
msal 1.20.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
route to CXP team

**Comment by SaurabhSharma-MSFT** [comment]
@saggy6210 I am unable to reproduce this issue.  Please Try running the `az aks get-credentials` command with the `--admin` flag.
If this doesn't work, then try to upgrade your Azure CLI version.

**Comment by SaurabhSharma-MSFT** [comment]
@saggy6210 Please let us know if you are still having issues.
