### ISSUE TITLE
Incorporate Network Watcher functionality.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-cli#2596]
Implement command for the Network RP "network watcher" resource type described in:
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-09-01/swagger/networkWatcher.json

- [x] CRUD commands
- [x] Configure NSG flow logging
- [x] Show next hop (Get-AzureRmNetworkWatcherNextHop)
- [x] Show topology (Get-AzureRmNetworkWatcherTopology)
- [x] Show troubleshooting (Start-AzureRmNetworkWatcherResourceTroubleshooting)
- [x] Show troubleshooting result
- [x] Show VM security rules
- [x] Verify IP flow (Test-AzureRmNetworkWatcherIPFlow)

Other PS cmdlets that don't have an obvious analogue:

    New-AzureRmPacketCaptureFilterConfig

    New-AzureRmNetworkWatcherPacketCapture
    Get-AzureRmNetworkWatcherPacketCapture
    Remove-AzureRmNetworkWatcherPacketCapture
    Stop-AzureRmNetworkWatcherPacketCapture

    Get-AzureRmNetworkWatcherSecurityGroupView

**Comment by mayurid** [comment]
@tjprescott to look at it
