### ISSUE TITLE
Azure CLI stops working after an hour but runs fine before that

### ISSUE THREAD

**Issue by pshuk256** [Azure/azure-cli#25977]
Hi,

I am facing this strange issue. I have this script that recursively runs az storage blob list because I want to search through entire container and filter out the blobs matching certain criterion (that I defined in my script). It runs fine and produces output until a certain point (I am doing it in chunk of 4000 results, so after every run, it generates nextMarker, which I use to run my next search). After a certain number of runs, it just stops working. I have stored all the nextMarkers and Azure somehow remembers which nextMarker it has to stop and it does that every single time. Can anyone help me to resolve the issue or a way to overcome the problem? 
Here is the script that I use to run recursively my Azure CLI script:
`#/usr/bin/

./Azure_Search_Q.sh > out

tail -1 out
line=$(tail -1 out);
echo "Length is:${#line}"
expr=${line:4:${#line}}
echo $expr

head -n -1 out >Joint_Folder_Files
while [ ! -z "$expr" ]
do
        sed "s/FLAG/${expr}/g" Azure_listBlob_wMarker_FLAG.sh > Azure_Search_newQ.sh
        chmod +x Azure_Search_newQ.sh
        ./Azure_Search_newQ.sh > out
        head -n -1 out >>Joint_Folder_Files
        line=$(tail -1 out)
        echo "Length is:${#line}"
        expr=${line:4:${#line}}
        echo $expr
done
`
here is the Azure CLI script (Azure_Search_Q.sh):
`#/usr/bin

key="******"
account_name=***
container_name=***
numResults=400
az storage blob list \
       --account-name $account_name \
       --account-key $key \
       --show-next-marker \
       --container-name $container_name \
       --prefix "Analysis/joint_analysis/" \
       --num-results $numResults \
       --query "[[].name | [?((ends_with(@, 'vcf.gz')) && (contains(@, '962756'))&& (contains(@, 'hard-filtered.')))], [].nextMarker]" --output yamlc
`
and here is the other one: Azure_listBlob_wMarker_FLAG.sh:
`#/usr/bin

key="*****"
account_name=****
container_name=***
numResults=400
marker=FLAG
az storage blob list \
       --account-name $account_name \
       --account-key $key \
       --num-results $numResults \
       --show-next-marker \
       --container-name $container_name \
       --prefix "Analysis/joint_analysis/" \
       --marker $marker \
       --query "[[].name | [?((ends_with(@, 'vcf.gz')) && (contains(@, '962756'))&& (contains(@, 'hard-filtered.')))], [].nextMarker]" --output yamlc
`

**Comment by yonzhan** [comment]
@evelyn-ys for awareness

**Comment by evelyn-ys** [comment]
It could be related with this fix https://github.com/Azure/azure-cli/pull/25915

And the fix will be released on 4/6
