### ISSUE TITLE
input from stdin, batch of commands

### ISSUE THREAD

**Issue by fanoush** [Azure/azure-cli#2597]
could be useful to accept command  from standard input and run more commands in one az command

echo "vm list" | az
cat batch.txt | az

or even internal repl loop
$ az
> vm list
...
>vm start

**Comment by tjprescott** [comment]
You should be able to use the @file syntax to accomplish some of these. Use @~ to load from stdin.

**Comment by fanoush** [comment]
thanks but both are not working - ubuntu 14.04, azure-cli (2.0.0)

~$ echo vm list --output table >azinput.txt
~$ az @azinput.txt
az: error: argument _command_package: invalid choice: u'vm list --output table' (choose from 'sql', 'redis', 'batch', 'network', 'iot', 'account', 'group', 'appservice', 'documentdb', 'resource', 'storage', 'vm', 'feature', 'snapshot', 'cloud', 'vmss', 'policy', 'keyvault', 'logout', 'container', 'role', 'acs', 'feedback', 'ad', 'provider', 'disk', 'component', 'lock', 'configure', 'tag', 'image', 'login')
usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {sql,redis,batch,network,iot,account,group,appservice,documentdb,resource,storage,vm,feature,snapshot,cloud,vmss,policy,keyvault,logout,container,role,acs,feedback,ad,provider,disk,component,lock,configure,tag,image,login}

~$ echo vm list --output table | az @~
[Errno 21] Is a directory: '/home/user'
Traceback (most recent call last):
  File "/home/user/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/user/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 90, in execute
    argv = Application._expand_file_prefixed_files(unexpanded_argv)
  File "/home/user/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 242, in _expand_file_prefixed_files
    return list([Application._expand_file_prefix(arg) for arg in argv])
  File "/home/user/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 238, in _expand_file_prefix
    return Application._maybe_load_file(arg_split[0])
  File "/home/user/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 228, in _maybe_load_file
    return Application._load_file(poss_file)
  File "/home/user/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 250, in _load_file
    allow_binary=True)
  File "/home/user/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/_util.py", line 117, in read_file_content
    with codecs_open(file_path, encoding=encoding) as f:
  File "/home/user/lib/azure-cli/lib/python2.7/codecs.py", line 878, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 21] Is a directory: '/home/user'

**Comment by fanoush** [comment]
the interactivity part is now solved by az-shell which is now integrated into 'az interactive' command.  The input from standard input or file still does not work, just tried azure cloud shell in portal

f@Azure:~$ echo vm list >file
f@Azure:~$ echo vm list | az @file
az: error: argument _command_package: invalid choice: vm list
usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {keyvault,image,account,postgres,feedback,functionapp,cloud,acr,network,configure,resource,cognitiveservices,monitor,cdn,group,component,storage,managedapp,find,iot,batch,mysql
,vm,interactive,login,disk,ad,webapp,cosmosdb,sf,redis,feature,policy,acs,snapshot,logout,provider,lab,sql,dls,appservice,lock,vmss,tag,role,dla}
          ...

**Comment by tjprescott** [comment]
Related to #1398.  Also, the syntax should be `az --blah @-` not ~, but I have confirmed that this isn't working currently.

**Comment by tjprescott** [comment]
While piping an id list specifically is not supported, the @- syntax to pipe from STDIN is working as intended.
