### ISSUE TITLE
'az account set' does not work

### ISSUE THREAD

**Issue by FedorRomanov** [Azure/azure-cli#2598]
# 'az account set' does not work on macOs Sierra 10.12.3
install latest version Azure CLI 2.0
```
bash-3.2$ az --version
azure-cli (2.0.1)
```
Do not install Azure CLI 1, i.e. `azure` command must not be available
login with 
`bash-3.2$ az login`
Let's say you have two accounts/subscriptions:
`bash-3.2$ az account list`
```
[
  {
    "cloudName": "AzureCloud",
    "isDefault": true,
    "name": "Name 1",
    "registeredProviders": [],
    "state": "Enabled",
    "tenantId": "374f8....d",
    "user": {
      "name": "user.name@company.com",
      "type": "user"
    }
  },
  {
    "cloudName": "AzureCloud",
    "id": "4...e2",
    "isDefault": false,
    "name": "Name 2",
    "registeredProviders": [],
    "state": "Enabled",
    "tenantId": "3...d",
    "user": {
      "name": "user.name@company.com",
      "type": "user"
    }
  }
]
```
try to perform any command,e.g. 
`bash-3.2$az vm list -g 'Name 2'`
it fails with 

> please run 'az account set' to select active account

run 
`bash-3.2$ az account set --subscription 'Name 2'`
it exits silently
repeat original command, it still fails with the same error message
`bash-3.2$az vm list -g 'Name 2'`
`please run 'az account set' to select active account`

> 

UPDATE: installing Azure CLI 1.0 and logging with it
`azure login`
fixes the issue

**Comment by yugangw-msft** [comment]
I can't reproduce it. @FedorRomanov , are you using the latest CLI? 
After `az account set`, could you run the `az account list` to see whether `isDefault` is flipped?

**Comment by FedorRomanov** [comment]
I have updated description with az version(it is `2.0.1`)

running `az account set` has absolutely no effect on output of `az account list`

**Comment by yugangw-msft** [comment]
@FedorRomanov, I had no luck to reproduce it. I removed CLI 1.0, did `account clear` to start from scratch and then login with an account which has 7 subscriptions. Switching among them worked fine.
For cross check, in your repro I saw the `Name 1` entry has no `id` field. Was that the real data? 

Also for reference, below are the commands I tried
```bash
(env27) admins-MacBook-Pro-2:azure-cli admin$ az account list --query "[].name"
[
  "AzureSDKADGraph2",
  "Visual Studio Ultimate with MSDN",
  "node",
  "Node CLI Test",
  "Azure SDK Infrastructure",
  "Azure SDK Powershell Test",
  "Azure SDK sandbox",
  "Azure CLI Demo with TTL = 2 days",
  "Visual Studio - Data Catalog",
  "Ticino Telemetry Subscription",
  "DevDiv Key Vault"
]
(env27) admins-MacBook-Pro-2:azure-cli admin$ az account set --subscription 'Node CLI Test'
(env27) admins-MacBook-Pro-2:azure-cli admin$ az vm list --query "length([])"
0
(env27) admins-MacBook-Pro-2:azure-cli admin$ az account set --subscription 'Node'
(env27) admins-MacBook-Pro-2:azure-cli admin$ az vm list --query "length([])"
0
(env27) admins-MacBook-Pro-2:azure-cli admin$ az account set --subscription 'AzureSDKADGraph2'
(env27) admins-MacBook-Pro-2:azure-cli admin$ az vm list --query "length([])"
5
(env27) admins-MacBook-Pro-2:azure-cli admin$ 

```

**Comment by yugangw-msft** [comment]
Please reactivate when you have a repro
