### ISSUE TITLE
List Direct Shared GalleryImageVersions not handling paging 

### ISSUE THREAD

**Issue by jerryc3** [Azure/azure-cli#25980]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az sig image-definition list-shared \
   --gallery-unique-name "d31a15c2-01ba-4985-ad28-65581c070a80-DEVSECOPS_GALLERY" \
   --location westeurope \
   --shared-to tenant \
   --query "[].{Name:name,ID:uniqueId,OS:osType,State:osState}" \
   --output table    

**Describe the bug**

Only 50 entities returned when there are actually more being returned (backend returns a skipToken to the next page of results)

**To Reproduce**

Direct shared gallery image definition with more than 50 versions.

**Expected behavior**

CLI should handle the paged response and return all versions via CLI compliant manner.

**Environment summary**

**Additional context**

ICM https://portal.microsofticm.com/imp/v3/incidents/details/367589416/home

**Comment by yonzhan** [comment]
@zhoxing-ms for awareness

**Comment by zhoxing-ms** [comment]
@jerryc3 In fact, the `az sig image-definition list-shared` command already supports paging. Please use the `--show-next-marker` parameter to obtain the paging marker (it is called `nextLink` on the server side), and then use the `--marker` parameter to pass in the paging marker when requesting the next page

**Comment by sandeepraichura** [comment]
Hey @zhoxing-ms - Looks like this is not working as expected and the customer reported this following error.  Is this a CLI versioning issue ?

bash-3.2$ az sig image-definition list-community --public-gallery-name DEVSECOPS_GALLERY --location westeurope --marker [https://management.azure.com:443/Subscriptions/d31a15c2-01ba-4985-ad28-65581c070a80](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmanagement.azure.com%2FSubscriptions%2Fd31a15c2-01ba-4985-ad28-65581c070a80&data=05%7C01%7Cazeddine.tarifet%40microsoft.com%7C8a67bccfbe41462937d808db188e28e5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638130771132772578%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0ul%2F3Bp7m85f5wiYaj7ufz%2BUkGFPZAKZ0YLCtfBi5wM%3D&reserved=0)

 

(InvalidApiVersionParameter) The api-version '2022-03-03' is invalid. The supported versions are '2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

Code: InvalidApiVersionParameter

Message: The api-version '2022-03-03' is invalid. The supported versions are '2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

**Comment by zhoxing-ms** [comment]
@sandeepraichura Could you please send the debug log *(add `--debug` parameter)* to me by email? My email address is Zhou.Xing@microsoft.com, thanks~

**Comment by sandeepraichura** [comment]
Reopening as the issue is not resolved

**Comment by zhoxing-ms** [comment]
@sandeepraichura May I ask why the REST prefix is added to the parameter `--marker`? The `--marker` parameter should only need to be passed in as `skiptoken`
