### ISSUE TITLE
az container logs returns an internal server error

### ISSUE THREAD

**Issue by JesseDeH** [Azure/azure-cli#25996]
## Describe the bug

When running the command `az container logs` for a container instance running a custom image, it returns an internal server error. The command `az container attach` returns the same error. 
The container is running properly and is reachable via it's ip address. I can also use ssh to connect to the container without issue.

**Command Name**
`az container logs`

**Errors:**
```
cli.azure.cli.core.azclierror: (InternalServerError) Encountered an internal server error. The tracking activity id is '1e7e94e6-a1d3-49eb-9dbf-7d11c7a6243e', correlation id is 'd5f7a7e5-bf12-489f-86aa-1ba3f6ee211d'.
Code: InternalServerError
Message: Encountered an internal server error. The tracking activity id is '1e7e94e6-a1d3-49eb-9dbf-7d11c7a6243e', correlation id is 'd5f7a7e5-bf12-489f-86aa-1ba3f6ee211d'.

az_command_data_logger: (InternalServerError) Encountered an internal server error. The tracking activity id is '1e7e94e6-a1d3-49eb-9dbf-7d11c7a6243e', correlation id is 'd5f7a7e5-bf12-489f-86aa-1ba3f6ee211d'.
Code: InternalServerError
Message: Encountered an internal server error. The tracking activity id is '1e7e94e6-a1d3-49eb-9dbf-7d11c7a6243e', correlation id is 'd5f7a7e5-bf12-489f-86aa-1ba3f6ee211d'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az container logs --name {} --resource-group {} --debug`

## Expected Behavior

Return the logs of the container.

## Environment Summary
```
Linux-5.4.0-1105-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.46.0

Extensions:
ai-examples 0.2.5
ml 2.14.1
ssh 1.1.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@JesseDeH I am not able to reproduce this issue and `az container logs` returns logs correctly.  If you are still having this problem, then please open a [Azure Support Ticket](https://aka.ms/azsupt) so that an engineer can further look into backend logs to identify the root cause.

**Comment by SaurabhSharma-MSFT** [comment]
@JesseDeH Please let me know if you have any other questions.

**Comment by JesseDeH** [comment]
We have moved away from using Container Instances in favor of Container Apps, so I am unfortunately not able to reproduce this issue now. Closing the ticket.

Thanks for looking into this.
