### ISSUE TITLE
Dedicated Host Resize Feature

### ISSUE THREAD

**Issue by cakarata** [Azure/azure-cli#25999]
### Related command

az vm host resize
az vm host list-host-resize-options

### Resource Provider

Microsoft.Compute/CRP

### Description of Feature or Work Requested

As CRP, we are adding a new feature called host resize. The Customers will make az vm host list-host-resize-options to get possible resize options and resize their dedicated host to. 

### Minimum API Version Required

2023-03-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/23268
https://github.com/Azure/azure-sdk-for-net/pull/35197

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/feature/cplat-2023-03-01/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-03-01/examples/dedicatedHostExamples/DedicatedHost_Update_Resize.json
https://github.com/Azure/azure-rest-api-specs/blob/feature/cplat-2023-03-01/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-03-01/examples/dedicatedHostExamples/DedicatedHost_ListAvailableSizes.json

### Target Date

2023-04-05

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
> Target Date
2023-04-05

@cakarata As we usually need to communicate and plan feature requests about a month in advance, the submission of this requirement is late. Currently, we can only release it on `04-25` as the earliest time. Does this date meet your expectations?

**Comment by cakarata** [comment]
> > Target Date
> > 2023-04-05
> 
> @cakarata As we usually need to communicate and plan feature requests about a month in advance, the submission of this requirement was late. Currently, we can only release this feature on `04-25` as the earliest time, does this date meet your expectations?

@zhoxing-ms it should work. Thank you.

**Comment by yanzhudd** [comment]
Hi @cakarata 
we noticed the swagger currently is not in the main branch (https://github.com/Azure/azure-rest-api-specs/pull/23268). It is suggested being merged into the main branch to having this feature released in CLI main repo.

**Comment by cakarata** [comment]
@yanzhudd The swagger is approved for the feature branch. @grizzlytheodore can you please help.

**Comment by yanzhudd** [comment]
Hi @cakarata, when we try to resize dedicated host, an errror is reported. Could you please help to take a look?
![image](https://user-images.githubusercontent.com/105691024/230839662-27c7d1bf-ee36-446b-b318-d3d5ee7cb2ab.png)

**Comment by cakarata** [comment]
That's because the feature is currently behind a feature flag. We are in the progress of making it publicly available. If you can share your subId and the region you are trying we can enable it.

**Comment by yanzhudd** [comment]
Hi @cakarata,
our subId is '0b1f6471-1bf0-4dda-aec3-cb9272f09590'. 
Thanks.
