### ISSUE TITLE
Add support for Azure workbooks in Az CLI 

### ISSUE THREAD

**Issue by syedhamjath** [Azure/azure-cli#25994]
Request to add support for Azure workbooks in Az CLI

**Related command**
az monitor workbook 

**Is your feature request related to a problem? Please describe.**
No, it's a new set of sub verbs.

**Describe the solution you'd like**
The idea is have CURD operation for Azure workbook in Az CLI.

az monitor workbook create/update/remove/list

**Describe alternatives you've considered**
The alternate option is to use REST API or ARM or bicep template.

**Additional context**
N/A

**Comment by AllyW** [comment]
Hi @syedhamjath  about adding the `workbooks` sub verb, can you provide the swagger file or the resource provider for development planning?

**Comment by syedhamjath** [comment]
Hi @AllyW, The resource provider for workbook is Microsoft.Insights. The Azure workbook rest API deatils are available in this link : https://learn.microsoft.com/en-us/rest/api/application-insights/workbooks

**Comment by syedhamjath** [comment]
@AllyW Is this [swagger json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2023-06-01/workbooks_API.json) helpful?

**Comment by AllyW** [comment]
@syedhamjath  thanks, we will process it in following sprint.
