### ISSUE TITLE
az storage container-rm update --default-encryption-scope

### ISSUE THREAD

**Issue by stevenyberg** [Azure/azure-cli#25998]
I would like to use container-rm update to change the defaultEncryptionScope of an existing storage account container.
The documentation says:
Update the default encryption scope for a container by resource id.
az storage container-rm update --ids mycontainerid --default-encryption-scope myencryptionscope

When I attempt this via Azure CLI, for an existing container that currently has either the default scope $account-encryption-key or a different custom scope, the attempt does not stick. The response is a 200, and the response json shows the defaultEncryptionScope is my intended new value. I have tried both using the correct --ids value, and tried using --storage-account --name parameters. The new scope is valid.
However, in Azure Portal, after refreshing, I do not see it actually changed.
If there is a specific preview feature I need to register to get this to persist the update, could someone share that? I did search preview features from Azure portal and from the Get features call and could not determine what preview may be required. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bab3ae5-cdc8-713b-6edb-68aa043513f3
* Version Independent ID: 85df2665-02da-b6fd-4d77-0d02e767fc73
* Content: [az storage container-rm](https://learn.microsoft.com/en-us/cli/azure/storage/container-rm?view=azure-cli-latest#az-storage-container-rm-update)
* Content Source: [latest/docs-ref-autogen/storage/container-rm.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/container-rm.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by stevenyberg** [comment]
A separate Microsoft Tracking ID was created for this issue, it is still under investigation

**Comment by stevenyberg** [comment]
Tracking Id was closed. Encryption scope update for an existing container will not be supported. Microsoft should update their documentation so it does not suggest that it is supported.
