### ISSUE TITLE
Adding support for Log Scrubbing in Application Gateway Web application Firewall

### ISSUE THREAD

**Issue by rravishankar2** [Azure/azure-cli#26002]
### Resource Provider

Network (NRP)

### Description of Feature or Work Requested

We are adding support for customers to be able to scrub sensitive fields from Application Gateway Firewall Logs. For example, if a header exists with a key 'password' and the customer wants to scrub a request header with a key 'password', the value of 'password' is replaced with a specific string.

If the user does not configure a rule or if the log scrubbing config is disabled, the logs are not scrubbed. 

Link to the design document

https://microsoft.sharepoint.com/:w:/r/teams/ApplicationGateway9/Shared%20Documents/WAF/Documents/Scrubbing%20Sensitive%20Fields/Scrubbing%20Sensitive%20Fields%20Design%20doc.docx?d=wa8b6d7508ce84b049829efe024456249&csf=1&web=1&e=Tqh4yt

### Minimum API Version Required

2022-11-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/23022

### Target Date

2023-05-01

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by rravishankar2** [comment]
I am not sure why it shows that it is a customer reported request, however, it is an internal request

**Comment by necusjz** [comment]
> I am not sure why it shows that it is a customer reported request, however, it is an internal request

It doesn't matter. But, please give us the permission of the above design doc, we'll estimate it better and consider which milestone to plan it based on our current workload.

**Comment by necusjz** [comment]
@rravishankar2 Could you set it you Microsoft internal? (alias: ethanyang)

**Comment by rravishankar2** [comment]
@necusjz I added your Microsoft alias link. You should've received an email.

**Comment by necusjz** [comment]
As we have limited bandwidth in this sprint, let's plan it in the next sprint. Thanks for your understanding.

**Comment by necusjz** [comment]
@rravishankar2 Still cannot access it, what's your alias then? Let's chat via Teams.

**Comment by rravishankar2** [comment]
@necusjz Sure. My alias is rravishankar. Could you please reach out to me over Teams? Thanks

**Comment by tejasshah7** [comment]
Any reason this has been delayed so much? This significantly delayed our feature release.

**Comment by necusjz** [comment]
> Any reason this has been delayed so much? This significantly delayed our feature release. This is NOT a breaking change. Why is this tagged as Breaking change?
I already shared the context with the owner of the feature request.

Sorry for the postpone, we had limit bandwidth in the last sprint for Microsoft Build event (also known as breaking change window). Currently, we're working for this feature request.

**Comment by Miskatonic-Electronic** [comment]
What is the new ETA for deploying these changes?

Can you help me understand how the change in dates was shared? I am the feature owner. My apologies if I missed the change in date message previously. I just want to make sure we have clear and open lines of communication in the future as we partner together on additional feature work.

**Comment by necusjz** [comment]
> What is the new ETA for deploying these changes?
> 
> Can you help me understand how the change in dates was shared? I am the feature owner. My apologies if I missed the change in date message previously. I just want to make sure we have clear and open lines of communication in the future as we partner together on additional feature work.

Ah, OK. Sorry for the misunderstanding, I have shared the context with @rravishankar2. And, the next coming release date is 07/04.
