### ISSUE TITLE
`az network nic update --remove ipConfigurations <index>` uses indexes incorrectly

### ISSUE THREAD

**Issue by giggio** [Azure/azure-cli#26003]
## Describe the bug

**Command Name**
`az network nic update`

**Errors:**

There are no error messages, but the behavior is incorrect. If I have 5 ipConfigurations and I run it like this:

```bash
az network nic update -g <rg> --name <name> --remove ipConfigurations 2 --remove ipConfigurations 3
```

It will succeed, but it will actually remove indexes 2 and 4.

## To Reproduce:
Steps to reproduce the behavior.

- Create a nic with 5 ip configs.
- Run `az network nic show -g <rg> -n <name> --query ipConfigurations -otable` to view existing ip configurations.
- Run the command to remove ip configs: `az network nic update -g <rg> --name <name> --remove ipConfigurations 2 --remove ipConfigurations 3`.
- Check the output.

## Expected Behavior

Ip configs 2 and 3 are removed. Instead, 2 and 4 are removed.

## Environment Summary
```
Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04.1 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.46.0

Extensions:
ssh 1.1.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

## Additional Context

This will happen for any number of ip configs, if you remove 2, 3 and 4, it will actually remove 2, 4 and 6. It is clear that this is a typical removal in a for loop which does not account for the removed items, and for this reason it is skipping every other item in the list.
This makes it impossible to remove more than half the ip configurations at once. If you have 5 ip configs and try to remove them all, it will fail with an out of bounds error.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@giggio

For your needs, generic update (i.e., --remove) doesn't support well. I highly recommend you to leverage [shorthand syntax](https://github.com/Azure/azure-cli/blob/dev/doc/shorthand_syntax.md#pass-a-null-value), however it's not supported yet.

Above PR is about that, after it released, you can achieve it like https://github.com/necusjz/azure-cli/blob/2ece708758c88340c4164f45a4c8dcf54bc7a76e/src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py#L4279.
