### ISSUE TITLE
`EnableAutomaticUpgrade` vm extension property not populated in `az vm list --resource-group xx`

### ISSUE THREAD

**Issue by bhavanakonchada** [Azure/azure-cli#26019]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az vm list --resource-group xx

**Describe the bug**

When the command `>az vm list --resource-group xx` is executed, it lists vms -> resources -> vm extensions -> but the values for property `EnableAutomaticUpgrade`  for each VM extension is set to `NULL`.

**To Reproduce**

1. Create a resource group.
2. Add a VM resource.
3. Add a VM extension like AzureSecurityLinuxAgent
4. On the VM extension, set `Automatic Upgrade Status` to true and save changes to VM.
5. Use Az CLI to see extension data for the given VM: `az vm extension list -g xx --vm-name yy`. In the command output, the property `EnableAutomaticUpgrade` is set to true. -> this is expected and the correct behavior
6. Use Az CLI to see extension data for the given VM: `az vm list --resource-group xx`. In the command output, the property `EnableAutomaticUpgrade` for the given VM is set to `NULL`. -> this is unexpected and the wrong behavior

**Expected behavior**

Behaviour of property values seen in `az vm extension list` and `az vm list` should be same. The correct value of `EnableAutomaticUpgrade` should be consistently populated in both commands.

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bhavanakonchada** [comment]
@yonzhan, will you have an update on the above issue?

**Comment by zhoxing-ms** [comment]
The `az vm list` command directly outputs the data returned by the REST service without any special processing logic. Therefore, this should be a service issue

**Comment by bhavanakonchada** [comment]
May I get an update on the bug please ?

**Comment by bhavanakonchada** [comment]
@zhoxing-ms I don't see any traction on this issue? Can it be brought to attention to the right folks?

**Comment by zhoxing-ms** [comment]
@grizzlytheodore Could you please help take a look at this issue or could you help route this issue to the right person?

**Comment by bhavanakonchada** [comment]
@grizzlytheodore @zhoxing-ms Folks, Can I get an update on this? We are blocked right now, and an update will help us.

**Comment by TravisCragg-MSFT** [comment]
@bhavanakonchada My apologies for the delay in response on this. 

These cmdlets are different and separate, and this is working by design. az vm list does not show full extension information, and most blanks are null because they have no info. for extension status always use az vm extension list.
