### ISSUE TITLE
On creating azure container instance getting error message "unrecognized arguments:"

### ISSUE THREAD

**Issue by arvinda221994** [Azure/azure-cli#26016]
On creating an azure container instance getting an error message

az command: az container create --resource-group sonarQubeSQC --name sonarqube --image sonarqube --ports 9000 --dns-name-label sqc.sonarqube --tags "Client=Internal" "Environment=Test" "Owner=SQC" --cpu 2 --memory 3.5

![image](https://user-images.githubusercontent.com/117155237/229194899-2b03e3c0-a0f8-40d3-8e96-58092636ff84.png)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@arvinda221994 You are getting this error as `az container create` doesn't have any argument named `--tag`.  Please refer to the [az container create](https://learn.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-create) documentation.

**Comment by arvinda221994** [comment]
@SaurabhSharma-MSFT Thanks for your response, I don't see the --tags attribute in [https://learn.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest](url) document

**Comment by SaurabhSharma-MSFT** [comment]
@arvinda221994 Yes this cmdlet doesn't have any --tag attribute which you are trying to use.  can you please share the documentation which you are referring to which asks for a --tag or --tags attribute?

**Comment by arvinda221994** [comment]
@SaurabhSharma-MSFT Yes I know that cmdlet doesn't allow tags, is there any solution to resolve that issue? Because I want to create a container instance using tags

**Comment by SaurabhSharma-MSFT** [comment]
@arvinda221994 In that case you need to create the container instance using `az container create` and then attach the resource with any tag using [az resource tag](https://learn.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#az-resource-tag).
