### ISSUE TITLE
Add support for Rate Limit in WAF Policy

### ISSUE THREAD

**Issue by sraghavan-msft** [Azure/azure-cli#26017]
**Related command**
az network application-gateway waf-policy custom-rule

https://learn.microsoft.com/en-us/cli/azure/network/application-gateway/waf-policy/custom-rule?view=azure-cli-latest

**Is your feature request related to a problem? Please describe.**
Rate Limiting requests to help protect backend applications from traffic spikes is the problem this feature addresses. This feature can be used to limit number of request within a configurable time interval that can be received from a client (identified by either ip address or geo location) or by an endpoint (typically a url). Any requests beyond this limit will be denied by WAF until the time interval lapses when requests will be allowed again.

**Describe the solution you'd like**
WAF Policy Custom Rule will be extended to support a rule of type RateLimitRule. This is addition to the MatchRule type that is already supported. Along with this, users can configure a threshold, time interval and how the client or the end point will be identified.

**Describe alternatives you've considered**
N/A

**Additional context**
**Resource Provided**

Network(NRP)

**Minimum API Version Required**

2022-11-01

**Swagger PR link / SDK link**

https://github.com/Azure/azure-rest-api-specs/pull/23021

**Request Example**

https://github.com/Azure/azure-rest-api-specs/blob/release-Microsoft.Network-2022-11-01/specification/network/resource-manager/Microsoft.Network/stable/2022-11-01/examples/WafPolicyCreateOrUpdate.json

**Comment by necusjz** [comment]
As we have limited bandwidth in this sprint, let's plan it in the next sprint. Thanks for your understanding.

**Comment by necusjz** [comment]
We're working heavily on Microsoft Build now, I'm afraid that this feature will be postponed to the next sprint.

**Comment by necusjz** [comment]
> Hello @necusjz, what is the ETA for this to be completed? It looks like it will be July (2023-07-04) based on the last update. Any chance of moving this up the queue?

We're already working on it. (But the next release date is 07/04 you mentioned :)
