### ISSUE TITLE
The endpoint 'management' for this cloud is not set but is used.

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-cli#2601]
I am adding an azurestack cloud and not specifying --endpoint-management. This parameter should not be needed as CLI 2.0 works only against ARM, not RDFE. Need to remove the usage of this parameter

**Comment by bganapa** [comment]
cc:@derekbekoe

**Comment by derekbekoe** [comment]
This was fixed in https://github.com/Azure/azure-cli/pull/2398/files#diff-69bacf5348b997023cd1e8e6f475a0daR248 which is on the 'api-profile-support' branch.

Closing issue.
