### ISSUE TITLE
Missing word `use` in parameter description.

### ISSUE THREAD

**Issue by abhi-markan** [Azure/azure-cli#26012]
[Enter feedback here]

```
--approval-required
Whether subscription approval is required. If false, new subscriptions will be approved automatically enabling developers to call the product’s APIs immediately after subscribing. If true, administrators must manually approve the subscription before the developer can any of the product’s APIs. Can be present only if subscriptionRequired property is present and has a value of false.
```
Missing word **use** in `before the developer can any of the product’s APIs`, should be:

```
before the developer can use any of the product’s APIs..
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12388aef-b752-cab1-af24-e54c72ef0c68
* Version Independent ID: 2e11c672-76d1-8bb2-94a3-7144792ba1b1
* Content: [az apim product](https://learn.microsoft.com/en-us/cli/azure/apim/product?view=azure-cli-latest#az-apim-product-create)
* Content Source: [latest/docs-ref-autogen/apim/product.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/apim/product.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@abhi-markan We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@abhi-markan The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
