### ISSUE TITLE
az cdn endpoint purge rejects /$web/* content path

### ISSUE THREAD

**Issue by daningalla** [Azure/azure-cli#26025]
**Related command**
az cdn endpoint purge

**Describe the bug**
I have a cdn profile that has an origin domain linked with an azure storage account. I'm publishing the files of a static website to blob storage, and azure creates a container called `$web`. In my GH action as instructed [here](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-static-site-github-actions?tabs=userlevel), I'm purging the cdn as one of the final steps. 

Trying right from Powershell, the following command fails:
`az cdn endpoint purge --content-paths "/`$web/*" --profile-name $CDN_PROFILE -g $RESOURCE_GROUP -n $CDN_ENDPOINT`
 
with:
```
(BadRequest) Invalid ContentPath "/$web/*". ContentPath for purge action must be a relative path: either for a single resource "/path/pic.jpg" or a wild card "/path/*".
Code: BadRequest
Message: Invalid ContentPath "/$web/*". ContentPath for purge action must be a relative path: either for a single resource "/path/pic.jpg" or a wild card "/path/*".
```

**To Reproduce**
Run the following from PS:
``az cdn endpoint purge --content-paths "/`$web/*" --profile-name $CDN_PROFILE -g $RESOURCE_GROUP -n $CDN_ENDPOINT``

**Expected behavior**
The CLI accepts the content-path `/$web/*`.

**Environment summary**
`az --version` = 2.46.0
OS: Windows 10 pro
Shell type: Powershell

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by PramodValavala-MSFT** [comment]
@daningalla Thanks for the feedback! We will review and get back to you on this.

**Comment by t-bzhan** [comment]
Hi @daningalla , that seems to be a limitation in service side which use an incorrect regular expression to validate URL paths. I will engage with service team to see whether we could come up with a fix for that.

**Comment by laPlacek** [comment]
I have a simillar problem when my path conains '@'  in it (CDN on front of npm registry). :|

**Comment by t-bzhan** [comment]
The latest update from the engineering team is that the path regex defined on the service side is specific to the Akamai provider. Consequently, we can eliminate the check, as it has already been retired. The engineering team is actively working to remove this restriction.

**Comment by t-bzhan** [comment]
The issue has been fixed now.
