### ISSUE TITLE
Commands fails with `CERTIFICATE_VERIFY_FAILED` on Mariner 2.0 docker image

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#26026]
**Related command**
`az bicep`
`az storage copy`

**Describe the bug**
Azure CLI commands utilizing [`urllib.request.urlopen`](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen) such as `az bicep`, `az storage copy` may encounter error `CERTIFICATE_VERIFY_FAILED` on Mariner 2.0 docker image.

**To Reproduce**
```
> docker run -it --rm mcr.microsoft.com/cbl-mariner/base/core:2.0
# # tdnf install -y azure-cli
# az storage copy
Connection error while attempting to download azcopy 10.13.0. You could also install the specified azcopy version to 
/root/bin manually. (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local 
issuer certificate (_ssl.c:1129)>)
```

**Solutions**
Short-term: Install `ca-certificates` on Mariner docker image explicitly:

```
tdnf install ca-certificates
```

`ca-certificates` contains the official Microsoft curated set of trusted root certificates. It has replaced the set of Mozilla Trusted Root Certificates.

Long-term: We are migrating usages of `urllib.request.urlopen` to `requests` (https://github.com/Azure/azure-cli/issues/26008) so that all commands can use the CA bundle provided by [`certifi`](https://pypi.org/project/certifi/) library which is included in Azure CLI packages.

**Additional information**
Technical details: #26007

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Updated the document to include `tdnf install ca-certificates`: https://github.com/MicrosoftDocs/azure-docs-cli/pull/3588
