### ISSUE TITLE
Update Azure Stack HCI 2023-03-01 API version

### ISSUE THREAD

**Issue by agrbhuvnesh** [Azure/azure-cli#26020]
Please update Azure CLI/Powershell to latest Azure Stack HCI api version 2023-03-01
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI/stable/2023-03-01

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@agrbhuvnesh May I ask if we only need to upgrade the api-version to `2023-03-01`? Or do we need to add some new commands and parameters based on the new version of Swagger?

**Comment by agrbhuvnesh** [comment]
Yes, there are few more commands added since last API version 2022-05-01 released. You can refer from swagger spec.

**Comment by Jing-song** [comment]
Hi @agrbhuvnesh , I found some problems in swagger and submitted a PR(https://github.com/Azure/azure-rest-api-specs/pull/23648), we need to fix it to make the new version work, could you please help to check it, thanks.
