### ISSUE TITLE
Add --ids parameter support for Azure Stack HCI 

### ISSUE THREAD

**Issue by agrbhuvnesh** [Azure/azure-cli#26021]
### Related command

az stack-hci --ids [cluster ids]

### Resource Provider

Microsoft.AzureStackHCI

### Description of Feature or Work Requested

We need to add support for at-scale  operations  through Azure Stack HCI CLI / Powershell by providing option to pass multiple resource ids (--ids)
Similar to Azure Virtual Machine
az vm extension set -n GenevaMonitoring --publisher "Microsoft.Azure.Geneva"  --ids $(az vm list -g <rg> --query "[].id" -o tsv)

### Minimum API Version Required

2023-03-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI/stable/2023-03-01/examples/PutExtension.json

### Target Date

2023-04-15

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
