### ISSUE TITLE
Unrecognized arguments: --continuation-token under az storage blob list

### ISSUE THREAD

**Issue by morristai** [Azure/azure-cli#26034]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

```bash
az storage blob list --container-name <name> --continuation-token <token>
```

**Describe the bug**

After I retrieve a continuation token from the first command that list storage blob, I can't use the token since it said `ERROR: unrecognized arguments: --continuation-token` when I want to get the rest of the result. 

**To Reproduce**

Put `--continuation-token` after `az storage blob list` or `az storage blob list --help` to verify if az support this argument.

**Expected behavior**

I can get the rest results via `--continuation-token` as an arguments after `az storage blob list` [similar to this one describe](https://stackoverflow.com/questions/73113493/how-do-we-deal-with-the-continuation-token-when-using-the-az-devops-security-g)

**Environment summary**

```bash
# MacOS 13.2.1 
➤ az --version
azure-cli                         2.46.0

core                              2.46.0
telemetry                          1.0.8

Extensions:
kusto                              0.5.0
aks-preview                      0.5.135
databricks                        0.10.0
interactive                        0.4.6
fzf                                1.0.2

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/usr/local/Cellar/azure-cli/2.46.0/libexec/bin/python'
Extensions directory '/Users/morris_tai/.azure/cliextensions'

Python (Darwin) 3.10.10 (main, Feb 16 2023, 02:55:02) [Clang 14.0.0 (clang-1400.0.29.202)]
```

**Additional context**

I will try powershell AZ module to see if the token works.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
Hi @morristai, the parameter for continuation token is `--marker`. You can check all the parameter description through `az storage blob list -h` or https://learn.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-list-optional-parameters

**Comment by morristai** [comment]
Thanks @evelyn-ys for the quick response, my bad for missing that parameter.
