### ISSUE TITLE
az keyvault list-deleted fails with provider error on v2.47.0

### ISSUE THREAD

**Issue by andypikeevo** [Azure/azure-cli#26058]
## Describe the bug

**Command Name**
`az keyvault list-deleted`

**Errors:**
```
(ProviderError) Resource provider 'Microsoft.KeyVault' failed to return collection response for type 'deletedVaults'.
Code: ProviderError
Message: Resource provider 'Microsoft.KeyVault' failed to return collection response for type 'deletedVaults'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az keyvault list-deleted`

## Expected Behavior
List of deleted keyvaults should be returned.

## Environment Summary
```
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04.2 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.47.0

Extensions:
ssh 1.1.2

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```
## Additional Context
I downgraded back to  2.46.0 and command works as expected

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by andypikeevo** [comment]
Update to confirm that when explicitly specifying `resource-type vault` the command still fails with the same error.

**Comment by evelyn-ys** [comment]
@kim-soohwan FYI

**Comment by kim-soohwan** [comment]
@andypikeevo, what cloud were you running this command in? Are you still experiencing this issue?

**Comment by andypikeevo** [comment]
> @andypikeevo, what cloud were you running this command in? Are you still experiencing this issue?

Hi, it was UKSouth
I have just re-upgraded back to 2.47.0 and it is now working as intended.

Closing as resolved.
