### ISSUE TITLE
 az aks get-credentials: FAILURE

### ISSUE THREAD

**Issue by 4021019** [Azure/azure-cli#26056]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.46.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@4021019 Can you please provide us the error message you are getting. Thanks

**Comment by SaurabhSharma-MSFT** [comment]
@4021019 Please let me know if you need any help on this one.  If yes, please provide us the debug log to investigate further.

**Comment by SaurabhSharma-MSFT** [comment]
@4021019 We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
