### ISSUE TITLE
 az keyvault list-deleted --resource-type hsm: Resource provider 'Microsoft.KeyVault' failed to return collection response for type 'deletedManagedHSMs'

### ISSUE THREAD

**Issue by raymonvtu** [Azure/azure-cli#26057]
## Describe the bug

When trying to list deleted HSMs i get this error. I knew there was a problem created before mine but this problem was closed in February because it was "fixed". It looks like the problem is still at large however.

**Command Name**
`az keyvault list-deleted`

**Errors:**
```
(ProviderError) Resource provider 'Microsoft.KeyVault' failed to return collection response for type 'deletedManagedHSMs'.
Code: ProviderError
Message: Resource provider 'Microsoft.KeyVault' failed to return collection response for type 'deletedManagedHSMs'.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault list-deleted --resource-type hsm`

## Expected Behavior
a list of deleted hsm vaults

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.47.0

Extensions:
virtual-wan 0.2.16

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
@kim-soohwan FYI

**Comment by raymonvtu** [comment]
Could this be a service issue? it is working again right now. We did not change anything and my cli version is still 2.47.
The comment returns the expected output even when defining the hsm resource type.

`{
  "azure-cli": "2.47.0",
  "azure-cli-core": "2.47.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "virtual-wan": "0.2.16"
  }
}`

**Comment by kim-soohwan** [comment]
There was a service side issue couple of weeks ago when these issues were being reported that was resolved soon after.
