### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by NrdWthaPythonScript** [Azure/azure-cli#26064]
## Describe the bug

**Command Name**
`az webapp deployment source config-zip`

**Errors:**
```
HTTPSConnectionPool(host='*****'.scm.azurewebsites.net', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:997)')))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp deployment source config-zip --resource-group {} --name {} --src {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.47.0

Extensions:
appservice-kube 0.1.7

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@NrdWthaPythonScript Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@NrdWthaPythonScript Could you please confirm if you are behind a `corporate firewall` or `corporate proxy` ? If Yes, this seems to be causing the SSL connection to fail during the certificate check. 

1. Could you please try the same operation from a different reliable network and check if that helps ?
2. If you want to make the AzCLI work behind a proxy [follow this. ](https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#work-behind-a-proxy)
3. If you want to make this work with your Org's proxy then you need to follow the below:

    - You need to add HTTP_PROXY and HTTPS_PROXY environment variables to the system
    - Then you need to find certifi path for your AzCLI installation. Default path should be: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\certifi".
    - Download your corporate proxy's root certificate and append it to "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\certifi\cacert.pem"

4. You could try setting the env variable (set AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1). **_Not_** a recommended approach though. 

Hope this helps.

**Comment by navba-MSFT** [comment]
@NrdWthaPythonScript I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by NrdWthaPythonScript** [comment]
yes I have added the certs to the file

**Comment by navba-MSFT** [comment]
@NrdWthaPythonScript Thanks for your reply. Could you please share the update on **Plan 1**, **Plan 2** and **Plan 4** ? Did you try it ? Does that solve your issue ? Also check with your internal network team if they could whitelist the host='*****'.scm.azurewebsites.net', port=443 on the proxy ?  Awaiting your reply.

**Comment by navba-MSFT** [comment]
@NrdWthaPythonScript I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@NrdWthaPythonScript The action is pending on you to follow the Plan 1, Plan 2 and Plan 4 mentioned above and share an update. Once you are ready to resume your troubleshooting on this, please feel free to reopen this thread. We would be happy to help.
