### ISSUE TITLE
Key not valid for use in specified state

### ISSUE THREAD

**Issue by antonGritsenko** [Azure/azure-cli#26075]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.19045-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.47.0
```
## Additional Context
This error occurred on any request to Azure using az cli.
The az cli was updated to latest version, but on prev we had the same.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
