### ISSUE TITLE
resource: support invoke arbitrary action on a resource

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#2607]
With #2606, #2573, hope this should get all RP covered before they have first-class (strong type) command supports

**Comment by tjprescott** [comment]
What do you mean by arbitrary action?

**Comment by yugangw-msft** [comment]
In a sense like a `VM stop`, a `post` operation which or w/o request payload.

**Comment by yugangw-msft** [comment]
The flow itself can be done by lot of external tools, but doing it through cli makes a bit sense for the reason that only CLI can provide the `authorization` header with the access token it manages

**Comment by JasonRShaver** [comment]
This is a parity item for XPlat CLI

**Comment by yugangw-msft** [comment]
Well, this is not a parity for Xplat CLI, rather is a parity for POSH
