### ISSUE TITLE
I am unable to execute az cli

### ISSUE THREAD

**Issue by parulmittaltia** [Azure/azure-cli#26088]
I ran az login post which iI entered credentials in browser and was able to sign in via browser.  But on CLI I get  error "Decryption failed: WinError -2146893813] Key not valid for use in specified state. App developer may consider this guidance: https://GitHub.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/Persistence decryption error 
Please report to us via GitHub: https://GitHub.com/Azure/azure-cli/issues/20231

I did not find useful guidance on guidance url so please fix as I can't proceed
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
