### ISSUE TITLE
az webapp deploy with zip does not overwrite new static files

### ISSUE THREAD

**Issue by BenjaminAbt** [Azure/azure-cli#26085]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

```shell
az --version
azure-cli                         2.47.0
core                              2.47.0
telemetry                          1.0.8
Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\abc\.azure\cliextensions'
Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]
Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.
```

**Related command**
> az webapp deploy --resource-group ${{ parameters.azResourceGroup }} --name app-${{ parameters.projectName }}-webapp-${{ parameters.envName }} --src-path ${{ parameters.webAppDeployPackageFilePath }} --type zip

**Describe the bug**
We have an ASP.NET application that contains static files. We use the standard .NET command for publishing the application.

```shell
dotnet publish $(PUBLISH_PROJECT_PATH) --no-restore --configuration $(BUILD_TYPE) -o $(PUBLISH_PROJECT_TARGET_FOLDER_ZIP_SOURCE) --runtime $(DOTNET_RUNTIMES) --self-contained true
```
The raw files are then zipped via powershell.
The zip is uploaded as an artifact in Azure DevOps during the build and used in the release step via az webapp deploy.

Issue: The new CSS files are not delivered via app. After a longer debugging, we saw that there are still old files in the KUDU section of the App Service.
However, we can verify in the Artifact ZIP that definitely the new files are included.

So the exclusion procedure is that az webapp deploy does not write the new files to the Web App.
We have also tried the --clean true command with unfortunately the same result.

**To Reproduce**
See command

**Expected behavior**
Files should be updated.

**Environment summary**
Azure DevOps with Self Hosted Windows Agent

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by BenjaminAbt** [comment]
Found more info.

- az webapp deploy says it succeeded
- WebApp Deployment Center says it succeeded

But the logs say it failed

```shell
Copying file: 'WindowsBase.dll'
Copying file: 'af\Humanizer.resources.dll'
Error: EINVAL: invalid argument, open '/home/site/wwwroot/af\Humanizer.resources.dll'
An error has occurred during web site deployment.
Kudu Sync failed
\n/opt/Kudu/Scripts/starter.sh "/home/site/deployments/tools/deploy.sh"
```
Huge KUDU bug.

Looks like its again the issue it that kudu cannot handle zip files from Windows to a Linux App.
Exists for years for the "AzureWebApp@1" Task and no fix. Frustrating....

**Comment by sarsharma** [comment]
Hi @BenjaminAbt, this seems to be an issue with [Powershell module](https://github.com/PowerShell/Microsoft.PowerShell.Archive) used for creating the zip archive. It uses `\` instead of `/` as separator which is causing issues during Kudu sync. 
You can notice in your logs, the `.dll` path is a mix of `/` and `\`, which caused `Error: EINVAL: invalid argument, open '/home/site/wwwroot/af\Humanizer.resources.dll'`
I was able to repro this issue when creating zip archive with Powershell, but it works fine if I use other utility to create the zip archive. 
Relevant powershell issue: https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/48
