### ISSUE TITLE
I am facing the issue az account list and az account show 

### ISSUE THREAD

**Issue by kirankumarpadla1122** [Azure/azure-cli#26095]
## Describe the bug

**Command Name**
`Unknown`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- ``

## Environment Summary
```
Windows-10-10.0.19044-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0 *
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please provide detailed error info.

**Comment by jiasli** [comment]
I searched the internet but didn't find useful information regarding the error `Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding`. Could you perform a clean installation following https://github.com/Azure/azure-cli/issues/20990?

**Comment by bebound** [comment]
It appears some CLI Python related files are missing. Jiasli's suggestion should work.

**Comment by kirankumarpadla1122** [comment]
C:\windows\system32>az account show
Auto upgrade failed. 'pypi'

By the suggestion jiasli i have followed thesteps even i am getting the some of the error like this. can you please advise on this

**Comment by bebound** [comment]
Please disable auto upgrade by `az config set auto-upgrade.enable=no`.
I guess you have trouble when open pypi.
Similar issue: https://github.com/Azure/azure-cli/issues/20473
