### ISSUE TITLE
az apim deletedservice list: Resource provider 'Microsoft.ApiManagement' failed to return collection response for type 'deletedServices'

### ISSUE THREAD

**Issue by PetrPospisil** [Azure/azure-cli#26107]
## Describe the bug
We just call the command and we get the error.

**Command Name**
`az apim deletedservice list`

**Errors:**
```
(ProviderError) Resource provider 'Microsoft.ApiManagement' failed to return collection response for type 'deletedServices'.
Code: ProviderError
Message: Resource provider 'Microsoft.ApiManagement' failed to return collection response for type 'deletedServices'.

```
[output.txt](https://github.com/Azure/azure-cli/files/11199459/output.txt)

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az apim deletedservice list --debug`

## Expected Behavior
It works without an error.

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.40.0 *

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```
## Additional Context
Probably started to happen today.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by PetrPospisil** [comment]
It does not work in 2.47.0 either.

[output.txt](https://github.com/Azure/azure-cli/files/11199561/output.txt)

**Comment by PetrPospisil** [comment]
`az account set -s f30a9808-d915-4ea0-ade5-ef9e90f20d72`
`az apim deletedservice list`
have started to work today morning

`az account set -s ee913b11-6c88-41bd-8d9b-addfe5119e0b`
`az apim deletedservice list`
still failing with the same error. 

It seems like MS is fixing this selectively based on error logs or maybe it is random.

**Comment by PetrPospisil** [comment]
Seems fixed by MS

**Comment by JLunda** [comment]
I am getting this same error when running the latest versions of both AZ CLI (2.55.0) and PowerShell 7 (7.4.0) as of this writing.

**Comment by fleed** [comment]
Also getting the error with version `2.56.0`

**Comment by dcdereus** [comment]
also getting error with 2.57.0
