### ISSUE TITLE
`az acs kubernetes get-credentials` should use ssh-agent if available

### ISSUE THREAD

**Issue by jseely** [Azure/azure-cli#2612]
Currently `az acs kubernetes get-credentials` will by default look for an ssh-key in `~/.ssh/id_rsa` or use an ssh key file provided through the `--ssh-key-file`. It appears this key is just being used to ssh into the master node in the cluster, so it should be able to use keys stored in the ssh-agent on the local machine.

**Comment by brendandburns** [comment]
Did it not work? According to the docs here:

http://docs.paramiko.org/en/2.1/api/client.html

It looks like parimiko should be trying to talk to an ssh-agent if one is running...

**Comment by rjtsdl** [comment]
@jseely can you confirm the issue is resolved or not?

**Comment by yugangw-msft** [comment]
closing as the `az acs` are deprecating
