### ISSUE TITLE
Get-AzVmSize,  az vm list-sizes and REST API returns incorrect CPU count

### ISSUE THREAD

**Issue by troiz95** [Azure/azure-cli#26130]
**Related command**
example
  **az vm list-sizes --location eastus --query "[?name=='Standard_E64-32ds_v5']"**     

**Describe the bug**
Get-AzVmSize,  az vm list-sizes and REST API returns incorrect CPU count for Standard_E* series and other instance sizes that have different actual number of vCPUs for the constrained vCPU capable 
**To Reproduce**
run

 **az vm list-sizes --location eastus --query "[?name=='Standard_E64-32ds_v5']"** 

returns                                                                                                         
[
  {
    "maxDataDiskCount": 32,
    "memoryInMb": 524288,
    "name": "Standard_E64-32ds_v5",
    "numberOfCores": 64,
    "osDiskSizeInMb": 1047552,
    "resourceDiskSizeInMb": 2457600
  }
]

or 
**Get-AzVMSize -Location eastus | select Name, NumberOfCores, MemoryInMB | select-string -pattern "Standard_E64-32ds_v5"**
returns 
**@{Name=Standard_E64-32ds_v5; NumberOfCores=64; MemoryInMB=524288}**

**Expected behavior**
for provided example, numberOfCores should be 32

**Environment summary**
azure-cli                         2.47.0
latest PS module
Any app that using Azure REST API

**Additional context**
Similar behavior was found 2 years ago. Also recently somebody responded that it should be re-submitted
https://github.com/Azure/azure-cli/issues/16196)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
> Get-AzVmSize, az vm list-sizes and REST API returns incorrect CPU count for Standard_E* series and other instance sizes that have different actual number of vCPUs for the constrained vCPU capable

Since REST API returns incorrect CPU count, so this should be a service issue

**Comment by navba-MSFT** [comment]
@troiz95 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@troiz95 The `az vm list-sizes` and` Get-AzVMSize` both are calling the deprecated [ Virtual Machine Sizes - List REST API](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-sizes/list?tabs=HTTP) underneath. The recommended API is [Resource Skus - List](https://learn.microsoft.com/en-us/rest/api/compute/resource-skus/list?tabs=HTTP#code-try-0)

I am looking into this further to address this. 

In the meantime, Please run the below PS command as a workaround:
```
$list = Get-AzComputeResourceSku -location eastus | ? { $_.ResourceType -eq 'virtualMachines' -and $_.Name -like 'Standard_E64-32ds_v5' }
$list | select Size, @{n='vCPUs'; e={$_.Capabilities.Where{$_.Name -eq 'vCPUs'}.Value}}, @{n='vCPUsAvailable'; e={$_.Capabilities.Where{$_.Name -eq 'vCPUsAvailable'}.Value}}
```

**Comment by troiz95** [comment]
Hi @navba-MSFT  !
Thanks, vCPUsAvailable property indeed returns correct result from AzComputeResourceSku  cmdlet. but - usual vCPU is still incorrect.

$list | select Size, @{n='vCPUs'; e={$_.Capabilities.Where{$_.Name -eq 'vCPUs'}.Value}}, @{n='vCPUsAvailable'; e={$_.Capabilities.Where{$_.Name -eq 'vCPUsAvailable'}.Value}}

Should I always use "vCPUsAvailable" in REST API apps instead of "vCPUs"? I've checked and even in Resource Sku API it returns incorrect vCPUs count (vCPUsAvailable is correct)

Size       vCPUs vCPUsAvailable
----       ----- --------------
E32-8ds_v5 32    8

**Comment by navba-MSFT** [comment]
@troiz95 vCPUsAvailable will give you the number of virtual processors that are seen by the guest OS. However, if you are running Windows you pay as if there were 64 vCPUs due to the way that we bill for Windows.

**Comment by navba-MSFT** [comment]
@troiz95 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@troiz95 I hope you had a chance to look at the above comment. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by brokedba** [comment]
> Hi @navba-MSFT ! Thanks, vCPUsAvailable property indeed returns correct result from AzComputeResourceSku cmdlet. but - usual vCPU is still incorrect.
> 
> Should I always use "vCPUsAvailable" in REST API apps instead of "vCPUs"? I've checked and even in Resource Sku API it returns incorrect vCPUs count (vCPUsAvailable is correct)
> 
> $list | select Size, @{n='vCPUs'; e={$_.Capabilities.Where{$_.Name -eq 'vCPUs'}.Value}}, @{n='vCPUsAvailable'; e={$_.Capabilities.Where{$_.Name -eq 'vCPUsAvailable'}.Value}}
> 
> Size vCPUs vCPUsAvailable E32-8ds_v5 32 8

I just replied to the mentioned Issue #16196 , `vCPUsAvailable`  is the right attribute to look at even using az cli. 
see my reply with the right command and shell script to select constrained Vms based on available VCPU needed. 

👉🏽 [16196#Comment](https://github.com/Azure/azure-cli/issues/16196#issuecomment-1570279017)
