### ISSUE TITLE
no module named decorator

### ISSUE THREAD

**Issue by kirkhammond** [Azure/azure-cli#26131]
## Describe the bug

**Command Name**
`az upgrade`

**Errors:**
```

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az upgrade --yes --all --debug`

## Environment Summary
```
Linux-6.2.9-200.fc37.x86_64-x86_64-with-glibc2.36, Fedora Linux 37 (Workstation Edition)
Python 3.11.2
Installer: RPM

azure-cli 2.44.1 *
```
## Additional Context
I've tried all the commands I can find to solve this, no matter what the module is missing. I've installed via pip as user and root, there is no change.

Fedora 37.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please provide detailed error log here.
