### ISSUE TITLE
Allow to customize flux controllers

### ISSUE THREAD

**Issue by mfilotto** [Azure/azure-cli#26137]
**Related command**

az k8s-configuration flux create

**Is your feature request related to a problem? Please describe.**

When using flux, we often need to customize flux controllers as describe [here](https://fluxcd.io/flux/cheatsheets/bootstrap/#how-to-customize-flux)

**Describe the solution you'd like**

It would be great if "az k8s-configuration flux create" had a way to patch flux controllers

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by NarayanThiru** [comment]
@bavneetsingh16 , can you pl. take a look at this?

**Comment by bavneetsingh16** [comment]
We allow updating the controllers deployed as part of flux extension, please find the documentation link for it below.

[https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-flux2?tabs=azure-cli#workload-identity-in-aks-clusters](https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-flux2?tabs=azure-cli#workload-identity-in-aks-clusters)

Need to use 'k8s-extension' cmd to update the flux extension.
