### ISSUE TITLE
Is the az spring-cloud command group deprecated?

### ISSUE THREAD

**Issue by ciufudean** [Azure/azure-cli#26136]
When I run `az spring-cloud app log` I get a deprecation warning.
I am not seeing this warning in his documenation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b05a9f2-699f-46c6-9242-53fd2b999bac
* Version Independent ID: bb91360d-8570-4189-db30-fc15e483d2f1
* Content: [Azure Spring Cloud](https://learn.microsoft.com/en-us/cli/azure/service-page/azure%20spring%20cloud?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/service-page/Azure Spring Cloud.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/service-page/Azure Spring Cloud.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@ciufudean The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
