### ISSUE TITLE
 key keyvault's key create: Using 1024 as size will fail

### ISSUE THREAD

**Issue by khenidak** [Azure/azure-cli#2613]
``` 
az keyvault key create --name somekey --vault-name somevault --size 1024 --protection software

```

Will fail with **Unsupported key size** while using 2048 will work. the problem is using
```
az keyvault key create --help  
```
Will give

```
...
--size                    : The key size in bytes. e.g. **1024** or 2048.
...
```

**Comment by tjprescott** [comment]
Thanks for the report @khenidak. This help text is pulled from the SDK. I've create an in our REST API specs to fix this problem at the source.

**Comment by yonzhan** [comment]
issue triaged.

**Comment by bim-msft** [comment]
@khenidak The help message was refined, we don't support RSA1024.
```
 --size                  : The key size in bits. For example: 2048, 3072, or 4096 for RSA.
```
