### ISSUE TITLE
Allow to use in-cluster decryption feature of flux

### ISSUE THREAD

**Issue by mfilotto** [Azure/azure-cli#26147]
**Related command**

az k8s-configuration flux create
az k8s-configuration flux kustomization create

**Is your feature request related to a problem? Please describe.**

Flux has this great feature of in-cluster decryption with sops and it's missing on AKS gitops extension because there is no parameter for that.

**Describe the solution you'd like**

It would be nice to be able to specify decryption provider and decryption secret in kustomization as described [here](https://fluxcd.io/flux/guides/mozilla-sops/#configure-in-cluster-secrets-decryption)

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by NarayanThiru** [comment]
@bavneetsingh16 , can you pl. take a look at this?

**Comment by bavneetsingh16** [comment]
@mfilotto, thanks for raising this feature request. We are currently evaluating the request internally and will get back to you shortly.

**Comment by bavneetsingh16** [comment]
@mfilotto, you can create a child resource in your git repository similar to [https://fluxcd.io/flux/components/kustomize/kustomizations/#decryption](https://fluxcd.io/flux/components/kustomize/kustomizations/#decryption) to use in-cluster decryption.

**Comment by bavneetsingh16** [comment]
A new flux version([v1.11.1](https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/extensions-release#1111-august-2024)) release is currently in progress. It will provide the option to use workload identity for kustomize controller. More details on its implementation can be found here [here](https://fluxcd.io/flux/guides/mozilla-sops/#azure).

To use workloadIdentity for kustomize controller, please follow this [doc](https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-flux2?tabs=azure-cli#workload-identity-in-aks-clusters).
