### ISSUE TITLE
Sample.INT

### ISSUE THREAD

**Issue by mrizwan-a** [Azure/azure-cli#26148]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

![IMG_20230330_205022](https://user-images.githubusercontent.com/130172262/231908520-6b5d515e-34c2-48aa-9f86-bbe7e064cbfd.jpg)

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
