### ISSUE TITLE
Setting Key-Value with empty string value does not work as expected in Powershell 7

### ISSUE THREAD

**Issue by Kakaranish** [Azure/azure-cli#26149]
**Related command**

`az appconfig kv set --name cfg-store --key some:key --value "" --yes`

**Describe the bug**

On Ubuntu command works as expected - "some:key" KV is created with no value
The same command executed in Powershell 7 results with such error
`argument --value: expected one argument`

**To Reproduce**

Execute `az appconfig kv set --name cfg-store --key some:key --value "" --yes` command in Powershell 7

**Expected behavior**

KV with no value should be created

**Environment summary**

Az version: 2.41.0
OS: Windows 10
PowerShell: 7.2.10

**Additional context**

The same command with additional `=` after `value` works as expected.
`az appconfig kv set --name cfg-store --key some:key --value="" --yes`

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@Kakaranish Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Kakaranish You can try to run the below command by escaping the quotes and that should work.

```
az appconfig kv set --name MyAppConfigName --key some:key3 --value `"`" --yes --debug
```

Hope this helps.

**Comment by navba-MSFT** [comment]
@Kakaranish I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by Kakaranish** [comment]
Hi, 
```
az appconfig kv set --name MyAppConfigName --key some:key3 --value `"`" --yes --debug 
```
indeed works but not in the way I would expect. Actual result is two quotes as a value but I need to add key with no value. For me `"" != no value`

What's funny I tested 
```
az appconfig kv set --name cfg-store --key some:key --value "" --yes
```
on MacOS v13.3.1 in PowerShell 7.3.2 and works as expected.

**Comment by navba-MSFT** [comment]
@Kakaranish Thanks for getting back. Could you please check if you observed the same behavior in bash shell prompt ?

**Comment by Kakaranish** [comment]
I tested this command on Ubuntu (on Windows) with bash and works as expected. It seems like the problem only occurs on Windows + Powershell 7

**Comment by navba-MSFT** [comment]
@Kakaranish Thanks for your reply. The above mentioned action plan to run the below command should serve your requirement.

> **az appconfig kv set --name MyAppConfigName --key some:key3 --value `"`" --yes --debug**

Running the above command is setting value to **no value**. It is **not** setting it as "". See the below screenshot:

![image](https://user-images.githubusercontent.com/57353862/233920472-65148dae-7eae-48cb-ae03-8f10e378b1b3.png)

**Comment by navba-MSFT** [comment]
@Kakaranish I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by Kakaranish** [comment]
Ok, you're right. But it's still very counterintuitive from user's perspective. You have to guess that since the most obvious option `""` doesn't work, then escaped quotes will be eventually interpreted as empty value. 
I don't know - maybe there is some internal deeper reasons why just `""`. I want to make a point that at least one user has with such thing problem and I don't know if it's expected or not but it's weird that this command differ for different platforms.

**Comment by navba-MSFT** [comment]
@Kakaranish Thanks for getting back. Due to a known issue in PowerShell, some extra escaping rules apply. For more information, see [Quoting issues with PowerShell](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md).

To use quotation marks and escape characters with Azure CLI command on powershell and avoid unanticipated results refer this article: https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#use-quotation-marks-in-parameters
