### ISSUE TITLE
Remove bugs right now 

### ISSUE THREAD

**Issue by KimberlWilliams** [Azure/azure-cli#26140]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please provide detailed CLI command and error log.

**Comment by SaurabhSharma-MSFT** [comment]
@KimberlWilliams As mentioned above can you please provide the error log.

**Comment by SaurabhSharma-MSFT** [comment]
@KimberlWilliams We will now proceed to close this thread as we haven't heard back. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
