### ISSUE TITLE
az network cli to support Cloud HSM resource type

### ISSUE THREAD

**Issue by amitdwivedi2006** [Azure/azure-cli#26152]
Hi Team,
We are from Azure Cloud HSM team. Our RP (currently under Private Preview) supports Private Endpoints with all the supported operations (Approve/Reject/Disconnect/Get/List etc). We need your help to support Cloud HSM resource type into Az Network CLI. Our details are as followed:
Resource Type: “Microsoft.HardwareSecurityModules/cloudHsmClusters”
Supported API version: “2022-08-31-preview”
Please let me (amdwive@microsoft.com) know if you need any further information from our side.
Thank You!

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
Resolved by https://github.com/Azure/azure-cli/pull/26235.
