### ISSUE TITLE
`az storage container generate-sas` creates incorrectly urlencoded token

### ISSUE THREAD

**Issue by michael-fritzsch** [Azure/azure-cli#26151]
## Related command
Generate SAS token for storage container (partly redacted by some `xxx` characters):
```
az storage container generate-sas --permissions l --account-name xxx --name xxx --start "2023-04-14T10:15:00Z" --expiry "2023-04-14T11:50:00Z" --account-key xxx -o tsv
```

## Describe the bug
The generated token is incorrectly urlencoded. For example, I cannot use it with `azcopy`.

Generated token (partly redacted by some `...` characters):
```
st=2023-04-14T10%3A15%3A00Z&se=2023-04-14T11%3A50%3A00Z&sp=l&sv=2021-06-08&sr=c&sig=...G/iwF...UE%3D
```

For comparison, a working token created in the Azure Portal is formatted like this:
```
sp=l&st=2023-04-14T10:49:38Z&se=2023-04-14T11:49:38Z&sv=2021-12-02&sr=c&sig=AB...%2B...%2FTp...c%3D
```

## Expected behavior
* Timestamps: colon characters (`:`) should not be urlencoded
* Signature: special characters (e.g. `/`, `+`) should be urlencoded

The only somehow related issue I found is https://github.com/Azure/azure-cli/issues/9072.

## Environment Summary
```
Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35, Ubuntu 22.04.2 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.47.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by julianfbeck** [comment]
Any updates on this issue?

**Comment by michael-fritzsch** [comment]
Hi @yonzhan, thanks a lot for looking at this issue. I would consider this to be more of a bug than a feature request. What do you think?

**Comment by cjl36** [comment]
Any updates on this? Seeing the same issue when trying to generate a SAS token to use in azcopy sync.

**Comment by calvinhzy** [comment]
Sorry for the late reply. 
Tried the latest version of CLI 2.52.0 and azcopy 10.20.1 
Currently tried both the sas token generated by the latest version of CLI and urlencoding the token again with `azcopy copy` and both worked. The example operation tried is to download everything in the container which requires both the list and read permissions. Which azcopy command and permission combinations are you currently trying to use? @michael-fritzsch @julianfbeck @cjl36 

![image](https://github.com/Azure/azure-cli/assets/17182306/9ac7496a-10e9-4365-9570-8e68ea2b806d)
![image](https://github.com/Azure/azure-cli/assets/17182306/c03eb6b8-11a0-446d-baef-271225fcf4b1)

**Comment by michael-fritzsch** [comment]
Hi @calvinhzy,

thanks for reaching out regarding this potential bug and for trying to reproduce it. Let's compare our results...

> Tried the latest version of CLI 2.52.0 and azcopy 10.20.1

My setup is as follows:

```bash
michael@ ~ $ az --version
azure-cli                         2.52.0

core                              2.52.0
telemetry                          1.1.0
    <...further output cutted...>

michael@ ~ $ azcopy --version
azcopy version 10.20.1
```

> Currently tried both the sas token generated by the latest version of CLI and urlencoding the token again with `azcopy copy` and both worked.

What do you mean by "urlencoding the token with `azcopy copy`"? What exactly did you do? The screenshot is cropped, so I can't see the whole command you executed.

I do the following to reproduce above error, which still exists on the current versions:

```bash
michael@ ~ $ cat az-cli-signature-test.sh
#!/bin/bash

set -x

az --version

SAS=`az storage container generate-sas --account-name xxx --name xxx --start "2023-09-19T11:00:00Z" --expiry "2023-09-19T12:00:00Z" --account-key xxx -o tsv`

azcopy --version

azcopy copy "https://xxx.blob.core.windows.net/<path to file>/?$SAS" . --recursive
```

Above command creates a SAS token where special characters (e.g. the colon symbol `:` in the time component) are urlencoded, when they actually should not be. Your screenshot also contains such a incorrectly formatted token, which makes me wonder how you have been able to use that token, while I am not. Specifically, all `%3A` should be output as `:`. This seems to be the correct format of a SAS token, which is also created using Azure Portal.

> ![image](https://github.com/Azure/azure-cli/assets/15315366/f86e9f14-922b-40e7-a407-76ff5b20cfc6)

@calvinhzy, would you mind to paste the complete commands you were executing and could you please try to reproduce the issue again with the commands I pasted above?

**Comment by calvinhzy** [comment]
The missing piece in the command that you tried is that it does not specify the permission given to the sas SAS=`az storage container generate-sas --account-name xxx --name xxx --start "2023-09-19T11:00:00Z" --expiry "2023-09-19T12:00:00Z" --account-key xxx -o tsv` If you use the portal to generate, it also requires specifying the permission allowed. 
![image](https://github.com/Azure/azure-cli/assets/17182306/3e7b274b-e097-4d67-8996-8f78e6c415f2)
You need to specify `--permissions rl`. Urlencoding should not be the issue here. Please give it a try with `--permissions rl` @michael-fritzsch 
![image](https://github.com/Azure/azure-cli/assets/17182306/01fa5943-e6da-4083-951a-f10c51ffd36d)
The previous screenshot was previously cutoff because of security concerns, please give it a try.

**Comment by michael-fritzsch** [comment]
Hi @calvinhzy,

thanks for checking again. I added `--permissions rl` and still get the same error. The error message is `403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.`, which indicates that the signature is malformed.

Full output of `azcopy`:

```bash
michael@ ~ $ azcopy copy 'https://xxx.blob.core.windows.net/<some path>/test.txt/?st=2023-09-20T12%3A00%3A00Z&se=2023-09-20T13%3A00%3A00Z&sp=rl&sv=2022-11-02&sr=c&sig=Eyo9AWSMijB6nyBG%2B%2Bt<removed a few characters>fwTA%3D' . --recursive
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.15.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature., Details: (none)
   HEAD https://xxx.blob.core.windows.net/<some path>/test.txt?se=2023-09-20t13%3A00%3A00z&sig=-REDACTED-&sp=rl&sr=c&st=2023-09-20t12%3A00%3A00z&sv=2022-11-02&timeout=901
   User-Agent: [AzCopy/10.20.1 Azure-Storage/0.15 (go1.19.12; linux)]
   X-Ms-Client-Request-Id: [b214c13e-bd25-48be-599a-b6fc18c0ded9]
   X-Ms-Version: [2020-10-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Date: [Wed, 20 Sep 2023 12:11:35 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [90b5b0ce-501e-0044-39bb-eb1709000000]


.
```

As I see that you run the commands in Windows, I also tried the same thing in Windows, which led to the same error. One thing I noticed is that you do not pass the parameter `--account-key` to azure-cli. If I run `az storage container generate-sas` without that parameter, I get an error, while you can use it without. Is there maybe something differently configured on your storage account or container compared to mine?

Anyhow, the signature format is different compared to the one created by Azure Portal, isn't it? And the error message states that the signature is malformed. This is why I think that the signature is somehow incorrectly generated.

Searching for a definition how a SAS token should look like, I found this: https://github.com/uglide/azure-content/blob/master/articles/storage/storage-dotnet-shared-access-signature-part-1.md. The example given there also has urlencoded timestamp and states that the signature part `sig=` has to be urlencoded. A SAS token created by Azure Portal (which works for me) has non-urlencoded timestamps. So things are not really clear. Are you aware of a valid SAS token specification?

Would you mind pasting the SAS token of your example to have me test it as well? Copy/paste is mostly nicer for others compared to screenshots ;) I would really like to reproduce your working example as well.

**Comment by calvinhzy** [comment]
I will need to look into the sas token urlencode standard. I did indeed find different implementations for the sas token urlencoding, CLI uses the [Python SDK](https://github.com/Azure/azure-sdk-for-python/blob/7abd04076bf3978057aa891e6fe8b2b3677a492f/sdk/storage/azure-storage-blob/azure/storage/blob/_shared_access_signature.py#L301) under the hood and it encodes everything but '/'.  In the mean time, please try this sas token generated with the current CLI version and see if there is anything different from your input
`az storage container generate-sas --permissions rl --account-name satestsasencode --name container1 --start "2023-04-14T10:15:00Z" --expiry "2024-04-14T11:50:00Z" -o tsv`
`st=2023-04-14T10%3A15%3A00Z&se=2024-04-14T11%3A50%3A00Z&sp=rl&sv=2022-11-02&sr=c&sig=7CisQYKHu8LGzF5eRfBxsVVb4IDxdzxrg9gur8Vk5E8%3D`
` azcopy copy "https://satestsasencode.blob.core.windows.net/container1?st=2023-04-14T10%3A15%3A00Z&se=2024-04-14T11%3A50%3A00Z&sp=rl&sv=2022-11-02&sr=c&sig=7CisQYKHu8LGzF5eRfBxsVVb4IDxdzxrg9gur8Vk5E8%3D" ./testazcopywithsas --recursive`
![image](https://github.com/Azure/azure-cli/assets/17182306/fe8cf818-7d93-45eb-b749-4f7307893933)
![image](https://github.com/Azure/azure-cli/assets/17182306/cc8cebd2-31d7-4c69-8ce5-b7b158cbca56)

**Comment by michael-fritzsch** [comment]
Hi @calvinhzy,

thanks for providing above details.

I was able to use `azcopy` with the signature you provided (I could use it to download `container1`). As this signature contains the datetime parts being urlencoded, this does not seem to be the actual issue.

Digging deeper, I realized the following:
**For the parameter `--account-key`, you have to pass the actual key (cryptographic key)** and not just the name of the key (e.g. `key1`), what I was doing all the time.

Thanks a lot for your help and for going through multiple iterations, @calvinhzy! ✌️ 

Maybe you can enlighten me, why you can generate a SAS token without passing `--account-key`? I get an error when running `az storage container generate-sas` without this parameter.

**Comment by calvinhzy** [comment]
Hi @michael-fritzsch for storage operations, CLI queries the account key for you if the logged in user has the required permissions and if --account-key is not provided like this https://github.com/Azure/azure-cli/blob/0a62d499ac898dcc9227e055ba48cf7c44ccbd0c/src/azure-cli/azure/cli/command_modules/storage/_validators.py#L212  A sas token can also be provided instead of the account-key. https://github.com/Azure/azure-cli/blob/0a62d499ac898dcc9227e055ba48cf7c44ccbd0c/src/azure-cli/azure/cli/command_modules/storage/_validators.py#L198
No problem at all. Glad I could help answer your questions.
