### ISSUE TITLE
az storage blob upload-batch unrecognized arguments

### ISSUE THREAD

**Issue by mr-matt012** [Azure/azure-cli#26150]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az storage blob upload-batch --account-name $storage_account_name -d $blob_container_name -s tempdir --validate-content true  --overwrite $overwrite --max-connections 14 --auth-mode login

**Describe the bug**

Im trying to set parameter --validate-content to true but it does not working. I've tried it from both my linux environment with the newest az cli and Cloud Shell. The result is the same. Seems it is a bug. Can you support me with resolving that issue?

ERROR: unrecognized arguments: true

**To Reproduce**
Use the given command in Azure Cloud Shell Bash (or linux environment).

**Expected behavior**

Command executes successfuly so the content of the files uploaded to Storage Account is veryfied.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mr-matt012** [comment]
Hello @yonzhan, is something heppening with my issue? I can see you tagged it as a feature-request. It's already described in the MS documentation as a full working feature.

**Comment by evelyn-ys** [comment]
@calvinhzy Can you pls take a look?

**Comment by calvinhzy** [comment]
It works by just specifying `--validate-content`, please try this. 
![image](https://github.com/Azure/azure-cli/assets/17182306/b0df7405-37b8-4f00-a64e-87faf6e34a2b)
