### ISSUE TITLE
ACR login does not update $HOME/.docker/config.json (creates relative '~' directories)

### ISSUE THREAD

**Issue by TheQueenIsDead** [Azure/azure-cli#26161]
## Describe the bug

**Command Name**
`az acr login`

**Errors:**

The acr login command places the docker config json in a filepath relative to where the command is ran, instead of the users global home directory. This means that 'docker will be unauthorized' upon a change of directory

```
# After az acr login in the ~/tmp dir, a pull is successful
~/tmp$ docker pull <n>.azurecr.io/<image>
development: Pulling from <image>
Digest: sha256:fd1a525630dbb7cac42ae52cb982eddcaeb478c5da25e59fa7507f36696c0651
Status: Image is up to date for <n>.azurecr.io/<image>
<n>.azurecr.io/<image>

# Create a new tmp dir, and change directory
~/tmp$ mkdir ../tmp2
~/tmp$ cd ../tmp2

# See that the previously successful docker pull command fails
~/tmp2$ docker pull <n>.azurecr.io/<image>
Error response from daemon: Head "https://<n>.azurecr.io/v2/<image>/manifests/<tag>": unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```
# Create a new directory, nothing in it
~$ mkdir ./tmp
~$ cd tmp/
~/tmp$ ls -la
total 8
drwxrwxr-x  2 user user 4096 Apr 17 08:31 .
drwxr-xr-x 76 user user 4096 Apr 17 08:31 ..

# Login
~/tmp$ az acr login -n {}
Login Succeeded

# Observe a new '~' directory with a `.docker` folder
~/tmp$ ls -la 
total 12
drwxrwxr-x  3 user user 4096 Apr 17 08:31  .
drwxr-xr-x 76 user user 4096 Apr 17 08:31  ..
drwx------  3 user user 4096 Apr 17 08:31 '~'
~/tmp$ ls -la ./~
total 12
drwx------ 3 user user 4096 Apr 17 08:31 .
drwxrwxr-x 3 user user 4096 Apr 17 08:31 ..
drwx------ 2 user user 4096 Apr 17 08:31 .docker

# Show that this is different to my actual home directory
~/tmp$ ls -la ~
total 44588
drwxr-xr-x 76 user user     4096 Apr 17 08:31 .
drwxr-xr-x  3 root  root      4096 May 11  2021 ..
drwxrwxr-x  3 user user     4096 Oct 12  2021 .3T
drwxrwxr-x  2 user user     4096 Nov  4  2021 .android
drwxrwxr-x  4 user user     4096 Sep 16  2021 .ansible
```

## Expected Behavior

I would expect the credentials to be loaded into /home/user/.docker/config.json instead of $PWD/.docker/config.json so that docker commands are authenticated regardless of working directory. 

## Environment Summary
```
Linux-5.19.0-38-generic-x86_64-with-glibc2.35, Ubuntu 22.04.2 LTS
Python 3.10.5
Installer: DEB

azure-cli 2.40.0 *
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by TheQueenIsDead** [comment]
This is still an issue on the latest version:
```$ az version
{
  "azure-cli": "2.47.0",
  "azure-cli-core": "2.47.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
```

**Comment by SouvickDutta** [comment]
I'm facing the same problem too.
```
$ az --version
azure-cli                         2.47.0

core                              2.47.0
telemetry                          1.0.8

Extensions:
bastion                            0.2.3
```

**Comment by junczhu** [comment]
Hi @TheQueenIsDead @SouvickDutta,
Please help check if you can reproduce with the docker cli.

Reference: https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/custom.py#L248

**Comment by hero-david** [comment]
Ah crazy, I did not realise that it just passed through to Docker. Thanks for showing me that.

Yes, I can confirm that this behavior happens when retrieving my token and logging in via:
```console
ACR_NAME="xxx"
ACR_TOKEN=$(az acr login --name $ACR_NAME --expose-token --output tsv --query accessToken)
docker login linced.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p $ACR_TOKEN
```

I'll raise this as a ticket elsewhere, or see if I can ascertain whether this is a conscious design decision. 

Thank you for your time :+1:

**Comment by TheQueenIsDead** [comment]
Ah crazy, I did not realise that it just passed through to Docker. Thanks for showing me that.

Yes, I can confirm that this behavior happens when retrieving my token and logging in via:
```console
ACR_NAME="xxx"
ACR_TOKEN=$(az acr login --name $ACR_NAME --expose-token --output tsv --query accessToken)
docker login linced.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p $ACR_TOKEN
```

I'll raise this as a ticket elsewhere, or see if I can ascertain whether this is a conscious design decision. 

Thank you for your time :+1:
