### ISSUE TITLE
Webapp up does not work in 2.47.0

### ISSUE THREAD

**Issue by JanDammansWeDoIt** [Azure/azure-cli#26173]
## Describe the bug
I've updated my azure cli to 2.47.0 and now the webapp up commands does not work anymore. My pipeline which uses azure cli 2.43.0 is still working so it is not related to the code

**Command Name**
`az webapp up`

**Errors:**
```
.../Backend should contain only one .csproj file
```

## To Reproduce:

- Go to the solution folder of the dotnet folder
- `az webapp up --plan my-plan --name my-app --os-type linux --location northeurope --resource-group my-rg --runtime "DOTNETCORE:7.0" --sku B1`

## Expected Behavior
Upload the project to the web app

## Environment Summary
```
macOS-13.3.1-arm64-arm-64bit, Darwin 22.4.0
Python 3.10.11
Installer: HOMEBREW

azure-cli 2.47.0

Extensions:
rdbms-connect 1.0.4

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by seligj95** [comment]
Closing due to no response.
