### ISSUE TITLE
az login --service-principal should allow for tenantId in --tenant parameter

### ISSUE THREAD

**Issue by rguthriemsft** [Azure/azure-cli#2617]
az login allows you to pass guids for user parameter but not tenant.  this command should allow you to pass the tenant id to the --tenant parameter similar to how old azure cli worked.

az login -u {client ID} -p {secret} -t {tenant id}

**Comment by yugangw-msft** [comment]
@rguthriemsft. could you please double check? I am using tenant-id frequently.

**Comment by yugangw-msft** [comment]
Please reopen if you see the tenant_id no longer works
