### ISSUE TITLE
How do I pass a sas token into a function app settings?

### ISSUE THREAD

**Issue by am8448** [Azure/azure-cli#26179]
I am using Azure CLI on powershell.

I have the SAS token in a variable and I get this error everytime I try to set an application setting:
```
'sp' is not recognized as an internal or external command,
operable program or batch file.
'spr' is not recognized as an internal or external command,
operable program or batch file.
'sv' is not recognized as an internal or external command,
operable program or batch file.
'sr' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.
```
My command is: `az functionapp config appsettings set --name $(appName) --resource-group ${{parameters.resourceGroup}} --settings sasUrl="$sas"` I've tried escaping the "&" but that as not helped: `$sas.Replace("&","^&")`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06e69fb3-f10c-98ac-0506-35d02f2a7481
* Version Independent ID: ad86610e-e20d-2c96-80fd-61c3d6e7f9ff
* Content: [az functionapp config appsettings](https://learn.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/functionapp/config/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/functionapp/config/appsettings.yml)
* Service: **azure-functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by kaibocai** [comment]
Hey can you try `az functionapp config appsettings set --name $(appName) --resource-group ${{parameters.resourceGroup}} --settings "sasUrl=$sas"`

**Comment by am8448** [comment]
> Hey can you try `az functionapp config appsettings set --name $(appName) --resource-group ${{parameters.resourceGroup}} --settings "sasUrl=$sas"`

Hi that was what it was initially, and it resulted in the same error. The thing is I'm sure this used to work at one point too.

**Comment by kaibocai** [comment]
so you have `$sas` set as a variable in your PowerShell terminal I assume, I will try this out and keep you update thanks.

**Comment by am8448** [comment]
> so you have `$sas` set as a variable in your PowerShell terminal I assume, I will try this out and keep you update thanks.

That's correct. This is on Azure Devops, and earlier in the same task/terminal, I am generating the token and storing it in a variable. I then am trying to consume that variable as a function app setting.

**Comment by am8448** [comment]
Is there any update to this?

**Comment by kamperiadis** [comment]
Hello @am8448 To pass a SAS token as an app setting, make sure that you set the sasToken value between single quotes and double quotes:
$sasToken='"<sasTokenValue>"'

Then you should be able to run the following successfully: `az functionapp config appsettings set -g <resourceGroup> -n <functionAppName> --settings sasToken=$sasToken`

Please let us know if you still have any issues/questions or if we can mark this as resolved. Thank you.
