### ISSUE TITLE
az ad sp create-for-rbac fails if password param specified

### ISSUE THREAD

**Issue by paselem** [Azure/azure-cli#2618]
I'm running the following command:

az ad sp create-for-rbac --password "@bcd3F!!!" -n "http://myNewCoolAppUrl"

and get the following error:
[Errno 2] No such file or directory: '@bcd3F!!!'
Traceback (most recent call last):
  File "C:\Users\paselem\AppData\Roaming\Python\Python36\site-packages\azure\cli\core\application.py", line 236, in _expand_file_prefix
    return '='.join([arg_split[0], Application._maybe_load_file(arg_split[1])])
IndexError: list index out of range

During handling of the above exception, another exception occurred:
...

When changing the password to remove the '@' as the first character it then succeeds. Took me a while to figure that out. I feel the error message could be much more descriptive.

**Comment by yugangw-msft** [comment]
The `@` is sort of a reserved word in CLI, implying you are loading content from a file.
//CC: @twitchax, we need some document coverage to call this behavior.
The `@` gets handled at core level, so there is nothing this command can do. Closing
