### ISSUE TITLE
Support Azure Databricks workspace update with new properties

### ISSUE THREAD

**Issue by msaranga** [Azure/azure-cli#26184]
### Related command

Azure Databricks service support workspace update in Az CLI
https://learn.microsoft.com/en-us/cli/azure/databricks/workspace?view=azure-cli-latest#az-databricks-workspace-update-optional-parameters

Resource provider: "Microsoft.Databricks/workspaces"

Description of feature or work requested. Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.

Azure Databricks RP allows customers to create a workspace with below properties, but they are immutable.

- PublicNetworkAccess
- requiredNsgRules
- enableNoPublicIp
- storageAccountSkuName

Starting from API version 2022-04-01-preview, Customer can modify above properties.

Can we add additional support to our existing workspace update CLI commands?
https://learn.microsoft.com/en-us/cli/azure/databricks/workspace?view=azure-cli-latest#az-databricks-workspace-update-optional-parameters

Minimum API version required. What is the minimum API version of your service required to implement your feature?
**2022-04-01-preview**

Swagger link. Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/databricks/resource-manager/Microsoft.Databricks/stable/2023-02-01/databricks.json

Target date. If you have a target date for releasing this feature/work, please provide it. While we can't guarantee these dates, it will help us prioritize your request against other requests.
As early as possible. 

Where do you want the feature to locate? A command module or an extension? Here is a [Comparision]
command module

Status of the service. Is it in preview or GA? : GA

Examples of the feature. Usually REST API specs repo should contain examples. An independent documentation or tutorial is also 

API: https://management.azure.com/subscriptions/{SubId}/resourceGroups/{RGName}/providers/Microsoft.Databricks/workspaces/{name}?api-version=2023-02-01

Request Payload
{
    "properties": {
        **"publicNetworkAccess": "Disabled",
        "requiredNsgRules": "NoAzureDatabricksRules",**        
        "managedResourceGroupId": "ABC",
        "parameters": {            
            **"enableNoPublicIp": {
                "type": "Bool",
                "value": true
            }**,
            **"storageAccountSkuName": {
                "type": "String",
                "value": "Standard_GRS"
            }**
        }
    },
    "sku": {
        "name": "premium"
    },
    "location": "<ARMLocation>"
}

Prerequisite to use this feature. Whitelisting subscription? Registering the feature for subscription? Is it available in public Azure?
No

### Resource Provider

Microsoft.Databricks/workspaces

### Description of Feature or Work Requested

feature request to update existing properties of databricks workspace.

Azure Databricks RP allows customers to create a workspace with below properties, but they are immutable and can only be created during workspace creation.

- PublicNetworkAccess
- requiredNsgRules
- enableNoPublicIp
- storageAccountSkuName

Starting from API version 2022-04-01-preview, Customer can modify above properties using same ARM Template.

https://learn.microsoft.com/en-us/cli/azure/databricks/workspace?view=azure-cli-latest#az-databricks-workspace-update-optional-parameters

https://learn.microsoft.com/en-us/azure/databricks/administration-guide/workspace/workspace-storage-redundancy

### Minimum API Version Required

2022-04-01-preview

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/databricks/resource-manager/Microsoft.Databricks/stable/2023-02-01/databricks.json

### Request Example

API: https://management.azure.com/subscriptions/{SubId}/resourceGroups/{RGName}/providers/Microsoft.Databricks/workspaces/{name}?api-version=2023-02-01

Request Payload
{
    "properties": {
        **"publicNetworkAccess": "Disabled",
        "requiredNsgRules": "NoAzureDatabricksRules",**        
        "managedResourceGroupId": "ABC",
        "parameters": {            
            **"enableNoPublicIp": {
                "type": "Bool",
                "value": true
            }**,
            **"storageAccountSkuName": {
                "type": "String",
                "value": "Standard_GRS"
            }**
        }
    },
    "sku": {
        "name": "premium"
    },
    "location": "<ARMLocation>"
}

### Target Date

2022-05-30

### Additional context

Kindly Please let us know if you need further information.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
