### ISSUE TITLE
Fix 'az sig update --soft-delete-policy'

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#26185]
Currently, when a sig is created without soft-delete-policy, user should be able to create a new soft-delete-policy from update. But this path is not working right now.

From this pr: https://github.com/Azure/azure-cli/pull/19569

you can see in src/azure-cli/azure/cli/command_modules/vm/custom.py
    if soft_delete is not None:
        gallery.**soft_delete_policy**.is_soft_delete_enabled = soft_delete

the gallery .'soft_delete_policy' can be null, and this code execution can be wrong, we need a quick fix for it.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
