### ISSUE TITLE
SSL Error: The certificate for https://packages.microsoft.com is expired.

### ISSUE THREAD

**Issue by MichaelJRogersGM** [Azure/azure-cli#26182]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

Using any packages on  https://packages.microsoft.com/  generates a SSL error.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by prng-dev** [comment]
The certificate for https://packages.microsoft.com is expired.

packet@ip-10-255-254-4:~/tmp$ get-cert.sh packages.microsoft.com
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            33:00:38:cd:96:ef:e8:07:13:f5:d9:78:97:00:00:00:38:cd:96
        Signature Algorithm: sha384WithRSAEncryption
        Issuer: C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 05
        Validity
            Not Before: Apr 23 18:00:41 2022 GMT
            Not After : Apr 18 18:00:41 2023 GMT
        Subject: C = US, ST = WA, L = Redmond, O = Microsoft Corporation, CN = packages.microsoft.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:b8:ce:cd:ad:37:98:ea:6c:0b:f0:37:1f:01:04:
                    82:f5:a7:5a:4a:8a:a2:b9:dc:da:33:8b:ca:37:ac:
                    10:1e:51:4b:a2:54:51:80:a9:7b:a7:6c:ec:f9:1f:
                    41:ca:71:ec:b5:f4:c8:5a:65:6d:01:8f:e1:59:35:
                    23:ee:23:6b:d2:1e:36:bf:d5:51:c1:b5:b7:55:55:
                    2f:96:84:b5:85:eb:76:93:e1:b8:9d:a0:a8:a0:c9:
                    e5:6a:4b:b8:75:1b:65:7d:f2:5e:ec:21:1f:82:ac:
                    d3:63:bd:86:d2:24:3b:0b:fd:88:a4:fd:a9:fc:49:
                    d5:21:b4:a8:bd:4f:5e:65:c7:37:55:8f:3c:63:3d:
                    6a:00:15:47:f5:1a:2f:6b:64:4b:b1:58:7d:e3:50:
                    e1:15:54:6a:3c:69:0f:79:24:47:1b:20:17:b0:37:
                    8c:10:6e:18:1e:92:4a:8e:18:1b:5d:8c:3e:7b:21:
                    65:c8:22:ca:57:83:cb:4f:a7:40:f2:64:7a:77:75:
                    6f:5e:ea:9d:7c:aa:be:94:26:96:45:41:3a:e7:82:
                    a5:74:b6:db:e3:25:05:09:87:f7:32:1b:4c:2f:69:
                    54:da:7b:c0:b8:8f:61:a2:31:4c:de:c7:4a:97:51:
                    29:dc:67:0b:26:f7:e8:21:2f:23:78:e3:9c:8c:2f:
                    ce:cd
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            CT Precertificate SCTs:
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : AD:F7:BE:FA:7C:FF:10:C8:8B:9D:3D:9C:1E:3E:18:6A:
                                B4:67:29:5D:CF:B1:0C:24:CA:85:86:34:EB:DC:82:8A
                    Timestamp : Apr 23 18:10:42.976 2022 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:44:02:20:77:D2:92:B3:4F:06:62:9C:3A:8D:FF:81:
                                BB:54:78:4B:5B:E0:44:CD:8F:7D:C7:47:4F:87:58:3B:
                                BB:EB:0D:50:02:20:0B:EC:8E:5F:7E:B0:4C:36:6E:E0:
                                F6:4A:AC:1E:F3:84:62:26:81:79:27:E8:4F:2F:33:B2:
                                84:D1:BA:22:89:46
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : 7A:32:8C:54:D8:B7:2D:B6:20:EA:38:E0:52:1E:E9:84:
                                16:70:32:13:85:4D:3B:D2:2B:C1:3A:57:A3:52:EB:52
                    Timestamp : Apr 23 18:10:42.685 2022 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:44:02:20:45:62:29:76:D7:E3:10:D4:EA:87:14:A2:
                                9E:1E:C4:7F:1E:1F:49:94:0F:DC:B0:C6:4F:F7:2C:1B:
                                75:F3:D4:E7:02:20:5B:7D:7B:35:01:E2:4D:9C:57:D4:
                                7F:2E:0D:93:F3:19:4A:F5:21:D1:B9:78:D9:A7:32:ED:
                                92:46:D1:6B:3F:17
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : B3:73:77:07:E1:84:50:F8:63:86:D6:05:A9:DC:11:09:
                                4A:79:2D:B1:67:0C:0B:87:DC:F0:03:0E:79:36:A5:9A
                    Timestamp : Apr 23 18:10:42.971 2022 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:45:02:20:49:0C:5E:6E:F9:0F:7F:45:B1:3F:F6:62:
                                55:3D:64:BE:69:FF:72:D2:FF:24:2E:73:48:44:65:C4:
                                24:2F:D3:D0:02:21:00:98:5D:19:1D:6F:DC:C6:D4:51:
                                93:21:81:1E:2A:60:72:F4:02:86:24:A0:3B:AB:8F:6A:
                                D1:22:74:13:EE:CB:E4
            1.3.6.1.4.1.311.21.10:
                0.0
..+.......0
..+.......
            1.3.6.1.4.1.311.21.7:
                0-.%+.....7.........F...........]...i...>..d..%
            Authority Information Access:
                CA Issuers - URI:http://www.microsoft.com/pkiops/certs/Microsoft%20Azure%20TLS%20Issuing%20CA%2005%20-%20xsign.crt
                OCSP - URI:http://oneocsp.microsoft.com/ocsp
            X509v3 Subject Key Identifier:
                AD:3B:CD:EC:93:BD:6C:0D:41:D6:CB:DD:B2:E0:99:0E:B4:E8:B6:AA
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Data Encipherment
            X509v3 Subject Alternative Name:
                DNS:packages.microsoft.com, DNS:apt-mo.trafficmanager.net
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 CRL Distribution Points:
                Full Name:
                  URI:http://www.microsoft.com/pkiops/crl/Microsoft%20Azure%20TLS%20Issuing%20CA%2005.crl
            X509v3 Certificate Policies:
                Policy: 1.3.6.1.4.1.311.76.509.1.1
                  CPS: http://www.microsoft.com/pkiops/Docs/Repository.htm
                Policy: 2.23.140.1.2.2
            X509v3 Authority Key Identifier:
                C7:B2:9C:7F:1C:E3:B8:5A:EF:E9:68:1A:A8:5D:94:C1:26:52:6A:68
            X509v3 Extended Key Usage:
                TLS Web Client Authentication, TLS Web Server Authentication
    Signature Algorithm: sha384WithRSAEncryption
    Signature Value:
        8a:77:7b:ef:29:83:30:b6:1e:da:01:0a:ef:24:1c:7a:06:52:
        95:bb:e7:6c:89:fc:d9:e4:99:f8:e6:f5:34:56:41:8b:bb:89:
        46:52:d6:2d:9d:0e:e8:38:d9:20:4e:0e:67:c6:47:d5:12:c6:
        a2:c4:45:b5:34:5b:c5:20:2d:e9:4b:9f:b6:0b:f8:3d:73:39:
        5d:f2:41:d8:f0:69:00:94:03:4a:05:8a:e5:0e:73:d2:a4:84:
        4a:eb:cd:e6:0a:1d:0b:0a:05:bf:e7:b9:f0:94:8e:c2:9f:f7:
        a8:9d:ad:3c:d5:69:25:34:72:8b:76:96:34:35:74:fc:67:f4:
        b4:32:96:0a:d9:aa:8b:60:4d:1d:fb:02:b5:9c:f0:3b:88:0d:
        8b:e5:c7:4f:87:4b:c7:10:19:8d:6b:78:02:16:3e:bf:d3:b4:
        f4:20:4a:3d:37:2b:89:38:e1:4a:d3:e5:73:6a:0e:04:76:e2:
        b5:c1:71:72:d2:7f:d0:e0:4d:96:ba:6a:0c:2d:c3:42:31:75:
        9c:6a:7b:c7:ea:55:e5:11:f7:c0:e0:83:a9:25:56:7f:a8:3b:
        f6:b3:4b:12:68:10:3e:53:8b:81:a2:91:49:f4:c2:c6:c4:2e:
        37:46:cf:f1:1a:2f:82:76:e3:2d:66:06:7a:0f:45:f1:6e:1a:
        42:64:3e:02:95:5c:35:9e:21:a6:4f:72:48:87:f9:8e:fe:57:
        0e:7a:bd:0e:64:24:f2:21:d5:60:13:18:ff:a7:67:dc:86:eb:
        6e:56:5e:37:cf:99:46:0d:0d:0c:f6:82:06:c7:28:35:26:94:
        4b:8d:1d:34:55:54:0f:ce:05:6c:9a:b4:9b:e7:10:b6:8c:d0:
        b3:3f:67:44:17:fd:41:9a:34:43:f1:ff:64:46:eb:71:d2:80:
        08:57:f1:cd:23:93:71:84:cb:eb:7c:55:99:47:7c:4c:81:01:
        35:c6:8b:af:49:51:d4:6f:60:7e:4a:8c:38:ac:33:93:15:98:
        a2:50:4b:47:aa:2e:d1:02:2a:bd:21:d9:06:0d:a6:12:51:ed:
        b2:12:33:77:73:5a:43:ab:f3:7f:c0:0e:05:4d:6d:e1:f2:5d:
        8a:7f:24:f3:4b:e1:00:e2:5a:f2:d3:52:1d:08:f4:82:27:3d:
        0a:c8:b5:1f:0c:0f:c4:15:39:10:3a:98:04:6f:a1:4d:7e:be:
        03:57:fa:35:4a:58:d1:9c:dd:80:8b:4e:01:67:c8:eb:62:67:
        e5:65:52:33:bf:a0:91:f9:af:b8:dd:ae:30:cc:07:5b:5f:f3:
        aa:db:a4:54:77:30:d2:a4:2e:b8:b4:6c:ff:50:e4:48:17:36:
        d5:cf:88:45:b1:7a:53:98
issuer=C = US, O = Microsoft Corporation, CN = Microsoft Azure TLS Issuing CA 05
CN=packages.microsoft.com
packet@ip-10-255-254-4:~/tmp$

**Comment by jiasli** [comment]
A new cert has been deployed to all mirrors of https://packages.microsoft.com/ on 2023-04-18 18:42:00 UTC. This issue has now been fixed. Please retry the operation and let us know if it works as expected.

**Comment by MichaelJRogersGM** [comment]
Thanks, that fixed it.

**Comment by somphouang** [comment]
I am having this issue, testing by running 
```
curl -i https://packages.microsoft.com
```
command works after more than 2 retry but often failed with SSL_ERROR_SYSCALL 

![image](https://github.com/Azure/azure-cli/assets/17149754/9124040f-a94a-4a02-8ecb-c53ff04abe3f)
