### ISSUE TITLE
az login hangs forever, redirects to localhost and hits ERR_CONNECTION_REFUSED in browser

### ISSUE THREAD

**Issue by luisnaranjo733** [Azure/azure-cli#26180]
## Describe the bug
az login hangs forever
1. Run az login
2. Browser window opens where I select which account I want to sign in to
3. The redirect goes to the browser in a new tab which looks like http://localhost:34541/?code=REDACTED&client_info=REDACTED&state=REDACTED&session_state=REDACTED

**Command Name**
`az login`

**Errors:**
Sign in hangs forever and never finishes

## To Reproduce:

Attempt to sign in

## Expected Behavior
Sign in succeeds

## Environment Summary
```
Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31, Ubuntu 20.04.6 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.47.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by luisnaranjo733** [comment]
Thanks!

I forgot to mention that I also cannot sign in with ```--use-device-code```
Auth succeeds in the browser but the az CLI never finds out about it

```bash
$ az login --use-device-code
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code REDACTED to authenticate.
$ az account show
Please run 'az login' to setup account.
```

**Comment by andrewegel** [comment]
I don't have a problem with `az login`, but the command `az disk update` command "hangs" for me:

```
az disk update --ids /long/path/to/disk/resource/i/know/is/accurate --set tags.keep_volume_until==...
```

Even more perplexing to me is when I add `-vvvv` or `--debug` the command fails/exits telling me that there is no `az disk update` command:

```
'update' is misspelled or not recognized by the system.

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
```

Even though `az disk update --help` shows proper switches.

```
% az version
{
  "azure-cli": "2.47.0",
  "azure-cli-core": "2.47.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
```

**Comment by bebound** [comment]
@luisnaranjo733 Can you show me the output of `az login --debug` and `az login --use-device-code --debug` when it hang.
Do you see `You have logged into Microsoft Azure!` from `http://localhost:34541/?code=REDACTED&client_info=REDACTED&state=REDACTED&session_state=REDACTED`?

@andrewegel  I can't repro. This appears to be the result of an incomplete installation. It is not related to this issue. Could you please create a new issue so we can better track it?

**Comment by luisnaranjo733** [comment]
Shared the logs privately :) Please let me know if you need anything else to assist with troubleshooting.
I can sign in with --use-device-code now but still can't sign in with the normal flow

**Comment by chloeyin** [comment]
Hey, I met the same issue today, but it rediect me to anothe port(everytime I login looks like it will redirect to different port)
![image](https://user-images.githubusercontent.com/30316518/233251521-25ee70ac-967e-437d-98da-2f53e816aeb1.png)
 http://localhost:44953/

**Comment by bebound** [comment]
More users are encountering this issue.

Since our program remains unchanged, I believe the issue may be related to WSL or the browser.

**Comment by dsteeley** [comment]
This is likely https://github.com/microsoft/WSL/issues/9947, installing the latest wsl via github releases may solve the issue.

**Comment by jiasli** [comment]
I also found a similar issue: 

- https://github.com/microsoft/WSL/issues/9805

**Comment by chloeyin** [comment]
Thanks! I use powershell to login and it works, it looks like a wsl problem. I will update my wsl and try again later.

**Comment by chloeyin** [comment]
Yes, after updating wsl to latest, it works now.

**Comment by luisnaranjo733** [comment]
Same - just updated to 1.2.5
https://github.com/microsoft/WSL/releases/tag/1.2.5

and can confirm this bug is fixed
it must have been that wsl2 bug

Should I close this issue?

**Comment by adnan-ashfaq** [comment]
I am having the same issue. Redirects me to localhost after account selection.
```
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2846
```

Azure Cli WSL
```
azure-cli                         2.48.1
core                              2.48.1
telemetry                          1.0.8
Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0
```

**Comment by MarcoFabbri-orienteed** [comment]
Same as @adnan-ashfaq here, can you reopen this issue? Thanks

**Comment by MarcoFabbri-orienteed** [comment]
Same as @adnan-ashfaq here, can you reopen this issue? Thanks

**Comment by adnan-ashfaq** [comment]
In my case, it was mismatch of MFA flow. I was working with Azure B2C AD related IaC, while my azure account in the portal was signed into different directory. Azure B2C AD has it's own MFA., so if you are logged into different directory in portal, and you are running `az login` for B2C, it would result in the above error. Make sure you're in Azure B2C AD in portal as well if you're running/testing B2C related work.

**Comment by BobLokerse** [comment]
I saw via `az --version` that I was using an older version. After upgrading it worked.
