### ISSUE TITLE
Unable to login through "az login"

### ISSUE THREAD

**Issue by RachnaKP** [Azure/azure-cli#26190]
Getting below error while using az login command :

The command failed with an unexpected error. Here is the traceback:
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /****/***/***** (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object) - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by RachnaKP** [comment]
Please update me on this

**Comment by bebound** [comment]
Duplicate of #21514
