### ISSUE TITLE
--key-type specifies invalid argument

### ISSUE THREAD

**Issue by PontiusTheBarbarian** [Azure/azure-cli#26195]
[Enter feedback here]
The `--key-type` parameter is documented as having `systemKeys` as a valid argument, the CLI returns a response for invalid argument, it should be `systemKey`.

![image](https://user-images.githubusercontent.com/33497574/233038112-ada0a75c-da53-4361-96a8-79f375186aa9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4246edfd-394e-4d61-360b-b95173159995
* Version Independent ID: e5365558-9b77-c72f-7b6d-f42e36a0a52c
* Content: [az functionapp keys](https://learn.microsoft.com/en-us/cli/azure/functionapp/keys?view=azure-cli-latest#az-functionapp-keys-set)
* Content Source: [latest/docs-ref-autogen/functionapp/keys.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/functionapp/keys.yml)
* Service: **azure-functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@PontiusTheBarbarian what's the cli version you are using.  I am using Azure CLI 2.47 and it asks me to enter "systemKeys"
![image](https://user-images.githubusercontent.com/38112130/234128743-8f9dbb13-ce9a-4ff0-b790-c6e645e2a24f.png)
Please upgrade your CLI and check again. Thanks.
