### ISSUE TITLE
Getting error while running az login --identity in ML compute: ImportError: cannot import name 'PersistenceError' from 'msal_extensions.persistence'

### ISSUE THREAD

**Issue by TaposwaniKarwa** [Azure/azure-cli#26198]
<img width="585" alt="Terminal-az login_2" src="https://user-images.githubusercontent.com/131268015/233080770-167b0dd3-5041-4f46-8632-7471e5e0b690.png">

## Describe the bug
Getting error while running az login --identity in ML compute
As advised in following Github issue link: https://github.com/Azure/azure-cli/issues/22325
We tried upgrading azure identity version from 1.7.0 to 1.12.0. But still it is not working.

**Command Name**
`az login --identity`

**Errors:**
```
ImportError: cannot import name 'PersistenceError' from 'msal_extensions.persistence' (/anaconda/envs/azureml_py38/lib/python3.8/site-packages/msal_extensions/persistence.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --identity`

## Environment Summary
```
Linux-5.15.0-1035-azure-x86_64-with-glibc2.10, Ubuntu 20.04.6 LTS
Python 3.8.5
Installer: PIP

azure-cli 2.47.0
azure identity 1.12.0

Extensions:
azure-cli-ml 1.41.0
ml 2.5.0

Dependencies:
msal 1.21.0
azure-mgmt-resource 21.2.1
```

**Comment by jiasli** [comment]
In additional to https://github.com/Azure/azure-cli/issues/22325#issuecomment-1371717240, downgrading `azure-identity` will downgrade `msal-extensions` because `azure-identity` has an upper bound for `msal-extensions`. On the contrary, upgrading `azure-identity` won't affect `msal-extensions` since new `azure-identity` is compatible with old versions of `msal-extensions`.

Could you try to upgrade `msal-extensions` to the latest version as well?

**Comment by TaposwaniKarwa** [comment]
@jiasli Could you please provide an update on the issue or any other suggestions to try.

**Comment by jiasli** [comment]
It is likely you are not installing into Azure CLI's env: `/anaconda/envs/azureml_py38/lib/python3.8/site-packages`. You may run `pip list -v` to confirm. If Azure CLI's environment has been corrupted, you need to use the `pip` of that environment to fix it.

@azureml-github, please help take a look, as installing Azure CLI into a custom python environment is not officially supported.
