### ISSUE TITLE
az acs create --orchestrator-type=kubernetes command doesnot have a output flag

### ISSUE THREAD

**Issue by saurabsa** [Azure/azure-cli#2619]
When we run: **az acs create --orchestrator-type=kubernetes --resource-group <resource-group-name> --name=<cluster-name> --dns-prefix=<cluster-dns-prefix>**, it displays an output:
_waiting for AAD role to propagate.done_

azure.cli.command_modules.acs.custom._add_role_assignment() accepts a flag to print this output but no flag is being passed to this method from acs_create().

Can a flag be added to the command to restrict the output? Shouldn't the output be logged to the logger?

**Comment by rjtsdl** [comment]
Hi @saurabsa , not sure how to proceed the request. Because --output is actually a global flag 
I am thinking to change the log level a little bit. So if --debug is supplied, we could just display. Otherwise, we don't, except it is a failure. Sounds better?

```
    --output -o                   : Output format.  Allowed values: json, jsonc, table, tsv.
                                    Default: json.
```

**Comment by saurabsa** [comment]
Hi, Yes no output unless failure works great.

**Comment by rjtsdl** [comment]
@saurabsa, I noticed that there is another direction to push. https://github.com/Azure/azure-cli/issues/2746 
Looks, people also want to get the progress message, just like this one.

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating
