### ISSUE TITLE
add support for ARM template parameters in properties format

### ISSUE THREAD

**Issue by FedorRomanov** [Azure/azure-cli#2621]
ARM template deployment accepts parameters only in JSON format, see  https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-deploy
The parameter file must be in the following format:
```
 {
   "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
   "contentVersion": "1.0.0.0",
   "parameters": {
      "storageNamePrefix": {
          "value": "contoso"
      },
      "storageSKU": {
          "value": "Standard_GRS"
      }
   }
 }
```
However, maintaining config params in JSON format has following disadvantages:

1. Lack of comments. One can’t add comments in JSON files. This is very problematic, because:
 - No way to document on why settings were set to what they are.
 - No way to add mnemonics or describe caveats.
 - No way to keep a basic ChangeLog in the config file itself, documenting which changes were made (which can be immensely useful)
2. Much more difficult to debug, as quickly commenting out a section isn’t possible.
3. Readability. JSON is readable for a data-interchange format, but not readable for a configuration file.
4. Strictness.The JSON standard is fairly strict, it means it’s more difficult to write. For example a trailing comma in objects or arrays is an error.

Please, add support for simple properties files for params, e.g
```
storageNamePrefix=contoso
storageSKU=Standard_GRS
```

**Comment by yugangw-msft** [comment]
We already support `--parameters` by taking a list of `<name>=<value>` pair. It is straightforward for you to pipe file content to it
