### ISSUE TITLE
webapp auth openid-connect add fails: Operation returned an invalid status 'Bad Request'

### ISSUE THREAD

**Issue by sh-jthorpe** [Azure/azure-cli#26221]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az webapp auth openid-connect add

**Describe the bug**

Command should add an Identity Provider to the Azure function. Instead it returns an error
**To Reproduce**

`az webapp auth openid-connect add --provider-name 'AAD B2C' --client-id '{client id}' --client-secret '{client secret}' --name '{function name}' --resource-group '{resource group}' --openid-configuration 'https://{aadb2c tenant name}.b2clogin.com/{aadb2c tenant name}.onmicrosoft.com/{user flow name}/v2.0/.well-known/openid-configuration'`

**Expected behavior**

Adds Identity Provider to AZ function

**Environment summary**

```
azure-cli                         2.47.0

core                              2.47.0
telemetry                          1.0.8

Extensions:
authV2                             0.1.2
azure-devops                      0.21.0
ssh                                1.1.3
storage-preview                    0.8.3

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\joe.thorpe\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]
```

**Additional context**

Doesn't work in UI either

**Comment by sh-jthorpe** [comment]
> Thank you for opening this issue, we will look into it.

Thanks. I'm confirming it still occurs on 2.47.0, but i expect it will.

**Comment by sh-jthorpe** [comment]
> Hi @sh-jthorpe,
> 
> 2.27.2 is not the latest Azure CLI(2.47.0).
> 
> Please upgrade to the latest Azure CLI version by following https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.

Same issue occurs on 2.47.0

**Comment by sh-jthorpe** [comment]
Ok, i know what's causing it:

Here's the error, which i got from adding the --debug flag:
```Content: {"Code":"BadRequest","Message":"AppSetting with name 'AAD B2C_PROVIDER_AUTHENTICATION_SECRET' is not allowed.","Target":null,"Details":[{"Message":"AppSetting with name 'AAD B2C_PROVIDER_AUTHENTICATION_SECRET' is not allowed."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"04072","MessageTemplate":"AppSetting with name '{0}' is not allowed.","Parameters":["AAD B2C_PROVIDER_AUTHENTICATION_SECRET"],"Code":"BadRequest","Message":"AppSetting with name 'AAD B2C_PROVIDER_AUTHENTICATION_SECRET' is not allowed."}}],"Innererror":null}```

Changing the parameter name from 'AAD B2C' to something else, like 'B2C' works. 

So, the CLI could probably provide a more meaningful error without getting into debug logs, but that's a pretty minor issue.

**Comment by seligj95** [comment]
Thanks for the feedback, we will review
