### ISSUE TITLE
[az databricks workspace] New support in Managed Services CMK and Managed Disks CMK implementation

### ISSUE THREAD

**Issue by scottmacchia-msft** [Azure/azure-cli#26236]
**Related command**
az databricks workspace create
az databricks workspace update

**Feature description**
The CLI implementation of Managed Disks CMK and Managed Services CMK for Azure Databricks workspaces is not accurate (https://msazure.visualstudio.com/One/_workitems/edit/16433527?src=WorkItemMention&src-action=artifact_link).

According to current implementation, all three forms of CMK (DBFS, Managed Disks, Managed Services) will always share the same key information. From the Databricks RP, we support different keys for all three forms of CMK simultaneously.

Additionally, users should be able to enable Managed Disks CMK and/or Managed Services CMK at workspace creation time.

**Current behavior**
Notice that there are no properties made available through _az databricks workspace create_ or _az databricks workspace update_ that allow user to enable Managed Disks CMK or Managed Services CMK.

**Expected behavior**
We support different keys for all three forms of CMK simultaneously.

Additionally, users should be able to enable Managed Disks CMK and/or Managed Services CMK at workspace creation time.

**Environment summary**

**Additional context**
Please see examples here:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/databricks/resource-manager/Microsoft.Databricks/stable/2023-02-01/examples/WorkspaceManagedDiskEncryptionCreate.json
https://github.com/Azure/azure-quickstart-templates/pull/13297/files#diff-3ceb9ed41771a4e6c1b1532c7895e82a79f899c5b82b738529fa7c589a30a7f6
https://learn.microsoft.com/en-us/azure/databricks/security/keys/cmk-managed-disks-azure
https://learn.microsoft.com/en-us/azure/databricks/security/keys/customer-managed-key-managed-services-azure

**Examples:**
`az databricks workspace create --disk-key-vault <keyVaultUri1> --disk-key-name <keyName1> --disk-key-version <keyVersion1> --disk-key-auto-rotation <true> --managed-services-key-vault <keyVaultUri2> --managed-services-key-name <keyName2> --managed-services-key-version <keyVersion2>`

`az databricks workspace update ---disk-key-vault <keyVaultUri1> --disk-key-name <keyName1> --disk-key-version <keyVersion1> --disk-key-auto-rotation <true> --managed-services-key-vault <keyVaultUri2> --managed-services-key-name <keyName2> --managed-services-key-version <keyVersion2> --key-source <Microsoft.KeyVault> --key-name <keyName3> --key-vault <keyVaultUri3> --key-version <keyVersion3>`

**Swagger files:**

DBFS CMK: 
```json
 "WorkspaceEncryptionParameter": {
      "properties": {
        "type": {
          "$ref": "#/definitions/WorkspaceCustomParameterType",
          "description": "The type of variable that this is"
        },
        "value": {
          "$ref": "#/definitions/Encryption",
          "description": "The value which should be used for this field."
        }
      },
      "description": "The object that contains details of encryption used on the workspace."
    },
```

Managed Services CMK and Managed Disks CMK:

```json
    "EncryptionEntitiesDefinition": {
      "properties": {
        "managedServices": {
          "type": "object",
          "description": "Encryption properties for the databricks managed services.",
          "$ref": "#/definitions/EncryptionV2"
        },
        "managedDisk": {
          "type": "object",
          "description": "Encryption properties for the databricks managed disks.",
          "$ref": "#/definitions/ManagedDiskEncryption"
        }
      },
      "description": "Encryption entities for databricks workspace resource."
    },
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jsntcy** [comment]
@scottmacchia-msft,
Regarding the properties for each form of CMK, could you please check if I understand correctly as below?

DBFS CMK: 
```json
 "WorkspaceEncryptionParameter": {
      "properties": {
        "type": {
          "$ref": "#/definitions/WorkspaceCustomParameterType",
          "description": "The type of variable that this is"
        },
        "value": {
          "$ref": "#/definitions/Encryption",
          "description": "The value which should be used for this field."
        }
      },
      "description": "The object that contains details of encryption used on the workspace."
    },
```

Managed Services CMK and Managed Disks CMK:

```json
    "EncryptionEntitiesDefinition": {
      "properties": {
        "managedServices": {
          "type": "object",
          "description": "Encryption properties for the databricks managed services.",
          "$ref": "#/definitions/EncryptionV2"
        },
        "managedDisk": {
          "type": "object",
          "description": "Encryption properties for the databricks managed disks.",
          "$ref": "#/definitions/ManagedDiskEncryption"
        }
      },
      "description": "Encryption entities for databricks workspace resource."
    },
```

**Comment by jsntcy** [comment]
Released with https://github.com/Azure/azure-cli-extensions/pull/6342
