### ISSUE TITLE
No module named 'azure.keyvault.v7_0'

### ISSUE THREAD

**Issue by omprakashsivaramasamy** [Azure/azure-cli#26255]
## Describe the bug

**Command Name**
`az keyvault secret list`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az keyvault secret list --vault-name {}`

## Environment Summary
```
Linux-5.4.0-1103-azure-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
