### ISSUE TITLE
Enable Autoupgrade by default for GuestAttestationExtension

### ISSUE THREAD

**Issue by Bab95** [Azure/azure-cli#26252]
### Related command

```console
az vm extension set -n GuestAttestation --publisher Microsoft.Azure.Security.LinuxAttestation --vm-name linux-tvm --resource-group tvm-test-ext_group --subscription __subscription_guid__  --enable-auto-upgrade true
```
```console
az vm extension set -n GuestAttestation --publisher Microsoft.Azure.Security.WindowsAttestation --vm-name windows-tvm --resource-group tvm-test-ext_group --subscription __subscription_guid__ --enable-auto-upgrade true
```

### Resource Provider

Microsoft.Compute/virtualMachines/extensions

### Description of Feature or Work Requested

GuestAttestation Extension on install should have autoupgrade flag enabled by default.

--enable-auto-upgrade true should be applied by default. 

### Minimum API Version Required

2018-10-01

### Swagger PR link / SDK link

N/A

### Request Example

N/A

### Target Date

2023-05-15

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@Bab95 I'd like to confirm with you that if automatic upgrade is enabled by default, is it possible for the VM extension after automatic upgrade to cause a breaking change to the customer's automation scripts?

**Comment by Bab95** [comment]
no it is not a breaking change. Extension is already onboarded to auto upgrade.

**Comment by zhoxing-ms** [comment]
@Bab95 OK, I'd like to confirm the following situation:
If the customer did not enable the auto upgrade to the VM extension before, the version of the VM extension is stable, right?
After enabling auto upgrade by default, may the VM extension be automatic upgraded to a next version that may includes a breaking change, resulting in a breaking change to the customer's script?
Therefore, I would like to confirm whether the automatically upgraded version of VM extension can ensure backward compatibility and prohibit breaking changes?

**Comment by Bab95** [comment]
@zhoxing-ms  customer doesn't need to interact with GuestAttestationExtension it's a process that keeps running in the background and do attestation timely. So it won't break anything on customer scripts.

**Comment by zhoxing-ms** [comment]
@Bab95 Got it, thanks~

**Comment by zhoxing-ms** [comment]
@Bab95 I have completed the development of this feature and built a private package through edge build. Could you please help install this private package and test it's effectiveness to see if it meets your expectations? [package link](https://dev.azure.com/azclitools/public/_build/results?buildId=52535&view=artifacts&pathAsName=false&type=publishedArtifacts)
