### ISSUE TITLE
Ignore interactive upgrade message

### ISSUE THREAD

**Issue by johnkors** [Azure/azure-cli#26266]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`$ az webapp`

**Describe the bug**

I often get this output below. Is there a way of ignore the update warnings, like non-interactive mode? This output stops scripting:

> New Azure CLI version available. Running 'az upgrade' to update automatically.
> This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
> Your current Azure CLI version is 2.47.0. Latest version available is 2.48.1.
> Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
> Do you want to continue? (Y/n): Y

The docs says something about output & none, but I don't want to surpress output. I just need to ignore any upgrade questions when running in scripts.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by johnkors** [comment]
Answering my own question:

https://learn.microsoft.com/en-us/cli/azure/update-azure-cli#automatic-update

```bash
$ az config set auto-upgrade.prompt=no
```
