### ISSUE TITLE
[Azure Monitor Control Service] Update monitor-control-service extension 

### ISSUE THREAD

**Issue by AfstoneBharfon** [Azure/azure-cli#26270]
### Resource Provider

Microsoft.Insights

### Description of Feature or Work Requested

The current version  of the monitor-control-service [Az CLI extension](https://github.com/Azure/azure-cli-extensions/tree/main/src/monitor-control-service) is using an old version of the Data Collection Rules (DCR), DataCollectionEndpoints (DCE), DataCollectionRuleAssociations (DCRA) API.

We want to update it so that it's in sync with our latest swagger specs. 

 

### Minimum API Version Required

2022-06-01

### Swagger PR link / SDK link

Swagger Links:

- DCR: https://github.com/Azure/azure-rest-api-specs/blob/fce14bf881523f16b14d8ecf325e004465cdcf56/specification/monitor/resource-manager/Microsoft.Insights/stable/2022-06-01/dataCollectionRules_API.json
- DCE: https://github.com/Azure/azure-rest-api-specs/blob/fce14bf881523f16b14d8ecf325e004465cdcf56/specification/monitor/resource-manager/Microsoft.Insights/stable/2022-06-01/dataCollectionEndpoints_API.json
- DCRA: https://github.com/Azure/azure-rest-api-specs/blob/fce14bf881523f16b14d8ecf325e004465cdcf56/specification/monitor/resource-manager/Microsoft.Insights/stable/2022-06-01/dataCollectionRuleAssociations_API.json

- Python SDK link: https://pypi.org/project/azure-mgmt-monitor/6.0.0/

### Target Date

May 2023

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
@jsntcy for awareness

**Comment by AfstoneBharfon** [comment]
@yonzhan What is a possible ETA for this ?

**Comment by jsntcy** [comment]
@AfstoneBharfon, the possible ETA will be 2023-07-04. If you want it be released earlier, we encourage your team to use our new [codegen tool](https://github.com/Azure/aaz-dev-tools) (UI based, easy to use) to generate the code.

**Comment by AfstoneBharfon** [comment]
@AllyW any update on this?

**Comment by AllyW** [comment]
Hi @AfstoneBharfon , we are processing this api-version this sprint.
