### ISSUE TITLE
How to authenticate AzCLI without using application secret

### ISSUE THREAD

**Issue by akhilma-dev** [Azure/azure-cli#26283]
Right now, we are logging in with auth token for AZ PowerShell cmdlet. We want to do the same for AzCLI but it seems like AzCLI doesn't support auth token.

I know we can download the cert via C# code to the container when infra structure access is initialized and delete the cert after authentication. It feels like bit of a security issue.

Any other simpler ways to authenticate AzCLI

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by akhilma-dev** [comment]
Any update on this issue?

**Comment by jiasli** [comment]
There is no such thing called "auth token" in Azure's context. If you mean access token, Azure CLI currently doesn't support bring-your-own access token (https://github.com/Azure/azure-cli/issues/16459).

Supported sign-in methods of Azure CLI are described in https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli

**Comment by akhilma-dev** [comment]
I mean access token. Is there any feature development to support access token?
