### ISSUE TITLE
The operation 'azure.mgmt.cdn.operations#EndpointsOperations.purge_content' is invalid

### ISSUE THREAD

**Issue by mgelei** [Azure/azure-cli#26282]
## Describe the bug

**Command Name**
`az cdn endpoint purge`

**Errors:**
```
The operation 'azure.mgmt.cdn.operations#EndpointsOperations.purge_content' is invalid.
Traceback (most recent call last):
azure/cli/core/__init__.py, ln 831, in get_op_handler
    op = getattr(op, part)
AttributeError: type object 'EndpointsOperations' has no attribute 'purge_content'

...

azure/cli/core/__init__.py, ln 836, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.mgmt.cdn.operations#EndpointsOperations.purge_content' is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a classic Azure CDN endpoint with some files from a Storage static website
- `az cdn endpoint purge -g {} -n {} --profile-name {} --content-paths {}`

## Expected Behavior
Endpoint gets purged

## Environment Summary
```
Linux-5.4.0-1105-azure-x86_64-with-glibc2.31
Python 3.9.2
Installer: DEB

azure-cli 2.18.0 *

Extensions:
azure-devops 0.19.0

```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
