### ISSUE TITLE
az webapp deployments hangs indefinitely in certain circumstances 

### ISSUE THREAD

**Issue by ceuk** [Azure/azure-cli#26281]
## Describe the bug

I guess technically this could be considered a design issue with the App Service deployment status API.

Basically the /api/deployments/latest endpoint used by things like `az webapp deployment source config-zip` doesn't return the latest deployment but actually (perhaps unintuitively) returns the latest *incomplete* deployment before returning the latest complete deployment if there are no pending deployments.

This means that if, for whatever reason, a deployment task gets stuck with a pending status (0 or something) it will *always* hijack the latest endpoint once your deployment completes. 

The outcome from the CLI POV is that it ends up hanging indefinitely. 

e.g. 

* *(deployment starts)*
* ping /latest: your job - *pending*
* ping /latest: your job - *pending*
* ping /latest: your job - *pending*
* *(your job completes successfully)*
* ping /latest: **old job** - *pending*

The outcome is that the command hangs indefinitely before timing out at 30 mins or whatever. This obviously has an impact on things like CI in particular where it will cause the entire pipeline to fail even when everything is actually working nominally. 

We had 4 old jobs with a pending status on our instance so it seems like it could be fairly common to end up with jobs just getting stuck/abandoned in that status (or at least the status.xml files are just never updated properly when the job is cancelled/fails etc)

Once we deleted the offending deployment directories (/home/site/deployments) it all works again. (Changing the status in the xml works too). 

Happy to provide any more info if needed. 

**Command Name**
`az webapp deployment source config-zip`

## To Reproduce:

* Edit a status.xml file on the target app service instance updating the Status to 0
* try to perform a local zip deployment with the command above

## Expected Behavior

* The command is able to successfully determine when the specific deployment it has instigated has been completed or failed and handle it as appropriate. 

## Environment Summary
```
azure-cli 2.48.1

Extensions:
application-insights 0.1.18
azure-devops 0.25.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by psethwick** [comment]
seems to also affect these azure devops tasks:
- task: AzureWebApp@1
- task: AzureRmWebAppDeployment@4
are those dependent on azure-cli, or do they also need notifying?

**Comment by Victor-TW** [comment]
Hi there,

We're also encountering a similar issue which is causing our CI/CD pipelines to never complete. We appreciate your attention to this problem and would like an update on the resolution of this issue.

Thank you.

**Comment by ceuk** [comment]
@Victor-TW there is a manual fix: 

1. Go to https://your-function-name.scm.azurewebsites.net/DebugConsole (change your-function-name as appropriate)
2. `cd` into ~/site/deployments
3. Delete the problematic deployment folder. If you're not sure which one(s) to delete, visit: https://your-function-name.scm.azurewebsites.net/api/deployments and check for any deployments with `complete: false`. Note the ID for these deployments and delete the folders with the same name in the interactive shell (`rm -rf <folder>`)

**Comment by tulikac** [comment]
The /api/deployments/latest always returns the last 'pending' deployment. However, we had a bug in our code which was causing deployments to be stuck in pending state. We have a fix rolling out for deployments getting stuck in a pending state. You should be able to just restart your app and that will clean up the pending state. After that, the api will work as expected.

**Comment by seligj95** [comment]
Closing as team confirmed the bug fix and solution. Please re-open if any issues or additional feedback.
