### ISSUE TITLE
Unable to set managed Virtual Network while creating Azure integration runtime for ADF using Azure CLI

### ISSUE THREAD

**Issue by dibakarmetla** [Azure/azure-cli#26309]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eea4b974-44c0-423c-2be3-b634725ca48f
* Version Independent ID: 2d4e3d60-0585-866d-9355-b09a6ae07ea8
* Content: [az datafactory integration-runtime managed](https://learn.microsoft.com/en-us/cli/azure/datafactory/integration-runtime/managed?view=azure-cli-latest#az-datafactory-integration-runtime-managed-create)
* Content Source: [latest/docs-ref-autogen/datafactory/integration-runtime/managed.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/datafactory/integration-runtime/managed.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@dibakarmetla Can you please provide details and the cmdlets you are using to add managed virtual network while creating the managed integration runtime?

**Comment by SaurabhSharma-MSFT** [comment]
@dibakarmetla We are still waiting for your response. Can you please help providing details.
