### ISSUE TITLE
Trying to get list of repositories from acr fails

### ISSUE THREAD

**Issue by frosch95** [Azure/azure-cli#26301]
az acr repository list --name <NAME> -o tsv --username <USERNAME> --password <PASSWORD>

This command ran for nearly two years without problems and now it shows the following error.
It is part of a Jenkins job and runs on a linux (SLES) agent node.

## Describe the bug

**Command Name**
`az acr repository list`

**Errors:**
```
'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cli/core/commands/client_factory.py, ln 74, in get_mgmt_service_client
    **kwargs)
cli/core/commands/client_factory.py, ln 176, in _get_mgmt_service_client
    logger.debug('Getting management service client client_type=%s', client_type.__name__)
AttributeError: 'NoneType' object has no attribute '__name__'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr repository list --name {} -o {} --username {} --password {}`

## Environment Summary
```
Linux-5.14.21-150400.24.55-default-x86_64-with-glibc2.3.4
Python 3.6.15
Installer: PIP

azure-cli 2.17.1 *

```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by frosch95** [comment]
RESOLVED: The problem was an old version az which I could'nt upgrade via az upgrade.

I removed everything (package and repo) and installed everything again.
Now i have the azure-cli 2.38.0 and everything works fine.

```
zypper rm azure-cli
zypper rr azure-cli
zypper addrepo --name 'Azure CLI' --check https://packages.microsoft.com/yumrepos/azure-cli azure-cli
zypper clean
zypper install --from azure-cli azure-cli
```

**Comment by SwathiDhanwada-MSFT** [comment]
@frosch95  Thanks for sharing your resolution here, as it would be helpful for the community members who are facing similar issues.
