### ISSUE TITLE
az SQL - Clarity requested for zone-redundant parameter

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#26317]
This issue is being moved from azure-docs-cli issue #[3577](https://github.com/MicrosoftDocs/azure-docs-cli/issues/3577).

Clarity is needed for true/false parameter values.  What is the default?  It isn't always **false**, so we need to communicate this with our customers.
![image](https://user-images.githubusercontent.com/58762114/235805138-379c17e5-9ca3-4c43-9c3c-6889cc49bc46.png)

**Here is the customer verbatim:** _Will it be zone-redundant or not when I run "az sql db create" without the zone-redundant option specified?  Nobody knows, and no one ever will_

**Impacted autogen file:** https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sql/db.yml

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@dbradish-microsoft Default is true, if you check the examples using `az sql db create --help` .
![image](https://user-images.githubusercontent.com/38112130/236962023-30d2797d-fe89-4f5f-808a-25ea3f0c8363.png)
This example is also available on the shared documentation.  
Also, it shouldn't be zone redundant if `--zone-redundant` is not specified.  Are you saying that DB create is sometimes behaving as zone redundant and sometimes not?

**Comment by meyerovb** [comment]
I’m just saying you should put default values in the documentation next to each parameter definition

**Comment by SaurabhSharma-MSFT** [comment]
@dbradish-microsoft The PR for the fix has been created and it will be merged once approved. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
