### ISSUE TITLE
Azure CLI command to check if private IP address is reserved on VNET

### ISSUE THREAD

**Issue by nataliakon** [Azure/azure-cli#2632]
Azure CLI is missing command similar to both PowerShell commnads for ASM and ARM: Test-AzureRmPrivateIPAddressAvailability and Test-AzureStaticVnetIPAddress

**Comment by tjprescott** [comment]
Hi @nataliakon, please note that AzureCLI 2.0 does not support ASM. 

What does `Test-AzureRmPrivateIPAddressAvailability` do that  `az network vnet check-ip-address` does not?

**Comment by nataliakon** [comment]
My apologies. I could not find the command before. It absolutely does.
