### ISSUE TITLE
az afd doc Needs to be reviewed to support the latest changes

### ISSUE THREAD

**Issue by jbinko** [Azure/azure-cli#26320]
This page needs to be updated.

Commands and parameters are different.
For example:

az afd endpoint create --help

Command
    az afd endpoint create : Creates an endpoint within the specified profile.
        Command group 'afd' is in preview and under development. Reference and support levels:
https://aka.ms/CLI_refstatus
Arguments
    --enabled-state                   [Required] : Whether to enable this endpoint.  Allowed values:
                                                   Disabled, Enabled.
    --endpoint-name                   [Required] : Name of the endpoint under the profile which is
                                                   unique globally.
    --origin-response-timeout-seconds [Required] : Send and receive timeout on forwarding request to
                                                   the origin. When timeout is reached, the request
                                                   fails and returns.
    --profile-name                    [Required] : Name of the CDN profile which is unique within
                                                   the resource group.
    --resource-group -g               [Required] : Name of resource group. You can configure the
                                                   default group using `az configure --defaults
                                                   group=<name>`.
    --tags                                       : Space-separated tags: key[=value] [key[=value]
                                                   ...]. Use "" to clear existing tags.

 

Global Arguments
    --debug                                      : Increase logging verbosity to show all debug
                                                   logs.
    --help -h                                    : Show this help message and exit.
    --only-show-errors                           : Only show errors, suppressing warnings.
    --output -o                                  : Output format.  Allowed values: json, jsonc,
                                                   none, table, tsv, yaml, yamlc.  Default: json.
    --query                                      : JMESPath query string. See http://jmespath.org/
                                                   for more information and examples.
    --subscription                               : Name or ID of subscription. You can configure the
                                                   default subscription using `az account set -s
                                                   NAME_OR_ID`.
    --verbose                                    : Increase logging verbosity. Use --debug for full
                                                   debug logs.

 

Examples
    Creates an enabled endpoint with origin response timeout set to 60 seconds.
        az afd endpoint create -g group --endpoint-name endpoint1 --profile-name profile --origin-
        response-timeout-seconds 60 --enabled-state Enabled

 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d54d5d3-0fb9-b31d-059a-5ae458cce794
* Version Independent ID: 710f99c9-f9d6-027f-3465-74c789e241ac
* Content: [az afd endpoint](https://learn.microsoft.com/en-us/cli/azure/afd/endpoint?view=azure-cli-latest#az-afd-endpoint-create)
* Content Source: [latest/docs-ref-autogen/afd/endpoint.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/afd/endpoint.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@jbinko Can you please provide parameter details which are different as I could see all parameters available in the documentation.  Please find below screenshot for your reference.
![image](https://github.com/Azure/azure-cli/assets/38112130/cbffac16-970a-4e22-848b-84b20a5805ef)
Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@jbinko Please let me know if you still seeing different parameters ?

**Comment by SaurabhSharma-MSFT** [comment]
@jbinko We will now proceed to close this thread as we haven't heard back. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
