### ISSUE TITLE
adding a secret to the keyvault with a bang (!) in the --value, does not execute

### ISSUE THREAD

**Issue by bszerdy** [Azure/azure-cli#26323]
## Describe the bug
when attempting to create a new secret or update an existing secret using the following command
`az keyvault secret set --vault-name "myVault" --name "PASSWORD" --value "Testing123!"`

**Command Name**
`az keyvault secret set`

**Errors:**
```
-bash: !": event not found
```

## Expected Behavior
The secret is saved

## Environment Summary
```
macOS-13.3.1-x86_64-i386-64bit, Darwin 22.4.0
Python 3.10.11
Installer: HOMEBREW

azure-cli 2.48.1

Extensions:
bastion 0.2.4

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
Can't reproduce:
![image](https://user-images.githubusercontent.com/10227683/236091602-e6835548-620f-41d0-a929-eabff88c5a3e.png)

Please check if your terminal has parsed `Testing123!` into `Testing123` and `!` before executing this cli command
