### ISSUE TITLE
Azure CLI parameter "--nat-gateway null" option does not work for `az network vnet subnet update` command

### ISSUE THREAD

**Issue by aimee-littleton** [Azure/azure-cli#26326]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
  `az network vnet subnet update`

**Describe the bug**
In the CLI doc for https://learn.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#az-network-vnet-subnet-update 

the description for the --nat-gateway parameter says that you can remove the NAT gateway resource from the subnet by using 'null' on the parameter.

From doc:
"--nat-gateway
Name or ID of a NAT gateway to attach. Use null to detach it."

However, when I use "null" on the --nat-gateway parameter, I get the following error: 

(InvalidRequestFormat) Cannot parse the request.
Code: InvalidRequestFormat
Message: Cannot parse the request.
Exception Details:      (MissingJsonReferenceId) Value for reference id is missing. Path properties.natGateway.
        Code: MissingJsonReferenceId
        Message: Value for reference id is missing. Path properties.natGateway.

I found that you can use the --remove parameter though to remove the NAT gateway. It appears that the "null" option for the --nat-gateway parameter is just a documentation error. 

I would like to request that the part of the --nat-gateway parmeter description that says "Use null to detach it." be removed from the public doc.

**To Reproduce**
Run the following commands to remove the NAT gateway resource from the subnet

This method to remove the NAT gateway from the subnet DOES NOT work 
aimee [ ~ ]$ az network vnet subnet update -g aimeeGroup_rg -n mySubnet --vnet-name myVNet --nat-gateway null

This method to remove the NAT gateway from the subnet DOES work:
aimee [ ~ ]$ az network vnet subnet update -g aimeeGroup_rg -n mySubnet --vnet-name myVNet --remove nat_gateway

Note can also say --remove natGateway to remove it from the subnet. Should there only be one type of iteration of the nat gateway property that can be used to remove from the subnet?

**Expected behavior**

**Environment summary**

**Additional context**
This ask comes on behalf of CSS due to a customer reported incident.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by aimee-littleton** [comment]
@necusjz when should I expect for "null" to work on the --nat-gateway parameter? I just tried testing it and I got the same error message as before: 

![cli doesn't work](https://github.com/Azure/azure-cli/assets/91630183/6f3a34be-78d9-4d77-9e4e-130421af81e9)

**Comment by necusjz** [comment]
https://github.com/Azure/azure-cli/milestone/130
