### ISSUE TITLE
`rule-file` parameter documentation incomplete

### ISSUE THREAD

**Issue by otto-gebb** [Azure/azure-cli#26348]
The parameter `--rule-file` of the command `az monitor data-collection rule create` is documented poorly:
the format is not described anywhere, there's no example given, and it's unclear how to prepare such a file.

The current documentation

> The json file for rule parameters.

is not very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf6b7160-92be-96ab-a1c5-ad6e3c81e901
* Version Independent ID: 18ff06dd-51e0-6884-be2d-f079f5c9312b
* Content: [az monitor data-collection rule](https://learn.microsoft.com/en-us/cli/azure/monitor/data-collection/rule?view=azure-cli-latest#az-monitor-data-collection-rule-list)
* Content Source: [latest/docs-ref-autogen/monitor/data-collection/rule.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/monitor/data-collection/rule.yml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AllyW** [comment]
Hi @otto-gebb , the input example of `--rule-file` for `az monitor data-collection rule create` has been added in help message and users can run `az monitor data-collection rule create -h` in shell to see parameter details.
