### ISSUE TITLE
Get-AzVirtualNetworkUsageList returns CurrentValue as 0 when subnet is delegated

### ISSUE THREAD

**Issue by gcbikram** [Azure/azure-cli#26346]
> ### `Get-AzVirtualNetworkUsageList` returns CurrentValue as 0 when subnet is delegated

**Describe the bug**
It should return the actual value rather than 0 as we cant clearly see how many ips are used by the resource when the subnet is delegated.

**To Reproduce**
run Get-AzVirtualNetworkUsageList -ResourceGroupName "xyz-rg" -Name "xyz-vnet"

**Expected behavior**
It should return the actual value in the CurrentValue property to help us identity how many resources can be deployed of similar types when the subnet is delegated

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please open this issue in azure-powershell repo.
