### ISSUE TITLE
Installing azure-cli 2.39 on RHEL 8 fails if python39 is not found

### ISSUE THREAD

**Issue by ChaseCrum** [Azure/azure-cli#26341]
Installing azure-cli 2.39 on RHEL 8 fails if python39 is not found

This item has been moved from MicrsoftDocs/azurecli [#3253](https://github.com/MicrosoftDocs/azure-docs-cli/issues/3253).Azure CLI version being used

2.39.0

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux

Description 

`Error:
Problem: cannot install the best candidate for the job

nothing provides python39 needed by azure-cli-2.39.0-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)`
Suggested fix

Options.

Current doc says required python is 3.6. request reflect python 3.9 as a dependency, or fix the dependency in the package to 3.6, as is documented.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
For centos7, CLI requires `python3` package, which is python3.6.
For RHEL 8, CLI requires `python39` package, which is python3.9.
