### ISSUE TITLE
When shell is missing for hook script, include instructions to install it

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-cli#26355]
**Related command**
`azd up`

**Is your feature request related to a problem? Please describe.**
pwsh is not installed by default on Windows or Linux, which leads to failures when a hook script uses pwsh

**Describe the solution you'd like**
Rather than just returning an error indicating 'pwsh: not found', also give me instructions, or a link to instructions to help me install it.

**Describe alternatives you've considered**
none

**Additional context**
![image](https://user-images.githubusercontent.com/74415662/236583417-81c88d93-27cf-4990-b0bc-a8c36bcef798.png)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Is this issue related to Azure CLI?

**Comment by calvinhzy** [comment]
Since `azd up` was called, here is the azd repo link, please help create an issue here https://github.com/Azure/azure-dev/issues
