### ISSUE TITLE
get-credentials fails for kubernetes cluster

### ISSUE THREAD

**Issue by stevesloka** [Azure/azure-cli#2636]
Hey, I just spun up my first k8s cluster on Azure. After it got running, I wanted to get the credentials, but they fail with the following error. I was able to SSH to the master and grab from there, but wanted to see if there was a bug somewhere:

```
~/d/c/k/acs ❯❯❯ az acs kubernetes get-credentials --resource-group=$RESOURCE_GROUP --name=$CLUSTER_NAME                                                                                master ✱ ◼
Password:
Could not deserialize key data.
Traceback (most recent call last):
  File "/Users/slokas/lib/azure-cli/lib/python2.7/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/slokas/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/Users/slokas/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 358, in _execute_command
    raise ex
SSHException: Could not deserialize key data.
```

**Comment by brendandburns** [comment]
I will try to repro. Are you sure you typed the correct key password?

**Comment by stevesloka** [comment]
I assume the password is my Mac password? It's the same prompt when something needs elevated permissions.

**Comment by brendandburns** [comment]
No, it would be the password for your SSH key in `~/.ssh/rsa_pub` You probably created it a long time ago...

**Comment by brendandburns** [comment]
Closing this issue, please re-open if you can't resolve by moving and re-creating that key.

**Comment by stevesloka** [comment]
Hey Brendan, sorry for the late reply, yes you are correct it was asking for my ssh passphrase, but looked `exactly` like the Mac admin password. I just upgraded to latest OSX and things have gone downhill from there. 

Thanks for keeping up with me on this!

**Comment by brendandburns** [comment]
I'll update the message to include 'ssh'

--brendan


________________________________
