### ISSUE TITLE
az login --service-principal fails if password contains '>'

### ISSUE THREAD

**Issue by birjj** [Azure/azure-cli#26369]
## Describe the bug

When running `az login` with a password that contains `>`, a file is created in the working directory with whatever name follows the `>` character in the password.  
It appears as if though the az cli for some reason executes the given password on the command line (!?!).

**Command Name**
`az login`

**Errors:**
```
AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '<redacted>'.

Trace ID: 005770b3-2399-47b0-aca3-2e5945c96200

Correlation ID: e0b066ac-f486-4d25-8638-56348b35d030

Timestamp: 2023-05-08 11:30:53Z

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Minimal reproduction:
- Run `az login --service-principal --password 'abcd>ABCD'`
- ⚠️ Observe that a file called `ABCD` has been created in your working directory ⚠️ 

For an actual account:
- Create a service principal with a password containing `>` (e.g. `abcd>ABCD`)
- Attempt to log in to the service principal using `az login`:  
    `az login --service-principal -u 'id-of-sp' --password 'abcd>ABCD' --tenant 'id-of-tenant'`
- ⚠️ Observe that a file called `ABCD` has been created in your working directory ⚠️ 

## Expected Behavior

The service principal is successfully authenticated.

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.48.1

Extensions:
account 0.2.5
automation 0.2.1
ssh 1.1.3

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by birjj** [comment]
This appears to be an issue with every single az command. A similar thing happens with:

1. Run `az help 'foo>bar'`
2. Observe that a file called `bar` has been created in your working directory.

I am running the az cli in PowerShell, and `Get-Command az` returns a path to `az.cmd`. My guess would be that this proxy script fails to escape its inputs correctly.

**Comment by jiasli** [comment]
This is a typical issue of PowerShell. You need to escape the argument twice: `'"foo>bar"'`. See

- https://learn.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#use-quotation-marks-in-parameters
- https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md
