### ISSUE TITLE
Request to extend MAA CLI support for the newly release API version

### ISSUE THREAD

**Issue by mssindhurid** [Azure/azure-cli#26373]
Microsoft Azure Attestation (MAA) has been Generally Available since Jan 2021 and offers [CLI support for control-plane and data-plane operations](https://learn.microsoft.com/en-us/azure/attestation/quickstart-azure-cli). 

Recently MAA released a new API version ([2022-08-01 version - [data plane]](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Ftree%2Fmain%2Fspecification%2Fattestation%2Fdata-plane%2FMicrosoft.Attestation%2Fstable%2F2022-08-01&data=05%7C01%7CSindhuri.Dittakavi%40microsoft.com%7Cdd94b6d1a50344207a0208db4dcc5002%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638189312149115308%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tYKit8H7laLEqh%2Bac%2BTgxzfviYwnlW3RGUhFz2oWv6Y%3D&reserved=0)) which includes API support for attesting a new type of Trusted Execution Environment (TEE), i.e., SEV-SNP. 

Request to extend MAA CLI support for the newly released API version. Request to prioritize the effort as we have customers using the SEV-SNP attestation feature and looking for CLI support.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
