### ISSUE TITLE
Please bump argcomplete dependency to support 3.0.0 or higher

### ISSUE THREAD

**Issue by thehappydinoa** [Azure/azure-cli#26375]
The `azure-cli-core` component still depends on `argcomplete>=2.0,<3.0` while 3.0.0 has been available since March.

Could you bump the version for `argcomplete` so that we can get the added benefits of full zsh support and various other bug fixes?

Just the same as https://github.com/Azure/azure-cli/issues/23222

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by thehappydinoa** [comment]
Hi @yonzhan thank you so much, it would be greatly appreciated. Then I can resolve some version conflicts!

**Comment by bebound** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/26684
