### ISSUE TITLE
Gen2 to Trusted Launch Conversion Support - VM Configuration

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-cli#26387]
### Related command

`az vm update`

### Resource Provider

Microsoft.Compute/virtualMachines

## Is your feature request related to a problem? Please describe

No, feature request to add output value, new parameter and add values into existing parameters for following commands to support single-instance VM Gen2 -> Trusted Launch conversion:

- [az vm update](https://learn.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-update)

#### --security-type (`az vm update`)

Customers can use `az vm update` with new parameter **--security-type** to enable *TrustedLaunch* on existing Gen2 (*HyperVGeneration=V2*) VMs. The new parameter will be aligned with `az vm create --security-type` command.

**Example**: `az vm update --security-type TrustedLaunch`

When above command is executed:

- CLI will validate if VM is Gen2 VM. `HyperVGeneration=V2` using OS Disk attributes.
- CLI will validate `securityType` is currently set to `null` or `TrustedLaunch` using VM attributes. **Note**: Backend will not perform any update if securityType is already set to TrustedLaunch.
- Post execution, the `securityType` of VM will be updated to `TrustedLaunch`

--security-Type Value    |    Description
-|-
TrustedLaunch    |    Changes existing Gen2 VM from Standard (or null) Security type to Trusted Launch enabled.

#### Scenario 1 - Gen2 VMs (Non-TL or TL enabled)

1. Customer runs following command to enable **TrustedLaunch** configuration for existing **Gen2 VM** 

    ```azurecli
    az vm update -n name -g group \
        --security-type TrustedLaunch
    ```
2. Set `--enable-secure-boot: false` and `--enable-vtpm: true` if not specified by end user.

3. CLI submits the request to Compute Resource provider Backend API.

#### Scenario 2 - Gen1 VM

1. Customer runs following command to enable **TrustedLaunch** configuration for existing **Gen1 VM** 

    ```azurecli
    az vm update -n name -g group \
        --security-type TrustedLaunch
    ```
2. OS Disk Validation will return HyperVGeneration = `V1` for Gen1 VMs.

3. CLI generates below error message for end user and terminates:

    `Trusted Launch security configuration can be enabled only with Azure Gen2 VMs. Please visit https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch for more details.`

#### Scenario 3 - Confidential VM

1. Customer runs following command to enable **TrustedLaunch** configuration for existing **Confidential VM** 

    ```azurecli
    az vm update -n name -g group \
        --security-type TrustedLaunch
    ```
2. VM validation will return `securityProfile` is not `null` and security type `securityProfile.securityType` is set to `ConfidentialVM`

3. For Confidential VMs, CLI generates below error message for end user and terminates:
`<resource name> is already configured with <securityProfile.securityType>. Security Configuration cannot be updated from ConfidentialVM to TrustedLaunch.`
 
## Describe alternatives you've considered

Not Applicable, new product feature request.

### Minimum API Version Required

2022-11-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-03-01/virtualMachine.json

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-03-01/examples/virtualMachineExamples/VirtualMachine_Update_ForceDetachDataDisk.json

### Target Date

2023-07-04

## Additional context

Request for Gen2 -> Trusted Launch VM conversion feature.

- [Link to Virtual Machine Swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-03-01/virtualMachine.json)

### Contacts

Role    |    Contact
-|-
Main developer contacts (emails + github aliases)    |    Abhishek Verma (AZURE) <Abhishek.Verma@microsoft.com>, Prashant Surad <psurad@microsoft.com>
PM contact (email + github alias)    |    Ajay Kundnani <ajay.kundnani@microsoft.com>
Other people who should attend a design review (email)    |    Deepak J V <J.Deepak@microsoft.com>

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
> Target Date
2023-06-30

@AjKundnani Since our work is already fully scheduled for this sprint, we plan to develop and release it in the next sprint. The release time of the next sprint is **07-04**, does it meet your expectations?

**Comment by lakmeedee** [comment]
Please note that "--enable-secure-boot" and "--enable-vtpm" are optional parameters.
If these are not provided by the user, --enable-secure-boot should be set to false and --enable-vtpm should be set to true

**Comment by zhoxing-ms** [comment]
@lakmeedee Dose CLI need to set the default values for `--enable-secure-boot` and `--enable-vtpm` only when the customer inputs parameter `--security-type` as `TrustedLaunch`?
In addition, will the changes of these two default values cause a breaking change for customers?

**Comment by lakmeedee** [comment]
> @lakmeedee Dose CLI need to set the default values for `--enable-secure-boot` and `--enable-vtpm` only when the customer inputs parameter `--security-type` as `TrustedLaunch`? In addition, will the changes of these two default values cause a breaking change for customers?

Yes - these optional parameters should be allowed only when the security type parameter is provided and set to Trustedlaunch; I believe there are no breaking changes here as customer doesn't have a Trusted launch VM to start with and is updating the Gen2 VM to trusted launch using this command

**Comment by yanzhudd** [comment]
> ### End to End Usage
> #### Scenario 1 - Non-TL Gen2 VM
> 1. Customer runs following command to enable **TrustedLaunch** configuration for existing **Gen2 VM**
>    ```
>    az vm update -n name -g group \
>        --security-type TrustedLaunch
>    ```
> 2. CLI validates
>    
>    * `HyperVGeneration` is set to V2 and,
>    * `securityProfile` is set to `null`.
>
> 3. CLI will generate below warning message for end user:
>    `Enabling Trusted Launch on existing Azure Gen2 VMs is in private preview. Ensure feature Gen2ToTLMigrationPreview is registered for subscription.`
>
> 4. Set `--enable-secure-boot: false` and `--enable-vtpm: true` if not specified by end user.
>
> 5. CLI submits the request to Compute Resource provider API.
> 
> #### Scenario 2 - Gen1 VM
> 1. Customer runs following command to enable **TrustedLaunch** configuration for existing **Gen1 VM**
>    ```
>    az vm update -n name -g group \
>        --security-type TrustedLaunch
>    ```
> 2. CLI validates
>    
>    * `HyperVGeneration` is set to V2 and,
>    * `securityProfile` is set to `null`.
> 
> **Note**: For Gen1 VM, HyperVGeneration is set to `V1`.
> 
> 3. CLI generates below error message for end user and terminates:
>    `Trusted Launch security configuration can be enabled only with Azure Gen2 VMs. Please visit https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch for more details.`
> 
> #### Scenario 3 - Confidential VM
> 1. Customer runs following command to enable **TrustedLaunch** configuration for existing **Confidential VM**
>    ```
>    az vm update -n name -g group \
>        --security-type TrustedLaunch
>    ```
> 2. CLI validates
>    
>    * `HyperVGeneration` is set to V2 and,
>    * `securityProfile` is set to `null`.
> 
> **Note**: For Trusted Launch or Confidential VM, `securityProfile` is not `null` and security type can be determined using `securityProfile.securityType`.
> 
> 3. For Confidential VMs, CLI generates below error message for end user and terminates:
>    `<resource name> is already configured with <securityProfile.securityType>. Security Configuration cannot be updated from ConfidentialVM to TrustedLaunch.`
> 
> ## Describe alternatives you've considered
> Not Applicable, new product feature request.
> 
> ### Minimum API Version Required
> 2023-03-01
> 
> ### Swagger PR link / SDK link
> https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-03-01/virtualMachine.json
> 
> ### Request Example
> https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-03-01/examples/virtualMachineExamples/VirtualMachine_Update_ForceDetachDataDisk.json

Hi @AjKundnani 
could you please help to confirm these questions?

- We noticed that the warning message in Scenario 1 mentions `Enabling Trusted Launch on existing Azure Gen2 VMs is in private preview`. Does this feature will be in private preview status? If so, it is **not** suggested to officially release this feature in the CLI main repo. There are two suggestions to make this feature available:
  1. It is suggested to use private package by edge build.
  2. The warning message in Scenario 1 may confuse users, because for users who have registered this message may not be necessary, while for users who have not registered, the service side will report an error. Therefore, if the feature must be released, we suggest to move this message to help message of the new added param and provide users with the person who needs to be contacted for registration.

  If the seceond suggestion is preferred, please provide us with an appropriate contact info.

- May I ask if the "CLI validates" of Scenario 2 and Scenario 3, and the "Request Example" are not written correcly?

Thanks

**Comment by AjKundnani** [comment]
@yanzhudd 

>  Therefore, if the feature must be released, we suggest to move this message to help message of the new added param and provide users with the person who needs to be contacted for registration.

Can we skip the warning or help message altogether? The upgrade is supported by Azure PS with no warning or help message for end user.
If help message is mandatory, instead of individual contact please point to URL [Enable Trusted launch on your existing Azure Gen2 VMs](https://azure.microsoft.com/en-us/updates/enable-trusted-launch-on-existing-gen2vms-preview/)

> May I ask if the "CLI validates" of Scenario 2 and Scenario 3, and the "Request Example" are not written correcly?

The request example is correct. The CLI validates highlights positive validation and under **Note** section specifies what'll be actual returned values. 
Available on email or IM to discuss further if needed.

**Comment by yanzhudd** [comment]
After discussion with @AjKundnani, the `Minimum API Version Required` would be changed to `2022-11-01`.
