### ISSUE TITLE
az ad sp create-for-rbac --display-name unrecognized argument

### ISSUE THREAD

**Issue by marshallbentley** [Azure/azure-cli#26388]
Although it's documented, "--display-name" does not appear to be a valid argument for the az ad sp create-for-rbac command and using it produces the following error:
```
ERROR: unrecognized arguments: --display-name my-sp
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://learn.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ad/sp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ad/sp.yml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
`--display-name` for `az ad sp create-for-rbac` was added in https://github.com/Azure/azure-cli/pull/22432 (2.37.0). Please update to the latest Azure CLI version.
