### ISSUE TITLE
ContentLength in storage file is always null

### ISSUE THREAD

**Issue by tre2man** [Azure/azure-cli#26381]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az storage file list --account-name <accountName> --account-key <accountKey> --share-name <shareName>
az storage file list --account-name <accountName> --account-key <accountKey> --share-name <shareName> -o table

**Describe the bug**

I want get contentLength in azure storage with az-cli. But Only table format show me contentLength, json format cannot show me contentLength.

**To Reproduce**

az storage file list --account-name <accountName> --account-key <accountKey> --share-name <shareName>
This script will show me ContentLength=null
az storage file list --account-name <accountName> --account-key <accountKey> --share-name <shareName> -o table
This script will show me correct contentLength

**Expected behavior**

Content Length always null. But table format correctly show me contentLength.

**Environment summary**

Intel Macbook Pro 16, az-cli version : 2.47.0

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
@calvinhzy Can you pls take a look?

**Comment by calvinhzy** [comment]
You can use the properties.contentLength value instead. Thanks.
