### ISSUE TITLE
Decryption failed: [WinError -2146893813]

### ISSUE THREAD

**Issue by apatel19056** [Azure/azure-cli#26406]
Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20231

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
