### ISSUE TITLE
Use az vmss update should support --custom-data

### ISSUE THREAD

**Issue by tyhan2018** [Azure/azure-cli#26408]
**Related command**

az vmss update 

**Is your feature request related to a problem? Please describe.**

Once the Az Linux Vmss has been created, I want to update the cloud-init script, but now az vmss update not support.

**Describe the solution you'd like**

az vmss update should be support --custom-data same as az vmss create

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
