### ISSUE TITLE
ERROR for "az storage fs directory move"

### ISSUE THREAD

**Issue by doj2** [Azure/azure-cli#26419]
When using "az storage fs directory move" to rename a directory it gives an error, 

**ERROR: Please specify a file system name and file path.**

Even though a file system and file path has indeed been provided.

The now deprecated "az storage blob directory move" works as intended but is deprecated and recommended to use "az storage fs"
Is there a fix for this?

The command I used below:
az storage fs directory move -d 'newName' -n 'originalName' -f 'mycontainer' --account-name 'mystorageaccount' --account-key 'mystorageaccountkey'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 677f1e65-8bbc-2905-b9bc-5c7761a4894c
* Version Independent ID: c40da9b2-8eea-976d-c80f-0e0d708b7745
* Content: [az storage fs directory](https://learn.microsoft.com/en-us/cli/azure/storage/fs/directory?view=azure-cli-latest#az-storage-fs-directory-move)
* Content Source: [latest/docs-ref-autogen/storage/fs/directory.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/storage/fs/directory.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
Hi @doj2, the error message `Please specify a file system name and file path` is actually asking for file system name for new location. Here's the example we documented for `az storage fs directory move`:
![image](https://github.com/Azure/azure-cli/assets/10227683/f3c8277f-3dbf-43d4-a382-be974c3609b7)

So for you scenario, pls try with
```
az storage fs directory move -d 'mycontainer/newName' -n 'originalName' -f 'mycontainer' --account-name 'mystorageaccount' --account-key 'mystorageaccountkey'
```

**Comment by doj2** [comment]
Thank you! I was able to rename folder directories with that! Didn't realize I needed to include the container name in the folder path.
