### ISSUE TITLE
az aks nodepool update requires either --enable-cluster-autoscaler --disable-cluster-autoscaler --update-cluster-autoscaler

### ISSUE THREAD

**Issue by saviour07** [Azure/azure-cli#26425]
**Related command**

az aks nodepool update

**Describe the bug**

The documentation for `az aks nodepool` update states:
> When called with no optional arguments this attempts to move the node pool to its goal state without changing the current node pool configuration. This can be used to move out of a non succeeded state.

https://learn.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest#az-aks-nodepool-update

The first example in the documentation is
> Reconcile the nodepool back to its current state.
az aks nodepool update -g MyResourceGroup -n nodepool1 --cluster-name MyManagedCluster

https://learn.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest#az-aks-nodepool-update-examples

However when running the command as described in the example, it does not execute and displays the following message
> Please specify "--enable-cluster-autoscaler" or "--disable-cluster-autoscaler" or "--update-cluster-autoscaler"

**To Reproduce**

* Run `az aks nodepool update -g <My Resource Group> -n <My Node Pool> --cluster-name <My AKS Cluster>` while logged into an Azure subscription which has the specified resource group, AKS cluster, and node pool
* Command does not run and a message stating that one of the _optional_ parameters is _required_

**Expected behavior**

Command executes without requiring one of the optional parameters

**Environment summary**

winver
> Windows 10 22H2 (OS Build 19045.2846)

az --version
> {
  "azure-cli": "2.1.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.1.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {}
}

Kubernetes version
> 1.24.10

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by saviour07** [comment]
I've updated Azure CLI to version 2.48.1 and the command works as expected.

I'm happy for this to be closed off.
