### ISSUE TITLE
Issue while creating image from source image using az image create

### ISSUE THREAD

**Issue by kabirbaidhya** [Azure/azure-cli#2642]
I'm trying to create a new VM using an existing VM that I've setup recently. 

I'm following [this official tutorial](https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-capture-image) but I'm having issue with this step to create an image using the source vm

```
az image create --resource-group ontarget-servers --name myImage --source int-server-vm
```

It throws error: 
```
Source Virtual Machine 'int-server-vm' specified in the request does not exist in this Azure location. 
```
Not sure what exactly is the problem. But this vm is exactly in the same resource-group that I've mentioned above. And also, I have only one resource group so far. I couldn't find any solution or more information about what actually is the issue. 

Had this process been available from GUI, I would have done it that way. But seems like replicating a vm to create a new one is only an option using Azure CLI and I'm stuck here.

**Comment by tjprescott** [comment]
@yugangw-msft can you take a look?

**Comment by yugangw-msft** [comment]
it is likely the region doesn't match. Your command doesn't provide the `location` arg, so CLI defaults to the location of group ` ontarget-servers` , but if the location of `int-server-vm` is different, an error will occur. To create the  image, the location must match.

**Comment by yugangw-msft** [comment]
Please reactivate if it was caused by other things

**Comment by kabirbaidhya** [comment]
Thanks. I tried the command with `--location=eastus` arg as my previous vm was in East US and it did work perfectly.

**Comment by tmarshall** [comment]
Would be great to add this clarification to [the azure docs](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/capture-image).
