### ISSUE TITLE
[AKS] Uptime SLA:  unrecognized arguments: --tier standard with az aks create/update

### ISSUE THREAD

**Issue by axelgMS** [Azure/azure-cli#26428]
## Describe the bug

Following the page https://learn.microsoft.com/en-us/azure/aks/free-standard-pricing-tiers

**Command Name**
`az aks create --resource-group myResourceGroup --name myAKSCluster   --tier standard  --debug --verbose`

**Errors:**
```
cli.azure.cli.core.azclierror: unrecognized arguments: --tier standard
az_command_data_logger: unrecognized arguments: --tier standard

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Using Azure Portal's Cloud Shell - so my AZ CLI version is latest 2.48.1
- `az aks create --resource-group {} --name {} --tier {} --debug --verbose`

## Expected Behavior

Command should not return any error and should create an AKS cluster with a Standard tier.

## Environment Summary
```
Linux-5.4.0-1107-azure-x86_64-with-glibc2.35 (Cloud Shell), CBL-Mariner/Linux
Python 3.9.14
Installer: RPM

azure-cli 2.48.1

Extensions:
ai-examples 0.2.5
aks-preview 0.5.106
azure-firewall 0.14.1
fleet 0.1.1
maintenance 1.3.0
ml 2.15.1
ssh 1.1.6

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@axelgMS Please upgrade your aks-preview version to the latest one as --tier argument got added to aks-preview version `0.5.133` and you are using `0.5.106`.  
>![image](https://github.com/Azure/azure-cli/assets/38112130/489418a7-aee2-4ce7-97a2-729bbc8a0d9f)
I have tried this with the latest version, and it worked as expected.  Please let me know if you have any other questions. Thanks.

**Comment by axelgMS** [comment]
yes, looks good.

Sorry I thought Azure Portal's CloudShell was auto-upgrading CLI & its components.
