### ISSUE TITLE
Is it possible to clear service_principal_entries.json secrets from cli?

### ISSUE THREAD

**Issue by esdccs1** [Azure/azure-cli#26430]
**Related command**

**Is your feature request related to a problem? Please describe.**
I notice in .azure/service_principal_entries.json that the service principal clientId and clientSecrets are stored there.
Is there a command to discard these entries after a certain period?
e.g. drop after 5 days etc..
or should we just manually `rm ~/.azure/service_principal_entries.json ` when cleaning up our workspace.

**Describe the solution you'd like**

I see here https://github.com/Azure/azure-cli/blob/0459b95edb485459d5ce1c9cd053fb1b37cd9a33/src/azure-cli-core/azure/cli/core/auth/identity.py#L126 it being used

i see the logout call happening here 
https://github.com/Azure/azure-cli/blob/0459b95edb485459d5ce1c9cd053fb1b37cd9a33/src/azure-cli-core/azure/cli/core/_profile.py#L292

but when i do `az login` followed by `az logout` it does not erase/clear the file

**Describe alternatives you've considered**

**Additional context**

AzCli V 2.44.0

**Comment by jiasli** [comment]
`~/.azure/service_principal_entries.json` is the container for Service Principal entries. `az logout` only deletes the entry within `service_principal_entries.json`, but not `service_principal_entries.json` itself.

To fully delete `service_principal_entries.json`, run `az account clear`:

https://github.com/Azure/azure-cli/blob/f0c87ca820e0bd3f9dd403ef96c21ed49b734d16/src/azure-cli-core/azure/cli/core/auth/identity.py#L215-L218

**Comment by esdccs1** [comment]
thank you `az account clear` has removed the `service_principal_entries.json` file.
