### ISSUE TITLE
Typo "resouce"→"resource"

### ISSUE THREAD

**Issue by hyoshioka0128** [Azure/azure-cli#26434]
https://learn.microsoft.com/en-us/cli/azure/fleet/member?view=azure-cli-latest)
#PingMSFTDocs

![image](https://github.com/Azure/azure-cli/assets/40815708/38ccf5eb-6124-48e7-9764-7d1802a8c62e)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4b22b75-9d47-6873-4ba8-eeaabfbc81e3
* Version Independent ID: 148da655-31dd-b53f-ffc0-6011cf5529a3
* Content: [az fleet member](https://learn.microsoft.com/en-us/cli/azure/fleet/member?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/fleet/member.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/fleet/member.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@hyoshioka0128 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
