### ISSUE TITLE
`az vnet peering sync` does not work in cross-tenant scenario

### ISSUE THREAD

**Issue by Satya-anshu** [Azure/azure-cli#26438]
# Describe the bug
## Command Name
`az network vnet peering sync`

### Errors:

ForbiddenError: (LinkedAuthorizationFailed) The client has permission to perform action 'Microsoft.Network/virtualNetworks/peer/action' on scope '/subscriptions/$SECONDARY_SUBSCRIPTION/resourceGroups/$RG2/providers/Microsoft.Network/virtualNetworks/$VNET2/virtualNetworkPeerings/$PEERNAME2TO1', however the current tenant '$SECONDARY_TENANT' is not authorized to access linked subscription '$PRIMARY_SUBSCRIPTION'.

### To Reproduce:
Give a user in $SECONDARY_TENANT the Network Contributor role on a Virtual Network ($PRIMARY_VNET_ID) that lives in $PRIMARY_SUBSCRIPTION within $PRIMARY_TENANT. Create peered VNets in across these tenants and perform sync operation.

Log in to both tenants as the user from the secondary tenant:

az login -t $PRIMARY_TENANT
az login -t $SECONDARY_TENANT

az network vnet peering sync --name primary-to-secondary-peer --resource-group $PRIMARY_VNET_RG --vnet-name $PRIMARY_VNET_NAME 

### Expected Behavior
The VNet peering sync should work.

Environment Summary
Windows 11 Enterprise

azure-cli 2.48.1

### Additional Context
The same also happens when attempting the sync operation in reverse direction (secondary VNet -> primary VNet peering sync operation), with the error output showing the inverse IDs.

az rest is a workaround (get token of sub2 and then run the sync peering command by calling the az rest api)

$token2 = $ (az account get-access-token --subscription $sub2 --query accessToken --output tsv)

az rest --method PUT --url "https://management.azure.com/subscriptions/$sub1/resourceGroups/$rg1/providers/Microsoft.Network/virtualNetworks/$vnet1/virtualNetworkPeerings/$peeringName?api-version=2022-09-01" **--headers "x-ms-authorization-auxiliary=Bearer $token2" --url-parameters syncRemoteAddressSpace=true**

The workaround was thanks to an earlier reported issue in vnet peering create in cross-tenant scenario:
https://github.com/Azure/azure-cli/issues/16691

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
