### ISSUE TITLE
Unable to authenticate az login using certificate

### ISSUE THREAD

**Issue by akhilma-dev** [Azure/azure-cli#26443]
Added new App registration in Azure AD and uploaded a certificate with .cer format and according to the documentation ([Create an Azure service principal – Azure CLI | Microsoft Learn](https://learn.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?toc=%2Fazure%2Fazure-resource-manager%2Ftoc.json&view=azure-cli-latest&tryIt=true&source=docs#code-try-9)) the file format should be .pem format. Used this command

'openssl pkcs12 -in cert.pfx -passin pass: -out cert.pem -nodes' for conversion. Then, I tried to authenticate using the following command 

az login --service-principal --username appID --tenant tenantID --password /path/to/cert

 

Below is the error I am getting - 

![image](https://github.com/Azure/azure-cli/assets/119459043/996f3386-d417-42ba-830d-b6c095b41670)

Which says the certificate with identifier used to sign the client assertion is not registered on application. 

 

Weirdly the Thumbprint shown in the error message is different from the thumbprint of the certificate we have.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by MinKPark** [comment]
Hi there, 
Along with this, I wonder whether we can provide a auth token than a cert. since it is allowed in Azure powershell cmdlet.

**Comment by jiasli** [comment]
@akhilma-dev, Azure CLI won't use a certificate out of no where to log in. Please double check if the certificate path is correct.

**Comment by jiasli** [comment]
@MinKPark, your feature request is tracked by https://github.com/Azure/azure-cli/issues/16459.

**Comment by jiasli** [comment]
To view the thumbprint (fingerprint) of the certificate used in `az login`, run

```
openssl x509 -in cert.pem -noout -fingerprint
```

See https://www.openssl.org/docs/man1.1.1/man1/x509.html

The thumbprint should match the thumbprint of the certificate in the keyvault:

```
$ openssl x509 -in cert.pem -noout -fingerprint
SHA1 Fingerprint=84:46:2F:52:8A:81:2B:AF:4F:77:77:34:2E:B7:22:4C:F6:21:66:94
```

![image](https://github.com/Azure/azure-cli/assets/4003950/5a8d50c8-b3d8-47c9-b9f2-bcaace01924e)

**Comment by akhilma-dev** [comment]
@jiasli, we have a certificate in our key Vault, and we are downloading it to the local and trying to use the certificate with right path. But still, we are seeing this issue
