### ISSUE TITLE
Create Application Gateway rewrite rule that removes the server header

### ISSUE THREAD

**Issue by kpnjacobstruiksma** [Azure/azure-cli#26449]
## Describe the bug
In previous versions like Azure CLI version 2.42.0 this command works and creates a rule for removing the server header. In the current version it does not work anymore. What is the command I now need to use for creating a rewrite rule that removes the server header?

**Command Name**
`az network application-gateway rewrite-rule create`

**Errors:**
```
Failed to parse '--response-headers' argument: argument value cannot be blank
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network application-gateway rewrite-rule create --resource-group {} --gateway-name {} --rule-set-name {} --name {} --response-headers server=`

## Expected Behavior
Create a rewrite rule that removed the server header
## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.48.1

Extensions:
azure-devops 0.26.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@kpnjacobstruiksma Try it out:

![image](https://github.com/Azure/azure-cli/assets/12371639/bd26e512-0794-4eec-b7f1-68343850fcf3)

**Comment by JacobStruiksma** [comment]
The single quotes with double quotes seems do to the trick indeed : `'""'`
