### ISSUE TITLE
az login or az login --tenant TENANT-ID are failing 

### ISSUE THREAD

**Issue by rajpisupati** [Azure/azure-cli#26457]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login --tenant {}`

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.10
Installer: MSI

azure-cli 2.48.1

Extensions:
resource-graph 2.1.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by rajpisupati** [comment]
here are more details about this issue !

az login
Please select the account you want to log in with.
The following tenants don't contain accessible subscriptions. Use 'az login --allow-no-subscriptions' to have tenant level access.
16b3c013-d300-468d-ac64-7eda0820b6d3 'Microsoft Non-Production'
86f8a0b2-5a4f-44f0-96ec-feb6051864fc 'Contoso'
The following tenants require Multi-Factor Authentication (MFA). Use 'az login --tenant TENANT_ID' to explicitly login to a tenant.
b6225b64-1a28-4cac-b8f2-03346d6ff3ae 'Default Directory'
The command failed with an unexpected error. Here is the traceback:
'defauult'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 238, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/output.py", line 166, in get_formatter
KeyError: 'defauult'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
To open a new issue, please run `az feedback`
________________________________

**Comment by jiasli** [comment]
Looks like you have corrupted configuration, possibly caused by

```
$ az config set core.output=defauult
$ az version
The command failed with an unexpected error. Here is the traceback:
'defauult'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 238, in invoke
    formatter = self.output.get_formatter(output_type)
  File "/opt/az/lib/python3.10/site-packages/knack/output.py", line 166, in get_formatter
    return OutputProducer._FORMAT_DICT[format_type]
KeyError: 'defauult'
```

Please delete `~/.azure` and try again.

**Comment by rajpisupati** [comment]
How do I fix this ! I am not able to find a solution to correct this Corrupted configuration ! I did reinstall a few times !
________________________________

**Comment by rajpisupati** [comment]
Got this fixed, might be a typo that got me this error, 
something like this : `az config set core.output=table` shall fix the issue
