### ISSUE TITLE
list iothub device twins: " 'list' is misspelled"

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/azure-cli#26467]
**Describe the bug**

Error displayed when listing device twins via Azure CLI.

**To Reproduce**

1. Open DOS command prompt
2. az login
3. az iot hub device-twin list 
4. error displayed

```
c:\Users\corey>az iot hub device-twin list
'list' is misspelled or not recognized by the system.
```

**Expected behavior**

Expect the device twins to be listed

**Environment (please complete the following information):**

- OS: Windows 10
- Shell: bash, cmd
- az cli version

```
{
  "azure-cli": "2.30.0",
  "azure-cli-core": "2.30.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.25.0",
    "azure-iot": "0.17.3"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
