### ISSUE TITLE
Azure Postgres Flexible Server Firewall Rule creation issue.

### ISSUE THREAD

**Issue by jgnader** [Azure/azure-cli#26466]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
az postgres flexible-server firewall-rule create

**Describe the bug**

Incorrect verification of IP Address Range, it's just validating the first number of the last octet, generating the message below:

"The end IP address is smaller than the start IP address."

**To Reproduce**

01 - Deploy an instance of Postgres Flexible Server in Azure
03 - Go to Networking Blade
04 - Open the Cloud Shell 
05 - Run the command below:

az postgres flexible-server firewall-rule create --rule-name rulename --subscription 'xxxxxxxxxxxxxxxxx' --resource-group xxxxxxx-rg --name name-xxxxxxx --start-ip-address 10.19.50.96 --end-ip-address 10.19.50.111

**Expected behavior**

A new Firewall rule should be created under Networking, having the option "Public access (allowed IP addresses)" selected.

**Environment summary**

Cloud Shell

**Additional context**

I understand the logic behind the CLI command line is just checking the first number of the last octet, like comparing the number 1 from 111 with the number 9 from 96, thus it says the last octet 111 is smaller than 96.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SwathiDhanwada-MSFT** [comment]
@jgnader Thanks for your comment. We will review the issue and get back to you shortly.

**Comment by nasc17** [comment]
@jgnader Could you please verify if this is still an issue using latest CLI release
azure-cli 2.61.0

**Comment by nachoalonsoportillo** [comment]
@nasc17, @jgnader This was fixes in 2.52.0 via https://github.com/Azure/azure-cli/commit/e4710f54d0190889a80d21f7c3625c56be9bbd1a

@yonzhan Please, close this issue as it is resolved. Thanks!
