### ISSUE TITLE
Non-admin users are unable to run AzCLI commands if any extension was installed system-wide

### ISSUE THREAD

**Issue by gubadam** [Azure/azure-cli#26462]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az extension

**Describe the bug**

Extensions installed using `--system` parameter break AzCLI for non-admin users:
![image](https://github.com/Azure/azure-cli/assets/23238442/131cebbf-6924-4441-aab1-aa291ea6d5f7)

This appears to be due to too restrictive permissions on one of the extension install subdirectory: _extensionName_._extensionVersion_.dist-info. 
After the extension is installed the inheritance is disabled and only Administrators group is allowed to read content of this catalog. Enabling inheritance/adding Users with Read access seems to be a workaround for this issue, but it requires elevated access.

**To Reproduce**

1. As a local administrator user install any extension to the system directory; e.g.  `az extension add -n resource-graph --system` 
2. As a non-admin user run any AzCli command; e.g. `az --help`, `az login`

**Expected behavior**

Non-admin users are able to execute AzCLI commands.

**Environment summary**

MSI / Azure CLI 2.48.1 / Windows 22H2 19045.2965 / powershell.exe

**Additional context**

This is affecting corporate setups where AzCLI extensions are installed by the IT dept staff and users have no admin access on the machine.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
Does non-admin user have read&exec permission in `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure-cli-extensions`?

**Comment by bebound** [comment]
CLI does not perform any special actions, we simply install extension to that folder. No idea how permissions are inherited on Windows.
But I'm able to fix it by applying `replace all child permission` in azure-cli-extension folder.
![image](https://github.com/Azure/azure-cli/assets/2227874/fff6ad12-011d-4ee4-871a-6689530d1600)
Maybe you can add a step to change the permission of that folder after install system extension? 

This seems to be an old issue: https://github.com/Azure/azure-cli/issues/13622
