### ISSUE TITLE
Graph API consent issue

### ISSUE THREAD

**Issue by joraff** [Azure/azure-cli#26471]
## Describe the bug

I'm getting permission errors (`PermissionScopeNotGranted`) with certain Graph API endpoints when trying to use `az rest`. This is in a Microsoft developer tenant, Azure AD level P2.

I asked Azure support about this, and they directed me to open an issue here. In their words, 
> This is a consent issue between Azure CLI (04b07795-8ddb-461a-bbee-02f9e1bf7b46) and the Microsoft Graph API (00000003-0000-0000-c000-000000000000) that needs to have action from Microsoft internally to solve it.

**Command Name**
`az rest`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

```bash
$ az rest --method GET --uri https://graph.microsoft.com/v1.0/roleManagement/directory/roleAssignmentScheduleRequests 
Forbidden({"error":{"code":"UnknownError","message":"{\"errorCode\":\"PermissionScopeNotGranted\",\"message\":\"Authorization failed due to missing permission scope RoleAssignmentSchedule.ReadWrite.Directory,RoleManagement.ReadWrite.Directory.\",\"instanceAnnotations\":[]}","innerError":{"date":"2023-05-10T19:44:10","request-id":"0f5bca39-214e-43c4-8f69-f17db718101c","client-request-id":"0f5bca39-214e-43c4-8f69-f17db718101c"}}})
````

```bash
$ az login --scope RoleManagement.ReadWrite.Directory
invalid_request: AADSTS65002: Consent between first party application '04b07795-8ddb-461a-bbee-02f9e1bf7b46' and first party resource '00000003-0000-0000-c000-000000000000' must be configured via preauthorization - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API.
```

## Environment Summary
```
macOS-13.2.1-arm64-arm-64bit, Darwin 22.3.0
Python 3.10.11
Installer: HOMEBREW

azure-cli 2.48.1

Extensions:
account 0.2.5

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```
## Additional Context

The az cli is signed in as a Global Admin of a tenant with AAD P2 that was created through the Microsoft Developer Program.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by kthejoker** [comment]
Hi @yonzhan I have this same issue today (with previously working code) using the `azure-identity `Python SDK package with a DeviceCodeCredential call.

```
from azure.identity import DeviceCodeCredential

cred = DeviceCodeCredential(tenant_id='<tenantid>')
t = cred.get_token("2ff814a6-3304-4ab8-85cb-cd0e6f879c1d\.default").token # Databricks scope
```

1) Are there any known workarounds for this? For example, are there previously working versions of the CLI or SDK we could pin to?
2) What is the status for fixing this? Since this requires two internal MSFT teams to coordinate, there's no visibility on the issue besides this Github issue.

**Comment by jiasli** [comment]
Azure CLI's app ID `04b07795-8ddb-461a-bbee-02f9e1bf7b46` doesn't have `RoleManagement.ReadWrite.Directory` permission pre-configured. See https://github.com/Azure/azure-cli/issues/22775 for explanations and workarounds.

**Comment by cveld** [comment]
@jiasli why is this permission not granted to the az cli app registration?
