### ISSUE TITLE
P0V3 is not a valid sku

### ISSUE THREAD

**Issue by troyha** [Azure/azure-cli#26498]
When running Azure CLI commands "az appservice list-locations --sku P0V3" or "appservice plan create" P0V3 is not a valid sku. At least for the locations command it should just show the locations where it is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f99cdf3a-4fd3-e949-aabe-1b26fe828444
* Version Independent ID: 1c2e7517-1275-9e30-db67-393c0451055f
* Content: [az appservice plan](https://learn.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/appservice/plan.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/appservice/plan.yml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by seligj95** [comment]
This is not a CLI issue. There is a bug on the backend that I have been working with the team to address. ETA for the fix to rollout is end of June.

**Comment by troyha** [comment]
Not sure if this is at all related to why [Terraform doesn't implement P0V3 as a valid sku](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/service_plan) but seems like this would prevent them from implementing it if they tried?
Planning on opening an issue with them as I would like to be able to spin up P0V3 plans using TF. Do you have the bug fix link I can share with them if it could be related?

**Comment by seligj95** [comment]
Apologies, I confused this with another issue. The bug I was thinking of is that you can't create zone redundant P0v3 plans. Standard P0v3 should work. I just ran the 2 commands you shared and both were successful. Please make sure you're using the latest CLI version. If you are still having trouble, please run the command with the `--debug` flag and share the output here.
