### ISSUE TITLE
az servicebus namespace create

### ISSUE THREAD

**Issue by ZabalaMelendez** [Azure/azure-cli#26495]
## Describe the bug

**Command Name**
`az servicebus namespace create`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az servicebus namespace create --resource-group {} --name {} --location {} --sku {}`

## Environment Summary
```
macOS-13.2.1-arm64-arm-64bit, Darwin 22.3.0
Python 3.10.11
Installer: HOMEBREW

azure-cli 2.48.1
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@ZabalaMelendez Can you please provide the error message and debug log to understand your problem?
