### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.storage.blob'

### ISSUE THREAD

**Issue by sondo123** [Azure/azure-cli#26490]
## Describe the bug

**Command Name**
`az quantum`

**Errors:**
```
Paste here the error message you have received. Make sure to remove all sensitive information,
such as user name, password, credential, subscription ID, etc.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az quantum --help`

## Environment Summary
```
macOS-13.3.1-arm64-arm-64bit, Darwin 22.4.0
Python 3.10.11
Installer: HOMEBREW

azure-cli 2.48.1

Extensions:
azure-devops 0.25.0
quantum 0.19.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 22.0.0
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
