### ISSUE TITLE
Issue in logging to Azure Portal

### ISSUE THREAD

**Issue by kowshikdremio** [Azure/azure-cli#26494]
Hi,
      I am unable to login to Azure portal. Getting the below error.

I am using "az login" and gave id and password. But, it's giving me the below error.

Authentication failed
server_error: AADSTS5000811: Unable to verify token signature. The signing key identifier does not match any valid registered keys. Trace ID: 9324e7c4-f08d-4477-a46d-0a031ef94800 Correlation ID: 8442d050-7e53-4661-8002-3d47dd4052a2 Timestamp: 2023-05-19 09:52:30Z. ($error_uri)

Please can you share the resolution.

Regards,
Kowshik

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Is this issue related to Azure Portal or Azure CLI?

**Comment by kowshikdremio** [comment]
I tried logging from both CLI and Browser.....same error....So it's not a
CLI specific issue for sure....Something to do with Portal I guess....

Regards,

Kowshik Dutta

Dremio | Senior Consulting Architect

*Self-service analytics with data warehouse functionality and data lake
flexibility across all of your data.*

**Comment by jiasli** [comment]
As this issue is related to your AAD account, and not limited to Azure CLI, please reach out to Azure Support instead. Thanks for understanding.
