### ISSUE TITLE
Improve az storage table stats and az storage queue stats command

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#2649]
Both commands apply to storage account which is equipped with read-access geo-redundant replication. Otherwise, the command will simply timeout after minutes, with misleading error message ```HTTPSConnectionPool```

Options:
1. Check if the storage meets the requirement.
2. Print better error message.

**Comment by tjprescott** [comment]
This would be more appropriately addressed in the SDK.

**Comment by troydai** [comment]
True

**Comment by zhusijia26** [comment]
Close due to the idle time. Please reopen if there is still questions.
