### ISSUE TITLE
The resource type could not be found in the namespace 'Microsoft.KubernetesConfiguration'

### ISSUE THREAD

**Issue by ecaha** [Azure/azure-cli#26491]
```
az k8s-extension extension-types list-by-location --location westeurope
```

gives

```
Command group 'k8s-extension extension-types' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(InvalidResourceType) The resource type could not be found in the namespace 'Microsoft.KubernetesConfiguration' for api version '2022-01-15-preview'.
Code: InvalidResourceType
Message: The resource type could not be found in the namespace 'Microsoft.KubernetesConfiguration' for api version '2022-01-15-preview'.
```

in the cloudshell

```
PS /home/erik> az version                                                                                                                                                         
{
  "azure-cli": "2.48.1",
  "azure-cli-core": "2.48.1",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "ai-examples": "0.2.5",
    "k8s-extension": "1.4.0",
    "ml": "2.15.1",
    "ssh": "1.1.6"
  }
}
```
in the local shell

```
PS C:\temp\vmwdeploy> az version
{
  "azure-cli": "2.48.1",
  "azure-cli-core": "2.48.1",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "arcappliance": "0.2.31",
    "connectedvmware": "0.1.12",
    "customlocation": "0.1.3",
    "k8s-extension": "1.4.0"
  }
}
````
for different tenants and subscriptions. Microsoft.KubernetesConfiguration resource provider seems to be registered on subscriptions in question. I tried some older azcli in the container - same result.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55b11d2b-710f-25df-00ff-bc7acff616e3
* Version Independent ID: 8df26e45-2211-00bb-b8a5-3e1ccd8e3347
* Content: [az k8s-extension extension-types](https://learn.microsoft.com/en-us/cli/azure/k8s-extension/extension-types?view=azure-cli-latest#az-k8s-extension-extension-types-list-by-location)
* Content Source: [latest/docs-ref-autogen/k8s-extension/extension-types.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/k8s-extension/extension-types.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@ecaha Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@ecaha This issue occurs if you haven't registered the provider for your subscription. Please run the below command in order:

# Set the right subscription id
> **az account set --subscription "XXXXXXXXXXXXXXXXXXXXXXXXX"**

# Feature registration 
> **az feature registration create --namespace Microsoft.KubernetesConfiguration --name ExtensionTypes** 


After running the above command, you need to wait for sometime.  You can check the registration status using the below command:

# Check the status
> **az feature show --namespace Microsoft.KubernetesConfiguration --name ExtensionTypes**


Once the provider is registered, you can run `az k8s-extension extension-types list-by-location --location westeurope` cli command again and check if that helps.

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ecaha I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ecaha The action is pending on you try the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by antiviruuzz** [comment]
Getting the same issue after performing steps above:
artem@artem-hp:~$ az version
{
  "azure-cli": "2.73.0",
  "azure-cli-core": "2.73.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "k8s-extension": "1.6.4"
  }
}
az feature show --namespace Microsoft.KubernetesConfiguration --name ExtensionTypes
{
  "id": "/subscriptions/ac6d09b0-7061-4954-b988-8ee7b8ca007a/providers/Microsoft.Features/providers/Microsoft.KubernetesConfiguration/features/ExtensionTypes",
  "name": "Microsoft.KubernetesConfiguration/ExtensionTypes",
  "properties": {
    "state": "Registered"
  },
  "type": "Microsoft.Features/providers/features"
}
az k8s-extension extension-types list-by-location --location westeurope
Command group 'k8s-extension extension-types' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(InvalidResourceType) The resource type could not be found in the namespace 'Microsoft.KubernetesConfiguration' for api version '2023-05-01-preview'.
Code: InvalidResourceType
Message: The resource type could not be found in the namespace 'Microsoft.KubernetesConfiguration' for api version '2023-05-01-preview'.
