### ISSUE TITLE
Continuous access evaluation resulted in challenge with result: InteractionRequired and code: TokenIssuedBeforeRevocationTimestamp

### ISSUE THREAD

**Issue by sofialouisyaxis** [Azure/azure-cli#26504]
## Describe the bug
When calling any 'az ad' request, I receive "Continuous access evaluation resulted in challenge with result: InteractionRequired and code: TokenIssuedBeforeRevocationTimestamp".

It it not obvious to me what I can do to fix this... Recently, I have updated my company's AD password, which lauched a new login in the azure portal. I completed it with MFA successfully, and I can access all information in the portal, but when I use az cli, I get this error. I have already done az login to make sure I had an updated token. 

What am I supposed to do to fix this?

**Command Name**
`az ad signed-in-user show`

**Errors:**
"Continuous access evaluation resulted in challenge with result: InteractionRequired and code: TokenIssuedBeforeRevocationTimestamp"

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad signed-in-user show`

## Expected Behavior
successful request

## Environment Summary
```
Linux-5.15.0-71-generic-x86_64-with-glibc2.31, Ubuntu 20.04.5 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.48.1
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Have you tried to re-login by running `az login`?

**Comment by sofialouisyaxis** [comment]
Hi! I have tried az login, which prompts login, but I have not tried with az logout in between. I will try that

**Comment by unique-dominik** [comment]
Yeah, just happened here and 

```
az logout
az login
```

Seems to have fixed it or it was a hickup.

**Comment by YazanGhafir** [comment]
Confirming, the problem persists with doing only az login and disappered after doing both az logout and az login.
