### ISSUE TITLE
az login in VM (the device login link returns a blank page which means i cannot paste the code provided)

### ISSUE THREAD

**Issue by flavian-anselmo** [Azure/azure-cli#26505]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
When I open the  link https://microsoft.com/devicelogin, it becomes blank. I'm doing this through a VM 
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Linux-5.15.0-1036-azure-x86_64-with-glibc2.35, Ubuntu 22.04.2 LTS
Python 3.10.10
Installer: DEB

azure-cli 2.48.1
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by flavian-anselmo** [comment]
some how it worked after stopping the vm and then doing a new connection
