### ISSUE TITLE
az vm create gives warning about default public IP SKU changing even when no public IP is being created

### ISSUE THREAD

**Issue by josephcsible** [Azure/azure-cli#26516]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**
`az vm create`

**Describe the bug**
When creating a VM without a public IP address, you get this irrelevant warning:

> It is recommended to use parameter "--public-ip-sku Standard" to create new VM with Standard public IP. Please note that the default public IP used for VM creation will be changed from Basic to Standard in the future.

Since that change won't affect VMs created with no public IP address, that warning in this case is just noise.

**To Reproduce**
`az vm create [...] --public-ip-address ""`

**Expected behavior**
Since no public IP address is being created, there should be no message saying the type of public IP address that is being created is going to change.

**Environment summary**
Cloud Shell bash

**Additional context**
This warning comes from here: https://github.com/Azure/azure-cli/blob/5352ca83cfeca436b8fa5dc16a06831bf61bff2c/src/azure-cli/azure/cli/command_modules/vm/custom.py#L913-L920

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
