### ISSUE TITLE
`az bicep publish` unrecognized arguments: --force

### ISSUE THREAD

**Issue by manitua** [Azure/azure-cli#26514]
**Related command**
`az bicep publish --file storage.bicep --target br:exampleregistry.azurecr.io/bicep/modules/storage:latest --force`

**Describe the bug**
The `az bicep publish` suggest to use `--force` when re-uploading, overwriting, already existing module:
```
Publishing module storage:latest
ERROR: The module "br:exampleregistry.azurecr.io/bicep/modules/storage:latest" already exists in registry. Use --force to overwrite the existing module.
```
Argument `--force` does not exists on `az bicep publish` and throws `unrecognized arguments: --force`

**To Reproduce**
Please note that some arguments ware changed as they may contain sensitive information.

1. Publish bicep module `az bicep publish --file storage.bicep --target br:exampleregistry.azurecr.io/bicep/modules/storage:latest`
2. Re-publish bicep module with same tag `az bicep publish --file storage.bicep --target br:exampleregistry.azurecr.io/bicep/modules/storage:latest` - This will throw error:
```
Publishing module storage:latest
ERROR: The module "br:exampleregistry.azurecr.io/bicep/modules/storage:latest" already exists in registry. Use --force to overwrite the existing module.
```
3. Re-publish again bicep module with same tag and use `--force` as suggested `az bicep publish --file storage.bicep --target br:exampleregistry.azurecr.io/bicep/modules/storage:latest --force` - will throw `unrecognized arguments: --force`

**Expected behavior**
Argument `--force` on `az bicep publish` should exist and work as suggested.

**Environment summary**
```
/usr/bin/az --version
azure-cli                         2.48.1

core                              2.48.1
telemetry                          1.0.8

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Bicep:
Bicep CLI v0.17.1

Python: 3.10.10
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@manitua Please upgrade your Azure CLI to 2.49.0 as `--force` parameter is part of this release. Once updated you should be able to see this newly added parameter.  Please refer to the below screenshot:
![image](https://github.com/Azure/azure-cli/assets/38112130/de5448b1-3906-4574-bb65-98948913f7bb)
