### ISSUE TITLE
Completer failing when resource name has a space

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-cli#26526]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

az 

**Describe the bug**

Install az completer on PowerShell and use 'az group list --subscription' then `Tab`  to get the subscription name.
If the subscription name has a space, it will appear as 
'az group list --subscription My\ default\ subscription` 

The command fails with the following message:
```
Subscription 'My\' not recognized.
unrecognized arguments: default\ subscription
``` 

**To Reproduce**

Use a subscription name with spaces.

**Expected behavior**

The string should be within double quotes and spaces should not be escaped in PowerShell.

**Environment summary**

PowerShell

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
Looks like argcomplete has compatibility issue on Windows.
` ` is convert to `\ ` on Linux, but it be `` `  `` on PowerShell.
Workaround,
``` powershell
(Get-Content $completion_file) -replace '\\ ', '\\ ' | Sort-Object | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new($_, $_, "ParameterValue", $_)
```
There are some other characters,Some strings were converted incorrectly. For  example: `\(`
I think we should create a PR for argcomplete.
