### ISSUE TITLE
Add domainNameLabelScope to public Ip Address DnsSettings

### ISSUE THREAD

**Issue by tinama0302** [Azure/azure-cli#26525]
### Related command

az network public-ip create --name <string> 

                            --resource-group <string> 

                            --allocation-method <string> 

                            [--dns-name <string>] 

                            [--dns-name-scope <string>] 

### Resource Provider

Network Resource Provider

### Description of Feature or Work Requested

When customers are trying to create public ip address, they can provide 1 optional parameter "DomainNameLabelScope"
possible value of ""DomainNameLabelScope" (string, can be null): "TenantReuse", "SubscriptionReuse", "ResourceGroupReuse", "NoReuse"

### Minimum API Version Required

2022-11-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/23721

### Target Date

2023-08-01

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by tinama0302** [comment]
Hi @yonzhan , thank you for your review, just have some questions for you: will CLI team do the code change for this issue? Or do I need to open PR to do this? If I need to do this, is this issue be reviewed and ok to start?

**Comment by tinama0302** [comment]
thank you for sharing @necusjz
