### ISSUE TITLE
`az keyvault certificate show` returning `null` for `x509CertificateProperties.subjectAlternativeNames` in 4.49.0

### ISSUE THREAD

**Issue by andysbolton** [Azure/azure-cli#26527]
**Related command**

az keyvault

**Describe the bug**

In 4.8.1, `az keyvault certificate show` would successfully return the `x509CertificateProperties.subjectAlternativeNames`.

![image](https://github.com/Azure/azure-cli/assets/5191998/1ee75f98-1f3b-4c22-a2e4-e79ebefc57ee)

In 4.49.0, `x509CertificateProperties.subjectAlternativeNames` is null:

![image](https://github.com/Azure/azure-cli/assets/5191998/999fb8ad-74c6-49d9-913c-708e7bc43a1a)

I didn't see this listed in the [breaking changes](https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#key-vault), though I'm not sure if I missed something.

**To Reproduce**

Query for a certificate in 4.49.0.

**Expected behavior**

`x509CertificateProperties.subjectAlternativeNames` should not be null.

**Environment summary**

I've recreated this on both Debian (fish and bash) and Windows (Powershell).

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Looking into this.
