### ISSUE TITLE
Typo "Azure SQL managed instance."→"Azure SQL Managed Instance."

### ISSUE THREAD

**Issue by hyoshioka0128** [Azure/azure-cli#26534]
https://learn.microsoft.com/en-us/cli/azure/sql/midb?view=azure-cli-latest
#PingMSFTDocs

![image](https://github.com/Azure/azure-cli/assets/40815708/fed09040-c599-4fa1-af20-fb526e51b5b2)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 783be10e-fb90-641a-53ae-6d7f3456cbc1
* Version Independent ID: d31d6323-89a5-c8e0-277f-a0e7bef841c8
* Content: [az sql midb](https://learn.microsoft.com/en-us/cli/azure/sql/midb?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/sql/midb.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sql/midb.yml)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@hyoshioka0128 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
