### ISSUE TITLE
Release for trafficmanager 2022-04-01

### ISSUE THREAD

**Issue by imsiddhartha** [Azure/azure-cli#26532]
### Related command

az network traffic-manager endpoint create

### Resource Provider

Microsoft.Network/trafficManagerProfiles

### Description of Feature or Work Requested

Added a new flag “Always Serve”, When it is enabled, ATM bypasses the health checks and always serves the endpoint. ATM asserts that endpoints that are “always served” are healthy. The customer will be configuring this flag for every endpoint that the ATM profile resolves to. Details in the [doc here](https://microsoft-my.sharepoint.com/:w:/p/samimodak/EbHOz_mYXddMg9C9JnolFy4BOVnGrSoNEVgGS_QG1xBkOA?e=pvFrma)

### Minimum API Version Required

2022-04-01

### Swagger PR link / SDK link

Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/trafficmanager/resource-manager/Microsoft.Network/stable/2022-04-01/trafficmanager.json

Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/22357

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/trafficmanager/resource-manager/Microsoft.Network/stable/2022-04-01/examples/Endpoint-PUT-External-WithAlwaysServe.json

### Target Date

2023-06-15

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by imsiddhartha** [comment]
@yonzhan Can you please share ETA for the release?

**Comment by necusjz** [comment]
@imsiddhartha It's planned in the next coming milestone https://github.com/Azure/azure-cli/milestone/132.
