### ISSUE TITLE
Az login: Unable to get 'ResourceType.MGMT_RESOURCE_SUBSCRIPTIONS' in profile 'latest'

### ISSUE THREAD

**Issue by GregorieCalderon** [Azure/azure-cli#26548]
`az login` error: `Unable to get 'ResourceType.MGMT_RESOURCE_SUBSCRIPTIONS' in profile 'latest'`

The command to replicate is simple: ` az login`

Normally it should log you in with no problem, but after the browser pops up and i sign in, my VSCode is presented with error: 
Unable to get 'ResourceType.MGMT_RESOURCE_SUBSCRIPTIONS' in profile 'latest'

To get the az cli i downloaded the installer from the docs: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli

![image](https://github.com/Azure/azure-cli/assets/85905534/27dcf963-4c33-41fa-b8ce-f0b995880def)

Current CLI version: **2.49.0**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
This is really a weird error. It looks like the source code is somehow corrupted.

Could you share the output of 

```powershell
# Run in PowerShell
& "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import azure.cli.core.profiles; print(azure.cli.core.profiles.AZURE_API_PROFILES)"
```

Part of it should look like 

```
<ResourceType.MGMT_RESOURCE_SUBSCRIPTIONS: ('azure.mgmt.resource.subscriptions','SubscriptionClient')>: '2019-11-01'
```

Also, could you follow https://github.com/Azure/azure-cli/issues/20990 to perform a clean install?

**Comment by GregorieCalderon** [comment]
> This is really a weird error. It looks like the source code is somehow corrupted.
> 
> Could you share the output of
> 
> ```powershell
> # Run in PowerShell
> & "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import azure.cli.core.profiles; print(azure.cli.core.profiles.AZURE_API_PROFILES)"
> ```
> 
> Part of it should look like
> 
> ```
> <ResourceType.MGMT_RESOURCE_SUBSCRIPTIONS: ('azure.mgmt.resource.subscriptions','SubscriptionClient')>: '2019-11-01'
> ```
> 
> Also, could you follow #20990 to perform a clean install?

When trying to run the python.exe file i get an error 

`SyntaxError: Non-UTF-8 code starting with '\x90' in file C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details`

I will try running the clean install as you mentioned.

**Comment by GregorieCalderon** [comment]
> This is really a weird error. It looks like the source code is somehow corrupted.
> 
> Could you share the output of
> 
> ```powershell
> # Run in PowerShell
> & "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import azure.cli.core.profiles; print(azure.cli.core.profiles.AZURE_API_PROFILES)"
> ```
> 
> Part of it should look like
> 
> ```
> <ResourceType.MGMT_RESOURCE_SUBSCRIPTIONS: ('azure.mgmt.resource.subscriptions','SubscriptionClient')>: '2019-11-01'
> ```
> 
> Also, could you follow #20990 to perform a clean install?

**It seems like the uninstall and re-install fixed this issue. Very weird.**

**Comment by DadouneDa** [comment]
Note that only a full uninstall,  including removing the following folders worked (for me) 

- `C:\Users\{username}\.azure`
- `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2`
