### ISSUE TITLE
Azure CLI Error - This region has quote of 0 instances for your subscription

### ISSUE THREAD

**Issue by salagger07** [Azure/azure-cli#26550]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

scott [ ~ ]$ az webapp up --os Linux --location centralus --sku F1 --name educationapp-$RANDOM
The webapp 'educationapp-13404' doesn't exist
Creating Resource group 'salagger_rg_4583' ...
Resource group creation complete
Creating AppServicePlan 'salagger_asp_9345' ...
This region has quota of 0 instances for your subscription. Try selecting different region or SKU.

The web app is written as recommended from Learn course.  The code references a resource group in the 'centralus' location.

Please advise.

Thanks,

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@salagger07 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@salagger07 Here are the action plans which you can follow to isolate this issue:

1. Ensure that you have selected the right subscription. You can run the below command to make sure that the right subscription is selected.
> az account set --subscription "XXXXXXXXXXXXXX"

2. Please check if retrying the same operation works ?
3. Please check if you have tried with a different region (like eastus, westus, eastus2) and check if that helps.
4. Could you please try with a different sku (B1 or B2 or B3) for your app service plan and check if that helps ?

5. You can also check the current quota usage and limits from the portal by routing to that subscription (Home -> Subscriptions-> Select a particular subscription) under Usage+Quotas settings.

<img width="846" alt="image" src="https://github.com/Azure/azure-cli/assets/57353862/f597b480-1499-4135-95e1-77c6e2ce2da2">

6. The AppService Plan subscription limits have been clearly mentioned in [this ](https://learn.microsoft.com/en-in/azure/azure-resource-manager/management/azure-subscription-service-limits#app-service-limits)documentation. If you want to increase the quota limits, you need to raise a support ticket with Microsoft.

Awaiting your reply.

**Comment by salagger07** [comment]
Ah.  Now that I use 'eastus' as the location, the app is building.  However, I received an app error when trying to access the web app.  I am retrying.  Stay Tuned.

**Comment by salagger07** [comment]
OK.  The app did build and produced output.  I enter the URL in the browser, and it results in an error (attached).

Here is the web app build output:

scott [ ~/mslearn-secure-app-with-oidc-and-azure-ad/app ]$ az webapp up --os Linux --resource-group salagger_rg_2001 --location eastus --sku F1 --name educationapp-$RANDOM
The webapp 'educationapp-25948' doesn't exist
Creating AppServicePlan 'salagger_asp_7822' ...
Creating webapp 'educationapp-25948' ...
Configuring default logging for the app, if not already enabled
Creating zip with contents of dir /home/scott/mslearn-secure-app-with-oidc-and-azure-ad/app ...
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 202
You can launch the app at http://educationapp-25948.azurewebsites.net<http://educationapp-25948.azurewebsites.net/>
Setting 'az webapp up' default arguments for current directory. Manage defaults with 'az configure --scope local'
--resource-group/-g default: salagger_rg_2001
--sku default: F1
--plan/-p default: salagger_asp_7822
--location/-l default: eastus
--name/-n default: educationapp-25948
{
  "URL": http://educationapp-25948.azurewebsites.net<http://educationapp-25948.azurewebsites.net/>,
  "appserviceplan": "salagger_asp_7822",
  "location": "eastus",
  "name": "educationapp-25948",
  "os": "Linux",
  "resourcegroup": "salagger_rg_2001",
  "runtime_version": "dotnetcore|7.0",
  "runtime_version_detected": "2.1",
  "sku": "FREE",
  "src_path": "//home//scott//mslearn-secure-app-with-oidc-and-azure-ad//app"
}

Thanks,



From: Scott A Lagger
Sent: Monday, May 29, 2023 5:27 PM
To: Azure/azure-cli ***@***.***>; Azure/azure-cli ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Azure/azure-cli] Azure CLI Error - This region has quote of 0 instances for your subscription (Issue #26550)

Ah.  Now that I use 'eastus' as the location, the app is building.  However, I received an app error when trying to access the web app.  I am retrying.  Stay Tuned.

**Comment by navba-MSFT** [comment]
@salagger07 Thanks for your reply. I am glad that the command ran successfully. I am unable to see your attached error log.

Could you please attach the error logs here in GitHub ? 

PS: Remove sensitive information from the logs.

**Comment by navba-MSFT** [comment]
@salagger07 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@salagger07 The action is pending on you to attach the `--debug `error logs here in GitHub. Once you are ready to resume troubleshooting on this, please feel free to reopen this thread. We would be happy to help.
