### ISSUE TITLE
az keyvault secret list command fails with "ERROR: The challenge resource 'vault.azure.net' does not match the requested domain"

### ISSUE THREAD

**Issue by KimForss** [Azure/azure-cli#26552]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Related command**

**Describe the bug**

When running "az keyvault secret list " the command fails with
_"ERROR: The challenge resource 'vault.azure.net' does not match the requested domain. Pass `verify_challenge_resource=False` to your client's constructor to disable this verification. See https://aka.ms/azsdk/blog/vault-uri for more information."_

The same command works with the 2.48.1 version

**To Reproduce**

Deploy environment with:

- Ubuntu 20.04 VM in subscription A in VNet A-net, 
  - remove the default cli installation
  - install latest cli
- Keyvault "KV" with private endpoint in VNet B-net in Subscription B. 
- Ensure VNets are peered
- Ensure that keyvault allows access from VM's subnet in VNet A-net
- Ensure access policies are correct in keyvault
 
run 
```
az keyvault secret list --vault-name "KV" --subscription [SUBSCRIPTION B]
```

**Expected behavior**

The secrets from the key vault "KV" should be listed

**Environment summary**

Since it is Ubuntu 20.04 the old cli installation is removed first with
```
sudo apt remove azure-cli -y
sudo apt autoremove -y
sudo apt update -y

```

and then the latest version is installed with

```
sudo curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
```

**Additional context**

If I run 

```
sudo apt-get install azure-cli=2.48.1-1~focal -y --allow-downgrades
```
the 

```
az keyvault secret list --vault-name "KV" --subscription [SUBSCRIPTION B]_
```

command works as expected

This is in the Microsoft Tenant so if you need access you can ping me directly

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by billpieper** [comment]
Running into the exact same issue when using azure cli 2.49.0

**Comment by rolish** [comment]
Same issue with azure cli 2.49.0

**Comment by evelyn-ys** [comment]
Sorry for the regression. The fix PR is ready and will be release in CLI 2.50.0 on 2023-07-04. Here's a [private package](https://yssa.blob.core.windows.net/cli/azure_cli_4_keyvault_fix.zip) for you to verify the fix and unblock your scenarios.

**Comment by VictorRos** [comment]
Hello!

I'm working for a company that use **Azure Pipelines** from **Azure DevOps** to build and deploy services to production.
Since yesterday, we are not able to that.

[AzureCLI@2](https://github.com/microsoft/azure-pipelines-tasks) task in version `2.220.0` has updated `azure-cli` from `2.48.1` to `2.49.0` yesterday.

Some Bash scripts run `az keyvault secret list` commands in our pipelines and it triggers the same error as KimForss.

```shell
The challenge resource 'vault.azure.net' does not match the requested domain.
Pass `verify_challenge_resource=False` to your client's constructor to disable this verification.
See https://aka.ms/azsdk/blog/vault-uri for more information.
```

We don't have the upper hand to update `azure-cli` bask to `2.48.1`.

And waiting for `2.50.0` is too far in the future.
We cannot afford to wait almost one month to deploy our services.

Do you know whether it would be possible to create a fix version `2.49.1` including this fix?
Should I also report this to `azure-pipelines-tasks` repository?

**Comment by dwoldo** [comment]
We had an issue with this as well. Our workaround was to override the version of Az CLI used _per job_.

Add a task before using the AzCLI@2 per job.
```yaml
  # Downgrade az cli to v.2.48.1
  - bash: pip install -Iv azure-cli==2.48.1 --extra-index-url https://azurecliprod.blob.core.windows.net/edge
    displayName: "Downgrade Azure CLI"
```

In context of the Azure Pipeline:
![image](https://github.com/Azure/azure-cli/assets/10914645/46b98f00-6f77-4779-a6d1-da768a5cb8b1)

**Comment by evelyn-ys** [comment]
@VictorRos  Let me know if @dwoldo's workaround works for you. You can also overwrite the Azure CLI with the private package I shared before

**Comment by VictorRos** [comment]
Hi @evelyn-ys

Sorry for the late answer.

We found a temporary solution to fix it.
I will share it for anyone that encounter this problem aswell.

We replace the following command:

```shell
az keyvault secret list --vault-name MY-SUPER-KEY-VAULT
```

By this command:

```shell
# Must be in lower case!!!
az keyvault secret list --id "https://my-super-key-vault.vault.azure.net/"
```

This is the complete workaround we use in Bash:

```shell
keyVault="MY-SUPER-KEY-VAULT"
azureCliVersion=$(az version | jq -r '."azure-cli"')
if [ "${azureCliVersion}" = "2.49.0" ]; then
  keyVaultLower=$(echo "${keyVault}" | tr '[:upper:]' '[:lower:]')
  secretInfos=$(az keyvault secret list --id "https://${keyVaultLower}.vault.azure.net/")
else
  secretInfos=$(az keyvault secret list --vault-name "${keyVault}")
fi
echo "${secretInfos}"
```

FYI @dwoldo
