### ISSUE TITLE
az functionapp deployment source config-zip : Returns with status 202 but the new changes aren't reflected

### ISSUE THREAD

**Issue by gowthamn6** [Azure/azure-cli#26576]
### Describe the bug

I've been using "az functionapp deployment source config-zip" from the past 2 months to deploy the new changes to my functions app from my local. Since almost a week ago, the az deployment returns success response but the changes won't reflect/ functions endpoint doesn't get updated. 

![image](https://github.com/Azure/azure-cli/assets/121905659/beea1ef8-5936-4470-a715-a3728fa087d2)

Here are my configuration settings for the functions app

![image](https://github.com/Azure/azure-cli/assets/121905659/e054f326-bc77-4e91-b523-7e338e6a45b4)

### Related command

az functionapp deploy --resource-group $()--name $()--src-path $()--subscription $()--type zip

### Errors

The command returned the http 202 but won't publish the changes to Functions app

### Issue script & Debug output

az functionapp deployment source config-zip -g $existingResourceGroupName -n $existingFunctionsAppName --src $functionsAppZipDeployPath --subscription $azureSubscriptionId

### Expected behavior

The az functionapp deployment source config-zip zip deploy command should be able to deploy the changes to the targeted functions app 

### Environment Summary

azure-cli 2.44.1
Powershell 7 
Azure Functions app version 4

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by GN-Intel** [comment]
> Hi @GN-Intel,
> 
> 2.44.1 is not the latest Azure CLI(2.49.0).
> 
> Please upgrade to the latest Azure CLI version by following https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.

Upgrade to the latest version. still seeing the same issue

**Comment by kamperiadis** [comment]
Hello @gowthamn6 Are you still experiencing this issue? This seems to be a deployment issue rather than an Azure CLI issue.

**Comment by liyavasdvbzld** [comment]
Same issue, deploy from VSCode works. I use the publish folder generated by VSCode deploy progress, and not able to work too.
