### ISSUE TITLE
Add upload to Azure Storage file with full url

### ISSUE THREAD

**Issue by yuwzho** [Azure/azure-cli#26587]
**Related command**

`az storage file upload`

**Is your feature request related to a problem? Please describe.**

Currently, I have a Azure Storage File URL with SaS token like " https://mystorageaccount.file.core.windows.net/myshare/myfile?sv=2019-02-02&st=2020-12-22T07%3A07%3A29Z&se=2020-12-23T07%3A07%3A29Z&sr=b&sp=racw&sig=redacted"

But when I use `az storage file upload` command to upload my local file to remote, I need to parse the URL into share-name, path and sas-token and finally invoke the command.
What worse is there is no built-in command to parse such URL into object. I have to write a script todo.

```
Arguments
    --share-name -s              [Required] : The file share name.
    --source                     [Required] : Path of the local file to upload as the file content.
    --sas-token                             : A Shared Access Signature (SAS). Must be used in
                                              conjunction with storage account name or service
                                              endpoint. Environment variable:
                                              AZURE_STORAGE_SAS_TOKEN.
```

**Describe the solution you'd like**

I am wondering whether the command can be designed similar to `az storage blob upload`. I can pass the file url as a parameter instead of parse it to several parameters.
```
 --blob-url                              : The full endpoint URL to the Blob, including SAS token
                                              and snapshot if used. This could be either the primary
                                              endpoint, or the secondary endpoint depending on the
                                              current `location_mode`.
Examples
 Upload to a blob with blob sas url.
        az storage blob upload -f /path/to/file --blob-url https://mystorageaccount.blob.core.window
        s.net/mycontainer/myblob?sv=2019-02-02&st=2020-12-22T07%3A07%3A29Z&se=2020-12-
        23T07%3A07%3A29Z&sr=b&sp=racw&sig=redacted
```

**Describe alternatives you've considered**

CLI can also provide a built-in method, do the contrast way of `az storage file url` to parse the given URL to an object. Then I can pass the object parameter to the existing command.

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
