### ISSUE TITLE
Customer billing is now managed by differtent tenant and it is affecting when he sets the Azure Context in Azure CLI and causing errors in his code

### ISSUE THREAD

**Issue by backbackforward** [Azure/azure-cli#26597]
### Describe the bug

 Customer appears to have a service principal identity. His expectation is that it is available from one resource group on one subscription, but it appears to be accessible from other resource groups. The potential for that is normal.

We are noticing duplicate spn-id while login with service principal with dc01 subscription and here is output.  Here with this exaple we are trying to connect with DC01 subscription for one of spn, but for some reason it shows both DC's dc01 and DC60.

### Related command

az login --service-principal --username a5c14060-5a0f-4b00-81be-84a60da6dc4b --password xxxxxx-xxxxxx~xxxxxxxxx~xxxxxxxxx --tenant xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx

[

  {

    'cloudName': 'AzureCloud',

    'homeTenantId': '69b863e3-480a-4ee9-8bd0-20a8adb6909b',

    'id': '89fe98e7-0242-4608-a261-f61fc59990c5',

    'isDefault': false,

    'managedByTenants': [],

    'name': 'sap-hcm-dc60-toronto',

    'state': 'Enabled',

    'tenantId': '69b863e3-480a-4ee9-8bd0-20a8adb6909b',

    'user': {

      'name': 'fa0047d6-acea-43de-99fd-8a9a7d1c6d03',

      'type': 'servicePrincipal'

    }

  },

  {

    'cloudName': 'AzureCloud',

    'homeTenantId': '69b863e3-480a-4ee9-8bd0-20a8adb6909b',

    'id': '75691fc5-c37a-4e8c-a15a-8c965ca7cd4a',

    'isDefault': true,

    'managedByTenants': [

      {

        'tenantId': '2f4a9838-26b7-47ee-be60-ccc1fdec5953'

      }

    ],

    'name': 'sap-hcm-dc01-washington',

    'state': 'Enabled',

    'tenantId': '69b863e3-480a-4ee9-8bd0-20a8adb6909b',

    'user': {

      'name': 'fa0047d6-acea-43de-99fd-8a9a7d1c6d03',

      'type': 'servicePrincipal'

    }

  }

]

### Errors

-

### Issue script & Debug output

-

### Expected behavior

This started occurring Friday 5/31
He has an app IDa5c14060-5a0f-4b00-81be-84a60da6dc4b that has default Azure Context of Subscription 75691fc5-c37a-4e8c-a15a-8c965ca7cd4a
ASC shows it is owned by tenant 	69b863e3-480a-4ee9-8bd0-20a8adb6909b, but managed by tenant 2f4a9838-26b7-47ee-be60-ccc1fdec5953
As far as I can tell it was always set up this way, but now the managing tenant appears to be disrupting the context of the subscription and causing errors.
Need this corrected so the managing tenant does not affect the context.
The context of the app ID always shows as the correct tenant.
Expect this to be exacalayed to ASMS PG.
This is not a CSP, but is managed by EA,

### Environment Summary

-

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
> Customer appears to have a service principal identity. His expectation is that it is available from one resource group on one subscription, but it appears to be accessible from other resource groups.

Service principal doesn't belong to a resource group or subscription. [Service principal](https://learn.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals?tabs=browser) is an AAD object. You can assign [RBAC role assignments](https://learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments) to it and access ARM resources with it.

> We are noticing duplicate spn-id while login with service principal with dc01 subscription and here is output. Here with this exaple we are trying to connect with DC01 subscription for one of spn, but for some reason it shows both DC's dc01 and DC60.

Azure CLI is simply an HTTP client calling [Subscriptions - List](https://learn.microsoft.com/en-us/rest/api/resources/subscriptions/list?tabs=HTTP) REST API to retrieve subscriptions the service principal `89fe98e7-0242-4608-a261-f61fc59990c5` has access to. If the customer feels `sap-hcm-dc60-toronto` shouldn't be listed, you may contact ARM customer support team and instruct the customer to remove service principal `89fe98e7-0242-4608-a261-f61fc59990c5`'s role assignments on `sap-hcm-dc60-toronto`.

> As far as I can tell it was always set up this way, but now the managing tenant appears to be disrupting the context of the subscription and causing errors.

I am not an expert of subscription management, but from my understanding, customer can remove the management permission for tenant `2f4a9838-26b7-47ee-be60-ccc1fdec5953` to avoid unexpected disruption. But again, this is out of the scope of Azure CLI as a client tool.

Thanks for your understanding.
