### ISSUE TITLE
Python versions above 3.8 should not be reported as OK

### ISSUE THREAD

**Issue by rakotomandimby** [Azure/azure-cli#26590]
### Describe the bug

On rolling releases Linux systems, where Python is regularily updated to the latest version, the BASH install script reports, for example Python version 3.11.3 to be OK:
```
[mihamina@arch-00 ~]$ curl -L https://aka.ms/InstallAzureCli | bash
[...]
Running install script.
-- Verifying Python version.
-- Python version 3.11.3 okay.
[...]

```

This is currently wrong, because Az CLI installs `virtualenv-16.7.11` which still uses the `distutils` module, which is hard deprecated: https://peps.python.org/pep-0632/

This leads to :

```
-- Executing: ['/usr/bin/python3', 'virtualenv.py', '--python', '/usr/bin/python3', '/home/mihamina/lib/azure-cli']
/tmp/tmpn0w4l6w9/virtualenv-16.7.11/virtualenv.py:24: 
    DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. 
    Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn

/tmp/tmpn0w4l6w9/virtualenv-16.7.11/virtualenv.py:25: 
    DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  import distutils.sysconfig

Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/mihamina/lib/azure-cli/bin/python3
Also creating executable in /home/mihamina/lib/azure-cli/bin/python
ERROR: The executable /home/mihamina/lib/azure-cli/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/usr' (should be '/home/mihamina/lib/azure-cli')
ERROR: virtualenv is not compatible with this system or executable
```

### Related command

`curl -L https://aka.ms/InstallAzureCli | bash`

### Errors

```
[mihamina@arch-00 ~]$ curl -L https://aka.ms/InstallAzureCli | bash
[...]
Running install script.
-- Verifying Python version.
-- Python version 3.11.3 okay.

[...]

-- Executing: ['/usr/bin/python3', 'virtualenv.py', '--python', '/usr/bin/python3', '/home/mihamina/lib/azure-cli']
/tmp/tmpn0w4l6w9/virtualenv-16.7.11/virtualenv.py:24: 
    DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. 
    Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn

/tmp/tmpn0w4l6w9/virtualenv-16.7.11/virtualenv.py:25: 
    DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  import distutils.sysconfig

Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/mihamina/lib/azure-cli/bin/python3
Also creating executable in /home/mihamina/lib/azure-cli/bin/python
ERROR: The executable /home/mihamina/lib/azure-cli/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/usr' (should be '/home/mihamina/lib/azure-cli')
ERROR: virtualenv is not compatible with this system or executable

```

### Issue script & Debug output

```
[mihamina@arch-00 ~]$ curl -L https://aka.ms/InstallAzureCli | bash
[...]
Running install script.
-- Verifying Python version.
-- Python version 3.11.3 okay.

[...]

-- Executing: ['/usr/bin/python3', 'virtualenv.py', '--python', '/usr/bin/python3', '/home/mihamina/lib/azure-cli']
/tmp/tmpn0w4l6w9/virtualenv-16.7.11/virtualenv.py:24: 
    DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. 
    Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn

/tmp/tmpn0w4l6w9/virtualenv-16.7.11/virtualenv.py:25: 
    DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  import distutils.sysconfig

Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/mihamina/lib/azure-cli/bin/python3
Also creating executable in /home/mihamina/lib/azure-cli/bin/python
ERROR: The executable /home/mihamina/lib/azure-cli/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/usr' (should be '/home/mihamina/lib/azure-cli')
ERROR: virtualenv is not compatible with this system or executable

```

### Expected behavior

Expectation is just that the install script executes.

### Environment Summary

Az CLI cannot be installed.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
I believe you are following https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script, but this script is also almost "deprecated". You may use other approaches to install Azure CLI:

- Use a native package manager, such as `apt`, `dnf` and `tdnf`: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli
- Manually create a virtual environment with built-in library `venv` and install with `pip`: https://github.com/Azure/azure-cli/issues/20476

**Comment by rakotomandimby** [comment]
@jiasli  ,

I use ArchLinux, the package manager is Pacman, provid ethe package and I will use it.

Otherwise, if the code we are talking about is **deprecated**, we have to requalify this issue to "Mark this script or documentation as deprecated"

Or also, we can requalify this to "Update the documentation"

**Comment by rakotomandimby** [comment]
@jiasli , Never mind: I will adopt the non-official new way https://mihamina.rktmb.org/2023/06/azurecli-custom-python.html

**Comment by MarkGetsauce** [comment]
2 years passed and still the same issue. Not everyone, I would dare to say more and more developers, using Ubuntu or RHEL. 
Arch and other rolling distros are much popular, especially among developers and still the official documentation last updated only a few months ago: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest&pivots=script refers to what  seems to be "almost deprecated since 2023" way of installing.
Why is this closed as completed I have no idea.

**Comment by rakotomandimby** [comment]
@MarkGetsauce , use the non-official new way https://mihamina.rktmb.org/2023/06/azurecli-custom-python.html ;-)
