### ISSUE TITLE
Microsoft.GraphServices Azure CLI module request

### ISSUE THREAD

**Issue by amatukmolina** [Azure/azure-cli#26598]
### Resource Provider

Microsoft.GraphServices/Accounts

### Description of Feature or Work Requested

We own the Resource Provider called Microsoft.GraphServices, and as part of the APEX launch readiness process we want help with the development and release of the Azure CLI package for our service. (we're working in parallel to get powershell and terraform packages). 

This is an overview of what our service does, which is enabling metered APIs in Microsoft Graph: https://learn.microsoft.com/en-us/graph/metered-api-overview

This documentation gives an overview on the type of commands our Public Preview users are executing to interact with our RP. https://learn.microsoft.com/en-us/graph/metered-api-setup?tabs=azurecloudshell

Also, if this is helpful, here's the Azure REST documentation of our Public Preview service: https://learn.microsoft.com/en-us/rest/api/graphservices/

### Minimum API Version Required

2023-04-13

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/graphservicesprod/resource-manager/Microsoft.GraphServices/stable/2023-04-13/graphservicesprod.json

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/graphservicesprod/resource-manager/Microsoft.GraphServices/stable/2023-04-13/examples/Accounts_Create.json

### Target Date

2023-08-01

### Additional context

The main reason we want to release this module is because of the requirement from APEX to have a consistent experience throughout all services that go to GA, so we are open to hear your guidance on how we can help this go as smoothly as possible.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jsntcy** [comment]
@amatukmolina, now we have a [new codegen tool](https://azure.github.io/aaz-dev-tools/) which is UI based and easy to use. We encourage your team to use it to generate CLI commands automatically as nobody knows your logic better than your team. Using our new codegen tool, you can have the following benefits:
- Shorten development cycle (save 50%+ development time, if no block issues, usually it takes less than 1 week).
- Directly generate CLI commands from swagger instead of waiting for SDK release.
- Consistent code style improves command quality and avoids code review efforts.

**Comment by carlosov-ms** [comment]
@amatukmolina pls check it out if you haven't done so, thanks!

**Comment by jsntcy** [comment]
@carlosov-ms, @amatukmolina, have you started the CLI work using codegen tool I mentioned above?

**Comment by amatukmolina** [comment]
@jsntcy  Yes, here's the PR for cli and aaz repos [[GraphServices] Add Microsoft.GraphServices cli module by amatukmolina · Pull Request #26785 · Azure/azure-cli (github.com)](https://github.com/Azure/azure-cli/pull/26785) and [Add Microsoft.GraphServices module by amatukmolina · Pull Request #217 · Azure/aaz (github.com)](https://github.com/Azure/aaz/pull/217). But we need some help moving it forward, there's some issues in the pipeline that haven't been resolved and we don't know if it's on us

**Comment by jsntcy** [comment]
Implemented in https://github.com/Azure/azure-cli-extensions/pull/6487
