### ISSUE TITLE
Eventhub CleanupPolicy (Compaction) not working through az cli

### ISSUE THREAD

**Issue by mathias-olsen** [Azure/azure-cli#26599]
### Describe the bug

When attempting to create an eventhub with: `--cleanup-policy Compaction` this results in a Json deserialization error.

### Related command

az eventhubs eventhub create
(--cleanup-policy Compaction)

### Errors

(RequestJsonDeserializationFailure) Failed to deserialize input. Got error message: Error converting value "Compaction" to type 'Microsoft.ServiceBus.Messaging.CleanupPolicy'. Path 'properties.retentionDescription.cleanupPolicy', line 1, position 91.
Code: RequestJsonDeserializationFailure

### Issue script & Debug output

cli.knack.cli: Command arguments: ['eventhubs', 'eventhub', 'create', '--name', 'removed', '--namespace-name', 'removed', '--resource-group', 'removed', '--cleanup-policy', 'Compaction', '--partition-count', '3', '--status', 'active', '--tombstone-retention-time-in-hours', '24', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01B9A418>, <function OutputProducer.on_global_arguments at 0x01D68BB0>, <function CLIQuery.on_global_arguments at 0x01D87808>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'eventhubs': ['azure.cli.command_modules.eventhubs']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: eventhubs                 0.323        15        25
cli.azure.cli.core: Total (1)                 0.323        15        25
cli.azure.cli.core: Loaded 15 groups, 25 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : eventhubs eventhub create
cli.azure.cli.core: Command table: eventhubs eventhub create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03F2B340>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\removed\.azure\commands\2023-06-03.11-12-16.eventhubs_eventhub_create.4048.log'.
az_command_data_logger: command args: eventhubs eventhub create --name {} --namespace-name {} --resource-group {} --cleanup-policy {} --partition-count {} --status {} --tombstone-retention-time-in-hours {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03F54610>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03F64538>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03F64730>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01D68BF8>, <function CLIQuery.handle_query_parameter at 0x01D87850>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03F646E8>]
Command group 'eventhubs eventhub' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\removed\\.azure\\service_principal_entries.bin', encrypt=True
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\removed\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\removed\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.application: Broker enabled? False
msal.application: Region to be used: None
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: ServicePrincipalCredential.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
msal.application: Cache hit an AT
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/removed?api-version=2022-10-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '151'
cli.azure.cli.core.sdk.policies:     'CommandName': 'eventhubs eventhub create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --namespace-name --resource-group --cleanup-policy --partition-count --status --tombstone-retention-time-in-hours --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.49.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.19045-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"partitionCount": 3, "retentionDescription": {"cleanupPolicy": "Compaction", "tombstoneRetentionTimeInHours": 24}, "status": "Active"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/removed?api-version=2022-10-01-preview HTTP/1.1" 400 283
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '283'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Sat, 03 Jun 2023 09:12:19 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"RequestJsonDeserializationFailure","message":"Failed to deserialize input. Got error message: Error converting value \"Compaction\" to type 'Microsoft.ServiceBus.Messaging.CleanupPolicy'. Path 'properties.retentionDescription.cleanupPolicy', line 1, position 91."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/eventhubs/operations/event_hub_entity.py", line 57, in cli_eventhub_create
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 149, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/eventhubs/aaz/latest/eventhubs/eventhub/_create.py", line 30, in _handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/eventhubs/aaz/latest/eventhubs/eventhub/_create.py", line 165, in _execute_operations
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/eventhubs/aaz/latest/eventhubs/eventhub/_create.py", line 189, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_operation.py", line 326, in on_error
azure.core.exceptions.HttpResponseError: (RequestJsonDeserializationFailure) Failed to deserialize input. Got error message: Error converting value "Compaction" to type 'Microsoft.ServiceBus.Messaging.CleanupPolicy'. Path 'properties.retentionDescription.cleanupPolicy', line 1, position 91.
Code: RequestJsonDeserializationFailure
Message: Failed to deserialize input. Got error message: Error converting value "Compaction" to type 'Microsoft.ServiceBus.Messaging.CleanupPolicy'. Path 'properties.retentionDescription.cleanupPolicy', line 1, position 91.

cli.azure.cli.core.azclierror: (RequestJsonDeserializationFailure) Failed to deserialize input. Got error message: Error converting value "Compaction" to type 'Microsoft.ServiceBus.Messaging.CleanupPolicy'. Path 'properties.retentionDescription.cleanupPolicy', line 1, position 91.
Code: RequestJsonDeserializationFailure
Message: Failed to deserialize input. Got error message: Error converting value "Compaction" to type 'Microsoft.ServiceBus.Messaging.CleanupPolicy'. Path 'properties.retentionDescription.cleanupPolicy', line 1, position 91.
az_command_data_logger: (RequestJsonDeserializationFailure) Failed to deserialize input. Got error message: Error converting value "Compaction" to type 'Microsoft.ServiceBus.Messaging.CleanupPolicy'. Path 'properties.retentionDescription.cleanupPolicy', line 1, position 91.
Code: RequestJsonDeserializationFailure
Message: Failed to deserialize input. Got error message: Error converting value "Compaction" to type 'Microsoft.ServiceBus.Messaging.CleanupPolicy'. Path 'properties.retentionDescription.cleanupPolicy', line 1, position 91.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03F2B460>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 2.096 seconds (init: 0.701, invoke: 1.395)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4027 in cache

### Expected behavior

Eventhub created with cleanup policy set to Compact/Compaction

### Environment Summary

{
  "azure-cli": "2.49.0",
  "azure-cli-core": "2.49.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by CleverJosh** [comment]
@Saglodha - for those of us with broken CD Pipelines - do you have a proposed workaround until the fix is released.

I have the same issue.

My script was previously working. Though, we were setting '--message-retention' optional parameter. That started breaking suddenly. So, I've adjusted the command according to [the documentation](https://learn.microsoft.com/en-us/cli/azure/eventhubs/eventhub?view=azure-cli-latest) with '--cleanup-policy' and 'retention-time' parameters set. I, of course, have met the same end as @mathias-olsen.

Would you propose that '--cleanup-policy' and 'retention-time' be removed completely until the fix is released? Or, is there a value that can be supplied as the '--cleanup-policy' parameter that will parse correctly?

**Comment by Saglodha** [comment]
Hello @CleverJosh, 

Unfortunately, this was a bug that was affecting other clients like ARM template etc. so we couldn't suggest a workaround here. That being said, the fix has been completed and should be merged with next release cycle for CLI (planned release for 07/04/2023). 

Apologies for the issue caused here, please let us know in case of any additional feedback.

**Comment by CleverJosh** [comment]
Thanks for the follow up, @Saglodha  - much appreciated.
