### ISSUE TITLE
Installer fails due to urllib problem

### ISSUE THREAD

**Issue by kfiresmith** [Azure/azure-cli#2659]
Urllib sends malformed gets through our proxy that simply won't work with a proxy that scrutinizes TLS connections.  From what I gather urllib has a long torrid history w/ HTTPS and perhaps something like Requests should be used instead.  

Here's where the problems start:
https://github.com/Azure/azure-cli/blob/master/scripts/curl_install_pypi/install.py#L121

`2017-03-28 19:27:53 my.ip.address - - invalid_request DENIED "Technology/Internet" - 400 TCP_NC_MISS GET - https pypi.python.org 443 /packages/source/v/virtualenv/virtualenv-15.0.0.tar.gz - gz "Python-urllib/1.17" 151.101.32.223 867 126 -`

**Comment by kfiresmith** [comment]
Similar issue - potentially related:  http://bugs.python.org/issue1424152

**Comment by derekbekoe** [comment]
@kfiresmith Were you referring to [this requests](https://pypi.python.org/pypi/requests)?
The script can only use packages available as part of Python and Requests is a separate module.
Can you use pip to install? `pip install --user azure-cli`

**Comment by kfiresmith** [comment]
Hi @derekbekoe  - Yea, good point, it's not a core package, Requests.  I don't have a good solution for making this behave properly with BlueCoat enterprise proxies.  The problem still stands, but the solution I originally proposed appears moot.  

To *work around* this, I built a Docker image off the proxy and just pull that.  Not optimal.

**Comment by derekbekoe** [comment]
Closing this and marking as FAQ as it's not actionable and there are other install methods available.
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
