### ISSUE TITLE
Incorrect parameter reference for azure-monitor-metrics

### ISSUE THREAD

**Issue by pichuang** [Azure/azure-cli#26600]
### Describe the bug

There is a parameter reference error in az aks for enabling Azure Monitor metrics

### Related command

Incorrect Command

```
az aks create --enable-azure-monitor-metrics
```

Correct Command
```
az aks create --enable-azuremonitormetrics
```

### Errors

Line 90: az aks create -n poc1-aks -g rg-poc1-aks -l EastUS --kubernetes-version 1.26.3 --enable-cluster-autoscaler --azure-monitor-workspace-resource-id /subscriptions/xxx-xxx-xxx-xxx/resourceGroups/rg-poc1-aks/providers/microsoft.operationalinsights/workspaces/amw-poc1-aks --grafana-resource-id /subscriptions/xxx-xxx-xxx-xxx/resourceGroups/rg-poc1-aks/providers/microsoft.grafana/grafana/grafana-poc1-aks --max-count 2 --min-count 1 --tier standard --max-pods 250 --auto-upgrade-channel stable --dns-name-prefix poc1-aks --enable-managed-identity --node-count 2 --node-vm-size Standard_B4ms --network-plugin azure --network-policy azure --vnet-subnet-id /subscriptions/xxx-xxx-xxx-xxx/resourceGroups/rg-poc1-aks/providers/Microsoft.Network/virtualNetworks/vnet-poc1-aks/subnets/subnet-nodepool --pod-subnet-id /subscriptions/xxx-xxx-xxx-xxx/resourceGroups/rg-poc1-aks/providers/Microsoft.Network/virtualNetworks/vnet-poc1-aks/subnets/subnet-podpool --enable-addons ingress-appgw --enable-azure-monitor-metrics --appgw-name agic-poc1-aks --appgw-subnet-id /subscriptions/xxx-xxx-xxx-xxx/resourceGroups/rg-poc1-aks/providers/Microsoft.Network/virtualNetworks/vnet-poc1-aks/subnets/subnet-agic

**unrecognized arguments: --enable-azure-monitor-metrics**

### Issue script & Debug output

**unrecognized arguments: --enable-azure-monitor-metrics**

### Expected behavior

`--enable-azure-monitor-metrics` should work, or all docs need to fix to `--enable-azuremonitormetrics`

### Environment Summary

$ az version
{
  "azure-cli": "2.49.0",
  "azure-cli-core": "2.49.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "aks-preview": "0.5.141",
    "amg": "1.2.5",
    "arcdata": "1.5.0",
    "azure-firewall": "0.14.7",
    "bastion": "0.2.4",
    "connectedk8s": "1.3.20",
    "customlocation": "0.1.3",
    "k8s-configuration": "1.7.0",
    "k8s-extension": "1.4.1",
    "ssh": "1.1.6",
    "virtual-wan": "0.2.17"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by pichuang** [comment]
Upstream source code: https://github.com/Azure/azure-cli-extensions/blob/main/src/aks-preview/azext_aks_preview/_help.py#L963-L965

**Comment by navba-MSFT** [comment]
@pichuang Apologies for the late reply. Thanks for reaching out to us and reporting this issue. The above PR has been filed to fix the docs.

**Comment by navba-MSFT** [comment]
@pichuang Please note another PR was filed above to fix the aks-preview CLI extension. https://github.com/Azure/azure-cli-extensions/pull/6379

This PR was to Deprecate option names `--enable-azuremonitormetrics` and` --disable-azuremonitormetrics`, use `--enable-azure-monitor-metrics` and `--disable-azure-monitor-metrics` instead, so as to be consistent with the option names in official azure-cli.

**Comment by navba-MSFT** [comment]
@pichuang The above PR is now merged.
