### ISSUE TITLE
az login started failing today

### ISSUE THREAD

**Issue by xiaodoli** [Azure/azure-cli#26609]
### Describe the bug

observed az login failing ~12PM PST. both interactive and devicecode failed with the following error on windows:

az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46(Microsoft Azure CLI). Resource value from request: https://management.azlr.onmicrosoft.com/8cfa8f6a-6010-4fd7-b962-827f81f87a6f. Resource app ID: bab1fbec-0954-45f2-9f29-227abd4c6eb2. List of valid resources from app registration: .
Trace ID: 8cf6bdc1-aa72-4969-a09b-39ac34767c00
Correlation ID: bc43f691-1e87-4a6b-a836-762715f2bd7a
Timestamp: 2023-06-05 22:58:36Z

on linux when using `az login --use-device-code`, there is error on web browser:

![image](https://github.com/Azure/azure-cli/assets/19724544/754ede88-be2b-4d24-a590-138ea583f6a3)

### Related command

az login

### Errors

from linux using `az login --use-device-code`, got this error:
The account needs to be added as an external user in the tenant first. Please use a different account.

from windows using `az login --use-device-code` or `az login`, got this error:

AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46(Microsoft Azure CLI). Resource value from request: https://management.azlr.onmicrosoft.com/8cfa8f6a-6010-4fd7-b962-827f81f87a6f. Resource app ID: bab1fbec-0954-45f2-9f29-227abd4c6eb2. List of valid resources from app registration: .

### Issue script & Debug output

NA

### Expected behavior

should be able to login to azure

### Environment Summary

az version # linux
{
  "azure-cli": "2.49.0",
  "azure-cli-core": "2.49.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}

az version # windows
{
  "azure-cli": "2.37.0",
  "azure-cli-core": "2.37.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
It seems you are logging into an Azure Stack cloud you registered with 

```
az cloud register --endpoint-active-directory-resource-id https://management.azlr.onmicrosoft.com/8cfa8f6a-6010-4fd7-b962-827f81f87a6f
```

but there are some configurations issues in that cloud.

> from linux using `az login --use-device-code`, got this error:
> The account needs to be added as an external user in the tenant first. Please use a different account.

You need to confirm whether the user has been invited as a guest user in that tenant. See https://learn.microsoft.com/en-us/azure/active-directory/external-identities/b2b-quickstart-add-guest-users-portal

> from windows using `az login --use-device-code` or `az login`, got this error:
> 
> AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46(Microsoft Azure CLI). Resource value from request: https://management.azlr.onmicrosoft.com/8cfa8f6a-6010-4fd7-b962-827f81f87a6f. Resource app ID: bab1fbec-0954-45f2-9f29-227abd4c6eb2. List of valid resources from app registration: .

This indicates the first-party app pre-authorization is not configurated correctly for Azure CLI (04b07795-8ddb-461a-bbee-02f9e1bf7b46). You will need to contact tenant admin to get that fixed.
