### ISSUE TITLE
Reservations module output not working as planned when using tsv or table output

### ISSUE THREAD

**Issue by hharsunen** [Azure/azure-cli#26607]
### Describe the bug

When using `-otsv` or `-otable` as the output format, it doesn't work as planned. Output is not tsv or table formatted

### Related command

az reservations catalog show --reserved-resource-type virtualmachines --location westeurope --subscription-id REDACTED -otsv

az reservations catalog show --reserved-resource-type virtualmachines --location westeurope --subscription-id REDACTED -otable

### Errors

command will output
https://management.azure.com/subscriptions/REDACTED/providers/Microsoft.Capacity/catalogs?location=westeurope&reservedResourceType=virtualmachines&api-version=2022-11-01&%24skip=50        <number>     <number>

### Issue script & Debug output

n/a

### Expected behavior

the output formatting should be table or space-separated formatted list/table

### Environment Summary

  "azure-cli": "2.49.0",
  "azure-cli-core": "2.49.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5",
    "automation": "0.2.1",
    "reservation": "0.3.0",
    "resource-graph": "2.1.0",
    "ssh": "1.1.6"

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@hharsunen Thanks for reaching out to us and reporting this issue. While I ran the same CLI command, I got the response output in the Tab separated values and also in table format. See below:

![image](https://github.com/Azure/azure-cli/assets/57353862/6a1f0561-2ef2-449d-b4d3-45a125930c24)

![image](https://github.com/Azure/azure-cli/assets/57353862/ab2c6f85-ac77-42b4-bf1e-6d9a4bf98c1c)

**Note**: I am using the same Azure CLI version with the same `reservation` extension version as your scenario.

**Comment by navba-MSFT** [comment]
@hharsunen As shown in my above screenshot only the parent json property values would be displayed. Please note that the **nested** property values will not appear in table format by default. You could try to use the [JMESPath query path to query the required field. ](https://learn.microsoft.com/en-us/cli/azure/format-output-azure-cli#table-output-format:~:text=parameter%20to%20customize%20the%20properties%20and%20columns%20you%20want%20to%20show%20in%20the%20list%20output.)
