### ISSUE TITLE
[DocumentDB] Listing connection strings doesn't support table output by default

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2660]
Running the following command results in a blank line being printed:

```shell
az documentdb list-connection-strings -n <NAME> -g <GROUP>
```

You can obviously use a custom output type, but it would be ideal if this command printed a table of connection strings by default.

**Comment by shurd** [comment]
This has been addressed. The API call to our resource provider that the CLI makes returns connection strings based on the account API.
