### ISSUE TITLE
[DocumentDB] Display MongoDB connection string immediately after creation

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2661]
The new `az documentdb list-connection-strings` command is awesome, however, it would be helpful if the MongoDB connection string were displayed immediately after calling `az documentdb create --kind MongoDB`. Right now, the `create` command displays the DocumentDB connection string immediately after creation, however, this is potentially confusing for a user who might try to use that to connect their Mongo-client to it (which wouldn't be successful?), or would need to then go figure out that they have to call the `list-connection-strings` command in order to actually get the correct connection string.

**Comment by lostintangent** [comment]
Actually, this looks to be an issue with the `az documentdb show` command as well, so assuming that `create` simply calls `show` upon completion of creating a new instance, it would be ideal if the `show` command displayed the MongoDB connection string for instances whose `Kind` is `MongoDB`.

**Comment by shurd** [comment]
Our resource provider does not return account keys when retrieving the database account as users with read only permissions can make this request. For consistency across our management tools, we are leaving account keys out of the response for now. You can either use `list-connection-strings` to view the account connection strings or `list-keys` to construct the connection strings.
