### ISSUE TITLE
associate resources to data collection endpoint

### ISSUE THREAD

**Issue by ipetko96** [Azure/azure-cli#26628]
**Related command**

**Is your feature request related to a problem? Please describe.**
I am not sure, but how can I associate existing resources to existing data collection endpoint.
In portal there is `+` button to select resources that will be associated, but I need to achieve this through API.

**Describe the solution you'd like**
New command something like `az monitor data-collection endpoint association create` would be useful.

**Describe alternatives you've considered**
I also tried to go from the other side and create association in the data collection rule with `az monitor data-collection rule association create` but there is the same problem, no way of select and associate existing data collection endpoint.

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jt-osuk** [comment]
Another customer with the same problem, we are starting to make use of DCR and have thousands of resources (machines) to associate to the DCR's via the Data Collection Endpoint.

**Comment by lckstrb** [comment]
I am also in the same situation but using PowerShell commands. How can I assciate vms to data collection endpoint (not data collection rule)? 
The command which I could find, New-AzDataCollectionRuleAssociation can only be used to associate resources to data collection rule not to data collection endpoint...

**Comment by ipetko96** [comment]
@lckstrb for now, you have few options on how to associate VMs to data collection endpoint. If you want to do it programmatically,  look at these two options: [templates](https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/datacollectionruleassociations) or [REST API](https://learn.microsoft.com/en-us/rest/api/monitor/data-collection-rule-associations/create)  
Third option is to manually click it in the Azure portal, which is good only for small number of VMs or for development\testing purposes.

**Comment by AllyW** [comment]
@ipetko96 @lckstrb  Parameter `endpoint-id` has been added into `az monitor data-collection rule association create ` which allows endpoint-id associated to a resource and released in azure extension already. Run `az extension add --name monitor-control-service --upgrade` and you'll get the new functionality.

**Comment by unixsubhasish17** [comment]
Hello @AllyW ,

Thanks but it seems there is another issue while passing endpoint-id while creating association for a DCR,

➜  ~ az monitor data-collection rule association create --name "performance" --rule-id "/subscriptions/xxxxxxx/resourceGroups/RG/providers/Microsoft.Insights/dataCollectionRules/performance" --resource "/subscriptions/xxxxxxxx/resourceGroups/RG/providers/Microsoft.Compute/virtualMachines/abcdefg" --endpoint-id "/subscriptions/xxxxxxxxx/resourceGroups/Shared-RG/providers/Microsoft.Insights/dataCollectionEndpoints/dce"
Error: Association name for resource to endpoint must be configurationAccessEndpoint

Any idea what is going wrong here?

**Comment by ipetko96** [comment]
I can confirm, I was also able to reproduce this issue. After calling this command:
`az monitor data-collection rule association create --name myAssociation --rule-id XXX --resource XXX --endpoint-id XXX`
I get this exception:
```
(InvalidEndpointAssociationName) An association of data collection endpoint must be named 'configurationAccessEndpoint'.
Code: InvalidEndpointAssociationName
Message: An association of data collection endpoint must be named 'configurationAccessEndpoint'.
Exception Details:      (InvalidEndpointAssociationName) An association of data collection endpoint must be named 'configurationAccessEndpoint'.
        Code: InvalidEndpointAssociationName
        Message: An association of data collection endpoint must be named 'configurationAccessEndpoint'.
        Target: name
```
The reason why I did not report it earlier after implementing new parameter, was that we circumvent missing feature with bicep template, and even after parameter was added to az cli I didn't want to rework whole functioning deployment. And yes, in bicep there is exactly this name configurationAccessEndpoint

bicep template look like this:
```
resource association 'Microsoft.Insights/dataCollectionRuleAssociations@2022-06-01' = {
  dependsOn: [
    vm
  ]
  name: 'configurationAccessEndpoint'
  scope: vm
  properties: {
    dataCollectionEndpointId: dce_id
  }
}

```

**Comment by unixsubhasish17** [comment]
Hello @ipetko96 ,

Yes, and thanks for your response. I was able to figure out last night about this. 

This is really confusing and no where we found any document about it. 

Ideally, we should not use data collection rule-id and endpoint id together. For example,

when we associate resource with DCR, we should not use endpoint id in the same command, so just to make it clear:

# az monitor data-collection rule association create --name "DCR_NAME" --rule-id "DCR_Rule_ID" --resource "VM_Resource_ID" ==> In this command if we pass --endpoint-id it will always return error.

So, to associate endpoint-id with VM, 

# az monitor data-collection rule association create --name "configurationAccessEndpoint" --resource "VM_resource_ID" --endpoint-id "Endpoint_ID"

I am totally surprise that this thing is not explicitly mentioned in the MS documents or may be its mentioned but I had a hard time to find it.

Anyway, thanks for your reply and I will get back to my work.

Have a nice evening !!

Thanks
Subhasish

**Comment by bhaskar39** [comment]
> I can confirm, I was also able to reproduce this issue. After calling this command: `az monitor data-collection rule association create --name myAssociation --rule-id XXX --resource XXX --endpoint-id XXX` I get this exception:
> 
> ```
> (InvalidEndpointAssociationName) An association of data collection endpoint must be named 'configurationAccessEndpoint'.
> Code: InvalidEndpointAssociationName
> Message: An association of data collection endpoint must be named 'configurationAccessEndpoint'.
> Exception Details:      (InvalidEndpointAssociationName) An association of data collection endpoint must be named 'configurationAccessEndpoint'.
>         Code: InvalidEndpointAssociationName
>         Message: An association of data collection endpoint must be named 'configurationAccessEndpoint'.
>         Target: name
> ```
> 
> The reason why I did not report it earlier after implementing new parameter, was that we circumvent missing feature with bicep template, and even after parameter was added to az cli I didn't want to rework whole functioning deployment. And yes, in bicep there is exactly this name configurationAccessEndpoint
> 
> bicep template look like this:
> 
> ```
> resource association 'Microsoft.Insights/dataCollectionRuleAssociations@2022-06-01' = {
>   dependsOn: [
>     vm
>   ]
>   name: 'configurationAccessEndpoint'
>   scope: vm
>   properties: {
>     dataCollectionEndpointId: dce_id
>   }
> }
> ```

The documentation did to mention anything about it. I have a requirement where I want to loop over data collection rules for a VM, then I cannot have the same name and it gives an error. For example, the following does not work.

resource vmassociation 'Microsoft.Insights/dataCollectionRuleAssociations@2021-04-01'= [ for x in dcrs:{
  name: '${x.dcrname}${virtualMachineName}-association'
  scope: virtualMachine
  properties: {
    dataCollectionEndpointId: dce.id
    dataCollectionRuleId: resourceId(x.dcrresourceGroup,'Microsoft.Insights/dataCollectionRules', x.dcrname)
  }
}]

Is it bug or is it by design?

**Comment by juliovaz96** [comment]
Same issue happening here... any updates @AllyW @yonzhan ?

**Comment by juliovaz96** [comment]
Hello guys,
Just a quick update on the solution I found on how to associate a DCE to an Azure Resource using Terraform or via Azure CLI:

For some reason, the only allowed value from Azure API for the "**name:**" parameter is **"configurationAccessEndpoint"**. I realized it only applies to the Data Collection ENDPOINT (DCE) association resource. DCR Association can have a different name value.
