### ISSUE TITLE
az ad sp delete claims to delete role assignments but it doesn't

### ISSUE THREAD

**Issue by Nothing4You** [Azure/azure-cli#26629]
### Describe the bug

https://learn.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-delete

> az ad sp delete: Delete a service principal and its role assignments.

This command only deletes the service principal but not its role assignments.

This appears to have been an intentional change and is likely just incorrect documentation/help message at this point.

### Related command

az ad sp delete

### Errors

N/A

### Issue script & Debug output

N/A

### Expected behavior

Role assignments are removed when the SP is deleted.

### Environment Summary

```
azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Extensions:
ai-examples                        0.2.5
cloud-service                      0.2.0
ml                                2.17.2
reservation                        0.2.0
ssh                                1.1.6

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/usr/bin/python3.9'
Extensions directory '/home/admin/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Feb  8 2023, 03:39:52) 
[GCC 11.2.0]
```

### Additional context

#20805 indicates that this is intentional
#22432 performed the change
https://learn.microsoft.com/en-us/cli/azure/microsoft-graph-migration#az-ad-sp-delete documents that the behavior was changed.

Both CLI docs at https://learn.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-delete and `az ad sp delete --help` indicate that role assignments would be removed.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
We can't blame the bot @azure-client-tools-bot-prd for providing the incorrect similar issue. After all, it only calculates the similarity but has no real intelligence to understand the meaning of those issues. 😆

**Comment by yonzhan** [comment]
Add @bebound for awareness about similar bot.
