### ISSUE TITLE
List examples of TrustedLaunchSupported and TrustedLaunchAndConfidentialVmSupported

### ISSUE THREAD

**Issue by sandeepraichura** [Azure/azure-cli#26632]
### Describe the bug

Please add examples to use TrustedLaunchSupported and TrustedLaunchAndConfidentialVmSupported in the CLI documentation. 
Also provide a link to public docs where we have listed out all the SecurityTypes supported by different galleries based on sharing scope (private, direct shared and community gallery)

https://learn.microsoft.com/en-us/azure/virtual-machines/shared-image-galleries?tabs=azure-cli#image-definitions

### Related command

`
az sig image-definition create --resource-group MyResourceGroup \
--gallery-name MyGallery --gallery-image-definition MyImage \
--publisher GreatPublisher --offer GreatOffer --sku GreatSku \
--os-type linux --os-state Specialized \
--features SecurityType=TrustedLaunchSupported
`
**TrustedLaunchSupported is a generic Gen2 image that does not contain the VMGS blob. Gen2 VM or TrustedLaunch VM can be created from this image type.

`
az sig image-definition create --resource-group MyResourceGroup \
--gallery-name MyGallery --gallery-image-definition MyImage \
--publisher GreatPublisher --offer GreatOffer --sku GreatSku \
--os-type linux --os-state Specialized \
--features SecurityType=TrustedLaunchAndConfidentialVmSupported
`
**TrustedLaunchAndConfidentialVmSupported is a generic Gen2 image that does not contain the VMGS blob. Gen2 VM, TrustedLaunch VM, or a ConfidentialVM can be created from this image type.

### Errors

na

### Issue script & Debug output

na

### Expected behavior

na

### Environment Summary

azure-cli

### Additional context

Already provided the commands above

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
