### ISSUE TITLE
[REDIS] `az redis create` doesn't wait for provisioning to complete

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#2663]
When running `az redis create` the command returns while the provisioning state is still `Creating`. Unless `--no-wait` is applied, I'd expect the command to return upon completing provisioning.

**Comment by devigned** [comment]
Hmm... perhaps it doesn't wait b/c it would take a while. I'm still waiting to see a Standard1 provision after ~20 mins.

**Comment by alfantp** [comment]
Provisioning could take a long time depending on the underlying VM create time and/or the number of shards the customer is provisioning. Didn't want the command to wait on it

**Comment by tjprescott** [comment]
@alfantp is this modeled as a Long Running Operation in swagger?  It sounds like it should be. In the CLI, if it is a LRO, then it will poll by default until complete. Command authors will then typically expose a `--no-wait` option to short-circuit the polling, as well as a "wait" command to allow for polling later. 

```
az foo create -n foo1 --no-wait
az foo create -n foo2 --no-wait
az foo wait -n foo1 --created
az foo wait -n foo2 --created
```

This is kind of like joining thread. The effect is that the creation of foo1 and foo2 will happen in parallel but the script will not continue until both are created. 

https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#register-commands

This has guidance on using `wait_command` and a section on "supporting --no-wait"

**Comment by MECHANDR** [comment]
redis create command takes long time based on the sku, size and shards being provisioned. Updating create command to have --no-wait will break existing users.
@haroldrandom Can you please close this issue

**Comment by haroldrandom** [comment]
Why having --no-wait breaks existing users? Many commands support --no-wait which let user retrieve status of his/her creating resources.

Can't redis do that?

**Comment by MECHANDR** [comment]
Existing users are calling redis create command without --no-wait, and the command returns immediately indicating that the cache is being created. If --no-wait option is added to create command, existing calls without --no-wait will suffer with long waiting times.

**Comment by haroldrandom** [comment]
--no-wait is optional not mandatory. Exsiting users should have choice whether enable --no-wait or not.

Adding --no-wait has no affect on existing users as far as I know. If user want to add --no-wait, redis should return status like `pending` indicating that resource is still under preparing and not fully available for now.

**Comment by MECHANDR** [comment]
If --no-wait is implemented for redis create command:
1. When user call with --no-wait option, redis will return with status like creating.
2. When user calls without --no-wait option, redis will wait until cache is successfully provisioned and then it will return. Existing user will experience long waiting behavior, as they aren't providing --no-wait option

**Comment by haroldrandom** [comment]
Sounds good. This is an expected behavior like other CLI commands.

**Comment by MECHANDR** [comment]
Yes. But this change will result in breaking existing user scripts, as they will end up waiting for long times. Shouldn't this be handled in better way?

**Comment by haroldrandom** [comment]
Currently, when creating redis, command with --no-wait will return immediately and return a status indicating that redis is under creating like --no-wait already supported?

**Comment by MECHANDR** [comment]
Currently redis create doesn't support --no-wait, so running create with or without --no-wait will return immediately and indicate cache is being created.

**Comment by haroldrandom** [comment]
@MyronFanQiu @tjprescott What do you think?

**Comment by haroldrandom** [comment]
Redis [spec of 2017](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/redis/resource-manager/Microsoft.Cache/stable/2017-10-01/redis.json) and [spec of 2018](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/redis/resource-manager/Microsoft.Cache/stable/2018-03-01/redis.json) marked this operation as **long running operation**, but the actual behavior is not as expected. It's a history mistake.

Considering that current user did't report or vote similar problem and also redis is a frequently used service of Azure, correcting this behavior would break many user's daily work which confusing them a lot and consuming their a lot of time to figure out.

So, it's fine to close.

However, If new user report similar question like this, redis service should fix that we think.
