### ISSUE TITLE
az ssh vm fails due to use of http:// instead of https://

### ISSUE THREAD

**Issue by kl298p** [Azure/azure-cli#26631]
### Describe the bug

I'm on MacOS Ventura running azure cli 2.49.0 -- latest version. I've tried running `az ssh vm` to get the SSH extension added, however it fails because of a HTTP request being made to pypi.python.org instead of HTTPS. The error is very clear:

**Could not fetch URL http://pypi.python.org/simple/oschmod/**: 403 Client Error: **SSL is required for url:** 

Please change the URL to http**s**://pypi.python.org/simple/oschmod/

### Related command

az extension add --name ssh  --debug

### Errors

Processing /var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl
  Added ssh==1.1.6 from file:///var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl to build tracker '/private/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/pip-build-tracker-q_dxc0ng'
  Removed ssh==1.1.6 from file:///var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl from build tracker '/private/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/pip-build-tracker-q_dxc0ng'
1 location(s) to search for versions of oschmod:
* http://pypi.python.org/simple/oschmod/
Fetching project page and analyzing links: http://pypi.python.org/simple/oschmod/
Getting page http://pypi.python.org/simple/oschmod/
Found index url http://pypi.python.org/simple/
Starting new HTTP connection (1): pypi.python.org:80
http://pypi.python.org:80 "GET /simple/oschmod/ HTTP/1.1" 403 16
Could not fetch URL http://pypi.python.org/simple/oschmod/: 403 Client Error: SSL is required for url: http://pypi.python.org/simple/oschmod/ - skipping
Skipping link: not a file: http://pypi.python.org/simple/oschmod/
Given no hashes to check 0 links for project 'oschmod': discarding no candidates
ERROR: Could not find a version that satisfies the requirement oschmod==0.3.12 (from ssh) (from versions: none)
ERROR: No matching distribution found for oschmod==0.3.12

### Issue script & Debug output

yes | az ssh vm --debug
cli.knack.cli: Command arguments: ['ssh', 'vm', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x10cbc6440>, <function OutputProducer.on_global_arguments at 0x10cc7b520>, <function CLIQuery.on_global_arguments at 0x10ccb09d0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: No module found from index for '['ssh', 'vm', '--debug']'
cli.azure.cli.core: Loading all modules and extensions
cli.azure.cli.core: Discovered command modules: ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'config', 'configure', 'consumption', 'container', 'cosmosdb', 'databoxedge', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'identity', 'interactive', 'iot', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'marketplaceordering', 'monitor', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'resource', 'role', 'search', 'security', 'servicebus', 'serviceconnector', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'synapse', 'util', 'vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acr                       0.138        34       144
cli.azure.cli.core: acs                       0.022         6        48
cli.azure.cli.core: advisor                   0.001         3         6
cli.azure.cli.core: ams                       0.015        22       100
cli.azure.cli.core: apim                      0.006        11        60
cli.azure.cli.core: appconfig                 0.003         8        42
cli.azure.cli.core: appservice                0.053        73       260
cli.azure.cli.core: aro                       0.011         1         8
cli.azure.cli.core: backup                    0.004        16        58
cli.azure.cli.core: batch                     0.026        36       104
cli.azure.cli.core: batchai                   0.003        10        30
cli.azure.cli.core: billing                   0.007        19        52
cli.azure.cli.core: botservice                0.003        12        42
cli.azure.cli.core: cdn                       0.006        39       133
cli.azure.cli.core: cloud                     0.002         1         7
cli.azure.cli.core: cognitiveservices         0.002         8        31
cli.azure.cli.core: config                    0.002         2         7
cli.azure.cli.core: configure                 0.001         2         5
cli.azure.cli.core: consumption               0.002         8         9
cli.azure.cli.core: container                 0.009         1        11
cli.azure.cli.core: cosmosdb                  0.010        57       191
cli.azure.cli.core: databoxedge               0.005         5        27
cli.azure.cli.core: dla                       0.004        23        62
cli.azure.cli.core: dls                       0.003         7        41
cli.azure.cli.core: dms                       0.002         3        22
cli.azure.cli.core: eventgrid                 0.005        25        96
cli.azure.cli.core: eventhubs                 0.013        13        19
cli.azure.cli.core: extension                 0.001         1         7
cli.azure.cli.core: feedback                  0.001         1         2
cli.azure.cli.core: find                      0.001         1         1
cli.azure.cli.core: hdinsight                 0.008         8        39
cli.azure.cli.core: identity                  0.002         2        11
cli.azure.cli.core: interactive               0.000         1         1
cli.azure.cli.core: iot                       0.097        19        82
cli.azure.cli.core: keyvault                  0.009        22       131
cli.azure.cli.core: kusto                     0.003         3        14
cli.azure.cli.core: lab                       0.004        11        34
cli.azure.cli.core: managedservices           0.002         3         8
cli.azure.cli.core: maps                      0.002         5        13
cli.azure.cli.core: marketplaceordering       0.003         1         2
cli.azure.cli.core: monitor                   0.038        26        80
cli.azure.cli.core: netappfiles               0.005        17        94
cli.azure.cli.core: network                   0.597       101       324
cli.azure.cli.core: policyinsights            0.013         9        17
cli.azure.cli.core: privatedns                0.005        14        66
cli.azure.cli.core: profile                   0.002         2         9
cli.azure.cli.core: rdbms                     0.149        55       230
cli.azure.cli.core: redis                     0.002         5        27
cli.azure.cli.core: relay                     0.004        10        37
cli.azure.cli.core: resource                  0.011        47       209
cli.azure.cli.core: role                      0.003        17        61
cli.azure.cli.core: search                    0.002         7        22
cli.azure.cli.core: security                  0.005        48       104
cli.azure.cli.core: servicebus                0.011        12        14
cli.azure.cli.core: serviceconnector          0.012         8       129
cli.azure.cli.core: servicefabric             0.015        26        75
cli.azure.cli.core: signalr                   0.002         8        30
cli.azure.cli.core: sql                       0.019        55       207
cli.azure.cli.core: sqlvm                     0.049         4        20
cli.azure.cli.core: storage                   0.041        58       272
cli.azure.cli.core: synapse                   0.013        54       246
cli.azure.cli.core: util                      0.002         3         7
cli.azure.cli.core: vm                        0.125        57       265
cli.azure.cli.core: Total (63)                1.613      1166      4505
cli.azure.cli.core: Loaded 1156 groups, 4505 commands.
cli.azure.cli.core: Updated command index in 0.005 seconds.
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x10d7540d0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/kl298p/.azure/commands/2023-06-07.06-12-10.ssh.99284.log'.
az_command_data_logger: command args: ssh {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x10d774b80>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x10d7928c0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x10d7929e0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x10e5ede10>]
cli.knack.prompting: No tty available.
cli.azure.cli.core.extension.dynamic_install: The command requires the extension ssh. It will be installed first.
urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool: https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool: Starting new HTTPS connection (1): azcliextensionsync.blob.core.windows.net:443
urllib3.connectionpool: https://azcliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 2873331
cli.azure.cli.core.extension._resolve: Candidates ['ssh-0.1.0-py3-none-any.whl', 'ssh-0.1.4-py3-none-any.whl', 'ssh-0.1.5-py3-none-any.whl', 'ssh-0.1.6-py3-none-any.whl', 'ssh-0.1.7-py3-none-any.whl', 'ssh-0.1.8-py3-none-any.whl', 'ssh-1.0.0-py3-none-any.whl', 'ssh-1.0.1-py3-none-any.whl', 'ssh-1.1.0-py3-none-any.whl', 'ssh-1.1.1-py3-none-any.whl', 'ssh-1.1.2-py3-none-any.whl', 'ssh-1.1.3-py3-none-any.whl', 'ssh-1.1.4-py3-none-any.whl', 'ssh-1.1.5-py3-none-any.whl', 'ssh-1.1.6-py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['ssh-0.1.0-py3-none-any.whl', 'ssh-0.1.4-py3-none-any.whl', 'ssh-0.1.5-py3-none-any.whl', 'ssh-0.1.6-py3-none-any.whl', 'ssh-0.1.7-py3-none-any.whl', 'ssh-0.1.8-py3-none-any.whl', 'ssh-1.0.0-py3-none-any.whl', 'ssh-1.0.1-py3-none-any.whl', 'ssh-1.1.0-py3-none-any.whl', 'ssh-1.1.1-py3-none-any.whl', 'ssh-1.1.2-py3-none-any.whl', 'ssh-1.1.3-py3-none-any.whl', 'ssh-1.1.4-py3-none-any.whl', 'ssh-1.1.5-py3-none-any.whl', 'ssh-1.1.6-py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['ssh-0.1.0-py3-none-any.whl', 'ssh-0.1.4-py3-none-any.whl', 'ssh-0.1.5-py3-none-any.whl', 'ssh-0.1.6-py3-none-any.whl', 'ssh-0.1.7-py3-none-any.whl', 'ssh-0.1.8-py3-none-any.whl', 'ssh-1.0.0-py3-none-any.whl', 'ssh-1.0.1-py3-none-any.whl', 'ssh-1.1.0-py3-none-any.whl', 'ssh-1.1.1-py3-none-any.whl', 'ssh-1.1.2-py3-none-any.whl', 'ssh-1.1.3-py3-none-any.whl', 'ssh-1.1.4-py3-none-any.whl', 'ssh-1.1.5-py3-none-any.whl', 'ssh-1.1.6-py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['ssh-0.1.0-py3-none-any.whl', 'ssh-0.1.4-py3-none-any.whl', 'ssh-0.1.5-py3-none-any.whl', 'ssh-0.1.6-py3-none-any.whl', 'ssh-0.1.7-py3-none-any.whl', 'ssh-0.1.8-py3-none-any.whl', 'ssh-1.0.0-py3-none-any.whl', 'ssh-1.0.1-py3-none-any.whl', 'ssh-1.1.0-py3-none-any.whl', 'ssh-1.1.1-py3-none-any.whl', 'ssh-1.1.2-py3-none-any.whl', 'ssh-1.1.3-py3-none-any.whl', 'ssh-1.1.4-py3-none-any.whl', 'ssh-1.1.5-py3-none-any.whl', 'ssh-1.1.6-py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Chosen {'downloadUrl': 'https://azcliprod.blob.core.windows.net/cli-extensions/ssh-1.1.6-py3-none-any.whl', 'filename': 'ssh-1.1.6-py3-none-any.whl', 'metadata': {'azext.isPreview': False, 'azext.minCliCoreVersion': '2.45.0', 'classifiers': ['Development Status :: 4 - Beta', 'Intended Audience :: Developers', 'Intended Audience :: System Administrators', 'Programming Language :: Python', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'License :: OSI Approved :: MIT License'], 'extensions': {'python.details': {'contacts': [{'email': 'azpycli@microsoft.com', 'name': 'Microsoft Corporation', 'role': 'author'}], 'document_names': {'description': 'DESCRIPTION.rst'}, 'project_urls': {'Home': 'https://github.com/Azure/azure-cli-extensions/tree/main/src/ssh'}}}, 'extras': [], 'generator': 'bdist_wheel (0.30.0)', 'license': 'MIT', 'metadata_version': '2.0', 'name': 'ssh', 'run_requires': [{'requires': ['oschmod (==0.3.12)']}], 'summary': 'SSH into Azure VMs using RBAC and AAD OpenSSH Certificates', 'version': '1.1.6'}, 'sha256Digest': 'ed727dbe18994db27d22b4c1fdc28a6bfa0a91670042389b0534838f9eb235e1'}
cli.azure.cli.core.extension.operations: Extension source is url? True
cli.azure.cli.core.extension.operations: Downloading https://azcliprod.blob.core.windows.net/cli-extensions/ssh-1.1.6-py3-none-any.whl to /var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl
urllib3.connectionpool: Starting new HTTPS connection (1): azcliprod.blob.core.windows.net:443
urllib3.connectionpool: https://azcliprod.blob.core.windows.net:443 "GET /cli-extensions/ssh-1.1.6-py3-none-any.whl HTTP/1.1" 200 207567
cli.azure.cli.core.extension.operations: Downloaded to /var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl
cli.azure.cli.core.extension.operations: Validating the extension /var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl
cli.azure.cli.core.extension.operations: Checksum of /var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl is OK
cli.azure.cli.core.extension.operations: Validation successful on /var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl
cli.azure.cli.core.extension.operations: Linux distro check: Reading from: /etc/apt/sources.list.d/azure-cli.list
cli.azure.cli.core.extension.operations: Linux distro check: An error occurred while checking linux distribution version source list consistency.
cli.azure.cli.core.extension.operations: [Errno 2] No such file or directory: '/etc/apt/sources.list.d/azure-cli.list'
cli.azure.cli.core.extension.operations: Executing pip with args: ['install', '--target', '/Users/kl298p/.azure/cliextensions/ssh', '/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl']
cli.azure.cli.core.extension._homebrew_patch: Homebrew patch: Temporarily creating /Users/kl298p/.pydistutils.cfg to support extension installation on Homebrew.
cli.azure.cli.core.extension.operations: Running: ['/usr/local/Cellar/azure-cli/2.49.0/libexec/bin/python', '-m', 'pip', 'install', '--target', '/Users/kl298p/.azure/cliextensions/ssh', '/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']
cli.azure.cli.core.extension.operations: Using pip 23.0.1 from /usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/pip (python 3.10)
Non-user install due to --prefix or --target option
Created temporary directory: /private/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/pip-target-c_umu_eg
Created temporary directory: /private/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/pip-build-tracker-q_dxc0ng
Initialized build tracking at /private/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/pip-build-tracker-q_dxc0ng
Created build tracker: /private/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/pip-build-tracker-q_dxc0ng
Entered build tracker: /private/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/pip-build-tracker-q_dxc0ng
Created temporary directory: /private/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/pip-install-7uqm9hnd
Created temporary directory: /private/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/pip-ephem-wheel-cache-dzwwqn2h
Looking in indexes: http://pypi.python.org/simple/
Processing /var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl
  Added ssh==1.1.6 from file:///var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl to build tracker '/private/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/pip-build-tracker-q_dxc0ng'
  Removed ssh==1.1.6 from file:///var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl from build tracker '/private/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/pip-build-tracker-q_dxc0ng'
1 location(s) to search for versions of oschmod:
* http://pypi.python.org/simple/oschmod/
Fetching project page and analyzing links: http://pypi.python.org/simple/oschmod/
Getting page http://pypi.python.org/simple/oschmod/
Found index url http://pypi.python.org/simple/
Starting new HTTP connection (1): pypi.python.org:80
http://pypi.python.org:80 "GET /simple/oschmod/ HTTP/1.1" 403 16
Could not fetch URL http://pypi.python.org/simple/oschmod/: 403 Client Error: SSL is required for url: http://pypi.python.org/simple/oschmod/ - skipping
Skipping link: not a file: http://pypi.python.org/simple/oschmod/
Given no hashes to check 0 links for project 'oschmod': discarding no candidates
ERROR: Could not find a version that satisfies the requirement oschmod==0.3.12 (from ssh) (from versions: none)
ERROR: No matching distribution found for oschmod==0.3.12
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 385, in resolve
    raise ResolutionImpossible(self.state.backtrack_causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('oschmod==0.3.12'), parent=LinkCandidate('file:///var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 101, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for oschmod==0.3.12
Removed build tracker: '/private/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/pip-build-tracker-q_dxc0ng'

cli.azure.cli.core.extension.operations: Command '['/usr/local/Cellar/azure-cli/2.49.0/libexec/bin/python', '-m', 'pip', 'install', '--target', '/Users/kl298p/.azure/cliextensions/ssh', '/var/folders/wp/r9cz533965x68m1cn7zmjhw00000gp/T/tmpprbvtlpe/ssh-1.1.6-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
cli.azure.cli.core.extension._homebrew_patch: Homebrew patch: Deleting the temporarily created /Users/kl298p/.pydistutils.cfg
cli.azure.cli.core.extension.operations: Pip failed so deleting anything we might have installed at /Users/kl298p/.azure/cliextensions/ssh
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 588, in execute
    parsed_args = self.parser.parse_args(args)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
  File "/usr/local/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 1833, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/usr/local/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 1866, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 2061, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/local/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 2038, in consume_positionals
    take_action(action, args)
  File "/usr/local/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 1927, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/parser.py", line 272, in _get_values
    value = super(AzCliCommandParser, self)._get_values(action, arg_strings)
  File "/usr/local/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 2472, in _get_values
    self._check_value(action, value[0])
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/parser.py", line 300, in _check_value
    use_dynamic_install = try_install_extension(self, args)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/extension/dynamic_install.py", line 119, in try_install_extension
    _check_value_in_extensions(cli_ctx, parser, args, use_dynamic_install == 'yes_without_prompt')
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/extension/dynamic_install.py", line 227, in _check_value_in_extensions
    add_extension(cli_ctx=cli_ctx, extension_name=ext_name, upgrade=True)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 344, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/extension/operations.py", line 173, in _add_whl_ext
    raise CLIError('An error occurred. Pip failed with status code {}. '
knack.util.CLIError: An error occurred. Pip failed with status code 1. Use --debug for more information.

cli.azure.cli.core.azclierror: An error occurred. Pip failed with status code 1. Use --debug for more information.
az_command_data_logger: An error occurred. Pip failed with status code 1. Use --debug for more information.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x10d754310>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 13.734 seconds (init: 0.166, invoke: 13.568)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3636 in cache
telemetry.check: Negative: The /Users/kl298p/.azure/telemetry.txt was modified at 2023-06-07 06:02:42.196889, which in less than 600.000000 s

### Expected behavior

Please change the URL to http**s**://pypi.python.org/simple/oschmod/ and I expect it will work.

### Environment Summary

az --version
azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/usr/local/Cellar/azure-cli/2.49.0/libexec/bin/python'
Extensions directory '/Users/kl298p/.azure/cliextensions'

Python (Darwin) 3.10.12 (main, Jun  7 2023, 00:45:35) [Clang 14.0.3 (clang-1403.0.22.14.1)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
`ssh` extension doesn't explicitly specify the location of `oschmod` as `http://pypi.python.org/simple/oschmod/`.

Instead, the URL is constructed by `pip`:

https://github.com/Azure/azure-cli-extensions/blob/7ec9e12fc67c11ebb0f05707d7ab2f40b2550f2c/src/ssh/setup.py#L25

```py
DEPENDENCIES = [
    'oschmod==0.3.12'
]
```

In my test, `pip` already uses `https`:

```
> az extension add -n ssh --debug
...
1 location(s) to search for versions of oschmod:
* https://pypi.org/simple/oschmod/
Fetching project page and analyzing links: https://pypi.org/simple/oschmod/
Getting page https://pypi.org/simple/oschmod/
Found index url https://pypi.org/simple/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/oschmod/ HTTP/1.1" 200 5973
```

Please verify if you have changed `pip`'s [Configuration](https://pip.pypa.io/en/stable/topics/configuration/) and set `index-url` to `http://pypi.python.org/simple/`. If so, please remove such configuration.

**Comment by kl298p** [comment]
I simply turned http into https and the extension installed correctly. Thanks a lot for the tip!

**Comment by sukhdev-vyash** [comment]
I am still facing the same error can someone please help.

While installing az ssh extension on VDI machine.

* https://pypi.org/simple/oschmod/
Fetching project page and analyzing links: https://pypi.org/simple/oschmod/
Getting page https://pypi.org/simple/oschmod/
Found index url https://pypi.org/simple
Starting new HTTPS connection (1): pypi.org:443
Incremented Retry for (url='/simple/oschmod/'): Retry(total=4, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))': /simple/oschmod/
Starting new HTTPS connection (2): pypi.org:443
Incremented Retry for (url='/simple/oschmod/'): Retry(total=3, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))': /simple/oschmod/
Starting new HTTPS connection (3): pypi.org:443
Incremented Retry for (url='/simple/oschmod/'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))': /simple/oschmod/
Starting new HTTPS connection (4): pypi.org:443
Incremented Retry for (url='/simple/oschmod/'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))': /simple/oschmod/
Starting new HTTPS connection (5): pypi.org:443
Incremented Retry for (url='/simple/oschmod/'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))': /simple/oschmod/
Starting new HTTPS connection (6): pypi.org:443
Could not fetch URL https://pypi.org/simple/oschmod/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/oschmod/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)'))) - skipping
Skipping link: not a file: https://pypi.org/simple/oschmod/
Given no hashes to check 0 links for project 'oschmod': discarding no candidates
ERROR: Could not find a version that satisfies the requirement oschmod==0.3.12 (from ssh) (from versions: none)
ERROR: No matching distribution found for oschmod==0.3.12

Any fix for it.
