### ISSUE TITLE
az cloud commands don't return anything

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-cli#26646]
### Describe the bug

`az cloud` commands don't return anything, which makes it an edge case when handling output result when compared to other commands.

For example, "az cloud set" doesn't return anything:
https://github.com/Azure/azure-cli/blob/8e7d910a378d5405ecd1fa0760e78a3ddd4b6f04/src/azure-cli/azure/cli/command_modules/cloud/custom.py#L151

Other functions also return nothing like "az cloud update" and etc. `az cloud` commands should return objects as appropriate as specified by the command guidelines:
https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#standard-command-types

### Related command

az cloud

### Errors

No errors, just unexpected behavior.

### Issue script & Debug output

No errors, just unexpected behavior.

### Expected behavior

`az cloud` commands should return objects as appropriate specified by the command guidelines:
https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#standard-command-types

### Environment Summary

PS C:\Users\Administrator> az --version
azure-cli                         2.49.0
core                              2.49.0
telemetry                          1.0.8
Extensions:
azure-devops                      0.26.0
Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Administrator\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
The current behavior is not to show anything for `set` commands. Same thing happens to `az account set` (https://github.com/Azure/azure-cli/pull/15978). 

I will send out an email to you to start an internal discussion.
