### ISSUE TITLE
Is resourceGroup for az servicebus namespace list supposed to be required?

### ISSUE THREAD

**Issue by mathiasi** [Azure/azure-cli#26644]
### Describe the bug

Documentation ( https://learn.microsoft.com/en-us/cli/azure/servicebus/namespace?view=azure-cli-latest#az-servicebus-namespace-list ) lists `az servicebus namespace list` as an example which used to work in the past. However sometime between now and version 2.42.0, `--resource-group` became a required parameter. I can't seem to find anything the release notes mentioning this breaking change and since the documentation still lists the example without the parameter, I'm wondering if it was an intended change?
With the change we cannot query across the entire subscription anymore.

### Related command

az servicebus namespace list

### Errors

the following arguments are required: --resource-group/-g

### Issue script & Debug output

cli.knack.cli: Command arguments: ['servicebus', 'namespace', 'list', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x032FB460>, <function OutputProducer.on_global_arguments at 0x034C7BF8>, <function CLIQuery.on_global_arguments at 0x034E9850>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'servicebus': ['azure.cli.command_modules.servicebus']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: servicebus                0.479        16        28
cli.azure.cli.core: Total (1)                 0.479        16        28
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 16 groups, 28 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : servicebus namespace list
cli.azure.cli.core: Command table: servicebus namespace list
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03F2B388>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\MAIM\.azure\commands\2023-06-09.13-08-14.servicebus_namespace_list.392.log'.
az_command_data_logger: command args: servicebus namespace list --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03F53388>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03F63460>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03F634F0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
urllib3.connectionpool: Starting new HTTPS connection (1): app.aladdin.microsoft.com:443
urllib3.connectionpool: https://app.aladdin.microsoft.com:443 "GET /api/v1.0/suggestions?query=%7B%22command%22%3A+%22servicebus+namespace+list%22%2C+%22parameters%22%3A+%22%22%7D&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.49.0%22%2C+%22errorType%22%3A+%22MissingRequiredParameters%22%2C+%22correlationId%22%3A+%2256dea47e-c136-44b3-a786-cbd89d80089d%22%2C+%22subscriptionId%22%3A+%224f4a9748-17ed-4dde-8134-d60793ebc2e2%22%2C+%22eventId%22%3A+%22111933f4-4b8f-474d-b26c-e8b3c7770dfe%22%7D HTTP/1.1" 200 None
cli.azure.cli.core.azclierror: NoneType: None

cli.azure.cli.core.azclierror: the following arguments are required: --resource-group/-g
az_command_data_logger: the following arguments are required: --resource-group/-g

Examples from AI knowledge base:
az servicebus namespace list
List the Service Bus Namespaces under subscription

az servicebus namespace list --resource-group myresourcegroup
List the Service Bus Namespaces under resourcegroup.

https://aka.ms/cli_ref
Read more about the command in reference docs
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03F2B4A8>]
az_command_data_logger: exit code: 2
cli.__main__: Command ran in 1.883 seconds (init: 0.894, invoke: 0.988)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3595 in cache
telemetry.check: Negative: The C:\Users\MAIM\.azure\telemetry.txt was modified at 2023-06-09 13:07:43.381650, which in less than 600.000000 s

### Expected behavior

List all namespaces in subscription

### Environment Summary

azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Extensions:
azure-devops                      0.25.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\MAIM\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mathiasi** [comment]
I realize it appears to be a duplicate of #25900
