### ISSUE TITLE
Support 2023_03_01 api version with az vmss create / update

### ISSUE THREAD

**Issue by madhoolikag** [Azure/azure-cli#26642]
### Related command

az vmss create
az vmss update

### Resource Provider

Microsoft.Compute

### Description of Feature or Work Requested

Some of the **VMSS Flex** features are enabled for use from the 2023_03_01 api version eg. VM Customization support for VMSS Flex where customer specifies the values via parameters --vcpus-available and --vcpus-per-core. 
Although there are no validations / checks on the cli side blocking the setting of these parameters for Flex specifically, since our service only supports the usage of these properties from the 2023_03_01 api version and cli is currently using the 2022_03_01 api version, we are unable to utilize this feature. 

Ask: Upgrade the az vmss create / update commands to support 2023_03_01 api version

### Minimum API Version Required

2023_03_01

### Swagger PR link / SDK link

https://msazure.visualstudio.com/DefaultCollection/One/_git/Compute-CPlat-Core/pullrequest/7592537

### Target Date

2023_06_25

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@madhoolikag We plan to develop and release it in the next sprint *(the release date is **08-01**)*. Does it meet your expectations?

**Comment by zhoxing-ms** [comment]
@madhoolikag  Sorry, our reply was late due to the Chinese Dragon Boat Festival holiday. In fact, **08-01** is already the fastest release time we can support at present.

**Comment by yanzhudd** [comment]
Hi @madhoolikag 
do we only need to upgrade the api version of "vmss", excluding "vm", to "2023-03-01"?

**Comment by madhoolikag** [comment]
Yes, the requirement is for the VMSS requests to be utilizing a 2023_03_01 api version. No change wrt the VM request api version.

**Comment by yanzhudd** [comment]
@madhoolikag thanks for your quick reply. 
Is there any other change need to be made, such as adding new parameter for `az vmss create/update` command?

**Comment by madhoolikag** [comment]
No @yanzhudd, I believe the vCpusAvailable and vCpusPerCore parameters are already supported. And for VMSS Flex, there are no validations preventing these properties from being sent in the request body right?

**Comment by yanzhudd** [comment]
@madhoolikag yes, for VMSS Flex, there are no validations preventing the vCpusAvailable and vCpusPerCore from being sent in the request body.

**Comment by madhoolikag** [comment]
@yanzhudd When can we see the usage of updated api version in cli?

**Comment by yonzhan** [comment]
Code complete: 07/26/2023 Build to Cloud Shell: 07/28/2023 Official Release: 08/01/2023
Azure CLI version: 2.51.0

**Comment by madhoolikag** [comment]
Thanks for confirming!
