### ISSUE TITLE
Doc bug: Incorrect command in the docs

### ISSUE THREAD

**Issue by iouri-s** [Azure/azure-cli#26660]
### Describe the bug

https://learn.microsoft.com/en-us/cli/azure/bicep?view=azure-cli-latest&source=docs mentions the following command:

[1] az config set bicep.version_check=True/False Turn on/off Bicep CLI version check when executing az bicep commands.

### Related command

az config set bicep.version_check=True/False

### Errors

It doesn't do anything

### Issue script & Debug output

# az config set bicep.version_check=False
Command group 'config' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
# az bicep build --file ../../Stack.AzureDeployment/Infrastructure/RegionDeployment/Bicep/main.bicep
A new Bicep release is available: v0.18.4. Upgrade now by running "az bicep upgrade".

### Expected behavior

No Upgrade nag

### Environment Summary

{
  "azure-cli": "2.48.1",
  "azure-cli-core": "2.48.1",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "aks-preview": "0.5.137"
  }
}

### Additional context

The correct command is az config set bicep.check_version=True/False, not az config set bicep.version_check=True/False

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@iouri-s 
Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
