### ISSUE TITLE
Prompt for a confirmation while deleting ExpressRoute Direct resource

### ISSUE THREAD

**Issue by rakshithtr** [Azure/azure-cli#26678]
**Related command**
az network express-route port delete

**Is your feature request related to a problem? Please describe.**
When Cx runs the above command to delete ExpressRoute Direct resource, we want to ask for a confirmation from the Cx. This is the message that needs to be shown to Cx  

"Deletion of ExpressRoute Direct requires disconnection of physical cross-connects. Please confirm that you have
completed this step in coordination with your Colo provider. Are you sure you want to remove resource '<resource_name>'"

**Describe the solution you'd like**
These are steps expected:
1. Cx deletes  an ExpresRoute Direct resource.
2. CLI should prompt the above message on display and ask for a confirmation.
3. If Yes=> Continue with deletion as done today. If No=> Just exit and do not delete

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@rakshithtr PR description is too rough, please fill it out.

**Comment by rakshithtr** [comment]
@necusjz Sorry, had forgot to remove the , so my description was not showing up. I have not updated it. Please let me know if you need any other information. Thanks.
