### ISSUE TITLE
The repository 'https://packages.microsoft.com/repos/azure-cli bookworm Release' does not have a Release file

### ISSUE THREAD

**Issue by RAutomation** [Azure/azure-cli#26686]
### Describe the bug

**Getting below error while running commands**

_The repository 'https://packages.microsoft.com/repos/azure-cli bookworm Release' does not have a Release file_

**Command**: RUN apt-get update --yes \
&& apt-get install --yes \
    azure-cli \
    dotnet-runtime-2.1 \
&& rm -rf /var/lib/apt/lists/*

### Related command

RUN apt-get update --yes \
&& apt-get install --yes \
    azure-cli \
    dotnet-runtime-2.1 \
&& rm -rf /var/lib/apt/lists/*

### Errors

The repository 'https://packages.microsoft.com/repos/azure-cli bookworm Release' does not have a Release file

### Issue script & Debug output

The repository 'https://packages.microsoft.com/repos/azure-cli bookworm Release' does not have a Release file

### Expected behavior

It should run as expected

### Environment Summary

NA

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Debian bookworm is not supported yet. Tracked by https://github.com/Azure/azure-cli/issues/25750.

**Comment by bebound** [comment]
The bookworm package is built but it's not released yet.

Close this as tracked by #25750.
