### ISSUE TITLE
"az containerapp up" will sometimes use a container app environment that the container app IS NOT located in

### ISSUE THREAD

**Issue by msha1026** [Azure/azure-cli#26688]
### Describe the bug

When using a `az containerapp up` with an existing container app, the logs will show that the command is using a different container app environment than the one the existing container app is already deployed to. For the most part, it does seem like the command does not actually use that environment that it logged, but we have had a handful of times where it will error out because it does use that incorrect environment.

### Related command

`az containerapp up -g <RG-Name> -n <Existing-Container-App> --image <some-image>`

### Errors

Here is the intermittent error we have seen (removed resource names):
```
WARNING: Using resource group '<MY-RESOURCE-GROUP>'
WARNING: Using ContainerAppEnvironment '<different-container-app-env-in-same-RG>' in resource group <MY-RESOURCE-GROUP>
WARNING: Updating Containerapp <existing-container-app> in resource group <MY-RESOURCE-GROUP>
WARNING: Adding registry password as a secret with name "***azurecrio-***"
ERROR: (ContainerAppEnvironmentMismatch) Container App '<existing-container-app>' already exists in a different environment. To create it in the environment '/subscriptions/***/resourceGroups/<MY-RESOURCE-GROUP>/providers/Microsoft.App/managedEnvironments/<different-container-app-env-in-same-RG>' delete it from the environment '<correct-container-app-env>' first.
```

### Issue script & Debug output

There is a lot of customer data in the debug log.

### Expected behavior

When using `az containerapp up -n` with the name of an existing container app, I expect the command to update the existing container app without a dependency on the container app environment name being needed.

### Environment Summary

```
azure-cli                         2.44.1 *

core                              2.44.1 *
telemetry                          1.0.8

Extensions:
azure-iot                         0.17.1
containerapp                      0.3.23
ml                                2.10.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by msha1026** [comment]
Update, azcli 2.49.0 was used during this error.

**Comment by navba-MSFT** [comment]
Non customer reported. Adding Service attention label.

**Comment by Greedygre** [comment]
Hi @msha1026 

For exiting containerapp, you can try this command, the difference is **not input the resource group** : 
`az containerapp up  -n <Existing-Container-App> --image <some-image>
`

Thanks!

**Comment by Greedygre** [comment]
> Hi @msha1026
> 
> For an existing containerapp, you can try this command, the difference is **not input the resource group** : `az containerapp up -n <Existing-Container-App> --image <some-image> `
> 
> Thanks!

This has been fixed in extension, you can also try it with new containerapp extension version:
`az extension add -n containerapp --upgrade
`
