### ISSUE TITLE
Update API Version used by AZCLI for Microsoft.KubernetesConfiguration from 2022-11-01 to 2023-05-01

### ISSUE THREAD

**Issue by blazepower** [Azure/azure-cli#26680]
### Related command

`az k8s-extension create`
`az k8s-extension update`

### Resource Provider

Microsoft.KubernetesConfiguration

### Description of Feature or Work Requested

Update API version used by AZCLI.

### Minimum API Version Required

2023-05-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/23676

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/60598e96cec040ea9862e89b9f84055dd6386d2c/specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/examples/CreateExtension.json

### Target Date

ASAP

### Additional context

This is a breaking change. 

We need to update our API version for our AZCLI commands to version `2023-05-01`.  This change adds new functionality for our users to support our GA release of Container Marketplace and also contains a **breaking change** for commands: `az k8s-extension create` and `az k8s-extension update`.  This breaking change fixes a bug that has caused numerous customer reported incidents since its introduction.

### The Bug
On the installation of our resources, customers are allowed to specify various parameters. Two such parameters, version and autoUpgradeMinorVersion) are conflicting. If version is specified, autoUpgradeMinorVersion MUST be false. We had validation to ensure that these conflicting values were not provided together, but there was a bug with that validation where it was not applied. There was a further bug where if version was specified, the autoUpgradeMinorVersion was ignored. This has led to confusion from customers and instances of our resources not performing as expected.

### The Breaking Change
The breaking change we have introduced with API version 2023-05-01 adds the missing validation and we will begin rejecting calls (PUT and PATCH) that provide a version and set autoUpgradeMinorVersion to true.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by blazepower** [comment]
@yonzhan any update as to when we will receive a follow-up?

**Comment by NarayanThiru** [comment]
KubernetesConfiguration feature is in deprecation path.  It is replaced with FluxConfiguration.  Adding @bavneetsingh16 to confirm and add any additional info.

**Comment by bavneetsingh16** [comment]
The api version '2023-05-01' is updated in 'k8s-extension' version [1.5.0](https://github.com/Azure/azure-cli-extensions/blob/main/src/k8s-extension/HISTORY.rst#150). Please update the cli extension using the below cmd:

 az extension update --name k8s-extension

**Comment by bavneetsingh16** [comment]
Closing this issue as the resolution steps are provided above.
