### ISSUE TITLE
webapp slot swap - add flag "if-target-older" or similar

### ISSUE THREAD

**Issue by cmcconomyfwig** [Azure/azure-cli#26697]
**Related command**
az webapp deployment slot swap

**Is your feature request related to a problem? Please describe.**
Yes - the nature of swaps is that you are swapping "whatever is in the two slots". As a caller, you have no idea whether you're swapping an intended staging content into production, or swapping back. You're swapping blind.  
If the current swap contents differ from your expectation, you could be performing an undesired swap

**Describe the solution you'd like**
I would like a flag, default false (to maintain current behaviour if not specified):
`--if-target-older`

This compare the latest "success end time" for the last "active" deployment in each slot, and would only invoke the swap IF the target slot is older than the source slot.

**Describe alternatives you've considered**
Currently, I run additional AZ commands to query the dates; this works, but I think it would be useful and a natural extension to the az cli command.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by cmcconomyfwig** [comment]
Just to detail the scenario I have in mind:

June 1: 
* I deploy code v2 for multiple different azure functions to staging
* Once ALL deployments are ready, I run a script to swap them all from staging to prod
* "staging" now contains v1 and "prod" contains v2

July 1:
* I deploy code v3 for multiple different azure functions to staging
* One of the projects didn't have any code changes, so no github action was triggered to deploy new code to staging
* Once all deployments are ready, I run a script to swap them all from staging to prod
* for all services, "staging" now contains v2 and "prod" contains v3
* EXCEPT for the one project that didn't deploy. there, I swapped V1 back into production slot and V2 back into staging!

If we check the dates, we avoid that accidental scenario (in this case where I have a script that attempts to swap ALL project)

**Comment by btardif** [comment]
@cmcconomyfwig this is a feature request, can you please submit it through or feedback forum:

https://feedback.azure.com/d365community/forum/b09330d1-c625-ec11-b6e6-000d3a4f0f1c?category_id=359425

**Comment by cmcconomyfwig** [comment]
Anyone looking to upvote this,

https://feedback.azure.com/d365community/idea/ed0bac8b-a60e-ee11-a81c-000d3adb7ffd
