### ISSUE TITLE
Enable Autoupgrade by default when creating Trusted Launch VM with enabled integrity monitoring

### ISSUE THREAD

**Issue by Bab95** [Azure/azure-cli#26705]
**Related command**
az vm create -n MyVm -g MyResourceGroup --image Ubuntu2204 --enable-secure-boot true --enable-vtpm true

**Is your feature request related to a problem? Please describe.**
As part of ongoing effort to make trusted launch as default we also install GuestAttestation Extension on the vm (which is an opt-out feature of trusted launch). GuestAttestation Extension does the VM attestation against Microsoft Azure Attestation. 
Currently whenever a new vm is created through Azure-CLI guest attestation extension is not autoupgrade enabled.  

**Describe the solution you'd like**
Requirement is whenever a new trusted launch vm is created through azure-cli and guest attestation extension is installed the extension should be autoupgrade enabled.

We already requested this autoupgrade enabled feature for az vm set extension [ref](https://github.com/Azure/azure-cli/issues/26252) , and would like the same for az vm create command as well.

**Describe alternatives you've considered**

N/A
**Additional context**

Resource Provider
Microsft.Compute/virtualMachines

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@Bab95 At present, if the VM created has Trusted Launch and integrity monitoring enabled, then GuestAttestation VM extension will be automatically installed *(related feature request: #21395)*. Do you want us to enable automatic upgrade by default for the GuestAttestation VM extension?
May I ask if this will cause a breaking change for customers?

**Comment by Bab95** [comment]
No, It should not be a breaking change. we would be just enabling the auto-upgrade flag and not requesting anything from customers.

**Comment by Bab95** [comment]
Moreover If possible we can give a flag to opt-out from auto-upgrade similar to opt-out of integrity-monitoring

**Comment by zhoxing-ms** [comment]
@Bab95 OK, could we add a new parameter `--disable-extension-autoupgrade` to opt-out from auto-upgrade for GuestAttestation VM extension.

**Comment by zhoxing-ms** [comment]
@Bab95 In addition, as our work is already fully arranged for this sprint, we plan to release this feature in the next sprint (on **08-01**). Does this date meet your expectations?

**Comment by Bab95** [comment]
just to summarize:
1. ```az vm create -n __vm_name__ --enable-secure-boot true --enable-vtpm true```
This will Create TrustedVM and install GuestAttestation Extension with autoupgrade enable for the extension
2. ```az vm create -n __vm_name__ --enable-secure-boot true --enable-vtpm true --disbale-extension-autoupgrade true```
This will create TrustedVM and install GuestAttestation Extension with autoupgrade disabled for the extension.
3. ```az vm create -n __cm_name__ --enable-secure-boot true --enable-vtpm true --disable-integrity-monitoring```
This will create TrustedVM but won't install GuestAttestation Extension.

Please confirm the above scenarios.

And I am concerned about the flag name. Can we make a more specific flag name. As it is for integrity monitoring it should reflect the same. For example
```--disable-integrity-monitoring-autoupgrade```

**Comment by zhoxing-ms** [comment]
> And I am concerned about the flag name. Can we make a more specific flag name. As it is for integrity monitoring it should reflect the same. For example
--disable-integrity-monitoring-autoupgrade

Make sense!

**Comment by Bab95** [comment]
@zhoxing-ms  can the same behavior replicated for vmss as well?

**Comment by zhoxing-ms** [comment]
@Bab95 OK~
