### ISSUE TITLE
Receiving 'BadRequest' for az role assignment create when using --assignee-principal-type ForeignGroup

### ISSUE THREAD

**Issue by CaseySHelp** [Azure/azure-cli#26700]
### Describe the bug

I am receiving the message: Principal 'principalid' does not exist in the directory 'customer tenant id'. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.

That principal id is from our partner tenant, not the tenant in which the command is running (hence the ForeignGroup). The command works correctly in any tenant that previously had GDAP configured prior to 6/1/2023.

### Related command

az role assignment create --assignee-object-id 'principalid' --role "Support Request Contributor" --scope "/subscriptions/subscriptionid" --assignee-principal-type ForeignGroup

### Errors

Principal {adminagentsgroupid} does not exist in the directory {clienttenantid}. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.

### Issue script & Debug output

PS C:\Windows\system32> az role assignment create --assignee-object-id {REDACTED-AdminAgentsGroupID} --role "Support Request Contributor" --scope "/subscriptions/{REDACTED-SubscriptionID}" --assignee-principal-type ForeignGroup --debug
cli.knack.cli: Command arguments: ['role', 'assignment', 'create', '--assignee-object-id', '{REDACTED-AdminAgentsGroupID}', '--role', 'Support Request Contributor', '--scope', '/subscriptions/{REDACTED-SubscriptionID}', '--assignee-principal-type', 'ForeignGroup', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0153B388>, <function OutputProducer.on_global_arguments at 0x01608B20>, <function CLIQuery.on_global_arguments at 0x01625778>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'role': ['azure.cli.command_modules.role']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: role                      0.006        17        61
cli.azure.cli.core: Total (1)                 0.006        17        61
cli.azure.cli.core: Loaded 17 groups, 61 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : role assignment create
cli.azure.cli.core: Command table: role assignment create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03FA3BF8>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\{REDACTED}\.azure\commands\2023-06-16.16-18-40.role_assignment_create.13980.log'.
az_command_data_logger: command args: role assignment create --assignee-object-id {} --role {} --scope {} --assignee-principal-type {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03FC9E38>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03FC9B20>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03FDF388>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01608B68>, <function CLIQuery.handle_query_parameter at 0x016257C0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03FDF340>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=AuthorizationManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\{REDACTED}\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\{REDACTED}\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/{REDACTED-CustomerTenantID}/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/{REDACTED-CustomerTenantID}/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{REDACTED-CustomerTenantID}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/{REDACTED-CustomerTenantID}/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/{REDACTED-CustomerTenantID}/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/{REDACTED-CustomerTenantID}/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/{REDACTED-CustomerTenantID}/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
msrest.universal_http.requests: Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
cli.azure.cli.core.commands.client_factory: Adding custom headers to the client:
cli.azure.cli.core.commands.client_factory:     'x-ms-client-request-id': 'fbf9b78d-0c82-11ee-872d-00155d32562c'
cli.azure.cli.core.commands.client_factory:     'CommandName': 'role assignment create'
cli.azure.cli.core.commands.client_factory:     'ParameterSetName': '--assignee-object-id --role --scope --assignee-principal-type --debug'
msrest.async_paging: Paging async iterator protocol is not available for RoleDefinitionPaged
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.signed_session
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Found 1 RTs matching {'environment': 'login.microsoftonline.com', 'home_account_id': '{REDACTED}', 'family_id': '1'}
msal.telemetry: Generate or reuse correlation_id: e9ef8200-3e4c-4aaf-9f40-7ae4f7f80da3
msal.application: Cache attempts an RT
urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com:443
urllib3.connectionpool: https://login.microsoftonline.com:443 "POST /{REDACTED-CustomerTenantID}/oauth2/v2.0/token HTTP/1.1" 200 4585
msal.token_cache: event={
    "client_id": "{REDACTED-ClientID}",
    "data": {
        "claims": "{\"access_token\": {\"xms_cc\": {\"values\": [\"CP1\"]}}}",
        "refresh_token": "********",
        "scope": [
            "https://management.core.windows.net//.default",
            "offline_access",
            "openid",
            "profile"
        ]
    },
    "environment": "login.microsoftonline.com",
    "grant_type": "refresh_token",
    "params": null,
    "response": {
        "access_token": "********",
        "client_info": "{REDACTED}",
        "expires_in": 4482,
        "ext_expires_in": 4482,
        "foci": "1",
        "id_token": "********",
        "scope": "https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default",
        "token_type": "Bearer"
    },
    "scope": [
        "https://management.core.windows.net//user_impersonation",
        "https://management.core.windows.net//.default"
    ],
    "skip_account_creation": true,
    "token_endpoint": "https://login.microsoftonline.com/{REDACTED-CustomerTenantID}/oauth2/v2.0/token"
}
msrest.http_logger: Request URL: 'https://management.azure.com/subscriptions/{REDACTED-SubscriptionID}/providers/Microsoft.Authorization/roleDefinitions?$filter=roleName%20eq%20%27Support%20Request%20Contributor%27&api-version=2018-01-01-preview'
msrest.http_logger: Request method: 'GET'
msrest.http_logger: Request headers:
msrest.http_logger:     'Accept': 'application/json'
msrest.http_logger:     'accept-language': 'en-US'
msrest.http_logger:     'User-Agent': 'python/3.10.8 (Windows-10-10.0.22621-SP0) msrest/0.7.1 msrest_azure/0.6.4 azure-mgmt-authorization/0.61.0 Azure-SDK-For-Python AZURECLI/2.44.0 (MSI)'
msrest.http_logger: Request body:
msrest.http_logger: None
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/{REDACTED-SubscriptionID}/providers/Microsoft.Authorization/roleDefinitions?$filter=roleName%20eq%20%27Support%20Request%20Contributor%27&api-version=2018-01-01-preview HTTP/1.1" 200 None
msrest.http_logger: Response status: 200
msrest.http_logger: Response headers:
msrest.http_logger:     'Cache-Control': 'no-cache'
msrest.http_logger:     'Pragma': 'no-cache'
msrest.http_logger:     'Transfer-Encoding': 'chunked'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'Content-Encoding': 'gzip'
msrest.http_logger:     'Expires': '-1'
msrest.http_logger:     'Vary': 'Accept-Encoding'
msrest.http_logger:     'x-ms-request-id': '650ba2bf-2ec6-4d89-af24-a87b8b238adf'
msrest.http_logger:     'X-Content-Type-Options': 'nosniff'
msrest.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger:     'Set-Cookie': 'x-ms-gateway-slice=Production; path=/; secure; samesite=none; httponly'
msrest.http_logger:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
msrest.http_logger:     'x-ms-correlation-request-id': '23bd5ff0-fa53-4781-bb85-f0e61f2dc7d7'
msrest.http_logger:     'x-ms-routing-request-id': 'CENTRALUS:20230616T201841Z:23bd5ff0-fa53-4781-bb85-f0e61f2dc7d7'
msrest.http_logger:     'Date': 'Fri, 16 Jun 2023 20:18:40 GMT'
msrest.http_logger: Response content:
msrest.http_logger: {"value":[{"properties":{"roleName":"Support Request Contributor","type":"BuiltInRole","description":"Lets you create and manage Support requests","assignableScopes":["/"],"permissions":[{"actions":["Microsoft.Authorization/*/read","Microsoft.Resources/subscriptions/resourceGroups/read","Microsoft.Support/*"],"notActions":[],"dataActions":[],"notDataActions":[]}],"createdOn":"2017-06-22T22:25:37.8053068Z","updatedOn":"2021-11-11T20:13:56.7444481Z","createdBy":null,"updatedBy":null},"id":"/subscriptions/{REDACTED-SubscriptionID}/providers/Microsoft.Authorization/roleDefinitions/cfd33db0-3dd1-45e3-aa9d-cdbdf3b6f24e","type":"Microsoft.Authorization/roleDefinitions","name":"cfd33db0-3dd1-45e3-aa9d-cdbdf3b6f24e"}]}
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.signed_session
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: f9603d0e-924d-412b-ba27-636c20cbf498
msrest.http_logger: Request URL: 'https://management.azure.com/subscriptions/{REDACTED-SubscriptionID}/providers/Microsoft.Authorization/roleAssignments/91a6dbff-fc5a-43de-8d7e-4fab9fde64f2?api-version=2020-04-01-preview'
msrest.http_logger: Request method: 'PUT'
msrest.http_logger: Request headers:
msrest.http_logger:     'Accept': 'application/json'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'accept-language': 'en-US'
msrest.http_logger:     'Content-Length': '266'
msrest.http_logger:     'User-Agent': 'python/3.10.8 (Windows-10-10.0.22621-SP0) msrest/0.7.1 msrest_azure/0.6.4 azure-mgmt-authorization/0.61.0 Azure-SDK-For-Python AZURECLI/2.44.0 (MSI)'
msrest.http_logger: Request body:
msrest.http_logger: {"properties": {"roleDefinitionId": "/subscriptions/{REDACTED-SubscriptionID}/providers/Microsoft.Authorization/roleDefinitions/cfd33db0-3dd1-45e3-aa9d-cdbdf3b6f24e", "principalId": "{REDACTED-AdminAgentsGroupID}", "principalType": "ForeignGroup"}}
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/{REDACTED-SubscriptionID}/providers/Microsoft.Authorization/roleAssignments/{REDACTED}?api-version=2020-04-01-preview HTTP/1.1" 400 489
msrest.http_logger: Response status: 400
msrest.http_logger: Response headers:
msrest.http_logger:     'Cache-Control': 'no-cache'
msrest.http_logger:     'Pragma': 'no-cache'
msrest.http_logger:     'Content-Length': '489'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'Expires': '-1'
msrest.http_logger:     'x-ms-request-id': '41ce386f-2e5d-4efb-9249-c7ac5bb5d4bc'
msrest.http_logger:     'X-Content-Type-Options': 'nosniff'
msrest.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger:     'x-ms-correlation-request-id': 'a92e2a54-89b0-4a23-9c38-88ba01591cf4'
msrest.http_logger:     'x-ms-routing-request-id': 'CENTRALUS:20230616T201841Z:a92e2a54-89b0-4a23-9c38-88ba01591cf4'
msrest.http_logger:     'Date': 'Fri, 16 Jun 2023 20:18:40 GMT'
msrest.http_logger: Response content:
msrest.http_logger: {"error":{"code":"PrincipalNotFound","message":"Principal {REDACTED-AdminAgentsGroupID} does not exist in the directory {REDACTED-CustomerTenantID}. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype"}}
msrest.exceptions: Principal {REDACTED-AdminAgentsGroupID} does not exist in the directory {REDACTED-CustomerTenantID}. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 179, in create_role_assignment
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/custom.py", line 203, in _create_role_assignment
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/role/_multi_api_adaptor.py", line 58, in create_role_assignment
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/authorization/v2020_04_01_preview/operations/_role_assignments_operations.py", line 332, in create
msrestazure.azure_exceptions.CloudError: Azure Error: PrincipalNotFound
Message: Principal {REDACTED-AdminAgentsGroupID} does not exist in the directory {REDACTED-CustomerTenantID}. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype

cli.azure.cli.core.azclierror: Principal {REDACTED-AdminAgentsGroupID} does not exist in the directory {REDACTED-CustomerTenantID}. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype
az_command_data_logger: Principal {REDACTED-AdminAgentsGroupID} does not exist in the directory {REDACTED-CustomerTenantID}. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03FA3D18>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.942 seconds (init: 0.493, invoke: 1.449)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3755 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\{REDACTED}\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Get a successful message that the RBAC role was successfully assigned to the FG.

### Environment Summary

azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by CaseySHelp** [comment]
We have opened a ticket with our Premier Partner Support Agreement for this as well. This is extremely urgent and time sensitive for us as we can't properly support our customers!

**Comment by CaseySHelp** [comment]
Turns out the reseller agreement was not being set up properly when gdap was issued for the customers affected. Issue is resolved.
