### ISSUE TITLE
AppGW: Add default predefined ssl policy field in resource

### ISSUE THREAD

**Issue by prateek2211** [Azure/azure-cli#26712]
### Related command

[az network application-gateway show](https://learn.microsoft.com/en-us/cli/azure/network/application-gateway?view=azure-cli-latest#az-network-application-gateway-show)

And other similar appgw commands which use the resource model

### Resource Provider

Microsoft.Network

### Description of Feature or Work Requested

Add readonly enum field `defaultPredefinedSslPolicy` in application gateway resource model

Swagger PR for the same: https://github.com/Azure/azure-rest-api-specs/pull/24094
This new property is released with API version >= 2023-02-01

### Minimum API Version Required

2023-02-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/24094

### Target Date

2023-06-28

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@prateek2211

Could you kindly list the following commands? 
> And other similar appgw commands which use the resource model

**Comment by prateek2211** [comment]
> @prateek2211
> 
> Could you kindly list the following commands?
> 
> > And other similar appgw commands which use the resource model

@necusjz 

az network application-gateway create
az network application-gateway list
az network application-gateway show
az network application-gateway update

**Comment by prateek2211** [comment]
@necusjz Any update on this?

**Comment by necusjz** [comment]
It's planned in the next coming sprint: https://github.com/Azure/azure-cli/milestone/132.

**Comment by prateek2211** [comment]
@necusjz Please note that api version has to be bumped up to 2023-02-01

**Comment by jaesoni** [comment]
@necusjz can you please share the customer-facing ETA (including CloudShell) for this? We will need to update our docs accordingly for our feature release.

**Comment by necusjz** [comment]
> @necusjz can you please share the customer-facing ETA (including CloudShell) for this? We will need to update our docs accordingly for our feature release.

https://github.com/Azure/azure-cli/milestone/132
