### ISSUE TITLE
webapp: remove the client side sku check for linux plan

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#2672]
We are requesting webapp service to error out, rather silently to create a windows plan, which is pretty incorrect
the change to rollback is #2651

**Comment by panchagnula** [comment]
@rramachand21 does our back end have an API now to check if SKU supports linuxduring ASP create? We currently have a client side check on CLI to error out if the SKU is valid for the App service plan?

**Comment by panchagnula** [comment]
@patricklee2  & @rramachand21 - is this something we can take care of?
