### ISSUE TITLE
Incorrect Az command in the Page

### ISSUE THREAD

**Issue by doctorlai-msrc** [Azure/azure-cli#26733]
### Describe the bug

At this page:

https://learn.microsoft.com/en-us/cli/azure/eventhubs/eventhub/authorization-rule?view=azure-cli-latest#az-eventhubs-eventhub-authorization-rule-create

The command in the Examples is missing "eventhubs"

So instead of 
```bash
az eventhub authorization-rule create --resource-group myresourcegroup --namespace-name mynamespace --eventhub-name myeventhub --name myauthorule --rights Listen
```

It should be
```bash
az eventhubs eventhub authorization-rule create --resource-group myresourcegroup --namespace-name mynamespace --eventhub-name myeventhub --name myauthorule --rights Listen
```

### Related command

az eventhubs eventhub

### Errors

N/A

### Issue script & Debug output

N/A

### Expected behavior

N/A

### Environment Summary

N/A

### Additional context

N/A

**Comment by SaurabhSharma-MSFT** [comment]
@doctorlai-msrc The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
