### ISSUE TITLE
"az logicapp create" creates Logic App with currently unsupported application setting parameter

### ISSUE THREAD

**Issue by ShingoHanai** [Azure/azure-cli#26736]
### Related command

az logicapp create --subscription {subscriptionId} -g {resourceGroup} -n {name of Logic App Stanard} -p {name or resourceId of App Service Plan} -s {name of storage account} --disable-app-insights true

### Resource Provider

Microsoft.Web/sites

### Description of Feature or Work Requested

"az logicapp create" creates now Logic App with following 3 unsupported application setting parameter.

1. FUNCTIONS_EXTENSION_VERSION which has value "~3". Azure Functions version v3 is not currently supported. Recommended value is "~4".

2. There is not WEBSITE_NODE_DEFAULT_VERSION parameter. This parameter needs to exist and recommended value is currently "~16" in Logic Apps Standard. (Function App recommends to be used value "~18".)

3. There is MACHINEKEY_DecryptionKey. This value is for .NET and Logic Apps Standard is used with node.js. This parameter shoudn't exist in Logic Apps Standard.

### Minimum API Version Required

2015-08-01

### Swagger PR link / SDK link

N/A

### Target Date

N/A

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ShingoHanai** [comment]
It's feedback from CSS support engineer Shingo Hanai (shhanai)

**Comment by archidda** [comment]
Hi @ShingoHanai, 

Thank you for raising the issue with Logic Apps team.

1. We are aware of this bug and for mitigation, I need you to set the app setting FUNCTIONS_EXTENSION_VERSION to ~4 in the configuration blade in portal.
2. About WEBSITE_NODE_DEFAULT_VERSION, logic app supports ~16.
3. I need to investigate and come back about the app setting MACHINEKEY_DecryptionKey.
