### ISSUE TITLE
Support `--rehydrate-priority` on `az storage blob copy start-batch`

### ISSUE THREAD

**Issue by maskati** [Azure/azure-cli#26732]
**Related command**
`az storage blob copy start-batch`

**Is your feature request related to a problem? Please describe.**
[az storage blob copy start](https://learn.microsoft.com/en-us/cli/azure/storage/blob/copy?view=azure-cli-latest#az-storage-blob-copy-start) supports `--rehydrate-priority` for [copying an archived blob](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob?tabs=azure-ad#copying-an-archived-blob) with [high priority](https://learn.microsoft.com/en-us/azure/storage/blobs/archive-rehydrate-overview#rehydration-priority). This functionality is missing from [az storage blob copy start-batch](https://learn.microsoft.com/en-us/cli/azure/storage/blob/copy?view=azure-cli-latest#az-storage-blob-copy-start-batch).

**Describe the solution you'd like**
Add the same support to `az storage blob copy start-batch`.

**Describe alternatives you've considered**
Enumerate and copy.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
