### ISSUE TITLE
install fails on debian GNU/Linux 12

### ISSUE THREAD

**Issue by vermegi** [Azure/azure-cli#26737]
### Describe the bug

Executing:

curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

Install fails

### Related command

Installing manually https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-1-install-with-one-command on a GitHub codespace. 
Codespace definition: https://github.com/vermegi/Deploying-and-Running-Java-Applications-in-Azure-Spring-Apps/tree/givermei/solution3.0 

azure-cli feature in codespace definition is currently commented out, since that was also failing (related issue: https://github.com/devcontainers/features/issues/589). I commented out the azure-cli feature and tried manual install, with the below failure message.

### Errors

Output:

Get:1 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm InRelease [3,597 B]
Get:2 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Get:3 http://deb.debian.org/debian bookworm InRelease [147 kB]
Get:4 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:5 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:6 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm/main amd64 Packages [1,847 B]
Get:7 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm/main all Packages [342 B]
Get:8 https://dl.yarnpkg.com/debian stable/main all Packages [10.9 kB]
Get:9 https://dl.yarnpkg.com/debian stable/main amd64 Packages [10.9 kB]
Get:10 http://deb.debian.org/debian bookworm/main amd64 Packages [8,904 kB]
Get:11 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [30.4 kB]
Fetched 9,227 kB in 2s (5,816 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-transport-https is already the newest version (2.6.1).
lsb-release is already the newest version (12.0-1).
gnupg is already the newest version (2.2.40-1.1).
curl is already the newest version (7.88.1-10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease  
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Get:4 https://packages.microsoft.com/repos/azure-cli bullseye InRelease [3,587 B]
Hit:5 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm InRelease
Hit:6 https://dl.yarnpkg.com/debian stable InRelease
Get:7 https://packages.microsoft.com/repos/azure-cli bullseye/main all Packages [1,852 B]
Get:8 https://packages.microsoft.com/repos/azure-cli bullseye/main amd64 Packages [782 B]
Fetched 6,221 B in 1s (11.7 kB/s)                      
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 azure-cli : Depends: libffi7 (>= 3.3~20180313) but it is not installable
             Depends: libssl1.1 (>= 1.1.1) but it is not installable
E: Unable to correct problems, you have held broken packages.

### Issue script & Debug output

curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
Get:1 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm InRelease [3,597 B]
Get:2 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Get:3 http://deb.debian.org/debian bookworm InRelease [147 kB]
Get:4 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:5 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:6 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm/main amd64 Packages [1,847 B]
Get:7 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm/main all Packages [342 B]
Get:8 https://dl.yarnpkg.com/debian stable/main all Packages [10.9 kB]
Get:9 https://dl.yarnpkg.com/debian stable/main amd64 Packages [10.9 kB]
Get:10 http://deb.debian.org/debian bookworm/main amd64 Packages [8,904 kB]
Get:11 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [30.4 kB]
Fetched 9,227 kB in 2s (5,816 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-transport-https is already the newest version (2.6.1).
lsb-release is already the newest version (12.0-1).
gnupg is already the newest version (2.2.40-1.1).
curl is already the newest version (7.88.1-10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease  
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Get:4 https://packages.microsoft.com/repos/azure-cli bullseye InRelease [3,587 B]
Hit:5 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm InRelease
Hit:6 https://dl.yarnpkg.com/debian stable InRelease
Get:7 https://packages.microsoft.com/repos/azure-cli bullseye/main all Packages [1,852 B]
Get:8 https://packages.microsoft.com/repos/azure-cli bullseye/main amd64 Packages [782 B]
Fetched 6,221 B in 1s (11.7 kB/s)                      
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 azure-cli : Depends: libffi7 (>= 3.3~20180313) but it is not installable
             Depends: libssl1.1 (>= 1.1.1) but it is not installable
E: Unable to correct problems, you have held broken packages.

### Expected behavior

Successful install

### Environment Summary

az not installed yet. This happens on install. 

/etc $ cat issue
Debian GNU/Linux 12 \n \l

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by vermegi** [comment]
I am currently also trying out the manual install process (option 2): https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions 

this was successful, so something in the automated install is blocking

Current installed version through the step by step process: 

az --version
azure-cli                         2.45.0 *

core                              2.45.0 *
telemetry                          1.0.8

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.21.0
azure-mgmt-resource               22.0.0

Python location '/usr/bin/python3'
Extensions directory '/home/vscode/.azure/cliextensions'
Extensions system directory '/usr/lib/python3/dist-packages/azure-cli-extensions'

Python (Linux) 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

Legal docs and information: aka.ms/AzureCliLegal


You have 2 update(s) available. Consider updating your CLI installation with 'az upgrade'

**Comment by vermegi** [comment]
Upgrading to latest fails though: 
az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.45.0. Latest version available is 2.49.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): Y
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease           
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease 
Ign:4 https://packages.microsoft.com/repos/azure-cli bookworm InRelease                               
Hit:5 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm InRelease          
Err:6 https://packages.microsoft.com/repos/azure-cli bookworm Release
  404  Not Found [IP: 40.114.136.21 443]
Hit:7 https://dl.yarnpkg.com/debian stable InRelease
Reading package lists... Done
E: The repository 'https://packages.microsoft.com/repos/azure-cli bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
CLI upgrade failed.

**Comment by vermegi** [comment]
Might be related. extension install also fails now on the step by step installed version of 2.45.0:

az extension add --name spring --debug
cli.knack.cli: Command arguments: ['extension', 'add', '--name', 'spring', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f71a5a4a520>, <function OutputProducer.on_global_arguments at 0x7f71a5986b60>, <function CLIQuery.on_global_arguments at 0x7f71a57c05e0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'extension': ['azure.cli.command_modules.extension']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: extension                 0.002         1         7
cli.azure.cli.core: Total (1)                 0.002         1         7
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0  
cli.azure.cli.core: Loaded 1 groups, 7 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : extension add
cli.azure.cli.core: Command table: extension add
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f71a4c8c360>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/vscode/.azure/commands/2023-06-23.08-17-15.extension_add.10864.log'.
az_command_data_logger: command args: extension add --name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f71a4ca68e0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f71a4b24680>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f71a4b247c0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f71a5986c00>, <function CLIQuery.handle_query_parameter at 0x7f71a57c0680>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f71a4b24720>]
urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool: https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool: Starting new HTTPS connection (1): azcliextensionsync.blob.core.windows.net:443
urllib3.connectionpool: https://azcliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 2914760
cli.azure.cli.core.extension._resolve: Candidates ['spring-1.0.0-py3-none-any.whl', 'spring-1.1.0-py3-none-any.whl', 'spring-1.1.1-py3-none-any.whl', 'spring-1.1.2-py3-none-any.whl', 'spring-1.1.3-py3-none-any.whl', 'spring-1.1.4-py3-none-any.whl', 'spring-1.1.5-py3-none-any.whl', 'spring-1.1.7-py3-none-any.whl', 'spring-1.1.8-py3-none-any.whl', 'spring-1.1.9-py3-none-any.whl', 'spring-1.1.10-py3-none-any.whl', 'spring-1.1.11-py3-none-any.whl', 'spring-1.1.12-py3-none-any.whl', 'spring-1.1.13-py3-none-any.whl', 'spring-1.1.14-py3-none-any.whl', 'spring-1.2.0-py3-none-any.whl', 'spring-1.3.0-py3-none-any.whl', 'spring-1.4.0-py3-none-any.whl', 'spring-1.4.1-py3-none-any.whl', 'spring-1.4.2-py3-none-any.whl', 'spring-1.5.0-py3-none-any.whl', 'spring-1.6.0-py3-none-any.whl', 'spring-1.6.1-py3-none-any.whl', 'spring-1.6.2-py3-none-any.whl', 'spring-1.6.3-py3-none-any.whl', 'spring-1.6.4-py3-none-any.whl', 'spring-1.6.5-py3-none-any.whl', 'spring-1.6.6-py3-none-any.whl', 'spring-1.6.7-py3-none-any.whl', 'spring-1.6.8-py3-none-any.whl', 'spring-1.7.0-py3-none-any.whl', 'spring-1.7.1-py3-none-any.whl', 'spring-1.7.2-py3-none-any.whl', 'spring-1.7.3-py3-none-any.whl', 'spring-1.8.0-py3-none-any.whl', 'spring-1.9.0-py3-none-any.whl', 'spring-1.9.1-py3-none-any.whl', 'spring-1.9.2-py3-none-any.whl', 'spring-1.10.0-py3-none-any.whl', 'spring-1.11.0-py3-none-any.whl', 'spring-1.11.1-py3-none-any.whl', 'spring-1.11.2-py3-none-any.whl', 'spring-1.11.3-py3-none-any.whl', 'spring-1.12.0-py3-none-any.whl', 'spring-1.12.1-py3-none-any.whl', 'spring-1.12.2-py3-none-any.whl', 'spring-1.13.0-py3-none-any.whl', 'spring-1.13.1-py3-none-any.whl', 'spring-1.13.2-py3-none-any.whl', 'spring-1.13.3-py3-none-any.whl', 'spring-1.14.0-py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['spring-1.0.0-py3-none-any.whl', 'spring-1.1.0-py3-none-any.whl', 'spring-1.1.1-py3-none-any.whl', 'spring-1.1.2-py3-none-any.whl', 'spring-1.1.3-py3-none-any.whl', 'spring-1.1.4-py3-none-any.whl', 'spring-1.1.5-py3-none-any.whl', 'spring-1.1.7-py3-none-any.whl', 'spring-1.1.8-py3-none-any.whl', 'spring-1.1.9-py3-none-any.whl', 'spring-1.1.10-py3-none-any.whl', 'spring-1.1.11-py3-none-any.whl', 'spring-1.1.12-py3-none-any.whl', 'spring-1.1.13-py3-none-any.whl', 'spring-1.1.14-py3-none-any.whl', 'spring-1.2.0-py3-none-any.whl', 'spring-1.3.0-py3-none-any.whl', 'spring-1.4.0-py3-none-any.whl', 'spring-1.4.1-py3-none-any.whl', 'spring-1.4.2-py3-none-any.whl', 'spring-1.5.0-py3-none-any.whl', 'spring-1.6.0-py3-none-any.whl', 'spring-1.6.1-py3-none-any.whl', 'spring-1.6.2-py3-none-any.whl', 'spring-1.6.3-py3-none-any.whl', 'spring-1.6.4-py3-none-any.whl', 'spring-1.6.5-py3-none-any.whl', 'spring-1.6.6-py3-none-any.whl', 'spring-1.6.7-py3-none-any.whl', 'spring-1.6.8-py3-none-any.whl', 'spring-1.7.0-py3-none-any.whl', 'spring-1.7.1-py3-none-any.whl', 'spring-1.7.2-py3-none-any.whl', 'spring-1.7.3-py3-none-any.whl', 'spring-1.8.0-py3-none-any.whl', 'spring-1.9.0-py3-none-any.whl', 'spring-1.9.1-py3-none-any.whl', 'spring-1.9.2-py3-none-any.whl', 'spring-1.10.0-py3-none-any.whl', 'spring-1.11.0-py3-none-any.whl', 'spring-1.11.1-py3-none-any.whl', 'spring-1.11.2-py3-none-any.whl', 'spring-1.11.3-py3-none-any.whl', 'spring-1.12.0-py3-none-any.whl', 'spring-1.12.1-py3-none-any.whl', 'spring-1.12.2-py3-none-any.whl', 'spring-1.13.0-py3-none-any.whl', 'spring-1.13.1-py3-none-any.whl', 'spring-1.13.2-py3-none-any.whl', 'spring-1.13.3-py3-none-any.whl', 'spring-1.14.0-py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['spring-1.0.0-py3-none-any.whl', 'spring-1.1.0-py3-none-any.whl', 'spring-1.1.1-py3-none-any.whl', 'spring-1.1.2-py3-none-any.whl', 'spring-1.1.3-py3-none-any.whl', 'spring-1.1.4-py3-none-any.whl', 'spring-1.1.5-py3-none-any.whl', 'spring-1.1.7-py3-none-any.whl', 'spring-1.1.8-py3-none-any.whl', 'spring-1.1.9-py3-none-any.whl', 'spring-1.1.10-py3-none-any.whl', 'spring-1.1.11-py3-none-any.whl', 'spring-1.1.12-py3-none-any.whl', 'spring-1.1.13-py3-none-any.whl', 'spring-1.1.14-py3-none-any.whl', 'spring-1.2.0-py3-none-any.whl', 'spring-1.3.0-py3-none-any.whl', 'spring-1.4.0-py3-none-any.whl', 'spring-1.4.1-py3-none-any.whl', 'spring-1.4.2-py3-none-any.whl', 'spring-1.5.0-py3-none-any.whl', 'spring-1.6.0-py3-none-any.whl', 'spring-1.6.1-py3-none-any.whl', 'spring-1.6.2-py3-none-any.whl', 'spring-1.6.3-py3-none-any.whl', 'spring-1.6.4-py3-none-any.whl', 'spring-1.6.5-py3-none-any.whl', 'spring-1.6.6-py3-none-any.whl', 'spring-1.6.7-py3-none-any.whl', 'spring-1.6.8-py3-none-any.whl', 'spring-1.7.0-py3-none-any.whl', 'spring-1.7.1-py3-none-any.whl', 'spring-1.7.2-py3-none-any.whl', 'spring-1.7.3-py3-none-any.whl', 'spring-1.8.0-py3-none-any.whl', 'spring-1.9.0-py3-none-any.whl', 'spring-1.9.1-py3-none-any.whl', 'spring-1.9.2-py3-none-any.whl', 'spring-1.10.0-py3-none-any.whl', 'spring-1.11.0-py3-none-any.whl', 'spring-1.11.1-py3-none-any.whl', 'spring-1.11.2-py3-none-any.whl', 'spring-1.11.3-py3-none-any.whl', 'spring-1.12.0-py3-none-any.whl', 'spring-1.12.1-py3-none-any.whl', 'spring-1.12.2-py3-none-any.whl', 'spring-1.13.0-py3-none-any.whl', 'spring-1.13.1-py3-none-any.whl', 'spring-1.13.2-py3-none-any.whl', 'spring-1.13.3-py3-none-any.whl', 'spring-1.14.0-py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Candidates ['spring-1.0.0-py3-none-any.whl', 'spring-1.1.0-py3-none-any.whl', 'spring-1.1.1-py3-none-any.whl', 'spring-1.1.2-py3-none-any.whl', 'spring-1.1.3-py3-none-any.whl', 'spring-1.1.4-py3-none-any.whl', 'spring-1.1.5-py3-none-any.whl', 'spring-1.1.7-py3-none-any.whl', 'spring-1.1.8-py3-none-any.whl', 'spring-1.1.9-py3-none-any.whl', 'spring-1.1.10-py3-none-any.whl', 'spring-1.1.11-py3-none-any.whl', 'spring-1.1.12-py3-none-any.whl', 'spring-1.1.13-py3-none-any.whl', 'spring-1.1.14-py3-none-any.whl', 'spring-1.2.0-py3-none-any.whl', 'spring-1.3.0-py3-none-any.whl', 'spring-1.4.0-py3-none-any.whl', 'spring-1.4.1-py3-none-any.whl', 'spring-1.4.2-py3-none-any.whl', 'spring-1.5.0-py3-none-any.whl', 'spring-1.6.0-py3-none-any.whl', 'spring-1.6.1-py3-none-any.whl', 'spring-1.6.2-py3-none-any.whl', 'spring-1.6.3-py3-none-any.whl', 'spring-1.6.4-py3-none-any.whl', 'spring-1.6.5-py3-none-any.whl', 'spring-1.6.6-py3-none-any.whl', 'spring-1.6.7-py3-none-any.whl', 'spring-1.6.8-py3-none-any.whl', 'spring-1.7.0-py3-none-any.whl', 'spring-1.7.1-py3-none-any.whl', 'spring-1.7.2-py3-none-any.whl', 'spring-1.7.3-py3-none-any.whl', 'spring-1.8.0-py3-none-any.whl', 'spring-1.9.0-py3-none-any.whl', 'spring-1.9.1-py3-none-any.whl', 'spring-1.9.2-py3-none-any.whl', 'spring-1.10.0-py3-none-any.whl', 'spring-1.11.0-py3-none-any.whl', 'spring-1.11.1-py3-none-any.whl', 'spring-1.11.2-py3-none-any.whl', 'spring-1.11.3-py3-none-any.whl', 'spring-1.12.0-py3-none-any.whl', 'spring-1.12.1-py3-none-any.whl', 'spring-1.12.2-py3-none-any.whl', 'spring-1.13.0-py3-none-any.whl', 'spring-1.13.1-py3-none-any.whl', 'spring-1.13.2-py3-none-any.whl', 'spring-1.13.3-py3-none-any.whl', 'spring-1.14.0-py3-none-any.whl']
cli.azure.cli.core.extension._resolve: Chosen {'downloadUrl': 'https://azcliprod.blob.core.windows.net/cli-extensions/spring-1.14.0-py3-none-any.whl', 'filename': 'spring-1.14.0-py3-none-any.whl', 'metadata': {'azext.isPreview': False, 'azext.minCliCoreVersion': '2.45.0', 'classifiers': ['Development Status :: 4 - Beta', 'Intended Audience :: Developers', 'Intended Audience :: System Administrators', 'Programming Language :: Python', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'License :: OSI Approved :: MIT License'], 'extensions': {'python.details': {'contacts': [{'email': 'azpycli@microsoft.com', 'name': 'Microsoft Corporation', 'role': 'author'}], 'document_names': {'description': 'DESCRIPTION.rst'}, 'project_urls': {'Home': 'https://github.com/Azure/azure-cli-extensions/tree/main/src/spring'}}}, 'generator': 'bdist_wheel (0.30.0)', 'license': 'MIT', 'metadata_version': '2.0', 'name': 'spring', 'summary': 'Microsoft Azure Command-Line Tools spring Extension', 'version': '1.14.0'}, 'sha256Digest': '3452d273b7e2bda35c592944518ff65cc148c06369a5b976af84100f1b6be719'}
cli.azure.cli.core.extension.operations: Extension source is url? True
cli.azure.cli.core.extension.operations: Downloading https://azcliprod.blob.core.windows.net/cli-extensions/spring-1.14.0-py3-none-any.whl to /tmp/tmphn6jlc_x/spring-1.14.0-py3-none-any.whl
urllib3.connectionpool: Starting new HTTPS connection (1): azcliprod.blob.core.windows.net:443
urllib3.connectionpool: https://azcliprod.blob.core.windows.net:443 "GET /cli-extensions/spring-1.14.0-py3-none-any.whl HTTP/1.1" 200 3439166
cli.azure.cli.core.extension.operations: Downloaded to /tmp/tmphn6jlc_x/spring-1.14.0-py3-none-any.whl
cli.azure.cli.core.extension.operations: Validating the extension /tmp/tmphn6jlc_x/spring-1.14.0-py3-none-any.whl
cli.azure.cli.core.extension.operations: Checksum of /tmp/tmphn6jlc_x/spring-1.14.0-py3-none-any.whl is OK
cli.azure.cli.core.extension.operations: Validation successful on /tmp/tmphn6jlc_x/spring-1.14.0-py3-none-any.whl
cli.azure.cli.core.extension.operations: Linux distro check: Reading from: /etc/apt/sources.list.d/azure-cli.list
cli.azure.cli.core.extension.operations: Linux distro check: Found in list file: https://packages.microsoft.com/repos/azure-cli/
cli.azure.cli.core.extension.operations: Linux distro check: Reported by API: None
cli.azure.cli.core.extension.operations: Linux distro check: Mismatch distribution name in /etc/apt/sources.list.d/azure-cli.list file
cli.azure.cli.core.extension.operations: Linux distro check: If command fails, install the appropriate package for your distribution or change the above file accordingly.
cli.azure.cli.core.extension.operations: Linux distro check: /etc/apt/sources.list.d/azure-cli.list has 'https://packages.microsoft.com/repos/azure-cli/', current distro is 'None'
cli.azure.cli.core.extension.operations: Executing pip with args: ['install', '--target', '/home/vscode/.azure/cliextensions/spring', '/tmp/tmphn6jlc_x/spring-1.14.0-py3-none-any.whl']
cli.azure.cli.core.extension.operations: Running: ['/usr/bin/python3', '-m', 'pip', 'install', '--target', '/home/vscode/.azure/cliextensions/spring', '/tmp/tmphn6jlc_x/spring-1.14.0-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']
cli.azure.cli.core.extension.operations: /usr/bin/python3: No module named pip

cli.azure.cli.core.extension.operations: Command '['/usr/bin/python3', '-m', 'pip', 'install', '--target', '/home/vscode/.azure/cliextensions/spring', '/tmp/tmphn6jlc_x/spring-1.14.0-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
cli.azure.cli.core.extension.operations: Pip failed so deleting anything we might have installed at /home/vscode/.azure/cliextensions/spring
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/extension/custom.py", line 16, in add_extension_cmd
    return add_extension(cli_ctx=cmd.cli_ctx, source=source, extension_name=extension_name, index_url=index_url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/azure/cli/core/extension/operations.py", line 344, in add_extension
    extension_name = _add_whl_ext(cli_ctx=cmd_cli_ctx, source=source, ext_sha256=ext_sha256,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/azure/cli/core/extension/operations.py", line 173, in _add_whl_ext
    raise CLIError('An error occurred. Pip failed with status code {}. '
knack.util.CLIError: An error occurred. Pip failed with status code 1. Use --debug for more information.

cli.azure.cli.core.azclierror: An error occurred. Pip failed with status code 1. Use --debug for more information.
az_command_data_logger: An error occurred. Pip failed with status code 1. Use --debug for more information.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f71a4c8c5e0>]
az_command_data_logger: exit code: 1
cli.azure.cli.__main__: Command ran in 6.225 seconds (init: 0.151, invoke: 6.074)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3458 in cache
telemetry.check: Negative: The /home/vscode/.azure/telemetry.txt was modified at 2023-06-23 08:12:11.657388, which in less than 600.000000 s

**Comment by bebound** [comment]
Tracked by https://github.com/Azure/azure-cli/issues/25750
