### ISSUE TITLE
az network application-gateway frontend-ip doesn't let to give id instead of names for parameters; az network application-gateway frontend-ip fails to update private-ip address when app-gateway and VNet are on different resource-groups

### ISSUE THREAD

**Issue by manikg321** [Azure/azure-cli#26746]
### Describe the bug

az network application-gateway frontend-ip create has predefined resource paths and expects app-gateway and VNet to be in the same resource group. The command needs to allow provide resource ids instead of name.

I have AKS with app-gateway. AKS is on xyz resource-group, while App-gateway is on MC_xyz resource-group. VNet is on  xyz resource-group and app-gateway uses subnet which is within xyz resource group. When I try to do 'az network application-gateway frontend-ip create', it fails when app-gateway and vnet are on different resource-groups.

### Related command

az network application-gateway frontend-ip create   \
  --resource-group **MC_xyz** \
  --gateway-name <gateway-name> \
  --name appgtwPrivateIP \
--private-ip-address <private-ip-address > \
--subnet <subnet > \
--vnet-name subscriptions/.../resourceGroups/**xyz**/providers/Microsoft.Network/virtualNetworks/<vnet-name>

### Errors

(InvalidRequestFormat) Cannot parse the request.
Code: InvalidRequestFormat
Message: Cannot parse the request.
Exception Details:      (InvalidJsonReferenceFormat) Reference Id /subscriptions/..../resourceGroups/**MC_xyz**/providers/Microsoft.Network/virtualNetworks/subscriptions/.../resourceGroups/**xyz**/providers/Microsoft.Network/virtualNetworks/<vnet-name>/subnets/<subnet> is not formatted correctly. The Id is expected to reference resources of type virtualNetworks/subnets. Path properties.frontendIPConfigurations[2].properties.subnet.

### Issue script & Debug output

  (InvalidRequestFormat) Cannot parse the request.
Code: InvalidRequestFormat
Message: Cannot parse the request.
Exception Details:      (InvalidJsonReferenceFormat) Reference Id /subscriptions/..../resourceGroups/MC_xyz/providers/Microsoft.Network/virtualNetworks/subscriptions/.../resourceGroups/xyz/providers/Microsoft.Network/virtualNetworks/<vnet-name>/subnets/<subnet> is not formatted correctly. The Id is expected to reference resources of type virtualNetworks/subnets. Path properties.frontendIPConfigurations[2].properties.subnet.

### Expected behavior

(InvalidRequestFormat) Cannot parse the request.
Code: InvalidRequestFormat
Message: Cannot parse the request.
Exception Details:      (InvalidJsonReferenceFormat) Reference Id /subscriptions/..../resourceGroups/MC_xyz/providers/Microsoft.Network/virtualNetworks/subscriptions/.../resourceGroups/xyz/providers/Microsoft.Network/virtualNetworks/<vnet-name>/subnets/<subnet> is not formatted correctly. The Id is expected to reference resources of type virtualNetworks/subnets. Path properties.frontendIPConfigurations[2].properties.subnet.

### Environment Summary

azure-cli                         2.47.0 *

core                              2.47.0 *
telemetry                          1.0.8

Extensions:
account                            0.2.1
azure-devops                      0.26.0

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.10.10 (main, Mar 31 2023, 09:27:10) [GCC 7.5.0]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@manikg321 

Did you aware the help message of `--subnet` argument?
> Name or ID of the subnet. If using Name, you need to provide `--vnet-name` as well.

It means `--vnet-name` is a supplement to ID of `--subnet`, cannot be a complete resource ID of itself.

**Comment by manikg321** [comment]
yes, as explained I tried both --subnet and --vnet-name together and also just the resource-name & resource-id. But still the same error. 'az network application-gateway frontend-ip create' points to the --resource-group but not the vnet resource group.

**Comment by manikg321** [comment]
Basically, what I am saying is: application-gateway and vnet are on different resource-groups; 'az network application-gateway frontend-ip create' fails in such cases.

**Comment by necusjz** [comment]
> Basically, what I am saying is: application-gateway and vnet are on different resource-groups; 'az network application-gateway frontend-ip create' fails in such cases.

For you case, let's input `--subnet` by ID and do not need to input `--vnet-name`.

**Comment by manikg321** [comment]
![image](https://github.com/Azure/azure-cli/assets/81321710/e9173e10-1584-4821-abcc-9616fe9165b7)

**Comment by manikg321** [comment]
Thanks! it worked. 
One more quick question, why does 'az network application-gateway frontend-ip update' throw error ApplicationGatewayFrontendIPPrivateIPCannotBeChanged

**Comment by necusjz** [comment]
> Thanks! it worked. One more quick question, why does 'az network application-gateway frontend-ip update' throw error ApplicationGatewayFrontendIPPrivateIPCannotBeChanged

Seems by service's design, our client tool has no idea about that.
