### ISSUE TITLE
StepSequence in v1 no longer available in AzureML v2

### ISSUE THREAD

**Issue by wangzelin007** [Azure/azure-cli#26750]
### Describe the bug

I am frustrated when trying to get one AML step to start after another AML step in a pipeline, when there are no input/output files between the 2 steps. It's a useful v1 feature (https://learn.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.stepsequence?view=azure-ml-py) that is removed in v2. Airflow also supports it naturally. Right now I have to modify like 6 different files to add a placeholder parameter for the 2 successive steps.

### Related command

az ml job create

### Errors

None

### Issue script & Debug output

None

### Expected behavior

Add a field called prerequisites in the pipelinecommandjob yaml so that i can specify which steps need to complete before starting the current step.

### Environment Summary

None

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
