### ISSUE TITLE
[servicebus, eventhubs] Potential bug because of modifying the list during iteration

### ISSUE THREAD

**Issue by bebound** [Azure/azure-cli#26765]
### Describe the bug

In https://github.com/azure/azure-cli/blob/ae4a96ad73e6e6b4cd27b29ade5cbe65e62dadf0/src/azure-cli/azure/cli/command_modules/eventhubs/operations/network_rule_set.py#L64-L67
``` python
   for i in ip_rule:
        for j in ip_rule_list:
            if i['ip-address'] == j["ip_mask"]:
                ip_rule_list.remove(j)
```
`ip_rule_list` is not fully iterated if j is removed. For example:
``` python
a = [1,2,3,4]
for i in a:
    print(i)
    a.remove(i)
>>> 1
>>> 3
```
There are four parts contains similar logic.

Related PR: #26685, found by `modified-iterating-list` rule.
> c:\users\kk\developer\azure-cli\src\azure-cli\azure\cli\command_modules\eventhubs\operations\network_rule_set.py:67:16: W4701: Iterated list 'ip_rule_list' is being modified inside for loop body, consider iterating through a copy of it instead. (modified-iterating-list)
c:\users\kk\developer\azure-cli\src\azure-cli\azure\cli\command_modules\eventhubs\operations\network_rule_set.py:126:16: W4701: Iterated list 'virtual_network_rule_list' is being modified inside for loop body, consider iterating through a copy of it instead. (modified-iterating-list)
c:\users\kk\developer\azure-cli\src\azure-cli\azure\cli\command_modules\servicebus\operations\network_rule_set.py:64:16: W4701: Iterated list 'ip_rule_list' is being modified inside for loop body, consider iterating through a copy of it instead. (modified-iterating-list)
c:\users\kk\developer\azure-cli\src\azure-cli\azure\cli\command_modules\servicebus\operations\network_rule_set.py:124:16: W4701: Iterated list 'virtual_network_rule_list' is being modified inside for loop body, consider iterating through a copy of it instead. (modified-iterating-list)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
The code is introduced by https://github.com/Azure/azure-cli/pull/25792
@schaudhari6254888  Could you please take a look?

**Comment by schaudhari6254888** [comment]
> The code is introduced by #25792 @schaudhari6254888 Could you please take a look?

Hey @bebound , Since IP address in Ip-rule is unique. So Suppose if it matches it will remove that ip address in ongoing iteration. even if skip the next index it doesn't harm bcs unique ip is already remove. So next iteration again it starts from 0th index of IP_RULE_list.

**Comment by bebound** [comment]
Thanks for your confirmation.
Would you mind if I use a copy when iteration, so I don't need to disable `modified-iterating-list` rule?
`for j in ip_rule_list[:]:`

**Comment by schaudhari6254888** [comment]
> Thanks for your confirmation. Would you mind if I use a copy when iteration, so I don't need to disable `modified-iterating-list` lint rule? `for j in ip_rule_list[:]:`

You can use
