### ISSUE TITLE
Add hibernate optional parameter for az vmss deallocate

### ISSUE THREAD

**Issue by vatsan28** [Azure/azure-cli#26760]
**Related command**
az vmss deallocate

**Is your feature request related to a problem? Please describe.**
Customers currently cannot chose to hibernate a VM when deallocating a VMSS VM

**Describe the solution you'd like**
Support for hibernating a VM while deallocating is added in the rest api and SDK. We want to extend this support for CLI by adding this optional parameter in the az vmss deallocate

**Describe alternatives you've considered**
<NA>

**Additional context**
Support for VM is already in place: https://learn.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-deallocate

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@vatsan28 May I ask could you please use the template of [[Microsoft Internal / Service Team] Feature Request](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=feature-request&projects=&template=Service_team_request.yml) to create this feature request, which can provide us with more necessary information for developing this feature

**Comment by yanzhudd** [comment]
> @vatsan28 May I ask could you please use the template of [[Microsoft Internal / Service Team] Feature Request](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=feature-request&projects=&template=Service_team_request.yml) to create this feature request, which can provide us with more necessary information for developing this feature

Hi @vatsan28, is there any update?
please note that the info you have provided is not enough for developing this feature. Please use the template mentioned above to provide more necessary info.

**Comment by vatsan28** [comment]
I have created the new issue: https://github.com/Azure/azure-cli/issues/26938
