### ISSUE TITLE
[IoT Hub] How to setup IoT Hub file upload?

### ISSUE THREAD

**Issue by jdneo** [Azure/azure-cli#2676]
I'm trying to enable the IoT Hub file upload through the Azure CLI 2.0. 

What I did is using the update command to set some related properties. For example:

```
az iot hub update --ids <iothub_id> --set properties.storageEndpoints.$default.connectionString="DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=<account_name>;AccountKey=<account_key>"
```

And after running the command, I get:
`Couldn't find 'connectionString=DefaultEndpointsProtocol=https;EndpointSuffix=core' in 'properties.storageEndpoints.$default.connectionString=DefaultEndpointsProtocol=https;EndpointSuffix=core'. Available options: ['connectionString', 'containerName', 'sasTtlAsIso8601']`

Seems the Azure CLI parsing the . incorrectly? Or am I using the command incorrectly?

**Comment by derekbekoe** [comment]
FYI @xscript

**Comment by xscript** [comment]
@jdneo This is a code bug. It is been fixed already. You can read more details at #2527 .
The fix should be rolled out at the next release.

**Comment by jdneo** [comment]
Hi @xscript, glad to see it has been fixed. And for now, what should I do if I want to configure the connectionString?

**Comment by xscript** [comment]
@jdneo I think you can do that from Azure Portal or use Azure Xplat CLI.

**Comment by jdneo** [comment]
We want to provision azure resource in CLI. The Azure Xplat CLI works. But still hope that the Azure CLI can release ASAP :)
