### ISSUE TITLE
Gallery image version soft delete recover call from CLI

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#26773]
### Preconditions

- [ ] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az sig image-version create

### Resource Provider

Microsoft.Compute/galleries

### Description of Feature or Work Requested

Currently when do "az sig image-version create", a source is required by CLI. We hope to remove this check because backend is beginning to support create without source.

Currently:
![SoftDeleteRecover](https://github.com/Azure/azure-cli/assets/69279251/c0ad22e9-ea47-4297-8d99-13f2e1f27a26)

source like managed image is required. And we can begin to allow them not in the input. Backend will reject invalid calls.

### Minimum API Version Required

2021-07-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/GalleryRP/stable/2021-07-01/gallery.json

### Request Example

az sig image-version create --gallery-image-version "def2" --gallery-image-name "1.0.0" --gallery-name "galleryName"  -g "rgName"

### Target Date

07-30

### PM Contact

SARAIC

### Engineer Contact

kansun

### Additional context

Pls let us know if you have any question.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
> source like managed image is required. And we can begin to allow them not in the input. Backend will reject invalid calls.

https://github.com/Azure/azure-cli/blob/27d920eceec01efdccf60e7136fdecc0ee679a72/src/azure-cli/azure/cli/command_modules/vm/custom.py#L4698-L4699

https://github.com/Azure/azure-cli/blob/27d920eceec01efdccf60e7136fdecc0ee679a72/src/azure-cli/azure/cli/command_modules/vm/custom.py#L4780-L4781

@kangsun-ctrl I'd like to confirm if we need to retain the check for `managed_image`? Or we need to remove all the check for `managed_image`, `os_snapshot`, and `os_vhd_uri` above?

**Comment by kangsun-ctrl** [comment]
> remove all the check for `managed_image`, `os_snapshot`, and `os_vhd_uri` above?

Hey @zhoxing-ms , previously for create az image version, either managed_image, os_snapshot, or os_vhd_uri needs to be input, now for support soft delete call, that does not need to be there. I think either we remove the required check for managed_image, os_snapshot, and os_vhd_uri, or we invent a new option -recover-image-version and that allows user to not input managed_image, os_snapshot, and os_vhd_uri during create. If user does not input -recover-image-version, then the check for managed_image, os_snapshot, and os_vhd_uri  is required.

**Comment by ReaNAiveD** [comment]
Hi @kangsun-ctrl , we are going to introduce a new command `az sig image-version undelete` to support the recovery of soft-deleted images. The `az sig image-version create` command will remain unchanged and will still require the check for managed_image, os_snapshot, and os_vhd_uri. 
The introduction of `az sig image-version undelete` is to stay consistent with other soft-delete-recovery commands such as  `az storage blob undelete` and `az backup protection undelete`. 
The new command that recovers a soft-deleted image will be like `az sig image-version undelete -g rgName  --gallery-name galleryName --gallery-image-definition def --gallery-image-version 1.1.1`.
What do you think about the solution?

**Comment by kangsun-ctrl** [comment]
@ReaNAiveD Hey your option sounds good!
