### ISSUE TITLE
az cli commands should be idempotent

### ISSUE THREAD

**Issue by adehaan-darwin-eu** [Azure/azure-cli#26770]
**Related command**

az postgres flexible-server create
https://learn.microsoft.com/en-us/cli/azure/postgres/flexible-server?view=azure-cli-latest#az-postgres-flexible-server-create

**Is your feature request related to a problem? Please describe.**

When issuing the above command in a deployment pipeline, the pipeline exits with error code 1:

WARNING: Checking the existence of the resource group '##obfuscated##'...
WARNING: Resource group '##obfuscated##' exists ? : True 
ERROR: Specified server name is already used.
##[error]Script failed with exit code: 1

**Describe the solution you'd like**

This command should be able to be executed even if the resource already exists. just raise a warning.

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by nachoalonsoportillo** [comment]
@adehaan-darwin-eu After having evaluated carefully the pros and cons of leaving the current behavior as-is or changing it in the way you're requesting, we have decided to leave it as it is now. 

The main reason for having taken that decision is that such change would be considered a breaking change, and it would indeed break all existing automation that relies on a logic like the following:

```
1. tries to create the resource
2. if fails,, do something
```

because the failure logic would no longer execute.

For more context on the discussion around creation commands, please refer to this link: https://github.com/Azure/azure-cli/issues/7613

**Comment by adehaan-darwin-eu** [comment]
Hello @nachoalonsoportillo,

Thank you for your response. Unforntunately I can't agree on your conclusion, even after reading: [#7613](https://github.com/Azure/azure-cli/issues/7613) 
as there is also as post that states my point of view:
-----------
@[tjprescott](https://github.com/tjprescott)
tjprescott
[on Mar 7, 2019](https://github.com/Azure/azure-cli/issues/7613#issuecomment-470631677)
CLI commands are intended to be idempotent (though some fall short of this standard) and thus failing a create because a resource already exists by default is not something we would entertain if for no other reason that it would be a massively breaking change.

However, we are open to the idea of exposing an opt-in existence check like --fail-if-exists that create commands can opt into, and we can even consider allowing users to configure this as TRUE by default through az configure.
-----------

Also your logic is not something that can be followed. Idempotency would not disable the failure checking. Please se the ARM template deployment way of dealing with this.

Another issue is that the az cli commands are not consistent in this context. Therefor if every product group would adhere to the principle of idempotency, we as the end users can predict the execution of the commands.
Idempotency is for instance not something as the az nsg create, because that first deletes an existing one and then creates one, but is like the az group create, this can be executed numerous times and will leave everything intact if it already exists, even with resources in it, and creates if it doesn't exist.

So herewith the request to revisit this for all the az cli commands and communicate the policy with all the product groups and do a code check on compliancy before release.
