### ISSUE TITLE
The command to get just an IP address of a VM is too complicated

### ISSUE THREAD

**Issue by svick** [Azure/azure-cli#2677]
I'm playing with the new CLI and wanted to figure out what is the right command to get the public IP address of one of my VMs, so that I can connect to it from bash using <code>ssh \`az whatever`</code>.

As far as I can tell, the command to do that is:

```bash
ssh `az vm list-ip-addresses -n vm-name --query [0].virtualMachine.network.publicIpAddresses[0].ipAddress -o tsv`
```

Is there a simpler way to do this? If not, I think that's way too complicated for something like this.

**Comment by yugangw-msft** [comment]
@svick, you can use 'az vm show -d'

**Comment by paulpal1** [comment]
More specifically I've had success with '(az vm show --name <name> | ConvertFrom-Json).publicIps'

**Comment by kgopi05** [comment]
Getting below error when querying for ip address of the server
(az vm show --name server01 | ConvertFrom-Json).publicIps
-bash: syntax error near unexpected token `.publicIps'

**Comment by benktesh** [comment]
For vms => az vm list-ip-addresses --output table
For vm by name => az vm list-ip-addresses --output table -n <myvmname>

To view in JSON format remove ' --output table' from the above commands.

**Comment by flik** [comment]
get only local vm ip address

ifconfig eth0
or
ifconfig ens33

You have to type above of interface name to get single ip address.

**Comment by elliott-fwdsec** [comment]
`az vm show -d --name myVM --resource-group myRG --query publicIps`
