### ISSUE TITLE
"az vm disk attach" failure

### ISSUE THREAD

**Issue by cattoni** [Azure/azure-cli#2678]
The command 

`az vm disk attach -g myResourceGroup --vm-name myVM --disk myDataDisk  --new --size-gb 1023 --sku Standard_LRS`

fails with the message:

`Required parameter 'disk.diskSizeGb' is missing (null).`

Actually the disk appears to be attached on the VM but in the portal it is not reported in the disk section of the resource group; accessing the disk in the portal from the disk section of the VM causes troubles.

Same problem if changing the size (e.g.  --size-gb 512)

**Comment by tjprescott** [comment]
What version of the vm module are you running (`az --version`)?

**Comment by cattoni** [comment]
Hi @tjprescott 

```
azure-cli (2.0.1)

acs (2.0.1)
appservice (0.1.1b6)
batch (0.1.1b5)
cloud (2.0.0)
component (2.0.0)
configure (2.0.1)
container (0.1.1b4)
core (2.0.1)
documentdb (0.1.1b2)
feedback (2.0.0)
find (0.0.1b1)
iot (0.1.1b3)
keyvault (0.1.1b6)
network (2.0.1)
nspkg (2.0.0)
profile (2.0.1)
redis (0.1.1b3)
resource (2.0.1)
role (2.0.0)
sql (0.1.1b6)
storage (2.0.1)
vm (2.0.1)

Python (Linux) 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4]
```

**Comment by tjprescott** [comment]
Hi @cattoni I could not reproduce this. Could you run the VM create and the disk attach operation with --debug and email the output to me (trpresco)?

**Comment by cattoni** [comment]
Hi @tjprescott 

I've just rerun the same command (with and without the --debug flag) and it succeeded, in both cases, no problems reported and the disk was actually available in both az CLI and portal.
Actually I made no changes.
My explanation is that some improvements happened on the server side.

Thanks for the support, I would close this issue.
