### ISSUE TITLE
Az Tag Delete Command Removes All Tags

### ISSUE THREAD

**Issue by delarooster** [Azure/azure-cli#26787]
### Describe the bug

In reading the documentation it appears that should I provide an input for the parameter `--name` the intended action should be to remove only that one tag, but instead deletes all tags on the resource.  I specifically was testing the command against a resource group, in this instance.

https://learn.microsoft.com/en-us/cli/azure/tag?view=azure-cli-latest#az-tag-delete

### Related command

` az tag update --name $tag_key --resource-id $resource_id --yes`

### Errors

All tags on resource group are deleted, not just the named ones

### Issue script & Debug output

Results are that all tags are removed, not just the named ones

### Expected behavior

Only the named tag(s) should be removed

### Environment Summary

"azure-cli": "2.49.0",
  "azure-cli-core": "2.49.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "azure-devops": "0.26.0",
    "azure-iot": "0.21.2",
    "bastion": "0.2.4",
    "kusto": "0.5.0",
    "managementpartner": "0.1.3"
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@delarooster Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@delarooster Our docs clearly says that the below command `Delete a predefined tag from the subscription not associated with a resource or having no tag values.`

>az tag delete --name MyTag

While all the other commands in `az tag delete` command with an id **deletes the entire set of tags** on a resource, resource group or subscription.

Instead you should be using the `az tag update` command with operation **delete** parameter as shown below:

> **az tag update --resource-id /subscriptions/{sub-id} --operation merge --tags key1=value1 key3=value3**

More Info [here](https://learn.microsoft.com/en-us/cli/azure/tag?view=azure-cli-latest#az-tag-update). Hope this helps.

**Comment by navba-MSFT** [comment]
@delarooster The action is currently pending on you to try the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
