### ISSUE TITLE
Issue with metadata in cirrusCreationTime

### ISSUE THREAD

**Issue by ksadhna** [Azure/azure-cli#26796]
### Describe the bug

Adding metadata to cirrusCreationTime in Json file is throwing this error :

("(InvalidRequestContent) The request content was invalid and could not be deserialized: 'Could not find member 'metadata' on object of type 'DeploymentParameterDefinition'. Path 'properties.parameters.cirrusCreationTime.metadata', line 1, position 8724.'.\nCode: InvalidRequestContent\nMessage: The request content was invalid and could not be deserialized: 'Could not find member 'metadata' on object of type 'DeploymentParameterDefinition'. Path 'properties.parameters.cirrusCreationTime.metadata', line 1, position 8724.'.",)

### Related command

azure powershell command to run a script

### Errors

("(InvalidRequestContent) The request content was invalid and could not be deserialized: 'Could not find member 'metadata' on object of type 'DeploymentParameterDefinition'. Path 'properties.parameters.cirrusCreationTime.metadata', line 1, position 8724.'.\nCode: InvalidRequestContent\nMessage: The request content was invalid and could not be deserialized: 'Could not find member 'metadata' on object of type 'DeploymentParameterDefinition'. Path 'properties.parameters.cirrusCreationTime.metadata', line 1, position 8724.'.",)

### Issue script & Debug output

NA

### Expected behavior

Above error should not be thrown

### Environment Summary

azure-cli                         2.46.0 *

core                              2.46.0 *
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\ksadhana\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

### Additional context

NA

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
