### ISSUE TITLE
microsoft.insights registration issue

### ISSUE THREAD

**Issue by resilientit** [Azure/azure-cli#26799]
### Describe the bug

unable to register the Resource Provider microsoft.insights on one of our client tenants. Stuck on Registering status indefinitely. Subscription ID = d39e851a-2331-441b-a05f-08b8f7951e9a

### Related command

Register-AzResourceProvider -ProviderNamespace microsoft.insights
Also tried the same command using AzureRM
Also tried in the Azure portal

### Errors

Subscription Registering Resource Provider
'Register' operation check timed out on Resource Provider 'microsoft.insights', please refresh resource providers list to check for registration status
20 hours ago

Subscription Unregistering Resource Provider
'Unregister' operation check timed out on Resource Provider 'microsoft.insights', please refresh resource providers list to check for registration status
20 hours ago

### Issue script & Debug output

[az-cli-log.txt](https://github.com/Azure/azure-cli/files/11925845/az-cli-log.txt)

ProviderNamespace : microsoft.insights
RegistrationState : Registering
ResourceTypes     : {components, components/query, components/metadata, components/metrics...}
Locations         : {East US, South Central US, North Europe, West Europe...}

DEBUG: 8:14:41 AM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning
default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Resources:6.7.0; CommandName: Register-AzResourceProvider; PSVersion: 5.1.19041.3031;
 IsSuccess: True; Duration: 00:00:10.9662072
DEBUG: 8:14:41 AM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning
default value [True].
DEBUG: 8:14:41 AM - RegisterAzureProviderCmdlet end processing.

### Expected behavior

I expect the Resource Provider to register like it should

### Environment Summary

PS C:\Windows\system32> Get-InstalledModule -Name Az

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
10.0.0               Az                                  PSGallery            Microsoft Azure PowerShel

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please open this issue in azure-powershell repo.

**Comment by malindhorst** [comment]
> Please open this issue in azure-powershell repo.

Hi @yonzhan , actually this is also happening on azure-cli:

`az provider show --namespace microsoft.insights -o table                                                                                                                                                                  

Namespace           RegistrationPolicy    RegistrationState
------------------  --------------------  -------------------
microsoft.insights  RegistrationRequired  Registering`

Same behaviour as described by @resilientit for nearly 24 hours stuck in Register state.

**Comment by CraigComeOnThisNameCantBeTaken** [comment]
I am also having this problem. It has prevented our first release unfortunately
