### ISSUE TITLE
Using latest version to deploy Azure template spec and error prompts for templateLink parameter 

### ISSUE THREAD

**Issue by chuckz1321** [Azure/azure-cli#26798]
### Describe the bug

When using "az deployment group create" to depoly a template spec, there will be errors but there's no "mode" parameter under the templateLink field. 
![image](https://github.com/Azure/azure-cli/assets/33536264/0487d62e-3b67-4ae6-9b11-7dd57bd7f741)

This will hinder the deployment on GitHub Action and will not able to execute the following actions. 

We found that the latest version has this issue but we won't see those error in 2.33.1. 

Could you please help to find out how to avoid this error messaging prompting? IMO, it should not prompt. 

### Related command

az deployment group create

### Errors

![image](https://github.com/Azure/azure-cli/assets/33536264/4921e73a-31a3-470a-9ca5-3ab2a446c185)
![image](https://github.com/Azure/azure-cli/assets/33536264/1b7b93db-e351-4bea-b9d5-c6de06ba6090)

### Issue script & Debug output

cli.knack.cli: Command arguments: ['deployment', 'group', 'create', '--resource-group', '20230602spec', '--name', 'clitest001', '--template-spec', '/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Resources/templateSpecs/mainSpec/versions/1.0', '--parameters', '.\\azuredeploy.parameter.dev.json', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01A3A460>, <function OutputProducer.on_global_arguments at 0x01B08BF8>, <function CLIQuery.on_global_arguments at 0x01B27850>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'deployment': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: resource                  0.014        47       209
cli.azure.cli.core: Total (1)                 0.014        47       209
cli.azure.cli.core: Loaded 47 groups, 209 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : deployment group create
cli.azure.cli.core: Command table: deployment group create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03DCB3D0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\chenzhang\.azure\commands\2023-07-01.16-40-22.deployment_group_create.31492.log'.
az_command_data_logger: command args: deployment group create --resource-group {} --name {} --template-spec {} --parameters {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03DF1538>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03E114A8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03E116A0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01B08C40>, <function CLIQuery.handle_query_parameter at 0x01B27898>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03E11658>]
azure.mgmt.resource.resources._serialization: mode is not a known attribute of class <class 'azure.mgmt.resource.resources.v2022_09_01.models._models_py3.TemplateLink'> and will be ignored
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\chenzhang\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\chenzhang\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.partner.microsoftonline.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://microsoftgraph.chinacloudapi.cn/oidc/userinfo', 'authorization_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/kerberos', 'tenant_region_scope': 'AS', 'cloud_instance_name': 'partner.microsoftonline.cn', 'cloud_graph_host_name': 'graph.chinacloudapi.cn', 'msgraph_host': 'microsoftgraph.chinacloudapi.cn', 'rbac_url': 'https://pas.chinacloudapi.cn'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.chinacloudapi.cn//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.chinacloudapi.cn//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: f21926d5-5aee-440b-89d5-b49d05c1de45
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.chinacloudapi.cn/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Resources/templateSpecs/mainSpec/versions/1.0?api-version=2021-05-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'eb1b8bc3-17ea-11ee-816c-6ca1005b8e7f'
cli.azure.cli.core.sdk.policies:     'CommandName': 'deployment group create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --template-spec --parameters --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.49.0 (MSI) azsdk-python-azure-mgmt-resource/22.0.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.chinacloudapi.cn:443
urllib3.connectionpool: https://management.chinacloudapi.cn:443 "GET /subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Resources/templateSpecs/mainSpec/versions/1.0?api-version=2021-05-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'f69173a8-b379-432d-aacc-9709d83e6404'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '14998'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'b4103235-83f8-4094-99e4-1d90981bc681'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CHINAEAST:20230701T084025Z:b4103235-83f8-4094-99e4-1d90981bc681'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Sat, 01 Jul 2023 08:40:24 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "location": "chinanorth2",
  "tags": {},
  "properties": {
    "mainTemplate": {
      "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
      "contentVersion": "1.0.0.0",
      "parameters": {
        "location": {
          "type": "string",
          "defaultValue": "westus2",
          "metadata": {
            "description": "Specify the location for the resources."
          }
        },
        "storageAccountType": {
          "type": "string",
          "defaultValue": "Standard_LRS",
          "metadata": {
            "description": "Specify the storage account type."
          }
        }
      },
      "variables": {
        "appServicePlanName": "[format('plan{0}', uniquestring(resourceGroup().id))]"
      },
      "resources": [
        {
          "type": "Microsoft.Web/serverfarms",
          "apiVersion": "2022-09-01",
          "name": "[variables('appServicePlanName')]",
          "location": "[parameters('location')]",
          "sku": {
            "name": "B1",
            "tier": "Basic",
            "size": "B1",
            "family": "B",
            "capacity": 1
          },
          "kind": "linux",
          "properties": {
            "perSiteScaling": false,
            "reserved": true,
            "targetWorkerCount": 0,
            "targetWorkerSizeId": 0
          }
        },
        {
          "type": "Microsoft.Resources/deployments",
          "apiVersion": "2022-09-01",
          "name": "createStorage",
          "properties": {
            "mode": "Incremental",
            "templateLink": {
              "id": "/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Resources/templateSpecs/linkdedSpec/versions/1.0"
            },
            "parameters": {
              "storageAccountType": {
                "value": "[parameters('storageAccountType')]"
              }
            }
          }
        }
      ]
    }
  },
  "systemData": {
    "createdBy": "chenzhang@mcpod.partner.onmschina.cn",
    "createdByType": "User",
    "createdAt": "2023-06-07T02:55:37.9478267Z",
    "lastModifiedBy": "chenzhang@mcpod.partner.onmschina.cn",
    "lastModifiedByType": "User",
    "lastModifiedAt": "2023-06-07T02:55:37.9478267Z"
  },
  "id": "/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Resources/templateSpecs/mainSpec/versions/1.0",
  "type": "Microsoft.Resources/templateSpecs/versions",
  "name": "1.0"
}
cli.azure.cli.core.util: attempting to read file .\azuredeploy.parameter.dev.json as utf-8-sig
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.partner.microsoftonline.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://microsoftgraph.chinacloudapi.cn/oidc/userinfo', 'authorization_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/kerberos', 'tenant_region_scope': 'AS', 'cloud_instance_name': 'partner.microsoftonline.cn', 'cloud_graph_host_name': 'graph.chinacloudapi.cn', 'msgraph_host': 'microsoftgraph.chinacloudapi.cn', 'rbac_url': 'https://pas.chinacloudapi.cn'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.chinacloudapi.cn//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.chinacloudapi.cn//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 447f4606-0fe6-4a78-90de-a052b5dedc5f
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.chinacloudapi.cn/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourcegroups/20230602spec/providers/Microsoft.Resources/deployments/clitest001/validate?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '266'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'eb1b8bc3-17ea-11ee-816c-6ca1005b8e7f'
cli.azure.cli.core.sdk.policies:     'CommandName': 'deployment group create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --template-spec --parameters --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.49.0 (MSI) azsdk-python-azure-mgmt-resource/22.0.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"templateLink": {"id": "/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Resources/templateSpecs/mainSpec/versions/1.0"}, "parameters": {"Location": {"value": "chinanorth2"}}, "mode": "Incremental"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.chinacloudapi.cn:443
urllib3.connectionpool: https://management.chinacloudapi.cn:443 "POST /subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourcegroups/20230602spec/providers/Microsoft.Resources/deployments/clitest001/validate?api-version=2022-09-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '62a9031d-a3a2-43dd-b064-4ce4fa2d5164'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '62a9031d-a3a2-43dd-b064-4ce4fa2d5164'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CHINAEAST:20230701T084028Z:62a9031d-a3a2-43dd-b064-4ce4fa2d5164'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Sat, 01 Jul 2023 08:40:27 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Resources/deployments/clitest001","name":"clitest001","type":"Microsoft.Resources/deployments","properties":{"templateLink":{"id":"/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Resources/templateSpecs/mainSpec/versions/1.0","contentVersion":"1.0.0.0"},"templateHash":"13363088331539002512","parameters":{"location":{"type":"String","value":"chinanorth2"},"storageAccountType":{"type":"String","value":"Standard_LRS"}},"mode":"Incremental","provisioningState":"Succeeded","timestamp":"0001-01-01T00:00:00Z","duration":"PT0S","correlationId":"62a9031d-a3a2-43dd-b064-4ce4fa2d5164","providers":[{"namespace":"Microsoft.Web","resourceTypes":[{"resourceType":"serverfarms","locations":["chinanorth2"]}]},{"namespace":"Microsoft.Resources","resourceTypes":[{"resourceType":"deployments","locations":[null]}]}],"dependencies":[],"validatedResources":[{"id":"/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Web/serverfarms/plandpliv4xuk3zj2"},{"id":"/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Resources/deployments/createStorage"},{"id":"/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Storage/storageAccounts/storedpliv4xuk3zj2"}]}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.chinacloudapi.cn/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourcegroups/20230602spec/providers/Microsoft.Resources/deployments/clitest001?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '266'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'eb1b8bc3-17ea-11ee-816c-6ca1005b8e7f'
cli.azure.cli.core.sdk.policies:     'CommandName': 'deployment group create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --template-spec --parameters --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.49.0 (MSI) azsdk-python-azure-mgmt-resource/22.0.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"templateLink": {"id": "/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Resources/templateSpecs/mainSpec/versions/1.0"}, "parameters": {"Location": {"value": "chinanorth2"}}, "mode": "Incremental"}}
urllib3.connectionpool: https://management.chinacloudapi.cn:443 "PUT /subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourcegroups/20230602spec/providers/Microsoft.Resources/deployments/clitest001?api-version=2022-09-01 HTTP/1.1" 201 999
cli.azure.cli.core.sdk.policies: Response status: 201
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '999'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Azure-AsyncOperation': 'https://management.chinacloudapi.cn/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourcegroups/20230602spec/providers/Microsoft.Resources/deployments/clitest001/operationStatuses/08585134060563196098?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '0c943542-338f-4d56-b98e-b063f4f72522'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '0c943542-338f-4d56-b98e-b063f4f72522'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CHINAEAST:20230701T084029Z:0c943542-338f-4d56-b98e-b063f4f72522'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Sat, 01 Jul 2023 08:40:29 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Resources/deployments/clitest001","name":"clitest001","type":"Microsoft.Resources/deployments","properties":{"templateLink":{"id":"/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourceGroups/20230602spec/providers/Microsoft.Resources/templateSpecs/mainSpec/versions/1.0","contentVersion":"1.0.0.0"},"templateHash":"13363088331539002512","parameters":{"location":{"type":"String","value":"chinanorth2"},"storageAccountType":{"type":"String","value":"Standard_LRS"}},"mode":"Incremental","provisioningState":"Accepted","timestamp":"2023-07-01T08:40:29.4015836Z","duration":"PT0.0007235S","correlationId":"0c943542-338f-4d56-b98e-b063f4f72522","providers":[{"namespace":"Microsoft.Web","resourceTypes":[{"resourceType":"serverfarms","locations":["chinanorth2"]}]},{"namespace":"Microsoft.Resources","resourceTypes":[{"resourceType":"deployments","locations":[null]}]}],"dependencies":[]}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.chinacloudapi.cn/subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourcegroups/20230602spec/providers/Microsoft.Resources/deployments/clitest001/operationStatuses/08585134060563196098?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'eb1b8bc3-17ea-11ee-816c-6ca1005b8e7f'
cli.azure.cli.core.sdk.policies:     'CommandName': 'deployment group create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --template-spec --parameters --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.49.0 (MSI) azsdk-python-azure-mgmt-resource/22.0.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.chinacloudapi.cn:443 "GET /subscriptions/f6d66baf-072b-4fbd-ba49-a859981c865f/resourcegroups/20230602spec/providers/Microsoft.Resources/deployments/clitest001/operationStatuses/08585134060563196098?api-version=2022-09-01 HTTP/1.1" 200 140
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '14998'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '5e6b8388-bdf3-4d65-8443-fc066384982d'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '5e6b8388-bdf3-4d65-8443-fc066384982d'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CHINAEAST:20230701T084030Z:5e6b8388-bdf3-4d65-8443-fc066384982d'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Sat, 01 Jul 2023 08:40:29 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '140'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"status":"Accepted"}

### Expected behavior

No errors 

### Environment Summary

azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\chenzhang\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by chuckz1321** [comment]
Any update on this issue?

**Comment by zhoxing-ms** [comment]
Same issue as #26112
