### ISSUE TITLE
Date format inconsistent in documentation

### ISSUE THREAD

**Issue by Strobodov** [Azure/azure-cli#26800]
### Describe the bug

The examples on page https://learn.microsoft.com/en-us/cli/azure/billing/invoice?view=azure-cli-latest#az-billing-invoice-download format the date as "YYYY-MM-DD" where the documentation states that date should be formatted as "MM-DD-YYYY"

### Related command

az billing

### Errors

None, it's a documentation bug

### Issue script & Debug output

None

### Expected behavior

Would expect the documentation to be consistent.

### Environment Summary

n/a

### Additional context

The --help flag of az billing invoice list says it should be formatted as "MM-DD-YYYY" (both the --period-end-date and -- period-start-date flags)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Strobodov** [comment]
Also the examples in the commands --help page are inconsistent.
