### ISSUE TITLE
Azure OpenAI specify rate limit in deployment via CLI

### ISSUE THREAD

**Issue by shayben** [Azure/azure-cli#26808]
**Related command**
az cognitiveservices account deployment create

**Is your feature request related to a problem? Please describe.**
Currently need to manually specify rate limit / quota per Azure OpenAI model across deployments, regions and subscriptions. If we manage multiple regions across multiple subscriptions this becomes very time consuming as new models roll out quickly.

**Describe the solution you'd like**
Ability to automate this via parameters in the CLI

**Describe alternatives you've considered**
Manually specifying this in Azure AI Studio under the deployment per resource

**Additional context**
:)

**Comment by navba-MSFT** [comment]
@shayben You can call [az resource update](https://learn.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#az-resource-update) or [az rest](https://learn.microsoft.com/en-US/cli/azure/reference-index?view=azure-cli-latest#az-rest) command to update [CallRateLimit ](https://learn.microsoft.com/en-us/rest/api/cognitiveservices/accountmanagement/accounts/update?tabs=HTTP#callratelimit)property.

**Comment by navba-MSFT** [comment]
@shayben I hope you had a chance to look at my above comment. If you need any further assistance on this issue, please feel free to reopen this thread. We would be happy to help.
