### ISSUE TITLE
Could jp be installed instead of downloaded?

### ISSUE THREAD

**Issue by woakesd** [Azure/azure-cli#26806]
**Related command**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jsntcy** [comment]
@woakesd, could you please share more details?

**Comment by navba-MSFT** [comment]
@woakesd Thanks for reaching out to us and reporting this issue. Please elaborate the issue and the Azure Service and CLI command you are using. This will help us to assist you better. Awaiting your reply.

**Comment by woakesd** [comment]
Actually I can answer my own question! No, because the Alpine version used doesn't include it.

But change the python version to 3.10 and don't specify an alpine version and it's available and the image builds. I haven't tested extensively but I can update ip addresses in a dns zone.

**Comment by navba-MSFT** [comment]
@woakesd I hope you had a chance to look at my above comment. If you need any further assistance on this issue please provide the detailed issue description, your use case, Azure CLI command and the azure service you are using, with debug output. This will help us to assist you better.
