### ISSUE TITLE
JSON parameters are not parsed correctly using CMD

### ISSUE THREAD

**Issue by Thraka** [Azure/azure-cli#2680]
It seems to be parsing this incorrectly and I'm not sure why?

```
az vmss extension set --publisher Microsoft.Azure.Extensions --version 2.0 --name CustomScript --resource-group vmss-test-1 --vmss-name myscaleset --settings '{"commandToExecute": "apt-get -y update && apt-get -y install nginx"}'

az: error: unrecognized arguments: apt-get -y update && apt-get -y install nginx}'
```

**Comment by tjprescott** [comment]
It may be you are not escaping --settings correctly. For example, on Windows it would have to look something like "{\"foo\": \"bar\"}".  

Alternatively, put your settings in a JSON file and then use `--settings @settings.json` and you shouldn't have to worry about the escaping.

**Comment by Thraka** [comment]
It seems that @settings.json is working fine, but it's a lot more annoying for customers if I have to document "run this command but first copy\paste this into a file" instead of just getting it to work. I tried escaping but nothing seems to work.

Does anyone have this working for windows? I would have hoped that the command would be agnostic of OS.

**Comment by tjprescott** [comment]
This is the proper escaping for CMD:
--settings "{\"commandToExecute\": \"apt-get -y update && apt-get -y install nginx\"}"

**Comment by Thraka** [comment]
Those did not work either

```cmd
C:\Users\me>az vmss extension set --publisher Microsoft.Azure.Extensions --version 2.0 --name CustomScript --resource-group vmss-test-1 --vmss-name myscaleset --settings "{ "commandToExecute": "apt-get -y update && apt-get -y install nginx" }"

  az: error: unrecognized arguments: -y update
  usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
      	  [--query JMESPATH]
          {storage,network,batch,sql,vm,appservice,keyvault,snapshot,group,ad,component,vmss,redis,iot,acs,login,role,provider,container,cloud,lock,image,logout,policy,feature,disk,resource,account,documentdb,tag,find,feedback,configure}
          ...
  'apt-get' is not recognized as an internal or external command,
  operable program or batch file.

C:\Users\me>az vmss extension set --publisher Microsoft.Azure.Extensions --version 2.0 --name CustomScript --resource-group vmss-test-1 --vmss-name myscaleset --settings "{ \"commandToExecute\": \"apt-get -y update && apt-get -y install nginx\" }"

  Unterminated string starting at: line 1 column 23 (char 22)
  'apt-get' is not recognized as an internal or external command,
  operable program or batch file.

C:\Users\me>az vmss extension set --publisher Microsoft.Azure.Extensions --version 2.0 --name CustomScript --resource-group vmss-test-1 --vmss-name myscaleset --settings "{ /"commandToExecute/": /"apt-get -y update && apt-get -y install nginx/" }"

  az: error: unrecognized arguments: -y update
  usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {network,vmss,batch,vm,documentdb,configure,storage,tag,keyvault,appservice,cloud,lock,redis,policy,iot,image,role,group,acs,resource,account,container,sql,feature,snapshot,provider,ad,disk,feedback,component,login,find,logout}
          ...
  'apt-get' is not recognized as an internal or external command,
  operable program or batch file.
```

**Comment by tjprescott** [comment]
I can duplicate this issue... for some reason, when you pass the escaped string, it cuts the string off at the && signs and that's why you get the error.

**Comment by Thraka** [comment]
Thanks for confirming, glad to help!

**Comment by tjprescott** [comment]
Changing the label, as this issue can apply to any parameter that accepts JSON using CMD.  The tentative fix I have would allow you to specify:
`--settings "{'foo': 'doo && boo'}"`

This works with CMD and bash (our supported shells). The only technicality is that it isn't strictly JSON because JSON uses double quotes around properties.

**Comment by tjprescott** [comment]
For the meantime, I've confirmed this works:
```
python -m azure.cli vmss extension set --publisher Microsoft.Azure.Extensions --version 2.0 --name CustomScript -g tjp-vmss --vmss-name vmss1 --settings "{\"commandToExecute\": \"apt-get -y update ^&^& apt-get -y install nginx\"}"
```

You need to escape the & with ^, and you have to replace `az` with `python -m azure.cli`.  I will see if we can fix this through a tweak to `az.bat`

**Comment by tbertenshaw** [comment]
Think I'm also experiencing this issue. Using the cli in powershell 6.2. I'm using blob urls with sas tokens. I tried escaping the & but still get this error
```
Unterminated string starting at: line 1 column 15 (char 14)
'sp' is not recognized as an internal or external command,
operable program or batch file.
'spr' is not recognized as an internal or external command,
operable program or batch file.
'sv' is not recognized as an internal or external command,
operable program or batch file.
'sr' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.
operable program or batch file.
'spr' is not recognized as an internal or external command,
operable program or batch file.
'sv' is not recognized as an internal or external command,
operable program or batch file.
'sr' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.
'sp' is not recognized as an internal or external command,
operable program or batch file.
'spr' is not recognized as an internal or external command,
operable program or batch file.
'sv' is not recognized as an internal or external command,
operable program or batch file.
'sr' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.
```

**Variable**
`$customScriptJson ="{\"fileUris\": [\"https://myblobstorage.blob.core.windows.net/scripts/bootstrap.ps1?se=2019-06-01T14%3A54%3A40Z^&sp=r^&spr=https^&sv=2018-03-28^&sr=b^&sig=39vbLOqlSYLVkCYvheGkMGBNtcHCEn/D2VFyhs33J04%3D\",\"https://myblobstorage.blob.core.windows.net/scripts/OctopusFunctions.ps1?se=2019-06-01T14%3A54%3A40Z^&sp=r^&spr=https^&sv=2018-03-28^&sr=b^&sig=vIHeGOkxCrluCmtK6gG2y00Ff5QZVRgyeh1/gW6zXzU%3D\",\"https://myblobstorage.blob.core.windows.net/scripts/LoggingFunctions.ps1?se=2019-06-01T14%3A54%3A40Z^&sp=r^&spr=https^&sv=2018-03-28^&sr=b^&sig=CJNtjQ43iQkDbxKOKfu84wUZs9pgfQLei7Gq/UBdQaU%3D\"],\"commandToExecute\": \"powershell.exe -ExecutionPolicy Unrestricted -File bootstrap.ps1\"}"`

**script**
```
az.cmd vmss extension set --vmss-name $name --name CustomScriptExtension --resource-group $resourceGroupName `
    --publisher Microsoft.Compute `
    --settings $customScriptJson --force-update --verbose
```

**Comment by tjprescott** [comment]
@tbertenshaw yes, that is absolute a Powershell quoting issue. There is nothing the CLI can do about that because the shell processes input before it ever reaches the CLI.

**Comment by tbertenshaw** [comment]
so painful.  Established that saving the string(without the escaped quotes and ampersands to disk then passing that to the settings works.

**Comment by rgherta** [comment]
I am sorry for the flashback but I am having issues passing --indexing-policy to cosmosdb as a string. I get all sorts of errors. I saw this statement 
--settings @settings.json

But I do not understand how exactly should I use it... let's say I save my json to disk as "C:\path\my.json" . How exactly do I pass this file as parameter? If I put the part or the path as a string it simply fails at first character. what exactly is that fancy @ sign
