### ISSUE TITLE
Installs unlicensed binary-only agent extension for secure boot

### ISSUE THREAD

**Issue by credbbl** [Azure/azure-cli#26803]
### Describe the bug

If I create a secure boot VM, azure-cli instructs the agent to install the unlicensed and binary-only agent extension `Microsoft.Azure.Security.LinuxAttestation.GuestAttestation` without asking the user.

I intend to fix that once and for all in the whole Debian distribution by disabling all extensions in the agent if not disabled by default.

### Related command

`az vm create --security-type TrustedLaunch --enable-secure-boot`

### Errors

Installs `Microsoft.Azure.Security.LinuxAttestation.GuestAttestation`.

```
2023-07-03T07:37:38.695057Z INFO ExtHandler [Microsoft.Azure.Security.LinuxAttestation.GuestAttestation-1.0.1.21] Target handler state: enabled [incarnation 2]
2023-07-03T07:37:38.695276Z INFO ExtHandler [Microsoft.Azure.Security.LinuxAttestation.GuestAttestation-1.0.1.21] [Enable] current handler state is: notinstalled
2023-07-03T07:37:38.695509Z INFO ExtHandler [Microsoft.Azure.Security.LinuxAttestation.GuestAttestation-1.0.1.21] Downloading extension package: https://umsavq3r0szsqptncs4x.blob.core.windows.net/4251b645-6705-d410-2ae4-d2b2db7d31f3/4251b645-6705-d410-2ae4-d2b2db7d31f3_1.0.1.21.zip
```

### Issue script & Debug output

Unrelated

### Expected behavior

No extension is installed without the users consent.

### Environment Summary

azure-cli latest

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@sirfamelin @Bab95 Could you please take a look at this issue?

**Comment by Bab95** [comment]
Guest Attestation Extension installation is enabled by default as Trusted Launch as default initiative. In case user wishes to opt out there's a flag available for it. 
**--disable-integrity-monitoring** 

https://learn.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create

**Comment by credbbl** [comment]
I know that it can be disabled. But as one of the responsible for the Debian distribution I care more about the default.

**Comment by Bab95** [comment]
why it's a concern for a single distro?

**Comment by credbbl** [comment]
Why not? The software as it is now is neither distributable, security supported, nor governed by any of the checks that we as a distribution do.

**Comment by hilaryw29** [comment]
Hi @GabstaMSFT, do you mind taking a look at this? Thanks!

**Comment by Howie425** [comment]
@Howie425

**Comment by GabstaMSFT** [comment]
@credbbl we are having internal discussion on this.

**Comment by jaboutboul** [comment]
Hi Bastian as mentioned in our chat, our engineering teams are looking into this and discussing options.

**Comment by jaboutboul** [comment]
Hello @credbbl, we will be shifting the agent in question (GA) to opt-in by default. The new behavior will require the user to specify “—enable-integrity-monitoring” if they wish GA to be installed. Auto-upgrades will be disabled by default as well and will require users to opt-in via “—enable-integrity-monitoring-autoupgrade.”

It is a generally accepted consensus by us moving forward that all agents/extensions should be only opt-in by default.
