### ISSUE TITLE
Microsoft.Insights / microsoft.insights is taking hours to Register in Azure Portal

### ISSUE THREAD

**Issue by WVDAdminTF** [Azure/azure-cli#26804]
### Describe the bug

microsoft.insights is taking hours to Register in Azure Portal

### Related command

az provider register --namespace 'Microsoft.Insights'

### Errors

No errors - showing Registering since hours

### Issue script & Debug output

microsoft.insights is taking hours to Register in Azure Portal

### Expected behavior

It should not take more than 10 minutes to register

### Environment Summary

azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Extensions:
ai-examples                        0.2.5
ml                                2.18.0
ssh                                1.1.6

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/usr/bin/python3.9'
Extensions directory '/home/mod/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Feb  8 2023, 03:39:52) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

microsoft.insights is taking hours to Register in Azure Portal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by WVDAdminTF** [comment]
![image_2023-07-03_154110853](https://github.com/Azure/azure-cli/assets/84956733/b3880d74-5b8b-4239-9485-eab204eeca66)

**Comment by zhoxing-ms** [comment]
Same as #26801
