### ISSUE TITLE
az login error argument --password/-p: expected one argument after upgrading to azure cli to 2.50.0-1~focal

### ISSUE THREAD

**Issue by cabral1888** [Azure/azure-cli#26815]
### Describe the bug

When running the command from CI in the previous version `2.49.0-1~focal` it did work:
```
az login \
  --service-principal \
  --tenant $AZURE_SP_TENANT \
  -u $AZURE_SP \
  -p $AZURE_SP_PASSWORD
```

However, since my CI installs the Azure CLI for every new execution (it always gets the latest version), now I'm using the version `2.50.0-1~focal` and I'm getting the error: 
```
argument --password/-p: expected one argument

Examples from AI knowledge base:
...
```
Is that an error I'm getting? Or have the API changed?

Could anyone help me with it? I really appreciate!

### Related command

`az login \
  --service-principal \
  --tenant $AZURE_SP_TENANT \
  -u $AZURE_SP \
  -p $AZURE_SP_PASSWORD`

### Errors

argument --password/-p: expected one argument

### Issue script & Debug output

Since it's running from a CI perspective, I cannot run the command using different flags

### Expected behavior

I would expect a JSON with all the subscriptions I'm logged in:
```
 [{
    "cloudName": "AzureCloud",
    "homeTenantId": "*",
    "id": "*",
    "isDefault": true,
    "managedByTenants": [
      {
        "tenantId": "TENANT_ID"
      }
    ],
    "name": "SUBSCRIPTION_1_NAME",
    "state": "Enabled",
    "tenantId": "*",
    "user": {
      "name": "*",
      "type": "servicePrincipal"
    }
  },{..}, ... ]
```

### Environment Summary

Since it's running from a CI perspective, I cannot run the command using different flags

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by cabral1888** [comment]
Hey team, nevermid. Just discovered the environment variable for password was not defined.
