### ISSUE TITLE
`az devops` cli in ADO YAML pipeline error "TF401019: The Git repository with name or identifier <wikiIdentifierguid> does not exist or you do not have permissions for the operation you are attempting."

### ISSUE THREAD

**Issue by prattak86** [Azure/azure-cli#26811]
### Describe the bug

When using the `az devops` cli tool to invoke the Azure DevOps Wiki API (or any other Azure DevOps API for that matter), I get the output error:

"TF401019: The Git repository with name or identifier [wikiIdentifierguid] does not exist or you do not have permissions for the operation you are attempting."

_Please note I have replaced an actual GUID for the Wiki Identifier with `[wikiIdentifierguid]` here and below_

My use case is that I am trying to publish Release Notes as a markdown file (ReleaseNotes.md) in a sub-page to the same Project Wiki from which the notes were queried. I know the process works as I have done this manually via the `az devops invoke` command from my local desktop environment.

I have been working through this issue for several days, trying many different approaches. I am confident my script is correct, or at least close enough, to have gotten different and more reasonable errors by now. I have attempted to use both Microsoft hosted Windows and Ubuntu latest agents, providing explicit paths, attempted several other techniques. I have provided the appropriate build service accounts full access to the repository and using the System.AccessToken where needed.

However, it is interesting that the `az devops wiki list --scope project --project "MY_PROJECT"` works by getting back details about the Wiki page and guid, so at least I can verify that it _should_ work. This command is run exactly one line above the `az devops wiki create` command. See inline script below:

`
az devops configure --defaults organization=https://dev.azure.com/myOrg project="MY_PROJECT"
az devops wiki list --scope project --project "MY_PROJECT"  # this command works well
az devops wiki page create --path '$(wikipathroot)/$(RELEASE_TAG)-$(Build.BuildId)' --wiki MY_PROJECT.wiki --file-path '$(Build.ArtifactStagingDirectory)/ReleaseNotes.md' --debug
`

I have see some open issues related to documentation for `az devops cli` command - is this related?

### Related command

`
az devops configure --defaults organization=https://dev.azure.com/myOrg project="MY_PROJECT"
az devops wiki list --scope project --project "MY_PROJECT"  # this command works well
az devops wiki page create --path '$(wikipathroot)/$(RELEASE_TAG)-$(Build.BuildId)' --wiki MY_PROJECT.wiki --file-path '$(Build.ArtifactStagingDirectory)/ReleaseNotes.md' --debug
`

### Errors

DEBUG: azext_devops.devops_sdk.client: Response content: b'{"$id":"1","innerException":null,"message":"TF401019: The Git repository with name or identifier [wikiIdentifierguid] does not exist or you do not have permissions for the operation you are attempting.","typeName":"Microsoft.TeamFoundation.Git.Server.GitRepositoryNotFoundException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitRepositoryNotFoundException","errorCode":0,"eventId":3000}'

DEBUG: msrest.exceptions: TF401019: The Git repository with name or identifier [wikiIdentifierguid] does not exist or you do not have permissions for the operation you are attempting.

- # There are several more of these instances of errors, but I grabbed the first two in the log. All errors are the same but occur at different times.

### Issue script & Debug output

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/azcliextensions/azure-devops/azext_devops/dev/common/exception_handler.py", line 18, in azure_devops_exception_handler
    raise CLIError(ex)
knack.util.CLIError: TF401019: The Git repository with name or identifier [wikiIdentifierguid] does not exist or you do not have permissions for the operation you are attempting.

ERROR: cli.azure.cli.core.azclierror: TF401019: The Git repository with name or identifier [wikiIdentifierguid] does not exist or you do not have permissions for the operation you are attempting.
ERROR: az_command_data_logger: TF401019: The Git repository with name or identifier [wikiIdentifierguid] does not exist or you do not have permissions for the operation you are attempting.
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f7c30d6aef0>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 0.855 seconds (init: 0.176, invoke: 0.679)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 3534 in cache
WARNING: telemetry.check: Negative: The /home/vsts/.azure/telemetry.txt was modified at 2023-07-03 22:37:43.458169, which in less than 600.000000 s
##[debug]Exit code 1 received from tool '/usr/bin/bash'
##[debug]STDIO streams have closed for tool '/usr/bin/bash'
##[error]Bash exited with code '1'.
##[debug]Processed: ##vso[task.issue type=error;]Bash exited with code '1'.
##[debug]task result: Failed
##[debug]Processed: ##vso[task.complete result=Failed;done=true;]
Finishing: Publish Release Notes to Wiki

### Expected behavior

I would expect to see something other than the TF401019 error code, or at least an attempt to PUT content up on the Wiki via API.

### Environment Summary

Microsoft-hosted Ubuntu agent

`vm-image: 'ubuntu-latest'
`

`az extension add --name azure-devops`
"WARNING: Extension 'azure-devops' 0.26.0 is already installed."

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by prattak86** [comment]
Any updates on this issue?

**Comment by Arvindgade** [comment]
Hi @prattak86,We are trying to repro the issue and ran the below command, Could you please help me here are you considering the **id** parameter as a Guid?
![image](https://github.com/Azure/azure-cli/assets/118356664/ee7373f9-5b39-41ea-9242-f3a7bf8df7ba)

**Comment by pareion** [comment]
Any update on this issue?

I'm having the same issue using the `az repos pr list ...` and trying to checkout pull requests from repositories in other projects than the pipeline itself.

**Comment by v-anvashist** [comment]
Hi @pareion  Are u facing this issue in Ubuntu ? If possible can you please try in windows also?

**Comment by v-anvashist** [comment]
@pareion  I am not able to repro this in windows and it is working fine for me.Please send the error screenshots.

**Comment by pareion** [comment]
@v-anvashist We're running Ubuntu22.04 in our pipelines and using the System.AccessToken from the pipeline to authenticate with the Azure Cli.

I did however figure out a solution and it's very... weird.

The $(System.AccessToken) you get from the pipeline has the same permissions as the `X Build Service (organization)` identity in Azure DevOps. However the scope of it is not determined by those permissions it's determined by the repository the pipeline exists in AND the repository you checkout in the given job in the pipeline.

So in my case the solution was to add several `- checkout git://$(Project Name)/$(Repository name)` in the pipeline job, which caused the repository scopes to be added to the $(System.AccessToken).

I then encoded that token with the following method:
`$encodedToken = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes(":$(System.AccessToken)"))`

And passed it as a header parameter to the rest call:
 $headers = @{
            "Authorization" = "Basic $encodedToken"
          }
`Invoke-RestMethod ...  -Headers $headers`

**Comment by prattak86** [comment]
> @v-anvashist We're running Ubuntu22.04 in our pipelines and using the System.AccessToken from the pipeline to authenticate with the Azure Cli.
> 
> I did however figure out a solution and it's very... weird.
> 
> The $(System.AccessToken) you get from the pipeline has the same permissions as the `X Build Service (organization)` identity in Azure DevOps. However the scope of it is not determined by those permissions it's determined by the repository the pipeline exists in AND the repository you checkout in the given job in the pipeline.
> 
> So in my case the solution was to add several `- checkout git://$(Project Name)/$(Repository name)` in the pipeline job, which caused the repository scopes to be added to the $(System.AccessToken).
> 
> I then encoded that token with the following method: `$encodedToken = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes(":$(System.AccessToken)"))`
> 
> And passed it as a header parameter to the rest call: $headers = @{ "Authorization" = "Basic $encodedToken" } `Invoke-RestMethod ... -Headers $headers`

I started to read "...solution and it's very... weird" and was thinking "okay, let's see how weird he's talking..." But reading it I realize that is quite strange. So is it basically like you have to get the repository permission scope context from the separate repository so that the `$(System.AccessToken)` gets the appropriate permissions? (Hope I understood that correctly) That is interesting, as well as working around it with a REST call.

I personally have ended up working with a different solution altogether because we decided that publishing the Release Notes to the same project's Wiki was convenient, but not really that important. So, I wrote a semi-complicated shell script that did similar things and we published results (Markdown file) to Azure Artifacts to be consumed and presented by a secondary service.

From my perspective, this is not an issue for me because I abandoned the approach. However, @pareion your solution seems like a nice workaround. Makes sense. I will consider how this could solve issues in the future! Thanks for contributing.

All of this to say... I wish there was a more standard way in ADO for presenting Release Notes. GitHub seems to have solved this.

**Comment by albertospelta** [comment]
@prattak86 @pareion I've resolved the issue by following the suggestions provided here https://developercommunity.visualstudio.com/t/Azure-Pipeline-Agent-unable-to-access-Wi/10456012#T-N10456686 . To obtain a token with the required permissions for the repo, I added the `resources` and `uses` to the YAML pipeline.

**Comment by Matthew0x** [comment]
I faced a similar (the same error message) issue when also using the CLI programmatically.

Specifically, when attempting to use the **az cli** with authentication through the either **Build Account** or the **Service Connection** in a CI/CD pipeline task (the credentials are fetched automatically depending on the task type set, OR the env variable, but it appears that one takes precedence over another). These are **not** the same.

This is because the **Build Account** was used for the step. The permissions matched, with the pipeline running until it reached the custom CLI commands in CI/CD, which would fail for this ambiguous reason.
In my case it was... the license. The license on the Service Connection's Service Principal (permission settings are not sufficient alone).

Make sure it's at least **Basic** or else it will not be able to read repositories.
This error is quite misleading, especially if you do not attempt to access the repositories in any capacity through the CLI.

Ref:
https://learn.microsoft.com/en-us/azure/devops/pipelines/security/secure-access-to-repos?view=azure-devops&tabs=yaml
https://learn.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops
