### ISSUE TITLE
az disk list fails for AzureUSGovernment

### ISSUE THREAD

**Issue by kfiresmith** [Azure/azure-cli#2681]
Using the latest Docker image, I get the following error when trying to create or list a disk:
`he resource type could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'.`

I'm a new Azure user, in the AzureUSGovernment environment, and have successfully logged in at the point I am hit with this problem.

I am trying to follow [this guide](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/classic/create-upload-vhd?toc=%2fazure%2fvirtual-machines%2flinux%2fclassic%2ftoc.json).

`bash-4.3# az --version
azure-cli (2.0.1+dev)

acr (0.1.1b5+dev)
acs (2.0.1+dev)
appservice (0.1.1b6+dev)
batch (0.1.1b5+dev)
cloud (2.0.0+dev)
component (2.0.0+dev)
configure (2.0.1+dev)
container (0.1.1b4+dev)
core (2.0.1+dev)
dla (0.0.1b1+dev)
dls (0.0.1b1+dev)
documentdb (0.1.1b2+dev)
feedback (2.0.0+dev)
find (0.0.1b1+dev)
iot (0.1.1b3+dev)
keyvault (0.1.1b6+dev)
lab (0.0.1b1+dev)
monitor (0.0.1b1+dev)
network (2.0.1+dev)
nspkg (2.0.0+dev)
profile (2.0.1+dev)
redis (0.1.1b3+dev)
resource (2.0.1+dev)
role (2.0.0+dev)
sql (0.1.1b6+dev)
storage (2.0.1+dev)
taskhelp (0.1.1b3+dev)
vm (2.0.1+dev)

Python (Linux) 3.5.2 (default, Dec 27 2016, 21:33:11) 
[GCC 5.3.0]
`

`requests.packages.urllib3.connectionpool : Starting new HTTPS connection (1): management.usgovcloudapi.net
requests.packages.urllib3.connectionpool : https://management.usgovcloudapi.net:443 "GET /subscriptions/******/providers/Microsoft.Compute/disks?api-version=2016-04-30-preview HTTP/1.1" 404 164
msrest.http_logger : Response status: 404
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-failure-cause': 'gateway'
msrest.http_logger :     'x-ms-request-id': '95e0c982-8d77-4b89-9cd3-c0c0846af978'
msrest.http_logger :     'x-ms-correlation-request-id': '95e0c982-8d77-4b89-9cd3-c0c0846af978'
msrest.http_logger :     'x-ms-routing-request-id': 'USDODEAST:20170330T193244Z:95e0c982-8d77-4b89-9cd3-c0c0846af978'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Date': 'Thu, 30 Mar 2017 19:32:44 GMT'
msrest.http_logger :     'Content-Length': '164'
msrest.http_logger : Response content:
msrest.http_logger : b'{"error":{"code":"InvalidResourceType","message":"The resource type could not be found in the namespace \'Microsoft.Compute\' for api version \'2016-04-30-preview\'."}}'
msrest.exceptions : The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'.
The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'.
`

**Comment by yugangw-msft** [comment]
Same thing #2190
